### ISSUE TITLE
Animation in BlendSpace1D only plays the first frame of animation

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#74706] opened 2023-03-10 08:39 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, OSX 12.6.1

### Issue description

I have two animations ("idle_left" and "idle_right") which are playing fine in the AnimationPlayer.

https://user-images.githubusercontent.com/327257/224265219-afcd10a2-a41d-45bd-be9c-bd05d3cd2a62.mp4

When I use these animations in a BlendSpace1D in an AnimationTree, only the first frame of each animation seems to be played:

https://user-images.githubusercontent.com/327257/224265931-e7b1389a-d2fe-4a74-bab1-6c81d0acdb3e.mp4

### Steps to reproduce

I have just added two animations to the AnimationPlayer. Then in the AnimationTree I added a state machine as root and added a BlendSpace1D node to blend both animations. Then on the left side i added the "idle_left" animation and on the right side I added the "idle_right" animation. 

### Minimal reproduction project

[animation_reproducer.zip](https://github.com/godotengine/godot/files/10940130/animation_reproducer.zip)

**Comment by kleonc** [comment] 2023-03-14 17:25
- The issue seems to be a mismatch of the update mode (discrete vs continous) for the `frame` track between the `RESET` and the other animations.
- Another issue is in the `RESET` animation `hframes` is not set properly (it's `1`) which leads to errors after fixing the issue in the point up above (like `Index p_frame = 9 is out of bounds (vframes * hframes = 1).`). Setting it to `11` within the `RESET` animation as in the other animaitons make these go away.

So everything seems to be working correctly, when it's being setup accordingly.

@TokageItLab The question is whether all this is intended/expected behavior. If it is, then the issue in here is that it's not anyhow indicated to the user what's the issue with the original setup. No error, no warning, nothing.

**Comment by derkork** [comment] 2023-03-15 08:11
Thanks a lot for digging into this and telling me. I would probably not have found this in a million years. For me the editor now shows a warning about the mismatch of the update mode (i'm not sure if this is new or if I just missed it the first time around). As for other warnings, I'm not sure what kind of warning the editor could give as this would require the editor to sort of guess the user's intention. 

Could you maybe give some details into how you approached fixing this? Maybe a small "when your animation doesn't work in BlendSpace"-checklist could be made out of this, that I could add to the tutorial for the  animation tree.

**Comment by TokageItLab** [comment] 2023-03-15 08:41
An error should be notified if the update mode is mismatched, but the user may miss it if there are many other notifications. Well, it would be nice to add a troubleshooting section on animation to the documentation.

**Comment by derkork** [comment] 2023-03-15 08:48
If you can suggest a few steps I'll happily add it to the documentation 👍

**Comment by kleonc** [comment] 2023-03-15 10:37
> For me the editor now shows a warning about the mismatch of the update mode (i'm not sure if this is new or if I just missed it the first time around). As for other warnings, I'm not sure what kind of warning the editor could give as this would require the editor to sort of guess the user's intention.
> 
> Could you maybe give some details into how you approached fixing this?

@derkork Well, I've actually seen the warning about the mismatched update modes some other time before when testing / playing with the AnimationTree. So I remembered it could be an issue, hence that's what I've checked. But [within the provided MRP](https://github.com/godotengine/godot/files/10940130/animation_reproducer.zip) I still can't make such warning to show up. Nothing right after opening, nothing after trying to tweak many different settings. Just tried to trigger this warning for like 5 minutes. No luck.

---

> An error should be notified if the update mode is mismatched, but the user may miss it if there are many other notifications.

@TokageItLab As I wrote up above, I've seen such warning earlier but not in the MRP provided in here. It's not like I've missed it, it just never shown up for me in here (I try to check the warnings before clearing them, especially when testing an issue).

---

>Maybe a small "when your animation doesn't work in BlendSpace"-checklist could be made out of this, that I could add to the tutorial for the animation tree.

> Well, it would be nice to add a troubleshooting section on animation to the documentation.

> If you can suggest a few steps I'll happily add it to the documentation +1

Sure it would be nice to have such section. Myself I'm not aware of all the AnimationTree's quirks / expectations etc.
Of course it would be nice if as much info/warnings could be directly provided to the user within the editor.

**Comment by kleonc** [comment] 2023-03-15 10:47
After looking at the source code I was able to trigger the error (`Value track: Sprite2D:frame with different update modes are blended. Blending prioritizes Discrete mode, so other update mode tracks will not be blended.`) pretty much immediately: it's shown only when the new track (being blended in I suppose) is discrete and the previous one was not. The other way around it's not triggered. Meaning for update modes:

- In `RESET` discrete, in the other animation continous: the error is not trigerred (like in the MRP).
- In `RESET` continous, in the other animation discrete: the error is trigerred.

**Comment by TokageItLab** [comment] 2023-03-15 11:40
Oh sure, I may be flagging it wrong. I'll take a look at it later.

**Comment by TokageItLab** [comment] 2024-07-09 00:56
Closed by https://github.com/godotengine/godot/pull/86629

**Closed by TokageItLab** 2024-07-09 00:56 UTC
Labels: usability, documentation, topic:animation
