### ISSUE TITLE
Tooltip for the hex text box in the color selector window prevents typing

### ISSUE THREAD

**Issue by leftbones** [godotengine/godot#80433] opened 2023-08-08 21:07 UTC
### Godot version

4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11

### Issue description

In the color selection window (such as 'BG Color' in the 'StyleBoxFlat' inspector, if you click into the 'Hex' input field and start typing, but leave your mouse over the box, you can start typing but once the tooltip shows up, all typing is blocked until the tooltip is dismissed.

### Steps to reproduce

See issue description.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-08-09 09:14
Thank you for reporting! This is a duplicate of:
* #79500

Consolidating there

**Closed by AThousandShips** 2023-08-09 09:14 UTC
