### ISSUE TITLE
Light from SpotLights sometimes disappear when in view.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#24599] opened 2018-12-26 06:25 UTC
**Godot version:**

Godot 3.1 Alpha 4

**OS/device including version:**

OS: Windows 10 Pro
GPU: nVidia GeForce GT 520M

**Issue description:**

Just look at the gif below.
![spotlight](https://user-images.githubusercontent.com/8316851/50434538-27995e00-0910-11e9-9ecd-deee7e2efe9a.gif)

Notes:

- There are a lot of spotlight inside the scene, it's 30 of them

- This scene is made using Blender, and I import it to Godot using Better Collada Exporter

- The Lights is initially a DirectionalLight (when open dae file in Godot) and I change the type to SpotLight

- After changing to SpotLight I save the scene as tscn.

- The floor and walls are in front cullling mode.

**Steps to reproduce:**
-

**Minimal reproduction project:**

Maybe I'll upload the dae when I have permission to do it.

**Comment by Zireael07** [comment] 2018-12-26 09:44
Godot can only display 6 lights at a time, I believe. Are there more lights that could be affecting the player (e.g. on the other side of the wall but bleeding through a gap, etc.)?

**Comment by Chaosus** [comment] 2018-12-26 10:07
> There are a lot of spotlight inside the scene, it's 30 of them

Godot currently supports only 8 spotlights simultaneously, nothing surprisingly that it will shut off some lights if the limit is reached.
Its also a duplicate of #15651(targeted to 3.2), so closed

**Closed by Chaosus** 2018-12-26 10:07 UTC

**Comment by theraot** [comment] 2020-03-12 08:43
I'm experiencing the problem of this issue.

Yes, I know that Godot can only use 8 lights per object, I get it. Now, let me tell you...

Godot should pick the lights that are  (more likely to be) visible on screen. Look at what @earlroxas13 posted again. Do you see 8 lights?

Alright, so, I have a first person game, with no ambient light because that is what I was going for, and I wanted to light the scene with spot lights. I did it with GridMap. Is GridMap counting as a single object? It seems to be. That is good... except for lighting.

I thought, perhaps if I bake my lights, this would be a non issue. However, I could not get it to bake lights on the GridMap.

The issue is that the lights Godot picks are not matching what is on screen. Just rotating the camera makes some appear and disappear. I tried fixing it with VisibilityNotifier, could not get it to work correctly.

Then I decided to switch to GLES2, and it just worked. All lights on screen were visible, regardless of where I moved, despite there being more than 8 illuminating the single object which is the large GridMap that constitutes most of the scene. I removed the VisibilityNotifier and it kept working. 

*My particles did not show in GLES2, but that is another tale.*

Thus, I believe the code for GLES3 is screwed up. It decides which 8 out of all the lights to use wrong.

**Comment by Calinou** [comment] 2020-03-12 08:56
> Godot should pick the lights that are (more likely to be) visible on screen.

This limitation will be lifted in Godot 4.0 (in fact, it was already lifted in the current `master` branch). In the meantime, you could add a script to each light that checks for the distance to the camera and fades the light as the distance between the camera and the light increases.

> All lights on screen were visible, regardless of where I moved, despite there being more than 8 illuminating the single object which is the large GridMap that constitutes most of the scene.

I don't remember if the 8-lights-per-mesh limitation applies there, since lighting is multipass in GLES2. However, this means it will get very slow as the number of lights increases.
