### ISSUE TITLE
Incorrect interpolation using BlendNodes in AnimationTree 

### ISSUE THREAD

**Issue by raiseledwards810** [godotengine/godot#65771] opened 2022-09-14 06:02 UTC
### Godot version

4.0 Alpha 17

### System information

Windows 10 64bit

### Issue description

When using any kind of blend node in AnimationTree bones interpolate incorrectly between poses.

Example:
![image](https://user-images.githubusercontent.com/42452866/190068588-4bd7371c-f613-4d98-92cb-1a80d736e931.png)
![image](https://user-images.githubusercontent.com/42452866/190068645-82d522b0-6a9e-4a44-83e3-adbd2d803a6b.png)
![image](https://user-images.githubusercontent.com/42452866/190068704-90bf24be-38f3-4efb-a064-7b6d087b698c.png)

The yellow cylinder is rotating only around the Z axiz from pose 1 to pose 2, notice how it's interpolation does not respect that, same interpolation between poses in blender:

![image](https://user-images.githubusercontent.com/42452866/190069437-280f6b73-74fd-4e0e-a50f-2e9646e76c70.png)
![image](https://user-images.githubusercontent.com/42452866/190069532-4954e8d5-cd5e-4a3c-a034-b0ebb0579f88.png)
![image](https://user-images.githubusercontent.com/42452866/190069587-b98a6815-9293-45c9-9b23-7db42a02d8b5.png)

This is a problem to blend more complex animations, here for example:

![image](https://user-images.githubusercontent.com/42452866/190070142-58dd7b5e-e9fd-49de-a59b-a03a7280cb48.png)
![image](https://user-images.githubusercontent.com/42452866/190070199-ef51fbdf-a746-4d0d-b89d-733a9e37756c.png)
![image](https://user-images.githubusercontent.com/42452866/190070345-850ac69e-913b-485e-ae24-4a4155188158.png)

The arm is trying to rotate only around the X axis  blending between two poses but it behaves incorrectly, which makes blend nodes unusable for creating something like an aiming system like in this scenario.

I don't use the animation optimizer when importing models. 

### Steps to reproduce

- Open the godot project with Alpha 17 buil
- Blend between poses in AnimationTree

### Minimal reproduction project

[Interpolation issue.zip](https://github.com/godotengine/godot/files/9563135/Interpolation.issue.zip)

**Comment by TokageItLab** [comment] 2022-09-15 17:41
Probably this is duplicate of #59536. Since Godot4's blending system does not allow more than 180 degrees of rotation from Rest for blending consistency, the Skeleton model should be imported with Rest as the midpoint of all poses (like T-pose) as much as possible.

**Comment by TokageItLab** [comment] 2022-09-15 18:01
FIY, Here is the blend when Pose 1 of Project is Rest.

![image](https://user-images.githubusercontent.com/61938263/190476864-c4bd195d-9529-4b1f-a334-2a6d8341479b.png)

![image](https://user-images.githubusercontent.com/61938263/190476624-23262cb1-4009-4e26-b208-d80b4c652b2e.png)

[Interpolation_issue_fix.zip](https://github.com/godotengine/godot/files/9577845/Interpolation_issue_fix.zip)

**Comment by raiseledwards810** [comment] 2022-09-15 20:10
Guess this makes blend nodes not usable for animation systems that require bones to move in a precise and less restricted way and I should wait for the node replacement of SkeletonIK to be implemented, right? Should I close this issue?

**Comment by TokageItLab** [comment] 2022-09-15 20:22
You can close it if you don't think it is necessary, but I think it is fine to keep it open for others as it is easier to understand the problem than #59536.

Simply the previous blend calculation was broken and needed to be fixed. In this issue's case caused by your project's Bone Rest being very different from both Pose 1 and Pose 2. So as long as we set the correct Rest, it should work correctly in most cases.

If you need more than 180 degrees of rotation when blending, something like #57959 might be useful, but it is basically an edge case, since more than 180 degrees of rotation in the human body means a fractured joint. Also, if you want to rotate the player itself, use RootMotion like #60774.

**Closed** 2022-10-21 16:07 UTC
Labels: documentation, topic:animation
