### ISSUE TITLE
Godot 3.5 RC1 X64 MONO crashes on open!

### ISSUE THREAD

**Issue by xoverify** [godotengine/godot#61338] opened 2022-05-23 21:27 UTC
### Godot version

Godot_v3.5-rc1_mono_win64

### System information

Windows 11 x64, GTX 560 TI

### Issue description

The **Godot x64 MONO version** is not opening to me, he open and crash on Project Manager without error. I **tested on x86 and works fine**. First time I have this error and it only happens in this version and architecture **3.5 RC1 X64 MONO** the **Beta works fine to me**

### Steps to reproduce

1. Download Godot_v3.5-rc1_mono_win64
2. Open and the error happen

**Comment by akien-mga** [comment] 2022-05-23 21:38
Duplicate of #61176.

**Closed by akien-mga** 2022-05-23 21:38 UTC
