### ISSUE TITLE
Possible TextureRect HTML 5 Bug, please confirm: Works on PC but not on Android v9

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot#48653] opened 2021-05-11 20:24 UTC
**Godot version:**
Version 3.3

https://www.bracerjack.com/
This site was created in Godot very simply.
This is the hierarchy structure in Godot:
![e](https://user-images.githubusercontent.com/46036208/117879559-b63c8900-b2d9-11eb-864a-7480d07fa6ce.png)

The output works in PC Desktop, but in Android Mobile V9 device with 2GB of ram, the image inside TextureRect fails to showup.

**Comment by Calinou** [comment] 2021-05-11 20:26
@BracerJack Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by BracerJack** [comment] 2021-05-11 20:33
[Godot.zip](https://github.com/godotengine/godot/files/6461841/Godot.zip)
minimal reproduction project attached.

**Comment by lawnjelly** [comment] 2021-05-14 06:36
Likely the image is too big. The image is 1681x4936. As a general guideline for web and mobile it isn't a great idea to use more than 2048 size. Most devices support that size. And power of 2 textures is recommended if you use any sort of wrapping.

**Comment by josefkaragoli** [comment] 2021-05-14 09:13
I can confirm that this is reproducible on both of my android phones, a Samsung Galaxy M31 and a Huawei p30. It's probably since as @lawnjelly said, most android GPUs only support up to 2048px textures

**Comment by Calinou** [comment] 2021-05-14 12:20
Closing per @lawnjelly's comment.

**Closed by Calinou** 2021-05-14 12:20 UTC
Labels: bug, needs testing, platform:android, platform:html5, topic:rendering
