### ISSUE TITLE
Floating point values entered in inspector rounded to 3 decimal places

### ISSUE THREAD

**Issue by RichardR01** [godotengine/godot#75618] opened 2023-04-03 14:03 UTC
### Godot version

4.01

### System information

n/a

### Issue description

I know this issue was opened 2 weeks ago, also 3 years ago; and still it, was closed. Since there is no obvious way of contacting the one who closed it, I am reopening it.

The problem is in the property editor, like in adjusting XYZ values for position. The value is forced to a 3rd precision point. If I manually put in a value like 0.1234, it is forced to be 0.123. There is no option to adjust this, and changing "Default Float Step" in Editor Settings>Interface>Inspector does not work here. I think this is a huge oversight and should not be ignored.

### Steps to reproduce

Create a 2D or 3D scene. Adjust the position value to a 4th (or higher) floating point precision.

### Minimal reproduction project

n/a

**Comment by AThousandShips** [comment] 2023-04-03 14:04
Duplicate of godotengine/godot-proposals#3524

**Closed** 2023-04-03 15:04 UTC
Labels: archived
