### ISSUE TITLE
Snap size is not saved with project or even kept as project or editor settings

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#48848] opened 2021-05-19 15:54 UTC
**Godot version:**
3.3

**OS/device including version:**
Linux

**Issue description:**
Below I have set snap to be 512x480 so I can see how it will look in the running game

![image](https://user-images.githubusercontent.com/12863685/118843920-6a35a980-b8c2-11eb-9a3e-b5235a2b0583.png)

However, this is not saved, so every single time you load the same project you have to go into the three dots menu, go to configure snap and enter the values. Otherwise you end up with this:

![image](https://user-images.githubusercontent.com/12863685/118844151-a36e1980-b8c2-11eb-9676-773875b9ee43.png)

What was expected was the configuration details for the editor to be saved. Using 'snap' as a means of showing a grid is irrelevant as it's the only way to do this in Godot, but the same problem remains.

**Steps to reproduce:**
1. set snap
2. close project

**Minimal reproduction project:**
not required

**Comment by Calinou** [comment] 2021-05-19 15:58
Duplicate of https://github.com/godotengine/godot/issues/27771.

**Closed by Calinou** 2021-05-19 15:58 UTC

**Comment by chucklepie** [comment] 2021-05-19 16:00
@Calinou Thanks, I've added a comment to that as there's an issue not mentioned there. Github really do need to make searching better. I spent 5 minutes searching for a similar thing before posting...
