### ISSUE TITLE
Unable to Play or Debug C# Projects in Visual Studio 2019

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#54901] opened 2021-11-12 05:41 UTC
### Godot version

v3.4.stable.mono.official [206ba70f4]

### System information

Windows 11

### Issue description

When using Visual Studio 2019 to edit Godot 3.4 C# Mono projects, I am unable to "Play in Editor" or debug the game in any way. If I hit the play button in VS2019, an error message stating:

> A project with an Output Type of Class Library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

<img width="335" alt="Godot_C_Sharp_VS_Error" src="https://user-images.githubusercontent.com/3398643/141415306-e1f78cf3-a200-449a-9446-761d87d10977.png">

I did however find a work around to allow debugging of Godot C# projects in Visual Studio based on the instructions on this page:
https://gist.github.com/31/302bab2630ddf8d90ab4aec0d358b538

So this works, but it must be done for every new project you create and is a hassle. Hopefully there is some way to update the Visual Studio plugin to do this automatically, or update Godot to generate the solution files with this already applied.

### Steps to reproduce

Download the Mono build of Godot 3.4 on Windows
Create a new project.
Add a C# script.
Click the script edit button.
Visual Studio 2019 will open.
Click play and see the error.

### Minimal reproduction project

[Sharp.zip](https://github.com/godotengine/godot/files/7525139/Sharp.zip)

**Comment by raulsntos** [comment] 2021-11-12 13:20
Seems like those instructions are for Godot 3.2 so it might be outdated, also this sounds like an issue with the Visual Studio extension and not Godot so it should be reported in the extension's repository: https://github.com/godotengine/godot-csharp-visualstudio

It seems this issue has already been reported in the extension repository:
- https://github.com/godotengine/godot-csharp-visualstudio/issues/10
- https://github.com/godotengine/godot-csharp-visualstudio/issues/21

**Comment by neikeq** [comment] 2021-11-13 20:42
Closing as duplicate of godotengine/godot-csharp-visualstudio#10 (as I just explained [here](https://github.com/godotengine/godot-csharp-visualstudio/issues/21#issuecomment-968132728)).

**Closed by neikeq** 2021-11-13 20:42 UTC
Labels: bug, platform:windows, topic:editor, topic:thirdparty, topic:mono
