### ISSUE TITLE
Godot clears the "Nodes" dock when you connect a signal.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#78714] opened 2023-06-26 16:03 UTC
### Godot version

v3.6.beta2.official [68c507f59]

### System information

w10 64

### Issue description

Take a look at the video, if you have to connect a lot of signals, you must click again on the node that emits them so that the "Nodes" dock reappears.

Distraction-free mode on.

You select the node that emits the signal
In the "Nodes" dock you connect the signal
The script editor opens automatically
You return to the editor to connect another signal
The "Nodes" dock no longer shows the signals and appears empty.
You must select the node again (even though the node is already selected because you selected it earlier) that emits the signals for the "Nodes" dock to display the signals.

![nodesDock](https://github.com/godotengine/godot/assets/19652075/91f82bd5-08fb-484f-9f8c-92c82a83691a)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by YuriSizov** [comment] 2023-06-26 16:13
This is a duplicate of https://github.com/godotengine/godot/issues/46035.

**Closed by YuriSizov** 2023-06-26 16:13 UTC
