### ISSUE TITLE
GPUParticles3D on MacOS causes Godot to crash when trying to view the 3d scene

### ISSUE THREAD

**Issue by rushcodes** [godotengine/godot#89300] opened 2024-03-08 21:48 UTC
### Tested versions

- Reproducible in 4.2.1.stable.official, not able to test other versions at the moment.

### System information

Godot v4.2.1.stable - macOS 14.3.1 - GLES3 (Compatibility) - Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

GPUParticles3D crash Godot when using the 3d view.

### Steps to reproduce

In an existing or new project:

1. Create a new 3d scene (Node3D)
2. Attach a child node of GPUParticles3D to it.
3. Switch or already have the 3d view active.

Doing so will cause Godot to crash within a few seconds. I've tested this 5 times and it happened each time. CPUParticles3D don't seem to have this issue.

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment] 2024-03-09 01:27
Thank you for the report. This is a known issue and is already tracked by https://github.com/godotengine/godot/issues/72469

The current state of our progress towards a solution is described here: https://github.com/godotengine/godot/issues/72469#issuecomment-1892677731

Duplicate of https://github.com/godotengine/godot/issues/72469

**Closed by clayjohn** 2024-03-09 01:27 UTC
