### ISSUE TITLE
Sorting projects in Project List inside Project Manager 

### ISSUE THREAD

**Issue by flashjaysan** [godotengine/godot#8794] opened 2017-05-17 11:11 UTC
This is a feature proposal.
There is a neat favorite feature in Project List inside the Project Manager (with the Stars to the left of project names) but it would be awesome if we could also sort the Project List by alphabetical name or reverse the order. It could be sorted for Paths too.
Anyway, just an idea for improvement.

**Comment by flashjaysan** [comment] 2017-05-17 11:36
A right click in the Project List could be useful to do that. And it could also be used to create, remove or rename a project.

**Comment by nunodonato** [comment] 2017-05-18 09:41
probably something to include in #8135

**Comment by nunodonato** [comment] 2017-06-02 14:19
close as duplicate of #6105 ?

**Comment by AnaDenisa** [comment] 2018-11-16 11:03
Hello :) I would like to work on this feature

**Comment by helenaMontenegro** [comment] 2018-11-23 12:09
I'm working with AnaDenisa, we would like to know if anyone knows where this issue is on the code, we've been looking for it since two weeks ago and we're having troubles finding it.
Thank you!

**Comment by reduz** [comment] 2018-11-23 12:12
Sorry, missed the first message. All the project manager is in a single file:

https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp  (and .h)

**Comment by AnaDenisa** [comment] 2018-11-23 12:21
Thank you! We added that feature and we will create a pull request soon. We only need to test it a few more times.
We wanted to ask that question for another issue and we switched them by mistake, sorry.

**Comment by akien-mga** [comment] 2018-12-06 13:14
Fixed by #23935.

**Closed by akien-mga** 2018-12-06 13:14 UTC
Labels: feature proposal, junior job, topic:editor, usability
