### ISSUE TITLE
v4.3.dev6 Renaming a file produces warning "File with name already exists"

### ISSUE THREAD

**Issue by testpossessed** [godotengine/godot#91786] opened 2024-05-10 05:40 UTC
### Tested versions

- Started after opening project in v4.3.dev6

### System information

Windows 11 Godot 4.3.dev6

### Issue description

Whenever I try to rename a file in the File System view I get a warning message "A file or folder with this same name already exists"

There may well be a file with that name somewhere in the file system of the project, but not at the same path so this warning should not be displayed.

### Steps to reproduce

Given several folders for enemy scenes using the convention enemy_1, enemy_2 etc
Given I have copied enemy_1.tscn from the folder enemy_1 to the folder enemy_2 using the built in duplicate file feature
When I select the new copy of enemy_1.tscn and press F2 to rename it and change the name to enemy_2
Then I get the warning message "A file of folder with this name already exists"

### Minimal reproduction project (MRP)

[bug_report.zip](https://github.com/godotengine/godot/files/15270727/bug_report.zip)

**Comment by AThousandShips** [comment] 2024-05-10 08:36
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/90473

Which was solved in:
* https://github.com/godotengine/godot/pull/91112

Please confirm on latest `master`

**Comment by Chaosus** [comment] 2024-05-10 08:39
Indeed, its exist on dev 6, but gone from latest master.

**Closed** 2024-05-10 08:41 UTC
Labels: bug, topic:editor, needs testing, regression
