### ISSUE TITLE
how to compile android template for arm 64 in 2.1.5 release?

### ISSUE THREAD

**Issue by SMaiLubis** [godotengine/godot#28686] opened 2019-05-04 18:10 UTC
**Godot version:**

2.1.5

**OS/device including version:**

android

**Issue description:**

how to compile android template for arm 64 in 2.1.5 release? 
in godot doc 2,1 only mention arm and x86

**Comment by akien-mga** [comment] 2019-05-06 08:26
It's not possible currently. The changes done for arm64 support in the master branch need to be cherry-picked for 2.1.x and 3.0.x.

Closing as duplicate of #25030.

**Closed by akien-mga** 2019-05-06 08:26 UTC
Labels: enhancement, platform:android, topic:buildsystem, topic:porting
