### ISSUE TITLE
"Find" top bar makes code text overlap the Status bar

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#10955] opened 2017-09-04 07:28 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
GodotEngine 2.1.4, Linux amd64, Screen resolution: 1920x1080

**Issue description / Steps to reproduce:**
When you try to search with Ctrl+F something in built-in code-editor and the file has more lines then your screen can fit, then the last line at the bottom overlaps the status bar of the editor. (see the [Screenshot](https://pp.userapi.com/c841122/v841122193/1f9fe/Giffkgvgkw4.jpg))

**Comment by 0ttoman** [comment] 2017-09-10 10:16
In general this happens when changing the hight of the editor in the layout. The last line overlaps with the border of the window until it is fully outside the frame, only then it is cut off.
The Class Reference (build-in documentation) could provide aspired behaviour.

**Comment by toger5** [comment] 2017-09-10 10:35
Only 2.x ? Or also 3.0 ?
I guess size changed doesnt reigger recalculation of the text... Which is weired since at least RTL definitly sipports that.

**Comment by 0ttoman** [comment] 2017-09-10 10:53
This bug is fixed in 3.0. Just tested it. I works as expected.

**Comment by bojidar-bg** [comment] 2017-09-11 08:19
Duplicate of #10738?

**Comment by 0ttoman** [comment] 2017-09-11 09:30
yeah, that's the same issue.

**Comment by bojidar-bg** [comment] 2017-09-11 09:40
Closing as duplicate of #10738.

**Closed by bojidar-bg** 2017-09-11 09:40 UTC
