### ISSUE TITLE
Button bug issue

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#92890] opened 2024-06-08 00:33 UTC
### Tested versions

v4.3.beta1.mono.official [a4f2ea91a]

### System information

Godot v4.3.beta1.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 950M (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 Threads)

### Issue description

Changing the border width of the button on hover and press in the editor will affect the default border width
![screenshots](https://github.com/godotengine/godot/assets/112788136/ddba32dd-ad57-43df-8a08-a8f5836494f7)

### Steps to reproduce

Changing the border width of the button on hover and press in the editor will affect the default border width

### Minimal reproduction project (MRP)

Changing the border width of the button on hover and press in the editor will affect the default border width

**Comment by AThousandShips** [comment] 2024-06-08 08:39
Please do not just repeat the same text three times, fill in the details properly

Please upload an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by bruvzg** [comment] 2024-06-08 16:12
Should be fixed by https://github.com/godotengine/godot/pull/92701

**Comment by AThousandShips** [comment] 2024-07-03 09:01
Closing as resolved, if you can still reproduce this in the latest version please upload an MRP

**Closed by AThousandShips** 2024-07-03 09:01 UTC
Labels: needs testing, topic:gui
