### ISSUE TITLE
Graph Edit - mouse wheel should zoom by default and not scroll

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#41538] opened 2020-08-26 11:20 UTC
**Godot version:**
3.2.2 and 4.0

**OS/device including version:**
Any

**Issue description:**
I think the graph edit should zoom by default rather than scroll up and down, like Blenders compositing view. It feels a lot more natural imo. Also current there is no mouse wheel shortcut to zoom... which feels really bad. I usually like navigating in node-based workflows (like UE4 bluprints) by zooming in and out. Only having the on-screen buttons to do this feels clunky. 

The code is there to do this... I have no idea why it was commented out. Enabling it makes it work perfectly fine. This comment was made by reduz in 34c022a0 over 4 and a half years ago. I think it works fine, however it could feel better once combined with adjustments made possible by PR #38261.
https://github.com/godotengine/godot/blob/a609b30ddb77bcc1c64008a7848da07b5448a10d/scene/gui/graph_edit.cpp#L1010-L1018

**Comment by EricEzaM** [comment] 2020-08-26 11:25
Also I have tested it using `set_zoom_custom(<zoom>, b->get_position())` so it zooms to your mouse position, and it feels really good.

**Comment by fire** [comment] 2020-08-26 14:48
The original reason was that antialiasing is off makes scaling 2d look bad, but antialiasing is off in master.

**Comment by Chaosus** [comment] 2020-09-05 11:27
Duplicate of https://github.com/godotengine/godot/issues/5214, however since it targets only Visual Shader I will close the old one

**Comment by Calinou** [comment] 2021-02-25 20:53
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2352, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2021-02-25 20:53 UTC
Labels: enhancement, topic:gui, usability
