### ISSUE TITLE
type of variable is wrong in release

### ISSUE THREAD

**Issue by Carpynch0** [godotengine/godot#33580] opened 2019-11-12 19:48 UTC
**Godot version:** 3.1.1.Stable

**OS/device including version:** debian 10.1

**Issue description:** if changes value of variable also change its type.

**Steps to reproduce:**

**Minimal reproduction project:**
```gdscript
extends Button

class_name boton_de_puebra

var variable_float :float = 0

func _ready() -> void:
	text = "texto"

func _process(delta: float) -> void:
	##########
	variable_float = 1
	##########
	if pressed:
		text = "soy float" if variable_float is float else "ERROR"
```

**Comment by nathanwfranke** [comment] 2019-11-12 20:06
Try setting it to `1.0` because it's probably changing to an int

**Comment by Calinou** [comment] 2019-11-12 20:39
Duplicate of #24035 and #28863 (the underlying cause is the same).

**Closed by Calinou** 2019-11-12 20:39 UTC
