### ISSUE TITLE
Support high-resolution displays

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#1954] opened 2015-05-21 14:10 UTC
Really miss the settings  Godot for high resolution screens. On the screen of my laptop interface Godot unbearably small. So impossible to work with.

**Comment by reduz** [comment] 2015-05-21 14:34
what laptop? don' t you have a compatibility option?

**Comment by DimitriyPS** [comment] 2015-05-21 18:05
>> what laptop?
http://www.samsung.com/hk_en/ativ/ativbook9plus.html

>> don' t you have a compatibility option?
Don't quite understand the question (don't speak English). If he was referring to: OS adapted for high resolution screen, - Yes, Linux Mint Cinnamon 17.1. It correctly supports high resolution screens.

The problem is not limited to my laptop. Such screens are not uncommon. In future they will be only more.

**Comment by Fiona** [comment] 2015-05-22 14:16
UI scaling is suggested for 1.2 as per the UI suggestions spreadsheet https://docs.google.com/spreadsheets/d/1S0meIdV2io-s9NjIX_u2im3nblnjmSoRhHk4Ll9UyAE/edit#gid=0

This will hopefully allow Godot to be fully supported on ultra high res screens like your laptop. Assuming this is accepted? @reduz are you planning to create a list of accepted suggestions for the UI rewrite or just pick them as you feel?

**Comment by akien-mga** [comment] 2015-11-15 19:10
Closing as a duplicate of #227.

**Closed by akien-mga** 2015-11-15 19:10 UTC
Labels: archived

**Comment by DimitriyPS** [comment] 2016-06-17 15:23
I understand that the problem has been resolved for Linux? Someone have tested on Linux?
