### ISSUE TITLE
CollisionShape don't work for scenes that are extending CollisionObject 

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#6808] opened 2016-10-13 02:54 UTC
**Operating system or device - Godot version:**
Windows 10 x64
Godot 2.1 x64 stable

**Issue description** (what happened, and what was expected):
 Inherited scenes based on a imported model/scene with the root node set to Rigid Body on import, will not receive collision.

**Steps to reproduce:**
Import a scene/character model and choose the custom import type set to a Rigid Body type as the root node. then create an Inherited scene based on the imported model/scene. Rig the Inherited scene with colliders and proceed to test collision.

**Link to minimal example project** (optional but very welcome):
I found that a work around is to first rig the base scene with colliders then save the scene. then you can delete the colliders from the base scene which magically makes the inherited scene know what a collider is. I've tested using Rigid Body node but I assume this bug probably extends to other Physics bodies too.
Something else I found weird was that if you instance the base scene and the inherited scene into another scene. if both the base scene and Inherited has a collider then you remove the collider from the base scene but keep the collider on the inherited scene. the base scene looks as if it inherits the collider from the inherited scene. fun stuff once you see how these bugs are so broken.

**Comment by kubecz3k** [comment] 2016-10-14 12:14
This is related to to https://github.com/godotengine/godot/issues/2314

**Comment by kubecz3k** [comment] 2016-10-14 12:18
@vonflyhighace2 in short this works like this by design (because of the fact that CollisionShapes nodes are only helpers). But there is plan to change this behavior in 3.0 and make it more user friendly. You can check how to workaround this in https://github.com/godotengine/godot/issues/2314

**Comment by kubecz3k** [comment] 2016-10-14 12:19
Archiving because it's duplicate of https://github.com/godotengine/godot/issues/5798

**Closed by kubecz3k** 2016-10-14 12:19 UTC
Labels: bug, topic:physics
