### ISSUE TITLE
editor bug when saving or selecting a node.

### ISSUE THREAD

**Issue by incdev96** [godotengine/godot#80305] opened 2023-08-05 18:45 UTC
### Godot version

4.1.1 stable

### System information

Ubuntu 23.04

### Issue description

the window that appears to select a node or the window that appears when saving a scene is displayed and instantly lodged in the ubuntu dock. I have to do alt+tab to select the window that opened before doing what I wanted to do and it's very annoying and at times it's impossible to select the window that opened. All versions of godot 4.x have this problem unlike godot 3.5.2 which does not have this problem.
[Capture vidéo du 2023-08-05 18-16-12.webm](https://github.com/godotengine/godot/assets/18330038/26e3ada5-551b-4716-aeb9-38414d58e603)

### Steps to reproduce

- Create a new simple projects
- Add a node. the window will go to the dock immediately
- Alt + tab or click on the godot logo on the dock to select the new window
- save the node. The backup window will have the same behavior

### Minimal reproduction project

no project required.

**Comment by saierXP** [comment] 2023-08-06 02:59
Please test if [this PR](https://github.com/godotengine/godot/pull/80036) is fixed, the download method for the test version can be found in the [document](https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html).

* Duplicate of #77333

**Comment by incdev96** [comment] 2023-08-07 01:13
I have a problem with dotnet 7. I installed it on my OS (Ubuntu 23.04) but Godot does not recognize it. Is it possible to have the standard version without mono?

**Comment by Zireael07** [comment] 2023-08-07 06:39
@incdev96 This is an unrelated issue.

**Comment by incdev96** [comment] 2023-08-07 14:29
Actually I had to install it with apt instead of snap. yeah i tested, this PR fixed it. THANKS

**Closed** 2023-08-08 07:31 UTC
Labels: bug, platform:linuxbsd, topic:porting, needs testing
