### ISSUE TITLE
Crash with signal 11 when reimporting a texture that is being used by a stylebox (currently opened in the inspector)

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#26885] opened 2019-03-10 21:25 UTC
**Godot version:**
3.1rc1

**OS/device including version:**
Linux Arch 5.0.0.1

**Issue description:**
I was disabling filtering for a texture that was used for a stylebox that I had opened in the editor. Godot crashed with the following backtrace:
```
1  Object::_change_notify                               object.h               567  0x55555697f889 
2  StreamTexture::load                                  texture.cpp            737  0x555558c101a2 
3  StreamTexture::reload_from_file                      texture.cpp            842  0x555558c10db6 
4  EditorNode::_resources_reimported                    editor_node.cpp        521  0x555557537152 
5  MethodBind1<EditorNode, Vector<String> const&>::call method_bind.gen.inc    815  0x555557593975 
6  Object::call                                         object.cpp             942  0x55555920e24e 
7  Object::emit_signal                                  object.cpp             1228 0x555559210015 
8  Object::emit_signal                                  object.cpp             1284 0x55555920e6a7 
9  EditorFileSystem::reimport_files                     editor_file_system.cpp 1782 0x5555574b25ee 
10 ImportDock::_reimport                                import_dock.cpp        461  0x5555576e5269 
11 ImportDock::_reimport_attempt                        import_dock.cpp        421  0x5555576e46c3 
12 MethodBind0<ImportDock>::call                        method_bind.gen.inc    137  0x5555576ebc06 
13 Object::call                                         object.cpp             942  0x55555920e24e 
14 Object::emit_signal                                  object.cpp             1228 0x555559210015 
15 Object::emit_signal                                  object.cpp             1284 0x55555920e6a7 
16 BaseButton::_gui_input                               base_button.cpp        139  0x555558108bf5 
17 MethodBind1<BaseButton, Ref<InputEvent>>::call       method_bind.gen.inc    815  0x555558112212 
18 Object::call_multilevel                              object.cpp             777  0x55555920caac 
19 Object::call_multilevel                              object.cpp             882  0x55555920dc98 
20 Viewport::_gui_call_input                            viewport.cpp           1527 0x5555580d508e 
21 Viewport::_gui_input_event                           viewport.cpp           1899 0x5555580d6fa9 
22 Viewport::input                                      viewport.cpp           2653 0x5555580d3ff3 
23 Viewport::_vp_input                                  viewport.cpp           1305 0x5555580d3e74 
24 MethodBind1<Viewport, Ref<InputEvent> const&>::call  method_bind.gen.inc    815  0x5555580fcdb2 
25 Object::call                                         object.cpp             942  0x55555920e24e 
26 Object::call                                         object.cpp             866  0x55555920db5f 
27 SceneTree::call_group_flags                          scene_tree.cpp         262  0x555558099093 
28 SceneTree::input_event                               scene_tree.cpp         418  0x55555809a011 
29 InputDefault::_parse_input_event_impl                input_default.cpp      442  0x5555568d69e7 
30 InputDefault::parse_input_event                      input_default.cpp      259  0x5555568d4def 
31 InputDefault::flush_accumulated_events               input_default.cpp      679  0x5555568d7d5a 
32 OS_X11::process_xevents                              os_x11.cpp             2461 0x5555568bf635 
33 OS_X11::run                                          os_x11.cpp             3002 0x5555568c35f9 
34 main                                                 godot_x11.cpp          55   0x5555568b2481 
```
property seems to be "" (empty string). `this` seems to be a valid texture.

**Steps to reproduce:**
Don't know yet

**Comment by akien-mga** [comment] 2019-03-10 21:57
Duplicate of #26749.

**Closed by akien-mga** 2019-03-10 21:57 UTC

**Comment by QbieShay** [comment] 2019-03-10 22:00
Ah ups, didn't see that one, sorry
