### ISSUE TITLE
Declaring arrays doesn't work in shaders

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12875] opened 2017-11-12 22:45 UTC
Godot 3.0 alpha2
Windows 10 64 bits
nVidia 940M

I tried to write this in a shader:
```glsl
	vec4 test[8];
```
However it didn't compile, the error is:
```
SCRIPT ERROR: (null): Expected ',' or ';' after variable
          At: :18
```

I thought such a construct was allowed in GLSL?

**Comment by reduz** [comment] 2017-11-12 23:10
Not going to be supported in 3.0, possibly in 3.1 or above

**Comment by Zylann** [comment] 2018-04-11 18:11
Can I ask why though? I just came on a QA thread asking for array uniforms: https://godotengine.org/qa/27228/array-godot-shader

And according to https://github.com/Zylann/godot_heightmap_native_plugin/issues/22, the amount of textures you can sample in a shader is limited on some graphics cards (so using textures as array inputs has a higher cost than just supporting them).

**Comment by Hinsbart** [comment] 2018-04-11 18:29
duplicate of #10751

**Closed by Hinsbart** 2018-04-11 18:29 UTC
Labels: enhancement, topic:core
