### ISSUE TITLE
Failed to compile godot source to an android export template

### ISSUE THREAD

**Issue by tam0705** [godotengine/godot#10819] opened 2017-08-31 14:35 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Pro, Godot 2.1.3-stable

**Issue description:**
I typed this to compile godot : scons platform=android target=release, but then this error pops out:
```
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- gcc detected.
Godot Android!!!!! (armv7) (with neon)
scons: done reading SConscript files.
scons: Building targets ...
C:\Program Files (x86)\Android\android-ndk-r13b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -o platform\android\os_android.os -c -fno-rtti -fno-exceptions -DNO_SAFE_CAST -Wall -DNDEBUG -DFREETYPE_ENABLED -DENABLE_DEPRECATED -isystem "C:\Program Files (x86)\Android\android-ndk-r13b/platforms/android-14/arch-arm/usr/include" -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -fvisibility=hidden -fno-strict-aliasing -DANDROID -DNO_STATVFS -DGLES2_ENABLED -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -march=armv7-a -mfloat-abi=softfp -mfpu=neon -D__ARM_NEON__ -target armv7-none-linux-androideabi -fno-integrated-as -gcc-toolchain "C:\Program Files (x86)\Android\android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64" -O2 -DNDEBUG -ffast-math -funsafe-math-optimizations -fomit-frame-pointer -ftree-vectorize -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -Icore -Icore\math -Ieditor -Idrivers -I. -Iplatform\android -Ithirdparty\zlib -Ithirdparty\freetype -Ithirdparty\freetype\include -Ithirdparty\libpng platform\android\os_android.cpp
scons: *** [platform\android\os_android.os] The system cannot find the file specified
scons: building terminated because of errors.
```
I've seen many of these, but none of them really helped me. I've changed the folder 'windows' in android-ndk to 'windows-x86_64' and 'windows-x86' but still the same problem. I also run the cmd as an admin. Is there anyone that can help me with this problem?

**Comment by volzhs** [comment] 2017-08-31 14:51
this might help.
https://github.com/godotengine/godot/issues/2939#issuecomment-193512897

**Comment by tam0705** [comment] 2017-09-01 03:57
I tried with p=android and still the same error :(
By the way, I saw somewhere that they said "I've the libgodot_android.so in the platform/android/java/libs directory, but I don't have it for now. Does that maybe cause the problem? I also don't know how to get the libgodot_android.so.

**Comment by vnen** [comment] 2017-09-01 14:37
It's possible that the problem is just the spaces in the path. Try to move the NDK to a path without spaces (i.e. outside of "Program Files (x86)".

**Comment by tam0705** [comment] 2017-09-02 07:19
Still the same error :(
I really have no idea what I must do next. What I've done are:
-Opening cmd as admin
-Moving android NDK and MinGW to a path without spaces (in my case C:\)
-Renaming a folder in path "C:\android-ndk-r13b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows" into "windows-x86" and "windows-x86_64"

I even tried to build with p=windows and another error outputs: 
```
In file included from platform\windows\os_windows.cpp:48:0:
platform\windows\joystick.h:36:20: fatal error: dinput.h: No such file or directory
 #include <dinput.h>
                    ^
compilation terminated.

=====
scons: *** [platform\windows\os_windows.windows.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by eon-s** [comment] 2017-09-02 17:24
Are you using a -j parameter? I have problems with that on Windows sometimes.

**Comment by tam0705** [comment] 2017-09-05 13:37
No I didn't use any parameters both when trying to compile in android platform and windows platform. :(
Does this relate to the libgodot_android.so? I found some persons talking about it when getting this error (the android platform one), but I really have no idea how to get the .so.

**Comment by tam0705** [comment] 2017-09-06 10:51
I used -j parameter and now another error outputs together with the previous one:
```
scons: *** [platform\android\os_android.os] The system cannot find the file specified
scons: *** [platform\android\godot_android.os] The system cannot find the file specified
```

**Comment by akien-mga** [comment] 2018-09-17 14:18
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:18 UTC
Labels: platform:android, topic:buildsystem
