### ISSUE TITLE
get_property_list() methods sort groups and categories to the end

### ISSUE THREAD

**Issue by Jowan-Spooner** [godotengine/godot#72318] opened 2023-01-29 17:05 UTC
### Godot version

4.0 beta 16

### System information

Linux Mint 20.2, HP laptop

### Issue description

The arrays returned by Object.get_property_list() and Script.get_script_property_list() have group, subgroup and category properties created with the @export_group, @export_subgroup and @export_category annotation at the end.

I've been trying to parse this information for a plugin, but am unable to tell from the returned information, what properties belong to which  group.

### Steps to reproduce

```
extends Node

@export_group("My Properties")
@export var number = 3
@export var string = ""
@export_subgroup("My Subgroup")
@export var subgroup_value = "Something"

@export_category('My category')
@export_group("Prefixed Properties", "prefix_")
@export var prefix_number = 3
@export var prefix_string = ""

@export var ungrouped_number = 3

func _ready():
	for i in get_property_list():
		print(i['name'])
	print("---")
	for i in get_script().get_script_property_list():
		print(i['name'])
```
returns:
```
Node
_import_path
name
unique_name_in_owner
scene_file_path
owner
multiplayer
Process
process_mode
process_priority
Editor Description
editor_description
script
my_node.gd
number
string
subgroup_value
prefix_number
prefix_string
ungrouped_number
My Properties
My Subgroup
My category
Prefixed Properties
---
my_node.gd
number
string
subgroup_value
prefix_number
prefix_string
ungrouped_number
My Properties
My Subgroup
My category
Prefixed Properties
```

### Minimal reproduction project

The code provided above should be enough to test this.

**Comment by Jowan-Spooner** [comment] 2023-01-29 17:06
I was initially unsure if this was a bug and [asked](https://github.com/godotengine/godot/issues/68780#issuecomment-1407658680) in #68780.

**Comment by dalexeev** [comment] 2023-01-29 17:49
Duplicate of #72151.

Export group annotations are broken in beta 16.

**Comment by Jowan-Spooner** [comment] 2023-01-29 17:52
Okay, I saw that broken exports were an issue, but it seemed to me, this was a different problem. Couldn't tell that it's both caused by the same thing, but if so I'm fine with closing this.

**Comment by Calinou** [comment] 2023-01-29 17:57
Duplicate of https://github.com/godotengine/godot/issues/72151.

**Closed by Calinou** 2023-01-29 17:57 UTC

**Comment by dalexeev** [comment] 2023-01-29 18:03
> Okay, I saw that broken exports were an issue, but it seemed to me, this was a different problem. Couldn't tell that it's both caused by the same thing

Groups in beta 16 do not work in the editor precisely because they are at the end of `get_property_list()`.
