### ISSUE TITLE
Replace include guards to pragma once ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18143] opened 2018-04-12 10:01 UTC
`#pragma once` is more clean and error-prone method to defend headers from inclusion and supported on all compilers now. How about removes include guards and change them to `#pragma once` ?

**Comment by Noshyaar** [comment] 2018-04-12 11:40
Related #54

**Comment by Anutrix** [comment] 2019-09-10 05:02
Found quite a few missing header gaurd reports on LGTM. Adding header gaurds don't harm, do they? So should I make a PR?

**Comment by akien-mga** [comment] 2019-09-23 09:11
@Anutrix Sure.

**Comment by Calinou** [comment] 2019-09-23 12:49
It'd be interesting to benchmark compile time differences between include guards and `#pragma once`, though I'm not sure if any popular compiler shows a significant difference there.

**Comment by Anutrix** [comment] 2019-10-03 04:35
> #pragma once does have one drawback (other than being non-standard) and that is if you have the same file in different locations (we have this because our build system copies files around) then the compiler will think these are different files.
Ref: https://stackoverflow.com/a/1946730
My question is whether Godot does the same anytime, i.e, copy file or have same file at different locations during the build process?

**Comment by Calinou** [comment] 2019-12-02 10:48
I replaced all include guards with `#pragma once` in the commit above. It seems to be building fine on Linux, testing on more platforms would be appreciated :slightly_smiling_face:

**Comment by vnen** [comment] 2020-01-03 13:36
Since `#pragma once` is non-standard, I'm against using it. It's possible that people are using Godot in other custom platforms so we can't be sure that their compilers support this directive. I know the directive is widely supported and the ports I mention are hypothetical, but there's no need to make it harder for them to port the code.

**Comment by Anutrix** [comment] 2020-01-03 18:25
I think we should instead add missing `#include` guards in all files that are missing it first.
Because missing both `#pragma once` and `#include` guard seems to be more concerning matter compared to choosing between them.
Also, if and when do decide to change it, we can just [guardonce](https://github.com/cgmb/guardonce) tools to convert between them.

**Comment by Calinou** [comment] 2020-11-27 14:52
Since it seems there is no clear consensus in favor of replacing traditional include guards with `#pragma once`, I'll close this.

**Closed by Calinou** 2020-11-27 14:52 UTC
Labels: discussion, enhancement, topic:buildsystem

**Comment by Xrayez** [comment] 2021-08-01 16:59
I've stumbled upon bugs with header include guards at least thrice during Godot development, and it was a nightmare to figure out the cause for a noob like me! Hypothetical issues that may arise seem to be far fetched compared to real programming pitfalls with C++. But I'm unaware of private discussions around this topic, the links at old IRC channel don't work anymore: https://github.com/godotengine/godot/pull/34143#issuecomment-598660316.

By the way, I've made a similar change in Goost now: goostengine/goost#115, hopefully Godot decides to make a move for consistency and in the interest of robustness at some point in the future.
