### ISSUE TITLE
Clicking "Audio" while in the Script Editor sinks the bottom menu

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10875] opened 2017-09-01 23:20 UTC
**Ubuntu 17.04, Godot Build: 8ed1a28**

**Issue description:**
If you're in the Script Editor, clicking the Audio button will make the whole bottom menu sink.

**Comment by djrm** [comment] 2017-09-25 17:06
i think this has been solved

**Comment by reduz** [comment] 2017-09-29 19:35
i think so, cat reproduce so closing

**Comment by YeldhamDev** [comment] 2017-09-29 19:42
@reduz @djrm Using build cb41482 and it still happens, but far less noticeable now:
![screenshot at 2017-09-29 16-37-22](https://user-images.githubusercontent.com/30739239/31033085-22db125e-a535-11e7-9f53-e5c1061c15ea.png)

**Comment by djrm** [comment] 2017-09-29 20:31
@YeldhamDev but that commit is 14 days old, can you try with a more recent version.

**Comment by YeldhamDev** [comment] 2017-09-29 20:35
@djrm I don't compile the engine myself, I make use of [calinou's builds](https://bintray.com/calinou/godot/editor), and I am using the most recent one available.

**Comment by YeldhamDev** [comment] 2017-09-30 21:28
@djrm Build 27e9714, it completely hides the bottom menu now.

**Comment by YeldhamDev** [comment] 2017-10-04 14:54
@reduz Build 8468839, it is still happening. My screen resolution is 1366x768, if this helps in anything.

**Comment by Noshyaar** [comment] 2017-10-04 15:01
Can confirm on ef08228

**Comment by djrm** [comment] 2017-11-10 03:30
this only happens on small screens, since the buses are fixed size, they move everything towards the bottom.

**Closed** 2017-12-25 01:27 UTC
Labels: bug, confirmed, topic:editor, usability
