### ISSUE TITLE
Unable to compile master

### ISSUE THREAD

**Issue by ShyRed** [godotengine/godot#17561] opened 2018-03-16 14:52 UTC
**Godot version:**
7275fb617064dfaffe96942016b7190dfc8e1366

**OS/device including version:**
Windows 7, Service Pack 1, 64Bit

**Issue description:**
Build fails with error:

```
c:\Work\godot>scons -j1 platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits o
r platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  8%] ←[94mCompiling ←[95m==> ←[93mmain\default_controller_mappings.gen.cpp←[0m

default_controller_mappings.gen.cpp
main\default_controller_mappings.gen.cpp(4): error C2466: cannot allocate an arr
ay of constant size 0
scons: *** [main\default_controller_mappings.gen.windows.tools.32.obj] Error 2
scons: building terminated because of errors.
```

**Steps to reproduce:**
Compile with `scons -j1 platform=windows`

File `default_controller_mappings.gen.cpp` is generated with invalid C++ code:

```C++
/* THIS FILE IS GENERATED DO NOT EDIT */
#include "default_controller_mappings.h"
#include "typedefs.h"
const char* DefaultControllerMappings::mappings[] = {
};
```

**Comment by Noshyaar** [comment] 2018-03-16 16:16
Duplicate of  #17551

**Closed by Noshyaar** 2018-03-16 16:16 UTC
