### ISSUE TITLE
Window location when running projects is incorrect on Windows 11 with 200% scaling

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#56188] opened 2021-12-23 08:19 UTC
### Godot version

Godot 3.4.2 (more info is visible in the screenshot)

### System information

Windows 11 for ARM on a Parallels VM at 200% scaling

### Issue description

The window location when running projects is incorrect on Windows 11 with 200% scaling. I have both the OS set to 200% scaling and the Godot editor set to 200% scaling. When I run a project, the window appears in the bottom-right corner of the screen, instead of the center as would be expected.

![corner](https://user-images.githubusercontent.com/1646875/147209536-c8c80dc6-a455-4fca-90f0-6260871e13be.png)

(Ignore the contents of the project, it's just some prints I was using to test another bug when I discovered this one)

### Steps to reproduce

Get an empty project, add a basic scene, and run the project. I suspect this could happen on any Windows system with 200% scaling, but it's possible this is specific to Windows 11 or to my setup. I also tested restarting the OS and the behavior still persisted.

### Minimal reproduction project

N/A - this is about where Godot places the window, it happens with an empty project.

**Comment by Calinou** [comment] 2021-12-23 18:54
Duplicate of https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2021-12-23 18:54 UTC
Labels: bug, platform:windows, topic:porting
