### ISSUE TITLE
vscode c# code hinting cann't identify the custom signal name

### ISSUE THREAD

**Issue by zhuyeaini9** [godotengine/godot#80395] opened 2023-08-08 01:40 UTC
### Godot version

4.1.1

### System information

vscode: 1.81.0 OS: Windows 10 x64 10.0.19045

### Issue description

the godot can build ok with custom signal,but the vscode hinting cannot identify the custom signal.

1.new a custom signal with c#:
	[Signal]
	public delegate void RightMouseClickEventHandler();
2.invoke the signal with SignalName like:
EmitSignal(SignalName.RightMouseClick);
![image](https://github.com/godotengine/godot/assets/37789892/263398e3-52f1-4f8e-baa7-7f24bc1fccaa)
3.the godot can build and run ok in editor,seems the vscode hinting issue.

### Steps to reproduce

1.new a custom signal with c#:
	[Signal]
	public delegate void RightMouseClickEventHandler();
2.invoke the signal with SignalName like:
EmitSignal(SignalName.RightMouseClick);

the vscode cann't identify the SignalName.RightMouseClick
![image](https://github.com/godotengine/godot/assets/37789892/263398e3-52f1-4f8e-baa7-7f24bc1fccaa)

### Minimal reproduction project

[test6.zip](https://github.com/godotengine/godot/files/12286413/test6.zip)

**Comment by raulsntos** [comment] 2023-08-08 06:27
This is a bug in VSCode's C# extension.

- Duplicate of https://github.com/godotengine/godot-csharp-vscode/issues/57.

**Closed by raulsntos** 2023-08-08 06:27 UTC
