### ISSUE TITLE
AtlasTexture's Texture Region Fading

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#44464] opened 2020-12-17 17:23 UTC
**Godot version:**
3.2.4 beta 4

**OS/device including version:**
Windows 10 x64
Intel HD 3000

**Issue description:**

The Texture Region tab (where output one is too) fades when zooming

https://i.imgur.com/nCDAXeZ.mp4

**Steps to reproduce:**

* Create a new Project
* Use GLES2 (dont know if same occurs with GLES3)
* Create a 3DSprite (on a 3dscene with camera)
* Assing a new texture atlas
* Use a texture that contains 2048+ size (dont know if same occurs with smaller ones)
* Open TextureRegion tab
* Zoom out/in

**Minimal reproduction project:**

[MK.zip](https://github.com/godotengine/godot/files/5712343/MK.zip)

**Comment by Calinou** [comment] 2020-12-17 17:40
I guess this happens because the engine is trying to display mipmaps, but the generated mipmaps are fully transparent.

**Comment by lawnjelly** [comment] 2020-12-17 17:52
I don't really know this area, but first suspect would be a texture without generated mipmaps. If the mipmaps below 0 are black, then it will fade to black with distance.

**Comment by nonunknown** [comment] 2020-12-17 18:49
Any chance to avoid this fading until solving? I tried enable/disable mipmaps on the import tab but no chance

**Comment by nonunknown** [comment] 2020-12-17 18:57
Here I've made a test, the stage wasnt po2 texture, then I resized it to 4096x4096 the character is 2048x2048 he isn't fading 
![image](https://user-images.githubusercontent.com/58845030/102531042-823d9e80-4080-11eb-833c-d35c9c26e918.png)

**Comment by lawnjelly** [comment] 2020-12-17 19:20
As Calinou, said, we need a minimum reproduction project. I've never used sprite3d or texture atlases, so I wouldn't know how to create them, and don't have time to spare at the moment to learn (I only know the backend). @clayjohn may be able to help more when he is up.

**Comment by nonunknown** [comment] 2020-12-17 21:48
@lawnjelly updated the first post with MRP files, make sure to use GLES2

**Comment by lawnjelly** [comment] 2020-12-18 10:16
Your project the background sprite3ds were just showing white for me, nothing like your video.

I tried following a tutorial on texture atlases:
https://www.youtube.com/watch?v=oEBUXW674dc

And it didn't work at all for me. Maybe there is something broken in the editor code, or I'm doing it wrong. Outside rendering is not my area maybe someone who works on texture atlas can help.

**Comment by clayjohn** [comment] 2020-12-19 20:14
I've taken a look at the project. The issue appears to be that you have instantiated a StreamTexture through the editor and then assigned the texture through the StreamTexture. When just loading the texture in the atlas and assigning a region everything works fine.

**Comment by nonunknown** [comment] 2020-12-19 21:06
@clayjohn even if it was a mistake of mine, textureregion tab shouldnt fade textures, so this is still a engine bug!

**Comment by clayjohn** [comment] 2020-12-19 21:12
When you fix the mistake the fading goes away completely, both in the tab and in the scene! So there isn't really anything for us to fix.

**Comment by Calinou** [comment] 2021-05-18 21:34
Closing per @clayjohn's comment.

**Closed by Calinou** 2021-05-18 21:34 UTC
Labels: bug, needs testing, topic:editor, topic:rendering
