### ISSUE TITLE
Editor freeze when running on Android devices - Index line=0 out of size (l.offset_caches.size()=0)

### ISSUE THREAD

**Issue by itsabhiaryan** [godotengine/godot#14590] opened 2017-12-12 12:04 UTC
**Windows 7, Godot version 3.0 beta1**

**Sometimes Editor freezes, when running on Android device**

**Steps to reproduce:**

Run 5 to 10 times on Android devices.

Android Device that I'm using : 

Moto G (3rd Generation) with Android version 6.0.1
 
There is unbreakable loop inside console, output attached below : 

![freeze](https://user-images.githubusercontent.com/7019724/33883511-13414658-df62-11e7-8f46-7246df124ab7.png)

**Comment by Wildos** [comment] 2017-12-13 21:27
Can it be related to the issue #14394 ? If so it may have been fixed by the PR #14633 ?

**Comment by akien-mga** [comment] 2017-12-13 21:42
That's what I thought too, but given the location where the issue is triggered, I don't think so.

Usage of `Line::offset_caches` seems a bit weird in `rich_text_label.cpp`, I only had a quick look but I can definitely see situations where it would be empty and thus trigger this error.
I don't know why it would make things freeze though.

**Comment by akien-mga** [comment] 2018-01-05 13:38
Can it still be reproduced in 3.0 beta 2 or the current master branch?

**Comment by akien-mga** [comment] 2018-01-05 16:10
I guess that means no..?

**Comment by s0ra** [comment] 2018-03-15 11:18
This happens on Godot 3.0.2. I can reproduce it.

**Comment by akien-mga** [comment] 2018-03-15 11:39
@s0ra Can you provide an example project that triggers the issue, and steps to reproduce?

**Comment by s0ra** [comment] 2018-03-15 11:51
The project will duplicate some Sprites and TouchScreenButtons. The issue occurs when I uses Small Deploy with Network FS to debug it on an Android device. I am not sure if the image assets were the cause, but I first put tons of them in the project. I am not going to put them in this example project but you may try. Download: https://www.sendspace.com/file/lccrl4

**Comment by reduz** [comment] 2018-11-11 12:37
Does this still happen on HEAD?

**Comment by akien-mga** [comment] 2019-11-26 13:32
I tried exporting the project in https://github.com/godotengine/godot/issues/14590#issuecomment-373350690 ~10 times to my Xiaomi Pocophone F1 from Linux with "Small Deploy with Network FS" but I couldn't reproduce any freeze. Using 3.2 master (8ea909f5).

Can anyone still reproduce it in latest 3.2 beta builds or newer?

**Comment by akien-mga** [comment] 2020-07-26 22:25
No answer, so closing.

**Closed by akien-mga** 2020-07-26 22:25 UTC
Labels: bug, platform:android, topic:porting
