### ISSUE TITLE
Tween with `float` property will be forced to interpolate as `int` type when passing `int` to Tween's argument

### ISSUE THREAD

**Issue by saierXP** [godotengine/godot#87326] opened 2024-01-18 08:21 UTC
### Tested versions

4.2.1

### System information

windows10

### Issue description

![tween-int-float](https://github.com/godotengine/godot/assets/45038185/9104cfe4-a2f9-4b5e-a6c8-9b47be8b4a52)

```gdscript
extends Node2D

func _ready() -> void:
	var t := create_tween()
	t.set_parallel()
	t.tween_property($Icon1,'rotation', PI, 1).from(0) # row1 left
	t.tween_property($Icon2,'rotation', PI, 1).from(0.0) # row1 right
	t.tween_property($Icon3,'rotation', PI, 1).as_relative().from(0) # row2 left
	t.tween_property($Icon4,'rotation', PI, 1).as_relative().from(0.0) # row2 right
```
tween interpolates by the type of the `from` argument, not the `float` type of the `property`.
Does not work if `as_relative` is used.

### Steps to reproduce

Run the MRP project attached below.

### Minimal reproduction project (MRP)

[tween-int.zip](https://github.com/godotengine/godot/files/13973877/tween-int.zip)

**Comment by jsjtxietian** [comment] 2024-01-18 09:06
Related to https://github.com/godotengine/godot/pull/73178

Reading the code, it seems godot does use the from value to determine final value. cc @KoBeWi

**Comment by KoBeWi** [comment] 2024-01-20 00:25
I'm getting a different result in 4.3 dev2:

https://github.com/godotengine/godot/assets/2223172/eb9f084f-ae44-4997-886d-e6522ae41186

Seems like this was fixed by some of the animation changes.

**Comment by saierXP** [comment] 2024-01-20 03:55
> Can you confirm the issue is fixed for you in the newest version?

The `as_relative().from(0)` one was fixed, but `from(0)` wasn't.

**Comment by TokageItLab** [comment] 2024-01-20 20:13
Fixed by https://github.com/godotengine/godot/pull/86046

**Comment by kleonc** [comment] 2024-01-21 13:14
> > but from(0) wasn't.
> 
> Not sure what you are referring to, but if you mix Int and float, the float will take precedence to make subsequent transitions consistent. This is an intended behavior.
> 
> If you have any other problems, please check the latest master or 4.3.dev2 or later versions and report them if you still have problems.

See how the `t.tween_property($Icon1,'rotation', PI, 1).from(0) # row1 left` behaves (top-left in the examples above).

Calling `.from(0)` makes the tweener tween with integers even though both the property and the final value passed are floats. So it's not true that float always take precendence in case of mixing float/int.

To me it seems like unintended behavior / bug.

---

Specifically when calling `from(an_int)` both `initial_val` and `final_val` end up being ints:
https://github.com/godotengine/godot/blob/0bcc0e92b3f0ac57d4c4650722f347593a258572/scene/animation/tween.cpp#L506-L512
https://github.com/godotengine/godot/blob/0bcc0e92b3f0ac57d4c4650722f347593a258572/scene/animation/tween.cpp#L73-L74

Hence `delta_val` etc. is int:
https://github.com/godotengine/godot/blob/0bcc0e92b3f0ac57d4c4650722f347593a258572/scene/animation/tween.cpp#L564

**Closed** 2024-01-26 10:52 UTC
Labels: bug, topic:animation
