### ISSUE TITLE
Resource with external dependency generates an error related to reading filesystem cache.

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot#78277] opened 2023-06-15 14:42 UTC
### Godot version

4.1-beta2

### System information

Windows

### Issue description

Each Spireframes resource in my project generates the following error upon opening the editor: `editor/editor_file_system.cpp:265 - Condition "split.size() != 9" is true. Continuing.` They have external dependencies on the image files, like the one in the reproduction project. Debugging shows that the variable in question has a size of 11 only in these resources, with the additional values related to the external dependency. A look at the filesystem cache file shows that the generated lines are indeed longer.

Bisected to #73131.

### Steps to reproduce

Download the reproduction project, open it, and reload it once. The error does not appear the first time.

### Minimal reproduction project

[reproduction_project.zip](https://github.com/godotengine/godot/files/11758967/reproduction_project.zip)

**Comment by capnm** [comment] 2023-06-15 14:45
https://github.com/godotengine/godot/issues/78242

**Comment by Chaosus** [comment] 2023-06-16 06:35
Duplicate of https://github.com/godotengine/godot/issues/78242

**Closed by Chaosus** 2023-06-16 06:35 UTC
Labels: bug, topic:editor, regression
