### ISSUE TITLE
Using System.Threading.Tasks throws error with .NET 5.0 as build tool.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#43458] opened 2020-11-11 16:35 UTC
**Godot version:**
Godot_v3.2.3-stable_mono_win64

**OS/device including version:**
Windows 10 1909

**Issue description:**
Ran into this problem while updating an older project to use the latest stable Godot and use dotnet CLI instead of MSBuild.
I started a new project from scratch, only reusing things from my old project. All seems to run fine with my code updated only my async functions throw errors and crash the game when they are called.

Isolated it in the example project. I also made sure that a basic C# CLI project runs the code just fine with my installed .Net build tool so it must be something Godot related.

I got this error instead of my Async function running correctly:
```
E 0:00:00.539   void Node2D._Ready(): System.TypeLoadException: Could not load type of field 'AudioEffects+<FadeOut>d__0:<>t__builder' (1) due to: Could not resolve type with token 01000017 from typeref (expected class 'System.Runtime.CompilerServices.AsyncVoidMethodBuilder' in assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Runtime.CompilerServices.AsyncVoidMethodBuilder member:(null)
  <C++ Error>   Unhandled exception
  <C++ Source>  *redacted*\2020 - Test\Node2D.cs:15 @ void Node2D._Ready()()
  <Stack Trace> Node2D.cs:15 @ void Node2D._Ready()()
```

**Steps to reproduce:**
1. Install .NET 5.0: SDK 5.0.100
2. Run: Godot_v3.2.3-stable_mono_win64.exe
3. Set build tool to: dotnet CLI
4. Import the example project.
5. Run the game, see the error.

**Minimal reproduction project:**
[2020 - Test.zip](https://github.com/godotengine/godot/files/5525310/2020.-.Test.zip)

**Comment by ScepticDope** [comment] 2020-11-11 17:18
Found a fix for it. Changing the .csproj:
`<TargetFramework>net5.0</TargetFramework>`

to

`<TargetFramework>netstandard2.1</TargetFramework>`

Fixes it. My guess is that net5.0 is not supported, yet? Will that be the case for Godot 4.0 though?

**Comment by Calinou** [comment] 2020-11-11 17:20
> My guess is that net5.0 is not fully supported, yet? Will that be the case for Godot 4.0 though?

See https://github.com/godotengine/godot-proposals/issues/793.

**Comment by aaronfranke** [comment] 2020-11-12 11:12
Godot uses Mono right now, and that will not change in the near future (and might still be the case for 4.0). Mono does not support .NET 5 as a target, only .NET 5 supports .NET 5 as a target right now :)

The default target is `net472`, if this isn't what Godot generated in your `.csproj` file then that sounds like a bug.

**Comment by Shpendicus** [comment] 2020-11-13 11:00
> Godot uses Mono right now, and that will not change in the near future (and will likely still be the case for 4.0). Mono does not support .NET 5 as a target, only .NET 5 supports .NET 5 as a target right now :)
> 
> The default target is `net472`, if this isn't what Godot generated in your `.csproj` file then that sounds like a bug.

Why no interesst to change mono to .NET 5?

**Comment by aaronfranke** [comment] 2020-11-13 11:08
@Shpendicus It's not at all that there is no interest. If there was no interest, then https://github.com/godotengine/godot-proposals/issues/793 would be closed. It's just that it won't happen in the near future, .NET 5 literally just came out a few days ago and it's still missing some things.

**Comment by Shpendicus** [comment] 2020-11-14 10:01
@aaronfranke my idea was actually that if ppl could start by now adpoting .NET 5, this time u need to adopt it into Godot, would IMHO be sufficient for .NET 5 to be on a really stable lvl/production useful lvl, so you are working simultaniously with MS .

**Comment by GeorgeS2019** [comment] 2021-04-07 14:45
@akien-mga  Same with the latest .NET 5.0.5

Install .NET 5.0: SDK 5.0.**202**
Run: Godot_v3.3rc7_mono_win64.exe
Set build tool to: dotnet CLI
Import the example project.
Run the game, see the error.

`void Node2D._Ready(): System.TypeLoadException: Could not load type of field 'AudioEffects+<FadeOut>d__0:<>t__builder' (1) due to: Could not resolve type with token 01000017 from typeref (expected class 'System.Runtime.CompilerServices.AsyncVoidMethodBuilder' 
`

**Comment by neikeq** [comment] 2021-04-07 15:36
Closing as not a bug. You should be able to use the .NET 5 Sdk to build your project but you cannot set the target framework to .NET 5 as Godot doesn't support that.
We have plans to support .NET 6 in the (near?) future.

**Closed by neikeq** 2021-04-07 15:37 UTC
Labels: topic:mono
