### ISSUE TITLE
Changing a node type in editor does not remove signal connections

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6602] opened 2016-09-24 19:12 UTC
**Operating system or device - Godot version:**
Windows 10 64-bits. Recent master build.

**Issue description** (what happened, and what was expected):
When changing a `LineEdit` to a `Control` I got an infinite stream of the following error:

```
ERROR: Object::emit_signal: Error calling method from signal 'timeout': 'Control::_toggle_draw_caret': Method not found.
   At: core\object.cpp:1278
```

It turns out a `LineEdit` control connects a timeout signal to its `_toggle_draw_caret` (obviously to draw the caret blinking) but never disconnects it when changing the node to another type. So now it wants to call the function in the new node, which does not have such function.

This is solved by deleting the node.

Something similar happens if you change one control for another:

```
ERROR: Disconnecting nonexistent signal 'size_changed', slot: 48438:_size_changed
   At: core\object.cpp:1559
ERROR: Signal 'size_changed'' already connected to given method '_size_changed' in that object.
   At: core\object.cpp:1499
```

It seems the code is trying to disconnect the signal but failing to do so for some reason.

**Steps to reproduce:**
- Add a `LineEdit` node.
- Right-click and select "Change Type".
- Select any other node type.
- See the errors in console.

**Comment by MattUV** [comment] 2017-03-09 08:40
The bug still exists on 2.1.2, I changed a KinematicBody2D into an Area2D, and also got the same error.
It was from a timer connected to the kinematic body in editor.

> ERROR: Object::emit_signal: Error calling method from signal 'timeout': 'Area2D(Bullet.gd)::_on_Timer_timeout': Method not found.


But, if you disconnect via the editor and connect by code, the error disappears. However, as soon as you try to reconnect via editor, it starts again. Even when I shifted back to KinematicBody2D

**Comment by MattUV** [comment] 2017-03-09 08:42
Note: I quit Godot and started it again, no more error! :)

**Comment by neikeq** [comment] 2017-03-09 12:20
I can't debug Godot right now, so I couldn't take care of the second part.

**Comment by neikeq** [comment] 2017-03-11 19:04
Alright, the second error is caused by Control which disconnects the Viewport's `size_changed` signal from one of its methods on exit tree and connects it back on enter tree, when `Node::replace_by` already took care of that.
This could be fixed by only preserving the connections that were created from the editor. I'll assume that looking for the `CONNECT_PERSIST` flag is the correct way to check that.

**Closed** 2017-03-13 10:05 UTC
Labels: bug, topic:editor
