### ISSUE TITLE
Debugged game on Secondary monitor freezes on editor play

### ISSUE THREAD

**Issue by matthewpaul-us** [godotengine/godot#54349] opened 2021-10-28 13:14 UTC
### Godot version

v3.3.4.stable.official [faf3f883d]

### System information

Windows 11 Pro 22000.258, AMD Ryzen 9 5900X, GLES2, NVIDIA GeForce GTX 1070, V. 496.49

### Issue description

After setting the editor setting 'run\window_placement\screen' to "Next Monitor" or "Monitor 2" causes the white screen freeze. Returning it to the default ("Same as Editor") or "Monitor 1" with the editor on my main monitor allows the debugged project to run successfully.   When the play button is pressed, the console shows the running command and a window opens, but the window freezes on a white screen and won't accept any input, including closing the window. Clicking stop from the engine closes the window without issue.

Exporting a project allows it to run without issue. This issue affects both Mono and normal version. Changing the graphics version from GLES2 to GLES3 doesn't make a difference.

I also tried testing on 3.3.2 and 3.3. Neither version successfully debugged and all presented with a frozen white screen

Log showing the project is requested to run.
![image](https://user-images.githubusercontent.com/1484070/139261970-65303489-a4fb-4687-9dd5-ec8f5499d25a.png)

picture of the window showing a white screen
![image](https://user-images.githubusercontent.com/1484070/139261916-d810c690-7067-4725-bcb4-d595e679b1bd.png)

### Steps to reproduce

1. Create new project
2. Change editor setting `run\window_placement\screen` to open it on a non-main window
2. Create empty scene and save
3. Click run in the editor

### Minimal reproduction project

[Windows 11 White Screen MRP.zip](https://github.com/godotengine/godot/files/7434338/Windows.11.White.Screen.MRP.zip)

**Comment by fenix-hub** [comment] 2021-10-29 18:12
@matthewpaul-us I'm having the same issue currently (on windows 11)

When I try to execute Godot Engine standalone version (from GodotEngine.org) or the Steam Version, whatever project I open or create, godot crashes.
The only way to make it work is to run godot from the Terminal. No error or strange logs whatsoever when it successfully opens projects anyway, which is a little bit weird (at least - I thought that something could be printed in console but not catched during crash).

> I did just find out something that might make this not related to Windows 11.
I didn't have issues on W11 until [this update](https://support.microsoft.com/en-us/topic/october-21-2021-kb5006363-cumulative-update-preview-for-net-framework-3-5-and-4-8-for-windows-11-8670e860-d20f-4c9b-b506-511c4d2e8470).
May not be related, but it's the latest day before Godot stopped working on my laptop.
I've been using 3.3.4.stable for a couple weeks on W11 without changing any editor settings.

**Comment by matthewpaul-us** [comment] 2021-11-02 13:02
@fenix-hub There are several bugs that seem to hinge on Windows 11, but I think your issue might be a better fit for #53485 .

In that one, he can open the project manager, but every time he tries to launch a project, godot crashes. This crash doesn't happen when he launches from a terminal that was open before Godot was started.

For this bug, it seems that Godot can't initialize the debugged window when it is on a secondary screen. I can't test this against Windows 10, as I don't have a multi-monitor setup with Win 10 any more. This bug is tied to the editor setting `run\window_placement\screen`. When that setting is set so the screen opens up on the main monitor, debugging works as expected. When the debugged window opens on my second monitor, the window freezes on a white screen, but I can't see any errors thrown.

**Comment by mhilbrunner** [comment] 2021-12-15 03:10
This may be a duplicate of https://github.com/godotengine/godot/issues/54076, Windows 11 made the new Windows Terminal the default and _all_ Godot versions currently have issues with that

**Comment by akien-mga** [comment] 2021-12-15 07:09
Definitely looks so.

**Closed by akien-mga** 2021-12-15 07:09 UTC
Labels: bug, platform:windows, topic:editor, crash

**Comment by dandeliondino** [comment] 2022-09-06 23:05
I don't think this was a duplicate of #54076. I've been experiencing the same issue as described here. It is only the Run window that white screens and crashes, and only if it is set to open on a different monitor from the main project. Additionally, if it is set to open on the same monitor as the editor, after it opens, I can drag it to a second monitor without it crashing.

Godot 3.5 stable
Windows 11

**Comment by SuzukiStumpy** [comment] 2023-02-10 09:22
I have this same issue (scene play freezes showing a white window on Monitor #2) with Godot v3.5.1 pre-built on Windows 10.  Running on a nVidia 2080 card.  Everything works fine on monitor #1.  I've seen similar issue with the Roon application which also freezes when launched on screen #2.  Not tried yet with the main editor window to see if that also hangs if launched on screen 2, but it certainly functions fine if launched on screen 1 and moved.
