### ISSUE TITLE
compiling android export template on Windows 7 32bit error

### ISSUE THREAD

**Issue by alvin00221** [godotengine/godot#2382] opened 2015-08-21 07:14 UTC
the error is os_android.os. please help regarding this. im not able to release game on playstore without admob. so im planning to create android export template.

**Comment by punto-** [comment] 2015-08-21 09:32
can you paste the error message you're getting? (preferably in text, not a
screenshot :p, the cmd window has a text selection mode) which admob module
are you using?

**Comment by alvin00221** [comment] 2015-08-22 06:02
C:\godot-master>scons p=android
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- could not detect gcc.
Please, make sure a path to a Mingw /bin directory is accessible into the enviro
nment PATH.

Godot Android!!!!!
scons: done reading SConscript files.
scons: Building targets ...
C:\android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt//windows-x86_6
4/bin/arm-linux-androideabi-g++ -o platform\android\os_android.os -c -DNO_STATVF
S -MMD -MP -MF -fpic -ffunction-sections -funwind-tables -fstack-protector -fvis
ibility=hidden -D__ARM_ARCH_7__ -D__GLIBC__ -Wno-psabi -march=armv6 -mfpu=neon -
mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-alias
ing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -D_DEBUG -g1 -Wall -O0 -DDEBUG_E
NABLED -fno-exceptions -DNO_SAFE_CAST -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DDEB
UG_MEMORY_ALLOC -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -D
MUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABL
ED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGD
SCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -
DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -I. -Iplatform\
android -IC:\android-ndk-r10e\platforms\android-15\arch-arm\usr\include -IC:\and
roid-ndk-r10e\sources\cxx-stl\gabi++\include -IC:\android-ndk-r10e\sources\cpufe
atures -Idrivers\builtin_openssl2 -Iplatform\android\vorbis -Idrivers\builtin_op
enssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin_openssl2\cryp
to\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\
modes platform\android\os_android.cpp
scons: *** [platform\android\os_android.os] The system cannot find the file spec
ified
scons: building terminated because of errors.



that is the error. i dont know how to fix this. i have set the environment variable of all requirements software. 

i used admob module by tumblebee. i dont know the exact. username

**Comment by alvin00221** [comment] 2015-08-22 07:14
i used fixes compile bug for android on windows.. but error still the same..

**Comment by John-35** [comment] 2015-08-27 02:20
In the file 'detect.py' in your 'platform/android' directory, you have to change the line (134) :

gcc_path=gcc_path+"/windows-x86_64/bin"

with: gcc_path=gcc_path+"windows/bin"
by

**Comment by adityanuar** [comment] 2015-10-04 06:18
i had the same problem, but the fix above me by John really helps. Thanks!

**Comment by vnen** [comment] 2015-10-30 13:41
Closing as duplicate of #1403.

**Closed by vnen** 2015-10-30 13:41 UTC
Labels: archived, bug, platform:android, platform:windows, topic:buildsystem
