### ISSUE TITLE
Freeing a Joint/Joint2D throws "Invalid ID"

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#2383] opened 2015-08-22 17:14 UTC
Something I noticed, is when a Joint has rigid bodies as nodes a, and b, when freeing the joint, the physics server (PhysicsServerSW) throws "Invalid ID", I don't know what this will cause, but my other scenes seem to be unstable, joints randomly don't connect, and the simulation isn't consistent.

*Bugsquad edit:* Initial issue was fixed, but still doesn't work with Joint2D-s.

**Comment by kakoeimon** [comment] 2016-02-23 10:38
I think this remains true for Joint2D.

**Comment by kekie1** [comment] 2017-03-30 01:47
I can confirm what kakoeimon said. This should be reopened or a new issue created for 2D joints.

**Comment by bojidar-bg** [comment] 2017-03-30 11:06
Reopening since it doesn't work for Joint2D-s (feel free to refer to df5fa62ab955437f05bfd7acdf6ed61d6d9c827e for pointers).

**Comment by Johnbpo** [comment] 2017-08-19 00:12
I confirm it doesn't work for PinJoint2D.

Here's a small demo scene to illustrate the problem.
[PinJoint2D_Issue.zip](https://github.com/godotengine/godot/files/1235954/PinJoint2D_Issue.zip)

You can grab the box, node_a and node_b are set then when you drop it, it sets them to empty paths.
You can try and free them too (it's commented).
It basically throws the error and the physics for the box just stop working altogether.

**Comment by eon-s** [comment] 2017-08-19 16:24
Confirmed on 2.1.4 beta 3.

Some notes:
 - The exclusion on the joint is not cleared on release. 
As workaround, remove the exclusion before removing the nodes from the joint.
```gdscript
pinjoint.set_exclude_nodes_from_collision(false)
```
 - The other errors on the console may not be errors, the joint should ignore if there is a missing element, maybe complain only if is invalid, but not null.

**Comment by RandomShaper** [comment] 2017-08-29 21:30
#10769 to the rescue!

**Comment by RandomShaper** [comment] 2017-11-02 19:05
Let's recapitulate.

#10769 is intended to fix the issues here for 2.1, and as far as I've been able to test, it does.
#10770 was the same for 3.0 master, which is already merged.

So, in 2.1 with #10769 merged or in master, is anyone still able to reproduce any of these issues?

**Comment by eon-s** [comment] 2017-11-03 02:45
@RandomShaper Tested your PR on 2.1 and I don't see any error with the sample project.

**Comment by RandomShaper** [comment] 2017-11-03 20:11
Thank you, @eon-s! I've removed the _Needs testing_ tag from #10769.

@akien-mga, I'd say that PR is ready to get merged and this issue to be closed. Alas, the 3.0 variant didn't include the _fixes_ annotation so manual closing is needed.

**Comment by akien-mga** [comment] 2017-11-04 10:40
Fixed by #10770.

**Closed by akien-mga** 2017-11-04 10:40 UTC
Labels: bug, junior job, topic:physics
