### ISSUE TITLE
Y Sort breaks TileMap layer highlighting

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#76474] opened 2023-04-26 12:49 UTC
### Godot version

4.0.2.stable, 4.1.dev1 (db1302637)

### System information

Windows 11, Forward+, NVIDIA GeForce GTX 1660 (531.61)

### Issue description

Highlighting TileMap layers in the editor stops working when Y Sort is enabled.

### Steps to reproduce

https://user-images.githubusercontent.com/10379487/234579030-145015a3-3f47-4efb-95e4-63f293cb86cc.mp4

### Minimal reproduction project

[TileMapLayers_Test.zip](https://github.com/godotengine/godot/files/11332945/TileMapLayers_Test.zip)

**Comment by Proggle** [comment] 2023-04-28 04:01
Probably the same bug as 73266 and the more general 72519

**Comment by kleonc** [comment] 2023-05-14 23:09
Duplicate of #73266.

**Closed by kleonc** 2023-05-14 23:09 UTC
Labels: bug, topic:editor, topic:2d
