### ISSUE TITLE
GDScript 2.0: Different behavior between debug and release mode

### ISSUE THREAD

**Issue by lemon37564** [godotengine/godot#60619] opened 2022-04-29 08:38 UTC
### Godot version

4.0 alpha6, alpha7

### System information

Linux, Vulkan Clustered

### Issue description

Below code have different behavior between debug and release mode.
It seems that the problem is on the line ```s += int_to_hex(i)```
```gdscript
extends Control

func int_to_hex(num: int) -> String:
	if num >= 0 and num < 10:
		return char(48 + num)
	else:
		return char(97 + num - 10)

func _ready():
	var s := ""
	for i in range(16):
		s += int_to_hex(i)
	$Label.text = s
``` 

### Steps to reproduce

download the minimal reproduction project and run

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8589360/test.zip)

**Comment by lemon37564** [comment] 2022-04-29 08:40
Under debug mode:
![image](https://user-images.githubusercontent.com/65079334/165911826-537125e3-0189-4b3c-87d1-14d87655db2e.png)

Under release mode:
![image](https://user-images.githubusercontent.com/65079334/165911892-5e2db803-f95a-4966-be64-3b522b3b9f10.png)

**Comment by Calinou** [comment] 2022-04-29 16:54
I can confirm this on 4.0.alpha 212989d46 (Linux, NVIDIA 510.60.02).

### 4.0.alpha

| Editor | Release export template |
|-|-|
| ![2022-04-29_18 52 48](https://user-images.githubusercontent.com/180032/165989198-efdcbe61-3d26-4d6f-9867-1160f86028ff.png) | ![2022-04-29_18 53 03](https://user-images.githubusercontent.com/180032/165989200-e380a291-6e95-4e92-82ad-39d594d1fe57.png) |

I can't reproduce this on 3.5.beta 59e84be9b though.

### 3.5.beta

| Editor | Release export template |
|-|-|
| ![2022-04-29_18 52 11](https://user-images.githubusercontent.com/180032/165989193-90667ff1-2a17-4aaa-886b-2ed6e05830ac.png) | ![2022-04-29_18 52 25](https://user-images.githubusercontent.com/180032/165989195-2938a755-4da1-426f-8e21-5bba47ed5ce5.png) |

**Comment by Faless** [comment] 2022-06-11 15:00
Possible duplicate of #59239

**Comment by akien-mga** [comment] 2022-06-23 12:38
Duplicate of https://github.com/godotengine/godot/issues/59239

**Closed by akien-mga** 2022-06-23 12:38 UTC
Labels: bug, topic:gdscript, confirmed, regression, topic:export
