### ISSUE TITLE
EditorFileDialog seems to be broken

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#3263] opened 2016-01-07 12:05 UTC
I have to admit I really like the EditorFileDialog, because it gives much more functionality. But it seems to somehow broken. No Icons appear, and if you press on some of the missing icons it crashes.
Would be cool if this gets working :-)

**Comment by akien-mga** [comment] 2016-01-07 12:16
Is that a recent regression?

**Comment by reduz** [comment] 2016-01-07 12:18
wow, i can' t really reproduce this..  maybe there is a file screwing up the preview thread?

**Comment by ndee85** [comment] 2016-01-07 12:35
Thats how the dialog looks for me
![editor_file_dialog](https://cloud.githubusercontent.com/assets/6723918/12170667/858f0682-b543-11e5-8d6e-82c70154dd7b.png)

**Comment by reduz** [comment] 2016-01-07 12:38
wow, how are you using this dialog?

**Comment by ndee85** [comment] 2016-01-07 12:44
I have a button thats shows the dialog. I set the mode to MODE_OPEN_DIR and the access to ACCESS_FILESYSTEM. Thats it.. and thats how it shows up.
Same for the normal dialog works fine.

**Comment by ndee85** [comment] 2016-01-07 13:07
Ehm.. just to make it clear.. Not that someone gets confused. I am talking about the EditorFileDialog Node which I want to use in one of my projects. In the Editor itself the file dialog works.. :+1:

**Comment by akien-mga** [comment] 2016-01-07 13:29
Hm, maybe EditorFileDialog would not be working in a non-tools build then, if it has editor-specific icons and features?

**Comment by bojidar-bg** [comment] 2016-01-14 08:00
@akien-mga I guess it is so.

**Comment by MarianoGnu** [comment] 2016-01-14 19:53
Problemas is buttons are using EditorIcons instead of Theme, same happens with FileDialog, i had it scheduled forma fixing when i had some time

**Comment by reduz** [comment] 2016-01-22 13:46
This will be fixed in 2.1 when we take a better look at how to do editor plugins

**Comment by AlexHolly** [comment] 2016-03-13 19:51
Ubuntu 64-bit
When I use .show() I get the same bugged view. On .popup() I get a game crash.

**Comment by MarianoGnu** [comment] 2016-03-16 19:00
I think there's something not clear here, as i understand EditorFileDialog was not suposed to be used on Games, just for the Editor, the reason it's available on the AddNode dialog is because the class is bounded in the class table here:
https://github.com/godotengine/godot/blob/master/tools/editor/editor_file_dialog.h#L48

I'm not sure of the consecuences of removing these lines, or if there's a reason for not using this dialog in a Game (code specific for the editor) otherwhise FileDialog and EditorFileDialog could be merged (or FileDialog deprecated)

**Comment by MarianoGnu** [comment] 2016-03-16 19:09
The "editor specific code" causing these errors are as follows:
https://github.com/godotengine/godot/blob/master/tools/editor/editor_file_dialog.cpp#L27

    mode_thumbnails->set_icon(get_icon("FileThumbnail","EditorIcons"));
    mode_list->set_icon(get_icon("FileList","EditorIcons"));
    dir_prev->set_icon(get_icon("ArrowLeft","EditorIcons"));
    dir_next->set_icon(get_icon("ArrowRight","EditorIcons"));
    dir_up->set_icon(get_icon("ArrowUp","EditorIcons"));
    refresh->set_icon(get_icon("Reload","EditorIcons"));
    favorite->set_icon(get_icon("Favorites","EditorIcons"));
    fav_up->set_icon(get_icon("MoveUp","EditorIcons"));
    fav_down->set_icon(get_icon("MoveDown","EditorIcons"));
    fav_rm->set_icon(get_icon("RemoveSmall","EditorIcons"));

EditorIcons is only available inside Editor (TOOLS enabled and/or get_tree().is_editor_hint()==true)
solution is moving these icons from tools/editor/icons to scene/resources/default_theme (and check if any of them is used in another Editor specific class, in this case it should be duplicated)

**Comment by AlexHolly** [comment] 2016-03-16 19:33
I like the small FileDialog looks much simpler and has all I need. Merging both sounds good because the code looks very similar. It would be nice to have a simple(FileDialog) and extended(EditorFileDialog) mode.

**Comment by akien-mga** [comment] 2016-07-15 09:30
What's the status on this with the new EditorPlugin API?

**Comment by AlexHolly** [comment] 2016-07-15 13:22
Game crashes.

```
func _ready():
	get_node("EditorFileDialog").popup()

ERROR: get_scene_editor_states: Index p_idx out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:331.
ERROR: get_scene_editor_states: Index p_idx out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:331.
```

![image](https://cloud.githubusercontent.com/assets/4741886/16875380/77e14990-4a9f-11e6-9187-78d34afde0c1.png)

**Comment by MarianoGnu** [comment] 2016-07-15 15:22
What the hell does edited_scene have to do with EditorFileDialog :/ it belongs to EditorNode

**Comment by reduz** [comment] 2016-07-20 22:43
Actually, this is OK, you shouldn't be able to use EditorFileDialog from the game or scene, I'm not even sure why it's allowing you to instance it

**Comment by MarianoGnu** [comment] 2016-07-21 09:56
If you block it then we can't use it for plugins u.u

**Closed** 2016-07-21 13:17 UTC
Labels: bug, topic:editor

**Comment by neikeq** [comment] 2016-07-21 16:32
@MarianoGnu you can still use them from source.

**Comment by MarianoGnu** [comment] 2016-07-21 18:58
I'll check, i supose

**Comment by kubecz3k** [comment] 2016-08-11 13:00
I don't get it, what EditorFileDialog has that's not available from regular FileDialog?
Using FileDialog in my editor plugin right now and it's working as expected.

**Comment by reduz** [comment] 2016-08-11 13:17
It needs the editor theme stuff
