### ISSUE TITLE
No autocompletion for set_shader_param

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#27774] opened 2019-04-07 16:12 UTC
**Godot version:**
Godot 3.1 Stable

**OS/device including version:**
Ubuntu 18.04 LTS 64 bits

**Issue description:**
There is no autocompletion for `set_shader_param` in gdscript

**Steps to reproduce:**
1. Create a new Sprite Node and attach a script
2. Create a new shader material in the insector
3. In a function start typing: `material.set_`
4. `set_shader_param` doesn't show in the autocomplete list

**Comment by Zylann** [comment] 2019-04-07 16:42
Tried too by attaching a `ShaderMaterial` to the sprite, it indeed doesn't appear. It doesn't even seem to detect `Material` properties either.
![image](https://user-images.githubusercontent.com/1311555/55686685-212d7000-595c-11e9-9b15-de89b5d3f0b9.png)
[ShaderParamAutocomplete.zip](https://github.com/godotengine/godot/files/3051776/ShaderParamAutocomplete.zip)

**Comment by Chaosus** [comment] 2019-07-30 13:15
Its not a bug - material by default is Material but can be casted to either ShaderMaterial or CanvasItemMaterial (for 2D). You should use "as" keyword like `var sm = material as ShaderMaterial` then sm will show set_shader_param in autocompletion. Closed by bugsquad..

**Closed by Chaosus** 2019-07-30 13:15 UTC
Labels: bug, topic:editor, topic:gdscript

**Comment by GeminiSquishGames** [comment] 2024-08-21 23:53
> Its not a bug - material by default is Material but can be casted to either ShaderMaterial or CanvasItemMaterial (for 2D). You should use "as" keyword like `var sm = material as ShaderMaterial` then sm will show set_shader_param in autocompletion. Closed by bugsquad..

This doesn't seem to be true for CanvasItemMaterial class. ``` as ShaderMaterial ``` does allow it to show up in the suggestions in autocompletion but ``` as CanvasItemMaterial ``` doesn't seem to be doing it. Been a while, maybe something broke along the way?
