### ISSUE TITLE
range() function static typing mismatch

### ISSUE THREAD

**Issue by kidManuel** [godotengine/godot#77186] opened 2023-05-17 23:34 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Pretty simple issue that I found recently: 
<img width="1308" alt="image" src="https://github.com/godotengine/godot/assets/11466523/54ab8639-15ae-4ee7-9426-7f6f78b22b5b">

I would have expected the global func range() to have a return type of Array[int], but it turns out it's just Array (no type).

### Steps to reproduce

Just create a var with an explicit type of Array[int] and try to assign a range(0, 10) to it. 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-05-17 23:47
- Duplicate of https://github.com/godotengine/godot/issues/72762.

**Closed by Calinou** 2023-05-17 23:47 UTC
