### ISSUE TITLE
Audio Effect Compressor is still affected by a sidechained audio bus that is muted.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#19630] opened 2018-06-18 18:44 UTC
**Godot version:**
Godot 3.0.3 stable

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When a compressor audio effect is sidechained with another audio bus it will still be affected by that audio bus even when the bus is muted or has the volume turned down so low that it shouldn't affect the compressor.

**Comment by jcampbellcodes** [comment] 2018-10-06 18:37
Sometimes this is a desired effect, so I'd propose that this bug be rephrased to be something like "add a pre-fader vs post-fader option for the compressor sidechain". 

Though I couldn't repro on my system (Mac OSX 10.13, Godot 3.0.5 Stable); it just defaulted to post-fader. I'll try again with a Windows 10 setup and see if it still defaults to pre-fader sidechain as you described (but in 3.0.5)

**Comment by KoBeWi** [comment] 2020-06-17 08:42
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 13:30
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 13:30 UTC
Labels: bug, topic:audio
