### ISSUE TITLE
16+ Gb ram used when click on imported Skeleton

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#38912] opened 2020-05-21 04:20 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Linux

**Issue description:**
I have import complex skeletons and they work fine, animations and loading work without problem.
**When I click on its Skeleton Godot Editor use 16+ Gb ram** (I kill it on 16gb ram usage), ofc I do not need click on skeleton in Godot editor, but if I missclick I can lost not saved changes... so its scary.
I add simple model where its hapened as example, I use much more complex models. (this example can be opened fine in Blender)

**Steps to reproduce:**
download 
[axtmp.glb.zip](https://github.com/godotengine/godot/files/4660568/axtmp.glb.zip)
and open it in Godot, then click on Skeleton - 16+ Gb will be used

**Minimal reproduction project:**
[axtmp.glb.zip](https://github.com/godotengine/godot/files/4660568/axtmp.glb.zip)

**Comment by nathanfranke** [comment] 2020-05-21 08:12
I can reproduce this in master (0b8cb945c)

Manjaro 20.0.1 KDE

Definitely needs a fix and should be backported to 3.2

**Comment by akien-mga** [comment] 2020-05-21 09:11
On phone now so it's not convenient to lookup, but this is a duplicate. There's a PR by @fire that aims to fix it by changing the Skeleton editor.

**Comment by Calinou** [comment] 2020-05-21 12:41
Duplicate of #35652.

**Closed by Calinou** 2020-05-21 12:41 UTC
