### ISSUE TITLE
@export-ed variables set after _init

### ISSUE THREAD

**Issue by coyo-t** [godotengine/godot#70575] opened 2022-12-26 04:04 UTC
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Win10

### Issue description

For whatever reason, `@export` variables get set after `_init` is called, not before. This is a problem for scripts that extend from `Resource` (IE custom texture things), as they don't have the `_ready` method to jank their way around it.

If this is intended there should be a way to specify whether they're set before or after `_init` (similar to what `@onready` does).

### Steps to reproduce

Run sample project; You can see the `TextureBinder` thats been assigned to the main scene's node in the inspector.

### Minimal reproduction project

[ExportVarsWrongOrderOfOperationsAAAAA.zip](https://github.com/godotengine/godot/files/10301453/ExportVarsWrongOrderOfOperationsAAAAA.zip)

**Comment by timothyqiu** [comment] 2022-12-26 05:07
This behavior is intended.

`_init()` is the constructor of the object. Exported properties are available after `_init()` from the perspective of outside code. So the saved values can only be set after `_init()`.

You want to update `_tex_pix` based on `source_tex` in the MRP:

```gdscript
extends Texture2D

@export var source_tex: Texture2D

var _tex_pix: Image

func _init () -> void:
	_tex_pix = source_tex.get_image()
```

Here you can define a setter for `source_tex` and initialize `_tex_pix` there:

```gdscript
extends Texture2D

@export
var source_tex: Texture2D:
	set(v):
		source_tex = v
		_tex_pix = v.get_image()

var _tex_pix: Image
```

**Comment by coyo-t** [comment] 2022-12-26 05:49
That's real unfortunate :(
For context in my actual project I'm creating dynamic textures (emulation's of ones Minecraft used to have), so I have the input textures (in this case an `AtlasTexture` for the clock sprite, and a `Texture2D` for its dial), and then create its output `Image` based on the atlastex's size.
```gdscript
func _init () -> void:
	_item_pix = sprite_path.get_image()
	_dial_pix = dial_path.get_image()
	grid = Image.create(_item_pix.get_width(), _item_pix.get_height(), false, Image.FORMAT_RGBA8)
```
I guess since I know the order they're defined in I can do something like
```gdscript
@export
var sprite_path: Texture2D:
   set(v): _item_pix = v.get_image()
@export
var dial_path: Texture2D:
   set(v):
      _dial_pix = v.get_image()
      grid = Image.create(...)
```
but it does still feel like a hack to have to do so.
I sort of get why it's done? "If its made through code things will explode since their export props haven't been set" but Eghh..
Breaking the intuition of "Things which are set in the editor will be usable when I'm in this object's initialization event" isn't a very good thing. I've apparently run into this problem previously too but not known the cause because of that intuition too.
I can't think of a good solution to this either. "Things created in the inspector have their exports init'd before `_init` is called" is _maybe_ the best? or an `_inspector_init()`? but agh very hard this is

**Comment by timothyqiu** [comment] 2022-12-26 06:15
I agree that adding a dedicated callback would help a lot. I found a related proposal, but it was closed by the author: https://github.com/godotengine/godot-proposals/issues/2708

As a workaround, if your internal state depends on other variables, does it make sense to add a separate function and call it outside? For example:

```gdscript
@export var sprite_path: Texture2D
@export var dial_path: Texture2D

var grid: Image

func create_grid() -> Image:
    # Make the image here.
    return Image.create(...)

# Or, lazy init and cache the result...
func get_grid_image() -> Image:
    if not grid:
        grid = create_grid()
    return grid
```

**Comment by coyo-t** [comment] 2022-12-26 07:33
Okay well i WAS going to do the usual GoldSRC function ptr malarky I normally do, something like:
```gdscript
var _think: Callable = _think_norm

func _think_init () -> void:
	if _item_pix == null:
		# Also create's fusia error textures here if the exports are null anyway
		...
	# ect
	if grid == null:
		grid = Image.create(_item_pix.get_width(), _item_pix.get_height(), false, Image.FORMAT_RGBA8)
	_think = _think_norm
	_think_norm()

func _think_norm () -> void:
	...

func setup () -> void:
	_think.call(self)
```
But that also ran into the same order of operations issue, since the thing which used the `grid` image as data for a sprite's texture.. cant set the texture's data since it.,. well, doesnt exist :/ plus other problems arising from trying to work around that (such as having 1 frame of the temp sprite texture before the proc texture is applied... Or would be applied if it worked -_-;)
The previous workaround of setting them with the exports having setters works.. "fine". Not happy with it but works.

I actually did come across that post on SO (which is how I learned of this oddity) but I wasn't aware there was already a an issue opened about it here, oops sorry =v="

I imagine trying to create a fix for this would have to be after 4.0's release right? I haven't looked into how export variables are handled but I'm guessing its more complex than just slapping a new `_post_init` functor to whatever handles the creation of objects. Unless it actually is, in which case wow do I look silly.

**Comment by dalexeev** [comment] 2023-04-15 05:08
You can use `NOTIFICATION_SCENE_INSTANTIATED`. See also godotengine/godot-proposals#5718.

**Comment by dweremeichik** [comment] 2023-04-24 06:53
Possible duplicate of #68427

**Closed** 2023-04-24 10:17 UTC
Labels: discussion, topic:core
