### ISSUE TITLE
[3.0] Line edit control placeholder text misspositioned when attribute align is set to center

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#13929] opened 2017-12-03 18:32 UTC
Hello,

This is a light visual issue.

The issue concerns the LineEdit control node.

When "align" property is set at "center", the inputed text's center will match the node's center. if more characters are inputed, the text will be recentred...

However, the placeholder's text won't work that way, the leftmost character of the placeholder's text will be set at the node's center.

**Comment by bojidar-bg** [comment] 2017-12-04 12:45
Looks like a partial duplicate of #5658.

**Comment by mhilbrunner** [comment] 2018-04-04 19:53
Closing as duplicate of the mentioned 5658.

**Closed by mhilbrunner** 2018-04-04 19:53 UTC
