### ISSUE TITLE
Some dropdowns in inspector fail when dropdown would go off screen (DisplayServer regression)

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#57317] opened 2022-01-27 16:50 UTC
### Godot version

4.0.alpha1.official (31a7ddbf8)

### System information

Windows 10

### Issue description

When a named enum can have many different values and is given the `@export` attribute, its dropdown menu in the inspector can lose functionality if there are more values than can fit in the "on screen".

When the mouse button is pressed, the dropdown is opened. If the mouse is over a valid selection when the mouse button is released, this value will be selected and the dropdown will close again immediately. For most users, the issue is easily worked around by pressing and holding the mouse button (once they've worked out that this is what they need to do), but pressing and holding can be an accessibility issue for some users.

Note that since the behaviour depends on screen size and the dropdown's position in the inspector, the number of values at which problems arise may not be consistent from case to case.

***

**Examples**

With 35+ values, the dropdown always closes immediately, selecting the first or second value, depending on the mouse's position:
![image](https://user-images.githubusercontent.com/61291296/151402547-43cf2105-9b1d-4587-9b17-dbe7e9e9d5f7.png)

With 34 values, the dropdown may not close if the mouse was high enough:
![image](https://user-images.githubusercontent.com/61291296/151402756-6234bdf6-6f00-438a-92c0-1e341bb945ae.png)

With 33 or fewer values, the dropdown behaves properly:
![image](https://user-images.githubusercontent.com/61291296/151402896-3876e3a2-f70d-4ca5-97df-f729f112f61b.png)

Unless the enum's position is lower on the screen:
![image](https://user-images.githubusercontent.com/61291296/151403033-fd2f12d1-ef9c-4ae1-aec1-207e7e42bb0f.png)
![image](https://user-images.githubusercontent.com/61291296/151403288-27eb2f8f-24c3-44fd-8377-c052edd534b1.png)

The problem persists when the dropdown menu has a scrollbar:
![image](https://user-images.githubusercontent.com/61291296/151404172-b06d4b56-46aa-4543-ab8d-7305d313b48b.png)

A real-world example, editing the type for a custom data layer in the new TileSet:
![image](https://user-images.githubusercontent.com/61291296/151403813-e131dc91-ac5e-4a45-8dd8-bc12ee800627.png)

Note that this _doesn't_ occur with the dropdown for an export with type `Resource`; the dropdown menu stays open as expected:
![image](https://user-images.githubusercontent.com/61291296/151404653-9cd259ce-d5e2-405d-85c7-17662aa406c2.png)
![image](https://user-images.githubusercontent.com/61291296/151404747-ea4c0b02-cd45-4270-beba-cb46b53b4f92.png)

### Steps to reproduce

1. Add a `Node` to an empty scene and attach a script with the following code.

```
extends Node

enum LengthyEnum{q,w,e,r,t,y,u,i,o,p,a,s,d,f,g,h,j,k,l,z,x,c,v,b,n,m,\
qa,wa,ea,ra,ta,ya,ua,ia,oa,pa,aa,sa,da,fa,ga,ha,ja,ka,la,za,xa,ca,va,ba,na,ma}

@export var lengthy_enum:LengthyEnum

```

(The enum may need more values, depending on resolution etc. 35 was sufficient for me.)

2. Select the Node so that it appears in the Inspector.

3. Open the dropdown menu by clicking it. It will close automatically, and whatever value was under the mouse's position will be selected.

4. Optionally, add additional export vars above the enum to see that the behaviour depends on the enum's position in the Inspector. Similarly, moving the Godot Editor window within the screen can change the behaviour.

### Minimal reproduction project

See steps above.

**Comment by Calinou** [comment] 2022-01-27 16:56
Does this occur on Godot 3.4.2?

**Comment by snailrhymer** [comment] 2022-01-27 17:36
I can't replicate it on v3.4.2.stable.official [45eaa2daf]

**Comment by snailrhymer** [comment] 2022-01-27 22:28
It can also happen with the 'view settings' in the main editor viewport:
![image](https://user-images.githubusercontent.com/61291296/151453868-55669a21-eb10-41a4-89b5-99756130acff.png)

**Comment by snailrhymer** [comment] 2022-01-28 13:21
Definitely looks to be a problem with this type of dropdown in general - one more example, choosing language from the project list:

![image](https://user-images.githubusercontent.com/61291296/151553957-5ea7c0e4-5f0b-442c-ba07-8cd4beccfb1f.png)

**Comment by KoBeWi** [comment] 2022-04-10 20:24
Sounds like #55712, but the issue was already fixed.

**Comment by akien-mga** [comment] 2022-04-11 12:46
I can reproduce the issue on Linux, at least an issue that has similar symptoms.

The problem happens when clicking on the Label section of the OptionButton (as opposed to clicking on the arrow on the right). If the popup is too big, it overlaps with the area being clicked, and thus the item below the pointer gets selected.

https://user-images.githubusercontent.com/4701338/162742261-b55b9da7-45e5-492b-8ba2-1d704207f23e.mp4

**Comment by snailrhymer** [comment] 2022-04-19 19:52
On Windows, only enums produce different the behaviours when clicking on the label vs the arrow. For the other examples (language selection and type selection), the dropdown closes immediately regardless of whether or not the arrow was clicked.

**Comment by YuriSizov** [comment] 2023-02-21 10:59
Doesn't seem to happen anymore, at least as of RC2 (on Windows 10). Since there have been multiple windowing and input related fixes in the meantime, I'll close this as fixed. Feel free to comment if it is still reproduceable on your system.

**Closed by YuriSizov** 2023-02-21 10:59 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:gui
