### ISSUE TITLE
Theme editor immediately closing after opening any theme item or simply clicking on viewport

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#72271] opened 2023-01-28 19:35 UTC
### Godot version

218bef90af2091afde3b1be816c87286c194a2a8

### System information

Windows 11

### Issue description

I think it's incorrect behaviour - clicking on theme items override or even a main viewport (regardless of 2D or 3D) immediately hides the theme editor.

![theme_editor_closing](https://user-images.githubusercontent.com/3036176/215287299-a2482ad8-09b4-45ac-9a21-12e32f99b1b0.gif)

### Steps to reproduce

Open and try to use the theme editor

### Minimal reproduction project

[TestTheme.zip](https://github.com/godotengine/godot/files/10528108/TestTheme.zip)

**Comment by Sauermann** [comment] 2023-01-28 21:29
I can confirm this on Linux X11.
Looks like this bug got introduced between Beta14 and Beta15.

**Comment by akien-mga** [comment] 2023-01-29 01:21
CC @KoBeWi

**Comment by Anixias** [comment] 2023-01-29 02:18
Just want to mention that it also automatically hides itself if you make any changes to the theme while it is set as the global (custom) theme in the project settings. It produces the following error every time:
![image](https://user-images.githubusercontent.com/22286697/215300781-7f464272-8598-4e9f-8ea2-f24e31359368.png)

**Comment by KoBeWi** [comment] 2023-01-29 11:03
When you click a stylebox, it gets edited instead of the Theme, hence the editor gets closed. I think there used to be some hack to prevent that.

As for the error, `_update_type_list()` is called with a Timer and throws error if you click the stylebox too fast. To fix it we can stop the debounce timer when the Theme gets unassigned.

**Comment by YuriSizov** [comment] 2023-01-31 14:06
> I think there used to be some hack to prevent that.

It still exists, the theme editor reports that it handles subresources of the currently edited theme, see https://github.com/godotengine/godot/blob/master/editor/plugins/theme_editor_plugin.cpp#L3715

However, I guess it doesn't prevent the edit null call from happening, which closes the editor.

**Comment by KoBeWi** [comment] 2023-01-31 14:14
`edit(null)` is needed to free the resource. Otherwise once the editor edits a resource, it will never get unloaded.

Part of this issue can be fixed now, but for complete fix I think we need a better way to handle editor persistence. I'm thinking of something like close button in the Theme editor to allow unloading the resource. Then we could make the editor an editing owner, so it doesn't receive null and allows to edit the Theme without disturbing.

**Comment by YuriSizov** [comment] 2023-01-31 14:38
So in the end all contextual editors will become persistent editors? 🤔 We "solved" the shader editor issues the same way, basically. I'm not sure this is a good direction, as it removes the perceived simplicity of Godot a bit. We also end up with a bunch of editors with their own open resource list this way, without any unified approach.

Overall, I think editing a subresource of a resource should not drop the context for the parent resource. Intuitively it doesn't make much sense. And that's where the root of the issue is.

**Comment by KoBeWi** [comment] 2023-01-31 14:52
No, the editor would be not visible until you edit a resource. Then once you edit it, you'd need to close it manually.

> Overall, I think editing a subresource of a resource should not drop the context for the parent resource.

The problem is that inspector is the "editing owner" of the Theme. Once you click StyleBox, the inspector will display it instead of the Theme, hence the editor is closed. For the Theme to keep being edited, the editor needs to be still used in some editing context.

**Comment by TokageItLab** [comment] 2023-01-31 19:03
Link the same problem https://github.com/godotengine/godot/issues/72262

**Comment by YuriSizov** [comment] 2023-02-03 11:01
I forgot to mention it before, but there was a plan to use instanced inspectors directly inside of the theme editor for all resources, which would solve the usability problem introduced here. Though this was more of a nice-to-have and thus bumped to an unknown release in a future. I could work on it for 4.0 though, if it would solve this more pressing issue,

**Comment by ababen1** [comment] 2023-02-10 12:18
I have this problem too, is there any workaround for this?

**Comment by SunderB** [comment] 2023-02-10 21:41
I can also confirm this issue. It occurs whenever pressing the + button to make a new override, and then when selecting an existing resource. (This is using a custom build I compiled today straight from master branch)

**Comment by Spartan322** [comment] 2023-02-11 11:56
It seems in some cases, most commonly the "Fonts" type, this bug causes crashes.

**Comment by YuriSizov** [comment] 2023-02-11 13:21
Crashing is tracked in another issue and should be fully fixed by https://github.com/godotengine/godot/pull/73098. The editor closing unexpectedly is partially addressed by that PR, but only for regular properties. For sub-resources it's a big inconvenience, but a proper solution has to wait for the next version, where I'll use embedded inspectors in the Theme editor and avoid using the main inspector for that. You can click the back button in the inspector to go back to the theme once you're done with a font or a stylebox.

**Comment by KoBeWi** [comment] 2023-02-11 17:10
The theme editor does not close if you use the inspector for editing instead of the in-editor buttons.
![image](https://user-images.githubusercontent.com/2223172/218271301-fedae470-f4ad-4834-a7a2-b3be21efedb9.png)

**Comment by YuriSizov** [comment] 2023-02-11 17:12
Yeah, because I'm pretty sure I explicitly call the edit method of the main inspector, so it switches context. But your workaround is nice for those who are affected.

**Comment by illlustr** [comment] 2023-02-12 20:37
I've found making the theme part of the properties for one of the `Control` nodes, and clicking/editing the theme from there, can be a temporary solution.
![Animation](https://user-images.githubusercontent.com/51869044/218335329-146dd889-df86-4039-b695-7d79babc1288.gif)

**Closed** 2023-10-06 14:58 UTC
Labels: bug, topic:editor, regression
