### ISSUE TITLE
"Thread 12 "godo:lavapipe0" received signal SIGSEGV, Segmentation fault.", "Violación de segmento (`core' generado)"

### ISSUE THREAD

**Issue by YACO99** [godotengine/godot#55375] opened 2021-11-27 02:07 UTC
### Godot version

4.0.dev.mono.custom_build.b43281c8a

### System information

ubuntu 21.10, intel i3-2377M, intel HD graphics 3000

### Issue description

Es_Argentina: cuando abro godot y crear un proyecto, aparece "Violación de segmento (`core' generado)".
y si borro ~/.config/godot/ puedo crear otro proyecto pero igual se "muere".

trate de actualizar "mesa" pero igual

(gdb) run
Starting program: /home/yaco/Godot/godot/bin/godot.linuxbsd.opt.tools.64.llvm.mono 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Nuevo Thread 0x7ffff6655640 (LWP 397654)]
Godot Engine v4.0.dev.mono.custom_build.b43281c8a - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 3.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 125534384
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
Vulkan API 1.2.162 - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 13.0.0, 256 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[Nuevo Thread 0x7fffebe7c640 (LWP 397655)]
[Nuevo Thread 0x7fffeb67b640 (LWP 397656)]
[Nuevo Thread 0x7fffeae7a640 (LWP 397657)]
[Nuevo Thread 0x7fffea679640 (LWP 397658)]
[Nuevo Thread 0x7fffe9e78640 (LWP 397659)]
[Nuevo Thread 0x7fffe9677640 (LWP 397660)]
[Nuevo Thread 0x7fffe8e76640 (LWP 397661)]
[Nuevo Thread 0x7fffcbfff640 (LWP 397662)]
[Nuevo Thread 0x7fffcb7fe640 (LWP 397663)]
[Nuevo Thread 0x7fffcaffd640 (LWP 397664)]
[Nuevo Thread 0x7fffbbfff640 (LWP 397665)]
[Nuevo Thread 0x7fffbb7fe640 (LWP 397666)]
[Nuevo Thread 0x7fffbaffd640 (LWP 397667)]
[Nuevo Thread 0x7fffba7fc640 (LWP 397668)]
[Nuevo Thread 0x7fffb9ffb640 (LWP 397669)]
[Nuevo Thread 0x7fffb97fa640 (LWP 397687)]
[Nuevo Thread 0x7fffb8914640 (LWP 397688)]
 
[Nuevo Thread 0x7fffb15fd640 (LWP 397689)]
[Nuevo Thread 0x7fffb0dfc640 (LWP 397690)]
[Nuevo Thread 0x7fff9bfff640 (LWP 397691)]
[Nuevo Thread 0x7fff9b7fe640 (LWP 397692)]
[Nuevo Thread 0x7fff9affd640 (LWP 397693)]
[Nuevo Thread 0x7fff9a7fc640 (LWP 397694)]
[Nuevo Thread 0x7fff99ffb640 (LWP 397695)]
[Nuevo Thread 0x7fff997fa640 (LWP 397696)]
Mono: Log file is: '/home/yaco/.local/share/godot/mono/mono_logs/2021-11-26_22.57.44_397650.log'
[Nuevo Thread 0x7fff93fff640 (LWP 397697)]
[Nuevo Thread 0x7fff98ff9640 (LWP 397698)]

Thread 12 "godo:lavapipe0" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7fffcaffd640 (LWP 397664)]
0x00007fffef443609 in llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::Instruction*) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1

(gdb) bt
#0  0x00007fffef443609 in llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::Instruction*) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#1  0x00007fffc0063150 in ?? ()
#2  0x00007fffc0021450 in ?? ()
#3  0x00007fffcaff4528 in ?? ()
#4  0x00007fffc00378c0 in ?? ()
#5  0x00007fffefea6ca1 in ?? () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#6  0x00007fffefe6ab31 in ?? () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#7  0x00007fffefe6bca5 in ?? () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#8  0x00007fffefe6cbf4 in llvm::InstructionCombiningPass::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#9  0x00007fffef45698d in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#10 0x00007fffef45628e in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#11 0x00007fffef45c1b4 in llvm::legacy::FunctionPassManager::run(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#12 0x00007fffef3bb7b6 in LLVMRunFunctionPassManager () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#13 0x00007ffff457f798 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#14 0x00007ffff4710d78 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#15 0x00007ffff469a8b6 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#16 0x00007ffff47a6546 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#17 0x00007ffff469f14c in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#18 0x00007ffff46a3154 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#19 0x00007ffff4637505 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#20 0x00007ffff44dc3d7 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#21 0x00007ffff4798e4a in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#22 0x00007ffff44d2205 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#23 0x00007ffff44f1929 in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#24 0x00007ffff44ef7eb in ?? () from /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
#25 0x00007ffff7653927 in start_thread (arg=<optimized out>) at pthread_create.c:435
#26 0x00007ffff76e39e4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100

### Steps to reproduce

$ sudo add-apt-repository ppa:oibaf/graphics-drivers
$ sudo apt update
$ sudo apt upgrade -y
$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.1 Mesa 22.0.0-devel (git-add883b 2021-11-26 impish-oibaf-ppa)

**Comment by qarmin** [comment] 2021-11-27 11:28
Duplicate of https://github.com/godotengine/godot/issues/50444
This is mesa, not Godot bug

**Closed by qarmin** 2021-11-27 11:28 UTC
Labels: bug, topic:core, crash
