### ISSUE TITLE
C# MoveAndSlide not moving Kinematicbody2d as expected.

### ISSUE THREAD

**Issue by samtsejerome** [godotengine/godot#41818] opened 2020-09-06 18:06 UTC
**Godot version:**
Godot  engine 3.2 stable.mono.official

**OS/device including version:**
Macbook Pro retina screen, running MacOs 10.15.6

**Issue description:**
what I did:
setup a quick project to experiment with a follow camera by moving a player 

what I expected:
MoveAndSlide used as documented to move the kinematicbody2d Node.

what happened:

the node wouldn't move when I processed user input very simply, so I then used a single  fixed velocity just to verify it worked at all  
like this: _velocity.y = .1f;  _velocity = MoveAndSlide(_velocity, Vector2.Up);
and this still didn't move the node!?

**Steps to reproduce:**

1. create a new project with a player scene like this:
<img width="233" alt="playerscene_sshot" src="https://user-images.githubusercontent.com/68197715/92331928-e6a89500-f071-11ea-948e-078f5813deeb.png">

**Minimal reproduction project:**
miimal project intnded only to move a kinematicbody downwards 
[defectreport.zip](https://github.com/godotengine/godot/files/5180068/defectreport.zip)

**Comment by DmitriySalnikov** [comment] 2020-09-06 22:51
That's your minimal project
![huCvIg8iTt](https://user-images.githubusercontent.com/7782218/92336686-f5ac3900-f0ab-11ea-9023-e2fb26ef3f59.gif)

The documentation says that move_and_slide automatically multiplies your vector by delta
![image](https://user-images.githubusercontent.com/7782218/92336730-5cc9ed80-f0ac-11ea-9ae5-ebe7e820b556.png)

**Comment by Calinou** [comment] 2020-09-06 23:44
Closing per @DmitriySalnikov's comment.

**Closed by Calinou** 2020-09-06 23:44 UTC

**Comment by samtsejerome** [comment] 2020-09-07 12:55
thx for the response and my apologies! (I thought my main project had been
using move_and_slide from the process callback so  made a mistake sorry to
waste your time!

**Comment by samtsejerome** [comment] 2020-09-07 13:14
I tried the csharp godot discord channel first but no help at all, then reproduced the problem in a test project so it looked like a bug and still does
I'm aware this works in gdscript, the point of the report  as per the title) is that it isnt via C# ( I tried it again from the physicsprocess callback instead, and same problem - see attached demo project to reproduce)
[defectreport_v2.zip](https://github.com/godotengine/godot/files/5183247/defectreport_v2.zip)

**Comment by DmitriySalnikov** [comment] 2020-09-07 14:29
This is not a bug. You pass 0.1 velocity to move_and_slide, in this function your 0.1 multiplied by delta (delta is the time difference between two frames, if you see 60fps then delta will be 1s / 60fps = 0.016s) 0.1 * 0.016 = 0.0016.  So your sprite is **moving**, but very **slowly**.
You need to increase velocity e.g. to 1.0f

Also you can check it in remote scene tree
![image](https://user-images.githubusercontent.com/7782218/92397131-e9b58b00-f12e-11ea-8ddb-f91443ebd706.png)

[More in docs](https://docs.godotengine.org/en/3.2/tutorials/physics/using_kinematic_body_2d.html#move-and-slide)

**Comment by samtsejerome** [comment] 2020-09-08 10:43
i'm soo sorry!
apologies, I've never needed to think abut the numeric valueof delta before
(particularly when I'm not referencing it explicitly)
really sorry to waste your time. I'll make sure its a bug forcertain before
raising an issue in future, good spot!
