### ISSUE TITLE
GI probe: Compress option adds green tint to scene

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#39335] opened 2020-06-06 08:43 UTC
**Godot version:**
3.2.1.stable.mono.official

**OS/device including version:**
Win10 pro 64bit, nivida GTX 1060, GLES3

**Issue description:**
Baking the GIProbe with compressed option checked adds a green tint to the scene that's not visible when compressed is unchecked.
![uncompressed](https://user-images.githubusercontent.com/8841352/83939981-5db75e80-a7e1-11ea-9ee1-80ee526e14c5.jpg)
![compressed](https://user-images.githubusercontent.com/8841352/83939978-5a23d780-a7e1-11ea-92be-4b65db004dc8.jpg)

**Steps to reproduce:**
Build GI probe without compressed checked and compare with scene after checking compressed and rebuild.

**Minimal reproduction project:**
[GIProbe.zip](https://github.com/godotengine/godot/files/4739678/GIProbe.zip)

**Comment by Calinou** [comment] 2020-06-06 12:14
Duplicate of #18449 and #32427. We should remove the `compress` property entirely at some point.

**Closed by Calinou** 2020-06-06 12:14 UTC
