### ISSUE TITLE
Frame drop using GridMap node

### ISSUE THREAD

**Issue by xavierocampos** [godotengine/godot#35177] opened 2020-01-16 01:14 UTC
I'm not an expert on Godot yet, so I'm testing the functions in as much detail as I can and now I'm testing the GridMap node for a MeshLibrary that I previously created with only 10 blocks. To start with there is a bug in detecting collisions, it only detects collisions if the nodes have a MeshInstance as a parent and a StaticBody as a child, which is not bad but I find the StaticBody > MeshInstance form more logical, so it would be nice if I accepted both forms, but the real problem is when playing the game, After making a few platforms to test the game gives some very important frame drops when using GridMap, while creating those same platforms placing block by block without using GridMap everything works fine, I made this test just to verify that the failure was not because there were too many elements on screen.

The test is done on a Corei3 3220, NVidia GT610 with 8 GB of DDR3 RAM, I couldn't give more technical details because my profile is more of a designer than a programmer.

**Edit:** It seems that I found the solution, by default the GridMap node has the Octant Size property at 8, and on my machine the FPS fell from 60 to 4, but if it is set to 1 it works correctly, shouldn't the default value be 1 then? because it is clear that such a high default value greatly affects performance and makes it seem like it is an engine error.

**Comment by Calinou** [comment] 2020-01-30 21:11
> Edit: It seems that I found the solution, by default the GridMap node has the Octant Size property at 8, and on my machine the FPS fell from 60 to 4, but if it is set to 1 it works correctly, shouldn't the default value be 1 then? because it is clear that such a high default value greatly affects performance and makes it seem like it is an engine error.

This needs to be tested further. What might work well in your specific configuration might not work well on another.

Can you upload a minimal reproduction project, please?

**Comment by Calinou** [comment] 2020-04-23 07:33
Duplicate of #28801.

**Closed by Calinou** 2020-04-23 07:33 UTC
Labels: discussion, topic:core
