### ISSUE TITLE
Can't see the menubar at the top of the editor

### ISSUE THREAD

**Issue by moonlightarcana** [godotengine/godot#14401] opened 2017-12-08 09:38 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64-bit, Godot v3.0-beta1, Intel HD Graphics 520

**Issue description:**
Cant See the menu bar at the top of the editor
![godotmenu bar](https://user-images.githubusercontent.com/29647211/33759776-9f3630c8-dc57-11e7-859c-c59ed5868543.PNG)

**Comment by Zireael07** [comment] 2017-12-08 09:40
Can you try updating the drivers? I think I've seen an issue about this, though you're on Windows and they were on Linux.

**Comment by akien-mga** [comment] 2017-12-08 09:49
There were several such issues reported by Windows 10 users with Intel IGPs, upgrading your drivers should fix it.

**Comment by moonlightarcana** [comment] 2017-12-08 10:32
I currently have the lastest version of the drivers installed.

**Comment by eon-s** [comment] 2017-12-08 11:03
Is duplicate of #8902 , 520 drivers are not fixed by Intel yet, it seems, try downgrading as explained in that issue.

**Comment by groud** [comment] 2017-12-08 11:53
OK, I close the issue as a duplicate.

**Closed** 2017-12-08 11:53 UTC

**Comment by reduz** [comment] 2017-12-08 12:00
I also had this problem on the same hardware as you, updating the drivers
fixed it

**Comment by reduz** [comment] 2017-12-08 12:01
or maybe it was installing windows updates, I don't remember

**Comment by moonlightarcana** [comment] 2017-12-08 12:13
Thanks for the all the suggestions and help. I did a rollback on the graphics drivers and issue is now solved.
Thanks for the all the speedy responses.
