### ISSUE TITLE
Crash when saving a scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37733] opened 2020-04-09 21:49 UTC
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits
GeForce GTX 1060 6GB/PCIe/SSE2
Compiled with MSVC

Each time I try to save a scene, the editor crashes in the Vulkan RenderingDevice.
The scene appears to save properly, but then the editor has to be restarted.

Project:
[VoxelTest.zip](https://github.com/godotengine/godot/files/4458802/VoxelTest.zip) (the name doesn't matter, it's just a project with an empty environment, camera and directional light)
Open `main.tscn`, and save it.

A fun part is where OpenGL32 is getting involved.
![image](https://user-images.githubusercontent.com/1311555/78943645-2ca60080-7ab4-11ea-8045-f041d44bcac6.png)

**Comment by qarmin** [comment] 2020-12-04 08:19
I can't reproduce crash with 4.0.dev.custom_build. ea7dd1be3

**Comment by qarmin** [comment] 2021-01-20 20:03
Can you still reproduce this in latest commits?

**Comment by Zylann** [comment] 2021-01-20 21:26
I won't be able to reproduce this for a little while, since I will likely switch back to Godot 4 only when it reaches its first alpha. Maybe it was fixed since?

**Comment by KoBeWi** [comment] 2022-04-25 00:34
Closing as can't reproduce.
Comment if it still happens in newest alpha.

**Closed by KoBeWi** 2022-04-25 00:34 UTC
Labels: bug, topic:editor, crash
