### ISSUE TITLE
Quitting Godot does not leave you time to confirm the save dialog

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#95279] opened 2024-08-08 10:32 UTC
### Tested versions

- Reproducible in 4.3 rc 2, and tested up to 4.2.2 stable, but might have been introduced sooner than that

### System information

Godot v4.3.rc2 - TUXEDO OS 3 22.04.4 - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

When closing Godot while having unsaved changes, a confirmation dialog to save or not show up very briefly, but does not allow you to pick a choice, and Godot closes abruptly.

[output.webm](https://github.com/user-attachments/assets/85e8bac6-10d1-4793-8215-99c5beb53a46)

The brief dialog looks like this : 

![Screenshot_20240808_114521](https://github.com/user-attachments/assets/46a78965-a6a8-453a-9334-ca597901c223)

And even if you didn't choose to save, the changes are actually saved and will be visible on the next start.

### Steps to reproduce

On small projects or empty, the dialog likely does not even show up, because Godot closes so quickly.
So might need a sizeable project to see it, you can use any of the public demos.

- Just open Godot (for some reason, it shows up that there are unsaved changes right out of the bat)
- Close Godot without saving anything
- You'll briefly see the dialog, and won't have enough time to pick a choice
- Note that, your saves are actually saved, just add a line to any script **without** saving, and close Godot, then open again, your new line will be there.

### Minimal reproduction project (MRP)

Not needed.
Any demo project would do

**Comment by akien-mga** [comment] 2024-08-08 10:59
> Just open Godot (for some reason, it shows up that there are unsaved changes right out of the bat)

I've seen that in the past but I think it's specific to the W4 demos you're testing on, as its SDK modifies project settings in a `@tool` script.

Even then, I can't reproduce the issue on https://gitlab.com/W4Games/demos/planet-crashers:

![image](https://github.com/user-attachments/assets/3c40fd73-7a7b-4b2b-ba07-12fb259e35cb)

The dialog stays there until I confirm a choice.

I also tried with non-W4 demos from https://github.com/godotengine/godot-demo-projects (which don't reproduce the first point in the steps to reproduce) and I don't see the issue either.

**Comment by akien-mga** [comment] 2024-08-08 11:02
Can you assess whether it's a crash that causes this abrupt closing, or it's somehow taking a path that leads to validating one of the buttons automatically? You might be able to put some breakpoints around the relevant logic in EditorNode to assess that.

Might also be worth checking whether this is tied to a specific editor setting, by temporarily resetting your editor settings (you can rename `editor_settings-4.3.tres`).

**Closed** 2024-08-08 12:14 UTC
Labels: bug, topic:editor, needs testing
