### ISSUE TITLE
Empty unnamed windows appear on slow double-click in FileSystem panel (Windows, StartAllBack custom taskbar)

### ISSUE THREAD

**Issue by Bronuh** [godotengine/godot#95863] opened 2024-08-20 15:19 UTC
### Tested versions

- Reproduced in versions `4.3-dev4` - `4.3`
- Not reproducible in `4.2.2` - `4.3-dev3`

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5176) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When performing a slow double-click (as when attempting to rename a file or folder) on any item in the `FileSystem` panel of the Godot editor, an empty unnamed window appears in the taskbar. **This issue allows multiple empty windows to open with further clicks**. These empty windows do not automatically close even when the main editor window is closed. Instead, they close in batches when attempting to switch to them.

### Steps to reproduce

1. Open any project in Godot version 4.3-dev4 or later.
2. In the FileSystem dock, slowly double-click any file or folder.
3. Continue clicking.
4. Observe the taskbar where empty unnamed windows start to appear.
![PowerToys_xsU9aC9rVM](https://github.com/user-attachments/assets/23961748-cc6a-4948-8a9b-2ddd0cfc80bf)

### Minimal reproduction project (MRP)

N/A

**Comment by Bronuh** [comment] 2024-08-20 16:35
upd: Additional testing revealed that this bug does not occur in KDE Plasma (both X11 and Wayland). The issue seems to be specific to Windows.

**Comment by Bronuh** [comment] 2024-08-20 18:16
upd2: When running Godot in compatibility mode, the bug does not occur.

**Comment by Bronuh** [comment] 2024-08-20 18:56
upd3: It seems that the bug is caused by using the classic StartAllBack taskbar in Windows 11. However, this problem still did not occur before version 4.3-dev4.

**Comment by JekSun97** [comment] 2024-08-20 21:04
I can't reproduce this problem
Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

**Comment by Hilderin** [comment] 2024-08-21 20:53
I was able to reproduce only when StartAllBack: Windows 11 is installed.
In fact on my PC, each time a tooltip is displayed a new window is created in the taskbar.

https://github.com/user-attachments/assets/4cdcc772-88d3-476e-8c75-b37ca8304eca

**Comment by CantWeAllDisagree** [comment] 2024-09-10 00:28
Yeah its def startallback been using godot all month installed startallback the otherday and was having the same issue. 

Something Im wondering though is if this is causing any kind of memory leak? Since the windows dont close automatically and that kinda makes me think...

**Comment by Jamsers** [comment] 2024-09-18 05:31
Can confirm this is an issue with StartAllBack - unfortunately there's no way to report issues to the StartAllBack developer. On heavier projects, this issue also causes hitching in Godot everytime phantom window appears on the taskbar.

**Comment by permster** [comment] 2024-09-18 07:06
I'm running the latest 3.8.8 version and the issue is still present. To get rid of the issue you can turn off "Use enhanced classic taskbar". Not a great workaround but if this is severely hindering someone at least there's a way around it without completely uninstalling.

I have sent an email to the "if you have questions" email address listed in my original StartAllBack license purchase email to see if someone will respond. I also provided a link to this GitHub issue. Crossing my fingers.

**Comment by akien-mga** [comment] 2024-09-20 10:05
Also confirmed by @magian1127 in #97177.

**Comment by akien-mga** [comment] 2024-09-20 10:07
It would be useful to [bisect](https://docs.godotengine.org/en/stable/contributing/workflow/bisecting_regressions.html) which Godot changes between 4.3-dev3 and 4.3-dev4 caused this issue with StartAllBack.

The two commits would be 36e943b6b (4.3-dev3) and df78c0636 (4.3-dev4).

**Comment by Simplestas** [comment] 2024-09-20 10:23
This was fixed in StartAllBack 3.8.9.

**Comment by Jamsers** [comment] 2024-09-20 11:00
Can confirm on my end - issue was fixed by StartAllBack 3.8.9.

**Comment by akien-mga** [comment] 2024-09-20 12:41
Amazing, thanks! Closing as fixed then.

**Closed by akien-mga** 2024-09-20 12:41 UTC
Labels: bug, platform:windows, topic:editor, confirmed, topic:thirdparty, regression
