### ISSUE TITLE
Skeleton3D has bone indexes unpredictably shuffled around when importing GLTF

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#61641] opened 2022-06-02 18:56 UTC
### Godot version

4.0 alpha 9

### System information

Windows 10, Vulkan, NVIDIA GTX 850M

### Issue description

Every time a new GLTF scene containing a complex character skeleton is exported from Blender and then imported into Godot, the bone indexes are shuffled around and cause unpredictable animation and skeleton modification behaviors, requiring me to manually re-add the model to the player scene and change the modified bone indexes in the SkeletonModificationStack3D in order to fix the problems.

Note 1: This happens even if I do not modify anything in the Blender scene. I just need to export to a new glb file and Godot shuffles the indexes and ordering around when importing. The imported scene may stay the same if I re-export it in the same Blender session, but if I just close Blender, open it again and then try to re-export the scene, it is already unpredictable.

Note 2: This does not happen in the 3.x branch of Godot. The bone indexes and ordering are preserved as expected.

How the scene cointaning the model looks when everything is in place:

https://user-images.githubusercontent.com/79013106/171686022-137469d5-6198-411c-8b08-c1c4c1e8c6f3.mp4

How the scene containing the model looks after just closing and opening Blender and re-exporting the model without any modifications in the blender scene:

https://user-images.githubusercontent.com/79013106/171705250-7e15137f-5ecb-4d5e-92dd-0f7c0db5b864.mp4

 (This is random, I never know what kind of crazy shape the character will take in the next export)

### Steps to reproduce

Create a character with a complex armature in Blender (in this case, I used rigify and only exported deformation bones), export it to glb, add the model to a scene and set up the scene. Then try closing Blender, opening it again, and re-exporting the character to the same file and watch the scene that contains the model break with bone ordering issues.

**Comment by TokageItLab** [comment] 2022-06-03 06:40
I think this is a problem with Blender exporter.

**Comment by antourenein** [comment] 2022-06-03 06:47
> Also, can you try specifically Blender 3.2, the unreleased version?

It seems exporting from from this version does keep the bone indexes stable and essentially fixes the problem... although it has created its own set of problems, such as some bones being strangely twisted.

![image](https://user-images.githubusercontent.com/79013106/171801812-6e368801-33db-4650-b7fc-ac1d44d11260.png)

I wonder if that is something I have to fix myself in the scene. I'll investigate further when I have some more time.

**Comment by fire** [comment] 2022-06-03 06:54
Please try to contact the gltf blender team. https://github.com/KhronosGroup/glTF-Blender-IO/issues @julienduroure

**Comment by antourenein** [comment] 2022-06-03 17:13
Upon further inspection and testing, it seems Blender 3.2 is in fact twisting the bones strangely on export, it even gets twisted when re-importing the GLB into Blender. I'll try to open an issue over there.

However I still find it kinda strange that Godot 3.x imports a Blender 3.1 GLB with consistent bone indexes every time, while they get all messy in Godot 4.0 with the same files...

**Comment by antourenein** [comment] 2022-06-03 17:15
Upon further inspection and testing, it seems Blender 3.2 is in fact twisting the bones strangely on export, it even gets twisted when re-importing the GLB into Blender. I'll try to open an issue over there.

However I still find it kinda curious that Godot 3.x imports a Blender 3.1 GLB with consistent bone indexes every time, while they get all messy in Godot 4.0 with the same files...

**Comment by julienduroure** [comment] 2022-06-03 17:20
@antourenein For Blender issue, please open a ticket here [1] with your test file. Thanks!

[1] : https://github.com/KhronosGroup/glTF-Blender-IO/issues

**Comment by TokageItLab** [comment] 2022-06-03 20:34
One thought that comes to mind is the possibility that the sorting algorithm has changed in Godot4. I don't know if this is true or not, but if the bone indexes are ordered by hierarchical and use *unstable sort (https://en.wikipedia.org/wiki/Stable_sort)*, it is possible that they could be randomized on import.

**Comment by antourenein** [comment] 2022-06-04 03:21
Alright, I created a minimum representation of the model and its blender scene, which reproduce all the problems without needing to carry the entire original model.

I replaced it with a simple dummy and removed its huge list of animations, and left it with the idle animation only, for simplicity's sake.

Here's a folder with a minimally similar setup to the one I'm using in my project:

[dummy-scene.zip](https://github.com/godotengine/godot/files/8836907/dummy-scene.zip)

The structure looks like this:
![image](https://user-images.githubusercontent.com/79013106/171977145-eb5f41ee-b5ca-445b-bf3f-c86d3248b962.png)

The scene has a simple AnimationTree setup and a LookAtTarget node, which is the target the SkeletonModificationStack3DLookAt references (if it doesn't work, just move the node around the structure and it should cache)

![image](https://user-images.githubusercontent.com/79013106/171978387-e91c4423-9a28-4ba5-9fe7-8a1f7c1f0948.png)

The "original" folder contains the gltf exported from Blender 3.1 that works with the "dummy-setup.tscn" without problems. This is the same "dummy.gltf" that is in the root. The "alt" folder contains a gltf that was exported after closing and reopening Blender 3.1. If you replace the "dummy.gltf" and its binary in the root folder with the one in the "alt" folder, the "dummy-setup.tscn" looks just utterly broken.

I've included an export from Blender 3.2 in the "blender3.2" folder, too, for reference.

Now, here is the blend file, so you can try the export process yourselves and investigate what might be happening:

[dummy-blend.zip](https://github.com/godotengine/godot/files/8836915/dummy-blend.zip)

This blend file has my gltf export settings saved, too.

**Comment by TokageItLab** [comment] 2022-06-04 06:32
If you open `alt/dummy.gltf` and `original/dummy.gltf` in a text editor instead of opening them in Godot, you can see that the order of the nodes in them is different. So, it is not a bug in Godot for now.

Previously, we changed to use BoneName instead of BoneIdx in some Class to solve this problem, but it still looks unstable. And I am planning to discontinue it in #61596.

---

I can think of an alternative solution to this: after building the BoneTree in Impoter, reorder the items in the same level of the tree by BoneName and reassign the BoneIdx, which will generate a same BoneIdx regardless of the order of the nodes, as long as the number of bones does not change.

However, as a side effect, the order of the tree on gltf is different from the order of the tree in Godot. For example, the little finger may be listed before the thumb. Apart from that, we can stabilize the imported BoneIdx.

How do you think @fire?

**Comment by fire** [comment] 2022-06-04 07:09
Fixed in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1659

**Comment by antourenein** [comment] 2022-06-06 00:13
I tried out exporting the scene from a new daily build of Blender 3.2 RC and it seems all problems relating to bone indexes really have gone away, as well as the strange twisting of bones!

**Comment by TokageItLab** [comment] 2022-08-31 02:49
I assume the shuffling of the bone ID is an exporter issue, not an importer issue, and that it was resolved in https://github.com/godotengine/godot/issues/61641#issuecomment-1146554954.

**Comment by QuePasitos** [comment] 2022-11-07 15:15
@antourenein Shame on you Julien you worthless loser slave. 

Shame on you cheap loser slave for openly promoting those stupid clown daft idiots (I am referring to that disgusting red 8-letter word which is pinned on the building in your trashy "Earthbound Dimensions Godot 4 Port" game ). 
Death to you and death to every loser slave supports those stupid slaves. 
You're an open promoter of racism and stupidity by promoting those idiots. Death to the stupid "health" and every dumb loser idiot slave who works for that trashy area. 

You showed nothing other that how stupid and cheap you mainstream propaganda clowns area. Death to "universities". Death to every low life lower clown who uses those stupid and childish and pathetic "prefixes" when mentioning first names. Death to open source. Hope you have a tragic life and painful death.

**Comment by julienduroure** [comment] 2022-11-08 05:31
This bug is fixed on Blender side since June, this ticket can be closed!

**Comment by fire** [comment] 2022-11-08 08:57
Sounds good. Can close any time.

**Closed** 2022-11-08 11:12 UTC
Labels: bug, topic:import, topic:animation, topic:3d
