### ISSUE TITLE
slow gui resizing Editor window

### ISSUE THREAD

**Issue by MithosMoon** [godotengine/godot#75187] opened 2023-03-21 15:37 UTC
### Godot version

4.0.1 (also 4.0)

### System information

Ubuntu 20.04, GLES and Forward, Gtx 1050

### Issue description

Gui is slower than with Godot 3.5 especially when resizing editor window. 
There is no difference, wether you have scenes loaded or not.

https://user-images.githubusercontent.com/49408918/226658479-32ae0533-5d3e-4929-9972-172ed80aad9a.mp4

### Steps to reproduce

1. Open Godot 4 editor
2. tear window down to get smaller window
3. grab window in the corner to resize
4. watch window artifacts show up while resizing (sometimes visible for seconds)

### Minimal reproduction project

"N/A"

**Comment by Calinou** [comment] 2023-03-21 16:41
- Duplicate of https://github.com/godotengine/godot/issues/39222.

**Closed by Calinou** 2023-03-21 16:41 UTC

**Comment by robmart** [comment] 2025-05-10 16:57
> * Duplicate of [Grabbing and moving Godot window is laggy on Linux (NVIDIA with Allow Flipping enabled) #39222](https://github.com/godotengine/godot/issues/39222).

Is this really the same issue? I have the re-sizing problem on windows 11, but not the dragging problem.
