### ISSUE TITLE
cant connect to host  http://127.0.0.1/assetlibrary/api

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#10011] opened 2017-08-01 04:49 UTC
Ubuntu 14.04
Godot 3.0 alpha

when i click on the asset store i got this error message:
can't connect to host  127.0.0.1/assetlibrary/api

**Comment by bojidar-bg** [comment] 2017-08-01 08:09
Looking at the code, it depends on #7147:
```
	// FIXME: Reenable me once GH-7147 is fixed.
	/*
	repository->add_item("godotengine.org");
	repository->set_item_metadata(0, "https://godotengine.org/asset-library/api");
	*/
	repository->add_item("localhost");
	repository->set_item_metadata(/*1*/ 0, "http://127.0.0.1/asset-library/api");
```

Guess we might close this one, as you are simply trying to connect to the (only one configured) localhost asset library.

**Comment by akien-mga** [comment] 2017-08-01 09:45
Yes, if it bothers users we can disable localhost too, but I considered it might be useful to test developments for #7147 locally.

**Comment by akien-mga** [comment] 2017-09-04 09:44
Closing as it's not a bug.

**Closed by akien-mga** 2017-09-04 09:44 UTC
Labels: archived
