### ISSUE TITLE
Godot Uses far lot CPU power than expected

### ISSUE THREAD

**Issue by MinaRashad** [godotengine/godot#37606] opened 2020-04-05 13:19 UTC
**Godot version:**
Godot 3.2 stable
Ubuntu
**Issue description:**
While using Godot to download from the templates, godot unexpectedly uses far more cpu power than expected, it uses alone 1/3 of computer resources

![Screenshot from 2020-04-05 15-12-44](https://user-images.githubusercontent.com/39602891/78499384-a5255e00-7750-11ea-83a3-d0b40828a7d6.png)
![Screenshot from 2020-04-05 15-13-10](https://user-images.githubusercontent.com/39602891/78499383-a5255e00-7750-11ea-9077-1e05441966f0.png)

Edit: for some reason, godot has many processes, although iam opening one window

Update: My OS restarted, I checked the /proc/sys/kernel/panic its value was not zero, meaning that something happened and caused kernel panic

**Comment by Calinou** [comment] 2020-04-05 18:09
Duplicate of #35868.

**Closed by Calinou** 2020-04-05 18:09 UTC
