### ISSUE TITLE
Some junk icon warnings in new project

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#21646] opened 2018-09-01 06:17 UTC
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10

**Issue description:**
If you create and run a new project you can observe these warnings in console window..
![image](https://user-images.githubusercontent.com/3036176/44943040-a3065b00-adc7-11e8-9740-fb9dc023af14.png)

**Comment by akien-mga** [comment] 2018-09-01 08:30
Duplicate of #21072.

**Closed by akien-mga** 2018-09-01 08:30 UTC
Labels: bug, topic:core
