### ISSUE TITLE
Convert resource files to binary on export

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6709] opened 2016-10-04 17:50 UTC
Feature request.

So **.tres** and **.xml** files (which are not `PackedScene`, as it's already handled) can get converted to binary on export like it's possible now with scenes.
If you inspect a packed game it's a bit ugly that the scenes are in binary but `.tres` files are still plain text.

**Comment by bojidar-bg** [comment] 2017-02-23 21:02
How is this issue going with export changes on master?

**Comment by homer666** [comment] 2017-05-31 21:32
Bumping for interest. What are the current state of things regarding this?

**Comment by Noshyaar** [comment] 2018-04-07 07:31
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by tavurth** [comment] 2018-08-11 12:37
This issue is still relevant, as the `tscn` files are still present in plain text.
To reproduce, export your project to Linux, and open the `pck` file with any text editor.

**Comment by tavurth** [comment] 2018-08-11 12:52
Duplicate of https://github.com/godotengine/godot/issues/6709

**Comment by Noshyaar** [comment] 2018-08-11 12:58
Since #12452 is already milestoned. I'll close this one. Thank you! :)

**Closed by Noshyaar** 2018-08-11 12:58 UTC
Labels: feature proposal, topic:editor
