### ISSUE TITLE
cannot reference static callable in static var

### ISSUE THREAD

**Issue by A-Hugh-Mann** [godotengine/godot#78024] opened 2023-06-09 00:07 UTC
### Godot version

4.1.dev.e7d2e4968

### System information

Arch Linux

### Issue description

When trying to define a static var as some static function an error prevents script from working. Except to be able to do this, haven't seen document anywhere that it can't be done.

### Steps to reproduce

create a new script:

```gdscript
class_name SomethingStatic
static var something: Callable = SomethingStatic._static_func
static func _static_func() -> void:
    pass
```

you get error:
Error at (3, 50): Cannot find member "_static_func" in base "SomethingStatic".

similar error when defining the func before the var, or when doing this with a func from another script.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-06-09 06:21
Duplicate of #41919.

**Closed** 2023-06-09 07:05 UTC
Labels: bug, topic:gdscript
