### ISSUE TITLE
[Godot 4.3 Dev 3 Net] GodotTools.OpenVisualStudio.exe is missing

### ISSUE THREAD

**Issue by CypherDoesStuff** [godotengine/godot#88448] opened 2024-02-17 16:52 UTC
### Tested versions

4.3 Dev 3

### System information

Godot v4.3.dev3.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

While using Visual Studio as dotnet editor in 4.3 Dev 3, Godot fails to find OpenVisualStudio.exe in GodotSharp tools. Looking at the location, the file doesn't exist. Though the exe is there in 4.3 Dev 2.
> /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:279 - Error when trying to run code editor: VisualStudio. Exception message: 'An error occurred trying to start process 'E:/Godot/Godot_v4_3-dev3_mono_win64-b59039bd/Godot_v4.3-dev3_mono_win64/GodotSharp/Tools\GodotTools.OpenVisualStudio.exe' with working directory 'D:\Godot\4.3Testing'. The system cannot find the file specified.'

### Steps to reproduce

1. Set Dotnet external editor to Visual Studio
2. Launch any .cs script from godot.

### Minimal reproduction project (MRP)

[4.3Test.zip](https://github.com/godotengine/godot/files/14319560/4.3Test.zip)

**Comment by cjohnson57** [comment] 2024-02-18 02:30
There are actually files there, just none of them have the .exe extension
![image](https://github.com/godotengine/godot/assets/30701749/6de3ff78-d929-4229-8b21-d516a536964d)

**Comment by raulsntos** [comment] 2024-02-18 04:43
Duplicate of https://github.com/godotengine/godot/issues/88447

**Closed by raulsntos** 2024-02-18 04:43 UTC
