### ISSUE TITLE
Classes are unknown to themselfes

### ISSUE THREAD

**Issue by scayze** [godotengine/godot#19983] opened 2018-07-05 14:09 UTC
3.0

Trying to create a new class, of the same type, inside the class, throws an error.

If that sentence didnt make any sense to you, check out this example:

```
extends Node

class Value:
	var x = 0.0
	
	func _init(px):
		x = px
	

	func mul(t):                    #
		return Value.new(x*t.x) # <- Parser Error: Identifier not found: Value
                                        #

func _ready():
	var v1 = Value.new(5)
	var v2 = Value.new(7)
	
	print(v1.mul(v2).x)
```

**Comment by volzhs** [comment] 2018-07-05 14:21
duplicated of #19345

**Comment by mhilbrunner** [comment] 2018-07-05 14:40
Closing as duplicate of #19345

**Closed by mhilbrunner** 2018-07-05 14:40 UTC
