### ISSUE TITLE
Freeing node causes unexpected behavior around tree exiting

### ISSUE THREAD

**Issue by carrollj** [godotengine/godot#83647] opened 2023-10-19 23:11 UTC
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Godot v4.2.beta1.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When QueueFree or Free is called on a node in C#, a few issues occur:

The Node is disposed by the time TreeExiting is emitted
_ExitTree is never called
_Notification never receives NOTIFICATION_EXIT_TREE

This does not occur when removing the node with RemoveChild, or when freeing the node in GDScript

### Steps to reproduce

The actual reproduction steps are pretty simple. Just call QueueFree or Free on a node.

I've attached a minimal project that can be run and gives more information. Here is the output from running that project:

![image](https://github.com/godotengine/godot/assets/10149189/20f59d28-6bd0-4494-9be7-1edbd1d0d750)

Each script has this structure, the only difference being one of them calls ```GetParent().RemoveChild(this)``` instead of ```QueueFree()``` in the ```_Process()``` method:

    [Signal] public delegate void InitializedEventHandler();

    public override void _Ready()
    {
	    Print("Starting C# QueueFree  Example...");
        TreeExiting += Cleanup;
        Initialized += () => Print("init");
    }

    public override void _Process(double delta) => QueueFree();

    public override void _Notification(int what)
    {
        if (what == (int)NotificationExitTree)
            Print("Notify Exit");
    }

    public override void _ExitTree() => Print("_exit_tree");

    public void Cleanup()
    {
        Print("cleanup");
        try
        {
            EmitSignal(SignalName.Initialized);
        }
        catch (Exception ex)
        {
            PrintErr(ex.Message);
        }
    }

### Minimal reproduction project

[TreeExitingBugMVP.zip](https://github.com/godotengine/godot/files/13048310/TreeExitingBugMVP.zip)

**Comment by carrollj** [comment] 2023-10-19 23:30
Saw that 4.2 beta 2 was release earlier today so I tested in a few more versions:

Working
v4.1.1.stable.mono.official [bd6af8e0e]
v4.1.2.stable.mono.official [399c9dc39]
v4.2.dev1.mono.official [0c2144da9]
v4.2.dev2.mono.official [da81ca62a]
v4.2.dev3.mono.official [013e8e3af]

Bug exists
v4.2.dev4.mono.official [549fcce5f]
v4.2.beta2.mono.official [f8818f85e]

So it looks like it was introduced in 4.2 dev 4

**Comment by bitsawer** [comment] 2023-10-20 00:06
Thanks for the report. Seems like a duplicate of https://github.com/godotengine/godot/issues/82279, which might get fixed by https://github.com/godotengine/godot/pull/83262 or an alternative solution. Closing this issue to keep discussion in one place.

**Closed by bitsawer** 2023-10-20 00:06 UTC
