### ISSUE TITLE
Run project -> project manager [3.0beta1]

### ISSUE THREAD

**Issue by DarkEngineer** [godotengine/godot#14375] opened 2017-12-07 12:50 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot beta1, windows 8 64-bit

**Issue description:**
After click on run project instead my application project manager is shown and in remote window there is a this:
![error](https://user-images.githubusercontent.com/3199618/33716010-d6493172-db54-11e7-9df1-a9de20931829.PNG)
but it should be something like this:
![err](https://user-images.githubusercontent.com/3199618/33716139-57288540-db55-11e7-975e-5f7c874aecb4.PNG)

**Steps to reproduce:**
run project (F5)

**Comment by akien-mga** [comment] 2017-12-07 12:58
Thanks for the report. That's a duplicate of #11391 which is fixed in the master branch.

**Closed by akien-mga** 2017-12-07 12:58 UTC
