### ISSUE TITLE
GCC internal compiler error on Ubuntu 18.04.1 on ARMv7

### ISSUE THREAD

**Issue by gexpult** [godotengine/godot#30908] opened 2019-07-29 04:41 UTC
**Godot version:**

Building from master branch (3.1)

**OS/device including version:**

OS: Ubuntu 18.04.1-3.10 (ARM v7)
GPU: Mali 450 MP2 (OpenGL ES 2.0)

**Issue description:**

Expected: Godot builds successfully.
Actual: Compiler error in function.c

```
In file included from ./core/cowdata.h:36:0,
                 from ./core/ustring.h:35,
                 from ./core/color.h:35,
                 from ./core/variant.h:39,
                 from modules/gdnative/gdnative/dictionary.cpp:33:
modules/gdnative/gdnative/dictionary.cpp: In function 'godot_variant godot_dictionary_get_with_default(const godot_dictionary*, const godot_variant*, const godot_variant*)':
./core/os/memory.h:108:64: internal compiler error: in assign_temp, at function.c:968
 #define memnew_placement(m_placement, m_class) _post_initialize(new (m_placement, sizeof(m_class), "") m_class)
                                                ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/gdnative/gdnative/dictionary.cpp:182:2: note: in expansion of macro 'memnew_placement'
  memnew_placement(dest, Variant(self->get(*key, *def)));
  ^~~~~~~~~~~~~~~~
```

**Steps to reproduce:**
Attempt to build on Odroid C1+ with Ubuntu minimal, adding Lubuntu desktop.
Build command:
`scons platform=x11 tools=no target=release_debug bits=32`

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-07-29 06:59
That's a duplicate of #16100, which should be fixed in the `3.1` branch with #25340.

What exact GCC version do you have? AFAIK Ubuntu 18.04 should have GCC 7.4.0, where this bug is supposed to be fixed. (CC @marxin)

**Comment by marxin** [comment] 2019-07-29 07:04
> What exact GCC version do you have? AFAIK Ubuntu 18.04 should have GCC 7.4.0, where this bug is supposed to be fixed. (CC @marxin)

Yep, please use at least GCC `7.4.0`. Note that version 7 will be out of support soon.

**Comment by gexpult** [comment] 2019-07-29 07:05
I'm using GCC 7.4.0.

**Comment by marxin** [comment] 2019-07-29 07:09
> I'm using GCC 7.4.0.

Then please create a pre-processed source file (`-E` option) and attach it here. And please provide a full command line.

**Comment by akien-mga** [comment] 2019-07-29 07:24
> Then please create a pre-processed source file (-E option) and attach it here.

For that, use `CCFLAGS="-E"` in the `scons` command line.

> And please provide a full command line.

To see that, use the `verbose=yes` SCons option.

So something like ` scons platform=x11 tools=no target=release_debug bits=32 verbose=yes CCFLAGS="-E"`

**Comment by clayjohn** [comment] 2020-07-11 06:47
No response, so closing. If this is still an issue, we can re-open.

**Closed by clayjohn** 2020-07-11 06:47 UTC
Labels: bug, topic:buildsystem
