### ISSUE TITLE
KinematicBody2D wobbles slightly when on the floor at certain scaling options.

### ISSUE THREAD

**Issue by 9BitStrider** [godotengine/godot#29341] opened 2019-05-31 11:28 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 Professionsal 64 Bit
Intel HD Graphics 620
(Unsure of CPU. Don't have access to the PC atm) 

**Issue description:**
When walking on the floor, my player node (Kinematicbody2d) very slightly bounces up and down as it walks on the tilemap object. Pixel snap is on. And nothing seems to be affecting it's Y velocity while it's on the floor. Odder still, this is only visible when the game resolution is displayed at 3x, 4x, or full screen. 1x, 2x, and maximized don't have this visual anomaly. (At least.. Not on a 1080p screen anyway. I haven't tried other resolutions yet). 

https://ibb.co/7gkJfSD (Notice the pixels of the sprite and the tiles are not flush with one another.) 

**Steps to reproduce:**
Walk on the floor. 

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2019-05-31 16:55
Any reproduction project? Maybe it's something with Tilemap? (like, holes in colliders)
I couldn't reproduce it with provided steps in official platformer demo.

**Comment by 9BitStrider** [comment] 2019-05-31 17:05
I'll whip one up ASAP. I would just upload what I already had but I overwrote the game with an older build by mistake while making a backup. Older build has no such issue. I'm sure it'll pop up again as I re-add what I lost.

**Comment by girng** [comment] 2019-06-01 05:49
@9BitStrider when you say "Older build" do you remember the commit? could help isolate what code was modified between versions (assuming it's a real bug)

**Comment by 9BitStrider** [comment] 2019-06-01 18:22
https://github.com/9BitStrider/mega-man-chronicles

I uploaded more to my GitHub. The bug happened again after turning on the option to view collision shapes.

**Comment by 9BitStrider** [comment] 2019-06-01 22:53
Starting to think the issue has to do with the slidebox CollisionShape2D node in the player scene. After more testing, the player can dash without issue as the other two characters. It's only when the scene swaps between the standing hitbox, and the sliding one for Mega Man himself.

**Comment by 9BitStrider** [comment] 2019-06-01 23:07
Confirmed. The issue started when I made the slide box a little bit longer to make it easier to slide over one block wide gaps. My guess is the jitter comes from the move and slide function as it's colliding with the floor, but also a chunk of the walls of each tile. Apologies for wasting your time.

**Comment by KoBeWi** [comment] 2019-06-02 00:13
> Everything is working as it should.

Closing then.

**Closed by KoBeWi** 2019-06-02 00:13 UTC
Labels: bug, needs testing, topic:physics
