### ISSUE TITLE
Particles2D causing tearing

### ISSUE THREAD

**Issue by splite** [godotengine/godot#17694] opened 2018-03-22 12:19 UTC
**Godot version:**
Steam version (3.0.2.stable.official)

**OS/device including version:**
Windows 10
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2

**Issue description:**
When adding any Particle2D node, whole scene start tearing horribly when moving camera.
If i hide Particle2D node IN EDITOR, tearing stops. If i hide Particle2D in-game via script, tearing still occurs.

**Steps to reproduce:**
Add Particle2D to scene, set texture, add material (no need to modify anything)
Play
Move Camera2D

**Minimal reproduction project:**
[TearingUnderParticles2D.zip](https://github.com/godotengine/godot/files/1837441/TearingUnderParticles2D.zip)

**Comment by girng** [comment] 2018-03-23 03:15
hmm, nice example. unfortunately i can't reproduce this. moving is very smooth. no tearing anywhere.

gtx 960, win10

**Comment by splite** [comment] 2018-03-23 09:20
1) Ok, looks like it doest glitch always (i dont see the tering right now, but when it hit, its terrible) - dont know why, mybe its something with pc uptime?

2) Turning v-sync OFF solved the issue, (sorry, forget to mention that...) maybe your 120hz monitor is reason why you cant see tearing?

At first i thought it was becouse of Light2D on my torch, but found out its Particles2D (sorry for wrongly named minimal reproduction project :) )

Still investigating, I will update this issue just after I find out more.

**Comment by eon-s** [comment] 2018-03-23 10:18
Cannot reproduce on Linux with AMD, but 60 hz monitor...

Try forcing 120fps on project settings (search for fps on project settings, it should be under "debug").

**Comment by splite** [comment] 2018-03-23 10:40
Happening again, this time i made a (60fps) gif:

You are looking at TileMap + ParallaxBg with two layers, one with some tilemaps (other hauses) + bg sprites in another ParallaxLayer.

![particles2d_tearing](https://user-images.githubusercontent.com/4945875/37824741-e7157628-2e8d-11e8-9fb7-848e4ca7d735.gif)
(ok, gif doesnt look THAT horrible, but its only small cut of screen)


This one looks like there are triangles? (or not, idk...)
![tearing2](https://user-images.githubusercontent.com/4945875/37824707-cdbca1ce-2e8d-11e8-8650-af0e41ccabd3.png)

others looks like this one (nothing special to see, just lines):
![tearing1](https://user-images.githubusercontent.com/4945875/37824942-7fe5e824-2e8e-11e8-9469-e122afbca152.png)

Again, tearing does not appears when i hide Particles2D node (smoke from chimey)

**Comment by splite** [comment] 2018-03-23 10:54
After forcing 120 fps it looks (subjectively, idk how to measure it :) ) even worse.

**Comment by splite** [comment] 2018-03-23 13:44
Found one more thing: if i maximalize window (not fullscreen, just maximalize), tearing disapears (almost, at least it is negligible) (using `[display] window/stretch/mode="2d" window/stretch/aspect="keep"`)

**Comment by splite** [comment] 2018-03-23 14:00
No visible difference between Steam version and downloaded (x64) version, tearing in both is the same. Downloaded x32 version is tearing too (subjectively not so much but as i say, its hard to measure :) )

I think now is the right time to learn how to compile godot... :)

**Comment by girng** [comment] 2018-03-23 19:18
just curious when changing the tileset textures's filter property (enabled or disabled), does that have any effect?

**Comment by splite** [comment] 2018-03-24 09:30
Changing Filtered flag does not have any visible effect.

**Comment by girng** [comment] 2018-03-25 23:52
i really want to try to replicate what's causing this.. anyone else (@godotengine), have any other questions / things to test or ask?

**Comment by splite** [comment] 2018-03-26 06:36
Tomorrow (27. 3. 2018 CET :) ) I can try this on the exactly same graphic card on another notebook, will update this issue how it goes.

**Comment by eon-s** [comment] 2018-03-26 10:35
If instead of using a you move the viewport (root) origin, the tearing is there too? (I'm thinking of workarounds until there is a real fix for this)

**Comment by splite** [comment] 2018-03-26 16:42
Well, i dont really need workaround.
For me its only hobby project - but if it turns out to be something like a bug on all MX graphics cards (or something like that), it's quite a showstopper for every serious developer...

**Comment by girng** [comment] 2018-03-26 21:33
@splite since other devs have tested this and i don't think their on a mobile gpu (and can't replicate it). i think it may be only an issue on mobile graphical processing units. i could be totally wrong, but just from what i'm seeing here

**Comment by splite** [comment] 2018-03-27 11:07
@girng ok, its official, looks like its NVIDIA MX (**Notebook cards**) related, tested on ANOTHER GeForce 940MX (exactly same model as mine) on another notebook and tearing appears, more or less the same as on my notebook, teared triangle etc as described. Everything is smooth when i hide Particles2D node in editor (not via script)

(btw, tested both on external monitor and ntb monitor, no visual difference)

**Comment by splite** [comment] 2018-03-27 12:46
Good News, Everyone! 👨‍🔬 

This is only "play from editor" bug - if i export game as windows executable, tearing diasappears. Tested on GeForce 940MX and Intel integrated card, no tearing at all. (I wanted to try what happens when i run my game with the integrated card)

Its annoying but I can live with that (I have heard that in 3.1 the particles will be rewrited to single pass)

**Comment by eon-s** [comment] 2018-03-27 13:01
@splite Nice! I was about to ask you to try that, so this is probably related to the debugger overhead on windows with these gpu (or cpu?).

Do the exported game was on release or debug mode?

**Comment by girng** [comment] 2018-03-27 18:41
ok, so yeah. not a graphics card issue at all

simply turn off 
![](https://i.gyazo.com/0ea41340f805e658c03fd9360c3d62a1.png)

however, this could be seem as normal. if the live scene is being refreshed like that, it will cause tearing. that's why that feature was implemented. i suspect future optimizations to be made so that tearing on live remote scene tree viewing is less and less

**Comment by splite** [comment] 2018-03-28 08:39
"Auto Switch To Remote Scene Tree" is off by default. (?), when i turn it on, tearing is even worse.

Anyway, I think we can close this issue, (at least its nothing with Particles2D, so the name is confusing)

Thanks guys!

**Comment by eon-s** [comment] 2018-03-28 10:56
@splite is up to you to keep it open and change the title (and maybe add the new information to first post) or close it (and maybe open a new one focusing on the issue inside the editor).

I think devs will prefer the former.

**Comment by girng** [comment] 2018-03-29 01:05
agree with @eon-s. looks like a new issue would be ideal. since this issue needs to be reduced a lot (**we had to kinda find out where the bug isolated from**). appreciate @splite for your time.

**Closed** 2018-03-29 14:27 UTC
Labels: bug, topic:rendering
