### ISSUE TITLE
GPUParticles3D stops emitting billboard particles if scale curve goes to 0

### ISSUE THREAD

**Issue by JaryJay** [godotengine/godot#76332] opened 2023-04-22 00:42 UTC
### Godot version

4.0.2

### System information

Windows 11, Vulkan, NVIDIA GeForce GTX 1660 SUPER

## Incorrect Behaviour

If the following conditions are met, a GPUParticles3D node will stop emitting particles after the first few:

1. Amount is not the default 8 (e.g. 3)
2. The emission shape is not the default "Point" (e.g. Sphere)
3. There is a scale curve which crosses 0 at some point, like so:
![image](https://user-images.githubusercontent.com/47123100/233752303-3385bed8-674f-4dcb-848c-5b6bda11e5dc.png)
4. The particle material's billboard mode is "Particle Billboard" and "Keep Scale" is on.
![image](https://user-images.githubusercontent.com/47123100/233752346-66b9a6e4-e94b-4c55-a296-fc918362e6cf.png)

If these are met, the GPUParticles3D node will only emit `amount` number of particles, and then stop emitting particles.

## Expected Behaviour

The expected behaviour is that the GPUParticles3D node continues emitting particles.

I also tried making the scale curve end just above 0, like so:
![image](https://user-images.githubusercontent.com/47123100/233752438-4860e0ca-5967-4e80-a820-d00bb3001a85.png)
When I do this, it works perfectly.

### Steps to reproduce

Run the attached project. The left particles node stop emitting after the first 3 particles (not expected behaviour), while the right particles node keeps on emitting particles (expected behaviour).

### Minimal reproduction project

[particles-bug.zip](https://github.com/godotengine/godot/files/11299913/particles-bug.zip)

**Comment by clayjohn** [comment] 2023-04-22 01:36
This may be a duplicate of https://github.com/godotengine/godot/issues/75748 and https://github.com/godotengine/godot/issues/68809

**Comment by Calinou** [comment] 2023-04-22 17:41
- Duplicate of https://github.com/godotengine/godot/issues/68809.

**Closed by Calinou** 2023-04-22 17:41 UTC
