### ISSUE TITLE
Multi-touch not registering correct inputs in HTML5

### ISSUE THREAD

**Issue by kylamon1** [godotengine/godot#55647] opened 2021-12-05 21:15 UTC
### Godot version

3.4

### System information

Window 10, GLES2, Chrome(PC, android, iOS), 

### Issue description

Multi-touch does not accurately track multiple fingers when running a project through HTML.

Test project exported to HTML so that you can run on a mobile device:

[Test Project](https://kylamon1.github.io/games/Godot/Multi-Touch.html)

### Steps to reproduce

Run a project in HTML that would require tracking multiple fingers.  Only one finger seems to be accurately tracked.

### Minimal reproduction project

[Multi-Touch_Error.zip](https://github.com/godotengine/godot/files/7656850/Multi-Touch_Error.zip)

**Comment by Calinou** [comment] 2021-12-05 21:56
Duplicate of https://github.com/godotengine/godot/issues/54135 (will be fixed in 3.4.1)
.

**Closed by Calinou** 2021-12-05 21:56 UTC
Labels: bug, platform:html5, topic:porting, topic:input
