### ISSUE TITLE
Crash when launching 3.5 rc1 on Win10x64

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#61254] opened 2022-05-21 16:00 UTC
### Godot version

v3.5 rc1 mono win64

### System information

Windows 10, V.10.0.19044, i7-6700K, 40GB RAM, GTX 980

### Issue description

Crashes when starting the application. The Project Manager only appears for a short time before Godot crashes.

The last ten lines of the mono log:
```
Loading reference 2 of C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System.Xml[000002594fccd720] -> System[000002594fcce2f0]: 4 (in domain Mono, info)
Requesting loading reference 3 (of 6) of C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll (in domain Mono, info)
Loading reference 3 of C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll asmctx DEFAULT, looking for System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System[000002594fcce2f0] -> System.Xml[000002594fccd720]: 3 (in domain Mono, info)
Image addref GodotTools[000002594fccead0] (asmctx DEFAULT) -> C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Tools/GodotTools.dll[000002595b707830]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotTools' (C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Tools/GodotTools.dll) (in domain Mono, info)
Assembly GodotTools[000002594fccead0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Image addref GodotTools.ProjectEditor[000002594fccd9f0] (asmctx DEFAULT) -> C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll[000002594fe8cd10]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotTools.ProjectEditor' (C:/Godot/Godot_v3.5-rc1_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll) (in domain Mono, info)
```

Beta 5 mono, does not crash.

### Steps to reproduce

Just start Godot.

**Comment by akien-mga** [comment] 2022-05-21 17:57
Thanks for the report. That's a duplicate of https://github.com/godotengine/godot/issues/61176 (which I've now pinned for better visibility). It will be fixed in RC 2.

**Closed by akien-mga** 2022-05-21 17:57 UTC
Labels: bug, topic:editor, crash
