### ISSUE TITLE
Function Calls In Custom Animation Track Doesn't Get Triggered

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#78298] opened 2023-06-15 23:56 UTC
### Godot version

Godot_v4.1-beta2_win64

### System information

Windows 11 Version 22H2, AMD Ryzen 7 6800H, AMD 6700M, Drivers 23.3.2

### Issue description

Adding a custom track with a function call doesn't work when other blends and nodes are added to the tree.

I'm trying to trigger a function call from the AnimationPlayer and it doesn't ever get called because it never even prints what is in the function. The animation does play though without issues, just the function call doesn't get triggered for some reason. Here are some screenshots.

When I'm running the game, it's not triggering. The booleans are not changing and it's not printing to the console in the editor.

Here is the custom track with the function call:

![image](https://github.com/godotengine/godot/assets/15805689/6672480b-e368-42b4-b9f4-4c2c1705ff62)

Here is the method call I'm expecting to see output to when triggering during running the game:

![image](https://github.com/godotengine/godot/assets/15805689/20bd4c79-68fe-43dd-8eb5-f268db89bc90)

This is the one shot node with the animation:

![image](https://github.com/godotengine/godot/assets/15805689/f9f63e82-5fb0-4c83-b9ba-2e6ad2196c29)

This is the specific one shot node:

![image](https://github.com/godotengine/godot/assets/15805689/ce8dbf20-78ec-48e1-b872-3a52695bfbcf)

I'm trying to reparent a mesh to another node during the middle of the animation. Moving a weapon from the hand to the back and vice-versa.

This has been demonstrated in Godot 3; so I'm not sure why it shouldn't work. Do you guys think this is a bug then? For example, here is a video of someone doing this in Godot 3.X:

https://www.youtube.com/watch?v=cj9S_5N0Z88&t=40s

### Steps to reproduce

Create a AnimationTree with multiple animations, blends, one shots. 

Add a function custom track call to one of the animations, preferably during a one shot animation. 

Expect to see the function call work but it's never triggered. Even with a breakpoint.

### Minimal reproduction project

[func_custom_track_animation_bug_new.zip](https://github.com/godotengine/godot/files/11769737/func_custom_track_animation_bug_new.zip)

Press E to trigger the one shot with the function custom track on it in the test project. It should print 

Press Space to jump

**Comment by AThousandShips** [comment] 2023-06-16 08:40
In the future please follow the instructions for creating a minimal reproduction project and do *not* include `.godot`

**Comment by AThousandShips** [comment] 2023-06-16 08:47
Also what you need to do in 4.x is:
```gdscript
animation_tree["parameters/OneShot/request"] = AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE
```

Please see the [documentation](https://docs.godotengine.org/en/stable/classes/class_animationnodeoneshot.html)

**Comment by AThousandShips** [comment] 2023-06-16 09:07
It works if you don't blend 100% to the second node, don't know if this is a bug, should the one-shot be fired if the output isn't used?

**Comment by AThousandShips** [comment] 2023-06-16 10:54
But the next node blends 100% the other node, so all of the input from the one-shot is ignored? Why should the input be computed and run at all when the input isn't used?

**Comment by AThousandShips** [comment] 2023-06-16 11:16
> I'm going to re-upload a test project with something that replicates the issue better, maybe with a cut down version that more accurately reflects my personal project.

Good because I can fully fix the issue when not having blend be 0 for the branch with the one-shot, so could be configuration issues

**Comment by AThousandShips** [comment] 2023-06-16 11:34
You still have resources from your project you haven't stripped out properly which will cause errors, but they are minor, but good to keep in mind for the future, they are two images in the global shader parameters

**Comment by AThousandShips** [comment] 2023-06-16 11:42
You need to filter for functions, they are a separate part of the "blend" and "add" nodes, otherwise it will be ignored if anything is filtered

**Comment by AThousandShips** [comment] 2023-06-16 11:46
Yes, exactly

**Comment by AThousandShips** [comment] 2023-06-16 11:51
The documentation says that you filter tracks, which is what happens here, but we could add some additional details, but that would be best served by an issue over on [documentation](https://github.com/godotengine/godot-docs/issues)

So if you feel the documentation is lacking please open an issue there over clarifying this under [animation tree](https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html) or similar

> Thank you for your help and patience, haha

No worries!

**Comment by AThousandShips** [comment] 2023-06-16 11:53
It allows you to filter tracks for particular paths, so if you have a function called on a specific node you can filter it, but yes otherwise it's only tracks for specific nodes or parts, not sure how that would be handled though as method tracks are node-specific, just like (at least I think) you can't have two tracks on the same animation affecting the same property (like two different tracks controlling the scale of a specific bone)

**Comment by AThousandShips** [comment] 2023-06-16 11:56
Make sure to clarify what you think is missing from the documentation, rather than just that it might be insufficient

**Comment by AThousandShips** [comment] 2023-06-16 11:58
* Closing in favour of: https://github.com/godotengine/godot-docs/issues/7528

**Closed by AThousandShips** 2023-06-16 11:58 UTC
Labels: topic:editor, documentation, topic:animation
