### ISSUE TITLE
.res Scene Launches Project Selection

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#38823] opened 2020-05-18 07:44 UTC
**Godot version:**
3.2.1.stable

**OS/device including version:**
Windows

**Issue description:**
res root scenes launches the project selection

**Steps to reproduce:**
Save a scene as .res and then run it

**Minimal reproduction project:**

**Comment by nathanfranke** [comment] 2020-05-18 07:45
https://github.com/godotengine/godot/issues/28036

**Comment by LoneDespair** [comment] 2020-05-18 07:48
@nathanfranke Oh sure thing, mine only shows tscn, scn and res as options for saving scenes

**Comment by nathanfranke** [comment] 2020-05-18 07:50
Sorry, I meant .tscn. You shouldn't save your scene as .res or .tres

**Comment by Calinou** [comment] 2020-05-18 07:52
Duplicate of #35709.

**Closed by Calinou** 2020-05-18 07:52 UTC
