### ISSUE TITLE
pressing Shift-A in GDScript editor shows VisualScript search

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#20454] opened 2018-07-25 16:55 UTC
Pressing Shift-A in GDScript editor shows VisualScript search rendering editor
hard to use.
**Godot version:**

41a0ecb59b244ee01ece644107f02c64d2a5b64a

**OS/device including version:**

Linux

**Comment by fire** [comment] 2018-07-25 17:22
See https://github.com/godotengine/godot/issues/20433

**Comment by akien-mga** [comment] 2018-07-25 21:18
Duplicate of #20433.

**Closed by akien-mga** 2018-07-25 21:18 UTC
