### ISSUE TITLE
GDScript - "\" escape character isn't recognized for print method.

### ISSUE THREAD

**Issue by TheYokai** [godotengine/godot#19094] opened 2018-05-22 06:09 UTC
**Godot version:**
3.0 / Master Branch

**OS/device including version:**
Windows 10

**Issue description:**
The following code won't work

```python
func _ready():
    print( \
      "some string" \
      )
```
However, the below code WILL work, making an inconsistancy

```python
func _ready():
    _other_print( \
            "some string" \
            )
    


func _other_print( value ):
    print( value )
```

This illustrates an inconsistency with the escape character when dealing with built in methods! Probably has to do with issues during code parsing. 

**Steps to reproduce:**

Copy + Paste the above into a script and check the results!

**Comment by TheYokai** [comment] 2018-05-22 06:13
It seems that restarting the editor will fix this behavior, but I will leave this here because it does seem to cause an error without restarting the editor.

**Comment by vnen** [comment] 2018-05-23 00:45
I can't reproduce this. I just copied and pasted and it worked fine. Were there any errors or it simply didn't print when you run?

**Comment by romeojulietthotel** [comment] 2018-05-23 03:19
I got an error if there's a space character after the "\". But without spaces it works fine.

**Comment by vnen** [comment] 2018-05-23 04:00
The newline must be the next thing after `\`, any other character (including space) will give an error. That's expected, it's not a bug.

**Comment by romeojulietthotel** [comment] 2018-05-23 04:18
@vnen, right, perhaps @TheYokai had spaces there.

**Comment by TheYokai** [comment] 2018-05-24 03:01
The space must have been my issue! I've opened the project in question and it seems to have been resolved then. Sorry for the false alarm.

**Comment by vnen** [comment] 2018-05-24 03:31
Alright then, I'm closing this.

**Closed by vnen** 2018-05-24 03:31 UTC
