### ISSUE TITLE
Godot 4 beta 3 HTML export only displays a grey screen

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#67615] opened 2022-10-19 07:06 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Linux

### Issue description

![image](https://user-images.githubusercontent.com/80917990/196619569-f92e931b-50fc-4b57-9ba4-1bb27dbfea7b.png)
![image](https://user-images.githubusercontent.com/80917990/196620200-c8050c54-6669-4962-b763-3e5996abacd3.png)

This is what I get when debugging the project in the browser. The issue is new to beta 3, my project works normally on beta 2.

### Steps to reproduce

Download the export presents through the editor and export to web, then press run in browser

**Comment by clayjohn** [comment] 2022-10-19 21:56
Duplicate of https://github.com/godotengine/godot/issues/67392 which has already been fixed in master.

**Closed by clayjohn** 2022-10-19 21:56 UTC
