### ISSUE TITLE
Godot Nightly Build - Vulkan doesnt work.

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#39442] opened 2020-06-10 17:54 UTC
**Godot version:**
latest on: https://hugo.pro/projects/godot-builds/

**OS/device including version:**
Windows 10

**Issue description:**
I see everyone using Godot nightly with vulkan but won't work on mine. I got an AMD Radeon RX 580 and it won't show up. I even used the vulkan SDK cube to make sure it worked, it did. I tried multiple different version of vulkan (the sdk) and it still get a mass of errors. I added env path to vulkan and godot and it won't show up.

 I get this:
![image](https://user-images.githubusercontent.com/5901214/84301270-5c02d900-ab08-11ea-8898-3157f106dbfd.png)

vulkan cube test: 
![image](https://user-images.githubusercontent.com/5901214/84301093-1ba35b00-ab08-11ea-8fbf-db25ea3e3b2a.png)

multiple installed versions:
![image](https://user-images.githubusercontent.com/5901214/84301351-7ccb2e80-ab08-11ea-98f3-e49b2b5cb2f0.png)

my gpu info:
![image](https://user-images.githubusercontent.com/5901214/84301430-9cfaed80-ab08-11ea-922d-be6a3536da83.png)

**Steps to reproduce:**
n/a

**Minimal reproduction project:**
n/a

**Comment by RaTcHeT302** [comment] 2020-06-11 08:28
@Calinou ok
!()[https://i.imgur.com/0f9HUQQ.png]
!()[https://i.imgur.com/LpQ5fIN.png]

**Comment by shmellyorc** [comment] 2020-06-11 10:43
ye re-downloaded from https://hugo.pro/projects/godot-builds/ and it works great :D.

![image](https://user-images.githubusercontent.com/5901214/84376220-a0888600-ab95-11ea-9c34-426720aecae5.png)

**Comment by name-here** [comment] 2020-06-11 18:52
As a side note, I noticed the macOS build on https://hugo.pro/projects/godot-builds/ is still a build of 3.2, not 4.0.  Is that a mistake, or does the master branch just not work on macOS yet?

**Comment by bruvzg** [comment] 2020-06-11 19:06
>  or does the master branch just not work on macOS yet?

`master` works OK on macOS, at least debug build.

**Comment by name-here** [comment] 2020-06-11 19:50
> You can check last build date by adding `.manifest.json` to the download link, macOS one is from 2020-01-23.

Yes.  It also shows the commit it was built from, which if you look it up is tagged as 3.2.1-stable and is from January ([here](https://github.com/godotengine/godot/commit/8a7a216be5dfbd8e2b7f32c39a92bbecec9306ca)).  The Windows build, on the other hand, is built from a commit from a few hours ago.

**Comment by akien-mga** [comment] 2020-10-25 22:32
This was likely fixed by #43066. Can anyone affected confirm that it no longer crashes in the latest `master` branch?

**Comment by Calinou** [comment] 2020-11-28 16:14
Closing due to lack of response. Please comment if you can still reproduce this on the latest `master` branch.

**Closed by Calinou** 2020-11-28 16:14 UTC
Labels: platform:windows, topic:rendering

**Comment by lupoDharkael** [comment] 2020-11-28 20:21
Tried to build in release with the following command:
`scons p=linuxbsd tools=yes target=release_debug use_static_cpp=yes use_lto=yes debug_symbols=no -j$(nproc)`

stoped with the following error:
```
/bin/ld: /tmp/godot.linuxbsd.opt.tools.64.BotQFT.ltrans39.ltrans.o: in function `EditorNode::EditorNode()':
<artificial>:(.text+0x1b5b): undefined reference to `vtable for EditorInspectorRootMotionPlugin'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.opt.tools.64] Error 1
scons: building terminated because of errors.
```

**Comment by Calinou** [comment] 2020-11-28 20:32
@lupoDharkael `targe=release_debug` is currently broken (especially with LTO), but I'd open a separate issue for that.
