### ISSUE TITLE
Theme resources randomly ballooning in filesize

### ISSUE THREAD

**Issue by Zain-A-Abbas** [godotengine/godot#86702] opened 2024-01-02 07:58 UTC
### Tested versions

Issue started in 4.1. Persists in 4.3.

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Certain resources files will randomly massively balloon in filesize, such as from 1kb to 95 mb. Or maybe, something happens during their creation that makes the filesize erupt. I never notice until much later and I can't reproduce it easily, so I'm not sure at what point it props up. Once this issue is noticed, I simply remake the resource by-hand to be identical, and there is no problem. Here is the same resource twice- both versions accomplish the same thing (setting a label to Dosis font at a certain boldness and size), but one accomplished it in a single kilobyte while the other took 95 MB.
[HighlightedSkillItemText.zip](https://github.com/godotengine/godot/files/13808014/HighlightedSkillItemText.zip)

### Steps to reproduce

Simply occurs over a period of time when making menus and creating themes for UI nodes. I wish I could include more details, but it has happened thrice over the course of 14 months of constantly working on control nodes and themes, so I am completely lost on how to reproduce it.

### Minimal reproduction project (MRP)

N/A

**Comment by Zireael07** [comment] 2024-01-02 08:39
Most likely your font data got embedded in the resource file

**Comment by AThousandShips** [comment] 2024-01-02 10:07
Duplicate of https://github.com/godotengine/godot/issues/82254

**Closed by AThousandShips** 2024-01-02 10:07 UTC

**Comment by Mickeon** [comment] 2024-02-15 17:12
I would open this. While the original issue with images embedding into FontFiles has been solved, these kind of similar issues have not. It's not just the font image that gets embedded when serialized, rather a massive amount of cache, as well.
![image](https://github.com/godotengine/godot/assets/66727710/b05d362d-8ec0-4c2b-b5b1-50055f151469)

**Comment by AThousandShips** [comment] 2024-02-15 17:15
Think best to open a new detailed issue instead
