### ISSUE TITLE
Vertically mirrored render on Windows (virtualbox)

### ISSUE THREAD

**Issue by IriaSomobu** [godotengine/godot#47473] opened 2021-03-29 21:08 UTC
**Godot version:** v3.2.3.stable.official

**OS/device including version:** Windows 10 (VirtualBox 6.1); GLES2 mode via VBoxSVGA (3d accel enabled)

**Issue description:** see screenshot

![image](https://user-images.githubusercontent.com/17745136/112900208-d2021c00-90eb-11eb-9f0b-62b553990f8e.png)
It is render bug -- when I move mouse on the right side buttons hovers as if they placed correctly.

**Steps to reproduce:** launch in Windows 1809 on VBoX with SVGA video driver and guest additions installed.

**Minimal reproduction project:** N/A

**Comment by IriaSomobu** [comment] 2021-03-29 21:18
Managed to open my project:
![image](https://user-images.githubusercontent.com/17745136/112901431-6de05780-90ed-11eb-83ca-84784f7c340f.png)

**Comment by Calinou** [comment] 2021-03-29 22:46
Duplicate of https://github.com/godotengine/godot/issues/40370.

**Closed by Calinou** 2021-03-29 22:46 UTC
