### ISSUE TITLE
Polygon2D + Skeleton2D gives insufficient visibility area 

### ISSUE THREAD

**Issue by SaffronStreams** [godotengine/godot#36846] opened 2020-03-06 10:13 UTC
I'm using Godot 3.2 on a Windows 10 system.

When working with bigger characters it can happen that some Polygon2D of them are no longer shown, even though they are still on the screen area. This happens when in the editor (see the video), but also happens when the game is running.

I think somehow the visibility rectangle (if this exists for Polygon2D) is not adjusted to keep the transformations done by Skeleton2D in mind. Since I cannot find a setting for this, I presume it's not intended to be set manually and so a bug.

The Polygons just turn off at very specific points, with no weird movement beforehand, so it's not linked to the 3.1 problem where polygons would sometimes be influenced by bones from another skeleton2D. 

[Link to example video.](https://www.youtube.com/watch?v=IpQWQDmllmg)

My steps for this project:
Have big image (3000*3000), use it as texture and cut out limbs etc with Polygon2D. Link to a Skeleton2D and fill that with Bone2D. Now animate and zoom in on different parts.

**Comment by Calinou** [comment] 2020-03-06 10:20
Duplicate of #35726.

**Closed by Calinou** 2020-03-06 10:20 UTC
