### ISSUE TITLE
Godot 3.5 BETA 2 is not working with GLES2 project

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#59405] opened 2022-03-22 04:41 UTC
### Godot version

Godot_v3.5-beta2_x11.64

### System information

Linux, GLES2

### Issue description

Godot 3.5 BETA 2 is crashing with a project with GLES2

### Steps to reproduce

Just open a GLES2 project working with Godot 3.5 BETA 1, with this new BETA 2 I got these errors

ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
ERROR: Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
   at: mesh_surface_set_material (drivers/gles2/rasterizer_storage_gles2.cpp:2652)
ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
malloc(): invalid size (unsorted)

**Comment by clayjohn** [comment] 2022-03-22 04:45
CC @lawnjelly Looks like it may have something to do with the new memory allocation stuff.

**Comment by lawnjelly** [comment] 2022-03-22 07:51
> CC @lawnjelly Looks like it may have something to do with the new memory allocation stuff.

Memory allocation (pools) hasn't been merged yet, so that's me off the hook (hopefully) :grinning: . I would say most likely to be something related to octahedral / split vertex streams. But we will probably need a minimum reproduction project I suspect to make anything of this.

This shouldn't have to be done, but it seems that in those cases of vertex format changes, sometimes reimporting everything might help (delete the hidden `.import` folder, and let the editor reimport the resources), or reimporting meshes manually might help.

**Comment by gerardogc2378** [comment] 2022-03-23 20:28
It's happening with this specific version

v3.4.4.stable.official.419e713a2

The error output is:

ERROR: Condition "array.size() != array_size" is true.
   at: mesh_add_surface (drivers/gles2/rasterizer_storage_gles2.cpp:2490)
malloc(): invalid size (unsorted)

**Comment by akien-mga** [comment] 2022-03-23 23:01
Would you be able to provide a minimal project that reproduces the issue? It's difficult for contributors to debug otherwise if they can't trigger the bug.

**Comment by clayjohn** [comment] 2022-03-23 23:20
@gerardogc2378 Can you clarify that you get the same crash on both 3.5 BETA 2 and in 3.4.4 stable?

**Comment by BastiaanOlij** [comment] 2022-03-23 23:33
This needs a reproducable project. `mesh_add_surface` obtains a set of data from which the mesh is constructed and it can get its data from a dozen places, including data provided by the user (in the case of ArrayMesh). So without knowing where the data is coming from, and where the real problem thus lies, it's hard to figure out.

Lawnjellys suggestion should be the first thing to try, trashing the `.import` folder so all mesh data is re-imported. If there was a change in the format of the data structure that would explain this going wrong. The octahedral change is a likely candidate to look at (also checking where this error is in the code) as I guess this would have changed the size of the normal buffer, and if a buffer was presented that still contains the old data it would cause this error.

**Comment by gerardogc2378** [comment] 2022-03-26 18:51
Hi guys

It was solved removing all *.png.import files and reimporting them again with some FLAGS, even GLTF files with animations. Also I deleted my .import directory.

I am using 3.4.4 stable version.

**Comment by gerardogc2378** [comment] 2022-03-26 20:03
And it's working with Godot_v3.5-beta2_x11.64 too...

**Comment by akien-mga** [comment] 2022-04-30 11:45
Closing as it was a problem with importer meshes needing a reimport, which can be forced by deleting the `res://.import/` folder.

**Closed by akien-mga** 2022-04-30 11:45 UTC
Labels: bug, topic:rendering, needs testing, regression
