### ISSUE TITLE
Multi-line String creates duplicate string

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6212] opened 2016-08-20 03:04 UTC
**Operating system or device - Godot version:** 2.1

**Issue description** (what happened, and what was expected):
Alright folks, this is a pretty fascinating bug: 

```
    get_node("RichTextLabel").set_bbcode("""
    hello
    """)
```

This is valid `GDScript` syntax, but, it will actually insert 2x `hello` strings instead of just one.

If you do it without a initial line break:

```
    get_node("RichTextLabel").set_bbcode("""hello
    """)
```

It works fine.  I am making some extensive tooltips and need the line breaks but it literally duplicated my text, lol pretty funny tbh. I am not sure if this intended :P

**Comment by volzhs** [comment] 2016-12-21 08:49
also can reproduce with `set_bbcode("\nhello")`

**Comment by bojidar-bg** [comment] 2016-12-21 10:37
`set_bbcode`/`append_bbcode` both do something funny, as evidenced by #3773 (actually, `set_bbcode` calls `append_bbcode` through `parse_bbcode` internally...)

Anyway, seems like this issue is either in the two calls to `add_text` [on lines 1475 and 1485](https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp#L1475-L1485) (probably no) or in [`add_text` itself](https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp#L1132-L1189), specifically the weirdness it does with newlines and similar.

Can you retest with `add_line("\nhello")` as well?

**Comment by volzhs** [comment] 2016-12-21 12:44
@bojidar-bg 
same result in both `set_bbcode` and `append_bbcode`
![image](https://cloud.githubusercontent.com/assets/8281454/21389739/8851d516-c7c6-11e6-8ac1-e222216a3768.png)

**Comment by bojidar-bg** [comment] 2016-12-21 14:36
@volzhs Uh my bad, I meant `add_text("\nstuff")` (and yeah, `append_bbcode` is expected to fail in the same way).

**Comment by volzhs** [comment] 2016-12-21 14:46
@bojidar-bg 
`add_text` result is here.

![image](https://cloud.githubusercontent.com/assets/8281454/21393433/bc08dcb8-c7d7-11e6-9057-47291f46c398.png)

**Comment by bojidar-bg** [comment] 2016-12-21 20:19
Ok, issue location confirmed and also a duplicate of #3773. @godotengine/bugsquad I'm not sure which of the two to close though, since this got much more attention and debugging...

**Closed** 2016-12-23 15:00 UTC
Labels: bug, confirmed, topic:core
