### ISSUE TITLE
WYSIWYG composition for viewport textures

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#11727] opened 2017-09-30 17:21 UTC
*Bugsquad edit:* Godot 3.0, current master branch.

Check the GUI_In_3D demo on how, right now at least, you need to compose the viewport texture blind (you get the 2D window when you add a UI node, but nothing shows up).

So it would be nice to be able to see the composition you are making, as I imagine the current situation will prove to be a headache for very complex stuff.

Can this be done, would it be good to have?

**Comment by Zireael07** [comment] 2017-09-30 17:43
Are you on 2.1. or 3.0?

**Comment by Ace-Dragon** [comment] 2017-09-30 18:03
I'm on Godot 3.0 (build done today).

**Comment by reduz** [comment] 2017-09-30 18:50
You can always do it in a separate scene and instance it. That's what Godot
is about :)

**Comment by reduz** [comment] 2017-09-30 18:52
Oh, misunderstood. Check the demo, it's all done with zero code

On Sep 30, 2017 3:49 PM, "Juan Linietsky" <reduzio@gmail.com> wrote:

You can always do it in a separate scene and instance it. That's what Godot
is about :)

**Comment by mhilbrunner** [comment] 2018-04-10 17:11
To be honest, I don't get what you're requesting at all. Can you maybe explain it some more, or in another way? Not really getting it, sorry.

**Comment by karroffel** [comment] 2018-04-15 17:58
@mhilbrunner for example, in one of my game projects I use a Sprite3D using a viewport texture to display Control nodes in the 3D space. The problem is that there is no visual feedback with the viewport. I basically set it all up "in the dark" and then I see in game if it looks right.

**Comment by KoBeWi** [comment] 2019-06-02 18:09
This is somewhat related to #20619

Both are caused by nodes being inside different Vieport than the editor's.

**Comment by rcorre** [comment] 2019-12-13 15:54
> You can always do it in a separate scene and instance it. That's what Godot
is about :)

This is true, and is what I ususally end up doing, but I found this issue after having multiple times where I thought "ugh, I wish I could just edit this in the same scene". This happens a lot where I want to create little simple GUI elements in 3D space (tooltips/hints/HUD elements, ect.).

This bug is misleading when you have two controls in the same scene and one of them is in a separate viewport. Selecting the control in the separate viewport instead shows the control from the current viewport. 
![1576252402](https://user-images.githubusercontent.com/2496231/70812975-af34e280-1d96-11ea-89f8-1d5c5e20607e.png)

In this screenshot, I've selected the `Crosshairs` viewport (which is used to display a GUI element in 3D), but it is actually showing the `HUD` viewport.

**Comment by Calinou** [comment] 2020-05-26 08:05
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 08:05 UTC
Labels: feature proposal, topic:editor, topic:rendering

**Comment by Zireael07** [comment] 2020-05-26 08:19
I think it's more of a bugfix that enhancement proposal - all other 2d scenes can be composed WYSIWYG, only viewports don't.

**Comment by AceIsAwful** [comment] 2023-02-14 19:24
Death to you Ace, you cheap loser shill. Death to you for openly promoting the dumpster of society, AKA "universities" [more like DUMPSTERversities]. Death to you and death to all "universities" and every moron who supports those trashpits. death to you for praising those clowns who boast about their stupidity using the disgusting & childish & daft "titles". Death to every loser donkey who uses that disgusting & racist 2/6 letter donkey "title". Death to you for being such stupid mainstream shills and praising those daft morons. Death to you for commenting (and potentially supporting or have watched) that disgusting and racist movie, which starts with a disgusting 6-letter monkey word and is followed by "Strange" (I'm referring to that garbage thread you commented on in blenderartists, which was started by that inferior animal ARandomHowdy). 

Death to you for promoting those stupid childish ego pigs who use that disgusting clownish 6 letter word.
You're all nothing but useless shills. Your projects are nothing but utter trash, and You have no potential, and are a complete and utter laughable failure, Ace. Death to every idiot who uses the stupid 6-letter clownish "prefixes/titles" when mentioning first names. Death to "universities" [DUMPSTERversities]. Death to you Ace. Have a sad life and painful death, Ace.
And one other thing.There is no such thing as "software" "engineering". That is the stupidest and most pathetic lie ever. Shame on you for mentioning the word "engineering" when talking about development of game "framework". Stop being disrespectful to Engineering. You know nothing about what Engineering entails. 
Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with scriptkiddies like you monkey game/software devs sitting behind a keyboard and writing code. Software/game dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering).
Hope your dirty and cheap throats get slit, silly Ace.
