### ISSUE TITLE
VisualShader editor RMB options are a very tall popup, requires scrolling

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#9618] opened 2017-07-12 16:31 UTC
**Operating system or device - Godot version:**
ArchLinux with Godot 2.1.4 Beta

**Issue description:**

Screen resolution vs options for shader graph

![resolution](https://user-images.githubusercontent.com/24534/28128293-e389a170-66f4-11e7-9fa4-52e4ee7d6046.png)
![screenshot from 2017-06-29 08-23-25](https://user-images.githubusercontent.com/24534/28128302-e9830422-66f4-11e7-9693-4f65720c2e94.png)

**Steps to reproduce:**
Into 3D View
Add Spatial into new scene
Add TestCube
New Shader Material
New Material Shader Graph
On Fragment Tab click with RMB

**Link to minimal example project:**

**Comment by MarianoGnu** [comment] 2017-07-14 10:46
just subscribing to comments

**Comment by akien-mga** [comment] 2017-07-14 11:01
@MarianoGnu 
![image](https://user-images.githubusercontent.com/4701338/28209827-972a58c8-6894-11e7-8184-b964fe6b20b1.png)

**Comment by vnen** [comment] 2017-07-14 13:51
It should be like Visual Script, with a side list of categorized options.

**Comment by MarianoGnu** [comment] 2017-07-14 19:07
@akien-mga thx i was looking tor that button but didn't see it

**Comment by MarianoGnu** [comment] 2017-07-14 19:09
@vnen i dont think it's worth doing that for 2.1, but adding submenus is still worth and possible IMO

**Comment by akien-mga** [comment] 2018-09-17 14:04
Still reproducible in the current master branch (I suppose, OP did not write what the problem actually *is*). All options can be accessed but you need to scroll down, and it doesn't look very good.
![screenshot_20180917_160328](https://user-images.githubusercontent.com/4701338/45627900-3790de80-ba93-11e8-91c9-fd2c627ad431.png)

Scrolling down is ok, but the fact that there is no padding between the bottom of the popup and the bottom of the Godot window makes it unclear whether you're actually seeing the last options or not.

**Comment by MarianoGnu** [comment] 2018-09-19 22:42
OP was meaning about Godot 2.1.4, this is a new issue actually, because the visual shader code is not shared between versions anymore

**Comment by Chaosus** [comment] 2019-04-14 16:54
@akien-mga Fixed in 3.2, I think this should be closed cuz we are no longer provide support for the non-critical bugs in the 2.x branch.

**Closed** 2019-04-15 10:44 UTC
Labels: enhancement, topic:editor, usability
