### ISSUE TITLE
[C#] Editor's connect signal code generation is not sophisticated

### ISSUE THREAD

**Issue by JimArtificer** [godotengine/godot#39566] opened 2020-06-15 12:59 UTC
**Godot version:** 3.2.1
**OS/device including version:** Windows 10

**Issue description:**
When using the editor's `Connect a Signal to a Method` dialog in conjunction with C#, a stub function is:
* always generated (does not check if the method is already defined)
* appended to the end of the file (not inserted into the C# class)

**Steps to reproduce:**
1. Create two nodes in the editor.
1. Attach a C# script to one of them with the `Default` template.
1. Select the other node and connect a signal to it from the `Node > Signals` UI panel. The `receiver method` name can use the default value.
1. Note that the generated method stub is not added to the script class. It is appended to the end of the script file. (Creating a compile error.)
1. Attach another signal to the same receiver method using the editor.
1. Note that the generated method stub is duplicated and appended to the end of the file. This occurs regardless of whether or not that method is already defined in the script file. (Creating a compile error.)

**My thoughts:**
The productivity workflow issue here is that the method stub is always generated. I have to delete code every time I connect a signal in the editor. A naive text search of the C# file for the receiver method's name that skipped the code insertion would solve my issue without requiring a contextual parse of the C# file. Another alternative: a checkbox option in the advanced connect signal dialog to skip code generation.

**Comment by Flavelius** [comment] 2020-06-16 16:07
It should not try to 'generate' code, in my opinion, as c# allows for a little deeper nested structures than gdscript that would have to be treated right and checked for potential duplicates etc; so it should even be easier (and more common coming from unity) to just enumerate existing methods and create a dropdown with matching targets (so users can rely on their brain or IDE to provide correct method signatures).

**Comment by damymetzke** [comment] 2020-11-02 15:45
Checking if the function exists could be problematic.
This functionality should currently be implemented by the function `find_function()`,
which can be overridden from `ScriptLanguage`.
There are 2 problems:
* It is currently not implemented for C#.
* Its meaning is ambiguous.
It could mean find the function in the file, or find the function in the base class.
In GDScript these 2 are identical, but in C# they are not.

Ideally 2 functions should exist: `find_function_in_file()` and `find_function_in_class()`, but this interface might not be compatible with existing code.

*About generation the code, I can think of 2 solutions:*

The easy solution would be to disable generation when creating a signal in C#.
This is an almost trivial change, and I've already implemented it on my fork with no problems.

The 'correct' solution would be to generate it just before the closing bracket of the correct class.
however there are a few obstacles:
* The above problem with `find_function()`.
If this is not solved the generated code can still be invalid.
* The function `validate()` is currently not implemented for C#.
* The C# file should be parsed the find the correct class.
If the correct class cannot be found the code should not be generated.

This solution is far from trivial.

My suggestion would be to *at least* solve it using the easy method temporarily,
since it still outweighs generating invalid code in my opinion.
After that properly implementing the generation could be discussed.

**Comment by kleonc** [comment] 2021-08-13 15:15
>When using the editor's `Connect a Signal to a Method` dialog in conjunction with C#, a stub function is:
>> always generated (does not check if the method is already defined)
 appended to the end of the file (not inserted into the C# class)

Having `External Editor` for `Mono` set to `Visual Studio Code` (probably to anything other than `Disabled`) in `Editor Settings` results in not modifying the script whatsoever. Disabling external editor results in behavior as described above. `3.2.4.beta3.mono`

**Comment by raulsntos** [comment] 2021-11-22 13:42
Duplicate of #18721?

**Closed** 2021-11-22 14:54 UTC
Labels: enhancement, topic:core, topic:editor, usability, topic:mono
