### ISSUE TITLE
[3.5rc1-2] Incorrect color rendering on transparent objects

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#61363] opened 2022-05-24 12:46 UTC
### Godot version

3.5-rc1, rc2

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

Not present in 3.5b5, present in rc1-2.

Transparent objects are no longer colored properly when rendered. This roof panel has strips of meshes that have an opaque material overlaid with meshes with transparent materials. The objects with alpha are the ones miscolored. 

![image](https://user-images.githubusercontent.com/632766/170037302-2382bcfa-f53d-4212-ad90-beeaee192862.png)

@clayjohn 

### Steps to reproduce

Open mrp.

### Minimal reproduction project

[wrong_color.zip](https://github.com/godotengine/godot/files/8762729/wrong_color.zip)

**Comment by Calinou** [comment] 2022-05-24 12:55
Duplicate of https://github.com/godotengine/godot/issues/61359.

**Comment by akien-mga** [comment] 2022-05-24 16:11
Reopening as it's not clear if it's a duplicate (even if they're likely both regressions from the same PR): https://github.com/godotengine/godot/issues/61359#issuecomment-1136114043

**Comment by akien-mga** [comment] 2022-05-24 21:07
Fixed by #61375.

**Closed by akien-mga** 2022-05-24 21:07 UTC
Labels: bug, topic:rendering, regression, topic:3d
