### ISSUE TITLE
Godot does not autocomplete enum in match for me

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#94861] opened 2024-07-28 06:48 UTC
### Tested versions

v4.3.rc1.official [e343dbbcc]

### System information

w10 64

### Issue description

Godot does not suggest the values ​​for the "EstadosEnte" enumeration.

https://github.com/user-attachments/assets/a50e2d7f-8114-45c2-9f7d-755da5ded9d4

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

...

**Comment by HolonProduction** [comment] 2024-07-28 12:51
Duplicate of #72328

**Closed** 2024-08-05 17:23 UTC
Labels: bug, topic:gdscript, topic:editor
