### ISSUE TITLE
Vertical tile scroll does not show in tileset editor when already zoomed in

### ISSUE THREAD

**Issue by jbwyatt4** [godotengine/godot#30110] opened 2019-06-26 23:41 UTC
**Godot version:**

Linux 64bit
3.1.1 and custom build 0bf5895e00c79e73f33c42cd95f67ae35ec88f88 (latest pull)
(I believe this is also in 3.0.6 and 3.1)

**OS/device including version:**

Nvidia prop drivers
430.14

**Issue description:**

When you return to the tileset when it is zoomed in the vertical scroll does not show.

**Steps to reproduce:**
1) Create tilemap, new tileset in tilemap dropdown, select it, load an image for the tileset
2) Zoom in so scroll bars show
3) Create a new single tile
4) Click the tilemap in the left dialog
5) Place the single tile
6) Go back to the tileset by selecting from the tilemap as in 1) and select the image. The tilemap should be already be zoomed in.
7) Move the mouse pointer to where the vertical scroll should be
(If you zoom out ctrl-mouse wheel down and ctrl-mouse wheel up vertical scroll reappears)

**Minimal reproduction project:**

URL:
https://gitlab.com/jbwyatt4/tempgodot1
Go to Scenes/World->ExampleBrokenVerticalScroll then follow the steps above.

**Comment by KoBeWi** [comment] 2019-06-26 23:52
This is a duplicate of #28143
And again, I can't reproduce it with the provided steps :/

**Closed by KoBeWi** 2019-06-26 23:52 UTC

**Comment by jbwyatt4** [comment] 2019-06-27 00:07
Posted a video detailing the steps and what to look for.

https://www.youtube.com/watch?v=aVdYAdoVw9U

**Comment by KoBeWi** [comment] 2019-06-27 00:19
Thanks for the video. If both issues involve expanding the editor, that's probably the step missed by both reports.
