### ISSUE TITLE
Inconsisten `Time` error handling

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#80059] opened 2023-07-30 14:52 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

Error handling is not well implemented. Try this:
```
print("Invalid date")
print(Time.get_unix_time_from_datetime_string("1970-01-40"))
print("Unix 0")
print(Time.get_date_string_from_unix_time(0))
print("From string")
print(Time.get_unix_time_from_datetime_string("1970-01-01"))
```
You will get:
```
Invalid date
0
Unix 0
1970-01-01
From string
0
```
Furthermore, in the [global scope](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error), `OK = 0`.

Conclusion, you can't distinguish between an invalid date and date 1970-01-01.

### Steps to reproduce

See "Issue description"

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-30 14:56
> Furthermore, in the [global scope](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error), `OK = 0`.

It doesn't return an error value so this isn't really relevant.

**Comment by acgc99** [comment] 2023-07-30 14:58
I would suggest:
- To raise an error that stops execution when an invalid date is given.
- Implement a method that returns `OK` if the date is valid and `FAILED` otherwise.

**Comment by AThousandShips** [comment] 2023-07-30 15:00
> To raise an error that stops execution when an invalid date is given.

Would break compatibility

> Implement a method that returns OK if the date is valid and FAILED otherwise.

Doesn't work since GDScript can't return by reference, so you can't return the value *and* the error

**Comment by acgc99** [comment] 2023-07-30 15:03
> Doesn't work since GDScript can't return by reference, so you can't return the value _and_ the error

The function that checks the date wouldn't have to raise any error, just determine if the date is valid. With this, the user can decide if to call other `Time` methods.

**Comment by AThousandShips** [comment] 2023-07-30 15:04
That would be the area of a [proposal](https://github.com/godotengine/godot-proposals), so please open one for that if you like

**Comment by acgc99** [comment] 2023-07-30 15:05
I opened a bug because you can't distinguish between an invalid date and 1970-01-01.

I will open the proposal

**Comment by AThousandShips** [comment] 2023-07-30 15:19
Closing in favour of https://github.com/godotengine/godot-proposals/issues/7414#issue-1827970405 as the current behaviour is by design (and would break compatibility)

**Closed by AThousandShips** 2023-07-30 15:19 UTC
Labels: discussion, topic:core, documentation
