### ISSUE TITLE
Overflowing of Godot's window

### ISSUE THREAD

**Issue by JeanKouss** [godotengine/godot#41755] opened 2020-09-04 02:09 UTC
**Godot version:** Godot_v3.2-stable_win64

**OS/device including version:** Windows 10 

**Issue description:**

When I am in the scripts , the right part of godot's window exceeds the right screen limit.
![image](https://user-images.githubusercontent.com/70731505/92191425-483ee880-ee53-11ea-9afb-9740e261e4ae.png)

**Steps to reproduce:**
-Enter project
-Enter Script.

**Comment by akien-mga** [comment] 2020-09-04 06:33
Duplicate of #31133.

This specific case caused by the long French translations of the buttons in the top bar of the script editor should already be fixed in 3.2.2-stable though.

**Closed by akien-mga** 2020-09-04 06:33 UTC
