### ISSUE TITLE
Godot 4 rc3 just crash while opening the project

### ISSUE THREAD

**Issue by enemy141** [godotengine/godot#73783] opened 2023-02-22 20:55 UTC
### Godot version

4.0 rc3

### System information

Windows 10

### Issue description

while I'm trying to open the project in Godot 4 rc3 the engine itself crashes for some reason it's just fine in the previous version.

### Steps to reproduce

https://user-images.githubusercontent.com/88548945/220756083-c1c905f8-f450-4ffe-86f0-0f84b05e763b.mp4

### Minimal reproduction project

[Shooting framwork.zip](https://github.com/godotengine/godot/files/10808254/Shooting.framwork.zip)

**Comment by Calinou** [comment] 2023-02-22 21:04
The minimal reproduction project is not runnable as-is, as it only includes `project.godot` and `export_presets.cfg`.

@enemy141 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by enemy141** [comment] 2023-02-23 04:15
It's my personal project and even remove unnecessary files the project still too big to be uploaded

**Comment by enemy141** [comment] 2023-02-23 04:17
even the project was created by RC2 still works fine

**Comment by MrDixioner** [comment] 2023-02-23 15:45
Windows 10 x64, GeForce GT1030, Forward+, Vulkan, Godot 4 RC 3. The project opens, nothing crashes, everything works fine. The only thing is that when you open a project, it gives a warning about a scene not found.

Console output:
```
Godot Engine v4.0.rc3.official.7e79aead9 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 516.94 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce GT 1030

ERROR: Error opening file 'D:/Documents/Godot/TEMP/icon.svg'.
   at: (core/io/image_loader.cpp:90)
Editing project: D:/Documents/Godot/TEMP
Godot Engine v4.0.rc3.official.7e79aead9 - https://godotengine.org
Vulkan API 1.3.205 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GT 1030

ERROR: Attempt to open script 'res://src/AutoLoad/Singleton_signal.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Script does not inherit from Node: res://src/AutoLoad/Singleton_signal.gd.
   at: (editor/editor_autoload_settings.cpp:423)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
ERROR: Cannot get class 'GitPlugin'.
   at: (core/object/class_db.cpp:326)
ERROR: Received a nullptr VCS extension instance during construction.
   at: (editor/plugins/version_control_editor_plugin.cpp:145)
ERROR: Cannot open file 'res://src/Map/map.tscn'.
   at: (scene/resources/resource_format_text.cpp:1649)
ERROR: Failed loading resource: res://src/Map/map.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:221)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:574)
```

**Comment by enemy141** [comment] 2023-02-23 15:59
Also nothing unsual before crash !!!???![Untitled](https://user-images.githubusercontent.com/88548945/220961315-9d4b6cb8-7e9f-45db-aafc-af9cd40250ce.png)

**Comment by Zireael07** [comment] 2023-02-23 16:13
@enemy141 Have you tried disabling the Git plugin? I see there's an error related to it

**Comment by akien-mga** [comment] 2023-02-23 16:47
The latest release of the Git plugin is _not_ compatible with Godot 4.0 RCs.

Duplicate of https://github.com/godotengine/godot-git-plugin/issues/160

**Closed by akien-mga** 2023-02-23 16:47 UTC
Labels: bug, topic:editor, needs testing, crash
