### ISSUE TITLE
Editor state persistence puts me in a weird spot after editing a tileset

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#78192] opened 2023-06-13 15:42 UTC
### Godot version

4.1.beta1

### System information

Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 Threads)

### Issue description

I'm editing a tileset resource, then I close the editor.

![image](https://github.com/godotengine/godot/assets/85438892/59a1ef88-dc90-4559-b3de-4745728844ae)

When I open it, I get this. No "TileSet" tab at the bottom, no particular tileset to edit.

### Steps to reproduce

Described above

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-06-13 16:03
Duplicate of #77013

**Closed by KoBeWi** 2023-06-13 16:03 UTC
Labels: bug, topic:editor, topic:2d
