### ISSUE TITLE
Adding `GpuParticles3D` into scene crashes the editor

### ISSUE THREAD

**Issue by yedpodtrzitko** [godotengine/godot#77681] opened 2023-05-31 06:12 UTC
### Godot version

v4.1.dev.custom_build.d9cf36950 / v4.1.dev3.official

### System information

MacOS 13.4, MB Pro M2, Compatibility Renderer

### Issue description

- adding `GPUParticles3D` into the scene crashes the editor:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.dev.custom_build (d9cf3695033a71902010239a27b7a264db7840cc)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00000001979daa24 _sigtramp + 56
[2] 2   libGLProgrammability.dylib          0x00000001fc63e27c glpLLVMCGSwitchStatement + 176
[3] 3   libGLProgrammability.dylib          0x00000001fc634ad8 glpLLVMCGNode + 588
[4] 4   libGLProgrammability.dylib          0x00000001fc63de60 glpLLVMCGBlock + 444
[5] 5   libGLProgrammability.dylib          0x00000001fc634aa8 glpLLVMCGNode + 540
[6] 6   libGLProgrammability.dylib          0x00000001fc63de60 glpLLVMCGBlock + 444
[7] 7   libGLProgrammability.dylib          0x00000001fc634aa8 glpLLVMCGNode + 540
[8] 8   libGLProgrammability.dylib          0x00000001fc650a9c glpLLVMCGIfStatementShortCircuit + 208
[9] 9   libGLProgrammability.dylib          0x00000001fc634ab8 glpLLVMCGNode + 556
[10] 10  libGLProgrammability.dylib          0x00000001fc63de60 glpLLVMCGBlock + 444
[11] 11  libGLProgrammability.dylib          0x00000001fc634aa8 glpLLVMCGNode + 540
[12] 12  libGLProgrammability.dylib          0x00000001fc63da68 glpLLVMCGFunctionDefinition + 2664
[13] 13  libGLProgrammability.dylib          0x00000001fc633744 glpLLVMCGTopLevel + 1480
[14] 14  libGLProgrammability.dylib          0x00000001fc65b20c glpLinkProgram + 10004
[15] 15  libGLProgrammability.dylib          0x00000001fc675140 ShLink + 208
[16] 16  GLEngine                            0x00000001fc829ac8 gleLinkProgram + 1228
[17] 17  GLEngine                            0x00000001fc797bcc glLinkProgramARB_Exec + 256
[18] ShaderGLES3::_compile_specialization(ShaderGLES3::Version::Specialization&, unsigned int, ShaderGLES3::Version*, unsigned long long) (in godot.macos.editor.dev.arm64) (shader_gles3.cpp:0)
[19] ShaderGLES3::_initialize_version(ShaderGLES3::Version*) (in godot.macos.editor.dev.arm64) (shader_gles3.cpp:678)
[20] ShaderGLES3::_version_bind_shader(RID, int, unsigned long long) (in godot.macos.editor.dev.arm64) (shader_gles3.h:204)
[21] ParticlesCopyShaderGLES3::version_bind_shader(RID, ParticlesCopyShaderGLES3::ShaderVariant, unsigned long long) (in godot.macos.editor.dev.arm64) (particles_copy.glsl.gen.h:29)
[22] GLES3::ParticlesStorage::_particles_update_instance_buffer(GLES3::ParticlesStorage::Particles*, Vector3 const&, Vector3 const&) (in godot.macos.editor.dev.arm64) (particles_storage.cpp:892)
[23] GLES3::ParticlesStorage::update_particles() (in godot.macos.editor.dev.arm64) (particles_storage.cpp:1102)
[24] RenderingServerDefault::_draw(bool, double) (in godot.macos.editor.dev.arm64) (rendering_server_default.cpp:87)
[25] RenderingServerDefault::draw(bool, double) (in godot.macos.editor.dev.arm64) (rendering_server_default.cpp:397)
[26] Main::iteration() (in godot.macos.editor.dev.arm64) (main.cpp:3405)
[27] OS_MacOS::run() (in godot.macos.editor.dev.arm64) (os_macos.mm:718)
[28] main (in godot.macos.editor.dev.arm64) (godot_main_macos.mm:77)
[29] 29  dyld                                0x0000000197653f28 start + 2236
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

- add `GPUParticles3D` node into a scene

### Minimal reproduction project

-

**Comment by Calinou** [comment] 2023-05-31 08:47
- Duplicate of https://github.com/godotengine/godot/issues/72469.

**Closed by Calinou** 2023-05-31 08:47 UTC
