### ISSUE TITLE
GDScript 2.0: `@export_category` interferes with the property inspector tooltip

### ISSUE THREAD

**Issue by permelin** [godotengine/godot#64432] opened 2022-08-15 11:45 UTC
### Godot version

v4.0.alpha.custom_build [f2a616841]

### System information

Linux

### Issue description

Properties can be documented by giving them a description with `##` comments. That description is then showed as a tooltip in the inspector, like this.
![example1](https://user-images.githubusercontent.com/36154/184624919-4048ad79-7aef-4264-9e6c-d7138eb35fd1.png)

However, any properties following an `@export_category` annotation will only have a "no description" tooltip. 
![example2](https://user-images.githubusercontent.com/36154/184624935-ad23ea3f-bde7-4672-b4d6-47de839b66b7.png)

This bug actually predates `@export_category` and also occurs when using `PROPERTY_USAGE_CATEGORY` directly in `_get_property_list()`.

The problem is that `EditorInspector::update_tree()` assumes that any property with `PROPERTY_USAGE_CATEGORY` either has a `name` that is a class name or a `hint_string` that is a path to a script. And it uses that class/path to look up the description of subsequent properties.

One possible fix is to simply add the required hint string to `@export_category`. I've verified that this works.
```diff
--- a/modules/gdscript/gdscript_parser.cpp
+++ b/modules/gdscript/gdscript_parser.cpp
@@ -3826,6 +3826,7 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
        switch (t_usage) {
                case PROPERTY_USAGE_CATEGORY: {
                        annotation->export_info.usage = t_usage;
+                       annotation->export_info.hint_string = script_path;
                } break;
```

One downside to that is that the tooltip of the category itself will be the description of the script ("This is a description of the script" in the screenshots above).

I guess the alternative is to change `EditorInspector::update_tree()` which is a 670 line hairy monster.

### Steps to reproduce

See screenshots above.

**Comment by adamscott** [comment] 2023-01-08 17:20
Confirmed on master (fcba87e).

### Minimal reproduction project
[64432.zip](https://github.com/godotengine/godot/files/10369013/64432.zip)

**Comment by akien-mga** [comment] 2023-10-02 09:05
I can't reproduce the bug in 4.2-dev5, while it's reproducible up to 4.2-dev4.

I don't see right away which change would have solved it in https://godotengine.github.io/godot-interactive-changelog/#4.2-dev5, maybe @dalexeev has an idea?

**Comment by dalexeev** [comment] 2023-10-02 09:09
* See also #78934.
* Fixed by #81221.

**Closed** 2023-10-02 09:11 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed

**Comment by TechnoLukas** [comment] 2024-02-13 14:45
It also depends on placement of `@export_category()`. 
For example if category is not placed at the first place, then it works:
`
## Description 0
@export_range(1, 10, 1, "or_greater") var speed_up = 1

@export_category("category 1")
## Description 1
@export var model_path := ""
## Description 2
@export_range(1, 10, 1, "or_greater") var action_repeat := 8

@export_category("category 2")
## Description 3
@export_range(1, 10, 1, "or_greater") var num_mod := 1
`

Though if it would be placed on the first place, then it won't work :
`
@export_category("category 0")
@export_range(1, 10, 1, "or_greater") var speed_up = 1

@export_category("category 1")
## Description 1
@export var model_path := ""
## Description 2
@export_range(1, 10, 1, "or_greater") var action_repeat := 8

@export_category("category 2")
## Description 3
@export_range(1, 10, 1, "or_greater") var num_mod := 1
`

**Comment by dalexeev** [comment] 2024-02-14 08:36
@TechnoLukas See #88318. For the future, feel free to open a new issue instead of commenting on a closed old one.
