### ISSUE TITLE
Plus/add button in TileSet editor is too big and overlaps with other UI elements

### ISSUE THREAD

**Issue by JulianGmp** [godotengine/godot#81766] opened 2023-09-16 21:14 UTC
### Godot version

4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sun, 13 Aug 2023 01:33:59 +0000 - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) () - AMD Ryzen 7 4700U with Radeon Graphics (8 Threads)

### Issue description

I was playing around with making a tilemap and added alternative tiles to account for rotating tiles.
I noticed that sometimes the white plus button to add a new alternative tile was twice as large as it should be and overlapped with other elements in the UI. For example, I wasn't able to click on a tile that was beneath the plus button for example.

![2023-09-16_22:38:11](https://github.com/godotengine/godot/assets/23147553/e87255f3-cee1-424e-ab04-a48888eb4319)
![2023-09-16_22:38:20](https://github.com/godotengine/godot/assets/23147553/01acce15-c302-411d-99c8-2823303c4824)

I attached a video of this, please note that you can't see the context menu because of the recording.

https://github.com/godotengine/godot/assets/23147553/26d514f7-b5e5-491c-99b3-0d41d271124e

### Steps to reproduce

1. Open the tileset editor
2. click on any ui element (selecting a tile, switching to "Select", ...)

This happens very consistently to me and I haven't seen it elsewhere so this might be specific to a linux desktop, or maybe KDE, or wayland, or a any combination of any of these. 

### Minimal reproduction project

I doubt this is related to the project itsself but just in case: [elgaming.tar.gz](https://github.com/godotengine/godot/files/12641580/elgaming.tar.gz)

**Comment by bitsawer** [comment] 2023-09-16 21:54
Thanks for the report, looks like a duplicate of https://github.com/godotengine/godot/pull/80968 which was fixed in master by https://github.com/godotengine/godot/pull/80968. Closing as duplicate.

**Closed by bitsawer** 2023-09-16 21:54 UTC

**Comment by JulianGmp** [comment] 2023-09-17 17:06
Ohh I missed that issue, sorry for the double report.
Though I'm glad to see it's already fixed, brb building godot from source :+1:
