### ISSUE TITLE
Creating a new node from recent nodes panel might create wrong node

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#58404] opened 2022-02-21 21:48 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

Sometimes when selecting one of the recent nodes on Create new node -dialog, node with similiar name plus suffix gets selected and created (eg. Node2D instead of Node).

### Steps to reproduce

![nimetön](https://user-images.githubusercontent.com/1621768/155029946-a4dd6dda-ac6a-4000-aef5-69d5d5f7b40b.png)

**Comment by IgorKordiukiewicz** [comment] 2022-02-27 17:00
It looks like it only happens with `Node`. If scene is a 2D scene, then `Node2D` gets selected, and if scene is a 3D scene, then `Node3D` gets selected, so maybe that's the desired behaviour?

**Comment by aXu-AP** [comment] 2022-02-27 17:47
No, it happens with AudioStreamPlayers too. I still haven't found exact steps to reproduce this, but it happens commonly enough.

Viewing this problem a bit more widely, I'd say the problem root isn't in ui, but in search. If you search for Node, Node2D/3D may get selected. Same kind of things happen with code editor, too, with writing `vector2` autocomplete may suggest this as `PackedVector2Array` instead. I'm not sure if that's related though.

**Comment by fazil47** [comment] 2022-02-28 09:04
As I understand it, clicking on a recent node updates the search bar with its name and selects the top result. `CreateDialog::type_list` contains all the types search will look through, but it doesn't include `Node` because of this line in `CreateDialog::_should_hide_type`:
https://github.com/godotengine/godot/blob/ff877adf0f6a9f2073e95d6fd6c59515b9e90cd2/editor/create_dialog.cpp#L128-L130

But even if `Node` is in `CreateDialog::type_list`, it's not the search result with the highest score because in a 3D scene `CreateDialog::preferred_search_result_type` is one derived from `Node3D` and in a 2D scene it's one derived from `Node2d`. 
https://github.com/godotengine/godot/blob/ff877adf0f6a9f2073e95d6fd6c59515b9e90cd2/editor/create_dialog.cpp#L347

![3d_scene](https://user-images.githubusercontent.com/18116695/155954596-7f1d5bcf-9559-4822-9c8b-34b83c9b81a5.png)

![2d_scene](https://user-images.githubusercontent.com/18116695/155954513-f5b6e55c-11fb-4075-a899-f97640067896.png)

**Comment by Sauermann** [comment] 2022-03-19 22:02
Duplicate of #51632

**Closed** 2022-03-19 22:45 UTC
Labels: bug, topic:editor, needs testing
