### ISSUE TITLE
Empty files being generated and cluttering my project in 4.1

### ISSUE THREAD

**Issue by emmdie** [godotengine/godot#75725] opened 2023-04-05 22:53 UTC
### Godot version

4.1.dev.custom_build [ac2e82463]

### System information

Manjaro Linux, Kernel 5.13.19-2, 

### Issue description

I have a lot of godot related files in my project folders, that are empty. Their names resemble actual files of my project, with a hash/version(?) appended. They are seemingly created upon saving changes or opening the project but never deleted.  
![godotClutter](https://user-images.githubusercontent.com/59830170/230228311-f7101971-2ce1-40ed-a7f9-7de9e67e4767.jpg)
This persists regardless of using git or not, also in a new project.   
The link to the project my screenshot is from, is here:  https://github.com/emmdie/TowerDefense

### Steps to reproduce

Creating a sample project, opening it with my godot version. Create a node, attach a script, add comments and save after each. File system looks like this: 

![godotClutter2](https://user-images.githubusercontent.com/59830170/230228640-fa1f2086-cb28-42e8-ae0d-6c4dea170360.jpg)
 
My godot version is the current git build from the AUR: https://aur.archlinux.org/packages/godot-git

### Minimal reproduction project

[clutter.zip](https://github.com/godotengine/godot/files/11163817/clutter.zip)

**Comment by emmdie** [comment] 2023-04-05 22:54
I didn't find a duplicate, hope I searched for the right terms. If the solution is to simply wait for an update or use a different version, that's fine by me :)

**Comment by gotnospirit** [comment] 2023-04-06 00:57
see #75078

**Comment by Calinou** [comment] 2023-04-06 01:09
- Duplicate of https://github.com/godotengine/godot/issues/75078 (which is resolved in the latest `master` branch or 4.0.2).

**Closed by Calinou** 2023-04-06 01:09 UTC
Labels: bug, topic:editor
