### ISSUE TITLE
GLES2 Editor (3.2 alpha) corrupted on OSX

### ISSUE THREAD

**Issue by tadaaagames** [godotengine/godot#32601] opened 2019-10-06 18:34 UTC
**Godot version:**
Godot 3.2 alpha1

**OS/device including version:**
Macbook Pro 13" on OSX 10.14.6

**Issue description:**
Editor interface is corrupted on projects with GLES2. 

<img width="1792" alt="es2" src="https://user-images.githubusercontent.com/46694168/66273876-3124fe80-e870-11e9-856d-20458ced9a94.png">

<img width="1792" alt="es3" src="https://user-images.githubusercontent.com/46694168/66273877-3124fe80-e870-11e9-8f5b-5387107d06a5.png">

**Steps to reproduce:**
Simply create a new blank project and select GLES2

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2019-10-06 18:47
This is likely a duplicate of https://github.com/godotengine/godot/issues/32574, if it is, it is good to know it is happening on OSX as well. I thought it may just be a windows bug.

**Comment by tadaaagames** [comment] 2019-10-06 19:17
Not sure. I'm not getting any crashes. The interface is not displaying correctly and both the build and the editor are choppy

**Comment by usbhell** [comment] 2019-10-06 21:02
I am seeing this too, its like the theme is missing bits its useable but dark and very hard to see what your doing. This is the Default theme, when you create a new project it looks like the screen print above, when you create a new scene it looks like the one below. Ive been using v3.2.dev.calinou.188a10df8 for a while and it does not have this problem. GLES3 is fine.

GLES2
OSX 10.11.6
NVIDIA GeForce 9400 256 MB

![theme](https://user-images.githubusercontent.com/14961837/66275792-5fb0d280-e88c-11e9-937b-ef1fe8b2fc8d.png)

**Comment by clayjohn** [comment] 2019-10-06 21:10
Okay, definitely a duplicate of #32574 then. I have a PR that should fix it by disabling the changes that broke the editor.

**Comment by usbhell** [comment] 2019-10-06 21:42
just this on the console, dont know if its related
 
WARNING: _render_target_allocate: Cannot allocate mipmaps for 3D post processing effects
   At: drivers/gles2/rasterizer_storage_gles2.cpp:4884.

**Comment by akien-mga** [comment] 2019-10-07 05:20
Fixed by #32603.

**Closed by akien-mga** 2019-10-07 05:20 UTC
Labels: bug, platform:osx, topic:editor, topic:rendering
