### ISSUE TITLE
LightmapGI does not take transparency into account when baking shadows.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#77590] opened 2023-05-28 21:15 UTC
### Godot version

v4.0.3.stable - v4.3.dev3

### System information

Godot v4.3.dev3 - Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 Threads)

### Issue description

As the title says, LightmapGI bakes shadows for objects with transparent materials as if they are 100% opaque.
I tried baking with every transparency mode possible, Alpha, Scissor, Hashed, Depth Prepass, none of it makes a difference.
This worked fine in Godot 3, so there is definitely a bug here.

Godot 3:
![image](https://github.com/godotengine/godot/assets/781121/c0485b9c-966d-46d8-ab6a-9ad96be94bb1)

Godot 4:
![image](https://github.com/godotengine/godot/assets/781121/1e6694eb-0d89-4fbb-abde-274d99894187)

### Steps to reproduce

1. Download the included MRP's, both Godot 3 and Godot 4 versions are provided.
2. Load up the projects and compare results.

### Minimal reproduction project

[mrps.zip](https://github.com/godotengine/godot/files/11591010/mrps.zip)

**Comment by EzraT** [comment] 2023-10-31 21:55
Retested in v4.2.beta4.official, still present.

**Comment by EzraT** [comment] 2024-02-11 12:06
I'm probably way in over my head on this, as this probably isn't a good first issue for a C++ beginner, but I'd like to take a stab at atleast taking a look at this issue myself.
Would somebody be so kind as to point me towards the relevant source files related to this issue?

Thanks in advance.

**Comment by Calinou** [comment] 2024-02-12 23:04
I can still reproduce this on 4.3.dev cae759949 (Linux, GeForce RTX 4090 with NVIDIA 545.29.06):

![image](https://github.com/godotengine/godot/assets/180032/885b476a-3215-4118-8a4e-b7f4d34d876a)

**Comment by passivestar** [comment] 2024-03-29 23:18
Encountered this too, 4.2.1, macOS 14.4.0 - Vulkan (Forward+) - Apple M1 Max

**Comment by EzraT** [comment] 2024-08-15 10:00
It's honestly quite disappointing and disheartening to see a crucial feature, that every major 3D game engine needs to have, is still incomplete and missing vital functionality, especially in an engine with as much potential as Godot has.

Godot 4 is nearing its third point release and LightmapGI is still incomplete, and will likely remain incomplete until 4.4, but even that isn't a certainty.

I get it, Godot is an open source project, and its contributors work on what they want to work on, when they can, I have nothing against that at all, I understand the nature of open source software projects, and I appreciate all the work people pour into it.

But I do think sometimes it's also important to look more objectively at what needs to be done and fixed to actually implement crucial features in a complete way. Godot has great features and insane potential, but the problems become apparent when you realize that some of those lack functionality, (this issue is an example of that), [or otherwise don't work together properly with other engine features](https://github.com/godotengine/godot/issues/60240). (Yes I know this is a Godot 3 issue, but this is a good example of the problem I'm trying to explain, this has been a long time problem.)

It's just disheartening to see this engine be so close to greatness, but at the same time always so far away from it because of crucial features that lack what they need to be considered complete solutions.

I don't want to put any pressure on anyone by voicing this, or point fingers at anyone, I get it, this is by and large how FOSS software development works.

I just wanted throw in my 2 cents on this and voice some of my concerns.

**Comment by AtlaStar** [comment] 2024-09-25 19:33
@EzraT thought you might be interested in this
![image](https://github.com/user-attachments/assets/19c0b286-a2ea-4e3a-9e1b-3a20a39cf5d1)
Notice though how it only wants to bake the lightmap when it is a child of a meshinstance?

Dunno if that was the behavior previously or not, but it gives some clues as to a possible solution if that isn't intended behavior, and a possible workaround for the time being

**Comment by AtlaStar** [comment] 2024-09-25 20:03
Scratch that, I forgot to actually bake the lightmaps. So in editor the maps appear fine if you change the nesting of the lightmap because it is showing the editor view, while if on the node where the lightmap existed, it falls to using the baked data. I did not realize that was the case when originally reading the issue

**Comment by AtlaStar** [comment] 2024-09-25 20:08
Further evidence showing that it isn't just showing things correctly in editor, but baking things correctly as well
![image](https://github.com/user-attachments/assets/17c1f044-c74c-4e10-917c-6f177325893e)

I will continue to look into things, although as I have not really onboarded myself onto the engine code, it may be something someone else would be able to solve sooner.

**Comment by EzraT** [comment] 2024-09-30 16:33
@AtlaStar 

I might be missing or misunderstanding something here but, are you sure those shadows are actually baked and part of the actual lightmap? Because they don't look like it, they look like Godot 4's normal dynamic shadows to me.

**Comment by AtlaStar** [comment] 2024-09-30 17:33
You are right, I lost this thread after I realized I was misinterpreting things and got sidetracked; they are the dynamic lights.

That said I believe that I saw a PR which would properly close this in the works/waiting for a few more things.

**Comment by atirut-w** [comment] 2024-10-01 01:21
> That said I believe that I saw a PR which would properly close this in the works/waiting for a few more things.

Indeed! #90109

**Closed** 2024-12-20 02:11 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
