### ISSUE TITLE
Integer division in a condition of an if block cannot be ignored

### ISSUE THREAD

**Issue by Lemonymous** [godotengine/godot#82276] opened 2023-09-25 00:45 UTC
### Godot version

v4.2.dev5.mono.official [e3e2528ba]

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1050 Ti (31.0.15.3623)

### Issue description

Godot will continue to warn about integer division in the condition of an if block, even when adding an ignore command.
```gdscript
func _ready():
	@warning_ignore("integer_division")
	if 1/1:
		pass
```
The following warning will continue even after you click to ignore it.
```
[Ignore] Line N (INTEGER_DIVISION):Integer division, decimal part will be discarded.
```

### Steps to reproduce

Copy paste the code above

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-09-25 07:52
* Duplicate of #56592.

Closing as #56592 is a superset of this issue. Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-09-25 07:52 UTC

**Comment by Lemonymous** [comment] 2023-09-25 12:28
Thank you!

I apologize for not doing my due diligence of searching for the issue beforehand this time. Will try to remember it for next time.
