### ISSUE TITLE
In Editor Script panel, double clicking on the return datatype of function signature, includes the  ">" 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#90728] opened 2024-04-16 00:35 UTC
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

If function with a declared datatype and no space between the arrow and datatype, double click on datatype includes  the `>`.  It should only include the word.

### Steps to reproduce

Create function such as below and double click on Result. Do not leave a space between arrow and result . 
E.g. ` ->Result`
```gdscript
func run(cfg:ConfigResult)->Result:
    pass
```

### Minimal reproduction project (MRP)

none

**Comment by AThousandShips** [comment] 2024-04-16 08:47
Can you try this in a more recent debug build like dev5? Dev3 is pretty old now

**Comment by kitbdev** [comment] 2024-04-16 16:53
- Looks like a duplicate of https://github.com/godotengine/godot/issues/69254

**Comment by wyattbiker** [comment] 2024-04-16 19:23
> Can you try this in a more recent debug build like dev5? Dev3 is pretty old now

Have tried it with latest v4.3.dev5.official [c9c17d6ca]. 

And yes, as @kitbdev said it is duplicate of https://github.com/godotengine/godot/issues/69254

Same issues.

**Comment by kitbdev** [comment] 2024-06-25 19:39
- After https://github.com/godotengine/godot/pull/92514, it now selects `Result:` by default, with the colon.

**Comment by kitbdev** [comment] 2024-06-30 17:04
- Fixed by https://github.com/godotengine/godot/pull/93656

**Closed** 2024-06-30 21:05 UTC
Labels: bug, topic:gdscript, topic:editor
