### ISSUE TITLE
[WEB EDITOR] Opening a project, editor gets unusable

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#52692] opened 2021-09-15 09:44 UTC
### Godot version

3.3.4 beta-4

### System information

Mozilla Firefox over -> manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

![Screenshot_2021-09-15_06-40-55](https://user-images.githubusercontent.com/58845030/133410580-74ba056e-65e5-47f0-95a4-d9bce919f8e5.png)

The last error message keeps spamming, and the user isnt able to use the editor!

### Steps to reproduce

* download from the godot repository the web editor 3.3.4 beta 4
* Run in a local machine with nodejs

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2021-09-15 16:56
Duplicate of https://github.com/godotengine/godot/issues/52468 (fixed in the next beta).

**Closed by Calinou** 2021-09-15 16:56 UTC
