### ISSUE TITLE
Some meshes don't render in gridmaps while in compatibility mode

### ISSUE THREAD

**Issue by JohnathanLP** [godotengine/godot#83134] opened 2023-10-11 03:24 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11 - RTX 2060, driver version 31.0.15.3699

### Issue description

I have two gltf files, created in two different programs, both containing a (as best I can tell) identical white cube. Both scenes import and can be seen and used correctly in Godot and at least one other program, so I don't think there's anything wrong with those files. With each file, I have created a MeshInstance3D, as well as a MeshLibrary, which I've then used in a GridMap. In Forward+, everything works fine.
![image](https://github.com/godotengine/godot/assets/15066028/0397ead6-c34c-49ea-853e-2f3f284e2f0e)
The two cubes in the front are the MeshInstance3Ds, and the two clusters in the back are the TileMaps.
The problem comes when I switch to Compatability, which I often use for game jams which prefer HTML5 builds, and for working on my older laptop. 
![image](https://github.com/godotengine/godot/assets/15066028/1f10f1ed-39da-40aa-8fed-95e8653f4abd)
The MeshInstance3Ds work just fine, but the GridMap created with the mesh from Crocotile disappears entirely. The gridmap still "works", ie you can and remove cubes, but none of the cubes will render at all until you switch back to Forward+.

### Steps to reproduce

Open the attached project, verify that all cubes are present, switch to Compatibility, see that one GridMap stops rendering.

### Minimal reproduction project

[GridMapMinimalProject.zip](https://github.com/godotengine/godot/files/12864470/GridMapMinimalProject.zip)

**Comment by clayjohn** [comment] 2023-10-11 04:28
I can confirm that this issue existed in 4.1.1 (and all the way up to and including dev 6). 

After testing in master, it looks like this has been fixed already, most likely by https://github.com/godotengine/godot/pull/81575 which will be included in 4.2-beta1 and also will be cherrypicked for 4.1.3.

**Closed by clayjohn** 2023-10-11 04:28 UTC
