### ISSUE TITLE
[Web] You can only run a project once

### ISSUE THREAD

**Issue by MIfoodie** [godotengine/godot#83530] opened 2023-10-18 00:28 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Web -  (Compatibility) - WebKit WebGL -  (2 Threads)

### Issue description

Using the web editor, you can only run the project once before it completely breaks and you have to reload to see the changes.

### Steps to reproduce

***

### 1. Drag the icon on the screen
![Step 1 screenshot](https://images.tango.us/workflows/ec479b4d-f3b3-4b1d-9c78-9a91a85f4daa/steps/2f1b1973-5df9-4a9a-9c13-f47351956425/5a2fe0ad-5b11-4dbe-89ea-510c99fffcc2.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5153&fp-z=1.0038&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=2&mark-y=24&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTQlMkNGRjc0NDImdz0xMTk1Jmg9NzA1JmZpdD1jcm9wJmNvcm5lci1yYWRpdXM9MTA%3D)

### 2. Run the project
![Step 2 screenshot](https://images.tango.us/workflows/ec479b4d-f3b3-4b1d-9c78-9a91a85f4daa/steps/45929674-1f22-4ad7-a7e6-0732bebc004e/b3f6ee25-a1df-4dcd-9bbb-f53dcca091d3.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5153&fp-z=1.0038&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=2&mark-y=24&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTQlMkNGRjc0NDImdz0xMTk1Jmg9NzA1JmZpdD1jcm9wJmNvcm5lci1yYWRpdXM9MTA%3D)

### 3. Stop the project and move the icon to a different part of the screen
![Step 3 screenshot](https://images.tango.us/workflows/ec479b4d-f3b3-4b1d-9c78-9a91a85f4daa/steps/86db5fb2-c142-459a-a700-7aec46a2de1c/f4af6065-b9a4-4075-b639-312d1ac6ea17.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5153&fp-z=1.0038&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n&mark-x=2&mark-y=24&m64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL2JsYW5rLnBuZz9tYXNrPWNvcm5lcnMmYm9yZGVyPTQlMkNGRjc0NDImdz0xMTk1Jmg9NzA1JmZpdD1jcm9wJmNvcm5lci1yYWRpdXM9MTA%3D)

### 4. Run it again - notice the position of the icon (it doesn't change)
![Step 4 screenshot](https://images.tango.us/workflows/ec479b4d-f3b3-4b1d-9c78-9a91a85f4daa/steps/a427af63-459c-4234-a096-7a53b38fd1fe/5a3178e1-1324-4968-83e1-06ce65368309.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&w=1200&border=2%2CF4F2F7&border-radius=8%2C8%2C8%2C8&border-radius-inner=8%2C8%2C8%2C8&blend-align=bottom&blend-mode=normal&blend-x=0&blend-w=1200&blend64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmstdjIucG5n)

<br/>

***

### Minimal reproduction project

N/A - I don't think anyone needs the file to a blank Godot project :)

**Comment by akien-mga** [comment] 2023-10-18 09:05
I can't reproduce the issue with Firefox Nightly 120.0a1 (2023-10-17) or Chromium 117.0.5938.132 on Linux.

Here's a test in Firefox Nightly where reloading the project works fine:

https://github.com/godotengine/godot/assets/4701338/6a05f172-ee77-44ea-ad4e-59279d77d9e3

Which browser are you using and on which OS? I see WebKit so I suppose Safari on macOS, but would be good to clarify and know the version.

Can you check the web debugger console while running the editor to see what errors are printed when you attempt to play the project the first and then the second time?

**Comment by akien-mga** [comment] 2023-10-18 09:09
Actually, how do you stop the project between attempts? From my tests it works if you close the "Game" instance using the cross icon next to it.

The "Editor" instance doesn't seem to be able to kill the process by pressing "Stop" or "Run", so indeed if you don't close the game using the cross icon, it doesn't work.

If that's your issue, then it's a duplicate of #57429.

**Closed** 2023-10-18 15:14 UTC
Labels: bug, platform:web, topic:editor
