### ISSUE TITLE
Texture loading outside of res://<path> does nothing. Is it a bug?

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22433] opened 2018-09-25 18:50 UTC
**Godot version:**
3.1 alpha
Mac OS X

**Issue description:**
Cannot load a texture outside of the `res://` root folder.

Setup a button and add icon from a folder not part of `res://` (E.g. `res://Users/userx/agodotproj/freeknight/png`). When you select the png file, the Load file dialog does nothing. Just sits there. You can only cancel or navigate back to the `res://` root folder.

**Comment by SimoFoto** [comment] 2018-09-26 09:10
I'm pretty sure this is intended. You can't access any files you want on the system, only those that are located in the project root directory. If you want to access something else you will have to use folders accessible via `user://` You should read this: http://docs.godotengine.org/en/3.0/tutorials/io/data_paths.html?highlight=user%3A%2F%2F

**Comment by jjay** [comment] 2018-09-26 14:33
You can't use `ResourceLoader::load()` for resources outside project path because Godot import resource and keep internal versions of it. But you can can can create a texture from image:
```gdscript
var img = Image.new()
img.load("/path/to/image.png")
var tex = ImageTexture.new()
tex.create_from_image(img)
```

**Comment by wyattbiker** [comment] 2018-09-26 20:57
It seems File.open() will honor paths anywhere on the system without user://.

```
	var new_file = File.new();
	var err=new_file.open("/Users/user/agodotproj/out.json", new_file.READ);
	if err != 0:
		print(err)
	print(new_file.get_len())
	var data=new_file.get_as_text();
	print(data.length())
	err=new_file.close();
```

**Comment by groud** [comment] 2018-09-28 13:17
Closing as a duplicate of #17848

**Closed by groud** 2018-09-28 13:17 UTC
