### ISSUE TITLE
Array.slice() creates returns array who's type is incorrect

### ISSUE THREAD

**Issue by sancho2** [godotengine/godot#67015] opened 2022-10-07 05:21 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

Ubuntu 20.04.5 LTS

### Issue description

The following code reports an error: 
"Cannot convert argument 1 from array to array"  
```
func test_slice(a:Array[int]):
	print(a)

func testtest(): 
	var a:Array[int] = [1, 2, 3, 4, 5]
	print(typeof(a))
	print(typeof(a.slice(1,2)))
	test_slice(a.slice(1,2))
```
Both typeof() commands return 28.   
It should have accepted the slice as a valid parameter value.    
It is worth noting that it is possible to store the slice in a typed variable and then pass that variable to the function. This works as expected.   

### Steps to reproduce

1. Create a typed array.   
2. Create a function with a parameter of the same type as in step 1. 
3. Try to pass the array to the function.   
4.

**Comment by amoriqbal** [comment] 2022-10-07 10:37
I can confirm it on Linux Mint 20 , Godot 4.0 beta 2

**Comment by kleonc** [comment] 2022-10-07 12:31
Kinda a duplicate of #63892 but I think we can leave it open as it's technically a little different.
#63892 is about `Array[T]`'s methods returning `Variant` instead of `T`.
This issue is about `Array[T]`'s methods returning `Array` instead of `Array[T]`.

**Comment by Mickeon** [comment] 2022-10-08 22:21
Unlike #63892 it's not a deeply rooted issue and can be fortunately fixed with a simple assignment.

**Closed** 2022-10-09 16:32 UTC
Labels: bug, topic:gdscript
