### ISSUE TITLE
Setter function of exported property only called when the value is different from its default

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#83375] opened 2023-10-15 08:44 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

The setter function of an exported property is only called when the value is different from its default.

I think it should be called even if its value is the same as the default one, because the setter function might contain logic considering both cases. If the setter is not called when initializing the class, it would be skipped, giving unexpected results.

### Steps to reproduce

Attach this script to a `Control` and run the scene with different exported property values (default and not default):
```
extends Control


@export var title: String:
	set(title_):
		title = title_
		print("set_title")
```

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/12909027/bug.zip)

**Comment by AThousandShips** [comment] 2023-10-15 08:44
This isn't because the setter isn't called for default, it's because the default value isn't stored in the scene so it isn't called when the scene is loaded

**Comment by acgc99** [comment] 2023-10-15 08:52
I realized this thing when exporting horizontal alignment of a child `Label`. I set the default to `HORIZONTAL_ALIGNMENT_CENTER` but then, when running the scene, the text was on the left.

To solve this, on the `_init` function of the parent, I had to write `horizontal_alignment = horizontal_alignment` to force calling the setter (or `label.horizontal_alignment = horizontal_alignment` more directly).

**Comment by AThousandShips** [comment] 2023-10-15 08:53
Yes, that's to be expected

You are expected to have your code be configured based on the default values, that's what them being default values means IMO

**Comment by acgc99** [comment] 2023-10-15 08:55
So although I would like to use `HORIZONTAL_ALIGNMENT_CENTER` as default, I'm forced to use `HORIZONTAL_ALIGNMENT_LEFT` to get the right behaviour.

**Comment by AThousandShips** [comment] 2023-10-15 08:57
That's not a bug though you need to make sure that your script and scene is set up so it works correctly when used, you need to make sure your label has the same default as your property

**Comment by acgc99** [comment] 2023-10-15 09:03
I agree it's not a bug. **You have to design the node from default values**. This behaviour should be commented at [docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#properties-setters-and-getters) at least.

**Comment by AThousandShips** [comment] 2023-10-15 09:06
Sure this can be added to some of the documentation, unsure how to make it clearer though

**Comment by acgc99** [comment] 2023-10-15 09:10
I opened the corresponding [issue at docs](https://github.com/godotengine/godot-docs/issues/8246).

**Comment by AThousandShips** [comment] 2023-10-15 09:17
Closing in favour of https://github.com/godotengine/godot-docs/issues/8246

**Closed by AThousandShips** 2023-10-15 09:17 UTC
Labels: discussion, topic:core, documentation
