### ISSUE TITLE
Inherited scripts does not initialize @onready variables

### ISSUE THREAD

**Issue by quantumcode-martin** [godotengine/godot#60168] opened 2022-04-12 08:52 UTC
### Godot version

4.0 alpha 6

### System information

Windows 10

### Issue description

When a `@onready` variable is declared inside a script and you inherit this script, the inherited script will not initiate the variable.
The variable will exist in the inheriting script but it's value will always be `null`.

**Wokraround**: Just re-initiate your variable in the inheriting script.
```
func _ready():
   my_variable = $MyNode
```

### Steps to reproduce

Inside the first script, let's declare a variable like so:
`@onready var my_variable := $MyNode`

Now we can inherit this script:
```
extends "res://MyFirstScript.gd"

func _process(delta):
    print(my_variable)
```

This will print `null` every time.

**Comment by akien-mga** [comment] 2022-04-12 09:51
I'm not sure this is a bug. It works fine if you use `@onready var my_variable := 42`.

But here you're assigning a Node, for a script which you then inherit from another Node which may not have the same `MyNode` as child. The child nodes don't come together with the script, they're part of the scene tree, not script.

When making sure the node inheriting `MyFirstScript.gd` actually has a child node named `MyNode`, then your example works fine.

**Comment by KoBeWi** [comment] 2022-04-12 12:13
Likely duplicate of #52223

**Comment by dalexeev** [comment] 2023-07-03 07:25
The bug is not reproducible in master:
![](https://github.com/godotengine/godot/assets/47700418/ad2a1079-ab24-4014-b9cc-a54d9d8e1b45)

**Closed** 2023-07-03 08:43 UTC
Labels: bug, topic:gdscript
