### ISSUE TITLE
Game window opens on the bottom right of the monitor when using Dual Monitors

### ISSUE THREAD

**Issue by TheCire** [godotengine/godot#21198] opened 2018-08-19 20:48 UTC
**Godot version:**
Godot Version 3.0 (Mono)

**OS/device including version:**
macOS 10.13.6

**Issue description:**
The game window pops up in the bottom right of the monitor instead of centered 

**Steps to reproduce:**
Open Godot on a Mac with a second monitor plugged in. Run a scene and watch as the game window pops up in the bottom right of the second monitor

**Minimal reproduction project:**
No need, just plug in a second monitor

**Comment by vnen** [comment] 2018-08-19 21:28
Duplicate of #16570

**Closed by vnen** 2018-08-19 21:28 UTC
