### ISSUE TITLE
App icon flashes before boot_splash on Android

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [godotengine/godot#95131] opened 2024-08-04 14:38 UTC
### Tested versions

- Reproducible on Godot 4.3.RC2

### System information

Windows 10 - Godot v4.3.RC2 - Forward+

### Issue description

When exporting a Godot project to Android, a brief but noticeable flash of the app icon occurs before the intended boot splash (image or color set in Project Settings -> Application -> Boot Splash) is displayed. This Brief icon display cannot be hidden or replaced using current Godot settings.

https://github.com/user-attachments/assets/ef495720-3029-439f-ae72-679d6fc37d1a

### Steps to reproduce

1. Create a new Godot project or use an existing one.
2. Set a Boot Splash image or color: Go to Project Settings -> Application -> Boot Splash and either select an image or define a background color.
3. Export the project for Android: Configure the export settings to android.
4. Observe the app launch sequence: Pay close attention to the screen immediately after launching the app. You should briefly see the app icon displayed before the boot splash image/color appears.

### Minimal reproduction project (MRP)

[AppIcon.zip](https://github.com/user-attachments/files/16487940/AppIcon.zip)

**Comment by Calinou** [comment] 2024-08-04 14:49
What does your app icon look like? I believe the pre-launch icon is based on Android design assets; it is *not* drawn by Godot itself. This means that you need to configure your project to use assets you created for this purpose in the Android export preset in the Export dialog.

**Comment by EiTaNBaRiBoA** [comment] 2024-08-04 14:53
> What does your app icon look like before launching it? I believe the pre-launch icon is based on Android design assets; it is _not_ drawn by Godot itself. This means that you need to configure your project to use assets you created for this purpose in the Android export preset in the Export dialog.
> 
> Godot can generate those assets for you if you leave the field empty, but you'll still need to define an icon at the very least.

I am not sure i understand what you mean, The icon of the app is the godot icon svg. when launching the app, the expected result is to see the boot splash color (which the video example i set it to pink) but instead the app shows before the boot splash the icon of the app in the middle.

**Comment by Alex2782** [comment] 2024-08-06 16:49
How did you configure Icon? My Samsung Tab S7 (Android 13) shows the app icon in the splash screen first.


![Bildschirmfoto 2024-08-06 um 18 39 43](https://github.com/user-attachments/assets/da48505b-bced-4587-861c-7199006943ec)


Example: https://github.com/godotengine/godot-demo-projects/tree/master/2d/bullet_shower


![Bildschirmfoto 2024-08-06 um 18 42 38](https://github.com/user-attachments/assets/57fdcb85-73c9-41ed-ba2a-52104d0ce033)


> I am not sure i understand what you mean

I think this settings (Android Export)

![image](https://github.com/user-attachments/assets/6749d688-c5b0-48d0-bd42-628b03472280)

**Comment by EiTaNBaRiBoA** [comment] 2024-08-10 18:17
> How did you configure Icon?
> 
> > If i open other apps on my phone they do not show their icon on launch
> 
> My Samsung Tab S7 (Android 13) shows the app icon in the splash screen first. (always, also `other` apps)
> 
> ![Bildschirmfoto 2024-08-06 um 18 39 43](https://private-user-images.githubusercontent.com/41921395/355532223-da48505b-bced-4587-861c-7199006943ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTM4MjUsIm5iZiI6MTcyMzMxMzUyNSwicGF0aCI6Ii80MTkyMTM5NS8zNTU1MzIyMjMtZGE0ODUwNWItYmNlZC00NTg3LTg2MWMtNzE5OTAwNjk0M2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE4MTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NGNiNWYyZTg0Mjk4ZDM4ZjA1ZGE0Y2VhNmJjZWE0MTkxMjhmZjQ1ZjhlMzY5ZWZlY2IwYzdiYzQzMWE2MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLPRZ_HdtoH0jKCjzmpb46wQegV58zDbtp97gcfgRas)
> 
> Example: https://github.com/godotengine/godot-demo-projects/tree/master/2d/bullet_shower
> 
> ![Bildschirmfoto 2024-08-06 um 18 42 38](https://private-user-images.githubusercontent.com/41921395/355533391-57fdcb85-73c9-41ed-ba2a-52104d0ce033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTM4MjUsIm5iZiI6MTcyMzMxMzUyNSwicGF0aCI6Ii80MTkyMTM5NS8zNTU1MzMzOTEtNTdmZGNiODUtNzNjOS00MWVkLWJhMmEtNTIxMDRkMGNlMDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE4MTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZDc1NWE0Y2QzMmY2ZjQ5Yzc5MmE0NTNjZDNjODkyNzg4NjczZTkwMzhjMWJhMmJmNzFkMjEzMTllOGI4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNJ4Yd7Rd0bikja3xw3KgPTUvdlrdTqUar19qEuJtUI)
> 
> > I am not sure i understand what you mean
> 
> I think this settings (Android Export)
> 
> ![image](https://private-user-images.githubusercontent.com/41921395/355534244-6749d688-c5b0-48d0-bd42-628b03472280.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTM4MjUsIm5iZiI6MTcyMzMxMzUyNSwicGF0aCI6Ii80MTkyMTM5NS8zNTU1MzQyNDQtNjc0OWQ2ODgtYzViMC00OGQwLWJkNDItNjI4YjAzNDcyMjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE4MTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTVjZGU0M2RiNzNiOWNlYTUwNGRlOWFkMmRkY2Y4MjhmNTQyZjM3ZmRkZDJlNGJlYTZmYzFhMDZhZGI1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGuNoFwMEpKg-8F4vmy1bfFJyLwYqcEzWmq2ZCQGLb4)

Thanks for the suggestion, I tried setting the main icon to 192x192 in the android export settings, but the issue still remains. I still see the default icon briefly before the splash screen appears.
I tested on Godot 4.2.2 and this issue doesn't occur. Could this be a regression?

**Comment by Alex2782** [comment] 2024-08-10 21:25
maybe PR #92965

or/and `Gradle Build`? I have deactivated `Gradle Build` and configured an icon.  It worked on Android 13 - Samsung.

![Screenshot 2024-08-10 231159](https://github.com/user-attachments/assets/b5d583d5-d823-4780-a71e-1606604cbbe5)

![image](https://github.com/user-attachments/assets/b09e75a4-18d0-4678-9a04-0c30d54ac00f)



<details><summary>godot-assets.svg</summary>

![godot-assets](https://github.com/user-attachments/assets/6fea4835-cad0-40af-8a60-e0aeabb92ab3)


</details>

**Comment by EiTaNBaRiBoA** [comment] 2024-08-11 04:27
> > I tried setting the main icon to 192x192 in the android export settings, but the issue still remains. I still see the default icon briefly before the splash screen appears.
> 
> maybe PR #92965
> 
> or/and `Gradle Build`? I have deactivated `Gradle Build` and configured an icon. It worked on Android 13 - Samsung.
> 
> ![Screenshot 2024-08-10 231159](https://private-user-images.githubusercontent.com/41921395/356838719-b5d583d5-d823-4780-a71e-1606604cbbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTA2MzMsIm5iZiI6MTcyMzM1MDMzMywicGF0aCI6Ii80MTkyMTM5NS8zNTY4Mzg3MTktYjVkNTgzZDUtZDgyMy00NzgwLWE3MWUtMTYwNjYwNGNiYmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA0MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZjM4ZjQyNTI1ZmI4MTRlODk0ZTllZGI5Nzg4ZDQwNWMwOWY1OTdkMjI4MzE2M2IzNjczOWM1YjY5YWM4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ntery0eOJBq9959DuFwKhOHqyxBdyI5igc6kC7AwDKE)
> 
> ![image](https://private-user-images.githubusercontent.com/41921395/356838685-b09e75a4-18d0-4678-9a04-0c30d54ac00f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTA2MzMsIm5iZiI6MTcyMzM1MDMzMywicGF0aCI6Ii80MTkyMTM5NS8zNTY4Mzg2ODUtYjA5ZTc1YTQtMThkMC00Njc4LTlhMDQtMGMzMGQ1NGFjMDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA0MjUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MmNkMDZlYTc3MWVmMmNlZTc0MzI4Yzg4ZTAxYWViNmU4NDE4YjFiNzIwZjQ2YzM0OWJiY2QzOTIxMjkyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MK_zV8n09W8CQd_SWL1qlOHzI9uZJ-quHPf2XjsvWq8)
> 
> godot-assets.svg

Both godot 4.2.2 and godot 4.3 that i tested on the same project used the same export settings and project settings. Godot 4.3 did reproduce the issue and godot 4.2.2 didn't reproduce the issue

**Comment by akien-mga** [comment] 2024-08-11 20:09
AFAIK the fact that an icon is shown when starting the app is intended behavior from Android itself. Apps built against recent SDKs behave this way, while some (possibly older) apps don't.

Now regarding why it's the default Godot icon, did you change the main project icon in the project settings? In my tests my custom icon.svg would be shown on Android just fine.

CC @m4gr3d

**Comment by EiTaNBaRiBoA** [comment] 2024-08-12 04:37
> AFAIK the fact that an icon is shown when starting the app is intended behavior from Android itself. Apps built against recent SDKs behave this way, while some (possibly older) apps don't.
> 
> Now regarding why it's the default Godot icon, did you change the main project icon in the project settings? In my tests my custom icon.svg would be shown on Android just fine.
> 
> CC @m4gr3d

Thanks for the reply, i know how to change the app icon and it wasn't part of the issue. The issue was opened due to what you said that the app icon shows before the display splash is due to the new sdk, do you think is it possible somehow to remove it or is it the new standard of android?

**Comment by Alex2782** [comment] 2024-08-12 10:06
@EiTaNBaRiBoA In your MRP `Gradle Build` is active, but you have not added the files to the zip file.

https://docs.godotengine.org/en/latest/tutorials/export/android_gradle_build.html
https://developer.android.com/develop/ui/views/launch/splash-screen?hl=en

I haven't tried it yet, but it should be possible if you customize files. You should be familiar with Android development.

![image](https://github.com/user-attachments/assets/08fa3704-df84-4813-8ddf-8b2077c52922)

**Comment by m4gr3d** [comment] 2024-08-12 11:19
> do you think is it possible somehow to remove it or is it the new standard of android?

@EiTaNBaRiBoA It's the new [Android standard](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate).

> Starting in Android 12, the system applies the [Android system default splash screen](https://developer.android.com/about/versions/12/features/splash-screen) on [cold](https://developer.android.com/topic/performance/vitals/launch-time#cold) and [warm starts](https://developer.android.com/topic/performance/vitals/launch-time#warm) for all apps. By default, this system splash screen is constructed using your app's launcher icon element and the [windowBackground](https://developer.android.com/reference/android/R.attr#windowBackground) of your theme, if it's a single color.

**Comment by anishmishra0** [comment] 2024-08-13 09:57
I have android 14 but I am not having this issue. I am currently using godot 4.2.2 with compatibility mode and my splash screen is properly visible.

Is this only present in 4.3??

**Comment by m4gr3d** [comment] 2024-09-02 13:45
No it's not possible to disable the app icon; as mentioned in the comment above this is the new Android standard.

**Comment by m4gr3d** [comment] 2024-09-02 13:45
Closing this issue as intended behavior.

**Closed** 2024-09-02 13:46 UTC
Labels: bug, platform:android, topic:porting
