### ISSUE TITLE
reizing intel gma 3150 linux

### ISSUE THREAD

**Issue by gra-frogger** [godotengine/godot#963] opened 2014-12-12 10:24 UTC
with godot is not in fullscreen mode the mouse point not is centered, but in with reized windows maximal the mouse go normal, this appen in the editor and in played game

**Comment by timwaters** [comment] 2015-01-06 20:23
I have a GMA 3150 I was able to get it working by enabling some things using this:
 http://www.cnx-software.com/2011/11/13/enable-opengl-2-0-and-webgl-for-intel-gma3150-in-ubuntu/

**Comment by akien-mga** [comment] 2015-11-05 08:30
If it's about very old hardware that does not support OpenGL 2.0 out of the box, I don't think we can do much. There is a workaround apparently in @timwaters link, so closing the issue (meaning that we Godot devs probably can't do anything about it).

**Closed by akien-mga** 2015-11-05 08:30 UTC

**Comment by akien-mga** [comment] 2015-11-06 10:23
Duplicate of #156, related to #1162.
