### ISSUE TITLE
android not finding compiled GD script

### ISSUE THREAD

**Issue by whilke** [godotengine/godot#2329] opened 2015-08-03 22:55 UTC
When I export a simple game to an android template with GDScripts set to compile, logcat spits out that it can't load any of the script resources.

if I tell the export to not compile GDScripts, script resources load just fine on android.

**Comment by whilke** [comment] 2015-10-03 05:12
I guess people are just not compiling GDScripts when exporting to Andorid?

**Comment by vnen** [comment] 2015-10-03 22:50
Strange, I always leave this option to compile (since it's the default) and never had such issue.

**Comment by akien-mga** [comment] 2015-11-10 15:46
Wild guess: do you by any chance load scripts at runtime with load() or preload(), without having them attached to some nodes in your scenes? If so you need to make sure to select to export *all files* and not just *scenes and resources*.

**Comment by whilke** [comment] 2015-11-11 19:20
That's possible, I will validate that when I get back to it.

**Comment by akien-mga** [comment] 2015-11-11 20:02
You can chose the type of data export here:
![res](https://cloud.githubusercontent.com/assets/4701338/11101495/78d94e1a-88b7-11e5-87bf-a22c4e4208a5.jpg)

**Comment by whilke** [comment] 2015-11-11 20:14
Double checked, all files is the export option that I have checked.

**Comment by reduz** [comment] 2015-12-31 22:27
need to check file/folder modification APIs on different OSs to make this work properly..

**Comment by akien-mga** [comment] 2016-07-15 08:49
Can you still reproduce this issue with 2.1-beta? Also, did you make sure to use export templates that match your Godot version?

**Comment by reduz** [comment] 2016-07-20 22:27
There was a bug related to newly added files not being added until you restart Godot that was fixed in 2.0, so I suspect at this point that this must be fixed, so closing.

**Closed by reduz** 2016-07-20 22:27 UTC
Labels: bug, platform:android, topic:porting
