### ISSUE TITLE
HTML5 Mono builds stall during initialization since 3.2.4 RC 4

### ISSUE THREAD

**Issue by ZwieBit** [godotengine/godot#47048] opened 2021-03-16 08:29 UTC
**Godot version:**
RC5 (from RC2 on)

**OS/device including version:**
IntelGraphics 655, GLES2

**Issue description:**
When i try to test a project with html5 export settings, the site ist halted and does not respond.

Current status (>RC2)
![image](https://user-images.githubusercontent.com/25595246/111278338-b4d44480-8639-11eb-8d62-129ce4fdce19.png)

*Edit fales: after force-stopping the script*
```
Script terminated by timeout at:
Godot/Module.then@http://0.0.0.0:8060/tmp_js_export.js:9:422409
promise callback*doInit@http://0.0.0.0:8060/tmp_js_export.js:615:21
init@http://0.0.0.0:8060/tmp_js_export.js:631:19
startGame@http://0.0.0.0:8060/tmp_js_export.js:727:11
@http://0.0.0.0:8060/tmp_js_export.html:222:12
@http://0.0.0.0:8060/tmp_js_export.html:242:5
```

Expected behaviour (RC1)
![image](https://user-images.githubusercontent.com/25595246/111278471-db927b00-8639-11eb-8269-5a8ac24e4654.png)

~When i try to run the export in nginx i get the following error: 
[image](https://user-images.githubusercontent.com/25595246/111281049-cf5bed00-863c-11eb-9582-e59bc18214fa.png)~ workaround applied via #47191

**Steps to reproduce:**
Download Project "GUI Theming Override" and Export it to HTML5

**Minimal reproduction project:**
Just download "GUI Theming Override" e.g.

**Comment by akien-mga** [comment] 2021-03-16 09:23
I can't seem to reproduce the issue, it loads fine for me in Firefox Nightly and latest Chrome stable, at least when served by Godot's localhost server (one click deploy).

**Comment by ZwieBit** [comment] 2021-03-16 09:33
In firefox and with internal server i get a rotating loading screen which stops after some seconds.
![image](https://user-images.githubusercontent.com/25595246/111286490-8ad35000-8642-11eb-985e-fb3979539355.png)

Tried changing my settings to english.
![image](https://user-images.githubusercontent.com/25595246/111286825-e69dd900-8642-11eb-8c29-2ef008f38c10.png)

**Comment by Faless** [comment] 2021-03-16 10:51
> When i try to run the export in nginx i get the following error:

The host is not returning the correct mime type for the `wasm` file.

**Comment by bruvzg** [comment] 2021-03-16 12:11
Can't reproduce it with exports from the classic Godot editor, but it is reproducible with Mono editor (exporting non-Mono project in both cases), macOS 11.2.3 (Chromium 91 and Firefox 86).

**Comment by ZwieBit** [comment] 2021-03-16 12:18
Nice! Didn't test that... for me exactly the same - html5 export without mono works as expected!

**Comment by neikeq** [comment] 2021-03-16 23:12
Did we change Mono or emsdk version between RC1 and RC2?

**Comment by Faless** [comment] 2021-03-16 23:33
@neikeq not that I remember, all the changes happened before RC1 (end December, early Jan). @akien-mga anything comes to mind?

**Comment by fenix-hub** [comment] 2021-03-20 19:50
I'm having this same issue trying to run a very simple project on RC6 (not mono version).
I'm trying to run a scene with a Control node and a custom node using a plugin of mine.
Here's what happens if exporting for HTML5 and using xampp
![2021-03-20_20-44](https://user-images.githubusercontent.com/45271396/111883727-6c13e700-89bd-11eb-885f-6f56968fd52f.png)

Here's using godot's server (the whole browser is completely stuck, cannot even open console)
![2021-03-20_20-37](https://user-images.githubusercontent.com/45271396/111883747-80f07a80-89bd-11eb-8d27-3936aee3f51a.png)

Could be unrelated, but the same issue happens on Android.
On windows and linux (only platforms I can test everything looks fine).

Here's the project if it could help reproduce this
[easycharts.zip](https://github.com/godotengine/godot/files/6176312/easycharts.zip)

Also here it is the already exported files for HTML5
[easycharts.zip](https://github.com/godotengine/godot/files/6176313/easycharts.zip)

**Comment by Faless** [comment] 2021-03-20 20:18
@fenix-hub see my comment above, server is not returning the right headers: https://github.com/godotengine/godot/issues/47048#issuecomment-800155862 and this PR #47191 .

**Comment by fenix-hub** [comment] 2021-03-20 22:47
@Faless Sorry, missed that message. Thanks :)

**Comment by ZwieBit** [comment] 2021-03-21 11:14
Damit, i'm so sorry. I just retested "GUI Theming Override" with different combinations, i think i made a mistake - Actually it works up until RC2. From RC3 on i get problem:

(internal server & nginx) RC3
![image](https://user-images.githubusercontent.com/25595246/111902571-66121a80-8a3e-11eb-9d0c-a36a107197b9.png)

Before it works with nginx and internal.

**Comment by ZwieBit** [comment] 2021-03-21 11:19
**RC4** 
internal server:
not responding / no message

nginx:
![image](https://user-images.githubusercontent.com/25595246/111902851-afaf3500-8a3f-11eb-8544-5bfa5ba35f41.png)

**Comment by Calinou** [comment] 2021-03-21 11:57
@ZwieBit You need to configure the web server to serve the file with the correct MIME type.

**Comment by ZwieBit** [comment] 2021-03-21 11:58
> @ZwieBit You need to configure the web server to serve the `.wasm` file with the correct MIME type. GitHub Pages and itch.io do this automatically, but some development web servers don't.

So why did this then actually work with RC1 and RC2?

**Comment by Faless** [comment] 2021-03-21 15:07
> So why did this then actually work with RC1 and RC2? I'll give it a try and research for the configuration.

Because it used the **slow** instantiation method that did not require the mime type. As mentioned above, I've made a workaround for it for future releases.

> I would say it's just a follow up error because of the "function signature mismatch".

This is a cache problem 90% of the time, so, always try clearing your cache when you get this error.

**Comment by akien-mga** [comment] 2021-03-25 12:11
Adding the error message in plain text as screenshots are not searchable:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```

**Comment by Faless** [comment] 2021-03-25 12:52
@akien-mga That issue is fixed by #47191 , The `function signature mismatch` is probably a cache issue.
I'm going to close this, but feel free to comment if you think the issue is still valid.

**Comment by ZwieBit** [comment] 2021-03-25 15:46
i know i'm a bit annoying ;-) So #47191 does also eliminate the problem with the internal server of godot, not only external ones?

**Comment by Faless** [comment] 2021-03-25 16:50
@ZwieBit what error are you getting when running the internal server in RC6?

**Comment by ZwieBit** [comment] 2021-03-25 17:10
> Damit, i'm so sorry. I just retested "GUI Theming Override" with different combinations, i think i made a mistake - Actually it works up until RC2. From RC3 on i get problem:
> 
> **RC3**
> (internal server & nginx)
> ![image](https://user-images.githubusercontent.com/25595246/111902571-66121a80-8a3e-11eb-9d0c-a36a107197b9.png)
>
> Before it works with nginx and internal.
On RC3 "function mismatch" - from RC4 onwards its simply not showing any output in edge, firefox, chromium - just not responding. I can reproduce it with every PC - just using godot-mono with a simple spatial and do a htlm5 export. I'll check this further....

**Comment by ZwieBit** [comment] 2021-03-25 17:11
> **RC4** **RC5** **RC6**
> internal server:
> not responding / no message
> 
> nginx:
> ![image](https://user-images.githubusercontent.com/25595246/111902851-afaf3500-8a3f-11eb-8544-5bfa5ba35f41.png)

On RC3 "function mismatch with wasm" - from RC4 onwards its simply not showing any output in edge, firefox, chromium - just not responding. I can reproduce it with every PC - just using godot-mono with a simple spatial and do a htlm5 export. I'll check this further....

**Comment by Faless** [comment] 2021-03-25 17:49
Mono build stalls during emscripten initialization. I can't seem to be able to get a proper trace, just:

```
Script terminated by timeout at:
Godot/Module.then@http://0.0.0.0:8060/tmp_js_export.js:9:422409
promise callback*doInit@http://0.0.0.0:8060/tmp_js_export.js:615:21
init@http://0.0.0.0:8060/tmp_js_export.js:631:19
startGame@http://0.0.0.0:8060/tmp_js_export.js:727:11
@http://0.0.0.0:8060/tmp_js_export.html:222:12
@http://0.0.0.0:8060/tmp_js_export.html:242:5
```

after force-stopping the script

**Comment by akien-mga** [comment] 2021-03-28 21:11
So to clarify (as @Faless and I spent some time looking at changes from RC 1 to RC 2...), the regression happened in 3.2.4 RC 3. So:
- Work fine: RC 1, RC 2
- Broken: RC 3 onward up to RC 6 (current latest)

We also confirmed that it's not related to changes in the build containers, as rebuilding RC 1 and RC 2 with the current containers also makes it work fine.

I initially suspected a regression from the Thread modernization changes in #45618 merged in RC 3, as I know it has caused other issues and Mono threads are somewhat touchy.

But after doing some test builds, it seems #45618 is not directly involved:
- Commit 418a08d6787f3bf2dd03e0a39c4f5a1dbf6ea1dd works OK. This is the parent commit of the #45618 merge commit (i.e. the last commit before the merge). Test build: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.2.4-rc-pre45618_mono_x11%2bjs.zip
- Commit 220f24c191149444dfd34d03d22d4e451dfcaa49 (i.e. #45618 merge commit) seems to work OK too. Test build: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.2.4-rc-post45618_mono_x11%2bjs.zip
Note: It crashes if you have a path to the Android SDK set in editor settings due to #46203 - removing it from the editor settings makes it possible to prevent the crash and test this build.

Note 2: Both builds have sound disabled as there were issues building the newly added alsa wrapper at these commits.

So here's the list of potential commits that introduced this regression: https://github.com/godotengine/godot/compare/220f24c191149444dfd34d03d22d4e451dfcaa49...4f891b706027dc800f6949bec413f448defdd20d

**Comment by akien-mga** [comment] 2021-03-28 22:46
Testing further, I found that 3.2.4 RC 3 is actually `good` (no regression). It's a bit tricky as 3.2.4 RC 3 was affected by another bug that broke the HTML5 export (#46352), but when rebuilding it with the relevant fix, there's no problem starting a Mono export.

I could confirm the Mono build stall in 3.2.4 RC 4 on the other hand.

So the problem actually happened between 3.2.4 RC 3 and 3.2.4 RC 4.

Relevant changes: https://github.com/godotengine/godot/compare/4f891b706027dc800f6949bec413f448defdd20d...dc99f04d51d6556e5ba4d9cfcce8117d168ac6f1

**Comment by Faless** [comment] 2021-03-29 07:01
8a020a6573109820f4326b085f1264daedb8ff98 is `good`

So, unless I made a mistake:
https://github.com/godotengine/godot/compare/8a020a6573109820f4326b085f1264daedb8ff98...82fcd3a7b8932908abc1c774979186c4adce861e

**Comment by akien-mga** [comment] 2021-03-29 07:01
Bisecting even further, this appears to be a regression from #46731 (merge commit 82fcd3a7b8932908abc1c774979186c4adce861e is `bad`, parent commit f477d3ca9851953ded5f0560081d726f5de9b534 is `good`).

**Closed** 2021-03-29 17:03 UTC
Labels: bug, platform:html5, regression, topic:mono, topic:porting
