### ISSUE TITLE
REMINDER: 3.0 BETA APPROACHING

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#12899] opened 2017-11-13 12:12 UTC
This is a reminder that 3.0 BETA is approaching. Your code must be merged before November 20 (a week from now) or it will have to wait for 3.1, as we will enter Feature Freeze!

![image](https://user-images.githubusercontent.com/6265307/32725188-e4c41f24-c852-11e7-92cd-0d2d1177cd58.png)

**Comment by NullConstant** [comment] 2017-11-13 12:17
Is this fancy logo going to be used *for* the beta or was that just done For Fun:tm:?

**Comment by reduz** [comment] 2017-11-13 12:22
@NullConstant It's just meant as a reminder image to focus on 3.0 beta :) Actual release will probably have something else.

**Comment by sersoong** [comment] 2017-11-13 14:43
Good!

**Comment by davidpgil** [comment] 2017-11-14 11:15
Glad I looked at this forum. I was JUST going to start porting my game to Godot 3 from 2.X. I guess the wait is almost over :)

**Comment by eon-s** [comment] 2017-11-15 08:36
Beta is going to need a full list of features and changes to make bug hunts easier, also to start with new demos.

**Comment by blurymind** [comment] 2017-11-16 13:13
alpha2 plugin system is broken. Godot fails to load custom nodes- is that a bug or a missing feature that will make a comeback?

**Comment by vnen** [comment] 2017-11-16 16:24
@blurymind I have no issues with custom nodes. Can you try with a more recent build? If there's a problem, open a new report.

**Comment by Zylann** [comment] 2017-11-17 23:27
Could this be fixed? How hard would it be? https://github.com/godotengine/godot/issues/11030
Fixing this would give a huge boost to the whole editor UX.

**Comment by yuyoDev** [comment] 2017-11-19 03:45
Regarding this topic #9561, 
The topic is closed, but the solution will be released until version 3.1
But I have seen that this problem the  "jitter-movement" in the motion demo is recurrent.
I also have the same problem(not only in motion-demo, that problem is in Godot 2.x and Godot3alpha), my suggestion is to add a function to get the refresh rate of the monitor, as suggested by @ghost
I think could be a nice solution for the Godot3.0 release until we wait for the Godot3.1 when is planned the  fixed frame interpolation @reduz. Please consider it!

**Comment by Calinou** [comment] 2017-11-19 17:20
> my suggestion is to add a function to get the refresh rate of the monitor

Not only this does not really solve the problem, but this also will cause differences in behavior between different monitor Hz (which should never impact how a game's physics and simulation runs).

**Comment by LikeLakers2** [comment] 2017-11-20 01:07
We seem to be 91% through the 3.0 milestone. Is this a bug? Should I let Github know? Or should I let reduz bask in the numbers being higher than they should be?

~~...You know SOMEONE had to do it.~~

**Comment by Zylann** [comment] 2017-11-20 01:31
@LikeLakers2
![image](https://user-images.githubusercontent.com/1311555/32998396-f7c8fd68-cd9a-11e7-9f4d-83d8031649e3.png)

**Comment by sersoong** [comment] 2017-11-20 14:11
Yeah,today is November 20.
Can you release beta today?
We are looking faward to it.

**Comment by akien-mga** [comment] 2017-11-20 14:22
The beta build will be released when it's ready, no ETA. Nov 20 is only the date for the feature freeze.

**Comment by sersoong** [comment] 2017-11-20 14:32
Oh, all right

**Comment by Redwan13** [comment] 2017-11-20 18:01
>The beta build will be released when it's ready, no ETA. Nov 20 is only the date for the feature freeze.

So, did feature freeze officially happen?

**Comment by blurymind** [comment] 2017-11-20 18:32
He just said that feature freeze will be november 20th

**Comment by CereEnder** [comment] 2017-11-20 18:36
What does "feature freeze" mean exactly?

**Comment by Sslaxx** [comment] 2017-11-20 18:41
No new features will be added. So nothing like Mono support, GDNative or VR/AR. Focus will be on fixing bugs.

**Comment by mrezai** [comment] 2017-11-20 19:14
@reduz @akien-mga @bruvzg : I think PR #10546 (bidi and text shaping support) can be considered for merge because it is implemented as a separate Control without any modification in other UI nodes.
Maybe even we can have something like "Qt Technology Previews" for some incomplete features.

**Comment by HummusSamurai** [comment] 2017-11-22 09:48
This is very important to fix because it causes broken scenes that are tricky to fix https://github.com/godotengine/godot/issues/13172

Most users will give up.

**Comment by akien-mga** [comment] 2017-11-30 15:20
Fixed :) https://godotengine.org/article/dev-snapshot-godot-3-0-beta-1

**Closed by akien-mga** 2017-11-30 15:20 UTC
Labels: discussion

**Comment by neikeq** [comment] 2017-11-30 16:00
I can still reproduce this.

**Comment by bojidar-bg** [comment] 2017-11-30 16:33
Update to latest `master` and try again.
