### ISSUE TITLE
Shadows cast by directional light disappear when viewed from a particular angle

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#91288] opened 2024-04-28 22:03 UTC
### Tested versions

- Reproducible in: v4.3.dev5.official [89f70e98d], v4.3.dev3.official [36e943b6b]
- Not reproducible in: v4.3.dev2.official [352434668]

### System information

Godot v4.3.dev5 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5123) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Under very specific conditions, shadows cast by a directional light disappear.

https://github.com/godotengine/godot/assets/5222656/49215984-9fe3-4fdc-89a7-e041431a5f1e

### Steps to reproduce

1) Open MRP.
2) Run.
3) Press Q to rotate camera to left, and E to rotate camera to right. Rotation must end before next input will be accepted.

Reasonably consistently, when the camera is moved one rotation step to the left of the initial position, the shadows cast in the scene will disappear.  Sometimes you need to press Q then E then Q again.

### Minimal reproduction project (MRP)

[perpendicular_shadow.zip](https://github.com/godotengine/godot/files/15144009/perpendicular_shadow.zip)

**Comment by krdluzni** [comment] 2024-05-13 16:14
Suspect https://github.com/godotengine/godot/pull/91790 was relevant to this. Testing the MRP on a master branch build from after that pull request was merged (v4.3.dev.gh [de196227e]), the issue is no longer apparent.

**Comment by clayjohn** [comment] 2024-05-13 16:21
Yes, good eye. I suspect this is a duplicate of https://github.com/godotengine/godot/issues/89560 and will be fixed by https://github.com/godotengine/godot/pull/91790

**Closed** 2024-05-16 20:35 UTC
Labels: bug, topic:rendering, topic:3d
