### ISSUE TITLE
Animations stutter when reaching 0.5 on the Animation Player component.

### ISSUE THREAD

**Issue by fossyman** [godotengine/godot#93035] opened 2024-06-11 14:38 UTC
### Tested versions

Reproducible in Godot version 4.2.2 mono.

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Mobile) - dedicated AMD Radeon RX 6750 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

When playing animations in the editor, they all stutter around the 0.5 second mark. This happens every time I press play to see the animation. The animation doesn't stutter after the first play if it is set to loop automatically.

This also doesn't happen while in the game as the animations play smoothly.

### Steps to reproduce

Import an animation and play it. Make sure the animation is over 0.5 seconds long.
Play the animation by pressing play, make sure looping is disabled.

### Minimal reproduction project (MRP)

[Animation Player issue MRP.zip](https://github.com/user-attachments/files/15789610/Animation.Player.issue.MRP.zip)

**Comment by TokageItLab** [comment] 2024-06-17 15:40
Should be duplicate of https://github.com/godotengine/godot/issues/85409.

**Closed by TokageItLab** 2024-06-17 15:40 UTC
Labels: archived, topic:animation
