### ISSUE TITLE
Exported integer script variables inaccurate for large integers

### ISSUE THREAD

**Issue by stshort** [godotengine/godot#52483] opened 2021-09-08 03:42 UTC
### Godot version

Godot_v3.3.3-stable_x11.64

### System information

Ubuntu 20.04.3 LTS

### Issue description

Not sure if this bug has been reported, but I couldn't find it in the issue list, so here's an issue I am running into -

When you export int variables like this:
```
export (int) var rng_seed
export (int) var rng_state
```

Then you assign the variable a large positive or negative integer, the integer will be inaccurate - it will automatically change state within the editor and set that as the variable.

It seems as though it may be using floating point precision somewhere when reading int values? I'm not too sure myself but it definitely feels like something similar to that is possible.

### Steps to reproduce

See the attached reproduction project and it'll be clear that it's not working as intended.

1. Create a project & scene with a node that has a script attached.
2. Export some large int variable, such as:
```
export (int) var rng_seed
export (int) var rng_state
```
3. Set either variable in the sidebar of the editor to a large positive or negative integer value. Notice that it changes after you save it.

For example, I am trying to store seed and state for my application to replicate something that is procedurally generated. However, when I am setting the values in the editor for my exported variables, this inaccuracy is causing this to fail, rendering me unable to generate specific seed+state combinations without hardcoding it into the script, or reading it from an external file.

For example, I attempted to set RNG Seed to `-7994387562401631103`, which the editor will automatically change to `-7994387562401631232` after I set it.

See the screenshots, before I tab off of the setting and after:
Before tabbing:
![Screenshot from 2021-09-07 20-38-38](https://user-images.githubusercontent.com/2568436/132442696-1291389a-d3a2-440a-8d08-f1e7f6e82719.png)

After tabbing (editor changed the value):
![Screenshot from 2021-09-07 20-38-46](https://user-images.githubusercontent.com/2568436/132442729-8deb2733-3c05-48e0-a12e-6fcfeb41def9.png)

### Minimal reproduction project

[godot-integer-issue.zip](https://github.com/godotengine/godot/files/7125634/godot-integer-issue.zip)

**Comment by stshort** [comment] 2021-09-08 04:28
Complete shot in the dark but perhaps the issue is here -> https://github.com/godotengine/godot/blob/0d5e13cd805a1aa69c5f395483051d3501bcfcd3/editor/property_editor.cpp#L504

Maybe `String::num` is inaccurate for large ints, but maybe not. Thought I'd take a stab looking through the source to try and figure out what might be causing it.

**Comment by pycbouh** [comment] 2021-09-08 10:05
Duplicate of https://github.com/godotengine/godot/issues/33095

**Closed by pycbouh** 2021-09-08 10:05 UTC
