### ISSUE TITLE
On project upgrade from 3.5 to 4.0 beta, Raycast2D nodes `cast_to` does not convert to `target_position`

### ISSUE THREAD

**Issue by Giometric** [godotengine/godot#66581] opened 2022-09-29 05:48 UTC
### Godot version

4.0 beta

### System information

macOS Monterey 12.6

### Issue description

Upgraded a small project from Godot 3.5 to 4.0 beta, using the automatic full upgrade. Once upgraded, Raycast2D nodes in one of my scenes had their target positions set to junk default values.

It appears that the property was renamed from `cast_to` in 3.5, to `target_position` in 4.0, and the upgrader did not convert the values. Copying the exact values as they were in 3.5 to `target_position` got them back to the way they were intended.

### Steps to reproduce

1. Create project in Godot 3.5
2. Create scene file which contains a Raycast2D node
3. Set `cast_to` property on Recast2D node to any non-default value
4. Upgrade project to 4.0 beta using full upgrader
5. Check value of target_position (in my case set to [0, 50] which appears to be a default?)

**Comment by gotnospirit** [comment] 2022-09-29 06:24
Duplicate of #65999

**Closed** 2022-09-29 06:30 UTC
