### ISSUE TITLE
Project data loss when quitting to project manager with a debugger error

### ISSUE THREAD

**Issue by jakubg1** [godotengine/godot#24774] opened 2019-01-04 22:38 UTC
I've tried searching "project data loss" when checking duplicates, and haven't found a similiar issue, so...

**Godot version:**
3.0.6 stable 64-bit

**OS/device including version:**
Windows 10

**Issue description:**
If the running project meets an error and shows the debugger (for example: "Division By Zero in operator "/""), and we will exit to project manager, all projects that were remembered there will be lost.

**Steps to reproduce:**
1. Open and run any project.
2. Produce an error that will make the project interrupt. It can be basically anything, wrong indexing, division by zero, etc.
3. Don't stop the ran project and quit to Project Manager.
4. You'll see a window saying you don't have any project in the list.

My solution idea is to forbid doing things like quitting to Project Manager when the project is running.

**Minimal reproduction project:**
I think it's fairly easy to reproduce that there's no one needed.

I hope I didn't make any serious mistakes when submitting this issue :)

**Comment by Naryosha** [comment] 2019-01-05 07:33
Cannot reproduce on Manjaro x86_64, Godot 3.0.6 stable
The halted project and the editor closed as expected. Project manager launched as expected. Project list still contains projects.
Tested with `breakpoint` keyword and 'Identifier not found error'

**Comment by jakubg1** [comment] 2019-01-08 20:47
I've tested the bug occurence again and the bug magically disappeared when trying to record it. It could be just a random data error.

**Comment by akien-mga** [comment] 2020-06-20 21:20
Couldn't reproduce either, so closing as there's no way to fix it. If anyone finds how to trigger the issue reliably, please comment and we can reopen it.

**Closed by akien-mga** 2020-06-20 21:20 UTC
Labels: bug, topic:editor
