### ISSUE TITLE
C# Async Await Whileloop in HTML not working

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#39170] opened 2020-05-30 13:16 UTC
**Godot version:**

Godot_v3.2.2-beta3_mono_x11_64

**OS/device including version:**

OS: 5.6.15-arch1-1
Mono JIT compiler version: 6.4.0
msbuild: 16.5.0-ci
Firefox: 76.0.1 (64-bit)

**Issue description:**

![Peek 2020-05-30 15-04](https://user-images.githubusercontent.com/60042618/83329150-1896a800-a288-11ea-92d8-28af7143490c.gif)

The Game stops responding on HTML. 

**Minimal reproduction project:**

```
using Godot;
using System;
using System.Threading.Tasks;

public class MainScene : Control
{
    private Label label;
    private Button button;
    private Random random = new Random();

    public override void _Ready()
    {
        label = GetNode<Label>("Label");
        button = GetNode<Button>("Button");
    }

    private void OnButtonPressed()
    {
        GenerateNumber();
    }

    private async void GenerateNumber()
    {
        int i = 0;
        label.Text = null;
        button.Disabled = true;

        while (i < 5)
        {
            i = random.Next(6);
            String text = (label.Text + i.ToString() + ", ");
            label.Text = text;
            await Task.Delay(300);
        }

        button.Disabled = false;
    }
}
```

**Comment by Calinou** [comment] 2020-05-30 13:19
Duplicate of https://github.com/godotengine/godot/issues/34506?

**Comment by hedi-sel** [comment] 2020-10-25 13:22
@JupiterRider I tried running your example, and I crashed as soon as the System.Threading.Tasks library was mentionned. (On the gif you shared, the browser lasted long enough to show the first integer)

Out of curiosity, may I ask for the output of your web console?

**Comment by Calinou** [comment] 2020-11-21 15:01
Duplicate of https://github.com/godotengine/godot/issues/34506.

**Closed by Calinou** 2020-11-21 15:01 UTC
Labels: documentation, platform:html5, topic:mono
