### ISSUE TITLE
[3.2.4 beta 4] new pixel snap jitters with odd sized sprites

### ISSUE THREAD

**Issue by PapaCheese** [godotengine/godot#44686] opened 2020-12-25 15:25 UTC
**Godot version:**
3.2.4 beta 4

**OS/device including version:**
windows 10, geforce 1080

**Issue description:**
the new pixel snap jitters with odd numbered sized sprites (ex. 31x31) with a smooth camera

3.2.3 stable:

https://user-images.githubusercontent.com/55656526/103137899-e80bd500-46d5-11eb-94d7-9284c285c842.mp4

3.2.4 beta 4 (only 64x64 and 32x32 works properly)

https://user-images.githubusercontent.com/55656526/103137902-f0641000-46d5-11eb-8000-2a35e7510cc1.mp4

**Steps to reproduce:**
(3.2.4 beta 4) new project, enable pixel snap, stretch mode to viewport, add pixel art sprite with odd size (filter off), add smooth camera and move it in game.

side notes: 
i added pixel perfect script to the main scene.
the new 'transform snap' does not solve my issue.

**Minimal reproduction project:**
[pixel snap jitter Minimal reproduction project.zip](https://github.com/godotengine/godot/files/5742132/pixel.snap.jitter.Minimal.reproduction.project.zip)

**Comment by lawnjelly** [comment] 2020-12-25 16:56
I just tested and it seems to be the extra changes in #43554 (not the m6502 change).

Following on from reduz PR #43194, some more of the snapping is now controlled by the transform snapping project setting, rather than the pixel snapping project setting. I'm not quite sure on the reasoning for this (as this is just a straight backport of his, aside from the canvas (camera) snapping).

We could consider keeping control of these with the pixel snap option in 3.2, to keep compatibility. Or have another option to control this snapping, but it would be better to avoid too many settings to prevent things becoming overcomplicated. Hopefully I can find out from reduz the reasoning for moving these settings and the best compromise.

**Comment by PapaCheese** [comment] 2020-12-25 17:13
with 'transform snap' on, walking with my character at a certain speed makes its head jitter (not visible in video)

**Comment by lawnjelly** [comment] 2020-12-25 17:19
> with 'transform snap' on, walking with my character at a certain speed makes its head jitter (not visible in video)

Ah this may be because of the camera not being snapped. I will look again at this.

The problem is that currently snapping the camera in reduz method causes another bug to exhibit, which results in a subtle jitter. This can be prevented by doing the camera snapping manually. But this may be too much for many users to understand. Maybe just forcing the camera snap will get someone interested to fix the other bug.

**Comment by akien-mga** [comment] 2021-01-05 16:19
Fixed by #44690.

**Closed by akien-mga** 2021-01-05 16:19 UTC
Labels: bug, regression, topic:core
