### ISSUE TITLE
[3.6] Audio category in Project Settings shows as collapsible section

### ISSUE THREAD

**Issue by Kleadron** [godotengine/godot#98326] opened 2024-10-18 23:05 UTC
### Tested versions

- Reproducible in 3.6.stable
- Not reproducible in: 3.5.3.stable

### System information

Windows 10, Godot 3.6

### Issue description

In the Project Settings of the Godot Editor starting from 3.6, the Audio category now shows up as collapsible, with a "General" tab underneath it containing the backported audio settings from 4.x. 
In 3.5.x, the Audio category was a standalone entry.

This led me to think the audio settings in Godot 3.6 were straight up removed, because I'd click the General button expecting the audio settings to be there instead.

You have to click the name of the collapsible category to access the Audio settings now. No other category in the Project Settings behaves like this.

Audio category in Godot 3.5:
![image](https://github.com/user-attachments/assets/472a9fa7-6ef1-4fd6-bf84-5f065d5a78d5)

Audio category in Godot 3.6:
![image](https://github.com/user-attachments/assets/fe35d650-b542-4c0b-a93b-f0c79ee11e4a)
Note that the header does not completely light up when selected, and you can click the general tab thinking you've opened the actual audio settings. The general tab contains TTS and iOS related settings.
![image](https://github.com/user-attachments/assets/ff47c35e-4401-4717-80ac-b9ff14329168)

### Steps to reproduce

Open the Project Settings in Godot 3.6 after loading any project (even a blank one) and look for the Audio category.

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment] 2024-10-19 05:37
Duplicate of #96883 ?

**Comment by lawnjelly** [comment] 2024-10-19 05:39
Closing as duplicate, better to discuss on original issue.

**Closed by lawnjelly** 2024-10-19 05:39 UTC
Labels: topic:editor, usability

**Comment by Kleadron** [comment] 2024-10-20 00:18
I didn't realize there was an existing issue. Sorry!

**Comment by lawnjelly** [comment] 2024-10-20 05:29
> I didn't realize there was an existing issue. Sorry!

No worries, sometimes it's difficult to find the duplicates and it's far better to risk a duplicate than not creating an issue if you aren't sure. :+1:
