### ISSUE TITLE
InputMap.get_action_list() doesn't return Joypad buttons when called in the editor

### ISSUE THREAD

**Issue by FringeSci-com** [godotengine/godot#54950] opened 2021-11-13 16:09 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

When you call InputMap.get_action_list() in a tool script in the editor, it _only_ returns keyboard buttons. Joypad buttons, axes, mouse buttons, and physical keyboard buttons don't show up. This _only_ happens in the editor, when _running_ the game it returns all the different types of controls as you'd expect.

I've tested this in 3.4 and 3.2.3 and they both have the same behavior.

(This has put a slight damper on my button prompt node that grabs button graphics based off of your Input Map. 😢)

### Steps to reproduce

Create a Node2D with the following script:
```GDScript
tool
extends Node2D

func _init():
	print(InputMap.get_action_list("ui_accept"))
```
In the editor it will print:
```[[InputEventKey:60], [InputEventKey:61], [InputEventKey:62]]```
(The numbers might be different for you)

If you play the project it will print:
```[[InputEventKey:20], [InputEventKey:21], [InputEventKey:22], [InputEventJoypadButton:23]]```

Notice when running in the editor it's missing the InputEventJoypadButton, but when playing the project it outputs all the buttons as expected.

If you add Joypad Axes, Mouse Buttons, or Physical Keyboard Buttons to ui_accept, you'll find that they're also missing in the editor as well.

**Comment by Calinou** [comment] 2021-11-13 16:18
From a quick look in `3.x`'s [`core/input_map.cpp`](https://github.com/godotengine/godot/blob/a79e4d0ae5707f954f6422672cc9279f8165d91b/core/input_map.cpp), I can't see why non-key events would be specifically excluded.

**Comment by KoBeWi** [comment] 2021-11-13 20:59
Could be because in editor it uses editor actions (default) and at runtime it uses the input map from project settings?

**Comment by FringeSci-com** [comment] 2021-11-14 04:19
> 
> 
> Could be because in editor it uses editor actions (default) and at runtime it uses the input map from project settings?

You might be on to something. Just tested this on a custom action and not one of the built-ins and it didn't show anything in the editor at all.

**Comment by akien-mga** [comment] 2021-11-15 07:59
I can't find where this would be implemented, but I think the editor ignores joypad input on purpose, due to #16832.

**Comment by madmiraal** [comment] 2021-12-28 12:34
This is by design. Godot engine is a game; so it has its own, fixed InputMap which is loaded and used by the editor and the project manager:
https://github.com/godotengine/godot/blob/28174d531b7128f0281fc2b88da2f4962fd3513e/main/main.cpp#L1257-L1263
When you call `InputMap.get_action_list("ui_accept")` (or `InputMap.action_get_events("ui_accept")` in 4.0) within the editor you get the editor's `InputMap`, which is limited to the those key mappings.
To get the project's `InputMap`'s `Action`'s events, you need to use `ProjectSettings.get_setting("input/ui_accept").events`.

**Comment by Zireael07** [comment] 2021-12-28 12:36
@madmiraal Is this documented anywhere?

**Comment by madmiraal** [comment] 2021-12-28 14:32
> Is this documented anywhere?

Not that I know of.

**Closed** 2022-05-04 07:03 UTC
Labels: topic:editor, documentation, topic:input
