### ISSUE TITLE
Interface glitch in background mode for WorldEnvironment

### ISSUE THREAD

**Issue by KaruroChori** [godotengine/godot#44254] opened 2020-12-10 07:06 UTC
**Godot version:**
Godot 4.0 bc30df8

**OS/device including version:**

Linux 80x86 64bit, GTX 1660 super and RTX 2060 (main one). Drivers 450.80

**Issue description:**
I am working in single window mode.
When setting the background mode for a WorldEnvironment node, canvas would result in what is shown in the attached figures.

**Steps to reproduce:**
Open the project and change the mode of the WorldEnvironment node.

**Minimal reproduction project:**
Attached
![Screenshot from 2020-12-10 07-00-05](https://user-images.githubusercontent.com/9377545/101733013-078be680-3ab6-11eb-9b37-592e6e9c4437.png)
![Screenshot from 2020-12-10 07-00-11](https://user-images.githubusercontent.com/9377545/101733014-08247d00-3ab6-11eb-8a4d-1c00790dd20b.png)
[test-godot-4.zip](https://github.com/godotengine/godot/files/5670840/test-godot-4.zip)

**Comment by Calinou** [comment] 2020-12-10 10:03
**OS:** Fedora 33 (KDE + KWin)
**GPU:** GeForce GTX 1080 (NVIDIA 455.45.01)

I can reproduce this on commit 90bdba576, albeit it looks different:

![image](https://user-images.githubusercontent.com/180032/101757244-336b9400-3ad7-11eb-9521-83513f8c786b.png)

It's worth nothing that I can't reproduce this on a brand new project though.

**Comment by Calinou** [comment] 2022-05-14 18:08
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-05-14 18:08 UTC
Labels: bug, archived, topic:rendering, regression, topic:gui, topic:2d
