### ISSUE TITLE
shape_find_owner: Index p_shape_index = 1 is out of bounds

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#38893] opened 2020-05-20 16:17 UTC
**Godot version:**
3.2.1.stable.mono
**OS/device including version:**
Debian 10
**Issue description:**
I use multiple collisions shape in a Area2D node with no problems
But if I try to check the owner using `ShapeOwnerGetOwner(ShapeFindOwner(selfShape))`
I have this error:
```
E 0:00:01.232   shape_find_owner: Index p_shape_index = 1 is out of bounds (total_subshapes = 1).
  <C++ Source>  scene/2d/collision_object_2d.cpp:316 @ shape_find_owner()
  <Stack Trace> :0 @ UInt32 Godot.NativeCalls.godot_icall_1_153(IntPtr , IntPtr , Int32 )()
                CollisionObject2D.cs:305 @ UInt32 Godot.CollisionObject2D.ShapeFindOwner(Int32 )()
                Node2D.cs:26 @ void Node2D._on_Area2D_area_shape_entered(Int32 , Area2D , Int32 , Int32 )()

```
**Steps to reproduce:**
run the project attached
**Minimal reproduction project:**
[Basic.zip](https://github.com/godotengine/godot/files/4658050/Basic.zip)

**Comment by nisovin** [comment] 2020-05-21 06:22
You're using the shape index of the entering area (which has multiple shapes) with the entered area (which only has one). The error is actually happening on the next line. You would need to use `area.ShapeOwnerGetOwner(area.ShapeFindOwner(areaShape))`

**Comment by git2013vb** [comment] 2020-05-21 09:32
Thank you @nisovin  :) I tried with `areaShape` and its ok. But I still have the error when I try to apply your instructions  using `selfShape`:
Ps.: my issue was with `selfShape` =)
```
E 0:00:01.248   shape_find_owner: Index p_shape_index = 1 is out of bounds (total_subshapes = 1).
  <C++ Source>  scene/2d/collision_object_2d.cpp:316 @ shape_find_owner()
  <Stack Trace> :0 @ UInt32 Godot.NativeCalls.godot_icall_1_153(IntPtr , IntPtr , Int32 )()
                CollisionObject2D.cs:305 @ UInt32 Godot.CollisionObject2D.ShapeFindOwner(Int32 )()
                Peer.cs:282 @ void Peer.LogDetection(Int32 , Godot.Area2D , Int32 , Int32 )()
                Peer.cs:309 @ void Peer._on_DetectionsRadius_area_shape_entered(Int32 , Godot.Area2D , Int32 , Int32 )()

```

**Comment by nisovin** [comment] 2020-05-21 18:05
That looks like entirely different code. Are you sure you're using the right shape index with the right collision object?

**Comment by git2013vb** [comment] 2020-05-22 16:43
Sure, the last snippet came from my real project not from the sample I posted here

**Comment by madmiraal** [comment] 2020-05-26 16:48
I agree with @nisovin, based on the minimal reproduction provided, the error is occurring with `areaShape` not with `selfShape`.

**Comment by madmiraal** [comment] 2020-06-01 10:26
Closing as the issue lies with the user's code not with Godot.

**Closed by madmiraal** 2020-06-01 10:26 UTC

**Comment by git2013vb** [comment] 2020-06-04 10:50
Close is more fast that fix I see :) Personally  I prefer to fix instead. Sad that I don't have enough experience in Godot code and I'm forced to write issue here.
Thank you anyway.

**Comment by Zireael07** [comment] 2020-06-04 11:13
Problem is not with Godot code, problem is with your script.
If you can't write a correct script, head to Godot forums, this is not the place for Q&A.

**Comment by git2013vb** [comment] 2020-06-04 17:26
I opened this tread for something I believe is a bug. I gave a minimal reproduction project + other explanations about the issue and that's it. Who ever talked about Q&A? 
Anyway this is a closed tread. Pointless to argue here about ,I guess, English language.
Thank you.
