### ISSUE TITLE
Remembering the the last opened scenes/scripts tabs before closing godot fo each project

### ISSUE THREAD

**Issue by ticnew** [godotengine/godot#8600] opened 2017-05-01 00:43 UTC
I wonder if it's gonna be useful if all your opened tabs (scenes/scripts) stay right there as you left them last time before you close your project, without start looking to open them each time instead of open the main scene only ?

**Comment by vnen** [comment] 2017-05-01 00:51
Duplicate of #2385 (and #3333).

**Closed by vnen** 2017-05-01 00:51 UTC
