### ISSUE TITLE
Crackly set_bus_volume_db if adjusted in real-time

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#48678] opened 2021-05-12 22:07 UTC
I did not find any duplicate issues.

**Godot version:**
3.3 stable, but should affect every 3.x version as I've this issue the whole time issues.

**OS/device including version:**
Using the GLES2 renderer, a Geforce GTX 750 Ti & Linux Mint 19.2
I doubt it's graphics related, however. It may be a Linux exclusive issue as far as I'm aware.

**Issue description:**
I had my program adjust the volume during run-time of a bus. It would either be delayed in changing the volume by a very noticeable amount or have a loud crackle as it tried to change it. To get around this I adjust the player's volume in real-time instead which causes no such issues.

**Steps to reproduce:**
Use set_bus_volume_db on a bus in real time. Have the volume go up and down while playing some music and you should also experience the issue.

**Minimal reproduction project:**
I will make one later to demonstrate the issue clearly, just cataloguing the issue from my own game.

**Comment by Calinou** [comment] 2021-05-12 23:43
Duplicate of https://github.com/godotengine/godot/issues/32882.

**Closed by Calinou** 2021-05-12 23:43 UTC

**Comment by agameraaron** [comment] 2021-05-13 01:24
I am sorry I did not find that existing issue.
I searched for "set_bus_volume_db" expecting it to catch this, but I'm learning now that it did not search the actual issues' thread contents or I searched wrong. I will remember this and be more thorough with my searching.

**Comment by Calinou** [comment] 2021-05-13 14:49
> but I'm learning now that it did not search the actual issues' thread contents or I searched wrong. 

GitHub's search *does* search in issue contents, but it may fail on words that aren't whole words (otherwise, there would be too many false positives).
