### ISSUE TITLE
Project Manager accidentally opening

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32435] opened 2019-09-30 03:36 UTC
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10 18362

**Issue description:** Project Manager accidentally opening when you run the scene, closes and run it again almost instantly. You can even see the project manager scene in the scene dock.

**Steps to reproduce:** Run the scene, close it and run again immediately

**Minimal reproduction project:**

![Print](https://user-images.githubusercontent.com/37383316/65842092-58734d00-e2ff-11e9-92a5-b8f1f2069fcc.jpg)

**Comment by Chaosus** [comment] 2019-09-30 09:09
Duplicate of #28036

**Closed by Chaosus** 2019-09-30 09:09 UTC
