### ISSUE TITLE
Path 2D doesn't render correctly with batching on

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#38014] opened 2020-04-19 16:04 UTC
**Godot version:**
3.2.2 beta 1

**OS/device including version:**
MXLinux19 64 bits
Ironlake Mobile

**Issue description:**
Path2D Only seems to render correctly when it's alone, other nodes make it look like this

![image](https://user-images.githubusercontent.com/18746022/79692885-a9b04300-8235-11ea-8c84-451e6633f3ba.png)

it stays on that part of the screen, even if the editor is resized it stays there.
**Steps to reproduce:**
Use a Path2D along some sprites.
Edit: the other node must have a z index greater than z index of the path.

**Comment by lawnjelly** [comment] 2020-04-19 16:43
Is it possible to have a minimum reproduction project?

**Comment by MightyPrinny** [comment] 2020-04-19 17:02
@lawnjelly I missed a detail, I didn't notice it only happens if the other node has a z index greater than the z index of the path, I tried on a sprite and a collision shape in a scene with only the path and another node and I was able to reproduce it.

**Comment by clayjohn** [comment] 2020-04-19 17:06
@MightyPrinny Please upload an MRP still. I am unable to reproduce the issue by following your instructions.

**Comment by MightyPrinny** [comment] 2020-04-19 17:13
[PathBug.zip](https://github.com/godotengine/godot/files/4499777/PathBug.zip)
Maybe doesn't happen on all gpus

**Comment by lawnjelly** [comment] 2020-04-19 17:23
It is now showing for me with your project in the IDE, if I set flash_batching to true. There is definitely something going wrong, I'm hoping it will not be too hard to fix once it's properly tracked down. :+1: 

It is probably the same bug as #38013 (but am not sure yet).

**Comment by lawnjelly** [comment] 2020-04-19 17:31
Nearly pinned this down. If you set max_join_items to 0 in the `rendering/gles2` section of project settings it fixed it for me, see if you can confirm. (This will prevent some of the benefits, but if it works it will prevent this bug if you are getting it till the next version)

It may be that the logic that decides whether to join items may not be checking something that needs to be checked in order to prevent a join, I'll see if I can find cure it.

**Comment by akien-mga** [comment] 2020-04-20 08:49
Fixed by #38019.

**Closed by akien-mga** 2020-04-20 08:49 UTC
Labels: bug, regression, topic:rendering
