### ISSUE TITLE
[Editor] code editor doesn't let me scroll to the bottom of the script

### ISSUE THREAD

**Issue by kvonspiczak** [godotengine/godot#23154] opened 2018-10-19 17:17 UTC
**Godot version:**
v3.1.alpha.mono.official

**OS/device including version:**
Win10 64 bit

**Issue description:**
I just noticed that I could not scroll to the end of the script. Keep scrolling and the editor will stop 1 line before the end.
The only way I can get to the very bottom of the script, is by holding left click and dragging the scroll bar to the bottom. Not a big thing, could not find an existing issue.

**Steps to reproduce:**
[gif showcasing the issue](https://cdn.discordapp.com/attachments/212250894228652034/502886383371681802/godot_bug.gif)

**Comment by kvonspiczak** [comment] 2018-10-19 17:56
Thank you @Mr-Slurpy !

**Comment by groud** [comment] 2018-10-19 18:45
Duplicate of #22744, which is now fixed on master.

**Closed by groud** 2018-10-19 18:45 UTC
