### ISSUE TITLE
Godot html5 game - collision bug (Chrome)

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#19910] opened 2018-07-02 10:00 UTC
**Godot version:**

**OS/device including version:**
win10 x64, Chrome 67.0.3396.99 （32 bit）, GTX 760

**Issue description:**
see this video
https://youtu.be/UFHBEHUAXQ0
game: https://dalton5000.itch.io/blazing-rails
not only this game...

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment] 2018-07-03 08:56
Looks similar to #19304.

**Comment by eska014** [comment] 2018-07-03 12:15
Duplicate of #16281

**Closed by eska014** 2018-07-03 12:15 UTC
Labels: bug, platform:html5, topic:porting
