### ISSUE TITLE
Skeleton animation goes wrong when opening multiple scenes that have the same instance.

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#41001] opened 2020-08-03 14:54 UTC
**Godot version:**

3.2.3.rc 5a766ce949 with #40313

**OS/device including version:**

OpenGL ES 2.0 Renderer: Radeon RX 570 Series (POLARIS10, DRM 3.35.0, 5.4.0-42-generic, LLVM 10.0.0)
OpenGL ES 2.0 Batching: ON

**Issue description:**

Skeleton animation goes wrong when opening multiple scenes that have the same instance.
![skeleton_multiple_open](https://user-images.githubusercontent.com/8281454/89194832-dae53100-d5e2-11ea-999b-d883a2c4fa6c.gif)
enabling `Force software skinning` at project settings fixes this issue.

**Steps to reproduce:**
1. open attached project
2. open `Spatial2.tscn`
3. switch scene between them

**Minimal reproduction project:**

[skeleton mesh test.zip](https://github.com/godotengine/godot/files/5016637/skeleton.mesh.test.zip)

**Comment by pouleyKetchoupp** [comment] 2020-08-15 12:40
Thanks for the detailed repro!

Since this issue is a regression caused by the changes in #40313 which is not merged yet, I would rather close this ticket and solve it as part of #40313.

**Closed by pouleyKetchoupp** 2020-08-15 12:40 UTC
Labels: bug, topic:core
