### ISSUE TITLE
Visual bugs with EditorHelpBit

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#37676] opened 2020-04-07 20:56 UTC
**Godot version:**
b2f79cac9a4b69a24ccf5f2bfeaeb5b38b7db369

**Issue description:**
- Font size is incorrect.
- Text cuts off (likely due to the previous point).
- Bold and underline text is not set properly.

**Comment by akien-mga** [comment] 2020-07-03 23:18
Duplicate of #39235.

**Closed by akien-mga** 2020-07-03 23:18 UTC
Labels: bug, regression, topic:editor
