### ISSUE TITLE
[FP] Indicate if a project is missing rather than deleting it from the project list

### ISSUE THREAD

**Issue by iownall555** [godotengine/godot#8792] opened 2017-05-17 00:40 UTC
I've noticed that Godot automatically removes unavailable projects from the project list. While this makes sense for deleted projects, it can be a bit of a pain if they are residing on removable media, mounted sshfs/sftp connections, network shares etc. which were not mounted at the time Godot was opened.

What I am thinking could happen is on every run Godot should check to see if the project is not there and then mark it as missing in the GUI and display a message when the user attempts to run or edit the project. (e.g `The project at <project path> is currently unavailable or unreadable. Check the path and try again.`)

Additionally the message could give the user the option of removing the project from the list should they desire to.

**Comment by bojidar-bg** [comment] 2017-05-17 10:36
Duplicate of #3866.

**Closed by bojidar-bg** 2017-05-17 10:36 UTC

**Comment by iownall555** [comment] 2017-05-17 13:44
Ahh blast. I guess my searching sucks then. Glad to know someone else has the same idea. Cheers.
