### ISSUE TITLE
GDScript vs C# performance

### ISSUE THREAD

**Issue by dragmz** [godotengine/godot#36060] opened 2020-02-09 20:55 UTC
Godot export templates:
https://downloads.tuxfamily.org/godotengine/3.2/mono/Godot_v3.2-stable_mono_export_templates.tpz

Projects:

* GDScript (gdlife) - https://github.com/dragmz/gdlife/tree/759ce2053569e5ebcc8e80ffa9087be005090979
* C# (gdlifenet) - https://github.com/dragmz/gdlifenet/tree/d3d379a32d237a0553c040ca518f7a361e5d9621

GDScript takes 10x longer than C# to execute. Results for rendering the first 1000 frames are (in milliseconds):

Intel Core i5 650 @ 3210 MHz, GTX 950

\# | GDScript (gdlife) | C# (gdlifenet)
-- | -- | --
1 | 17090 | 1743
2 | 17216 | 1711
3 | 17575 | 1700

How to benchmark:

1. Clone the projects repositories
2. Create exported builds of the projects
3. Run the exported builds and wait for the run to complete - the result is printed to stdout

--

The purpose of this issue is to keep a track on the performance in case there are any optimizations implemented in the future.

**Comment by Calinou** [comment] 2020-02-09 21:01
What's the point of this issue? It's known that there are plans to optimize GDScript in 4.0.

**Comment by dragmz** [comment] 2020-02-09 21:13
@Calinou currently the point is to keep a track on raw figures for any future optimizations

**Comment by nathanwfranke** [comment] 2020-02-10 05:06
I am kind of curious why GDScript would be that much slower. Isn't it converted into bytecode?

**Comment by Calinou** [comment] 2020-02-10 08:18
@nathanwfranke I don't remember if bytecode compilation is still present, but if it is, keep in mind it only speeds up how fast the script *loads*, not runs (just like in Python).

**Comment by Zylann** [comment] 2020-02-10 10:07
I've been doing GDScript microbenchmarks for a while: https://github.com/Zylann/gdscript_performance

**Comment by Shatur95** [comment] 2020-02-10 16:30
Bad to hear. I really like GDScript.

**Comment by jabcross** [comment] 2020-02-10 19:55
As I understand, GDScript is not intended for use in CPU-bound situations, it's just a convenient language for beginners that's tightly coupled with the engine specifics. Most games' CPU-bound use-cases are intended to be covered by specific nodes.

For CPU-bound situations you can use C#, GDNative or write a module.

**Comment by ShlomiRex** [comment] 2020-02-10 21:16
> As I understand, GDScript is not intended for use in CPU-bound situations, it's just a convenient language for beginners that's tightly coupled with the engine specifics. Most games' CPU-bound use-cases are intended to be covered by specific nodes.
> 
> For CPU-bound situations you can use C#, GDNative or write a module.

Agreed, though it is interesting topic.
I wonder if Native script (C++) is much faster than C#?

**Comment by dragmz** [comment] 2020-02-10 21:29
> I wonder if Native script (C++) is much faster than C#?

I've got a module Godot module implementation of the algorithm available here: https://github.com/dragmz/gdlifemod (tested with MSVC 2019 only)

**Comment by jabcross** [comment] 2020-02-10 23:01
> I wonder if Native script (C++) is much faster than C#?

C++ is theoretically as fast as it can possibly be. Unless you want to write assembly :D

Seriously though, C# is pretty fast as long as you're not memory-bound. Otherwise you get the same problem as Java: lag spikes on garbage collection.

**Comment by aaronfranke** [comment] 2020-02-11 07:56
> Unless you want to write assembly :D

A bit off topic, but... due to the sheer level of sophistication of compilers, it is extremely likely that C++ will outperform handwritten assembly. For trivial cases, the compiler has those cases optimized. For non-trivial cases, the problems are likely too complex for a human to hand-optimize the assembly.

Back on topic, here are some more benchmarks: http://www.royaldonut.games/2019/03/29/cpu-voxel-benchmarks-of-most-popular-languages-in-godot/ Note that voxel generation is a use case which can be given many low-level optimizations, so C# and especially C++ benefit a lot here.

**Comment by girng** [comment] 2020-02-11 10:44
> Bad to hear. I really like GDScript.

Please don't let specific benchmarks like this change your decision on GDScript :)

 GDScript is not just for beginners, and it's certainly not slow (relative to a smooth gaming experience). There are trade-offs with any language. The sheer power and rapid prototyping GDScript offers, while giving the developer the chance to build their dream game, should not be overseen.

**Comment by Shatur95** [comment] 2020-02-11 11:13
> Please don't let specific benchmarks like this change your decision on GDScript :)

Yes, I'm will use it :) I think that if necessary, I will rewrite the bottlenecks in C++.
The documentation also says that static typing in GDScript may increase performance in future.

**Comment by bojidar-bg** [comment] 2020-02-11 13:18
Note that GDScript uses real Godot Objects and the ObjectDB for managing them when creating sub-classes in a script. Also it will create ScriptInstances for each of them, and make every variable access on such a script go through a few levels of indirection (thankfully, it will not do string comparisons, but hashmap and red-black tree lookups are enough).
C# on the other hand, can get away with not boxing `int`-s and `bool`-s as `Variant`-s, not storing any excess information in the private classes, apart from what the garbage collector needs, and not doing any hashmap or tree lookups when reading variables from them. Also, it can place objects next to each other in memory, improving cache locality.
Thus, I suspect a lot of the slowdown in this benchmark comes from the fact that the GDScript version does a lot more computation than the C# version. Some of the difference may be eliminated by using a PoolByteArray or two to store the values of the tiles, instead of creating actual tile objects.

**Comment by dragmz** [comment] 2020-02-11 13:49
@bojidar-bg both implementations are intentionally naive to mimic what a beginner would do

**Comment by Janglee123** [comment] 2020-02-14 18:26
I accept that c# is more efficient than gdscript. But the gaming coding is not necessarily what causes performance issues. The performance of game is more likely to decide by the parts of the game that the engine is already handling. The average user case does not include rendering 10k sprites or anything like that. 
On the other hand, GDSript allows for rapid prototyping and makes it easy to get something ready quickly. 
So don't think GDScript is a bad option just because it's not optimized as something that optimized over years and years.

**Comment by pchasco** [comment] 2020-02-18 02:38
There are a number of performance improvements that can be made for GDScript, first and foremost by implementing some basic back-end optimization to the byte code. As of version 3.2 there is no optimization of the byte code beyond some basic constant folding that happens in the compiler front end (that I have observed, at least). Because GDScript VM executes code in a loop containing a giant switch, reducing the number of byte code instructions generated will go a long way to improving the performance.

I have a fork in the works that I've begun implementing the following optimizations of the GDScript byte code:

- Dead code/store elimination
- Jump threading
- Constant propagation
- Typed registers (Involves adding a number of virtual registers to the function state and instructions to address them. Access to virtual registers can be done without type checking for non-object types (int, real, vector, etc)). Not sure if it would make sense to extend this to further types.)

Potential:
- ptrcall registers - Same basic concept as typed registers for values, but with ptrcalls to avoid more expensive calls through script API.

Some of these optimizations would affect the semantics of the running application if GDScript is being run in multiple threads. Optimizations that store into typed temporaries in the virtual registers will not be visible externally until the values are stored, which may not be guaranteed until the exit of the function. C# has the volatile qualifier to tell the optimizer to always load the value before it's read and commit it to memory after it is modified. I don't think we'd want to add this level of additional level of complexity to GDScript, so the optimizations will need to be very conservative when they could introduce concurrency issues.

Even with all of these optimizations in place, there is very little chance that GDScript will perform as well as C#. Sure, you could build a JIT for GDScript, but I think it would be easier just to implement GDScript as a .NET language and use the mono tooling that is already in place.

**Comment by aaronfranke** [comment] 2020-02-18 02:48
> but I think it would be easier just to implement GDScript as a .NET language

Out of curiosity, do you know how such a thing would be done? It sounds like a fun experiment.

**Comment by pchasco** [comment] 2020-02-18 02:58
> Out of curiosity, do you know how such a thing would be done?

It's not something I've ever done in .NET, but it has been done. You would need to write your own front end to parse the GDScript, then transform that code to CIL instructions to build an assembly. Theoretically, at this point the assembly would be loaded and run no differently than one built with C#. Obviously it is easier said than done, but I think this solution would be easier than rolling your own JIT. Another approach is to compile GDScript to LLVM IL. I'm not sure which approach would be easier, but I suspect building the GDScript language for .NET would be as the mono integration is already in place.

**Comment by jabcross** [comment] 2020-02-18 03:42
If we're going to use a target for GDScript, it should probably be LLVM.
Dotnet is a bit big to bundle when targeting mobile phones, I think.

**Comment by pchasco** [comment] 2020-02-18 03:54
> If we're going to use a target for GDScript, it should probably be LLVM. Dotnet is a bit big to bundle when targeting mobile phones, I think.

Possibly... but the team has already decided that dotnet will be supported, and that support is implemented.

**Comment by aaronfranke** [comment] 2020-02-18 04:20
@pchasco Mono support is optional and the engine is officially and primarily compiled without it, since it about doubles the size of the engine to have Mono support.

**Comment by pchasco** [comment] 2020-02-18 04:50
> @pchasco Mono support is optional and the engine is officially and primarily compiled without it, since it about doubles the size of the engine to have Mono support.

That is true. If I am not mistaken LLVM has been discussed in the past and was decided against because it adds a rather sizable build dependency.

Personally, I think the best approach is to make GDScript as fast as it can be without going to JIT. I have done a significant amount of work on a GDScript to C compiler, but I have largely abandoned that effort in favor of improvements to the VM. After some initially encouraging results, real-world performance wasn't that much improved over GDScript to make it worth my while. The compiler targeted GDNative, which was the primary performance bottleneck. I could have it generate an engine module to avoid GDNative, but then it would be much less convenient to build.

**Comment by bojidar-bg** [comment] 2020-02-18 10:02
Note that GDScript performance improvements are planned, as discussed in a [google doc](https://docs.google.com/document/d/1JGMGZQTD0aVGe23BKyqIlnJ56ifYUK7K80n8V4KoP1M/edit?ts=5cd0456b#heading=h.8lrd3183co7).

Just a few cents on ideas listed previously:

> Dead code/store elimination
> Constant propagation

We were thinking of using SSA (single static assignment) in the compiler, which might alleviate this issue.

> Jump threading

Definitely sounds useful, and I can see how the compiler might sometimes generate bytecode which chains jumps needlessly.

> Typed registers

We were thinking of going for typed instructions instead. They will still use Variant, but they will not check its type, or unbox it, but will just take the bytes out.
With typed instructions, I feel there might not be much performance gain from this one, except for cache optimizations (due to less "padding" around the data from Variant).

> ptrcall registers

Not sure about this one either. Maybe there could be some instructions which do a ptrcall using a pointer stored within the bytecode directly?

> [..] I think it would be easier just to implement GDScript as a .NET

As already mentioned, non-mono builds of Godot should have working GDScript.
Not sure how well .NET will perform for untyped GDScript where everything might have to be `dynamic`, instead of having a  type.

> I think the best approach is to make GDScript as fast as it can be without going to JIT.

I agree. Going to JIT can only eliminate the time spent dispatching instructions. As currently implemented by #11518, the dispatching code is pretty fast, and can even be branch predicted by the CPU. (It is not a giant switch in a loop, except on compilers which do not support jumptables.)

**Comment by pchasco** [comment] 2020-02-18 13:20
@bojidar-bg Thanks for the share! I've been trying to find a summary of the planned improvements on github but I haven't had much luck to this point.

> We were thinking of using SSA (single static assignment) in the compiler, which might alleviate this issue.

You could go that way... But I think it's overkill. Deconstructing SSA form correctly is not trivial as it can introduce hard-to-find bugs in the code when not done correctly. You can still implement dead code elimination, constant folding, common subexpression elimination, and most other beneficial optimizations without it.

> We were thinking of going for typed instructions instead. They will still use Variant, but they will not check its type, or unbox it, but will just take the bytes out.

I suppose this could work... In my fork where I have been trying some of these things out I went direction of registers. Mostly because I did not want to suggest breaking encapsulation of the variant structure to work in its data directly. Getting directly into the variant data might be a bit faster because it would avoid the load/store operations for the registers.

> the dispatching code is pretty fast, and can even be branch predicted by the CPU.

Technically true but I wonder if this actually happens in practice.

**Comment by pchasco** [comment] 2020-02-28 07:35
I have a partial implementation of some of these optimizations in my fork:

https://github.com/pchasco/godot

Notably missing is support for the iterate and yield instructions, and functions with default arguments. Also incomplete is typed instructions. This is published now as only a PoC. In the next week or so I will implement the missing instructions. There is no challenge there beyond finding the time; there is no significant difference to them versus the standard jump instructions. 

Typed instructions will take somewhat longer.

I also plan to implement optimization for built-ins that are pure functions. Calls to pure functions are candidates for elimination via common sub expression elimination optimization.

**Comment by massanchik** [comment] 2020-05-08 14:10
> > Bad to hear. I really like GDScript.
> 
> Please don't let specific benchmarks like this change your decision on GDScript :)
> 
> GDScript is not just for beginners, and it's certainly not slow (relative to a smooth gaming experience). There are trade-offs with any language. The sheer power and rapid prototyping GDScript offers, while giving the developer the chance to build their dream game, should not be overseen.

On the other hand, I know Python and I know C# but I still  need to learn GDScript almost from scratch. While it's not that hard, it messes up with my brain when I come back to regular python development at work. It's similar to python in some cases,  but it's not python.
I guess will switch to C# for now, to save Python mental stuff 😅

**Comment by Two-Tone** [comment] 2020-05-13 07:04
> If we're going to use a target for GDScript, it should probably be LLVM. Dotnet is a bit big to bundle when targeting mobile phones, I think.

How small is LLVM? As far as I can tell it'd still more than double the current download size.

But honestly, going from 20MB to 50MB isn't exactly much. Sure, a 250% increase in download size sounds _huge_, but in context of modern day phones, computers, and available bandwidth it is absurdly tiny.

**Comment by jabcross** [comment] 2020-05-13 08:47
> > If we're going to use a target for GDScript, it should probably be LLVM. Dotnet is a bit big to bundle when targeting mobile phones, I think.
> 
> How small is LLVM? As far as I can tell it'd still more than double the current download size.
> 
> But honestly, going from 20MB to 50MB isn't exactly much. Sure, a 250% increase in download size sounds _huge_, but in context of modern day phones, computers, and available bandwidth it is absurdly tiny.

I was talking about the export's size, not the engine's. Games that use C# need to ship the virtual machine too on targets that don't have dotnet.

LLVM exports to native binary so it becomes a non-issue.

**Comment by DriNeo** [comment] 2020-05-13 10:41
If GDScript can be compiled using LLVM, all GDScript users will download the LLVM version.

**Comment by Calinou** [comment] 2020-05-13 12:30
@DriNeo I don't think that'd be quite the case. LLVM is notoriously difficult to compile from source, so any user who's using an OS without a recent prepackaged LLVM will likely not bother about it. (What about Raspberry Pis and the like?)

**Comment by jabcross** [comment] 2020-05-13 13:03
> @DriNeo I don't think that'd be quite the case. LLVM is notoriously difficult to compile from source, so any user who's using an OS without a recent prepackaged LLVM will likely not bother about it. 

Most users don't compile Godot from source, though. If somebody figures out the whole LLVM compilation issue and adds the source code to the repo (like we do with basically every external lib), all the end user will have to do is download the proper version from the website.

It would also be possible to implement LLVM support through an addon that outputs GDNative binaries, so this wouldn't necessarily need to be baked into the engine.

**Comment by Calinou** [comment] 2020-05-13 13:37
@jabcross The LLVM source code is dozens of gigabytes. It'll never be added to the Godot source repository at this point :stuck_out_tongue:

**Comment by Shatur95** [comment] 2020-05-13 13:41
> I think we should focus on improving GDNative integration instead (and possibly add WebAssembly support as a replacement in the long-term).

It would be awesome.

**Comment by jabcross** [comment] 2020-05-13 14:04
I'm not 100% updated on this, but the problem with GDNative currently is the interface bottleneck, right? Function calls still need string comparison and whatnot?

**Comment by pchasco** [comment] 2020-05-13 14:18
That's not entirely correct. You can basically acquire a handle to a script
method and use ptrcall to invoke it, eliding any lookup.

**Comment by jabcross** [comment] 2020-05-13 14:29
Still, lots of hoop jumping for something arguably simple. It happens with variable assignment too, right?

Are there any known estabilished games that  used GDNative so far?

**Comment by pchasco** [comment] 2020-05-13 15:24
> Still, lots of hoop jumping for something arguably simple. It happens with variable assignment too, right?

I don't think it's a lot of hoops. And I wouldn't recommend using ptrcall for every method; premature optimization adages still apply.
 
> Are there any known estabilished games that used GDNative so far?

Karroffel mentioned one on my [blog ](http://blog.moblcade.com/?p=85) but he didn't give the name of it...

**Comment by Shpendicus** [comment] 2020-07-08 19:26
What is the current state of GDScriptt right now and could you guys make some performance increase, be it GDNative and GDScript?

**Comment by nathanfranke** [comment] 2020-07-08 19:29
GDScript is being remade by vnen which will hopefully improve performance.

> be it GDNative and GDScript?

GDNative is a completely different language so I don't understand the second part

**Comment by pchasco** [comment] 2020-07-08 19:30
You can likely achieve performance increase by porting your GDScript to compiled GDNative scripts.

I am not confident that the currently proposed changes being made to GDScript will significantly improve performance, but time will tell.

**Comment by gjmcodes** [comment] 2020-07-16 21:30
Out of curiosity, accordingly to Godot documentation:

> .NET / C#
As Microsoft's C# is a favorite amongst game developers, we have added official support for it. C# is a mature language with tons of code written for it, and support was added thanks to a generous donation from Microsoft.

It has an excellent tradeoff between performance and ease of use, although one must be aware of its garbage collector.

I'm curious what manual care I'd have to have when coding with C#. Is there any recommendation to where and when I should manually call garbage collection operations in C# scripts?

**Comment by pchasco** [comment] 2020-07-16 21:36
> I'm curious what manual care I'd have to have when coding with C#. Is there any recommendation to where and when I should manually call garbage collection operations in C# scripts?

I don’t know why you would need to manually force a collection. I definitely would not do it during gameplay. The only time when it may be beneficial to do a manual collection would be after loading or saving a game, or after dismissing a menu when you can get away with some stutter. But you can generally just ignore the GC altogether if your game is performing well.

**Comment by Two-Tone** [comment] 2020-07-16 21:37
You'd be better off asking your question either on the [subreddit](https://www.reddit.com/r/godot/) or [Godot Q&A](https://godotengine.org/qa/questions).

**Comment by gjmcodes** [comment] 2020-07-16 22:10
Thanks! Well, truth be told: the way putted out in the documentation seemed there should be some sort of handling or expectations for memory leak if things are kept 'automatically'.

All in all, I was just curious whether instantiations and real time calculations could leave garbage behind without any proper manual handling. I'll query about those on Reddit. Thanks!

**Comment by milkowski** [comment] 2020-09-10 21:19
There is new kid on the block: MIR https://github.com/vnmakarov/mir that is aiming to be lightweight JIT for multiple intermediate representations https://developers.redhat.com/blog/2020/01/20/mir-a-lightweight-jit-compiler-project/ and initially being implemented as JIT for Ruby 3.0.
It seems it could be interesting target also for typed GDScript.

**Comment by Shpendicus** [comment] 2020-11-17 15:10
@milkowski so would u then use GDScript or GDNative code in combination with this new M-JIT?

**Comment by thunderrous** [comment] 2020-11-29 09:50
Sorry to barge in like this but I'd like to ask what performance difference is there between gdscript and lua?

**Comment by Miziziziz** [comment] 2021-02-16 06:38
Sharing my findings here:


**Godot version:** Godot Mono v3.2.3 and Godot v3.2.3



**OS/device including version:** Windows 10, GLES3, Geforce 2060 rtx



I have this procedural hair generated using ImmediateGeometry:
https://user-images.githubusercontent.com/7292421/107883893-fb097d00-6eae-11eb-9c10-86a716994d3a.mov
Calculating all the vertice positions requires a lot of vector math (cross products and such) and then also has to be converted from local, to global, to local positions at one point. Doing this on my machine has a noticeable impact in the profiler:
![gdscriptprofiler](https://user-images.githubusercontent.com/7292421/107883954-50458e80-6eaf-11eb-9027-35c21aa2f76e.png)
Recreating this in C# gives about a 10fps improvement in my main project.
Can't really see frame time in the profiler but you can see the graph and compare:
![csprofiler](https://user-images.githubusercontent.com/7292421/107883991-900c7600-6eaf-11eb-9758-51ba0432f626.png)

Since math is done in c++ I figured the issue was probably related to how gdscript handles loops or arrays and might be worth reporting.

**Minimal reproduction project:**

contains a C# scene and GdScript scene
[ProcHairTest.zip](https://github.com/godotengine/godot/files/5978133/ProcHairTest.zip)

**Comment by pchasco** [comment] 2021-02-16 14:45
It's difficult to speculate exactly why C# is significantly faster than the GDScript version. I would expect a significant difference would be that the mono module has its own mirror implementations of the core types, including vector3. Having mono implementations of those core types enables visibility into the methods by the optmizer, and as they are not virtual, it may be able to inline some of the calls. The GDScript runtime has to dynamically dispatch calls on Vector3. Also, your GDScript execution is very CPU pipeline unfriendly, and branching and by necessity loops in GDScript compile out to many unnecessary and unpredictable branches in the bytecode (as far as the branch predictor is concerned), likely forcing the CPU to flush its pipeline frequently.

**Comment by trudnai** [comment] 2021-05-30 01:21
> A bit off topic, but... due to the sheer level of sophistication of compilers, it is extremely likely that C++ will outperform handwritten assembly. For trivial cases, the compiler has those cases optimized. For non-trivial cases, the problems are likely too complex for a human to hand-optimize the assembly.

That is actually a general misconception made up by C++ programmers who never ever seen an Assembly code. Assembly code can be as well optimized as the coder knowledge and experience allows it to. So a good Assembly programmer can make a lot better code than a C++ any time. However, a beginner will not be able to optimize their code too much. Unlike a beginner C++ programmer who  just pass a command line argument to get a fair output. 

Now as for commenting of the experienced Assembly programmer, it still takes time to manually optimize a code and sometimes that makes the code quite unmaintainable at the end. Once I wrote a DSP filter to a PIC controller, and it took me a good 3 month just to optimize it and to fit into the chip. As a result I was able to use a much smaller chip than the competition meanwhile filtering 2 channels at the same time instead of just 1. Simply because I was using Assembly and not C.

Moral is that writing something in Assembly can give you the ultimate performance and smallest code, but might not worth the effort of it. And it depends on the project again, so if you can save just $1 per circuit by using a smaller chip, you can save a million dollar in a million unit. But in a Game development it might not justify the amount of work you push into it.

**Comment by pchasco** [comment] 2021-05-30 03:13
Certainly a developer with a deep knowledge of the problem, the specific
hardware, and the specific instruction set can write as good or better code
than any optimizing compiler. The problem comes in when writing code that
should run on other hardware. Even if the program is compatible with a
different CPU, there are few guarantees that it will be optimal.

**Comment by asheraryam** [comment] 2021-12-09 08:26
@vnen I don't think this issue is relevant after the GDScript rewrite, the benchmarks need to be redone

**Comment by vnen** [comment] 2022-01-07 03:07
> @vnen I don't think this issue is relevant after the GDScript rewrite, the benchmarks need to be redone

The information is interesting to have for history's sake and it does need to be re-run from time to time, but I don't think an open issue is the best place to keep this information (given there's nothing actionable to one day close the issue). I don't know what would be the best place though.

**Comment by elvisish** [comment] 2022-02-27 14:47
How is performance comparably after the rewrite?

**Comment by vnen** [comment] 2022-03-23 20:44
I gave some general numbers about improvement in GDScript itself a while ago: https://godotengine.org/article/gdscript-progress-report-typed-instructions

I haven't compared it with other languages and don't plan to for now. Focus on performance will happen after Godot 4.0 is released.

I'm closing the issue now as I don't think there's anything that could be done here. Sure, GDScript could have better performance, but it doesn't really need to be on par with C#.

**Closed by vnen** 2022-03-23 20:44 UTC
Labels: discussion, topic:gdscript, topic:dotnet, performance
