### ISSUE TITLE
3D Particles Leads to FPS Drop

### ISSUE THREAD

**Issue by samdaiya** [godotengine/godot#29973] opened 2019-06-22 05:06 UTC
**Godot version:** 3.1.2

**OS/device including version:** Manjaro Linux and Android Oreo

**Issue description:** When I Emmit Partcles for the First Time FPS Drops and game gliches. On Second time there is no issue. I createad a Particles Scene and then created instance of it in main scene using GDScript. I also tried it with Android and experienced the same problem.

**Screenshots**
* FPS at Start
![Idle FPS](https://user-images.githubusercontent.com/17422674/59959611-be6a6000-94d8-11e9-9cb0-3c5d80591dde.png)

* FPS at First Particle Emmition
![First Particle Emission](https://user-images.githubusercontent.com/17422674/59959615-cf1ad600-94d8-11e9-93f9-1048c5232697.png)

**Steps to reproduce:** Open and run project provided by me and then and then hit "Enter" you will see FPS Dropping and Glitch. FPS count is at the bottum left of the Scene.

**Minimal reproduction project:** 
[ParticlesFPSDrop.zip](https://github.com/godotengine/godot/files/3316511/ParticlesFPSDrop.zip)

**Comment by clayjohn** [comment] 2019-06-22 05:18
Duplicate of https://github.com/godotengine/godot/issues/13954 and https://github.com/godotengine/godot/issues/17263

This issue is caused by the shader having to compile on the first frame it is shown. Here is a great youtube video explaining how to work around the problem. https://www.youtube.com/watch?v=Cg4ZT6X0ghs

**Comment by samdaiya** [comment] 2019-06-22 05:44
I tried without adding any Shader Material and still facing same problem.

**Comment by clayjohn** [comment] 2019-06-22 05:57
There is a spatial material on the object and a particles material for the particles. Both need to compile. In order to avoid the hiccup, you need to follow the steps in the video. i.e. Have the particles appear in the scene for a frame before the scene is loaded so that the shader compiles.

**Comment by samdaiya** [comment] 2019-06-22 06:00
I have a mian Scene that contains Instances Particles

**Comment by samdaiya** [comment] 2019-06-22 06:42
I switched to GLES2 and Converted Particles to CPUParticles and there no more glitches.

**Closed** 2019-06-22 07:32 UTC
Labels: topic:core, topic:rendering

**Comment by mipsc** [comment] 2021-01-02 07:40
> Duplicate of #13954 and #17263
> 
> This issue is caused by the shader having to compile on the first frame it is shown. Here is a great youtube video explaining how to work around the problem. https://www.youtube.com/watch?v=Cg4ZT6X0ghs

I'm having this issue and been struggling to solve it for weeks already, and I applied the trick and I got it finally solved!
