### ISSUE TITLE
Keyboard Input gets stuck, Windows

### ISSUE THREAD

**Issue by LanceJZ** [godotengine/godot#6612] opened 2016-09-25 20:50 UTC
Sept 23rd compile
Windows 10 OS

When a key is pressed, then released the pressed is no longer true.
The pressed stays true after key is released.

My asteroids project that works in 2.1, compile it in 2.2, issue above happens.

https://github.com/LanceJZ/Godot_Asteroids

**Comment by Faless** [comment] 2016-09-26 11:07
This is related to: #6388 .
Action stays "pressed" due to the modifier still being counted in the release action.
The shift gets stuck because when pressed the event has (keycode = shift, modifiers = shift) while when released has (keycode = shift, modifiers = none).

**Comment by Hinsbart** [comment] 2016-09-26 16:19
yeah, I guess it happens because the "Fire" action is bound to `ctr`, a modifier.
So duplicate of #6388

**Comment by vnen** [comment] 2016-09-26 17:01
Closing as duplicate of #6388 then.

**Closed by vnen** 2016-09-26 17:01 UTC
Labels: bug, topic:core
