### ISSUE TITLE
On certain Android devices, 3D models do not appear

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#86956] opened 2024-01-08 08:30 UTC
### Tested versions

- Reproducible in: 4.2.1, 4.2, 4.1.3, 4.1.2, 4.1.1, 4.1
- Not reproducible in: 4.0.3 and before (didn't encounter the issue in these versions)

### System information

Windows 11 64-bit, Ryzen 5 5500U, 8GB RAM, Nvidia GTX 1650

### Issue description

So if the game has a 3D model, then it does not render on some Android devices. Interestingly, when I open the app on my phone for the very first time after installing it, the models are rendererd properly. However, after opening the app second time, the model disappears. To fix this, I have to either delete cache/data, or reinstall the app again. Doing this it works, however launching the app again makes the model disappear.

So this issue starts happening after we open the app second time and beyond.

### 3D Models
- This is not happening with primitive models made inside Godot. It only happens with imported models. I have right now only tested this with .glb file.
- Even with imported models, when imported a basic Blender's monkey mesh with a material, it rendered properly.
- However, all the Mixamo models I tested, and some of my owns didn't work.

### Android Devices
- So it happens only with some Android devices.
    - It didn't work on Poco M4 Pro.
    - However, when tested on Realme 9 Pro 5G, it worked without any issues.
    - Similar problems happened with few more devices, but I don't remember their names.

### Similar/Same Issue
- This issue seems to have the same problem - https://github.com/godotengine/godot/issues/80668

### Steps to reproduce

1. Download the MRP provided.
2. Extract the apk/project files to your desired location.
3. Open the project files using Godot.
4. Go to Project -> Export.
5. Select Android (Runnable).
6. Press export project, and save your file to your desired location.
7. Install the apk on your Android phone.
8. Run the app for the first time (everything will work fine & you will see character and monkey models).
9. Run the app second time (depending on your device, the character model on left will disappear).

### Minimal reproduction project (MRP)

[Android 3D Rendering Issue.zip](https://github.com/godotengine/godot/files/13857777/Android.3D.Rendering.Issue.zip)

**Comment by Zireael07** [comment] 2024-01-08 08:32
As you already noted, duplicate of #80668 most likely

**Comment by bitsawer** [comment] 2024-01-08 11:39
Are you using the compatibility renderer? This:

>Interestingly, when I open the app on my phone for the very first time after installing it, the models are rendererd properly. However, after opening the app second time, the model disappears.

might also point towards https://github.com/godotengine/godot/issues/82419. You can try disabing shader cache as mentioned in https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963 and see if that helps.

This is possibly a duplicate of some of the mentioned issues, but let's see if we can get any more info.

**Comment by Skyvastern** [comment] 2024-01-08 18:36
> Are you using the compatibility renderer? This:
> 
> > Interestingly, when I open the app on my phone for the very first time after installing it, the models are rendererd properly. However, after opening the app second time, the model disappears.
> 
> might also point towards #82419. You can try disabing shader cache as mentioned in [#82419 (comment)](https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963) and see if that helps.
> 
> This is possibly a duplicate of some of the mentioned issues, but let's see if we can get any more info.

I had rendering mode set to compatibility already. However, shader cache was enabled, so disabling it actually worked on the sample project I provided. Looks like this is the cause of the issue.

Gonna confirm the same for the main project I was working on, and if it works there too, then that means shader cache was the issue!

**Comment by Skyvastern** [comment] 2024-01-09 09:57
> > Are you using the compatibility renderer? This:
> > > Interestingly, when I open the app on my phone for the very first time after installing it, the models are rendererd properly. However, after opening the app second time, the model disappears.
> > 
> > 
> > might also point towards #82419. You can try disabing shader cache as mentioned in [#82419 (comment)](https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963) and see if that helps.
> > This is possibly a duplicate of some of the mentioned issues, but let's see if we can get any more info.
> 
> I had rendering mode set to compatibility already. However, shader cache was enabled, so disabling it actually worked on the sample project I provided. Looks like this is the cause of the issue.
> 
> Gonna confirm the same for the main project I am working on, and if it works there too, then that means shader cache was the issue!

Yes, disabling shader cache fixed the problem in the main project I was working on. Thanks a lot!

So, I think its confirmed that shader cache is the issue. Would like to know that is disabling shader cache the expected behaviour on Android with 3D models, or is it something that has to be resolved? And is there any downsides of disabling it?

Either way, the current workaround or the expected thing to do fixed the issue for me. Thanks again for the help!

**Comment by bitsawer** [comment] 2024-01-11 12:10
Thanks for confirmation, closing this as a duplicate of https://github.com/godotengine/godot/issues/82419 as disabling shader caching seems to help.

As for disabling shader cache, see https://github.com/godotengine/godot/issues/82419#issuecomment-1743757677. 

If you can reproduce the `_save_to_cache()` error, it might be a good idea to make a new, separate issue for it if there is no existing one yet.

**Closed by bitsawer** 2024-01-11 12:10 UTC
Labels: bug, platform:android, topic:rendering, needs testing, topic:3d
