### ISSUE TITLE
Godot autogenerated signals functions doesnt create in VSCode

### ISSUE THREAD

**Issue by uSources** [godotengine/godot#35885] opened 2020-02-03 15:26 UTC
**Godot version:** 3.2 Mono

**OS/device including version:** Windows 10

**Issue description:** Godot doesnt add singal function to a script file.

**Steps to reproduce:** Using Godot Mono and VSCode as IDE. Try to attach one signal to script, VSCode opens up but doesnt add signal function to C# script.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-02-03 22:39
Duplicate of #23208.

**Closed by Calinou** 2020-02-03 22:39 UTC
Labels: bug, topic:editor, topic:mono
