### ISSUE TITLE
NinePatch changes texture scale when resized

### ISSUE THREAD

**Issue by shmellyorc** [godotengine/godot#33225] opened 2019-11-01 01:06 UTC
Godot version:
Godot 3.2 Alpha 3 (from your website)

OS/device including version:
Windows 10

Issue description:
When doing pixelated texture, resizing the Ninepatch changes its scale.

Steps to reproduce:
1. Add a pixelated nine patch frame
2. Set up the patch margins
3. resize the nine patch in the editor.

Minimal reproduction project:
https://i.imgur.com/VeQeuhQ.gifv

Notes: Godot 3.2 alpha 1 doesn't have this issue. Anything past alpha 1 has this issue.

**Comment by clayjohn** [comment] 2019-11-01 05:16
CC @puthre maybe related to your PR?

**Comment by puthre** [comment] 2019-11-01 08:02
@shmellyorc you'll have to have your ninepatch texture resolution smaller than what you will have on screen otherwise it will get scaled down. Previously (before #32170) it would just be distorted (but you wouldn't have seen that in your example as the margins in your example are the same everywhere).

**Comment by shmellyorc** [comment] 2019-11-01 22:11
@puthre alpha1 and below doesn't have this issue. It should stop at the points of the margins NOT scale the texture. Alpha1 and below, it stops at the margins. I cannot do most of my ui since it would scale the textures. 

In Apha1: My margins patch margins are 4, the same as it was in the picture above. I shouldn't need to adjust anything because someone thought to scale textures below the margins. If I set my viewport is set to a scale, all nodes should enforce to that scale, it seems lazy.

alpha1 viewport margin:
https://i.imgur.com/VYpEk7x.gifv

**Comment by akien-mga** [comment] 2019-11-27 10:31
So that's not a regression but a bugfix?

**Comment by Shadowblitz16** [comment] 2020-01-20 21:40
@puthre both scaling down and distortion is considered a but when it comes to how 9 slices should work.

if the 9 slice is smaller then the texture it should start clipping starting with the center, then the edges, then the corners until it is completely invisible with a size of 0,0

**Comment by puthre** [comment] 2020-01-20 22:33
@Shadowblitz16 I don't think I understand your proposal (or as I understand it it would not look very good except with some hand picked use cases). The main reason for my fix as far as I remember was that you could not use the 9 patch frame at all in Stretch Mode = 2D mode where your viewport size is can be much lower than the actual resolution of the device (which happens when you deploy on a mobile device) and you need to have textures much larger than the size of the viewport to match that screen resolution. Before my fix it didn't even distorted in the same way with GLES2 and GLES3. 
If you don't want it to scale, just provide a smaller texture.

**Comment by Shadowblitz16** [comment] 2020-01-21 01:36
No this is horrible for pixel art we shouldn't have to modify our textures because you decided to change how 9 patches have always worked.

if anything it should be a flag or a project setting to scale down these things.
you basically just broke everyone's projects that relied on these.

this is kinda why I get angry is because some person comes along and instead of just fixing the problem they do something that doesn't make sense or breaks backwards compatibility

9 slices are there to prevent the edges from being warped there is no point in them if they don't do this.

if you need to scale these things, implement a way to scale the canvas or the scale the 9slice.

**Comment by akien-mga** [comment] 2020-01-21 07:08
@Shadowblitz16 While I can understand your frustration, I'll have to ask you to remain civil and avoid using making things personal. You may disagree with the change, but you shouldn't express anger, especially not against other community members. https://godotengine.org/code-of-conduct

**Comment by akien-mga** [comment] 2020-01-21 07:09
Can anyone provide a reproduction project so that we can see what works and what doesn't?

**Comment by naturally-intelligent** [comment] 2020-05-07 19:08
Also having this issue with a broken downscaling after upgrading to Godot 3.2.1

It's nice there is a workaround for now, but I agree this is a bug/regression because NinePatches should never scale their edges (at least without some kind of flag allowing it set by the dev).

**Comment by Lucrecious** [comment] 2020-05-10 06:09
@naturally-intelligent What exactly is the work around here? I've been stuck on how to fix this for hours...

**Comment by puthre** [comment] 2020-05-10 08:58
@Lucrecious Scale your texture down to be smaller than the resolution of the patch on screen.

**Comment by naturally-intelligent** [comment] 2020-05-12 01:14
Not scale - I think you mean to edit your 9P textures to have less stretch than the biggest use.

**Comment by Lucrecious** [comment] 2020-05-12 13:13
@puthre @naturally-intelligent 
Sorry, I feel very dumb, but I literally don't understand what you guys are saying.

I don't know what "less stretch than the biggest use" means or "scale your texture to be smaller than the resolution of the patch".

Would it be possible for either one of you to provide a concrete example using actual numbers? An example that starts from a 9P that down scales and ends with it being fixed? Doesn't have to be a Godot file, just some text.

**Comment by puthre** [comment] 2020-05-12 14:15
@Lucrecious The nine patch margins will only stretch down if it can't fit in the small space you allocate to it on screen (small relative to the patch texture resolution). Just try to scale down the image texture that you are using for the nine patch (using gimp or something similar) and you will see what I mean.

**Comment by shmellyorc** [comment] 2020-05-22 14:23
in 3.0, the textures wouldnt stretch (wouldnt change scale). The corners and the ninepatch would stop to the size of the corners. Ever past 3.0, I have to make very small textures.

**Comment by naturally-intelligent** [comment] 2020-05-22 23:36
> @naturally-intelligent What exactly is the work around here? I've been stuck on how to fix this for hours...

If you look at this tutorial image:

https://tekeye.uk/android/examples/ui/android-9-patch-image-files

You will have to make middle sections 2,4,5,6, and 8 very small (1 pixel), while your corners (1,3,7,9) can be any size.

I spent the better part of a day in frustration thinking this was my fault, until I found this thread, so I feel your pain...

**Comment by agameraaron** [comment] 2020-06-12 06:47
Confirmed that GLES2 implementation for tiling axis stretching doesn't work.
It looks identical to stretched mode as if it is the same option or acts the same.
This forces me to use GLES3 if I want to have my program's nine patches appear correctly.
I would much prefer keep using GLES2 for the wider compatibility.

**Comment by akien-mga** [comment] 2020-10-21 15:15
Fixed by #42119.

**Closed by akien-mga** 2020-10-21 15:15 UTC
Labels: bug, confirmed, regression, topic:rendering

**Comment by RPicster** [comment] 2021-04-05 17:59
Hello, this issue is still alive and kicking. It's not fixed by the mentioned commit.
Having the issue in GLES3 in 3.3RC7

**Comment by akien-mga** [comment] 2021-04-05 18:18
There are two nine patch modes, which one are you using? It would likely be better to open a new issue with full details on the issue as you experience it in recent build.

**Comment by RPicster** [comment] 2021-04-05 21:11
I tried it with different modes, settings Nodes and the problem was always the same - I will open a new issue!
