### ISSUE TITLE
Scroll bar and text

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#58356] opened 2022-02-20 14:15 UTC
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

In the method selection window, too long function names overlap the scroll bar.
I think they should be behind the bar and also should not be displayed in the area occupied by the scroll bar. That is, the text should not be displayed (not even behind the bar) in the area occupied by the scroll bar.
![Captura2](https://user-images.githubusercontent.com/19652075/154847000-28e96dcd-6597-40f2-86e6-10c82269fc1f.PNG)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by KoBeWi** [comment] 2022-02-20 17:19
Duplicate of #57881

**Closed by KoBeWi** 2022-02-20 17:19 UTC
