### ISSUE TITLE
Importing as Atlas Texture has no effect whatsoever

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#37071] opened 2020-03-15 17:39 UTC
**Godot version:** 3.2.1. stable

**OS/device including version:** Win64

**Issue description:**
Following this procedure: https://godotengine.org/article/atlas-support-returns-godot-3-2 results in a forced restart, but upon restart of the editor, all pngs are exactly as before.

**Steps to reproduce:**
Follow this:
https://godotengine.org/article/atlas-support-returns-godot-3-2

**Comment by navett52** [comment] 2020-04-14 03:39
I am also having this same issue. I'm running on Pop!_OS, 64 bit. I hope this gets a fix soon.

**Comment by Giwayume** [comment] 2020-04-23 03:12
Can anyone confirm that the article https://godotengine.org/article/atlas-support-returns-godot-3-2 works for them, and what operating system/Godot version they're using? I assume this feature was tested and working at some point?

**Comment by asheraryam** [comment] 2020-04-23 07:52
@Giwayume I'll try older versions in the weekend because it's not working for me on 3.2.1

**Comment by IanKovich** [comment] 2020-05-07 18:20
**@ Giwayume**
> Can anyone confirm that the article https://godotengine.org/article/atlas-support-returns-godot-3-2 works for them, and what operating system/Godot version they're using? I assume this feature was tested and working at some point?

I'm using Windows 64-bit. It looks like the feature works perfectly fine in 3.2, but not in 3.2.1. I REALLY hope this gets fixed, because it's unbelievable how easy it is to use.

**Comment by travisryte** [comment] 2020-05-16 14:18
I'm also having this problem 3.2.1 doesn't work. Using Windows 64-bit.

**Comment by Calinou** [comment] 2020-05-31 19:26
Could someone try to [bisect the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) to see when it broke exactly? Also, try [3.2.1rc2](https://godotengine.org/article/release-candidate-godot-3-2-1-rc-2) and [3.2.1rc1](https://godotengine.org/article/release-candidate-godot-3-2-1-rc-1) to narrow the range of commits that need to be built to bisect the regression.

**Comment by akien-mga** [comment] 2020-06-02 08:30
I think this was fixed in 3.2.2 beta already. Please try https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-3

**Comment by akien-mga** [comment] 2020-06-02 08:31
Duplicate of #36976 (please comment if your tests show otherwise).

**Closed by akien-mga** 2020-06-02 08:31 UTC
Labels: bug, confirmed, topic:import

**Comment by asheraryam** [comment] 2020-06-02 15:15
I can confirm this is fixed on 3.2.2 beta 3 

![image](https://user-images.githubusercontent.com/43449832/83537230-f35e9f80-a4fc-11ea-8b1b-a2df8aff92fc.png)

**Comment by chucklepie** [comment] 2020-06-08 16:02
Will this fix texture array creation option from the same place as this failed too?

**Comment by asheraryam** [comment] 2020-06-08 20:42
@chucklepie I didn't try that and I am not sure what you mean, but I guess you can download the beta from the website and make sure.

**Comment by chucklepie** [comment] 2020-06-08 22:02
Import as atlas works in beta. What I meant by the texture array is I presumed the import option 'texture array' would create a sprite sheet out of selected graphics, but I guess not.

Doesn't help when you read the manual there is absolutely nothing on the 'import as...' options...


https://docs.godotengine.org/en/stable/getting_started/workflow/assets/import_process.html?highlight=import

or here
https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html

It completely skips what any of the import

**Comment by golddotasksquestions** [comment] 2020-11-26 16:27
Importing Atlas textures still feels incredibly unreliably and broken due to various reasons:

On Win 64, the AtlasTexture reimport process fails with the exact same symptoms in Godot 3.2.3 stable and Godot 3.2.4 beta2, the way it is described here under "How to use atlases in Godot": https://godotengine.org/article/atlas-support-returns-godot-3-2
Currently this is the only documented guide for using Atlas Textures as using search will only bring up [API docs](https://docs.godotengine.org/en/3.2/classes/class_atlastexture.html).

Here is how I read those instructions:

1. Select a bunch of png files in the FileBrower tab, 
2. go to the import tab,
3. select Import as: "TextureAtlas"
4. make sure that no AtlasTexture exists or to select an already existing AtlasTexture (if you do this the first time you obviously won't have an existing AtlasTexture, so you would think there is nothing to do, except to hit "reimport")
5. hit "reimport"
6. - popup saying changing the type requires restart, 
7. hit "Save Scenes, Reimport, and restart" button
8. - Godot saves, (presumeably) reimports, shut down and restarts

Navigate to the folder with the individual png files:
no atlas file file
Try to double click one of the individual png files:
just no reaction whatsoever
Dragging individual png file into viewport:
showing the "forbidden" symbol

Switching windows in the OS to another program than back to Godot will cause an automatic reimport every time.

If you then go to the guide again to figure out what went wrong you might notice an "res://atlas2", so you think it might be required to write something there even though the guide said having no file is fine too.

So select all your png files again, and in the Import tab under AtlasTexture you write "res://atlas2.png" this time, just like in the screenshot, hit "reimport" .... but nothing happens. You double click the png file, nothing happens.

If you do all that instead of a file path (like "res://atlas2.png") you would type just a name in that field like "atlas2", after the reimport/restart, no whenever you double click a png file you get a "loading error" popup, asking you to fix dependencies (which you can't because the "atlas2" file was not created, or at least does not show up anywhere. When you try to drag one of the png files into the viewport a sprite gets added to the Scene Tree, but the texture does not show up (despite being loaded).

The only way to actually make AtlasFiles work is to not to do any of the above and right away

1. Select a bunch of png files in the FileBrower tab, 
2. go to the import tab,
3. select Import as: "TextureAtlas"
5.  **type out a full filepath** to where you want the Atlas file generated to, like (like "res://inages/atlas.png")
6. hit "reimport"
7. - popup saying changing the type requires restart, 
8. hit "Save Scenes, Reimport, and restart" button
9. - Godot saves,  reimports, shut down and restarts

This is incredibly frustrating (and alienating to newcomers) because the UI is anything but clear about what the correct steps are and even the tiniest mistake leads to your files not working anymore without any feedback to the user as to what the issue is or where they did wrong, or how to reverse the steps so they can try again.

**Comment by Giwayume** [comment] 2020-11-26 19:19
Hmmm I haven't had the same problem. My process:

1. Click the folder icon

![image](https://user-images.githubusercontent.com/4075314/100385978-27b9a100-2ff2-11eb-9f8e-ef76d5ccae8d.png)

2. On the dialog that pops up, navigate to a folder, type the filename and click "save".

![image](https://user-images.githubusercontent.com/4075314/100386014-43bd4280-2ff2-11eb-9212-1c66a7b76a23.png)

3. Click the "Reimport" button. 

And it works.

**Comment by golddotasksquestions** [comment] 2020-11-26 21:33
Lucky you.

**Comment by Giwayume** [comment] 2020-11-26 23:19
> Lucky you.

The snark isn't necessary. Documenting where it works and where it doesn't is important for fixing these kinds of issues. I'm also trying to clarify your step 4 as you've made no clear indication whether or not you've tried the file selection dialog.

**Comment by golddotasksquestions** [comment] 2020-11-26 23:45
I was not trying to be snarky. I mean it in the literal sense. There are so many ways the user can fall off the right path here and the engine is not communicating what is going wrong or how to fix it, so much that I really think you are literally lucky, lucky your intuition matched the intended "right" path, and did not lead you off that path into a ditch, causing you hours wasted for no good reason. The UI does not make any of this obvious. There are cliffs and pitfalls left and right. Any survivor that goes through this unharmed is imho for the lack of a better word: lucky.

Dokumentation is necessary of course, but this is not only documentation issue. There should not be any cliffs and pitfalls left and right. The right path should be clear and brightly lit, easy to see. And if anyone should stumble despite all that, there should be cushions left and right that softly bounce the user back into the right direction and keep them straight on the right path.

> I'm also trying to clarify your step 4 as you've made no clear indication whether or not you've tried the file selection dialog.

You did not post a question in your previous comment, otherwise I would of course have answered: Yes I've tried clicking the file dialog. Unfortunately my 30+ years experience with file dialogs taught me that this was for opening files. What was I suppose to save? I have not done anything yet. I have not made an Atals Texture at this point. If this is indeed for saving I thought, it must be at a later point.
In my 30+ years of working with all kinds of software I have never experiences this kind of UX flow. I don't know where you got your experience so your intuition led you to the right path immediately, but I can tell you I would have never got there without meticulously and methodically testing each and every possible solution one by one for hours in painful trail and error.
