### ISSUE TITLE
[Vulkan] Workflow - Create a empty 3d scene causes black screen

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50153] opened 2021-07-04 12:35 UTC
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When the user create a blank 3d scene, with a camera, the scene will be totally black. which can lead to misunderstanding of what is happening.

What is really happening is that the scene has no default WorldEnviroment Like early versions of godot has!

**Solution**

Bring back the default WorldEnvironment node!

### Steps to reproduce

N/a

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2021-07-04 14:58
Duplicate of https://github.com/godotengine/godot/issues/46478.

**Closed by Calinou** 2021-07-04 14:58 UTC
