### ISSUE TITLE
when importing .gltf with separate meshes, naming of imported meshes is unintuitive and different than what it was in < 3.4

### ISSUE THREAD

**Issue by Rbetik** [godotengine/godot#54922] opened 2021-11-12 16:32 UTC
### Godot version

3.4

### System information

Mac OS Mojave 10.14.4

### Issue description

When importing .gltf with option 'import with separate objects ' resulting .mesh files are named as 'scene name' + default type from 3d editor instead of custom name as it was in previous versions

### Steps to reproduce

1. import .gltf with separate objects
2. look at names of resulting .mesh files

### Minimal reproduction project

[weight_paint_import_bug](https://github.com/Rbetik/weight_paint_import_bug)

Edited: Url was incorrect.

**Comment by Calinou** [comment] 2021-11-12 17:28
cc @fire

**Comment by fire** [comment] 2021-11-12 18:46
Can you give an example what you want it to be if you can change the name?

**Comment by Rbetik** [comment] 2021-11-12 18:54
How it worked in 3.3.4 (and below ) seemed pretty intuitive, mesh name was the same as name of meshinstance class in .gltf scene, which is the same as name of object in 3d modeling tool.

**Comment by betalars** [comment] 2021-11-22 19:15
Can replicate, went here to make this an issue myself.

I get, that this behavior might help when users do messy naming conventions, but it breaks your project, when you are using previously established proper naming conventions.

Also: I would add that the **use legacy names** checkbox seems to not be working right now. (I would assume this is intended so users may keep the naming convention as it previously worked)

Please fix this ASAP. I was just in the process of updating all my meshes and import files to use a good naming scheme so I can find everything and now I have to redo that entirely. Not looking forward to having to redo that process again.
![image](https://user-images.githubusercontent.com/18014034/142921534-ea86a478-c325-41ab-9653-b17ef66c2234.png)

**Comment by betalars** [comment] 2021-11-22 19:23
> Can you give an example what you want it to be if you can change the name?

I think the change is fine and I think I will adjust my naming convention to fit the new system (well I have to anyway, because I cannot wait for the fix). I just think the Checkbox should work so users can keep their existing conventions.

This being said: I think I have a slight preference for using the old scheme as default and have the checkbox be relabelled to something like "Include root file name"

**Comment by joeyeroq** [comment] 2021-11-26 22:11
This change is not fine, the gltf file name should not be part (a suffix) of the mesh name. This change has unfortunately has spilled over to the godot 4 version and hopefully will be reversed.

**Comment by Calinou** [comment] 2021-11-27 01:20
`use_legacy_names` is `true` by default: https://github.com/godotengine/godot/blob/f11bed249ba027d3b27a77e130b1178889789da3/editor/import/resource_importer_scene.cpp#L1076

However, I can see that it's forcibly set to `false` for files that do not have an existing `.import` *file* (not to be confused with the top-level `.import/` folder): https://github.com/godotengine/godot/blob/f11bed249ba027d3b27a77e130b1178889789da3/editor/editor_file_system.cpp#L1695

**Comment by betalars** [comment] 2021-12-02 10:55
> However, I can see that it's forcibly set to `false` for files that do not have an existing `.import` _file_ (not to be confused with the top-level `.import/` folder):

Is there a way to override that for users?

**Comment by Calinou** [comment] 2021-12-02 15:24
> Is there a way to override that for users?

Select the glTF file in the FileSystem dock, go to the Import dock, check **Use Legacy Names** and click **Reimport**:

![image](https://user-images.githubusercontent.com/180032/144451237-2f4a9a12-925a-4923-a177-4f08fcbf0dc9.png)

I can confirm that it's disabled for newly imported glTF scenes, as I said above.

**Comment by betalars** [comment] 2021-12-04 17:41
> I can confirm that it's disabled for newly imported glTF scenes, as I said above.

Just to confirm: this means if I first imported an glTF with an older version of godot, that checkbox can work, but if godot 3.4 was running while I added that file to my project the legacy-names checkbox won't work no matter what.

Because currently it is not working no matter what.

**Comment by akien-mga** [comment] 2021-12-12 11:29
See #55796, there was indeed a regression in 3.4-stable which made the `nodes/use_legacy_names` option not functional, since it wouldn't see the regex module as available.

This was fixed by #54911 which is included in 3.4.1.

You can either reimport models with 3.4.1 RC 2 or 3.3.4 stable and they should have the legacy names, unless the option is disabled.

**Closed by akien-mga** 2021-12-12 11:29 UTC
Labels: bug, confirmed, topic:import, regression, topic:3d

**Comment by RockyMadio** [comment] 2021-12-19 18:55
Thank you.

Those compression options will make the meshes load faster during runtime?

**Comment by Calinou** [comment] 2021-12-19 21:19
> Those compression options will make the meshes load faster during runtime?

Mesh compression is mostly about improving rendering performance and reducing battery usage on mobile platforms. It's unlikely to affect loading times.

**Comment by Calinou** [comment] 2022-02-26 18:46
> Is this issue already solved in the new/current build?

No, see https://github.com/godotengine/godot/issues/56447.

**Comment by RockyMadio** [comment] 2022-02-26 18:50
> No, see #56447.

Thank you
