### ISSUE TITLE
engine crashes while baked lightmap calculates light

### ISSUE THREAD

**Issue by stdgn** [godotengine/godot#49036] opened 2021-05-24 17:14 UTC
**System:** Windows 10
**Version:** 3.3.1

Engine crashes while calculating light when there are 2 or more identical objects in Gles 2. 
(seemed like a bug to me)

**Comment by akien-mga** [comment] 2021-05-24 17:17
Duplicate of #48822.

Stay tuned for 3.3.2 which will be released in a few hours and solves this.

**Closed by akien-mga** 2021-05-24 17:17 UTC
