### ISSUE TITLE
OpenGL validation error related to sampler depth comparisons when starting the editor with `--verbose`

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#85962] opened 2023-12-09 14:18 UTC
### Tested versions

- Reproducible in: 4.2.beta1, 4.2.stable, 4.2.1.rc1
- Not reproducible in: Versions earlier than 4.2.beta1, as they don't feature working 3D directional shadows in OpenGL.

### System information

Godot v4.2.rc (b3a0e077e) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.129.03) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Opening a 3D editor on an empty project:

```
drivers/gles3/rasterizer_gles3.cpp:176 - GL ERROR: Source: OpenGL	Type: Undefined behavior	ID: 131222	Severity: Medium	Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons enabled, with a texture object (1018) with a depth format, by a shader that samples it with a non-shadow sampler. Using this state to sample would result in undefined behavior
```

Running the 3D platformer demo directly with `--verbose`:

```
ERROR: GL ERROR: Source: OpenGL Type: Undefined behavior        ID: 131222      Severity: Medium        Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons enabled, with a texture object (122) with a depth format, by a shader that samples it with a non-shadow sampler. Using this state to sample would result in undefined behavior
at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:176)
```

The error message is the same, but the texture ID differs (it's the same every run still).

### Steps to reproduce

- Create a new project using the Compatibility rendering method.
- Open the project in the editor with `--verbose` on the [command line](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

This can be automated as follows:

```bash
mkdir -p /tmp/dir
touch /tmp/dir/project.godot
godot /tmp/dir/project.godot --verbose
```

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment] 2023-12-09 19:21
Duplicate of https://github.com/godotengine/godot/issues/84558

Closing in favour of https://github.com/godotengine/godot/issues/84558

**Closed by clayjohn** 2023-12-09 19:21 UTC
Labels: bug, topic:rendering, topic:3d
