### ISSUE TITLE
Broken GLES2 render in Godot 3.4 and later on iOS due to Octahedral Compression

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#57322] opened 2022-01-27 18:38 UTC
### Godot version

3.4.2 and 3.5 beta 1

### System information

iOS 15.2.1 / iPhone SE / OpenGL ES 2.0 Renderer: Apple A9 GPU

### Issue description

When running the game on iOS, GLES2 rendering does not work correctly.
I tried a variety of render settings, re-imported everything several times, but nothing helped.
I have tried all versions of Godot since 3.4 to check at what point the rendering started to work incorrectly, however, in all versions the situation is the same.

On the video you can track the process of how it looks.

https://user-images.githubusercontent.com/13809475/151420521-a01c91e0-bb55-4235-9335-593ddb72cc9f.mp4

Also here are some screenshots. Sorry for the quality, I didn't make it.
![Shotcut_00_00_16_533](https://user-images.githubusercontent.com/13809475/151420777-659273d4-d171-49d4-ad9f-c353f4ce74c7.png)

![Shotcut_00_00_03_467](https://user-images.githubusercontent.com/13809475/151420765-f9c573e6-9273-4fb2-b23b-b367c1fa9f42.png)

![Shotcut_00_00_36_067](https://user-images.githubusercontent.com/13809475/151420798-191379d4-2177-4995-b465-c435b38d9997.png)

Runs from Xcode

![xcode](https://user-images.githubusercontent.com/13809475/151420923-b8130aad-9915-4f7c-9ac2-c77110b47f55.jpg)

This project works great on Android, Windows, Linux, MacOS but is completely broken on iOS.
Switching to GLES3 solves this problem, but the game starts to work very slowly (FPS drops a lot).

When starting the project, the console outputs this

```
*********** main.m
running app main
Path: /var/containers/Bundle/Application/141C6F1F-C05D-41A4-BAFE-8B9F9C1B4C81/Bunker.app
godot_iphone /var/containers/Bundle/Application/141C6F1F-C05D-41A4-BAFE-8B9F9C1B4C81/Bunker.app/Bunker
cwd /private/var/containers/Bundle/Application/141C6F1F-C05D-41A4-BAFE-8B9F9C1B4C81/Bunker.app
os created
setting data dir to /var/mobile/Containers/Data/Application/E8A36F7A-E7D7-49B6-AA65-3296D3C7DC04/Documents from /var/mobile/Containers/Data/Application/E8A36F7A-E7D7-49B6-AA65-3296D3C7DC04/Documents
setup 0
2022-01-27 19:12:00.839936+0300 Bunker[1369:282913] Metal API Validation Enabled
2022-01-27 19:12:00.977090+0300 Bunker[1369:282913] Setting up an OpenGL ES 2.0 context.
2022-01-27 19:12:00.977381+0300 Bunker[1369:282913] failed to make complete framebuffer object 8cd6
2022-01-27 19:12:00.977430+0300 Bunker[1369:282913] Failed to create frame buffer!
******** setting up keyboard input view
******** adding observer for keyboard show/hide

start animation!
2022-01-27 19:12:01.018063+0300 Bunker[1369:282913] ERROR: AudioOutputUnitStart failed, code: -50
2022-01-27 19:12:01.018145+0300 Bunker[1369:282913]    at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
2022-01-27 19:12:01.025181+0300 Bunker[1369:282913] Godot Engine v3.5.beta1.official.b9b23d222 - https://godotengine.org
Godot Engine v3.5.beta1.official.b9b23d222 - https://godotengine.org
2022-01-27 19:12:01.030797+0300 Bunker[1369:282913] OpenGL ES 2.0 Renderer: Apple A9 GPU
OpenGL ES 2.0 Renderer: Apple A9 GPU
2022-01-27 19:12:01.202877+0300 Bunker[1369:282913] 
```

When switching to a game scene with a loaded 3D level

```
(servers/visual/visual_server_scene.cpp:731) - Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
ERROR: Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
   at: instance_set_surface_material (servers/visual/visual_server_scene.cpp:731) - Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
2022-01-27 19:12:39.319028+0300 Bunker[1369:282913] ERROR: Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
2022-01-27 19:12:39.319089+0300 Bunker[1369:282913]    at: instance_set_surface_material (servers/visual/visual_server_scene.cpp:731) - Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
ERROR: Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
   at: instance_set_surface_material (servers/visual/visual_server_scene.cpp:731) - Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
```

Endless spamming of bugs to the console (shown in the video video) throughout the game.

```
2022-01-27 19:16:12.030526+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.047285+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.065636+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.080681+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.097296+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.114506+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.130409+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.146974+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.164081+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.181806+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.197300+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.213994+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.230584+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.247444+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.264062+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.281690+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.298460+0300 Bunker[1369:282913] DrawView: 500 error
2022-01-27 19:16:12.314070+0300 Bunker[1369:282913] DrawView: 500 error
```

### Steps to reproduce

Download and open the project from the archive.

The minimum project contains the most complete script for building the game.

Main level in res://levels/level_0.tscn

Rendering takes place on the scene res://scenes/game.tscn

### Minimal reproduction project

[Bunker_21.zip](https://github.com/godotengine/godot/files/7959387/Bunker_21.zip)

**Comment by Calinou** [comment] 2022-01-27 19:10
> I have tried all versions of Godot since 3.3 to check at what point the rendering started to work incorrectly, however, in all versions the situation is the same.

This statement contradicts the issue title, which says that this issue only affects Godot 3.4.2 and later.

**Comment by SkanerSoft** [comment] 2022-01-27 19:18
I apologize, I mistyped, it should indicate 3.4.
Corrected.
I tried 3.4, 3.4.1, 3.4.2 and 3.5 (beta 1).

**Comment by Calinou** [comment] 2022-01-27 19:21
@SkanerSoft Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by SkanerSoft** [comment] 2022-01-27 19:48
I'll try. It seems to me that if the problem exists in both 3.4 and 3.5, then intermediate versions between them will also contain it...

Well, it's time to download export templates =)

I will add the results only tomorrow, since the export templates for one version are downloaded for about 45 minutes.

**Comment by Calinou** [comment] 2022-01-27 20:52
> I'll try. It seems to me that if the problem exists in both 3.4 and 3.5, then intermediate versions between them will also contain it...

3.4 betas and RCs were released *before* 3.4.stable.

**Comment by lawnjelly** [comment] 2022-01-28 09:14
Octahedral compression? #46800
That's biggest change in 3D around then that springs to mind, and I don't know how tested it was on all hardware.

**Comment by akien-mga** [comment] 2022-01-28 09:43
> I tried 3.4, 3.4.1, 3.4.2 and 3.5 (beta 1).

It's still not clear to me whether you tried Godot 3.3.x and it works fine there?

It's important to know if the issue is new in 3.4+ (i.e. a regression), or if the issue has always existed (in which case testing intermediate releases as suggested in https://github.com/godotengine/godot/issues/57322#issuecomment-1023561703 will not be of any use).

**Comment by SkanerSoft** [comment] 2022-01-28 09:43
Objects are not animated, they break randomly. Some belong to the GridMap and some do not.
You can try downloading the minimal project to see it from the inside.

Now my tests on previous versions.

3.4 beta 1 won't launch due to not being able to check file security on my mac.
```
The "Godot.app" file cannot be opened because Apple cannot scan it for malware.
This software needs to be updated. Contact the developer for details.
```

3.4 beta 2
The project does not work correctly, or it gives an error when launched (see screenshot).
![Снимок экрана 2022-01-28 в 12 35 11](https://user-images.githubusercontent.com/13809475/151523261-cf3be442-d13d-428c-b724-c4bae612a651.png)


3.4 beta 3
Looking forward to downloading the export templates. The speed is very low ... I will write later.

**Comment by SkanerSoft** [comment] 2022-01-28 09:49
> > I tried 3.4, 3.4.1, 3.4.2 and 3.5 (beta 1).
> 
> It's still not clear to me whether you tried Godot 3.3.x and it works fine there?


3.3 can't open project, everything looks broken. Some of the models are not displayed. The feeling that something is not supported in it from what is in the project. And there is no way to create the game again in the old version, since this is a very large project.

**Comment by SkanerSoft** [comment] 2022-01-28 09:54
The project has been made for more than a year, it has a lot of models, details that will be very difficult to re-import again, since you will have to re-create every 3D object in the game. This is an unbearable amount, because the project has long existed for the players.

**Comment by lawnjelly** [comment] 2022-01-28 09:56
Everytime you try a new version, it's probably a good idea to delete your .import folder and let the IDE reimport everything.

It is highly possible the problem is happening via the imported resources. That error in 3.4 beta 2 could be from using later imported assets with an earlier version of the engine.

**Comment by SkanerSoft** [comment] 2022-01-28 10:06
Yes, I delete import files before each opening. However, the project does not start. In addition, it looks incorrect in the editor itself (for version 3.4 beta 2).
Version 3.4 beta 3 is just downloading. Internet speed is extremely slow...

**Comment by SkanerSoft** [comment] 2022-01-28 10:13
> And don't panic
I understand. Thanks. It's just that the game has a huge audience (millions of people) on Android, and many players have asked for iPhone support, which I can't provide because of this...
I would like to use the 3.5+ features to provide the best experience for the players. As soon as I download 3.4 beta 3, I will share the results of testing. For 3.4 beta 2, everything is bad.

**Comment by lawnjelly** [comment] 2022-01-28 10:46
I'm guessing you have access to the Mac and iPhone there which is helpful. Am looking at the project now trying to work out some likely culprits.

Some things I would try in project settings, to at least eliminate them as the cause:

* `rendering->threads->thread_model` change this to to single_safe. multithreaded is not as well tested.
* `rendering->gles2->compatibility->disable_half_float` set this to on, just in case the iOS override isn't working for some reason (half float will cause this kind of bug)
* `rendering->limits->buffers` set these to defaults
* `rendering->misc->split_stream` worth a try just in case it fixes some bug in the octahedral

It looks like the octahedral vertex compression may be difficult to test, because there is no global on / off switch that I can see. You can turn it on and off in the import settings for a mesh, but your meshes seem to be baked into tscn files, so I don't know if it is possible to edit their vertex format (I'm not familiar with the importing etc).

One thing you could try it a new project and just try a mesh either imported with and without octahedral, and see if it works on the device in both cases.

**Comment by SkanerSoft** [comment] 2022-01-28 11:53
Version 3.4 beta 3 produces the same result.
![Снимок экрана 2022-01-28 в 14 51 18](https://user-images.githubusercontent.com/13809475/151542503-526c1f4b-194d-4d76-ab86-7890e02beeb4.png)

Now I will try to enter the settings that you said to check everything. It will be long... =)

**Comment by SkanerSoft** [comment] 2022-01-28 14:16
For today I give up. The project did not start in any intermediate version. Buffer errors everywhere.

As a result, I again reached version 3.5 beta 1

I left only one mesh (ground) on the stage and the project still did not start. And now it finally crashes, without even reaching the render.

![Снимок экрана 2022-01-28 в 17 13 14](https://user-images.githubusercontent.com/13809475/151562084-5a5cf762-3b67-47d8-9624-283a8fff26ea.png)


Ошибки в консоли при попытке запуска.

```
*********** main.m
running app main
Path: /var/containers/Bundle/Application/8948DA8A-051A-45C6-959F-C103D336ECCE/Bunker_22.app
godot_iphone /var/containers/Bundle/Application/8948DA8A-051A-45C6-959F-C103D336ECCE/Bunker_22.app/Bunker_22
cwd /private/var/containers/Bundle/Application/8948DA8A-051A-45C6-959F-C103D336ECCE/Bunker_22.app
os created
setting data dir to /var/mobile/Containers/Data/Application/0A128652-C84B-49FE-B0D6-51A4A6526B21/Documents from /var/mobile/Containers/Data/Application/0A128652-C84B-49FE-B0D6-51A4A6526B21/Documents
setup 0
2022-01-28 16:36:57.202697+0300 Bunker_22[509:25076] Metal API Validation Enabled
2022-01-28 16:36:57.340939+0300 Bunker_22[509:25076] Setting up an OpenGL ES 2.0 context.
2022-01-28 16:36:57.341241+0300 Bunker_22[509:25076] failed to make complete framebuffer object 8cd6
2022-01-28 16:36:57.341290+0300 Bunker_22[509:25076] Failed to create frame buffer!
******** setting up keyboard input view
******** adding observer for keyboard show/hide
start animation!
2022-01-28 16:36:57.378979+0300 Bunker_22[509:25076] ERROR: AudioOutputUnitStart failed, code: -50
2022-01-28 16:36:57.379070+0300 Bunker_22[509:25076]    at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
2022-01-28 16:36:57.382773+0300 Bunker_22[509:25076] Godot Engine v3.5.beta1.official.b9b23d222 - https://godotengine.org
Godot Engine v3.5.beta1.official.b9b23d222 - https://godotengine.org
2022-01-28 16:36:57.394280+0300 Bunker_22[509:25076] OpenGL ES 2.0 Renderer: Apple A9 GPU
OpenGL ES 2.0 Renderer: Apple A9 GPU
2022-01-28 16:36:57.569652+0300 Bunker_22[509:25076] 
 
2022-01-28 16:36:58.566629+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
2022-01-28 16:36:58.566812+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
2022-01-28 16:36:58.567249+0300 Bunker_22[509:25297] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)}
2022-01-28 16:36:58.567843+0300 Bunker_22[509:25076] DrawView: 500 error
2022-01-28 16:36:58.585304+0300 Bunker_22[509:25076] DrawView: 500 error
2022-01-28 16:36:58.588912+0300 Bunker_22[509:25293] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
2022-01-28 16:36:58.589062+0300 Bunker_22[509:25293] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)
2022-01-28 16:36:58.589391+0300 Bunker_22[509:25293] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (00000003:kIOGPUCommandBufferCallbackErrorHang)}
2022-01-28 16:36:58.599696+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
2022-01-28 16:36:58.599860+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
2022-01-28 16:36:58.599930+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
2022-01-28 16:36:58.599976+0300 Bunker_22[509:25297] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
2022-01-28 16:36:58.600087+0300 Bunker_22[509:25297dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib
] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=4 "Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)" UserInfo={NSLocalizedDescription=Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)}
2022-01-28 16:36:58.600247+0300 Bunker_22[509:25076] Terminating due to blacklisting by kernel driver
```

**Comment by SkanerSoft** [comment] 2022-01-28 14:33
The smallest project.

[Bunker_21.zip](https://github.com/godotengine/godot/files/7959387/Bunker_21.zip)

**Comment by SkanerSoft** [comment] 2022-01-29 11:21
So, I tried to re-import new models that were created in the same way as the previous ones.
This time I imported the same model with different parameters and the result showed up immediately.

The screenshot shows the two models and the differences in settings (yes, just one tick).
![1643452117](https://user-images.githubusercontent.com/13809475/151658848-48767aac-139d-4a49-95fa-435f9843af47.png)


And now how it looks on the phone.


https://user-images.githubusercontent.com/13809475/151659005-12554eaa-0b41-4e04-bb22-e1ee457b8c7d.mp4

**Comment by SkanerSoft** [comment] 2022-01-29 11:22
@lawnjelly  If this can be fixed without re-importing all game assets, that would be great. Because the game is displayed normally everywhere, except for the iPhone...

**Comment by SkanerSoft** [comment] 2022-01-29 15:07
I will wait for Monday to get some answer on the solution.

**Comment by clayjohn** [comment] 2022-01-29 16:54
Cc @The-o-king

**Comment by SkanerSoft** [comment] 2022-01-29 18:38
Ok, I spent a whole day testing and yes, it is 100% "Octahedral Compression", after re-creating the assets and re-importing into the game with "Octahedral Compression" disabled, the whole game began to display correctly on all devices. Apparently, there are many weeks ahead of recreating gaming assets... well, the reason has become clear. Hope this bug gets fixed.
As a recommendation, you can turn it off by default, since many people have no idea about such subtleties and the technical side of the issue.

**Comment by akien-mga** [comment] 2022-01-31 19:15
@SkanerSoft I might be missing something as I'm not very familiar with this asset pipeline, but why would you need to recreate your assets to work this around? Isn't it sufficient to re-import all your models with Octahedral Compression disabled? I.e. select all 3D assets (glTF, Collada, etc.), go to import tab, untick the option and press "Re-Import".

**Comment by SkanerSoft** [comment] 2022-01-31 20:57
@akien-mga The trouble is that my assets do not lie in the form of separate files.  They are literally inside tscn files... It was my mistake when I originally designed the game's architecture)

**Comment by lawnjelly** [comment] 2022-02-01 07:13
> @akien-mga The trouble is that my assets do not lie in the form of separate files. They are literally inside tscn files... It was my mistake when I originally designed the game's architecture)

I don't know if this works as I didn't know it existed, but if you look in `project_settings/import_defaults` tab, and select importer `Scene`, there is a checkbox for octahedral compression. Sounds worth a try at least, maybe this will re-import meshes in the tscn files?

**Comment by SkanerSoft** [comment] 2022-02-01 11:31
The tscn files are not imported at all, so this won't work.
Of course, I immediately unchecked the compression box, only now for all game objects I will have to repeat "open blender -> export object -> open Godot -> import glTF -> copy mesh -> paste mesh into the desired object -> save -> rebake the shadows"...

Inside my scenes are meshes already imported and modified by the engine.

**Comment by Zireael07** [comment] 2022-02-01 11:55
I don't get it... WHY are your gltf in your scene files?

**Comment by SkanerSoft** [comment] 2022-02-01 12:24
Ok, look this =)

[test.zip](https://github.com/godotengine/godot/files/7978390/test.zip)

**Comment by akien-mga** [comment] 2022-02-01 13:43
> UPD: This makes the project cleaner, there are no heaps of extra files. Plus less redundant information.

It's tangential to this issue (octahedral compression needs to be fixed not to produce these bugs), but be aware that with this practice you are saving 3D mesh data as *text* in tscn files, when you could be using it from binary data in .glb, with a lot more flexibility to reimport everything on the fly if you need to change anything (like import settings here, or modify your mesh data, animations, etc.).

I don't have the original glb to compare, but see here the extra size that you get in a `.tscn` file from encoding mesh data as a byte array (the .tscn file has lines with 1 million characters). I converted it to `.scn` for comparison (the size of `.tscn` + `.glb` should be similar to that `.scn`):
```
-rw-r--r-- 1 akien akien 168K Feb  1 14:39 kosmonavt_1.scn
-rw-r--r-- 1 akien akien 1,2M Feb  1  2022 kosmonavt_1.tscn
```

**Comment by akien-mga** [comment] 2022-02-01 13:44
BTW, since the issue is specific to iOS, you could also test to see if the `compatibility/disable_half_float.iOS` project setting makes a difference. It might be that octahedral compression requires half float support to work well (but in turns half float seem to create issues on some iOS devices).

**Comment by SkanerSoft** [comment] 2022-02-01 15:04
> compatibility/disable_half_float.iOS

Tried it didn't help.




> data in .glb

Yes, I already understood that it is better to store all objects next to the scenes. There will be more files, and a little less ease of editing (glb cannot be edited in the engine (for example, duplicate some object inside (for example, a tree in a forest or a chandelier in an apartment, if a forest or apartment is a single glb))),

**Comment by The-O-King** [comment] 2022-02-02 06:51
Hello! Sorry I just saw this right now (not sure how I missed the notification before) but I'll see if I can look into this by the end of the week - so after reading the thread my understanding is that when the project is opened directly as it is stored in the .zip file, in even the latest version of Godot, when exported to the iPhone, things are broken? But reimporting the assets without octahedral compression makes things work again? Is that correct?


So I think we may be looking at two problems: 
1. In general octahedral compression does not work on iPhone under GLES2
2. There is an issue where a project being opened up which was not using octahedral compression on it's assets has broken rendering (perhaps somewhere a flag is being set which is making the renderer think octahedral is being used on these assets when it should not)

Is this the most recent minimal example of the bug found at this comment https://github.com/godotengine/godot/issues/57322#issuecomment-1024280728? 

I didn't have an iPhone to test octahedral compression on during it's development to run into this issue, but I may be able to access a mac/iPhone later on and see if I can reproduce this (not sure if I will have access to anything as old as an A9 though)

Let me know if I've missed anything

**Comment by SkanerSoft** [comment] 2022-02-02 08:22
[test.zip](https://github.com/godotengine/godot/files/7984682/test.zip)

Hey! Here is an exact example, there are two objects, they are signed in the scene, one with compression and one without it.
Here are screenshots of what it looks like on iPhone and Android.
This time I took my wife's Android, and it turned out that her phone also had problems. There are no such problems on my Android. I have nokia 7.1.

On the iPhone, the second model is not displayed at all, and after about 10 seconds, the game crashes with an error accessing something.

![1643786898](https://user-images.githubusercontent.com/13809475/152118009-2b85e2c3-21fb-45ea-aaac-f0dbedb69224.png)

**Comment by SkanerSoft** [comment] 2022-02-02 08:29
It may be easier for you to find access to an Android phone (eg Samsung M12), and if you can fix the problem on it, it may (but not sure) fix the problem on the iPhone as well. This is just a guess.

**Comment by akien-mga** [comment] 2022-02-02 08:46
> So I think we may be looking at two problems:
>
> 1. In general octahedral compression does not work on iPhone under GLES2

That seems correct, at least for some iPhones. Might be useful to get test results from more iPhone models to confirm.

What @SkanerSoft tested so far seems to be an iPhone SE 2016 (A9 APU): https://www.gsmarena.com/apple_iphone_se-7969.php
(i.e. not the current iPhone SE 2020 with A13 APU: https://www.gsmarena.com/apple_iphone_se_(2020)-10170.php)

> 2. There is an issue where a project being opened up which was not using octahedral compression on it's assets has broken rendering (perhaps somewhere a flag is being set which is making the renderer think octahedral is being used on these assets when it should not)

I'm not sure about that one, maybe @SkanerSoft can confirm. I think the affected geometry might have all been imported *after* octahedral compression was added to the engine and enabled by default. The main issue @SkanerSoft is having is that since their workflow involves converting the geometry into Godot's own format, it cannot be reimported easily and thus the only available geometry is the octahedral compressed one.

**Comment by SkanerSoft** [comment] 2022-02-02 09:06
Please also note that in this project, the astronaut models were first imported into Godot 3.5 Beta 1, and compression also broke their rendering.

Unfortunately, I didn't know before, but it turns out to be broken on some Androids as well. And not all models break.

What I have noticed so far:

1. [Android] Compression is 100% broken for animated models (example in test.zip archive), other models are displayed normally both with and without compression.

Example
https://github.com/godotengine/godot/files/7984682/test.zip

2. [iPhone SE] Some animated models break (but not all), the rest of the models are displayed broken in 90% of cases, another 10% are not displayed at all and cause two options for verification:
- Infinite error 500
- Game crash with access error.

Example
https://github.com/godotengine/godot/files/7984788/min_project.zip

If you turn off compression, then on all devices all models (with and without animation) are displayed completely correctly and do not cause errors.

**Comment by The-O-King** [comment] 2022-02-02 15:55
Ok one thing I can bring up right now at least is that there's another issue open on Android devices with Mali GPUs which causes issues with rendering of animated meshes, and the Samsung M12 has one of these gpus :/ - although I have not found a way to resolve it or truly confirm the driver bug yet (see this issue https://github.com/godotengine/godot/issues/54763)

**Comment by SkanerSoft** [comment] 2022-02-03 08:57
There was a thought. Is there a way to disable "Octahedral Compression" not at the import level, but at the project settings level?
So that the tuning engine can completely ignore it altogether.

Or, if the model was imported with compression, then the engine can use it ONLY with it and nothing else?

Something like "ignore Octahedral Compression" or "disable Octahedral Compression" could be added to the settings.

I guess a lot of users could import their models without being aware of this error... like me =)

**Comment by Calinou** [comment] 2022-02-03 17:08
> There was a thought. Is there a way to disable "Octahedral Compression" not at the import level, but at the project settings level?

Since Godot 3.3, you can change the import defaults in the project settings. They will only take effect when (re)importing resources in the future.

**Comment by SkanerSoft** [comment] 2022-02-03 17:22
@Calinou 

Unfortunately, some of my assets were created over a year ago and I just don't have the files to re-import them. I'll have to recreate them, which will take me weeks... there are a lot of objects in the game.

I recommend reading the entire discussion so that I do not repeat myself.

**Comment by Calinou** [comment] 2022-02-03 17:36
> Unfortunately, some of my assets were created over a year ago and I just don't have the files to re-import them. I'll have to recreate them, which will take me weeks... there are a lot of objects in the game.

By definition, octahedral compression is a destructive operation. It's not possible to simply disable it on meshes that were already imported with octahedral compression enabled.

**Comment by SkanerSoft** [comment] 2022-02-03 17:41
At some point, I discovered an amazing way to store game assets right in scenes, without even knowing that all my models are broken for some situations =)

I'm not upset or angry, I just feel bad that I have to spend a lot of time to revive the game for iOS =(


![1643909863](https://user-images.githubusercontent.com/13809475/152398086-49cd8775-8c9d-4b2c-9868-ecddda5a8132.png)

**Comment by Zireael07** [comment] 2022-02-03 17:53
> By definition, octahedral compression is a destructive operation. It's not possible to simply disable it on meshes that were already imported with octahedral compression enabled.

In that case, octahedral compression should default to OFF (with a big warning that it is destructive!)

**Comment by Calinou** [comment] 2022-02-03 18:01
> In that case, octahedral compression should default to OFF (with a big warning that it is destructive!)

It is only destructive if you remove your source resources, which you should never do since Godot 3.0 – it's not a supported workflow anymore.

**Comment by SkanerSoft** [comment] 2022-02-03 18:17
In most cases, users are unaware of the presence of compression at all. For example, me =)
I found out about this a year later, when the game refused to work on iOS. At this point, I have successfully imported meshes and saved them into scenes. I would remove this option from the default by making it disabled. Too unstable.
Let it be included by those who understand what they are doing.

**Comment by Calinou** [comment] 2022-02-03 18:19
> In most cases, users are unaware of the presence of compression at all. For example, me =) I found out about this a year later, when the game refused to work on iOS. At this point, I have successfully imported meshes and saved them into scenes. I would remove this option from the default by making it disabled. Too unstable. Let it be included by those who understand what they are doing.

Considering the benefits of octahedral compression have yet to be proven, I'd vouch for removing it entirely rather than disabling it by default in 3.5.

**Comment by The-O-King** [comment] 2022-02-06 02:25
Apologies for the delay, I have been learning how to use xcode/develop on mac/ios for the past day or so haha (thanks to my friend for letting me use their apple devices to dig into this!)


Ok so some progress - I think I found the issue causing all of those `DrawView: 500 errors` - it's actually not the octahedral compression (surprise!); in my implementation of split stream vertex buffers, I seem to have missed setting the `uses_half_float` flag in rasterizer_storage_gles2.cpp when checking the format for compressed vertex positions - this is causing an `invalid enum` and resulting in the messed up rendering seen in the first


As for the rendering artifacts seen on the character models in the minimal scene, those may be caused by octahedral, but I have not been able to reproduce that on the iphone that I have access to (iPhone 13 pro) - I am curious though if anything changes in the rendering after the half_float fix is merged in - I'll see if I can dig into this aspect of it though and see if I can reproduce


and just as a quick response to the usefulness of octahedral compression - while I recognize the performance and battery life claims have not necessarily actualized in real world projects (just the benchmarks I've made), I would like to also point out that there is also a large visual quality improvement in using octahedral compression (almost ground truth level quality for the same cost as the old compression technique) so there is value there too; I'm a bit confused how loading octahedral compressed meshes could work if you couldn't import your meshes as octahedral compressed in godot to create them in the first place (there are no 3D modelling packages I'm aware of that export octahedral compressed meshes)

**Comment by SkanerSoft** [comment] 2022-02-06 09:13
@The-O-King 

This is good news! I'm glad there's progress! I can run tests if you provide any interim builds with fixes!

As for rendering artifacts (characters with animation), you can try to reproduce this on Android, they are also observed on it.

From myself, I can conduct tests on both iPhone (A9) and Samsung (Mali).

**Comment by akien-mga** [comment] 2022-04-30 15:13
Do you still reproduce the same issue in 3.5 beta 4 or later? There were various fixes to octahedral compression in the past few betas.

**Comment by Calinou** [comment] 2022-05-28 14:52
@SkanerSoft Bump :slightly_smiling_face:

**Comment by akien-mga** [comment] 2022-06-10 09:40
Assuming fixed, please comment if the issue is still reproducible.

**Closed by akien-mga** 2022-06-10 09:40 UTC
Labels: bug, platform:ios, topic:rendering, confirmed, regression, topic:3d

**Comment by SkanerSoft** [comment] 2022-06-10 09:56
Good afternoon! The problem has now been fixed!
