### ISSUE TITLE
Controls with size flags horizontal & vertical `SIZE_EXPAND_FILL` do not fill `GridContainer`

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#63142] opened 2022-07-18 10:28 UTC
### Godot version

3.4.4.stable.arch_linux

### System information

ArchLinux x11

### Issue description

![image](https://user-images.githubusercontent.com/70787919/179493054-ba53f677-a656-4a8f-8baf-9bcf8711db4d.png)

### Steps to reproduce

- open provided scene
- click `GridContainer`
- view issue

### Minimal reproduction scene

```
[gd_scene format=2]

[node name="GridContainer" type="GridContainer"]
margin_right = 300.0
margin_bottom = 300.0
rect_min_size = Vector2( 300, 300 )
rect_pivot_offset = Vector2( -72, -48 )
custom_constants/vseparation = 0
custom_constants/hseparation = 0
columns = 8

[node name="ColorRect" type="ColorRect" parent="."]
margin_right = 37.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 336, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect2" type="ColorRect" parent="."]
margin_left = 37.0
margin_right = 74.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 299, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect3" type="ColorRect" parent="."]
margin_left = 74.0
margin_right = 111.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 262, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect4" type="ColorRect" parent="."]
margin_left = 111.0
margin_right = 148.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 225, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect5" type="ColorRect" parent="."]
margin_left = 148.0
margin_right = 185.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 188, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect6" type="ColorRect" parent="."]
margin_left = 185.0
margin_right = 222.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 151, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect7" type="ColorRect" parent="."]
margin_left = 222.0
margin_right = 259.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 114, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect8" type="ColorRect" parent="."]
margin_left = 259.0
margin_right = 296.0
margin_bottom = 37.0
rect_pivot_offset = Vector2( 77, -48 )
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect9" type="ColorRect" parent="."]
margin_top = 37.0
margin_right = 37.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect10" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 37.0
margin_right = 74.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect11" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 37.0
margin_right = 111.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect12" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 37.0
margin_right = 148.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect13" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 37.0
margin_right = 185.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect14" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 37.0
margin_right = 222.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect15" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 37.0
margin_right = 259.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect16" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 37.0
margin_right = 296.0
margin_bottom = 74.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect17" type="ColorRect" parent="."]
margin_top = 74.0
margin_right = 37.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect18" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 74.0
margin_right = 74.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect19" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 74.0
margin_right = 111.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect20" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 74.0
margin_right = 148.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect21" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 74.0
margin_right = 185.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect22" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 74.0
margin_right = 222.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect23" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 74.0
margin_right = 259.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect24" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 74.0
margin_right = 296.0
margin_bottom = 111.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect25" type="ColorRect" parent="."]
margin_top = 111.0
margin_right = 37.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect26" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 111.0
margin_right = 74.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect27" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 111.0
margin_right = 111.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect28" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 111.0
margin_right = 148.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect29" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 111.0
margin_right = 185.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect30" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 111.0
margin_right = 222.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect31" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 111.0
margin_right = 259.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect32" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 111.0
margin_right = 296.0
margin_bottom = 148.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect33" type="ColorRect" parent="."]
margin_top = 148.0
margin_right = 37.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect34" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 148.0
margin_right = 74.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect35" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 148.0
margin_right = 111.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect36" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 148.0
margin_right = 148.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect37" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 148.0
margin_right = 185.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect38" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 148.0
margin_right = 222.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect39" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 148.0
margin_right = 259.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect40" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 148.0
margin_right = 296.0
margin_bottom = 185.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect41" type="ColorRect" parent="."]
margin_top = 185.0
margin_right = 37.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect42" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 185.0
margin_right = 74.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect43" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 185.0
margin_right = 111.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect44" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 185.0
margin_right = 148.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect45" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 185.0
margin_right = 185.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect46" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 185.0
margin_right = 222.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect47" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 185.0
margin_right = 259.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect48" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 185.0
margin_right = 296.0
margin_bottom = 222.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect49" type="ColorRect" parent="."]
margin_top = 222.0
margin_right = 37.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect50" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 222.0
margin_right = 74.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect51" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 222.0
margin_right = 111.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect52" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 222.0
margin_right = 148.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect53" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 222.0
margin_right = 185.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect54" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 222.0
margin_right = 222.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect55" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 222.0
margin_right = 259.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect56" type="ColorRect" parent="."]
margin_left = 259.0
margin_top = 222.0
margin_right = 296.0
margin_bottom = 259.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect57" type="ColorRect" parent="."]
margin_top = 259.0
margin_right = 37.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect58" type="ColorRect" parent="."]
margin_left = 37.0
margin_top = 259.0
margin_right = 74.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect59" type="ColorRect" parent="."]
margin_left = 74.0
margin_top = 259.0
margin_right = 111.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect60" type="ColorRect" parent="."]
margin_left = 111.0
margin_top = 259.0
margin_right = 148.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect61" type="ColorRect" parent="."]
margin_left = 148.0
margin_top = 259.0
margin_right = 185.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect62" type="ColorRect" parent="."]
margin_left = 185.0
margin_top = 259.0
margin_right = 222.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect63" type="ColorRect" parent="."]
margin_left = 222.0
margin_top = 259.0
margin_right = 259.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3

[node name="ColorRect64" type="Control" parent="."]
margin_left = 259.0
margin_top = 259.0
margin_right = 296.0
margin_bottom = 296.0
size_flags_horizontal = 3
size_flags_vertical = 3
```

**Comment by bend-n** [comment] 2022-07-18 11:58
It says cherrypick 3.4... why do i not have it

**Comment by akien-mga** [comment] 2022-07-18 11:59
It says 3.5, not 3.4.

Duplicate of https://github.com/godotengine/godot/issues/59780

**Closed by akien-mga** 2022-07-18 11:59 UTC
