### ISSUE TITLE
NavigationAgent ignores NavigationObstacle

### ISSUE THREAD

**Issue by Vosnov** [godotengine/godot#76670] opened 2023-05-02 09:59 UTC
### Godot version

4.0.2.stable.official

### System information

Windows 10, NVIDIA GeForce GTX 1660 SUPER, Vulkan

### Issue description

NavigationtArget doesn't find a workaround and tries to go through NavigationObstacle as if it doesn't exist. Avoidance enabled
= true. All settings by default. The problem is reproduced in both 2d and 3d

### Steps to reproduce

![image](https://user-images.githubusercontent.com/59560897/235634260-0fa1a1a3-7e2d-456f-8f3c-a73b07736ea8.png)
![image](https://user-images.githubusercontent.com/59560897/235634420-a20cf02c-5def-4fec-9455-2280deed80e3.png)

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11371953/Test.zip)

**Comment by AThousandShips** [comment] 2023-05-02 10:03
Does this happen if you don't set the target position every frame? You're not supposed to set it constantly as it recomputes the path

**Comment by AThousandShips** [comment] 2023-05-02 10:06
You also set a very high velocity when the distance is high, I suggest normalizing it

**Comment by smix8** [comment] 2023-05-02 10:09
Resetting the path every physics_frame with a new target_position is indeed a problem as it destroys any path consistence or direction.

I do not think that this is the main or only problem as the current avoidance resets every frame anyway so it lacks consistence in velocity as well.

If you can try testing with pr https://github.com/godotengine/godot/pull/69988 that fixes most of those issues.

**Comment by smix8** [comment] 2023-05-02 13:04
So I had time to test the project now. While using a NavigationObstacle for something static is in general not recommended it is not the main issue. The issue is that ...

a) The agent has a radius of 80 pixel but the NavigationAgent2D only has a radius of 10 pixel so it thinks it can move around the obstacle radius at that smaller size but gets stuck on physics collision.

b) NavigationObstacle2D `estimate_radius` is a useless property that fails a lot calculating a proper radius so it should not exist. This property gets removed in the linked avoidance rework for exactly such reasons. Set it to a manual radius a little larger than the size of your object so you have some avoidance margin. E.g. in my test 100 worked fine.

c) Since the avoidance will push the agent away from the ideal path it is also required to increase `path_desired_distance` and `path_max_distance` to avoid the agent resetting its path all the time which can make it get stuck. E.g. in my test 120 for path_max_distance  and 250  for path_max_distance worked fine.

**Comment by smix8** [comment] 2023-05-02 15:37
Properly due to https://github.com/godotengine/godot/pull/74893 which made it to 4.0.2 that affected obstacles which was fixed in 4.0.3 with https://github.com/godotengine/godot/pull/75756.

**Comment by Calinou** [comment] 2023-05-02 15:39
Closing per @smix8's comment, as this will be resolved in 4.0.3.

**Closed by Calinou** 2023-05-02 15:39 UTC
Labels: bug, topic:navigation
