### ISSUE TITLE
Addons in C# - multiple scripts are not loaded

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#28882] opened 2019-05-14 11:46 UTC
**Godot version:**
3.1 Mono

**OS/device including version:**
Windows 10

**Issue description:**
Related to #15237
If I create an addon (written in C#) which has more than one script file, only one file gets compiled. Others are not included in assembly.

**Steps to reproduce:**
- Create a simple plugin with a minimum of two .cs files. ```CustomNode.cs``` will be connected to a new node type and ```StaticMaster.cs``` can for example hold some singleton static logic.
- Compile. Addon works as it has to.
- Create a fresh empty project and copy this plugin into "addons" folder.
- Compile. Get error ```The type or namespace StaticMaster cannot be found```
- Manually add ```<Compile Include="StaticMaster.cs" />``` to .csproj. Compile. Works.

**Comment by aaronfranke** [comment] 2019-05-20 10:59
This is a well known problem, but it's a duplicate of https://github.com/godotengine/godot/issues/28882

**Comment by KoBeWi** [comment] 2020-08-18 18:47
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by aaronfranke** [comment] 2020-08-18 19:47
This is still a problem which hasn't been solved yet. It might be solved by 4.0 if we use the new csproj format.

**Comment by TechnoPorg** [comment] 2022-01-17 23:48
I can't reproduce this anymore. The related issue #12917 was closed by #37116, and I believe that fixed this issue as well.

**Closed** 2022-01-17 23:50 UTC
Labels: bug, topic:core, confirmed, topic:mono
