### ISSUE TITLE
GridMap: Thumbnails are not being generated

### ISSUE THREAD

**Issue by Alastor01** [godotengine/godot#25352] opened 2019-01-26 18:26 UTC
Godot version:
- 3.1 Beta 2

OS/device including version:
- OS - Windows 10 64-bit
- GPU - Nvidia GTX 1050 Ti (drivers up to date)

Issue description:
- When MeshLib is generated from a scene, no thumbnails are actually created - instead you get black squares which show in GridMap dock for your tiles

Steps to reproduce:
1) Model / unwrap and texture a sequence of 3D tiles to be used
2) Export all tiles to DAE / GLTF / OBJ / ESCN (I tried only DAE and ESCN)
3) Import in Godot as a scene, assign material if required, convert to MeshLib (Merge with existing - OFF)
4) Add Spatial Node as root node
5) Add GridMap as a child of Spatial, assign your .meshlib
6) Click on GridMap node and observe that all your tiles are shown as black squares

NOTE: This does NOT affect assets carried on from Godot 3.0.6 (stable) - .meshlib files made in Godot 3.0.6 seem to retain their thumbnails in Godot 3.1 Beta 2

Minimal reproduction project:
- Minimal project included for Godot 3.1 Beta 2 (all asset files can be used as you want)
[3D Test Project.zip](https://github.com/godotengine/godot/files/2799347/3D.Test.Project.zip)

**Comment by akien-mga** [comment] 2019-01-26 19:46
Duplicate of #24971, it's fixed in the current master branch, should be fixed in 3.1 beta 3.

**Closed by akien-mga** 2019-01-26 19:46 UTC
Labels: bug, topic:editor

**Comment by Alastor01** [comment] 2019-01-26 20:54
@akien-mga Thanks, can't wait to try Beta 3!
