### ISSUE TITLE
Internal Script Error! -opcode #38 when loading Resource derived class from disk

### ISSUE THREAD

**Issue by MagellanicGames** [godotengine/godot#43163] opened 2020-10-28 14:20 UTC
**Godot version:** 3.2.4 Beta 1

**OS/device including version:** Kubuntu 18.04

**Issue description:** When loading a resource it errors giving Internal Script Error! - opcode # 38 .

**Steps to reproduce:**

- Create a script that extends Resource and assign a class name
- Declare an exported variable

![image](https://user-images.githubusercontent.com/32498309/97447871-ed43e200-1927-11eb-9547-c2ce1f034314.png)

- Create a resource of that type and save as .tres
- load the tres in gdscript with the load() function

![image](https://user-images.githubusercontent.com/32498309/97448155-3eec6c80-1928-11eb-9da4-2a48317ae821.png)

**Minimal reproduction project:** [ResourceLoad.zip](https://github.com/godotengine/godot/files/5452411/ResourceLoad.zip)

Apologies if this already known, I had a search but couldn't find anything matching this issue.  I found this after trying out my latest released project in the beta.  It gave the error when loading a data class I use for enemies.  The code works no problems in 3.2.2.

**Comment by Calinou** [comment] 2020-10-28 14:26
Duplicate of https://github.com/godotengine/godot/issues/43042.

> Apologies if this already known, I had a search but couldn't find anything matching this issue

I found the original issue by searching for "opcode 38".

**Closed by Calinou** 2020-10-28 14:26 UTC
