### ISSUE TITLE
Make touch screen support InputEventMagnifyGesture.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31820] opened 2019-08-31 03:01 UTC
**Godot version:3.1

**OS/device including version:**

**Issue description:**

InputEventMagnifyGesture only works on macbook touch pad, it's a very common gesture on mobile device.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-02-18 20:00
Duplicate of #13139.

**Closed by Calinou** 2020-02-18 20:00 UTC
Labels: enhancement, topic:input
