### ISSUE TITLE
TileMap editor "Delete" shortcut not working

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#16293] opened 2018-02-01 19:12 UTC
**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
Whenever I attempt the CTRL-D or CTRL-B tilemap hotkeys they fail.
In the case of CTRL-D, the tilemap node is duplicated.

**Steps to reproduce:**
Open tilemap, attempt to select or duplicate tiles via hotkeys.

**Comment by wingedadventurer** [comment] 2018-03-11 20:09
Same issue here. My world building time has decreased several times because of this. 🙁

**Comment by JohnPablok** [comment] 2018-04-01 19:11
Same issue, apparently only the "Pick Tile" hotkey works.

**Comment by guilhermefelipecgs** [comment] 2018-04-03 19:36
@akien-mga This issue was already fixed on master branch. Tested with 9ad180029876a53747df577d8925a055f6b9687e

**Comment by akien-mga** [comment] 2018-04-03 20:07
Thanks - is it still reproducible in 3.0.2?

**Comment by guilhermefelipecgs** [comment] 2018-04-03 20:26
Yes, in 3.0.2 the hotkeys doesn't work yet.

**Comment by wingedadventurer** [comment] 2018-04-04 09:34
Like  @guilhermefelipecgs said, it's fixed in the latest master branch. 🙂

Another problem though, when using T A S (Transpose, Mirror X, Mirror Y) shortcuts in tilemap, those 4 "Rotate X degrees" icons don't change. They change normally when you click with mouse.

**Comment by akien-mga** [comment] 2018-04-04 09:42
> Another problem though, when using T A S (Transpose, Mirror X, Mirror Y) shortcuts in tilemap, those 4 "Rotate X degrees" icons don't change. They change normally when you click with mouse.

Could you open another issue for that?

**Comment by wingedadventurer** [comment] 2018-04-04 09:49
@akien-mga done.

**Comment by noidexe** [comment] 2018-05-18 14:57
Another issue that might be related to this is that there seems to be no way to get out of tilemap editing mode. Pressing Q, W, E seems to put you in the respective modes(slect, move, rotate) and the cursor changes, but when you click and drag you just paint tiles.  This happens on 3.0.2 and 3.0.3-rc2 at least. 

Let me know if you want me to open a separate issue for this.

Also, the G key is assigned to the paint bucket but also to show grid. Show grid seems to be the action being performed on key press. 
Same goes for the Delete key.  If you select some tiles and press Delete you get a popup to delete the selected node(the tilemap) rather than deleting the selected tiles.  This also happens when you select a node, then some file in the file manager and press delete, which has caused me to delete nodes by mistake quite a few times. 
I think there's a general issue with shortcuts assigned to more than one action that depend on context to work properly.

**Comment by Omiminpo** [comment] 2018-06-09 00:30
Is there an alternative to select, duplicate and move multiple tiles till this gets fixed?

**Comment by noidexe** [comment] 2018-06-09 16:35
@Omiminpo there is a "Tilemap" drop-down menu in the right part of the top bar when you have a tilemap selected. It has those options.

**Comment by Omiminpo** [comment] 2018-06-12 05:37
@noidexe https://snag.gy/Z2mKnw.jpg here's a screen of how it looks for me, I can't find it unless i'm missing something obvious

**Comment by Dodgetgo** [comment] 2018-10-29 00:51
Still a problem in 3.0.6 even after changing the hot keys from Control+B and Control+D to Alt+B and Alt+D.

**Comment by bojidar-bg** [comment] 2018-12-04 19:58
After looking around, seems like this is caused by #12505. Maybe the canvas_item_editor changes should be cherrypicked?

**Comment by akien-mga** [comment] 2018-12-04 20:34
CC @groud

**Comment by paulloz** [comment] 2019-01-07 17:41
Please someone correct me if I'm wrong but those shortcuts are working on master right now (db33b03f4910431f859454260e5828a9f306216f). I worked with tilemap shortcuts a few months ago in #21272 and I believe it was in the same state as currently.  
The thing is, it's really convoluted: for them to work the *Select* tool needs to be active (understand: you need to hit `Ctrl+B` one time), and as I was saying in #21123 there's no way in the current UI to know what is the active tool...

One more thing, since the aforementioned PR the shortcuts for *Copy* and *Cut* have been moved from `Ctrl-D` and `Ctrl-M` to `Ctrl-C` and `Ctrl-X`.
![godot windows tools 64_2019-01-07_18-35-16](https://user-images.githubusercontent.com/437025/50783614-b6609000-12ab-11e9-884e-c38a82c9da89.png)

**Comment by noidexe** [comment] 2019-01-07 18:07
I just tried it and it seems to be working fine now.

**Comment by bojidar-bg** [comment] 2019-01-07 19:36
Ahem. It is fixed on _master_, but still present in _3.0.x_. That's why it is open.

**Comment by paulloz** [comment] 2019-01-07 19:48
bojidar: of course.  
I just thought it was a good place to bring up a related UI issue and note that (as 3.1 should be coming shortly) the shortcuts listed in the issue have been changed.

**Comment by AtomaFajrovulpo** [comment] 2019-10-31 18:03
Does not work in 3.2 alpha 3 either

**Comment by Beliriel** [comment] 2020-03-20 20:21
Still exists on 3.2.1

**Comment by Calinou** [comment] 2020-03-20 21:19
@Beliriel Some TileMap editor default shortcuts were changed in 3.2.1, see https://github.com/godotengine/godot/pull/36054.

**Comment by Beliriel** [comment] 2020-03-21 02:09
I want to delete Tiles from Tilesets. Delete doesn't work.

**Comment by Calinou** [comment] 2020-04-24 08:03
@Beliriel I presume the node deletion dialog is taking over in this case?

**Comment by KoBeWi** [comment] 2021-05-17 19:19
Seems fixed in 3.3

**Closed by KoBeWi** 2021-05-17 19:19 UTC
Labels: bug, confirmed, topic:editor, usability
