### ISSUE TITLE
InputMap : remap with gdScript and change scene, key is pressed

### ISSUE THREAD

**Issue by theludovyc** [godotengine/godot#21038] opened 2018-08-15 11:49 UTC
**Godot version: 3.0.6

**OS: Windows 7

**Steps to reproduce:
Add 2 new actions in Input Map:
Project > Project Settings > Input Map
Write "MyKey_0" clic to add.
Write "MyKey_1" clic to add.
Scroll down.
At "MyKey_0", on left clic on "+", choose key, press A, and clic ok.
At "MyKey_1", on left clic on "+", choose key, press Q, and clic ok.

Create scene name it "Scene0" and save it at root in res://. Add node and name it "Scene0". Add script on this node "Scene0.gd".

Scene0.gd:
extends Node

func _ready():
	print("Be in scene0")
	pass

func _process(delta):
	if Input.is_action_just_pressed("MyKey_0"):
		print("load scene")
		get_tree().change_scene("res://Scene1.tscn")

	if Input.is_action_just_pressed("MyKey_1"):
		print("remap")
		var v=InputMap.get_action_list("MyKey_0")
		v[0].scancode=KEY_Q

		v=InputMap.get_action_list("MyKey_1")
		v[0].scancode=KEY_A

		print("load scene")
		get_tree().change_scene("res://Scene1.tscn")
	pass

Create scene name it "Scene1" and save it at root in res://. Add node and name it "Scene1". Add script on this node "Scene1.gd".

Scene1.gd:
extends Node

func _ready():
	print("Be in scene1")
	pass

func _process(delta):
	if Input.is_action_pressed("MyKey_0"):
		print("Hello MyKey_0")

	if Input.is_action_pressed("MyKey_1"):
		print("Hello MyKey_1")
	pass

**Issue description:
When you start Scene0 and press A and release it, work fine in Scene1.
When you start Scene1 and press Q and release it, didn't work fine in Scene1. "Hello MyKey_1" is print in loop... You need to press A and release it, to stop loop and return to normal.

**Context:
It's simplified version of code I make last week-end for LD-42 to remap. So people can use qwerty keyboard because I use azerty. You can test my game here https://ldjam.com/events/ludum-dare/42/home-1 and see all the code here https://github.com/theludovyc/Godot_LudumDare42/blob/master/Script/Main.gd .

**Comment by KoBeWi** [comment] 2020-06-18 20:51
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
(btw whole game is not a minimal project)

**Comment by KoBeWi** [comment] 2020-09-28 16:26
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:26 UTC
Labels: bug, topic:input
