### ISSUE TITLE
Create a Quad shape? (just sets a tiny concave polygon maybe)

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#17893] opened 2018-03-31 19:21 UTC
Gogot 3.0.2 Windows

Hi there,

A kinematic Body using move_and_slide won't move on top of a plane mesh collider.

**Steps to reproduce:**
- Create a staticBody, set it's friction to 0.5 
- Create a plane mesh as floor in Godot and add a collision plane to it
- drag those as child of staticBody
- a character won't move on top of the plane mesh using move_and_slide

Solution : 
Use a collision box instead to the plane mesh collision
The character will move using the same script with move_and_slide

**Comment by AndreaCatania** [comment] 2018-04-04 09:14
If you mean primitive plane shape, it's a correct behaviour. The plane shape is not meant to walk on.

Try to use a primitive box shape or create a static body from a mesh plane

**Comment by DevMagicLord** [comment] 2018-05-01 17:36
There is other 3D engines games with levels made of planes for floor and walls with physics working as intended. Godot should try to get it working.

**Comment by Zireael07** [comment] 2018-05-01 18:50
Plane shape is mostly meant to be world ground/bottom, so that you don't get stuff falling infinitely.

**Comment by DevMagicLord** [comment] 2018-05-02 22:53
>  This is not possible in Godot because the plane shape has infinite size. This mean that if you create a walls with plane shape you will not be able anymore to make doors or rooms... Probably in that engine the plane shape is meant to be used in another way or it just use a box with a thin side


Try unity, any plane will work with physics, many games have planes for walls and floors.
Is this Bullet physics limitation compared to Physx ? If it's not possible because of Buller physics i'm ok with that.

**Comment by Zireael07** [comment] 2018-05-03 08:26
Does unity plane shape have infinite size? I'm not sure...

**Comment by DevMagicLord** [comment] 2018-08-30 20:54
No need for infinite plane in Unity.

You can create a 7 meters plane, a capsule will collide on top of it and will fall down when it leaves the plane surface area. Collisions work great on walls that are planes only also.
Nvidia Physix must work differently.

Could Bullet work the same way and work with collisions against planes ?

**Comment by Zireael07** [comment] 2018-08-31 08:04
@DevMagicLord: That means unity's plane shape is a quad, not a plane.

**Comment by reduz** [comment] 2018-09-07 12:55
This is not a bug, plane shape is infinite in Godot. Use something else instead (maybe we could add a Quad shape?). Changing to enhancement.

**Comment by Zireael07** [comment] 2018-09-07 13:09
Quad shape please...

**Comment by AndreaCatania** [comment] 2018-09-07 13:12
3.1 or 3.2?

**Comment by DevMagicLord** [comment] 2018-09-08 12:44
What is the purpose having a collision plane in the editor menu when physics doesn't work on it ?

Perhaps rename "collision plane" to "infinite collision plane" or "non physics collision plane", this way we won't be confused about collision.

**Comment by eon-s** [comment] 2018-09-08 20:37
Won't hurt to have a quad shape on 3.1, is just a new resource on the list.

@DevMagicLord Planes have infinite extents by definition, like lines.

**Comment by Zireael07** [comment] 2018-09-09 07:17
@eon-s: wouldn't hurt to have it stated explicitly, some engines/devs use plane to refer to a quad.

**Comment by eon-s** [comment] 2018-09-09 18:11
@Zireael07 the thing is that the meaning of Plane is that, you cannot be more explicit https://en.wikipedia.org/wiki/Plane_(geometry)

**Comment by DevMagicLord** [comment] 2018-09-11 09:46
I don't think lot of games will use infinite planes, add "Plane quad" is a good solution.

Put "infinite plane" in last position because nobody will use it for games, perhaps it could have some uses for some testing.

**Comment by eon-s** [comment] 2018-09-11 09:49
@DevMagicLord Is useful with Area

**Comment by DevMagicLord** [comment] 2018-09-14 08:12
Useful with Area ? Any example ?

**Comment by AndreaCatania** [comment] 2018-09-14 08:36
Plane shape is useful to define infinite collision, no wander if used with area or static body the use cases are not listable.
Also is good a thing define world margin (that prevent physical objects to fall forever) and the plane shape is perfect for this task.
Add quad shape is an enhancement, and prevents people to expect from the plane to be finite.

**Comment by AndreaCatania** [comment] 2018-09-22 08:56
Moving to 3.2 since it's a new feature

**Comment by Zylann** [comment] 2019-02-19 13:48
I'm confused by this issue... planes work fine for me with rigidbodies, they collide with it correctly as a floor. If KinematicBody can't handle it I would indeed call that a bug Oo

**Comment by Calinou** [comment] 2020-03-18 10:39
Isn't this use case covered well enough by a very thin BoxShape?

**Comment by madmiraal** [comment] 2020-06-07 09:28
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by madmiraal** 2020-06-07 09:28 UTC
Labels: discussion, enhancement, topic:physics
