### ISSUE TITLE
Alt+(any number) dose'nt work

### ISSUE THREAD

**Issue by xStar-Lordx** [godotengine/godot#46599] opened 2021-03-02 19:20 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
When i press for example Alt + 123 it shuld write the "{" but instead it acts like i was pressing the 1 2 or 3 in the numpad whit the numlock off. That happens with all the shortcuts like Alt + 91 for [.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-03-02 22:01
Duplicate of https://github.com/godotengine/godot/issues/2689.

**Closed by Calinou** 2021-03-02 22:01 UTC
