### ISSUE TITLE
`CSGShape._update_shape()` doesn't work properly when invisible or outside the scene tree

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#41093] opened 2020-08-07 05:50 UTC
**Godot version:**
3.2.3.rc3 - master

**OS/device including version:**
Windows 10 2004

**Issue description:**
Calling `_update_shape` on a `CSGShape` with child shapes doesn't work properly when invisible or when outside the scene tree because there's code that prevents its children's brushes from generating:
https://github.com/godotengine/godot/blob/9be7b30f3536057b22fd70d5367268749c1a7ea9/modules/csg/csg_shape.cpp#L158-L159
It's also not possible (by design) to call `_update_shape` on child shapes in order to circumvent this:
https://github.com/godotengine/godot/blob/9be7b30f3536057b22fd70d5367268749c1a7ea9/modules/csg/csg_shape.cpp#L273-L275
The result is the exclusion of all child data, which mainly affects `get_meshes()[1]`.

**Steps to reproduce:**
1. Add a `CSGShape` with child shapes to the scene
2. Set `visible` to `false`
3. Call `_update_shape()`
4. Display the final mesh with `get_meshes()[1]`

OR

1. Instance a `CSGShape` with child shapes from a script
2. Call `_update_shape()`
3. Display the final mesh with `get_meshes()[1]`

**Minimal reproduction project:**
[Update Shape.zip](https://github.com/godotengine/godot/files/5039521/Update.Shape.zip)

**Comment by madmiraal** [comment] 2020-08-07 07:35
@hoontee I've not marked this as a bug, because, as you say, it's by design.

However, I do like the idea, which you seem to be exploring, of creating new meshes at runtime by merging CSG shapes. :+1:

**Comment by hoontee** [comment] 2020-08-07 07:51
> @hoontee I've not marked this as a bug, because, as you say, it's by design.

`_update_shape` by design won't work on child shapes, yes, but that wasn't really the focus of the issue.
The bug is that `_update_shape` doesn't work properly when the shape isn't visible or isn't inside the scene tree. Otherwise, it works as intended.

**Comment by hoontee** [comment] 2020-08-07 08:16
Also, for context, I'm trying to convert all `CSGShapes` in my project to `MeshInstances` at runtime in order to avoid the stuttering explained in #40931. Nothing fancy :p

**Comment by madmiraal** [comment] 2020-08-07 08:48
> The bug is that `_update_shape` doesn't work properly when the shape isn't visible or isn't inside the scene tree. Otherwise, it works as intended.

First, I'm surprised that `update_shape` was even made accessible. However that's beside the point. I assume, when originally designed, it was thought that there is no need to update the shape if it's not visible. Your use case: exporting the mesh when the CSG shape is invisible, is an exception that was clearly not considered, but I agree it would make sense.

> I'm trying to convert all CSGShapes in my project to MeshInstances at runtime in order to avoid the stuttering explained in #40931. Nothing fancy

CSG shapes were created to enable rapid prototyping not to be used in your end game. If you're not doing runtime changes, then why not just use a pre-created Mesh?

**Comment by hoontee** [comment] 2020-08-07 09:04
> CSG shapes were created to enable rapid prototyping not to be used in your end game. If you're not doing runtime changes, then why not just use a pre-created Mesh?

I'm using them in my project for room surfaces. The level design is constantly changing, so I determined that directly using what I'm making in CSG is the easiest solution. There's no additional graphics or physics overhead other than the stuttering when making nearby rooms visible.

**Comment by Wiering** [comment] 2020-08-08 19:53
I'm running into the same problem. I'm creating CSG from code, it displays fine, but when I try to save it, get_meshes() always returns [].

**Closed** 2022-03-09 13:16 UTC
Labels: topic:core, usability
