### ISSUE TITLE
Size of non scaled PhysicsBody2D nodes (at 1,1) seems fixed to 64 pixels

### ISSUE THREAD

**Issue by viniciuscsg** [godotengine/godot#23605] opened 2018-11-08 22:38 UTC
Godot version:3.0.6.stable.official; OS/device: Windows 10

Differently from other node types such as Sprites or CollisionPolygon2d, it seems like the three PhysicsBody2D nodes cannot have their size set in pixels without changing their transform scaling properties changed from the non scaled 1,1 size. The scaling transform unit for these nodes seems to be fixed at 64 pixels (to the best of my knowledge searching the docs, forums and known issues). That prevents PhysicsBody2D nodes to match grid sizes that are not power of 2, such as 24px X 24px grids, and still keeping them at 1,1 scale (non scaled), to adhere to in game size unit. 

You might be thinking this is a non-issue because you shouldn't worry about the size of PhysicsBody2D nodes, as their size wont interact with game world nor be rendered at run time, just the size of their children nodes such as CollisionPolygon2d or Sprites. However it is still quite inconvenient in level building if the game grid is not power of 2 for two reasons, assuming a PhysicsBody2D node is used as a parent CollisionPolygon2d and sprites nodes:

1- If the PhysicsBody2D node is at 1,1, then the sprite and collision child nodes will also be at 1,1, and they indeed can have their size changed to match the grid with the inner handlers while still being at 1,1, which is good, but then the group selection which is centered at the parent will have a large 64x64 handler box irrespective of the objects size and of the grid, making level building and object selection hard as the boxes will overlap a lot, covering a lot of cells.

2- if the PhysicsBody2D parent node is rescaled in the editor to make for convenient positioning and selection of node groups, preventing above problems, then the child Sprite and CollisionPolygon2d nodes will inherit the PhysicsBody2D transform (for example, 2.66666... for 64px scaled into 24x24 grid) which will fractionary for any grid which is not power of 2, while for the game logic it would be easier to plan movement and stretching/squashing if basic units like blocks, which match the grid, were at 1,1.

Steps to reproduce: drop a PhysicsBody2D on the editor, give it child nodes, resize it.

**Comment by akien-mga** [comment] 2018-11-09 08:14
Duplicate of #4255, fixed in the master branch with #17502.

**Closed by akien-mga** 2018-11-09 08:14 UTC
