### ISSUE TITLE
[bug] "Input.is_action_pressed" method has a reproducible bug

### ISSUE THREAD

**Issue by amkk** [godotengine/godot#31798] opened 2019-08-30 14:37 UTC
**Godot version:**

3.1.1  &  3.2.dev.custom_build (current head)

**OS/device including version:**

tested on Windows 10 64 bit and Windows 7 64bit

**Issue description:**

Input.is_action_pressed() has a bug that can be easily reproduced.
If it occurs, is_action_pressed returns false even if the action is pressed.
You can test with the 2D Platformer  demo.
**Steps to reproduce:**
1. Open 2D Platformer demo
2. In this demo's InputMap there is an action called move_left.
　Left key of keyboard and left key of D-pad are set as events in this InputMap.

<img width="301" alt="387" src="https://user-images.githubusercontent.com/8508498/64017770-69e10200-cb65-11e9-9fb0-21087e521226.png">

3.Let's Play the demo.
4. First, press and hold the left key of the D-pad.
robi will start walking.
5.In that state, press and release the left key on the keyboard.
After that, robi will stop even if you keep pressing the D-pad.
This is because is_action_pressed returns false.

You may think that there is no problem in real use cases, but there are problems in certain situations.
In most action games you can move with both D-pad and analog input.(Hollow Knight, Dead Cells, Bloodstained etc...)

To do this, suppose you assigned a D-pad and an analog input to the move action.
This bug occurs even with very weak analog inputs, so if the user (player) prefers to use a D-pad, the problem will occur.
Analog inputs can produce weak outputs even when not touched. 
Even in this case, movement stops even if the player keeps pressing the D pad.

I actually tried it with the ps4 controller.
The dead zone remains at the default of 0.5.
 Also, even if weak analog output occurs(some kind of noise), the character will not move without operation.
Even in this condition, when moving character with d-pad, the character sometimes stops due to this bug.
This bug seems to occur regardless of the dead zone setting.
That's all.
Thank you.

**Comment by KoBeWi** [comment] 2019-08-30 14:45
Duplicate of #23749

**Closed by KoBeWi** 2019-08-30 14:45 UTC
