### ISSUE TITLE
Mesh doesn't reload until .tscn is closed and reopened

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#10119] opened 2017-08-06 01:20 UTC
Godot 3.0 alpha1
Windows 10 64 bits

Repro steps:

1) Create a cube in Blender and export it as .obj
2) In Godot, set import settings to "multiple objects" so that it generates a .mesh (I initially wanted to import it as a mesh for use in gridmap, intention related to #9910)
3) Assign that .mesh to a MeshInstance, notice you can see the mesh now
4) Modify the mesh in Blender and reexport it
5) Notice Godot probably reimports the mesh because the loading bars show briefly, however the mesh is still unchanged in the scene
6) Now close the scene, and reopen it: the mesh is now up to date

**Comment by razvanc-r** [comment] 2017-08-06 11:22
This is probably related to #10017, it's not just the mesh, it's probably all properties (color, etc.)

**Comment by kubecz3k** [comment] 2017-08-18 10:29
I also this it's probable that this issue is duplicate of #10017 @Zylann what do you think?

**Comment by kubecz3k** [comment] 2017-08-18 10:30
Also we should check if this issue is still viable after https://github.com/godotengine/godot/commit/33c1d25517050470689924c60414feaf295ce05f

**Closed** 2017-11-12 20:17 UTC

**Comment by akien-mga** [comment] 2019-01-02 14:11
Please open a new issue, this one has been closed over a year ago.
