### ISSUE TITLE
Animation State Machine, Transition waits for 2 frames when transition should happen

### ISSUE THREAD

**Issue by elXill** [godotengine/godot#94034] opened 2024-07-07 14:47 UTC
### Tested versions

Reproduceable in: Godot v4.2.2.stable, and I think prior versions.

May be related to https://github.com/godotengine/godot/issues/29187

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

- Reproduciable in 4.22
I have made a script that let's me play the game frame by frame with each press. After doing that I noticed that bool change happens a frame later which is natural but I would expect animation to start transitioning in this frame too just when bool changes in _physics_process. To check this out I set my Xfade to 0.

Stepping to next frame done in `_input()`
Animation bools changed in `_physics_process()`.

So everything happens like this:

Frame 0 idle animation
Frame 1 idle animation button pressed
**Frame 2 idle animation button pressed, button bool changed**
**Frame 3 transition to new animation can be get; button pressed; button bool changed**
Frame 4 transition visually gets rendered(with 0 xfade time); button pressed; button bool changed

This happens a bit differently when next animation should start at the end automatically

Frame 0 frame 13/13 of current animation
Frame 1 frame 14/13 of current animation (adds one more last frame to animation but there is a visual change in animation)
**Frame 2 frame 0/x of new animation (adds one more frame to start of animation)**
Frame 3 new animation gets rendered visually 1/x

If I'm not mistaken frames written in bold are some kind of latency. When there is an xfade value (bigger than 1 frame equal) this stopping at frame 0/x is less appearant since there is a blending between animations.

-I found an old memo about this:
There is 2 frame latency between input and new state, which can be solved with 2x my_anim_tree.advance(0) which causes other problems
Example; root motion values always being 0 get_root_motion_position() depending on place used in script,
Example; causes a lag for set_bone_global_pose_no_override() function (1 or 2 frames), when used with conjunction of BoneAttachment3D and Marker3D.

### Steps to reproduce

Any state machine setup should work. The script I used to stop frames is below, I used some other things to see which frame animation on total frame count etc. but it should be easily seen with just this and checking animation in game frame by frame (it is easier to see if animations are more different)

```
extends Node
func _input(_event):
	
	if(Input.is_key_pressed(KEY_KP_5)):
		if(get_tree().paused == false):
			get_tree().paused = true
		else:
			get_tree().paused = false
			
	if(Input.is_key_pressed(KEY_KP_6)):
			get_tree().paused = false
			get_tree().create_timer(float(1.0/60.0),true,true,false).timeout.connect(_stop_for_single_step)

func _stop_for_single_step():
	get_tree().paused = true
```

### Minimal reproduction project (MRP)

I will whip something out.

**Comment by TokageItLab** [comment] 2024-07-07 15:34
Dupe of https://github.com/godotengine/godot/issues/91215

**Closed by TokageItLab** 2024-07-07 15:34 UTC
Labels: topic:animation

**Comment by elXill** [comment] 2024-07-20 14:25
I remember you saying animation player having a similar documented problem that we should use `advance(0)` but my experience was a bit different than documentation. 

![image](https://github.com/user-attachments/assets/4f6ff8d0-c12d-489e-aca8-027c67ded657)

play()x2 + advance(0.01) roughly solves this issue, 

I'm not sure but the problem may be last frame of current animation and first frame of next animation rendering in seperately. I'm not sure here but may be they need to be glued together as a single frame?? and root motion for this shoud be first clip's last and prior to last roo motion as well??

I guess this is just a solution for 1 frame if it is. Is this how it should work, should I report it?
