### ISSUE TITLE
Children of nodes in inherited scenes are removed when the node is renamed in the original scene

### ISSUE THREAD

**Issue by fire540** [godotengine/godot#56704] opened 2022-01-11 22:54 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, GLES 3

### Issue description

When a node in a scene is renamed, any children of that node in any inherited scenes are removed. This is likely because the .tscn file format saves nodes according to their path in the scene, which changes when a parent node is renamed. The incorrect behavior here is that instead of automatically fixing the paths or giving the user an option to keep the nodes it ignores them.

Possible solutions:
* Automatically update node paths in inherited scenes accordingly when a node in a scene is renamed
* Display a popup window upon opening a scene with a list of nodes whose paths are invalid, and give an option to either reparent these nodes or remove them.
Here is the missing dependencies popup that is shown when a resource in use is removed. Something similar could be added for nodes with an invalid path.
![image](https://user-images.githubusercontent.com/67974470/149031706-78c783eb-5db5-4b38-b0f8-f4b6dd19dbd2.png)
* At the very least, display a warning that some nodes in the scene have an invalid path and allow users to back out of opening the scene without losing work.

### Steps to reproduce

1. Open the minimal reproduction project linked below
2. Open `Scene.tscn` and `Inherited Scene.tscn`
3. Notice the `B` node under node `A` in `Inherited Scene.tscn`
4. Rename node `A` in `Scene.tscn`
5. Observe that node `B` no longer exists, because it's parent was renamed (but still exists!)

### Minimal reproduction project

[Godot Bug.zip](https://github.com/godotengine/godot/files/7850320/Godot.Bug.zip)

**Comment by Calinou** [comment] 2022-01-11 23:02
Duplicate of https://github.com/godotengine/godot/issues/24817 (same cause)
.

**Closed by Calinou** 2022-01-11 23:02 UTC
Labels: bug, topic:editor
