### ISSUE TITLE
Unable to deselect Audio bus effects (including selecting nodes or files, switching tabs, etc.)

### ISSUE THREAD

**Issue by IronBrandon** [godotengine/godot#85478] opened 2023-11-28 18:07 UTC
### Godot version

3.5.3.stable.official [6c814135b]

### System information

OS: Windows 11 - CPU: Intel Core i7-8700 @ 3.20GHz - GPU: NVIDIA GeForce GTX 1060 3GB

### Issue description

When I create an effect on an Audio Bus, selecting it is permanent unless I select another effect.
I've had this issue for a while and, when first discovering thought to myself "Eh, somebody else probably found it, it's already fixed". That was about a year ago now (_maybe longer_), and it's still the exact same.

The way I'd expect it to work is it would deselect if I clicked **anywhere** outside of the effect itself or the Inspector window (_or if I switch to the Output, Debugger, etc._).

### Demonstration video
https://github.com/godotengine/godot/assets/42562727/42ee9699-0420-4b97-9644-8de62204c78e

### Steps to reproduce

1. Open a Godot project (_happens in anyone for me_) or create a new one
2. Open the Audio tab
3. Create an effect and select it or select an existing one
4. Attempting to click outside the box will never deselect it. Attempting to delete a node or clicking DEL will only delete the effect (_even when it's not visible_).
### Temporary Fix
Create a deselection effect on the same bus and delete it. While it is an easy fix, this can get in the way of many developers, as it did with me (_it took me months to realize this_).

### Minimal reproduction project

N/A

**Comment by berrybus** [comment] 2023-11-29 00:33
For what it's worth, I was able to reproduce this on 3.5.3, but not on 4.1, so maybe some backporting is necessary?

Here are some recordings from 4.1 on Windows 11:

https://github.com/godotengine/godot/assets/10054174/937b896c-56c9-4aa6-b39e-56ab5cc8210d

The audio effect stays selected visually, but it looks like you can still delete other nodes.

https://github.com/godotengine/godot/assets/10054174/9326d2f8-ce01-4d45-a830-403f03cb68a8

You can also wiggle the effect around to get the visual selection to go away

**Comment by IronBrandon** [comment] 2023-12-01 17:47
> For what it's worth, I was able to reproduce this on 3.5.3, but not on 4.1, so maybe some backporting is necessary?
> 
> Here are some recordings from 4.1 on Windows 11:
> 
>  capture.mp4 
> The audio effect stays selected visually, but it looks like you can still delete other nodes.
> 
>  deselect.mp4 
> You can also wiggle the effect around to get the visual selection to go away

This is an important issue (_at least to me_) because new developers will think the effects don't work. I probably would've switched engines if I hadn't figured it out, and it also delayed my game's sound design progress.

**Comment by Calinou** [comment] 2023-12-07 01:07
This wasn't actually fixed in 4.x – there's still no way to deselect a list of audio effects. What was fixed in 4.x was shortcut propagation issues, making the audio editor's Delete shortcut take priority over other shortcuts such as removing nodes.

**Closed** 2023-12-14 16:45 UTC
Labels: bug, topic:editor, confirmed, usability, topic:audio
