### ISSUE TITLE
TextEdit boundary wrap mode does not work if text field is empty before running

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#70582] opened 2022-12-26 07:21 UTC
### Godot version

4.0 beta 10

### System information

Windows 10

### Issue description

https://github.com/godotengine/godot/issues/3985 - old issue but has some new comments

The project is a control node that contains a textedit node with boundary wrapping enabled and no default text.

### Steps to reproduce

Type till it hits the edge, doesn't wrap if text field was empty before launching.

### Minimal reproduction project

[textedit-bug.zip](https://github.com/godotengine/godot/files/10302154/textedit-bug.zip)

**Comment by blurrred** [comment] 2023-03-29 05:40
I'm having the same issue with TextEdit wrapping not working, only it also fails even if I populate it with text before launching.

**Comment by kitbdev** [comment] 2024-03-09 20:12
Cannot reproduce in 4.0, 4.0.4, or latest master.
Before 4.1, the line wrap mode was not exposed and only separate words were wrapped, I think this was your issue but I'm not sure. 
If it was then this is a duplicate of https://github.com/godotengine/godot/issues/74256 and fixed in https://github.com/godotengine/godot/pull/74813.

**Closed** 2024-03-09 20:13 UTC
Labels: bug, topic:gui
