### ISSUE TITLE
Almost imperceptable buzzing noise when playing / updating editor

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#22245] opened 2018-09-19 10:26 UTC
If I weren't using headphones I wouldn't have noticed, it's very subtle.
Probably a driver issue / signal interference on my end, I haven't noticed it on anything else though, just Godot.
Just curious if anyone else has noticed this?

**Comment by Zireael07** [comment] 2018-09-19 10:39
Fill out the issue template please (what OS? Godot version? what sound card?)

**Comment by girng** [comment] 2018-09-19 14:06
How to confirm this is related to Godot as compared to an OS driver issue, or a hardware one?

**Comment by muiroc** [comment] 2018-09-19 14:44
I had this issue with an old laptop and Blender 2.7x, do you have it installed? if you do you could try opening it and moving rotating the scene view (or maybe any other opengl program?)

**Comment by NykolaR** [comment] 2018-09-22 03:03
I can confirm I have this static as well while rotating a 3D scene in the editor using the middle mouse button, can only really hear it when using monitoring headphones/speakers though. I think I have the same problem in blender but I'm not sure.

OS: Linux x86_64, Godot 3.x

**Comment by groud** [comment] 2018-09-28 13:57
Without more information on your hardware, OS, opengl version & all, it is unlikely we fix the issue.
Very likely like a driver bug though.

**Comment by KoBeWi** [comment] 2020-06-26 23:03
No one else reported it since then and it lacks information, so should be fine to close this issue.
(it can be reopened if someone reproduces this in 3.2.2)

**Closed by KoBeWi** 2020-06-26 23:03 UTC
Labels: bug, topic:editor
