### ISSUE TITLE
Start Godot Project Manager center of the screen. 

### ISSUE THREAD

**Issue by y0nd0** [godotengine/godot#42214] opened 2020-09-20 15:45 UTC
**Godot version:**
Godot 3.2.2 64-bit (GDScript) - Btw. is there a 32-bit PC on the globe? I doubt it. Godot should only be available in 64-bit (Windows / Linux, like Mac) But anyway... 🙂 

**OS/device including version:**
Window 10 64-bit (Version 1909)

**Issue description:**
The window of Godot Proejct Manager is not centered of the screen. It's a bit annoying. Nothing critical but would be great if this gonna be polished. ❤️ 
In Godot the project launcher (play, F5) is also not centred until the hdpi flag is set in the project settings. Maybe this is a similar issue. But I rather think that this is just a spawned window of the console application without window position property set. I'm not experienced with C++, but in C# there are options for a window form to spawn. A property for the start position of the window. It should start at the middle / center of the screen.

**Steps to reproduce:**
1. Use a 4k resolution (3840 x 2160 px, OS UI scale 200%)
2. Start Godot. (In my case with hidden console, but it does not matter.)
3. See that the window is not centered. It's aligned at the right bottom area of the screen.

![demo](https://user-images.githubusercontent.com/68586847/93715093-5a18cf00-fb67-11ea-9e42-37e27d664f05.jpg)

**Comment by akien-mga** [comment] 2020-09-20 15:50
Looks like the computation for window position (top left, so center minus half size) doesn't take into account the upscaling of the window.

**Comment by y0nd0** [comment] 2020-09-20 15:57
Yes that's also plausible. Does the SDK have an option for centered window? Or is this computed manually? I would prefer the auto solution of the window SDK if possible and work correctly. If not is the scale value known? Can this be a part of the calculation?

**Comment by Calinou** [comment] 2020-09-20 16:00
Duplicate of https://github.com/godotengine/godot/issues/13017.

**Closed by Calinou** 2020-09-20 16:00 UTC
