### ISSUE TITLE
Tonemap is ignored in viewports with transparent background

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#51901] opened 2021-08-19 22:44 UTC
### Godot version

3.4 beta 4

### System information

Windows 10, GLES3, GTX 1070

### Issue description

When using additional viewports(render targets) in 3D, tonemap is ignored in the secondary viewports, if `transparent_bg` is enabled. Other stuff in the WorldEnvironment seems to work in all viewports (fog etc.)

### Steps to reproduce

Open my project. Added simple control nodes for convenience. 
Edit world environment and viewport node settings while running the scene is another option.

### Minimal reproduction project

[TonemapBug.zip](https://github.com/godotengine/godot/files/7018051/TonemapBug.zip)

**Comment by clayjohn** [comment] 2021-08-19 23:31
Duplicate of https://github.com/godotengine/godot/issues/45208

**Closed by clayjohn** 2021-08-19 23:31 UTC
