### ISSUE TITLE
Nuget packages cannot be used on linux (probably also MacOS) (Mono)

### ISSUE THREAD

**Issue by Duehok** [godotengine/godot#41306] opened 2020-08-16 08:13 UTC
**Godot version:**
3.2.2

**OS/device including version:**
any linux (tested on Ubuntu 20.04)

**Issue description:**
To use a nuget package in a Godot project, `nuget restore` has to be run in the project's folder. According to godot's docs, `dotnet restore` does not work under linux or win (and I confirmed that).
https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#using-nuget-packages-in-godot

`nuget restore` under linux and MacOS is not compatible with the project files format that Godot utilises.
https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#feature-availability
See the (2) note for nuget CLI (Mono)/restore

So no nuget package can be used under Linux.

**Minimal reproduction project:**
This project uses the package `Newtonsoft.Json`. It builds and works correctly under Win 10.
[CSharpTest.zip](https://github.com/godotengine/godot/files/5080245/CSharpTest.zip)

**Comment by raulsntos** [comment] 2020-08-16 09:46
I can confirm using **dotnet CLI** as the build tool fails with the error:
```
MakeJson.cs(3,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [/media/raulsntos/Data/GodotProjects/CSharpTest/CSharpTest.csproj]
```
As a workaround, it seems that switching to **MSBuild (Mono)** for the build tool works so you may want to consider using that for now, it's in `Editor Settings > Mono > Builds`.

Also, this sounds like a duplicate of #41241.

**Comment by Duehok** [comment] 2020-08-16 10:23
i tried changing the build tool. I could not get it to build. Can you describe exactly what you did?

**Comment by raulsntos** [comment] 2020-08-16 12:20
After setting the build tool to `MSBuild`, this is what I did:
- Delete the .mono directory
- Run `nuget restore`
- Build the project
![image](https://user-images.githubusercontent.com/3903059/90334035-ebc27900-dfca-11ea-849e-583461f129b9.png)

And this is my mono version:
```
Mono JIT compiler version 6.12.0.86 (tarball Mon Jul 20 08:39:42 UTC 2020)
```

If you still can't get it to build it may be helpful to take a look at the contents of `msbuild_log.txt` that can be open with the `View log` button.

**Comment by Duehok** [comment] 2020-08-16 13:16
`nuget restore`

```MSBuild auto-detection: using msbuild version '' from '/usr/bin'.
 
>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
 
MSBUILD: error MSBUILD0004: Too many project files specified```

How did you get nuget on linux to work with the .sln ands .csproj files of a godot project?

**Comment by raulsntos** [comment] 2020-08-16 13:45
All I did was download your minimal project and executed `nuget restore`.

It could be your mono installation, according to #38167 the currently stable mono version **6.10** doesn't work, have you tried installing the preview mono **6.12** from [https://www.mono-project.com/download/preview/](https://www.mono-project.com/download/preview/)?

**Comment by Duehok** [comment] 2020-08-16 14:09
IT WORKS after using the installation from #38167. Many thanks. 🎆🎇🙏🏻😱🎉🍾

I will start a new, clean, GMO-free ubuntu virtual machine and check what are the minimal changes from the official instructions to get it to work.

**Comment by Duehok** [comment] 2020-08-16 15:12
As best as I can tell, the requirements are the following, after having downloaded Godot C#:

- install mono 6.12+ according to those instructions:
⚠ First trap: as of 08-2020, that is the preview version, not the stable one.
https://www.mono-project.com/download/preview/#download-lin

Which for ubuntu 20.04, is:
```
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu preview-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-preview.list
sudo apt update
```
Note the `sudo tee /etc/apt/sources.list.d/mono-official-preview.list`
- Install mono-complete with ⚠ msbuild⚠ , not just mono-complete

```
sudo apt install mono-devel msbuild
```
- Install nuget, according to those instructions:
https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux

To add a package, in a terminal run from the folder of the godot project, do `nuget add package ThePackageName`
⚠Modify the .csproj file according to that:
https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#using-nuget-packages-in-godot

> By default, tools like NuGet put Version as an attribute of the `PackageReference` Node. You must manually create a Version node as shown above. This is because the version of MSBuild used requires this. (This will be fixed in Godot 4.0.)

then still in a terminal in the godot project folder, do `nuget restore`

This has to be explained in Godot's documentation if there is any hope of it being actually used on Linux. I can't get the docs to compile easily and I am not going to spend hours getting that to work before creating a PR for the docs so no PR from me.

**Comment by Calinou** [comment] 2020-08-16 15:28
> This has to be explained in Godot's documentation if there is any hope of it being actually used on Linux. I can't get the docs to compile easily and I am not going to spend hours getting that to work before creating a PR for the docs so no PR from me.

Feel free to edit the documentation without testing it locally and we'll review your pull request to fix formatting.

**Comment by LordBrkica** [comment] 2020-08-20 17:40
I would like to add another aspect to this Problem/Bug.

I am using Windows10, and Godot 3.2.3RC3. In Godot Editor I have MS Build (VSBuild Tools) selected.
I use Visual Studio Code for work (so all code and debugging). Until now I had no problem. However, lately I am getting the problem that VSC cannot find the Newtonsoft.Json (os System.Text.Json).

When looking at the minimal reproduction project:
> **Minimal reproduction project:**
> This project uses the package `Newtonsoft.Json`. It builds and works correctly under Win 10.
> [CSharpTest.zip](https://github.com/godotengine/godot/files/5080245/CSharpTest.zip)

This is how it looks like when I open it on my screen:
![image](https://user-images.githubusercontent.com/51578785/90805976-ada3bd00-e31c-11ea-8643-9e4039b84044.png)

I can still sucessfully BUILD the project, but VSC is somehow broken. Does anyone else has similar problems ?

**Comment by Duehok** [comment] 2020-08-20 19:20
You mean building using the editor's "play" button works, and the project runs, but the red squigly lines stay in VS Code? If yes, I do not have this problem and it is surprising!

**Comment by LordBrkica** [comment] 2020-08-20 19:27
> You mean building using the editor's "play" button works, and the project runs, but the red squigly lines stay in VS Code? If yes, I do not have this problem and it is surprising!

Exactly this, everything builds ok in editor, I can execute the program, but squigly lines in VSC stay and make development a torture.

**Comment by neikeq** [comment] 2020-08-20 19:59
Assuming this is a duplicate of #41241

**Closed by neikeq** 2020-08-20 19:59 UTC
Labels: bug, platform:linuxbsd, topic:mono
