### ISSUE TITLE
Bad font rendering in Manjaro linux when open new project

### ISSUE THREAD

**Issue by orderorder** [godotengine/godot#69684] opened 2022-12-06 21:04 UTC
### Godot version

Godot Engine v3.5.1.stable.arch_linux

### System information

Manjaro 22.0.0 - Mesa 22.2.4-1 - AMD R7 240 - CPU: AMD A10-7850K

### Issue description

I run the program. In the project management screen the fonts render correctly. But when I open a new project the fonts render in the form of squares
![screenshot](https://user-images.githubusercontent.com/7293829/206022398-f8bebdf1-ccd8-482f-b7bf-6f7c8ef7c75a.png)

### Steps to reproduce

Start GODOT open new project

### Minimal reproduction project

N/A

**Comment by S0yKaf** [comment] 2023-06-08 17:11
Any update on this? I know its not a godot issue per-say but it's pretty inconvenient to not be able to use GLES2 because of it. 

as far as I have been able to find, it seems to be an issue with mesa and the radeonsi driver. yet I'm not seeing any issue relating to this being reported on the mesa repo.

**Comment by Calinou** [comment] 2023-06-08 17:12
We don't know why this is ocurring – I suggest reporting this to Mesa developers.

**Comment by S0yKaf** [comment] 2023-06-08 17:28
> > Any update on this?
> 
> Which graphics card model do you have?
> 
> We don't know why this is ocurring – I suggest reporting this to Mesa developers.

6.3.5-arch1-1
mesa 23.1.1-1
[AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280]

I also don't know why its happening and it's driving me insane lol. Guess I'll bite the bullet and open an issue in mesa.

**Comment by S0yKaf** [comment] 2023-06-08 18:10
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9176

**Comment by S0yKaf** [comment] 2023-06-08 21:22
Ok, so it's been confirmed to be an issue with mesa. if you're having the same problem, I've added a patch on the mesa issue that you can use to build mesa-git with that will fix the problem.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9176#note_1949560

@Calinou I think this issue can be closed now? unless you want to wait for mesa to officially fix it on their side.

**Comment by Calinou** [comment] 2023-06-08 23:16
Closing, as this is an issue in Mesa.

**Closed by Calinou** 2023-06-08 23:16 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:thirdparty, needs testing

**Comment by akien-mga** [comment] 2023-06-09 06:56
@S0yKaf Note that you linked the retroarch issue twice on the Mesa report, instead of linking this Godot issue. You might want to correct that.

**Comment by S0yKaf** [comment] 2023-06-09 07:18
Good catch, Thank you, I fixed it!
