### ISSUE TITLE
Two overlapping Area2D / pickable CollisionObjects both receive input event

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#29825] opened 2019-06-16 09:45 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
I have two overlapping Area2d with rectangle shape. When I click them, both got input event. The one at the bottom gets the event first.
So there is no way to just click the top one. Moreover the get_tree().set_input_as_handled() doesn't stop propagating this event.

**Minimal reproduction project:**
[godotArea2dOverlapping.zip](https://github.com/godotengine/godot/files/3294004/godotArea2dOverlapping.zip)

**Comment by mrcdk** [comment] 2019-06-16 09:53
That's expected. The signals have already been emitted so the event can't be set as handled. If you need more control over it you'll need to use [`_input_event()`](https://docs.godotengine.org/en/3.1/classes/class_collisionobject2d.html#class-collisionobject2d-method-input-event)

**Comment by pgoral** [comment] 2019-06-16 10:02
It seems to me that Area2D should have some kind mechanism to be able to click just the top most

**Comment by pgoral** [comment] 2019-06-16 15:23
For some time I am searching the web trying to find generic solution for this, but I only find people with similar question.

**Comment by pgoral** [comment] 2019-06-16 17:36
I wrote this code and it seems to work in my case, but I do not know if it will work for all cases. Still i think Area2D should do this out of the box.

```
func _on_Area2D_input_event(viewport, event, shape_idx):
	if event is InputEventMouseButton and event.is_pressed():
		var areas = get_overlapping_areas()
		var is_on_top = true
		if areas.size() > 0:
			for area in areas:
				if not is_greater_than(area):
					is_on_top = false				
		if is_on_top:
			emit_signal("mouse_event", event)
```

**Comment by Winsalot** [comment] 2020-09-17 19:34
I have also ran into this issue, so I though I would share my own workaround:

```gdscript
var mouse_entered = false

func _unhandled_input(event):
	if event.is_action_pressed("mouse_select_single") && \
	mouse_entered:
		# do here whatever should happen when you click on that node
		self.get_tree().set_input_as_handled()

func _on_Area2D_mouse_entered():
	mouse_entered = true

func _on_Area2D_mouse_exited():
	mouse_entered = false

```

Here I only use Area2D signals to check if the mouse is inside the CollisionShape2D. The input event is handled directly by the node without emitting any signals.

**Comment by lukepass** [comment] 2022-07-27 09:53
I'm having the same issue and I think that Area2D should have a machanism to mask the input of the other Area2D items below.

@Winsalot thanks for the workaround! However how can I know the order in which the areas are clicked? As far as I can tell if I click on an area the order of input is random, correct?

**Comment by Sauermann** [comment] 2023-06-07 16:07
looks like a duplicate of #16042 and has more detail info

**Comment by crysan** [comment] 2023-07-31 06:11
Godot 4
There is some kind of perfect decision?

**Comment by cjmaxik** [comment] 2023-11-27 07:53
Stumbled upon this issue just now, a real showstopper.

**Comment by mnemoli** [comment] 2023-12-03 10:44
@Calinou can I give a gentle nudge on PR review for this?

**Closed** 2024-02-12 12:49 UTC
Labels: discussion, confirmed, topic:input
