### ISSUE TITLE
2.1.4-beta Area2D error on KinematicBody2D.queue_free()

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#9534] opened 2017-07-07 02:47 UTC
**Operating system or device - Godot version:**
Debian 9 - Godot 2.1.4-beta

**Issue description:**
I have a scene which have an Area2D node as root node, doing .queue_free() inside the "body_enter" signal logs this eror

> "Condition '!node' is true. Continuing..."

The error says is on "scene/2d/area2d.cpp:332" in "_clear_monitoring" function.

I also have a VisibilityNotifier2D node with an "exit_screen" signal, and I do .queue_free() there too, but it doesn't trigger the error.

**EDIT
------**

Seems it has nothing to do the bullet, it's the target that is throwing the error. Here is a demo project.

[Demo.zip](https://github.com/godotengine/godot/files/1130945/Demo.zip)

**Comment by eon-s** [comment] 2017-07-07 03:09
What node does the `.queue_free`? (tried with the same area but does not throw any error)
Can you make a small project with that error to see it better?

**Comment by vicguedez** [comment] 2017-07-07 12:29
@eon-s I updated the issue and upload a demo project.

**Comment by eon-s** [comment] 2017-07-09 22:16
Tested with a recent build too.
If you do `call_deferred("queue_free")` on the KinematicBody2D it does not throw any error.

@RandomShaper may know better if this is a bug or the deferred call cannot be avoided.

This may be related or duplicate of #1247 too.

**Comment by vicguedez** [comment] 2017-07-09 23:49
Ty, will use call_deferred()... Will leave this open then.

**Comment by RandomShaper** [comment] 2017-07-10 08:17
Added to my backlog.

**Comment by RandomShaper** [comment] 2017-07-10 12:54
The error is printed at __area_2d.cpp__ because of

```
Node *node = obj ? obj->cast_to<Node>() : NULL;
ERR_CONTINUE(!node);
```

but if you look a few lines below, in similar code, you have:

```
Node *node = obj ? obj->cast_to<Node>() : NULL;

if (!node) //node may have been deleted in previous frame, this should not be an error
    continue;
//ERR_CONTINUE(!node);
```

In this case, when that happened wouldn't be exactly the "previous frame", but I belive the situation in the first loop is as benign as in the second one.

So this is expected to work, but the warning may be misleading.

**Comment by RandomShaper** [comment] 2017-07-11 10:27
Manually closing via  #9591.

**Closed by RandomShaper** 2017-07-11 10:27 UTC
