### ISSUE TITLE
Textures not rendering properly or on Android with GLES2 and ETC1 VRAM compression

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#39915] opened 2020-06-28 10:40 UTC
I don't know of any potential duplicates.

**Godot version:**
3.2.1.stable (official)

**OS/device including version:**
(Mostly a copy-paste from a previous issue, this time with GLES2)
Microsoft Windows NT Version 10.0.18363.900 running on an Intel Core i3 and integrated graphics,
I'm using GLES2.
My Android device is a Lenovo K6 (K33a48) running Android 7.0, with security patch level "November 1st 2017", build number K33_S231_171114_ROW, with an 8-core MSM8937 processor clocked at 1.4GHz. Has 2 Gigs of RAM and 16 GB of internal storage.

**Issue description:**
I have 2 textures.
One is a blue sphere collectible thingy, and one is a grid placeholder texture.
That grid placeholder texture works kind-of-fine, while it definitely has issues.
<strike>At least it's visible.
Then, here comes the kicker, That blue sphere thingy isn't even visible!
Not in-game, and not on the hud!</strike>

This screenshot was taken on Android, where it looks wrong:
![device-2020-06-28-123555](https://user-images.githubusercontent.com/24682280/85945212-85ab6500-b93c-11ea-8487-d32964f6fc85.png)

This screenshot was taken on PC, where it looks correct:
![image_289](https://user-images.githubusercontent.com/24682280/85945157-1d5c8380-b93c-11ea-8ef2-7b347420e360.png)

**Steps to reproduce:**
Export the thing to android and click the play button in the editor, and compare the two versions. The issue should be clear.

**Minimal reproduction project:**

[funnel-new.zip](https://github.com/godotengine/godot/files/4842071/funnel-new.zip)
Please note that I just now realized I misspelled "collectible" everywhere in the project. Oops.

Edit: I just noticed that I can edit this. Removed the old issue.

**Comment by CenTdemeern1** [comment] 2020-06-28 10:50
Or wait, I just googled it, "collectable" seems to be the better word here.

**Comment by CenTdemeern1** [comment] 2020-06-28 11:18
Wait, hold on, I just read the description of the Etc vram compression thing.
It doesn't support alpha channels!
That may be the issue for the blue sphere things not showing up?
I don't know how to get around it though, and that doesn't solve the issue of the weird half transparent ball.

**Comment by Calinou** [comment] 2020-07-01 12:12
Duplicate of #26211. (See also https://github.com/godotengine/godot-proposals/issues/822.)

**Comment by CenTdemeern1** [comment] 2020-07-01 12:39
Update!
I've just established that this doesn't happen on my brother's phone.
It's a Moto E6 Plus phone.

**Comment by Calinou** [comment] 2020-07-01 12:43
@CenTdemeern1 I feel like this issue is becoming a melting pot of several different bugs. Which bug is not occuring in particular on your brother's phone?

ETC1 doesn't support alpha channel, this is a limitation of the format. No device can lift it.

**Comment by CenTdemeern1** [comment] 2020-07-02 07:47
I've dropped the ETC1 "bug" from this thread, it's about the weird looking ball

**Comment by CenTdemeern1** [comment] 2020-07-02 07:47
So the kind-of-checkered ball looks normal on my brother's phone

**Comment by clayjohn** [comment] 2020-07-03 16:27
@CenTdemeern1 In that case it is a duplicate of https://github.com/godotengine/godot/issues/33633 which has a proposed fix here https://github.com/godotengine/godot/pull/33646 :)

**Closed by clayjohn** 2020-07-03 16:27 UTC
Labels: archived, bug, platform:android, topic:porting, topic:rendering
