### ISSUE TITLE
ERROR: initialize: Directional shadow framebuffer status invalid    At: drivers/gles2/rasterizer_scene_gles2.cpp:3369

### ISSUE THREAD

**Issue by aaronelias1** [godotengine/godot#31093] opened 2019-08-05 05:02 UTC
**Godot version:**

 
Godot_v3.1-stable_win64.exe
OpenGL 2.1 / OpenGL ES 2.0 compatible hardware

**OS/device including version:**

 Windows 10 x64
Intel(R) HD Graphics 3000
OpenGL v.3.1
 

**Issue description:**

OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 3000
ERROR: initialize: Directional shadow framebuffer status invalid
   At: drivers/gles2/rasterizer_scene_gles2.cpp:3369

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/23706835/62440053-c26ade00-b724-11e9-8403-0e599c277c54.png)

![image](https://user-images.githubusercontent.com/23706835/62440105-f7773080-b724-11e9-8c2e-696170b55d17.png)

**Minimal reproduction project:**

**Comment by qarmin** [comment] 2019-08-05 05:09
Duplicate of #28894
1. You can use Mesa for Windows and check if this help
2. You can use Linux(I have this graphics card and it working without any errors)

**Comment by clayjohn** [comment] 2019-08-05 05:28
Yes, this is a duplicate of #28894. 

In the future, please search existing issues before opening a new one.

**Closed by clayjohn** 2019-08-05 05:28 UTC
Labels: archived, bug, topic:rendering

**Comment by aaronelias1** [comment] 2019-08-05 05:44
![image](https://user-images.githubusercontent.com/23706835/62441523-d3b6e900-b72a-11e9-9b1e-76fa56f0bf66.png)

use Mesa for Windows
