### ISSUE TITLE
Import a scene as a MeshLibrary

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#25946] opened 2019-02-16 16:36 UTC
**Godot version:**

3.0.6

**OS/device including version:**

Linux 4.20.6-arch1-1-ARCH 

**Issue description:**

My current meshlib/gridmap workflow looks like:

1. Edit meshlibrary in blender
2. Export using godot-blender-exporter
3. Open the .escn in godot
4. Click through the "Changes to this scene will not be saved" popup
5. Convert > MeshLibrary
6. Click OK in the dialog
7. Close the scene, as future imports seem to get messed up if it is still open

**Suggestion:**

Could we have an `Import As: MeshLibrary` option that would perform steps 3-7 automagically whenever the .escn is updated?

**Comment by slapin** [comment] 2019-08-06 10:40
Totally confirm this but I think API for importer script would be better idea (but fancy importer GUI option would be nice too).
Your workflow prevents editing materials which might not be nice.

**Comment by Xenoamor** [comment] 2019-08-12 21:46
Perhaps you should be able to link an output .meshlib to the scene that it was exported from. Then on that scene there'll be something like a "re-export to meshlib" button

Or more drastically a meshlib could be a root node and everything under it gets converted into it

**Comment by aaronfranke** [comment] 2024-09-08 09:02
Thanks for this proposal! I'm closing this as a duplicate of my proposal: https://github.com/godotengine/godot-proposals/issues/7494

Currently, Godot hard-codes "scene or animation library". My proposal is about more adding types, including mesh, and MeshLibrary would be a natural extension of this, so we can consider it a part of the same proposal.

**Closed by aaronfranke** 2024-09-08 09:02 UTC
Labels: enhancement, topic:import, topic:3d
