### ISSUE TITLE
GDScript : class circular reference : class as method parameter signature

### ISSUE THREAD

**Issue by jeremyz** [godotengine/godot#32205] opened 2019-09-19 13:44 UTC
**Godot version:**
v3.2.alpha.custom_build.a1fcac640

**Issue description:**
Inside a class definition,
if you set that very class as type signature of a method's parameter,
it creates a circular reference around that class definition.

**Steps to reproduce:**
```
extends MainLoop
class_name Circular
var v : int
func _initialize() -> void:
        v = 0
func _idle(delta : float) -> bool:
        v +=1
        if v > 3:
                return true
        return false
func copy(other : Circular) -> void:
        v = other.v
```

```
Loading resource: res://circular.gd
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2069.
Leaked instance: GDScript:1154 - Resource name:  Path: res://circular.gd
Leaked instance: GDScriptNativeClass:581
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:443.
```

replace ```func copy(other : Circular) -> void:```
with ```func copy(other) -> void:```
to avoid the leak.

**Comment by bojidar-bg** [comment] 2019-11-08 15:34
Duplicate of #31378, which I close as a duplicate of #27136, in an attempt to cut down on the amount of GDScript circular reference issues open.

**Closed by bojidar-bg** 2019-11-08 15:34 UTC
Labels: bug, topic:gdscript
