### ISSUE TITLE
Error System.IO.IOException 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#52780] opened 2021-09-17 14:31 UTC
### Godot version

v3.4.beta4.mono.official [6a058cbf3]

### System information

Debian 10 - C#

### Issue description

I have this error in Output:
` modules/mono/mono_gd/gd_mono_utils.cpp:369 - System.IO.IOException: Invalid handle to path "/home/vale/godot/DesertEdgeSharp/authentication/[Unknown]"`
This error don't allow me to compile.

This project was working fine in one pc. The error show up when I cloned it from git in another pc.
In code I have no errors. Its difficult to understand where the problem is.

### Steps to reproduce

See before

### Minimal reproduction project

NA

**Comment by git2013vb** [comment] 2021-09-17 16:28
I found the way to compile just by chance :
I switched in dotnet CLI in editor settings (from MSBuild (Mono)). Clearly the error message doesn't help in this issue.

**Comment by Calinou** [comment] 2021-09-17 17:36
Duplicate of https://github.com/godotengine/godot/issues/26686.

**Closed by Calinou** 2021-09-17 17:36 UTC
Labels: topic:mono
