### ISSUE TITLE
Godot no way to edit the projection matrix

### ISSUE THREAD

**Issue by DxUr** [godotengine/godot#80778] opened 2023-08-19 08:40 UTC
### Godot version

4.1.1

### System information

fedora 38

### Issue description

As the title, I edit the source code and I add a custom_projection propriety it is working pretty well.

![Screenshot from 2023-08-19 09-38-27](https://github.com/godotengine/godot/assets/137767403/93f3aade-bae8-4ce5-8bc1-1dc53491120d)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-08-19 08:41
How do you mean you cannot edit it? Are the input fields locked? Or do you mean there's no visual editing in the 3D view?

**Comment by DxUr** [comment] 2023-08-19 08:43
I mean the official build, but know it is working pretty well.
So it will be an enhancement if that added to the engine.

**Comment by AThousandShips** [comment] 2023-08-19 08:45
Okay, this isn't the place for features, please open a [proposal](https://github.com/godotengine/godot-proposals), this is for reporting bugs

**Comment by AThousandShips** [comment] 2023-08-19 08:49
Duplicate of https://github.com/godotengine/godot-proposals/issues/2713

**Closed by AThousandShips** 2023-08-19 08:49 UTC
Labels: feature proposal, topic:editor, topic:3d
