### ISSUE TITLE
Cannot connect a signal to a static function from a static constructor

### ISSUE THREAD

**Issue by TechnoPorg** [godotengine/godot#82345] opened 2023-09-26 01:43 UTC
### Godot version

Godot v4.1.1.stable

### System information

Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 () - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

When trying to write a class with a static function which handles the `Input.joy_connection_changed` signal, I am unable to connect the signal to the function from within the `_static_init` function. When I try to do so, I get the following error:
```gdscript
static func _static_init():
	Input.joy_connection_changed.connect(_joy_connection_changed)
```
`Invalid get index '_joy_connection_changed' (on base: 'Nil').`
However, connecting to the same static function from an instance constructor throws no error and works as expected. Given that there are multiple instances, though, this does not work for making only one connection.

### Steps to reproduce

In the attached MRP, there are two scenes: one for trying to connect from the static constructor, and one for connecting from the instance constructor. When running the former, it will break with the aforementioned error; however, with the latter, the signal connects and fires properly.

### Minimal reproduction project

[static_signal_connect_bug.zip](https://github.com/godotengine/godot/files/12721058/static_signal_connect_bug.zip)

**Comment by bitsawer** [comment] 2023-09-26 02:12
Thanks for the report, seems to be a duplicate of https://github.com/godotengine/godot/issues/82340, so closing this one to keep discussion in one place.

As a possible workaround, you can add and use explicit `class_name` as mentioned in the other issue:

```gdscript
extends Node2D

class_name TestClass

static func _static_init():
    Input.joy_connection_changed.connect(TestClass.test)

static func test(foo, bar):
    print("Joy connection changed!")

```

**Closed** 2023-09-26 02:12 UTC
