### ISSUE TITLE
Sync scene change affect game performance but no warning is displayed

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#27433] opened 2019-03-26 08:46 UTC
**Godot version:**
3.1-stable

**OS/device including version:**
5.0.3-arch1-1-ARCH

**Issue description:**
Seems like enabling sync scene changes has a notable impact on the performance of the running game.
What happened to me is that I considered some scenes unfeasible to make for a while, until one day i noticed that when running the game directly those scenes that run super slow in the editor run fine (60fps vs 22fps when running from the editor). After disabling 'sync scene changes', similar performance was observed when running from the editor.

**Proposal**
When sync scene changes is enabled, I believe that the editor should display a small warning upon a stable framerate drop. (For example, if the game stays below 40 fps(configurable) for more than 3 seconds (configurable), you should see somewhere in the game window a small warning that tells you to try and run without sync).

**Comment by Calinou** [comment] 2019-03-26 11:09
Can you notice this performance drop in an empty project (or an official demo project)?

**Comment by TheDuriel** [comment] 2019-03-26 23:16
I can expand upon this: Having the 2D/3D view open, while also running your game from the editor, causes a drastic drop in performance. (Half in our project. from 80-120 to 40 fps.) Observed on a moderately powerful windows, and a mac machine. 

There are two steps you can take to fix this: Switch to the script editor. (You'll get most your frames back.) AND Manually prevent the editor root viewport from drawing while not in focus. (You'll get all your frames back.) We made an editor plugin for this exact purpose.

**Comment by Zireael07** [comment] 2019-03-27 07:29
Where can I find your plugin, @TheDuriel ?

**Comment by Calinou** [comment] 2019-11-16 21:47
@TheDuriel Can you upload the plugin that you made for this purpose on GitHub? Thanks in advance :slightly_smiling_face:

**Comment by TheDuriel** [comment] 2019-11-16 22:47
@Calinou https://github.com/TheDuriel/DurielsGodotUtilities you can find it here.

**Comment by Calinou** [comment] 2021-06-15 16:32
Duplicate of https://github.com/godotengine/godot/issues/29531 (same cause).

**Closed by Calinou** 2021-06-15 16:32 UTC
Labels: discussion, enhancement, topic:editor, usability
