### ISSUE TITLE
Godot 4: Exported project cannot load an autoload containing a specific constant name

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#58563] opened 2022-02-26 17:13 UTC
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

An exported project cannot open an autoload that contain a constant matching the following regex: `ENTER_BASE_.*`. The behavior of the editor and the exported build are not the same.

Godot 4 only.

Error :

```
ERROR: Script does not inherit a Node: res://autoload.gd
   at: (main/main.cpp:2294)
```

Full stacktrace :

```
$ ./Test\ export.exe

Godot Engine v4.0.alpha3.official.256069eaf - https://godotengine.org
Vulkan API 1.2.141 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1660 SUPER

WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 171250688
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
ERROR: Condition "int32_t(p_level) - 1 != level" is true.
   at: initialize_extensions (core/extension/native_extension_manager.cpp:99)
ERROR: Script does not inherit a Node: res://autoload.gd
   at: (main/main.cpp:2294)
ERROR: BUG: Unreferenced static string to 0: process_internal
   at: unref (core/string/string_name.cpp:117)
ERROR: BUG: Unreferenced static string to 0: physics_process
   at: unref (core/string/string_name.cpp:117)
ERROR: BUG: Unreferenced static string to 0: physics_process_internal
   at: unref (core/string/string_name.cpp:117)
ERROR: BUG: Unreferenced static string to 0: size_changed
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: bus_layout_changed
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: physics_frame
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: process_frame
   at: unref (core/string/string_name.cpp:119)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:119)
```

### Steps to reproduce

1. Create a project
2. Create an antoload containing the script in **Minimal reproduction project** section
3. Export it (tested in Windows, default options, debug activated)
4. Launch the exported project
5. Ctrl+C or quit the project to trigger the error (I'm not sure this step is required, it depends how you start project)
6. Show the stacktrace

### Minimal reproduction project

```gdscript
extends Node

const ENTER_BASE_a = "a"
```

**Comment by gustavi** [comment] 2022-03-12 08:08
Almost sure it's related to https://github.com/godotengine/godot/issues/59059. If it's duplicated, close this one and keep the other which is me detailed.

(Even it's duplicated I think we still have an issue with the error message which is hard to understand)

**Comment by akien-mga** [comment] 2023-02-22 15:12
Duplicate of #59059.

**Closed by akien-mga** 2023-02-22 15:12 UTC
Labels: bug, topic:core, regression, topic:export
