### ISSUE TITLE
Help window - clipping issue (related to Godot's core team? :)

### ISSUE THREAD

**Issue by dreamsComeTrue** [godotengine/godot#37069] opened 2020-03-15 16:24 UTC
**Godot version:**

Current master 2a49798c7b92b332c2198f52b9c5ae10bd944bd0

**OS/device including version:**

Latest Fedora, Vulkan updated drivers

**Issue description:**

As in attached GIF.
Question: Why it's only emphasizing reduz/punto/akien ??? Is that a bug or purposely added feature? :P 

![godot-bug](https://user-images.githubusercontent.com/1110337/76705619-bc3cd700-66e1-11ea-8097-c1cca419b280.gif)

**Comment by akien-mga** [comment] 2020-03-16 07:49
Duplicate of #36164.

**Closed by akien-mga** 2020-03-16 07:49 UTC
Labels: bug, topic:gui
