### ISSUE TITLE
Adding menu items to the "Tools" menu not working

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/godot#10259] opened 2017-08-11 19:15 UTC
Hi. I was looking for ability to make custom menu in editor. 

I found issue #1429 and pull request #6065. Both are closed. But functionality is not working.
Then I found commit 0aa7242624fcd74eaf13db006274829c284fab3b that was made in a week after previous. And functionality was commented in this commit.

I am really interested is it possible to fix this again. Thanks.

**Comment by neikeq** [comment] 2017-08-11 19:50
Duplicate of #9969

**Closed by neikeq** 2017-08-11 19:50 UTC
