### ISSUE TITLE
Controls defined in Input Map are not saved

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#8989] opened 2017-05-29 19:22 UTC
**Operating system or device - Godot version:**
Linux Mint 18.1 Cinnamon x64
Godot master 8125bbb

**Issue description:**
Any keys or buttons defined under the Input Map menu are not applied or saved. 

**Steps to reproduce:**
- Create a new project
- Create a new action in the Input Map menu and assign any key or button to it
- Add any node to the scene, save, and exit Godot
- Re-open your project and check the Input Map menu

Your previously-defined key/button will no longer be there.

To go a step further:
- Assign a key/button to your action again
- Add a Label node to the scene, and attach a script that reads your custom action input and changes the text accordingly
- Save and run, and press the assigned key/button

The text won't change.

**Link to minimal example project:**
[testproj.zip](https://github.com/godotengine/godot/files/1036489/testproj.zip)
I've created an action called "button" and assigned the J key to it, but the assignment wasn't saved so you should probably do that yourself before testing it.

**Comment by Zireael07** [comment] 2017-05-29 19:23
Duplicate of #8969?

**Comment by homer666** [comment] 2017-05-29 19:24
Wow, you're right. I searched for Input Map which returned no results. My bad!

**Closed** 2017-05-29 19:26 UTC
