### ISSUE TITLE
"Select Current" in the main scene setting confirmation dialog does nothing if the current scene wasn't saved yet

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#57135] opened 2022-01-24 17:12 UTC
### Godot version

4.0alpha 1

### System information

Debian 11

### Issue description

I create a new project, Then I added a node and when I run it I have this pop-up (as expected):
![image](https://user-images.githubusercontent.com/13235119/150830793-f9ba8116-1385-4819-af81-f90dba36316a.png)

When I click in `select current` 
nothing happen and I sill have the pop-up opened.

### Steps to reproduce

See before.

### Minimal reproduction project

NA

**Comment by Calinou** [comment] 2022-01-24 17:42
I can't reproduce this on `master` fc09d783f.
This is likely due to the same cause as https://github.com/godotengine/godot/issues/57136.

**Comment by git2013vb** [comment] 2022-01-24 17:49
> I can't reproduce this on `master` [fc09d78](https://github.com/godotengine/godot/commit/fc09d783f4e8a6b8978c6971450f26e812268e67).
> 
> This issue is likely due to the same cause as #57136. The project fails to run, so you don't see anything appear on screen.

I don't think so. I think there is a missing step: If I don't have the scene saved "select current" have to be disabled. Or it have to land in save scene page then auto-select the one saved.

**Comment by sairam4123** [comment] 2022-01-24 17:52
> I can't reproduce this on `master` [fc09d78](https://github.com/godotengine/godot/commit/fc09d783f4e8a6b8978c6971450f26e812268e67).
> 
> This issue is likely due to the same cause as #57136. The project fails to run, so you don't see anything appear on screen.

It seems to be a regression, actually select current should open up the save dialog if the scene is unsaved.

**Comment by akien-mga** [comment] 2023-01-12 10:55
This is fixed as of 4.0 beta 11.

**Closed by akien-mga** 2023-01-12 10:55 UTC
Labels: bug, topic:editor, confirmed
