### ISSUE TITLE
AnimationTree AnimationNodeBlendTree skeleton scaling issue with Blend2 and Blend3

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#55838] opened 2021-12-11 21:27 UTC
### Godot version

4.0 dev

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

In 4.0 latest nightly dev build (as of 11 Dec) there is an issue with skeleton scaling when using Blend2 or Blend3 in a AnimationNodeBlendTree in AnimationTree. When blending between 2 animations the skeleton weirdly scales (looks like it's scaling down the root bone in between the blended animations). This issue was not present in Godot 3.4 stable. I used the same gltf import from Blender (skeleton with animations) in 4.0 as in 3.4.

See here: https://www.youtube.com/watch?v=WX0F99OoLQk

### Steps to reproduce

1. Import a gltf character with animations (I used one from Mixamo)
2. Create AnimationTree
3. Select NewAnimationBlendTree
4. Create 2 or 3 Animation nodes
5. Create a Blend2 or a Blend3 node
6. Connect the 2 or 3 animations into the Blend node and to the output
7. Link AnimationTree to AnimationPlayer that have the character animations (inside the imported gltf)
8. Activate the AnimationTree in editor
9. Scrub the Blend back and forth - you will see the skeleton scaling when blending; example here: https://www.youtube.com/watch?v=WX0F99OoLQk

### Minimal reproduction project

Don't have one, just follow the steps above.

**Comment by Calinou** [comment] 2021-12-11 21:36
cc @TokageItLab

**Comment by TokageItLab** [comment] 2021-12-12 00:41
May duplicate of #54407.

**Closed** 2022-03-17 09:49 UTC
Labels: bug, regression, topic:animation, topic:3d
