### ISSUE TITLE
Input map is changed when project is opened on macOS

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#35355] opened 2020-01-20 10:58 UTC
**Godot version:**
3.1, 3.2 RC2

**OS/device including version:**
Mac OS

**Issue description:**
When opening a project with an input bound to CTRL+(letter key), the binding automatically changes to CTRL+Coammand+(letter key). I would expect the input map to be unchanged.

**Steps to reproduce:**
1. Create a project on Linux or Windows with CTRL+g bound to an action (attached example).
2. Open the project on MacOS.
3. The keybinding is now change in the project.godot:
`diff --git a/project.godot b/project.godot
index a92f97e..c5ba98a 100644
--- a/project.godot
+++ b/project.godot
@@ -17,6 +17,6 @@ _global_script_class_icons={

 test_action={
 "deadzone": 0.5,
-"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":true,"meta":false,"command":true,"pressed":false,"scancode":71,"unicode":0,"echo":false,"script":null)
+"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":true,"meta":true,"command":true,"pressed":false,"scancode":71,"unicode":0,"echo":false,"script":null)
  ]
 }
`

**Minimal reproduction project:**
[input-test.zip](https://github.com/godotengine/godot/files/4085789/input-test.zip)
input-test.zip contains a project with the changes Godot on MacOS produces in the unstaged chandes. A git hard reset brings back the project to the state before it was opened on Mac.

**Comment by Calinou** [comment] 2020-01-20 20:23
This one sounds difficult to fix :slightly_frowning_face: 

The issue is that you may want to use either <kbd>Ctrl</kbd> or <kbd>Command</kbd> depending on the desired behavior. Games can probably use <kbd>Ctrl</kbd> everywhere, but a non-game application may want to use <kbd>Command</kbd> so that the modifier is remapped to <kbd>Meta</kbd> on macOS.

**Comment by HEAVYPOLY** [comment] 2020-05-06 22:12
Can confirm here.  I want to use Ctrl Z for ui_undo on windows and linux, every time I open the project to export of mac, the input gets changed to Ctrl Meta Z which confuses windows and linux users.

**Comment by HEAVYPOLY** [comment] 2020-05-06 22:14
![inputmap](https://user-images.githubusercontent.com/24432677/81233679-03da3380-8fac-11ea-8d01-771479054552.JPG)

I think the Project Settings override system would work perfectly here, so you could set the hotkey Per OS like this:
![overrride](https://user-images.githubusercontent.com/24432677/81233762-3c7a0d00-8fac-11ea-81a9-6292586f8325.JPG)

**Comment by HEAVYPOLY** [comment] 2020-08-08 21:50
Is it possible to just not edit the shortcuts at all?  This is really frustrating, any time I open the project on Mac I need to redo all my shortcuts.

**Comment by Calinou** [comment] 2020-08-08 22:02
@HEAVYPOLY If the shortcuts weren't edited, then we'd be using Windows-specific shortcuts in projects running on macOS. It's not a great experience for end users either.

**Comment by HEAVYPOLY** [comment] 2020-08-08 22:25
Ended up working around this by settings the input map in code using 
InputMap.add_action()

**Comment by HEAVYPOLY** [comment] 2020-08-08 22:26
@Calinou Yes I think swapping between Ctrl and Meta would make a lot more sense than Adding Meta to Ctrl

**Comment by HEAVYPOLY** [comment] 2020-08-09 02:53
On this note, I'm trying to change the input with this script:
`    var action = "ui_undo"
    InputMap.add_action(action)
    var ev = InputEventKey.new()
    ev.set_scancode(KEY_Z)
    ev.set_shift(true)
    var ev2 = InputEventKey.new()
    ev2.set_scancode(KEY_Z)
    ev2.set_alt(true)
    InputMap.action_add_event(action,ev)
    InputMap.action_add_event(action,ev2)`

And only the first event (Shift Z) is triggering the action, 2nd doesn't seem to do anything.  Any ideas what could cause this?

**Comment by colugomusic** [comment] 2020-12-03 20:02
Doing nothing at all would be much better than what Godot is currently doing. If the idea is to convert a windows-style keyboard shortcut to its macOS equivalent then simply changing every instance of "control" to "control+meta" doesn't even achieve that.

**Comment by akien-mga** [comment] 2020-12-04 10:23
@EricEzaM Is this fixed by #43662?

**Comment by EricEzaM** [comment] 2020-12-04 10:28
@akien-mga I am confident jn saying yes but I would like to have someone test on Mac first, before closing

**Comment by Schroedi** [comment] 2020-12-10 08:32
Thanks for working on this problem!

Here is the change that happens when I open the sample project with the current master(70c435272):
`-"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":true,"meta":false,"command":true,"pressed":false,"scancode":71,"unicode":0,"echo":false,"script":null)
+"events": [ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"store_command":true,"alt":false,"shift":false,"control":true,"command":true,"pressed":false,"keycode":0,"physical_keycode":0,"unicode":0,"echo":false,"script":null)`
With highlighting:
<img width="1153" alt="Screen Shot 2020-12-10 at 09 30 00" src="https://user-images.githubusercontent.com/97124/101741392-488df600-3aca-11eb-8eb0-2a6e7662dc96.png">

It seems like the keycode (g) is lost. Is this expected?

**Comment by akien-mga** [comment] 2020-12-10 09:02
Yes, we might be able to add some conversion code to preserve compatibility, but 4.0 key events are not compatible with 3.x (`scancode` became `keycode`, and there is now `physical_keycode` too).

**Comment by Calinou** [comment] 2022-01-22 16:07
There is now a way to set a <kbd>Cmd</kbd> modifier in the input map in `master`. <kbd>Ctrl</kbd> should now be kept as-is in the input map.

**Comment by EricEzaM** [comment] 2022-06-30 11:34
That might stick around until this is resolved: https://github.com/godotengine/godot/blob/1e082914e2d8270a415f1408c8e56d4adf520df4/core/input/input_event.h#L114-L127

**Closed** 2022-09-08 07:43 UTC
Labels: bug, platform:macos, topic:core, confirmed, topic:input
