### ISSUE TITLE
New scene doesn't name the root node in PascalCase

### ISSUE THREAD

**Issue by Yelnats321** [godotengine/godot#82741] opened 2023-10-03 19:29 UTC
### Godot version

4.1.1 stable

### System information

N/A

### Issue description

The [project organization style guide](https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html#style-guide) says to name nodes in PascalCase and files in snake_case. If one sets the name of a new scene to be say `scene_one`, the root node of the scene will also be named `scene_one` instead of `SceneOne`.

Although there is a Root Name option in the dialog, it follows convention to automatically rename the root node to PascalCase.

### Steps to reproduce

1. Select Create New>Scene... in the FileSystem view in the editor
2. Set the Scene Name to `scene_one`
3. Press OK
4. Observe that the root node is also named `scene_one`

### Minimal reproduction project

N/A

**Comment by jackwilsdon** [comment] 2023-10-07 19:46
Looks like this is a duplicate of #79751, which should be fixed in 4.2 (#79756).

**Comment by Sauermann** [comment] 2023-10-08 10:58
Consolidating as a duplicate with #79751.

**Closed** 2023-10-08 10:58 UTC
