### ISSUE TITLE
Files imported as custom resource types are not considered as resources

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#20496] opened 2018-07-26 20:55 UTC
First of all sorry if this issue title is unclear. I can't find a better way to describe this in a quick way.

**Godot version:** 832e2bf

**OS/device including version:** Win10 x64

**Issue description:**
Here are possibly related issues I've found: #17395, #6763, #6067
I have this pretty simple plug-in defining a custom resource type and a resource importer.
```gdscript
tool
extends EditorPlugin

var import_plugin

func _enter_tree():
	add_custom_type("InkStory", "Resource", preload("ink_story.gd"), preload("icon.png"))
	import_plugin = preload("import_plugin.gd").new()
	add_import_plugin(import_plugin)

func _exit_tree():
	remove_import_plugin(import_plugin)
	import_plugin = null
	remove_custom_type("InkStory")
```

The import plugin is setting the `resource_type` like so.
```gdscript
tool
extends EditorImportPlugin

[...]

func get_resource_type():
	return "InkStory"

[...]
```

So far, everything's fine.  
The import plug-in works like a charm:
![image](https://user-images.githubusercontent.com/437025/43287595-cb67872c-9125-11e8-88e1-4ab818a06f9c.png)
And the custom resource type is shown in the list of exported properties (I used `export (Resource) var Story`):
![image](https://user-images.githubusercontent.com/437025/43287461-6bac054c-9125-11e8-8a05-a22b9eaa1b6f.png)

However, even once imported, the icon aside the file here does not update (it's updating if the resource_type in the import plug-in is set to a built-in one):
![image](https://user-images.githubusercontent.com/437025/43287573-bd981350-9125-11e8-8fa9-b57ab5ae496c.png)
More importantly, it's impossible to set this file/resource to the previously mentioned exported property (whether it is by drag'n'dropping it or using the `Load` button).

---

Bests ❤️

**Comment by wscalf** [comment] 2020-04-25 00:36
Hello from the future! Dunno if you're past this, but I'm running into something similar now. If you change the type returned from the EditorImportPlugin to "Resource", it lets you use either Load or drag'n'drop to associate a file to a resource slot, as you'd expect. I'm not sure what functionality you might lose by doing that, but at least so far it doesn't seem to hurt anything.

That might be all it takes, though I hit another snag after getting past that - the ResourceSaver doesn't seem to be serializing my resource correctly. I'm using C#, and it's possible it's a C#-specific issue and may not affect you. If it _does_, you can work around it by skipping the ResourceSaver and directly writing the tres file with the information you need to the file system (I used the inspector to generate one and then used it as a template.) I opened a separate ticket about that issue here: https://github.com/godotengine/godot/issues/38191

**Comment by NoodleSushi** [comment] 2020-08-04 04:37
The first arguments passed on `add_custom_type` and `remove_custom_type` are pretty different (`"InkStory"` & `"InkResource"`), is that a typo?

**Comment by paulloz** [comment] 2020-08-04 06:18
> 
> 
> is that a typo?

Yes, it is.

**Comment by AnidemDex** [comment] 2022-04-27 15:34
> However, even once imported, the icon aside the file here does not update (it's updating if the resource_type in the import plug-in is set to a built-in one)

I think that's https://github.com/godotengine/godot/issues/32706

Is this stills relevant @paulloz  ? I can use imported files as resources in exported resource variables
![godot_JHWotF3sN5](https://user-images.githubusercontent.com/7025991/165554641-6f9a6d9c-60e2-4aa2-b1f3-dc9a71289e30.gif)

**Comment by paulloz** [comment] 2022-04-28 06:58
@AnidemDex Will check as soon as I can.

**Comment by AnidemDex** [comment] 2022-04-28 13:47
@paulloz this is the reproduction project https://github.com/AnidemDex/Godot-CustomResource

**Comment by paulloz** [comment] 2022-04-29 06:28
So @AnidemDex, nothing changed AFAIK. Your example works because you are importing things as a `Resource`, not as an actual custom type. As soon as you'll change the return of `get_resource_type` from `Resource` to your custom type extending `Resource` you'll see the same behaviour as described in the original post.

**Comment by AnidemDex** [comment] 2022-04-30 13:48
Maybe is related to this? https://github.com/godotengine/godot-proposals/issues/18#issuecomment-988053877

ClassDB can't found that type in native classes, so is not recognized as resource or that specific resource type

**Comment by Calinou** [comment] 2022-06-27 21:47
Duplicate of https://github.com/godotengine/godot/issues/32706.

**Closed by Calinou** 2022-06-27 21:48 UTC
Labels: bug, topic:core, topic:editor
