### ISSUE TITLE
Cannot return to Theme Editor after adding StyleBoxTexture to a style

### ISSUE THREAD

**Issue by dfedorch** [godotengine/godot#44984] opened 2021-01-07 01:00 UTC
**Godot version:**  Godot Engine v3.2.3.stable.mono.official

**OS/device including version:**

OS: Windows 10 Home build 1909
OpenGL ES 3.0 Renderer: GeForce RTX 2060/PCIe/SSE2

**Issue description:**
I am trying to create a custom style in Godot. I ran into a problem where the theme previewer and "Edit Theme" button is no longer accessible after adding a StyleBoxTexture - Double clicking on the .style resource will then only bring up that style box's TextureRegion editor.

**Steps to reproduce:**
1. Create an empty project and import an image to use as a panel background
2. Right click in the FileSystem viewer and create a new Style resource 
3. Double click on your new theme resource file - Godot will open the theme previewer in the center pane with the preview of UI widgets and the "Edit Theme" menu allowing you to add new styles to the theme. 
![themePreviewer](https://user-images.githubusercontent.com/49380586/103837063-e8eb2200-5058-11eb-9f05-c74de2fb5ceb.png)

4. Add a new StyleBoxTexture style (ex: add a new Panel style to the theme, select StyleBoxTexture type) 
![panelStyle](https://user-images.githubusercontent.com/49380586/103837074-f1dbf380-5058-11eb-8e9d-918bf7c6b772.png)

5. Drag a texture onto the Texture property of your new StyleBoxTexture
6. Go to the TextureRegion editor and edit the texture region
7. From this point, you are no longer able to see the theme previewer or access the Edit Theme menu to add new styles to the theme. Double clicking on the theme file in the FileSystem viewer will bring up the theme's properties in the right pane, but the center pane will always show the TextureRegion editor. Restarting Godot or closing and opening the project does not seem to resolve it.
![afterDoubleClick](https://user-images.githubusercontent.com/49380586/103837915-bd1c6c00-5059-11eb-8d2f-c1f6bcec7dcb.png)

8. What is expected: Double clicking on the theme file should bring up the theme previewer in the center pane with the "Edit Theme" button

**Minimal reproduction project:**
[ThemeEditorBugSample.zip](https://github.com/godotengine/godot/files/5778885/ThemeEditorBugSample.zip)

**Comment by Calinou** [comment] 2021-01-07 01:13
Duplicate of https://github.com/godotengine/godot/issues/28341 ?

**Closed** 2021-01-07 01:13 UTC
Labels: bug, topic:editor, topic:gui
