### ISSUE TITLE
Problem with GDScript line breaking

### ISSUE THREAD

**Issue by fazjaxton** [godotengine/godot#1882] opened 2015-05-11 02:26 UTC
From https://github.com/okamstudio/godot/issues/208, it seems that line breaks in parenthesis should be valid GDScript.  However, the parser does not think so:

![newline_error](https://cloud.githubusercontent.com/assets/244322/7557625/b5033552-f75a-11e4-8619-25464a5d7ad5.png)

If this is intended to be valid syntax, the parser has an error.

**Comment by eska014** [comment] 2015-11-11 00:22
Seems linebreaks in parentheses works only for `if` right now without `\` at the end of the line, not for other expressions including functions. Apparently `for` doesn't accept parens at all.

**Comment by bojidar-bg** [comment] 2017-10-04 14:56
Should have been fixed in #6694. (Effectively a duplicate of #6268)

**Closed by bojidar-bg** 2017-10-04 14:56 UTC
Labels: bug, confirmed, topic:gdscript
