### ISSUE TITLE
Errors in editor status bar use line breaks instead of spaces

### ISSUE THREAD

**Issue by escargot-sans-gluten** [godotengine/godot#25108] opened 2019-01-18 17:38 UTC
**Godot version:**
3.1 beta 2

**OS/device including version:**
ubuntu 18.04.1

**Issue description:**
This. I couldn't find if it was reported by somebody else.
It used to happen in beta 1 and in alphas too.
![statusbar_line_breaks](https://user-images.githubusercontent.com/44414272/51403130-c865ec80-1b4f-11e9-9c6d-625af01053c6.png)

**Steps to reproduce:**
Write invalid code in the editor

**Comment by escargot-sans-gluten** [comment] 2019-01-18 17:46
Oh and it seems to only happen when **not** in distraction-free mode.

**Comment by meld-cp** [comment] 2019-01-18 17:50
The warning text may be wrapping instead of filling the space above the status text.   I recall seeing some discussion about changing the layout, reducing the size of the status text (white) possibly using icons etc. But I'm not sure if this is the result of that or if it's still in the works.

**Comment by Naryosha** [comment] 2019-01-19 01:55
Duplicate of #22302

**Closed** 2019-01-19 09:07 UTC
