### ISSUE TITLE
Editor UI changing by selecting control nodes in main screen

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#59454] opened 2022-03-23 23:30 UTC
### Godot version

4.0.alpha4

### System information

Arch (Linux-lts 5.15.30-1)

### Issue description

When I'm in 2D view and selecting Control nodes in the Scene, the docks (Scene, Inspector, Filesystem,...) just change size. Especially when selecting the Label node, than the sides minimize almost completely making it impossible to see the properties in the inspector.

I'm running Linux with i3 window manager. Not sure if this has anything to do with it as I can not test this on. 

These are some screenshots, in one I have a margin container selected and than I click on the label and the Editor UI becomes like this. Especially with the label it is annoying as resizing is not possible at all.

![Screenshot from 2022-03-24 08-28-36](https://user-images.githubusercontent.com/56970759/159813000-d4ee4f74-4ce2-4f0e-aead-22055740ae65.png)
![Screenshot from 2022-03-24 08-28-45](https://user-images.githubusercontent.com/56970759/159813003-9033aebd-5952-4626-a9ce-f5fd7966aaae.png)

### Steps to reproduce

Just create/open any project in Godot 4.0.

**Comment by Calinou** [comment] 2022-03-23 23:37
Duplicate of https://github.com/godotengine/godot/issues/58052 (fixed in `master`, will be fixed in 4.0alpha5)

>

**Closed by Calinou** 2022-03-23 23:37 UTC

**Comment by voylin** [comment] 2022-03-24 02:27
@Calinou Thanks! Sorry, tried searching for similar bugs but couldn't find the correct words to search for.
