### ISSUE TITLE
[4.4.dev2] Enum names not showing in inspector when used as keys for exported typed dictionary

### ISSUE THREAD

**Issue by moehnked** [godotengine/godot#96936] opened 2024-09-12 21:33 UTC
### Tested versions

4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.22631 Build 22631 - NVIDIA GeFORCE RTX 4070 (GRD  v556.12) - Intel(R) Core(TM) i7-14700KF, 3400 Mhz, 20 Core(s), 28 Logical Processor(s)

### Issue description

while using typed dictionaries, I attempted to use an enum defined in another class as the key type. It works for selecting a key when adding a new element to the dictionary but after its added, it is listed as a number instead of the string name of the enum

![image](https://github.com/user-attachments/assets/f19698dc-b77c-4578-8c9b-2d98b94fc2fc)

![image](https://github.com/user-attachments/assets/23adaeba-9716-420e-b995-ea99d293756f)

I believe that it would make much more sense and be more readable if the string name of the enum were displayed instead of the int equivalent

### Steps to reproduce

1. create an enum
    - E.G `enum MyEnum{t1, t2, t3}`
3. create an exported variable that is a typed dictionary with a key as that enum
   - E.G. `@export var myDictionary : Dictionary[MyEnum, Variant]`
4. attempt to enter elements into the dictionary via the inspector. observe that the key listed is a number instead of the name provided in the enum's declaration once a key-value pair is added to the dictionary.

![image](https://github.com/user-attachments/assets/417ea4c2-7ca5-4a95-bba1-ab86c2a5fd80)

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-09-13 05:43
* Duplicate of #96852.

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2024-09-13 05:43 UTC
