### ISSUE TITLE
BBCode [center] tag doesn't center over multiple lines

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#29278] opened 2019-05-29 09:08 UTC
**Godot version:**

3.1.1

**Issue description:**

```
[center]Text text text text text text text text text text text text text text text text text text text[/center]
```

![image](https://user-images.githubusercontent.com/28724859/58544647-50779500-81c7-11e9-9485-30521977ed9a.png)

Expected the 2nd line to be centered

**Comment by KoBeWi** [comment] 2019-05-29 11:29
Looks like duplicate of #6982

**Closed by KoBeWi** 2019-05-29 11:29 UTC
