### ISSUE TITLE
CollisionPolygon2D fall through with One Way Collision enabled

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#25732] opened 2019-02-09 08:06 UTC
**Godot version:** Godot 3.1 Beta 3

**OS/device including version:** Windows 10

**Issue description:**

![polygoncollision](https://user-images.githubusercontent.com/12462089/52518337-dfde5400-2c7b-11e9-8fd9-8d9836b3cfcc.gif)

**Steps to reproduce:**
Seems to happen only when the body with polygon is moving upwards

**Minimal reproduction project:**

[OneWayPolygonCollision.zip](https://github.com/godotengine/godot/files/2847633/OneWayPolygonCollision.zip)

**Comment by DleanJeans** [comment] 2019-02-23 16:59
[OneWayPolygonCollisionWater.zip](https://github.com/godotengine/godot/files/2897010/OneWayPolygonCollisionWater.zip)

![waterpolygoncollision](https://user-images.githubusercontent.com/12462089/53289270-aa328280-37c6-11e9-8dc1-aebb4d621149.gif)

**Comment by reduz** [comment] 2019-02-23 19:34
Sorry, I quit programming, I'll go open a farm.

**Comment by DleanJeans** [comment] 2019-03-14 08:16
This doesn't seem like `CollisionPolygon2D` exclusive. A `RigidBody2D` character can go through a rectangle `StaticBody2D` wall at times.

**Comment by andrejp88** [comment] 2019-09-19 22:15
I just ran into this same issue. In my case I have a capsule-shaped KinematicBody2D (player) falling through a segment-shaped StaticBody2D. Out of the following 5 segments, it only occurs with the one marked X:
![image](https://user-images.githubusercontent.com/7419746/65284654-21987c80-db32-11e9-8ed7-41ff4bb73c82.png)

That one is at y=130, and if I remove it and place another identical platform at that coordinate, the player falls through again. So it seems to be tied to the position. If I set its "One Way Collision Margin" to 1.4 or higher, then the player won't fall through but will instead rapidly vibrate up and down by 1 pixel while standing on it, so unfortunately that's not a solution.

(Using 3.1.1 stable)

**Comment by njt1982** [comment] 2019-11-01 23:19
I've had some luck by manually replicating this:
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/scene/2d/collision_polygon_2d.cpp#L51-L58

So.. in my case I have a "terrain" which I was trying to apply `ConcavePolygonShape2D` and `ConvexPolygonShape2D` to without success. This terrain is an array of points (defining the heightmap) rendered using `draw_polyline`.
What I am doing now is looping over all the points from zero to `length-1` and creating individual convex triangles for each i, i+1 and a "bottom" vector2.

This seems to have fixed it for mel it's made all my terrain edges "solid".

**Comment by akien-mga** [comment] 2020-01-13 14:18
For the reference, the project in OP no longer reproduces the issue, as it was fixed by cb09abdbbdb.

The project in https://github.com/godotengine/godot/issues/25732#issuecomment-466669002 still reproduces the issue in the current master branch.

**Comment by capnm** [comment] 2020-10-18 03:42
I can confirm  #42574 fixes the issue (broken in 3.2.3.stable)
https://github.com/godotengine/godot/issues/25732#issuecomment-466669002
in the 3.2 branch.

**Closed** 2021-01-07 16:51 UTC
Labels: bug, confirmed, topic:physics
