### ISSUE TITLE
Theme Variations don't appear in Inspector

### ISSUE THREAD

**Issue by MM4096** [godotengine/godot#97668] opened 2024-10-01 01:35 UTC
### Tested versions

- `4.3.stable`
- Not in `4.2`

### System information

Godot v4.3.stable.mono - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) - Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 Threads)

### Issue description

When creating a theme variation through `Theme Editor > Type > + > Theme Name` and overwriting the `Base Type` with another node (tested example: `Button`), the new variation does not appear under the dropdown in the inspector on **buttons** (See below images). The variation can still be used when editing the variation through the text prompt (see below).

Theme variation's existence:
![image](https://github.com/user-attachments/assets/f42e2757-657a-40e7-8941-6da773877e29)

Doesn't appear in inspector:
![image](https://github.com/user-attachments/assets/f8a3c38f-f77d-4c63-b05e-463b9e138c51)

Doing this works though:
![image](https://github.com/user-attachments/assets/fc6b320a-14ca-4703-b5a5-06c1c59afdcf)

**NOTE**: The theme variant was called `red_button`, the first screenshot shows another theme that has `RedButton` instead. This issue still persists, I just posted the wrong screenshot.

### Steps to reproduce

1. Open a new project
2. Create theme
3. Create theme variation
4. See it not appear in the inspector

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment] 2024-10-01 11:36
Duplicate of #96315

**Closed by KoBeWi** 2024-10-01 11:36 UTC
