### ISSUE TITLE
shift-tab no longer bound to `ui_focus_prev`

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#34405] opened 2019-12-17 15:10 UTC
Noticed in Beta3 and master that, while `tab` advances focus, `shift-tab` no longer works. This behavior worked in 3.1.1, and I rely on it for the accessibility plugin. It also probably breaks workflow for any other keyboard-heavy users.

Thanks for looking into this.

**Comment by ndarilek** [comment] 2019-12-17 15:15
Looked into this briefly and it seems like the binding still exists, but it doesn't trigger. Maybe shift state isn't correctly captured?

**Comment by Calinou** [comment] 2019-12-17 17:17
Did it work in previous 3.2 betas or alphas?

**Comment by ndarilek** [comment] 2019-12-17 19:09
Not sure, I just tried Beta3 and master. I know it worked on stable. But 
it fails in both the editor and my own UIs, so should hopefully be easy 
to reproduce.

**Comment by dankan1890** [comment] 2019-12-17 20:31
Broken between beta1 and beta1.99mono.

**Comment by ndarilek** [comment] 2019-12-17 20:42
Are you currently running a bisect?


If not, any chance you have the commit SHA for beta1? It isn't a tag, 
and it'd probably save me half a dozen bisect steps.


Thanks.

**Comment by dankan1890** [comment] 2019-12-17 20:50
At the moment I have no time to work on the code, the commits are:
Beta1 - 077b5f6c2c06bb2c0af525ee25f87e0db719f9d2
Beta1.99 - b7ea22c5d203da1b592a743a4c893de25cd34408

**Comment by akien-mga** [comment] 2019-12-17 21:16
Probably caused by #30721, CC @NilsIrl (I had the feeling that everytime anyone tried to fix this kind of issue a regression popped up..)

**Comment by ndarilek** [comment] 2019-12-17 21:39
```
commit 0024dd7bb5a8a5194ed0283fc506edcd8b4a7737 (refs/bisect/bad)
Merge: cafb888361 24e1039eb6
Author: Nils ANDRÉ-CHANG <nils@nilsand.re>
Date:   Thu Sep 12 21:28:49 2019 +0100
    Merge branch 'master' into tab_key

commit cafb888361eba08297dd88b18dc71f4d418525c0 (HEAD)
Author: Nils ANDRÉ-CHANG <nils@nilsand.re>
Date:   Sat Jul 20 22:32:49 2019 +0100
    Allow tab key to be used for shortcuts
```

**Comment by NilsIrl** [comment] 2019-12-17 21:42
Beat me to it :1st_place_medal: 

So I guess we can just revert the commit? And think about fixing the issue properly. From what I understand, the code that checks for `CTRL+Tab` is at the wrong place and `is_action_pressed` doesn't take into account modifiers

**Comment by NilsIrl** [comment] 2019-12-17 21:47
The problem is that `mods` also is true if `shift` is pressed.

https://github.com/NilsIrl/godot/blob/0024dd7bb5a8a5194ed0283fc506edcd8b4a7737/scene/main/viewport.cpp#L2287-L2302

So a fix could be done that fixes both bugs (current and the one that was meant to be fixed by the #30711 )

But it still isn't a "proper" fix

**Comment by NilsIrl** [comment] 2019-12-17 22:08
Nope, I think I got everything wrong.

Aren't the shortcut the same thing and context dependant?

**Comment by akien-mga** [comment] 2019-12-18 07:25
I think I'll revert the commit for now, I feel like any fix we try right now might have potential for adding other issues.

We can then take the time to reassess this for 4.0 (and possibly a 3.2.x release if we can make a fix that does not break compatibility). Changing modifiers handling in `is_action_pressed` and generally reviewing their handling in `InputEvent` might indeed be necessary for 4.0, there have been many issues around this topic over the years.

**Closed** 2019-12-18 07:31 UTC
Labels: bug, regression, topic:input
