### ISSUE TITLE
load() does not work with relative path using ".." and without "res://"

### ISSUE THREAD

**Issue by PkayJava** [godotengine/godot#5999] opened 2016-08-01 15:44 UTC
**Ubuntu 16.04.2 - compile from the last commit:**

**Steps to reproduce:**

I follow this guide

http://docs.godotengine.org/en/latest/reference/gdscript.html

```
# Load the class resource when calling load()
var MyClass = load("myclass.gd")

func _init():
    var a = MyClass.new()
    a.somefunction()
```

MyClass is always null. 

but if i change to var MyClass = preload("myclass.gd") it works fine.
seems like load is broken now.

**Comment by akien-mga** [comment] 2016-08-01 15:54
Can't reproduce, this works fine for me:
```
var MyClass = load("res://myclass.gd")

func _init():
	var a = MyClass.new()
	a.test()
```

**Comment by supaiku-o** [comment] 2016-08-01 16:37
@akien-mga Without the res:// load returns null, whereas preload works even without res://

**Comment by akien-mga** [comment] 2016-08-01 16:39
For me it works without `res://` too with `load()`, same result.

**Comment by supaiku-o** [comment] 2016-08-01 16:51
Ah, ok. It works if the path is not relative or it's relative, but prefixed with res://
Preload works with relative paths either way.

````gdscript
var x = load("not/relative/item.gd") #=> success
var x = load("../relative/item.gd") #=> null
var x = load("res://../relative/item.gd") #=> success
var x = preload("../relative/item.gd") #=> success
var x = preload("res://../relative/item.gd") #=> success

**Comment by PkayJava** [comment] 2016-08-02 01:56
I could use prefix "res://" for now. I will leave this ticket, you might want to close it.

**Comment by Hinsbart** [comment] 2016-09-25 18:00
I looked into it but it's not trivial to fix.
The thing is, that `preload()` is evaluated during script parsing, so it knows the path of the script in which it's called and is able to work with paths relative to that.
`load()` however is just a normal function and thus has no idea from where it was called.

**Comment by Chaosus** [comment] 2018-08-21 11:18
_(checked) load works as expected in latest master and 2.1.5 - Closed by bugsquad_

**Closed by Chaosus** 2018-08-21 11:18 UTC
Labels: bug, confirmed, topic:core

**Comment by Chaosus** [comment] 2018-08-21 12:00
please note that I closed this issue because attached example

```
# Load the class resource when calling load()
var MyClass = load("myclass.gd")

func _init():
    var a = MyClass.new()
    a.somefunction()
```
is valid, if you have the problem with `load("../myclass.gd")` please comment and I reopen it(or better create a new issue with valid example)
