### ISSUE TITLE
2D bugs 

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#27108] opened 2019-03-16 00:12 UTC
Godot 3.1 stable
Win 7 64 bits.

1) Camera 2D : "Smoothing" parameter 
Checking or Uncheking "Smoothing" on Camera2D node has not effect.
When the game  is playing the player sprite look the same.

2) Weird PNG display bug, while the sprite sheet looks good.
https://postimg.cc/MX4FKL3B

3) Did not found "Pixel Perfect" option for 2D on Camera2D node or in Project Settings -> Window

Project download : 
https://github.com/DevMagicLord/Godot3/blob/master/bugs/A/2DBug.zip

**Comment by eon-s** [comment] 2019-03-16 02:28
Try to make one issue per problem, and be detailed with the title.

2. This is a problem with your imported image, filters or mipmap can do that, the border of the region may bleed on the sides, if you need filters avoid reaching the border of the frame (is normal on every engine), the solution is to reimport the image with the correct settings or correct the image so it has some transparent margin.

See https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/importing_images.html

3. There is no pixel perfect option, what you may be looking for is `2D pixel snap`.

**Comment by Chaosus** [comment] 2019-03-16 07:23
1. If you want have a working Camera2D Smoothing property then you need to actually moves the camera, in the provided example you just moves sprite - attach the camera to player if you want to see this effect

2. Its already been reported a million times, and its not a bug(just a common filtering problem); just toggle this checkbox in Import tab of the image:
![image](https://user-images.githubusercontent.com/3036176/54472028-ffb0ec80-47d2-11e9-8a39-4e20f72cb300.png)

3. Its not clear what do you mean about "Pixel perfect" in respect of Camera2D. Please create a separate issue and describe it in details. 

I thinks its "fixed" and I close this

**Closed by Chaosus** 2019-03-16 07:23 UTC

**Comment by stevematdavies** [comment] 2019-06-04 09:11
For mac with 3.1, this doesn't improve the image, there still seems to be "fuzzy" edges as if it was processed as mipmap with filter. The Pixel perfect he is mentioning means a clean no antialiased image /texture. 
Yes its been reported a lot but the fix above isn't working all the time. 

When you reload the image on occasion, after such a fix, often the image / texture is removed.

**Comment by Chaosus** [comment] 2019-06-04 12:30
Then you should open a new issue ^^ the original is too general and not detailed
