### ISSUE TITLE
Editing collapsed line expands the collapsed line above it

### ISSUE THREAD

**Issue by CianFlint** [godotengine/godot#100906] opened 2024-12-29 16:46 UTC
### Tested versions

v4.3.stable.official.77dcf97d8

### System information

Windows 10

### Issue description

Editing collapsed line expands the collapsed line above it

### Steps to reproduce

If you have 2 collapsed lines of code in the godot script editor and press the backspace anywhere on the collapsed line below, the collapsed line above will expand

### Minimal reproduction project (MRP)

any godot project script with 2 neighboring collapsed indents

**Comment by Saulo-de-Souza** [comment] 2024-12-29 17:07
When you hit the backspace key on the line below a collapsed code, what you do is simply go to the top line, and once you go to the top line, which is collapsed code, you are editing that line, therefore the editor expands the collected code. This behavior is normal, in my opinion.
If the collapsed code was not expanded, you would not see the mouse cursor in the form of an edit, generating unexpected behavior.

**Comment by kitbdev** [comment] 2024-12-30 16:40
- looks like a duplicate of https://github.com/godotengine/godot/issues/89522
- fixed by https://github.com/godotengine/godot/pull/89554

**Comment by CianFlint** [comment] 2024-12-30 17:16
> When you hit the backspace key on the line below a collapsed code, what you do is simply go to the top line, and once you go to the top line, which is collapsed code, you are editing that line, therefore the editor expands the collapsed code. This behavior is normal, in my opinion. If the collapsed code was not expanded, you would not see the mouse cursor in the form of an edit, generating unexpected behavior.

it expands when backspace doesn't change lines

**Closed** 2024-12-30 17:20 UTC
