### ISSUE TITLE
Typing field while editing string on exported dictionary in inspector doesn't stay focused.

### ISSUE THREAD

**Issue by averyraddeveloper** [godotengine/godot#78807] opened 2023-06-28 18:24 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3598) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

For an exported dictionary, when adding a new key/value pair with a String, trying to type the string results in the field becoming unfocused after every character typed. 
This happens when the string is the key or in the value.
This issue causes you to have to click into the typing field each time you enter a character.

### Steps to reproduce

This can be recreated in a blank project by exported a blank dictionary and trying to edit it in the inspector.

```
extends Node2D

@export var blank_dictionary = {}
```

### Minimal reproduction project

No need for example project.

**Comment by AThousandShips** [comment] 2023-06-28 18:32
* Duplicate of: #78712

**Closed by AThousandShips** 2023-06-28 18:32 UTC
