### ISSUE TITLE
Input mapping mouse scroll wheel combinations ignores the combination (such as shift+mouse scroll wheel), and acts as if it's just scroll wheel.

### ISSUE THREAD

**Issue by Ewsername** [godotengine/godot#88031] opened 2024-02-06 19:58 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3758) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Input mapping the scroll wheel and using it with Input.is_action_pressed("scroll_wheel") while also input mapping shift+mouse scroll with Input.is_action_pressed("shift_scroll_wheel") will ignore the combination of shift+mouse scroll wheel.
Let's say i have two lists of nodes in separate indexes (index A, and B), i want to scroll through the nodes in index A using the mouse wheel up and down with Input.is_action_just_pressed("scroll_wheel").
This works.
But if i also map shift+mouse wheel scroll for the other index (index B) in a different function and scroll through with  Input.is_action_just_pressed("shift_scroll_wheel"), then when i scroll holding shift i also scroll through the other index (index A) at the same time as if the engine completely ignores the fact that I'm pressing the shift button+scroll wheel.
This is also true for the other combinations such as ctrl and alt.

I've provided a project file that shows this in action.

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/159178256/b5d8169c-2446-48d8-8e62-44ebed06f6a0)
Left hand index.

![image](https://github.com/godotengine/godot/assets/159178256/8cd91bc6-6e29-4cf2-aa70-0195c00d55cb)
Right hand index.
The names "switch tool right/left" is just for whatever hand the script is in.

![image](https://github.com/godotengine/godot/assets/159178256/aa20553a-357d-41b5-b8ba-4d5d0389ce14)
Input mapping.

![image](https://github.com/godotengine/godot/assets/159178256/b7135fa3-24da-4c8a-9015-0a00369341e5)

The nodes can be anything and contain anything, like a MeshInstance3D or AnimationPlayer or whatever.

### Minimal reproduction project (MRP)

[BugReport.zip](https://github.com/godotengine/godot/files/14185447/BugReport.zip)

**Comment by AThousandShips** [comment] 2024-02-06 20:16
Can you try with released instead? If so then it's a duplicate of:
* https://github.com/godotengine/godot/issues/36322

**Comment by Ewsername** [comment] 2024-02-06 20:46
> Can you try with released instead? If so then it's a duplicate of:
> 
>     * [Scroll wheel up or down .is_action_just_pressed() does not register #36322](https://github.com/godotengine/godot/issues/36322)

Yes, tried it now with release.
With release both lists are affected (looping through both index lists) no matter if holding shift while scrolling or not.

I've had to resort to using numeric buttons for one hand and the scroll wheel for the other for now.

If this is the same behavior as the other thread suggests then we can close this one.

**Comment by Sauermann** [comment] 2024-02-06 22:10
I have tested the MRP on Linux X11 Xfce with v4.3.dev.custom_build [d3352813e] and can confirm the described behavior:
- Without shift-key it works as expected
- When I hold the shift-key down, the mouse wheel causes the left hand and the right to change.

However this behavior is expected.
To ensure, that shift and the other modifier keys are respected, change your functions to:
``` gdscript
if Input.is_action_just_pressed("switch_tool_right", true):
```
by adding a second parameter and set the second parameter to `true`. 
You will find additional details in the documentation of the function: https://docs.godotengine.org/en/latest/classes/class_input.html#class-input-method-is-action-just-pressed.

Can you please test, if this solves your problem?

**Comment by Ewsername** [comment] 2024-02-06 23:10
Thank you, this solves the issue. Both on pressed and just pressed.
You learn something every day.

**Comment by Sauermann** [comment] 2024-02-06 23:12
Good to hear that. Closing issue based on previous post.

**Closed by Sauermann** 2024-02-06 23:12 UTC
Labels: discussion, topic:input
