### ISSUE TITLE
The Project Manager window is no longer resized to follow the editor scale

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47387] opened 2021-03-26 13:25 UTC
**Godot version:**

166a6d0

**Issue description:**

This seems to apply only in 4.0, but the recent editor scale change for 4ks made the Project Manager really cramped:
![image](https://user-images.githubusercontent.com/2223172/112637377-6182a300-8e3e-11eb-95cf-decd93fa0e10.png)
Here's in 3.x:
![image](https://user-images.githubusercontent.com/2223172/112637651-ac041f80-8e3e-11eb-8c36-649e71e1cfcc.png)
(the window is bigger by default)

Some dialogs have this problem too.

**Steps to reproduce:**
1. Buy 4k display
2. Open Godot

**Comment by Calinou** [comment] 2021-03-26 13:39
It seems the window is no longer automatically resized depending on the editor scale in `master`.

**Comment by likeich** [comment] 2021-03-26 17:43
I'm currently working on this. I've narrowed the problem down to line 2429 in project_manager.cpp		

`DisplayServer::get_singleton()->window_set_size(DisplayServer::get_singleton()->window_get_size() * MAX(1, EDSCALE));`

3.3 is (correctly) setting the window size to 1536x900 on 4k monitors. Master is setting it to 1024x600.

Will be looking into this further.

**Comment by likeich** [comment] 2021-03-26 19:22
It looks like it's a regression with Vector2i because `DisplayServer::get_singleton()->window_get_size() * MAX(1, EDSCALE)` always returns the original window size whereas in 3.3 it will actually multiply by whatever the scale value turns out to be and return the correct value. 

I have a workaround fix for this issue ready to go. Working with the multiplication code is over my head though and it'd probably be better to fix it there.

@Calinou any advice?

**Comment by Calinou** [comment] 2021-03-26 20:38
> any advice?

I don't know what would be the best course of action to fix Vector2i multiplication, sorry. In the meantime, you can multiply the components separately.

**Comment by likeich** [comment] 2021-03-27 01:14
Got it, that was my workaround. Will submit a PR.

**Closed** 2021-03-27 07:46 UTC
Labels: bug, regression, topic:editor, usability
