### ISSUE TITLE
Material is not saved when re-loading project in draw passes in Particles . .

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#41784] opened 2020-09-05 10:24 UTC
**Godot version:**
3.2.2 stable . .

**OS/device including version:**
nVidia Geforce GTX 1050 Ti, Windows 10, Intel i5 processor . .

**Issue description:**
When I load the game again, from the start menu, ie. start Godot again, the particles ' forget ' that ' material ' I assigned to it, for some reason . .

![2020-09-05 1217](https://user-images.githubusercontent.com/61069740/92303125-5172a700-ef72-11ea-8b22-2d88be272a94.gif)

Then, I have to re-place the spatialmaterial I made, so it looks like I wanted to, maybe there's a bug, where the ' Particles ' node doesn't correctly save the ' materials ' one has added to it, not sure, it's supposed to look like this, but when I save, and re-start Godot, it goes back to ' no ' material ? . .

![2020-09-05 1218](https://user-images.githubusercontent.com/61069740/92303139-7a933780-ef72-11ea-8e7b-689ee54f6e19.gif)

Not sure where the problem is, seems like a bug, but I'm not expert <3 . .

**Steps to reproduce:**
Make a particle system ( not CPUParticles, but GPUParticles ), add a mesh, an .obj from Blender, think it also happens if it's a Godot primitive, cubemesh, planemesh, and change the material, then save the project, exit, and go back in, it sort of over-rides what one has made, and uses a basic, non-colored material, instead, not sure why . . .

**Minimal reproduction project:**
Like above . .

**Comment by jasperbrooks79** [comment] 2020-09-05 10:31
I've tried exporting the .obj from Blender, with no material .mtl, and it doesn't work . . For some reason, if one adds a new material, to the particle, in ' draw passes ', it doesn't save it, when exiting program, can't make it work . . :( :( . . . Sry . . .

**Comment by jasperbrooks79** [comment] 2020-09-05 10:45
Made it work, by going into the ' Geometry ' settings, below ' Draw passes ' in inspector, and setting it there, seems to work . . This would be a problem with players re-loading the game, as well, not sure . . Anyway, there's a work-around, took some time, found those settings by accident some months ago . .

I'm not sure, what I was doing wrong, when I tried to do it, the ' normal ' way, in ' Draw passes ' > set material . . :O :O . . .

**Comment by Calinou** [comment] 2022-11-04 23:18
Duplicate of https://github.com/godotengine/godot/issues/27556 and possibly others.

**Closed by Calinou** 2022-11-04 23:18 UTC
Labels: bug, topic:editor, needs testing, topic:particles
