### ISSUE TITLE
godot project manager empty

### ISSUE THREAD

**Issue by master172** [godotengine/godot#52005] opened 2021-08-23 06:52 UTC
### Godot version

3.3.3

### System information

Windows10 core i5 nvidia geforce gtx 1650

### Issue description

well lets be simple once while working on a project on a project i decided to take a brake and watch some YouTube but when i reopened godot the project manager was empty it had like 10 projects just a hour earlier i thought that has a simple bug and left it some weeks later when i did a disk cleanup and opened godot the project manager was empty again but i don't think that it happened because of the disk cleanup since i do it a lot and nothing actually ever happened to godot because of the disk cleanup + the first time i didn't even use disk cleanup now just yesterday when i restarted godot the project manager was empty again it just happens automatically

### Steps to reproduce

i don't think we can reproduce it since it happens randomly 

### Minimal reproduction project

not available since its a project manager issue and not a project issue and i use only the stable versions

**Comment by Calinou** [comment] 2021-08-23 09:49
Duplicate of https://github.com/godotengine/godot/issues/40968 (same cause).

**Closed by Calinou** 2021-08-23 09:49 UTC
