### ISSUE TITLE
_can_drop_data not called in sub-viewports

### ISSUE THREAD

**Issue by Splagoon** [godotengine/godot#68063] opened 2022-10-30 20:19 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

When dragging and dropping controls inside a `SubViewport` (inside a `SubViewportContainer`), dragging a control will call `_get_drag_data` as expected, but dragging over other controls never calls `_can_drop_data`. This was not the case in Godot 3.5, where dragging and dropping controls in a `ViewportContainer` worked as expected.

### Steps to reproduce

Two sample projects are included:

- DragAndDropRepro3 was built using `v3.5.1.stable.official [6fed1ffa3]` and works as expected
- DragAndDropRepro4 was built using `v4.0.beta3.official [01ae26d31]` and calls `_get_drag_data` as expected but never calls `_can_drop_data` nor `_drop_data`

### Minimal reproduction project

[DragAndDropRepro.zip](https://github.com/godotengine/godot/files/9896741/DragAndDropRepro.zip)

**Comment by Sauermann** [comment] 2022-10-30 20:40
Will be solved by #67531

**Comment by KoBeWi** [comment] 2022-10-30 20:57
Duplicate of #28522

**Closed by KoBeWi** 2022-10-30 20:57 UTC
