### ISSUE TITLE
Godot built-in drawing tool

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30954] opened 2019-07-30 08:35 UTC
Godot buld-in simple painting tool( at now,if i need to make a draft role/ui in project, i need open any outside drawing software and import some draft in my project, is some troubles, if Godot have buld-in simple drawing tool (likes GameMakerStudio) is should be convenient

**Comment by Faless** [comment] 2019-07-31 11:42
Isn't this a duplicate of #6477 ?

**Comment by akien-mga** [comment] 2019-07-31 11:56
Yes, duplicate of #6477. Sprite editing is outside the scope of Godot's features, at least for the time being.

**Closed by akien-mga** 2019-07-31 11:56 UTC
Labels: feature proposal, topic:editor
