### ISSUE TITLE
[4.0 RC2] TouchScreenButton not working on macOS or iOS

### ISSUE THREAD

**Issue by johnnyw** [godotengine/godot#73562] opened 2023-02-18 17:49 UTC
### Godot version

4.0 RC2

### System information

macOS Ventura 13.1 on M1 Max MacBook Pro, iOS 16 on iPhone 13 Pro

### Issue description

`TouchScreenButton` does not appear to be triggering the action as expected on macOS or iOS devices with a project made in Godot 4.0 RC2. `TouchScreenButton` works as expected on the same platforms using the current 3.5.1 official build of Godot for macOS. Attached are minimal reproduction projects for both Godot 4 and Godot 3.

In both projects, "Emulate Touch from Mouse" are selected in the project's Input Devices -> Pointing options.

### Steps to reproduce

Open the projects in their respective versions of the Godot editor on macOS Ventura and try to interact with the button. It works in 3.x but doesn't work in 4.x. The results appear to be consistent on macOS and iOS in either case.

### Minimal reproduction project

[TouchButtonDemoGodot4.zip](https://github.com/godotengine/godot/files/10774860/TouchButtonDemoGodot4.zip)
[TouchButtonDemoGodot3.zip](https://github.com/godotengine/godot/files/10774861/TouchButtonDemoGodot3.zip)

**Comment by Sauermann** [comment] 2023-02-18 19:40
This is likely a duplicate of #73457

**Closed** 2023-02-18 22:44 UTC
