### ISSUE TITLE
Editing autotile properties doesn't actually change/apply them.

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#24200] opened 2018-12-07 02:07 UTC
**Godot version:** 3.0.6
**OS:** Windows 8.1 Enterprise, 64-bit CPU

**Issue description:**
Editing auto-tiles doesn't actually change any of the properties. The editor shows the changes (eg. newly-added collision polygons); when I save and run, the game runs as if those changes don't exist.

Closing Godot and reloading my project reloads without any of those changes.

**Steps to reproduce:**
- Clone [this commit of my project](https://github.com/nightblade9/eman-quest/tree/60fb116b1e886af2a9c8e3b2edeec1679a2415a7)
- Open `res://Tilesets/AutoTileTilesets.tscn` in the 2D editor
- Open the tileset on either the `CastleDungeon` or `DesertDungeon` tilemaps
- Click the `Autotiles` tab at the bottom of Godot, and edit anything - for example, add/remove collision polygons.
- Scene > Save all Scenes, and run the game.

Expected: the collision changes apply. Running `git diff` should show some changes.
Actual: none of the collision changes apply. `git diff` shows no changes on disk.

I worked around this issue by changing the `Properties` of the auto-tile itself: I set the `Spacing` from 0 to 1 to 0, saved, and I can see my changes are flushed to disk (eg. `git diff`).

**Minimal reproduction project:** [Git commit](https://github.com/nightblade9/eman-quest/tree/60fb116b1e886af2a9c8e3b2edeec1679a2415a7) or [zip](https://www.sendspace.com/file/9r4en6)

**Comment by xDGameStudios** [comment] 2018-12-07 10:45
Autotiles is a resource, you said you saved all the scenes.. did you save the “TileSet” resource?

**Comment by nightblade9** [comment] 2018-12-22 22:39
I just want to add that in the two weeks since I opened this, I can reproduce it several times with different tilesets. I thought it was a very isolated bug, but it seems to occur very frequently. Thankfully, the workaround is pretty easy and works well.

**Comment by KoBeWi** [comment] 2020-06-29 23:33
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

(whole game doesn't count as minimal project btw)

**Comment by KoBeWi** [comment] 2020-09-28 22:21
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:21 UTC
Labels: bug, topic:editor
