### ISSUE TITLE
Raycast cannot collide with GridMap until the second physics frame

### ISSUE THREAD

**Issue by dashdotdashdot** [godotengine/godot#77872] opened 2023-06-05 10:50 UTC
### Godot version

4.0.3.stable

### System information

macOS Ventura 13.4 (22F66)

### Issue description

Raycasts performed with either World3D's `DirectSpaceState.IntersectRay` method or a RayCast3D do not collide with any GridMap-placed static bodies on the first physics frame. However, raycasts *will* collide on the first physics frame when those same bodies are placed directly.

From the second physics frame onward, raycasts collide with the GridMap-placed bodies as expected.

I'd expect that, as long as the GridMap has become ready and collision layers/masks/ etc. are all correct, raycasts should collide with its placed bodies on the first physics frame, just like those raycasts collide with non-GridMap StaticBody3D instances.

Although the attached MRP is GDScript-only, I've confirmed this happens identically in both GDScript and C#.

### Steps to reproduce

1. Create a MeshLibrary that includes meshes with appropriate PhysicsBody3D-derived and CollisionShape3D children.
2. Assign that MeshLibrary to a GridMap and place those meshes into a scene.
3. On the first physics frame, use World3D's `DirectSpaceState.IntersectRay` method to raycast through one of the placed meshes, ensuring that its mask is set to include the GridMap instance's collision layer. Observe that the raycast's result is empty.
5. On the second physics frame, perform the same raycast again. Observe that the raycast's result indicates collision with the GridMap.
6. (optional) Copy the mesh in question directly into the test scene instead of placing it with the GridMap. Observe that a raycast made on the first physics frame will return a result indicating collision with the directly-placed mesh.

### Minimal reproduction project

[GridMapRaycastMRP.zip](https://github.com/godotengine/godot/files/11651657/GridMapRaycastMRP.zip)

**Comment by AThousandShips** [comment] 2023-06-05 10:54
* Duplicate of #76349

**Comment by smix8** [comment] 2023-06-05 11:25
The reason why it works for a single e.g. StaticBody is because a single body can run its own server setup directly on object creation and has not to wait until it is joining the SceneTree.

All the combined "Mega-Nodes" in Godot (e.g. GridMap, TileMap, ...) can not do that. Those nodes first need to enter the SceneTree and load their resources e.g. TileSet, MeshLibrary, ....

The single StaticBody is already part of the very first server sync followed by the very first physics_process() callback.
All the SceneTree nodes that run their setup inside the tree are just sending data at that point so they can only be available on the next server sync / next physics_process() callback.

**Comment by dashdotdashdot** [comment] 2023-06-05 11:46
> All the combined "Mega-Nodes" in Godot (e.g. GridMap, TileMap, ...) can not do that. They also need to deferred some of their setup to not get the servers stuck e.g. RenderingServer when threaded. Those nodes first need to enter the SceneTree and load their resources e.g. TileSet, MeshLibrary, .... before they even start to create their server objects.

I see - it sounds like a "mega-node" that has fired its ready function is not necessarily completely ready, or at least not ready to collide. That being the case, is there any way to know when such "mega-nodes" *are* ready to collide (a different callback perhaps) or is it a matter of waiting some number of physics frames? If the latter, is there a way to know how many physics frames one must wait?

**Comment by smix8** [comment] 2023-06-05 12:37
Depends on the node but in general you can listen or await for the SceneTree `physics_frame` or `process_frame` signals.

**Comment by dashdotdashdot** [comment] 2023-06-05 14:38
> Depends on the node but in general you can listen or await for the SceneTree `physics_frame` or `process_frame` signals.

Thank you very much. In my case, the raycasts always seem to be able to collide with the GridMap if I don't fire them until the SceneTree emits the `physics_frame` signal, which usually happens around physics frame 3~4 in my MRP.

Please excuse me if this is a silly question, but to clarify for the sake of others possibly looking at this later, the docs for SceneTree's `physics_frame` signal state that it is

>Emitted immediately before Node._physics_process is called on every node in the SceneTree.

Since both my scene's top-level node's and my GridMap's `_physics_process` are being called from physics frame 1 onwards, and I only see `physics_frame` emitted on physics frame 3, does this mean that there's some additional, presently-undocumented meaning to `physics_frame` and `process_frame`?

**Comment by dashdotdashdot** [comment] 2023-06-05 15:22
I can't say I'm terribly familiar with Godot's mythology, urban or otherwise, but my question is not about visual frame vs. physics "frame" ("frame" here used because it's the term Godot uses) timing. Rather, it's about why `physics_frame` - which the documentation states is emitted before `_physics_process` is called on every node in the SceneTree - does not make an appearance until `_physics_process` has already been called several times, and why it seems to be related somehow to whether these "mega-nodes" like GridMap have finished setting themselves up.

**Comment by smix8** [comment] 2023-06-05 15:46
I don't encounter this. The signal is emitted just fine starting with physics_frame 0 at engine start.
You can create a mini project that shows the issue and share / attach it here.

**Comment by dashdotdashdot** [comment] 2023-06-05 16:11
> You can create a mini project that shows the issue and share / attach it here.

My apologies; I thought I had connected to `physics_frame` but had actually connected to `process_frame`. Awaiting `physics_frame` does indeed drop us in on the first physics frame, where the raycasts are not yet able to collide with the GridMap.

But clearing this mistake leaves the main part of my question, *mutatis mutandis*, intact: Why is it that awaiting the SceneTree's `process_frame` gives us assurance that the "mega-nodes" like GridMap are "truly ready"? Is it that this signal is only emitted after they've finished completely setting up, or does it just so happen that awaiting it gives us a better-than-average chance of having waited long enough for that to have happened?

**Comment by smix8** [comment] 2023-06-05 16:31
If a node or script makes a deferred call those are placed in the message_queue.
The message_queue is flushed on specific points in the main loop.

It is always flushed directly after a `_process()` callback before the RenderingServer syncs and renders a visual frame.
It is also flushed at the end of each physics iteration before and after the PhysicsServer sync.

If physics does not see a need to run another iteration you will have to wait with possibly multiple frames of 0 physics iterations that could trigger the physics_frame signal.

**Comment by dashdotdashdot** [comment] 2023-06-05 16:45
> It is always flushed directly after a `_process()` callback before the RenderingServer syncs and renders a visual frame. It is also flushed at the end of each physics iteration before and after the PhysicsServer sync.
> 
> If physics does not see a need to run another iteration you will have to wait with possibly multiple frames of 0 physics iterations that could trigger the physics_frame signal.

That's a very good explanation of why visual frames and physics frames are not the same; it is true, correct, and is sure to be useful to someone. But, forgive me, I do not see in it a way to answer the question of why awaiting `process_frame`, as advised, should provide assurance that "mega-nodes" like GridMap are "truly ready" (or whatever you want to call that state in this issue's context - fully set up? Collidable? take your pick). If you did answer in referencing the various -Servers and their syncs, I'm afraid I don't possess a full enough understanding of Godot's internals to recognise it.

If awaiting `process_frame` leaves one with only a partial *chance* that the "mega-nodes" in question are fully set up, then that's fine - but it's necessary to know that it's just a useful delay tactic. Likewise if it *does* provide assurance - armed with that knowledge, one can then rely upon it.

**Comment by smix8** [comment] 2023-06-05 21:34
> Depends on the node but in general you can listen or await for the SceneTree physics_frame or process_frame signals.

That was a generalized statement how to keep track of syncs in the main loop.

There is no assurance cause it all depends on node and context. E.g. in a perfect situation the GridMap can setup everything on NOTIFICATION_ENTER_WORLD where it builds its octants and grid cells and sends the collision shapes to the PhysicsServer so if you are only interested in the collision shapes for a raycast you often only need to wait for the next physics frame signal. Now if you are also interrested in the other parts of the GridMap updating correctly like the visual meshes you need to wait for the process_frame as well because not all is done in the physics frame.

If anything happens meanwhile like a transform, cell or item change the GridMap resets the affected quadrants. This e.g. deletes all those quadrant collision shapes, navigation meshes and baked cell meshes and starts over with the quadrants which makes you wait for another frame.

TileMap is even worse in that it also does a deferred call for the quadrant update. So you not only need to keep track of the signal but also when the next message queue flush can happen else you will need to wait for more than one frame and signal.

**Comment by dashdotdashdot** [comment] 2023-06-06 04:22
Great, that's how I thought it might work. Thanks for clarifying.

**Comment by Calinou** [comment] 2023-06-09 19:40
Closing in favor of https://github.com/godotengine/godot/issues/76349.

**Closed by Calinou** 2023-06-09 19:40 UTC
