### ISSUE TITLE
GDScript syntax highlight broken by a quote in a comment

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#18008] opened 2018-04-05 21:05 UTC
**Godot version:**
`master` branch commit eaa5dfbdbd1217d62902f966496658770638c3d1

**Issue description:**
The GDScript syntax highlighting seems to have been broken recently.

**Steps to reproduce:**
1. Insert only one single quote (i.e. `'` ) or one double quote (i.e. `"`) in a comment
2. All the lines after the single quote get highlighted as strings.

**Minimal reproduction project:**
[broken_highlight.zip](https://github.com/godotengine/godot/files/1881857/broken_highlight.zip)

**Comment by vnen** [comment] 2018-04-05 21:52
Duplicate of #17983

**Closed by vnen** 2018-04-05 21:52 UTC
