### ISSUE TITLE
Add classes as export hints

### ISSUE THREAD

**Issue by menip** [godotengine/godot#29912] opened 2019-06-19 22:07 UTC
### Issue
Currently you can `export var my_button` and even `export(NodePath) var my_button` but not `export var my_button:Button` or (understandably) `export(NodePath) var my_button:Button`.

### Proposal
Would be convenient to be able to specify what class the node you need should extend.

### Example
As an example, I currently have following in my game:

    onready var play:Button = $HBox/VBox/Buttons/Play
    onready var status:Label = $HBox/VBox/PanelContainer/VBox/Status

    # More convenient would be one of these:
    export var play:Button
    export var status:Label

    # Or
    export(Button) var play
    export(Label) var status

    # Why not both
    export(Button) var play:Button
    export(Label) var status:Label

This could also be used for classes defined via `class_name` in scripts, though I currently don't have use case example.

--------------------------------------------------------------------------------------------------------
Note: Note sure how to properly phrase title.

**Comment by bojidar-bg** [comment] 2019-06-19 22:35
Duplicate of #7821 (the node part), and #22641 (custom _resource_ script)

**Closed by bojidar-bg** 2019-06-19 22:35 UTC

**Comment by menip** [comment] 2019-06-19 22:44
@BastiaanOlij 
Does #22641  cover case of:

    # A.gd
    extends Object
    class_name My_Class

    B.gd
    export(My_Class) var thing

I see that it's covering scripts that `extend Resource`, but couldn't make out if it would generalize to all classes.

**Comment by bojidar-bg** [comment] 2019-06-20 09:20
Well, it is impossible to export a variable of type Variant::TYPE_OBJECT, unless it extends Resource.
If exporting Node-typed variables (which are internally converted to NodePath-s) is added, I suppose that custom-Node-typed variables would be discussed as well.
But, exporting Object-typed variables is likely never going to work, since Object-s require manual memory management. Reference-typed variables are also likely to not be exportable, since they are not expected to be serialized inside the scene.
