### ISSUE TITLE
Javascript Target Error

### ISSUE THREAD

**Issue by primesoftware** [godotengine/godot#5714] opened 2016-07-15 05:02 UTC
I tried building the Javascript target which looks like it worked ok. Some warnings but nothing that broke the build. When I tried to test in Firefox, I got nothing but a gray screen and the following error

```
let it go!
has res dir: 
exists engine cfg? 0
Init OS
Init Audio
Init VS
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_sRGB
EXT_texture_filter_anisotropic
GL_ANGLE_instanced_arrays
GL_EXT_blend_minmax
GL_EXT_color_buffer_half_float
GL_EXT_frag_depth
GL_EXT_sRGB
GL_EXT_texture_filter_anisotropic
GL_MOZ_WEBGL_compressed_texture_s3tc
GL_MOZ_WEBGL_depth_texture
GL_MOZ_WEBGL_lose_context
GL_OES_element_index_uint
GL_OES_standard_derivatives
GL_OES_texture_float
GL_OES_texture_float_linear
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_vertex_array_object
GL_WEBGL_color_buffer_float
GL_WEBGL_compressed_texture_s3tc
GL_WEBGL_depth_texture
GL_WEBGL_draw_buffers
GL_WEBGL_lose_context
MOZ_WEBGL_compressed_texture_s3tc
MOZ_WEBGL_depth_texture
MOZ_WEBGL_lose_context
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
S3TC: 1 ATITC: 0
Init SM
WEBAUDIO MIX RATE: 48000
Init Mixer
Init SoundServer
Init SpatialSoundServer
Init Physicsserver
[1;31mERROR: set_locale: [0m[1mCondition ' !is_valid_locale(p_locale) ' is true.
[0;31m   At: core/translation.cpp:508.[0m
FS SYNCHED!
```
Everything else seemed to initialize OK. I built the latest codebase from Github on Linux x64 with latest EMCC.

**Comment by akien-mga** [comment] 2016-07-15 05:34
The `set_locale` issue is likely a duplicate of #2477, though the message changed a bit.

About having only a grey screen, it could be a duplicate of #3918 or #3570. The emscripten export has lot of issues and will be worked on for 3.0.

**Comment by akien-mga** [comment] 2016-07-18 08:17
Closing as duplicate of the aforementioned issues.

**Closed by akien-mga** 2016-07-18 08:17 UTC
