### ISSUE TITLE
animationPlayer bezier track impact other animations if they don't have this track

### ISSUE THREAD

**Issue by waterdu** [godotengine/godot#32521] opened 2019-10-03 13:35 UTC
**Godot version:**
3.1.1 stable
**OS/device including version:**
windows 10
**Issue description:**
animationPlayer bezier track impact other animations if they don't have this track
For example, this animation attack rotate sprite degree 90. 
The new animation would be impacted if it doesn't have default rotate degree key inserted.

**Steps to reproduce:**
Say if I have 10 animations in the animationPlayer.
I edit one animation to add the sprite rotation degree 90 track.

However, this impact my other animations sprite to rotate 90 degree.
To prevent this I have to add rotation degree 0 to all of my other animations.

Same issue happened to other key feature as well. I'm very frustrated to edit the frame.
Every time I add one animation I have to edit my existed animations default frame.
**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2019-10-22 14:04
Related/duplicate of #812

**Comment by golddotasksquestions** [comment] 2019-10-24 15:08
This bug is wasting a lot of my time as I have to create tracks in all my animations for a property need in only one animation.

**Comment by KoBeWi** [comment] 2020-10-28 00:47
Ok this really looks like duplicate of #812
There's a proposal with a PR that will likely fix this https://github.com/godotengine/godot-proposals/issues/1597

**Closed by KoBeWi** 2020-10-28 00:47 UTC
Labels: bug, topic:editor
