### ISSUE TITLE
Duplicating keyframes on the animation tab with CTRL + D crashes Godot

### ISSUE THREAD

**Issue by Bones404** [godotengine/godot#59298] opened 2022-03-18 20:39 UTC
### Godot version

4.0-alpha4

### System information

Windows 10, GLES3

### Issue description

When using the shortcut CTRL + D on a keyframe, Godot crashes. Happens with all types of keyframe tracks.
The keyframe should be duplicated on the spot where the playhead is.

### Steps to reproduce

Create an AnimationPlayer node, create a new animation and a track, key a property, press CTRL + D.

**Comment by Calinou** [comment] 2022-03-18 20:59
@Bones404 Can you reproduce this on 3.4.3?

**Comment by Bones404** [comment] 2022-03-18 21:15
It works normally on 3.4.3

**Comment by keptsecret** [comment] 2022-03-19 19:52
This may have been fixed. I'm on the latest commit (81c2d7a) on Windows 11 and this doesn't seem to happen.

**Comment by taigi100** [comment] 2022-03-20 15:08
Can't reproduce it either on current master either. Linux arch

**Comment by Calinou** [comment] 2022-03-20 16:11
Closing per the above comments. Please comment if you can still reproduce this on latest `master` (*not* 4.0alpha4).

**Closed by Calinou** 2022-03-20 16:11 UTC
Labels: bug, topic:editor, crash, regression, topic:animation
