### ISSUE TITLE
Vulkan: 3D viewport -> 2D sprite rendering no longer works

### ISSUE THREAD

**Issue by rosshadden** [godotengine/godot#50327] opened 2021-07-09 23:08 UTC
### Godot version

4.0.dev (a5b2988a01)

### System information

Arch Linux

### Issue description

In Godot 3 one great workflow for rendering 3D scenes in an otherwise 2D world is simply to set the `texture` property of a sprite to the texture of a viewport. In `master`, this seems to be broken.

In Godot 4 it actually does do _something_, but it seems to be loading in or creating a random texture. To me it seems like maybe a pointer problem, loading in a texture from an unexpected memory address, because the images it ends up using as the sprite texture are very weird and artifacted.

The results also seem somewhat nondeterministic, or at the very least I get different results on different monitors. This should obviously have no coupling whatsoever with anything outside Godot itself, which is one thing that made me think it may be a memory address problem. Maybe this is a problem with Godot's vulkan renderer?

Edit: I want to clarify that 3D works very well in Godot 4 for me. So it's not the vulkan renderer itself, nor graphics drivers issues, nor anything else like that. It's really just this very specific case I have found so far.

Godot 3:
![image](https://user-images.githubusercontent.com/669012/125143411-9ca49b80-e0e8-11eb-8a27-118d4eb663e0.png)

Godot 4:
- a 2k monitor
![image](https://user-images.githubusercontent.com/669012/125143295-3ddf2200-e0e8-11eb-953f-a6f229c51f6b.png)
- both of my 1080p monitors
![image](https://user-images.githubusercontent.com/669012/125143343-6b2bd000-e0e8-11eb-93b4-a51416d2053d.png)

### Steps to reproduce

I have attached two minimal reproduction projects to demonstrate this problem, but the problem is pretty easy to understand even just by looking at code, as the scene tree is pretty self explanatory.

Godot 3:

```gdscript
extends Node2D

onready var sprite: Sprite = $"Sprite"
onready var viewport: Viewport = $"Viewport"

func _ready():
	# works perfectly!
	sprite.texture = viewport.get_texture()
```

-------------------

Godot 4:

```gdscript
extends Node2D

@onready var sprite: Sprite2D = $"Sprite2D"
@onready var viewport: Viewport = $"SubViewport"

func _ready():
	# does... something? but definitely not what it should
	sprite.texture = viewport.get_texture()
```

### Minimal reproduction project

Godot 3: [godot-3-3d2d.zip](https://github.com/godotengine/godot/files/6794246/godot-3-3d2d.zip)
Godot 4: [godot-4-3d2d.zip](https://github.com/godotengine/godot/files/6794248/godot-4-3d2d.zip)

**Comment by Calinou** [comment] 2021-07-09 23:25
Related to https://github.com/godotengine/godot/issues/50296.

**Comment by rosshadden** [comment] 2021-07-20 14:36
I made a change to the Godot 4 minimal reproduction project that makes this problem stand out even more. The 3D scene rendered by the viewport is now a separate scene, to demonstrate that running the 3D scene `Node3D` works as expected. The problem only comes from running the 2D scene which contains the viewport and instanced 3D scene.

This change should just make it a little more clear that it's not the 3D rendering itself not working, or something wrong with my computer (as far as I can tell), but possibly something more specific to the `Viewport#getTexture` usage.

[godot-4-3d2d-2.zip](https://github.com/godotengine/godot/files/6849135/godot-4-3d2d-2.zip)

**Comment by GiantBlargg** [comment] 2021-09-10 19:47
Is this fixed by #52528?

**Comment by rosshadden** [comment] 2021-12-06 17:38
By the way I tried this on a couple other computers to make sure it's not just my environment. I have this problem on every computer I have tried it on, but they are all Linux so it does not necessarily affect other OS's.

**Comment by rosshadden** [comment] 2021-12-06 18:06
Ooh, breakthrough. I did what @navy-cap-echo said [here](https://github.com/godotengine/godot/issues/55471#issuecomment-983409801) and set Render Target Update Mode to "Always" and it works.
I'll leave this open so @Calinou can figure out what best to do with it. Looks like there are other related issues open that would cover this so feel free to close. I'm not sure whether having to change that setting from the default is intended but I will do so until I hear otherwise to get around this problem.

**Comment by Calinou** [comment] 2021-12-06 18:09
Duplicate of https://github.com/godotengine/godot/issues/55471 (same cause).

**Closed by Calinou** 2021-12-06 18:09 UTC
Labels: bug, topic:rendering, regression
