### ISSUE TITLE
AnimationPlayer will ignore overriding set_pos() in script when animating

### ISSUE THREAD

**Issue by ShieldHero** [godotengine/godot#10947] opened 2017-09-03 21:37 UTC
**Issue description:**
While animating a Node2D using AnimationPlayer it will ignore any set_pos(), set_rot() and set_scale() in script and will always use the base function. 
I'm mainly overriding set_pos() in order to detect any movement which works as intended except when moving an object via AnimationPlayer. Doing some snooping in the source code shows that the AnimationPlayer only calls the base function.
I'm using 2.1.4 stable but this should be relevant for 3.0 as well.
If this was intended for performance reason then a signal or a way to detect changed properties will be appreciated.

**Steps to reproduce:**
Have a Node2D with a script that overrides set_pos(), then use AnimationPlayer node to move it, it will move correctly but without using the script function.

**Comment by RandomShaper** [comment] 2017-10-16 20:18
Judging by the code, I think that behavior is by design.

At least your node will get a `NOTIFICATION_LOCAL_TRANSFORM_CHANGED`.

**Comment by RandomShaper** [comment] 2017-11-01 13:19
I thought that was being the case since `AnimationPlayer` is handling `Node2D`'s position, rotation and scale in separate code paths, setting the properties right away.

But now I've found this: https://github.com/godotengine/godot/blame/584bc88834bb86e3e3fc76788a8412ac39acb3ad/scene/animation/animation_player.cpp#L323

Wouldn't that be disabling the special handling altogether? CC @reduz

**Comment by akien-mga** [comment] 2020-09-04 09:41
Is this still reproducible in tCan anyone still reproduce this bug in [Godot 3.2.3 rc5](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-5) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2020-12-10 16:23
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.

**Closed by akien-mga** 2020-12-10 16:23 UTC
Labels: discussion, topic:core
