### ISSUE TITLE
C#: calling a `GDScript` function with typed Array results into runtime error

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#92793] opened 2024-06-05 11:38 UTC
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 11

### Issue description

I want to call a setup function on my scene with a typed array as argument.
Calling this function results into a runtime error.
```bash
E 0:00:00:0718   GD.cs:366 @ void Godot.GD.PushError(string): Invalid type in function 'setup1' in base 'Godot.Node3D'. Cannot convert argument 1 from StringName to Array.
  <C# Source>    /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:147 @ void Godot.NativeInterop.ExceptionUtils.DebugCheckCallError(Godot.NativeInterop.godot_string_name, nint, Godot.NativeInterop.godot_variant**, int, Godot.NativeInterop.godot_variant_call_error)
  <Stack Trace>  GD.cs:366 @ void Godot.GD.PushError(string)
                 ExceptionUtils.cs:147 @ void Godot.NativeInterop.ExceptionUtils.DebugCheckCallError(Godot.NativeInterop.godot_string_name, nint, Godot.NativeInterop.godot_variant**, int, Godot.NativeInterop.godot_variant_call_error)
                 NativeCalls.cs:6312 @ Godot.Variant Godot.NativeCalls.godot_icall_2_701(nint, nint, Godot.NativeInterop.godot_string_name, Godot.Variant[], Godot.NativeInterop.godot_string_name)
                 GodotObject.cs:622 @ Godot.Variant Godot.GodotObject.Call(Godot.StringName, Godot.Variant[])
                 TestScene.cs:17 @ void TestScene._Ready()
                 Node.cs:2137 @ bool Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant&)
                 Node3D.cs:1036 @ bool Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant&)
                 TestScene_ScriptMethods.generated.cs:38 @ bool TestScene.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant&)
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(nint, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, int, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*)


```

### Steps to reproduce

Load the attached project and run the test scene.
- Run the TestScene
the call `setup1` is failing and call `setup2` with untyped array succeeds

### Minimal reproduction project (MRP)

[func_call_typed_array.zip](https://github.com/user-attachments/files/15586230/func_call_typed_array.zip)

**Comment by raulsntos** [comment] 2024-06-05 15:02
The error message is incorrect, it should be saying that the element type of the array does not match:

> ERROR: Invalid type in function 'setup1' in base 'Godot.Node3D'. The array of argument 2 (Array) does not have the same element type as the expected typed array argument.

I fix the error message in https://github.com/godotengine/godot/pull/92800.

The other issue reported here is about the Array type mismatch. This would be a duplicate of https://github.com/godotengine/godot/issues/74936. As explained in https://github.com/godotengine/godot/issues/74936#issuecomment-1481538393 I think C# is marshalling `Array<T>` as an untyped array.

- Closing this issue to consolidate on https://github.com/godotengine/godot/issues/74936. Thanks for reporting!

**Closed by raulsntos** 2024-06-05 15:02 UTC
Labels: bug, topic:gdscript, needs testing, topic:dotnet

**Comment by MikeSchulze** [comment] 2024-06-05 18:14
Thank you for your reply👍
