### ISSUE TITLE
Animation Tree crushing my player character

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#58654] opened 2022-03-01 13:08 UTC
### Godot version

4.0 alpha 3

### System information

Windows 11, Vulkan, Rx 5700 XT, Ryzen 7 3600x

### Issue description

my character crushes during an interpolation between 2 animations 

### Steps to reproduce

open minimal project, and move the blendtree cursor

### Minimal reproduction project

[Anim_Trans_Bug.zip](https://github.com/godotengine/godot/files/8161782/Anim_Trans_Bug.zip)

**Comment by Noiros** [comment] 2022-03-02 08:41
a tiny video :
https://gyazo.com/3e0f87d3d55efefbbb5962d8606a3433

**Comment by Calinou** [comment] 2022-03-02 17:36
This is a duplicate of another issue, but I can't find it right now.

**Comment by TokageItLab** [comment] 2022-03-03 07:35
Dupe of #55838 and #54407, maybe fixed by #57675.

**Closed by TokageItLab** 2022-03-03 07:35 UTC
Labels: bug, needs testing, topic:animation, topic:3d
