### ISSUE TITLE
`@icon` doesnt show the icon on the node when not on a class

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#69141] opened 2022-11-24 22:34 UTC
### Godot version

fa270c245 or 4.0b6

### System information

ArchLinux x11

### Issue description

`@icon` does not show any icon.

![image](https://user-images.githubusercontent.com/70787919/203870713-3e7978a4-409d-4182-bf8d-2fb8fe881d89.png)

### Steps to reproduce

- create node
- create script
- create vector icon
```gdscript
extends Node
@icon("./vector_icon.svg")
```

### Minimal reproduction project

[mrp](https://github.com/godotengine/godot/files/10087573/bug.zip)

**Comment by souplamp** [comment] 2022-11-25 00:02
Try Project -> Reload Current Project and see if it shows up?

**Comment by bend-n** [comment] 2022-11-25 00:04
no

**Comment by souplamp** [comment] 2022-11-25 00:12
Is the icon in `res://`? Try changing the path from `./` to `res://` and see if that does it after another reload.

**Comment by bend-n** [comment] 2022-11-25 00:13
no

**Comment by souplamp** [comment] 2022-11-25 00:26
I have now; I got it to work by adding `class_name Example` before the `@icon` declaration, but that shouldn't be necessary to get the icon to show up. You could use that as a work-around for now, though.

**Comment by bend-n** [comment] 2022-11-25 00:27
I cant, unfortunately, for my use case.

**Comment by MewPurPur** [comment] 2022-11-25 00:50
That's just not how `@icon` works atm, it was just a replacement of `class_name X, "icon://path"`. But maybe that should be supported by it, too.

**Comment by bend-n** [comment] 2022-11-25 00:52
@MewPurPur Should this be a proposal then?
Also, what is "icon://"?

**Comment by souplamp** [comment] 2022-11-25 01:05
> That's just not how `@icon` works atm, it was just a replacement of `class_name X, "icon://path"`. But maybe this behavior should be supported by it, too.

**From `@GDScript` docs:**
_After loading an icon at icon_path, **the icon is displayed in the Scene dock for every node that the script is attached to.** 
For named classes, the icon is also displayed in various editor dialogs._

The docs make it sound like this functionality should be possible, especially when it clarifies that named classes have additional functionality. If the behavior is not intended, the docs should be updated to make that more clear. But I do agree this behavior should be supported, too.

---

> Should this be a proposal then?

The docs make it sound like this functionality is possible, so if the docs are wrong, you're right to consider this a bug.

> Also what is `icon://`?

That declaration was necessary in Godot 3.0 to add an icon to a class, but it's no longer necessary in Godot 4, as the `@icon` annotation replaced it.

**Comment by bend-n** [comment] 2022-11-25 01:08
Yeah, I noticed the docs too, but that could be a docs bug instead of a godot bug.

> That declaration was necessary in Godot 3.0 to add an icon to a class, but it's no longer necessary in Godot 4, as the `@icon ` annotation replaced it.

Is that so? In godot3 I did `class_name class "res://icon.png"` just fine.

**Comment by souplamp** [comment] 2022-11-25 01:15
> Yeah, I noticed the docs too, but that could be a docs bug instead of a godot bug.

All of the docs are kept in this repository; the godot-docs repository pulls the .xml files from here, so this would still be the right place to report a bug :)

> Is that so? In godot3 I did `class_name class "res://icon.png"` just fine.

Oh, maybe I'm mistaken then. I think that's what MewMewPur meant by `icon://`

**Comment by RedMser** [comment] 2022-11-25 02:46
Duplicate of #65203

**Closed** 2022-11-25 08:31 UTC

**Comment by MewPurPur** [comment] 2022-11-25 13:55
Btw `icon://path` was just a fake path example. 😬
