### ISSUE TITLE
Improve the user:// path

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#4696] opened 2016-05-17 22:14 UTC
**Operating system or device - Godot version:** all

**Issue description**: Two things
1 - the user path where files are saved should be the same as all other apps in that OS. for Linux, this is usually ~/.local/share/whatever. Right now it's in ~/.godot/whatever
2 - it would be nice to remove the 'godot' folder, and just use the app name. For exported builds, it doesnt look nice

not sure how it is on the mac as I can not test

**Comment by akien-mga** [comment] 2016-05-17 22:19
1. is a duplicate of #3513
2. is a duplicate of #4431

;)

**Closed by akien-mga** 2016-05-17 22:19 UTC
