### ISSUE TITLE
Random Crash when running game app

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#32082] opened 2019-09-10 20:57 UTC
3.1.2

Ubuntu 18.04

Game crashed when run from the editor when the code reached a point where previously I had some breakpoints.

I can't reproduce it yet.

This is the dump:
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fb09dccef20] (??:0)
[2] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__dynamic_cast+0x20) [0x7fb09e6c8400] (??:0)
[3] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x25eb92c] (/home/puthre/godot/mygodot/godot/core/script_debugger_remote.cpp:624)
[4] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x25f07d8] (/home/puthre/godot/mygodot/godot/core/script_debugger_remote.cpp:717 (discriminator 1))
[5] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x25f0b73] (/home/puthre/godot/mygodot/godot/core/script_debugger_remote.cpp:902)
[6] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x45cf06] (/home/puthre/godot/mygodot/godot/main/main.cpp:1915)
[7] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x444161] (/home/puthre/godot/mygodot/godot/platform/x11/os_x11.cpp:3006)
[8] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64(main+0xd8) [0x4356c8] (/home/puthre/godot/mygodot/godot/platform/x11/godot_x11.cpp:55)
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fb09dcb1b97] (??:0)
[10] /home/puthre/godot/mygodot/godot/bin/godot.x11.opt.tools.64() [0x4376aa] (??:?)
-- END OF BACKTRACE --
ERROR: _get_socket_error: Socket error: 104
   At: drivers/unix/net_socket_posix.cpp:199.
```

**Comment by puthre** [comment] 2019-09-11 09:14
I think this is the same one but when running on android:
```
09-11 10:07:59.943 26922 26922 I crash_dump64: obtaining output fd from tombstoned
09-11 10:07:59.959 26922 26922 I crash_dump64: performing dump of process 24477 (target tid = 24521)
09-11 10:07:59.960 26922 26922 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-11 10:07:59.960 26922 26922 F DEBUG   : Build fingerprint: 'samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXS6ESGD:user/release-keys'
09-11 10:07:59.960 26922 26922 F DEBUG   : Revision: '9'
09-11 10:07:59.960 26922 26922 F DEBUG   : ABI: 'arm64'
09-11 10:07:59.960 26922 26922 F DEBUG   : pid: 24477, tid: 24521, name: GLThread 72248  >>> com.viar.puzzle <<<
09-11 10:07:59.960 26922 26922 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6f00000003
09-11 10:07:59.960 26922 26922 F DEBUG   :     x0   0000007e1db06810  x1   0000007e609073a8  x2   0000007e60907bc8  x3   0000000000000000
09-11 10:07:59.960 26922 26922 F DEBUG   :     x4   0000000000000044  x5   0000007e19e5a9c0  x6   0000000000000040  x7   0000000100000001
09-11 10:07:59.960 26922 26922 F DEBUG   :     x8   0000007e1db06810  x9   0000006f00000013  x10  0000000000000000  x11  000000000000001b
09-11 10:07:59.960 26922 26922 F DEBUG   :     x12  0000000000000000  x13  0000000000001701  x14  000000000000000d  x15  aaaaaaaaaaaaaaab
09-11 10:07:59.961 26922 26922 F DEBUG   :     x16  0000007e6091d228  x17  0000007e609fd838  x18  0000007e68f2efdc  x19  0000007e7d788110
09-11 10:07:59.961 26922 26922 F DEBUG   :     x20  0000007e5e6e8588  x21  0000000000000002  x22  0000007e601ee60f  x23  0000007e609073a8
09-11 10:07:59.961 26922 26922 F DEBUG   :     x24  0000007e60907bc8  x25  0000007e5b07af50  x26  0000000000000008  x27  0000007e5e6e8588
09-11 10:07:59.961 26922 26922 F DEBUG   :     x28  0000000000000000  x29  0000007e5e6e6e90  x30  0000007e5fe286e8
09-11 10:07:59.961 26922 26922 F DEBUG   :     sp   0000007e5e6e6e20  pc   0000007e609fd860  pstate 0000000060000000
09-11 10:08:01.144 26922 26922 F DEBUG   : 
09-11 10:08:01.144 26922 26922 F DEBUG   : backtrace:
09-11 10:08:01.145 26922 26922 F DEBUG   :     #00 pc 00000000000b6860  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libc++_shared.so (__dynamic_cast+40)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #01 pc 000000000173f6e4  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libgodot_android.so (_ZN20ScriptDebuggerRemote15_send_object_idEm+6704)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #02 pc 0000000001742c8c  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libgodot_android.so (_ZN20ScriptDebuggerRemote12_poll_eventsEv+440)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #03 pc 0000000001745108  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libgodot_android.so (_ZN20ScriptDebuggerRemote9idle_pollEv+816)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #04 pc 00000000001e149c  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libgodot_android.so (_ZN4Main9iterationEv+1196)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #05 pc 00000000001aad40  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+168)
09-11 10:08:01.145 26922 26922 F DEBUG   :     #06 pc 0000000000007c80  /data/app/com.viar.puzzle-Qv6u3CtQNT9Y81nt5MOdrA==/oat/arm64/base.odex (offset 0x6000)

```

**Comment by akien-mga** [comment] 2019-09-23 09:23
Any new info on how to reproduce it?

**Comment by puthre** [comment] 2019-09-23 09:34
No, it did not happen again. It probably had to do with something specific that I've done with the debugger.

**Comment by akien-mga** [comment] 2020-01-19 22:29
Closing for now as we don't know how to reproduce this issue.

It might have been due to too big allocations which #35312 should solve.

**Closed by akien-mga** 2020-01-19 22:29 UTC
Labels: bug, crash, needs testing, topic:core
