### ISSUE TITLE
Problem: my current project is opened as an empty.

### ISSUE THREAD

**Issue by vladikoles** [godotengine/godot#2755] opened 2015-11-09 00:27 UTC
My current 3d-project is opened as an empty, though it run normally.

I missed something, right?

State: 3fcfdfec0ac5175f55527b3ec95d14d48bf29dd2
Ubuntu 14.04 64-bit (ru_Ru)
scons platform=x11

**Comment by CowThing** [comment] 2015-11-09 00:47
Same issue as #2611 ?
It has a fix here #2711

**Comment by vnen** [comment] 2015-11-09 01:15
Closing as duplicate of #2611.

**Closed by vnen** 2015-11-09 01:15 UTC
Labels: archived, bug, topic:editor

**Comment by vladikoles** [comment] 2015-11-09 01:34
If it is the same problem - it is returned.
Or it is a new problem with the same manifestation.

I compiled the most recent.

**Comment by vnen** [comment] 2015-11-09 02:28
@vladikoles it is a bug still not fixed, the issue I referenced is still open and being worked on.

About you first error message about the icon, it seems the same #2658 with a proposed fix in #2652. The second error is likely related to #1150, though something you may ignore.

Feel free to comment your experience on any of those issues.

**Comment by vladikoles** [comment] 2015-11-09 19:28
That's what I have now (61c4c5795ff9057b1c67142758418a4f982a0241):

Run godot:
--
BOOT SPLASH: 
BOOT SPLASH IS : 
ERROR OPENING FILE: icon.png
ERROR: _load_recent_projects: Condition ' err!=OK ' is true. Continuing..:
   At: tools/editor/project_manager.cpp:524.
--

Click "Edit":
--
OPENING: <project path>
BOOT SPLASH: 
BOOT SPLASH IS : 
--

My current 3d-project is opened as an empty.

Click "Play the project (F5)":
--
running:  -path  -rdebug localhost:6007 -p 0x0 res://new_scene.scn
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:246.
********* listening on port 6007
OK! 11
has connection!
has connection!
BOOT SPLASH: 
BOOT SPLASH IS : 
--

Project play normally.

Close playing window:
--
freed code id 3
pre-removing print handler...
removing print handler...
found
print hanlder list is (nil)
freed code id 2
freed code id 1
CLOSING CONNECTION
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:246.
--

Close godot:
--
freed code id 3
freed code id 5
freed code id 4
freed code id 6
freed code id 2
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:246.
freed code id 1
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1853.
--

I hope this information will help something.

**Comment by vladikoles** [comment] 2015-11-12 13:46
Problem: any project (and any demo projects) is opened as an empty!
This clarification of issue.

Please do not consider this a bug closed. The problem does not disappear with the new commits.
What do i do?
I can not keep up the development!
I will have to reopen the issue.

**Comment by akien-mga** [comment] 2015-11-12 13:52
As said above, your bug is the same one as #2611, which is not fixed yet.
There is a fix for it in #2711, but it has not been merged yet. You can grab the pull request as a patch and apply it locally if you want: https://github.com/godotengine/godot/pull/2711.patch

**Comment by vladikoles** [comment] 2015-11-15 19:22
Thanks.
