### ISSUE TITLE
ParticlesMaterial's emission direction is wrong if direction.z != 0 and direction.y != 0

### ISSUE THREAD

**Issue by mortarroad** [godotengine/godot#47145] opened 2021-03-18 21:44 UTC
**Godot version:**
v3.2.4-rc5

**OS/device including version:**
Windows 10. GLES3.

**Issue description:**
If the direction property of a ParticlesMaterial is changed, it often behaves completely unpredictable.
This is especially apparent, if the values are close to zero.

**Minimal reproduction project:**
The example has two particle systems, which are identical, save for the emission direction.
One of them has the vector (1.0, 0.0, 0.0), the other (1.0, 0.01, 0.01).
They should visually emit in almost the same direction, they are almost 45° off.

[particle_spread_test.zip](https://github.com/godotengine/godot/files/6167382/particle_spread_test.zip)

**Comment by akien-mga** [comment] 2021-03-19 10:36
Is this reproducible in the `master` branch too?

**Comment by mortarroad** [comment] 2021-03-19 16:26
Yes, master has the same issue.

I had assumed there had been a rewrite for ParticlesMaterial.
Since master breaks compatibility, I would recommend redesigning ParticlesMaterial anyway.
The way it currently is, isn't really that pretty.

For spread I would do the following:
- Remove the direction, just emit along a constant axis. If needed, the Node can be rotated already.
- Add a separate external_velocity vector that is added on top of the computed velocity.

**Comment by Calinou** [comment] 2021-03-19 17:58
> Remove the direction, just emit along a constant axis. If needed, the Node can be rotated already.

The direction property was originally added here: https://github.com/godotengine/godot/pull/26613

**Comment by mortarroad** [comment] 2021-03-19 19:01
Hm, yeah, I forgot about emitting with local coordinates...
Then I suppose at least a user controlled Up vector should be introduced.

**Comment by clayjohn** [comment] 2021-03-19 20:21
Possible duplicate of https://github.com/godotengine/godot/issues/30340

Can you check and see if #47146 fixes #30340?

**Comment by mortarroad** [comment] 2021-03-19 21:27
It should fix that too, yes.
But that issue mentions the documentation, and that says:
>float spread
>Each particle's initial direction range from +spread to -spread degrees. Applied to X/Z plane and Y/Z planes.

The new implementation doesn't match that, but neither did the old one, I suppose...
The spread is now applied in the plane that is orthogonal to the _direction_.

**Closed** 2021-03-25 22:57 UTC
Labels: bug, topic:3d, topic:rendering
