### ISSUE TITLE
Click on Skeleton Node with large number of bones crashes editor

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#35643] opened 2020-01-28 01:53 UTC
**Godot version:**
v3.2.rc4.official

**OS/device including version:**
Windows 10 x64

**Issue description:**
Click on a Skeleton Node with large number of bones ( 186+ for a complex 3d character ) leads to console spam with "Object was deleted while awaiting a callback" followed by lockup/editor crash. 

Bug happens consistently for all Skeletons in the project that use a high number of bones.
Tested and does not happen on previous versions v3.2 rc1, rc2 and rc3 for the same project.

**Steps to reproduce:**
Load scene with skeleton node from a 3d character with 100+ bones and play clickerheroes

**Minimal reproduction project:**
Assets are to big in filesize to share rightnow but if required for testing I could try to extract them from the project.

**Comment by Calinou** [comment] 2020-02-02 18:00
Duplicate of #35652.

**Closed by Calinou** 2020-02-02 18:00 UTC
