### ISSUE TITLE
High load without any profit on ANY video card

### ISSUE THREAD

**Issue by br3eze** [godotengine/godot#60100] opened 2022-04-10 13:44 UTC
### Godot version

3.4.4

### System information

Arch linux (godot has been installed from repos), GLES3, NVIDIA 2060m

### Issue description

![image](https://user-images.githubusercontent.com/5236855/162620377-b64dc0f3-c47b-4b85-b15e-18fcf1964ab8.png)

It's All about FullHD. If it will help.

Completely empty scene in a new project == 100% load on NVIDIA 2060m with only ~300 fps! Caping fps will just reduce load, but a high fps cost will be still there. Veeery simple scenes do the same. Performance of the engine is very poor. How to fix? Why so? What I do wrong? 

Please give me some explanation. I can play 3D online shooter with 60 people and have ~120 fps on my Intel 620. And I have on this intel around 250 fps on the same empty scene. I can run a 3D game, can't get performance in an empty scene. Or may be I completely misunderstand something?

Thank You.

### Steps to reproduce

Create empty project and run it on NVIDIA card. I add label to see FPS, but it's not because of that.

### Minimal reproduction project

extends Spatial

func _ready():
	OS.set_use_vsync(false)

var t
func _process(_delta):
	t = "FPS: " + str(Engine.get_frames_per_second())
	$Label.set_text(t)

**Comment by mrjustaguy** [comment] 2022-04-10 15:10
I think you're running into a Driver issue or something..

Try running the TPS demo and benchmark performance there, that should give a more realistic FPS.. it should be around 30-60 FPS on the GPU on high settings at Full HD (The Third Person Shooter Demo is seriously poorly optimized, no culling and an unrealistic crap ton of triangles being processed)

If the TPS demo runs within those figures, there's probably some bottleneck unrelated to the GPU going on, while the GPU is just being Pegged in a Loop doing actually nothing smart in reality (considering the power draw this could be the case, as it'd be drawing a bit more at 90% utilization or higher if it was genuinely doing something)

If the TPS demo runs at lower Framerates, the Utilization figures are probably showing it's actual utilization, and it's most likely bad drivers, which on Linux wouldn't surprise me with nvidia.

**Comment by br3eze** [comment] 2022-04-10 15:24
"and it's most likely bad drivers, which on Linux wouldn't surprise me with nvidia". 
Quake Champions, Starcraft 2, Squad, Horizon Zero Dawn (maximum settings 60fps caped) - these are my 100% benchmarks and everything is ok. Just have a look at these games, they are pretty heavy. So, they haven't "Driver issue" and empty project has.. 

"The Third Person Shooter Demo" I mean real games and everything is ok with them.

**Comment by Zireael07** [comment] 2022-04-10 15:30
@br3eze: Those real games use a variety of techniques (some are DirectX, some are OpenGL). Also Starcraft and Quake are fairly old so it's not surprising they perform well.

Personally I concur you may have bad drivers, for instance on my Dell Vostro, the discrete card gives worse performance in Linux than the integrated Intel Kaby Lake, because it immediately gets so hot that thermal throttling kicks in.

**Comment by br3eze** [comment] 2022-04-10 15:39
"it immediately gets so hot" look at the screenshot It looks like the temperature is ok.
"Starcraft and Quake are fairly old" older than empty scene? Come on..

300 fps in empty scene with the last drivers, no problem with actually not old games like "Horizon Zero Dawn".

I don't think guesses and guessing are the best way to find the answer.

**Comment by Calinou** [comment] 2022-04-10 17:03
> Arch linux
> NVIDIA 2060m

Remember that using NVIDIA Optimus has a performance overhead, especially on Linux where the implementation is known to be subpar compared to Windows. You won't be able to achieve thousands of FPS like you can on a desktop GPU.

**Comment by mrjustaguy** [comment] 2022-04-10 19:09
Eh, I've seen what Driver issues do to Performance...

One great example in my experience is Age of Mythology on Virtual Box (Win XP machine, darn Windows killing SecDrv which killed DRM..) and just the menu at low res was running at barely 2 FPS, with high utilization, Due to poor Driver emulation and that's on a Desktop machine that's running ARK Survival Evolved on High Settings and doing 30 FPS no problems.

Age of Mythology is a Game from 2002 and is very basic 3D that wants a 450MHz processor with 128MB RAM paired with a 16 MB VRAM 3D capable GPU
ARK Survival Evolved is a Game from 2017 and is a Massive, Visually Impressive Open World Game running on Unreal Engine 4

So yes, Poor drivers can result in such a stupid utilization giving such idiotically poor performance, and as with all software, only a very specific part could be the bottleneck in any given situation, which is why doing more testing is required to be able to better narrow down to what's happening.

**Comment by br3eze** [comment] 2022-04-11 01:41
"disable compositing in your window manager"

Already tried fluxbox and kde with/without compositing. Of course it's not about it.
And of course it's not about vsync at all! Look at fps on the screenshot. May be 345 Hz displays exist on laptops, but I haven't even saw them. I play mentioned games without vsync and with compositing with a super heavy scenes. Really BIG GAMES! Against just an empty scene or a simple scene with a low poly standard meshes.
Please STOP this already!

"So yes, Poor drivers can result"

I made builds for windows and other OS. People say the same: "wow, why so stupid simple scenes make so high load and no fps at all while we can play AAA games without any problems?"
Obvious it's not about drivers or something like this. I can understand "it's not my problem" view, but we've already checked it before write here.
Please stop this already!

We've tried 4.x branch but it's buggy as hell yet, so we're trying to deal with 3.4.4. We didn't tried much lower versions, if someone really know which version can help it will be great. But I think it's a system issue.
If somebody will check this too it will really help to stop guessing by stars process too.

**Comment by clayjohn** [comment] 2022-04-11 02:49
> If somebody will check this too it will really help to stop guessing by stars process too.

For somebody to help further you will need to provide a minimal reproduction project that exhibits the problem you are describing. The people trying to help are left guessing because they aren't seeing the problem on their hardware and you haven't provided much information to go on. 

To be clear, low FPS on an empty scene is not a common problem which is why the other commenters are trying to guess what os/driver issues exist for your specific setup. It's more likely an issue with your computer than it is with Godot as none of the other commenters are able to reproduce your issue.

**Comment by br3eze** [comment] 2022-04-11 03:33
"Quake Champions, Starcraft 2, Squad, Horizon Zero Dawn (maximum settings)"
    "low FPS on an empty scene is not a common problem"
    "It's more likely an issue with your computer than it is with Godot "

"Just an empty scene or a simple scene with a low poly standard meshes"
    "you will need to provide a minimal reproduction project"
    "made builds for windows and other OS. People say the same"

Ow God help me...

**Comment by mrjustaguy** [comment] 2022-04-11 06:02
I'd tell you to reinstall the drivers, but I'm unsure how much that'd help if it's a Driver bug, unless something messed up the Driver install, such as Windows installing their own drivers during the User's installation, which I have seen happen on a Windows 10 Machine a few months ago, rendering certain games unplayable that shouldn't have any issues running on the hardware, while not causing any issues for others, however I don't think many Linux distros love f-ing up the driver installs the way Windows likes to do.

The thing is, We don't really know what's going on, as we are so far unable to reproduce the issue ourselves, so were kind of like Doctors irl, making educated guesses as to what's the problem based on symptoms we see... and here it's quite clear that Hardware side is ok, otherwise you'd almost surely be running into issues with other things too, and You're running into an issue only with Godot, which we are unable to see on our machines, which means it's not a Godot problem, but rather something it's interacting with - so 99% chance it's an issue with some driver it's interacting with.

Try using GLES 2.. that might help narrow down the issue further

**Comment by br3eze** [comment] 2022-04-11 06:26
@mrjustaguy  "Try using GLES 2.. that might help narrow down the issue further"
Driver from repos. GLES2 and 3 produce the same thing last 4 months.

Can I ask You something. AAA games are O.K., BFGames, they are **much** more complex than just an empty scene with a box. On this background, why You are still using this logic?
In other words: what can't do Horizon Zero Dawn, Metro Exodus, Squad, Arma 3, and many, many other games with the poor driver, what Godot can and do from start with his super boxes? I completely can't understand it..

Can You upload a screenshot with a new default project and the same scene? What card do You use? What fps You will have? 
Integrated video cards shouldn't be taken here, as You know, they simplify many commands and then can give You even fps boost. NVIDIA will calculate every command honestly.

**Comment by mrjustaguy** [comment] 2022-04-11 09:21
My Specs:
Windows 11
i3 10105f @ 3.7GHz (Turbo Boost Disabled due to personal preference)
16 GB 3200 MHz Memory
GTX 1050 Ti (4 GB VRAM), Windows Driver 512.15
1920x1080 (60 Hz Display)

4 Cube Scene 3.4.4 Stable 1920x1080
![3 4 4 FPS](https://user-images.githubusercontent.com/50302479/162707173-b778d510-a62b-4982-90f6-770a28fcb4bc.png)

As you can see, I'm Getting ~1300 FPS just fine, and the limiting factor is almost surely the Pixel Fill rate
According to Tech Powerup charts, my GPU is 55% of your GPU's horsepower https://www.techpowerup.com/gpu-specs/geforce-rtx-2060-max-q.c3533

**Comment by mrjustaguy** [comment] 2022-04-11 09:24
@br3eze Also, you know, if something is bad with a Driver, it can impact only One piece of software, because it is possible that only One piece of software is using the offending piece of said Driver.

**Comment by br3eze** [comment] 2022-04-11 09:50
Can't be... and what should I do? Why other people get this fps drops too?
Can You share Your project and exe/bin file please?

Thank You for help.

**Comment by mrjustaguy** [comment] 2022-04-11 10:24
are you running the official Stable release or custom build? I mean that is like the only other thing I can think of at this point, that there is a regression in a build that none of us were using.

**Comment by CoreTaxxe** [comment] 2022-04-11 10:29
I had the same issue with an AMD card (rx 6600, ryzen 5 3600, win10) a few months myslef. Empty scene barely hit the 200 fps at max load and complex scenes could barely reach 60. Other games ran perfectly fine (battlefield 5 max settings 120 fps ). Even a whole system reinstall didnt fix the issue. All drivers were up to date and properly installed. I know personal experience doesnt add too öuch to this but it might indicate that there is something weird however rarely occurong going on.

**Comment by mrjustaguy** [comment] 2022-04-11 10:30
@CoreTaxxe This does help significantly, as it removes Driver issue from the equation more or less completely, as it's unlikely for both Nvidia and AMD to have the same issue, and Windows 10 is a very commonly used OS that both companies support well.

**Comment by CoreTaxxe** [comment] 2022-04-11 10:43
@mrjustaguy im currently not using this pc anymore (since developing with it simply didnt work lol) and switched with my sister. Once I got home I can try and pinpoint the issue further down but as for now i have no clue wich program might cause the issue. (Irrc i tested godot right after the system wipe so the only launcher that  might come into play is steam, amd enterprise , titanwolf mouse config, roccat swarm. Everything else should have been windows preinstalled.

**Comment by mrjustaguy** [comment] 2022-04-11 10:46
On your current PC Godot runs fine, and all of the said software is also there too? If so it probably eliminates those..

**Comment by CoreTaxxe** [comment] 2022-04-11 10:57
> On your current PC Godot runs fine, and all of the said software is also there too? If so it probably eliminates those..

Yes. On my current machine godot runs flaweslly. And yes all these softwares and more is also installed. I have a dumb theory tho : Godot used to have hiccups (stutters)    when rotating the camera fast (also empty scene). This was not unique to godot but other gamed had it far far less often. I ultimatively narrowed this issue down to the RAM sleeping part filling up the space completely and "stealing godots" space so to speak. I fixed that issue by clearing this sleeping ram with an external script every few seconds.  Tldr ; maybe Godot gets not enough priorities and therefore is forced to step back of other processes ask for resources.  Im by all means no expert so this is just an uneducated guess

**Comment by mrjustaguy** [comment] 2022-04-11 11:03
That probably wouldn't explain why it's using 90% of an rtx 2060 mobile at like full clock speeds.. I mean sure doing a Memory Check just to be on the safe side might make sense, but it's like a 1 in a million chance that it has anything to do with it pegging the GPU so hard for no good reason.. Priorities might be it if for some reason when Godot runs some background Program decides it wants all that GPU horsepower and the two fight over it... but if task manger or some such program is saying Godot's using 90% of the GPU, it's probably what's actually using 90% of the GPUs power.

**Comment by akien-mga** [comment] 2022-04-11 11:12
Just to clarify, when you disable V-Sync, the engine will attempt to render as many frames as possible. So that means that you're going to get either 100% GPU or 100% CPU usage, and the max FPS that matches the hit bottleneck. 350 FPS doesn't sound particularly impressive on an empty scene, and this can result from various issues which have been discussed above, but it's (AFAIK) completely expected that either CPU or GPU usage would be maxed out with VSync disabled.

For example running `glxspheres64` with VSync disabled on my Linux laptop with Intel IGP:
![image](https://user-images.githubusercontent.com/4701338/162728012-b0d8816b-b71d-4eff-b38c-aff96b8191a3.png)

![image](https://user-images.githubusercontent.com/4701338/162728071-47e894ff-f1dd-4531-bfdc-1c5a2ed16493.png)

This is working as intended - I'm asking `glxspheres64` to hammer my GPU to render as many frames per second as it can.

**Comment by lawnjelly** [comment] 2022-04-11 12:07
> Please give me some explanation. I can play 3D online shooter with 60 people and have ~120 fps on my Intel 620. And I have on this intel around 250 fps on the same empty scene. I can run a 3D game, can't get performance in an empty scene. Or may be I completely misunderstand something?

Do you have another game that runs full screen using OpenGL etc that runs at e.g. 1000 fps that is giving you the reason for this expectation? Otherwise, this kind of performance characteristics is often the case. Run the app with a small window e.g. 100x100 pixels see if the frame rate increases. You haven't mentioned the resolution you are running at, which will usually be totally key to this.

There are lots of different bottlenecks that kick in depending on what you are doing, and there are fixed costs to a full screen update (e.g. fill rate) especially at high resolution which will make the frame rate lower than you might be expecting with no load. This is twice as important if some kind of secondary processing is going on (e.g. OS, the nvidia optimus thing).

These characteristics are often also seen on mobile and integrated GPU, it is usually only desktop GPU with minimal OS etc interference that will reach very high frame rates full screen. Also mobile GPUs might cap things to stop you hammering the battery etc.

**Comment by mrjustaguy** [comment] 2022-04-11 12:09
1080p, says in stats.. CPU max single thread usage is ~30%
The issue probably isn't with Godot but something else, it's just manifesting in Godot..

**Comment by mrjustaguy** [comment] 2022-04-11 12:19
@CoreTaxxe What GPU are you using on your machine that doesn't have any issues with Godot? is it an nvidia GPU by any chance?

**Comment by br3eze** [comment] 2022-04-12 05:58
@mrjustaguy Thank You for Your patience! You were right!
I've tested a few distros and it is true. Somehow true. One of them shows 350 fps other 2k fps.
Thank You!

**Comment by mrjustaguy** [comment] 2022-04-12 07:08
Glad I could help.

My last post is no longer relevant as the Problem was found to be the Distro not playing nice (for whatever reason), I originally wanted to know the GPU manufacturer as the case for that specific issue could have been AMD's not so great OpenGL support as pointed out by Calinou on Godot's Contributor Chat, and moving to nvidia would have fixed that, meaning the culprit was most likely AMD's drivers and thus sadly not actually be helpful with determining the issue.

Now Why the Distro had an issue only with Godot and not any other intensive games or programs is a Good question, but we will probably never know

**Comment by br3eze** [comment] 2022-04-12 07:38
@mrjustaguy While I was completely amazed with this, I was thinking.. what differences have all these distros?
Closed drivers - nope it almost can't be, soft versions - sure, but not likely. May be kernel config: timers resolution, anti-cpu-bugs, other stuff can ba harmful for performance?
And kernel really differs from distro to distro. What do You think?

**Comment by mrjustaguy** [comment] 2022-04-12 08:07
It could be any number of things, but like you said it's probably not the GPU Drivers, rather how they communicate with the OS probably, and somewhere in there is probably a bug if some specific thing is asked (which Godot seems to be doing and others aren't) and the communication between the two goes through hell, telling the GPU nonsense, it doing a super inefficient render route as a result of the miscommunication or even telling it such nonsense that it refuses to work.

This is My guess, however I'm not an expert in these things, I'm just working with Experience I've had with fixing such stupid problems and just following my instincts that I've tuned over years of fixing Games that won't work properly on Modern OS-es (mainly windows) out of the box..  and oh boy can I tell you just how stupid the problems can be and how even dumber the solutions to them are... These things have just soo many moving pieces and sometimes something completely unrelated can slightly change how something else works, leading to a cascading effect that breaks the end software..

I mean one great example was how a game refused to run because it was named differently, but stating a totally unrelated issue, that had Nothing to do with how it was fixed.. and I'm not sure anymore, but I think it just refused to run with the OG exe name.. I know that I had to just rename something, but not sure what it was anymore..

**Comment by CoreTaxxe** [comment] 2022-04-12 08:46
> But yes, the only thing confuses me that I can't even start work with 4.x branch. It's just hangs on the project creation dialog.
> 
> Like a painful interference of software pieces..

Yeah, i have this issue as well with the alpha 6. 1-4 worked fine but 6 hanga itself while creating the project.

**Comment by br3eze** [comment] 2022-04-15 08:09
@mrjustaguy 
Obviously, in 99% of common things, there are only a few of them can reduce performance: 1 - mesa, 2 - kernel, 3- xorg.
It is not a driver or vulkan stuff, as we know already.
I'm configuring kernel, already made mesa 22.1.
But can You help me build mesa 20.3? I get some errors while building it on Arch linux and can't understand what it wants.

**Comment by mrjustaguy** [comment] 2022-04-15 08:32
Sadly I don't have any experience with that... I generally tend to stick to really high level stuff, with only a fairly decent idea of what's going on in the background (stuff that's mostly just General Computer Basics) and I only got Windows experience..

Linux sadly never was an acceptable option for me, not because I don't like tinkering with these things, I probably would come to enjoy that, it's just that some things I need just really don't want to work on Linux.

I might get some experience when W10 support goes out and some old machines get turned to Linux machines, but that's still a way off and it is still unclear what will even end up happening with the machines at that point.

**Comment by br3eze** [comment] 2022-04-23 18:01
@mrjustaguy  @CoreTaxxe 

Hey guys. I think I have found something.
In the last week: 2 kernel versions, 3 mesa, 2 xorg, 3 intel, 2 nvidia )

1. Don't install **xf86-video-intel** - it **KILLS** all the "Intel HD Video" performance and somehow sometimes (even some fresh install iterations) can break NVIDIA too. Tested on Manjaro, Arch and Artix distros. I don't sure on 100%, but I have tested one version and it worked, but was too old. So never mind.

2. Sometimes, Mangohud can break some things (some games for example), try to check everything without it. But it is a seldom situation. Mangohud is a very useful thing, just use it carefully.

3. Some old hidden stuff in Your home directory can help this low fps story to exist. Don't have a clue, just have deleted it all out. But it has helped only partly.

4. I can play Arma 3 on Ultra settings with a stable 60 fps with vsync. So may be.. **just may be**, it is about Godot too? Can someone say something about it? I can build a debug version and send You some information? Help?
NVIDIA performance is ugly yet: 0 __GL_SYNC_TO_VBLANK=0 ~/nvidia_run.sh godot_empty_project**
gives only **1'100 fps** on nvidia: Temp: **66C**    **P0**    **39W** Load: **94%**
Nvidia support:
- Thank You, but my NVIDIA card is a primary one now, for what? And why intel and nvidia cards don't work on 100%?
- I really don't know why _Your_ nvidia optimus doesn't work well, but "Let it be" nvidia is Your primary gpu now, have a nice day.

But at least I can continue my work now _somehow_ on intel: it gives now 3'300 fps.
I'm not an expert in such things, just hope it will help You to not have to change Your laptops just because of a ** software and the best support ever.

If someone know how to fix nvidia **please** share.

**Comment by xyproto** [comment] 2022-10-22 14:34
Does it work when `godot` is launched with `prime-run`?

**Comment by akien-mga** [comment] 2023-02-11 20:31
Closing as there isn't much actionable for us in this issue.

There's definitely room for optimization in future releases, but this will need to be driven by bottleneck analysis and benchmarks.

**Closed by akien-mga** 2023-02-11 20:31 UTC
Labels: discussion, platform:linuxbsd, topic:rendering, topic:thirdparty, needs testing
