### ISSUE TITLE
Variable reference changes to different node

### ISSUE THREAD

**Issue by Chrisstar56** [godotengine/godot#36584] opened 2020-02-26 23:26 UTC
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:**
I have a variable that holds the reference to a node (that was last hit by the raycast). Sometimes though, when the original node gets deleted, its spot somehow gets taken up by a completely different one that has spawned in since than (other type as well). This is causing errors for me, because this other node doesn't have the same propertys. Here is the code:

```
extends RayCast

var last setget test
func _process(delta):
    var mouse = get_viewport().get_mouse_position()
    self.transform.origin = get_viewport().get_camera().project_ray_origin(mouse)
    self.cast_to = 50 * get_viewport().get_camera().project_ray_normal(mouse)
    if is_colliding():
        var obj = get_collider()
        
        if(not is_instance_valid(obj)): return
        var hex = obj.get_parent().get_parent()
        if last and is_instance_valid(last):
            last.highlight = false
        if hex.has_method("set_rotation"):
            last = hex
            hex.highlight = true
            Globals.PosLabel.text = hex.gridCoord.toString()
    elif last and is_instance_valid(last):
        last.highlight = false
        last = null

func test(e):
    last = e
    print ("test called")
  
func getCurrent():
    return last
```
As you can see, when last gets set, it clearly has the "highlight" property. This variable is never set from anywhere outside of this class (I tested with the setter). So how can it be that a different node ends up in that variable?

**Comment by Calinou** [comment] 2020-02-27 09:56
Duplicate of #32383. This is fixed in the `master` branch, but I don't know if it will be fixed in the `3.2` branch.

**Closed by Calinou** 2020-02-27 09:56 UTC
