### ISSUE TITLE
Regression: Occlusion culling randomly occluding things completely in the open.

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#100032] opened 2024-12-05 03:03 UTC
### Tested versions

Just synced mainline yesterday when I noticed this happening: v4.4.dev.custom_build [4497273fd]
Didn't happen in 4.3 or 4.4-dev5.

### System information

Godot v4.4.dev (4497273fd) - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

There are certain locations where things will just get completely occluded, even though they're out in the open.  Seems to be random each run, so the locations where things occlude will change.  Here are a couple clips to demonstrate the issue:

https://www.twitch.tv/jitspoe/clip/HeartlessTenuousCardAMPTropPunch-6opP9uinLWBMT6P1
https://www.twitch.tv/jitspoe/clip/WittyCheerfulIcecreamSaltBae-9Q3UarksnpuI7fS4

### Steps to reproduce

It's difficult to reproduce consistently, as it seems random.  Never had it happen before I synced the latest main, though.  In my case, I used the bsp importer to import a medium complexity map with the occluder option enabled: https://godotengine.org/asset-library/asset/2147

When walking around the level, sometimes lights and other objects would disappear.  Standing in specific locations would cause a bunch of things to stop rendering as though there were an occluder polygon just floating in space, there.

### Minimal reproduction project (MRP)

Still trying to work out a way to consistently repro this in a MRP, but considering the severity of it for anybody using occluders, I thought I'd report it while I try to work out the details.

**Comment by jitspoe** [comment] 2024-12-05 05:10
Ok, yeah, the occluders are super busted.  If I try to preview them in the editor they look like this:
![Image](https://github.com/user-attachments/assets/21a0d122-75fc-4822-9e1c-773176eb9530)

For this scene:
![Image](https://github.com/user-attachments/assets/91b2baf4-969e-4f98-83ea-9f79386901ec)

**Comment by clayjohn** [comment] 2024-12-05 06:53
When was the last time you pulled? We merged https://github.com/godotengine/godot/pull/99941 and https://github.com/godotengine/godot/pull/98770 recently. Neither one seem likely to cause the issue you have, but its worth checking.

**Comment by lawnjelly** [comment] 2024-12-05 08:14
You can turn off occlusion jitter in `rendering/occlusion_culling/jitter_projection` to test #99941.

**Comment by jitspoe** [comment] 2024-12-05 08:24
I have both of these.  https://github.com/godotengine/godot/pull/98770/files seems the most suspect, since it changes the vertex buffers from float* to Vector3*, and the problem looks like a vertex indexing one.

**Comment by Rudolph-B** [comment] 2024-12-05 12:26
I can confirm #98770 is the cause. I made a mistake in the pointer math causing the `_transform_vertices_range()` to overwrite itself constantly. I missed it during testing since the issue only appears if `_transform_vertices_range()` is called multiple times, which only happens with larger scenes.

I'll have fix shortly

**Closed** 2024-12-05 20:16 UTC
Labels: bug, topic:rendering, regression, topic:3d

**Comment by jitspoe** [comment] 2024-12-06 02:43
Thanks for the fix!  Just confirmed this issue is present in 4.4-dev6 and fixed when I synced latest main.

**Comment by jamie-pate** [comment] 2025-03-15 19:24
Something changed between 4.3..4.4 that broke OpenXR occlusion culling too

I'm getting similar issues in XR in `4.4-stable` and `4.4.1-rc1` https://github.com/godotengine/godot/issues/104193 but maybe it's a different root cause..
