### ISSUE TITLE
Cursor is lost in Editor on closing script files in the editor

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78607] opened 2023-06-23 10:08 UTC
### Godot version

4.1.beta.3

### System information

Windows 11

### Issue description

Cursor in the editor is being lost in many scenarios in 4.1.beta 3. I could catch in one of the scenarios, while closing scripts

https://github.com/godotengine/godot/assets/84369217/2de85cb1-69da-40e3-84f0-0e962f6d1d91

### Steps to reproduce

Open two scripts A and B in the editor. 
Close the script B while editing script A. 

Curor is lost.

Workaround: Save the file, cursor will be back.

### Minimal reproduction project

N.A

**Comment by akien-mga** [comment] 2023-06-23 10:13
Thanks for the report!

- Duplicate of #78589, consolidating there.

**Closed by akien-mga** 2023-06-23 10:13 UTC
