### ISSUE TITLE
Pixel artifacts near light on low resolution with multiple meshes

### ISSUE THREAD

**Issue by RealMikadoe** [godotengine/godot#75463] opened 2023-03-29 14:02 UTC
### Godot version

4.0 stable

### System information

Windows 10, NVIDIA GeForce GTX 1660 Ti, Vulkan

### Issue description

When moving around near multiple meshes and a light source, pixel artifacts start appearing on the screen. These appear for a split second and then disappear again.

![bug](https://user-images.githubusercontent.com/95089122/228562003-a4b612de-88e4-487b-a5c0-d0b35462d9b1.gif)

### Steps to reproduce

Create a new 3D project in godot 4.0
Add a simple player character with basic movement (mouse movement is not necessary but can make it easier to spot)
Create 4 box meshes and connect them
Add an OmniLight3D or DirectionalLight3D
Set the viewport resolution to something like 640 by 320 (lower makes it easier to spot)
Run the scene and move around with the character

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11101643/bug.zip)

**Comment by Calinou** [comment] 2023-03-29 18:10
- Duplicate of https://github.com/godotengine/godot/issues/16337 (same cause).

**Closed by Calinou** 2023-03-29 18:10 UTC
