### ISSUE TITLE
Function texture_set_shrink_all_x2_on_set_data is missing from Godot 4 RenderingServer

### ISSUE THREAD

**Issue by k8035** [godotengine/godot#67261] opened 2022-10-11 15:10 UTC
### Godot version

4.0.beta2.mono

### System information

Windows 11

### Issue description

The method `void texture_set_shrink_all_x2_on_set_data ( bool shrink )` (see [3.x documentation here](https://docs.godotengine.org/en/stable/classes/class_visualserver.html#class-visualserver-method-texture-set-shrink-all-x2-on-set-data)) is not available in Godot 4's renamed [RenderingServer](https://docs.godotengine.org/en/latest/classes/class_renderingserver.html) class.

We use the method for the purpose described here:

https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#reducing-aliasing-on-downsampling

> If the game has a very high base resolution (e.g. 3840×2160), aliasing might appear when downsampling to something considerably lower like 1280×720. Aliasing can be made less visible by shrinking all images by a factor of 2 upon loading. This can be done by calling the method below before the game data is loaded:
> 
> VisualServer.texture_set_shrink_all_x2_on_set_data(true)

We decide to call or not call the `texture_set_shrink_all_x2_on_set_data` method depending on the screen resolution. For resolutions of 2880x1620 or higher, we use the original textures that are optimized for 3840x2160 and do not call that method. For lower resolutions like 1920x1080, we call `texture_set_shrink_all_x2_on_set_data` in order to reduce the required texture memory and to reduce aliasing.

Available alternative: we could use mipmapping instead. However, this needlessly increases texture memory usage when the user is running a resolution like 1920x1080.

### Steps to reproduce

(Using Godot 3.x)
- Create a 2D project and set the base size to 3840x2160
- Import some texture and place it as an image in the scene.
- When running the project at a resolution of 3840x2160, the texture will be displayed in original quality.
- Add the method `texture_set_shrink_all_x2_on_set_data` to ready() of the main scene, in an IF statement that checks whether the screen resolution is lower than 2880x1620.
- When running the project at a resolution of 1920x1080, the texture should be displayed at half its resolution, reducing aliasing and reducing memory usage.

**Comment by clayjohn** [comment] 2022-10-11 17:11
I believe this functionality was moved to the importer in Godot 4.0. That being said, it sounds like your game relies on having the ability to downscale all textures at run time, so an importer option may be of little help.

**Comment by Calinou** [comment] 2022-10-14 16:20
Duplicate of https://github.com/godotengine/godot/issues/43276. Please post your findings there as a comment :slightly_smiling_face:

**Closed by Calinou** 2022-10-14 16:20 UTC
Labels: discussion, topic:rendering, topic:import
