### ISSUE TITLE
Godot crashes when moving/renaming a scene and an attached script at the same time

### ISSUE THREAD

**Issue by EmeraldSlash** [godotengine/godot#29266] opened 2019-05-29 00:15 UTC
**Godot version:** 3.1

**OS/device including version:** Windows 7 Pro x64

**Issue description:** When the user tries to move a scene (along with its attached .gd file) Godot's file system pane which is a dependency in another scene, Godot crashes. Similarly, when renaming a directory which contains scene-script pairs that are a dependency for another scene, Godot also crashes. Does not occur when moving any of the items individually, only when you move scene-script pairs.

**Steps to reproduce:**
- Make a new scene (this will be the one you drag along with its script)
- Attach a script and save it in the same folder as the scene is saved in
- Make another scene (this will be the one with the dependency)
- Insert the first scene into this second scene to create the dependency
- Drag script and scene into a new folder at the same time OR rename the folder scene-script pair are in (depending on which instance of this issue you would like to reproduce)

**Comment by KoBeWi** [comment] 2019-05-29 00:49
Does it always happen, like, in a fresh project? I can't reproduce it. Might be related to the recurring crash that happens randomly when moving resource folders, but it's hard to reproduce.

**Comment by EmeraldSlash** [comment] 2019-05-29 02:42
I tried it again myself in a new project and reproduced the issue, and wrote the following explanation:

>Tried it myself on a new project and found that it was a little more complicated than what I described. There also needs to be another scene that is dependent on the scene being moved. To cause the issue, simply drag the scene-script pair out of the 'folder'. It will crash every time - however due to the way Godot works, doing it again in a fresh instance of the editor (where the scene that has the dependency is in a state where its dependencies are missing) will not work and you must update the dependency of the scene and save before you can reproduce the crash again.

However I tried it again and now it's not being reproduced. At this stage I'm unsure how exactly to reproduce it reliably, however when it does occur it follows a pattern. I'll try and narrow it down. It doesn't feel random, but yeah it could be related.

**Comment by avencherus** [comment] 2019-05-29 06:55
I had some issue with this in the past when I had some tool code that was checking on scenes in the editor.  A rename would crash the editor sometimes and sometimes not, it was difficult to reproduce.

I ended up going a different route with the code, so it wasn't actually doing anything with the scenes besides doing a filename comparison.  This line of deadcode was the source of the crashing.

When running in debug, these crashes would occur at some line where Godot was trying to access a scene, and it was no longer valid.  I assume because it was renamed and perhaps the references were changed or lost.

That issue is likely not related, I mention it though for any potential debuggers, because the problem might also be some code relying on a bad scene reference during the editor renaming process.  These seem to cause crashes without raising any errors.

**Comment by PabloNeirotti** [comment] 2019-07-03 18:45
I also had this issue happen. I moved a png which was at the same level of my tscn, into a Textures subfolder. This crashed Godot, and then when opening that tscn file it asks me to manually fix dependencies.

I think it crashed because I already had the scene opened.

**Comment by RobTheFiveNine** [comment] 2019-08-14 15:25
I have also been experiencing this in v3.1.1 running under Ubuntu 18.04. I have been renaming some directories, and if they have any scenes underneath them that reference scripts that are also in the same tree, Godot will crash every time (but does successfully rename the directory and update the paths)

**Comment by sbward** [comment] 2019-10-20 02:37
I just experienced this bug in 3.1.1 on MacOS Catalina.  I moved a scene and the root node script of that scene from the filesystem root into a subdirectory, then the progress meter froze partway through, and after a few seconds Godot crashed.  Upon reopening my project I was shown the Fix Dependencies modal.

Although it would be a major change, #15673 is worth considering to help prevent these kinds of issues.

**Comment by Tralexium** [comment] 2020-06-01 16:59
Currently on version 3.2.1 and I've experienced this bug when renaming the source folder which had a nested unsaved scene. This is a completely fresh project, which gives me hopes that it's not a very niche issue.

Events before crash:
- Created project
- Disabled 3D editor and asset editor via the "Editor -> Manage Editor Features..." tab
- Created a new 2DNode and added it as a new scene (still unsaved at this point)
- Deleted the default scene that comes with a new project
- Nested a ColorRect node to the root node Node2D
- Attached a script to the root node, didn't save the code
- Added assets from a zip to a new folder called Assets, this is outside of the Source folder
- Tried to rename the Source folder (scene was still considered unnamed at that point)
- Crash happens

Post crash:
- Reopening the engine reveals that the script has been detached from the player scene
- The ColorRect node seems to have disappeared due to not saving the scene before renaming the folder

Here's my folder hierarchy:
![image](https://user-images.githubusercontent.com/44052517/83433458-4703b700-a431-11ea-9c7b-1361e10f1b9f.png)

**Comment by MooSoup** [comment] 2021-07-24 20:09
Still crashing in 3.3.2 :| I renamed my Sprite to Player Sprite, forgot to add the change to my script, crash, I change the name in the script, still crash... I reversed everything, crash
![A5bZt3RQfG](https://user-images.githubusercontent.com/58120191/126880102-0e590ee7-5bd5-4132-b6ae-de86ec3b4505.png)

**Comment by RobTheFiveNine** [comment] 2023-05-14 11:08
> Does the crash still happen for anyone? I wasn't able to get the editor to crash in any of the configurations discussed here for either 3.5 or 4.0.2. I do get the same error message as mentioned by @Calinou in #59116 on both engine versions. Maybe one of these two issues should be treated as a duplicate of the other one from now on?

I've not run into it recently. I just took a look at my reply further up the thread and the sepcific scenario I mentioned I have been doing a lot the last week and it hasn't crashed Godot (using 4.0.1 and 4.0.2).

**Comment by akien-mga** [comment] 2023-05-15 11:24
Thanks, closing as fixed then.

**Closed by akien-mga** 2023-05-15 11:24 UTC
Labels: bug, topic:editor, confirmed, needs testing, crash

**Comment by patrick-motard** [comment] 2023-07-25 13:46
I've run into this issue today on Godot 4.1.  I have a scene, `DevScene` that instantiates another scene `dev_row`. It instantiates multiple instances of `dev_row.tscn`, both via the editor, and via code. In the filesystem view, i right clicked on `dev_row`, selected rename, and renamed the scene `DevRow`. After, `DevScene` became corrupt.

```
  Cannot open file 'res://scenes/dev_row.tscn'.
  Failed loading resource: res://scenes/dev_row.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/packed_scene.cpp:1033 - Method/function failed. Returning: err
  scene/resources/packed_scene.cpp:92 - Condition "nc == 0" is true. Returning: nullptr
  Attempting to parent and popup a dialog that already has a parent.
  editor/editor_data.cpp:880 - Index p_idx = 5 is out of bounds (edited_scene.size() = 5).
  editor/editor_data.cpp:683 - Index p_idx = 5 is out of bounds (edited_scene.size() = 5).
  editor/editor_data.cpp:745 - Index p_idx = 5 is out of bounds (edited_scene.size() = 5).
  ```
  
  I am not able to open the `DevScene` scene in Godot and manually update the references to `dev_row`. Godot claims it's corrupt. I'm currently trying to figure out how to fix this. I thought I would chime in here since this issue has been closed as fixed, but I don't think it is.

**Comment by Zireael07** [comment] 2023-07-25 13:48
@patrick-motard .tscn is human-readable and editable by other editors such as Notepad, Notepad++ or Visual Studio.

While annoying, I've personally had to resort to such a manual approach to fix some other kind of breakage.

**Comment by patrick-motard** [comment] 2023-07-25 13:54
I closed Godot, and re-opened it. From there, I was able to open `DevScene.tscn`. The following error was present:
```
 res://scenes/DevScene.gd:12 - Parse Error: Preload file "res://scenes/dev_row.tscn" does not exist.
 res://scenes/DevScene.gd:12 - Parse Error: Could not resolve type for variable "dev_row_scene".
 ```
 
 This is the error I would expect to see, as Godot did not fix/update references to the renamed scene in other scenes scripts that reference it. After updating the reference in the script in question, the game now launches. 
 
 I see two issues here:
 1. Godot scenes referencing renamed scenes become corrupt upon renaming. A restart of Godot is necessary for the user to perform manual renaming.
 2. Godot does not automatically rename references to renamed scenes in Gdscripts. The user must manually fix each path/name.
 
 I can do without the second issue being fixed, but the first seems rather unfriendly to end users.

**Comment by KoBeWi** [comment] 2023-07-25 13:55
You mean renaming inside Godot or outside?

**Comment by patrick-motard** [comment] 2023-07-25 13:55
@Zireael07 good point. I noticed the same while checking my `tcsn` files into source control. I'll keep that in my back pocket for future cases. @akien-mga -- since you closed this issue originally, would you expect this issue to be re-opened or would you like a new one submitted?

**Comment by patrick-motard** [comment] 2023-07-25 13:56
@KoBeWi to whom are you referring to? I can edit my [comment ](https://github.com/godotengine/godot/issues/29266#issuecomment-1649892898)to be more clear.

**Comment by KoBeWi** [comment] 2023-07-25 14:08
> Godot scenes referencing renamed scenes become corrupt upon renaming.

@patrick-motard This ^

> would you expect this issue to be re-opened or would you like a new one submitted?

Unless you have a minimal project and some steps how this can be reproduced, (re)opening the issue is pointless.

**Comment by patrick-motard** [comment] 2023-07-25 14:47
@KoBeWi - I hear you loud and clear on needing steps to be able to reproduce this. I have limited time right now, but I can come back to this in September. I'll try to reproduce it in a new project.

**Comment by maridany1999** [comment] 2023-10-17 17:01
I often experience the same issue (but I don't know why it happens, since doesn't give any logs). However, renaming a Scene (F2) through the FileSystem, the engine crashes and closes automatically. This usually happens when I have the scene that I'm renaming opened. Also, I have a script attached to the scene, which include exported variables

The temporary solution to avoid this issue is to close the scene before renaming it. At least, it has worked for me.

**Comment by KoBeWi** [comment] 2023-10-17 17:05
@maridany1999 Is it specific to your project or does it happen in a fresh project too?

**Comment by maridany1999** [comment] 2023-10-17 18:09
@KoBeWi I've been only experiencing on my project, and it does not happen in a new project. Additionally, it's really difficult to reproduce it, since it has some sort of 1% chance for the crash to happen. I'll keep experimenting, and messing around with, to see if I can recreate it.

The crash usually happened when I was doing this:
(In the FileSystem Window)
1 - Duplicate Scene, and give new name
(Open Duplicated Scene)
2 - Change the Script Attached to the new duplicated scene
3 - Rename Nodes inside the new duplicated scene
(In the FileSystem Window)
4 - Then, Pressing F2, to change the name of the new duplicated scene -> Small chance to cause a crash
