### ISSUE TITLE
Light2D scale - scalar multiplication tending to zero || det == 0

### ISSUE THREAD

**Issue by zzz-assault** [godotengine/godot#25986] opened 2019-02-17 20:40 UTC
**Godot Version:**
- 3.1 Beta 5

**OS/device including version:**
- Windows 10
- RTX 2080
- I7 8700

**Issue description:**
With the switch from Beta 4 to Beta 5 the following error occured (100+ same errors per second).
_"E 0:00:23:0627 Condition ' det == 0 ' is true. <C Source> core/math/transform_2d.cpp:51 @ affine_invert()"_

**Steps to reproduce:**
Modify the Light2D scale within the physics_process with 0.x multiplication.
I assume this is also valid for process, but haven't tested it.

_**Hint:** tried a few other node types, it seems that only Light2D is causing errors with the above mentioned multiplication_

**Minimal reproduction project:**
- Create new project
- add Node2D as root (main scene)
- add Light2D (just add Godot Icon as texture)
- add script to Light2D 
`func _physics_process(var delta : float):
	scale *= 0.5`

**Comment by akien-mga** [comment] 2019-02-17 21:31
I can reproduce this both in all beta builds from beta 1 to beta 5, so it doesn't seem to be a regression.
It's also kind of expected when setting a scale of 0.

**Comment by zzz-assault** [comment] 2019-02-17 22:24
So for me it's no issue, I just solved it otherwise.
But strangewise I'll never experienced this error message in Beta 4.

In addition, please be aware, that a endless multiplication with 0.5 will never hit 0 -> so it might be a bug (also other nodes don't bother with it).

**Comment by akien-mga** [comment] 2019-02-18 09:02
> In addition, please be aware, that a endless multiplication with 0.5 will never hit 0

In symbolic computation, that's correct, but not in floating point algebra. With floating point you may even hit -0.0000002137 or similar.

**Comment by zzz-assault** [comment] 2019-02-18 20:33
Thx for the explanation, wasn't aware about the float limits.

But still there is an inconsistency compared to other nodes, as for example a **Sprite Node**, with the exact same script doesn't show this error. I assume there is some "save state condition" in the code, which is not valid for Light2D anymore (and I swear with Beta4 the error wasn't existing for me … :-) )

**Comment by akien-mga** [comment] 2019-02-19 07:48
Yeah, I agree that there's still a bug that should be handled in the engine (likely in the rendering code). 

But as per the above, making scale tend towards zero is asking for trouble ;) If you want an element to shrink down and disappear, it would be better to tween the scale to something small enough (e.g. 0.05) and then `hide()` it.

**Comment by zzz-assault** [comment] 2019-02-21 22:45
As mentioned above, I changed my code … the endless multiplication of 0.5 was just a placeholder, which lead to the error … :-)

**Comment by akien-mga** [comment] 2020-06-20 21:09
Still reproducible in 3.2.2 RC 2.

**Comment by JestemStefan** [comment] 2021-07-09 18:26
> 
> 
> Thx for the explanation, wasn't aware about the float limits.
> 
> But still there is an inconsistency compared to other nodes, as for example a **Sprite Node**, with the exact same script doesn't show this error. I assume there is some "save state condition" in the code, which is not valid for Light2D anymore (and I swear with Beta4 the error wasn't existing for me … :-) )

This seems to be correct. In `node_2d.cpp` when some value approach 0 it's set to Epsilon instead.
![obraz](https://user-images.githubusercontent.com/37214990/125121249-ea72d100-e0f3-11eb-8e22-ed40b1fe825a.png)

**Comment by JestemStefan** [comment] 2021-07-11 05:44
Kinda reproducible in master build `v4.0.dev.custom_build [374ffbe2d]`.

Difference is: `det == 0` error is printed twice, scale reach 0 according to `print_debug` and then `scale` is back to `0.00001`.

Checking if #50351 solve this

**Comment by Calinou** [comment] 2021-08-07 13:20
Closing in favor of https://github.com/godotengine/godot/issues/41756, which has more information about the issue at hand.

**Closed by Calinou** 2021-08-07 13:20 UTC
Labels: bug, topic:core, confirmed, topic:2d

**Comment by akien-mga** [comment] 2021-08-12 13:42
> Closing in favor of #41756, which has more information about the issue at hand.

I think they might be related but different issues, since they're fixed by different PRs.

This one was just fixed by #50363.
