### ISSUE TITLE
v3.6.beta5.official [2a347ab86] Environment node visual errors

### ISSUE THREAD

**Issue by mojoyup1528** [godotengine/godot#92918] opened 2024-06-08 23:07 UTC
### Tested versions

When assigning a new WorldEnvironment with a new Environment, changing to utilize some of the parameters causes visual issues with scene. 

### System information

Windows 11 Gv3.6.beta5.official [2a347ab86]

### Issue description

Processor	13th Gen Intel(R) Core(TM) i7-13700KF   3.40 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor
Display Driver NVIDIA GeForce RTX 4070

When I create a Spatial scene and add a child WorldEnvironment node with a new Environment, some parameters dont work for me (maybe for all I don't know yet). These parameters specifically are:
-SS Reflections
-SSAO
-DOF Far Blur
-DOF Near Blur

![with_parameters](https://github.com/godotengine/godot/assets/43324644/b6121e24-f3da-49be-a126-41fd19bce451)
![without_parameters](https://github.com/godotengine/godot/assets/43324644/12ea5255-937b-4735-804c-f6055e2b2521)

So far, its only those four settings that do this. I went back to 3.5.3 (my other version), and they work just fine. Hope all is well!

### Steps to reproduce

Create a Spatial 3d Scene, Assign a WorldEnvironment Node, then give it a new Environment, and add meshinstances to the scene. Change parameters and both in editor and runtime will be bad visuals. 

### Minimal reproduction project (MRP)

[BugProject.zip](https://github.com/user-attachments/files/15749847/BugProject.zip)

**Comment by piramidamsc** [comment] 2024-06-09 00:11
Yes, indeed, ssr,ssao and dof post processing do not work on OpenGL 3.The material does not display texture or color,If you disable the depth check, the material starts to display correctly.

**Comment by mojoyup1528** [comment] 2024-06-15 17:48
UPDATE: Ive been trying to figure it out so you guys don't have more work to do :P So, I figured out so far that as long as I dont have any textures in the scene that DONT utilize refraction in the parameters, then the worldenvironment SSAO, DEPTH, and SSREF seem to work ok. Its when I have a texture that doesnt use refraction in the scene, that it breaks the ability to apply those parameters. 

My guess is, refraction is just a requirement for things to render properly, otherwise it will turn the textures black. Makes sense to me. SO for now, even if I don't require it on some textures, I just turn on refraction for all of them and it seems to work at the moment. Still a concern, but there are far more concerning Im sure! 

I can deal with this and if anyone comes across black scenes from those worldenvironment settings, just turn on refraction on all materials.

**Comment by mojoyup1528** [comment] 2024-06-16 17:35
UPDATE2: SO apparently, I am not able to get them working the way I need to. I found that you dont need all the materials to have refraction, as each material is effected separate in the scene. 

You can turn up the metallic to max and get some color going, but the texture used in the albedo at that point is not natural or colorful. It merely relies on albedo_color at that point. SO the issues remain. 

1. having ss reflections, ssao, or dof settings on, turn textures black unless the texture has refraction enabled, which then removes reflections. So they do not work at the same time. 
2. if not refraction enabled, full metallic on at least gives you color options, but texture color is ignored

General goal: To have the ability to use ss reflections and other parameters without the need for refraction parameter on material, as refraction gets rid of reflections, but is needed to retain albedo_texture colors. 

So you either get reflections without color, or no reflection with color

Hope that was not confusing.

**Comment by Calinou** [comment] 2024-06-16 19:10
> just turn on refraction on all materials as long as you can deal with not having shadows, but thats as far as I got testing.

Enabling refraction on a material forces it to be transparent, which disables shadow casting and makes rendering it much slower. It also won't provide any culling anymore since it no longer writes to the depth buffer, and therefore no longer contributes to the depth prepass.

**Comment by lawnjelly** [comment] 2024-06-19 20:35
Probably a duplicate of #91967 , which is fixed.
I couldn't seem to make much sense of the MRP, will try again tomorrow, but from the description it sounds same problem.

**Comment by lawnjelly** [comment] 2024-06-20 10:10
@mojoyup1528 If you can test an artifact from #92070 that would be useful to confirm that this issue is already fixed (or not).

**Comment by lawnjelly** [comment] 2024-06-30 11:28
Closing as no response, assuming fixed. We can reopen if this turns out to be separate bug.

**Closed by lawnjelly** 2024-06-30 11:28 UTC
Labels: bug, topic:rendering, needs testing, regression, topic:3d

**Comment by mojoyup1528** [comment] 2024-06-30 15:26
Sorry Ive been very busy. If its already removed Ill just continue with what I can. NO worries. If you still want me to test, let me know and Ill help out some more :)
