### ISSUE TITLE
2D Continuosus collision detection by raycasting mode broken

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#35803] opened 2020-01-31 20:48 UTC
Godot version: Godot_v3.2-stable_win64
OS/device including version: win64

problem: When 2d Continuous raycasting mode is turned on, things get bounced in the opposite direction.

The problem seemed to be located here (collision detection by raycasting mode):

https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/servers/physics_2d/body_pair_2d_sw.cpp#L171

The contact seems to be flipped. Don't exactly know whats going on with the function, but it seems a little off.  
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/servers/physics_2d/body_pair_2d_sw.cpp#L214-L217

[flipped gif](https://imgur.com/a/UsgoR5z)
[unflipped gif](https://imgur.com/a/fuN2RIX)
[temp fix gif](https://imgur.com/a/hEq0tXg)

Seems to cause the problem in #32138

**Comment by Calinou** [comment] 2020-01-31 21:57
Duplicate of #32138. Still, thanks for the detailed information :slightly_smiling_face: Feel free to copy-paste OP into a comment in that issue.

**Closed by Calinou** 2020-01-31 21:57 UTC
