### ISSUE TITLE
Ctrl-S inconsistently fails to save the Script Editor.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#42864] opened 2020-10-16 21:40 UTC
**Godot version:**
3.2.3.stable and master (e273f83)

**OS/device including version:**
Windows 10 [10.0.18362.1082]
NVIDIA GeForce RTX 2080 Ti
Driver 452.06

**Issue description:**
When pressing Ctrl-S from Script view while an [empty] scene tab is selected, confusing messages are displayed, and the script fails to save.

To make things more confusing, the Godot editor does *not* notify about unsaved scripts when closing the editor.

Additionally, Godot 4.0.dev shows a message saying "Saved 1 modified resource(s)". This is a trap. It didn't actually save the script. Oddly, this shows *instead* of the "root node required to save the scene", inconsistently, which adds more confusion here.

After having lost several hours of work once and almost losing my work a second time, I decided to file this bug, because inconsistent behavior for something as important as saving seems like a bug.

Basically, the behavior of the Script editor should not depend on whether the 2D or 3D editor has an [empty] scene open, because it is not attached to the currently open scene. If Ctrl-S saves the current script automatically in some cases, it should save the current scene *always*. My preference would be to err on the side of saving *too much* rather than *not enough*.

If it is not possible to fix this due to technical limitations, I would propose that saving the current script on Ctrl-S should be *removed* as the real problem here is inconsistent behavior.

**Steps to reproduce:**
1. Open a new Godot project.
2. Create a .gd script
3. Close the default scene, if any.
4. Do work from the Script view, and attempt to save. One of these dialogs may appear:
    <img width="333" alt="saved_1_modified_resources" src="https://user-images.githubusercontent.com/39946030/96310315-0067c100-0fbc-11eb-894d-9bacb2708df4.png">
    <img width="209" alt="godot_ctrl-s_not_working" src="https://user-images.githubusercontent.com/39946030/96310338-0bbaec80-0fbc-11eb-8eae-2b8c1d4ace07.png">
Regardless of the dialog presented, the script is not saved.
5. Close the editor, notice no attempt is made to notify you of the unsaved script.
6. Reopen Godot, and find that the changes made to the .gd script were lost without warning.
7. Open a new scene and save it as a file.
8. Now attempt to make script changes and hit ctrl-s. Repeat closing and reopening the editor.
9. The script changes *are* saved in this case.

**Minimal reproduction project:**
Happens in any project.

**Comment by Calinou** [comment] 2020-10-16 21:45
Duplicate of https://github.com/godotengine/godot/issues/9069.

**Closed by Calinou** 2020-10-16 21:45 UTC
