### ISSUE TITLE
Godot 3 Particle Curves *Fixnum Build*

### ISSUE THREAD

**Issue by riirii** [godotengine/godot#8493] opened 2017-04-22 21:39 UTC
**Operating system or device - Godot version:**

Windows 64-bit

**Issue description:**

Tried selecting the points in the 3d particle scale curve editor. Each time could only make points beside the point I was trying to select. Sometimes I could select a point, but most of the time it just created new points as I tried to select one.

**Steps to reproduce:**

Create a 3d particle system. Set your mesh. Set your particle material. Go into the scale curve editor. Select either point at the beginning or the end. It will make new points instead most of the time. Try to create a point in the middle of the curve. Now try to select it. Most of the time all you can do is create a new point beside it or on top of it.

Possible issue is that the selection area is way too small.

**Comment by nunodonato** [comment] 2017-04-22 22:17
I can confirm this (Linux).

Its not about particles at all, just the new Curve texture. Probably a WIP that @reduz still needs to improve

**Comment by RameshRavone** [comment] 2017-04-23 02:42
Fixed with #8495

**Comment by kubecz3k** [comment] 2017-08-10 18:52
I'm confused. What is the status of this issue? Is it still bugged?

**Comment by kubecz3k** [comment] 2017-08-10 18:59
I'm unable to reproduce in e93ce339dcdf4e9ade63286cfa04cdd4b5a8ecd4 so I guess It's fixed.

**Closed by kubecz3k** 2017-08-10 18:59 UTC
Labels: bug, confirmed, topic:editor, usability
