### ISSUE TITLE
Ability to copy/cut/paste nodes

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#19471] opened 2018-06-09 16:32 UTC
**Godot version:**
Godot 3.0.3-rc3

**OS/device including version:**
Windows 10

**Issue description:**
Often times, I'll be setting up a node only to realize that I should have put it somewhere else, like moving it into a different scene. I'd like to be able to copy/cut and paste nodes in different scenes.

**Steps to reproduce:**
Create a scene with a node of any type. Create a new scene and try to move the node from the first scene into the new one.

**Comment by vnen** [comment] 2018-06-09 17:30
Duplicate of #3720

**Closed by vnen** 2018-06-09 17:30 UTC
