### ISSUE TITLE
Setting scale x on kinematic body to negative is instead changing scale y to -1

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#42219] opened 2020-09-20 22:22 UTC
**Godot version:**
3.2.2 stable

**OS/device including version:**
linux mint

**Issue description:**
I have a kinematic body 2d with raycasts. I am setting scale.x to -1 so that I can easily reverse all the rays.

However, when I change the scale.x to -1:
![image](https://user-images.githubusercontent.com/12863685/93723425-69fbd780-fb96-11ea-8c13-9cb5e597f168.png)

As soon as my next call to either move and slide or move and collide happens, scale.x turns to 1 and scale.y turns to -1 in the debug window:
![image](https://user-images.githubusercontent.com/12863685/93723552-438a6c00-fb97-11ea-904f-3927ec7fe2ba.png)

But note, the image has not flipped vertically, just horizontally exactly as my code changed it to -1. 

BUT! my kinematic body which is now flipped horizontally now thinks it's current state is 1. So when I set scale.x back to 1 in code, nothing happens because it thinks 1 is now -1.

Literally this is all my code is:

```
func _set_facing():
   scale.x=facing

func _move(_delta):
	if Globals.bullet_time==1.0:
		velocity.x=lerp(velocity.x,MAX_SPEED*move_direction,_get_h_weight())
	else:
		velocity.x=lerp(velocity.x,MAX_SPEED*move_direction,_get_h_weight())*(0.5)
		
	velocity=move_and_slide(velocity,Vector2.UP)

```

I have read various bugs stating scale doesn't work very well with kinematic bodies and move and slide, but come on! surely it should be working as expected after all these years, otherwise what is the point of being able to set scale?

I have noticed loads of similar faults, but nothing ever gets done. This one is from 2016!
https://github.com/godotengine/godot/issues/5929

That one says don't flip kinematic, only the sprite. So as above, what is the point in having scale on a kinematic2d (I know it's a node2d), but that bug is saying only flip the sprite, which has it's own flip_h.

Unless you can suggest a way to have 2D characters that reverse direction and swap every single one of it's nodes to the opposite side easily?

**Steps to reproduce:**
1. create a kinematic body
2. set scale x to -1
3. call move and slide or move and collide
4. check the debug information
5. try and change scale x to 1 and nothing happens

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-09-20 22:58
Have you looked into the RemoteTransform/RemoteTransform2D nodes? These can be used to apply translation/rotation/scale to nodes without having to parent them to other nodes. Maybe you can use them to avoid having to flip the body.

**Comment by aaronfranke** [comment] 2020-09-21 04:30
Duplicate of #17405, same symptom as #21849.

**Closed by aaronfranke** 2020-09-21 04:30 UTC
Labels: archived, topic:physics
