### ISSUE TITLE
InputEventMouseButton events ignore modifiers (eg. cannot ctrl+mousewheel)

### ISSUE THREAD

**Issue by maackey** [godotengine/godot#37835] opened 2020-04-13 02:11 UTC
**Godot version:**
3.2.stable.official

**OS/device including version:**
Ubuntu 18.04.4 LTS 

**Issue description:**
InputEventMouseButton events ignore modifiers (eg. cannot ctrl+mousewheel)
It appears that all of the mouse buttons ignore all of the modifiers
InputEventKey events work as expected

**Steps to reproduce:**
 - Create a new InputEventMouseButton or detect one from the player
 - Set a modifier on the event from InputEventWithModifiers (InputEventMouseButton inherits)
 - Bind the event to an action -- note that the action will fire regardless of the modifier key

**Comment by akien-mga** [comment] 2021-09-17 11:12
Closing as duplicate of #52776 (newer issue but it includes a reproduction project).

**Closed by akien-mga** 2021-09-17 11:12 UTC
Labels: bug, discussion, topic:input
