### ISSUE TITLE
Dragging items in inspector causes scrollbar drag issues (4.0)

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#44878] opened 2021-01-02 18:51 UTC
**Godot version:**
v4.0.dev.custom_build.41e902886
hash:41e9028868e49669de83c82ba20fd9dcef0d1b8b

**OS/device including version:**
Windows 10

**Issue description:**
When you have enough items in the Filesystem, if you try to drag a up or down, the scrollbar will glitch. 
For example:
-the scrollbar starts dragging with it the item

-the scrollbar resets its position each time you move the mouse (while pressed)
-when you release the item the scrollbar keeps following the mouse (even though it's not pressed anymore)

**Steps to reproduce**
Create enough items in the filesystem so that the scrollbar appears. 
Then drag items up and down in FileSystem (enough so that the scroll bar has to move)
This project has enough items so the scrollbar appears:
[Drag.zip](https://github.com/godotengine/godot/files/5760744/Drag.zip)

https://user-images.githubusercontent.com/47060866/103465635-cfba3c80-4d0b-11eb-8b37-0f8d7e2888a9.mp4

**Comment by Calinou** [comment] 2021-01-02 20:56
Duplicate of https://github.com/godotengine/godot/issues/38665.

**Closed by Calinou** 2021-01-02 20:56 UTC
