### ISSUE TITLE
Game on fullscreen lags

### ISSUE THREAD

**Issue by Worly** [godotengine/godot#4660] opened 2016-05-15 14:31 UTC
**Operating system or device - Godot version:**
Windows 10 x64, CPU: Intel i3, GPU: Nvidia Geforce GTX 950 
Godot version: 2.0.3

**Issue description** (what happened, and what was expected):
When game is on fullscreen moving sprites lag a bit, but when it's on windowed everything works fine.
I checked the fps and it always stays at 60.

**Comment by Calinou** [comment] 2016-05-15 16:09
Did you test with running the game from the editor, or from an exported game (release or debug mode)?

**Comment by bojidar-bg** [comment] 2016-05-15 17:40
If it is related to V-Sync, it might be duplicate of #4605.

**Comment by Worly** [comment] 2016-05-15 17:56
V-Sync is forced I think and it happens in editor and exported game(release), and I forgot to mention, it only occurs when there are more than few animated sprites changing their frame.

**Comment by kubecz3k** [comment] 2016-05-16 07:58
@Worly Could you check how "Motion Test" demo is behaving for you? I think it might be related to https://github.com/godotengine/godot/issues/2043

**Comment by Worly** [comment] 2016-05-16 11:42
I updated my graphic card drivers and it's ok now, but before update other games ran smoothly so should I just close this issue or what? Motion test runs smoothly now too. 

Thank you for reply

**Comment by kubecz3k** [comment] 2016-05-16 13:03
It seems the bug was in the part of your graphic driver that is responsible for opengl support.  Guess we will close this issue then, since there is nothing to fix on our side.

**Closed by kubecz3k** 2016-05-16 13:03 UTC
Labels: archived
