### ISSUE TITLE
Snap package fails to initialize video driver

### ISSUE THREAD

**Issue by lundybernard** [godotengine/godot#27548] opened 2019-03-30 23:49 UTC
**Godot version:**

Snap install
3.1.stable.official

**OS/device including version:**

Ubuntu 18.04.2 LTS
4.15.0-46-generic
alienware 13 r3

**Issue description:**

Godot fails to start:
```
> godot
cp: cannot stat '/snap/godot/45/usr/share/mime': No such file or directory
Directory '/home/lb/snap/godot/45/.local/share/mime/packages' does not exist!
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:167.

(zenity:1252): GdkPixbuf-WARNING **: 16:36:54.933: Cannot open pixbuf loader module file '/home/lb/snap/godot/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/lb/snap/godot/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
Fontconfig error: Cannot load default config file

(zenity:1252): GdkPixbuf-WARNING **: 16:36:55.001: Cannot open pixbuf loader module file '/home/lb/snap/godot/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/lb/snap/godot/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

(zenity:1252): Gtk-WARNING **: 16:36:55.001: Could not load a pixbuf from /org/gtk/libgtk/icons/48x48/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```
Followed directions to run `gdk-pixbuf-query-loaders > /home/lb/snap/godot/common/.cache/gdk-pixbuf-loaders.cache`
installed libgdk-pixbuf2.0-dev, and the command succeeds.

**Steps to reproduce:**
Install Godot from snap `> snap install godot --classic --stable` and run godot
or install godot from the ubuntu software center

**Minimal reproduction project:**

none needed

**Comment by ShyRed** [comment] 2019-04-01 16:47
According to [Stackoverflow](https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update) the error messages seem to indicate missing or broken graphics drivers:

> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast

Can you (re-)install the graphics drivers for your system and try again?

**Comment by ShyRed** [comment] 2019-04-01 17:05
Same issue as #27494 ?

**Comment by lundybernard** [comment] 2019-04-01 18:03
I was able to install Godot via Steam, and it runs successfully.
no system changes, and I confirmed that the snap installed version still fails as described above.

**Comment by ShyRed** [comment] 2019-04-01 18:11
This is interesting... 🤔 

Can you give it a shot and try the version of the [official website](https://godotengine.org/download/linux), too?

**Comment by lundybernard** [comment] 2019-04-01 18:21
yes, the official binary also runs without any errors.  looks like it is specific to the snap install

```
> ./Godot_v3.1-stable_x11.64 
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
```

**Comment by qarmin** [comment] 2019-04-01 19:03
I got same issue on Ubuntu 18.04.2 with Nvidia GTX 970 drivers 415. 
Compiled and downloaded Godot, works good.

**Comment by akien-mga** [comment] 2019-04-01 20:51
CC @popey

**Comment by nikvaessen** [comment] 2019-06-03 18:19
exact same issue with ubuntu 18.04 running nvidia driver `418.67` and CUDA Version: `10.1`.

I also have the exact same issue running steam:

```
$ steam
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

```
$ godot
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

According to https://github.com/ValveSoftware/steam-for-linux/issues/6116 the issue is related to nvidia not bundling 32 bit run time libraries anymore. Can this be the case for the snap install? However, the binary `Godot_v3.1.1-stable_x11.64` downloaded from `https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_x11.64.zip` works as expected.

**Comment by Axelaredz** [comment] 2019-10-02 11:00
also error message when using Godot from Snap
`axel@redz:~$ godot
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:167.
`

**Comment by xuv** [comment] 2019-10-09 10:20
I can confirm, Snap store version is generating the error.
1. Reinstalled nVidia drivers, did not work
2. Installed 64 bit version from [official website](https://godotengine.org/download/linux), works perfectly

Tested on Ubuntu 18.04.1 with latest updates

**Comment by mattiaswerner** [comment] 2019-11-01 12:51
Affecting me as well on a fully updated 18.04, with a 970 gtx and tested nvidia drivers from 415 to 440.

**Comment by Calinou** [comment] 2019-11-01 14:27
@mattiaswerner Thanks for confirming this :slightly_smiling_face:

As this issue is stemming from an unofficial distribution of Godot, I'll close this. Please report issues related to the Snap [here](https://forum.snapcraft.io/t/godot-engine-call-for-testing/4997).

**Closed by Calinou** 2019-11-01 14:27 UTC
Labels: bug, platform:linuxbsd, topic:porting
