### ISSUE TITLE
AnimationPlayer Audio clips end offset cuts starting form the end

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#19421] opened 2018-06-07 17:14 UTC
**Godot version:**

Godot master efdd0c4

**OS/device including version:**

Windows 10

**Issue description:**

![https://i.imgur.com/yjGsZn3.gifv](https://i.imgur.com/yjGsZn3.gif)

It should cut starting from the beggining of the clip so if you set the end offset to 10 it should make the clip 10 seconds long not <length_of_clip> - 10

**Comment by reduz** [comment] 2018-11-19 16:03
Sorry, this is working as intended. End offset cuts from the end, which makes perfect sense when you edit it visually. Closing.

**Closed by reduz** 2018-11-19 16:03 UTC
Labels: bug, topic:editor
