### ISSUE TITLE
Exporting custom Resource is always null.

### ISSUE THREAD

**Issue by MackyK** [godotengine/godot#73329] opened 2023-02-15 02:46 UTC
### Godot version

4.0.rc2

### System information

Windows 10

### Issue description

After setting a custom resource in export variable then running the project the variable is always null.

### Steps to reproduce

Create a script with class_name that extends Resource.
Create a Node script with an export type of the custom resource class.
Write Print() with the export variable in _ready function
Create the custom resource file in File System.
Drag and Drop custom resource file into the export property on the node.
Run Scene
Output: null

### Minimal reproduction project

Unable to provide project due to another bug. "Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'CustomResource' and its derivatives."

**Comment by prominentdetail** [comment] 2023-02-15 21:17
maybe a related issue: https://github.com/godotengine/godot/issues/72563

**Comment by Calinou** [comment] 2023-02-15 21:23
Duplicate of https://github.com/godotengine/godot/issues/66862.

**Closed by Calinou** 2023-02-15 21:23 UTC
Labels: bug, topic:gdscript, topic:editor
