### ISSUE TITLE
Game does not start if Camera2D has an external script attached

### ISSUE THREAD

**Issue by Endojo** [godotengine/godot#25343] opened 2019-01-26 14:26 UTC
commit 35c1694
Xiaomi POCOPHONE F1 (Android 9)
GLES2 and GLES3

If a project is started via the editor on an android device and it contains a camera with a script attached to it, the splash screen flickers (first fast, then slower). Nothing else happens.

Interestingly this only happens when the script is external, when embedded into the camera node it works without errors. Other scripts on different nodes always work.

The content of the script or making it local to the scene doesn't seem to affect this behaviour in any way.

**Comment by Endojo** [comment] 2019-01-26 16:12
Turns out this also happens when another node has a script, not just the camera...
Unfortunately it seems pretty non deterministic and exporting after each try takes time so testing this is pretty slow :(

**Comment by volzhs** [comment] 2019-01-26 16:15
would you provide a sample project to test?

**Comment by Endojo** [comment] 2019-01-26 16:57
It doesn't seem to have this behaviour in 3.0.6 stable, if that helps

**Comment by samdaiya** [comment] 2019-02-10 09:33
I found that You are using Custome Package in you Export Templates maybe that's why you are facing this problem. I removed Custom debug package from Export options and it works.

**Do following steps and check if it works for you.**
* Go to Project>Export
* Select Android(Runnable) in Presets.
* Now Clear Input of  Debug as show in Screenshot below.

![screenshot](https://user-images.githubusercontent.com/17422674/52531986-e0422200-2d43-11e9-9b66-1211b3966659.png)

**Comment by akien-mga** [comment] 2019-02-25 17:34
I have a Pocophone F1 too and tried the MRP, I can't reproduce the issue with 3.1 beta 7. Can you try again? And make sure to use a template that matches your editor binary, as mentioned by @samdaiya the custom package you're using may be the issue.

**Comment by akien-mga** [comment] 2020-01-13 12:33
Closing as per the above, it was likely an issue with using an outdated custom package.

**Closed by akien-mga** 2020-01-13 12:33 UTC
Labels: bug, platform:android, topic:core
