### ISSUE TITLE
glTF Importer does not properly handle camera export from Blender

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#10176] opened 2017-08-08 20:19 UTC
**OS - Godot version:** Arch Linux - master [`8a4bce6`](https://github.com/godotengine/godot/commit/8a4bce6ebd843f9a8f482f74601f4933aae737a3)

**Issue description:**

Godot does not properly handle the importing of glTF files from blender with camera included. Using the  Khronos [glTF Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) for Blender.

**Steps to reproduce:**
Create a new mesh in blender, then export as a glTF. When exporting, tick "Export camera".

**Comment by kubecz3k** [comment] 2017-08-12 08:32
related issue: #10130

**Comment by akien-mga** [comment] 2017-08-31 05:52
Closing as duplicate of the more recent #10780, which has a stacktrace of a related editor crash.

**Closed by akien-mga** 2017-08-31 05:52 UTC
Labels: bug, topic:core
