### ISSUE TITLE
Using arrow keys to navigate 'Instance Child Scene' modal crashes editor [3.2.4-rc2]

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#46092] opened 2021-02-16 13:11 UTC
**Godot version:**
3.2.4.rc2.official

**OS/device including version:**
Ubuntu Linux 20.04

**Issue description:**
When selecting a scene to instance in the 'Instance Child Scene' modal, using the arrow keys causes some odd behaviour. When pressing the down arrow key 3 times:

1. The selection moves down by 1, as expected
2. The selection moves back up
3. The editor crashes

https://user-images.githubusercontent.com/4892574/108067141-41e6a680-7058-11eb-9d0b-cb61900fd7d6.mp4

**Steps to reproduce:**

* Click on the link icon button to open the 'Instance Child Scene' modal
* Press the down arrow key 3 times

**Minimal reproduction project:**
n/a

**Comment by akien-mga** [comment] 2021-02-16 13:28
Duplicate of #46074.

**Closed by akien-mga** 2021-02-16 13:28 UTC
Labels: bug, crash, topic:editor

**Comment by snoopdouglas** [comment] 2021-02-16 13:58
Sorry! Annoyingly, nothing came up when searching for rc2 crashes

**Comment by akien-mga** [comment] 2021-02-16 14:00
No worry, it's better to have duplicates than to miss critical issues :) (And GitHub doesn't make it easy to find duplicates, especially if already closed).
