### ISSUE TITLE
[DX12] Panorama skybox crashes editor

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#98147] opened 2024-10-13 17:28 UTC
### Tested versions

- Reproducible in 4.3.stable.

### System information

Godot v4.3.stable - Windows 10.0.22631 - d3d12 (Forward+) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 32.0.15.6081) - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

So... I have a `PanoramaSkyMaterial`

![image](https://github.com/user-attachments/assets/4d9d9182-4f09-4964-9149-8b228cf7db2f)

And i have a fancy lossless image i want to use as a skybox...

![image](https://github.com/user-attachments/assets/150a3713-8dfe-4835-9e00-a8eb3d8acc15)

And when i drag this image over `Panorama` variable to set it as skybox texture - it crashes the editor.

It happens only when i use DX12 only.

Why am i using DX12? Because i experience a severe lag on Vulkan, so, yeah, i need that

### Steps to reproduce

- Download MRP
- Launch the project, go to test.tscn
- Locate `WorldEnvironment`
- Repeat steps mention in the description
- Crash

### Minimal reproduction project (MRP)

[skyboxcrash.zip](https://github.com/user-attachments/files/17356496/skyboxcrash.zip)

**Comment by AtlaStar** [comment] 2024-10-14 22:18
was able to confirm 
![image](https://github.com/user-attachments/assets/8f1a7f16-b566-4867-8e65-afd2ed7ef5a6)

Attempted to open project in 4.3 branch and met with this access violation error caused by trying to dereference a null pointer

**Comment by AtlaStar** [comment] 2024-10-14 23:15
![image](https://github.com/user-attachments/assets/4903d411-ec39-4469-b72a-a80d808962be)
So, after building things properly, unable to reproduce with the following; Godot v4.3.1.rc (6699ae789) - Windows 10.0.19045 - d3d12 (Forward+) - dedicated AMD Radeon RX 6650 XT (Advanced Micro Devices, Inc.; 32.0.11027.1003) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

Going to compare this build to stable, then perform a bisection if necessary.

**Comment by AtlaStar** [comment] 2024-10-14 23:44
Alright, reproduced for real this time

![image](https://github.com/user-attachments/assets/152760d2-94e3-4505-8971-00d097965fc3)

Gonna bisect because it seems like the issue may have to do with mipmap generation if I understand correctly at least, as it appears that the generation can produce dimensions of 0 as shown here.

![image](https://github.com/user-attachments/assets/cafbda25-199b-475f-b715-07f3d5a03dc6)

I may be misunderstanding the core issue though.

**Comment by AtlaStar** [comment] 2024-10-15 00:34
So, bisect shows that this is a duplicate of https://github.com/godotengine/godot/issues/96352 and is in fact a mipmap issue. Fix is already in 4.4, and was in fact cherry picked for 4.3.1.rc as well.

**Comment by clayjohn** [comment] 2024-10-15 04:27
Thanks for bisecting!

Closing as already fixed!

**Closed by clayjohn** 2024-10-15 04:27 UTC
Labels: bug, needs testing, crash
