### ISSUE TITLE
InterpolatedCamera processes in editor while doing nothing

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#14488] opened 2017-12-10 01:57 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

InterpolatedCamera, with the enabled tickbox checked, caused constant display updates.
However, it did not actually do anything to its position.

2.x previously had made it move in editor. It should either reproduce that behavior, or it should not cause updates when in editor.

**Steps to reproduce:**
1. Create a scene
2. Create InterpolatedCamera
3. Set a target
4. Set enabled
5. Watch the update spinner goooooo (and your CPU cycles go up)

**Comment by kubecz3k** [comment] 2017-12-10 11:00
duplicate of https://github.com/godotengine/godot/issues/13204

**Closed by kubecz3k** 2017-12-10 11:00 UTC
