### ISSUE TITLE
Forward+/Mobile: Shadow filtering is broken with High or Ultra quality

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#97839] opened 2024-10-05 09:49 UTC
### Tested versions

e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231

### System information

Godot v4.4.dev (65f3df592) - Windows 10.0.22631 - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

### Issue description

Found another regression introduced in e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231. It looks like all filtering for shadow maps no-longer works. Once again, only affects Forward+ and mobile renderers.
Post e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231
![godot windows editor dev x86_64_EXy1sxlQmB](https://github.com/user-attachments/assets/67145097-4553-4021-b417-ba71a7d269df)
Pre e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231
![godot windows editor dev x86_64_sSUadArpKU](https://github.com/user-attachments/assets/5e253374-4454-4bf9-95b0-38a124d5ea14)

### Steps to reproduce

- Create a directional light.
- Enable a shadow.

### Minimal reproduction project (MRP)

N/A

**Comment by DarioSamo** [comment] 2024-10-05 14:33
Was the filtering improved recently? Perhaps it was a conflict from when I rebased it. CC @clayjohn 

Commenting to participate and look into it later.

**Comment by clayjohn** [comment] 2024-10-05 17:15
There were some changes recently, but they only take effect when using TAA/FSR2.2. I don't think that is what we are seeing here

**Comment by Calinou** [comment] 2024-10-17 12:28
I can't reproduce this in 4.4.dev 04692d83c (Linux, GeForce RTX 4090 with NVIDIA 560.35.03):

![image](https://github.com/user-attachments/assets/4d2ccb9b-d892-4bf3-b5e3-cb200b580585)

**Comment by Calinou** [comment] 2024-10-26 13:06
I've finally found out the cause: it only breaks when the shadow filter quality is set to High or Ultra. This affects both Forward+ and Mobile.

**Comment by DarioSamo** [comment] 2024-10-28 12:05
> I've finally found out the cause: it only breaks when the shadow filter quality is set to High or Ultra.

Do you happen to know off the top of your head if these qualities correspond to a sample count >= 16? Perhaps it just needs a little expansion of the bits available to the sample count in the new specialization constants structure.

**Comment by DarioSamo** [comment] 2024-10-28 13:30
Should be fixed by https://github.com/godotengine/godot/pull/98614, please let me know if it works.

**Closed** 2024-10-28 22:17 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:3d
