### ISSUE TITLE
Constants are Not Constant

### ISSUE THREAD

**Issue by verbalshadow** [godotengine/godot#15200] opened 2017-12-30 19:37 UTC
**Godot version:**
http://godot3builds.digitecnology.com/
2017-12-30.12:57:13.99960d929
Git commit id (short): 99960d929 

**OS/device including version:**
Arch Linux 64bit

**Issue description:**
When you have const variable it is still changable.

**Steps to reproduce:**
```
extends Node

const love = 9

func _ready():
	love += 1
	print (love)
```
**Minimal reproduction project:**
[const_bug.zip](https://github.com/godotengine/godot/files/1594705/const_bug.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment] 2017-12-30 20:40
Duplicate of #6221.

**Closed by vnen** 2017-12-30 20:40 UTC
Labels: bug, topic:gdscript
