### ISSUE TITLE
4.0: using CharacterBody3D with collisions from "Single convex collision sibling" of a capsule mesh causes horrible performance

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#66354] opened 2022-09-24 13:40 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

Arch Linux

### Issue description

Using Simplified or Multiple works fine, but Single is just straight chaos. It takes seconds for the splash screen to disappear and even then the performance is in the seconds-per-frame range.

### Steps to reproduce

1. Set up a scene with a simple floor with trimesh static body
1. Create a CharacterBody3D and put the template script on it for the sake of simplicity
2. Put a capsule mesh on the character and create single convex collision sibling
3. Start the scene

### Minimal reproduction project

[CharacterBody3D Problem.zip](https://github.com/godotengine/godot/files/9638809/CharacterBody3D.Problem.zip)

**Comment by Calinou** [comment] 2022-09-24 14:37
Duplicate of https://github.com/godotengine/godot/issues/48587 (same cause).

**Closed by Calinou** 2022-09-24 14:37 UTC
