### ISSUE TITLE
AnimationPlayer sometimes not showing animations in editor

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#63911] opened 2022-08-04 15:03 UTC
### Godot version

3.5 rc8, 4.0 alpha 13

### System information

Windows 11

### Issue description

Sometimes when clicking on an `AnimationPlayer` node the animation list in the bottom panel of the editor is empty (still visible in the inspector dropdown though). Usually the panel opens automatically when clicking on an animation player node, but with this bug it's not even opening. Animations play when starting the game, they just don't show up in the editor. You also can't click on any buttons, as all of them are disabled (see screenshot below).

![image](https://user-images.githubusercontent.com/8750135/182879736-53febe9b-d1fe-440d-b159-172656698c8e.png)

The animations have been created in Godot, not Blender or something else.

### Steps to reproduce

1. Close all scenes and the AnimationPlayer panel at the bottom
2. Open a scene with an AnimationPlayer and a script attached to the root
3. Open the script
4. Click on the AnimationPlayer -> nothing happens
5. Go into 2D/3D view -> nothing shows up. Clicking on the player again also does nothing
6. Switch to annother node and then back to the player -> now the animations show up in the panel

**Comment by TokageItLab** [comment] 2022-08-04 16:10
Can you confirm this in also 4.0?

**Comment by mbrlabs** [comment] 2022-08-04 16:41
Alright, i know why it happens. It's not as bad as i thought it is but it's still a bit annoying.

It only happens when you are in script mode, then select the AnimationPlayer -> empty panel. Switching to the 3D/2D viewport also does not show it. You have to select annother node and then select the Player again. This happens in 3.5 rc8 and master.

Maybe related to #63344.

**Comment by mbrlabs** [comment] 2022-08-04 16:44
I updated my original post with reproduction steps

**Comment by akien-mga** [comment] 2022-08-04 17:18
Duplicate of https://github.com/godotengine/godot/issues/63621.

**Closed by akien-mga** 2022-08-04 17:18 UTC
Labels: bug, topic:editor, topic:animation
