### ISSUE TITLE
DirectionalLight create cropped shadow for Sprite3D close to the sprite

### ISSUE THREAD

**Issue by Nymzer** [godotengine/godot#53320] opened 2021-10-01 20:58 UTC
### Godot version

3.3.4 stable

### System information

GLES3 and GLES2

### Issue description

DirectionalLight create cropped shadow for Sprite3D close to the sprite.

OmniLight and SpotLight create proper shadow.

### Steps to reproduce

With a simple light setup with shadow enabled, the issue seem to be only with DirectionalLight. The issue occur even with the light shadow bias property set to 0.

To enable the shadow with alpha transparency on the Sprite3D, we need to go in section Flags the property "Alpha Cut" and select the option "Opaque Pre-Pass". The issue occur with all Flags "Billboard" options selected.

![DirectionalLight create cropped shadow for Sprite3D](https://user-images.githubusercontent.com/91755299/135685290-d4879b54-9c11-4dde-a1c8-93cce08e9533.png)

![DirectionalLight create cropped shadow for Sprite3D (2)](https://user-images.githubusercontent.com/91755299/135685309-2c8fb063-f544-470d-a2de-1b6904a6dfea.png)

### Minimal reproduction project

[DirectionalLight_Sprite3D_Shadow_cropped_bug.zip](https://github.com/godotengine/godot/files/7270110/DirectionalLight_Sprite3D_Shadow_cropped_bug.zip)

**Comment by clayjohn** [comment] 2021-10-01 21:06
This is likely some combination of settings. Try fiddling with bias, shadow range, and normal bias and see if you can get something a little bit better.

**Comment by Calinou** [comment] 2021-10-01 21:39
This is likely due to shadow peter-panning caused by the bias values being too high. Try adjusting the DirectionalLight's shadow bias and normal bias values, but note that you won't get a "perfect" result no matter what you do
.

This is fixed in 4.0 thanks to the introduction of shadow normal offset bias and shadow pancaking.

**Closed by Calinou** 2021-10-01 21:39 UTC
Labels: discussion, topic:rendering

**Comment by Nymzer** [comment] 2021-10-01 21:41
DirectionalLight doesn't have a shadow range. I tried a negative bias of -0.2, I can get something that look better, however if I rotate the light, the bias value doesn't work anymore. If I play with the "Contact" value for the shadow the result I get doesn't look good.

I even tried to create a duplicate Sprite3D only to cast the shadow as suggested on the page below. However having a separate Sprite3D only to cast the shadow from a different position doesn't work once the camera move.
Y-Billboard Sprite3D does not cast shadows : https://github.com/godotengine/godot/issues/27738

**Comment by Calinou** [comment] 2021-10-01 21:51
> DirectionalLight doesn't have a shadow range.

There's a Max Distance property under the Directional Shadow section:

![image](https://user-images.githubusercontent.com/180032/135690030-3b21a168-f761-4363-9df0-6ce9f9511e24.png)

**Comment by Nymzer** [comment] 2021-10-01 22:03
Thanks, that I played with the Directional Shadow settings. It didn't removed completely the cropped shadow, however now the space between the shadow and the Sprite3D is smaller and it look much better.
