### ISSUE TITLE
open many script files make the Editor's UI messy

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#29534] opened 2019-06-06 09:50 UTC
**Godot version:**
Godot 3.1.1

**OS/device including version:**
Windows 7 x64bit
i7 4970k
8 GB Ram
Nvidia GTX 980

**Issue description:**
open many script files in Godot make the Editor's UI messy , open about 45 or more ?
see this video please .. it's a little bit long 
https://youtu.be/9rT4G7sTSbo

also i forget to mention .. open less than 40 or 35 script file in Godot is fine , but more will break the UI

**Steps to reproduce:**
open many scripts files as you can , maybe about 45 or more , restart the Engine , reopen the project

**Comment by qarmin** [comment] 2019-06-06 09:59
As a workaround you should increase Message Queue size in project settings to 4096 Kb or more
![Zrzut ekranu z 2019-06-06 11-57-44](https://user-images.githubusercontent.com/41945903/59024607-87e2e300-8852-11e9-862f-c5f11e4c849c.png)

**Comment by owstetra** [comment] 2019-06-06 10:04
@qarmin will do , Thank you <3
but in the next build could you make it by default ? so no one run into this error again ?

**Comment by akien-mga** [comment] 2019-09-25 13:56
Duplicate of #17693.

**Closed by akien-mga** 2019-09-25 13:56 UTC
Labels: bug, topic:editor
