### ISSUE TITLE
Last character of node's name missing during the edit

### ISSUE THREAD

**Issue by realgdman** [godotengine/godot#61069] opened 2022-05-15 23:53 UTC
### Godot version

4.0.alpha8.official [cc3ed63af]

### System information

Windows 10, Vulkan, Nvidia Geforce 750Ti (30.0.15.1165)

### Issue description

While editing of long (or nested) node names, probably those trimmed with ellipsis ..., last character is replaced with empty space.
Note on screenshot, last 0 is missing, but present in tooltip, but there is some empty character selected at the line end.
This is visual only, character returns when you finish edit.

Not sure what control used to render node tree, guess its Tree with TreeItems.

![image](https://user-images.githubusercontent.com/83962805/168498873-ef2af7a7-f02f-46e6-99b4-de5aa171d1c4.png)

### Steps to reproduce

1. Create any node
2. Give that node long name, or resize nodetree panel, so name is trimmed with ...
3. Try to edit that node name
4. Observe that is space shown instead of last character

**Comment by Calinou** [comment] 2022-05-16 01:54
I think this is a duplicate of another issue (which happens in all LineEdit nodes, and only on `master`), but I can't find it right now.

**Comment by iwek7** [comment] 2022-11-15 17:25
I think it works correctly as of beta 4.

**Closed** 2022-11-15 19:40 UTC
Labels: bug, confirmed, regression, topic:gui
