### ISSUE TITLE
Some errors don't show proper details in debug console

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15885] opened 2018-01-20 12:39 UTC
**Godot version:**
`master` / eb9fa02fbdfe59f8012979f137447dd8026f33b5

**OS/device including version:**
_Manjaro Linux 17.1.1_

**Issue description:**
In a C# project, some error messages do not show proper details in the editor console, while more relevant information can be read in the terminal, if Godot is launched from there.

For example, below shows how Godot displays two different errors in the editor console:
![godot-error-console](https://user-images.githubusercontent.com/2367032/35183461-141b4d08-fe2a-11e7-93c5-6b7a37cb6be7.png)

On the other hand, below shows what was logged in the terminal when the same errors occur:
```
ERROR: add_child: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.
   At: scene/main/node.cpp:1336.
ERROR: add_child: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.
   At: scene/main/node.cpp:1336.
Node has been detached from parent, or already disposed.
  at AlleyCat.Common.DisposableCollector.Add (System.IDisposable disposable) [0x00021] in /home/fender/workspace/AlleyCat/Program/AlleyCat/Common/DisposableCollector.cs:19 
  at AlleyCat.Common.DisposableExtensions.AddTo (System.IDisposable disposable, Godot.Node node) [0x00025] in /home/fender/workspace/AlleyCat/Program/AlleyCat/Common/DisposableExtensions.cs:15 
  at AlleyCat.UI.Console.Console.OnInitialize () [0x00019] in /home/fender/workspace/AlleyCat/Program/AlleyCat/UI/Console/Console.cs:68 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /home/fender/.cache/pacaur/mono-nightly/src/mono-5.9.0.375/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
```

**Steps to reproduce:**
I encountered the problem when I tried to add a child node to the parent from another of its children inside its `_EnterTree()` callback, which apparently seems to be not allowed.

**Comment by akien-mga** [comment] 2019-11-26 14:03
It's likely not Mono-related but a duplicate of #32276, which was fixed by #33517.

**Closed by akien-mga** 2019-11-26 14:03 UTC
Labels: bug, topic:mono
