### ISSUE TITLE
scons using /bin/g++ or /usr/bin/g++ rather than primary g++ found in PATH

### ISSUE THREAD

**Issue by omenos** [godotengine/godot#34533] opened 2019-12-22 06:10 UTC
**Godot version:** 3.1.2 (official xz tarball)

**OS/device including version:** RHEL 7 (build container), RHEL 8 host

**Issue description:**

Fair warning, compiler details are not my forte. I've also shared this with Red Hat to eek out any extra information I can to get to the root of this issue (whether GCC, Godot, or RHEL in general). I strongly believe this to be a RHEL issue, but posting here for any extra thoughts on the matter or to potentially help those running into similar issues. This issue does not appear on Fedora or RHEL 8, even when using `gcc-toolset-9` (a DTS) on RHEL 8. Using the base GCC on RHEL 7 also doesn't exhibit this issue as it (4.8.5) doesn't meet the required conditions.

The Developer Toolsets provided by Red Hat seem to have an issue with some of the enforced flags used in the build process, namely the following sections:

https://github.com/godotengine/godot/blob/0587df4aa5f2977350cc80b1522cdc1e483c4515/SConstruct#L343-L364

https://github.com/godotengine/godot/blob/0587df4aa5f2977350cc80b1522cdc1e483c4515/platform/x11/detect.py#L159-L163

Using DTS 9.1 (or 7+), which provides `gcc` and `g++` 9.1.1, running a build of the editor (such as the following) will fail immediately with the following error:

```bash
$ scons-3 platform=x11 tools=yes deprecated=no bits=64 target=release_debug
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/x11/godot_x11.cpp
g++: error: unrecognized command line option '-Wshadow-local'
scons: *** [platform/x11/godot_x11.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

The two lines to note:
```
Checking for C header file mntent.h... (cached) no
g++: error: unrecognized command line option '-Wshadow-local'
```

When commenting out L343-L346 in SConstruct, the build will progress just fine (with one caveat coming up), and the `mntent.h` header file becomes found again. But, just before the build finishes, the linking of the final executable fails with:

```
g++: error: unrecognized command line option '-no-pie'
```

Adjusting the LINKFLAGS in `detect.py` to `env.Append(LINKFLAGS=['-fpie']` solves this issue.

Modified editor build on RHEL 7 (`devtoolset-9`):
```
godot.x11.opt.tools.x64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=56426a38b300fdfdcee9b592b187e5d4e49d0eb9, not stripped
```

Standard build on RHEL 8 (`gcc-toolset-9`):
```
godot.x11.opt.tools.64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=31018dd69b3e23636af8fca371cc9efc95520dc7, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Using the RHEL 7 build on RHEL 8 seems to work fine though, but I haven't gone too far into testing yet.

**Steps to reproduce:**

I have been doing this in a RHEL 7 container (registry.redhat.io/ubi7/ubi:latest), but modified instructions for CentOS (docker.io/centos:7) are provided:

```bash
# Install dependencies and build tools < RHEL
yum -y update
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum-config-manager --enable rhel-7-server-optional-rpms --enable rhel-server-rhscl-7-rpms
yum -y install python3 python36-scons pkgconfig libX11-devel libXcursor-devel libXinerama-devel libXi-devel libXrandr-devel mesa-libGL-devel mesa-libGLU-devel mesa-libEGL-devel mesa-libGLw-devel alsa-lib-devel pulseaudio-libs-devel xz devtoolset-9*

# Install dependencies and build tools < CentOS
# Substituting DTS 8 for DTS 9 as it is not available yet
yum -y update
yum -y install epel-release centos-release-scl
yum -y install python3 python36-scons pkgconfig libX11-devel libXcursor-devel libXinerama-devel libXi-devel libXrandr-devel mesa-libGL-devel mesa-libGLU-devel mesa-libEGL-devel mesa-libGLw-devel alsa-lib-devel pulseaudio-libs-devel xz devtoolset-8*

# Retrieve Source
curl -L -O https://downloads.tuxfamily.org/godotengine/3.1.2/godot-3.1.2-stable.tar.xz
tar xf godot-3.1.2-stable.tar.xz
cd godot-3.1.2-stable

# Build
source /opt/rh/devtoolset-9/enable
scons-3 platform=x11 bits=64 target=release_debug tools=yes
```

**Final Notes:**

Again, I just want to say I don't think this is an issue for the Godot team to have to worry about. I'm pretty much convinced this is a RHEL issue with the way the DTS (which isn't a standard GCC build) handles things. Waiting to here back from Red Hat on that.

**Comment by omenos** [comment] 2020-01-14 21:39
Just following up, I got some more info and a pointer from Red Hat. This is not an issue with the Red Hat tools, but with how scons is setting up the path to GCC. I don't know specifically how, as I'm not a scons user at all, but it appears that it is finding the correct GCC binaries to check for the version, but then using the /usr/bin/gcc binaries instead which do not share the same version and feature set.

https://bugzilla.redhat.com/show_bug.cgi?id=1785894

Going to rename the title of this issue to reflect this.

**Comment by akien-mga** [comment] 2020-01-14 22:08
You can probably work it around with `scons-3 platform=x11 tools=yes deprecated=no bits=64 target=release_debug CXX=$CXX CC=$CC` (check that `CXX` and `CC` are properly defined by DTS, but given the version check that passes for GCC 9, it seems to be).

**Comment by omenos** [comment] 2020-01-14 22:54
The SCL's define themselves through an `enable` script found at /opt/rh/devtoolset-X/enable. For devtoolset-9, that's as follows:

```
# General environment variables
export PATH=/opt/rh/devtoolset-9/root/usr/bin${PATH:+:${PATH}}
export MANPATH=/opt/rh/devtoolset-9/root/usr/share/man:${MANPATH}
export INFOPATH=/opt/rh/devtoolset-9/root/usr/share/info${INFOPATH:+:${INFOPATH}}
export PCP_DIR=/opt/rh/devtoolset-9/root
# bz847911 workaround:
# we need to evaluate rpm's installed run-time % { _libdir }, not rpmbuild time
# or else /etc/ld.so.conf.d files?
rpmlibdir=$(rpm --eval "%{_libdir}")
# bz1017604: On 64-bit hosts, we should include also the 32-bit library path.
if [ "$rpmlibdir" != "${rpmlibdir/lib64/}" ]; then
  rpmlibdir32=":/opt/rh/devtoolset-9/root${rpmlibdir/lib64/lib}"
fi
export LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root$rpmlibdir$rpmlibdir32${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root$rpmlibdir$rpmlibdir32:/opt/rh/devtoolset-9/root$rpmlibdir/dyninst$rpmlibdir32/dyninst${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export PKG_CONFIG_PATH=/opt/rh/devtoolset-9/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
```
So `CC` and `CXX` aren't being defined up front. Using the following does work as expected, however using $(which gXX) in place of the full path does not work as the SCL environment hasn't been activated yet, so it'll use the system compiler:

```
$ scl enable devtoolset-9 "scons-3 platform=x11 tools=yes deprecated=no bits=64 target release_debug CXX=/opt/rh/devtoolset-9/root/usr/bin/g++ CC=/opt/rh/devtoolset-9/root/usr/bin/gcc
```

I find it interesting that it appears to be finding the correct GCC to version check with (as it is the first found binaries in the PATH), but doesn't use the same binaries paths to compile with.

**Comment by KoBeWi** [comment] 2020-12-01 23:13
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by omenos** [comment] 2020-12-02 01:33
Gave this a quick spin in a RHEL 7.9 container with Godot 3.2.3 (SCons 3.1.2, devtoolset-[9,10] for gcc/g++ 9,10), the problem still exists. Setting the CC/CXX environment variables manually is required otherwise SCons will choose to use the binaries in `/usr/bin` for compiling, regardless if those binaries were the ones found in PATH as part of its search.

I don't know if this is a SCons issue that is solved in 4.x, or an issue with the way Godot is implementing SCons. That being said, there's a simple enough workaround and I don't know if RHEL/CentOS 7 makes up a large enough demographic of Godot consumers to be worth the trouble of investigating, it's in a pretty niche situation with it's native compiler toolchains.

**Comment by akien-mga** [comment] 2024-05-11 13:28
I believe we've fixed this issue years ago, but forgot to update here. I don't have time right now to dig through the Git history and try to assess if/when this was solved, so I'll close the issue assuming it's indeed fixed (I haven't run into it in years, despite being able to reproduce it back in 2020).

Let us know if you still manage to reproduce this issue in either `master` or `3.x` branches.

**Closed by akien-mga** 2024-05-11 13:28 UTC
Labels: bug, platform:linuxbsd, topic:buildsystem, confirmed
