### ISSUE TITLE
GODOT 4.1.1 Simple 3d gridmap causes some gaps during movement/ on certain cordinates

### ISSUE THREAD

**Issue by atsd34** [godotengine/godot#82787] opened 2023-10-04 13:10 UTC
### Godot version

Godot_v4.1.1-stable_mono_win64

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

On a simple character movement+ 3d grid with repeating tiles; there are some weird black lines during movement. 

When character moves sometimes black/gray/white (depending on setup) lines appear when you slightly move it disappears again.
![image](https://github.com/godotengine/godot/assets/37181550/2d87b50f-cca5-4da2-9f1e-892f0282948b)

### Steps to reproduce

1- Create a 3d scene
2- add gridmap 
 I have tried grid size as 1, 0.99, 0.9,0.5 nothing works
3- fill with same tile
4- add a character
5- during run

### Minimal reproduction project

[bleed.zip](https://github.com/godotengine/godot/files/12803681/bleed.zip)

**Comment by bitsawer** [comment] 2023-10-04 13:37
Thanks for the report. Looks like a duplicate of https://github.com/godotengine/godot/issues/16337, https://github.com/godotengine/godot/issues/79081 and https://github.com/godotengine/godot/issues/35067 (issues apply to Godot 4.x too). It's not really a bug with GridMap, it's a fundamental problem when rendering almost overlapping surfaces. Linked issues discuss several options and workarounds that might work for you.

**Closed by bitsawer** 2023-10-04 13:37 UTC
