### ISSUE TITLE
MultiplayerSpawner errors when spawning node with SubViewport

### ISSUE THREAD

**Issue by soft-circles** [godotengine/godot#72939] opened 2023-02-09 03:24 UTC
### Godot version

4.0.rc1

### System information

MacOS Ventura 13.1, AMD Radeon Pro 5300M, Intel UHD Graphics 630, Rendering backend: Vulkan

### Issue description

When spawning a scene that contains a SubViewport within its hierarchy via a MultiplayerSpawner with a custom spawn function set via `set_spawn_function(<Callable>)`, Godot will produce an error:

`Node not found: "SubViewport" (relative to "Sprite3D").`
`ViewportTexture: Path to node is invalid.` 

The texture still gets rendered out to whatever is trying to capture the SubViewport's texture (in this case a Sprite3D) but I don't expect to see an error here because the scene hierarchy is correct even in the Remote view.

### Steps to reproduce

1. Run the project
2. Notice in the Debugger the two errors that appear

`main.gd` Attached to the root node in the main scene calls `.spawn()` on the `MultiplayerSpawner` node. Which has `subviewport_scene.tscn` as the only element in it's `Auto Spawn List`.

In `subviewport_scene.tscn` There is a `Sprite3D` with a `SubViewport` as it's child. The child of the `SubViewport` is a full screen `ColorRect`.

### Minimal reproduction project

[spawner_error.zip](https://github.com/godotengine/godot/files/10693238/spawner_error.zip)

**Comment by clayjohn** [comment] 2023-02-28 18:53
Duplicate of https://github.com/godotengine/godot/issues/27790

**Closed by clayjohn** 2023-02-28 18:53 UTC
