### ISSUE TITLE
Joystick buttons closing or restart game

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#17355] opened 2018-03-08 00:30 UTC
Hi there,

In project Input joystick is mapped to axis directions axis and button R1.
When i press down A joystick button it closes the game, if i press B button joystick it restarts the game.
Why those work when they are not mapped ?

**Comment by vonflyhighace2** [comment] 2018-03-09 06:02
there are a number of reason this could be. Are you running the project from the startup project list manager? thats a known issue.

**Comment by akien-mga** [comment] 2018-08-14 14:48
Duplicate of #15199.

**Closed by akien-mga** 2018-08-14 14:48 UTC
Labels: bug, discussion, topic:core
