### ISSUE TITLE
Closing a floating panel will name it incorrectly

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#44284] opened 2020-12-11 03:31 UTC
**Godot version:** Godot Engine v4.0.dev.custom_build.2fa910e03

**OS/device including version:**
Win 64 Nvidea

**Issue description:**
Closing the panel will make it dock again, however the tab name of the panel will be the name of the remaining panel, effectively swapping names.

So if you "Make floating" the Scene panel and then close it, the Import Panel will be named "Scene" and the Scene panel will be named "Import".

![image](https://user-images.githubusercontent.com/47016402/101858350-ba694c80-3b69-11eb-900b-1774e4231704.png)

**Steps to reproduce:**

I click on the three vertical buttons next to the "Scene" panel to "Make floating".
Then close the panel to make it docking again

**Comment by EricEzaM** [comment] 2020-12-12 05:35
I have noticed that if you then click and drag, in this case "scene" to "import", they will swap around and it will be correct again.

Also notice that the text does not fit properly. Do this with the Node and Inspector docks and it is even more obvious.

![tKhAauWaGS](https://user-images.githubusercontent.com/41730826/101976295-a1f35200-3c8f-11eb-8656-5e99ef350690.gif)

**Comment by akien-mga** [comment] 2020-12-12 15:17
There's #44321 as duplicate of this, but it also shows that not only the editor but also in-game TabContainer is affected, so I'll close this in favor of #44321.

**Closed by akien-mga** 2020-12-12 15:17 UTC
Labels: bug, topic:editor
