### ISSUE TITLE
int number will change to a real number when [for i in range(10):]

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#8781] opened 2017-05-16 04:03 UTC
**Operating system or device - Godot version:**
master [76289b5]

**Issue description:**
range(int) will change to range(real) if it after for

**Steps to reproduce:**

```
var a = range(10)
for i in a:
  print(typeof(i))
```
print 2 -> is int number

but

```
for i in range(10):
  print(typeof(i))
```

print 3 ->is real number

**Comment by akien-mga** [comment] 2017-05-16 05:22
Duplicate of #8278.

**Closed by akien-mga** 2017-05-16 05:22 UTC
