### ISSUE TITLE
Moving files causes scene corruption.

### ISSUE THREAD

**Issue by rainerdeyke** [godotengine/godot#17585] opened 2018-03-17 15:41 UTC
**Godot version:**
201d2d7

**OS/device including version:**
Lubuntu 16.04 (x86_64).

**Issue description:**
Moving files corrupts scenes that depend on that file.

**Steps to reproduce:**
Start with the 3D platformer demo.  Create a new folder called "creatures".  Drag 'enemy.scn' into the new folder.  Drag 'enemy.gd' into the new folder.  This reliably causes an error message that 'enemy.scn' is truncated.

**Minimal reproduction project:**

[platformer_demo_corrupted.zip](https://github.com/godotengine/godot/files/1821805/platformer_demo_corrupted.zip)

**Comment by Noshyaar** [comment] 2018-03-17 16:11
Observations:
- dragging only the script file corrupts the scene
- only happens with binary format scene (.scn). I tried to do the same with .tscn but it didn't corrupt.

**Comment by rainerdeyke** [comment] 2018-03-18 06:45
I suspect that this problem is caused by line 1167 in core/io/resource_format_binary.cpp.  Short version: when renaming dependencies, 'ResourceFormatLoaderBinary::rename_dependencies' creates a new file with the latest file format version number, without actually updating the contents of the file to the latest version.  This creates a "mixed version" file that the engine is then unable to load.

**Comment by akien-mga** [comment] 2019-01-22 07:40
Seems fixed in the current master branch, at least I can't reproduce it with the steps outlined in the OP.

**Closed by akien-mga** 2019-01-22 07:40 UTC
Labels: bug, topic:editor
