### ISSUE TITLE
Rapid audio sample playing causes audio clicking.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#38848] opened 2020-05-19 07:26 UTC
**Godot version:**
8e91d2746d28d1f84f872ef535b55807e1ac3535 (3.2)

**OS/device including version:**
Win10 64-bit

![image](https://user-images.githubusercontent.com/13004169/82297219-02046d00-99bb-11ea-8c72-2df468b55f3c.png)

**Issue description:**
When playing a lot of samples there can be an audio clicking sound that randomly occurs.

**Steps to reproduce:**
Use the sample project below, and rapidly click the mouse around the window in a circular pattern to trigger different positional audio nodes.

Doing this rapidly on my system causes some kind of audio clicking noise.

**Minimal reproduction project:**
[Audio Playback Issue.zip](https://github.com/godotengine/godot/files/4648840/Audio.Playback.Issue.zip)

**Comment by Calinou** [comment] 2020-05-19 07:32
Duplicate of #22016.

**Closed by Calinou** 2020-05-19 07:32 UTC
