### ISSUE TITLE
[Mono] Exported List of enum values gives incorrect values when loaded

### ISSUE THREAD

**Issue by KamiGrave** [godotengine/godot#47419] opened 2021-03-27 19:49 UTC
**Godot version:**
v3.2.3 Mono (Stable)

**OS/device including version:**
Windows 10

**Issue description:**
Exported lists of enums give bad values once loaded. Editor and data files have the correct expected values, but once loaded are shown to be invalid. They appear to alternate between seemingly random values and 0.
This appears to be consistent over exported script variables and resources.

**Steps to reproduce:**
1. Create a scene with a Node with a CSharp script.
2. Within the script declare an enum called TestEnum, with values VALUE_0, VALUE_1, VALUE_2.
3. Within the class, create an exported property of a List<TestEnum>.
4. Within the class, in the _ready method, write a for loop and print statement to print the values of the list.
4. From the editor, increase the list size to ~6 and optionally, set the values.
5. Run the code, and observe that the values that are printed out are incorrect.

**Minimal reproduction project:**
Attached is a minimal reproduction project. It has a single scene with a single Node2D with script attached. The script loads a resource (containing exported enum list) and also contains an exported list filled with the same enum type
. It prints one list then the other when run. There are no visual elements to this project.
[EnumBug.zip](https://github.com/godotengine/godot/files/6216294/EnumBug.zip)

**Sample output**
 
Values from resource:
Value: 533223456
Value: 0
Value: 533223480
Value: 0
Values from member:
Value: 533220256
Value: 0
Value: 533220280
Value: 0
Value: 533220304
Value: 0

**Expected output**
Values from resource:
Value: 0
Value: 1
Value: 2
Value: 0
Values from member:
Value: 0
Value: 0
Value: 0
Value: 2
Value: 1
Value: 0

**Comment by Calinou** [comment] 2021-03-27 20:19
Duplicate of https://github.com/godotengine/godot/issues/42926.

**Closed by Calinou** 2021-03-27 20:19 UTC
Labels: bug, topic:editor, topic:mono

**Comment by KamiGrave** [comment] 2021-03-27 20:39
Believe it or not I did search before posting. Was looking specifically for lists though, which is maybe why I didn't find it.

Confirmed duplicate. Same issue.
