### ISSUE TITLE
Importing png assert Frezees Godot and Not Responding

### ISSUE THREAD

**Issue by sai0077** [godotengine/godot#73145] opened 2023-02-12 05:37 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, RTX 3060, Vulkan

### Issue description

When dropping png assert into Editor res:// folder makes godot4 rc1 not responding and editor freezes. After waiting for 20mins still not responding.

![image](https://user-images.githubusercontent.com/36237494/218294910-8498d375-eaac-4aad-85ce-61523babae6b.png)

### Steps to reproduce

step1: open New project in Godot4 rc1 
step2: drag and drop the png assert in the res:// folder 

### Minimal reproduction project

step1: open New project in Godot4 rc1 
step2: drag and drop the png assert in the res:// folder

**Comment by sai0077** [comment] 2023-02-12 05:42
Additional information: Render ->Forward+

**Comment by akien-mga** [comment] 2023-02-12 09:37
Duplicate of https://github.com/godotengine/godot/issues/53871

**Closed by akien-mga** 2023-02-12 09:37 UTC
