### ISSUE TITLE
Visual script: when drag and drop a node the output show an error

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#22222] opened 2018-09-18 16:18 UTC
**Godot version:**
v3.1.dev.calinou.e522baf

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script :when drag and drop a node (ex: Area2D) from scene tree or a property setter/getter from the inspector,or drag and drop function or variable , the output show this error :
 scene/gui/control.cpp:772 - Condition ' get_viewport()->gui_is_dragging() ' is true.

**Steps to produce:**
create new visual script >> drag and drop node/property/function/variable/

**Comment by ffaristocrat** [comment] 2018-09-19 03:36
Probably related to #21493?

**Comment by akien-mga** [comment] 2018-09-19 07:11
Duplicate of #21493.

**Closed by akien-mga** 2018-09-19 07:11 UTC
Labels: bug, topic:visualscript
