### ISSUE TITLE
Layout menu doesn't respect scaling

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28108] opened 2019-04-17 02:15 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
If a node has scaling other than 1 (say, 0.5) and you use Layout -> Center, it will place its top-left corner as if its scale was 1. You can see this since the node will be properly centered if you set its scale back to 1.

**Comment by volzhs** [comment] 2019-04-17 02:43
cc @groud

**Comment by KoBeWi** [comment] 2019-05-23 15:30
Duplicate of #19068

**Comment by groud** [comment] 2019-05-23 19:51
Indeed, closing as a duplicate

**Closed by groud** 2019-05-23 19:51 UTC
Labels: topic:editor, usability
