### ISSUE TITLE
Ghosting effect with pixel-art in bigger resolutions

### ISSUE THREAD

**Issue by Efromomr** [godotengine/godot#44098] opened 2020-12-04 22:27 UTC
**Godot version:**
 Godot Engine v3.2.3.stable.offical

**OS/device including version:**
 GLES3

**Issue description:**
My pixel sprites have a ghosting effect in motion in any resolution apart from 1280x720. It's especially well seen at low speeds. Changing stretch mode or aspect doesn't help (pixel snap and Vsync are on). I've found some old issues about making pixel-perfect camera but they don't help either. Base width and height are set to 320x180. Test size and width are set to 1280x720.

https://user-images.githubusercontent.com/8281454/103243029-c5124700-499b-11eb-812d-f42211fa4832.mp4

https://user-images.githubusercontent.com/8281454/103243033-c93e6480-499b-11eb-9ab9-0ae2cead2b3f.mp4

**Steps to reproduce:**
1. Apply 2d pixel filter to images.
2. Create a tilemap.
3. Add any moving object and attach camera to it.
4. Change game resolution. 

**Minimal reproduction project:**
 
[RPG.zip](https://github.com/godotengine/godot/files/5645842/RPG.zip)

_bug squad edit : attached mp4 files_

**Comment by Calinou** [comment] 2020-12-04 23:09
Can you take a screenshot or record a video?

This may be due to monitor ghosting, which is an hardware issue a game engine can't prevent.

**Comment by Efromomr** [comment] 2020-12-05 14:25
https://www.kapwing.com/videos/5fcb902c6f4246003d28797e
https://www.kapwing.com/videos/5fcb8f34df9dd100571ff681
I've made a recording but it looks jittery there, the game runs smoother in the editor. The effect is best seen in the MRP, which I attached. 

At first I thought that it was monitor ghosting but I checked that on different monitors and the problem persists. To tell the truth, I'm not sure that ghosting is a correct term to classify this strange ripple-like effect.

**Comment by Calinou** [comment] 2020-12-05 16:03
Can you try upgrading your project to 3.2.4beta3 and enable the new "snap transforms" option in the Project Settings? This may be a duplicate of https://github.com/godotengine/godot/issues/41491 which has been fixed recently.

**Comment by Efromomr** [comment] 2020-12-05 16:32
Unforunately, it didn't help. Also, diagonal moving is somehow jittery with transform snap on (player's "trembling").

**Comment by Efromomr** [comment] 2020-12-28 20:54
Have accidentally closed it, though the issue is still relevant. Have there been any improvements with transform snap since 3.2.4.beta4?

**Comment by Calinou** [comment] 2020-12-28 21:00
> Have there been any improvements with transform snap since 3.2.4.beta4?

Not that I know of.

**Comment by groud** [comment] 2021-05-24 12:09
Closing as this is likely fixed by #44690 now that it's merged.

**Closed by groud** 2021-05-24 12:09 UTC
Labels: topic:rendering
