### ISSUE TITLE
Engine Crash and gives OpenGL issue

### ISSUE THREAD

**Issue by Itslossless** [godotengine/godot#68166] opened 2022-11-02 12:52 UTC
### Godot version

3.5.1-stable

### System information

Windows 11 21H2, Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz, 16.0 GB, NVIDIA Geforce MX330 version 31.0.15.2225, GLES2 GLES3

### Issue description

The engine crash all the time, and if I don't use the engine for a few minutes it will crash, after the crash, I try to reopen it and I get the next message: "Your video card driver does not support any of the supported OpenGL versions".

I need to restart the PC to open again the engine and then again after a few minutes the same crash append.

### Steps to reproduce

1. Open any project
2. wait a few minutes

### Minimal reproduction project

[3D Road.zip](https://github.com/godotengine/godot/files/9920445/3D.Road.zip)

**Comment by clayjohn** [comment] 2022-11-02 16:40
This sounds like a duplicate of https://github.com/godotengine/godot/issues/67887 which was caused by faulty drivers. 

Can you try updating / rolling back your drivers to see if it fixes the issue?

**Comment by AThousandShips** [comment] 2024-07-29 17:21
Closing due to lack of response, if you provide the requested information this can be reopened

**Closed by AThousandShips** 2024-07-29 17:21 UTC
Labels: documentation, needs testing
