### ISSUE TITLE
Mono: Performance degradation, memory leaks and unsafe reference errors when using Resource.Duplicate

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#35450] opened 2020-01-22 20:49 UTC
**Godot version:**
3.2 RC2

**OS/device including version:**
MXLinux19 64bits

**Issue description:**
Duplicating resources causes the game to slow down over time and if the resources aren't preloaded unsafe reference errors might show up in the debug tab of the editor.

**Steps to reproduce:**
Get the MRP and compare the scenes Test.tscn to SameButGDScript.tscn, the gdscript version doesn't have performance degradation and the game runs a bit faster(probably due to C#'s garbage collection).

If you change the exported variable "preload_resources" to false in Test.tscn you might get unsafe reference errors.

**Minimal reproduction project:**
[RandomError.zip](https://github.com/godotengine/godot/files/4099848/RandomError.zip)

**Comment by MightyPrinny** [comment] 2020-01-22 22:51
Performance doesn't seem to degrade in release builds, only in the editor, and the memory usage of the game never decreases when it runs from the editor, in release builds memory usage seems normal.

**Comment by MightyPrinny** [comment] 2020-01-22 22:56
In release builds when I close the game and the resources aren't preloaded the game prints this:

ERROR: _unload_scripts_domain: Mono: Domain finalization timeout.
   At: modules/mono/mono_gd/gd_mono.cpp:1020.

**Comment by MightyPrinny** [comment] 2020-01-22 23:10
memory usage in a release build of the gdscript version stays at 87 mb

**Comment by neikeq** [comment] 2020-01-23 21:47
Memory is not leaked. It's just not being GCed yet.
Also keep in mind there are more static objects in the C# one because this is not merged yet: #34275. But that doesn't seem to have much impact on performance in this case.

I'll have to investigate more if the performance degradation is because of the GC being stressed or something else.

**Comment by MightyPrinny** [comment] 2020-01-23 22:21
weird, in a project I'm working on memory usage is more stable, here it goes up and it does 't decrease much when gc happens, in my project(where I avoid using Duplicate) memory usage decreases way more after gc happens.

**Comment by MightyPrinny** [comment] 2020-01-23 22:30
Btw I'm talking about the memory used by the game process.

**Comment by MightyPrinny** [comment] 2020-01-23 23:05
There's definitely a memory leak, at least before your PR, I've left the game running for about 25 minutes and the process is using 334mb and it keeps increasing.

**Comment by MightyPrinny** [comment] 2020-01-24 09:50
In RC3 memory no longer leaks in release builds.

**Comment by neikeq** [comment] 2020-01-24 17:34
I will have a second look tomorrow to see if I can reproduce the memory leak.

**Comment by KoBeWi** [comment] 2020-12-17 00:35
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by raulsntos** [comment] 2023-02-26 03:27
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

**Closed by raulsntos** 2023-02-26 03:27 UTC
Labels: bug, topic:dotnet
