### ISSUE TITLE
Godot 3.1 Beta 4 - simply disappeared the 3d view

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#25824] opened 2019-02-12 15:07 UTC
**Godot version:**
3.1 beta 4

**OS/device including version:**
windows 64

**Issue description:**
3d view disappeared 

**Steps to reproduce:**
only open my project in beta 3

![godot erro beta4](https://user-images.githubusercontent.com/39173940/52645044-2247a100-2ec7-11e9-9dd9-63e18e4da8ed.png)

**Comment by Zireael07** [comment] 2019-02-12 15:13
duplicate of #25804?

**Comment by giovanigsilva** [comment] 2019-02-12 15:22
> duplicate of #25804?

yes, sorry

**Closed** 2019-02-12 15:23 UTC
