### ISSUE TITLE
External Editor: Wraps each flag in quotes which negates switches

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16108] opened 2018-01-27 09:55 UTC
I am trying to configure Visual Studio with Godot 3.0 stable, and the way Godot reads the exec flags completely kills integration.

![Editor settings](https://i.gyazo.com/e536135b7bcf6294cf44ce420ed7ec8f.png)
becomes:
![Command line](https://i.gyazo.com/7461adae0285590981c0a0c6c3055838.png)

It is wrapping each "word" in quotes, which negates the functionality of Visual Studio's /edit command switch. As a result Visual Studio tries to read in "/edit" as a file instead of a command.

**Comment by 11clock** [comment] 2018-01-27 22:19
Similar issues with JetBrains Rider. It tries to read in "--line" as a file name rather than a command argument.

**Comment by nobuyukinyuu** [comment] 2018-02-15 04:44
This sounds like a dupe of #16335.

**Comment by akien-mga** [comment] 2018-02-15 09:21
Indeed, and thus fixed in the master branch (and will be fixed in 3.0.1).

**Closed by akien-mga** 2018-02-15 09:21 UTC
Labels: bug, topic:editor

**Comment by 11clock** [comment] 2018-02-15 17:39
I actually made this one first.

**Comment by nobuyukinyuu** [comment] 2018-02-15 19:44
@11clock My bad.
