### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3446] opened 2016-01-25 11:33 UTC
I've successfully compiled Godot from github source code. commit 87517c564b832
when I run the output I get:
$ ./godot.x11.tools.64
Segmentation fault (core dumped)

halp!
(using ubuntu gnome 15.04 64bits)

**Comment by akien-mga** [comment] 2016-01-25 11:59
Can you try running it through gdb so that there is more info about the crash?
Also, were you able to run earlier versions fine?

**Comment by lordadamson** [comment] 2016-01-25 12:08
No I wasn't able to run previous versions it gave me the same error. I'll try to debug and will update you.

**Comment by lordadamson** [comment] 2016-01-25 14:54
Okay I switched machines and the bug no longer occurs so it does not affect me anymore.
but it did happen on the old machine it was a core dual machine by the way.

**Comment by akien-mga** [comment] 2016-01-25 14:58
It would still be quite interesting to get the output from gdb, you can run it as:
```gdb ./bin/godot.x11.tools.64```
Then ```run``` and after the crash ```bt``` to get the backtrace.

**Comment by lordadamson** [comment] 2016-01-25 15:08
I will as soon as I can. I'm in a challenge to create a game in 7 days now so I don't have that much time but I'll do it later today.

**Comment by bojidar-bg** [comment] 2016-01-27 10:38
BTW, it *might* be from old OpenGL or drivers version...

**Comment by bojidar-bg** [comment] 2016-01-27 10:45
Also, related to #67, #2067 and #977 (segmentation fault, linux)

**Comment by reduz** [comment] 2016-01-31 23:08
most likely OpenGL not supported

**Comment by akien-mga** [comment] 2016-02-01 11:07
Yeah, closing as a duplicate of #156.

**Closed by akien-mga** 2016-02-01 11:07 UTC
Labels: bug, platform:linux, topic:core

**Comment by lordadamson** [comment] 2016-02-01 22:16
Sorry I couldn't debug it guys. It wasn't my computer. it was a computer in a co-working space that I had access to for a limited amount of time.
