### ISSUE TITLE
Number knob stays in place when scrolling

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#73682] opened 2023-02-21 14:41 UTC
### Godot version

v4.0.rc.custom_build [7e79aead9]

### System information

Linux

### Issue description

[Screencast from 2023-02-21 15-40-00.webm](https://user-images.githubusercontent.com/28286961/220375262-ee7a9a36-595a-4559-8d0a-b6162f37ad6b.webm)

### Steps to reproduce

Open the inspector and scroll while hovering over a number field.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-02-21 16:06
Duplicate of https://github.com/godotengine/godot/issues/42497.

There's a proposed fix in a comment, maybe give it a try locally :slightly_smiling_face:

**Closed by Calinou** 2023-02-21 16:06 UTC
