### ISSUE TITLE
3.x to 4.0 Project Converter corrupts one of my scenes.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#74958] opened 2023-03-15 20:49 UTC
### Godot version

4.0

### System information

Windows 10, i7-8850h

### Issue description

A scene in my project named "Path Point.tscn" becomes unable to open when converting it to Godot 4.0 from 3.5.2.
The engine throws an alert which states `Scene file 'Path Point.tscn' appears to be invalid/corrupt.` upon attempting to open the scene.

I've tried isolating the scene and its dependencies to a project which causes the same issue but with different text within the alert: `Error while loading file 'Path Point.tscn'.`

---
Sidenote: does anyone know what's wrong with the scene file's code? I'd like to be able to use this scene without starting from scratch.

### Steps to reproduce

Import the project containing this scene (in the Minimal reproduction project) in Godot 4.0, select it and then press "Covert Full Project".
try opening the `Path Point.tscn` scene and see if it works.

### Minimal reproduction project

[Path Point Transfer.zip](https://github.com/godotengine/godot/files/10984342/Path.Point.Transfer.zip)

**Comment by gotnospirit** [comment] 2023-03-15 23:04
Paths and node names were converted.

```
[ext_resource path="res://Mesh-Path3D Point.tres" type="ArrayMesh" id=1]
[ext_resource path="res://Path3D Point/path point material.tres" type="Material" id=2]
[ext_resource path="res://Path3D Point.gd" type="Script" id=3]

...

[node name="Path3D Point" type="MultiMeshInstance3D"]
```

Duplicate of #66256

**Comment by KoBeWi** [comment] 2023-03-15 23:13
Closing as duplicate.

**Closed by KoBeWi** 2023-03-15 23:13 UTC
