### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build

### ISSUE THREAD

**Issue by rodrigofbm** [godotengine/godot#17287] opened 2018-03-05 21:29 UTC
**Godot 3.0.2 Mono Stable:**
**Ubuntu 16.04:**

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ERROR: add_item: Method/Function Failed.
   At: modules/mono/editor/csharp_project.cpp:118
```

When I create some C# script and debug it. Someone can helpe me?

**Comment by Zireael07** [comment] 2018-03-06 07:32
What is your Mono version?

**Comment by rodrigofbm** [comment] 2018-03-06 15:01
Mono 5.4.1.7

**Comment by bruvzg** [comment] 2018-03-06 15:35
Make sure you have `mono-complete` package installed, `mono-runtime` is not enough.

**Comment by DoYouRockBaby** [comment] 2019-01-20 12:51
Hi,

I'm trying to play with the new godot 3.1 beta.

Godot don't manage to create the C# project, it says that :
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

It's strange because i installed the microsoft build tool.
```

OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
Editing project: C:/Users/Léo/Documents/Test Godot (C:::Users::Léo::Documents::Test Godot)
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ERROR: generate_game_project: Method/Function Failed, returning: String()
   At: modules/mono/editor/csharp_project.cpp:103

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ERROR: add_item: Method/Function Failed.
   At: modules/mono/editor/csharp_project.cpp:127

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ERROR: generate_game_project: Method/Function Failed, returning: String()
   At: modules/mono/editor/csharp_project.cpp:103

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
ERROR: add_item: Method/Function Failed.
   At: modules/mono/editor/csharp_project.cpp:127
WARNING: _open: Case mismatch opening requested file 'code.CMD', stored as 'code.cmd' in the filesystem. This file will not open when exported to other case-sensitive platforms.
     At: drivers/windows/file_access_windows.cpp:104
```

![image](https://user-images.githubusercontent.com/16799566/51439438-68d82000-1cba-11e9-9417-9b3f62cf531e.png)

**Comment by exts** [comment] 2019-01-20 12:58
(cc: @neikeq @hpvb )

**Comment by aaronfranke** [comment] 2019-09-02 19:22
@rodrigofbm Can you still reproduce with Godot 3.1.1 and the latest Mono?

@DoYouRockBaby Have you tested with a user account that doesn't have accent marks in it? I have no idea if that is the problem or not, but that's something that stuck out to me looking at your post.

**Comment by rodrigofbm** [comment] 2019-10-12 17:05
@aaronfranke With Godot 3.1.1 and mono 6.4.0.198 it's working fine.

**Comment by akien-mga** [comment] 2019-10-12 17:56
Closing as fixed.

**Closed by akien-mga** 2019-10-12 17:56 UTC
Labels: bug, topic:mono
