### ISSUE TITLE
AnimationPlayer NodePath function arg grabs the wrong path

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#32114] opened 2019-09-13 04:28 UTC
**Godot version:**
3.2
**OS/device including version:**
ArcoLinux
**Issue description:**
Attempting to assign a node path to a function arg in an animation.  The value is wrong in all cases,  as it seems to try to grab the path from the position of a node higher in the hierarchy.  A unique case occurs when attempting to target the immediate parent, and I'm not entirely sure how it manages to arrive at the path it does.

![image](https://user-images.githubusercontent.com/28724859/64837433-0e2a6600-d5b4-11e9-9c45-e9149de9712b.png)

![image](https://user-images.githubusercontent.com/28724859/64837384-e20ee500-d5b3-11e9-941f-02423fb2e2b9.png)

![image](https://user-images.githubusercontent.com/28724859/64837429-01a60d80-d5b4-11e9-8d9a-8cb58dab0995.png)

This is the result of attempting to get the path of the immediate parent of the AnimationPlayer (Activator).  When selecting the AnimationPlayer, or another node at its level, it simply refers to its own name (where it should be something like ../AnimationPlayer or ../CollisionShape2D).  Attempting to reference the TextBox results in the path `AnimationPlayer/TextBox`.

As you might expect, these paths make no sense from the perspective of AnimationPlayer, and so they always fail to find a node.

![image](https://user-images.githubusercontent.com/28724859/64837519-82650980-d5b4-11e9-8f38-3bda9f87425f.png)

![image](https://user-images.githubusercontent.com/28724859/64837531-94df4300-d5b4-11e9-8f7e-82abfad2027c.png)

**Comment by KoBeWi** [comment] 2020-08-30 23:14
Fixed in 3.2 (the issue is from before stable)

**Closed by KoBeWi** 2020-08-30 23:14 UTC
Labels: bug, topic:core
