### ISSUE TITLE
Reparenting a node with modifiable children can loose changes made to children

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#29593] opened 2019-06-08 00:20 UTC
Godot 3.1
Windows 10 64 bits

I lost a material and some transform settings after reparenting a scene instance which had an edited child.

Repro:
1) Create scene A with two child nodes in it
2) Create scene B with a `Spatial` root and one `MeshInstance` as child
3) Instance scene B into scene A, under one of its child nodes, so you have this structure:
```
Root
- Child1
    - InstanceOfA
- Child2
```
4) Toggle `editable children` on the scene you just instanced, and add a new material to the `material_override` property of the mesh instance.
5) Drag `InstanceOfA` under another child node: notice children are not showing up as editable anymore, but the material will still be there if you check it again. However, for the purpose of this repro, *do not do it*.
6) Save the scene and close it
7) Reopen the scene, children are still not editable, *but if check again editable children*, the material is gone.

**Comment by sparkart** [comment] 2019-06-08 05:02
I guess the fix would be to keep the "editable children" option selected when you move the node. Since it appears that Godot is using the "editable children" option to determine whether it should save instance data or not.

Or perhaps, it would be better if the instance data remained regardless of the "editable children" option.

**Comment by bncastle** [comment] 2019-08-14 00:51
This bug also occurs when duplicating a node that has **child nodes** with editable children. The "editable children" setting of the children is not copied.
![EditableChildren](https://user-images.githubusercontent.com/1876691/62986996-e658ae80-be0b-11e9-865b-f8781e173b3e.gif)

**Comment by KoBeWi** [comment] 2020-08-27 00:02
Duplicate of #23979

**Closed by KoBeWi** 2020-08-27 00:02 UTC
Labels: bug, confirmed, topic:editor
