### ISSUE TITLE
iOS iPad - Gui not in the middle

### ISSUE THREAD

**Issue by NeroNekro** [godotengine/godot#54665] opened 2021-11-06 14:04 UTC
### Godot version

3.3

### System information

MacBook Air M1 16gb 512gb

### Issue description

Try to center the gui. Using CenterContainer and so on. Every time the GUI is not the middle of the screen and slightly on the left side. On the Macbook the Gui is on the middle of the screen.

### Steps to reproduce

Create a menu with a centercontainer and export iOS

**Comment by akien-mga** [comment] 2021-11-06 14:22
Please provide a minimal reproduction project and screenshots to show what the problem is.

**Comment by NeroNekro** [comment] 2021-11-15 12:31
> Please provide a minimal reproduction project and screenshots to show what the problem is.

i create a new project with the same settings and its work. Sry :)

**Comment by Calinou** [comment] 2021-11-15 12:34
Closing per the above comment.

**Closed by Calinou** 2021-11-15 12:34 UTC
Labels: bug, platform:ios, needs testing, topic:gui
