### ISSUE TITLE
Bezier curve editor selector on left is out of sync with the text

### ISSUE THREAD

**Issue by Wokarol** [godotengine/godot#57202] opened 2022-01-25 15:19 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

The selection that allows to choose the track to edit does not align with the labels in the slightest 

### Steps to reproduce

1. Create bezier track
2. Open the bezier editor

### Minimal reproduction project

![SelectionBroken](https://user-images.githubusercontent.com/38141841/151004891-e10c66b3-af3d-4f92-b031-b83a96c5fc87.png)

**Comment by Ansraer** [comment] 2022-01-25 15:21
I think this might be a duplicate of #53088.

**Closed** 2022-01-25 15:23 UTC
Labels: bug, topic:editor, topic:animation
