### ISSUE TITLE
Button "Action Mode" does not apply to pressing with keys/buttons

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22615] opened 2018-10-02 09:47 UTC
**Godot version:**
3.1-alpha 7aca38e

**OS/device including version:**
Linux Mint 19 Cinnamon x64

**Issue description:**
Button nodes have a property called "Action Mode", which specifies when a Button is considered "pressed" (either when the button is pushed down, or when it is released). However, when pressing a Button with a key/button assigned to `ui_accept` (Space, Enter, etc.) the Button will always be pressed on button release, regardless of what Action Mode is set.

**Minimal reproduction project:**
[button action mode bug.zip](https://github.com/godotengine/godot/files/2437358/button.action.mode.bug.zip) - This project contains one Button, with its Action Mode set to "Button Press". Click on it to confirm that its "pressed" signal does fire on button down, then try pressing the button by pressing Space/Enter.

**Comment by tom-jk** [comment] 2020-08-10 12:31
Testing MRP on linux mint 18.3

Can reproduce in 3.0 thru 3.1.2, including 3.1.alpha1
Can reproduce (and is broken for both keyboard and mouse) in 3.2.alpha0 thru 3.2.beta5
Can't reproduce in 3.2.beta6 thru 3.2.3.rc3

Issue appears to be resolved.

**Comment by Calinou** [comment] 2020-08-10 14:00
Closing as resolved per @tom-jk's comment.

**Closed by Calinou** 2020-08-10 14:00 UTC
Labels: bug, topic:core

**Comment by jbho** [comment] 2024-10-12 20:20
Has this issue returned in 4.4?  Seems like it.
