### ISSUE TITLE
@export_category conflicts with autoload singletons

### ISSUE THREAD

**Issue by Metalloriff** [godotengine/godot#82228] opened 2023-09-24 06:11 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3713) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

This isn't a massive issue, but caused a few hours of confusion for me.

I have an autoload singleton named "Network", and I'm accessing it in my player script. After organizing my code a bit with @export_category, I created a category named "Network", and was getting "Invalid get index 'blah' (on base: 'Nil')."

It seems that creating an export category creates some sort of nil variable that conflicts with singletons (or maybe existing variables in general).

### Steps to reproduce

1) Create an autoload singleton
2) On any scene, create a script
3) In that script, create an export category with the same title as the singleton name
4) Attempt to access the singleton

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-09-24 08:01
* Duplicate of #79861.
* Fixed by #78254 for future 4.2.
* Cherry-picked for future 4.1.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-09-24 08:01 UTC

**Comment by Metalloriff** [comment] 2023-09-24 17:14
> * Duplicate of [@export_category creates a variable that causes issues if another one has the same name #79861](https://github.com/godotengine/godot/issues/79861).
> 
>     * Fixed by [GDScript: Fix conflict between property and group names #78254](https://github.com/godotengine/godot/pull/78254) for future 4.2.
> 
>     * Cherry-picked for future 4.1.2.
> 
> 
> Thanks for reporting the bug nonetheless!

Sorry about that! It was late and I didn't think to check existing issues. My first time making an issue. I'll check beforehand in the future!

Thanks for the quick response
