### ISSUE TITLE
Black screen at editor startup (resizing the window doesn't do anything)

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8302] opened 2017-04-07 10:04 UTC
**Operating system or device - Godot version:**
Windows 10 - Godot 3.0 alpha

**Issue description:**
Duplicate of these issues #8148 #8174 #7888 then I saw this tweet by karroffel

> If the screen is black after startup try resizing the window. That's an upstream bug and will be fixed soon.

But now, even resizing the window doesn't do anything

**Comment by BE-NeverGames** [comment] 2017-04-08 15:26
I do encounter this problem as well unfortunately. It only happens with my own compiled version though, the latest master build from the Godot Builder works fine. 
What is the source of your version? Did you compile it yourself or, if not, where did you get it from?

**Comment by Shockblast** [comment] 2017-04-09 05:11
sorry my english.
The latest build of UNOFFICIAL GODOT ENGINE BUILDS (April 8, 2017 at 10:12) continues with "black screen" problem, now it only works when I drag the window while loading the project, if I do after the project loads Is always showing black, even if after I change the size of the window. (Win 10 x64 pro)

**Comment by BE-NeverGames** [comment] 2017-04-09 07:11
Do you mean the builds frovided by fixnum.org? In that case, I can confirm that the problem occurs with those as well. However, I also tried a build from the 6th of April and that one does work actually just like the latest build from the GodotBuilder. Since that one is also from the 6th I would assume that one of the commits after that caused something to break. I will see what I can find.

@Shockblast Could you try out the latest master build from https://github.com/GodotBuilder/godot-builds/releases so that we can confirm that the issue started after that?

**Comment by Ahmed0425** [comment] 2017-04-09 10:22
@BE-NeverGames @Shockblast I've built godot myself using mingw in debug mode ... I can also confirm that the problem started after the new particle system's release ...
I've tried the latest godot build from godot builder, resized the window after loading and works fine

**Comment by Shockblast** [comment] 2017-04-09 19:01
@BE-NeverGames 

On the master https://github.com/GodotBuilder/godot-builds/releases/tag/master_20170406b that continues with black screen problems, but is fixed by dragging the window from the maximized screen or "resizing the window"

The problem starting from the January 4 build (UNOFFICIAL GODOT ENGINE BUILDS January 4, 2017 at 03:38) since there were problems with the black screen.

**Comment by akien-mga** [comment] 2017-04-09 19:04
Bug confirmed on Windows and OSX.

@Faless bisected it, it started with 74808ac4d9176180dc7ecace99723edab8a73e0e. @reduz already had a look but couldn't understand what the issue is so far...

**Comment by akien-mga** [comment] 2017-04-09 21:13
Fixed by fccf281. Please comment if you can still reproduce that issue :)

**Closed by akien-mga** 2017-04-09 21:13 UTC
Labels: bug, confirmed, platform:osx, platform:windows, topic:rendering

**Comment by Shockblast** [comment] 2017-04-09 22:15
@Ahmed0425 
No, it's still happening.
![ss](https://cloud.githubusercontent.com/assets/5357217/24841344/d9d54f0c-1d58-11e7-90e2-2f9789903aa8.png)

**Comment by akien-mga** [comment] 2017-04-09 22:34
@Shockblast Even if you resize the window?

**Comment by Shockblast** [comment] 2017-04-09 22:40
@akien-mga In that case it works again.

**Comment by Ahmed0425** [comment] 2017-04-09 23:17
@akien-mga That seems to be a good bugfix ... because the driver's issue disappeared
Now the error appears in core\class_db.cpp & core\object.cpp only (txt file describes 3 errors in those 2 files)
[Godot 3.0.txt](https://github.com/godotengine/godot/files/908625/Godot.3.0.txt)

**Comment by Ahmed0425** [comment] 2017-04-10 00:07
godot works now with this commit https://github.com/godotengine/godot/commit/1c480698ce0e881cbd28f1f0ddba95cee74ca834
however, there are still some errors that need to be fixed as they might cause crashes
[3.0.txt](https://github.com/godotengine/godot/files/908659/3.0.txt)

**Comment by karroffel** [comment] 2017-04-10 00:28
@Ahmed0425 these errors don't cause crashes

**Comment by Ahmed0425** [comment] 2017-04-10 00:42
@karroffel indeed but godot crashes when I open 3D workspace view settings or open shaders ... seems to be a problem with 3D mode in general in godot engine (new txt file attached)
[New Text Document.txt](https://github.com/godotengine/godot/files/908694/New.Text.Document.txt)

**Comment by Shockblast** [comment] 2017-04-10 01:33
@Ahmed0425 
The maximized screen and the logo work very well ;) (in the beginning).
3D also works pretty well, exept for viewers that do not work but I think that's for another "issue".
In the shaders when I write there crashes the engine.

![ss](https://cloud.githubusercontent.com/assets/5357217/24842911/d008e4fa-1d73-11e7-9fe8-0cf684ec6e46.jpg)

**Comment by reduz** [comment] 2017-04-10 01:41
Ah that shader tab shouldnt be there.. must hide it
