### ISSUE TITLE
Add MIDI parsing capabilities to godot.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#29083] opened 2019-05-21 19:24 UTC
I know this may be requested, but I need godot to extend their MIDI support to being able to parse MIDI files.

https://www.youtube.com/watch?v=qmZMGb3N0KE
It will help me develop some software for blind musicians, like the girl in this video, who was unable to become a professional pianist because of a lack of braile scores.

My goal is to make some imitone + synthesia kind of hybrid, where I'll take the audio from some microphone and then output the note using some text to speech system to convert the MIDI note into speech instructions over what note or adorment the note has and wait until the player has input said note, similar to synthesia but I'll need to being able to parse the microphone audio in case the blind musician uses other instrument that isn't a MIDI keyboard.

**Comment by chiya-chan** [comment] 2019-05-21 19:51
Write it yourself you fucking idiot

**Comment by bruvzg** [comment] 2019-05-21 20:43
* MIDI I/O is supported.
* Microphone input is supported.
* MIDI playback is not supported (existing feature request issue: #12238).
* Unlikely parsing MIDI files without playback capabilities will be added to the engine, but you can parse MIDI files with GDScript or make a gdnative wrapper for third-party MIDI library.
* I have simple gdnative add-on for the text-to-speech support here: https://github.com/bruvzg/godot_tts (this implementation won't be ever integrated into the engine, due to licensing issues (depends on LGPL libs)).

**Comment by akien-mga** [comment] 2019-05-22 09:33
We had a Google Summer of Code project by @DanielMatarov for MIDI playback last year, the results of which can be found in https://github.com/DanielMatarov/Google-Summer-of-Code--Module-and-test-projects

I'm not sure what its current state is, but we should look into better integrating it and documenting its usage.

There's also a GDScript MIDI player at https://bitbucket.org/arlez80/godot-midi-player

**Comment by ca3games** [comment] 2019-05-27 04:28
> We had a Google Summer of Code project by @DanielMatarov for MIDI playback last year, the results of which can be found in https://github.com/DanielMatarov/Google-Summer-of-Code--Module-and-test-projects
> 
> I'm not sure what its current state is, but we should look into better integrating it and documenting its usage.
> 
> There's also a GDScript MIDI player at https://bitbucket.org/arlez80/godot-midi-player

https://www.youtube.com/watch?v=J1jm1qBoVCs

Made some test with such player, is right now kind of buggy and doesn't render properly the files.

**Comment by DanielMatarov** [comment] 2019-05-27 10:22
Hi,

The project I worked on last year seems to no longer work in the newest
version of Godot. Somebody has filed an issue, and the problem seems to
stem from the mix function.

**Comment by ca3games** [comment] 2019-05-27 15:47
What's the latest version your MIDI code works?

**Comment by DanielMatarov** [comment] 2019-05-28 09:34
I think 3.0

**Comment by Calinou** [comment] 2020-05-26 13:35
Duplicate of #12238.

**Closed by Calinou** 2020-05-26 13:35 UTC
Labels: discussion, feature proposal, topic:audio, topic:input
