### ISSUE TITLE
HeightMapShape3D not working properly with intersect_ray

### ISSUE THREAD

**Issue by 100gold** [godotengine/godot#78652] opened 2023-06-24 19:23 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10

### Issue description

Some part of HeightMapShape3D not producing intersection when using get_world_3d().direct_space_state.intersect_ray
In the minimal reproduction project, the highlighted area does not show intersections, but the other part of the HeightMapShape3D works correctly.

![screen](https://github.com/godotengine/godot/assets/1216278/b6b0cc3b-56a9-40b3-bae6-7d3449b68f71)

### Steps to reproduce

1) launch minimal reproduction project with Debug->Visible collision shapes enabled
2) Hover mouse on HeightMapShape3D
3) Some area of HeightMapShape3D will produce intersection:
    _Output:_
    found { "position": (-3.604305, 0.3, 0.013499), "normal": (0, 1, 0), "collider_id": 26675774603, "collider": @@3:<StaticBody3D#26675774603>, "shape": 0, "rid": RID(4007204487169) }
Some other zones produce no intersection:
   _Output:_
   not found

### Minimal reproduction project

[bug_heightmap.zip](https://github.com/godotengine/godot/files/11857984/bug_heightmap.zip)

**Comment by AThousandShips** [comment] 2023-06-24 19:36
* Duplicate of: #68238

**Closed by AThousandShips** 2023-06-24 19:36 UTC
