### ISSUE TITLE
Disabling editable children reverts to default

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#23239] opened 2018-10-23 08:42 UTC
**Godot version:** 
3.1 custom `c487cce6`

**Issue description:**
I don't understand what is the benefit of reverting parameters changes when editable children is disabled.
My problem is that i have scenes that contain nodes, let's call them objectives. For each objective i might want to tweak the areas(trigger areas). In a scene i might also have collision bounds with the environment.

What i expect is to be able to edit the objective's children (in particular some shapes) and then remove the ability to edit them in order to have less clutter in the 3D scene. If editable children is not ticked for an objective, i can't select the triggers of that objective, which is good if i want ot be able to select something in the 3D scene (some objectives have very big trigger areas that overlap a lot)

#22009 explains why i experienced some data loss during development :(

**Proposal**
Keep the changes in editable children even if they are folded back.
There are multiple solution to this issue, i think the best one would be to decouple editable children and the editability of the property of a scene (#22263 for reference?)
Could also work with having the ability to say "editable" and "selectable".

**Comment by asheraryam** [comment] 2018-10-24 11:20
This feature is already present for 2D but not for 3D (since Godot 2.1 even).

![screenshot_20181024_141929](https://user-images.githubusercontent.com/43449832/47427065-ea8ddf80-d797-11e8-8680-815086301486.png)

**Comment by asheraryam** [comment] 2018-10-24 13:49
Maybe I misunder, but I think the main issue is:

> What i expect is to be able to edit the objective's children (in particular some shapes) and then remove the ability to edit them in order to have less clutter in the 3D scene.

**Comment by QbieShay** [comment] 2018-10-24 14:06
@asheraryam there was an implicit [without losing my modifications]

**Comment by KoBeWi** [comment] 2020-07-16 13:18
@QbieShay The "unselectable children" option was added for 3D in 3.2. Does it resolve the issue?

**Comment by lyuma** [comment] 2021-02-12 02:37
Given the presence of a dialog box indicating that the reversion is intended behavior, I assume that disabling "Editable Children"i is *intended* to revert them to default. Hence, I would advocate closing this issue as out of date or "works as intended".
![Please Confirm... Disabling "editable_instance" will cause all properties of the node to be reverted to their default.](https://user-images.githubusercontent.com/39946030/107723015-02553e80-6c95-11eb-96b6-22b16a53929b.png)

Further, some commenters mis-read the issue as a request for "selectable children". This feature was also already implemented in 3.2

If there are still unresolved problems, they should be re-opened as other issues.

Issue #45915 which I filed is about deselecting "Editable Children" not having an immediate effect until the scene is re-opened. Such issues, in which a feature appears to work one way in memory and differently on disk, can cause confusion because it is difficult for anyone to correlate an action with different effects at an arbitrary later time when the scene is next re-opened.

As exhibited by the widely varying responses to this type of issue, it's hard to improve usability if the editor exhibits inconsistency in its behavior, so I would label any issue in which the in-memory state of a resource differs from the on-disk state as being a usability problem.

**Comment by KoBeWi** [comment] 2021-02-27 00:49
Closing as this conflicts with #45915 
You can open a proposal if it's still desired: https://github.com/godotengine/godot-proposals

Nodes don't keep track whether property was changed by the user or from some other action like `tool` script or AnimationPlayer. Implementing this proposal means that either we should keep track whether the property was changed during it was editable or the users would end up with properties that shouldn't be saved in their scene.

**Closed by KoBeWi** 2021-02-27 00:49 UTC
Labels: enhancement, topic:editor
