### ISSUE TITLE
screen flicker when zooming (3d)

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#58421] opened 2022-02-22 09:43 UTC
### Godot version

3.4.2.stable

### System information

windows 10, Intel(R) Core(TM) i7-4860HQ CPU @ 2.40GHz   2.39 GHz, 16.0 GB ram

### Issue description

screen flicker when zooming in/out in a 3d scene

https://user-images.githubusercontent.com/59080934/155105196-48df9f60-b469-4638-bfb0-81675303c197.mp4

### Steps to reproduce

-

**Comment by Calinou** [comment] 2022-02-22 15:29
Can you reproduce this if you enable **Interface > Editor > Update Continuously** in the Editor Settings?

**Comment by lawnjelly** [comment] 2022-02-22 19:08
Also is it a particular scene, or any scene? If there is something dodgy e.g. in a model causing a NaN this could potentially cause strange behaviour.

**Comment by AndHalfAFish** [comment] 2022-02-23 06:04
It happened after a couple of hours of working. I don't think it had anything to do with the scene since it was very simple.
@Calinou : I will check this, if it happens again today.

**Comment by Calinou** [comment] 2022-04-21 18:37
@AndHalfAFish Have you been able to reproduce this again since you last commented?

**Comment by AndHalfAFish** [comment] 2022-04-24 20:29
No. It hasn't happened again.

**Comment by Calinou** [comment] 2022-04-24 22:51
Closing, as nobody has been able to reproduce this recently. Please comment if you can still reproduce this on 3.4.4 or later.

**Closed by Calinou** 2022-04-24 22:51 UTC
Labels: bug, platform:windows, topic:rendering, needs testing, topic:3d
