### ISSUE TITLE
Vulkan: Screen-space effects (SSAO, SSIL, SSR) sometimes break when the viewport is resized

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#67391] opened 2022-10-14 11:32 UTC
### Godot version

4.0 dev beta 3

### System information

Windows 10, AMD Radeon RX6800XT

### Issue description

On Windows my game shows a bunch of horizontal stripes across the screen:
![image](https://user-images.githubusercontent.com/491704/195836246-38e8a9c7-6754-46d9-8c9d-72f4bbfcc519.png)

This isn't present on Arch Linux KDE X11 with Mesa drivers on the exact same hardware:
![image](https://user-images.githubusercontent.com/491704/195836688-3e542aed-c914-4026-a92f-7650945b33f2.png)

The issue seems to be related to changing window (viewport) dimensions. Disabling fullscreen in the game seems to help:

1. Hit `~` key to open in-game console
2. Type `display_fullscreen false`
3. Type `quit` and restart the game

### Steps to reproduce

1. Clone Liblast's repo: https://codeberg.org/Liblast/Liblast
2. Don't forget `lfs install && lfs pull` or you'll have no assets
3. Run the game

**Comment by unfa** [comment] 2022-10-14 14:56
It seems that screen-space effects are affected by this.

![image](https://user-images.githubusercontent.com/491704/195877528-eae42894-2264-4a71-9bf1-1ae82905d81c.png)
1. Look at the green face screen-space reflection that's incorrectly cast on the floor surface
2. The background scene is supposed to be blurred out with bokeh, but it seems that effect sis broken as well.
3. Bokeh however is rendered correctly where the backdrop of the scene is the sky, and not any geometry.

**Comment by Calinou** [comment] 2022-10-14 16:30
Resizing the window will break SSAO/SSIL/SSR in my experience.

**Comment by BastiaanOlij** [comment] 2022-12-06 11:47
Is this still broken? I fixed a bunch of bugs around SSAO/SSIL/SSR detecting changes in buffer sizes awhile back.

**Comment by Calinou** [comment] 2022-12-06 15:33
I can't reproduce this issue with SSAO anymore as of 4.0.beta7 (Linux, AMD Radeon RX 6900 XT with RADV):

### Half Size disabled

https://user-images.githubusercontent.com/180032/205954430-2d3b87de-5ec4-475b-b728-336df97a138b.mp4

### Half Size Enabled

See https://github.com/godotengine/godot/issues/62881.

https://user-images.githubusercontent.com/180032/205954460-cc6d5fc2-09f0-4836-b2d7-58b7e495ec52.mp4

**Comment by unfa** [comment] 2022-12-06 15:41
I'll have to test it. It only happened on Windows 10, never on Linux, despite running on the exact same hardware.

**Comment by Ansraer** [comment] 2022-12-17 15:23
I can confirm that SSIL breaks on Win 10 with a Radeon 6900XT running the latest drivers.

### Steps to reproduce:
1. Open a scene with SSIL enabled (e.g. https://github.com/Rytelier/Godot-4-forest-benchmark)
2. Move the camera so that some geometry goes beyond the bottom border.
3. Behold, artifacts! 

<details>
<summary>Example image</summary>

![image](https://user-images.githubusercontent.com/6329420/208248960-c764f029-eb3b-48ec-b5cb-356a17dc288f.png)

</details>

Resizing the viewport fixes and/or causes this problem. My guess is that there are problems with the buffer size, but I haven't looked deeper into it yet.

**Comment by clayjohn** [comment] 2023-01-18 05:03
Related: https://github.com/godotengine/godot/issues/62881 and https://github.com/godotengine/godot/issues/65987

**Comment by BastiaanOlij** [comment] 2023-02-09 05:15
Should be fixed with #72838

Small footnote that with fixing SSR there seems to be a new issue where high roughness causes small reflections to blur into star shapes. We'll investigate that with a separate issue (if we don't figure this out today).

**Closed** 2023-02-13 18:15 UTC
Labels: bug, topic:rendering, needs testing, topic:3d

**Comment by Calinou** [comment] 2023-10-23 16:10
@unfa Do you use MSAA? See https://github.com/godotengine/godot/issues/61415.
