### ISSUE TITLE
AnimationTreePlayer's default value for Process Mode is null?

### ISSUE THREAD

**Issue by p4ngy4** [godotengine/godot#4271] opened 2016-04-09 07:12 UTC
on Godot 2.0.1_stable

Is AnimationTreePlayer supposed to have a default value for Process Mode?

I know this is really trivial but it actually caused me a lot of trouble when I replaced AnimationTreePlayer with AnimationPlayer and couldn't figure out why it wouldn't play any animations. Turns out it inherited the null Process Mode value from the AnimationTreePlayer it replaced.

**Comment by akien-mga** [comment] 2016-04-11 08:05
Ping @JoshuaGrams and @slapin who seem to be our AnimationTreePlayer experts :)

**Comment by JoshuaGrams** [comment] 2016-04-11 10:59
Heh. The [constructor](https://github.com/godotengine/godot/blob/master/scene/animation/animation_tree_player.cpp#L1863) is creating a local variable and setting _that_ to idle processing, rather than the actual object property.

I should also dig around a bit and make sure the editor isn't doing something stupid as well...

**Comment by JoshuaGrams** [comment] 2016-04-11 11:04
Because...yeah, the AnimationPlayer constructor unconditionally sets it to idle processing, so the inheriting thing presumably happens in the editor code somehow? Or there's something else going on...

@p4ngy4: If you can describe exactly how to reproduce the bug in an empty project...then we can be sure we're fixing the same problem that you're seeing...that would be great. :)

**Comment by JoshuaGrams** [comment] 2016-04-11 11:32
OK, here's what I'm seeing.

- Create an empty scene.
- Add a Node2D as the root node (since editing the root node is wonky).
- Add an AnimationTreePlayer.
- Then use the replace node tool to replace it with an AnimationPlayer.

The AnimationPlayer keeps the processing mode from the ATP. Which...is probably a good behavior.

But on 2.0.1 stable (tested win32 and win64) the ATP starts with an empty processing mode.

On 2.0.2 stable it defaults to fixed processing, so we could probably close this as already fixed...except that I don't know why it changed. The constructors try to set an idle processing mode, which makes more sense to me (why waste CPU cycles updating the animation on the potentially faster fixed step? Just updated when you're actually going to display a frame).

So I don't know how that property gets set or whether it's fragile and likely to break again in the future...

**Comment by bojidar-bg** [comment] 2016-12-19 18:25
Is this still so in master?

**Comment by akien-mga** [comment] 2018-04-04 08:57
Seems fixed in the master branch, AnimationTreePlayer defaults to Idle process mode.

**Closed by akien-mga** 2018-04-04 08:57 UTC
Labels: enhancement, topic:core
