### ISSUE TITLE
Physics engine freeze

### ISSUE THREAD

**Issue by marhov** [godotengine/godot#56304] opened 2021-12-28 22:54 UTC
### Godot version

3.4.2 stable

### System information

Windows 10

### Issue description

I'm experience a freeze in the godot physics engine (both bullet and GodotPhysics). 

Godot versions: 3.1.1 stable, 3.2.1 stable, 3.2.3-rc3 and 3.4.2 stable tested and all with same behavior

### Steps to reproduce

I made a very simple example to show the issue:

https://github.com/marhov/godot/tree/main/freeze

just clone the repo and run the "Destination" scene. Use keyboard arrows up and down to move. The issue can be reproduced by first press forward and then backward. Then wait for a couple of seconds and the picture will freeze. The freeze happens when the rigid body is moving very slow or not at all and is very easy to reproduce.

### Minimal reproduction project

https://github.com/marhov/godot/tree/main/freeze

**Comment by Rubonnek** [comment] 2021-12-29 02:12
This is not a bug. You are using a `RigidBody` with `Can Sleep` enabled.

Once the object sleeps due to lack of movement, `_integrate_forces` will not be called.

Toggle off the `Can Sleep` option in the Inspector to disable this behavior.

Closing.

**Closed by Rubonnek** 2021-12-29 02:12 UTC
Labels: bug, topic:physics, needs testing, topic:3d
