### ISSUE TITLE
AnimatedSprite not emitting "frame_changed" signal correctly

### ISSUE THREAD

**Issue by thebricco** [godotengine/godot#10586] opened 2017-08-23 15:45 UTC
**Operating system or device, Godot version**
Win 10, Godot 2.1.3 and 2.1.4-beta.

**Issue description:**
"frame_changed" signal in AnimatedSprite node is not connected correctly to methods.

**Steps to reproduce:**
For example, the following code put in AnimatedSprite node won't work:

func _ready():
    connect("frame_changed", self, "method")

func method():
    print("called")

**Comment by Zylann** [comment] 2017-08-23 17:28
Then what are you doing to change the sprite's frame?

**Comment by thebricco** [comment] 2017-08-23 17:32
The sprite's frame are changed just fine, however when the frame changes the signal should be emitted, and apparently it is not.

**Comment by Zylann** [comment] 2017-08-23 17:52
But what are you doing to make the sprite's frame change? Do you set it with a method? Do you start an animation?

**Comment by thebricco** [comment] 2017-08-23 18:00
I simply play the animation with "play(anim)" or "set_animation(anim)".

**Comment by eon-s** [comment] 2017-08-24 04:18
I can't reproduce on latest beta.

Check the connections, maybe you are losing it in some way.
Can you share a minimal project with the problem?

**Comment by akien-mga** [comment] 2018-09-17 14:17
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:17 UTC
Labels: bug, topic:core
