### ISSUE TITLE
GDscript 2.0 Button.pressed.connect(self.function_name) raises an error

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#55552] opened 2021-12-02 16:44 UTC
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Win 64, Nvidea 765M

### Issue description

Cannot connect signal using the new GDScript 2.0 syntax described in the blogpost here:
https://godotengine.org/article/core-refactoring-progress-report-1

In the latest build shared by Akien on twitter (from 2021.11.17), this will work:

```
func _ready():
	$Button.connect("pressed", self._on_Button_pressed)

func _on_Button_pressed():
	print("pressed")
```

While this syntax which is what was described in the blog post as what is coming, will crash immediately in 20211117:
```
func _ready():
	$Button.pressed.connect(self._on_Button_pressed)

func _on_Button_pressed():
	print("pressed")
```

This is the error I get:
```
W 0:00:00:0135   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 3080400
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:154 @ _debug_messenger_callback()
```

To me the latter one, the one that is mentioned in the blog post is what makes a lot more sense. It seems odd to me to break compatibility with new syntax in order to avoid having string arguments, but then using strings for the signal anyway.

### Steps to reproduce

1. Make a new scene with Node2D root + script below
2. Add Button
3. Run scene

```
extends Node2D

func _ready():
	$Button.pressed.connect(self._on_Button_pressed)

func _on_Button_pressed():
	print("pressed")
```

### Minimal reproduction project
[Button_connect_signal_test.zip](https://github.com/godotengine/godot/files/7648396/Button_connect_signal_test.zip)

**Comment by KoBeWi** [comment] 2021-12-03 00:54
I can't reproduce the crash in the same build. Maybe it's something with your project?
Also `button.pressed` doesn't work due to #38937. If you want to use the new syntax, stick with `button_down` for now.

**Comment by golddotasksquestions** [comment] 2021-12-03 09:52
@KoBeWi , I'm not sure what you mean. As I have explained in the issue description with the alternative string example: the "pressed" signal works just fine in this build. What does not work for me is the new string-less method to connect signals.

I'm apparently not the only one.

Besides the Button, the project is virtually empty as you should be able to see from the "Steps to reproduce" section of this issue. However I also attached it now for you to test in v4.0.dev.20211117.official [175690957] if you want.
If you already have done so, I'm really out of idea why it would not work for me, while it does work for you.

**Comment by KoBeWi** [comment] 2021-12-03 11:38
I still can't reproduce the crash, I just get the error I mentioned.

I modified slightly your project:
[Button_connect_signal_test.zip](https://github.com/godotengine/godot/files/7649253/Button_connect_signal_test.zip)
The expected result is that the first scene won't work (due to the mentioned bug), but the second and third one should run without problem.
Can you check? And if it doesn't work, can you try also [the newest nightly build](https://hugo.pro/projects/godot-builds/)?

**Comment by golddotasksquestions** [comment] 2021-12-03 13:04
Maybe this is a misunderstanding: With "crash" I meant the project crashes/freezes immediately on startup when you try to run it, producing the error I included in the original issue post here. The Editor is not crashing. Maybe I'm lacking the correct word phrasing for this, it's like any other Error crash you would have on startup when you have a syntax mistake.

I've tried to run your project version, in v4.0.dev.20211117.official [175690957], but I could not.
When I try to import the project, I immediately get a popup alert window, telling me: "Project Settings were created with a newer version, whose settings are not compatible with this version."

I will try later again with the latest Nightly builds from Calinou.

**Comment by KoBeWi** [comment] 2021-12-03 13:05
Ah, just clear the project.godot if you want to run it in the old build.

**Comment by akien-mga** [comment] 2021-12-03 13:32
> The Editor is not crashing. Maybe I'm lacking the correct word phrasing for this, it's like any other Error crash you would have on startup when you have a syntax mistake.

To clarify on terminology, a crash means that the Godot process stopped abruptly when it shouldn't, because the process performed an illegal operation (e.g. accessing memory it isn't allowed to, or dereferencing a null pointer). See https://en.wikipedia.org/wiki/Crash_(computing)

If a project execution is stopped due to a syntax error, that's not a crash, just a script error which is raised in the debugger for you to evaluate and fix. The editor and runtime process behave as intended: error found, debugger raised - you can then fix the error and resume playing.

**Comment by golddotasksquestions** [comment] 2021-12-06 10:17
@KoBeWi 

> Can you check? And if it doesn't work, can you try also the newest nightly build?

Thanks, deleting/replacing the project.godot file worked to import your project, and I could run the other scenes (main2, main3).
Apart from my wrong use of crash terminology, this behaves exactly like described in the OP issue.

Meaning 
`$Button.button_down.connect(self._on_Button_pressed)` and
`$Button.connect("pressed", self._on_Button_pressed)` work, but
`$Button.pressed.connect(self._on_Button_pressed) `does not.

My expectation would be for the last one to work since signal usage was described like that in the [blog post](https://godotengine.org/article/core-refactoring-progress-report-1). For me personally this makes also the most sense of the three.

**Comment by KoBeWi** [comment] 2021-12-06 10:29
Thanks for confirming, as I thought, this is duplicate of #38937
`pressed` signal can't be connected with the new syntax, because it clashes with the `pressed` property, so one of them needs to be renamed. There is a PR open that will resolve this, but there isn't agreement on how the signal should be renamed yet: #48193

**Closed by KoBeWi** 2021-12-06 10:29 UTC
Labels: bug, topic:gdscript, needs testing
