### ISSUE TITLE
Drag, dock and position editor panels on other screens

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#25920] opened 2019-02-15 20:54 UTC
**Godot version:**
3.0, 3.1

**OS/device including version:**
all

**Issue description:**
I would like to drag and dock the editors panels freely to customize my workspace. This would allow me to also dock the panels "magnetically" together to form a cluster or sort and position on my screen however I like. This would also allow me to have the 2D/3D/script/assets area on one screen and my panels on another screen. The position and size of the panels should be saved and revertible to "default" at any time as well as to "last custom workspace" for instance.

Maybe even being able to separate "script", "2D" and "3D" as individual panels which then are draggable and position able even on separate screens. A feature that has come up as request on reddit a number of times before. (here is one example: https://www.reddit.com/r/godot/comments/aqr5ja/voice_your_frustration_what_do_you_think_is_the/egiov4f)

**Comment by ianb96** [comment] 2019-02-20 16:01
duplicate of #8250 or #9059 or #12742 or #2326

**Comment by clayjohn** [comment] 2019-04-21 19:37
Yea, this is a duplicate issue. Please search through existing issues when opening new ones. 

Duplicate of: #8250, #9059, #12742, #2326

**Closed by clayjohn** 2019-04-21 19:37 UTC
