### ISSUE TITLE
ERROR: affine_invert: Condition ' det == 0 ' is true.

### ISSUE THREAD

**Issue by canvasbushi** [godotengine/godot#31090] opened 2019-08-05 03:34 UTC
**Godot version:** 
3.1.1

**OS/device including version:** 
Android 8.0

**Issue description:**
Everything works fine, but im seeing a few errors pop up on the godot console:
Not sure whats causing it, anyone know a fix?

```text
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
ERROR: affine_invert: Condition ' det == 0 ' is true.
   At: core/math/transform_2d.cpp:51
```

**Steps to reproduce:**
godot 3.1.1 1 click deploy export to android

**Minimal reproduction project:**

**Comment by Gramps** [comment] 2019-11-06 22:26
No idea what it really is but I get the same error when moving my mouse across the editor's main window.  It does not happen when I mouse over any other panes except the main, center one.

**Comment by nawillcodes** [comment] 2020-05-16 22:20
Having the same issue, it happened after messing with some for loops

**Comment by Calinou** [comment] 2020-05-16 22:24
@nawillcodes Can you upload the project in which you managed to reproduce this?

**Comment by nawillcodes** [comment] 2020-05-16 23:15
3.2, It seems to only happen when I zoom in and out of the camera. My final project won't have any zoom so I'll be ok before I upload my entire project. I can upload samples and parts but it would be a lot of work to deconstruct what I don't want people to see

**Comment by madmiraal** [comment] 2020-09-06 15:38
Closing as duplicate of #41756. Although this was logged before, #41756 has a MRP and further analysis around Light2D.

**Closed by madmiraal** 2020-09-06 15:38 UTC
Labels: bug, needs testing, platform:android, topic:core
