### ISSUE TITLE
Vulkan: Indirectly lit surfaces show up black in reflections when using SDFGI with Bounce Feedback set to 0.0

### ISSUE THREAD

**Issue by DKesserich** [godotengine/godot#49836] opened 2021-06-22 18:59 UTC
### Godot version

4.0 dev (af451ff)

### System information

Windows 10, Vulkan, Radeon 5700XT

### Issue description

Surfaces that are being lit by bounced lighting when SDFGI is active are reflected as if they are receiving no lighting at all.
![image](https://user-images.githubusercontent.com/5456044/122981814-04b85b00-d34f-11eb-9366-1ff97b9fa527.png)

### Steps to reproduce

Extreme Example:
Create a 3D scene with a World Environment and enable SDFGI.
Build an enclosed volume out of MeshInstance3Ds (either planes or cubes)
Place a sphere inside the enclosed volume. Set the sphere material to have a metalness of 1 and a roughness of 0.
Place an OmniLight or a Spotlight inside the volume. Set the Range (if OmniLight) or the Angle (if Spotlight) to a low amount. 
Set the Energy high enough for bounce lighting to fill the interior.
Observe that only the parts of the surface that are receiving direct lighting will be reflected in the sphere.

### Minimal reproduction project

[SDFGITest.zip](https://github.com/godotengine/godot/files/6696764/SDFGITest.zip)

**Comment by DKesserich** [comment] 2021-06-22 19:00
SDFGI doesn't seem to work at all on latest. I had to go back two weeks to find a commit where it worked.

**Comment by Calinou** [comment] 2021-06-22 19:25
> SDFGI doesn't seem to work at all on latest. I had to go back two weeks to find a commit where it worked.

This is a [known issue](https://github.com/godotengine/godot/issues/49631).

**Comment by Calinou** [comment] 2021-08-30 13:07
Increasing Bounce Feedback above 0.0 seems to resolve this (try 0.5). Don't set it too high or infinite feedback look will happen, making surfaces overly bright.

**Comment by Calinou** [comment] 2022-01-05 13:53
Thinking about it, this may actually be done by design. If **Bounce Feedback** is set to 0, then lighting will only bounce one time (as the second bounce's energy is multiplied by 0). This means there is no way for the resulting indirect lighting to show up in reflections, since it would have to bounce twice (or more) to achieve this.

https://github.com/godotengine/godot/pull/39965 will resolve this by default, but this is still something that will happen if you manually decrease **Bounce Feedback** to 0.

**Comment by Calinou** [comment] 2022-03-22 16:20
This is now addressed by default by https://github.com/godotengine/godot/pull/39965, closing.

**Closed by Calinou** 2022-03-22 16:20 UTC
Labels: topic:rendering, documentation, topic:3d
