### ISSUE TITLE
GPUParticle2D jitter since Godot Beta 10

### ISSUE THREAD

**Issue by sgervais333** [godotengine/godot#71225] opened 2023-01-11 15:16 UTC
### Godot version

4.0beta10 (4.0beta11)

### System information

Windows 11, Vulkan API 1.3.224 - Vulkan NVIDIA GeForce RTX 3080 Ti

### Issue description

GPUParticle2D seems to jitter since Godot Beta 10 (I have the same problem Godot Beta 11).

Here is what I expect (screen capture of the project in Godot Beta 9):
![Animation](https://user-images.githubusercontent.com/6784639/211841608-c7b268ab-98c6-4c2c-9e42-b7730e44ea20.gif)

Here is what I got in Godot 4.0beta10 and Godot 4.0beta11:
![Animation2](https://user-images.githubusercontent.com/6784639/211841773-bdfc7c45-c262-4be9-b5b7-18856ddcb6f3.gif)

### Steps to reproduce

1. Make 2DScene
2. Add GPUParticle2D
3. Set the Process Material of this GPUParticle2D to a new ParticleProcessMaterial
4. Move the particle around (or make a animationPlayer to move the Particle)

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/10393668/TestProject.zip)

**Comment by Calinou** [comment] 2023-01-11 17:34
I can confirm this on 4.0.beta11 (it's visible in https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/2d/particles). This occurs when moving a GPUParticles node with Local Coords disabled..

**Comment by clayjohn** [comment] 2023-01-11 20:10
I have a feeling this is caused by https://github.com/godotengine/godot/pull/70418 we will need to investigate further

**Comment by sgervais333** [comment] 2023-01-12 03:59
> I can confirm this on 4.0.beta11 (it's visible in https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/2d/particles). This occurs when moving a GPUParticles node with Local Coords disabled.
> 
> It's worth checking whether this issue occurs in 3D as well.
> 
> Can you reproduce this after disabling **Interpolate** and setting **Fixed FPS** to 0 on the GPUParticles node? See #70777.

Yes, it fixes it when I disable **Interpolate** and set **Fixed FPS** to 0 on the GPUParticles node. So I assume it is liked to https://github.com/godotengine/godot/pull/70777

**Comment by sgervais333** [comment] 2023-01-13 18:49
The problem is still in Godot Beta 12.

It's like the Interpolate have no effect.

**Comment by akien-mga** [comment] 2023-01-17 09:16
Fixed by #71520.

**Closed by akien-mga** 2023-01-17 09:16 UTC
Labels: bug, topic:rendering, confirmed, regression
