### ISSUE TITLE
Editor crashes when baking light

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#3993] opened 2016-03-09 11:35 UTC
**Operating system or device:**

 Godot 2.0.1 stable, Win64 / Win32 (tested on both versions)

Windows 8 64-bit desktop computer.

**Issue description** (what happened, and what was expected):

Baking a lightmap crashes at "Light Baker Setup - Creating Light Octree" step. Every single time.

Here's commandline output:

	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	DETECTED MONITORS: 1
	ERROR: Cannot initialize RtAudio audio driver: No devices present.
	   At: drivers/rtaudio/audio_driver_rtaudio.cpp:65
	ERROR: initialize: Initializing audio failed.
	   At: platform/windows/os_windows.cpp:993
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	OPENING: E:/unfa/Godot/Projekty/02 (E:::unfa::Godot::Projekty::02)
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	running cmdline: "E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe" "-path" "E
	:/unfa/Godot/Projekty/02" "-editor"
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	DETECTED MONITORS: 1
	ERROR: Cannot initialize RtAudio audio driver: No devices present.
	   At: drivers/rtaudio/audio_driver_rtaudio.cpp:65
	ERROR: initialize: Initializing audio failed.
	   At: platform/windows/os_windows.cpp:993
	EXEC PATHP??: E:\unfa\Godot\Godot_v2.0_stable_20160223_win64.exe
	VBoxContainer: 136,100
	bind toptions
	ERROR: texture_set_data: Condition ' p_image.empty() ' is true.
	   At: drivers/gles2/rasterizer_gles2.cpp:957
	ERROR: texture_set_size_override: Condition ' p_width<=0 || p_width>16384 ' is t
	rue.
	   At: drivers/gles2/rasterizer_gles2.cpp:1387
	ERROR: baked_light_set_light: Condition ' p_light.size()==0 ' is true.
	   At: servers/visual/visual_server_raster.cpp:1256
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	ERROR: create: Condition ' Math::is_nan(p_aabb.size.x) ' is true. returned: 0
	   At: core/math/octree.h:827
	settings changed
	ERROR: _update_camera: Condition ' !E ' is true.
	   At: scene/resources/world.cpp:129
			total triangles: 0

**Steps to reproduce:**

1. Create a scene with node tree:

- Spatial
     - Baked Light Instance
         - TestCube
         -  Spotlight (set it to bake Full)

2.  Select the Baked Light Instance and add a new BakedLight resource in it.

3.  Typie in "512, 512" as the "Generate size" in the first Lightmap texture instance

4. Cclick "Bake" in the editor viewport's top panel

5. Watch it blow up

**Comment by unfa** [comment] 2016-03-14 10:59
Just tested it on Win64 .0 stable custom build and the same thing happens.

**Comment by unfa** [comment] 2016-03-17 08:49
Just built Godot from source for X11 - latest Git version has this problem as well. Crashes on baking light.

**Comment by akien-mga** [comment] 2016-07-24 08:33
This is likely a duplicate of #1990.

**Comment by djrm** [comment] 2016-07-26 03:12
yes this is a duplicate of #1990, im unable to reproduce this after the fix for #1990

**Closed** 2016-07-26 05:16 UTC
Labels: bug, topic:editor
