### ISSUE TITLE
Crash on "Create multiple convex collision siblings" of a QuadMesh

### ISSUE THREAD

**Issue by pho** [godotengine/godot#37984] opened 2020-04-18 11:04 UTC
Godot version: v3.2.1.stable.official

OS/device including version: Windows 10 Version 1909

Issue description: Create multiple convex collision siblings on a QuadMesh crashes Godot

Steps to reproduce:

- Add a QuadMesh to a scene
- Click on Mesh > Create multiple convex collision siblings
- Bye

Minimal reproduction project: Any 3D scene

**Comment by Calinou** [comment] 2020-04-18 12:28
Related to #30687.

**Comment by madmiraal** [comment] 2020-05-06 10:28
I'm unable to reproduce this problem following your instructions. Please upload a minimal reproduction project that is one convex collision shape away from crashing the editor.

**Comment by Calinou** [comment] 2020-05-06 13:04
I'll close this as a duplicate of #30687.

**Closed by Calinou** 2020-05-06 13:04 UTC
Labels: bug, crash, topic:editor
