### ISSUE TITLE
NodePath exports no longer work

### ISSUE THREAD

**Issue by Kelin2025** [godotengine/godot#69361] opened 2022-11-29 23:13 UTC
### Godot version

4.0beta6

### System information

Win 10 (the same on MacOS)

### Issue description

The same issue that happened [here](https://github.com/godotengine/godot/issues/68840) happens with gdscript as well
All nodes that use NodePath variables in my project got broken

### Steps to reproduce

1. Create a script
2. Create a variable `@export something: NodePath = ""`
3. Add this node to some scene
4. Try to change this variable in GUI. It's always empty, and attempts to change the value by selecting nodes/pasting do nothing

### Minimal reproduction project

N/A

**Comment by garychia** [comment] 2022-11-30 09:39
It seems that if you write something like (I think this is a type error as NodePath is not String but it compiles)
`
@export var my_path: NodePath = ""
`
The compiler seems to treat the default value of my_path as a String instead of a NodePath.
As the result, the comparison here
https://github.com/godotengine/godot/blob/5826e960143fd416e0d02cf8f672d778f56da9ea/core/object/script_language.cpp#L424-L426
will fail as there is no function that compares a String (default value) with a NodePath (value to be assigned to my_path).
If you change it to
`
@export var my_path: NodePath = NodePath("")
`
Everything works fine.

**Comment by Kelin2025** [comment] 2022-11-30 09:43
@garycha will try today, thanks. However, it worked with string before

**Comment by kleonc** [comment] 2022-11-30 11:18
> It seems that if you write something like (I think this is a type error as NodePath is not String but it compiles) `@export var my_path: NodePath = ""` The compiler seems to treat the default value of my_path as a String instead of a NodePath. As the result, the comparison here
> 
> https://github.com/godotengine/godot/blob/5826e960143fd416e0d02cf8f672d778f56da9ea/core/object/script_language.cpp#L424-L426
> 
> will fail as there is no function that compares a String (default value) with a NodePath (value to be assigned to my_path).
> If you change it to
> `@export var my_path: NodePath = NodePath("")`
> Everything works fine.

Hence it's likely a regression from #68354. cc @anvilfolk

**Comment by anvilfolk** [comment] 2022-11-30 16:09
Thanks for the heads up!

I can see three possible solutions here.

1.  Create comparators for `String` and `NodePath`.
2. Change the `GDScriptAnalyzer` so that the `""` gets interpreted as `NodePath` rather than as a `String`.
3. Use `if (Variant::evaluate(Variant::OP_NOT_EQUAL, defval, p_value) || defval != p_value) { `, which is a combination or pre & post-commit.

I'm not entirely sure which one is "best". Would love people's input!

**Comment by Kelin2025** [comment] 2022-11-30 16:54
We could also just ban using string values for NodePath variable tbh. Not a big deal, less confusion, less checks inside engine

**Comment by anvilfolk** [comment] 2022-11-30 16:57
Yeah, I'm gonna try out a few things to see what GDScript accepts & doesn't accept right now, and hopefully come up with a solution :)

**Comment by anvilfolk** [comment] 2022-11-30 17:24
Been digging a little more.

>We could also just ban using string values for NodePath variable tbh. Not a big deal, less confusion, less checks inside engine

I don't think this is a good solution, unfortunately! You can't construct NodePaths by appending things together, like `@export var r : NodePath = ^"." + ^"Node2D"`. There's probably some code out there constructing `NodePath`s from `String` concatenation.

Maybe the best thing is implicit conversion to `NodePath` for initializers. I suspect that already happens during assignments, will check now :)

**Comment by anvilfolk** [comment] 2022-11-30 19:54
I think I've found a solution I'm pretty happy with. I didn't want to change the behavior of `some_node_path ==/!= some_string` in GDScript since people might not expect that.

I'm currently trying to see if I can't make an implicit conversion of default values for the initializers. Just wanted to let people know hopefully there'll be a fix soon :)

**Comment by Kelin2025** [comment] 2022-11-30 20:02
Cool, thanks for the blazing fast reaction!

**Closed** 2022-12-11 22:58 UTC
Labels: bug, topic:editor, confirmed, regression
