### ISSUE TITLE
Left Dock set width bug on smaller window and buggy to set again and unwanted autosizes to show Node names in Scene inspector.

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#27974] opened 2019-04-13 08:32 UTC
**Godot version:**
3.1.1 Mono 2fbc421

**Issue description:**
When I size my left dock when maximized and then make the window smaller. So small that it effects the left dock size. In my case half my screen. The left dock is shown smaller which is fine except that now it thinks it needs to resize it every time I select a node in the Scene inspector whose name can't be fully displayed in the new smaller size. This result in jerky UI. Also you can't set a new width to the left dock when this happens and its sized bigger to show a name.

To actually fix the size again you first have to select a node that can be displayed in the small size and then resize. Otherwise it won't listen to the new size and keeps spazzing out when you select a different node. The worst is this has to be repeated for every scene tab that is open. So switching between scenes also changes the left dock size.

I read two other vaguely related issues but this is different. Especially the inability to set a new size unless you are at the smallest new size already and that this is about the annoying auto resizing when selecting a node in Scene inspector.

**Comment by Calinou** [comment] 2021-09-01 19:30
Duplicate of https://github.com/godotengine/godot/issues/31133 (same cause).

**Closed by Calinou** 2021-09-01 19:30 UTC
Labels: enhancement, topic:editor, usability
