### ISSUE TITLE
GodotSharp: Inconsistent use of types in TabBar

### ISSUE THREAD

**Issue by Garteal** [godotengine/godot#95429] opened 2024-08-12 15:36 UTC
### Tested versions

4.3 rc2 mono

### System information

EndeavourOS / Windows 11

### Issue description

I stumbled upon this inconsistency where a TabBar (in C#) is expecting and returning different types instead of one.

For example, according to the [Godot Docs](https://docs.godotengine.org/en/stable/classes/class_tabbar.html#signals), the `tab_changed` is said to return an `int`. However in C# it will return a `long`. (This goes for all EventHandlers)
![image](https://github.com/user-attachments/assets/48293257-d4d8-4895-92bc-c12e5c0194c3)

Thing is, the C# methods expect an `int` instead of a `long`.
![image](https://github.com/user-attachments/assets/69e9bb9c-e2c2-4669-8fa8-61069d0ca826)

I expect this to be one or the other and not mixed like this. I'd say these should simply be an `int`?

Also, I couldn't easily find the source code to address this, so if anyone could point me to it I could create a PR when I find more inconsistencies.

### Steps to reproduce

1. Use any Event from TabBar
2. Call any Method from TabBar

### Minimal reproduction project (MRP)

none

**Comment by raulsntos** [comment] 2024-08-12 16:15
- This issue is a duplicate of https://github.com/godotengine/godot/issues/65749. Closing to consolidate there.

> For example, according to the [Godot Docs](https://docs.godotengine.org/en/stable/classes/class_tabbar.html#signals), the `tab_changed` is said to return an `int`. However in C# it will return a `long`.

The class reference is using the GDScript type names, which means `int` is a 64-bit integer (the C# equivalent is `long`).

The generated C# bindings use the metadata registered in ClassDB to determine which integer type to use. In the case of `GetTabTitle`, since the C++ method uses a 32-bit integer, the metadata allows us to use the correct type in C#. Unfortunately, such metadata doesn't exist for signals so, even though in this case it may be fine to use 32-bit integers, we have to use 64-bit integers to be safe.

**Closed by raulsntos** 2024-08-12 16:15 UTC
