### ISSUE TITLE
Vulkan selects wrong device

### ISSUE THREAD

**Issue by TheFamousRat** [godotengine/godot#47545] opened 2021-04-01 14:19 UTC
**Godot version:**
Godot version : 4.0 custom build from commit bb90d3a
Build command used : `scons p=linux bits=64 target=release_debug -j4`

**OS/device including version:**
OS : Ubuntu 20.04
GPU : GeForce GTX 960M

**Issue description:**
I have vulkan installed and working on my machine. For example, the `vkcube` command from `vulkan-tools` works as expected from the terminal. However, when running Godot 4.0, the integrated GPU is selected instead of the discrete one, resulting in the program not launching at all. The following output gets printed to the terminal : 

`Godot Engine v4.0.dev.custom_build.bb90d3adc - https://godotengine.org
Vulkan API 1.2.162
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Using Vulkan Device #0: INTEL - Intel(R) HD Graphics 530 (SKL GT2)
- Vulkan subgroup size 32
- Vulkan subgroup stages STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE
- Vulkan subgroup supported ops FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD
- Vulkan subgroup quad operations in all stages
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x3200008
  Serial number of failed request:  105
  Current serial number in output stream:  111`

**Steps to reproduce:**
Launching Godot 4.0 on a machine where the integrated GPU's id is the first one, so 0 ?

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2021-04-01 14:35
Duplicate of https://github.com/godotengine/godot/issues/42348.

**Closed by Calinou** 2021-04-01 14:35 UTC
