### ISSUE TITLE
Moving a child Node3D with "Use Local Space" is broken

### ISSUE THREAD

**Issue by kebabskal** [godotengine/godot#81789] opened 2023-09-17 08:55 UTC
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Moving a child Node3D with "Use Local Space" causes it to jump and then not be translated in along the local axes.
Nodes that are direct children of the current scene works, but not one step.

See screen capture:
https://github.com/godotengine/godot/assets/2920473/a8ef7306-997f-4479-bf6d-f06cb9f30722

### Steps to reproduce

1. Create a new project using v4.2.dev4.official [549fcce5f]
2. Create a 3D scene
3. Create a MeshInstance3D as a child and assign any mesh to it (I used a cube) (Parent Cube)
4. Create another MeshInstance3D, give it a shape and parent this to the previous (Child Cube)
5. Rotate and move the Parent Cube a bit
6. Enable "Use Local Space" in the scene view toolbar
7. Move the Child Cube using the movement gizmo.
8. Observe how the Child Cube first snaps to the wrong position and then moves along the wrong axis/plane

### Minimal reproduction project

[godot-local-space-bug.zip](https://github.com/godotengine/godot/files/12642429/godot-local-space-bug.zip)

**Comment by AThousandShips** [comment] 2023-09-17 09:00
Duplicate of https://github.com/godotengine/godot/issues/81604

**Closed by AThousandShips** 2023-09-17 09:00 UTC
