### ISSUE TITLE
Crackling audio playback on Chrome with HTML5 threads export (AudioWorklet)

### ISSUE THREAD

**Issue by davcri** [godotengine/godot#47487] opened 2021-03-30 08:35 UTC
**Godot version:** 3.3rc6

**OS/device including version:**

Manjaro Linux + Chrome 89.0.4389.90. 

<details>
<summary>More HW/SW info: </summary>
<pre>
System:
  Kernel: 5.11.6-1-MANJARO x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
  Distro: Manjaro Linux 
Machine:
  Type: Desktop System
  Mobo: ASUSTeK model: ROG STRIX B550-F GAMING (WI-FI) v: Rev X.0x 
CPU:
  Info: 8-Core model: AMD Ryzen 7 3700X bits: 64 type
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1650 SUPER] driver: nvidia v: 460.56 
  Display: x11 server: X.Org 1.20.10 driver: loaded: nvidia resolution: 
  1: 1920x1080~60Hz 2: 1600x900~60Hz 
  OpenGL: renderer: GeForce GTX 1650 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA 460.56 
Audio:
  Device-1: NVIDIA TU116 High Definition Audio driver: snd_hda_intel 
  Device-2: AMD Starship/Matisse HD Audio driver: snd_hda_intel  (this one it's actually connected to the speakers)
  Device-3: RODE Microphones RODE NT-USB type: USB 
  driver: hid-generic,snd-usb-audio,usbhid 
  Sound Server-1: ALSA v: k5.11.6-1-MANJARO running: yes 
  Sound Server-2: PulseAudio v: 14.2 running: yes 
</pre>
</details>

**Issue description:**
Audio playback has crackling noises on Chrome with HTML5 threads export. Follows up a discussion from https://github.com/godotengine/godot/issues/43210

Some tests that I did with my HW/SW setup:

- Issue it's still there with older Chrome versions (80, 86)
- Changing the output latency to 100ms doesn't mitigate the issue
- Changing audio format to mp3 or ogg doesn't mitigate the issue
- I cannot reproduce the issue on Firefox 87.0. Every combination of export and audio device works fine.
- [Video](https://user-images.githubusercontent.com/6860637/112728048-9a497780-8f25-11eb-82f3-89cca3154ed1.mp4) | Issue may be related to a specific combination of Chrome + motherboard audio card + audio driver: audio it's pretty bad on the motherboard audio (`Starship/Matisse HD controller` which it's my daily output audio device), but it's almost okay with the `RODE-NT USB` headphones output (it's a USB mic with integrated audio device). 
However it still has some audio crackling. 
- [Video](https://user-images.githubusercontent.com/6860637/112728544-2066bd80-8f28-11eb-98e7-feeda116b8a4.mp4) | Single-thread export plays audio better than multi-thread export

**Steps to reproduce:**
I can reproduce the issue by simply playing an audio file with the official Godot Web Editor (see [video](https://youtu.be/LQYa5yoeI80)).

**Minimal reproduction project:**
[Web Preview](https://davcri.github.io/godot-html5-thread-audio/) | [Repo ](https://github.com/davcri/godot-html5-thread-audio)
Godot project with an `AudioStreamPlayer` playing a WAV audio. HTML5 exported with threads.

**Comment by akien-mga** [comment] 2021-03-30 08:44
Possibly the same issue as this upstream bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1188901

**Comment by Mast3rGenius** [comment] 2021-03-30 22:53
+1 Godot 3.2.3
https://amberstudios.itch.io/slimes-and-sawblades

It also has weird audio delay/repeat issues on top of the crackling.

**Comment by Faless** [comment] 2021-03-31 01:09
> +1 Godot 3.2.3
> https://amberstudios.itch.io/slimes-and-sawblades
> 
> It also has weird audio delay/repeat issues on top of the crackling.

That's not the threaded version, see: #47453

**Comment by davcri** [comment] 2021-04-22 13:49
I have a good news and a bad news.

- **Good news**: the issue disappeared after an upgrade of my system (Chrome 90.0, Linux 5.11.10). Now I can go to the MRP (https://davcri.github.io/godot-html5-thread-audio/) and the audio plays perfectly
- **Bad bews**: I didn't understand what fixed the issue

I tried the MRP with older chrome builds but it seems to work just fine. So I guess that it was related to something with the SW/HW audio stack.

Sorry for the lack of information, let me know if I can make some other test.

**Comment by Faless** [comment] 2021-06-04 12:13
Maybe a driver issue fixed by the upgrade?
Closing anyway since it can no longer be reproduced.
Feel free to comment below if you experience the issue again and I'll reopen it.

**Closed by Faless** 2021-06-04 12:13 UTC
Labels: bug, confirmed, platform:html5, topic:audio, topic:thirdparty
