### ISSUE TITLE
Shader sign function is broken when values of 0 are present.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#76909] opened 2023-05-10 10:04 UTC
### Godot version

Godot 4.2

### System information

Linux, fedora 38

### Issue description

Sign function is supposed to return 1 or -1 depending if the given value is positive or negative. 

Seems like the sign function does not contain logic to handle values that are exactly 0, so the result is a heavy flickering. 

In unity or unreal values that are 0 are either included as positive or as negative. Same for any other software.

We should either include 0 as positive or negative or add a parameter named "Include 0" Which would return positive at 0 values when activated and negative when deactivated.

### Steps to reproduce

Pass some information with 0 values to the sign function. Specially noticeable when used to calculate the direction of normals in world space.

[Grabación de pantalla desde 2023-05-10 12-02-24.webm](https://github.com/godotengine/godot/assets/64601424/02ca3fb7-da49-4724-b18d-f4d8c1690261)

### Minimal reproduction project
Edit: Added minimal reproduction project.
[SignBug.zip](https://github.com/godotengine/godot/files/11442371/SignBug.zip)

**Comment by yosoyfreeman** [comment] 2023-05-10 10:18
As a workaround you can make your own sign function with a decompose node and 3 "if".

![imagen](https://github.com/godotengine/godot/assets/64601424/7aa7e912-c6da-452f-a682-785932d41045)

In this case, values equal to 0 are included as positive.

**Comment by yosoyfreeman** [comment] 2023-05-10 13:30
> 
Hi Adam, i didn't made one cause it involves any use of the function, but i updated one with the setup i used to test it already created. Hope it helps.

Freeman.

**Comment by AThousandShips** [comment] 2023-05-10 13:57
The fact that Unreal uses a *different* function than sign (which is defined the way glsl does it) is weird and I don't think we should copy it

**Comment by AThousandShips** [comment] 2023-05-10 14:03
I would suggest opening a proposal for adding a new function, or adding extra functionality to sign like you suggested, but this is not a bug

**Comment by yosoyfreeman** [comment] 2023-05-10 14:22
I think we may agree that the flickering issue is not an expected behaviour. 

I been researching this topics, and almost any 3D engine do this correction automatically because otherwise is virtually unusable as it will not cover special cases by itself.  And not only on engines, but on programming languages too. For example, Sign was removed from python cause it was considered unusable due to this same problem, not being able to cover 0, nans etc.  (Source:  https://stackoverflow.com/questions/1986152/why-doesnt-python-have-a-sign-function)

Sign is problematic by design and need to be corrected for the application you are using it, which in this case is 3D graphics. Again, aleatory flickering does not seem like a desirable behaviour.

Adding another node with another name would be confusing. People learning visual shaders or shaders in general for 3D games and engines will try to follow guides and tutorials and encounter a hard barrier that should not be there.

In my view this have two possible fixes:

-Include what an option to what you want to do with 0 values, which would be the more friendly approach.

-Warn users in the description that Sign function will return errors on 0/null values and suggest to use another function instead.


Also, it is not documented: 
![imagen](https://github.com/godotengine/godot/assets/64601424/db3fa2e9-6827-46c1-ab4b-cc8f6993a85e)

**Comment by AThousandShips** [comment] 2023-05-10 14:24
It doesn't return errors though, it just appears to as it goes from 1 to 0 to -1 at a very narrow range, it *does* cover 0, it just doesn't take any margin, adding an option to take a margin into account is a good idea but I'd suggest doing a proposal for that since it's not fixing any bug but improving behaviour that can be confusing

**Comment by yosoyfreeman** [comment] 2023-05-10 14:40
I made a proposal as you suggest.

But i still think the flickering is an error due to number precision. I'm multiplying my uv for the direction on the normal, and is not 0  when 0, it flickers between -1,0 and 1. So at least adding some margin by default to account for that should eliminate flicker.

**Comment by clayjohn** [comment] 2023-05-10 16:30
As mentioned above, the proper GLSL implementation of ``sign()``: "returns -1.0 if x is less than 0.0, 0.0 if x is equal to 0.0, and +1.0 if x is greater than 0.0"

https://registry.khronos.org/OpenGL-Refpages/gl4/html/sign.xhtml

For text shaders, Godot lets users write GLSL directly, so we are stuck with the GLSL specification here. For Visual shaders we could just not use GLSL ``sign()`` and use ``x >= 0.0 ? 1.0 : -1.0`` instead

**Comment by kleonc** [comment] 2023-05-10 17:40
> Specially noticeable when used to calculate the direction of normals in world space.

@yosoyfreeman Note that your calculations for obtaining normals in world space are incorrect in the first place. Since you've not modified the vertex shader, the `normal` input of the fragment shader is in view space (see [the docs](https://docs.godotengine.org/en/4.0/tutorials/shaders/shader_reference/spatial_shader.html#fragment-built-ins)). Also [to properly transform normal you need to transform it by the transposed inverse matrix of the given transformation](https://paroj.github.io/gltut/Illumination/Tut09%20Normal%20Transformation.html) (by $(M^{-1})^T$ instead of just by the given transformation $M$). Given that, to transform normal from view space to world space you need to multiply it by transposed inverse of view to world transformation matrix, which is equivalent to transposed world to view transformation matrix. So [according to the docs](https://docs.godotengine.org/en/4.0/tutorials/shaders/shader_reference/spatial_shader.html#fragment-built-ins): transposed `VIEW_MATRIX`.

Like this (note that by moving the camera the world space normals are not changing):

![qdNUpcURAK](https://github.com/godotengine/godot/assets/9283098/9cc2397e-a666-436a-8d7b-a095aa827533)


> For text shaders, Godot lets users write GLSL directly, so we are stuck with the GLSL specification here. For Visual shaders we could just not use GLSL `sign()` and use `x >= 0.0 ? 1.0 : -1.0` instead

@clayjohn I don't think that's a good idea to create such discrepancies between the same named functions / visual nodes. If anything, I think it would make more sense to potentially add some additional node instead.

BTW such change wouldn't solve OP's problem shown in here anyway as it's caused by the floating point errors: each value which should be theoretically zero after the matrix multiplication(s) can end up being positive/negative near-zero value, and thus it can "flicker" between being positive/negative when the view (camera) transform is changing.

---

I don't see any bug in here. Given there's https://github.com/godotengine/godot-proposals/issues/6854 opened I think there's nothing to discuss in here and this issue could be closed.

**Comment by clayjohn** [comment] 2023-05-10 18:36
@kleonc Thanks for your helpful summary. And I agree, the remaining issues here are better discussed in a proposal as we need to decide whether straying from the GLSL spec in VisualShaders is a good idea. 

Closing in favour of https://github.com/godotengine/godot-proposals/issues/6854

**Closed by clayjohn** 2023-05-10 18:36 UTC
Labels: discussion, topic:shaders, topic:3d
