### ISSUE TITLE
Resizing an IntArray became slower in 2.x series, starting from 2.1.5 beta1

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20571] opened 2018-07-29 14:18 UTC
Godot 2.1.5 beta1 and later 2.x series
Windows 10 64 bits

I ran my GDScript benchmark and noticed that resizing an `IntArray` became slower. Maybe it's not that relevant considering 2.x series life is slowly ending, but I post the issue for awareness.

![image](https://user-images.githubusercontent.com/1311555/43367364-8492074e-9343-11e8-83c3-ce2f55126c88.png)
Chart up axis is microseconds starting at zero.

The test being run is this one: https://github.com/Zylann/gdscript_performance/blob/master/project2/tests/test_int_array_resize.gd

**Comment by allkhor** [comment] 2018-07-30 17:18
I did some tests and I have this results:
![array_resize](https://user-images.githubusercontent.com/1049442/43412346-c227ec52-944e-11e8-95d8-8c664034b0f6.png)

**Comment by akien-mga** [comment] 2018-08-13 08:39
Looking over the git log since 2.1.4-stable, I guess it may be related to 647c4ae5bf9b64e78b8ff0fd36c8aa610f2a814b? (cc @marcelofg55)

@allkhor So it looks like you can't reproduce the regression on Linux?

**Comment by allkhor** [comment] 2018-08-13 08:50
@akien-mga  Yes, on Linux x64 i can't reproduce the regression.

**Comment by KoBeWi** [comment] 2020-06-19 12:31
This doesn't sound like critical issue to fix in 2.1, so closing.

**Closed by KoBeWi** 2020-06-19 12:31 UTC
Labels: bug, topic:core
