### ISSUE TITLE
UI Translating non engine variables in tree path

### ISSUE THREAD

**Issue by conde2** [godotengine/godot#87449] opened 2024-01-21 19:47 UTC
### Tested versions

Tested in Godot v4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2137569/87530a7a-09be-4c55-baf2-6e653c5b415f)

![image](https://github.com/godotengine/godot/assets/2137569/a28741f3-2ec2-4f6b-88c0-35492c89abf4)

### Steps to reproduce

Create a animation tree, then add a new BlendSpace2D, change the node name to Idle, it will be translated later in the root path.
![image](https://github.com/godotengine/godot/assets/2137569/3ccddf54-76c3-41bd-a7c6-2ea16c1fa83b)

### Minimal reproduction project (MRP)

[LearnProject.zip](https://github.com/godotengine/godot/files/14002595/LearnProject.zip)

**Comment by AThousandShips** [comment] 2024-01-21 19:53
Duplicate of https://github.com/godotengine/godot/issues/86033

**Closed by AThousandShips** 2024-01-21 19:53 UTC
