### ISSUE TITLE
GuiInput InputEventScreenTouch not receiving "touch up" event

### ISSUE THREAD

**Issue by autofool** [godotengine/godot#53006] opened 2021-09-24 11:37 UTC
### Godot version

3.3.3.stable.mono

### System information

linux, Nvidia 1650 ti

### Issue description

I have created a Button for Touchscreen. Its Godot.Button not Godot.TouchScreenButton. When querying InputEventScreenTouch for (Pressed) variable, I'm not receiving "False" one. So I can see ButtonDown event but not Button Up.

### Steps to reproduce

- Disable emulate mouse from touch.
- Enable emulate touch from mouse.
- Create Button node.
- Add script to query InputEventScreenTouch inside _GuiInput() function. eg:
```
if (@event is InputEventScreemTouch touch) {
    if (touch.Pressed) {
        //button down
    } else {
        //button up
    }
}
```
- Run project in editor. You will receive button up and down due to mouse emulating touch.
- Run project in Android. You will receive button down but not button up.

### Minimal reproduction project

[TestButton.zip](https://github.com/godotengine/godot/files/7225337/TestButton.zip)

**Comment by Calinou** [comment] 2021-09-24 11:52
Duplicate of https://github.com/godotengine/godot/issues/29525.

**Closed by Calinou** 2021-09-24 11:52 UTC
