### ISSUE TITLE
Disable Generated Comments in Scripts

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15037] opened 2017-12-25 10:46 UTC
The generated comments in scripts are annoying to remove every time. It would be nice to be able to disable them.

**Comment by MrJustreborn** [comment] 2017-12-25 11:07
You can select a preset with no comments:
![bildschirmfoto_2017-12-25_12-06-04](https://user-images.githubusercontent.com/11594586/34338783-27c1497a-e96c-11e7-9038-13b9d75a06c4.png)

**Comment by Noshyaar** [comment] 2017-12-25 12:35
Duplicate of #5711, use the presets.

**Closed by Noshyaar** 2017-12-25 12:35 UTC
