### ISSUE TITLE
4.0, Editor: Mouse hover is not recognized after interacting with certain UI elements

### ISSUE THREAD

**Issue by TamerSoup625** [godotengine/godot#62864] opened 2022-07-09 19:52 UTC
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 10 Home, AMD A10-9620P RADEON R5

### Issue description

After selecting an option from an OptionButton or entering a value in a SpinBox, none of the UI elements will react to a mouse hover, which also means tooltip are not shown.
Unfocusing then refocusing the window makes UI react like normal, but the issue can return again.
What's interesting is that this does not happen on projects, it works like normal.

### Steps to reproduce

1. Get an OptionButton or SpinBox as part of the editor interface. This can be done by creating a Node and using the inspector to get the node's process_mode or process_priority (Each modified by an OptionButton and SpinBox)
2. Select an option for process_mode or type a number for process_priority
3. Notice how buttons don't react to a mouse hover and tooltip does not get shown

### Minimal reproduction project

[Mouse hover bug.zip](https://github.com/godotengine/godot/files/9077817/Mouse.hover.bug.zip)
Follow the steps above on the Main's option_button and spin_box property on the editor to get the bug.
Execute the project to see that it works fine on projects

(Also sorry if I messed up something, I'm new to GitHub)

**Comment by KoBeWi** [comment] 2022-07-09 20:34
Sounds like duplicate of #58609
Alt+Tabbing (sometimes twice) will fix the focus problems.

**Closed by KoBeWi** 2022-07-09 20:34 UTC
