### ISSUE TITLE
Deleted and recreated external script becomes unnamed and then built-in

### ISSUE THREAD

**Issue by headkase** [godotengine/godot#4892] opened 2016-05-29 22:54 UTC
**Operating system or device - Godot version:**

Windows 10 Home 64-bit  Godot 2.0.3 Stable Official 64-bit

**Issue description** (what happened, and what was expected):

Script became unnamed and also built-in.

**Steps to reproduce:**

See video linked on Godot Facebook Page:

https://www.facebook.com/groups/godotengine/permalink/782418088561454/

**Link to minimal example project** (optional but very welcome):

**Comment by headkase** [comment] 2016-05-29 22:58
Here is the project post-error:

[Test2.zip](https://github.com/godotengine/godot/files/288595/Test2.zip)

**Comment by neikeq** [comment] 2016-05-29 23:07
Here is the video for those who don't use Facebook: https://www.youtube.com/watch?v=dLeaiDYaRxI

**Comment by reduz** [comment] 2016-06-12 13:31
I think I fixed this a few days ago, does it still happen?

**Comment by headkase** [comment] 2016-06-12 22:30
Here is an updated video: https://www.youtube.com/watch?v=LOI-t2oWu3M

The unnamed script remains but you can get rid of it now.  Also, if you delete the script from the file-system and then save the scene before you clear the script from the sprite node then the script becomes built-in.  I'm not sure if that is intended behavior or not.

**Comment by reduz** [comment] 2016-06-14 01:18
Yeah, now when an object is deleted, the reference to the file is lost, but the resource will not be erased. It just becomes built-in.  This is intended behavior, so closing this.

**Closed by reduz** 2016-06-14 01:18 UTC
Labels: bug, topic:editor
