### ISSUE TITLE
SSR still don't work

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#51134] opened 2021-08-01 06:12 UTC
### Godot version

4.0.dev (007b877cb)

### System information

Windows 10, Vulkan Clustered, RTX 3060 Ti / GTX 1650 ti

### Issue description

On my pc and laptop enabling ss reflections causes error spam in the console
![Screenshot_8](https://user-images.githubusercontent.com/54563399/127761230-b1e7465b-34c5-4a1f-80a5-0fc4c4b96b2a.png)
![Screenshot_9](https://user-images.githubusercontent.com/54563399/127761260-650d7d69-83be-4d37-9abc-47f1d7520c66.png)

### Steps to reproduce

Enable ss reflections.

### Minimal reproduction project

https://github.com/Calinou/godot-sponza-4

**Comment by Calinou** [comment] 2021-08-01 14:35
Duplicate of https://github.com/godotengine/godot/issues/50151.

**Closed by Calinou** 2021-08-01 14:35 UTC
Labels: bug, topic:rendering
