### ISSUE TITLE
binaries don't work on fedora

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3547] opened 2016-02-02 07:48 UTC
If I download Godot from the website it won't run. It will complain that libssl and libcrypto are missing. 
```
error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```
and a similar error for libcrypto.
Now I believe this is a ancient issue that exists for whatever reason and no one has got a good solution for it so far.

The libs are there and installed but the naming is different and I guess the versions are different I tried to work around it by creating symlinks, and what not, but without success.

I suggest we just upload binaries that were built on fedora for fedora users. because even if we found a way to work around it the whole download and run without installation thing will lose its meaning.

I can build and send the binaries, just tell me which commit to checkout to.

**Comment by akien-mga** [comment] 2016-02-02 08:07
Thanks for the report. It's a duplicate of #1391.

**Closed by akien-mga** 2016-02-02 08:07 UTC
