### ISSUE TITLE
Godot crashes in GLES2  rendering

### ISSUE THREAD

**Issue by BrockGod** [godotengine/godot#26659] opened 2019-03-05 20:24 UTC
**Godot version:** 3.1  Beta 8/9/10/11

**OS/device including version:** Windows 10

**Issue description:** Godot crashes when change or create GLES2 proyect.

**Steps to reproduce:** -Open Godot 3.1, create new proyect in GLES2 or change existen proyect to GLES2. and godot crashes when open this proyect.
[Nuevo proyecto de juego.zip](https://github.com/godotengine/godot/files/2932699/Nuevo.proyecto.de.juego.zip)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-03-05 20:42
What graphics card and driver do you have?

**Comment by BrockGod** [comment] 2019-03-05 20:45
AMD R7 1GB Drivers ver 18.12.2 (graphic card integranted) 3.2 Ghz
8GB Ram

**Comment by ElMarck** [comment] 2019-03-05 21:09
I have the same problem, I can not open or create any project with GLES2 in windows 8.1.
Until beta 7 everything worked fine, so I don't know if it's my graphics card or my drivers.
With beta 11 I register this error if I open it normally:
[error_godot.png](https://github.com/ElMarck/personal/blob/master/error_godot.png)

and when I open the editor directly from the windows cmd:
[error_godot_ed.png](https://github.com/ElMarck/personal/blob/master/error_godot_ed.png)

**Comment by vonflyhighace2** [comment] 2019-03-05 21:30
@BrockGod I would first advise to update to windows 10 since AMD themsleves state they will not support windows 8 with drivers and updates. I believe its a free update from 8 to 10 still since you have a product code. then update the AMD drivers to the latest version. As or right now I would chalk this up to drivers being incompatible with changes to Godot and the state of GLES implementation.

**Comment by akien-mga** [comment] 2019-03-05 22:31
Duplicate of #26500.

**Closed by akien-mga** 2019-03-05 22:31 UTC

**Comment by akien-mga** [comment] 2019-03-05 22:38
> and when I open the editor directly from the windows cmd:
error_godot_ed.png

That one is unrelated, it's because you're using incorrect arguments to start the project. You need to pass `--path` before the path to the project.
