### ISSUE TITLE
ScrollContainers causes flickering/changes scroll value randomly to other ScrollContainer (Android)

### ISSUE THREAD

**Issue by SuzukaDev** [godotengine/godot#61816] opened 2022-06-08 15:51 UTC
### Godot version

3.4.4 estable

### System information

Windows 7 & Android

### Issue description

When adding multiple ScrollContainers in a container, and then scrolling them in a touch screen (does not occur with emulated touch, only on an actual touch screen) causes one ScrollContainer to flicker/change randomly their scroll value, despite not being pressed/touched its rect area.

Video demostration on the minimal reproduction project added:

https://user-images.githubusercontent.com/52723367/172661203-ff0e4fbd-e0dd-4181-8401-9e20e2bdc801.mp4

Further observations:
- This does not occur with emulated touch, only on an actual touch screen. (Tested on Android phone)
- The node that flickers is always the same despite changing the order of the nodes in the scene tree. Changing them produce the flickering always on the same ScrollContainer (Top Left in the video):
![ignores order](https://user-images.githubusercontent.com/52723367/172660139-973340d9-2290-42b9-8a66-6d375b438f07.png)

- The flicker only seems to happen when **scrolling to the right (moving the finger to the left)**. Scrolling to the other direction never triggers the flickering.

The issue may be related with https://github.com/godotengine/godot/issues/45402
(I have opened a different issue since in this case, the flicker **happens with any deadzone value** on the ScrollContainer). Leaving the deadzone to 0 (as default) or to a higher value doesn't seem to alter the effect.

### Steps to reproduce

- Create any kind of containers (tested with SplitContainers and HBoxContainers).
- Add some ScrollContainers as a child.
- Add some childs to the scroll containers and make it exceed the size of the containers, in order to allow scrolling.
- Run the project on mobile (with one-click deploy) and scroll on 

### Minimal reproduction project

[SplitContainer_Scroll_Issue.zip](https://github.com/godotengine/godot/files/8863182/SplitContainer_Scroll_Issue.zip)

**Comment by madmiraal** [comment] 2022-06-16 18:41
Duplicate of or related to #53619?

**Comment by SuzukaDev** [comment] 2022-06-17 17:39
@madmiraal I think is the same issue, I was able to reproduce it and is basically the same bug.
(Sorry I didnt saw it when searching the issues)

---
Also, an updated workaround (in my first solution I only considered HScrollBars)

```
extends Node
# Add this as a child of a ScrollContainer as a workaround for the issue:
# https://github.com/godotengine/godot/issues/61816

enum SCROLL_BAR{Horizontal, Vertical}

export(SCROLL_BAR) var scrollbar_to_lock = SCROLL_BAR.Horizontal 

var _scroll_disabled:bool = true
var _previous_scrollbar_value:float = 0.0
var _scrollbar

onready var _scroll_container:ScrollContainer = get_parent()


func _ready():
	_scroll_container.connect("scroll_started", self, "_on_scroll_started")
	_scroll_container.connect("scroll_ended", self, "_on_scroll_ended")
	for c in _scroll_container.get_children():
		if (c is HScrollBar and scrollbar_to_lock == SCROLL_BAR.Horizontal) or (c is VScrollBar and scrollbar_to_lock == SCROLL_BAR.Vertical):
			c.connect("value_changed", self, "_on_scrollbar_changed")
			_scrollbar = _scroll_container.get_h_scrollbar() if c is HScrollBar else _scroll_container.get_v_scrollbar()


func _on_scroll_started() -> void:
	_scroll_disabled = false


func _on_scroll_ended() -> void:
	_scroll_disabled = true
	_previous_scrollbar_value = _scrollbar.value


func _on_scrollbar_changed(_value:float) -> void:
	if _scroll_disabled:
		_scrollbar.value = _previous_scrollbar_value

```

**Closed** 2022-06-26 01:48 UTC
Labels: bug, platform:android, topic:input, topic:gui
