### ISSUE TITLE
Crash when attempt to Close Other Scripts From Right Click Drop Down

### ISSUE THREAD

**Issue by Chevifier** [godotengine/godot#63061] opened 2022-07-16 06:44 UTC
### Godot version

4.0 dev Alpha 12

### System information

Linux, Ubuntu 22.04 LTS

### Issue description

[https://youtu.be/0ioEK-o6NcA](https://youtu.be/0ioEK-o6NcA)

Crash occurs when I attempt to close other tabs.
Note intermittently happens with only a few(3) open.

### Steps to reproduce

1. Open Godot 4 Alpha 12
2. Open plenty of Scripts
3. Right Click any Script in the Scripts list 
4. Select Close Other Tabs

**Comment by Dssdiego** [comment] 2022-07-16 14:22
It doesn't seem to happen on a Windows Machine

Godot version
4.0 dev Alpha 12

System information
Windows 10 Pro (10.0.19044 Build 19044)

https://user-images.githubusercontent.com/7061445/179358751-8c5ac0c1-b2ef-47fe-ba12-1910133687fc.mov

**Comment by Rindbee** [comment] 2022-07-17 03:14
Easier to reproduce when closing unsaved scripts or removing the open script file from FileSystem dock. May be related to #62964.


![1](https://user-images.githubusercontent.com/30386067/179382255-03ff5ca4-52e3-4c27-96cf-9d57bf3747fb.gif)

**Comment by Zylann** [comment] 2022-07-17 20:52
I also get this error everytime I close a script with Ctrl+W:
```
RROR: Condition "!is_inside_tree()" is true.
   at: Control::grab_focus (scene\gui\control.cpp:2532)
```

Call stack:
![image](https://user-images.githubusercontent.com/1311555/179424322-a08b5a1d-2f62-4428-890c-a07310823f01.png)

**Comment by Rindbee** [comment] 2022-07-18 09:09
Removing the current tab control of the `TabContainer` will first remove the corresponding tab from the internal `TabBar`, and if the removed tab is the **current** one, the `tab_changed` signal will be emitted. This causes the `tab_changed` signal to emitted before the tab control is actually removed.

After the `tab_changed` signal is emitted, the control obtained using `get_current_tab` may be the control being deleted. The tab in the `TabBar` has changed, but the tab control in the `TabContainer` has not changed yet.

https://github.com/godotengine/godot/blob/dfc76dc26dc9412b0467131997e6b8ffdbe4ff02/scene/gui/tab_container.cpp#L931

https://github.com/godotengine/godot/blob/dfc76dc26dc9412b0467131997e6b8ffdbe4ff02/scene/gui/tab_container.cpp#L552

https://github.com/godotengine/godot/blob/dfc76dc26dc9412b0467131997e6b8ffdbe4ff02/scene/gui/tab_bar.cpp#L959-L961
https://github.com/godotengine/godot/blob/dfc76dc26dc9412b0467131997e6b8ffdbe4ff02/scene/gui/tab_bar.cpp#L986-L988

https://github.com/godotengine/godot/blob/dfc76dc26dc9412b0467131997e6b8ffdbe4ff02/scene/gui/tab_container.cpp#L461-L464

**Comment by Paulb23** [comment] 2022-07-18 12:10
That backtrack looks familiar, duplicate of #61689

**Closed by Paulb23** 2022-07-18 12:10 UTC
Labels: bug, topic:editor, confirmed, crash
