### ISSUE TITLE
NavigationAgent2D's velocity_computed signal always returns Vector(0, 0) when multiple agents are present (HTML5 only, Desktop works fine)

### ISSUE THREAD

**Issue by thx4nothing** [godotengine/godot#66793] opened 2022-10-03 00:33 UTC
### Godot version

3.5.1

### System information

Windows 10, GLSE3

### Issue description

When exporting the project to HTML5, the two KinematicBody2D agents don't move. In the desktop version, they move without problems.
The velocity_computed signal always returns Vector(0, 0) when multiple agents are present, but only in the HTML5 version of the project.
When removing one agent, or disabling avoidance and moving them normally, it works in HTML5, too.

I expected it to work in HTML5 just as it works in the desktop version.

### Steps to reproduce

- Create a new Navigation2D Node with a NavigationPolygonInstance.
- Add two or more KinematicBody2D as a child to Navigation2D and give it a NavigationAgent2D with avoidance enabled.
- Add a sprite and collision shape
- Attach a script in which the NavigationAgent2D's velocity_computed function gets connected to a new function move
- The move function has move_and_slide(velocity)
- Set a target location far away and use the agents set_velocity to set the speed according to the agens next location

### Minimal reproduction project

[webtest.zip](https://github.com/godotengine/godot/files/9693867/webtest.zip)

**Comment by smix8** [comment] 2022-10-03 01:32
Not sure about HTML5 builds but the navigation system does not discriminate between builds except for debug.

Avoidance has a high performance cost so it runs in threads. If the navigation system works without avoidance I assume the issue is that your html build has no threads enabled or your test browser has thread problems.

**Comment by akien-mga** [comment] 2022-10-03 06:38
The default Web export has threads disabled as it's still very cumbersome to host a Web build in a way that satisfies browser security requirements for SharedArrayBuffer.

`NO_THREAD` is defined when threads are disabled, and so the code should handle it appropriately (either by running on the main thread, or by raising an error if the feature simply doesn't make sense in a non multithreaded build, making the use of the threaded Web export mandatory for avoidance).

In 4.0 we no longer support the `NO_THREADS` option ai this only needs to be changed in 3.x.

**Comment by akien-mga** [comment] 2022-10-03 12:00
Fixed by #66806.

**Closed by akien-mga** 2022-10-03 12:00 UTC
Labels: bug, platform:web, topic:navigation
