### ISSUE TITLE
gdscript: suggested sprite node name obscured by function tooltip

### ISSUE THREAD

**Issue by michaeldesu** [godotengine/godot#1618] opened 2015-04-03 23:09 UTC
When using the gdscript editor, if say you enter a line 

get_node(

you will see the Node get_node( NodePath path) tooltip text, but behind that text, a list of node names appears in purple text, which is very helpful, but the last name item appears directly behind the function tooltip text. Probably the node list prompter should be elevated at least one line up.

**Comment by eska014** [comment] 2015-11-16 21:08
This issue is still valid when typing on the last visible line.

**Comment by akien-mga** [comment] 2016-04-29 08:57
Duplicate of #1261 and fixed by #3910.

**Closed by akien-mga** 2016-04-29 08:57 UTC
Labels: bug, confirmed, topic:editor
