### ISSUE TITLE
“Emulate Touch from Mouse” doesn’t.

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#46172] opened 2021-02-18 13:22 UTC
**Godot version:** 3.2.3.stable

**OS/device including version:**

Windows 10

**Issue description:**

Even if “Emulate Touch from Mouse” is turned on, the debug program sends InputEventMouse instead of touchscreen input events. I plan to support multitouch and gestures in my project, so “Emulate Mouse from Touch” is not an option.

**Steps to reproduce:**
1. Turn on “Emulate Touch from Mouse” and turn off “Emulate Mouse from Touch”.
2. Listen for inputs.

Expected result: No mouse events are heard. Touchscreen tap and drag events may be fired.

Observed result: Mouse events are heard. No touchscreen events are fired.

**Minimal reproduction project:**

I’m not on my computer, and frankly I think the issue is simple enough for a quick look.

**Comment by JapanYoshi** [comment] 2021-02-18 13:23
Tangentially related to #24589, which is about Buttons not reacting to touchscreen tap events at all.

**Comment by naithar** [comment] 2021-02-18 15:05
Not reproducible with simple test project printing input events from both `_input(event):` and `_unhandled_input(event):`.
 I'm getting both `InputEventScreenTouch` and `InputEventScreenDrag` generated from mouse.

`Emulate Touch from Mouse` doesn't remove mouse events - `touch` events are fired alongside `mouse` ones on PC, so logs will be looking like this:
```
[InputEventScreenDrag:2526]
[InputEventMouseMotion:2528]
[InputEventScreenDrag:2532]
[InputEventMouseMotion:2534]
[InputEventScreenTouch:2538]
[InputEventMouseButton:2540]
```

**Comment by JapanYoshi** [comment] 2021-02-19 03:59
I see. But why are mouse events still being fired?

**Comment by naithar** [comment] 2021-02-19 08:06
If you are using mouse they are fired. 
As I previously mentioned `Emulate Touch from Mouse` doesn't prevent that, it just fires touch event additionally to the ones that are fired by default.

**Comment by JapanYoshi** [comment] 2021-02-19 08:50
That just makes it harder to ensure the game is functional on mobile devices that don’t fire mouse click events.

**Comment by naithar** [comment] 2021-02-19 09:10
If you are aiming only for mobile devices, you can probably just remove mouse event processing from `_input`. This way you don’t have to worry about getting inconsistent results on PC vs mobile. 
For most GUI controls to work you will have to enable `Emulate mouse from touch`.

**Comment by JapanYoshi** [comment] 2021-02-19 09:25
Why do GUI elements not work without Emulate Mouse From Touch? Are touchscreens second-rate compared to mice, that they shouldn’t be allowed to activate normal GUI buttons?

Additionally, certain elements, like ScrollContainers, should behave differently with touch controls than with mouse controls: specifically, scrolling should be done by dragging the area on touchscreens, and turning the scroll wheel or dragging the scrollbar on mouse.

**Comment by naithar** [comment] 2021-02-19 10:36
Most GUI elements expect mouse events because that’s what they are processing in `_gui_input`. So you have to enable mouse emulation for them to work.

As for ScrollContainer. I think it works as you described on both mobile (dragging to scroll) and PC (mouse wheel scrolling). At least the code responsible for it didn’t change. But mouse emulation should be enabled anyway. It might not accelerate or decelerate the same way as native, but that’s expected, since Godot uses it’s own gui elements.

**Comment by madmiraal** [comment] 2021-05-24 08:24
Closing, because, as @naithar points out, this is not a bug.

**Closed by madmiraal** 2021-05-24 08:24 UTC
Labels: topic:input

**Comment by JapanYoshi** [comment] 2021-05-24 08:35
> As for ScrollContainer. I think it works as you described on both mobile (dragging to scroll) and PC (mouse wheel scrolling). At least the code responsible for it didn’t change.

Late as heck, sorry, but ScrollContainers do not respond to touch events *at all* when Emulate Mouse from Touch is disabled. They can't be dragged up and down like a mobile scroll container should. And when Emulate Mouse from Touch is enabled, I have to drag my finger on the scrollbar.

**Comment by volzhs** [comment] 2021-05-24 08:48
@JapanYoshi set mouse filter to `Pass` instead of `Stop` for all child nodes inside `ScrollContainer`

**Comment by madmiraal** [comment] 2021-05-24 08:50
@JapanYoshi, the problem with dragging `ScrollContainers` is a separate known issue: #21137.

**Comment by naithar** [comment] 2021-05-24 09:16
> Late as heck, sorry, but ScrollContainers do not respond to touch events _at all_ when Emulate Mouse from Touch is disabled. They can't be dragged up and down like a mobile scroll container should. And when Emulate Mouse from Touch is enabled, I have to drag my finger on the scrollbar.

@JapanYoshi for dragging to work correctly you have to correctly setup `Filter` values (to `Pass` or `Ignore`) for all GUI elements inside `ScrollContainer`. It might require you to also change signals that you use (`released` instead of `pressed` for `Button` for example). 
The issue @madmiraal linked have a better description of the ways to workaround/fix the issue.
