### ISSUE TITLE
Debugger does not highlight lines when stepping into inner classes

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#65486] opened 2022-09-07 16:04 UTC
### Godot version

v4.0.alpha15.official.432b25d36

### System information

Linux

### Issue description

When stepping through code in the debugger, the current line is usually highlighted with a small arrow and by scrolling the line into view. But when stepping into an inner class, this doesn't happen. Instead some errors get printed in the console. The full output when stepping through the attached code snippet:
```
ERROR: Condition "path.is_empty()" is true.
   at: compute_checksums (editor/debugger/debug_adapter/debug_adapter_types.h:70)
ERROR: Resource file not found: res://.
   at: _load (core/io/resource_loader.cpp:226)
hello
ERROR: Condition "path.is_empty()" is true.
   at: compute_checksums (editor/debugger/debug_adapter/debug_adapter_types.h:70)
ERROR: Resource file not found: res://.
   at: _load (core/io/resource_loader.cpp:226)
hello again
goodbye
```

### Steps to reproduce

Run the code below, and step through the code with F11 or the "Step into" button in the debugger panel.

### Minimal reproduction project

```gdscript
extends Node2D

class Example:
	func _init():
		print("hello")
	
	func greet():
		print("hello again")

func _ready():
	breakpoint
	var e = Example.new()
	e.greet()
	# you should be able to step into the above functions with the debugger before reaching this line.
	print("goodbye")
```

**Comment by Chaosus** [comment] 2022-12-10 09:15
Duplicate of https://github.com/godotengine/godot/issues/67439

**Closed by Chaosus** 2022-12-10 09:15 UTC
Labels: bug, topic:gdscript, topic:editor
