### ISSUE TITLE
Problems with other languages

### ISSUE THREAD

**Issue by Yaisis** [godotengine/godot#951] opened 2014-12-09 21:31 UTC
All file paths must use English characters only, also applies to comments in the scripts. When using characters from other languages, errors occur. It would be good to use the default UTF-8 encoding, in order to avoid problems with other languages.

**Comment by akien-mga** [comment] 2015-11-01 12:14
Archiving as this issue is partly a duplicate of other Unicode-related issues (e.g. #531).

The problem about "All file paths must use English characters only, also applies to comments in the scripts." seems more peculiar, but there's not enough info to make anything of it. Please open a new issue just for that if it's still affected you in the current master branch, and add details about how to reproduce the issues, what are the error messages, etc.

**Closed by akien-mga** 2015-11-01 12:14 UTC
