### ISSUE TITLE
LineEdit cursor is sometimes invisible if 2D scaling is below the native resolution

### ISSUE THREAD

**Issue by brianwinterpixel** [godotengine/godot#58133] opened 2022-02-15 08:10 UTC
### Godot version

3.4.2.stable

### System information

Windows 10, GLES3

### Issue description

All text editing controls use a cursor line width of 1 pixel in exported projects. This causes issues when using controls with different scales. This is a common use case when scaling down UI to fit smaller resolution screens.

#### Example:
This LineEdit has rect_scale=(0.9, 0.9)

At some cursor positions, it is visible:
![image](https://user-images.githubusercontent.com/95356449/154017100-b11828e6-0c71-4d57-aa8b-363817305eb2.png)
However, in others, it is always invisible:
![image](https://user-images.githubusercontent.com/95356449/154017210-8910d161-75a1-4f6c-b8d1-eb1a66127739.png)

### Steps to reproduce

See above

### Minimal reproduction project

[lineeditScaleBug.zip](https://github.com/godotengine/godot/files/8067006/lineeditScaleBug.zip)

**Comment by Calinou** [comment] 2022-02-15 19:16
> This causes issues when using controls with different scales. This is a common use case when scaling down UI to fit smaller resolution screens.

Control scaling should only be used for animation purposes, as it breaks down in many situations (input handling, containers, …). Do *not* rely on Control scaling for multiple resolutions. Use Godot's built-in support for [multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) instead, which supports specifying a custom scale factor since Godot 3.4.

**Comment by brianwinterpixel** [comment] 2022-02-15 20:25
In our project we don't explicitly scale down nodes, but our base resolution is set higher than some platforms we deploy to, resulting in them being scaled down by the engine. So perhaps the issue title/description could be improved.

**Comment by Calinou** [comment] 2022-02-15 20:55
To my knowledge, this automatic scaling can't be easily detected on the node's size, so I'm not sure what could be done (other than defaulting the caret width to 2).

**Comment by jasonwinterpixel** [comment] 2022-02-16 12:20
Solution is probably allowing users to set the caret width in theme properties.

**Comment by Calinou** [comment] 2023-07-21 01:08
- Duplicate of https://github.com/godotengine/godot/issues/24207 (same cause).

**Closed by Calinou** 2023-07-21 01:08 UTC
Labels: bug, topic:rendering, topic:gui
