### ISSUE TITLE
Export category/group/subgroup with base class name incompatible with that class `new`

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#80920] opened 2023-08-23 08:18 UTC
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

Create an export category/group/subgroup with a name that coincides with a base class and then try to instantiate one instance of that class.

### Steps to reproduce

Just this:
```
extends Control

@export_category("Label")
#@export_group("Label")
#@export_subgroup("Label")
@export var text: String

var label: Label


func _ready():
	label = Label.new()
	label.text = text
```

When I run the code, I get:
```
Invalid call. Nonexistent function 'new' in base 'Nil'.
```

My temporal solution is to do `@export_category("Label_")` or similar.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12416886/project.zip)

**Comment by dalexeev** [comment] 2023-08-23 11:31
* Duplicate of #73843.
* Fixed by #78254 for future 4.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-08-23 11:31 UTC
