### ISSUE TITLE
get_overlapping_bodies gives outdated results

### ISSUE THREAD

**Issue by cosarara97** [godotengine/godot#8713] opened 2017-05-10 20:18 UTC
**Operating system or device - Godot version:** v2.1.3.stable.official running on arch linux
Happens on android too.

**Issue description:**
The Area2D method get_overlapping_bodies returns outdated results. Calling it twice on the same node positions can give different results.

**Steps to reproduce:**
I started a project with a root node, and inside it a KinematicBody2D that holds a CollisionPolygon2D,
and an Area2D that holds a CollisionShape2D that uses a RectangleShape2D.

I placed the KinematicBody2D outside the Area2D.
The script uses the _fixed_process(delta) callback to do the following:

* Call get_overlapping_bodies() on the Area2D
* Move the KinematicBody2D inside the Area2D using set_pos

I'd expect the get_overlapping_bodies call to return an array with the KinematicBody2D on the 2nd frame. This doesn't happen until the 3rd frame.

**Link to minimal example project:**
[areatest.zip](https://github.com/godotengine/godot/files/991102/areatest.zip)

This could be related to the following question by another user: https://godotengine.org/qa/6822/getting-inaccurate-results-polling-get_overlapping_bodies

**Comment by eon-s** [comment] 2017-05-10 21:01
You won't get instantaneous overlap information from areas that way, using signals is the way to do it, just connect `body_enter` and you will get the overlap report when occurs.

Other way is using the Shape2D methods to check instant overlaps between shapes.

--------------

Duplicate of #2222, I think.

**Comment by cosarara97** [comment] 2017-05-10 21:31
Oh, I see. Then I propose some comment be left in the documentation to warn of this gotcha, since I'm not the first one to be bitten by it.

**Comment by eon-s** [comment] 2017-05-10 21:41
@cosarara97 you can open an issue on https://github.com/godotengine/godot-docs to discuss documentation problems about this topic.

**Comment by kubecz3k** [comment] 2018-04-19 18:07
I can see there is now proper mention of this in the docs: http://docs.godotengine.org/en/3.0/classes/class_area.html?highlight=get_overlapping_bodies%20#class-area-get-overlapping-bodies

**Closed by kubecz3k** 2018-04-19 18:07 UTC
Labels: discussion, documentation, topic:physics
