### ISSUE TITLE
Cannot apply multiple diffuse materials in Godot

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#7394] opened 2016-12-29 20:03 UTC
**Operating system or device - Godot version:**
Fedora 25, Godot 2.1.1 (stable)

**Issue description** (what happened, and what was expected):
I am attempting to load a 3D model exported from Blender. The mesh exported just fine but the mesh uses multiple textures, and Godot seems to be lacking a consciousness of which areas are to be applied to the mesh.

**Steps to reproduce:**
I used some simple colors to demonstrate this
![enter image description here][1]

So I apply image textures to it by clicking Material slot > Edit > Textures/Diffuse within the editor. And after the image texture is applied it looks like this:
![enter image description here][2]
So it textured the spoiler correctly but it is not applying to say the windshield because the texture for the windshield is in a different texture. There are multiple slots for materials but loading the other png files in them does not seem to do me much good. Here is a screenshot of what my editor looks like while I am doing this
![enter image description here][3]

  [1]: https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12665/Selection_013.medium.png
  [2]: https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12666/Selection_014.png
  [3]: https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/12667/Selection_012.medium.png

**Comment by bojidar-bg** [comment] 2017-06-14 20:32
Would it be possible to give an example model or project which showcases the issue nicely?

**Comment by Noshyaar** [comment] 2018-04-10 16:08
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:15
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:15 UTC
Labels: enhancement, topic:rendering
