### ISSUE TITLE
Godot's Projects list menu appears instead of running my main scene when trying to play

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot#38705] opened 2020-05-12 22:59 UTC
**Godot version:**
Godot v3.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
I don't know what causes this and why, but "randonly" instead of Godot run my main scene, it opens surprisingly the projects list (the first screen after the splash screen when you open Godot Engine executable).

**Steps to reproduce:**
Again, I don't know what causes this issue, but I know that the Godot Engine uses the elements built-in that we use to create our project, in the GUI itself, so something is overriding the default load, I think.

**Minimal reproduction project:**

**Comment by nathanfranke** [comment] 2020-05-12 23:22
I've had this issue before, not sure what the solution was. Can you give us a reproduction project? If you are working on a big project, back it up (carefully) and delete things until the issue is fixed.

**Comment by ghsoares** [comment] 2020-05-12 23:29
@nathanfranke Hello, I can't give a reproduction project because I don't know which expecific configurations cause this and until now, it appears to be random (maybe some wrong memory-access like issue?), and the only project that I have which causes this issue is not possible to share for now...
And even that this is happening, I don't think that can potentially corrupt my project or something, but I will make a backup to be safe.

**Comment by KoBeWi** [comment] 2020-05-12 23:34
Does anything show up in the console? (the system one, not inside Godot)

**Comment by ghsoares** [comment] 2020-05-12 23:38
@KoBeWi In both system and in-engine console appears the message when you open the Godot Engine:
"
Godot Engine v3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: [Your Graphics Card here]
"

It behaves like I opened the Godot Engine inside the Godot Engine, so maybe if I'm unlucky, I can run Godot Engine inside Godot Engine inside Godot Engine.

**Comment by ghsoares** [comment] 2020-05-12 23:42
One addition that I didn't mentioned: if I select a project from the opened list and edit it, it will open the project window normally as it should (or not) be, but as the "main scene" (the Project List that opened instead of the real main scene) closed to open the editing project window, the first Project window detects as the game has closed (So it behaves exactly as it was my game).

**Comment by ghsoares** [comment] 2020-05-12 23:42
So, to resume: Sometimes the engine opens the engine instead of my project's main scene

**Comment by mhilbrunner** [comment] 2020-05-13 00:15
Likely linked to https://github.com/godotengine/godot/issues/28036 - I'll try to finally submit my fix for that. :)

**Comment by mhilbrunner** [comment] 2020-05-13 00:16
I'm closing this as a duplicate of the above mentioned issue https://github.com/godotengine/godot/issues/28036 for now. If we fix that one and this still persists, please let us know. For now, please follow that issue for updates.

**Closed by mhilbrunner** 2020-05-13 00:16 UTC

**Comment by ghsoares** [comment] 2020-05-13 00:18
@mhilbrunner Understood!
