### ISSUE TITLE
RichTextLabel can't clear bbcode text nor empty string

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#35368] opened 2020-01-20 16:58 UTC
**Godot version:**
3.1.2 Stable
**OS/device including version:**
Windows
**Issue description:**
![2020-01-20_235333](https://user-images.githubusercontent.com/34160378/72744553-5e5ba980-3be0-11ea-8487-c448f02b03f0.png)
![2020-01-20_235219](https://user-images.githubusercontent.com/34160378/72744587-6a476b80-3be0-11ea-8988-9f3f3cd03cb4.png)
![2020-01-20_235227](https://user-images.githubusercontent.com/34160378/72744591-6ca9c580-3be0-11ea-9359-0b7015e9d1cd.png)

Look at above, the text in RichTextLabel wasn't disappear from (1 -> 0), it just voer-write to it. I have try empty it "" or using .clear() but none of them worked

**Comment by dankan1890** [comment] 2020-01-21 08:14
Try `set_bbcode()`.

**Comment by rieniter** [comment] 2020-01-21 13:06
> Try `set_bbcode()`.

thank you
Edited: i called that script function from other file through instance node, that why i overwrite it, i tried called directly and it work fine

**Comment by KoBeWi** [comment] 2020-03-05 13:25
What are the exact steps to reproduce this? (project would be useful too)
Or is this resolved?

**Comment by Ydjeen** [comment] 2020-03-10 10:48
@KoBeWi to reproduce it you could write two words using the `centered` BBCode in a small RichTextLabel. The first one should be short, the second one - long.
![RTL_centered_owerwrite](https://user-images.githubusercontent.com/6872975/76305113-d41cf100-62c4-11ea-83e8-d0ad8b1eca94.gif)
[BrokenRichTextLabel.zip](https://github.com/godotengine/godot/files/4311879/BrokenRichTextLabel.zip)

**Comment by KoBeWi** [comment] 2020-03-10 12:07
@Ydjeen That looks like a different issue tho.

**Comment by Ydjeen** [comment] 2020-03-10 12:38
@KoBeWi my bad, it actually is.

**Comment by HaSa1002** [comment] 2020-05-29 16:16
@rieniter can you please provide an example or a minimal reproduction project, how to reproduce the issue as kobewi already asked you?

**Comment by Calinou** [comment] 2020-06-06 23:38
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.

**Closed by Calinou** 2020-06-06 23:38 UTC
Labels: bug, topic:gui
