### ISSUE TITLE
AnimationTree.tree_root.get_child_by_name(String) gives "non existing method error"

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#63759] opened 2022-08-01 05:31 UTC
### Godot version

3.5 RC7

### System information

Windows 10

### Issue description

As in the documentation, AnimationTree.tree_root should return an AnimationNode Object, which should have a "get_child_by_name(String)" method. The editor even completes the method for us. However, it gives us an error which says that such method does not exist.

![BugReportAnimationNode](https://user-images.githubusercontent.com/8985409/182078417-412d0eba-67c2-43ab-af92-acf3d73ca877.png)

### Steps to reproduce

Try to run the minimal project.

### Minimal reproduction project

[BugReport_3_5_AnimationNode.zip](https://github.com/godotengine/godot/files/9231157/BugReport_3_5_AnimationNode.zip)

**Comment by TokageItLab** [comment] 2022-08-01 12:33
Duplicate of #62379.

**Closed by TokageItLab** 2022-08-01 12:33 UTC
Labels: bug, topic:animation
