### ISSUE TITLE
Textures is always compressed

### ISSUE THREAD

**Issue by AlofBronco** [godotengine/godot#77302] opened 2023-05-21 10:02 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, 64-bit

### Issue description

The textures is always compressed, and there is no way to fix this (in scene textures uncompressed and works fine, but in other places like game icon or SpriteFrames menu the textures are very blurry)
![image](https://github.com/godotengine/godot/assets/130389810/33f3c35a-0b92-455f-96dd-f159304653ee)
![image](https://github.com/godotengine/godot/assets/130389810/2df3d641-2251-49bf-ad63-9071c5c213c3)

### Steps to reproduce

Create project and put 8x8 or 16x16 textures and set they to the icon or make AnimatedSprite and put the textures in it

### Minimal reproduction project

[dem.zip](https://github.com/godotengine/godot/files/11524225/dem.zip)

**Comment by AThousandShips** [comment] 2023-05-21 10:06
Duplicate of #57550, it's a filtering issue

**Comment by AlofBronco** [comment] 2023-05-21 10:49
And now this is unfixable?

**Comment by AThousandShips** [comment] 2023-05-21 10:53
This is the same issue as another issue that is worked on

**Closed** 2023-05-21 11:39 UTC
Labels: archived

**Comment by Calinou** [comment] 2023-05-21 17:56
- Duplicate of https://github.com/godotengine/godot/issues/74337.
