### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by cpusam** [godotengine/godot#9523] opened 2017-07-06 02:14 UTC
**Operating system or device - Godot version:**
From my unknown users:
Android version: Android 6.0
Device: Y55s (1610)
RAM (MB): 3072
Display size: 720 × 1280
Dpi: 320
Native Platform: armeabi-v7a
OpenGL ES: 3.0
CPU: Qualcomm
CPU: MSM8917

Game made with version 2.1.3

**Issue description:**

```

backtrace:
  native: pc 0000000000c68bf0  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+164)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b6290  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+47664)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c8fd4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+180)
  native: pc 0000000000d73894  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+132)
  native: pc 0000000000c68bac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE+96)
  native: pc 00000000000b0654  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDFunction4callEP10GDInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE+24052)
  native: pc 00000000000c91ac  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance17_ml_call_reversedEP8GDScriptRK10StringNamePPK7Varianti+204)
  native: pc 00000000000c9210  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10GDInstance24call_multilevel_reversedERK10StringNamePPK7Varianti+36)
  native: pc 00000000006358a8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Node2D14_notificationvEib+116)
  native: pc 0000000000d71c50  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object12notificationEib+24)
  native: pc 00000000003e1b4c  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Node9_set_treeEP9SceneTree+92)
  native: pc 00000000003e1acc  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Node18_add_child_nocheckEPS_RK10StringName+88)
  native: pc 00000000003d0da4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN11MethodBind1IP4NodeE4callEP6ObjectPPK7VariantiRNS5_9CallErrorE+152)
  native: pc 0000000000d73958  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE+328)
  native: pc 0000000000cbe3a8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN12MessageQueue14_call_functionEP6ObjectRK10StringNamePK7Variantib+252)
  native: pc 0000000000cbe5e8  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN12MessageQueue5flushEv+180)
  native: pc 0000000000080300  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN4Main9iterationEv+808)
  native: pc 00000000000506d4  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (_ZN10OS_Android17main_loop_iterateEv+20)
  native: pc 000000000005e46c  /data/app/com.algunsnerds.mathtablegame-1/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+3072)
  native: pc 00000000016b9afd  /data/app/com.algunsnerds.mathtablegame-1/oat/arm/base.odex

```

From 20 users I had one bug on the game (that above). Is solvable this kind of bug?

**Steps to reproduce:**
unknown, or maybe just open the game.

**Link to minimal example project:**

**Comment by jjay** [comment] 2017-08-02 16:56
Same thing there. I have same one and one more on emitting signal. I can't reproduce this, and my codebase pretty big for searching issue line by line =/

Is there some safe way to call callback functions (_ready/_enter_tree/_process) without crashing the game?

**Comment by RandomShaper** [comment] 2017-08-15 22:59
@sam-leo, could you provide some context?

By the stack trace, it seems Godot is crashing when a node which has at least 5th generation descendants enters the tree. And it looks as it happens from a deferred call (signal of `_call_deferred()`), but I'm not sure about that. It cold be just the normal scene change flow.

Maybe you can add some `print()`s to pinpoint or at least delimit the point where the game crashes.

**Comment by sam-leo** [comment] 2017-08-16 01:14
@RandomShaper well, I'm not capable to reproduce the error because it happens in my user's devices. In my own device, (android 4.4.2) nothing occurs. The same error happened 4 time in android 5 with 2 users, 1 time in android 6 with one user and 1 time in android 4.4 with one user. This from 9 july until now.

**Comment by jahd2602** [comment] 2019-05-06 22:37
This is still happening in 3.1.1-stable.

**Comment by KoBeWi** [comment] 2020-07-08 00:17
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 00:21
Closing due to no reply. Please comment if you can still reproduce in 3.2.3+.

**Closed by KoBeWi** 2020-09-28 00:21 UTC
Labels: bug, platform:android

**Comment by maxiproduksiyon585** [comment] 2020-12-28 21:09
I am using Godot version 3.2.3. Below are the crash messages of the game from a few users who have installed my game in the Google Play store.

What exactly does this problem occur and is there a solution? Thank you.


I am using Godot version 3.2.3. Below are the crash messages of the game from a few users who have installed my game in the Google Play store.

What exactly does this problem occur and is there a solution? Thank you.

Me, my friends, and a lot of Godot users tested my game. We could not find the problem.

my game:
[https://play.google.com/store/apps/details?id=com.maxi.savethepuka](https://play.google.com/store/apps/details?id=com.maxi.savethepuka)

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.maxi.savethepuka <<<

backtrace:
  #00  pc 00000000007152b0  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000715280  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000715280  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000715280  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000714974  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000713174  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 00000000012a5608  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000001343c34  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 000000000029bd58  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000273210  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 00000000012a5504  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 000000000129d40c  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 000000000129d700  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000736294  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 00000000000bca70  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000084250  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+228)
  #00  pc 0000000000c4d545  /data/app/com.maxi.savethepuka-1/oat/arm/base.odex (offset 0x944000)`
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.maxi.savethepuka <<<

backtrace:
  #00  pc 000000000004276c  /system/lib/libc.so (tgkill+12)
  #00  pc 0000000000040379  /system/lib/libc.so (pthread_kill+32)
  #00  pc 000000000001ca9b  /system/lib/libc.so (raise+10)
  #00  pc 0000000000019d19  /system/lib/libc.so (__libc_android_abort+34)
  #00  pc 000000000001755c  /system/lib/libc.so (abort+4)
  #00  pc 000000000001b6af  /system/lib/libc.so (__libc_fatal+16)
  #00  pc 0000000000019da1  /system/lib/libc.so (__assert2+20)
  #00  pc 00000000000645cb  /data/app/com.maxi.savethepuka-1/lib/arm/libc++_shared.so
  #00  pc 000000000006cc35  /data/app/com.maxi.savethepuka-1/lib/arm/libc++_shared.so (__cxa_pure_virtual+8)
  #00  pc 0000000000fb3984  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 00000000000bcabc  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so
  #00  pc 0000000000084250  /data/app/com.maxi.savethepuka-1/lib/arm/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+228)
  #00  pc 0000000000c4d545  /data/app/com.maxi.savethepuka-1/oat/arm/base.odex (offset 0x944000)`
  
  `pid: 0, tid: 0 >>> com.maxi.savethepuka <<<

backtrace:
  #00  pc 0000000000dd733c  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/lib/arm64/libgodot_android.so
  #00  pc 0000000000ddd584  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/lib/arm64/libgodot_android.so
  #00  pc 0000000000183940  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/lib/arm64/libgodot_android.so
  #00  pc 0000000000155434  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/lib/arm64/libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+184)
  #00  pc 00000000000351b0  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/oat/arm64/base.odex (art_jni_trampoline+144)
  #00  pc 000000000005be6c  /data/app/com.maxi.savethepuka-6VVqlW2vJb8tcbx-CRmUQQ==/oat/arm64/base.odex (org.godotengine.godot.GodotRenderer.onDrawFrame+92)
  #00  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 000000000014606c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #00  pc 00000000002e0cd0  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #00  pc 00000000002dbfb0  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912)
  #00  pc 000000000059b87c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+868)
  #00  pc 0000000000131a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #00  pc 0000000000330c66  /system/framework/framework.jar (android.opengl.GLSurfaceView$GLThread.guardedRun+1086)
  #00  pc 000000000059c780  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
  #00  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #00  pc 0000000000331260  /system/framework/framework.jar (android.opengl.GLSurfaceView$GLThread.run+48)
  #00  pc 00000000002b191c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.18252570399552585066)+240)
  #00  pc 000000000058b6e8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
  #00  pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #00  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 000000000014606c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #00  pc 00000000004ab72c  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #00  pc 00000000004ac7c0  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #00  pc 00000000004ecb00  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #00  pc 00000000000e28c0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #00  pc 000000000008503c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)`

**Comment by Calinou** [comment] 2020-12-28 21:30
@maxiproduksiyon585 Unfortunately, without an accurate backtrace on the Godot side, there's nothing we can do about this.

**Comment by maxiproduksiyon585** [comment] 2020-12-28 21:43
Thank you for the information. I'm using Gles2. Because my video card isn't running Gles3 now. I haven't had a chance to use these phones where my game crashes.

**Comment by RandomShaper** [comment] 2020-12-29 11:30
At some point we may benefit from adding to the build system the ability to output a symbols file. Google Play is able to provide a symbolicated stack trace in the crashes section if such file is provided together with the APK.

**Comment by maxiproduksiyon585** [comment] 2020-12-31 04:15
Thanks
