### ISSUE TITLE
Crash when opening "Asset Library"

### ISSUE THREAD

**Issue by julroy67** [godotengine/godot#19759] opened 2018-06-25 03:28 UTC
**Godot version:**
3.0.3 (flatpak)

**OS/device including version:**
Linux (Archlinux)
Intel HD Graphics 4400
Mesa 18.1.2

**Issue description:**
Godot always crashes a few seconds after opening the "Asset Library".

**Steps to reproduce:**
1. Launch Godot
2. Open "Asset Library"
3. Wait a few seconds for crash to happen

**Stacktrace:**
```
initia@initia ~ flatpak run -d org.godotengine.Godot
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Haswell Mobile 
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
ERROR: _png_error_function: Not a PNG file
   At: drivers/png/image_loader_png.cpp:62.
libpng error: Not a PNG file
ERROR: _load_image: PNG Corrupted
   At: drivers/png/image_loader_png.cpp:94.
ERROR: _load_mem_png: Condition ' err ' is true. returned: Ref<Image>()
   At: drivers/png/image_loader_png.cpp:252.
ERROR: copy_internals_from: Condition ' p_image.is_null() ' is true.
   At: core/image.h:327.
ERROR: _jpegd_mem_loader_func: Couldn't initialize ImageLoaderJPG with the given resource.
   At: modules/jpg/image_loader_jpegd.cpp:125.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/libc.so.6() [0x31308330b0] (??:0)
[1] /lib/libc.so.6() [0x31308330b0] (??:0)
[2] /lib/libcrypto.so.1.0.2(X509_subject_name_cmp+0xa) [0x3131554a0a] (??:0)
[2] /lib/libcrypto.so.1.0.2(X509_subject_name_cmp+0xa) [0x3131554a0a] (??:0)
[3] /lib/libcrypto.so.1.0.2(OBJ_bsearch_ex_+0x7a) [0x31314719ea] (??:0)
[3] /lib/libcrypto.so.1.0.2(OBJ_bsearch_ex_+0x7a) [0x31314719ea] (??:0)
[4] /lib/libcrypto.so.1.0.2() [0x313151ac79] (??:0)
[4] /lib/libcrypto.so.1.0.2() [0x313151ac79] (??:0)
[5] /lib/libcrypto.so.1.0.2(X509_OBJECT_retrieve_match+0x27) [0x313155c577] (??:0)
[5] /lib/libcrypto.so.1.0.2(X509_OBJECT_retrieve_match+0x27) [0x313155c577] (??:0)
[6] /lib/libcrypto.so.1.0.2(X509_STORE_add_cert+0x78) [0x313155c6d8] (??:0)
[6] /lib/libcrypto.so.1.0.2(X509_STORE_add_cert+0x78) [0x313155c6d8] (??:0)
[7] /app/bin/godot-bin() [0x5ad1ad] (/run/build/godot-tools/modules/openssl/stream_peer_openssl.cpp:328 (discriminator 3))
[7] /app/bin/godot-bin() [0x5ad1ad] (/run/build/godot-tools/modules/openssl/stream_peer_openssl.cpp:328 (discriminator 3))
[8] /app/bin/godot-bin() [0x201f067] (/run/build/godot-tools/core/io/http_client.cpp:301 (discriminator 2))
[8] /app/bin/godot-bin() [0x201f067] (/run/build/godot-tools/core/io/http_client.cpp:301 (discriminator 2))
[9] /app/bin/godot-bin() [0x11e2ad8] (/run/build/godot-tools/scene/main/http_request.cpp:?)
[9] /app/bin/godot-bin() [0x11e2ad8] (/run/build/godot-tools/scene/main/http_request.cpp:?)
[10] /app/bin/godot-bin() [0x11e29b7] (/run/build/godot-tools/scene/main/http_request.cpp:165)
[10] /app/bin/godot-bin() [0x11e29b7] (/run/build/godot-tools/scene/main/http_request.cpp:165)
[11] /app/bin/godot-bin() [0x936360] (/run/build/godot-tools/drivers/unix/thread_posix.cpp:72)
[11] /app/bin/godot-bin() [0x936360] (/run/build/godot-tools/drivers/unix/thread_posix.cpp:72)
[12] /lib/libpthread.so.0(+0x3131007444) [0x7fbfa01c0444] (??:0)
[12] /lib/libpthread.so.0(+0x3131007444) [0x7fbfa01c0444] (??:0)
[13] /lib/libc.so.6(clone+0x5f) [0x31308e827f] (??:0)
-- END OF BACKTRACE --
/app/bin/godot: line 3:     4 Aborted                 (core dumped) /app/bin/godot-bin
```

**Comment by vnen** [comment] 2018-06-25 03:31
Duplicate of 19336

This is already fixed in 3.0.4. Ask your provider to update the package.

**Closed by vnen** 2018-06-25 03:31 UTC
