### ISSUE TITLE
Unexpected --version output from Blender binary

### ISSUE THREAD

**Issue by bluelightzero** [godotengine/godot#87744] opened 2024-01-30 16:36 UTC
### Tested versions

Steam version of Godot v4.2.1.stable.official [b09f793f5]

Tested with:

 - Blender 4.0.2 (in /bin)
 - Blender 4.0.2 (in /usr/bin)
 - Blender 3.6.8 (from blender.org)
 - Blender 4.0.2 (from blender.org)

### System information

Godot v4.2.1.stable - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (RADV NAVI10) () - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/4492982/f2515507-d85a-499c-ad30-9697c51bf2da)

Output of `blender --version`:

```
Blender 4.0.2
	build date: 2023-12-10
	build time: 00:00:00
	build commit date: 1970-01-01
	build commit time: 00:00
	build hash: unknown
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Werror=implicit-function-declaration -Wstrict-prototypes -Werror=return-type -Werror=vla -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wno-stringop-overread -Wno-stringop-overflow -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wimplicit-fallthrough=5 -Wno-error=unused-but-set-variable -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--as-needed -fopenmp -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wcomma-subscript -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wno-stringop-overread -Wno-stringop-overflow -Wimplicit-fallthrough=5 -Wundef -Wmissing-declarations -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--as-needed -fopenmp -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build link flags:  -Wl,
```

### Steps to reproduce

 - In editor settings: Set Blender 3 Path to either `/bin`, `/usr/bin` or blender.org downloaded `.../blender-3.6.8-linux-x64` folder.

 - In project settings: Enable Blender importing. 

 - Save + Restart

### Minimal reproduction project (MRP)

[BlenderImportTest.zip](https://github.com/godotengine/godot/files/14101437/BlenderImportTest.zip)

**Comment by akien-mga** [comment] 2024-01-30 16:39
CC @godotengine/import @RedMser

**Comment by RedMser** [comment] 2024-01-30 16:51
From what I can tell, since https://github.com/godotengine/godot/pull/85448 was merged, you need to specify the path to the blender executable directly, not just the folder it resides in.

Though I wonder why that's the error message you get, since [there's an error check for failure during execution](https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_scene_importer_blend.cpp#L70). Would be curious to see what the `pipe` string actually contains for you.

**Comment by bluelightzero** [comment] 2024-01-30 16:55
The UI is a folder selector:

![image](https://github.com/godotengine/godot/assets/4492982/42f49aaa-179e-4927-8bc0-aeeeed72cc56)

I can type in the executable manually, but this does not work either and get this error in console output:

`modules/gltf/register_types.cpp:65 - Blend file import is enabled, but the Blender path doesn't point to an accessible directory. Blend files will not be imported.`

**Comment by RedMser** [comment] 2024-01-30 17:05
Ah sorry, #85448 was only merged very recently, so it isn't part of 4.2. In your case, directory seems to be correct indeed.

I assume `/usr/bin/blender --version` returns the same as what you sent in the original report? If that is the case, then I really don't have a proper guess, beyond trying to insert a breakpoint there and see what `pipe` contains (since it seems to be missing the string `"Blender "` which should be printed right at the start).

**Comment by bluelightzero** [comment] 2024-01-30 17:07
`/usr/bin/blender --version` returns:
```
Blender 4.0.2
	build date: 2023-12-10
	build time: 00:00:00
	build commit date: 1970-01-01
	build commit time: 00:00
	build hash: unknown
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Werror=implicit-function-declaration -Wstrict-prototypes -Werror=return-type -Werror=vla -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wno-stringop-overread -Wno-stringop-overflow -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wimplicit-fallthrough=5 -Wno-error=unused-but-set-variable -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--as-needed -fopenmp -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wcomma-subscript -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wno-stringop-overread -Wno-stringop-overflow -Wimplicit-fallthrough=5 -Wundef -Wmissing-declarations -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--as-needed -fopenmp -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build link flags:  -Wl,--version-script='/builddir/build/BUILD/blender-4.0.2/source/creator/symbols_unix.map'
	build system: CMake
```

**Comment by RedMser** [comment] 2024-01-30 17:08
Found a similar issue (duplicate?) with a workaround in comments that you can try: https://github.com/godotengine/godot/issues/81597#issuecomment-1781887232

**Comment by bluelightzero** [comment] 2024-01-30 17:12
This seems to have worked. Thanks

![image](https://github.com/godotengine/godot/assets/4492982/8c4bbb6d-e014-4136-8b6d-2900a0a276cf)

**Comment by RedMser** [comment] 2024-01-30 20:51
Nice to hear! Can you please close this issue, as it seems to be a duplicate of #81597

**Closed** 2024-01-30 20:52 UTC
Labels: bug, topic:import
