### ISSUE TITLE
Properties in project's default Theme affect the editor

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#62428] opened 2022-06-26 12:30 UTC
### Godot version

4.0.alpha10

### System information

Ubuntu 20.04.3 LTS

### Issue description

~~Changing text outline in game's default theme affects the editor itself. An image will explain everything:~~

Changing the game's default theme affects the editor itself in some instances. Example with text outline:

![image](https://user-images.githubusercontent.com/85438892/175813222-1bf54111-b1c4-4568-a601-89c8638d724f.png)

![image](https://user-images.githubusercontent.com/85438892/175813265-d513d984-992b-41bf-be17-ab06dc1f0017.png)

### Steps to reproduce

1. Set a default theme from gui/themes/custom in Project Settings
2. Open that theme
3. Change outline size (or another item, but some don't have an effect)

**Comment by TheDuriel** [comment] 2022-06-26 15:31
> gui/themes/custom

"Intentionally" affects the entire project, including the editor.

It is generally advised to set your theme to the top level control node of your GUI scenes.

**Comment by MewPurPur** [comment] 2022-06-26 15:42
It only happens for constant properties. Here's this not happening for font color:
![image](https://user-images.githubusercontent.com/85438892/175822246-9ab3e0a4-6b52-4896-b32c-0497f6cf2a53.png)

**Comment by TheDuriel** [comment] 2022-06-26 15:59
It **should** be happening for the entire theme, as the entire thing is applied to the editor. So if nothing is happening, then the editor is simply not using those properties.

**Comment by raulsntos** [comment] 2022-06-26 16:33
The editor theme doesn't have a value for every property so it falls back to `gui/themes/custom`. The Button's `font_color` was mentioned, that property is not affected because the theme editor sets it:

https://github.com/godotengine/godot/blob/af694245f51bb09a02812b0e2b5c700bad5a06ca/editor/editor_themes.cpp#L737

Since the `outline_size` property is not set in the theme editor, it falls back to the value found in `gui/themes/custom`.

---

About it being "intentional", I'm not sure if that's the case considering the documentation:

https://github.com/godotengine/godot/blob/af694245f51bb09a02812b0e2b5c700bad5a06ca/doc/classes/ProjectSettings.xml#L619-L621

The way I understand it, the "project" refers to the user's game and not the editor. If it really is intentional it should be properly documented that this setting also affects the editor, but personally I don't find that very useful or intuitive so I'd prefer it if the editor theme is not affected by it.

**Comment by MewPurPur** [comment] 2022-06-26 16:42
I see, I've edited the issue accordingly.

**Comment by Calinou** [comment] 2022-06-26 17:51
Duplicate of https://github.com/godotengine/godot/issues/60930.

**Closed by Calinou** 2022-06-26 17:51 UTC
Labels: bug, topic:editor, topic:gui
