### ISSUE TITLE
Executing get_tree().quit() on the HTML 5 export crash the site, other browser tabs still works.

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot#42783] opened 2020-10-13 21:36 UTC
**Godot version:**
3.2.3

**OS/device including version:**
GTX 1650

**Issue description:**
Executing get_tree().quit() on the HTML 5 export crash the site, other browser tabs still works.

**Comment by Calinou** [comment] 2020-10-13 21:49
This should be implemented in 3.2.3 thanks to https://github.com/godotengine/godot/issues/23010, but it's seems it's not working on your end?

Which browser are you using? Also, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by BracerJack** [comment] 2020-10-14 00:01
Hello Calinou as always :D
I am currently using Firefox developer edition v82.0b6
It really is quite simple, a button with get_tree().quit() attached to the Esc keyboard key, export to HTML 5.
Press it and watch it hang ;p

**Comment by capnm** [comment] 2020-10-14 09:32
> It really is quite simple, a button with get_tree().quit() attached to the Esc keyboard key, export to HTML 5.
Press it and watch it hang ;p

So you actually get what you want. The next step is to close the web-browser tab :wink:

**Comment by Faless** [comment] 2020-11-27 11:17
I'm unable to reproduce this in latest beta.
Can you provide a screenshot of the "crash". I don't really understand what "crash the site" means.

**Comment by Faless** [comment] 2020-12-11 11:20
Closing since there is no reply.
Feel free to open a new issue if you have more details, or comment below (and I'll reopen).

**Closed by Faless** 2020-12-11 11:20 UTC
Labels: bug, needs testing, platform:html5, topic:porting
