### ISSUE TITLE
Shift key not registered on Macs

### ISSUE THREAD

**Issue by And-0** [godotengine/godot#2065] opened 2015-06-10 14:58 UTC
I'm getting reports from Mac users that their shift keys are not being recognized in my Godot game. All other keys work fine but the Shift key is never registered as being pressed, neither in the game nor when rebinding controls in the options menu. The game doesn't seem to notice the player is pressing anything at all.

Issue reported for OSX Mavericks (10.9). Since I don't own a Mac I unfortunately can't do any testing myself but I can contact the players if more information is needed.

**Comment by trollworkout** [comment] 2015-07-20 02:24
i have a mac when i get to this ill let you know. i can tell you right now the ui shift works fine but not sure about the running game.

**Comment by akien-mga** [comment] 2016-05-20 13:43
@trollworkout Did you have the opportunity to check?

Or can anyone reproduce the issue in Godot 2.0.x?

**Comment by trollworkout** [comment] 2016-05-21 00:49
@akien-mga  Still not working

When I try and add a new key Shift by itself is not detected but Shift+any other key works fine. This issue is also present in script. In event if I try to detect Shift nothing happens but if I try to detect Shift+a key using nested ifs all the sudden it works.

**Comment by vnen** [comment] 2016-05-21 01:23
While the issue is valid, there are already #3551 and #3552 which have better info (and maybe they can be merged too).

**Closed by vnen** 2016-05-21 01:23 UTC
Labels: bug, platform:osx, topic:core

**Comment by trollworkout** [comment] 2016-05-21 01:34
@vnen  sure np 👍
