### ISSUE TITLE
Particles2D freezes the game during a few frames when emitting is set to true

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#17263] opened 2018-03-04 20:22 UTC
**Godot version: 3.0.2 stable**

**OS/device including version:**
Ubuntu 17.10 with AMD R5

**Issue description:**
Setting `emitting = true` on a Particles2D node that was never emitting before, freezes the game for a couple of frames.
Affects release builds too.

**Steps to reproduce:**
Set `emitting = true` for the first time on a non emitting Particles2D node while the game is running. 

**Minimal reproduction project:**
[particles-emit-bug.zip](https://github.com/godotengine/godot/files/1778878/particles-emit-bug.zip)

**Comment by Ranoller** [comment] 2018-03-05 23:11
Can´t replicate in Win 7 compiled from master at 3/03/18. Particles works well, no frames skipped.

**Comment by Ranoller** [comment] 2018-03-05 23:23
Ok... preprocess is in seconds... so if your system is not powerfull it can skip frames (5 seconds of preprocessing take time to do, and makes no sense in a particle system that loops in 2 seconds)

**Comment by eon-s** [comment] 2018-03-05 23:44
Preprocessing is in 5 because I was testing it but I think there is an issue about preprocess not working, zero does the same and looks worse on web exports.

And some users seem to be experiencing that on `add_child` too of scenes with a Particles2D node, not only on emission change.

**Comment by Ranoller** [comment] 2018-03-05 23:50
Ok. In win 7 i have not problems. Maybe related to godot-ubuntu or maybe related to gles3 compatibilities... In theory particles in godot 3 are gpu processed. Any gles3 menssage on startup?

**Comment by eon-s** [comment] 2018-03-05 23:52
No error messages, and is on the first time the particles are emitted, maybe the texture/material resource loading is doing something here.

**Comment by Ranoller** [comment] 2018-03-05 23:56
Particles texture should load at the beggining of the scene, if there any freeze should be at start... There is more freezes with instancing other kinds of resources/objects?

**Comment by eon-s** [comment] 2018-03-05 23:56
Well... with no textures is the same, with no particles material there is a barely noticeable effect, I do not know what is doing the particles emit process to cause that...

**Comment by Ranoller** [comment] 2018-03-06 00:01
Are you test recent build? There are a lot of changes...i'm looking for any commit that can do a regesion, but first is good to try master, Can you compile master?

**Comment by eon-s** [comment] 2018-03-06 01:07
The same with master, and I think it is an old thing but I always thought it was related to audio, it can be reproduced with shots (instancing) and coins (emitting toggle) in the 2D platformer demos.

**Comment by travm** [comment] 2018-03-06 01:16
I've actually noticed this in my project as well. I'm running on MacOS Sierra 10.12.6. I haven't had the opportunity to try it on Windows, but I will as soon as I can.

In my usage, I am instancing a "bullet" that has a Particles2D node on it. When that bullet is instanced for the first time, I noticed a few frames of visible stuttering/freeze. Every additional instance of the bullet (and particles) has no stutter/freeze. 

Also, the particles in my case are emitting by default when they are instanced.

**Comment by Ranoller** [comment] 2018-03-06 03:04
Seems like particle material, beeing a resource, is not loaded until particles2D is instanced (make sense with the new redesign) but anyway, a simple material for a particle should not freeze nothing. A test that can be done is make a preload with the particle materials in _init() and see if this aliviate the issue. If preloads fix that, well, then we know that problem is with particles material.

**Comment by travm** [comment] 2018-03-06 03:29
I'm not sure I follow. Do you have a simple code example that I can try out?

**Comment by Ranoller** [comment] 2018-03-06 08:09
Simply save the particles material like a .tres file and write in the script:
```
func _init():
 var xxxxxx = preload("res://xxx/particlesmaterial.tres")
```
(change x with var name and path)

**Comment by travm** [comment] 2018-03-06 13:11
Thanks! I gave this a try and unfortunately, it looks like the issue is still there. Assuming, that the preload and assignment to the variable is all that was necessary in the level script.

In the bullet I'm just using the same .tres file that I am preloading in the level. Can you think of any other ideas of what may be causing it?

**Comment by eon-s** [comment] 2018-03-06 14:30
As I mentioned before, I have tried without texture and without material (where should not work) and the emiting effect is the same, the problem seems to be in Particles2D or VisualServer (which toggles the emitting status).

**Comment by eon-s** [comment] 2018-03-08 23:42
Tested on Windows 10, same hardware and got the same, this is the profiler when I grabbed a coin in the Platformer 2D demo:

![framestuttering](https://user-images.githubusercontent.com/10215987/37182622-f2057296-2310-11e8-840d-bc1ab7c4547b.png)

Something is happening on idle time when particle starts emitting.

**Comment by jaggygames** [comment] 2018-03-22 02:52
I can also reproduce the bug using the 2D platformer demo and picking up a coin. It's present in my own project too ^_^

Godot version: 3.0.2 stable

OS/device including version:
Windows 10

![particle bug](https://user-images.githubusercontent.com/3285214/37748118-29d48280-2db5-11e8-8e12-cb49f7bc3358.PNG)

**Comment by jaggygames** [comment] 2018-03-22 03:03
Using the 2D particle demo, there is noticeable skipping for me. 

I had all other particles emitting apart from the explosion and used a button to set emitting = true during runtime. 

This only seems to happen the first time emitting is set to true.

**Comment by ProbDenis** [comment] 2018-04-17 07:59
I've noticed something similar, but it's not limited to particles. Whenever a material (in my case SpatialMaterial) becomes _visible to the camera for the first time_, there's very short freeze. It only seems to happen once for each material.
Preloading doesn't make any difference, and it's not about instancing. It happens even if the node has already been in the scene tree for a while - as soon as it moves into the camera view or the material becomes visible in some other way, there is that short freeze. Sometimes it's so tiny that you don't notice it, but sometimes it freezes for half a second, which is really distracting in the middle of game. I noticed this both for particle effects and simple meshes. Additional nodes sharing the same materials don't have this issue and everything runs smoothly otherwise.

**Comment by Zireael07** [comment] 2018-04-17 08:29
@ProbDenis: I am seeing the same thing for meshes (SpatialMaterial, not some of my custom shaders).

https://i.imgur.com/whxHUNd.jpg

Big freeze is me turning 180 so that some Chinese lanterns become visible.

Issue went away after I moved the lanterns around so they are visible on game start.

**Comment by Zireael07** [comment] 2018-04-17 09:46
'Idle time' in profiler is generally totally not helpful, it would be nice if such things as shader compilation were noted as such.

Also, isn't there an issue about shader compilation maybe getting done at game start or am I misremembering something? Because those big big stutters are BAD for smooth gameplay :(

**Comment by eon-s** [comment] 2018-04-17 09:52
So it is when some visual node AABB enters the camera?, this should happen with other things as well.

Idle time can not be too helpful but may indicate that something is locking the main thread.

On android this is a several seconds pause.

**Comment by Zireael07** [comment] 2018-04-17 09:54
I'm not on Android so it's not THAT bad but on a Radeon 6630M, this dropped my fps from 25-30 to single digits for a frame or so.

**Comment by eon-s** [comment] 2018-04-17 11:31
If the game needs an extra loading time, it will be fine, but a full pause for the first time a particle is emitted is really bad.

**Comment by reduz** [comment] 2018-09-06 22:01
This will be fixed in 3.2, where Vulkan/Shader Caching can be used.

**Comment by eon-s** [comment] 2018-09-07 13:15
Well, Vulkan won't be an option for mobile and web for a couple of years, I guess that CPU particles will be the only workaround for this.

**Comment by clayjohn** [comment] 2019-06-22 05:14
Good discussion on here, but closing as it is a duplicate of https://github.com/godotengine/godot/issues/13954

**Closed by clayjohn** 2019-06-22 05:14 UTC
Labels: bug, topic:rendering
