### ISSUE TITLE
`RefCounted` does not emit `NOTIFICATION_PREDELETE` after being unreferenced and awaiting to be freed

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#82841] opened 2023-10-05 10:46 UTC
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.113.01) - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

The `RefCounted` class does not emit a notification of PREDELETE when it *should* be deleted.

### Steps to reproduce

```gdscript
class_name test extends RefCounted
func _notification(what):
    if self == null: return
    if what == NOTIFICATION_PREDELETE: print("Queued for deletion!")
```
```gdscript
extends Node
func _ready():
   var r:=test.new()
```

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/12817425/minimal.zip)

**Comment by bitsawer** [comment] 2023-10-05 11:09
This works for me:

```gdscript
class_name test extends RefCounted

var test_value = 5

func _notification(what):
    if what == NOTIFICATION_PREDELETE:
        print("Queued for deletion!")
        print(test_value)

```

Looks like not having any member variables causes `self` to be null during NOTIFICATION_PREDELETE (and possible some other notifications?). You can see the notification even in the original code if you remove the line `if self == null: return`.

**Comment by bitsawer** [comment] 2023-10-05 11:24
After some digging, looks like this is basically a duplicate of https://github.com/godotengine/godot/issues/31166 and https://github.com/godotengine/godot/issues/80834. The same fundamental problem is mentioned there, `self` can be null. Looks like a pretty ancient issue, all the way back from Godot 3.x. Closing this to keep discussion in one (or two) place.

**Closed by bitsawer** 2023-10-05 11:24 UTC
Labels: bug, topic:core, topic:gdscript
