### ISSUE TITLE
Godot logo changes position in splash screen depending on the location of the file browser

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21232] opened 2018-08-20 16:33 UTC
**Godot version:**
3.1 calinou faa49c1

**OS/device including version:**
Ubuntu 18.10 Gnome, GTX 970 proprietary software

**Issue description:**
Depending on the File Manager(checked with Nemo and Nautilus) position, Godot open in different locations. Also splash screen which is opening after choosing project, change position itself.

**Steps to reproduce:**
https://streamable.com/y4qx1

**Comment by KoBeWi** [comment] 2020-07-16 22:40
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

**Comment by Calinou** [comment] 2020-07-17 07:25
(Labeling as `platform:linuxbsd` since the splash screen handling has a lot of OS-specific stuff to it.)

**Comment by KoBeWi** [comment] 2020-09-28 16:25
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:25 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:rendering
