### ISSUE TITLE
C# - Can't use any MSBuild action

### ISSUE THREAD

**Issue by marios8543** [godotengine/godot#73900] opened 2023-02-25 01:27 UTC
### Godot version

3.5.1-.NET

### System information

Windows 11

### Issue description

Using .NET version of Godot 3.5.1 on a fresh installation of Windows 11. Whenever I try to use any action in the MSBuild menu I get the following error:

`platform/windows/os_windows.cpp:2922 - Condition "ret == 0" is true. Returned: ERR_CANT_FORK`

### Steps to reproduce

> Open a project
> select build, rebuild or clear in msbuild menu

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2023-02-25 04:20
Duplicate of https://github.com/godotengine/godot/issues/68335

**Closed by raulsntos** 2023-02-25 04:20 UTC
