### ISSUE TITLE
UI Freezes when tabbing to Z in inspector -> transform 

### ISSUE THREAD

**Issue by rklassen** [godotengine/godot#50598] opened 2021-07-18 23:24 UTC
### Godot version

3.3.2 stable

### System information

Windows 10, 3700X, 1660Ti

### Issue description

If you change the X scale, press tab, change the Y scale, press tab, the UI will freeze. After a few seconds, it will return to normal and you can key-in the Z value.

### Steps to reproduce

1. Select spatial node
2. Change the x scale in inspector
3. Press tab
4. Change y scale
5. Press tab

**Comment by Calinou** [comment] 2021-07-18 23:51
Duplicate of https://github.com/godotengine/godot/issues/34817.

**Closed by Calinou** 2021-07-18 23:51 UTC
