### ISSUE TITLE
Crash on Android with Adreno 305, both GLES2 (with WorldEnvironment) and GLES3 (with MeshInstance)

### ISSUE THREAD

**Issue by bruno-reload** [godotengine/godot#26926] opened 2019-03-11 17:02 UTC
**Godot version:**
RC2

**OS/device including version:**
android 5.1.1
opengl3
cpu armeabi-v7a
chipset msm8610
render adreno (TM) 305

**Issue description:**

I have a problem ADRENO (TM) 305 with from RC2, if I just add worldEnvironment of the game closes without giving explanations, this in GLES2. GLES3 is game closes after the godot splash screen if it has a meshInstance. there is some definitive solution that does not involve the compilation of godot together with the solution presented in essues#12816 [solution](https://github.com/endragor/godot/commit/02b12c98043afa6418e0463204e638d6f435ed0a)

**Steps to reproduce:**
android with render adreno (TM) 305

**Minimal reproduction project:**
add wordlEnvironment node in GLES2

**Comment by akien-mga** [comment] 2019-03-11 17:18
The GLES3 issue likely won't get fixed, issues on Adreno 3xx were the primary reason for implementing a GLES2 backend for those devices.

The GLES2 issue sounds like the same as #26924.

**Comment by akien-mga** [comment] 2019-03-11 19:14
Closing as duplicate of #26924, we can continue debugging there.

**Closed by akien-mga** 2019-03-11 19:14 UTC
Labels: bug, platform:android, topic:rendering
