### ISSUE TITLE
The protagonist of the 2d camera experiences severe shaking

### ISSUE THREAD

**Issue by dream-young-soul** [godotengine/godot#83135] opened 2023-10-11 03:31 UTC
### Godot version

Godot v4.1.2.stable.mono 

### System information

Godot v4.1.2.stable.mono - Windows 10.0.23560 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5009) - 12th Gen Intel(R) Core(TM) i5-12490F (12 Threads)

### Issue description

Regarding this issue, I checked the relevant information. At first I thought it was the official document [Fixing jitter, stutter and input lag](https://docs.godotengine.org/en/stable/tutorials/rendering/jitter_stutter.html#what-is-jitter-stutter-and-input-lag)

[#7774](https://github.com/godotengine/godot-docs/issues/7774), there is another discussion on this topic, but I am not making a pixel game.

until i saw
[#74203](https://github.com/godotengine/godot/issues/74203)
[#77813](https://github.com/godotengine/godot/issues/77813)
I'm not sure why this topic was closed, because I also tried using force_update_scroll() and it didn't work, maybe because I used Tween for character movement?

I tried writing a piece of code using 3.5.3 and found that the character did not jitter. But version 4.x is available. Please see video for details

4.1.2:

https://github.com/godotengine/godot/assets/17066147/dcdc0f44-a2cc-4b5a-bd57-93ca4b7bb73d

3.5.3:

https://github.com/godotengine/godot/assets/17066147/dbaf2ec3-dbab-4a7d-b218-d45449725573

### Steps to reproduce

1. Create a Node2D node
2. Create a Camera2D node
3. Create a CharacterBody2D node, which contains a Sprite2D node and a RemoteTransform2D node. The RemoteTransform2D node [remote_path] points to Camera2d
Create a player.gd script pointing to the CharacterBody2D node
```gdscript
extends CharacterBody2D

var _tween:Tween = null

func_process(delta):
    var speed = Vector2.ZERO
    var s:int = 8
    if Input.is_action_pressed("ui_right"):
        speed.x = s

    if Input.is_action_pressed("ui_left"):
        speed.x = -s

    if Input.is_action_pressed("ui_up"):
        speed.y = -s

    if Input.is_action_pressed("ui_down"):
        speed.y = s

    if speed != Vector2.ZERO:
        #self.position += speed
    if _tween == null or !_tween.is_running():
        _tween = self.create_tween()
        _tween.tween_property(self,"position",self.position + speed,0.02)
```
4. Run

### Minimal reproduction project

[camera2d.zip](https://github.com/godotengine/godot/files/12864479/camera2d.zip)
The example contains two folders, respectively the 3.5.3 and 4.1.2 projects.

**Comment by AThousandShips** [comment] 2023-10-11 13:56
#77813 was closed because it was a duplicate, see https://github.com/godotengine/godot/issues/77813#issuecomment-1577090092

I'd say this is a duplicate of #77813

**Comment by dream-young-soul** [comment] 2023-10-12 03:52
I checked [#77813 (comment)](https://github.com/godotengine/godot/issues/77813#issuecomment-1577090092) carefully. 
Thank you, I have solved this problem. The following is the c# code I added.
```
  
  int move_speed = 50;
  Callable callable = Callable.From<int>((int a) =>
  {
      Camera2D.ForceUpdateScroll();
  }
  );


  this.CreateTween().TweenMethod(callable, 0,100,move_speed);
```

**Closed** 2023-10-12 03:52 UTC
Labels: topic:rendering, topic:2d
