### ISSUE TITLE
Lighting issue on last face of ArrayMesh

### ISSUE THREAD

**Issue by MennoMax** [godotengine/godot#52399] opened 2021-09-04 15:40 UTC
### Godot version

3.4.beta4.official

### System information

Linux Mint 20.1 Cinnamon, GLES3, GLES2, NVIDIA GeForce GTX1060 6GB (470.63.01-0ubuntu0.20.04.1)

### Issue description

In the attached project, I generated a mesh along a Curve3D. On the last surface (as seen on the screenshot below) the lighting seems to be slightly glitched. Removing the affected inner wall section will result in the glitch being present on the top surface instead, which is why I believe that this affects the last surface of the mesh.

![Screenshot from 2021-09-04 17-29-00](https://user-images.githubusercontent.com/12477395/132099915-fb5ef767-333c-4f2d-9246-de58055c7b11.png)

Same Project in Godot 3.3.stable.official:
![Screenshot from 2021-09-04 17-28-25](https://user-images.githubusercontent.com/12477395/132099920-b723d5fb-f1a7-43f6-ac7e-1ee60156aa66.png)

### Steps to reproduce

Run the project, it has a controllable camera with controls as seen in Blender. (Middle Mouse Button to rotate around the camera origin, Shift + Middle Mouse Button to move the cameras origin)

On the last surface, as seen on the screenshots, the lighting issue should be visible.

### Minimal reproduction project

[issue.zip](https://github.com/godotengine/godot/files/7110120/issue.zip)

Edit: The project below contains just the ArrayMesh exported from the generated one above with a camera facing the affected face directly.
[LightIssue.zip](https://github.com/godotengine/godot/files/7110213/LightIssue.zip)

**Comment by Calinou** [comment] 2021-09-04 15:43
This is likely a regression from octahedral compression or the vertex attribute split.

**Comment by MennoMax** [comment] 2021-09-04 17:12
Comparing 3.3 to 3.4, the project I added in my edit seems to have a different issue as shown below (but only in 3.3, so it should still be fine for debugging the 3.4 issue)
Godot 3.3.stable.official:
![Screenshot from 2021-09-04 19-03-34](https://user-images.githubusercontent.com/12477395/132102711-f161c2f0-1c3d-4a2c-9450-a1bb3a4ad8d1.png)
---
3.4.beta4.official
![Screenshot from 2021-09-04 19-04-00](https://user-images.githubusercontent.com/12477395/132102714-fd3263d4-8255-439a-9b12-ab4409484249.png)

**Comment by akien-mga** [comment] 2021-09-16 13:26
CC @The-O-King, @clayjohn, @lawnjelly

**Comment by clayjohn** [comment] 2021-09-17 15:44
I can't reproduce using 3.4-beta4 and running on Windows 10
![Screenshot (23)](https://user-images.githubusercontent.com/16521339/133816530-71c4e7e4-d3d2-43bf-9da8-6d7c51c1e40e.png)

**Comment by MennoMax** [comment] 2021-09-17 17:23
Tested it on Windows myself now - same issue there. So this might be driver or graphics card related, which is weird because it does work in 3.3.

**Comment by Zireael07** [comment] 2021-09-26 07:57
I seem to be seeing the same, but in 4.0:
![Screenshot_20210926_095636](https://user-images.githubusercontent.com/4525388/134799029-6e6ca558-51d5-4f3b-9423-4c78e9986fe6.jpeg)

**Comment by akien-mga** [comment] 2021-09-27 16:41
I can reproduce the issue on Linux with both Intel HD 630 and AMD Radeon RX Vega M, both using Mesa 21.2.2.

The bug is a bit weird when checking different versions though:

- In 3.4 beta 4 and 3.4 beta 5, I have the same as @MennoMax:
![Screenshot_20210927_183951](https://user-images.githubusercontent.com/4701338/134950278-8e4daf19-646b-4759-bf8c-74e6d06a0b10.png)

- In 3.4 beta 3, I have errors and no mesh:
![Screenshot_20210927_184030](https://user-images.githubusercontent.com/4701338/134950366-80a72656-4ecc-4c4f-92f2-90549e595203.png)

- In 3.4 beta 2 and earlier (down to 3.3-stable), I have no errors but a different lighting from @MennoMax:
![Screenshot_20210927_184117](https://user-images.githubusercontent.com/4701338/134950515-462328e7-cadd-4ba5-897a-6eed76775716.png)

**Comment by MennoMax** [comment] 2021-09-27 22:50
@akien-mga The first [minimal project](https://github.com/godotengine/godot/files/7110120/issue.zip) I posted should be more accurate, as the other might contain differences in the way array meshes are imported/exported. I experienced the same issues with the other minimal project as you.

**Comment by The-O-King** [comment] 2021-11-01 16:34
I will try to investigate this on the devices that I have and see if I can reproduce it and find out what exactly is causing this from the octahedral compression side 

In the meantime I have updated #48625 which provides the option to enable/disable octahedral compression (among other compression options) at import time, which should allow you to get around this issue as @akien-mga has noted

**Comment by The-O-King** [comment] 2021-11-08 17:20
Ok so I was able to reproduce this on one of my computers and was able to get a fix in! I tested it locally and things seem to work, if others want to give it a go to confirm that would be great :) #54768 

The issue stemmed from the way I was binding vertex attributes from the buffer to the shader - I was always specifying the vertex attribute as a vec4 and using offsets to specify where in the vertex buffer the data would come from, regardless of whether we actually had 4 components of data (this is specific to octahedral normal/tangents)

But now we specify 2 or 4 components depending on what data is present in the buffer

**Comment by akien-mga** [comment] 2021-11-08 18:44
Fixed by #54768.

**Closed by akien-mga** 2021-11-08 18:44 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:3d
