### ISSUE TITLE
Instanced, locked scenes become unlocked on scene reload

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#47836] opened 2021-04-12 18:51 UTC
**Godot version:**
3.3 RC8

**OS/device including version:**
macOS Big Sur
M1 Mac Mini

**Issue description:**
Instanced scenes that are locked in editor become unlocked upon reopening the scene. This is very frustrating when working with large scenes with lots of instances.

**Steps to reproduce:**
- instance a scene in another scene
- lock the instance
- save, close and reopen the scene

**Comment by akien-mga** [comment] 2021-04-12 19:19
I can confirm the issue. I thought it was a regression but apparently not, the same happens in 3.2.3 and 3.2.

**Comment by akien-mga** [comment] 2021-04-12 19:22
Related to #8322.

**Comment by KoBeWi** [comment] 2021-04-13 13:16
Duplicate of #12838

**Closed by KoBeWi** 2021-04-13 13:16 UTC
Labels: bug, confirmed, topic:editor
