### ISSUE TITLE
Dropdown menu editor bug when hovering on MacOS

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#56927] opened 2022-01-18 23:58 UTC
### Godot version

4.0.dev.20220118

### System information

macOS Monterey - 12.1 - M1 - Vulkan

### Issue description

When hovering any but the first dropdown menu they glitch and the first one is showed. See the gif:
(I'm not pressing anything, just clicking to open the menu and moving the cursor)
![godot-bug](https://user-images.githubusercontent.com/2206700/150037705-351ff2b4-213d-4c6e-a3b3-78183406f889.gif)

This doesn't happen if the window is not at the screen's `0,0` position.

![godot-bug-2](https://user-images.githubusercontent.com/2206700/150037988-c2efa520-86b0-4fc0-bf0a-ca0305092722.gif)

### Steps to reproduce

- Open the Godot editor
- Open the top menu dropdowns
- Hover over the options

**Comment by bruvzg** [comment] 2022-01-19 05:39
Duplicate of #53912, will be fixed by #56825

**Closed** 2022-01-19 09:03 UTC
Labels: bug, platform:macos, topic:porting
