### ISSUE TITLE
Quads flickering in orthogonal view

### ISSUE THREAD

**Issue by drop1down** [godotengine/godot#26879] opened 2019-03-10 19:23 UTC
**Godot version:**
3.0.6 stable

**OS/device including version:**
Win10 64bit
nvidia gtx650ti - fresh driver 419.35 (same problem with 3xx driver)

**Issue description:**
Very basic bug
Flickering quads in Godot-editor / 3D using orthogonal view
near viewport side
not tested in game

**Steps to reproduce:**
Load example and rotate view

**Minimal reproduction project:**
[_flickertest.tscn.txt](https://github.com/godotengine/godot/files/2949916/_flickertest.tscn.txt)

![ezgif-1-278a3ddd15bb](https://user-images.githubusercontent.com/48416452/54090233-42f20200-4372-11e9-8c37-b3603682a416.gif)

**Comment by groud** [comment] 2019-03-10 20:19
Have you tried with 3.1 ?

**Comment by drop1down** [comment] 2019-03-10 21:51
Yes same problem with GL ES 3 / 2

**Comment by qarmin** [comment] 2020-01-29 18:10
Still happens with Godot 3.2

**Comment by clayjohn** [comment] 2020-01-29 18:39
Duplicate of https://github.com/godotengine/godot/issues/18809

**Closed by clayjohn** 2020-01-29 18:39 UTC
Labels: bug, topic:rendering
