### ISSUE TITLE
cant edit or see 2d nodes within a viewport in 3d scene

### ISSUE THREAD

**Issue by thepromaper** [godotengine/godot#50185] opened 2021-07-05 16:29 UTC
### Godot version

3.3.2 stable

### System information

Windows 10

### Issue description

you cant see or edit 2d nodes as son of a viewport in a 3d scene, if used in a viewport texture, its gonna be rendered fine, however you can only edit it by changing the properties in the inspector (scale, move and rotate tools don't work) and there will be nothing visible on screen until you go back to the 3d view.

here is what trying to edit it looks like:
![image](https://user-images.githubusercontent.com/72669769/124499372-7e0a7180-dd83-11eb-9467-9a07ad5191ed.png)
here is what it displays on the sprite3d:
![image](https://user-images.githubusercontent.com/72669769/124499904-68497c00-dd84-11eb-8679-d498c44a5a2b.png)

as you see, the node exists in the viewport texture but not when you try to visually edit it by clicking on a 2d node.

a workaround its to edit the 2d part in its own scene and then instance it, however its clunky to use like that.

### Steps to reproduce

1. create a spatial node as root of a scene
2. add a viewport as child
3. add node2d as son of viewport
4. click on the node2d and try to edit it with the editor move or scale tools or even see it

### Minimal reproduction project

[viewp2d.zip](https://github.com/godotengine/godot/files/6765483/viewp2d.zip)

**Comment by Calinou** [comment] 2021-07-05 20:58
I'm fairly sure this is a duplicate of another issue, but I can't find it right now.

**Comment by KoBeWi** [comment] 2023-03-01 23:40
Duplicate of this #20619 probably.

**Closed by KoBeWi** 2023-03-01 23:40 UTC
Labels: bug, topic:editor, topic:2d
