### ISSUE TITLE
Ubuntu 18.04 Nouveau driver crash on opening project

### ISSUE THREAD

**Issue by TomWor** [godotengine/godot#21889] opened 2018-09-09 07:47 UTC
**Godot version:**
Official 3.0.6 stable

**OS/device including version:**
Ubuntu 18.04 stock version with default Nouveau graphics drivers on Nvidia GTX 970
(Works with proprietary driver)

**Issue description:**
Immediate crash on opening project from the project browser
(in my case the Kinematic Character 3D demo)
It crashes the OS completely, can' t even switch into another tty via F keys, Hardware cursor still working though.
 

**Steps to reproduce:**
Start Godot, open project for editing

**Minimal reproduction project:**
Kinematic Character demo from asset library

**Comment by Zireael07** [comment] 2018-09-09 07:57
Yet another sucky GLES3 drivers, I guess? Try the 3.1 alpha with GLES2 to see if it works.

**Comment by swenner** [comment] 2018-09-16 00:11
@TomWor Consider reporting the bug to Ubuntu or the Nouveau project.

**Comment by mohamedhany4116** [comment] 2018-10-06 09:18
I have got the exact same issue but with Godot 3.1 alpha 
Here is my issue
https://github.com/godotengine/godot/issues/22790

**Comment by Calinou** [comment] 2020-04-25 19:56
Closing, as this is most likely a driver-specific bug. Also, keep in mind Nouveau is usually as stable as the proprietary NVIDIA driver and is more prone to regressions, since it's the fruit of reverse engineering.

**Closed by Calinou** 2020-04-25 19:56 UTC
Labels: bug, topic:rendering
