### ISSUE TITLE
Uning the Connect a Siganl to a Method edit UI does not work with exteranl editor.

### ISSUE THREAD

**Issue by cjpdev** [godotengine/godot#43546] opened 2020-11-14 21:00 UTC
**Godot version:** v3.2.3.stable.mono.offical

**OS/device including version:**
Windows 10

**Issue description:**
When using an external editor (Visual Studio Code). And using the node UI dialog `Connect a Siganl to a Method`  it does not add the method code to the script. However, its does works when using inbuilt editor.

Godot switchs to the external editor, but no code is added.

Also "Got to Method" and "Disconnet" have no effect. If this functionality is not supported. When `Editor Setting to Use External Editor = on' ,  Possbile "Got to Method"  could be disabled. And the UI could prompt you to add/remove the code yourself.

Visual Studio code: version : 1.15.1
godot-tools 1.1.2
Mono Debug 0.16.2

**Steps to reproduce:**
Set the Editor Setting to "Use External Editor = on" 
Add a node to the scene
Add script (c# or GDScript) 
From the node panel select CavasItem hide() and select connect.
From the "Connecting a Siganl to a Method" panel select the Node to connect the signal to.

**Comment by Calinou** [comment] 2020-11-14 21:08
Duplicate of https://github.com/godotengine/godot/issues/41283.

**Closed by Calinou** 2020-11-14 21:08 UTC
