### ISSUE TITLE
Bottom Panel's grows beyond Window Size

### ISSUE THREAD

**Issue by ultimateprogramer** [godotengine/godot#36221] opened 2020-02-14 17:13 UTC
**Godot version:** 3.2

**OS/device including version:** Ubuntu 18.04

**Issue description:**

When you open up the bottom panel in some circumstances, it grows beyond the window size, and the bottom action buttons (Such as Output, Debugger, Audio, etc) become inaccessible because they are below the window's main view port.

**Steps to reproduce:**

* Open up a project (I will use Dodge the creeps)
* Open up the Code Editor as full screen.
* Minimize the Code Editor back to original configuration.
* Open up something a file like `default_bus_layout.tres`
* You will see you cant access items in the Bottom Panel.

**Screenshot**
![editor_screenshot_2020-02-14T201032+0300](https://user-images.githubusercontent.com/177851/74552474-5801e880-4f66-11ea-86fe-ffc8d984c36a.png)

**Comment by KoBeWi** [comment] 2020-02-14 17:28
Duplicate of #26835

**Closed by KoBeWi** 2020-02-14 17:28 UTC

**Comment by ultimateprogramer** [comment] 2020-02-14 18:00
@KoBeWi this also happens sometimes with the Animations tab. Not just the Audio Tab

**Comment by KoBeWi** [comment] 2020-02-14 18:49
Commenting in that issue should be enough, because it's basically the same problem.
