### ISSUE TITLE
Script editor doesn't recognize ".gd" extension

### ISSUE THREAD

**Issue by a-watson** [godotengine/godot#2558] opened 2015-09-30 21:11 UTC
I just built and started using the most recent source on github. I added a node to one of my scenes and attached a new script to it. I created the script by going to the "Script" heading in the node's inspector, selecting "New GDScript", then selecting Edit. When I went to save the script I tried to save it as "myScript.gd", and got an alert from the editor that said "File format requested unknown: gd". Upon further inspection, my script is being saved to memory somewhere because when I quit and reopen the project it's still there, but its being named something like "GDScript (11111)" and not in my project folder anywhere. I can still open my other scripts (all with the ".gd" extension) and edit/save them without any problems at all. I can also create a script by going to the script tab first and setting it's path there. Then I can add it to a node with the Load option without problems.

I'm running ubuntu 14.04 on a 64-bit laptop, if that changes anything.

**Comment by NateWardawg** [comment] 2015-09-30 21:17
Hello, I'm not sure why it wouldn't be saving, but the reason the script still exists when you reopen your project is because it's saved within the scene itself. In the cases where you don't need to use a script outside of a particular scene it's pretty safe to leave it simply saved as a part of that scene.

This is also the case for many other resources such as shaders and materials.

**Comment by vnen** [comment] 2015-09-30 21:48
Yeah, this is a nasty bug indeed, though this is was already reported on #2415. You can save the script using the save button in the Inspector.

@reduz, couldn't you take a look on #2459 to (try to) fix this?

**Comment by a-watson** [comment] 2015-10-01 00:53
@vnen My bad! I must've missed it when I was searching for related bugs. I tried a few different searches and didn't see anything that seemed related.
I guess for now I'll be creating them in the editor directly, until this gets fixed.

**Comment by eska014** [comment] 2015-10-28 19:32
Duplicate of #2415.

**Closed by eska014** 2015-10-28 19:32 UTC
