### ISSUE TITLE
iOS HTML5 Intermittent Crashes

### ISSUE THREAD

**Issue by davidCentervention** [godotengine/godot#39092] opened 2020-05-27 16:07 UTC
**Godot version:**
3.2.1 (Also seems to crash with previous versions as well)

**OS/device including version:**
iPad 5th generation. iOS 13.4.1. Chrome and Safari. HTML5 build using GLES2

**Issue description:**
Using HTML5 with GLES2 on an iPad causes intermittent crashes. It appears to crash about 25% of the time on initial load. Once it is running it runs fine.

I'm having trouble capturing any javascript errors related to this as the ipad stops sending exceptions to the remote debugger when it crashes.

**Steps to reproduce:**
Create a blank Godot project. Set to GLES2. Make an HTML5 build, and try to run 10 times in a row on iPad, it will crash a few times on initial load.

**Minimal reproduction project:**
https://drive.google.com/file/d/1vtCovyApZGjBMS-V2UI3-pBZOcN7XiPK/view?usp=sharing

**Comment by Faless** [comment] 2020-05-28 12:57
Does it ever happen on the first load? Otherwise it might be a memory problem, specifically, browsers seem to have trouble freeing all the webassembly memory when reloading pages, causing errors on multiple reloads. In which case, closing the browser tab and open a new one works.

Just guessing here (I know it happens on some browsers), I don't have an iPad to test it, and I can't do much without having any log.

**Comment by Calinou** [comment] 2020-05-28 13:43
Related to #26554 and #37931.

**Comment by davidCentervention** [comment] 2020-05-28 13:51
It does happen on first load, with a cleared browser cache. If there's other ways to get logging during a crash on mobile, I'm willing to try some alternate ways. I have tried remote debugging but that unfortunately doesn't seem to be sending any exceptions or logging during the crash: https://medium.com/@haroonabbasi/remote-debugging-safari-iphone-ipad-ios-11-on-windows-340b403a9829

**Comment by Calinou** [comment] 2022-05-27 10:24
@davidCentervention Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

**Comment by Calinou** [comment] 2022-07-23 21:47
Closing due to lack of response. Please comment with a minimal reproduction project attached if you can still reproduce this bug. See also https://github.com/godotengine/godot/issues/62445 if running iOS 16.

**Closed by Calinou** 2022-07-23 21:47 UTC
Labels: bug, platform:html5, platform:ios, topic:porting, needs testing, crash
