### ISSUE TITLE
Popupmenu cannot be click when in popup and under other control node

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#48569] opened 2021-05-09 02:25 UTC
**Godot version:**
3.3

**OS/device including version:**
windows 10 professional

**Issue description:**
When in a popup node tree, Popupmenu cannot be click if there is another control node above it

**Steps to reproduce:**
Add a popup then add 2 optionbutton under it,  let the second one below in the tree

**Minimal reproduction project:**
[PopupMenuBug.zip](https://github.com/godotengine/godot/files/6446845/PopupMenuBug.zip)

**Comment by kleonc** [comment] 2021-05-09 07:09
Duplicate of #46325.

**Comment by Calinou** [comment] 2021-05-09 07:19
Closing per @kleonc's comment.

**Closed by Calinou** 2021-05-09 07:19 UTC
Labels: needs testing, topic:gui
