### ISSUE TITLE
Android FileDialog folders not clickable

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#18477] opened 2018-04-28 03:18 UTC
Godot Master

Platform Android

I am not able to open any folder only by writing the path manually in the top lineedit.
Spen and double tab have no effect in the FileDialog.

Has it something to do with permissions or is some feature missing?

**Comment by raymoo** [comment] 2018-05-01 23:05
Duplicate of https://github.com/godotengine/godot/issues/8151

**Closed** 2018-05-02 08:49 UTC
Labels: bug, platform:android, topic:porting
