### ISSUE TITLE
Lights projecting textures?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#20134] opened 2018-07-13 13:42 UTC
I was trying to make my spotlight project a texture onto all the meshes in my 3D scene.

One use case is to add some realism to spotlights by emulating an [IES light](http://www.chocofur.com/creating-ies-lights-blender-and-cycles.html) - in the real world lamps have certian emissive profiles based on the emission angle.

Other use-cases are creating real projectors or translucency projection effects.

I thought I could do this by simply adding a texture to the light material, but there's no such option.
I thought maybe I can do so with a light shader - what I've read on this indicated that it an only work for a selected mesh that has a shader that's "cooperating": 
https://godotengine.org/qa/28084/projected-texture

I wonder if there's a hidden way to do this in Godot so it'll work on all meshes easily, or maybe it could be added in for easier use?

Additional ideas:

Can this work fro Omi lamps too? I guess that'd require a cubemap for projection?
This could lead to some amazing visual effects.

**Comment by Calinou** [comment] 2018-07-13 13:50
Duplicate of https://github.com/godotengine/godot/issues/2002. (It's still not implemented as of 3.0.5.)

**Closed by Calinou** 2018-07-13 13:50 UTC
