### ISSUE TITLE
function 'notification' not exists on JavaClass

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#44932] opened 2021-01-05 13:03 UTC
**Godot version:**
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 750M OpenGL Engine

**OS/device including version:**
MacOS Sierra 10.12.6 fails
Windows 10 is working fine

**Issue description:**
During testing for orphan nodes on my project i had implement an *auto_free* on objects.
I need it for freeing mocked classes to release all dependencies.

Here the code to freeing objects and references
```
static func free_instance(instance :Object):
	if instance != null:
		if not instance is Reference:
			instance.free()
		else:
			instance.notification(Object.NOTIFICATION_PREDELETE)
```
I had an test where iterates over all engine classes and build a mock from it.
After the test is finished i release all mocked objects and only for class *JavaClass* the free fails by an error 
```
Bug, call error: #1431449824
```
This Bug only occurs on MacOS on Windows10 it works without any errors

**Steps to reproduce:**
```
var instance := JavaClass.new()
free_instance(instance)
```

**Minimal reproduction project:**
See steps to reproduce

**Comment by akien-mga** [comment] 2021-01-05 13:12
Duplicate of #44931

**Closed by akien-mga** 2021-01-05 13:12 UTC

**Comment by MikeSchulze** [comment] 2021-01-05 13:19
Ups Sorry, I had a mistake submitting the problem.
