### ISSUE TITLE
Window Resize Crash 3.2.3 RC6

### ISSUE THREAD

**Issue by Mikadini** [godotengine/godot#42004] opened 2020-09-12 09:45 UTC
**Godot version:**
3.2.3 rc6 GLE2

**OS/device including version:**
i7 6700k 4.49ghz
16 gb ram 2133mhz
gtx 1080 with 452.06

**Issue description:**
When I try to change the resize of the game window to test that the aspect ratio is maintained correctly the program crashes. it's a minor bug because you have to do some movement with the mouse and not a single resize but I hope it can help anyway

**Steps to reproduce:**
Create a project with GLES2 set as window size: 90 in height and 160 in width, set 2d in stretch mode and keep in aspect. Try to do an aggressive back and forth resize and it will hang like that

**Minimal reproduction project:**
Project File: 
[Heartbest Mobile Game.zip](https://github.com/godotengine/godot/files/5212492/Heartbest.Mobile.Game.zip)

Screenshot of the error:
<img width="1920" alt="Screenshot error" src="https://user-images.githubusercontent.com/44696452/92992730-5218b980-f4ed-11ea-9f06-07a2fbae78c0.png">

**Comment by Calinou** [comment] 2020-09-12 09:49
Duplicate of https://github.com/godotengine/godot/issues/24702.

**Closed by Calinou** 2020-09-12 09:49 UTC
