### ISSUE TITLE
Custom Resource Array values exported to the inspector show as null on running project

### ISSUE THREAD

**Issue by Kangrew** [godotengine/godot#70552] opened 2022-12-25 12:24 UTC
### Godot version

Godot 4.0 beta 9, Godot 4.0 beta 10 (Pre-Release)

### System information

Windows 10, GLES3, RTX 3060Ti

### Issue description

This is how it is in the inspector. I've assigned the 4 values:
![Inspector](https://user-images.githubusercontent.com/73686440/209467585-960b39a0-67c6-45c1-9af8-1b6e80bbcfb9.png)

But this is what is shown in console when I print the values:
[\<null\>, \<null\>, \<null\>, \<null\>]

One more thing to mention is I gave a setter function that is resizing the array to have a specific size:

```
func _validate_suits(value: Array[SpellSuitData]) -> Array[SpellSuitData]:
	if value.size() != total_suits:
		value.resize(total_suits);
	return value;
```

But even if I remove the setter function, the printed array is empty.

### Steps to reproduce

1. Create an Array of a custom resource and export it to the editor.
2. Assign resources to it.
3. Run the project and print it in the ready function

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-29 21:25
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2022-12-29 21:25 UTC
