### ISSUE TITLE
Viewport as a child of canvas layer doesn't work as intended

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6356] opened 2016-08-31 21:45 UTC
linux x86 godot 2.2 alpha 
Viewport, when in tree, works as a box that renders only things that are in bounds. When having viewport as a child of CanvasLayer node, viewport renders it's children even if they are out of bounds. 
Steps to reproduce: 
Tree: 
CanvasLayer
.- Control
.-- Viewport
.--- Sprite
Switch CanvasLayer to Node and viewport will work. 
Example project:   [Viewport Example.zip](https://github.com/godotengine/godot/files/448339/Viewport.Example.zip) https://www.dropbox.com/s/rcbs55gq6unet27/Viewport%20Example.zip?dl=0 (Thanks YeOldeDM :D )

**Comment by akien-mga** [comment] 2017-02-16 15:21
Is this still valid in the current master branch? Viewport stuff was heavily refactored.

**Comment by ArcFutahito** [comment] 2017-02-21 05:41
I'd test it but on newest build from master: 

/home/godot.x11.tools.64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

In kubuntu 16.10 x64:

Reading state information... Done
libpng16-16 is already the newest version (1.6.25-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by akien-mga** [comment] 2017-02-21 06:16
@ArcFutahito You should tell whoever produces your binaries to build with `builtin_libpng=yes`. Ubuntu should go to hell with its libpng mess (only libpng12 in Ubuntu <= 16.04, the latter being LTS, and then only libpng16 in Ubuntu >= 16.10, that's completely irresponsible).

**Comment by ArcFutahito** [comment] 2017-02-21 06:24
@akien-mga got a build from fixnum. Ok will build manually and tell you results of the test in a couple of days.

**Comment by ArcFutahito** [comment] 2017-02-25 22:26
Issue persists in 3.0, also found this weird bug in 2.1

**Comment by 0nepixel** [comment] 2017-04-14 23:10
Yeap, same here, the bug persist until the current stable version :/

**Comment by MakeGodotGreatAgain** [comment] 2017-07-31 14:24
can confirm this bug still prevalent in 2.1.4 and the latest master

nasty little bug.

**Comment by MakeGodotGreatAgain** [comment] 2017-07-31 15:43
okay, so I found a temporary fix for this if anyone still needs to use their viewport in 2.1

whatever you do, don't have your `viewport node` a child under any `canvas layer` (even if it's a subchild of a subchild of a subchild, etc, etc)

 **what you can do is put your `viewportsprite` node underneath a `canvaslayer` instead**. And you can achieve the same effect. just use `viewportsprite.set_viewport_path` and link it to wherever your viewport node is at.

i just put my viewport node under /root

**Comment by ronroniv** [comment] 2018-05-03 09:50
Since the attention notice for stales issues was posted on a duplicate (#7286)...

This issue is still reproducible in 3.0.3 rc1.

I hope this gets some attention from contributors. I'm currently using a workaround that manually moves viewport relative to camera position. 😂

**Comment by akien-mga** [comment] 2018-07-24 20:45
Duplicate of #6356 and fixed by #20252.

**Closed by akien-mga** 2018-07-24 20:45 UTC
Labels: bug, topic:core
