### ISSUE TITLE
The closing window has different sizes

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#42787] opened 2020-10-14 08:40 UTC
**Godot version:**

3.2.3 mono stable

**OS/device including version:**

win64 home

**Issue description:**

The closing window is shown in different sizes, I can't know what the reason is, sometimes I have gotten a closing window with a considerable horizontal size.
In these two images you can see that they have different sizes although they keep a small size.

![Captura](https://user-images.githubusercontent.com/19652075/95964997-b939ce80-0e09-11eb-8578-8055b6ae9cb3.PNG)
![Captura2](https://user-images.githubusercontent.com/19652075/95965013-bb9c2880-0e09-11eb-84d1-f2b30cdf4f8e.PNG)

**Steps to reproduce:**
Just work with the editor and when you close it look at the size of the closing window.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-10-14 08:52
I don't understand what the problem is exactly.

The two screenshots show the use of different fonts, and thereby it's normal that the dialog widgets change size to accommodate the font that they use.

**Comment by Torguen** [comment] 2020-10-14 09:08
Well sometimes something like this comes up.
![Captura](https://user-images.githubusercontent.com/19652075/95968369-a1fce000-0e0d-11eb-88e0-83fb0c726a9f.PNG)

**Comment by Calinou** [comment] 2020-10-14 12:17
The dialog probably keeps the size of the widest AcceptDialog that was opened during the editor session. I've noticed this issue many times in editor dialogs. It needs to be fixed on a case-by-case basis by setting the dialog's minimum size to `(0, 0)`.

**Comment by Torguen** [comment] 2022-02-16 11:13
This no longer happens in the latest versions.

**Closed** 2022-02-16 11:20 UTC
Labels: bug, topic:editor
