### ISSUE TITLE
ENet "peer_connected" & "connection_succeeded" signals fired on Client after failed Connection to Server with (RefuseNewConnections = true)

### ISSUE THREAD

**Issue by CarterG81** [godotengine/godot#45276] opened 2021-01-18 06:47 UTC
Very simple. Title explains.
Couldn't find duplicate, but I heard there might have been one (known issue on Discord).

**Godot version:**
3.2.3 Mono

**Issue description:**

"peer_connected" & "connection_succeeded" signals fired on Client when attempting to connect to a Server which is has RefuseNewConnections = true.
After some time, "server_disconnected" is then called.

Peer Connected & Connection Success should never be fired.

**Steps to reproduce:**
App1: CreateServer()
App1: RefuseNewConnections = true
App2: CreateClient()

**Comment by Faless** [comment] 2021-01-18 11:35
As far as I understand this is related to ENet.
What `refuse_new_connections` does is resetting the peer as soon as it tries to connect.
It does not send a disconnect message to the client, but disconnects if forcefully via `enet_peer_reset`.
It seems that the response to the connect event is still sent to the client though.
Probably, the ENet `CONNECT` event where we forcibly disconnect the peer, is dispatched after the client has received the ACK.
I'm not sure we can easily solve this with the current ENet API.

**Comment by mhilbrunner** [comment] 2022-01-14 00:41
Yes, this seems an ENet thing - this should be caught by whatever handling the specific game has for timeouts.
Otherwise, there is not much we can do on our side (without hacks). I tend towards not fixing this.

**Comment by mhilbrunner** [comment] 2022-01-14 02:39
Closing as duplicate of https://github.com/godotengine/godot/issues/45276

**Closed by mhilbrunner** 2022-01-14 02:39 UTC
Labels: bug, topic:thirdparty, topic:network
