### ISSUE TITLE
Choosing "Run in Browser" launches a different game when using the default port 8060

### ISSUE THREAD

**Issue by phkeese** [godotengine/godot#76584] opened 2023-04-29 17:31 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

MacOS Ventura 13.1

### Issue description

When launching my game (Game A) from the editor, another project (Game B) is launched, instead of the one I am editing.
There is no mention of that project (Game B) in `~/Library/Application Support/Godot`, other than old project lists.
The launched app (Game B) was developed in Godot 3.5 and exported to web there.
When I change the port for the web server from 8060 to 8080, the currently edited project (Game A) is launched.
There is no mention of the other project (Game B) within the current project (Game A). 
The only similarity they share is the naming of the output directory `build/web/index.html`.

### Steps to reproduce

I have not found a way to reproduce this error in a clean project nor have I found any references to the launched (wrong) project.

### Minimal reproduction project

N/A - Not yet reproduced.

**Comment by Cratesmith** [comment] 2023-05-18 03:29
I"m experiencing this too. 
I've tried deleting every reference to godot from the machine and it still shows the other project. It's like it's holding temporary files somewhere that I don't know about

**Comment by Calinou** [comment] 2023-05-18 04:58
- Duplicate of https://github.com/godotengine/godot/issues/75743.

**Closed by Calinou** 2023-05-18 04:58 UTC
