### ISSUE TITLE
Inspector automatically changes size when selecting node

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#32790] opened 2019-10-13 05:24 UTC
**Godot version:**
3.2 Alpha 2

**OS/device including version:**
Windows 10
**Issue description:**
When selecting the NavigationMeshInstance node - the inspector automatically increases in size.

![InspectorResize](https://user-images.githubusercontent.com/16636969/66711352-1e229a80-ed58-11e9-844e-edd2a92fe8f5.gif)

**Steps to reproduce:**
1) Create NavigationMeshInstance node
2) Create any other node
3) Switch between the two nodes and observe the inspector increase in size - no matter how muxh you bring the inspector out

This is extremely jarring and I haven't noticed it on other nodes as of yet. I double checked my 3.1.1 version and it does not do this.

**Comment by somnivore** [comment] 2019-10-29 18:05
This is also happening when selecting animation keys, when switching between key selected and no key selected (empty inspector.)

**Comment by Calinou** [comment] 2019-11-07 02:12
I can confirm this on commit https://github.com/godotengine/godot/commit/5fb160c7c692c469488f11aca90a36ac3248dfee.

**Comment by Duroxxigar** [comment] 2019-11-07 03:13
![image](https://user-images.githubusercontent.com/16636969/68357202-890a8b80-00e2-11ea-8fc0-27885031b915.png)

Looks like the issue is that there isn't a max allowed number of characters in the node name. Maybe we should chop off after a certain point?

**Comment by fire** [comment] 2019-11-07 03:17
I suggest clipping for display purposes the node name with ellipses.

**Comment by tom-jk** [comment] 2020-08-10 17:10
I believe #34535 was a duplicate of this issue, and was resolved.

To be sure, followed given steps:

Can't reproduce in 3.1.2.stable
Can reproduce in 3.2.alpha0 thru 3.2.rc2
Can't reproduce in 3.2.rc3 thru 3.2.3.rc3

Issue was resolved.

**Comment by fire** [comment] 2020-08-10 18:44
Closing as resolved per @tom-jk's comment.

**Closed by fire** 2020-08-10 18:44 UTC
Labels: bug, confirmed, topic:editor, usability
