### ISSUE TITLE
Object.CONNECT_ONESHOT is seen as invalid

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18750] opened 2018-05-09 23:15 UTC
Godot 3.0.3rc1

I think I posted an issue on this but I can't find it anymore...
CONNECT_ONESHOT is an enum found in `Object`, but it's not possible to write it in its "static" form, and doesn't appear in autocomplete (actually, nothing appears at all despite all constants `Object` has):

![image](https://user-images.githubusercontent.com/1311555/39844274-7f7c0f2c-53ef-11e8-931b-7fe5d205e5f9.png)

However, writing it as a member works:

![image](https://user-images.githubusercontent.com/1311555/39844281-920ca480-53ef-11e8-8cfb-bfdc30847a55.png)

**Comment by vnen** [comment] 2018-05-10 01:17
The issue is that `Object` is seen as a built-in type, not like the common parent of all objects.

**Comment by Zylann** [comment] 2018-05-10 09:25
What does "built-in" type means here? Isn't it a type in the end? (which is then accessible from any script without an instance?)

**Comment by bojidar-bg** [comment] 2018-05-10 09:35
In this context, a built-in type is a Variant type which has a corresponding TYPE_ constant.

**Comment by williamd1k0** [comment] 2019-06-27 05:35
Tested it on Godot 3.1-stable.
No error is shown, so it seems to be fixed now.
Autocomplete still does not work for `Object.*`.

Related issue: #26190

**Comment by akien-mga** [comment] 2019-06-27 07:58
Thanks, closing as fixed then. The autocomplete issue can be further discussed in #26190 (unless the issue with `Object.*` seems to be a different one, in which case it should probably have its own issue).

**Closed by akien-mga** 2019-06-27 07:58 UTC
Labels: bug, topic:gdscript
