### ISSUE TITLE
Custom resources with TileSet.CellNeighbor fields return null for all fields in Release builds

### ISSUE THREAD

**Issue by squimmy** [godotengine/godot#71115] opened 2023-01-09 14:40 UTC
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 10, Vulkan API 1.3.205 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 970

### Issue description

If a custom resource has a field of type `TileSet.CellNeighbor`, accessing the fields of the resource returns `null`, but only in _Release_ builds. Debug builds do not exhibit this bug, nor does running the game from the editor.

(Maybe there are other enums that exhibit the same behaviour, but I have no checked.)

### Steps to reproduce

Define a custom resource with a `@export var neighbours: TileSet.CellNeighbor` var, and create a resource file for it.
Reference one of the resource's variables in code, and compile a Release build.

### Minimal reproduction project

[ReleaseDebugBuildDifferenceReproduction.zip](https://github.com/godotengine/godot/files/10373915/ReleaseDebugBuildDifferenceReproduction.zip)

In the attached project, Debug builds correctly display the text `Bar`, while Release builds show `<null>`

Debug:
![image](https://user-images.githubusercontent.com/651033/211330996-3b0e9d2e-1323-4720-bab2-1a785f005322.png)

Release:
![image](https://user-images.githubusercontent.com/651033/211331019-34e4cbf0-6a2d-42a9-9beb-17226bc36589.png)

**Comment by anvilfolk** [comment] 2023-01-09 21:05
This might be a duplicate of #64084, unless `@export` adds different behavior. I believe this should be fixed by #64253, which I think came after beta 10 was released.

**Comment by anvilfolk** [comment] 2023-01-10 02:51
Looks fixed on `master`. From the editor:
![image](https://user-images.githubusercontent.com/1133892/211450799-099fb9e9-0795-4d94-8d9b-62854b3afd79.png)

And running after exporting:
![image](https://user-images.githubusercontent.com/1133892/211450868-c5c79c8c-7fde-45fb-baa8-b9cf6232c08c.png)

Recommend closing @akien-mga :)

**Closed** 2023-01-10 07:39 UTC
Labels: bug, topic:gdscript
