### ISSUE TITLE
Resizing window creates font artifacts.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14736] opened 2017-12-16 13:15 UTC
godot [version](godot3builds.digitecnology.com/builds/2017-12-15.12:12:09.433cb6f49/godot-v3.0-osx.fat.zip)
MBP (2016) MacOs Sierra 10.12.06
Radeon Pro 455 2048 MB
Intel HD Graphics 530 1536 MB

maybe relevant : https://github.com/godotengine/godot/issues/12477

**Steps to reproduce:**
https://youtu.be/byPni2AQO_4
1. Resize script font with "Command+MouseScroll/up/down"
2. Resize Godot window.
3. Resize font again.

**Comment by vnen** [comment] 2017-12-18 01:34
Duplicate of #14390.

**Closed by vnen** 2017-12-18 01:34 UTC
