### ISSUE TITLE
[3.x] Windows + Mono cross-compile fails at linking stage

### ISSUE THREAD

**Issue by GlitchedCode** [godotengine/godot#58417] opened 2022-02-22 01:57 UTC
### Godot version

3.x branch

### System information

Official Arch Linux Docker image

### Issue description

Attempting to compile the engine for Windows with mono support in a clean Arch Linux docker container results in a series of linking errors:
```
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmini_la-driver.o):(.bss+0x0): multiple definition of `_dowildcard'; /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-wildcard.o):/build/mingw-w64-crt/src/mingw-w64-v9.0.0/mingw-w64-crt/crt/wildcard.c:32: first defined here
modules/libmodules.windows.opt.64.a(gd_mono_marshal.windows.opt.64.o): in function `GDMonoUtils::get_runtime_invoke_count_ref()':
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xab95): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xabab): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xb323): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xb339): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
modules/libmodules.windows.opt.64.a(csharp_script.windows.opt.64.o): in function `GDMonoUtils::get_runtime_invoke_count_ref()':
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xa77): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0xa81): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
modules/libmodules.windows.opt.64.a(signal_awaiter_utils.windows.opt.64.o): in function `GDMonoUtils::get_runtime_invoke_count_ref()':
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0x48): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0x52): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0x72): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0x13c): relocation truncated to fit: IMAGE_REL_AMD64_REL32 against undefined symbol `TLS init function for GDMonoUtils::current_invoke_count'
/root/godot/modules/mono/mono_gd/gd_mono_utils.h:136:(.text+0x146): additional relocation overflows omitted from the output
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmini_la-mini-windows.o):(.text+0x2dc): undefined reference to `__imp_timeGetDevCaps'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmini_la-mini-windows.o):(.text+0x334): undefined reference to `__imp_timeSetEvent'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmini_la-mini-windows.o):(.text+0x39a): undefined reference to `__imp_timeKillEvent'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmono_dbg_la-debugger-agent.o):(.text+0x1d3f): undefined reference to `__imp_shutdown'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmono_dbg_la-debugger-agent.o):(.text+0x1d58): undefined reference to `__imp_shutdown'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x1e0): undefined reference to `__imp_SafeArrayPutElement'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x2d5): undefined reference to `__imp_SafeArrayCreate'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x32d): undefined reference to `__imp_SafeArrayDestroy'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x35e): undefined reference to `__imp_SafeArrayGetDim'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x37c): undefined reference to `__imp_SafeArrayGetUBound'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x383): undefined reference to `__imp_SafeArrayGetLBound'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x435): undefined reference to `__imp_SafeArrayPtrOfIndex'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x4c4): undefined reference to `__imp_SafeArrayGetDim'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x569): undefined reference to `__imp_SafeArrayGetUBound'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x5ce): undefined reference to `__imp_SafeArrayGetLBound'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0xf18): undefined reference to `__imp_SysFreeString'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x2100): undefined reference to `__imp_SysStringLen'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x39f6): undefined reference to `__imp_CoCreateFreeThreadedMarshaler'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x3b0a): undefined reference to `__imp_SysAllocStringLen'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x6eb3): undefined reference to `__imp_SysAllocStringLen'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x7b83): undefined reference to `__imp_SysAllocStringLen'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-cominterop.o):(.text+0x7b98): undefined reference to `__imp_SysFreeString'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-marshal-windows.o):(.text+0x33): undefined reference to `__imp_CoTaskMemAlloc'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-marshal-windows.o):(.text+0x53): undefined reference to `__imp_CoTaskMemRealloc'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-marshal-windows.o):(.text+0x147): undefined reference to `__imp_CoTaskMemAlloc'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-marshal-windows.o):(.text+0x1e0): undefined reference to `__imp_CoTaskMemAlloc'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-threads.o):(.text+0x64f5): undefined reference to `__imp_CoInitializeEx'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-threads.o):(.text+0x6563): undefined reference to `__imp_CoUninitialize'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x2ae): undefined reference to `GetFileVersionInfoSizeW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x303): undefined reference to `GetFileVersionInfoW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x348): undefined reference to `VerQueryValueW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x399): undefined reference to `VerQueryValueW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32process.o):(.text+0x4ab): undefined reference to `VerQueryValueW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0xb2): undefined reference to `__imp_getpeername'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x566): undefined reference to `__imp_getsockopt'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x1288): undefined reference to `__imp_WSASocketW'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x2be7): undefined reference to `__imp_shutdown'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x2d50): undefined reference to `__imp_WSAIoctl'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x2e87): undefined reference to `__imp_gethostname'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket.o):(.text+0x30e0): undefined reference to `__imp_gethostname'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-mono-os-wait-win32.o):(.text+0x6fb): undefined reference to `__imp_WSAWaitForMultipleEvents'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-mono-os-wait-win32.o):(.text+0x806): undefined reference to `__imp_WSAWaitForMultipleEvents'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-networking-posix.o):(.text+0x239): undefined reference to `__imp_getprotobyname'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-networking-posix.o):(.text+0x2a1): undefined reference to `__imp_getprotobyname'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoutils_la-networking-posix.o):(.text+0x2f9): undefined reference to `__imp_getprotobyname'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x8d): undefined reference to `__imp_WSAIoctl'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x17b): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x247): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x3ff): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x42e): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x587): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x5ad): more undefined references to `__imp_WSASetLastError' follow
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x9a8): undefined reference to `__imp_WSARecv'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xa71): undefined reference to `__imp_WSARecv'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xab7): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xadd): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xc3f): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xc6d): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xe07): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xe2d): more undefined references to `__imp_WSASetLastError' follow
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xed6): undefined reference to `__imp_WSASend'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xf9f): undefined reference to `__imp_WSASend'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0xfdf): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x100d): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x10b4): undefined reference to `__imp_WSAIoctl'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x11d7): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x121b): undefined reference to `__imp_WSASetLastError'
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: /root/mono-installs/desktop-windows-x86_64-release/lib/libmonosgen-2.0.a(libmonoruntimesgen_la-w32socket-win32.o):(.text+0x1363): undefined reference to `__imp_WSASetLastError'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.64.mono.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:05:35.681]
```

### Steps to reproduce

Create a new docker container, install mingw-w64 and the other build dependencies from the arch repository as stated in the relevant documentation, download godot sources and godot's custom mono build, build a linux executable, generate mono glue, then build a windows executable with mono glue enabled

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-02-22 08:45
Duplicate of #52190

**Closed by akien-mga** 2022-02-22 08:45 UTC
Labels: bug, platform:linuxbsd, topic:buildsystem, topic:mono
