### ISSUE TITLE
Parent scene .tscn file becoming un-parseable when renaming child scenes

### ISSUE THREAD

**Issue by wirelessfuture** [godotengine/godot#70124] opened 2022-12-15 21:05 UTC
### Godot version

4.0.beta8.official [45cac42c0]

### System information

MacOS 12.5.1 Monterey

### Issue description

Sometimes renaming the child scene of a parent scene causes the parent scenes .tscn file to become corrupt, leading to the Cannot parse scene error. I was able to fix this by opening the scene in a text editor and replacing the offending lines with lines from a backup file. (in this case it was a subresource that was missing half of the information it normally has)

### Steps to reproduce

Place a scene inside of a parent scene, and then try to rename it and save whilst the child scene is open in editor. Its hard to reproduce as Ive renamed scenes like this before without issues. 

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-12-15 21:27
Duplicate of #69794

**Closed by akien-mga** 2022-12-15 21:27 UTC
