### ISSUE TITLE
[C# API] Possible type mismatch of property Node.AnchorsPreset

### ISSUE THREAD

**Issue by HydrogenC** [godotengine/godot#71062] opened 2023-01-08 12:49 UTC
### Godot version

4.0 beta 10

### System information

Irrevalent

### Issue description

The property Node.AnchorsPreset should be of type LayoutPreset just like what Node.SetAnchorsPreset takes, but it is now of type int. This is difficult for users to figure out which preset each int value stands for, which makes the property unusable. Its type should be changed to LayoutPreset instead. 

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2023-01-08 13:32
The C# API is generated from ClassDB, this property is defined in Core as taking an INT which is why C# also defines it that way:

https://github.com/godotengine/godot/blob/fcba87e696d58912838d8a4a6987b10efa28e78f/scene/gui/control.h#L285-L286

**Comment by HydrogenC** [comment] 2023-01-09 00:54
Additionally, setting the Node.AnchorsPreset property may result in unexpected results, while the SetAnchorsPreset function always gives the correct result. Maybe make Node.AnchorsPreset a readonly property and guide users to the SetAnchorsPreset function for modifying?

**Comment by raulsntos** [comment] 2023-01-09 03:26
The `Control.AnchorsPreset` property uses the `_SetAnchorsLayoutPreset` method internally, it's not the same as calling `SetAnchorsPreset`, they're two different APIs. Someone from the @godotengine/gui-nodes team can explain better how these APIs work but basically `_SetAnchorsLayoutPreset` sets the anchors preset (like `SetAnchorsPreset`) but also sets the offset preset and the grow direction preset, maybe renaming the property to `anchors_layout_preset` would make the difference clearer.

**Comment by HydrogenC** [comment] 2023-01-10 00:53
> The `Control.AnchorsPreset` property uses the `_SetAnchorsLayoutPreset` method internally, it's not the same as calling `SetAnchorsPreset`, they're two different APIs. Someone from the @godotengine/gui-nodes team can explain better how these APIs work but basically `_SetAnchorsLayoutPreset` sets the anchors preset (like `SetAnchorsPreset`) but also sets the offset preset and the grow direction preset, maybe renaming the property to `anchors_layout_preset` would make the difference clearer.

Thanks for your explanation!

**Comment by YuriSizov** [comment] 2023-01-10 10:49
Both `anchors_preset` and `layout_mode` are not supposed to be used in scripting. They are marked as `PROPERTY_USAGE_INTERNAL`, and are only relevant for the editor. They exist as properties because that's the only way to have them in the inspector and in a specific order.

Now, GDScript doesn't hide those properties either, because `PROPERTY_USAGE_INTERNAL` is for the most part only used for documentation. So it's not an issue with the C# generator, but it's probably something we should address across the board.

The collision is accidental, and the property and the method have no relation. The `set_anchors_preset` method is just a helper method to set all anchors together according to a `LayoutPreset` value. The `anchors_preset` property accepts different values than `LayoutPreset` (we just happen to reuse that enum internally for validation to reduce duplication of such a large enumeration). They are not compatible for each other.

**Comment by zak-grumbles** [comment] 2023-04-16 16:42
Hi! Interested in working on this issue. After reading the discussion, I'm unsure of what needs to be done here. It sounds as though things are behaving as intended? Or does there need to be a type change in ClassDB to fix the C# type?

**Comment by YuriSizov** [comment] 2023-04-17 09:22
Hey, sorry, there is no consensus yet on what should be done here. And this shouldn't be marked as a good first issue, at least not until we reach one.

**Closed** 2024-04-22 10:58 UTC
Labels: bug, topic:gui
