### ISSUE TITLE
Deleted scenes in an array are replaced by new instanced scenes for no reason.

### ISSUE THREAD

**Issue by Kadaka** [godotengine/godot#38081] opened 2020-04-21 14:33 UTC
**Godot version:**
3.2.1_stable_mono_win64
**OS/device including version:**
win10 latest version
**Issue description:**
I create an array, then fill it with 10 instanced scenes.
I delete some of the items in the array, after that I replace the deleted objects with new instanced scenes one by one.
when repeating the deletion and replacement, some deleted objects will be replaced with new instanced scenes at the wrong time. and sometimes one new intanced scene will replace two different deleted objects, which is not allowed in the script too.
Main scene (MainS) is a node2d with a script:
```gdscript
extends Node2D

var width = 10

var piece = preload("res://Piece.tscn")
var grid = null
var counter = 0

func _ready():
	grid = create_array()
	refill(grid)
	
func _process(delta):
	if counter < 3:
		refill(grid)
		rand_delete(grid)
#		counter += 1
	pass

func create_array():
	# create an array with 10 nulls
	var array = []
	for i in width:
		array.append(null)
	return array

func valid_counter(grid):
	# count the number of valid pieces in the array
	var n = 0
	for i in width:
		if grid[i] != null and is_instance_valid(grid[i]):
			n += 1
	return n

func refill(grid):
	# if some of the items in the array are nulls or deleted, replace them with new pieces.
	for i in width:
		if grid[i] == null or !is_instance_valid(grid[i]):
			var n1 = valid_counter(grid)
			print_debug(grid)
			var new_piece = piece.instance()
			add_child(new_piece)
			var n2 = valid_counter(grid)
			if n1 != n2:
				print_debug("bug", n1, n2) # n1 and n2 should always be the same.
				print_debug(grid)
			grid[i] = new_piece

func rand_delete(grid):
	# randomly deleted 3 items in the array
	for k in 3:
		var rng = RandomNumberGenerator.new()
		rng.randomize()
		var i = rng.randi_range(0, 9)
		if grid[i] != null and is_instance_valid(grid[i]):
			grid[i].delete()
	print_debug(grid)
```

Another scene (Piece) is a node2d with script:
```gdscript
extends Node2D

func delete():
	queue_free()
````

when running the script, part of the output is:
```
[[Deleted Object], [Deleted Object], [Deleted Object], [Node2D:1282], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Node2D:1331]]
   At: res://MainS.gd:44:refill()
[[Node2D:1339], [Deleted Object], [Deleted Object], [Node2D:1282], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Node2D:1331]]
   At: res://MainS.gd:38:refill()
bug810
   At: res://MainS.gd:43:refill()
[[Node2D:1339], [Node2D:1340], [Node2D:1340], [Node2D:1282], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Node2D:1331]]
   At: res://MainS.gd:44:refill()
[[Node2D:1339], [Node2D:1340], [Node2D:1340], [Node2D:1282], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Node2D:1331]]
   At: res://MainS.gd:54:rand_delete()
[[Node2D:1339], [Deleted Object], [Deleted Object], [Deleted Object], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Deleted Object]]
   At: res://MainS.gd:38:refill()
bug68
   At: res://MainS.gd:43:refill()
[[Node2D:1339], [Node2D:1344], [Node2D:1344], [Deleted Object], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Deleted Object]]
   At: res://MainS.gd:44:refill()
[[Node2D:1339], [Node2D:1344], [Node2D:1344], [Deleted Object], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Deleted Object]]
   At: res://MainS.gd:38:refill()
[[Node2D:1339], [Node2D:1344], [Node2D:1344], [Node2D:1345], [Node2D:1323], [Node2D:1323], [Node2D:1339], [Node2D:1329], [Node2D:1330], [Deleted Object]]
   At: res://MainS.gd:38:refill()
```
 
Bugs appear when there are bug+2 number.
I'm not sure if it's really a bug or I have made some mistakes, please help me.

**Steps to reproduce:**
just run the script MainS, and the bug will appear, we can see it in the script output.

**Minimal reproduction project:**
[To_reproduce_a_bug.zip](https://github.com/godotengine/godot/files/4510603/To_reproduce_a_bug.zip)

**Comment by Calinou** [comment] 2020-04-22 12:33
Duplicate of #32383.

**Closed by Calinou** 2020-04-22 12:33 UTC
