### ISSUE TITLE
3d platformer triggers segfault

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#21931] opened 2018-09-10 12:00 UTC
``` Swift
[user@user bin]$ '/run/media/user/user/git/godot/bin/godot.x11.opt.tools.64' 
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: /home/user/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/scene_format_text.cpp:560.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:153.
ERROR: _load: Failed loading resource: /home/user/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:190.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:845.
Scanning projects at: /run/media/user/user/git/godot-demo-projects
Found 52 projects.
Editing project: /run/media/user/user/git/godot-demo-projects/3d/platformer (::run::media::user::user::git::godot-demo-projects::3d::platformer)
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
WARNING: _get: Property not found: _global_script_class_icons
   At: core/project_settings.cpp:194.
[user@user bin]$ WARNING: grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.
   At: scene/gui/control.cpp:2067.
WARNING: set_theme: GridMap.theme/set_theme() is deprecated and will be removed in a future version. Use GridMap.mesh_library/set_mesh_library() instead.
   At: modules/gridmap/grid_map.cpp:215.
WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physics material instead.
   At: scene/3d/physics_body.cpp:622.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f642d597e00] (??:0)
[2] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x967ace) [0x555d99dacace] (??:0)
[3] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x8423c0) [0x555d99c873c0] (??:0)
[4] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x842cef) [0x555d99c87cef] (??:0)
[5] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22ad414) [0x555d9b6f2414] (??:0)
[6] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x18700bb) [0x555d9acb50bb] (??:0)
[7] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x850453) [0x555d99c95453] (??:0)
[8] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22ad414) [0x555d9b6f2414] (??:0)
[9] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x14ea57a) [0x555d9a92f57a] (??:0)
[10] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x14ea6c8) [0x555d9a92f6c8] (??:0)
[11] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x14eaf1a) [0x555d9a92ff1a] (??:0)
[12] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x14eb013) [0x555d9a930013] (??:0)
[13] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x14eb4fb) [0x555d9a9304fb] (??:0)
[14] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0xddb24b) [0x555d9a22024b] (??:0)
[15] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0xddb900) [0x555d9a220900] (??:0)
[16] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x646d5e) [0x555d99a8bd5e] (??:0)
[17] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22b1a9c) [0x555d9b6f6a9c] (??:0)
[18] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22b9a36) [0x555d9b6fea36] (??:0)
[19] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22ba885) [0x555d9b6ff885] (??:0)
[20] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0xd7d56d) [0x555d9a1c256d] (??:0)
[21] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x22ad414) [0x555d9b6f2414] (??:0)
[22] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x1515bb2) [0x555d9a95abb2] (??:0)
[23] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x15187db) [0x555d9a95d7db] (??:0)
[24] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x4cd1dc) [0x555d999121dc] (??:0)
[25] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x4b8a21) [0x555d998fda21] (??:0)
[26] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(main+0xcc) [0x555d998ef9ac] (??:0)
[27] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f642d584223] (??:0)
[28] /run/media/user/user/git/godot/bin/godot.x11.opt.tools.64(+0x4adbde) [0x555d998f2bde] (??:0)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment] 2018-09-10 12:33
I can't reproduce the crash on Mageia 6 x86_64:
```
$ pwd
/home/akien/Projects/godot/godot-demo-projects/3d/platformer
$ godot-git -e   
OpenGL ES 3.0 Renderer: GeForce GTX 670MX/PCIe/SSE2
WARNING: grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.
   At: scene/gui/control.cpp:2067.
WARNING: set_theme: GridMap.theme/set_theme() is deprecated and will be removed in a future version. Use GridMap.mesh_library/set_mesh_library() instead.
   At: modules/gridmap/grid_map.cpp:215.
WARNING: set_friction: The method set_friction has been deprecated and will be removed in the future, use physics material instead.
   At: scene/3d/physics_body.cpp:622.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
```
At this stage the editor is open and I can edit things.

**Comment by akien-mga** [comment] 2018-09-10 12:34
What commit are you using? It might be fixed by #21921.

**Comment by LinuxUserGD** [comment] 2018-09-10 14:10
https://github.com/godotengine/godot/commit/ffe158ae85b970cbc05b4da1047102dc19dc8297 on arch linux

**Comment by akien-mga** [comment] 2018-09-10 17:10
Alright, it should be fixed when you update to the current master HEAD then.

**Closed by akien-mga** 2018-09-10 17:10 UTC
Labels: bug, topic:core

**Comment by LinuxUserGD** [comment] 2018-09-10 19:13
:+1
