### ISSUE TITLE
Non-alphanumeric keys cause system beep when pressed

### ISSUE THREAD

**Issue by getzen** [godotengine/godot#58370] opened 2022-02-20 21:26 UTC
### Godot version

4.0 alpha 2

### System information

Mac OS 12.2.1 on iMac (Retina 5K, 27-inch, 2017)

### Issue description

When using the 4.0 alpha 2 Godot editor on my iMac, I get a system beep with certain keystrokes. It happens with the return key, backspace, page up/down, the arrow keys and so on. So, for example, if I use the backspace key three times, the key works, but I hear beep, beep, beep.

It does not happen with normal alphanumeric keys. It happens whether typing text in a script or adjusting property values in the editor. It does not happen in Godot 3 or any other app. It does not happen when playing a Godot 4 project.

I tried deleting Godot 4 alpha 2 and all the supporting files and then reinstalling Godot 4 alpha 2. No change.

### Steps to reproduce

Download Godot 4 alpha 2. Create a project. Type text in a script or type property values. Beep occurs with each alphanumeric keypress.

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/8104940/Project.zip)

**Comment by akien-mga** [comment] 2022-02-20 21:28
Duplicate of #58016, this is fixed in the upcoming 4.0 alpha 3.

**Closed by akien-mga** 2022-02-20 21:28 UTC
