### ISSUE TITLE
3.2 beta 2 through rc1: GLES3 projects crash the editor [Linux on Chrome OS]

### ISSUE THREAD

**Issue by bigcatrik** [godotengine/godot#35298] opened 2020-01-18 22:15 UTC
**Godot version:**
Godot_v3.2-beta2_x11.64 through Godot_v3.2-rc1_x11.64

**OS/device including version:**
Ubuntu Linux Xenial (running in crouton/Chrome OS)

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Issue description:**

GLES3 projects crash the editor.  GLES2 projects will open in editor as normal.

OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Bay Trail 
i965: Failed to submit batchbuffer: Invalid argument

00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31] (rev 0e) (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31]
	Flags: bus master, fast devsel, latency 0, IRQ 262
	Memory at d0000000 (32-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at 1000 [size=8]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915

**Steps to reproduce:**

Open Project List, select project.  Crash.

Open Project List, create new project.  Crash.

**Minimal reproduction project:**
[G32_rc1_02.zip](https://github.com/godotengine/godot/files/4081877/G32_rc1_02.zip)

**Comment by clayjohn** [comment] 2020-01-19 00:46
Your MRP is just an empty folder. Please attach something with a project in it that can be used to reproduce the crash. 

I have similar hardware to you that I can test on if provided with an MRP. With my own projects I cannot reproduce the crash. (Ubuntu 16.04 Xenial, running through crouton, Intel Bay Trail-M N2840)

**Comment by bigcatrik** [comment] 2020-01-19 01:00
Yes, 3.1.2 stable works, as does the 3.2 alphas and beta1.

New file.

[Archive.zip](https://github.com/godotengine/godot/files/4082117/Archive.zip)

**Comment by clayjohn** [comment] 2020-01-19 01:17
I still can't reproduce, here is a build from PR #35302 that I think may solve your issue, can you test it please? https://drive.google.com/file/d/135XnhoppJIkBjhBJIUJqwSs5S9ckCq_F/view?usp=sharing

**Comment by bigcatrik** [comment] 2020-01-19 01:39
Thanks, but the new build still crashes with the "i965: Failed to submit batchbuffer: Invalid argument" error.

**Comment by clayjohn** [comment] 2020-01-19 01:43
Can you add the following directly to your project.godot file under "[rendering]"
``quality/reflections/high_quality_ggx=false``

**Comment by bigcatrik** [comment] 2020-01-19 02:22
Still crashes.  After the crash I noticed it had deleted the line 
quality/driver/driver_name="GLES3"
from the [rendering] section (the added line about reflections was still there).

**Comment by clayjohn** [comment] 2020-01-19 02:58
That's because the editor no longer saves project settings when they are the same as the defaults. 

I think the issue you are having is that your GPU is struggling to run the computations necessary to calculate the radiance map. Between beta 1 and beta 2 we added code to fix bugs in the radiance map generation. However, I think this added code made the shader sufficiently complex that your hardware can no longer run it. The last thing to try will be to run a project with a small radiance map. 

To do so, open a project in GLES3. Add a worldenvironment node with a procedural sky, and set the radiance size to the lowest setting (32) I think. Then set the project to GLES3 and see if it crashes.

**Comment by bigcatrik** [comment] 2020-01-19 04:41
I set the radiance size to 32 using beta1 (which will still run GLES3) but when trying to open it in your latest build and rc1 it crashed.

Oh well, I still have GLES2.

**Comment by clayjohn** [comment] 2020-01-19 04:44
Thanks for trying. I must be wrong about what's causing the crash then.

**Comment by bigcatrik** [comment] 2020-01-19 04:50
Thanks for looking into it.

**Comment by clayjohn** [comment] 2020-01-19 05:21
Any chance you haven't updated your drivers in awhile? I was able to find some similar errors from 2017-2018 stemming from some MESA driver issues.

**Comment by bigcatrik** [comment] 2020-01-19 16:09
I use the built-in crouton update function.  I last updated two days ago before I started investigating the crashes.

**Comment by akien-mga** [comment] 2020-01-19 16:24
What Mesa version do you have?

**Comment by clayjohn** [comment] 2020-01-19 17:10
> I use the built-in crouton update function.

Please note, the built-in crouton update function only updates the chroot itself, it doesn't update your ubuntu distro you still need to update everything else. 

For example, you can update your mesa drivers with the following commands:
```
sudo apt-get update
sudo apt-get dist-upgrade
```

**Comment by bigcatrik** [comment] 2020-01-19 19:18
Update/upgrade said I'm all up to date (0 across the board).

Here's the glxinfo report:

~$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.20
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by bigcatrik** [comment] 2020-01-21 17:08
rc2 still crashes my system when creating or opening a GLES3 project (even the one with radiance off).  GLES2 still works (hooray).

**Comment by clayjohn** [comment] 2020-01-21 17:27
Are you able to run other graphics-heavy programs (blender for example). I was looking into this further, and I don't see why your hardware would have such trouble. Mine is very similar.

CPU: Intel(R) Celeron(R) CPU N2840 @ 2.16GHz
GPU: Intel® HD Graphics for Intel Atom® Processor Z3700 Series
OS: Ubuntu 16.04
Driver: Mesa 18.0.5

**Comment by bigcatrik** [comment] 2020-01-21 17:51
Yes, Blender 2.81 runs.  Rendering is glacially slow (now that they've taken out the Blender Internal render) and pegs the CPU meter, but it doesn't crash.

**Comment by RodZill4** [comment] 2020-01-24 19:24
I have (similar?) crashes when setting the radiance size of a procedural or panorama sky to values > 512.
I'm under Windows with a GeForce GTX 960M (and it worked fine with 3.1.2).

**Comment by bigcatrik** [comment] 2020-01-24 23:20
rc3 still has the same problem as the previous versions (3.2 beta2 to present version) for me -- rc3 crashes when creating or opening a GLES3 project (even one with radiance off). GLES2 still works.

**Comment by akien-mga** [comment] 2020-01-25 12:19
@RodZill4 It's related, but not the same issue. For @bigcatrik it's crash on much lower end hardware with any radiance size -- in your case it runs on mid-high end with extreme settings.

**Comment by akien-mga** [comment] 2020-01-25 18:00
After discussing with @clayjohn, we decided that it's unlikely for this issue to be fixed, so we're closing it. Still, if anyone figures out a fix that can be used to reduce further the computation intensity of radiance maps, it might help make the GLES3 renderer viable on such hardware again.

This integrated GPU is very low end and quite dated, so even though it supports the OpenGL 3.3 specification, it doesn't seem powerful enough for the use we make of it, which does work for most other OpenGL 3.3-compliant hardware.

To summarize, the options left for @bigcatrik are:
- Use GLES2 with Godot 3.2. For this hardware it's likely the best choice, GLES3 is too high-end.
- Use GLES3 from Godot 3.1.x, which should still work as it has less features and appears to be less demanding on the GPU (at least when it comes to this specific code path which leads to a crash)
- Upgrade to a more recent Linux distro with latest Mesa drivers, e.g. Ubuntu 19.10 (or 20.04 when it's out), which *might* include relevant Mesa fixes which would make this setup viable (at least @clayjohn seems to have nearly the same setup and things work for him).

Thanks for the help debugging though, and sorry that we can't think of any way to make things work again without outright reverting the necessary bugfix that increased the computational requirements.

Note: For @RodZill4's issue on a higher end GPU, it's tracked in #35552.

**Closed by akien-mga** 2020-01-25 18:00 UTC
Labels: bug, crash, platform:linuxbsd, topic:rendering
