### ISSUE TITLE
CSG flicker / missing triangles / holes in the geometry at certain translations

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#43755] opened 2020-11-21 21:27 UTC
**Godot version:**
Godot 3.2.3 stable, Godot 3.2.4 beta2

**OS/device including version:**
Win 64, Nvidea

**Issue description:**
CSG geometry does not seem stable, flickers at certain translations, generating holes in the geometry.

![csg_flicker_3 2 4beta2](https://user-images.githubusercontent.com/47016402/99887877-5d543800-2c48-11eb-997e-58d3aa02ae73.gif)

Previous related issue:
https://github.com/godotengine/godot/issues/33121

There is also a very noticeable reduction in Editor framerate with only 10 CSG boxes in the scene.

**Steps to reproduce:**

1. Create a new 3D scene,
2. Add CSGCombiner node as child of the Spacial,
3. Add CSGBox as child of the Combiner (floor), resize,
4. Add another CSGBox as child of the Combiner (wall), resize and move,
5. duplicate and move the wall a few times.

**Minimal reproduction project:**
[csg_flicker.zip](https://github.com/godotengine/godot/files/5578411/csg_flicker.zip)

**Comment by Calinou** [comment] 2020-11-21 22:49
cc @madmiraal

**Comment by Calinou** [comment] 2022-12-06 22:39
Duplicate of https://github.com/godotengine/godot/issues/58637 (same cause – it's caused by coplanar faces).

**Comment by akien-mga** [comment] 2023-04-27 15:05
> Duplicate of #58637 (same cause – it's caused by coplanar faces).

#74771 fixed #58637, but in my tests it didn't seem to fix the MRP in this issue, nor the one from #75862.

I don't know what's the difference but let's reopen this one for keeping track of the cases which aren't solved yet (as of the upcoming 4.1 dev 2).

**Comment by fire** [comment] 2024-05-09 03:38
Testing some csg improvements.

![image](https://github.com/godotengine/godot/assets/32321/60fbc7a0-7903-4c59-9e8f-5a5a9d9877d2)

**Closed** 2024-11-29 21:10 UTC
Labels: bug, confirmed, topic:3d
