### ISSUE TITLE
Object's `set_meta()` doesn't work on inherited scenes 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#12990] opened 2017-11-17 17:33 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
6277e6d40a0f0e8c84470482400959fca4ff5ad8

**Issue description:**
I'm writing an editor tool in which I would like to save some informations inside the scene itself. It turns out I can't save any information inside those scenes which are extending another ones. 

**Steps to reproduce:**
Short way:
1. Download sample project
2. open `InheritedScene.tscn` 
3. Save it.
4. Check `InheritedScene.tscn`  in notepad and see that there is no meta data
5. Additional: Repeat above steps for `BaseScene.tscn` and see meta is saved inside  `BaseScene.tscn`

Long way:
1. Create `BaseScene.tscn`
2. Create scene which is inheriting `BaseScene.tscn` save it as `InheritedScene.tscn`
3. Attach this code to `InheritedScene.tscn`:
```
tool
extends Node
func _ready():
	set_meta("Custom Meta", "Meta informations: " +  get_name() + " save time: " + str(OS.get_time()));
```
4. Reopen `InheritedScene.tscn`
5. Save it 
6. Open `InheritedScene.tscn` in notepad and see that there is no meta data

**Link to minimal example project:**
[MetaInfoSaveInInheritedSceneTool.zip](https://github.com/godotengine/godot/files/1483183/MetaInfoSaveInInheritedSceneTool.zip)

**Comment by fracteed** [comment] 2017-11-19 00:40
Good to see that you have isolated the issue! I was having lots of trouble reading metadata via the get_meta function a few weeks back on my game. Now I realise why I was getting all the errors :)

**Comment by kubecz3k** [comment] 2017-11-19 08:49
I also suspect this issue is related with #12838

**Comment by akien-mga** [comment] 2019-10-28 14:03
For the reference, I checked if #32416 would fix this issue, but it did not.

**Comment by Hubber116sx** [comment] 2019-11-21 17:32
2 Years later and this error still persists.

**Comment by eh-jogos** [comment] 2021-04-23 11:35
Having problems with this as well, on 3.3

**Comment by Jayman2000** [comment] 2021-11-11 15:53
A side effect of this bug is that Editor Descriptions can’t be set for inherited scenes.

**Comment by Rubonnek** [comment] 2021-12-27 05:49
I'm not able to reproduce this issue in the 3.x branch at commit a75afd61a77c58fc7daaa525e485398795221f6f

**Comment by Calinou** [comment] 2021-12-27 17:13
Closing per @Rubonnek's comment. Please comment if you can still reproduce this.

**Closed by Calinou** 2021-12-27 17:13 UTC
Labels: bug, topic:core, confirmed, topic:plugin
