### ISSUE TITLE
Classes/Reference search windows sometimes appear behind the code editor

### ISSUE THREAD

**Issue by viibr** [godotengine/godot#7255] opened 2016-12-06 18:18 UTC
**Operating system or device - Godot version:**
Windows - 2.1.1

**Issue description** (what happened, and what was expected):
This is a minor bug. Occasionally the Class and Reference search window for the script editor will appear behind the code itself if the autocomplete dialog is also visible. However, the class/reference search windows receive the mouse clicks instead of the code editor.

Here is an image to [show what I mean.](http://imgur.com/a/xjdtT)

**Comment by bojidar-bg** [comment] 2016-12-06 18:27
Duplicate of #7156 (and #6769 in turn)

**Closed by bojidar-bg** 2016-12-06 18:27 UTC
