### ISSUE TITLE
Mono: dependency classes aren't added to solution automatically

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11930] opened 2017-10-08 04:26 UTC
When you create a base class in a file, and create a deriving class in another file and attach it to a node, the build will fail, complaining that the base class isn't a part of the build.

**Comment by khairul169** [comment] 2017-10-08 06:07
Autoload singleton also doesn't added automatically while regenerating the solution after deleting whole project solution..

**Comment by neikeq** [comment] 2017-10-08 21:24
@tagcup What is the build error exactly?

**Comment by tagcup** [comment] 2017-10-08 23:01
> The type or namespace name `BaseClass' could not be found. Are you missing an assembly reference?

**Comment by tagcup** [comment] 2017-10-08 23:02
Attached an example project demonstrating the issue
[monodependency.zip](https://github.com/godotengine/godot/files/1367276/monodependency.zip)

**Comment by neikeq** [comment] 2017-10-08 23:28
There was a mistake in the example you uploaded. Line 4 of `Player.cs` should be `public class Player : PlayerBase` not `public class PlayerBase : Player`. After changing that, it gives the error you were talking about, because the file which declares `PlayerBase` is not part of the project.

Can you describe how did you create the file for the base class?

**Comment by tagcup** [comment] 2017-10-08 23:31
Yeah, probably sent the wrong file, anyway, that's what I mean.

> Can you describe how did you create the file for the base class?

emacs Player.cs. Why should it matter?

**Comment by tagcup** [comment] 2017-10-08 23:35
BTW, assuming that globals need to be implemented using a singleton class in a separate file, I also bumped into the issue @khairul169 mentioned too, originally

**Comment by tagcup** [comment] 2017-10-08 23:44
Ah maybe you mean that's the kind of thing that would be added along with support for external editors / IDEs?

**Comment by neikeq** [comment] 2017-10-08 23:56
The reason is you didn't create the file from Godot or an IDE, which would have added it manually.
Right now, there is no way for `CSharpScript` to know its base `CSharpScript`, only the base `MonoClass`, so it can't check that file as well to add it to the project. This will be possible soon though.

**Comment by neikeq** [comment] 2017-10-08 23:57
Also need to check AutoLoads as mentioned above.

**Comment by tagcup** [comment] 2017-10-09 00:01
> The reason is you didn't create the file from Godot or an IDE, which would have added it manually.

> This will be possible soon though.

Yeah, that was kind of the point that I'm trying to make.

> Also need to check AutoLoads as mentioned above.

Well, yes, I do reproduce the same problem?

**Comment by akien-mga** [comment] 2018-01-06 23:41
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment] 2022-01-25 00:24
This seems to have been fixed a long time ago, the project in https://github.com/godotengine/godot/issues/11930#issuecomment-335045262 with the fix in https://github.com/godotengine/godot/issues/11930#issuecomment-335046555 works fine in 3.5 beta 1, and likely in earlier releases too.

**Closed by akien-mga** 2022-01-25 00:24 UTC
Labels: enhancement, usability, topic:mono
