### ISSUE TITLE
Vulkan: Huge memory usage and performance drop after resizing the game window

### ISSUE THREAD

**Issue by marcinn** [godotengine/godot#60110] opened 2022-04-10 19:22 UTC
### Godot version

v4.0.alpha.custom_build.eb6ebdc4a

### System information

Manjaro Linux, 5.10.105-1-MANJARO, x86_64, NVIDIA GM107GLM [Quadro M620 Mobile] nvidia 510.54, X11, Vulkan

### Issue description

After resizing the game window, fps are dropped by about half. Also there is noticeable huge memory usage, which also looks like a memory leak. And when you resize the window few times more, you should hang your OS due to out of memory.

https://www.youtube.com/watch?v=Xd9wGFQBbzk

The issue exists both on X11 and Gnome/Wayland.

### Steps to reproduce

1. Open the project and run the main scene
2. Make window way smaller. You should notice a huge lag and increased memory usage.
3. Then the memory usage will drop almost to original value, but it will be slightly greater. Performance will be dropped about half (check fps)
4. Resize the window few times more in a short time. Your PC will hang due to OOM.

### Minimal reproduction project

Should be any project, but I'm attaching the one used to record the video.
[PopupCrash.zip](https://github.com/godotengine/godot/files/8459740/PopupCrash.zip)

**Comment by Calinou** [comment] 2022-04-10 20:06
Related to https://github.com/godotengine/godot/issues/56205.

In general, changing graphics settings can cause various resource leaks, which you can test by using https://github.com/Calinou/godot-photo-mode-demo.

**Comment by darksylinc** [comment] 2023-08-13 00:09
Is this still an issue? I cannot reproduce this issue on Xubuntu 20.04 with Godot 4.2 master on AMD GPUs.

Neither the memory leak nor the performance degradation. However the perf degradation could be NVIDIA specific.

I noticed this triggers a pathological case of #80570 which will be fixed when #80571 gets merged.

Thus perhaps after merging that PR the slowdown will be gone?

**Comment by Calinou** [comment] 2023-08-14 12:52
https://github.com/Calinou/godot-photo-mode-demo in 4.2.dev3 on NVIDIA exhibits permanently increased VRAM usage after settings are temporarily increased once (from 3.8 GB to 5.3 GB), and then twice (from 5.3 GB to 5.5 GB). Subsequent settings toggles don't affect VRAM usage significantly:

https://github.com/godotengine/godot/assets/180032/77b21bc5-010d-4a94-a538-737bb8827ae1

**Comment by lostminds** [comment] 2023-08-19 20:07
Regarding the memory leak when resizing the window, could that be the same as https://github.com/godotengine/godot/issues/77295 ? Still an issue on 4.2.dev3 now that I tried it. 
Seems like it's allocating a large number of new buffers of some sort for the new size during window resize that aren't properly released as the window keeps changing size and new resources are allocated for the new size.

**Closed** 2023-09-01 23:51 UTC
Labels: bug, topic:rendering, confirmed, regression, performance
