### ISSUE TITLE
[4.2-beta1] Light not falling on one side of mesh

### ISSUE THREAD

**Issue by wjagodfrey** [godotengine/godot#83476] opened 2023-10-17 04:27 UTC
### Godot version

4.2-beta1

### System information

MacOS 12.3

### Issue description

I recently upgraded from 4.2-dev6 to 4.2-beta1, and in doing so this mesh broke. It looks like some of my larger meshes broke as well but this is the simplest, clearest example.

I've recalculated the normals in blender (3.6.2) and tried exporting as .obj rather than .glb - same problem. Am I missing something or is this a bug?

Video [here](https://youtu.be/75HI7inweXE).

<img width="565" alt="image" src="https://github.com/godotengine/godot/assets/5732688/b0603fd2-41f5-4baf-a498-0b7053fa9168">

<img width="1082" alt="Screen Shot 2023-10-17 at 5 10 50 PM" src="https://github.com/godotengine/godot/assets/5732688/f2089bd4-3101-4977-b356-29a42be10fb9">

### Steps to reproduce

Here are my files. Place the .glb or .obj in a scene with an OmniLight3D and rotate the object.

Take a look at the blender file and see that the normals are correct.

### Minimal reproduction project

Files:
[Door.Glass.zip](https://github.com/godotengine/godot/files/12924219/Door.Glass.zip)

**Comment by atirut-w** [comment] 2023-10-17 07:20
Does the issue go away if you tick "Force Disable Compression" in the import settings? If so, this might be a duplicate of #83240.

**Comment by bitsawer** [comment] 2023-10-17 14:30
Seems indeed to be a duplicate of https://github.com/godotengine/godot/issues/83240, so closing this to keep discussion in on place.

**Closed by bitsawer** 2023-10-17 14:30 UTC

**Comment by wjagodfrey** [comment] 2023-10-17 20:11
That was it, thank you both
