### ISSUE TITLE
Crash when calling emit_signal when using a mono build

### ISSUE THREAD

**Issue by jcrapsey** [godotengine/godot#35093] opened 2020-01-13 17:52 UTC
Godot v3.1.2.stable.mono.custom_build.6de4c53
Windows 10 Pro, 10.0.18362 Build 18362

Following the tutorial here
[https://docs.godotengine.org/en/3.1/development/cpp/custom_godot_servers.html](https://docs.godotengine.org/en/3.1/development/cpp/custom_godot_servers.html)

I keep getting a crash when the HilbertHotel thread function calls emit_signal on the _HilbertHotel wrapper class. When looking at other server code in the project I cannot find another example of this way of calling emit_signal being used.

I though this would be my error when following the tutorial, so I decided to use a non-mono build and the example worked as expected.

Steps to reproduce:
clone and build https://github.com/jcrapsey/godot/tree/hilbert_hotel and build following the tutorial [https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_mono.html](https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_mono.html)

download the following project 
[csharp_repro.zip](https://github.com/godotengine/godot/files/4054888/csharp_repro.zip)

When the project is started it should result in an immediate crash.

Here is what I see in visual studio when attached
![hilbertHotelerror](https://user-images.githubusercontent.com/396625/72278544-18538400-35e9-11ea-895d-487ebb4b5664.png)

**Comment by neikeq** [comment] 2020-01-16 22:13
The signal is emitted from a different thread. Depending of what you want to do in the signal callback, this may have been solved by #35208. Otherwise, it's a duplicate of #16024.

**Closed by neikeq** 2020-01-16 22:13 UTC
Labels: bug, crash, topic:mono
