### ISSUE TITLE
Engine RandomFreeze Bug

### ISSUE THREAD

**Issue by DannyWarp** [godotengine/godot#41217] opened 2020-08-13 06:53 UTC
Engine randomly freeze.
v3.2.2

System:
  Host: HP-250-G6 Kernel: 5.4.0-42-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.6.7 Distro: Linux Mint 20 Ulyana 
Machine:
  Type: Laptop System: HP product: HP 250 G6 Notebook PC 
  v: Type1ProductConfigId serial: <superuser/root required> 
  Mobo: HP model: 832B v: 23.61 serial: <superuser/root required> 
  UEFI: Insyde v: F.42 date: 08/06/2018 
CPU:
  Dual Core: Intel Core i3-7020U type: MT MCP speed: 2300 MHz 
  min/max: 400/2300 MHz 
Graphics:
  Device-1: Intel HD Graphics 620 driver: i915 v: kernel 
  Device-2: AMD Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / 
  Radeon 520 Mobile] 
  driver: radeon v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: ati,modesetting,radeon 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.0.8 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  driver: r8169 
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi 
Drives:
  Local Storage: total: 480.80 GiB used: 32.14 GiB (6.7%) 
Info:
  Processes: 208 Uptime: 7m Memory: 3.76 GiB used: 1.20 GiB (31.9%) 
  Shell: bash inxi: 3.0.38
  
  OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8
  (run on discrete gpu):
  OpenGL ES 3.0 Renderer: AMD HAINAN (DRM 2.50.0, 5.4.0-42-GENERIC, LLVM 10.0.0)

More information in archive, baby.

[randFreezeFiles.zip](https://github.com/godotengine/godot/files/5067533/randFreezeFiles.zip)
![freeze-catched](https://user-images.githubusercontent.com/52859138/90103150-bdcf0180-dd4a-11ea-836f-8aab44d5f3be.png)

**Comment by Zireael07** [comment] 2020-08-13 06:55
The report template is there for a reason. Fill it out (your OS, GFX card) because otherwise we have no way to help you.
PS. It seems you are opening two instances of Godot?

**Comment by volzhs** [comment] 2020-08-13 06:56
it seems the screen did not update while maximizing godot editor window.

**Comment by DannyWarp** [comment] 2020-08-13 07:00
all information in archive.

**Comment by DannyWarp** [comment] 2020-08-13 07:00
one instance of godot baby

**Comment by DannyWarp** [comment] 2020-08-13 07:04
> it seems the screen did not update while maximizing godot editor window.

yes

**Comment by akien-mga** [comment] 2020-08-13 08:57
Please fill the issue template as requested:
```
<!-- Please search existing issues for potential duplicates before filing yours:
https://github.com/godotengine/godot/issues?q=is%3Aissue
-->

**Godot version:**
<!-- Specify commit hash if using non-official build. -->


**OS/device including version:**
<!-- Specify GPU model, drivers, and the backend (GLES2, GLES3, Vulkan) if graphics-related. -->


**Issue description:**
<!-- What happened, and what was expected. -->


**Steps to reproduce:**


**Minimal reproduction project:**
<!-- A small Godot project which reproduces the issue. Drag and drop a zip archive to upload it. -->
```

**Comment by DannyWarp** [comment] 2020-08-13 09:51
> Please fill the issue template as requested:
> 
> ```
> 
> 
> **Godot version:**
> 
> 
> 
> **OS/device including version:**
> 
> 
> 
> **Issue description:**
> 
> 
> 
> **Steps to reproduce:**
> 
> 
> **Minimal reproduction project:**
> 
> ```

really?

**Comment by DannyWarp** [comment] 2020-08-13 09:52
really?

**Comment by Calinou** [comment] 2020-08-13 12:15
Duplicate of https://github.com/godotengine/godot/issues/27669.

**Closed by Calinou** 2020-08-13 12:15 UTC

**Comment by DannyWarp** [comment] 2020-08-13 13:31
> Duplicate of #27669.

this no duplicate

**Comment by DannyWarp** [comment] 2020-08-13 13:31
> Duplicate of #27669.

freeze ALL ENGINE

**Comment by DannyWarp** [comment] 2020-08-13 13:32
stupid community

**Comment by Calinou** [comment] 2020-08-13 13:36
@DannyWarp I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.
