### ISSUE TITLE
AnimationPlayer's frame 0 auto trigger AnimationPlayer.stop()

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#94781] opened 2024-07-26 07:39 UTC
### Tested versions

v4.3.beta3.mono.official [82cedc83c]

### System information

Godot v4.3.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 5GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

My Scene's tree like this:
![image](https://github.com/user-attachments/assets/b1b7f71a-892d-4030-bf03-64bbbafbddc8)

and GDS like this:
![image](https://github.com/user-attachments/assets/44c12aa4-9965-46d1-b64c-75ae79f677df)

create animation like this:
![image](https://github.com/user-attachments/assets/9f2b0040-23e6-4344-b889-aa193bc4e77f)
Note: the first key was at time 0 and second key was at time 2.333

when push button:
![image](https://github.com/user-attachments/assets/60b7d1b8-27a5-4691-83a4-3741d75e8240)

I think it should prints:
![image](https://github.com/user-attachments/assets/45b03f54-8c49-44ab-96f5-d6b59b9d0e38)

but actually it prints:
![GIF 2024-7-26 15-30-39](https://github.com/user-attachments/assets/bfa9e586-7da0-4358-b794-e7bb1dcabd2f)

![image](https://github.com/user-attachments/assets/77260026-7262-44e9-bf3c-5238f7eaa2ac)

### Steps to reproduce

please run the MRP

### Minimal reproduction project (MRP)

[AnimationPlayerTest.zip](https://github.com/user-attachments/files/16388257/AnimationPlayerTest.zip)

**Comment by TokageItLab** [comment] 2024-07-26 08:14
Fixed by https://github.com/godotengine/godot/pull/94420 in RC1

**Closed by TokageItLab** 2024-07-26 08:14 UTC

**Comment by CsloudX** [comment] 2024-07-26 08:16
I'm test 4.3.rc1, there was this issue too.

**Comment by akien-mga** [comment] 2024-07-26 10:19
I can confirm that the issue is reproducible in 4.3.rc1, as well as 4.2.stable (so it's not a regression).

But I don't think it's a bug.

The first print on app start comes from reading the value in the scene file and setting it. The setter gets triggered, that's expected. Your scene file has "world" as the default value for `tag`.

Then playing the animation prints "hello" "world" as expected.

Then calling `AnimationPlayer.stop()` resets the animation to position 0, which triggers the setter again. That's intended and documented behavior: https://docs.godotengine.org/en/stable/classes/class_animationplayer.html#class-animationplayer-method-stop

![image](https://github.com/user-attachments/assets/da3e5e8a-93bb-42c6-9c94-fa1184d273c5)

You can use `stop(true)` if you don't want it to reset.

And for the first print, `world` was saved in the scene while playing the animation in the editor. The "Reset on save" feature is supposed to reset it to an empty string as in your `RESET` animation, but for some reason that wasn't working well? After disabling it and re-enabling it it fixed the problem for me.

**Comment by CsloudX** [comment] 2024-07-26 10:25
@akien-mga Thanks.
use stop(true) resolved the second problem.

But first problem I can't resolve:
![GIF 2024-7-26 18-23-54](https://github.com/user-attachments/assets/499eab66-6763-429c-8315-0320dd18be51)

**Comment by akien-mga** [comment] 2024-07-26 10:35
It seems like the value of Current Animation in the AnimationPlayer will impact what gets saved on reset.
If you change it to "RESET", it should solve the problem. Alternatively, unset the Active property, and set it active from code when you want the value to be changed.
