### ISSUE TITLE
The Theme editor panel cannot be resized

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#31999] opened 2019-09-05 22:41 UTC
Godot 3.1.1

When you create a `Theme` resource from the inspector, the theme editor opens:

![image](https://user-images.githubusercontent.com/1311555/64388281-803fff80-d036-11e9-999e-ce5469b4142e.png)

But it cannot be resized vertically. The handle doesn't react.

The only way I found so far is to collapse the theme editor by clicking on `Theme` at the bottom, and reopen it again. Note: when it reopen, it is also taller.

If you use the inspector arrows to go to the previously edited object, that makes the theme editor close, which is normal. But if you go back to the theme, it comes back into its "smaller" size and returns in its non-resizeable state.

**Comment by akien-mga** [comment] 2019-09-23 06:31
That's fixed in the master branch:
![Screenshot_20190923_082735](https://user-images.githubusercontent.com/4701338/65405349-0486d680-dddc-11e9-8026-e02b3dfe0799.png)

Duplicate of #29056, fixed by @YeldhamDev in #29074.

The default height could likely be tweaked so that everything is visible by default though, providing it doesn't take up more than half the viewport height.

**Closed by akien-mga** 2019-09-23 06:31 UTC
Labels: bug, topic:editor
