### ISSUE TITLE
Viewport "Clear mode" isn't disabling clearing the render target

### ISSUE THREAD

**Issue by chiguireitor** [godotengine/godot#33831] opened 2019-11-23 01:09 UTC
**Godot version:**
v3.2 - 28613ab8c

**OS/device including version:**
Ubuntu Linux 19.10
Linux Kernel 5.3.0.19-generic

**Issue description:**

When setting a Viewport render target clear mode to never, after clearing it for the first time, it keeps cleaning the buffer on each frame, not accumulating renders.

**Steps to reproduce:**

1. Create a viewport
2. Change Clear mode to Next frame
3. Disable Next frame (as it isn't deactivated automatically)
4. Framebuffer on the render target keeps getting cleared each frame

**Minimal reproduction project:**
N/A

**Comment by clayjohn** [comment] 2019-11-23 02:21
Duplicate of https://github.com/godotengine/godot/issues/33351

**Comment by martinruefenacht** [comment] 2020-05-12 21:31
@clayjohn I don't think it is a duplicate of #33351.

This happens to me when I set the viewport clear mode to Never as well.
My viewport is rendering a 3D scene and the buffer is always cleared, no matter which clear_mode I have set.

**Comment by martinruefenacht** [comment] 2020-05-12 21:48
[Uploading viewport_clear_test.zip…](just run the main scene)

There is a 2D test and a 3D test in this test file. Transperant Bg for the viewport is important, without it the drawn makes sense. With it enabled this seems to be a bug.

**Comment by clayjohn** [comment] 2020-05-12 21:50
@martinruefenacht I think it has the same underlying cause, I'll investigate.

**Comment by martinruefenacht** [comment] 2020-05-12 21:58
That may be true, I don't know the internals.

The other issue seems to be related to the scripting side though. And in my case 2D works fine, but 3D is bugged.

**Comment by clayjohn** [comment] 2020-05-13 05:56
So, I can reproduce the issue. However, I don't think we should do anything about it. Right now the API for 3D is a little different than for 2D. For 2D it makes sense to control render target clearing in the Viewport. For 3D it is controlled in the environment's ``background`` property. Setting the environment's background to ``keep`` ends up doing exactly what you are looking for. If we were to force disable clearing, it would be unclear what the behaviour should be when the ``background`` property is `` clear color``. If the Viewport is set to clear ``never`` and the ``background`` is set to ``sky``, then the entire screen is covered anyway and it doesn't matter what the Viewport clear setting is, similarly if the background is set to ``clear color`` it should clear color regardless of the Viewport setting. 

That being said, this should be documented that the ``clear`` setting is intended for 2D usage.

**Comment by martinruefenacht** [comment] 2020-05-13 08:01
@clayjohn Fair enough! This does work.

One question remains though. How do you initially write a full background color to the viewport? Since there is no "Once" clear mode it is not possible to assign a white (or some other color).

I am using this to replicate mudrunner/snowrunner dynamic ground movement.

**Closed** 2020-09-03 06:01 UTC
Labels: documentation, junior job, topic:rendering
