### ISSUE TITLE
Code completion (type inference?) not working for custom types

### ISSUE THREAD

**Issue by essial** [godotengine/godot#74888] opened 2023-03-14 02:27 UTC
### Godot version

4.0

### System information

MacOS

### Issue description

When calling a function that has a custom class, the return type is disregarded unless I explicitly cast the result to the type in the editor (breaking code completion)...

I have this function defined in a global class:
![image](https://user-images.githubusercontent.com/242652/224876860-0f9b4695-ab8f-4da5-b52b-8b20df3ea52f.png)

When I try to use the value returned by it, I get incorrect code completion:
![image](https://user-images.githubusercontent.com/242652/224876903-58bff677-575a-4501-8e84-dc1174230f44.png)

Creating a new variable of the same type works (in the same file)
![image](https://user-images.githubusercontent.com/242652/224876924-d0601926-8d23-4d20-bb9a-8ce9a1714518.png)

And if I cast the type to itself it also works...
![image](https://user-images.githubusercontent.com/242652/224876948-0ffd628b-5dbf-49ea-9722-28c82a7b2b88.png)

### Steps to reproduce

Create a custom class with class_name.
Create a function in a global scene that returns an instance of that class type.
Try to reference the return value and see code completion is broken.

### Minimal reproduction project

I've provided specific screenshots describing the issue.

**Comment by vnen** [comment] 2023-03-14 14:36
> When I try to use the value returned by it, I get incorrect code completion:

BTW, is this really "incorrect" or just "incomplete"? The screenshot shows methods for `RefCounted` which is the default base type if you don't use `extends`.

**Comment by Piralein** [comment] 2023-03-14 15:47
Did a quick test, is your PlayerManager an autoload?

Using the function in the same file works,
using a class instance works,
using a static function works,

using an autoloaded class **doesn't** work.

**Comment by essial** [comment] 2023-03-14 16:03
Yes, PlayerManager is autoloaded as it needs to basically be a singleton for the instance. Is there an alternative to AutoLoad for static instances (singletons) or is this a legit bug with auto loaded instances?

Great find @Piralein!

**Comment by essial** [comment] 2023-03-14 16:06
Here's my autoload if it's any help:
<img width="620" alt="Screenshot 2023-03-14 at 12 06 30 PM" src="https://user-images.githubusercontent.com/242652/225066428-c191b111-47d8-4eb8-81c1-dd2b3636e3f5.png">

**Comment by vnen** [comment] 2023-03-14 17:09
> I believe so (in my opinion) because it's explicitly typed to the class, which has those properties. Using a variable specifically declared as PlayerState does _not_ include RefCounted properties. You're a godot dev, so please correct me if I'm wrong!
>
> I have a class, PlayerState which is in a PlayerState.gd file that has no extends at all. Simply `class_name PlayerState` at the top, followed by the vars which are the properties of the instance.

If you don't use `extends` it behaves as if you had used `extends RefCounted`, since that's the default base. The fact that it does not show members from RefCounted is also a bug, because it should list members of base classes (which also includes `Object`).

There's definitely something odd going on given it's detecting something (RefCounted) but not the actual class.

**Comment by essial** [comment] 2023-03-14 17:22
Awesome, I though I was going crazy and doing something horribly wrong. I just finished refactoring my entire codebase to use strongly defined class types and was worried I wasted a bunch of time. Thanks for figuring out what the specific problem is!

**Comment by essial** [comment] 2023-03-15 04:30
More strangeness...
<img width="524" alt="Screenshot 2023-03-15 at 12 28 51 AM" src="https://user-images.githubusercontent.com/242652/225206723-34f4666f-2b87-4062-a488-cc5231b611f0.png">
Globals is another auto loaded scene, and ITEM_TYPES is an enum defined in that scene. I know I need to move the enum out to its own file, but this is really strange stuff.

In this specific case the gdscript its in is NOT autoloaded and just has a class_name.

**Comment by santibag** [comment] 2023-07-23 12:20
v4.1.stable.official [970459615]
It would be so good if this gets fixed.

It doesn't have to have class keywords. If you defined a var or func, it's not suggested in a different script's code completion. Along with increasing the risk of typos, it adds additional steps for writing correct code.

I'm a relatively new dev. When I learned about type hints, I started using them too. Because getting completion saves many things.

**Comment by dalexeev** [comment] 2023-07-23 13:51
@santibag In this particular case, the behavior is expected. The `get_node()` method, and also `$` and `%` shorthands have `Node` type, not a specific subtype. GDScript does not know what type the node will be at runtime and whether the node be at all.

Autocompletion _can_ give you correct suggestions for node paths, variables, functions, etc. only if this scene is the currently open one in the editor. This does not work for other scenes as the same script can be attached to different scenes. See also godotengine/godot-proposals#1935.

To workaround this, I recommend using `@onready` variables with a specified static type, instead of using the `$` notation multiple times in the function body. It also improves performance in frequently called functions like `_process` and loops.

Also, some people use the `as` operator (like `($Label as Label).text`), but I prefer not to use it in this manner because it is 1. more verbose, 2. less optimal, extra code at runtime, 3. the `as` operator hides errors by silently casting the object to `null` on type mismatch.

**Comment by wagnerfs** [comment] 2023-09-19 03:54
This is actually quite annoying, having code complete on normal custom classes with properties of other custom classes work just fine, you put it as Autload and bam, it doesn't work anymore, to make matters worse there's not work around to that, managing a project with a couple autoloads and several properties/methods with custom classes.

I'm almost certain this seems like a regression since I don't think I used to have this issue before 4.1.
For now I'm updating my code to do casting on those, but I'm not quite sure if this kind of casting has any hit on performance.

**Comment by Nukiloco** [comment] 2023-09-29 05:06
It felt like I been dealing with this bug since 3.x, even having type hints as your variables doesn't allow the autocomplete to work. Probably one of the most annoying bugs in this engine so far since most of my scripts in most of my projects point to an autoload so I basically never get any type hints at all. I usually have to do special key combos like Shift Alt O, and go between the files, just to check out the types. This happens to not just functions but variables as well in autoload. Wasn't there another issue on autoload not returning any type hints in a different way?

**Comment by HolonProduction** [comment] 2023-11-22 00:51
So looking at this I found three issues in the code. Two of which should be easy to fix:

1. Easy to Fix: `_guess_identifier_type` knows the statically annotated type, but still tries to guess a type from the last assigned expression. However this interfered type should only be returned if it is compatible with the static one and more specific.
2.  Easy to Fix: `_type_from_property` doesn't handle custom class names in the `PropertyInfo` it just returns a native type with the native class `PlayerState`. Since there is no such native class no auto completion is provided.

Those two things can be changed at one point and will fix most of the cases dealing with this. (That said before working on that, other issues and PR's should be cross referenced since the auto completion issues tend to overlap and I also kinda remember other issues and PR's regarding autoloads.

3. Hard to fix: Since I'm a fan of `preloaded` types over global class names I also looked into this. As long as we statically type everything in our script and properly fix 1. we should be fine. But sadly we cannot interfere the return type from the autoload. The autoload is resolved as `SCRIPT` type not as `CLASS` type, meaning we cannot use the GDScript internals and only have access to `get_property_list`. This limits the type information to a `PropertyInfo` which has no good way to store Script types that are not globally named. (There are ways for `Resources` and `Nodes` through hints but I don't know if they support custom scripts and also this feels very hacky).

The two solutions I see for this is either expanding `PropertyInfo` or resolving autoloads as `CLASS` types. I think the later sounds more feasible but I lack the knowledge to pull it off. Also since this is only a problem for users that use static typing though `preload` in their autoloads, but no static typing in the rest of their scripts, this sounds more like an edge case without priority.

**Comment by wagnerfs** [comment] 2023-11-29 17:18
Just out of curiosity, is there a reason why `PropertyInfo` stores the native class name instead of the `class_name` defined by the user when available?

**Comment by HolonProduction** [comment] 2023-11-29 18:03
> Just out of curiosity, is there a reason why `PropertyInfo` stores the native class name instead of the `class_name` defined by the user when available?

Could you provide the exact case were this happens?

With the following:
![image](https://github.com/godotengine/godot/assets/99511741/33d6bb6f-725e-4e71-86a5-2a1307af1c59)

I get this as output:
```
{ "name": "test", "class_name": &"State", "type": 24, "hint": 0, "hint_string": "", "usage": 4096 }
```

Would be good to look into the cases were this does not get propagated right.

**Comment by HolonProduction** [comment] 2023-11-29 18:06
Also changing `get_instance_base_type` is the wrong approach. It is the native type which needs to be instantiated. What needs fixing are the cases were the Global Class name gets not added to the property info.

**Comment by wagnerfs** [comment] 2023-11-29 23:57
> Also changing `get_instance_base_type` is the wrong approach. It is the native type which needs to be instantiated. What needs fixing are the cases were the Global Class name gets not added to the property info.

It's because, like you mentioned, autoloads are treated like `SCRIPT`, and when it access its properties, things like
```gdscript
var a1: CustomType
var a2: Node
```
all properties with custom types become the native class they extend, so `a1` type would be `Node` and that's why this kinda code doesn't complete properly:
```gdscript
Autoload.a1.
```
as for your example, I was talking about the source, apparently, if your property is of type `SCRIPT` or `GDSCRIPT`, `class_name` will always return the native/extended name instead of the current user defined name

**Comment by wagnerfs** [comment] 2023-11-30 17:28
Try this:

```gdscript
#thing.gd
extends Node
class_name StuffThing

var bla: int = 10
```
```gdscript
#autoload.gd
extends Node

var a: StuffThing
```
```gdscript
#any other file
extends Node2D

func _ready():
    var l = Autoload.get_script().get_script_property_list()
    print(l)
```

outputs:
```
[{ "name": "autoload.gd", "class_name": &"", "type": 0, "hint": 0, "hint_string": "res://autoload.gd", "usage": 128 }, { "name": "a", "class_name": &"Node", "type": 24, "hint": 0, "hint_string": "", "usage": 4096 }]
```

as you can see, var `a` is of type `Node`, not StuffThing

**Comment by HolonProduction** [comment] 2023-11-30 18:13
Can't reproduce :confused:

```
[{ "name": "autoload.gd", "class_name": &"", "type": 0, "hint": 0, "hint_string": "res://autoload.gd", "usage": 128 }, { "name": "a", "class_name": &"StuffThing", "type": 24, "hint": 0, "hint_string": "", "usage": 4096 }]
```

v4.3.dev.custom_build [d76c1d0e5]

**Comment by wagnerfs** [comment] 2023-11-30 18:28
> Can't reproduce 😕
> 
> ```
> [{ "name": "autoload.gd", "class_name": &"", "type": 0, "hint": 0, "hint_string": "res://autoload.gd", "usage": 128 }, { "name": "a", "class_name": &"StuffThing", "type": 24, "hint": 0, "hint_string": "", "usage": 4096 }]
> ```
> 
> v4.3.dev.custom_build [[d76c1d0](https://github.com/godotengine/godot/commit/d76c1d0e516fedc535a2e394ab780cac79203477)]

OH, good call, I've been testing around 4.1 branch not master, my bad, sorry

**Closed** 2024-01-17 17:58 UTC
Labels: bug, topic:gdscript, topic:editor, usability
