### ISSUE TITLE
GLES3 - Depth sorting problem with overlapping transparent textures

### ISSUE THREAD

**Issue by kubajz22** [godotengine/godot#43253] opened 2020-11-01 03:54 UTC
**Issue description:**
Hi, I'm using Godot 3.2.3, GLES3 and I noticed that when you have multiple models with materials marked as Transparent and you add to the scene a source of light that can cast shadows, this will happen: https://youtu.be/2uhuNK9D7mg . As you can see, those leaves that are further away from the camera start to appear in front of the closer ones. I colored them red so it's really obvious. This only happens when there are multiple transparent objects with opaque pre-pass enabled and they are lit using a light source that casts shadows. The "Do not receive shadows" flag doesn't make a difference though. This issue is present on version 3.2.2 as well. When using the GLES2 renderer it behaves in the opposite way, rendering farther objects in front of closer ones when the depth draw mode is set to Opaque only.

**Godot version:**
3.2.3-stable

**OS/device including version:**
GPU: nVidia GeForce 1650 Mobile with nvidia-driver-450.80.02-0ubuntu0.20.04.2 driver
CPU: Intel core i5 9300H
OS: Linux Mint 20

**Steps to reproduce:**
Set up a scene with multiple overlapping objects which are configured as follows:
-Transparent flag enabled
-Depth draw set to Opaque pre-pass
-No alpha scissoring
Then add a directional light and enable shadows.

**Example project:**
[Depth_sorting_issue.zip](https://github.com/godotengine/godot/files/5470197/Depth_sorting_issue.zip)

**Comment by clayjohn** [comment] 2020-11-01 04:23
Do you mind uploading the MRP as a zip file? You can just drag and drop it into the comment. 

The link you provided has enough sketchy popups that I am uncomfortable downloading from it.

**Comment by kubajz22** [comment] 2020-11-01 04:48
Done. Didn't see those due to my overpowered adblock.

**Comment by volzhs** [comment] 2020-11-01 04:49
[Depth_sorting_issue.zip](https://github.com/godotengine/godot/files/5470207/Depth_sorting_issue.zip)
I made MRP smaller to 4.3MB

**Comment by EzraT** [comment] 2020-11-01 12:12
Can confirm, same thing happens on my system.
Linux Mint 20 x86_64
Intel i7-2600K
NVIDIA GeForce GTX 1060 6GB, driver 450.80.02

**Comment by Calinou** [comment] 2020-11-01 14:00
Related to https://github.com/godotengine/godot/issues/36669.

**Comment by kubajz22** [comment] 2020-11-08 22:11
Happens on Mesa Intel UHD Graphics 630 as well so it probably isn't a nVidia related issue.

**Comment by tinmanjuggernaut** [comment] 2021-07-18 22:28
The problem is related to the direction of the DirectionalLight and is limited to (caused by?) DirectionalLights. The renderer apparently orders by light direction instead of camera direction.

* Setup: Trees w/ alpha textures for leaves, directional light with shadows. Light comes from the side of the red trees. All are the same tree object, with two different materials. The only difference is the red tint. depth_draw_alpha_prepass enabled, along with alpha in the texture. 

![image](https://user-images.githubusercontent.com/632766/126083129-6eab80aa-bbf2-40a5-86a3-218a5bb34c2d.png)

* View with the light at our backs. Depth is correct.

![image](https://user-images.githubusercontent.com/632766/126083157-c862671b-412e-4ae3-b9e3-ba57a4addf90.png)

* View towards the light. Depth is reversed.

![image](https://user-images.githubusercontent.com/632766/126083365-a0c6e87d-5acb-4b8f-9f2e-4fa4aa598461.png)

* If I rotate the whole block and look at the trees perpendicular to the light, then the part of the camera that faces the light is wrong, and the half that faces away is correct.

![image](https://user-images.githubusercontent.com/632766/126083290-cd17ac56-5804-48bc-b349-cdf23f5f79f0.png)

* If I disable the directional light and use ambient light, it occludes properly. (not shown)

* If I put a giant spotlight in the sky, it also occludes properly, however I get horrible shadow bias banding on the flat plane ground. (shown below)
 
* If I use both the directional light and the spotlight, it shows the red trees through the green. (not shown)

![image](https://user-images.githubusercontent.com/632766/126083795-e941cd04-f450-4aca-af22-417206174685.png)

* Enabling alpha scissors is a workaround, especially if the default shader is fixed as in #36669. 

![image](https://user-images.githubusercontent.com/632766/126083201-176b9f11-de50-415d-97d8-147833c8b1ca.png)

* However alpha scissors is ugly. I'm working with AAA assets, with the transparent pipeline on the right. The left is the best I can make them look with alpha scissors. Yikes. It only looks good close up. Far away and it looks like PS1 style graphcis.

![image](https://user-images.githubusercontent.com/632766/126083326-2d30a9b7-7837-4843-9a22-39c2a1c56163.png)


Godot 3.3.2
WIn64
Nvidia GTX 1060

**Comment by tinmanjuggernaut** [comment] 2021-07-20 12:02
More specifically, it is the shadows. It always impacts DirectionalLight, and it temporarily* affects OmniLight and SpotLight.

DL Shadow on/off and light angle determines if it occludes properly.

With DL, none of these things have any effect:
- Unshaded mode
- Unshaded render mode in the material
- Vertex lighting
- Orthographic view
- Directional Light shadow settings
- DirectionalShadow modes or other settings except max distance

----

Reducing DirectionalShadow Max Distance does occlude properly if the distance is set lower than the distance between the camera and the far tree. e.g. 2. Then as you move the camera closer and farther, the back one will overlap or not depending on the distance. When overlapping, you can move the closer tree and it makes no difference. It only depends upon the camera and the far tree distance.

\*Temporary effect
* I switched to an OmniLight, then retested SpotLight and they do the same thing. Here I have two trees. The omnilight has a range of around 10-20. If I push the light outside of the lighting range, green always occludes. 
* At any angle where the light is on the green tree side of the perpendicular line between the trees, green occludes properly all of the time. 
* If I push the omni/spot light back just over that line, the red tree will overlap. However, it only does it while I'm moving the light. If I let go of the mouse button, the green snaps in front of the red. If I hold the mouse down but stop moving, it takes about 1 second, then the green snaps in front of the red. Once it's been corrected, I can rotate the camera around the pair and it always occludes properly.

![image](https://user-images.githubusercontent.com/632766/126314405-eefb0c5d-827a-48d3-ac82-7da51c8eb741.png)

**Comment by Calinou** [comment] 2021-07-20 18:33
> However alpha scissors is ugly. I'm working with AAA assets, with the transparent pipeline on the right. The left is the best I can make them look with alpha scissors. Yikes. It only looks good close up. Far away and it looks like PS1 style graphics. It makes the 3D mesh look like a low res billboard.

[Alpha hashing, alpha antialiasing alpha to coverage](https://github.com/godotengine/godot/pull/40364) can be implemented to improve the appearance of alpha scissor. These can likely be backported to `3.x` for (alpha hashing and alpha antialiasing at least).

**Comment by tinmanjuggernaut** [comment] 2021-07-20 19:19
> In general, using alpha blending for vegetation will always be a difficult thing to get right due to sorting issues.

@Calinou If we couldn't handle "difficult", we wouldn't have chosen to develop in 3D.

I appreciate the workarounds, however I'm interested in fixing this bug so I don't have a shoddy looking game. Other engines have beautiful alpha. Godot also has it with 2/3rds of the light types, and 50% of the directional light. I'm convinced it's a simple bug, though finding it is quite challenging as I'm out of my element in the rendering pipeline.

Here's what I've found so far. After this line:
https://github.com/godotengine/godot/blob/f4e3701893bdf6b304ee114745def2f8ac4aa822/drivers/gles3/rasterizer_scene_gles3.cpp#L4565

I wrote a function to print out the alpha render_list (last 3 indices of elements). I also print out `element->instance->depth`.

If DL shadow is disabled, the depth of the trees change, and so the renderlist gets sorted with the farthest away rendered first. I see values like 4-12 as I move the camera. 

If DL shadow is enabled, the render list is always green then red, with the light behind the red. The depth of the objects **always** reports the same values.  green tree: (-7.72), red tree: (-11.24)!

So that explains why it's sorting wrong half of the time. The depth value doesn't update. 

Now why that is, I'm still searching for the cause. I'd appreciate help on this.

**Comment by tinmanjuggernaut** [comment] 2021-07-20 20:18
Looks like a problem in VisualServer, not the rasterizer. The scene objects already have their distance set (wrong or right) when the visual server calls the rasterizer and passes along the culled instances to `render_scene` here:

https://github.com/godotengine/godot/blob/f4e3701893bdf6b304ee114745def2f8ac4aa822/servers/visual/visual_server_scene.cpp#L2189

**Comment by tinmanjuggernaut** [comment] 2021-07-21 21:07
In `VisualServerScene::_prepare_scene()` all object instances calculate and store their distance to the camera in `instance->depth`.
https://github.com/godotengine/godot/blob/f4e3701893bdf6b304ee114745def2f8ac4aa822/servers/visual/visual_server_scene.cpp#L2015

**Directional Lights**
For DLs, every frame, shadows are calculated by checking the distance to the DL and storing it in the same `instance->depth` variable, overwriting it.
https://github.com/godotengine/godot/blob/f4e3701893bdf6b304ee114745def2f8ac4aa822/servers/visual/visual_server_scene.cpp#L2068

The distance to the camera is never recalculated. Instead, the wrong information is passed to the renderer, which sorts incorrectly depending on angle. 

OpenGL or other functions in the renderer may be correcting depth sort order for opaque objects, I haven't tested, but it does not do so for alpha objects, which are sorted based upon the information from the visual server.


**Omni Lights**
For omnis, the exact same thing happens. `Instance->depth` is calculated relative to the final plane of the shadow cube, overwriting the camera depth. This incorrect information is then passed to the renderer, and for that frame at least, transparent objects are sorted incorrectly depending on angle.

What makes omnis work is that they only update the shadows if the shadows are marked dirty. So the instance depth is wrong for one frame, then corrected every frame after until the shadows are recalculated.

If I tell Omnis to recalculate every frame like DLs, depth is sorted incorrectly as well.
https://github.com/godotengine/godot/blob/f4e3701893bdf6b304ee114745def2f8ac4aa822/servers/visual/visual_server_scene.cpp#L2165


So I see four possible solutions:
1. Initial camera depth is not used before it's overwritten. Move this calculation after shadows are calculated. 
1. Recalculate instance depth a second time after shadows are calculated.
1. Calculate shadow depth on a copy or an additional variable so as to not to overwrite the camera depth.
1. Use dirty shadows for DLs also and only update periodically.

1 seems the easiest and least intrusive. I have implemented it and so far everything works. Is this the best solution? I'll write up a PR for review.

Here the camera is facing towards the directional light, with shadows enabled. Front trees properly occlude back trees. Opaque house, terrain, and trunks are properly occluded everywhere, and quality alpha without using alpha scissors anywhere (which also works as any normal opaque object). Omnilights and spotlights also work better as they never occlude improperly

![image](https://user-images.githubusercontent.com/632766/126558559-ab3f7a67-4f23-421c-ac63-bb2ebe6f3d4b.png)

(Image from my game, see my profile.)

**Comment by tinmanjuggernaut** [comment] 2021-07-21 21:30
I did find one instance where incorrect sort ordering still occurs:

![image](https://user-images.githubusercontent.com/632766/126562195-de8ecde0-36ee-4879-b947-c4b9861cc8d8.png)

You can see it occurs when one object is within another. Vertex, face, or pixel-based depth rendering would be needed to fix this and the VisualServer only calculates based on entire objects. It doesn't appear that the rendering pipeline even considers this possibility either.

**Comment by clayjohn** [comment] 2021-07-21 21:49
@tinmanjuggernaut 

> You can see it occurs when one object is within another. Vertex, face, or pixel-based depth rendering would be needed to fix this and the VisualServer only calculates based on entire objects. It doesn't appear that the rendering pipeline even considers this possibility either.

Indeed, the rendering pipeline only does per-object depth sorting. Per-vertex or per-pixel are leagues more complex and usually require some form of Order Independent Transparency (which comes with its own issues and limitations).

> 1 seems the easiest and least intrusive. I have implemented it and so far everything works. Is this the best solution? I'll write up a PR for review.

I agree, please make a PR so myself and others can review. :)

Great work by the way!

**Comment by tinmanjuggernaut** [comment] 2021-07-22 00:00
> Indeed, the rendering pipeline only does per-object depth sorting. Per-vertex or per-pixel are leagues more complex and usually require some form of Order Independent Transparency (which comes with its own issues and limitations).

Unlike alpha-scissoring, this is an acceptable tradeoff. A few colliding trees here and there, no one's going to notice.

> Great work by the way!

Thanks! I'm very happy with the results. This bug has been one of the worst problems with the renderer forever. 
PR is in and ready.

**Comment by tinmanjuggernaut** [comment] 2021-07-22 00:27
I was working off of 3.3. Apparently, there was a lot of work done in the 3.x branch on the VisualServer and/or renderer. This branch with my patch now occludes even the overlapping trees shown above!

**Comment by akien-mga** [comment] 2021-07-22 06:54
Fixed by #50721.

**Closed by akien-mga** 2021-07-22 06:54 UTC
Labels: bug, confirmed, topic:3d, topic:rendering
