### ISSUE TITLE
Cannot save files from asset library downloads using the Android editor

### ISSUE THREAD

**Issue by Scratchfan3ds** [godotengine/godot#75789] opened 2023-04-07 16:37 UTC
### Godot version

4.0.stable

### System information

Android 13 4 gb ram 64gb storage mali chip 

### Issue description

I cant download anything on the assetlib because:
![Screenshot_20230407_183331_Godot Editor 4](https://user-images.githubusercontent.com/127613195/230644800-918943aa-298b-4106-952d-5a3a220e620b.jpg)

### Steps to reproduce

Like maybe fix the issue please? :)

### Minimal reproduction project

It's not a project i want to download assets

**Comment by YuriSizov** [comment] 2023-04-07 16:51
> Like maybe fix the issue please? :)

The "Steps to reproduce" section is for you to describe how to reproduce the issue, which steps to take to see the problem that you describe.

**Comment by Calinou** [comment] 2023-04-07 16:57
- Related to https://github.com/godotengine/godot/issues/75716.

**Comment by Scratchfan3ds** [comment] 2023-04-08 08:15
So would anyone fix it?

**Comment by Calinou** [comment] 2023-04-08 16:59
> So would anyone fix it?

We don't know what's causing this issue yet, so there is no way for us to fix the issue. In the meantime, you can download assets from the [asset library website](https://godotengine.org/asset-library) and extract the downloaded ZIP files using a file manager application on Android.

**Comment by whendricso** [comment] 2023-05-22 18:17
I was able to install assets in my project on my Galaxy Tab S2 SM-T817V

However, doing so was difficult due to a separate issue where the confirmation dialogue did not scale with the screen, and numerous errors were generated in Output:
![Screenshot_20230522-140549](https://github.com/godotengine/godot/assets/3516852/fbf35a91-48f8-4d77-be04-026d21e7dbf0)
![Screenshot_20230522-140628](https://github.com/godotengine/godot/assets/3516852/ff992ec6-ff4e-4fda-a16b-e46cf1ae0418)

The files did download into the appropriate folder in the project, despite the errors.

**Comment by m4gr3d** [comment] 2023-06-16 04:56
I'm also unable to reproduce the issue in the latest version of the Android editor. The files download in the right location when I try to replicate the issue.

Closing for now, but feel free to re-open if you are able to replicate the issue in the latest version of the Android editor.

**Closed by m4gr3d** 2023-06-16 04:56 UTC
Labels: bug, platform:android, topic:editor, topic:porting, topic:assetlib, needs testing
