### ISSUE TITLE
Bullet engine: Rigidbody Flickering when inherits parent position

### ISSUE THREAD

**Issue by DrZanuff** [godotengine/godot#14337] opened 2017-12-06 21:12 UTC
**Windows 10 64bits, Godot 3.0 Beta 1

Issue description:
When a Rigidbody inherits its parent's position, the Rigidbody position start flickering until its sleeps.

Steps to reproduce:
Create a Area, Position3D, spatial(Any node with 3D coordinates). Add a rigidbody with gravity scale set to 0. Try to move the parent and the rigidbody positions start to flick. With GodotPhysics it works as expected.

Link to minimal example project:
[Godot3Bug Bullet Engine.zip](https://github.com/godotengine/godot/files/1536902/Godot3Bug.Bullet.Engine.zip)

**Comment by akien-mga** [comment] 2017-12-06 21:19
CC @AndreaCatania

**Comment by akien-mga** [comment] 2017-12-11 09:29
Confirmed in the current master branch.

**Comment by AndreaCatania** [comment] 2017-12-11 09:34
This works with Godot physics engine but it is not intended to work. The rigid body should be always moved by setting Forces and Torques.

**Comment by kubecz3k** [comment] 2018-01-15 10:34
As far as I can tell @AndreaCatania is right and this is not a bug. Its will work well if RigidBody mode will be changed to `kinematic` for the purpose of such manual position change (for example for character climbing implementation).

**Comment by reduz** [comment] 2018-01-18 11:11
I dont think this is a bug either. I guess godot physics is more permissive, but this is not the intended use so closing this issue.

**Closed by reduz** 2018-01-18 11:11 UTC
Labels: bug, confirmed, topic:physics
