### ISSUE TITLE
Animation Playback Track plays only the first frame of the animation

### ISSUE THREAD

**Issue by Dev0mi** [godotengine/godot#94146] opened 2024-07-09 18:43 UTC
### Tested versions

- Reproducible in: 4.3.beta2, 4.2.2.stable - Not reproducible in: 4.2.1stable, 4.2.stable, 4.1.3.stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon (TM) RX 480 Graphics (Advanced Micro Devices, Inc.; 31.0.14037.17019) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Playing animation through Animation Playback Track doesn't work.

When you play an animation in an Animation Player form another Animation Player, using Animation Playback Track the animation updates only on the first frame[Problem 2], also the animation updates in the editor but only when you are scrubbing through the timeline [Problem 1].

![Godot_v4 2 2-stable_win64_HUR5F9xYuJ](https://github.com/godotengine/godot/assets/85759515/b04405c0-0827-4413-9f92-07e419356525)

### Steps to reproduce

Create a new project on the specified hardware.
Create two AnimationPlayer nodes and one Node to animate.
Animate the Node in the first Animation Player.
In the second Animation Player create an Animation Playback Track that plays the animation. [Problem 1]
Run the scene [Problem 2]

### Minimal reproduction project (MRP)

[MRP Animation Playback Tracks.zip](https://github.com/user-attachments/files/16147866/MRP.Animation.Playback.Tracks.zip)

**Comment by TokageItLab** [comment] 2024-07-09 19:05
Cannot reproduce in master (42e5b3ac2da07d2105c775977b39e6949c723ded)

**Comment by TokageItLab** [comment] 2024-07-09 19:17
It is probably related to https://github.com/godotengine/godot/pull/86661 and should have been fixed in 4.3, so I think it is incorrect to say that it does not work in 4.3.beta2.

**Closed** 2024-07-09 22:08 UTC
Labels: bug, needs testing, regression, topic:animation
