### ISSUE TITLE
TextEdit VScroll auto-jumping to new location on clicking.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#42762] opened 2020-10-13 03:45 UTC
3.2.3 Official

- Run project then follow these steps exactly.:
- Scroll to the bottom
- then click on the word "WEIRD".
- The TextEdit will auto-scroll up a few lines.

If you scroll to the bottom again and double-click the word "WEIRD", it will accidentally select the word "wheel", up a few lines.  The problem is even worse on the Android.
![first](https://user-images.githubusercontent.com/26915986/95811902-842a6080-0cd1-11eb-9b6a-a09f8da64859.png)
![second](https://user-images.githubusercontent.com/26915986/95811925-8ee4f580-0cd1-11eb-8cd5-104fabf401b0.png)

Here is a minimal project (note that there are no Line Breaks in the sentance tested)
[323.zip](https://github.com/godotengine/godot/files/5368812/323.zip)

My current project relies heavily on TextEdit controls and user input.  May I please get help fixing this?

**Comment by volzhs** [comment] 2020-10-13 03:49
duplicate of #41962

**Comment by ondesic** [comment] 2020-10-13 04:40
@volzhs
The issue may be the same but it does not auto-scroll to the top as the name of the other issue suggests.  If you add enough text it will simply move up a few lines instead of going to the top.

**Comment by volzhs** [comment] 2020-10-13 04:44
@ondesic yes. it's the same issue.
clicking a text in auto wrapped line makes the scroll moves.
it moves up to show the first character of the selected wrapped line.

**Comment by ondesic** [comment] 2020-10-13 04:50
Sorry, you posted while I was editing my post with more pictures

**Comment by volzhs** [comment] 2020-10-13 04:56
AFAIK, it needs to be fixed around here.

https://github.com/godotengine/godot/blob/a22c7eff0f3d443aa18cc962a6c50d066c3bdc2a/scene/gui/text_edit.cpp#L4001-L4007

in case anyone interests.

**Comment by Calinou** [comment] 2020-10-13 11:19
Duplicate of #41962.

**Closed by Calinou** 2020-10-13 11:19 UTC
