### ISSUE TITLE
TextureButton Click Masks: get rid of antique PNM files !

### ISSUE THREAD

**Issue by nylnook** [godotengine/godot#14700] opened 2017-12-15 11:48 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos Linux 64 bits, Godot 3 beta 1 compiled

**Issue description:**
Actual click masks in TextureButtons use the antique PNM format:
- which only a few modern image editors can modify (only Gimp), plus Imagemagick in command line, but only a few artists are able to use command line
- which seem to be easily corrupted, and randomly
- which in Godot do not document which [specific sub-format](https://en.wikipedia.org/wiki/Netpbm_format) is expected (ASCII, binary, which key, how to produce it)
- is not imported in Godot 3 (no .import file)
- flash "Unrecognised binary resource file error(s)" errors in the debugger

Please see downstream issue : https://github.com/flossmanualsfr/escoria/issues/9

A solution would be to implement #5432, but at least, allowing to use the far more widespread PNG file with only 2 indexed colors (black an white) instead would allow an alternative and a workaround.

**Steps to reproduce:**
Try with this minimal example [click-masks.zip](https://github.com/godotengine/godot/files/1572105/click-masks.zip)
or
Clone https://github.com/flossmanualsfr/escoria and look at the debugger

**Comment by nylnook** [comment] 2017-12-19 14:24
I'm sorry, this is not a feature proposal, this a bug report: under Android export at least, this generate black squares around TextureButtons with a Click mask.

**Comment by akien-mga** [comment] 2017-12-19 14:30
Well you formulated as a feature request. "Getting rid" of a feature/format is not a bug.

But it would be indeed nice to have another issue keeping track of the actual *bugs*. Whether fixing them implies deprecating PNM support to replace it by something else, we'll have to establish there.

**Comment by nylnook** [comment] 2017-12-19 14:34
Wrong formulation, my mistake, there is already two downstream bugs:
https://github.com/flossmanualsfr/escoria/issues/9
https://github.com/flossmanualsfr/escoria/issues/12
And we don't know if it's impacting export to HTML5....

I can report them again in the Godot tracker if you think it's better.

**Comment by akien-mga** [comment] 2017-12-19 14:38
An upstream bug report for flossmanualsfr/escoria#9 would be nice yeah; the other one looks like a duplicate in the end?

**Comment by nylnook** [comment] 2017-12-19 15:23
Ok for creating other reports : here is a minimal project example to test
[click-masks.zip](https://github.com/godotengine/godot/files/1572105/click-masks.zip)

I tested it, and it actually exports, but HTML5 give a lot of warnings:
[click-masks-HTML5-exports.zip](https://github.com/godotengine/godot/files/1572132/click-masks-HTML5-exports.zip)

Black squares on Android are not happening in this minimal example.

**Comment by nylnook** [comment] 2017-12-26 16:48
I'm sorry I titled the 3 bugs with PNM instead of PBM, it's confusing, but they are real and I'm not trying to waste your time, please reopen the 3 of them !

**Comment by akien-mga** [comment] 2018-01-03 09:36
Closing this one as split in the above three issues.

**Closed by akien-mga** 2018-01-03 09:36 UTC
Labels: feature proposal, topic:core
