### ISSUE TITLE
GDScript Assigning to a variable 'self' using a cast of type 'RefCounted' increases reference count twice

### ISSUE THREAD

**Issue by WildRackoon** [godotengine/godot#69504] opened 2022-12-02 18:18 UTC
### Godot version

4.0 beta6

### System information

Windows 10

### Issue description

When getting a reference to 'self' using a cast of type 'RefCounted' increases the reference counter twice instead of once.

Is this an Issue or a misconception around the casting mechanism ?
Should I consider other ways to save an Array of heterogeneous collection of RefCounted subclasses ?

### Steps to reproduce

Instance the following class: (Or just run the supplied project main scene)
```gdscript
extends RefCounted
class_name ReferenceIssueClass

func _init()-> void:
  # Showcase Expected behaviour with and without cast on other objects
  # This section prints 2 then 3
  var otherstuff = ConfigFile.new()
  print(otherstuff.get_reference_count())
  var ref_other : RefCounted = otherstuff as RefCounted
  print(otherstuff.get_reference_count())
  
  # This section prints 2 then 3
  var otherstuff2 = ConfigFile.new()
  print(otherstuff2.get_reference_count())
  var ref_other2 : RefCounted = otherstuff2
  print(otherstuff2.get_reference_count())
  
  # Expected behaviour on self without cast
  # This section prints 2 then 3
  print(self.get_reference_count())
  var ref_nocast : RefCounted = self
  print(self.get_reference_count())
  
  # Weird behaviour on self with cast
  # This section prints 3 then 5
  print(self.get_reference_count())
  var ref_cast : RefCounted = self as RefCounted
  print(self.get_reference_count())
```
Prints to console:
```
2
3
2
3
2
3
3
5 # Should be 4 ?
```

### Minimal reproduction project

[selfreferenceissue.zip](https://github.com/godotengine/godot/files/10143382/selfreferenceissue.zip)

**Comment by adamscott** [comment] 2022-12-02 21:20
For better formatting, please use the typing system of Github code blocks:

\`\`\`gdscript
[code here]
\`\`\`

**Comment by adamscott** [comment] 2022-12-02 21:58
Confirmed on master ([6f1d4fd](https://github.com/godotengine/godot/commit/6f1d4fd8871155efcb29d115a7168879948e1cf3)).

This doesn't only happen when using `self` though. Could reproduce with the `ReferenceIssueClass` instance of the MRP in `init.gd`.

```gdscript
extends Node

# Called when the node enters the scene tree for the first time.
func _ready():
  var ref: = ReferenceIssueClass.new()
  prints("ref count: %s" % ref.get_reference_count())  # 1
  var other_ref: = ref
  prints("ref count: %s" % ref.get_reference_count())  # 2
  prints("--")
  prints("ref count: %s" % ref.get_reference_count())  # 2
  var other_other_ref: = ref as RefCounted
  prints("ref count: %s" % ref.get_reference_count())  # 4
  prints("--")
```

CC @anvilfolk @rune-scape

**Comment by anvilfolk** [comment] 2022-12-12 01:02
I've been trying to figure this one out, but I really don't understand most of these parts so if you do, feel free to get it done and I will badger you with questions afterwards ;)

I just tried this

```GDScript
	print("before: ", self.get_reference_count()) # Prints number 3
	var ref_cast = self as Object
	print("after: ", self.get_reference_count()) # Also prints 3
```

Probably not exactly desired either? Unless it's a feature & not a bug.

There's a lot of type magic happening in the cast `OP`s in the VM. The cast itself seems to define whether the `ASSIGN_OP` recognizes that it is working with a `RefCount` object.

**Comment by adamscott** [comment] 2022-12-12 01:13
This is normal, @anvilfolk. `Object` is not `RefCounted`, so it will not augment the reference count. 🙃

**Comment by anvilfolk** [comment] 2022-12-12 01:15
Ok, so it's got to be something about how `self` is interpreted as `RefCounted` somehow. The increment in refcount doesn't happen to during `OPCODE_CAST_*` for non-`self` indexes.

**Comment by rune-scape** [comment] 2022-12-12 03:21
@anvilfolk i think that code snippet should actually increase the refcount
i ran that code snippet and ref_cast ends up null? so that's probably why it doesn't increase 🙃

**Comment by anvilfolk** [comment] 2022-12-12 03:28
Yeah, as far as I can tell the VM doesn't actually run a cast at all. I am thoroughly confused :)

**Comment by anvilfolk** [comment] 2022-12-12 04:29
I may have figured it out.

The `OP_CODE_*` cast VM commands do a copy from one location to another. Behind the scenes, these things are stored as Variants storing an object. Somehow, at this point in the VM, these variants are known to be `RefCounted`, and therefore, when the vm does `*dst = *src`, this increases the ref count.

I believe the difference between `self` and other objects appears to be that `self` has a permanent address, which means that never gets to be dereferenced. I _think_. This is definitely still very beyond me, but I've gotten the expected results in some very small test cases.

**Comment by anvilfolk** [comment] 2022-12-12 13:10
yeah, I think those are different compile-time issues - feel free to look into them and fix if you want :)

Right now I'm focusing on this runtime problem of the refcount incrementing during casting operations!

**Comment by anvilfolk** [comment] 2022-12-14 00:48
I've been digging into this one for hours but an really getting burned out because I can't keep track of which variants are causing refs and unrefs to happen. I might come back to this at a later time, but taking a break for now I think :)

**Comment by anvilfolk** [comment] 2023-01-13 03:31
@vnen I wonder if a lot of the recent fixes around return values & VM stacks also fix this one? I tried to figure it out but the VM was a little too much for me :)

**Comment by adamscott** [comment] 2023-01-13 12:23
@anvilfolk Tested the MRP and it still exhibits the issue.

**Comment by vnen** [comment] 2023-01-16 19:15
I fail to see the bug here. Sure it's odd that it increments twice but it's not like it's being leaked. What happens is that when you run `var x = y as Class` there are two instructions happening:

1. Cast `y` to `Class`, put in temporary address in the stack.
2. Copy the stored temporary value to the permanent address of `x`.

So at the end you have two extra references: one in `x` (as expected) and one in a temporary stack address that will be freed when overwritten or when the function returns.

This behavior can be noted in this snippet:

```gdscript
func _init():
	print(self.get_reference_count()) # 3
	var ref_cast: RefCounted = self as RefCounted
	print(self.get_reference_count()) # 5
	var other = RefCounted.new()
	print(self.get_reference_count()) # 4
```

You can see that when a new `RefCounted` is created it uses the same temporary stack as the cast so it frees one reference. Note that this is based on the underlying GDScript VM current implementation, the way it uses the stack may change in the future.

I'm not sure what's the cause for concern here. Why is the reference count number important?

**Comment by anvilfolk** [comment] 2023-01-16 20:58
Thank you for looking into it and sharing your expertise! :) It looks like I was pretty close in my interpretation of what was happening, but somehow couldn't find a program to replicate what yours just did :)

So, in my personal interpretation, I expect RefCounts to increment when _I_ do something that creates a reference. I wouldn't expect invisible temporary variables to increase them behind the scenes, especially temporary variables with unknown lifespan. Even if I can logically understand it now (after digging into the VM), the behavior is unintuitive and unexpected enough that people created an issue related to it :)

Is there a possibility that a large, memory intensive `RefCounted` object stays alive for much longer than it should? Or is the idea that the temporary variables actually have really short lifespans and therefore do not meaningfully extend the lifetime of `RefCount=0` objects?

And if that's the case, then we should definitely weigh "fixing" it against the performance decrease of resetting temporary stack variables to null variants every time they are done being used!

**Comment by vnen** [comment] 2023-01-20 18:49
> So, in my personal interpretation, I expect RefCounts to increment when _I_ do something that creates a reference. I wouldn't expect invisible temporary variables to increase them behind the scenes, especially temporary variables with unknown lifespan. Even if I can logically understand it now (after digging into the VM), the behavior is unintuitive and unexpected enough that people created an issue related to it :)

I understand this but you have to take into account that other objects interacting with the RefCounted they may create extra references (either permanently or temporarily) so relying on this number to go up by exactly one all times will probably fail often. There's no reason to care about this number unless you are looking for cycles or something very low level (which then you have to take all possible interactions into account).

> Is there a possibility that a large, memory intensive `RefCounted` object stays alive for much longer than it should? Or is the idea that the temporary variables actually have really short lifespans and therefore do not meaningfully extend the lifetime of `RefCount=0` objects?

I doubt it. It's rare to have situation in which the temporary will live longer the one you are storing in a local variable for instance. The longer it can live is until the end of the function when the stack will be cleared. The worst case is if you use `await` and this lives for a long time while waiting for the function to resume (this probably can be fixed if really needed by clearing unused slots before saving the state, since some of the temporaries may still be used after resume in some cases).

> And if that's the case, then we should definitely weigh "fixing" it against the performance decrease of resetting temporary stack variables to null variants every time they are done being used!

I don´t think it's worth it. It will just create a performance penalty without real gain. The only possible gain is if the temporary slot wouldn't be reused again (and thus not reset) but that's more likely to occur at the end of a function, by then the value wouldn't be held much longer anyway. For the case of `await` might be worth investigating if really necessary.

**Comment by anvilfolk** [comment] 2023-01-20 18:56
Thanks for explaining. I feel pretty compelled by your arguments!

How does this issue get handled in this case? Closed as "not an issue"?

**Closed** 2023-02-17 20:22 UTC
Labels: bug, topic:gdscript, confirmed
