### ISSUE TITLE
Internal Script Error! - opcode #31 (report please).

### ISSUE THREAD

**Issue by dennmat** [godotengine/godot#21591] opened 2018-08-30 02:36 UTC
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Window 10 Home 64-bit v1803

**Issue description:**
Attempted to create an instance of a class in the method of another class in a file not attached to any nodes and received the error above.

If the script is attached to another node (not sure if it has to be in the current scene) the error does not occur.

Managed to boil it down to a simple example:

**Steps to reproduce:**

1. Create a new GD Script file with the following: (In this case called Node2D.gd, this was before I knew the root of the issue so the name is a little deceptive)

```gdscript
extends Node

class A:
	var id = 1
	
class B:
	func make():
		var a = A.new() #Error occurs on this line
```

2. Create a node(In this example a Node2D) and attach a new script to it
```gdscript
extends Node2D

const B = preload("res://Node2D.gd").B

func _ready():
	var b = B.new()
	b.make()
```

3. Receive error

**Minimal reproduction project:**
[testerror.zip](https://github.com/godotengine/godot/files/2334400/testerror.zip)

**Comment by akien-mga** [comment] 2018-08-30 06:12
CC @vnen @bojidar-bg

**Comment by vnen** [comment] 2018-08-30 14:01
I think this is a duplicate of #5843. I started investigating it but couldn't find the cause yet.

**Comment by akien-mga** [comment] 2018-08-30 14:14
Closing as duplicate of #5843.

**Closed by akien-mga** 2018-08-30 14:14 UTC
Labels: bug, topic:gdscript
