### ISSUE TITLE
Fly mode in spatial view

### ISSUE THREAD

**Issue by joelgomes1994** [godotengine/godot#6095] opened 2016-08-10 01:30 UTC
Hello!

I see that is pretty hard to set the camera to a desirable position (using the gizmos and all). I suggest an "fly mode" when the camera is selected, to position it using a first person point of view, controlling with the mouse to look and WASD keys to move. This feature is similar to the Blender's Shift + F, that allows an easy camera positioning.

And congratulations to the developers for the new release, nice stuff! :smile:

**Comment by bojidar-bg** [comment] 2016-08-10 06:13
Duplicate of #2797 I think

**Closed by bojidar-bg** 2016-08-10 06:13 UTC
