### ISSUE TITLE
Audiostream does not play in webassembly export?

### ISSUE THREAD

**Issue by stubbsy345** [godotengine/godot#12182] opened 2017-10-17 15:28 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OSX, godot 3.0

**Issue description:**
Audio plays fine locally. But fails to play when played in webassembly export and no errors appear in the debugger so nothing to indicate what is going wrong. *.wav are set to export.

**Comment by marcelofg55** [comment] 2017-10-17 15:44
Audio is not yet implemented in webassembly.

**Comment by eska014** [comment] 2017-10-17 18:41
Duplicate of #11804

**Closed by eska014** 2017-10-17 18:41 UTC
