### ISSUE TITLE
SpriteFrames window does not respect Project Settings Default Texture Filter

### ISSUE THREAD

**Issue by fiaKaiera** [godotengine/godot#74337] opened 2023-03-04 04:46 UTC
### Godot version

4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

In Project Settings > Rendering > Textures > Canvas Textures > Default Texture Filter is set to "Nearest" or "Nearest Mipmap".
When interacting with the textures with SpriteFrames, the filter is not respected and applied.

Here's an example frame imported in SpriteFrames compared with the one imported in-scene,
with Nearest as the Default Texture Filter:
![image](https://user-images.githubusercontent.com/15869263/222876117-58b0f754-e449-4832-b917-01051803fc14.png)

As a result, this has made it hard to import frames, especially in cases where similar colors blend too much to make them distinguishable unless the filter is applied.
Back in Godot 3.5, this could have been easily solved by setting the filter in the Import tab.

### Steps to reproduce

1. In Project Settings, set Rendering > Textures > Canvas Textures > Default Texture Filter to "Nearest" or "Nearest Mipmap"
2. Create a SpriteFrames resource
3. Add a frame from a sprite sheet that has a low resolution per frame (anything less than 24 x 24px will do)
4. The imported frame does not respect Nearest texture filter

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-03-04 08:24
Duplicate of https://github.com/godotengine/godot/issues/57550.

**Closed by Calinou** 2023-03-04 08:24 UTC
