### ISSUE TITLE
"Quick Open..." dialog on Linux doesn't always put the focus into the text field

### ISSUE THREAD

**Issue by WarrenMarshall** [godotengine/godot#85648] opened 2023-12-02 08:57 UTC
### Godot version

4.1.1, 4.2

### System information

Linux, PopOS!

### Issue description

When using the "Quick Open..." dialog it will sometimes appear and the focus is NOT in the text field and there's no way to get the focus in there without mouse clicking on it. This is frustrating and slows the developer down by having to reach for the mouse.

### Steps to reproduce

Unfortunately, it's fairly random and I don't know what causes it.  It feels like it does this maybe 20% of the time I open that dialog, but it's hard to say.  It feels like a timing issue of some kind but that's just a wild guess.

### Minimal reproduction project

![image](https://github.com/godotengine/godot/assets/3742107/39fdc551-ef2c-4a7b-b9f1-ba5cb79ba7b8)

**Comment by Nukiloco** [comment] 2024-05-28 06:17
I can 100% reproduce this on v4.3.dev6.official [64520fe67].

Open the script editor as a dockable window and use the Quick Open shortcut.
The window will open up and the search will be focused but not the window itself!

I remember also randomly when the script editor was docked, sometimes there was a chance that it could also have the same issue, which might actually be the main issue here.

**Comment by Giganzo** [comment] 2024-08-30 09:45
Cant reproduce it in 4.3.rc1 and 4.3.stable so this might have been fixed by: https://github.com/godotengine/godot/pull/93682

**Closed** 2024-08-30 09:47 UTC
Labels: bug, topic:editor, needs testing, topic:gui
