### ISSUE TITLE
Inspector: Property tooltips use setter not member description

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#12158] opened 2017-10-16 17:51 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 (132c6d)

**Issue description:**

Property tooltips need to be updated to use member variable descriptions. We are no longer updating set/get descriptions in the class xml, so they are out of date.

![screen shot 2017-10-15 at 3 17 31 pm](https://user-images.githubusercontent.com/3812514/31589792-1f2a762a-b1bc-11e7-8183-fe26c9610c00.png)

**Comment by akien-mga** [comment] 2017-10-16 21:36
Duplicate of #6382.

**Closed by akien-mga** 2017-10-16 21:36 UTC
Labels: bug, topic:editor
