### ISSUE TITLE
Script editor last line weird behavior

### ISSUE THREAD

**Issue by couturierb** [godotengine/godot#39173] opened 2020-05-30 16:33 UTC
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Windows 10 Pro, update 1909

**Issue description:**
When i scroll down in the script editor, i can't see the last line, and all mouse selection, select bad text. If i scroll just one line upper, it's ok !
Maybe the same as #22744 ?

![bug-script](https://user-images.githubusercontent.com/4509127/83333964-9d42ef80-a2a3-11ea-814d-862fe38ea62c.gif)

**Steps to reproduce:**
- Create a script file with several line (you need to fill entire screen)
- Scroll down
- Try to select some code with your mouse

**Comment by volzhs** [comment] 2020-05-30 16:53
duplicate of #38778

**Comment by Calinou** [comment] 2020-05-30 16:56
Duplicate of #38778. The fix is incorporated in 3.2.2beta3 and will be available in 3.2.2.

**Closed by Calinou** 2020-05-30 16:57 UTC
