### ISSUE TITLE
GUI Incorrect Placement of Textbox when Renaming Any Node with Keyboard

### ISSUE THREAD

**Issue by Hzzkygcs** [godotengine/godot#39082] opened 2020-05-27 10:39 UTC
**Godot version:** v3.2.1.stable.official

**OS/device including version:** Windows 10 Home Single Language, version 1903

**Issue description:**

So I was following the `step-by-step: your first game` tutorial. Then when I was in the Main scene tutorial section, I created 3 timer nodes, then I rename it one by one. I click/select any random nodes (as in the picture below) by mouse, then moving the selection by arrow keys to the timer nodes I want to rename. Then I press enter key (return key) on my keyboard, and the textbox was shown in a wrong placement as you can see in the screen snip below. However it mostly/oftenly shown when I want to rename the third nodes (Timer3) with the arrow-key whereas  the two other timer nodes didn't produce the bug as often as Timer3.

![unexpected placement of textbox](https://user-images.githubusercontent.com/32788259/83007372-c5c9b000-a03d-11ea-9d68-1a4191e52d4d.jpg)

**Steps to reproduce:**
1) Click any random nodes on your scene
2) move the selection to the node you want to rename
3) press enter key on your keyboard

**Minimal reproduction project:**

[Bug report.zip](https://github.com/godotengine/godot/files/4688164/Bug.report.zip)

**Comment by KoBeWi** [comment] 2020-05-29 11:05
Duplicate of #35876

**Closed by KoBeWi** 2020-05-29 11:05 UTC
