### ISSUE TITLE
"compute_list_dispatch: Uniforms were never supplied for set (3) at the time of drawing" Error when rapidly deleting many local to scene particle systems

### ISSUE THREAD

**Issue by supremecool185** [godotengine/godot#82257] opened 2023-09-24 17:57 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 Threads)

### Issue description

If you instantiate a large number of GPUParticle2D nodes that use a ParticleProcessMaterial rather than a ShaderMaterial, and set the "Local to Scene" variable to true, if those nodes get deleted by calling queue_free() it will cause the error message:
`compute_list_dispatch: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline`
Additionally whenever this error message appears there will also be visual artifacts of particles scaling across the whole screen.

Attempting to replicate this I set up a script that would instantiate a new particle system every frame in _process() and then queue_free() it after some number of seconds, however this does not actually cause the error. The particle systems must (as far as i know) be instantiated in _input() rather than _process().

### Steps to reproduce

1. Create a GPUParticles2D node
2. Set its ProcessMaterial as a new ParticleProcessMaterial
3. Set the ProcessMaterial variable "Local to Scene" to true
4. Add a script to the GPUParticles node that calls queue_free() after some amount of time
5. Create a node that instantiates a copy of the GPUParticles node every time a keyboard input is received in _input()
6. Run this scene and mash keyboard buttons to generate a large number of GPUParticle nodes
7. See that if multiple nodes get deleted in quick succession by queue_free() the particles will artifact and generate error codes

### Minimal reproduction project

[Minimal reproduction project.zip](https://github.com/godotengine/godot/files/12709290/Minimal.reproduction.project.zip)
Run the scene named "spawner.tscn" and mash keyboard inputs to see the error

**Comment by bitsawer** [comment] 2023-09-24 22:41
Looks similar to https://github.com/godotengine/godot/issues/77759. I guess it was not fixed by https://github.com/godotengine/godot/pull/79849 and was a separate issue. Let's keep this issue open as now we have a good test project.

I can confirm this, looks like the error triggers here:

https://github.com/godotengine/godot/blob/df0a822323a79e1a645f0c6a17d51c7602f23166/drivers/vulkan/rendering_device_vulkan.cpp#L8165

**Comment by Calinou** [comment] 2023-10-05 17:17
I can't reproduce this on 4.2.dev fe8a58b9d (Linux, NVIDIA 535.113.01).

**Closed** 2023-10-11 22:22 UTC
Labels: bug, topic:rendering, confirmed, topic:particles
