### ISSUE TITLE
Vector2 scene preview

### ISSUE THREAD

**Issue by gusg21** [godotengine/godot#29832] opened 2019-06-16 17:26 UTC
I was wondering if there was any way to show the location of a Vector2 in the scene. For instance, I have a sprite that I set the position of through a parameter to a script, is there any way to represent the Vector2 in the scene so I can get a preview?

I'm opening this here because I feel like it could be a valuable feature if it's not already in the engine.

**Comment by groud** [comment] 2019-06-16 17:45
Vectors have a lot of different use, they may represent a position, a speed, an index on the map... a lot of things in fact. Having a built-in way to preview Vector2 would be pointless, as too many possibilities would have to be covered. 

> is there any way to represent the Vector2 in the scene so I can get a preview?

This is the perfect use case for tool script. It is covered by several tutorials such as [this one](https://www.youtube.com/watch?v=XPs-HGzElTg).

**Comment by LikeLakers2** [comment] 2019-06-16 17:53
>is there any way to represent the Vector2 in the scene so I can get a preview?

You could use a [Position2D](http://docs.godotengine.org/en/latest/classes/class_position2d.html) for this purpose -- just set its position to the Vector2 you want to represent.

**Comment by KoBeWi** [comment] 2019-06-16 21:18
Duplicate of #29520

**Closed by KoBeWi** 2019-06-16 21:18 UTC
Labels: feature proposal, topic:editor
