### ISSUE TITLE
Godot v3.1 beta crash opening a tscn file

### ISSUE THREAD

**Issue by myrmidon-media** [godotengine/godot#24868] opened 2019-01-09 16:21 UTC
Using godot git version 3.1.beta.custom_build.7d46dbb, editor crashes when opening a tscn file with the following stacktrace:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7feabc8f9e00] (??:0)
[2] EditorPropertyRevert::can_property_revert(Object*, StringName const&) (??:?)
[3] EditorFolding::_do_object_unfolds(Object*, Set<Ref<Resource>, Comparator<Ref<Resource> >, DefaultAllocator>&) (??:?)
[4] EditorFolding::_do_node_unfolds(Node*, Node*, Set<Ref<Resource>, Comparator<Ref<Resource> >, DefaultAllocator>&) (??:?)
[5] EditorFolding::_do_node_unfolds(Node*, Node*, Set<Ref<Resource>, Comparator<Ref<Resource> >, DefaultAllocator>&) (??:?)
[6] EditorFolding::_do_node_unfolds(Node*, Node*, Set<Ref<Resource>, Comparator<Ref<Resource> >, DefaultAllocator>&) (??:?)
[7] EditorFolding::unfold_scene(Node*) (??:?)
[8] EditorNode::load_scene(String const&, bool, bool, bool, bool) (??:?)
[9] EditorNode::open_request(String const&) (??:?)
[10] FileSystemDock::_select_file(String) (??:?)
[11] MethodBind1<FileSystemDock, String>::call(Object*, Variant const**, int, Variant::CallError&) (??:?)
[12] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:?)
[13] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (??:?)
[14] MessageQueue::flush() (??:?)
[15] SceneTree::iteration(float) (??:?)
[16] Main::iteration() (??:?)
[17] OS_X11::run() (??:?)
[18] /usr/bin/godot(main+0x151) [0x147b3d1] (??:?)
[19] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7feabc8e6223] (??:0)
[20] /usr/bin/godot(_start+0x2e) [0x147b1be] (??:?)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment] 2019-01-09 16:57
Can you provide a scene file that reproduces it?

**Comment by akien-mga** [comment] 2019-01-13 13:44
Moving to next milestone for now, can't fix it for 3.1 without a way to reproduce it.

**Comment by myrmidon-media** [comment] 2019-01-13 15:32
Sorry for late response.

Here you are the escene file:

https://drive.google.com/file/d/1P-bqe1k-9gMWFAvBS8x1k57CaP-HvYTN/view?usp=sharing

Sometimes it crashes not opening the scene file but when trying to play it:

```
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f719ae9ae00] (??:0)
[2] Object::get_signal_list(List<MethodInfo, DefaultAllocator>*) const (??:?)
[3] SceneState::_parse_connections(Node*, Node*, Map<StringName, int, Comparator<StringName>, DefaultAllocator>&, HashMap<Variant, int, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&) (??:?)
[4] SceneState::_parse_connections(Node*, Node*, Map<StringName, int, Comparator<StringName>, DefaultAllocator>&, HashMap<Variant, int, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&) (??:?)
[5] SceneState::_parse_connections(Node*, Node*, Map<StringName, int, Comparator<StringName>, DefaultAllocator>&, HashMap<Variant, int, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&, Map<Node*, int, Comparator<Node*>, DefaultAllocator>&) (??:?)
[6] SceneState::pack(Node*) (??:?)
[7] PackedScene::pack(Node*) (??:?)
[8] EditorNode::_save_scene(String, int) (??:?)
[9] EditorNode::_save_scene_with_preview(String, int) (??:?)
[10] EditorNode::_save_all_scenes() (??:?)
[11] EditorNode::_menu_option_confirm(int, bool) (??:?)
[12] EditorNode::_menu_option(int) (??:?)
[13] EditorNode::_run(bool, String const&) (??:?)
[14] EditorNode::_menu_option_confirm(int, bool) (??:?)
[15] EditorNode::_menu_option(int) (??:?)
[16] MethodBind1<EditorNode, int>::call(Object*, Variant const**, int, Variant::CallError&) (??:?)
[17] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:?)
[18] Object::emit_signal(StringName const&, Variant const**, int) (??:?)
[19] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:?)
[20] PopupMenu::activate_item(int) (??:?)
[21] PopupMenu::_gui_input(Ref<InputEvent> const&) (??:?)
[22] MethodBind1<PopupMenu, Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (??:?)
[23] Object::call_multilevel(StringName const&, Variant const**, int) (??:?)
[24] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:?)
[25] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:?)
[26] Viewport::_gui_input_event(Ref<InputEvent>) (??:?)
[27] Viewport::input(Ref<InputEvent> const&) (??:?)
[28] Viewport::_vp_input(Ref<InputEvent> const&) (??:?)
[29] MethodBind1<Viewport, Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (??:?)
[30] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:?)
[31] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:?)
[32] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:?)
[33] SceneTree::input_event(Ref<InputEvent> const&) (??:?)
[34] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:?)
[35] InputDefault::parse_input_event(Ref<InputEvent> const&) (??:?)
[36] OS_X11::process_xevents() (??:?)
[37] OS_X11::run() (??:?)
[38] /usr/bin/godot(main+0x151) [0x147b3d1] (??:?)
[39] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f719ae87223] (??:0)
[40] /usr/bin/godot(_start+0x2e) [0x147b1be] (??:?)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment] 2019-01-26 00:20
Can you still reproduce it in the current master branch? Many similar bugs have been fixed recently.

**Comment by myrmidon-media** [comment] 2019-01-26 10:05
Still crashing with version r18796.6e600706e9-1

**Comment by akien-mga** [comment] 2019-01-26 10:11
Sadly we can't reproduce the issue with the scene you provided, it's impossible to open standalone:
![screenshot_20190126_111042](https://user-images.githubusercontent.com/4701338/51785701-1172fd80-215b-11e9-97bf-b86701e74913.png)

**Comment by myrmidon-media** [comment] 2019-01-26 10:17
Let me talk with the team. 

Would it be of any help to get another stacktrace with latest godot version?

**Comment by qarmin** [comment] 2019-12-26 09:05
Still we don't have project to reproduce this issue

**Comment by akien-mga** [comment] 2020-01-03 13:15
Indeed, closing as we can't do anything to debug further.

**Closed by akien-mga** 2020-01-03 13:15 UTC
Labels: bug, topic:editor
