### ISSUE TITLE
Parser bug (please report): Trying to check compatibility of unset target type

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#40778] opened 2020-07-27 20:57 UTC
**Godot version:**

4.0.dev.custom_build. e235863bf

**Issue description:**

When I click control on opened script editor, then Godot shows this error:

```
 Parser bug (please report): Trying to check compatibility of unset target type
```

**Steps to reproduce**
1. Open script GridContainer.gd
2. Press Control key on the keyboard

**Minimal reproduction project:**

I'm not sure about minimal project, so this maybe be a little too big, but should work:
https://github.com/qarmin/The-worst-Godot-test-project/archive/77c0f179780f7a7651c268cf17b677e3e3c778de.zip

**Comment by RevoluPowered** [comment] 2020-08-01 23:03
```python
extends Control

var servers = {}
var local_port = 6777

func _ready():
	var PlayOffline = $HBoxContainer/PlayOffline
	var Server = $HBoxContainer/Server
	var ConnectToServer = $"HBoxContainer/HBoxContainer/Connect to Server"
	Server.pressed = _on_server_pressed
	PlayOffline.pressed = _on_play_offline_pressed
	ConnectToServer.pressed = _on_connect_to_server_pressed
		
	_populate_server_list()

func _populate_server_list():
	var local_ip = "127.0.0.1"
	for l in IP.get_local_addresses():
		# FIXME
		# get_local_addresses gives both IPv4 and IPv6 and I can't be arsed filtering them now
		if l.begins_with("192."):
			local_ip = l
			break;
	servers["localhost"] = { "ip": local_ip, "port": local_port}
	var server_list = $HBoxContainer/HBoxContainer/OptionButton
	server_list.clear()
	for server in servers:
		server_list.add_item(server)
	server_list.select(0)


func _on_play_offline_pressed():
	GameOrchestrator.start_offline()
	hide()


func _on_server_pressed():
	GameOrchestrator.start_server(local_port)
	hide()


func _on_connect_to_server_pressed():
	var serverlist = $HBoxContainer/HBoxContainer/OptionButton
	var serverinfo = servers[serverlist.get_item_text(serverlist.get_selected_id())]
	GameOrchestrator.connect_to_server(serverinfo["ip"], serverinfo["port"])
	hide()
```

Same is happening with this script but not another one.

**Comment by RevoluPowered** [comment] 2020-08-01 23:04
**Happens for me on:**
- running of game
- editing of code
- saving code

**Comment by Calinou** [comment] 2022-09-12 23:24
Duplicate of https://github.com/godotengine/godot/issues/44375 (which has more information).

**Closed by Calinou** 2022-09-12 23:24 UTC
Labels: bug, topic:gdscript, regression
