### ISSUE TITLE
Getting slower during long time development

### ISSUE THREAD

**Issue by KayacChang** [godotengine/godot#33960] opened 2019-11-28 01:32 UTC
**Godot version:**
Version 3.1

**OS/device including version:**
MacOS Version 10.14.6 / Mac mini

**Issue description:**
Godot editor getting slower during the development.
It is fine at first time, but after long time development, it's become really slow.
Both editor and game runtime will become slow.
Re-open it doesn't solved this problem.

I try create a new project and move all dependencies to new one.
And the slow problem solved, it's work fine when create a new one.

So I guess maybe some favorite open too much, 
cause memory issue when the editor opening.

**Comment by FeralBytes** [comment] 2019-11-28 02:30
Sorry, but this is simply too vague. Just to be clear you may be on to something. But you need to justify it more. You claim a memory leak, so can you show proof of the leak? Do you have an example project? Can you be more exact in time frames?

**Comment by KayacChang** [comment] 2019-11-28 18:22
This is a project I currently work on:
[SpaceShooter](https://github.com/KayacChang/SpaceShooter)

I try to reproduce the previous problem I seem,
Because it's work fine now, I need to take some time to try it out.

**Comment by Xrayez** [comment] 2019-11-28 21:13
Might be related to how editor cache is stored so that reading it from disk may become slower over time. Reading `Favorites` from disk may decrease performance, also you might be experiencing something similar to #27333.

**Comment by akien-mga** [comment] 2020-10-01 09:28
This is fairly vague and in https://github.com/godotengine/godot/issues/33960#issuecomment-559578601 @KayacChang couldn't reproduce the issue anymore (and the linked project is deleted), so closing.

**Closed by akien-mga** 2020-10-01 09:28 UTC
Labels: bug, needs testing, topic:editor
