### ISSUE TITLE
2D object not rendered in 2D editor viewport of they are chidren of a SubViewport

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#73274] opened 2023-02-14 09:27 UTC
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, Compatability

### Issue description

Nothing is rendered in the Godot editor if you are editing a 2D scene that is a child of a SubViewport node.

### Steps to reproduce

Create a new scene with a Node3D root node.  
Add a Node2D as a child.  
Click on the Node2D.  Godot will switch to 2D view.
Add a Polygon2D as a child of the Node2D.  Draw a polygon.  You will  see the results in the viewport.
Add a SubViewport node as a child of the Node3D
Drag the Node2D so that it is a child of the SubViewport.
Click  on the Node2D again.  Now nothing is rendered in the viewport.

### Minimal reproduction project

[2dIn3D.zip](https://github.com/godotengine/godot/files/10730809/2dIn3D.zip)

**Comment by Sauermann** [comment] 2023-02-14 09:50
Please have a look at #50185

**Comment by KoBeWi** [comment] 2023-03-01 23:40
SubViewports do not display anything on their own, you need SubViewportContainer or ViewportTexture.
Also duplicate of #20619

**Closed by KoBeWi** 2023-03-01 23:40 UTC
