### ISSUE TITLE
ColorPicker's eyedrop takes ages to pick a color

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#25358] opened 2019-01-26 22:28 UTC
**Godot version:**
 1253b9c

**OS/device including version:**
Manjaro GNU/Linux - Intel i5, Haswell

**Issue description:**
Both in-game and in the editor, when trying to pick a color via the eyedrop, everything will start to freeze until much later, when the color will finally be picked.

**Comment by avencherus** [comment] 2019-01-27 08:57
Confirmed in 1253b9c038277aebfb5a4cc11685823f2331a26b as well.

**Comment by groud** [comment] 2019-01-31 11:38
According to my investigations, the problems comes from the get_data() function that is slow on ViewportTextures. It calls `VS::get_singleton()->texture_get_data(vp->texture_rid)`, which is probably the source of the problem.
I am surprised it does not work neither in GLES3 nor in GLES2.

**Comment by akien-mga** [comment] 2019-02-25 19:19
Confirmed in baefda668.

**Comment by reduz** [comment] 2019-02-26 00:43
@avencherus it's definitely not meant to be used in real-time, but it should not be super slow

**Comment by JFonS** [comment] 2019-02-27 09:13
Are you all testing in debug builds? I think it's just the `texture_get_data()` method is slow, and it's even slower on debug builds. I tested on the official release beta8 and it's slow but not that bad, in my custom debug build of the same commit it's much slower. 

We could either find a way to speed up `texture_get_data()` or change the color picker so it takes samples every 0.25 seconds or something similar.

**Comment by akien-mga** [comment] 2019-02-27 09:17
It was not particularly slow in 3.0 as far as I remember.

**Comment by JFonS** [comment] 2019-02-27 09:24
@akien-mga It's just a little laggy, but I get the same amount of lag between a release build of 3.0 and 3.1, so I don't think anything changed there.

**Comment by akien-mga** [comment] 2019-02-27 13:13
Ok, then this sounds like a good compromise:

> change the color picker so it takes samples every 0.25 seconds or something similar.

**Comment by groud** [comment] 2019-02-27 13:16
> change the color picker so it takes samples every 0.25 seconds or something similar.

Not sure what this means, but in my editor, the color picker takes 7 seconds to pick a color.
So if this processing is done every 7 seconds, this is going to freeze my computer. Unless I misunderstood the proposal.

**Comment by JFonS** [comment] 2019-02-27 13:26
@groud Right now `texture_get_data` gets called on every mouse movement event. My idea is to change the current behaviour so the texture is sampled in a constant but solwer rate, and maybe one last sample on the click event. 

This way we would give te CPU more time to complete the get texture call before calling it another time.

**Comment by groud** [comment] 2019-02-27 13:35
> @groud Right now `texture_get_data` gets called on every mouse movement event.

Oh, so the problem is that it calls this function too often. Because it seems like I have a freeze only when I click in the end. The calls are probably stacking up, which lead to a longer freeze.

Maybe a workaround would be not to add a repetitive call, but to add a delay to the call to `texture_get_data`. So that the engine would wait for something like 0.2 seconds for the mouse standing still before actually calling the function. You would reset the same timer every time the mouse moves, and call the function when it it timeouts.

**Comment by Zylann** [comment] 2019-12-30 14:55
Can we simply query a 1x1 part of the viewport instead of downloading the entire thing?

**Comment by Calinou** [comment] 2019-12-30 15:03
@Zylann I've precisely thought about that, but I have no idea how this could be achieved.

**Comment by Zylann** [comment] 2019-12-30 15:09
@Calinou I guess it needs to be implemented. I once needed the opposite (`set_data_partial`).

**Comment by JFonS** [comment] 2020-01-12 20:11
I checked the current implementation of `texture_get_data` and it does a draw call to render the textre and retrieve its data. I'm pretty sure the newer versions of OpenGL have ways to get individual pixels from textures, but it was implemented this way to have more compatibility. 

Vulkan will most likely also allow us to get partial data, but we will still need to support GLES2, so I would just add a timer like @groud suggested.

**Comment by JFonS** [comment] 2020-01-13 11:47
I'm adding the "junior job" label. The task is to modify `ColorPicker` so instead of sampling the screen on every mouse movement it's only done when the mouse sits still in a position for a set amount of time. 

What needs to be done:
* Add a timer to `ColorPicker`.
* Reset the timer on every mouse movement input.
* When the timer times out perform the same screen sampling that is now done on every mouse movement.

You can at `editor/code_editor.cpp` for a similar usage of timers in `code_complete_timer`.

**Comment by JFonS** [comment] 2020-01-13 11:50
Moving to 4.0 milestone, not a blocking issue. The fix should be cherrypicked back to 3.2

**Comment by YeldhamDev** [comment] 2020-01-13 11:55
Just to update on my part, the freezing doesn't happen anymore in my end. Neither with GLES3 nor GLES2.

**Comment by buefox** [comment] 2020-02-04 17:31
Hi! May I take this task and start looking into it? Thanks!

**Comment by Calinou** [comment] 2020-02-04 20:41
@buefux It appears nobody is currently working on it, so go ahead :slightly_smiling_face:

**Comment by akien-mga** [comment] 2023-02-12 12:09
Fixed by #61997.

**Closed by akien-mga** 2023-02-12 12:09 UTC
Labels: bug, confirmed, topic:gui
