### ISSUE TITLE
Godot 3.5 move_and_collide regression

### ISSUE THREAD

**Issue by andyprice** [godotengine/godot#64016] opened 2022-08-06 21:55 UTC
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Fedora 36 x86_64 GLES3

### Issue description

In Godot 3.4.5, using move_and_collide() to move a KinematicBody towards a StaticBody results in the KinematicBody stopping and a collision being returned.

In Godot 3.5, using move_and_collide() to move a KinematicBody towards a StaticBody results in the KinematicBody stopping but null is always returned.

### Steps to reproduce

Attaching this script to a KinematicBody that's initially positioned above a StaticBody shows the difference in behaviour between 3.4 (it bounces) and 3.5 (it stops but move_and_collide always returns null so it doesn't bounce).
```
extends KinematicBody

var speed = -1.0

func _physics_process(delta):
	var collision = move_and_collide(Vector3(0, speed * delta, 0))
	# print(transform.origin)
	if collision:
		speed = 1.0
```

### Minimal reproduction project

[CollisionTest.zip](https://github.com/godotengine/godot/files/9275807/CollisionTest.zip)

**Comment by akien-mga** [comment] 2022-08-06 22:01
CC @godotengine/physics

**Comment by rburing** [comment] 2022-08-06 23:00
Duplicate of infamous https://github.com/godotengine/godot/issues/62153.

**Closed by rburing** 2022-08-06 23:00 UTC
Labels: bug, topic:physics, regression
