### ISSUE TITLE
Text input focus border not hide when scroll out of panel.

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot#13266] opened 2017-11-25 06:55 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10 64 bit, v3.0.beta.custom_build.1406fb6

**Issue description:**
In edit about dialog, at "Authors" tab, click one of input element, then scroll mouse up, the element focus border not hide. 

It should hide border out of its parent area.

![image](https://user-images.githubusercontent.com/39784/33228205-5df2ead2-d1f0-11e7-90ad-f36ea77f32d3.png)

![image](https://user-images.githubusercontent.com/39784/33228209-73e4d346-d1f0-11e7-8385-644b6fcba42f.png)

Same bug also in "Donors" tab in About dialog.

**Comment by Noshyaar** [comment] 2017-11-25 06:58
Duplicate of #9612

**Closed by Noshyaar** 2017-11-25 06:58 UTC
