### ISSUE TITLE
Duplicating BaseButton gives Error/Warning

### ISSUE THREAD

**Issue by andanysh** [godotengine/godot#51892] opened 2021-08-19 18:00 UTC
### Godot version

v3.3.1

### System information

Windows 10

### Issue description

The BaseButton.duplicate() method generates the following Error message even though the initial object (BaseButton) uses correct/default settings for 'set_enabled_focus_mode'.

"set_enabled_focus_mode: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead."

I'm not sure how to work around this if I want to duplicate an object with a BaseButton to capture the dynamically changed state as opposed to just .instance() or .new() which do not.

### Steps to reproduce

func _ready():
	var myBtn = Button.new()
	add_child(myBtn)
	var newBtn = myBtn.duplicate()
	add_child(newBtn)

### Minimal reproduction project

[ButtonTest.zip](https://github.com/godotengine/godot/files/7016841/ButtonTest.zip)

**Comment by Calinou** [comment] 2021-08-19 19:09
Duplicate of https://github.com/godotengine/godot/issues/48160.

**Closed by Calinou** 2021-08-19 19:09 UTC
