### ISSUE TITLE
Export Godot mobile

### ISSUE THREAD

**Issue by Pabloviniciu23** [godotengine/godot#88216] opened 2024-02-11 17:44 UTC
### Tested versions

4.2 stable

### System information

Mobile - Godot 4.2 stable

### Issue description

The error occurs when I try to export a game to the web or apk, the export button goes too far below the limit of the cell phone screen And you can't see or touch it.
![Screenshot_2024-02-11-14-18-39-679_org godotengine editor v4](https://github.com/godotengine/godot/assets/111866296/effbedb2-9a99-42f3-b297-a796a806c52a)

### Steps to reproduce

.

### Minimal reproduction project (MRP)

.

**Comment by AThousandShips** [comment] 2024-02-11 17:52
Duplicate of https://github.com/godotengine/godot/issues/73130

**Closed by AThousandShips** 2024-02-11 17:52 UTC
