### ISSUE TITLE
GPU 3D particles. pass index out of size while using only one pass

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot#28128] opened 2019-04-17 13:00 UTC
**Godot version:**
GoDot 3.1 Stable. Official build

**OS/device including version:**
GNU/Linux Ubuntu with Xfce and MESSA drivers

**Issue description:**
3D GPU particles print error about "pass index out of size" while all particle nodes are using only one pass. Only pass 0 is used but engine is trying to access pass 1,2 and 3. Happens only during saving the scene and on play (which automatically saves scene). Errors are print for every particle system in scene.
Errors :
```
 scene/3d/particles.cpp:204 - Index p_pass=1 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=2 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=3 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=1 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=2 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=3 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=1 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=2 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=3 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=1 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=2 out of size (draw_passes.size()=1)
 scene/3d/particles.cpp:204 - Index p_pass=3 out of size (draw_passes.size()=1)
```
I'm not accessing passes so it must be inside engine.

**Comment by clayjohn** [comment] 2019-04-17 15:06
This is a duplicate of #26663 Which was fixed in PR #27894.

It is fixed in master branch and will be fixed in the coming 3.1.1 release and 3.2!

**Closed by clayjohn** 2019-04-17 15:06 UTC
Labels: bug, topic:core
