### ISSUE TITLE
Metadata doesn't save when adding it in editor

### ISSUE THREAD

**Issue by fkeyzuwu** [godotengine/godot#66421] opened 2022-09-26 00:39 UTC
### Godot version

4.0 dev, ef26618, compiled in debug mode

### System information

Windows 10

### Issue description

Script metadata is being added in the editor, but isn't actually updated behind the scenes. 
When doing a check with has_meta(), the metadata is not found.
When closing and re-opening the project, the metadata is not found in the editor since it isn't actually saved.

### Steps to reproduce

Make a project, add metadata to a script via the inspector, try accessing it in code.
Also close and re-open the project to confirm the metadata is not saved.

### Minimal reproduction project

[Metadata Deleted.zip](https://github.com/godotengine/godot/files/9642126/Metadata.Deleted.zip)

**Comment by timothyqiu** [comment] 2022-09-26 02:20
I can't reproduce this on current master.

Is the metadata added to Script or to the Node? Metadata set on the script won't be saved.

**Comment by fkeyzuwu** [comment] 2022-09-26 12:18
> 

Yes, the metadata is added to the script. But that is the problem.

I tried finding info about this but didn't find anything about not having access to anything on the script unless its attached to a node and Initialized I guess. I did figure out that the property list, or the method list etc, don't return my custom properties/methods, which is i guess fine. But the metadata DOES let me add it on a script without a node, which was fixed by you in one of latest merges.
https://github.com/godotengine/godot/pull/65868

its good that it doesn't crash, however if this is not the correct way to use metadata and won't give you the actual results that you entered in the UI, why not add an error message to the screen saying you cant do that and stop you from doing it?

I'd say there's a couple things that can be done, in order of easiest to hardest:

1. Just leave it like this as the intended behavior, and at least somewhere on the documentation add a line which says metadata is not saved on scripts which are not attached to nodes, and you should not do it.
2. Add an error popup that stops you from adding metadata on a naked script
3. Add support for metadata related methods for naked scripts and saving them
4. Add support in general for using most Object related methods from the GDScript class inside code. (including metadata fix)

Obviously I don't expect all this to happen anytime soon, but I assume 1 and 2 should not be THAT hard to do and would stop most of the confusion.

**Comment by timothyqiu** [comment] 2022-09-26 13:23
This has been a long existing issue.

Script is a special type of resource that does not have other settings saved (which is what could be improved). You can reproduce this on 3.x too. Checking `Local To Scene` won't be saved either.

> But the metadata DOES let me add it on a script without a node, which was fixed by you in one of latest merges.

The crash is not related to script properties not saved. It crashed because the dialog did not handle Resource correctly.

**Comment by fkeyzuwu** [comment] 2022-09-26 13:41
> Script is a special type of resource that does not have other properties saved (which is what could be improved). You can reproduce this on 3.x too. Checking `Local To Scene` won't be saved either.

Thanks for confirming this, I was suspecting Script is a special type of resource and that it couldn't save properties(not just meta). I'll be aware of this in the future.

> Since your MRP uses `has_meta()` directly, you should add your metadata to the Node instead of the script. That'll be checked correctly.

This works if you the scripts inherits from node, but if the script is just RefCounted you still need to dynamically add meta in code, which kinda defeats the purpose for my use case of it being easy to add const values that are not hard-coded inside the script itself.

Thanks for the reply!

**Comment by kmadridr** [comment] 2022-09-28 05:43
Shouldn't this issue be closed?

**Comment by fkeyzuwu** [comment] 2022-10-04 23:52
> Shouldn't this issue be closed?

Dunno. The original issue deviated to a UI focused problem. But is still a problem and just because it is the "intended" way it should work, doesn't mean it isn't an issue and can't be misleading. Especially since in the UI/console nothing says something is wrong.

**Comment by adamscott** [comment] 2024-02-01 14:36
Closing as duplicate of #84653. That issue may be more recent than this one, it is better detailed than this one, as it is more circumspect.

**Closed by adamscott** 2024-02-01 14:36 UTC
Labels: bug, topic:editor
