### ISSUE TITLE
Arch Linux: Godot 4 (beta 8) crashes on (latest X11)

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#70271] opened 2022-12-18 20:02 UTC
### Godot version

v4.0.beta8.official.45cac42c0

### System information

6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### Issue description

After updating Arch Linux, Godot 4 beta 8 starts crashing on launch:
(used to work a few days ago; also beta 7 crashes now)

```
Godot Engine v4.0.beta8.official.45cac42c0 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Laptop GPU
 
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
godot: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

Reads like the root issue might be in X11. But assuming that X won't have a fix soon and we need a  workaround "soon" or we can't use Godot anymore.

### Steps to reproduce

1. Install and Update Arch Linux.
2. Launch Godot
3. Notice it crash with the errors above.

### Minimal reproduction project

Not needed.

**Comment by akien-mga** [comment] 2022-12-18 20:29
Duplicate of #69352

**Closed by akien-mga** 2022-12-18 20:29 UTC
