### ISSUE TITLE
Specifying an enum as the return type of a function in GDScript not working correctly

### ISSUE THREAD

**Issue by pierresteeg** [godotengine/godot#67093] opened 2022-10-08 20:12 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10/Ubuntu 21.10

### Issue description

Specifying the return type as an enum in GDScript does not work correctly. It does, however, work fine when a parameter is defined as an enum. 

Declaring and writing the function does not display any errors or odd behaviour. Once the function is being run it will result in an error with the message `Trying to return value of type "int" from a function which the return type is "Dictionary"`. This could be worked around by just defining the return value as an int, but I'd dislike giving up the comfort of static typing.

Here is some test code to illustrate the issue:

```
enum Test {
  A = 1,
  B = 2,
  C = 3
}

func test_parameter_function(parameter : Test) -> int:
  return 0

func test_return_function() -> Test:
  return Test.B

func calling_function() -> void:
  test_parameter_function(Test.A) # This does work fine and behaves as expected.
  test_function() # This does not work and will display the described error at this line.
```

Perhaps this is related to autocomplete for enums being broken in beta 2?

### Steps to reproduce

Append the above code in a new GDScript file and call `calling_function`.

**Comment by Calinou** [comment] 2022-10-08 20:25
Duplicate of https://github.com/godotengine/godot/issues/57966.

**Closed by Calinou** 2022-10-08 20:25 UTC
Labels: bug, topic:gdscript
