### ISSUE TITLE
Inherited scene children names in the scene inspector lose yellow color upon switching tabs

### ISSUE THREAD

**Issue by damnjan** [godotengine/godot#78751] opened 2023-06-27 14:05 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Macbook pro M1, MacOS Ventura 13.4.1

### Issue description

Upon creating an inherited scene, the child nodes in the scene inspector are showed as yellow. After switching to a different scene tab and then switching back, the children are no longer showing yellow color. If you close the tab and open the scene again, then they are again displayed with yellow text.

![inherited](https://github.com/godotengine/godot/assets/2204518/955ce00c-4b79-400e-a974-45998fc5e153)

The same issue appears for scene's editable children:

![editable](https://github.com/godotengine/godot/assets/2204518/fe829456-5ff8-4014-afa8-f7940164ba9f)

### Steps to reproduce

1. Create a Node2D scene, add another Node2D node to it as a child
2. Create an inherited scene from that one (it opens in new tab, showing child nodes with yellow colored text)
3. Switch to a different tab
4. Switch back to the inherited scene tab

Similarly for editable children:
1. Create scene A, add a child node to it
2. Create another scene and add scene A as its child
3. Right click on scene A in the inspector and select Editable Children
4. Switch to another tab and then switch back

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-06-27 14:07
* Duplicate of: #78577

**Closed by AThousandShips** 2023-06-27 14:07 UTC
