### ISSUE TITLE
Vulkan Mobile: CLIP_ONLY doesn't work with tilemap, shows background clear color

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#76104] opened 2023-04-15 21:27 UTC
### Godot version

4.0.2 stable

### System information

Windows 10, Vulkan, RTX 3060 (466.81)

### Issue description

When using CLIP_ONLY setting on Clip Children and the Forward Mobile renderer, it doesn't hide the clipping object, it renders the background color instead.

### Steps to reproduce

- Add a sprite object to clip with.
- Add a child sprite to be clipped.
- Set the renderer to Mobile.
- Watch the clip object be rendered as the background/the tileset hall-of-mirrorsing.

### Minimal reproduction project

[cliptest.zip](https://github.com/godotengine/godot/files/11240698/cliptest.zip)

**Comment by Calinou** [comment] 2023-04-15 21:40
- Related to https://github.com/godotengine/godot/issues/75956.

**Comment by clayjohn** [comment] 2023-04-16 02:58
Sounds like a duplicate of #75956

**Closed** 2024-04-19 14:29 UTC
Labels: bug, topic:rendering, confirmed, topic:2d
