### ISSUE TITLE
Polygon2D + 2DTwoBoneIK modification randomly leaks memory

### ISSUE THREAD

**Issue by GopherDevGames** [godotengine/godot#85070] opened 2023-11-18 22:26 UTC
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Godot v4.2.rc1 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu Nov  9 02:34:53 UTC 2023 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (nvidia; 535.129.03) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

Polygon2D that uses a skeleton and skeleton modification 2DTwoBoneIK appears to slowly keep allocating more and more memory over time, while never freeing it unless it's visibility changes.

Changing it's visibility to hidden will "pause" it from leaking any more memory, and then setting it back to visible seems to somehow free that memory, but after that it will continue to leak.

Weirdly, this still happens while the ModificationStack or modifcation 2DTwoBoneIK itself are disabled.

Not sure if this also affects the editor, since the modification stack also runs there.

Expected behavior would be the node/modification not infinitely allocating more and more ram until system resources run out.

I have attached a reproduction project, just run the Maijn.tscn scene using F6 to run it.

### Steps to reproduce

1. Make a polygon2D
2. Add a texture to it
3. a skeleton with 2 bones to the scene and assign it to the polygon2D
4. setup some UV for the 2 bones
5. add a SkeletonModificationStack with a 2DTwoBoneIK Modification
6. Run the project/scene
7. Use the bulit-in memory monitor to confirm if the Static Memory is slowly increaseing

### Minimal reproduction project

[2DBoneIKMemoryLeakIssue.zip](https://github.com/godotengine/godot/files/13401612/2DBoneIKMemoryLeakIssue.zip)

**Comment by kleonc** [comment] 2024-03-19 15:14
> ### Godot version
> 
> v4.2.rc1.official [[ad72de5](https://github.com/godotengine/godot/commit/ad72de508363ca8d10c6b148be44a02cdf12be13)]

Can reproduce in:
- v4.2.stable.official [46dc27791]

Can't reproduce in:
- v4.2.1.stable.official [b09f793f5]
- v4.2.2.rc2.official [c61a68614],
- v4.1.4.rc2.official [fbc4a7e3a]
- v4.3.dev5.official [89f70e98d].

Closing as already fixed.

**Closed by kleonc** 2024-03-19 15:14 UTC
Labels: bug, topic:2d
