### ISSUE TITLE
TextureRect with Tile mode does not work with AtlasTexture

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#20472] opened 2018-07-26 06:47 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**

Godot 2 and 3

**OS/device including version:**

Windows 10 x64

**Issue description:**

TextureRect (and TextureFrame in Godot 2) with `Tile` mode does not work with AtlasTexture.
I tried with both GLES2 and GLES3.

![2018-07-26 03_20_47-godot engine - waffle scanner _](https://user-images.githubusercontent.com/10428035/43245500-dad97e96-9084-11e8-8ae6-7bff2a24dff1.png)
![2018-07-26 03_40_51-godot engine - waffle scanner _](https://user-images.githubusercontent.com/10428035/43245758-cf95c408-9085-11e8-8e72-5944ba8463d0.png)

I also tried to search existing issues but I only found this one #5660, is this related?

**Steps to reproduce:**

**Minimal reproduction project:**

[TextureTile.zip](https://github.com/godotengine/godot/files/2239106/TextureTile.zip)

**Comment by williamd1k0** [comment] 2018-07-26 06:49
Note: All `STRETCH_*` modes work with the AtlasTexture except the `STRETCH_TILE`.

**Comment by williamd1k0** [comment] 2018-07-29 19:34
I'm adding here a minimal reproduction project because it's not working with `draw_texture_rect( Texture texture, Rect2 rect, bool tile)` too.

[TextureTile.zip](https://github.com/godotengine/godot/files/2239106/TextureTile.zip)

**Comment by Jose-Moreno** [comment] 2020-07-12 22:14
[2020] I currently needed this for a project i'm working on for the RaspberryPi 4, and I can confirm this **_still doesn't work_** under Godot 3.2.stable and beyond.

This would be quite useful when using both internal (Import/TextureAtlas) and external (TexturePacker / FreeTexturePacker) texture packing solutions for optimization purposes aimed at low-end, mobile, SoC & IoT devices and when you're not necessarily using tilemap nodes / tileset resources in your workflow.

**Comment by joakin** [comment] 2020-09-28 16:01
This may be a duplicate of https://github.com/godotengine/godot/issues/38021 I hit it too.

**Comment by yhwhey** [comment] 2022-12-05 23:51
Still an issue in Godot 4b7

**Comment by vvvvvvitor** [comment] 2023-05-05 18:55
Any updates on this?

**Comment by hawkerm** [comment] 2023-10-04 00:59
I believe I also hit this issue in 4.1.1 still. Added an AtlasTexture to a TextureRect and see `Tile` for Strech Mode behaving the same as `Scale`.

**Comment by EviTRea** [comment] 2023-10-07 08:09
This also presents in 4.1.2. Control nodes just really hate Sprite Sheet for some reason.

**Comment by LeifintheWind** [comment] 2024-04-15 04:50
Still an issue as far as I can tell in 4.2. 

When using control nodes, is there a workaround for tiling? Pixel art UI looks pretty awful stretched lol

**Comment by Saint-XIV** [comment] 2024-08-01 06:37
still an issue in 4.3.rc1 :(

**Comment by bsil78** [comment] 2024-09-05 01:57
still an issue in 4.4 dev1, very needed...

**Comment by stanleyHorace** [comment] 2024-09-14 08:35
I believe it might be worthwhile for future reference to link the general issues related to AtlasTexture here too:

https://github.com/godotengine/godot/issues/43268#issuecomment-720571636

**Comment by KoBeWi** [comment] 2024-10-28 21:47
Duplicate of #5660
This is a limitation of AtlasTexture.

**Closed by KoBeWi** 2024-10-28 21:47 UTC
Labels: bug, topic:rendering, confirmed, topic:gui, topic:2d
