### ISSUE TITLE
WebGL 2 depth/hdr does not work on HTML5 export

### ISSUE THREAD

**Issue by gerardabello** [godotengine/godot#16021] opened 2018-01-24 08:05 UTC
I thought this was related to issue #13985, but this shows in firefox 58+.

**Godot version:**
Godot 3.0 rc2

**OS/device including version:**
Ubuntu 17.10  Nvidia GTX660

**Issue description:**
I have a small project and this is how it looks on the editor/linux export:
![image](https://user-images.githubusercontent.com/2431197/35320140-132afedc-00e3-11e8-9972-b25b26f1cbde.png)

But it looks like this on chromium 63:
![image](https://user-images.githubusercontent.com/2431197/35320171-2fa7dfee-00e3-11e8-9173-ac92d7927aa3.png)
and like this in firefox 58/59:
![image](https://user-images.githubusercontent.com/2431197/35320200-41f6c624-00e3-11e8-8c95-46df197bf788.png)

It looks like the sky texture has the problem, so I tweak some settings in the import. Setting Srgb to Enable, makes it better on firefox, but not perfect:
![image](https://user-images.githubusercontent.com/2431197/35320274-77abf73a-00e3-11e8-9474-0b763f0bca95.png)
You can see there are some weird colors at the dark part of the asteroid that I don't know how to get rid of. It also happens on the sky texture but it is not as visible.

In chrome there is no change.

**Steps to reproduce:**
Open the project and export to HTML.
Open in browser.
Lightning is too bright in firefox and too dark in chrome.
Change 'textures/skymap_8k.jpg' import setting Srgb to Enable.
Export again to html.
Now the lightning is ok in firefox but dark parts of the image have some weird colors.

**Minimal reproduction project:**
[game.zip](https://github.com/godotengine/godot/files/1659002/game.zip)

**Comment by gerardabello** [comment] 2018-02-03 11:30
Just discovered that disabling depth/hdr in the project settings, makes the editor/linux export have the same look as the html5 export, so I guess that the problem is that this setting does not work on html5.

**Comment by lastrodamo** [comment] 2018-05-11 14:48
@gerardabello i disabled depth/hdr in the project setting and export for Firefox 59.0.2. But i have the same result of your firefox 58/59 image.
In my godot projects, if i remove all hdr or jpg environnement map and uncheck depth/hdr option ; i have the same wrong color aspect on html 5.

**Comment by akien-mga** [comment] 2019-01-20 11:05
Is this still reproducible with the GLES2 / WebGL 1 renderer in the current master branch?

**Comment by gerardabello** [comment] 2019-03-20 08:00
> Is this still reproducible with the GLES2 / WebGL 1 renderer in the current master branch?

I cannot use the master branch directly, but with 3.1 stable the behavior with GLES2 there seems to be no issue:
![image](https://user-images.githubusercontent.com/2431197/54668121-5fb6d400-4aee-11e9-9aed-2fc96e4f5ca8.png)
It does not looks the same as the GLES3 renderer, although I imagine this is expected.

With GLES3 the issue persists.

**Comment by Calinou** [comment] 2019-03-20 12:43
HDR isn't supported in GLES2, whereas HDR is supported (and enabled by default on desktop) in GLES3.

**Comment by akien-mga** [comment] 2019-11-26 14:28
I can confirm that it works OK in Firefox and Chromium on Linux with GLES2, but still exhibits the same issue as in the OP with GLES3 (current master branch).

This is unlikely to be fixed as WebGL 2.0 support in browsers proved to be quite poor, so the focus for the web platform is on WebGL 1.0 (and the GLES3/WebGL 2.0 renderer will be removed in Godot 4.0, thus obsoleting this issue). Still, we can keep this open for now in case someone really wants this to work on WebGL 2.0 and wants to investigate. A fix could be backported to the 3.2.x branch.

**Comment by clayjohn** [comment] 2020-06-20 22:12
Closing as the issue likely lies with WebGL 2.0 and not our code. WebGL 2.0 is still poorly supported and it looks like WebGPU will be supported before WebGL 2.0 is.

**Closed by clayjohn** 2020-06-20 22:12 UTC
Labels: bug, platform:html5, topic:rendering
