### ISSUE TITLE
Godot 3.2.2 suddenly very slow, had been working fine before [NVIDIA] [Windows 10]

### ISSUE THREAD

**Issue by cfibre** [godotengine/godot#40809] opened 2020-07-28 21:45 UTC
**Godot version:**
Godot 3.2.2 stable

**OS/device including version:**
*OS:* Windows 10

*GPU:* nVidia GTX 1050
*Backend:* GLES3
*RAM:* 8GB
*CPU:*  Intel i5-8400T

**Issue description:**
*Before the issue, launching Godot, and launching the project (everything really) was near instantaneous.*
Upon launching Godot, the console window appears but the project manager window takes around 30 seconds to appear.
Once I select a project it takes around a minute to open, and once i just got a white screen.
The program in general is a lot slower than it should be.
When i run a project with only a few scenes (or just one), it takes around 20 seconds to run.

There are no error messages in the console.

**Steps to reproduce:**
I can't think of anything that changed between the last time I launched Godot without the issue and when I first launched it with the issue.

**Attempted fixes:**
I tried all of the following, with no effect:
- Updating graphics drivers
- Downloading a fresh copy of Godot
- Trying Godot 3.2.1
- Switching to GLES2 inside the godot editor

Looking inside of Task Manager, everything looks fine.

I made a GitHub account just to submit this error, sorry if I have made some faux pas.

**Comment by akien-mga** [comment] 2020-07-28 21:49
Sounds like #20566, see if you have a USB peripheral whose buggy firmware slows down the engine.

**Comment by cfibre** [comment] 2020-07-29 09:42
Thanks.
I use 2 USB Peripherals, both made by Corsair
After restarting my computer and reinstalling my firmware and updating iCUE itself, (Corsair's utility software for peripherals),
Godot is running perfectly. In #20566 people have said that Godot slows down after a while so I will keep you updated.

**Comment by akien-mga** [comment] 2020-07-29 10:44
Thanks, I'll close this as duplicate of #20566 already as Corsair devices had been identified specifically as some of the problematic ones. But if the problem crops up again, do comment here if it turns out to be unrelated to #20566 and still reproducible.

**Closed by akien-mga** 2020-07-29 10:44 UTC
