### ISSUE TITLE
Label + RichTextLabel renders differently in Viewports

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot#67983] opened 2022-10-28 20:41 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, GLES 2

### Issue description

A Label or a RichTextLabel renders differently when put inside a Viewport.

![screenshot](https://user-images.githubusercontent.com/2530086/198728093-4e04ed73-0dc4-44b8-b53e-1bd2988b3fff.png)

### Steps to reproduce

Open the reproduction project or clone https://github.com/sszigeti/Viewport-font-hinting-difference

### Minimal reproduction project

[Viewport-font-hinting-difference-1.zip](https://github.com/godotengine/godot/files/9891623/Viewport-font-hinting-difference-1.zip)

**Comment by Calinou** [comment] 2022-10-28 20:49
Duplicate of https://github.com/godotengine/godot/issues/17574.

Add a CanvasItemMaterial to your ViewportContainers with the **Premul Alpha** blend mode:

![image](https://user-images.githubusercontent.com/180032/198730009-527c315a-24a6-4080-9c24-ed0b434359ca.png)

**Closed by Calinou** 2022-10-28 20:49 UTC

**Comment by sszigeti** [comment] 2022-10-28 21:11
@Calinou -- in my case this is only a partial fix. I have a shader on the ViewportContainer that applies a slight alpha fade at the top and bottom edges (I'm scrolling some text there). This no longer works with Premult Alpha, the shader is unable to modify the `a` property:

```
shader_type canvas_item;
//render_mode blend_premul_alpha;

uniform float paddingSize : hint_range(0, 0.5) = 0.2;

void fragment() {
	vec4 pixel = texture(TEXTURE, UV);
	
	float fade = 1.0;
	if (UV.y < paddingSize) {
		fade = UV.y / paddingSize;
	}
	if (UV.y + paddingSize >= 1.0) {
		fade = (1.0 - UV.y) / paddingSize;
	}

	pixel.a = min(pixel.a, fade);
	COLOR = pixel;
}

```

I have also tried using `render_mode blend_premul_alpha` in the shader, without having a separate CanvasItemMaterial -- with the same result.

Would you have a suggestion as to how I should modify this shader?

**Comment by Calinou** [comment] 2022-10-28 23:16
> I have a shader on the ViewportContainer that applies a slight alpha fade at the top and bottom edges (I'm scrolling some text there). This no longer works with Premult Alpha, the shader is unable to modify the a property:

It should be possible to adapt your shader to work with premultiplied alpha. See [this page](https://microsoft.github.io/Win2D/WinUI3/html/PremultipliedAlpha.htm) for a description of premultiplied alpha, and [this one](https://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/) for a description of why it's a good idea to use it.

**Comment by sszigeti** [comment] 2022-10-29 09:37
Thank you @Calinou! For reference I'm sharing the shader with the necessary correction here (thanks to @golddotasksquestions [for the help](https://www.reddit.com/r/godot/comments/yfokvs/can_a_scrollcontainer_inside_a_viewport_receive/iu7bjc5/)):

    shader_type canvas_item;

    uniform float paddingSize : hint_range(0, 0.5) = 0.2;

    void fragment() {
        vec4 pixel = texture(TEXTURE, UV);

        vec3 fix = pixel.rgb / pixel.a;
        pixel = vec4(fix, pixel.a);
        
        float fade = 1.0;
        if (UV.y < paddingSize) {
            fade = UV.y / paddingSize;
        }
        if (UV.y + paddingSize >= 1.0) {
            fade = (1.0 - UV.y) / paddingSize;
        }

        pixel.a = min(pixel.a, fade);
        COLOR = pixel;
    }
