### ISSUE TITLE
Tab navigation in a Vector3 inspector property doesn't properly give focus to spinboxes (DisplayServer regression)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#37723] opened 2020-04-09 19:06 UTC
Godot 4 b3310a00743d65d8baa2b5730ecfaed8bf8842a6
Windows 10 64 bits

Using the tab key to focus X, Y and Z parts of a Vector3 property in the inspector doesn't seem to work properly. In 3.2.1 it focuses each field one after the other by allowing to type numbers immediately. In master, it visually gives focus, but typing numbers doesn't work.

1) Create a `Spatial`
2) Go to its `transform` property and click on the `X` spinbox. Observe you can input numbers normally.
3) Hit the `Tab` key. Observe the `Y` field now looks focused, but typing numbers does nothing.
4) Hit `Tab` again. Observe `Z` is now focused and this time typing numbers works again. Sometimes it still doesn't work, not sure why.

**Comment by Calinou** [comment] 2022-01-30 21:15
@Zylann Can you still reproduce this after https://github.com/godotengine/godot/pull/54173 was merged?

**Comment by KoBeWi** [comment] 2022-06-23 14:14
The field is properly edited when you press Enter after tabbing. Should be easy to fix, but maybe current behavior is already ok?

**Comment by qez008** [comment] 2022-07-20 12:28
Godot 4 alpha 12 
macOS Mojave 

I'm experiencing a very similar issue on mac. Tab navigation is practically unusable in alpha 12, while it works perfectly fine in the stable version.  Pressing tab in the inspector can yield three different outcomes with a seemingly random occurrence:

<img width="988" alt="tab_navigation_g4" src="https://user-images.githubusercontent.com/46963115/179978673-dc3a4955-fd6a-4a6f-92bc-c89a667700e9.png">

All obtained by pressing tab or shift-tab. Only the middle actually allows you to edit the selected field with keystrokes. This seems to be an issue with all exported variables (not just Vector3s).

**Comment by RedMser** [comment] 2022-10-26 21:20
I think this is caused by #59908, but I did not try running a build before/after the commit.

There seems to be two independent issues, either of which can happen, when switching focus via tab:
1. The old popup closes, but the newly opened popup gets closed as well. That's the first screenshot of qez's comment.
2. The old popup stays open, but is not focused anymore, causing inputs to be redirected to the main window (not 100% sure on this one). That's corresponds to the last screenshot.

My assumption is that there are some notifications or signals which get emitted as soon as we tell the OS to show/hide the window, but there's race conditions. Those then either cause the messages to get out of order, producing invalid state. Or they arrive too early/late, causing certain actions to not succeed (such as which element gets focus next, or hiding the old popup *before* showing the new one).

I've tried debugging this a fair bit, but I'm not sure how to proceed.

**Comment by Stealcase** [comment] 2022-11-26 14:55
Since the issue I opened was closed for being a duplicate, I'm just sharing a visualization of the bug and some insights I've had. 

## It seems that the field you are tabbing _from_ has an impact on how the next field is selected.
* Notice how tabbing from a "boolean" field to a "Float_Range" field makes the field receptive to inputs, but tabbing from a "float_range" to a "float_range" does not? The next field is not selected properly. ("Volume DB" => "Unit Size" does NOT select field, but "Stream Paused" => "Max Distance" Does!)

The field is "Focused", but cannot accept input until you press "spacebar" or "enter", because there is no caret/cursor. 
I think this corresponds to @RedMser's suggestion nr 1. 

* Notice how tabbing from a "float_range" field to a pure float/int field (or any other field really) causes the double-selection bug. ("Max Distance" => "Max Poliphony", and "Panning Strength" => "Max Poliphony"). 

This corresponds to @RedMser's suggestion 2. 
![Bugged Properties](https://user-images.githubusercontent.com/38126357/197388936-2a31ecb3-aba0-4f25-97e8-1a81e7cd274c.gif)

## Further example of bug
Nobody else that I can see has reported this bug  occuring in the Scene tree, but it exists there as well. 
Trying to rename 1 or several files in the scene hierarchy triggers a popup/selection issue. 

### Expected behaviour
Mouse clicking on Node Y while in Rename State on Node X should instantly exit Rename State on Node X, and select Node Y. This worked in Godot 3.5, shown below.

![Godot 3_5 renaming](https://user-images.githubusercontent.com/38126357/197390886-1b422cd8-7b47-4374-91cc-f0daf79ec335.gif)
### Actual Behaviour
1. Pressing tab while in Rename State does nothing.
2.  Clicking on another node while in rename state *only exits* the rename state: The original node retains focus. 
3. 2 Clicks are required to select a new node.
![Bugged Scene Tree](https://user-images.githubusercontent.com/38126357/197390893-8b3c36cd-f2a3-4470-86aa-b10143bc1ab9.gif)

**Closed** 2023-01-12 14:17 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:gui
