### ISSUE TITLE
AtlasTexture using get_data() always returns null 

### ISSUE THREAD

**Issue by greencloversguy** [godotengine/godot#38641] opened 2020-05-10 19:53 UTC
I can see why this is the case, at Atlas doesn't actually create the image, and you can easily get around it by getting the image data of the atlas itself and then using get_rect with the region as the argument, though it takes extra work to include the margin. However, for the purposes of testing, I think when get_data is used on an AtlasTexture, it should just perform the above and return the actual image.

**Comment by Calinou** [comment] 2020-05-19 08:16
@greencloversguy Please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when reporting bugs, so that we can know which Godot version this bug occurs in.

**Comment by Calinou** [comment] 2020-12-23 17:46
Duplicate of https://github.com/godotengine/godot/issues/44529.

**Closed by Calinou** 2020-12-23 17:46 UTC
Labels: bug, topic:core
