### ISSUE TITLE
Unable to export arrays via C#

### ISSUE THREAD

**Issue by Steveplays28** [godotengine/godot#70171] opened 2022-12-16 21:41 UTC
### Godot version

v4.0.beta8.mono.official [45cac42c0]

### System information

Windows 10

### Issue description

In C#, using Godot 4.0 beta 8 mono, I'm unable to export arrays of any type. Doesn't matter if it's `string[]`, `PackedScene[]`, or anything else, it will always return `Nil`.
The code compiles, though there's multiple errors in the debugger (see MRP). I haven't tested if this does work in GDScript. This used to work in beta 6 and beta 1, which are the versions I used before upgrading my project to beta 8.

#### Examples

- `[Export] string[]` returns `(Nil) PackedStringArray` in the editor
- `[Export] PackedScene[]` returns `(Nil) Array[PackedScene]` in the editor

![image of the issue in the editor](https://user-images.githubusercontent.com/62797992/208186368-7a53e7a1-92cb-415c-8f11-8f5f1ee2ee4b.png)

#### Errors

These errors are produced by the following code:

```cs
[Export]
public PackedScene[] Scenes;
```

##### Console

```log
 Cannot open file '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Failed to read file: '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Cannot load C# script file '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Failed loading resource: /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs. Make sure resources have been imported by opening the project in the editor at least once.
  Cannot open file '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Failed to read file: '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Cannot load C# script file '/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs'.
  Failed loading resource: /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs. Make sure resources have been imported by opening the project in the editor at least once.
```

##### Debugger

```log
E 0:00:02:0718   void Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(System.Type , IntPtr , IntPtr ): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The type is not supported for conversion to/from Variant: 'Godot.PackedScene[]'
  <C++ Error>    Exception
  <C++ Source>   /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs:17 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.VariantUtils+GenericConversion`1.ToVariant(T& )()
  <Stack Trace>  VariantUtils.generic.cs:17 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.VariantUtils+GenericConversion`1.ToVariant(T& )()
                 VariantUtils.generic.cs:220 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.VariantUtils.CreateFrom<T >(T& )()
                 Variant.cs:159 @ Godot.Variant Godot.Variant.From<T >(T& )()
                 Export_ScriptPropertyDefVal.generated.cs:9 @ System.Collections.Generic.Dictionary`2[Godot.StringName,Godot.Variant] Export.GetGodotPropertyDefaultValues()()
                 :0 @ --- End of inner exception stack trace ---()
                 :0 @ System.Object System.RuntimeMethodHandle.InvokeMethod(System.Object , System.Span`1[System.Object]& , System.Signature , Boolean , Boolean )()
                 :0 @ System.Object System.Reflection.RuntimeMethodInfo.Invoke(System.Object , System.Reflection.BindingFlags , System.Reflection.Binder , System.Object[] , System.Globalization.CultureInfo )()
                 :0 @ System.Object System.Reflection.MethodBase.Invoke(System.Object , System.Object[] )()
                 ScriptManagerBridge.cs:927 @ void Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(System.Type , IntPtr , IntPtr )()
```

```log
E 0:00:02:0728   Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Set(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant* ): System.InvalidOperationException: The type is not supported for conversion to/from Variant: 'Godot.PackedScene[]'
  <C++ Error>    Exception
  <C++ Source>   /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs:20 @ T Godot.NativeInterop.VariantUtils+GenericConversion`1.FromVariant(Godot.NativeInterop.godot_variant& )()
  <Stack Trace>  VariantUtils.generic.cs:20 @ T Godot.NativeInterop.VariantUtils+GenericConversion`1.FromVariant(Godot.NativeInterop.godot_variant& )()
                 VariantUtils.generic.cs:406 @ T Godot.NativeInterop.VariantUtils.ConvertTo<T >(Godot.NativeInterop.godot_variant& )()
                 Export_ScriptProperties.generated.cs:13 @ Boolean Export.SetGodotClassPropertyValue(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:57 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Set(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant* )()
```

### Steps to reproduce

1. Run MRP
2. Go to console tab (should see 8 errors)
3. Go to debugger tab (should see 2 errors)

### Minimal reproduction project

[export-array-bug-mrp-godot.zip](https://github.com/godotengine/godot/files/10249585/export-array-bug-mrp-godot.zip)

**Comment by raulsntos** [comment] 2022-12-16 21:55
Duplicate of https://github.com/godotengine/godot/issues/69822
Should have been fixed by https://github.com/godotengine/godot/pull/69933

**Closed by raulsntos** 2022-12-16 21:55 UTC

**Comment by Steveplays28** [comment] 2022-12-16 22:04
Thank you!
Missed the other issue, sorry.
