### ISSUE TITLE
Crash when baking shadows in CPUlightmapper

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#48856] opened 2021-05-19 18:55 UTC
**Godot version:**
Godot 3.3.1 Stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
Baking shadows instantly crashes. Godot crashes without any entries to the console, which also immediately closes.
Everything works well in 3.3.

**Steps to reproduce:**
1. Create any scene with meshes
2. Bake the shadows

**Minimal reproduction project:**
Any project.

Once again, I note that in 3.3 everything works fine. However does not work completely in 3.3.1.
In the evening I will try to somehow get the possible error messages, but so far it has not been possible to do so. The engine just closes when the "Bake" button is pressed.

**Comment by Calinou** [comment] 2021-05-19 19:04
> In the evening I will try to somehow get the possible error messages, but so far it has not been possible to do so. The engine just closes when the "Bake" button is pressed.

[Run the editor from a terminal.](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html)

To get a proper crash backtrace, you need to [compile a Godot build](https://docs.godotengine.org/en/stable/development/compiling/index.html) with debug symbols included since official releases don't include debug symbols.

**Comment by Zireael07** [comment] 2021-05-19 19:06
Dupe/related to #48822?

**Comment by akien-mga** [comment] 2021-05-19 19:08
It's probably a duplicate of #48822 yes. Could you test the build I linked there?

**Closed by akien-mga** 2021-05-19 19:08 UTC
Labels: bug, crash, topic:3d, topic:editor, topic:rendering
