### ISSUE TITLE
Loading actions are extremely slow and the editor freezes randomly

### ISSUE THREAD

**Issue by djgaven588** [godotengine/godot#30627] opened 2019-07-16 19:01 UTC
**Godot version:**
v3.1.1 stable

**OS/device including version:**
Windows 10
Intel Core i5 6500
16 gb ram
GTX 1070

**Issue description:**
Loading the engine, loading a project, and starting a game take in the range of 30-120 seconds. I expected to take a fraction if this time considering it uses little to no resources during these actions.

**Steps to reproduce:**
Download the latest stable version for windows
Run it

**Minimal reproduction project:**
Kinematic Character 3D starter project

Any help would be greatly appreciated, as I really do want to try out the engine, but with this issue it is painful to even attempt.

**Comment by Calinou** [comment] 2019-07-16 19:56
Duplicate of https://github.com/godotengine/godot/issues/20566.

**Closed by Calinou** 2019-07-16 19:56 UTC
