### ISSUE TITLE
Editor does not recognize C# subclasses of builtin resources

### ISSUE THREAD

**Issue by Mantissa-23** [godotengine/godot#85731] opened 2023-12-03 23:48 UTC
### Godot version

4.2.stable.mono

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3734) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

If you create a custom resource inheriting from something other than the `Resource` class, such as `PhysicsMaterial` or `AudioStream`, in C#, it will not show up in the resource list when trying to create a new resource.

This is an inconsistency with GDScript, where these custom resources inheriting from built-in resources will show up.

### Steps to reproduce

- Create a C# class inheriting from a built-in resource (see MRP)
- Run .NET build
- Search for resource in any dialog for creating a new resource, such as making a new file or selecting that resource in the inspector for a node which has it as a property.
- Observe the lack of the custom resource in the list

This can be repeated successfully using GDScript.

### Minimal reproduction project

MRP contains both an example of this being unsuccessful in C#, and successful in GDScript.

[CSharp Resource Inheritance Bug.zip](https://github.com/godotengine/godot/files/13540596/CSharp.Resource.Inheritance.Bug.zip)

**Comment by raulsntos** [comment] 2023-12-23 18:44
Looking at your MRP, the C# class `PhysicsMaterialSubclassCSharp` does not have the `[GlobalClass]` attribute which is the equivalent of GDScript's `class_name` keyword. When adding the `[GlobalClass]` attribute I'm unable to reproduce the issue so it seems to be working as intended.

For more information on global classes see the [_C# global classes_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html) documentation.

**Comment by Sauermann** [comment] 2024-01-28 14:37
The comment above explains how to use this, so this seems to be a misunderstanding of the functionality. Closing accordingly.

**Closed by Sauermann** 2024-01-28 14:37 UTC
Labels: discussion, topic:editor, topic:dotnet
