### ISSUE TITLE
Adding a CollisionShape2D crashes the editor

### ISSUE THREAD

**Issue by GregX999** [godotengine/godot#76619] opened 2023-04-30 16:05 UTC
### Godot version

4.0.3.rc1.mono

### System information

Windows 11

### Issue description

Adding a CollisionShape2D to the scene, as a child of a CharacterBody2D, crashes the editor.

(Note: Adding a CollisionPolygon2D works fine.)

### Steps to reproduce

1. Create a project
2. Create a scene based on Node2D
3. Add a CharacterBody2D
4. Add a CollisionShape2D as a child of the CharacterBody2D
5. The editor crashes (closes)

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-04-30 16:19
Duplicate of https://github.com/godotengine/godot/issues/76543 (workaround in comments)

**Closed by KoBeWi** 2023-04-30 16:19 UTC
