### ISSUE TITLE
Add custom graph nodes to graph shader editor using plugins.

### ISSUE THREAD

**Issue by samuncle** [godotengine/godot#3349] opened 2016-01-14 11:52 UTC
I think it would be useful if the shader editor in godot could have some premade nodes like a panner to allow quickly to do animated textures (like river flowing, lava etc).

The input would be:

> uv map (the uv map of the object)
> x (the intensity of the animation in u coordinate)
> y (the intensity of the animation in v coordinate)
> time

and the output would be an animated uv coordinate

I made a screenshot explaining the idea
![panner](https://cloud.githubusercontent.com/assets/6406045/12323632/61942756-babd-11e5-9d33-6157d3f55ece.png)

Thinking in a generic way, it would be very useful to be able to create node group and being able to export them. Which means even if we wouldn't have the panner we could easily create our own groups and sharing them.

**Comment by kubecz3k** [comment] 2016-01-14 13:04
Sounds like great feature for 2.1 - which will be focused on easy plugin creation

**Comment by MarianoGnu** [comment] 2016-06-20 04:19
By design rule, Godot shouldn't implement project specific features, instead some kind of custom graph node might be implemented.
Most probably for 2.2 since we are too close to 2.1 to add features...

**Comment by kubecz3k** [comment] 2016-06-20 07:41
@MarianoGnu yeah, I think it should generally would be nice to get some nodes from graph editor, and merge them into one node under some name - this would allow to simplify reading of those graphs. I think it's more related to 'visual programming' area since there would be similar requirement.. Don't think it will be made for 2.1 or even 2.2 since for 2.2 networking is the theme...

**Comment by samuncle** [comment] 2016-07-28 03:09
> By design rule, Godot shouldn't implement project specific features, instead some kind of custom graph node might be implemented.

I agree but this feature (panner or whaterever is included) isn't specific to a project. It's used in many shaders (like waterfalls, clouds, convoyer belts, etc). It's only a brick that allows to quickly design a cool material and it's present in many engines (like Unreal or Unity).

**Comment by MarianoGnu** [comment] 2016-07-28 09:57
Yeah, i recently realized hoy to do it by jus inherit resource, so plugins wont be involved at all. Anyway the editor will most likely be rewritten for 2.2 and/or 3.0

**Comment by quantum-entangler** [comment] 2016-09-15 13:30
Shader node groups would be awesome and if the interface would work similar to how blender node groups work then that would be epic, especially the way you can instance those groups inside different materials. 

It also means those of us willing and capable of building more complex shader/nodegraphs can share our node snippets with those who might not, thus making their lives easier too. :)

**Comment by akien-mga** [comment] 2018-09-15 10:54
Moving to the next milestone as 3.1 is now feature frozen.

Also, is it still relevant in the current master branch with new VisualShader?

**Comment by Megalomaniak** [comment] 2018-12-16 08:35
Far as I can tell, still as relevant as ever.

**Closed** 2019-08-14 13:52 UTC
Labels: feature proposal, topic:editor
