### ISSUE TITLE
velocity.x 89 to 91 are kind of glitched

### ISSUE THREAD

**Issue by MuubNito** [godotengine/godot#81208] opened 2023-08-31 20:38 UTC
### Godot version

4.1.1 stable

### System information

Godot v4.1.1 stable - Windows 10.0.22621 (Though i use windows 11?) - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.56000) - AND Ryzen 7 5700U with Radeon Graphics (16 Threads)

### Issue description

(Using gameboy resolution (160x144) btw) Using the template movement script, the variable SPEED is massively slower than 91, and if the SPEED is on 90, going left feels like 89 speed and going right feels like 91.

### Steps to reproduce

1. Create a project (If you use the one I sent here, the steps are already done)
2. Set viewport to 160x144 (Gameboy resolution)
3. Create a Floor with StaticBody2d and a CharacterBody2d and make them visible using polygon2d's
4. Attach the movement template script to the CharacterBody2d
5. Set variable SPEED to 89/90/91 (Any that you want to test)
6. Play the game. The character movement is either slow or fast

### Minimal reproduction project

[UntitledTestProject.zip](https://github.com/godotengine/godot/files/12490443/UntitledTestProject.zip)

**Comment by MuubNito** [comment] 2023-08-31 20:47
By the way, I may not respond that fast since I am not that active on github

**Comment by fire** [comment] 2023-08-31 23:51
Our physics team is a bit small so this may be left unsolved longer than we want. Headsup

**Comment by kleonc** [comment] 2023-09-01 10:40
The "issue" is caused by the `position = round(position)` being done at the end of `_physics_process`.

Here's a showcase of how position changes:
<details><summary>player.gd from the MRP modified for testing (click to expand)</summary>
<p>

```gdscript
extends CharacterBody2D


const SPEED = 89.0
const JUMP_VELOCITY = -275.0

# Get the gravity from the project settings to be synced with RigidBody nodes.
var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")

func _ready() -> void:
	print("SPEED = %.3f" % [SPEED])

func _physics_process(delta):
	if Engine.get_physics_frames() >= 10:
		get_tree().quit()

	var position_old := position

	# Add the gravity.
	if not is_on_floor() and velocity.y < 400:
		velocity.y += gravity * delta

	# Handle Jump.
	if Input.is_action_just_pressed("jump") and is_on_floor():
		velocity.y = JUMP_VELOCITY

	# Get the input direction and handle the movement/deceleration.
	# As good practice, you should replace UI actions with custom gameplay actions.
#	var direction = Input.get_axis("walk_left", "walk_right")
	var direction = 1.0

	if direction:
		velocity.x = SPEED * direction
	else:
		velocity.x = 0

	move_and_slide()
	var position_new := position

	position = round(position)

	prints("[frame=%d] %-6.3v ---> %-6.3v ---rounded--> %-6.3v" % [Engine.get_physics_frames(), position_old, position_new, position])
```

</p>
</details> 

Outputs:
```
SPEED = 89.000
[frame=0] (27.000, 93.000) ---> (28.483, 93.272) ---rounded--> (28.000, 93.000)
[frame=1] (28.000, 93.000) ---> (29.483, 93.544) ---rounded--> (29.000, 94.000)
[frame=2] (29.000, 94.000) ---> (30.483, 94.817) ---rounded--> (30.000, 95.000)
[frame=3] (30.000, 95.000) ---> (31.483, 96.089) ---rounded--> (31.000, 96.000)
[frame=4] (31.000, 96.000) ---> (32.483, 96.925) ---rounded--> (32.000, 97.000)
[frame=5] (32.000, 97.000) ---> (33.483, 97.000) ---rounded--> (33.000, 97.000)
[frame=6] (33.000, 97.000) ---> (34.483, 97.000) ---rounded--> (34.000, 97.000)
[frame=7] (34.000, 97.000) ---> (35.483, 97.000) ---rounded--> (35.000, 97.000)
[frame=8] (35.000, 97.000) ---> (36.483, 97.000) ---rounded--> (36.000, 97.000)
[frame=9] (36.000, 97.000) ---> (37.483, 97.000) ---rounded--> (37.000, 97.000)
```
```
SPEED = 90.000
[frame=0] (27.000, 93.000) ---> (28.500, 93.272) ---rounded--> (29.000, 93.000)
[frame=1] (29.000, 93.000) ---> (30.500, 93.544) ---rounded--> (31.000, 94.000)
[frame=2] (31.000, 94.000) ---> (32.500, 94.817) ---rounded--> (33.000, 95.000)
[frame=3] (33.000, 95.000) ---> (34.500, 96.089) ---rounded--> (35.000, 96.000)
[frame=4] (35.000, 96.000) ---> (36.500, 96.925) ---rounded--> (37.000, 97.000)
[frame=5] (37.000, 97.000) ---> (38.500, 97.000) ---rounded--> (39.000, 97.000)
[frame=6] (39.000, 97.000) ---> (40.500, 97.000) ---rounded--> (41.000, 97.000)
[frame=7] (41.000, 97.000) ---> (42.500, 97.000) ---rounded--> (43.000, 97.000)
[frame=8] (43.000, 97.000) ---> (44.500, 97.000) ---rounded--> (45.000, 97.000)
[frame=9] (45.000, 97.000) ---> (46.500, 97.000) ---rounded--> (47.000, 97.000)
```
```
SPEED = 91.000
[frame=0] (27.000, 93.000) ---> (28.517, 93.272) ---rounded--> (29.000, 93.000)
[frame=1] (29.000, 93.000) ---> (30.517, 93.544) ---rounded--> (31.000, 94.000)
[frame=2] (31.000, 94.000) ---> (32.517, 94.817) ---rounded--> (33.000, 95.000)
[frame=3] (33.000, 95.000) ---> (34.517, 96.089) ---rounded--> (35.000, 96.000)
[frame=4] (35.000, 96.000) ---> (36.517, 96.925) ---rounded--> (37.000, 97.000)
[frame=5] (37.000, 97.000) ---> (38.517, 97.000) ---rounded--> (39.000, 97.000)
[frame=6] (39.000, 97.000) ---> (40.517, 97.000) ---rounded--> (41.000, 97.000)
[frame=7] (41.000, 97.000) ---> (42.517, 97.000) ---rounded--> (43.000, 97.000)
[frame=8] (43.000, 97.000) ---> (44.517, 97.000) ---rounded--> (45.000, 97.000)
[frame=9] (45.000, 97.000) ---> (46.517, 97.000) ---rounded--> (47.000, 97.000)
```

It behaves according to the code, no bug in here. Hence closing.

@MuubNito For the future: if you're not sure you're facing a bug please try asking for help in [other community channels](https://godotengine.org/community/) (Q&A, Discord, Reddit, etc.) before opening an issue in here (this is a bug tracker, not a help desk). :slightly_smiling_face:

**Closed by kleonc** 2023-09-01 10:40 UTC
Labels: topic:physics

**Comment by MuubNito** [comment] 2023-09-02 00:00
Thanks for the support!

**Comment by MuubNito** [comment] 2023-09-02 00:04
Thanks! :)
