### ISSUE TITLE
_process still called when tree is paused

### ISSUE THREAD

**Issue by Nysosis** [godotengine/godot#82385] opened 2023-09-26 17:51 UTC
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 6.1.7601 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 30.0.14.7304) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

Not sure if this is a docs issue or a bug.

In the [processes mode](https://docs.godotengine.org/en/stable/tutorials/scripting/pausing_games.html#process-modes) docs, it states:

> The _process, _physics_process, _input, and _input_event functions will not be called. However signals still work and cause their connected function to run, even if that function's script is attached to a node that is not currently being processed.

However in my app the `_process` is still being called even when paused (or I'm misunderstanding something, which is probably the more likely)

### Steps to reproduce

1. Start a new instance of the repro app
2. Start a new game
3. Pause the game (via the enter key)
4. Press the escape key

You should see the print of `close2` being emitted on that escape key press from within `_process`, even though the game has been paused via the pause behaviour.

### Minimal reproduction project

[WhackThemBugs.zip](https://github.com/godotengine/godot/files/12730553/WhackThemBugs.zip)

**Comment by bitsawer** [comment] 2023-09-26 20:45
The pause does stop `_process()` from being called, but because `_on_pause_popup_popup_hide()` unpauses the game you see that print.

For example, add `print(Time.get_ticks_msec())` to `_process()` and you should easily see that pausing stops it from being called. Closing as not a bug. In the future, you can ask other community channels first if you are not sure about some behavior: https://godotengine.org/community

**Closed by bitsawer** 2023-09-26 20:45 UTC
