### ISSUE TITLE
Inspector plugIN impossible to set size for container

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#93936] opened 2024-07-04 12:55 UTC
### Tested versions

4.2.1 stable

### System information

windows 10

### Issue description

size is always at a minimum, impossible to increase container Vertical size

### Steps to reproduce

- create an inspector plugIN script
- create a plugIN
- load that script in the plugIN
- add a ScrollContainer
- add a VBoxContainer
- add labels inside VBoxContainer

![plugInsp](https://github.com/godotengine/godot/assets/77213594/894d14be-b8f6-430c-9c17-22357d66dc7e)

```
extends EditorInspectorPlugin

func _can_handle(object):
	if ( object is Node2D ):
		return true;


func _parse_end(object):

	var scrollCont1 = ScrollContainer.new();
	var vBoxCont1 = VBoxContainer.new();
	var labell_1 = Label.new();
	scrollCont1.size.y = 200;
	
	scrollCont1.add_child( vBoxCont1 );
	vBoxCont1.add_child( labell_1 );
	labell_1.text = " 000 "
	
	for n in 5:
		var a = labell_1.duplicate();
		a.text = "LABEL -> " + str(n);
		vBoxCont1.add_child( a );
	
	add_custom_control(scrollCont1);
```

### Minimal reproduction project (MRP)

[plgIN_BOXscroll.zip](https://github.com/user-attachments/files/16099145/plgIN_BOXscroll.zip)

**Comment by jonSP12** [comment] 2024-07-04 13:03
It works, thanks
this way iam able to increase the size

#scrollCont1.size.y = 200;
scrollCont1.set_custom_minimum_size(Vector2(100, 50));

i tried with the anchors ( full rect ) at frist, has that is how most people set this nodes in the editor, but was getting the No size result

**Comment by AThousandShips** [comment] 2024-07-04 13:04
Then please ask in the [forums](https://forum.godotengine.org/) instead in the future, this is for bug reporting, not support questions, please make sure something is a bug before reporting

Closing as this is not a bug

**Closed by AThousandShips** 2024-07-04 13:04 UTC
