### ISSUE TITLE
Support for heightmap terrains

### ISSUE THREAD

**Issue by MirceaKitsune** [godotengine/godot#16299] opened 2018-02-02 01:33 UTC
I recently got the new 3.0 release of Godot, which I'm slowly learning in the process of creating my own games. One thing that was quickly brought to my attention is the absence of a builtin terrain editor: The engine may not be an appealing option for outdoor games at the moment, due to lacking the ability to create and terraform even a basic heightmap terrain from within the editor (ideally in-game as well via scripting).

A third-party plugin offering the desired functionality was already designed, and from what I'm seeing it's very professional and works quite smoothly. It implements a special node type for terrains, which gives you a surface painting toolkit that lets you modify a surface using various brush designs. A video showing this in action can be found here:

https://www.youtube.com/watch?v=pfVAfUEmNJs

Below is the plugin in cause for Godot version 3.0:

https://github.com/Zylann/godot_heightmap_module

Unless any issues or reasons I'm not aware of exist, is this addon a viable option for integration into mainstream Godot? If there are any reasons why this specific library isn't ideal by default, perhaps those reasons can be fixed or a similar alternative developed?

**Comment by mhilbrunner** [comment] 2018-02-02 02:20
Duplicate of feature proposal in https://github.com/godotengine/godot/issues/3616.
Also relevant: https://github.com/godotengine/godot/issues/9046

**Closed by mhilbrunner** 2018-02-02 02:20 UTC
