### ISSUE TITLE
Very short audio clips repeat regardless of settings

### ISSUE THREAD

**Issue by SdgGames** [godotengine/godot#53324] opened 2021-10-02 05:01 UTC
### Godot version

3.3.4, 3.3.3, and 3.3.2

### System information

Windows Server 2022 Standard

### Issue description

Very small .wav files will loop endlessly regardless of import settings.

I downloaded [this](https://freesound.org/people/NoiseCollector/sounds/4384/) sound effect for a Pong game, but it would repeat no matter what settings I try. I verified that the loop checkbox is disabled. Loop mode seems to be defaulting to Forward mode, and it resets to Forward mode every time I close and re-open the project. I tried adding padding to the same audio clip, extending it to a length of 0.5 seconds, and it now works as expected.

I uploaded a minimal reproduction project with both audio clips. I noticed that the audio clip preview box in the inspector will also repeat when playing the short clip.

### Steps to reproduce

There are two identical audio files in this project. S1.wav is a blip sound lasting 0.06 seconds. S2.wav is the same blip sound with padding, totaling 0.5 seconds. Running or exporting the project with S2 in the AudioStreamPlayer Stream field will result in a single blip. Running with S1 in the Stream field will result in an endless repeat of the sound effect.

### Minimal reproduction project

[Audio_Bug.zip](https://github.com/godotengine/godot/files/7270876/Audio_Bug.zip)

**Comment by akien-mga** [comment] 2021-10-02 09:58
Duplicate of #46164.

**Closed by akien-mga** 2021-10-02 09:58 UTC
