### ISSUE TITLE
Icon to restore the default value

### ISSUE THREAD

**Issue by GodoterFR** [godotengine/godot#59096] opened 2022-03-13 11:38 UTC
### Godot version

v3.4.3.stable.official [242c05d12]

### System information

Windows 10, GLES 3.0, GPU Intel HD Graphic 630 27.20.100.8935, CPU i3-7300 10.0.19041.546

### Issue description

When changing a default value in the inspector, an icon (a circular arrow) allows you to return to the default value.

This icon is missing in :
Particles2D -> Process Material > Orbit Velocity (for Velocity and Velocity Random)

### Steps to reproduce

Add a Particles2D node
Add a ParticlesMaterial
Go to Orbit Velocity
Change the Velocity and Velocity Random values
No return to default value possible

**Comment by KoBeWi** [comment] 2022-03-13 11:59
Duplicate of #30651

**Closed by KoBeWi** 2022-03-13 11:59 UTC
