### ISSUE TITLE
.NET 6: The game crashes on System.AccessViolationException

### ISSUE THREAD

**Issue by wizcas** [godotengine/godot#66174] opened 2022-09-20 18:57 UTC
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 11,  3080Ti, Vulkan mobile

### Issue description

I'm making a shooter game. When there are many node instances been created for bullets, the game player crashes with the following log printed in verbose mode:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_variant_destroy(Godot.NativeInterop.godot_variant ByRef)
   at Godot.NativeInterop.godot_variant.Dispose()
   at Godot.Variant+Disposer.Dispose(Boolean)
   at Godot.Variant+Disposer.Finalize()
```

### Steps to reproduce

1. Run godot with `--editor --verbose`
2. Open the attached project
3. Run the game
4. Hold left mouse button to start shooting knifes. Wait for a while (~ 20 seconds) and it'll eventually crash.
5. Check the terminal log for the error message. **NO ERRORS ARE SHOWN in editor**

### Minimal reproduction project

[bug-mem-violation.zip](https://github.com/godotengine/godot/files/9610550/bug-mem-violation.zip)

**Comment by wizcas** [comment] 2022-09-21 17:27
More info on this:

1. If all instances are `QueueFree`'d on collision, it won't crash
2. If instances are stopped (by velocity set to zero) on collision, it'll still crash after a while, even if there's no new instance is created.

**Comment by wihrl** [comment] 2022-09-23 12:12
This seems to happen for me too. Spawning lots of objects results in a silent crash, eventually.

**Comment by Imvoo** [comment] 2022-10-02 10:26
I'm getting the same issue, sometimes my game crashes with a `System.AccessViolationException`, sometimes my game crashes with no error.

I've created a minimal project to replicate this problem: [test-memory-bug.zip](https://github.com/godotengine/godot/files/9692219/test-memory-bug.zip)

<details>
<summary>Code Snippet (if you want a quick summary), just attach this to any root Scene node</summary>

```csharp
public partial class MemoryCrashTest : Node2D
{
  public override void _Ready() {
    var peer = new ENetMultiplayerPeer();
    peer.CreateServer(12345);
    Multiplayer.MultiplayerPeer = peer;
  }

  public override void _PhysicsProcess(double delta) {
    for (var i = 0; i < 1000; i++) {
      ThisWillEventuallyCrash();
      // ThisWillNotCrash();
    }
  }

  public void ThisWillEventuallyCrash() {
    Rpc(nameof(Ping), Variant.CreateFrom(new byte[] {1, 2}));
  }

  public void ThisWillNotCrash() {
    var variant = Variant.CreateFrom(new byte[] {1, 2});
    Rpc(nameof(Ping), variant);
    variant.Dispose();
  }

  [RPC(CallLocal = true)]
  public void Ping(byte[] array) {
    GD.Print("Pong");
  }
}
```
</details>

In this example, we create a Variant using `Variant.CreateFrom(byte[])` and send it to ourselves via RPC.
If we don't manually call `.Dispose` on the `Variant`, the game will crash after 2-3 seconds (or after 16350 messages have been logged in my case).
If we call `.Dispose` on the `Variant`, the game no longer crashes (even if run for a long time).

I'm not sure if this is 100% the same issue or not (since it's hard to diagnose properly as sometimes there's no error messages on crash), but hopefully this helps diagnose the issue!

**Comment by raulsntos** [comment] 2022-11-26 04:30
I opened PR https://github.com/godotengine/godot/pull/69194 that may fix this issue, can you try it out to confirm?

Linux users can download the artifact built by CI: https://github.com/godotengine/godot/suites/9514119809/artifacts/451640372
For other platforms, you'll have to build Godot yourself.

**Comment by neikeq** [comment] 2022-12-10 09:49
Can you check if this is fixed in beta 8?

**Comment by Chaosus** [comment] 2022-12-10 12:05
Interesting in the beta 8 Callable constructor lacks the supports for lambda functions, and the project attached to this topic will not compile:

![image](https://user-images.githubusercontent.com/3036176/206854273-20af84d4-563c-4b29-95f7-65ddbde9954a.png)

**Comment by raulsntos** [comment] 2022-12-10 12:53
Since beta 4 this constructor was replaced with a static method: `Callable.From`. (https://github.com/godotengine/godot/pull/67987)

```csharp
Callable.From((Projectile projectile) =>
{
    AddChild(projectile);
    projectile.GlobalPosition = Muzzle.GlobalPosition;
    projectile.ZIndex = 1;
}).CallDeferred(projectile);
```

**Comment by markdibarry** [comment] 2023-03-15 00:22
Still present in 4.1.dev (550a779)

**Comment by RedworkDE** [comment] 2023-03-17 22:50
@markdibarry do you have an MRP for that? I do not get a crash with either of the two projects in this issue on current master.

**Comment by markdibarry** [comment] 2023-03-18 15:24
@RedworkDE Tried MRP supplied by OP with latest build (550a7798510810d238b733a54f69da71b2a2d152), and can't reproduce. Good enough for me.

**Comment by Anixias** [comment] 2023-04-18 00:51
Whenever I close my game, it freezes for a very long time before finally closing. Inspecting it with JetBrains Rider, it is caused by an AccessViolationException during the Dispose method of a TileData. This is in 4.0.2 stable.

**Comment by RedworkDE** [comment] 2023-04-19 11:22
@Anixias That looks like a very different issue to me, please open a new issue for that with an MRP

**Comment by germanbv** [comment] 2023-05-25 06:30
I have the same problem as @Anxias and I'm also on 4.0.2 stable.

**Comment by RedworkDE** [comment] 2023-05-25 07:01
@germanbv That still looks like a completely different crash than what this issue is about (which is almost certainly fixed), so same as before, please create an MRP for your crash and open a new issue for it.

**Comment by germanbv** [comment] 2023-05-25 07:04
@RedworkDE I'll do it as soon as I know how to reproduce it.  today it happened to me at least 10 times, but I have no idea what is causing it. Sometimes the whole editor crashes without a reason and I think it might be related to this.

**Comment by LordBrkica** [comment] 2023-07-15 19:50
I get the same exception, it happens somtimes (so 50% - 50% chance of it happening or everything being ok).  
It happens when I try to switch from a scene which has a big tilemap (200x200 tiles) back to my main menu via **GetTree().ChangeSceneToPacked**

**Comment by RedworkDE** [comment] 2023-07-15 21:02
Just to confirm, when the crash happens your app is not trying to exit? If it is please see https://github.com/godotengine/godot/issues/77486, otherwise please try to narrow down your project and open a new issue with an MRP.

**Comment by LordBrkica** [comment] 2023-07-19 10:51
You are right, the app si trying to exit when the crash happens.

**Comment by raulsntos** [comment] 2024-06-10 16:22
This exception could be caused by a number of reasons and it looks like the issue originally reported was fixed. If anyone is still getting a `System.AccessViolationException` in Godot 4.2.2 or greater, please create a new issue and provide an MRP. Your issue likely has a different cause from this one.

**Closed by raulsntos** 2024-06-10 16:22 UTC
Labels: bug, needs testing, topic:dotnet, crash
