### ISSUE TITLE
No function to undo add_control_to_container in EditorPlugin

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#15731] opened 2018-01-15 01:51 UTC
**Godot version:** 3.0

**Issue description:** The functions add_control_to_dock and add_control_to_bottom_panel from EditorPlugin can be undone with remove_control_from_docks and remove_control_from_bottom_panel respectively. Controls added using add_control_to_container cannot be removed in a similar fashion.

The class documentation says "If your plugin is being removed, also make sure to remove your custom controls too." without specifying the proper way to do so. This is unlike the other two add_control_to... that suggest to call remove_control_from...

**Proposed change:** Either describe the proper way to clear controls from containers if it differs from the approach used for docks and the bottom panel, or implement a function remove_control_from_containers.

**Comment by vnen** [comment] 2018-01-15 02:27
Duplicate of #5968.

**Closed by vnen** 2018-01-15 02:27 UTC
