### ISSUE TITLE
Having a MultiMesh with "Use Colors" and "Local to Scene" on at the same time causes Project to crash when Run is pressed

### ISSUE THREAD

**Issue by FrasherGray** [godotengine/godot#94764] opened 2024-07-26 01:12 UTC
### Tested versions

- Reproducible in: 4.2.2 stable

### System information

Windows 11 - Godot v.4.2.2.stable - Intel

### Issue description

The issue is that you can't test your project when a multimesh in your scene tree has "Use Colors" and "Local to Scene" selected at the same time, and no error comes up when doing so. I confirmed no errors are detected with the _console.exe version file.

### Steps to reproduce

Create a new project
add multimesh3d node
give multimesh3d a new multimesh
select "Use Colors"
select "Local to Scene"
press "Run"

### Minimal reproduction project (MRP)

https://github.com/FrasherGray/MRPMultimeshBug.git

**Comment by huwpascoe** [comment] 2024-07-26 07:51
Probably trying to copy a null buffer on scene initialization. If the instance_count is set to 1, does this prevent the crash?

**Comment by FrasherGray** [comment] 2024-07-26 11:54
@huwpascoe yeah, it does.

**Comment by RadiantUwU** [comment] 2024-08-22 19:24
Cannot reproduce with the above MRP.

**Comment by FrasherGray** [comment] 2024-08-23 22:58
> Cannot reproduce with the above MRP. v4.3.rc.custom_build [[739019e](https://github.com/godotengine/godot/commit/739019e4e4a6e4763e37adfd9883a1c85d5f6249)]

Are you saying that the issue has been inadvertently solved, or can you not replicate it in 4.2 either?

**Comment by AThousandShips** [comment] 2024-09-17 20:36
Closing as fixed based on above, if you can still reproduce this in 4.3 or later please comment here and this can be reopened

**Closed by AThousandShips** 2024-09-17 20:36 UTC
Labels: bug, needs testing, crash, topic:3d
