### ISSUE TITLE
get_node returns null objects arbitrarily

### ISSUE THREAD

**Issue by eko234** [godotengine/godot#38425] opened 2020-05-03 05:37 UTC
i'm trying to access one of my nodes children, but when i use the method get_node, it first returns me a [Object:Empty] and then it returns the current object, obviously crashing the game, doing something so simple as :

`var nd := get_children()
print(str(nd))`

results in the following output

[]
[[CanvasLayer:1183], [Node2D:1197]]

**Comment by eko234** [comment] 2020-05-03 05:50
wow, apparently it had something to do with the fact that the node "GOD" was already taken for godot i guess.

**Comment by asheraryam** [comment] 2020-05-03 14:31
If there are reserved Node names then they should definitely be documented somewhere.

**Comment by eduardonunesp** [comment] 2020-05-04 18:12
Hey @eko234 do you have some example that can be reproduced by devs?

**Comment by Calinou** [comment] 2020-05-04 19:50
Duplicate of #32383?

**Comment by KoBeWi** [comment] 2020-05-23 16:34
@eko234 Can you test again in 3.2.2 beta 3?
btw there are no reserved node names.

**Comment by madmiraal** [comment] 2020-06-01 09:48
Closing as unable to reproduce without a minimal reproduction project.

**Closed by madmiraal** 2020-06-01 09:48 UTC
