### ISSUE TITLE
GDScript editor Parse error with hex literals containing "b"

### ISSUE THREAD

**Issue by johngirvin** [godotengine/godot#33710] opened 2019-11-18 16:07 UTC
**Godot version:**
3.2 BETA 1

**Issue description:**
An "parse error" is raised in the GDScript editor when entering a hex literal containing a lower case "b" character.

**Steps to reproduce:**

1. Open a GDScript editor
2. Enter the code `var x = 0xb`
3. Observe the "Parse error: Invalid numeric constant at 'b'" message

**Comment by Calinou** [comment] 2019-11-18 16:24
This should be fixed now that #32966 has been merged, can you test a [nightly build](https://hugo.pro/projects/godot-builds/) to confirm this?

**Comment by akien-mga** [comment] 2019-11-18 16:26
Indeed, this seems to be a duplicate of #32963 which is fixed in master/upcoming 3.2 beta 2.

**Comment by johngirvin** [comment] 2019-11-18 16:33
Confirmed fixed in nightly `3.2.beta.calinou.0a9235b4` - thanks.

**Closed** 2019-11-18 16:41 UTC
