### ISSUE TITLE
Saving in Undocked Script Editor Snaps Back to Godot Window

### ISSUE THREAD

**Issue by sian2005** [godotengine/godot#79131] opened 2023-07-06 21:47 UTC
### Godot version

4.1 stable

### System information

Windows 10

### Issue description

Upon saving (Control+ S) inside the Script Editor, it snaps back to the Godot window, which is unexpected behaviour. Saving should not update the window, neither change windows.

### Steps to reproduce

Press 'Control + S' in an undocked Script Editor

### Minimal reproduction project

_Not required to reproduce bug_

**Comment by quinnyo** [comment] 2023-07-08 06:09
Duplicate of #78672 ?

**Closed** 2023-07-09 09:35 UTC
Labels: bug, topic:editor, topic:input
