### ISSUE TITLE
Virtual Shader Ui 

### ISSUE THREAD

**Issue by ALipAkrohk** [godotengine/godot#48414] opened 2021-05-03 15:57 UTC
**Godot version:**
3.3.Stable_arch_linux

**OS/device including version:**
Gnu/Linux

**Issue description:**

his is a request for godot's development team to refine godot's user interface to be more user friendly and easier to use, godot's an amazing tool for creating games of all sorts but something that I often find annoying is its user interface ESPECIALLY when it comes down to nodes.
everyone should know what i'm talking about . if you've ever tried to do something in godot through nodes (by nodes i mean visual scripting/visual shaders and animationtrees) i'm pretty sure you have come to notice that something about the interface is just wrong. it makes the engine look so unprofessional . 
not only the zooming in and out method is so inconvenient i often find myself struggling with connecting nodes to another. if you zoom out just a little bit you'll notice that you can't really connect nodes together anymore.. godot is such a capable engine with a bright future infront of it and for that reason i find this 
which to some of you might come as a minor issue , unfitting . personally i think godot can really benefit from a ui refinement. not having a good looking, fitting UI that's  convenient to use and easy to the eyes can really scare people away and that's not to be overlooked for a project like godot which's mostly driven by it's community . i don't know maybe hire a freelancer to redesign some of the icons to meet today's modern standards? or maybe just tweak the code a bit to make the whole node-based system smoother to use? like really connecting material nodes from just a tiny bit zoomed out view is almost a challenge on its own
.an example for this is the projcet 'material maker' which has been made using godot. it shares the same interface when it comes down to navigating through nodes and i think a lot of people can agree that while it's a flexible and capable tool and can be used to make some high quality materials, it does suffer from bad ui .thanks for reading through .

![image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F13393087%2F88777663-c25ebc00-d187-11ea-8cd4-f6acb034f2fc.png&f=1&nofb=1)

**Comment by Calinou** [comment] 2021-05-03 16:21
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Closed by Calinou** 2021-05-03 16:21 UTC

**Comment by akien-mga** [comment] 2021-05-03 18:48
> Duplicate of #46425. Try upgrading to 3.3; the issue has likely been resolved there.

To clarify, the issue is not resolved in 3.3, but it will be in 3.4 and 4.0. Possibly also in a future 3.3.x update.
