### ISSUE TITLE
Godot on Mac OS doesn't detect Blender executable

### ISSUE THREAD

**Issue by demolen** [godotengine/godot#94763] opened 2024-07-26 01:06 UTC
### Tested versions

reproducible in Godot v4.3 , macOS Sonoma, Blender 4.2, Apple Silicon M2

### System information

 macOS Sonoma, Blender 4.2, Apple Silicon M2

### Issue description

Godot doesn't detect the executable of blender, even when pointed at the executable manually

### Steps to reproduce

try to import a .blend file on MacOs:

<img width="1748" alt="Screenshot 2024-07-26 at 02 48 55" src="https://github.com/user-attachments/assets/9e77df54-b88b-4860-929e-ed4058857851">

### Minimal reproduction project (MRP)

[blender.zip](https://github.com/user-attachments/files/16385334/blender.zip)

**Comment by Calinou** [comment] 2024-07-26 01:09
- Related to https://github.com/godotengine/godot/issues/84920.

**Comment by akien-mga** [comment] 2024-07-26 08:07
The Blender path setting changed in 4.3 and is now expected to be a path to the Blender _binary_, not to its parent folder (which was the source of a lot of confusion in 4.0 - 4.2).

Does it work if you pick the actual `Blender` binary in that `MacOS` folder?

**Comment by demolen** [comment] 2024-07-26 12:40
> pick the actual `Blender` bin

I've tried pointing both at the executable in `/Applications/Blender.app/Contents/MacOS`  as well as `/Applications/Blender.app` but none would result in a detection.


`x@MacBook MacOS % pwd
/Applications/Blender.app/Contents/MacOS
x@MacBook MacOS % ls -la
total 305192
drwxr-xr-x@ 3 x  admin         96 Jul 26 02:58 .
drwxr-xr-x@ 7 x  admin        224 Jul 16 08:36 ..
-rwxr-xr-x@ 1 x  admin  156255424 Jul 16 08:37 Blender
x@MacBook MacOS % 
`

**Comment by demolen** [comment] 2024-07-26 13:37
Things I tried so far:

making a symlink:
` ln -s /Applications/Blender.app/Contents/MacOS/Blender /usr/local/bin/blender` didn't work
moving Blender elsewhere also didn't work
renaming Blender to blender also didn't
running godot with `sudo` also didn't

**Comment by akien-mga** [comment] 2024-07-26 14:18
> I've tried pointing both at the executable in `/Applications/Blender.app/Contents/MacOS` (see the screenshot in the first post)

The screenshot in the first post shows you pointing at the **folder** `/Applications/Blender.app/Contents/MacOS`. The executable should be `/Applications/Blender.app/Contents/MacOS/Blender`.

**Comment by AThousandShips** [comment] 2024-07-26 14:22
The dialog pointing to a directory instead of a file is covered in:
* https://github.com/godotengine/godot/issues/93235

Does it work if setting the path from the settings?

**Comment by demolen** [comment] 2024-07-26 14:22
> > I've tried pointing both at the executable in `/Applications/Blender.app/Contents/MacOS` (see the screenshot in the first post)
> 
> The screenshot in the first post shows you pointing at the **folder** `/Applications/Blender.app/Contents/MacOS`. The executable should be `/Applications/Blender.app/Contents/MacOS/Blender`.

yes! manually entering the Path to the executable "/Applications/Blender.app/Contents/MacOS/Blender" solved the issue.

**Comment by demolen** [comment] 2024-07-26 14:24
this is however still an issue, since browse to the executable seem to fail detecting the blender.

**Comment by AThousandShips** [comment] 2024-07-26 14:25
When using browse in the settings or the dialog?

**Comment by demolen** [comment] 2024-07-26 14:26
https://github.com/user-attachments/assets/79f52c93-2620-4970-8b49-3904ceb230dc

**Comment by AThousandShips** [comment] 2024-07-26 14:27
Then that's a duplicate of:
* https://github.com/godotengine/godot/issues/93235

Thank you for reporting

**Comment by demolen** [comment] 2024-07-26 14:28
> When using browse in the settings or the dialog?

It seems that it requires blender "executable" however upon "browse" we can only select a directory.

**Comment by demolen** [comment] 2024-07-26 14:28
> Then that's a duplicate of:
> 
> * [Blend import dialog window ask for folder, not file. #93235](https://github.com/godotengine/godot/issues/93235)
> 
> Thank you for reporting

exactly

**Closed by AThousandShips** 2024-07-26 14:27 UTC
Labels: bug, platform:macos, topic:editor, needs testing, topic:import
