### ISSUE TITLE
Physics Profiler sections shows something irrelevant

### ISSUE THREAD

**Issue by hedin-hiervard** [godotengine/godot#26904] opened 2019-03-11 09:51 UTC
**Godot version:**

3.1 beta11

**OS/device including version:**

macOS

**Issue description:**

I'm debugging the peak FPS drop and encountered this. This looks like a profiler bug to me, since Physics time is high while Physics2D sections shows really low usage.
What I am actually doing to slow things down is some UI node manipulation.
<img width="316" alt="Screen Shot 2019-03-11 at 11 49 16" src="https://user-images.githubusercontent.com/961822/54114838-f222ed80-43f3-11e9-8747-c5dee97317f9.png">

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by hedin-hiervard** [comment] 2019-03-11 09:53
The only explanation I can have is that Physics it actually _fixed_process() time. But why it doesn't show up in Script Functions then?

**Comment by Ramh5** [comment] 2020-05-27 01:21
I am having similar problems understanding the profiler. I have no physics in my game. What is this Physics time that takes the entire time.  Also why don't Script Functions time add up to all the functions below it. FYI the frame did take about 4 seconds, so the profiler got that right. But it should all be inside the _redraw_table() and it just shows 10% of what is should be.
![image](https://user-images.githubusercontent.com/16180873/82965490-43d27c00-9f96-11ea-9e78-e45124638654.png)

**Comment by Shfty** [comment] 2021-09-22 17:05
Same issue here on 3.3.2:
![image](https://user-images.githubusercontent.com/1253239/134388557-037658e5-e0e9-4787-a0d0-c98ffd3877bb.png)

The spikes represent selecting objects in a 3D editor built within Godot; various things happen in response to this, such as assembling composite meshes for outline rendering in a separate viewport / world, and assembling similar composite collision shapes so the selected objects can all collide as one while being moved around.

However, disabling the code that talks to the physics server - namely the creation of composite collision shapes - has no effect on the profiler output. The spikes still occur on selection change, suggesting that the performance issue lies elsewhere, but are nonetheless attributed to Physics Time.

**Comment by Calinou** [comment] 2021-10-16 15:02
Duplicate of https://github.com/godotengine/godot/issues/23715#issuecomment-859460407.

**Closed by Calinou** 2021-10-16 15:02 UTC
Labels: bug, topic:editor
