### ISSUE TITLE
is it possible to add custom property for a node through the inspector?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11384] opened 2017-09-18 01:39 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
ALL

**Issue description:**

It's easy to add property to a node by call Object.set ( String property, Variant value ).
For some cases, we may need to add some nodes of the same type and attach some data to each node without extends the Node.
 of course, this may be done through scripts. But it will be intuitive this may be done just through the inspector.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Noshyaar** [comment] 2017-09-18 05:35
No. Use `export` for now.
```
extends Node
export var custom_prop = 0
```

**Comment by alexzheng** [comment] 2017-09-18 05:42
I knew it's impossible for current release.
I asked it here to make sure whether it's possible to have this in future release.

**Comment by toger5** [comment] 2017-09-18 11:33
@alexzheng
Can u make an example what u need it for?
Properties only make sense kg DMAX habe an impacted in sth.
Since you want to add them aufblitzen an additional script there is no additional functionality. And all the functionality which should be acessible is already bound to GDscript anyways.

**Comment by alexzheng** [comment] 2017-09-18 12:28
For example, I have several menus  extends from a base menu, and all buttons pressed signal is handled in a callback. If I can attach data to these buttons, It will not need to attach scripts to each button.

**Comment by Zylann** [comment] 2017-09-18 12:48
I think you can already bind additional parameters when you connect signals:
![image](https://user-images.githubusercontent.com/1311555/30542640-10f124a4-9c78-11e7-9102-ca71f00e7860.png)

**Comment by alexzheng** [comment] 2017-09-18 13:01
@Zylann
Thanks,I know this,but this is not my situation.

**Comment by toger5** [comment] 2017-09-18 13:08
Just came up with another situation.
A root node which handles multiple instances. Than each instance can store a property how it is treated. Things like how much money you get when collecting an item. Or how much Damage is Felt when walking over it. How propagieren it is, that it explodes...

**Comment by Zylann** [comment] 2017-09-18 17:08
Like tag properties? A sort of arbitrary dictionary every node (or even resource) can have? I think such a feature would need core dev advice (and would benefit only non-coders)

**Comment by reduz** [comment] 2017-09-18 19:07
This is supported but it's not really exposed.. maybe it should be

**Comment by alexzheng** [comment] 2017-09-18 23:20
Yes, just like the tag, but Godot can have more kind of types supported.
The final scene file may just like the export did in script, but we can done this without a script. 
Not only non-coders, but also programmer  handle  these properties in scripts.

**Comment by bojidar-bg** [comment] 2018-05-22 16:36
Depends on the resolution of #18591.

**Comment by Calinou** [comment] 2019-10-02 16:42
Duplicate of #5433.

**Closed by Calinou** 2019-10-02 16:42 UTC
Labels: feature proposal, topic:editor

**Comment by ballerburg9005** [comment] 2020-05-29 15:39
I wrote a plugin to solve exactly this issue:

https://github.com/ballerburg9005/godot-metadata-inspector
