### ISSUE TITLE
Linux (+windows mingw) Mono mscorlib.dll not found

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#34825] opened 2020-01-04 19:08 UTC
**Godot version:**
master (https://github.com/godotengine/godot/commit/a7853fc04ba79a027f372eb2e8102009c31fec3b)
**OS/device including version:**
Arch Linux
**Steps to reproduce:**
```Swift
cd godot && \
git pull && \
echo 'Mono' && \
echo 'Build temporary binary' && \
scons p=server tools=yes module_mono_enabled=yes mono_glue=no -j 8 && \
#scons p=windows tools=yes module_mono_enabled=yes mono_glue=no mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' && \
echo 'Generate glue sources for linux' && \
bin/godot_server.x11.tools.64.mono --generate-mono-glue modules/mono/glue && \
echo 'Linux' && \
scons p=x11 bits=64 target=release_debug tools=yes use_llvm=yes use_lld=yes use_thinlto=yes module_mono_enabled=yes -j 8 && \
scons p=x11 bits=64 target=release_debug tools=no use_llvm=yes use_lld=yes use_thinlto=yes module_mono_enabled=yes -j 8 && \
#echo 'Generate glue sources for windows' && \
#wine bin/godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue && \
echo 'Windows' && \
scons p=windows target=release_debug tools=yes module_mono_enabled=yes mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' -j 8 && \
scons p=windows target=release_debug tools=no module_mono_enabled=yes mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' -j 8 && \
```
**Output:**
```Swift
[user@archlinux bin]$ ./godot.x11.opt.tools.64.llvm.mono
Godot Engine v3.2.beta.mono.custom_build.a7853fc04 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
 
Mono: Logfile is: /home/user/.local/share/godot/mono/mono_logs/2020_01_04 19.58.42 (129772).txt
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/run/media/user/user/git/godot/bin/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll' directory.
[user@archlinux bin]$ 
_____________________________________________________

Config attempting to parse: '/run/media/user/user/git/godot/bin/GodotSharp/Mono/etc/mono/config'. (in domain Mono, info)
Config attempting to parse: '/home/user/.mono/config'. (in domain Mono, info)
Assembly Loader probing location: '/run/media/user/user/git/godot/bin/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll'. (in domain Mono, info)
_____________________________________________________

[user@archlinux bin]$ wine godot.windows.opt.tools.64.mono.exe
000b:fixme:winediag:__wine_start_process Wine Staging 5.0-rc1 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
Godot Engine v3.2.beta.mono.custom_build.a7853fc04 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
002b:fixme:win:RegisterTouchWindow (0x10060 00000000): stub
002b:fixme:imm:ImmReleaseContext (0000000000010060, 00000000117F8B90): stub
002b:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Games",000000000032BEF8): stub
002b:fixme:avrt:AvSetMmThreadPriority (0000000012345678)->(2) stub
 
Mono: Logfile is: C:\users\user\Application Data/Godot/mono/mono_logs/2020_01_04 20.05.10 (42).txt
002b:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `Z:\run\media\user\user\git\godot\bin/GodotSharp/Mono/lib\mono\4.5\mscorlib.dll' directory.
[user@archlinux bin]$ 
______________________________________________________________________

Config attempting to parse: 'Z:\run\media\user\user\git\godot\bin/GodotSharp/Mono/etc\mono\config'. (in domain Mono, info)
Assembly Loader probing location: 'Z:\run\media\user\user\git\godot\bin/GodotSharp/Mono/lib\mono\4.5\mscorlib.dll'. (in domain Mono, info)
```

**Comment by LinuxUserGD** [comment] 2020-01-16 21:48
I found a workaround:
- copy 4.5 folder (`/run/media/user/user/git/godot/bin/GodotSharp/Mono/lib/mono/4.5`) to a temporary location while compiling
- after compilation finished, copy it back

First case (running it fails with above error that mscorlib.dll was not found):
```Swift
[user@archlinux 4.5]$ ls -a
.  ..  Facades
[user@archlinux 4.5]$ 
```
Second case (while compiling or after copying it back):
```Swift
[user@archlinux 4.5]$ ls -a
.                                            Mono.CompilerServices.SymbolWriter.dll     System.Data.Entity.dll                  System.Reactive.Experimental.dll                  System.Web.DynamicData.dll
..                                           Mono.CSharp.dll                            System.Data.Linq.dll                    System.Reactive.Interfaces.dll                    System.Web.Extensions.Design.dll
Accessibility.dll                            Mono.Data.Sqlite.dll                       System.Data.OracleClient.dll            System.Reactive.Linq.dll                          System.Web.Extensions.dll
Commons.Xml.Relaxng.dll                      Mono.Data.Tds.dll                          System.Data.Services.Client.dll         System.Reactive.Observable.Aliases.dll            System.Web.Http.dll
cscompmgd.dll                                Mono.Debugger.Soft.dll                     System.Data.Services.dll                System.Reactive.PlatformServices.dll              System.Web.Http.SelfHost.dll
CustomMarshalers.dll                         Mono.Http.dll                              System.Deployment.dll                   System.Reactive.Providers.dll                     System.Web.Http.WebHost.dll
Facades                                      Mono.Management.dll                        System.Design.dll                       System.Reactive.Runtime.Remoting.dll              System.Web.Mobile.dll
I18N.CJK.dll                                 Mono.Messaging.dll                         System.DirectoryServices.dll            System.Reactive.Windows.Forms.dll                 System.Web.Mvc.dll
I18N.dll                                     Mono.Messaging.RabbitMQ.dll                System.DirectoryServices.Protocols.dll  System.Reactive.Windows.Threading.dll             System.Web.Razor.dll
I18N.MidEast.dll                             Mono.Parallel.dll                          System.dll                              System.Reflection.Context.dll                     System.Web.RegularExpressions.dll
I18N.Other.dll                               Mono.Posix.dll                             System.Drawing.Design.dll               System.Reflection.Metadata.dll                    System.Web.Routing.dll
I18N.Rare.dll                                Mono.Profiler.Log.dll                      System.Drawing.dll                      System.Runtime.Caching.dll                        System.Web.Services.dll
I18N.West.dll                                Mono.Security.dll                          System.Dynamic.dll                      System.Runtime.CompilerServices.Unsafe.dll        System.Web.WebPages.Deployment.dll
IBM.Data.DB2.dll                             Mono.Security.Win32.dll                    System.EnterpriseServices.dll           System.Runtime.DurableInstancing.dll              System.Web.WebPages.dll
ICSharpCode.SharpZipLib.dll                  Mono.Simd.dll                              System.IdentityModel.dll                System.Runtime.Remoting.dll                       System.Web.WebPages.Razor.dll
Microsoft.Build.dll                          Mono.Tasklets.dll                          System.IdentityModel.Selectors.dll      System.Runtime.Serialization.dll                  System.Windows.dll
Microsoft.Build.Engine.dll                   Mono.WebBrowser.dll                        System.IO.Compression.dll               System.Runtime.Serialization.Formatters.Soap.dll  System.Windows.Forms.DataVisualization.dll
Microsoft.Build.Framework.dll                Mono.XBuild.Tasks.dll                      System.IO.Compression.FileSystem.dll    System.Security.dll                               System.Windows.Forms.dll
Microsoft.Build.Tasks.v4.0.dll               mscorlib.dll                               System.Json.dll                         System.ServiceModel.Activation.dll                System.Workflow.Activities.dll
Microsoft.Build.Utilities.v4.0.dll           Novell.Directory.Ldap.dll                  System.Json.Microsoft.dll               System.ServiceModel.Discovery.dll                 System.Workflow.ComponentModel.dll
Microsoft.CodeAnalysis.CSharp.dll            PEAPI.dll                                  System.Management.dll                   System.ServiceModel.dll                           System.Workflow.Runtime.dll
Microsoft.CodeAnalysis.CSharp.Scripting.dll  RabbitMQ.Client.dll                        System.Memory.dll                       System.ServiceModel.Internals.dll                 System.Xaml.dll
Microsoft.CodeAnalysis.dll                   SMDiagnostics.dll                          System.Messaging.dll                    System.ServiceModel.Routing.dll                   System.Xml.dll
Microsoft.CodeAnalysis.Scripting.dll         System.Collections.Immutable.dll           System.Net.dll                          System.ServiceModel.Web.dll                       System.Xml.Linq.dll
Microsoft.CodeAnalysis.VisualBasic.dll       System.ComponentModel.Composition.dll      System.Net.Http.dll                     System.ServiceProcess.dll                         System.Xml.Serialization.dll
Microsoft.CSharp.dll                         System.ComponentModel.DataAnnotations.dll  System.Net.Http.Formatting.dll          System.Threading.Tasks.Dataflow.dll               WebMatrix.Data.dll
Microsoft.VisualC.dll                        System.Configuration.dll                   System.Net.Http.WebRequest.dll          System.Threading.Tasks.Extensions.dll             WindowsBase.dll
Microsoft.Web.Infrastructure.dll             System.Configuration.Install.dll           System.Numerics.dll                     System.Transactions.dll
Mono.Btls.Interface.dll                      System.Core.dll                            System.Numerics.Vectors.dll             System.Web.Abstractions.dll
Mono.Cairo.dll                               System.Data.DataSetExtensions.dll          System.Reactive.Core.dll                System.Web.ApplicationServices.dll
Mono.CodeContracts.dll                       System.Data.dll                            System.Reactive.Debugger.dll            System.Web.dll
[user@archlinux 4.5]$ 
```
So both mingw windows and linux binary runs well with or without wine after this workaround.

I think it's still a bug as it seems like too many files are deleted (cleaned up) after compilation which are required.

**Comment by tinmanjuggernaut** [comment] 2020-03-15 20:46
@akien-mga @neikeq 
I'm running into this problem building Windows/mono from linux using the official build containers.

The Windows/Mono binary won't run because [mono_configure.py](https://github.com/godotengine/godot/blob/master/modules/mono/build_scripts/mono_configure.py) doesn't copy the needed mono files (e.g. mscorlib.dll) into the GodotSharp directory. It copies them for the linux install (same Godot source tree for both builds). 

I can run my linux/mono build, then windows/mono build and see mscorlib, et al appear in GodotSharp for the first, then disappear for the second.

I can confirm windows/mono included the proper files on Nov 12th. @LinuxUserGD ran into this problem by Jan 5th. So hopefully one of the changes to the above mentioned files will be easily identifiable.

@akien-mga Are you not running into this with the latest official releases?

**Comment by LinuxUserGD** [comment] 2020-03-15 21:16
@tinmanjughernaut
So I just changed order to first compile linux mono glue, after that compile for windows mono and at the end compile linux mono glue again so the files are regenerated.
Tried it without container but could be a similar compilation process / command order with them. Otherwise godot can't find required files in /bin.

Another way would be to compile a windows glue but that gave me some issues with multiple definitions using the self-compiled windows mono.

**Comment by akien-mga** [comment] 2020-03-16 08:00
It works fine on the official buildsystem, so I guess you're using a different workflow/options (likely `mono_static` is not set?). What we do:
- Build the mono glue on Linux and copy it to a shared folder: https://github.com/godotengine/godot-build-scripts/blob/master/build.sh#L153 https://github.com/godotengine/godot-build-scripts/blob/master/build-mono-glue/build.sh#L28
- Reuse the same glue in all builds, using `mono_static=yes`: https://github.com/godotengine/godot-build-scripts/blob/master/build-linux/build.sh https://github.com/godotengine/godot-build-scripts/blob/master/build-windows/build.sh https://github.com/godotengine/godot-build-scripts/blob/master/build-macosx/build.sh

**Comment by akien-mga** [comment] 2020-03-16 08:01
BTW if you don't use `mono_static=yes`, then it's likely expected that it won't copy Mono DLLs and you should have them installed system-wide from the Mono SDK. But if then Godot can't locate them, that's a bug.

**Comment by tinmanjuggernaut** [comment] 2020-03-16 11:46
Looks very similar to mine, modeled off of the documentation. I do use mono_static and copy_mono_root. I have a singular godot source tree that I mount in all dockers.

I went back to an October copy of mono_configure.py, but that did not fix the problem. :/

I've erased my whole modules/mono dir and checked it out and regenerated glue as below, that did not help.

1. I build x11/mono with `module_mono_enabled=yes mono_static=yes mono_glue=no`
2. I run that executable with `--generate-mono-glue modules/mono/glue` which puts it directly in the mounted godot source tree
3. Then I build x11 or windows.

This is my linux build command, which populates the `GodotSharp/Mono/lib/mono/4.5/` folder:

`podman run --rm -v /home/cory/gd/godot:/root/godot -w /root/godot godot-ubuntu-64:3.2-mono-6.6.0.166 scons -j12 p=x11 bits=64 tools=yes target=release_debug module_mono_enabled=yes mono_static=yes mono_glue=yes copy_mono_root=yes`

My windows command leaves that folder mostly empty:
`podman run --rm -v /home/cory/gd/godot:/root/godot -w /root/godot godot-windows:3.2-mono-6.6.0.166 scons -j12 p=windows bits=64 tools=yes target=release_debug module_mono_enabled=yes mono_static=yes mono_glue=yes copy_mono_root=yes mono_prefix=/root/dependencies/mono-64`

The only difference I see in your windows scons command are these options `warnings=no progress=no (platform instead of p) debug_symbols=no use_lto=yes `, but adding those had no impact.


Here's the bin/GodotSharp folder from a windows build.
```
bin/GodotSharp/
bin/GodotSharp/Api
bin/GodotSharp/Api/Debug
bin/GodotSharp/Api/Debug/GodotSharp.dll
bin/GodotSharp/Api/Debug/GodotSharp.pdb
bin/GodotSharp/Api/Debug/GodotSharp.xml
bin/GodotSharp/Api/Debug/GodotSharpEditor.dll
bin/GodotSharp/Api/Debug/GodotSharpEditor.pdb
bin/GodotSharp/Api/Debug/GodotSharpEditor.xml
bin/GodotSharp/Api/Release
bin/GodotSharp/Api/Release/GodotSharp.dll
bin/GodotSharp/Api/Release/GodotSharp.pdb
bin/GodotSharp/Api/Release/GodotSharp.xml
bin/GodotSharp/Api/Release/GodotSharpEditor.dll
bin/GodotSharp/Api/Release/GodotSharpEditor.pdb
bin/GodotSharp/Api/Release/GodotSharpEditor.xml
bin/GodotSharp/Mono
bin/GodotSharp/Mono/bin
bin/GodotSharp/Mono/bin/MonoPosixHelper.dll
bin/GodotSharp/Mono/etc
bin/GodotSharp/Mono/etc/mono
bin/GodotSharp/Mono/etc/mono/2.0
bin/GodotSharp/Mono/etc/mono/2.0/Browsers
bin/GodotSharp/Mono/etc/mono/2.0/Browsers/Compat.browser
bin/GodotSharp/Mono/etc/mono/2.0/DefaultWsdlHelpGenerator.aspx
bin/GodotSharp/Mono/etc/mono/2.0/machine.config
bin/GodotSharp/Mono/etc/mono/2.0/settings.map
bin/GodotSharp/Mono/etc/mono/2.0/web.config
bin/GodotSharp/Mono/etc/mono/4.0
bin/GodotSharp/Mono/etc/mono/4.0/Browsers
bin/GodotSharp/Mono/etc/mono/4.0/Browsers/Compat.browser
bin/GodotSharp/Mono/etc/mono/4.0/DefaultWsdlHelpGenerator.aspx
bin/GodotSharp/Mono/etc/mono/4.0/machine.config
bin/GodotSharp/Mono/etc/mono/4.0/settings.map
bin/GodotSharp/Mono/etc/mono/4.0/web.config
bin/GodotSharp/Mono/etc/mono/4.5
bin/GodotSharp/Mono/etc/mono/4.5/Browsers
bin/GodotSharp/Mono/etc/mono/4.5/Browsers/Compat.browser
bin/GodotSharp/Mono/etc/mono/4.5/DefaultWsdlHelpGenerator.aspx
bin/GodotSharp/Mono/etc/mono/4.5/machine.config
bin/GodotSharp/Mono/etc/mono/4.5/settings.map
bin/GodotSharp/Mono/etc/mono/4.5/web.config
bin/GodotSharp/Mono/etc/mono/browscap.ini
bin/GodotSharp/Mono/etc/mono/config
bin/GodotSharp/Mono/etc/mono/mconfig
bin/GodotSharp/Mono/etc/mono/mconfig/config.xml
bin/GodotSharp/Mono/lib
bin/GodotSharp/Mono/lib/mono
bin/GodotSharp/Mono/lib/mono/4.5
bin/GodotSharp/Mono/lib/mono/4.5/Facades
bin/GodotSharp/Tools
bin/GodotSharp/Tools/DotNet.Glob.dll
bin/GodotSharp/Tools/GodotTools.BuildLogger.dll
bin/GodotSharp/Tools/GodotTools.Core.dll
bin/GodotSharp/Tools/GodotTools.dll
bin/GodotSharp/Tools/GodotTools.IdeConnection.dll
bin/GodotSharp/Tools/GodotTools.ProjectEditor.dll
bin/GodotSharp/Tools/Newtonsoft.Json.dll


```

Attached are some windows and linux build logs, and a diff between linux and windows2. Not much there.
[mono-linux.log](https://github.com/godotengine/godot/files/4337931/mono-linux.log)
[mono-windows.log](https://github.com/godotengine/godot/files/4337932/mono-windows.log)
[mono-windows2.log](https://github.com/godotengine/godot/files/4337929/mono-windows2.log)
[mono-diff.txt](https://github.com/godotengine/godot/files/4337928/mono-diff.txt)

**Comment by neikeq** [comment] 2020-03-16 14:46
Did you build mono from source? Can you find `/root/dependencies/mono-64/lib/mono/4.5/mscorlib.dll`?

**Comment by LinuxUserGD** [comment] 2020-03-16 16:32
I just have `lldb/mono.py` in the `~/lib/mono` directory using mono 6.13.0

**Comment by LinuxUserGD** [comment] 2020-03-16 16:33
So I need to symlink those?

**Comment by neikeq** [comment] 2020-03-16 19:49
You need to build the Base Class Library for Windows as well. It must be for the same version as the runtime you built.

**Comment by tinmanjuggernaut** [comment] 2020-03-17 11:34
I see ok. The official docker scripts still aren't right.

**Ubuntu-64 docker** - builds mono from source, then also downloads some msbuild, nuget, etc deb packages. Then mono gets a 'make install' which presumably gets merged into /usr/lib. The library is found in `/usr/lib/mono/4.5/mscorlib.dll`. When Godot is built, no mono_prefix is necessary. 

**Windows** - There is no mscorlib.dll anywhere under `/root/dependencies/mono-*`. In the mono source tree, there is a `mono-6.6.0.166/external/binary-reference-assemblies/v4.5/mscorlib.dll`.

Mono is built from source. The msbuild, nuget, etc rpms are installed (in godot-mono docker) and so in the windows docker mscorlib.dll is under `/usr/lib/mono/4.5`, just like ubuntu. However this docker includes `MONO64_PREFIX=/root/dependencies/mono-64` and my build command needs `mono_prefix=/root/dependencies/mono-64`, as apparently the former environment commands are ignored (with a deprecated warning) and without them it errors out because it can't find the mono install directory.

If I preface my scons command with `cd /root/dependencies/mono-64/lib/mono/; for i in /usr/lib/mono/* ; do ln -s $i ; done` then scons will build with a full GodotSharp directory.

Since I have an open PR on the windows docker, I can change it now. What is the preferred solution for it?

* symlink `/usr/lib/mono/*` into `/root/dependencies/mono-{64,32}/lib/mono/`
* make install into /usr instead of /root/dependencies? - Can 32 and 64 bit coexist?

I will also remove the deprecated MONO(32|64)_PREFIX environment variables.

Also shouldn't the Godot engine build scripts error out, or at least issue a warning if mscorlib.dll, et al can't be found or copied? I won't make that change as I'm not familiar with those files.

**Comment by akien-mga** [comment] 2020-03-17 11:51
The official Windows containers have the BCL, so if yours don't, it's a problem either from your changes, from using docker instead of podman possibly (didn't try docker), or something else.
```
$ podman run -it localhost/godot-windows:master-mono-6.6.0.161
[root@c487fed95813 ~]# ls /root/dependencies/mono-64/
bin  etc  include  lib  share
[root@c487fed95813 ~]# ls -l /root/dependencies/mono-64/lib/mono/4.5/mscorlib.dll
-rwxr-xr-x. 1 root root 4642304 Jan 21 19:49 /root/dependencies/mono-64/lib/mono/4.5/mscorlib.dll
```

**Comment by tinmanjuggernaut** [comment] 2020-03-17 12:04
Hmm, the current offiical windows container [doesn't build](https://github.com/godotengine/build-containers/issues/37), at least not with mono-6.6.0.166, which is what started me on that PR. I guess I can rebuild again with build-containers/master and mono-6.6.0.161 and see what that does.

**Comment by akien-mga** [comment] 2020-03-17 12:32
I'm currently doing a build with `./build.sh 3.2 mono-6.6.0.166`, we'll see if I can reproduce your issue. Building the Windows container now.

**Comment by akien-mga** [comment] 2020-03-17 12:50
My Windows build was successful and it does include all libraries in `/root/dependencies/mono-64/lib/`, so I'm puzzled as to why your container differs.

**Comment by LinuxUserGD** [comment] 2020-03-17 13:06
Compiling worked fine with `./autogen.sh --prefix=/root/dependencies/mono-64 --host=x86_64-w64-mingw32 --disable-boehm --with-mcs-docs=no HOST_PROFILE=win32 --disable-mcs-build` but when enabling mcs compilation fails (using mono master without podman).
So I still only have lldb in `/root/dependencies/mono-64/lib/mono`

**Comment by akien-mga** [comment] 2020-03-17 13:10
@LinuxUserGD Cross-compiling Mono for Windows from Linux is quite complex and requires hacks to work. Unless you use https://github.com/godotengine/build-containers which is the solution we use for official builds, we likely won't be able to recommend/support cross-compiling until upstream Mono fixes their buildsystem.

**Comment by tinmanjuggernaut** [comment] 2020-03-17 13:24
I ultimately gave up on cross-compiling locally, as even when I got it to build, with files in GodotSharp, the executable wouldn't run in windows. It was only until I built the containers back in November that I got a mono executable that ran (non-mono was fine). However, now rebuilding the containers I'm having trouble as noted.

**Comment by LinuxUserGD** [comment] 2020-04-27 14:31
Seems to be fixed now as it's possible again to use latest shared non-static wine downloaded for windows without compiling it.

**Closed** 2020-04-27 14:31 UTC
Labels: bug, platform:linuxbsd, topic:buildsystem, topic:mono
