### ISSUE TITLE
Vulkan: GPUParticles2D are offset when using global coordinates (Local Coords disabled)

### ISSUE THREAD

**Issue by gokiburikin** [godotengine/godot#56892] opened 2022-01-18 07:19 UTC
### Godot version

v4.0.dev.calinou [e885de050]

### System information

Windows 10, Vulkan, GTX970

### Issue description

When using global coordinates with GPUParticles2D the particles are spawned at what looks like global_position * 2. Seems like a Transform is being applied twice. Expected behaviour (correct in 3.X) is that they should spawn at the same position as local coordinates but not be further affected by the node's position after spawning.

This occurs as far back as v4.0.dev.20211108.official [596865366].

https://user-images.githubusercontent.com/3820082/149888707-1fefc05d-d101-4660-80bf-f801574b5a35.mp4

### Steps to reproduce

Create a new project, create a new scene, add a GPUParticle2D node, give it a default Particles process material, disable Local Coords and move the node around.

### Minimal reproduction project

[global-particles-mrp.zip](https://github.com/godotengine/godot/files/7886949/global-particles-mrp.zip)

**Comment by floppyhammer** [comment] 2022-01-20 07:41
What caused this might be that particles are drawn in the node's local coordinates using global transform data. As I observe, the transform data coming out of the compute pass are already in global coordinates before being copied to the instance buffer.

**Comment by h0lley** [comment] 2022-03-04 00:27
mentioning `local_coords` property name in here so the issue is find-able

**Comment by floppyhammer** [comment] 2022-06-07 05:06
Could be closed by https://github.com/godotengine/godot/pull/57538.

**Comment by clayjohn** [comment] 2022-06-07 17:28
Closed by https://github.com/godotengine/godot/pull/57538

**Closed by clayjohn** 2022-06-07 17:28 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:2d
