### ISSUE TITLE
Language view

### ISSUE THREAD

**Issue by obedabit** [godotengine/godot#34793] opened 2020-01-03 20:59 UTC
**Godot version:**
v3.1.1 stable
**OS/device including version:**
Windows 10 1903 build
**Issue description:**
I have a viewing language issue when I chose the Arabic language in the program the letter language view separated from each other witch is wrong in the Arabic language the letter should be connected like this (الاسم) not like in the photo.

![ArabicLanguageIssue](https://user-images.githubusercontent.com/54214435/71748207-7f9b6680-2e7a-11ea-97b5-2be639564f2f.png)

**Comment by groud** [comment] 2020-01-03 21:42
Closing as a duplicate of #982

Godot does not support right-to-left languages correctly yet.

**Closed by groud** 2020-01-03 21:42 UTC
