### ISSUE TITLE
[2.1.5] PacketPeerStream.get_var() generates Errors.

### ISSUE THREAD

**Issue by rcurtis** [godotengine/godot#20807] opened 2018-08-08 14:27 UTC
**Godot version:**
2.1.5

**OS/device including version:**
Win7

**Issue description:**
On upgrading from 2.1.4 to 2.1.5 reading TCP packets with PacketPeerStream.get_var() puts the following error in the 'Errors' tab in the Godot editor: 

`"Condition ' strlen < 0 || strlen + pad > len ' is true. returned: ERR_FILE_EOF"`

get_var() returns null and the PacketPeerStream.get_available_packet_count() is never decremented and always remains the same number of available packets.

**Steps to reproduce:**
This is happening in quite a large project that relies on a large infrastructure of remote servers.  I'll try to put together something that can reproduce later.

**Comment by rcurtis** [comment] 2018-08-08 14:37
Relevant output from the Godot console: 
![wtfgodot](https://user-images.githubusercontent.com/1637426/43844038-d66b8404-9af6-11e8-8a8d-fcaed13212a3.png)

... It looks like there is some weird threading happening in the logging or its logging some strange char set.

**Comment by rcurtis** [comment] 2018-08-08 15:56
For reference, this is the tutorial I was using to assemble Godot readable TCP packets: https://github.com/stisa/godot-tcp-example/blob/master/node/server.js

I imagine this format has changed in some way.

This is the data layout I was using previously:

```
// The size of the buffer is:
// 4 bytes for the length of the packet +
// 4 bytes for the type +
// 4 bytes for the length of the string +
// the length of the string, rounded up to the nearest multiple of 4
var response = new Buffer(4+4+4+dataLength)
response.writeUIntLE(4+4+dataLength,0,4) // Write the length of the remaining packet
response.writeUIntLE(0x00000004,4,4) // Write the type, 4 is for strings
response.writeUIntLE(Buffer.byteLength(data),8,4) // Write the length of the string (in bytes)
response.write(data,12) // Write the actual string
```

**Comment by rcurtis** [comment] 2018-08-08 19:54
I commented out the check in marshals::_decode_string()
`ERR_FAIL_COND_V(strlen < 0 || strlen + pad > len, ERR_FILE_EOF);`

Oddly, if I put a break point on PacketPeerStream::get_packet() and manually step through the function it works fine.  But if I let it run at full speed I get a ton of 
`ERROR: PacketPeerStream:get_packet: Condition 'remaining < 4 ' is true. returned: ERR_UNAVAILABLE`

**Comment by akien-mga** [comment] 2018-08-15 18:31
CC @Faless

**Comment by Faless** [comment] 2018-08-16 00:07
From a brief look at the server code I would say it's missing the string
padding.
Basically, every string must be aligned to the nearest word (ie. the number
of bytes must be divisible by 4).
The previous code (2.1.4) wasn't checking the size correctly (possibility
causing crashes and/or memory content leakage), that has been fixed in
2.1.5 and thus, if your custom server code doesn't add the padding to the
string correctly it will be discarded by Godot.

**Comment by Faless** [comment] 2018-08-16 20:46
As a follow up, I tested the [linked code](https://github.com/stisa/godot-tcp-example/blob/master/node/server.js) (which does add the padding) with Godot 2.1.5 (on Linux) and it worked.

@rcurtis isn't that code working for you? Did you make any modification the linked code?

**Comment by rcurtis** [comment] 2018-08-17 13:19
@Faless I'll get back to you on this issue when I'm able to switch back.

**Comment by rcurtis** [comment] 2018-08-17 13:25
@Faless Padding the outgoing buffer to the nearest word did fix this issue.  Thanks for the quick response.

**Comment by Faless** [comment] 2018-08-17 13:39
> Padding the outgoing buffer to the nearest word did fix this issue.

Awesome, closing the issue as it works as intended.

**Closed by Faless** 2018-08-17 13:39 UTC
Labels: bug, topic:network
