### ISSUE TITLE
Issues with marquee selection in the 3d viewport

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#9145] opened 2017-06-13 07:29 UTC
**Operating system or device - Godot version:**

Godot 3.0 Win10 and Linux Mint

**Issue description:**
Some node types cannot be marquee selected in the 3d viewport. This included MeshInstance and MeshInstance as a child of a Spatial node. Neither a single object or multiple objects of these types can be selected in this manner.

If a MeshInstance is made a child of a Position3d node it can be marquee selected in the viewport.

Of those nodes that cannot be marquee selected, they can all be selected with a single click in the viewport, except for an instanced scene with a Spatial node as the root.

An instanced scene containing meshes under a spatial node cannot be selected in any manner in the viewport. However an instanced scene with meshes under a Position3d node can be selected via marquee or single click.

**Included scene:**

![selection_test](https://user-images.githubusercontent.com/7741669/27070671-5a9f0560-505d-11e7-860f-4a1dfcf6ef89.jpeg)

This project contains most of the selection anomalies that I have come across.

[selection_test.tar.gz](https://github.com/godotengine/godot/files/1070624/selection_test.tar.gz)

**Comment by nunodonato** [comment] 2017-06-13 08:03
related with #2852 ?

**Comment by brenttaylor** [comment] 2017-07-24 02:48
@nunodonato Yes, absolutely related.

**Comment by tagcup** [comment] 2017-08-23 17:50
After #10209, this issue still partially persists.

Example: I have a group-of-trees scene which is made of a couple of trees (tree has it's own scene, of course), and when I instance the group-of-trees, I can't select any of those trees.

Also see [this post](https://github.com/godotengine/godot/pull/10209#issuecomment-321964786) which reports a zoom-dependent behavior.

**Comment by kubecz3k** [comment] 2018-04-04 15:49
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by SneakyMax** [comment] 2018-08-21 03:51
Still appears to be happening for me in `v3.1.dev.calinou.8bc9986`

**Comment by akien-mga** [comment] 2018-09-17 09:41
CC @JFonS

**Comment by JFonS** [comment] 2018-09-17 10:01
@creeperdeking It should be fixed by 8804eb8, so a more up to date build will probably work fine for you.

**Comment by JFonS** [comment] 2018-09-18 11:08
I would close this issue, if the problem is still present on current master it can be reopened.

**Closed** 2018-09-18 11:38 UTC
Labels: bug, topic:editor, usability
