### ISSUE TITLE
Odd sized textures don't fit their handles in the 2D viewport (GLES 2)

### ISSUE THREAD

**Issue by ilyafuu** [godotengine/godot#26752] opened 2019-03-07 13:45 UTC
**Godot version:**
v3.1.rc.custom_build. 69761816381f11536980441265345ba055ad1c26

**OS/device including version:**
debian 9.8

**Issue description:**
NewNode >Sprite>Texture>New.... screenshot

![2019-03-07_16-27](https://user-images.githubusercontent.com/17591539/53960667-eb486200-40f7-11e9-9c30-ab7fe0ad109a.png)
![2019-03-07_16-32](https://user-images.githubusercontent.com/17591539/53960676-eedbe900-40f7-11e9-8dd0-df246cbbdb4b.png)
![2019-03-07_16-33](https://user-images.githubusercontent.com/17591539/53960681-f1d6d980-40f7-11e9-9fac-771346fb6858.png)
![2019-03-07_16-33_1](https://user-images.githubusercontent.com/17591539/53960696-01562280-40f8-11e9-9354-28ebaae58966.png)
![2019-03-07_16-34](https://user-images.githubusercontent.com/17591539/53960707-09ae5d80-40f8-11e9-9950-17b6d1c6ac3a.png)
![2019-03-07_16-34_1](https://user-images.githubusercontent.com/17591539/53960714-0d41e480-40f8-11e9-8144-413ed533ef00.png)
![2019-03-07_16-35](https://user-images.githubusercontent.com/17591539/53960720-0f0ba800-40f8-11e9-8e5b-2ef5d39648b0.png)
![2019-03-07_16-36](https://user-images.githubusercontent.com/17591539/53960721-103cd500-40f8-11e9-88c1-e1682b90e62d.png)
![2019-03-07_16-37](https://user-images.githubusercontent.com/17591539/53960723-116e0200-40f8-11e9-8269-567d22aa7104.png)

Error: Graditnt Texture

>  drivers/gles2/rasterizer_storage_gles2.cpp:727 - Condition ' !texture->active ' is true. returned: Ref<Image>()

**Comment by akien-mga** [comment] 2019-03-07 13:50
Is this a recent bug?

**Comment by ilyafuu** [comment] 2019-03-07 14:10
yeah

**Comment by akien-mga** [comment] 2019-03-07 16:54
The problem is only with CurveTexture and GradientTexture which are 1px high. The rest only happens because you upscaled the original Sprite on Y (to e.g. scale 100 or so), so all subsequent texture types that you put on that same sprite were upscaled.

**Comment by groud** [comment] 2019-03-07 17:20
Note that the same happens for all textures with odd dimensions.

**Comment by akien-mga** [comment] 2019-03-07 17:30
It's not a recent regression at all though, the same happens in 3.0.6 and 3.1 beta 1. So moving to next milestone.

**Closed** 2019-03-07 21:41 UTC
Labels: bug, topic:editor, topic:rendering
