### ISSUE TITLE
Running a C# project in 32 bit godot beta8 & 9 causes a crash

### ISSUE THREAD

**Issue by NikodemL** [godotengine/godot#26433] opened 2019-03-01 09:09 UTC
**Godot version:**
Godot_v3.1-beta9_mono_win32
Godot_v3.1-beta8_mono_win32

**OS/device including version:**
Windows 8.1 Enterprise

**Issue description:**
Godot crashes when you play the scene

**Steps to reproduce:**
Create a new project,
Create a new scene with 1 node,
Add c# script to the node.
Play scene
Godot crashes

**Comment by akien-mga** [comment] 2019-03-01 09:16
I assume you have a 64-bit system? If so it's a duplicate of #17299.

**Closed by akien-mga** 2019-03-01 09:16 UTC
