### ISSUE TITLE
Array inspector editor with fixed resource type aka: "TYPE_RESOURCE_ARRAY"

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#24118] opened 2018-12-02 18:01 UTC
**Godot version:**
N/A

**OS/device including version:**
N/A

**Issue description:**
Wanted to raise a discussion regarding the implementation of a way to allow for a
"TYPE_RESOURCE_ARRAY" type, it could use the default type one TYPE_ARRAY in conjunction with,
PROPERTY_HINT_RESOURCE_TYPE and using hint_string in the future could allow to point to a specific class_name and resource type. But I can't get my head around what changes should be done..
Is it better to introduce a POOL_RESOURCE_ARRAY variant (messing with the core), or maybe just stay with the built-in TYPE_ARRAY+PROPERTY_HINT_RESOURCE_TYPE combo.. but then the problem is I have to store within the array the item type and if hint == PROPERTY_HINT_RESOURCE_TYPE then disable type_change and automatically create instance when changing size.
Am I thinking right?! What would be a cleaner proper approach to this?!

@reduz, @vnen

**Comment by girng** [comment] 2018-12-02 19:58
you can try to utilize  setget and use the array index that points to a object in the script, to get the value. then you can take advantage of any resource type

**Comment by bojidar-bg** [comment] 2018-12-14 12:54
Isn't this a duplicate of #3586, implemented by #6930, and fixed by #24129?

**Comment by akien-mga** [comment] 2018-12-14 13:09
Indeed. Please fill the Godot version when reporting issues too, "N/A" is not true in a feature request which may be implemented in one version and not in another.

**Closed by akien-mga** 2018-12-14 13:09 UTC
Labels: discussion, topic:editor
