### ISSUE TITLE
Second screen infinite loading

### ISSUE THREAD

**Issue by Mikadini** [godotengine/godot#41908] opened 2020-09-09 13:40 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Gtx 1080 nvidia drivers 452.06

**Issue description:**
If I try to start the main scene while the godot instance is in the secondary screen (which is a 4k screen and is not set as the main screen on windows) the scene loads indefinitely and remains blank (I attach screenshot) .

I have tried changing the primary display and it only ever works in the primary monitor regardless of which one it is
![Screenshot](https://user-images.githubusercontent.com/44696452/92605999-b865c800-f2b2-11ea-9ee6-95aa0ac22b34.png)

**Steps to reproduce:**
Play godot in a non primary screen

**Minimal reproduction project:**
[Corso FPS.zip](https://github.com/godotengine/godot/files/5195521/Corso.FPS.zip)

**Comment by Calinou** [comment] 2020-09-09 13:48
Duplicate of #41907.

**Closed by Calinou** 2020-09-09 13:48 UTC
