### ISSUE TITLE
Calling _Input in mono c# godot will increase object count.

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#41553] opened 2020-08-27 01:12 UTC
**Godot version:**

mono 3.2.2 / mono 3.2.3 rc4

**OS/device including version:**

windows 10

**Issue description:**

The `Monitor.ObjectCount` will increase at each `_Input` calling. Using gdscript won't cause the issue. 

**Steps to reproduce:**
1. Create a new project.
2. Add a scene.
3. Attach a C# script.
4. Override the `_Input` function with no codes inside.
5. Print `Monitor.ObjectCount` at `_Process`.

**Minimal reproduction project:**

[ObjectCountIssue.zip](https://github.com/godotengine/godot/files/5133407/ObjectCountIssue.zip)
The project file is created in 3.2.3 rc4

**Comment by bojidar-bg** [comment] 2020-08-27 07:15
Likely duplicate of #41543 (would happily reopen if not the case).

**Closed by bojidar-bg** 2020-08-27 07:15 UTC
