### ISSUE TITLE
Import plugins not working properly in 3.4-beta5

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#53032] opened 2021-09-24 19:49 UTC
### Godot version

v3.4.beta5.official.dd0ee4872

### System information

Linux,Pop!_OS 21.04,5.11.0-7620-generic,GLES3,NVIDIA GeForce GTX 1070 with Max-Q Design/PCIe/SSE2,

### Issue description

When starting the editor with an import plugin it will not automatically import the resources associated with the plugin.

Re-enabling the plugin causes it to properly import the resources.

I noticed the [editor_plugins] section fo the project.godot file works differently now, but even after updating it the plugin still doesn't import resources on startup.

https://streamable.com/97jol3

### Steps to reproduce

```bash
# clone and initialize the govox example project:
git clone https://github.com/jamie-pate/govox.git
cd govox
git submodule init
git submodule update MagicaVoxel-Importer
./deploy-git-hooks.sh
# run the godot editor
~/bin/Godot_v3.4-beta5_x11.64  -e
```
It should import all the `.vox` files but doesn't...

Disabling and Re-enabling the plugin in the editor forces it to import the resources.

**Comment by Calinou** [comment] 2021-09-24 19:54
Duplicate of https://github.com/godotengine/godot/issues/52968.

**Closed by Calinou** 2021-09-24 19:54 UTC
