### ISSUE TITLE
Weird shadows on Quad/Plane/Sprite3D with billboarding enabled

### ISSUE THREAD

**Issue by maksutheam** [godotengine/godot#69026] opened 2022-11-22 20:48 UTC
### Godot version

4.0.beta5.official

### System information

Pop!_OS 22.04 LTS x86_64, NVIDIA GeForce GTX 1060 6GB, Vulkan

### Issue description

These weird shadows appear across Sprite3D and quad & plane MeshInstances when they have a material with billboarding enabled.

![kuva](https://user-images.githubusercontent.com/60304828/203413192-2843618e-305f-4980-a600-52db839423ae.png)

### Steps to reproduce

1. Add a quad/plane MeshInstance node or a Sprite3D node to the scene
2. Add a new StandardMaterial3D or ORMMaterial3D to the mesh or material override. If using Sprite3D, also add a texture to the texture field, such as icon.svg.
3. Enable 'Billboard' on the material

### Minimal reproduction project

[4.0 Billboard Bug.zip](https://github.com/godotengine/godot/files/10070905/4.0.Billboard.Bug.zip)

**Comment by Calinou** [comment] 2022-11-23 01:06
As a workaround, you can probably set the **Cast Shadow** property on the Sprite3D node's GeometryInstance3D section to **Off**.

**Comment by clayjohn** [comment] 2022-11-23 02:26
It looks like the shadow is not updating even though the object is moving. We probably need to check the vertex shader when deciding whether or not to update shadow maps. Right now we mostly just check if the object moves or if the object is animated (including vertex shader animation)

**Comment by clayjohn** [comment] 2022-11-23 02:40
Actually this is a duplicate of https://github.com/godotengine/godot/issues/41420

I will leave this open to track the issue in 4.0 separate from 3.x as the solution will be different for each.

**Closed** 2024-02-13 10:27 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
