### ISSUE TITLE
C# GD.Randf() breaks HTML build 

### ISSUE THREAD

**Issue by VoidGoat** [godotengine/godot#44923] opened 2021-01-04 23:03 UTC
**Godot version:**

v3.2.2.stable.mono

**OS/device including version:**

macOS 10.15.4 exporting to HTML

**Issue description:**

Using GD.Randf in a C# script makes HTML build freeze on launch. Removing the script or the GD.Randf call fixes the problem.

**Steps to reproduce:**
Create a scene and add a script to a node with a script that calls `GD.Randf()` in the _Ready() function. Something like
`GD.Print(GD.Randf())` 
Then export the project to HTML. When the HTML project is run from a web server it starts to load but freezes. 

**Minimal reproduction project:**

[RandfMinReproduction.zip](https://github.com/godotengine/godot/files/5767154/RandfMinReproduction.zip)

**Comment by Calinou** [comment] 2021-01-05 01:00
Duplicate of #36858 (same cause), fixed by https://github.com/godotengine/godot/pull/44105.

**Closed** 2021-01-05 09:36 UTC
Labels: archived, bug, platform:html5, topic:mono
