### ISSUE TITLE
TileMap get_children() returns TileMap layers as nodes

### ISSUE THREAD

**Issue by Morfeuszz** [godotengine/godot#88362] opened 2024-02-15 14:04 UTC
### Tested versions

- Reproducible: v4.3.dev3.mono.official [36e943b6b]
- Not reproducible: v4.3.dev2.official [352434668]

### System information

Godot v4.3.dev3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3713) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Starting from v4.3.dev3 TileMap layers are returned alongside rest of child nodes when using GetChildren()

### Steps to reproduce

1. Open project and run main scene
2. Results are shown in console

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14297713/MRP.zip)

**Comment by AThousandShips** [comment] 2024-02-15 14:07
This is by design, though the question is if they should be internal or not

**Comment by Morfeuszz** [comment] 2024-02-15 14:24
Looking at the changelog again now i see it's there, I must have missed it, my bad.

I guess its internal in current dev version? I can't really reference its type at least in c#.

In my project i go through TileMap children and duplicate them, which now causes apparent error:
_Class 'TileMapLayer' or its base class cannot be instantiated._

Checking if each iterated node is not of this type would fix the issue for now but its not currently possible

**Comment by AThousandShips** [comment] 2024-02-15 14:26
The nodes are not internal children, but they are an internal non-exposed class

**Comment by groud** [comment] 2024-02-15 16:59
> This is by design, they were changed to nodes, though the question is if they should be internal or not

Yes, those should be internal for the TileMap node indeed. I might have forgotten about doing it explicitly ? I thought they would be marked as internal by default (in the editor code).

**Comment by AThousandShips** [comment] 2024-02-15 17:03
Not done:
https://github.com/godotengine/godot/blob/6f805dee2a0d9d23a8365de0331479c8846bf298/scene/2d/tile_map.cpp#L1005

But simple to do

**Comment by KoBeWi** [comment] 2024-02-15 20:23
They don't have `owner` so they don't show in the editor (and you can use that to skip them when accessing children). Internal children are a separate thing, which can be set when using `add_child()`.

**Closed** 2024-02-16 23:28 UTC
Labels: bug, discussion, topic:2d
