### ISSUE TITLE
Screen position & size of the "add node" popup dialog is not saved

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#78401] opened 2023-06-18 12:35 UTC
### Godot version

4.0.3

### System information

ubuntu 23.04

### Issue description

 - The position (and the size) of the add node (`Ctrl + A`) popup is reset on each node addition.
 - This is unlike e.g. the "instantiate child scene" popup (`Ctrl + Shift + A`).
 - This is bad because on my setup, the popup keeps showing up on my secondary monitor while the godot editor is on my main monitor.

### Steps to reproduce

- have two monitors
- `Ctrl + A`
- `Ctrl + Shift + A`
(notice how moving and resizing the "Instantiate Child Scene" window allows you to customize where it will next show up)

### Minimal reproduction project

an empty project.godot file

**Comment by AThousandShips** [comment] 2023-06-18 12:37
Cannot replicate on 4.x, it is saved correctly, with multiple monitors, but on Windows, so might be platform specific

**Comment by AThousandShips** [comment] 2023-06-18 12:41
* Duplicate of: #75084

But the fix there was not backported to 4.0.x, will open a dedicated fix for 4.0.x

**Comment by akien-mga** [comment] 2023-06-19 14:48
Fixed by #78403.

**Closed by akien-mga** 2023-06-19 14:48 UTC
Labels: bug, topic:editor, confirmed
