### ISSUE TITLE
Tilemap: Delete Erases Node, Not Tiles

### ISSUE THREAD

**Issue by Zakkumaru** [godotengine/godot#18637] opened 2018-05-05 16:10 UTC
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Xubuntu 16.04

**Issue description:**
In the tilemap editor, where you place tiles, selecting a bunch of tiles and then pressing the delete key will ask you if you want to delete the node, but the drop-down menu for the tile map clearly says that the delete key will delete the tiles selected

**Steps to reproduce:**

- Add a TileMap node
- Add tiles to the tilemap
- Select tiles using the tilemap selection tool
- Press delete key

**Minimal reproduction project:**
It's a generic engine issue, not related to my project itself

**Comment by homer666** [comment] 2018-05-06 05:01
Related to #16198

**Comment by bojidar-bg** [comment] 2018-06-03 13:36
Even more related to #16293.

**Comment by bojidar-bg** [comment] 2018-12-04 19:32
Closing as duplicate of #16293, as it is a shortcut:
![image](https://user-images.githubusercontent.com/5276727/49467831-fbf0ef80-f80b-11e8-88e9-0a27282e08d6.png)

**Closed by bojidar-bg** 2018-12-04 19:32 UTC
Labels: bug, topic:editor, usability
