### ISSUE TITLE
Sub-resource id changes for no reason

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33411] opened 2019-11-07 01:16 UTC
**Godot version:**
3.2 beta1

**Issue description:**
Could be another case of #30538, dunno (judging from https://github.com/godotengine/godot/issues/30538#issuecomment-548158299, it could be revived). I noticed that sometimes my resources still shuffle, even though it should be fixed. I just
found a test case that reproduces it 100%, so I think it's time to open an issue about it.

**Steps to reproduce:**
1. Open the reproduction project
2. Open "Nodes/UI/InGame/UI.tscn" scene
3. Open the same scene in some external text editor
4. Go to line 162. Notice the animation has id=16
5. Save the scene in Godot
6. Animation is now id=15

This always happens.

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3817403/ReproductionProject.zip)
(this is a dump of my game with irrelevant parts removed)

**Comment by chiguireitor** [comment] 2019-11-23 00:30
Have this issue too, today i compiled tools beta2, will keep an eye on this issue as it affects mergability of different branches of my project.

**Comment by KoBeWi** [comment] 2019-12-31 11:53
Not sure if related, but AnimatedSprite's animations can move around.
![image](https://user-images.githubusercontent.com/2223172/71620800-273f3d00-2bcc-11ea-9d21-f3ddf5d5bb06.png)

I'll add this issue to 3.2 milestone, because similar pointless changes happen A LOT (and the other similar issue had 3.2 too). While you can, heh, just discard these changes, there's always a risk of discarding your work and it's... _uncomfortable_.

**Comment by akien-mga** [comment] 2020-01-15 14:03
Duplicate of #22226.

**Closed by akien-mga** 2020-01-15 14:03 UTC
Labels: bug, topic:core
