### ISSUE TITLE
Materials set to "Transparent" have strange layering (ex: background on foreground)

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#21050] opened 2018-08-15 17:51 UTC
**Godot version:** 3.1-dev with Mono, including latest c627f3a707b9dc052e6665f1a5b1268862a90642 and others such as 80a8636aa3739822b1ebbbad39f932a176ec158d (I've been having this problem for awhile it's not new)

**OS/device including version:** Linux Xubuntu 18.04.1 64-bit, Mono 5.14

**Issue description:** For some reason, if I enable the "transparent" property of a texture, the background sometimes appears over the foreground. It's a really strange effect.

![trans1](https://user-images.githubusercontent.com/1646875/44163274-8c9e9680-a088-11e8-80bd-3222f76be9b3.png)

![trans2](https://user-images.githubusercontent.com/1646875/44163270-8a3c3c80-a088-11e8-9e53-5074f371dd59.png)

If I disable "Transparent", then the mesh renders correctly, however, anything with transparency in it (like if I wanted to make a glass block) appears white instead.

**Steps to reproduce:** Have a mesh with textures overlaying and enable the transparent property of the material. In my case I have a code-generated Mesh via SurfaceTool.

**Comment by fire** [comment] 2018-08-15 18:07
Did you try DEPTH_DRAW_ALPHA_OPAQUE_PREPASS ?

**Comment by CptPotato** [comment] 2018-08-17 11:08
Sounds like transparency sorting to me. (transparent objects are sorted back to front based on their origin). 

There is no perfect fix for this. Using 1 bit alpha (aloha testing, not sure what the name is in godot) is one way but you'll have to put up with sharp borders and aliasing.

**Comment by aaronfranke** [comment] 2019-11-04 06:51
So... an update on this issue. My brother and I recently updated our main project to Godot 3.2 alpha, and we can confirm that this issue is still present.

However, I will note that a) It can be worked around if we fiddle with it, and b) It doesn't ever occur on GLES 2, so it's possibly a GLES 3 specific issue. Since GLES 3 isn't being worked on anymore due to being removed in the future, I suggest bumping this to the 4.0 milestone.

![Untitled](https://user-images.githubusercontent.com/1646875/68103303-2f1c8280-fea4-11e9-8e3d-d8ab7178ff1f.png)

**Comment by clayjohn** [comment] 2019-11-05 00:01
Im not sure this should be an open issue. The solution is to use DEPTH_DRAW_ALPHA_OPAQUE_PREPASS

Otherwise it's just a limitation of 3d rendering. We aren't going to do a prepass on all transparent objects because it is expensive and usually unnecessary.

**Comment by tcoxon** [comment] 2020-01-29 18:08
I think this issue is back in 3.2.

[sprite3d-shadow-depth.zip](https://github.com/godotengine/godot/files/4129735/sprite3d-shadow-depth.zip)

In this reproducer I have two transparent Sprite3Ds set up with DEPTH_DRAW_ALPHA_OPAQUE_PREPASS. In the foreground is a blue one, set to not cast shadows, and in the background is a red one that does cast a shadow. The blue sprite is positioned to occlude the red sprite.

When you run the project in 3.2, you can see the red sprite through the blue sprite. You can also see this in the editor by lining up the camera. Strangely, it only does this for certain angles of directional light?

3.1.1 was unaffected.

I think this is related to #30764, the fix for #30673. It has a pretty major impact on my project.

**Comment by asheraryam** [comment] 2020-02-06 12:12
I can confirm this is happening on the latest 3.2 stable.

**Comment by clayjohn** [comment] 2020-06-26 19:51
@tcoxon Can you run it again in 3.2.2? I can't reproduce the issue.

**Comment by Calinou** [comment] 2020-11-01 13:59
This is a limitation shared by most real-time renderers: https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting

Using opaque pre-pass usually solves this, but there are known bugs like https://github.com/godotengine/godot/issues/43253. I'll close this issue in favor of other reports that are specifically about opaque pre-pass.

**Closed by Calinou** 2020-11-01 13:59 UTC
Labels: bug, confirmed, discussion, topic:rendering
