### ISSUE TITLE
move_and_slide returns (0, 0) vector when pushing another kinematic body in 2D

### ISSUE THREAD

**Issue by afable** [godotengine/godot#32012] opened 2019-09-06 14:16 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
When moving a KinematicBody2D (pusher) that programatically moves another KinematicBody2D (pushee), move_and_slide (of pusher) returns a (0, 0) vector even though its position is moving.

**Steps to reproduce:**
1. Create a KinematicBody2D for the pusher and add input movement.
2. Create a KinematicBody2D for the pushee and add a push function to move_and_slide itself when collided.
3. Print result velocity from pusher colliding with and moving pushee.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/3584302/bug.zip)

**Comment by pouleyKetchoupp** [comment] 2019-09-10 09:26
First, as an easy fix for your issue, did you try to use a `RigidBody2D` for the pushee instead of a `KinematicBody2D` so you don't have to detect the collision and push it by script?

It's going to be difficult to fix this issue without a hack because what's happening is the expected behavior. During the same frame, the pushee and the pusher are moved by the same velocity using `move_and_slide`. But their position in the internal physics simulation is not instantly updated, which causes the pusher to always detect a collision with the pushee during the same frame and return a velocity of 0,0.

**Comment by afable** [comment] 2019-09-10 15:22
> First, as an easy fix for your issue, did you try to use a `RigidBody2D` for the pushee instead of a `KinematicBody2D` so you don't have to detect the collision and push it by script?

Yes, I actually started with a `RigidBody2D` as the pushee but found that the pushee moves too freely. I'm creating a top-down RPG and wanted a very simple push mechanic where the pusher and pushee move at the same pace and only in cardinal directions (except when pushed diagonally from corners). I don't really need the physics engine in my game so I didn't want to over complicate things by configuring it and `RigidBody2D`s for a very simple push mechanic.

> It's going to be difficult to fix this issue without a hack because what's happening is the expected behavior. During the same frame, the pushee and the pusher are moved by the same velocity using `move_and_slide`. But their position in the internal physics simulation is not instantly updated, which causes the pusher to always detect a collision with the pushee during the same frame and return a velocity of 0,0.

I figured as much. The velocity of 0,0 (even though the pusher was moving position) did trip me up while I was debugging a completely separate issue that I was able to resolve.

I created a bug report for the 0,0 velocity since, without knowing the internal details of the engine, I assumed `KinematicBody2D`'s move_and_slide would always return a velocity if it moved position in a frame and I couldn't find any external indicators of why it was returning velocity 0,0. Feel free to do what you wish with this bug report if the engine is working as expected.

**Comment by pouleyKetchoupp** [comment] 2019-09-11 07:56
Thanks for sharing more details, it helps understanding what you're trying to achieve.

Can you try to set the pushee as a `RigidBody2D` again with these parameters?
`Mode: Character` (can't be rotated)
`Gravity Scale: 0` (not affected by gravity)
`Linear Damp: 128` (stops immediately when not pushed)

The result looks very similar to what you had and you'll get the correct velocity from `move_and_slide` for the pusher. Let me know what you think!

**Comment by afable** [comment] 2019-09-11 14:41
Yes, that does make make the pusher and pushee behave the same way, thank you.

Although, the setup I have now (with only `KinematicBody2D`s and `StaticBody2D`s) has it so that the pushee is prevented from moving through collisions with other `KinematicBody2D`s and `StaticBody2D`s. Is there a setting to prevent the pushee as a `RigidBody2D `from moving through collisions with other `RigidBody2D`s and `StaticBody2D`s while still being collided with by the pusher?

**Comment by Zireael07** [comment] 2019-09-11 14:58
@afable: Physics layers should do the trick, although I'm not sure where to look for them in 2D (I only used them in 3D)

**Comment by afable** [comment] 2019-09-11 15:52
> @afable: Physics layers should do the trick, although I'm not sure where to look for them in 2D (I only used them in 3D)

Thank you! Setting them all in the same collision layer and mask do help with `RigidBody2D`s colliding with other `RigidBody2D`s. Unfortunately, they still seem to move through `StaticBody2D`s and `KinematicBody2D`s.

I suspect I would have to programmatically detect collisions in pushees and turn off `KinematicBody2D`'s `move_and_slide`'s `infinite_inertia` flag when there are multiple collisions happening for one cardinal direction (but still allow another cardinal direction such as pushing a pushee diagonally against a wall). I don't want my pusher to be able to push objects into walls. 

My current setup with only `KinematicBody2D`s and `StaticBody2D`s behaves as desired although if I could make `RigidBody2D`s behave the same with simply configuring its settings I would go that route (I really dislike my Scene List having both my Player and pushable objects listed with the same `KinematicBody2D` icon).

**Comment by madmiraal** [comment] 2020-06-24 12:37
Closing, because `move_and_slide()` returning `Vector(0, 0)` is the expected behaviour when colliding perpendicularly with another `KinematicBody` or `StaticBody`.

**Closed by madmiraal** 2020-06-24 12:37 UTC
Labels: bug, topic:physics

**Comment by nklbdev** [comment] 2021-12-02 10:44
I figured out how to avoid zero-velocity when calling `move_and_slide` after the `KinematicBody2D` has been pushed by another `KinematicBody2D`!
Before you call `move_and_slide`, call `move_and_collide(Vector2.Zero)`. I don't know exactly how, but it works! Be careful, there may be side effects!
