### ISSUE TITLE
Explain what is required to make proper HTML5 export

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#4072] opened 2016-03-16 16:32 UTC
Continuation of:
https://github.com/godotengine/godot/issues/4000#issuecomment-197373433

To work on better **web export**, it is rather critical to see a picture that explains in sufficient technical detail how Godot components work together. Current HTML5 export is slow and "counter-productive", so is there a visualization that explains why?

Even if this is obvious, it will  help to design a better architecture for in Godot 4.0 or whatever. For example, it may be possible to provide architecture that may be able to export only a subset of games (such as various static menus and clickers).

**Comment by akien-mga** [comment] 2016-03-16 16:45
http://godotengine.org/article/webassembly-godot-web

**Comment by akien-mga** [comment] 2016-03-16 16:46
> Despite it being adopted by Unity and Unreal too, ASM.JS is still hit or miss. It requires a huge amount of resources to compile the Javascript blob, a large pre-allocated chunk of memory (to serve as process memory), and a relatively fast computer to run it. Forget about mobile web. This back-end is still in the works in Godot, but we were mainly waiting for browser vendors to make it not suck. This may never happen.

**Comment by akien-mga** [comment] 2016-03-16 16:52
Closing as duplicate of #2417. Also check the issues for the ``platform:html5`` tag: https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+label%3Aplatform%3Ahtml5

**Closed by akien-mga** 2016-03-16 16:52 UTC

**Comment by techtonik** [comment] 2016-03-16 16:59
@akien-mga the post you referred to doesn't have any technical details. It only lists various attempts to port Godot engine.

#2417 is about optimizing asm.js, while this issue is about documenting Godot architecture.
