### ISSUE TITLE
Broken new shader materials

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#72579] opened 2023-02-02 09:38 UTC
### Godot version

v4.0.beta16.official [28a24639c]

### System information

Mac

### Issue description

So until recently I've been on 4.beta.14 and everything was ok, but lately moving to Beta.16 I start to see shader material issues.

At first these were only on export.

## At first: 
I saved over the original shader material from the Editor.
After this the shader would function as in 4.14 when run from the editor, but not when run from an exported build.

## Later
I deleted the original shader material and created a new shader material
I then loaded my original shader into the new shader material.

Now the bug also exists in the Godot editor.

### Steps to reproduce

I run some shaders which read input data in a 1-Dimensional array (An image with dimensions akin to Vector2(2048x1))

I then use each pixel for timeseries analysis.

```glsl
shader_type canvas_item;

uniform bool FLIP;
uniform float HEIGHT = 0.8;
uniform vec4 COLOR_UP = vec4(0.32, 0.21, 0.59, 1.);
uniform vec4 COLOR_DW = vec4(0.18, 0.38, 0.80, 1.);

bool should_discard(vec4 candle, vec2 uv) {
  return abs(
             step(candle.b + HEIGHT, FLIP ? uv.y : 1.0 - uv.y) -
             step(candle.g - HEIGHT, FLIP ? uv.y : 1.0 - uv.y)) < 0.001;
}

void fragment() {
  vec4 candle = texture(TEXTURE, UV);

  if (should_discard(candle, UV)) {
    discard;
  }

  else if (candle.a > candle.r) {
    COLOR = COLOR_UP;
  }

  else {
    COLOR = COLOR_DW;
  }
}
```

The normal result of this (4.beta.14) is as follows

<img width="1552" alt="Screenshot 2023-02-02 at 16 31 18" src="https://user-images.githubusercontent.com/100964/216287255-d9fa70cf-e764-4d46-94be-49f3c50ee791.png">

The result from 4.beta.16 is as follows:

<img width="1552" alt="Screenshot 2023-02-02 at 16 32 18" src="https://user-images.githubusercontent.com/100964/216287470-e515aa81-6b06-44d0-925d-8a89b6b0b9d0.png">

The only other thing I can think of would be it is where I construct my images:

```gdscript
func from_colors(data: Array): # Array<Color>
	if len(data) < 1:
		push_warning("Color data is too small")
		return self.of_size(1)
	
	var size = len(data)

	var image = self.of_size(size)
	if image == null:
		return null

	var item
	for i in range(size):
		image.set_pixel(i, 0, data[i])

	return ImageTexture.create_from_image(image)
```

As I saw something else had recently changed there (Singleton `ImageTexture.create_from_image()` from instance before)

### Minimal reproduction project

See above

**Comment by tavurth** [comment] 2023-02-02 09:59
Hmm I tried to export in `4.beta.14` and with now the same result (`git reset --hard {hash}`)

Ideas as I see:

1. Godot is somehow caching the shaders in a user directory
2. Godot 4.x was always like this (I tested it was working fine on export before)

**Comment by tavurth** [comment] 2023-02-02 10:03
Exporting in Godot `4.beta.14` works without issue, both production and debug builds.

**Comment by Calinou** [comment] 2023-02-02 13:15
Your shader code is missing a closing parenthesis after `UV`:

```
  if (should_discard(candle, UV) {
    discard;
  }
```

**Comment by tavurth** [comment] 2023-02-02 13:29
> Your shader code is missing a closing parenthesis after `UV`:

Yep that's just a factor of my reduction to the minimum possible codebase here on Github.

Real code is around 5x larger 😅

**Comment by clayjohn** [comment] 2023-02-02 17:13
Duplicate of https://github.com/godotengine/godot/issues/72538

The underlying issue is that ShaderMaterials which haven't changed uniform settings are saving null instead of the actual uniform. The workaround is to set your uniforms to something other than default and they should save fine

**Closed by clayjohn** 2023-02-02 17:13 UTC
Labels: needs testing, topic:shaders
