### ISSUE TITLE
Godot closes if you resize a window

### ISSUE THREAD

**Issue by BigBugBang** [godotengine/godot#62577] opened 2022-06-30 23:11 UTC
### Godot version

3.5-rc5, 3.4.2 stable, 3.4.4 stable

### System information

Windows 10, NVidia 3080, driver 516.59

### Issue description

Godot closes if you resize a window

https://user-images.githubusercontent.com/108496359/176793163-87b283f9-e580-4da2-943e-ae3aa0cd3f2e.mp4

### Steps to reproduce

Just launch Godot and resize a window with the mouse

**Comment by Calinou** [comment] 2022-06-30 23:39
Duplicate of https://github.com/godotengine/godot/issues/24702.

**Closed by Calinou** 2022-06-30 23:39 UTC
