### ISSUE TITLE
Using System.Random will crash on iOS devices (not in the simulator)

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#40633] opened 2020-07-23 15:22 UTC
**Godot version:**
3.2.2 Mono

**OS/device including version:**
Tested on iOS 11/12/13 with various iPhones

**Issue description:**
App will crash when instantiating a new `System.Random` object. e.g. `var foo = new Random()`. **This only happens on real devices.** On the iOS simulator it does not crash.

I am unsure whether this is a problem with the way Godot is using Mono, a symptom of AoT (required for iOS), or a problem with the Mono implementation on iOS. Generating random numbers seems like a pretty common thing to want to do.

```
System.TypeInitializationException: The type initializer for 'System.Random' threw an exception.
at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) <0x1018f8378 + 0x00010> in :0
at System.Random.GenerateGlobalSeed () <0x1018f8248 + 0x00006> in :0
at System.Random..cctor () <0x1018f8098 + 0x00000> in :0
```

I'm resonably confident it's crashing when GetRandomBytes calls `Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)` internally (which is native, and not showing on the call stack).

**Steps to reproduce:**
1. Init a new System.Random object - e.g. `var foo = new Random();`

**Minimal reproduction project:**
[MonoRandomIOS.zip](https://github.com/godotengine/godot/files/4967065/MonoRandomIOS.zip)

**Comment by neikeq** [comment] 2020-07-31 18:39
Judging by the exception message I'm closing this as duplicate of #38810.

**Closed by neikeq** 2020-07-31 18:39 UTC
Labels: bug, crash, platform:ios, topic:mono
