### ISSUE TITLE
Broken documentation rendering on initial startup

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#65056] opened 2022-08-29 20:52 UTC
### Godot version

58f8f3a40e8b068b9f7b92cae21e0cabb406dd07

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

In-editor documentation rendering is completely messed up:
![Screenshot from 2022-08-29 22-40-53](https://user-images.githubusercontent.com/347965/187295561-79895697-d963-46b6-9944-2422586b4137.png)

My editor theme is set to the default preset. Changing it to another preset (and back to default) resolves the issue (edit: but only for the current page).

I've had this for a couple of days, not sure if it's been reported already, I couldn't find anything.

### Steps to reproduce

1. Ctrl-click on a built-in class/function

**Comment by clayjohn** [comment] 2022-08-29 22:22
Duplicate of: https://github.com/godotengine/godot/issues/64997

Fixed by: https://github.com/godotengine/godot/pull/65025

If you pull from master again and rebuild you should be good to go

**Closed by clayjohn** 2022-08-29 22:22 UTC
