### ISSUE TITLE
Godot4.2 does not have WebSocketServer and WebSocketClient class

### ISSUE THREAD

**Issue by ProgrammerMao** [godotengine/godot#94561] opened 2024-07-20 15:11 UTC
### Tested versions

Godot_v4.2.2-stable_win64

### System information

Win11

### Issue description

https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html
In the document, `Minimal client example` and `Minimal server example` have `WebSocketServer` and `WebSocketClient` class, but in the `Godot4.2.2`, not found they classes, That also happned in `Godot4.1.2`, but I don't know when begin.
I found in the `godot-demo-projects`, `networking/websocket_chat/websocket` have two files,`WebSocketClient.gd` and `WebSocketClient.gd`, may compliant with document

### Steps to reproduce

None

### Minimal reproduction project (MRP)

None

**Comment by AThousandShips** [comment] 2024-07-20 15:16
If you look at the top of the page it says it is outdated, please refer to the [4.3 version](https://docs.godotengine.org/en/latest/tutorials/networking/websocket.html) which has been updated

Closing as a duplicate of:
* https://github.com/godotengine/godot-docs/issues/6631

**Closed by AThousandShips** 2024-07-20 15:16 UTC
