### ISSUE TITLE
Changing the `default_font_size` on multiple Buttons causes `get_children()` to return null

### ISSUE THREAD

**Issue by dustingarner** [godotengine/godot#83592] opened 2023-10-19 00:59 UTC
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - macOS 13.5.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

Upon creating a scene that has multiple `Button` nodes as children, get_children() on the parent returns null if the Buttons share a Theme that has a `default_font_size` of >=38.

### Steps to reproduce

- Create a new scene with a `Node` as the parent.
- Add a `Button` node as a child.
- Write any text as the `text` of the `Button`.
- Click on the `Theme` section of the Inspector and add a `New Theme`.
- Add any `default_font` for the `Theme`.
- Set the `default_font_size` to 38 or higher.
- Duplicate the `Button` in the Scene Tree.
- Add a script and run `get_children()` on the parent `Node`. It returns `null`.

### Minimal reproduction project

[Theme Bug.zip](https://github.com/godotengine/godot/files/13035363/Theme.Bug.zip)

**Comment by kleonc** [comment] 2023-10-19 12:07
Seems to be a debugger-only bug, it only shows as null when debugging:
![Godot_v4 1 2-stable_win64_JgJQuEHWkc](https://github.com/godotengine/godot/assets/9283098/abfe5e49-a5d6-45f3-ab78-250ad4d368bc)

Can reproduce in
- v4.1.2.stable.official [399c9dc39],
- v4.2.dev1.official [0c2144da9].

Seems fixed in:
- v4.2.dev3.official [013e8e3af],
- v4.2.beta1.official [b1371806a].

(v4.2.dev2.official [da81ca62a] just crashed for me. :upside_down_face:)

Closing as already fixed, not sure by what exactly though (so in case getting it fixed in 4.1 is wanted someone would need to dig some further).

**Closed by kleonc** 2023-10-19 12:07 UTC
Labels: bug, needs testing, topic:gui
