### ISSUE TITLE
Particles2D not displayed

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#23662] opened 2018-11-12 07:05 UTC
**Godot version:**
3.1 d16ce4a8e

**OS/device including version:**
Windows 10

**Issue description:**
Particles2D in existing project not displayed at all. Particles2D added after loading the project are one-pixel in size.

**Steps to reproduce:**
Load existing project with Particles2D.

**Minimal reproduction project:**
[Github repo](https://github.com/lekoder/godot-issue-paralax-particles)

**Comment by JFonS** [comment] 2018-11-12 07:55
See #23647

**Comment by akien-mga** [comment] 2018-11-12 08:02
Duplicate of #23647 indeed.

**Closed by akien-mga** 2018-11-12 08:02 UTC
