### ISSUE TITLE
MacOS: AnimationTreePlayer nodes have overlapping UI elements

### ISSUE THREAD

**Issue by paulcosmos** [godotengine/godot#26117] opened 2019-02-21 11:59 UTC
**Godot version:**

3.0.6 stable

**OS/device including version:**

MacBook Pro (Retina, 15-inch, Mid 2015)

**Issue description:**

The AnimationTree nodes have overlapping interface elements in the MacOS version of the editor. 

**Screenshots:**

Blend2:
![Blend2](https://user-images.githubusercontent.com/24660807/53166825-49405a00-35ce-11e9-8233-4e7528cee97d.png)

Blend3:
![Blend3](https://user-images.githubusercontent.com/24660807/53166826-49d8f080-35ce-11e9-8f6e-3084f4ac2c12.png)

Blend4:
![Blend4](https://user-images.githubusercontent.com/24660807/53166934-7c82e900-35ce-11e9-9ed5-1073ade8569b.png)

Mix:
![Mix](https://user-images.githubusercontent.com/24660807/53166827-49d8f080-35ce-11e9-8c6e-cff61129bd28.png)

Oneshot:
![Oneshot](https://user-images.githubusercontent.com/24660807/53166828-49d8f080-35ce-11e9-8cef-c8388e3cde68.png)

Output:
![Output](https://user-images.githubusercontent.com/24660807/53166829-4a718700-35ce-11e9-80b1-f9eaf288d7e4.png)

Timescale:
![Timescale](https://user-images.githubusercontent.com/24660807/53166830-4a718700-35ce-11e9-8667-d5279477fdd8.png)

Transition:
![Transition](https://user-images.githubusercontent.com/24660807/53166831-4a718700-35ce-11e9-8ebd-83cecce34b69.png)

**Comment by akien-mga** [comment] 2019-02-21 12:18
HiDPI fixes needed, cc @Calinou @bruvzg

**Comment by akien-mga** [comment] 2019-02-21 12:19
> 3.0.6 stable

> The AnimationTree nodes have overlapping interface elements in the MacOS version of the editor.

AnimationTree is a feature of Godot 3.1, do you mean AnimationTreePlayer? Or are you seeing this issue in 3.1 beta builds?

**Comment by paulcosmos** [comment] 2019-02-21 12:44
> AnimationTree is a feature of Godot 3.1, do you mean AnimationTreePlayer? Or are you seeing this issue in 3.1 beta builds?

Sorry, yes it was the AnimationTreePlayer node, but the interface panel at the bottom that displays the nodes is labeled as 'AnimationTree', hence the confusion. I've updated the title to reflect the node name. I haven't checked the beta builds, shall I?

**Comment by akien-mga** [comment] 2019-02-21 12:52
It would be interesting to check if the issue is reproducible in 3.1 beta 5 yeah. If it's not, the fix likely just needs to be backported.

**Comment by paulcosmos** [comment] 2019-02-21 13:10
Doesn't seem to be an issue in beta 5. As far as I can tell all UI elements are working as intended:
![macos-beta5-test](https://user-images.githubusercontent.com/24660807/53171208-fbc9ea00-35d9-11e9-83ba-fb815256a6fa.png)

**Comment by bruvzg** [comment] 2019-02-21 19:15
Node are ok in current master, but add node button spacing is not scaled correctly, ` * EDSCALE` is missing somewhere.

![screenshot 2019-02-21 at 20 38 22](https://user-images.githubusercontent.com/7645683/53193251-3acb6000-3619-11e9-9e2a-e8d9cbab1003.png)

**Comment by akien-mga** [comment] 2019-12-19 08:20
Closing as fixed in 3.1.

**Closed by akien-mga** 2019-12-19 08:20 UTC
Labels: bug, platform:osx, topic:editor, usability
