### ISSUE TITLE
[2D Editor] Snapping to bounding box interferes with snapped placement of sprites and polygons

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1177] opened 2015-01-11 02:16 UTC
Polygons always snap to the top-left corner of their padded AABB.
If you draw a polygon so that all its vertices are snapped to the grid then move it it is impossible to place it so that the vertices are snapped to the grid, unless the snap size perfectly matches the padding size.

Sprites always snap to the top-left corner of their AABB.
If a sprite size isn't a multiple of the snap size it is impossible to place it neatly on the grid.

I propose to snap the object origins rather than the AABB corner.
This way the snapping point of sprites may be adjusted by the offset.
This way polygons may be snapped and their snapped vertices remain on the grid.

**Comment by akien-mga** [comment] 2015-11-20 09:39
Closing as a duplicate of #1544 which is similar and also suggests that a solution would be origin snapping instead of top-left corner.

**Closed by akien-mga** 2015-11-20 09:39 UTC
Labels: enhancement, topic:editor
