### ISSUE TITLE
Weird GI colors when using a compressed (Video Ram) emissive texture

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18449] opened 2018-04-26 16:00 UTC
Godot 3.0.2 with a GTX 1070, Windows 10 64 bits.

In my game project when I use a compressed emissive texture and then use a GIProbes I get weird colors arround the asset. The color isn't always the same it can be blue, then green or orange. When I increase the emissive value the color is mostly visible on the asset, it makes the whole asset glow with that weird color but the assets nearby aren't lighted by this weird color they only reflect it.

I have seen that reimporting the texture to Uncompressed or Loseless fixed the problem.

Compressed Emissive:

![compressed](https://user-images.githubusercontent.com/30020215/39317359-b0d66ea6-497b-11e8-809f-4d6a38ad9df0.png)

Uncompressed:

![uncompressed](https://user-images.githubusercontent.com/30020215/39317364-b6ba98ec-497b-11e8-9a9a-bcf0e13c009b.png)

In a new Godot project I have tried to reproduce it with the same asset and compressed emissive texture but I had no bug. So I will directly link to the source file of the game. The asset in an instanced scene called "Light", the texture Light emissive must be reimported as Video Ram compression, then in the Main scene the GIProbes must be baked. 

https://github.com/LudumDare41/LD41

**Comment by KoBeWi** [comment] 2020-06-16 16:03
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

(the linked "MRP" is too big and doesn't seem to have GI Probes...)

**Comment by Zireael07** [comment] 2020-06-16 16:22
I think the existence of #39335 (a recent dupe) is enough of an answer?

**Comment by KoBeWi** [comment] 2020-06-16 16:24
But this one seems to be about texture compression (on import). It might be a different issue.

**Comment by akien-mga** [comment] 2021-04-28 10:02
Fixed by #41471.

**Closed by akien-mga** 2021-04-28 10:02 UTC
Labels: bug, topic:rendering
