### ISSUE TITLE
The mouse disappears in full screen when pointer trails are active

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#49321] opened 2021-06-04 19:26 UTC
**Godot version:**

3.3.2 stable mono

**OS/device including version:**

win10
radeon vega 8

**Issue description:**

The mouse disappears in full screen ( shift + f11 ) although it is still operational but is invisible.

**Steps to reproduce:**
Press shift + f11 to fullscreen in the editor.

activate this option for the mouse
![Captura](https://user-images.githubusercontent.com/19652075/120859239-388c3600-c584-11eb-81e1-376bf4065d75.PNG)

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2021-06-04 20:18
Can't reproduce.
Windows 10, GTX 1060

**Comment by Torguen** [comment] 2021-06-04 20:24
> Can't reproduce.

> Windows 10, GTX 1060

Activate this!

![Captura](https://user-images.githubusercontent.com/19652075/120858807-9a986b80-c583-11eb-9c10-4a7587d483b4.PNG)

**Comment by akien-mga** [comment] 2021-09-16 13:03
Duplicate of #40230.

**Closed by akien-mga** 2021-09-16 13:03 UTC
Labels: bug, platform:windows, topic:editor, confirmed
