### ISSUE TITLE
`gdscript_tokenizer` error when right clicking on dictionary

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#47333] opened 2021-03-24 18:08 UTC
**Godot version:**

3.2.3

**OS/device including version:**

**Issue description:**

If I have a `Dictionary` variable, defined outside any functions like
```gdscript
var a = {
	x =true
}
```
and I right click somewhere between key and val, that is after `x` and before `=true`, I get this error in `Output`:

```
modules/gdscript/gdscript_tokenizer.cpp:1129
- Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
```

The error doesn't appear if such variable is inside some function like:
```gdscript
func _init():
	var a = {
		x =true
	}

```
Also this happens only with "lua-style" defined pairs, that is the error doesn't appear here:
```gdscript
var a = {
	'x':true
}

```

**Steps to reproduce:**
1. Create an empty script and paste this code:
```gdscript
var a = {
	x =true
}
```
2. Right click on 2:6 or 2:7 (after `x` but before `=true`)
You will get the error in Output

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-03-24 18:54
Duplicate of https://github.com/godotengine/godot/issues/35994 (same cause).

**Closed by Calinou** 2021-03-24 18:54 UTC
