### ISSUE TITLE
Tileset erased when creating duplicate

### ISSUE THREAD

**Issue by securas** [godotengine/godot#85330] opened 2023-11-24 23:22 UTC
### Godot version

4.2 RC1

### System information

Windows 10

### Issue description

Consider the situation where you have a tilemap with a given tileset.
If you save the tileset to a resource file, you can use the same tileset on a second tilemap.
If you select the tileset on that second tilemap, make it unique and save it to another resource file, the original tileset is erased.
All information seems to be lost albeit opening the resource file on a text editor shows tile information.

### Steps to reproduce

The description includes the steps to reproduce and I'm attaching an example project.

### Minimal reproduction project

[2023_12_Test_Tileset.zip](https://github.com/godotengine/godot/files/13462507/2023_12_Test_Tileset.zip)

**Comment by KoBeWi** [comment] 2023-12-21 18:44
Duplicate of #80076

**Closed by KoBeWi** 2023-12-21 18:44 UTC
Labels: bug, topic:editor, topic:2d
