### ISSUE TITLE
Control resizing issue (regression) in 3.2.4 RC5

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#47481] opened 2021-03-30 02:58 UTC
**Godot version:** 3.2.4 RC5

**OS/device including version:** Windows 10

**Issue description:**
Control resizing seems wonky. It looks like the size changes keep multiplying, and it's really hard to size controls properly. In some instances, you're dragging anchors one way, but the control is still resizing in the other direction.

![sample video](https://im6.ezgif.com/tmp/ezgif-6-6f534174162d.gif)

**Steps to reproduce:** Create a `Button` or `Label` and try to double size by dragging the corners. No special setup required.

This is a regression from 3.2.3, where this worked fine (I tested it again just now to be sure).

**Comment by volzhs** [comment] 2021-03-30 04:46
@nightblade9 you can insert gif directly on github by dragging it on to comment.

**Comment by floppyhammer** [comment] 2021-03-30 05:01
Check out #46979 that was already fixed in 3.3 RC6.

**Comment by akien-mga** [comment] 2021-03-30 06:37
Duplicate of #46979.

**Closed by akien-mga** 2021-03-30 06:37 UTC
