### ISSUE TITLE
Crash when renaming .tscn

### ISSUE THREAD

**Issue by jaggzh** [godotengine/godot#19445] opened 2018-06-08 12:14 UTC
Debian stretch  with a stable release  of godot.

IDE crash (segfault):
I had been renaming some .tscn and .gd's  from within godot.
I had one scene preloaded from a .gd script, which errored when running my app within godot. After fixing that the app would run. I had also changed some comments in some .gd's amidst this time.

**Then, upon re-renaming one of my .tscn's in the main resources folder (also from within godot), it crashed.  (This was a  file I had previously renamed once.)**

I have been unable to reproduce the issue.  I hope the backtrace helps.

Do we provide stable releases with debug [symbols]? Would that make the backtrace prettier?

handle_crash: Program crashed with signal 11
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0xfc5b00xyz] (??:0)
[2] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x19caa12] (??:?)
[3] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x19d3c93] (??:?)
[4] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2e41e] (<artificial>:?)
[5] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2e57c] (??:?)
[6] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2e5ee] (??:?)
[7] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x97a5b8] (??:?)
[8] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x4f2512] (??:?)
[9] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2ebe9] (??:?)
[10] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2a37f] (??:?)
[11] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2b389] (??:?)
[12] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x10f1bcd] (??:?)
[13] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x9d9300] (??:?)
[14] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xb39a17] (<artificial>:?)
[15] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xbc7cfe] (<artificial>:?)
[16] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x463bbd] (??:?)
[17] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2ebe9] (??:?)
[18] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2a37f] (??:?)
[19] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2b389] (??:?)
[20] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x126672f] (<artificial>:?)
[21] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x4f204a] (??:?)
[22] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2ebe9] (??:?)
[23] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2a37f] (??:?)
[24] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2b389] (??:?)
[25] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1078065] (<artificial>:?)
[26] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xb96baa] (??:?)
[27] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2f7b0] (??:?)
[28] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x19c751a] (??:?)
[29] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xfca7ef] (<artificial>:?)
[30] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xfcb324] (??:?)
[31] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xfcb4ad] (<artificial>:?)
[32] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x7072f0] (??:?)
[33] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x1a2ebe9] (??:?)
[34] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x19c75a1] (??:?)
[35] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xf7a4d8] (??:?)
[36] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0xfc6f42] (??:?)
[37] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x493fee] (<artificial>:?)
[38] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x4b0217] (<artificial>:?)
[39] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x55b34f] (<artificial>:?)
[40] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x45411c] (??:?)
[41] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xfc5a21xyz] (??:0)
[42] /home/jag/pubp/Godot_v3.0.2-stable_x11.64() [0x46061f] (??:?)
-- END OF BACKTRACE --

**Comment by MrJustreborn** [comment] 2018-06-11 19:37
I had the same problem on Manjaro x64

(I dont have the stacktrace)

When renaming a tscn the editor crashed (everytime) the tscn were referenced in different scenes maybe thats the cause (one scene where it was referenced also was opened)

**Comment by hpvb** [comment] 2018-08-13 20:07
I have tried to reproduce this in a variety of ways also and have been unable to on master.

**Comment by reduz** [comment] 2018-09-07 17:03
This one is a duplicate of another issue which I can't find but I am sure I have seen it :\

**Comment by spongeboburu** [comment] 2018-11-10 05:38
I just tried renaming a folder and that resulted in a crash. Freshly built from master.

It might be related.

**Comment by akien-mga** [comment] 2019-01-22 11:43
There were various fixes recently regarding crashes that could happen when renaming/moving files around. So I'll assume this one might have been fixed too.

Please comment if you can still reproduce it.

**Closed by akien-mga** 2019-01-22 11:43 UTC
Labels: bug, topic:editor
