### ISSUE TITLE
Running on android device installs but does not run

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8581] opened 2017-04-29 17:18 UTC
**Ubuntu 17.04 - Godot version: 2.1.3**

**Issue description:**
Debug-running on Android device installs the game but does not run it.
On 2.1.2 the project runs automatically after installed on the device when running from the editor.

**Steps to reproduce:**
Configure Android export and try to run the project on the Android device on 2.1.3.

**Link to minimal example project:**
Any project should be fine.

ps: Templates are ok, tested with clean editor settings too.

**Comment by eon-s** [comment] 2017-06-19 16:06
I can't reproduce this anymore on 2.1/HEAD.

**Comment by eon-s** [comment] 2017-06-25 23:14
Reopening because it does not work on the 2.1.4 beta #9368

The terminal window shows:

> Error: Unknown option: --user 0
> java.lang.NullPointerException
> 	at com.android.commands.am.Am.runStart(Am.java:433)
> 	at com.android.commands.am.Am.run(Am.java:109)
> 	at com.android.commands.am.Am.main(Am.java:82)
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
> 	at dalvik.system.NativeStart.main(Native Method)

**Comment by akien-mga** [comment] 2017-06-26 06:09
Looks like an issue with ab7faa128, though it's a bit weird that it appears 5 months later when we had 2.1.2 and 2.1.3 in the meantime.

What version of ADB are you using?

**Comment by eon-s** [comment] 2017-06-26 09:13
Weird, if I build everything it works fine (except remote debugger), just fails on 2.1.3 and 2.1.4 official builds.

@akien-mga adb 1.0.32 and 1.0.39, I'm unable to do remote debug on 2.1.2 and older too and I was suspecting of adb for that (it used to work before reinstalling everything).

I'll see if I can get some old tools to test.

**Comment by RandomShaper** [comment] 2017-07-26 23:23
I don't know what https://github.com/godotengine/godot/commit/ab7faa12814b92892d7757db3113307732389300 was trying to fix, but it's pointless. `--user 0` would mean "run as root".

From `adb shell` onwards, the command is executed on the device itself. So `--user` has to be supported by the version of the __`am`__ command present on the device, which will vary among Android versions.

Also it's clearly the cause of @eon-s's issue. What Android version are you running?

**Comment by eon-s** [comment] 2017-07-26 23:29
@RandomShaper tested with 4.2.2 and 4.4.4

**Comment by RandomShaper** [comment] 2017-07-26 23:56
Thanks, @eon-s. The `--user` switch seems to have been introduced from Jelly Bean (4.1, API level 16), according to https://github.com/android/platform_frameworks_base/blob/jb-release/cmds/am/src/com/android/commands/am/Am.java, so it's weird it doesn't work for you, but maybe the Android people release stuff in non straighforward ways.

Anyway, although it worked for you, Godot 2.1 Android support starts on API level 14, so that switch cannot be unconditionally used, but. above all, I don't see the point.

**Comment by volzhs** [comment] 2017-07-27 00:29
@RandomShaper IIRC, `--user` tried to solve a problem if a device has multiple user accounts.

**Comment by RandomShaper** [comment] 2017-07-27 00:38
Oh, I was blind. I've seen the original issue in the commit message. I'll have a look.

**Comment by RandomShaper** [comment] 2017-07-27 13:19
@eon-s, and in both cases you get the same message `Error: Unknown option: --user 0`? Are you running stock or custom ROM?

**Comment by eon-s** [comment] 2017-07-27 15:01
@RandomShaper stock, 2.1.2 official builds work and if I build 2.1.4, works.

**Comment by RandomShaper** [comment] 2017-07-27 15:37
I think #9922 covers all the cases.

**Comment by RandomShaper** [comment] 2017-07-28 10:54
This should be fixed now #9922 is merged.

**Closed by RandomShaper** 2017-07-28 10:54 UTC
Labels: bug, platform:android, topic:porting

**Comment by eon-s** [comment] 2017-08-01 11:52
Just confirming that is working on latest beta.
