### ISSUE TITLE
Extract gdscript runtime as a individual interpreter?

### ISSUE THREAD

**Issue by qichunren** [godotengine/godot#20631] opened 2018-07-31 11:55 UTC
I enjoyed use gdscript. Who is interested in creating a gdscript interpreter to seprate from Godot editor? 

I would like to see GDScript dev ecology growing up as a independent programing language.

**Comment by OvermindDL1** [comment] 2018-07-31 14:33
Except a good bit of the language exists solely for integration with the editor, and ignoring those parts why not just use Python at that point?

**Comment by vnen** [comment] 2018-07-31 16:47
Related #17846

I don't think this will ever happen in an official way. GDScript is too tailored for Godot. It depends 100% on the types defined on the Godot core, so one would have to extract that to make GDScript work on its own. It's too much effort and there's probably better languages already available to do what you want.

The only possibility (if even that) is if another host tool wants to use GDScript as a scripting language, then change it to be embeddable. Likely won't happen.

**Comment by LikeLakers2** [comment] 2018-07-31 16:54
I don't know if it counts, but if you're looking for Godot to run scripts from the command line, [Godot can totally do that](http://docs.godotengine.org/en/3.0/getting_started/editor/command_line_tutorial.html#running-a-script). Though like @OvermindDL1 said, at that point it might be better to use Python, depending on what your needs are.

**Comment by KoBeWi** [comment] 2018-07-31 18:55
> it might be better to use Python, depending on what your needs are.

It mightn't. GDScript has some QoL changes compared to Python that makes the latter totally unusable in comparison. For example, Python forces you to write `self` for literally every property you use in a class, including methods. Also, it forces you to write explicitly `self` as first argument of class method's, because you know, self comes as hidden argument, but in Python everything has to be explicit. That's the most stupid thing I ever seen in programming language. If someone plans to switch to Python for GDScript reasons, I have to say that similar syntax just isn't worth it. There are other languages too.

Hating aside, I see why someone would want GDScript as separate language, but it would be useless on it's own, because it lacks lots of features you'd expect from a stand-alone language. Most of languages now provide things like lambdas or, dunno, metaprogramming, which GDScript just lacks. It's a very basic language, because most of the stuff you do via GDScript is actually done by the engine. Separating them is a bad idea. Just saying. If someone wants to do that themselves, I'm not saying they shouldn't xd

**Comment by akien-mga** [comment] 2018-08-13 09:48
Duplicate of #17846, and won't happen for the same reasons listed there (and here). It's just not worth it. GDScript was created to be embedded into Godot, not to be a standalone language.

**Closed by akien-mga** 2018-08-13 09:48 UTC
