### ISSUE TITLE
Missing Basis constructor for euler angles.

### ISSUE THREAD

**Issue by spongebob** [godotengine/godot#12515] opened 2017-10-30 13:26 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26, x86_64, master branch, nvidia 1080 with 384.90 prop drivers.

**Issue description:**
Basis Basis(Vector3 euler) constructor will show up in syntax completion and is in the latest documentation, but trying to use it results in "Parse Error: Invalid arguments for 'Basis'' constructor.".

**Steps to reproduce:**
var basis = Basis(Vector3(0, 0, 0))

**Suggestion**
Here is a proposal for some really useful functions that Basis could have:

- Quat get_quaternion(), set_quaternion(Quat quat)
- Vector3 get_euler(EulerOrder order), set_euler(EulerOrder order, Vector euler)
- [Vector3, float] get_axis_angle(), set_axis_angle(Vector3 axes, float angle)
- Vector3 get_direction(), set_direction(Vector3 direction)

Note that the euler functions allow to specify an order where EulerOrder is an enum describing every permutation the order the euler angles can have. 

Optionally one could set the up angle for the Basis or have optional arguments for the functions that would need it, such as euler angles and direction functions. Otherwise it could be assumed to be 0,1,0 to keep it consistent with the editor.

**Comment by akien-mga** [comment] 2017-11-01 09:15
Duplicate of #10721. CC @tagcup for the suggested new methods.

**Closed by akien-mga** 2017-11-01 09:15 UTC
Labels: bug, topic:core
