### ISSUE TITLE
Metallic Texture is not rendering properly.

### ISSUE THREAD

**Issue by aarroz** [godotengine/godot#10292] opened 2017-08-12 04:37 UTC
Ubuntu 16.04 - Most recent Git Build of Godot

Mirror material in Materials demo is not reflecting the HDR environment correctly, rendering mostly red,green and blue in dark regions.
![screenshot_2017-08-11_21-35-05](https://user-images.githubusercontent.com/19158892/29237904-f79f9070-7edc-11e7-98b8-6c907bf8cd0b.png)

Steps to reproduce:
Opening the Material Tester demo, running the demo and viewing the mirror mesh.

**Comment by fracteed** [comment] 2017-08-12 04:49
Yes, it is broken and related to ambient environment lighting. See here #10216

**Comment by kubecz3k** [comment] 2017-08-14 16:31
Closing as a duplicate of https://github.com/godotengine/godot/issues/10216

**Closed by kubecz3k** 2017-08-14 16:31 UTC
Labels: archived

**Comment by kubecz3k** [comment] 2017-08-14 16:33
@aarroz fell free to add your observations to the #10216
