### ISSUE TITLE
Errors in gdscript when creating a Callable from self

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#40793] opened 2020-07-28 14:57 UTC
**Godot version:**
Master cf03f90fa8d8e0fadcf22741ab75220665578371

**OS/device including version:**
Windows 10

**Issue description:**
Callables with self cause parsing errors in gdscript, which makes it impossible to connect signals by script.

This script line produces gdscript errors:
```
var callable = Callable(self, "my_function")
```

Log:
```
SCRIPT ERROR: Parse Error: No constructor of "Callable" matches the signature "Callable(res://Control.gd, String".
          at: GDScript::reload (res://Control.gd:5)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: GDScript::reload (modules\gdscript\gdscript.cpp:620)
Loading resource: res://Control.tscn
ERROR: Condition "!s->is_valid()" is true.
   at: EditorInspector::_update_script_class_properties (editor\editor_inspector.cpp:2451)
```

This workaround used to work but now it produces the same error:
```
var self_var = self
var callable = Callable(self_var, "my_function")
```

**Steps to reproduce:**
Add this line to any script:
```
var callable = Callable(self, "my_function")
```
And check for gdscript errors.

**Minimal reproduction project:**
Can be reproduced in any project.

**Comment by akien-mga** [comment] 2020-07-28 16:26
The confusing error should be fixed, but isn't this invalid GDScript? Variables are declared with `var`, not type names, so this should be:
```gdscript
var callable = Callable(self, "my_function")
```

**Comment by pouleyKetchoupp** [comment] 2020-07-28 16:55
Ah sorry, I just made a typo when copying the Callable constructor from a function call, editing the issue description.

**Comment by akien-mga** [comment] 2020-07-28 18:02
Possibly a duplicate of #40751 then.

**Comment by KoBeWi** [comment] 2020-07-28 18:07
Yep, the problem is that it passes String where StringName is expected. Unless we can make the error more clear (i.e. state what types can be used in the constructor), the issue can be closed.

**Closed** 2020-08-18 21:18 UTC
Labels: bug, regression, topic:gdscript
