### ISSUE TITLE
Sprite.texture created programmatically is Empty in remote tree node inspector

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#30033] opened 2019-06-24 13:36 UTC
**Godot version:**
05a0a68

**Issue description:**
Sprite.texture set programmatically is Empty in remote tree node inspector
![Screenshot_56](https://user-images.githubusercontent.com/11059246/60023064-5614ad80-9695-11e9-931b-fff1fb1750ae.png)

**Comment by KoBeWi** [comment] 2019-06-27 13:43
Also related to #28353 and probably other resources have this too.

**Comment by KoBeWi** [comment] 2020-07-24 18:11
Seems fixed in 3.2.2

**Comment by timothyqiu** [comment] 2020-12-24 13:10
@KoBeWi I think this is not fixed in 3.2.2 and still valid in 3.2.3 / 3.2.4.beta4.

Try this MRP: [ShapeDebug.zip](https://github.com/godotengine/godot/files/5739648/ShapeDebug.zip)

**Comment by KoBeWi** [comment] 2020-12-24 13:14
Looks like this only happens with textures created in code. When you do `$B/Sprite.texture = load("res://icon.png")` it appears correctly.

**Comment by Calinou** [comment] 2021-03-25 19:41
Duplicate of https://github.com/godotengine/godot/issues/28353 (same cause).

**Closed by Calinou** 2021-03-25 19:41 UTC
Labels: bug, topic:editor
