### ISSUE TITLE
Dragging Editor Window between monitors crashes it

### ISSUE THREAD

**Issue by rafaelgdp** [godotengine/godot#34187] opened 2019-12-07 19:59 UTC
**Godot version:** Godot 3.2 Beta commit 8eb183aebb9c79ff92d6f566af7ad2f91696ce08

**OS/device including version:** MacOS Catalina 10.15.1. Macbook Pro 2018.

**Issue description:** Whenever I drag the Godot Editor window between my secondary monitor and the main screen, it crashes. It seems it tries to adjust the window display scale/resolution to match the current screen it is changing to. However, the client simply crashes. It is worth noting that I tried with both Editor's display scale set to "Auto" and to a fixed percentage (200%). In both scenarios, it crashed when dragged from one monitor to the other. In some cases, the screen turns all red before it crashes.

**Steps to reproduce:** Open Godot in a machine with at least two screens with different resolutions and drag the window from one monitor to the other.

**Minimal reproduction project:** No project needed as it seems to be an Editor bug.

**Comment by akien-mga** [comment] 2019-12-07 20:11
Duplicate of #34172.

**Closed by akien-mga** 2019-12-07 20:11 UTC
