### ISSUE TITLE
Error when opening a scene with camera preview on

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#33050] opened 2019-10-24 21:25 UTC
**Godot version:**
Master 930d6d8ca4c34b0383d232335902f7f808806a66

**OS/device including version:**
Windows 10

**Issue description:**
In the editor, when opening a scene which has Camera preview enabled, an error occurs:
```
ERROR: _toggle_camera_preview: Condition ' p_activate && !preview ' is true.
   At: editor/plugins/spatial_editor_plugin.cpp:2822.
```
When closing the scene, this error occurs:
```
ERROR: _toggle_camera_preview: Condition ' !p_activate && !previewing ' is true.
   At: editor/plugins/spatial_editor_plugin.cpp:2823.
```

It doesn't happen in version 3.1.1 stable.

**Comment by qarmin** [comment] 2019-10-25 09:47
Duplicate of #29230
Bisect show that this is first bad commit 5e8017721a8a552c26f6ad2abe3e4b438727214b

**Comment by akien-mga** [comment] 2019-10-25 10:04
>  Bisect show that this is first bad commit [5e80177](https://github.com/godotengine/godot/commit/5e8017721a8a552c26f6ad2abe3e4b438727214b)

**Closed by akien-mga** 2019-10-25 10:04 UTC
Labels: bug, regression, topic:editor
