### ISSUE TITLE
The path cannot be correctly specified. The last directory is trimmed.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#13323] opened 2017-11-26 22:44 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu16.04, Master

**Steps to reproduce:**
Click to creating a new project. Select any folder.
The last directory will not be in the way.

**Comment by akien-mga** [comment] 2017-11-26 22:48
Duplicate of #13203.

**Closed by akien-mga** 2017-11-26 22:48 UTC
