### ISSUE TITLE
Editor multi window support

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#29560] opened 2019-06-06 22:44 UTC
**Godot version:**
3.1

**OS/device including version:**
linux

**Issue description:**
It would be very useful to have multi window support in the editor. Currently I find I waste a large amount of time flipping between tabs and layouts.
It would be useful to have support for a seperate window dock where the user can drag the ide, the viewport or the docks. 
I find this extremely useful when working in other software over multiple monitors, or on linux, multiple virtual desktops.

**Comment by KoBeWi** [comment] 2019-06-07 00:08
Duplicate of #9059 (and other issues linked there)

**Closed by KoBeWi** 2019-06-07 00:08 UTC
