### ISSUE TITLE
Touch input doesn't emit mouse_entered() or mouse_exited() in buttons

### ISSUE THREAD

**Issue by swordxh** [godotengine/godot#85695] opened 2023-12-03 00:21 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.2.stable

### System information

Android 9, godot 4.2

### Issue description

Any buttons that falls into the "control" category doesn't emit mouse_entered() or mouse_exited() if you use touch screen, even if you set emulate_mouse_from_touch to true. 
I tested Area2D mouse_entered or exited and they work even on touch screen.
For a project i'm making i can't really use TouchScreenButton because i need precise anchoring as a GUI node.

### Steps to reproduce

Place a Button/TextureButton and connect mouse_entered() or mouse_exited(), it won't fire if you are using a touch screen.
In the minimal reproduction project there's a button already placed with signals connected to the text, if you hover it with a mouse the text changes, if you try to touch it on android it doesn't.

### Minimal reproduction project

[button-mouse-test.zip](https://github.com/godotengine/godot/files/13537718/button-mouse-test.zip)

**Comment by klaritan** [comment] 2023-12-15 23:48
Noticed this issue as well. Same Godot version. mouse_entered or mouse_exited are never fired via touch screen

**Comment by maran** [comment] 2023-12-21 17:41
I can confirm this is also the case on Android 14.

**Comment by Joopster** [comment] 2023-12-22 07:48
Same issue on iOS. 

This completely breaks my mobile app.

**Comment by QbieShay** [comment] 2023-12-22 08:50
CC @Sauermann

**Comment by QbieShay** [comment] 2023-12-22 08:57
@maran @Joopster I think if you explain how you're using mouse entered and exited in those platforms it will help us understand if we can support your use case, either with a fix or with a workaround.

From what I understand this introduces a difference in the way input is handled on desktop and touchscreen which makes it really hard to develop for mobile because you can't realiably emulate input on desktop. Is this correct?

**Comment by maran** [comment] 2023-12-22 09:03
We have a couple of Control elements that we highlight if you hover  (or drag on mobile) over them. Initially we used mouse_entered and mouse_exited events for these, however this stopped working on mobile platforms.

We are now using a work-around to listen for gui_event events on most of these controls and using various custom logic to estimate the original behavior, which works but it makes the code a bit dirtier imho.

**Comment by wystans** [comment] 2024-01-07 21:29
Is [#86081](https://github.com/godotengine/godot/pull/86081) a potential fix for this bug?

**Comment by Blue64537** [comment] 2024-01-13 10:36
I also ran into this bug, which broke my game on mobile (android and mobile web).
It is broader than just buttons, because it also happens with panels.
It is broken in 4.2.1-stable and 4.3-dev2, but it still worked in 4.1.2-stable.

**Comment by StabAlarash** [comment] 2024-03-14 21:33
Hey I just ended up with this problem on 4.2.1 so for good measure I tested a few versions:
- 4.1.3: the only one that worked for me
- 4.2.1: my original version, fails
- 4.2.2-rc1: fails
- 4.3-dev4 

If that can help, but looks like the problem definitly happens between 4.1.2 and 4.2.1 and still exists in more recent versions

**Comment by gloomie** [comment] 2024-03-18 16:41
This problem still exists on 4.3-dev5 (althought release logs state something about "mouse_entered" is fixed). 
Actually, the most recent version that works is 4.1.3.

Without this resolved, all android/ios projects are locked to 4.1

**Comment by Sauermann** [comment] 2024-04-11 19:15
I have tested the MRP exported to an Android 13 device.

- I can confirm the bug with v4.2.1.stable.official [b09f793f5]
- I can confirm the bug with v4.3.dev5.official [c9c17d6ca]
- With v4.3.dev.custom_build [b2f425fe6] the MRP works as expected and the bug doesn't appear.

It looks like the bug has been resolved since v4.3.dev5.

**Comment by brwxisme** [comment] 2024-04-21 02:05
Tested on 4.2.2, still exist

**Comment by Sauermann** [comment] 2024-04-27 19:14
I have bisected the fix to #89920

**Comment by akien-mga** [comment] 2024-04-29 07:49
Fixed by #89920 in 4.3. The fix will be cherry-picked for 4.2.3.

**Closed by akien-mga** 2024-04-29 07:49 UTC
Labels: bug, platform:android, confirmed, topic:input, regression, topic:gui
