### ISSUE TITLE
Option for showing more/all file types in FileSystem dock

### ISSUE THREAD

**Issue by TheMadScientist1234** [godotengine/godot#25665] opened 2019-02-06 18:50 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
Can't see .cfg files in the file explorer dock

**Steps to reproduce:**
1. Create a new godot project
2. Make a script that saves a new ConfigFile within the res:// directory
3. Try and look for where you saved in the file explorer dock

**Comment by Chaosus** [comment] 2019-02-08 07:01
Well its not only cfg files - txt, exe, dat is not visible too, editor dock is not supposed to be a full system explorer - the idea is to support only significant files extensions which is useful for game development and can be edited in the editor itself

**Comment by akien-mga** [comment] 2019-02-09 11:55
Indeed, this is by design, the FileSystem dock only lists files that you can actually use directly (scenes, resources).

Now that the Script editor allows opening arbitrary text files, there could be a use case for seeing files like .cfg or .json in the FileSystem dock. Maybe as an option where you can set a whitelist of file types you want to include in the FileSystem dock.

**Comment by PLyczkowski** [comment] 2019-04-05 21:52
IMO the fact that the Godot Editor can't open a file type is not a reason to not show that file type in the FileSystem Dock, and when the user tries to open a file that the editor don't know how to open, it should send it to the default OS application.

Currently, you have to have 2 file explorers active when working on a Godot project, and keep them more or less in sync by hand - one in the Godot Editor, and one that can show files like txt, json, psd, .blend etc.

Also displaying a non-accurate state of directories (with files not displayed) in the editor can cause the user to delete directories with important files, or assume wrongly they are not there.

**Comment by SolarLune** [comment] 2019-12-16 21:15
Generally agree; it would be wise, in my opinion, to support additional / all formats (or some kind of whitelist), especially if they're human-readable like txt or json, since not being able to edit or read certain formats limits the usability of the script editor (since it's easier to just jump to a different editor permanently rather than switching constantly).

**Comment by clayjohn** [comment] 2020-05-27 05:28
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 05:28 UTC
Labels: discussion, feature proposal, topic:editor
