### ISSUE TITLE
HTML5 with GLES3: Game takes a long time to start (spins at 100% CPU utilization)

### ISSUE THREAD

**Issue by gandalf3** [godotengine/godot#39002] opened 2020-05-24 05:35 UTC
**Godot version:**
Tested with 3.2.1 stable and latest master (b0eca5828).

**OS/device including version:**
Archlinux
Firefox 76.0.1
Chromium 83.0.4103.61

**Issue description:**
Loading the exported html in Firefox or Chromium pins one CPU core to 100% on a black screen for around a minute, then the game starts.

No errors are reported in the console, though there are a few webgl warnings that appear after the delay:

```
WebGL warning: getBufferSubData: Reading from a buffer with usage other than *_READ causes pipeline stalls. Copy through a STREAM_READ buffer. 2 html5_test.js:7:30378
WebGL warning: drawArraysInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. html5_test.js:7:247343
```

This delay is not present in the same project after switching to GLES2.

**Steps to reproduce:**

1. Export a simple project to HTML5 
2. Start a local server (e.g. `python -m http.server 8000`.
3. Visit the exported html in a browser (e.g. at `localhost:8000/html5_test.html`).

**Minimal reproduction project:**

[html5_test.tar.gz](https://github.com/godotengine/godot/files/4672996/html5_test.tar.gz), just a cube and a camera.

**Comment by Calinou** [comment] 2020-05-24 08:12
Duplicate of #21957.

**Closed by Calinou** 2020-05-24 08:12 UTC
