### ISSUE TITLE
Sprite3D nodes are invisible on mobile devices?

### ISSUE THREAD

**Issue by Tianmaru** [godotengine/godot#60103] opened 2022-04-10 15:50 UTC
### Godot version

3.4.3.stable.official

### System information

Debian 11, GLES2

### Issue description

In a game about cleaning your room, we used Sprite3D nodes, to distribute T-Shirt sprites across a room.
If I test the HTML5 export on my PC, everything looks fine. However, I also tried the game on two tablets (IPad as well as Android), and for some reason, there were no T-Shirts to see. At first, I thought it was a bug in my code - but now I am pretty sure they are just invisible?
Am I missing some option in the project settings? I don't know what could cause this behaviour.

### Steps to reproduce

Add a Sprite3D node, add a texture and test it on PC and mobile.

### Minimal reproduction project

You can also test our game (https://tianmaru.itch.io/kuddelmuddel). There should be T-Shirts visible in the title screen.

**Comment by clayjohn** [comment] 2022-04-10 16:15
Can you provide more information about your setup. 

For example, do you have VRAM compression turned on when importing the t-shirts?

Do you get any errors when you run the scene on the platforms where things break?

Do you have any special shader on the t-shirts?

**Comment by Calinou** [comment] 2022-04-10 17:01
Can you reproduce this after disabling **Mipmaps** in the Import dock, clicking **Reimport** then exporting to Android again? If so, this is a duplicate of https://github.com/godotengine/godot/issues/54220.

**Comment by Tianmaru** [comment] 2022-04-10 19:20
Thanks for your replies.
@clayjohn Yes, VRAM compression was enabled. No, there is no special shader on the t-shirts, it is just a Sprite3D node with the texture set to a PNG file. The only things I changed is the modulate property, the pixel size set to 0.001 and axis to Y-axis. I don't know how to test for error messages, but at least the game doesn't crash and otherwise seems to behave normally on tablets.
@Calinou thanks, I will give that a try. I will keep you informed if that helped.
I found something about texture sizes being required to be a power of 2 for mobile device, is that relevant for my case?

**Comment by clayjohn** [comment] 2022-04-10 19:46
> I found something about texture sizes being required to be a power of 2 for mobile device, is that relevant for my case?

Potentially, Godot automatically resizes non power of 2 textures where necessary. But there could be something going wrong with the resize.

**Comment by Tianmaru** [comment] 2022-04-11 11:08
I disabled mipmaps, changed compression from vram to lossless and, just to be sure, rescaled the images to 256x256. Now it is working!

**Comment by Calinou** [comment] 2022-04-11 12:17
Duplicate of https://github.com/godotengine/godot/issues/54220.

**Closed by Calinou** 2022-04-11 12:17 UTC
Labels: bug, platform:android, topic:rendering, topic:3d
