### ISSUE TITLE
ProjectManager UI laggy / unresponsive

### ISSUE THREAD

**Issue by JavierJF** [godotengine/godot#26689] opened 2019-03-06 08:57 UTC
**Godot version:**
Godot 3.1 Beta 11
Godot 3.1 Beta 10
Godot 3.1 Beta 9

Godot 3.0.6 stable

**OS/device including version:**
Windows 10, version 1803, build 17134.590

**GPU model**
Intel(R) UHD Graphics 620

**Screen**
I'm including this because I think it could be a high-dpi related issue. The screen is a 4k screen from a
Dell XPS 13; it's working at 2k with Windows scaling set to 175%. I haven't experienced this behavior in my other PC, even in another screen at 2k, but in that case UI scaling is at 100%.

**Issue description:**
Project manager interface is very unresponsive, while the rest of the editor interface works as expected. Looks like sometimes the interface is not refreshed, and also it doesn't properly handle input events.

It seems like many times an input event is cached/buffered somehow, but not processed, so pressing twice "f" results into one displayed "f" and another one stored until another UI event is input by the user, then the other "f" is displayed.

**Steps to reproduce:**
Start Godot and try to use the project manager normally.

**Comment by Calinou** [comment] 2019-03-06 09:25
Duplicate of https://github.com/godotengine/godot/issues/23069.

**Closed** 2019-03-06 09:58 UTC
Labels: archived
