### ISSUE TITLE
Node added to inherited scene always draw on the top

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#12765] opened 2017-11-09 03:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.1 

**Issue description:**

the tree in the editor
<img width="1292" alt="screen shot 2017-11-09 at 11 49 18 am" src="https://user-images.githubusercontent.com/1130047/32587604-43971c02-c544-11e7-8452-d28ab280effe.png">

the result:
<img width="1137" alt="screen shot 2017-11-09 at 11 49 34 am" src="https://user-images.githubusercontent.com/1130047/32587605-43d9055e-c544-11e7-82b6-a5d86e6e2f3b.png">

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by kubecz3k** [comment] 2017-11-27 17:01
hard to tell from the description, but looking at the attached screen it seems this issue is a duplicate of #12139

**Comment by akien-mga** [comment] 2018-09-17 15:18
Duplicate of #12139.

**Closed by akien-mga** 2018-09-17 15:18 UTC
Labels: bug, topic:rendering
