### ISSUE TITLE
Ternary conditional operator

### ISSUE THREAD

**Issue by Fiona** [godotengine/godot#1961] opened 2015-05-22 14:58 UTC
"If this do this else this" is such a common operation and the reason ternaries exist in almost all modern languages. Them missing is especially egregious in languages with syntactic whitespace. (4 lines for a simple choice.)

Python's ternary syntax is both readable and non-cryptic.

    a if test else b

**Comment by jackmakesthings** [comment] 2015-05-24 23:19
+1, would love to see this implemented. Though - speaking as someone more accustomed to js and php-type syntaxes - I would be thrown off by having one of the possible outcomes declared before the actual testing condition is. Maybe some adaptaion of `condition ? a : b` (where a is the "if true" option and b is the "else"/"if false") would work?

**Comment by punto-** [comment] 2015-05-25 02:24
Does the python thing work as a value? ie can you do "var a = b if test
else c" ?

**Comment by SaltPeter** [comment] 2015-05-25 03:04
I'm hoping to add this feature, I'm very experienced. Would I just be looking at  gd_tokenizer?

**Comment by Fiona** [comment] 2015-05-26 10:00
@punto- Yes that's really what it's primarily for.

**Comment by reduz** [comment] 2016-01-03 22:24
will do for 2.1

**Comment by hetdegon** [comment] 2016-01-03 23:04
That's great news!

**Comment by trollworkout** [comment] 2016-01-30 11:08
i had a different suggestion that matches gd script more
if test a else b

this is very similar with what you already have in gd script but you can also use it like this
var = (if test a else b)

**Comment by akien-mga** [comment] 2016-02-01 10:15
I think we should go with the Python syntax when implementing this, since most of GDScript's syntax is based on python, better stick to it.

**Comment by brunosxs** [comment] 2016-02-12 23:32
I add my voice to this choir
Also agree with @akien-mga , it has to follow python syntax, even if it is a little strange compared to others.

**Comment by razvanc87** [comment] 2016-02-13 17:57
+1 for python syntax

**Comment by leotada** [comment] 2016-04-25 15:24
+1 for python syntax

**Comment by bojidar-bg** [comment] 2016-05-19 08:53
I would like to throw CoffeeScript syntax into the mix:
````coffee
a = if test then x else y
````

**Comment by trollworkout** [comment] 2016-05-19 10:06
I'm down for anything as long as it can be used to assign value to a variable or return
var a = x if test else y
return x if test else y

**Comment by Dillybob92** [comment] 2016-05-23 09:15
+1 for python syntax, this would be a great feature

**Comment by Fiona** [comment] 2016-05-23 09:32
GDScript is (largely incorrectly) refered to as a Python-like language. Therefore, deviating from the Python syntax in a core language feature like this would break the principle of least surprise.

**Comment by trollworkout** [comment] 2016-05-23 20:21
@Fiona  I agree with you and I even proposed and alternative. Ironically after further consideration I also support it for this ternary operator due to it's simplicity.

I originally proposed "if test a: else b" likely : must be used to figure out where test ends which requires 7 components

Bojidar's proposal "if test then x else y"  requieres 6 components

Python's one "x if test else y"  only requires 5 components

Quickest one has to be "test ? a : b" Java but does not really fit with GD Script and is hard to read

**Comment by gregoryfein** [comment] 2016-07-09 04:31
Would love to see any implementation of ternary.  Don't have an opinion on syntax so long as there is one to use. :)  But, if I had to throw my hat on one, I'd say Java style.

**Comment by akien-mga** [comment] 2016-07-20 15:05
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Dillybob92** [comment] 2016-08-23 17:55
2.2 possible? :)

**Comment by bojidar-bg** [comment] 2016-08-25 13:05
Going to try doing it :smile:

**Comment by Sslaxx** [comment] 2016-08-25 13:51
+1 for the Python style for GDScript, though I also like the C/C++/Java-styled operator.

**Comment by hubbyist** [comment] 2016-08-25 14:26
I would prefere "if test : x else y" syntax in trollworkout's post for a mix of least components and semantic easiness. I like to see condition(s) are followed by outcomes and well separated as in a if block which is better for a short syntax for an if block IMO.

**Comment by bojidar-bg** [comment] 2016-08-25 15:39
I decided to do the Python variation (apologies to supporters of the other options), since it looks way simpler to implement than all variations that have `if` before the test. Plus, as @Fiona said, it is the "principle of least ~~programmer work~~ surprise"

**Comment by hetdegon** [comment] 2016-08-26 04:03
I preferred the C-style option out of habit but, hey, this will do nicely. Thanks @bojidar-bg !

**Closed** 2016-09-11 21:40 UTC
Labels: feature proposal, topic:gdscript

**Comment by kintrix007** [comment] 2020-07-28 15:25
I don't know if this is the right place to ask, but is there any chance we will get C-style ternary operators? I'm just wondering, since GDscript allows for C-style operators like `|| && ! << >> & | ^`. So I think it would just make sense to add `?:` as well. But I cannot add it myself...

**Comment by Calinou** [comment] 2020-07-28 17:30
@kintrix007 There are no plans to add C-style ternary operators. To make the language easier to learn and reason about, we'd prefer having only one obvious way to write ternary statements :slightly_smiling_face:

**Comment by RevoluPowered** [comment] 2020-08-09 17:11
> @kintrix007 There are no plans to add C-style ternary operators. To make the language easier to learn and reason about, we'd prefer having only one obvious way to write ternary statements 🙂

I am actually searching the same thing, the syntax is not so obvious to me, or to others, I've looked it up several times, so some consistency with other languages would be nice so we don't have to remember another way of doing the same thing basically.

**Comment by RevoluPowered** [comment] 2020-08-09 17:19
To me and others, I am sure, it's completely the wrong order.

it should be [condition] [true] [false] regardless of the language, in all contexts you check a condition first, before returning the results.

it seems stupid to me to do [true] [condition] [false] and makes little sense to me.

**Comment by Calinou** [comment] 2020-08-09 18:22
@RevoluPowered GDScript's ternary operator syntax is already consistent with Python's.

**Comment by KingDuckZ** [comment] 2021-03-30 14:11
Just adding my experience as someone who is new to godot and learning gdscript.
First thing I tried instinctively was `var a = (condition ? true_part : false_part)` and it errored out.
Then I tried `var a = if condition true_part else false_part`, and it also errored out. So I gave up and converted my one-liner to the multi-line if/else version, as I thought that was the only supported way.

Then out of curiosity I tried searching for it and I landed on this page. I would have never guessed this weird reordering. Ok it's not the end of the world and I can remember it for now, but it's backwards and confusing. I can easily see myself in the future trying to get back to gdscript and going like "hold on, what was the ternary operator syntax again...?"
Anyways, that's my experience.

**Comment by Calinou** [comment] 2021-03-30 14:17
> Edit: besides, are conditions short-circuited in gdscript

I'd benchmark it to check that :slightly_smiling_face: 

You can use `OS.delay_msec()` to add a blocking delay.

**Comment by bojidar-bg** [comment] 2021-03-31 09:11
Well, nobody said the current behavior is perfect. If you want to push for a change in Godot 4.0 / GDScript 2.0, feel free to open a proposal on https://github.com/godotengine/godot-proposals.

The way it was implemented sought to reuse as many keywords as possible, since GDScript is a white-space and keyword-friendly language. In addition, it was implemented that way for feature party with Python. You can check the discussion above.

However, the fact that it was decided that way for reasons, does not mean it is useful. As you say yourself, there are cases in which the syntax is clunky and unreadable. It still works and isn't buggy in some major way, it is just less than useful.

And that's what proposals are for--creating a place where discussions as to the merit of exact solutions to usability problems and missing features can be held. So, if you want to improve Godot, to make it better for the next time someone stumbles upon ternaries, and if you have a general idea of how that can happen, I would strongly recommend going there and opening a proposal.

Further discussion on a closed issue is counter-productive, as it is way harder to find it afterwards. :)

**Comment by Calinou** [comment] 2021-03-31 09:20
For reference, I can confirm the slow function here is skipped on 3.3rc6:

```
extends Node2D


func slow_function() -> int:
	OS.delay_msec(20)
	return -42


func _ready() -> void:
	var begin := OS.get_ticks_usec()

	for i in 1000:
		var test := 6
		var result := slow_function() if test > 5 else 42

	print("Took %d microseconds" % (OS.get_ticks_usec() - begin))
```
