### ISSUE TITLE
Nested scroll containers create weird jumping on Android

### ISSUE THREAD

**Issue by pixelriot** [godotengine/godot#63669] opened 2022-07-30 08:58 UTC
### Godot version

3.4.4, 3.3.4

### System information

Android

### Issue description

I'm trying to implement a "Netflix"-like library with several horizontal scroll containers, embedded in a vertical scroll container.

On desktop everything works fine but on Android the vertical and horizontal scroll seem to influence each other which leads to a weird jumping of the whole ui.

https://user-images.githubusercontent.com/21098503/181903550-569d4aed-bd82-4987-9832-26e273884f9a.mp4

### Steps to reproduce

Open the sample project and export or run it on an Android phone.
Try to scroll vertically and horizontally and notice the jumpy behavior.

### Minimal reproduction project

APK:
[Testproject.apk.zip](https://github.com/godotengine/godot/files/9225838/Testproject.apk.zip)

Godot project:
[testproject.zip](https://github.com/godotengine/godot/files/9225839/testproject.zip)

**Comment by pixelriot** [comment] 2022-07-30 09:06
related issues:

https://github.com/godotengine/godot/issues/41661

https://github.com/godotengine/godot/issues/57356

**Comment by Rindbee** [comment] 2022-07-30 11:41
This could be caused by event acceptance. When the child control does not accept the event, its parent control will try to accept it. The `ScrollContainer` also doesn't accept events when it can't scroll.

**Comment by madmiraal** [comment] 2022-08-01 16:52
Duplicate of #61816 that's fixed with #62289 and it's 3.x version #62290 and will be included in 3.5.

**Closed** 2022-08-01 19:56 UTC
Labels: bug, platform:android, topic:input, topic:gui
