### ISSUE TITLE
Random, GLES3-only (white) flickering of GUI controls over Tilemap

### ISSUE THREAD

**Issue by Jeto143** [godotengine/godot#28967] opened 2019-05-17 20:14 UTC
I'm aware that #9913 exists but I'm not sure this is the same bug (not a Nvidia card, and not exactly the same symptoms).

**Godot version:**

3.1.1

**OS/device including version:**

Windows 10 (up to date) 

**Graphic card:**

Intel(R) HD Graphics 620

**Issue description:**

GUI controls such as flat panels (e.g. `StyleBoxFlat` resources) randomly flicker (generally, they flash white) when over a TileMap.

**Video showcasing the issue:**

https://streamable.com/ai0x9 (here it seems to happen when I move my mouse, but it also does when doing nothing at all, it *might* slightly increase the occurrences but it's not obvious at all)

**Notes:**

I've just spent literally half my day trying to figure out what could cause that, disabling 95% of my game's features/nodes, and still have no idea what's causing it.

- I've tried disabling HDR
- I've tried altering almost every single display rendering setting (at least the flags / dropdowns)
- Adding sprites/objects on the tilemap sometimes seem to make the problem go away, for some reason. Also playing with the camera zoom or other seeminlgy 100% random things. But then it reappears later because some other thing changed as well.
- Not entirely sure this is timemap-related, this stops happening if I hide it though.
- Not happening at all on GLES2 (so I'll be switching to that in the meantime).
- If that can help, in the reproduction project below, disabling Project Settings > Rendering > Quality > Texture Array Reflections seem to fix it. Isn't enough on my actual project though.

**Minimal reproduction project:**

[flickerbug.zip](https://github.com/godotengine/godot/files/3192936/flickerbug.zip)

Look at the top left panel for ~30 seconds. If you didn't see any flickering, try relaunching a few times (sometimes they randomly disappear), otherwise it probably means it doesn't happen for you (I doubt this is reproducible on every system / setup).

**Comment by Jeto143** [comment] 2019-05-17 21:14
So it turns out I finally found a Display option that seems to fix it: 
**Rendering > Limits > Canvas Polygon Buffer Size Kb**

Setting this to 1024 instead of 128 appears to have made the issue go away. But I wouldn't be surprised if it reappeared in other circumstances. In any case, that may help you Godot people figure out what it is about.

**Comment by agameraaron** [comment] 2019-11-26 11:25
Have you noticed any more tile pop-out since you implemented your fix of modifying the Canvas Polygon Buffer Size?

**Comment by Jeto143** [comment] 2019-11-26 11:37
Yes, in my case the flickering totally disappeared ever since I changed that setting.

**Comment by Calinou** [comment] 2020-07-16 13:08
@Jeto143 Can you (or anyone else) still reproduce this bug in Godot 3.2.2 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2021-04-28 12:53
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.

**Closed by akien-mga** 2021-04-28 12:53 UTC
Labels: documentation, enhancement, topic:rendering
