### ISSUE TITLE
Visual distortion of CanvasLayer in the editor

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#8451] opened 2017-04-18 23:41 UTC
**Operating system or device - Godot version:** Linux Mint Mate 18.1 (x64_86), custom_build 3.0 (commit 7088d9e)
**Issue description:** The size of the CanvasLayer is always equal to the size of the editor viewport, rather than the size of the window specified in the project settings.
**Steps to reproduce:** Simple example (see size option and visual position of node):
## Default view
![image](https://cloud.githubusercontent.com/assets/5412322/25157292/cdbb9e02-24b9-11e7-9696-c706b2c353db.png)

## Only changed size of editor panels
![image](https://cloud.githubusercontent.com/assets/5412322/25157350/31e3f99c-24ba-11e7-9922-4532e989cab9.png)

So... WTF?!

**Comment by bojidar-bg** [comment] 2017-04-19 09:26
Duplicate of #8328, I think (feel free to comment if this is not the case).

**Closed by bojidar-bg** 2017-04-19 09:26 UTC
