### ISSUE TITLE
LargeTexture on Sprite3D

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#6966] opened 2016-10-29 16:14 UTC
**Operating system or device - Godot version:**
Current master branch, Linux

**Issue description** (what happened, and what was expected):
I can't use a LargeTexture on a Sprite3D. It just displays a white rect.
Is there any other way of handling large textures (>1024px) in 3D i don't know of?

Edit: My problem is not disk space but the texture size limitation on mobile devices.

**Comment by Calinou** [comment] 2016-10-29 16:14
Try using a standard ImageTexture with lossy compression (WebP) instead of a LargeTexture.

**Comment by timoschwarzer** [comment] 2016-10-29 16:17
Does Godot split the textures into pieces then or handles very large textures in another way?
Because we can't use very big textures on mobile devices...

**Comment by timoschwarzer** [comment] 2016-10-29 16:24
![image](https://cloud.githubusercontent.com/assets/8849554/19831217/daf980ca-9e04-11e6-8725-46c5b659e17e.png)
Seems like it's not splitting the texture..

**Comment by eon-s** [comment] 2016-11-01 00:39
Have you tried with a Quad?

**Comment by timoschwarzer** [comment] 2016-11-01 13:51
A Quad renders only white, too.

**Comment by Noshyaar** [comment] 2018-04-07 05:55
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment] 2018-04-07 14:43
There is no way to test a large texture on Godot 3 since it does not have any means to import in that format, this issue may be relevant to Godot 2 only.

**Comment by akien-mga** [comment] 2018-11-22 10:50
Closing then as I doubt this will be fixed in the 2.1 branch by now.

**Closed by akien-mga** 2018-11-22 10:50 UTC
Labels: bug, topic:rendering
