### ISSUE TITLE
MaterialShaderGraph deleting node randomly selects another node

### ISSUE THREAD

**Issue by uoji** [godotengine/godot#4981] opened 2016-06-01 21:50 UTC
**OSX 10.11.4 iMac early 2008 - Godot version:2.0.3**

**Issue on MaterialShaderGraph deleting node:**
I have some nodes in the Graph view, if i delete one node, a random node is selected and if i move the mouse the new selected node moves with the mouse. Sometimes more than one node is randomly selected and is moving with the mouse and overlapping each other.

**Steps to reproduce:**
Just create some nodes and delete one of them and than move the mouse.

**Comment by bojidar-bg** [comment] 2016-06-02 12:19
Duplicate of #4433 (that was a bit hard to search for, so don't worry).

**Closed by bojidar-bg** 2016-06-02 12:19 UTC
