### ISSUE TITLE
Mesh is not selectable via 3D viewport

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#4049] opened 2016-03-14 13:21 UTC
**Operating system or device:**
Windows 7 64bit

**Issue description (what happened, and what was expected):**
If you load the attached project you will see that if you try to click on the quad in the 3D view, nothing happens. Alt + RMB also does not list the quad underneath the mouse cursor.

A similar thing happens with MeshInstance:

**Steps to reproduce:**
- add a mesh instance node to the scene and load "plane.msh" (included in the project dir)
- the transform gizmo will be visible
- if you unselect the object by clicking somewhere else, the object is no longer selectable via the 3D view
- if you add another object, try a TestCube node for example, the MeshInstance is now selectable via the 3D view. Despite this, Quads are still not selectable.

These may be unrelated, but I thought I'd mention them both here since they are similar and I suspect they might stem from the same thing.

Here's the project: https://dl.dropboxusercontent.com/u/3292249/quad_select.zip
(still can't attach zip files for some reason?)

**Comment by Chaosus** [comment] 2018-09-17 15:31
Its not only about Quads, other type of meshes is affected too(the problem still exist 3.1). If you create any new MeshInstance it will register clicks only after first selection in Scene tree

**Comment by akien-mga** [comment] 2018-12-14 17:15
CC @JFonS

**Comment by JFonS** [comment] 2019-01-31 14:55
Can't reproduce anymore, closing this issue. If you can still reproduce, leave a comment and we can reopen it.

**Closed by JFonS** 2019-01-31 14:55 UTC
Labels: bug, confirmed, topic:editor
