### ISSUE TITLE
Error when using AnimationPlayer after adding a RESET track

### ISSUE THREAD

**Issue by JohnDevlopment** [godotengine/godot#51485] opened 2021-08-11 00:38 UTC
### Godot version

3.4-beta3

### System information

Linux Mint 19.3 Tricia

### Issue description

I recently started using the new Godot 3.4 beta3 build. After I added a reset track to one of my animations, I started getting a strange error in the console: "Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead."

The error pops up in my "dark beast" scene whenever I switch to its tab, and when I run the scene with either F5 or F6.

The scene in question has an attached tool script.

I've narrowed down the issue to be with the AnimationPlayer, and specifically the RESET track, because when I removed said track, the error no longer happened.

### Steps to reproduce

Open the project and switch to the "dark beast" scene (which should be the main scene). The error will show up without fail on the listed build. Also run the scene and the error should pop up on the console.

EDIT: I should have mentioned this, but I manually added a track and named it "RESET". I don't know if this detail is important, but the editor recognized it as a RESET track all the same.

### Minimal reproduction project

Zip file: 
[kevin.zip](https://github.com/godotengine/godot/files/6965131/kevin.zip)

**Comment by fire** [comment] 2021-08-11 08:47
I don't think my RESET bake was merged, so to find out this happens need to bisect.

**Comment by akien-mga** [comment] 2021-08-11 08:49
> I don't think my RESET bake was merged, so to find out this happens need to bisect.

That's right, so this likely comes from the original implementation of the RESET track.

**Comment by RandomShaper** [comment] 2021-08-11 10:21
Can't reproduce on a418d09617cb1aa5bfc986a2b1d89a9db7e2f05a.

**Comment by fire** [comment] 2021-08-12 17:41
@JohnDevlopment Can you try your test cases again and report back for the RESET track failure?

**Comment by snougo** [comment] 2021-08-12 21:45
I tried the project and didn't get any error

**Comment by RandomShaper** [comment] 2021-08-12 21:55
Maybe the MRP needs to be a thicker slice of the original project.

**Comment by JohnDevlopment** [comment] 2021-08-13 00:52
I opened the MRP and suddenly I wasn't getting the error anymore. And I opened the original project and didn't get the error there either. So, my report is that the error disappeared. It's weird because I didn't update Godot or build a version based on #a418d09 or newer. And I haven't figure out yet what caused the error to go away.

**Closed** 2021-08-19 15:55 UTC
Labels: bug, topic:editor, topic:animation
