### ISSUE TITLE
Vector2 angle_to method does not return exactly PI when it should.

### ISSUE THREAD

**Issue by Diaspater** [godotengine/godot#25452] opened 2019-01-29 04:55 UTC
**Godot version:**

v3.1.beta1.official

**OS/device including version:**

Windows 10

**Issue description:**

The angle_to function for two opposite Vector2s does not return exactly PI. After performing the example code, I never reached the "do stuff" section do to the angle not being exactly equal to PI when it should as 180 degrees should be equal to PI. This is probably due to some floating point error but I have not yet determined the exact cause of it yet.

**Steps to reproduce:**
```
var vector1= Vector2(1,0)
var vector2= Vector2(-1,0)
var angle  = vector1.angle_to(vector2)
if angle == PI : 
    #Do Stuff
    pass
```

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2019-01-29 06:18
Note ``PI`` in Godot is not equal to 3.141593 it is equal to: 
https://github.com/godotengine/godot/blob/f32c8269241ea5f293b3eda2f9dbe01ffb6f7397/core/math/math_defs.h#L43

**Comment by Chaosus** [comment] 2019-01-29 07:55
> if angle == PI :

This is incorrect comparsion - float numbers should be compared with defined precision(tolerance) so it should be

abs(value1 - value2) < tolerance

**Comment by Chaosus** [comment] 2019-01-29 08:04
Further #18992 should fix this issue by introducing comparsion method. I close this issue - its just caused by incorrect usage.

**Closed by Chaosus** 2019-01-29 08:04 UTC

**Comment by Diaspater** [comment] 2019-01-29 11:05
Thank you for the explanation on why the comparison was failing from a technical standpoint and also providing an example of a better way to compare floats for nearly identical results.
