### ISSUE TITLE
Application renders too small on Mac with Retina Display

### ISSUE THREAD

**Issue by ariromano** [godotengine/godot#25501] opened 2019-01-31 04:32 UTC
**Godot version:**
3.06.stable.official.8314054

**OS/device including version:**
MacOS 10.14.2
OpenGL ES 3.0 Renderer: AMD Radeon Pro Vega 64 OpenGL Engine

**Issue description:**
After playing a simple empty "game" on a retina display, the resulting window flickers red and only shows the game in a corner.

<img width="1136" alt="screen shot 2019-01-30 at 8 20 36 pm" src="https://user-images.githubusercontent.com/9257572/52030845-87b28f80-24ce-11e9-90ab-103aa14c886d.png">

**Steps to reproduce:**
open project on a Mac with retina display (tried on 2017 iMac Pro and 2017 13" MacBook Pro)
[test.zip](https://github.com/godotengine/godot/files/2815685/test.zip)
click play button
→ the resulting window contains 1/4 game, the rest is double buffering flickering between red and grey every frame.

expected behavior: game renders into full window. (either the window is 1/4 of the size or the contents get upscaled)

If "enable HiDPi" is set in the project settings, it works.

**Minimal reproduction project:**
attached. it's really just an empty project.

**Comment by groud** [comment] 2019-01-31 09:55
Duplicate of #21416

**Comment by groud** [comment] 2019-01-31 09:56
Or maybe not, let's keep ip open, the other issue does not describe a red screen

**Closed** 2019-02-08 10:06 UTC
Labels: bug, platform:osx, topic:rendering
