### ISSUE TITLE
Typed array in parameter on RPC causes type error.

### ISSUE THREAD

**Issue by tmff** [godotengine/godot#90599] opened 2024-04-12 23:16 UTC
### Tested versions

- Reproducable in 4.3dev4, 4.2.1

### System information

Godot v4.3.dev4 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3758) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When calling an RPC that has a parameter with type Array[Vector2i], it will error as it cannot convert the argument from array to array. This seems incorrect as the types are the same and works when just using the Array type, but I might be misunderstanding how RPCs work.

### Steps to reproduce

Have 2 instances running, one as client and one as host. On host press the type bug button and it will throw an error.

### Minimal reproduction project (MRP)

[BugTesting.zip](https://github.com/godotengine/godot/files/14964428/BugTesting.zip)

**Comment by dalexeev** [comment] 2024-04-13 06:45
* Duplicate of #69215.
* Fixed by #78219 for future 4.3.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-04-13 06:45 UTC
