### ISSUE TITLE
Godot crashes while adding CollisionShape2D to CharacterBody2D

### ISSUE THREAD

**Issue by mike2ykme** [godotengine/godot#76799] opened 2023-05-07 04:37 UTC
### Godot version

4.0.3 RC1

### System information

OS: Pop OS LTS 22.04; GPU: Nvidia 4050; Intel i7

### Issue description

I was trying to add a CollisionShape2D to a Node2D and it continually crashes on 4.0.3 RC1. I have not had an issue when using 4.0.2
[Screencast from 05-06-2023 11:22:18 PM.webm](https://user-images.githubusercontent.com/10487582/236657671-94473216-3230-4c35-b9a6-8f87a79d11eb.webm)

### Steps to reproduce

Try and attach Collision shape 2d to a Node 2D

### Minimal reproduction project

Create a new project
Create new Node2D
Add Child node collision shape 2D to Node2D

**Comment by AThousandShips** [comment] 2023-05-07 06:35
Are you adding it to a `CharacterBody2D` or to a `Node2D`?

**Comment by Rindbee** [comment] 2023-05-07 09:39
Duplicate of #76543.

**Comment by KoBeWi** [comment] 2023-05-07 17:07
Closing as duplicate.

**Closed by KoBeWi** 2023-05-07 17:07 UTC
