### ISSUE TITLE
Scaled 2D Skeletal Deformation Mesh is wrong

### ISSUE THREAD

**Issue by bitbotzgames** [godotengine/godot#48380] opened 2021-05-02 09:52 UTC
Godot version: 3.3

OS/device including version: Windows 10 Version 20H2, GLES2 & GLES3,  geforce gtx 1660

Issue description:
When using a scaled Polygon2D with a Skeleton2D wich has animated Bones2D the animation is wrong.

It works as expected in Godot 3.2.3 ...
![3 2 3](https://user-images.githubusercontent.com/83534976/116808958-0e39f980-ab3c-11eb-8b73-bd396e028812.gif)

... but not in 3.2
![3 3](https://user-images.githubusercontent.com/83534976/116808994-43dee280-ab3c-11eb-8f21-60ce9c6eec8f.gif)

Steps to reproduce:
Download the project and test it in 3.3 to see the bug. 3.2.3 should work as expected.

Minimal reproduction project:
[Skeletal Deformation Bug.zip](https://github.com/godotengine/godot/files/6411088/Skeletal.Deformation.Bug.zip)

**Comment by lawnjelly** [comment] 2021-05-02 12:26
May well be a duplicate of #48348 (haven't tested yet). I'll be looking at these bugs soon (just have to finish delta smoothing).

**Comment by lawnjelly** [comment] 2021-05-03 11:49
Yes can confirm this is a duplicate, same fix.

**Closed by lawnjelly** 2021-05-03 11:49 UTC
Labels: bug, regression, topic:2d, topic:rendering
