### ISSUE TITLE
ClassDB cannot find/does not include custom classes

### ISSUE THREAD

**Issue by Structed** [godotengine/godot#71744] opened 2023-01-20 16:38 UTC
### Godot version

v4.0.beta13.official [caacade56]

### System information

Windows 10 22H2

### Issue description

The [`ClassDB`](https://docs.godotengine.org/en/latest/classes/class_classdb.html) class in Godot 4 (Beta 13) seems to not include custom classes.
`ClassDB` seems to now be the only way to get and instantiate classes. Previously, one could use `ProjectSettings.get_setting("_global_script_classes")`.

For my addon, I want to be able to instantiate classes on the fly by a given string.

### Steps to reproduce

When I build a custom class, I want to be able to instantiate it via the ClassDB.

In Godot 3.5, I would do something like this:

```gdscript
func get_class_instance(name: String):
	var classes = ProjectSettings.get_setting("_global_script_classes")
	for element in classes:
		if element["class"] == name:
			return load(element["path"]).new()


	push_error("Class \"" + name + "\" could not be found")
	return null
```

The same function in Godot 4, to my best knowledge, would be like this. I also added some debugging with the variables `has` and `exists`:
```gdscript
func get_class_instance(name: String) -> RefCounted:
	var class_list = ClassDB.get_class_list()
	var has = class_list.has(name) # false
	var exists = ClassDB.class_exists(name) # false
	if ClassDB.can_instantiate(name):
		return ClassDB.instantiate(name)

	push_error("Class \"" + name + "\" could not be found")
	return null
```

When I look into `/.godot/global_script_class_cache.cfg`, my custom classes are there. But in the ClassDB, they can't be found or instantiated. They are not in the result of `ClassDB.get_class_list()`, nor does `ClassDB.class_exists()` return true. Also, these classes are (now obviously) not instantiable via `ClassDB.instantiate()

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/10468135/repro.zip)
I did include the `.godot/` directory to show that it the class cache does include the file.

**Comment by YuriSizov** [comment] 2023-01-20 16:58
> Previously, one could use `ProjectSettings.get_setting("_global_script_classes")`.

There is a documented workaround for the new structure, you can read the file in `.godot` now. There is also https://github.com/godotengine/godot/pull/71665 that will expose the list again, with proper API.

**Comment by Structed** [comment] 2023-01-20 17:07
Ah I see. From the first issue, where the move happene and the related docs update PRs, I got the impression that the new waywould be going through`ClassDB`. That would have been so much better than the old way!

**Comment by KoBeWi** [comment] 2023-02-04 16:05
Might be duplicate of #21789
ClassDB docs don't seem to mention custom classes anywhere, so it should be documented if it's a limitation.

**Comment by YuriSizov** [comment] 2023-02-04 16:09
> Might be duplicate of #21789

Well, not entirely. I think the issue here is related to your changes, and the ClassDB route was just an attempt to fix up the code according to the new system for caching global classes. But I agree, it would be worth to add a note that ClassDB doesn't work with them (and point to the new method, I guess).

**Comment by YuriSizov** [comment] 2023-02-05 12:57
The initial issue is resolved by https://github.com/godotengine/godot/pull/71665, you can use the new method now.

**Closed by YuriSizov** 2023-02-05 12:57 UTC
Labels: topic:core, documentation

**Comment by pewcworrell** [comment] 2025-04-23 19:09
Is there a feature request to add custom classes to the ClassDB or an explicit statement as to why ClassDB shouldn't have custom classes? It bothers me how many times I'm having to make work arounds for custom classes when a beautiful interface exists for built in classes. For example, if I want to have a list of all possible resources, I would like to use the following code:
```gdscript
var options: Array[String] = []
			for type: String in ClassDB.get_inheriters_from_class("Resource"):
				options.append(type)
```
However, this only provides the built in resource options. For custom classes, do I have to iterate everything in the ProjectSettings.get_global_class_list(), instantiate it, and walk up its inheritance chain to see if it inherits from Resource? 

There has to be another way right? The editor shows my custom classes alongside the base classes in the inspector when I have a Variant specified as an object.

**Comment by KoBeWi** [comment] 2025-04-23 20:08
> There has to be another way right? The editor shows my custom classes alongside the base classes in the inspector when I have a Variant specified as an object.

It does so using ScriptServer, which is not exposed to scripting.
