### ISSUE TITLE
On error, the editor is focused and the WASD keys are typed in the code

### ISSUE THREAD

**Issue by Omiod** [godotengine/godot#74041] opened 2023-02-27 11:26 UTC
### Godot version

4.0 rc5

### System information

Windows 10

### Issue description

On code error, the editor is focused and the WASD keys are typed.
The code editor shouldn't be focused in this case.

### Steps to reproduce

I'm testing the game, moving the character with the WASD keys.
If an error happens, the game goes in background and the editor is focused.
Because a movement keys is pressed, it gets written in the code.
Nine times out of ten I quickly edit the unwanted characters, but sometimes I don't notice it and in the next run I get an error.

Annoyingly, the error is not about the typo, but some more generic issue in another script.
For example something like "Parser Error: Could not resolve super class inheritance from "Bullet"." where that script is perfectly ok.

Thank you.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-02-27 16:56
> On code error, the editor is focused and the WASD keys are typed.
> The code editor shouldn't be focused in this case.

This is done by design, as many people have requested the ability to be able to immediately edit their code after encountering a script error.

**Comment by Omiod** [comment] 2023-02-27 18:19
I see.
Would be great to have an option to manually focus before writing code.
Thank you.

**Comment by Calinou** [comment] 2023-02-27 18:35
- Duplicate of https://github.com/godotengine/godot/issues/21812.

**Closed by Calinou** 2023-02-27 18:35 UTC
Labels: discussion, topic:editor
