### ISSUE TITLE
multiplayer.get_remote_sender_id() Why 0?

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#75818] opened 2023-04-08 11:30 UTC
### Godot version

4.0.2

### System information

win10

### Issue description

![image](https://user-images.githubusercontent.com/61361272/230718603-22122dab-57cd-48f4-bc2c-492363559831.png)

In RPC.

Server and client.
The server knows that the client is 919395789.
Why client RPC_ID 1.
Multiplayer.get_remote_sender_id () on the server.
It's a "0".

But its "rpc_id (sender id)" can interact with the corresponding client correctly.

Shouldn't the server return "919395789" with "multiplayer.get_remote_sender_id ()"?

### Steps to reproduce

1

### Minimal reproduction project

1

**Comment by zuiaiyangyang3** [comment] 2023-04-08 11:32
![222](https://user-images.githubusercontent.com/61361272/230718831-72347efe-2b8c-46fa-a2bd-0a83fe44e107.gif)

**Comment by mhilbrunner** [comment] 2023-05-18 07:05
Hey! Thanks for reporting. I could not reproduce this using Godot 4.0.2 on Windows 10 with this test function:
```js
@rpc("any_peer", "reliable", "call_remote")
func _test():
	var 中文假字生成器id = multiplayer.get_remote_sender_id()
	print("中文假字生成器id[%s]中文假字生成器id" % [中文假字生成器id])
```
(Do not mind the text, I copied the first result for "chinese lorem ipsum" from Google and hope it's inoffensive, I was trying to make sure it is not an encoding/GDScript parsing issue.)

That always reported `1` for the server and the peer ID `101626451` for the peer correctly.
`multiplayer.get_remote_sender_id()` should as far as I can tell only return 0 if called outside a RPC function or maybe if not connected.

Can you try to create a minimal reproduction project for your issue to post here?

**Comment by AThousandShips** [comment] 2023-05-18 07:35
(it just says "Chinese fake character generator" 😆)

**Comment by marcol1** [comment] 2023-08-19 22:30
possible that this is caused by just calling the RPC function directly, instead of through rpc(). can you check this is not the case?

**Comment by Faless** [comment] 2023-10-13 13:19
Closing as there is no reply, and this is likely caused by calling the function directly instead of via `.rpc()`, or it is the `call_local` path of the RPC itself.

**Closed by Faless** 2023-10-13 13:19 UTC
Labels: needs testing, topic:multiplayer
