### ISSUE TITLE
Viewport: Unable to use parent world as world_2d

### ISSUE THREAD

**Issue by puthre** [godotengine/godot#31856] opened 2019-09-01 10:06 UTC
3.1.1.stable.official

Ubuntu 18.04

I want to have a viewport that renders the same scene as the main viewport but with a different camera. If I try to set the world_2d of the viewport as the main world_2d
vp2.world_2d =  get_viewport().world_2d
I get:
WARNING: set_world_2d: Unable to use parent world as world_2d
   At: scene/main/viewport.cpp:963.

And it doesn't work. 

However if I remove this check from the code everything works smoothly.

Is there any reason for this check?

**Comment by Asaurus1** [comment] 2020-03-21 04:57
@puthre I am having the same issue as the OP, but I do not understand how your pull request would close this issue?

**Comment by puthre** [comment] 2020-03-21 08:41
@Asaurus1 it removes the check in  scene/main/viewport.cpp

**Comment by luislodosm** [comment] 2020-05-23 21:16
Same here.

```
var default_viewport = get_viewport()
other_viewport.world_2d = other_viewport.world_2d
```

W 0:00:00.469   set_world_2d: Unable to use parent world as world_2d
  <Fuente C++>  scene/main/viewport.cpp:1024 @ set_world_2d()

**Comment by Caligari** [comment] 2020-10-16 04:43
In 3.2.3.stable.official (Windows) I'm still seeing this issue - trying to set up a separate Camera2D to give another view on the same 2D world, and nothing shows up on-screen. Error reported is:

W 0:00:14.280   set_world_2d: Unable to use parent world as world_2d
  <C++ Source>  scene/main/viewport.cpp:1024 @ set_world_2d()

**Comment by DevAndreyBilchenko** [comment] 2021-01-24 16:07
same problem :(

**Comment by MikeFP** [comment] 2021-03-22 21:17
Maybe if we make a PR just to remove the check in `viewport.cpp`, it'll be easier to aprove it. 

That's gotta be an important use case. It's essential to put multiple 2d cameras rendering the same scene from different angles/positions, which is a pretty common use case IMO.

**Comment by ProPablo** [comment] 2021-07-11 05:57
Heya, thank god for open source, I compiled 3.3 and made the change, sure enough, it worked, not sure why the check is there (maybe to prevent recursive viewports), any word on the change? Happy to make my first pull request on commenting 3 lines but I feel its a bit ignorant without understanding what that check was trying to prevent

**Comment by Calinou** [comment] 2021-07-11 16:53
> Heya, thank god for open source, I compiled 3.3 and made the change, sure enough, it worked, not sure why the check is there (maybe to prevent recursive viewports), any word on the change? Happy to make my first pull request on commenting 3 lines but I feel its a bit ignorant without understanding what that check was trying to prevent

Feel free to open a pull request so we can discuss it there.

**Comment by BimDav** [comment] 2021-08-20 16:29
Let's revive this thread. I made the proposed PR.
The check was first introduced in https://github.com/godotengine/godot/commit/97cf3eba56f7f89b9a6b275c70e54e52303e25a7, maybe @Faless can shed some light on the subject ?

It would be cool to have in 2D the same structure as the example project for split screen: https://github.com/godotengine/godot-demo-projects/tree/master/viewport/dynamic_split_screen, which does not work now because of that check.

**Comment by BimDav** [comment] 2021-09-02 15:34
So I had time to test this further and it seems like it was a bad idea to remove that check, even though it may work in some cases.

I tested the splitscreen case from https://kidscancode.org/godot_recipes/2d/splitscreen_demo/, but adopted this structure
<img width="607" alt="viewports" src="https://user-images.githubusercontent.com/67792882/131873125-73d240dc-10b5-42ac-8ff2-101e0ff49703.PNG">

This results in some pretty wild artefacts: 
![viewport](https://user-images.githubusercontent.com/67792882/131873203-809a4ff9-f919-436a-a60c-d48285509fb9.gif)

Here is the project 
[splitscreen_start.zip](https://github.com/godotengine/godot/files/7100096/splitscreen_start.zip)

**Comment by BimDav** [comment] 2021-09-02 15:45
After checking https://github.com/godotengine/godot/pull/31877 I changed the type of the Viewports node to a CanvasLayer with layer = 1, and then it works as intended, because the viewports don't render what is inside the CanvasLayer and the recursion cycle is broken. 
So this check could be removed but users will have to know the proper technique. 

Or the full https://github.com/godotengine/godot/pull/31877 PR could be updated. I may be able to do it, but my C++ is pretty rusty, pun intended.

**Comment by Macksaur** [comment] 2021-09-02 18:21
I think the correct way to do this is with the full PR (and using layer masks). The check should be removed once layer masks are in.

Personally, I'm looking at fixing up #31877 and matching feature parity with 3D/Spatial, I'd really like it for some clean rendering effects. I am about done with fixing the issues I had with the original PR (UI/Inputs on child Viewports) and some missing functions. Just have to port it to 4.0... 😅 Hopefully I can make a PR once I've done that and rounded out the documentation etc.

**Comment by BimDav** [comment] 2021-09-03 08:30
I motivated myself to update #31877 yesterday, it was not so bad: https://github.com/godotengine/godot/pull/52350.
What issues did you have with the original PR ?

**Comment by Macksaur** [comment] 2021-09-03 17:58
Some missing functions on the gdscript side (I want to be able to do this without using nodes too), inability to nest viewports and take input properly and potentially unwanted differing behaviours vs Spatial node masking and CanvasItem masking. It's not terribly much different but I'm just fretting over getting it right. I have more time tonight to hopefully wrap it up. I've spent some time building a proper debug scene and trying to use the features in one of my projects to make sure I've gotten everything I'd need.

**Comment by photon-niko** [comment] 2022-08-24 12:08
a

why isn't this closed yet

**Comment by Calinou** [comment] 2022-08-24 14:29
> why isn't this closed yet

The issue is still relevant in both 3.x and `master` to my knowledge.

**Closed** 2022-11-02 16:40 UTC
Labels: bug, topic:core, confirmed, topic:2d
