### ISSUE TITLE
macOS self-contained mode is inoperative

### ISSUE THREAD

**Issue by LCHONE** [godotengine/godot#73424] opened 2023-02-16 10:21 UTC
### Godot version

4.0.rc 2 mono

### System information

Mac M1

### Issue description

I create an empty file called `_sc_` in Godot_mono.app/Contents/MacOS/, but the godot editor doesn't create editor_data folder, it uses ~/Library/Application Support/Godot/ to save editor data.

### Steps to reproduce

1.Download godot_mono 4.0 rc2 on M1
2.Create _sc_ file in Godot_mono.app/Contents/MacOS/
3.Open editor

### Minimal reproduction project

no

**Comment by akien-mga** [comment] 2023-02-16 10:27
Duplicate of #73081

**Comment by LCHONE** [comment] 2023-02-16 10:38
Are these two issues the same? Is it a bug or feature?

**Comment by akien-mga** [comment] 2023-02-16 10:40
Can you list the contents of the `~/Library/Application Support/Godot/` folder? If there's more than `app_userdata`, then it might not be the same indeed.

**Comment by LCHONE** [comment] 2023-02-16 10:41
~/Library/Application Support/Godot/

**Comment by akien-mga** [comment] 2023-02-16 10:44
It's a different issue then.

Can you show the contents of your `Godot_mono.app`, and confirm that there's no `editor_data` folder created next to it?

**Comment by LCHONE** [comment] 2023-02-16 10:45
![image](https://user-images.githubusercontent.com/44140589/219343563-61e04582-58cb-4a3a-b899-226e493cd6f3.png)

**Comment by bruvzg** [comment] 2023-02-16 10:54
`_sc_` should be in the same folder as `Godot_mono.app`, not inside it. Bundle should be considered read only and not, and `Contents/MacOS/` can have executable files.

**Comment by LCHONE** [comment] 2023-02-16 11:13
But 3.5.1 version it works.
![image](https://user-images.githubusercontent.com/44140589/219349882-a59499b8-5dc5-4295-9503-ba0eb5a394b2.png)

**Comment by bruvzg** [comment] 2023-02-16 11:36
> I do this with 4.0 rc2, it doesn't work either.

It works if started from terminal, but not from Finder. Seems like a result of App Translocation done by Gatekeeper.

- It's incorrect to write self-contained mode data into a bundle, since it will damage the bundle signature, and in general the bundle might be in read only location.
- It's impossible to get a real bundle path, since Gatekeeper can relocate it randomly (at least on macOS 13.0).

So I guess self-contained mode is no longer supported on macOS (and probably will not be supported since there's no way to do it properly), docs should be updated to indicate it.

**Comment by LCHONE** [comment] 2023-02-16 13:22
> [macOS] Re-add support for the _sc_ inside app bundle. #73429

ok, thanks. 
I'd like to make two comments as a user: support _sc_ inside app bundle again and this feature can be switched on and off using the editor ui.

**Comment by akien-mga** [comment] 2023-03-07 07:48
This is likely "fixed" as far as macOS allows it to be with https://github.com/godotengine/godot/pull/73429#issuecomment-1434261545.

**Closed by akien-mga** 2023-03-07 07:48 UTC
Labels: bug, platform:macos, topic:editor, topic:porting
