### ISSUE TITLE
is_on_floor() doesn't work with _process(delta) and high FPS on trimesh collision

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#36009] opened 2020-02-08 09:22 UTC
**Godot version:**
3.2 Stable

**OS/device including version:**
Linux 5.5.2-arch1-1

**Issue description:**
If you use `is_on_floor()` and the kinematic body is on a on an uneven trimesh collision, `is_on_floor()` returns false, if you call `move_and_slide()` with `_process(delta)` AND you have high FPS.

**Steps to reproduce:**
1. Create a uneven mesh.
2. Give the mesh a trimesh collision.
3. Place a Kinematic body
4. Attach a [script](https://docs.godotengine.org/en/latest/tutorials/3d/fps_tutorial/part_one.html) to the Kinematic body 

5. Use `_process(delta)` instead of  _physics_process(delta) 
6. Disable VSYNC to make sure having high FPS

**Minimal reproduction project:**
https://github.com/JupiterRider/is_on_floor_issue

![Peek 2020-02-07 17-59](https://user-images.githubusercontent.com/60042618/74082710-e8b76080-4a5c-11ea-9599-3a619f0bdd32.gif)

**Comment by KoBeWi** [comment] 2020-02-08 12:22
Well, it's rather expected that you need to use physics methods inside `physics_process(delta)`.

**Comment by jamie-pate** [comment] 2020-02-10 16:25
Probably related? #35780

**Comment by Seel** [comment] 2020-02-11 17:13
> 
> 
> Well, it's rather expected that you need to use physics methods inside `physics_process(delta)`.

I use _process for the player because the camera scrolling and player movement is smoother when moving at 100+ fps. <_<

However the minimal reproduction project has me standing on_floor when standing still and only lifting off the ground when moving.

**Comment by Calinou** [comment] 2020-02-11 22:03
> I use _process for the player because the camera scrolling and player movement is smoother when moving at 100+ fps. :/

It's probably a better idea to use `_fixed_process()` with lawnjelly's [smoothing-addon](https://github.com/lawnjelly/smoothing-addon) for physics interpolation.

**Comment by KoBeWi** [comment] 2020-12-23 00:11
Closing, only do physic things in `physics_process`, otherwise the behavior is undefined (it might work or it might break).

**Closed by KoBeWi** 2020-12-23 00:11 UTC
Labels: bug, topic:physics
