### ISSUE TITLE
Problem to unzip files from Godot 3.6-

### ISSUE THREAD

**Issue by Firty** [godotengine/godot#80660] opened 2023-08-15 15:01 UTC
### Godot version

4.1.1-Stable

### System information

Windows 10

### Issue description

I'm having trouble opening files generated by Godot 3.6 in Godot 4.1. When converting a project I ran into this hurdle.
FileAccess.open_compressed(a,FileAccess.READ,FileAccess.COMPRESSION_ZSTD) returns 15.

bytes_to_var(File.get_buffer(File.get_length()).decompress(BI,CP))
Which is the inverse of (in Godot 3.6):
var t0:PoolByteArray = var2bytes(data)
var t1:PoolByteArray = t0.compress(CP)
File.store_buffer(t1)

Returns:
[X: (0, 282985740871592310000, 0), Y: (0, 18968164584483854000000000000000, 0), Z: (0, 0, 0), O: (1131311474376118900000, 1841289165 7350839000000000000000, 220411264)]
A Traform3D that has nothing to do with the original file.
CP == 2
BI == 128000000

### Steps to reproduce

In Godot 3.6 bytes2var(Arquivo.get_buffer(Arquivo.get_len()).decompress(BI,CP)) works well...

I researched to see what the zstd difference is between 3.6 to 4.1 and noticed that they upgraded from version 1.5.2 to version 1.5.5. I say this because when the first stable version of Godot 4.0 came out and I started doing the migration, there was no such problem.

### Minimal reproduction project

https://drive.google.com/file/d/14dgtdRWVzm-i1OVCaRVjKwYmOMcEsVRJ/view?usp=sharing
An example file, generated by Godot 3.6 but not opening in 4.1

**Comment by AThousandShips** [comment] 2023-08-15 16:13
Duplicate of #73530

**Closed by AThousandShips** 2023-08-15 16:13 UTC

**Comment by Firty** [comment] 2023-08-15 17:24
Thanks for the clarification, I understand that for things to improve it is not always possible to maintain compatibility. But in my case, a file like that has 4 to 25 textures encapsulated along with the information, and currently there are more than 2300 files like that hehehe, yes I am a crazy person who used Godot to make a sales program for a knitting company, with the right to generate pdf and print kkkkkk I'll fix it, at least you pointed out the problem to me.
