### ISSUE TITLE
Control/Container types auto-resize bug

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#25005] opened 2019-01-15 08:35 UTC
**Godot version:** v3.1.beta1.official

**OS/device including version:** Ubuntu 18.10, Linux alienware 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Issue description:**
I'm adding nodes dynamically (objectives & rewards) for an RPG GUI type of thing and I'm experiencing this issue where the vertical size increases when adding these nodes.

**Steps to reproduce:**
It's a fairly complex Control nodes layout. The buggy version can be found here: https://github.com/razcore-art/godot-open-rpg/tree/controls_bug. As you can see, if you open up the game, the quests interface looks just fine, but if you run the game and play with selecting quests that appear in the lists on the left (be sure to go through all of them, in different orders), you'll see that the height of the buttons increases. Now it's not just the `<`/`>` buttons, it's just that the other nodes are invisible container nodes.

If you need anything explained about the code let me know.

**Minimal reproduction project:** https://github.com/razcore-art/godot-open-rpg/tree/controls_bug

**Comment by groud** [comment] 2019-01-15 10:47
Indeed, something looks like it is not updating. But it's going to be hard to debug with such a hug project. If you could create a minimal reproduction project, it might be feasible though.

**Comment by razcore-art** [comment] 2019-01-15 10:58
I'll try, I really haven't got the time these days and I'm not sure what triggers the bug so it will be difficult to put it together (time-wise). The project isn't complicated, it's just the layout that's complicated, it's easier to just show how stuff is wired.

`QuestManager.gd` reads a JSON file of Dictionary that holds other Dictionaries. For each sub-Dictionary it emits `quest_added` and `QuestSystem.gd` reroutes that to `GUI.gd`. `GUI.gd` just populates the lists on the left of the UI based on these quest Dictionaries.

When selecting an item from these lists (`QuestsList.gd`), they just emit the given quest Dictionary themselves which is caught by `QuestInfo.gd` in `_on_QuestsAF_quest_selected`. Withing `populate_objectives` & `populate_rewards` the problem occurs. They instantiate `ObjectiveItem.tscn`, `RewardItem.tscn` respectively and addes them under the appropriate `VBoxContainer` (`objectives` & `rewards` variables).

That's it and the problem happens with these last `VBoxContainer` nodes. But I tried many other node types and I think it's a generic `Container` node issue.

**Comment by razcore-art** [comment] 2019-01-25 00:04
Nope, problem still remains
![image](https://user-images.githubusercontent.com/1177508/51716478-979d2000-2045-11e9-9139-277172c45fa9.png)

**Comment by groud** [comment] 2019-01-31 10:50
Ok, so that's actually an expected behavior. In the hierarchy you are using a Panel instead of a Panel container. As a panel's size does not get updated according to its content (unlike the container version), the content goes out of the parent panel. 

Closing :)

**Closed by groud** 2019-01-31 10:50 UTC
Labels: bug, topic:core

**Comment by razcore-art** [comment] 2019-01-31 12:56
@groud, I just checked and it can't be that anyway, because those buttons are nested inside of a `HSplitContainer` which is a container.

I converted `Panel` to `PanelContainer` (and added `MarginContainer` for good measure too - in order to add margin to `HSplitContainer`) and I'm getting the same thing. Containers are pretty unstable in my experience.

![bug](https://user-images.githubusercontent.com/1177508/52055568-6bfbc780-2568-11e9-9ac4-8a4d0d012063.gif)

**Comment by groud** [comment] 2019-01-31 13:20
Ah indeed the basic container type does nothing. Might be made abstract.

**Comment by razcore-art** [comment] 2019-01-31 16:16
@groud I think would be better, it's a bit confusing at the moment. And I think it has to be emphasized in the docs that only (concrete) `Container` types manage the size of the children `Control` nodes. Because at the top there's also `Control` which as far as I understand behaves like the simple `Container`, it doesn't do anything.

**Comment by groud** [comment] 2019-01-31 16:37
Yeah, the general control nodes do not do anything regarding its children. Looks like the basic container does the same, that's why I consider making the Container class abstract, so that it cannot be used as is.

**Comment by cbrinck** [comment] 2021-04-10 19:57
I had a similar error with a simple calculator I wanted to make for a card game.
[ErrorCalc.zip](https://github.com/godotengine/godot/files/6290660/ErrorCalc.zip)

The windows keep changing their size to max, and eventually it got to the point where I couldn't even change a size attribute at all.

**Comment by Calinou** [comment] 2021-04-10 20:20
@cbrinck Please open a new issue for this, since this issue is quite old.

**Comment by cbrinck** [comment] 2021-04-10 23:00
I mean, I also "fixed" it by putting them inside a control node...
