### ISSUE TITLE
The value reset icon for scale and rotation does not appear.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#41793] opened 2020-09-05 18:38 UTC
**Godot version:**

3.2.3 RC5 mono

**OS/device including version:**

win10 64 home
nvidia gt440

**Issue description:**

The value reset icon for scale and rotation does not appear.
If you change the values like scale or rotation of a sprite node (for example) and later want to reset the size or angle to its original value, you will have to use the keyboard and enter the values.

![bug](https://user-images.githubusercontent.com/19652075/92311488-b7cde880-efb7-11ea-81fc-5e3627c459a0.gif)

**Steps to reproduce:**
Just add a sprite node, assign a chart to it, and change its scale or rotation.
You will notice that the reset icon does not appear.

**Minimal reproduction project:**

It is not necessary.

**Comment by Torguen** [comment] 2020-09-06 10:54
Here you can see that in a node of type "RichTextLabel" the icon does appear.
![bug](https://user-images.githubusercontent.com/19652075/92324225-0de66e80-f040-11ea-9736-fd976555685c.gif)

**Comment by aaronfranke** [comment] 2020-09-07 08:26
> **Steps to reproduce:**
> Just add a sprite node, assign a chart to it, and change its scale or rotation.

I don't know what you mean by "chart". I tried adding an image to the sprite node and I can't reproduce the issue in 3.2.3 rc5 mono:

![Screenshot from 2020-09-07 04-24-05](https://user-images.githubusercontent.com/1646875/92365651-1ed7c400-f0c2-11ea-9221-f5e06c40fa26.png)

> **Minimal reproduction project:**
> It is not necessary.

It is necessary.

**Comment by Torguen** [comment] 2020-09-07 09:14
It was mistranslated, I meant image.
I use translator to create my reports, although I check it, sometimes this happens, I don't have a high level of English.

Ok, now they do appear, I don't know why that could happen.
I will be attentive and if it happens again I will see what causes it.

**Comment by dreamsComeTrue** [comment] 2020-10-17 11:12
Is that still relevant then? If the issue no longer exist, possibly it can be closed, @akien-mga ?

**Comment by Torguen** [comment] 2020-10-17 11:34
I can't say, it happened to me that time but it hasn't happened again.

**Comment by dreamsComeTrue** [comment] 2020-10-17 11:37
Well, without reproducible project, and confirmation from the others - it's hard to track in that matter :/

**Comment by akien-mga** [comment] 2020-10-17 12:29
I can't reproduce either. The issue does seem valid given the GIF in the original post, so there might be cases where it happens. But until we can narrow it down, nothing can be done to solve it, so we might as well close it, and reopen if a way to reproduce it is found.

**Closed by akien-mga** 2020-10-17 12:29 UTC
Labels: bug, topic:editor
