### ISSUE TITLE
No Error Message when Vulkan is Unsupported on GPU on Ubuntu 20.04 (Editor Crash) 

### ISSUE THREAD

**Issue by ExquisiterEmil** [godotengine/godot#70676] opened 2022-12-28 19:20 UTC
### Godot version

4.0 beta 10

### System information

Ubuntu 20.0.4.1

### Issue description

When starting the engine and loading any project (also when creating a new one), the editor crashes before the loading is complete (while the Godot splash screen is shown). The console does not show any error, the crash occurs shortly after the blend file import warning. 

Even in `verbose` mode, I did not find any error.

I tried running almost all Godot 4 betas. Every one crashed on project load, some even sooner. Then I cloned Godot and compiled it. I tried to debug, with little success. The call stack shows that some Thread `llvmpipe-3` has a Segementation fault, but with "Unkown source", so I don't know where exactly it is coming from.

This can be related to #68043 or #59318, since I also get the error `/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath` on starting the launcher, but with the args `--audio-driver Dummy` the error disappears but the crash still occurs.

### Steps to reproduce

- Be daring enough to use Linux (Ubuntu 20.0.4)
- Download Godot 4 beta 10 and create new project
- Watch the Editor crash
- Become sad and go back to using Windows

### Minimal reproduction project

Any empty project

**Comment by Donn-Eddy** [comment] 2022-12-28 19:37
I am running Ubuntu 20.04.5 LTS.

Are you trying to run the Mono version?  Mine would crash using Mono and I had to run the binary in the terminal window to get the correct error message.  I was missing a directory or something, but chasing down that error message is what got the Mono version of Godot running for me.  I am running Godot Mono v4.0b10 just fine now,

**Comment by ExquisiterEmil** [comment] 2022-12-29 10:11
I think I fixed it. My graphics card does not support Vulkan, so running the engine with `--rendering-driver opengl3` lets the engine run, finally! Will update thread name accordingly.
(I found this out by installing Windows on another drive on this PC, where it then shows the error message)

**Comment by Calinou** [comment] 2022-12-29 19:59
Duplicate of https://github.com/godotengine/godot/issues/58927.

**Closed by Calinou** 2022-12-29 19:59 UTC
