### ISSUE TITLE
Videoplayer doesn't work on HTML5 (theora module disabled)

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#17495] opened 2018-03-13 20:06 UTC
Basically any ogv video file in a project using the videoplayer node will cause an error when exporting to HTML5, it will say something as file not found or similar. I will try to add more information later on but it's very easy to reproduce, just have a videoplayer node with a video file being played and export the project as HTML5, you will then notice how the error occurs and the video is not being played.

**Comment by Calinou** [comment] 2018-03-13 21:15
Browsers support decoding [Theora](https://caniuse.com/#feat=ogv) and [WebM](https://caniuse.com/#feat=webm) videos, however, Godot implements video decoding using libtheora and libvpx on native platforms (it can't be compiled into the WebAssembly module for performance and file size reasons).

I'm not sure if this can be done, considering that everything happening in the Godot viewport is not part of the DOM.

**Comment by samvila** [comment] 2018-03-13 21:17
So if I change my codec to Theora or WebM should work? If so I could still use the OGV file with the videoplayer node or should I do something different?

**Comment by Calinou** [comment] 2018-03-13 21:24
> So if I change my codec to Theora or WebM should work? If so I could still use the OGV file with the videoplayer node or should I do something different?

No, it won't work in any case on the WebAssembly platform.

**Comment by samvila** [comment] 2018-03-13 21:31
Is the same thing for Godot 3.x?

**Comment by reduz** [comment] 2018-03-13 21:46
I think those decoders have software fallbacks, specially theora.. are you
sure they shouldn't work?

On Mar 13, 2018 14:31, "samvila" <notifications@github.com> wrote:

Is the same thing for Godot 3.x?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/17495#issuecomment-372825544>,
or mute the thread

**Comment by eska014** [comment] 2018-03-13 23:07
Exporting VideoStreams doesn't work on any platform in 3.0
Closing as duplicate of #14954

**Comment by samvila** [comment] 2018-03-14 17:01
My report was meant for Godot 2.x, is there any duplicated for 2.x? Otherwise we should have this re-open. I think this problem should be fix in 2.x and not only in 3.x

**Comment by akien-mga** [comment] 2018-03-14 19:54
> My report was meant for Godot 2.x


That's why we have an issue template that asks prominently "**Godot version**"...

The theora module is not enabled on 2.1: https://github.com/godotengine/godot/blob/2.1/platform/javascript/detect.py#L33

**Comment by samvila** [comment] 2018-03-14 19:56
So shouldn't be open this ticket to do not forget about the 2.x version for this issue?

**Comment by akien-mga** [comment] 2018-03-14 20:04
Why not, one could try to enable building that module and see if it works on the javascript platform of 2.1.

**Comment by akien-mga** [comment] 2018-09-18 10:33
@samvila I built 2.1.5 export templates for HTML5 with the Theora module enabled, could you test them? https://github.com/GodotBuilder/godot-builds/releases/tag/2.1.5-js-theora

`godot.javascript.opt.zip` is the release template, `godot.javascript.debug.zip` the debug one.

**Comment by akien-mga** [comment] 2019-06-04 07:33
Fixed by 723c14cdfc1519e639d7927c72a25100fc606dc0.

**Closed by akien-mga** 2019-06-04 07:33 UTC
Labels: enhancement, platform:html5, topic:porting
