### ISSUE TITLE
GD Script: Dictionary shows as null in Stack Trace but is not null

### ISSUE THREAD

**Issue by thegemore** [godotengine/godot#83059] opened 2023-10-09 17:38 UTC
### Godot version

4.1

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

I have a dictionary that the IDE shows as null in Stack Trace, but is not null according to both the Remote -> Members inspection and according to how the code runs. The following screenshots show object ID 229461988902 and the dictionary nodeJoins being null in only ONE of the panels. Self is shown in the first screenshot to confirm i am looking at the same object

![image](https://github.com/godotengine/godot/assets/143091099/e0c0e025-a2f3-48e9-b57b-0cc241c7f504)
![image](https://github.com/godotengine/godot/assets/143091099/9b6ab838-4660-4a44-8b19-0de09c4bbd0a)

### Steps to reproduce

It appears to happen after several iterations (it is NOT occurring the first time line 122 is hit) but it does occur after 122 or 125 is hit a few times

![image](https://github.com/godotengine/godot/assets/143091099/5a83878b-15ee-4b40-ae9c-37c31f8c4160)

	if (dependantNode not in nodeJoins):
		nodeJoins[dependantNode] = {}

	if (prequisiteNode not in nodeJoins):
		nodeJoins[prequisiteNode] = {}

### Minimal reproduction project

Can provide full script/project if/as needed

**Comment by thegemore** [comment] 2023-10-09 17:39
To clarify reproducing steps - it seems to be the case that creating a dictionary and then adding dictionary values several times caused the IDE Stack Trace to read the original dictionary as null

**Comment by thegemore** [comment] 2023-10-09 17:45
![image](https://github.com/godotengine/godot/assets/143091099/1616be5f-8d62-4f42-84b6-b4e19ec3fe30)
Cleaner image that shows the issue. It has hit the breakpoint on line 23

**Comment by Zireael07** [comment] 2023-10-09 17:47
Duplicate of already reported issue - the debugger will show any value bigger than some size as null.
Arrays and Dictionaries will often cause this

**Comment by AThousandShips** [comment] 2023-10-09 18:09
Duplicate of https://github.com/godotengine/godot/issues/39465

**Closed by AThousandShips** 2023-10-09 18:09 UTC
