### ISSUE TITLE
VulkanContext::swap_buffers: Condition "err" is true. Returning: ERR_CANT_CREATE

### ISSUE THREAD

**Issue by doopt5** [godotengine/godot#71631] opened 2023-01-18 17:07 UTC
### Godot version

Godot_v4.0-beta13_win64

### System information

Windows 11, Intel(R) Core(TM) i5-1035G1 , Intel UHD Graphics 620, Driver Version 31.0.101.211, Vulkan 1.3.215

### Issue description

Every time I start up Godot 4 regardless of what beta version I use I receive the error bellow:

```
PS D:\> .\Godot_v4.0-beta13_win64.exe --verbose
PS D:\> Godot Engine v4.0.beta13.official.caacade56 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Text-to-Speech: SAPI initialized.
Using "winink" pen tablet driver...
OpenGL Renderer: Intel(R) UHD Graphics
WASAPI: Activated device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 32
WASAPI: min_period_frames = 96
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4045494686
EDITOR API HASH: 3529156112
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
Editing project: D:/Personal/War of the Gods
EditorSettings: Save OK!
Godot Engine v4.0.beta13.official.caacade56 - https://godotengine.org
TextServer: Added interface "Dummy"
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Orphan StringName: SceneMultiplayer
StringName: 1 unclaimed string names at exit.
Text-to-Speech: SAPI initialized.
Vulkan devices:
  #0: Intel Intel(R) UHD Graphics - Supported, Integrated
Vulkan API 1.3.215 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics
Optional extension VK_KHR_incremental_present not found
Optional extension VK_GOOGLE_display_timing not found
- Vulkan Variable Rate Shading supported:
  Pipeline fragment shading rate
- Vulkan multiview supported:
  max view count: 16
  max instances: 268435454
- Vulkan subgroup:
  size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD
  quad operations in all stages
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Using "winink" pen tablet driver...
Creating VMA small objects pool for memory type index 0
Shader 'CanvasSdfShaderRD' SHA256: 322fc7e4931383292913b506598f45ecc2830f603bb1b525d5a799c6d95f7882
Shader 'SkeletonShaderRD' SHA256: 7f4ee713ae80b4b097a099fc0f779ec86d848fdec356c671539e3a209ee8664e
Shader 'ParticlesShaderRD' SHA256: 701dae7ccc64ec686c6cd520f524c72df657bcd8a28ca5de4e418dd11946ceb5
Shader 'ParticlesCopyShaderRD' SHA256: 406d178ce67f7a3aba13cec12c0f4e23493163962be4bd88d8fb91eb67ea7a10
Shader 'CanvasShaderRD' SHA256: 518bad1d4517b4573fede0c452d8151ce27540d998d359cbdfb69468e7f61c16
Shader 'CanvasOcclusionShaderRD' SHA256: 8a20f3600eb76a11a47b2589fc8baa63bd1fe05ae738402118bd8853fe7c7177
Shader 'ClusterRenderShaderRD' SHA256: d4c7faec42c1ac031b883a3c6b9f87bb5611565d8b28627cb4184d7e54394dec
Shader 'ClusterStoreShaderRD' SHA256: 652e18dc2db88b573d30610e5f01f9272d00eb67b0e108636b3acbf131dda771
Shader 'ClusterDebugShaderRD' SHA256: 8a362aa1f8e655af4994994409bee4e84a4c9f10daa0cde89e87d649095c7e75
Shader 'SceneForwardClusteredShaderRD' SHA256: 9f8c3904e4919dbed2a5323110ec1ee51e1125793420bbaa1bff6298a8584a3d
Shader 'ResolveShaderRD' SHA256: b9528d87c4b39d8cea02db870c0c3d937a0f50751b8fe25f9dc7350a28c9a3fe
Shader 'TaaResolveShaderRD' SHA256: 2d158169338aab183f86ce7095d16bca54cbb781c30f265ed1876815a6c6fb63
Shader 'SsEffectsDownsampleShaderRD' SHA256: 79dca3f93f20130c08b84b8b2863d48e95769feb43ee1b20746ad5ae99c7a6fd
Shader 'SsilShaderRD' SHA256: 3da23f6734adef4a56537bb25302a31252019e961d83db9d75a37a4556252618
Shader 'SsilImportanceMapShaderRD' SHA256: c68ef0e83c30cc5492cf865e7202e2ebdd6aa4fb362bb815ce15638f6bfef41a
Shader 'SsilBlurShaderRD' SHA256: 385416b4a23e1ae276f7d797eae9150bffcb5ecfb94e44989752aaaed320070f
Shader 'SsilInterleaveShaderRD' SHA256: 67e0d970ae9fa49c0e69f0d0115db1285b0a28dd1092a70054cc7eb5158a65f7
Shader 'SsaoShaderRD' SHA256: a93422023fb9bbc4c4e5c9737710a5d147c5fc64f6796d847b41ea4e50179747
Shader 'SsaoImportanceMapShaderRD' SHA256: dff92d15321e0752486c6a37b2779eee3a9fb941ba2c4853b4083e4f052dbf1a
Shader 'SsaoBlurShaderRD' SHA256: d900d7fc95dfee8e993a9efd0726ca3b1f5d94df47c81094daacf169f27dad61
Shader 'SsaoInterleaveShaderRD' SHA256: 333ad55476b44db74ab47026be5e625c2bb1e84fbb88fc06a09085ee6708843c
Shader 'ScreenSpaceReflectionScaleShaderRD' SHA256: d4325fce3d9efed290b5fba96b5e6b71bbb37fc0229b9a132760c9c0c1676254
Shader 'ScreenSpaceReflectionShaderRD' SHA256: e0c87bf50148638794fc4bda6f373b3f696d1b33d4d0ffc119e1446544030299
Shader 'ScreenSpaceReflectionFilterShaderRD' SHA256: 20c53d40849e0b023cff504f78547d0da5e298be3b5f3663e5536c84c93e9b79
Shader 'SubsurfaceScatteringShaderRD' SHA256: 769a9ce682599c9dcb38a2253201835a1aa4882977b9a15ede729132e889a444
Shader 'SkyShaderRD' SHA256: fc14bef99e114f5634ce2aec54d69ec1255b65ebacccacae7141eb1c233fd317
Shader 'VoxelGiShaderRD' SHA256: 939c97646adbc4ffa5dc497d5e8da8e104361ab091066bd36af351729e51aa27
Shader 'VoxelGiDebugShaderRD' SHA256: 073fd873df8f9561d16d2ad01f3fe8ee7fa5bf6ccca44267a01d1c95e4405b80
Shader 'SdfgiPreprocessShaderRD' SHA256: 5bbf83265f79c28a98e2c6712256904129647283c588f9180f8f937c12594831
Shader 'SdfgiDirectLightShaderRD' SHA256: 6925b8ebb9b12bfcfa793e6d040823c7775cd60b0e3e707cf27f2a9cc80c14b3
Shader 'SdfgiIntegrateShaderRD' SHA256: 6b1849157e7d26e6b002b42c18f28875a19765f713c9c60856bf13e82e9ee176
Shader 'GiShaderRD' SHA256: c79d89aa233a0dd4d6b8285023ccd35b253de21f5a42753377390375487e1b52
Shader 'SdfgiDebugShaderRD' SHA256: 217e44bfe7beeef14bff5ec0fec22871f51dd2031b25c8a1a5be57c2c886805e
Shader 'SdfgiDebugProbesShaderRD' SHA256: f08ef14a682008770b7d6e3e8f1fe06c0faf5e7dc038bd5cdc0a09f8210380a1
Shader 'VolumetricFogShaderRD' SHA256: d4364faf6b2510d1c3106d2f51b4d2c9cfd32d77c8fd197a5abf0c3f6e416a4c
Shader 'VolumetricFogProcessShaderRD' SHA256: fe9edcfa99b10f19766eb535561d667caec3b1930009dcdf1b84a5161a295b3b
Shader 'BokehDofShaderRD' SHA256: b47db0a4fd3398552c8ca28ac9c3ab4e594cfba33540b7c79b690adccab87e49
Shader 'CopyShaderRD' SHA256: 7f61c608e9e2b5890c73514126c3202f6809ebe28754f0c73698dfcfdabea584
Shader 'CopyToFbShaderRD' SHA256: e512d0a65e137dafb9b8e6bf10985e33abc7d88525a6ef7ecf83a0f9d4339643
Shader 'CubeToDpShaderRD' SHA256: 327c9693386f5ac56925c3a4c6055cf35dd66609a1daeb8acf81498ebf4972ec
Shader 'CubemapDownsamplerShaderRD' SHA256: c35c045345b78d132f2e358878f28e38a0137a60d4e3eca15d87901a4924aade
Shader 'CubemapFilterShaderRD' SHA256: 9f04dd1f2f69daae7038944a739bfac2ac4f9cf6b6f4e03094382766029bdf0e
Shader 'CubemapRoughnessShaderRD' SHA256: b626842ae151b5a1daf8d2d4a6899ed45451d41f182e92a2e52a2ddf8aabb4cf
Shader 'SpecularMergeShaderRD' SHA256: 48263118edcdedaf9ad982502a4dc74b35f988bda00f2a2e18dac71d470ef664
Shader 'LuminanceReduceShaderRD' SHA256: 1bdc7fa0dfdea7ccb5a4ff6617dbe07979b0a79f5302a5fec9a85561ca5a3fc0
Shader 'TonemapShaderRD' SHA256: 56209f1fa07ab779886abfd70ccd48be05123d8a5ac6cfcfe37be4bb013ba5a4
Shader 'FsrUpscaleShaderRD' SHA256: 7ad07b4a03631cff29af34a7aaebe7e53d1b30768deea4d6855822d6e1360241
Shader 'RoughnessLimiterShaderRD' SHA256: caf2f417c8d62008625cf7d7f9e7fa31ec21d161b6e6e9df891fc34704ee94c8
Shader 'SortShaderRD' SHA256: 00737ddffcfdcc61b3587ecac1f603e7a84c03298021b29de474fc587962bf0e
Shader 'BlitShaderRD' SHA256: 09bcef8771de131e293141ae55cce4f1dd5ef390286f52b7b1184c16b34754d2
WASAPI: Activated device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 32
WASAPI: min_period_frames = 96
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms

Using present mode: VK_PRESENT_MODE_FIFO_KHR
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4045494686
EDITOR API HASH: 3529156112
Class 'EditorPropertyNameProcessor' is not exposed, skipping.
Class 'FramebufferCacheRD' is not exposed, skipping.
Class 'GDScriptEditorTranslationParserPlugin' is not exposed, skipping.
Class 'GDScriptNativeClass' is not exposed, skipping.
Class 'GodotPhysicsDirectSpaceState2D' is not exposed, skipping.
Class 'GodotPhysicsDirectSpaceState3D' is not exposed, skipping.
Class 'GodotPhysicsServer2D' is not exposed, skipping.
Class 'GodotPhysicsServer3D' is not exposed, skipping.
Class 'IPUnix' is not exposed, skipping.
Class 'MovieWriterMJPEG' is not exposed, skipping.
Class 'MovieWriterPNGWAV' is not exposed, skipping.
Class 'ResourceFormatImporterSaver' is not exposed, skipping.
Class 'ResourceImporterMP3' is not exposed, skipping.
Class 'ResourceImporterOggVorbis' is not exposed, skipping.
Class 'SceneCacheInterface' is not exposed, skipping.
Class 'SceneRPCInterface' is not exposed, skipping.
Class 'SceneReplicationInterface' is not exposed, skipping.
Class 'UniformSetCacheRD' is not exposed, skipping.
EditorSettings: Load OK!
Loaded builtin certs
Creating VMA small objects pool for memory type index 2
EditorSettings: Save OK!
```

### Steps to reproduce

Steps are unknown to reproduce.

### Minimal reproduction project

https://drive.google.com/file/d/1pbsfcPePUv-Ju8Bhpyo0rQ1vHYa5IjpA/view?usp=sharing

**Comment by akien-mga** [comment] 2023-01-18 17:17
There is no error in the logs you pasted in the issue. Where do you see the `VulkanContext` error?

**Comment by doopt5** [comment] 2023-01-25 17:25
> There is no error in the logs you pasted in the issue. Where do you see the `VulkanContext` error?

Godot Engine v4.0.beta13.official.caacade56 - https://godotengine.org
OpenGL Renderer: Intel(R) UHD Graphics

Editing project: D:/Personal/PokemonTG
Godot Engine v4.0.beta13.official.caacade56 - https://godotengine.org
Vulkan API 1.2.175 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics

WARNING: res://addons/godotsize/SizeMapWindow.tscn:3 - ext_resource, invalid UID: uid://c3neulsswfssf - using text pathg
     at: load (scene/resources/resource_format_text.cpp:452)
WARNING: res://addons/godotsize/SizeMapWindow.tscn:4 - ext_resource, invalid UID: uid://djjln8qyewx7n - using text pathg
     at: load (scene/resources/resource_format_text.cpp:452)
SCRIPT ERROR: Parse Error: Native class "FileAccess" cannot be constructed as it is abstract.
          at: GDScript::reload (res://Scripts/PalleteChanger.gd:23)
SCRIPT ERROR: Parse Error: Static function "new()" not found in base "FileAccess".
          at: GDScript::reload (res://Scripts/PalleteChanger.gd:23)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)

**Comment by clayjohn** [comment] 2023-01-25 17:31
Duplicate of https://github.com/godotengine/godot/issues/67404

**Closed by clayjohn** 2023-01-25 17:31 UTC
Labels: bug, platform:windows, topic:rendering
