### ISSUE TITLE
Wrong type is used when adding properties in Project Settings in 3.2 alpha

### ISSUE THREAD

**Issue by larryc5** [godotengine/godot#33502] opened 2019-11-09 23:14 UTC
**Godot version:**
Godot_v3.2-alpha2_win64

**OS/device including version:**
Windows 10/desktop

**Issue description:**
If you add a property in the Project Settings panel, the type that the property gets is different from what the Type option is set to. After fiddling around, I figured out the pattern:
* Type gets set to the type of one item above it in the dropdown.
* Setting it to `bool` doesn't create any property (since it's at the top of the dropdown I presume).
* Consequently, you can't use `PoolColorArray` since it's at the bottom of the dropdown.

**Steps to reproduce:**
1. Go to Project -> Project Settings -> General.
2. Create a property of any type.
3. See the pattern that is previously mentioned.

**Minimal reproduction project:**
Any project.

**Comment by akien-mga** [comment] 2019-11-09 23:20
Duplicate of #33075. You might want to update to 3.2 beta 1 :)

**Closed by akien-mga** 2019-11-09 23:20 UTC
