### ISSUE TITLE
Vulkan: Uniforms where never supplied for set (3) at the time of drawing, which are required by the pipeline

### ISSUE THREAD

**Issue by magarcan** [godotengine/godot#57374] opened 2022-01-28 22:56 UTC
### Godot version

4.0 dev

### System information

MacBook Air (M1)

### Issue description

<img width="1440" alt="Captura de pantalla 2022-01-28 a las 23 50 49" src="https://user-images.githubusercontent.com/1155927/151632627-d2b55df0-27c7-4e45-9f4b-3db6556f2b42.png">

### Steps to reproduce

Just modify 2D Gradient Texture 2D within the material.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7962324/Bug.zip)

**Comment by Calinou** [comment] 2022-01-28 23:12
Duplicate of https://github.com/godotengine/godot/issues/51361.

**Closed by Calinou** 2022-01-28 23:12 UTC
Labels: bug, platform:macos, topic:rendering

**Comment by akien-mga** [comment] 2022-01-28 23:21
> Duplicate of #51361.

I guess that depends on what @magarcan meant with:

> 4.0 dev

If it's 4.0 alpha 1, then the fix for #51361 is already included in theory.

**Comment by Calinou** [comment] 2022-01-28 23:39
> I guess that depends on what @magarcan meant with:

You can see the date at the bottom of the screenshot, it's `4.0.dev.20220105`.

**Comment by magarcan** [comment] 2022-01-29 08:19
Sorry, I thought it was alpha 1.
