### ISSUE TITLE
Workspace Autoswitch Sabotaging Animation Workflow

### ISSUE THREAD

**Issue by SimoneBruhn** [godotengine/godot#27096] opened 2019-03-15 14:57 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10, Geoforce GTX 860M - Driver Version 419.35

**Issue description:**
When inside the animation player, selecting a AnimatedSprite node causes the view to switch to AnimatedSprite, instead of simply marking it for the ability to animate it. To animate it I need to switch back to the AnimationPlayer. However if I deselect the node at any time, I need to repeat those steps;

Press node in list > Automatic switch to AnimatedSprite workspace > Switch back to AnimationPlayer > Don't missclick or accidentality select another node. 

It took me 25 minutes of fighting the very non intuitive editor/control engine design to animate something that should have taken only 2 minutes. A lot of time is being spent fighting the engine rather than being spent creating work.

**What should happen/Suggested fixes**
What should happen is that I should be able to smoothly select what node I want to animate from the nodes in the scene node list without switching the workspace. 

I suggest a modifier to be added that allows for marking/clicking/selecting a node from the scene node list without switching workspace. Like holding CTRL or ALT. Or some kind of option or setting that prevents the workspace from being automatically switched.

**Steps to reproduce:**
-Scene with overlapping AnimatedSprite nodes.
-AnimationPlayer
-Clicking the AnimatedSprites in the node list while in the AnimationPlayer workspace

**Comment by bojidar-bg** [comment] 2019-03-15 18:26
Second that. I'm having similar issues with the TextureRegion contextual editor popping up every now and then while navigating nodes in order to check their properties (because I hit a Sprite or similar node).

**Comment by MrBlockers** [comment] 2019-03-21 00:32
> Second that. I'm having similar issues with the TextureRegion contextual editor popping up every now and then while navigating nodes in order to check their properties (because I hit a Sprite or similar node).

I've found that the context swapping to TextureRegion occurs when you select a Sprite which is using a region of the texture (region_enabled = true). It certainly throws a wrench in the workflow. I'm new to the code base, so I'm having issues finding the check that swaps it, but I imagine it cant be much more complicated than an if statement.

**Comment by akien-mga** [comment] 2020-01-15 10:15
Duplicate of #27468.

**Closed by akien-mga** 2020-01-15 10:15 UTC
Labels: bug, topic:editor, usability
