### ISSUE TITLE
If a key is physically pressed and released very quickly then the engine internal state is that the key is not released and that it is still pressed.

### ISSUE THREAD

**Issue by ahibal** [godotengine/godot#31897] opened 2019-09-02 13:53 UTC
**Godot version:** Godot_v3.1.1-stable_x11.64 official

**OS/device including version:** debian Release 9 (stretch) 64-bit
Processor:AMD Athlon(tm) 64 X2 Dual Core Processor 6000+ × 2
Memory:2.9 GiB

**Issue description:** If a key is physically pressed and released very quickly, then the engine internal state is, that the key is not released and that it is still pressed.

**Steps to reproduce:** Quickly press and release a key that is used in script, as fast as you can.

**Minimal reproduction project:** https://github.com/ahibal/godot-earth-defender-game

**Comment by Calinou** [comment] 2019-09-02 15:26
Duplicate of #27104.

**Closed by Calinou** 2019-09-02 15:26 UTC
