### ISSUE TITLE
GDScript huge performance drop on func with a return

### ISSUE THREAD

**Issue by NaejDoree** [godotengine/godot#26602] opened 2019-03-04 17:49 UTC
**Godot version:**

3.0.6 stable

**OS/device including version:**

Windows 10.0.17763

**Issue description:**

Added a return valsue to a function in GDScript and got a huge perf drop

**Steps to reproduce:**

```
func move(dir):
	var nextMoving = []
	var cycles = 0
	var noCollision = true
	for elem in moving:
		var next = {}
		#compute next pos
		for key in elem:
			next[key + dir] = FULL
		#compute collisions
		if collisionCheck(next,grid):
			noCollision = false
			for key in elem:
				grid[key] = FULL
			#TODO: check cycle
			for key in elem:
				if(checkCycle(key)):
					cycles += 1
		else :
			nextMoving.append(next)
	moving = nextMoving
	if (moving.size() == 0):
		emit_signal("forceGeneration")

	emit_signal("updated",self)
	if cycles > 0:
		print("CYCLE !!!! " + str(cycles) + " CYCLES !!!")
		emit_signal("cycle",cycles)
		grid = {}
	#return noCollision
```
if you remove the comment on the return statement the function takes a lot more time to compute
full script can be found here : https://pastebin.com/JVYPtU88
I'll upload my source code once my game jam is over

**Minimal reproduction project:**

I'll upload my source code once my game jam is over and will make you this thing if i have the time

**Comment by vnen** [comment] 2020-01-09 18:29
Sorry for the delay on this. But without an actual reproduction project it's impossible to assess this. The script you posted doesn't seem to be CPU-intensive with or without the return statement, but it also doesn't really do much by itself.

I'll be preemptively closing this, since nobody else reported the issue in the meantime and the potential problem might have been fixed. If you can reproduce the issue, please comment with a reproduction project so we can test it.

**Closed by vnen** 2020-01-09 18:29 UTC
Labels: bug, topic:gdscript
