### ISSUE TITLE
Nonexisting function 'rpc' in base 'Callable' for C# RPCs

### ISSUE THREAD

**Issue by lolomap** [godotengine/godot#84149] opened 2023-10-29 16:18 UTC
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon(TM) RX Vega 10 Graphics (Advanced Micro Devices, Inc.; 31.0.14057.2005) - AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Exception "Nonexisting function 'rpc' in base 'Callable' for C# RPCs" appears on call rpc in GDScript, if Callable is method in C# script with Rpc attribute.

### Steps to reproduce

1. Create C# Node class with public method using [Rpc(MultiplayerApi.RpcMode.AnyPeer, CallLocal = true, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
2. Add it to Autoload as Global Variable
3. Try to call it inside GDScript like 
```Python
MyMonoClass.RpcMethod.rpc()
``` 

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-10-29 16:25
Related:
* https://github.com/godotengine/godot/issues/78545

Unsure what the support is for C#

**Comment by OverseeingDev** [comment] 2024-07-24 16:36
I can confirm I have this issue and it is annoying 😄

**Comment by AThousandShips** [comment] 2024-07-24 16:57
CC @raulsntos 

Is this an oversight or a limitation?

**Comment by raulsntos** [comment] 2024-07-25 00:57
The steps to reproduce seem to be calling `rpc` on a method from a C# script. AFAIK accessing a method from a C# script like that would call `CSharpInstance::get` which, for methods, should return a non-custom `Callable` so I think it should work.

https://github.com/godotengine/godot/blob/91eb688e178fe32f28aebfbec01137abefd75413/modules/mono/csharp_script.cpp#L1478-L1479

https://github.com/godotengine/godot/blob/91eb688e178fe32f28aebfbec01137abefd75413/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs#L102-L108

This is essentially the same as doing this in C++:

```C++
return Callable(object_id, SNAME("RpcMethod"));
```

If the C# method is annotated with the `[Rpc]` attribute as the steps to reproduce say, then the script's `rpc_config` should be populated as well. So I see nothing on the C# side that would prevent this from working but maybe I'm missing something.

**Comment by OverseeingDev** [comment] 2024-07-25 15:24
Hopefully this helps: 
As a workaround I am currently just doing 
`MyMonoClass.rpc("RpcMethod")`
which does work, event though
`MyMonoClass.RpcMethod.rpc()` doesn't

**Comment by raulsntos** [comment] 2024-07-26 12:12
I should have checked earlier, but I'm unable to reproduce in v4.3.rc1.mono.official [e343dbbcc]. Looks like it was fixed by https://github.com/godotengine/godot/pull/87858.

**Closed** 2024-07-26 12:21 UTC
Labels: bug, needs testing, topic:dotnet
