### ISSUE TITLE
Calling a singleton function doesn't show autocompletion in the editor

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#48624] opened 2021-05-10 20:47 UTC
**Godot version:**

3.3 stable

**OS/device including version:**

Windows 10 x64

**Issue description:**

When the user have a script and wants calls a function from this same script it shows the func description like this:
![image](https://user-images.githubusercontent.com/58845030/117722469-7bdacb00-b1b7-11eb-980b-3b58160305df.png)
But when you call a func from a Singleton, this hint doesnt show:
![image](https://user-images.githubusercontent.com/58845030/117722553-957c1280-b1b7-11eb-9283-2a9df9e18e25.png)

**Steps to reproduce:**
* Create a Singleton
* Create a Normal Script
* Create a function for this normal script
* in _ready call the created function
* there you should see a hint
* call a func from the created singleton
* you shouldnt see the func hint

**Minimal reproduction project:**

N/A

**Comment by Calinou** [comment] 2021-05-10 20:55
The script editor completion doesn't work if you have an error in your script. Fix the error and autocompletion should appear again.

**Comment by JestemStefan** [comment] 2021-05-14 07:28
I can confirm that there is no hint for scripts in Autoload. Example:
![obraz](https://user-images.githubusercontent.com/37214990/118236632-956d6280-b496-11eb-9648-b34c1ed3c6d9.png)

But for built-in like Engine it works:
![obraz](https://user-images.githubusercontent.com/37214990/118236394-4de6d680-b496-11eb-8def-ee591d3747bb.png)

**Comment by nonunknown** [comment] 2021-05-14 12:30
@Calinou There's another problem to, maybe I should open a proposal for that?

the case is that, what if the user wants to have a scene-only singleton? I mean at scene start he add_autoload_singleton() and at scene finish he calls remove_autoload_singleton(). The problem lies in, when the user call this "temporary" autoload from the scripts inside this scene, isnt possible!

**Comment by Calinou** [comment] 2021-05-14 12:42
> @Calinou There's another problem to, maybe I should open a proposal for that?
> 
> the case is that, what if the user wants to have a scene-only singleton? I mean at scene start he add_autoload_singleton() and at scene finish he calls remove_autoload_singleton(). The problem lies in, when the user call this "temporary" autoload from the scripts inside this scene, isnt possible!

I can't see too many use cases for a scene-only singleton. You can load a `.tscn` file in the Project Settings' AutoLoad section already.

**Comment by magikmw** [comment] 2021-11-29 15:24
Just a bit of cleanup (maybe?), related issues:
* #40537
* #22824

**Comment by hsandt** [comment] 2023-05-01 08:49
On Godot 4.0.2 I now can autocomplete methods called on singletons autoloaded _directly via their gd script_.
However, if the script is attached to a single-node scene, and that scene is set as autoload singleton, then the autocompletion **sometimes** doesn't work (Godot is not aware of the type of script attached to that node).

**EDIT** while writing this comment: after switching to .gd and back to autoload scene, autocompletion now works! I don't know if this is a hack or if Godot just took one minute to properly parse the singleton scene > script.
Anyway, I just added "sometimes" above and kept the rest of my message below in case it happens again.

Will need more testing and see if we can close the issue in both cases, or if there is really a permanent bug sometimes.

---

I considered strong-typing the node, but to do this you need to name your script with `class_name SingletonName`.
Unfortunately, when using the exact same name as the autoload singleton, you will get an error

> Class "GameManager" hides an autoload singleton.

which makes sense because you know have a redundant declaration (singleton class and singleton instance are not the same thing).

So you now need two names:

`class_name MySingletonClass`

and in autoload definition, you associate the Singleton.tscn to some name `MySingleton` or `MySingletonInstance` and cast `MySingletonInstance` to `MySingletonClass` to enable auto-complete, but it's not great.

**Comment by HolonProduction** [comment] 2023-11-26 13:16
Still valid in 4.x (completing the method does work, but the property hint is missing)

**Comment by Loufe** [comment] 2024-03-27 20:02
This is so bizarre. I wish it were consistent, but it's not.
In my photos below, all functions in the "Omni" singleton had function parameter hints working, yet none worked for the "DTools" singleton. I changed something in "DTools" and reloaded, now _neither_ of them. I have no idea.

**NOT WORKING**
![image](https://github.com/godotengine/godot/assets/5817861/d1c892da-caa2-4d0b-a735-e47a1d2a60f7)
![image](https://github.com/godotengine/godot/assets/5817861/b661a951-7c6d-4369-b5bf-66dedcb27c4f)

**WORKING**
![image](https://github.com/godotengine/godot/assets/5817861/6a51d5af-e7b9-4938-a85e-80db667e8f42)
![image](https://github.com/godotengine/godot/assets/5817861/a040d040-63a2-401f-a4a8-af211dfbdef6)

![image](https://github.com/godotengine/godot/assets/5817861/a0f1e3a5-3fb5-4aba-81ec-464d3914a73c)


If anyone could debug this it would be much appreciated, it's very frustrating and sounds like there are a multitude of issues regarding this problem. 

Qu'est-ce que t'en penses, @Calinou ?

**Comment by HolonProduction** [comment] 2024-03-29 10:28
As you might have seen, I submitted I fix, that I believe fixes the issue. Although I did not get inconsistent random behavior, but I could imagine that there are some situations, in which the type of the autoload might be resolved as class because of some caching mechanics :shrug:

If you have the capabilities, to compile the engine yourself, could you try applying my fix and tell us how it went?

If not, please try a recent dev built, as #85382 might have an influence as well

**Comment by HolonProduction** [comment] 2024-03-29 10:40
Also, the code that you showed, is it inside of either `Omni` or `DTools`?

**Comment by MayniYT** [comment] 2024-06-16 20:53
I'm wondering if this problem will be solved?

**Comment by HolonProduction** [comment] 2024-06-17 11:34
As long as you stick with GDScript, #87278 should have fixed it for 4.3. Feel free to try it in the recent beta.

**Closed** 2024-07-24 08:04 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
