### ISSUE TITLE
Throw warning in Script-Editor on changing array you currently loop

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#28711] opened 2019-05-05 19:55 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
When i (accidentally) remove an element from the array im currently looping over in a for loop, it just breaks the loop.

Here imo it would be better to throw a warning in the editor. Especially for new-comers, as this is something you might tend to do when you are not that experienced. 
The breaking of the loop for a new-comer is just behaviour that is hardly visible and difficult to find out without Debugging.

I know its a No-No in Programming to do that, but nothing is preventing you here from doing so.

**Steps to reproduce:**
Make array with elements
iterate over array,
delete element from array while looping

**Comment by Anutrix** [comment] 2019-07-06 18:57
I wonder if someone can implement something like ConcurrentModificationException for GDScript

**Comment by Reneator** [comment] 2019-07-06 21:04
@Anutrix Do you mean a compiler-exception or runtime-exception?

**Comment by Calinou** [comment] 2021-03-01 00:03
Duplicate of https://github.com/godotengine/godot/issues/32261 (same cause).

**Closed by Calinou** 2021-03-01 00:03 UTC
Labels: enhancement, topic:editor, topic:gdscript

**Comment by Anutrix** [comment] 2021-03-01 04:09
> 
> 
> @Anutrix Do you mean a compiler-exception or runtime-exception?

Both or either.
