### ISSUE TITLE
"Stretchy/Wide" Inspector bug.

### ISSUE THREAD

**Issue by CloudAlRio** [godotengine/godot#20166] opened 2018-07-15 05:10 UTC
**Godot version:** v3.1.dev.custom_build.f6ce73f

**OS/device including version:** Windows 10 x64 

**Issue description:** Inspector stretches horizontally beyond window. It doesn't matter where inspector is located.

![default](https://user-images.githubusercontent.com/7885573/42730805-3dfc349a-8839-11e8-9635-5c36658c25aa.png)

**Steps to reproduce:** 
1. Create Sprite
2. Add GradientTexture
3. Add Gradient
4. Add Material
Inspector will expand horizontally after this.
And after you select another node, inspector will (probably, it's not visible for me) corrrect itself, but editor will stay stretched out. You will need to resize window.
It seems to happen only with gradient texture

**Comment by groud** [comment] 2018-07-15 16:05
Duplicate of #18999

**Closed** 2018-07-15 16:05 UTC
Labels: archived
