### ISSUE TITLE
warning "Ignore" button not always clickable!!

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#25907] opened 2019-02-15 14:29 UTC
**Godot version:**
Last master version.

**OS/device including version:**
MacOS Mojave

**Issue description:**
I'm experiencing this because my screen isn't big enough the problem is if the warning occupies more than one line the "Ignore" button/link is not clickable.
Below there are some images that replicated what I'm trying to say:

<img width="656" alt="captura de ecra 2019-02-15 as 14 22 57" src="https://user-images.githubusercontent.com/10358443/52862725-d480a200-312d-11e9-83dd-85163439e1e5.png">

with a double line warning the ignore cannot be clicked (the mouse arrow does not appear in my print screen)... but it's a simple pointer arrow.

<img width="761" alt="captura de ecra 2019-02-15 as 14 23 05" src="https://user-images.githubusercontent.com/10358443/52862774-f67a2480-312d-11e9-8d28-4cb143c619c6.png">

if I expand the editor so to warning fits in one line the ignore can be clicked.

**Comment by justinluk** [comment] 2019-12-22 18:54
I've found that the ignore button isn't always clickable as well, even if the warning is only on one line. One work around I found is that if I click on another window on my desktop and then try to click 'Ignore' it works.

**Comment by RiverHeart** [comment] 2019-12-29 00:14
Godot v3.1.2 stable and Windows 10. Same issue.

Found the [relevant code ](https://github.com/godotengine/godot/blob/b3fac5ded0ba5878255cc93123b324ee737da41b/editor/plugins/script_text_editor.cpp#L645) but no idea what it's doing.

**Comment by Calinou** [comment] 2019-12-29 15:25
Duplicate of #21613 – the underlying cause is the same.

**Closed by Calinou** 2019-12-29 15:25 UTC
Labels: bug, topic:editor, usability
