### ISSUE TITLE
Rendering issue on Compatibily rendering on windows 11.

### ISSUE THREAD

**Issue by LimaneGaya** [godotengine/godot#82772] opened 2023-10-04 09:12 UTC
### Godot version

4.2.dev6

### System information

Windows 11 - Godot 4.2.dev6 - Compatibility

### Issue description

Rendering works fine on the editor but only shows black boxes when launching the game

### Steps to reproduce

setting up a simple scene and playing it.
![Capture d'écran 2023-10-04 100045](https://github.com/godotengine/godot/assets/36268750/6dba41a3-e810-4c04-aaca-c65a3563de65)
![Capture d'écran 2023-10-04 100113](https://github.com/godotengine/godot/assets/36268750/9560e93a-ebb9-4d8e-b802-203a6ca08d84)

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12801579/project.zip)

**Comment by Chaosus** [comment] 2023-10-04 09:25
I guess, you need to add the WorldEnvironment to a 3D scene, use 
![image](https://github.com/godotengine/godot/assets/3036176/2233c9b8-3d5a-4a53-8945-dbbad6f76b80)

**Comment by bitsawer** [comment] 2023-10-04 09:29
Looks like a duplicate of https://github.com/godotengine/godot/issues/82503, so closing to keep discussion in one place. Disabling the directional light shadow also helps until a proper fix is made.

**Closed by bitsawer** 2023-10-04 09:29 UTC
