### ISSUE TITLE
Random crashing on Arch Linux: xcb

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godotengine/godot#7713] opened 2017-02-03 09:18 UTC
Forenote: this issue was not encountered initially (with low usage, mind you), so might be caused by being on a rolling system, or it might be something done by Godot in an unstable/depreciated way.

OS: Arch Linux, most up-to-date system as of today (Feb 3, 2017).
libxcb 1.12-1 is what I have and the relevant library AFAICT
nVidia driver version 375.26 (graphics card is a GTX 1050 Ti)

Godot version: 2.1.2 stable
AUR version, 64-bit download, 32-bit download, Steam version.

Any project. Tried with multiple projects, sometimes they work and sometimes not.

Error:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
godot: xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

The result is commonly it successfully getting to the project manager, and crashing upon editing a project. Sometimes it will successfully open the project, and sometimes it will simply freeze (just the app, not my system). I've only had it happen once, but it has crashed before even reaching the project manager before.

______________________________________

Other notes:

When opening a project, 2 Godot splash screens appear (with the titlebar on the top full width), this happens in all cases.

Some of the example projects in steam crash mid-run with the same error (godot.x11.opt.tools.64: xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed). Happens in:

-  Window Management. Simply move the window or hit any of the built-in window controls.
-  GUI in 3D. Happens after a while (when using the spinbox?), the window will force mouse focus randomly and the mouse will disappear, tabbing out/between windows will eventually cause it.
- this also appeared when trying to run one of the sample projects (after having the xcb error with a different project) and having it crash immediately (not sure if relevant):

X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  0 ()
  Serial number of failed request:  219
  Current serial number in output stream:  219
X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  0 ()
  Serial number of failed request:  220
  Current serial number in output stream:  220

EDIT: Result of 'strace -e open,stat godot' : http://pastebin.com/dw86ZicG
EDIT2: Ran it again, the end is a little different:

godot: xcb_io.c:630: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=27580, si_uid=1000, si_status=SIGABRT, si_utime=14, si_stime=51} ---
open("/proc/sys/vm/overcommit_memory", O_RDONLY|O_CLOEXEC) = 3
+++ exited with 0 +++

**Comment by bojidar-bg** [comment] 2017-02-08 07:48
Can't reproduce on my end, at least with self-build 2.1.

**Comment by insomniacUNDERSCORElemon** [comment] 2017-02-12 15:28
As I've said, it seems to affect all Godot versions (including self built stable, packaged stable, and packaged alpha). I'm fairly sure it's related to the nvidia proprietary driver.

I've had updates to both the kernel and x.org server, neither has fixed it. Someone has also said that xcb hasn't been updated in a while, either.

**Comment by insomniacUNDERSCORElemon** [comment] 2017-02-16 18:30
As I suspected, this seems fixed as of nVidia driver version 378.13. This also fixed the crashes when running some of the demo projects in the Steam version.

This can be closed, but it might be worth testing with 375.26 on other systems to make sure it was not related to my system at all... and if not try comparing to working, seeing if something like this can be prevented in the future (or even why it was happening in the first place).

----------

Also worth noting: This driver release also fixed an issue with the game Unturned, which wouldn't start.

However, it DIDN'T fix a similar issue with Streets of Rogue, which will freak out (to the point of blackscreening the system after killed) if it's not in fullscreen mode.

**Comment by bojidar-bg** [comment] 2017-02-16 18:36
Ah, nVidia..... :laughing: 
I think I'll close it, it seems like something else broke it (xcb seems to be partly broken on my system too, giving badwindow errors all the time, but, like I care about it.... :smiley:).

**Closed by bojidar-bg** 2017-02-16 18:36 UTC
Labels: bug, needs testing, platform:linux
