### ISSUE TITLE
Vulkan `swap_chain_resize` error on Linux in dev branch

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#98811] opened 2024-11-04 09:47 UTC
### Tested versions

v4.4.dev.mono.gh-97745 [8936057ad]

### System information

Godot v4.4.dev.mono (8936057ad) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Nov 2024 20:51:49 +0000 on Wayland - Wayland display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 threads)

### Issue description

![图片](https://github.com/user-attachments/assets/2ba4c93e-558f-40e7-a4fc-f08cbc64d237)
```
ERROR: Condition "err != VK_SUCCESS" is true. Returning: ERR_CANT_CREATE
   at: swap_chain_resize (drivers/vulkan/rendering_device_driver_vulkan.cpp:3003)
```

### Steps to reproduce

Try editing a project rendered using vulkan.

### Minimal reproduction project (MRP)

N/A

**Comment by Delsin-Yu** [comment] 2024-11-04 09:51
You are using a version that belongs to your PR; maybe try to reproduce the issue in the main branch?

**Comment by scgm0** [comment] 2024-11-04 09:56
> You are using a version that belongs to your PR; maybe try to reproduce the issue in the main branch?

I am sure that this error has nothing to do with the content of my pr, It is a low-level error , The embedded window modified by my pr is higher level, but I will test the main branch later.

**Comment by scgm0** [comment] 2024-11-04 10:02
> You are using a version that belongs to your PR; maybe try to reproduce the issue in the main branch?

v4.4.dev.custom_build [1bffd6c73]
![图片](https://github.com/user-attachments/assets/4bb06d44-12cf-4081-8b49-d20b62c4f9cf)
This problem also reproduced in the main branch.

**Comment by Calinou** [comment] 2024-11-04 10:50
Can you reproduce this in 4.3.stable?

If you've updated your graphics drivers recently, make sure to reboot.

**Comment by scgm0** [comment] 2024-11-04 11:40
> Can you reproduce this in 4.3.stable?
> 
> If you've updated your graphics drivers recently, make sure to reboot. Also try forcing Godot to run on integrated graphics using `--gpu-index 1` on the [command line](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

4.3.stable does not have this problem.
![图片](https://github.com/user-attachments/assets/37d4f458-81ae-46f5-9f64-60cd07bc190c)

**Comment by akien-mga** [comment] 2024-11-04 11:48
Could you also try 4.4.dev3 to pinpoint if it's a recent regression, or one introduced already in earlier snapshots?

**Comment by scgm0** [comment] 2024-11-04 11:51
> Could you also try 4.4.dev3 to pinpoint if it's a recent regression, or one introduced already in earlier snapshots?

I have an editor built on October 22nd and it doesn't have this issue either

**Comment by DarioSamo** [comment] 2024-11-04 12:02
Any luck with this [PR](https://github.com/godotengine/godot/pull/98780)?

**Comment by DarioSamo** [comment] 2024-11-04 12:11
Can you also do regression testing with https://github.com/godotengine/godot/commit/aaa0e2fddfead4a31afddc07a26cd6af0c19dacd in particular?

**Comment by scgm0** [comment] 2024-11-04 12:14
> Any luck with this [PR](https://github.com/godotengine/godot/pull/98780)?

Used the #98780 build on github and no `swap_chain_resize` errors occurred.

**Comment by akien-mga** [comment] 2024-11-04 12:21
- Duplicate of #98779, consolidating there.

**Closed by akien-mga** 2024-11-04 12:21 UTC
Labels: bug, platform:linuxbsd, topic:rendering, regression
