### ISSUE TITLE
Cannot compile on windows

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#6180] opened 2016-08-17 09:07 UTC
**Operating system or device - Godot version:**
Windows 7 Enterprise SP1 32bits (Virtualbox) - Godot git build 56fa741b7a729bd5a00cff17e4382af547de92ad

Windows was freshly installed from MS Edge website (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
Tools were installed like in the documentation.

**Issue description** (what happened, and what was expected):
Error message during compilation:
core\object.h(329): error C2059: syntax error: 'constant'
core\object.h(332): error C2143: syntax error: missing ';' before '}'
core\object.h(332): error C2238: unexpected token(s) preceding ';'
core\object.h(348): error C2059: syntax error: 'private'
core\object.h(350): error C2255: 'friend': not allowed outside of a class defini
tion
core\object.h(352): error C2255: 'friend': not allowed outside of a class defini
tion
core\object.h(353): error C2255: 'friend': not allowed outside of a class defini
tion
core\object.h(402): error C2178: '_type_name' cannot be declared with 'mutable'
specifier
core\object.h(403): error C2178: '_type_ptr' cannot be declared with 'mutable' s
pecifier
core\object.h(406): error C2270: '_has_user_signal': modifiers not allowed on no
nmember functions
core\object.h(408): error C2270: '_get_signal_list': modifiers not allowed on no
nmember functions
core\object.h(409): error C2270: '_get_signal_connection_list': modifiers not al
lowed on nonmember functions
core\object.h(411): error C2270: '_get_bind': modifiers not allowed on nonmember
 functions
core\object.h(415): error C2059: syntax error: 'protected'
core\object.h(417): error C2270: '_use_builtin_script': modifiers not allowed on
 nonmember functions
core\object.h(418): error C2575: '_initialize_typev': only member functions and
bases can be virtual
core\object.h(418): error C3861: 'initialize_type': identifier not found
core\object.h(419): error C2575: '_setv': only member functions and bases can be
 virtual
core\object.h(420): error C2270: '_getv': modifiers not allowed on nonmember fun
ctions
core\object.h(421): error C2270: '_get_property_listv': modifiers not allowed on
 nonmember functions
core\object.h(422): error C2575: '_notificationv': only member functions and bas
es can be virtual
core\object.h(427): error C2270: '_get': modifiers not allowed on nonmember func
tions
core\object.h(428): error C2270: '_get_property_list': modifiers not allowed on
nonmember functions
core\object.h(432): error C2039: '_bind_methods': is not a member of 'Object'
core\object.h(324): note: see declaration of 'Object'
core\object.h(434): error C2270: '_get_get': modifiers not allowed on nonmember
functions
core\object.h(435): error C2039: '_get': is not a member of 'Object'
core\object.h(324): note: see declaration of 'Object'
core\object.h(435): error C2440: 'return': cannot convert from 'bool (__cdecl *)
(const StringName &,Variant &)' to 'bool (__thiscall Object::* )(const StringNam
e &,Variant &) const'
core\object.h(435): note: There is no context in which this conversion is possib
le
core\object.h(437): error C2270: '_get_set': modifiers not allowed on nonmember
functions
core\object.h(438): error C2039: '_set': is not a member of 'Object'
core\object.h(324): note: see declaration of 'Object'
core\object.h(438): error C2440: 'return': cannot convert from 'bool (__cdecl *)
(const StringName &,const Variant &)' to 'bool (__thiscall Object::* )(const Str
ingName &,const Variant &)'
core\object.h(438): note: There is no context in which this conversion is possib
le
core\object.h(440): error C2270: '_get_get_property_list': modifiers not allowed
 on nonmember functions
core\object.h(441): error C2039: '_get_property_list': is not a member of 'Objec
t'
core\object.h(324): note: see declaration of 'Object'
core\object.h(441): error C2440: 'return': cannot convert from 'void (__cdecl *)
(List<PropertyInfo,DefaultAllocator> *)' to 'void (__thiscall Object::* )(List<P
ropertyInfo,DefaultAllocator> *) const'
core\object.h(441): note: There is no context in which this conversion is possib
le
core\object.h(443): error C2270: '_get_notification': modifiers not allowed on n
onmember functions
core\object.h(444): error C2039: '_notification': is not a member of 'Object'
core\object.h(324): note: see declaration of 'Object'
core\object.h(444): error C2440: 'return': cannot convert from 'void (__cdecl *)
(int)' to 'void (__thiscall Object::* )(int)'
core\object.h(444): note: There is no context in which this conversion is possib
le
core\object.h(452): error C2575: '_changed_callback': only member functions and
bases can be virtual
core\object.h(461): error C2270: '_get_type_namev': modifiers not allowed on non
member functions
core\object.h(463): error C3861: 'get_type_static': identifier not found
core\object.h(467): error C2270: '_get_meta_list_bind': modifiers not allowed on
 nonmember functions
core\object.h(468): error C2270: '_get_property_list_bind': modifiers not allowe
d on nonmember functions
core\object.h(469): error C2270: '_get_method_list_bind': modifiers not allowed
on nonmember functions
core\object.h(473): error C2255: 'friend': not allowed outside of a class defini
tion
core\object.h(474): error C2270: '_validate_property': modifiers not allowed on
nonmember functions
core\object.h(476): error C2059: syntax error: 'public'
core\object.h(480): error C2059: syntax error: 'public'
core\object.h(492): error C2270: '_is_gpl_reversed': modifiers not allowed on no
nmember functions
core\object.h(494): error C2270: 'get_instance_ID': modifiers not allowed on non
member functions
core\object.h(528): error C2270: 'cast_to': modifiers not allowed on nonmember f
unctions
core\object.h(544): error C2270: 'get_type': modifiers not allowed on nonmember
functions
core\object.h(545): error C2270: 'get_save_type': modifiers not allowed on nonme
mber functions
core\object.h(549): error C2270: 'is_type': modifiers not allowed on nonmember f
unctions
core\object.h(550): error C2270: 'is_type_ptr': modifiers not allowed on nonmemb
er functions
core\object.h(552): error C2270: 'get_type_name': modifiers not allowed on nonme
mber functions
core\object.h(565): error C2270: 'get': modifiers not allowed on nonmember funct
ions
core\object.h(567): error C2270: 'get_property_list': modifiers not allowed on n
onmember functions
core\object.h(569): error C2270: 'has_method': modifiers not allowed on nonmembe
r functions
core\object.h(570): error C2270: 'get_method_list': modifiers not allowed on non
member functions
core\object.h(572): error C2575: 'call': only member functions and bases can be
virtual
core\object.h(573): error C2575: 'call_multilevel': only member functions and ba
ses can be virtual
core\object.h(574): error C2575: 'call_multilevel_reversed': only member functio
ns and bases can be virtual
core\object.h(581): error C2270: 'getvar': modifiers not allowed on nonmember fu
nctions
core\object.h(582): error C2575: 'setvar': only member functions and bases can b
e virtual
core\object.h(587): error C2270: 'get_script': modifiers not allowed on nonmembe
r functions
core\object.h(591): error C2270: 'has_meta': modifiers not allowed on nonmember
functions
core\object.h(593): error C2270: 'get_meta': modifiers not allowed on nonmember
functions
core\object.h(594): error C2270: 'get_meta_list': modifiers not allowed on nonme
mber functions
core\object.h(603): error C2270: 'get_script_instance': modifiers not allowed on
 nonmember functions
core\object.h(609): error C2270: 'get_signal_list': modifiers not allowed on non
member functions
core\object.h(610): error C2270: 'get_signal_connection_list': modifiers not all
owed on nonmember functions
core\object.h(611): error C2270: 'get_all_signal_connections': modifiers not all
owed on nonmember functions
core\object.h(612): error C2270: 'has_persistent_signal_connections': modifiers
not allowed on nonmember functions
core\object.h(613): error C2270: 'get_signals_connected_to_this': modifiers not
allowed on nonmember functions
core\object.h(617): error C2270: 'is_connected': modifiers not allowed on nonmem
ber functions
core\object.h(622): error C2270: 'is_blocking_signals': modifiers not allowed on
 nonmember functions
core\object.h(624): error C2270: 'get_static_property_type': modifiers not allow
ed on nonmember functions
core\object.h(626): error C2270: 'get_translatable_strings': modifiers not allow
ed on nonmember functions
core\object.h(628): error C2270: 'get_argument_options': modifiers not allowed o
n nonmember functions
core\object.h(630): error C2270: 'XL_MESSAGE': modifiers not allowed on nonmembe
r functions
core\object.h(631): error C2270: 'tr': modifiers not allowed on nonmember functi
ons
core\object.h(634): error C2270: 'is_queued_for_deletion': modifiers not allowed
 on nonmember functions
core\object.h(637): error C2270: 'can_translate_messages': modifiers not allowed
 on nonmember functions
core\object.h(641): error C2059: syntax error: ')'
core\object.h(642): error C2588: '::~Object': illegal global destructor
core\object.h(642): error C2575: 'Object': only member functions and bases can b
e virtual
core\object.h(642): error C4430: missing type specifier - int assumed. Note: C++
 does not support default-int
core\object.h(644): error C2059: syntax error: '}'
core\object.h(644): error C2143: syntax error: missing ';' before '}'
core\object.h(647): error C2065: 'p_object': undeclared identifier
core\object.h(647): error C2365: 'predelete_handler': redefinition; previous def
inition was 'function'
core\object.h(648): error C2065: 'p_object': undeclared identifier
core\object.h(648): error C2182: 'postinitialize_handler': illegal use of type '
void'
core\object.h(648): error C2365: 'postinitialize_handler': redefinition; previou
s definition was 'function'
core\object.h(654): error C4430: missing type specifier - int assumed. Note: C++
 does not support default-int
core\object.h(654): error C2143: syntax error: missing ',' before '*'
core\object.h(665): error C2059: syntax error: '>'
core\object.h(665): error C2976: 'HashMap': too few template arguments
c:\godot\core\hash_map.h(84): note: see declaration of 'HashMap'
core\object.h(666): error C2059: syntax error: ','
core\object.h(673): error C2061: syntax error: identifier 'Object'
core\object.h(674): error C2061: syntax error: identifier 'Object'
core\object.h(677): error C2061: syntax error: identifier 'Object'
core\object.h(679): error C2143: syntax error: missing ';' before '*'
core\object.h(679): error C4430: missing type specifier - int assumed. Note: C++
 does not support default-int
core\object.h(679): error C2238: unexpected token(s) preceding ';'
core\object.h(679): fatal error C1003: error count exceeds 100; stopping compila
tion
scons: *** [modules\enet\register_types.windows.opt.debug.32.obj] Error 2
scons: building terminated because of errors.

**Steps to reproduce:**

cd c:\godot
echo "Building Godot..."
call "C:\Program Files\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
pause
scons platform=windows
pause

**Comment by mefihl** [comment] 2016-08-17 09:24
#6156

**Comment by bojidar-bg** [comment] 2016-08-17 12:28
Yep, looks like a dupe of #6156.

**Closed by bojidar-bg** 2016-08-17 12:28 UTC

**Comment by gokudomatic** [comment] 2016-08-17 13:35
If it's a dupe of #6156, why didn't I get an error about "enet/unix.h" file not found?

**Comment by MorphlingZhou** [comment] 2016-08-19 07:08
may be you can change to the branch 2.1

**Comment by gokudomatic** [comment] 2016-08-21 14:42
Thanks, MorphlingZhou. Actually, the hint from issue #6182 did the trick. Deleting enet was enough to compile.
