### ISSUE TITLE
Can't duplicate dictionary

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#23351] opened 2018-10-28 12:21 UTC
I didn't found similar issues

**Godot version:**
3.0.6

**OS/device including version:**
Ubuntu 18.04.1

**Issue description:**
When I try to copy dictionary with duplicate() method it doesn't copy sub-dictionaries. So this doesn't copy them completely. But I expect complete duplication.

**Steps to reproduce:**

just run the project and you will see it in terminal
[Dictionary.zip](https://github.com/godotengine/godot/files/2522752/Dictionary.zip)

**Comment by neikeq** [comment] 2018-10-28 14:01
Can the same be said about arrays of arrays?

**Comment by bojidar-bg** [comment] 2018-10-28 14:01
The duplicate method has a `deep` parameter to do this. [docs](http://docs.godotengine.org/en/latest/classes/class_dictionary.html#class-dictionary-duplicate)

So, you would have to do `myDict.duplicate(true)` to duplicate sub-dictionaries and arrays. Note that this won't duplicate any nodes or resources (or other Object-s) contained in the dictionary.

Duplicate of #3697, implemented by #17382. To be reopened in case it still doesn't work in 3.x, as it is a bug then.

**Closed** 2018-10-28 14:01 UTC

**Comment by bojidar-bg** [comment] 2018-10-28 14:03
@neikeq Arrays also have the deep parameter in their duplicate function. [docs](http://docs.godotengine.org/en/latest/classes/class_array.html#class-array-duplicate)

Also, nice timing there :wink:
