### ISSUE TITLE
DisplayServer: Window set_position semantics change based on single window mode

### ISSUE THREAD

**Issue by derammo** [godotengine/godot#61263] opened 2022-05-21 21:51 UTC
### Godot version

4.0 dev (4173a4735eb1690132d30430f88fb7d2681c5727)

### System information

Windows  10

### Issue description

# Summary

The Window::set_position(...) call takes coordinates as an argument and moves a window (top level OR popup) to that location/

In single window mode it takes coordinates relative to the main window, presumably like 3.x.

In multi window mode it takes absolute screen coordinates, so things can end up on an entirely different monitor for example.

# Impact

Any application code using this API that works as expected in single window mode won't do the right thing in multi window mode and vice versa, unless the code always checks the window mode.  

# Commentary

It might be better if 4.0 had a separate Window::set_screeen_position or something like that if the semantics are going to be that different. Or screen-space positioning could be done relative to a Display, so that you have to specify both.

This was only tested on Windows.

### Steps to reproduce

This is an internal issue against the API.   Reproducing it requires writing code to use that API and calling it and observing the results in both single- and multi window modes.

**Comment by h0lley** [comment] 2022-07-02 17:46
Confirming this for v4.0.alpha11.official [afdae67cc] and Ubuntu.

Reproduction:

You require at least two monitors to reproduce this.

1. Create a new project
2. Place the editor window on your right monitor
3. In editor settings, ensure that window placement is set to "same as editor"
4. Create a new scene with any type of root node
5. Launch test play and notice that the window is placed on your right monitor as expected - the same as the editor
6. Attach a script to the root node and put this this in _ready():
```
get_viewport().position = get_viewport().position
```
7. Run the game again and notice that the window ends up on your left monitor, when of course that code shouldn't have any effect

**Comment by Sauermann** [comment] 2022-11-14 06:19
`Window::set_position` is always in the coordinate system of the Window's embedder. The embedder can be the Window Manager Screen.

The single-window-mode config-option can change, who the embedder of a Window is. But since this is a user-configurable option, the user should know, if it is switched on or not. So in most cases, this should not be a problem.

In the other cases, for convenience the three functions `CanvasItem::get_screen_transform`, `CanvasItem::get_screen_position` and `CanvasItem::get_screen_rect` are there to help with that.
``` gdscript
    var c: Control = $Control
    var w: Window = $"Control/Window"
    w.position = c.get_screen_position()
```
This script will position the Window so that it is at the location of the Control, not matter, where the Window is embedded.

**Comment by akien-mga** [comment] 2023-02-22 13:11
Closing following above comment.

**Closed by akien-mga** 2023-02-22 13:11 UTC
Labels: discussion, topic:porting
