### ISSUE TITLE
3.x editor crash when TexturePreview created

### ISSUE THREAD

**Issue by uuuuuup** [godotengine/godot#50725] opened 2021-07-22 05:56 UTC
### Godot version

3.x 40b57319e23856a0cba54cbeeda6bba4cc29b589

### System information

Ubuntu GLES3 Nvidia 1060

### Issue description

In TextureRect, when I create new Texture, editor crashes.
I think, when TexturePreview is not in the tree, it cannot get font.
When I changed as below, it fixed.
Could you please check it?

```
--- a/editor/plugins/texture_editor_plugin.cpp
+++ b/editor/plugins/texture_editor_plugin.cpp
@@ -65,7 +65,7 @@ TexturePreview::TexturePreview(Ref<Texture> p_texture, bool p_show_metadata) {
 
                metadata_label->set_text(itos(p_texture->get_width()) + "x" + itos(p_texture->get_height()) + " " + format);
 
-               Ref<DynamicFont> metadata_label_font = get_font("expression", "EditorFonts")->duplicate();
+               Ref<DynamicFont> metadata_label_font = EditorNode::get_singleton()->get_gui_base()->get_font("expression", "EditorFonts")->duplicate();
                metadata_label_font->set_size(16 * EDSCALE);
                metadata_label_font->set_outline_size(2 * EDSCALE);
                metadata_label_font->set_outline_color(Color::named("black"));
```

### Steps to reproduce

1. create TextureRect
2. create AnimatedTexture
3. click AnimatedTexture button
4. editor crashes

**Comment by akien-mga** [comment] 2021-07-22 07:21
Confirmed, it's a duplicate of #50702.

**Closed by akien-mga** 2021-07-22 07:21 UTC
Labels: bug, crash, topic:editor
