### ISSUE TITLE
add tooltip to all buttons with hotkeys

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27627] opened 2019-04-03 03:50 UTC
**Godot version:**

3.1

All buttons that have a hotkey associated with them in the Editor, should display this hotkey in their tooltip.

**Comment by groud** [comment] 2019-04-03 07:49
I think that's already the case. 
Do you have any example where it is not ?

**Comment by TheDuriel** [comment] 2019-04-03 10:56
Tilemap editor, Tileset editor, Animation Tree editor, AnimationPlayer editor. Are some of the big ones that have a severe lack of hinting.

**Comment by groud** [comment] 2019-04-03 11:11
Those are not buttons, they are editors.

Could you provide screenshot of buttons having a hotkey but no tooltip ?
Please be precise on what is lacking, else it does not help much since the hinting in buttons is normaly automatically added.

**Comment by TheDuriel** [comment] 2019-04-03 19:51
AnimationPlayer Editor > Animation Dropdown
Not a single one of these has default bindings. Tooltips show up once an action is bound.

Tileset Editor >
Every single button is missing a tooltip and hotkey. Except for the next and previous coordinate buttons at the top.

What _even is_ the edit button? Nobody i know knows.

Zoom needs to be bound. Holding alt to display names needs to be in the editor settings.

Every editor tab needs a hotkey. And ever tool within needs a hotkey. They're all identical anyways. Using 1-9 for tabs, and the top row of letters for tools works just fine, and follows editor conventions.

AnimationTree Editor>
Needs a hotkey for stepping back out of a nested node.
In all it's sub editors, zooming is not bound to anything.
BlendTree > The Add node dialogue has no key, nor action that will make it pop up. In other editors drawing connections makes the equivalent menu appear. Or it is done using rightclick, (BlendSpaces for example.)
BlendSpace >
Snapping needs a toggle. 

Resource Editor >
In the inspector.
Needs hotkeys for new resource, save, and save as. At the very least.


These are just the ones i remember.

**Comment by groud** [comment] 2019-04-03 19:59
So your problem is different from what your issue stands. You were saying that there were buttons with hotkey that did not have the shortcut displayed in the tooltip, now you make a list of buttons that lack both of them, which is normal. The problem is different.

So what you are saying is just that some buttons should have a default hotkey (and indeed the tooltip that go with it), am I right ? I so I'll update the issue title and its content.

**Comment by urholaukkarinen** [comment] 2019-04-20 10:32
In the script editor debugger there are buttons for actions such as "Step Into" and "Step Over", but those do not have the hotkey included in the tooltip. It's a minor issue, since the same actions can also be found in the Debug menu (with hotkeys), but in my opinion the buttons should also mention the hotkey. 
![Step Into](https://user-images.githubusercontent.com/5576504/56456138-bd01a780-6370-11e9-9ec3-65b85a08aa2e.png)

**Comment by amisner2k** [comment] 2019-11-20 23:57
Basically, if I may add to this, the issue is as follows:
Any toolbar button that has a shortcut key assigned should display that shortcut key in its tooltip. As demonstrated, there are some buttons throughout the editor which do not show their assigned shortcut keys in their tooltips. This is more of a request for a general polishing pass across the editor itself.

However, this issue as it stands is too broad and unmanageable so I believe this particular issue can be closed (the buttons in the Debugger toolbar as @urholaukkarinen mentioned have been fixed in 3.2.beta1 have been fixed for one).  New issues can be created in the future that identify any particular buttons missing their shortcut keys in their tooltips.

**Comment by Calinou** [comment] 2020-04-09 07:41
Closing per @amisner2k's comment. Many cases of missing shortcut tooltips have been fixed in 3.2. If you can find new ones, please open an issue with *exact* references to buttons that are missing shortcuts in their tooltips. You can do this by uploading screenshots or referencing the button's exact text (so it can be easily searched in the source code).

**Closed by Calinou** 2020-04-09 07:41 UTC
Labels: enhancement, topic:editor
