### ISSUE TITLE
Project crashes when a skeleton is selected

### ISSUE THREAD

**Issue by fazil47** [godotengine/godot#44225] opened 2020-12-09 15:21 UTC
**Godot version:**
3.2.3 Maintenance release

**OS/device including version:**
NVIDIA 1650, latest drivers, GLES3 backend

**Issue description:**
The project crashed when I selected the skeleton of an imported glTF model (included in minimal reproduction project).
This is what's shown in the console
![image](https://user-images.githubusercontent.com/18116695/101649823-4e9bbc80-3a61-11eb-92cb-38ae9cf4440f.png)

**Steps to reproduce:**
Open scene.tscn in the included project and select the skeleton
![image](https://user-images.githubusercontent.com/18116695/101649547-05e40380-3a61-11eb-8006-1e423bce3f99.png)

**Minimal reproduction project:**
[File is bigger than 10MB, so here's the GDrive link](https://drive.google.com/file/d/1P88VE7lNbkkzzSx-SxifK2VEwwtZsCRa/view?usp=sharing)
The model is "Animated Dragon" by elly77ellison licensed under Creative Commons Attribution. https://skfb.ly/6QUnM

**Comment by Calinou** [comment] 2020-12-09 16:38
Duplicate of #35653

(the underlying issue is the same).

As a workaround, try increasing the message queue size to 4096 in the Project Settings.

**Closed by Calinou** 2020-12-09 16:38 UTC

**Comment by pouleyKetchoupp** [comment] 2020-12-09 16:41
As a side note, this specific issue seems fixed in 3.2.4 beta 3.
https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-3
