### ISSUE TITLE
The project name becomes the folder name

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#84544] opened 2023-11-06 19:00 UTC
### Godot version

4.2 beta 4

### System information

Windows 10

### Issue description

When creating a new project and selecting the project path, the project name becomes the same as the destination folder in the path, which seems quite inconvenient when you write the project name and then select the path.

### Steps to reproduce

Open the project creation window and change the project path

### Minimal reproduction project

Not needed

**Comment by AThousandShips** [comment] 2023-11-06 19:02
Duplicate of https://github.com/godotengine/godot/issues/83605

**Closed by AThousandShips** 2023-11-06 19:02 UTC
