### ISSUE TITLE
Middle mouse scroll cause exit from popup window(e.g. Editor Settings)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#20872] opened 2018-08-10 08:15 UTC
**Godot version:**
3.1 

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
When I have open popup windows like Editor Settings, any scroll via Middle Mouse Button outside the window(white in image below) cause close this window.

Also it is also annoying when accidentally i click outside window with any mouse button, the window will close itself. I think better will be close windows by double click.

![afsfasf](https://user-images.githubusercontent.com/41945903/43946502-b5e73468-9c85-11e8-8c86-5cc5f3b727e1.png)

**Comment by Noshyaar** [comment] 2018-08-10 10:53
Duplicate of https://github.com/godotengine/godot/issues/6453

**Closed** 2018-08-15 19:17 UTC
