### ISSUE TITLE
Vulkan: Self-shadow issue

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#47914] opened 2021-04-15 10:34 UTC
**Godot version:**
master : c7a4e2196ee08d7ec5190873bd243fbf2727c18f

**OS/device including version:**
Windows NVidea 3070

**Issue description:**
Getting weird self shadow in this scene:
![image](https://user-images.githubusercontent.com/1945449/114855945-d471af00-9e29-11eb-94f5-62802dd036f4.png)

Asfar as I've been able to test, removing the shadow mesh from the object things work correctly. I'm guessing we're creating a lower polygon shadow mesh seeing the floor in this scene is pretty detailed. 
The problem is that the contours won't follow each other well and you have a high chance of self shadow in that situation.

**Steps to reproduce:**
Download the GLTF for the subd mini tutorial and add it to a scene in Godot.

**Minimal reproduction project:**
Just use: https://sketchfab.com/3d-models/subd-minitutorial-8ee637a4afa44d95836749c994270dd3

**Comment by Calinou** [comment] 2022-01-29 17:05
I can't reproduce this on `master` fc09d783f (Linux, NVIDIA 495.46), both with the Vulkan Clustered and Vulkan Mobile backends. Closing.

**Minimal reproduction project:** [test_subd_minitutorial.zip](https://github.com/godotengine/godot/files/7964170/test_subd_minitutorial.zip)
 
### Vulkan Clustered

![2022-01-29_18 02 05](https://user-images.githubusercontent.com/180032/151670090-8faa471b-5448-4dd8-8eac-80df90f3960a.png)

### Vulkan Mobile

![2022-01-29_18 04 02](https://user-images.githubusercontent.com/180032/151670091-a7dbe575-4815-4a7b-a274-cce0c41e04b1.png)

**Closed by Calinou** 2022-01-29 17:05 UTC
Labels: bug, topic:rendering, topic:3d
