### ISSUE TITLE
Mono - GetNode(null) crashes with a native stack trace, Socket error 104

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#32899] opened 2019-10-18 06:00 UTC
**Godot version:**
3.2 Mono

**OS/device including version:**
Ubuntu 18.04 bionic
x86_64 Linux 5.0.0-31-generic

**Issue description:**
Running `GetNode(null)` crashes the game with Socket error 104, native stack trace printed
`mono_crash.24bbb244f.0.json`: https://pastebin.com/11qBYF56
Console Log: https://pastebin.com/2jsaggHH

**Steps to reproduce:**
1) Run `GetNode(null)`, or execute the reproduction project

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3742478/GodotTestProject.zip)

**Comment by qarmin** [comment] 2019-10-18 15:10
Probably duplicate of #32762

**Comment by nathanwfranke** [comment] 2019-10-18 15:17
C# script executes fine individually, it's the GetNode call that crashes the game. Therefore, I do not believe it is a duplicate

**Comment by qarmin** [comment] 2019-10-18 15:35
Can you open mono godot from console and check after crash if Native Stacktrace is similar to https://github.com/godotengine/godot/issues/32888#issuecomment-543128269 ?

**Comment by nathanwfranke** [comment] 2019-10-19 04:53
Native Crash: https://pastebin.com/2jsaggHH
The Stacktrace is not similar

**Comment by aaronfranke** [comment] 2019-10-19 06:33
Can reproduce with 119bf237209414a49879fba40459f22315ab1467, can't reproduce with 3.1.1, seems like a regression.

Ubuntu 18.04 64-bit, kernel 5.0.0-31-generic, Mono 6.4.0.198

Terminal output: https://pastebin.com/aLhsAgfp Mono Crash JSON: https://pastebin.com/t4g9sueY

**Comment by nathanwfranke** [comment] 2019-11-16 21:32
Related to #33506

**Comment by neikeq** [comment] 2019-11-18 11:27
I see, we can't pass a null NodePath or RID pointer to ptrcall. What we can do for now is throw `NullReferenceException` when passing them as null, and once we move to .NET Standard 2.1 we can mark them as NotNull.

**Closed** 2019-11-18 11:40 UTC
Labels: bug, crash, topic:mono
