### ISSUE TITLE
BBCode tags not properly rendered on tooltips

### ISSUE THREAD

**Issue by ArthurAttout** [godotengine/godot#23420] opened 2018-10-31 12:29 UTC
**Godot version:**
Godot Engine v3.0.6.stable.mono.official.8314054

**OS/device including version:**
Windows 10, Nvidia GT710

**Issue description:**
On Windows, tooltips from the node inspector do not properly render. Tags are not transformed. This makes the tooltip difficult to read / confusing.

![image](https://user-images.githubusercontent.com/18170545/47788056-f2f29700-dd10-11e8-8186-2396bd37ef42.png)

**Steps to reproduce:**

- Create a node
- Leave cursor above any of the Inspector properties

**Comment by akien-mga** [comment] 2018-10-31 12:32
Duplicate of #15431, fixed in the master branch.

**Closed by akien-mga** 2018-10-31 12:32 UTC
