### ISSUE TITLE
NinePatchRect does not show Texture in Remote Tree when set from created ImageTexture

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#47364] opened 2021-03-25 17:46 UTC
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 20H2
1030GT, not sure of driver version right now
Backend is GLES3

**Issue description:**

- Assign an ImageTexture created from a loaded Texture to a NinePatchRect via code.
- Look in the Remote Tree, and find your NinePatchRect.
- It'll have [empty] in the texture property.

**Steps to reproduce:**
In the provided project:
- Run the attached project
- Inspect the Remote Tree

From scratch:
- Load a Texture from file using code
- Create an ImageTexture from that using code, I don't think sub-regions matter too much here
- Assign the ImageTexture to a NinePatchRect
- Inspect the NinePatchRect in the Remote Tree
- [empty] will be in the texture property slot

**Minimal reproduction project:**

[NinePatchRect Texture Test.zip](https://github.com/godotengine/godot/files/6206785/NinePatchRect.Texture.Test.zip)

**Comment by Calinou** [comment] 2021-03-25 19:58
Duplicate of #28353 (same cause).

**Closed by Calinou** 2021-03-25 19:58 UTC
Labels: bug, topic:editor
