### ISSUE TITLE
Godot 4.0.2 locks up when ConfirmationDialog is visible in editor and you change it's parent type

### ISSUE THREAD

**Issue by graydwarf** [godotengine/godot#76505] opened 2023-04-27 12:49 UTC
### Godot version

4.0.2

### System information

Windows 11

### Issue description

Godot 4.0.2 locks up when ConfirmationDialog is visible in editor and you change it's parent type. 

Forced to end task and lose changes.

### Steps to reproduce

- New standard/default project
- Add Control node
- Add ConfirmationDialog as child of Control node
- Make the ConfirmationDialog visible
- Change the Control type to Node2D
- Try to do anything in godot including clicking the X button.

Expected:
- Should not lock up godot

Actual:
- Godot completely locked up but still responsive.

Assuming it's some sort of modal dialog oopsy.

### Minimal reproduction project

[confirmation-dialog-freeze.zip](https://github.com/godotengine/godot/files/11343625/confirmation-dialog-freeze.zip)

**Comment by capnm** [comment] 2023-04-27 18:26
The father _AcceptDialog_  the same, the deadlock also happens on Linux + GitHub tip:
```
ctrl+c

Process 137980 stopped
* thread #1, name = 'godot.linuxbsd.', stop reason = signal SIGSTOP
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffffffd6c0, rem=0x00007fffffffd6d0) at clock_nanosleep.c:78:7
(lldb) bl all
error: 'bl' is not a valid command.
(lldb) bt all
* thread #1, name = 'godot.linuxbsd.', stop reason = signal SIGSTOP
  * frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffffffd6c0, rem=0x00007fffffffd6d0) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffffffd6c0, remaining=0x00007fffffffd6d0) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x000055555a122909 godot.linuxbsd.editor.dev.x86_64`OS::add_frame_delay(this=0x00007fffffffd858, p_can_draw=<unavailable>) at os.cpp:564:4
    frame #4: 0x0000555556ade195 godot.linuxbsd.editor.dev.x86_64`Main::iteration() at main.cpp:3322:23
    frame #5: 0x0000555556a32e4d godot.linuxbsd.editor.dev.x86_64`OS_LinuxBSD::run(this=0x00007fffffffd858) at os_linuxbsd.cpp:889:7
    frame #6: 0x0000555556a2972b godot.linuxbsd.editor.dev.x86_64`main(argc=<unavailable>, argv=<unavailable>) at godot_linuxbsd.cpp:73:6
    frame #7: 0x00007ffff7c5c083 libc.so.6`__libc_start_main(main=(godot.linuxbsd.editor.dev.x86_64`main at godot_linuxbsd.cpp:43), argc=2, argv=0x00007fffffffdd88, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdd78) at libc-start.c:308:16
    frame #8: 0x0000555556a2959e godot.linuxbsd.editor.dev.x86_64`_start + 46
  thread #2, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055555d73c1e0, mutex=0x000055555d73c1b8) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x000055555a22c435 godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(void*) [inlined] Semaphore::wait(this=0x000055555d73c1b8) const at semaphore.h:56:14
    frame #5: 0x000055555a22c3f8 godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(self=0x000055555d73a190) at ip.cpp:115:13
    frame #6: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(void*) [inlined] std::__atomic_base<bool>::load(std::memory_order) const at ip.cpp:111
godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(void*) [inlined] std::atomic<bool>::load(std::memory_order) const at atomic:113:22
godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(void*) [inlined] SafeFlag::is_set() const at safe_refcount.h:147:15
godot.linuxbsd.editor.dev.x86_64`_IP_ResolverPrivate::_thread_function(void*) at ip.cpp:114:29), p_userdata=0x000055555d73a190)(void*), void*) at thread.cpp:61:3
    frame #7: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #8: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #9: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #3, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055555d58df48, mutex=0x000055555d58df20) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x000055555a6299fb godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(void*) [inlined] Semaphore::wait(this=<unavailable>) const at semaphore.h:56:14
    frame #5: 0x000055555a6299af godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(p_user=<unavailable>) at worker_thread_pool.cpp:154:39
    frame #6: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(void*) at worker_thread_pool.cpp:152), p_userdata=0x000055555d7ada50)(void*), void*) at thread.cpp:61:3
    frame #7: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #8: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #9: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #4, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055555d58df48, mutex=0x000055555d58df20) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x000055555a6299fb godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(void*) [inlined] Semaphore::wait(this=<unavailable>) const at semaphore.h:56:14
    frame #5: 0x000055555a6299af godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(p_user=<unavailable>) at worker_thread_pool.cpp:154:39
    frame #6: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`WorkerThreadPool::_thread_function(void*) at worker_thread_pool.cpp:152), p_userdata=0x000055555d7ada68)(void*), void*) at thread.cpp:61:3
    frame #7: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #8: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #9: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #5, name = 'godot.l:disk$0'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055555dc94e30, mutex=0x000055555dc94e08) at pthread_cond_wait.c:647:10
    frame #3: 0x00007ffff426e81d libvulkan_radeon.so`___lldb_unnamed_symbol8708 + 13
    frame #4: 0x00007ffff42418bb libvulkan_radeon.so`___lldb_unnamed_symbol7982 + 139
    frame #5: 0x00007ffff426e73b libvulkan_radeon.so`___lldb_unnamed_symbol8701 + 27
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #7, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d4cfcb libc.so.6`__GI___select(nfds=4, readfds=0x00007fffe318cd38, writefds=0x0000000000000000, exceptfds=0x0000000000000000, timeout=0x00007fffe318cd28) at select.c:41:10
    frame #1: 0x0000555556a3ea07 godot.linuxbsd.editor.dev.x86_64`DisplayServerX11::_wait_for_events(this=0x000055555dc0d850) const at display_server_x11.cpp:3641:22
    frame #2: 0x0000555556a4f503 godot.linuxbsd.editor.dev.x86_64`DisplayServerX11::_poll_events(this=0x000055555dc0d850) at display_server_x11.cpp:3657:3
    frame #3: 0x0000555556a4f4b5 godot.linuxbsd.editor.dev.x86_64`DisplayServerX11::_poll_events_thread(ud=<unavailable>) at display_server_x11.cpp:3619:18 [artificial]
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`DisplayServerX11::_poll_events_thread(void*) at display_server_x11.cpp:3619:18), p_userdata=0x000055555dc0d850)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #8, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffdbffecb0, rem=0x0000000000000000) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffdbffecb0, remaining=0x0000000000000000) at nanosleep.c:27:13
    frame #2: 0x00007ffff7d4d85f libc.so.6`usleep(useconds=50000) at usleep.c:32:10
    frame #3: 0x0000555556a37a6a godot.linuxbsd.editor.dev.x86_64`JoypadLinux::monitor_joypads(this=0x000055555f3e9370, p_udev=0x00007fffd4000b60) at joypad_linux.cpp:208:3
    frame #4: 0x0000555556a376b3 godot.linuxbsd.editor.dev.x86_64`JoypadLinux::monitor_joypads_thread_run(this=0x000055555f3e9370) at joypad_linux.cpp:129:4
    frame #5: 0x0000555556a3742a godot.linuxbsd.editor.dev.x86_64`JoypadLinux::monitor_joypads_thread_func(p_user=<unavailable>) at joypad_linux.cpp:115:8 [artificial]
    frame #6: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`JoypadLinux::monitor_joypads_thread_func(void*) at joypad_linux.cpp:113:6), p_userdata=0x000055555f3e9370)(void*), void*) at thread.cpp:61:3
    frame #7: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #8: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #9: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #9, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffdb7fdd70, rem=0x0000000000000000) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffdb7fdd70, remaining=0x0000000000000000) at nanosleep.c:27:13
    frame #2: 0x00007ffff7d4d85f libc.so.6`usleep(useconds=10000) at usleep.c:32:10
    frame #3: 0x0000555556a38db0 godot.linuxbsd.editor.dev.x86_64`JoypadLinux::joypad_events_thread_run(this=0x000055555f3e9370) at joypad_linux.cpp:470:4
    frame #4: 0x0000555556a3743a godot.linuxbsd.editor.dev.x86_64`JoypadLinux::joypad_events_thread_func(p_user=<unavailable>) at joypad_linux.cpp:443:8 [artificial]
    frame #5: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`JoypadLinux::joypad_events_thread_func(void*) at joypad_linux.cpp:441:6), p_userdata=0x000055555f3e9370)(void*), void*) at thread.cpp:61:3
    frame #6: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #7: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #8: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #10, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffdadf6d20, rem=0x00007fffdadf6d30) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffdadf6d20, remaining=0x00007fffdadf6d30) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x00005555577b6679 godot.linuxbsd.editor.dev.x86_64`AudioDriverPulseAudio::thread_func(p_udata=0x00007fffffffda28) at audio_driver_pulseaudio.cpp:587:25
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`AudioDriverPulseAudio::thread_func(void*) at audio_driver_pulseaudio.cpp:397), p_userdata=0x00007fffffffda28)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #11, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055555f09bab8, mutex=0x000055555f09ba90) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x00005555575d3f4b godot.linuxbsd.editor.dev.x86_64`tvg::TaskQueue::pop(this=0x000055555f09ba40, task=0x00007fffda5f5dd0) at tvgTaskScheduler.cpp:79:19
    frame #5: 0x00005555575d3da3 godot.linuxbsd.editor.dev.x86_64`tvg::TaskSchedulerImpl::run(this=0x000055555fe51cd0, i=0) at tvgTaskScheduler.cpp:137:44
    frame #6: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #7: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #8: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #12, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffb3ffebf0, rem=0x00007fffb3ffec00) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffb3ffebf0, remaining=0x00007fffb3ffec00) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x00005555583dfb72 godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformAndroid::_check_for_changes_poll_thread(ud=0x00007fffb4038160) at export_plugin.cpp:404:25
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) [inlined] std::__atomic_base<bool>::load(std::memory_order) const at export_plugin.cpp:259
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) [inlined] std::atomic<bool>::load(std::memory_order) const at atomic:113:22
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) [inlined] SafeFlag::is_set() const at safe_refcount.h:147:15
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) at export_plugin.cpp:262:27), p_userdata=0x00007fffb4038160)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #13, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffb37fdd70, rem=0x00007fffb37fdd80) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffb37fdd70, remaining=0x00007fffb37fdd80) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x000055555843b2c6 godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformIOS::_check_for_changes_poll_thread(ud=0x0000555560e8ba90) at export_plugin.h:169:26
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) [inlined] std::__atomic_base<bool>::load(std::memory_order) const at export_plugin.h:144
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) [inlined] std::atomic<bool>::load(std::memory_order) const at atomic:113:22
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) [inlined] SafeFlag::is_set() const at safe_refcount.h:147:15
godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) at export_plugin.h:147:28), p_userdata=0x0000555560e8ba90)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #14, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffb2ffcda0, rem=0x00007fffb2ffcdb0) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffb2ffcda0, remaining=0x00007fffb2ffcdb0) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x00005555584a422f godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformWeb::_server_thread_poll(data=0x00005555606f1c70) at export_plugin.cpp:651:24
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`EditorExportPlatformWeb::_server_thread_poll(void*) at export_plugin.cpp:648), p_userdata=0x00005555606f1c70)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #15, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7d1523f libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007fffd9df4d60, rem=0x00007fffd9df4d70) at clock_nanosleep.c:78:7
    frame #1: 0x00007ffff7d1aec7 libc.so.6`__GI___nanosleep(requested_time=0x00007fffd9df4d60, remaining=0x00007fffd9df4d70) at nanosleep.c:27:13
    frame #2: 0x00005555577a5cea godot.linuxbsd.editor.dev.x86_64`OS_Unix::delay_usec(this=<unavailable>, p_usec=<unavailable>) const at os_unix.cpp:273:9
    frame #3: 0x00005555586b54c6 godot.linuxbsd.editor.dev.x86_64`EditorFileServer::_thread_start(s=0x000055556011a3f0) at editor_file_server.cpp:293:24
    frame #4: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`EditorFileServer::_thread_start(void*) at editor_file_server.cpp:259), p_userdata=0x000055556011a3f0)(void*), void*) at thread.cpp:61:3
    frame #5: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #6: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #7: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #16, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x000055556df8c0b0, mutex=0x000055556df8c088) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x00005555583d75e8 godot.linuxbsd.editor.dev.x86_64`TilesEditorPlugin::_thread() [inlined] Semaphore::wait(this=0x000055556df8c088) const at semaphore.h:56:14
    frame #5: 0x00005555583d7593 godot.linuxbsd.editor.dev.x86_64`TilesEditorPlugin::_thread(this=0x000055556df8b9f0) at tiles_editor_plugin.cpp:68:23
    frame #6: 0x00005555583d74a5 godot.linuxbsd.editor.dev.x86_64`TilesEditorPlugin::_thread_func(ud=<unavailable>) at tiles_editor_plugin.cpp:62:6 [artificial]
    frame #7: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`TilesEditorPlugin::_thread_func(void*) at tiles_editor_plugin.cpp:62:6), p_userdata=0x000055556df8b9f0)(void*), void*) at thread.cpp:61:3
    frame #8: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #9: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #10: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #17, name = 'godot.linuxbsd.'
    frame #0: 0x00007ffff7f8e376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13
    frame #1: 0x00007ffff7f8e359 libpthread.so.0`__pthread_cond_wait at pthread_cond_wait.c:508:14
    frame #2: 0x00007ffff7f8e290 libpthread.so.0`__pthread_cond_wait(cond=0x0000555560ecfd10, mutex=0x0000555560ecfce8) at pthread_cond_wait.c:647:10
    frame #3: 0x000055555a8fec00 godot.linuxbsd.editor.dev.x86_64`std::condition_variable::wait(std::unique_lock<std::mutex>&) + 16
    frame #4: 0x0000555557b311f5 godot.linuxbsd.editor.dev.x86_64`EditorResourcePreview::_thread() [inlined] Semaphore::wait(this=0x0000555560ecfce8) const at semaphore.h:56:14
    frame #5: 0x0000555557b311b8 godot.linuxbsd.editor.dev.x86_64`EditorResourcePreview::_thread(this=0x0000555560ecf8e0) at editor_resource_preview.cpp:326:15
    frame #6: 0x0000555557b31155 godot.linuxbsd.editor.dev.x86_64`EditorResourcePreview::_thread_func(ud=<unavailable>) at editor_resource_preview.cpp:99:7 [artificial]
    frame #7: 0x000055555a122de1 godot.linuxbsd.editor.dev.x86_64`Thread::callback(p_caller_id=<unavailable>, p_settings=<unavailable>, p_callback=(godot.linuxbsd.editor.dev.x86_64`EditorResourcePreview::_thread_func(void*) at editor_resource_preview.cpp:99:7), p_userdata=0x0000555560ecf8e0)(void*), void*) at thread.cpp:61:3
    frame #8: 0x000055555a974d74 godot.linuxbsd.editor.dev.x86_64`execute_native_thread_routine + 20
    frame #9: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #10: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
  thread #18, name = 'WSI swapchain q'
    frame #0: 0x00007ffff7f8e7d1 libpthread.so.0`__pthread_cond_timedwait at futex-internal.h:320:13
    frame #1: 0x00007ffff7f8e7aa libpthread.so.0`__pthread_cond_timedwait at pthread_cond_wait.c:520:11
    frame #2: 0x00007ffff7f8e6d0 libpthread.so.0`__pthread_cond_timedwait(cond=0x0000555577181c68, mutex=0x0000555577181c40, abstime=0x00007fffe398dde0) at pthread_cond_wait.c:665:10
    frame #3: 0x00007ffff41cbb81 libvulkan_radeon.so`___lldb_unnamed_symbol6530 + 257
    frame #4: 0x00007ffff7f87609 libpthread.so.0`start_thread(arg=<unavailable>) at pthread_create.c:477:8
    frame #5: 0x00007ffff7d57133 libc.so.6`__clone at clone.S:95
```

**Comment by Rindbee** [comment] 2023-04-29 04:38
Seems to be a duplicate of #68575.

**Comment by capnm** [comment] 2023-04-29 05:33
...and your PR fixes it :-)

**Comment by Calinou** [comment] 2023-06-09 18:37
- Duplicate of https://github.com/godotengine/godot/issues/68575.

**Closed by Calinou** 2023-06-09 18:37 UTC
