### ISSUE TITLE
Inherited signals don't fire, can't be removed, can't be connected to child

### ISSUE THREAD

**Issue by Max-Hollywood** [godotengine/godot#45244] opened 2021-01-17 00:54 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10, GLES3, terrible specs (but all new components)

**Issue description:**
An `extend`ed node does not fire inherited signals, and the signals cannot be disconnected (they come back), and connecting that signal to the child doesn't fire either.

I also randomly get `editor/connections_dialog.cpp:525 - Condition "!it" is true.` while setting trying to set up the signals.

I think it's a part of this issue: https://github.com/godotengine/godot/issues/12373

**Steps to reproduce:**
_Node setup:_
TestUnit
Grunt (extends TestUnit)

_Signal connection:_
`TestUnit` -> signal `connect` to `input_event` left click

_Input event_
`TestUnit` -> left click -> `print("selected")`
`Grunt` -> left click -> nothing

**Minimal reproduction project:**
Here's the exact project as it is (25KB):
[CIA.zip](https://github.com/godotengine/godot/files/5825365/CIA.zip)

**Comment by bmolyneaux** [comment] 2021-02-15 00:01
If I understand correctly, the issue is actually that you have input_pickable set to false on the Grunt nodes within the World scene. This doesn't seem to be a Godot bug.

**Comment by Calinou** [comment] 2022-07-08 23:09
Duplicate of https://github.com/godotengine/godot/issues/12373.

**Closed by Calinou** 2022-07-08 23:09 UTC
Labels: topic:core, needs testing
