### ISSUE TITLE
File.file_exists() can't find images if exported with "Compress for disk" option

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#1562] opened 2015-03-23 17:51 UTC
No errors displayed.

**Comment by reduz** [comment] 2015-04-09 04:35
Lossy or lossless?

**Comment by PLyczkowski** [comment] 2015-04-09 11:00
Godot 1.1 beta windows 64, exported to windows 32, images are png, loaded in with code not added via resources, export all files option chosen, no images appear with 0, 0.5, or 1 compress for disk setting, works fine with the "keep original" option.

**Comment by PLyczkowski** [comment] 2015-04-09 11:02
(The GUI is a bit unclear, the compress slider should become inactive when "keep original" is chosen. Also, when compress for ram is chosen, the slider still says compress for disk.)

**Comment by reduz** [comment] 2015-04-28 23:16
does this still happen? if you reload the editor also still happens?

**Comment by PLyczkowski** [comment] 2015-04-29 09:40
Still happens, images are compressed and saved ok (filesize goes to 39 MB from 170 MB), but they are not displayed.

**Comment by PLyczkowski** [comment] 2015-04-29 09:41
The images are not added as resources in the editor, they are loaded in during runtime via code.

**Comment by reduz** [comment] 2015-04-29 11:46
can you make a small example project where this happens? I tested this and
I'm also using it in production games without issues

**Comment by PLyczkowski** [comment] 2015-05-06 16:22
Here you go:

https://www.dropbox.com/s/hz3lcahwi0qvhns/Compression%20Bug%20Example.zip?dl=0

You can also check out the windows warning sounds that are played when the txt file is being imported. There are no errors displayed. It may have something to do with the non-standard characters used?

**Comment by akien-mga** [comment] 2015-11-17 14:38
Can you still reproduce this issue in the current master branch or a recent nightly build?

**Comment by PLyczkowski** [comment] 2015-11-17 14:49
@akien-mga I'll try it out (it can take a couple of days before I find time).

**Comment by PLyczkowski** [comment] 2015-12-03 15:02
Sorry for delay. I can confirm this still happens using the 2.0 alpha from 09/30/2015 12:18 AM.

**Comment by PLyczkowski** [comment] 2015-12-03 15:14
It also still happens in the newest nightly build I can find, from 10/30/2015 12:25 AM.

**Comment by reduz** [comment] 2015-12-03 15:18
Im upgrading webp in hopes it fixes the issue

**Comment by PLyczkowski** [comment] 2016-03-30 14:16
Still doesn't work in 2.0.1 : (

Maybe I am doing something wrong? I use this:

```
func display_image(image_path):

	image_path = "res://"+image_path

	# Check if file exists.

	var check_file = File.new()

	if check_file.file_exists(image_path):

		# Display file.

		var texture = ImageTexture.new()

		texture = load(image_path)

		var image = Sprite.new()

		image.set_texture(texture)

		viewport_image_container.add_child(image)

		tools.print_message("Display changed.", 0)

		#manuscript_player.preload_images(1, manuscript_player.last_preloaded_image_line + 1)

	else:

		tools.print_error("Error: File does not exist")
```

This works without the compressing option. With it the files (.png's) are not found.

Which is kind of understandable, since from what I gather the png's are converted to tex files with the Compress option on? How can Compress option be helpful then if it changes the format of the file?

**Comment by volzhs** [comment] 2016-03-30 14:20
I guess, those codes works if you just don't check ``file_exists``.

**Comment by PLyczkowski** [comment] 2016-03-30 14:31
Oh, it indeed works without the check! So the problem is with file_exists() that doesn't play nicely with the Compress option?

**Comment by volzhs** [comment] 2016-03-30 15:47
I think, it's better to check if the texture is null.

```gdscript
func display_image(image_path):
    image_path = "res://"+image_path
    var texture = load(image_path)
    if texture:
        var image = Sprite.new()
        image.set_texture(texture)
        viewport_image_container.add_child(image)
        tools.print_message("Display changed.", 0)
    else:
        tools.print_error("Error: File does not exist")
```

**Comment by volzhs** [comment] 2016-03-30 15:51
I don't know exactly, but I guess, the magical ``load()`` or ``preload()`` function will find converted texture(``.tex``) somehow.
but, ``file_exists`` function will check exact file name.

**Comment by PLyczkowski** [comment] 2016-03-30 15:56
Ok, thanks!

@reduz This can now be closed - If you don't consider `file_exist` and the way the Compress function interact a bug of course. I have no opinion myself.

**Comment by akien-mga** [comment] 2016-03-30 16:09
I've tested to export locally to a zip archive with "compress for disk", and indeed all ``.png`` files become ``.converted.tex`` files, so ``File.file_exists()`` can't reliably be used to locate such textures.

It's not a bug in the API per se, now the question is whether we would want to add some workaround behaviour so that it does work, or just advise users to use ``load()`` instead.

**Comment by bojidar-bg** [comment] 2016-07-24 19:47
Isn't this a duplicate of #1680 ?

**Comment by akien-mga** [comment] 2018-05-09 10:40
I wrote #18740 to better summarize the issue, so closing this one in favour of the new one.

**Closed by akien-mga** 2018-05-09 10:40 UTC
Labels: confirmed, enhancement, topic:porting
