### ISSUE TITLE
Ability to refactor variable/method names in the editor

### ISSUE THREAD

**Issue by Ploppy3** [godotengine/godot#23225] opened 2018-10-22 15:18 UTC
_Edit: This issue was reported as a duplicate of #20624_

The old issue was closed due to 'inactivity' though I think it's a much needed feature of the editor. There will probably be not much activity since there isn't much to say about it, just that we need it!

Thank you.

**Godot version:**

3.0.6

**Comment by neikeq** [comment] 2018-10-22 19:14
I guess this mean to automatically refactor rename variables, right? If that's the case this would be a duplicate of #20624, but that one is closed I have no idea why.

**Comment by Jalu1** [comment] 2018-10-22 19:28
In that case, yes it would be a duplicate. It looks like that one was closed because no one worked to do it. I'll look into making it happen.

**Comment by Ploppy3** [comment] 2018-10-22 19:55
@neikeq is right, that's what I wanted. If you have a better idea for a title, point it out and I'll make sure to edit it.

**Comment by toger5** [comment] 2018-10-22 22:00
There is something to talk about:
What exacly do you need to refactor more urgently? 
Node names ? And refactor the paths in gd scripts? 
Or Class variables/ mehtods? And update all instances (also in other files)

**Comment by Ploppy3** [comment] 2018-10-22 22:28
My question was originally for variables and methods. I forgot to mention the methods, I thought they were related, my bad.

I think node renaming is an other feature request https://github.com/godotengine/godot/issues/3163 which I would love to see implemented!

**Comment by nthana** [comment] 2018-10-29 09:19
I totally agree with Ploppy3. This feat is very useful because it will increase productivity a lot.

Usually, in coding process, variable names and method names would be changed frequently (also true with class names and resource names).

Comparing with the Java Eclipse editor, that editor supports full renaming of methods, variables, and classes (Menu : Refactor > Rename).  It even support cross class references, and that save time a lot.

I think that if GDScript editor could support that, it would be a fabulous feature.

Thank you.

**Comment by clayjohn** [comment] 2020-05-27 18:22
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 18:22 UTC
Labels: feature proposal, topic:editor, usability
