### ISSUE TITLE
Install over AssetLib shows errors if containing files have zero size

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#50157] opened 2021-07-04 14:11 UTC
### Godot version

3.3.2.stable.official

### System information

MacOs

### Issue description

When installing my plugin [`GdUnit3`](https://github.com/MikeSchulze/gdUnit3) over the AssetLib it shows errors on the console.

This error occures 6 times
`drivers/unix/file_access_unix.cpp:279 - Condition "!p_src" is true.`

I find out this errors comming form files included in the plugin where have zero size.
e.g. `\addons\gdUnit3\test\core\resources\copy_test\folder_a\file_a.txt`

The error is only shown on MacOS, under Windows no errors are reported.

Files with zero length should not endup in a error.

### Steps to reproduce

On MacOS
- open Godot with a fresh project
- go to AssetLib and install `GdUnit3`
- install by include all files

See console output

**Comment by akien-mga** [comment] 2021-07-04 14:43
Duplicate of #33564, fixed in 3.3.3 and later.

**Closed by akien-mga** 2021-07-04 14:43 UTC
Labels: bug, platform:macos, topic:assetlib, topic:editor
