### ISSUE TITLE
Loading resources from user://

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#2319] opened 2015-07-30 12:22 UTC
( Win7, 1.1stable )
At the moment you can't load resources from user:// path. Saving using ResourceSaver works fine.
ResourceLoader seem to always add "res://" before given path:

```
load("user://test.png") # existing resource

ERROR:  Failed loading image: res://user://test.png
At:  scene/io/resource_format_image.cpp:114
ERROR:  Failed loading image for BitMap: res://user://test.png
At:  scene/resources/bit_mask.cpp:219
ERROR:  Failed loading resource: user://test.png
At:  core/io/resource_loader.cpp:209
```

Are there some reasons for it to not work, or it's a bug?

**Comment by vnen** [comment] 2015-08-01 01:38
:+1:

**Comment by LeonardMeagher2** [comment] 2015-08-18 23:21
:+1:

**Comment by Andi-K** [comment] 2015-08-25 17:16
:+1:  (Linux  1.1 stable )

**Comment by okamstudio** [comment] 2015-08-25 17:30
ok, ok, the problem is that this is fixed in okam's repository and merging
it is not that easy. Will fix it eventually, I promise :)

On Tue, Aug 25, 2015 at 2:17 PM, Andi-K <notifications@github.com> wrote:

> [image: :+1:] (Linux 1.1 stable )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2319#issuecomment-134674800>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment] 2015-09-04 03:06
I think this is fixed, give it a try when you can

**Comment by vnen** [comment] 2015-09-04 21:29
It's now working for me.

**Closed** 2015-11-10 15:53 UTC
Labels: enhancement, topic:core
