### ISSUE TITLE
Saving any scene on godot v4 beta 17 (google play version)

### ISSUE THREAD

**Issue by ItzFafa** [godotengine/godot#73101] opened 2023-02-11 13:56 UTC
### Godot version

4.0.0.beta.17

### System information

Android 12 Mediatik helio g95 6 ram 128gb

### Issue description

So I made a project scene of a floor with a character and simple movement system and I tried to save it to test it and it saved but kept giving me this error:

editor/progress_dialog.cpp:173 - Do not use progress dialog (task) while flushing the message queue or using call_deferred() ! editor/progress_dialog.cpp:206 - Condition "!tasks.has (p_task)" is true. Returning: canceled editor/progress_dialog.cpp:206 - Condition "!tasks.has (p_task)" is true. Returning: canceled • editor/progress_dialog.cpp:206 Condition "!tasks.has (p_task)" is true. Returning: canceled • editor/progress_dialog.cpp:206 Condition "Itasks.has (p_task)" is true. Returning: canceled

• editor/progress_dialog.cpp:206 Condition "!tasks.has(p_task)" is true. Returning: canceled

• editor/progress_dialog.cpp:235 Condition "!tasks.has(p_task)" is true.

And the fps was horrible like 5 fps or something then I tried on a different scenes even tried a scene with just node 3d and all gives the same error while trying to save the scene 

### Steps to reproduce

Just saving any scene

### Minimal reproduction project

![Screenshot_2023-02-11-15-54-53-094_org godotengine editor v4](https://user-images.githubusercontent.com/115576911/218261696-6725da43-0dac-448f-b8ee-76848879cb09.jpg)

https://user-images.githubusercontent.com/115576911/218261716-69c7c4e8-95f4-4993-bc4c-9bcb6a6dbe93.mp4

**Comment by Zireael07** [comment] 2023-02-11 14:42
Can you try the release candidate?

**Comment by Calinou** [comment] 2023-02-11 15:38
Duplicate of https://github.com/godotengine/godot/issues/73097.

**Closed by Calinou** 2023-02-11 15:38 UTC
