### ISSUE TITLE
Opened value/name changer popup doesn't change position after resizing editor

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22182] opened 2018-09-17 12:39 UTC
**Godot version:**
3,1 e522baf

**OS/device including version:**
Windows 10 HD 4600

**Issue description:**
When I try change value/name by clicking on it, and later resize editor window, that popup still wait in self position instead change position to correct.

**Steps to reproduce:**
![aa](https://user-images.githubusercontent.com/41945903/45623362-6012db80-ba87-11e8-9dce-a8e294784dc6.gif)

![ezgif-1-4777bef4bd](https://user-images.githubusercontent.com/41945903/45623372-64d78f80-ba87-11e8-9e43-5228bd6e1b27.gif)

**Comment by asheraryam** [comment] 2018-12-14 15:35
Should this be closed by https://github.com/godotengine/godot/pull/22729?

**Comment by akien-mga** [comment] 2018-12-14 15:41
@guilhermefelipecgs mentioned that the issue is only fixed partially.

**Comment by guilhermefelipecgs** [comment] 2018-12-14 16:30
We can close this. It seems someone already fix the second problem. Popmenu's is closing automatic when you click on edge of the window to resize editor. Tested with f11047aa81563343eb8b3d8d989af393fd2639b6.

**Closed** 2018-12-14 17:05 UTC
Labels: bug, junior job, topic:editor
