### ISSUE TITLE
Gradient texture 'expands' Inspector window

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19523] opened 2018-06-12 13:38 UTC
**Godot version:**

76875ba

**Issue description:**

Inspector window 'expands' to the right.

![inspectorexpands-01](https://user-images.githubusercontent.com/15687516/41292821-eb78e186-6e53-11e8-807d-dc48db616c7b.jpg)

![inspectorexpands-02](https://user-images.githubusercontent.com/15687516/41292827-ed60c9c8-6e53-11e8-93c3-b2d13f2e2c9b.jpg)

**Steps to reproduce:**
New project, new scene, add 2D Root node, add 2D particle system, add Particles material, add Gradient Texture, add New Gradient. Now click the Gradient Texture area again and the Inspector expands to the right.

**Minimal reproduction project:**

The included project has all the above except the Gradient.

[Godot3Master.zip](https://github.com/godotengine/godot/files/2094240/Godot3Master.zip)

**Comment by sketchyfun** [comment] 2018-06-12 14:28
I was just about to post this issue :D 
Here's clip to show it in action anyway:

![peek 2018-06-12 15-28](https://user-images.githubusercontent.com/10464013/41296621-3f9f4628-6e55-11e8-8e29-4b3f4ae6260b.gif)

**Comment by JFonS** [comment] 2018-06-14 07:44
This looks like a duplicate of #18999

**Comment by Hinsbart** [comment] 2018-06-16 19:07
closing as duplicate of #18999

**Closed by Hinsbart** 2018-06-16 19:07 UTC
Labels: bug, confirmed, topic:editor, usability
