### ISSUE TITLE
If you select a context menu item without left clicking, the element you clicked on steals the mouse focus.

### ISSUE THREAD

**Issue by Benguin** [godotengine/godot#59586] opened 2022-03-27 16:13 UTC
### Godot version

v4.0 alpha 4

### System information

Archlinux, KDE X11

### Issue description

Myself and some others have an issue where occasionally mouse clicks stop working on any element except the last element to be successfully interacted with. It can be fixed be right clicking and then left clicking a context menu item

### Steps to reproduce

- Right click a node from the scene
- Do not release the right mouse button
- Hover over a context menu item
- Release right mouse button (on linux, this also selects that menu item-- not sure about other platforms)

- context menu is closed, but due to the lack of a LMB buttonup event, the node believes it still has focus and the editor won't allow mouseclicks on any other element.

### Minimal reproduction project

Any project should work for this. It may need to be done on Linux-- context menus on linux usually appear on RMB down rather than on RMB up, which I'm not sure is true on Windows.

**Comment by Sauermann** [comment] 2022-03-27 16:37
This sounds very similar to #59406.

**Comment by Benguin** [comment] 2022-03-27 16:41
> This sounds very similar to #59406.

Yeah that seems right-- it was hard to think what to search for :man_facepalming:

**Comment by Calinou** [comment] 2022-03-27 17:07
Duplicate of https://github.com/godotengine/godot/issues/59406.

**Closed by Calinou** 2022-03-27 17:07 UTC
