### ISSUE TITLE
Allow for codependant scripts

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#24404] opened 2018-12-16 19:44 UTC
![image](https://user-images.githubusercontent.com/4584511/50057878-83a8f900-013e-11e9-89f9-27dd79a0b05e.png)

I don't really understand the reason for this restriction - why can't class names be essentially definition references like in any other language? I'm assuming there's some technical limitation I'm not aware about that makes this difficult?

**Comment by bojidar-bg** [comment] 2018-12-16 21:48
Duplicate of #21461 or #22135?

This restriction will be fixed later on, maybe as part of 3.2. Currently, the GDScript parser will need too many changes to support this, and we don't want to make them right before 3.1 is released.

**Comment by akien-mga** [comment] 2018-12-17 09:33
Duplicate of #21461 and #22135 indeed.

**Closed by akien-mga** 2018-12-17 09:33 UTC
