### ISSUE TITLE
Class "XXX" hides global script class on FileAccess.get_var()

### ISSUE THREAD

**Issue by dave2** [godotengine/godot#68666] opened 2022-11-14 21:02 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.beta4.official.e6751549c

### System information

Ubuntu 22.04

### Issue description

GDscript produces an error with no backtrace: "Class 'XXX' hides global script class'. 

I've narrowed down an error I started getting when loading saved objects from a file down to the call to `FileAccess.get_var()`. This occurs when I have a class instance written out with `FileAccess.store_var(true)` (which works), and doesn't appear to occur for any other reason. 

I can just serialise the object myself (and probably should) but this error is definitely harder to track down with no backtrace.

### Steps to reproduce

Just run the attached minimum project.

### Minimal reproduction project

[storavar_bug.zip](https://github.com/godotengine/godot/files/10007026/storavar_bug.zip)

**Comment by Calinou** [comment] 2022-11-14 23:26
Related to https://github.com/godotengine/godot/issues/52558 and https://github.com/godotengine/godot/issues/65393.

**Comment by kleonc** [comment] 2022-11-28 21:19
Seems like the cause is:
- `FileAccess::store_var` (or more precisely [`encode_variant` function](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/core/io/marshalls.cpp#L1117)) with `p_full_objects = true` for an `Object` [stores its every property with `PROPERTY_USAGE_STORAGE`](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/core/io/marshalls.cpp#L1513-L1528) (and only such properties),
- [`Object.script` property has `PROPERTY_USAGE_STORAGE` flag](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/core/object/object.cpp#L502) (it's part of `PROPERTY_USAGE_DEFAULT`).
- [`Resource.resource_path` property has no `PROPERTY_USAGE_STORAGE` flag](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/core/io/resource.cpp#L438),
- [`GDScript.script/source` property has `PROPERTY_USAGE_STORAGE` flag](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/modules/gdscript/gdscript.cpp#L1000) (it's part of `PROPERTY_USAGE_NO_EDITOR`).

So when an `Object` with a `GDScript` script attached is being saved, its `script` is saved as a pure data: the whole source code is written directly, no reference (path) to the resource file which it's loaded from is saved. Thus when the loading happens during `FileAccess.get_var()` (`decode_variant` function) a new `GDScript` resource is being created and the saved source code is set to it. At this point [the script is reloading itself](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/modules/gdscript/gdscript.cpp#L988-L991) which leads to [a parser error](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/modules/gdscript/gdscript.cpp#L856-L866) as the global class name defined in the script (with `class_name`) is already registered (by the original script file, who's source code was just duplicated).

---

I guess it would make sense to marshall `Resource`s as path-only instead? (and let the `ResourceLoader` do its job)

**Comment by kleonc** [comment] 2022-12-26 17:06
The same happens when callling `Resource.duplicate(true)` (#70570).

**Comment by voylin** [comment] 2023-01-10 02:06
Has anybody been working on this? Else I would like to take a look and see if I can fix this as it's a big inconvenience for my current game project.

**Comment by aaronfranke** [comment] 2023-02-05 09:03
Please re-test in the latest master or a recent beta. PR #71142 has likely fixed this issue.

**Comment by Eliwi** [comment] 2023-02-17 01:53
Nope, I still get this error (I'm on RC 2)

**Comment by jsonify** [comment] 2023-02-24 05:54
I just got the same error on RC 4.

**Comment by Vennnot** [comment] 2023-02-26 09:00
Getting this error as well currently. Cannot continue work on my project

**Comment by gaintap** [comment] 2023-04-25 08:50
Still getting this error in 4.0.2, posting hacky workaround. I was able to bypass the error by making a new script and class name that extends the problem class and loading objects with the empty script attached instead.

Example dummy script: attack_resource_import_only.gd

```
extends AttackResource 
class_name = AttackResourceImportOnly

func _ready():
     pass
```
My use case is loading a resource that contains an array of resources (a weapon resource with an array of "available attacks" resources). Nesting the attack resource within the weapon resource triggered the error but it's working by using the dummy import only resource. I can use the autocompletion of the main class (AttackResource) on objects loaded with the dummy class, so not using the dummy class anywhere other than assigning it in the inspector.

**Comment by muhuk** [comment] 2023-07-11 10:29
This is still happening in newly released version `4.1`.

**Comment by DispairingGoose** [comment] 2023-07-21 19:46
Also happening in `4.1.1`

**Comment by DispairingGoose** [comment] 2023-07-21 20:09
Has anybody been able to come up with any work arounds? I've tried using the `var_to_bytes` and `bytes_to_var` methods, however these produce `EncodedObjectAsID`s instead of instances of resource classes

**Comment by ForestGameDev** [comment] 2023-10-27 16:53
I wrote this code to convert objects to dictionaries automatically and store them using store_var (with full_objects =  false), then read them back from dictionary to object. It's kind of reinventing the wheel, but may help someone until this is fixed: https://www.reddit.com/r/godot/comments/17hrj2q/sharing_my_save_state_code_not_converting_to_json/

@DispairingGoose do you know if using var_to_str / str_to_var approach will force you to export the game with gd script files not compiled (i.e. as plan text)? [https://ask.godotengine.org/99313/save-file-breaks-after-game-export](This question) made my think it could be the case, even when var_to_str is not mentioned there :), but in my mind it would make sense that is the case.

**Comment by DispairingGoose** [comment] 2023-11-26 15:25
> I wrote this code to convert objects to dictionaries automatically and store them using store_var (with full_objects = false), then read them back from dictionary to object. It's kind of reinventing the wheel, but may help someone until this is fixed: https://www.reddit.com/r/godot/comments/17hrj2q/sharing_my_save_state_code_not_converting_to_json/
> 
> @DispairingGoose do you know if using var_to_str / str_to_var approach will force you to export the game with gd script files not compiled (i.e. as plain text)? This question https://ask.godotengine.org/99313/save-file-breaks-after-game-export made my think it could be the case, even when var_to_str is not mentioned there :), but in my mind it would make sense that is the case.

It seems to be the case that you don't need to export gdscript files as plain text using the following code:
```
func save() -> void:
	var file = FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	file.store_string(var_to_str(self))
	file.close()


static func load() -> PlayerData:
	var file = FileAccess.open(SAVE_PATH, FileAccess.READ)
	var object = str_to_var(file.get_as_text())
	file.close()
	print(object)
	return object
```

Tested on 4.1.3 - I have attached the project I tested with.
[spoonsandforks.zip](https://github.com/godotengine/godot/files/13467240/spoonsandforks.zip)

**Comment by dwalter** [comment] 2024-02-22 01:05
I found a temporary work around. Change the `class_name` like:

e.g.
`ObjectSpriteCreator.gd`
```
# was: class_name ObjectSpriteCreator
class_name ObjectSpriteCreatorV2
```

And when you load (keeping the filename the same wasn't an issue):
`MainNode2dScript.gd`
```
const ObjectSpriteCreatorV2 = preload("ObjectSpriteCreator.gd")
```

Changing the filename didn't have an effect and I tried loading the project with this change and then trying to change it back and loading again to see if the cache clears but that didn't work, so this is my current work-around.

**Comment by dwalter** [comment] 2024-04-07 01:07
This is still an issue and popped up again for all the new classes/ files I created after doing a linux build.

**Comment by mournguard** [comment] 2024-04-15 05:29
Happening to me on v4.3.dev5.official [89f70e98d] - Doesn't that basically makes store/get_var kind of useless?

**Closed** 2024-04-15 11:42 UTC
Labels: bug, topic:core, topic:gdscript, confirmed

**Comment by KyleReese** [comment] 2024-07-15 04:11
I am still seeing this with the latest 4.3 beta when trying to FileAccess.get_var() a dictionary with a custom resource as the value.

**Comment by BCG-Jackson** [comment] 2024-09-02 23:03
not fixed

**Comment by dalexeev** [comment] 2024-09-04 17:25
@KyleReese, @BCG-Jackson Sorry for the delay. Can't reproduce this in 4.3 with the MRPs [one](https://github.com/godotengine/godot/issues/68666#issue-1448744681) and [two](https://github.com/godotengine/godot/issues/68666#issuecomment-1826813049). Note that you must export the variable to be stored in a file. There is currently an inconsistency between text and binary serialization for resources, see #80894 and #80897.

If your issue is still not resolved, please provide reproduction steps, MRPs, and/or other details.

**Comment by hex358** [comment] 2024-11-04 04:07
Ran into the same issue when trying to binary save scene at its current state (props, vars, nodes etc.) using var_to_bytes(true) and then trying to load it using bytes_to_var
