### ISSUE TITLE
Visual Studio can't open solution (Unknown solution item type) 

### ISSUE THREAD

**Issue by irmantus** [godotengine/godot#67324] opened 2022-10-12 20:00 UTC
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

macOS 12.4

### Issue description

Can't open solution on Visual Studio for Mac

### Steps to reproduce

1. Create new project
2. Create C# script
3. Try to open script in VS
<img width="363" alt="image" src="https://user-images.githubusercontent.com/37515045/195436091-eef150e5-e11c-4699-bd4e-cb872d62dc92.png">

**Comment by Calinou** [comment] 2022-10-12 23:11
Duplicate of https://github.com/godotengine/godot/issues/67029.

**Closed by Calinou** 2022-10-12 23:11 UTC
Labels: bug, platform:macos, topic:editor, topic:dotnet
