### ISSUE TITLE
lagging when zooming a script using Distraction Free Mode

### ISSUE THREAD

**Issue by WIL-TZY** [godotengine/godot#82144] opened 2023-09-22 19:58 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

The program is lagging when I zoom out in a script using Distraction Free Mode. The script was just a CharacterBody2D script using the Basic Movement template. 
The program even crashed once, though I'm having trouble reproducing the crash, but I can reproduce the script editor lag.

My project is very initial, I created it yesterday. 
![godot-script](https://github.com/godotengine/godot/assets/94930303/eff3bf52-e4ee-4726-907c-a0b0c316c92c)

### Steps to reproduce

Toggle "Distraction Free Mode" in the script editor.
Zoom in (or out) some times (you'll notice the program becomes laggy).
Optionally, if you click anywhere on the script to start typing, you'll notice it will lag for a few seconds.

### Minimal reproduction project

[ScriptLagTest.zip](https://github.com/godotengine/godot/files/12704157/ScriptLagTest.zip)

**Comment by Calinou** [comment] 2023-09-22 20:22
I can confirm this on 4.2.dev 7831eedf1 (Linux, GeForce RTX 4090):

https://github.com/godotengine/godot/assets/180032/74f3da82-fbba-4442-acbd-7faedaedf36b

This is likely because all editor settings are occasionally reloaded when there's no need to (which is also what happens when you change editor theme settings or colors, for instance).

**Comment by MewPurPur** [comment] 2023-09-23 03:38
If I were to guess, it's because zooming in/out actually changes the font size in the editor settings. So `EDITOR_THEME_CHANGED` and likely `EDITOR_SETTINGS_CHANGED` fire, causing a lot of code to propagate and resulting in extreme slowdowns.

Maybe we have some opportunities to somehow speed up editor theme changes? Or to localize impacts? @YuriSizov has probably thought about this stuff.

**Comment by YuriSizov** [comment] 2023-09-23 13:59
@MewPurPur You are generally correct, yes. Editor settings change and that triggers an update to the entire editor theme. There are two issues with this:
- The entire theme always gets regenerated;
- The entire editor GUI needs to refresh.

The second issue is unavoidable if anything about themes changes. I haven't profiled to know if this is a big bottleneck or not though. We are getting to a place where we could be smarter about handling theme changed notifications and avoid redrawing if no relevant property was modified. But we aren't there yet.

So in this case, even if we add some guard to avoid updating the code editor twice, the rest of the UI still would update.

The first issue is way more approachable and I do indeed have some ideas. I didn't plan to work on them right now, but I may give it a go and expedite that. But again, I haven't profiled anything to know how much of a boost that would be.

**Comment by MajorMcDoom** [comment] 2024-01-17 05:30
Hi there, just wanted to add my two cents, since I came to add a similar proposal and saw this one.

I actually use zoom in/out all the time as part of my coding process in Visual Studio. It's important to me to be able to see my code at whatever level of detail I need. Sometimes I like to see more of the "big picture", and sometimes I like to really focus in on a small section.

I think what struck me as odd is that script editor zoom (and shader editor zoom) was implemented as an font size preference, instead of as a zoom scale applied on top and saved in the `.godot` folder or something. For comparison, you can zoom in the 3D viewport, and that is also saved, but it is saved differently and doesn't require a slow save/refresh.

Could text zoom potentially be implemented that way instead?

**Comment by YuriSizov** [comment] 2024-01-17 11:23
> Could text zoom potentially be implemented that way instead?

Fonts are rasterized, they aren't rendered in vector. This is different from the 3D environment, which is rendered based on the spatial information. So, no, without a significant rework of how fonts work in general this isn't possible.

**Comment by MajorMcDoom** [comment] 2024-01-17 12:42
> > Could text zoom potentially be implemented that way instead?
> 
> Fonts are rasterized, they aren't rendered in vector in realtime. This is different from the 3D environment, which is rendered based on the spatial information. So, no, without a significant rework of how fonts work in general this isn't possible.

What I meant is not to change the render method, but rather change the nature of what a zoom change is. You can still make it increment as a font size "offset" without treating it as an editor preference change. And consequently, without needing to trigger a whole preference save or theme refresh.

**Comment by MajorMcDoom** [comment] 2024-01-17 16:59
I did a quick tool script implementation to show what I mean. The "font size offset" is just implemented as a font size override that can be saved to the project cache or editor cache or whatever. It's on top of the long-term preference. You can just reset it to zero, and it will show the underlying font size as per the editor settings. This is how Visual Studio works.

![font_size_override](https://github.com/godotengine/godot/assets/13228932/08243611-819d-4d99-8a5d-a70aed122961)

**Comment by MajorMcDoom** [comment] 2024-02-18 04:12
Hi all, I made a PR #88474 which (among other things) has a fix for this. Please take a look and give your thoughts. Thanks! :)

**Closed** 2024-02-22 10:25 UTC
Labels: bug, topic:editor, confirmed, performance
