### ISSUE TITLE
Exported Vector2 inspector value is ignored

### ISSUE THREAD

**Issue by sudoio** [godotengine/godot#15264] opened 2018-01-02 18:27 UTC
**Godot version:**
v3.0.beta.build2

**OS/device including version:**
Fedora Linux 27 x86_64

**Issue description:**
- In the script, I have:
```gdscript
export(Vector2) var GRID_SIZE = Vector2(1920, 1080)
```
- If I change the value in the Inspector to e.g. `(1920, 1000)`:

![inspector](https://user-images.githubusercontent.com/19972511/34494757-faed7a34-f002-11e7-9b63-4b88c97c588c.png)

- The result doesn't change (doesn't matter if changed in `World.tscn` or  `Grid.tscn`)
- However, if I change the value in the script, it works fine

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/1598339/project.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment] 2018-01-02 19:04
I just copied your code and changed value to 1920, 1000 in inspector.
and run.

```gdscript
export(Vector2) var GRID_SIZE = Vector2(1920, 1080)

func _ready():
	print(GRID_SIZE)  # prints (1920, 1000)
```

how did you check if it's not changed?

**Comment by volzhs** [comment] 2018-01-02 19:11
I just checked your project.
I will explain with your code.

```gdscript
extends Node2D

export(Vector2) var ROWS_COLUMNS = Vector2(10, 10)
# this value is updated after initial time and before _ready
export(Vector2) var GRID_SIZE = Vector2(1920, 1080)

var Tile = preload("res://scenes/GridTile.tscn")

# this is executed when initial time
# so, whatever value was set, this will be initial value of GRID_SIZE which is 1920, 1080
var TILE_SIZE = GRID_SIZE / ROWS_COLUMNS

func _ready():
	draw_grid()
	
func draw_grid():
	for row in ROWS_COLUMNS.x:
		for column in ROWS_COLUMNS.y:
			draw_tile(column, row)
			
func draw_tile(column, row):
	var tile = Tile.instance()
	add_child(tile)
	
	tile.position.x = TILE_SIZE.x * (row + 0.5)
	tile.position.y = TILE_SIZE.y * (column + 0.5)
```

but with `onready` keyword...

```gdscript
# this will be executed just before _ready
# so, GRID_SIZE is updated to what you changed in inspector
onready var TILE_SIZE = GRID_SIZE / ROWS_COLUMNS
```

after all, it's not a bug.

**Comment by groud** [comment] 2018-01-02 21:42
Closing then :)

**Closed by groud** 2018-01-02 21:42 UTC
Labels: archived
