### ISSUE TITLE
Issue with Godot 3.4.4 where a portion of the UI's right side is hidden under my screen.

### ISSUE THREAD

**Issue by EyeBallTank** [godotengine/godot#61644] opened 2022-06-02 22:13 UTC
### Godot version

3.4.4, Standard version, win32

### System information

Windows 10, GLES3 (That's how Godot is set on my PC at least), screen resolution is 1280x1024, Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz 3.70 GHz, 64 bits system even though i used a 32 version of Godot (Precaution related reasons since my PC is a bit of a mess)

### Issue description

As i'm working on the platformer tutorial from GDQuest's Youtube series (Which is from 2019, so i noticed some differences in the program), i ran into an issue that i don't think i could work around:
Some features are not available on my screen size, because they are hidden at the right side.

But this only happens when i had ColorRect selected, so i couldn't press the key icon.
Apparently, selecting different nodes in the node tree of the Portal scene (Like AnimationPlayer or CollisionShape2D), the UI interface was at fixated sizes that fit the screen.

I noticed some options to change the positions of the Inspector/Node/etc sections around the main preview screen but for some reason, it's when i'm selecting ColorRect where this stuff can't happen (And during that, i can't even resize stuff either).

So this whole time, i had access to these sidebar features just fine but then the Inspector/Node sidebar ends up crossing over my screen.
Honestly, i think this happened before but it didn't bother me because i was able to click on the node signal stuff just fine.

![here it is](https://user-images.githubusercontent.com/93493280/171745395-fc85a36d-9450-4707-a6f4-3f6e3d4ffb23.PNG)

As of right now, i saved the project and ended up saving the Portal scene in the src/objects folder with the Coin scene, even if this means i just skipped some stuff in the tutorial (But it's in case i have to take a break from this stuff in general, because i still plan to keep this going).
Maybe this is a result of me getting way too late into doing more stuff with the overall program but i still look forward to make something good with it.

If this very specific issue was already reported as an issue, let me know if i'm not the only one.

### Steps to reproduce

I just had the program open long enough and only noticed it when watching the second episode of a series by GDQuest, where i noticed i couldn't see a button that i had to press, in order to follow the tutorial step by step.

**Comment by Calinou** [comment] 2022-06-03 08:29
Duplicate of https://github.com/godotengine/godot/issues/31133

**Closed by Calinou** 2022-06-03 08:29 UTC
Labels: bug, topic:editor
