### ISSUE TITLE
VideoPlayer's stream_position property don't work. 

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#32358] opened 2019-09-26 04:39 UTC
**Godot version:**
3.1.1

**OS/device including version:**
macos 10.14

**Issue description:**
```
video.stream = load("res://res/2d/vid/v1.WebM")
video.stream_position = 5
video.play()
```
or
```
video.stream = load("res://res/2d/vid/v1.WebM")
video.play()
video.stream_position = 5
```
all don't seek the video

I want to use controller control the video play status . Is there any way can do this ?

**Comment by hungrymonkey** [comment] 2019-09-28 00:08
duplicate
https://github.com/godotengine/godot/issues/14430#issuecomment-535149609

**Comment by hungrymonkey** [comment] 2019-10-13 14:08
You should try godot 3.2 Alpha https://downloads.tuxfamily.org/godotengine/3.2/alpha1/ and use gdnative
https://www.youtube.com/watch?time_continue=2&v=kMetfTX54cE

**Comment by Calinou** [comment] 2019-10-13 14:14
Duplicate of #14430.

**Closed by Calinou** 2019-10-13 14:14 UTC
Labels: topic:audio
