### ISSUE TITLE
Crash, if any variable have reference to delete node

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#24475] opened 2018-12-19 13:53 UTC
**Godot version:**
3.0.6 - 3.1a3 

**OS/device including version:**
Windows 10 x64

**Issue description:**
App is freez and crash, if any variable have reference to delete node. 

**Steps to reproduce:**
```
var n
func _ready():
	n = Node.new()
	add_child(n)
	n.queue_free()   # crash
#	n = null  # no crash
```
Run project - and in editor go to remote debug and select Node with this var.

**Comment by qarmin** [comment] 2018-12-19 14:11
Can't reproduce in Windows 10 Godot 0cff752
Can you open godot via console/terminal and then run a project and see what was written to console?

**Comment by SuperDIMMaX** [comment] 2018-12-19 14:11
nope... just freez and crash

**Comment by qarmin** [comment] 2018-12-19 14:22
No, just empty window without any error message and freeze.

**Comment by AlexHoratio** [comment] 2018-12-19 14:34
Unless I'm missing something this is intended(?) behaviour, if you're referencing n after freeing it you're going to have to use ``weakref(n).get_ref()`` to check that n exists and is not a previously freed node.

**Comment by SuperDIMMaX** [comment] 2018-12-19 14:47
no, no referense... no use this var.... just freez
i try another Windows, try 3.0.6 stable 3.1a3.... - crash
[https://www.dropbox.com/s/s5lx9nxfmer40wx/test.zip?dl=0](url)
can you drop project without crash?

**Comment by SuperDIMMaX** [comment] 2018-12-19 15:05
Find. Run project - and in editor go to remote debug.

**Comment by Zylann** [comment] 2018-12-19 15:50
@AlexHoratio AFAIK it is meaningless to use weakref on nodes because they are not references. I thought Reduz added a way to check if a var holding an object is valid, recently? Also a crash (i.e no breakpoint) should be fixed, if that happens in an editor build.

**Comment by SuperDIMMaX** [comment] 2018-12-19 15:58
> Reduz added a way to check if a var holding an object is valid
Yep, I know :).
[https://github.com/godotengine/godot/commit/ff1e7cfbf4b7ad9b327588ce7dffb43d31fee3e9](url)
 But, crash in an editor build... ((( Any variants to avoid this?

**Comment by Zireael07** [comment] 2018-12-19 16:05
I am using 3.0.3 and for quite some time I had a similar problem running one of my projects from editor. @Zylann can you clarify what do you mean by crash (i.e no breakpoint) - in my case, it did crash but it showed the full stacktrace telling me what exactly happened, so exactly like a breakpoint was set.

**Comment by SuperDIMMaX** [comment] 2018-12-19 16:07
temp small hack:
`	set_meta("n", Node.new())
	add_child(get_meta("n"))
	get_meta("n").queue_free()`
store in metadata :/ ... no crash :)

**Comment by Zylann** [comment] 2018-12-19 16:09
@Zireael07 sometimes people say "crash" when it's actually an error catched by debugger. If it really crashes with no info in non-release build, that must be fixed. If you get an error with stack trace in the editor, then it's fine.

**Comment by Zireael07** [comment] 2018-12-19 16:16
O_o you can add metadata as children? super weird

@SuperDIMMaX: Do you see an error with stack trace when the editor build crashes?

**Comment by williamd1k0** [comment] 2018-12-19 16:20
I cannot reproduce it on Windows.

@SuperDIMMaX Could you try the following approach?

```gdscript
extends Node

var n
func _ready():
	n = Node.new()
	add_child(n)
	n.call_deferred('queue_free')
	prints('queue_free', n)
	yield(get_tree(), "idle_frame") # Just waiting to check it again in the next frame
	prints('_ready:done', n)
	n = null
```

Output (no crash):
```
queue_free [Node:1067]
_ready:done [Deleted Object]
```

**Comment by SuperDIMMaX** [comment] 2018-12-19 16:21
Nope... no error... app freez, then crush. Editor say:
`ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190`

**Comment by SuperDIMMaX** [comment] 2018-12-19 16:32
> O_o you can add metadata as children? super weird

Nope. I store reference to object in metadata vars.

**Comment by SuperDIMMaX** [comment] 2018-12-19 16:35
I guess, editor not validate reference and try get non exist object.

**Comment by SuperDIMMaX** [comment] 2018-12-19 16:40
Time mark this as bug?

**Comment by girng** [comment] 2018-12-20 16:12
can confirm this happens on 3.0.6, w10, 64-bit
i get spammed `<couldn't map PC to fn name>` , no other useful info is printed, unfortunately

**Comment by KoBeWi** [comment] 2020-07-05 14:25
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 19:45
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 19:45 UTC
Labels: bug, topic:core, topic:editor
