### ISSUE TITLE
Exported project does not open (scene parse error), works fine in editor

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#21524] opened 2018-08-28 10:08 UTC
**Godot version:**
6b10e3750 (both tools and export compiled from same source)

**OS/device including version:**
Windows 10

**Issue description:**
Game opens and runs fine with editor, but when exported it exits immediately. Debug build with `-v` outputs:

```
[...]
Loading resource: res://Game.tscn
Loading resource: res://Game.gdc
Loading resource: res://Enceladus/Enceladus.tscn
ERROR: ResourceFormatLoaderText::load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene\resources\scene_format_text.cpp:1225
ERROR: Failed loading resource: res://Enceladus/Enceladus.tscn
   At: core\io\resource_loader.cpp:190
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Can't preload resource at path: res://Enceladus/Enceladus.tscn
          At: res://Game.gdc:14
ERROR: GDScript::load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:771
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err != OK ' is true. returned: RES()
   At: modules\gdscript\gdscript.cpp:2118
ERROR: Dictionary::_unref: Condition ' !_p ' is true.
   At: core\dictionary.cpp:171
```

If I'm reading it correctly, It can't parse `res://Enceladus/Enceladus.tscn`, which causes error to propagate to `preload` in `Game.gd`.

There are no unusual files (json, etc) that are used/imported in the `Enceladus.tscn`

If I remove references (preloads) to `Enceladus.tscn` game runs fine - I'm assuming there is something in the scene that causes the error.

When I remove everything from the scene (every child), it **still** crashes with same output. Complete contents of `Enceladus.tscn` with every child node removed: [Enceladus.zip](https://github.com/godotengine/godot/files/2327539/Enceladus.zip)

Files were not edited by hand. I assume that the dangling `Image` is what causes problem.

**Steps to reproduce:**
Happens in a large project, unable to create minimal reproduction.

**Expected behaviour:**
Best case: project runs when exported as it does in the editor.
Sufficient: increase verbosity of the error message in debug mode, allowing pinpointing of corruption in the scene file in case of further corruptions.

Ad-hoc advice as how to recover the scene would be also greatly appreciated, but the core issue is that the scene got corrupted in first place.

EDIT: Corrected the hash

**Comment by eon-s** [comment] 2018-08-28 10:34
48d0def do not seem to be a valid commit.

And that scene has a custom `_editor_icon` metadata with the icon embedded, try removing that icon subresource and all references from the tscn file.

I do not know how do you managed to do that without a custom editor or importer.

**Comment by lekoder** [comment] 2018-08-28 10:39
@eon-s I took the commit from my own project. Correct one is 6b10e3750.

The scene was over a week in the making, I can't really backtrack everything I did there. I will be vigilant for this to re-surface - I actually think I got this problem before, but it was a throw-away scene so I just re-created it.

How do I go about removing `_editor_icon`? Just edit it out with text editor, or is there an option for it in the Godot editor itself?

**Comment by akien-mga** [comment] 2018-08-28 10:49
With a debug build and the provided `Enceladus.tscn` file, I get this error:
```
ERROR: create_from_image: Condition ' p_image.is_null() ' is true.
   At: scene/resources/texture.cpp:190.
```
When running from the editor I also get:
```
ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<Image>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1013.
ERROR: texture_get_data: Condition ' !texture->active ' is true. returned: Ref<Image>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1013.
```
I haven't tried a release build, but it's expected that errors in debug builds can lead to crashes in release builds (as less checks are done to increase performance).

To fix your scene, you should be able to do something like this manually:
```
diff --git a/Enceladus.tscn b/Enceladus.tscn
index f1a4c8b..6925fb0 100644
--- a/Enceladus.tscn
+++ b/Enceladus.tscn
@@ -1,26 +1,4 @@
 [gd_scene load_steps=3 format=2]
 
-[sub_resource type="Image" id=3]
-
-data = {
-"data": PoolByteArray( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 45, 59, 0, 82, 91, 121, 0, 83, 91, 121, 0, 83, 91, 121, 0, 82, 91, 121, 0, 40, 45, 59, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 122, 131, 176, 6, 163, 181, 239, 108, 164, 182, 242, 200, 165, 183, 243, 242, 165, 183, 2
43, 242, 164, 182, 242, 200, 163, 181, 239, 108, 122, 131, 176, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 122, 137, 181, 27, 164, 182, 242, 206,
 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 164, 182, 242, 206, 122, 136, 181, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 122, 131, 176, 6, 164, 182, 242, 206, 165, 183, 243, 255, 165, 183, 243, 227, 160, 181, 237, 89, 164, 177, 238, 25, 164, 177, 238, 25, 160, 181, 237, 89, 165,
 183, 243, 227, 165, 183, 243, 255, 164, 182, 242, 206, 122, 131, 176, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 44, 59, 0, 161, 180, 239, 107, 165, 183, 243, 255, 165, 183, 243, 227, 123,
 136, 181, 18, 38, 45, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 45, 57, 0, 121, 136, 181, 19, 165, 183, 243, 227, 165, 183, 243, 255, 161, 180, 239, 107, 39, 44, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82
, 91, 121, 0, 164, 182, 243, 198, 165, 183, 243, 255, 160, 180, 237, 89, 38, 45, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 41, 58, 0, 163, 174, 238, 89, 165, 183, 243, 255,
 164, 182, 243, 198, 82, 91, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 91, 121, 0, 165, 183, 242, 241, 165, 183, 243, 255, 163, 177, 238, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 163, 177, 238, 25, 165, 183, 243, 255, 165, 183, 242, 241, 82, 91, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 91, 121, 0, 165, 183, 242, 241, 165, 183, 243, 255, 158, 180, 241, 
23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 162, 176, 237, 24, 165, 183, 243, 255, 165, 183, 242, 241, 82, 91, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 91, 121, 0, 164, 182, 243, 198, 165, 183, 243, 255, 155, 178, 236, 87, 35, 43, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 43, 57, 0, 155, 178, 236, 87, 165, 183, 243, 255, 164, 182, 243, 198, 82, 91, 121, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 45, 59, 0, 162, 181, 239, 107, 165, 183, 243, 255, 165, 183, 243, 226, 121, 135, 181, 18, 38, 45, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 45, 57, 0, 121, 135, 181, 18, 164, 182, 243, 226, 165, 183, 243, 255, 162, 181, 239, 107, 40, 45, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 118, 133, 177, 7, 164, 182, 242, 206, 165, 183, 243, 255, 165, 183, 243, 227, 160, 181, 237, 89, 164, 177, 238, 25, 164, 177, 238, 25, 160, 181, 237, 89, 165, 183, 243, 227, 165, 183, 243, 255, 164, 182, 242, 206, 118, 133, 177, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 122, 136, 180, 27, 164, 182, 242, 207, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 165, 183, 243, 255, 164, 182, 242, 206, 122, 136, 180, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 122, 131, 176, 6, 163, 181, 239, 108, 164, 182, 242, 200, 165, 183, 243, 242, 165, 183, 243, 242, 164, 182, 242, 200, 163, 181, 239, 108, 122, 131, 176, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 45, 59, 0, 82, 91, 121, 0, 83, 91, 121, 0, 83, 91, 121, 0, 82, 91, 121, 0, 40, 45, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
-"format": "RGBA8",
-"height": 16,
-"mipmaps": false,
-"width": 16
-}
-
-[sub_resource type="ImageTexture" id=2]
-
-flags = 0
-storage = 0
-lossy_quality = 0.7
-flags = 0
-image = null
-size = Vector2( 16, 16 )
-
 [node name="Enceladus" type="Node2D"]
-__meta__ = {
-"_editor_icon": SubResource( 2 )
-}
```

We still need to find out how such invalid metadata could be added, and how to improve error reporting in this case though.

**Comment by eon-s** [comment] 2018-08-28 10:55
Removing (with a text editor) the meta entry and related sub resources should be enough to recover it.

**Comment by akien-mga** [comment] 2018-08-28 11:32
@willnationsdev Above comment sounds like one of your recent PRs caused this bug.

**Comment by lekoder** [comment] 2018-08-28 11:59
This is not, however, the root cause. My problem was related to filename case in/sensitivity (of course) somewhere else in the game, this metadata/icon just obfuscated it. You might still want to fix it, but it is not critical (does not actually break the exports).

**Comment by willnationsdev** [comment] 2018-08-28 19:49
@akien-mga Oh, interesting. I guess I'll have to look into how that might be happening.

**Comment by willnationsdev** [comment] 2018-08-28 20:32
@akien-mga I have a fix for that specific problem. Tested it with my own build, and reproducing the same steps no longer creates the problem in question.

**Comment by hpvb** [comment] 2018-08-28 22:49
It is generally true that ERROR messages in the editor will crash a release build. This is as far as I understand by design.

**Comment by akien-mga** [comment] 2018-08-29 06:33
I thought we added some code on Windows to trigger warnings when load resources with incorrect case (which works on Windows, but wouldn't work anywhere else).

@lekoder I guess your example shows that it's not working as it should? If you can reproduce a minimal project with the same kind of case mismatch that causes an error on export, that would be great to debug further and improve the error reporting.

**Comment by lekoder** [comment] 2018-08-29 06:48
@akien-mga There is a warning when filename has different case, but I had a **directory** with different case, and that is not reported. [Minimal reproduction](https://github.com/lekoder/godot-directory-case-unwarned).

I think it would be great if it was interpreted as error and highlighted in the code editor - it's not like the code is going to work on windows (after export) anyway.

**Comment by willnationsdev** [comment] 2018-09-20 00:41
There was mention of a dangling Image in the scene file earlier in this Issue. Did the recent editor icon refactoring fix this, or is this still a bug?

**Comment by akien-mga** [comment] 2019-01-23 14:31
What's the status on this issue? I think the original issue has been fixed, are there other points pending that would be worth moving to a new issue?

**Comment by akien-mga** [comment] 2020-01-08 10:03
> What's the status on this issue? I think the original issue has been fixed, are there other points pending that would be worth moving to a new issue?

Re-read and it does seem to me that later comments as of https://github.com/godotengine/godot/issues/21524#issuecomment-416557782 are about a different issue.
#21544 fixed the issue about a creating dangling `Image` references that raise errors.

**Closed by akien-mga** 2020-01-08 10:03 UTC
Labels: bug, topic:core
