### ISSUE TITLE
Light2d ignores mask, occluders on all layers cast shadows

### ISSUE THREAD

**Issue by piotrf230** [godotengine/godot#39133] opened 2020-05-28 22:24 UTC
Godot Engine v3.2.1.stable.official (via Steam)

Windows 10
x64
Appears in both OpenGL 3.0 and 2.0 setup
Intel Core i7-770K CPU 4.20GHz
GeForce GTX 1060 6GB

Occluder2D, set on Light Mask layer 2 casts shadow, but Light2D is set on layer 1. When the Layer 1 on Light2D's Shadow Item Cull Mask is uncheched and checked again, everything looks good in editor, but reverts when project is played/exported or Light2D is saved as Scene.

Steps to reproduce:
1. In new project add 2 Light Occluders 2D, 1 Light2D (enable shadow) and background to see shadows (in my example it's Polygon2D)
2. Set one of the occluders' Light Mask to layer 2 only, it still casts shadow
3. Uncheck and check Light2D's shadow's Item Cull Mask Layer, shadow of second occluder shoudn't appear
4. Play Project, the shadow shows again, but only in game window
![occluder issue](https://user-images.githubusercontent.com/45321260/83199733-14607280-a142-11ea-9dda-5643c1caccd3.png)

Minimal reproduction project:
[Test.zip](https://github.com/godotengine/godot/files/4698584/Test.zip)

**Comment by Calinou** [comment] 2020-05-29 07:02
Duplicate of #29612?

**Comment by piotrf230** [comment] 2020-05-29 07:18
Oh, I didn't find this issue while searching, I'm not sure if it is exactly the same bug, but might have the same origin.

**Comment by lawnjelly** [comment] 2020-05-30 06:25
I've just been looking at this. It seems to be a bug that appears in the editor sporadically. I.e. I think the run version is correct, but the editor will sometimes show one shadow and sometimes both.

When I step through `canvas_light_shadow_buffer_update` I can see the occluder instances, in some cases in the editor there are 2 (correct) and in some cases only 1 (wrong).

This seems to be triggered when I change the shadow item cull mask for the light. If it starts at layer 1 they both show, if I click to only layer 2 in the editor neither show, when I click back on layer 1 both show, and when i turn off layer 2 (to the same situation as at the start) only the left shadow shows.

**Comment by lawnjelly** [comment] 2020-05-30 07:24
Ok I think the weird behaviour might be down to this.

* On startup, the `shadow_cull_mask` doesn't appear to being set from the main code to visual server, thus it is using the default -1 (which is setting on all occluders)
* When you do set the `shadow_cull_mask` in the editor, it is being set, so it then starts doing its thing
* The `shadow_cull_mask` behaviour appears to be different from the layer masks used in the rest of godot (as I understand them):

In other parts of godot layer 1 has a special significance, showing everything (I guess being equivalent to all bits set). This doesn't appear to happen with the shadow mask.

The first thing to do will be to ensure that the `shadow_mask` is set properly on startup in the editor and in game, then decide what is the desired behaviour for the layers.

**Comment by lawnjelly** [comment] 2020-05-30 07:57
Ok the initialization problem may be quite simple. I figured out that when your light `shadow_mask` is set to layer 1 only (the default) nothing is written in the tscn file, therefore there is no call to `canvas_light_set_item_shadow_cull_mask` when starting the scene.

The problem is that the default value for `shadow_mask` in the constructor is -1, rather than 1.

I can change the constructor to 1. However we need to decide what is the intended behaviour for layers here. If the desire is to have the same behaviour of a master layer, then -1 may in fact be correct, and the problem is in how the layers are applied. We just need a consistent rule.

**Comment by akien-mga** [comment] 2020-06-02 08:46
Fixed by #39162 (`3.2`) and 61b3eb3b28671a397ed873d47db925f662382e74 (`master`).

**Closed by akien-mga** 2020-06-02 08:46 UTC
Labels: bug, topic:rendering
