### ISSUE TITLE
Autocompletion does never hit `Object.get_argument_options`.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#76594] opened 2023-04-29 21:50 UTC
### Godot version

v4.1.dev.custom_build [9f12e7b52]

### System information

Windows 10

### Issue description

Could be the same as #44480.

When using `Object.connect` the autocompletion won't suggest signal names. The signal names are ment to be populated inside `Object.get_argument_options` which inturn should be called [here](https://github.com/godotengine/godot/blob/9f12e7b52d944281a39b7d3a33de6700c76cc23a/modules/gdscript/gdscript_editor.cpp#L2504-L2517). However when reaching this code part Line 2505 will result in `NULL` and the method will never be called.

### Steps to reproduce

- open the mrp
- type a parenthesis behind `connect`
- no suggestions will be shown

### Minimal reproduction project

[context_based_autocompletion.zip](https://github.com/godotengine/godot/files/11360134/context_based_autocompletion.zip)

**Comment by ajreckof** [comment] 2023-04-30 00:14
This is in fact a duplicate of #76515
This is a bit more general it might happen with other function, discovered it with `emit_signal`.
It happens whenever the script editor does not find an object to use completion on it. It might happen for example if the scene is closed and he can't find the node this script is attached to.

**Comment by adamscott** [comment] 2023-04-30 00:39
Duplicate of #76515

**Closed by adamscott** 2023-04-30 00:39 UTC
Labels: bug, archived, topic:gdscript, topic:editor, confirmed
