### ISSUE TITLE
macOS Game Preview location

### ISSUE THREAD

**Issue by adamprocter** [godotengine/godot#12657] opened 2017-11-05 14:39 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS 10.13.1
Godot 3 Alpha Build 2
Radeon Pro 460 4 GB
Intel HD Graphics 530 1536 MB

**Issue description:**
Working in Godot 3 , Press play to view game. the window with game appears but is not in the middle of the screen but bottom right obscuring half of it. Moving screen to center the new position is not remembered. See Image attached
<img width="1639" alt="screenshot 2017-11-05 14 38 04" src="https://user-images.githubusercontent.com/123951/32415780-0889a892-c237-11e7-8321-2e147cdcbbd5.png">

Same issue when using same Spaces

**Steps to reproduce:**
Open project, press play

**Comment by Zireael07** [comment] 2017-11-05 14:41
Duplicate of #7477 will be fixed by #12606

**Closed** 2017-11-05 14:58 UTC
Labels: archived
