### ISSUE TITLE
Constant resource reshuffling in scene file

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#32710] opened 2019-10-10 12:30 UTC
**Godot version:**
3.1.alpha1.mono

**OS/device including version:**
Manjaro Linux x64

**Issue description:**
From time to time the editor will reorder the resources in my main scene between two different states

Initial reorder
![image](https://user-images.githubusercontent.com/30666851/66568637-dde4d180-eb37-11e9-91f1-302e432dda35.png)

The editor reordering it back
![image](https://user-images.githubusercontent.com/30666851/66568668-eb9a5700-eb37-11e9-928e-46dca8e64930.png)

This continues to repeat constantly (every time I run the game ect)

File in question: https://github.com/ForLoveOfCats/SkyOfSteel/blob/master/Game/RuntimeRoot.tscn

**Comment by KoBeWi** [comment] 2019-10-10 12:35
Duplicate of #30538

There's already a PR fixing this, but it's not merged yet.

**Closed by KoBeWi** 2019-10-10 12:35 UTC

**Comment by ForLoveOfCats** [comment] 2019-10-10 12:43
Well that's what I get for trusting Github's related issues search... Sorry for the duplicate issue
