### ISSUE TITLE
Crash after changing editor's theme

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#57198] opened 2022-01-25 14:53 UTC
### Godot version

4.0.alpha1.official.31a7ddbf8

### System information

Garuda Linux

### Issue description

We tried to change the theme of the editor, but after 3 or 4 changes, Godot crashed.

~~~~
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha1.official (31a7ddbf838572e50415159a56720275f9523262)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7f9d3496ada0] (??:0)
[2] /usr/lib/libpthread.so.0(pthread_mutex_lock+0x4) [0x7f9d34c52424] (??:0)
[3] /home/pancake/bin/godot.4.0() [0x28958ec] (??:0)
[4] /home/pancake/bin/godot.4.0() [0x28c2f21] (??:0)
[5] /home/pancake/bin/godot.4.0() [0x28d8216] (??:0)
[6] /home/pancake/bin/godot.4.0() [0x28dbae0] (??:0)
[7] /home/pancake/bin/godot.4.0() [0x290978f] (??:0)
[8] /home/pancake/bin/godot.4.0() [0x28f0972] (??:0)
[9] /home/pancake/bin/godot.4.0() [0xdce064] (??:0)
[10] /home/pancake/bin/godot.4.0() [0x3d25db4] (??:0)
[11] /home/pancake/bin/godot.4.0() [0x3d27485] (??:0)
[12] /home/pancake/bin/godot.4.0() [0xdce657] (??:0)
[13] /home/pancake/bin/godot.4.0() [0xd57710] (??:0)
[14] /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f9d34955b25] (??:0)
[15] /home/pancake/bin/godot.4.0() [0xd7103e] (??:0)
-- END OF BACKTRACE --
~~~~

### Steps to reproduce

1. Open any project.
2. Change the editor's theme a few times.

For us, it doesn't happen everytime.

### Minimal reproduction project

Not related to an actual project. The issue happened with a brand new empty project.

**Comment by Calinou** [comment] 2022-01-25 14:56
Duplicate of https://github.com/godotengine/godot/issues/50760.

**Closed by Calinou** 2022-01-25 14:56 UTC
