### ISSUE TITLE
Path2D - Can't remove or modify points

### ISSUE THREAD

**Issue by giacomocali** [godotengine/godot#98291] opened 2024-10-18 11:03 UTC
### Tested versions

Godot version v4.3.stable.mono.official [77dcf97d8]. Don't think it makes a difference in this particular case, but i'm using the Mobile renderer.

### System information

Linux 6.8.0-44-generic, Linux Mint 22 (64 bit), GNOME 46 (Wayland) - Godot v4.3.stable.mono.official [77dcf97d8] - APU: AMD Ryzen 5 5500U - RAM: 24GB

### Issue description

Running Linux Mint with GNOME (Wayland)
When trying to remove or modify the points of a Path2D, the console prints some errors saying that some array was out of bounds. Also CTRL+Z is not working and i can't delete the Path2D node itself. When closing and re-opening Godot, it lets me delete it.

Also when switching to GNOME on X11 everything works normally.

### Steps to reproduce

Open Godot version v4.3.stable.mono.official [77dcf97d8] on Linux, add a Path2D node, and after a couple of modifications to the points it breaks and doesn't let you modify them, remove them, use CTRL+Z or delete the Path2D node itself. It only lets you drag and move the points around.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-10-18 13:44
This looks like a duplicate of #96081, that was already fixed by #96237. You can test it in godot 4.4 dev 2 or wait for godot 4.3.1

**Comment by giacomocali** [comment] 2024-10-21 19:24
Sorry for replying so late - but yeah it's the same exact bug

These are the errors that appear when repeatedly trying to remove the last point from the inspector:

  ./core/templates/cowdata.h:214 - Index p_index = 4 is out of bounds (size() = 4).
  ./core/templates/cowdata.h:214 - Index p_index = 4 is out of bounds (size() = 3).
  ./core/templates/cowdata.h:214 - Index p_index = 4 is out of bounds (size() = 2).
  ./core/templates/cowdata.h:214 - Index p_index = 4 is out of bounds (size() = 1).
  ./core/templates/cowdata.h:214 - Index p_index = 4 is out of bounds (size() = 0).
  ./core/templates/cowdata.h:314 - Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
  editor/editor_inspector.cpp:1851 - Condition "p_to_pos < -1 || p_to_pos > count" is true.

![Schermata del 2024-10-21 21-24-06](https://github.com/user-attachments/assets/a14047ca-f30c-4ae5-b639-0827a559bd5b)

**Closed** 2024-10-22 09:00 UTC
