### ISSUE TITLE
Running the game, 3 nodes of the same scenes and scripts don't run the _ready built-in function but only 1 node is.

### ISSUE THREAD

**Issue by GittyGrubHub85** [godotengine/godot#78082] opened 2023-06-10 14:20 UTC
### Godot version

4.1 beta

### System information

Windows 10 - Godot 4.1 beta - Compatibility

### Issue description

**Claimed Bug 1**

I decide to use Godot 4.1 on my 4.0 project to see if it works as normal. I saw an error on my data dictionary using .json and felt confused in fixing the issue. 

I'm using 3 nodes of the same scene and script, I decide to add a print function on the _ready() and as I test it on the run only 1 output showed instead of 3 outputs because I'm using 3 nodes of the same scenes and script.

There are times I can get the game to work as normal but most of the run attempts, the game keeps closing.

I don't know if this is a bug or not or maybe a new feature that I should learn but I just felt like I need to report this as a bug because it didn't make any sense to me why aren't my other nodes' _ready function not executing in runtime and only 1 is.

### Steps to reproduce

You create these nodes:
- Panel_Node (has a script)  [link here](https://pastebin.com/GLWt2kyx)
     - Control_Node (as a scene and has a script) [link here](https://pastebin.com/csx2eRJq)
          - Panel
                - Label
                - Panel1 (as a scene and has a script, Panel2 and Panel3 share the same scene and script) [link here](https://pastebin.com/69yWvzeW)
                - Panel2 (as a scene and has a script, Panel1 and Panel3 share the same scene and script) [link here](https://pastebin.com/69yWvzeW)
                - Panel3 (as a scene and has a script, Panel1 and Panel2 share the same scene and script) [link here](https://pastebin.com/69yWvzeW)

I tried recreating this in a new project, it didn't show any issues. It appears to me that my project is the only one that can recreate this issue.

### Minimal reproduction project

commenting certain codes in the function prevents any issues.

**Comment by AThousandShips** [comment] 2023-06-10 14:23
Please upload an MRP as your description doesn't contain any details about the script or anything else:
> A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the .godot folder in the archive (but keep project.godot).

> Required, unless the reproduction steps are trivial and don't require any project files to be followed. In this case, write "N/A" in the field.

> Drag and drop a ZIP archive to upload it. Do not select another field until the project is done uploading.

**Comment by AThousandShips** [comment] 2023-06-10 14:28
Your links are broken, you need to put the text you want to show in \[text](URL) like this

**Comment by AThousandShips** [comment] 2023-06-10 14:32
Well your code has several errors in it, `Directory` isn't a type, nor is `File`

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk, and your code isn't valid, so nothing to investigate here

**Comment by GittyGrubHub85** [comment] 2023-06-10 14:41
My project is a huge one, it will take time for me to update the issue. Pardon me.

**Comment by AThousandShips** [comment] 2023-06-10 14:45
No rush, but you'd probably be better off talking on the community channels and making sure this *is* a bug, as I can't see anything here that indicates a bug, only several errors in your code

**Comment by GittyGrubHub85** [comment] 2023-06-10 15:10
I want to give you a video link too see I ran multiple attempts of my game and the error shows up and then it doesn't when I run the game again.
[Video Link here](https://youtu.be/KmhdIPcM8UY)

**Comment by AThousandShips** [comment] 2023-06-10 15:19
Now, please take this to the other community channels and see what you can get help with there, the video shows some details but without a project we can't help here, as you're barely providing any information

Your scripts are also different from what the ones in the video are, so they don't help

If you figure out what's going on here, or are able to provide an MRP to test, please do so, but otherwise there's nothing here to fix as a bug

**Comment by GittyGrubHub85** [comment] 2023-06-10 15:20
Thank you. Also, what's an MRP?

**Comment by AThousandShips** [comment] 2023-06-10 15:21
I explained it above in my first comment

**Comment by Zireael07** [comment] 2023-06-10 15:31
@GittyGrubHub85 https://github.com/godotengine/godot/issues/78082#issuecomment-1585685980 says what a MRP is

**Comment by KoBeWi** [comment] 2023-06-10 20:00
Duplicate of #77610
You set `name` inside `_ready()`, which is undefined behavior right now.

**Closed by KoBeWi** 2023-06-10 20:00 UTC
Labels: topic:core, needs testing
