### ISSUE TITLE
FileSystem browser not returning actual file structure

### ISSUE THREAD

**Issue by AlexHoratio** [godotengine/godot#8387] opened 2017-04-13 11:15 UTC
**Operating system or device - Godot version:**
Debian Linux 9.0, Godot 3.0

**Issue description:**
The FileSystem browser gave me an incorrect tree structure. The actual structure is:

- res://
    - Scenes
    - Scripts

Where the structure it returned was  
- res://
    - Scenes
        - Scenes
        - Scripts
    - Scripts
        - Scenes
        - Scripts

**Steps to reproduce:**
As far as I can tell, this can be reproduced by adding a new folder inside of a project folder, then expanding the folder in the FileSystem browser.

**Comment by magyar123** [comment] 2017-04-13 12:01
I can confirm this, it's present in 2.1.2 too. I think the problem is [in this function](https://github.com/godotengine/godot/blob/master/editor/editor_file_system.cpp#L490) but not sure, I'll check it later.

**Comment by magyar123** [comment] 2017-04-13 12:03
BTW in my experience the issue is only present if the new folder is created outside the editor.

**Comment by bojidar-bg** [comment] 2017-04-13 12:12
Duplicate of #3662, sorry.

**Closed by bojidar-bg** 2017-04-13 12:12 UTC
