### ISSUE TITLE
All the texts are half cut off

### ISSUE THREAD

**Issue by JOJO-AND-AURORA** [godotengine/godot#81723] opened 2023-09-16 07:08 UTC
### Godot version

Godot_v4.1.1-stable_win64.exe

### System information

Windows 10 - OpenGL API 3.3.0 - Build 21.20.16.5174 - Compatibility - Using Device: Intel - Intel(R) HD Graphics 530

### Issue description

This is my first time to learn godot, with excitement. But after I downloaded and started it, something went wrong! All the texts are half cut off. Screenshot as below:

![image](https://github.com/godotengine/godot/assets/97926461/8ec5004e-36bb-4f31-b8de-be42ba96436f)

I searched this issue on google, and I found someone else also had this problem, the link is https://godotforums.org/d/35467-all-text-half-cut-off-and-projects-wont-launch.

Fortunately , I found where the problem is. On the first time I opened godot, anything was fine until I opened it again. So I thought there was something wrong with config or cache files. So I searched the generated files by godot, and deleted them all. I opened godot again, and the the problem was gone! But I opened godot one more time, the problem showed again. So the problem is in these files. After times of trying deleting different detail files, I located this cache files causing this issue: C:\Users\Administrator\AppData\Roaming\Godot\shader_cache\CanvasShaderGLES3. But I can't do more with this issue. Please help!

### Steps to reproduce

1. download the latest godot Godot_v4.1.1-stable_win64.exe from homepage.
2. open godot, and close it and open it again.

### Minimal reproduction project

N/A

**Comment by saierXP** [comment] 2023-09-16 11:28
* Duplicate of https://github.com/godotengine/godot/issues/79955

**Comment by AThousandShips** [comment] 2023-09-16 11:33
Duplicate of #79955

**Closed by AThousandShips** 2023-09-16 11:33 UTC
Labels: bug, topic:rendering
