### ISSUE TITLE
Morphs and skeletons do not work together

### ISSUE THREAD

**Issue by ryu1981** [godotengine/godot#7668] opened 2017-01-29 05:51 UTC
**Operating system or device - Godot version:**
Godot_v2.1.2-stable_win64.exe - Windows7 64bit

**Issue description:**
Morphs and animations sometimes stop working.

Blender 
<img src="http://drive.google.com/uc?export=view&id=0B_beyBEMhqIHZGNpMGF3YzFXM2s">

Import to Godot engine (Morph does not work)
<img src="http://drive.google.com/uc?export=view&id=0B_beyBEMhqIHYUxKdmFUMjNOSjA">

**Steps to reproduce:**
Import 3D models that have both morphs and skeletons.
When there is morph and skeleton, It occurs.
When there is only morph, this problem does **not** occur.
When there is only a skeleton, this problem does **not** occur.
When the number of morphs is small, this problem does **not** occur.
Sorry for my bad english. Thank you.

**Link to minimal example project:**
<a href="https://drive.google.com/file/d/0B_beyBEMhqIHazdRRkdWT3I2WHc/view?usp=sharing">https://drive.google.com/file/d/0B_beyBEMhqIHazdRRkdWT3I2WHc/view?usp=sharing</a>
(Including 3D models)
(In the Blender, skeleton = bone, morph = shape key)

**Comment by bojidar-bg** [comment] 2017-01-29 18:07
Part of this is in #4120 (though I prefer it in a separate issue, plus that other one is a bit vague)

**Comment by JosephCatrambone** [comment] 2017-12-19 02:17
This appears to be fixed on the latest build of Godot.

![2017-12-18_18-16-53](https://user-images.githubusercontent.com/2160055/34137403-a7682f1a-e41f-11e7-8584-8ecd536b560a.gif)

**Comment by Noshyaar** [comment] 2018-04-10 16:14
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by JosephCatrambone** [comment] 2018-04-10 19:13
I'll make a note to try on the current stable and master branches today or tomorrow.  I think I have an old test project.

**Comment by JosephCatrambone** [comment] 2018-11-17 22:31
> > Thus far it looks like the issue is resolved on the current master. I don't see the wonky distortion in the exported mesh. I'll try with a few more intricate models, but at this point it looks like exports with the better Collada exporter are okay.
> 
> Except that is the whole point here. Notice the OP showed a distortion animation in the original (in Blender) but upon import into Godot the animated distortion (note the OP dragging the time slider there) is gone. Ergo: the absence of the distortion animation (when imported) indicates the problem _remains_ in this particular issue, **not** resolution of it.

I should have phrased my comment better.  What I meant by "funky distortion" was this: previously, when a morph target was activated, vertices would move clockwise or counterclockwise between the two morphs, leaving big holes in the model.  I don't see _that_ funky distortion in the current version, instead, shape keys/morph targets behave as one would expect and I think the issue is resolved.

**Comment by KoBeWi** [comment] 2020-06-11 21:20
Works in 3.2

**Closed by KoBeWi** 2020-06-11 21:20 UTC
Labels: bug, topic:editor, topic:rendering
