### ISSUE TITLE
DisplayServer::_create_window freeze IDE on nVidia driver 450

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#42246] opened 2020-09-22 11:35 UTC
Godot v4.0.dev ac69f092f

Ubuntu 20.04, nVidia driver 450 (latest) on a GTX 1650

When I try to open any type of window, like create new scene, new project, new node, etc, the entire window freeze, and freeze for a while my host system!
The problema has temporary solved fallback to driver 440.

[vulkan.txt](https://github.com/godotengine/godot/files/5261082/vulkan.txt)

**Comment by Zireael07** [comment] 2020-09-22 11:58
Duplicate of https://github.com/godotengine/godot/issues/41574

**Closed** 2020-09-22 18:18 UTC
