### ISSUE TITLE
Scroll bar doesn't move with the mouse in animation track editor

### ISSUE THREAD

**Issue by holzmb** [godotengine/godot#57058] opened 2022-01-22 11:45 UTC
### Godot version

3.4.2

### System information

Linux

### Issue description

vid

https://user-images.githubusercontent.com/49844382/150637129-7cd7b1ba-fcc2-4207-83b2-7f3eba9abfee.mp4

you're unable to select more keyframes besides what's visible, cause scroll bar does not move with the mouse.

### Steps to reproduce

make few animations tracks and try to select keyframes with the mouse

### Minimal reproduction project

watch attached video

**Comment by Calinou** [comment] 2022-01-22 15:52
Duplicate of https://github.com/godotengine/godot/issues/34362.

**Closed by Calinou** 2022-01-22 15:52 UTC
Labels: bug, topic:editor
