### ISSUE TITLE
Tweens still leak memory.

### ISSUE THREAD

**Issue by uzkbwza** [godotengine/godot#62356] opened 2022-06-23 18:22 UTC
### Godot version

4.0.alpha10

### System information

Windows 10

### Issue description

Using Tweens in Godot 4.0 causes memory leaks. 

https://user-images.githubusercontent.com/43023911/175367781-2dd5e505-7a8a-4eb2-92ed-29283512de6a.mp4

This cannot be fixed by using free() manually, because they are of type RefCounted. Once created, they tend to stick around in memory, even when no reference to them exists.

### Steps to reproduce

Use create_tween().

### Minimal reproduction project

[memleak.zip](https://github.com/godotengine/godot/files/8969917/memleak.zip)

**Comment by Calinou** [comment] 2022-06-23 19:41
cc @KoBeWi

**Comment by KoBeWi** [comment] 2022-06-23 22:21
Duplicate of #52699
This is a GDScript bug.

**Closed by KoBeWi** 2022-06-23 22:21 UTC
Labels: bug, topic:core
