### ISSUE TITLE
Godot doesn´t have ALT+NumKey to write special ASCII characters

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#15098] opened 2017-12-27 13:40 UTC
**Godot version:**

Godot 2.1.4 / Godot 3 beta 2

**OS/device including version:**

Win 7 32 y 64 bit

**Issue description:**

If you try to use an ASCII special character with ALT+number, you can't, nor in script editor, inspector, any control, etc.... so, i can't find correct way to....  |£H┘©╣ùE■├▓Âµ»ƒ¥

**Steps to reproduce:**
Try to use any ascii special character inside godot without copy them from external editor.

**Minimal reproduction project:**

Not needed

- [x ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by vnen** [comment] 2017-12-27 14:03
Duplicate of #2689.

**Closed by vnen** 2017-12-27 14:03 UTC

**Comment by reduz** [comment] 2017-12-27 14:09
I think this is specific of Windows text input controls.. we just get
unicode directly from the OS and those characters dont show up.. meaning it
should probably be implemented manually.
