### ISSUE TITLE
RenderingDevice error spam when using ViewportTexture in Viewport child

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#76249] opened 2023-04-19 08:25 UTC
### Godot version

1b4b893

### System information

Win 10

### Issue description

For e.g. terrain deform or water simulations it is often required to feed back a ViewportTexture to a child of the Viewport to be rendered on the next frame. This works without issues in Godot 3 and while the same simulation works in Godot 4 as well it spams a flood of RenderingDevice errors. 

`RenderingDeviceVilkan::draw_list_bind_uniform_set: Attempted to use the same texture in framebuffer attachment and a uniform (set: 1, binding: 1), this is not allowed`.

Properly related to issues https://github.com/godotengine/godot/issues/60475 and https://github.com/godotengine/godot/issues/44473 and https://github.com/godotengine/godot/issues/70193

### Steps to reproduce

Create a SubViewport.
Create a ColorRect child.

![setup](https://user-images.githubusercontent.com/52464204/233014853-abc26430-b631-4f9f-8294-1c5fdf29e73a.png)

Add a ShaderMaterial and a Shader with an uniform sampler2D on the ColorRect.

```
shader_type canvas_item;
uniform sampler2D test_tex;
void fragment() {}
```
Add the ViewportTexture from the SubViewport to the uniform sampler.

### Minimal reproduction project

See steps.

**Comment by winston-yallow** [comment] 2023-04-19 10:19
I don't think that can work: You are tying to use the result of rendering the subviewport while rendering the subviewport.

That's what the error means, it can't use the buffer that is written to as a source for a uniform at the same time.

I think the error message could make this more clear though.

**Comment by Calinou** [comment] 2023-07-03 10:10
- Duplicate of https://github.com/godotengine/godot/issues/60475 (same cause).

**Closed by Calinou** 2023-07-03 10:10 UTC
Labels: bug, topic:rendering
