### ISSUE TITLE
Error: Could not load game data at path '.'. Is the .pck file missing? (64 bits exported game with a 3.7gb pck)

### ISSUE THREAD

**Issue by sinaSPOGames** [godotengine/godot#87751] opened 2024-01-30 18:21 UTC
### Tested versions

Reproducible in 3.4.5 x64

### System information

Windows 10 22h2 (Godot 3.4.5 x64) Gles3.1

### Issue description

this error...
this may be just enough to tell the issue
![image](https://github.com/godotengine/godot/assets/87777184/c1c071e4-848e-4ff9-aa23-0d97d9f5a453)

### Steps to reproduce

same as mrp

### Minimal reproduction project (MRP)

-make a project (with over 3gb of assets)
export with etc and etc2 enabled
(non embed pck file)

**Comment by sinaSPOGames** [comment] 2024-01-30 18:22
last note: i use x64 os and i know the 32bit float limit on pck file size

**Comment by Drakenroft** [comment] 2024-01-30 20:08
Can you reproduce this in 3.5.3 or 3.6 beta 4? Also, does this happen if you toggle "embed pck"?
I'm not a contributor but i'm sure this would help figure it out, it may even be already fixed in newest 3.x versions.

**Comment by AThousandShips** [comment] 2024-01-30 20:10
Indeed please try with a new (and supported) version like 3.5.3, 3.4 is no longer supported

**Comment by sinaSPOGames** [comment] 2024-01-30 20:11
@AThousandShips unfortunately i cannot do this
because of corse im not going to check entirely over 100 scrips)

**Comment by sinaSPOGames** [comment] 2024-01-30 20:12
this happened after enabling etc2 and etc options in export
lemme uncheck those

**Comment by AThousandShips** [comment] 2024-01-30 20:13
Then there's nothing we can do to help, 3.4 is no longer supported so you will have to update if you want help, no fixes will be added to 3.4

**Comment by sinaSPOGames** [comment] 2024-01-30 20:14
> Can you reproduce this in 3.5.3 or 3.6 beta 4? Also, does this happen if you toggle "embed pck"? I'm not a contributor but i'm sure this would help figure it out, it may even be already fixed in newest 3.x versions.

yes @Drakenroft this issue happens on embed pck as well

**Comment by sinaSPOGames** [comment] 2024-01-30 20:15
> Then there's nothing we can do to help, 3.4 is no longer supported so you will have to update if you want help, no fixes will be added to 3.4, so nothing we can do except guide you will solve this
> 
> Upgrading to 3.5.3 isn't going to break anything most likely, the upgrade isn't complex, you don't have to change any of your scripts

there are some stuff exist that i cant use in newer version (related to nodes and shader)

**Comment by Drakenroft** [comment] 2024-01-30 20:16
> @AThousandShips unfortunately i cannot do this because of corse im not going to check entirely over 100 scripts to see if anything changed or not

From 3.4 to 3.5 the port may even not break it strongly depends on what API did you use, i not recall all the changes but i don't think there were a lot of breaking ones, you can always revert changes from git, or if you for some reason aren't using some sort of version control, just duplicate the folder and try there

**Comment by AThousandShips** [comment] 2024-01-30 20:17
> there are some stuff exist that i cant use in newer version (related to nodes and shader)

I'm not sure what you want us to do then? No updates will happen to 3.4, so unless this is some error on your end nothing can fix this, I'm sorry

**Comment by sinaSPOGames** [comment] 2024-01-30 20:19
i will try this then since i have no choice xd
although before this i will try to disable those 2 options in export settings just in case before trying it
because before doing those it was working fine

(enabling etc2 and etc options because they were enabled in project settings but not in export settings)
before this however it was launching by also loading resources from project but not the export (likely those resources were not included)

**Comment by AThousandShips** [comment] 2024-01-30 20:20
Are you maintaining an old game project? And running into new issues because your project grew larger?

**Comment by sinaSPOGames** [comment] 2024-01-30 20:20
not really that but kind of

**Comment by sinaSPOGames** [comment] 2024-01-30 20:21
the project was arround 70mb when first alpha was released but after adding the whole openworld and high quality assets it became alittle large on file terms

**Comment by sinaSPOGames** [comment] 2024-01-30 20:21
it was supported for 32 bits at first then deprecated due 32 bits float limt (2.1gb)
and now its 3.5gb

**Comment by Drakenroft** [comment] 2024-01-30 20:23
@AThousandShips i suggest to close the issue for now, and @sinaSPOGames when you have tried updating the engine versione make a new one if the issue persist

**Comment by AThousandShips** [comment] 2024-01-30 20:24
Because you really shouldn't be developing a new project on such an old version, you're bound to run into more problems, you really should take the work and update the version 🙂 

Let's keep it open until you confirm if it's still happening on 3.5.3

**Comment by sinaSPOGames** [comment] 2024-01-30 20:31
also forgot to mention
when the engine is packing the file debug keeps spamming this (only starts when last pice [the project.binary] being stored])

ERROR: Condition "fwrite(p_src, 1, p_length, f) != (size_t)p_length" is true.
   at: store_buffer (drivers/windows/file_access_windows.cpp:301)

**Comment by AThousandShips** [comment] 2024-01-30 20:52
That sounds like it fails to write, for some reason, it could be an operating side issue, but unsure, the error happens when it tries to write `p_length` bytes, and the result of the operation isn't `p_length` times written, which is wrong

The question is if this is a Godot issue, or a limit on the OS etc.

**Comment by sinaSPOGames** [comment] 2024-01-30 21:31
welp
now the issue is something else thats doesnt make any sense

the latest export works but loads assets from the original project folder not the embed pck file...





Godot Engine v3.5.3.stable.official.6c814135b - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce MX110/PCIe/SSE2
Async. shader compilation: OFF
 
ERROR: No loader found for resource: C:/CRITICAL PROJECTS/RCP/assets/basic models prev/Başlıksız10_20230116040116.png.
   at: _load (core/io/resource_loader.cpp:278) - Method failed. Returning: RES()
ERROR: Can't load dependency: C:/CRITICAL PROJECTS/RCP/assets/basic models prev/Başlıksız10_20230116040116.png.
   at: poll (core/io/resource_format_binary.cpp:611) - Method failed. Returning: error
ERROR: Failed to load resource 'res://.import/Japan City_yoki_pass_trees.obj-fa505149e3d2cf92933aa300b67c628f.mesh'.
   at: load (core/io/resource_loader.cpp:206) - Condition "err != OK" is true. Returned: RES()
ERROR: Failed loading resource: res://.import/Japan City_yoki_pass_trees.obj-fa505149e3d2cf92933aa300b67c628f.mesh. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270) - Condition "found" is true. Returned: RES()
ERROR: Failed loading resource: res://1.0/Models/City/Japan City/JAPAN CITY 0.5/Japan City_yoki_pass_trees.obj. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270) - Condition "found" is true. Returned: RES()
ERROR: Can't load dependency: res://1.0/Models/City/Japan City/JAPAN CITY 0.5/Japan City_yoki_pass_trees.obj.
   at: poll (core/io/resource_format_binary.cpp:611) - Method failed. Returning: error
ERROR: Failed to load resource 'res://1.0/Models/City/Japan City/JAPAN CITY 0.5/MAP SLICES/Japan City - part 0 forest LOD.scn'.
   at: load (core/io/resource_loader.cpp:206) - Condition "err != OK" is true. Returned: RES()
ERROR: Failed loading resource: res://1.0/Models/City/Japan City/JAPAN CITY 0.5/MAP SLICES/Japan City - part 0 forest LOD.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270) - Condition "found" is true. Returned: RES()
ERROR: res://1.0/MAIN_IRC.tscn:10 - Parse Error: [ext_resource] referenced nonexistent resource at: res://1.0/Models/City/Japan City/JAPAN CITY 0.5/MAP SLICES/Japan City - part 0 forest LOD.scn
   at: poll (scene/resources/resource_format_text.cpp:412) - res://1.0/MAIN_IRC.tscn:10 - Parse Error: [ext_resource] referenced nonexistent resource at: res://1.0/Models/City/Japan City/JAPAN CITY 0.5/MAP SLICES/Japan City - part 0 forest LOD.scn
ERROR: Failed to load resource 'res://1.0/MAIN_IRC.tscn'.
   at: load (core/io/resource_loader.cpp:206) - Condition "err != OK" is true. Returned: RES()
ERROR: Failed loading resource: res://1.0/MAIN_IRC.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270) - Condition "found" is true. Returned: RES()
ERROR: Failed loading scene: res://1.0/MAIN_IRC.tscn
   at: start (main/main.cpp:2107) - Condition "!scene" is true. Returned: false
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object.cpp:2070) - ObjectDB instances leaked at exit (run with --verbose for details).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417) - Resources still in use at exit (run with --verbose for details).
ERROR: There are still MemoryPool allocs in use at exit!
   at: cleanup (core/pool_vector.cpp:63) - Condition "allocs_used > 0" is true.
4

**Comment by sinaSPOGames** [comment] 2024-04-01 23:42
ahh... o forgot this thread lol
the issue was an asset having a letter in it that wasn't accessible in the exported game...

always remember to double check your logs

I discovered this like 8 hours later this thread's opening btw

**Closed** 2024-04-01 23:43 UTC
Labels: bug, needs testing, topic:export
