### ISSUE TITLE
`@icon` does not work unless `class_name` is specified

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#65203] opened 2022-09-01 15:44 UTC
### Godot version

4.0.dev (728785d5328172acd4cc4b182914aea5d234fea4)

### System information

Windows 10

### Issue description

If you specify only `@icon`, it does not work. You must add `class_name` to your script for the icon to show up.

This is unlike the documentation which states:
> Add a custom icon to the current script. The icon is displayed in the Scene dock for every node that the script is attached to. For named classes the icon is also displayed in various editor dialogs.

### Steps to reproduce

- Create an icon
- Create a node with a script
- Add `@icon("res://icon.svg")` to the script
- Reload project (since this does not seem to live reload), icon does not show up
- Add `class_name Something` to the script
- Reload project again, icon now shows up

### Minimal reproduction project

[icon_annotation.zip](https://github.com/godotengine/godot/files/9471348/icon_annotation.zip)

Icon will only show up if you add `class_name Something` to the script and then reload project.

**Comment by RedMser** [comment] 2022-09-01 15:46
Seems like there are some places that explicitly check for `ScriptServer::is_global_class` and early-returning with no icon (such as `EditorData::script_class_get_icon_path`).
Might be since the syntax used to be `class_name name, "path"`?

Either the documentation has to be updated to clarify this limitation, or the code has to be updated to work as expected.

**Comment by Gatada** [comment] 2022-09-28 12:58
I actually thought this was by design? Custom classes can have custom icons.

Would be nice to be able to have icons on anything though.

**Comment by RedMser** [comment] 2022-09-28 13:02
> I actually thought this was by design?

Not sure, the syntax used to be `class_name <name>, <icon>` in the past. So by splitting it to a separate annotation, I'd expect it to be usable standalone.

Didn't really investigate how much effort it'd be to make `@icon` work without `class_name`, but yeah would be the nicest solution here... :)

**Comment by souplamp** [comment] 2022-11-25 03:32
Mentioned in #69141, but the docs should make this clear; it sounds like giving a script an icon and giving a class an icon are two separate things.

**Comment by bend-n** [comment] 2022-11-25 05:27
I vote this works without `class_name`, as custom icons are good for addons, and having duplicate classes of the same name is not something godot appreciates, meaning addons cant have dependencys on other addons.

**Comment by akien-mga** [comment] 2022-11-25 08:34
For now the docs should be fixed, as they're wrong. The way this feature implemented is tied to `class_name` aka "global script classes"

In your `project.godot` you can see that the two are linked:
```
_global_script_classes=[{
"base": "Node",
"class": &"MyClass",
"language": &"GDScript",
"path": "res://myclass.gd"
}, {
"base": "Node2D",
"class": &"MyNewClass",
"language": &"GDScript",
"path": "res://node_2d.gd"
}]
_global_script_class_icons={
"MyClass": "",
"MyNewClass": ""
}
```

To support icons for non global scripts, the scripts would need to be parsed on a case by case basis which might add some technical complexity. Might be possible and maybe not even hard, but it's still in the "new feature" realm, the implementation would need to be rethought.

**Comment by souplamp** [comment] 2022-11-25 13:55
> For now the docs should be fixed, as they're wrong.

I wonder if it would also be on point to have the parser raise an error for a `@icon` annotation with no `class_name` present?

**Comment by YuriSizov** [comment] 2022-12-01 14:28
I think that my intended reading of that documentation snippet was that named classes appear in dialogs -> so the icon is also visible there, not to imply that it should work with unnamed classes. I don't think I've tested that 🙃

**Closed** 2022-12-02 00:04 UTC
Labels: discussion, topic:editor

**Comment by bend-n** [comment] 2022-12-02 00:05
I can make a proposal?
