### ISSUE TITLE
Using same uniform in both `vertex()` and `fragment()` fails rendering on Android (3.1.RC1)

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#26852] opened 2019-03-09 20:16 UTC
Godot 3.1 RC1
Android GLES2

**Minimal scene:**
![Scene](https://user-images.githubusercontent.com/13801432/54076829-a95e1e00-42a7-11e9-9161-2bbb63ba110d.PNG)

**Result on all other platforms:**
![Capture](https://user-images.githubusercontent.com/13801432/54076838-bc70ee00-42a7-11e9-9777-cf7fe5e6be22.PNG)

**Result on Android:** the square does not render.

**Here's the shader used on the mesh:**
```
shader_type spatial;
render_mode unshaded;

uniform sampler2D uSpriteTexture;
uniform vec2 uFailure = vec2(1.0, 1.0);

void vertex()
{
	VERTEX.xy += uFailure;
}

void fragment() 
{
	ALBEDO = vec3(0.8, 0.2, 0.1);
	ALBEDO.rg = uFailure;
}
```

The rendering fails if, and only if, the uniform is used in both the vertex and fragment shaders.

**Reproduction:**
Download [this project](https://github.com/godotengine/godot/files/2948809/temp.zip) and run on Android GLES2 (not tested on GLES3) to reproduce.

**Comment by clayjohn** [comment] 2019-05-23 18:49
Duplicate of https://github.com/godotengine/godot/issues/28199 I know this one was made first, but https://github.com/godotengine/godot/issues/28199 has some discussion and more information

**Closed by clayjohn** 2019-05-23 18:49 UTC
Labels: bug, platform:android, topic:rendering

**Comment by lawnjelly** [comment] 2019-05-24 09:29
Fantastic, it does appear to fix it on mine too. I manually applied the changes to the 4 files, and recompiled the export templates as I have limited time for the next couple of weeks, so I can't rigorously test yet.

Many thanks! :+1: :)
