### ISSUE TITLE
Flickering top bar when trying to select item from dropdown menu (DisplayServer regression)

### ISSUE THREAD

**Issue by BliznyukNM** [godotengine/godot#54550] opened 2021-11-03 14:07 UTC
### Godot version

4.0.dev (87ddc5bbbf)

### System information

MacOS (12.0.1 Monterey), MacBook Pro M1 13'

### Issue description

Flickering top bar when trying to select any item.

https://user-images.githubusercontent.com/46704931/140074964-7f344945-d461-4d32-b3b7-9dd05f635fa5.mov

### Steps to reproduce

Hover your cursor over any menu item (starting from second item). It will show one frame of proper menu item, one frame of first item.

**Comment by Calinou** [comment] 2021-11-03 14:20
@BliznyukNM Can you reproduce this after enabling **Single Window Mode** in the Editor Settings?

**Comment by kleonc** [comment] 2021-11-03 14:29
Duplicate of #53912?

**Comment by Calinou** [comment] 2021-11-03 14:33
Duplicate of #53912.

**Closed by Calinou** 2021-11-03 14:33 UTC
Labels: bug, platform:macos, topic:editor, topic:porting, regression
