### ISSUE TITLE
Some characters from the Utf-8 set fail to be rendered in godot. (In the editor and at runtime)

### ISSUE THREAD

**Issue by hidemat** [godotengine/godot#54617] opened 2021-11-05 02:22 UTC
### Godot version

Godot Engine v3.4.rc2.official.23955fc28  &  Godot 3.3.4-mono-stable

### System information

Windows 10, OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2

### Issue description

I can't get the following characters to show up even though the are in the Utf-8 set:

`𠂊 𠆢`

They are from Japanese. The vast majority of characters from Japanese show up, but some don't, like these 2 ( There are others but these are the ones I could identify). 

This happens both at runtime and in the editor.

I'm using the Noto Sans Japanese font form Google Fonts, and have verified that it supports these characters. This is where you can verify if you wish:
https://fonts.google.com/noto/specimen/Noto+Sans+JP?query=noto

### Steps to reproduce

1. Copy and paste these characters (`𠂊 𠆢`) to any control node that accepts text like a label. 
2. Assign the Noto Sans Japanese font to the node. 
3. They don't show up.

### Minimal reproduction project

[JapaneseRadicals.zip](https://github.com/godotengine/godot/files/7480050/JapaneseRadicals.zip)

**Comment by bruvzg** [comment] 2021-11-05 09:27
This is fixed in `master`. 3.x uses `wchar_t` to store strings, which is 16-bit on Windows and can't fit characters  outside BMP (`U+0000` - `U+FFFF`). On macOS, Linux, iOS and Android it is 32-bit and should work without issues.

𠂊 `U+2008A`
𠆢 `U+201A2`

Changing it to `char32_t` like we did in `master` will break compatibility with all existing modules and GDNative add-ons.

Adding some surrogate pair support should be possible (to the UTF-8 encode/decode and font draw_char), it will behave poorly with input controls, but OK for display. If it is necessary to display the real text, it might be worth it. Previously we only encounter this issue with emojis.

**Comment by Calinou** [comment] 2021-11-06 17:25
Duplicate of https://github.com/godotengine/godot/issues/52698 (same cause).

**Closed by Calinou** 2021-11-06 17:25 UTC
Labels: bug, topic:gui
