### ISSUE TITLE
Project Manager reports "Update Available" when on latest 4.3 beta version

### ISSUE THREAD

**Issue by roa-nyx** [godotengine/godot#93446] opened 2024-06-21 23:52 UTC
### Tested versions

`v4.3.beta2.official [b75f0485b]`

### System information

Windows 11

### Issue description

The `Project Manager` has a yellow text notices at the bottom right beside the version information.

The version information: `v4.3.beta2.official [b75f0485b]`
The yellow notice: `Update available: v4.3-beta2.`

Kinda looks like the update information got clobbered and maybe it's improperly reporting that I'm not on the latest version. However the download it links to just redownloads this same version.

### Steps to reproduce

Open `Project Manager` in `v4.3.beta2.official`. Look at bottom right. (I suppose you need to make sure you have the setting to check for updates enabled, which I did some time ago, don't remember where that is).

### Minimal reproduction project (MRP)

Not a godot engine related issue, but rather just the `Project Manager`. Let me know if I need to put this elsewhere or if more details are needed.

**Comment by roa-nyx** [comment] 2024-06-21 23:52
![image](https://github.com/godotengine/godot/assets/8572438/b25a484a-925c-4774-8951-bf3f9fcac032)

Screenshot in case that's helpful

**Comment by JekSun97** [comment] 2024-06-21 23:55
I confirm

**Comment by Calinou** [comment] 2024-06-21 23:56
cc @KoBeWi

**Comment by KoBeWi** [comment] 2024-06-22 01:16
Duplicate of #93390
Guess it's time to pin that issue.

**Closed by KoBeWi** 2024-06-22 01:16 UTC
Labels: bug, topic:editor, confirmed
