### ISSUE TITLE
Enum not completing in a Match statement

### ISSUE THREAD

**Issue by supernovafiles** [godotengine/godot#88820] opened 2024-02-25 16:25 UTC
### Tested versions

- Reproducible in 4.2.1

### System information

Windows 10 - Godot 4.2.1

### Issue description

An enum cannot be autocompleted in a match statement. In any other part of the code, the enum is autocomplete. It only autocompletes until the enum name.

### Steps to reproduce

Create an enum:

```gdscript
enum PieceType {
    PAWN,
    ROOK
}
```

Create a match statement and try to use the enum:

```gdscript
match piece_type:
    PieceType.PAWN:
        some code
```

After typing "PieceType", type the dot "." and the enum names will not be available for autocompletion.

### Minimal reproduction project (MRP)

This is a tiny bug and can be reproduced easily, I don't think an MRP is necessary.

**Comment by HolonProduction** [comment] 2024-02-25 16:39
Duplicate of #72328

**Comment by Chaosus** [comment] 2024-02-25 16:45
Duplicate of https://github.com/godotengine/godot/issues/72328

**Closed by Chaosus** 2024-02-25 16:45 UTC
