### ISSUE TITLE
Start projects with an empty "World" node

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11217] opened 2017-09-12 23:19 UTC
I don't know if it's a bug, but once I've created the first node, I can't make any more parentless nodes (in 3.0 anyway). I can't deselect all nodes in the scene hierarchy, there's no "no parent" option in the reparent GUI, and I can't drag a node outside the initial parent. 

If this is intentional, then every project must have a "world" node that holds _everything_. It would save some time to have it there already. 

If you've used Godot for a long time, then it probably would save maximum 10 seconds. But it's just "another one of those things" you have to do when you start a project. And to some people (me), workflow speed is really important, so just little things like this make a whole world of difference.

**Comment by toger5** [comment] 2017-09-13 02:30
Yea there is a ux issue with changing the root node of a scene. there is another issue about that.
but the approach of adding a world node isn't that bad to be honest

**Comment by vnen** [comment] 2017-09-13 04:02
Well, in a standalone scene I can see the benefit, but with inheritance and instancing, there'll be a lot of extra "world" nodes that you won't really need.

I think it would be better if there were a way to set up a default root node for new scenes or something. A way to change the type of the root node would be a prerequisite though.

**Comment by bojidar-bg** [comment] 2017-09-13 05:35
Does this count as a way to change the type of the root node?
![image](https://user-images.githubusercontent.com/5276727/30361233-7dfb2c98-985e-11e7-8b43-5aa618a9d97a.png)

**Comment by Andev08** [comment] 2017-09-13 13:14
> in a standalone scene I can see the benefit, but with inheritance and instancing, there'll be a lot of extra "world" nodes that you won't really need.

The ideal solution would probably be to have the scene itself as the root node, which would prevent root node spam, and also free up a slot in the resource tree.

If you had multiple scenes, then it would make sense to have them grouped together, so why not have them under their "scene" node type?

**Comment by toger5** [comment] 2017-09-13 13:50
@bojidar-bg changing works, but what if your root node is a mesh instance. and you want an additional spatial node as the root and the mesh as it's only child... than it gets harder... you need to change it, add the mesh instance and than add all the other nodes to that mesh instance

**Comment by toger5** [comment] 2017-09-13 13:51
maybe right click could give the option to add_child node AND add parent node

**Comment by Andev08** [comment] 2017-09-13 13:55
@toger5 I think bojidar-bg was replying to
> A way to change the type of the root node would be a prerequisite though.

But yeah
> what if your root node is a mesh instance. and you want an additional spatial node as the root and the mesh as it's only child

is precisely the reason I created this issue, because it's things like this that slow everything down! I'm glad I'm not the only one

**Comment by bojidar-bg** [comment] 2017-09-13 15:39
Isn't this a duplicate of #9363 then?

**Comment by toger5** [comment] 2017-09-13 15:45
yea kind of...

**Comment by mhilbrunner** [comment] 2018-04-10 18:58
Closing as duplicate of https://github.com/godotengine/godot/issues/9363.

Also it was explicitely decided against starting a new scene with a node (see discussion in https://github.com/godotengine/godot/issues/12325), but if you drag a node into an empty scene view it now asks you if you want to add it as root, which at least makes that part more clear.

**Closed by mhilbrunner** 2018-04-10 18:58 UTC
Labels: feature proposal, topic:editor
