### ISSUE TITLE
When using Merge From Scene, nodes added under editable children are not accessible

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#43261] opened 2020-11-01 11:42 UTC
**Godot version:**
v3.2.3 stable

**Issue description:**
When using Merge From Scene, nodes added under editable children are not accessible

**Steps to reproduce:**
Create scene A with a couple of Nodes (A1, A2, A3). Create scene B that has scene A instanced in it. Use the Editable Children option on instanced scene A, add nodes B1, B2, B3 parented to any of the now visible nodes of the instanced scene A (nodes A1, A2, A3). Create scene C. Use the Merge From Scene option. Choose scene B. Nodes B1, B2, B3 are not accessible to be merged.

What was expected: For nodes B1, B2, B3 to be accessible in the Merge From Scene dialog.

**Comment by KoBeWi** [comment] 2020-11-01 11:47
Duplicate of #27023

**Closed by KoBeWi** 2020-11-01 11:47 UTC
