### ISSUE TITLE
Can no longer add or remove scripts to TileSet via v4.0 Godot Editor - However 3to4 leaves them still attached

### ISSUE THREAD

**Issue by blipk** [godotengine/godot#64480] opened 2022-08-16 03:27 UTC
### Godot version

4.0alpha14

### System information

AMD Arch64

### Issue description

The v4.0 editor no longer has an option to attach or remove scripts from a `TileSet` however it is still supported via the .tres format and importing a project from v3.4 with a script attached to a `TileSet` will leave it attached - without any visibility of this in the editor inspector. (Although using 'View owners...' in FileSystem on the .gd script will show it attached to the TileSet .tres)

![Screenshot from 2022-08-16 13-17-16](https://user-images.githubusercontent.com/45532845/184790889-218f94da-dcec-4680-a7f5-cd8ff9942ddf.png)

![Screenshot from 2022-08-16 13-18-39](https://user-images.githubusercontent.com/45532845/184790894-5b495583-11e9-4f65-8d0f-1605b80f7662.png)

As far as I understand this is because TileSet is now a `Resource`, not a `Node`, so no longer inherits `_ready()`, `_process()` etc.
Although an alternative is to use `TileMap.tile_set.set_script("res://MyTileSetScript.gd")`, I still think it will be useful to have script support in the editor to more easily support implemented functionality that is seperate between TileMap and TileSet, to avoid bloating the script attached to the TileMap.

EDIT: I think I was wrong about the TileSet type and usage of Node functions in 3.4, however you could still attach a script as pictured below, I believe to support _is_tile_bound() etc although it's still useful to have a script on a TileSet for other reasons
![Screenshot from 2022-08-16 13-47-47](https://user-images.githubusercontent.com/45532845/184793755-2efa3e86-821e-4def-8923-a96f84510a81.png)

### Steps to reproduce

- Create TileMap with a TileSet in Godot 3.4
- Attach script to TileSet
- Save TileSet resource to .tres
- Close project and open in Godot 4.0alpha14

**Comment by kleonc** [comment] 2022-08-16 07:51
>Can no longer add or remove scripts to TileSet via v4.0 Godot Editor

You can, but `script` properties are not shown in subinspectors (for whatever reason). But it's the same as in `3.x`. The difference is in `4.0` the `TileSet` resource is allowed to be opened in subinspector (rather a good thing as it makes the `TileMap` keep being opened in the inspector). But if you'd RMB click and choose `Edit` (or if you'd open a `TileSet` resource from a filesystem dock) it would open in its own inspector and `script` property will show up.

![pUNhlcKUca](https://user-images.githubusercontent.com/9283098/184825418-802c00f8-343d-4fcf-aa47-0e28011c1187.png)![godot windows tools 64_Wx5uUCWwRl](https://user-images.githubusercontent.com/9283098/184825043-b306b21b-9b7a-414a-b443-ed9b7631c46d.png)![Osi5mQccZn](https://user-images.githubusercontent.com/9283098/184825048-8f017b71-4586-414f-9d46-8f4d97d9ad55.png)![godot windows tools 64_TMSXdMTUmt](https://user-images.githubusercontent.com/9283098/184825474-9e730e50-9d56-455c-a5ab-50fd9f456954.png)

**Comment by blipk** [comment] 2022-08-16 07:56
Ah, thanks for that @kleonc 
You're right. In 3.4 the TileSet inspector would open when clicking on it making it a lot more obvious, along with the sub-editor in the bottom dock.

Thanks for pointing out how to open the TileSet in the 4.0 inspector.

I'm not sure if this issue is needed then as it is available to change, albeit a little obscured, perhaps it would be useful to show scripts in the sub-inspector if attached?

Feel free to close this issue.

**Comment by kleonc** [comment] 2022-08-16 08:53
> In 3.4 the TileSet inspector would open when clicking on it making it a lot more obvious

To make it clear, it's because of this editor setting:

![Godot_v3 5-stable_win64_v1FTXM2o6u](https://user-images.githubusercontent.com/9283098/184829200-83fc8008-b209-40f3-90f5-e5c40d81049d.png)

In 4.0 by default TileSet in no longer in this list.

---

>perhaps it would be useful to show scripts in the sub-inspector if attached?

This also could be confusing. If you'd have a script attached and you'd clear it (when shown in subinspector) then you'd see the property itself is gone. Just like if by removing the value of the property you removed the property itself. Could be kinda mindblowing. :smile: 

I guess there could be an editor setting to always show scripts in subinspector or something like this. Or just always show them. Or some other solution. But I think it's a subject for a proposal where it could be discussed properly.
So yeah, I'll close this issue as it seems to be working as intended/designed. Feel free to open a proposal though.

**Closed** 2022-08-16 08:53 UTC
Labels: discussion, topic:editor

**Comment by blipk** [comment] 2022-08-16 09:53
Yeah your point makes sense.

Thanks @kleonc will leave it for a proposal if anyone finds it that much of a hindrance.
