### ISSUE TITLE
Editor becomes very wide and overflows when a Control node is selected due to top bar being too large

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#58052] opened 2022-02-13 14:53 UTC
### Godot version

4.0.dev (48ed040)

### System information

Windows 10

### Issue description

Selecting `Control` nodes with many top-bar options will cause the inspector to shrink to a size that's hard to work with and is unable to be resized. This started appearing after #55157 was merged.

https://user-images.githubusercontent.com/21325943/153758814-fce73ab5-d1c2-4673-bab2-1e3b0c09b6bf.mp4

### Steps to reproduce

Add a `RichTextLabel` to a scene.

**Comment by KoBeWi** [comment] 2022-02-13 14:58
This will be resolved by #55630

**Closed** 2022-03-20 17:54 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:gui

**Comment by Calinou** [comment] 2022-03-25 15:51
Note that ultimately, this issue has the same cause as https://github.com/godotengine/godot/issues/31133.

**Comment by yedpodtrzitko** [comment] 2022-04-30 06:10
This is apparently resolved, but I'm still having this issue with Alpha 7 on MacOS 11.6.5. 
Any suggestion what can be done about it?

**Comment by KoBeWi** [comment] 2022-04-30 11:24
The issue is not fully resolved, a proper fix is still planned and is tracked in #31133.
