### ISSUE TITLE
CanvasLayer not working when renderer is forward_plus

### ISSUE THREAD

**Issue by MeBadDev** [godotengine/godot#71027] opened 2023-01-07 14:46 UTC
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 10 , Intel(R) HD Graphics 615

### Issue description

In this video, you can see i have a`CanvasLayer`, and a `Label` as its children(i put there to show the issue better).

When I press the play button and move around, you can see the text on `Label` is been seperated to 2 part, one part stay on the map and behave like a child of world, and it won't update when camera move.

the second part behaves normally.

https://user-images.githubusercontent.com/94725241/211173889-ad3277b0-5954-4132-8de0-a49d7f0a3ec5.mp4

When I switch the Renderer in project settings to `gl_compatibility`, everything works, `Label` isn't seperated to two, and it correctly follow `CanvasLayer`.

### Steps to reproduce

1. Open the minimal reproduction file
and change Renderer to forward_plus in project settings 
2. Run the main scene, it should be "res://scenes/main.tscn"
3. You should notice that the first "L" in "Look at this Label" flies away as camera move
4. Switch `Renderer` to `gl_compatibility` in project settings
5. Restart godot
6. Run the scene again
7. Now everything works as except

### Minimal reproduction project

[NewBug.zip](https://github.com/godotengine/godot/files/10366514/NewBug.zip)

**Comment by Sauermann** [comment] 2023-01-07 16:49
I have tested the MRP with `forward_plus` and `gl_compatibility` renderer on Debian Linux X11 with Nvidia graphic card and the problem doesn't happen for me in v4.0.beta.custom_build [163f6f5fe].

**Comment by KoBeWi** [comment] 2023-01-07 16:59
Intel(R) HD Graphics 615 might be a problem here.

**Comment by arkology** [comment] 2023-01-07 20:42
In theory may be related to https://github.com/godotengine/godot/issues/58314

**Comment by Calinou** [comment] 2023-01-07 22:15
@MeBadDev Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by MeBadDev** [comment] 2023-01-07 22:45
Another bug here is the ParallelBackground,  when I run the game, you can see I have set Mirroring to 1152, which is the my game window size, but it is clearly not mirroring.

**Comment by arkology** [comment] 2023-01-09 07:28
Just tested MRP and can confirm that this is the same as https://github.com/godotengine/godot/issues/58314

**Comment by akien-mga** [comment] 2023-01-09 07:42
Duplicate of #58314

**Closed by akien-mga** 2023-01-09 07:42 UTC
Labels: bug, topic:rendering, topic:2d
