### ISSUE TITLE
Vulkan: MultiMeshInstance3D Shader: Unknown identifier in expression for INSTANCE_ID / INSTANCE_CUSTOM 

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot#57584] opened 2022-02-03 11:33 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10 Version 20H2 Build 19042.1415; Vulkan; RTX 3060 6GB; Ryzen 5900HS

### Issue description

I can not access INSTANCE_ID or INSTANCE_CUSTOM.

I do not understand why it does not work, or what I have to do.

I have been looking for examples, including the Fish example,
which I believe is not actually as in-depth as I believe it should be,
but regardless, nothing was helping.

I also get "Storage buffer supplied (binding: 0) is invalid" every time I change one of the parameters in the editor,
like the texture or the hint_range value. I do not know if that is related.

Note that the supplied shader code does not contain INSTANCE_ID or INSTANCE_CUSTOM,
to show that it works. Simply trying to use one of them results in the ... <edit>:
error: Unknown identifier in expression: INSTANCE_ID</edit, forgot to add the error -.->

I do not know if it's me, or Godot.

Thank you.

### Steps to reproduce

See attached project.
[MultiMeshTest.zip](https://github.com/godotengine/godot/files/7994065/MultiMeshTest.zip)

**Comment by clayjohn** [comment] 2022-02-03 16:54
I ran the MRP using alpha 1 and could reproduce the error in part. 

It seems that when a multimesh is used but ``instance_count`` is ``0``, Godot throws the ``Storage buffer supplied (binding: 0) is invalid`` error. This indicates that one of the buffers needed for multimeshes is not being created unless instance count is greater than zero. We should likely be passing in a dummy storage buffer like we do with textures. 

Beyond that, I can't reproduce any of the other issues. After setting ``instance_count`` to 256 I was able to see all of the meshes and even set their color based on ``INSTANCE_ID``.

As a side note, not all documentation has been updated for 4.0 alpha as the rendering APIs have not been finalized. The fish tutorial, for example, was written for 3.x and has not been updated to 4.0. If you wish to follow it, then I suggest that you use 3.x as that is what the tutorial was written for. 4.0 alpha is still highly stable and not well documented.

**Comment by Zireael07** [comment] 2022-02-03 18:04
Typo: I think you meant *un*stable in the final sentence ;)

**Comment by SolsticeProjekt** [comment] 2022-02-03 19:38
> Beyond that, I can't reproduce any of the other issues. After setting `instance_count` to 256 I was able to see all of the meshes and even set their color based on `INSTANCE_ID`.

In utter disbelief that I might have skipped that, and that it could really be so simple,
I've set the instance_count in the editor to 256. 

I've tried it in both v4.0.alpha1.official [31a7ddbf8] and v3.4.2.stable.official [45eaa2daf].

Kind of relieved it still throws the same error.

I don't understand what I am missing. You say you can't reproduce the issue. I assume you've tried the test project.
I assume you've simply, as you've stated, entered an instance_count in the editor and INSTANCE_ID was being recognized.

So I've set the instance_count to 256, added the INSTANCE_ID

```
shader_type spatial;

uniform sampler2D txt : hint_albedo;
uniform float bla : hint_range(0.0,1.0,0.00390625);


void fragment()
{
	ALBEDO = texture(txt,UV).rgb;

	if (INSTANCE_ID == 0)
	{
		ALBEDO = vec3(0.0);
	}
}
```

Unknown identifier in expression: INSTANCE_ID

**Comment by clayjohn** [comment] 2022-02-04 03:37
> I don't understand what I am missing. You say you can't reproduce the issue. I assume you've tried the test project.
I assume you've simply, as you've stated, entered an instance_count in the editor and INSTANCE_ID was being recognized.

> So I've set the instance_count to 256, added the INSTANCE_ID to the shader, and ...

This is where an MRP comes in handy. ``INSTANCE_ID`` is only available in the vertex processor function. When I tested it, I was using it from the vertex processor function and it worked fine. 

While the docs may be out of date for some things, this is not one of them and they can be very helpful when problem solving: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html#vertex-built-ins

**Comment by clayjohn** [comment] 2023-02-24 20:43
The ``storage buffer supplied (binding: 0) is invalid`` error appears to have been fixed. And the other error message was correct and should have been shown as the user was attempting to access a vertex builtin in the fragment function. Accordingly, I will close this as resolved.

**Closed by clayjohn** 2023-02-24 20:43 UTC
Labels: bug, regression, topic:shaders, topic:3d

**Comment by statico** [comment] 2025-01-02 18:17
In case anyone else is searching endlessly for why their shader is reporting an error about `INSTANCE_CUSTOM`, this is the reason ☝ 

You can't use `INSTANCE_CUSTOM` in a fragment shader, only the vertex shader. So add a `varying` to pass the `INSTANCE_CUSTOM` value from the vertex shader to the fragment shader.
