### ISSUE TITLE
[v4.0beta17] Debugger slows down between steps when using specific Shader

### ISSUE THREAD

**Issue by Silvanuz** [godotengine/godot#72742] opened 2023-02-04 22:53 UTC
### Godot version

v4.0 beta17

### System information

Win10 64 bit, GTX 1070, Intel(R) Core(TM) i7-6700K CPU

### Issue description

This is NOT happening in Godot 3.x .

I have a shader which adds a wind effect to my sprites.
But when I use it in the current beta, the debugger becomes really slow.
Every step between a breakpoint takes so much time.

You can watch the video and the example project for more details.

https://user-images.githubusercontent.com/36472149/216792801-5bc1f97f-fea3-42a7-88ba-bba5085d14ce.mp4

### Steps to reproduce

Attach this shader to a sprite and create a seperate standard CharacterBody2D object..Debug the Character script. (See the video)

```
// original wind shader from https://github.com/Maujoe/godot-simple-wind-shader-2d/tree/master/assets/maujoe.simple_wind_shader_2d
// original script modified by HungryProton so that the assets are moving differently
//
// speed - The speed of the wind movement.
// minStrength - The minimal strength of the wind movement.
// maxStrength - The maximal strength of the wind movement.
// strengthScale - Scalefactor for the wind strength.
// interval - The time between minimal and maximal strength changes.
// detail - The detail (number of waves) of the wind movement.
// distortion - The strength of geometry distortion.
// heightOffset - The height where the wind begins to move. By default 0.0.
 
shader_type canvas_item;
render_mode blend_mix;
 
// Wind settings.
uniform float speed = 1.0;
uniform float minStrength : hint_range(0.0, 1.0);
uniform float maxStrength : hint_range(0.0, 1.0);
uniform float strengthScale = 100.0;
uniform float interval = 3.5;
uniform float detail = 1.0;
uniform float distortion : hint_range(0.0, 1.0);
uniform float heightOffset = 0.0;
 
float getWind(vec2 vertex, vec2 uv, float time){
    float diff = pow(maxStrength - minStrength, 2.0);
    float strength = clamp(minStrength + diff + sin(time / interval) * diff, minStrength, maxStrength) * strengthScale;
    float wind = (sin(time) + cos(time * detail)) * strength * max(0.0, (1.0-uv.y) - heightOffset);
    
    return wind;
    }

 
void vertex() {
    vec4 pos = MODEL_MATRIX * vec4(0.0, 0.0, 0.0, 1.0);
    float time = TIME * speed + pos.x * pos.y;
    VERTEX.x += getWind(VERTEX.xy, UV, time);
}
```

### Minimal reproduction project

[Issue.zip](https://github.com/godotengine/godot/files/10609812/Issue.zip)

**Comment by clayjohn** [comment] 2023-02-04 22:58
Duplicate of https://github.com/godotengine/godot/issues/67696

**Closed by clayjohn** 2023-02-04 22:58 UTC

**Comment by Silvanuz** [comment] 2023-02-04 23:03
Thanks for the fast reply.

I can confirm that the workaround from #67696 works great.
