### ISSUE TITLE
Had to download 150MB every upgrade on Steam

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#4108] opened 2016-03-20 15:55 UTC
Because Godot use upx ( which is discouraged by Steam, because they use their own compression ) after every upgrade most of binary is changed and Steam had do redownload it whole ( normally Steam breaks your game files into 1MB chunks and redownload only those chunks that were changed ).

Problem is, that without upx'ing Godot templates games produced by Steam Godot will few MB larger...

Possible solustions with their downsides:
1. Package Godot with upx and compress templates on host - may have problem with upx license, may produce longer installation time/longer package time for games ( if we decide to use upx on templates on game package and give Developer option to use upx or not use upx - this may be good idea ).
2. Have templates as separate DLC.
3. ...?

**Personally I like the idea where game developer can decide if his game should be upx'ed or not.**

**Comment by Marqin** [comment] 2016-03-20 16:00
> 16:59 < Akien> Marqin: And you're mistaken in your issue. Steam uses their own compression _for downloads_, not for installed and exported binaries.
> 16:59 < Marqin> then you can upx godot after steam downloads it :-)

**Comment by punto-** [comment] 2016-03-21 04:36
I agree that the users should understand more what happens during the
"export" process to a platform, the current one doesn't scale very well so
eventually they'll have to tailor it to the needs of their own game.
As far as I remember tho, I removed the upx from the steam binaries, at
least on windows, but that was when they were coming from jenkins.. I don't
remember what's happening on the new travis build.

**Comment by Marqin** [comment] 2016-03-21 12:00
@punto-  I've checked it on my computer, and on OS X Steam editor is compressed by upx, the same for templates.

**Comment by akien-mga** [comment] 2016-03-21 12:07
For the travis build I chose to give a go at upx'ing everything, including Windows 64-bit binaries that we not compressed previously.

So far it seems to work fine, the only possible regression so far seems to be this Windows user reporting better calculation performance on 2.0 than 2.0.1: https://www.reddit.com/r/godot/comments/4b4jhk/godot_201_has_less_performance_than_20/
But I'm still waiting for some feedback on what was the actual procedure to compare the two binaries; I wouldn't expect upx to have an impact on editor performance either anyway.

If we want to distribute Steam binaries non-compressed to benefit from binary deltas, I'm not against it, but we should keep in mind that the export templates should probably be kept the same between the Steam and non-Steam versions. Developers wouldn't want to have exported games with different conditions depending on what Godot version they were using.

**Comment by Marqin** [comment] 2016-03-21 12:08
@punto- ok, I had 2.0.0 on my linux PC so that's what was in 2.0.0:
windows 64bit templates + linux editor there were **not** compressed by UPX ( rest was ).

In 2.0.1 everything is compressed by UPX, even linux editor.

Also, I've looked into Travis conf and it's configured to use upx.

**Comment by akien-mga** [comment] 2016-03-21 12:09
> windows 64bit templates + linux editor there were not compressed by UPX ( rest was ).

That's weird for the Linux editor, as it has always been configured to be upx'ed in the build script. The Windows 64bit templates and editor were not though, with a comment saying that upx did not support 64bit windows properly.

**Comment by Marqin** [comment] 2016-03-21 12:10
@akien-mga what if developers want to publish their games to Steam and benefit from binary deltas, and you give them upx'ed templates? There should be good instructions on how to un-upx them ( including OS X one which is put in some .zip ).

**Comment by akien-mga** [comment] 2016-03-21 12:10
Well we can just stop using upx altogether.

**Comment by Marqin** [comment] 2016-03-21 12:12
> That's weird for the Linux editor, as it has always been configured to be upx'ed in the build script.

```
 ✘  ~/.steam/steam/SteamApps/common/Godot Engine  upx -kt godot.x11.opt.tools.64
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

upx: godot.x11.opt.tools.64: NotPackedException: not packed by UPX

Tested 0 files.

```

**Comment by Marqin** [comment] 2016-03-21 12:18
As for perfomance in 2.0.1:
upx is a DRM without encryption. Normally when you use app only some parts of it are loaded into memory. Here whole executable is uncompressed into memory ( so takes more RAM ). But RAM shouldn't affect performance like that. IMHO that could be difference in compiler version/optimalization flags/LTO ( I don't think LTO is used in Godot ).

**Comment by akien-mga** [comment] 2016-04-04 16:05
Ok. Seeing that:
- UPX is dead upstream, had its [last release in 2013](http://upx.sourceforge.net/) and I can't even find the up-to-date source code for this release (main repo is [stuck in 2011](https://sourceforge.net/p/upx/code/ci/default/tree/))
- UPX has only experimental support for Win64/PE (and from 2013... the format might have evolved with Win10), and apparently no support for 64-bit OSX: http://upx.sourceforge.net

I would propose to just stop using upx for our official releases. It will make it all somewhat bigger, but will likely solve some issues that users are having due to the compression, and also hopefully solve this very issue about Steam binary deltas.

We could still document the usage of UPX in the wiki, for users who would like to bring down the size of their binaries as much as possible, but we probably shouldn't force it on users if it's buggy on various platforms. The alternative is to stay conservative and only compress 32-bit binaries on desktop platforms, but then, better not use it at all IMO (we don't want people to start distributing 32-bit binaries in priority because they're "smaller", it's 2016 :D).

WDYT?

I can give it a try this evening and report how big the whole distribution would be when not using UPX.

**Comment by Marqin** [comment] 2016-04-04 21:17
:+1:

**Comment by akien-mga** [comment] 2016-04-14 05:29
Currently downloading 2.0.2 on Steam, it's still 147.9 MB even though not upx'ed, so Steam properly compresses the binaries for transfer, as expected.
Let's see once we publish 2.0.3 if the binary deltas work fine and give a download of ~10 MB or so.

**Comment by akien-mga** [comment] 2016-07-14 18:48
Should be fixed as we're now no longer using upx. The gain is not obvious so far, but mostly because changes between 2.0.2 and 2.0.3 were still relatively consequent (especially updated libs).

The real gain should come in the upcoming beta branch where we'll push builds more regularly.

**Closed by akien-mga** 2016-07-14 18:48 UTC
Labels: discussion
