### ISSUE TITLE
.DAE reimport won't recognize any animation changes

### ISSUE THREAD

**Issue by lefavilla** [godotengine/godot#40176] opened 2020-07-07 12:41 UTC
This subject is maybe filling this: https://github.com/godotengine/godot/issues/32666

**Godot version:**
3.2.2 RC 1 & 3.2.2 STABLE

**Issue description:**
If you have an existing 3D Model (Name it A) with animations 1,2,3 in your current project and you want to overhaul or redo any animation within that model "A" let's say animation 1 because you are missing some keys. You are at this point extremely far in the project and you already set up a lot of custom tracks. 

Your normal way is… that you click your imported mesh, check that all animation files go into .tres files and that check "keep custom tracks on reimport.". You must click reimport after that change because your .import needs to know that custom tracks should be kept.

Now you go into blender/maya whatever, change your model A especially animation 1 adding some new frame keys or something something. You export it by dae or any format you wish. Then you drop it into the folder where your old model A is and overwrite it. Back in godot, godot does an auto reimport.

Wonderful. You hop now into your .tscn and you try out your animation. It would be lovely to see any changes. But nope, not in Godot.

Godot has some real problems here. You can delete around some .import files and cached stuff. On any point it will work but you loose every custom track you had ever build till then.

HINT: This reimport way was last working with .DAE files in Godot 3.2.2 rc 1

It won't work in the newest stable version Godot 3.2.2 stable. Some of your pops said that this bug has been around since ages. This is something important. The industry gets in trouble if reimporting 3D Models with changed animations won't work. Basic stuff if you name it. Our designer from our team took several hours to get a feeling whats wrong with the reimport system. Thats time and time is value. Now I had some time to look into this. Hope it helps!

**Steps to reproduce:**
1. Clean 3D Gles 2 Project.
2. Build any ugly 3D Model with at least 1 animation. Let it dance or wiggle. Whatever.
3. Import it into your project. Make a scene out of it and give your animation some custom track.
4. Set your 3D file in import-explorer to animation file as ".tres" be sure to check "keep custom tracks on reimport".
5. Go back into the 3D Model with blender/Maya/program and change something in the animation 1.
6. Export your 3D model, overwrite the old model file in your project. Godot will recognize changes.
7. Now if you think your animation realy got important you are something wrong. Nothing happened. But you know you have done everything right.

**What will work and is not an option in a big game, because custom tracks can be big:**

1. You just delete every importet stuff from your old file while godot is closed.
2. You copy your new model into the project.
3. You open godot and every change will be there. Fine.
4. BUT all your custom tracks are now gone.

Sorry for my great english skills. Let me know if you have question.

**WORK AROUND**
Reimport your 3D Models(.dae) with changed animations on godot 3.2.2 rc1 . Push it and reopen it with godot 3.2.2 stable. Works. _Have not tested other formats yet._

*Bugsquad edit (keywords for easier searching): Collada*

**Comment by Calinou** [comment] 2020-07-07 12:59
> I beg my ass of that you please fix this situation.

I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by slapin** [comment] 2020-07-07 14:52
This happens for .escn import too, as well as any other.

**Comment by akien-mga** [comment] 2020-07-07 14:58
I think this might have been fixed by #39968 already (in current `3.2` branch, for 3.2.3), can anyone confirm?

**Comment by slapin** [comment] 2020-07-07 14:59
The bug is started to happen between 3.1 and 3.2 (closer to 3.2) and became worse after that. It happens because scene importer gets resources from cache instead of files on disk. Too hard to debug after that and too hard to find solution which would not look ugly, so I just worked this around by removing .import directory every time I need to update dependent resources. This is one of bugs which will take years to fix until probably the code in question will be rewritten.

I made way to disable/enable cache usage from script, but that requires  to deploy modified engine to everyone, which ended up impossible task, so just removing .import directory is universal solution.

**Comment by slapin** [comment] 2020-07-07 15:02
I suggest using import script for custom tracks, save them to files into directory and add to AnimationPlayer using import script, which will scan directory for files and add these to scene's AnimationPlayer. That will be more reliable.

**Comment by akien-mga** [comment] 2020-08-17 09:41
> I think this might have been fixed by #39968 already (in current `3.2` branch, for 3.2.3), can anyone confirm?

As there's no reproduction project, there's no way for me to verify this. But many other users had reimport problems starting in 3.2.2 which were fixed by #39968.

**Closed by akien-mga** 2020-08-17 09:41 UTC
Labels: bug, needs testing, regression, topic:import
