### ISSUE TITLE
Screen flickers in full screen, when screen resolution is other than native.

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#4340] opened 2016-04-16 16:19 UTC
**Operating system or device:**

Windows 10 64, Geforce gtx970, latest drivers

**Issue description** (what happened, and what was expected):

Screen flickers in full screen, in run game and editor (when the editor window is full screen), when screen resolution is other than native. My native is 1920x1080. Flickers on any lower res.

**Steps to reproduce:**

Change screen res to lower than native. Start a new project, add anything to scene, set fullscreen in settings, play project.

**Link to minimal example project** (optional but very welcome):

**Comment by eska014** [comment] 2016-04-17 18:03
Can't reproduce on Windows 7 with Nvidia, probably a Windows 10 issue

**Comment by vnen** [comment] 2016-04-17 20:33
I can't reproduce either on Windows 10 with Nvidia card.

**Comment by YugoCode** [comment] 2016-05-06 10:38
On the QA-site me and some other have a similar problem:
http://godotengine.org/qa/2186/movement-laggy-in-window-mode-smooth-in-fullscreen-mode

What to do?

**Comment by reduz** [comment] 2016-06-20 20:26
This is fixed now, as we added vsync

**Comment by reduz** [comment] 2016-06-20 20:27
@YugoCode There is nothing to do about this, it's the result of the windows compositor

**Closed by reduz** 2016-06-20 20:26 UTC
Labels: bug, topic:porting
