### ISSUE TITLE
[Bullet] Bullet Physics bad performance in GridMap

### ISSUE THREAD

**Issue by burstina** [godotengine/godot#34963] opened 2020-01-09 20:14 UTC
**Godot version:**
3.2 beta5

**OS/device including version:**
Windows 10

**Issue description:**
running this MRP stress test, Bullet is really slow compared to GodotPhysics.
I see bigger FPS drop when application is procedurally filling the gridmap, When the filling cycle ends, FPS turns good.

**Steps to reproduce:**
run MRP using Bullet and look at top-left label: showing FPS and Gridmap radius
run MRP using GodotPhysics and look at top-left label: showing FPS and Gridmap radius

**Minimal reproduction project:**
Project: [GodotPhysics.zip](https://github.com/godotengine/godot/files/4042312/GodotPhysics.zip)
gridmap.gd tabless (for editor tab-to-space indentation issues) [gridmap.txt](https://github.com/godotengine/godot/files/4049778/gridmap.txt)

**Comment by MightyPrinny** [comment] 2020-01-10 03:31
In my experience performance especially bad on meshes with generated trimesh collision when an object collides with a part of the terrain that isn't flat.

**Comment by burstina** [comment] 2020-01-10 08:21
> 
> 
> In my experience performance especially bad on meshes with generated trimesh collision when an object collides with a part of the terrain that isn't flat, not sure if that is related.

before attached MRP, I tried generated convex collision and performances were also bad

**Comment by lawnjelly** [comment] 2020-01-10 19:02
When I tried to run your project (in a relatively recent 3.2 master) I got 'Parser Error: Mixed tabs and spaces in indentation'.

**Comment by burstina** [comment] 2020-01-10 20:38
> 
> 
> When I tried to run your project (in a relatively recent 3.2 master) I got 'Parser Error: Mixed tabs and spaces in indentation'.

I use these indenting settings and it run fine:
![immagine](https://user-images.githubusercontent.com/47447512/72184786-82a1d400-33f1-11ea-8dea-585da09f6d1c.png)

**Comment by Calinou** [comment] 2020-01-10 21:10
Script parsing doesn't depend on your editor settings, but you do need to convert indentation when saving to fix non-compliant scripts.

**Comment by burstina** [comment] 2020-01-11 01:21
> @burstina Script parsing doesn't depend on your editor settings, but you do need to convert indentation when saving to fix non-compliant scripts.

I unferstand that,  but in editor I have spaces only, no tabs at all, I don't know why you get tabs.

**Comment by lawnjelly** [comment] 2020-01-11 09:38
> > @burstina Script parsing doesn't depend on your editor settings, but you do need to convert indentation when saving to fix non-compliant scripts.
> 
> I unferstand that, but in editor the script has spaces only, no tabs at all, I don't know the reason you get tabs.

You are absolutely right burstina, I just reunzipped the project and opened in a different text editor and the spaces are correct. My Godot is set to use tabs (tabs, 4, auto indent, convert indent on save, draw tabs, NOT draw spaces) and it seems to mess up auto converting when running the project. I'll open an issue for this as it seems to be a bug. (Sorry didn't mean to derail this issue)

**Comment by lawnjelly** [comment] 2020-01-11 11:59
Finally got it to run by ensuring my IDE was in space indentation mode before loading the project! :smile: 

Now to the issue, I can confirm I had the same behaviour on mine, Bullet was slower adding physics objects.

_However_, I would expect this. This is because physics engines typically have different aspects like space partitioning schemes (and different efficiencies with different types of objects). There can be a trade off between the speed of adding objects, and the speed of doing physics queries at runtime. And of course some methods are simply more efficient than others.

For instance having no space partitioning is really quick to add, but can be really slow at runtime with lots of objects.

Also there can be different costs to instantiating objects, sometimes pre-creating a pool can be a good idea.

I have just done a profile with valgrind, here is the result:
![bullet_profile](https://user-images.githubusercontent.com/21999379/72203872-96891c80-3469-11ea-8027-dc18fa7901c3.png)

**Comment by burstina** [comment] 2020-01-11 19:44
I just edited mail message to attach "GridMap.txt": people with indentation issues can download this txt , rename to Gridmap.gd and replace old Gridmap.gd.

**Comment by codespren** [comment] 2020-03-11 14:23
Can confirm that this issue still exists in 3.2.1.

In my case I have created a large world from multiple Gridmaps with static colliders. I load gridmaps dynamically so only gridmaps close to player are loaded and visible. Everything was working fine in Godot 3.1 but starting from 3.2 the background loading is very slow because of static colliders (without colliders the loading is fast). Gridmap and colliders works fine once loaded. Loading works also fast when using Godot Physics instead of Bullet.

It also seems that it's not possible to do loading from background thread. If I load Gridmaps by calling call_deferred from background thread it's still as slow as before.

**Comment by Calinou** [comment] 2020-03-11 14:36
@codespren Can you reproduce this issue in Godot 3.2 alphas/betas/RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/3.2/).

**Comment by codespren** [comment] 2020-03-11 16:54
@Calinou I tested my personal project with few alphas and betas and had same slowness in all of them, including alpha 0.

I did some more testing but unfortunately have problems to reproduce the difference between 3.1 and 3.2. However, I made a simple test project where gridmaps are loaded from code without threads and at least in that test the loading is very slow but there's no significant difference between 3.1 and 3.2:

Gridmaps: 1
Godot 3.1.1 Mono Stable: 3.30380010604858
Godot 3.2.1 Mono Stable: 4.86759996414185

Gridmaps: 2
Godot 3.1.1 Mono Stable: 9.73939990997314
Godot 3.2.1 Mono Stable: 11.2165002822876

Gridmaps: 3
Godot 3.1.1 Mono Stable: 31.4248008728027
Godot 3.2.1 Mono Stable: 32.7775001525879

Gridmaps: 4
Godot 3.1.1 Mono Stable: 55.4754981994629
Godot 3.2.1 Mono Stable: 56.2607002258301 

[gridmaptest.zip](https://github.com/godotengine/godot/files/4319555/gridmaptest.zip)

**Comment by Classy11** [comment] 2020-07-03 23:19
Godot version:
Godot 3.2.2 Mono Stable

OS/PC:
Windows 10 64bit, GTX 1080, i7 7700k, 32gb ram

I am facing performance issues with dynamically loading and unloading the GridMap too. I am also loading and unloading cells based on the player's FOV. Unfortunately, this causes a decent amount of frame skips and lag. I have isolated the issue in my project and it is definitely coming from setting cell items in the GridMap. Running my project in GLES2 renderer mode enhances the performance of dynamic GridMap loading and unloading by a good amount, but I find that to be a rather harsh solution for this issue.

**Comment by slapin** [comment] 2021-01-21 18:50
This is another clockbait bug, the performance issue is not in physics simulation but during addition of collision shapes, which make it similar to https://github.com/godotengine/godot/issues/30027

**Comment by Calinou** [comment] 2022-03-09 21:53
Duplicate of https://github.com/godotengine/godot/issues/30027 (same cause). See also https://github.com/godotengine/godot/issues/28801 (which is unrelated, and occurs with both Bullet and GodotPhysics).

**Closed** 2022-03-09 21:54 UTC
Labels: bug, confirmed, topic:physics, topic:3d
