### ISSUE TITLE
Frequent crash related to GDScript parser

### ISSUE THREAD

**Issue by jivvy** [godotengine/godot#62579] opened 2022-07-01 03:16 UTC
### Godot version

v4.0.alpha.custom_build [afdae67cc]

### System information

Arch Linux, Sway/Wayland

### Issue description

<details open>
<summary>Crash report</summary>

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (afdae67cc381bb340da2e864279da6b836804b7f)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e8e0) [0x7f72e283e8e0] (??:0)
[2] /usr/lib/libc.so.6(+0x1607fd) [0x7f72e29607fd] (??:0)
[3] String::copy_from(char const*) (??:0)
[4] String::String(char const*) (??:0)
[5] StringName::operator String() const (??:0)
[6] GDScriptParser::DataType::to_string() const (??:0)
[7] ExtendGDScriptParser::parse_function_symbol(GDScriptParser::FunctionNode const*, lsp::DocumentSymbol&) (??:0)
[8] ExtendGDScriptParser::parse_class_symbol(GDScriptParser::ClassNode const*, lsp::DocumentSymbol&) (??:0)
[9] ExtendGDScriptParser::update_symbols() (??:0)
[10] ExtendGDScriptParser::parse(String const&, String const&) (??:0)
[11] GDScriptWorkspace::parse_script(String const&, String const&) (??:0)
[12] GDScriptTextDocument::sync_script_content(String const&, String const&) (??:0)
[13] GDScriptTextDocument::didChange(Variant const&) (??:0)
[14] void call_with_variant_args_helper<__UnexistingClass, Variant const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Variant const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[15] void call_with_variant_args_dv<__UnexistingClass, Variant const&>(__UnexistingClass*, void (__UnexistingClass::*)(Variant const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (??:0)
[16] MethodBindT<Variant const&>::call(Object*, Variant const**, int, Callable::CallError&) (??:0)
[17] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (??:0)
[18] Object::callv(StringName const&, Array const&) (??:0)
[19] JSONRPC::process_action(Variant const&, bool) (??:0)
[20] JSONRPC::process_string(String const&) (??:0)
[21] GDScriptLanguageProtocol::process_message(String const&) (??:0)
[22] GDScriptLanguageProtocol::LSPeer::handle_data() (??:0)
[23] GDScriptLanguageProtocol::poll() (??:0)
[24] GDScriptLanguageServer::_notification(int) (??:0)
[25] GDScriptLanguageServer::_notificationv(int, bool) (??:0)
[26] Object::notification(int, bool) (??:0)
[27] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[28] SceneTree::process(double) (??:0)
[29] Main::iteration() (??:0)
[30] OS_LinuxBSD::run() (??:0)
[31] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.tools.64(main+0x174) [0x55c088d772fd] (??:0)
[32] /usr/lib/libc.so.6(+0x29290) [0x7f72e2829290] (??:0)
[33] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f72e282934a] (??:0)
[34] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.tools.64(_start+0x25) [0x55c088d770b5] (??:0)
-- END OF BACKTRACE --
================================================================
```

</details>

### Steps to reproduce

Unsure.
Noticed it first start happening when began using neovim external text editor
**Exec Path**: `/usr/bin/alacritty`
**Exec Flags**: `-e nvr --servername godot --remote-send "<C-[>:e {file}|:call cursor({line},{col})`

**Comment by jivvy** [comment] 2022-07-01 03:25
Seems similar to #55858

**Comment by akien-mga** [comment] 2022-07-01 07:06
Indeed, duplicate of #55858. Feel free to add your details there.

**Closed by akien-mga** 2022-07-01 07:06 UTC
