### ISSUE TITLE
Error compile Linux 

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#14749] opened 2017-12-16 16:09 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Archlinux, 3.0BetaBuilding

**Issue description:**
Fail compilation : 
[Initial build] Compiling ==> modules/tinyexr/register_types.cpp
[Initial build] Compiling ==> modules/tinyexr/image_loader_tinyexr.cpp
[Initial build] Compiling ==> modules/visual_script/visual_script_nodes.cpp
[Initial build] Compiling ==> modules/visual_script/register_types.cpp
In file included from thirdparty/tinyexr/tinyexr.cc:2:
thirdparty/tinyexr/tinyexr.h:442:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
scons: *** [thirdparty/tinyexr/tinyexr.x11.opt.tools.64.llvm.o] Error 1
scons: building terminated because of errors.

**Steps to reproduce:**
Compile with:
scons platform=x11 tools=yes use_llvm=yes target=release_debug bits=64 -j 9

**Comment by vnen** [comment] 2017-12-16 16:19
Duplicate of #14668.

**Closed by vnen** 2017-12-16 16:19 UTC
