### ISSUE TITLE
Make winding order of tilemaps consistent to fix 2d navigation polygon baking

### ISSUE THREAD

**Issue by BerkUnver** [godotengine/godot#85122] opened 2023-11-20 05:12 UTC
### Godot version

4.2 RC 1

### System information

Windows 10

### Issue description

When a painting collision information on a tilemap, you have the option to flip the tile you are rotating horizontally or vertically. However, this transform doesn't take into affect that the winding order of the vertices of polygons is by default clockwise in a tilemap, so the vertices become wound counterclockwise when the tile is flipped. 

This creates a problem when one has overlaps between tilemaps. It causes a navmesh to be generated incorrectly.

### Steps to reproduce

Make a tileset with two tiles.
Add a physics layer to the tileset, and add collision data to the tile.
Flip the collision data horizontally or vertically in the editor, and paint the other tile with this.
Examine the tileset's .tres file.
The vertices of the physics layer for the tile you just painted will be in the counterclockwise instead of clockwise order.

### Minimal reproduction project
[TileMapBug.zip](https://github.com/godotengine/godot/files/13416877/TileMapBug.zip)

The red tiles are the ones with incorrect winding order. If you hide the tilemaps, you can see that the navigation region has incorrectly marked a region as navigable.

**Comment by akien-mga** [comment] 2023-11-20 11:06
A minimal reproduction project would be very helpful for contributors to reproduce and thus understand the problem easily.

**Comment by kleonc** [comment] 2023-11-20 11:33
I think it's intentionally not preserving the winding order as the physics server doesn't care about the winding order. You can apply shapes with any winding order.

Also note that the default tile shapes might have clockwise (CW) / counterclockwise (CCW) winding order depending on the TileSet setup:
| CW |  CCW |
|--------|--------|
|![Godot_v4 2-rc1_win64_LN9nUQBRGO](https://github.com/godotengine/godot/assets/9283098/bed08048-e6eb-4716-a97c-6b6c0dfc2d49)|![Godot_v4 2-rc1_win64_pysVncHFNp](https://github.com/godotengine/godot/assets/9283098/397948a5-f020-4391-875a-fe764dbba8d1)|

So it's not like the collision shapes are meant to be clockwise or something like that.

Regarding potentially preserving the winding order (whether it's originally CW or CCW) of the given collision shape when flipping/mirroring:
![Godot_v4 2-rc1_win64_JHb6f24FIf](https://github.com/godotengine/godot/assets/9283098/d2a16bb8-e92a-45c7-8465-f78c82b39d75)
it's just a matter of additionally reversing the vertices order when performing the flipping, that would be a simple change. The question is whether/why does it need to be changed? :thinking:

**Comment by BerkUnver** [comment] 2023-11-20 15:52
Ok. I've done some more digging, and this is definitely a bug. I can get a NavigationRegion2D to generate incorrect navigation data because of this. I've attached a sample project where this is the case, and renamed the issue likewise.

**Comment by kleonc** [comment] 2023-11-20 16:24
> Ok. I've done some more digging, and this is definitely a bug. I can get a NavigationRegion2D to generate incorrect navigation data because of this. I've attached a sample project where this is the case, and renamed the issue likewise.

cc @smix8

**Comment by smix8** [comment] 2023-11-22 19:17
The winding is not the problem per se, the stacking and nesting of polygons inside each other is.

It forces polygon hole calculation which has a growing chance to yield unwanted results the more polygons are involved.

**Comment by dauntaun** [comment] 2024-03-02 10:18
It looks like the navigation baking simply ignores the rotated shape and defaults to the original orientation. This happens even for single tiles with no nesting/overlap of polygons. Sadly this makes the current workflow of transposing tiles directly in the editor not compatible with navigation baking.

Single tile:
![unwound](https://github.com/godotengine/godot/assets/47953199/4495395a-a7d0-469c-933c-5a93acba7f31)

Two tiles side-by-side:
![side_by_side](https://github.com/godotengine/godot/assets/47953199/b991d610-76dd-4d11-959f-0bea85ba3b99)

Creating alternative tiles and rotating the shape through the tilemap makes the mesh bake properly:
![wound_correctly](https://github.com/godotengine/godot/assets/47953199/2c48ca8e-e610-4412-86ea-6fc33d40c4a9)

**Comment by smix8** [comment] 2024-05-08 15:59
> This seems to be fixed in 4.3 dev 4.


Closing this because solved but also because the winding by default is not relevant for the navmesh baking.

The reason is that the navmesh baking merges all traversable outlines and all the obstruction outlines together. The winding does not matter in this, only the nesting-order of the outlines no matter their winding.

**Closed by smix8** 2024-05-08 15:59 UTC
Labels: bug, needs testing, topic:navigation, topic:2d
