### ISSUE TITLE
Moving files while scenes are open can crash Godot and break projects.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#18199] opened 2018-04-14 16:08 UTC
**Godot version:**

Godot 3.1 dev. (Hash 3a5b25d)

**OS/device including version:**
Win10 64 bit (Fall Creator's Update); 24 gigs RAMl; an AMD 7700HD GPU; i7 3770 CPU

**Issue description:**
I made a backup first so my project is fine, but I did notice that if you were to use the _move file_ command while scenes using the files are open, it will cause Godot to crash. After that, you can try to reopen the project to learn that it now throws errors and will no longer open properly.

If every scene is closed though, you can move as many files as you want without issues.

**Steps to reproduce:**
If you have a project, make a backup first, then have your scenes open and attempt to move a large number of files (script files in my case) to a new folder.

Thank you for looking.

**Comment by Ace-Dragon** [comment] 2018-04-17 14:47
The files are being moved from inside of Godot using its file manager and refactoring tools.

**Comment by reduz** [comment] 2018-09-07 14:05
closing, as duplicate of #16853

**Closed by reduz** 2018-09-07 14:05 UTC
Labels: bug, topic:editor
