### ISSUE TITLE
GLES2 doesn't show imported .dae file

### ISSUE THREAD

**Issue by mszynawa** [godotengine/godot#26519] opened 2019-03-03 10:25 UTC
**Godot version:**
Godot 3.1, beta 10

**OS/device including version:**
Windows 10 x64

**Issue description:**
I have a problem with show imported .dae file when I started game. Model is visible completely random. Anyone has idea why is this happen?

[Visible model](https://gyazo.com/3a1ae2d07eaefd42ae937c514a6e8771)

[Not visible](https://gyazo.com/3778847c982f74298ae6235399978839?fbclid=IwAR2jWXmYvHe4nwwunAAt_XodRXhuz6tj55YiyaqW5SMdcuLlsHmFoXmbjuw)

Error which return console:
`E 0:00:05:0806   Condition ' p_aabb.position.z > 1e15 || p_aabb.position.z < -1e15 ' is true. returned: 0
  <C Source>     ./core/math/octree.h:803 @ create()`

**Comment by akien-mga** [comment] 2019-03-03 10:31
Duplicate of #26468.

**Closed by akien-mga** 2019-03-03 10:31 UTC
Labels: bug, high priority, topic:core
