### ISSUE TITLE
2D Lighting problem in android

### ISSUE THREAD

**Issue by masoudbh3** [godotengine/godot#2482] opened 2015-09-16 21:34 UTC
2D Lighting have problem in android.
see around of occluders:
![1](https://cloud.githubusercontent.com/assets/9015847/9918807/51207646-5cde-11e5-87fb-e537a9c4310b.png)
![2](https://cloud.githubusercontent.com/assets/9015847/9918854/9bdea630-5cde-11e5-9c13-504b98cfa23e.png)

i run '2D Lighting' demo with my galaxy note 3 , after that close it completely, but still running in background and reduce my battery to zero percent in five minutes.

**Comment by akien-mga** [comment] 2015-11-09 12:11
> i run '2D Lighting' demo with my galaxy note 3 , after that close it completely, but still running in background and reduce my battery to zero percent in five minutes.

Is this part strictly related to the 2D Lighting demo, or does it also happen with other demos? If so, please open a separate bug report as it would likely be unrelated to the above graphical glitch.

**Comment by GitGozer** [comment] 2016-06-28 19:29
I also have this problem on my oneplus 2 (android 6.0.01)

**Comment by vnen** [comment] 2016-06-28 21:04
Well, shadows are really buggy, especially on Android. I believe there's nothing to do since the update to GLES3 will try to fix this.

**Comment by vnen** [comment] 2016-06-28 21:09
Also, related issue: #4031

**Comment by reduz** [comment] 2017-08-04 16:57
this will have to wait for 3.1..

**Comment by reduz** [comment] 2018-07-29 17:10
@karroffel should be interesting to see how this works in GLES2 driver

**Comment by akien-mga** [comment] 2018-12-14 16:33
What's the current state in the master branch, with both the GLES2 and GLES3 drivers?

**Comment by arrkiin** [comment] 2019-01-31 09:57
While porting [libre-pinball](https://github.com/Calinou/libre-pinball) by @Calinou to version **3.1 (beta3)** I recognized a problem with GLES2 lights and shadows on Android (Version 8.0.0). Using GLES3 on the same device everything works as expected. I built a tiny project to demo the issue at [GodotLightDemo](https://github.com/arrkiin/GodotLightDemo)

**GLES2 on Android**
![lightdemogles2android](https://user-images.githubusercontent.com/6756598/52045943-dfd8a880-2545-11e9-80c8-794d2de35c97.png)

**GLES3 on Android**
![lightdemogles3android](https://user-images.githubusercontent.com/6756598/52045968-ee26c480-2545-11e9-996c-1d881c4d8978.png)

**GLES2 on Windows**
![lightdemogles2windows](https://user-images.githubusercontent.com/6756598/52046021-072f7580-2546-11e9-8ab1-3d25c4ea614b.png)

**Comment by akien-mga** [comment] 2019-11-26 11:05
@arrkiin I couldn't reproduce the exact issue visible in your screenshot on GLES2 in the current master branch (7e27ac98d), but I can reproduce the issue in the OP with jagged edges around occluders:
![light2d_android_gles2](https://user-images.githubusercontent.com/4701338/69624400-e7bd8800-1044-11ea-9280-4be09d0bd13a.jpg)

I tried making sure that the Rendering/Quality parameters are all the same for desktop and mobile but that doesn't change the result.

Unlikely to be fixed for 3.2 at this point, so moving to 4.0 milestone. It might be solved by the vulkan port, in which case it would still be welcome to have a custom fix backported to the 3.2 branch. (CC @clayjohn)

**Comment by Calinou** [comment] 2019-11-26 13:29
Maybe this is due to shader precision being lower on mobile compared to desktop? Having a project setting to force `highp` precision on all platforms may solve this.

**Comment by KoBeWi** [comment] 2020-10-04 23:29
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment] 2021-05-15 19:39
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-05-15 19:39 UTC
Labels: bug, platform:android, topic:rendering

**Comment by SmartySmart702** [comment] 2021-06-20 23:59
Godot 3.3.2

Win 10, GLES2 (Android 10).

Not sure if its the same problem.
The pictures should explain the problem pretty well. There are also cases where the shadow has some pixelated looking artefacts.
It only occurs if the light if not close to the occluder.

GLES3 is working find.

![GLES2](https://user-images.githubusercontent.com/42713365/122692157-d1cd7480-d233-11eb-940b-9f1c3300cfd5.jpg)
![GLES3](https://user-images.githubusercontent.com/42713365/122692159-d42fce80-d233-11eb-8eb9-36482955e4bc.jpg)

**Comment by Calinou** [comment] 2021-06-21 06:37
@SmartySmart702 Please open a new issue with a minimal reproduction project attached. This issue is quite old by now and the rendering engine has changed entirely since Godot 2.X.
