### ISSUE TITLE
Interface nodes in viewports with override size interacts wrongly with mouse

### ISSUE THREAD

**Issue by juse4pro** [godotengine/godot#45282] opened 2021-01-18 10:57 UTC
**Godot version:**
3.2.3.stable.mono.official

**OS/device including version:**
GLES3
Windows 10

**Issue description:**
When settings display mode to 'disabled' and wrap my game in a viewport which sets it's override size by script to another resolution than the viewport size, no interface nodes seem to have correct coordinates when it comes to overlap checks with the mouse.

**Expected:**
The visible interface nodes are interacting with the mouse correctly. The visible area and clickable area of the elements are the same. Even if the game window is resized by user.

**What happens**
The visible interface and the mouse events seems to use different coordinates. When the user resizes the game window the clickable areas are not at the visible location.

**Steps to reproduce:**
* Create new project
* Go to Project Settings -> Display -> Window
* Set Size to 640x360
* Set stretch mode to 'disabled'
* Create a scene with a viewport container
* Add a viewport to the viewport container
* Set the viewport size to the project settings window size (640x360)
* Add a button (or any interface node) to the viewport
* Set the position of the button to something non-zero (e.g. 100, 100)
* Attach a script to the viewport
* Provide a _Ready override (I was using C#)
* Add calls `this.SetSizeOverride(true, new Vector2(640, 360)); this.SizeOverrideStretch = true;`
* Play the scene
* Resize the game window
* **Now the button position that is affected by the mouse and the visual position of the button seems to be off**

**Minimal reproduction project:**
[BugProof.zip](https://github.com/godotengine/godot/files/5829635/BugProof.zip)

**Video**
https://user-images.githubusercontent.com/7323098/105029807-1b325180-5a53-11eb-9c9f-586b65f53cd3.mp4

**Comment by AlexanderLangguth** [comment] 2021-01-19 12:57
I think I'm having the same issue.
The sizeOverride seems to be ignored in the calculation of the mouse pointers location.

**Comment by Calinou** [comment] 2021-01-19 14:09
Duplicate of https://github.com/godotengine/godot/issues/29570.

**Closed by Calinou** 2021-01-19 14:09 UTC

**Comment by juse4pro** [comment] 2021-01-20 20:53
For simple mouse position evaluations this would be easily possible. But am I capable to create kind of a "mouse event transformation" layer so the Godot control nodes actually knows the new mouse position? 
Is it maybe possible to create a control node that bypasses the mouse events and just transforms it. But I've read that Godot starts with the deepest nodes in the tree with the interface mouse calculation and passes it upwards the tree.

So I don't know how I should actually do this to tell it the Godot interface system.
