### ISSUE TITLE
Continually crashing project on file delete.

### ISSUE THREAD

**Issue by sancarn** [godotengine/godot#21675] opened 2018-09-02 00:13 UTC
Following error:

```
0:00:00:0474 - Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
----------
Type:Error
Description: 
Time: 0:00:00:0474
C Error: Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
C Source: modules/gdscript/gdscript_editor.cpp:287
C Function: debug_get_stack_level_instance
```

I had a C# project which was continually crashing Godot during the build process. This occured after I removed a C# file (Manhole.cs) from the project folder in Windows Explorer. I decided to download and test the project from the non-mono version. And got the above error. If I created an empty Manhole.cs file in the project folder the project would build again.

I'm a bit of a Godot noob so I assume there is an intended way to delete files which I don't know about...

**Comment by akien-mga** [comment] 2018-09-02 07:53
CC @neikeq

**Comment by KellyThomas** [comment] 2018-09-02 12:26
While the editor shouldn't be crashing it is expected that the build would fail you you have remived a `.cs` file but not updated your `.csproj`.

The documentation has some coverage of this and sample of the line to be removed here:  
http://docs.godotengine.org/en/3.0/getting_started/scripting/c_sharp/c_sharp_basics.html#project-setup-and-workflow

**Comment by sancarn** [comment] 2018-09-02 13:42
Thanks @KellyThomas will bare this in mind!

**Comment by aaronfranke** [comment] 2020-10-06 17:38
@sancarn Please re-test with Godot 3.2.3 and/or the master branch. Both of these use the new C# project format, so issues related to the `csproj` file might just not exist anymore. Also, check if you have the latest Mono and .NET Core.

If this issue does still exist for you, then you will need to include a minimal reproduction project.

**Comment by KoBeWi** [comment] 2021-05-22 16:13
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2021-05-22 16:13 UTC
Labels: topic:editor, topic:mono
