### ISSUE TITLE
Scene post-import scripts don't get executed properly

### ISSUE THREAD

**Issue by iboshkov** [godotengine/godot#7175] opened 2016-11-23 01:31 UTC
**Operating system or device - Godot version:**
Likely all (tested on Linux)

**Issue description** (what happened, and what was expected):
Expected the post-import script to work as [described in the documentation](http://docs.godotengine.org/en/stable/tutorials/3d/importing_3d_scenes.html#import-script), but instead it couldn't execute the script.

**Steps to reproduce:**
![image](https://cloud.githubusercontent.com/assets/2392895/20548562/d1c86cf4-b124-11e6-994c-b135b79060a2.png)
![image](https://cloud.githubusercontent.com/assets/2392895/20548565/d74a1a56-b124-11e6-821f-7661449cb9dd.png)

**Link to minimal example project** (optional but very welcome):
[ReproduceImportScript.zip](https://github.com/godotengine/godot/files/607961/ReproduceImportScript.zip)

**Comment by echo-Mike** [comment] 2017-02-15 21:24
Guess:
This error ocures only in file **resource_importer_scene.cpp** in line 1302
```
if (post_import_script.is_valid()) {
		scene = post_import_script->post_import(scene);
		if (!scene) {
			EditorNode::add_io_error(TTR("Error running post-import script:")+" "+post_import_script_path);
			return err;
		}


	}
```
At that time script is loaded and valid, but bag things happen in line 1300:
`scene = post_import_script->post_import(scene);`
VS12 says that this call lay on `post_import` function of `EditorScenePostImport ` class in same file in line 26:
```
Node *EditorScenePostImport::post_import(Node* p_scene) {

	if (get_script_instance())
		return get_script_instance()->call("post_import",p_scene);

	return p_scene;
}
```
Here if script instance exist then post_import method of script executes, but if we trust VS12 next calls ocures:
line 29 `return get_script_instance()->call("post_import",p_scene);` calls function defined in file **script_language.h** in line 305 and implemented in **script_language.cpp** in line 152:
```
Variant ScriptInstance::call(const StringName& p_method,VARIANT_ARG_DECLARE) {

	VARIANT_ARGPTRS;
	int argc=0;
	for(int i=0;i<VARIANT_ARG_MAX;i++) {
		if (argptr[i]->get_type()==Variant::NIL)
			break;
		argc++;
	}

	Variant::CallError error;
	return call(p_method,argptr,argc,error);
}
```
This call count the argument quantity and in line 163 `return call(p_method,argptr,argc,error);` calls next function defined and implemented as _inline_  function in file **script_language.h** in line 306:
```
virtual Variant call(const StringName& p_method,const Variant** p_args,int p_argcount,Variant::CallError &r_error) { r_error.error=Variant::CallError::CALL_ERROR_INVALID_METHOD; return Variant(); }
```
As we can see this function do nothing except seting up an error and returning empty variant.
So after we return in main code segment in file **resource_importer_scene.cpp** `if (!scene)` statement is true and error ocures.
But i may be wrong because dependent on the type of object (here we call by pointer, so it is dependent `return get_script_instance()->call("post_import",p_scene);`) two more functions can be called instead of `PlaceHolderScriptInstance::call`:
`GDInstance::call` in file **gd_script.cpp** line 1296
or
`VisualScriptInstance::call` in file **visual_script.cpp** in line 1950
And error may occur there

**Comment by echo-Mike** [comment] 2017-02-15 21:53
@eska014  please check my comment, i think this bug is architectural problem

**Comment by bojidar-bg** [comment] 2017-08-17 06:42
@echo-Mike Indeed, the problem is that `PlaceHolderScriptInstance::call` would be called instead of `GDInstance::call`. The reason, however, is slightly different from what you proposed, since if what you said was true, no game using GDScript would ever run 😃 .

@iboshkov You forgot to add the `tool` keyword, which is required for scripts that have to work in the editor:
```
tool # needed so it runs in editor
extends EditorScenePostImport

func post_import(scene):
  # do your stuff here
  return scene # remember to return the imported scene
```

I would close this as invalid, if someone gets to retest and find that somehow this still exists, it can be reopened.

**Closed by bojidar-bg** 2017-08-17 06:42 UTC
Labels: bug, topic:editor
