### ISSUE TITLE
Support for TextureRect scale below 1

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#21201] opened 2018-08-19 21:45 UTC
Currently `TextureRect`s scale below `1` is not supported. It can be set but the margin is not correct calculated then. (It still uses the size of scale 1)

**Comment by KoBeWi** [comment] 2019-04-16 12:25
Isn't it the same as #19068?

**Comment by IceflowRE** [comment] 2019-04-16 21:02
In the mentioned issue it's not explicit note for size lower 1, but it addresses the same problem and could be solved with the other.

**Comment by KoBeWi** [comment] 2020-11-13 10:57
Closing as duplicate of #19068

**Closed by KoBeWi** 2020-11-13 10:57 UTC
Labels: bug, topic:gui
