### ISSUE TITLE
Audio produces a strange glitch in the background

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#31339] opened 2019-08-12 22:30 UTC
**Godot version:**
3.1.1-stable

**OS/device including version:**
Windows 10 1803, Realtek Audio drivers

**Issue description:**
The audio gets weirdy distorted, both in engine, and in-game, this is not a cause of my computer, as i can record it and you can hear it clearly in the recording.

**Steps to reproduce:**
Assuming you're able to hear it, simply play a .ogg file

**Minimal reproduction project:**
[AudioGlitch.zip](https://github.com/godotengine/godot/files/3494558/AudioGlitch.zip)

Here's also a video in the event you can't hear it
https://www.youtube.com/watch?v=nVSxnRiVAgg

**Comment by akien-mga** [comment] 2019-08-13 10:15
Can't reproduce it on Linux, the file plays fine in editor, in game and in external music software.

For those like me who'd need some time to actually understand what the glitch is meant to sound like, in the video there's a slight high pitched buzzing sound which is not in the original OGG.

**Comment by Calinou** [comment] 2019-08-13 10:33
This is likely specific to the WASAPI audio driver. I wonder if the XAudio2 driver included in the Godot repository still works (pass `xaudio2=yes` on the SCons command line to build it).

**Comment by Zylann** [comment] 2019-08-13 16:30
Is it like https://github.com/godotengine/godot/issues/23544 ?

**Comment by Calinou** [comment] 2020-03-07 12:29
Duplicate of #23544 indeed.

**Closed by Calinou** 2020-03-07 12:29 UTC
Labels: bug, platform:windows, topic:audio
