### ISSUE TITLE
Global built-in constants are shown as not available in shader include files.

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#68126] opened 2022-11-01 16:46 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

Using global built-in constants (PI, TAU, E) in shader include files show an error `Unknown identifier in expression`, but using the include in a regular shader file does work.

### Steps to reproduce

Create a .gdshaderinc file.
Create a function.
Try referencing any of the global constants (PI, TAU, E).

### Minimal reproduction project

[ShaderincMissingGlobals.zip](https://github.com/godotengine/godot/files/9912387/ShaderincMissingGlobals.zip)

**Comment by Calinou** [comment] 2022-11-01 16:48
Duplicate of https://github.com/godotengine/godot/issues/68124.

**Closed by Calinou** 2022-11-01 16:48 UTC
