### ISSUE TITLE
Can't run Windows 10 UWP exports unless in debug mode

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#18077] opened 2018-04-09 04:59 UTC
**Godot version:** 3.0.2

**OS/device including version:** Windows 10

**Issue description:** When you export a game to UWP with proper certificate signing, it installs fine but once you open the game, it immediately closes. The only way to get it to work is to export it in debug mode.

**Steps to reproduce:**
1. Export a signed UWP app from Godot with debug mode disabled
2. Install
3. Run installed UWP game.

**Comment by nunodonato** [comment] 2018-04-09 10:58
duplicate of #9131

**Closed** 2018-04-09 19:51 UTC
