### ISSUE TITLE
A new -Private- keyword for GDScript

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#28033] opened 2019-04-15 00:50 UTC
**Godot version:**
ANY

**OS/device including version:**
ANY

**Issue description:**
would sure be nice if we got access to a "Private" keyword instead of using the round about way of trying to set private properties. Just saying

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Battlefrog** [comment] 2019-04-15 00:55
As far as I'm aware, this isn't going to be supported for a number of reasons.

First, lineage. gdscript is heavily influenced by Python, which, by itself, does not have the concept of private members within classes. 

Second, simplicity. Programmers can already use encapsulation to hide members from either being accessed or assigned, or both. Private members are just a way of completely blocking access, which can be refrained by the programmer themselves.

At least that's my take. I could be wrong.

**Comment by vonflyhighace2** [comment] 2019-04-15 01:07
Hmm. That never really crossed my mind. I was hoping that GDscript was unique enough to allow some that Python doesn't support. Encapsulation is there but a real pain to deal with if you require a lot of it.

**Comment by akien-mga** [comment] 2019-04-15 11:42
Duplicate of #18411.

**Closed by akien-mga** 2019-04-15 11:42 UTC
Labels: feature proposal, topic:gdscript
