### ISSUE TITLE
[FBX] mixamo animation is broken and mesh skin is hidden

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#43218] opened 2020-10-30 18:23 UTC
**Godot version:**
3.2 4f908fb671959d7a8d1331caa0a8a3a8bce604fa

**OS/device including version:**
Windows 10

**Issue description:**
I wanted to test the new fbx importer from #42941 on a more complex model and found this [animated character](https://opengameart.org/content/gilbert-cartoon-character) on OpenGameArt (Probably exported from Blender with rig+animations from mixamo). While the old version of the importer also has some issues (wrong material, and a weird bend on the arm) it generally imported quite nicely, even the animations. 
When i use the new importer all i see is the rig and no mesh. The animations are also pretty messed up. I don't know if this can be fixed by tweaking some things after importing, but i feel this should work out of the box 😄
I also didn't see any error messages (at least not in my release build). 

@RevoluPowered

Here is what the **new importer** does:
![new_importer](https://user-images.githubusercontent.com/8750135/97741136-946c7900-1ae2-11eb-9de3-9b03be6c1705.gif)

And this is with **3.2.3 stable**:
![old_importer](https://user-images.githubusercontent.com/8750135/97741166-9f270e00-1ae2-11eb-8a82-4d0263e28154.gif)

**Steps to reproduce:**
Just download the model, import and open the fbx scene.

**Comment by RevoluPowered** [comment] 2020-10-31 13:43
Thanks for the first issue, we expect some as we make bug-fixes for the beta release :)

Please can you send me the source assets privately to gordon@gordonite.tech or leave them on this PR if you don't mind them being seen by people?

If you do share directly to my email, please note: they won't be shared anywhere, I will find the bug and fix the problem draw conclusions. If you want I can keep it locally and ensure it wont regress in the future.

Thanks!

**Comment by RevoluPowered** [comment] 2020-10-31 13:59
Notes:
- bone interpolation here is broken with the fbx tracks        ```                                                     [anim interpolation code]```
- the mesh disappearing - again workaround -> clear skin will resolve mesh being invisible.  ```[skin binds are wrong from blender]```

**Comment by RevoluPowered** [comment] 2020-10-31 14:11
If I recall correctly the skin hiding is because of a bug in our code when unused deformers are removed

**Comment by RevoluPowered** [comment] 2020-10-31 14:31
OK so compared against GLTF2, noticed the binds for the skin and the skeleton properties are reversed in the Blender FBX exporter.

**Comment by RevoluPowered** [comment] 2020-10-31 14:33
This code returns the bone rest rather than the skin bind, which means its stores in the FBX the assimp way which was a broken way. 


![image](https://user-images.githubusercontent.com/748770/97781849-eadec380-1b85-11eb-92ac-623290248a6f.png)

**Comment by RevoluPowered** [comment] 2020-10-31 14:55
progress - confirmed skin binds are wrong, most likely the convention they are exported with is actually the wrong axis.

![image](https://user-images.githubusercontent.com/748770/97782371-0eefd400-1b89-11eb-9485-020399f27c9f.png)

**Comment by fire** [comment] 2020-11-16 18:36
Wanted to see if there's any movement on this.

**Comment by RevoluPowered** [comment] 2020-12-16 18:05
#44402 These issues apply to this issue.

**Comment by akien-mga** [comment] 2022-04-06 22:15
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:15 UTC
Labels: bug, confirmed, topic:import, regression, topic:3d

**Comment by mbrlabs** [comment] 2022-04-07 19:53
Yep, can confirm this fixed it :)
