### ISSUE TITLE
File with extension  *.tscn and *.scn  not generated previews in filesystem dock

### ISSUE THREAD

**Issue by AgasferLukich** [godotengine/godot#48428] opened 2021-05-03 20:14 UTC
**Godot version:** Godot_v3.3-stable_win64

**OS/device including version:** Win 10 pro 20H2 , AMD Ryzen 5 3500X , NVIDIA GeForce GTX 750 TI (2 Gb RAM),  GLES3

**Issue description:**  *.tscn and *.scn  not generated previews in filesystem dock.  But generated in Godot_v3.0.6-stable_win64

**Steps to reproduce:** Create and save any scene with Spatial node containing any Mesh (with or without Light source)

**Minimal reproduction project:** 
[test_no_preview_issue.zip](https://github.com/godotengine/godot/files/6417405/test_no_preview_issue.zip)

**Comment by Calinou** [comment] 2021-05-03 21:16
> Issue description: *.tscn and *.scn not generated previews in filesystem dock. But generated in Godot_v3.0.6-stable_win64

This feature was likely lost in the FileSystem dock rewrite in 3.1.

**Comment by JulienVanelian** [comment] 2021-05-04 08:46
Last issue about this is [#47171](https://github.com/godotengine/godot/issues/47171)
And PR [#47172](https://github.com/godotengine/godot/pull/47172)

**Comment by akien-mga** [comment] 2021-05-04 09:32
Thanks, duplicate of #47171.

**Closed by akien-mga** 2021-05-04 09:32 UTC
Labels: enhancement, topic:editor, usability
