### ISSUE TITLE
Floating point inputs in inspector behave dIfferently between Linux and macOS versions of the editor and lose precision upon saving

### ISSUE THREAD

**Issue by eigenax** [godotengine/godot#94167] opened 2024-07-10 10:55 UTC
### Tested versions

- Reproducible in 4.2.2.stable, 4.0.stable, 4.0.alpha1

### System information

Godot v4.2.2.stable - Debian GNU/Linux 12 (bookworm) 12 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (nvidia) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)  ///  Godot v4.2.2.stable - macOS 14.5.0 - Vulkan (Mobile) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

The Inspector behaves differently between macOS and Linux when editing `float` (and floating-point vector-type) properties.
It seems on macOS numbers are usually displayed and saved correctly, while on Linux both whole numbers and fractions are often displayed and saved incorrectly.

If I remember correctly, months ago I read in another issue about property range hints that the behavior on Linux was intended to reflect the inability of `float`s to store arbitrary fractions, but the conversion from the entered value to one that can be stored in a float often does not work correctly.
Small whole numbers can usually be stored without loss of precision. The number 40 for example is represented as 01000010001000000000000000000000 (sign 0 = positive, exponent 10000100 = 2^5 = 32, mantissa 01000000000000000000000 = 1 + 0.25 = 1.25), which is 32 * 1.25 = 40 (exact).
Fractions that are 1 divided by a power of two (1/2^x) can also be stored without loss of precision for small exponents, yet on Linux Godot rounds 0.015625 (which is 1/64) to 0.01559599999746 (displayed when hovering the field), displays it as 0.0156 in the text field and saves it as 0.015596 in the tscn-file.

Converting a manually entered 0 to -0 should also be avoided, even if both are valid IEEE 754 `float`s.

These conversions occur in the `step`-field of `TextureProgressBar` as well as its `custom_minimum_size`, `Control`'s `position` and `size`, `Node2D`'s `scale`, but not `Node2D`'s or `Node3D`'s `position` (where whole numbers are usually stored as entered, but fractions are rounded to 3 decimal places (e.g. 0.0625 to 0.0630000000092, saved as 0.063) which is not ideal either.

### Steps to reproduce

Create a new `TextureProgressBar`. Its `min_value` is shown as 0 and its `max_value` as 100 on macOS, while on Linux -0 and 99.9999 is displayed. The resulting tscn-files do not differ.

However, entering 40, 40 in the `TextureProgressBar`'s `custom_minimum_size` fields results in tscn-files reflecting the difference in the editor: on macOS the resulting file contains `custom_minimum_size = Vector2(40, 40)` (as displayed in the Inspector on macOS), while the file created on Linux containes `custom_minimum_size = Vector2(39.9996, 39.9996)` (as displayed in the Inspector on Linux).

This behavior is not unique to `TextureProgressBar`, but affects many if not all floating-point inputs in the editor.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-08-04 14:48
Likely duplicate of:
* https://github.com/godotengine/godot/issues/91631

Closing as solved, if you can still reproduce this in [4.3.rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/) please comment and this can be reopened

**Closed by AThousandShips** 2024-08-04 14:48 UTC
Labels: discussion, topic:core
