### ISSUE TITLE
Memory leak when using `weakref()`

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#90086] opened 2024-03-31 23:38 UTC
### Tested versions

- Reproducible in 4.2.1 Stable and master 29b3d9e9e538f0aa8effc8ad8bf19a2915292a89

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

The following code leaks memory:

```GDScript
extends Node

class MyObj:
	var obj: MyObj

func _process(_delta: float) -> void:
	var obj_1 = MyObj.new()
	var obj_2 = MyObj.new()
	# obj_1.obj = obj_2 # does not leak
	obj_1.obj = weakref(obj_2) # leaks
```

If you swap the commented line with the line that leaks, it will no longer leak.

This also happens with other types:

```GDScript
extends Node

class MyResource extends Resource:
	var my_resource : MyResource

func _process(_delta: float) -> void:
	var res_1 : MyResource = MyResource.new()
	var res_2 : MyResource = MyResource.new()
	#res_1.my_resource = res_2 # does not leak
	res_1.my_resource = weakref(res_2) # leaks
```

I expect that `weakref()` should not have this sort of impact in this scenario. Please correct me if I am mistaken!

With `weakref()`:
![image](https://github.com/godotengine/godot/assets/17506573/dedf43d5-ba35-4764-b157-4e69da40f129)

Without `weakref()`:
![image](https://github.com/godotengine/godot/assets/17506573/900292bb-e0b0-4b1e-b8e0-ae7927769547)

### Steps to reproduce

1. Paste either of the above code snippets on a node in a scene and run the game.
2. Watch the Static Memory Monitor.

### Minimal reproduction project (MRP)

[weakref-leak-bug.zip](https://github.com/godotengine/godot/files/14817931/weakref-leak-bug.zip)

**Comment by scrahe** [comment] 2024-04-01 00:52
I'm guessing this is how it's supposed to work, as it's not supposed to un-allocate the memory. It also says this in the documentation, that until the game needs the memory, it won't delete the objects.

**Comment by timothyqiu** [comment] 2024-04-01 01:13
"Objects" in "Monitors" panel shows the number of objects growing indefinitely.

Changing `var obj: MyObj` inside `MyObj` to `var obj: WeakRef` fixes the problem.

Assigning the weak reference to a plain `MyObj` directly is an error:

```gdscript
var x: MyObj = weakref(obj_2)
# ERROR: Trying to assign value of type 'WeakRef' to a variable of type ''.
```

I guess something wrong happened during the implicit conversion.

**Comment by dalexeev** [comment] 2024-04-02 09:43
Use `NOTIFICATION_PREDELETE` to check if the object is freed:

```gdscript
class MyObj:
    var id: int
    var obj: MyObj

    func _init(p_id: int) -> void:
        id = p_id

    func _notification(what: int) -> void:
        if what == NOTIFICATION_PREDELETE:
            prints(id, "freed")

func _run() -> void:
    var obj_1 = MyObj.new(1)
    var obj_2 = MyObj.new(2)
    #obj_1.obj = obj_2 # Does not leak.
    obj_1.obj = weakref(obj_2) # Does not leak.
```

```gdscript
class MyObj:
    var id: int
    var obj: WeakRef # <-- !!!

    func _init(p_id: int) -> void:
        id = p_id

    func _notification(what: int) -> void:
        if what == NOTIFICATION_PREDELETE:
            prints(id, "freed")

func _run() -> void:
    var obj_1 = MyObj.new(1)
    var obj_2 = MyObj.new(2)
    obj_1.obj = obj_2 # `obj_2` leaks.
    #obj_1.obj = weakref(obj_2) # Does not leak.

```

The implicit conversion between `WeakRef` and `Object`/`RefCounted` is quite unexpected. But I think this is not a GDScript issue, the line is highlighted as unsafe (though we don't have the `UNSAFE_ASSIGNMENT` warning). Looks like this is a core issue.

**Comment by AThousandShips** [comment] 2024-04-02 10:31
There's no casting at least not valid casting occurring, try just `print(obj_1.obj)` after assigning it, it'll print `<null>`, there's no warning as `weakref` is just `Variant` and can be cast to any object type as `null`, the leak though is a question

**Comment by AThousandShips** [comment] 2024-04-02 11:19
It seems to be a core issue, it happens when ever you assign an invalid object type which is refcounted, caused by this code it seems:
https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/core/variant/variant_construct.cpp#L320-L348

The `init_ref` causes it to gain excess refs I believe, will try a fix

**Comment by AThousandShips** [comment] 2024-04-02 11:31
Will try dig into the casting or conversion of refcounted, seems to be some glitch with the count increment

**Comment by dalexeev** [comment] 2024-04-02 12:52
> This seems to be related to how property access is handled, as:
> 
> ```gdscript
> var w : WeakRef = obj_2
> ```
> 
> Fails with an error at runtime, so something is wrong with how `obj_1.obj` is processed on assignment

If the base type is not known at compile time, then the property is assigned as follows:

`Variant::set_named()` -> `Object::set()` -> `GDScriptInstance::set()`

And `Object.set()` does not report errors, according to [the docs](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set):

> Assigns value to the given property. If the property does not exist or the given value's type doesn't match, nothing happens.

**Comment by AThousandShips** [comment] 2024-04-02 13:04
The code that's causing the leak is this:
https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/modules/gdscript/gdscript.cpp#L1605-L1612

Something about how it handles conversions here means the value leaks, even though at the end of the conversion `value` is `null`

Can't quite find what in the code is broken exactly, probably something in:
https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/core/variant/variant_construct.cpp#L331-L348

Not handling something correctly

**Comment by AThousandShips** [comment] 2024-04-02 13:42
It seems that it's due to how the construction of an object doesn't correctly assign type, so it's a `Variant` with type `NIL` but the object is still assigned

Will write up a fix, new changes makes it error on runtime, and doesn't leak

**Closed** 2024-07-26 11:48 UTC
Labels: bug, topic:core, topic:gdscript
