### ISSUE TITLE
Signals connected from the editor are no longer connected on exported versions in dev 4.4 dev6

### ISSUE THREAD

**Issue by pixel-boy** [godotengine/godot#100343] opened 2024-12-13 00:01 UTC
### Tested versions

Reproductible in dev 4.4 dev6
I tried several versions, I first had the impression that the problem disappeared from version 4.4 dev2 but the behavior seems random / not always identical, I even have the impression of having succeeded in exporting with 4.4 dev6 without the problem.

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6636) - AMD Ryzen 7 2700X Eight-Core Processor (16 threads)

### Issue description

Signals connected from the editor seem not to connect in the exported build, this happens in version 4.4 dev6 (I don't know if it happens all the time, I did several tests with different versions and the behavior seems a bit weird / random)

### Steps to reproduce

- Connect a signal via the editor
- Export the project
- The connection is not made in the exported version

### Minimal reproduction project (MRP)

[Minimal Project.zip](https://github.com/user-attachments/files/18118834/Minimal.Project.zip)

**Comment by AeioMuch** [comment] 2024-12-13 00:11
Thank you for reporting!

It's a duplicate of https://github.com/godotengine/godot/issues/100097
And fixed already by https://github.com/godotengine/godot/pull/100235

**Closed** 2024-12-13 00:28 UTC
