### ISSUE TITLE
no tiles in inspector for TileSet in 3.2.1 stable

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#37707] opened 2020-04-09 04:57 UTC
**Godot version:**
3.2.1 stable
**OS/device including version:**

**Issue description:**
start from 3.2.1, no tiles are shown in the inspector when edit the TileSet

**Steps to reproduce:**
add a TileMap
add a TileSet for that tilemap
add some tiles
select the TileSet to edit
no tiles is show in the inspector. 

**Minimal reproduction project:**
<img width="445" alt="Screen Shot 2020-04-09 at 12 46 19 PM" src="https://user-images.githubusercontent.com/1130047/78859207-466a2800-7a61-11ea-9620-12b6cacf10d0.png">
<img width="428" alt="Screen Shot 2020-04-09 at 12 48 02 PM" src="https://user-images.githubusercontent.com/1130047/78859225-4ec26300-7a61-11ea-81f3-dcf6fc6d726e.png">

**Comment by Calinou** [comment] 2020-04-09 07:45
Duplicate of #37522

**Closed by Calinou** 2020-04-09 07:45 UTC
