### ISSUE TITLE
Overriding _UnhandledInput leads to increasing number of Objects

### ISSUE THREAD

**Issue by LasseSchnepel** [godotengine/godot#81083] opened 2023-08-28 18:18 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

If I overwrite _UnhandledInput, the Performance Monitor for ObjectCount shows an increasing number with every call to my overriding function.
This is independent of the content of the function, I tried both an empty function and a call to the base method.

This applies to C#, but seems fine with GDScript.

C#:
```c#
using Godot;

public partial class MRP : Node3D
{
    public override void _UnhandledInput(InputEvent evt)
    {
        GD.Print(Performance.GetMonitor(Performance.Monitor.ObjectCount));
    }
}
``` 

GDScript (does not show increasing number of objects)
```GDScript
extends Node3D

func _unhandled_input(event):
	print(Performance.get_monitor(Performance.OBJECT_COUNT))
	pass
```

### Steps to reproduce

Create a project with a Node than overrides _UnhandledInput, start the game and move the mouse over the window. (or start the provided MRP)

### Minimal reproduction project

[LeakMRP.zip](https://github.com/godotengine/godot/files/12457160/LeakMRP.zip)

**Comment by AThousandShips** [comment] 2023-08-28 18:26
Duplicate of #75269

**Closed by AThousandShips** 2023-08-28 18:26 UTC
