### ISSUE TITLE
ERROR Initialize: Directional Shadow Framebuffer status invalid at: drivers/gles2/rasterizer_scene_gles2.cpp:3369 On Windows 7 Professional 32 Bit

### ISSUE THREAD

**Issue by newbie125** [godotengine/godot#30181] opened 2019-06-29 09:29 UTC
**Godot version:** v3.1.1.stable.official

**OS/device including version:** Windows 7 Professional (32-bit) (OS Build 6.1.7601)

Intel HD Graphics Driver Version 9.17.10.4229

**Issue description:**

When Opening Godot Editor at startup (v3.1.1.stable .official) following error occurs:
ERROR Initialize: Directional Shadow Framebuffer status invalid at: drivers/gles2/rasterizer_scene_gles2.cpp:3369
I have run OpenGL extension viewer to confirm which version of OpenGL ES  my driver supports. It shows v3.1 is supportable(SnapShot Attached). While GodotV3.1.1 Stable Official requires OpenGL ES 2.0 compatible Hardware. Does this causing the issue?
Any answer would be app
![OpenGL ES Version](https://user-images.githubusercontent.com/52110609/60382275-2ccf9500-9a7a-11e9-973f-517c0c0c8cb0.PNG)
reciated!  

**Steps to reproduce:**
This occur at startup of Godot Editor v3.1.1 Stable official.

**Minimal reproduction project:**

![GLES2 0 Error Snapshot](https://user-images.githubusercontent.com/52110609/60382164-c72ed900-9a78-11e9-9e40-ec4d1dbdab46.PNG)

**Comment by KoBeWi** [comment] 2019-06-29 21:21
Duplicate of #28894

**Closed by KoBeWi** 2019-06-29 21:21 UTC
