### ISSUE TITLE
Project explorer opens without text on some ui elements

### ISSUE THREAD

**Issue by jjay** [godotengine/godot#4922] opened 2016-05-30 17:32 UTC
**Operating system or device - Godot version:**
OSX 10.11.5, Godot built from [73918100b](https://github.com/godotengine/godot/commit/73918100b)

**Issue description** (what happened, and what was expected):
Project explorer opens without text on some ui elements (possibly translated).
![godot_project_bug](https://cloud.githubusercontent.com/assets/122736/15655383/5d178084-26a5-11e6-8ac3-d6c62e2976f1.png)

**Steps to reproduce:**
`git checkout 73918100b && scons platform=osx && ./bin/godot.osx.tools.32`

**Comment by akien-mga** [comment] 2016-05-30 17:35
Duplicate of #4879.

**Closed by akien-mga** 2016-05-30 17:35 UTC
Labels: bug, platform:osx, topic:editor
