### ISSUE TITLE
Renaming a Mono Godot project causes script assembly to not be loaded

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#47528] opened 2021-03-31 15:10 UTC
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Windows 20H2
1030 GT, unsure of driver version
GLES3

**Issue description:**

Rename a project in the Godot project menu, and try to run the project. Scripts will not be loaded.
When trying to rename the project in the Godot project menu, a lot of warnings appear in the console.
![image](https://user-images.githubusercontent.com/1487089/113167175-5fa05180-923b-11eb-80b5-a69340fb836d.png)

**Steps to reproduce:**
- Open the provided minimum reproduction project
- Try to run it, and observe the error about the assembly not being loaded
- Close the project
- Rename it to "Rename test"
- Open the project
- Try to run it, observe "READY!" being printed in the console as the scripts are loaded this time

**Minimal reproduction project:**

[Rename test.zip](https://github.com/godotengine/godot/files/6237551/Rename.test.zip)

Hopefully this hasn't been reported already.
(And sorry for the issue spam! Hopefully this minimal reproduction project is small enough.)

**Comment by Calinou** [comment] 2021-03-31 16:26
Duplicate of https://github.com/godotengine/godot/issues/27030 (same cause).

**Closed by Calinou** 2021-03-31 16:26 UTC
Labels: bug, topic:editor, topic:mono
