### ISSUE TITLE
Visual artifacts in spatial shader involving alpha channel on nVidia GPUs

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot#71729] opened 2023-01-20 12:40 UTC
### Godot version

3.x (as of 13 January 2023)

### System information

Ubuntu 22.04.1 LTS, AMD 3020e

### Issue description

Encountered a peculiar bug, which may be related to alpha channel overflow(?) on nVidia GPUs (tested on friend's 1080ti and 3050ti, Windows 10). No issues found on Intel, AMD and mobile GPUs that I could test my game on (Linux, Windows and Android).

![bug_in_game](https://user-images.githubusercontent.com/46825200/213693982-5fd516a8-ed95-47bf-8f32-2479e2a8dd71.jpg)

Those white bands appear at the edge of the cloud models, where alpha channel approaches 0.
I thought that clamping alpha channel between 1e-4 and 1.0 would solve the issue by creating a safety margin, but it doesn't seem like it.

Here is the shader used on the clouds (clouds are just deformed 3D spheres): https://github.com/roalyr/GDTLancer/blob/master/Assets/Shaders/Clouds/Cloud_mix/CloudSolid_mix/CloudSolid_mix_cull_front.gdshader

There is a possibility that it could be related to me using a custom build of Godot 3 (log depth buffer), but it doesn't explain peculiar buggy behavior exclusively on nVidia GPUs.

### Steps to reproduce

See minimal reproduction project. I have included clouds with buggy shader, as well as background stars with `DEPTH = 1` shader to simulate in-game scene as closely as possible.

Here is the compiled Windows MRP (exported using https://github.com/roalyr/godot-for-3d-open-worlds/releases/tag/3.x-2023.01.13):  

[nVidia test.exe.zip](https://github.com/godotengine/godot/files/10466257/nVidia.test.exe.zip)

1. Launch it on AMD or Intel GPU, it should look like this
![Intended look](https://user-images.githubusercontent.com/46825200/213695638-93ca251f-1b57-4f19-addd-f2ec0f2784f3.jpg)
2. Launch it on nVidia and it should look like this (notice the bands on the edges of the clouds)
![bug_in_test](https://user-images.githubusercontent.com/46825200/213695875-127f27ff-216e-4e36-b942-85861bb407eb.jpg)

### Minimal reproduction project

[nVidia_GPU_shader_bug.zip](https://github.com/godotengine/godot/files/10466299/nVidia_GPU_shader_bug.zip)

**Comment by lawnjelly** [comment] 2023-01-20 16:16
Yes, can confirm, if you change your shader to:
```
void fragment()
{
	float dt = dot(NORMAL, VIEW);
	if (dt < 0.0)
	{
	}
	else
	{
	float rim = clamp(pow(dot(NORMAL, VIEW), rim_power)*rim_strength, 1e-4, alpha_clip);
	ALBEDO = albedo.rgb*COLOR.rgb;
	ALPHA = rim;
	}
}
```
You get the same effect.

Will close this once you've digested.

**Comment by lawnjelly** [comment] 2023-01-20 17:08
Closing as this is most likely caused by the mechanism above. Can reopen if this does not fix it _in vivo_.

**Closed by lawnjelly** 2023-01-20 17:08 UTC
Labels: topic:rendering

**Comment by roalyr** [comment] 2023-01-20 20:19
Clamping `dot(NORMAL, VIEW)` in a test shader indeed makes it work as intended, which is exactly the desired behavior. I will send the game to test and confirm it for sure after that.

**Comment by roalyr** [comment] 2023-01-20 22:41
All good.
