### ISSUE TITLE
TileMap Navigation map synchronization error because of different `cell_size`

### ISSUE THREAD

**Issue by mohe2015** [godotengine/godot#79474] opened 2023-07-14 17:55 UTC
### Godot version

4.1.dev.custom_build [e709ad4d6407e52dc62f00a471d13eb6c89f2c4c]

### System information

Godot v4.1.dev unknown - NixOS 23.11 (Tapir) - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 4700U with Radeon Graphics (8 Threads)

### Issue description

I expected that a TileMap with two navigation layers simply works. But when running the project the following error is thrown:
```
ERROR: Navigation map synchronization error. Attempted to update a navigation region with a navigation mesh that uses a different `cell_size` than the `cell_size` set on the navigation map.
   at: update_polygons (modules/navigation/nav_region.cpp:118)
```

### Steps to reproduce

1. Create `TileMap` root node
2. Add a second layer to the `TileMap`
3. Add `TileSet` to the `TileMap`
4. Add two navigation layers to `TileSet`
5. Drag `res://icon.svg` into the `TileSet` tiles to create an atlas out of it.
6. Select top left tile and reset to default shape for both navigation layers.
7. Add the top left tile somewhere on the `TileMap`
8. Run the project

### Minimal reproduction project

[TileMapNavigationBug2.zip](https://github.com/godotengine/godot/files/12052765/TileMapNavigationBug2.zip)

**Comment by AThousandShips** [comment] 2023-07-14 17:58
Duplicate of #79468

**Closed by AThousandShips** 2023-07-14 17:58 UTC

**Comment by mohe2015** [comment] 2023-07-14 18:07
> * Duplicate of [Navigation region 3D not syncing #79468](https://github.com/godotengine/godot/issues/79468)
> 
> 
> See there for the solution

I have a few questions to that:

1. What are the correct values for which project settings for my provided reproduction project? Could you maybe quickly try it please because I tried setting all settings containing `cell_size` to 1 and all to 0.25 and both didn't seem to work.
2. In the project settings for navigation/2d/default_cell_size I can't set decimal numbers but only integers. Is this intended? 
3. Could the error message show the differing values so you know which value you need to set to which value? Because currently it's more blind guessing.
4. I would expect that this seemingly super basic setup would work by default and not fail with this unclear error message.

**Comment by AThousandShips** [comment] 2023-07-14 18:14
CC @smix8
