### ISSUE TITLE
The default project settings are set to OpenGL ES v3 instead of v2.

### ISSUE THREAD

**Issue by 5N08** [godotengine/godot#23510] opened 2018-11-04 19:42 UTC
**Godot version:**
3.1 alpha 2 portable

**OS/device including version:**
Win 7 32bits / Sony Vaio laptop with Intel HD integrated graphics

**Issue description:**
The default project settings are set to OpenGL ES v3 instead of v2. This renders v2 support useless since people with older graphics cards still can't get beyond project manager. What happens right now is that the editor (and video card) crashes the moment I try creating a new project.

**Steps to reproduce:**
Have older machine without GLES3 support and try creating a new project.

Thanks for supporting GLES2 and for fixing this.

**Comment by NewNodeGames** [comment] 2018-11-04 20:09
The problem is not the default project settings. Check this, happens in Windows with the default environment: https://github.com/godotengine/godot/issues/21551
I use Linux and this issue don't happen.

**Comment by 5N08** [comment] 2018-11-04 20:42
@NewNodeGames You are correct. I deleted the file as well and it starts properly now with empty scene.
Thanks.

**Comment by akien-mga** [comment] 2018-11-05 07:47
Duplicate of #21551 then.

**Closed by akien-mga** 2018-11-05 07:47 UTC
