### ISSUE TITLE
Debugger shows object as "null", even though it's a "Deleted Object"

### ISSUE THREAD

**Issue by Sulter** [godotengine/godot#65110] opened 2022-08-30 20:16 UTC
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

When the debugger is displaying the content of a freed object, it will show up as containing "null".
This is not correct as the object is actually a "Deleted Object" as printed in the example below:

```swift
extends Node2D
var ref: Object
func _ready():
	ref = Node2D.new()
	add_child(ref)
	ref.queue_free()

func _process(_delta):
	if ref: 
		print(ref) #set breakpoint here

```

Debugger view using external debugger (Visual Code):
![image](https://user-images.githubusercontent.com/5460908/187533555-e3f9ce77-56d3-492d-94f2-ede42f8896a1.png)

This has been tested and reproduced with external editor Visual Code as well as the internal tool.

This is confusing for the user, as you expect the debugger to tell you the content of the object.

### Steps to reproduce

Run the GDscript above

**Comment by Calinou** [comment] 2022-08-30 20:18
Duplicate of https://github.com/godotengine/godot/issues/49019 and/or https://github.com/godotengine/godot/issues/59816 (same cause).

**Closed by Calinou** 2022-08-30 20:18 UTC
