### ISSUE TITLE
NavigationRegion3D.bake_navigation_mesh() crashes application when Parsed Geometry Type, Source Geometry Mode, Source Group Name were set

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#39321] opened 2020-06-05 13:14 UTC
**Godot version:**
4.0.dev
Commit: f05b4fea33e84ea3322702d774d69926a41ba913 [f05b4fe]

**OS/device including version:**
Windows 10 x64 Bit

**Issue description:**
Thru GDScript:
 NavigationRegion3D.bake_navigation_mesh() crashes application when this following were set for the NavigationMesh:
- set_parsed_geometry_type(0)
- set_source_geometry_mode(1)
- set_source_group_name("navmesh")

**Steps to reproduce:**
Thru GDScript:
1. Create a scene with the following nodes:
- Navigation3D
- NavigationMesh
- NavigationRegion3D
- 3 MeshInstance with CubeMesh (1 floor, 2 boxes)

2. Position the 3 MeshInstance with the floor on the bottom and the 2 boxes on top of the floor.
3. Add_to_group "navmesh" the FloorMeshInstance
4. Set the following parameters for the NavigationMesh:
- set_parsed_geometry_type(0)
- set_source_geometry_mode(1)
- set_source_group_name("navmesh")
5. Assign the NavigationRegion3D.navmesh = NavigationMesh
5. Run NavigationRegion3D.bake_navigation_mesh() 

_I also tried using a pre-made NavigationMesh.tres file with the said parameters set, still it crashes on baking._

**Expected Result:**
NavigationMesh is baked properly (check the generated test.tscn in Maps folder, see attached minimal reproduction project)

**Minimal reproduction project:**
Run the Lobby Scene, Click Create Map

[BakeNavmeshCrash.zip](https://github.com/godotengine/godot/files/4736295/BakeNavmeshCrash.zip)

**Comment by Calinou** [comment] 2020-06-05 13:26
cc @AndreaCatania

**Comment by smix8** [comment] 2022-05-17 23:04
I removed everything from the MRP that had nothing to do with the issue as meshes and more were broken in newer Godot versions. The described steps work without any issues until the scripted baking except that boxes are ignored if only floor has groupname but that is not a bug.

The different baking settings do not contribute to any error here.

The issue is that `NavigationRegion3D.navmesh = NavigationMesh.new()` will already trigger a navmesh update on the NavigationServer. An immediate call to `NavigationRegion3D.bake_navigation_mesh()` will break the navmesh while it is registering. Need to wait a frame or call the baking function deferred.

@Calinou @akien-mga 
I think this issue can be closed as a duplicate as the problem with users creating procedual navmeshes and immediatly baking to a crash is noted in other open issues with more detail.

**Closed** 2022-05-17 23:39 UTC
Labels: bug, topic:navigation
