### ISSUE TITLE
AnimationTree forces properties to be at value in RESET track in `UPDATE_DISCRETE` and `UPDATE_TRIGGER` mode

### ISSUE THREAD

**Issue by zacryol** [godotengine/godot#69066] opened 2022-11-23 19:29 UTC
_Bugsquad Edited: This problem occurs in beta6, but has already been addressed in master. There is no more need to report._

---

### Godot version

4.0.beta6

### System information

Linux

### Issue description

When using multiple animations with an AnimationTree, it appears as though the RESET track is prioritized above all others.
The included MRP shows an example: The two animations, one to set visible and one to set the flip_v, do not appear to play at all, as the value is being forced. Changing the value in the RESET track will change the value it's stuck at. The spin animation works as long as it's playing (as it gets set every frame in a more continuous manner), but as soon as that animation ends, it's back to the RESET track value.

### Steps to reproduce

Make an AnimationTree that uses animations that have values in the RESET track.

### Minimal reproduction project (updated)
[anim-bug-mrp.zip](https://github.com/godotengine/godot/files/10078645/anim-bug-mrp.zip)

**Comment by zacryol** [comment] 2022-11-23 19:30
This is a regression, as I did not have this problem in beta4.

**Comment by KoBeWi** [comment] 2022-11-23 19:39
I opened the project and not sure what's the problem. How do you even play the animations?

**Comment by KoBeWi** [comment] 2022-11-23 19:43
> The animations are played automatically by the AnimationTree and StateMachine.

Doesn't look like it.

> The spin animation can be played by clicking it in the editor.

There is no spin animation.

It would be helpful if you recorded some video maybe.

**Comment by zacryol** [comment] 2022-11-23 19:44
I may have added that after zipping the project

**Comment by zacryol** [comment] 2022-11-23 19:48
https://user-images.githubusercontent.com/60046681/203634142-be22dbf4-2489-4653-ba9b-9f79ce30c170.mp4

**Comment by zacryol** [comment] 2022-11-23 19:56
I also checked beta 5, and it works correctly there.

**Comment by TokageItLab** [comment] 2022-11-23 20:18
I also cannot reproduce it. I think this problem already has been fixed in #68993.

**Comment by TokageItLab** [comment] 2022-11-23 20:28
Oh, unfortunately that fix seems to have been merged right after the beta6 build was created, please wait for beta7.

**Comment by TokageItLab** [comment] 2022-11-23 20:40
I consider this issue slightly bigger, so I pin this on issue board until beta7.

**Comment by zacryol** [comment] 2022-11-23 20:49
> Oh, unfortunately that fix seems to have been merged right after the beta6 build was created, please wait for beta7.

Yeah, I just built from master (https://github.com/godotengine/godot/commit/f05a55ef9579fdcd7928b528dbc66dc11b039948) and it seems to work there.

**Closed** 2022-11-23 21:14 UTC
Labels: bug, regression, topic:animation
