### ISSUE TITLE
GDScript debugger crashes the instant a doubly linked list is made using a Dictionary.

### ISSUE THREAD

**Issue by SamuelNewhouse** [godotengine/godot#34512] opened 2019-12-21 14:11 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Home, Version 1809, OS Build 17763.914

**Issue description:**
If run normally the game will not crash, but stepping through the code with the GDScript debugger causes the debugger to crash the instant a doubly linked list is made using a Dictionary. The moment the list is linked both forwards and backwards, the debugger crashes.

**Steps to reproduce:**
1. Use a dictionary with "next" and "previous" keys as a structure for a doubly linked list.
2. Use a loop inside _ready() to create the doubly linked list.
3. Run the game and it will not crash.
4. Step through code with the debugger and it will crash on the second loop when "previous" is assigned to the first list item.

**Minimal reproduction project:**
[Doubly Linked.zip](https://github.com/godotengine/godot/files/3991449/Doubly.Linked.zip)

**Comment by Zylann** [comment] 2019-12-21 14:30
List nodes are reference cycles. Item 1 references item 0, item 0 references item 1.

**Comment by SamuelNewhouse** [comment] 2019-12-21 14:48
Thanks Zylann. I created a new listItem derived from Object and it no longer crashes when stepping through the code.

**Comment by bojidar-bg** [comment] 2019-12-28 09:39
Duplicate of #1289.

**Closed by bojidar-bg** 2019-12-28 09:39 UTC
