### ISSUE TITLE
Animation Bezel editor is unusable without vertical zoom

### ISSUE THREAD

**Issue by PabloNeirotti** [godotengine/godot#30166] opened 2019-06-28 19:55 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
iMac (Retina 5K, 27-inch, 2017)
macOS Mojave (10.14.5)

**Issue description:**
It's impossible to use the bezel editor since the scale is gigantic for some cases.

For instance, I am trying to modify `self_modulate:r` to go from 5.0 to 1.0, but I can barely visualize the scale at all. Same is true for `self_modulate:a` which only goes from 0.0 to 1.0.

<img width="735" alt="Screen Shot 2019-06-28 at 12 47 44 PM" src="https://user-images.githubusercontent.com/905216/60367600-6ed9d780-99a3-11e9-832a-6b9149e9eb8d.png">

A vertical zoom would be nice, like other animation softwares like Apple Motion.

Plus: It'd be nice if the left column was adjustable because you can't actually tell apart one from another, since the captions are so small.

**Comment by KoBeWi** [comment] 2019-06-28 20:27
More detailed duplicate of #29997

**Closed by KoBeWi** 2019-06-28 20:27 UTC
