### ISSUE TITLE
Cannot reference other static function inside of static function without explicit namespace.

### ISSUE THREAD

**Issue by IAmNotIsaac** [godotengine/godot#82340] opened 2023-09-26 00:12 UTC
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.45004) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

### Issue description

In Godot 4, the ability to reference a function by name was introduced (first-class functions). A function cannot be modified in any at run-time, thus, it is constant and should work similarly to a constant in syntax.

### Steps to reproduce

```gdscript
class_name Example

const foo = 64

static func bar():
    pass

# Called on elsewhere via "Example.entry_point()"
static func entry_point():
    print(foo)          # Works as intended, outputs "64".
    print(Example.bar)  # Also works as intended, outputs: "GDScript::bar".
    print(bar)          # ERROR: "Invalid get index 'bar' (on base: 'Nil').".
```

It should be expected that `print(bar)` produces the same output as `print(Example.bar)`.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2024-03-21 12:46
* Duplicate of #86032.
* Fixed by #86088 for future 4.3.
* Cherry-picked for future 4.2.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-03-21 12:46 UTC
Labels: bug, topic:gdscript
