### ISSUE TITLE
Error returns when adding a number to an axis of a Vector3

### ISSUE THREAD

**Issue by Nuciloco** [godotengine/godot#51141] opened 2021-08-01 10:49 UTC
### Godot version

v4.0.dev.calinou [48857194b]

### System information

Windows 10, Vulkan, Nvidia GTX 750 Ti

### Issue description

The issue occurs when adding a number to one of the vector3's axis. From testing, this sees like it comes from a Vector3 variable being defined in the global scope of a script. The error that it reports is that Nil is being added to a Vector3 which it isn't at all.

### Steps to reproduce

Place the script down below on any Node and run the project.
```
extends Node

@export var gravity : float = 9.8
@export var delta : float = 0.0001
var velocity : Vector3 = Vector3(0, 0, 0)

func _ready():
	velocity.y += (gravity * delta)
	print(velocity.y)
```
This should cause the axis y to increase but instead it returns an error.

### Minimal reproduction project

[VectorIssue.zip](https://github.com/godotengine/godot/files/6912539/VectorIssue.zip)

**Comment by Calinou** [comment] 2021-08-01 14:18
Duplicate of https://github.com/godotengine/godot/issues/50283.

**Closed by Calinou** 2021-08-01 14:18 UTC
