### ISSUE TITLE
Collisions Issues when change scenes

### ISSUE THREAD

**Issue by AlexNight1986** [godotengine/godot#26241] opened 2019-02-24 16:06 UTC
**Godot version:**
3.1 beta 6

**OS/device including version:**
 Windows 7

**issue description:**
in a platform game when i change between scenes there are issues regarding collisions between player and platform

 **Steps to reproduce:**
using  "change_scene()" or PackedScene with "change_scene_to()" seems to trigger these issues.

it happens to me in Godot 3.1 since Beta 3

sorry for my english

**Comment by akien-mga** [comment] 2019-02-25 10:05
Could you provide a project that reproduces those issues?

**Comment by akien-mga** [comment] 2019-02-25 10:34
Seems like a duplicate of #24694 actually.
Please comment if you think it's not.

**Closed by akien-mga** 2019-02-25 10:34 UTC
Labels: bug, topic:physics

**Comment by AlexNight1986** [comment] 2019-02-26 22:32
yes i think the problem is very similar

> Seems like a duplicate of #24694 actually.
> Please comment if you think it's not.

yes i think the issue is very similar to this
