### ISSUE TITLE
Bottom Panel Errors due to SpriteFrames resource

### ISSUE THREAD

**Issue by Megamega53** [godotengine/godot#38599] opened 2020-05-09 20:00 UTC
**Godot version:**
3.2.1 stable-official
**OS/device including version:**
Windows 8.1
**Issue description:**
I've noticed a bug where if you add SpriteFrames to whatever node you're using, the bottom panel disappears when you switch to the Script workspace. And it doesn't reappear even when you select another node. The only way to bring back the bottom panel was to toggle the maximize button on your window. I've also noticed that if you don't switch to the Script workspace, but switch to a different node, the SpriteFrames resource will disappear from the node it was placed in. However, if you add a SpriteFrame to an AnimatedSprite node and select "New SpriteFrames" in the Frames category in the Inspector, the SpriteFrame resource will stay. However, the problem with the Bottom Panel will remain if you switch to the Script workspace.
**Steps to reproduce:**
1. Create two nodes and select one
2. Go to the Inspector and create a new Resource
3. Select SpriteFrames
4. Select the Script workspace and you will notice that the SpriteFrame's workspace will overtake the Bottom Panel.
5. Select another node and the node with the SpriteFrame resource will no longer have said resource.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-05-10 17:42
Duplicate of #16164.

**Closed by Calinou** 2020-05-10 17:42 UTC
