### ISSUE TITLE
HiDPI automatically used on FullHD screens, makes the UI too big

### ISSUE THREAD

**Issue by rosancoderian** [godotengine/godot#6096] opened 2016-08-10 06:31 UTC
**Operating system or device - Godot version:**
Deepin linux (Debian), Godot 2.1 64bit

**Issue description** (what happened, and what was expected):
gui is too big

**Steps to reproduce:**
run Godot_v2.1-stable_x11.64

**Link to minimal example project** (optional but very welcome):
![deepinscreenshot20160810132556](https://cloud.githubusercontent.com/assets/5107597/17543945/5d13b8f0-5efe-11e6-8536-4db5e8046d69.png)

**Comment by bojidar-bg** [comment] 2016-08-10 06:40
Seems related to our x11 hdpi detection, @Hinsbart

**Comment by habamax** [comment] 2016-08-10 08:53
Is 1920x1080 considered hiDPI?

In windows 10 ui is blurry. If I check on a godot binary "Disable display scaling on hiDPI settings" I get a bi smaller ui but crisp.

Then if in godot settings I set "hiDPI mode" to hiDPI -- I get HUGE UI which goes far right hiding panels off screen.

I am not sure if it is a bug or fullhd is considered non hiDPI.

**Comment by akien-mga** [comment] 2016-08-10 08:56
FullHD is not HiDPI no, and theoretically when using the auto-detect option, it should not enable HiDPI mode. The OP did not mention setting the hidpi mode manually, so I guess they're having a bug with the autodetect. If they chose hidpi manually, then it's not a bug, but a feature :)

**Comment by habamax** [comment] 2016-08-10 08:57
Ok, got it.

**Comment by czlowiekimadlo** [comment] 2016-08-11 13:53
Got same issue with Godot 2.1 stable on Lenovo Thinkpad X240 with full HD screen running Ubuntu 14.04.03 (LTS). Haven't set HiDPI, it was first time running any 2.1 build on this machine.

**Comment by reduz** [comment] 2016-08-11 14:06
It's set according to detected DPI size, but it clearly should also detect
screen resolution...

**Comment by akien-mga** [comment] 2016-08-11 14:16
1920x1080 on a 12.5" would make for ~175 dpi IINM, maybe it's over our threshold for high? Obviously since our solution for this is to double the size of everything, we should also take into account the screen resolution in pixels as @reduz mentions.

It might also be related to the missing xrandr API on Ubuntu 14.04 LTS that @Hinsbart had to workaround IIRC. @czlowiekimadlo's error message hints that we seem to try dlopen'ing the .so, which is bogus as .so files are contained in development packages (`libxrandr-dev` here) and are thus rarely installed on end users' machines. We'd have to dlopen the proper soname (maybe checking several possibilities as we can't know which version the users have).

**Comment by Hinsbart** [comment] 2016-08-11 14:41
@akien-mga Oh right, I didn't think of that. I'll see to it.

@czlowiekimadlo just to make sure, what's your reported dpi when calling `OS.get_screen_dpi()`?

**Comment by czlowiekimadlo** [comment] 2016-08-11 15:17
@Hinsbart I already left work for today, I will be able to provide this information tomorrow.

**Comment by romeojulietthotel** [comment] 2016-08-12 23:52
@akien-mga, .so is the standard shared object library extension.  Also libxrandr is required by many different packages on most linux distros. For example on arch linux look at the right hand column at the bottom: https://www.archlinux.org/packages/extra/x86_64/libxrandr/   It's an extension to X and is not a dev package, https://www.x.org/wiki/libraries/libxrandr/

**Comment by Hinsbart** [comment] 2016-08-13 00:10
@romeojulietthotel Yes, the Arch package actually also provides the .so, but most of the other major distributions don't. They have libXrandr.so.2 and provide the .so only via the developer package, as @akien-mga pointed  out.

See for example the contents of this package for [Ubuntu](http://packages.ubuntu.com/trusty/amd64/libxrandr2/filelist).
Also helpful might be the Wikipedia entry for [soname](https://en.wikipedia.org/wiki/Soname).

**Comment by akien-mga** [comment] 2016-08-15 07:32
Indeed, Arch is the exception, not the rule :)

**Comment by czlowiekimadlo** [comment] 2016-08-16 08:32
@Hinsbart reported DPI is 176

**Comment by czlowiekimadlo** [comment] 2016-08-16 13:52
https://github.com/godotengine/godot/blob/a22d1f21e1063b661f2fc103ebd2b48f4056d42f/tools/editor/project_manager.cpp#L1188

Maybe this is our issue? :D

**Comment by akien-mga** [comment] 2016-08-16 13:57
Definitely, I think the threshold is way too low, it should likely be at least 200. (To be checked on some real life monitor sizes + resolutions to see what dpi would be there on retina / 2k / 4k screens).

**Comment by czlowiekimadlo** [comment] 2016-08-16 15:31
I think changing HiDPI settings to On/Off/Auto would be nice as well, but it might be something for a separate feature request.

**Comment by firefly2442** [comment] 2016-08-21 16:16
Just chiming in, had the same issue.  Ubuntu Linux, Godot stable 2.1 custom build, 1920x1080 and it defaulted to "Auto".  Had to change it to "LoDPI" and restart.

**Comment by ashak** [comment] 2016-08-25 12:55
Same thing as @firefly2442 but on Debian Stretch. Settings -> Editor Settings -> Global-> Hidpi mode changed to LoDPI, restarted Godot stable 2.1 and it looks ok.

Amusingly before doing that I was wondering why I saw the error about libXrandr.so missing, so I fired Godot up with strace. Initially it seems to find the actual shared library fine:
open("/usr/lib/x86_64-linux-gnu/libXrandr.so.2", O_RDONLY|O_CLOEXEC) = 3

But a short while later it then goes off and tries to find libXrandr.so in various other locations and seems to fail?!
open("/lib/x86_64-linux-gnu/tls/x86_64/libXrandr.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/tls/x86_64", 0x7fff40034e90) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/tls/libXrandr.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/tls", 0x7fff40034e90) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/x86_64/libXrandr.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/x86_64", 0x7fff40034e90) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libXrandr.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
 etc.

**Comment by Hinsbart** [comment] 2016-08-25 13:03
@ashak see a few comments above. You probably don't have the development package for libXrandr installed, that's why it can find the *.so.2 but no the *.so. Will be fixed by #6116, although that won't fix the automatic enabling of HiDPI on FullHD monitors.

**Comment by cjthomp** [comment] 2016-09-17 18:11
FWIW, on OS X 10.11.6 running 4k monitors, godot started with the interface scaled up far too much (ends of labels were clipped off, file menu layouts were broken, editor font was HUGE). Had to change it from `Auto` to `LoDPI` manually for it to be usable.

**Comment by vnen** [comment] 2016-09-17 18:22
@cjthomp in Git master there's already a MidDPI option which might be better. I'm not sure if the detection was changed though.

**Comment by reduz** [comment] 2016-09-18 10:46
detection was improved in master, so feel free to test that too

**Comment by srcnalt** [comment] 2016-11-20 01:35
I have the very same issue on Solus 1.2.1, 1920*1080 screen size.

**Comment by akien-mga** [comment] 2016-11-20 08:15
@srcnalt What monitor size (in inches) and what Godot version?

**Comment by srcnalt** [comment] 2016-11-20 13:24
Hello @akien-mga! It is v2.1.stable.custom_build on Linux Solus, my screen size is 15 inch diagonal. I solved it switching Hidpi mode to Lowpi. But still first launch detects the screen as Hidpi.

**Comment by akien-mga** [comment] 2017-03-22 17:21
Here's a bad review that shows that this issue can really hit hard: http://steamcommunity.com/id/arcticturtle/recommended/404790/

I see two ways to fix the issue:
- Quick fix: increase the threshold for "hidpi" which is apparently too low in some configurations - that means that in other configurations where people might have had use for the hidpi mode, it wouldn't be used. But it's better that people have to manually set the hidpi mode if it wasn't recognized properly than having a huge editor where it's hard to access the settings.
- Better fix: Remove the "auto" mode. When the editor starts the first time, detect whether it should be hidpi or not and use that. Then show a popup dialog asking the user whether the DPI mode was properly recognized, with the possibility to accept the proposed mode (hidpi_mode set to whatever was detected) or refuse (hidpi_mode set to the other value, would ask for a restart to take effect).

**Comment by akien-mga** [comment] 2017-03-22 17:22
Also, it would be nice to include a fix for the upcoming 2.1.3 if someone is willing to work on it ASAP.

**Comment by akien-mga** [comment] 2017-03-24 17:52
Fixed by a531051 for 2.1, and was already fixed in master by bfe67a3 (and improved with c103f32).

**Comment by akien-mga** [comment] 2017-03-24 17:52
The "better fix" I suggested above should be further discussed in #8134.

**Closed by akien-mga** 2017-03-24 17:52 UTC
Labels: bug, platform:linux, topic:editor, usability

**Comment by dos1** [comment] 2017-09-04 13:53
The "better fix" would be to scale everything fluidly by reported DPI and not just by some artifically selected two modes. The 2000px width check is plain wrong - I've been using hidpi screens on some devices capable of running Godot with full HD or even lower resolution.

**Comment by Calinou** [comment] 2017-09-04 17:45
> The "better fix" would be to scale everything fluidly by reported DPI and not just by some artificially selected two modes.

Godot does not currently support arbitrary DPI scaling, but now that the icons and parts of the GUI theme are vector-based, it should be possible to add support for any floating-point scaling value.

**Comment by agentzz9** [comment] 2018-01-04 17:26
![image](https://user-images.githubusercontent.com/13109230/34575756-e223dbce-f1a1-11e7-9d9a-b5fbe6c6f024.png)
 
I am facing this sizing up on x64 2.1.4Stable on windows(10).
Cannot seem to get it normal. I guessed I messed up some preferences. But cannot seem to identify which. Also cannot access the _clipped_ portions of the IDE on right & bottom.
Problem on any project (also on project explorer starter page)

**Comment by Calinou** [comment] 2018-01-04 23:55
@agentzz9 You can edit `editor_settings.tres` which is located in `%APPDATA\Godot`, set `interface/editor/hidpi_mode` to `1` to force loDPI.

**Comment by carlsmith** [comment] 2018-08-17 00:02
MacBook Air 13 (1440x900) - same issue.

Changing the setting (`Editor > Editor Settings > Interface > Editor > Hidpi Mode`) didn't make any difference until Godot was restarted manually, but it worked fine after that.

The `LoDPI` setting works well. The `MidDPI` setting works, but still looks a bit oversized.
