### ISSUE TITLE
Control-Tab shortcuts

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#22853] opened 2018-10-08 15:04 UTC
**Godot version:**

v3.1.alpha.custom_build.0063ba9

**OS/device including version:**

macOS Mojave, 10.14 SDK

**Issue description:**

Shortcuts with Control-Tab do not register, including other combos like Control-Shift-Tab and Control-Alt-Tab. I remember seeing this in the 3.0 line as well.

![3152ec5b-d041-43ba-a329-6a3507202fd2](https://user-images.githubusercontent.com/38134085/46616804-f4012180-cae0-11e8-9f72-1fa07d1dd745.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-10-17 06:28
Indeed, duplicate of #8799.

**Closed by akien-mga** 2018-10-17 06:28 UTC
