### ISSUE TITLE
AStar not finding shortest path

### ISSUE THREAD

**Issue by Abbix13** [godotengine/godot#33304] opened 2019-11-03 20:25 UTC
**Godot version: 3.1.1**

**OS/device including version: Windows10**

**Issue description: AStar is not selecting the shortest path to a point/cell**

Here's a gif showing the odd behaviour:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53912415/68091469-d37bd600-fe5e-11e9-81e7-34d5cf096c67.gif)

**Steps to reproduce: I am using a slightly altered version of the AStar grid tutorial script. This time to work on an isometric grid, here's the code:

```
extends TileMap

onready var astar_node = AStar.new()

export(Vector2) var map_size = Vector2(5, 5)

var path_start_position = Vector2() setget _set_path_start_position
var path_end_position = Vector2() setget _set_path_end_position

var _point_path = []
onready var obstacles #get_used_cells_by_id(0)

const BASE_LINE_WIDTH = 3.0
const DRAW_COLOR = Color('#fff')

onready var _half_cell_size = cell_size / 2


func _ready():
	var walkable_cells_list = astar_add_walkable_cells()
	astar_connect_walkable_cells(walkable_cells_list)

func astar_add_walkable_cells():
	var cells_array = []
	for cell in get_used_cells():
		cells_array.append(cell)
		
		var point_index = calculate_point_index(cell)
		
		if(cell.x == 0 && cell.y == 0):
			astar_node.add_point(point_index, Vector3(cell.x, cell.y, 0.0), 1)
			continue
		astar_node.add_point(point_index, Vector3(cell.x, cell.y, 0.0), cell.x+cell.y)
	return cells_array

func astar_connect_walkable_cells(points_array):
	var open = []
	for point in points_array:
		var point_index = calculate_point_index(point)
		var points_relative = PoolVector2Array([
			Vector2(point.x + 1, point.y),
			Vector2(point.x - 1, point.y),
			Vector2(point.x, point.y + 1),
			Vector2(point.x, point.y - 1)])
		for point_relative in points_relative:
			var point_relative_index = calculate_point_index(point_relative)

			if is_outside_map_bounds(point_relative):
				continue
			if not astar_node.has_point(point_relative_index):
				continue
			astar_node.connect_points(point_index, point_relative_index, false)

func set_weight(current_point, target_point):
	var dx = target_point.x - current_point.x
	var dy = target_point.y - current_point.x
	return sqrt((dx*dx) + (dy*dy))

func is_outside_map_bounds(point):
	return point.x < 0 or point.y < 0 or point.x >= map_size.x or point.y >= map_size.y


func calculate_point_index(point):
	return point.x + map_size.x * point.y


func _get_path(world_start, world_end):
	_set_path_start_position(world_to_map(world_start))
	_set_path_end_position(world_to_map(world_end))
	var path_world = []

	for point in _point_path:
		print(point)
		var point_world = map_to_world(Vector2(point.x, point.y)) + _half_cell_size
		path_world.append(point_world)
	
	return path_world


func _recalculate_path():
	var start_point_index = calculate_point_index(path_start_position)
	var end_point_index = calculate_point_index(path_end_position)

	_point_path = astar_node.get_point_path(start_point_index, end_point_index)



func _set_path_start_position(value):
	#if value in obstacles:
	#	return
	if is_outside_map_bounds(value):
		return
	path_start_position = value
	if path_end_position and path_end_position != path_start_position:
		_recalculate_path()


func _set_path_end_position(value):
	if is_outside_map_bounds(value):
		return
	path_end_position = value
	if path_start_position != value:
		_recalculate_path()
```
**

ps: PLEASE ANSWER QUICKLY THIS IS FOR A COLLEGE PROJECT

**Comment by KoBeWi** [comment] 2019-11-03 20:44
Reproduction project would make testing this faster.

**Comment by Abbix13** [comment] 2019-11-03 21:48
> Reproduction project would make testing this faster.

Actually I didn't quite understand what a Reproduction Project might be. Is it how my project has been settup, such as scenes, nodes and other scripts linked to them?
If so here's a screenshot of the scene i'm using, as well as the script attached to "Personagem", which is also a slightly addapted version of the one in the AStar tutorial:
![image](https://user-images.githubusercontent.com/53912415/68092464-2c9d3700-fe6a-11e9-8144-5939df29333b.png)

```
extends Position2D

export(float) var SPEED = 200.0

enum STATES { IDLE, FOLLOW }
var _state = null

var path = []
var target_point_world = Vector2()
var target_position = Vector2()
var velocity = Vector2()

func _ready():
	_change_state(STATES.IDLE)


func _change_state(new_state):
	if new_state == STATES.FOLLOW:
		path = get_parent().get_node('TileMap')._get_path(position, target_position)
		if not path or len(path) == 1:
			_change_state(STATES.IDLE)
			return
		# The index 0 is the starting cell
		# we don't want the character to move back to it in this example
		target_point_world = path[1]
	_state = new_state


func _process(_delta):
	if not _state == STATES.FOLLOW:
		return
	var arrived_to_next_point = move_to(target_point_world)
	if arrived_to_next_point:
		path.remove(0)
		if len(path) == 0:
			_change_state(STATES.IDLE)
			return
		target_point_world = path[0]


func move_to(world_position):
	var MASS = 10.0
	var ARRIVE_DISTANCE = 10.0
	var desired_velocity = (world_position - position).normalized() * SPEED
	var steering = desired_velocity - velocity
	velocity += steering / MASS
	position += velocity * get_process_delta_time()
	return position.distance_to(world_position) < ARRIVE_DISTANCE


func _input(event):
	if event.is_action_pressed('click'):
		if Input.is_key_pressed(KEY_SHIFT):
			global_position = get_global_mouse_position()
		else:
			target_position = get_global_mouse_position()
		_change_state(STATES.FOLLOW)
```
The script attached to the Tutorial node is just to move the camera around with the arrow buttons, it is not related to the pathfinding

**Comment by KoBeWi** [comment] 2019-11-03 21:53
> Actually I didn't quite understand what a Reproduction Project might be. Is it how my project has been setup, such as scenes, nodes and other scripts linked to them?

No, it's a zip with Godot project that you can just open, run and see the issue. It doesn't need to be your main project, but some minimal one that reproduces the issue. (btw, you can attach zips here by dropping them into the text field)

**Comment by bojidar-bg** [comment] 2019-11-03 21:54
Why are you doing `astar_node.add_point(point_index, Vector3(cell.x, cell.y, 0.0), cell.x+cell.y)`? Setting the weights like this might cause the seemingly-suboptimal path to be actually an optimal path. If you replace `cell.x + cell.y` with just `1` it should result in a straight line.
Note that if `cell.x + cell.y` happens to be negative, astar cannot guarantee optimal results (actually, the optimal result would be a path which circles into itself, due to the negative-cost cycle).

**Comment by Abbix13** [comment] 2019-11-03 21:57
> Why are you doing `astar_node.add_point(point_index, Vector3(cell.x, cell.y, 0.0), cell.x+cell.y)`? Setting the weights like this might cause the seemingly-suboptimal path to be actually an optimal path. If you replace `cell.x + cell.y` with just `1` it should result in a straight line.
> Note that if `cell.x + cell.y` happens to be negative, astar cannot guarantee optimal results (actually, the optimal result would be a path which circles into itself, due to the negative-cost cycle).

I've added those after trying with a value of 1, to see if it would change anything.

**Comment by Abbix13** [comment] 2019-11-03 22:20
Here's the Reproduction Project:
[Reproduction.zip](https://github.com/godotengine/godot/files/3802216/Reproduction.zip)

**Comment by bojidar-bg** [comment] 2019-11-04 00:29
The compiled GDScript files will hardly help finding the issue.

Anyway, ensure that it is not the animation messing the movement up, as it seems to have some kind of memory of the last path.

**Comment by Abbix13** [comment] 2019-11-04 00:50
There is no animation set. Only the change in position caused by the movement.
As for compiled GDScript files. I don't know what you mean. I used the "export" option in the "Project" menu and selected Export PKC/Zip.
Forgive my ignorance on this. I'm fairly new to the engine itself and to creating games via engines. My last college project was in libgdx...

**Comment by WizzardMaker** [comment] 2019-11-04 16:35
You just zip the project folder where all of your assets and scripts are. Its the folder with the project.godot file.

**Comment by Abbix13** [comment] 2019-11-05 23:03
[Reproduction.zip](https://github.com/godotengine/godot/files/3811673/Reproduction.zip)
Here

**Comment by bojidar-bg** [comment] 2019-11-06 12:12
Debugging the project, seems like the problem is not with AStar.
In `Astar_godot.gd`:
```gdscript
func _set_path_start_position(value):
	#if value in obstacles:
	#	return
	if is_outside_map_bounds(value):
		print(value) # << Added by me
		return
```
Results in a position similar to `(5, 3)` being printed when testing to go from the top corner to the bottom corner to the left corner.
Then, the project proceeds to find a path from the previous start position to the new end position, thus creating a "suboptimal" path.

A bit earlier in that same script there is:
```gdscript
func _get_path(world_start, world_end):
	_set_path_start_position(world_to_map(world_start))
	_set_path_end_position(world_to_map(world_end))
	var path_world = []

	for point in _point_path:
		var point_world = map_to_world(Vector2(point.x, point.y)) + _half_cell_size
		path_world.append(point_world)
	
	return path_world
```

Notice the problem? Well, ignoring the fact that the character never ends in exactly the same position as provided by the path, this code actually shifts positions by `_half_cell_size` when giving them to the player, but does not remove this offset when converting the positions back into tile positions.

Suggested fix: Remove `_half_cell_size` from here, and potentially add it to the target point in the character script. Actually, it is much simpler to just offset the sprites and other things in the player node, instead of messing with offsets in code.

Here is a fixed project with the suggested fix above and with a bunch of added prints: [Reproduction-fixed.zip](https://github.com/godotengine/godot/files/3814309/Reproduction-fixed.zip)

Closing as I cannot confirm there being a bug in Godot using the reproduction project.

**Closed by bojidar-bg** 2019-11-06 12:12 UTC
