### ISSUE TITLE
GDScript: Nested (Inner) classes can't use script preloads from parent class.

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#38214] opened 2020-04-26 05:29 UTC
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
The following setup causes the error `The identifier "ImportedClass" isn't a valid type (not a script or class), or couldn't be found on base "self"`.

```
const ImportedClass = preload("res://class_to_import.gd");

func this_works() -> ImportedClass:
	return ImportedClass.new();

class Nested:
	func this_fails() -> ImportedClass:
		return ImportedClass.new();
	
	func this_also_fails(arg: ImportedClass) -> void:
		pass;
```

However, if you add `const ImportedClass = preload("res://class_to_import.gd");` to the nested class itself, then the errors go away.  I believe the type system of GDScript is failing to consider imported types from the parent class's scope.

**Steps to reproduce:**

1. Create a script that you intend to import later on.
2. Create another script containing a nested class.
3. Import the first script you created using a constant preload expression.
4. Create a function in the nested class and try to annotate that function as returning the imported script or taking an argument of the imported script's type.

**Minimal reproduction project:**
[NestedClassImportRepro.zip](https://github.com/godotengine/godot/files/4534673/NestedClassImportRepro.zip)

**Comment by hilfazer** [comment] 2020-04-26 09:59
It's that constants are, like variables, properties of an object, not a class. So a class shouldn't be able to access them.

**Comment by ThakeeNathees** [comment] 2020-04-27 10:16
related to #4472

**Comment by vnen** [comment] 2020-05-17 13:41
Duplicate of #37380

**Closed by vnen** 2020-05-17 13:41 UTC
