### ISSUE TITLE
The caret in `MeshLibrary`'s name field jumps back to the beginning of the field

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#63549] opened 2022-07-27 17:56 UTC
### Godot version

v4.0.alpha.custom_build [cc5135959]

### System information

Arch Linux

### Issue description

https://user-images.githubusercontent.com/36025825/181302677-de246a16-a7fa-4fc1-9969-9c3679580d93.mp4

### Steps to reproduce

1. In the FileSystem dock, create a new resource and select `MeshLibrary`
2. Double click it and switch to the 3D view
3. On the toolbar, select the "MeshLibrary" -> "Add Item"
4. In the Inspector expand the "Item" -> "0" and write something in the name field

**Comment by Calinou** [comment] 2022-07-27 18:05
I think this is an issue with all indexed properties (property arrays) in the inspector.

**Comment by KoBeWi** [comment] 2022-07-27 20:26
Pretty sure there was a similar issue already reported.
What happens is that when you type something, the inspector gets refreshed, because it receives property list changed notification.

**Comment by AntonioDell** [comment] 2022-07-29 11:29
Hi @MmAaXx500, can you please add an MRP or text how to reproduce the error? 
I tried reproducing it based on your video, but could not find a way to get the view you have recorded (I am not that familiar with the editor and the codebase yet). If anyone else knows how to reproduce this I'll be happy to look into it :)

**Comment by MmAaXx500** [comment] 2022-07-29 11:47
@AntonioDell I have added the steps to the OP. I don't think an MRP helps here in any way, because it's not project/setup specific, but if you think otherwise I can add one.

**Comment by AntonioDell** [comment] 2022-07-29 13:22
Hi @MmAaXx500, thank you for taking the time to update the post! Sadly following your instructions I can't seem to find the Item array. Can you reproduce the error from the current alpha branch?
Attached you find a screencast where I tried reproducing the view based on the description and failed. Maybe an MRP will help here after all? I wasn't able to build the alpha version you mentioned in the OP, the build on that  commit fails with an error. So maybe this is a new bug introduced in the current master  branch?

[Screencast from 07-29-2022 03:18:34 PM.webm](https://user-images.githubusercontent.com/29783330/181769268-54853706-7c42-4319-8342-d25dea9842d1.webm)

**Comment by AntonioDell** [comment] 2022-07-29 14:07
> @AntonioDell I recorded the whole process. I'm using [cd24fb8](https://github.com/godotengine/godot/commit/cd24fb848e5727ebc7ccbcd0fc94112c6baed4f2) on the video
> MeshLib-name-repro.mp4

That was the missing link, thank you! I will look into it :)

**Comment by akien-mga** [comment] 2023-01-21 10:38
Fixed by #63667.

**Closed by akien-mga** 2023-01-21 10:38 UTC
Labels: bug, topic:editor, regression
