### ISSUE TITLE
Broken visibility buttons in scene tree

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34470] opened 2019-12-19 19:28 UTC
**Godot version:**
3.2.beta.custom_build. 981c6aa10
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
Try to  click some times at visibility button and drag it.
It can also require right mouse button clicks
![jfile](https://user-images.githubusercontent.com/41945903/71203292-027ac980-229e-11ea-9df1-f59c305e99a6.gif)
![jfile](https://user-images.githubusercontent.com/41945903/71203341-14f50300-229e-11ea-8ace-7e36bd63105b.gif)

**Comment by timothyqiu** [comment] 2019-12-20 05:59
I found a minimal method to reproduce this:

1. Select the current node
2. Drag from its visibility icon
3. Drop it on the parent node (so a reparent operation is actually triggered)

I think #34319 might prevent this from happening. But the reason why the icon doesn't change after that needs further investigation.

**Comment by KoBeWi** [comment] 2020-11-11 23:26
Seems fixed in 3.2.3 (probably by the mentioned PR)

**Closed by KoBeWi** 2020-11-11 23:26 UTC
Labels: bug, topic:editor
