### ISSUE TITLE
Control Default Cursor Shape has no effect in a SubViewport

### ISSUE THREAD

**Issue by ejektaflex** [godotengine/godot#74805] opened 2023-03-12 06:04 UTC
### Godot version

4.0

### System information

Windows 11

### Issue description

When using a SubViewport contained within a SubviewportContainer, none of my child Control nodes within the Subviewport have their mouse cursors changed to align with their Control's default mouse cursor option. They are always unchanged, even when an attempt is made to change the default with code. It seems like being within a SubViewport disables it's ability to know when it needs to change mouse cursors inside that SubViewport.

### Steps to reproduce

* Create a Control node root.
* Put a SubViewportContainer inside it
* Put a SubViewport inside of that
* Put a ColorRect inside of the SubViewport and change it's default cursor to something else, such as "Forbidden"
* Hit "Play" and mouse over the ColorRect.

### Minimal reproduction project

[TestRepro.zip](https://github.com/godotengine/godot/files/10950080/TestRepro.zip)

**Comment by Calinou** [comment] 2023-03-21 18:51
cc @Sauermann

**Comment by kumikumi** [comment] 2023-05-26 03:37
I'm affected by this issue. More specifically, when moving the mouse, the cursor flickers between the proper cursor for the child node, and the default cursor for the SubViewportContainer (but the SubViewportContainer default cursor overrides it and gets shown most of the time).

@Sauermann did you get feedback for your idea? Is there a workaround while we wait for the fix?

**Comment by Sauermann** [comment] 2023-05-26 08:24
> did you get feedback for your idea?

Nobody did answer in this thread, so: no.

After looking at the problem again, maybe my previous idea is not the best possible way to deal with this situation.

In the following code-section, `Control::CURSOR_ARROW` is used for two different intentions:
- indicator for the default mouse cursor
- indicator that the control has no cursor set

If a separate mouse cursor enum value was available for the second one, then it could be used for SubViewportContainer to indicate that the Control should not set a mouse cursor. But this would still not be enough to solve the problem completely, because there might be a parent Control behind the SubViewportContainer, which could interfere with the cursor shape.

https://github.com/godotengine/godot/blob/2eec9a67d564b11326f44c5ef8b6b6f9aec251b9/scene/main/viewport.cpp#L1956-L1978

I might get back to this after #67791, which changes the way, how the Control is calculated above which the mouse cursor is. That new algorithm identifies the Control (event within nested SubViewports and embedded Windows) where the cursor is and this would provide a different, more natural solution for this issue.

**Comment by Insane-Owl** [comment] 2023-07-19 18:16
This is still an Issue in Godot 4.1.1 stable

**Comment by Koyper** [comment] 2023-07-22 12:59
How about creating a new internal signal emitted by `SubViewport` whenever the cursor shape is set, and `SubViewportContainer` connects to this new subviewport signal at runtime, and sets its `mouse_default_cursor_shape` in accordance with the signal?

**Comment by kumikumi** [comment] 2023-07-22 14:20
The problem is that SubViewportContainer's "mouse_default_cursor_shape" property is needlessly overriding the proper cursor that is already set by whatever is rendered in the viewport.

I did this as an experiment:

In my SubViewportContainer, set mouse_default_cursor_shape to "Can Drop" (arbitrarily selected a cursor that I don't need right now)

Then in Godot's `scene/main/viewport.cpp` add this check around the part that sets the cursor at line 2077 in Godot 4.1:

```
if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_CURSOR_SHAPE)) {
	if (ds_cursor_shape != DisplayServer::CURSOR_CAN_DROP) {
		DisplayServer::get_singleton()->cursor_set_shape(ds_cursor_shape);
	}
}
```
Lo and behold, the cursors inside the viewport work now, as they are not being overridden.

The proper fix would involve either allowing us to set a "null" value for the cursor shape, or changing the code in a way that SubViewportContainer's own cursor setting is discarded so that the cursor set by the viewport contents stays in effect.

**Comment by Sauermann** [comment] 2023-07-22 14:32
#67791 rewrites the methodology, how the Control is determined, which is under the mouse cursor.
My current estimation is, that with these changes it becomes much easier to correctly set the Mouse cursor shape based on Controls within a SubViewport.

**Comment by Koyper** [comment] 2023-07-22 16:06
> Lo and behold, the cursors inside the viewport work now, as they are not being overridden.

Thanks for figuring out a workaround - I might try this out until a fix happens after [#67791](https://github.com/godotengine/godot/pull/67791) is merged.

@Sauermann Purely out of curiosity, is the original reason `SubViewportContainer` is setting the cursor shape, coming from the way the 3.x `Viewport` always intercepts gui input regardless of location in the tree?

**Comment by Sauermann** [comment] 2023-07-22 16:15
@Koyper I'm not as familiar with the 3.x-codebase, so I can't really make the comparison.

My understanding of the current implementation is, that first the SubViewport evaluates the CursorShape and sets it.
Afterwards the root Viewport evaluates the CursorShape and sets it.
So it is a problem of the sequence in which the CursorShape is set.
With  #67791 it becomes trivial to identify the node that the cursor is over (even within nested SubViewports), so my idea is to set the CursorShape only once and not for for each Viewport separately.

**Comment by kumikumi** [comment] 2023-07-23 01:03
> With #67791 it becomes trivial to identify the node that the cursor is over (even within nested SubViewports), so my idea is to set the CursorShape only once and not for for each Viewport separately.

I made a one-line fix that just skips setting the cursor for SubViewports, I opened it as a PR at #79805

I made a repro with nested SubViewports here that is also fixed by the PR: [nested-subviewports-demo.zip](https://github.com/godotengine/godot/files/12137447/nested-subviewports-demo.zip)

I understand that this may be made obsolete by your effort, but I decided to post it anyway on the off chance that it helps. At least it demonstrates a possible simple way to fix it.

**Closed** 2023-07-26 16:48 UTC
Labels: bug, topic:gui

**Comment by jonSP12** [comment] 2024-08-23 14:37
In the editor a diferent cursor shape gets stuck instead of the arrow ?


https://github.com/user-attachments/assets/e908ee88-4ab5-4793-ace3-8f68b8258a62


- Changing the cursor shape in script doesnt seem to work....
- The only way i found how to change it is to add another control node at the end of the tree. 
- But then those things can't be selected inside the subViewPortContainer.
