### ISSUE TITLE
Mixamo fbx import issue

### ISSUE THREAD

**Issue by duasun** [godotengine/godot#59071] opened 2022-03-12 16:53 UTC
### Godot version

4.0 alpha 4, also alpha 3

### System information

Win 10, gtx 1660 Super

### Issue description

When importing model downloaded from mixamo in fbx format, weird mesh appears. 
![Screenshot (72)](https://user-images.githubusercontent.com/39042523/158026934-f6f719db-a4b5-47c8-8ccb-0abc432aa0db.png)
![Screenshot (73)](https://user-images.githubusercontent.com/39042523/158027007-f4fae837-e31f-4120-b49c-91d5fb2ac222.png)
![Screenshot (74)](https://user-images.githubusercontent.com/39042523/158027016-3208d1d9-b6ce-42d0-9232-dbd218af32ab.png)

### Steps to reproduce

Drag and drop fbx file into scene. Or open inherited new scene.

**Comment by Calinou** [comment] 2022-03-12 16:55
Duplicate of https://github.com/godotengine/godot/issues/43218.

**Closed by Calinou** 2022-03-12 16:55 UTC
