### ISSUE TITLE
Bullet: Falling cube unexpectedly spins on colliding with floor

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#15770] opened 2018-01-16 06:53 UTC
**Godot version:**
3.0 RC1

**Steps to reproduce:**
[Bullet vs Godot physics.flv.zip](https://github.com/godotengine/godot/files/1633889/Bullet.vs.Godot.physics.flv.zip)

**Minimal reproduction project:**
[Test Bullet.zip](https://github.com/godotengine/godot/files/1633884/Test.Bullet.zip)

**Comment by groud** [comment] 2018-01-16 07:10
Because of this : https://youtu.be/NYLQSaMXHmg

**Comment by AndreaCatania** [comment] 2018-01-16 07:43
With Bullet we resolved a lot of bugs the godot physics engine had, for free (except for all job I did).
With Bullet we can support other new things like SoftBody, Explosions, we could implement a better LOD, etc...
With Bullet we have the physics engine optimized for ragdolls and other scenarios.
With Bullet we have joints working correctly.
With Bullet we have a physics engine always updated for free.

Also I don't understand your video, with bullet you get a different behavior, but what's wrong?

**Comment by Noshyaar** [comment] 2018-01-16 07:52
I'm not sure why we have "Issue description:" field anymore.

**Comment by DimaKiva** [comment] 2018-01-16 08:04
> Also I don't understand your video, with bullet you get a different behavior, but what's wrong?

In Bullet just a cube falls on the plane and begins to dance. In Godot physics it falls more correctly.

**Comment by groud** [comment] 2018-01-16 08:12
It's true that the behavior is a little bit unexpected with bullet. It look like the cube is bouncing while the bounce value is 0.

**Comment by brodiefairhall** [comment] 2018-01-16 08:25
I'm fine with Bullet, It's different to the Alpha Physics, it worked fine in Beta 2, but now my solid bodies are just falling through static bodies in RC1, like collision is now nonexistent?

**Comment by AndreaCatania** [comment] 2018-01-16 08:34
@groud if you check the video more closely you can see that the body penetrate a bit the collision plane and when the depenetration happen the body rotate a bit.

@DimaKiva if you change the static collision with any other collision shape type it doesn't happen anymore, let me know about it.

@brodiefairhall Please open an issue with a proper sample project so I can check it, and remember to mention me so I can't miss it

**Comment by Zireael07** [comment] 2018-01-16 08:35
@brodiefairhall Check out #15747 just in case?

**Comment by brodiefairhall** [comment] 2018-01-16 08:44
@Zireael07 That is exactly what I seem to have encountered. Thanks!

**Comment by groud** [comment] 2018-01-16 09:18
> @groud if you check the video more closely you can see that the body penetrate a bit the collision plane and when the depenetration happen the body rotate a bit.

Well, yes. In any case, it's still a little bit an unexpected behaviour.

**Comment by reduz** [comment] 2018-01-16 10:10
I may dedicate more time eventually and fix the Godot built-in physics
engine, but having Bullet support in the meantime helps for having some
features we can't do otherwise

**Comment by groud** [comment] 2018-01-16 10:16
@DimaKiva Can you try with an AABB collision shape for the ground ?

And please next time, fill in the issue template correctly. If you want a problem to be solved it's a minimum, and not doing so is disrespectful for people that spend their time working on the engine. I almost closed the issue without any more consideration.

**Comment by DimaKiva** [comment] 2018-01-16 10:35
> AABB

If I understand correctly. If Plane change to cube, everything is fine, no problems.

**Comment by AndreaCatania** [comment] 2018-01-16 10:37
check this: https://github.com/godotengine/godot/issues/14750#issuecomment-357895879

> The plane shape collision is mean to be infinite and is not possible have finite plane shape. It's useful when you want to have floor at the end of the world in order to stop falling bodies at certain height, it's not meant to be used to be part of a scene.
>
> If you need just a plane you can generate a trimesh convex shape, in this case the shape will have the exactly same size of visible mesh.
>
> So this is not a bug and can be closed.

**Comment by groud** [comment] 2018-01-16 12:52
I asked about this behaviour in https://github.com/bulletphysics/bullet3/issues/1514
So this is not really an issue, it is an expected behaviour apparently for performance reasons.

Anyway this is outside Godot's scope, and the problem can easily worked around using a simple concave polygon or a box collision. Thus I close the issue.

**Closed by groud** 2018-01-16 12:52 UTC
Labels: topic:physics
