### ISSUE TITLE
LineEdit on Android with Hacker's Keyboard ignores or behaves weird on arrow keys

### ISSUE THREAD

**Issue by Procyon3** [godotengine/godot#7872] opened 2017-02-22 10:41 UTC
**Operating system or device - Godot version:**
Godot 2.1.1. Running the application on Android with Hacker's Keyboard that has arrow keys.

**Issue description:**
Some Android keyboard apps have arrow keys, such as Hacker's Keyboard. LineEdit will ignore these keys. After pressing Left or Up, any future keys pressed, including Enter, but excluding Backspace, will repeat the last key pressed before the arrow key instead of doing what they normally do.

**Comment by kubecz3k** [comment] 2018-04-10 17:28
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Procyon3** [comment] 2018-04-11 14:26
The issue is still present.

Here is an example project. It also has the bug for RichTextLabel:
https://github.com/godotengine/godot/issues/7620

The project below can be exported to a phone that has the Hacker's Keyboard.
When opened, click on the LineEdit node in the top left and move the cursor with the cursor keys of the Hacker's Keyboard.
The cursor won't move.

[Bugtest LineEdit and RichTextLabel.zip](https://github.com/godotengine/godot/files/1899225/Bugtest.LineEdit.and.RichTextLabel.zip)

**Comment by Calinou** [comment] 2020-06-07 17:36
@Procyon3 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Procyon3** [comment] 2020-06-08 13:18
This bug is still present in Godot v3.2.2-beta4.

It is as I wrote on Apr 11 2018 for version 3.0.2: the Hacker Keyboard's arrow keys don't move the cursor. Nothing else happens after pressing an arrow key.

**Comment by MaaaxiKing** [comment] 2020-06-19 17:21
If you consider that this issue is so old, it should be fixed in the next version, right?

**Comment by Calinou** [comment] 2020-06-19 17:34
@MaaaxiKing That's not how it works :slightly_smiling_face: 

Someone needs to do the work to fix it. We don't know how difficult it is.

**Comment by madmiraal** [comment] 2022-07-12 17:18
I'm unable to reproduce this issue in 3.4.4. Arrow keys from the [Hacker's Keyboard](https://apkpure.com/hacker-s-keyboard/org.pocketworkstation.pckeyboard) work as expected:

![7872](https://user-images.githubusercontent.com/9253928/178553138-20e40db8-9e21-420f-82ce-e3635e3d41e7.gif)

**Comment by Calinou** [comment] 2022-07-12 17:44
Closing per @madmiraal's comment. Please comment if you can still reproduce this on 3.4.4 or later.

**Closed by Calinou** 2022-07-12 17:44 UTC
Labels: bug, platform:android, topic:porting, confirmed, topic:input
