### ISSUE TITLE
KinematicCollision2D/3D does not allow setting of collider's properties

### ISSUE THREAD

**Issue by zacryol** [godotengine/godot#48027] opened 2021-04-19 19:48 UTC
[collision-bug-test.zip](https://github.com/godotengine/godot/files/6338624/collision-bug-test.zip)

**Godot version:** 3.2.3

**OS/device including version:** Solus Linux

**Issue description:** when attempting to set a property of a KinematicCollision[2D or 3D]'s `collider` property, you get an error like `"Invalid set index 'collider'"` even though that's not what you're setting.

**Steps to reproduce:** call a kinematic body's move_and_collide() method, saving the return value. If the collision is not null, attempt to set a property like `collision.collider.name = "Ball"` you get an error as if you were attempting to set the `collider` property itself

For now, a workaround is to save a reference `var collider = collision.collider` then set the properties of the local `collider` var.

**Minimal reproduction project:** Provided

**Comment by smix8** [comment] 2021-04-19 20:09
This GDScript issue is present with nearly all object properties rightnow. For the moment you can also work around this issue by using set() and get() methods instead of accessing object properties directly.

**Comment by madmiraal** [comment] 2021-04-20 11:21
Closing as duplicate of #41319.

**Closed by madmiraal** 2021-04-20 11:21 UTC
Labels: bug, topic:gdscript, topic:physics
