### ISSUE TITLE
GDScript 2.0: Game window crashes without run time error while using %

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#62992] opened 2022-07-13 21:29 UTC
### Godot version

4.0 alpha 11

### System information

Fedora 36

### Issue description

Using module operator with size of empty array crashes game window without any errors. Check below code

```gdscript
func _ready():
	var arr = Array()
	var b = 10 % arr.size()
	print("Will not get printed")
```
	

### Steps to reproduce

1. Run above code

**Comment by Calinou** [comment] 2022-07-13 21:38
This likely causes a division by zero, as modulo is a division remainder.

**Comment by cdemirer** [comment] 2022-07-14 18:26
#59556 related if not the same.

**Comment by Calinou** [comment] 2022-10-12 23:20
Duplicate of https://github.com/godotengine/godot/issues/59556.

**Closed by Calinou** 2022-10-12 23:20 UTC
Labels: bug, topic:gdscript, crash
