### ISSUE TITLE
`thread_model=2` causes Godot to exit with SIGSEGV when opening project.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#1290] opened 2015-01-21 18:48 UTC
This happens since 2ef5a342e34df3863ac512bb3673eba28f15e9f4.
Removing the line from `engine.cfg` makes opening the project possible again.
Setting the project setting `thread_model` back to multi-threaded (=`2`) causes the problem to return.
No error messages are displayed.

**Comment by Mikeb85** [comment] 2015-01-22 01:55
I've got this issue too.  When I'm running Godot from the terminal and try to open a project, it throws this error:

> ERROR: set_wait_time: time should be greater than zero.
   At: scene/main/timer.cpp:69.

If the project is thread_model=0, it still runs, if thread_model=2 it crashes without any additional error messages.

**Comment by FEDE0D** [comment] 2015-04-04 00:09
Same here. I don't get any errors except for
`attempt set state: (current:0)`

**Comment by akien-mga** [comment] 2015-11-18 09:40
Is this issue still valid in the current master branch / nightly builds?

**Comment by volzhs** [comment] 2015-11-18 10:32
I guess this is related to http://www.godotengine.org/work_packages/10.

**Comment by akien-mga** [comment] 2015-11-20 07:48
I just tried and can't reproduce it in the current master branch, so I'll assume it has been fixed already (even though threading support is likely not 100% perfect yet).

**Comment by volzhs** [comment] 2015-11-20 10:29
I think, it can not be reproduced because of this.
https://github.com/godotengine/godot/blob/master/main/main.cpp#L705-L710

**Comment by akien-mga** [comment] 2015-11-20 11:26
Thanks for checking it, I'll reopen the issue then as it's only worked around, Multi-Thread is likely still broken.

**Comment by akien-mga** [comment] 2016-01-21 09:38
As there's a workaroudn for now, I'll move it to a later milestone, it's not critical for the upcoming 2.0 release.

**Comment by akien-mga** [comment] 2016-07-15 08:21
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment] 2018-05-09 09:34
> I think, it can not be reproduced because of this.
https://github.com/godotengine/godot/blob/fe9f4ed/main/main.cpp#L705-L710

That hack was removed in 871c47a2. In the meantime the editor was forced to always use the thread safe render mode, so this issue should be fixed.

**Closed by akien-mga** 2018-05-09 09:34 UTC
Labels: bug, topic:core
