### ISSUE TITLE
Physic 2D lag on Mac

### ISSUE THREAD

**Issue by bbcbreno** [godotengine/godot#17859] opened 2018-03-30 04:59 UTC
**Godot version:**
Godot 3.0.2

**OS/device including version:**
MacOS 10.13.2
Radeon Pro 455 2 GB

**Issue description:**
Any object that's moved with physic lag every second and in the same time. I uploaded this video to show the problem:
https://www.dropbox.com/s/olylyeq1iq0k0nh/bug%20godot%20lag.mov

**Steps to reproduce:**
Create a new project with a RigidBody2D and run the project.

**More info:**
- This issue reflect to Android too. But the lag happens approximately every 3 seconds
- On Godot 2.1.5 works fine without lag.
- I cleaned the Godot in my Mac removing all files in Library/Application Support/Godot and the app
- I tried others Godot3 versions too
- I'm not sure, but I think I had not this problem before, I notice this last week (but I started with Godot this month)

**Comment by aron3097** [comment] 2018-03-30 05:04
In my case.
on pc and android, If turn `Vsync` on , it will lag.
on android , if use light2D, specially with shadow enable, it lag.

**Comment by Calinou** [comment] 2018-03-30 12:40
This looks similar to https://github.com/godotengine/godot/issues/2043.

**Comment by bbcbreno** [comment] 2018-03-30 21:30
@Calinou , yes, it's similar! But here works fine on Godot 2 and I don't think it's a GPU issue.

**Comment by bojidar-bg** [comment] 2018-03-31 06:36
@bbcbreno Likely jitter, see #15270.
Basically, it sometimes manages to squeeze two physics frames between two display frames, thus causing a perceived jump (body moving too quickly). Or, more often, it would draw twice before the next physics frame comes, thus causing a slight stall (a frame without movement).

**Comment by Calinou** [comment] 2020-06-07 17:03
Duplicate of #2043 and #15270.

**Closed by Calinou** 2020-06-07 17:03 UTC
Labels: bug, topic:physics
