### ISSUE TITLE
duplicate() don't copy variables values in Resources 

### ISSUE THREAD

**Issue by rsousacode** [godotengine/godot#37222] opened 2020-03-22 06:24 UTC
Last reproduced in Godot version: https://github.com/godotengine/godot/commit/da4eb7101d986af0ba6a15efaaed3dee77370d80

We use Godot C#, and we don't see a proper way to get a real duplication of the Resource like in Unity (`InventoryItem clone = UnityEngine.Object.Instantiate(this) as InventoryItem`). In the docs says that Resource are similar to Unity Scriptable Objects but they're not for most proper use cases. In our inventory system, our items can't have the stackable option (for example having a max of 10 items per slot - for the same item), because `this.Duplicate() as InventoryItem` _doesn't work properly_. (**assuming that this one is the equivalent of the refered Unity method**)

Edit: Maybe we assumed wrongly the actual bold text, since `duplicate` is used many times in the core of the engine, but the actual exposed thing can be misleading, and people can assume that does what the unity like func does.  

I previously thought that this was related to https://github.com/godotengine/godot/issues/3393, but then we realised that it was better to create another issue.

**Comment by Calinou** [comment] 2020-03-22 16:22
Please mention the Godot version you're using in issue description. Also, please upload a minimal reproduction project to make this easier to troubleshoot :slightly_smiling_face:

**Comment by bigmonte** [comment] 2020-03-22 17:52
This is very hard to reproduce in a minimal project. Unfortunately I don't have time to research it more. After my semester ends, I'll try to do. 

But at least I'll place here, what happens in my project:

(itemToAdd has the parameters OK)
![screen1](https://user-images.githubusercontent.com/34067397/77256381-c290fd00-6c65-11ea-9476-d47ab8382012.png)

(After adding it to the array, all parameter bacame null)

![screen2](https://user-images.githubusercontent.com/34067397/77256383-cae93800-6c65-11ea-862a-f2e9770c48ff.png)

**Comment by bigmonte** [comment] 2020-03-22 18:41
Unity Minimal Project: https://ufile.io/w0crj713
Godot Minimal Project: https://uploadfiles.io/jel6rfpw

**Comment by Anutrix** [comment] 2020-03-26 14:16
Does duplicate(deep=true) do what is intended?

**Comment by bigmonte** [comment] 2020-03-27 18:25
@Anutrix No. It was the first things I've tried.

**Comment by neikeq** [comment] 2020-04-02 18:35
Is this only failing for user created properties/fields or does the same apply to the native class properties?

**Comment by bigmonte** [comment] 2020-04-02 21:59
If by native class property you mean a thing something that is present in the original Resource class, I don't think it fails, i.e. https://github.com/godotengine/godot/issues/37222#issuecomment-602246934 in the first screenshot `_targetInventory` is assigned to `Inventory.Instance` (which is a C# Singleton). And that one never becames null, only the user ones. (But that was a way to force the Resource to get the one Inventory controller for debugging, since we want to discover the inventory by name, because we can have multiple ones) .

If you want I can open a proposal for adding this clone/duplicate functionality. Since I noticed some time after opening this that `duplicate` is used many times in godot source, and I don't think the usage should be 'confuded' as it happenned to me. 

Actually I had replaced `Duplicate` https://github.com/godotengine/godot/issues/37222#issuecomment-605199089 by `new InventoryItem()` right there, and works fine.

**Comment by MikeSchulze** [comment] 2020-08-04 19:59
i got same error on gdScript
```
extends Resource
class_name ClassA

var _foo = 10
````

```
const classA = preload("res://test/ClassA.gd")

func _ready():
	ready1()
	ready2()
	ready3()

func ready1():
	prints("preloaded class duplicate(true)")
	var original:ClassA = classA.new()
	
	var c1 = original.duplicate(true)
	prints( original, original._foo, " -> ", c1, c1._foo)
	
	original._foo = 22
	c1 = original.duplicate(true)
	prints( original, original._foo, " -> ", c1, c1._foo)	

	
func ready2():
	prints("class by name  duplicate(true)")
	var original:ClassA = ClassA.new()
	
	var c1 = original.duplicate(true)
	prints( original, original._foo, " -> ", c1, c1._foo)
	
	original._foo = 22
	c1 = original.duplicate(true)
	prints( original, original._foo, " -> ", c1, c1._foo)	


func ready3():
	prints("class by name  duplicate(false)")
	var original:ClassA = ClassA.new()
	
	var c1:ClassA = original.duplicate()
	prints( original, original._foo, " -> ", c1, c1._foo)
	
	original._foo = 22
	c1 = original.duplicate()
	prints( original, original._foo, " -> ", c1, c1._foo)	
```
output:
````
--- Debugging process started ---
Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 980/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
preloaded class duplicate(true)
[Resource:1196] 10  ->  [Resource:1197] 10
[Resource:1196] 22  ->  [Resource:1199] 10
class by name  duplicate(true)
[Resource:1201] 10  ->  [Resource:1202] 10
[Resource:1201] 22  ->  [Resource:1204] 10
class by name  duplicate(false)
[Resource:1206] 10  ->  [Resource:1207] 10
[Resource:1206] 22  ->  [Resource:1208] 10
````

**Comment by phaitonican** [comment] 2020-11-03 14:08
id love to have a duplicate() functions which also duplicates the internal variables, because I use a class as a Data Structure and once I duplicate it (with whatever paremeters, if true or 4), the variables stay on but all are empty. Its basicallly a preload().new() but duplicate should exactly duplicate that class.

Now I added own duplicate function for the data structure class like above, but this is just a temporary solution.

**Comment by cloewen8** [comment] 2021-05-23 05:09
Confirmed, the bug is still in Godot 3.3.

I have a particle resource with a color (purple by default). I set the color before adding it. The simulation function duplicates it before adding it. It should be the set color, but it remains purple.
Resource:
```py
var color = Color.purple
```
Adding code:
```py
var water = Fluid2DParticle.new()
water.color = Color.blue
fluids.fill_area(Rect2(start, size), water)
```
The fill_area function:
```py
func fill_area(area: Rect2, p: Fluid2DParticle):
	for x in range(area.position.x, area.end.x):
		for y in range(area.position.y, area.end.y):
			_add_point(Vector2(x, y), p.duplicate())
	update()
```

**Comment by MikeSchulze** [comment] 2021-05-23 12:00
You can use your own clone function as workaround, i use this solution.

```
func deep_clone(source :Object) :
	var clone = source.duplicate()
	# copy all property values
	for property in source.get_property_list():
		var property_name = property["name"]
		clone.set(property_name, source.get(property_name))
	
	if source is Node:
		# remove incomplete duplicated childs
		for child in clone.get_children():
			clone.remove_child(child)
			child.free()
		assert(clone.get_child_count() == 0)
		# clone childs
		for child in source.get_children():
			clone.add_child(deep_clone(child))
```

**Comment by Calinou** [comment] 2021-05-23 13:14
Duplicate of https://github.com/godotengine/godot/issues/3393.

**Closed by Calinou** 2021-05-23 13:14 UTC
Labels: bug, confirmed, topic:core
