### ISSUE TITLE
Can’t open Find… menu in Script Editor using keyboard shortcut

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#65616] opened 2022-09-10 12:58 UTC
### Godot version

v4.0.alpha.custom_build [8899f1eec]

### System information

Arch Linux (IDK how to give a version for this)

### Issue description

I can’t open the “Find…” menu in the Script Editor using a keyboard shortcut. Its shortcut is <kbd><kbd>Ctrl</kbd>+<kbd>F</kbd></kbd> by default, but I tried rebinding it to <kbd><kbd>Ctrl</kbd>+<kbd>.</kbd></kbd>, and it still doesn’t work. I can reliably open the “Find…” menu by going to Editor > Command Palette… though.

### Steps to reproduce

1. Open a script in the Script Editor.
2. Go to Editor > Editor Settings… > Shortcuts.
3. Make sure that “Find…” in the “Script Text Editor” section has a unique shortcut (for testing, I’ve been using <kbd><kbd>Ctrl</kbd>+<kbd>.</kbd></kbd>).
4. Close the Editor Settings window.
5. Try to activate the keyboard shortcut for “Find…”

### Minimal reproduction project

[find_script_editor_keyboard_shortcut.zip](https://github.com/godotengine/godot/files/9540390/find_script_editor_keyboard_shortcut.zip)

**Comment by KoBeWi** [comment] 2022-09-10 13:58
Duplicate of #65601
You can use F3 as a workaround.

**Closed by KoBeWi** 2022-09-10 13:58 UTC
