### ISSUE TITLE
KinematicCollision2D.position obtained from get_slide_collision(i) is not precise enough.

### ISSUE THREAD

**Issue by Iris-6** [godotengine/godot#27416] opened 2019-03-25 22:30 UTC
**Godot version:**
3.1 release

**OS/device including version:**
Windows 10, Intel i7

**Issue description:**
![diag](https://user-images.githubusercontent.com/48930896/54958414-e7209f00-4f55-11e9-81fa-9ea141cdffcb.png)

**Steps to reproduce:**
Obtain KinematicCollision2D.position from get_slide_collision(i).

**Comment by eon-s** [comment] 2019-03-25 23:24
Cannot reproduce this behavior, with RectangleShape at least.

See the dots where collision points were reported on the borders:
![collisionsreported](https://user-images.githubusercontent.com/10215987/54960483-8a17ef80-4f3b-11e9-8707-d72a0b8dfed8.png)

The problem I see is another, the collision is correctly reported when going to the right (the end point of the platform) but is the rightmost point of the collider when going to the left.
All this can be reproduced with vertical motion and diagonal too.

**Comment by eon-s** [comment] 2019-03-25 23:29
And tested with CollisionPolygon2D and got the opposite result, the correct collision to the left and the leftmost point on the right...

**Comment by Calinou** [comment] 2019-03-28 00:06
@Iris-6 Please attach a reproduction project, perhaps this issue is related to  project settings such as the stretch mode or 2D pixel snap.

**Comment by Iris-6** [comment] 2019-03-28 16:52
[BugTest.zip](https://github.com/godotengine/godot/files/3019222/BugTest.zip)
![badcollision](https://user-images.githubusercontent.com/48930896/55176855-3cd98f00-5182-11e9-9c99-3ac457e86e7a.png)

**Comment by Iris-6** [comment] 2019-04-04 18:19
Any news on this issue?

**Comment by eon-s** [comment] 2019-04-04 23:13
Physics bugs can take some time to fix, even if the solution sometimes is a couple of lines the problem can be hard to track.

As a low precision workaround you can use the usual raycasts, put 3 or more Raycast2D nodes pointing down on the body and check them when you want to see how much is in the air.

**Comment by securas** [comment] 2019-12-14 08:24
still a problem in 3.2 beta 3

**Comment by madmiraal** [comment] 2020-03-23 16:21
@Iris-6 The diagram you provided in the original issue [description](https://github.com/godotengine/godot/issues/27416#issue-425144485) is not what I see in your example project:
![27416Test](https://user-images.githubusercontent.com/9253928/77336592-a6ea2d00-6d1f-11ea-8f43-e1436e6e3a3d.png)
When the `KinematicBody2D` object is moved off the edge of the `StaticBody2D`, the collision point does not hang off the edge and is in the position you describe as expected.

What is perhaps unexpected is that the collision point is the right-most point and not the centre:
![27416Test2](https://user-images.githubusercontent.com/9253928/77336814-f892b780-6d1f-11ea-80a2-805c304aa63d.png)
The reason for this is that when the two surfaces are perfectly parallel, there two viable collision points: the left and the right and only one can be used. It makes no attempt to find the average. This can be verified by rotating the `KinematicBody2D` by only -1° to see the left side selected as the collision point:
![27416Test3](https://user-images.githubusercontent.com/9253928/77337380-b8800480-6d20-11ea-8c9f-60141a4a89df.png)
Note, it will correctly move the collision point when the `KinematicBody2D` moves off the left edge of the `StaticBody2D`:
![27416Test4](https://user-images.githubusercontent.com/9253928/77338131-d00bbd00-6d21-11ea-9bc0-3a0e781430b1.png)

@eon-s and @securas if you're describing a different problem, I would suggest opening a separate issue and providing a sample project to demonstrate it.

**Comment by madmiraal** [comment] 2020-06-28 11:38
Closing as resolved in 3.2.

**Closed by madmiraal** 2020-06-28 11:38 UTC
Labels: bug, confirmed, topic:physics
