### ISSUE TITLE
LightOccluder2D doesn't work when exporting to Android

### ISSUE THREAD

**Issue by theZadek** [godotengine/godot#32855] opened 2019-10-15 22:33 UTC
**Godot version:**
3.1.1, 3.2

**OS/device including version:**
Android 7.0, Phone used: MyPhone Hammer Energy

**Issue description:**
LightOccluder2D doesn't work when the project is exported to Android but works inside the editor or other exports.

issue:
![image](https://user-images.githubusercontent.com/48355246/66874682-3e4a9780-efac-11e9-9f36-a698b91550e9.png)

expected result:
![image](https://user-images.githubusercontent.com/48355246/66874631-12c7ad00-efac-11e9-89ff-c0a7adb74c3f.png)

**Steps to reproduce:**
Have Light2D interact with LightOccluder2D, it doesn't matter if you are using GLES2 or GLES3.

**Minimal reproduction project:**
[Godot Bug Report.zip](https://github.com/godotengine/godot/files/3731691/Godot.Bug.Report.zip)

**Comment by theZadek** [comment] 2019-10-16 17:26
oh and the error message:

```
E 0:00:03:0218   Condition ' status != 0x8CD5 ' is true. returned: RID()
  <C Source>     drivers/gles2/rasterizer_storage_gles2.cpp:4847 @ canvas_light_shadow_buffer_create()

```

**Comment by Calinou** [comment] 2019-10-16 17:57
Duplicate of #29208 (the error message is exactly the same).

**Closed by Calinou** 2019-10-16 17:57 UTC
