### ISSUE TITLE
is_on_floor() occasionally gives false positive when jumping through one-way platforms

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#30509] opened 2019-07-11 03:59 UTC
**Godot version:**
3.1

**OS/device:**
Windows 8.1, Toshiba Satellite

**Issue description:**
Occasionally, when jumping up through static one-way platforms, `KinematicBody2D's` `is_on_floor()` gives a false positive. If you're setting `vel = move_and_slide(vel, Vector2.UP)` in your movement code, this results in `vel.y` getting reset to 0, screwing up the player's trajectory.

I have noticed this using both `mode_and_slide()` and `move_and_slide_with_snap()`. I have confirmed it for one-way `CollisionShape2Ds` (with both rectangle shapes and polygon shapes), as well as `TileMaps` with one-way collision. I've confirmed it for `one_way_collision_margin` = 0 and 1.

It happens infrequently (maybe 1/50 times in my game), but frequently enough to be a big concern for me. You should be able to reproduce it in any platformer test project by jumping through one way platforms over and over, altering your trajectory.

The situation looks like the following. The green path is the expected trajectory. The orange path is the actual trajectory, caused by vel.y resetting when the engine falsely recognizes is_on_floor() = true.

![unknown](https://user-images.githubusercontent.com/29932982/61021166-2c29df00-a355-11e9-9d16-fcf050398f72.png)

**Steps to reproduce:**
1. Create a 2D platformer scene with a `KinematicBody2D` and `StaticBody2Ds` with one-way `CollisionShape2Ds` (use rect or polygon as the shape).
2. Jump around and across the one-way platforms over and over until you notice a false positive `is_on_floor()` resetting your vel.y = 0, making you start falling instantly.

**Minimal reproduction project:**
Forthcoming

**Comment by myhalibobo** [comment] 2019-07-12 01:40
[#25967](https://github.com/godotengine/godot/issues/25967) It seems to be the same problem as mine

**Comment by akien-mga** [comment] 2019-07-12 05:07
Closing as duplicate of #25967.

**Closed by akien-mga** 2019-07-12 05:07 UTC
Labels: bug, topic:physics
