### ISSUE TITLE
The editor crashes when clicking on a MenuButton while a pop-up is open

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#20451] opened 2018-07-25 15:28 UTC
**Godot version:** Git https://github.com/godotengine/godot/commit/9e16f4a3704b76b3b7c236e29a141b3c33263667

**OS/device including version:** Fedora 28

**Issue description:** Clicking on a MenuButton while a pop-up dialog is open will crash the editor. It is likely to be a regression from https://github.com/godotengine/godot/pull/19726.

![menubutton_editor_crash](https://user-images.githubusercontent.com/180032/43209956-37535d88-902e-11e8-9d27-d002afcc7734.png)

Backtrace:

```
[1] /lib64/libc.so.6(+0x37070) [0x7ffff5095070] (??:0)
[2] Ref<Texture>::ref(Ref<Texture> const&) (/home/hugo/Documents/Git/godotengine/godot/core/reference.h:70)
[3] Ref<Texture>::Ref(Ref<Texture> const&) (/home/hugo/Documents/Git/godotengine/godot/core/reference.h:197)
[4] Button::get_icon() const (/home/hugo/Documents/Git/godotengine/godot/scene/gui/button.cpp:211)
[5] Viewport::_gui_input_event(Ref<InputEvent>) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1871)
[6] Viewport::input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:2477 (discriminator 2))
[7] Viewport::_vp_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1220)
[8] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/hugo/Documents/Git/godotengine/godot/core/method_bind.gen.inc:729 (discriminator 12))
[9] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/hugo/Documents/Git/godotengine/godot/core/object.cpp:918 (discriminator 1))
[10] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object.cpp:843)
[11] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/scene_tree.cpp:262)
[12] SceneTree::input_event(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/scene_tree.cpp:418 (discriminator 6))
[13] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/hugo/Documents/Git/godotengine/godot/main/input_default.cpp:392)
[14] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/main/input_default.cpp:260)
[15] OS_X11::process_xevents() (/home/hugo/Documents/Git/godotengine/godot/platform/x11/os_x11.cpp:2026 (discriminator 3))
[16] OS_X11::run() (/home/hugo/Documents/Git/godotengine/godot/platform/x11/os_x11.cpp:2637)
[17] /home/hugo/Documents/Git/godotengine/godot/bin/godot.x11.tools.64(main+0xb5) [0x102a3eb] (/home/hugo/Documents/Git/godotengine/godot/platform/x11/godot_x11.cpp:56)
[18] /lib64/libc.so.6(__libc_start_main+0xeb) [0x7ffff508124b] (??:0)
[19] /home/hugo/Documents/Git/godotengine/godot/bin/godot.x11.tools.64(_start+0x2a) [0x102a27a] (??:?)
```

**Steps to reproduce:** Open the Project Settings or Editor Settings, then click on any of the editor's MenuButtons while a pop-up is open.

**Comment by johannesgunnar** [comment] 2018-07-25 15:33
This does not seem to happen in v3.0.5 under Ubuntu 18.04. Instead the pop up closes and main editor window gains focus as expected.

**Comment by volzhs** [comment] 2018-07-25 15:34
yes. it happens with latest master. I'm facing same issue.

**Comment by volzhs** [comment] 2018-07-25 15:39
it also happens sometimes when closing editor settings.

**Comment by Calinou** [comment] 2018-07-25 15:40
It's likely a regression from https://github.com/godotengine/godot/pull/19726.

**Comment by malbach** [comment] 2018-07-25 16:37
Hi,
Not happening here with master [f778bd8](https://github.com/godotengine/godot/commit/f778bd8e694cb9c93cc0e021418f2be362dcdd3c) (which includes #19726)
Windows 7 x64, compiled with MONO
It does exactly like @johannesgunnar explained above

**Comment by guilhermefelipecgs** [comment] 2018-07-27 17:10
This is a regression from 0e29f7974b59e4440cf02e1388fb9d8ab2b5c5fd.

**Comment by hpvb** [comment] 2018-07-27 17:50
I'll have a look to see if I made an error in the cow pr

**Comment by volzhs** [comment] 2018-07-27 17:57
@hpvb #20475 this one looks definitely related to the COW pr.
would you take a look?

**Comment by hpvb** [comment] 2018-07-28 01:11
I'm looking into it now, it seems that there are some codepaths that rely on the previous 'copy on read' behavior of Vector<T> to be safe in certain multi-threaded scenarios. Particularly things taking pointers too early, essentially bypassing CoW entirely.

It'll take a while to hunt all of these down and fix them I'll get going on it :)

**Comment by hpvb** [comment] 2018-07-28 01:46
While I'm not wrong this is a race condition the crash is present at 9423f23ffb80c946dec380f73f3f313ec44d0d18 which is one commit before the CoW fixes. :) I'll bisect some more but I think the problem is mousing over disabled icons. Probably the other crashes too. Still looking at the animation player.

**Comment by hpvb** [comment] 2018-07-28 01:57
This regression is caused by d1f5deabd8138fbfd56db2f850d96dca7b03cc8e or #19726

**Closed** 2018-07-29 02:20 UTC
Labels: bug, topic:editor
