### ISSUE TITLE
ENet not completely implemented

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#17964] opened 2018-04-04 11:04 UTC
[thirdparty/enet/godot.cpp](https://github.com/godotengine/godot/blob/master/thirdparty/enet/godot.cpp) is full of methods not yet implemented.

I think it would be better finish it before documenting properly godot's networking capabilities.

**Comment by akien-mga** [comment] 2018-04-04 11:08
It's just an interface between Godot sockets and ENet. Some of those methods might be unimplemented simply because we don't need them for Godot sockets (but ENet requires them of socket implementations).

CC @Faless

**Comment by Noshyaar** [comment] 2018-04-04 11:31
Related to #17798 ?

**Comment by mhilbrunner** [comment] 2018-04-04 16:51
Closing as duplicate of #17798.

**Closed by mhilbrunner** 2018-04-04 16:51 UTC
Labels: discussion, topic:network
