### ISSUE TITLE
Errors after setting custom theme in project settings

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#54752] opened 2021-11-08 06:58 UTC
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

I'm using a custom theme in my project. Instead of having to remember to manually set the custom theme override for each Control node in various scenes to be able to get an accurate preview, I've set the custom theme in the Project Settings.

![Godot 3 4 Bug Report - Project Settings Custom Theme](https://user-images.githubusercontent.com/227734/140696762-a381a6df-b11e-40aa-bea4-8232804547f5.png)

When I press F5 (or F6) to test the project/scene I get a bunch of errors related to loading the theme and custom images as the window launches.

```
E 0:00:00.724   _load_data: Condition "img.is_null() || img->empty()" is true. Returned: ERR_FILE_CORRUPT
  <C++ Source>  scene/resources/texture.cpp:566 @ _load_data()
E 0:00:00.731   _load: Failed loading resource: res://.import/GuiChecked.svg-40071e1e72cdcbe9d0e9ea53c8ee9f94.stex. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>   Condition "found" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:270 @ _load()
E 0:00:00.738   _load: Failed loading resource: res://assets/ui/GuiChecked.svg. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>   Condition "found" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:270 @ _load()
E 0:00:00.745   poll: res://theme.tres:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/ui/GuiChecked.svg
  <C++ Source>  scene/resources/resource_format_text.cpp:412 @ poll()
E 0:00:00.749   load: Failed to load resource 'res://theme.tres'.
  <C++ Error>   Condition "err != OK" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:206 @ load()
E 0:00:00.755   _load: Failed loading resource: res://theme.tres. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>   Condition "found" is true. Returned: RES()
  <C++ Source>  core/io/resource_loader.cpp:270 @ _load()
E 0:00:00.759   register_scene_types: Error loading custom theme 'res://theme.tres'
  <C++ Source>  scene/register_scene_types.cpp:795 @ register_scene_types()
```

If I unset the custom theme from Project Settings and just set my top-most Control node's Theme override to use the custom theme, these errors go away. Furthermore, when I have the custom theme configured as a project setting and launch a scene which doesn't have any Control nodes (i.e., no custom theme set or referenced in the scene), I still get these errors. This leads me to believe that my custom theme is okay, and all the related files are okay, but that the problem is somehow related to how the custom theme interacts with the Project Settings.

### Steps to reproduce

1. Open minimal reproduction project and press F5.
2. Check Errors tab of Debugger to see the errors.

### Minimal reproduction project

[CustomThemeBugReport.zip](https://github.com/godotengine/godot/files/7494837/CustomThemeBugReport.zip)

**Comment by pycbouh** [comment] 2021-11-08 10:51
Hmm, I wonder if the problem is related to the usage of SVG for icons, instead of, say, PNG.

**Comment by Deozaan** [comment] 2021-11-08 17:51
I just tested this hypothesis by removing the SVG images from the custom theme and replacing one of them with a PNG. I get the same 7 errors in the same order, but of course this time they refer to the PNG where they used to refer to the SVG.

**Comment by Deozaan** [comment] 2021-11-08 17:59
And perhaps I should clarify that everything appears to work properly even with the errors. It's just that I think these errors should not be happening when launching the project.

So I think that it's just some code happening in the wrong order while initializing the window. It's like it tries to reference the theme on startup before the rest of the engine is ready for that. But then once the rest of the engine catches up and it displays my Control nodes, the custom theme can be accessed without problems.

**Comment by AureaFUNSoft** [comment] 2021-11-09 03:30
I also encounter similar problem. In my case i use webp image, then when run the Theme is not working and the theme just reverted to default. But when I remove the theme from the Project Settings, Instead setting it directly on the root of my control nodes, the Theme is working properly without debugger error.
I hope my information helps.

**Comment by Deozaan** [comment] 2021-11-09 05:38
AureaFUNSoft's comment got me to double check, because I thought the theme was working despite these errors. And I found something interesting.

If I close the project, delete the `.import` folder, then open the project again in Godot 3.3.4, the custom theme setting in the Project Settings works without problems. If I then close the project and open it again in Godot 3.4, the custom theme settings in the Project Settings also works without problems.

But if I then delete the `.import` folder again and open the project in Godot 3.4, I get the errors and the custom theme does not work.

So the issue seems to be related to how Godot 3.4 imports the theme. If Godot 3.3.4 imports the theme, then Godot 3.4 can read it just fine. But if Godot 3.4 imports the theme, I get errors.

**Comment by Ybaedbaenn** [comment] 2021-11-14 13:30
I have the same issue on the same version, Windows 10, GLES3, NVIDIA GeForce GT 540M, graphics driver version 23.21.13.9135, Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz.

The issue occurred when I added a texture to CheckButton by dragging an imported graphic from the editor - the theme stopped displaying, the same errors appeared. Adding a new StreamTexture to CheckButton and manually setting the resource to res://.import/button.png-76b80516a6ac8aaf48535d9d57e0549f.stex caused the theme to start displaying, but the CheckButton texture still does not appear, and the following errors appeared: 
ERROR: Condition "img.is_null() || img->empty()" is true. Returned: ERR_FILE_CORRUPT
   at: _load_data (scene/resources/texture.cpp:566)
ERROR: Condition "img.is_null() || img->empty()" is true. Returned: ERR_FILE_CORRUPT
   at: _load_data (scene/resources/texture.cpp:566)
After restarting the editor, the paths to the resources in StreamTexture are emptied.

**Comment by Sirgulator** [comment] 2021-11-30 02:57
Having the same issue, could trigger the behavior by setting the filtering of a PNG used by the theme and re-importing, since then got this message:

```
ERROR: Condition "img.is_null() || img->empty()" is true. Returned: ERR_FILE_CORRUPT
   at: _load_data (scene/resources/texture.cpp:566)
ERROR: Failed loading resource: res://.import/themetex.png-363ab9f9e3582cb36e37300b1020dd30.stex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading resource: res://GUI/themetex.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://GUI/custom-theme.tres:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://GUI/themetex.png
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://GUI/custom-theme.tres'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://GUI/custom-theme.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Error loading custom theme 'res://GUI/custom-theme.tres'
   at: register_scene_types (scene/register_scene_types.cpp:797)
```

**Comment by pycbouh** [comment] 2021-11-30 15:23
This is not actually a regression. Under the same circumstances, this used to crash the editor on project open, see https://github.com/godotengine/godot/issues/51003. I've just tried again with 3.3-stable with the MRP from this report, and it does indeed just crash on open.

My previous PR fixed the crash, but my research didn't actually lead me to an understanding of what is going on here, see https://github.com/godotengine/godot/pull/51014. I think that WebP module is not loaded (yet?) when we attempt to load the theme and its subresources — icons.

**Comment by Deozaan** [comment] 2021-11-30 21:32
> This is not actually a regression. Under the same circumstances, this used to crash the editor on project open, see #51003. I've just tried again with 3.3-stable with the MRP from this report, and it does indeed just crash on open.
> 
> My previous PR fixed the crash, but my research didn't actually lead me to an understanding of what is going on here, see #51014. I think that WebP module is not loaded (yet?) when we attempt to load the theme and its subresources — icons.

I'm not sure that what you're describing fully explains this issue.

The MRP project crashes for me in 3.3.4-stable as well. But I assumed that was because the files were imported using 3.4-stable, and that it wasn't backwards compatible. If I delete the `.import` folder, then the project will open without errors in 3.3.4-stable. And then I can also open the project in 3.4-stable without any errors.

So it seems to me that it has more to do with how 3.4 is trying to import the files than it has to do with waiting for things to be loaded.

**Comment by pycbouh** [comment] 2021-11-30 21:59
It is absolutely because of the load order. Your observations are explained by https://github.com/godotengine/godot/pull/47854 also being a part of 3.4. The way the textures are imported by default has changed.

**Comment by Deozaan** [comment] 2021-11-30 22:06
Understood. Thank you for explaining.

**Comment by Sirgulator** [comment] 2021-12-02 15:01
Is this expected to be fixed for 3.4 release? Currently the only breaking bug we have before release later this month.

So as I understand correctly, if i would open the project in 3.3.4 and generate a .import file for the Theme and related textures, it would work in 3.4 as long as you not re-import the assets?
How would this behave on exporting the game?

**Comment by pycbouh** [comment] 2021-12-02 15:08
> Is this expected to be fixed for 3.4 release? 

It's not been merged yet, but yes, https://github.com/godotengine/godot/pull/55484 can be cherry-picked for a 3.4.x patch.

> So as I understand correctly, if i would open the project in 3.3.4 and generate a .import file for the Theme and related textures, it would work in 3.4 as long as you not re-import the assets?

`Theme` doesn't have an import file, it's a natural Godot resource. The problem is with images, they need to be imported with 3.3.4, so that they are stored as PNGs instead of WebPs. I think you can also fix this in 3.4 temporarily by forcing it to import PNGs. See the `rendering/lossless_compression/force_png` setting.

> How would this behave on exporting the game?

The 3.3 trick should work, as long as you run it on the same machine with pregenerated `.import` folder.

**Closed** 2021-12-02 16:20 UTC
Labels: bug, topic:editor, topic:gui

**Comment by rockgem** [comment] 2021-12-04 07:41
im having the same problems, and when i try to load my project in 3.3.4 it simply crashes. it definitely isn't backwards compatible.

**Comment by pycbouh** [comment] 2021-12-04 11:43
> im having the same problems, and when i try to load my project in 3.3.4 it simply crashes. it definitely isn't backwards compatible.

You need to delete the .import folder before opening your project in 3.3. That's because 3.3 is not forward compatible with some changes in 3.4. You should also be able to avoid the issue in 3.4 itself by forcing PNG imports (see discussion above). Or you can wait for 3.4.1 patch that fixes the issue with the default setting.
