### ISSUE TITLE
Glitchy light behaviour on gridmaps in GLES2 and GLES3.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#26269] opened 2019-02-25 10:02 UTC
**Godot version:**
Godot_v3.1-beta7
Retested in 3.1-RC1, same results.

**OS/device including version:**
Linux Mint 19.1
NVIDIA GP106 [GeForce GTX 1060 6GB], Driver version: 415.27

**Issue description:**
Lights (OmniLights in this case), do not seem to render correctly on GridMaps while using GLES2.

**Steps to reproduce:**
Place lights in any scene that has a GridMap in it, and test using GLES2.

Examples:
![02](https://user-images.githubusercontent.com/781121/53329543-95500f00-38ec-11e9-9f08-8e1a4ce1d162.gif)

![01](https://user-images.githubusercontent.com/781121/53329414-50c47380-38ec-11e9-950c-11f7ecce86ff.gif)

**Comment by EzraT** [comment] 2019-03-06 09:57
After some more testing I also found out this sometimes happens in GLES3 as well, just a lot less often than it does in GLES2.
Will update later with another screenshot.

**Comment by eon-s** [comment] 2019-03-10 20:39
I cannot reproduce using the kinematic demo and omnilights, can you add a minimal project where you can reproduce it? otherwise this will be hard to test and solve.

Also, looks similar to this old issue #8651.

**Comment by EzraT** [comment] 2019-03-10 21:32
@eon-s 
Reproduction Project:
[lightbug.zip](https://github.com/godotengine/godot/files/2950087/lightbug.zip)

After opening it, select OmniLight8, and focus the camera on it with F.
After that orbit the camera round it with middle mouse button.
It can be a little tricky to get the glitch to show up, the angles are a bit specific, but I can reliably reproduce it this way.

**Comment by eon-s** [comment] 2019-03-10 22:01
On Ubuntu with amdgpu on R5 and GLES3 cannot reproduce it.
On GLES2 got this:
![lightbug](https://user-images.githubusercontent.com/10215987/54092026-028c8700-4366-11e9-983f-1f7dfde6a90b.gif)
See the strange effect on both lights on the floor when looking down.

**Comment by avril-gh** [comment] 2019-03-10 22:03
can confirm on build 59aa79f2182c070a7f2c274072da50a5a2934e70
Windows7 x64 GT720 Gles2

![1032019_2255_41](https://user-images.githubusercontent.com/3224132/54092081-2a8ce200-4388-11e9-83e8-ce2a5807fdab.gif)

**Comment by EzraT** [comment] 2019-03-10 22:06
Here's another example:
![05](https://user-images.githubusercontent.com/781121/54092155-041b7680-4389-11e9-9b27-99f5b48a12c2.gif)
It is much much harder to reproduce in GLES3, but I can sometimes do it on my main project.

**Comment by EzraT** [comment] 2019-05-24 18:04
Another example of this happening in GLES3:
[Video](https://gfycat.com/leftabandonedfrogmouth)

**Comment by Megalomaniak** [comment] 2019-05-24 23:45
looking at image in https://github.com/godotengine/godot/issues/26269#issuecomment-470044288

It looks to me like polygon normals get flipped...

**Comment by clayjohn** [comment] 2019-07-15 22:04
Just tested out, this will be fixed by https://github.com/godotengine/godot/pull/30570

**Comment by EzraT** [comment] 2019-07-15 23:23
> Just tested out, this will be fixed by #30570

Correct me if I'm wrong, but I dont think the PR you linked will fix the gridmap seams problem described in this issue, so this should probably stay open regardless.

**Comment by clayjohn** [comment] 2019-07-16 01:30
Can you upload an image showing that? I can't reproduce nor can I see that issue from any of the videos.

**Comment by EzraT** [comment] 2019-07-16 05:09
@clayjohn 
[Video](https://gfycat.com/leftabandonedfrogmouth)
And:
![05](https://user-images.githubusercontent.com/781121/54092155-041b7680-4389-11e9-9b27-99f5b48a12c2.gif)
And also:
![01](https://user-images.githubusercontent.com/781121/53329414-50c47380-38ec-11e9-950c-11f7ecce86ff.gif)

**Comment by clayjohn** [comment] 2019-07-16 05:15
Ah yes! I see it now. Thank you. 

Also notice how the one getting cut off is the weird bright highlight? But underneath you can see the original light is fine. Its just another symptom with the same underlying issue. Both issues will be fixed by https://github.com/godotengine/godot/pull/30570

If you are interested. What is happening is that some objects are mistakenly retaining a reference to the light that used to effect them, but then that light is removed from the array, making them instead refer to a light already affecting them twice. However, this happens on a per-object basis, so some objects are being lit twice, while their neighbouring object isn't, resulting in the sharp lines.

**Comment by EzraT** [comment] 2019-07-16 05:18
Are you sure? The first video in my reply shows an instance of this happening in GLES3, so I doubt that's the case.

**Comment by clayjohn** [comment] 2019-07-16 05:26
I didnt realize that one was GLES3. It looks like the same underlying issue. It is still doubling up light intensity but only on a specific object. 

Im gonna try to reproduce on GLES3.

**Comment by EzraT** [comment] 2019-07-16 06:08
Okay, after trying to reproduce this more I think I know what causes the lights being cut off, its Godot's hard limit of 8 lights per mesh, apparently I'm just using too many lights in my scene. 
When I lower the amount of OmniLights, the seams dissapear.

So to sum up what I think happens here:

When creating GridMaps in the editor, the gridmap itself is not baked, meaning every cell of the map is treated as its own MeshInstance.(?)
But at some point, I'm not entirely sure when this happens, Godot bakes GridMaps into larger chunks, and if there are more then 8 Lights cast on one chunk, and less than 8 on the other, any light cast on more then 1 chunk, results in that light being cut off at certain camera angles.

So I think this is probably a side effect of how lights work in Godot's current renderer, its unfortunate if thats the case.
I hope this limit can eventualy be raised or lifted in the upcoming Vulkan renderer, because this is quite limiting for lighting on GridMaps.

**Comment by clayjohn** [comment] 2019-07-16 06:20
Good detective work! 

That does seem like a frustrating situation. I think the plan for Vulkan is to allow for many more lights per object. As for 3.2, we should see if there is a way to make max number of lights per object a project setting or something.

**Comment by EzraT** [comment] 2019-07-16 06:29
Thanks to you and @SonerSound for the GLES2 fix!
I'll see if I can circumvent this problem in the meantime by using a BakedLightMap.

**Closed** 2019-07-17 07:56 UTC
Labels: bug, topic:rendering

**Comment by jamie-pate** [comment] 2020-02-04 00:10
Still getting this behavior in GLES3 in 3.2-stable.

interestingly, setting this code a few frames after _ready `cell_octant_size = cell_octant_size` seems to fix the issue!

**Comment by jamie-pate** [comment] 2020-02-04 02:10
> Thanks to you and @SonerSound for the GLES2 fix!
> I'll see if I can circumvent this problem in the meantime by using a BakedLightMap.

imo BakeLightMaps + GridMap = disaster. (if your gridmap tiles are even slightly complicated, it bakes the gridmap and super-bloats your scenes)

**Comment by EzraT** [comment] 2020-06-17 09:53
> imo BakeLightMaps + GridMap = disaster. (if your gridmap tiles are even slightly complicated, it bakes the gridmap and super-bloats your scenes)

You are correct, I did not manage to get good enough results with BakedLightMap, by now I think most people are aware already that the current Lightmapping implementation in 3.x is kinda bad.
reduz has also said this, hence the upcoming re-write for 4.0, which will be much much better.
