### ISSUE TITLE
Full screen shaders does not work in browser (texscreen issue?)

### ISSUE THREAD

**Issue by DjPale** [godotengine/godot#8299] opened 2017-04-06 22:56 UTC
**Operating system or device - Godot version:**
Windows 10 Pro x64 v1607
Chrome Version 57.0.2987.133
Godot v2.1.2-stable (Steam)

**Issue description:**
Full-screen shaders doesn't work on Chrome, might be an issue with texscreen as I discovered this while making my own screen-space shading with some lighting effects

**Steps to reproduce:**
Export the demo "Screen-Space Shaders to the HTML target", host it and run in Chrome. Select an effect, only the fx-texture is shown

**Link to minimal example project:**
Demo included with Godot - `demos/2d/screen_space_shaders`

**Comment by bojidar-bg** [comment] 2017-04-07 08:09
Can someone confirm on 3.0?

**Comment by jomoho** [comment] 2017-04-19 14:19
I have this issue on all export targets, I basically get a white screen. Seems like on export the item is rendered before reading from texscreen?!

**Comment by cwkx** [comment] 2017-04-28 11:00
Also getting this, caused some grief in ludum dare. Any thoughts?

**Comment by reduz** [comment] 2017-04-28 12:47
I think glCopyTexSubImage for some reason migh not work. 3.0 uses a
different approach that should work

**Comment by cwkx** [comment] 2017-04-28 13:03
Thanks, any chance of fixing the "Export to Godot 3.0" or fixing this in the stable? I have quite a heavily-shader based game that would like to let people play in HTML5 asap, but updating it fails "Error loading scene. Ugh".

**Comment by akien-mga** [comment] 2017-04-28 13:05
>  a heavily-shader based game that would like to let people play in HTML5 asap

The HTML5 platform in 2.1.x has various issues, it's not ready meant for production. It should be better in the upcoming version 3.0, but it's still a few months away, so it won't work for a "asap" need.

**Comment by reduz** [comment] 2017-04-28 13:35
Its a non supported feature I think and it's not fixable due to how 2.x
renderer works. 3.0 uses a different rendering method in general.

**Comment by punto-** [comment] 2017-04-28 16:39
Is this a problem with Angle's implementation of glCopyTexSubImage? Maybe
they'll know

**Comment by kubecz3k** [comment] 2018-04-07 11:06
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by kubecz3k** [comment] 2018-04-07 11:06
It's unlikely to be fixed in 2.x Can someone confirm it's no longer the case in 3.0?

**Comment by Gpas** [comment] 2018-06-14 17:43
Does this issue still need testing? I could test it with Windows 10 and different browsers with the newest stable release.

**Comment by akien-mga** [comment] 2018-09-17 13:53
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 13:53 UTC
Labels: bug, confirmed, topic:rendering

**Comment by eon-s** [comment] 2018-09-17 14:52
This may need to be tested with webgl 1 export on 3.1.
