### ISSUE TITLE
VisualShader editor shader_param and editor layout bug

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#20396] opened 2018-07-23 23:42 UTC
**Godot version:**
Godot Engine v3.1.dev.calinou.4b549fa

**OS/device including version:**
windows 10

**Issue description:**
1st issue:
Shader_param sub tab does not show when i have a uniform set in the visual shader editor.
UNLESS i press some of those buttons that are shown in the picture, it somehow updates the engine.
and if i change the shader param and try to run the game it will not react to what my input was.
and when i come back to the shader material the shader_param window is gone, and i have to press those checkboxes again for it to show up.
But! after i minimized godot and maximized it a while later the shader_param sub tab does show all the time now, and the value i set in the param works aswell.
but this brings me to the 2nd issue:
if i resize the layout tabs and minimize and then maximize they get reset to there original saved position.

![godotvsbug](https://user-images.githubusercontent.com/13393087/43108560-b7090390-8ee2-11e8-8a4c-960e289be252.PNG)
![godotvsbug2](https://user-images.githubusercontent.com/13393087/43108565-bba6ac40-8ee2-11e8-94d1-965c8b8638de.PNG)

**Comment by reduz** [comment] 2018-11-25 19:14
I can't reproduce this, may have been fixed so closing. Feel free to repoen if it persists.

**Closed by reduz** 2018-11-25 19:14 UTC
Labels: bug, topic:editor, usability
