### ISSUE TITLE
Array.count() not working on parsed JSON

### ISSUE THREAD

**Issue by izneuhaus** [godotengine/godot#46584] opened 2021-03-02 05:10 UTC
**Godot version:**
3.2.3.stable

**OS/device including version:**
macOS Catalina (v10.15.7)

**Issue description:**
Calling `Array.count()` on an array that was parsed from a JSON string always returns zero. Calling the method on a non-JSON Array works as expected.

**Steps to reproduce:**
```
var json_string : String = "[0,8,8,0]"
var json_array : Array

json_array = JSON.parse(json_string).result
json_array.count(8) # expected result is 2, returns 0
```

**Minimal reproduction project:**
[Archive.zip](https://github.com/godotengine/godot/files/6066274/Archive.zip)

**Comment by nobuyukinyuu** [comment] 2021-03-02 05:33
numeric values parsed in from JSON are always of `TYPE_REAL`.  To get the proper count you have to make a comparison which can be implicitly converted to/from this value.  In this case,   `json_array.count(8.0)` will return the proper value of 2.

**Comment by akien-mga** [comment] 2021-03-02 09:01
Closing as not a bug as described by @nobuyukinyuu.

**Closed by akien-mga** 2021-03-02 09:01 UTC
