### ISSUE TITLE
Ubuntu Touch support

### ISSUE THREAD

**Issue by roman2861** [godotengine/godot#2913] opened 2015-11-25 16:59 UTC
Hello everyone.

My promise is to add Ubuntu Touch support in Godot Engine. You will be the first engine, which supports UT and with Your help we can port and develop many games for that awesome platform!

**Comment by vnen** [comment] 2015-11-25 21:56
If you manage to do it, that'd be great. There's a request for that (among other platforms) in #1516.

**Comment by punto-** [comment] 2015-11-25 22:16
Can we get any hardware from Ubuntu to test this?

**Comment by razvanc-r** [comment] 2016-03-02 09:21
I'm highly interested in this as well. Nexus works with ubuntu touch doesn't it? Other than that there has to be some emulators somewhere around

**Comment by akien-mga** [comment] 2016-04-01 13:56
Closing as duplicate of #1516.

**Closed by akien-mga** 2016-04-01 13:56 UTC
Labels: enhancement, platform:linux, topic:porting
