### ISSUE TITLE
C# Built-in Timers Keeps Working Even if Script's node Got Freed

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#44503] opened 2020-12-18 18:44 UTC
**Godot version:**
3.2.3.stable.mono / 3.2.4.beta4.mono

**OS/device including version:**
All

**Issue description:**
C# Built-in `Timer` keeps working in background even if the node attached to the script got reloaded/freed , sometimes it fires 

```
E 0:00:45.219   godot_icall_2_93: Parameter "ptr" is null.
  <C++ Source>  modules/mono/glue/mono_glue.gen.cpp:898 @ godot_icall_2_93()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_2_93(IntPtr , IntPtr , System.String , System.Object )()
                Object.cs:138 @ void Godot.Object.Set(System.String , System.Object )()
                (
                :0 @ void System.Timers.Timer.MyTimerCallback(System.Object )()
                :0 @ void System.Threading.Timer+Scheduler.TimerCB(System.Object )()
                :0 @ void System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()()
                :0 @ Boolean System.Threading.ThreadPoolWorkQueue.Dispatch()()
                :0 @ Boolean System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()()

```

**Steps to reproduce:**
Create a  `Timer` with `AutoReset = true` , Reload/Free the scene , the old `Timer` keeps Calling `Elapsed` beside the new created one from the new instance.

**Minimal reproduction project:**
[GodotTimerIssue.zip](https://github.com/godotengine/godot/files/5717510/GodotTimerIssue.zip)

**Comment by MrZak-dev** [comment] 2020-12-18 18:49
A simple approach to go over this is to call `Timer.Dispose()` in `_ExitTree()` Call .
e.g 
```csharp
public override void _ExitTree()
{
    MyTimer.Dispose();
}
```

**Comment by Calinou** [comment] 2020-12-18 20:17
cc @neikeq

**Comment by MrZak-dev** [comment] 2020-12-22 15:57
Update : 
This happens even if the timer is local variable , they don't get Disposed after Freeing a scene or reload.

**Comment by Tobi-Mob** [comment] 2021-09-10 20:57
That is the expected behaviour for a .net Timer.
The Object is kept alive, even if the variable or the containing object goes out of scope.

This does not only happen in Godot, it also happens in a Console-Application or Winforms-Application (See example below)
I don't think it is reasonable possible for Godot to find and Dispose all IDisposeables.

In the case below, the Timer variable goes out of scope and the Timer is no longer accessible by normal means.
It only exists somewhere in the runtime memory. Even if the Timer is somehow pulled out of the runtime memory, it would be hard to guess if the timer is still required or just dangling in the air.

Example of the Behaviour in a .net Console Application:

        static void Main(string[] args)
        {
            TestTimer();
            Console.WriteLine("Timer Variable is out of scope, but the object is still alive");
            Console.ReadLine();
        }

        static void TestTimer()
        {
            Timer t = new Timer(5000);
            t.Enabled = true;
            t.Elapsed += OnTick;
        }

        private static void OnTick(object sender, ElapsedEventArgs e)
        {
            Console.WriteLine("Tick");
        }

Will produce this output:
>Timer Variable is out of scope, but the object is still alive
>Tick
>Tick
>Tick

The one who creates the IDisposeable object is usually responsible to also call Dispose
(Your `override _ExitTree()` seems like a good solution)

See: https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer?view=net-5.0#remarks
>This type implements the IDisposable interface. When you have finished using the type, you should dispose of it either directly or indirectly.

**Comment by Tobi-Mob** [comment] 2021-09-10 21:02
Instead of a .net Timer, maybe a Godot coroutine would be a good solution?

I am not sure, but maybe it is possible to combine this: https://docs.godotengine.org/en/3.2/getting_started/scripting/c_sharp/c_sharp_differences.html#yield

```
await ToSignal(timer, "timeout");
GD.Print("After timeout");
```

And this: https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_basics.html#coroutines-signals

```
# Wait 5 seconds, then resume execution.
yield(get_tree().create_timer(5.0), "timeout")
```

**Comment by Tobi-Mob** [comment] 2021-09-12 17:50
Should look like this in c#

    //Wait 5 seconds, then resume execution.
    await ToSignal (GetTree().CreateTimer (5, false), "timeout");

**Comment by raulsntos** [comment] 2023-07-12 14:47
Closing as working as intended, as explained by @Tobi-Mob. Thanks!

**Closed by raulsntos** 2023-07-12 14:47 UTC
Labels: bug, topic:dotnet
