### ISSUE TITLE
utf8support

### ISSUE THREAD

**Issue by s3543130** [godotengine/godot#90052] opened 2024-03-30 19:37 UTC
### Tested versions

4.2.1.stable

### System information

win11 22H2 22621.3296

### Issue description

Using non-ASCII characters will disable syntax hints,
In Godot Engine, double-clicking in the GDSript editor fails to select the specified name, and finally selects the entire line.
Using non-ASCII names in vscode will lose the [editor.hove.enabled] feature.
Non-ascii is the normal case:
{
In the help documentation
In code completion
}
![vscode鼠标悬停提示不可用](https://github.com/godotengine/godot/assets/70407821/87ed91cc-b6a8-47dd-a7d1-996b31339d3a)

### Steps to reproduce

res://N_节点2D.gd

### Minimal reproduction project (MRP)

[尝试.zip](https://github.com/godotengine/godot/files/14813141/default.zip)

**Comment by s3543130** [comment] 2024-03-30 19:39
![vscode鼠标悬停提示可用](https://github.com/godotengine/godot/assets/70407821/ff8af9bc-6323-4cb6-bb6e-586945baac6f)

**Comment by s3543130** [comment] 2024-03-30 19:41
![QQ截图20240331034104](https://github.com/godotengine/godot/assets/70407821/8ad73bb3-8a1a-4df3-87e9-8bbcbfa4f882)
![QQ截图20240331034157](https://github.com/godotengine/godot/assets/70407821/1928ecb2-73e5-4720-82dc-a379a243afee)

**Comment by kitbdev** [comment] 2024-04-03 22:59
- For the internal script editor see https://github.com/godotengine/godot/issues/75808
- For the VSCode plugin, it can be reported here: https://github.com/godotengine/godot-vscode-plugin

**Comment by akien-mga** [comment] 2024-04-04 15:05
As per above comment, closing as partial duplicate of #85808. Please report the VSCode plugin issue on https://github.com/godotengine/godot-vscode-plugin/issues if it doesn't exist already.

**Closed by akien-mga** 2024-04-04 15:05 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing
