### ISSUE TITLE
Button "Pretty Code" in Script Editor

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#26198] opened 2019-02-23 16:36 UTC
**Feature description:**
It would be good to see a button that would format the GDScript code (also C# and others) similarly to the clang-format for C++.

**Comment by Zylann** [comment] 2019-02-23 16:48
Similar to https://github.com/godotengine/godot/issues/7392

**Comment by groud** [comment] 2019-02-23 17:31
Yes, closing as a duplicate of #7392

**Closed by groud** 2019-02-23 17:31 UTC
