### ISSUE TITLE
3.1 KinematicBody stop_on_slope parameter is not properly implemented in move_and_slide

### ISSUE THREAD

**Issue by knut-soltvedt** [godotengine/godot#34228] opened 2019-12-09 19:23 UTC
Hi folks,

I've just started to play with the engine, and it's awesome. But I think I've found a small bug with the behaviour of the `stop_on_slope` parameter of `move_and_slide` for KinematicBody. 

Indeed, the character still slightly slides down before stopping, as shown by the [following gif](https://imgur.com/a/ZQ2ILT5).
![ezgif-6-b4df92b03887](https://user-images.githubusercontent.com/17750346/70465233-ce92ed80-1ac0-11ea-8635-d7d5108942be.gif)

I've read the code that handles this part, and I think [this line](https://github.com/godotengine/godot/blob/3.1/scene/3d/physics_body.cpp#L1222) is reponsible for this behaviour:
```
if ((lv_n + p_floor_direction).length() < 0.01)
```
We're basically checking that normalized velocity and floor normal cancels each others before stopping the body - i.e. we're checking only gravity applies to the body. However, if the body decelerates "slowly", there will be one point in time where gravity will take over its motion, causing it to slide down slightly before reaching the condition's equilibrium. The following diagram is an attempt to explain what's happening:

![image](https://user-images.githubusercontent.com/17750346/70467918-66470a80-1ac6-11ea-863f-7bf6b82a12ca.png)

One solution could be to change the above condition for something that checks the norm of the "horizontal" velocity along the plane solely.

**Comment by madmiraal** [comment] 2020-01-17 13:39
Duplicate of #34117?
Have you tried the suggestions [there](https://github.com/godotengine/godot/issues/34117#issuecomment-565698923)?

**Comment by Calinou** [comment] 2020-01-29 22:19
Duplicate of #34117.

**Closed by Calinou** 2020-01-29 22:19 UTC
Labels: bug, topic:physics
