### ISSUE TITLE
Adding contours of the selected object and his children nodes

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18465] opened 2018-04-27 11:58 UTC
Currently it is hard to see which assets are selected, a box appears arround the model. And is the scene is instanced from a Spatial node, a little cube is added at the position of the node, with a big model or detailled one or a model with the same color as the little cube it becomes invisible. I suggest to add an highlight arround the model, maybe in orange like Blender, Unity and Unreal do. The line should be thick like in Blender 2.8.
The line have less opacity when hidden behind other objects and two color, a darker color for other selection and a brighter color for the main selection.

How the line works is that they should highlight every children objects when selected, so an instanced scene should highlight every assets in the scene when selected. Every children use the darker color.

Here is what Blender 2.8's line looks like:

![lines](https://user-images.githubusercontent.com/30020215/39361462-dda34a2e-4a22-11e8-8d25-7b3000ef1243.png)

**Comment by Vega-KH** [comment] 2018-05-05 22:43
I've been thinking about how this could be implemented (I think it would look nice, nearly all DCCs use outline on 3D objects).  It seems that the only way to accomplish this would be to add an extra shader pass on the objects with grow + inverted normals. (post processing would be way too costly.)

Anyone have other ideas on this?  After I thought about how to implement it, it seems rather daunting.

**Comment by Calinou** [comment] 2018-05-05 22:48
@Vega-KH Godot has built-in support for multi-pass materials (you can add a spatial or shader material to a material's **Next Pass** property) and its spatial material features a **Grow** property which can be used to draw outlines around objects (when used with the **Front** culling mode).

**Comment by Vega-KH** [comment] 2018-05-06 23:59
Thanks for the info, @Calinou . I think maybe I don't want to jack into the Next Pass property because if the material on the object already has a next pass, I would be overriding it. So basically I will need to detect if an object is selected and add another pass directly in the visual server.

Maybe I will test post-processing first to see how costly it actually is. It would be much easier to implement.

**Comment by Calinou** [comment] 2021-02-15 03:04
Duplicate of https://github.com/godotengine/godot/issues/10702.

**Closed by Calinou** 2021-02-15 03:04 UTC
Labels: enhancement, topic:editor, usability
