### ISSUE TITLE
Print Statement does not output with multiple instances of Godot open at once. 

### ISSUE THREAD

**Issue by jkdean1** [godotengine/godot#37740] opened 2020-04-10 06:07 UTC
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Mac OS Catalina Version 10.15.4

**Issue description:**
I am working on a multiplayer game, I have my project setup such that the server and client are actually in separate godot projects.(possibly not the best way to do this but...) when I run one, the other does not allow/have any print statement output. It does not matter which I run first the other instance of the godot editor on my machine cannot print. It took me a very long time to figure out that this is the issue. Could possibly be a mac issue with the way macOS handles the different processes? 

**Steps to reproduce:**
Run one instance of godot with a project, and then run another instance of godot in a separate project on the same machine. Print anything desired to the console like "hello world" in each. The editor that the run button is clicked second will not produce the hello world message. 

**Minimal reproduction project:**

### Here is a screen shot of an example with the output windows, (A) launched before (B)

![Screen Shot 2020-04-10 at 1 01 28 AM](https://user-images.githubusercontent.com/22102430/78967019-e9a15880-7ac6-11ea-9d9a-d758ab7f9438.png)

### Here is a screen shot of the example code, each is connected the same way. 
![Screen Shot 2020-04-10 at 1 01 28 AM](https://user-images.githubusercontent.com/22102430/78967034-f2922a00-7ac6-11ea-866a-dc1afacb0a8d.png)

I am assuming the "Error listening on port 6007" is related? does the godot editor use the same output stream for both?

**Comment by aaronfranke** [comment] 2020-04-10 06:40
This is a duplicate of #20020.

You're not supposed to open two instances of the editor for the same project, and currently you can only have one instance of the game per editor, which #20020 proposes to make possible.

**Closed by aaronfranke** 2020-04-10 06:40 UTC

**Comment by jkdean1** [comment] 2020-04-10 16:47
They are different projects and different editors, not the same instance of one project twice. That was why I thought it was a little different compared to the other issue. It could be the same, and it might not be an issue at all if that is by design.

**Comment by aaronfranke** [comment] 2020-04-10 22:29
Oh, I see. It's not the same symptom, but it's still something that will also be fixed when #20020 is fixed (since it will use different ports for different instances), so I'll leave this closed.
