### ISSUE TITLE
textinput cannot response to keys input. when input method changed 

### ISSUE THREAD

**Issue by TracyLestrade** [godotengine/godot#75962] opened 2023-04-12 02:37 UTC
### Godot version

4.0.1 stable

### System information

windows 10 intel UHD 600.

### Issue description

when I change system input method. godot script editor cannot response some keys. like
backspace, up, down, left, right, delete, enter. 
also happend to other textinput

### Steps to reproduce

changeg input method (windows + space)

### Minimal reproduction project

none

**Comment by Zireael07** [comment] 2023-04-12 09:06
This is a bug that has been fixed in 4.0.2

**Comment by AThousandShips** [comment] 2023-04-12 09:35
Duplicate of #74957, search tags such as "input method" should be added, though it *is* pinned

**Closed** 2023-04-12 09:38 UTC
