### ISSUE TITLE
Godot crashes, when using LSP

### ISSUE THREAD

**Issue by drmgc** [godotengine/godot#53128] opened 2021-09-27 13:31 UTC
### Godot version

v3.3.3.stable.official.b973f997f

### System information

Debian Bookwarm, GLES3, GeForce GTX 670

### Issue description

Godot crashes, when connecting to it via lsp, when opening more then one file.
```
Godot Engine v3.3.3.stable.official.b973f997f - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 670/PCIe/SSE2
OpenGL ES Batching: ON
 
Project is missing: /home/drmgc/prj/castra/project.godot
Editing project: /home/drmgc/sandbox/NewGameProject (::home::drmgc::sandbox::NewGameProject)
Godot Engine v3.3.3.stable.official.b973f997f - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 670/PCIe/SSE2
OpenGL ES Batching: ON
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7f567f3ebd60] (??:0)
[2] /opt/Godot_v3.3.3-stable_x11.64() [0xe15f97] (??:0)
[3] /opt/Godot_v3.3.3-stable_x11.64() [0x2f78a1a] (??:?)
[4] /opt/Godot_v3.3.3-stable_x11.64() [0x2f288f5] (??:?)
[5] /opt/Godot_v3.3.3-stable_x11.64() [0xe50446] (??:0)
[6] /opt/Godot_v3.3.3-stable_x11.64() [0xe447b5] (??:0)
[7] /opt/Godot_v3.3.3-stable_x11.64() [0x2f2cec1] (??:?)
[8] /opt/Godot_v3.3.3-stable_x11.64() [0x2f2d90c] (??:?)
[9] /opt/Godot_v3.3.3-stable_x11.64() [0x2f64a28] (??:?)
[10] /opt/Godot_v3.3.3-stable_x11.64() [0x2f7fd1b] (??:?)
[11] /opt/Godot_v3.3.3-stable_x11.64() [0xe142e4] (??:0)
[12] /opt/Godot_v3.3.3-stable_x11.64() [0x1cda1ae] (??:0)
[13] /opt/Godot_v3.3.3-stable_x11.64() [0x1ceb9c8] (??:0)
[14] /opt/Godot_v3.3.3-stable_x11.64() [0x3119a3d] (??:?)
[15] /opt/Godot_v3.3.3-stable_x11.64() [0x990dcd] (??:0)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f567f3d6d0a] (??:0)
[17] /opt/Godot_v3.3.3-stable_x11.64() [0x99f5ae] (??:0)
-- END OF BACKTRACE --```

### Steps to reproduce

1. start editor (emacs with lsp-mode and gdscript-mode)
2. start godot
3. start lsp in one or two buffers
4. edit one of files
5. godot crashes with som time

### Minimal reproduction project

[repr.zip](https://github.com/godotengine/godot/files/7236582/repr.zip)

**Comment by akien-mga** [comment] 2021-09-27 13:36
Duplicate of #51923.

**Closed by akien-mga** 2021-09-27 13:36 UTC
