### ISSUE TITLE
Kinematic Collision Flickering Tiles Godot 3

### ISSUE THREAD

**Issue by Archeia** [godotengine/godot#16280] opened 2018-02-01 11:11 UTC
**Godot version:**
Godot_v3.0-beta2_win64.exe

**OS/device including version:**
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
16 GB RAM
NVIDIA GeForce GTX 1080

**Issue description:**
I tried out the kinematic collision example and then noticed that tiles are flickering.

**Steps to reproduce:**
Just play test and walk around for a bit. The severity of the flickering is random but alt tabbing seems to trigger it more often. Here's a video:
https://youtu.be/PBB2cOkbus8

I had a worse case that it lasts for a long time with more tiles missing without alt tab too.

**Minimal reproduction project:**
Just download the demo project and hit play and walk around for a bit. Within the first 5 minutes you should be able to get flickering.

**Comment by nshusa** [comment] 2018-02-01 11:22
Duplicate of [9913](https://github.com/godotengine/godot/issues/9913)

**Closed** 2018-02-01 11:43 UTC
