### ISSUE TITLE
When exporting an Array[Node], you can't assign any nodes in the UI.

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#72961] opened 2023-02-09 11:34 UTC
### Godot version

4.0-rc1

### System information

Windows 10

### Issue description

When exporting an Array of Node's, in the editor, it shows that it's an Array[Object], and doesn't let you assign any nodes to any of the elements.
![Screenshot 2023-02-09 113224](https://user-images.githubusercontent.com/31216671/217801405-6ff23100-0f8b-4f68-9ce5-0b7d089311a2.png)
In Player.gd, I have the line `@export var nodes: Array[Node]`, yet it doesn't allow me to assign any Node's.

### Steps to reproduce

Write a simple script attached to a node, with the line of code `@export var nodes: Array[Node]` on it, then try to assign a node to an element in the UI.

### Minimal reproduction project

Not applicable.

**Comment by Zireael07** [comment] 2023-02-09 11:35
Duplicate of https://github.com/godotengine/godot/issues/62916.

Please search before opening issues

**Closed** 2023-02-09 11:36 UTC

**Comment by JamesC01** [comment] 2023-02-09 11:42
@Zireael07 Sorry, I must've used a search term that was too generic, because it came up with 7 pages of issues, and I didn't see any in the first page, and assumed it must be a new issue with rc1. I'll try to be more thorough next time I open an issue.

**Comment by akien-mga** [comment] 2023-02-09 11:43
No worry, the search functionality in GitHub is indeed pretty barebones and it can be pretty difficult to find duplicates.
