### ISSUE TITLE
Double Nodes when Inheriting

### ISSUE THREAD

**Issue by FonkinS** [godotengine/godot#70590] opened 2022-12-26 13:28 UTC
### Godot version

4.0 Beta 9

### System information

MacOS Ventura 13.0.1

### Issue description

If you create scene A, and make B an inherited scene from A, if you then add a node, such as `Node2D` to scene B, and you add a node with the same name to scene `A`, scene B will now have two identical nodes with the same name, and will be treated as the same object.

### Steps to reproduce

- Make a new scene
- Make another scene, inherited from the first
- Add any node to the second scene
- Add a node with the same name to the first scene
- Open the second scene. 

You will see that there are two identical nodes, one which was made for the second scene, the other inherited from the first scene.

### Minimal reproduction project

[DoubleNodesFromInheritingBugGodot.zip](https://github.com/godotengine/godot/files/10303641/DoubleNodesFromInheritingBugGodot.zip)

**Comment by KoBeWi** [comment] 2022-12-26 14:31
Duplicate of #26390

**Closed by KoBeWi** 2022-12-26 14:31 UTC
