### ISSUE TITLE
Crashes in PaymentManager.java (2.1)

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#10456] opened 2017-08-19 17:26 UTC
**Operating system or device - Godot version:**
OSX, Android
Godot 2.1.4-beta (commit e5102a9)

**Issue description:**
Sometimes I have crashes in PaymentManager.java like this one:

```
08-19 19:51:06.700: E/AndroidRuntime(21854): FATAL EXCEPTION: main
08-19 19:51:06.700: E/AndroidRuntime(21854): Process: org.asmstudio.spacecute, PID: 21854
08-19 19:51:06.700: E/AndroidRuntime(21854): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=0, data=Intent { (has extras) }} to activity {org.asmstudio.spacecute/org.godotengine.godot.Godot}: java.lang.NullPointerException
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3553)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3596)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.os.Looper.loop(Looper.java:193)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at dalvik.system.NativeStart.main(Native Method)
08-19 19:51:06.700: E/AndroidRuntime(21854): Caused by: java.lang.NullPointerException
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at org.godotengine.godot.payments.PaymentsManager$4.canceled(PaymentsManager.java:226)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at org.godotengine.godot.payments.HandlePurchaseTask.handlePurchaseRequest(HandlePurchaseTask.java:102)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at org.godotengine.godot.payments.PaymentsManager.processPurchaseResponse(PaymentsManager.java:228)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at org.godotengine.godot.Godot.onActivityResult(Godot.java:248)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.Activity.dispatchActivityResult(Activity.java:5456)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3549)
08-19 19:51:06.700: E/AndroidRuntime(21854): 	... 11 more
08-19 19:51:10.501: I/Process(21854): Sending signal. PID: 21854 SIG: 9
```

As far as I see the `PaymentManager.godotPaymentV3` is null but I have no ideas why. Purchases works most the time but sometimes not.

Maybe we should check `godotPaymentV3 != null` in every method of PaymentManager?

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by mhilbrunner** [comment] 2018-04-10 20:35
Closing, duplicate of https://github.com/godotengine/godot/issues/17481.

**Closed by mhilbrunner** 2018-04-10 20:35 UTC
Labels: bug, platform:android, topic:core
