### ISSUE TITLE
Cross compiled export release templates for windows don't work

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#7289] opened 2016-12-13 10:38 UTC
**Operating system or device - Godot version:**
Arch Linux 64bit - latest build

**Issue description** (what happened, and what was expected):
The cross compiled release binary for windows doesn't work. It doesn't matter if it is the 32- or 64-bit version. I'm trying to run the exported game under Windows 10 (which runs in a VM), and it crashes. However, there is one difference: The 64 bit version crashes immediately, while the 32 bit version shows the title screen of the game and crashes when I press "start".
The game runs fine under Linux and in web. The cross compiled debug versions also work fine under Windows.

The fact that it does show the title screen when using the 32 bit version and doesn't when using the 64 bit version indicates that is has something to do with my game. But on the other hand, when it runs fine under linux and webgl (and the debug build), it should just work under Windows, shouldn't it?

I found this issue relating to that problem: #2189 But this has been fixed, if I didn't misread.

**Steps to reproduce:**
Compile godot under Linux. Cross compile Windows release templates. Copy them to template folder. Make a game. Export to Windows. Run under Windows.

**Comment by akien-mga** [comment] 2016-12-13 10:53
If you're using GCC 6, that's a known issue. #4623.

**Comment by lonesurvivor** [comment] 2016-12-13 11:27
I'm using GCC 5. 
However, I just tried with two other projects. Both of them are actually working with the 32 bit build, but are crashing with the 64 bit build.
I also made a new project with a single scene with only a root node. This actually works with both versions. So it has something to do with my projects, but I can't figure out what it is.

**Comment by lonesurvivor** [comment] 2016-12-13 11:33
Oh wait... my mingw actually uses GCC 6... I guess that's the problem.

**Comment by akien-mga** [comment] 2016-12-13 11:46
Indeed, so closing as duplicate of #4623.

**Closed by akien-mga** 2016-12-13 11:46 UTC
