### ISSUE TITLE
In a Navigation Map created programmatically, velocity_computed()->safe_velocity is always 0

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#81859] opened 2023-09-18 12:03 UTC
### Godot version

4.1.1

### System information

Windows 10

### Issue description

If I create a navigation map at runtime, by setting up the navigation mesh, region and everything and then assign that map to the NavigationAgent3D, velocity_computed always returns 0.
Doesn't happen with the basic prebaked navigationmesh.

### Steps to reproduce

Run both scenes. NavigationTestPrebaked works just fine, Agent walks towards the destination. NavigationTestRuntime does nothing, despite query_path() returning a valid path so the RID is working.

### Minimal reproduction project

[test_velocity_computed.zip](https://github.com/godotengine/godot/files/12647518/test_velocity_computed.zip)

**Comment by smix8** [comment] 2023-09-18 15:21
The issue in the test project is that a NavigationAgent3D node that has no target_position set. WIthout a target_position set the NavigationAgent does not process the movement.

This was added because so many users forgot to set a target_position but activated everything else which would make the NavigationAgents move towards the world origin.

f you set the velocity with the NavigationServer3D API using `NavigationServer3D.agent_set_velocity` everything works fine.

**Comment by smix8** [comment] 2023-09-19 22:01
Closing the issue as it was confirmed solved on Discord by user.

**Closed by smix8** 2023-09-19 22:01 UTC
Labels: needs testing, topic:navigation
