### ISSUE TITLE
GDScript debugger may get null object issue

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#74297] opened 2023-03-03 13:34 UTC
### Godot version

4.0 stable

### System information

Windows11

### Issue description

null check always false

### Steps to reproduce

<img width="319" alt="image" src="https://user-images.githubusercontent.com/18411187/222733320-f5b17458-77d6-4640-8a5e-625352433ff0.png">

### Minimal reproduction project

no need

**Comment by AThousandShips** [comment] 2023-03-03 13:37
But the children of a node are never null?

**Comment by AThousandShips** [comment] 2023-03-03 13:40
Are you certain this node is null? There are some cases when the debugger shows data as null when they are too large

**Comment by hakuhan** [comment] 2023-03-03 13:41
> But the children of a node are never null?

Do you mean it is just a debug issue?

**Comment by AThousandShips** [comment] 2023-03-03 13:42
I'm not sure but it looks very strange that a child of a node is null, that should never happen as far as I know

**Comment by hakuhan** [comment] 2023-03-03 13:43
I agree with you. I store this child to a list for later use. And I got a null value. So I foud this issue.

**Comment by AThousandShips** [comment] 2023-03-03 13:45
Is the node still valid at that time? Has it got deleted?

**Comment by hakuhan** [comment] 2023-03-03 13:45
Real value isn't null.
<img width="275" alt="image" src="https://user-images.githubusercontent.com/18411187/222735635-a9e2012f-eaa8-48a2-99ad-063e1c1419b2.png">
<img width="73" alt="image" src="https://user-images.githubusercontent.com/18411187/222735676-df488b5e-3e67-4766-b158-d8e9e34275b7.png">

**Comment by AThousandShips** [comment] 2023-03-03 13:47
#74148 might solve this

**Comment by hakuhan** [comment] 2023-03-03 13:47
> 



> Is the node still valid at that time? Has it got deleted?

Many child nodes in my list is null. But not 100% make it clear.

**Comment by AThousandShips** [comment] 2023-03-03 13:48
Oh, sorry I was confused, can you confirm that the nodes are null, and how do you do so?

**Comment by dalexeev** [comment] 2023-03-03 13:50
Are you sure it's `null` and not Freed Object?

```gdscript
var node := Node.new()
print(node) # <Node#3501556037163>
print(node == null) # false
print(node != null) # true
print("+" if node else "-") # +
print("+" if not node else "-") # -

node.free()
print(node) # <Freed Object>
print(node == null) # true
print(node != null) # false
print("+" if node else "-") # +
print("+" if not node else "-") # +

node = null
print(node) # <null>
print(node == null) # true
print(node != null) # false
print("+" if node else "-") # -
print("+" if not node else "-") # +
```

See also #59816.

**Comment by hakuhan** [comment] 2023-03-03 13:52
I check children at _ready function, It should not be null
<img width="207" alt="image" src="https://user-images.githubusercontent.com/18411187/222737163-3edce714-550d-4edc-92af-80fd721edb0e.png">

**Comment by hakuhan** [comment] 2023-03-03 13:57
But from logs. These children are not null. And I think there has another issues. Because my dictionary container is null when I trying to got one child and I'm sure that container is initailized.

**Comment by hakuhan** [comment] 2023-03-03 13:59
> Are you sure it's `null` and not Freed Object?
> 
> ```gdscript
> var node := Node.new()
> print(node) # <Node#3501556037163>
> print(node == null) # false
> print(node != null) # true
> print("+" if node else "-") # +
> print("+" if not node else "-") # -
> 
> node.free()
> print(node) # <Freed Object>
> print(node == null) # true
> print(node != null) # false
> print("+" if node else "-") # +
> print("+" if not node else "-") # +
> 
> node = null
> print(node) # <null>
> print(node == null) # true
> print(node != null) # false
> print("+" if node else "-") # -
> print("+" if not node else "-") # +
> ```
> 
> See also #59816.

My codes work at beta12. I upgrade engine from beta12 to stable. This issue #59816 comes from alpha version.

**Comment by dalexeev** [comment] 2023-03-03 14:03
Have you checked that the node is `null`? The tooltip can lie:

> Are you certain this node is null? There are some cases when the debugger shows data as null when they are too large

**Comment by hakuhan** [comment] 2023-03-03 14:19
It is a debugger issue.  Equation are right!

**Comment by adamscott** [comment] 2023-03-04 16:14
> ### Minimal reproduction project
> 
> no need

Citing [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project):

> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
> 
> We recommend always attaching a minimal reproduction project, **even if the issue may seem simple to reproduce manually**.

Please join a MRP.

**Comment by hakuhan** [comment] 2023-03-05 02:59
> 

ok

**Comment by Calinou** [comment] 2023-03-19 03:46
- Duplicate of https://github.com/godotengine/godot/issues/36801.

**Closed by Calinou** 2023-03-19 03:46 UTC
