### ISSUE TITLE
Godot crashes when started indirectly in a terminal

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#2536] opened 2015-09-26 09:59 UTC
On Linux when Godot is started with a desktop launcher, if the option 'Run in terminal' is checked Godot crash and the terminal too.
If i use a bash file with the command `xfce4-terminal -H -x path_to_godot` I've just the message "freed code id 1".
The only way is first to open a terminal, and then to write the full path or the alias.

**Comment by akien-mga** [comment] 2015-11-10 19:37
I can confirm this issue in the current master branch (61c4c57).

For example with konsole, KDE's terminal:
* ```konsole -e godot-git``` will start the project manager properly in a new terminal, but trying to load a game results in the terminal closing (normally since the project manager instance is closed), but no new instance is spawned
* ```konsole -e godot-git -e ~/Projects/dynadungeons/dynadungeons/``` starts to load the editor (I can see it trying to go from windowed to maximized as it does usually) and then crashes.
* ```konsole -e godot-git -path ~/Projects/dynadungeons/dynadungeons/``` works fine, so there's definitely an issue with the subprocess spawning mechanism, so I wonder why the command with -e switch would not start the editor process directly.

Sometimes with the above calls, I get this output in the terminal from where I ran the instructions:
```
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 20 (X_GetProperty)
  Resource id:  0x4a0001a
```

Same behaviour with gnome-terminal.

**Comment by reduz** [comment] 2015-12-29 22:16
This is not a bug, it's just that for running a game, either the current directory must be located where the executable is or a path must be provided as command line, do the same with:

xfce4-terminal -H -x path_to_godot -- -path /path/to/game

not sure how you pass arguments to -x executable, but if you figure it out that way will work

**Closed by reduz** 2015-12-29 22:16 UTC
Labels: bug, confirmed, platform:linux, topic:core

**Comment by akien-mga** [comment] 2015-12-29 23:09
Right, something like this does seem to work:
- editor: ```konsole -e godot-git -- -e``` 
- game: ```konsole -e godot-git```

**Comment by BBric** [comment] 2016-10-21 09:00
I have always this problem (i had removed my account), the problem is not to launch Godot with a terminal directly, but with a desktop launcher (for avoid an input each time and launch the editor with a simple double click) which launch a terminal (for the prints which don't appears in the output) which launch Godot.

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Godot
Exec=xfce4-terminal -H -e "/usr/local/godot/godot_2.1 -e"
Terminal=false
StartupNotify=true
```

The "./godot_2.1" command alone works, but not via the launcher or another terminal application, with konsole it is the same.

**Comment by akien-mga** [comment] 2016-10-22 10:03
@BBric Your desktop file works just fine on Plasma 5 (also using xfce4-terminal to be sure). It pops up a dialog to ask me to ensure I trust the execution of this command, and when saying yes it starts Godot in a terminal.

**Comment by BBric** [comment] 2016-10-22 21:45
I have the same behavior but it crash at opening. Maybe that it is linked to this issue #6888.
