### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by keito940** [godotengine/godot#11489] opened 2017-09-22 08:42 UTC
Thank you, keito940.
I saw a site that teaches children to make games with a game engine called Godot.
So, why not correspond to Raspberry Pi?
If you correspond to Raspberry Pi, I think that you can make a full-scale program than Scratch.
However, it may be better to be careful when GDNative...

**Comment by akien-mga** [comment] 2017-09-22 08:50
Raspberry Pi is already supported: https://www.reddit.com/r/godot/comments/6x5byi/godot_214_raspberry_pi_edition/

What do you mean exactly with "correspond to RPi"?

**Comment by keito940** [comment] 2017-09-22 08:54
"correspond to RPi"?

I went in the meaning of making Godot possible to develop with Raspberry Pi ...

**Comment by akien-mga** [comment] 2017-09-22 09:00
Well as mentioned above, it's possible already. You just need to compile the binaries on a Pi.

**Comment by slapin** [comment] 2017-09-22 10:50
will 3.0 work on Pi? IIRC it uses GLES2.

**Comment by astearon** [comment] 2018-02-15 14:10
I also am interested to know if GODOT 3.0 is usable on the Pi2 or the Asus TinkerBoard

**Comment by Calinou** [comment] 2018-02-15 14:15
@astearon Godot 3.0 isn't supported on the Raspberry Pi 1/2/3 since it requires support for OpenGL ES 3.0, and those ARM SBCs only support OpenGL ES 2.0.

By the way, the upcoming Raspberry Pi model is rumored to support OpenGL ES 3.0 – it has been hinted at by commits in the open source VideoCore driver repository.

**Comment by CannonContraption** [comment] 2018-04-12 05:15
Hang on, my pi 3 running raspbian is reporting Mesa 13.0.6 and OpenGL ES 3.0. I haven't updated it in a few months, but it looks like there might be support. Am I reading this wrong? I'm really new to all things graphics so it could just be I'm looking at the wrong section.

Unfortunately when I try compiling, I get a long traceback from Python mentioning that it's trying to build for Android. Having never used scons before, I'm a little in the dark about this.

**Comment by Chaosus** [comment] 2018-09-08 08:11
Closed as duplicate of #2671

**Closed by Chaosus** 2018-09-08 08:11 UTC
Labels: discussion, platform:linuxbsd, topic:porting
