### ISSUE TITLE
Godot (4.3) freezes/crashes when opening projects with lots of spotlights/omnilights

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#89441] opened 2024-03-13 11:39 UTC
### Tested versions

- Reproducible in 4.3.dev4
- Not reproducible in 4.2.1.stable

### System information

Godot v4.3.dev4 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.5161) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Godot 4.3.dev4 cannot open projects with lots of omnilights/spotlights - the editor freezes, and in the console a constant non ending spam of `Condition "err != VK_SUCCESS" is true` is outputted.

### Steps to reproduce

Try to open any project with lots of omnilights/spotlights (perhaps 100+). A publicly available project that satisfies this condition is [Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level).

### Minimal reproduction project (MRP)

[Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level)

**Comment by kitbdev** [comment] 2024-03-13 16:46
- probably duplicate of https://github.com/godotengine/godot/issues/89312

**Comment by clayjohn** [comment] 2024-04-18 04:31
Thank you for the update, in that case, it is definitely a duplicate of https://github.com/godotengine/godot/issues/89441. Dario did some investigation in that thread already. So I will close this report in favour of https://github.com/godotengine/godot/issues/89441 so we can track the issue in one place

**Closed by clayjohn** 2024-04-18 04:31 UTC
Labels: bug, topic:rendering, regression
