### ISSUE TITLE
KinematicBody2D's get_slide_count  sometimes misses collisions

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#17835] opened 2018-03-29 01:21 UTC
**Godot version:**
13d5ee0

**Issue description:**
The KinematicBody2D's method `get_slide_count` can sometimes miss some collisions, depending of the speed of the body itself (at least that seems to be the reason).

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/1858305/Test.zip)

**Comment by eon-s** [comment] 2018-03-29 01:38
Really weird, increasing the higher jump from 1400 to 1500 gets the slide again.

**Comment by mrcdk** [comment] 2018-03-29 02:44
Looks like it's somehow hitting this code https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp#L1049-L1054 setting `slope_stop_min_velocity` to 0 registers the collider. Looks like a bug.

**Comment by reduz** [comment] 2018-09-07 12:49
Can anyone try this one again? I think it should be fixed by now

**Comment by reduz** [comment] 2018-09-07 12:50
I remember someone fixed the function because it was missing collisions

**Comment by aaforcebox** [comment] 2018-09-07 15:00
Tried on 3.1.alpha.official and the problem is gone!! So the bug is only 3.0.6 and earlier versions.

**Comment by YeldhamDev** [comment] 2018-09-08 03:44
@reduz It's... fixed-ish? This used to print "Hit detected!" only when first touching the ground, and not it continuously prints it while being touched. So I'm not really sure.

**Comment by reduz** [comment] 2018-11-16 13:10
Yes, this is clearly fixed

**Closed by reduz** 2018-11-16 13:10 UTC
Labels: bug, topic:physics
