### ISSUE TITLE
Web Editor "Stop" button doesn't kill the game "tab" from running.

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#77182] opened 2023-05-17 23:14 UTC
### Godot version

4.0.2 (Web Editor)

### System information

Firefox, Ubuntu 22.04

### Issue description

Clicking the "Stop" button doesn't kill the game "tab" from running. When a user presses "play" again, the previous game version is still playing (and the web editor won't automatically change tabs). To refresh the game, the user HAS to click the close button from the game tab, even if they already pressed "stop" on the editor.

My use-case is an interactive Web onboarding for the Godot editor. During the onboarding, the user has to click "play" a couple of times to check the game being made; but I can't reference the "Game" tab close button (it's not an editor thing but something from the web editor wrapper), so the only option is to guide the user to click the "Stop" button if the game is being played. When they press "Play" again, the previous game version is still playing, which will confuse users.

### Steps to reproduce

Press play once, and instead of closing the "Game" tab, press stop from the editor interface. Pressing play again won't refresh the game tab.

### Minimal reproduction project

This is not a project-specific thing, it's related to the web editor wrapper itself. Any project can trigger this.

**Comment by Calinou** [comment] 2023-05-17 23:16
- Duplicate of https://github.com/godotengine/godot/issues/57429.

**Closed by Calinou** 2023-05-17 23:16 UTC
Labels: bug, platform:web, topic:editor
