### ISSUE TITLE
FBX Importer fails to import smooth shaded objects

### ISSUE THREAD

**Issue by felixscheffer** [godotengine/godot#48271] opened 2021-04-28 15:18 UTC
I created a simple smooth-shaded UV sphere in Blender (2.90 and 2.91) and exported it as fbx file.
![blender_spehre](https://user-images.githubusercontent.com/1678164/116425446-98cfdf80-a842-11eb-88ec-efe632964707.PNG)

After importing the fbx file into Godot, it looks flat shaded.
![godot_sphere](https://user-images.githubusercontent.com/1678164/116426179-2d3a4200-a843-11eb-9f0d-cfda8623c9a9.PNG)

Importing the same fbx file back into Blender works just fine. Triangulating the sphere before exporting had no effect. 

**Godot versions:**
v3.2.3 mono win64
v3.3 mono win64

I attached the sphere model. If there's anything else you need, let me know.

[sphere.zip](https://github.com/godotengine/godot/files/6392833/sphere.zip)

**Comment by Calinou** [comment] 2021-04-28 15:25
Duplicate of https://github.com/godotengine/godot/issues/46851.

**Closed by Calinou** 2021-04-28 15:25 UTC
