### ISSUE TITLE
Ability to spawn multiple debuggers with automatic port assignment

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20020] opened 2018-07-07 17:29 UTC
Godot 3.0.4

I would like to make a game prototype where X clients can join a game hosted by 1 server.
In order to fully debug this, I need to run at least 2 clients and 1 server with the Godot debugger. For the sake of simplicity, I intend to run one client with 1 editor, and all other processes with the command line debugger (so I could even spawn them from the editor automatically when I hit Play with some custom plugin).

Problem:
The debugger port Godot uses is a global editor setting. This can be handy if you know exactly which game you want to debug, but that also means two debuggers launched on two instances of the same project will conflict.
There is a way to specify the port with the command line debugger, but I think it would just be easier to let Godot pick an available port automatically, when not specified.

In fact, even after trying, the command line option also doesn't work, probably because it's not actually what I think it is (then there is no such parameter as described in this issue):
```
> ../../../bin/Godot_v3.0.4-stable_win64.exe main_server.tscn -d --remote-
debug 127.0.0.1:6008
Remote Debugger: Connection failed with status: '1', retrying in 1 msec.
Remote Debugger: Connection failed with status: '1', retrying in 10 msec.
Remote Debugger: Connection failed with status: '1', retrying in 100 msec.
Remote Debugger: Connection failed with status: '3', retrying in 1000 msec.
Remote Debugger: Connection failed with status: '3', retrying in 1000 msec.
Remote Debugger: Connection failed with status: '3', retrying in 1000 msec.
Remote Debugger: Unable to connect
```

Note:
It can also help implement the ability to spawn multiple game instances from 1 editor and have multiple debugger tabs, though I don't need this at the moment.

**Comment by AlexHolly** [comment] 2018-07-07 23:14
#3696

**Comment by akien-mga** [comment] 2018-07-23 14:19
Duplicate of #3696, but since this one has a more detailed proposal of how it could be implemented, I'll close the older one.

**Comment by clayjohn** [comment] 2020-05-27 19:00
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 19:00 UTC
Labels: feature proposal, topic:editor
