### ISSUE TITLE
Tileset Edit unavailable if shader present in a tile

### ISSUE THREAD

**Issue by LeD95** [godotengine/godot#36947] opened 2020-03-09 17:27 UTC
**Godot version:** v3.2.stable.official (Standard 64-bit for Windows)

**OS/device including version:** Windows 7 Home Premium, 64 bit

**Issue description:** TileSet editing window, normally present at the bottom center of the editor becomes unavailable if any of the tiles in the tileset uses a material with a shader that was opened through inspector of a tile. For lack of better wording there will be screenshots included.

**Steps to reproduce:**
1. Create a TileMap node [1] and add a new TileSet [2] to it, then click on it to enter tileset editor. (Screen_1.png)
2, Create at least one tile for that tileset.
3. In any of the tiles add a new material. Right now everything should be normal (Screen_2.png)
4. Add a new shader to that material[1]. The Shader editor will now appear[2]. (Screen_3.png)
5.  If you were to click away to exit inspector for the tileset, for instance focus a different node on your scene, and then came back to the tileset, instead of the TileMap editor you will see the shader editor. It will not go away if you don't do one of two things.
A) Restart the editor and reenter the TileSet editor.
B) Find the tile where you edited the shader and click the blue name of the shader to close the shader editor. Then unfocus the tileset in inspector and go back into it so that TileMap appears. (Screen_4.png)

**Minimal reproduction project:**
Attached [BugReport.zip](https://github.com/godotengine/godot/files/4308078/BugReport.zip)
(though I doubt its usefulness because restarting fixes it)

![Screen_1](https://user-images.githubusercontent.com/61984474/76240252-33cabc00-6233-11ea-9e6f-3418a8daef70.png)
![Screen_2](https://user-images.githubusercontent.com/61984474/76240262-375e4300-6233-11ea-9345-4da5042bf83c.png)
![Screen_3](https://user-images.githubusercontent.com/61984474/76240268-39c09d00-6233-11ea-9f25-1aec30f98459.png)
![Screen_4](https://user-images.githubusercontent.com/61984474/76240270-3cbb8d80-6233-11ea-9190-410636e78ecf.png)

**Comment by KoBeWi** [comment] 2020-03-09 19:10
Related to #32002 probably.

**Comment by LeD95** [comment] 2020-03-11 15:56
> Related to #32002 probably.

Sounds the same, aside from restarting godot not fixing it. Might be another issue underneath defining whether it persists or not.

**Comment by Calinou** [comment] 2020-04-09 07:34
Duplicate of #32002.

**Closed by Calinou** 2020-04-09 07:34 UTC
Labels: bug, topic:editor
