### ISSUE TITLE
Monitors tab in the editor debugger has ".0" for int properties

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#99114] opened 2024-11-12 10:56 UTC
### Tested versions

Reproducible in latest 4.4

### System information

Godot v4.4.dev (ec6a1c0e7) - Pop!_OS 22.04 LTS on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 threads)

### Issue description

![image](https://github.com/user-attachments/assets/f6eca5e8-0ed1-4d1d-9a0e-c21a1d5d80ae)

### Steps to reproduce

Open the part of the editor UI I've shown and run the project so the numbers show.

### Minimal reproduction project (MRP)

N/A

**Comment by MewPurPur** [comment] 2024-11-12 10:59
This isn't an issue in current 4.3

@KoBeWi

**Comment by KoBeWi** [comment] 2024-11-12 11:11
Duplicate of #99000

**Closed by KoBeWi** 2024-11-12 11:11 UTC
