### ISSUE TITLE
Segmentation fault on built mono version with a C# script as Autoload Singleton

### ISSUE THREAD

**Issue by Rumpunzel** [godotengine/godot#36789] opened 2020-03-04 12:29 UTC
**Godot version:** 3.2 mono

**OS/device including version:** Ubuntu 18.04

**Issue description:** The build Godot crashes with a segmentation fault when running a game with a C# script as Autoload Singleton. The easy workaround is to put the script on a node and set that as Singleton instead.

**Comment by Calinou** [comment] 2020-03-04 12:54
Duplicate of #35547.

**Closed by Calinou** 2020-03-04 12:54 UTC
