### ISSUE TITLE
Export Button Bug In Project Tab Options [GAE, Godot Android Editor]

### ISSUE THREAD

**Issue by AhmadZairin** [godotengine/godot#77441] opened 2023-05-24 14:59 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Android 10, AArch64 Processor rev 2 (aarch64), 64-bit & 4 x Kryo 260 (A53) & 4 x Kryo 260 (A73), Qualcomm Adreno (TM) 610, OpenGL ES 3.2

### Issue description

https://github.com/godotengine/godot/assets/83836349/0a99ee50-4fc3-4808-98da-6d991fd21ae5

This is a video link that uses Google Drive if the GitHub video can't be played: https://drive.google.com/file/d/16_8-6yMu8zrzMPogTV74GsIetj9Du_0v/view?usp=drivesdk

There is a bug on screens with 720x1600 resolution, namely a bug in the project options section for export where the export button disappears somewhere or maybe sinks to the bottom when you want to export to the Android platform, which prevents me from exporting it to tpz/zip format because of the button. It passes through the screen limiter of my smartphone

### Steps to reproduce

For the next update, please change the size of the tab, if the tab reaches the screen size limit, make it so that the tab size does not hit the screen border which will remove some buttons

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-05-24 15:07
Duplicate of #73130

**Closed** 2023-05-24 15:09 UTC
