### ISSUE TITLE
The new 2D glowing is Confusing!

### ISSUE THREAD

**Issue by 3booodpro** [godotengine/godot#73134] opened 2023-02-11 23:31 UTC
### Godot version

4.0.rc1

### System information

Windows 10, Forward+, GTX 1660 Super

### Issue description

Specific Glowing is gone.. :(

in Godot 3.5 to use the glowing is very easy, All you have to do is adding a WorldEnvironmet Node and then:
![image](https://user-images.githubusercontent.com/78119395/218278800-1ed04780-402d-4ed2-b3bb-e084cefde005.png)
make its settings like this, Now all you have to do is change the RAW Modulate for any node to make it glow, Like this:
![image](https://user-images.githubusercontent.com/78119395/218278857-c8a3745d-0fcb-46c6-b120-1bb29ae74914.png)
or even lines if you want:
![image](https://user-images.githubusercontent.com/78119395/218278887-4ff59731-4d31-4df8-bcc7-f80b8c663dde.png)

Now moving to Godot 4.0.rc1.. Its Harder for some reasons, We start with adding a WorldEnvironment Node and then:
![image](https://user-images.githubusercontent.com/78119395/218284605-3349afe5-dea5-4b45-90a2-2ba3ec872eca.png)
But as you can see its not working:
![image](https://user-images.githubusercontent.com/78119395/218285055-a9c855b2-248d-4701-a3cc-6e5ff012f85e.png)
I did tweak the settings a little bit:
![image](https://user-images.githubusercontent.com/78119395/218285077-20cf6dd0-cf7c-4fcc-ae84-e8c60fa9e222.png)
as you can see now its working for the Sprites, Now I will test it on the Lines:
![image](https://user-images.githubusercontent.com/78119395/218285206-9e741e9d-fd00-4ad4-b715-0c8709d0f108.png)
Its not working.. So I tweaked the settings again.. Like This:
![image](https://user-images.githubusercontent.com/78119395/218285236-81f4690b-e0ce-4e67-a88c-486252bb8040.png)
Now Its working, but there's a problem:
![image](https://user-images.githubusercontent.com/78119395/218285268-4f6a3eac-f70e-4005-a44c-bd3af229e395.png)
as you can see, Its making everything glowing even though I don't want it to be glowing, And no matter what I change in the settings its not fixed ,I wish you can make it like the old one so we can be specific to what we want to be glowing and what doesn't.

### Steps to reproduce

Add the World Environment and tweak the settings like what I wrote above.

### Minimal reproduction project

[Glowing 3.5.zip](https://github.com/godotengine/godot/files/10714938/Glowing.3.5.zip)
[Glowing 4.0.rc1.zip](https://github.com/godotengine/godot/files/10714940/Glowing.4.0.rc1.zip)

**Comment by Calinou** [comment] 2023-02-11 23:50
Duplicate of https://github.com/godotengine/godot/issues/62110.

**Closed by Calinou** 2023-02-11 23:50 UTC
