### ISSUE TITLE
Cannot to destroy the light in code while destroying the node2d.

### ISSUE THREAD

**Issue by jegor377** [godotengine/godot#7405] opened 2017-01-01 02:50 UTC
**Operating system or device - Godot version:**
Godot official 2.1 stable version and Windows 10 Pro.

**Issue description** (what happened, and what was expected):
I wanted to remove the loaded node2D which had the light2d in it by code and the light did not remove. There are two scenes (Levels) and I change them in my main screen scene by removing the last scene from the node2d and loading, adding new scene from next level.

**Steps to reproduce:**
Create scene with Node2D as the first node with name "World" and then create light in it. After that create another scene with Node and attach a script to this node and create node2d in it with name "Level". In the script, if the "Level" has the "World" node then get_node("Level/World").queue_free() and load the "World" from another scene.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2017-01-02 10:40
Uhm, I can't really understand what you mean, can you either put up a minimal example project or explain it better? Thanks.

**Comment by DualMatrix** [comment] 2018-09-15 00:01
I could not reproduce this in master

**Comment by akien-mga** [comment] 2018-09-15 00:03
Thanks for testing, closing.

**Closed by akien-mga** 2018-09-15 00:03 UTC
Labels: bug, topic:core
