### ISSUE TITLE
Find in files doesnt search for built-in scripts

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#52694] opened 2021-09-15 09:52 UTC
### Godot version

3.3.4 beta-1

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

Yesterday I just had a very cumbersome situtation:

I was trying to find a code where when the user clicks, the zombies follow him, but I didnt remember where I placed it, I tried in many ways to search for related code in the `Search->Find in files` but it didnt gave any result! I was getting crazy because it didnt makes sense! Then I searched in the Tree and foud the **built-in script** with the code I was searching for!

So, why doesnt Find in files doesnt work with **built-in scripts**? There's a special reason?

### Steps to reproduce

* Create a built-in script
* Try to find some code there

### Minimal reproduction project

N/a

**Comment by KoBeWi** [comment] 2021-09-15 10:14
Duplicate of #49629

**Closed by KoBeWi** 2021-09-15 10:14 UTC
