### ISSUE TITLE
Still can't open solution in Visual Studio for mac in Godot 4 beta-4

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#68267] opened 2022-11-04 19:06 UTC
### Godot version

Godot 4 beta 4

### System information

Mac os 13 2.3 GHz Dual-Core Intel Core i5 Intel Iris Plus Graphics 640 1536 MB

### Issue description

Still can't open solution in Visual Studio for mac. I get this error:
<img width="359" alt="Screenshot 2022-11-04 at 20 55 46" src="https://user-images.githubusercontent.com/104303630/200055767-9ed2eba6-71bf-4ea7-a7ae-b191b33ad1ef.png">

### Steps to reproduce

Open the project in visual studio

**Comment by Calinou** [comment] 2022-11-04 19:32
Duplicate of https://github.com/godotengine/godot/issues/67029. Please don't open new issues for issues you've already reported previously :slightly_smiling_face:

**Closed by Calinou** 2022-11-04 19:32 UTC
