### ISSUE TITLE
Light Mask render layers not working

### ISSUE THREAD

**Issue by cr98** [godotengine/godot#43047] opened 2020-10-24 10:06 UTC
**Godot version:** 
3.2.3

**OS/device including version:**
OS Windows 10 - ryzen 3 cpu - rx550 2GB gpu, GLES3

**Issue description:**
Light2D Node
only layer one works other layers don't work so can't have different lights affecting different nodes(sprites, texture rects, etc)
lights only work when other nodes are assigned to layer 1

**Steps to reproduce:**
1. On a new scene create a 2DNode
2. Add Sprite Node
3.  Add a Light2D node
4. place light2D over the sprite node
5. Under visibility menu in the inspector assign both Sprite and light2D nodes to a light mask
    layer other than the first one, don't forget to assign boths nodes to the same layer eg: layer 3
    see light not working, test the same with layer 1.

**Minimal reproduction project:**
[lights_layers_issue_tests.zip](https://github.com/godotengine/godot/files/5432691/lights_layers_issue_tests.zip)

**Comment by Calinou** [comment] 2020-10-24 12:11
Duplicate of https://github.com/godotengine/godot/issues/29612.

**Closed by Calinou** 2020-10-24 12:11 UTC

**Comment by cr98** [comment] 2020-10-24 22:37
> Duplicate of #29612.

I don't think it's a duplicate the bug referenced there is different, the bug I am refering to is that only light mask render layer 1 works the others do nothing.

**Comment by cr98** [comment] 2020-10-25 03:04
> > Duplicate of #29612.
> 
> I don't think it's a duplicate the bug referenced there is different, the bug I am refering to is that only light mask render layer 1 works the others do nothing.

ok nevermind I was confused it's not the Light2D light mask layer that affects other nodes is the item cull mask layer in the range property of the Light2D node. nodes that need to be affected do need to be set in light mask layer property which it's a bit confusing(at least for me), you can't match light mask layer with light mask layer. it is item cull mask layer with light mask layer
