### ISSUE TITLE
Thread finished signal

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9339] opened 2017-06-24 02:27 UTC
Instead of having to poll a thread to see if it is finished, it would be very handy to have a signal emited when the thread is finished.

**Comment by kubecz3k** [comment] 2018-04-03 11:28
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by supagu** [comment] 2018-04-07 10:05
this would still be a great feature to have!

**Comment by Toshiwoz** [comment] 2018-06-25 20:09
@kubecz3k this is not a bug, but a feature request.
It would be useful, maybe someone will pick this up?

**Comment by GlaDOSik** [comment] 2018-07-07 17:06
Agree, this would be a pretty good feature.

**Comment by Zylann** [comment] 2018-11-10 17:37
This would be useful, in addition to a fix for #7235

**Comment by akien-mga** [comment] 2020-05-26 14:06
According to @reduz in https://github.com/godotengine/godot/pull/34862#issuecomment-634040529, this would not be a good idea as signals are not thread-safe, and only the main thread would receive the signal.

As such I'll close this. In the eventuality that we'd have thread-safe signals in the future, this can be re-assessed, but it should then be reopened as a proposal on the new [godot-proposals](https://github.com/godotengine/godot-proposals) repository.

**Closed by akien-mga** 2020-05-26 14:06 UTC
Labels: feature proposal, topic:core
