### ISSUE TITLE
Getting unnecessary 'Parent Busy' warning with Animation Player in 3.4.5

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#66048] opened 2022-09-18 13:32 UTC
### Godot version

3.4.5 stable

### System information

Windows 10, 2x RTX 2070 Super, AMD 3700x

### Issue description

I am trying to add animation to sprites using animation player. However, the editor throws a warning saying:

"Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead."

I am not even using any script, which indicates that there is some problem with the Animation Player itself. I tried searching online about this problem, I came across a few suggestions about adding a call_deferred code to the script. I even tried doing that, but the error remained. I even tried changing the Method Call Mode of the Animation Player, but that too didn't get rid of the error.

In previous versions, this error was not there. I am attaching the zip file of the minimum reproduction of the project.

### Steps to reproduce

File has been attached.

### Minimal reproduction project

[AA DeleteGodot.zip](https://github.com/godotengine/godot/files/9594063/AA.DeleteGodot.zip)

**Comment by ajk2196** [comment] 2022-09-19 14:36
@Calinou please look into this.

**Comment by akien-mga** [comment] 2022-09-19 14:43
Please don't mention specific contributors to look at your issues. They all have plenty enough to deal with on their own terms.

I had a look at your minimal reproduction project and I can't reproduce the issue, neither in 3.4.5-stable nor in 3.5-stable.

The error should happen when you `add_child()` a node at a time which is not supported, it's usually a valid error. There's indeed no script nor animation code trigger in your MRP that would make this bug happen so I'm not sure why you would see it on that project.

**Comment by ajk2196** [comment] 2022-09-20 03:53
I know and I am sorry for direct mentioning. Please atleast attend my issue, atleast add a tag or something so that I can know that it has been taken up. I was worried that my issue won't be taken up because it went to second page due to newly reported issues, and all other issues above and below me were getting comments / showing some progress.

However, coming back to the main topic of this issue, here is a video that should be helpful I think.

https://user-images.githubusercontent.com/90527174/191163757-2864f2de-bbb9-4b46-89b2-1f37a29c244a.mp4

**Comment by pi-hottie** [comment] 2022-10-06 14:18
I have the same issue. And it happens when there is AnimationPlayer on the active scene in the editor.

https://user-images.githubusercontent.com/115164711/194336346-6509fe08-bfde-4ea5-a019-daa37feac369.mp4

**Comment by pi-hottie** [comment] 2022-10-06 14:32
I noticed that the error appears even when the editor just loses focus, if the active scene in the editor has AnimationPlayer. 
So the problem is reproduced only if the option "Save On Focus Loss" is set in the editor settings

**Comment by ajk2196** [comment] 2022-10-07 15:02
Yeah I had that setting 'on' too. I hope that turning it off would solve the problem. I would have checked it, but deleted the entire project out of frustration caused by this error.

**Comment by Calinou** [comment] 2022-10-07 16:43
Duplicate of https://github.com/godotengine/godot/issues/59666.

**Closed by Calinou** 2022-10-07 16:43 UTC
Labels: topic:editor, needs testing, topic:animation
