### ISSUE TITLE
Scene  > Double Click on Node Icon not working

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#52596] opened 2021-09-12 10:03 UTC
### Godot version

v4.0.dev.calinou [5f69218ed]

### System information

Linux Mint 20.2, Vulkan, Nvidia GeForce 950 

### Issue description

Previously, when the user _double-clicked_ on the node _icon_ on the Scene, this node _was framed_ and selected in the main view. Now the rename command was simply called.

### Steps to reproduce

Create and select any displayed node in Scene. Double-click at this node.

**Comment by Calinou** [comment] 2021-09-12 16:30
@AntohaRDNS Does this work correctly in 3.3.3 or 3.4 beta4?

**Comment by jmb462** [comment] 2021-09-25 18:16
Works correctly in 3.3.3 and with lastest 3.x branch.
I confirm that it doesn't work any more in master branch.

**Comment by CakHuri** [comment] 2021-10-12 07:03
I can't reproduce this using https://github.com/CakHuri/godot/commit/f9aec342dcd51d65c5970dd395e3c7a66cac446c

**Comment by AntohaRDNS** [comment] 2021-10-31 12:24
@Calinou  It work correctly in 3.3.4 stable
it does not work at any 4.0 build

**Comment by AntohaRDNS** [comment] 2022-04-02 18:33
problem still exist in - v4.0.alpha.calinou [48ed0400b]

**Comment by KoBeWi** [comment] 2022-04-21 22:04
Can't reproduce in f4b0c7a
![godot windows tools 64_MSpDxgXGmK](https://user-images.githubusercontent.com/2223172/164559239-63d31524-e0c9-4a68-ac5b-13f14629b812.gif)
Unless the issue is about something else?

**Comment by Mickeon** [comment] 2022-09-05 21:20
Cannot reproduce this issue in v4.0.alpha.custom_build [00fa4e23e]

**Comment by KoBeWi** [comment] 2022-09-14 22:15
Given no further confirmation, it's probably fine to close this. Comment if you can still reproduce (and preferably attach a video)

**Closed by KoBeWi** 2022-09-14 22:15 UTC
Labels: bug, topic:editor, confirmed, regression
