### ISSUE TITLE
Godot 3.3 C# Linux Export System List produces incorrect results

### ISSUE THREAD

**Issue by Holo74** [godotengine/godot#48858] opened 2021-05-19 19:08 UTC
**Godot version:**
Godot 3.3

**OS/device including version:**
Linux, GLES3

**Issue description:**
C# exported variables using System.Collection.Generic.List<(enum)> is filling incorrectly when running.

1. Create new project
2. Create new c# script
3. Create enum in script of any name
4. export a System.Collection.Generic List of the enum type
5. Fill enum in the inspector
6. Output the list using GD.print
[Crashing.zip](https://github.com/godotengine/godot/files/6511082/Crashing.zip)

**Comment by Calinou** [comment] 2021-05-19 19:14
Duplicate of https://github.com/godotengine/godot/issues/42926.

**Closed by Calinou** 2021-05-19 19:14 UTC
