### ISSUE TITLE
Control anchoring is incorrect if camera zoom is set

### ISSUE THREAD

**Issue by xdeadmonkx** [godotengine/godot#9659] opened 2017-07-15 20:40 UTC
**Operating system or device - Godot version:**
Windows 8.1, Godot 3.0

**Issue description:**
If camera zoom is other than 1, then root control anchor breaks

**Steps to reproduce:**
Set main camera zoom to 0.5
Make control (fullscreen will be better) with anchor - right | bottom
Change game window size with hands when playing
See that control moves out of window

**Comment by reduz** [comment] 2017-08-29 12:16
@groud Does this still happen in your rewrite?

**Comment by groud** [comment] 2017-08-29 12:34
Where should I change the "main camera" zoom ?

**Comment by bojidar-bg** [comment] 2017-08-29 13:25
Assuming that's a 2D camera, you need a Camera2D node.

**Comment by groud** [comment] 2017-08-29 13:36
Ok I think I spotted a bug anyway, maybe related to original issue: you cannot anchor a control to a camera2d node, while it works with the default viewport. 

Steps to reproduce:
- Add a camera2d node
- Add a control panel node as a child of the camera2d
Results: anchors cannot be moved to the right/bottom side of the camera view

**Comment by akien-mga** [comment] 2018-01-09 16:30
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment] 2018-09-05 16:48
I am not sure whether this is worth fixing, given using those together is not intended, I will be closing this as wontfix. If anyone wants to give a try and the fix it not too hacky, maybe.

**Closed by reduz** 2018-09-05 16:48 UTC
Labels: bug, topic:core
