### ISSUE TITLE
Continuous Collision Detection does nothing

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27654] opened 2019-04-03 19:16 UTC
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Studying a little, mainly based on [this video](https://youtu.be/7_nKOET6zwI), I realized that is not easy to calculate a precise collision.
But I saw that there is a [continuous collision detection](https://docs.godotengine.org/uk/latest/classes/class_rigidbody.html#class-rigidbody-property-continuous-cd) option, which theoretically might make a difference, but not. 
Where this option would be effective?

![image](https://user-images.githubusercontent.com/11199752/55506254-57e94a80-562b-11e9-8d5d-d3d65a0f66de.png)

![](https://cdn.discordapp.com/attachments/212250894228652034/562057944204836884/c.gif)

**Steps to reproduce:**
1) Open tha attached project
2) Press F6 (current scene)
3) Turn off / on the "continuous cd" option for the RigidBody an no difference is shown in the collision.

**Minimal reproduction project:**
[teste.zip](https://github.com/godotengine/godot/files/3040366/teste.zip)

**Comment by Calinou** [comment] 2019-04-03 20:05
Duplicate of https://github.com/godotengine/godot/issues/9071.

**Closed by Calinou** 2019-04-03 20:05 UTC
