### ISSUE TITLE
"Use External" doesn't work on placeholder GLTF materials

### ISSUE THREAD

**Issue by Skywolf285** [godotengine/godot#82964] opened 2023-10-07 13:22 UTC
### Godot version

Godot_v4.2-dev6_linux

### System information

Pop!_OS 22.04 LTS x86_64 

### Issue description

When your import a GLTF scene from Blender and have the materials export as "Placeholder" does Godot not allow your to change the material to an external resource when editing the Advanced Import Settings. It lets you set it but the changes are ignored on the imported scene.

When the material is exported as usual ("Export" in Blender) it does work as expected however.

I'm not sure if this is intentional but it's at the very least not desirable for me. If it in intentional the option to assign an external resource shouldn't be possible in the first place though.

### Steps to reproduce

1. Download the minimal reproduction project, extract it and open it in Godot.
2. Observe the two Suzanne models and their respective .glb file. One if export with materials as placeholder and the other had the materials fully exported. Both have their materials set to use "Override_Material.tres" in the Advanced Import Settings.

### Minimal reproduction project

[GLTF Material Override.zip](https://github.com/godotengine/godot/files/12837878/GLTF.Material.Override.zip)

**Comment by fire** [comment] 2023-10-07 16:17
I don’t think it was intentional but this is a new feature so rushing it for 4.2 might be too fast

**Comment by jss2a98aj** [comment] 2023-10-26 01:14
I think this is a duplicate of #64970 
#64903 fixes it, but it unfortunately doesn't look it is getting merged any time soon. I haven't had any issues with custom builds implementing it at least.

**Comment by akien-mga** [comment] 2023-10-26 07:06
- Duplicate of #64970.

**Closed by akien-mga** 2023-10-26 07:06 UTC

**Comment by DriftWare07** [comment] 2024-04-09 23:03
Trying to use external materials on an imported glb corrupted my project.
