### ISSUE TITLE
In Viewport Label is upside down when it is used in Particles2D

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#15436] opened 2018-01-07 10:32 UTC
**Godot version:**
Godot 3
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
 Windows 7-64

[testviewport.zip](https://github.com/godotengine/godot/files/1609680/testviewport.zip)
**Steps to reproduce:**

Add:
Node
->Viewport
->->Label
->Particles2D

In particles2D add default material and add ViewportTexture
Give size to viewport - eg.: 100x100
Add "hello world" in Label
Reduce value to 1 in property Amount in Particles2D

Run

**Comment by eon-s** [comment] 2018-01-07 13:10
Particles material seems to be the same for 2D and 3D, you need to enable VFlip on render target of the viewport for 2D nodes to look correctly when using a ViewportTexture.

**Comment by git2013vb** [comment] 2018-01-07 13:49
It is a workaround?

**Comment by git2013vb** [comment] 2018-01-07 13:54
Btw. I'm not sure if is related  or not but when I open again the project I have this error: 
ERROR: ViewportTexture::get_size: Condition ' !vp ' is true. returned: Size2()
   At: scene\main\viewport.cpp:106

**Comment by eon-s** [comment] 2018-01-07 14:09
Is how to set up viewport textures on 3D materials so I guess is the way to configure the particles materials too.

And I do not get that error, btw (could be related to the label min size if your text changes).

**Comment by git2013vb** [comment] 2018-01-07 14:33
Seems he[Particles2D] lost the connection to viewport... because if i try again to set texture in Particles2D it work again with no errors.
I've attached the example if you want take a look.

Other problems related with this example are:
Text resolution, (seems he lost focus or it is magnified). I'm not sure. I don't have references how it is supposed to work. 
My goal is to show a variable text in particles.. Like player health.
I know I can use animation in label directly but I wish to understand if is possible to do the same with particles with good result.

**Comment by eon-s** [comment] 2018-01-07 14:48
Well, got that error on the editor, it only happens when opening the project with a ViewportTexture set as Particles2D texture, and selecting the Particles2D node, the project runs fine, though.

-------------------

Default font looks terrible, try creating a new dynamic font for the label with a font file, it should be better that way, if not, may be a bug on the font rendering (another issue).

**Comment by git2013vb** [comment] 2018-01-08 10:49
Can I assume this tread define the bug in description?

**Comment by eon-s** [comment] 2018-01-08 12:52
The upside down part is a viewport option, the error is something else, I have seen it on other viewport usage (not only particles).

**Comment by git2013vb** [comment] 2018-01-08 16:59
Why you call it "option"?

...When I wake up in the morning I'm not "upside down"....

When something is wrong we have call it "option" instead to decide to fix it?

Just asking.

**Comment by reduz** [comment] 2018-09-06 16:27
This can only really be fixed in 3.2, as we will have more control with Vulkan and will be able to make sure viewport is always properly upright.

**Comment by git2013vb** [comment] 2018-09-15 11:01
Thanks :)

**Comment by akien-mga** [comment] 2019-11-26 13:42
Closing as it's not a bug per se, it's a normal limitation of the OpenGL implementation that Viewport ends up upside down, so you need to use `v_flip` on the render target as mentioned.

@reduz mentioned that this will be solvable in 4.0 with Vulkan, but since there are various other issues keeping track of Viewport flipping, I'll close this one.

**Closed by akien-mga** 2019-11-26 13:42 UTC
Labels: bug, discussion, topic:rendering
