### ISSUE TITLE
Convert text resources to binary breaks preload in exported games

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#66090] opened 2022-09-19 07:19 UTC
### Godot version

4.0-beta1

### System information

Linux

### Issue description

When exporting with the option "Convert text resources to binary" enabled, preloading converted resources in scripts will not work in the exported version causing a script error.

I believe this is a regression from #65135 which changed the behavior binary conversion.

### Steps to reproduce

- Create a simple project with 2 scenes: `main.tscn` and `side.tscn`.
- Have the `main.tscn` `preload("res://side.tscn")`.
- Export the game.
- Run the exported version.
- `SCRIPT ERROR: Parse Error: Preload file "res://side.tscn" does not exist.`

Now...
- Disable "Convert text resources to binary"
- Export again
- No error.

### Minimal reproduction project

[proj_export_binary.zip](https://github.com/godotengine/godot/files/9596787/proj_export_binary.zip)

**Comment by akien-mga** [comment] 2022-09-19 07:21
See https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1#known-issues ;)

Duplicate of #56343.

**Closed by akien-mga** 2022-09-19 07:21 UTC
Labels: bug, regression, topic:export
