### ISSUE TITLE
Error in CustomMultiplayer Poll

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#51496] opened 2021-08-11 07:29 UTC
### Godot version

3.4 beta3 mono

### System information

Debian 10

### Issue description

I have these errors:
```
E 0:00:50.130   _process_get_node: Invalid packet received. Unabled to find requested cached node.
  <C++ Error>   Condition "!F" is true. Returned: nullptr
  <C++ Source>  core/io/multiplayer_api.cpp:260 @ _process_get_node()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_0_3(IntPtr , IntPtr )()
                MultiplayerAPI.cs:256 @ void Godot.MultiplayerAPI.Poll()()
                Gateway.cs:30 @ void DesertEdge.Singleton.Gateway._Process(Single )()

```

```
E 0:00:50.130   _process_packet: Invalid packet received. Requested node was not found.
  <C++ Error>   Condition "node == nullptr" is true.
  <C++ Source>  core/io/multiplayer_api.cpp:203 @ _process_packet()
  <Stack Trace> :0 @ void Godot.NativeCalls.godot_icall_0_3(IntPtr , IntPtr )()
                MultiplayerAPI.cs:256 @ void Godot.MultiplayerAPI.Poll()()
                Gateway.cs:30 @ void DesertEdge.Singleton.Gateway._Process(Single )()

```

### Steps to reproduce

I make a custom connection, then I connect a peer, then a disconnect the peer, then I try to reconnect another peer.
The error show up when I try to reconnect another peer.
I use this code in _process:

```
     public override void _Process(float delta)
        {
            if (CustomMultiplayer == null)
                return;
            if (!CustomMultiplayer.HasNetworkPeer())
                return;
            CustomMultiplayer.Poll();
        }
```
The error link bring me in "CustomMultiplayer.Poll()" row

### Minimal reproduction project

NA

**Comment by Calinou** [comment] 2021-08-11 15:09
@git2013vb Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by git2013vb** [comment] 2021-08-12 06:36
> @git2013vb Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Its no so simple to make one... I'm still in learning mode :).  Often I can resolve my issues but in this one I don't have enough details to understand where the problem lie. There is a way to show a better stack trace and more verbose log? With more details I can try to make a minimal project.

**Comment by mhilbrunner** [comment] 2021-08-12 07:32
cc @Faless

**Comment by mhilbrunner** [comment] 2022-01-14 00:18
Hey! I couldn't reproduce this issue in testing, but that is likely due to this being difficult to reproduce without more context.
If you can try to break it down to a project that shows the issues, that'd help immensely. If not, maybe talk to us on the Godot Engine chat, there are ways to provide your project privately for debugging purposes.
Note that the latter is quite time intensive on our side, so no promises.
I'm going to close this for now, as it was working fine in my testing. Please ping us for a reopen if there is any additional info!

**Closed by mhilbrunner** 2022-01-14 00:18 UTC
Labels: bug, topic:network
