### ISSUE TITLE
Broken dialogs when MangoHud enabled

### ISSUE THREAD

**Issue by TheJackiMonster** [godotengine/godot#65851] opened 2022-09-15 22:18 UTC
### Godot version

4.0.beta1

### System information

Archlinux, Vulkan, RX 5700, Mesa 22.1.7-1 (RADV)

### Issue description

The dialog from the projects menu to remove missing projects only shows up as black window. The dialog can not be closed as well as the projects window, making the whole application unresponsive.

Looks like the following image:

![image](https://user-images.githubusercontent.com/13867397/190518285-af0a34f8-5686-408d-afc5-7ab4145583d2.png)

Also more information which might be useful: I'm using GNOME as desktop in a Wayland session.

### Steps to reproduce

- Start Godot (4.0 alpha1)
- Click "Remove Missing" (I have two missing projects)
- Get a broken dialog

**Comment by TheJackiMonster** [comment] 2022-09-15 22:21
This issue happens with any dialog I could potentially open from the projects window (about, import, ...). So I assume this is a known issue? If it's a duplicate please link to it for me because I didn't find it searching for something similar. ^^'

**Comment by TheJackiMonster** [comment] 2022-09-15 22:23
Using the `--single-window` parameter seems to work-around the issue. Maybe it's connected to issue #56536.

**Comment by Calinou** [comment] 2022-09-15 23:35
Does 4.0.alpha12 and prior work? If so, this is a duplicate of https://github.com/godotengine/godot/issues/65409.

**Comment by TheJackiMonster** [comment] 2022-09-15 23:45
But it doesn't crash as mentioned as in #65409 or is this still related?

**Comment by TheJackiMonster** [comment] 2022-09-15 23:48
4.0.alpha12 doesn't even get me to the list of projects because a broken dialog opens before they get loaded:

![image](https://user-images.githubusercontent.com/13867397/190527649-50ad8ae4-cc54-4dff-ba0b-d0c5a730deb9.png)

**Comment by TheJackiMonster** [comment] 2022-09-15 23:56
Okay, I think I found the partial cause for the issue. If I disable MangoHud by passing `MANGOHUD=0` when I launch Godot, the issue does not occur anymore. So I would probably adjust the issue lowering priority. It would still be neat if Godot works with MangoHud globally enabled to ease debugging for people.

**Comment by Calinou** [comment] 2022-09-15 23:56
Duplicate of https://github.com/flightlessmango/MangoHud/issues/706.

**Closed by Calinou** 2022-09-15 23:56 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:thirdparty, needs testing
