### ISSUE TITLE
Cannot use relative path to create a scene

### ISSUE THREAD

**Issue by quabug** [godotengine/godot#1265] opened 2015-01-19 04:39 UTC
```
.
├── dir
│   ├── main.gd
│   └── main.xml
└── engine.cfg
```
```
# main.gd
extends Node
func _ready():
	print(load("main.xml"))
	print(load("res://dir/main.xml"))
```
output:
[Object:null]
[PackedScene:505]

**Comment by the-mech** [comment] 2015-01-21 01:54
Correct me if I'm wrong, but isn't that the right behavior?

**Comment by reduz** [comment] 2015-01-21 02:00
it works with preload(), but not with load()

**Comment by akien-mga** [comment] 2015-11-08 15:55
IIUC this is by design, so closing.

**Closed by akien-mga** 2015-11-08 15:55 UTC
Labels: archived, enhancement, topic:gdscript
