### ISSUE TITLE
Unable to get color data from an array of source_color type in shader.

### ISSUE THREAD

**Issue by SneaK1ng** [godotengine/godot#76157] opened 2023-04-17 05:36 UTC
### Godot version

v4.1.dev.custom_build.a7276f1ce

### System information

Win10, AMD 2600, GeForce GTX 1060, Vulkan API 1.3.205

### Issue description

I can't get correct color data from an array of source_color type.
The color data is saved as **Color** in the file:
`shader_parameter/palette = [Color (1, 0, 0, 1), Color (0, 1, 0, 1), Color (0, 0, 1, 1)]`
Shouldn't it be saved as PackedColorArray?

### Steps to reproduce

1.Declare an array of source_color type.
2.Set colors.

### Minimal reproduction project

[shadertest.zip](https://github.com/godotengine/godot/files/11246504/shadertest.zip)

**Comment by SneaK1ng** [comment] 2023-04-17 05:37
May be related to https://github.com/godotengine/godot/issues/76135

**Comment by clayjohn** [comment] 2023-04-17 06:59
Yes, looks like a duplicate of #76135 which will be fixed by https://github.com/godotengine/godot/pull/74937

**Comment by bitsawer** [comment] 2023-04-17 07:11
Not completely fixed by https://github.com/godotengine/godot/pull/74937. That PR will fix some conversions, but the problem here seems to be that the serialized `shader_parameter/palette` does not have the correct type, it loses it somewhere during the saving process. Manually editing the 

`shader_parameter/palette = [Color (1, 0, 0, 1), Color (0, 1, 0, 1), Color (0, 0, 1, 1)]`

into

`shader_parameter/palette = PackedColorArray(1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1)`

fixes things. I checked with a debugger and the type is correct most of the way (PACKED_COLOR_ARRAY), but in the end it is serialized and then loaded as generic Variant::Type::ARRAY containing variant Color objects (which is not the same as PACKED_COLOR_ARRAY), which will not convert properly into a vec4 uniform field (due to Variant conversion rules).

I'll dig in some more and comment later.

**Comment by bitsawer** [comment] 2023-04-17 10:18
Updated https://github.com/godotengine/godot/pull/74937 to fully fix this issue, at least for now.

**Comment by Calinou** [comment] 2023-04-17 10:23
- Duplicate of https://github.com/godotengine/godot/issues/76135.

**Closed by Calinou** 2023-04-17 10:23 UTC
Labels: bug, archived, topic:editor, topic:shaders
