### ISSUE TITLE
The tooltip doesn't close automatically on X11

### ISSUE THREAD

**Issue by Cliear** [godotengine/godot#94739] opened 2024-07-25 12:56 UTC
### Tested versions

Linux 4.3 bata 3

### System information

WSL Version： 2.2.4.0     Kernel Version： 5.15.153.1-2       WSLg Version： 1.0.61          MSRDC Version： 1.2.5326            Direct3D Version： 1.611.1-81528511                         DXCore Version： 10.0.26091.1-240325-1447.ge-release             Windows Version： 10.0.19045.4651

### Issue description

The tooltip can not be closed automatically on Gizmos

### Steps to reproduce

![tooltip_stuck](https://github.com/user-attachments/assets/3ecfe210-0464-4479-b82e-ccd62ab0a140)

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment] 2024-08-18 21:19
This is intended behavior in that particular dropdown. It has automatic closing disabled when choosing options, so that you can check/uncheck multiple gizmos without needing to go through the submenus for every gizmo you wish to toggle.

To close the dropdown, click outside the dropdown or press <kbd>Escape</kbd>.

**Closed by Calinou** 2024-08-18 21:19 UTC
Labels: bug, topic:gui
