### ISSUE TITLE
move_and_slide_with_snap 3D KinematicBody not snapping on slopes

### ISSUE THREAD

**Issue by Jepulisk** [godotengine/godot#38564] opened 2020-05-08 10:30 UTC
Godot_v3.2.2-beta1_win64

I can't seem to get KinematicBody 3D snap onto slopes. Currently testing with 45º slope.

Same issue here but 2D https://github.com/godotengine/godot/issues/26274

I tried the suggestion to set floor_max_angle to 45º or above.

What am I missing here?

Project attached.

[Cortez.zip](https://github.com/godotengine/godot/files/4598414/Cortez.zip)

**Comment by Calinou** [comment] 2020-05-08 12:18
Related to #30777?

**Comment by madmiraal** [comment] 2020-05-08 14:55
Duplicate of #34098?

In addition I've noticed:
1. You're turning snap off when not jumping or falling:
```
	var snap = Vector3()
	if not (jumping or falling):
		snap = Vector3(0, -1, 0)
```

but you're defining falling as moving down:
```
	falling = false
	if velocity.y < 0:
		falling = true
```
which is the case when you're moving down the slope.

2. You're setting the `move_and_slide_with_snap()` `floor_max_angle` to 46° with the slope of your "Mountain" also at 46°. Although this has been fixed with #36079, to make this work at the moment requires the `floor_max_angle` to be greater than the floor.

**Comment by Jepulisk** [comment] 2020-05-08 16:27
The mountain is 45°. After removing falling from snap check

	var snap = Vector3()
	if not jumping:
		snap = Vector3(0, -1, 0)

it still doesn't snap.

Then I swapped the 4 RayShapes which were the "feet" colliders with 1 BoxShape and with that it indeed snaps to the slope. At first I had the feet as a BoxShape but swapped to RayShapes because I don't want the player to slide on slopes but found this https://github.com/godotengine/godot/issues/34117. Now snap works but sliding is happening again (I'll try the fix for that from that thread).

So isn't this a bug with RayShape not snapping just like madmiraal linked https://github.com/godotengine/godot/issues/34098?

**Comment by AttackButton** [comment] 2020-05-21 18:48
Why not set 46º as the default value instead of 45º?

**Comment by madmiraal** [comment] 2020-05-26 14:50
Closing as duplicate of #34098.

**Closed by madmiraal** 2020-05-26 14:50 UTC
