### ISSUE TITLE
Crashes when you start the editor. 3.1 Beta 8

### ISSUE THREAD

**Issue by MGeymer** [godotengine/godot#26647] opened 2019-03-05 16:06 UTC
Godot version: 3.1 Beta 8

OS/device including version: Windows 10 / AMD A8-6410 APU with AMD Radeon R5 Graphics, cores: 4

Issue description: The error is observed starting with Beta 8, when opening a project with GLES2, the editor crashes, there are no errors.

**Comment by akien-mga** [comment] 2019-03-05 16:08
Can you try 3.1 beta 10?

**Comment by Akira1San** [comment] 2019-03-05 16:15
Ive made the same issue, no one saw it :(
link; https://github.com/godotengine/godot/issues/26500

**Comment by MGeymer** [comment] 2019-03-05 17:01
@akien-mga This is observed with beta 8, and in 10 it is present.

**Comment by qarmin** [comment] 2019-03-05 18:08
Can you open it from console to see a log?

**Comment by MGeymer** [comment] 2019-03-05 18:55
@qarmin Yes, I did it. but it was not anything unusual.
```
Editing project: C:/Users/Sergey/Documents/Godot/testt (C:::Users::Sergey::Documents::Godot::testt)
OpenGL ES 2.0 Renderer: AMD Radeon (TM) R5 M330

C:\Program Files\Godot Engine>fixed path: C:/Users/Sergey/Documents/Godot/testt/.import
unit: C:\
```

**Comment by akien-mga** [comment] 2019-03-05 22:31
Duplicate of #26500.

**Closed by akien-mga** 2019-03-05 22:31 UTC
