### ISSUE TITLE
Adding a Property Track for to the Animation Player should only show exported properties

### ISSUE THREAD

**Issue by zilluss** [godotengine/godot#84156] opened 2023-10-29 17:33 UTC
### Godot version

4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Property Tracks list all properties of a node. For custom nodes, this includes private properties that aren't relevant to the Animation Track and clutter the list. Properties that aren't exported shouldn't be listed.

### Steps to reproduce

Add a property track for a custom node in the Animation Player. The list of properties will include all properties, including ones that aren't exported.

### Minimal reproduction project

N/A

**Comment by zilluss** [comment] 2023-11-03 12:00
Just checked, it only happens with tool scripts (Minimal test project attached).
[Uploading AnimationProperties.zip…]()

**Comment by KoBeWi** [comment] 2023-11-03 12:06
The project did not upload, but I was able to reproduce.

I suspect this line:
https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/editor/property_selector.cpp#L188
I didn't test, but I think `@tool` will add `PROPERTY_USAGE_SCRIPT_VARIABLE` to the properties. I wonder if it's needed here.

**Comment by akien-mga** [comment] 2023-11-20 16:38
Closing as duplicate of #85139 which has an MRP.

**Closed by akien-mga** 2023-11-20 16:38 UTC
Labels: bug, topic:editor, confirmed, usability
