### ISSUE TITLE
File name hint provided when a scene is saved is not displayed/given

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#81343] opened 2023-09-05 14:35 UTC
### Godot version

4.2.dev.4

### System information

Windows 11

### Issue description

When you save a scene, then in the file save dialog the file name is provided based on the root node.
e.g., 
if root node is `SomeName` then typically based on the settings the hint will be `some_name.tscn`

This is no more available as part of 4.2.dev.4, but working in 4.1.1

### Steps to reproduce

- Create a Project
- Create a Scene
- Add a node and name something like `SomeName`
- Now Save the Scene
Expected to provide a hint like in 4.1.1 as `some_name.tscn`, but it will not show in the save dialog.

### Minimal reproduction project

N.A

**Comment by YuriSizov** [comment] 2023-09-05 14:39
Thanks for opening a bug report. This is a duplicate of https://github.com/godotengine/godot/issues/81225, so I'm going to close this to consolidate the discussion.

**Closed by YuriSizov** 2023-09-05 14:39 UTC
