### ISSUE TITLE
Gridmap node glitch for a grid-base game mechanic

### ISSUE THREAD

**Issue by TairoyZone** [godotengine/godot#84420] opened 2023-11-03 16:53 UTC
### Godot version

4.1.3 stable

### System information

Windows 11 - Godot v4.1.3.stable - Vulkan (Forward+) - dedicated

### Issue description

I have this mechanic for placing towers; however, it seems like the tower placer object is often getting buried in the ground. Now, I'm not a smart person to dissect and identify the underlying issue 100%. I really have no clue how this happens. All I know is that using a Gridmap is wonky, in some cases it's really bad and in some cases it's not so bad but it still there making my game janky. I tried plunging into solving this for a long while, and for a long time, nobody has been willing to help with this issue since I posted it in the community. This bug report is my last resort since I believe that it's more likely a Godot bug. Please help; I need this fix T_T.

My issue recorded:
https://github.com/godotengine/godot/assets/132976014/b51548d0-e062-4b6d-a3de-ac29a8e06971

How I used raycast from camera together with local_to_map() and map_to_local() functions:
![BaseLevel gd](https://github.com/godotengine/godot/assets/132976014/c4a96e2b-8dba-4266-aabb-289f605784d3)

### Steps to reproduce

It's really easy:
1. Create a level using Gridmap node with collision layer and collision mask

2. Have a Camera3D, Box Mesh(2,2,2 size), Lighting to the level. Use this function for creating a raycast from a camera:

```gdscript
func _cast_ray_from_mouse() -> Dictionary:
	var mouse_position := get_viewport().get_mouse_position()
	var from: Vector3 = player_camera.project_ray_origin(mouse_position)
	var to: Vector3 = from + player_camera.project_ray_normal(mouse_position) * RAY_LENGTH
	var space_state := get_world_3d().direct_space_state
	var query = PhysicsRayQueryParameters3D.create(
		from, to, 0xFFFFFFFF, [ self, white_queen ]
		)
	return space_state.intersect_ray(query)
```
3. For having a draggable object, update the  Box Mesh like this:

```gdscript
func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		_update_preview()

func _update_preview() -> void:
	var result := _cast_ray_from_mouse()
	if result.is_empty():
		box_mesh.hide()
	else:
		_cell = grid_map.local_to_map(result.position)
		box_mesh.global_transform.origin = grid_map.map_to_local(_cell)
		box_mesh.show()
```

4. You must wobble the mouse slowly since the flicker is a bit subtle to detect and its only in a very specific area. You will discover that the Box Mesh is flickering rapidly on the surface at certain places of the level made by a Gridmap.

### Minimal reproduction project

Minimal reproduction project:
[BugRecreation.zip](https://github.com/godotengine/godot/files/13252768/BugRecreation.zip)

You can see that the box mesh is flickering here:
https://github.com/godotengine/godot/assets/132976014/1fea917c-a0c3-46ad-ac8d-8625b05deb44

**Comment by kleonc** [comment] 2023-11-03 20:43
That's expectable behavior, the ray collision point can include floating point error. If you'd print the resulting position you'd see you can get a position a little below the top of the hitted collider. E.g.:
```gdscript
...
print("%.6v" % [result.position])
...
```
```
...
(-18.450174, 2.000000, -13.334887)
(-18.488651, 2.000000, -13.270485)
(-18.527081, 1.999998, -13.206186)
(-18.579418, 2.000000, -13.206186)
(-18.527081, 1.999998, -13.206186)
(-18.474743, 2.000000, -13.206186)
(-18.527081, 1.999998, -13.206186)
(-18.527081, 1.999998, -13.206186)
(-18.527081, 1.999998, -13.206186)
(-18.579418, 2.000000, -13.206186)
...
```
For these `y = 1.999998` the `grid_map.local_to_map(result.position)` would return the cell coordinates below the ones you're expecting. Don't expect you'll always get the exact edge point.

Anyway, since you want to obtain the cell **above** the cell hitted by the ray you should be using the `result.normal` to obtain a position above the intersection point. E.g.:
```gdscript
...
elif result.collider == grid_map:
  #var cell_hitted = grid_map.local_to_map(result.position - result.normal * 0.5 * grid_map.cell_size)
  var cell_in_front = grid_map.local_to_map(result.position + result.normal * 0.5 * grid_map.cell_size)
  ...
```

---

Closing as not a bug (floating point errors are expectable for ray intersection point).

**Closed by kleonc** 2023-11-03 20:43 UTC
Labels: topic:editor, needs testing, topic:3d

**Comment by TairoyZone** [comment] 2023-11-04 09:17
What an amateur assumption on my part. That's a neat trick to know ^_^ Thanks a bunch!.. I appreciate you for shedding a light on this.
