### ISSUE TITLE
DirectionalLight's shadows doesn't work with orthogonal cameras

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21462] opened 2018-08-26 22:00 UTC
**Godot version:**
 db55d8a

**Issue description:**
**Perspective mode:**
![screenshot at 2018-08-26 18-57-19](https://user-images.githubusercontent.com/30739239/44633468-3a9c2180-a962-11e8-83bc-b2c91c996026.png)

**Orthogonal mode:**
![screenshot at 2018-08-26 18-57-52](https://user-images.githubusercontent.com/30739239/44633471-4687e380-a962-11e8-8ed3-68ff1d561d45.png)

**Comment by Bauxitedev** [comment] 2018-08-27 09:51
For me it only breaks in the editor when you press 5 on the numpad to switch to otrhographic mode. If you place a orthographic camera and then click the "preview" button on the camera it does seem to work.

E.g. here's an orthographic shadow:
![img](https://user-images.githubusercontent.com/31383123/44653579-7a5d1a80-a9ef-11e8-8b8d-cb6a3ab667ea.png)

**Comment by reduz** [comment] 2018-09-07 23:09
This is not really bug, but more like the fact that PSSM (2 and 4 splits) are pointless in orthographic view.
Try using ortographic shadow instead.

**Comment by reduz** [comment] 2018-09-07 23:09
I wish usability of this could be improved, maybe shadow should be forced to ortographic?

**Comment by YeldhamDev** [comment] 2018-09-08 03:28
@reduz Orthogonal shadow does nothing.

**Comment by akien-mga** [comment] 2020-01-08 09:59
Also affects SpotLight, see example project from #28878: https://github.com/godotengine/godot/files/3176735/FF.zip

**Comment by tom-jk** [comment] 2020-07-22 15:34
Testing with MRP: [21462.zip](https://github.com/godotengine/godot/files/4960891/21462.zip)

Can reproduce in 3.1.alpha2, 3.1.1, 3.1.2, 3.2, 3.2.1 (stables)
Can't reproduce in 3.2.2.stable.

Appears to be resolved.

**Comment by akien-mga** [comment] 2020-07-22 15:37
Thanks, closing.

**Closed by akien-mga** 2020-07-22 15:37 UTC
Labels: bug, topic:rendering

**Comment by AvikArefin** [comment] 2023-10-24 13:06
![image](https://github.com/godotengine/godot/assets/86384286/494a126a-fd3c-4875-ba1a-a18dad04a775)
![image](https://github.com/godotengine/godot/assets/86384286/6f392ca9-cb6f-49c3-a717-d499b4fe2bce)
The problem seems to have reappeared in Godot 4.1.2, I did not test this in any other version of godot.
