### ISSUE TITLE
FileSystem pane doesn't detect mouse has left it and starts to scroll

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#24864] opened 2019-01-09 13:18 UTC
**Godot version:**
3.1 Mono 64-Bit beta

**OS/device including version:**
Windows 10 NVidia GTX1050

**Issue description:**
Dragging a sprite asset from my assets folder onto the Sprite node texture field causes the asset folder to start scrolling in the direction I am moving the mouse almost as if the FileSystem pane hasn't recognised the mouse has left it's area.

**Steps to reproduce:**
Create a folder. Add enough assets to cause a scroll bar to appear in the FileSystem pane. Add a Sprite node and drag an asset, probably from bottom of list, onto the Texture field.

**Comment by qarmin** [comment] 2019-01-10 06:56
This is same issue as #23375?

**Comment by groud** [comment] 2019-01-10 07:18
Duplicate of #23375

**Closed** 2019-01-10 07:18 UTC
Labels: archived
