### ISSUE TITLE
Audio category is selectable in project settings and display some parameters

### ISSUE THREAD

**Issue by Chlipouni** [godotengine/godot#66588] opened 2022-09-29 08:59 UTC
### Godot version

v4.0.beta1

### System information

Windows 10

### Issue description

In project settings dialog box, the "Audio" category is selectable and displays some parameter values.
Some of them don't have the same value than those displayed in sub-categories.

This issue doesn't happen for all other categories.

### Steps to reproduce

- Open the "Project Settings" dialog box.
- Activate the "Advanced Settings" view.
- Select the "Audio" category by clicking the label.

**Comment by jmb462** [comment] 2022-09-29 11:00
I cannot reproduce this issue with v4.0.beta1.official [20d667284]
![audio](https://user-images.githubusercontent.com/3649998/193014582-65b619fb-9425-42d9-9053-a1a442d1d24d.gif)

**Comment by akien-mga** [comment] 2022-09-29 11:39
It might be due to having old (pre beta 1) project settings in your `editor_settings-4.tres` config which are still shown (as they could be user-generated settings) instead of being removed as obsolete.

I'm pretty sure we have an issue about this but I couldn't find it.

**Comment by Chlipouni** [comment] 2022-09-29 14:37
I deleted the "editor_settings-4.tres" file and restarted Godot editor, the issue was still here.

I tried the following actions :
- Selected the "Action" category
- Reseted the default value for each visible parameter
- Restarted Godot Editor
- The issue disapeared and the "Action" category is no more selectable

So as you said, maybe an old issue from one of the 4.0 alpha releases I used before the beta.

**Comment by Calinou** [comment] 2022-12-26 17:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/3526 (same cause).

**Closed by Calinou** 2022-12-26 17:19 UTC
Labels: topic:editor, needs testing
