### ISSUE TITLE
string.capitalize different output in C# and GDScript

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot#60051] opened 2022-04-09 05:05 UTC
### Godot version

3.4.4

### System information

Windows 10

### Issue description

The C# version of string.Capitilize() has incorrect output. Which is different from the documentation and GDScript.

```
Problem: "capitalize camelCase mixed_with_underscores".Capitalize();
Expected: Capitalize Camel Case Mixed With Underscores
Received: Capitalize Camelcase Mixed With Underscores
```

Maybe can have something to do with [#28748](https://github.com/godotengine/godot/issues/28748)

### Steps to reproduce

Write this in a _Ready function:

"capitalize camelCase mixed_with_underscores".Capitalize();

### Minimal reproduction project

Not necessary?

**Comment by raulsntos** [comment] 2022-04-09 18:34
Duplicate of #56941.
Fixed by #57076 but only in master, not in 3.x, probably because it breaks compatibility.

**Comment by Calinou** [comment] 2022-04-09 23:10
> Fixed by https://github.com/godotengine/godot/pull/57076 but only in master, not in 3.x, probably because it's a breaking compatibility change.

The different behavior is probably worth documenting in `3.x`. Also, could it be made opt-in in `3.x` (e.g. by passing an optional `new_capitalize=true` argument to `.Capitalize()` in C#)?

**Comment by akien-mga** [comment] 2022-04-12 07:31
I think this can be cherrypicked.

Duplicate of #56941

**Closed by akien-mga** 2022-04-12 07:31 UTC
Labels: documentation, topic:dotnet
