### ISSUE TITLE
Editor settings are reset to defaults when restarting the editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6056] opened 2016-08-06 12:10 UTC
Tested on Godot 2.1 rc1 and rc2, Windows 10 64 bits

Editor settings are reset to defaults if the editor is restarted without modifying them during the session.

This is very annoying because I have a scene containing a lot of data, and using Ctrl+S takes a few seconds of freeze to complete. Given that I use Ctrl+S a lot more when coding than editing the scene, I remapped Ctrl+S so it saves only the script instead of the scene. But it still freezes because the script is reloaded and also the scene for some reason. So I disabled auto-reload of scripts as my last hope. But after restarting twice the nightmare comes back :s

Repro:
1) Open the editor
2) Go to Editor Settings, Text Editor, uncheck "Auto-reload scripts on change" (or any checkbox, works with all of them I guess)
3) Close the editor
4) Open the editor, open Editor Settings, notice the options are remembered correctly
5) Don't modify them, close the editor
6) Open the editor again, open Editor Settings, notice the options are reverted to defaults.

**Comment by mefihl** [comment] 2016-08-11 18:19
Confirmed on Windows10, Godot 2.1 stable.

**Comment by kubecz3k** [comment] 2016-08-12 14:47
Also confirming on Ubuntu 16.04

**Comment by hetdegon** [comment] 2016-09-17 07:54
I seem to be continuously losing text editor settings (mostly everything else I keep in defaults), stuff like colors, line spacing, open dominant script on scene change and such.
At first I thought it was a stray .xml config from a previous version, but after deleting it, settings seemed to save after closing and opening again. But later I updated Godot to current git and settings were lost again. I assume it's related to this issue? It's kind of odd because I can test it out, confirm settings save, but the next day they'll be gone again for no apparent reason.

**Comment by volzhs** [comment] 2016-10-24 13:23
And losing custom android user key and password for debug in EditorSettings > Android section too.

**Comment by volzhs** [comment] 2016-10-30 16:11
It doesn't happen when run in QT with debug. so weird. :(

**Closed** 2016-11-11 13:17 UTC
Labels: bug, confirmed, topic:editor
