### ISSUE TITLE
Vulkan: Error messages related to missing libraries printed when starting Godot

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#36185] opened 2020-02-13 17:48 UTC
**Godot version:** Git https://github.com/godotengine/godot/commit/5c3944e7da9ca72077cb5348fadc86347904838c

**OS/device including version:** Fedora 31 (64-bit), NVIDIA 440.44, GeForce GTX 1080

**Issue description:** Two error messages are printed when starting the project manager, but they seem to be harmless. They don't affect editor rendering or execution in any way.

```text
ERROR: ERROR : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS32

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 0x87a8440

   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:127)
ERROR: ERROR : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 0x87a8440

   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:127)
```

Some information about the Vulkan libraries present on the system:

```text
❯ ls /usr/lib{,64}/libvulkan* -l
lrwxrwxrwx   20 root 29 Jan  4:20 /usr/lib/libvulkan.so.1 -> libvulkan.so.1.2.131
lrwxrwxrwx   20 root 29 Jan  4:20 /usr/lib64/libvulkan.so.1 -> libvulkan.so.1.2.131
.rwxr-xr-x 362k root 29 Jan  4:20 /usr/lib/libvulkan.so.1.2.131
.rwxr-xr-x 358k root 29 Jan  4:20 /usr/lib64/libvulkan.so.1.2.131
.rwxr-xr-x 6.3M root 18 Dec  2019 /usr/lib/libvulkan_intel.so
.rwxr-xr-x 6.1M root 18 Dec  2019 /usr/lib64/libvulkan_intel.so
.rwxr-xr-x 5.5M root 18 Dec  2019 /usr/lib/libvulkan_radeon.so
.rwxr-xr-x 5.4M root 18 Dec  2019 /usr/lib64/libvulkan_radeon.so

❯ file /usr/lib{,64}/libvulkan*
/usr/lib/libvulkan_intel.so:     ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=815d3d0cd4894d1eace895a70f874718f8bffdd3, stripped
/usr/lib/libvulkan_radeon.so:    ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=9773cb8c00e9510a2b0dea9441fdefdcba3a70ed, stripped
/usr/lib/libvulkan.so.1:         symbolic link to libvulkan.so.1.2.131
/usr/lib/libvulkan.so.1.2.131:   ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=70e8a5f37f15c7d7682bdb1dd77b63b127b71910, stripped
/usr/lib64/libvulkan_intel.so:   ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9acdc1de68dac97c2dffa53d82f1cb132262b049, stripped
/usr/lib64/libvulkan_radeon.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e9e6ebabc0ee89837662b9ec9f068fb046cf4ba8, stripped
/usr/lib64/libvulkan.so.1:       symbolic link to libvulkan.so.1.2.131
/usr/lib64/libvulkan.so.1.2.131: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fff0deb5a06f6b33f050021bc8cf2c90a7aca2c7, stripped
```

I don't know why it's trying to load 32-bit libraries from `/usr/lib`. (On Fedora, 64-bit libraries are in `/usr/lib64`.)

**Steps to reproduce:** Run Godot on a system with a NVIDIA graphics card on Linux.

**Comment by quantmint** [comment] 2020-02-13 17:54
This also happens with an intel gpu on arch linux.

**Comment by bruvzg** [comment] 2020-02-13 18:13
It's loader issue and already reported to the upstream: https://github.com/KhronosGroup/Vulkan-Loader/issues/262

**Comment by akien-mga** [comment] 2020-02-13 20:09
Indeed duplicate of https://github.com/KhronosGroup/Vulkan-Loader/issues/262, nothing we can do on our end.

**Comment by akien-mga** [comment] 2020-02-22 14:33
Actually we can hide the error, so I'll do that.

**Closed** 2020-02-22 15:28 UTC
Labels: bug, platform:linuxbsd, topic:rendering
