### ISSUE TITLE
Exported array of Node type cannot be assigned values

### ISSUE THREAD

**Issue by tlitookilakin** [godotengine/godot#70370] opened 2022-12-20 21:12 UTC
### Godot version

4.0-beta9

### System information

Windows 10

### Issue description

Attempting to assign Nodes to array items in arrays exported with Node types fails. It correctly appears as a node-typed array in the inspector, and you can add new indices to the array. It's just the assignment of nodes that seems to have no effect. 

### Steps to reproduce

1. Create a script which exports a typed array that is Node or any subclass of Node.
2. Add an item in the inspector
3. Click "Assign" in the inspector
4. Select a node & click "OK"

Nothing happens and the value remains unset.

Can be replicated with the following line of code:
`@export var my_nodes: Array[Control]`

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2022-12-20 21:16
Duplicate of #62916

**Closed by KoBeWi** 2022-12-20 21:16 UTC
