### ISSUE TITLE
Wrong Normals when importing Mesh

### ISSUE THREAD

**Issue by DeFYzz** [godotengine/godot#29904] opened 2019-06-19 16:29 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 AMD RX 480

**Issue description:**
Wrong Lighting when importing mesh. Looks like Normals are flipped
Triangles which should be lit aren't lit and vice versa

**Steps to reproduce:**
- Import .obj models from pack: https://opengameart.org/content/nature-kit
- Add simple OmniLight and observe wrong lighting

**Comment by Llcoolsouder** [comment] 2019-06-23 01:37
I just tried to reproduce this. It looks like the side of the model opposite the light is what is getting lit up. Is this what you're referring to?
![image](https://user-images.githubusercontent.com/15933766/59970492-ac6ada80-9535-11e9-9b7a-5a3020b2dee4.png)
![image](https://user-images.githubusercontent.com/15933766/59970499-d6240180-9535-11e9-898a-48a5a6f8f5ed.png)

**Comment by DeFYzz** [comment] 2019-06-23 11:45
Yes that's exactly the issue

**Comment by Llcoolsouder** [comment] 2019-07-08 21:35
@DeFYzz have you seen this same issue with other objs other than the one from this repo?

**Comment by Llcoolsouder** [comment] 2019-07-08 22:29
I did a quick test to confirm that this was in fact a problem with the models and not an issue with the implementation of omnilight. I changed the color of the light to red so that it is easier to see its effects.

![image](https://user-images.githubusercontent.com/15933766/60846545-c818e680-a1ad-11e9-8491-6bd613949cef.png)

The monkey is just the standard mesh from Blender. Notice that the light behaves as expected, whereas both the flower and bamboo models have opposite lighting.

I think the easiest way to solve your problem would be to simply edit the models themselves. See the [Blender docs](https://docs.blender.org/manual/en/latest/modeling/meshes/editing/normals.html#flip-direction) for instructions on flipping the normals of the models. Hope that helps.

**Comment by akien-mga** [comment] 2019-07-09 06:09
Thanks for testing, closing then as it's not an engine issue.

**Closed by akien-mga** 2019-07-09 06:09 UTC
Labels: bug, topic:rendering
