### ISSUE TITLE
_init with parameters breaks when used with scene tree editor

### ISSUE THREAD

**Issue by ishax-kos** [godotengine/godot#75920] opened 2023-04-11 04:01 UTC
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I was exploring whether I should instantiate a number of slot node from an exported count parameter, or collect the manually added nodes in said parameter. I had created an _init function to properly initialize these slots, when my static typing seemed to hit this error. 

### Steps to reproduce

The problem is demonstrated in the provided project with an assert. Note that the problem goes away if there are no parameters in `_init` for the `test_class.gd` script. Additionally, a cpp exception is emitted.

### Minimal reproduction project

[Bug_report_class_name.zip](https://github.com/godotengine/godot/files/11196254/Bug_report_class_name.zip)

**Comment by gotnospirit** [comment] 2023-04-11 04:48
https://godotengine.org/qa/4786/how-to-pass-parameters-when-instantiating-a-node?show=4827#c4827

**Comment by dalexeev** [comment] 2023-04-11 06:54
You should not create node classes with required constructor parameters, they cannot be instantiated from the scene editor. Also, when adding a node from code, `MyNodeClass.new()` will only create the root of the scene, not the entire scene. Instead, you can add a static method that creates a node or instantiates a scene.

```gdscript
extends Node
class_name MyNodeClass

var param: String

static func create(p_param: String) -> MyNodeClass:
    var packed_scene: PackedScene = load("res://my_node_class.tscn")
    var node: MyNodeClass = packed_scene.instantiate()
    node.param = p_param
    return node
```

Usage:

```gdscript
var node := MyNodeClass.create("test")
add_child(node)
```

Related:

* #67059
* godotengine/godot-proposals#1513
* godotengine/godot-proposals#1935
* godotengine/godot-proposals#5899

I also remember that there was a proposal/comment about adding the ability to specify node/resource parameters when creating in the editor (but IMO this unnecessarily complicates things).

**Comment by Calinou** [comment] 2023-05-03 21:31
- Duplicate of https://github.com/godotengine/godot-proposals/issues/5899.

**Closed by Calinou** 2023-05-03 21:31 UTC
