### ISSUE TITLE
Imported Obj Surface Material won't render during runtime

### ISSUE THREAD

**Issue by mojoyup** [godotengine/godot#53138] opened 2021-09-27 16:49 UTC
### Godot version

Godot Engine v3.3.3.stable.custom_build - https://godotengine.org

### System information

Windows 10 64bit

### Issue description

I import my obj with textures from sketchup where textures are converted to png. I create a MeshInstance, and assign the obj to it. The textures are recognized in the editor but when I play a scene/runtime, they are not rendered. 

### Steps to reproduce

Create a model in any sketchup and paint colors or textures to it. Group it and export it as obj anywhere. Load it into Godot and assign it to a MeshInstance. Run. Sometimes, after import it automatically has transparent on also. Check to see it is not transparent. (maybe another bug idk yet). 

### Minimal reproduction project

[textureRenderBug.zip](https://github.com/godotengine/godot/files/7238037/textureRenderBug.zip)

**Comment by Calinou** [comment] 2021-09-27 17:38
Duplicate of https://github.com/godotengine/godot/issues/27647.

**Closed by Calinou** 2021-09-27 17:38 UTC
