### ISSUE TITLE
Crash on start-up 4.2.beta1

### ISSUE THREAD

**Issue by mrfisty** [godotengine/godot#83288] opened 2023-10-13 18:34 UTC
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Windows 11 - Godot v4.2.beta1.official - Bulkan (Forward+) dedicated 

### Issue description

Updated to latest beta release and now my project crashes upon opening.  I started it via CMD to see any error messages as no logs are being created and it reads:

_WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported._

![image](https://github.com/godotengine/godot/assets/4332336/bad72c60-c03a-434a-94dd-a6510aa95e5f)

I've had Blender installed for years. I've never set the path and it's worked fine with previous versions of Godot. I did try setting the path by opening a project that doesn't crash, but that did not fix the issue.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by RedMser** [comment] 2023-10-13 18:42
Try running with `--verbose`

**Comment by akien-mga** [comment] 2023-10-13 18:58
The warning is unrelated to your crash, you can ignore it.

**Comment by mrfisty** [comment] 2023-10-13 19:14
Hi, this is what CMD outputs when using '--verbose'. 


TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2246567268384
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2246567268384
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2246567268384
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
Vulkan devices:
  #0: NVIDIA NVIDIA GeForce RTX 3070 Ti - Supported, Discrete
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti
Optional extension VK_KHR_incremental_present not found
Optional extension VK_GOOGLE_display_timing not found
- Vulkan Variable Rate Shading supported:
  Pipeline fragment shading rate
  Primitive fragment shading rate
  Attachment fragment shading rate, min texel size: (16, 16), max texel size: (16, 16)
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  min size: 32
  max size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR, STAGE_TASK_NV, STAGE_MESH_NV
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
Startup PSO cache (3.0 MiB)
Using "wintab" pen tablet driver...
Creating VMA small objects pool for memory type index 1
Shader 'CanvasSdfShaderRD' (group 0) SHA256: 19a470b1e616a12a3d3701be069c386717f206be92c51159db0a6d8cdd1d2104
Shader 'SkeletonShaderRD' (group 0) SHA256: 684509d9973d69d9dee6ec20f5c9b24c0627add0ccee12088bbee0f8988bb945
Shader 'SortShaderRD' (group 0) SHA256: 465ec103a8d81f3883db2e8c9499aafe9b8731a110e8b49080ba2ff5f4a202f3
Shader 'ParticlesShaderRD' (group 0) SHA256: 10e2ccaac616575ea6654b4303261ebf73b8a8a3a9ed09a102ee2f8f5d44e61e
Shader 'ParticlesCopyShaderRD' (group 0) SHA256: a170455c426fcc450a59e242dfa16d22924303ea33b4dc876930ca998b0ad610
Shader 'CanvasShaderRD' (group 0) SHA256: faead27fda54026c7107e93d331d7a6d2cc8002f54bfe9172c055679b8f6e669
Shader 'CanvasOcclusionShaderRD' (group 0) SHA256: 425e078a5ee529bf6b4cd7e7b0d89af2f549695f40b02e845cf9560d352522a6
Shader 'ClusterRenderShaderRD' (group 0) SHA256: 4cd3e92e3cffa57d206e464efc7ea28e827e92c5a9ae137f7c75ca87d7ba442b
Shader 'ClusterStoreShaderRD' (group 0) SHA256: c1eb4aec9f453d53b2881f2ecda92787b4cb45531a2a445829a7978c36f36fb3
Shader 'ClusterDebugShaderRD' (group 0) SHA256: aa84986bc15effd60a5463a82a5f67e6284f65a198e62078fbe4f2ba3dca2ebb
Shader 'SceneForwardClusteredShaderRD' (group 0) SHA256: c8c1b9831024adc3cc957841a49e9b9f0b5bec5b7af0787740b469f0ff81202d
Shader 'SceneForwardClusteredShaderRD' (group 1) SHA256: afb958db87c6216c3d8acd0d9f03413090062668e1a24dc09125f850202967f1
Shader 'SceneForwardClusteredShaderRD' (group 2) SHA256: db60ae0c89c1745bc02efd85f0b6d556a6bbe9c65f9c8f06d4cd06cf20943808
Shader 'SceneForwardClusteredShaderRD' (group 3) SHA256: 5ef6d0cefbc0c2107cd377651f95f5eb20ce1ecb27a3206fb774262cdfc9104e
Shader 'ResolveShaderRD' (group 0) SHA256: 7836d7e35d8688ea560577753c58f1e759b9a7d2fe5262f016788e8b228dbb67
Shader 'TaaResolveShaderRD' (group 0) SHA256: 16e93673c0db0b0eb562c43c08210ab90a5867632be8686a41f9bd64a818c49e
Shader 'Fsr2DepthClipPassShaderRD' (group 0) SHA256: ae5fc42edbc6a8b9c774ca0cbbe7284015f9ce75669cf71b0ec2c9a41669548a
Shader 'Fsr2ReconstructPreviousDepthPassShaderRD' (group 0) SHA256: 7dca27908eb39edaeed1970b20197657db9925a33987835fb5a6e5dd9c7f16f4
Shader 'Fsr2LockPassShaderRD' (group 0) SHA256: 341e9947ddf8390d94ccd6a407eb58cb9b0e46a1262f5e964fff5aa23228f3f6
Shader 'Fsr2AccumulatePassShaderRD' (group 0) SHA256: 8a63f96a25891f5e622e1f7936b8162c68214a95861bf9dd18c460253b4506d7
Shader 'Fsr2RcasPassShaderRD' (group 0) SHA256: ecb54cc06f46e85318b42db355d0d49304f796e462651800f6ac606eb3a3041c
Shader 'Fsr2ComputeLuminancePyramidPassShaderRD' (group 0) SHA256: 84c4fe9671446a4f9e0b8c58910f0ad724b1cf69ce32e63a8ff59e2b18e4751b
Shader 'Fsr2AutogenReactivePassShaderRD' (group 0) SHA256: 6e19495f2960448228b97623af618f455eb8544eec3cc35a70696952b4fd4f12
Shader 'Fsr2TcrAutogenPassShaderRD' (group 0) SHA256: 25adc653d2cf9b8307282b8ec330d4355ae880a81aff8d5b96b9690cd3b10aa3
Shader 'SsEffectsDownsampleShaderRD' (group 0) SHA256: 72f2eb835ee5dbc0bd632b78f4ab0027ca06baf11a1d04ebd84d89ea22bbcabf
Shader 'SsilShaderRD' (group 0) SHA256: 59a5cf65b331518cc04a80171b75f143fd2d77628d8cd7734c042407f88ade02
Shader 'SsilImportanceMapShaderRD' (group 0) SHA256: 17ae956468943aea6e41afa262e5da2fa65db6a04bb6c4a1f6d63d897c63bae1
Shader 'SsilBlurShaderRD' (group 0) SHA256: da688c3e965c3a70cf38f65cf0c0e3c9413aa06d7b6b348ab644187afd8cc4a8
Shader 'SsilInterleaveShaderRD' (group 0) SHA256: 4d33815c1faa7f5eaa4bf5a8deb5a600f050591d440db47e7e7ad1e4d8bdde9f
Shader 'SsaoShaderRD' (group 0) SHA256: 946a8381257638b7cf6e8785939b3f682101f3d56a596277fac808454cfa2e8d
Shader 'SsaoImportanceMapShaderRD' (group 0) SHA256: a765e3da0253e4dae42e74fe7c0852fbc31d4b93e2e7fba8424e4fe39dc5ed05
Shader 'SsaoBlurShaderRD' (group 0) SHA256: a3d80c0e60344b3c739c0f5a7c904e72442376f7f22dcc5976a5378ba28d6338
Shader 'SsaoInterleaveShaderRD' (group 0) SHA256: 804ba4a16ededae7f978dd8a424ab3131c1260d4240c64d6f4a7b3fab963cfc6
Shader 'ScreenSpaceReflectionScaleShaderRD' (group 0) SHA256: ef80fec1bb8dbdacb749c7ad402691c62ccc0fb830514b2a6ada0ef191895634
Shader 'ScreenSpaceReflectionShaderRD' (group 0) SHA256: 8c27020f89df6f7f0c2e58055d61c44703a522a65a2526488bc24c36be1e4dca
Shader 'ScreenSpaceReflectionFilterShaderRD' (group 0) SHA256: add1bcc0731d324df4c23544e72b9545d5e0d74bbe9c1544d01d15ad1298544a
Shader 'SubsurfaceScatteringShaderRD' (group 0) SHA256: 4f74c8a760d0ffb67e3b4aa8fe112b857a14b7f55cb9179d66a7847928f8e46dShader 'SkyShaderRD' (group 0) SHA256: 78483971dc8f23774efdbbe46479a1f7d3e7eeb0924f928983f68011db6a9441
Shader 'VoxelGiShaderRD' (group 0) SHA256: b5c895c0bfca93d2b302bba44e0cba7203a61baf2a198d4f305971e959daec96
Shader 'VoxelGiDebugShaderRD' (group 0) SHA256: 6f7d9c393c2ec23b63d3129313dc238f7af14b1e456c64cc2efa3f37196fcf79
Shader 'SdfgiPreprocessShaderRD' (group 0) SHA256: ff3ba42f1982928b54ad02e2bb7a6e0ca73ac56958dc992fee2134e8a92a687e
Shader 'SdfgiDirectLightShaderRD' (group 0) SHA256: 5a314c91b3c9f64cce4adf06181597129db1e80d33da31a5857e89a9f54c96c9
Shader 'SdfgiIntegrateShaderRD' (group 0) SHA256: dbdcd4124d3cea0afd75b4fe763ee66ef33483857b9a114a9a62324c699f475b
Shader 'GiShaderRD' (group 0) SHA256: dccf64938d62ac9f5a78c73525cc3b877ceba0f1ba71e6b0fb526eddbf134366
Shader 'SdfgiDebugShaderRD' (group 0) SHA256: bead9ecd11e73e3d37d9af851d23e4accb8c2be3bf3e957b8c79b69262daef10
Shader 'SdfgiDebugProbesShaderRD' (group 0) SHA256: c88765d403dbf6058e476267ff698ec06276a70c9940bece8f16694cad6e50ae
Shader 'VolumetricFogShaderRD' (group 0) SHA256: 22516bbccd1830060f93fe23cca3e76054dc8f2ef8a647a3f095f26116426df7
Shader 'VolumetricFogProcessShaderRD' (group 0) SHA256: 62c6fd1fc9038dd99a93b5d3fe081b7dd84a615c3c1c2862ea0359859fea4327Shader 'BokehDofShaderRD' (group 0) SHA256: 5b3a0f34bdb29346ef46cfa60ed17378839ce768419482127362609ee15b5c1e
Shader 'CopyShaderRD' (group 0) SHA256: 316d4eeecb096e102230ffa50ff36a9abdcd0163280f0f598f59c5bd5dd97fe5
Shader 'CopyToFbShaderRD' (group 0) SHA256: ce49a0cdc11756f3d1f6f4e2429bcda4e59e93cfc737e3ad8a3b46a2a84bbb7a
Shader 'CubeToDpShaderRD' (group 0) SHA256: 41c03f51c4235645900d2a1a8740b2d678cd576307eca344786376cc2e74a5ea
Shader 'CubemapDownsamplerShaderRD' (group 0) SHA256: 6cb0ee8a2040f91cdc25e5311ba8137d0d1457eb974961e7b405917796b2e236
Shader 'CubemapFilterShaderRD' (group 0) SHA256: 44b645975926d09b8a236a5bd80ab51aeff2edc375ba67d7763f316f893a7af5
Shader 'CubemapRoughnessShaderRD' (group 0) SHA256: 67522746c0ca6b7a1c09eb1be178c1b27e7d5795d31d02c5305662c07c91ac0f
Shader 'SpecularMergeShaderRD' (group 0) SHA256: 0d406a7ee959c7e880648210a643712c2b4f8f1e0486249f3e22d26ae338d2b4
Shader 'ShadowFrustumShaderRD' (group 0) SHA256: 405cda681a6d4875773b28363f343b6adbfc203d924d4519f776e9043ba45fef
Shader 'MotionVectorsShaderRD' (group 0) SHA256: 24f0475364690efb767a3ed59719122f6cfca08e40407cb4b173e4bb7241f3ba
Shader 'LuminanceReduceShaderRD' (group 0) SHA256: d8c7e0c84b1e408293a022c030cd135aa372657b0d13df6c31557bfe90fc93bf
Shader 'TonemapShaderRD' (group 0) SHA256: 0022f8bae0f8e095a94107880254a0134bdb3b3746e7106981d7ada6fe0e237c
Shader 'VrsShaderRD' (group 0) SHA256: 60c02bcc8f2ad12e21b87f2c3cb7f1608c66a6ef946559f96e8b42a9d15d7aca
Shader 'FsrUpscaleShaderRD' (group 0) SHA256: ccdec7b960843d6785de079cfdc57868e9ca0d515f4382f95547c2a941e8c1fa
Shader 'BlitShaderRD' (group 0) SHA256: d880d7f9e74b46b4b627f11310cab301d50cc3ce7ad8dc7735971dbfe68332a5
WASAPI: Activated output_device using IAudioClient3 interface
WASAPI: wFormatTag = 3
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 16000
WASAPI: nAvgBytesPerSec = 128000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 0
WASAPI: mix_rate = 16000
WASAPI: fundamental_period_frames = 160
WASAPI: min_period_frames = 160
WASAPI: max_period_frames = 160
WASAPI: selected a period frame size of 160
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 160 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4024205830
EDITOR API HASH: 3626030836
EditorSettings: Load OK!
Loaded system CA certificates
Creating VMA small objects pool for memory type index 3

**Comment by akien-mga** [comment] 2023-10-13 19:22
This may not be the cause of the crash, but you seem to have invalid Vulkan layers for GalaxyOverlayVkLayer installed, which may conflict with Godot's usage of Vulkan.

**Comment by mrfisty** [comment] 2023-10-13 19:56
I do have GOG installed (Good Old Games). They do seem to use some Vulkan layer called Galaxy. 

I tried disabling the overlay in the GOG settings, and I even deleted that Vulkan layer in the Registry Editor (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers), but it's still crashing. 

```
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Vulkan devices:
  #0: NVIDIA NVIDIA GeForce RTX 3070 Ti - Supported, Discrete
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti
Optional extension VK_KHR_incremental_present not found
Optional extension VK_GOOGLE_display_timing not found
- Vulkan Variable Rate Shading supported:
  Pipeline fragment shading rate
  Primitive fragment shading rate
  Attachment fragment shading rate, min texel size: (16, 16), max texel size: (16, 16)
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  min size: 32
  max size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR, STAGE_TASK_NV, STAGE_MESH_NV
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
Startup PSO cache (3.0 MiB)
Using "wintab" pen tablet driver...
Creating VMA small objects pool for memory type index 1
Shader 'CanvasSdfShaderRD' (group 0) SHA256: 19a470b1e616a12a3d3701be069c386717f206be92c51159db0a6d8cdd1d2104
Shader 'SkeletonShaderRD' (group 0) SHA256: 684509d9973d69d9dee6ec20f5c9b24c0627add0ccee12088bbee0f8988bb945
Shader 'SortShaderRD' (group 0) SHA256: 465ec103a8d81f3883db2e8c9499aafe9b8731a110e8b49080ba2ff5f4a202f3
Shader 'ParticlesShaderRD' (group 0) SHA256: 10e2ccaac616575ea6654b4303261ebf73b8a8a3a9ed09a102ee2f8f5d44e61e
Shader 'ParticlesCopyShaderRD' (group 0) SHA256: a170455c426fcc450a59e242dfa16d22924303ea33b4dc876930ca998b0ad610
Shader 'CanvasShaderRD' (group 0) SHA256: faead27fda54026c7107e93d331d7a6d2cc8002f54bfe9172c055679b8f6e669
Shader 'CanvasOcclusionShaderRD' (group 0) SHA256: 425e078a5ee529bf6b4cd7e7b0d89af2f549695f40b02e845cf9560d352522a6
Shader 'ClusterRenderShaderRD' (group 0) SHA256: 4cd3e92e3cffa57d206e464efc7ea28e827e92c5a9ae137f7c75ca87d7ba442b
Shader 'ClusterStoreShaderRD' (group 0) SHA256: c1eb4aec9f453d53b2881f2ecda92787b4cb45531a2a445829a7978c36f36fb3
Shader 'ClusterDebugShaderRD' (group 0) SHA256: aa84986bc15effd60a5463a82a5f67e6284f65a198e62078fbe4f2ba3dca2ebb
Shader 'SceneForwardClusteredShaderRD' (group 0) SHA256: c8c1b9831024adc3cc957841a49e9b9f0b5bec5b7af0787740b469f0ff81202d
Shader 'SceneForwardClusteredShaderRD' (group 1) SHA256: afb958db87c6216c3d8acd0d9f03413090062668e1a24dc09125f850202967f1
Shader 'SceneForwardClusteredShaderRD' (group 2) SHA256: db60ae0c89c1745bc02efd85f0b6d556a6bbe9c65f9c8f06d4cd06cf20943808
Shader 'SceneForwardClusteredShaderRD' (group 3) SHA256: 5ef6d0cefbc0c2107cd377651f95f5eb20ce1ecb27a3206fb774262cdfc9104e
Shader 'ResolveShaderRD' (group 0) SHA256: 7836d7e35d8688ea560577753c58f1e759b9a7d2fe5262f016788e8b228dbb67
Shader 'TaaResolveShaderRD' (group 0) SHA256: 16e93673c0db0b0eb562c43c08210ab90a5867632be8686a41f9bd64a818c49e
Shader 'Fsr2DepthClipPassShaderRD' (group 0) SHA256: ae5fc42edbc6a8b9c774ca0cbbe7284015f9ce75669cf71b0ec2c9a41669548a
Shader 'Fsr2ReconstructPreviousDepthPassShaderRD' (group 0) SHA256: 7dca27908eb39edaeed1970b20197657db9925a33987835fb5a6e5dd9c7f16f4
Shader 'Fsr2LockPassShaderRD' (group 0) SHA256: 341e9947ddf8390d94ccd6a407eb58cb9b0e46a1262f5e964fff5aa23228f3f6
Shader 'Fsr2AccumulatePassShaderRD' (group 0) SHA256: 8a63f96a25891f5e622e1f7936b8162c68214a95861bf9dd18c460253b4506d7
Shader 'Fsr2RcasPassShaderRD' (group 0) SHA256: ecb54cc06f46e85318b42db355d0d49304f796e462651800f6ac606eb3a3041c
Shader 'Fsr2ComputeLuminancePyramidPassShaderRD' (group 0) SHA256: 84c4fe9671446a4f9e0b8c58910f0ad724b1cf69ce32e63a8ff59e2b18e4751b
Shader 'Fsr2AutogenReactivePassShaderRD' (group 0) SHA256: 6e19495f2960448228b97623af618f455eb8544eec3cc35a70696952b4fd4f12
Shader 'Fsr2TcrAutogenPassShaderRD' (group 0) SHA256: 25adc653d2cf9b8307282b8ec330d4355ae880a81aff8d5b96b9690cd3b10aa3
Shader 'SsEffectsDownsampleShaderRD' (group 0) SHA256: 72f2eb835ee5dbc0bd632b78f4ab0027ca06baf11a1d04ebd84d89ea22bbcabf
Shader 'SsilShaderRD' (group 0) SHA256: 59a5cf65b331518cc04a80171b75f143fd2d77628d8cd7734c042407f88ade02
Shader 'SsilImportanceMapShaderRD' (group 0) SHA256: 17ae956468943aea6e41afa262e5da2fa65db6a04bb6c4a1f6d63d897c63bae1
Shader 'SsilBlurShaderRD' (group 0) SHA256: da688c3e965c3a70cf38f65cf0c0e3c9413aa06d7b6b348ab644187afd8cc4a8
Shader 'SsilInterleaveShaderRD' (group 0) SHA256: 4d33815c1faa7f5eaa4bf5a8deb5a600f050591d440db47e7e7ad1e4d8bdde9f
Shader 'SsaoShaderRD' (group 0) SHA256: 946a8381257638b7cf6e8785939b3f682101f3d56a596277fac808454cfa2e8d
Shader 'SsaoImportanceMapShaderRD' (group 0) SHA256: a765e3da0253e4dae42e74fe7c0852fbc31d4b93e2e7fba8424e4fe39dc5ed05
Shader 'SsaoBlurShaderRD' (group 0) SHA256: a3d80c0e60344b3c739c0f5a7c904e72442376f7f22dcc5976a5378ba28d6338
Shader 'SsaoInterleaveShaderRD' (group 0) SHA256: 804ba4a16ededae7f978dd8a424ab3131c1260d4240c64d6f4a7b3fab963cfc6
Shader 'ScreenSpaceReflectionScaleShaderRD' (group 0) SHA256: ef80fec1bb8dbdacb749c7ad402691c62ccc0fb830514b2a6ada0ef191895634
Shader 'ScreenSpaceReflectionShaderRD' (group 0) SHA256: 8c27020f89df6f7f0c2e58055d61c44703a522a65a2526488bc24c36be1e4dca
Shader 'ScreenSpaceReflectionFilterShaderRD' (group 0) SHA256: add1bcc0731d324df4c23544e72b9545d5e0d74bbe9c1544d01d15ad1298544a
Shader 'SubsurfaceScatteringShaderRD' (group 0) SHA256: 4f74c8a760d0ffb67e3b4aa8fe112b857a14b7f55cb9179d66a7847928f8e46dShader 'SkyShaderRD' (group 0) SHA256: 78483971dc8f23774efdbbe46479a1f7d3e7eeb0924f928983f68011db6a9441
Shader 'VoxelGiShaderRD' (group 0) SHA256: b5c895c0bfca93d2b302bba44e0cba7203a61baf2a198d4f305971e959daec96
Shader 'VoxelGiDebugShaderRD' (group 0) SHA256: 6f7d9c393c2ec23b63d3129313dc238f7af14b1e456c64cc2efa3f37196fcf79
Shader 'SdfgiPreprocessShaderRD' (group 0) SHA256: ff3ba42f1982928b54ad02e2bb7a6e0ca73ac56958dc992fee2134e8a92a687e
Shader 'SdfgiDirectLightShaderRD' (group 0) SHA256: 5a314c91b3c9f64cce4adf06181597129db1e80d33da31a5857e89a9f54c96c9
Shader 'SdfgiIntegrateShaderRD' (group 0) SHA256: dbdcd4124d3cea0afd75b4fe763ee66ef33483857b9a114a9a62324c699f475b
Shader 'GiShaderRD' (group 0) SHA256: dccf64938d62ac9f5a78c73525cc3b877ceba0f1ba71e6b0fb526eddbf134366
Shader 'SdfgiDebugShaderRD' (group 0) SHA256: bead9ecd11e73e3d37d9af851d23e4accb8c2be3bf3e957b8c79b69262daef10
Shader 'SdfgiDebugProbesShaderRD' (group 0) SHA256: c88765d403dbf6058e476267ff698ec06276a70c9940bece8f16694cad6e50ae
Shader 'VolumetricFogShaderRD' (group 0) SHA256: 22516bbccd1830060f93fe23cca3e76054dc8f2ef8a647a3f095f26116426df7
Shader 'VolumetricFogProcessShaderRD' (group 0) SHA256: 62c6fd1fc9038dd99a93b5d3fe081b7dd84a615c3c1c2862ea0359859fea4327Shader 'BokehDofShaderRD' (group 0) SHA256: 5b3a0f34bdb29346ef46cfa60ed17378839ce768419482127362609ee15b5c1e
Shader 'CopyShaderRD' (group 0) SHA256: 316d4eeecb096e102230ffa50ff36a9abdcd0163280f0f598f59c5bd5dd97fe5
Shader 'CopyToFbShaderRD' (group 0) SHA256: ce49a0cdc11756f3d1f6f4e2429bcda4e59e93cfc737e3ad8a3b46a2a84bbb7a
Shader 'CubeToDpShaderRD' (group 0) SHA256: 41c03f51c4235645900d2a1a8740b2d678cd576307eca344786376cc2e74a5ea
Shader 'CubemapDownsamplerShaderRD' (group 0) SHA256: 6cb0ee8a2040f91cdc25e5311ba8137d0d1457eb974961e7b405917796b2e236
Shader 'CubemapFilterShaderRD' (group 0) SHA256: 44b645975926d09b8a236a5bd80ab51aeff2edc375ba67d7763f316f893a7af5
Shader 'CubemapRoughnessShaderRD' (group 0) SHA256: 67522746c0ca6b7a1c09eb1be178c1b27e7d5795d31d02c5305662c07c91ac0f
Shader 'SpecularMergeShaderRD' (group 0) SHA256: 0d406a7ee959c7e880648210a643712c2b4f8f1e0486249f3e22d26ae338d2b4
Shader 'ShadowFrustumShaderRD' (group 0) SHA256: 405cda681a6d4875773b28363f343b6adbfc203d924d4519f776e9043ba45fef
Shader 'MotionVectorsShaderRD' (group 0) SHA256: 24f0475364690efb767a3ed59719122f6cfca08e40407cb4b173e4bb7241f3ba
Shader 'LuminanceReduceShaderRD' (group 0) SHA256: d8c7e0c84b1e408293a022c030cd135aa372657b0d13df6c31557bfe90fc93bf
Shader 'TonemapShaderRD' (group 0) SHA256: 0022f8bae0f8e095a94107880254a0134bdb3b3746e7106981d7ada6fe0e237c
Shader 'VrsShaderRD' (group 0) SHA256: 60c02bcc8f2ad12e21b87f2c3cb7f1608c66a6ef946559f96e8b42a9d15d7aca
Shader 'FsrUpscaleShaderRD' (group 0) SHA256: ccdec7b960843d6785de079cfdc57868e9ca0d515f4382f95547c2a941e8c1fa
Shader 'BlitShaderRD' (group 0) SHA256: d880d7f9e74b46b4b627f11310cab301d50cc3ce7ad8dc7735971dbfe68332a5
WASAPI: Activated output_device using IAudioClient3 interface
WASAPI: wFormatTag = 3
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 16000
WASAPI: nAvgBytesPerSec = 128000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 0
WASAPI: mix_rate = 16000
WASAPI: fundamental_period_frames = 160
WASAPI: min_period_frames = 160
WASAPI: max_period_frames = 160
WASAPI: selected a period frame size of 160
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 160 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 4024205830
EDITOR API HASH: 3626030836
EditorSettings: Load OK!
Loaded system CA certificates
Creating VMA small objects pool for memory type index 3
```

**Comment by luiscesjr** [comment] 2023-10-17 17:52
I'm also having this similar issue, project won't open in the editor and the last lines are just:

```
WARNING: Upgrading mesh from older surface format. Once saved again (or re-imported), this mesh will be incompatible with earlier versions of Godot.
     at: _fix_surface_compatibility (servers/rendering_server.cpp:2035)
WARNING: Upgrading mesh from older surface format. Once saved again (or re-imported), this mesh will be incompatible with earlier versions of Godot.
     at: _fix_surface_compatibility (servers/rendering_server.cpp:2035)
Loaded system CA certificates
Creating VMA small objects pool for memory type index 3
```

I'll track this issue as well.

**Comment by akien-mga** [comment] 2023-10-30 16:00
If you're using the godot-jolt extension, it's not / was not compatible with Godot 4.2 at the time.

Otherwise there isn't much actionable here without knowing what's in the project.

Do you still have this crash in 4.2-beta3 or later?

**Comment by mrfisty** [comment] 2023-10-30 18:47
I was using godot-jolt with that project so I'll either try removing it or updating to 4.2-beta3 later on and report back.

**Comment by akien-mga** [comment] 2023-10-30 21:50
Then it's a duplicate of a bunch of issues, fixed in godot-jolt by https://github.com/godot-jolt/godot-jolt/pull/640.

**Closed by akien-mga** 2023-10-30 21:50 UTC
Labels: bug, topic:editor, needs testing, crash, regression
