### ISSUE TITLE
Brackets & Square Brackets with apple keyboard on M1 Platform not working

### ISSUE THREAD

**Issue by Marco-MP88** [godotengine/godot#59105] opened 2022-03-13 14:13 UTC
### Godot version

4.0 alpha 4

### System information

Monterey 12.2.1, M1 Pro Apple Silicon

### Issue description

Option + 5 and Option + 6 should do [ ]
Option + 8 and Option + 9 should do { }

In Editor nothing appears.

### Steps to reproduce

Try to type [] or {} in Godot Editor when editing a script

**Comment by Calinou** [comment] 2022-03-13 17:49
Duplicate of https://github.com/godotengine/godot/issues/54303.

**Closed by Calinou** 2022-03-13 17:49 UTC
