### ISSUE TITLE
HTML - Custom Html Shell template strings not replaced

### ISSUE THREAD

**Issue by Dibujaron** [godotengine/godot#43470] opened 2020-11-12 02:27 UTC
**Godot version:** 3.2.2.stable.official

**OS/device including version:** Windows 10

**Issue description:**

When using a custom template, the $-prefixed template strings are not being replaced as expected. Therefore the generated html is unusable (get a json parse error).

**Steps to reproduce:**
- set up an html export
- copy [the default html export template](https://raw.githubusercontent.com/godotengine/godot/master/misc/dist/html/full-size.html) somewhere into your project
- set this file as custom html shell 
- export project
- attempt to open generated html file

**Minimal reproduction project:** Should fail for any project

Thanks,
Dib

**Comment by Faless** [comment] 2020-11-12 06:12
Thanks for reporting this issue.
I can confirm it, the code skip `$VAR` replacing when using the custom shell, which is a different behaviour from the documented one.
I'll fix it, and review the `$VAR` documentation to see if something changed.

**Comment by Faless** [comment] 2020-11-12 06:27
So, the problem is that you are using the default html in the `master` branch, instead of the one in the [`3.2` branch](https://raw.githubusercontent.com/godotengine/godot/3.2/misc/dist/html/full-size.html).
This is a bug in the documentation, which should point to the correct branch.

**Comment by pycbouh** [comment] 2020-11-12 10:12
This documentation, to be precise: https://docs.godotengine.org/en/stable/tutorials/platform/customizing_html5_shell.html

**Comment by Dibujaron** [comment] 2020-11-12 16:33
Ah, fantastic, thanks for quick response, I'll use the other template!

**Comment by Faless** [comment] 2021-03-17 13:13
The custom template has been greatly simplified, and the [new documentation](https://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html) will include the inline HTML template to avoid confusing the user.
The link to the git repository is still there, but should be more or less stable with now.
I'll close this issue as fixed, as the confusion should be gone. Further discussion should probably go in the documentation repository in case.

**Closed** 2021-03-17 13:14 UTC
Labels: bug, confirmed, documentation, platform:html5
