### ISSUE TITLE
Cannot Change Gravity Direction of a Rigidbody

### ISSUE THREAD

**Issue by mjones409** [godotengine/godot#38877] opened 2020-05-20 04:43 UTC
**Godot version:**
Godot_v3.2.1-stable_x11.64
**OS/device including version:**
Debian Linux
**Issue description:**
You can edit the gravity scale field in the rigidbody editor, but that only gives you gravity in the y direction. The field "total_gravity" in the class "PhysicsDirectBodyState" should be editable either directly or with a setter so that you can change gravity in the x and/or z direction as well as the y for that **specific** rigidbody. I have taken to making the "gravity scale" = 0 and implementing my own gravity because total_gravity is read only.
**Steps to reproduce:**
Try to change total_gravity.x or total_gravity.y on a rigidbody.
**Minimal reproduction project:**
A rigidbody with a script attached that extends Rigidbody and has the function "_integerate_forces"

**Comment by Calinou** [comment] 2020-05-20 07:43
cc @AndreaCatania

**Comment by madmiraal** [comment] 2020-05-20 09:16
Gravity, and particularly its direction, is a property of the space not the body. If you want to change the direction of gravity in the game you can use the Project Settings -> Physics -> (2D or 3D) -> Default Gravity Vector or in a particular area using an Area2D or Area -> Gravity Vec.
Gravity scale simply controls how much this body is affected by the space's gravity.
Furthermore, since gravity is just a mass independent force, if you want to apply a force in particular direction to a body, just add the desired force.

**Comment by mjones409** [comment] 2020-05-20 14:59
> 
> 
> Gravity, and particularly its direction, is a property of the space not the body. If you want to change the direction of gravity in the game you can use the Project Settings -> Physics -> (2D or 3D) -> Default Gravity Vector or in a particular area using an Area2D or Area -> Gravity Vec.
> Gravity scale simply controls how much this body is affected by the space's gravity.
> Furthermore, since gravity is just a mass independent force, if you want to apply a force in particular direction to a body, just add the desired force.

The issue is that you have to change the entire space, not just the gravity of one rigidbody. If i want one player's gravity to be in the x and one in the z direction, I need to edit total_gravity or the whole vector3 of the rigidbodys gravity field

**Comment by madmiraal** [comment] 2020-05-21 11:19
@mjones409 The point is that this is not a bug, therefore this issue should be closed. If you think this is a feature that should be implemented in Godot, then you should open a feature proposal [here](https://github.com/godotengine/godot-proposals). That been said, it is unlikely to be considered a valid proposal, because of [point 8](https://github.com/godotengine/godot-proposals#8-can-the-feature-be-worked-around-in-script-with-a-few-lines): you can implement this by using the existing `add_force()` function.

**Comment by Calinou** [comment] 2020-05-21 12:26
Closing per @madmiraal's comment.

**Closed by Calinou** 2020-05-21 12:26 UTC
Labels: enhancement, topic:physics
