### ISSUE TITLE
Godot crashes randomly and takes entire NVIDIA graphics driver with it

### ISSUE THREAD

**Issue by AreebDurrani** [godotengine/godot#75953] opened 2023-04-11 19:57 UTC
### Godot version

Godot Engine v4.0.2.stable.official.7a0977ce2

### System information

Manjaro Linux x86_64, Kernel: 6.2.10-1-MANJARO ,  CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz, GPU: NVIDA GTX 1650, DRIVER: 530.41.03-3, BACKEND: Vulkan

### Issue description

Godot randomly crashes, usually only a few minutes into a session (but sometimes it lasts longer). After the crash, the Godot window remains open but does not respond to anything. The NVIDIA graphics driver is crashed and cannot be utilized by any other application, so the system at this point is using Intel integrated graphics only. Any attempt to kill the process will cause the entire system to freeze in such a way that can only be resolved by holding down the power button to turn off the PC. Attempting to shut down or reboot through the KDE GUI or through the command line will also cause such a freeze to happen.

Error Log:

Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
libspeechd.so.2: cannot open shared object file: No such file or directory
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650
 
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1970)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1698)
ERROR: Can't create a Vulkan window
   at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:5145)
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_set_flag (platform/linuxbsd/x11/display_server_x11.cpp:2320)
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_set_flag (platform/linuxbsd/x11/display_server_x11.cpp:2320)
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_set_flag (platform/linuxbsd/x11/display_server_x11.cpp:2320)
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_set_flag (platform/linuxbsd/x11/display_server_x11.cpp:2320)
ERROR: Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
   at: _make_window (scene/main/window.cpp:521)

### Steps to reproduce

Open any project on this hardware configuration and work for a while until it crashes.

### Minimal reproduction project

N/A, happens with any project.

**Comment by clayjohn** [comment] 2023-04-11 20:17
Duplicate of https://github.com/godotengine/godot/issues/67404

Tracked by https://github.com/godotengine/godot/issues/71929

**Closed by clayjohn** 2023-04-11 20:17 UTC
