### ISSUE TITLE
Color picker UI node moves on it's own when switching between scene tabs.

### ISSUE THREAD

**Issue by 2-3-5-41** [godotengine/godot#77019] opened 2023-05-12 20:25 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows10/11

### Issue description

With a color picker node under a normal control node, it will move slightly every time when switching to the scene. A work around would be just putting the color picker under a layout/container.

### Steps to reproduce

1. new project
2. new Control node scene
3. add color picker node as child
4. switch between that scene and another scene
5. color picker will move to the bottom right slowly with every scene switch.

### Minimal reproduction project

n/a

It'll take the same amount of time to open a zip that it takes to create the project yourself.

**Comment by kleonc** [comment] 2023-05-13 11:07
Duplicate of #62937.

**Closed by kleonc** 2023-05-13 11:07 UTC
