### ISSUE TITLE
Scene script recognizable only one time

### ISSUE THREAD

**Issue by AserYolo** [godotengine/godot#84536] opened 2023-11-06 17:09 UTC
### Godot version

4.1 and above

### System information

Windows 10 Godot's Compatibility mode

### Issue description

I made a small game months ago in godot 4.0 and it has a menu and a credits/end scene. Basically when the game ends you can go back to the menu scene and replay it. Recently thought I was making another small project in version 4.1 and I did the same thing but better this time(added smooth scene transitions and stuff also with an options scene this time) and when I was going back to the main menu from the credits/end scene or even the options scene none of the buttons were working(like play, options, exit and stuff), showing an error that it basically doesn't recognise the script the second time you access that scene. At first I asked for help and tried to solve it but nothing happened. So today I tried my old project which was working and found out that it doesn't work either. Idk if it's really a bug but if you can plz help me out. I will also send some picture that represent the problem between the menu and the options scene. If there is a problem just to my code plz let me know.
![IMG_20231030_160347_edit_4256319614454](https://github.com/godotengine/godot/assets/150061784/ff7a7740-0300-4e80-bb40-f2970fa96692)
![IMG_20231030_171137](https://github.com/godotengine/godot/assets/150061784/546aa3e9-d4e8-42aa-94df-0aa33923b0cc)
![IMG_20231030_171156](https://github.com/godotengine/godot/assets/150061784/71215881-3890-4393-902a-b93a89227459)
![IMG_20231030_172505](https://github.com/godotengine/godot/assets/150061784/3d931459-5709-45a7-a8b4-8d1dfee5d664)
![IMG_20231030_173601_edit_6742043383866](https://github.com/godotengine/godot/assets/150061784/29ef721e-4944-4ab9-bfe2-0665e363d636)
Here is the code on the menu scene:
```gdscript
extends Control

var main_level = preload("res://Levels/main_level.tscn")
var options = preload("res://Ui/options.tscn")

func _ready():
	RenderingServer.set_default_clear_color(Color.DIM_GRAY)

func _on_play_pressed():
	SceneTransition.change_scene(main_level)

func _on_quit_pressed():
	get_tree().quit()

func _on_options_pressed():
	get_tree().change_scene_to_packed(options)
```
The code on the options scene:
```gdscript
extends Control

var menu = preload("res://Ui/main_menu.tscn")

var music_is_playing = true

func _on_adjust_music_pressed():
	if music_is_playing == true:
		BackgroundMusic.pause_music()
		music_is_playing = false
	elif music_is_playing == false:
		BackgroundMusic.resume_music()
		music_is_playing = true

func _on_back_pressed():
	get_tree().change_scene_to_packed(menu)
```

The code on the SceneTransition scene:
```gdscript
extends CanvasLayer

@onready var animation = $AnimationPlayer

var scene_is_transitioning = false

func change_scene(target: PackedScene):
	scene_is_transitioning = true
	animation.play("dissolve")
	await animation.animation_finished
	get_tree().change_scene_to_packed(target)
	animation.play_backwards("dissolve")
	scene_is_transitioning = false
```
And the errors:
```
E 0:00:07:0277   emit_signalp: Error calling from signal 'pressed' to callable: 'MarginContainer::_on_play_pressed': Method not found.
  <C++ Source>   core/object/object.cpp:1082 @ emit_signalp()
E 0:00:07:0890   emit_signalp: Error calling from signal 'pressed' to callable: 'MarginContainer::_on_options_pressed': Method not found.
  <C++ Source>   core/object/object.cpp:1082 @ emit_signalp()
E 0:00:08:0482   emit_signalp: Error calling from signal 'pressed' to callable: 'MarginContainer::_on_quit_pressed': Method not found.
  <C++ Source>   core/object/object.cpp:1082 @ emit_signalp()
```

Also some errors that pop when the game starts(doesn't seem to really effect it in any way):
```
E 0:00:03:0479   _parse_ext_resource: res://Ui/main_menu.tscn:32 - Parse Error: [ext_resource] referenced non-existent resource at: res://Ui/menu.gd
  <C++ Source>   scene/resources/resource_format_text.cpp:162 @ _parse_ext_resource()
E 0:00:03:0487   set_path: Another resource is loaded from path 'res://Ui/main_menu.tscn' (possible cyclic resource inclusion).
  <C++ Error>    Method/function failed.
  <C++ Source>   core/io/resource.cpp:75 @ set_path()
```
By the way even if I use get_tree().change_scene_to_file() instead of packed it still shows the same error.

### Steps to reproduce

I think I covered the most up. If you have more questions or need more information plz let me know.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-11-06 17:10
Please copy the code and errors instead of photographing your screen with your phone

**Comment by AserYolo** [comment] 2023-11-06 17:13
> Please copy the code and errors instead of photographing your screen with your phone

> Please copy the code and errors instead of photographing your screen with your phone

How can I edit it now? Or should I send the code in the comments?

**Comment by AThousandShips** [comment] 2023-11-06 17:13
You click the three dots and press `Edit`

**Comment by AserYolo** [comment] 2023-11-06 17:28
> You click the three dots and press `Edit`

Ok I uploaded the code.

**Comment by AThousandShips** [comment] 2023-11-06 17:32
You are including `options.tscn` in `main_menu.tscn` and then `main_menu.tscn` in `options.tscn`, this is not supported, cyclic references aren't valid

**Comment by AserYolo** [comment] 2023-11-06 17:33
> You are including `options.tscn` in `main_menu.tscn` and then `main_menu.tscn` in `options.tscn`, this is not supported, cyclic references aren't valid

wdym I have two different scenes to change between

**Comment by AThousandShips** [comment] 2023-11-06 17:34
You have:
```
var options = preload("res://Ui/options.tscn")
```
And
```
var menu = preload("res://Ui/main_menu.tscn")
```

And each references the other, that's not supported, see the link above

**Comment by AserYolo** [comment] 2023-11-06 17:34
> You are including `options.tscn` in `main_menu.tscn` and then `main_menu.tscn` in `options.tscn`, this is not supported, cyclic references aren't valid
> 
> See:
> 
> * [[TRACKER] Cyclic dependencies related issues #80877](https://github.com/godotengine/godot/issues/80877)

then how sould I do it even if I use change scene to file it still doesnt work

**Comment by AThousandShips** [comment] 2023-11-06 17:36
I don't know, but I'm just saying what the issue is, telling you what's wrong, you would have to figure that out until this can be resolved

**Comment by AThousandShips** [comment] 2023-11-06 17:37
Duplicate of https://github.com/godotengine/godot/issues/76641

**Closed by AThousandShips** 2023-11-06 17:37 UTC
Labels: topic:gdscript, needs testing

**Comment by AserYolo** [comment] 2023-11-06 17:40
> Thank you for reporting, closing as a duplicate of:
> 
> * [Script removed from node upon preload scene in cyclic  reference. #76641](https://github.com/godotengine/godot/issues/76641)
> 
> Please see there and the tracker for more details

Ok thank you very much have a good day

**Comment by AThousandShips** [comment] 2023-11-06 17:41
You too!
