### ISSUE TITLE
Prompt to clean up open scripts to prevent "Message queue out of memory"

### ISSUE THREAD

**Issue by Cryszon** [godotengine/godot#17693] opened 2018-03-22 11:44 UTC
**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
Having 80 or more scripts open in a project (`open_scripts` in `editor_layout.cfg`) with default `message_queue_size_kb` (1024) causes the console to fill up with `ERROR: Message queue out of memory` when opening the project and makes the editor unstable once the project finally opens.

The reason for having so many scripts open is that I use an external code editor and use the internal editor for only debugging, which leaves multiple files open when viewing the stack trace.

**Steps to reproduce:**
Open a project with 80 different scripts open with the default `message_queue_size_kb` value (1024).

**Proposed solution**
The solution is to simply either increase the `message_queue_size_kb` or close some open scripts when the number of scripts becomes too high. This could be prompted when attempting to open a project with too many scripts open.

The script editor could also implement something similar to VS Code's [Preview Mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode) where scripts don't stay open when viewing the stack trace.

**Comment by Zylann** [comment] 2018-03-22 12:04
The queue filling up sounds like every single open script uses `call_deferred`, right?

**Comment by reduz** [comment] 2018-09-07 00:47
This sounds like fun, I supose you can put a breakpoint in call_deferred or MessageQueue::push_call, or directly in _err_print_error to break and see when this error happens and understand why call_deferred is being used so much.

**Comment by fracteed** [comment] 2019-04-16 02:33
@Cryszon thanks for posting this issue, as I just ran into for the first time and was somewhat freaked out when I couldn't load up my project! I am still using 3.0.6, but it looks like it hasn't been fixed in 3.1/3.2. Not sure that I had 80 scripts open the last time I had the project open but I did have quite a lot.  

It was an easy fix by deleting the editor_layout.cfg file, but this is a scary bug and initially caused me to miss several heartbeats :)

**Comment by pouleyKetchoupp** [comment] 2019-09-05 09:45
I can't exactly reproduce the issue with 90 scripts and a message queue size of 1024 KB, but I can reproduce it with a size of 400 KB in my test project. Maybe it depends on the complexity of the scripts or other things in the project (mine is very minimal).

Anyway, it might be worth solving the problem because there's still a limit in how many scripts can be loaded.

In my case, each edited script causes 210 calls to `MessageQueue::push_call` when the project is loaded, and almost all of them are from this line:
https://github.com/godotengine/godot/blob/8bcf6ca95317329242e954a71047ce1183cfe5f8/editor/plugins/script_editor_plugin.cpp#L2154

There are mostly due to `update_callback` from `CanvasItem` and `sort_children` from `Container` when all the controls for the script editor are added to the tree for each script: text editor, menus, etc...

An easy fix would be to flush the message queue while loading all the scripts when there are many of them. I've tested it on my own and didn't spot any issue when doing that. I'm going to propose a PR in case it could be an ok temporary fix.

**Comment by akien-mga** [comment] 2019-09-25 13:55
Moving to 4.0 milestone as the plan is to change MessageQueue to use a page allocator so that it can grow as needed and prevent such overflows.

**Comment by akien-mga** [comment] 2020-01-28 07:55
Superseded by #35653.

**Closed by akien-mga** 2020-01-28 07:55 UTC
Labels: bug, hero wanted!, topic:editor
