### ISSUE TITLE
Godot 3.4 crashes when opening FBX file (84 MB)

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#56256] opened 2021-12-26 16:58 UTC
### Godot version

3.4.2

### System information

Linux, GLES3

### Issue description

When I open the FBX file Godot crashes and spams the following error message:
```
ERROR: Condition "!mem" is true. Returned: nullptr
   at: alloc_static (core/os/memory.cpp:77)
```

This also happened in Godot 3.3. I don't think it's a memory issue since I opened other FBX files that were larger than 84 MB.

### Steps to reproduce

I will upload a file soon.

**Comment by Chaosus** [comment] 2021-12-26 19:21
Maybe it's a duplicate of https://github.com/godotengine/godot/issues/51373 (I'm not sure if the reason is the same because the error message is different)

**Comment by AgentSmith0** [comment] 2021-12-26 22:51
> Maybe it's a duplicate of #51373 (I'm not sure whether it happens for the same reason because the error message is different)

It's not a duplicate because in this case I am able to import the file, but I can't open it as a scene. In the other issue the editor crashed directly on import.

**Comment by AgentSmith0** [comment] 2021-12-27 09:12
Is it possible to make a comment only visible for contributors?

**Comment by Zireael07** [comment] 2021-12-27 09:14
No, but I understand it's possible to mail the project/asset directly to some of the contributors (Akien? Calinou?)

**Comment by Calinou** [comment] 2021-12-27 16:25
> No, but I understand it's possible to mail the project/asset directly to some of the contributors (Akien? Calinou?)

Neither of us have experience working on the FBX importer, so sending the project to us directly would unfortunately not be useful.

**Comment by akien-mga** [comment] 2022-04-06 22:17
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:17 UTC
Labels: bug, topic:core, crash
