### ISSUE TITLE
GradientTexture flags cannot be set

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18388] opened 2018-04-23 23:52 UTC
Godot 3.0.2

It's not possible to set the texture flags of a GradientTexture. You can see the property in the inspector and click on the flags, but they don't do anything and revert to their defaults.
There is no error in the console, it just looks like it's not implemented.

![image](https://user-images.githubusercontent.com/1311555/39158795-5061f470-4762-11e8-9b15-96d9bf486f6e.png)

I found this while trying to set a GradientTexture to repeat, which would be particularly useful for endless gradients or animations.

**Comment by CowThing** [comment] 2019-10-10 19:36
This is still an issue in 3.2 alpha 1

**Comment by AdamRatai** [comment] 2020-03-15 19:33
I think it's still an issue in 3.2.1 stable official

**Comment by KoBeWi** [comment] 2020-09-02 01:44
Still valid in 3.2.3 rc4, but resolved in 4.0, because flags are no longer set for textures but for CanvasItems. Unless the issue is important to fix, it can be closed already.

**Comment by akien-mga** [comment] 2020-09-02 07:44
Duplicate of #25045.

**Closed by akien-mga** 2020-09-02 07:44 UTC
Labels: bug, confirmed, topic:core
