### ISSUE TITLE
Very slow loading

### ISSUE THREAD

**Issue by Ole3383** [godotengine/godot#61046] opened 2022-05-15 09:44 UTC
### Godot version

3.4.4

### System information

Windows 10, AMD Ryzen 5 1600X

### Issue description

After a while I get these slow loading times.
I don't know why or when it happens, but it affects everything (loading the editor, projects and debugging the projects).
This is not limited to a specific project.

https://user-images.githubusercontent.com/105585427/168466470-d0c53532-8e9a-407f-b183-ef5dd7d44afc.mp4

### Steps to reproduce

I just use the engine and after a while it gets very slow with loading.

**Comment by akien-mga** [comment] 2022-05-15 10:22
Probably a duplicate of #20566. Can you disconnect USB peripherals to see if one of those is wrongly reporting itself as a joystick and stalling Godot?

**Comment by akien-mga** [comment] 2022-05-19 06:56
Assuming that it's what I described, please comment if disconnecting USB peripherals doesn't solve it.

**Closed by akien-mga** 2022-05-19 06:56 UTC
Labels: bug, performance
