### ISSUE TITLE
Incompatible GDScript parser in 3.2.1 and 3.2.2 versions

### ISSUE THREAD

**Issue by devolonter** [godotengine/godot#39979] opened 2020-06-30 08:31 UTC
**Godot version: 3.2.2**

**OS/device including version: macOS Catalina 10.15.5**

**Issue description:**
The code provided below compiles without errors in 3.2.1, but in 3.2.2 it throws: **Parse Error: Variable "i" already defined in the scope**.  Example:
```
func _ready():
  for i in range(10):
    print_debug(i)

      for i in range(10):
        print_debug(i)
```

**Minimal reproduction project:**
[3.2.2.zip](https://github.com/godotengine/godot/files/4850442/3.2.2.zip)

**Comment by bruvzg** [comment] 2020-06-30 08:34
Shadowing was disabled in #39276

**Comment by devolonter** [comment] 2020-06-30 08:40
> Shadowing was disabled in #39276

Ah, thanks! But it's strange that maintenance release broke backward compatibility

**Comment by Calinou** [comment] 2020-06-30 08:42
> Ah, thanks! But it's strange that maintenance release broke backward compatibility

We don't claim to follow semantic versioning for this reason. Patch releases may break backward compatibility in subtle ways, especially in projects that follow bad practices such as shadowing variables.

**Comment by akien-mga** [comment] 2020-06-30 08:42
Duplicate of #39861.

**Closed by Calinou** 2020-06-30 08:42 UTC
