### ISSUE TITLE
Input.is_action_pressed("a") does not behave the same as event.is_action_pressed("a") on doubleclick

### ISSUE THREAD

**Issue by p4ngy4** [godotengine/godot#4307] opened 2016-04-13 07:32 UTC
on v2.0.1_stable

If you try both of these statements in an _input(event) function, event.is_action_pressed("a") will return true and Input.is_action_pressed("a") will return false if the action "a" was triggered by a doubleclick.

example code:
```
func _ready():
    set_process_input(true)

func _input(event):
    if event.type == 3 and event.is_pressed():
        print(event.is_action_pressed("a"), Input.is_action_pressed("a"))
```

after creating action "a" and setting its input to a mouse click, upon testing it should print "true true for the first click then "true false" for the second click of the doubleclick.

**Comment by Hinsbart** [comment] 2016-09-17 01:08
Can't reproduce anymore.
I think this has been fixed by the recent changes in Input Actions.

**Closed** 2016-09-17 07:42 UTC
Labels: bug, topic:core
