### ISSUE TITLE
GDScript 2.0: An enum type annotation is parsed differently in release and debug/editor mode

### ISSUE THREAD

**Issue by Kyrio** [godotengine/godot#64084] opened 2022-08-07 23:46 UTC
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, 64-bit editor and builds

### Issue description

The GDScript parser exhibits different behavior in a release export compared to the debug export or running in editor. Here's the offending line:
```gdscript
func _on_json_request_completed(result: HTTPRequest.Result, response_code: int, headers: PackedStringArray, body: PackedByteArray):
    if result != HTTPRequest.RESULT_SUCCESS or response_code != 200:
```

This line causes no issue in the editor or in a debug build. However, a release build throws the following error:
```
SCRIPT ERROR: Parse Error: Invalid operands "HTTPRequest" and "int" for "!=" operator.
          at: GDScript::reload (res://gui/releases/release_list.gd:136)
```

Changing the type annotation of `result` to `int` fixes the error, which likely means the Result enum was mistaken for the HTTPRequest class.

### Steps to reproduce

1. Declare a variable with a `HTTPRequest.Result` type annotation
2. Use the inequality operator to compare it with one of the `HTTPRequest.Result` constants
3. Export the project in release mode
4. Start the build with a console attached

### Minimal reproduction project

[EnumAnnotation.zip](https://github.com/godotengine/godot/files/9292958/EnumAnnotation.zip)

**Comment by Kyrio** [comment] 2022-08-09 16:35
Added a reproduction project.

**Comment by heppocogne** [comment] 2022-08-10 03:18
This problem is caused by the differences in the following macro definitions.
Because of these differences, the release binaries do not register C++ enum type names at runtime and result in GDScript errors with the expressions like `C++ClassName.C++EnumTypeName`.

Debug build:
https://github.com/godotengine/godot/blob/317ced8204d80367c445963fc989de320c6f9a68/core/object/class_db.h#L380-L384
Release build:
https://github.com/godotengine/godot/blob/317ced8204d80367c445963fc989de320c6f9a68/core/object/class_db.h#L414-L418

The possible solutions would be:
1. Change the macro definitions in release build to be the same as debug build.
This approach requires less code modification.
If the difference is for performance optimization (I'm not sure), this may not be the best approach.
2. Change the logics of type checking for C++ enum types.
We would have to modify the following codes and more to allow C++ enum types that do not exist in ClassDB:
https://github.com/godotengine/godot/blob/317ced8204d80367c445963fc989de320c6f9a68/modules/gdscript/gdscript_analyzer.cpp#L502-L505
https://github.com/godotengine/godot/blob/317ced8204d80367c445963fc989de320c6f9a68/modules/gdscript/gdscript_analyzer.cpp#L583-L592

**Comment by vr-voyage** [comment] 2022-09-10 02:24
I got hit by a similar bug, where the following code :

```gdscript
var status:int = http.get_status()
if status != HTTPClient.STATUS_REQUESTING:
    print("%d != %d" % [status, HTTPClient.STATUS_REQUESTING])
    break
```

Would output
```
6 != 6
```

However, I hit that bug when running the code through the 'Play' button in the Editor, using Godot 4 Alpha 16.
I don't know if that's related to that bug, but I was able to fix that issue by just removing the 'int' cast :

```gdscript
var status = http.get_status()
if status != HTTPClient.STATUS_REQUESTING:
    print("%d != %d" % [status, HTTPClient.STATUS_REQUESTING])
    break
```

Now, I wasn't able to reproduce that bug by just doing `var status:int = HTTPClient.STATUS_REQUESTING`, so this not a simple enum cast or enum compare bug, it seems.

**Comment by anvilfolk** [comment] 2022-12-17 04:13
These issues seem related to #69532.

I'll try looking into a solution that doesn't require adding extra information to `ClassDB` in release exports. There might be something the analyzer can do.

**Comment by anvilfolk** [comment] 2022-12-17 04:19
@vr-voyage can you create a new issue with an MRP for that one? It seems related but not completely, and I'd love to take a look at that one :)

**Comment by anvilfolk** [comment] 2022-12-17 16:04
Ok, so there is something the analyzer can do in the situation mentioned here, but not in #69532, so I think #64253 should be merged :)

**Closed** 2023-01-05 23:31 UTC
Labels: bug, topic:gdscript, topic:export
