### ISSUE TITLE
TileMap copy/cut using Atlas icon instead of correct tile

### ISSUE THREAD

**Issue by emilnymann** [godotengine/godot#35497] opened 2020-01-24 10:36 UTC
**Godot version:** 

3.1.2

**OS/device including version:** 

Windows 10 version 1903, build 18362.592

**Issue description:** 

When editing a tilemap with atlasses and using the selection tool to select an area and then either copying or cutting, the pasted version will use the icons of each atlas rather than the correct tile that was cut or copied.

**Steps to reproduce:**

1. Set up a tilemap with a tileset using atlasses.
2. Select an icon for each atlas.
3. Draw with some tiles from different atlasses.
4. Use the selection tool to select the area you just drew.
5. Use either the cut or copy tool and paste it somewhere else.

![screenshot](https://user-images.githubusercontent.com/27289912/73062866-aeb35f80-3e9d-11ea-87f4-31295d3cd66d.png)

**Comment by bojidar-bg** [comment] 2020-01-24 12:41
Just to make it clear: does the paste operation still paste the correct nodes, even if the display of the selection is wrong?

**Comment by bojidar-bg** [comment] 2020-01-24 12:44
Or wait. This is a duplicate of #29307, which was fixed by #29460.

**Closed by bojidar-bg** 2020-01-24 12:44 UTC
Labels: bug, topic:editor
