### ISSUE TITLE
Bug When Playing A Scene With A Video Player

### ISSUE THREAD

**Issue by CDGames1** [godotengine/godot#37978] opened 2020-04-18 05:03 UTC
**Godot version:**
3.2.1 Stable

**OS/device including version:**
Windows

**Issue description:**
when I start A Godot Scene With A VIdeo Player It Just Goes To Not Responding

**Steps to reproduce:**
Try To Fix The Crash Rate ???????????????

![image](https://user-images.githubusercontent.com/63894306/79628607-736fb680-8196-11ea-894a-499f634e7a55.png)

**Comment by akien-mga** [comment] 2020-04-18 06:33
We can't do anything if you don't provide steps to reproduce or a minimal reproduction project.

**Comment by volzhs** [comment] 2020-04-18 07:18
prefer to give a minimal project in this case...

**Comment by bojidar-bg** [comment] 2020-04-18 10:42
Potential duplicate of #37648?

**Comment by Calinou** [comment] 2020-04-23 07:43
Duplicate of #37648.

**Closed by Calinou** 2020-04-23 07:43 UTC
