### ISSUE TITLE
Inspector theme doesn't update between light and dark theme until another node is selected

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#81108] opened 2023-08-29 08:10 UTC
### Godot version

4.1.1.stable, 4.2.dev 541674d10

### System information

Godot v4.2.dev (541674d10) - Fedora Linux 38 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.98) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

The inspector theme doesn't update between light and dark theme until another node is selected:

For example, after switching from light to dark theme, you initially see this in the inspector:

![Screenshot_20230829_100621](https://github.com/godotengine/godot/assets/180032/c4a46d5f-04e6-40eb-9eab-f22e482828b9)

If you switch to another node in the inspector (or deselect all nodes then select a node again), section and icon colors will appear correctly (i.e. with darker tones).

### Steps to reproduce

- Select a node in the Scene tree dock.
- Set the editor theme to **Light** in the Editor Settings.
- Notice the sections' and icons' color in the inspector.
- Select another node (or deselect all nodes then select a node again).
- Notice how the theme now appears correctly.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-08-29 11:08
This is a duplicate of https://github.com/godotengine/godot/issues/81108. I plan to look into it at some point, it just needs a bit of theme changed notification handling.

**Closed by YuriSizov** 2023-08-29 11:08 UTC
Labels: bug, topic:editor
