### ISSUE TITLE
Camera smoothing causes sprites to flicker

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2667] opened 2015-10-24 15:47 UTC
When using 2d pixel snap with a camera that has smoothing enabled, sprites flicker (move, say, left-right ~1 pix several times) just before the camera settles. 

The position of spires is probably a non-integer.

**Edit:** Problem persists without pixel snap.

**Comment by seadra** [comment] 2015-10-24 15:58
I was comparing the project settings against the platformer demo and I noticed something strange: my projects doesn't even have rasterizer/use_pixel_snap option!

The project was created with the git tip.

**Comment by reduz** [comment] 2015-10-24 20:48
i guess make some test scene

**Comment by seadra** [comment] 2015-10-27 03:43
[Here](http://www.mediafire.com/download/9gvoq8o3zp8rrz2/flicker.zip) is a test project that shows the flickering problem.

I disable mipmaps and filter because I was getting strange artifacts like this:
![screenshot](https://cloud.githubusercontent.com/assets/9574367/10748920/db230ff2-7c32-11e5-8eb8-77189c2ba1ba.png) (see the left side of the characters hand, there is a strange line)

**Comment by seadra** [comment] 2015-10-27 14:27
The flickering of the sprite is present with or without pixel snap it seems.
The problem seems to be Camera2D smoothing.

**Comment by Alex-doc** [comment] 2016-06-16 13:36
I'm having a similar problem with ParallaxBackground, setting the camera2D smoothing on and to a very low value makes the parallax look "jittery". Seems to me that is due to the camera smoothing.
Might need [some more interpolation here](https://github.com/godotengine/godot/blob/ef8b160da898a67f226c6af2f443a18929739db7/scene/2d/camera_2d.cpp#L123)?

**Comment by reduz** [comment] 2016-06-16 13:53
can you make a small demo project?

**Comment by Alex-doc** [comment] 2016-06-16 14:58
On my game seems to happen even without smoothing camera when I set the drag margin off.
I went very close to the issue with the [demo here](https://www.dropbox.com/s/tt0ay50i67zkvfo/Jitter.zip?dl=0) the glitch seems to show up better on less performant hardware.

To be clear, I'm not referring to the repeating of the parallax.
I'm referring to the actual jittery motion when you slightly and suddenly move the camera.
To better give the idea, it kinda looks like some sort of floating point imprecision with the position of the parallax or the camera

**Comment by Dillybob92** [comment] 2017-05-03 03:35
Folks any update on this?

I've tried drag margins off, disabling smoothness, updating the camera in fixed_update right below `move`, using the `align()` suggestion [here](https://godotengine.org/qa/6197/how-to-stop-camera-lag?show=6197#q6197) as well.


### There is one solution though

You enable the `filter` under the `Image Loader`project  settings.

However... some of my images I don't want filter to be enabled on because I need the sharpness for that particular sprite. Is there a temporary work around for this?

**Comment by bojidar-bg** [comment] 2017-05-03 10:36
@Dillybob92 You should be able to update the filter on per-sprite basis by overriding its flags (AFAIK).

**Comment by Dillybob92** [comment] 2017-05-03 15:38
@bojidar-bg yeah, looks like that will do for now. It's just some sprites for the world I don't want filtered as it ruins the sharpness of the image. I just don't know if this is what all game engines do, or just a godot thing.  But filtering definitely fixes it. I thought it was a camera issue at first. [reduz gave updated too here](https://github.com/godotengine/godot/issues/2043#issuecomment-298838012)

**Comment by Calinou** [comment] 2019-12-24 09:33
For anyone still able to reproduce this issue, does setting the Camera2D update mode to **Process* improve the situation?

**Comment by Calinou** [comment] 2020-06-07 20:02
Duplicate of #35606, which has more information about the issue at hand.

**Closed by Calinou** 2020-06-07 20:02 UTC
Labels: bug, topic:rendering
