### ISSUE TITLE
Cannot import compressed glb and godot try reimport the glb if user switch from other program.

### ISSUE THREAD

**Issue by adfriz** [godotengine/godot#73738] opened 2023-02-22 06:47 UTC
### Godot version

v3.5.1.stable.mono.official [6fed1ffa3] and v4.0.rc2.official [d2699dc7a]

### System information

Windows 10 21H2, Nvidia GT630M, 4.5.0 NVIDIA 391.35, GLES3

### Issue description

cannot import compressed glb file, uncompressed version is worked perfectly.

[3.5.1 mono logs]
 
 modules/gltf/gltf_document.cpp:6834 - glTF2 extension KHR_draco_mesh_compression is not supported.
 modules/gltf/packed_scene_gltf.cpp:75 - Condition "err != Error::OK" is true. Returned: nullptr
 editor/editor_file_system.cpp:1759 - Error importing 'res://compress.glb'.

[4.0rc2 standard win64 logs]

  modules/gltf/gltf_document.cpp:7454 - GLTF: Can't import file 'compress', required extension 'KHR_draco_mesh_compression' is not supported. Are you missing a GLTFDocumentExtension plugin?
  modules/gltf/gltf_document.cpp:7312 - Condition "err != OK" is true. Returning: ERR_PARSE_ERROR
  modules/gltf/gltf_document.cpp:6993 - Condition "err != OK" is true. Returning: err
  modules/gltf/gltf_document.cpp:7421 - Condition "err != OK" is true. Returning: err
  Error importing 'res://compress.glb'.

### Steps to reproduce

glb bug:
just import compressed glb file to godot.

reimport bug ?:
after the compressed glb appear in filesystem area try open other app like a notepad and back to godot, godot will try reimport even its already marked with X icon.

### Minimal reproduction project

N/A

Use default 3d project.

Object i use.
[object.zip](https://github.com/godotengine/godot/files/10800789/object.zip)

**Comment by akien-mga** [comment] 2023-02-22 07:33
Draco compressed files are not supported currently, as the error message mentions. See https://github.com/godotengine/godot/issues/47822

The continuous attempt at reimporting unsupported files is a duplicate of https://github.com/godotengine/godot/issues/62271

**Closed by akien-mga** 2023-02-22 07:33 UTC
