### ISSUE TITLE
When I download an image file an error occurs when trying to load that resource

### ISSUE THREAD

**Issue by ferhand** [godotengine/godot#12044] opened 2017-10-12 01:41 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8.1
Godot 2.1.3 estable

**Issue description:**
First I make a request to a website and download an image file .jpg

then I try to load that image and put it in a TextureFrame using load("image_path") like 
var i = load("image_path")
get_node("TextureFrame").set_texture(i)
but nothing happen

if I print the variable i then writes  [Object:null]

Why?

I've try to load several images and put them in the TextureFrame but only miss with the images I download and not with image I already have in my PC...

Help..!         please...!

Edit:
 This is one of the "problematic" images..
![ferhand64](https://user-images.githubusercontent.com/25112749/31477423-5f551e1c-aee2-11e7-98ef-ce99766d1295.jpg)   Am I handson?

**Comment by Dillybob92** [comment] 2017-10-12 02:08
need to add res://image.png

in future though, post on Q&A site, discord, and other community links for help, this place is really for native bug reports :)

**Comment by volzhs** [comment] 2017-10-12 02:37
attach the problematic image.

**Comment by Noshyaar** [comment] 2017-10-12 17:33
Was the image_path correct? Did it have 'res://' in front of it? Or extension? Are you certain it finished downloading before you `load` it? Did you check with File.exists? Did the console output any errors?

Are you sure the problem is not in the download script?

**Comment by volzhs** [comment] 2017-10-12 17:39
to make sure, did you download it on runtime with godot? or download it from browser and use it?

**Comment by ferhand** [comment] 2017-10-12 23:26
@Noshyaar : Yes, the path was correct all the 10 000 times I try it. Also that image you see there is the downloaded one. The console didn't output any errors. I haven't check with File.file_exists, I'll do it this next weekend because only then I'll have internet with no proxy.

@volzhs : I download that image in run time...

**Comment by Dillybob92** [comment] 2017-10-13 01:57
can u give example project plz in a zip file? ty

**Comment by akien-mga** [comment] 2018-09-17 15:14
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 15:14 UTC
Labels: bug
