### ISSUE TITLE
Godot 4.2 Project Manager fonts bug on opengl3

### ISSUE THREAD

**Issue by Xerathe** [godotengine/godot#85987] opened 2023-12-10 05:02 UTC
### Tested versions

Was not present in 4.0
After update to 4.2 the bug occured

### System information

Win10 ; Godot 4.2 stable ; OpenGL3 rendering mode (GPU: Intel HD 520)

### Issue description

Updated to 4.2 after 4.0 using the same workaround for running it on OpenGL3 (i.e. --rendering-driver opengl3 parameter). The font in the Project Manager ONLY has changed to this. The project editor itself and everything else is fine.
![Lqe5g](https://github.com/godotengine/godot/assets/111675193/4221f802-9cbe-4820-9655-0d6e327839fe)

### Steps to reproduce

Launching 4.2 stable .exe with "--rendering-driver opengl3" parameter

### Minimal reproduction project (MRP)

Not required

**Comment by AThousandShips** [comment] 2023-12-10 11:46
Duplicate of https://github.com/godotengine/godot/issues/79955

**Closed by AThousandShips** 2023-12-10 11:46 UTC
