### ISSUE TITLE
Inspector disapears after opening NativeScript resource

### ISSUE THREAD

**Issue by NilsIrl** [godotengine/godot#30863] opened 2019-07-27 10:43 UTC
**Godot version:**
e4ec59b

**OS/device including version:**
Ubuntu 19.04 X11
1366x768 laptop monitor/screen

**Issue description:**
When double clicking on the `NativeScript` resource, the inspector disappeared in the Window. I am not sure if this is only the case of `NativeScript`.

**Steps to reproduce:**
![output](https://user-images.githubusercontent.com/26231126/61993426-f6cb0400-b06b-11e9-9424-1f64c55c9c03.gif)

**Comment by akien-mga** [comment] 2019-07-27 10:48
Might be a duplicate of #29495.

The issue is exacerbated by the too long French translations of the buttons in the script editor, which force it to have a big width. Solving #29495 might not fully fix that issue (it can be checked on 3.1.1 which is not affected by #29495 to confirm).

**Comment by NilsIrl** [comment] 2019-07-27 11:27
> Might be a duplicate of #29495.

The behaviour is the same so I would agree.

**Comment by NilsIrl** [comment] 2019-07-27 11:29
Fixed by #30865.

Closing.

**Comment by NilsIrl** [comment] 2019-07-27 12:12
I still have the problem with 94aabf56a0a.

**Comment by NilsIrl** [comment] 2019-07-27 12:15
Setting the language to English does fix the problem though.

**Comment by akien-mga** [comment] 2020-01-19 21:17
I'll close as duplicate of #31133 which has the same underlying cause.

**Closed by akien-mga** 2020-01-19 21:17 UTC
Labels: bug, topic:editor, usability
