### ISSUE TITLE
Godot closes suddenly.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#70011] opened 2022-12-13 09:43 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

w10 64

### Issue description

With this program godot will exit when you put the digits "0,0" in posmod.
The cmd prompt does not indicate anything.

https://user-images.githubusercontent.com/19652075/207283163-53582213-fa72-416b-9335-31999a914d43.mp4

### Steps to reproduce

Write "0,0" in postmod like in the video.

### Minimal reproduction project

[testCierreRepentino.zip](https://github.com/godotengine/godot/files/10216544/testCierreRepentino.zip)

**Comment by Sauermann** [comment] 2022-12-13 09:53
Can confirm crash on Linux in v4.0.beta.custom_build [ba4bd7f00]

```
================================================================
handle_crash: Program crashed with signal 8
Engine version: Godot Engine v4.0.beta.custom_build (ba4bd7f00971a94c20d90e7d2c665d5eb0ae1b90)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7ff22903ad60] (??:0)
[2] VariantUtilityFunctions::posmod(long, long) (/srv/docker/data/godot-compile/godot/./core/math/math_funcs.h:228)
[3] ./bin/godot-master() [0x5271b38] (/srv/docker/data/godot-compile/godot/core/variant/variant_utility.cpp:?)
[4] ./bin/godot-master() [0x5271ae6] (/srv/docker/data/godot-compile/godot/core/variant/variant_utility.cpp:1046)
[5] ./bin/godot-master() [0x5271a81] (/srv/docker/data/godot-compile/godot/core/variant/variant_utility.cpp:1481)
[6] Variant::call_utility_function(StringName const&, Variant*, Variant const**, int, Callable::CallError&) (/srv/docker/data/godot-compile/godot/core/variant/variant_utility.cpp:?)
[7] GDScriptAnalyzer::reduce_call(GDScriptParser::CallNode*, bool, bool) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:2450)
[8] GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*, bool) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:1912)
[9] GDScriptAnalyzer::resolve_variable(GDScriptParser::VariableNode*) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:1484)
[10] GDScriptAnalyzer::resolve_node(GDScriptParser::Node*, bool) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:?)
[11] GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:1338)
[12] GDScriptAnalyzer::resolve_function_body(GDScriptParser::FunctionNode*) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:1279)
[13] GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode*) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:938)
[14] GDScriptAnalyzer::resolve_program() (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:4381)
[15] GDScriptAnalyzer::analyze() (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_analyzer.cpp:4397)
[16] GDScriptLanguage::complete_code(String const&, String const&, Object*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, bool&, String&) (/srv/docker/data/godot-compile/godot/modules/gdscript/gdscript_editor.cpp:?)
[17] ScriptTextEditor::_code_complete_script(String const&, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, bool&) (/srv/docker/data/godot-compile/godot/editor/plugins/script_text_editor.cpp:?)
[18] ScriptTextEditor::_code_complete_scripts(void*, String const&, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, bool&) (/srv/docker/data/godot-compile/godot/editor/plugins/script_text_editor.cpp:744)
[19] CodeTextEditor::_complete_request() (/srv/docker/data/godot-compile/godot/editor/code_editor.cpp:?)
[20] void call_with_variant_args_helper<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:267)
[21] void call_with_variant_args<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, int, Callable::CallError&) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:377)
[22] CallableCustomMethodPointer<CodeTextEditor>::call(Variant const**, int, Variant&, Callable::CallError&) const (/srv/docker/data/godot-compile/godot/./core/object/callable_method_pointer.h:105)
[23] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/srv/docker/data/godot-compile/godot/core/variant/callable.cpp:?)
[24] Object::emit_signalp(StringName const&, Variant const**, int) (/srv/docker/data/godot-compile/godot/core/object/object.cpp:?)
[25] Error Object::emit_signal<>(StringName const&) (/srv/docker/data/godot-compile/godot/./core/object/object.h:?)
[26] CodeEdit::request_code_completion(bool) (/srv/docker/data/godot-compile/godot/scene/gui/code_edit.cpp:1928)
[27] CodeTextEditor::_code_complete_timer_timeout() (/srv/docker/data/godot-compile/godot/editor/code_editor.cpp:925)
[28] void call_with_variant_args_helper<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:267)
[29] void call_with_variant_args<CodeTextEditor>(CodeTextEditor*, void (CodeTextEditor::*)(), Variant const**, int, Callable::CallError&) (/srv/docker/data/godot-compile/godot/./core/variant/binder_common.h:377)
[30] CallableCustomMethodPointer<CodeTextEditor>::call(Variant const**, int, Variant&, Callable::CallError&) const (/srv/docker/data/godot-compile/godot/./core/object/callable_method_pointer.h:105)
[31] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/srv/docker/data/godot-compile/godot/core/variant/callable.cpp:?)
[32] Object::emit_signalp(StringName const&, Variant const**, int) (/srv/docker/data/godot-compile/godot/core/object/object.cpp:?)
[33] Error Object::emit_signal<>(StringName const&) (/srv/docker/data/godot-compile/godot/./core/object/object.h:?)
[34] Timer::_notification(int) (/srv/docker/data/godot-compile/godot/scene/main/timer.cpp:80)
[35] Timer::_notificationv(int, bool) (/srv/docker/data/godot-compile/godot/scene/main/timer.h:37)
[36] Object::notification(int, bool) (/srv/docker/data/godot-compile/godot/core/object/object.cpp:792)
[37] SceneTree::_notify_group_pause(StringName const&, int) (/srv/docker/data/godot-compile/godot/scene/main/scene_tree.cpp:?)
[38] SceneTree::process(double) (/srv/docker/data/godot-compile/godot/scene/main/scene_tree.cpp:466)
[39] Main::iteration() (/srv/docker/data/godot-compile/godot/main/main.cpp:3192)
[40] OS_LinuxBSD::run() (/srv/docker/data/godot-compile/godot/platform/linuxbsd/os_linuxbsd.cpp:878)
[41] ./bin/godot-master(main+0xca) [0x248fdfa] (/srv/docker/data/godot-compile/godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[42] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7ff229025d0a] (??:0)
[43] ./bin/godot-master(_start+0x2a) [0x248fc6a] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted
```

**Comment by qarmin** [comment] 2022-12-13 10:11
Duplicate of  #43932

**Closed by qarmin** 2022-12-13 10:11 UTC
