### ISSUE TITLE
MaterialStorage warning with default project settings in compatibility renderer

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#93453] opened 2024-06-22 06:19 UTC
_Edit: Not specific to Linux_

### Tested versions

- Reproduces in v4.3.beta2.official [b75f0485b]
- Doesn't reproduce in v4.3.beta1.official [a4f2ea91a]

### System information

Arch Linux <span>#</span>1 SMP PREEMPT_DYNAMIC Wed, 12 Jun 2024 20:17:17 +0000 - Tty - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

The default value for `rendering/limits/global_shader_variables/buffer_size` is 65536, which in compatibility renderer can produce the following warning:

```
MaterialStorage: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 4096. Falling back on maximum buffer size.
  <C++ Source>   drivers/gles3/storage/material_storage.cpp:1115 @ MaterialStorage()
```

Whether the warning is issued or not seems to depend on hardware, it happens on my laptop but not on my desktop.

I'm not sure what should be changed here, the warning or the default, but I don't think a project with default settings should produce warnings.

### Steps to reproduce

Create a new project and set renderer to Compatibility. Run the project.

### Minimal reproduction project (MRP)

N/A

**Comment by patwork** [comment] 2024-06-22 07:15
https://github.com/godotengine/godot/issues/85374

**Comment by anniryynanen** [comment] 2024-06-22 07:38
So... the warning was suppressed, but has now re-emerged? Is that intentional?

**Comment by patwork** [comment] 2024-06-22 07:44
The limit at which the warning is displayed has changed. https://github.com/godotengine/godot/pull/92568

**Comment by anniryynanen** [comment] 2024-06-22 08:41
Removing "Linux" from the issue description, doesn't seem to be OS related.

**Comment by clayjohn** [comment] 2024-06-22 18:45
Duplicate of https://github.com/godotengine/godot/issues/85374

I wrote up a comment there on what I think the proper solution to this issue would be https://github.com/godotengine/godot/issues/85374#issuecomment-2183188628

**Closed by clayjohn** 2024-06-22 18:45 UTC
Labels: bug, topic:rendering
