### ISSUE TITLE
Low frame rate using TileMap on Android

### ISSUE THREAD

**Issue by myhalibobo** [godotengine/godot#26620] opened 2019-03-05 02:04 UTC
Godot version:
Godot_v3.1-beta10_win64

OS/device including version:
Honor 8 Lite

Issue description:
The effect of android running
![image](https://user-images.githubusercontent.com/8662169/53775535-ea63d480-3f2d-11e9-84a2-bae347b340b1.png)

Minimal reproduction project:
[tilemap_test.zip](https://github.com/godotengine/godot/files/2950388/tilemap_test.zip)

**Comment by volzhs** [comment] 2019-03-05 05:06
gles2 or 3?

**Comment by myhalibobo** [comment] 2019-03-05 05:44
@volzhs I tested it. It's all the same

**Comment by volzhs** [comment] 2019-03-05 13:11
related #7885

**Comment by MatiasVME** [comment] 2019-06-11 20:06
More evidence from the case.
https://youtu.be/NW5qQgb5LM8

If you need information about the android device (lenovo tab 4) tell me.

**Comment by Calinou** [comment] 2019-07-11 17:56
Duplicate of #7885.

**Closed by Calinou** 2019-07-11 17:56 UTC
Labels: bug, platform:android, topic:core
