### ISSUE TITLE
Editor crashes with access violation on specific interaction with VS Code

### ISSUE THREAD

**Issue by YellowAfterlife** [godotengine/godot#52469] opened 2021-09-07 16:40 UTC
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES3

### Issue description

Seems to be related to the language server or communication between Godot and VSC as the in-IDE editor does not suffer from this.

I was not able to locate any crash logs for it; Event Viewer just reads
```
Faulting application name: Godot.exe, version: 3.3.3.0, time stamp: 0x00000000
Faulting module name: Godot.exe, version: 3.3.3.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000022ff33
Faulting process id: 0xd71c
Faulting application start time: 0x01d7a36a4f8f5621
Faulting application path: ...\Godot.exe
Faulting module path: ...\Godot.exe
Report Id: c76d984f-eb4d-42c3-b7e8-bfe0ca00a4fb
Faulting package full name: 
Faulting package-relative application ID: 
```

### Steps to reproduce

1. Checkout https://github.com/YellowAfterlife/GodotPortals/commit/d773ed247afce7b565ecf8b5ceebf7bf715496f5
2. Open `Objects/Night/NightProjector.gd` in VS Code, connect to the editor
3. Start slowly entering `onready var` on a blank line
4. (editor mysteriously implodes)

![godot-crash](https://user-images.githubusercontent.com/731492/132380113-599aaf93-d824-458d-9191-3633e7e0b750.gif)

**Comment by pycbouh** [comment] 2021-09-07 16:58
Duplicate of https://github.com/godotengine/godot/issues/51923

**Closed by pycbouh** 2021-09-07 16:58 UTC
