### ISSUE TITLE
Autocomplete not filtering well any longer

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#59368] opened 2022-03-21 02:29 UTC
### Godot version

v4.0.alpha.custom_build [02f61d9fb]

### System information

Windows 10

### Issue description

Autocomplete used to filter results much better than it does now... 
godot 3.x
![image](https://user-images.githubusercontent.com/203130/159197469-596a962f-c81f-412e-9805-76ab3b719410.png)

godot 4
![image](https://user-images.githubusercontent.com/203130/159197521-12a23cfc-244d-4101-8928-17ddd6c12814.png)

godot 4 matching case (shouldn't have to but still doesn't work)
![image](https://user-images.githubusercontent.com/203130/159197768-0e8275a0-e6fe-4100-b741-f8ea47cda788.png)

I think fuzzy matches should always come last come after direct matches (case ignored) unless context dictates otherwise.  but lists should be clean of anything that doesn't fit context in the first place

### Steps to reproduce

- create a new script
- test autocomplete on just about anything compared to 3.x

**Comment by KoBeWi** [comment] 2022-03-22 18:20
This is actually duplicate of #40933
Auto-completion doesn't suggest Vector2 at all, with Object classes you will get expected results.

**Closed by KoBeWi** 2022-03-22 18:20 UTC
Labels: bug, topic:editor, regression

**Comment by dmaz** [comment] 2022-03-25 01:24
Ok sure but https://github.com/godotengine/godot/pull/43998 is over a year old and out of date

**Comment by Calinou** [comment] 2022-03-25 01:33
> Ok sure but #43998 is over a year old and out of date

Feel free to salvage that PR, taking https://github.com/godotengine/godot/pull/43998#issuecomment-757925968 into account :slightly_smiling_face:

**Comment by dmaz** [comment] 2022-03-27 18:23
@Calinou here's the new PR... First I did for opensource so I probably got the process wrong.
https://github.com/godotengine/godot/pull/59594
