### ISSUE TITLE
Normalmap artifacts

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#10043] opened 2017-08-02 14:14 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04
Godot_v3.0-alpha1 and Godot master at 57d961a

GPU: GeForce GTX 1050Ti
Driver: 375.66

**Issue description:**
When enabling Normalmap black artifacts appear on 3D model, no matter if a texture is set or not.
![selection_038](https://user-images.githubusercontent.com/6707330/28877680-5e3ee94e-779d-11e7-86e5-79723dcda4b6.jpg)

**Steps to reproduce:**

1. Import a 3D model
2. Enable Normalmap

**Comment by Zireael07** [comment] 2017-08-02 14:19
Was your model imported from .dae (Collada)?

**Comment by Noshyaar** [comment] 2017-08-02 14:22
Related #9562 #9939

**Comment by Keetz** [comment] 2017-08-02 14:25
@Zireael07 yes .dae exported from Blender with the better collada plugin

**Comment by Keetz** [comment] 2017-08-02 14:33
@Noshyaar ahh, didn't find those issues when i tried searching for similar. Guess this can be closed? I can add a comment with the information about GPU and driver in one of the other issues instead.

**Comment by kubecz3k** [comment] 2017-08-02 16:17
closing as a duplicate of https://github.com/godotengine/godot/issues/9939

**Closed by kubecz3k** 2017-08-02 16:17 UTC
Labels: archived
