### ISSUE TITLE
Sprites cropped using a rotated Rect2D don't get cut at the parent's sides, but at a greater rectangle's

### ISSUE THREAD

**Issue by K-l6408** [godotengine/godot#62974] opened 2022-07-13 10:07 UTC
### Godot version

3.3.4.stable.official

### System information

Kubuntu 21.04, GLES3, Mesa DRI Intel 4000

### Issue description

When you put a Sprite as a children of a rotated ColorRect with "clip contents" on, the Sprite gets cropped along the rectangle with sides parallel to the x and y axis that touches the Rect2D
![image](https://user-images.githubusercontent.com/106444866/178708156-7d04a9eb-98dd-4bfd-8fc0-df825b8a65e9.png)
like this

### Steps to reproduce

Have a Sprite as a child of a Rect2D

Turn "Clip Contents" on for the Rect2D

Rotate the Rect2D

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/9101105/Test.zip)

**Comment by Calinou** [comment] 2022-07-13 17:12
I'm not sure if that can be fixed, as clipping with axis-aligned rects is much easier to reason about compared to clipping with a rotated rect.

**Comment by Calinou** [comment] 2022-12-05 10:34
Duplicate of https://github.com/godotengine/godot/issues/62974 (same cause).

**Closed by Calinou** 2022-12-05 10:34 UTC
Labels: bug, topic:rendering, topic:2d

**Comment by kleonc** [comment] 2022-12-05 11:09
> Duplicate of #62974 (same cause).

That's this issue. :upside_down_face:

**Comment by Calinou** [comment] 2022-12-05 12:14
Duplicate of https://github.com/godotengine/godot/issues/20671.
