### ISSUE TITLE
External Changes to files do not notify or update

### ISSUE THREAD

**Issue by liukaichi** [godotengine/godot#96892] opened 2024-09-12 02:41 UTC
### Tested versions

- Reproducible in 4.4 dev2. Not reproducible in 4.3 stable

### System information

Godot v4.4.dev2 - Windows 10.0.22631 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

In 4.3 and earlier, if I make external changes, for example, pull from my version control, Godot would see that things have changed and notify me accordingly. This doesn't happen anymore with 4.4 dev2. I haven't tried this on 4.4 dev1 yet. 

### Steps to reproduce

Make the most basic project, have a script print("A") in the ready function.

Externally change this to print("B"). 

### Minimal reproduction project (MRP)

[external-change-bug.zip](https://github.com/user-attachments/files/16972583/external-change-bug.zip)

**Comment by Mopzilla** [comment] 2024-09-12 03:29
also having this issue, when I drag my file in for importing nothing happens in Godot.

**Comment by akien-mga** [comment] 2024-09-12 06:19
Duplicate of #96828.

**Closed by akien-mga** 2024-09-12 06:19 UTC
