### ISSUE TITLE
WorldEnvironment Near DOF will cause blank screen on Android.

### ISSUE THREAD

**Issue by AkatDeen** [godotengine/godot#28114] opened 2019-04-17 07:16 UTC
Godot 3.1
Android 7.0, Mali-T860 (OpenGLES3.2 capable device)

WorldEnvironment Near DOF when set to 'on', it will run blank screen on Android.

**Steps to reproduce:**
1. Create WorldEnvironment Node in the scene (or enable it through the camera).
2. Enable Near DOF in the inspector
3. compile to Android

after the splash screen, the Android will only render blank screen with the clear color.

its working just fine when Near DOF is set to 'disable'. and Far DOF is working just great.

**Comment by KoBeWi** [comment] 2020-12-02 21:41
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by kreaninw** [comment] 2020-12-03 04:35
> Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

I can confirm that this is still reproducing with the project exported in Godot 3.2.4 beta3, as shown [here](https://photos.app.goo.gl/tSjwzWwqrFSD8AV66). 

Tested on Sony Xperia XZ2, the OS as shown below:
![Screenshot_20201203-012438](https://user-images.githubusercontent.com/1403194/100964163-c79d9000-3506-11eb-8cbf-1acdcd65a711.jpg)

I uploaded the apk files with the option **Dof Near Blur** enabled and disabled [here](https://drive.google.com/drive/folders/1WWfi1IN1IEEch3eFm3wSwk6hYG68_E1O?usp=sharing).

Below is the reproduction project:
[test.zip](https://github.com/godotengine/godot/files/5633684/test.zip)

**Comment by volzhs** [comment] 2020-12-03 04:54
seems related to #15526

**Comment by Calinou** [comment] 2022-07-10 18:30
Duplicate of https://github.com/godotengine/godot/issues/15526.

**Closed by Calinou** 2022-07-10 18:30 UTC
Labels: bug, platform:android, topic:rendering, confirmed
