### ISSUE TITLE
[Debugging] Variables are `<null>` in the inspector

### ISSUE THREAD

**Issue by andreas-volz** [godotengine/godot#99774] opened 2024-11-27 23:39 UTC
### Tested versions

Godot v4.3.stable.official [77dcf97d8]

### System information

Linux Mint 21 (Vanessa) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 535.183.01) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

In some cases while debugging are variables <null> in the inspector while they're not in the code.

![Image](https://github.com/user-attachments/assets/14df63b1-a38e-4581-b8a3-a85acd920ccf)
![Image](https://github.com/user-attachments/assets/035d14d9-353f-4b1d-95d1-de04657c3463)

...by the way, the vf4_data variable is printed in the next debug step with many text. Just for interest, it's a 2,8 MB JSON file. The code works as expected just the debugger shows a null variable.

### Steps to reproduce

In some cases I notice this in my project. It may depend in the size of assigned data to a variable, but I'm not sure.

### Minimal reproduction project (MRP)

I've currently no mimimal reproduction project. If nobody known this problem or could reproduce it I may try to generate one.

**Comment by rhighs** [comment] 2024-11-28 10:55
Please provide just a minimal way to reproduce this, I'm not too familiar with this aspect of the engine but I'd like to help!

**Comment by ydeltastar** [comment] 2024-11-28 13:04
- See: https://github.com/godotengine/godot/issues/39465#issuecomment-1962334703

**Comment by adamscott** [comment] 2024-12-05 14:34
Closing as a duplicate of #39465

**Closed by adamscott** 2024-12-05 14:34 UTC
