### ISSUE TITLE
Incorrect render order for transparent object with disabled depth test

### ISSUE THREAD

**Issue by wlodeqp** [godotengine/godot#15873] opened 2018-01-19 18:06 UTC
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
Ubuntu 16.04 64-bit, Windows 10 64-bit

**Issue description:**
![screen](https://user-images.githubusercontent.com/35608701/35164458-b3402632-fd4a-11e7-82f8-7dd6bba6c4f8.png)

**Steps to reproduce:**

**Minimal reproduction project:**
[Test_Project.zip](https://github.com/godotengine/godot/files/1647483/Test_Project.zip)

**Comment by Noshyaar** [comment] 2018-01-20 06:26
Reproducible on eb9fa02, Antergos x86_64, Mesa DRI Intel(R) Haswell

**Comment by x1212** [comment] 2018-01-20 11:34
As far as I know it is/was common practice to render transparent objects last, sorted by distance to the camera from far to near  (if I understand http://docs.godotengine.org/en/latest/learning/features/3d/3d_performance_and_limitations.html#transparent-objects and https://godotengine.org/article/godot-3-renderer-design-explained correctly, it confirms this).
If that is the case I think this isn't a bug but more of a problem with documentation/usability, as it isn't obvious that the transparency setting has any influence on the order in which objects are rendered without reading more about the 3D renderer first.
Anyway: To me it looks like you want to create decals and https://godotengine.org/article/godot-3-renderer-design-explained seems to suggest that they are already supported in some way, but I didn't see anything about how to create them yet.

**Comment by wlodeqp** [comment] 2018-01-20 20:14
Thank you for your answer. For flat surfaces decals should be great but what if terrain is more complex?
I would like to achieve something similar like on the screenshot below and disable depth test should simplify vertex calculations.
![spline tool](https://user-images.githubusercontent.com/35608701/35187595-aec4b14a-fe26-11e7-8428-a5c4ab181beb.jpg)

**Comment by wlodeqp** [comment] 2018-01-20 22:03
You are right, I didn't think about this...:(

**Comment by jesperkondrup** [comment] 2018-05-08 10:13
I noticed this as well, not sure if it's exactly the same issue, but I have some plants standing both in front and behind a fence, the fence is centered between the two row of plants. All plants are using the same mesh but the fence is another mesh. 

From the other side of the fence everything looks great, no issues at all, but on the front side (see image) there's constant flickering and it does not know what to render first. It could probably be fixed if i divided the plants mesh into 2 separate meshes, so there's one in front of the fence and one behind, but I feel like it should also work using one mesh? Also the issue disappears if I use alpha scissor but this does not look good (bad edge).

![image](https://user-images.githubusercontent.com/24936603/39751535-cad9aec6-52b8-11e8-8900-923152a9b7fc.png)

**Comment by reduz** [comment] 2018-09-06 17:27
priority does not matter, as transparent objects always render last. I think what is missing is adding a decal option. Will not be implemented now, so kicking to 3.2

**Comment by nathanwfranke** [comment] 2019-10-19 05:26
Any update on this? My game has models made of multiple parts, some being transparent. Thus, a fix for decals alone might not solve my issue.

**Comment by clayjohn** [comment] 2019-10-19 16:09
@nathanwfranke there is a few connected issues going on. The transparency issue should be fixed already for 3.2. the issue here is that there is no depth test so the decal draws over everything.

**Comment by KoBeWi** [comment] 2020-11-06 22:14
From documentation of Material:
> Note: this only applies to sorting of transparent objects. This will not impact how transparent objects are sorted relative to opaque objects. This is because opaque objects are not sorted, while transparent objects are sorted from back to front (subject to priority).

The cube is opaque. When you enable transparency, the decal shows correctly behind it.

**Closed by KoBeWi** 2020-11-06 22:14 UTC
Labels: bug, topic:rendering
