### ISSUE TITLE
RPC {Method} is not allowed from {ID}. Mode is 0. Master is 1.

### ISSUE THREAD

**Issue by AlexAndDraw** [godotengine/godot#22757] opened 2018-10-05 11:24 UTC
3.1

I am getting this [ERROR](https://media.discordapp.net/attachments/466075013095751690/497495074301804547/ERR1.png)

**SCRIPTS**

*  [Server Connection Manager](https://cdn.discordapp.com/attachments/295745870752776203/497563749931155457/unknown.png)

* [Server Game Script](https://cdn.discordapp.com/attachments/295745870752776203/497564093947969546/unknown.png)

* [Client Connection Manager](https://cdn.discordapp.com/attachments/295745870752776203/497565538688696330/unknown.png)

The error seems to show up on the [clients](https://cdn.discordapp.com/attachments/295745870752776203/497566100976828416/unknown.png) but despite that it still seems to work on the [server](https://cdn.discordapp.com/attachments/295745870752776203/497566333568024597/unknown.png) regardless. 

If it matters:

I'm building a room-based server. Each room has two player objects and a unique legible name. The client will interface with the server via the counterpart room nodes (ie player one and two are in room one and send to and from room one, where players three and four are in room two and send to and from room two).

**Comment by AlexAndDraw** [comment] 2018-10-05 14:41
Checking over it again and I was getting this error previously (possibly including in 3.0) but it was less readable.

**Comment by AlexAndDraw** [comment] 2018-10-05 15:17
So RPC_ID(1, "tempConfirm"), seems to work. However I had tried that earlier to no apparent change.

**Comment by Chaosus** [comment] 2018-10-05 16:29
You have probably miss `set_network_master(1)` on client side, to allow server to use rpc on client. Anyway cc @Faless

**Comment by AlexAndDraw** [comment] 2018-10-05 17:31
@Chaosus Setting master to 1 (the server) on client causes the same error.  To be precise

Server calls "initialize" -> At the end of initialize, the game node RPC's "tempConfirm" (which is on the server). This is where the error is occurring.

**Comment by Faless** [comment] 2018-10-05 17:38
@AlexAndDraw where is `tempConfirm` defined? I can't find it in the screenshot you linked (ps. please, next time use a [gist](https://gist.github.com/) or post the code. Images are not searchable).
It looks like its mode is `0` [which means disabled](http://docs.godotengine.org/en/latest/classes/class_multiplayerapi.html#enumerations) (i.e. you didn't set the network keyword for it).

**Comment by AlexAndDraw** [comment] 2018-10-05 17:40
tempConfirm is defined on the game node on the server. 

https://cdn.discordapp.com/attachments/295745870752776203/497564093947969546/unknown.png <- Second from the bottom. 

Do I need to explicitly define a client-side version too?

**Comment by Faless** [comment] 2018-10-05 18:01
> Do I need to explicitly define a client-side version too?

@AlexAndDraw yes you do. Both sender and receiver checks if the function is allowed to be called

**Comment by AlexAndDraw** [comment] 2018-10-05 18:18
So I have no idea how to do that properly? Writing "remote tempConfirm" on the game client or using game.rpc_config("tempConfirm", 1)  both give me the same error.

**Comment by Faless** [comment] 2018-10-05 18:35
Well, the node where you are calling the RPC must have the function defined with the right RPC mode.
```
remote tempConfirm():
  pass
```
Should work, as long it's on the right node.
I can't help you without seeing the code.
This seems to be a logical error, not a bug in the engine.
If you can provide a minimal reproduction project I could help you further.
Otherwise I would close this issue as, again, this does not seem to be a bug in the engine.

**Comment by AlexAndDraw** [comment] 2018-10-05 18:44
This one was one me yeah. Close away. Thanks.

**Closed** 2018-10-05 20:28 UTC
Labels: archived, topic:network
