### ISSUE TITLE
Reflection Probe Mask Broken in Forward Clustered Renderer

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#55345] opened 2021-11-26 10:45 UTC
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

Reflection Probe Cull mask should determine which objects are being rendered in the reflections, however instead, they determine which objects are being rendered in the reflections and which objects get affected by the reflections, which is inaccurate behavior

see https://docs.godotengine.org/en/stable/tutorials/3d/reflection_probes.html

Forward Mobile Renderer has the appropriate behavior

### Steps to reproduce

Create a Reflection Probe Setup, with Object(s) that are reflective with cull mask 1, and Object(s) that are supposed to be visible in the reflection with cull mask 2.
Set Reflection Probe Mask to 2, and toggle mask 1 on and off -> observe how reflective objects with cull mask only set to 1 stop getting Reflections from the probe when Cull mask 1 is set to off on the Probe

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7608182/Bug.zip)

**Comment by WrobotGames** [comment] 2022-03-15 18:54
Due to this bug it wasn't possible to render car reflections. I want the capture inside of the car but obviously don't want the inside of the car to be visible in the reflection. But when I use the mask feature the reflections turn off for the car. This makes the probe useless.

**Comment by Calinou** [comment] 2022-03-15 19:44
Duplicate of https://github.com/godotengine/godot/issues/50195.

**Closed by Calinou** 2022-03-15 19:44 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
