### ISSUE TITLE
On MacOS screens are detected incorrectly

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#83587] opened 2023-10-18 23:08 UTC
### Godot version

4.1 stable

### System information

MacOS Sonoma 14.0

### Issue description

On MacOS, Godot's understanding of monitors is chaotic.
"Primary screen", "Other screen", "Screen with mouse" etc do not work. It is hard to deduce the system, but each time the screen that is chosen has no logical connection to a selected option. For example, sometimes it is always on one of the screens, and changing `Initial Position Type` does nothing. Sometimes it suddenly switches to other screen, again without any reason.
`Initial Position` also behaves strangely, so that if set to "0, 0" it will not necessarily be the center of the screen.

### Steps to reproduce

`Settings - General - Display - Window - Initial Position Type`
"Initial positions" do not work as intended.
`DisplayServer.window_set_current_screen(0)` also does nothing, game window stays on the same screen regardless of the supplied parameter.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment] 2023-10-25 18:53
`Screen with mouse/keyboard` options should be fixed by https://github.com/godotengine/godot/pull/83824, for other options I can't reproduce the issue. Note that if you are running from the editor, the initial position project setting is overridden by the editor settings.

**Comment by AThousandShips** [comment] 2024-07-29 18:10
Closing as resolved, if any of these issues can still be reproduced please open a new issue

**Closed by AThousandShips** 2024-07-29 18:10 UTC
Labels: bug, platform:macos, topic:porting, needs testing
