### ISSUE TITLE
The difference between Godot and Bullet physics

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#17638] opened 2018-03-19 21:23 UTC
**OS/device including version:**

Godot 3.0.X Win 64

**Issue description:**

Strange behavior under using Bullet physics.
It differs from Godot physics.

**Steps to reproduce:**
1 Set Bullet physics . A little run
2 Set Godot physics. Re-run and compare the results.

**Minimal reproduction project:**

https://yadi.sk/d/KchEad_h3TYcw6

**Comment by groud** [comment] 2018-03-20 10:23
I think that's normal. cc @AndreaCatania

**Comment by AndreaCatania** [comment] 2018-03-20 10:48
I didn't run the project, but as groud said it's normal because are two different software

**Comment by groud** [comment] 2018-03-20 10:49
Ok, if this is expected I close the issue. (Also, Godot physics should be deprecated soon ;) )

**Comment by ret80** [comment] 2018-03-20 11:43
Do not look but close! Still I insist that you study this issue. Since the bullet physics behaves extremely strange for physics in general. It's hard to describe. I will open the problem.

**Comment by AndreaCatania** [comment] 2018-03-20 12:08
It's not required that you open another issue even if this is closed. Can you please make a video that show this difference? I can't check it right now

**Comment by ret80** [comment] 2018-03-20 12:14
No at this moment. I'll try to do a little later.

**Comment by ret80** [comment] 2018-03-20 17:33
I do not know how well it turned out to demonstrate problems.
https://yadi.sk/i/TdWEcm2b3TaaTJ

**Comment by ret80** [comment] 2018-03-20 17:40
The video is not very good quality. Problems with the velocity. She shows no sign of abating. apply_imports why it is not working. The image twitches.

**Comment by AndreaCatania** [comment] 2018-03-20 18:21
The problem is not the physics engine, and it works on Godot physics just for a case.

The problem is in the Player.gd file, in the function _physics_process at line 79 you call this function:

    set_linear_velocity(vel)

This function set the velocity of body and ignore previous states of it.
Few line above you have `vel.y = 0` that remove the gravity applied by physics engine, so you have 0 gravity for this reason.
Also the jump should be handled in the same place where you handle the rigid body movement.

An advice is use forces and impulse instead of set_velocity, so you can benefit from physics engine internal calcs. If you want for some reason use set_velocity at this point you have to take care by gravity and jump velocity each frame by yourself

**Comment by ret80** [comment] 2018-03-20 20:45
@AndreaCatania I do not set Y= 0 for the speed. I set Y=0 to move the character horizontally.
Commented code. Perhaps will become clearer. Please note the line:

```
vel += get_linear_velocity()
```

Player.gd

```
        var vel = Vector3(0, 0, 0) # create a vector of the speed of movement of the character
	if Input.is_key_pressed(KEY_W):
		vel = transform.basis.xform(Vector3(0, 0, 1)).normalized() * speed # we expect forward direction	
	if Input.is_key_pressed(KEY_S):
		vel = transform.basis.xform(Vector3(0, 0, -1)).normalized() * speed
	if Input.is_key_pressed(KEY_A):
		vel = transform.basis.xform(Vector3(1, 0, 0)).normalized() * speed
	if Input.is_key_pressed(KEY_D):
		vel = transform.basis.xform(Vector3(-1, 0, 0)).normalized() * speed
	vel.y = 0 # just in case reset the value of Y so as to move to the side it is not needed.
	vel += get_linear_velocity() # add the current speed to the direction of travel. Y this may not be 0
	vel.x = clamp(vel.x, -5, 5) # These 2 sink that the a terrible. Need to the player is not accelerated to escape velocity. I agree that a bad decision. Fix
	vel.z = clamp(vel.z, -5, 5) 
	set_linear_velocity(vel) # We change the speed taking into account the past
```

I will try to alter the code to your Board through: ```_integrate_forces( PhysicsDirectBodyState state )```

In the meantime, I'm not sure the differences in physics are related to my bad code.

**Comment by ret80** [comment] 2018-03-20 21:36
@AndreaCatania Updated example. Get better. But the image floats when moving.
https://yadi.sk/d/KchEad_h3TYcw6

**Comment by vonflyhighace2** [comment] 2018-04-01 04:47
Bullet physics does not work with Areas. Is this by design, or an oversight? try as you might getting a area to register a bullet based physics object returns nill.

**Comment by AndreaCatania** [comment] 2018-04-01 05:51
@vonflyhighace2 Areas works in godot with bullet physics. If something is not working correctly open an issue about it

**Comment by AndreaCatania** [comment] 2018-04-01 05:56
@ret80 I written some docs about rigid body, check it: https://github.com/godotengine/godot-docs/pull/1277

**Comment by vonflyhighace2** [comment] 2018-04-01 19:30
there seems to still be issues with the 3D areas. 2D maybe but on the 3D side its completely broken. There are other issues submitted with similar issues to mine as well.

**Comment by AndreaCatania** [comment] 2018-04-01 20:47
Strange, I did two PR about areas  and it was registering rigid body overlap correctly... Can you give me the link to your issue please?

**Comment by vonflyhighace2** [comment] 2018-04-01 22:03
Sorry where those PR recent? I have not tried any new builds yet and am running an older build. I'll do a test on the updated Master and report back.

**Comment by AndreaCatania** [comment] 2018-08-26 07:26
Is the fix of this problem confirmed?

**Comment by vonflyhighace2** [comment] 2018-09-04 04:52
Yes this is still an issue…can reproduce this in 3.1 alpha.. overlapping areas seem to be ignored or missed when using the bullet engine…the legacy engine has no issues like this.

________________________________

**Comment by KoBeWi** [comment] 2020-06-13 15:54
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by madmiraal** [comment] 2020-09-25 10:21
The OP issue description is very vague, but using the description from a later [comment](https://github.com/godotengine/godot/issues/17638#issuecomment-374690451):
> Problems with the velocity. She shows no sign of abating. apply_imports why it is not working. The image twitches.

1. As explained by @AndreaCatania in his [response](https://github.com/godotengine/godot/issues/17638#issuecomment-374704875), this issue occurs in Godot physics too, and it's because `RigidBodies` should not have their velocity changed every frame; instead forces and impulses should be used.
2. I'm not sure what is meant by `apply_imports`, but I think it's safe to assume it's unrelated to physics.
3. I've looked at the MRP provided in 3.0.6 and there was definitely a jitter in Bullet that was not there in Godot physics. This issue has gone a way in 3.2.3.

The discussion did shift to Areas not working; specifically:
> RigidBody in Character mode does not register collision with 3D areas.

I've tested this, and a `RigidBody` in `Character` mode is definitely detected by an `Area` in 3.2.3. Since there is no MRP, I'm not sure what the issue is or was. If this is a valid issue, @vonflyhighace2, please create a new issue with an MRP.

Therefore, closing this issue as resolved in 3.2.

**Closed by madmiraal** 2020-09-25 10:21 UTC
Labels: bug, topic:physics

**Comment by Zireael07** [comment] 2020-09-25 10:46
apply_imports is likely a typo for apply_impulse, FYI ;)

**Comment by madmiraal** [comment] 2020-09-25 14:56
I've tested the OPs project in 3.0-stable and `apply_impulse` (jump) was definitely working back then; so I'm not sure what the issue was.
