### ISSUE TITLE
Script Editor jitters when scrolling while dragging file with Scroll Past End Of File enabled

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#61291] opened 2022-05-22 19:21 UTC
### Godot version

3.5rc1

### System information

Linux/Ubuntu 21.10

### Issue description

Dragging a file from the filesystem dock into the script editor now scrolls the view when the mouse cursor is on the top or bottom. This causes an issue when the editor setting `text_editor/cursor/scroll_past_end_of_file` is enabled, where if you scroll down enough it will jitter the text edit (see attached video)

https://user-images.githubusercontent.com/24468819/169712240-b725b05f-c1b2-479f-aeca-8803b473b482.mp4

### Steps to reproduce

1. Enable `Scroll Past End Of File` in the Editor Settings
2. Open a script and drag a file into it from the filesystem dock
3. Move your mouse to the bottom

**Comment by kleonc** [comment] 2022-05-25 09:05
Duplicate of #59822.

**Closed by kleonc** 2022-05-25 09:05 UTC
Labels: bug, topic:editor, confirmed
