### ISSUE TITLE
TimeMap random blink

### ISSUE THREAD

**Issue by miblooming** [godotengine/godot#32698] opened 2019-10-10 06:57 UTC
**Godot version:**
Godot_v3.1.1

**OS/device including version:**
Windows7 x64

**Issue description:**
TimeMap random blink

**Steps to reproduce:**
Open and run the demo "Kinematic Character".
Click the game Window Title Bar to fouce on the Window.
See the video:
[20191010144810rec.zip](https://github.com/godotengine/godot/files/3710899/20191010144810rec.zip)

**Minimal reproduction project:**
The demo "Kinematic Character" of Godot.

**Comment by groud** [comment] 2019-10-10 08:00
Duplicate of #9913

**Closed by groud** 2019-10-10 08:00 UTC
