### ISSUE TITLE
Multiple OmniLight3Ds result in incorrect intensity on mobile renderer 

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#70057] opened 2022-12-14 14:10 UTC
### Godot version

4.0.beta8

### System information

macOS 13.0.1

### Issue description

If you have more than one OmniLight3D in a scene using the mobile renderer, the light closest to the camera will for some reason get an exaggerated intensity. The effect is not gradual like a distance fade (which is turned off for the lights) but instant as you can see below.

https://user-images.githubusercontent.com/17763524/207616193-f8e48910-5a78-4e39-a8d7-a467ba6a2368.mov

https://user-images.githubusercontent.com/17763524/207616239-6da661f1-e9b9-4e27-bd1e-6a0260aef994.mov

### Steps to reproduce

- Create a 3d scene
- Add a simple plane mesh (or something else to light)
- Add an OmniLight3d
- Duplicate the OmniLight3d

Observe that the light closest to the camera will get incorrect intensity as long as there is more than one light visible.

### Minimal reproduction project

[mobile_omnilight_intensity_bug.zip](https://www.lostminds.com/godot/mobile_omnilight_intensity_bug.zip)

**Comment by mrjustaguy** [comment] 2022-12-14 17:39
this is a known issue. See https://github.com/godotengine/godot/issues/55881

**Comment by clayjohn** [comment] 2022-12-14 17:44
Thanks for the report, but yes, this is a duplicate of https://github.com/godotengine/godot/issues/55881

I will close this issue so that it can be tracked in one place

**Closed by clayjohn** 2022-12-14 17:44 UTC
Labels: bug, topic:rendering, topic:3d
