### ISSUE TITLE
Adding a Script to a Resource causes OS Crash

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#30660] opened 2019-07-17 20:13 UTC
**Godot version:** 3.1.1

**OS/device including version:** Solus Gnome 4.0

**Issue description:**

When I add a GDSCript to a Resource file using the Inspector->Script->New GDScript and I open the Script, Godot freezes and after a few seconds my whole system crashes as well, so I have to make a **hard reset**

**Steps to reproduce:**
1. Using the Inspector create a new `Resource` (Create a new resource in memory and edit it)
2. Save this `Resource` to the disk (save the current edited resource)
3. Go to the `Resource` file in the FileSystem dock, double click it so the Inspector "opens" it
4. In the `Reference/Script` cathegory go to the `Script` property and in the drop down menu click on `New GDScript`
5. Click on the Built-in(?) GDScript just created to open it in the Script Editor
6. Try to `File->Save as`

You can check this in the live stream I recorded today [at this exact moment](https://youtu.be/VL-D6zdoBsw?t=4262) the moment the livestream ends is exactly when my system crashed as well

**Comment by dragmz** [comment] 2019-07-19 05:31
Cannot reproduce OS crash on Windows (although I can reproduce Godot crash).

**Comment by dragmz** [comment] 2019-07-19 12:21
Seems to overflow a stack:
https://gist.github.com/dragmz/0b0e878b94b7e437de515480db872c55

**Comment by creikey** [comment] 2019-08-09 02:55
I was unable to reproduce on linux following the reproduction steps.

**Comment by henriiquecampos** [comment] 2019-08-09 15:53
> I was unable to reproduce on linux following the reproduction steps. There was no crash or other error, everything seemed to work properly

Try to do that without a scene open and don't attach the resource to any node.

**Comment by Paulb23** [comment] 2019-09-21 13:16
Seems similar to #27380. Was this fixed by #31985?

**Comment by capnm** [comment] 2019-09-21 16:00
> Try to do that without a scene open and don't attach the resource to any node.

Can not reproduce with 3.2.alpha.custom_build. 2e065d8ad

**Comment by dragmz** [comment] 2019-09-21 18:30
Can no longer reproduce with 2e065d8ad

**Comment by Paulb23** [comment] 2019-09-22 17:10
Closing as fixed by #31985.

**Closed by Paulb23** 2019-09-22 17:10 UTC
Labels: bug, crash, topic:core
