### ISSUE TITLE
Godot not closing when quiting.

### ISSUE THREAD

**Issue by henres** [godotengine/godot#84967] opened 2023-11-16 08:00 UTC
### Godot version

4.2-beta6-mono

### System information

Godot v4.2.beta6.mono - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu Nov  9 02:34:53 UTC 2023 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV GFX1100) () - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Hello,

When trying to quit godot, the godot editor goes grey and I got this error in the terminal:

```shell
EditorSettings: Save OK!
Unloading: Disposing tracked instances...
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
```

It's only happening in the beta6. No problem in the beta5. But I still have the same error showing. So I'm not sur if the error is relevant.
```shell
EditorSettings: Save OK!
Unloading: Disposing tracked instances...
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
Unloading: Finished disposing tracked instances.
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
PulseAudio: context terminated
Updated PSO cache (0.7 MiB)
```

Thanks

### Steps to reproduce

* Open Godot 4.2 beta6
* Create a new project
* Select `Scene -> Quit` or `Ctrl + Q`
* Godot will stay open

### Minimal reproduction project

Just create a new project from Godot 4.2 beta6

**Comment by akien-mga** [comment] 2023-11-16 08:09
Thanks for the report.

- Duplicate of https://github.com/godotengine/godot/issues/84728

**Closed by akien-mga** 2023-11-16 08:09 UTC
