### ISSUE TITLE
Changing node's type that has an attached script does not update node icon.

### ISSUE THREAD

**Issue by beamer159** [godotengine/godot#81757] opened 2023-09-16 19:49 UTC
### Godot version

4.1.1.stable

### System information

Windows 11

### Issue description

When a node has a script attached, changing that node's type does not update the node's icon in the Scene dock. The icon seems to be tied to the scripts `extends [NODE_TYPE]` line, where the icon will be `NODE_TYPE`'s icon. Even then, changing this line to reflect the new type and saving the script does not updating the node icon. The scene must then be closed and reopened to update the node's icon.

Expected behavior: When a node's type is changed in the Scene dock, the icon will change immediately to reflect this new type. If this type does not match the type extended by an attached script, a warning icon could appear next to this node in the Scene dock notifying the user about this discrepancy.

### Steps to reproduce

1. Create a new 2D scene (new scene with a root `Node2D` node). The node icon is a blue ring, denoting a `Node2D` node.
2. Attach a script to the `Node2D` node.
3. Right-click the `Node2D` node in the scene dock, choose "Change Type", and change the type to a `Node` node. Expected behavior is that the icon changes to a white ring, denoting a `Node` node type. Actual behavior is that the icon remains a blue ring.

Even changing the script to `extends Node` and saving the project does not change the node's icon. However, closing and reopening the scene does change the node's icon, after changing the script as described above. Note that you can change the script to extend any arbitrary node type, and the node's icon will change to reflect this arbitrary node after reopening the scene.

### Minimal reproduction project

A project cannot show this issue since it's fixed when the project is closed and reopened. Instead, I attached a video displaying the issue in a minimal project.

https://github.com/godotengine/godot/assets/7436252/894acb49-8ba4-4f89-8a36-dbd1871ac066

**Comment by Deozaan** [comment] 2023-09-18 07:59
Duplicate of one of these: #76983 #79226 #81276

**Comment by akien-mga** [comment] 2023-09-18 08:07
Indeed, this is fixed in 4.2. Thanks for the report!

**Closed by akien-mga** 2023-09-18 08:07 UTC
