### ISSUE TITLE
Connect button pressed signal through the code is not working.

### ISSUE THREAD

**Issue by JBingrun** [godotengine/godot#57098] opened 2022-01-23 20:05 UTC
### Godot version

4.0.dev (dd6e5b3)

### System information

Windows 11, Vulkan API 1.2.170, NVIDIA GeForce GTX 1050 Ti

### Issue description

Trying to connect button pressed signal but return an error message:

```
Line 12:Cannot find property "connect" on base "bool".
Line 12:Function "connect()" not found in base bool.
```

I've also tried the button-down signal and is working fine.

```
extends Node

@onready var btn: Button = $Button

func _ready():
	btn.pressed.connect(btn_press)
	btn.button_down.connect(btn_down)

func btn_press():
	print("btn_pressed!")
	
func btn_down():
	print("btn_down!")
```

### Steps to reproduce

- Add a button node.
- Trying to connect its pressed signal through the code.
- The error shows up.

**Comment by akien-mga** [comment] 2022-01-23 20:14
Duplicate of https://github.com/godotengine/godot/issues/38937

**Closed by akien-mga** 2022-01-23 20:14 UTC
Labels: bug, topic:gdscript
