### ISSUE TITLE
Baking NavigationMeshInstance using the action prevent further edition of the NavigationMesh properties

### ISSUE THREAD

**Issue by SylvestreMassalaz** [godotengine/godot#51400] opened 2021-08-08 15:21 UTC
### Godot version

3.4.0-beta3

### System information

Windows 10, GLES3, NVidia RTX 2070

### Issue description

When working with navigation and navigationMeshInstance, after clicking on Bake NawMesh in the editor, the properties of the NavMesh ressources are no longer editable (you can not open dropdowns, edit numeric fields...). The issue persists until the resource panel is closed and reopen (either by closing and opening the resource or changing nodes in the scene tree).

### Steps to reproduce

- Create a new scene
- Add a navigation node, and a NavigationMeshInstance as it's child
- Add Some content under the mesh to have something to bake to (maybe optional?)
- Select the navigationMeshInstance Node 
- Click Bake NavMesh in the editor

### Minimal reproduction project

[BugReport340Beta3.zip](https://github.com/godotengine/godot/files/6951004/BugReport340Beta3.zip)

**Comment by akien-mga** [comment] 2021-08-09 07:42
Confirmed in 3.3.2-stable too, so it's not a recent regression.

To clarify the issue, it seems to happen when the `navmesh` subresource of the NavigationMeshInstance was expanded *before* pressing Bake NavMesh. Then indeed, the Inspector behaves weirdly. You can see in this GIF how the click actions work only every now and then:

![Peek 2021-08-09 09-41](https://user-images.githubusercontent.com/4701338/128673709-03cfdd87-6f0e-47c6-814d-f9a0ee7ca359.gif)

**Comment by snougo** [comment] 2021-09-14 15:55
I got this issue too in 3.4 beat4

**Comment by smix8** [comment] 2022-05-15 22:23
@akien-mga 
This is the same selection issue as in #34764 which seems to be fixed in Godot 4.0 and 3.5 so this can be closed too?

**Closed** 2022-05-16 10:58 UTC
Labels: bug, topic:editor, confirmed, topic:navigation
