### ISSUE TITLE
Game resolution clamps to the lowest one if using multiple monitors in fullscreen mode

### ISSUE THREAD

**Issue by MUTEDGALAXY** [godotengine/godot#45627] opened 2021-02-01 11:13 UTC
**Godot version:**
3.2.3 Stable.

**OS/device including version:**
OS: Windows 10
GPU: RTX 2060
GLES3
Main monitor: 2560x1440
Second Monitor: 1920x1080

**Issue description:**
Fullscreen is not working properly when having multiple monitors and launching a game on the biggest one.

**Steps to reproduce:**
launch any game one the biggest monitor with fullscreen enabled

**Minimal reproduction project:**
Works with any project.

![image](https://user-images.githubusercontent.com/53514993/106451189-4d739280-64da-11eb-92ea-7ec469f212ee.png)

![image](https://user-images.githubusercontent.com/53514993/106451412-a6dbc180-64da-11eb-8c48-88768cd85e50.png)

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:17
![image](https://user-images.githubusercontent.com/53514993/106451928-5022b780-64db-11eb-8429-393c3f1fa7e6.png)

same result even with this

**Comment by floppyhammer** [comment] 2021-02-01 11:41
Window size has no effect when fullscreen is turned on unless you change the stretch mode below as well.

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:42
I tried swithching stretch mode to Viewport or 2D. No effect

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:44
> Window size has no effect when fullscreen is turned on unless you change the stretch mode below as well.

And that's not my problem. My problem is that the game window doesn't scale to my monitor resolution and clamps at 1920x1080

**Comment by floppyhammer** [comment] 2021-02-01 11:45
It seems I misunderstood your problem. Fullscreen work fine for me in either case, even when I use a ridiculously high resolution.

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:46
Weird... I'm using default settings. Maybe because of the second monitor?

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:47
Woah. I disabled second monitor and game scaled to my main motior. Looks like in fullscreen mode game resolution just clamps to the lowest one.

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:49
That's a bug actually.

**Comment by floppyhammer** [comment] 2021-02-01 11:51
I could not reproduce this issue with a second monitor of lower resolution attached. What is your Windows Multiple displays setting (duplicate or extend)?

**Comment by MUTEDGALAXY** [comment] 2021-02-01 11:53
Extend

**Comment by floppyhammer** [comment] 2021-02-01 11:58
My devices:
OS: Windows 10
Main monitor: 2160x1440
Second monitor: 1920x1080

Godot settings:
![image](https://user-images.githubusercontent.com/28705694/106455813-a980eb80-64c7-11eb-885b-09afac38cf9e.png)
Windows settings:
![image](https://user-images.githubusercontent.com/28705694/106455887-c4536000-64c7-11eb-91d7-a2449d67ca3e.png)

Fullscreen works fine for me.

**Comment by MUTEDGALAXY** [comment] 2021-02-01 12:03
I tried using 150% scaling now it's just flickering. I'm using 100% as default. And my project settings are exactly the same

**Comment by Calinou** [comment] 2021-02-01 15:32
Duplicate of https://github.com/godotengine/godot/issues/21674.

**Closed by Calinou** 2021-02-01 15:32 UTC
