### ISSUE TITLE
The child node added under the inherited Window node cannot be selected or dragged in its position in the 2D editor

### ISSUE THREAD

**Issue by SpriteSword** [godotengine/godot#81687] opened 2023-09-15 10:08 UTC
### Godot version

4.1.1.stable.mono

### System information

Win10

### Issue description

尝试在继承于Window节点下面添加子节点，发现不能在2D编辑器中选中、拖拽它的位置。

![屏幕截图 2023-09-14 185748](https://github.com/godotengine/godot/assets/106657877/4972bc2d-1265-4563-a5de-a6c1a67d3206)

### Steps to reproduce

添加个继承于Window节点的节点（如AcceptDialog），在该节点下面随便添加个子节点

点击该子节点，发现在2D编辑器中毫无反应，也不能在2D编辑器中选中、拖拽它的位置。

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-09-15 10:38
Duplicate of #20619 (Window inherits Viewport)

**Closed by KoBeWi** 2023-09-15 10:38 UTC

**Comment by AThousandShips** [comment] 2023-09-15 10:44
Also in the future please open issues in English, use online translation tools if needed
