### ISSUE TITLE
Editor: TouchScreenButton is not following Camera2D even under another CanvasLayer, but works in the web

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#78992] opened 2023-07-03 16:45 UTC
### Godot version

4.1.rc2

### System information

Windows 11, gl_compatibility

### Issue description

_UPDATE:_ This is an issue in the editor only. I've exported it to HTML5 and it runs fine in my browser. I've re-opened my editor and no success as well.

I've a HUD that is expectedly following the `Camera2D`. However, only the left analog (which inherits `TouchScreenButton`) is not following the camera, and that analog is at the same `CanvasLayer` of the working UI.

![image](https://github.com/godotengine/godot/assets/110610266/6ebfc0fc-4f67-48b6-a040-3edeb51e8bbd)

And, for example, if I add a `ColorRect` as a direct child of `touch_controls`, it works fine.

Here's the actual issue:

https://github.com/godotengine/godot/assets/110610266/196e8c9f-b726-41ff-8562-0d46544d4a87

### Steps to reproduce

- 1. Add a `Camera2D` to some entity
- 2. Add a `TouchScreenButton` somewhere inside a `CanvasLayer`.

### Minimal reproduction project

This MRP works: I don't know the reason.

[godot-camera-touch.zip](https://github.com/godotengine/godot/files/11939780/godot-camera-touch.zip)

**Comment by hydroper** [comment] 2023-07-03 17:27
Strangely the minimal repro works. That's what I've in my actual production's analog (a `TouchScreenButton`):

![image](https://github.com/godotengine/godot/assets/110610266/589f2898-c07a-4902-9ebd-11aa7b99220e)

The `bg` is not following the camera. Why?

**Comment by hydroper** [comment] 2023-07-03 17:32
Added a video demonstrating the issue.

**Comment by hydroper** [comment] 2023-07-03 17:40
I discovered this is an issue in the editor only. It doesn't happen when I export my project to HTML5 and run it through itch.io

**Comment by Zireael07** [comment] 2023-07-03 17:59
Does the issue go away if you switch to Compatibility?

**Comment by hydroper** [comment] 2023-07-03 18:17
@Zireael07 Yes! The renderer was set to `forward_plus`.

**Comment by Zireael07** [comment] 2023-07-03 18:34
In that case duplicate of another issue that I can't find at the moment.

**Comment by Calinou** [comment] 2023-07-03 18:42
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.

**Closed by Calinou** 2023-07-03 18:42 UTC

**Comment by arkology** [comment] 2023-07-03 18:54
So this happens not only with w10 but also will w11 too. Interesting.
