### ISSUE TITLE
[Godot 3.0alpha1] Inspector pane shows empty when run scene

### ISSUE THREAD

**Issue by ricpelo** [godotengine/godot#10342] opened 2017-08-14 17:30 UTC
**Operating system or device - Godot version:**

PC with Ubuntu 16.04 LTS, Godot 3.0 alpha1

**Issue description:**

When I run a project or scene, the Inspector pane gets empty and I can't change any properties of the selected node. This issue can't be reproduced with Godot 2.1.

**Steps to reproduce:**

1. Create a scene with some nodes.
2. Ensure a node (any node) is selected, and its properties shows in the Inspector pane.
3. Run the scene using any method (F5, F6 or Ctrl+Shift+F5, there's no difference).

The game window appears but you can see that the Inspector pane in the Godot editor becomes empty even with a node selected in the Scene pane.

You need to click in a node again (in the Scene pane) to fill the Inspector pane with its properties.

![2017-08-14-192313_1280x1024_scrot](https://user-images.githubusercontent.com/616169/29283442-0113f140-8127-11e7-90cd-dde945d81c95.png)

**Comment by vnen** [comment] 2017-08-14 21:48
Duplicate of #9408

**Closed by vnen** 2017-08-14 21:48 UTC
