### ISSUE TITLE
Editor crashes with imported fonts in certain circumstances

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4855] opened 2016-05-28 11:29 UTC
**Operating system or device - Godot version:**

Arch Linux, Godot 2.1 Git (https://github.com/godotengine/godot/commit/b6fdac80cb0716f4c64aed9d0920159b50e2ed15)

This issue seems to happen only with the Clang compiler. Version used here is `clang version 3.8.0 (tags/RELEASE_380/final)`. With GCC `gcc (GCC) 6.1.1 20160501`, this bug does not seem to occur.

**Issue description** (what happened, and what was expected):

The editor will crash in at least two circumstances when using imported bitmap fonts:

- Double-clicking **res://** in the FileSystem tab with a font imported at the project root.
- Setting the editor font to an imported font.

After such a crash, if you re-open the project, it will crash again as soon as you open any scene, a few seconds after the opening, without leaving any error message.

**Link to minimal example project** (optional but very welcome): [test.zip](https://github.com/godotengine/godot/files/287684/test.zip)

**Comment by reduz** [comment] 2016-07-08 12:39
does this still happen? I think I managed to fix the crash bugs with fonts recently

**Comment by akien-mga** [comment] 2016-07-15 11:14
@Calinou Ping :)

**Comment by reduz** [comment] 2016-07-21 13:40
I'm closing as I'm certain I fixed it and can't reproduce it

**Closed by reduz** 2016-07-21 13:40 UTC
Labels: bug, topic:editor
