### ISSUE TITLE
Audio isn't working

### ISSUE THREAD

**Issue by mxt08-real** [godotengine/godot#47602] opened 2021-04-03 17:58 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
AudioStreamPlayer(2D, 3D and the normal) doesn't work in the inspector playing nor in the game.

**Steps to reproduce:**
I go to the scene, create a AudioStremPlayer[2D/3D], I upload different wav files, and it doesn't play the audio.

**Minimal reproduction project:** [Audio test.zip](https://github.com/godotengine/godot/files/6253161/Audio.test.zip)

**Comment by Calinou** [comment] 2021-04-03 18:46
@mxt08-real Can you get sound working in other games and applications? Double-check that Godot isn't muted in the system audio mixer.

**Comment by nonunknown** [comment] 2021-04-06 21:21
**Godot version:**
3.3 RC6 official

**OS/device including version:**
Windows 10 x64

**Details:**

Can't reproduce this error, both on editor and in-game it works

@mxt08-real Make sure to check your system audio, also turn on autoPlay in audiostream to test in-game

**Comment by akien-mga** [comment] 2021-04-29 16:47
Closing as there was no further update from the issue reporter and this doesn't seem to be a bug.

**Closed by akien-mga** 2021-04-29 16:47 UTC
Labels: bug, needs testing, topic:audio
