### ISSUE TITLE
TileMap ignores Tile Origin property in 3.2

### ISSUE THREAD

**Issue by jhlothamer** [godotengine/godot#41826] opened 2020-09-06 22:29 UTC
**Godot version:** 3.2.2 (3.2.3 rc5 too)

**OS/device including version:** Ubuntu 20.04/PC

**Issue description:**
The TileMap "Tile Origin" (cell_tile_origin) property setting is not honored.

**Steps to reproduce:**
Create scene with TileMap and TileSet in 3.1.  Set tile in cell (0,0).  Update "Tile Origin" in the inspector from Upper Left to Bottom Right.  You will see the tile image move down.  Setting "Tile Origin" to Center will move the tile image down and right.  Now open the same project/scene 3.2.  The tile image will be in the same place as the Upper Left origin setting no matter what the value of the property is set to.

**Minimal reproduction project:**
[32_tilemap_tile_origin_bug.zip](https://github.com/godotengine/godot/files/5180385/32_tilemap_tile_origin_bug.zip)

**Comment by Calinou** [comment] 2020-09-06 23:58
Could you try [bisecting the regression](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) to pinpoint the exact commit where the regression occurred? This will greatly speed up troubleshooting.

**Comment by Ranoller** [comment] 2020-09-07 00:35
Well, this is not a bug. The old behavior was incorrect. Tilemap origin is not texture position, is origin of the cell, to y-sort and other things. There is a "compatibility mode" button in tilemap poroperties to not break older projects.

**Comment by Ranoller** [comment] 2020-09-07 01:08
There is not bibisect needed. The commit was this: https://github.com/godotengine/godot/pull/30231 and was not a "collateral bug", that was exactly the expected result, and was added the compatibility for 3.1 and older. There are big explanations about that in older issues, but if is needed now other time i can made a resume with all the changes from 2.0 to 3.1 that changed tile origin from this primary use to a texture offset. There is a big discussion (very old, i will try to find that) of other contributors about the "use of tile origin" that become in a cascade of pull request that end in a strange positioning of textures and shapes.

**Comment by aaronfranke** [comment] 2020-09-07 08:16
Closing because, as stated above, this is an expected breakage and won't be changed in the engine.

**Closed by aaronfranke** 2020-09-07 08:16 UTC
Labels: bug, regression, topic:core
