### ISSUE TITLE
Godot Screen Pixel Jitter.

### ISSUE THREAD

**Issue by Gerarama** [godotengine/godot#41814] opened 2020-09-06 16:11 UTC
**Godot version:**
Godot 3.2.2 stable, and Godot 4.0
GLES 2,3 Vulkan

**OS/device including version:**

Windows 10 1909 , GTX 1070, I5 , 1360x780 screen.

**Issue description:**

Pixels snap randomly and offest and scaling isn't smooth and jitter, also screen differnets can snap the pixels randomly.
![as8](https://user-images.githubusercontent.com/61591052/92330030-941ca800-f074-11ea-9fdb-02e91f39552b.gif)
![as9](https://user-images.githubusercontent.com/61591052/92330031-941ca800-f074-11ea-9f18-70c2a932daaa.gif)

Pixel snap has no effect at all.
nor making the values smaller in godot source code.

**Steps to reproduce:**
Simply try to scale a sprite very slowly and you see line of tearing visible.
or change the viewport size while looking at your sprites.

**Minimal reproduction project:**
[jitter.zip](https://github.com/godotengine/godot/files/5179932/jitter.zip)

**Comment by Calinou** [comment] 2020-09-06 16:41
There is nothing that can be done about this with sprites that have filtering disabled. You must ensure that the scaling ratio is always an integer factor.

Duplicate of https://github.com/godotengine/godot/issues/6506.

**Closed by Calinou** 2020-09-06 16:41 UTC

**Comment by Gerarama** [comment] 2020-09-06 17:08
> There is nothing that can be done about this with sprites that have filtering disabled.

But the godot sprite doesn't have filtering disabled.

Also this maybe related to #24612

and #33949

Also i find this problem:

This is my texture without scalling anything at resolution of 640x480:
![Sword1](https://user-images.githubusercontent.com/61591052/92330975-ae0db900-f07b-11ea-81c5-fdbe266df379.png)

This is the same texture when scaling the resolution to 640x480 using animation player:
![Sword2](https://user-images.githubusercontent.com/61591052/92330985-c41b7980-f07b-11ea-80a0-6d0d3bf59f4b.png)

The texture broke out!

This is my texture when not scalling anything with without fullscreen:

![Sword3](https://user-images.githubusercontent.com/61591052/92330994-d72e4980-f07b-11ea-8f9c-ce16cfb84bbd.png)


This is my texture when scalling with without fullscreen:
![Sword4](https://user-images.githubusercontent.com/61591052/92330998-dc8b9400-f07b-11ea-92e6-9af46cdc7587.png)


Its not about the resolution only. when the animating the sprite makes some extra pixels. making the animation jitter.

>  You must ensure that the scaling ratio is always an integer factor to avoid scaling artifacts

I did during the testing, and you can see the resultions i chose in the "Snap" animation in my Minimal reproduction project

Please try to play the other two animations in the file to understand even more.

**Comment by AttackButton** [comment] 2020-12-12 18:55
I don't think this issue should be closed. Because in Godot version 3.2.4-beta-4, even with `transform_snap` enabled, this still happening.

Using the op MRP with the new `transform_snap` option:

![godot-jitter-screen-3 2 4-beta-4](https://user-images.githubusercontent.com/25422687/101992441-162ef500-3c92-11eb-8867-65494bca564d.gif)

**Comment by mortarroad** [comment] 2021-03-15 13:15
The jittering when sprites are scaled while using point sampling is inherent to the process.
However, it can be mitigated with some filtering, which will smoothly transition between neighboring pixels, while still keeping them pixelated.
I wrote a shader for that.

It should work as a drop in replacement.

Example:
![jitter](https://user-images.githubusercontent.com/80684659/111158734-b13cb100-8598-11eb-8fdb-5f8f27945f97.gif)
Both sprites on the left are scaled by the same amount.
The bottom one has the new filter on it.

I hope this is useful to someone.
[jitter.zip](https://github.com/godotengine/godot/files/6141346/jitter.zip)

**Comment by Zireael07** [comment] 2021-03-15 13:22
@mortarroad: It would be awesome if you posted this shader on either https://godotshaders.com/ or Godot Assetlib or the Godot subreddit, so that people could find it easier.

**Comment by mortarroad** [comment] 2021-03-15 14:43
Done: https://godotshaders.com/shader/sub-pixel-accurate-pixel-sprite-filtering/
