### ISSUE TITLE
AnimationPlayer - Animation list scroll bar Bug

### ISSUE THREAD

**Issue by Rogemcy** [godotengine/godot#92892] opened 2024-06-08 01:01 UTC
### Tested versions

 4.3 beta1 

### System information

win10 64bit

### Issue description

AnimationPlayer - Animation list scroll bar disappeared when running game or changing any node's visibility (maybe any operation?) . And the mouse wheel didn't work.
![20240608085026](https://github.com/godotengine/godot/assets/14737837/ce340638-245b-44c6-9e9e-923d774b3205)

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-06-08 02:06
This is a duplicate of #92614 and was already solved in latest mater in pr https://github.com/godotengine/godot/pull/92664

**Closed** 2024-06-08 08:37 UTC
