### ISSUE TITLE
System.Net.WebSockets.ClientWebSocket.Connect caused crashing when running on andorid device.

### ISSUE THREAD

**Issue by zhmt** [godotengine/godot#86949] opened 2024-01-08 03:58 UTC
### Tested versions

4.2.1 stable

### System information

windows 11 - Godot v4.2.1 stable - mobile

### Issue description
System.Net.WebSockets.ClientWebSocket.Connect caused crashing when running on andorid device. 

System information:
windows 11 - Godot v4.2.1 stable - mobile - .net 8.0
Android device:
Redmi note 11, android 13.
Export settings:
debug export, arm64-v8a, without gradle building.

Some logcat informations maybe useful:
```
2024-01-08 11:22:00.086 19965-20143 godot                   ezg.g5                               E  USER ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands
2024-01-08 11:22:00.086 19965-20143 godot                   ezg.g5                               E     at: unref (core/string/string_name.cpp:127)
2024-01-08 11:22:00.093 19965-20143 godot                   ezg.g5                               E  USER ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSetup
2024-01-08 11:22:00.093 19965-20143 godot                   ezg.g5                               E     at: unref (core/string/string_name.cpp:127)
2024-01-08 11:22:00.097 19965-20143 libc                    ezg.g5                               A  FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7dfc3f4e54)

```

### Steps to reproduce

Create a System.Net.WebSockets.ClientWebSocket, and try to connect to any server.
```
    var webSocketUrl = $@"ws://{"192.168.199.147"}:{5282}/ws";
    var serverUri = new Uri(webSocketUrl);
    ws = new ClientWebSocket();
    GD.Print("Connecting to Server " + webSocketUrl);
    ws.ConnectAsync(serverUri, CancellationToken.None);
```
It will be successful on desktop(windows 11), but crashed on android.

### Minimal reproduction project (MRP)

[GodotTest.zip](https://github.com/godotengine/godot/files/13856109/GodotTest.zip)

This is a simple demo that will reproduce this issue.

**Comment by saierXP** [comment] 2024-01-08 05:55
Duplicate of
* https://github.com/godotengine/godot/issues/84559

**Closed** 2024-01-09 16:57 UTC
