### ISSUE TITLE
Steam Deck Dpad unresponsive when rebound

### ISSUE THREAD

**Issue by POWERUPT** [godotengine/godot#72845] opened 2023-02-07 15:45 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Steam Deck (compiled on Windows 10, GTX 1060, Ryzen 5 2600)

### Issue description

I'm developing my game for Windows and Linux, with the Steam Deck in mind. I have developed a controls menu where controls can be rebound, and this works perfectly fine on Windows with all compatible controllers.
 
However, on my Steam Deck, the D pad is extremely unresponsive. My guess is that it works about 1/5 of the time, that is for every 5 inputs there is a chance that one will register. Sometimes it's more, sometimes less.

This only seems to happen in projects where controls are rebound from the defaults. I have included projects that exemplify this for anyone with a Steam Deck.

I have tried to nail down whether it's a general controller issue on Linux, which it is not. On my Linux laptop an Xbox One controller works perfectly fine with no issues. I have also plugged the Xbox One controller into my Steam Deck using a USB A to USB C adapter, and it also works perfectly fine.

I initially found that it worked fine after using the default ui_<direction> bindings instead of custom ones, but in the main project the issue still persists, I'm guessing because I load the bindings from a file on startup.

I asked about this on the Godot forums, was told that this was related to a past issue and may have not been fixed entirely or regressed.

### Steps to reproduce

1. Use the latest version of Godot 3 (3.5.1 stable)
2. Create a project where the input bindings for the dpad are modified (Or use sample)
3. Compile for Linux
4. Get the file onto the Steam Deck via USB, FTP, etc
5. Run on the Steam Deck in controller mode (If running from desktop hold the start button until you hear a beep to change modes, or just add it to your Steam Library for the time being.)

### Minimal reproduction project

[Issues.zip](https://github.com/godotengine/godot/files/10676873/Issues.zip)

ControllerTest - Working input tester for Steam Deck
ControllerTestNoWork - Using different bindings names, the dpad becomes unresponsive on Steam Deck

No idea why this behavior happens, even after I changed the names of the inputs back in my main project, again I speculate it has to do with the fact that they are rebound at startup

**Comment by Calinou** [comment] 2023-02-07 15:50
Duplicate of https://github.com/godotengine/godot/issues/45628.

**Closed by Calinou** 2023-02-07 15:50 UTC
