### ISSUE TITLE
[Godot4] class compile error

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50937] opened 2021-07-27 11:33 UTC
### Godot version

v4.0.dev.calinou [e6a544c16]

### System information

windows10

### Issue description

I create a `XLifeFunc.gd` and code like this:
```
class_name XLifeFunc

var _end_func : Callable

func _init(start_func:Callable, end_func:Callable):
	_end_func = end_func
	start_func.call()

func _notification(what):
	if what == NOTIFICATION_PREDELETE:
		_end_func.call()
```
then create a scene and attach code like this:
```
extends Node2D

class XLifeFunc2:
	var _end_func : Callable

	func _init(start_func:Callable, end_func:Callable):
		_end_func = end_func
		start_func.call()

	func _notification(what):
		if what == NOTIFICATION_PREDELETE:
			_end_func.call()


class LF extends XLifeFunc2:  #error here
	func _init():
		super(f1,f2)
	
	func f1():
		prints("f1")

	func f2():
		prints("f2")


func _ready():
	var lf = LF.new()
	prints("done")
```

if `class LF extends XLifeFunc2`, it output:
```
f1
done
f2
```
this is my expect, but if  `class LF extends XLifeFunc`, it only output:
```
done
```
the `XLifeFunc` and `XLifeFunc2` code was same but the `XLifeFunc2` was a inner class.

### Steps to reproduce

1. open the reproduction project
2. run and output was:
```
f1
done
f2
```
3. change `class LF extends XLifeFunc2` to `class LF extends XLifeFunc`
4. run and output was:
```
done
```

### Minimal reproduction project

[FuncTest.zip](https://github.com/godotengine/godot/files/6885037/FuncTest.zip)

**Comment by Calinou** [comment] 2021-07-27 12:12
@CsloudX Does this behave as expected in 3.3.2?

**Comment by CsloudX** [comment] 2021-07-27 12:43
@Calinou
I just test 3.3.2, it all right

**Comment by lyuma** [comment] 2022-04-08 08:29
Still causes problems on 4.0.alpha 7bb963efe9 but it's different than in the initial report.

`extends XLifeFunc` now gives the expected output:
```
f1
done
f2
```

however, `extends XLifeFunc2` will cause an infinite loop upon stepping into the constructor! I tried both stepping in manually and letting it run, and it always hangs.

**Comment by Chaosus** [comment] 2022-05-21 06:33
@lyuma I think it is fixed in https://github.com/godotengine/godot/pull/61025, check again

**Comment by vnen** [comment] 2022-05-24 13:58
I tested with the MRP and it seems to work as intended.

**Closed by vnen** 2022-05-24 13:58 UTC
Labels: bug, topic:gdscript, regression
