### ISSUE TITLE
No option for importing 3D textures as pixel art.

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#65147] opened 2022-08-31 13:58 UTC
### Godot version

4.0.alpha15

### System information

MacOS 12

### Issue description

Both Sprite3D and 3D Materials have no options to set the texture filter to "nearest" (pixel art).
This is fine in Godot 3, as the pixelation was set in import settings.

### Steps to reproduce

1: Create a Sprite3D, add a texture
2: Try to find pixelation property
3: It doesn't exist.

**Comment by Calinou** [comment] 2022-08-31 14:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/5228.

**Closed by Calinou** 2022-08-31 14:12 UTC

**Comment by Zireael07** [comment] 2022-08-31 15:51
Whoa, yet another change likely to bite lots of people... docs page telling how to upgrade from 3.x when?

**Comment by Calinou** [comment] 2022-08-31 17:56
> Whoa, yet another change likely to bite lots of people... docs page telling how to upgrade from 3.x when?

This change was made a long time ago, but there will be a migration guide in due time. Please stop bumping issues about this – it won't make the migration guide be written faster :slightly_smiling_face:
