### ISSUE TITLE
New TileMap editor: The physical settings for all tiles are not saved

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#63150] opened 2022-07-18 14:01 UTC
### Godot version

godot4 a12

### System information

win10 vulkan desktop

### Issue description

![tp](https://user-images.githubusercontent.com/14953625/179527999-b84340ea-1720-4a88-adac-151b8ca2eb07.gif)

The physics collision setting is lost.

### Steps to reproduce

add tilemap,set tileset,add physics layer,then set the physics options in the tileset, then save and close again for loading.

**Comment by Zwizzah** [comment] 2022-07-18 18:02
Happened to me once (alpha 12), so I switched to alpha 8. Now it's happening in that version too, when creating a new project.

**Comment by groud** [comment] 2022-07-19 07:56
Likely a duplicate of https://github.com/godotengine/godot/issues/58848. Is your TileSet a subresource and not saved independently ?

**Comment by CodeLazier** [comment] 2022-07-19 09:10
is subresource,but tileset save as a  disk resource (*.res) and the problem disappeared

**Comment by groud** [comment] 2022-07-19 09:18
Ok, closing as a duplicate of https://github.com/godotengine/godot/issues/58848.
If you have a consistent way to reproduce the issue, please provide your feedback there.

**Closed by groud** 2022-07-19 09:18 UTC
Labels: bug, topic:editor, topic:2d
