### ISSUE TITLE
Editor's root viewport serves stale images after the first access for ViewportTexture

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#45898] opened 2021-02-11 16:38 UTC
**Godot version:**
4.0 #4c528e7

**OS/device including version:**
Windows 10

**Issue description:**
Attempting to capture an editor screenshot with an editor plugin (GDScript) doesn't produce the desired result. The first time you try to get the image from the root `SubViewport`'s `ViewportTexture`, it is returned as expected. However, all consecutive attempts return the same exact image, even though the code even waits for two frames (as is tradition) before grabbing the picture:

```gdscript
	var editor_tree = get_editor_interface().get_base_control().get_tree()
	await editor_tree.process_frame
	await editor_tree.process_frame
	
	var base_control = get_editor_interface().get_base_control()
	var main_viewport = (base_control.get_tree().get_root() as Viewport)
	var viewport_image = main_viewport.get_texture().get_data()
	
	var datetime = OS.get_unix_time()
	viewport_image.save_png("res://.output/godot-editor-" + str(datetime) + ".png")
```

Same does not happen with a user project though, and the image is captured correctly.

```gdscript
	var image = $SubViewportContainer/SubViewport.get_texture().get_data()
	var datetime = OS.get_unix_time()
	image.save_png("res://.output/output-" + str(datetime) + ".png")
```

**Steps to reproduce:**
See the code above and demo projects.

**Minimal reproduction project:**
Editor plugin (press F11 to capture):
[plugin-editor-screenshotter-4.0.zip](https://github.com/godotengine/godot/files/5966876/plugin-editor-screenshotter-4.0.zip)

User project (press the on screen button to capture):
[bug-viewport-screenshot.zip](https://github.com/godotengine/godot/files/5966890/bug-viewport-screenshot.zip)

**Comment by Calinou** [comment] 2021-02-11 16:56
Duplicate of https://github.com/godotengine/godot/issues/44811

**Closed by Calinou** 2021-02-11 16:56 UTC
Labels: bug, regression, topic:editor
