### ISSUE TITLE
_input(event) don't work with SubViewport Node

### ISSUE THREAD

**Issue by thoced** [godotengine/godot#60899] opened 2022-05-09 10:31 UTC
### Godot version

4.0 Alpha 07 official

### System information

Windows 10, Vulkan Clustered, NVIDIA

### Issue description

Hello,
The **_input(event)** method does not work with the Node **SubViewport**

The method is never called, no event is raised.

Dsable input option in editor is not engaged

the problem seems to have been fixed for version 3.5 in January 2022 (https://github.com/godotengine/godot/issues/9950)

### Steps to reproduce

- Create a empty project
- Add a SubViewport Node in the tree
- Attach a new Scricpt (GDSCRIPT)
- To implement _input(Event) method

**Comment by CsloudX** [comment] 2022-08-22 12:56
I meet this in `_unhandle_input`, it's only handle mouse wheel event. left button, motion events etc can't handle.

**Comment by Sauermann** [comment] 2022-09-29 20:41
As far as I can tell, this works as intended: SubViewports do not receive InputEvents by default. ([See here](https://github.com/godotengine/godot/issues/9950#issuecomment-318841555))

You can
A) Manually write code to forward the events in a way that fits your requirements
B) Place the SubViewport within a SubViewportContainer (which does A in a standardized way automatically)

**Comment by akien-mga** [comment] 2023-02-26 15:47
Closing based on above comment.

**Closed by akien-mga** 2023-02-26 15:47 UTC
Labels: bug, topic:input, regression
