### ISSUE TITLE
No filter option for tileset textures

### ISSUE THREAD

**Issue by abueide** [godotengine/godot#39891] opened 2020-06-27 17:31 UTC
**Godot version:**

4.0, b55d859c5f092d145cd0d2c8df9ac5d42c500626

**OS/device including version:**

Windows, Vulkan

**Issue description:**

When I import my texture there is no filter option to disable like there is in the 3.2 branch. Instead it was moved to the CanvasItem node. So when I import the texture directly into the game and switch the mode it works fine. However when I use the texture as a tileset in a tilemap, and I set the filter option on the tilemap node (I also did it on all of its parent's nodes), it doesn't work and everything in my tileset is blurry. I feel like the filter option belonged better inside of the import options, I'm not sure why it was changed though.

**Steps to reproduce:**
Create new tileset and tilemap. In the tileset import some pixel art. Your tiles will be blurry no matter which filter option you select on any node.

**Minimal reproduction project:**

[repro.zip](https://github.com/godotengine/godot/files/4840990/repro.zip)

**Comment by Calinou** [comment] 2020-06-27 18:50
Duplicate of #36328.

**Closed by Calinou** 2020-06-27 18:50 UTC
