### ISSUE TITLE
Inspecting variables via hovering always returns null

### ISSUE THREAD

**Issue by Ev1lbl0w** [godotengine/godot#52701] opened 2021-09-15 12:53 UTC
### Godot version

4.0.dev latest (32f8f74)

### System information

Arch Linux

### Issue description

When debugging, hovering over variables always prints `null`, despite having a value in the stacktrace:
![image](https://user-images.githubusercontent.com/6501975/133435745-b321a6ea-0e5a-439f-a211-7f4deaa74f3c.png)
Furthermore, this hover evaluates every text token, which is not useful:
![image](https://user-images.githubusercontent.com/6501975/133436001-624ed7e2-b0ac-44a8-98f0-b663cbc5e8c6.png) ![image](https://user-images.githubusercontent.com/6501975/133436025-daa317ff-2202-4b1a-be2e-8d221ccb5f71.png) ![image](https://user-images.githubusercontent.com/6501975/133436072-8b53db15-2a86-44cc-a38d-f9bdd3aed7e0.png)

Neither of these behaviors happen on `3.3.3`; there it prints variable values correctly, and doesn't evaluate needless tokens.

### Steps to reproduce

- Have a script like:
```gdscript
extends Node2D

var vec = Vector3(1,2,3)
const aaa = 3

# Called when the node enters the scene tree for the first time.
func _ready():
	var internal = 4
	var array = [1, 2, 3]
	var color = Color(0.2, 0.1, 0.021)
	var b = 3 + 2
	print("Done")
```
- Set a breakpoint on `var b = 3 + 2` and run the project
- On breakpoint, hover on the text for variables; it will always print `null` 

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/7170161/MRP.zip)
- `for3dotX.tscn` for Godot `3.x`
- `for4dot0.tscn` for Godot `4.0`

**Comment by Jummit** [comment] 2021-09-15 15:20
Code responsible: https://github.com/godotengine/godot/blob/ed11d03b56d14f2868eaae041a42d1c4d4d425c1/core/debugger/local_debugger.cpp#L326-L328

**Comment by Jummit** [comment] 2021-09-15 15:28
Code responsible: https://github.com/godotengine/godot/blob/58c30b2626f4fcd00dece84de7778acfd2e9c6f8/editor/plugins/script_editor_plugin.cpp#L400-L407

**Comment by totalgee** [comment] 2021-10-17 22:07
I've seen a similar behaviour in 3.3.3 and 3.3.4, where hovering over a variable shows `Null` in the debugger when it obviously isn't, because the code works properly (and a conditional check for null on the variable will return false!). The debugger inspector that shows all in-scope variable/member values also shows the variable as `[null]`. For me, this happens when calling `get_node()` on certain nodes -- for example, I had a scene where this happened with an `AnimatedSprite` child, but other children would show the proper ObjectID. Not sure if this is related to the above, or a separate issue...

**Comment by KoBeWi** [comment] 2021-12-24 10:40
Duplicate of #49939

**Closed by KoBeWi** 2021-12-24 10:40 UTC
Labels: bug, topic:gdscript, topic:editor, regression
