### ISSUE TITLE
bbcode to support different sizes

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8186] opened 2017-03-28 11:52 UTC
It would be real handy to have different font sizes supported in bbcode

https://en.wikipedia.org/wiki/BBCode
suggests the following syntax:

[style size="15px"]Large Text[/style]

**Comment by Calinou** [comment] 2017-03-28 13:44
Duplicate of https://github.com/godotengine/godot/issues/5557.

**Comment by akien-mga** [comment] 2017-03-28 14:06
Indeed.

**Closed by akien-mga** 2017-03-28 14:06 UTC
Labels: discussion, feature proposal, topic:core
