### ISSUE TITLE
[4.0beta11] C#/.net Errors in log have large prepended internal irrelevant information

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#71334] opened 2023-01-13 15:50 UTC
### Godot version

4.0.beta11.mono

### System information

Windows 10

### Issue description

Error logs coming from the .net backend in the debugger window have a large internal call info information string prepended, that does not add any value, but instead obscures the actual error messages:
![grafik](https://user-images.githubusercontent.com/8841352/212359253-a0f620c7-bd45-4753-a604-08fa37061cbf.png)

### Steps to reproduce

Have c# errors, open debugger error panel

### Minimal reproduction project

It's impossible for me currently to recreate the errors i got when upgrading my (huge) project (i'm not even sure where some are coming from), and deleting assets to reduce filesize just makes the editor crash or error out at various random stages, effectively not getting to the point anymore where the errors can even be printed. But the screenshot should be enough to show the obscuring string.

**Comment by raulsntos** [comment] 2023-01-13 15:54
Duplicate of https://github.com/godotengine/godot/issues/67451

**Closed by raulsntos** 2023-01-13 15:54 UTC
