### ISSUE TITLE
Inconsistent Icon Scaling in FileSystem Dock

### ISSUE THREAD

**Issue by im4potato** [godotengine/godot#45973] opened 2021-02-13 20:11 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Arch Linux

**Issue description:**
Scaling the editor causes icons in the FileSystem dock to scale incorrectly. Below is an example of what 100% vs 200% looks like. As you can see, there is inconsistent behavior, at 100% all icons are the same size, but at 200% some icons are half the size of others.
![Scaling](https://user-images.githubusercontent.com/62815710/107860387-4c0c6900-6dfc-11eb-8c24-d32c1fd95e4c.png)

**Steps to reproduce:**
Set `Interface > Editor > Display Scale` to anything other than 100%.

**Comment by Calinou** [comment] 2021-02-13 22:01
Duplicate of https://github.com/godotengine/godot/issues/43074 (fixed in 3.2.4beta1 and later).

**Closed by Calinou** 2021-02-13 22:01 UTC
