### ISSUE TITLE
godot 4.1 On the M1 MAX, the animation setting AnimationTree stucks 100% when setting the state machine. Please help solve this bug

### ISSUE THREAD

**Issue by zeku2022** [godotengine/godot#79147] opened 2023-07-07 09:41 UTC
### Godot version

4.1

### System information

macOS 13.3.1

### Issue description

godot 4.1 On the M1 MAX, the animation setting AnimationTree stucks 100% when setting the state machine. Please help solve this bug

### Steps to reproduce

https://www.youtube.com/watch?v=Luf2Kr5s3BM&ab_channel=Chris%27Tutorials
I followed this tutorial to set up the animation state machine, and clicking Active will definitely freeze. My animation status settings are fine.

### Minimal reproduction project

https://github.com/zeku2022/godot_playground

**Comment by akien-mga** [comment] 2023-07-07 09:49
Probably a duplicate of #79012, I'll test.

**Closed** 2023-07-07 09:58 UTC
Labels: bug, crash, topic:animation
