### ISSUE TITLE
Tilemap Editor - Workflow Enhancements

### ISSUE THREAD

**Issue by pixeltao** [godotengine/godot#24517] opened 2018-12-21 03:54 UTC
**Godot version:**
v3.1.alpha.official

I've been dabbling with the new tileset and tilemap editor in Godot 3.1 Alpha and I've thought of an improvement with the tilemap editor that would make working with big tilesets easier. **Disclaimer**: I'm still new with Godot, so I might have missed some feature or functionality.

Right now, when working with big tilesets (hundreds of tiles) like the one we had on Mercenary Kings, the fastest way I've found to create all tiles is to use an atlas rather than defining each tile individually. However, when you use an atlas (or tiles created individually) with your tilemap, tiles are auto-sorted and displayed like this in the tileset window (bottom-right):

![image](https://user-images.githubusercontent.com/45957049/50323750-1df39e80-04a9-11e9-95b6-a36f37c85057.png)

This is pretty much unusable with a huge tileset because tiles are not placed like they were in the tileset texture. This can make finding specific tiles really cumbersome.

So, I've thought of **2 features** that would make the process of picking tiles and drawing with them a LOT easier:

**1st**, display the tileset image (or portion created with the atlas) directly in the tilemap editor so that the user can pick them from there, like this:

![image](https://user-images.githubusercontent.com/45957049/50323761-382d7c80-04a9-11e9-99a3-ba31751c9229.png)

**2nd**, allow the user to pick a group of tiles (like a stamp tool) and draw with them.

I'm aware that these functionalities could potentially be a lot of work to implement, but they'd make the process of making tilemaps a lot smoother (in addition to the existing and already great auto tile feature).

**Comment by girng** [comment] 2018-12-21 06:32
yeah, agreed x100. similar to how tiled does it. would be  a huge improvement to the tileset editor. with that said, there is the tiled importer [here](https://github.com/vnen/godot-tiled-importer) (i'm sure you know, but just in case)

**Comment by pixeltao** [comment] 2018-12-21 17:37
@girng Yup, we're currently using Tiled with this importer right now for our new project. Even though it's working great, it'd still be cleaner and more convenient to be able to do everything directly in Godot.

**Comment by Seel** [comment] 2019-02-09 21:18
Both of these features are things I remember from RPG Maker 2000 and am missing here.

**Comment by letsgamedev** [comment] 2019-02-17 08:21
I highly appreciate displaying the real tilemap. Maybe it would be a good idea to make the whole atlas some kind of default atlas where I can specify all the collisions and so on and then use the auto-tile feature to pick certain tile groups for creating those extra "tile buttons" in the editor. So the "Disable Autotile" Button can go cause we have access to the single tiles through the default mega atlas.

Also what really annoys me is, if you made an Atlas you cannot really editing it with the Editor. And I don't see a delete button for a Tile I want to remove cause I made a mistake at the configuration.

The Editor is on the right way but at the moment a little pain to use :)

**Comment by Jantho1990** [comment] 2019-04-11 01:31
Chiming in to say this would be a really useful feature!

**Comment by Imerion** [comment] 2019-04-19 00:11
Agreed, this would be very useful!

**Comment by sachdevs** [comment] 2019-06-01 21:10
👍 This feature is enough of a sore spot that I don't use tilemaps in Godot. Instead I find myself using Tiled and importing afterwards.

Without this feature, I almost feel that Tilemaps are near unusable for large tilesets.

**Comment by insomnius** [comment] 2019-06-02 14:54
Agreed, that would be very useful!!

**Comment by Jummit** [comment] 2019-06-02 14:57
Agreed, that would be very useful!!!

**Comment by giulianob** [comment] 2019-07-26 15:15
+1 I'm going to switch to Tiled for now because its nearly impossible to work in the current tilemap editor when the tiles are all over the place. I don't want to add another step to my workflow but I don't see a workaround right now.

**Comment by vortexofdoom** [comment] 2019-07-29 03:41
Currently, you can select a region to have as a single tile, that has its own collision and everything. It would be useful if there was an editor to allow the same functionality with non-adjacent tiles. You could make a 2x2 (or any number, really) grid of smaller tiles with various rotations/flips and have that be one tile to be used.

This would allow for the method a lot of older games used where the world was built out of 16x16 pixel tiles, but those tiles used a smaller number of 8x8pixel tiles. With modern computers, you really don't have to worry about the memory aspect that was the reason they did this, but it's such a distinctive and interesting part of the style.

My current workaround is making a tilemap that is purely these 2x2 tiles and then copy-pasting into the "real map" and forcing myself to keep to the 16x16 grid. It works, but it has its drawbacks. Just putting out a related but separate use case for stamps and the like.

**Comment by KoBeWi** [comment] 2021-03-14 15:54
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1769
The issue is resolved in the new tile editor.

**Closed by KoBeWi** 2021-03-14 15:54 UTC
Labels: enhancement, topic:editor, usability
