### ISSUE TITLE
Certain classes have unmutable min sizes

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4844] opened 2016-05-27 15:26 UTC
**Operating system or device - Godot version:**
Using : Godot_v2.0.3_stable_x11.64 on linuxmint 17.3

**Issue description** (what happened, and what was expected):
**LineEdit** control must be resizeable to (0,y) size as **Label** control or alternatively (0,0) size as **TextEdit** control.

**Steps to reproduce:**
Create a new project and open a new scene. Add a **LineEdit** node. Try to resize it below (46,23).
NOTE : Didn't have any clue about weather it is a font related issue or not. May try additional tests if directions are given.

**Link to minimal example project** (optional but very welcome):

**Comment by hubbyist** [comment] 2016-05-31 08:14
I found some more unmutable min size situations. Do I add them to this issues or open separate issues since this issue is already labeled.

**Comment by trollworkout** [comment] 2016-05-31 11:35
@hubbyist  Maybe you can edit the post to "certain classes have unmutable min sizes" and list them in the body

**Comment by hubbyist** [comment] 2016-05-31 18:23
unmuteable min size values of some control nodes

	LineEdit    : (46,23)
	Label       : (0,13)
	Button      : (12,19)

**Comment by hubbyist** [comment] 2016-06-01 07:41
I realized that when I set seperation value of HboxContainer and VBoxContainer to 0 in project theme MarginContainer unmuteable min size gets (0,0). So it seem that this unmutable mins sizes are related to theme. So separating default theme of projects and default theme of editor may solve most of the unmutable min size problems.

**Comment by reduz** [comment] 2016-06-14 01:34
This is by design, such min-sizes are product of theme items such as stylebox, fonts and constants. If you need something like this, just create a custom theme or custom styles, and it will be more predictable.  

closing, as this is not a bug

**Closed by reduz** 2016-06-14 01:34 UTC
Labels: bug, junior job, topic:core
