### ISSUE TITLE
App closes when closing preview on Android

### ISSUE THREAD

**Issue by nonolai** [godotengine/godot#62160] opened 2022-06-17 21:47 UTC
### Godot version

4.0 Alpha 10

### System information

Samsung S22 Ultra

### Issue description

When using the Godot Editor on an Android phone, closing is the previewed app closes the whole editor

Expected: closes app preview, going back to editor
Actual: whole editor app closes. Need to reopen project 

Note: I'm not confident if this is an intended usecase, but saw the .apk of the editor available in the 4.0 alpha 10 downloads and wanted to try it out! Feel free to close if knowingly unsupported 

### Steps to reproduce

1. Create new project
2. Save scene, add it as the starting scene
3. Start app via "play" button
4. Use "back" gesture (edge swipe).

**Comment by akien-mga** [comment] 2022-06-18 08:47
Same issue with the 3.5 RC 4 version of the Android editor. I agree that this should be improved as suggested.

**Comment by Calinou** [comment] 2022-06-18 18:12
Duplicate of https://github.com/godotengine/godot/issues/61611.

**Closed** 2022-06-18 18:14 UTC
Labels: bug, archived, platform:android, topic:editor, usability
