### ISSUE TITLE
Why engine removes objects from the scene?

### ISSUE THREAD

**Issue by SJerin** [godotengine/godot#6444] opened 2016-09-10 11:11 UTC
Faced with the strange behavior of the engine: When working with a project, for example, when you change the size of any of the objects of the game, for Godot can change the position of other objects, and in some cases completely remove them from the scene. This problem was seen in Version 2.1. It interferes with work.

**Comment by vnen** [comment] 2016-09-10 14:28
Children nodes inherit transform from their parents, including scale. If you make a node big, its children will be scaled too and might be now rendered off-screen because of the size or offset.

**Comment by SJerin** [comment] 2016-09-10 14:55
This has happened when you change an object that has no child nodes. Objects not only disappeared from the scene, and the nodes tree.

**Comment by vnen** [comment] 2016-09-10 15:14
I've never seen this. Please provide a small sample project which reproduces this bug.

**Comment by SJerin** [comment] 2016-09-10 17:08
![screen](https://cloud.githubusercontent.com/assets/18466871/18412206/5f5d6952-7791-11e6-8a8d-9a2a62272bb5.png)
I'm trying to re-create the project and I again fail when you try to save the scene. And so it happened for various reasons: an attempt to save the scene, run it or just when moving / changing objects.

**Comment by Sslaxx** [comment] 2016-09-11 10:37
I haven't seen objects getting outright removed from the scene, but I _have_ seen objects sometimes moving +1,+1 in their position when selected.

**Comment by akien-mga** [comment] 2017-02-16 15:17
Can this issue still be reproduced? It seems hard to debug based on the current information.

**Comment by Noshyaar** [comment] 2018-04-06 10:32
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Sslaxx** [comment] 2018-04-06 10:36
Not seen this in 3.0.2, not sure about 2.1.4.

**Comment by Noshyaar** [comment] 2018-04-06 11:50
There's high chance that it's no longer relevant in the latest version. I'll close this for now.

**Closed by Noshyaar** 2018-04-06 11:50 UTC
Labels: bug, topic:core
