### ISSUE TITLE
Y-Axis flickers if using non-compatibility renderer

### ISSUE THREAD

**Issue by Repiteo** [godotengine/godot#74826] opened 2023-03-12 16:00 UTC
### Godot version

4.x

### System information

Windows 11, Forward+ & Mobile, RTX 3080, version 528.49

### Issue description

The default viewport of a 3D scene has the Y-axis perfectly aligned, which causes flickering when applying a yaw rotation. This flickering is minimized/removed when zooming a viewport all the way in or out, but is otherwise consistently popping in and out of view. Using compatibility mode will also remove flickering, though a min/max zoomed viewport appears to have less "jitter" on the Y-Axis when rotating

[YouTube demonstration](https://youtu.be/a8rKNTuaQrI) of the renderers and their different behaviors

### Steps to reproduce

1. Open a new instance of a Godot 4.x project
2. Ensure the renderer is set to either Forward+ or Mobile
3. Enter a 3D scene & hold the middle-mouse button to yaw the camera

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-03-13 18:45
Duplicate of https://github.com/godotengine/godot/issues/37016. So closing to keep the issue tracked in one place.

**Closed by clayjohn** 2023-03-13 18:45 UTC
