### ISSUE TITLE
Class names stop working after a while

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#76380] opened 2023-04-23 19:10 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Compatability

### Issue description

I'm getting a problem where class names that I define in GDScript just stop working after a while.  I'm not sure what is causing this.  I am just noticing that when I'm working on a project where I've defined a lot of classes using `class_name MyClassName` the name will just stop being recognized after a while.  Sometimes if I restart the editor two times it will become available again.  

Sometimes a class name that I had been using for a long time just stops working and I have to append a '2' to the class name to be able to use the class again.  This is not due to name collisions - these are the only classes in my project with this name and they're complicated enough that I doubt they are part of the core GDScript api.

I suspect the Godot editor is caching something that is persisting between sessions, and whatever that is is interfering with the ability of the script to compile 

### Steps to reproduce

I'm not sure what causes this.  It might be related to duplicating a .gd resource and then editing it, but not always.  I'm just noticing that after working on a project for a while, some class names just stop being recognized.

### Minimal reproduction project

N/A

**Comment by trollusk** [comment] 2023-04-30 20:22
I've had this problem as well. Sometimes class_name just doesn't work (and the name stays grey), especially if you change the class name in an existing script. Repeatedly editing and saving seems to eventually wake Godot up and get it to register the class.

**Comment by vfig** [comment] 2023-06-02 16:18
one specific set of steps (likely not the only one) that is capable of triggering this problem:

1. make a script Foo.gd with `class_name Foo`
2. in the file system panel, duplicate Foo.gd, call it Bar.gd
3. change the line in Bar.gd to be `class_name Bar`.

at this point one would expect both class names to be working. but the Foo class name will not be recognised properly. this can break previously working scenes; for example, a script that does `find_children("","Foo")` in a scene with objects with Foo.gd attached will return an empty array while this class name is 'broken'.

opening Foo.gd, editing its class_name declaration, saving, then editing it back and saving again will get it working again.

**Comment by AThousandShips** [comment] 2023-06-02 16:26
This is caused by the fact that you overwrite the class, it'd be hard to detect this change as you would have to go through evert script to find the one that was overwritten

**Comment by vfig** [comment] 2023-06-02 20:12
@AThousandShips no, i did not overwrite the class. ItemGem.gd was intact and unchanged.

in fact, if (before i edited ItemGem.gd to force a fix) i had deleted the new script, i would have had a _completely unchanged working copy_ (as reported by `git status`) that no longer worked correctly: an extremely unhappy situation.

**Comment by AThousandShips** [comment] 2023-06-02 20:14
You did, you added a new class with the same `class_name`, this sets the script associated with that name to the new script

**Comment by vfig** [comment] 2023-06-02 20:23
…while the script that had previously been associated with that class name was still there, unchanged, with its `class_name` declaration intact.

it would be reasonable in this situation for godot to show an error that there is a duplicate class name; and then when i have edited one file or the other to resolve that, for it to update its cache so that both (now different) class names are associated with their respective scripts.

it is not reasonable for it to lose track of the association. it is not reasonable if one copy of the project fails to work while a completely clean checkout of the project in a new folder, with identical code and resource files, would work.

(and it is not particularly reasonable to reply to a bug report with “fixing this would be hard” and “you’re holding it wrong”.)

**Comment by AThousandShips** [comment] 2023-06-02 20:25
Yes, that is a good suggestion, but tracking this isn't simple

> and it is not particularly reasonable to reply to a bug report with “fixing this would be hard” and “you’re holding it wrong”.

Just stop here, I never said any of those things or anything like it, be professional and reasonable please

**Comment by blackears** [comment] 2023-06-02 20:34
I've run into a similar situation to the one @vfig is describing.  I don't know how Godot handles the tracking, but a minimal solution could be to add a button that just has the editor discard everything and rebuild the tracking from scratch - akin to what a 'build clean' would do in a C++ environment.

**Comment by AThousandShips** [comment] 2023-06-02 20:35
That's a really good idea actually, for many reasons

**Comment by vfig** [comment] 2023-06-02 20:40
no, that is a _terrible_ idea. if godot’s cache cannot handle a temporary class name conflict without breaking the project, pushing that problem back onto the user with a “clean build” button or similar is wrong.

a godot user should fully expect that the scripts they write work as written, and not have to guess if a cache they dont know about needs to be wiped for their project to work correctly.

**Comment by AThousandShips** [comment] 2023-06-02 20:43
How do you suggest to solve it? How do you track replaced class names? Can you point to the changes in the code to make to fix this?

**Comment by vfig** [comment] 2023-06-02 21:00
i do not know the code that handles this, so i cant point you to specific lines or anything. i can suggest an approach that would resolve the issue with the replication steps that i encountered (though of course the OP report might be a different caching bug that would not be resolved by it):

i am assuming that the cache is roughly a dictionary mapping class names to one script file.

when a new class_name declaration is processed, check the previous file associated with it in the cache. if the previous file does not exist, or is the same as the file currently being processed, replace the cache entry.

if the previous file exists and is not the same as the one being processed, that is a conflict. update the cache entry with a flag to indicate that it is in conflict, and a list of the files involved in the conflict (not a “long list”, it would be rare to have more than two). push an error to alert the user to the problem. (possibly this should be a compile error entirely preventing these scripts from running, but i dont know enough about the system to say).

when a script involved in a conflict is edited or deleted, check all the scripts in the list to see if the conflict is now resolved. if it is, remove the flag and the list of conflicts, and update the cache entry to be associated with the appropriate script.

**Comment by blackears** [comment] 2023-06-02 21:07
I would be in favor of some sort of 'scrap the whole thing and start from scratch' emergency option.  Godot is operating in a complex environment  and does not have complete control of the source.  Eg, switching between branches with version control could completely alter what the project even contains.  Addons can also have side effects on what the IDE is doing.  

Cleaning the build is essential in a C++ environment simply because there are so many weird things that can get your project out of sync with what a fresh build would produce.

**Comment by trollusk** [comment] 2023-06-02 21:09
@AThousandShips Now you are being combative. Who has said "fix it"? The users in this thread are reporting a serious bug. It is not reasonable for you to demand that bug reporters specify how to fix the bug.

**Comment by AThousandShips** [comment] 2023-06-02 21:19
I am sorry, I was responding to what to me felt like a combative attitude declaring that it's unhelpful to explain that it's hard, and what felt like a dismissive attitude of "just fix it" or "it's unreasonable that it works like this", that's why I responded in an unreasonable way, I felt the attitude dismissed the actual work involved in fixing this and that was unfair of me

**Comment by vfig** [comment] 2023-06-02 21:26
@blackears the c++ situation is not exactly a model to be imitated! however in this instance the bug is happening entirely within godot’s purview, editing files only within its own editor.

**Comment by blackears** [comment] 2023-06-02 21:29
@vfig not is you're using source control.  Files can be changed outside of the editor.

**Comment by vfig** [comment] 2023-06-02 21:32
@blackears no files are changed outside the godot editor in the reproduction steps i described.

**Comment by FeralBytes** [comment] 2023-06-29 21:53
@blackears I can confirm this experience and I am using git, but I have not changed the current tree at all. I have only used git to snapshot the project, yet Godot is forgetting the class_name.

**Comment by donn-xx** [comment] 2023-08-17 08:40
Godot 4.1.1 seems to still have class_name issues. I posted on a similar thread: https://github.com/godotengine/godot/issues/30048#issuecomment-1681862745

Not sure which issue number is the right one to join.

**Comment by daenvil** [comment] 2023-10-11 10:27
I have been using 4.1 for some months and I can confirm that I encountered this issue multiple times, mostly when moving or duplicating files (all within the editor). I circumvented it by renaming classes whenever the error happened. The worse case was recently when I moved my project to a new location and *every* class name broke.

I think this might be related to #78642 , where a "update cache" button is also suggested as a solution.

**Comment by Wad67** [comment] 2023-10-12 06:59
I have also encountered this issue just now, I recently cloned my game repo on new hardware, imported it and godot began complaining about not finding class_name definitions. 

'Solved' by right clicking the offending files, and moving them to the project root directory.

**Comment by lpares12** [comment] 2024-01-06 09:38
Hitting this issue just now. Suddenly all the classes can't be found in any of the scripts. Had found it before and I could just restart Godot, or remove a class_name and add it again. But this time it does not work.

**Comment by donn-xx** [comment] 2024-01-06 10:44
> Hitting this issue just now. Suddenly all the classes can't be found in any of the scripts. Had found it before and I could just restart Godot, or remove a class_name and add it again. But this time it does not work.

I have found 3 "fixes". 

1. Glacial: Open each script. Change class_name by one character. Save. Undo. Save again.
2. Gradual: Delete .godot/global_script_class_cache.cfg
3. Nuclear: Delete .godot/ entirely

**Comment by anvilfolk** [comment] 2024-01-06 15:52
> Hitting this issue just now. Suddenly all the classes can't be found in any of the scripts. Had found it before and I could just restart Godot, or remove a class_name and add it again. But this time it does not work.

@lpares12 one day I hope to have time to look into this a bit more in-depth! Do you happen to remember renaming or duplicating a .gd file? That seems to be at the source of at least a few of these issues!

**Comment by donn-xx** [comment] 2024-01-06 17:35
> @lpares12 one day I hope to have time to look into this a bit more in-depth! Do you happen to remember renaming or duplicating a .gd file? That seems to be at the source of at least a few of these issues!

I would say the glitch does happen when there is a lot of .gd file churn. I would say that duplicating another .gd file (that has a class_name) and then editing it (before you can change the class_name to something else) seems a good way to trigger this. Will have to try isolate it.

**Comment by MayaKerr** [comment] 2024-02-18 07:04
Has this been fixed or a reset cache button been added anywhere/ any plugin?

I accidentally committed to my repo with Godot open and it duplicate ALL of my files in my project. I went through and deleted the duplicates, but now none of my classes are working and I cannot get this fixed with restarts or renaming classes.

Since this issue was opened in 2023, now asking in 2024, has a fix been found or created?

**Comment by donn-xx** [comment] 2024-02-18 07:19
> Has this been fixed or a reset cache button been added anywhere/ any plugin?
> 
> I accidentally committed to my repo with Godot open and it duplicate ALL of my files in my project. I went through and deleted the duplicates, but now none of my classes are working and I cannot get this fixed with restarts or renaming classes.
> 
> Since this issue was opened in 2023, now asking in 2024, has a fix been found or created?

No fix yet, afaik.

Go into .godot/ and open `global_script_class_cache.cfg`

Dig around in there and alter any weird looking stuff. Also try restarting your project multiple times. It tends to flush-out as you fix error messages.

Another trick I have used is to open the scripts and go to the class_name FOO and hold Ctrl while you hover over FOO. Sometimes this forces Godot to recognize FOO as a class. I also retype FOO and Ctrl+S : all this is kind of like editing the config file I mentioned above.

Good luck. Take it one class at a time with restarts in between.

**Comment by MayaKerr** [comment] 2024-02-18 07:47
Thank you!! This is incredibly helpful and I was able to get my schtuff
working again! Bookmarking incase this ever happens again.

**Comment by Roboticy3** [comment] 2024-03-17 18:12
I've been working on a rather large project for a long time now, and this always comes up when trying to send the data to other devices over github! .godot is automatically added to the .gitignore in projects created with git version control. It *seems* like removing the class cache from the gitignore would solve this device issue from looking at the thread. Is there a reason it's added to the gitignore by default?

I for one have two devices I use to work on the game. One of them has a corrupted class cache and the other doesn't. After trying to remove the class cache from the gitignore and creating a test branch where the class cache is in the repository from the device with the "clean" cache, it looks like it works!

Since rebuilding the class cache from scratch is finicky, is there any reason the class cache needs to be automatically added to the gitignore?

**Comment by donn-xx** [comment] 2024-04-02 11:59
Without `global_script_class_cache.cfg` (as @Roboticy3 points out) Godot breaks. This is still the case on the latest main (compiled today).

If that file is missing, one gets compile errors on every mention of a class_name like `classFoo.do_something()`

Could Godot not somehow **pre-process** gdscript files to re-build that cache file *before* starting their execution?

At the moment I am having to do this weird thing with const and preload to _superimpose_ a name onto each class so that it works:

Here, classfoo.gd is *already* using its own class_name:
```python
class_name classFoo # <-- this one
extends Resource
etc.
```
But I have to alias it so:
```python
const FakeClassFoo := preload("classfoo.gd") # The const name is the aliased class_name
..
var foo := FakeClassFoo.new() # which is weird
etc.
```

I have to do this so that, as that cache file comes and goes, the code does not break.

**Comment by donn-xx** [comment] 2024-04-03 07:59
Another issue is Plugin dev.

My gdscript relies on class_names in all sorts of ways. When I distribute the plugin, that global cache file does not go along with it, therefore there will likely be all kinds of broken behaviour for the end-user as names fail to resolve etc.

**Comment by romgerman** [comment] 2024-05-19 12:31
Just now we encountered this. After importing a project from git Godot cannot find any classes defined with class_name. But if you open your custom classes in the script editor (or vscode) then godot recognizes them. Also some addons (like DialogueManager) stops working after importing the project.

**Comment by donn-xx** [comment] 2024-05-22 04:42
I have written two plugins (gdscript) that rely on class_name. Despite the `const` trick above, there are cases where the class_name is important and when the plugins are installed, one gets the dreaded, "SCRIPT ERROR" with complaints about not knowing class names.

If the `global_script_class_cache.cfg` file of the *plugin* could somehow be merged with the one in the project its being installed into, that might be a hacky fix for now.

**Comment by donn-xx** [comment] 2024-05-22 06:02
I just cloned a Godot Project* and tried to run it. This is what you get. I have closed and opened and closed and opened, but it refuses to just parse the class names!

*(https://github.com/YuriSizov/boscaceoil-blue/)

```
SCRIPT ERROR: Parse Error: Could not find type "SettingsManager" in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:34)
SCRIPT ERROR: Parse Error: Could not find type "VoiceManager" in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:35)
SCRIPT ERROR: Parse Error: Could not find type "MusicPlayer" in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:36)
SCRIPT ERROR: Parse Error: Could not find type "IOManager" in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:37)
SCRIPT ERROR: Parse Error: Could not find type "Song" in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:40)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:47)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:48)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:49)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:50)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:51)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:52)
SCRIPT ERROR: Parse Error: Identifier "ColorPalette" not declared in the current scope.
          at: GDScript::reload (res://globals/Controller.gd:53)
..
...
It goes on and on
```

How is this a thing?

**Comment by romgerman** [comment] 2024-05-23 09:00
Turns out if you commit `global_script_class_cache.cfg` (I'm using git) then the project will not have any class_name errors after cloning (It was the problem for me because my gamedev partner couldn't run the game after getting sources).

**Closed** 2024-06-28 12:51 UTC
Labels: bug, topic:gdscript, needs testing, high priority
