### ISSUE TITLE
Play-shortcut not working when the focus in the script editor

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#66443] opened 2022-09-26 13:38 UTC
### Godot version

4.0 beta1 mono

### System information

macOS Monterey 12.5

### Issue description

When the focus is in the script editor (caret is blinking in the code area) the Play-shortcut (Command + B on macOS) is not working.

### Steps to reproduce

1. Open Script editor.
2. Open any existing script or create a new one.
3. Press Command + B

Expected: The game is compiled and started.
Actual: Nothing happens.

**Comment by EricEzaM** [comment] 2022-09-26 13:58
It appears that ScriptTextEditor is swallowing the input because of `Go To Next Bookmark` shortcut.
![image](https://user-images.githubusercontent.com/41730826/192295483-6c8dacbe-3709-4008-a46c-00fd59cf5d84.png)

Try removing/changing that shortcut and see what happens (or change run project/play to something else)

We may need to reconsider the default shortcuts here.

**Comment by codespren** [comment] 2022-09-26 14:08
Changing "Go to Next Bookmark" to something else than Command+B fixes the issue.

**Comment by EricEzaM** [comment] 2022-09-27 12:53
Duplicate of https://github.com/godotengine/godot/issues/61782

**Closed by EricEzaM** 2022-09-27 12:53 UTC
Labels: bug, topic:editor, topic:input
