### ISSUE TITLE
Slow response to touch input

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#3442] opened 2016-01-25 00:17 UTC
There is a problem with a response time to touch input. 
Here's a simple code:
````
func _input(event):
    if event.type == InputEvent.SCREEN_DRAG:
         set_pos(event.pos)
````

This script is attached to a sprite node. All it should do is simply place the node exactly where the touch event is happening, however there's a delay- when quickly moving finger across the screen it almost feel like there's this code happening:
````
set_pos(get_pos().linear_interpolate(event.pos, n*delta))
````
On tablet it is possible to get ~3-4cm distance between the positions of a finger and a sprite. 

I'll admit that the devices I'm using for testing are quite old: Samsung Galaxy Tab 2 10.1 and LG Nexus 4, however I tested other demo performance made with Unity on same devices and I couldn't spot similar issue, that's why I think this is the engines issue.

**Comment by reduz** [comment] 2016-01-25 00:40
this is device specific and not a bug, the problem is not that response to
touch is slow, but that graphcs generally take a few seconds to reach the
scren.
try grabbing app icons and moving them around and you will see the same
behavior

**Comment by UgisBrekis** [comment] 2016-01-25 01:22
Ok, you're right. I'm just curious how that responsiveness is achieved- maybe depending on speed and direction there's added an extra vector...

**Comment by reduz** [comment] 2016-01-31 23:09
closing, as it's not a bug

**Closed by reduz** 2016-01-31 23:09 UTC
Labels: platform:android

**Comment by moechofe** [comment] 2019-03-20 17:08
I just encounter the same behavior and found a talk from apple that explain why this happen and how they upgrade their API to deal with it by doing prediction: https://developer.apple.com/videos/play/wwdc2015/233/
