### ISSUE TITLE
Setting mouse cursor to 72x72 image causes rendering errors in 3d

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#28272] opened 2019-04-21 15:59 UTC
**Godot version:** 3.1

**OS/device including version:** Ubuntu 18.10

Nvidia GP108M [GeForce MX150]
Nvidia drivers

**Issue description:**

Changing mouse cursor to a 72x72 png (pulled from Kenney's Crosshair pack: https://www.kenney.nl/assets/crosshair-pack) results in anything in transparent part failing to render in 3d.

**Steps to reproduce:**
Make a 3d scene with some moving objects, place a camera in the scene and change you mouse cursor to a 72x72 png, hover it near moving objects and you'll see the transparent square around the mouse cursor does not update.

**Minimal reproduction project:**

[CursorTest.zip](https://github.com/godotengine/godot/files/3101373/CursorTest.zip)
![ezgif-5-0a106d8388b6](https://user-images.githubusercontent.com/7292421/56472487-e8e26300-642c-11e9-8bff-af85ecfc3651.gif)

**Comment by Calinou** [comment] 2019-04-21 16:15
Does it work with power-of-two sizes such as 64×64? Also, does this bug occur when using the GLES2 renderer?

**Comment by Miziziziz** [comment] 2019-04-21 16:40
Bug doesn't occur with 64x64.
Just tested on GLES2 and the bug occurs there as well for 72x72 image

**Comment by akien-mga** [comment] 2019-04-22 08:43
CC @guilhermefelipecgs

**Comment by guilhermefelipecgs** [comment] 2019-04-22 12:48
I was not able to reproduce this. @Miziziziz What is your nvidia driver version?

My Specs:
Archlinux - 5.0.8-arch1-1-ARCH
GeForce GTX 970 - Driver 418.56

**Comment by Miziziziz** [comment] 2019-04-23 00:04
here's my output of sudo lshw -c display

*-display                 
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:138 memory:a2000000-a2ffffff memory:b0000000-bfffffff ioport:4000(size=64) memory:c0000-dffff
  *-display
       description: 3D controller
       product: GP108M [GeForce MX150]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=nvidia latency=0
       resources: irq:140 memory:a3000000-a3ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:3000(size=128)

**Comment by Sslaxx** [comment] 2019-04-23 09:37
Do you know which one of those is being used by Godot/your project?

**Comment by guilhermefelipecgs** [comment] 2019-04-23 12:16
@Miziziziz Please, run `nvidia-settings --version` to get the driver version of your nvidia.

**Comment by Miziziziz** [comment] 2019-04-23 21:52
@guilhermefelipecgs  version 390.77 
@Sslaxx running godot in command line has this line pop up: 
OpenGL ES 3.0 Renderer: GeForce MX150/PCIe/SSE2
so I assume it's the nvidia

**Comment by guilhermefelipecgs** [comment] 2019-05-08 02:36
@Calinou You were able to confirm the error. What GPU did you used?

**Comment by Miziziziz** [comment] 2019-05-08 17:19
@Calinou I don't have anything like that set up

**Comment by guilhermefelipecgs** [comment] 2019-05-09 16:33
As I explain in this comment https://github.com/godotengine/godot/issues/28743#issuecomment-490970222, cursor flickering is an OS problem, so we don't have much to do. System's cursor normally have a size of 32x32, any image bigger than that may cause flickering in some machines (even high end machines, the 256x256 limit I put for cursors is because images larger than that caused flicker on my GTX 970 on Linux).

I'm planning to improve the class ref with more details about that and unfortunately that's all I can do.

**Comment by guilhermefelipecgs** [comment] 2019-05-09 16:42
The only way to have a flicker-free cursor is to implement by yourself within godot, but the downside is that you will have higher latency response.

**Comment by Calinou** [comment] 2019-12-24 10:41
I'll close this in favor of #28743 as it has more information about the issue at hand.

**Closed by Calinou** 2019-12-24 10:41 UTC
Labels: bug, topic:rendering
