### ISSUE TITLE
Android CameraServer.feeds() returning empty array

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#55290] opened 2021-11-24 16:35 UTC
### Godot version

3.4 stable

### System information

OSX 10.15.7

### Issue description

When exporting to Android or running through the debug on android feature `CameraServer.feeds()` returns an empty array.

The same code is working correctly for OSX

### Steps to reproduce

1. Clone https://github.com/tavurth/godot-camera
2. Setup android export
3. Enable camera permission
4. Run as debug on Android device

### Minimal reproduction project

https://github.com/tavurth/godot-camera

**Comment by Calinou** [comment] 2021-11-24 16:41
Duplicate of https://github.com/godotengine/godot/issues/46531.

**Closed by Calinou** 2021-11-24 16:41 UTC
Labels: bug, platform:android, topic:porting

**Comment by Swaraj-cs** [comment] 2022-07-30 07:43
Any other option to use  for android?

**Comment by Calinou** [comment] 2022-07-30 16:52
> Any other option to use for android?

Not yet: https://github.com/godotengine/godot/issues/46531#issuecomment-1186628092
