### ISSUE TITLE
Add global search/replace to editor

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6217] opened 2016-08-20 12:42 UTC
It would be nice to have ability to search for anything (but, most important, names and maybe strings) inside the whole project or at the very least across text files (should be much easier to implement this). This would be very helpful for big projects and especially when working with third-party project. Having also a global replace feature would make renaming things easy.
### Implementation thoughts
- text-only version
  - filename filtering (e.g. "*.gd")
  - possibility to choose between open and all project files
  - search results can be presented in tree, like this (or even with more hierarchy - including functions):
    - script.gd
      - line xx: [line with search term highlighted]
      - line yy: [line with search term highlighted]
    - another_script.gd
      - ..
  - possibility to choose which occurrences to replace
- full version
  - highlight occurrences everywhere in ui (e.g. Inspector)
  - search area filter (e.g. only nodes or only signals)
  - search result window can be pretty much the same as text-only version, but also display type of search result
  - clicking on search result switches to appropriate item (e.g. clicking on node name would change to its scene and select node)

**Comment by Dillybob92** [comment] 2016-08-20 20:52
Yeah, I always alt tab to notepad ++ but having it inside the editor would be great. Nice idea!

**Comment by draxdeveloper** [comment] 2016-12-19 19:36
upvoted this :)

**Comment by neikeq** [comment] 2016-12-19 20:59
Looks like a duplicate of #2592

**Comment by akien-mga** [comment] 2017-01-02 11:40
Indeed.

**Closed by akien-mga** 2017-01-02 11:40 UTC
Labels: feature proposal, topic:editor, usability
