### ISSUE TITLE
In exports without debug, methods return wrong booleans

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#62500] opened 2022-06-28 22:18 UTC
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 11, Vulkan Clustered, GeForce 1660 (516.40)

### Issue description

With the following code.

custom.gd:
```gdscript
extends Node
class_name Custom

func get_true_value() -> bool:
	return true
```
main.gd:
```gdscript
extends Node

@onready var custom: Custom = $Custom
@onready var label: Label = $Label

func _ready() -> void:
	var value_a := true
	var value_b := custom.get_true_value() # true
	label.text = str("value_a = ", value_a, "\n", "value_b = ", value_b)
```

We get the following result.

Export with debug:
![image](https://user-images.githubusercontent.com/10379487/176308486-3524fade-8414-4f70-a41f-a1cea1693c61.png)

Export without debug:
![image](https://user-images.githubusercontent.com/10379487/176308542-a75ff579-fdf3-4bac-819b-5cdfccb349e9.png)
 

### Steps to reproduce

* export reproduction project with and without debug;
* run both compare behavior.

### Minimal reproduction project

[export-test.zip](https://github.com/godotengine/godot/files/9005714/export-test.zip)

**Comment by akien-mga** [comment] 2022-06-28 22:21
Duplicate of #59239

**Closed by akien-mga** 2022-06-28 22:21 UTC
