### ISSUE TITLE
Text in LineEdit will not auto fulfill the display area after delete some text

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#43438] opened 2020-11-10 13:34 UTC
**Godot version:**
3.x

**OS/device including version:**

**Issue description:**

Text in LineEdit will not auto fill the display area after delete some text

1. the length of text is larger than the display area
<img width="540" alt="Screen Shot 2020-11-10 at 9 18 14 PM" src="https://user-images.githubusercontent.com/1130047/98679147-8d731f80-239a-11eb-889a-3541a6e889d2.png">

2. after delete some text, the length of text is still  larger than the display area, but the text will not shift to right to fill the display area
<img width="540" alt="Screen Shot 2020-11-10 at 9 18 48 PM" src="https://user-images.githubusercontent.com/1130047/98679162-92d06a00-239a-11eb-8352-aa11c2dcd31d.png">

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by EricEzaM** [comment] 2020-11-12 14:09
Took me a sec to understand what this was on about. Essentially the cursor should stay to the right when deleting. Here is an example on youtube search. See how the caret stays on the right hand side when the text is longer than the textbox?

![A9kqbiXFOb](https://user-images.githubusercontent.com/41730826/98950136-580a3580-2544-11eb-9310-1b875f486f2d.gif)

**Comment by Calinou** [comment] 2020-11-12 15:28
Duplicate of https://github.com/godotengine/godot/issues/27420.

**Closed by Calinou** 2020-11-12 15:28 UTC

**Comment by alexzheng** [comment] 2020-11-12 23:06
exactly.
