### ISSUE TITLE
Use additional mouse buttons to go back/forward in inspector history

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#19772] opened 2018-06-25 22:01 UTC
**Godot version:**

All versions

**Issue description:**

Some mice have additional buttons that usually are mapped to go back or forwad in a web browser. Would it be possible to use those buttons to go to `previous edited` / `next edited object in history` in the inspector when navigating through subresources?

**Comment by Zylann** [comment] 2018-06-26 01:15
If that's possible, I'd like this to be an option, since I use those buttons for other purposes.

**Comment by vnen** [comment] 2018-06-27 01:44
The problem is that it's not possible to set mouse buttons as shortcuts, only keys.

**Comment by akien-mga** [comment] 2020-06-02 09:54
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-06-02 09:54 UTC
Labels: feature proposal, topic:editor, usability
