### ISSUE TITLE
Can't compile master due to possibly uninitialized values

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#40342] opened 2020-07-13 12:15 UTC
**Godot version:**
master branch commit 19c420545d4ea4e097f69fd76e5e121819d35873

**OS/device including version:**
Arch Linux - GCC 10.1.0

**Issue description:**
I'm getting the following when I attempt to compile the `master` branch:
```
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h: In member function 'VkRenderPass_T* RenderingDeviceVulkan::_render_pass_create(const Vector<RenderingDevice::AttachmentFormat>&, RenderingDevice::InitialAction, RenderingDevice::FinalAction, RenderingDevice::InitialAction, RenderingDevice::FinalAction, int*)':
./core/cowdata.h:141:3: error: '*((void*)& description +32)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +32)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: '*((void*)& description +24)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +24)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: '*((void*)& description +16)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:2995:27: note: '*((void*)& description +16)' was declared here
 2995 |   VkAttachmentDescription description;
      |                           ^~~~~~~~~~~
[Initial build] Compiling ==> editor/editor_log.cpp
[Initial build] Compiling ==> editor/editor_node.cpp
[Initial build] Compiling ==> editor/editor_path.cpp
editor/editor_node.cpp:6322:2: warning: #warning neeeds to be reimplemented [-Wcpp]
 6322 | #warning neeeds to be reimplemented
      |  ^~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h: In member function 'void RenderingDeviceVulkan::_draw_list_insert_clear_region(RenderingDeviceVulkan::DrawList*, RenderingDeviceVulkan::Framebuffer*, Point2i, Point2i, bool, const Vector<Color>&, bool, float, uint32_t)':
./core/cowdata.h:141:3: error: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[3]' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:5647:21: note: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[3]' was declared here
 5647 |   VkClearAttachment clear_at;
      |                     ^~~~~~~~
In file included from ./core/ustring.h:35,
                 from ./core/string_name.h:36,
                 from ./core/node_path.h:34,
                 from ./core/hashfuncs.h:36,
                 from ./core/oa_hash_map.h:34,
                 from drivers/vulkan/rendering_device_vulkan.h:34,
                 from drivers/vulkan/rendering_device_vulkan.cpp:31:
./core/cowdata.h:141:3: error: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[2]' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  141 |   _get_data()[p_index] = p_elem;
      |   ^~~~~~~~~
drivers/vulkan/rendering_device_vulkan.cpp:5647:21: note: 'clear_at.VkClearAttachment::clearValue.VkClearValue::color.VkClearColorValue::float32[2]' was declared here
 5647 |   VkClearAttachment clear_at;
      |                     ^~~~~~~~
```

**Steps to reproduce:**
Attempt to compile `master` branch with GCC 10.1.0

```
scons platform=x11 CXX=g++ target=release_debug debug_release=yes debug_symbols=full tools=yes bits=64 -j6
```

**Comment by Xrayez** [comment] 2020-07-13 12:36
Have you tried compiling with `werror=no`?

**Comment by Rubonnek** [comment] 2020-07-13 13:07
@Xrayez thanks, I wasn't aware of that. I'll keep that in mind.

Right now I'm good -- I only wanted to compile the engine to test #40315 against the `master` branch, but akien-mga did it before I could.

**Comment by akien-mga** [comment] 2020-07-13 13:34
Duplicate of #38829.

**Closed by akien-mga** 2020-07-13 13:34 UTC
Labels: bug, topic:core
