### ISSUE TITLE
Option to set Position2D gizmos length

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#7400] opened 2016-12-31 15:36 UTC
Position2D has a fixed length gizmos that when working with low-resolution art gets really chaotic. This can be solved sometimes by scaling down the node, but there are times where that is not possible and we either settle with a giant gizmos or rage and flip the table. Unity uses a zoom-like solution, but I propose just a inspector setting; I find it gives more freedom to your choices.

**Comment by Zylann** [comment] 2016-12-31 17:08
Should it be a project setting or editor setting?

**Comment by volzhs** [comment] 2017-01-02 15:57
hm. what about having auto size gizmo based on project screen size and zoom level?

**Comment by Zylann** [comment] 2017-01-02 16:01
You would still need an on-screen size setting.

**Comment by volzhs** [comment] 2017-01-02 16:05
yes, option for setting should be in editor setting.

**Comment by eon-s** [comment] 2017-01-02 16:34
I prefer to have fixed size with inspector option for resize, and maybe with editor zoom option to keep on screen size but not general setting (you may want some of them scaled but not all).

**Comment by Zylann** [comment] 2017-01-02 16:39
@eons-s I don't see the point of having some gizmos scaled and others not. Gizmos are editor-specific, 2D handles and 3D handles never have per-node scaling options.

**Comment by eon-s** [comment] 2017-01-02 16:54
@Zylann true, but Position2D/3D are nodes used often as nodes, these could have the options, even for color axis too. 

And position nodes could be killed too, and get the option to have an editor only position gizmo enabled on every node (like the locks).

**Comment by mateusak** [comment] 2017-01-05 14:29
What eon-s is proposing is what I proposed as well. I guess I should have made it more clear.

**Comment by Zylann** [comment] 2017-01-05 15:49
I agree to the fact it's difficult to see the center of a Node2D unless you use Position2D (while I also think the goal of Position2D was to see a position without having to select it or putting set a sprite on it).

I wouldn't mind having editor-only options on Position2D nodes or all Node2Ds, they have to be properties if you want per-node custom size or color. However because they are properties like other nodes we should make sure it doesn't gets into exported games (like the tree expand states).

But if you have individual properties on Position2D some games would still be tedious to work on due to different scale and you would have to change that per instance instead of a single sizing mode option.

**Comment by mateusak** [comment] 2017-01-05 16:35
I'm not sure if I understand you, but what I mean is this:

Do you know when you create a theme for the panel node, and change its Style? Even with such theme selected in the node, you can still go there and apply a custom Style to it, not affecting any other panels. 

That said, the way I'm proposing is to add an setting to the project settings like `position2d_gizmos_size` and add an inspector setting to each Position2D node that allows you to override the global setting.

**Comment by bojidar-bg** [comment] 2017-01-05 16:37
Related/Dupe of #4255?

**Comment by mateusak** [comment] 2017-01-05 16:42
I guess it's related, but it's not a duplicate.

**Comment by Noshyaar** [comment] 2018-04-10 16:09
Still reproducible/relevant in 3.1 master 48890b1 : I don't think it's implemented yet?

**Comment by eon-s** [comment] 2018-04-10 17:30
No options for Position2D or 3D gizmo's length (which could be nice to have too).

**Closed** 2019-06-01 22:06 UTC
Labels: enhancement, junior job, topic:editor
