### ISSUE TITLE
OK and Cancel buttons are swapped between Windows and Linux

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#59379] opened 2022-03-21 09:07 UTC
### Godot version

3.5f59f30d

### System information

Linux, kernel 5.16.165arch1-1 (64-bit), x11, Linux(wine)  kernel 5.16.15arch-1-1(64-bit)

### Issue description

on wine:
![image](https://user-images.githubusercontent.com/70787919/159231355-fb07bc5a-1683-49e2-903c-80353cd717bc.png)
on linux:
![image](https://user-images.githubusercontent.com/70787919/159231597-8f0bc134-84ce-4b78-af52-0ef6075ed1bc.png)
hint: its the bottom two buttons

### Steps to reproduce

run>create script

**Comment by KnightNine** [comment] 2022-03-21 09:10
lmao

**Comment by bendnuts** [comment] 2022-03-21 09:21
oh, and its not just add script. its literally any confirm thingy

**Comment by akien-mga** [comment] 2022-03-21 09:22
Please give descriptive titles to your issues.

This is expected. Different OSes and desktop environments have different conventions for the positioning of OK and Cancel buttons. Windows and Qt put OK on the left and Cancel on the right - macOS and GTK put it the other way around.

Duplicate of #51799.

**Comment by akien-mga** [comment] 2022-03-21 09:23
Maybe we can expose this as an editor setting though (it is configurable for the project with `gui/common/swap_ok_cancel`, but not for the editor).

**Comment by bendnuts** [comment] 2022-03-21 09:31
i see.

**Closed** 2022-10-11 10:34 UTC
Labels: enhancement, topic:editor, usability
