### ISSUE TITLE
Godot 4.0 : Different issues with PrimitiveMesh

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#36760] opened 2020-03-03 12:19 UTC
**Godot version:**
Godot Engine v4.0.dev.custom_build.e2b66cacf built on March 2nd

**OS/device including version:**
Windows 64bits Professionnal 10.0.18363

**Issue description:**
Several errors in the system console when specifying a `CapsuleMesh` / `CubeMesh` / `CylinderMesh` / `SphereMesh` / `PrismMesh` in a `MeshInstance` : 

`ERROR: Condition "!F" is true. Continuing.
   at: clean_up_dependencies (./servers/visual/rasterizer.h:185)`

With a `PlaneMesh` and a `QuadMesh`, the error is different and is written in a loop as long as the `MeshInstance` is selected : 

`ERROR: Condition "det == 0" is true.
   at: invert (core/math/basis.cpp:69)`

Unlike Godot 3.x, the `Mesh` miniature assigned to a `MeshInstance` does not update and remains a plan.

**Comment by Calinou** [comment] 2020-03-03 13:41
> Unlike Godot 3.x, the Mesh miniature assigned to a MeshInstance does not update and remains a plan.

This is already being tracked in #36721.

**Comment by briansemrau** [comment] 2021-10-30 18:12
I'm not able to reproduce this issue in master 6b0b1a4c04.

**Comment by Calinou** [comment] 2021-10-30 18:48
Closing per @briansemrau's comment.

**Closed by Calinou** 2021-10-30 18:48 UTC
Labels: bug, topic:core
