### ISSUE TITLE
Global enum as export does not work: Invalid enum index, cyclic dependency and variables not declared

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#43432] opened 2020-11-10 08:52 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Linux mint

**Issue description:**
Autoload enum globals are causing problems in code. I tracked this (and a few other similar bugs) to  #30289 regarding class names getting mixed up, which is declared as fixing all related faults as far as I can see. It doesn't.

From the below, the simple thing to take is: if I have an enum in an autoload I get all the errors, if I move the enum into a normal node, the errors go away. If I change the autoload enum into a simple int, the problem goes away, i.e. Global enums do not work as export.

AUTOLOAD globals.gd
This is the only place that defines this enum (doesn't matter the name, it happens if I change to any name)
```enum REX_WEAPON {NONE, BULLET_SINGLE, BULLET_DOUBLE,LASER, DRONE,SPRAY}```

Weapon.gd
This is the only place that contains the class Weapon
```
extends Node2D
class_name Weapon

export var never_runs_out:bool=false
export(Globals.REX_WEAPON) var weapon_type
```

Weapon_Bullet.tscn
```
extends Weapon
var bullet_type_single:=true
func _ready() -> void:
	if !bullet_type_single:
		never_runs_out=false
```

Weapons.tscn
Contains scene of 5 nodes instanced from Weapon. I believe this is where Godot is getting completely messed up.

This is what I get:

this repeat for each of my 5 instances:
```
 res://entities/player/weapon.gd:12 - Parse Error: invalid index 'REX_WEAPON' in constant expression
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
```

This for any instances that use the base class export:
```
 res://entities/player/Weapon_Bullets.gd:10 - Parse Error: The identifier "never_runs_out" isn't declared in the current scope.
```

and the final error:
```
 res://entities/player/Weapons.gd:167 - Parse Error: The class "Weapon" couldn't be fully loaded (script error or cyclic dependency).
```

There is no cyclic dependency, the variable does exist and there is nothing wrong with the code. If I change the enum to an int all the errors goes away. If I move the enum from autoload it works. In other words, none of these errors are real.

**Comment by chucklepie** [comment] 2020-11-10 09:41
Hello,
I seem to have fixed it by doing this:

export(preload("res://singletons/Globals.gd").WEAPON) var weapon_type

Surely this is a bug? You shouldn't have to preload an autoload, and even if it does, my code never produced a cyclic dependency.

I found this at the following url:
https://godotengine.org/qa/45983/cannot-use-enum-as-variable

**Comment by chucklepie** [comment] 2020-11-10 09:48
and it trying figure it out, I've just lost an entire nights work by mistake cutting/pasting code. Brilliant :(

**Comment by Calinou** [comment] 2020-11-21 14:53
Duplicate of https://github.com/godotengine/godot/issues/14681. Feel free to add a comment with your findings there.

**Closed by Calinou** 2020-11-21 14:53 UTC
