### ISSUE TITLE
Property Inspector (Object Properties) Expand/Collapse All

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#12601] opened 2017-11-03 02:11 UTC
It would be useful to be able to expand all inspector categories and collapse them all by using an option in the object properties button.

**Comment by Dillybob92** [comment] 2017-11-03 02:16
Yeap, definitely would love this as a boolean in Editor Settings

**Comment by akien-mga** [comment] 2017-11-03 06:33
Duplicate of #9427.

**Closed by akien-mga** 2017-11-03 06:33 UTC
