### ISSUE TITLE
Godot tries to open files that do not exist.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#7131] opened 2016-11-17 00:05 UTC
**Operating system or device - Godot version:**
linux x86_64 
branch master

**Issue description** (what happened, and what was expected):
I am looking at why godot consumes cpu when nothing is really going on.
The joystick monitor runs a loop every 1 sec. and checks for /dev/input/event{0,31} devices.
Checking if they exist will be more lightweight compared to trying to open them.
The gain may not be huge but the change should be simple enough. In the link below a stat() call consumes less than half as much cpu

Godot also tries to open these two files:
/blackberry-deploy
""
The blackberry-deploy attempt should not happen or exist under the root "/" and I don't know why Godot is trying to open a file called ""

**Steps to reproduce:**
Start godot
`strace -fF -e trace=open -p <godot pid>`

**Link to minimal example project** (optional but very welcome):
FWIW some perf numbers on a different ways to test if a file exists. Note that stat() does the best.
http://stackoverflow.com/a/12774387

**Comment by hpvb** [comment] 2017-02-09 17:53
The file opening behavior you're seeing is actually udev behavior and can't be easily changed. The non-udev codepath basically works the same way so there's nothing to be gained by fixing it.

I have not been able to reproduce the other open file behavior on the godot 3 branch. It appears that that issue has been fixed.

**Comment by romeojulietthotel** [comment] 2017-04-17 00:05
1. You didn't see the joystick code trying to open devices instead of checking if they exist?
2. And you didn't see Godot trying to open /blackberry-deploy?
3. You also did not see Godot trying to open a file called ""?

If you could reply more specifically about what you did/did'nt see it would save us all a little time. Who doesn't like a time-saver. ;^)

I will try to test this out as soon as I can build it.

**Comment by akien-mga** [comment] 2017-09-04 08:19
The `blackberry-deploy` stuff seems to come from https://github.com/godotengine/godot/blob/2.1/platform/bb10/export/export.cpp#L527

It's super hacky and likely works only for @punto- as noone has any `blackberry-deploy` or `blackberry-deploy.bat` file in their root folder obviously. It's fixed in the master branch as we removed that branch, for 2.1 I think we should also either kill this code or make it opt-in.

**Comment by hpvb** [comment] 2017-09-05 12:50
Apart from the udev/joystick case on X11 there should be no more extraneous open()s since #10986. I think this can be closed now?

**Comment by akien-mga** [comment] 2017-09-05 12:55
Yeah but I want to fix the blackberry stuff on 2.1 first.

**Comment by akien-mga** [comment] 2017-09-05 13:20
Done.

**Closed by akien-mga** 2017-09-05 13:20 UTC
Labels: bug, discussion, platform:linux
