### ISSUE TITLE
Setting the background mode to canvas in a WorldEnvironment node turns godot interface unusable (DisplayServer regression)

### ISSUE THREAD

**Issue by navy-cap-echo** [godotengine/godot#55506] opened 2021-12-01 08:12 UTC
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 970

### Issue description

Adding a WorldEnvironment node to a scene and changing the Background mode to canvas make godot interface unusable. 
All appearing items (the dropdown, windows, ...) appears the same color.

![image](https://user-images.githubusercontent.com/55918951/144193389-09ccf492-4828-4d4c-a219-cd6ccb220cc8.png)

![image](https://user-images.githubusercontent.com/55918951/144193546-4b7b4eb1-ffc7-49b9-98bb-016198558cad.png)

![image](https://user-images.githubusercontent.com/55918951/144193677-71a81c6a-7f6b-484e-a35f-130070caa5ff.png)

![image](https://user-images.githubusercontent.com/55918951/144195220-de64b3e7-9f11-41db-aa72-882c0deb4f52.png)

### Steps to reproduce

- Create a 2D scene
- Add a WorldEnvironment node to the scene
- Change Background mode to Canvas

Also, be aware that by changing the background mode to canvas in the "default_env.tres" the problem does not appear.

### Minimal reproduction project

[Black.zip](https://github.com/godotengine/godot/files/7632022/Black.zip)

**Comment by Calinou** [comment] 2021-12-03 14:22
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2021-12-03 14:22 UTC
Labels: bug, archived, topic:rendering, confirmed, regression, topic:gui, topic:2d
