### ISSUE TITLE
Godot 4: Changing process mode to disable then back to inherit breaks Area2Ds

### ISSUE THREAD

**Issue by svendixon** [godotengine/godot#74988] opened 2023-03-16 16:13 UTC
### Godot version

Godot 4.0.stable.official

### System information

Windows 11, Vulkan, GTX 980 Ti (528.02)

### Issue description

I was attempting to create a hit stun using `process_mode` and setting it to `PROCESS_MODE_DISABLED` then back to `PROCESS_MODE_INHERIT` after a quick timer ended. However if the player gets hit stunned and then quickly attacks the enemy who intern gets hit stunned or visa-versa the `Area2D` seems to be in some weird state where the `get_overlapping_areas` array doesn't get cleared? Breaking the `Area2D`.

![disable_process_mode](https://user-images.githubusercontent.com/14341036/225680056-59357b5d-1dc9-4c28-aadd-e297e6ab8e53.gif)

FYI, the connections of the signals are still in place, so are the `monitoring` and `monitorable` flags, and `CollisonShape2D` is not `disabled`.

### Steps to reproduce

**_See attach sample project._**
_Move with the arrow keys and attack with the space bar._

### Minimal reproduction project

[DisableProcessBug.zip](https://github.com/godotengine/godot/files/10993012/DisableProcessBug.zip)

**Comment by markdibarry** [comment] 2023-03-16 17:39
Duplicate of https://github.com/godotengine/godot/issues/61420

**Comment by Calinou** [comment] 2023-03-21 23:23
- Duplicate of https://github.com/godotengine/godot/issues/61420.

**Closed by Calinou** 2023-03-21 23:23 UTC
