### ISSUE TITLE
[3.2.1] RichTextLabel tabulation bug with dynamic font.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#37081] opened 2020-03-16 03:11 UTC
**Godot version:**
3.2 branch at 809dc1a12ae16c6665a837e1ae7e3359650aadb0 
Not present in 3.2 stable

**OS/device including version:**
win7

**Issue description:**

Tabulation in a RichTextLabel, with a dynamic font loaded, has bad position, the second word after the tabulation get a position that ignores last tabulation.
Probably related with https://github.com/godotengine/godot/pull/36215 and the "backtrack" thing, but not sure. I can´t take the time to isolate, but i did a test project here (test with 3.2 current and stable to see the result):

3.2 stable:
![tabbug3_2_master](https://user-images.githubusercontent.com/11712737/76719989-c7245580-673b-11ea-8f8e-21c7553b12dc.png)

3.2 current:
![tabbug3_2_branch](https://user-images.githubusercontent.com/11712737/76720004-d1deea80-673b-11ea-99cf-56e3051b7bf5.png)

**Minimal reproduction project:**
[tab_bug.zip](https://github.com/godotengine/godot/files/4335860/tab_bug.zip)

**Comment by akien-mga** [comment] 2020-03-16 08:18
CC @Eoin-ONeill-Yokai, likely related to #35768.

**Comment by Eoin-ONeill-Yokai** [comment] 2020-03-17 18:13
@akien-mga It probably is. Things are bit crazy here with COVID-19 but I'll try to make some time to look at this in the future.

**Comment by Eoin-ONeill-Yokai** [comment] 2020-03-29 01:15
@akien-mga A correction is up now, though I might need some help testing on master with rebase since my work PC is having difficulties operating godot with the brand new windowing system (I think these are known issues iirc, I saw reduz mention something along those lines on twitter.) However, this should be working as expected and is a rather minor change / correction.

@Ranoller Thanks for taking the time to file a bug report for this nasty regression!

**Comment by Ranoller** [comment] 2020-03-29 04:49
Thanks to you to take the time to fix them!

**Comment by Eoin-ONeill-Yokai** [comment] 2020-04-06 19:50
@akien-mga I may have messed up my PR commit since this didn't automatically close. Now that the PR is merged and cherry-picked, we can close this issue.

**Comment by akien-mga** [comment] 2020-04-06 19:59
Fixed by #37397.

**Closed by akien-mga** 2020-04-06 19:59 UTC
Labels: bug, regression, topic:gui
