### ISSUE TITLE
Theme Editor makes the editor crash under some circumstances

### ISSUE THREAD

**Issue by rblopes** [godotengine/godot#69350] opened 2022-11-29 18:29 UTC
### Godot version

v4.0.beta5.official [89a33d28f], v4.0.beta6.official [7f8ecffa5]

### System information

KDE neon 22.04 (Ubuntu-derived)

### Issue description

Trying to open, or going back to an open scene tab, whose `Control` node has a Theme embedded or attached, and its Theme editor was used before, crashes the editor. Also, selecting a control node with a Theme resource might crash the editor.

It doesn't matter if the Theme resource is attached to the root node or any of its children.

As a workaround, I've found that deleting just the files related to the scene I'm editing inside `.godot/editor`, instead of annihilating the whole `.godot` folder, restores the editor back to a working condition. Another solution is to remove the Theme resource from the control.

Tried on both `beta-5` and `beta-6` releases, `beta-4` seems OK.

I'm sharing [a video](https://youtu.be/0FExWgLLq_Y) containing some footage of me stressing the editor to reproduce the bug. (There's also an issue, captured at the beginning of the video, where the Scene Tree dock becomes blank, but that is not the subject of this bug report.)

### Steps to reproduce

This is the simplest way I could find to reproduce the bug:
1. Start a new project;
2. Create a scene with a `Control` (or any derived class) node;
3. Add a Theme resource to it, open it in the Theme panel;
4. Open another scene, or create a new empty one in the editor;
5. Go back to the previous scene;
6. Godot Editor crashes.

### Minimal reproduction project

[theme-editor-crash.zip](https://github.com/godotengine/godot/files/10115925/theme-editor-crash.zip)

**Comment by kleonc** [comment] 2022-11-30 00:01
Might be a duplicate of #69159/#68774 which is present in beta5/6 (already fixed for beta7) and looks kinda similar. Can't tell for sure without an actual crash log though, and I can't reproduce the crash myself.

**Comment by rblopes** [comment] 2022-11-30 00:30
I read those other two bug reports before posting, but I wasn't sure if those are related to my issue, though.

I'll experiment again with my the MRP and other stuff when `beta-7` is released and give an update.

**Comment by kleonc** [comment] 2022-11-30 01:52
> I'll experiment again with my the MRP and other stuff when `beta-7` is released and give an update.

If you'd like you could try testing the current `master` by getting some uploaded artifacts from the CI actions. So no need for compiling the source yourself. For example: [Linux Builds](https://github.com/godotengine/godot/actions/workflows/linux_builds.yml) -> [latest `master` commit](https://github.com/godotengine/godot/actions/runs/3579038619) (as of writing this) -> bottom of the page -> [linux-editor-mono](https://github.com/godotengine/godot/suites/9575039414/artifacts/456044911) (seems like only the mono version is uploaded for Linux so it's bigger in size but it should be as fine for testing as non-mono version).

**Comment by rblopes** [comment] 2022-12-01 14:02
Sorry for not replying sooner.

I did some tests, using the Mono-enabled build, no issues so far, no crashes.

**Comment by kleonc** [comment] 2022-12-01 14:50
> Sorry for not replying sooner.
>
> I did some tests, using the Mono-enabled build, no issues so far, no crashes.

No problem, and thanks for testing! :slightly_smiling_face:

If you no longer can reproduce the crash then I'll close this issue as it's preasumably a duplicate of #69159 (in which case it's already fixed by #69252). And if by any chance it's not a duplicate of #69159, it still seems to be fixed anyway and hence no longer an issue.

Of course in case you or anyone else could reproduce the crash in a post-#69252 version then this issue could be reopened.

**Closed by kleonc** 2022-12-01 14:50 UTC
Labels: bug, topic:editor, crash
