### ISSUE TITLE
`ScrollContainer` `follow_focus` not working with `grab_focus` when called from `_ready`

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#57257] opened 2022-01-26 16:36 UTC
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

When a `ScrollContainer` has `follow_focus` activated it should follow the focused child node. This also works when calling `grab_focus` from a child node, in the `_input` method for example. But when calling `grab_focus` in the `_ready` method of the child the container does not scroll to it. Nevertheless the child gets focus. This could be intended but I couldn't find anything about it in the docs.
What confuses me even more, is that when adding
```yield(get_tree().create_timer(0.0), "timeout")```
before the `grab_focus` call the scrolling suddenly works. (I'm using this as a workaround at the moment.)

### Steps to reproduce

- open the reproduction project and execute it
- the last button should have focus, but it shouldn't be visible without scrolling
- now open the script and remove the comment from the `yield` line
- start the project again
- the button should be visible and have focus

### Minimal reproduction project

[focus_scroll_bug.zip](https://github.com/godotengine/godot/files/7943401/focus_scroll_bug.zip)

**Comment by KoBeWi** [comment] 2022-01-26 16:51
`grab_focus()` is often unreliable when calling in methods like `_ready()` etc.
You should use `call_deferred("grab_focus")`, it's a "proper" equivalent of your yield hack.

**Comment by RoniPerson** [comment] 2022-01-26 16:54
> `grab_focus()` is often unreliable when calling in methods like `_ready()` etc. You should use `call_deferred("grab_focus")`, it's a "proper" equivalent of your yield hack.

I tried that already and did it again in my example project right now and it does not seem to work on my side.

**Comment by EIREXE** [comment] 2022-02-13 19:19
There seems to be a regression with grab_focus, it used to work fine in 3.4, but it now fails when called right after the control is added to the scene tree.

**Comment by dweremeichik** [comment] 2022-02-18 06:09
I have also spent some time trying to figure out when follow focus does and does not work. It seems like there may be one or more corner cases here. Even with `call_deferred("grab_focus")` I am having issues getting it to follow the focused control. Disclaimer: my case has nothing to do with `_ready`, and is triggered by an event.

**Comment by RoniPerson** [comment] 2022-02-19 16:54
I also found calling `yield(get_tree(), "idle_frame")` before `grab_focus` to work. But only when not in `low_processor_mode`. So it is not usable for editor plugins.

**Comment by EIREXE** [comment] 2022-03-01 10:10
Did a bisect, something's off with f49ffe4bb02c6af443652f67bbf6c0c47344d721, investigating...

**Comment by RoniPerson** [comment] 2022-03-01 11:26
#3629 could be the same cause.

**Comment by RoniPerson** [comment] 2022-03-01 11:28
godotengine/godot-proposals#3629 seems to be related somehow

**Comment by KoBeWi** [comment] 2022-04-03 22:45
`call_deferred()` seems to work correctly in 4.0, so closing as there is a workaround already. The 0 timer used in the MRP is equivalent of 2 idle frames.

**Closed by KoBeWi** 2022-04-03 22:45 UTC
Labels: bug, topic:gui
