### ISSUE TITLE
QuadMesh primitive flip faces option has no effect

### ISSUE THREAD

**Issue by tom-jk** [godotengine/godot#64638] opened 2022-08-19 21:42 UTC
### Godot version

v4.0.alpha14.official [106b68050]
edit: and 3.5, also 3.1 (no flip faces option in 3.0)

### System information

Linux Mint 20, Vulkan Clustered, Nvidia RTX 2060 SUPER (515.65.01-0ubuntu0.20.04.1)

### Issue description

The QuadMesh primitive faces the same way regardless of whether flip faces is checked or not.

All other mesh primitives (those that make a visible mesh anyway) respond correctly, including PlaneMesh.

This happens in the editor and when the scene is run.

### Steps to reproduce

1. Open MRP.
2. Select QuadMesh node.
3. Toggle Flip Faces, observe no change.

### Minimal reproduction project

[Issue_64638.zip](https://github.com/godotengine/godot/files/9385556/Issue_64638.zip)

**Comment by Calinou** [comment] 2022-08-19 22:21
Does this occur in 3.5 too?

**Comment by tom-jk** [comment] 2022-08-20 08:31
Yes, same result.

**Comment by clayjohn** [comment] 2022-08-23 21:23
The root cause of this is the fact that QuadMesh does not use indices. The flip faces code relies on swapping the order of indices to flip faces.

**Comment by clayjohn** [comment] 2022-09-16 15:27
This is now fixed as QuadMesh and PlaneMesh are merged together

**Closed by clayjohn** 2022-09-16 15:27 UTC
Labels: bug, topic:core, topic:3d
