### ISSUE TITLE
MultiMeshInstance visible_instance_count property doesn't register changes after the first frame

### ISSUE THREAD

**Issue by thehatless** [godotengine/godot#66385] opened 2022-09-25 04:00 UTC
### Godot version

v4.0.alpha.calinou [08d8f884c]

### System information

Windows 10, Nvidia GeForce GTX 1650, Vulkan

### Issue description

Changes to a MultiMeshInstance's visible_instance_count property only take effect on the frame the node was created. Increasing or decreasing it on later frames doesn't change the number of visible instances.

This is problematic for multimesh's stated purpose of batching many meshes into one draw call.

### Steps to reproduce

Alter visible_instance_count on the first frame then after the first frame (demonstrated in attached project.)

### Minimal reproduction project

[Bugreport.zip](https://github.com/godotengine/godot/files/9639975/Bugreport.zip)

**Comment by rburing** [comment] 2022-09-25 07:44
Duplicate of https://github.com/godotengine/godot/issues/62809 (see my analysis there).

**Closed by rburing** 2022-09-25 07:44 UTC
