### ISSUE TITLE
Script Variables Do Not Appear For AnimationPlayer Script in C#

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15031] opened 2017-12-25 07:07 UTC
**Godot version:**
3.0 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
When using export variables in an AnimationPlayer in C#, they do not appear in the inspector, even after building the solution.

**Steps to reproduce:**
Attach a script to an AnimationPlayer.
Add any variable and give it the Export attribute.
Look at the inspector.

Other nodes may have a similar issue, haven't checked.

**Comment by jonbonazza** [comment] 2017-12-25 07:28
I have just encountered this issue on a Node2D, so it isn't isolated to AnimationPlayer. What's even weirder is that after some time, it appeared... I don't know what I did to make it appear all of the sudden. One thing that might be related is that I was trying to access the exposed field via an AnimationPlayer. Maybe something is bugged there with the connection?

**Comment by mrcdk** [comment] 2017-12-26 19:30
Duplicate of https://github.com/godotengine/godot/issues/12518 you need to build the solution for export variables to show because godot reads the assembly code

**Comment by 11clock** [comment] 2017-12-26 19:51
@mrcdk Please read the issue thoroughly, I specifically stated that the problem persists after rebuild. Only a complete restart works.

**Comment by akien-mga** [comment] 2018-01-05 15:39
That's the same issue as #12518, in my experience you need to build once + restart to get stuff to appear.

**Closed by akien-mga** 2018-01-05 15:39 UTC

**Comment by sophienarwhal666** [comment] 2019-12-29 00:37
Okay. You do not need to "build once" to actually get this to work. All you need to do is restart.
