### ISSUE TITLE
Error spam when renaming nodes in a scene with AnimationPlayer

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#83255] opened 2023-10-13 09:44 UTC
### Godot version

4.2 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you have AnimationPlayer with any animation track, renaming a node will spam errors referencing the track path:
```
ERROR: Found invalid node path 'Icon:position' on node 'Node2D/AnimationPlayer'
   at: (C:\godot_source\editor/scene_tree_dock.cpp:1610)
```
The error seems more related to scene tree dock than AnimationPlayer, I noticed the same error with TileMap scene tiles. On big scenes the error spam can freeze the editor. The line referenced in the error seems to have existed for some time, but some code changes made that error appear much more often (in fact I have never seen it until recently).

I'd suspect #80721 CC @tom95 (didn't test)

### Steps to reproduce

1. Create new scene
2. Add AnimationPlayer
3. Add some node
4. Create new animation and add track for any property of the new node
5. Rename a node on the scene

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-10-13 09:48
Potential duplicate of #83209?

**Comment by KoBeWi** [comment] 2023-10-13 10:01
Looks like the same issue/cause.

**Closed** 2023-10-13 10:08 UTC
Labels: bug, topic:editor, usability, regression
