### ISSUE TITLE
error on vulkan instance

### ISSUE THREAD

**Issue by Heliox01** [godotengine/godot#56353] opened 2021-12-30 19:37 UTC
### Godot version

4.0 dev built by me

### System information

Windows 11,rx 5600xt, vulkan ,driver radeon software 21.30

### Issue description

error on the console:
Godot Engine v4.0.dev.custom_build - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_get_json: Failed to open JSON file C:\Users\Elia\Desktop\RenderDoc_1.10_64\renderdoc.json
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1728270964944
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
Vulkan API 1.2.176 - Using Vulkan Device #0: AMD - AMD Radeon RX 5600 XT

ERROR: Transient parent has another exclusive child.
   at: (scene\main\window.cpp:412)
Editing project: C:/Users/Elia/Desktop/file/programmazione/godot/prova (C:::Users::Elia::Desktop::file::programmazione::godot::prova)
Godot Engine v4.0.dev.custom_build - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_get_json: Failed to open JSON file C:\Users\Elia\Desktop\RenderDoc_1.10_64\renderdoc.json
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2902833766192
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
Vulkan API 1.2.176 - Using Vulkan Device #0: AMD - AMD Radeon RX 5600 XT

### Steps to reproduce

just open godot

**Comment by Calinou** [comment] 2021-12-30 20:41
Duplicate of https://github.com/godotengine/godot/issues/56198 (same cause).

**Closed by Calinou** 2021-12-30 20:41 UTC
Labels: bug, topic:rendering
