### ISSUE TITLE
camera orbit

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#14417] opened 2017-12-08 17:19 UTC
would be nice to implement the same camera orbit system that can be found in blender called Auto depth, just checks what is under mouse cursor and uses that as a point of reference to rotate around, would make camera orbit much nicer to use when inspecting meshes

**Comment by Calinou** [comment] 2019-10-02 16:11
Duplicate of #17517, which has more information about the feature.

**Closed by Calinou** 2019-10-02 16:11 UTC
Labels: feature proposal, topic:editor, usability
