### ISSUE TITLE
Weird vulkan debug message running godot editor or any project.

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#58112] opened 2022-02-14 20:20 UTC
### Godot version

4.0.Alpha_2

### System information

Windows 10, AMD Ryzen 2700x, Nvidia 1070ti

### Issue description

Whenever I run a project from the editor I get this error: 

E 0:00:00:0080   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_get_json: Failed to open JSON file C:\Program Files\Rockstar Games\Social Club\SocialClubVulkanLayer.json
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 268251824
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:157 @ _debug_messenger_callback()

I think it has to do with the fact that my computer believes I have vulkan installed for GTA 5 still, but the game is long gone. However I think some residue might be left of that vulkan context that Godot finds and tries to interact with, but fails and thus causes the weird debug message. The project runs fine, but it just throws a random message at me.

When I run the editor from a command line (the console window is gone for me(see other BugReport)) it throws the same message, but still runs well

### Steps to reproduce

1. ? (Seriosly don't know what is up and how to reproduce... but probably involving deinstalling vulkan driver, download a game using vulkan, run said game, then deintalling said game and then run the editor?)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-02-14 20:56
Duplicate of https://github.com/godotengine/godot/issues/56089.

**Closed by Calinou** 2022-02-14 20:56 UTC

**Comment by Flavelius** [comment] 2022-05-06 08:29
In case anyone else stumbles upon this and the rockstar games spyware is definitely not installed:
delete the corresponding key in the registry under:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers
and the error will be gone.
