### ISSUE TITLE
Mouse events: last left click released is not caught

### ISSUE THREAD

**Issue by 3lis4** [godotengine/godot#23840] opened 2018-11-20 08:01 UTC
**Godot version:**  v3.0.6.stable.official.8314054

**OS/device including version:** Ubuntu 14.04.5 LTS 64 bits and Windows 7

**Issue description:**

Hi! 
I have an issue with the _gui_input() method. I joined a zipped project to show the "bug". It contains this simple code:
```gdscript
func _gui_input(ev):
    if ev is InputEventMouseButton and ev.button_index == BUTTON_LEFT:
        print("Left")
    if ev is InputEventMouseButton and ev.button_index == BUTTON_RIGHT:
        print("right")
```

When I do: left click pressed, right click pressed, right click released, left click released
I expect to have:
```
Left
right
right
Left
```

But the last left clic (released) seems to be ignored.

**Steps to reproduce:**
To reproduce it, just do the following: left click pressed, right click pressed, right click released, left click released

It will give this result:
```
Left
right
right
```
so the last left click (released) is ignored (?)

Also, I tried to do it doing: right click pressed, left click pressed, left click released, right click released
and then it works fine and I have :
```
right
Left
Left
right
```

Thanks!

**Minimal reproduction project:**

[mouse_events.zip](https://github.com/godotengine/godot/files/2598653/mouse_events.zip)

<sub>Bugsquad edit: Fixed codeblock formatting, `s/clic/click/`</sub>

**Comment by bojidar-bg** [comment] 2018-11-20 11:42
Couldn't reproduce on 2d6b994e476f00e5725117501f6fc006eadd0d30.
On the other hand, doing left press -> right press -> left release -> right release does not give the right release event:
```
Left
right
Left
```

**Comment by 3lis4** [comment] 2018-11-22 10:03
Hello,

Thanks for your interest. This can be a big issue as we're missing many player inputs. Is there any work around?

**Comment by bojidar-bg** [comment] 2018-11-22 10:44
@3lis4 I think you might be able to work around it by using _input instead of _gui_input and filtering events manually.

**Comment by Calinou** [comment] 2019-12-30 10:53
@3lis4 Can you still reproduce this on [Godot 3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by tom-jk** [comment] 2020-07-24 11:48
Linux Mint 18.3. Testing with MRP (with script modified to show click as +L or +R and release as -L or -R).

<details>
<summary>code</summary>

```gdscript
func _gui_input(ev):
	if ev is InputEventMouseButton and ev.button_index == BUTTON_LEFT:
		if ev.is_pressed():
			print("+L")
		else:
			print("-L")
	if ev is InputEventMouseButton and ev.button_index == BUTTON_RIGHT:
		if ev.is_pressed():
			print("+R")
		else:
			print("-R")
```
</details>

3.0.5.stable

Input|Output|?
----|----|----
+L +R -L -R|+L +R -L -R| :heavy_check_mark: 
+L +R -R -L|+L +R -R| :x: 
+R +L -R -L|+R +L -R| :x: 
+R +L -L -R|+R +L -L -R| :heavy_check_mark: 

3.1.alpha2

Input|Output|?
----|----|----
+L +R -L -R|+L +R -L| :x:
+L +R -R -L|+L +R -R -L| :heavy_check_mark: 
+R +L -R -L|+R +L -R| :x:
+R +L -L -R|+R +L -L -R| :heavy_check_mark: 

3.2.2.stable, 3.2.3.beta1

Input|Output|?
----|----|----
+L +R -L -R|+L +R -L -R| :heavy_check_mark: 
+L +R -R -L|+L +R -R -L| :heavy_check_mark: 
+R +L -R -L|+R +L -R -L| :heavy_check_mark: 
+R +L -L -R|+R +L -L -R| :heavy_check_mark: 

Appears to be resolved.

**Comment by Calinou** [comment] 2020-07-24 11:49
Closing as resolved per @tom-jk's comment.

**Closed by Calinou** 2020-07-24 11:49 UTC
Labels: bug, topic:core
