### ISSUE TITLE
`UPDATE_DISCRETE` & `UPDATE_TRIGGER` aren't blended correctly

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#68261] opened 2022-11-04 15:05 UTC
### Godot version

4.0.beta3

### System information

MacOS 13 (Ventura)

### Issue description

I have setup a animation tree with a BlendTree as it's root. When I connect two `Transition` nodes together, the second one is unable to play animations that modify the `region_rect` property on Sprite2Ds.

### Steps to reproduce

1. Create a new project with a AnimationTree
2. Add an AnimationNodeBlendTree as it's root
3. Add two transition nodes
4. Connect one's output to another's input
5. The second one will not work.

**Example:**
https://user-images.githubusercontent.com/32573897/200008069-0f99b428-ac8d-4b50-8856-c1a598db1bdb.mov

**Comment by alfredbaudisch** [comment] 2022-11-05 09:18
I can't reproduce this, the transitions are working (beta4 and custom-build-6882890).

Can you try beta4 @mageowl?

**Comment by mageowl** [comment] 2022-11-07 16:10
Weird! I tried making a new project, and it worked, but even after redo-ing all of the animation stuff, it still doesn't work on my main one.

Animation player:
![Screenshot 2022-11-07 at 8 08 18 AM](https://user-images.githubusercontent.com/32573897/200358141-cb8d7b05-69cd-4b1e-9f45-2d627d7dbf21.png)
Animation tree:
![Screenshot 2022-11-07 at 8 08 42 AM](https://user-images.githubusercontent.com/32573897/200358271-8c5899e6-0a7a-47e5-89da-99127fcf22b1.png)
Project:
https://github.com/mageowl/johns-world

**Comment by mageowl** [comment] 2022-11-08 01:15
Aha! The problem is in the Region Rect for the sprite. For some odd reason using the `frame` property works, but `region_rect` does not. No clue why.

**Comment by TokageItLab** [comment] 2022-11-22 01:15
It is caused by an accidental overwriting of the initial values at the end of the blending process. I probably did this when I did some kind of fix before...sorry. I will send a PR for fixing this later.

**Comment by TokageItLab** [comment] 2022-11-22 06:51
The problem of no playback is fixed in #68993, please check it. BTW, as for `region_rect`, I think the track path in the project is wrong, so it is probably not a bug.

**Closed** 2022-11-23 09:25 UTC
Labels: bug, confirmed, regression, topic:animation, topic:2d
