### ISSUE TITLE
Objects not selectable in Editor when in a Window-Node

### ISSUE THREAD

**Issue by zurrealStudios** [godotengine/godot#86191] opened 2023-12-15 11:11 UTC
### Tested versions

I had the Problem in different Versions. I encountered the Issue in following Versions:
- 4.2.1
- 4.1.3
- 4.1.2
- 4.0.3 (if I remember correctly)

### System information

Windows 10, Debian 12, Manjaro Linux

### Issue description

Hello dear Godot-Community,
I encountered following Bug(?), that when creating Window-Nodes in a Scene and also if the Window-Node is a Scene itself, and You put another Object in it, for example a Panel-Node, You can't move them with your Mouse in the Editor.
I don't know if it is intended and I got relatively comfortable manipulating the Objects with the Inspector. The major Problem I encountered now is, that I need to setup custom Anchors and this is not possible, while i can't see them. I hope the following Video will explain the Problem well.

https://github.com/godotengine/godot/assets/36889534/c7ff7653-9279-4da2-925c-1c152e21770d

Thank You all very much and have a great Day :)

### Steps to reproduce

Create a Window-Node in a Scene, or create a Window-Node AS a Scene. Put in it an Object (e.g. Panel) and try to move it with Your Mouse.

### Minimal reproduction project (MRP)

[WindowObjectsBug.zip](https://github.com/godotengine/godot/files/13684465/WindowObjectsBug.zip)

**Comment by AThousandShips** [comment] 2023-12-15 11:12
Duplicate of https://github.com/godotengine/godot/issues/79289

**Closed by AThousandShips** 2023-12-15 11:12 UTC
