### ISSUE TITLE
Minor UI bug with particles preprocess setting

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#26589] opened 2019-03-04 14:22 UTC
**Godot version:**

```
3.1.beta9.official
```

**OS/device including version:**

Linux

**Issue description:**

In the `Particles` node editor, the handle for the `preprocess` setting can be dragged all the way off the bar to the left.
This doesn't happen with other settings.
It seems pretty harmless, but I figured I'd report it.

![out](https://user-images.githubusercontent.com/2496231/53739050-d1d8b900-3e5e-11e9-9a7e-a02e32a3d75a.gif)

**Comment by akien-mga** [comment] 2019-03-04 14:32
Duplicate of #24191.

**Closed by akien-mga** 2019-03-04 14:32 UTC
