### ISSUE TITLE
Game Window Placement's Rect unpredictably offset get_viewport().get_mouse_pos()'s origin

### ISSUE THREAD

**Issue by BlenderNPR** [godotengine/godot#5883] opened 2016-07-23 19:55 UTC
**Operating system or device - Godot version:**
Windows 10 64bit, Godot 2.0.4.1

**Issue description** (what happened, and what was expected):
The setting
Game Window Placement > Rect > Centered (and maybe others, have not tested them proper)
...offset **get_viewport().get_mouse_pos()'s** origin point unpredictably when in **fullscreen**
origin just hovers somewhere in the top-left area of viewport

**Steps to reproduce:**
use get_viewport().get_mouse_pos() to find mouse pos in viewport
print mouse pos on any label
set game to start in fullscreen
with Game Window Placement > Rect > not default (centered was tested in my case)
**Result:** get_viewport().get_mouse_pos()'s origin will be off top-left corner

**Link to minimal example project** (optional but very welcome):
Unfortunately I'm not on my working machine when reporting this. Sorry.

**Comment by akien-mga** [comment] 2016-07-23 22:17
I couldn't reproduce the issue on Linux (Mageia 6 x64).
I made this simple test project to try to reproduce: [game_placement_test.zip](https://github.com/godotengine/godot/files/380000/game_placement_test.zip) (clicking left mouse button should toggle fullscreen mode)

@vnen Might this be related to #2498?

**Comment by BlenderNPR** [comment] 2016-07-23 23:12
Problem will occur if 
1. start from editor (f5) 
2. in fullscreen when set in project properties... 
3. Game Window Placement > Rect > Centered
[game_placement_test_edited.zip](https://github.com/godotengine/godot/files/380010/game_placement_test_edited.zip)

I just tested  it on 2.1beta and 2.0.4.1. Problem occur on both.

no problem when run directly from project list though. :/

**Comment by vnen** [comment] 2016-07-24 02:01
The only problem I have is that the window is fullscreen, but positioned in the wrong place (the editor tries to put the game window at the center of the screen, even with the fullscreen setting). The mouse position is reported correctly within the window.

**Comment by akien-mga** [comment] 2016-07-24 07:04
Still not reproducible for me on Linux when setting fullscreen in te project settings directly and starting from the editor.

**Comment by BlenderNPR** [comment] 2016-07-25 02:38
More result from random test last night.
I ran the last project on 2 machines, both Win10-64bit

1. on an intel core M3 tablet (intel HD 5300): co-ordinate error, fullscreen
2. on an intel i5 (GTX 560ti): it never go into fullscreen, top-left edge at the middle of the screen, without window decoration

Both ran from the editor.

**Comment by vnen** [comment] 2016-07-25 04:02
This is very strange. Can you try with the [2.1-rc1 version](https://godotengine.org/download)? Since it includes my patch referenced above, it might (hopefully) have solved this issue.

**Comment by BlenderNPR** [comment] 2016-07-25 05:37
2.1 rc 1
Fixed confirmed on Core M3 tablet and intel i5 machine.
Thanks! :smile:

**Comment by vnen** [comment] 2016-07-25 14:18
Great! Closing as fixed.

**Closed by vnen** 2016-07-25 14:18 UTC
Labels: bug, topic:core
