### ISSUE TITLE
Priority 1 "Next Pass" being drawn over parent material

### ISSUE THREAD

**Issue by dreamingWitch** [godotengine/godot#33471] opened 2019-11-09 03:26 UTC
**Godot version:**
3.2 beta-1

**OS/device including version:**
Linux HP Envy X360, Ryzen 5 2500U

**Issue description:**
In Godot 3.1, we could give to a 3D material a priority 1 "Next pass" with the "unshaded" and "no_depth_test" flags for a quick and easy "see-through walls" effect. Now in 3.2 beta-1, this pass appears over the original material.

 In 3.1:
![image](https://user-images.githubusercontent.com/18239423/68521672-5f339f00-0271-11ea-871f-02dc18e26d1e.png)
In 3.2 beta-1:
![image](https://user-images.githubusercontent.com/18239423/68521687-7f635e00-0271-11ea-8556-de4736c8e1d7.png)

**Steps to reproduce:**
Create a Mesh Instance. Give it a spatial material and give this material another spatial material as its "Next Pass". Set this "Next Pass"'s priority to 1 and set to true its material's "Unshaded" and "No Depth Test" flags.

**Minimal reproduction project:**
[next_pass_issue_demonstration.zip](https://github.com/godotengine/godot/files/3826861/next_pass_issue_demonstration.zip)

Or is this the true intended behaviour?
If so, could there be another simple way to get the same result?

**Comment by clayjohn** [comment] 2019-11-09 04:04
Duplicate of #31164

The reason this isn't a bug is detailed in comment https://github.com/godotengine/godot/issues/31164#issuecomment-518868682

Feel free to ask for clarification if you need it. :)

**Closed by clayjohn** 2019-11-09 04:04 UTC
