### ISSUE TITLE
(4.0) Navigation agent and obstacle nodes have small icons

### ISSUE THREAD

**Issue by BlueStaggo** [godotengine/godot#57255] opened 2022-01-26 16:07 UTC
### Godot version

4.0 alpha 1

### System information

Windows 11, Vulkan, NVIDIA GeForce GTX 1650 472.12

### Issue description

The following nodes have small icons:
- NavigationAgent2D
- NavigationAgent3D
- NavigationObstacle2D
- NavigationObstacle3D

Image:
![image](https://user-images.githubusercontent.com/71090710/151200300-8fd9eb57-9257-4290-8835-5d010f6b4ff4.png)

### Steps to reproduce

If you have any of the nodes I mentioned in any of your scenes, you should see their icons. If not, create a new node and scroll to the bottom. 

### Minimal reproduction project

Not needed. Just create a new project then add a new node.

**Comment by akien-mga** [comment] 2022-01-26 16:13
Duplicate of #57129

**Closed by akien-mga** 2022-01-26 16:13 UTC
