### ISSUE TITLE
KinematicBody move_and_slide with infinite_inertia set to false doesn't work with vehicles

### ISSUE THREAD

**Issue by ThomasUijlen** [godotengine/godot#40025] opened 2020-07-01 16:52 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
When using a KinematicBody with move_and_slide ant turn infinite_inertia off it doesn't work with vehicles.
Since the vehicle is a RigidBody you shouldn't be able to push but you still can.

**Steps to reproduce:**
Just push a vehicle with a KinematicBody with infinite_inertia set to false.

**Comment by madmiraal** [comment] 2020-07-02 07:50
Duplicate of  #31981.

**Closed by madmiraal** 2020-07-02 07:50 UTC
