### ISSUE TITLE
Suggest snake_case when attaching a node script

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#67897] opened 2022-10-26 08:49 UTC
### Godot version

4.0 Beta3

### System information

Any

### Issue description

When a node script is attached the suggested name (love this feature btw) should be converted to snake case. It currently just takes the name of the node (which uses PascalCase). There is one exception, if the scene is saved then the file names base name is used.

I suggest:
- get rid of the file name based naming
- use String().to_snake_case()

I think this is the relevant function that needs to get + `.to_snake_case()` at one of the strings. 
```
void ScriptCreateDialog::config(const String &p_base_name, const String &p_base_path, bool p_built_in_enabled, bool p_load_enabled) {
	class_name->set_text("");
	class_name->deselect();
	parent_name->set_text(p_base_name);
	parent_name->deselect();
	internal_name->set_text("");

	if (!p_base_path.is_empty()) {
		initial_bp = p_base_path.get_basename();
		file_path->set_text(initial_bp + "." + ScriptServer::get_language(language_menu->get_selected())->get_extension());
		current_language = language_menu->get_selected();
	} else {
		initial_bp = "";
		file_path->set_text("");
	}
	file_path->deselect();

	built_in_enabled = p_built_in_enabled;
	load_enabled = p_load_enabled;

	_language_changed(current_language);
	_class_name_changed("");
	_path_changed(file_path->get_text());
}
```

### Steps to reproduce

Create a script using the `attach script to node`-button.

**Comment by KoBeWi** [comment] 2022-10-26 10:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/1211
There is a PR implementing it.

**Closed by KoBeWi** 2022-10-26 10:50 UTC
