### ISSUE TITLE
Problem exporting in headless mode if the project has never been opened

### ISSUE THREAD

**Issue by lyubomirv** [godotengine/godot#71521] opened 2023-01-16 17:21 UTC
### Godot version

4.0 beta12

### System information

Linux x86-64, Debian 11

### Issue description

I am trying to export a game using the editor in `--headless` mode and this fails because the project has not been open at least once in the full editor. During the export there is a log message that says:

> ERROR: Failed loading resource: res://.godot/imported/icon.svg-218a8f2b3041327d8a5756f3a245f83b.ctex. Make sure resources have been imported by opening the project in the editor at least once.

This is a valid scenario, though, as in a project you usually defer the building/exporting of a game to a CI system that builds the game for all platforms, and that system usually runs command-line versions of all the tools, hence the `--headless` flag. The CI system would checkout the code from a repository, and do its work.

However, Godot's documentation explicitly mentions that the `.godot` directory should not be committed. That means that the cache of the imported files would not be present on the CI system, and the above error prevents the export.

Note that there was no such problem in version 3.x (e.g. 3.4, 3.5), as I've tested the exact same thing with the same CI system I am running and exports were done without any problems in `--headless` mode without first opening the project.

So it seems there are two choices here:
- Commit the `.godot` directory to the repository (which is what can workaround the problem currently); or
- Make Godot generate these cache files in `--headless` mode, or provide some other parameter like `--rebuild-import-cache` or something that can be used together with `--headless` to prime the system before export.

### Steps to reproduce

1. Get the minimal project, it has just the godot icon in an otherwise empty scene. Don't open it with the editor, or if you do, close the editor and delete the `.godot` directory.
2. Execute this command on Linux from the project's directory:
    ```godot.4.0.beta12.x86_64 --headless --export-release linux.x86_64 export/test_export.x86_64```
3. See that in the `export` directory, you have the exported game but if you open it, it would be an empty scene.

4. Try exporting with the editor. The exported game will have the godot icon on the screen.

### Minimal reproduction project

[test_export.tar.gz](https://github.com/godotengine/godot/files/10427911/test_export.tar.gz)

**Comment by Calinou** [comment] 2023-01-16 21:29
Duplicate of https://github.com/godotengine/godot/issues/69511 (same cause).

**Closed by Calinou** 2023-01-16 21:29 UTC
