### ISSUE TITLE
Toggling breakpoints break when line spacing is high

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#93036] opened 2024-06-11 14:46 UTC
### Tested versions

- Reproducible in: 4.3.dev [a7aa8356b9288fb6de1cef2980465703c63102ea] and 4.3.beta1.

### System information

N/A

### Issue description

When hovering/clicking the breakpoint gutter in a `Text/CodeEdit` node that has `line_spacing` set to a high value, it can result in the wrong line getting the breakpoint.

CC @kitbdev.

### Steps to reproduce

- Create a `Text/CodeEdit` node and put some text in it.
- Set its `line_spacing` theme property to a high value (e. g. 10).
- Run the project and move your mouse slowly in the gutter.

### Minimal reproduction project (MRP)

Unnecessary, trivial to reproduce.

**Comment by RadiantUwU** [comment] 2024-08-01 17:48
Looks like it might be `TextEdit::get_line_column_at_pos` screwing things over. I'll try to look over a fix.

**Comment by RadiantUwU** [comment] 2024-08-01 17:50
```cpp
int TextEdit::get_line_height() const {
	return MAX(text.get_line_height() + theme_cache.line_spacing, 1);
}```
Shouldn't this account for it?
Unless the theme cache for line spacing isn't being updated properly.

**Comment by kitbdev** [comment] 2024-08-01 18:52
I believe the issue is because TextEdit only redraws the gutter when the hovered gutter changes, but CodeEdit uses different logic to determine which one is hovered, causing the wrong one to be hovered and then not updating when it should.

`CodeEdit::_main_gutter_draw_callback` uses `bool hovering = p_region.has_point(get_local_mouse_pos());`, while `TextEdit` uses `get_line_column_at_pos()` which isn't the same as the rect sent for the draw callback.

https://github.com/godotengine/godot/pull/92865 fixes it by exposing `get_hovered_gutter()` and using that in `CodeEdit` instead.

**Comment by RadiantUwU** [comment] 2024-08-01 22:06
> https://github.com/godotengine/godot/pull/92865 fixes it by exposing get_hovered_gutter() and using that in CodeEdit instead.

Is the bug no longer reproducible in #92865 ?

**Comment by kitbdev** [comment] 2024-08-02 16:45
> Is the bug no longer reproducible in https://github.com/godotengine/godot/pull/92865 ?

Yes, I cannot reproduce it in #92865.

**Comment by kitbdev** [comment] 2024-09-30 00:02
- fixed by https://github.com/godotengine/godot/pull/92865

**Closed** 2024-09-30 00:04 UTC
Labels: bug, topic:gui
