### ISSUE TITLE
PathFollow 3D erratic rotations / wobbling / twitching

### ISSUE THREAD

**Issue by soloparatolos** [godotengine/godot#3713] opened 2016-02-15 10:16 UTC
The object following pathfollow offset gets weird and erratic rotations but only on the first loop/lap. Tested on beta and RC 2.0 on linux systems.

Simple test inluded to confirm the issue.
[followcurvetest.zip](https://github.com/godotengine/godot/files/130461/followcurvetest.zip)

**Comment by tagcup** [comment] 2017-11-17 19:34
Does this happen with the current master branch?

**Comment by eon-s** [comment] 2017-11-18 02:13
Using a build like a week old, the motion is similar to the original one, 3 points on the right side have a small "shake" when turning.

Here is the project for master:
[curvetestv3.zip](https://github.com/godotengine/godot/files/1484291/curvetestv3.zip)

**Comment by tagcup** [comment] 2017-11-18 03:19
That's not a bug in pathfollow3d. It's working as expected, following the tangent of the curve. If the curve tangent isn't smooth (as in the attached project), you'll get "erratic rotations".

The curve class can be changed to guarantee smooth derivatives/gradients or some helper could be added to the UI to guarantee that the tangent manifold is smooth maybe, but it's a lot work work for little gain. I'd just be careful when designing curves.

**Comment by tagcup** [comment] 2017-11-18 03:21
I know you can't really see the torsion on the UI but you can try to be extra careful about making it smooth

**Comment by eon-s** [comment] 2017-11-18 04:32
Well, I have just tested the sample project in both versions and that is what appears to be the problem mentioned in the OP, so you say that is an issue on the curve design then?

Too bad there is not possible to see the points on the inspector for fine tuning...

**Comment by tagcup** [comment] 2017-11-19 23:36
You can see the points and the curve itself quite well if you zoom in, but what matters is the torsion of the curve which is the second derivative.

Roughly speaking, if you see kinks or "sudden" changes in your curve when you zoom in, that's a bad sign.

Again, introducing a new type of curve based on a different type of polynomial which makes in hard to introduce large gradient changes would be a solution.

**Comment by OuTopos** [comment] 2018-07-14 21:43
I'm on Godot v3.0.5 stable.
PathFollow2D rotation seems to be working properly.
PathFollow (3D) rotation is not working properly.
The behavior that I expect is that the rotation is perpendicular to the curve.
And the same offset would always produce the same rotation.
That is how PathFollow2D seems to work.

 #14321 seemed to have fixed it for 2D.
Could 3D get the same treatment?

**Comment by ywaby** [comment] 2018-11-29 15:29
same with master build.
PathFollow node loop will result strange rotate.
I replace with OrientedPathFollow node,and it is work fine

**Comment by rogeriodec** [comment] 2019-03-16 03:52
![](https://cdn.discordapp.com/attachments/212250894228652034/556321247147982859/c.gif)

I created a Path (3D) in capsule form and made a mesh move over it, using PathFollow.
**The mesh has absolutely no rotation**.
However, as you can see in the image, the mesh appears slightly rotated.
I do not know what causes this.
Any idea?

**Comment by funkbro** [comment] 2019-03-22 11:04
Closing the curve doesn't actually "Close" the curve, but instead places another point at the start point.
This causes the anchors to be seperate and unable to use the "Mirror Handles" options.
The main issue though is it causes a noticeable rotation jitter. 
[https://youtu.be/-4zX-wWV_L8](url)

**Comment by aaronfranke** [comment] 2020-06-08 15:44
This bug report seems to be still valid due to the duplicate reported in #36258, but it needs an updated minimal reproduction project. Neither of the two projects posted above work in Godot 3.2.2.

**Comment by eon-s** [comment] 2020-06-08 16:10
This is a fixed example tested on 3.2.2beta4, the body glitches on turns and after one loop the rotation breaks completely.

[curvetestv322.zip](https://github.com/godotengine/godot/files/4747177/curvetestv322.zip)

**Comment by Calinou** [comment] 2021-07-02 14:32
I can still reproduce this on 3.3.2 and 3.4.beta c04521986, specifically this part:

> the body glitches on turns and after one loop the rotation breaks completely.

https://user-images.githubusercontent.com/180032/124289886-179f0c80-db53-11eb-83c2-49a9549ecd64.mp4

**Closed** 2022-06-15 21:54 UTC
Labels: bug, topic:core, confirmed, topic:3d
