### ISSUE TITLE
Hovering over dictionary key in the inspector results in error

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#83084] opened 2023-10-10 03:24 UTC
### Godot version

v4.2.dev.custom_build [6b727ebdd] (master at the time of writing)

### System information

Godot v4.2.dev (6b727ebdd) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

Hovering over an existing key of an exported `Dictionary` in the inspector results in the following error:

```
Invalid tooltip formatting. The expect string should be formatted as 'type|class|property|args'.
```

I discovered this while testing this pull request of mine: https://github.com/godotengine/godot/pull/82947 - however the error is not caused by it... I made a debug build of master to confirm, which showed that the error comes from here: https://github.com/godotengine/godot/blob/6b727ebdd298bdfad8b5c5ea78100bfb6a537d79/editor/editor_help.cpp#L2858

### Steps to reproduce

Export a dictionary:

```
@export var x:Dictionary
```

Add some keys in the inspector, and hover over the key.

**Note** v4.2.dev6.official [57a6813bb] is not affected.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-10-10 05:24
* Duplicate of #82934.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-10-10 05:24 UTC
