### ISSUE TITLE
Wrong collision layer value if it was changed after editing layer/mask name

### ISSUE THREAD

**Issue by MasterOfSteel** [godotengine/godot#47302] opened 2021-03-23 14:54 UTC
**Godot version:**
3.2.3

**Issue description:**
After changing the name of a physics/collision layer and changing values of all layers to false, layer value becomes maximal (2147483648) instead of minimal (0).

**Steps to reproduce:**
I believe that it is not important as to which layers specifically are changed, as long as it is the same layer whose value is being changed and the one that has been renamed
1. Create a scene with an area2D and a collision shape
2. Change values of layers 1, 2, 3, 4 to true
3. Change the name of first four layers in the projects settings to A, B, C, D
4. Set area2D's all mask and/or layer flags to false
5. Add a script with: `func _ready(): print(get_collision_mask())`
6. Run the simulation
7. If the bug happened, the script will output '2147483648' instead of '0' that is expected

Project with broken collision layers:
[Test.zip](https://github.com/godotengine/godot/files/6190494/Test.zip)

**Comment by pouleyKetchoupp** [comment] 2021-03-23 17:10
Looks like a duplicate of #41281, fixed in #42733.

Could you please confirm it's fixed in [3.3-RC6](https://godotengine.org/article/release-candidate-godot-3-3-rc-6)? It won't fix a broken collision layer unless you use the reset button (↺), but the breakage shouldn't happen anymore.

**Comment by Calinou** [comment] 2021-04-01 23:11
@MasterOfSteel Bump :slightly_smiling_face: 

See above:

> 
Could you please confirm it's fixed in [3.3-RC6](https://godotengine.org/article/release-candidate-godot-3-3-rc-6)? It won't fix a broken collision layer unless you use the reset button (↺), but the breakage shouldn't happen anymore.

**Comment by pouleyKetchoupp** [comment] 2021-06-07 17:15
Closing for now as it looks like a duplicate. Feel free to re-open if you have more information to share.

**Closed by pouleyKetchoupp** 2021-06-07 17:15 UTC
Labels: bug, topic:physics
