### ISSUE TITLE
Cannot use negative numbers in `@export_range`

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#69544] opened 2022-12-03 23:09 UTC
### Godot version

4.0.beta7

### System information

Irelevant

### Issue description

When using `@export_range()` it does not accept any negative ints and floats as both first and second argument.

### Steps to reproduce

`@export_range(-1, 1) var x`
copy-paste this code into any script and get:
`Parse Error: Expected float as argument 1 of annotation "@export_range".`

### Minimal reproduction project

see above

**Comment by MewPurPur** [comment] 2022-12-04 00:23
Duplicate of #41183

**Closed** 2022-12-04 00:51 UTC
