### ISSUE TITLE
Collision shapes persist after they've been deleted

### ISSUE THREAD

**Issue by xyroclast** [godotengine/godot#7693] opened 2017-02-01 01:50 UTC
OS: Linux Mint 18
Godot: 2.1.2

Steps to reproduce:
Create a scene consisting of a KinematicBody with a child CollisionShape (I used capsule). Add some sort of image or animation as well, so the object is visible (I used AnimatedSprite3D). Script the KinematicBody so that it has downward movement (I used the move() function with a downward Y direction)
Save the scene and place an instance of the scene in a scene with a collide-able floor.
Test the game and verify that the object stops at the floor.
Then, delete the CollisionShape from the saved scene.
When you run the test again, you should see the object still continuing to collide with the ground.

Originally I thought this was just my lack of understanding of how Godot collision works, but you can verify that it's a bug by following the above steps again, but never create the CollisionShape in the first place. The object will pass through the floor as expected.

**Comment by eon-s** [comment] 2017-02-01 03:39
I think the scene is not being updated on the main scene if you run it just after deleting the node, if you touch anything on the main scene so it gets marked as modified before running, it should update the instance with the current version.

**Comment by xyroclast** [comment] 2017-02-01 04:48
Doesn't seem to be the case in my project, unfortunately, as far as I can tell - I've modified quite a few things in the main scene over the last while and haven't had any of the removed collision shapes stop doing their thing.

As an added note, not sure if it's causing the issue, but when I looked into one of the afflicted sub-scene files in a text editor, I noticed that it still has a reference to the deleted capsule - "[sub_resource type="CapsuleShape" id=1]" - Is it possible that the CollisionShape object is being destroyed, but somehow the associated shape itself is somehow staying behind and causing trouble?

**Comment by eon-s** [comment] 2017-02-01 10:19
Is possible that, for some reason, the collision shape node was removed and the shape resoure remained there.

I was unable o replicate, at least on Windows, I see the CollisionShape2D (after deleting the original) on the editor but does not appears (nor the shape) on the running scene.

**Comment by bojidar-bg** [comment] 2017-02-01 10:19
Duplicate of #2804.

**Comment by eon-s** [comment] 2017-02-01 10:22
@bojidar-bg I don't think is duplicate because if I understand right, is removing the shape from the editor, not the common error of removing shape from code.

**Comment by bojidar-bg** [comment] 2017-02-01 10:25
@eon-s Yeah, but the cause is still the same, even if the symptom is different. You don't get to go to your doctor for coughing and running nose separately, you go for both at once.

Anyway, thinking about it, I guess I might reopen this one, since it should be easy to fix this symptom in core.

**Comment by eon-s** [comment] 2017-02-01 12:41
@xyroclast  I can't replicate on Ubuntu 64 bit either, maybe your project/scene was corrupted, using different Godot versions perhaps?

Check if you can do it on a new project and share the broken scenes.
Also, just in case, try with the self contained mode (an empty `._sc_` file where Godot executable is located).

@bojidar-bg I thought it could be some problem with resources on the scene file in 2.1.2 but can't break my scenes here, not even in my most messy projects, might be something else.

**Comment by pkowal1982** [comment] 2017-02-01 14:32
I've also encountered this problem. On Windows 7 and Ubuntu 16.04, both 64 bits versions. Godot 2.1.2 and before.
Short example to check it on your own.
It should print COLLISION on run without modification.
But get rid of RemoveMe node and run the scene once again. For me it still prints COLLISION.
[godot_remove_bug.zip](https://github.com/godotengine/godot/files/745101/godot_remove_bug.zip)

**Comment by eon-s** [comment] 2017-02-01 14:58
For some reason, I was trying to do this on 2D, maybe got confused reading something else, that is why example projects are more than welcome I guess :sweat_smile: 

----------------------------------

And yes, removing the CollisionShape for any kind of body does not remove the shape resource, even on Godot 3, custom build of 01/30 from fixnum.org site.

**Comment by reduz** [comment] 2017-02-01 15:18
Its a design problem of godot 2.x which can't be fixed. 3.0 will solve it

**Comment by eon-s** [comment] 2017-02-01 15:29
To avoid this problem while we wait for Godot 3, before removing a CollisionShape, clear the Shape from the inspector, that should remove it from the scene file.

**Comment by xyroclast** [comment] 2017-02-01 19:21
Thanks for the responses guys, I'll go with @eon-s 's fix until 3 comes out!
I'm proud that my understanding of Godot has grown enough that my bug senses were tingling correctly.
One more question: What's the easiest way to fix scenes where I've already deleted the shape, without breaking things? Is it best to tear each one down and start over, or is there a reasonably simple fix? (my thoughts jump to finding lines to delete from the scene files in a text editor, but that might be unadviseable?)

**Comment by eon-s** [comment] 2017-02-01 20:00
@xyroclast Adding a new collision shape, setting shape then clearing it may solve the inconsistency on the scene file.

Or, to make it by hand or if you have more shapes on the body, with the scene closed on Godot, open the tscn file with a text editor, on the section where the body data is located there should appear a couple of "shapes" references (type and properties), check the id and remove the resource with that id on the top of the file, then delete all these lines on the body part (if there are many shapes I'm not sure if you have to fix the index there), finally put the shape count on zero (or the corresponding number) for the body.

**Comment by xyroclast** [comment] 2017-02-01 20:01
@eon-s thank you!

**Comment by xyroclast** [comment] 2017-02-01 23:00
Update for anyone else needing a fix:
I've just verified that adding a new CollisionShape node to the KinematicBody will immediately erase the persisting shape object.

**Comment by kubecz3k** [comment] 2018-04-10 17:18
I'm revisiting old issue, I think this should be fixed in 3.0, please let us know if that's not the case!

**Closed by kubecz3k** 2018-04-10 17:18 UTC
Labels: bug, junior job, topic:core, topic:physics
