### ISSUE TITLE
1px tall sprite not centered properly

### ISSUE THREAD

**Issue by jackwilsdon** [godotengine/godot#24615] opened 2018-12-27 01:00 UTC
**Godot version:** 3.0.6

**OS/device including version:** Windows 10 10.0.14393

**Issue description:** 1px tall sprites with the "centered" option selected are not centered correctly.

**Steps to reproduce:**

1. Take a 1px tall image and create a sprite of it:

    ![1px](https://user-images.githubusercontent.com/1843197/50460987-9c9d7f80-0972-11e9-9de6-790781b8bd0b.png)

2. Ensure that `Centered` is checked.
3. Note that the sprite is not aligned to the pixel grid or it's selection box;

    ![Godot issue](https://user-images.githubusercontent.com/1843197/50460983-95767180-0972-11e9-93ce-13601cb19a0e.png)

**Minimal reproduction project:** [1pxIssue.zip](https://github.com/godotengine/godot/files/2711102/1pxIssue.zip)

**Comment by eon-s** [comment] 2018-12-27 09:42
By marking a pixel centered, you are trying to get half pixels and that is not possible, I do not think there is a way to solve that.

The offset with the selection may be visual by the editor assuming that the sprite is in one rect but drawing correctly in full pixels, displaced.

**Comment by jackwilsdon** [comment] 2018-12-27 16:40
Surely centering a 1px wide/tall image just means leaving it where it is when it was not centered? Otherwise you're pushing it off the pixel grid? This is most likely a duplicate of #7015 so feel free to close this if it is.

**Comment by akien-mga** [comment] 2019-11-11 13:44
Duplicate of #7015 indeed.

**Closed by akien-mga** 2019-11-11 13:44 UTC
Labels: bug, topic:core
