### ISSUE TITLE
Editor window closing when running game from the editor

### ISSUE THREAD

**Issue by macjuul** [godotengine/godot#35664] opened 2020-01-28 14:48 UTC
**Godot version:**
3.2 RC 4 (Mono)

**OS/device including version:**
Windows 10

**Issue description:**
The bug causes the editor window to close when running the game, leaving just the game itself and the Godot console open. Exiting the game will cause the console to close as well. The bug itself appears to be rather unpredictable and re-opening the editor does not seem to solve it, however I found two ways to temporarily fix the issue.

- Clear the AppData\Local\Temp\Godot directory (The issue returns within 1 minute after this fix)
- Delete the .mono directory within the project (The issue returns after multiple hours after this fix) 

At the moment the editor window closes, the following errors appear in the console
![image](https://user-images.githubusercontent.com/7606171/73272913-708ea680-41e3-11ea-8a21-ae695854e47d.png)

For the past 3 days the bug has returned at least 2 or 3 times each day at mostly random points, including when creating a new .cs file, changing project settings, and simply just opening the project in Godot.

**Steps to reproduce:**
- Open up a working Mono project
- Work on the project for anything between a few minutes to a few hours
- The editor window disappears when the game is run from the editor
- Apply one of the two fixes and the editor window stops closing again, at least until the issue 
inevitably returns

**Minimal reproduction project:**
I prefer to keep my projects source private, and so far attempting to reproduce the issue in separate projects hasn't worked out yet

**Comment by Torguen** [comment] 2020-01-29 09:33
This also happened to me, the editor window closed suddenly without any crash and I could not get information about that because I have the console disabled.

**Comment by jasonswearingen** [comment] 2020-02-02 13:24
I haven't had the editor crash yet, but I have seen a lot of weirdness regarding my C# code running in the editor (not on purpose).  Such as key inputs being partially consumed by a C# input controller while I'm doing stuff in vs2019.  Partially, as in "pressing up arrow causes a different IDE window to scroll, but my input cursor doesn't" kind of wierdness.

I killed godot, put ```if (Engine.EditorHint){ return;}``` in related places, restarted godot, and my problems went away.

**Comment by KoBeWi** [comment] 2020-12-21 00:41
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by KoBeWi** [comment] 2021-05-15 23:42
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2021-05-15 23:42 UTC
Labels: bug, topic:editor, topic:mono

**Comment by GNamimates** [comment] 2021-08-09 15:18
I manage to reproduce this by leaving the window open for a few minutes in the recent godot version
several times

**Comment by Calinou** [comment] 2021-08-09 15:29
@GNamimates Please open a new issue with a minimal reproduction project attached.

**Comment by Torguen** [comment] 2021-08-09 15:59
3.3.3 rc1 has not given me this problem. Neither did the latest stable release.

**Comment by GNamimates** [comment] 2021-08-09 16:48
I mean this does happens to me but in a different way, oopsie sorry about that 😅 mine only closes when the window is left on for a few minutes...
