### ISSUE TITLE
Editor crash when importing TPS Demo with GLES2 and Bullet

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25600] opened 2019-02-04 04:44 UTC
**Godot version:**
3.1 

**OS/device including version:**
Ubuntu 18.04.1 Intel HD 3000

**Issue description:**
When I imported TPS Demo, then editor crash and show this backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fcefa73ef20] (??:0)
[2] btQuantizedBvh::btQuantizedBvh() (/media/veracrypt10/godot/thirdparty/bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:30)
[3] btQuantizedBvh::serialize(void*, unsigned int, bool) const (/media/veracrypt10/godot/thirdparty/bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:853)
[4] RasterizerStorageGLES2::_update_material(RasterizerStorageGLES2::Material*) (/media/veracrypt10/godot/drivers/gles2/rasterizer_storage_gles2.cpp:1640 (discriminator 2))
[5] RasterizerStorageGLES2::update_dirty_materials() (/media/veracrypt10/godot/drivers/gles2/rasterizer_storage_gles2.cpp:1713)
[6] RasterizerStorageGLES2::update_dirty_resources() (/media/veracrypt10/godot/drivers/gles2/rasterizer_storage_gles2.cpp:5067)
[7] RasterizerGLES2::begin_frame(double) (/media/veracrypt10/godot/drivers/gles2/rasterizer_gles2.cpp:291)
[8] VisualServerRaster::draw(bool, double) (/media/veracrypt10/godot/servers/visual/visual_server_raster.cpp:104 (discriminator 2))
[9] VisualServerWrapMT::draw(bool, double) (/media/veracrypt10/godot/servers/visual/visual_server_wrap_mt.cpp:104)
[10] Main::iteration() (/media/veracrypt10/godot/main/main.cpp:1886)
[11] ProgressDialog::task_step(String const&, String const&, int, bool) (/media/veracrypt10/godot/editor/progress_dialog.cpp:224)
[12] EditorNode::progress_task_step(String const&, String const&, int, bool) (/media/veracrypt10/godot/editor/editor_node.cpp:3288)
[13] EditorProgress::step(String const&, int, bool) (/media/veracrypt10/godot/./editor/editor_node.h:810)
[14] ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*) (/media/veracrypt10/godot/editor/import/resource_importer_scene.cpp:1344 (discriminator 27))
[15] EditorFileSystem::_reimport_file(String const&) (/media/veracrypt10/godot/editor/editor_file_system.cpp:1573)
[16] EditorFileSystem::reimport_files(Vector<String> const&) (/media/veracrypt10/godot/editor/editor_file_system.cpp:1724 (discriminator 3))
[17] EditorFileSystem::_update_scan_actions() (/media/veracrypt10/godot/editor/editor_file_system.cpp:565)
[18] EditorFileSystem::_notification(int) (/media/veracrypt10/godot/editor/editor_file_system.cpp:1100)
[19] EditorFileSystem::_notificationv(int, bool) (/media/veracrypt10/godot/editor/editor_file_system.h:107 (discriminator 14))
[20] Object::notification(int, bool) (/media/veracrypt10/godot/core/object.cpp:957)
[21] SceneTree::_notify_group_pause(StringName const&, int) (/media/veracrypt10/godot/scene/main/scene_tree.cpp:969)
[22] SceneTree::idle(float) (/media/veracrypt10/godot/scene/main/scene_tree.cpp:518 (discriminator 3))
[23] Main::iteration() (/media/veracrypt10/godot/main/main.cpp:1877)
[24] OS_X11::run() (/media/veracrypt10/godot/platform/x11/os_x11.cpp:2975)
[25] /usr/bin/godot(main+0xdc) [0x1156933] (/media/veracrypt10/godot/platform/x11/godot_x11.cpp:56)
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fcefa721b97] (??:0)
[27] /usr/bin/godot(_start+0x2a) [0x115679a] (??:?)
```

**Comment by LinuxUserGD** [comment] 2019-02-04 12:42
Does this also happen with GLES3?

**Comment by QbieShay** [comment] 2019-02-08 22:49
Can't reproduce on my machine, but i get errors:

```
editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
 editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
 editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
 editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
 editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
 editor/collada/collada.cpp:2538 - Condition ' err != OK ' is true. returned: ERR_FILE_CORRUPT
 editor/import/editor_import_collada.cpp:1282 - Condition ' err ' is true. returned: err
 editor/import/editor_import_collada.cpp:1803 - Condition ' err != OK ' is true. returned: __null
 core/os/file_access.cpp:605 - Condition ' !f ' is true. Continuing..:
 core/io/resource_format_binary.cpp:1046 - Condition ' !f ' is true.
```

**Comment by QbieShay** [comment] 2019-02-09 11:03
Happens also when compiling with GCC.

https://gfycat.com/creativeunconscioushare

**Comment by qarmin** [comment] 2019-02-27 05:32
Today I have again this crash but now on Ubuntu 18.04 with GTX 970

**Comment by akien-mga** [comment] 2019-02-28 10:42
I just did an import of the TPS demo with GLES2 using a4b687bda and I didn't get any crash.
I also got a lot less errors than usual after recent changes by @reduz, so could you try again? It might be fixed now.

**Comment by akien-mga** [comment] 2019-02-28 11:10
BTW, it's surprising that the crash happens in Bullet code, when this demo is using the GodotPhysics backend. Or did you change it to Bullet?

**Comment by qarmin** [comment] 2019-02-28 13:49
No, I don't change engine to Bullet but probably I use it.

I remember that Godot Physics changed its name from "GodotPhysics - deprecated" to "GodotPhysics" so "GodotPhysics - deprecated" automatically use default physics engine.

I think that Godot should accept all names which begins with "GodotPhysics" or "Bullet", to recognize which engine use.

**Comment by akien-mga** [comment] 2019-02-28 13:56
> I remember that Godot Physics changed its name from "GodotPhysics - deprecated" to "GodotPhysics" so "GodotPhysics - deprecated" automatically use default physics engine

.Oh right... That explains why physics were so buggy lately. I just fixed that in the demo.

**Comment by clayjohn** [comment] 2020-01-10 06:17
Is this still reproducible? It seems as if it isn't.

**Comment by qarmin** [comment] 2020-01-10 07:27
Crash probably doesn't happens for now because tps-demo use now(by default) Godot Physics and since Godot disabled DEBUG flag in Bullet modute, errors are silenced and doesn't cause crash.

**Comment by KoBeWi** [comment] 2020-12-06 19:03
Doesn't crash for me either. I think it's fine to close this issue.

**Closed by KoBeWi** 2020-12-06 19:03 UTC
Labels: bug, crash, topic:rendering
