### ISSUE TITLE
FBX Importer only import bones

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#38416] opened 2020-05-02 14:17 UTC
**Godot version:**
v3.2.1.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
I was playing around with the FBX importer, so just tried to import a .fbx file into the project folder, when I opened the file scene, the model appears to have only the bones, without the mesh. If I select the AnimationPlayer node I can preview the animation properly, but if I select the Skeleton node, Godot will crash and several messages saying "Object was deleted while awaiting a callback" will be printed in the console window. I'm able to import the same model into Unity engine.

**Steps to reproduce:**
Open Godot, drag and drop the above fbx file, open its scene, try to select the Skeleton Node.

**Minimal reproduction project:**
FBX file: https://drive.google.com/open?id=16ZXXVXfy5pFg2SymXAizA96DxMHpfTSs
Project: https://drive.google.com/open?id=1bLg50KCLWVvRjEVn79u7m0DXC7CthVam

**Comment by ThakeeNathees** [comment] 2020-05-02 14:48
A workaround till it's fixed: import it(*.fbx) in blender and export it as *.fbx and then use it in godot.

**Comment by marmitoTH** [comment] 2020-05-02 14:54
It does fix the mesh issue, but I'm still unable to select the Skeleton node, same crash.

**Comment by smix8** [comment] 2020-05-03 22:31
In the project settings go to "Memory -> Limits -> Message Queue" and increase the "Max Size KB". That should prevent the crash issue with the skeleton node for now as the default value is set for toasters and those are no good for working with 3d skeletons.

Similar issue:
https://github.com/godotengine/godot/issues/35652
Current pull request for a proper fix with the skeleton node:
https://github.com/godotengine/godot/pull/36409

**Comment by fire** [comment] 2020-05-26 18:15
Closing as a duplicate of #35652. Thanks for your report.

**Comment by marmitoTH** [comment] 2020-05-26 18:21
> Closing as a duplicate of #35652. Thanks for your report.

It's not the same problem, the FBX importer is importing only the bones of the model that I mentioned. I thought the freezing was also related to this problem, but it wasn't. This other issue is only related to the freezing.

**Comment by fire** [comment] 2020-05-26 18:26
We are working on improved fbx support https://github.com/godotengine/godot/pull/38966 . It's still in the early stages.

**Comment by fire** [comment] 2020-05-26 18:36
Renaming the issue so it's clear that the main issue FBX import is only resulting in bones.

**Comment by akien-mga** [comment] 2022-04-06 22:29
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:29 UTC
Labels: bug, topic:import
