### ISSUE TITLE
Polygon 2D UV editor snap to grid not working correctly

### ISSUE THREAD

**Issue by Mikengy22** [godotengine/godot#96420] opened 2024-09-01 02:25 UTC
### Tested versions

v4.3.stable.mono

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Mobile)

### Issue description

The snap to grid option in the Polygon 2D UV editor doesn't make the points align to the grid and when Panning the image with middle click, the snap point changes.

### Steps to reproduce

-Add a Polygon2D
-Add a texture to the Polygon2D (can be anything)
-Open the UV editor from the toolbar
-Enable the Grid and Snap options in the top right corner
-Go to the Points tab
-Place points, they won't be aligned to the grid, and panning the camera will move the snapping point

### Minimal reproduction project (MRP)

N/A

**Comment by kleonc** [comment] 2024-09-01 07:24
Duplicate of #94385 (fixed by #95259, should get cherry-picked into 4.3.1).

**Closed by kleonc** 2024-09-01 07:24 UTC
