### ISSUE TITLE
Moving a lot of files cause editor crash

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28095] opened 2019-04-16 19:32 UTC
**Godot version:**
3.2 5823b5d

**OS/device including version:**
Linux Mint 19

**Issue description:**
When I move a lot of files from folder(or multiple folders) to another, then editor crash with this backtrace:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f85c97b5f20] (??:0)
[2] CowData<wchar_t>::size() const (/home/rafal/Pulpit/godot/./core/cowdata.h:127)
[3] String::size() const (/home/rafal/Pulpit/godot/./core/ustring.h:151)
[4] String::length() const (/home/rafal/Pulpit/godot/./core/ustring.h:194)
[5] String::operator==(String const&) const (/home/rafal/Pulpit/godot/core/ustring.cpp:201)
[6] StringName::StringName(String const&) (/home/rafal/Pulpit/godot/core/string_name.cpp:281 (discriminator 2))
[7] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (/home/rafal/Pulpit/godot/core/undo_redo.cpp:306 (discriminator 1))
[8] UndoRedo::redo() (/home/rafal/Pulpit/godot/core/undo_redo.cpp:338)
[9] UndoRedo::commit_action() (/home/rafal/Pulpit/godot/core/undo_redo.cpp:260)
[10] EditorNode::_scene_tab_changed(int) (/home/rafal/Pulpit/godot/editor/editor_node.cpp:4288 (discriminator 4))
[11] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[12] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:942 (discriminator 1))
[13] Object::emit_signal(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/core/object.cpp:1228 (discriminator 1))
[14] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/core/object.cpp:1285)
[15] Tabs::set_current_tab(int) (/home/rafal/Pulpit/godot/scene/gui/tabs.cpp:418 (discriminator 4))
[16] EditorNode::reload_scene(String const&) (/home/rafal/Pulpit/godot/editor/editor_node.cpp:4703)
[17] FileSystemDock::_update_dependencies_after_move(Map<String, String, Comparator<String>, DefaultAllocator> const&) const (/home/rafal/Pulpit/godot/editor/filesystem_dock.cpp:1144)
[18] FileSystemDock::_move_operation_confirm(String const&, bool) (/home/rafal/Pulpit/godot/editor/filesystem_dock.cpp:1370)
[19] FileSystemDock::_move_with_overwrite() (/home/rafal/Pulpit/godot/editor/filesystem_dock.cpp:1323)
[20] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:56 (discriminator 4))
[21] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:942 (discriminator 1))
[22] Object::emit_signal(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/core/object.cpp:1228 (discriminator 1))
[23] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/core/object.cpp:1285)
rafal@rafal-SATELLITE-L750:~$ [24] AcceptDialog::_ok_pressed() (/home/rafal/Pulpit/godot/scene/gui/dialogs.cpp:387 (discriminator 2))
[25] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:56 (discriminator 4))
[26] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:942 (discriminator 1))
[27] Object::emit_signal(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/core/object.cpp:1228 (discriminator 1))
[28] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/core/object.cpp:1285)
[29] BaseButton::_gui_input(Ref<InputEvent>) (/home/rafal/Pulpit/godot/scene/gui/base_button.cpp:139 (discriminator 2))
[30] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[31] Object::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/core/object.cpp:777 (discriminator 1))
[32] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/core/object.cpp:883)
[33] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:1537 (discriminator 2))
[34] Viewport::_gui_input_event(Ref<InputEvent>) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:1909 (discriminator 3))
[35] Viewport::input(Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:2688 (discriminator 2))
[36] Viewport::_vp_input(Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:1313)
[37] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[38] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:942 (discriminator 1))
[39] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/core/object.cpp:867)
[40] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:262)
[41] SceneTree::input_event(Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:418 (discriminator 6))
[42] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/rafal/Pulpit/godot/main/input_default.cpp:416)
[43] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/main/input_default.cpp:260)
[44] InputDefault::flush_accumulated_events() (/home/rafal/Pulpit/godot/main/input_default.cpp:680)
[45] OS_X11::process_xevents() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:2462)
[46] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3004)
[47] /usr/bin/godot(main+0xdc) [0x1323773] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[48] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f85c9798b97] (??:0)
[49] /usr/bin/godot(_start+0x2a) [0x13235da] (??:?)
```
**Minimal reproduction project:**
TPS Demo

**Comment by MunWolf** [comment] 2019-04-16 20:01
Probably duplicate of #28069

**Comment by akien-mga** [comment] 2019-04-17 07:51
Duplicate of #26394 and/or #28012.

**Closed by akien-mga** 2019-04-17 07:51 UTC
Labels: bug, topic:editor
