### ISSUE TITLE
Empty Plugins List Partially Breaks the Editor

### ISSUE THREAD

**Issue by CheesecakeCG** [godotengine/godot#27882] opened 2019-04-10 04:22 UTC
**Godot version:** 3.1 Stable, but the issue started sometime during the Beta or Alpha of 3.1.

**OS/device including version:**
Pop!_OS 18.04
Dell Optiplex 990
i3-2100, RX460

**Issue description:**
Code complete box does not open, but completion is possible.
BlendTree's nodes can't be connected.
Many spinner box's numbers are hidden.

**Steps to reproduce:**
I think I deleted an editor plugin without disabling it. Leaving this in the project.godot
```GAP
[editor_plugins]

enabled=PoolStringArray(  )
```
Removing it fixes the issue.

**Comment by Calinou** [comment] 2020-08-18 14:19
I can't reproduce this on 3.2.2, closing.

**Closed by Calinou** 2020-08-18 14:19 UTC
Labels: bug, topic:editor
