### ISSUE TITLE
Defect in the editor's texts

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#36712] opened 2020-03-01 19:50 UTC
**Godot version:**
3.2.1 rc1 mono

**OS/device including version:**
win10 64

**Issue description:**
In the example project when you scroll down the text is displayed poorly.

**Steps to reproduce:**
Open the "spritePadre.tscn" scene.
Select the node "RichTextLabel"
Scroll with the mouse wheel as shown in the GIF

![GIF](https://user-images.githubusercontent.com/19652075/75632619-33f90500-5bfe-11ea-91f2-3264a372a191.gif)

**Minimal reproduction project:**
[testRichText.zip](https://github.com/godotengine/godot/files/4272331/testRichText.zip)

**Comment by clayjohn** [comment] 2020-03-01 19:55
Duplicate of https://github.com/godotengine/godot/issues/36087

Thanks for opening an issue. But please search existing issues before opening a new one.

**Closed by clayjohn** 2020-03-01 19:55 UTC
