### ISSUE TITLE
Godot 3.2 RC1 hangs the system

### ISSUE THREAD

**Issue by katoneko** [godotengine/godot#35251] opened 2020-01-17 20:38 UTC
**Godot version:**
3.2 RC1

**OS/device including version:**
Windows 10 Pro 64-bit
NVIDIA GeForce GT 220
Driver ver: 21.21.13.4201

**Issue description:**
Launching Godot RC1 opens the project manager as expected but it freezes trying to load up a selected project and, after a couple of seconds, the screen goes black and then the system remains in a half-frozen state where it responds to input, albeit it severely lags behind. The only option then is rebooting. It did display an error once when the screen didn't black out:
![уууу](https://user-images.githubusercontent.com/48890128/72644114-0af41c00-3992-11ea-8733-b46967ea8e6d.PNG)

The 3.1 version worked well both with GLES 2 and 3.

~~The GPU drivers seem to be up-to-date, but I'll try updating them and get back in a couple of minutes.~~
The drivers are of the latest version.

**Steps to reproduce:**
Launch Godot 3.2 RC1, select a project, get the black screen.

**Comment by clayjohn** [comment] 2020-01-17 20:46
May be related to https://github.com/godotengine/godot/issues/35242#issuecomment-575744258

**Comment by katoneko** [comment] 2020-01-17 20:57
Yeah, should've done that prior. Tried beta6 and it works there, no hanging.

**Comment by clayjohn** [comment] 2020-01-17 21:08
Can you try launching the game/editor in GLES2 with ``./Godot_v3.2-rc1_win64.exe --video-driver GLES2``?

**Comment by katoneko** [comment] 2020-01-17 21:24
Tried with GLES2, didn't change anything.

**Comment by clayjohn** [comment] 2020-01-17 21:38
Could you try out the builds in this comment and let me know if either works? https://github.com/godotengine/godot/issues/35242#issuecomment-575780552

They are built from varying places between beta6 and rc1.

**Comment by katoneko** [comment] 2020-01-17 22:06
@clayjohn tried 0.50 and 0.25, both are bad. Guess I might need to start `bisect`ing too.

**Comment by clayjohn** [comment] 2020-01-17 22:07
If you can, that would be extremely helpful.

**Comment by katoneko** [comment] 2020-01-17 22:25
I've never compiled anything this big, but I'll try tomorrow. Thanks for the guidance!

**Comment by Berkru** [comment] 2020-01-17 22:29
Don't Know if is correlated, but it is hanging Ubuntu 19.10 too. #35257

**Comment by akien-mga** [comment] 2020-01-18 10:39
Closing as duplicate of #35242, tests show that it seems to be the same issue.

**Closed by akien-mga** 2020-01-18 10:39 UTC
Labels: bug, regression, topic:rendering
