### ISSUE TITLE
Android version unable to add multiple nodes

### ISSUE THREAD

**Issue by marcelovbcfilho** [godotengine/godot#64627] opened 2022-08-19 16:12 UTC
### Godot version

3.5.stable

### System information

Android 12, GLES3, Snapdragon 750G, Galaxy Tab S7 FE

### Issue description

After creating a new empty project, creating a 2d scene and adding more than one node the app just crashes and became unresponsive.

After restarting the project the resources folder becames empty as if the godot configuration became missing.

The same issue also happened on my Poco F3 with android 12 and Snapdragon 870.

Obs: In the images you can see a video player control, this is because I recorded the error, but the file is too large for github issues (40mb) if you ask I can upload it on youtube and send the link here.

Image 1: Creating an empty project

![Screenshot_20220819-130506_Video Player](https://user-images.githubusercontent.com/51462138/185660955-61f069c8-2647-4b8f-b169-35571649df13.jpg)

Image 2:The editor crashing after adding the thrid node

![Screenshot_20220819-130608_Video Player](https://user-images.githubusercontent.com/51462138/185661018-61d058f9-ac43-4a44-865f-d48c1ee41b31.jpg)

Image 3: Re-opening the project and the resources not showing my scene and nothing else, even the godot icon became missing

![Screenshot_20220819-130632_Video Player](https://user-images.githubusercontent.com/51462138/185661203-1303af36-c825-423c-a053-b55a1bf7658e.jpg)

### Steps to reproduce

1 - Download the official apk available on github releases
2 - Installing the apk
3 - Open godot
4 - Create a empty project
5 - Create a 2d scene
6 - Add 2 nodes (can be anyone, not related to specific node)

### Minimal reproduction project

Due to the problem being with an empty project I will just zip the crashed project.

[Test android.zip](https://github.com/godotengine/godot/files/9383535/Test.android.zip)

**Comment by Calinou** [comment] 2022-08-19 16:33
Duplicate of https://github.com/godotengine/godot/issues/64166.

**Closed by Calinou** 2022-08-19 16:33 UTC
