### ISSUE TITLE
How to disable the internal text editor?

### ISSUE THREAD

**Issue by Giresharu** [godotengine/godot#7213] opened 2016-11-30 16:05 UTC
Godot version:2.1.1

I set the external editor to sublime3,but when I edit a script,both the sublime3 and internal editor pop up.

How can I disable the internal editor?

**Comment by manokara** [comment] 2016-12-01 16:14
Actually, my bad, this issue was fixed in master by the lines I linked before, from PR [#6962](https://github.com/godotengine/godot/pull/6962). The bug is only present in 2.1.1 stable, and is a duplicate of [#3046](https://github.com/godotengine/godot/issues/3046). 

Could that PR be backported to 2.1.1 maybe?

**Comment by bojidar-bg** [comment] 2016-12-02 09:45
Ok... marking as dupe of #3046.

**Closed by bojidar-bg** 2016-12-02 09:45 UTC
Labels: bug, topic:editor, usability
