### ISSUE TITLE
Empty window at plugin load error

### ISSUE THREAD

**Issue by Teashrock** [godotengine/godot#30063] opened 2019-06-25 10:22 UTC
**Godot version:**
3.1.1 stable official x64

**OS/device including version:**
Windows 10 1709 x64

**Issue description:**
Attempted to activate plugin with some error, and got empty warning window.
<img src="https://i.imgur.com/jQTtdJU.png" />

**Steps to reproduce:**
1. Place any kind of error to a plugin main file.
2. Go to Project Settings -> Plugins.
3. Try to activate plugin.
4. See empty window with warning and no text,

**Minimal reproduction project:**
http://www.mediafire.com/file/o0qjswb0r074zik/PluginAutoload.zip/file

**Comment by expat1999** [comment] 2019-06-26 00:54
I attempted to recreate this using the minimum reproduction project provided and could not.

**Godot version:**
3.1.1 stable official x64

**OS/device including version:**
Windows 10 1803 x64

**Comment by siddharth952** [comment] 2019-07-07 05:49
@Teashrock Are you still having the issue mentioned?

**Comment by Teashrock** [comment] 2019-07-07 09:16
@expat1999 
No bug? Screenshot, please.

@siddharth952 
Sorry, didn't saw an update here.

**Comment by Calinou** [comment] 2019-07-07 12:28
@Teashrock Does this occur if you set the editor language to English? Perhaps this is due to a bug in the translation.

**Comment by Teashrock** [comment] 2019-07-08 07:07
@Calinou 
I'll try.

**Comment by hbina** [comment] 2019-07-09 04:12
The problem is likely due to the fact that there is a whitespace between '%' and 's' in the Russian translation.

https://github.com/godotengine/godot/blob/56269e2db835e50a4cf2681bb73c44ae41fcca10/editor/translations/ru.po#L2426

**Comment by akien-mga** [comment] 2019-07-09 10:56
Fixed by #30450.

**Closed by akien-mga** 2019-07-09 10:56 UTC
Labels: bug, junior job, topic:editor
