### ISSUE TITLE
`focus_mode` reset when duplicating Button (3.x)

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#65220] opened 2022-09-01 22:26 UTC
### Godot version

3.5.stable

### System information

ArchLinux

### Issue description

When duplicating a Button with custom "focus_mode" set in inspector, the new Button has it set to a default value of "All".

### Steps to reproduce

1. Create a Button node in the editor
2. Set "focus_mode" to "None" or "Click"
3. Duplicate the button using Ctrl+D
4. Observe the new Button having its "focus_mode" set to a default value of "All"

This also happens when duplicating a Button via GDScript. It must be some sort of a small oversight internally. Yeah, I know "duplicate" is considered buggy... But it is a feature that's used a lot in the editor.

Interestingly, this does not happen when duplicating a Control node.

**Comment by Calinou** [comment] 2022-09-01 23:19
Duplicate of https://github.com/godotengine/godot/issues/57009.

**Closed by Calinou** 2022-09-01 23:19 UTC

**Comment by and3rson** [comment] 2022-09-02 10:06
@Calinou Thanks! My bad - I've tried searching but it totally flew under my radar.
