### ISSUE TITLE
SpotLights with shadows enabled cause artifacts to appear in the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#12030] opened 2017-10-11 15:50 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):** Windows 10, Godot Git https://github.com/godotengine/godot/commit/409e58e67abde4e7af6e43b32c23338e119377fb, NVIDIA

SpotLights with shadows enabled cause artifacts to appear in the editor. This doesn't seem to occur in running projects, though. Also, SpotLights with very wide angles (over 90°) will look completely broken with shadows enabled, but they will look fine with shadows disabled. Tweaking the shadow bias doesn't seem to have any effect on these artifacts.

**Narrow SpotLight with shadows (broken):**

![spotlight_narrow_broken](https://user-images.githubusercontent.com/180032/31451275-f9e702b0-aeab-11e7-98ab-37ac1b29ff94.png)

**Wide SpotLight with shadows (broken):**

![spotlight_wide_broken](https://user-images.githubusercontent.com/180032/31451280-fa53e4fc-aeab-11e7-85f8-5e08f0cf7058.png)

**Ultrawide SpotLight with shadows (broken):**

![spotlight_over_90_broken](https://user-images.githubusercontent.com/180032/31451277-fa07e6a6-aeab-11e7-9c59-ac856b686bdc.png)

**Ultrawide SpotLight without shadows (working):**

![spotlight_over_90_working](https://user-images.githubusercontent.com/180032/31451278-fa2d900e-aeab-11e7-8df1-0e362f4ae4e6.png)

**SpotLight in running project (working):**

![spotlight_in_game](https://user-images.githubusercontent.com/180032/31451273-f9c5ae3a-aeab-11e7-98cb-d59f46559205.png)

**Comment by reduz** [comment] 2017-10-11 16:15
Spotlights should not work with angles over 90 degrees... that's probably
the bug.
If so, they are not expected to work with shadow mapping.

**Comment by groud** [comment] 2017-10-11 16:18
Duplicate of #12028. ^^

**Closed by groud** 2017-10-11 16:18 UTC
