### ISSUE TITLE
Label3D alignment does not appear to be accurate

### ISSUE THREAD

**Issue by RichMakeGame** [godotengine/godot#89137] opened 2024-03-04 11:51 UTC
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz (8 Threads)

### Issue description

I'm using label3D and need to use top/left alignment and have consistent placement when the font size changes, however the Left / Top alignment does not keep the top/left of the text plane in a consistent position. Similar issue is present with Right/Bottom. At default settings and font size of ~286 the text drifts -0.5 units in y

all these label3D items have the same transform, top/left alignment, just different font size:
![label3d_align](https://github.com/godotengine/godot/assets/97259185/1a15c612-33b2-40db-b4d2-450b2be987ee)

### Steps to reproduce

Add a label3d to a 3d project, write some text eg 'Test text'
set alignment to Left and Top, and snap view to front orthogonal
alter font size from 1 up to 350 and notice the alignment starts above left of the origin and strays right and quite far below

a similar problem occurs if set to Right and Bottom alignment

### Minimal reproduction project (MRP)

[3dlabel_align_issue.zip](https://github.com/godotengine/godot/files/14480977/3dlabel_align_issue.zip)

**Comment by akien-mga** [comment] 2024-03-04 11:56
CC @bruvzg

**Comment by bruvzg** [comment] 2024-03-04 12:50
I do not think it's bug and not Label3D specific (the only Label3D specific part, it's showing bounding box of the visible part). The left edge of the T top line is not a left edge of the glyph, and text is aligned to the glyph edge (other apps do the same):

<img width="673" alt="Screenshot 2024-03-04 at 14 46 03" src="https://github.com/godotengine/godot/assets/7645683/f4807267-ff9b-4134-8988-35fca20a0169">

**Comment by RichMakeGame** [comment] 2024-03-04 14:25
Ahaa ok I see, so it is actually scaling correctly its just I was confused by the bounding box?

**Comment by akien-mga** [comment] 2024-03-05 09:06
Closing as this was apparently not a bug, but not #89145 should fix the bounding box to make it clearer.

**Closed by akien-mga** 2024-03-05 09:06 UTC
Labels: bug, topic:gui, topic:3d
