### ISSUE TITLE
Android apps installed with "Small Deploy" enabled will freeze when re-started after the editor connection was stopped

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#33900] opened 2019-11-25 22:35 UTC
**Godot version:**
Known broken:
Godot_v3.1.1-stable_x11.64
Godot_v3.2-beta1_x11.64
Godot Engine v3.2.beta
e297b83b8e7c335c4ccf96b7bacd42f3cc7e52c8

**OS/device including version:**
Linux

**Steps to reproduce:**
* Install an Android app via the editor button, with **Debug → Small Deploy with Network FS** enabled.
* Close (kill) the Android app and the Godot editor.
* Start the app in the Android UI again.
The app freezes (black screen).

It is independent of the OpenGL version.
Installation and remote USB debugging works as expected (until you exit the Godot editor).

The app hangs when trying to connect to the now non-existent reverse adb port.
Related adb logcat output:
```
11-25 22:44:48.862 24522 24545 E godot   : **ERROR**: Socket error: 111
11-25 22:44:48.862 24522 24545 E godot   :    At: drivers/unix/net_socket_posix.cpp:211:_get_socket_error() - Socket error: 111
11-25 22:44:48.862 24522 24545 E godot   : **ERROR**: Connection to remote host failed!
11-25 22:44:48.862 24522 24545 E godot   :    At: drivers/unix/net_socket_posix.cpp:429:connect_to_host() - Connection to remote host failed!
11-25 22:44:48.862 24522 24545 E godot   : Could not connect to remotefs: localhost:6010.
...
11-25 22:44:50.497  3588  3620 W WindowManager: Window freeze timeout expired.
11-25 22:44:50.497  3588  3620 W WindowManager: Force clearing orientation change: Window{96e3d36 u0 Splash Screen org.godotengine.xxxx}
11-25 22:44:50.498  3588  3620 W WindowManager: Force clearing orientation change: Window{fb8dd7d u0 org.godotengine.xxx/com.godot.game.GodotApp}
11-25 22:44:50.647  3588  3620 W WindowManager: App freeze timeout expired.
11-25 22:44:50.647  3588  3620 W WindowManager: Force clearing freeze: AppWindowToken{85ab437 token=Token{4af7c3f ActivityRecord{848805e u0 org.godotengine.xxx/com.godot.game.GodotApp t439}}}
11-25 22:44:50.654  3588  3620 I WindowManager: Screen frozen for +2s158ms due to Window{96e3d36 u0 Splash Screen org.godotengine.xxx}
11-25 22:44:50.669   430   430 D SurfaceFlinger: duplicate layer name: changing BlackSurface to BlackSurface#1
11-25 22:44:52.910  3588  3620 I zygote64: Explicit concurrent copying GC freed 28977(1718KB) AllocSpace objects, 5(244KB) LOS objects, 42% free, 18MB/31MB, paused 445us total 235.539ms
11-25 22:44:58.490  3588  3610 W ActivityManager: Launch timeout has expired, giving up wake lock!
```

**Comment by akien-mga** [comment] 2020-10-01 09:46
Is this still reproducible with 3.2.3-stable or later? Is it reproducible with any app (e.g. default project with simple "Node" main scene), or a specific one?

**Comment by capnm** [comment] 2020-10-01 17:25
> Is it reproducible with any app (e.g. default project with simple "Node" main scene), or a specific one?

Or a Button, Yes
[small-deploy-i33900.zip](https://github.com/godotengine/godot/files/5313810/small-deploy-i33900.zip)

> Is this still reproducible with 3.2.3-stable or later? 

Notching changed, I can still reproduce the problem with 3.2.3-stable today
```
0-01 19:03:34.301 14900 14917 E godot   : Could not connect to remotefs: localhost:6010.

10-01 19:03:49.487  3586  3845 I InputDispatcher: Application is not responding: 
Window{dca3f74 u0 org.godotengine.testgodoti33900/com.godot.game.GodotApp}.  
It has been 5023.1ms since event, 5005.9ms since wait started.  
Reason: Waiting to send non-key event because the touched window has not finished processing 
certain input events that were delivered to it over 500.0ms ago.  
Wait queue length: 20.  Wait queue head age: 6070.6ms.

10-01 19:03:52.298  3586  3625 E ActivityManager: ANR in org.godotengine.testgodoti33900 
(org.godotengine.testgodoti33900/com.godot.game.GodotApp)

10-01 19:03:56.503  3586  4119 I WindowManager: WIN DEATH: Window{dca3f74 u0 
org.godotengine.testgodoti33900/com.godot.game.GodotApp}
```

**Comment by Faless** [comment] 2020-10-05 11:22
I'm not sure I fully understand the issue, so forgive me if I miss the point.
If you deploy with remote FS the app is exported without the resources which are instead fetched via network/adb and served by the editor. So when you close the editor, the file server is closed, and the app will no longer work (as expected).
The RemoteFS is meant to be used during development while you test features (run from the editor) frequently to speed up the process.

**Comment by capnm** [comment] 2020-10-05 12:11
> The RemoteFS is meant to be used during development while you test features (run from the editor) frequently to speed up the process.

Yes, but the deployed app stays in Android and probably shouldn't just freeze the UI and crash when you then launch it.

**Comment by akien-mga** [comment] 2020-10-05 12:24
Alright, I had misinterpreted the issue too as the title referred to "will freeze after launch", but it's after "re-launch when it's no longer connected".

So it's not a bug per se but I agree that it would be nice to find a way to either uninstall the remote deployed app (does `adb` enable that?), or possibly include some placeholder scene that would show an error instead of crashing? CC @m4gr3d

**Comment by capnm** [comment] 2020-10-05 12:44
> either uninstall the remote deployed app (does adb enable that?)

adb uninstall `<app package name>`

> or possibly include some placeholder scene that would show an error instead of crashing?

I think that would be easier to implement and would also work if the Godot editor unexpectedly crashes;)

**Comment by Faless** [comment] 2020-10-05 14:12
> I think that would be easier to implement and would also work if the Godot editor unexpectedly crashes;)

This is really not possible, given the files are served by the editor (which is the whole point of that debug option).
If you don't want that, do not deploy with remote FS.

**Comment by m4gr3d** [comment] 2020-10-05 22:10
I don't think the `adb` approach would work as it would imply preventing the editor from closing until the command is done running which seems ill-advised.

Instead of having a placeholder scene, the app could ping for the Godot editor and throw an error message if it's unavailable, although, I'm not familiar enough with the remote FS implementation, so I'd take @Faless's words on the matter.

**Comment by capnm** [comment] 2020-10-06 01:23
git grep 'Could not connect to remotefs'
main/main.cpp:881:                      OS::get_singleton()->printerr("Could not connect to remotefs: %s:%i.\n", remotefs.utf8().get_data(), port);

```c
Error err = file_access_network_client->connect(remotefs, port, remotefs_pass);
if (err) {
           OS::get_singleton()->printerr("Could not connect to remotefs: %s:%i.\n",
                remotefs.utf8().get_data(), port);
           goto error;
}
```


Is there a way to exit Android app and let it display a popup with some label and [Exit] button?

**Comment by m4gr3d** [comment] 2023-05-30 01:00
> Alright, I had misinterpreted the issue too as the title referred to "will freeze after launch", but it's after "re-launch when it's no longer connected".
> 
> So it's not a bug per se but I agree that it would be nice to find a way to either uninstall the remote deployed app (does `adb` enable that?), or possibly include some placeholder scene that would show an error instead of crashing? CC @m4gr3d

This issue is fixed in Godot 4.x, as the remote fs was rewritten on Android to sync the project files to the device, allowing the installed apk to continue accessing them.

Fixed by https://github.com/godotengine/godot/pull/76540

**Closed by m4gr3d** 2023-05-30 01:00 UTC
Labels: enhancement, platform:android, topic:editor, topic:porting, confirmed
