### ISSUE TITLE
Viewports+Camera3Ds in ViewportContainers not rendering in the 2D editor

### ISSUE THREAD

**Issue by esijg** [godotengine/godot#19638] opened 2018-06-18 22:39 UTC
**Godot version:**
Godot 3.0.3

**OS/device including version:**
Ubuntu 18.04 64bit on AMD Cayman (HD 6950) and Mesa 18.0.0-rc5.
Intel® Core™ i5-4570 CPU @ 3.20GHz × 4 

**Issue description:**
Some viewports+cameras in viewport containers don't seem to render in editor (even though they render ingame). Duplicating viewport containers along with the viewport and camera will result in the duplicate to render correctly but the first one still does not render. Restarting Godot and reopening the project will result in the old viewports to render correctly but any new ones will have the same problem.

![funkyviewports](https://user-images.githubusercontent.com/2924543/41565730-8566fac4-7347-11e8-94e1-6e98b8fa5192.png)

**Steps to reproduce:**

1. Create new scene with spatial node as root
2. Add Viewport container + Viewport + Camera.
3. Set size of Viewport to anything, 500x500 will do fine.
4. Look into 2D view and see how the viewport is invisible in editor.
5. Duplicate Viewport Container along with its children and see how the duplicate renders correctly in 2D view.
6. Play the scene and see how both viewports render correctly ingame.
7. Restart Godot and reopen the project/scene and see both viewports rendering correctly in editor
8. Do steps 2 to 4 again and see how the new viewport does not render correctly in editor also.

**Comment by clayjohn** [comment] 2020-06-08 04:31
@Calinou I think this sort of bug was the reason we started asking people to set viewports as local to scene.

**Comment by johannesgunnar** [comment] 2020-06-08 13:30
A minimal reproduction project doesn't really help given the fact that this bug disappears the moment you load the project. (see step 7 above)

I have tested this in 3.2.1 and 3.2.2beta4. This bug is present in both versions.

**Comment by Rindbee** [comment] 2023-05-22 23:34
Seems to be fixed in v3.5.2.stable.official [170ba337a] and v4.0.stable.official [92bee43ad].

**Closed** 2023-05-23 07:55 UTC
Labels: bug, topic:editor, confirmed, topic:3d
