### ISSUE TITLE
Inspector does't update selection when moving in Scene Dock by arrows

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22397] opened 2018-09-24 11:21 UTC
**Godot version:**
3.1  399910d

**OS/device including version:**
Windows 10

**Issue description:**
When I try move in Scene Dock by up and dow arrows, current node is changing in Inspector but still in Scene dock is selected wrong node

**Steps to reproduce:**
https://streamable.com/n963h

**Comment by qarmin** [comment] 2018-09-24 18:29
Changing node in Scene Dock works fine with Ubuntu, so seems to be only Windows issue

**Comment by KoBeWi** [comment] 2019-10-15 15:16
This is how it works in 3.2
![sPpcCVTbER](https://user-images.githubusercontent.com/2223172/66844905-6cf64d00-ef6f-11e9-9e1c-12e175aba5f6.gif)

Elements are correctly focused, but only nodes with transform get selected.

**Comment by Leleat** [comment] 2020-09-08 10:38
> Elements are correctly focused, but only nodes with transform get selected.

I checked the get_selected() items of the SceneTreeDock because I noticed this weird behaviour as well. And 2 nodes get selected simultaneously if you try to select some nodes with your arrow keys (in your example `AnotherOne` and `Tween` would get selected at the same time if you move the selection with arrow keys from the top to the bottom).  

I don't think this selection issue might be related to a Transform property. Control nodes can get selected properly with arrow keys. Spatial nodes can't. Maybe everything inheriting from CanvasItem can be selected... I don't know.

One issues which is caused by this behaviour is that you can't 'properly' remove Scripts from non-CanvasItem(?) Nodes with just your keyboard. For example: if `Tween` in KoBeWi's gif had a script attached to it and I'd try to move to it (from the top to the bottom) with the arrow keys, `AnotherOne` and `Tween` would be selected. The Add-Script button would be visible for `Tween` instead of the Dettach-Script button. It appears that the Add/Dettach-Script button looks at the other CanvasItem Node to decide what button is visible. Weirdly though, the Add-Node button would properly add a child node to `Tween`.

There is a second issue when a CanvasItem and a non-CanvasItem node have scripts attached to them and you try to navigate to the non-CanvasItem node and dettach the script. Instead of dettaching from the non-CanvasItem node the script from the CanvasItem node is dettached.

In case I didn't explain it properly, here is a minimal project. Try to navigate to the `Tween` node and use the attach/dettach script button. You should navigate from the top once and from the bottom once to understand what I mean.

[New Game Project.zip](https://github.com/godotengine/godot/files/5187753/New.Game.Project.zip)

**Comment by KoBeWi** [comment] 2022-01-03 11:25
Closing as duplicate of #12544

**Closed by KoBeWi** 2022-01-03 11:25 UTC
Labels: enhancement, topic:editor, usability
