### ISSUE TITLE
drivers/gles3/rasterizer_gles3.cpp:176 - GL ERROR

### ISSUE THREAD

**Issue by joined72** [godotengine/godot#86449] opened 2023-12-22 17:15 UTC
### Tested versions

4.2.1 stable

### System information

Ubuntu 22.04 - AMD Ryzen 5 - Nvidia 750 Ti - 16 GB RAM - 512 SDD NVME - XFCE 4.18

### Issue description

Opening the simple attached Test Project in the Editor, in the Output window will appears the following error message:

`drivers/gles3/rasterizer_gles3.cpp:176 - GL ERROR: Source: OpenGL	Type: Undefined behavior	ID: 131222	Severity: Medium	Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons enabled, with a texture object (1018) with a depth format, by a shader that samples it with a non-shadow sampler. Using this state to sample would result in undefined behavior`

### Steps to reproduce

See the previous topic.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/13754631/test.zip)

**Comment by bitsawer** [comment] 2023-12-22 17:19
Thanks for the report. Seems like a duplicate of https://github.com/godotengine/godot/issues/84558, so closing this to keep discussion in one place.

**Closed by bitsawer** 2023-12-22 17:19 UTC
Labels: topic:rendering, needs testing

**Comment by joined72** [comment] 2023-12-22 17:20
> Thanks for the report. Seems like a duplicate of #84558, so closing this to keep discussion in one place.

But here there is a Minimal Reproducible Project, can I suggest to use it?
