### ISSUE TITLE
Global level preload/load tscn causes runtime error when instantiated from a thread

### ISSUE THREAD

**Issue by someThrowAway1900** [godotengine/godot#86049] opened 2023-12-11 23:12 UTC
### Tested versions

v4.2.1.rc1
v4.2

### System information

Windows 10

### Issue description

NOTE - I do not know if this is by design or if it is an error. Reporting for capture.

Global level preload/load tscn causes runtime error when instantiated from a thread. This is the error:

```
E 0:00:00:0755   threadTEST.gd:18 @ threadRun(): This function in this node (CollisionShape3D) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  <C++ Error>    Condition "!is_readable_from_caller_thread()" is true. Returning: (Transform3D())
  <C++ Source>   scene/3d/node_3d.cpp:333 @ get_transform()
  <Stack Trace>  threadTEST.gd:18 @ threadRun()
```

### Steps to reproduce

- Open the attached project
- Run project (there is no error)
- Uncomment line 6 (#var persisent: Resource = preload("res://someScene.tscn") # global causes thread issue)
- Run project (error shown)

### Minimal reproduction project (MRP)

[threadTEST.zip](https://github.com/godotengine/godot/files/13641832/threadTEST.zip)

**Comment by AThousandShips** [comment] 2023-12-12 14:52
Duplicate of https://github.com/godotengine/godot/issues/79194

**Closed by AThousandShips** 2023-12-12 14:52 UTC
Labels: discussion, topic:core
