### ISSUE TITLE
Screen flickering/artifacting 

### ISSUE THREAD

**Issue by connercms** [godotengine/godot#56134] opened 2021-12-21 16:58 UTC
### Godot version

3.4.1

### System information

MacOS Monterrey, Apple MacBook Air M1, GLES3

### Issue description

I downloaded Godot (through Steam) and have been following along with the tutorials. I recently began experiencing an issue where the screen is flickering / artifacting (not sure what to call it exactly) and making it very hard to focus on the task at hand. It happens more when performing some actions (like browsing drop down menus in the title bar) than others, but also happens when just panning my cursor across the screen. It happens in both windowed and full screen. 

https://user-images.githubusercontent.com/12799522/146968612-426954ab-92b2-4110-8c99-30f10c393094.mov

### Steps to reproduce

Not sure the steps to reproduce as it seemed to start happening randomly but will include zip of the project.

### Minimal reproduction project

[build.zip](https://github.com/godotengine/godot/files/7756881/build.zip)

**Comment by Calinou** [comment] 2021-12-21 17:02
Duplicate of https://github.com/godotengine/godot/issues/56055.

**Closed by Calinou** 2021-12-21 17:02 UTC
