### ISSUE TITLE
Custom node icon is oversized in inspector

### ISSUE THREAD

**Issue by DricomDragon** [godotengine/godot#75845] opened 2023-04-09 07:55 UTC
### Godot version

4.0.2.stable

### System information

Ubuntu 20.04.6 LTS (i3wm), OpenGL API 4.6 (Core Profile) Mesa 21.2.6 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics 620 (KBL GT2)

### Issue description

When using a custom SVG icon for a Node that's exporting a variable, the custom icon is not scaled properly in the editor inspector.

```gdscript
@icon("res://icon.svg")
class_name CustomNode
extends Node2D
@export var exp_var: String = "Hello"
```

![editor-oversized-custom-icon-inspect](https://user-images.githubusercontent.com/31211344/230760378-53695a99-2e2a-4cc4-9925-e3609121a031.png)

Does not depend on rendering backend (reproduced with Forward+ and Compatibility).

### Steps to reproduce

1. Create a script exporting a custom SVG icon and exporting at least one variable
2. Restart the editor to apply custom icon
3. Open the inspector on a instantiated custom node
4. Look at the icon in the inspector

### Minimal reproduction project

[BugReport_EditorOversizedCustomIcon.zip](https://github.com/godotengine/godot/files/11185014/BugReport_EditorOversizedCustomIcon.zip)

**Comment by KoBeWi** [comment] 2023-04-09 09:48
Duplicate of #57286
The issue is fixed in 4.1-dev, but the fix might be cherry-picked to 4.0.3.

**Closed by KoBeWi** 2023-04-09 09:48 UTC
