### ISSUE TITLE
My computers crashing whenever I turn on Godot

### ISSUE THREAD

**Issue by literallynickk** [godotengine/godot#43308] opened 2020-11-04 10:05 UTC
So, I decided that Godot seems like a cool engine and I wanna start using it, but whenever I try to turn on a project in the editor, my monitor goes black and shows "No Signal" and I can't even turn Godot off with ALT+F4, pc does not respond to anything and I need to restart the PC.
What do I do cuz I legit wanna use this engine
here is my PC specs:
Intel(R) Core(TM) i7 CPU 870 @
8 GB RAM
64-bit
NVIDIA GeForce 210

**Comment by Calinou** [comment] 2020-11-04 10:10
Duplicate of https://github.com/godotengine/godot/issues/37105. Try switching to the GLES2 renderer.

**Closed by Calinou** 2020-11-04 10:10 UTC
