### ISSUE TITLE
File dialog gets stuck on the path of the first selected preset in export dialog

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#31427] opened 2019-08-17 03:32 UTC
**Godot version:**
afecc0b

**Issue description:**
On the "Export" dialog, the first selected preset's export path will always be the one showing in the file dialog when exporting a project, while selecting others unable to change it.

From the testing I did, the problem seems to be with the `EditorFileDialog` itself, as the select paths are sent to it, but it fails to acknowledge them. Here's the line if anyone want to try their luck:
https://github.com/godotengine/godot/blob/afecc0bc2283dfbfbce70ae95c28e0ed4ecd4160/editor/project_export.cpp#L944

**Comment by aole** [comment] 2019-08-29 04:41
I Cannot reproduce this on the latest master ...

![test](https://user-images.githubusercontent.com/4707543/63910665-a55cbe80-c9f5-11e9-9cdc-f75c4bf9760b.gif)

**Comment by YeldhamDev** [comment] 2019-08-29 04:44
It happens in the file dialog, not in the export dialog.

**Comment by akien-mga** [comment] 2019-08-30 07:31
CC @SonerSound

**Comment by SonerSound** [comment] 2019-08-30 08:10
Will work on it this weekend starting today. Thanks for the catch!

**Comment by SonerSound** [comment] 2019-08-30 15:25
@YeldhamDev I'm having trouble either reproducing or understanding the issue. Do you mean that when both paths are set, and when pressing the path button, the path thats default is not the one from the currently selected export path?

**Comment by SonerSound** [comment] 2019-08-30 16:22
By the way, that line was reverted sometime ago. Is it possible thats fixed now?

**Comment by YeldhamDev** [comment] 2019-08-30 16:30
> I'm having trouble either reproducing or understanding the issue.

Consider that you have multiple export presets, and each one has a different export path.
The first time you click in "Export Preset", the file dialog will correctly set its path to export path of the preset, but it will make it get stuck in said path, so this in any other preset will always show that first path.

> By the way, that line was reverted sometime ago.

The commit that commented that line out was closed.

**Comment by SonerSound** [comment] 2019-08-30 16:35
> The commit that commented that line out was closed.

I was talking about the commit that I made that reverted the line you transcribed in the your first post. That whole if block was reverted by my merge request. (#31586)

**Comment by YeldhamDev** [comment] 2019-08-30 16:45
The code in "editor/editor_export.cpp" is actually what's causing the bug.

**Closed** 2019-12-17 21:24 UTC
Labels: bug, topic:editor
