### ISSUE TITLE
Z order ignored for children of CollisionShape2D

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#12147] opened 2017-10-16 08:52 UTC
Godot 2.1.4, linux.

When a sprite is a child of a `CollisionShape2D`, it ignores `Z` and is on top of everything. It displays correctly in the editor but not when running the project.

See the attached project which replicates the incorrect behaviour. Edit it and reparent the Sprite to the RigidBody2D instead of the collision shape and it works correctly.
[zorder.tar.gz](https://github.com/godotengine/godot/files/1386746/zorder.tar.gz)

This is a pretty minor and inconsequential bug, so feel free to close this as "wontfix", but I thought it might be worth knowing about anyway.

**Comment by reduz** [comment] 2017-10-16 11:21
Ah this happens because shapes can be debugged while running the game, so
the arr always visible..

**Comment by akien-mga** [comment] 2018-01-15 10:58
Is this still reproducible in Godot 3.0 RC1?

**Comment by qarmin** [comment] 2018-11-01 10:39
In Godot 3.1 fbc0e5d changing Z order works correctly

**Comment by akien-mga** [comment] 2018-11-01 10:48
Thanks for testing! Marking as solved in 3.1 (though it might have been in 3.0 already).

**Closed by akien-mga** 2018-11-01 10:48 UTC
Labels: bug, topic:core
