### ISSUE TITLE
Behavior of Input event changed since Godot 3.3.2

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#57386] opened 2022-01-29 08:40 UTC
### Godot version

3.4.2-stable 3.5-beta1

### System information

Linux x11

### Issue description

Godot in options set to **Single-thread**.

Tested on exported template and editor (same behavior).

```
var events = 0

func _process(delta):
  print(events)
  events = 0

func _input(event):
  if(event is InputEventMouseMotion):
    events+=1
```

On Godot 3.3.2-stable this code always print 1

On Godot 3.4.2-stable and 3.5-beta1 this code print "many events".

Maybe Im missing something, I was expecting "whole application work in single thread". 

Only related change I remember (in one of stable updates) - is "fix for input" to make it separated from rendering frame... **this behavior expected and not_a_bug?**

This means I have to move old "input" to _process function, basically.

### Steps to reproduce

launch example code

**Comment by Calinou** [comment] 2022-01-29 16:29
Duplicate of https://github.com/godotengine/godot/issues/55037.

**Closed by Calinou** 2022-01-29 16:29 UTC
Labels: topic:input
