### ISSUE TITLE
Texture stretching

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#37935] opened 2020-04-16 13:05 UTC
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Android 4.4 ~~Samsung S3 Note~~ Samsung Galaxy Tab 3 8.0 SM-T311, GLES 2
**Issue description:**
In GLES 2 on a standard 3d-plane, the texture is stretched
**Steps to reproduce:**
Create a standard 3d-plane, standard material (I use unshaded), assign any texture (I used .png with standard export settings).

Editor (windows 10):
![editor](https://user-images.githubusercontent.com/10414783/79459357-81a6c100-8036-11ea-866a-983dcbf18137.PNG)
Android 4.4
![android](https://user-images.githubusercontent.com/10414783/79459372-85d2de80-8036-11ea-957d-5e73c6960320.png)

**Comment by Calinou** [comment] 2020-04-16 13:46
@DDru Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by DDru** [comment] 2020-04-16 22:09
@Calinou [bug proj.zip](https://github.com/godotengine/godot/files/4489951/bug.proj.zip)

**Comment by volzhs** [comment] 2020-04-16 22:40
This is how it looks on Galaxy S8+ / Android 9

![Screenshot_20200417-073850_Test1](https://user-images.githubusercontent.com/8281454/79513400-b2124d80-807e-11ea-9778-cbf33a903063.jpg)

**Comment by avril-gh** [comment] 2020-04-17 00:19
```
Android 4.4
GLES: ARM, Mali-450 MP, OpenGL ES 2.0
GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
EGL:
EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_framebuffer_target EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache
```
![Screenshot_2020-04-17-02-15-07](https://user-images.githubusercontent.com/3224132/79518643-e4f21c80-8051-11ea-9197-e8c766998dea.jpg)

**Comment by DDru** [comment] 2020-04-17 00:48
@avril-gh tested device has Mali-400 MP4 and Android: 4.4.2
Also i made mistake about device name. Correct name is Samsung Galaxy Tab 3 8.0 SM-T311

**Comment by avril-gh** [comment] 2020-04-17 12:34
@DDru 
Try to enable debug and see if there's anything '_interesting_' in log file

project settings - > debug -> settings -> verbose stdout - enable
project settings - > logging -> file logging -> enable file logging - enable
(_log path, is where your log will be on android device, by default its in data/data/yourappname/logs_)

also, my image is from latest **v3.2.2.rc**, would you like to try out on v3.2.2.rc perhaps ?

**Comment by DDru** [comment] 2020-04-17 14:05
@avril-gh 
> also, my image is from latest v3.2.2.rc, would you like to try out on v3.2.2.rc perhaps ?

in 3.2.2.rc.official no any changes

> Try to enable debug and see if there's anything 'interesting' in log file

I found logs only in editor. And they had some strange lines:
```
...
ADDING: res/mipmap/icon_background.png
ADDING: res/mipmap/icon_foreground.png
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: no space left
ADDING: resources.arsc
0 param: --xr_mode_regular
1 param: --use_depth_32
2 param: --use_immersive
Installing to device (please wait...): Samsung SM-T311
```
Project directory and path to Godot.exe has only latin-symbols.

**Comment by lawnjelly** [comment] 2020-04-18 11:29
Just a hunch, do you get the same problem with a power of 2 texture size? (i.e. 256x256, 512x512 etc)

**Comment by avril-gh** [comment] 2020-04-18 17:08
@DDru , @lawnjelly is very true, your texture is 340px. Try texture with something like x8 let it be **320x320**px. ( _and btw, what a smart debug idea with this UV, im impressed_ :smile: )

**Comment by DDru** [comment] 2020-04-19 02:58
@avril-gh, @lawnjelly no. At first I used the neighboring texture "checker.png", which is 1024x1024 size and I saw an error on it.
![Снимок](https://user-images.githubusercontent.com/10414783/79678317-6659d280-823d-11ea-82cf-880c8fcd799a.PNG)

**Comment by DDru** [comment] 2020-04-19 03:06
@lawnjelly, visualization UV-coordinates really shows error.
Editor:
![Снимок](https://user-images.githubusercontent.com/10414783/79678392-7d4cf480-823e-11ea-9b53-258fa09faad9.PNG)
Android:
![Screenshot_2020-04-19-13-03-33](https://user-images.githubusercontent.com/10414783/79678394-7faf4e80-823e-11ea-8508-108b4e8adb64.png)

**Comment by Calinou** [comment] 2020-04-19 09:14
This is because vertex shading is forced by default on mobile. You can disable it in the Project Settings.

**Comment by lawnjelly** [comment] 2020-04-19 12:30
I think even with vertex shading these should interpolate correctly (this is basic texture mapping).

From what I can see it looks like the vertex UVs are incorrect in the vertex shader. It would be helpful to see the glsl shaders (rather than uber shader) that are produced to get an idea of what might be causing a problem on this hardware. I'll print these here if I have time to look at the issue. (or @clayjohn)

**Comment by DDru** [comment] 2020-04-20 08:39
@lawnjelly, standart CubeMesh, and plane from Blender get bug too.
But on model from Blender it look different.
![Screenshot_2020-04-20-18-38-29](https://user-images.githubusercontent.com/10414783/79731913-4e19ae80-8336-11ea-89f0-4efa9f2ab1f2.png)

**Comment by lawnjelly** [comment] 2020-04-20 09:37
Hmm, thanks for the extra tests. Have to admit I can't immediately think of an easy way to pin this down remotely. There are a lot of possibilities. It might be one of those cases where one of the rendering team would need access to this hardware.

There's also no high precision available on the Mali 400 MP4 in the fragment shader if the UVs are touched, but I don't *think* this is fragment shader problem (the texture would presumably look more pixellated if it was).

It is very likely to be a hardware / driver bug or peculiarity, but we could also be doing something like godot accessing the wrong attribute location for the UVs.

**Comment by Calinou** [comment] 2022-01-07 17:40
@DDru Can you (or anyone else) still reproduce this bug in [Godot 3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) or any later release?

**Comment by Calinou** [comment] 2022-01-28 22:59
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2022-01-28 22:59 UTC
Labels: bug, platform:android, topic:rendering, topic:3d
