### ISSUE TITLE
export Arrays with type doesn't not work...

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#22974] opened 2018-10-13 01:22 UTC
**Godot version:**
I'm using version 3.1.alpha.calinou.4c1a5d9

**OS/device including version:**
MacOS

**Issue description:**
using export variables of array type results in a array of no specific type.

`export(Array, PackedScene) var scenes` in the editor I get an array that when adding entries they are all null and when I select the type I can select anything I want so what is the purpose of setting an array to be PackedScene...
the problem remains the same with other types too.
`export(Array, int) var my_ints`

<img width="206" alt="captura de ecra 2018-10-14 as 01 47 30" src="https://user-images.githubusercontent.com/10358443/46911430-3bf5cd80-cf53-11e8-81fa-85b2c151c9e1.png">

<img width="130" alt="captura de ecra 2018-10-14 as 01 47 43" src="https://user-images.githubusercontent.com/10358443/46911432-44e69f00-cf53-11e8-9b1b-07b264110a6b.png">

The array is not limited to PackedScenes I can make it what ever I want...

**Comment by Zireael07** [comment] 2018-10-13 08:10
I would edit the issue title to "export Array, type  does not work", since exporting arrays without type works fine.

**Comment by akien-mga** [comment] 2018-10-16 10:57
Duplicate of #20004.

**Closed by akien-mga** 2018-10-16 10:57 UTC
