### ISSUE TITLE
[3.4RC2 regression] Can't close last remaining scene tab in editor.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#54452] opened 2021-10-31 15:56 UTC
### Godot version

3.4RC2

### System information

Windows 10

### Issue description

Can't close current scene tab if this is the last remaining scene tab opened. We have to make a new scene tab or open another one to be able to close the first. Previous behavior (3.4RC1 and previous versions) would open an empty scene tab automatically when closing the last remaining tab.

### Steps to reproduce

Create, save and open a single scene. Try to close the tab. It can't be closed without creating another tab first.

### Minimal reproduction project

It does not need any particular project configuration. Just create a scene and try to close its tab without creating a new one.

**Comment by akien-mga** [comment] 2021-10-31 22:09
Duplicate of #54304.

**Closed by akien-mga** 2021-10-31 22:09 UTC
Labels: bug, topic:editor, regression
