### ISSUE TITLE
Touchscreen button doesn't obey control positioning

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#171] opened 2014-03-05 19:43 UTC
Hi
found a little thing:
the touchscreen button is missing the layout features found in other controls, and controls having specific layout (as the centercontainer) don't act upon it

as the other button lacks the passby press feature, I am currently work around it with a texture button and handling the press flag myself capturing scroll in, scroll out and pressures:

sample code:

```
func _input(event):
  if (event.type == 3 || event.type == 6 ):
    var button_rect = Rect2(get_node("LControl/Button").get_global_pos(), get_node("LControl/Button").get_size())     
    if (button_rect.has_point(event.pos)):
      button_pressed = event.is_pressed()
  if (event.type == 7 ):
    var button_rect = Rect2(get_node("LControl/Button").get_global_pos(), get_node("LControl/Button").get_size())
    if ( (!button_rect.has_point(event.pos)) and button_rect.has_point(event.pos-event.relative_pos) ):
      button_pressed=false
    if ( (button_rect.has_point(event.pos)) and !button_rect.has_point(event.pos-event.relative_pos) ):
      button_pressed=true
```

**Comment by akien-mga** [comment] 2015-10-29 12:17
Can someone confirm this issue in the current master branch?

**Comment by akien-mga** [comment] 2016-01-05 10:48
Ping :)

**Comment by kubecz3k** [comment] 2016-03-08 12:07
TouchScreenButton is not inheriting from ControlNode so the issue is still correct. However I'm unsure about bug status, since TouchScreenButton is not a Control by design, so it's hard to demand from it to behave like a Control node.

**Comment by kubecz3k** [comment] 2016-03-08 12:12
I think we should close this or convert to feature request, what do you think @akien-mga ? I personally would prefer to close since I'm unsure if there really is demand for this functionality (and if it's then we will have feature request soon anyway). Also other control nodes probably behave little different today on touch screens then they were in 2014 so I'm unsure how much usage needs TouchScreenButton meets  in present times anyway.

**Comment by akien-mga** [comment] 2016-03-08 12:15
As there as not been any activity on this issue in two years, neither from the reporter or from other interested users, I think we can close it indeed. If there's a need in the current 2.0 version, someone will open a feature request.

**Closed by akien-mga** 2016-03-08 12:15 UTC
Labels: bug, topic:core

**Comment by reduz** [comment] 2016-03-08 12:32
Ah I fixed this some months ago, forgot to close it

**Comment by AKashyap86** [comment] 2018-07-07 03:01
Hi . It works .. when inside a container (It will work in any others too like HBox or VBox but they are overkill).. 
Add a VBox, add few simple containers as children and one touch screen button as child of each container . And voila . You have control obeying touch screen buttons !!

**Comment by PonasKovas** [comment] 2019-06-18 16:28
I know this is not a big bug, but it really bothers me.
It really doesn't make sense to me why `TouchScreenButton` is a `Node2D` instead of `Control`.

As it's written in the latest documentation, 
[Node2D](https://docs.godotengine.org/en/3.1/classes/class_node2d.html#brief-description):

> A 2D game object, parent of all 2D related nodes. Has a position, rotation, scale and Z-index.

[Control](https://docs.godotengine.org/en/3.1/classes/class_control.html#brief-description):

> All User Interface nodes inherit from Control. A control’s anchors and margins adapt its position and size relative to its parent.

And just the word _BUTTON_ makes me think that `TouchScreenButton` should fall in the "User Interface" category.

Also, as I understand, Node**2D** nodes should only be used in **2D** games, and `TouchScreenButton` might be needed in both 2D and 3D games.

**Comment by 2blackbar** [comment] 2021-07-08 18:36
Cmon people, this is important stuff, you cant center touchscreen buttons !!! like WTF !!!!! Seriously ?

**Comment by Calinou** [comment] 2021-07-08 19:35
@2blackbar Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
