### ISSUE TITLE
use StyleBoxFlat to cause borders and rounded corners to overflow

### ISSUE THREAD

**Issue by 36k-wild-monkey** [godotengine/godot#45569] opened 2021-01-30 04:23 UTC
Godot version:

3.2.3.stable.official

OS/device including version:

Win10

Issue description:

Button uses StyleBoxFlat to cause borders and rounded corners to overflow 

![1](https://user-images.githubusercontent.com/46029824/106346827-e47ef580-62f4-11eb-97c9-6cc7b739abfb.png)
![2](https://user-images.githubusercontent.com/46029824/106346831-e648b900-62f4-11eb-9873-89e7c84a6773.png)
![3](https://user-images.githubusercontent.com/46029824/106346869-2019bf80-62f5-11eb-84e7-791b370acc84.png)
![4](https://user-images.githubusercontent.com/46029824/106346990-e6958400-62f5-11eb-997f-8d0fa38acb68.png)
![5](https://user-images.githubusercontent.com/46029824/106346992-e85f4780-62f5-11eb-9dbd-9abc77060786.png)

**Comment by Calinou** [comment] 2021-01-30 14:50
@36k-wild-monkey Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by 36k-wild-monkey** [comment] 2021-01-30 14:53
[project.zip](https://github.com/godotengine/godot/files/5898143/project.zip)

**Comment by 36k-wild-monkey** [comment] 2021-01-30 14:54
> @36k野生猴子请上传一[个最小的复制项目](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project)，使这更容易排除故障。

**Comment by Calinou** [comment] 2022-11-05 00:36
I can't reproduce this on 3.5.1 (Linux), closing. The StyleBoxFlat remains enclosed within the control's rect.

![image](https://user-images.githubusercontent.com/180032/200092861-86cf7c27-ab24-41a8-975b-90dc1837c681.png)

![image](https://user-images.githubusercontent.com/180032/200092872-3fe8b55d-7ef3-486d-981e-694a9d3c1271.png)

https://user-images.githubusercontent.com/180032/200092903-2545f8ac-9029-4088-8038-137ad798a52e.mp4

**Closed by Calinou** 2022-11-05 00:36 UTC
Labels: bug, topic:gui
