### ISSUE TITLE
Godot 4: VisibleOnScreenNotifier3D does not emit screen entered signal consistently 

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#65406] opened 2022-09-06 06:19 UTC
### Godot version

4.0 alpha 12-15

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

VisibleOnScreenNotifier3D emits the screen enter signal only once. When the camera looks away and then back on the visibility notifier node, the node will not emit the screen enter signal any more. I noticed the issue first in alpha 12 and it's still present in alpha 15.

### Steps to reproduce

1. open any 3d project, put a VisibleOnScreenNotifier3D in.
2. Run the project, move the notifier node off screen (or move the camera so that the notifier is off screen)
3. Move the notifier back into the frame (or turn camera towards notifier)
4. no signal is emitted

**Comment by venilark** [comment] 2022-12-30 11:23
tested it on Alpha 10 and it seems working fine but I don't see the camera_entered signal that was present in the old VisibilityNotifier

**Comment by Sezotove** [comment] 2023-01-21 03:01
I've been able to replicate this in 4.0b13.

Notifiers and enablers do not fire the OnScreen signal if they're a child and they set their parent to visible = false. 

Notifiers, If you make it a sibling of the node you want to 'manage' it will fire the signals, however they're still very inconsistent and do not appear to be working as intended.

**Comment by JonqsGames** [comment] 2024-02-12 18:22
In my case event with parent visible, VisibleOnScreenNotifier3D works in desktop but when deployed to web it just doesn't work.

**Comment by AThousandShips** [comment] 2024-02-12 18:26
That's because the notifier is only available on Vulkan, see [here](https://github.com/godotengine/godot/issues/87176)

**Comment by AThousandShips** [comment] 2024-02-12 18:32
Assuming from the comments above that this is specifically about visibility notifiers that are hidden, they do indeed not work, by design, see:
* https://github.com/godotengine/godot-proposals/issues/8458

Closing as this is not a bug, if the original issue was not this please update here

**Closed by AThousandShips** 2024-02-12 18:32 UTC
Labels: bug, topic:3d
