### ISSUE TITLE
GDScript printing a broken array crashes the game without any error

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#20425] opened 2018-07-24 22:45 UTC
https://github.com/godotengine/godot/commit/12d69ef53e8d86db864320449f5a4bd37a7c251b
x11

```
func _ready():
	var rs = []
	rs.push_back(rs)
	print(rs)
```

**Comment by Zylann** [comment] 2018-07-24 22:55
I would have done this:
```gdscript
func print_safe(value, blacklist={}):
	if typeof(value) == TYPE_ARRAY:
		if blacklist.has(value):
			printraw("<cycle!>")
		else:
			print("A")
			blacklist[value] = true
			printraw("[")
			for i in len(value):
				var sub_value = value[i]
				print_safe(sub_value, blacklist)
				printraw(",")
			printraw("]")
			blacklist.erase(value)
	
	elif typeof(value) == TYPE_INT:
		printraw(value)
```

Unfortunately GDScript fails at running it because it tries to hash the cyclic array, which ALSO causes a crash. But in C++ the pointer could be used instead and that would work.

**Comment by akien-mga** [comment] 2018-07-24 22:57
CC @vnen

**Comment by AlexHolly** [comment] 2018-07-24 23:03
Is there any usecase for this` rs.push_back(rs)`? I think it should show some error.
Another print? I am too lazy to write more than `print` :D

**Comment by Zylann** [comment] 2018-07-24 23:06
@AlexHolly arrays are too low-level to consider use cases to print errors when they are cyclic. Also they are used so often that the overhead would impact many places.
My example is not about adding another print, it's about fixing the one we have currently so it can print cycles :)

**Comment by vnen** [comment] 2018-07-25 01:04
I don't think this one is my fault xP

Seems the same as #8693.

**Comment by akien-mga** [comment] 2018-07-25 06:37
Indeed, duplicate of #8693.

**Closed by akien-mga** 2018-07-25 06:37 UTC
Labels: bug, topic:gdscript
