### ISSUE TITLE
Unknown regression in 3.0.1

### ISSUE THREAD

**Issue by CezaryKopias** [godotengine/godot#17055] opened 2018-02-26 19:32 UTC
**Godot version:**
3.0.1

**OS/device including version:**
Windows7 x64

**Issue description:**
I do not have a clue what is the problem but
provided scene does not run in 3.0.1 and immediately get
** Debug Process Started **
** Debug Process Stopped **
but works fine in 3.0

**Steps to reproduce:**
Open provided scene "shaders01.tscn" and hit F6

**Minimal reproduction project:**
[1 - testing shaders.zip](https://github.com/godotengine/godot/files/1759992/1.-.testing.shaders.zip)

**Comment by Zireael07** [comment] 2018-02-26 19:51
Have you tried running it several times? I noticed that after upgrading Godot, the first time or two the debugger connection doesn't quite work.

**Comment by hpvb** [comment] 2018-02-26 19:57
This is probably a duplicate of #17028. This will be fixed in 3.0.2

**Comment by akien-mga** [comment] 2018-02-26 21:07
Indeed, there's no main scene defined so it's a duplicate of #17028.

**Closed by akien-mga** 2018-02-26 21:07 UTC
