### ISSUE TITLE
Godot 2.1 HiDPI Crash on Windows 10 [PNG file corrupted by ASCII conversion]

### ISSUE THREAD

**Issue by archetypitect** [godotengine/godot#6010] opened 2016-08-02 15:11 UTC
I'm using Godot 2.1 RC on Windows 10 and have the same error as #5168.  Created new issue because I can't reopen that one, but can still reproduce the error.  Also, though the previous poster's screen was not large enough for hidpi, mine is.

I have a qhd screen on my laptop, and the engine runs fine in Auto - it just defaults to lowdpi.  If I set hidpi it hangs before reaching the project select and loops the same series of errors to the console as #5168:

`ERROR: _png_error_function: PNG file corrupted by ASCII conversion
   At: drivers\png\image_loader_png.cpp:60
libpng error: PNG file corrupted by ASCII conversion
ERROR: ImageLoaderPNG::_load_image: PNG Corrupted
   At: drivers\png\image_loader_png.cpp:94
ERROR: _load_mem_png: Condition ' err ' is true. returned: Image()
   At: drivers\png\image_loader_png.cpp:297
ERROR: RasterizerGLES2::texture_set_data: Condition ' p_image.empty() ' is true.
   At: drivers\gles2\rasterizer_gles2.cpp:962`

If I select a project, the same errors loop again and the editor crashes for good.

I'm wondering if perhaps it doesn't play nice with Windows' high dpi settings, as when it finally launches, everything is large/zoomed in.  Disabling display scaling in the .exe properties plops the scale back to normal, but doesn't fix the hang/errors.

**Comment by akien-mga** [comment] 2016-08-02 15:15
IIRC this was confirmed by @vnen too on IRC, as a Windows-only issue.

**Comment by akien-mga** [comment] 2016-08-02 15:16
Actually not just confirmed but also fixed by @vnen with 3cdb5e0 IINM. I'll soon make a RC2 build that you'll be able to test.

**Comment by vnen** [comment] 2016-08-02 15:16
This is a duplicate of #5949. It was already on master but present on RC1.

**Closed** 2016-08-02 15:17 UTC
Labels: bug, confirmed, platform:windows, topic:editor
