### ISSUE TITLE
Opened menus instantly close when text field is focused

### ISSUE THREAD

**Issue by cagibi-dev** [godotengine/godot#72605] opened 2023-02-02 14:39 UTC
### Godot version

4.0-beta17

### System information

Linux Mint 20.3 x86_64, Xfce with Xfwm4 on X11

### Issue description

When a menu is opened, it closes itself almost immediately if a text field is focused.

Also happens in the editor when in single-window mode. (EDIT: was already raised by #72189 for the editor version, is my issue a duplicate?)

![Peek 02-02-2023 15-34](https://user-images.githubusercontent.com/45714685/216353884-8d3681d6-2495-4f7a-8362-994cb4fa9563.gif)

On the GIF I clicked several times on the menu, but it appeared so briefly that only one frame was caught in the recording.

### Steps to reproduce

- Create a scene with MenuButton and TextEdit nodes
- Populate MenuButton with option(s)
- Run scene
- Click on TextEdit
- Click on MenuButton
- Notice that MenuButton is immediately closed

### Minimal reproduction project

[menutest.zip](https://github.com/godotengine/godot/files/10570017/menutest.zip)

**Comment by akien-mga** [comment] 2023-02-02 14:59
Works fine for me on Mageia Linux 9, with KDE Plasma 5.26.5 with KWin on X11.

Are you running Xfce on X11 or Wayland?

**Comment by cagibi-dev** [comment] 2023-02-02 14:59
I'm using X11.

**Comment by TheRealSlander** [comment] 2023-02-05 16:40
Confirming the bug on Manjaro Cinnamon v5.6.7 (X11) with the main menu instantly closing if the code editor tab is selected.
If I switch to 2D or 3D view, I can use the main menu normally. The bug is very annoying :D

Godot version is 4.0 Beta 17 and I'm using the Single Window Mode. When disabling the Single Window Mode, the problem is gone.

https://user-images.githubusercontent.com/102065761/216832047-82c84487-4726-4324-bce8-5ae8cb10fc6c.mp4

**Comment by cagibi-dev** [comment] 2023-02-14 19:46
This bug disappeared in version 4.0 RC2, at least for me. Seems like some change between beta17 and RC2 fixed it.

@TheRealSlander do you still encounter it?

If not, let's close this issue, and re-check #72189 (similar issue) as well.

**Closed** 2023-02-14 22:04 UTC
Labels: bug, platform:linuxbsd, topic:porting, topic:gui

**Comment by TheRealSlander** [comment] 2023-02-14 22:16
I confirm the bug has disappeared in RC1 and RC2. Great job!
