### ISSUE TITLE
Navigation2D freezes the game on some Android devices

### ISSUE THREAD

**Issue by Luraktinus** [godotengine/godot#23917] opened 2018-11-23 08:28 UTC
**Godot version:**
Godot 3.1alpha2

**OS/device including version:**
a Huawei P9 lite with Android 6

**Issue description:**
Game crashes on some Android devices, if points are in direct sight of each other, it works, but if it has to make a turn, it freezes the game.

Test project: https://github.com/Luraktinus/EN_/tree/Test
or the minimal version here:
[test.zip](https://github.com/godotengine/godot/files/2610082/test.zip)

Related issue: https://github.com/godotengine/godot/issues/466

**Steps to reproduce:**
Run Level 1 of the Project on some Android devices, some will crash after some time.

**Comment by akien-mga** [comment] 2018-11-23 09:01
Tried on a Samsung S3 running LineageOS 14.1, couldn't get it to crash so far. However the player and enemies are invisible :)

**Comment by Luraktinus** [comment] 2018-11-23 09:03
Are they visible on a PC ?

**Comment by akien-mga** [comment] 2018-11-23 09:05
Yeah on Linux it works well. On Android the game is playable though, just without the Polygon2D-based graphics.

**Comment by akien-mga** [comment] 2018-11-23 09:06
Can you retrieve logs from the crashing game with `adb`?

**Comment by Luraktinus** [comment] 2018-11-23 09:30
yeah, but later

**Comment by Luraktinus** [comment] 2018-11-23 11:05
[test.txt](https://github.com/godotengine/godot/files/2610484/test.txt)
here is the log of a freezing game

**Comment by Luraktinus** [comment] 2018-11-23 11:36
it only freezes with an enemy that uses Navigation2D, and if they are more than one point

**Comment by akien-mga** [comment] 2018-11-23 11:39
Do you also get the freeze when using GLES2? It would be interesting to have the logs in such a case, in the ones from https://github.com/godotengine/godot/issues/23917#issuecomment-441212955 I see mainly GLES3-related issues.

**Comment by Luraktinus** [comment] 2018-11-23 11:42
how do i force GLES2 rendering on android?

**Comment by akien-mga** [comment] 2018-11-23 12:04
You can set GLES2 as renderer in Project Settings before exporting.

**Comment by Luraktinus** [comment] 2018-11-23 16:07
Tried that, same result :/

**Comment by Luraktinus** [comment] 2018-11-27 16:41
any more ideas how to go around this bug?

**Comment by akien-mga** [comment] 2019-02-08 09:59
Thanks, I'll close this one as duplicate of #24835 as it's clearer then, we now know what to focus on to fix this for both Android and iOS.

**Closed by akien-mga** 2019-02-08 09:59 UTC
Labels: bug, hero wanted!, platform:android, topic:core
