### ISSUE TITLE
Godot does not rename files in such a way that Git is aware of the change

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#86403] opened 2023-12-21 19:44 UTC
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Windows 10 Mobile

### Issue description

If you have your Godot project as part of a Git repository and you rename or move a file within the Godot editor, this is not tracked by Git.

### Steps to reproduce

Create a new Git repository.  Create a new Godot project within the repository.  Add a file to the project.  Add the file to git and commit the change.  Now rename and/or move the file in the Godot editor.  Now commit again.  The old file path will be indicated as missing, and the new file path will be indicated as not added.  

Git is unaware of the file's new name/location.  Because of this, my Git history is not keeping track of the times I rename or move a file.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2023-12-21 19:55
So this will happen automatically if you move the file in the operating system? That's not how I've had things work, this is something you need to manually do in my experience

**Comment by Zireael07** [comment] 2023-12-21 19:57
Yeah, if moved in the filesystem Git will pick up on the existence of the new file (usually)

**Comment by AThousandShips** [comment] 2023-12-21 19:58
Yes the existence, marking the old one as deleted and the new one as added, until you use `git add` or `git mv`, at least that's how it works for me

**Comment by Zireael07** [comment] 2023-12-21 20:14
>  it might also not apply without git mv if the file doesn't match enough

hence the 'usually' in my comment above

**Comment by AThousandShips** [comment] 2023-12-21 20:17
But `git` doesn't automatically do things like this by design, and it did pick up on it according to the issue? It just didn't automatically add it to the commit, from the wording:
> Now rename and/or move the file in the Godot editor. Now commit again.

There's no automatic management of this in the editor, as per the previous sentence the adding was not implied here

**Comment by fire** [comment] 2023-12-22 00:45
As far as I know in other systems there would be a git addon that would let the developer add files to the stage.

**Comment by blackears** [comment] 2023-12-22 01:29
Just to be clear - I am moving the files by dragging and dropping them in the File System area of the Godot editor and renaming them in the save area.  I would expect Godot to check to see if the files are hosted in a Git repository, and if so provide something similar to a `git mv` command instead of just using the OS's native renaming system.

**Comment by Zireael07** [comment] 2023-12-22 08:11
> I would expect Godot to check to see if the files are hosted in a Git repository, and if so provide something similar to a git mv command instead of just using the OS's native renaming system.

That's only true of IDEs that have a Git plugin. Godot does not have such a plugin yet AFAIK.

**Comment by AThousandShips** [comment] 2023-12-22 13:28
So this isn't a bug, Godot itself without plugins doesn't interact with VCS in any way, and arguably you are expecting behavior that goes right against what VCS workflow is normally supposed to be, as I said above if Godot *did* do this without being told to it would be a bug, as VCS is supposed to be done with direct intentionality

So I'd suggest investigating the Godot [git plugin](https://github.com/godotengine/godot-git-plugin) for some functionality, otherwise this is not a bug but the area for a proposal, but I don't think this is something that's going to be popular, even as an optional setting

Closing this as there's no bug here, and the proper place for this is a proposal

Thank you

**Closed by AThousandShips** 2023-12-22 13:28 UTC
Labels: topic:editor, needs testing
