### ISSUE TITLE
First UI element on the tree is getting it's background detached from itself when zooming

### ISSUE THREAD

**Issue by DaviWollmann** [godotengine/godot#86760] opened 2024-01-03 20:00 UTC
### Tested versions

- Reproducible: Godot v4.2.1.stable.mono, Not Reproducible: Godot v3.5.3.stable.mono LTS

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 27.20.100.9664) - Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 Threads)

### Issue description

When zooming with the Camera2D on a Node2D that has as a child a CanvasLayer with UI Controls, the first control node is getting its background detached from itself.

![bug-report](https://github.com/godotengine/godot/assets/38411284/4f79ac41-5851-461b-a32c-e290994985b0)

### Steps to reproduce

* Create a new scene and for the root node type use Node2D
* Add a Sprite2D node and add a texture to it
* Add a Camera2D to it with the following script:
`

          extends Camera2D
          
          var zoom_speed := 0.05
          
          func _input(event: InputEvent):
	          if event.is_action_released('zoom_in'):
		          zoom_camera(-1)
          
	          if event.is_action_released('zoom_out'):
		          zoom_camera(1)
          
          func zoom_camera(direction: int) -> void:
	          var previous_mouse_position := get_local_mouse_position()
          
	          zoom += zoom * zoom_speed * direction
	          
	          var diff = previous_mouse_position - get_local_mouse_position()
	          offset += diff
`
* Create a new scene and for the root node type now use CanvasLayer
* Add some controls to it (buttons, panels...)
* Add the scene to the one created before and set that as the main scene
* Start the game and try scrolling in and out, the first UI element on the CanvasLayer scene must loses its background

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/godotengine/godot/files/13822834/bug.zip)

**Comment by arkology** [comment] 2024-01-03 20:02
Try Compatibility renderer, should fix the problem.
Duplicate of https://github.com/godotengine/godot/issues/58314

**Comment by Calinou** [comment] 2024-01-03 21:50
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.

**Closed by Calinou** 2024-01-03 21:50 UTC
