### ISSUE TITLE
Signal unbinding broken on Web builds

### ISSUE THREAD

**Issue by GuilhermeGSousa** [godotengine/godot#67297] opened 2022-10-12 07:59 UTC
### Godot version

master

### System information

Windows 10

### Issue description

Unbinding an argument when connecting a signal is causing that signal to not be emited on web builds. The signal will work fine on desktop builds.

### Steps to reproduce

1. Connect to a signal that has at least one argument, unbinding it
2. Call that signal
3. Notice that the conected method is not called on web builds

or

Download project below and press the button on both desktop and web builds, the signal won't be emited on the web build.

### Minimal reproduction project

[unbind-bug.zip](https://github.com/godotengine/godot/files/9762818/unbind-bug.zip)

**Comment by kleonc** [comment] 2022-10-12 13:51
Confirmed, the error (when running MRP):
```
USER ERROR: Error calling from signal 'on_pressed' to callable: 'Control(bug.gd)::_on_bug': Method expected 0 arguments, but called with 1.. tmp_js_export.js:466:18
   at: emit_signalp (core/object/object.cpp:1057) - Error calling from signal 'on_pressed' to callable: 'Control(bug.gd)::_on_bug': Method expected 0 arguments, but called with 1.. tmp_js_export.js:466:18
```
Seems like it's connected directly to the method instead of to an unbinding callable to the method. For confirmation:
```gdscript
func _ready():
	var c: Callable = get_signal_connection_list("on_pressed")[0].callable
	c.is_custom() # `true` on desktop, `false` on web export.
	c == _on_bug # `false` on desktop, `true` on web export.
```

**Comment by akien-mga** [comment] 2023-02-22 15:16
Duplicate of #72348

**Closed by akien-mga** 2023-02-22 15:16 UTC
Labels: bug, topic:core, confirmed, topic:export
