### ISSUE TITLE
Copy / Paste Nodes in Scene does not work anymore

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#64035] opened 2022-08-07 07:20 UTC
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

When I try to copy and paste a node it does not work anymore. I am quite sure it worked before.
Now the paste inserts Text to the editor.

### Steps to reproduce

Add a node to the scene.
Select it, copy it with CTRL+C and try to paste it with CTRL+V while the script editor is open.

**Comment by Calinou** [comment] 2022-08-07 07:33
cc @KoBeWi

**Comment by DarkiStar** [comment] 2022-08-10 11:09
I tried it with 3.4.4 stable and copy/paste nodes is not possible **while the script editor is open**.
I am not sure now if the behaviour is intended. But if it is, it is not intuitive.

**Comment by KoBeWi** [comment] 2022-08-10 11:16
Looks like a typical input issue that is fixed in 4.0, see #52861

Copy-paste does work, but the shortcut is randomly hijacked by one of the visible editors (in your case it's the script editor). This is not intended behavior and is an already known issue.

**Comment by EricEzaM** [comment] 2022-09-27 12:40
Are we closing such issues in favour of tracking them all in #52861?

**Comment by akien-mga** [comment] 2022-09-27 13:12
> Are we closing such issues in favour of tracking them all in #52861?

Yes, closing as duplicate of #52861.

**Closed by akien-mga** 2022-09-27 13:12 UTC
Labels: bug, topic:editor, topic:input
