### ISSUE TITLE
Properly document navigation mesh generation

### ISSUE THREAD

**Issue by 1Snakel** [godotengine/godot#32425] opened 2019-09-29 00:39 UTC
3.1.1
Ubuntu 16.04

Editor generates non conforming navmeshes.

Generate navmesh, tweaks wont change anything

**Minimal reproduction project:**
[NavMeshBug.tar.gz](https://github.com/godotengine/godot/files/3666166/NavMeshBug.tar.gz)
![image](https://user-images.githubusercontent.com/11818756/65824069-57c3b380-e238-11e9-8402-5d7dae18bb5a.png)
![image](https://user-images.githubusercontent.com/11818756/65824070-5db99480-e238-11e9-9502-4fcb9a0c5e72.png)
![image](https://user-images.githubusercontent.com/11818756/65824072-64e0a280-e238-11e9-8129-0a803633c42c.png)

**Comment by JFonS** [comment] 2019-09-30 07:53
I checked your reproduction project. You need to set your MesheInstances as children of the NavigationMeshInstances, not the other way around.

This correctly generates a navigation mesh for the whole cave:
![Screenshot from 2019-09-30 09-51-09](https://user-images.githubusercontent.com/4402304/65859176-df5c1000-e367-11e9-9b37-f8d481a2264e.png)

This whole workflow should be properly documented in the official docs since I don't think there is any navigation related tutorial. Changing the issue title and tags to keep track of that.

**Comment by Arunkumar1998BOM** [comment] 2019-11-04 18:12
Hi @JFonS , can you tell me under which hierarchy in the godot-doc repo, can I make the changes for the above observation. I am new to this and it would be really helpful
Thanks

**Comment by Calinou** [comment] 2020-04-17 13:36
What's the status on this, now that #34776 has been merged?

**Comment by smix8** [comment] 2022-10-11 19:46
@Calinou @akien-mga 
This issue can be closed as there is now both class-doc as well as a dedicated godot-doc page merged just for navmesh generation.

**Closed** 2022-10-11 20:57 UTC
Labels: documentation, topic:navigation
