### ISSUE TITLE
OS.current_screen does not switch screens in fullscreen

### ISSUE THREAD

**Issue by outfrost** [godotengine/godot#43876] opened 2020-11-26 01:53 UTC
**Godot version:**
3.2.3 stable

**OS/device including version:**
Manjaro 20.2, Linux 5.9.10
OpenGL ES 3.0 Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.39.0, 5.9.10-1-MANJARO, LLVM 11.0.0)

**Issue description:**
I've been searching around, but cannot find an answer.

I use an `OptionButton` to move my game's window from one screen to another, like so:
```gdscript
func on_item_selected(index: int) -> void:
	OS.current_screen = index
```

When in windowed mode (i.e. `OS.window_fullscreen == false`), this works just fine. I select screen 0, the window goes to screen 0; I select screen 1, the window is now on screen 1.

However, when the game is running fullscreen (`OS.window_fullscreen == true`), setting `OS.current_screen` does nothing. The game stays on the same screen.

Is this inteded? It seems like an inconsistency to me. Is there a different (better?) way to switch screens while in fullscreen?

**Minimal reproduction project:**
[screen-switch-repro.zip](https://github.com/godotengine/godot/files/5605190/screen-switch-repro.zip)

**Comment by Calinou** [comment] 2020-11-26 01:57
> Is this inteded? It seems like an inconsistency to me. Is there a different (better?) way to switch screens while in fullscreen?

Try this:

```gdscript
OS.window_fullscreen = false
OS.set_deferred("current_screen", index)
OS.set_deferred("window_fullscreen", true)
```

**Comment by outfrost** [comment] 2020-11-26 02:59
Will test on Windows and provide a repro project when I get a moment.

My current workaround looks like this:
```gdscript
func on_item_selected(index: int) -> void:
	if OS.window_fullscreen:
		OS.window_fullscreen = false
		OS.current_screen = index
		OS.window_fullscreen = true
```

And it works, but it's a bit counterintuitive.

**Comment by outfrost** [comment] 2020-11-26 22:59
On Windows 10 it behaves exactly the same.

I have attached a repro project in the top post.

**Comment by akien-mga** [comment] 2022-07-19 08:03
Duplicate of #14620

**Closed by akien-mga** 2022-07-19 08:03 UTC
Labels: bug, topic:core, needs testing
