### ISSUE TITLE
Area fails to detect collisions on 2.0 beta

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#3589] opened 2016-02-04 22:42 UTC
As I mentioned on facebook, and show on this video of my game production https://www.youtube.com/watch?v=cQ8KxhPOFk0
and confirmed with other users. The collision not works in some cases.
I send too the scenes that this issue occurs.

[area_fail.zip](https://github.com/godotengine/godot/files/118364/area_fail.zip)

**Comment by cimpresovec** [comment] 2016-02-05 10:10
I have seen the issue on Facebook and have tested it since you provided the scene. The problem is  on your side. When you upgrade your gun and add more bullets, you forget to add the area_enter to some bullets. Here is the fixed version. All collisions work after this. Please test and then you can close the issue if it also fixes it for you.

`func add_tiro():
	var tiro
	if gun==0:
		tiro = TIRO1.instance()
	elif gun>0:
		tiro = TIRO2.instance()
	tiro.set_pos(get_pos() + Vector2(get_texture().get_width()/2,0))
	tiro.get_node("Area2D").connect("area_enter",self,"_on_fire_enter")
	get_parent().add_child(tiro)
	if gun>1:
		if gun>2:
			tiro = TIRO2.instance()
		else:
			tiro = TIRO1.instance()
		tiro.set_pos(get_pos() + Vector2(get_texture().get_width()/2 - 10,-10))
		tiro.set_rot( 0.15 )
		tiro.get_node("Area2D").connect("area_enter",self,"_on_fire_enter")
		get_parent().add_child(tiro)
	if gun>3:
		if gun>4:
			tiro = TIRO2.instance()
		else:
			tiro = TIRO1.instance()
		tiro.set_pos(get_pos() + Vector2(get_texture().get_width()/2 - 10,10))
		tiro.set_rot( -0.15 )
		tiro.get_node("Area2D").connect("area_enter",self,"_on_fire_enter")
		get_parent().add_child(tiro)
	
	
	delay_tiro = 0.1`

**Closed** 2016-02-08 11:57 UTC
Labels: archived
