### ISSUE TITLE
Light2D "Light Mask" property not working

### ISSUE THREAD

**Issue by oiblank** [godotengine/godot#33657] opened 2019-11-16 13:48 UTC
**Godot version:** 
3.2 beta 1
**OS/device including version:** 
Windows 10
**Issue description:** 
Light2D's Light Mask property not working, when two lights overlap, I can't disable the brightness stacking by disabling their light mask to make them not react to each another.
**Steps to reproduce:**
Make two separate Light2D nodes overlap each other. Try disabling or changing their Light Mask property.

**Comment by KoBeWi** [comment] 2019-11-16 13:52
Is this related? #26507

**Comment by oiblank** [comment] 2019-11-16 14:50
> Is this related? #26507

The referenced issue should be solvable by changing the "Light Mask" property, which would make overlapping Light2D nodes not interact with each other, which is not working at the moment.

They are in a way related, but the referenced issue is a feature proposal to clamp pixel brightness for overlapping Light2Ds, and this is a bug report for a property not working right.

**Comment by 2shady4u** [comment] 2019-12-26 14:43
I have a similar problem with a game I'm currently making.

![shaders2](https://user-images.githubusercontent.com/42484461/71479793-4d449600-27f6-11ea-9c27-d124865fd22f.gif)

Even though the light mask property of the Light2D's is disabled (they shouldn't be influenced by other lights in the scene) they still influence each other...

**Comment by Axeltherabbit** [comment] 2020-04-11 15:19
Would be nice to see this thing fixed in the new version, I'm having the same issue

**Comment by Calinou** [comment] 2020-04-11 16:16
Someone should check in the `master` branch if this is still present with the Vulkan renderer.

**Comment by KoBeWi** [comment] 2020-04-11 16:28
[Lights2D don't work at all on Vulkan](https://github.com/godotengine/godot/issues/36112).

**Comment by Calinou** [comment] 2020-05-19 08:28
Duplicate of #8685 (from what I can understand).

**Closed by Calinou** 2020-05-19 08:28 UTC
Labels: bug, confirmed, topic:rendering
