### ISSUE TITLE
Render-related errors on editor close (Attempted to free invalid ID, Condition "!shader" is true, Condition "!material" is true)

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#73503] opened 2023-02-17 14:51 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Linux Ubuntu 20.04 with Unity desktop + Intel Haswell integrated graphics

### Issue description

If I run godot 4 rc2 in the terminal, then close the Godot window, I have the following errors:

> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
> ERROR: Attempted to free invalid ID: 0
>    at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
> ERROR: Condition "!shader" is true.
>    at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
> ERROR: Condition "!material" is true.
>    at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)

(I also sometimes have memory leak warnings, but that is another issue I think)

If I run Godot headlessly e.g. using --convert-3to4, it quickly ends the process and shows the same error (good to know to quickly reproduce it without manual intervention).

Note: project is mobile, I have both an integrated Intel Haswell graphics card with only partial support for Vulkan, and a discrete Nvidia GPU that does support Vulkan but doesn't seem to be detected.

### Steps to reproduce

1. Run godot4 (rc2) in terminal
2. Close window

OR

1. Run godot4 --convert-3to4

### Minimal reproduction project

N/A (create any empty project to reproduce)

**Comment by theraot** [comment] 2023-03-03 00:44
I'm getting this output on an exported game in Windows 10 made with Godot 4 stable (calling it from the CMD so I can see the output):

```
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.236 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
ERROR: Condition "!material" is true.
   at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)
```

It only happens with Forward Mobile.

**Comment by theraot** [comment] 2023-03-03 00:46
Oh, arguably same issue: https://github.com/godotengine/godot/issues/67406

**Comment by Calinou** [comment] 2023-03-03 03:13
- Duplicate of https://github.com/godotengine/godot/issues/67406.

**Closed by Calinou** 2023-03-03 03:13 UTC
Labels: bug, platform:linuxbsd, topic:rendering
