### ISSUE TITLE
Adding a BitmapFont as a Custom Font in Project Settings causes errors

### ISSUE THREAD

**Issue by ReanthSoft** [godotengine/godot#55008] opened 2021-11-15 20:50 UTC
### Godot version

3.4

### System information

Windows 10, NVIDIA GeForce RTX 2080, GLES3

### Issue description

In Godot 3.4, adding a BitmapFont as a Custom Font in the Project Setting's gui/theme/custom_font section causes errors when reopening the project. The same happens if a BitmapFont is added to a Theme which is then used in the gui/theme/custom section. This works in Godot 3.3.4

![bitmapFontBug01](https://user-images.githubusercontent.com/94398478/141850836-af88d127-c7a7-4b69-83aa-2b9f82a5fb41.png)
![bitmapFontBug02](https://user-images.githubusercontent.com/94398478/141850844-b057a0d0-42ca-4365-bf58-f24d703dbaed.png)

### Steps to reproduce

Open the provided project and see the errors in the console.

### Minimal reproduction project

[BitmapFontBug.zip](https://github.com/godotengine/godot/files/7541550/BitmapFontBug.zip)

**Comment by Calinou** [comment] 2021-11-15 21:11
Related to https://github.com/godotengine/godot/issues/36614. See https://github.com/godotengine/godot/issues/36614#issuecomment-592177855 for a workaround.

**Comment by ReanthSoft** [comment] 2021-11-15 21:30
Thanks, I've added the theme to a root Control node as a workaround.

**Comment by pycbouh** [comment] 2021-11-30 16:25
This is actually the same issue as https://github.com/godotengine/godot/issues/54752, which will be fixed by https://github.com/godotengine/godot/pull/55483. The problem is not with fonts, it's with loading images.

**Closed** 2021-12-02 16:20 UTC
Labels: bug, topic:gui
