### ISSUE TITLE
New cyclic reference error with autoload and preloaded script

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61043] opened 2022-05-15 02:05 UTC
### Godot version

6d5d9dd

### System information

Windows 10 x64

### Issue description

I have a `class_name` script `Game` that preloads another script that uses an autoload that uses a variable of the type `Game`. There is obvious cyclic reference here, but it runs fine in 3.5. In 4.0 the script is parsed properly in the editor, but at runtime it stops on `Parser Error: Could not preload resource file` at the `preload` line.

### Steps to reproduce

The steps are confusing, just check the project.

### Minimal reproduction project

[AutoloadBug.zip](https://github.com/godotengine/godot/files/8694166/AutoloadBug.zip)
You can run it both in 3.5 and 4.0 and compare results.

**Comment by lyuma** [comment] 2022-05-17 08:30
Thanks for filing this. It's quite a big issue in my projects, some of which had over a hundred GDScript files, so it was quite difficult to untangle while porting to 4.x

As a result I had to go and replace a lot of variable references with simply type `Object` ... and to solve cycles with Autoload, I had to be very careful with the initialization order, and where not possible, I had to replace them with `$"/root/AutoloadName"` but this breaks autocomplete and usage of enums in match statements, so not perfect.

it's still very difficult to develop without accidentally re-introducing one of these cyclic references.

**Comment by BenjaminNavarro** [comment] 2022-06-26 13:13
I face the same issue when trying to port my 3.4 game to 4.0 alpha 10.

I remember when trying to do a port with an earlier version (probably before or around the first alpha build) errors would show up in the editor but now they only appear when the game is launched. I still think that this should work as with 3.x but a least having the errors in the editor as well made fixing the "errors" easier

**Comment by tinmanjuggernaut** [comment] 2022-07-31 19:33
Maybe related to or duplicate of #58551?

**Comment by adamscott** [comment] 2022-08-03 23:59
Related to #58181. In both cases, it's about cycling references with a preload.

**Comment by KoBeWi** [comment] 2022-09-25 17:51
I created 2 new MRPs, because the original one doesn't display the issue correctly:
[cyclic.zip](https://github.com/godotengine/godot/files/9641426/cyclic.zip)
[cyclic3.zip](https://github.com/godotengine/godot/files/9641427/cyclic3.zip)
The latter is made for Godot 3 and you can see that the scene loads correctly.

**Closed** 2022-11-18 22:46 UTC
Labels: bug, topic:gdscript, confirmed, regression

**Comment by boballymoon** [comment] 2023-03-27 10:19
![game_world](https://user-images.githubusercontent.com/129056056/227912069-9c423567-a89c-4280-80ad-0e71761114c8.PNG)

Stupid error. I used godot engine from 3.1 to 4-beta. But i did not see this error. I solved that:
add empty node in project and give "game" and "path" name. Copy this for every script. 

@onready var Game = get_node("/root/game_world/game") #game object and variables
@onready var Path = get_node("/root/game_world/path") #game's all paths is in script
