### ISSUE TITLE
Add Node in the editor is giving an error when filtering the name.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#24041] opened 2018-11-28 18:22 UTC
Win10 64-bit af8d941

Minimal Project: [3.1 Add Node Error.zip](https://github.com/godotengine/godot/files/2626115/3.1.Add.Node.Error.zip)

When creating a new node in the editor I encountered an error popping up in the console.

![godot_master_2018-11-28_20-08-19](https://user-images.githubusercontent.com/13004169/49172637-47a62380-f34a-11e8-9804-3ef6dff05f71.png)

It was specifically caused by one new custom node type that I added (using a plugin) with the name BlendSprite.  Once I reach the point of typing BLE the error starts happening, as it matches to the ble in VisibilityEnabler.

Unsure of the severity of it or what else might be affected.

![image](https://user-images.githubusercontent.com/13004169/49172668-5a205d00-f34a-11e8-9b1d-b6db0598cd0b.png)

**Comment by willnationsdev** [comment] 2018-11-28 18:50
Ugh, I swear, there's just no end to these `script class`-related errors. XD I'll take a look at it as soon as I'm able.

**Comment by willnationsdev** [comment] 2018-11-30 15:48
I've identified what the problem is. When determining whether the `current_item_is_preferred`, it is not taking into account whether the `p_type` or the `to_select_type` is a custom type. Since custom types force themselves to become the `to_select_type` if none exists yet, there are cases where an engine type will run `ClassDB::is_parent_class` against a custom type (and obviously the ClassDB would fail to look up the custom type, resulting in the error).

**Comment by mbrlabs** [comment] 2019-07-12 07:05
That's probably fixed in current master. I don't get any errors at least with the provided reproduction project.

**Comment by akien-mga** [comment] 2019-07-12 07:09
Might have been fixed by #26818?

**Comment by akien-mga** [comment] 2019-10-30 10:37
This seems fixed in the current master branch indeed.

**Closed by akien-mga** 2019-10-30 10:37 UTC
Labels: bug, topic:editor
