### ISSUE TITLE
Windows export template of godot 2.0rc1 has fewer options than latest beta

### ISSUE THREAD

**Issue by nopeson** [godotengine/godot#3664] opened 2016-02-11 06:32 UTC
Godot 2.0 rc1:
![win_export_20_rc1](https://cloud.githubusercontent.com/assets/16130334/12970623/6da27978-d091-11e5-9334-e1e6778fc092.png)

Godot 2.0 latest beta:
![win_export_20_beta](https://cloud.githubusercontent.com/assets/16130334/12970627/793e0860-d091-11e5-8072-73bbbd63013e.png)

**Comment by akien-mga** [comment] 2016-02-11 06:41
Yes that's because we were using a relatively big third party library for this, and it caused several issues, so it was removed: 80e88c6.

The idea for 2.1 would be to rework on this topic to either write some custom code to replace what this library was doing (we were using only a very small fraction of its features, so it was a bit overkill to have to maintain it), or strip the relevant code from that library and maintain it ourselves.

**Comment by bojidar-bg** [comment] 2016-08-11 14:13
@akien-mga Given that nothing about this happened in 2.1 (*afaik), maybe you should update it? :smile:

**Comment by akien-mga** [comment] 2016-08-11 14:22
Right, closing as "not a bug", since we did this on purpose. The bug report keeping track of readding such a feature is #1211.

**Closed by akien-mga** 2016-08-11 14:22 UTC
Labels: platform:windows, topic:porting

**Comment by Sslaxx** [comment] 2016-08-11 16:12
Is the information retained in export.cfg?
