### ISSUE TITLE
Adding "export (Array, Type) var my_vars" to GDScript for arrays with pre-selected type.

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#7299] opened 2016-12-14 03:34 UTC
We know that using a line such as
`export (Texture) var my_texture`
in GDscript will allow you to select one individual image from the Editor.
![](http://i.imgur.com/cYaOrbW.png)

That is nice, but what if you wanted to load 5 or 10 images. You would have to copy paste 5-10 lines of code in GDScript, as well as keep track of var names of each texture, my_texture1, my_texture2 and so on. ![](http://i.imgur.com/spb5b0q.png)

Here is my idea of future implementation:
`export (Array, Texture) var my_texture_array`

If we could improve export to take in two arguments, one that tells it that we want to create an export of type Array, and the other to define the type, we would make it a lot more user-friendly and intuitive.

I am not saying it is not possible to create an array of Textures in the editor. Currently, if you were to write for example:
`export var my_array = Array()`
you would get an Array in the editor. 
...
Except it is very encumbersome.
You would have to first set the size of the array (and that is fine, but can also be improved by adding a + button), 
Then you would have to set the type; browsing through a long list of types. That can take a minute if you don't know exactly where in the list it is. 

So if I were to select for example "Object", I get a long list I have to look through in order to find "Texture". 
![](http://i.imgur.com/ockxTi7.png)
I would have to select ImageTexture, since Texture is not on the list. Did not know that, so I probably spend a lot more time trying to find it.
After all that, I can select the little arrow on the right in order to open ImageTexture in the inspector. This allows me to load ONE image. Now I have to repeat the same process for every. single. texture.

So my thought by adding an 
`export(Array, Texture) var my_textures` 
option to GDScript, we would not have to select any "Type", navigate a long long list, select it and open it up, and only to repeat this nonsense. 

It would just be there, ready and waiting for you. Easily accessible and user-friendly.

Thoughts? Opinions? Feelings?

**Comment by akien-mga** [comment] 2016-12-14 06:22
Duplicate of #3586?

**Comment by Tybobobo** [comment] 2016-12-14 07:52
@akien-mga As long as that also cover export types (Texture, PackedScene, and so on). :)

Although I don't see the need for having *three* arguments for creating a single array with a predefined type(?).

**Comment by bojidar-bg** [comment] 2016-12-14 11:14
Duplicate of #3586 indeed. Under #6930, `export(Array, Texture)` would work just fine.

**Closed by bojidar-bg** 2016-12-14 11:14 UTC
