### ISSUE TITLE
Not possible to have perfect integers with timer node when values are over 22.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#5826] opened 2016-07-20 18:52 UTC
**Operating system or device - Godot version:**
Win10 64 bit; ATI 79xx GPU; 24 Gigs RAM; third-gen i7 CPU.
Godot 2.1 Beta (build from July20)

**Issue description** (what happened, and what was expected):
When typing an integer value for the timer node (for the _wait time_ parameter), values over 22 will instead produce a decimal number that's just below the intended value.

So a value of 23 becomes 22.999999
And a value of 600 becomes 599.999987

**Steps to reproduce:**
Open Godot, add a timer node in an empty project, give it an integer value over 22

This shouldn't be too hard to fix I think.

**Comment by TheoXD** [comment] 2016-07-20 19:03
totally normal

**Comment by bojidar-bg** [comment] 2016-07-21 13:33
Note that in 3.0 we would have double precision floats, so should be less of a problem then (still it is a regression from 2.0, since the editor rounded them properly back then)

**Comment by ScotFlux** [comment] 2016-07-21 14:45
Actually, I've read this before posting a new issue. What comes to my mind is Particles2D and Inconsistent decimal places the Editor (Inspector) took. Also, still on Particles2D, some parameter start its strange values not from 22.3, instead from 33.5

**Comment by ScotFlux** [comment] 2016-08-06 02:51
Fixed by https://github.com/godotengine/godot/commit/9151eb591dcab408d3a7e4d9e3b3874c2e281acf

I guess this issue can be closed now...

I feeeel good (whoa-oa-oa!)

**Comment by vnen** [comment] 2016-08-06 03:47
Closing as fixed then.

**Closed by vnen** 2016-08-06 03:47 UTC
Labels: enhancement, topic:editor, usability

**Comment by bojidar-bg** [comment] 2016-08-06 09:04
I think, fixed by 9151eb591dcab408d3a7e4d9e3b3874c2e281acf, tell us if it is still present, so that we can reopen it.
