### ISSUE TITLE
MenuButton -> PopupMenu label disappears when assigning a shortcut

### ISSUE THREAD

**Issue by arnoldochavez** [godotengine/godot#32634] opened 2019-10-08 00:01 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
When assigning a shortcut to a new added item in the PopupMenu of a MenuButton, the label disappears and just displays the shortcut text

**Steps to reproduce:**
```
var mb := MenuButton.new()
var popup := mb.get_popup()
var shortcut : ShortCut
mb.text = "file"
popup.add_item("New item")
shortcut = ShortCut.new()
shortcut.shortcut = InputEventKey.new()
(shortcut.shortcut as InputEventKey).scancode = KEY_N
(shortcut.shortcut as InputEventKey).control = true
popup.set_item_shortcut(0, shortcut)
add_child(mb)
```

**Minimal reproduction project:**
Copy & Paste the code given in the **Steps to reproduce** section

Without shortcut:
![imagen](https://user-images.githubusercontent.com/33552997/66357795-87a44280-e92d-11e9-8801-9a01e4c4e73d.png)

With shortcut:
![imagen](https://user-images.githubusercontent.com/33552997/66357761-680d1a00-e92d-11e9-98c3-23d5506ca3b8.png)

**Comment by arnoldochavez** [comment] 2019-10-08 01:05
Maybe the problem is here:
https://github.com/godotengine/godot/blob/31600f07d2fae10a2f256ea5621e0a64d8bb671b/scene/gui/popup_menu.cpp#L522
It seems to replace the item name with the shortcut name?

**Comment by akien-mga** [comment] 2019-10-08 05:43
Duplicate of #25519.

**Closed by akien-mga** 2019-10-08 05:43 UTC
