### ISSUE TITLE
Renaming folders creates garbage files in partial(pck/zip) export

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#39475] opened 2020-06-12 07:13 UTC
**Godot version:**
3.2.2 beta4 official

**OS/device including version:**
Windows 10 64bits

**Issue description:**
If you have a scene (e.g.: res:/foo/bar.tscn) selected for partial export as part of a pck/zip file, each time you rename the folder the old path names are still included in the `export_files` property in export_presets.cfg, resulting in a pck/zip file with extra folders and empty tscn files. 

**Steps to reproduce:**
- create a new project
- create a folder named "foo" (it can be any name)
- create a new scene in res://foo/scene.tscn
- go to project->export and add a preset
- on the Resources tab choose "export selected scenes (and dependencies)
- tick the checkbox next to /foo/scene.tscn
- close the export windows and rename the "foo" folder to "foorenamed" (or any name)
- open the export window again and this time tick the checkbox next to /foorenamed/scene.tscn
- export as zip
Expected: 
In export_presets.cfg the `exported_files` field should be equal to `PoolStringArray( "res://foorenamed/scene.tscn" )` 
The zip file should contained the folder foo with the scene.tscn file inside
Actual:
In exports_presets.cfg the `exported_files` field is equal to `PoolStringArray( "res://foo/scene.tscn", "res://foorenamed/scene.tscn")` with another scene being added with every rename. 
The zip file will contain the folder foorenamed with a correct scene.tscn file and an extra folder foo with an empy scene.tscn file.

Workaround:
- close the editor
- manually remove the extra paths from `exported_files`
- reopen the project

I'm not sure if this can break a resource_pack but I can think of a case where unintended files get exported. 
- create res://a/scene.tscn and set it as partial export
- rename to res://b/scene.tscn and again, set it as partial export
- create res://a/scene.tscn
a/scene.tscn and all dependencies will get exported even if you only wanted to export b/scene.tscn

**Minimal reproduction project:**
It'd be best if you can reproduce it on a newly created project, but here's a video in case the reproduction steps aren't clear enough. 
https://streamable.com/y5vt51

**Comment by akien-mga** [comment] 2020-06-12 07:20
Duplicate of #39269, it should be fixed in 3.2.2 RC 1 that I'll release in a bit (downloads are on the repo already if you want to test).

**Closed by akien-mga** 2020-06-12 07:20 UTC
