### ISSUE TITLE
Cannot export animations from model to model

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot#36158] opened 2020-02-12 19:46 UTC
3.2.stable

windows 10

have 2 different models that have different meshes but same skeleton, wanted to update animations on older one by getting animations from new one

export animation from one newer model that has more animations and load it to older one, it will be messed with wrong rotations on some bones

That is critical and I have no idea what to do now, I'm sure that skeleton is same, because in blender I can freely CTRL+C poses on all bones and CTRL+V on older model without any issues

**Comment by Xylord** [comment] 2020-03-05 01:11
I can confirm I have the same issue. Currently looking for a workaround.

**Comment by Calinou** [comment] 2020-04-05 20:49
@Favkis @Xylord This should be addressed by #36415, please check.

**Comment by Calinou** [comment] 2020-05-26 08:29
Closing due to lack of response. Moreover, this is a duplicate of https://github.com/godotengine/godot/issues/15560.

**Closed by Calinou** 2020-05-26 08:29 UTC
Labels: topic:core
