### ISSUE TITLE
Pressing Toggle Comment shortcut while the script editor and shader editor are open will always toggle comment in the shader editor, no matter the current focused editor

### ISSUE THREAD

**Issue by AzadKshitij** [godotengine/godot#41472] opened 2020-08-23 14:55 UTC
**Godot version:**
Godot Engine v3.2.2.stable.official

**OS/device including version:**
OpenGL ES 3.0 Renderer: AMD Radeon(TM) Vega 8 Graphics

**Issue description:**
when I try to clear comment while both script editor and shader editor it comment line in shader editor even my pointer was present inside script editor.

  

![Godot Engine - Mobile RPG - Player tscn 2020-08-23 19-47-10](https://user-images.githubusercontent.com/54288405/90981414-7af8ff00-e57e-11ea-83a1-2199d86def06.gif)

**Steps to reproduce:**
open shader editor window and script editor window at same time and try to comment any line using shortcut "ctrl + k"
and it will comment line from shader editor

**Minimal reproduction project:**

**Comment by EricEzaM** [comment] 2020-08-23 22:13
Fixed by #39039 if it ever gets merged.

Anyhow, this is a duplicate of #17591.

**Comment by Calinou** [comment] 2020-08-26 13:15
Duplicate of #17591.

**Closed by Calinou** 2020-08-26 13:15 UTC
Labels: bug, topic:editor
