### ISSUE TITLE
Rotating camera seems to update visual distance to objects on screen

### ISSUE THREAD

**Issue by Ario99** [godotengine/godot#46085] opened 2021-02-16 05:39 UTC
Sorry if this is already a documented issue, I tried finding similar problems but couldn't find anything that I thought was actually the problem I had.

**Godot version:**
v3.2.3.stable.official

**OS/device including version:**

Windows 10
Nvidia 1060 GTX
Driver version 27.21.14.6079
GLES3

**Issue description:**
The visuals on object position after collision isn't updated properly until the player camera is rotated.

**Steps to reproduce:**
Create rigid bodies without any gravity and then create a player rigid body that can move forward (dependent on camera rotation) and implement a camera that can rotate in first person view for the player. Then head face first into one of the floating rigid bodies and watch as rotating the camera causes the rigid body to rapidly move away as if moving the camera somehow updates the distance between the camera and rigid body.

**Minimal reproduction project:**
I'm just adding the project I'm working on for this since it's still very much bare bones.
[Spacemen.zip](https://github.com/godotengine/godot/files/5986303/Spacemen.zip)

**Comment by pouleyKetchoupp** [comment] 2021-02-19 22:44
@Ario99 I'm not able to reproduce any issue with the camera rotation causing changes in how the rigid body behaves.

It looks like what's going on is your camera is slightly in front of your player's collision, so when colliding right into an asteroid, you can see the inside for a moment. Then the asteroid is pushed away and you start seeing it going away from the camera. Rotating the camera doesn't influence this behavior from what I've seen.

You can make things better by just putting your camera slightly back, inside the player's collision shape. Then you can either hide the player's mesh completely, or use camera cull mask property to make sure you don't see the player's mesh from the inside.

Let me know if that helps!

**Comment by Ario99** [comment] 2021-02-22 02:56
@pouleyKetchoupp I did what you said to see if it would do anything but it didn't seem to effect that issue. Here's a recording from my desktop.
[2021-02-21 20-54-02.zip](https://github.com/godotengine/godot/files/6019261/2021-02-21.20-54-02.zip)

**Comment by pouleyKetchoupp** [comment] 2021-02-22 16:47
@Ario99 It seems the two objects are moving the expected way after bumping into them, and shaking the camera is not affecting their movement. Can you describe in details the behavior you would expect in this scenario?

**Comment by pouleyKetchoupp** [comment] 2021-03-08 17:40
I'm going to go ahead and close this issue for now. But feel free to re-open anytime with more details about the expected behavior if there's still something that needs to be solved and I'll be glad to help.

**Closed by pouleyKetchoupp** 2021-03-08 17:40 UTC
Labels: needs testing, topic:physics
