### ISSUE TITLE
Text editor steals focus from "Find in Files" dialog

### ISSUE THREAD

**Issue by ghmart** [godotengine/godot#88847] opened 2024-02-26 03:38 UTC
### Tested versions

- Reproducible in 4.3-dev3.
- Not reproducible in 4.2.1-stable.

### System information

Godot v4.3.dev3 - Debian GNU/Linux 11 (bullseye) 11 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti () - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

Text editor steals focus ~when nothing is selected before invoking~ from "Find in Files" dialog.

### Steps to reproduce

1. Open any script. ~Don't select anything.~
2. Hit "Control + Shift + F" shortcut.

### My attempt to fix
Tried to investigate "editor/find_in_files.cpp" ("FindInFilesDialog::_notification") and found that if replace
	`callable_mp((Control *)_search_text_line_edit, &Control::grab_focus).call_deferred();`
with
	`_search_text_line_edit->grab_focus();`
the problem is gone.

Not sure about "Doesn't work more than once if not deferred..." comment. It works normally subsequently (at least on my Linux with v.4.3-dev3).

### Minimal reproduction project (MRP)

N/A

**Comment by pancelor** [comment] 2024-02-26 04:07
I also have this issue in 4.3-dev3 and not in 4.2.1-stable

I'm not at my computer right now; I'll get my exact specs later. But these should be correct -- I copied them from a recent github issue of mine:

> Manjaro Linux #1 SMP PREEMPT Sat Sep 23 10:10:02 UTC 2023 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (nvidia; 535.129.03) - AMD FX(tm)-8350 Eight-Core Processor (8 Threads)

**Comment by Sauermann** [comment] 2024-03-07 20:00
Bisected to 40d69c25d5b4238b6372d4c0f5fd10a8f0a64e9e #86441
CC @Mequam @dsnopek

**Comment by akien-mga** [comment] 2024-06-18 14:07
> Tried to investigate "editor/find_in_files.cpp" ("FindInFilesDialog::_notification") and found that if replace
> `callable_mp((Control *)_search_text_line_edit, &Control::grab_focus).call_deferred();`
> with
> `_search_text_line_edit->grab_focus();`
> the problem is gone.

Tested and this doesn't seem to work in current `master`.

CC @bruvzg @KoBeWi - maybe we can improve the Find in Files focus handling logic to make it less dependent on the timing of events.

**Comment by akien-mga** [comment] 2024-06-18 15:48
> (tried single window mode, as it can't even happen with multiple windows).

For me on Linux (Fedora 40, KDE Plasma on Wayland, X11 DisplayDriver) the issue is only reproducible with multiple windows actually, and not reproducible in single window mode.

**Comment by KoBeWi** [comment] 2024-06-18 15:51
Huh I tested with multiple windows and seems like you can focus the editor, it just doesn't accept input.
Still can't reproduce the bug though.

**Comment by dsnopek** [comment] 2024-06-27 20:55
This has been a little tricky for me to reproduce. It's not reproducible on my system (Ubuntu 22.04) with i3 (my usual environment) or GNOME. I used multiple window mode in both cases, and tried both Forward+ and Compatibility (above, someone said it happened for them only on Forward+ and not Compatibility).

However, I just setup a Fedora 40 VM in VirtualBox, and I _am_ able to reproduce the issue there! (using Compatibility, since getting Vulkan running in VirtualBox is a pain)

Strangely, that is also GNOME, however, it looks like it's running on Wayland and so using xwayland. I wonder if that's the difference? On my host machine, I'm using real X11 in order to take advantage of the proprietary nvidia drivers.

It'd be great if other folks who are experiencing this issue could share:

1. The name of their window manager or desktop environment?
2. Whether or not you're using real X11 or xwayland?

In any case, I'll experiment with some changes to the code that was committed in PR https://github.com/godotengine/godot/pull/86441 to see if I can find a workaround.

**Comment by akien-mga** [comment] 2024-06-27 21:54
I reproduce the issue on Fedora 40 KDE Plasma/KWin on Wayland myself, so using XWayland. I can test tomorrow if it's indeed not reproducible on the same system with KDE X11.

**Comment by dsnopek** [comment] 2024-06-27 22:34
I just posted draft PR https://github.com/godotengine/godot/pull/93682 which fixes the issue in my testing.

I don't know if it reintroduces the bugs that PR https://github.com/godotengine/godot/pull/86441 aimed to fix, though, and I'm going to attempt to determine that.

In any case, I'd appreciate it if other folks who are experiencing the bug described here could test if my PR fixes it for you as well!

**Closed** 2024-06-28 10:37 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting, regression
