### ISSUE TITLE
Arrays in gdscript sharing values improperly

### ISSUE THREAD

**Issue by gyrcom** [godotengine/godot#36520] opened 2020-02-24 21:17 UTC
Godot version 3.2
Linux Mint 19.2
**Issue description:**
I am importing data into my script using Sqlite. Works properly. When I populate a global array the info is also found in another global array that should be untouched
**Steps to reproduce:**
node1: autoload
`auto.gd````
extends Node
export(Array, Array, float) var colour = []
export(Array, String) var values = []
```
node.gd:
```
extends Node	
const SQLite = preload("res://lib/gdsqlite.gdns")# SQLite module
var item_list = []
func _ready():
	var db = SQLite.new()# Create gdsqlite instance
	db.open_db("res://godottest.db")
	var tablenames = db.fetch_array("SELECT name FROM sqlite_master WHERE type='table'") # Get table list from db
	var i = 0
	for tname in tablenames: # step through the tables
		auto.values.append(tname.name)
		
		
		# Add to item list
	print("Values  ", auto.values)
	print("Colour  ", auto.colour)
```

When I print auto.values and auto.colour I get the same results when the colour array was untouched.

Shortened for clarity

**Comment by Calinou** [comment] 2020-02-24 22:11
Duplicate of #16478

**Closed by Calinou** 2020-02-24 22:11 UTC

**Comment by gyrcom** [comment] 2020-02-25 03:31
Not the same problem.
Two different arrays ending up with the same information.
They are NOT copies of each other. They are two separate arrays.
Data in one array ends up in the other array.

**Comment by Calinou** [comment] 2020-02-25 08:11
@gyrcom My bad, this is actually a duplicate of #20436.
