### ISSUE TITLE
Vulkan: adding a texture causes a consoler spam.

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#49150] opened 2021-05-27 20:59 UTC
**Godot version:**
Godot night build

**OS/device including version:**
Win 10 64, AMD RX 480

**Issue description:**
adding a texture causes a consoler spam.
See vid: https://drive.google.com/file/d/1xEgbyLanm8EPrLhSzuOT4K4YvbvLsVYC/view?usp=sharing

**Comment by Calinou** [comment] 2021-05-27 21:05
Duplicate of https://github.com/godotengine/godot/issues/48886 (same cause).

**Closed by Calinou** 2021-05-27 21:05 UTC
