### ISSUE TITLE
ListView misbehaves in the Project Setting's Autoload tab

### ISSUE THREAD

**Issue by ultimateprogramer** [godotengine/godot#79652] opened 2023-07-19 08:57 UTC
### Godot version

4.1.1 Stable

### System information

Windows 11 - 4.1.1 Stable - Compatibility

### Issue description

When dealing with the Autoloads the List control renditions in an inconsistent fashion. Random borders and lines start showing up. As below:

![image](https://github.com/godotengine/godot/assets/177851/cf6d947b-32a7-45e5-b8f7-850fe6f7076e)

### Steps to reproduce

- Open Project Settings
- Navigate to the Autoload Tab
- Add Autoload Entries

or

- Open Project Settings
- Navigate to the Autoload Tab
- Select an item on the list

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-07-20 16:55
* Looks like a duplicate of #74115. Thanks for the report!

**Closed by dalexeev** 2023-07-20 16:55 UTC
