### ISSUE TITLE
texture progress progress texture becomes empty when the value is 100

### ISSUE THREAD

**Issue by TuxTheAstronaut** [godotengine/godot#56975] opened 2022-01-19 22:18 UTC
### Godot version

v3.4.2.stable

### System information

Pop!_OS 21.10 x86_6, GLES3

### Issue description

when a texture progress value is set to 100 the progress texture becomes invisible like if it was at 0

![image](https://user-images.githubusercontent.com/55007230/150222789-4a953428-2055-48ed-9da2-af814f0c4320.png)
![image](https://user-images.githubusercontent.com/55007230/150222808-b770e06a-8ec6-4067-83f6-545919beb842.png)

### Steps to reproduce

make a texture progress node and give it a back ground and a progress texture then play around when the value to see that it works. then set the progress value to 100 and the progress texture will become invisible 

### Minimal reproduction project

[Radial progress bug.zip](https://github.com/godotengine/godot/files/7900905/Radial.progress.bug.zip)

**Comment by Calinou** [comment] 2022-01-19 22:36
I can't reproduce this on `3.x` 4cadd50f0:

![image](https://user-images.githubusercontent.com/180032/150229480-2f727da1-a7ee-4124-b89e-4779d223cbef.png)

https://user-images.githubusercontent.com/180032/150229502-75e0e2f5-0dbe-4a05-8e68-13b91378d854.mp4

**Comment by TuxTheAstronaut** [comment] 2022-01-19 22:53
i tested it on 3.4.2 on both my mac and linux machine and got the same result

https://user-images.githubusercontent.com/55007230/150231384-7d8fe06b-1996-4f09-9438-d7203aa2cde7.mp4

**Comment by TuxTheAstronaut** [comment] 2022-01-19 23:02
but it dose work on godot 4

https://user-images.githubusercontent.com/55007230/150232285-54e3d5ee-d07b-4368-8bc9-e928caae1480.mp4

**Comment by Calinou** [comment] 2022-01-19 23:04
@TuxTheAstronaut Can you test 3.5beta1?

**Comment by raulsntos** [comment] 2022-01-19 23:12
I think this was fixed by #54345

**Closed** 2022-01-19 23:13 UTC
Labels: bug, topic:gui

**Comment by TuxTheAstronaut** [comment] 2022-01-19 23:17
works fine on 3.5

https://user-images.githubusercontent.com/55007230/150233695-7398b38a-97e1-44b7-a988-3f134b040d65.mp4
