### ISSUE TITLE
GIProbe allows light to pass though walls

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#12024] opened 2017-10-11 12:20 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 17.0.5
Godot 3.0 Master Build
NVidia GT540M, driver 384.90

**Issue description:**

GIProbe produces light "artifacts". If bias is setted to 0 it produces artifacts. If bias is setted to default 1.5 the the light passes though the walls.

BIAS 1.5
![screenshot_2017-10-11_15-10-33](https://user-images.githubusercontent.com/13662414/31440092-5a59039c-ae97-11e7-9e9d-e6526544b42a.png)

BIAS 0
![screenshot_2017-10-11_15-16-39](https://user-images.githubusercontent.com/13662414/31440127-79d21ee8-ae97-11e7-9b44-1c9cd4b8f056.png)

**Steps to reproduce:**
Any light with shadow with a range going beyond a wall and a GIProbe.

Run the example, and play with the range of the Omni light or with the bias of GIProbe.

**Link to minimal example project:**
[GIProbe.zip](https://github.com/godotengine/godot/files/1375518/GIProbe.zip)

**Comment by reduz** [comment] 2017-10-11 13:08
Should be fixed (or compensated) in Godot 3.1 with anisotropy setting..

**Comment by tagcup** [comment] 2017-11-17 15:56
@reduz Is that going to be an anisotropy setting for the GIProbe itself?

(BTW, I couldn't find much documentation on GIProbe, it might be a good idea to have a dedicated doc or tutorial on it since it's one of the strong selling points of Godot 3.)

**Comment by reduz** [comment] 2017-11-17 16:33
@tagcup Ah, I was planning on writing docs on lighting techniques before Beta is out, guess I should work on that ASAP.

**Comment by reduz** [comment] 2017-11-17 16:36
@tagcup Regarding Anisotropy, there are two ways of doing it. 

The first is having a cubemap array, so you have lighting info for each voxel face, which means increasing the probe size by 6

The second (what I will do) is adding a RGB565 cubemap array of two elements which contains the lighting distribution on each voxel face. This has the problem that, for colored light, you can get color bleeding for lights on both sides, but It's not too bad honestly.

**Comment by tagcup** [comment] 2017-11-17 16:57
@reduz Ah, didn't realize you were planning for a wider topic (lighting techniques), that'd be awesome since a lot of the settings in light-related nodes are mystery to users.
I'm pretty sure there are higher-priority tasks before the feature-freeze, but you know your schedule best.

So about the cubemaps, what exactly is going to be anisotropic?

**Comment by reduz** [comment] 2018-09-05 21:27
Did not have time to fix this for 3.1, given no rendering changes will be made pending port to Vulkan.
Kicking to 3.2

**Comment by Adinimys** [comment] 2020-02-01 21:51
I got a similar issue with OmniLight without even using GIProbe. I saw no one reporting it so I don't know if I should file a new bug report or simply post here as it is very similar.

This is how it looks in my game :
![godot_light_bleed](https://user-images.githubusercontent.com/8863312/73599510-90f09500-4544-11ea-92c4-53d1be55fdab.png)

And the project to reproduce it :+1: 
[LightBleedExample.zip](https://github.com/godotengine/godot/files/4143273/LightBleedExample.zip)

After searching for the cause of my issue tested various solutions. I tried various settings like increasing the wall thickness, adjusting the biais, switching shadow casting to double-sided...
Nothing fixes it.
The only work around I found is to try to adjust the render layer of objects that shouldn't be affected to move them in a layer that isn't affected by the light. But it's messy and probably not the intended solution.


So, sorry for bumping an old thread but considering I encountered the same issue without any GIProbe I figured that maybe the title should be changed ?

**Comment by Calinou** [comment] 2020-02-02 00:31
@Adinimys This is unrelated to GIProbe. Please ask in one of the other [community channels](https://godotengine.org/community) instead, as I don't think this is a bug (it could be an issue with your wall model).

**Comment by Adinimys** [comment] 2020-02-02 06:44
I forgot to mention that I asked on Discord before posting here. I was told there by two users that looked at my project that they couldn't fix it and that it looked like a bug and that I should come post on Github.

About my mesh being manifold. I followed these advices : https://blender.stackexchange.com/questions/7910/what-is-non-manifold-geometry and I think that it's ok. I found no issues. It seems suitable to me. You can take a look at it here :
[walls.blend.zip](https://github.com/godotengine/godot/files/4143626/walls.blend.zip)

**Comment by clayjohn** [comment] 2020-02-02 07:29
@Adinimys I looked into your reproduction project. The reason you are seeing some color on the back of the walls is because you have your shadows to set to gray instead of black. Gray shadows let some light through (which is the entire point of having gray shadows). If you don't want color in the shadows area, set your shadow color to black.

**Comment by Adinimys** [comment] 2020-02-02 12:24
Damn. What a stupid mistake. Sorry for wasting your time with that :/

**Comment by akien-mga** [comment] 2020-02-05 13:18
Ah nevermind, I hadn't seen that the now-resolved https://github.com/godotengine/godot/issues/12024#issuecomment-581072895 was added to a pre-existing valid report.

**Comment by Calinou** [comment] 2020-07-02 07:31
This was resolved to an extent in the new Vulkan renderer (after enabling anisotropy in GIProbe), closing. Also, the new lightmapper should be leak-free and SDFGI can be made more resistent to leaks by enabling occlusion (at the cost of performance).

In any case, you may have to design your level around it by making walls thick enough when possible. (This is generally the case in any game engine out there.)

**Closed by Calinou** 2020-07-02 07:31 UTC
Labels: bug, topic:rendering
