### ISSUE TITLE
VisualScript Connect bool from function to node without exec line causes crash

### ISSUE THREAD

**Issue by boltfox20** [godotengine/godot#43418] opened 2020-11-09 16:57 UTC
It might have already been reported, but I don't see it in the list.

I am new to Godot and VisualScripting. That being said, I tried to do something that - in hindsight - seems pretty silly; I tried to connect a function argument bool to a condition bool without connecting the exec line. I would have expected to get an error message telling me that it has to be connected by the exec line before the bool can be connected, instead it crashed and quit. Took a half hour to find the exact reason, but it seems that if the condition node has never been connected to the function node, trying to connect the bool will always crash it. However, after having that node connected, even once, the bool is able to be connected regardless of exec line condition. Since I did get an error message for trying to save the program without the condition node being connected to a function, I am thinking it might have something to do with trying to update a node that has not been officially added to the VisualScript file that also cannot currently be added to the file due to a separate error. The constant attempts likely cause a feedback loop of attempts that overload the program.

Here is the very basic code that broke the program:
![GodotCrash 2020-11-09 110116](https://user-images.githubusercontent.com/4684411/98571882-fff0dc00-2282-11eb-8158-646a9a2da8ba.png)

![image](https://user-images.githubusercontent.com/4684411/98572131-434b4a80-2283-11eb-8f8e-078bc1fff25a.png)
![image](https://user-images.githubusercontent.com/4684411/98572165-5100d000-2283-11eb-8d50-96c8b0b0ef58.png)
![image](https://user-images.githubusercontent.com/4684411/98572192-59590b00-2283-11eb-8ddb-7bd361eca2c0.png)
![image](https://user-images.githubusercontent.com/4684411/98572273-6ece3500-2283-11eb-9029-97d48c1b7a09.png)

**Comment by Calinou** [comment] 2020-11-09 17:27
@boltfox20 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by boltfox20** [comment] 2020-11-09 18:59
I couldn't replicate it in a blank project, but removing as much unrelated stuff as possible has yielded interesting observations.

If I remove the "_ready" Function node, it works fine. If I save after making the Condition node but before attaching the bool, sometimes it works, sometimes not. Also, for a split second, renaming the folder the project is in seemed to fix it, as well, and then trying to replicate **that** result proved impossible. I have renamed the functions and the bool argument without altering the results, as well. Also, I originally had the project in a folder inside the Godot Engine folder (I made a "projects" folder to put my project folders in), so I moved it to my desktop, where the blank project was being saved and the crash remained. I also tested it after unzipping the file I'm sending you. It worked the first time. Closing Godot without saving, then reopening brought back the crash. I have added a comment to the script with the steps to recreate the bug.

If it doesn't crash for you, I can send a video of me attempting it.
[Bug Replicate.zip](https://github.com/godotengine/godot/files/5512675/Bug.Replicate.zip)

**Comment by boltfox20** [comment] 2020-11-09 19:01
Just to be sure, this screenshot is just before releasing the mouse button, causing the crash.
![image](https://user-images.githubusercontent.com/4684411/98584524-ff147600-2293-11eb-8d60-8b147e8bb46e.png)

**Comment by qarmin** [comment] 2020-11-29 19:39
Backtrace
```
ERROR: add_node: A function node has already been set here.
   At: modules/visual_script/visual_script.cpp:331.
ERROR: get_node: Condition "!func.nodes.has(p_id)" is true. Returned: Ref<VisualScriptNode>()
   At: modules/visual_script/visual_script.cpp:409.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f097402f210] (??:0)
[2] VisualScriptEditor::_update_graph_connections() (/mnt/Miecz/godot3.2/modules/visual_script/visual_script_editor.cpp:457)
[3] VisualScriptEditor::_update_graph(int) (/mnt/Miecz/godot3.2/modules/visual_script/visual_script_editor.cpp:866)
[4] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (/mnt/Miecz/godot3.2/core/undo_redo.cpp:294 (discriminator 4))
[7] UndoRedo::redo() (/mnt/Miecz/godot3.2/core/undo_redo.cpp:338)
[8] UndoRedo::commit_action() (/mnt/Miecz/godot3.2/core/undo_redo.cpp:260)
[9] VisualScriptEditor::_graph_connected(String const&, int, String const&, int) (/mnt/Miecz/godot3.2/modules/visual_script/visual_script_editor.cpp:3029 (discriminator 1))
[10] MethodBind4<String const&, int, String const&, int>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:3115 (discriminator 33))
[11] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[12] Object::emit_signal(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/core/object.cpp:1246 (discriminator 1))
[13] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:1304)
[14] GraphEdit::_top_layer_input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/gui/graph_edit.cpp:558 (discriminator 9))
[15] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[16] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[17] Object::emit_signal(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/core/object.cpp:1246 (discriminator 1))
[18] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:1304)
[19] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:1680 (discriminator 1))
[20] Viewport::_gui_input_event(Ref<InputEvent>) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:2068 (discriminator 3))
[21] Viewport::input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:2858 (discriminator 2))
[22] Viewport::_vp_input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:1452)
[23] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[24] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[25] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:846)
[26] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:275)
[27] SceneTree::input_event(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:431 (discriminator 5))
[28] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/mnt/Miecz/godot3.2/main/input_default.cpp:416)
[29] InputDefault::parse_input_event(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/main/input_default.cpp:260)
[30] InputDefault::flush_accumulated_events() (/mnt/Miecz/godot3.2/main/input_default.cpp:679)
[31] OS_X11::process_xevents() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:2241)
[32] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3408)
[33] godot(main+0x125) [0x138258b] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[34] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f09740100b3] (??:0)
[35] godot(_start+0x2e) [0x13823ae] (??:?)
```

**Comment by boltfox20** [comment] 2020-11-30 04:44
... Okay... So, you guys are still working on it, then? It's happened many
times since then. The only commonality has been connecting the variables of
a node before connecting it to the sequence line.

**Comment by qarmin** [comment] 2020-11-30 06:04
Looks that is a duplicate of #41737

**Closed by qarmin** 2020-11-30 06:04 UTC
Labels: bug, confirmed, crash, topic:visualscript
