### ISSUE TITLE
GDScript tokenizer error when typing brackets in a string literal

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#42199] opened 2020-09-19 19:21 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows

**Issue description:**

when writing code with string literals (single- or multiline strings) that contain brackets (of any kind - round, square, curly), I  often get
```modules/gdscript/gdscript_tokenizer.cpp:1129 - Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()```

**Steps to reproduce:**
1. create a GDScript script (`Filesystem` - right click on empty space  - `New Script`)
2. remove all the code (`Ctrl+A` - `Delete`)
3. write `""`
4. write `()` inside `""`
the script result source code could be
```gdscript
"()"
```

and you will see godot tokenizer error in `Output`

the same is for 
```
'()'
```
```
"""
()
"""
```
and for `[]` and `{}` instead of `()`

The error doesn't occur for example in these cases:
- `var x = "()"`
- `"()"` that is pasted from clipboard

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-09-19 20:06
Duplicate of https://github.com/godotengine/godot/issues/35994.

**Closed by Calinou** 2020-09-19 20:06 UTC
Labels: bug, topic:gdscript
