### ISSUE TITLE
If you alt-tab off and in the editor and you drag a sprite it will act like if alt were pressed

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12592] opened 2017-11-02 18:26 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master c880302 Windows 10

**Issue description:**

![https://i.imgur.com/fYKnEfW.gifv](https://i.imgur.com/fYKnEfW.gif)

I didn't press alt the second time I dragged the sprite.

**Steps to reproduce:**
1. alt-tab off and in the editor
2. Drag a sprite into the editor's viewport without pressing alt

**Comment by akien-mga** [comment] 2019-01-19 11:10
Might be a duplicate of #10949?

**Comment by akien-mga** [comment] 2019-11-26 12:43
I can't reproduce it on Linux. Is this still reproducible on Windows?

**Comment by tom-jk** [comment] 2020-08-06 15:33
Testing on linux mint 18.3.

- Can reproduce in 3.0 thru 3.1.2.
  If you press and release the Alt key once more after returning to Godot but before you release the mouse, the behaviour is correct. Presumably Godot will only acknowledge the key-up when focused.

- Can't reproduce in 3.2, 3.2.3.rc3.

Issue appears to be resolved.

**Comment by Calinou** [comment] 2020-08-06 16:30
Closing as resolved per @tom-jk's comment.

**Closed by Calinou** 2020-08-06 16:30 UTC
Labels: bug, topic:editor
