### ISSUE TITLE
Godot 3.2.2 mono stable - Can't create new scripts or extend in inspector

### ISSUE THREAD

**Issue by laGrossePistache** [godotengine/godot#41620] opened 2020-08-30 12:33 UTC
**Godot version:**
Godot 3.2.2 mono stable

**OS/device including version:**

Windows 10 with Ryzen 4700u cpu / GLES2 and GLES 3

**Issue description:**

With mono version only, I can't create or extend a new script in the inspector. Nothing happen when i click on create or extend.. It's only work when I create the script in the filesystem by right click and create script.

It is the same on every project I create.

**Steps to reproduce:**
- Create a new project, a new node and try to create a new script in the node's inspector.
[mono issue.zip](https://github.com/godotengine/godot/files/5146766/mono.issue.zip)

**Minimal reproduction project:**

**Comment by laGrossePistache** [comment] 2020-08-30 12:37
I have delete my AppData\Roaming\Godot directory and it's now working! Sorry !

**Comment by laGrossePistache** [comment] 2020-08-30 13:34
Finally, the issue has come back.. I don't really know why !

**Comment by aaronfranke** [comment] 2020-09-26 01:15
@IaGrossePistache I can't reproduce this on Linux with either Godot 3.2.2 or Godot 3.2.3. I can create scripts in the inspector just fine. This issue is probably specific to your computer. It seems strange that a Godot editor feature would only break on the Mono version, but I have to ask, what version of Mono do you have installed? Also, are you able to run the projects fine?

**Comment by laGrossePistache** [comment] 2020-10-02 15:01
I upgrade to Godot 3.2.3 and it has never happen again, so I think we can close this issue

**Comment by akien-mga** [comment] 2020-10-02 15:19
Thanks, closing then.

**Closed by akien-mga** 2020-10-02 15:19 UTC
Labels: bug, needs testing, topic:editor, topic:mono
