### ISSUE TITLE
can't add new .png files

### ISSUE THREAD

**Issue by shrunkenmaster** [godotengine/godot#65980] opened 2022-09-17 11:52 UTC
### Godot version

4.0 beta1

### System information

Windows 10, Vulkan API 1.2.0, NVIDIA GeForce GTX 1050 Ti

### Issue description

Cannot add any .png files to res:// folder. All existing .png files from alpha17 project are fine.
<img width="131" alt="Screenshot 2022-09-17 124619" src="https://user-images.githubusercontent.com/77408850/190855173-b76f9407-39e0-440f-8155-ccff50aac441.png">

### Steps to reproduce

Add a file directly into folder on desktop, or drag file into editor filesystem.
File shows with red cross.
<img width="131" alt="Screenshot 2022-09-17 124619" src="https://user-images.githubusercontent.com/77408850/190855238-131f51e0-bdb4-4b61-bdfb-9aea94a6d30e.png">

**Comment by gotnospirit** [comment] 2022-09-17 12:04
Can't reproduce with 4.0.beta or custom build 95df3e7c on Windows 10.
Tried using drag&drop and also directly copy the file in the directory.

Is editing the png with paint.net ok?

**Comment by KoBeWi** [comment] 2022-09-17 12:18
Any minimal project?
Also try to remove `.godot` folder (make sure to close Godot before doing that).

**Comment by shrunkenmaster** [comment] 2022-09-18 14:48
png files are fine outside of engine, ie. Aseprite/Paint.
Deleted the folder containing the bad .png and recreated it, seems to work fine now.

**Comment by KoBeWi** [comment] 2022-09-18 15:08
I think this is a duplicate of #58131, so closing.

**Closed by KoBeWi** 2022-09-18 15:08 UTC
Labels: bug, topic:editor, needs testing, topic:import
