### ISSUE TITLE
Animation tree not working at all

### ISSUE THREAD

**Issue by MaxEinDax** [godotengine/godot#69223] opened 2022-11-26 18:43 UTC
### Godot version

4.0 beta 6

### System information

Windows 11, nothing special

### Issue description

The animations in the animation tree are not working

### Steps to reproduce

add multiple 2d animations and connect them in an animation tree

### Minimal reproduction project

Not the time for that

**Comment by TokageItLab** [comment] 2022-11-27 04:24
Duplicate of #69066

**Closed by TokageItLab** 2022-11-27 04:24 UTC
