### ISSUE TITLE
Cannot define variable with name 'name' and 'value' in C# Class

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#68249] opened 2022-11-04 11:14 UTC
### Godot version

4.0-beta4

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

error:
E:\GodotProjects\Godot4Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\TestObject_ScriptProperties.generated.cs(19,13): 无法分配到 变量 'in godot_string_name' ，因为它是只读变量
E:\GodotProjects\Godot4Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\TestObject_ScriptProperties.generated.cs(23,13): 无法分配到 变量 'in godot_variant' ，因为它是只读变量
E:\GodotProjects\Godot4Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\TestObject_ScriptProperties.generated.cs(35,79): 参数 1: 无法从“Godot.NativeInterop.godot_string_name”转换为“string?”
E:\GodotProjects\Godot4Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\TestObject_ScriptProperties.generated.cs(39,78): 参数 1: 无法从“Godot.NativeInterop.godot_variant”转换为“double”
E:\GodotProjects\Godot4Test\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\TestObject_ScriptProperties.generated.cs(39,78): 使用了未赋值的 out 参数“value”

This code build failed

```csharp
using System;
using System.Collections.Generic;


public partial class TestObject : Godot.RefCounted
{
    public string id;
    public string name;
    public double value;

    public TestObject()
    {
    }
}

```

But can use 'Name' and 'Value'

### Steps to reproduce

Look uploaded project

### Minimal reproduction project
[Godot4Test.zip](https://github.com/godotengine/godot/files/9937672/Godot4Test.zip)

_No response_

**Comment by raulsntos** [comment] 2022-11-04 11:17
Duplicate of https://github.com/godotengine/godot/issues/66819

**Closed by raulsntos** 2022-11-04 11:17 UTC
