### ISSUE TITLE
Vulkan: GPUParticles3D crash when duplicating 128 at once

### ISSUE THREAD

**Issue by solek1312** [godotengine/godot#70607] opened 2022-12-27 00:26 UTC
### Godot version

4.0 Beta 10

### System information

Linux Mint 21, Vulkan, Intel Iris Xe (Intel i5-1135G7)

### Issue description

Godot throws this pair of errors two times when "Z-Billboard" or "View Depth" flags are checked in GPUParticle3D properties, and when you switch to a scene that contains them:

```
E 0:03:11:0898   compute_list_bind_uniform_set: Condition "!uniform_set" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7807 @ compute_list_bind_uniform_set()
E 0:03:11:0898   compute_list_dispatch: Uniforms were never supplied for set (2) at the time of drawing, which are required by the pipeline
  <C++ Error>    Method/function failed.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8006 @ compute_list_dispatch()
```

Also, whenever there's a big enough amount of such particle system nodes in the scene (in reproduction project it's between 128 and 256), Godot freezes, console showing errors:

```
ERROR: Only one draw/compute list can be active at the same time.
   at: compute_list_begin (drivers/vulkan/rendering_device_vulkan.cpp:7715)
ERROR: Only one draw/compute list can be active at the same time.
   at: compute_list_begin (drivers/vulkan/rendering_device_vulkan.cpp:7715)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_compute_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7728)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_compute_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7728)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_set_push_constant (drivers/vulkan/rendering_device_vulkan.cpp:7946)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_dispatch_threads (drivers/vulkan/rendering_device_vulkan.cpp:8026)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7792)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_set_push_constant (drivers/vulkan/rendering_device_vulkan.cpp:7946)
ERROR: Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
   at: compute_list_dispatch_threads (drivers/vulkan/rendering_device_vulkan.cpp:8026)
ERROR: Condition "!compute_list" is true.
   at: compute_list_end (drivers/vulkan/rendering_device_vulkan.cpp:8117)
```

Could be related to [#63315](https://github.com/godotengine/godot/issues/63315) as I'm also using Linux on an integrated Intel GPU.

### Steps to reproduce

1. Make any working particle system
2. Check "View Depth" flag in draw order OR "Z-Billboard" flag in transform align
3. Switch to scene with the particle system from any other scene to get "Uniforms were never supplied" error message
4. Duplicate particled systems (whether instances or local) until there is ~128-256 of them to get the freeze

### Minimal reproduction project

[testdebug.zip](https://github.com/godotengine/godot/files/10305085/testdebug.zip)

**Comment by lostminds** [comment] 2023-01-23 10:30
Could this be related? https://github.com/godotengine/godot/issues/61516 Seems like it's the same error messages, but with some further clues and now a linked PR

**Comment by clayjohn** [comment] 2023-01-23 16:19
@lostminds I'm not sure if they are the same issue. #61516 is an issue with the Material attached to the GPUParticles' Mesh, while this Issue is related to a property of the GPUParticles itself.

**Comment by lostminds** [comment] 2023-01-23 16:59
> @lostminds I'm not sure if they are the same issue. #61516 is an issue with the Material attached to the GPUParticles' Mesh, while this Issue is related to a property of the GPUParticles itself.

Ok, well, I hope this issue can be resolved. As far as I can tell the billboarding still works as intended in this case, but I'd rather not use something that generates this kind of error each time an effect scene is loaded. I would try with CPUParticles3D instead, but it seems there is no billboarding option there anymore in 4.0beta14

**Comment by clayjohn** [comment] 2023-01-23 21:03
The first bug in this issue (the two error prints when changing scenes) is fixed by https://github.com/godotengine/godot/pull/71925

I debugged the second bug here and, as it turns out, the crash is caused by adding 128 GPUParticles to the scene at once rather than having 256 in the scene. I could reproduce the crash by doubling the the number of particles in the scene with ctrl+d (crashed when copying 128 particles and duplicating), but I could not reproduce the crash when duplicating only 64 at a time. I easily was able to have over 300 in the scene. Updating PR title and milestone accordingly

**Comment by 1029chris** [comment] 2023-04-28 04:20
We're ran into this issue for our project, instantiating particles using "Z-Billboard" would spam the logs and randomly crash the game. We have a system that instantiates a collection of various particles to be used globally, like a splash or puff of smoke, but we don't spawn 128 of any of them.

**Comment by clayjohn** [comment] 2023-04-28 05:46
@1029chris It sounds like you may have a different issue. This issue is pretty specific, it results in a hard crash when duplicating 128 particles or more at once. It doesn't spam the logs, it just crashes without printing anything. 

You should open a new bug report and include all the requested info as well as a minimal reproduction project so others can try to reproduce and solve the issue that you face

**Comment by 1029chris** [comment] 2023-04-28 21:39
@clayjohn Perhaps, but the logs shown here for the freezing is very similar to what we got as well. The frame would hitch and inputs would be eaten. I have a hunch whatever fixes this issue will also fix ours. We ended up removing "Z-Billboard" from all our particles, and we're not crashing or getting log spam anymore.
![image](https://user-images.githubusercontent.com/15712599/235258252-00747389-961e-40cb-b86b-62a6216a6986.png)

**Comment by zicman666** [comment] 2023-05-08 10:21
> @clayjohn Perhaps, but the logs shown here for the freezing is very similar to what we got as well. The frame would hitch and inputs would be eaten. I have a hunch whatever fixes this issue will also fix ours. We ended up removing "Z-Billboard" from all our particles, and we're not crashing or getting log spam anymore. (I'm very thankful for this issue existing, I'm not sure we would have found the source of the crashes without it!) ![image](https://user-images.githubusercontent.com/15712599/235258252-00747389-961e-40cb-b86b-62a6216a6986.png)

Hello, I dont find the "Z-Billboard", where can i find it ?
I have the same errors all the time in my game.
When I load a level, when i use particles, when i queue_free sprite_3D , when i have particle collision boxes ... i'm going to be crazy ...

**Comment by Calinou** [comment] 2023-05-08 16:01
I think they're referring to Y-Billboard.

**Comment by zicman666** [comment] 2023-05-08 19:01
> I think they're referring to the billboard mode property set to Y-Billboard.
Thank you ... unfortunatly i have already tried all the billboard setting.

**Comment by Travh98** [comment] 2023-06-10 14:36
I had this issue when running one big GPUParticles3D emitting 1000 particles alongside 100 smaller GPUParticles3D each emitting 3 particles. I had Billboard enabled in the ParticleProcess Material, and crashed with the "compute_list" errors.
I then disabled Billboard in the ParticleProcess material and instead enabled it in my Draw Pass 1 Mesh's material, and I haven't crashed since.

**Comment by IvanIG3** [comment] 2023-06-20 10:46
I also found this bug. At a random time, Godot freezes and throws a bunch of errors. I'm using Godot 4.0.3.

![godot_bug](https://github.com/godotengine/godot/assets/54667250/9be2f83a-794e-4f30-a505-794dee4e4d0d)

**Comment by zicman666** [comment] 2023-06-20 15:54
> I also found this bug. At a random time, Godot freezes and throws a bunch of errors. I'm using Godot 4.0.3.
> 
> ![godot_bug](https://user-images.githubusercontent.com/54667250/247090964-9be2f83a-794e-4f30-a505-794dee4e4d0d.PNG)

At Random time, like me. Impossible to understand why ... I gave up my project ...

**Comment by IvanIG3** [comment] 2023-06-25 16:25
> @IvanIG3 @zicman666 If you aren't duplicating a lot of nodes, these are likely unrelated issues. Please open a separate issue with a minimal reproduction project attached, and describe what you were trying to achieve there.

I'd like to make a minimal reproduction project with this bug, but I don't know why is this happening and where the error comes from. I don't even know what the error message means, so I have no clue what I need to replicate the bug in a minimal reproduction project. Could someone bring some light? so I can understand what's going on and I'll try to isolate the bug from my project into a minimal reproduction project.
Thanks!

**Comment by zicman666** [comment] 2023-06-25 19:03
I have the same problem.
In my game sometimes i have these errors with Sprite3D, sometimes Particles, textures, 3d objets ... i have tried to change soooooooooo many settings during 2 months ... and finally as i said before  I gave up my project ... (my game is on itchio but to avoid the bug i have deleted too many features).

**Comment by IvanIG3** [comment] 2023-07-03 11:03
Sometimes, when Godot crashes and throws all the _COMPUTE_LIST_ errors to the console, at the end of it there are two more errors that seems related to #71929.

![error](https://github.com/godotengine/godot/assets/54667250/27cdbbb3-1d4a-417e-bc01-d2ced5a11b02)

**Comment by krazyjakee** [comment] 2023-07-20 20:38
To confirm, the workaround is to set particle draw order from DRAW_ORDER_VIEW_DEPTH to DRAW_ORDER_INDEX (or any other setting).

Not ideal but it is a workaround.

**Closed** 2023-07-24 17:40 UTC
Labels: bug, topic:rendering, confirmed, topic:3d, topic:particles

**Comment by idchlife** [comment] 2023-08-16 14:29
> To confirm, the workaround is to set particle draw order from DRAW_ORDER_VIEW_DEPTH to DRAW_ORDER_INDEX (or any other setting).
> 
> Not ideal but it is a workaround.

Does not work for me.

I have thousands of errors in output when scene opened. Particles are set to DRAW_ORDER_INDEX.

Transform Align: Z-Billboard

```sh
 Only one draw/compute list can be active at the same time.
  drivers/vulkan/rendering_device_vulkan.cpp:7748 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7966 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8046 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8194 - Condition "!compute_list" is true.
  Only one draw/compute list can be active at the same time.
  drivers/vulkan/rendering_device_vulkan.cpp:7748 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7966 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8046 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8194 - Condition "!compute_list" is true.
  Only one draw/compute list can be active at the same time.
  drivers/vulkan/rendering_device_vulkan.cpp:7748 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7812 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:7966 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8046 - Condition "p_list != ID_TYPE_COMPUTE_LIST" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8194 - Condition "!compute_list" is true.
```
