### ISSUE TITLE
Editing the path of a node in a TypedArray of type Object fails

### ISSUE THREAD

**Issue by AeioMuch** [godotengine/godot#90302] opened 2024-04-06 11:53 UTC
### Tested versions

- Reproducible in 4.2.1.stable and later, haven't tested before but it's probably there since the introduction of the feature.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When trying to edit the path of a node in a typed array of Object, it fails and give the following message :

```
  Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```

https://github.com/godotengine/godot/assets/75151379/f79acf21-d147-4c68-b40e-13a456709ef8

I discovered this while working on the batch drag and drop PR.
PS : On a side note, I think it is probably the cause of another bug when using the AnimationPlayer, when it RESET the track, the array keep its size, but with empty slots. I think it's a plausible theory because this issue is not happening with typed array of NodePaths.

### Steps to reproduce

1. Add a node in the typed array of Object
2. Click the 3 dots and press `Edit`
3. Change the path to another valid node
4. Observe it fails and print the error message

### Minimal reproduction project (MRP)

[EditPathBug.zip](https://github.com/godotengine/godot/files/14893402/EditPathBug.zip)

**Comment by ajreckof** [comment] 2024-04-06 20:35
duplicate of #89065

**Closed** 2024-04-06 20:42 UTC
Labels: bug, topic:editor, needs testing
