### ISSUE TITLE
Godot 4: Editor menus appear in the center of the screen

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#66884] opened 2022-10-04 14:28 UTC
### Godot version

4.0 beta2

### System information

macOS ARM

### Issue description

When opening menus in the editor, they appear in the center of the screen instead at the drop down position they should.

https://user-images.githubusercontent.com/203453/193846379-33ec086d-2c94-44c4-a7a7-b6489b5c0bb7.mov

### Steps to reproduce

Open a menu.

**Comment by Zireael07** [comment] 2022-10-04 16:56
99% certain this issue was already reported but I can't find the #. Was likely a DisplayServer regression

**Comment by bruvzg** [comment] 2022-10-04 17:09
I can't reproduce it on M1 mac. Probably related to the recent changes to prevent popups from showing outside the screen.

What's your display configuration? Please provide `system_profiler SPDisplaysDataType` command output.

**Comment by dploeger** [comment] 2022-10-04 17:26
```
Graphics/Displays:

    Apple M1 Pro:

      Chipset Model: Apple M1 Pro
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 16
      Vendor: Apple (0x106b)
      Metal Family: Supported, Metal GPUFamily Apple 7
      Displays:
        LEN P27h-10:
          Resolution: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
          UI Looks like: 2560 x 1440 @ 60.00Hz
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
        Color LCD:
          Display Type: Built-in Liquid Retina XDR Display
          Resolution: 3024 x 1964 Retina
          Mirror: Off
          Online: Yes
          Automatically Adjust Brightness: Yes
          Connection Type: Internal
        LEN P27h-10:
          Resolution: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
          UI Looks like: 2560 x 1440 @ 60.00Hz
          Mirror: Off
          Online: Yes
          Rotation: Supported
```

**Comment by dploeger** [comment] 2022-10-04 17:28
Ah, you're right. It only occurs when I'm connected to my two external monitors. It works without them.

**Comment by dploeger** [comment] 2022-10-04 17:28
It even works when I'm connected, but the Godot window is on the internal screen.

**Comment by Cykyrios** [comment] 2022-10-04 18:29
Are you using the Single Window mode? This should only happen in this mode, and should be fixed by #66712, which will be in the next beta.
Related to #66707, #66691 and a few other.

**Comment by dploeger** [comment] 2022-10-04 18:37
Hm. I guess I do. Didn't go into that yet. Thanks.

**Comment by Gatada** [comment] 2022-10-05 10:30
I see this on my MacBok M1 Max setup with two screens, running Godot 4b2 on macOS Monterey 12.6.

https://user-images.githubusercontent.com/326334/194039600-4a69634d-b2b1-49f0-ac05-695774c0094e.mov

I still haven't worked out when it happens, as after launch Godot initially shows the popups at correct location:

<img width="238" alt="Screenshot 2022-10-05 at 11 28 38" src="https://user-images.githubusercontent.com/326334/194039838-a279a846-1905-4619-b78d-cd74e7fdc859.png">

**Comment by Gatada** [comment] 2022-10-05 10:45
Hm, I just changed the display setup, but connecting a new screen. After that - Godot is showing the popups at the wrong location. I **think** the other times it happened, was also because I disconnected my second screen..

<img width="929" alt="Screenshot 2022-10-05 at 11 43 44" src="https://user-images.githubusercontent.com/326334/194042443-dcd9eecf-6ccd-4ab9-ad54-d0a2502c8d10.png">

**Comment by clayjohn** [comment] 2022-11-04 17:44
Could someone who was able to reproduce this issue please test in Beta 4 and see if it has indeed been fixed?

**Comment by SoapSpangledGames** [comment] 2022-11-11 18:11
I was having this issue with Beta 2 on Linux, and it no longer happens in Beta 4.

**Comment by akien-mga** [comment] 2022-11-11 20:02
Thanks, closing as fixed.

**Closed by akien-mga** 2022-11-11 20:02 UTC
Labels: bug, platform:macos, topic:gui
