### ISSUE TITLE
Flashing Black?

### ISSUE THREAD

**Issue by Giggysman** [godotengine/godot#50491] opened 2021-07-15 15:45 UTC
### Godot version

3.3 Stable

### System information

Windows 10, Intel i5 gen 7 620 Hd graphics, GLES3

### Issue description

So when i make a custom material or texture in a scene and add that scene into another scene Everything with that material flashes black during playtesting and in the editor. It gets worse the more i edit the scene.

### Steps to reproduce

Just add a simple material to a mesh instance.

### Minimal reproduction project

[TestBug.zip](https://github.com/godotengine/godot/files/6824491/TestBug.zip)

**Comment by Calinou** [comment] 2021-07-15 16:02
Can you reproduce this after switching to the GLES2 backend in the Project Settings (**Rendering > Quality > Driver > Driver Name**)?

Also, can you take some screenshots or record a video of this happening?

**Comment by Zireael07** [comment] 2021-07-15 16:34
Almost certain it's a dupe of an existing issue (one was about Intel cards in specific, one was about bad mipmaps I think in environment sky, and the third is still unresolved)

**Comment by Giggysman** [comment] 2021-07-16 03:32
https://gyazo.com/3ec29b2da5e1e21b6de7177f2d67feb7 - there's a video.

no bugs in GLES 2

**Comment by Calinou** [comment] 2022-08-05 06:50
Duplicate of https://github.com/godotengine/godot/issues/25512.

**Closed by Calinou** 2022-08-05 06:50 UTC
Labels: bug, platform:windows, topic:rendering, needs testing, topic:3d
