### ISSUE TITLE
Program crashes with signal 11 on Ubuntu 32-bit system

### ISSUE THREAD

**Issue by Unlimiter** [godotengine/godot#30230] opened 2019-07-01 20:32 UTC
**Godot version:**
v3.1.1-stable_x11

**OS/device including version:**
Ubuntu 18.04.2 LTS
Output of `sudo lshw -C display`:
```
  *-display UNCLAIMED       
       description: VGA compatible controller
       product: 82Q963/Q965 Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list
       configuration: latency=0
       resources: memory:f0400000-f04fffff memory:e0000000-efffffff ioport:1100(size=8) memory:c0000-dffff
```

**Issue description:**

I expected Godot to run properly, but this gets output:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f56d14] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f56d14] (??:0)
-- END OF BACKTRACE --
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f56d14] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)
```

**Steps to reproduce:**
Download `Godot_v3.1.1-stable_x11.32` from the official website for Linux, and run it (on my computer anyways).

**Comment by Calinou** [comment] 2019-07-01 20:51
Duplicate of #27496.

**Closed by Calinou** 2019-07-01 20:51 UTC
Labels: bug, crash
