### ISSUE TITLE
Changing default val of exported variable in script should change default val of this variable in already instanced nodes

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#8127] opened 2017-03-23 22:56 UTC
_**bugsquad edit**:_
Tested on 2.1.2, and 2.0. and 1.1 

Symptoms of this issue are visible on this gif:
![exportdefaultvaltest](https://cloud.githubusercontent.com/assets/6129594/24290611/df8f3474-1085-11e7-80e9-b56049db2ae8.gif)

Reproduction steps:
1. Create new script
2. Attach it to a node
3. Create new exported variable _integerVariable_ in the script with default value = 5
4. Save the script, look at the inspector _integerVariable_ will have correct value of 5
5. Do NOT change exported variable in inspector.
6. Change default value inside the script.
7. Value in inspector is not updated.  

sidenote: after doing some test on older Godot **I don't know if this is a bug** or design decision. As far as I remember to have that kind of 'automatic update' behavior you always needed to create subscene in a separate file and update variables in inspector of this subscene.

------------------------------

Currently (as of 2.1.2), attempting to change the default value (in the code editor) of an exported variable leaves every instance (Including the original instance, which has thrown me off several times when editing) with it's previous default value. 

I can understand the reason for this (ensuring the variables of previously edited instances are not overwritten) but I would prefer if instead of this implementation, you could just set an exported variable as "Changed" (with the revert icon appearing) on an instance to ensure it isn't overwritten and overwrite every instance with an "Unchanged" value whenever the default value is changed

**Comment by reduz** [comment] 2017-03-23 23:26
Don't really understand the problem, could you please be more specific?

**Comment by ElfEars** [comment] 2017-03-23 23:31
Essentially, when you change the default value of an exported variable (In the code editor), all instances (including the original) do not reflect this change, even if their value has not been overridden by a different one

**Comment by ElfEars** [comment] 2017-03-23 23:41
for instance, if I were to make a script as such

```
export var test = 5

func _ready():
print(str(test))
```
then set "test" to 3 within the code editor, it would still print 5 as the current instance's value would be "stuck" as the previous default unless the revert button is pressed

**Comment by eon-s** [comment] 2017-03-24 02:23
I think the thing is not that it leaves the previous default value but it does not update the value to the new default value.

The value in the inspector (first, default) remains as assigned when changing default on the script.

-------

This is a problem at first, when starting with the script, but later, changing everything to a new default value could be a mass issue because it could imply change all the values across the project.
So, I think it could be worse fixing the initial behavior.

**Comment by kubecz3k** [comment] 2017-03-24 10:02
As far as I'm able to understand this issue it's a duplicate of https://github.com/godotengine/godot/issues/5997

**Comment by kubecz3k** [comment] 2017-03-24 10:07
Oh the symptoms are similar, but it's different issue after all. Will update first post in a moment with small comment and gif

**Comment by kubecz3k** [comment] 2017-03-24 10:28
Setting milestone to 3.0  since 'fixing' this will enforce changes in existing projects.

**Comment by kubecz3k** [comment] 2017-03-24 10:30
Leaved a detailed comment in first post, setting milestone to 3.0  since 'fixing' this will enforce changes in existing projects.

**Comment by reduz** [comment] 2017-08-06 11:59
I thought of a very simple way to do this, I'll give it a try. Keep in mind this will not work with tool scripts.

**Closed** 2017-08-06 12:34 UTC
Labels: discussion, enhancement, topic:editor
