### ISSUE TITLE
Connecting the "finished" signal to "queue_free" on a particle system crashes the editor after a one-shot

### ISSUE THREAD

**Issue by shadiradio** [godotengine/godot#82019] opened 2023-09-21 01:43 UTC
### Godot version

4.2.dev5.mono

### System information

macos 12.6.8 - vulkan

### Issue description

I'm attempting to create one-shot particle VFX (explosion bursts) that clean themselves up so all you have to do is instantiate them. If you connect the "finished" signal to "queue_free" on the root, this crashes the editor after triggering the one-shot bool to visualize it. I'm guessing it's attempting to free the root, but since this isn't an instance in a runtime game, something weird happens.

### Steps to reproduce

1. Create a scene that inherits from GPUParticles2D.
2. Set the lifetime to 1s and enable one-shot mode
3. Connect the signal "finished" to "queue_free" on the root node
4. Turn the "emitting" bool on

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-09-21 02:25
Duplicate of #81320

**Closed by KoBeWi** 2023-09-21 02:25 UTC
Labels: bug, topic:editor, crash, topic:particles
