### ISSUE TITLE
Cursors set with transparent textures have visual issues on Windows.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#21745] opened 2018-09-04 07:19 UTC
### Windows 10 64-bit 
**v3.1.alpha_custom_build.f50dd68**

@capnm @guilhermefelipecgs Another small odd issue.  X)

So I was messing around with the idea of assigning a transparent texture to the mouse cursor, but on Windows10 it draws some weird half transparent thing.  Stranger still, when hovering over another texture, the pixels appear to be inverting the color.

Was trying this as a work around for the problem with CAPTURE mode not tracking the cursor position or restoring it when it ends.  The idea was to instead set a transparent cursor and use CONFINED mode.

![godot_master_2018-09-04_10-12-53](https://user-images.githubusercontent.com/13004169/45015684-1956c780-b02b-11e8-8a00-6e13ab84e2bd.png)

Example Project: [Transparent Cursor.zip](https://github.com/godotengine/godot/files/2347520/Transparent.Cursor.zip)

Note - Works fine on Ubuntu at least.

**Comment by guilhermefelipecgs** [comment] 2018-09-05 16:32
What are you trying to do? if your problem is that captured mode reset the cursor to center, you can use `Input.warp_mouse_position` with the last mouse position before changing to captured mode.

**Comment by avencherus** [comment] 2018-09-05 23:45
It was more of a thought of having an aiming system that was only interested in the angle of the cursor, and not the exact position.  With also the requirement of hiding it.  An example might be a top down hack and slash where you might use the mouse for general direction, but doesn't make sense to have a cursor or cross hair out ahead of the player.

So storing position wouldn't work for that, but I believe that relative position at least is functioning like this, and I wouldn't need to go with this method.

Just reporting this though in case it might be an issue with deeper roots, or if someday, somewhere, someone really needs too hide their cursor that way.  X)

**Comment by guilhermefelipecgs** [comment] 2018-09-12 15:11
Thanks for explain that. Thankfully captured mode with relative position will do the job, but indeed this should be fixed for windows. Unfortunately I'm without windows environment right now but asap I'll give a check on this.

**Comment by avencherus** [comment] 2018-09-12 19:05
No problem, I appreciate you looking into these things.  X)

Although it will be rather slow paced, I can test things out on Windows when you need it.

**Comment by groud** [comment] 2018-10-02 09:53
Could anyone reproduce the bug on master then ?

**Comment by guilhermefelipecgs** [comment] 2018-10-02 13:06
@groud Yep, this affect master branch.

**Comment by akien-mga** [comment] 2019-01-23 19:19
Is this still reproducible in the current master branch?

**Comment by akien-mga** [comment] 2020-01-08 10:32
> Is this still reproducible in the current master branch?

Bump @avencherus.

**Comment by avencherus** [comment] 2020-01-08 14:27
@akien-mga Seems so, at least up to 83fe471.

**Comment by avencherus** [comment] 2020-01-08 14:28
![godot_2020-01-08_16-26-45](https://user-images.githubusercontent.com/13004169/71985745-d2d33780-3233-11ea-893d-55c233f592e8.png)

**Comment by KoBeWi** [comment] 2020-12-10 00:10
Still valid in d8825fb

**Comment by aaronfranke** [comment] 2021-12-23 08:11
Starting with Godot 4.0, you will be able to set the mouse to `MOUSE_MODE_CONFINED_HIDDEN` if you want it to be confined and hidden (#43450), in addition to the current `MOUSE_MODE_HIDDEN` option that also exists in Godot 3.x. Therefore, there won't be a reason to assign a transparent texture, since you can just set the mouse to hidden in any situation.

**Comment by akien-mga** [comment] 2022-07-29 11:25
Still reproducible in 3.5 RC 8. CC @bruvzg 

The code says it handles alpha but evidently that doesn't seem to work properly.

https://github.com/godotengine/godot/blob/ca49a14914d02bd660a7d20d885b7dc41d69459d/platform/windows/os_windows.cpp#L2686-L2730

**Comment by akien-mga** [comment] 2022-07-29 11:34
For the record, transparency seems to work provided that the image is not *only* fully transparent pixels.

I tried with a 32x32 image with full transparency and it shows as a black square (Windows build on WINE), but if I add a single black pixel with either full opacity, or even 1% opacity, the transparency works fine.

So the latter works OK as a workaround: fully transparent texture of any size < 256 with at least slightly opaque pixel (with 1% opacity it's practically invisible too).

[Here's my working texture.](https://user-images.githubusercontent.com/4701338/181750528-a3e34065-3dec-4d62-9711-474ac854542d.png)

**Closed** 2022-09-14 15:44 UTC
Labels: bug, platform:windows, topic:core, confirmed
