### ISSUE TITLE
Different colors in GLES3(usual) and GLES2(unusual) while opening a 2D project.

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#32487] opened 2019-10-02 08:30 UTC
**Godot version:**
Almost latest master 1f40117caa6ad25340261969d377e1b398cd5349

**OS/device including version:**
Windows 10 x64 Pro 1903
Intel 620 HD Graphics

**Issue description:**
![Annotation 2019-10-02 134849](https://user-images.githubusercontent.com/11459028/66029307-a5803a80-e51c-11e9-878d-03a7c731291b.png)
![Annotation 2019-10-02 134947](https://user-images.githubusercontent.com/11459028/66029308-a5803a80-e51c-11e9-8169-8c5ebd8abfc9.png)

GLES2 and GLES3 mode show totally different colors in editor when opening a 2D project.
I could **NOT** reproduce it for 3D projects.

**Steps to reproduce:**
1. Open any 2D project.
2. Switch between GLES2 and GLES3.

**Minimal reproduction project:**
Any 2D project should do.

**Comment by qarmin** [comment] 2019-10-02 08:33
Seems like #32479 
Did you tried to remove *.gen.h files?

**Comment by Anutrix** [comment] 2019-10-02 08:38
I am rebuilding latest master. Will check after that. But if *.gen.h need to be cleared why is it not cleared during compile time.

**Comment by clayjohn** [comment] 2019-10-02 15:06
The same issue was reported in https://github.com/godotengine/godot/issues/32465. But im not closing as a duplicate as that issue seems to be focused on the crash which may or may not be related.

**Comment by Anutrix** [comment] 2019-10-02 17:31
But why are the 3D projects unaffected?

**Comment by clayjohn** [comment] 2019-10-02 17:46
The issue with *.glsl.gen.h files is only present in GLES2 shaders. It happens because they need to include ``drivers/gles2/shaders/stdlib.glsl``. When ``stdlib.glsl`` is edited it doesn't trigger a rebuild of the shader files. There were issues with ``stdlib.glsl`` that could affect your current build if you haven't cleaned your build files in away.

I am not certain that ``glsl.gen.h`` files are the cause. but it makes sense as I cannot reproduce.

**Comment by Anutrix** [comment] 2019-10-02 17:55
How to fix the settings? Deleting and rebuilding didn't help.

**Comment by clayjohn** [comment] 2019-10-02 18:02
Thanks for checking. It must be something else then. Just deleting the *glsl.gen.h files and rebuilding should have been enough if I was right.

**Comment by clayjohn** [comment] 2019-10-03 02:32
Okay, after testing it on another computer it appears that this is a Windows related issue. And it is indeed a duplicate of #32465

**Closed by clayjohn** 2019-10-03 02:32 UTC
Labels: bug, topic:rendering

**Comment by Anutrix** [comment] 2019-10-03 02:36
@clayjohn I don't have Nvidia graphics.
