### ISSUE TITLE
Lightmap Probes not casting light on dynamic objects

### ISSUE THREAD

**Issue by gerblesh** [godotengine/godot#59361] opened 2022-03-20 20:08 UTC
### Godot version

v4.0.alpha4.official

### System information

Windows 10, 2070 SUPER, Vulkan Clustered

### Issue description

![image](https://user-images.githubusercontent.com/101901964/159180363-bdcb9482-ea75-400d-9ae5-6f3bad83509c.png)

dynamic objects are remaining unlit from the Baked Lightmap with the generated lightmap probes, it returns these errors when moving the dynamic object in editor:
 servers/rendering/renderer_rd/renderer_storage_rd.cpp:7557 - Condition "!lm" is true. Returning: false
 servers/rendering/renderer_rd/renderer_storage_rd.cpp:7563 - Condition "!lm" is true. Returning: AABB()

### Steps to reproduce

Make a scene and light it with Lightmap Probe and Emissive materials. Make sure 'gen probes' is enabled in the lightmap. Bake the lightmap and insert a mesh, make it's 'GI mode' be either 'dynamic' or 'disabled'. The mesh either remains unlit, both in editor and in game.

**Comment by Calinou** [comment] 2022-03-20 20:56
Duplicate of https://github.com/godotengine/godot/issues/57890.

**Closed by Calinou** 2022-03-20 20:56 UTC
