### ISSUE TITLE
Android: Left/right triggers reversed on Xbox One Wireless controller

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#42803] opened 2020-10-14 18:53 UTC
**Godot version:** 3.2.3

**OS/device including version:** Android 7.0, Blackview BV8000Pro, Xbox Wireless controller paired via bluetooth

**Issue description:**

Playing my game on Android results in controls where the triggers are reversed. I.e. LT performs RT's action and RT performs LT's. I observe the correct behavior under Linux, Windows Desktop/UWP/Xbox One, and HTML 5.

**Steps to reproduce:**

1. Export an Android project with LT/RT bindings.
2. Pair an Xbox wireless controller with the target Android device.
3. Run the game.

**Minimal reproduction project:**

No minimal reproduction yet. Happy to create one if this can't be independently duplicated, but since "minimal" for me has to pull in accessibility/TTS plugins, it's a bit of a production. :) My hope is that this might be easy to observe on one of the existing demo Android projects.

**Comment by Klowner** [comment] 2020-10-23 16:01
I tried to reproduce this with my Xbox One controller and my Pixel 3 and everything seems to be working as intended.

My steps:
   1. In project settings, I added 4 new actions (`rt-axis`, `rt-button`, `lt-axis`, `lt-button`)
   2. I assign inputs to these actions
      a. `lt-axis` = `Device 0, Axis 6 + (L2)`
      b. `rt-axis` = `Device 0, Axis 7 + (R2)`
      c. `lt-button` = `Device 0, Button 6 (L2)`
      d. `rt-button` = `Device 0, Button 7 (R2)`
   3. then I include the gdscript to print their values:
```
func _input(event):
	print(
		'lta: ', Input.is_action_pressed("lt-axis"),
		' rta: ', Input.is_action_pressed("rt-axis"),
		' ltb: ', Input.is_action_pressed("lt-button"),
		' rtb: ', Input.is_action_pressed("rt-button"))
```

output when I pull left-trigger:
```
lta: True rta: False ltb: True rtb: False
```
output when I pull right-trigger:
```
lta: False rta: True ltb: False rtb: True
```

**Comment by Calinou** [comment] 2021-07-30 13:23
@ndarilek  Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by ndarilek** [comment] 2021-07-30 14:54
Sorry, moved away from Godot. Maybe someone else is better able to test?

**Comment by Calinou** [comment] 2021-07-30 15:21
I'll close this then. If anyone else can still reproduce this, please comment.

**Comment by Calinou** [comment] 2023-07-10 00:56
For future reference, this was reported by another user in https://github.com/godotengine/godot/issues/56181 (and now https://github.com/godotengine/godot/issues/79263).

**Comment by dannygaray60** [comment] 2024-11-13 19:12
@Calinou Bug still in Godot 3.6 stable, the triggers are swapped and the "release" state don't work

**Comment by Calinou** [comment] 2024-11-14 16:31
> @Calinou Bug still in Godot 3.6 stable, the triggers are swapped and the "release" state don't work

**Closed by Calinou** 2024-11-14 16:31 UTC
Labels: bug, platform:android, topic:input
