### ISSUE TITLE
custom html export template runtime errors - project must be named this and it does not work anyway ( abort(99))

### ISSUE THREAD

**Issue by fidli** [godotengine/godot#32117] opened 2019-09-13 11:31 UTC
**Godot version:** 3.1 branch (8acaac10b6458fe1ed76877a38149e4c2966baa3), also tags/3.1.1-stable

**OS/device including version:** ubuntu 18.04, firefox

**Issue description:** when using official editor build and official template everything works fine,
when i checkout godot 3.1 branch, build editor myself, build html export template myself, i can export project using that editor just fine.

but then, during runtime if the project export is not named this.html, then I get missing .pck file error (it looks for this.pck, somehow the this is not translated to the project name
if I name the project "this", then it loads, but i get error uncaught exception: abort(99)

what am I doing wrong? what were exact commands you built your official html export template with?

**Steps to reproduce:**
versions:
emdsk, current master (efc64876db1473312587a3f346be000a733bc16d)
scons:
script: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog
engine: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog

editor build command:
scons platform=x11

template build command:
first, you need to fix the html: full-size.html:180 - add ");" to the end of the line

scons platform=javascript tools=no LINKFLAGS=$'-s "EXTRA_EXPORTED_RUNTIME_METHODS=[\'callMain\']"'

then on runtime i get these names (when project name is not "this" and assuming i  fix the html template):
in PackedSourcePCK::try_open_pack:
p_path == "./this.program.pck"
and "this.pck"
and "this.program.pck"

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-09-13 11:57
This is likely caused by the exported path containing a dot. Try exporting the project with a name that doesn't contain a dot (except for the `.html` extension).

**Comment by fidli** [comment] 2019-09-13 12:30
> This is likely caused by the exported file name containing a dot. Try exporting the project with a name that doesn't contain a dot (except for the `.html` extension). See #15188, which happened when exporting to macOS.

export path is: /eyenSrc/CE/prof/viewer/clients/CompoundViewer/export/prof.html
project name is: CompoundViewer

> Also, aftere exporting your project, you'll need to start a local Web server to test it. This is to comply with browsers' security policies, which don't allow loading external files when using the `file://` protocol. See [Exporting for the Web](http://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_for_web.html) in the documentation for details.

I am having it on a server, where the official template works, but my build (tags/3.1.1-stable) does not

**Comment by akien-mga** [comment] 2019-09-24 06:40
>  first, you need to fix the html: full-size.html:180 - add ");" to the end of the line

Why? Line 180-182 is:
```
                                [statusProgress, statusIndeterminate, statusNotice].forEach(elem => {
                                        elem.style.display = 'none';
                                });
```
Seems valid to me. Adding `);` on line 180 would create a syntax error.

Your initial post had a lot more build options for the export template, including disabling a number of things that could cause issues. For example disabling `minizip` support means that you can't unzip a PCK anymore, which seems to relate to your error log.

**Comment by akien-mga** [comment] 2019-09-24 06:59
> > first, you need to fix the html: full-size.html:180 - add ");" to the end of the line
> 
> Why? Line 180-182 is:
> 
> ```
>                                 [statusProgress, statusIndeterminate, statusNotice].forEach(elem => {
>                                         elem.style.display = 'none';
>                                 });
> ```
> 
> Seems valid to me. Adding `);` on line 180 would create a syntax error.

My bad, this had been fixed in the meantime in #32176.

**Comment by fidli** [comment] 2019-09-24 07:02
> Your initial post had a lot more build options for the export template, including disabling a number of things that could cause issues. For example disabling `minizip` support means that you can't unzip a PCK anymore, which seems to relate to your error log.

I realized that for the bug report it would be nice to have it as compact as possible, and changed it to the simplest form, which i then clean-checkouted and built and tested with the same errornous result. I asked two people to independently test it and they have same issue....

**Comment by fidli** [comment] 2019-09-24 11:30
It seems that we made it work,
the build commands stay simple:
scons -j 6 platform=javascript tools=no target=release_debug

but the emscripten vesion must be exact:
emscripten-1.38.27

`./emsdk install emscripten-1.38.27
./emsdk activate emscripten-1.38.27
source emsdk_env.sh
`

**Comment by akien-mga** [comment] 2019-09-24 11:37
> but the emscripten vesion must be exact:
emscripten-1.38.27

What was the non-working version?

**Comment by fidli** [comment] 2019-09-24 11:42
> > but the emscripten vesion must be exact:
> > emscripten-1.38.27
> 
> What was the non-working version?

current latest for sure

**Closed** 2019-10-01 18:15 UTC
Labels: bug, platform:html5, topic:porting
