### ISSUE TITLE
Capsule Shapes collision not updated when capsule shape changed after Mouse Scaling

### ISSUE THREAD

**Issue by BR14Nx** [godotengine/godot#73399] opened 2023-02-15 22:23 UTC
### Godot version

3.4.2 mono stable

### System information

Windows 11 Pro, GLES3

### Issue description

Capsule shapes size is not correctly updated when changing capsules shape, then change scaling via mouse and change capsules shape again. 
The Collision outline might be correctly adjusted and shown in the editor, but when running a game you can see that the collision shape has different dimensions

### Steps to reproduce

1. Create Kinematic Body
2. Add Collision Shape as child node
3. Set Shape to CapsuleShape
4. Rotate X to 90 degrees
5. Translate capsule in the Y axis to match characters center
6. Change capsule height and width via mouse to match the characters shape
7. Press `R` and scale the Y axis bigger than the character
8. Redo step 6
9. Run a test scene to see wrong collision

### Minimal reproduction project

[CapsuleShapeIssue.zip](https://github.com/godotengine/godot/files/10748365/CapsuleShapeIssue.zip)

**Comment by Calinou** [comment] 2023-02-15 22:29
Scaling collision shapes (or its parent PhysicsBody) is not supported – you must edit the collision shape resource's extents.

**Comment by KoBeWi** [comment] 2023-02-15 22:41
Can't reproduce in 4.0. The collider is the same in-game and in editor.

> 3.4.2

That's a very old version.

**Comment by BR14Nx** [comment] 2023-02-16 00:06
> Scaling collision shapes (or its parent PhysicsBody) is not supported – you must edit the collision shape resource's extents instead.

Nevertheless it is working with other shapes. I tried it with the cube, scaling also did the job.
And if it is not supported, then I recommend to give a warning when parent PhysicsBody or collisions shape scale is changed (maybe even prohibit the scaling of collision shape nodes and hide the parameter in the editor). If even the outliner is adjusted by scaling, then this is very misleading.
Maybe it is already done in 4.0?

**Comment by Calinou** [comment] 2023-02-16 01:07
Duplicate of https://github.com/godotengine/godot/issues/5734 (same cause).

**Closed by Calinou** 2023-02-16 01:07 UTC
Labels: topic:physics
