### ISSUE TITLE
Skeleton IK breaks root bone position in rc5 and rc6

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#47381] opened 2021-03-26 10:09 UTC
**Godot version:**
3.3.rc6

**OS/device including version:**
Zorin OS 15

**Issue description:**
In 3.2.4.rc5 and 3.3.rc6 the root bone of an SkeletonIK gets its position corrupted. Even if it has an animation.
The bug is introduced in 3.2.4.rc5

This is working as expected in rc4.
![legrc4](https://user-images.githubusercontent.com/27329423/112615878-52dac280-8e23-11eb-8521-dc9f134e5319.gif)

This is how it works in rc5 and rc6.
![legrc5](https://user-images.githubusercontent.com/27329423/112615988-7c93e980-8e23-11eb-80b6-c2b254ebe23e.gif)

**Steps to reproduce:**
I use this setup
https://www.youtube.com/watch?v=68ypH04teuw

**Minimal reproduction project:**

Can't share the model.

**Comment by akien-mga** [comment] 2021-03-26 10:13
This is possibly a duplicate of #47086, which is fixed by #47147 (merged after 3.3 RC 6, it will be in 3.3 RC 7).

**Comment by Janders1800** [comment] 2021-03-26 10:15
Yeah seems the same, I'll test in cr7. feel free to close.

**Comment by Janders1800** [comment] 2021-03-26 12:10
I've compiled 3.x branch and there are still a couple of problems.

The rotation of the root bone and child gets corrupted (in rc4 works OK)
rc4
![iklegrc4](https://user-images.githubusercontent.com/27329423/112628952-efa55c00-8e33-11eb-88e9-f52a4e1601de.gif)

3.x
![ikleg3x](https://user-images.githubusercontent.com/27329423/112628963-f633d380-8e33-11eb-8416-24b333517c4a.gif)


Wen yous set Interpolation to 0, the animation in the bones stops working (this also happens in rc4)
![iklegInter](https://user-images.githubusercontent.com/27329423/112629340-7f4b0a80-8e34-11eb-9f2b-70e2d8c45a14.gif)

**Comment by akien-mga** [comment] 2021-03-26 12:53
CC @TwistedTwigleg

**Comment by TwistedTwigleg** [comment] 2021-03-26 13:29
I'll take a look once I can into the issue :+1: 
I have a *rough* idea on what is causing the interpolation set to zero issue, but I'm not sure on the other issue with the root bone.

**Comment by TwistedTwigleg** [comment] 2021-03-28 16:04
@Janders1800 - I made a PR that should fix the issue. When you have a chance, do you mind testing to see if it works? I haven't been able to test on a skinned mesh, but I think it should work correctly now.

**Comment by Janders1800** [comment] 2021-03-28 23:24
I've tested this: https://github.com/godotengine/godot/pull/47441/commits/b42f89edaa4952476fa587750bd3a5185de1c69f
And both problems are gone, it works OK, but this is for 4.0 branch only?
![Iksolve](https://user-images.githubusercontent.com/27329423/112771696-635e8900-902d-11eb-9290-fa7332621536.gif)

**Comment by TwistedTwigleg** [comment] 2021-03-29 00:48
Awesome, I’m glad its working!

The change will be applied to the Godot 4.0 branch, but cherry picked back to Godot 3.x. With it confirmed working, it can probably be merged in soon, but unfortunately another issue, BoneAttachment nodes not correctly mapping to bones, happens so that will likely need to be fixed first.

**Comment by akien-mga** [comment] 2021-04-07 14:51
Reopening for now until the fix is backported to 3.3.

**Comment by akien-mga** [comment] 2021-04-09 07:00
Fixed by #47738.

**Closed by akien-mga** 2021-04-09 07:00 UTC
Labels: bug, regression, topic:animation
