### ISSUE TITLE
Editor does not register keyboard input anymore after un-focussing the windows and refocussing

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#75296] opened 2023-03-24 17:51 UTC
### Godot version

4.0.1

### System information

Windows 11, Vulkan, ryzen 9 5900X, rx 6700xt

### Issue description

After tabbing out of the editor and then going back to it, the editor does not register keyboard input (of any kind, from any keyboard I have plugged in).

I have verified that my keyboard is working and the editor is focused. This is not specific to the project I am working on, happens regardless of the project,

Note that this does not always happen, but always sometimes. Though I don't know what causes the issue/ when exactly it happens.

### Steps to reproduce

Create a new project in Godot 4.0.1
Tab in and out of the project a few times (maybe run the project a few times as well, maybe lock the account (Win + L))
Try to use any keyboard shortcut in the Godot editor

### Minimal reproduction project

See "Steps to reproduce"

**Comment by Calinou** [comment] 2023-03-24 18:08
This is a duplicate of another issue, but I can't find it right now.

**Comment by BrastenXBL** [comment] 2023-03-24 22:18
> This is a duplicate of another issue, but I can't find it right now.

I think you're looking for https://github.com/godotengine/godot/issues/74957 and https://github.com/godotengine/godot/pull/75172

**Comment by triptych** [comment] 2023-03-25 17:45
Seeing this happen almost 100% of the time after alt+tabbing in windows. Pressing the win key resolves it but it comes back after a while. Super annoying!

**Comment by Calinou** [comment] 2023-03-25 18:06
This should be fixed in the `master` branch, but the fix hasn't been cherry-picked for 4.0.x yet. Can someone try building `master` for Windows and check if the issue still occurs there?

**Comment by YuriSizov** [comment] 2023-03-25 18:59
This is indeed a duplicate of the linked issue. If the error is still reproduceable even after the fix, we should reopen the original one.

The fix will be available in 4.0.2.

**Closed by YuriSizov** 2023-03-25 18:59 UTC
Labels: bug, platform:windows, topic:editor, topic:porting

**Comment by domdfcoding** [comment] 2024-08-01 07:23
I'm seeing this issue (or another with the same effect) on 4.2.2 on Ubuntu 20.04. Not on every Alt+Tab but fairly regularly (every 5-15 minutes). Keyboard shortcuts work but I can't type into text entry fields.

**Comment by Calinou** [comment] 2024-08-01 20:22
@domdfcoding This is likely an unrelated issue, so please open a new issue.
