### ISSUE TITLE
 [3.4] When limit smoothing and smoothing are enabled simultaneously and the Camera2D is outside of the limits, there is a one frame delay before the smoothing starts.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#56913] opened 2022-01-18 17:17 UTC
### Godot version

3.4.stable

### System information

Ubuntu 20.04.3 LTS

### Issue description

When Camera2D has limit smoothing enabled, smoothing enabled, and is outside of the limits, it starts sliding to the new limits one frame late.
This behavior did not exist in 3.3, since the camera would always immediately snap into the limits in that version, which was changed in #49409
It also does not occur for smoothing in general, even if Camera2D has the same properties. If position is changed and then reset_smoothing is called in the same function, the camera will immediately slide there. The behavior outside of limits is inconsistent in this regard.

### Steps to reproduce

1. Create a Camera2D and set its limits to small numbers
2. Enable Limit Smoothing and Smoothing
3. Move the Camera2D outside of the limits.
4. Run the project

Since it's just a one frame delay, to make the bug visible would take a bit more, in my minimal reproduction project I did the following:
1. Create a script
2. Call reset_smoothing on the Camera2D
3. Pause the tree in the same function to see the delay.

### Minimal reproduction project

[Camera issue.zip](https://github.com/godotengine/godot/files/8750422/Camera.issue.zip)
(Comment and uncomment the line that pauses the tree to see the jump clearly)

**Comment by MewPurPur** [comment] 2022-05-22 23:05
This persists in 3.5.rc1, but isn't in 4.0.alpha8

**Comment by akien-mga** [comment] 2022-06-10 12:28
Related to / possible duplicate of #56336.

**Closed** 2022-07-18 07:31 UTC
Labels: bug, topic:core, regression, topic:2d
