### ISSUE TITLE
UI behave improperly showing values in a new missaligned box.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#57206] opened 2022-01-25 15:57 UTC
### Godot version

4.0 alpha 1

### System information

Windows 10

### Issue description

When clicking a value box, there is a new missaligned box that opens below. This also happens when passing the cursor over a value. The information appears in a new box way below. It is clear looking at the pictures. Also the TAB key should jump to the next value but it is not working.

![Captura de Tela (6)_LI](https://user-images.githubusercontent.com/8985409/151010566-52f2abe0-99ac-4cff-b119-97ed5ceea09e.jpg)
![Captura de Tela (7)_LI](https://user-images.githubusercontent.com/8985409/151010623-e3448ad2-fd5f-4618-a1b3-54f56bc7b432.jpg)
![Captura de Tela (9)_LI](https://user-images.githubusercontent.com/8985409/151011364-7a6e4da7-4bbd-4310-96f1-e3d03eb235cb.jpg)

### Steps to reproduce

Try to modify a transform value of any node in the scene.

**Comment by Calinou** [comment] 2022-01-25 16:07
Duplicate of https://github.com/godotengine/godot/issues/45740.

**Closed by Calinou** 2022-01-25 16:07 UTC
