### ISSUE TITLE
KinematicBody.move_and_collide() affects all KinematicCollisions

### ISSUE THREAD

**Issue by PatrickCaughey** [godotengine/godot#48946] opened 2021-05-21 23:22 UTC
**Godot version:**
Godot_v3.3.1.stable.official

**OS/device including version:**
Windows 10
64 bit

**Issue description:**
When move_and_collide returns a KinematicCollision, it always returns the same collision, but changes its values. This causes all collisions to actually be the same object with the same values. This is not intuitive, as it appears that nothing has touched the collisions, but they are all changing.

**Steps to reproduce:**
Use multiple move_and_collide calls from the same object, make sure they all result in collisions. Check whether all of the returned collisions are the same object. 

Check to see step by step. Each variable holds the same object, which is updated by move_and_collide.

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/6525417/TestProject.zip)

**Comment by KoBeWi** [comment] 2021-05-21 23:34
Duplicate of #36290

**Closed by KoBeWi** 2021-05-21 23:34 UTC
