### ISSUE TITLE
Area3D signals doesn't work on the exported binary but they do on the editor.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#27501] opened 2019-03-28 21:04 UTC
Hi, my game has a instanced Scene composed of a Camera and some other nodes, and it uses a child Area 3D node to check if the player is outside bounds, so it can start following it.
The game works properly on the editor, but when I export and test the exported binary, the camera for some reason doesn't follow the player.
I even made print statements on the area signal, but they also don't get registered.
I asked for help on the discord, but they weren't able to guess what is wrong, since the project works just fine under the editor, except when being exported.

You can see what the bug does here in action:
https://www.youtube.com/watch?v=fs_vsTMD230

The project files are here:
https://github.com/ca3games/Godot/tree/master/3.1%20beta/Aurelio's%20Game

The proper scene node that has the issue is here:
https://github.com/ca3games/Godot/tree/master/3.1%20beta/Aurelio's%20Game/Scenes/Level

The scene is called Basic Camera Setup.
You can check the camera node script, and see the signals of the Area 3D child.

**Comment by eon-s** [comment] 2019-03-28 21:32
I do not know why is different on export, but initialize your camera with `out = true` and should work.

The behavior is strange anyway...

**Comment by ca3games** [comment] 2019-03-28 22:21
> I do not know why is different on export, but initialize your camera with `out = true` and should work.
> 
> The behavior is strange anyway...

Thanks, It works.
I was really confused because the project worked fine on the editor.

**Comment by eon-s** [comment] 2019-03-28 22:41
I think you should leave this open until the strange behavior gets fixed, something seems to be wrong on editor or export template.

**Comment by ca3games** [comment] 2019-03-29 02:32
> I think you should leave this open until the strange behavior gets fixed, something seems to be wrong on editor or export template.

ok, I'll reopen it.

**Comment by Calinou** [comment] 2019-03-29 16:53
Make sure your editor and export template versions match *exactly* (they should be built from the same commit).

**Comment by eon-s** [comment] 2019-03-29 19:20
I was able to reproduce it too, with the correct templates, is just an area that toggles a variable with enter and exit, the body starts inside and with the variable on false (changes to true on exit).
It seems to not detect the exit of the body when starts inside on export (tested with debug) but could be something else...

**Comment by eon-s** [comment] 2019-03-29 22:32
Well, I have managed to reproduce it on a minimal project, the problem is the way area enter is triggered in editor and export templates, and only happens with CollisionPolygon.

[areaerrorenterexit.zip](https://github.com/godotengine/godot/files/3024761/areaerrorenterexit.zip)
Run this on editor and from the command line, exported with debug.

**Comment by noidexe** [comment] 2019-04-09 20:29
I have a similar issue and creating a CollisionShape node, setting the shape to ConvexPolygonShape and typing the vertices by hand works fine on export. So I think the issue must lie somewhere in collision_polygon.cpp. Maybe where the convex shapes are generated, below `//here comes the sun, lalalala` :smile:

**Comment by akien-mga** [comment] 2020-01-15 11:53
I can confirm the issue in 3.1.2-stable, but it seems fixed in the master branch (3da2160233).

Probably fixed by #34340.

**Closed by akien-mga** 2020-01-15 11:53 UTC
Labels: bug, confirmed, topic:physics
