### ISSUE TITLE
Instance Transform of MultiMeshes created with set_buffer() are incorrect

### ISSUE THREAD

**Issue by Xeern** [godotengine/godot#76884] opened 2023-05-09 18:41 UTC
### Godot version

4.0.2.stable

### System information

Windows 11, Intel Core i5-8250U, Forward+, GTX 1050 Ti

### Issue description

When I create a MultiMesh with `set_buffer()` and then try to get the transform of each Instance I get different values in comparison to creating the MultiMesh with `set_instance_transform()` . Also when I try to change the values directly in the buffer dropdown in the editor the meshes get completely distorted. The basis changed as well. For the creation I used the standard basis, but after setting the buffer, the values are all over the place.
The instances itself are placed correctly though.

### Steps to reproduce

I created a simple scene with a Node3D and a MeshInstance3D (optional). The Node3D has a script attached that creates two MultiMeshInstances.  The script is a `@tool` script with a bool button for easier MultiMesh creation, but the function in question looks like this:

```
func build_variant():
	# creates two multimeshes
	var multimesh = MultiMesh.new()
	var multimesh2 = MultiMesh.new()
	
	multimesh.transform_format = MultiMesh.TRANSFORM_3D
	multimesh2.transform_format = MultiMesh.TRANSFORM_3D
	
	multimesh.instance_count = 25
	multimesh2.instance_count = 25
	
	multimesh.visible_instance_count = 25
	multimesh2.visible_instance_count = 25
	
	multimesh.mesh = BoxMesh.new()
	multimesh2.mesh = BoxMesh.new()
	
	# creates a buffer for the transform
	var buffer = PackedFloat32Array()
	for i in range(25):
		buffer.append_array([1,0,0,20*randf()-10,0,1,0,0.0,0,0,1,20*randf()-10])
	
	# instances for the first multimesh
	multimesh.set_buffer(buffer)
	
	# instances for the second multimesh
	for i in range(25):
		multimesh2.set_instance_transform(i, Transform3D(Basis(), Vector3(buffer[12*i+3],0,buffer[12*i+11])))
	
	# adds a MultiMeshInstance3D to the scene tree
	var instance = MultiMeshInstance3D.new()
	instance.multimesh = multimesh
	add_child(instance)
	instance.owner = get_tree().get_edited_scene_root()
	
	var instance2 = MultiMeshInstance3D.new()
	instance2.multimesh = multimesh2
	add_child(instance2)
	instance2.owner = get_tree().get_edited_scene_root()
	
	# output for comparison
	for i in instance.multimesh.instance_count:
		print("origin1: ",instance.multimesh.get_instance_transform(i).origin)
		print("origin2: ",instance2.multimesh.get_instance_transform(i).origin)
		print(" ")
```

This is an example output:
```
origin1: (0.007426, 0.15, 0.003713)
origin2: (8.487642, 0, -3.616688)

origin1: (0.15, 0, 0.15)
origin2: (-6.913401, 0, 8.174704)
 
origin1: (0, 0.15, 0)
origin2: (-8.218485, 0, 4.932026)
 
origin1: (0.15, 0, 0.15)
origin2: (9.599366, 0, -8.300961)
...

```
Origin2 shows the "correct" transform. Or at least what I would expect to be the correct transform.
Sometimes there is also `(0,0,0)` or `nan`.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment] 2023-05-09 20:02
Possibly a duplicate of https://github.com/godotengine/godot/issues/73123, MultiMesh buffer update is asynchronous (see the second post by clayjohn). That said, this should probably be at least mentioned in the documentation.

**Comment by clayjohn** [comment] 2023-05-10 19:46
Indeed, this is a duplicate of https://github.com/godotengine/godot/issues/73123

Closing in favour of https://github.com/godotengine/godot/issues/73123 so we can track the issue in one place

**Closed by clayjohn** 2023-05-10 19:46 UTC
Labels: bug, topic:rendering
