### ISSUE TITLE
ios: up min version to 7.0

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#6715] opened 2016-10-05 06:55 UTC
**Operating system or device - Godot version:**
Yesterday tried to gather in the last "xcode" engine under the "arm" and received the "Not Found -lcrt1.3.x". It was necessary to increase the minimum version to 7, and then all gathered. On segodnishny day no longer make sense to specify the version is less than 7.

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-10-17 07:30
Thanks, I'll close this one as duplicate of #6849 as the latter is arguably easier to understand. But I'll mention there that apparently increasing the min version to 7.0 seemed to fix it for you.

**Closed by akien-mga** 2016-10-17 07:30 UTC
Labels: bug, platform:ios, topic:buildsystem
