### ISSUE TITLE
3d workspace disappears in the editor

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#25804] opened 2019-02-11 21:52 UTC
**Godot version:**
3.1 beta custom_build

**OS/device including version:**
win10

**Issue description:**
If the 3d camera is set to Environment and Background / Mode any other than Sky, then when resizing the working viewport in the editor, the window will become a solid color.

![bug2](https://user-images.githubusercontent.com/10414783/52596032-11813600-2e9b-11e9-83be-9151aee64c70.PNG)

**Comment by bojidar-bg** [comment] 2019-02-11 22:13
Any error in the console? GLES2 or GLES3? Does it also happen on an empty project?

**Comment by DDru** [comment] 2019-02-11 22:19
> Any error in the console? GLES2 or GLES3? Does it also happen on an empty project?
It works in an empty project with gles2

**Comment by avril-gh** [comment] 2019-02-12 07:55
I can confirm. **1st viewport in editor turns blank in some scenarios.**

If you add WorldEnvironment node then within it, set Sky -> ProceduralSky, then 1st viewport will be visible.
If you remove WorldEnvironment node, then switch editor to 2 or 3 viewports, then 1st viewport will turn blank.

This is Output log while doing it.
```
Switch Scene Tab
 drivers\gles2\rasterizer_storage_gles2.cpp:564 - Condition ' !texture->active ' is true. returned: Ref<Image>()
Remove Node(s)
 drivers\gles2\rasterizer_storage_gles2.cpp:564 - Condition ' !texture->active ' is true. returned: Ref<Image>()
Create Node
Set environment
Set background_mode
Set background_sky
Remove Node(s)
 drivers\gles2\rasterizer_storage_gles2.cpp:564 - Condition ' !texture->active ' is true. returned: Ref<Image>()
Create Node
Set environment
Set background_mode
Set background_mode
Set background_sky
Remove Node(s)
```

**Comment by QbieShay** [comment] 2019-02-12 08:12
Huh, interesting, I had the same problem but my 3D view was displaying a font

**Comment by kn00tcn** [comment] 2019-02-12 14:48
shouldnt we be listing the gpu+driver version?

**Comment by avril-gh** [comment] 2019-02-12 16:47
this seems fixed on 8fd6a02d3e18ee9001ba4e397bd65b789781891e
I cant reproduce it anymore.

**Comment by wombatstampede** [comment] 2019-02-13 08:41
After encountering the error in 3.1 beta4 (GLES2, NVIDIA GT610) the 3D view now works for me in the nightly build from https://hugo.pro/projects/godot-builds/.

So I can confirm avril-gh`s post. (for me) Seems fixed.

**Comment by akien-mga** [comment] 2019-02-13 08:45
Thanks, closing as fixed.

**Comment by JFonS** [comment] 2019-02-13 08:46
@DDru can you still reproduce the issue in the latest builds? If not we can close this issue.

**Comment by DDru** [comment] 2019-02-22 15:33
I updated Godot (latest commit edbf1d0) and this problem works again.

**Comment by DDru** [comment] 2019-02-23 11:49
In version "Latest commit a291c83" this bug is still there.
@akien-mga

**Comment by akien-mga** [comment] 2019-02-23 11:51
Is the bug reproducible in beta 6?

**Comment by DDru** [comment] 2019-02-23 12:00
I downloaded and checked. In beta6, everything is fine, but a291c83 was after beta. Sorry.

**Comment by akien-mga** [comment] 2019-02-23 12:14
CC @YeldhamDev

**Comment by YeldhamDev** [comment] 2019-02-23 15:14
@akien-mga I'm am unable to reproduce it with GNU/Linux - Intel HD Graphics. I once again have no clue how my last commit would even affect this.

**Comment by DDru** [comment] 2019-02-23 15:28
It seemed to me that this happened after "https://github.com/godotengine/godot/issues/26149".
By the way, I have nvidia gt1030 if it helps.

**Comment by akien-mga** [comment] 2019-02-23 19:30
> I also once again have no clue how my last commit would even affect this.

That was just a shot in the dark, as your commit involved the SplitContainer's drawing, and the editor 3D viewport is inside a SplitContainer IINM. But indeed that was a long shot :)

**Comment by DDru** [comment] 2019-02-24 23:03
@akien-mga I updated the custom build (after beta 7) and I no longer have this bug.

**Comment by akien-mga** [comment] 2019-02-25 08:04
Closing again then, though that's quite weird. If it comes up again, there might be something at fault on your system (e.g. a plugin that messes things up).

**Closed by akien-mga** 2019-02-25 08:04 UTC
Labels: bug, high priority, platform:windows, topic:rendering
