### ISSUE TITLE
Black screen macOS 3.0

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#7865] opened 2017-02-21 23:18 UTC
**Operating system or device - Godot version:**
3.0 current master
macOS 
MacBook Pro (Retina, 13-inch, Early 2015)
2,7 GHz Intel Core i5
8 GB 1867 MHz DDR3
Intel Iris Graphics 6100 1536 MB
Xcode compiled

**Issue description:**
when I start godot I get a black screen. I need to resize the window before I can see the ui.
in addition to that the performance is really bad at the moment. zooming in 3d view but also things like opening the node section.
there is also randomly an issue which pops up, tells me godot is not working anymore but godot still works.

**Steps to reproduce:**
compiling on Xcode. starting the binary. with the current master: de0045cf1b0a5e20fbf74da192039d344ee8d0c7

**Link to demonstration video:**
https://youtu.be/-8JEwtKx9so

**Comment by Hinsbart** [comment] 2017-02-21 23:41
Seems similar to (if not a duplicate of) #7443.
That pop up might come from the project-manager crashing on exit.

**Comment by toger5** [comment] 2017-02-22 00:35
sorry for duplicate (should we close it than?)
I don't think the project manager is the reason for the popup because it appears again and again. in 2 minute interval (estimated)

**Comment by akien-mga** [comment] 2017-02-22 06:35
Closing as duplicate of #7443.

**Closed by akien-mga** 2017-02-22 06:35 UTC
Labels: bug, platform:osx, topic:porting

**Comment by algorev** [comment] 2017-03-14 18:04
It never actually stops being white for me.
