### ISSUE TITLE
preload cause ' cyclic resource inclusion' error

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#77436] opened 2023-05-24 12:27 UTC
### Godot version

4.0.3.stable

### System information

Windows11, GLES3

### Issue description

I has a root scene contains a scene2 in the node tree, and if now I use preload() function in other .gd files, will cause ' possible cyclic resource inclusion' error. 

### Steps to reproduce

if you use my reproduction project directly: 
(on start, output will get a error, scene1.gd will auto disattach from scene1.tscn)
1. attach scene1.gd on scene1.tscn 
2. run the scene2, will show errors in output

start from a new project:
1. create two scenes: scene1.tscn, a scene2.tscn 
4. scene2.tscn instantiates a child from scene1.tsn 
5. scene1.tscn add a script, add write:
```gdscription
extends Node2D
class_name Scene1

const scene1 := preload("res://Scene1.tscn")

func Create() -> Scene1:
	# scene1 will be null
	return scene1.instantiate() as Scene1
```
6. run the scene2 or restart the editor, will show errors

### Minimal reproduction project

[CyclicResource.zip](https://github.com/godotengine/godot/files/11554487/CyclicResource.zip)

**Comment by AThousandShips** [comment] 2023-05-24 13:21
> cyclic references are not supported with `preload()`.

Should probably be documented

**Comment by KoBeWi** [comment] 2023-05-28 07:57
Duplicate of #77090

**Closed by KoBeWi** 2023-05-28 07:57 UTC
