### ISSUE TITLE
Shortcut for adding nodes (ctrl-a) doesn't work if you do it quickly

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#60370] opened 2022-04-19 11:07 UTC
### Godot version

4.0.alpha6.official

### System information

Windows 10

### Issue description

If you do ctrl-a fairly quickly, (rolling your pinky and index finger onto the ctrl + a) it gets stuck, highlighting the add-node button, without pressing it.

### Steps to reproduce

Press CTRL-A fairly quickly and it will highlight the add-node button, but not press it.

**Comment by Calinou** [comment] 2022-04-19 12:41
@JamesC01 Can you reproduce this on 3.4.4?

**Comment by JamesC01** [comment] 2022-04-19 14:13
> @JamesC01 Can you reproduce this on 3.4.4?

No, not at all. There also seems to be a significant delay in opening the menu in 4.0, compared to 3.4.4. This has been a problem I've noticed in 4.0 almost a year ago.

**Comment by Calinou** [comment] 2022-04-19 18:24
Duplicate of https://github.com/godotengine/godot/issues/45033.

**Closed by Calinou** 2022-04-19 18:24 UTC
Labels: bug, topic:editor, topic:input, regression
