### ISSUE TITLE
linux compilation crash on master : drivers/unix/os_unix_global_settings_path.gen.cpp

### ISSUE THREAD

**Issue by Olm-e** [godotengine/godot#13314] opened 2017-11-26 17:01 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 18.2 
gcc (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519

**Issue description:**

compiling crash (was working one week ago)
...
```
[ 50%] Compiling ==> drivers/unix/os_unix_global_settings_path.gen.cpp
drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'
 String OS_Unix::get_global_settings_path() const {
                                            ^~~~~
scons: *** [drivers/unix/os_unix_global_settings_path.gen.x11.tools.64.o] Error 1
scons: building terminated because of errors.


```

**Comment by akien-mga** [comment] 2017-11-26 17:19
That's not a crash, it's an error. You just need to delete `drivers/unix/os_unix_global_settings_path.gen.*`.

Duplicate of #13076.

**Closed by akien-mga** 2017-11-26 17:19 UTC

**Comment by Olm-e** [comment] 2017-11-26 21:55
ok thanks a lot !, confirmed, working, 
(will go and look to find how to better search through github issues... ;) )
