### ISSUE TITLE
Setting transform for a Node2D outside the tree doesn't invalidate the global_transform

### ISSUE THREAD

**Issue by nbaum** [godotengine/godot#79214] opened 2023-07-08 17:35 UTC
### Godot version

v4.1.stable.official

### System information

Godot v4.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (nvidia; 535.54.03) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Setting `transform` for a `Node2D` outside the tree doesn't invalidate `global_transform`, so after setting `transform`, reading `global_transform` doesn't reflect the change.

Because `set_global_transform` internally sets `transform` and does not invalidate the global one, this also means that if you set `global_transform` and then immediately read it back, you don't get the transform you just set. This was why I noticed the bug.

I infer from https://github.com/godotengine/godot/pull/67710 that reading the global_transform of a Node2D which is outside the tree is _expected_ to work and should return the transform relative to the root of the disconnected tree branch.

It seems that prior to 0a9f72d5a80c8957ef5172f546c9076089862cef, a newly created CanvasItem's `global_transform` was marked as invalid, so the _first_ time it is read, it is updated from the current `transform`. After that commit, the `global_transform` appears to be marked as valid from birth.

Manually invoking `_invalidate_global_transform` on the node causes `global_transform` to update as expected, the next time it is read. Perhaps the solution is doing that automatically in `set_transform`, something which currently only happens if the transform is in the tree?

A Node3D has the same behaviour, but [it is still considered an error to access the global_transform outside the tree](https://github.com/godotengine/godot/pull/70443), and an error is reported when you try to do so.

### Steps to reproduce

Make any node and attach a script to it:

```gdscript
extends Node

func _ready() -> void:
  var node := Node2D.new()
  node.transform.origin.x = 1
  assert(node.global_transform.origin.x == 1, "First assignment got lost")
  node.transform.origin.x = 2
  assert(node.global_transform.origin.x == 2, "Second assignment got lost")
``` 

In 4.1, the first assertion will fail. In versions before 0a9f72d5a80c8957ef5172f546c9076089862cef, the first assertion will pass, but the second assertion will fail.

### Minimal reproduction project

[node2d-transform-bug.zip](https://github.com/godotengine/godot/files/11991329/node2d-transform-bug.zip)

**Comment by kleonc** [comment] 2024-04-27 14:54
Can reproduce in:
- v4.1.stable.official [970459615]
- v4.1.1.stable.official [bd6af8e0e]

Can't reproduce in:
- v4.1.2.stable.official [399c9dc39]
- v4.1.3.stable.official [f06b6836a]
- v4.1.4.stable.official [fe0e8e557]
- v4.2.stable.official [46dc27791]
- v4.2.1.stable.official [b09f793f5]
- v4.2.2.stable.official [15073afe3
- v4.3.dev5.official [89f70e98d]

Closing as fixed, likely by #80105.

**Closed by kleonc** 2024-04-27 14:54 UTC
Labels: bug, topic:2d
