### ISSUE TITLE
HTML doesn't run

### ISSUE THREAD

**Issue by Nuku** [godotengine/godot#67418] opened 2022-10-14 23:36 UTC
### Godot version

4.0 beta 3

### System information

Windows 11

### Issue description

play.js:13687 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
onPrintError @ play.js:13687
play.js:13672 CORE API HASH: 0
play.js:13672 EDITOR API HASH: 0
play.js:13687 USER SCRIPT ERROR: Parse Error: Function "var2str()" not found in base self.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/SaveEngine.gd:115)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Function "str2var()" not found in base self.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/SaveEngine.gd:116)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Compile Error: 
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/FS.gd:-1)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Compile Error: 
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/singletons/G.gd:-1)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/FS_Main.gd:130)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/FS_Main.gd:138)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/FS_Main.gd:164)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/FS_Main.gd:170)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/FS_Main.gd:176)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/FSDebug.gd:125)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/FSDebug.gd:131)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/FSDebug.gd:148)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/SystemLayers/FSDebug.gd:154)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/InputProcessor.gd:469)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Could not resolve super class inheritance from "SaveEngine".
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/LocationProcessor.gd:0)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/Mechanics/Combat/FSCombatManager.gd:41)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://Classes/Mechanics/Combat/FSCombatManager.gd:48)
onPrintError @ play.js:13687
play.js:13687 USER SCRIPT ERROR: Parse Error: Could not resolve super class inheritance from "SaveEngine".
onPrintError @ play.js:13687
play.js:13687    at: GDScript::reload (res://scripts/MainMenu.gd:0)
onPrintError @ play.js:13687
play.js:6753 WebGL: INVALID_OPERATION: clientWaitSync: timeout > MAX_CLIENT_WAIT_TIMEOUT_WEBGL
_emscripten_glClientWaitSync @ play.js:6753
255[.WebGL-000022AC085CEA00] GL_INVALID_OPERATION: It is undefined behaviour to have a used but unbound uniform buffer.
play.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.

URL: https://flexiblesurvival.com/resources/FI/play.html

### Steps to reproduce

Compiled to html5, uploaded result, went to page.

**Comment by Calinou** [comment] 2022-10-14 23:40
Duplicate of https://github.com/godotengine/godot/issues/67392.

**Closed by Calinou** 2022-10-14 23:40 UTC

**Comment by akien-mga** [comment] 2022-10-15 08:41
It's actually not a duplicate of that issue. There's plenty of script errors in the log, your GDScript code is not compatible with 4.0 beta 3 and wouldn't run on desktop either.

**Comment by Nuku** [comment] 2022-10-15 12:49
Huh, but it does run: https://flexiblesurvival.com/resources/FI/FSGodot.exe I just tried it.

**Comment by Nuku** [comment] 2022-10-16 06:40
Working on my end, looks like it's all my/our fault likely. Thanks for the help!
