### ISSUE TITLE
Wrong focus for Duplicate/copy/paste/cut hotkeys for Node-Nodes in Editor in scene-tree when Script-editor open

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#63081] opened 2022-07-16 17:43 UTC
### Godot version

3.5.rc6.official

### System information

Windows 10

### Issue description

When i am using the Ctrl+C, Ctrl+D or Ctrl+V,Ctrl+X in the Scene-tree when only a "Node" type (no Node2D or Node3D type) is selected and the script-editor is open, it will copy/duplicate/paste a line of code in the script editor instead of the tree-view.

I think one of the reasons for this is, that if i select any Node2D or Node3D node in a scene, it will automatically jump to the 2D/3D View instead of the script-editor and in that view the Scene-tree has "priority" over the 2d/3d view (or rather doesnt conflict it i guess).

with "Wrong focus" in the title i want to describe that it seems it doesnt apply the actions to the wrong window/Tile/Panel in the editor, although im actually clicking on something in the scene-tree.

### Steps to reproduce

The first examples show the expected behaviour, and the last ones will show the "unwanted" behaviour with the script-editor:

https://user-images.githubusercontent.com/24807557/179366167-a56fedab-b0d7-42b2-9f16-afb441767bfa.mp4

Create a new Scene with pure Nodes, open the script-editor and select a node in the scene-tree andand try to copy/duplicate/paste/cut. It will then proceed to do that action on the line of code currently selected instead.

**Comment by KoBeWi** [comment] 2022-07-16 22:58
Duplicate of #52861
The issue is fixed in 4.0

**Closed by KoBeWi** 2022-07-16 22:58 UTC
Labels: bug, topic:editor, topic:input

**Comment by Reneator** [comment] 2022-07-17 07:00
Tested in Godot 4 alpha 11 and it works properly (after changing the hotkey from shift+ctrl+d to ctrl+d for text-editor)

**Comment by Reneator** [comment] 2022-08-07 19:23
With 3.5 stable this issue got worse, it now also happens with other scene-trees than nodes. The Editor is not swapping to the 2D anymore and i cannot copy/paste via hotkeys, until i swap to the 2D view.

3.5 stable:

https://user-images.githubusercontent.com/24807557/183307576-be18230a-5c0e-4530-9a70-cb03d7bc1814.mp4



In Godot 4 alpha 13 it works similar, but here it seems the scene-tree panel gets the focus and then its possible to work with the hotkeys, although the script-editor is still open.

4 alpha 13:

https://user-images.githubusercontent.com/24807557/183307580-309282fd-080c-4e68-9f72-c96143655743.mp4


Could it be possible that parts of the behaviour was backported to 3.5 but then the actual focus-logic itself wasnt?

As this ticket is archived, should i open a new ticket or is this info fine here?

**Comment by KoBeWi** [comment] 2022-08-07 21:24
There are 2 separate things here.
The first one is #63344. It's intended behavior, you can disable it in editor settings.
The other one is indeed #52861. In 4.0 the editor handles shortcut context much better, but seems like the wrong behavior in 3.5 might've affected #63344 in a bad way. You can comment in #52861, we should resolve it somehow eventually.
