### ISSUE TITLE
Type hinting with signals produces unintended behaviour.

### ISSUE THREAD

**Issue by MissKraya** [godotengine/godot#27969] opened 2019-04-13 03:44 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When type hinting is used with signals some weird behaviour occurs, the following code is valid and works perfectly fine.

![](https://cdn.discordapp.com/attachments/212250894228652034/566465324485181461/unknown.png)

However when type hinting is added it throws the following error when run.

![](https://cdn.discordapp.com/attachments/212250894228652034/566465447160184837/unknown.png)

But when I add a null check to the function body the code works again and also fires off properly when the player enters the spikes.

![](https://cdn.discordapp.com/attachments/212250894228652034/566465630988009472/unknown.png)

I have checked the built in help which confirms that body is indeed of type PhysicsBody2D

![](https://cdn.discordapp.com/attachments/212250894228652034/566466164327448586/unknown.png)

This suggests to me that possibly something that isn't a PhysicsBody2D is being passed to the function by mistake? 

**Minimal reproduction project:**
[Reproduction project (Metroidvania.zip)](https://github.com/godotengine/godot/files/3075694/Metroidvania.zip)

**Comment by MissKraya** [comment] 2019-04-13 03:58
Apparently typeof() produces the number 17 which is apparently type object and not PhysicsBody2D... 

Also the problem is solved if I move the spikes scene up off the tilemap so that it's not colliding which tells me the collision with the Tilemap is passing an Object to body_entered and not a PhysicsBody2D as the documentation suggests... not sure if this is intentional or not?

**Comment by kaadmy** [comment] 2019-04-13 04:03
Just to be clear, `typeof` returns an enum value from the `TYPE_*` [global enum](class-globalscope-constant-type-max), which is *not* the class name of the object.

**Comment by Duroxxigar** [comment] 2019-04-13 04:06
I was able to reproduce this issue. I don't think this is intended functionality either. While technically, it is true that a collision happened, it just seems odd that you wouldn't be able to use static typing if you're using a tilemap. Perhaps have a toggle to allow the user decide if a tilemap should generate body_entered events or not.

**Comment by akien-mga** [comment] 2019-04-15 09:17
Duplicate of #27076.

**Closed by akien-mga** 2019-04-15 09:17 UTC
