### ISSUE TITLE
LineEdit for Point2 in inspector overflows / size is wrong in VBoxContainer.

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#17273] opened 2018-03-05 07:38 UTC
All these are made from ctrl-d with sizeflag expand thy the size is different!
![v c y 8 eram g lw8av7](https://user-images.githubusercontent.com/29348971/36962615-3a2575f4-208b-11e8-9986-5bd10160679e.png)
![tcu 35l 6w y cwqq 7](https://user-images.githubusercontent.com/29348971/36962618-3d6296a2-208b-11e8-8470-ae085cb88881.png)
![gev4a hct jcter rjnq8o](https://user-images.githubusercontent.com/29348971/36962619-3d9ce2c6-208b-11e8-84c9-d0438dfa599b.png)
The version is 3.0.2

Find the reason!
The last one in the boxcontainer will get the totalsize % items.
total size is 200.separation is 0.item num is 9.
then 200 % 9 = 2
all items except last one is 22
the last one is 24
22 * 8 + 24 = 200

**Comment by Ranoller** [comment] 2018-03-05 08:14
You are right... there are a lot of people testing engine, probably all GUI issues was reported jet. Problem is not reporting, problem is fixing. And yes, GUI problems now are a dissaster, but the problem that you shows is estethic... when the mouse get capturated and not released and you have to do F6 for preview and save and Alt+F4 to close... well, this is a real problem, if you don´t know this combination, you lose your work.

**Comment by groud** [comment] 2018-03-05 09:09
> is there anyone really testing the engine before publish a stable version?

A stable version means that the API is stable, and that no update should break compatibility. It does not mean that the engine is bug free. Also, feel free to get involved and test the engine before we release a new version, this is what the bug tracker if for. With open source projects, complaining is not the way to go.

I rename the issue title for it to be more precise. The second has probably been already raised though,  if anyone find the related issue let us know :)

**Comment by chenjie199234** [comment] 2018-03-05 09:15
@groud i apologize for wy worlds!

**Comment by chenjie199234** [comment] 2018-03-05 09:17
@groud 
I made a UI on 3.0.1 and it become a mass when i open it in 3.0.2!and i lost my work!That is the reason why i was crazy!

**Comment by groud** [comment] 2018-03-05 09:19
> I made a UI on 3.0.1 and it become a mass when i open it in 3.0.2!and i lost my work!That is the reason why i was crazy!

No problem, I understand, this should not happen. If you can provide us with a specific description of what broke between 3.0.1 and 3.0.2 that might help us solve the problem.

**Comment by chenjie199234** [comment] 2018-03-05 09:23
@groud the work lost . the file was rewrite by my damn hand!
the main problem is that the label and button's position is in a mass.all these items are in boxcontainer!maybe it is the same problem like this!

**Comment by chenjie199234** [comment] 2018-03-07 06:50
@groud 
Find the reason!
The last one in the boxcontainer will get the totalsize % items.
total size is 200.separation is 0.item num is 9.
then 200 % 9 = 2
all items except last one is 22
the last one is 24
22 * 8 + 24 = 200
is this normal?

**Comment by groud** [comment] 2018-03-07 07:01
I have no clue, but maybe. You can try to change the code, compile, and see if the problem is solved :)

**Comment by bojidar-bg** [comment] 2018-03-08 10:12
Interestingly enough, there have been no big changes to BoxContainer or LineEdit nodes that might impact this between 3.0 and 3.0.2, as far as I can see. There have been some to GridContainer that sound like what you are seeing, but this is not a GridContainer anyway.

Likely related to the fact that expanding children try to fill all the available space, but it is not evenly divisible between them, while Control nodes can have only integer sizes.

Can you try adding a bare Control node with Expand on below all the other nodes, so it would be able to evenly divide the size? :smiley:

**Comment by chenjie199234** [comment] 2018-03-08 11:29
@bojidar-bg so this is not a bug?should i close the issue?

**Comment by bojidar-bg** [comment] 2018-03-08 11:45
Well, no, I think this behaviour can still be improved, even if it is somewhat expected.

**Comment by hpvb** [comment] 2018-03-08 12:12
I'm a little confused, is this actually a regression? We have two incompatibilities noted on the release notes page for 3.0.2:
>* RichTextLabels did not properly determine the baseline of all fonts. If you relied on the look of the previous implementation please let us know. See #15711 for details.
>* SpinBoxes didn't calculate their width properly. This is now fixed but could subtly change your GUI layout. See #16432 for details.
Are you affected by these @chenjie199234 ?

**Comment by chenjie199234** [comment] 2018-03-08 12:48
@hpvb 
download 3.0.2 on the offical web
create a new project
add a control
add a panel child to control change its size
add a H/VBoxcontainer to the panel and set full rect to fill the panel
then add item to the box, set the item's size flag to fill and expand,ctrl-d copy the item then u can see the problem on the last one u copyed.

**Comment by Calinou** [comment] 2020-06-07 19:38
@chenjie199234 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by KoBeWi** [comment] 2020-06-07 20:36
This was fixed with the new inspector in 3.1. The LineEdits no longer pop out awkwardly, so this is not possible to happen anymore.

**Closed by KoBeWi** 2020-06-07 20:36 UTC
Labels: bug, topic:core
