### ISSUE TITLE
Crashes a few seconds upon launching editor (Win 10)

### ISSUE THREAD

**Issue by nullterm** [godotengine/godot#19624] opened 2018-06-18 03:48 UTC
**Godot version:**
Latest, 3.0.3, 32-bit and 64-bit.

**OS/device including version:**
Windows 10
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2

**Issue description:**
Started up Godot, but the editor crashes with-in a few seconds before being able to do anything.

**Steps to reproduce:**
Start Godot, wait a few seconds or try to open a demo, crash.

**Minimal reproduction project:**
Can't make it into any project or demo.

![image](https://user-images.githubusercontent.com/3742554/41517398-89efe480-726f-11e8-9930-825c4946671f.png)

**Comment by vnen** [comment] 2018-06-18 05:48
Duplicate of #19336

**Closed by vnen** 2018-06-18 05:48 UTC
