### ISSUE TITLE
C# Script Generated Editor Nodes without Script

### ISSUE THREAD

**Issue by daKuleMune** [godotengine/godot#41310] opened 2020-08-16 17:07 UTC
**Godot version:**

Godot Engine v3.2.3.rc3.mono.official

**OS/device including version:**

**Issue description:**

When using a [Tool] to generate a node with the following code.
```
var node = new Node();
AddChild( node );
node.Owner = GetTree().EditedSceneRoot;
```
Add node can be added into the node tree, however when doing this with a class the script attached to the node will be blank.
![image](https://user-images.githubusercontent.com/916489/90339715-dd1a9880-dfaf-11ea-8980-0aa12e0e2cd8.png)

```
public class CustomNode : Node {
}
...
var node = new CustomNode();
AddChild( node );
node.Owner = GetTree().EditedSceneRoot;
```

**Steps to reproduce:**
Create a custom class and attach it to the node tree via [Tool] _Ready or _EnterTree.

**Minimal reproduction project:**

[godot-issue.zip](https://github.com/godotengine/godot/files/5081089/godot-issue.zip)

**Comment by navstev0** [comment] 2020-08-16 17:19
Additional information was found that
```
var node = new CustomNode();
CSharpScript script = node.GetScript() as CSharpScript;
var test = script.ResourcePath == ""
```
test evaluates to true

**Comment by raulsntos** [comment] 2023-07-12 14:28
Duplicate of https://github.com/godotengine/godot/issues/48828

**Closed by raulsntos** 2023-07-12 14:28 UTC
Labels: bug, topic:dotnet
