### ISSUE TITLE
Animation Blend Tree Filters UI Is Broken

### ISSUE THREAD

**Issue by nuke-makes-games** [godotengine/godot#32920] opened 2019-10-19 15:05 UTC
**Godot version:** 3.1.1 stable

**OS/device including version:** win10, 64 bit

**Issue description:** I have a simple 2d skeleton i am animating with a blend tree. For some reason, when i try to filter certain tracks through the godot UI, some of the body parts of the skeleton show up incorrectly as a checkbox. This problem causes animation blending to completely fail.

Screenshot of the UI bug: https://cdn.discordapp.com/attachments/477544613511692358/635127578583105562/Untitled.png

GIF of the animation blend failing: https://cdn.discordapp.com/attachments/477544613511692358/634759381082439690/jjjjj.gif

Basically, the animations being blended affect entirely different body parts and so they should blend fine. The issue is that the filter is totally broken (i assume due to the checkbox bug) so it freezes the entire animation as a result.

**Steps to reproduce:**

I tried to reproduce this with a new project but could not. Perhaps i somehow corrupted something in my prefab. I cannot be certain what is causing the issue but it's only appearing within this one project.

**Minimal reproduction project:**

[Game.zip](https://github.com/godotengine/godot/files/3746830/Game.zip)

Load up the project and open the Prefabs/Characters directory. There is a player test prefab there.

Open that prefab and examine its animation blend tree. Look at the filters on the Add2 node.

**Comment by pouleyKetchoupp** [comment] 2019-11-21 14:16
@nuke-makes-games It looks like the only thing that's preventing your animation to play correctly is that your 2 state machines (ArmMovement and LegMovement) are sharing the same playback (AnimationNodeStateMachinePlayback) so the arm animation is actually ignored in the blend tree.

Is it something you've done on purpose? Currently the system can work only when each state machine has its own playback control.

To fix your animation problem, you can just change one of the state machines to use a unique playback instead:
![image](https://user-images.githubusercontent.com/1075032/69344988-a443d200-0c70-11ea-8c96-5cd2e88c5d9f.png)

I'm able to use the movement blend and its filter correctly after this change.
Can you try to do that and see if it solves your problem?

**Comment by KoBeWi** [comment] 2020-10-20 19:36
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-10-20 19:36 UTC
Labels: bug, topic:editor
