### ISSUE TITLE
Sky is displayed incorrectly on android using ARVR camera and mobile native interface.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#27335] opened 2019-03-22 20:51 UTC
**Godot version:**
3.1-stable

**OS/device including version:**
Android 9 - Pixel2 XL- GLES3 (GLES2 doesn't start...)

**Issue description:**
When running on the device, the sky is not displayed correctly. It seems to work for the reflections. (Although the material display a metalness that's incorrect: roughness is supposedly 1.0 in the following screenshots)

** On the PC **
![Screenshot_2019-03-22_21-33-19](https://user-images.githubusercontent.com/7917475/54852138-39f71e00-4cec-11e9-8014-d7fd262932da.png)

**On the phone**
![photo_2019-03-22_21-49-06](https://user-images.githubusercontent.com/7917475/54852166-55fabf80-4cec-11e9-8a71-9bf03bca7377.jpg)
![photo_2019-03-22_22-00-43](https://user-images.githubusercontent.com/7917475/54852714-f3a2be80-4ced-11e9-9aad-2714c73e289e.jpg)
![photo_2019-03-22_21-48-49](https://user-images.githubusercontent.com/7917475/54852168-55fabf80-4cec-11e9-82df-f8d9d57badc4.jpg)

**On the PC**
![Screenshot_2019-03-22_21-47-46](https://user-images.githubusercontent.com/7917475/54852189-657a0880-4cec-11e9-8b00-127364e97b60.png)

**On the phone**
![photo_2019-03-22_21-49-56](https://user-images.githubusercontent.com/7917475/54852209-79256f00-4cec-11e9-81de-dffdf178b7a1.jpg)
![photo_2019-03-22_21-49-54](https://user-images.githubusercontent.com/7917475/54852210-79256f00-4cec-11e9-96d2-f9178d997e54.jpg)

**Notes**
~~Seems like the image is distorted when the head is tilted, might have to do with a non orthonormal camera matrix?~~

[here](https://gfycat.com/FrailValuableCottonmouth) a video.

**Comment by BastiaanOlij** [comment] 2019-04-08 22:16
I'll have to give it a try on my phone but it looks to me it's not processing the accelerometer data properly. Either that or your screen orientation isn't set correctly though Godot should adjust for that.

**Comment by BastiaanOlij** [comment] 2019-04-09 13:18
Strangely enough it has no issues when rotating the camera while using the mobile vr interface on the desktop. I'll do some more digging tomorrow, time for bed :)

**Comment by MassiminoilTrace** [comment] 2019-06-07 17:17
I found a workaround, maybe it's related to the cause of the problem.
I'm working on Fedora Gnu/Linux 29 with Godot 3.1.1

My game has the problem described with a Panorama sky with an image on it.
By setting the "Sky Custom Fov" property in the editor to a non-zero value, it displays it correctly.
The name of the property inside the engine is `background_sky_custom_fov`.
The property can be found in Camera→Background→Sky Custom Fov.
Maybe it is related.
Hope it helps in resolving the issue.

**Comment by zlsa** [comment] 2019-08-17 05:03
I can confirm this as well, and that @MassiminoilTrace's workaround does work (but with obvious downsides.)

**Comment by BastiaanOlij** [comment] 2019-09-07 00:41
Any chance if #31419 has fixed this issue?

**Comment by akien-mga** [comment] 2019-09-23 07:10
> Any chance if #31419 has fixed this issue?

I could test if there is a MRP that I can run on my phone. Otherwise I'm not familiar enough with the ARVR camera and mobile native to put something together quickly to confirm.

**Comment by clayjohn** [comment] 2019-11-30 16:50
@QbieShay is this still reproducible?

**Comment by QbieShay** [comment] 2019-11-30 19:59
@clayjohn no, the sky seems now ok! Although the game is now lagging..

**Closed** 2019-11-30 21:25 UTC
Labels: bug, platform:android, topic:arvr, topic:rendering
