### ISSUE TITLE
Godot overrides changes when pulling from Git remote

### ISSUE THREAD

**Issue by woubuc** [godotengine/godot#26370] opened 2019-02-27 19:45 UTC
**Godot version:**
3.1-beta6

**OS/device including version:**
Windows 10

**Issue description:**
When having the Godot editor open in a project with Git version control, and pulling changes from a remote, Godot will overwrite many changes as soon as the editor window is focused again (including the project.godot file and open scenes) with data from the current session, rather than use the newly pulled data.

This means that, in order to update our project with the team's changes from a remote Git repository, we have to close the editor, pull the changes, and then load the project again.

**Comment by akien-mga** [comment] 2019-02-27 19:48
Duplicate of #20250.

**Closed by akien-mga** 2019-02-27 19:48 UTC
