### ISSUE TITLE
'Add child node' shortcut rebinded to Shift+A doesn't work in the scene dock

### ISSUE THREAD

**Issue by isnt-alice** [godotengine/godot#27630] opened 2019-04-03 08:17 UTC
This thing.
![add_child_node](https://user-images.githubusercontent.com/48971470/55463548-27170000-55ae-11e9-9ac6-8179785198c3.png)
~~Basic UX improvement.~~ A bug?

**Godot version:**

5b00cd8

**OS/device including version:**

Manjaro Linux

**Issue description:**

Rebound shortcut has no effect, should open the "Create New Node" dialogue.

**Steps to reproduce:**
Editor > Editor Settings > Search "Add Child Node" > Rebind shortcut
Click the Scene tab
Press the rebound shortcut
No effect

**Comment by Calinou** [comment] 2019-04-03 08:29
What do you mean? The current default shortcut seems to be <kbd>Ctrl + A</kbd>, whereas it is <kbd>Shift + A</kbd> on the screenshot you posted.

**Comment by isnt-alice** [comment] 2019-04-03 08:32
The shortcut doesn't work if I hover the cursor over that menu.
I did remap the shortcut to Shift+A because Blender, though.

**Comment by isnt-alice** [comment] 2019-04-03 08:34
I just changed the shortcut back to Ctrl+A and it works...

**Comment by akien-mga** [comment] 2019-04-03 08:53
Please be more explicit in your bug reports, we have an issue template asking for details for a reason.

A screenshot is not a bug report, especially one which only shows a tooltip without saying what isn't working. The rest of the discussion made it clearer, but this should have been mentioned from the start.

**Comment by isnt-alice** [comment] 2019-04-03 08:57
@akien-mga It wasn't originally a bug report, sorry.

**Comment by KoBeWi** [comment] 2020-08-20 23:26
Fixed in 4.0
(although seems still broken in 3.2.3 rc3)

**Closed by KoBeWi** 2020-08-20 23:26 UTC
Labels: bug, topic:editor

**Comment by TheRealSlander** [comment] 2024-07-21 11:29
Sorry to necro this, but I recently bumped into the exact same problem in Godot 4.3.beta3. I'm using Godot on Manjaro Linux 64 bits with Cinnamon DE. I'm using the Single Window Mode if this has something to do with it.

I remapped my "Add Child Node..." event to the `Shift + A` shortcut (as all my other applications have this to add something, like Blender) but in the TreeNode the shortcut is not working.

When the focused window is the 2D panel, the `Shift + A` shortcut works perfectly, but not when the focused panel is the TreeNode.

I join a video below to illustrate this (sorry for the bad compression quality):
[cinnamon-2024-07-21T131816+0200.webm](https://github.com/user-attachments/assets/efd48924-7c08-4924-9d90-37c56eac2e89)

**Comment by TheRealSlander** [comment] 2024-08-15 07:37
@KoBeWi tagging you as I don't know if this issue was watched since it has been closed then necroed back by me. O.O'

**Comment by KoBeWi** [comment] 2024-08-15 09:47
Isn't #93631 the same issue?

**Comment by TheRealSlander** [comment] 2024-08-15 10:25
Yes it is, haven't seen that one sorry.
