### ISSUE TITLE
Combination of metallic materials, SSR, MSAA, and hint_screen_texture produces pure black pixels

### ISSUE THREAD

**Issue by BattyBovine** [godotengine/godot#89949] opened 2024-03-27 18:42 UTC
### Tested versions

- 4.2.1 stable
- 4.3-dev5
- Current master branch (7d151c83811f8ac8873439826c16d88c83aba12f)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

I discovered a weird issue while attempting a custom post processing shader based on [this documentation page](https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html). This page appears to be outdated in its own right, but that's a separate issue. While getting this working, I happened to notice that anything reflective, particularly metallic materials, were displaying as either non-reflective or pure black. After lots of testing, I determined that this occurs under very particular circumstances. It only seems to appear when using a WorldEnvironment node that has SSR enabled, along with MSAA anti-aliasing. The effect is most noticeable on fully metallic textures because this produces pure black pixels, though non-metallic materials seem to produce correct colours but no reflections. I've created a [sample project](https://github.com/BattyBovine/msaa-screentexture-error) to demonstrate this, and the releases on that page contains a release build to examine the effects. Toggling on MSAA, SSR, and Post Process at the same time demonstrates the pure black pixel effect on metallic materials. A metalness slider is also available to demonstrate that non-metallic materials still exhibit incorrect results, though much more subtle.

I've tried other anti-aliasing as well. FSR 2.0 works fine, FXAA works fine, and TAA looks more jittery than without a post-process filter but does not produce anything like this. Although all reflections seem affected by this, it only appears when screen-space reflections are enabled as well. This could very well be another AMD-specific problem, though I don't have a way to check since I don't currently have access to NVIDIA hardware.

It should also be noted that using a ColorRect in 2D for post-processing according to [this page](https://docs.godotengine.org/en/stable/tutorials/shaders/custom_postprocessing.html) does not exhibit this behaviour. This also only happens on the Forward+ renderer, possibly because SSR only works on Forward+.

For reference, here's some screenshots of the effect from the example project I created. The red corners when the post-processing is applied is the post-process filter itself; this is to make it clear that post-processing is enabled. This is the only change to the otherwise unmodified hint_screen_texture input.

SSR and MSAA enabled, post process mesh set to not visible:
![SSR and MSAA enabled, post process mesh set to not visible](https://github.com/godotengine/godot/assets/428511/0af60a8b-8c26-445b-b5b9-7445ee66a0fb)

SSR and MSAA enabled, post process mesh set to visible:
![SSR and MSAA enabled, post process mesh set to visible](https://github.com/godotengine/godot/assets/428511/e09218f3-cdc9-4bd9-ade7-97f86218c539)

SSR enabled, MSAA disabled, post process mesh set to visible:
![SSR enabled, MSAA disabled, post process mesh set to visible](https://github.com/godotengine/godot/assets/428511/19b2c1a6-997c-4448-b53f-d90fd1ec0325)

### Steps to reproduce

In a new project:
- Use Forward+ renderer
- Enable MSAA
- Add a WorldEnvironment node to a scene with SSR enabled
- Use a shader with a hint_screen_texture on a MeshInstance3D

Any fully metallic objects in the scene will appear black when rendered to the screen texture, and reflections in general will be non-existent.

### Minimal reproduction project (MRP)

https://github.com/BattyBovine/msaa-screentexture-error

**Comment by jsjtxietian** [comment] 2024-07-03 03:54
I did not reproduce it with Godot v4.3.beta (7cecdc0da) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5241) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

**Comment by Calinou** [comment] 2024-07-03 15:23
I can't reproduce this on 4.3.beta 92c8e87cd (Linux, GeForce RTX 4090 with NVIDIA 550.90.07).

![No effects](https://github.com/godotengine/godot/assets/180032/f01ffa04-5fe0-44b6-9fb6-10623f711c1c)

![All effects](https://github.com/godotengine/godot/assets/180032/bf899223-6104-44d3-b109-2bf61cf6bccf)

**Comment by Jamsers** [comment] 2024-07-03 16:09
I can reproduce the issue on Godot v4.2.2.stable, but not on Godot v4.3.beta2.

Sys info: Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.56000) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

**Comment by clayjohn** [comment] 2024-07-03 19:10
I can confirm the same as Jamsers. I can reproduce the bug with an RX 6900XT with 4.2.2 and 4.3 dev 5, but not with Beta 2.

Closing as fixed!

**Closed by clayjohn** 2024-07-03 19:10 UTC
Labels: bug, topic:rendering, needs testing, topic:shaders, topic:3d
