### ISSUE TITLE
High GPU usage after creating particles

### ISSUE THREAD

**Issue by bruno-ortiz** [godotengine/godot#15355] opened 2018-01-05 00:41 UTC
**Godot version:**
Godot 3.0 Beta2
GPU - GTX 980 TI

**OS/device including version:**
Windows 10 falls creator

**Issue description:**
After creating a Particles node, GPU usage bumps to around 45%, on Particles2D is even worse, GPU usage goes to around 50%

**Steps to reproduce:**
Create a empty scene and add the Particles or Particles2D node.

**Comment by capnm** [comment] 2018-01-05 02:20
Looks like the particles node is causing 100% editor viewport updates, similar to the setting Spinner -> update always. This is probably expected when it emits particles, but in godot 2.x it at least leaves the process if there are no particles to draw: https://github.com/godotengine/godot/blob/0d6485d919e0d4685bcbcf8ec117ea698538f785/scene/2d/particles_2d.cpp#L456

The update is now managed somewhere in the gles3 rasterizer, I couldn't find where.
You can hide the node in the scene, then the editor will not be permanently updated.
(Tested in the current tip version of godot3).

**Comment by Ron5s** [comment] 2018-01-05 03:50
I opened #14869.  I am experiencing high resource usage in ram cpu and gpu.  I think there are other issues open about this.  If you read the last post by Juan he states that "it seems to be completely driver bound, so this may actually be a problem onGLES3 having significantly more driver overhead" .  It could be unrelated to my problem though.

**Comment by Dillybob1992** [comment] 2018-01-05 05:27
Hmm. Only getting around 22% GPU usage here (GTX 950).  However, is this abnormal behavior since Godot 3.0 uses GPU processing for Particles now?

**Comment by bruno-ortiz** [comment] 2018-01-05 12:33
@Dillybob1992 , apparently the result varies(i don't know the circumstances), now i'm getting 32% for Particles2D and 20% for Particles, i know that Particles are processed by the GPU now,  but as you said 20% and 32% don't seem correct to me.

**Comment by reduz** [comment] 2018-01-05 12:56
The CPU usage should be simliar to toggling update always, and is the
result of the screen redrawing in every frame. The bug here is that, if
particles are not visible, they should not cause a screen redraw.

**Comment by reduz** [comment] 2018-01-05 18:00
Apologies, I just checked and it's working as intended. For both 2D and 3D particles, when not on screen it does not redraw. Closing this, as it's a non issue.

**Comment by bruno-ortiz** [comment] 2018-01-05 18:05
@reduz  when it's not visible it does not redraw, but even when the particle is not emitting or does not have any material attached to it, it keeps redrawing, maybe its a issue?

**Comment by capnm** [comment] 2018-01-05 21:28
@bruno-ortiz is right. If you disable **emitting** or enable **on_shot**, it keeps redrawing the editor even if there is nothing to draw.

**Comment by reduz** [comment] 2018-01-06 03:37
This is not a bug, though. Emitting does not mean the particle system is
disabled, just that new particles will not be emitted. Emitting can be off
and particles still stay alive for a while.

**Comment by capnm** [comment] 2018-01-06 04:23
The editor is always redrawn, even if all the particles are already dead ;)

**Comment by reduz** [comment] 2018-01-12 14:32
Yeah, but this is not a bug. Will mark as enhancement and kick to 3.1

**Comment by qarmin** [comment] 2018-09-02 15:55
On my Laptop 
i3-2330m (2/4) Intel HD 3000 with Linux Mint Mate 19 and GLES 3 (in GLES 2 particles don't work)
CPU usage is 4-12% but if I create Particles2D(default properties) CPU usage jump to 50%, when I set emitting to false, cpu back to normal.

This shouldn't work that, because by default only 8 particles are emitting with 1s lifetime

**Comment by Zireael07** [comment] 2018-09-02 15:59
I believe particles very existence affects how often screen is redrawn, there were issues about it, and I'm not sure if the fixes were merged.

**Comment by qarmin** [comment] 2018-09-18 12:09
Here is a gif which show CPU(left values) and GPU(right values) with enabled and disabled newly created particles2D node.

![ezgif-1-f9634d72be](https://user-images.githubusercontent.com/41945903/45686116-de38b600-bb4b-11e8-81d9-27756daf5456.gif)

"Menedżer okien pulpitu" is in english "Windows Desktop Manager"
I worked on machine with Intel 4770s and Intel HD 4600

**Comment by Calinou** [comment] 2018-09-18 13:45
I think it works as expected here. However, to decrease CPU usage when idle, it would be possible to pause particle simulation while the editor window is minimized or unfocused.

**Comment by akien-mga** [comment] 2019-11-14 10:50
This seems fixed in the master branch. Particles use a lot of CPU when they're enabled, as expected and described. But when disabling `emitting`, they don't use any extra CPU.

**Closed by akien-mga** 2019-11-14 10:50 UTC
Labels: enhancement, topic:rendering
