### ISSUE TITLE
Renaming nodes and parameters of a Blend Tree works erratically and randomly ignores the names provided, giving random names

### ISSUE THREAD

**Issue by alfredbaudisch** [godotengine/godot#65835] opened 2022-09-15 16:52 UTC
### Godot version

4.0-alpha17

### System information

Windows 10

### Issue description

Renaming the nodes and parameters of a Blend Tree does not work consistently. Also the name provided is sometimes accepted, sometimes not. When the name is not accepted, the name is automatically either set to `<null>` or with a name of a random node type name appended by a number.

See how many times and different names I tried until it accepted a name:
![BlendTreeName](https://user-images.githubusercontent.com/248383/190461937-d2bb17d7-c90e-4ad3-9b77-0bfb7a850ad9.gif)

### Steps to reproduce

- Create an Animation Tree
- Set it as State Machine root
- Create a Blend Tree node in the state machine
- Open the Blend Tree, add any node and try to rename
- If you don't see the same issue, try adding more nodes and renaming them

**Comment by Calinou** [comment] 2022-09-15 17:03
Duplicate of https://github.com/godotengine/godot/issues/58822.

**Closed by Calinou** 2022-09-15 17:03 UTC
