### ISSUE TITLE
Self reference on static function isn't working on 4.2.dev3

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#80599] opened 2023-08-13 21:49 UTC
### Godot version

Godot Engine v4.2.dev3.official.013e8e3af

### System information

Vulkan API 1.2.231 - Forward Mobile - Using Vulkan Device #0: Apple - Apple M1 Max

### Issue description

Creating a static function and referencing self class on function body isn't working anymore on 4.2.dev3 (I was using 4.2.dev1 and it was working fine. I tested on 4.2.dev2 and it worked too).
Example:
```gdscript
extends Node2D

class MyConfig:
  var x: int

  static func build_config(x: int) -> MyConfig:
    var my_config: MyConfig = MyConfig.new()
    my_config.x = 3

    return my_config

func _ready() -> void:
  MyConfig.build_config(3)
```

Error `Parser Error: Identifier not found: MyConfig` on `var my_config: MyConfig = MyConfig.new()`.

### Steps to reproduce

Download mrp and run `node_2d.tscn` scene

### Minimal reproduction project

[static_self_ref.zip](https://github.com/godotengine/godot/files/12330491/static_self_ref.zip)

**Comment by dalexeev** [comment] 2023-08-14 06:44
* Duplicate of #80508.
* Will be fixed by #80510.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-08-14 06:44 UTC
Labels: bug, topic:gdscript, regression
