### ISSUE TITLE
Tilemap ysort not working correctly for isometric tiles on y-axis (x=0)

### ISSUE THREAD

**Issue by MisterMX** [godotengine/godot#57879] opened 2022-02-09 21:11 UTC
### Godot version

4.0.alpha2

### System information

Windows 10

### Issue description

YSort does not work correctly for isometric tiles on 2D tilemap.

### Steps to reproduce

1. Create a tilemap with isometric tileset
2. Place 1st tile on y axis
3. Place 2nd tile to the bottom right of 1st

![Capture](https://user-images.githubusercontent.com/15015463/153290643-f487b79b-fd3e-425d-974a-0db96e523c03.PNG)

**Comment by Calinou** [comment] 2022-02-09 23:13
@MisterMX Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by MisterMX** [comment] 2022-02-26 10:49
The issue appears also in `4.0.alpha3`. Any updates on that?

**Comment by Maxouwell** [comment] 2022-03-04 21:13
Same here on v4.0.alpha3.official [256069eaf]
![image](https://user-images.githubusercontent.com/13748802/156842041-a8d5e3ba-d252-4737-ae15-ed2fc6e4694a.png)
(YSort origin value don't do anything)
Even changing ZIndex does not resolve the problem

**Comment by Maxouwell** [comment] 2022-03-09 21:09
Still present in alpha 4

**Comment by Maxouwell** [comment] 2022-03-24 21:53
Still present in v4.0.alpha5.official [d7d528c15]

**Comment by groud** [comment] 2022-03-25 08:43
@Maxouwell there's no need to up this issue at every alpha release. If the issue is still open, it means that, yes, the issue is still present.

**Comment by paperman5** [comment] 2022-03-31 23:48
This issue may have something to do with the cell quadrant size. If I set up a hex grid and then change the quadrant size I can alter the incorrect overlap pattern.
![image](https://user-images.githubusercontent.com/22630098/161167328-ae5c70d5-1810-4a2a-be0a-b435c293651d.png)

**Comment by groud** [comment] 2023-01-18 15:55
This is working as intended on master, with the instructions I stated above:

https://user-images.githubusercontent.com/6093119/213222280-6f5dfd5b-5a5b-4dfa-bbac-afb7b82e9f41.mp4

You now also have a configuration warning to tell what is wrong.

Closing as solved.

**Closed by groud** 2023-01-18 15:55 UTC
Labels: bug, topic:core, confirmed, topic:2d

**Comment by ersignee** [comment] 2023-04-03 23:31
> Have you both:
> 
> * set `y_sort_enabled` to true on the TileMap node?
> * enabled Y-sorting on the TileMap layer you are drawing your tiles on?
> 
> If yes, then we'll need a MRP as Calinou asked.

This fixes the issue for me.
