### ISSUE TITLE
Editor shortcuts don't save

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#5373] opened 2016-06-23 11:45 UTC
**Operating system or device - Godot version:**
Windows 7. Recent 64-bit builds from https://archive.hugo.pro/godot/ and http://fixnum.org/godot/.

**Issue description & repro steps:**
Set or change any shortcut in the "Shortcuts" tab of the "Editor Settings" panel, yay, the shortcut works! Quit the editor and start it again; all the shortcuts are reset to the defaults. :(

**Comment by djrm** [comment] 2016-06-23 18:10
i thought i was the only one

**Comment by rgrams** [comment] 2016-07-03 18:47
I don't mean to nag, but is there a plan/timeline for fixing this? Not much point in having customizable shortcuts if they don't save.

**Comment by djrm** [comment] 2016-07-03 18:55
@rgrams the plan is to fix this before 2.1 release

**Comment by rgrams** [comment] 2016-07-03 18:56
Random other editor settings have stopped saving in the last month-ish too: Script temperature history size, code complete delay . . .

**Comment by djrm** [comment] 2016-07-03 18:58
I investigated this problem a bit and the values are saved correctly, the problem is when you reopen godot some saved values get overwritten (for instance the shortcuts)

**Comment by rgrams** [comment] 2016-07-03 19:12
Ahh! That sounds like it's the cause of #5477 too.

**Comment by allkhor** [comment] 2016-07-03 19:27
Android settings overwritten too, like a adb, jarsigner, debug keystore. 
Os Xubuntu 16.04 x64, godot ac157f8 commit.

**Comment by djrm** [comment] 2016-07-03 19:29
so it seems that its a general problem when loading project settings, at least certain settings.

**Comment by allkhor** [comment] 2016-07-03 19:41
Many settings after restart a godot overwritten to default value.

**Comment by djrm** [comment] 2016-07-03 20:49
it seems that the problem of saving shortcuts is not related to other settings not being saved (which i haven't found any by the way).

**Comment by djrm** [comment] 2016-07-03 22:58
this was fixed by 1e095cf39760d0469e7a5a0749b1541a0790cb77, i dont know about the other issues about missing settings but it might be possible that they are also fixed

**Comment by reduz** [comment] 2016-07-03 23:00
they should be, so closing

**Closed by reduz** 2016-07-03 23:00 UTC
Labels: bug, topic:editor

**Comment by rgrams** [comment] 2016-07-04 11:02
Woo! Sweet, it works.

**Comment by rgrams** [comment] 2016-07-05 15:11
Or . . . not. Now, about every other time I restart the editor I get this: [screenshot](http://i.imgur.com/wFjex0E.png), and all of the editor settings are lost, including the project list.

**Comment by allkhor** [comment] 2016-07-05 15:37
Maybe you try delete(rename|backup) your godot config folder?  In linux a config location is: ~/.godot After that Godot create a new config and problem mast bee solved.

**Comment by djrm** [comment] 2016-07-05 16:25
i dont know much about windows file paths but is it ok to mix this \ and this / in the same path, or to even use /.

as the terminal points out, the path to the config file contains both.

**Comment by rgrams** [comment] 2016-07-05 17:36
Ahhh, alright, deleting the config stuff seems to have solved the total settings wipe, thanks! Some random settings still resetting as before, but that's another issue.

**Comment by reduz** [comment] 2016-07-06 12:41
@rgrams by chance you don't have that editor_setrings.tres that has an invalid identifier error right?

**Comment by reduz** [comment] 2016-07-06 12:42
if any of you runs into this again please keep the file

**Comment by rgrams** [comment] 2016-07-06 16:45
@reduz here's the old .tres and .xml
[godot_editor settings files.zip](https://github.com/godotengine/godot/files/350420/godot_editor.settings.files.zip)

**Comment by reduz** [comment] 2016-07-06 22:45
I don't see anything wrong with the tres and it seems to load it fine, I'll just leave closed but let me know if you experience something like that again (just post the broken .tres file)

**Comment by ankhzet** [comment] 2024-09-11 06:24
8 years later, same problem
