### ISSUE TITLE
Wrong shadows when use VIEW_MATRIX in VERTEX calculation

### ISSUE THREAD

**Issue by BasilYes** [godotengine/godot#80814] opened 2023-08-20 10:28 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12018.5) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads). Same on Fedora 38

### Issue description

When I use VIEW_MATRIX to calculate VERTEX, shadows dont effected by this.
![image](https://github.com/godotengine/godot/assets/36816595/bf01531d-5f5a-49e2-b3a3-4d481d56d2be)
shader code
```
shader_type spatial;


void vertex(){
	VERTEX = (vec4(VERTEX, 1.0) * VIEW_MATRIX).xyz;
}
```

### Steps to reproduce

Just apply this shader, to any mesh and it's will broke shadows
```
shader_type spatial;


void vertex(){
	VERTEX = (vec4(VERTEX, 1.0) * VIEW_MATRIX).xyz;
}
```

### Minimal reproduction project

[ShaderResearch.zip](https://github.com/godotengine/godot/files/12387945/ShaderResearch.zip)

**Comment by clayjohn** [comment] 2023-08-20 15:08
This is a duplicate of https://github.com/godotengine/godot/issues/41420

The issue comes from the fact that the VIEW_MATRIX used by the shadow calculations is the light's VIEW_MATRIX, not the camera's VIEW_MATRIX. 

There is already a PR to fix this: https://github.com/godotengine/godot/pull/72638

**Closed by clayjohn** 2023-08-20 15:08 UTC
