### ISSUE TITLE
_ready method is not subject to the inheritance rules like other user methods

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#38274] opened 2020-04-27 22:26 UTC
**Godot version:**
v3.2.2.rc.custom_build.36a30f681

**OS/device including version:**
Windows 10

**Issue description:**
The _ready method (and other similar methods like _process) is called for both the base class and derived class despite it is not explicitly called in the derived class. This surprised me a bit.
This prevents overwriting the implementation of the base class.

Shouldn't the base class method be called explicitly in derived class? Like this:

```
func _ready():
	._ready()
```

**Comment by KoBeWi** [comment] 2020-04-28 01:02
`_ready()` is not a "user method" though, it's inherited from a built-in class. Methods like `_ready()`, `_process()` or `_input()` etc. are called in the whole inheritance tree automatically. AFAIK there are plans for a GDScript rework that gets rid of this behavior, but it won't happen until Godot 4.0/4.1 (because compatibility)

**Comment by Calinou** [comment] 2020-04-28 07:31
Duplicate of #29271.

**Closed by Calinou** 2020-04-28 07:31 UTC
