### ISSUE TITLE
Can't Play the Project (F5) when in full screen edit mode

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#6911] opened 2016-10-24 01:31 UTC
**Operating system or device - Godot version:**
OS X 10.11.6
Godot Version 2.1 stable official

**Issue description** (what happened, and what was expected):
When I am editing text in full screen mode (as in I press Command Shift F11) I can't just run the project by pressing F5.  I have to press CMD - SHIFT - F11 to exit full screen / edit mode and then press F5.  When done, I have to re-enter again with CMD - SHIFT - F11.  I'm getting quite good at this but it's a bit of a chore.

**Comment by Noshyaar** [comment] 2018-04-07 04:48
I can't reproduce this on latest master, Antergos x86_64. Can anyone using OSX confirm the issue?

**Comment by KoBeWi** [comment] 2019-05-31 23:07
Looks like it was fixed in 3.0.

**Closed by KoBeWi** 2019-05-31 23:07 UTC
Labels: bug, topic:editor, usability
