### ISSUE TITLE
Visual Scripting shader "make unique" not working as expected

### ISSUE THREAD

**Issue by Valinakova** [godotengine/godot#47821] opened 2021-04-12 07:57 UTC
Godot version 3.2.3
GLES3

AMD Rx 550 Series

Hi again, I believe I may have found another bug.

When I duplicated the object with the shaders on it, than made both the material and the shader unique, than tried editing the texture, the changes translate to other objects. Duplicating the textures by right-click duplicate and rename them than place the duplicated texture to the object for editing doesn't always resolve the issue, as even then, the editing the duplicates still causes the changes to translate to the originals. 

**Steps to reproduce:**

Duplicate an object (try the IcoSphere which is something I imported), or a godot created sphere. Attempt to make the shader and material Unique. Do this by right click on the material and make "unique", do the same for the shader. Try changing some of the settings such as the values in the distortion or the noise shader, and it would duplicate the changes to other object's textures when it shouldn't. 

Also try right-click duplicate + rename the material and shader. Duplicated sphere and remove the texture on the duplicate. Than apply both the duplicated material and shader. Try changing the texture's settings, sometimes it would change the settings of other textures despite being a different shader.

[Bug_testing2.zip](https://github.com/godotengine/godot/files/6294751/Bug_testing2.zip)

**Comment by Valinakova** [comment] 2021-04-12 07:58
cc @Chaosus

**Comment by KoBeWi** [comment] 2021-04-12 14:33
Every VisualShader node is a separate resource, so that might be the issue.

**Comment by Chaosus** [comment] 2021-04-27 14:02
Duplicate of https://github.com/godotengine/godot/issues/36882

**Closed by Chaosus** 2021-04-27 14:02 UTC
Labels: bug, topic:shaders, topic:visualscript
