### ISSUE TITLE
Expand on the editor UI customizability

### ISSUE THREAD

**Issue by RiverMesa** [godotengine/godot#12742] opened 2017-11-08 08:19 UTC
So currently, Godot has a very neat editor interface that offers *some* customization (theming, the ability to have tabbed dockers that can be put on either side of the window, custom tools with addons), however it doesn't really go too far beyond that (although that's arguably plenty already).
The way you actually move the tabs around is a bit clunky and at first maybe even confusing, and you can't resize any of the tabs, nor have more than 2 on any given available location.

There is however, one program that I think *really* nails the UI customization, and that's [Krita](https://krita.org) - the poorly-recorded GIF will probably showcase that better than I can in words.

![Krita UI customization](https://i.imgur.com/YeURp08.gif)

As you can see, any particular docker can be dragged and dropped onto almost any area of the screen (including on top of other dockers, in which case tabs are created), as well as resized, even if it makes other nearby dockers (or the actual image viewport) small to the point of unusability.

While not shown in the GIF, Krita also allows for any of those dockers to be disabled and enabled entirely, either directly from the docker itself, or from a drop-down menu in the toolbar.

Now, I'm not suggesting to copy what Krita does 1:1, if that is even possible without reworking huge chunks of Godot's UI code (Krita runs on top of Qt5 and KDE librarires, which likely handle a lot of the workload for it), but I do think that the ability to further adjust one's UI to their particular workflow and preferences (as well as being able to save, load and share such presets, which Krita also offers) would be hugely beneficial.

**Comment by groud** [comment] 2017-11-08 10:12
Looks a little bit like a duplicate of #8250.

**Comment by Calinou** [comment] 2019-10-02 14:46
Duplicate of #8250.

**Closed by Calinou** 2019-10-02 14:46 UTC
Labels: feature proposal, topic:editor
