### ISSUE TITLE
Incremental compilation borked on 3.2 branch

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#39117] opened 2020-05-28 09:41 UTC
**Godot version:**
3.2 branch commit 1339976
Scons 3.1.2
Linux Mint

**Issue description:**
Incremental compilation is broken, I have bisected it down to be being caused by the above commit. It works in the commit before.

Touching a cpp or simply rerunning Scons repeatedly, without editing any files, compiles a large number of files.
It doesn't appear to be a full rebuild, it seems to be compiling most or all files in modules and thirdparty directories every time.

Further info - I was changing `drivers/gles2/rasterizer_canvas_gles2.cpp`, in case which cpp affects whether this happens - however it now appears that touching a file is not necessary.

**Steps to reproduce:**
Pull the commit mentioned, rebuild, then run Scons again (or touch a cpp first).

**Comment by akien-mga** [comment] 2020-05-28 09:58
CC @Xrayez

**Comment by Xrayez** [comment] 2020-05-28 10:14
I'm not really sure why this would happen at first thought. Perhaps the list iterating the modules is unordered, but nonetheless it's sorted in:

https://github.com/godotengine/godot/blob/133997654cf77ba8effdde0f4f11fdf65cb32e72/SConstruct#L457

Yet maybe this list can be sorted even earlier:

https://github.com/godotengine/godot/blob/133997654cf77ba8effdde0f4f11fdf65cb32e72/SConstruct#L192-L213

I'll test this locally, but I have to say I've had incremental compilation issues long before 1339976.

**Comment by Xrayez** [comment] 2020-05-28 10:46
Can't reproduce on Windows, SCons v3.1.2, Python 3.6.4.

Compiled four times: before the commit, and with commit, while changing `drivers/gles2/rasterizer_canvas_gles2.cpp`.

**Comment by lawnjelly** [comment] 2020-05-28 11:48
Just to update: We seem to have pinned this down to the version of python.

### My PC
Linux Mint 18.3
I have Scons 3.1.2 installed, old version is uninstalled.
Python 2.7.12 is installed and default, and advice is not to upgrade the default because of conflicts with the OS.
Looking in `usr/lib`
It seems I have python 2.6, 2.7, 3 and 3.5 installed (3.5 was installed in order to compile Godot 4.x).

### Python
I had changed the shebang (first line) of scons in usr/local/bin to python3 (this seemed to be the recommended way to get it to override the default and work to compile Godot 4.x).

_However_ for some reason this was causing this issue to exhibit with this PR. We found that if I changed the shebang BACK to just python, the compilation would take place as expected.

So it is possible there is some conflict occurring as a result of having python 2 (default) and 3 on the same system.

This is just straight feedback, I am very much a linux beginner, and not familiar with python or scons. :+1:

**Comment by Xrayez** [comment] 2020-05-28 12:52
I've discovered some recent issue regarding incremental build: #25403, might worth checking out for hints.

**Comment by lawnjelly** [comment] 2020-05-28 13:14
Following the hints in #25403 I've run with `--debug=explain --taskmastertrace=trace.log`.

The debug explain shows that it thinks that lots of files have changed when they haven't. This is just a sample, it could well be thinking all files have changed:
```
        `modules/theora/video_stream_theora.cpp' changed
           `core/os/os.h' changed
           `core/project_settings.h' changed
           `thirdparty/misc/yuv2rgb.h' changed
           `modules/theora/video_stream_theora.h' changed
           `core/engine.h' changed
           `core/image.h' changed
           `core/io/logger.h' changed
           `core/list.h' changed
           `core/os/main_loop.h' changed
           `core/ustring.h' changed
           `core/vector.h' changed
           `core/object.h' changed
           `core/os/thread_safe.h' changed
           `core/set.h' changed
           `core/typedefs.h' changed
           `core/io/resource_loader.h' changed
           `core/os/file_access.h' changed
           `core/os/semaphore.h' changed
           `core/os/thread.h' changed
```
If it thinks all files have changed, it is interesting that it only seems to be rebuilding modules and thirdparty, and not everything...

**Comment by Xrayez** [comment] 2020-05-28 16:04
Already fixed by #39121 on 3.2, waiting for the same patch to be available for 4.0 with #39125.

But I wanted to say that, somehow even while testing this with Python 2.7, I couldn't really reproduce the issue, but I think that I've got lucky enough for the same list of modules to remain in order every build, preventing full rebuild. Or might certainly be implementation-defined behavior specifically exhibited on (Windows) interpreter, who knows. :eyes:

**Comment by akien-mga** [comment] 2020-05-28 18:55
> But I wanted to say that, somehow even while testing this with Python 2.7, I couldn't really reproduce the issue, but I think that I've got lucky enough for the same list of modules to remain in order every build, preventing full rebuild.

Well that's because, again, @lawnjelly's issue was with Python **3.5** :) https://github.com/godotengine/godot/pull/39121#issuecomment-635393280
Python 2.7 works fine, it likely had the bug fixed or is using a completely different system for dictionaries which doesn't exhibit this de-ordering issue in the first place.

So you'd need to test with Python 3.5 (possibly also earlier 3.x) to reproduce it.

**Closed** 2020-05-28 18:55 UTC
Labels: bug, cherrypick:3.2, topic:buildsystem

**Comment by bdbaddog** [comment] 2020-05-29 20:01
Is it possible it was someone switching back and forth between py 2.7 and 3.5?

**Comment by lawnjelly** [comment] 2020-05-30 05:26
> Is it possible it was someone switching back and forth between py 2.7 and 3.5?

Well it could have been something to do with intermediate files.

Situation in the end was that it worked when the Scons file 1st line shebang just contained `python`, but didn't work when it contained `python3`.

I think though the conclusion was that there was some python feature used that was 3.6-3.7 only in the PR, and it wasn't present in 3.5 (rather than a problem with Scons itself). But that is just my understanding, @Xrayez and @akien-mga  would be able to tell you more.

There's more info on the IRC logs here:
https://godot.eska.me/irc-logs/devel/2020-05-28.log

**Comment by Xrayez** [comment] 2020-05-30 08:56
1. A list of modules was refactored to a dictionary of modules in 1339976.
2. Developing the feature on Python 3.6 couldn't allow me to detect the limitations of dictionaries not guaranteeing the order of insertion... (and tbh I've never had to extensively develop in older versions of Python).
3. The order determines the contents of `modules/modules_enabled.gen.h` which is included in some sources and `modules/register_modules_types.gen.cpp`. Obviously shuffling the order makes SCons think that the files are changed, so they need to be rebuilt.

I wonder whether it could be useful to determine whether those files are modified by writing a custom `env.Decider` function, like `len(modules_contents) == previous_length`, but that's probably more hacky than the above fix.

**Comment by bdbaddog** [comment] 2020-05-31 01:59
@Xrayez - yup that'd be more hacky.  Dict insertion order maintenance starts in py 3.6.. so likely that was the root of your issue. Glad you found a solution.
