### ISSUE TITLE
RichTextLabel does not expand to show content

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#64142] opened 2022-08-09 06:49 UTC
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

A "Min Size" needs to be set to a RichTextlabel to show its content.
"Fit content to Height" does not do the job.
"Size Flags" set to Fill/Fill dont to the the job.

![image](https://user-images.githubusercontent.com/23613040/183583118-b4a4e1c7-de79-4dd9-86c0-15c0bb60b752.png)

### Steps to reproduce

see above

**Comment by Calinou** [comment] 2022-08-09 09:25
Duplicate of https://github.com/godotengine/godot/issues/18260.

**Closed by Calinou** 2022-08-09 09:25 UTC
