### ISSUE TITLE
Can't get method on CallableCustom "Delegate::Invoke" error

### ISSUE THREAD

**Issue by VirmaY-chr** [godotengine/godot#79121] opened 2023-07-06 17:34 UTC
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 10

### Issue description

After frequent build, a lot of errors occurs:

`Can't get method on CallableCustom "Delegate::Invoke".
core/object/object.cpp:1058 - Error calling from signal 'timeout' to callable: 'Node::': Method not found.
modules/mono/managed_callable.cpp:92 - Condition "delegate_handle.value == nullptr" is true.`

The "Build" button gets blocked and every time I need to restart the project. Deleting `.godot` folder doesn't help.

### Steps to reproduce

Build the solution 3-4 times and get this error flow.

### Minimal reproduction project

[gd-sai-delegate-error.zip](https://github.com/godotengine/godot/files/11970719/gd-sai-delegate-error.zip)

**Comment by RedworkDE** [comment] 2023-07-06 18:17
Duplicate of #70026

**Closed by RedworkDE** 2023-07-06 18:17 UTC
