### ISSUE TITLE
GDScript 2.0 - Generated documentation icon doesn't match Create Node dialog icon

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#68611] opened 2022-11-13 13:37 UTC
### Godot version

v4.0.beta4.official.e6751549c

### System information

Arch Linux

### Issue description

The icon shown in the generated doc page for a custom class without a custom icon does not match the icon shown for the same class in the Create Node dialog.

For example, take this script:
```gdscript
class_name CustomClass
extends Node
```

The Create Node dialog shows the same icon as the parent class.
![Create New Node dialog](https://user-images.githubusercontent.com/5725958/201510392-55ce73e6-0c80-41c0-af35-2d9c737724e7.png)

This icon matches the icon shown once the node with the custom class is created.
![Node](https://user-images.githubusercontent.com/5725958/201510522-9445ea77-b5c2-4dfa-bbd1-e4f44272bf47.png)

The documentation always shows the ArrowRight icon.
![Generated documentation page custom class](https://user-images.githubusercontent.com/5725958/201510433-fe7e51d4-15e7-49a2-aa6e-595962a81461.png)

The Search Help dialog also always shows the ArrowRight icon.
![Search Help dialog custom class](https://user-images.githubusercontent.com/5725958/201511465-c5853852-1f0d-4b0c-bad7-1545bfbd04ab.png)

This also occurs for generated docs for a script without a class_name.
```gdscript
extends Node
```
![Generated documentation page](https://user-images.githubusercontent.com/5725958/201524467-ac58c445-ec63-4615-8af6-36a2cb31202d.png)
![Search Help dialog](https://user-images.githubusercontent.com/5725958/201524465-2343bf1f-32ce-4d70-a5ac-7cbfdf2b1f97.png)

The doc page icon should match the Create Node icon, for any parent class.

### Steps to reproduce

1. Create a script extending any Node, optionally using `class_name`. Do not add an icon with `@icon("")`.
2. Look at the generated doc page for this class. The icon is ArrowRight.
3. Open the Create New Node dialog, and find the class. The icon matches the parent class.

**Comment by Chaosus** [comment] 2022-11-13 18:22
Duplicate of https://github.com/godotengine/godot/issues/68316

**Closed by Chaosus** 2022-11-13 18:22 UTC
