### ISSUE TITLE
GLTF import should use the ORM Material instead of the Standard Material

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#70979] opened 2023-01-06 04:04 UTC
### Godot version

4.0 beta 10

### System information

Windows 10 960m

### Issue description

Currently any imported gltf scene will be automatically setup to use the Standard Material 3d shader. Since gltf files have the Occlusion, Roughness and Metalness channels packed into one texture as part of the format spec, it would make more sense that Godot uses the ORM Material shader.

Otherwise you lose some performance since the Standard shader is doing 5 texture lookups per material. The ORM shader will use 3 texture lookups and therefore be more performant, especially if you have large texture sizes and many objects in a scene.

As can be seen in this screenshot, when opening up a gltf import, the standard shader is being used by default:

![gltf_orm](https://user-images.githubusercontent.com/7741669/210927634-21ebab6e-f2e5-4b73-82d7-8fbc51280538.jpg)

### Steps to reproduce

- import a gltf file that has been properly authored with the PBR spec
- if you open up the file in Godot, it can be seen that the default shader has been used

### Minimal reproduction project

[gltf_orm.zip](https://github.com/godotengine/godot/files/10357260/gltf_orm.zip)

**Comment by Calinou** [comment] 2023-01-06 23:13
Duplicate of https://github.com/godotengine/godot-proposals/issues/2955.

**Closed by Calinou** 2023-01-06 23:13 UTC
Labels: bug, topic:import, topic:3d
