### ISSUE TITLE
Matrix32 returns null in xform and basis_xform

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#2265] opened 2015-07-14 11:35 UTC
I try, try and try for hours to find the problem in my code!
Matrix32 return null in xform whem I passa another matrix32 to it.
(I work on a progressive transformation system)

**Comment by akien-mga** [comment] 2015-11-10 16:39
Can you still reproduce it in the current master branch?

**Comment by marcosbitetti** [comment] 2015-11-26 11:24
Well, I lose the code piece ( I try a lot of solutions inside file). But I think that is a problem on thread when accessing a value in an object recently handled.
I have a similar issue in this code this morning, when I try to catch some element on a dictionary it crashes the game (note the last comment on this file):

			tool
			extends "res://scenes/tmp_data/grass2.gd" # extends Spatial

			# data format structure
			# mesh_layers_data
			# 	is a struc of objects typed:
			#		


			# convert old version of plugin data to new data structure
			func convert_mesh_layer_v102_to_v103(_mesh_layers_data):
				# pass 1 - convert layer models to support lod levels
				var tmp = []
				for ld in _mesh_layers_data:
					var v = Dictionary()
					v.mesh =  ld
					v.near = 0.0
					v.far = 100.0
					v.resource = null
					var lvs = []
					lvs.append(v)
					tmp.append(lvs)
				return tmp
				


			var space_division_size = Vector3(10,0,10)


			func _setup_matrix():
				var aabb = get_parent().get_aabb()
				#var dist = aabb.size / grass_step
				var mts_z = Array()
				
				# mount matrixes grid
				var dist = space_division_size / grass_step
				for mt_z in range(ceil(aabb.size.z / space_division_size.z)):
					var mts_x = Array()
					for mt_x in range(ceil(aabb.size.x / space_division_size.x)):
						var mt = Array()
						var offset = Vector3( mt_x*space_division_size.x, 0, mt_z*space_division_size.z )
						var zz = aabb.pos.z + offset.z
						for z in range(ceil(dist.z)):
							var xx = aabb.pos.x + offset.x
							for x in range(ceil(dist.x)):
								var dt = Transform()
								dt.origin = Vector3(xx,0,zz)
								mt.push_back(dt)
								xx += grass_step
							zz += grass_step
						mts_x.append(mt)
					mts_z.append(mts_x)
				return mts_z

			func setup_matrix():
				var dist = space_division_size / grass_step
				var mt = Array()
				var zz = -dist.z/2
				for z in range(ceil(dist.z)):
					var xx = -dist.x/2
					for x in range(ceil(dist.x)):
						var dt = Transform()
						dt.origin = Vector3(xx,0,zz)
						mt.push_back(dt)
						xx += grass_step
					zz += grass_step
				return mt

			# load resources
			func setup_resources():
				#var data = []
				#for ml in mesh_layers_data:
				#	for m in ml:
						#mesh_layers.push_back( ResourceLoader.load(m,'Mesh') )
						#m.resource = ResourceLoader.load(m.mesh,'Mesh')
				#		data.append(m)
				#mesh_layers.append(data)
				for m in material_layers_data:
					if not m.empty():
						material_layers.push_back( ResourceLoader.load(m,'Material') )
					else:
						material_layers.push_back( false )


			func _ready():
				#self.ready()
				
				mesh_layers_data = convert_mesh_layer_v102_to_v103(mesh_layers_data)
				#setup_resources()
				
				var mat = setup_matrix()
				
				#mount grid
				var aabb = get_parent().get_aabb()
				var dist = space_division_size / grass_step
				var center = dist / 2
				for mt_z in range(ceil(aabb.size.z / space_division_size.z)):
					for mt_x in range(ceil(aabb.size.x / space_division_size.x)):
						var mt = Array()
						var offset = Vector3( mt_x*space_division_size.x, 0, mt_z*space_division_size.z )
						var zz = aabb.pos.z + offset.z + center.z
						for ml in mesh_layers_data:
							var multimesh_i = MultiMeshInstance.new()
							var multimesh = MultiMesh.new()
							print(ml.far) # this line make crash!
							#multimesh_i.set_multimesh(multimesh)
							#multimesh_i.set_draw_range_begin(ml.near)
							#multimesh_i.set_draw_range_end(ml.far)
				


I already reported some problems with data in other issues, with arrays initialization.

**Comment by reduz** [comment] 2016-01-02 15:08
I can't really tell what's going on.. was this issue fixed in HEAD?

**Comment by marcosbitetti** [comment] 2016-01-03 02:06
It remains in current  HEAD

**Comment by akien-mga** [comment] 2016-07-21 09:18
It would be nice to have a minimal example that reproduces the issue, the above script is a bit lengthy to debug such an issue :/

**Comment by Zylann** [comment] 2017-12-18 22:28
I just ran into this issue in 2.1.4:
```gdscript
	var a = Matrix32()
	var b = Matrix32()
	var c = a.xform(b)
	print("c = ", c)
```
The following prints:
```
c = 
```
Nothing

**Comment by bojidar-bg** [comment] 2018-04-27 13:12
Note that both `variant_call.cpp` and `transform.h` define only Vector3, Plane, and AABB as valid arguments:
https://github.com/godotengine/godot/blob/b35f3a569e578c5ff7eb73257f84d74e30e361d1/core/variant_call.cpp#L767-L776
https://github.com/godotengine/godot/blob/b35f3a569e578c5ff7eb73257f84d74e30e361d1/core/math/transform.h#L78-L85

**Comment by Chaosus** [comment] 2018-08-29 13:56
You cannot pass matrix32(or Transform in 3.1) to xform. This issue is formed by invalid usage. I think its not a good idea to pass check to xform too, because its performance critical function. I think this should be closed. What do you think @akien-mga ?

**Comment by akien-mga** [comment] 2018-08-29 14:04
Well it's invalid usage, but then the bug is that the engine doesn't trigger an error when calling `Transform.xform` with wrong arguments.

Also https://github.com/godotengine/godot/issues/2265#issuecomment-383389033 seems to be the intended usage (calling it with a Vector3), but it's not working either apparently.

**Comment by Chaosus** [comment] 2018-08-29 14:10
`transform.xform(position)` seems to be worked

**Comment by aaronfranke** [comment] 2019-05-08 09:17
Does this issue apply to only Transform2D, or also Transform (3D)?

**Comment by KoBeWi** [comment] 2019-05-19 23:18
> Does this issue apply to only Transform2D, or also Transform (3D)?

It applies to both. Also documentation tells you what arguments are valid.

**Comment by Anutrix** [comment] 2019-10-04 21:25
What's the status on this?

**Closed** 2020-04-29 07:32 UTC
Labels: bug, topic:core
