### ISSUE TITLE
Instanced scenes in the editor keep their locks when added to the tree

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8322] opened 2017-04-08 19:04 UTC
**Ubuntu 16.10- Godot version: 2.1.2**

**Issue description:**
Editor locks are useful when editing a scene, but adding a scene to the tree (in the editor) and keeping the locks of the original scene root does not make much sense, maybe only when working with scene inheritance.

Current behaviour also undo any lock change you make when editing the instanced scene or reloading the project/scene with instances.

I think that the original locks of scenes added to the tree should be ignored, this may let the scene with instances use their own locks and will reduce the accumulation icons on the tree too.

**Steps to reproduce:**
- Create a scene, put some locks to the root node.
- Instance that scene on another, the locks are there.
- Plus: change the locks on the instanced scenes.  
- Reload the scene with the instances, the locks appear there again.

**Comment by akien-mga** [comment] 2019-04-15 14:32
Doesn't seem to be a bug to me if I understand the issue correctly. When you instantiate a scene in another scene, locks are not displayed initially.

They are only visible if you give the instantiated scene the "Editable Children" property, which means indeed that you can edit its properties, including locks. So you can indeed unlock a node of a specific scene instance with "Editable Children", and move things around. So far I would say that it's a feature and it works well.

Then there is one thing which might be slightly confusing, which is covered by the above steps to reproduce, and which I can confirm:
- Instantiate Child scene in Parent scene, set Editable Children
- Disable lock in Child scene, move previously locked node around
- Save Parent scene, close it, reopen it
- The lock is back in the Child scene. One might expect that it should not be readded since it had been removed earlier

IMO the new lock status of the instantiated scene could be saved in its parent scene to solve it.

**Comment by eon-s** [comment] 2019-04-16 09:13
Yes, lock are displayed and reappear after loading the scene, no matter the _local_ status of the lock.

I will try to be more clear...

1st, one may want to lock the root to not move it while editing a scene, this is usually done for nearly every single root node with position:
![scenelock1](https://user-images.githubusercontent.com/10215987/56196843-00c17d80-600e-11e9-9c85-68fce43e4a19.png)

Then, when instancing the scene on another, the normal workflow is to position the node somewhere else, but appears with its original lock.
![scenelock2](https://user-images.githubusercontent.com/10215987/56196930-2ea6c200-600e-11e9-9305-b891b02b7e9e.png)

If you remove the lock, then reload the scene, the lock appears again...

The current options are:
1: Remove the lock from the original scene, but then it can be messed up by accident, needs to set the lock every time it needs to be edited, and remove before saving, too complicated.
2: Remove the lock every time there is a need to reposition the instanced scene, this is annoying and pollutes the scene with useless locks when you have many instanced scenes.

What I think is that the lock should be applied only locally, not be added with the instanced scene too because the context is different.

**Comment by akien-mga** [comment] 2019-05-06 08:58
Related to #14462.

**Comment by akien-mga** [comment] 2021-04-23 21:14
Still valid as of 3.3-stable (see e.g. #47836).

**Comment by KoBeWi** [comment] 2022-01-16 00:51
This is the same issue as #12838, which explains the problem more clearly, so closing.

**Closed by KoBeWi** 2022-01-16 00:51 UTC
Labels: enhancement, discussion, topic:editor, confirmed, usability
