### ISSUE TITLE
PopupMenu does not oversample correctly.

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot#76449] opened 2023-04-25 19:05 UTC
### Godot version

4.0.2.stable

### System information

Windows 11, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/20043270/234376433-f79c8151-16d5-4509-9aab-e5ef51d6187e.png)

As seen in the above image, when using the canvas_items scaling mode, MenuButton items font does not render correctly, instead rendering at default resolution.

### Steps to reproduce

Download repro project, run test_ui.tscn and click the ">_" button in the top left.

### Minimal reproduction project

[UIScalingTest.zip](https://github.com/godotengine/godot/files/11325900/UIScalingTest.zip)

**Comment by EMBYRDEV** [comment] 2023-04-25 19:14
![image](https://user-images.githubusercontent.com/20043270/234379112-64b25493-bb70-4551-aba5-d73d199afb26.png)

Upon further investication, it looks like the canvas_items scaling mode just isnt playing nice with the PopupMenu node... This is with the corner radius set in the theme so it isnt relying on any bitmap assets.

**Comment by EMBYRDEV** [comment] 2023-04-25 19:23
This may be related to #76450 as both utilise sub-viewports.

**Comment by Calinou** [comment] 2023-04-25 19:45
- Duplicate of https://github.com/godotengine/godot/issues/70791.

**Closed by Calinou** 2023-04-25 19:45 UTC
