### ISSUE TITLE
Expose type safe API for using AnimationNode derivatives

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#21399] opened 2018-08-25 07:04 UTC
**Godot version:**
`master` / f72f74486d3

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
Before the refactorings introduced in c7e4527a88, each subtype of `AnimationNode` provided type safe (at least for C#) API to use its functionalities, like `AnimationNodeBlend2.Amount` for example.

However, now it seems that the only way to use such functionalities is to use parameters (except for `AnimationNodeStateMachinePlayback`, which also needs to be obtained as a generic parameter), which is not type-safe and difficult to figure out what properties are available from the documentation.

Along with #19878, I think it has reduced the usability of the API quite significantly, so I wish the old type safe API could be restored, so it can be used in conjunction with the new parameter based approach.

**Comment by reduz** [comment] 2019-01-12 12:08
This has been finally properly documented, so closing this issue. This change was intended.

**Closed by reduz** 2019-01-12 12:08 UTC
Labels: enhancement, topic:core
