### ISSUE TITLE
script editor- fold doesnt fold the whole code- commented code interrupts folding

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13191] opened 2017-11-22 21:12 UTC
See bellow
![bugfolding](https://user-images.githubusercontent.com/6495061/33149984-99584ce4-cfc9-11e7-97ee-ab59e5f95582.gif)

found 2 bugs actually- probably related to one another
1. commented code should not be treated as something to be folded/unfolded
2. commented code should not interrupt  folding of parent function

**Comment by kubecz3k** [comment] 2017-11-22 21:59
sorry it's a duplicate of https://github.com/godotengine/godot/issues/13107

**Closed by kubecz3k** 2017-11-22 21:59 UTC
Labels: archived

**Comment by blurymind** [comment] 2017-11-22 22:10
ah sorry, I didnt see the other one
