### ISSUE TITLE
(3.3 rc9) Poor performance overall

### ISSUE THREAD

**Issue by TronchitoSawer** [godotengine/godot#47897] opened 2021-04-14 19:26 UTC
**Godot version:**
3.3 rc9

**OS/device including version:**
WINDOWS 10, ASUS VivoBook with AMD Ryzen5-2500U,

**Issue description:**
Poor performance in general, both when using the menus in the editor (changing between scenes, for example), and when starting the project, which has frame drops that were not seen with the previous version (3.2.2 stable). Actually, this started happening from version 3.2.3, and I didn't say anything then (my fault, sorry, I was a rookie), because I was hoping that the new versions would fix the problem. But it has not been like that, I have tried the RC versions since 6, and in all of them the problem persists.
By the way, my project is a Bullet Hell shooter, with a lot of bullets on the screen. In 3.2.2 version, it runs at 60 stable fps, however, in later versions frame rate is unstable, with frame drops from 5 to 20 fps.
Thanks. 

**Steps to reproduce:**
Only opening Godot and charging any project, everything goes slow.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-04-14 19:39
> By the way, my project is a Bullet Hell shooter, with a lot of bullets on the screen. In 3.2.2 version, it runs at 60 stable fps, however, in later versions frame rate is unstable, with frame drops from 5 to 20 fps.

Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by TronchitoSawer** [comment] 2021-04-15 12:16
Yes. I will attach a little project that is a retail version of a bullet spawner which I´m working on, but it illustrates what I said earlier, at least on my laptop. When I run it with version 3.2.2 it runs at a stable 60fps, however when I run it with a later version I experience drops of up to 12fps. Anyway, you can vary some parameters to test (some of these parameters don't work because this project comes from a trimmed version of the main one).
However , with this project I have not been able to reproduce the slow loading between scenes, I imagine that because of how small it is.


[TESTING.zip](https://github.com/godotengine/godot/files/6317788/TESTING.zip)

**Comment by rainlizard** [comment] 2021-04-16 07:32
Can't reproduce.

(disabled vsync since I was getting solid 60)
v3.3-rc9_win64: ~190 FPS at 1600 bullets on screen
v3.2.2-stable_win64: ~205 FPS at 1600 bullets on screen
CPU i7-4790K, 16GB RAM, 970 GTX.

Are you another victim of the Remote Scenetree? 1600 nodes will make your game lag if you have the Remote Scenetree up.

**Comment by akien-mga** [comment] 2021-04-16 07:57
Testing on Linux with:
```
System:    Host: cauldron Kernel: 5.11.14-desktop-1.mga9 x86_64 bits: 64 Desktop: KDE Plasma 5.21.3 Distro: Mageia 9 mga9 
CPU:       Info: Quad Core model: Intel Core i7-8705G bits: 64 type: MT MCP cache: L2: 8 MiB 
           Speed: 900 MHz min/max: 800/3100 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 5: 900 6: 900 7: 942 8: 900 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu v: kernel 
           Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision FHD Camera type: USB driver: uvcvideo 
           Display: x11 server: Mageia X.org 1.20.11 driver: loaded: intel,v4l resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 21.0.2
```

All tests at the "steady-state" at 1600+ bullets.

### Intel HD Graphics 630

v3.2.2-stable_x11.64: 145 FPS
v3.3-rc9_x11.64: 150 FPS

### AMD Radeon RX Vega M

v3.2.2-stable_x11.64: 160 FPS
v3.3-rc9_x11.64: 160 FPS

**Comment by mrjustaguy** [comment] 2021-04-16 10:03
If your Project loads slowly, Do you use Preloads in the Projects? if so that is same as #42688

As far as the runtime I have no ideas what's causing your slowdowns..

**Comment by TronchitoSawer** [comment] 2021-04-16 16:04
> Can't reproduce.
> 
> (disabled vsync since I was getting solid 60)
> v3.3-rc9_win64: ~190 FPS at 1600 bullets on screen
> v3.2.2-stable_win64: ~205 FPS at 1600 bullets on screen
> CPU i7-4790K, 16GB RAM, 970 GTX.
> 
> Are you another victim of the Remote Scenetree? 1600 nodes will make your game lag if you have the Remote Scenetree up.

By Remote Scenetree up do you mean if I turn it on once I run? No, when I run the scene, I always do it with "local" on. Anyway, when I turn off vsync the same thing happens to me, even the frame drops are more pronounced: with version 3.2.2 I get a stable 115 fps, and with later versions the fps become irregular, dropping to 80 fps. Anyway, my whole is limited to 60fps, and whith the vsyinc on.

**Comment by TronchitoSawer** [comment] 2021-04-16 16:10
> If your Project loads slowly, Do you use Preloads in the Projects? if so that is same as #42688
> 
> As far as the runtime I have no ideas what's causing your slowdowns..

Yes, I use many preloads becase it is a big project (two years of hard work in my free time),  With version 3.2.2, my project takes around 90 seconds to open, but once opened, switching between scenes is fast and smooth. However, with later versions, my project takes twice as long to open, and switching between scenes is very slow, everything goes with lag.

**Comment by TronchitoSawer** [comment] 2021-04-24 14:49
Hello again. I am using Godot 3.3 stable, and the problem still persits. When I change scenes on the editor, the change between them takes several seconds. Even when I open different scripts to edit them. Could it be some problem with the ram memory? My computer only has 8 gb, but it should be  #enoug: until version 3.2.3 it had not given me these problems? Have the system requirements perhaps gone up with the new versions?

**Comment by Calinou** [comment] 2021-04-24 16:26
> Have the system requirements perhaps gone up with the new versions?

This shouldn't be the case unless there's a memory leak somewhere. Can you reproduce this issue after disabling the [new BVH](https://godotengine.org/article/godot-3-3-has-arrived#dynamic-bvh) in the project settings?

**Comment by TronchitoSawer** [comment] 2021-04-24 19:32
> > Have the system requirements perhaps gone up with the new versions?
> 
> This shouldn't be the case unless there's a memory leak somewhere. Can you reproduce this issue after disabling the [new BVH](https://godotengine.org/article/godot-3-3-has-arrived#dynamic-bvh) in the project settings?

Hello, thanks for your reply. I´ve just dissabled BVH from project settings, and at least, the whole project loads faster at the begining (even faster than in 3.2.2), however, the change betwwen scenes in the editor and the opening of de scripts are still just as slow.

**Comment by Calinou** [comment] 2021-08-08 15:55
@TronchitoSawer Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or [Godot 3.4beta2](https://godotengine.org/article/dev-snapshot-godot-3-4-beta-2)?

**Comment by Calinou** [comment] 2021-11-14 18:14
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-11-14 18:14 UTC
Labels: bug, topic:rendering, needs testing, regression, performance
