### ISSUE TITLE
Strange behavior of NavigationAgent2D

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92184] opened 2024-05-21 03:54 UTC
### Tested versions

Godot 4.3 dev6 and Godot 4.2.2 

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

NavigationAgent2D sometimes gets stuck at intersections of NavigationRegion2D baked mesh
All parameters are default

https://github.com/godotengine/godot/assets/130399274/4c2eece8-d6ce-486f-8bfe-55c212508595

### Steps to reproduce

Create a huge navigation mesh, and use NavigationAgent2D to avoid obstacles

### Minimal reproduction project (MRP)

[nav.zip](https://github.com/godotengine/godot/files/15384201/nav.zip)

**Comment by JekSun97** [comment] 2024-05-21 08:49
I also want to clarify that I changed various properties of the agent itself, then returned everything to default, after which I began to notice this problem

**Comment by smix8** [comment] 2024-05-21 10:32
In this case it is a matter of adjusting the path desired distance and target desired distance to the agent's movement speed.

The agent in that test project moves at a speed of 550.0.

Using the default distances of  20 and 10 px there is no way at that speed that the agent does not regularly over- or undershoots the path positions. That is also what it gets stuck, it never is able to get to a position where it can increase its internal path index because the physics step movement distances are too large.

This is mentioned in the agent documentation under common problems as a setup issues here https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#pathfollowing-common-problems

**Comment by JekSun97** [comment] 2024-05-21 11:01
> In this case it is a matter of adjusting the path desired distance and target desired distance to the agent's movement speed.
> 
> The agent in that test project moves at a speed of 550.0.
> 
> Using the default distances of 20 and 10 px there is no way at that speed that the agent does not regularly over- or undershoots the path positions. This is also what gets the agent stuck. The agent is never able to get to a position where it can increase its internal path index because the physics step movement distances are too large.
> 
> This is mentioned in the agent documentation under common problems as a setup issues here https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#pathfollowing-common-problems
> 
> I rember there was an old Godot 3 PR #62682 from lawnjelly that tried to mitigate this by doing path segment checks but it was never ported to Godot 4 development branch and then closed. It would still be viable but by now the NavigationAgent logic has changed so much that the old PR would likely need a full rework.

I knew you would mention the motion speed option (forgot to remove it), I hope you set the speed to default and tested my project because this option didn't change anything, the PROBLEM is there, with all the default options.

(I don’t understand why immediately remove this problem from the bugs list, apparently it will drown in a pile of old problems...)

**Comment by smix8** [comment] 2024-05-21 11:11
You are right and it also happens on a few edges with reduced speed.

Likely the issue is amplified by some of the very, very, very long navigation mesh polygon edges. The agent uses Geometry2D edge segment checks internally and those naturally run into precision issues with very long segements. As soon as the edge length is reduced to a more manageable length the issue disappears for me using the defaults.

**Comment by JekSun97** [comment] 2024-05-21 11:14
How then can you increase your movement speed? I set the speed to 30, the problem is still there :'(

**Comment by smix8** [comment] 2024-05-21 11:43
I went back to the original state of your test project and the only thing that I changed was the size of the navigation mesh to reduce the edge length.

The issues only happens on navigation mesh polygons that are extremely large.

This tells us that this is at its core a precision issue with the geometry functions to find the closest position on a triangle. The navigation map needs to find the closest positions on the navigation mesh surfaces. It finds the closest polygon and then the closest position to the agent on the triangles of the polygon. When precision becomes an issue this will give positions that are more and more different with more and more larger gaps every time the agent moves a little and a new path is requested.

I now realized that your script updates the agent target position every single physics step with the mouse position.

When I remove that part or do the update with a timer on a longer interval (e.g. 0.5 sec) the precision issue is still visible with the path positions having larger than usual point gaps but the agent no longer gets stuck.

That very frequent path updates can cause problems is also mentioned in the common problems of the agent documentation. The reason why it is such a problem ( apart from performance) is that because the navigation map needs to find the closest positions on the navigation mesh surfaces this might give positions that are either behind or in front of the agent every time. Since an agent is just a point in pathfinding, it has no orientation, when the position is one update in front and one update behind the agent direction the agent gets stucked bouncing between the two constantly changing start positions.

**Comment by JekSun97** [comment] 2024-05-21 11:50
@smix8 Got it, thanks for the detailed explanation.
Is this a problem with the Recast library?
So big 2D worlds with pathfinding are not about Godot? Is there really no way to get around this problem?

**Comment by JekSun97** [comment] 2024-05-21 13:55
@smix8 I came up with an interesting method that could solve my problem, it is a slightly different pathfinding method, and its accuracy is not always perfect, but this pathfinding is used in Game Maker, and for most cases it is ideal, it would be great if it was added as additional option for pathfinding.

I attached NavigationRegion2D to my character who should look for a path, now NavigationRegion2D is a descendant of CharacterBody2D, we draw a region polygon around the character, the accuracy of the path depends on this region, and if after some time we constantly baked this region in a new way, it could bypass obstacles. Dynamic baking is certainly bad for performance, but this region is not large, only around the character, which would not greatly impact performance.

https://github.com/godotengine/godot/assets/130399274/b86cfc49-0eab-4e38-8fe4-b55c62a5cac7

And if NavigationRegion2D had a new Node mode in the SourceGeometryMode parameter, in it it would be possible to select a 2D node from the scene, which would store all the static objects that would participate in baking the region, then such a method could be used!

Such a pathfinding would look something like this:

https://github.com/godotengine/godot/assets/130399274/11b215cf-8f9e-4563-86fa-a94bacb313cd

such problems can occur if the region around the character is too small:

https://github.com/godotengine/godot/assets/130399274/9231dca4-f60d-4676-bfc3-0262586fabec

**Comment by smix8** [comment] 2024-05-21 17:19
Your idea is in general heading in the right direction as you only want navigation mesh within a reasonable distance around your active actors when dealing with large worlds. Your proposed solution might even be a working solution for some projects.

Naturally I am part of the doomsayer-squad that sees all the technical constrains that exist in the current navigation system that may cause problems for this so bear with me.

You said you added 100 agents and performance was nearly the same which I believe.

The performance issues do not directly correlate with the agent count and more with the navigation map and navigation mesh complexity. You can have ten thousands of agents if your entire navigation map only has 1-2 polygons to search through. Things are very different in performance when you have ten thousands polygons to search through just for 1-2 agents.

On a static navigation map with the navigation mesh not changing things will stay performance stable but as soon as you change region or navigation mesh the navigation map needs to update its navigation mesh polygon soup and all the edge connections. Those navigation map updates get increasingly costly the larger and more complex the combined navigation mesh gets.

While this is a general performanc issue with navigation meshes, by moving a NavigationRegion2D node with your agent like proposed it triggers such a costly navigation map update on every single frame. On top every single agent connected to that map will query a new navigation path on the map change. Because your moved region is still freeform the entire geometry parse and rebake of the navigation mesh is also far more costly compared to a simple grid-based navigation that just flips a cell state. I think you can see why this proposed approach will ballon into a performance issues quickly with the current system.

In general it is always better to not move regions and instead toggle static region chunks around the active actors.

![chunk](https://github.com/godotengine/godot/assets/52464204/2fb3d11e-9e75-40f3-bffa-700246fe3adc)

Keeping the region chunks in place avoids a good part of the heavy recalculations costs every frame that would happen when a region is moved. Also when regions stay fixed they can fit into a large world grid and this way can also more efficiently be rebaked for runtime changes. If regions are moved every frame arbitrary with agents all those things require very costly recalculations. That is why nearly all large open world games are done on static navigation mesh chunk systems.

**Comment by smix8** [comment] 2024-09-14 22:26
Closing as there is a proposal open to track the feature part of this discussion and there is no real actionable issue left here.

**Closed by smix8** 2024-09-14 22:26 UTC
Labels: discussion, documentation, topic:navigation, topic:2d

**Comment by lorenzo-arena** [comment] 2025-04-14 21:56
I'm having a similar set of issues as the one experienced by @JekSun97, as in I have various entities which try to reach a target position and some of them occasionally get stuck without any apparent reason. Is there any guide about what I should try to set as the NavigationAgent parameters? I'm trying to tweak them, however as soon as I manage to "solve" this particular issue other problems occur, like entities not being able to pass across an obstacles (maybe because it's "slim"?).
