### ISSUE TITLE
Character cannot actively affect RigidBody

### ISSUE THREAD

**Issue by ProgrammerMao** [godotengine/godot#66860] opened 2022-10-04 03:22 UTC
### Godot version

4.0 beta2

### System information

Win11 22H2, Intel UHD Graphics 730, 31.0.101.3413

### Issue description

Character移动的时候影响不到RigidBody
但是RigidBody移动时却可以正常的影响Character
Character自带脚本的和我自己写的脚本都会这样

The RigidBody is not affected when the character moves
However, when RigidBody moves, it can affect the character normally
Character's own script and my own script will be like this

---
我输出了一下RigidBody的碰撞对象
除了RigidBody主动碰撞Character
是不会出现Character的

I output the collision object of RigidBody
Except RigidBody active collision character
Character will not appear

---
我觉得原因是move_and_slide()把velocity的量调成了0
导致没有与RigidBody碰撞到

I think the reason is move_and_slide() sets the velocity to 0
As a result, there is no collision with RigidBody

---
https://user-images.githubusercontent.com/72609054/193727420-34927f43-e492-4be8-a30f-fadf1f444729.mp4

### Steps to reproduce

控制Character朝RigidBody移动
无法推动RigidBody

Controls character movement toward RigidBody
Unable to push RigidBody

### Minimal reproduction project

[Character cannot actively affect RigidBody.zip](https://github.com/godotengine/godot/files/9702506/Character.cannot.actively.affect.RigidBody.zip)

**Comment by Zireael07** [comment] 2022-10-04 08:01
Duplicate of #59473

**Comment by Chaosus** [comment] 2022-10-04 08:11
Duplicate of #59473

**Closed by Chaosus** 2022-10-04 08:11 UTC

**Comment by ProgrammerMao** [comment] 2022-10-04 09:06
> 的副本 #59473
Thanks
