### ISSUE TITLE
Singleton stops working after second run

### ISSUE THREAD

**Issue by rayosdev** [godotengine/godot#14493] opened 2017-12-10 03:08 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 Godot3 beta 1

**Issue description:**

singleton script isent registered at runtime after running edited scene twice. removal and re-adding in project settings needed in order for it to work again 

**Steps to reproduce:**

**Link to minimal example project:**
[sigelton_bug.zip](https://github.com/godotengine/godot/files/1545284/sigelton_bug.zip)

**Comment by Ranoller** [comment] 2017-12-10 05:18
This was fixed in #13841

**Comment by bojidar-bg** [comment] 2017-12-10 09:50
Yea, closing as duplicate of #13841 and thus fixed by #13989.

**Closed by bojidar-bg** 2017-12-10 09:50 UTC
