### ISSUE TITLE
MacOS editor in fullscreen has a menu bar / window focus issue related to dialogs and menus opening

### ISSUE THREAD

**Issue by johnpenny** [godotengine/godot#86027] opened 2023-12-11 11:25 UTC
### Tested versions

Reproducible in: 
- Godot v4.2.1.rc1.mono
- Godot v4.2.beta1.mono

NOT reproducible in:
- Godot v4.2.dev6.mono
- Godot v4.1.3.stable.mono

### System information

macOS 14.1.2 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads) - Also tested on macOS 14.0.0 before updating.

MacBook Pro 14" with notch.

### Issue description

It seems that dialogues in the MacOS editor, while fullscreen, cause the menu bar to not render correctly.

- Trigger any dialogue in the editor while fullscreen and the menu bar rendering breaks
- This also breaks the window menu popover
- Unfocussing and refocussing the window makes the menu bar appear again
- The menu bar items are still interactable, but are not rendered

https://github.com/godotengine/godot/assets/1178362/0c905c66-f074-4e19-a5e6-a7841c141e78

Video description:
- Using the menu bar 'Help > Copy System Info' is clicked and the menu bar remains visible
- A context menu (right click) is opened on a Node, and when the mouse clicks away from it the menu bar disappears
- The mouse clicks on the window menu to re-focus the editor window and the menu bar reappears
- Using the menu bar 'Scene > Save Scene' is clicked and the menu bar disappears once the save dialogue is done
- The mouse clicks on the window menu to re-focus  the editor window and the menu bar reappears
- A context menu (right click) is opened on a Node, and when the mouse clicks away from it the menu bar disappears
- The mouse hovers over the menu bar demonstrating that it is still interactable, but not rendering
- The window menu which should appear when hovering over the menu bar is not appearing
- The editor is now in full screen with no functioning window menu and a broken menu bar

Note that the window menu always remaining visible is undesirable behaviour or a separate bug, but I have used it here to demonstrate window refocussing.

### Steps to reproduce

Fullscreen the Godot editor and trigger a dialogue; The menu bar and window menu will be broken until you refocus the editor window.

### Minimal reproduction project (MRP)

Editor issue - any project file

**Comment by ShlomiRex** [comment] 2024-01-19 17:50
Can confirm on latest commit #7827c8e37 using Macbook M1 Pro, macOS Sonoma 14.2.1

To reproduce: 
* Maximize editor
* Click on "About godot" (for me its the name of the binary file: "About godot.macos.editor.dev.arm64"
* The "About" popup appears, close it
* Now the top-bar is not accessable (when mouse is near top-bar it won't unhide)

**Comment by GrubLady** [comment] 2024-07-05 00:20
Looks like this was fixed by a4f2e5210f80c3b2badfadcd7fe9004a26dbb221

**Comment by akien-mga** [comment] 2024-07-05 09:57
Fixed by #90131.

**Closed by akien-mga** 2024-07-05 09:57 UTC
Labels: bug, platform:macos, topic:editor, topic:porting, regression
