### ISSUE TITLE
Issue with tilemap/tileset

### ISSUE THREAD

**Issue by CoffeeBear70** [godotengine/godot#55919] opened 2021-12-14 04:33 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

After clicking off a tilemap's tileset menu, any and all tilemaps will not allow you to edit their tile's collision or be unable to make new tiles at all. While you can fix this by reloading the project, it's time consuming, and quite annoying

### Steps to reproduce

Step 1 Click on a tilemap node's tileset property
Step 2 Click onto another node

### Minimal reproduction project

[Bug test project.zip](https://github.com/godotengine/godot/files/7708665/Bug.test.project.zip)

**Comment by boruok** [comment] 2021-12-14 07:21
related to https://github.com/godotengine/godot/issues/52760
fixed in Godot_v3.4.1-rc1

**Comment by Calinou** [comment] 2021-12-14 10:09
Duplicate of https://github.com/godotengine/godot/issues/52760.

**Closed by Calinou** 2021-12-14 10:09 UTC
