### ISSUE TITLE
Tool script doesn't compiles if it uses a singleton

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5763] opened 2016-07-17 23:56 UTC
Tested on Godot 2.0.4 and Godot 2.1, Windows 10 64 bits

Some of my game objects have `tool` on their root script in order to show gizmos in the editor. However, since I use a singleton in them, they no longer compile and I cannot see the gizmos anymore.
Using `tool` in the singleton script doesn't helps.

Repro:
[SingletonCompileError.zip](https://github.com/godotengine/godot/files/368194/SingletonCompileError.zip)
Open this test project, the error appears in the console.

**Comment by neikeq** [comment] 2016-07-18 00:04
Closing as duplicate of #4236 
I will include there the information provided by this issue.

**Closed by neikeq** 2016-07-18 00:04 UTC
Labels: archived
