### ISSUE TITLE
Polygon2D-Circle overlapping is inaccurate

### ISSUE THREAD

**Issue by tuket** [godotengine/godot#14379] opened 2017-12-07 14:24 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 2.1.4.stable.

**Issue description:**

Poligon2D-Circle overlapping is inaccurate.

**Steps to reproduce:**
I create a CollisionPolygon2D and a CircleShape2D.
For the circle I create a script that changes the color when overlaps with something.

```
func _process(delta):
	var num = get_node("Area2D").get_overlapping_bodies().size()
	if num > 0:
		get_material().set_shader_param("col", Color(0, 1, 0))
```
You can see in the following gif what I mean with inaccurate

![2017-12-07_15-16-39](https://user-images.githubusercontent.com/4165974/33719661-ccc6dad4-db61-11e7-98cb-c589a5939649.gif)

**Link to minimal example project:**

[godot.zip](https://github.com/godotengine/godot/files/1539413/godot.zip)

**Comment by liorda** [comment] 2017-12-10 18:13
It looks like you have a scale factor on Sprite, which in editor looks like a scale on the (child) collision shape, but that scale is reset in runtime.

**Comment by akien-mga** [comment] 2018-09-18 08:55
That's indeed a duplicate of #7375 and #5734.

**Closed by akien-mga** 2018-09-18 08:55 UTC
Labels: bug, topic:physics
