### ISSUE TITLE
Improve integration of tool Nodes and AutoLoad singleton objects

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#10611] opened 2017-08-24 16:04 UTC
1. Create scene
2. Add a Node
3. Add a simple tool script to it
```
tool
extends Node

export(Texture) var player_sprite
export(int) var health_points
```
4. The exported vars are visible in the Inspector
5. Create unattached script global_singleton:
```
extends Object

func some_global_method():
    print('Called global method')
```
6. Add it to AutoLoad scripts in Project Settings
7. Append next code to your Node script:
```
func some_method_using_singleton():
    global_singleton.some_global_method()
```
**Actual result:**
The exported vars are gone from the editor and the Node is in fact no longer a tool

**Expected:**
The Node tool mode persists

**Comment by Hinsbart** [comment] 2017-08-24 17:10
> The exported vars are gone from the editor and the Node is in fact no longer a tool

That's because the script fails compiling, since autoloads can't be used in tool scripts yet.
Closing as duplicate of #4236.

**Closed by Hinsbart** 2017-08-24 17:10 UTC
