### ISSUE TITLE
preload() doesn't work in exported projects

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#65692] opened 2022-09-12 11:01 UTC
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Linux, Firefox 103.0.2

### Issue description

Attempting to load a scene using preload() fails in a web export. A workaround is to use `@onready` and `load()` instead.

Upon checking the web console, these errors are printed from running the MRP:

```
Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
USER ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:656) - Parser bug (please report): tried to assign unset node without an identifier.
USER SCRIPT ERROR: Parse Error: Preload file "res://TestLabel.tscn" does not exist.
   at: GDScript::reload (res://main.gd:3) - Parse Error: Preload file "res://TestLabel.tscn" does not exist.
USER SCRIPT ERROR: Parse Error: Cannot infer the type of "LABEL" variable because the initial value doesn't have a set type.
   at: GDScript::reload (res://main.gd:3) - Parse Error: Cannot infer the type of "LABEL" variable because the initial value doesn't have a set type.
```

### Steps to reproduce

Run the MRP from below.
If you run it in the editor or export to a desktop executable, you should get a screen with the text "hello world" in the center. But if you run it as a web export through the editor, you get a black screen.

### Minimal reproduction project

[MRP_preload.zip](https://github.com/godotengine/godot/files/9547303/MRP_preload.zip)

**Comment by eh-jogos** [comment] 2022-09-12 21:15
Also broken for Linux exports.

I got no error whatsoever when running in the editor but when running the release executable on editor I got these error messages:

```
SCRIPT ERROR: Parse Error: Preload file "res://addons/quiver.beat_em_up/utilities/OneShotTimer.tscn" does not exist.
          at: GDScript::reload (res://addons/quiver.beat_em_up/characters/action_states/ground_actions/grab_actions/quiver_action_grab_idle.gd:18)
SCRIPT ERROR: Parse Error: Preload file "res://addons/quiver.beat_em_up/utilities/OneShotTimer.tscn" does not exist.
          at: GDScript::reload (res://addons/quiver.beat_em_up/characters/ai/states/quiver_ai_chase_closest_player.gd:13)
SCRIPT ERROR: Parse Error: Preload file "res://addons/quiver.beat_em_up/utilities/OneShotTimer.tscn" does not exist.
```
That preload was a `const` and since the script itself breaks and it starts a chain reaction of errors.

For some reason the release export deals better with it, when I try to export with debug I get many more errors but using the work around described in this issue solved problems with both de release and debug exports.

**Comment by Asgatoril** [comment] 2022-09-14 08:44
I can confirm this for Linux exports.
Project runs fine in the editor but in the exported project "preload" doesn't work.

`SCRIPT ERROR: Parse Error: Preload file "res://Scenes/Navigation.tscn" does not exist.
          at: GDScript::reload (res://Scripts/Main.gd:6)
SCRIPT ERROR: Parse Error: Preload file "res://Scenes/NPC/Character.tscn" does not exist.
          at: GDScript::reload (res://Scripts/Main.gd:7)
SCRIPT ERROR: Parse Error: Preload file "res://Scenes/TerrainGenerator.tscn" does not exist.
          at: GDScript::reload (res://Scripts/Main.gd:9)
`

**Comment by michaldev** [comment] 2022-09-14 12:56
On linux works only when I run by editor. After release doesn't work. Problem is also on android and web.

**Comment by alfredbaudisch** [comment] 2022-09-15 09:31
Preloads are actually not working in any export. 

![image](https://user-images.githubusercontent.com/248383/190369119-6408be11-a991-4932-bbaf-1456459dcb83.png)

**Comment by akien-mga** [comment] 2022-09-15 10:05
Duplicate of #56343.

**Closed by akien-mga** 2022-09-15 10:05 UTC
Labels: bug, topic:gdscript, topic:export
