### ISSUE TITLE
KinematicBody2D move_and_collide problems

### ISSUE THREAD

**Issue by shyn01** [godotengine/godot#29771] opened 2019-06-14 08:08 UTC
Godot version:3.1.1

OS/device including version: Windows 10

Issue description:
i create two same KinematicBody2D,both have same collisionpolygon2d,in same position.
problem 1:when i call move_and_collide(step) the two kinematicbody2d in same frame,them will move faster then step.
problem 2:if i create same KinematicBody2D more then four in same position.call test_move.they will can not occur collision.

Steps to reproduce:
create two KinematicBody2D and child of collisionpolygon2d in same position.in _physics_process to call move_and_collide(step)
create more,to call test_move(get_transform(),Vector2(0,0)),would not to occur collision

**Comment by t-karcher** [comment] 2019-06-14 14:51
Did you create those nodes with the "duplicate" function in the editor? If yes, you'd have to make them unique first in order to create separate objects (not linked to each other): Select the node --> click on the small tool icon next to the node name in the inspector --> select "Make unique".

**Comment by KoBeWi** [comment] 2020-07-28 14:58
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:19
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:19 UTC
Labels: bug, needs testing, topic:physics
