### ISSUE TITLE
Unable to Tween for Font's Outline Color

### ISSUE THREAD

**Issue by Dentrax** [godotengine/godot#29732] opened 2019-06-12 21:09 UTC
**Godot version:** `v3.1.stable.official`

**OS/device including version:** `Arch x64 - 5.1.7`

**Issue description:**
I am trying to tween a `Font`'s _Outline Color_ between given colors via `Tween`.

**Steps to reproduce:**
1. Create a `Tween` node
2. Create a `Label` and add `Custom Dynamic Font`
3. Run the code I gave at the bottom.

**Codes:**
```
$Tween.interpolate_property($Label, "outline_color", Color(1, 1, 1, 1), Color(1, 0, 0, 1), 1.0, Tween.TRANS_LINEAR, Tween.EASE_IN)
$Tween.start()
```

**Comment by KoBeWi** [comment] 2019-06-12 21:22
Probably related to #29718

**Comment by TheDuriel** [comment] 2019-06-12 23:06
Not a bug. outline_color is a property of the font resource, not the label. Moreover, font resource changes must be finalized by calling `update_changes ( )` on the resource.

**Comment by Dentrax** [comment] 2019-06-13 10:27
@TheDuriel In this case, Can i tween the Outline Color? If so, how can i do that?

**Comment by Calinou** [comment] 2019-08-24 03:39
This would be feasible with `add_constant_override()`. However, since [`Tween.interpolate_method()` only accepts a single argument](https://github.com/godotengine/godot/issues/27425), you will need to create an exported property as I explained [here](https://github.com/godotengine/godot/issues/29718#issuecomment-524514168) then tween it using `Tween.interpolate_property()`.

**Comment by KoBeWi** [comment] 2019-12-15 13:21
Closing. As noted by TheDuriel, `outline_color` is a property of DynamicFont, so you need to Tween on the font. The proper code here is this:
```
$Tween.interpolate_property($Label.get_font("font"), "outline_color", Color(1, 1, 1, 1), Color(1, 0, 0, 1), 3.0, Tween.TRANS_LINEAR, Tween.EASE_IN)
```
Although keep in mind that this will affect all Controls sharing this resource, so make it unique or local to scene.

**Closed by KoBeWi** 2019-12-15 13:21 UTC
Labels: bug, topic:gui
