### ISSUE TITLE
Casting error in C# with type Button 

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#38497] opened 2020-05-06 03:58 UTC
**Godot version:**
3.2.1
**OS/device including version:**
Windows
**Issue description:**
This took me a while to figure out what was going on.  I created a scene with a 
Control
------GridContainer
------------Button

there is a script attached to the GridContainer that sets the button's text to "hello".
I first use the regular code:
`Button f = GetNode<Button>("btn")`
`f.Text = "Hello"`

This fails with a "Specified cast not valid" error.
This same code works fot Labels, RichTextLabels or any other node I have used.
Finally, I found that the the type being returned is not "Button" but "Godot.Button".
If I do the following, it will work:
`Godot.Button f = GetNode<Godot.Button>("btn")`
`f.Text = "Hello"`

For some reason Godot will currently not accept the Button type in casting.
Here is the scene and script.
[Test.zip](https://github.com/godotengine/godot/files/4584748/Test.zip)

**Comment by MightyPrinny** [comment] 2020-05-07 00:33
your node path is wrong, you named the button "btn" not "button"

**Comment by MightyPrinny** [comment] 2020-05-07 00:38
Oh never mind, your test project doesn't have the code that's supposed to fail, you shouldn't have uploaded that

**Comment by MightyPrinny** [comment] 2020-05-07 00:43
If you have another class named Button in your project that might be your problem, it's just a name clash.

**Comment by ondesic** [comment] 2020-05-07 01:21
MightyPrinny,
There are no other classes named Button.  I'll upload the project folder.  The code I gave was only an example.

**Comment by raulsntos** [comment] 2022-08-11 00:41
Can't reproduce in v3.5.stable.mono.official [991bb6ac7], also as **MightyPrinny** said your MRP is invalid.

This code works as long as there is a node of type `Button` with the name `btn` in the scene as a child of the node that has the script attached:

```csharp
Button f = GetNode<Button>("btn");
f.Text = "Hello";
```

You only need to specify the `Godot` namespace when there is a name clash, as **MightyPrinny** said (for example, you have another class in your project with the name `Button`).

I'll close this but if anyone can still reproduce this on 3.5 or later, please open a new issue with a minimal reproduction project attached.

**Closed by raulsntos** 2022-08-11 00:41 UTC
Labels: bug, topic:dotnet
