### ISSUE TITLE
Movement glitch

### ISSUE THREAD

**Issue by duasun** [godotengine/godot#47221] opened 2021-03-21 12:14 UTC
**Godot version:**
3.2.4. rc5

**OS/device including version:**
Win 10, Gtx 1660Super, Gles2

**Issue description:**
Lack of control when moving control node. Small movements move node big time. 

**Steps to reproduce:**
Not sure.

**Minimal reproduction project:**
Screen recording. Do not have min. repr. proj. 

https://www.youtube.com/watch?v=N1IUnW7owpU

**Comment by akien-mga** [comment] 2021-03-21 12:19
Duplicate of #446979, this was fixed in 3.3 RC 6 already: https://godotengine.org/article/release-candidate-godot-3-3-rc-6

**Closed by akien-mga** 2021-03-21 12:19 UTC
