### ISSUE TITLE
Physics2DServer doesn't send body info to signals

### ISSUE THREAD

**Issue by bitbionic** [godotengine/godot#12215] opened 2017-10-18 15:01 UTC
Found on Linux Mint 18.1, Intel i7, NVIDIA Gtx 660m
Godot 2.1.4-stable

Using the Bullet Shower demo, place a break-point in the _on_player_body_enter_shape or _on_player_body_exit_shape functions . You'll notice that there is no body or information about the body _**per the debug screenshot attached**_. I found / reproduced this in another project when I was using the same technique as the Bullet Shower demo. I don't someone can remove the physics body based on collision without this information because there is no identifier present.

![debugbulletshower](https://user-images.githubusercontent.com/7328956/31725902-82e89f64-b3f3-11e7-87ca-189e865aa73f.png)

**Link to minimal example project:**
Use Bullet Shower Demo.
https://github.com/godotengine/godot-demo-projects/tree/2.1/2d/shower_of_bullets

**Comment by akien-mga** [comment] 2018-09-17 15:20
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by akien-mga** [comment] 2018-09-17 15:47
Actually tested in the master branch and it's still valid.
![screenshot_20180917_174722](https://user-images.githubusercontent.com/4701338/45634061-bc82f480-baa1-11e8-99c8-a7f25faaa065.png)

**Comment by ericdsw** [comment] 2019-03-20 21:19
This appears to be happening with areas as well, `area_shape_entered` signal is correctly calling my `_on_Area2D_area_shape_entered` method, but the `area_id` is always 1 and the `area` is null.

**Comment by KoBeWi** [comment] 2020-06-13 15:36
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Listwon** [comment] 2020-09-15 10:20
@KoBeWi It's still reproducible on 3.2.2, but the thing is that this behaviour seems reasonable. `area` or `body` is null, because there are no `Area2D` or `KinematicBody2D` nodes in the `SceneTree` (except of the player node). `area_id` in my case is always 0 (default value I guess).
[shower_of_bullets_areas_3_2_2.zip](https://github.com/godotengine/godot/files/5224117/shower_of_bullets_areas_3_2_2.zip)

**Comment by KoBeWi** [comment] 2020-09-15 11:12
I think `area_id` should be RID of the area, even if there's no node.

**Closed** 2021-05-18 18:00 UTC
Labels: bug, confirmed, topic:physics
