### ISSUE TITLE
Animation tree blending bug

### ISSUE THREAD

**Issue by ICatRegister** [godotengine/godot#45235] opened 2021-01-16 16:49 UTC
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10

**Issue description:**
Setting the parameter to a negative value on the Blend3 node leads to jerking when switching animations if blending is enabled between these animations.
When using the Add3 node, it's even worse: the effect is the same, but the animation does not work with a negative parameter

![anim_tree](https://user-images.githubusercontent.com/30937277/104817691-d8def980-5833-11eb-8589-9e136944091a.gif)

**Steps to reproduce:**

- Download the project. 
- Set the parameter on the Blend3 node to a negative value.
- Switch between animations 1 and 2. 

 With a positive parameter on Blend3 or zero xfade_time on Transition node, the effect does not appear

**Minimal reproduction project:**

[AnimTreeBlendBug.zip](https://github.com/godotengine/godot/files/5824757/AnimTreeBlendBug.zip)

**Comment by Calinou** [comment] 2021-01-16 20:39
Duplicate of https://github.com/godotengine/godot/issues/37661.

**Closed by Calinou** 2021-01-16 20:39 UTC
