### ISSUE TITLE
Editing UI when its parent is a Window node does not show in-editor gizmos

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#89384] opened 2024-03-11 13:01 UTC
### Tested versions

Tested in 4.3.x, 4.2.x
Most likely present in any version

### System information

Godot v4.3.dev4 - Windows 10.0.19044 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.24019.1006) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

Editor gizmos don't show:
![Godot_v4 3-dev4_win64_SC00semHFs](https://github.com/godotengine/godot/assets/102416174/4f87de6b-1bea-4e55-a050-9fc67135baef)

<sub>I'm not sure if this has been reported already, I couldn't find anything using the Github search.</sub>

### Steps to reproduce

1. Create Window Node
2. Create child Control Node

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment] 2024-03-11 13:57
Sounds very similar to #20619, https://github.com/godotengine/godot-proposals/issues/2139. Would you consider any of them a duplicate?
Also see #74573.

**Comment by Swarkin** [comment] 2024-03-11 14:20
74573 seems to be a (partial) fix for this, I can see in one of the videos posted there gizmos showing up, but dragging them doesn't update the Window's rendered content. (See the second last video in that issue)

**Comment by KoBeWi** [comment] 2024-03-12 22:50
This is a duplicate of #79289 (which technically is the same issue as #20619, but it was introduced when dialogs were changed to Window).

**Closed by KoBeWi** 2024-03-12 22:50 UTC
Labels: enhancement, topic:editor, topic:2d
