### ISSUE TITLE
Game window and save fails when show TileMap

### ISSUE THREAD

**Issue by ochesto** [godotengine/godot#23612] opened 2018-11-09 09:12 UTC
**Godot version:**

![selection_015](https://user-images.githubusercontent.com/7444694/48253232-6741d000-e3cc-11e8-97ae-3fae28e58702.png)

**OS/device including version:**

Ubuntu Mate 18.04 (updated).
![selection_014](https://user-images.githubusercontent.com/7444694/48253255-77f24600-e3cc-11e8-97c2-deaaf7e6b92a.png)

**Issue description:**

![desktop-animation](https://user-images.githubusercontent.com/7444694/48253282-85a7cb80-e3cc-11e8-8c87-216682f64fd1.gif)

**Steps to reproduce:**
New project with only a TileMap doesn't reproduce well when start. And if the project is save, saves only the tiles that show in the game window.

**Minimal reproduction project:**

New project with a Node and MapTile. Using this tutorial basically: [https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html](url)

**Comment by Calinou** [comment] 2018-11-09 10:46
I can reproduce this on commit https://github.com/godotengine/godot/commit/eef2625ae5a8be8a4aa89a6443acfd5b6184c668.

**Editor:**

![image](https://user-images.githubusercontent.com/180032/48258321-1609fe80-e415-11e8-8b48-84a5d28f7d25.png)

**Running project:**

![image](https://user-images.githubusercontent.com/180032/48258303-0be80000-e415-11e8-89dc-7dc44fa9d9c4.png)

**Comment by Zireael07** [comment] 2018-11-09 10:55
The window part looks like a bug that was already reported, might've been a driver issue?

**Comment by reduz** [comment] 2018-11-09 13:17
Please upload a project that breaks so I can test, I have no time right now to set one up.

**Comment by Calinou** [comment] 2018-11-09 13:33
@reduz https://github.com/Calinou/game-off-2018 :slightly_smiling_face:

**Comment by akien-mga** [comment] 2018-11-10 20:49
Fixed by #23625.

**Closed by akien-mga** 2018-11-10 20:49 UTC
Labels: bug, confirmed, topic:editor
