### ISSUE TITLE
Kinematic character slows down at certain areas

### ISSUE THREAD

**Issue by crym0nster** [godotengine/godot#15740] opened 2018-01-15 11:23 UTC
**Godot version:**
3.0 RC1

**OS/device including version:**
Arch Linux, Linux Mint

**Issue description:**
Kinematic character with move_and_slide() slows down at certain areas. Walking at marked areas reduces speed ~2 times. Tested on 2 machines with Linux, but on Windows it works well.
![screenshot_2018-01-15_16-10-31](https://user-images.githubusercontent.com/20391158/34939946-8e1a3eee-fa0f-11e7-8973-2d8114f72566.png)

**Steps to reproduce:**
Try attached example

**Minimal reproduction project:**
[test_kinematic_character.zip](https://github.com/godotengine/godot/files/1631430/test_kinematic_character.zip)

**Comment by jedStevens** [comment] 2018-01-15 12:13
Was also getting this, had me boggled  because I was blaming my code which was for the most part simple, at least the movement was.

Can't confirm if a windows machine runs my project and since it's a larger private one I'm not into sharing but I could make a small example later today, as to what gives me this error

**Comment by AndreaCatania** [comment] 2018-01-15 13:27
Is this happening only with bullet physics?

**Comment by jedStevens** [comment] 2018-01-15 13:28
In transit atm, but I have not tried godot physics to compare. I will later
today.

**Comment by volzhs** [comment] 2018-01-15 13:30
I tested this with godot physics. and it stucks at a corner and couldn't move at all

**Comment by AndreaCatania** [comment] 2018-01-15 13:32
Is it possible that the problem is the mesh itself, I'll check it soon

**Comment by jedStevens** [comment] 2018-01-15 13:36
Potentially, I am using an auto generated mesh.

I'll use a blender made one next. What is best practices for a mesh for
this? Tris / Quads

On Jan 15, 2018 8:32 AM, "Andrea Catania" <notifications@github.com> wrote:

Is it possible that the problem is the mesh itself, I'll check it soon

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/15740#issuecomment-357683777>,
or mute the thread

**Comment by crym0nster** [comment] 2018-01-15 13:42
I also got stuck in a corner with GodotPhysics. There was an error:
ERROR: _initialize_and_check_api_hashes: Mono: Core API hash mismatch!
   At: modules/mono/mono_gd/gd_mono.cpp:259.

**Comment by AndreaCatania** [comment] 2018-01-15 13:42
You must use mesh composed by triangles, also the best shape type to use is a convex shape instead of a concave one since the solver is more lightweight.
However the concave shape should work perfectly then let me know if it doesn't.

**Comment by crym0nster** [comment] 2018-01-15 14:02
I triangulated mesh in Blender and it stopped slowing down on the ramp(the top thing marked red on screenshot), but on the floor - still slowing down. Also on Windows it runs without any problems at all

**Comment by crym0nster** [comment] 2018-01-15 14:04
And I tried converting mesh to convex collision shape(selected mesh and on toolbox "create conves static body") - it just created a box enclosing room, but no internal geometry

**Comment by AndreaCatania** [comment] 2018-01-15 14:24
It's possible for you to send here the blender file?

**Comment by jedStevens** [comment] 2018-01-15 14:28
I can provide my files around noon (Toronto time)

On Jan 15, 2018 9:25 AM, "Andrea Catania" <notifications@github.com> wrote:

It's possible for you to send here the blender file?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/15740#issuecomment-357696678>,
or mute the thread

**Comment by crym0nster** [comment] 2018-01-15 14:29
[blend.zip](https://github.com/godotengine/godot/files/1631920/blend.zip)
the file is original room - just planes. second - with solidify and triangulate and splitted into several objects

**Comment by AndreaCatania** [comment] 2018-01-15 16:12
@crym0nster 

> Walking at marked areas reduces speed ~2 times.

Do you mean that the FPS drops or do you mean the body velocity slows?
I can't reproduce it on my machines, neither linux nor windows

**Comment by crym0nster** [comment] 2018-01-15 16:18
Velocity. I have seen that NPC (also kinematic character) slows down at these areas.

**Comment by AndreaCatania** [comment] 2018-01-15 16:21
@crym0nster can you make a video please?

**Comment by crym0nster** [comment] 2018-01-15 16:23
yes, I'll try

**Comment by crym0nster** [comment] 2018-01-15 16:35
https://www.youtube.com/watch?v=eQ6PhVPDL3g&feature=youtu.be sorry for quality. these numbers - current velocity. normally it should be 35, but it goes to 18 on horizontal plane for some reason

**Comment by AndreaCatania** [comment] 2018-01-15 16:42
Ok thanks you i let you know

**Comment by AndreaCatania** [comment] 2018-01-15 22:33
I was able to reproduce it, in order to fix it you should increase the safe margin from 0.001 to 0.005 in the kinematic body.

**Comment by crym0nster** [comment] 2018-01-15 22:39
Thanks, it works. So was it a bug or not? Because I tried it on Windows and there was no problem with default setting

**Comment by AndreaCatania** [comment] 2018-01-15 22:43
The problem was floating point precision, for this reason the margin is customizable

**Comment by AndreaCatania** [comment] 2018-01-15 22:45
Remember to close the issue if it's solved, and thanks you for the report

**Closed** 2018-01-15 22:46 UTC
Labels: bug, topic:physics
