### ISSUE TITLE
Audio Latency Linux/X11 and HTML5

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#35509] opened 2020-01-24 12:50 UTC
**Godot version:**
Godot_v3.2-rc2_x11.64

**OS/device including version:**
Kubuntu/19.10

**Issue description:**
On Linux/X11 (both editor and export) as well as HTML5 (on my computer at least; chrome and firefox) has significant delay before playing a sound. Android and Windows (running through Wine!) exports do not (or at least no more than I suspect is normal). Linux/X11 AudioServer.get_output_latency() says around a bit over 0.200 which sounds about right, but all other platforms just say 0, including HTML5. There are a few old issues and PRs about 200ms delay, maybe didn't fix all the problems.

Lowering Audio/Output latency has no significant effect. Using Audio/Driver JACK instead of PulseAudio feels a little better and gives a slightly lower latancy value but it's not much. Pausing/playing music etc on my computer has absolutely no delay.

**Steps to reproduce:**
Play sound on button press.

**Comment by Calinou** [comment] 2020-01-24 13:16
Does it improve if you disable Vsync in the Project Settings and make sure the project renders as fast as possible?

**Comment by xix-xeaon** [comment] 2020-01-24 13:24
@Calinou I already have Vsync disabled and I get hundreds of FPS for Linux/X11 and Windows. HTML5 only goes to 60 though so not sure about that. My phone doesn't perform as well (it's a 3D game), but it does not have any delay.

**Comment by Calinou** [comment] 2020-01-24 14:36
Thanks for replying. Have you tried using Godot's ALSA driver? You can do so by running the Godot binary with the following command-line arguments:

```text
path/to/godot_binary --path /path/to/project/folder --audio-driver ALSA
```

Note that Godot doesn't support JACK natively, so it will have to convert from ALSA/PulseAudio to JACK if you're using JACK on your system.

**Comment by xix-xeaon** [comment] 2020-01-25 09:12
ALSA doesn't improve it, and says 0 latency. The thing with JACK might just be random/imagination, it's not significant. The latency values for PulseAudio or JACK on Linux/X11 gives values between 0.190 and 0.230 and stays the same until game is restarted - it never changes. And once I got 0.400 but the delay certainly wasn't That long. Everything else is always 0. Doesn't seem like that value can be trusted at all.

**Comment by akien-mga** [comment] 2020-01-25 09:21
What latency is reported when you run Godot with `-v`?
Here it says:
```
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
```

**Comment by xix-xeaon** [comment] 2020-01-25 09:48
@akien-mga I get the exact same as you for PulseAudio.
ALSA says `Audio buffer frames: 341 calculated latency: 7ms` but also gives a whole bunch of `ALSA lib pcm.c:8432:(snd_pcm_recover) underrun occurred`
Windows export (in wine) `WASAPI: audio buffer frames: 265 calculated latency: 6ms` (and yeah I checked, wine uses PulseAudio)

**Comment by Calinou** [comment] 2020-04-18 13:05
Duplicate of #16259. A workaround is included in https://github.com/godotengine/godot/issues/16259#issuecomment-591831079, please give it a try.

**Closed by Calinou** 2020-04-18 13:05 UTC
Labels: bug, platform:html5, platform:linuxbsd, topic:audio
