### ISSUE TITLE
Animation 'Call Method' finds but does not allow insertion of methods in custom c# script with [Tool]

### ISSUE THREAD

**Issue by CowKeyMan** [godotengine/godot#39016] opened 2020-05-24 17:13 UTC
**Godot version:** 3.2.1 - mono stable

**OS/device including version:** Windows

**Steps to reproduce:** 

1. Create a c# script with [Tool].
2. Make a simple method of any type
3. Attach the script from step 1 to object
4. Make an animation player, with a new animation
5. Add a call method track, select the original object
6. Add a key to call the method from step 2
7. Read the unecessary error

This bug does not occur in gdscript

It can be bypassed by creating a call method key for another method, then renaming the name of the method to the desired method.

**Comment by Calinou** [comment] 2020-06-02 21:20
Duplicate of #39156.

**Closed by Calinou** 2020-06-02 21:20 UTC
