### ISSUE TITLE
Wrong looking of VRAM Compressed textures

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51943] opened 2021-08-21 06:09 UTC
### Godot version

v4.0.dev.custom_build [e599f1bdf]

### System information

Windows 11, Vulkan Clustered

### Issue description

Not for any images but specific ones. All the three images look fine in 3.4.

VRAM Compressed in 4.0
![image](https://user-images.githubusercontent.com/28705694/130312212-cc07e3bc-779c-40d0-a871-8157e3d6f4e9.png)

Lossless in 4.0
![image](https://user-images.githubusercontent.com/28705694/130312314-4ad845e0-9761-4526-add7-c2b2330df799.png)

Also, the mipmaps of VRAM Compressed textures don't look right.
![vram_mipmaps](https://user-images.githubusercontent.com/28705694/130312379-793f7a34-6fd6-44f5-9b72-aafd5b3000ba.gif)

### Steps to reproduce

Check out the attached reproduction project.

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7025005/New.Game.Project.zip)

**Comment by Calinou** [comment] 2021-08-21 17:42
Duplicate of https://github.com/godotengine/godot/issues/49981.

**Closed by Calinou** 2021-08-21 17:42 UTC
Labels: bug, topic:rendering, topic:import
