### ISSUE TITLE
Simple 2D skeleton modification stack IK setup throws a bunch of confusing errors

### ISSUE THREAD

**Issue by Lyxilytical** [godotengine/godot#79960] opened 2023-07-27 15:49 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 570 Series () - AMD Ryzen 3 2200G with Radeon Vega Graphics (4 Threads)

### Issue description

Setting up a simple modification stack that uses inverse kinematics throws a bunch of warnings and errors at runtime

![image](https://github.com/godotengine/godot/assets/118941006/67fdebed-ddff-4aec-8636-8b3bc9d8d866)
![image](https://github.com/godotengine/godot/assets/118941006/da7b0ee9-5278-4bb4-80fc-6df1b5b80ee4)

![image](https://github.com/godotengine/godot/assets/118941006/4702267c-ecd9-407d-8909-b11cb80ce66b)

Also occurs when you open the project.

![image](https://github.com/godotengine/godot/assets/118941006/e6d3b869-c9b2-4d4d-b902-53e22b02f70a)

### Steps to reproduce

Choose any backend renderer and open a blank scene

Create a skeleton with 2 bones as seen in the screenshots

Select the skeleton and create a new SkeletonModificationStack2D, and add a SkeletonModification2DTwoBoneIK

Create a target node for the IK chain, and assign the target and the bones in the SkeletonModification2DTwoBoneIK

Make sure the SkeletonModifcationStack2D is enabled and run the scene

From what I know, this is the intended way to use IK in Godot 4, so realistically I assume it shouldn't throw any confusing errors and warnings? I could be doing something wrong though, considering that the current documentation is outdated...

### Minimal reproduction project

[SkeletonModifcationIKBug.zip](https://github.com/godotengine/godot/files/12185386/SkeletonModifcationIKBug.zip)

**Comment by AThousandShips** [comment] 2023-09-07 20:33
This has been reported in:
* #81433

Which provides more information, consolidating there

Duplicate of: #81433

**Closed by AThousandShips** 2023-09-07 20:33 UTC
Labels: bug, topic:editor, topic:animation

**Comment by idzharbae** [comment] 2024-01-26 11:22
I encounter a similar case:
When I save a scene that contains skeleton node with another name, if I import that scene to another scene godot logs will flood with `Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.` errors. 

Below is the video evidence, I saved `Player` scene as `King` scene because I want it to have the same skeleton and everything, but when I link it to the main scene the logs are flooded with errors. The skeleton modification that I use was `SkeletonModification2DLookAt`. It can be resolved by making a new scene instead, and copying each node one by one.

https://github.com/godotengine/godot/assets/29392405/96722c68-d26e-4e4c-9bbf-fd6c164e66c9
