### ISSUE TITLE
The data editing tab does not open when the breakpoint is active

### ISSUE THREAD

**Issue by Oleksandrigo** [godotengine/godot#60726] opened 2022-05-03 12:08 UTC
### Godot version

3.3.4 and 3.5 beta 5

### System information

Windows 11, GTX 1660 Super, GLES3

### Issue description

It's hard to explain in words, but I'll try. There is a global script - "Global", which is in the autostart. It has this.
```
extends Node
var rel_table = [
	[
		{ "sa": 1}
	],
	[0]
]
```
There is an empty scene with a script attached that has this.
```
extends Control
func _ready():
	var s = G.rel_table
	print(s)
```
Put a breakpoint on print(s), 
Run the scene, debugger opens, click on Globals->G. 
Now we have the data we need opened in the inspector. Click on Members->Rel Table (expand). 
Press 0->Array(size 1). 
Finally click on 0->Dictionary... 

And absolutely nothing. Dictionary tab won't open. That is, the tab tries to open, but it closes immediately.

### Steps to reproduce

see description

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8610282/test.zip)

**Comment by kleonc** [comment] 2022-05-03 13:00
In action (3.4.4.stable), sometimes it doesn't open at all, sometimes it closes immediately:
![WVoUwZsSub](https://user-images.githubusercontent.com/9283098/166457345-e94c4668-711d-45a6-9ec3-cab4a85e2934.gif)

**Comment by Calinou** [comment] 2022-05-03 17:41
Duplicate of https://github.com/godotengine/godot/issues/25375.

**Closed by Calinou** 2022-05-03 17:41 UTC
