### ISSUE TITLE
FileDialog.FILE_MODE_OPEN_FILE results in a 'Save File' dialogue

### ISSUE THREAD

**Issue by bitbutter** [godotengine/godot#83376] opened 2023-10-15 09:12 UTC
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3168) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

file_dialog.mode = FileDialog.FILE_MODE_OPEN_FILE seems not to be respected. A file dialogue opened after having been configured this way shows up as a 'Save file' dialogue.

### Steps to reproduce

Create a new project/scene and add this code to a script attached to the scene root. Run the scene. A 'Save File' dialogue appears.

```
extends Node3D
var file_dialog

func _ready():
	file_dialog = FileDialog.new()
	file_dialog.mode = FileDialog.FILE_MODE_OPEN_FILE
	file_dialog.connect("file_selected", Callable(self, "_on_file_selected"))
	add_child(file_dialog)
	file_dialog.popup_centered_ratio()
```

### Minimal reproduction project

I think reproduction is trivial with the code snippet above.

**Comment by AThousandShips** [comment] 2023-10-15 09:19
You're using the wrong property, it's `file_mode` not `mode`

**Comment by AThousandShips** [comment] 2023-10-15 09:20
Duplicate of https://github.com/godotengine/godot/issues/58795

**Closed by AThousandShips** 2023-10-15 09:20 UTC
