### ISSUE TITLE
Default non english text issue(Cyrillic)

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#45083] opened 2021-01-11 00:23 UTC
**Godot version:**
3.2.4

**OS/device including version:**
Windows 7.

**Issue description:**
Label with text "Hellow Дмитрий."

![image](https://user-images.githubusercontent.com/22836285/104139281-71e8bd00-53bb-11eb-9f7c-5f8319c92c54.png)

but costom font (windows Arial) - working

![image](https://user-images.githubusercontent.com/22836285/104139366-06ebb600-53bc-11eb-9334-7bf00dc6833f.png)

Editor font is fine.
**Steps to reproduce:**
Set label lext = "Hellow Дмитрий."

**Comment by Calinou** [comment] 2021-01-11 01:11
Duplicate of https://github.com/godotengine/godot-proposals/issues/1079.

**Closed by Calinou** 2021-01-11 01:11 UTC
