### ISSUE TITLE
100% CPU usage in master

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#49335] opened 2021-06-05 13:57 UTC
**Godot version:**
v4.0.dev.calinou.4e52b8401

**OS/device including version:**
Ubuntu Focal amd64, Radeon R9 290 (amdgpu/radeon)
Debian Buster amd64 (with updated mesa and drivers), Radeon RX 550 (amdgpu/radeon)

**Issue description:**
Having Godot open uses 100% (one core) CPU load at all times. Even with an empty project. Even the project manager.

**Steps to reproduce:**
- Launch Godot (just the project manager is enough)
- Launch `htop` and observe near-100% CPU usage by the Godot process (apparently, a single thread bouncing between all cores)

This was not the case in Godot v4.0.dev.custom_build.6019dab0b (a random build I had lying around since the last time I poked in master), and it is not the case in 3.3.2-stable.
It might have something in common with #47551 , which covers "low performance". However, the issue here is not "performance" - it is 100% CPU load, regardless of how powerful that CPU is, even when doing nothing.
I've enabled the "update spinner" to make sure there are no visual updates going on, so Godot really is doing exactly nothing.

**Comment by Calinou** [comment] 2021-06-05 15:25
Could you [perform a bisection](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html) between the commits 4e52b8401 (bad) and 6019dab0b (good)? Thanks in advance :slightly_smiling_face:

**Comment by dark-penguin** [comment] 2021-06-05 15:39
Oh, I was wondering how to do that - thanks for the manual.

BTW do you perhaps have an archive of your builds? This is a lot of building to do.

**Comment by Calinou** [comment] 2021-06-05 15:45
> BTW do you perhaps have an archive of your builds? This is a lot of building to do.

I don't due to storage space limitations.

**Comment by dark-penguin** [comment] 2021-06-05 18:07
Upon further examination, the "good" commit (6019dab) has the following behavior:
- The project manager does not load the CPU
- Opening an empty scene loads the CPU, and displays a constantly spinning "update spinner"
On a less powerful machine, it fully loads one CPU core. On a more powerful machine, it's loading only about 70% of one core.

Which is mostly the same as what we have now (in 7085c0d), except now the project manager also causes CPU load, and the spinner is now not spinning.

So how should I proceed?.. Does it make sense to bisect the spinner and the project manager?..

**Comment by Calinou** [comment] 2021-06-05 18:09
> Opening an empty scene loads the CPU, and displays a constantly spinning "update spinner"
On a less powerful machine, it fully loads one CPU core. On a more powerful machine, it's loading only about 70% of one core.

This is because the editor used to constantly mark settings as changed, but this was fixed somewhere in H1 2021.

**Comment by dark-penguin** [comment] 2021-06-05 18:30
I've tried Hotspot... but I don't even understand how to read those graphs, not to mention the actual debug symbols. Seems like it's spending 80% of time trying to parse some TLS certificates?.. And I can't make it past the project manager, because that's another process, so the debugger stops capturing.

Could you maybe check if you see a similar "suspiciously high" CPU usage with your latest build? I have about 70% on one core regardless of how powerful the CPU is - for some reason, htop does not say "100%", even though I see well over 100% total load with my graphical system monitor (with nothing else to cause it).

**Comment by Zireael07** [comment] 2021-06-05 18:56
I know performance problems related to TLS/mbedTLS were reported, but I can't find the issue # ... @Calinou? @Faless ?

**Comment by Calinou** [comment] 2021-06-05 19:24
>  And I can't make it past the project manager, because that's another process, so the debugger stops capturing.

Start the editor direclty on a project by passing the path to a `project.godot` file in the project manager.

**Comment by dark-penguin** [comment] 2021-06-05 19:50
How should I post the results? The capture file is 200+ Mb, screenshots won't help much because you have to click them... And Hotspot went crazy and does not work anymore; it says `Error: unknown switch 'z'`, but I did not pass any switch to it...

I can help with bisecting and testing on multiple systems, but I don't think I'll be of much help with C++ profiling. I can try to get some results with good enough instructions, if I'm the only one who has this problem. But since the problem is 100% reproducible in any system for at least half a year, maybe someone could confirm it first?..

**Comment by dark-penguin** [comment] 2021-06-06 10:19
I got curious and tried to at least get it to work, but I still don't understand the graphs - so I don't know what should I post.

Here are four screenshots: for the project manager running for a few seconds after launching (flame and bottom-up), and for Godot with an empty project running for a minute (flame and top-down). I have the capture files, but those are 0.5Gb and 1.5Gb...

![hotspot_manager_flame](https://user-images.githubusercontent.com/16963337/120920854-8fe7ee80-c6c9-11eb-823f-1f364cf5455e.png)
![hotspot_manager_bottom_up](https://user-images.githubusercontent.com/16963337/120920853-8f4f5800-c6c9-11eb-9b2b-13e151ba1d46.png)
![hotspot_godot_flame](https://user-images.githubusercontent.com/16963337/120920850-8e1e2b00-c6c9-11eb-906d-22c326595296.png)
![hotspot_godot_topdown](https://user-images.githubusercontent.com/16963337/120920852-8f4f5800-c6c9-11eb-9a03-089641cade3c.png)

**Comment by Calinou** [comment] 2021-12-02 21:27
@dark-penguin Can you still reproduce this on a recent build of the `master` branch?

**Comment by dark-penguin** [comment] 2021-12-02 21:32
I'll try in a few days - I'm crazy busy these days, but I'm not ignoring it. :)

**Comment by nathanfranke** [comment] 2021-12-02 21:34
Can't reproduce in v4.0.dev.custom_build [8bb0f2aff]

One is in a project, one is project manager

![image](https://user-images.githubusercontent.com/14253836/144506635-965b74c3-7f9b-4a7c-95a9-681cd50c6dd9.png)

Intel i5 6600k, GTX 960, on Arch btw

**Comment by dark-penguin** [comment] 2021-12-02 21:51
Oh, that's right, I forgot I don't have to build it, I can just download it from Calinou's builds and try right away!..

Indeed, it seems fine now! (v4.0.dev.calinou [702ffc624], Debian Bullseye, RX550)

**Comment by Calinou** [comment] 2021-12-03 00:14
Closing as resolved.

**Closed by Calinou** 2021-12-03 00:14 UTC
Labels: bug, topic:editor, needs testing
