### ISSUE TITLE
.PNG file reading/decompression error, miscolored pixels. 

### ISSUE THREAD

**Issue by gunbuilderguy** [godotengine/godot#82895] opened 2023-10-06 05:14 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 10, AMD 6800xt (driver info broken)

### Issue description

For some reason, PNG files aren't read right, and some pixels seem to take the hue of surrounding pure green pixels.
here's the file:
![border_shade_modifiers](https://github.com/godotengine/godot/assets/123529947/30d95a89-0a90-44af-aa71-c76de8689671)
the original affected pixels don't really seem to share much in common values-wise, it seems it's more of a position-based effect

here's how it looks in the editor
![image](https://github.com/godotengine/godot/assets/123529947/d7294a45-fe9b-4884-aac9-252d0a3d3bc0)
they may be faint but become significantly more visible in practice, sticking out especially when the green outline is passed through a recoloring shader.
![image](https://github.com/godotengine/godot/assets/123529947/de954907-d97d-409c-84ab-5fe0d2e359e4)

This effect isn't present on photoshop, photofiltre, photopea and multiple image viewers i've tried.

exporting the same file as an uncompressed .DDS file does not share those problems
my guess is that it's the way the engine decompresses the file to read it where the error lies.

### Steps to reproduce

download the tile image
open it in godot, you can faintly see the effects in the preview
you can zoom better by zooming in the tileset editor (margin; 1,1, padding: 1,1)
the contrast is higher on a tilemap on empty grey background

### Minimal reproduction project

N/A

**Comment by aaronfranke** [comment] 2023-10-06 06:52
Double-click on the file in your FileSystem dock, and click over to the Import tab. Check the Compress mode.

<img width="324" alt="Screenshot 2023-10-06 at 1 51 23 AM" src="https://github.com/godotengine/godot/assets/1646875/a6b9b431-11bc-48c5-b2ea-62b61e270040">

**Comment by kleonc** [comment] 2023-10-06 14:52
This is caused by the enabled [`process/fix_alpha_border` import setting](https://docs.godotengine.org/en/4.1/tutorials/assets_pipeline/importing_images.html#process-fix-alpha-border) (it's enabled by default):

![Godot_v4 2-dev6_win64_cSYCUTtHOe](https://github.com/godotengine/godot/assets/9283098/7fc75c81-1797-4a65-b04f-311bd6ac8af1)


| `fix_alpha_border = true` | `fix_alpha_border = false` |
|--------|--------|
|![Godot_v4 2-dev6_win64_rsFqIAOmHy](https://github.com/godotengine/godot/assets/9283098/f1ea98b7-57a7-4fff-90f2-ac738c73030b)|![DjsunNZG6s](https://github.com/godotengine/godot/assets/9283098/5501f409-61fc-45e1-b5e1-503cd67fe4e0)|

Closing as not a bug (not sure if there's anything to improve here).

**Closed by kleonc** 2023-10-06 14:52 UTC
