### ISSUE TITLE
Opening project in the Project Manager when run in standalone terminal closes Godot (parent process killed)

### ISSUE THREAD

**Issue by ignaloidas** [godotengine/godot#18304] opened 2018-04-19 20:41 UTC
**Godot version:**
3.0.2

**OS/device including version:**
Kubuntu 17.10 AMD R5 M430 GPU and Intel iGPU

**Issue description:**
When Godot is launched by a console only running Godot (no bash, etc.) when trying to open a project in editor, it crashes

**Steps to reproduce:**
If using KDE based system, launch Godot with this command:
`konsole -e /path/to/godot`
then when you try open a project in a editor, it crashes
EDIT:just tested, also works with terminator

**Minimal reproduction project:**
Tested with official 3D platformer demo

**Comment by LinuxUserGD** [comment] 2018-04-19 21:25
What about xterm (running xterm -e path/to/godot)?

**Comment by ignaloidas** [comment] 2018-04-19 21:27
> What about xterm (running xterm -e path/to/godot)?

Just tested, also crashes, looks like this happens for all terminal emulators

**Comment by Calinou** [comment] 2018-04-19 21:34
I can reproduce this issue on commit https://github.com/godotengine/godot/commit/df79cc86a56c2d18b421ceacda3dee6669e6cbd9 using Fedora 27 and KDE Plasma 5.12.4, by launching Godot using `konsole -e godot` (Godot is available in the `PATH` on this system).

**Comment by akien-mga** [comment] 2018-04-20 06:25
It does not crash and it's not a bug: when you open a project in the project manager, Godot spawns a new process. If you ran the initial project manager project in a standalone terminal, it gets killed when the project manager process is killed, and thus kills the child processes.

**Comment by ignaloidas** [comment] 2018-04-20 11:18
> it gets killed when the project manager process is killed, and thus kills the child processes.

Oh makes sense, any way to circumvent this and have the terminal always alive?

**Comment by LinuxUserGD** [comment] 2018-04-20 13:32
It keeps alive on Antergos using Godot Mono and gnome-terminal, don't know why.

**Comment by Phoenix1747** [comment] 2018-04-24 08:04
>  Oh makes sense, any way to circumvent this and have the terminal always alive?

Just open the terminal yourself and then execute Godot like any other normal program? What are you trying to do? :thinking:

**Comment by Phoenix1747** [comment] 2018-04-24 16:38
Ah I see, try making a starter with `/path/to/godot_binary` that works for me. If you got it installed you can just do `/usr/bin/godot`, hope this helps :)

**Comment by Calinou** [comment] 2018-04-24 17:53
Would something like `konsole -e bash /path/to/godot` work in this case as a workaround, so that a shell is started?

**Comment by akien-mga** [comment] 2018-05-01 09:54
Just for the cross-reference, different issue but similar cause (process forking when opening a project): #18233

**Comment by akien-mga** [comment] 2020-09-14 13:27
This seems no longer reproducible for me with Godot 3.2.2 on Mageia, running `konsole -e godot`. The spawned terminal gets closed when editing a project in the project manager, but the newly spawned instance doesn't get killed.
Can anyone still reproduce it?

**Comment by ignaloidas** [comment] 2020-09-14 13:36
> This seems no longer reproducible for me with Godot 3.2.2 on Mageia, running `konsole -e godot`. The spawned terminal gets closed when editing a project in the project manager, but the newly spawned instance doesn't get killed.
> Can anyone still reproduce it?

Same behavior here, tested with `konsole` and `gnome-terminal`. Seems OK to close this now.

**Comment by akien-mga** [comment] 2020-09-14 14:07
Thanks, closing.

**Closed by akien-mga** 2020-09-14 14:07 UTC
Labels: platform:linuxbsd, topic:editor
