### ISSUE TITLE
[3.0] Cannot build master branch in Windows after changes on platform\iphone\export\export.cpp

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9555] opened 2017-07-08 10:34 UTC
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 3.0 commit fdcac7be02e119e5fdc43bd650921d799e65b8ef

**Issue description:**
.-Did a git pull origin master
.-Build with scons as usual
.-Error:
platform\iphone\export\export.cpp(265) : error C3861: 'chmod' identifier not found

**Comment by akien-mga** [comment] 2017-07-08 10:35
Duplicate of #9554.

**Closed by akien-mga** 2017-07-08 10:35 UTC

**Comment by rubenjavier** [comment] 2017-07-08 10:38
sorry, got away from my PC and took too long to report and didnt check just before posting
