### ISSUE TITLE
Godot 4.0 Gridmap change floor hotkeys broken

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#71916] opened 2023-01-23 14:51 UTC
### Godot version

4.0 beta 14

### System information

Windows 10

### Issue description

The hotkeys to change floor in gridmap don't work as they are also used by the select mode and rotate mode tools. Temporary fix: clear the editor hotkeys for Select and Rotate mode and it works in gridmap.

### Steps to reproduce

Add a gridmap, attempt to use Q and E to change floors, Select and Rotate hotkeys will supersede the floor change in Gridmap.

### Minimal reproduction project

N/A

**Comment by jkulawik** [comment] 2023-04-06 21:25
Cursor Clear Rotation (W) does not work too

**Comment by akien-mga** [comment] 2023-05-15 12:34
> Duplicate of #71916?

You linked this very issue.

**Comment by tavurth** [comment] 2023-05-15 17:31
Sorry was shuffling many tabs:

https://github.com/godotengine/godot/issues/67497

**Comment by akien-mga** [comment] 2023-05-16 09:05
Duplicate of #67497

**Closed by akien-mga** 2023-05-16 09:05 UTC
Labels: bug, topic:editor, confirmed, usability, regression, topic:3d
