### ISSUE TITLE
LineEdit does not open the iPad virtual keyboard when exported to HTML 

### ISSUE THREAD

**Issue by ofrias** [godotengine/godot#45906] opened 2021-02-11 19:07 UTC
**Godot version:**
 Godot v3.2.3

**OS/device including version:**
MacOS exporting to HTML

**Issue description:**
When clicked, a LineEdit does not open the virtual keyboard (of a tablet or phone) when running on an HTML exported project

**Steps to reproduce:**
1) Open on a phone or tablet a project exported to HTML containing a LineEdit, for example  https://origamer.itch.io/ortografiator
2) Click on the LineEdit
3) The device virtual keyboard should open, but it doesn't

**Minimal reproduction project:**
Any project with a LineEdit exported to HTML

**Comment by Calinou** [comment] 2021-02-11 20:50
Duplicate of https://github.com/godotengine/godot/issues/32680.

**Closed by Calinou** 2021-02-11 20:50 UTC
