### ISSUE TITLE
Duplicated instances with an exported node already set inside the scene file reuse the same subnode instance

### ISSUE THREAD

**Issue by jkulawik** [godotengine/godot#85187] opened 2023-11-21 19:08 UTC
### Godot version

4.1.3

### System information

Linux, Pop OS 22.04 LTS

### Issue description

If you set an export inside a scene file, instance that in another one and then duplicate that instance, it will cause the instances to use the same subnode instance. For example, this caused two characters in my game to make calls to the same navigation agent and animation tree owned by the 1st character, causing the 2nd character to not work properly.

This behavior is very confusing and goes against the common sense of how Godot works. Perhaps exports should not be set in a scene's root node, but to me it seems like the functionality this offers (i.e. not maintaining node path strings) validates such a use case pretty well. If not, then perhaps doing so should cause configuration errors in the editor.

This issue seems to be related to the editor, as the export will be marked as "resettable" in the editor and "resetting" it will solve the issue, i.e. now the duplicated node will use its own subnode. This behavior does not happen if the scene is instantiated manually several times, only during duplication.

Additionally, if the export is changed in the scene file, the duplicate export will not be updated - this seems to me like it's caused by the same root issue.

### Steps to reproduce

In the MRP, there's a scene file ("CustomNode") with this script:
```python
@export var subnode: Node
func _ready():
	print(name, "\t", subnode)
	print(name, "\t", $SubNode)
```
Open the "main" scene and instance CustomNode. Select it and then duplicate (Ctrl+D).
Run the main scene (F6) and see the output:
```
CustomNode	SubNode:<Node#26927432858>
CustomNode	SubNode:<Node#26927432858>
CustomNode2	SubNode:<Node#26927432858>
CustomNode2	SubNode:<Node#26977764514>
```
Note that the 2nd node's exported subnode points to a subnode of the other CustomNode's subnode instance.

Delete the duplicate, click the "reset property" (circular arrow) button on the first node's export, duplicate again and run.
```
CustomNode	SubNode:<Node#26927432858>
CustomNode	SubNode:<Node#26927432858>
CustomNode2	SubNode:<Node#26977764514>
CustomNode2	SubNode:<Node#26977764514>
```
Note that both `subnode` and `$SubNode` now point to the same subnode in both CustomNodes (the expected behavior).

Now, undo twice to revert these last changes. The first CustomNode should have the reset arrow again. Duplicate again, open the CustomNode scene, and change the export to SubNode2. Run the main scene:
```
CustomNode	SubNode2:<Node#26944210080>
CustomNode	SubNode:<Node#26927432858>
CustomNode2	SubNode:<Node#26927432858>
CustomNode2	SubNode:<Node#26977764514>
```
Note that the 2nd Node did not update its export, and that it still points to the SubNode instance from the first CustomNode instance.

### Minimal reproduction project

[EditorBugRepro.zip](https://github.com/godotengine/godot/files/13430117/EditorBugRepro.zip)

**Comment by kleonc** [comment] 2023-11-22 15:19
Closing as duplicate of #82670.

**Closed by kleonc** 2023-11-22 15:19 UTC
