### ISSUE TITLE
Godot editor accepts non-ascii chars but doesn't show them

### ISSUE THREAD

**Issue by tapir** [godotengine/godot#871] opened 2014-11-09 10:50 UTC
As a result, there might be invisible unknown characters in the code

**Comment by kubecz3k** [comment] 2015-11-02 09:52
Closing because it's old, and from my experience it seems like the problem was caused by not using/importing  font with national characters. Feel free to open new one if this is not the case.

**Comment by tapir** [comment] 2015-11-02 09:57
Let me put it this way: If the font doesn't have non-ascii chars then editor should not accept it. The current behaviour is that, you accidently hit a key lile ş, ı, ğ etc. Most of the time you don't even notice it and then you spent hours why the code does not work. You can't even fix it without opening the code in a proper text editor. I think this should be reopened.

**Comment by kubecz3k** [comment] 2015-11-02 11:27
@tapir thank you very much for your comment. Indeed it was my mistake to close this issue. The worst part is the editor pretends it's not accepting these characters since cursor is not moving, but they are still there.

**Comment by tapir** [comment] 2015-11-02 11:52
:+1:

**Comment by akien-mga** [comment] 2015-11-10 22:25
I confirm this issue, it hit me when testing #2491.

**Comment by tapir** [comment] 2016-01-26 15:54
In the name of all non-ASCII keyboard layout users, can we get this fixed for 2.0 :)
This bug is really annoying. Etiher we should use a utf-8 font by default or the text editor shouldn't accept non-ASCII chars.

**Comment by reduz** [comment] 2016-01-26 15:56
this will be fixed in 2.1 when Godot gets proper internaitonalization

**Comment by abdlquadri** [comment] 2016-01-29 12:08
Looking at the the 2.1 roadmap it seems Internationalisation is absent. http://www.godotengine.org/projects/godot-engine/roadmap

**Comment by reduz** [comment] 2016-01-29 12:26
i have a more up to date list, but will post it on the new website

**Comment by kubecz3k** [comment] 2016-01-29 12:35
@abdlquadri actually it's even on this old list, under the "Editor #27: Make editor translatable"

**Comment by reduz** [comment] 2016-01-29 12:38
yeah, the new issue i wrote down is to use dynamically generated fonts, so
using unicode for multiple languages is easier

**Comment by akien-mga** [comment] 2016-05-29 18:19
Fixed in 3e8eb39 \o/

**Closed by akien-mga** 2016-05-29 18:19 UTC
Labels: bug, confirmed, topic:editor
