### ISSUE TITLE
Moving platform with tilemap does not working properly

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#35550] opened 2020-01-25 13:51 UTC
[**Godot](url) version:**
**OS/device including version:**
3.1 & 3.2 - MAC/WIN

**Issue description:**
[movingTilemap.zip](https://github.com/godotengine/godot/files/5309940/movingTilemap.zip)

Similar to what happened with a KinematicBody2D on a platform before 3.1, there are issues when the platform has a Tilemap (as collisions):
   - vertical movement : the body "enter" in the platform
   - horizontal movement: the body move with the horizontal movement

[screenshot](https://i.ibb.co/qpdpPSq/Capture-d-e-cran-2020-01-25-a-17-55-59.png)

I tried different setup in the demo project, but nothing works.

- Setup1: Kinematic Parent with sync to physic, static Tilemap => vertical movement seems ok
- Setup3: Node2D Parent, static Tilemap => not working
- Setup2: Node2D Parent, Tilemap with kinematic collision => not working
- Setup4: Kinematic Parent, Tilemap with parent collision => not working with movements
  - vertical: when the platform goes up, you can't move
  - horizontal: you are accelerated/decelerated according the platform movement.

Edit: My assumption is, it should work with "use parent" on the tilemap (but I'm not sure)

**Comment by madmiraal** [comment] 2020-05-24 08:45
It's unclear to me what the issue is. What do you mean by "not working"? What is the current behaviour? What is the expected behaviour?

If there are multiple issues, you should close this issue and create a separate issue for each problem, together with a minimal reproduction project clearly demonstrating that one problem. Also, you should upload images, example projects, etc. directly to Github instead of using links to external storage providers.

**Comment by fabriceci** [comment] 2020-05-24 10:09
> It's unclear to me what the issue is. What do you mean by "not working"? What is the current behaviour? What is the expected behaviour?

If you want a body follows (without moving) properly a platform in 3.1, you need to check the "sync to physics" box. But like in KinematicBody3D, there is not "sync to physics" checkbox on tilemap, so I tried different setup.

Maybe the issue should be renamed "Add sync to physics checkbox to the tilemap"

**Comment by madmiraal** [comment] 2020-05-25 08:10
> Add sync to physics checkbox to Tilemap/GridMap

That would make this a feature request and not a bug. Feature requests should be made [here](https://github.com/godotengine/godot-proposals).

**Comment by bojidar-bg** [comment] 2020-05-25 08:20
You can probably use some StaticBody2D/KinematicBody2D with sync to physics, then put the TileMap as a child and turn on "use parent" for collisions. I'm afraid there isn't a similar workaround for GridMaps, however.

**Comment by fabriceci** [comment] 2020-05-25 10:17
> That would make this a feature request and not a bug.

I do not agree, that's a possible solution not a new feature. Furthermore, I forgot the existence of the "use parent" checkbox used in the setup n°4, this option should act like the parent (KinematicBody2D with sync to physics), but it doesn't.

If I'm wrong, feel free to close the issue.

> You can probably use s...

@bojidar-bg It's already tested in my setup n ° 4

The workaround I found is not to use the "_physics_process" function for kinematic bodies, but instead keep them in a list in the scene node, and "update" them in the right order. In case of a collision with the platform apply the platform velocity to the player. It's working but it's restrictive / heavy.

**Comment by pwnorbitals** [comment] 2020-10-01 06:42
> According to my understanding the setups 2 and 4 should work.
> 
>     setup 4: physics issue?
>     setup 2 : I think the Tilemap needs the motion parameter: sync to physic (in kinematic mode).

This sounds like two different issues, one being a feature request

**Comment by fabriceci** [comment] 2020-10-01 06:58
@pwnorbitals I think it is not necessary to have a sync to physics after all, because there is already a "use parent" checkbox.

**Closed** 2021-03-25 19:16 UTC
Labels: bug, topic:physics
