### ISSUE TITLE
Odd AnimationPlayer behavior

### ISSUE THREAD

**Issue by gusthe** [godotengine/godot#54815] opened 2021-11-09 20:23 UTC
### Godot version

4.0dev (20211108)

### System information

Manjaro

### Issue description

The AnimationPlayer has trouble changing the animation of and AnimatedSprite2D if the change happens at the start of the track. In the video it fails every time, but some times it will work randomly.

https://user-images.githubusercontent.com/11148529/140995876-071aba35-2047-4a05-9849-96c8ea284e96.mp4

### Steps to reproduce

To reproduce:
1: create an AnimatedSprite2D with two animations and an AnimationPlayer
2: AnimationPlayer: Make a new animation track for the AnimatedSprite2D animation
3: AnimationPlayer: Set the first key at the start of the track, then set the second any where after.
4: play the AnimationPlayer like I showed in the video.

**Comment by Calinou** [comment] 2021-11-10 00:08
@gusthe Can you reproduce this in 3.4 or only in `master`?

**Comment by gusthe** [comment] 2021-11-10 00:28
It only happens in master.

**Comment by gusthe** [comment] 2021-11-10 00:52
I thought it only did it with the animation track, but after some more testing it happens with things like changing the visibility of a node or it's z_index. So I think every key at the 0 time mark is getting skipped.

**Comment by TokageItLab** [comment] 2021-11-10 20:47
I'm wondering if it seems to work correctly when you manually reset the timeline to 0.
Does the problem only occur when Restarting in the editor? Do you get a problem with the script when running the scene?

**Comment by gusthe** [comment] 2021-11-10 21:07
Sorry, I should have mentioned that it's not isolated to the editor. It does also happen when running the scene.

**Comment by gusthe** [comment] 2021-11-11 03:09
I did some more testing, and the bug isn't present on 4.0dev (20210727), but is present on 4.0dev (20210811) and later.

**Comment by TokageItLab** [comment] 2021-11-11 06:12
Can you determine the commit hash with bisect?
https://docs.godotengine.org/ja/stable/community/contributing/bisecting_regressions.html

**Comment by TokageItLab** [comment] 2021-11-11 06:27
So, what I'm saying is that NodeOneShot is currently designed to play during Activation, and if you want to fade it out after it's been Deactivated, it needs to be played even though it's not in Activation. This means that some process changes are required. However, I think it is not impossible, so as an Enhancement I am interested in this.

**Comment by gusthe** [comment] 2021-11-13 19:56
I get this revision after bisecting.
[78d33a6e24a3977fc3a2c66808d7cbdddd3add11] Use doubles for time in animation code

**Comment by TokageItLab** [comment] 2021-11-13 20:24
Thanks! It is indeed possible that the key is failing to be gotten due to differences in the precision of the values.

Godot 4 has changed the time used in animations to use double instead of float, but you still need to use float in methods exposed as GDScript.

The bug may be caused by an implicit conversion between double and float somewhere in the passing between the methods, which reduces the accuracy.

**Comment by gusthe** [comment] 2021-11-14 00:52
Sorry I thought 0 steps left meant that it was at the end of the bisect, but I needed to do one more test.
After the last test I got. 84f720966c74d5b37f70e21867e9e3e6a1e44c36 Use doubles for time in many other places

**Comment by TokageItLab** [comment] 2021-11-14 05:54
@gusthe By the way, does the bug still occur if you set AnimationPlayer `Process Mode` to `Physics`?

**Comment by gusthe** [comment] 2021-11-15 00:17
Yeah, it still happens after setting the AnimationPlayer to Physics.

**Comment by TokageItLab** [comment] 2021-11-26 23:13
@gusthe Thank you for your help with the investigation! It might be fixed by #55371, please check it :)

**Closed** 2021-11-27 00:14 UTC
Labels: bug, topic:editor, regression, topic:animation

**Comment by gusthe** [comment] 2021-11-27 01:30
@TokageItLab Yep, that fixed it! Thank you!
