### ISSUE TITLE
CSGMesh fails to render after creation

### ISSUE THREAD

**Issue by MiK546** [godotengine/godot#50286] opened 2021-07-08 18:16 UTC
### Godot version

v3.3.2-stable_mono_x11.64

### System information

Linux Mint 20.1, GLES3, Nvidia RTX3070 (Driver version 460.84)

### Issue description

If you add a CSGMesh as a child of any Spatial node and add any of most mesh types to it the mesh is not rendered. Instead the following error is printed to the output tab:

```
 drivers/gles3/rasterizer_storage_gles3.cpp:4084 - Index p_surface = 0 is out of bounds (mesh->surfaces.size() = 0).
 servers/visual_server.cpp:1595 - Condition "vertex_data.size() == 0" is true. Returned: Array()
 modules/csg/csg_shape.cpp:738 - Condition "arrays.size() == 0" is true. Returned: _post_initialize(new ("") CSGBrush)
```
If you move the CSGMesh under some other node, it starts rendering correctly. It can even be moved back to the original place after that and it continues to work. Reloading the project also seems to cause the CSGMesh to render correctly. The problem only happens after a mesh is added to a previously unused CSGMesh.

Some mesh types, like capsule and sphere, do not cause the bug for some reason. Others, including cube, cylinder, plane, prism or quad do.

### Steps to reproduce

1. Create an empty project
2. Create a new 3D scheme (Spatial as root node)
3. Create a new CSGMesh as a child of the Spatial
4. Add a cube, cylinder, plane, prism or quad mesh to the CSGMesh node
5. The mesh won't render and instead the error listed above is printed to the output tab

### Minimal reproduction project

This won't hopefully be necessary as the bug requires adding only 1 node to an empty project. The bug also fixes itself if loading from a project so the CSGMesh node would need re-creating anyway.

**Comment by Calinou** [comment] 2021-07-08 19:29
cc @madmiraal

**Comment by madmiraal** [comment] 2021-07-09 05:01
Duplicate of #46610.

**Closed by madmiraal** 2021-07-09 05:01 UTC
Labels: bug, topic:3d, topic:core
