### ISSUE TITLE
Octree error on editor launch with visible collision shapes

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#13840] opened 2017-12-02 22:15 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot 3 Beta 1

**Issue description:**

When launching a 2D game from the editor, there is a seemingly random chance for the following error to pop up in the Debugger dock, under `Errors`, when `Visible Collision Shapes` is enabled under the Debug menu:
```
ERROR: Octree<struct VisualServerScene::Instance,1,class DefaultAllocator>::create: Condition ' p_aabb.position.x > 1e15 || p_aabb.position.x < -1e15 ' is true. returned: 0
   At: core\math\octree.h:800
```
It does not seem to actually affect anything and causes no harm outside of confusing the user into thinking there is an actual error, the game itself runs fine.

**Steps to reproduce:**
Create a project, place a Body with a CollisionShape2D and `Visible Collision Shapes` enabled, then hit play over and over until you see an error in the Debugger dock.

**Comment by leoddd** [comment] 2017-12-02 22:26
(Edited because I figured out that it was visible collision shapes causing this to happen, at the very least it did not happen for 20 launches in a row after disabling them and re-appeared immediately upon re-enabling them.)

**Comment by reduz** [comment] 2017-12-05 17:54
it may be possible that the body falling eventually reached really large values, which the octree complained about because of the visibility. Not quite sure if this could be considered a bug. Is this at the beginning, or after a while?

**Comment by leoddd** [comment] 2017-12-05 22:30
This is immediately on launch, and the body does not move.

**Comment by akien-mga** [comment] 2018-01-06 21:36
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by volzhs** [comment] 2018-04-11 16:59
I could create a sample project for this.

[Error on launch.zip](https://github.com/godotengine/godot/files/1899729/Error.on.launch.zip)

run with `Visible Collision Shapes` option at Debug menu.
weird thing is that error is gone if `icon.png` is assigned instead of `icon_630x360.png` to sprite texture in the sample project.

**Comment by nazgum** [comment] 2018-04-22 21:07
Just figure I would add I also encounter this.  It only happens with visible collision shapes on.

Using Godot 3.0.2 on Ubuntu Linux 17.10 in a 2D project

**Comment by reduz** [comment] 2018-11-11 12:36
I can no longer reproduce this. Tested on Ubuntu an Windows. may have been fixed. Please reopen if you manage to find a different way to do it.

**Closed by reduz** 2018-11-11 12:36 UTC
Labels: bug, topic:core

**Comment by 95camarones** [comment] 2018-12-05 21:03
I am getting a similar readout with Godot 3.0.6 on OS X El Capitan. With visible collision shapes, I get the following error:

> 0:00:00:0922 - Condition ' p_aabb.position.x > 1e15 || p_aabb.position.x < -1e15 ' is true. returned: 0
> ----------
> Type:Error
> Description: 
> Time: 0:00:00:0922
> C Error: Condition ' p_aabb.position.x > 1e15 || p_aabb.position.x < -1e15 ' is true. returned: 0
> C Source: core/math/octree.h:801
> C Function: create

**Comment by travm** [comment] 2019-01-01 08:41
I've also ran into this as well. For my setup, I'm preloading the scene in a global and assigning it to a dictionary to reference throughout the game. It happens immediately on boot without actually instancing the scene in the game. 

I hope that helps, happy to provide further details if needed.

**Comment by numerical25** [comment] 2019-01-14 02:17
I am experiencing the issue too. Its not threatening but its there. I ran all my scenes individually and I noticed that the error (For Me) occurs in my parallax scene which only has a ParallaxBackground Node  4 ParrallaxLayer Child Nodes. And for Each ParrallaxLayer I have 1 Sprite Node for the Background Images.
