### ISSUE TITLE
Dragging a number field in material editor eats the cursor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#13988] opened 2017-12-05 00:49 UTC
Godot 3.0 beta 1
Windows 10 64 bits

Same as https://github.com/godotengine/godot/issues/3196, just happened for me in beta 1 while dragging SpatialMaterial/Rim/Tint.

**Comment by reduz** [comment] 2017-12-05 15:36
All this logic for range drag is here:
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2418

Feel free to give it a check/review.

**Comment by mortem-malum** [comment] 2017-12-06 20:54
I cannot seem to replicate this bug on beta 1 or a dev build. Could it be possible that this bug is due to a driver or other systems related error?

**Comment by Zylann** [comment] 2017-12-06 20:56
@mortem-malum did you specifically tried on the SpatialMaterial/Rim/Tint property?

**Comment by mortem-malum** [comment] 2017-12-06 21:19
Yes with multiple objects and scenes.

**Comment by mortem-malum** [comment] 2017-12-06 21:23
But reduz's suggestion on #3196 would be a good if this is system specific.

**Comment by Zylann** [comment] 2017-12-06 21:41
I tried again with master on the same field and couldn't reproduce... maybe it's random, or was fixed by luck?

**Comment by akien-mga** [comment] 2018-01-05 14:01
Seems like the same as #15351? Let's close as duplicate of the latter which is more detailed.

**Closed by akien-mga** 2018-01-05 14:01 UTC
Labels: bug, hero wanted!, topic:editor
