### ISSUE TITLE
DisplayServer: ColorPicker doesn't hide after selecting a color

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45745] opened 2021-02-05 22:35 UTC
**Godot version:**
Godot Engine v4.0.dev.calinou.779dc7613

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
When dealing with worldenvironment node, I was choosing the ambient color, but when clicked on the color the popup doesnt hide:

![image](https://user-images.githubusercontent.com/58845030/107096206-f1b24d80-67e8-11eb-91d0-1ed930bad33b.png)

**Steps to reproduce:**
- Create worldenvironment
- Change ambient color

**workaround**

Click on godot icon in the taskbar.

**Comment by KoBeWi** [comment] 2022-05-04 18:20
What do you mean by doesn't hide? It works the same in 3.5, you need to click outside the picker or press Escape to hide it. This is intended behavior.

**Comment by akien-mga** [comment] 2022-11-21 15:39
Closing based on above comment.

**Closed by akien-mga** 2022-11-21 15:39 UTC
Labels: bug, regression, topic:gui
