### ISSUE TITLE
Godot 4 "super" throwing error, but still working.

### ISSUE THREAD

**Issue by WideArchShark** [godotengine/godot#66838] opened 2022-10-03 18:37 UTC
### Godot version

4.0 beta 2

### System information

Windows 10, 64 bit 32GB RAM

### Issue description

I've created a class _init(x) that sets a variable. My subclass calls the "super", also with an argument. It works absolutely fine, but I get:
`Too many arguments for "_init()" call. Expected at most 0 but received 1.`

### Steps to reproduce

**File 1:**
```
extends Node

class_name GameState

var game_state_manager : GameStateManager

func _init(gsm) -> void:
	game_state_manager = gsm
```

**File 2:**
```
extends GameState

class_name PlayerTurnState

func _init(gsm) -> void:
	super(gsm)
```

File 2 throws the error.

**Comment by Tyrannosaurus1234** [comment] 2022-11-19 23:37
Can confirm this still happens on 4.0 beta 5.

**Comment by Chaosus** [comment] 2022-11-22 12:40
Please attach a minimal reproducing project. I get a different error when trying to reproduce it:

![image](https://user-images.githubusercontent.com/3036176/203316396-62e3e157-d5de-4800-aebd-3b733c3ec931.png)

**Comment by red1939** [comment] 2022-12-05 14:19
@WideArchShark Remember that if the PlayerTurnState is indeed a node which is placed inside a prefabricated scene, it shouldn't be non-default constructible. How are you instantiating it?

**Comment by red1939** [comment] 2022-12-05 17:22
@Tyrannosaurus1234 Could you provide a more meaningful example/project?

**Comment by dalexeev** [comment] 2023-02-14 12:49
I tested this in d2699dc7a. This works correctly and without any errors/warnings if you do `PlayerTurnState.new(gsm)`.

Note that if you want to store such a node in the scene file, **all** arguments to its constructor must have default values, as red1939 wrote above.

See also:

* godotengine/godot-proposals#1513
* godotengine/godot-proposals#5899
* godotengine/godot-proposals#1935

There was also a proposal (or comment) to add the ability to specify arguments for the constructor to the Inspector, but I couldn't find it.

**Comment by vnen** [comment] 2023-02-22 14:37
I cannot reproduce the issue in the OP. Given the comments it might be a misunderstanding. This is not a bug but a limitation of the system. Since the improvement requests are already tracked by other issues, I'll close this one.

**Closed by vnen** 2023-02-22 14:37 UTC
Labels: bug, topic:gdscript
