### ISSUE TITLE
Whole desktop freezes when trying to resize Godot window

### ISSUE THREAD

**Issue by A404M** [godotengine/godot#74749] opened 2023-03-10 23:53 UTC
### Godot version

4.0-2

### System information

Arch Linux,Intel UHD+Nvidia RTX 3050,Wayland,Gnome

### Issue description

godot is freezing when I try to resize the window by dragging the edge and moving my mouse in any mode except Compatibility mode.
I tested on Godot 3 and it was fine. Godot 4 has the problem.
Even it works fine on X11 but has the problem with Wayland

### Steps to reproduce

resize the godot in Forward+ or Mobile mode in godot or godot-mono with Wayland.

### Minimal reproduction project

Plain project

**Comment by Calinou** [comment] 2023-03-13 19:21
- Duplicate of https://github.com/godotengine/godot/issues/74850.

**Closed by Calinou** 2023-03-13 19:21 UTC
Labels: bug, platform:linuxbsd, topic:porting

**Comment by A404M** [comment] 2023-03-15 19:12
> * Duplicate of [Godot window crashes and becomes unresponsive [Linux Gnome] #74850](https://github.com/godotengine/godot/issues/74850).

This issue isn't as same as the other one you linked.

**Comment by A404M** [comment] 2023-03-26 04:50
After update 4.0.1-1 I opened godot and it told me I have no vulkan driver for current gpu (I had for nvidia one but the app runs on intel gpu most of the time) after installing vulkan driver which is intel-vulkan I now have no issue with it. thanks
