### ISSUE TITLE
Blendshape flicker in 3.4.1

### ISSUE THREAD

**Issue by inkfood** [godotengine/godot#56118] opened 2021-12-21 06:01 UTC
### Godot version

3.4.1

### System information

osx

### Issue description

Animated blend shape causes flickering of models. Works in 3.4, does not work in 3.4.1

![godot_3 4 1_flicker](https://user-images.githubusercontent.com/8083536/146879222-d96aae8b-6e48-4f38-aa0e-f813e44f21a5.gif)

(left:baseMode, center: model with animationPlayer running, right: model with animationPlayer not running)

### Steps to reproduce

Create new node, add Model with blendshapes, tick local to scene box on mesh, add animationaPlayer & animate blend shapes. Drag this Node into the main scene multiple time. All objects will flicker if on one of them the animation runs.  
(Model imported from blender via gltf)

### Minimal reproduction project

https://github.com/inkfood/blendShape_flicker

**Comment by clayjohn** [comment] 2021-12-21 07:50
May be a duplicate of https://github.com/godotengine/godot/issues/56055

**Comment by akien-mga** [comment] 2021-12-21 08:17
> May be a duplicate of #56055

Pretty likely indeed.

**Closed by akien-mga** 2021-12-21 08:17 UTC
Labels: bug, platform:macos, topic:rendering, regression

**Comment by inkfood** [comment] 2021-12-21 08:38
Confirmed! Tested with this build  https://github.com/bruvzg/godot/tree/macos_gl_off_ctx.

Thank you
