### ISSUE TITLE
Support for saving multiple Images in BakedLightmap is not implemented properly

### ISSUE THREAD

**Issue by gdlq** [godotengine/godot#61603] opened 2022-06-01 13:21 UTC
### Godot version

3.5RC2

### System information

Windows 10, GLES3

### Issue description

I can’t believe I have to do this again…
In previous issue #61547 I explain a problem with inability to bake multi-image atlases, no matter what I do it bakes all in one single atlas (or worse it didn’t bake at all).

@JFonS explained that this happens because of the very large mesh, so this time I **removed that mesh** from MRP and kept only standard cubes imported from Blender. 
Lightmap scale is set to 4x, Atlas Size is 2048 and yet it bakes all in **single absurdly large 2048х12288 atlas**!
And if you set lightmap scale to 1x it **still bakes single lightmap as 512x3072**, which doesn't make any sense because we set 2048 in Atlas Size.
Issue #58102 seems to be implemented incorrectly and doesn't create multiple baked .exr lightmap textures.

### Steps to reproduce

Bake lightmaps from minimal reproduction project.

### Minimal reproduction project

[test_lightmap_large_3.x.zip](https://github.com/godotengine/godot/files/8814448/test_lightmap_large_3.x.zip)

**Comment by JFonS** [comment] 2022-06-01 17:18
Duplicate of #61547, answered [there](https://github.com/godotengine/godot/issues/61547#issuecomment-1143899480).

**Closed by JFonS** 2022-06-01 17:18 UTC
Labels: bug, topic:rendering, topic:3d
