### ISSUE TITLE
Scripts in subfolder raise "Cannot instance script because the associated class could not be found"

### ISSUE THREAD

**Issue by ObsidianDoom** [godotengine/godot#90121] opened 2024-04-02 00:00 UTC
### Tested versions

Reproducible in : v4.2.1.stable.mono.official [b09f793f5], v4.2.stable.mono.official [46dc27791], v4.3.dev5.mono.official [89f70e98d]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19044 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.5176) - 12th Gen Intel(R) Core(TM) i5-12600 (12 Threads)

### Issue description

If a C# script, e.g. Startup.cs, is in a subdirectory of res://, e.g. res://Scripts/Startup.cs, and attached to a scene via
```
[ext_resource type="Script" path="res://Scripts/Startup.cs" id="1_7futq"]
```
when attempting to run the scene - the error is displayed
```
can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://Scripts/Startup.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
```

If the C# script is not in a subdirectory but in the root, i.e. res://Startup.cs, and attached to a scene via
```
[ext_resource type="Script" path="res://Startup.cs" id="1_7futq"]
```
The scene runs with no errors.

The expectation is that scripts should be able to stored in subdirectories and when referenced as such the scene should run with no errors.

### Steps to reproduce

Two mrps attached, one which fails and illustrates the problem ( mrp-fails ) and one which works - by not using scripts in sub directories ( mrp-works )

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/14829639/mrp.zip)

**Comment by ObsidianDoom** [comment] 2024-04-02 09:18
Thank you for investigating. I was not aware of the pre-requisite to include the *.csproj file(s) in the same directory as project.godot (perhaps that needs to be emphasised somewhere in documentation, if it is not already).

Having done as you suggested and also restructured the solution in Visual Studio IDE to have a folder below the project containing the cs files I can now reference the scripts in the subdirectory via the ext_resource path and the scene runs. If this is "working as designed" then this issue can be closed.

**Comment by paulloz** [comment] 2024-04-02 10:46
There are no requirements on having `*.csproj` in the same folder as `project.godot`. Only the one project file associated with Godot.

It's true that it might not be emphasized that much in the documentation. IMO, it's because this file is generated by the engine at the right place, and moving it around exposes the user to the same kind of issues as moving around any other mandatory file. If you feel it should still be emphasized, I invite you to do so in the [documentation repository](https://github.com/godotengine/godot-docs).

Otherwise, yes, I'd say this is working as intended.

**Closed** 2024-04-02 11:15 UTC
Labels: bug, needs testing, topic:dotnet
