### ISSUE TITLE
Suggestion: fly mode shortcuts changes

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#28156] opened 2019-04-18 10:35 UTC
I suggest to change the shortcuts in fly mode to make it compatibly with AZERTY keyboards.
Forward: W or Z
Backward: S
Left: A or Q
Right: D
Upward: Space
Downward: Ctrl

**Comment by MissKraya** [comment] 2019-04-18 16:17
I use Q and E for vertical movement a fair amount, I don't know how much other people do but I think this would be better as an editor option you can toggle... better yet allow for complete editor key rebinding?

**Comment by Calinou** [comment] 2020-02-02 17:29
Duplicate of #11777.

**Closed by Calinou** 2020-02-02 17:29 UTC
Labels: enhancement, topic:editor, usability
