### ISSUE TITLE
Support more formats for project translations

### ISSUE THREAD

**Issue by wkubiak** [godotengine/godot#6339] opened 2016-08-31 10:26 UTC
**Operating system or device - Godot version:**
Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Currently, Godot editor uses gettext format (POT/PO/MO files) for it's localization, while Godot projects are supposed to utilize .csv format files.

I understand the pros of using spreadsheets for keeping string translations, but the format has it's issues too, like having to stay careful in regards to the tools you use for editing them (newer versions of Excel can seriously bloat a simple .csv file). One user has issue #5640 in regards to encoding and end-line chars.

I propose that Godot should support more formats for importing translations into projects, starting with gettext as it's pretty standard fare today and already supported by the Godot build process.

**Comment by Calinou** [comment] 2016-08-31 17:19
Also, our .csv implementation does not have plurals support, which gettext provides.

**Comment by Calinou** [comment] 2018-04-11 16:45
Closing as a duplicate of https://github.com/godotengine/godot/issues/9398.

**Closed by Calinou** 2018-04-11 16:45 UTC
Labels: feature proposal, topic:core
