### ISSUE TITLE
GDScript print statement doesn't come through in method called from NOTIFICATION_EXIT_TREE on application close request

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#79218] opened 2023-07-08 18:20 UTC
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

When you exit an application the NOTIFICATION_EXIT_TREE is called on all nodes in the scene tree. When you from within this method call "print(...)", the message does not reach the editor of some reason.

### Steps to reproduce

1. Download scene
2. Run scene from editor
3. Click the application exit button
4. Watch as no message comes up in the editor log.

### Minimal reproduction project

[scene.zip](https://github.com/godotengine/godot/files/11991490/scene.zip)

**Comment by dalexeev** [comment] 2023-07-08 18:25
* Duplicate of #79031.

**Closed by dalexeev** 2023-07-08 18:25 UTC
