### ISSUE TITLE
Random (?) crash on Linux

### ISSUE THREAD

**Issue by manungsa** [godotengine/godot#85347] opened 2023-11-25 15:13 UTC
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - EndeavourOS #1 SMP PREEMPT_DYNAMIC Sun, 15 Oct 2023 18:38:43 +0000 - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 520 (SKL GT2) () - Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 Threads)

### Issue description

Godot crashed randomly (?). That's it. I've been experiencing it several times, making some of my unsaved work lost :( ...
I only found this output on the terminal:
```
[user@EndeavourOS] godot_4-1-3
$ ./Godot_v4.1.3-stable_linux.x86_64
Godot Engine v4.1.3.stable.official.f06b6836a - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 23.2.1-arch1.2 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 520 (SKL GT2)

Editing project: /home/user/mnt/godot/project
Godot Engine v4.1.3.stable.official.f06b6836a - https://godotengine.org
Vulkan API 1.3.255 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 520 (SKL GT2)
[user@EndeavourOS] godot_4-1-3
$
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8224)
[xcb] Unknown request in queue while dequeuing
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
Godot_v4.1.3-stable_linux.x86_64: xcb_io.c:175: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```

### Steps to reproduce

Unknown

### Minimal reproduction project

None

**Comment by Cykyrios** [comment] 2023-11-25 17:23
See #75308 for more details.

**Comment by Chaosus** [comment] 2023-11-26 10:08
Duplicate of #75308

**Closed by Chaosus** 2023-11-26 10:08 UTC
