### ISSUE TITLE
Vulkan: Random meshes vanish in large scenes with lights that have a projector texture

### ISSUE THREAD

**Issue by DAShoe1** [godotengine/godot#68274] opened 2022-11-04 22:38 UTC
### Godot version

4.0.beta3

### System information

Windows 11, AMD Vega64 Driver 22.8.1, Vulkan

### Issue description

When a scene has a large number of MeshInstance3D nodes (more than 980 in the MRP) and a Spotlight3D or Omnilight3D with a projector texture is added to the scene and moved around, Godot will randomly stop drawing meshes. Reloading the scene will restore them. This occurs within the editor as well as at runtime.

https://user-images.githubusercontent.com/117487773/200084568-f2694824-ea7f-40ef-ac85-e4bebecfff0b.mp4

### Steps to reproduce

- Add at least 980 MeshInstance3D nodes with a BoxMesh.
- Add a Spotlight3D or Omnilight3D, enable shadows, and assign a texture to the projector.
- Move the light around the scene.

### Minimal reproduction project

[Light_Projector_Test.zip](https://github.com/godotengine/godot/files/9942340/Light_Projector_Test.zip)

**Comment by Calinou** [comment] 2022-11-04 23:30
I can confirm this on 4.0.beta 282e50ac8 (Fedora 36, Radeon RX 6900 XT with RADV). This only occurs on Vulkan Clustered, not Vulkan Mobile.

**Comment by 73v3** [comment] 2022-11-05 00:12
I'm seeing almost identical behaviour in my project on Beta 4 (Windows 10. NVIDIA GTX 2070 super) Vulkan mobile. 

Moving the player causes random tiled meshinstance3Ds to vanish. 

Behaviour stops when I: 
- move the tiles further away from player
- turn off the omni light on the player
- drop the number of 3d tiles in the scene. 

I'm not using a projector texture. Just a vanilla omnilight3d. 

Sorry to barge into your thread but it looks like the same issue and may help clarify the underlying bug.

**Project** (20Mb, sorry)

[VanishingMeshes.zip](https://github.com/godotengine/godot/files/9942552/VanishingMeshes.zip)

**Comment by Calinou** [comment] 2022-11-05 00:31
@73v3 Your issue occurs when using Vulkan Mobile, so it is unrelated. Please open a separate issue with the minimal reproduction project attached.

**Comment by 73v3** [comment] 2022-11-05 01:17
> 

Apologies. Renderer was actually set to forward_plus. Switching to mobile fixes the issue.

**Comment by dzil123** [comment] 2022-11-05 06:11
I'm getting this error when closing the editor after observing the behavior: 
```
ERROR: Pages in use exist at exit in PagedAllocator: N33RendererSceneRenderImplementation22RenderForwardClustered32GeometryInstanceSurfaceDataCacheE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
```

**Comment by clayjohn** [comment] 2022-11-09 19:44
It looks like the issue is coming from here:
https://github.com/godotengine/godot/blob/e25d9281d4f6f0b5b4d972b25cddaa1009ad1d26/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L3732-L3736
``_mark_dirty()`` is called which frees the surface data, but then for some reason, the surface isn't being reallocated. This will take a bit of investigation to figure out. 

We need to check why the surface isn't being reconstructed in some cases (it appears totally random, so maybe some undefined behaviour has snuck in).

**Closed** 2023-01-20 23:01 UTC
Labels: bug, topic:rendering, confirmed, topic:3d
