### ISSUE TITLE
Godot hangs when (re)importing .obj files

### ISSUE THREAD

**Issue by darrylryan** [godotengine/godot#51315] opened 2021-08-06 12:51 UTC
### Godot version

4.0.dev (b3c2281706778cf5311a68fe0071aa2740d01131)

### System information

Windows 10

### Issue description

Godot 4.0 regularly hangs when (re)importing resources. It seems to happen mostly with .obj meshes for me, but I am not sure if it also happens with other resources.

It seems to me that there are two issues here:

1) The models *do* import correctly the first time I import them... this only happens when something changes which causes it to try to reimport or when I reload the project and it tries to import again. There must be some bad data getting written the first time that breaks the reimporting the second time round.

2) The importer really shouldn't just hang when it can't import a file for whatever reason. There should be some mechanism to catch and report errors and it should timeout if an external importer hangs for too long without any progress.

Also, ideally if an import fails it would seem sensible to replace it with a placeholder mesh or texture rather than just failing so the game still loads and runs rather than just breaking. This is common in other game engines.

### Steps to reproduce

Import an obj such as https://github.com/awkwardpolygons/cartographer/blob/master/addons/cartographer/meshes/clipmap_multi.obj to a project and add it to the scene, and then try reloading the project. It doesn't seem to happen all the time though... I am not sure exactly what triggers it to try to reimport.

### Minimal reproduction project

As above

**Comment by fracteed** [comment] 2021-08-07 02:34
I can also confirm this is an issue.

**Comment by akien-mga** [comment] 2021-08-07 10:18
Related to (possibly duplicate of) #48265.

**Comment by darrylryan** [comment] 2021-08-07 12:29
I think the .obj deadlock is indeed related to #48265

I also found the engine got stuck when importing a png file yesterday too though, so I think there might be a wider issue... we need the .obj importer not to hang if it can't find the material, but we also need the engine to be able to carry on and fall back to default resources if an importer does get stuck or fail for whatever reason (this is also the case with the scene importer by the way - if something is missing it just says the scene is corrupted rather than loading what it can and replacing the rest with placeholders).

**Comment by JestemStefan** [comment] 2021-08-24 12:10
Can someone check if this issue still exists? I have hard time reproducing it on v4.0.dev.20210820.official [75697c0df]

I downloaded `.obj` file from link above and I tried to reproduce it about 20 times according to description, but it never triggered  a deadlock.

**Comment by darrylryan** [comment] 2021-09-06 11:49
Yes, it is still very much broken unfortunately.

**Comment by Calinou** [comment] 2021-09-19 18:18
Duplicate of https://github.com/godotengine/godot/issues/48265 (same cause).

**Closed by Calinou** 2021-09-19 18:18 UTC
Labels: bug, confirmed, topic:import
