### ISSUE TITLE
MeshInstance3D's Surface Material Override gets reset when reimporting mesh

### ISSUE THREAD

**Issue by Lippanon** [godotengine/godot#85850] opened 2023-12-06 15:23 UTC
### Tested versions

v4.3.dev.custom_build [d76c1d0e5]

### System information

Windows 10, Vulkan

### Issue description

Not sure if this is a documentation issue or a MI3D bug. In any case, it's an annoying workflow issue, it's common to make changes to models, and when they have multiple surfaces/slots with different materials, one has to keep setting them. 
GeometryInstance3D's ```material_override``` is much better to work with but not suitable for every case.

A mesh with materials set in the Surface Material Override):
![image](https://github.com/godotengine/godot/assets/115422160/79e661b3-a066-4825-93d0-b81632c2aada)

The associated functions ```set_surface_override_material / get_surface_override_material``` belong to MeshInstance3D.
The docs state "Sets the override material for the specified surface of the Mesh resource. This material is associated with this MeshInstance3D rather than with mesh."
This leads one to think, by being associated with the MI3D node and not the mesh, they should not be reset by simply reimporting the mesh (after changing a setting for example) in the importer:
![image](https://github.com/godotengine/godot/assets/115422160/ffa10661-2c60-4da8-8e21-2b9a95dd2fa0)

However, they do get reset when reimporting.
I understand that changing the Mesh in the MeshInstance3D might change the number of surface slots, even so you could keep the set materials that fit the "new" amount of slots, At least it would be nice if, when the path of the Mesh remains the same, it attempts to keep the materials.

### Steps to reproduce

1. Open the MRP, notice the MeshInstance3D with a cube Mesh and 2 materials set in the override slots;
2. Double click 'a_blender_cube.glb';
3. Select Reimport, notice the Cube is still associated with the MeshInstance3D node, but the override slots have been cleared;

### Minimal reproduction project (MRP)

[SMO_cleared_bug.zip](https://github.com/godotengine/godot/files/13587883/SMO_cleared_bug.zip)

**Comment by OhiraKyou** [comment] 2023-12-11 03:02
I've been encountering this since updating from 4.1.3-stable to v4.2.stable.official [46dc27791]

**Comment by KoBeWi** [comment] 2023-12-11 22:14
Duplicate of #79779

**Closed by KoBeWi** 2023-12-11 22:14 UTC
Labels: bug, confirmed, topic:import, topic:3d
