### ISSUE TITLE
Cannot select wich visual layers contribute to GPUParticlesCollisionHeightField3D

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#74881] opened 2023-03-13 20:53 UTC
### Godot version

4.0 stable

### System information

ArchLinux

### Issue description

There is no way to specify which rendering layers will contribute to the generated collisions with a GPUParticlesCollisionHeightField3D. I tried to change the layers of the property inherited from VisualInstance3D, but it had no effect. I assume the purpose of GPUParticlesCollisionHeightField3D is to generate collisions for terrains easily. However, given there is no way to filter what geometry gets selected, its use cases become very limited.

### Steps to reproduce

Create a flat terrain mesh and add another mesh high above the terrain. Add a GPUParticlesCollisionHeightField3D covering the terrain and the other mesh. Add a particle system above the second mesh. There is no way to have that mesh ignored. Given it's a height field, even if the mesh is detached from the ground, particle collisions will happen underneath that mesh too.

### Minimal reproduction project

N/A

**Comment by and-rad** [comment] 2023-03-13 21:28
Duplicate of #61014.

The `Cull Mask` property is what you're looking for, but it's not currently working for any of the particle attractors and colliders.

![cullmask](https://user-images.githubusercontent.com/8700280/224836244-f936c151-9249-481f-a4a0-b0bbd3eaf0e9.PNG)

**Comment by clayjohn** [comment] 2023-03-13 21:29
Closing as duplicate of https://github.com/godotengine/godot/issues/61014.

**Closed by clayjohn** 2023-03-13 21:29 UTC

**Comment by m4nu3lf** [comment] 2023-03-13 22:55
> Duplicate of #61014.
> 
> The `Cull Mask` property is what you're looking for, but it's not currently working for any of the particle attractors and colliders.
> 
> ![cullmask](https://user-images.githubusercontent.com/8700280/224836244-f936c151-9249-481f-a4a0-b0bbd3eaf0e9.PNG)

If I read correctly #61014, that mask has a different use than what I'm describing. That mask defines what particles collide with the GPUParticlesCollisionHeightField3D whereas I'm describing a mask that defines what meshes are used to generate the GPUParticlesCollisionHeightField3D in the first place.

**Comment by and-rad** [comment] 2023-03-14 07:01
You're right, my bad. And you're right, there is currently no way to do that. SDF particle collision has the ` Bake Mask` property for that use case, so something similar might have to be implemented for the height field collision node too.
