### ISSUE TITLE
Can't Add Script if Script Exists!!

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#7305] opened 2016-12-15 18:57 UTC
**Operating system or device - Godot version:**
Godot 2.1, Windows 8.1

**Issue description** (what happened, and what was expected):
If you make a script on a node, save the script, then delete the node, and then make a new scene, add a node, and then add script, and select the path of the script you had saved, it says invalid path, file already exists, when obviously it should just add the script you want.  

I.E. It seems like you can't add a pre-existing script to a node.  'Add Script' should be changed to say 'Create New Script and Attach' or it should allow you to add a pre-existing script.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-12-15 20:11
I think this was already fixed in master, can someone confirm?

**Comment by RebelliousX** [comment] 2016-12-15 20:42
@bojidar-bg It is already fixed, https://github.com/godotengine/godot/issues/7016
@1000h Why using an old version? It is fixed in >2.1.1

**Comment by bojidar-bg** [comment] 2016-12-16 11:58
Yeah, right, duplicate of #7016, thanks @RebelliousX.

**Closed by bojidar-bg** 2016-12-16 11:58 UTC
