### ISSUE TITLE
[3.6 beta3] CPUParticles2D glitch/stutter with Local Coords off

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#80697] opened 2023-08-16 20:02 UTC
### Godot version

3.6 beta3

### System information

Windows 10

### Issue description

There is a coords/position problem with CPUPatricles2D with Local Coords off.

First problem: when you toggle the Local Coords in the editor, the node changes position for (1 frame I believe) before returning to its designated position.

Second problem: changing the position of the said CPUParticles2D node results in stutter of the already emitted sprites. The tricky bit is that it doesn't always happen, but it does happen regularly (and the problem is exacerbated in a real project).

### Steps to reproduce

See the MRP and click Local Coords on/off in the editor on the Fountain node.

### Minimal reproduction project

[CPUParticles2D_bug.zip](https://github.com/godotengine/godot/files/12363092/CPUParticles2D_bug.zip)

**Comment by Calinou** [comment] 2023-08-16 20:07
Can you reproduce this in 3.5.2? Does it only occur with physics interpolation enabled?

**Comment by oeleo1** [comment] 2023-08-16 20:13
> Can you reproduce this in 3.5.2? Does it only occur with physics interpolation enabled?

Sorry I didn't mention that this works fine in 3.6 beta2. I am not using physics interpolation - just tried a project on stock 3.6 beta3 and made an MRP. The only thing I added is the batching configuration we have in 3.6 beta2 and before. So this is a regression relative to the previous beta and lower versions.

**Comment by Calinou** [comment] 2023-08-16 20:36
cc @lawnjelly

**Comment by lawnjelly** [comment] 2023-08-17 06:11
> First problem: when you toggle the Local Coords in the editor, the node changes position for (1 frame I believe) before returning to its designated position.

I had also previously noticed the 1 frame glitch on changing from local to global coords in the inspector. However, when I checked (and I just confirmed) this also occurs in beta 2, and 3.5.2. I didn't investigate fully as I put it down to order of operations, and if it only occurs during switching modes (which is unlikely to occur in game) then it was not necessarily a problem.

If you instead toggle the local coords checkbox for `Trail_CPUParticles2D` in your MRP you will also see a glitch where the position is incorrect for 1 frame on changing.

> Second problem: changing the position of the said CPUParticles2D node results in stutter of the already emitted sprites. The tricky bit is that it doesn't always happen, but it does happen regularly (and the problem is exacerbated in a real project).

I'll see if I can reproduce this. I did try and ensure that `CPUParticle` behaviour without interpolation was the same before / after beta 3, but it is possible I missed something.

**Comment by lawnjelly** [comment] 2023-08-17 06:47
Ah, I have noticed one change which could possibly cause a difference in terms of order of operations.

Previous version altered (non interpolated) particles immediately on receiving `NOTIFICATION_TRANSFORM_CHANGED`, whereas this version only updates particles on `INTERNAL_PROCESS`. If there is an order of operations problem such that the particles should be moved _after_ internal process this could be the cause of a difference.

I'll put in some debug code to see if this could be happening. I haven't noticed a difference so far but it could be quite subtle visually. It would be quite easy to fix if so. :+1:

**Comment by lawnjelly** [comment] 2023-08-17 07:02
Ok I think I've got it - as I was thinking above, the `NOTIFICATION_TRANSFORM` is coming in _after_ the particles have been calculated on that frame, so there can be a delay of one frame before the particles catch up.

I'll fix this soon, may be able to fit in today, or after the weekend.

**Comment by akien-mga** [comment] 2023-09-18 15:02
Fixed by #80827.

**Closed by akien-mga** 2023-09-18 15:02 UTC
Labels: bug, topic:rendering, regression, topic:2d, topic:particles
