### ISSUE TITLE
AnimationPlayer animations ignoring certain tracks, ending at the wrong time

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#69543] opened 2022-12-03 20:04 UTC
### Godot version

EDIT: 4.0 dev

### System information

Windows 11

### Issue description

I just upgraded to latest and several of my working animations stopped working completely. 

The function calls made towards the end stopped working. Animations stopped transitioning. Some started transitioning later than the length of the animation, which doesn't make sense. 

It gave me quite the fright. I have come back to beta 6 and everything is back to normal. 

So there were some changes that occured in the middle that could be the culprit. 

Will upload MRP if the culprit is not identifiable. 

Could just be an issue with existing animations with certain parameters, that were affected. Not all animations were. 

### Steps to reproduce

See issue description. 

### Minimal reproduction project

Will upload if needed.

**Comment by TokageItLab** [comment] 2022-12-04 10:49
Perhaps this fix #69336 affected your project, but I can't determine what is causing you the problem.

MRP must be required, and if possible, if you send some video of the problem explanation it is helpful in determining the problem.

**Comment by LakshayaG73** [comment] 2022-12-05 10:35
It is very difficult to provide an MRP here, as I cannot submit my working production frames. 

Let me try. Else will try with a video first.

**Comment by LakshayaG73** [comment] 2022-12-05 10:39
Something interesting to mention is that I have faced the issue in https://github.com/godotengine/godot/pull/68992 without using animation tree. It depends on the animation length, and the number of floating points. 

I had opened an issue but I believe it was closed as I didn't upload an MRP. (Sorry).

**Comment by LakshayaG73** [comment] 2022-12-05 10:43
https://github.com/godotengine/godot/issues/66631

**Comment by LakshayaG73** [comment] 2022-12-05 10:47
I believe the same issue is happening here, where the methods are not being called when they should be **at the end of the animation** It has somehow gotten more pronounced. 

My game runs at 60 FPS, so if this is a frame pacing issue as mentioned by @Calinou, then it needs to be fixed on your end, as the eligible animation lengths shouldn't be dependent on the desired frame rate?

**Comment by TokageItLab** [comment] 2022-12-05 11:08
There are many cases where a bug cannot be investigated by video only. We do not want your resources, so please create an MRP with placeholder-like objects.

At any rate, your description lacks too much information. What type of track is being played, with what options and using what method? Also, if you open the tres file in a text editor, is the animation key value exactly the same or less than the Animation length?

**Comment by LakshayaG73** [comment] 2022-12-05 11:15
Apologies if it wasn't clear.

As mentioned, these are all **call method** tracks with keys **at the end of the animation**

The length of the animation in the .tres file seems to be correct. It is 0.208333 in the .tres file, and 0.2083 in the editor.

**Comment by TokageItLab** [comment] 2022-12-05 11:17
What value is the key position in tres? Is it a method track?

**Comment by LakshayaG73** [comment] 2022-12-05 11:18
tracks/5/type = "method"
tracks/5/imported = false
tracks/5/enabled = true
tracks/5/path = NodePath("PlayerStateMachine/Jump")
tracks/5/interp = 1
tracks/5/loop_wrap = true
tracks/5/keys = {
"times": PackedFloat32Array(0.208333),
"transitions": PackedFloat32Array(1),
"values": [{
"args": [],
"method": &"end"
}

**Comment by Calinou** [comment] 2022-12-05 11:25
Related to https://github.com/godotengine/godot/issues/69382.

This is a duplicate of another issue, but I can't find it right now.

**Comment by TokageItLab** [comment] 2022-12-05 11:27
Cannot be reproduced. I believe #68992 fixed it for that issue. There is an [MRP](https://github.com/eh-jogos/godot4_method_track_bugs) by @eh-jogos that has a script that fires a method at the end of a 0.208333 long animation using AnimationPlayer as well, but it works properly.

**Comment by LakshayaG73** [comment] 2022-12-05 11:50
resource_name = "jump_end"
length = 0.208333
step = 0.0416667
tracks/0/type = "value"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath(".:feet_position")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = {
"times": PackedFloat32Array(0.042, 0.204259),
"transitions": PackedFloat32Array(1, 1),
"update": 3,
"values": [80, 140]
}

Are you certain? Have you tested with this step value? 

I can say without a doubt that with absolutely no change in my code base, I see different behavior for this between beta 6 and 7. Not sure how this is not a regression to be honest...

**Comment by TokageItLab** [comment] 2022-12-05 11:59
> Are you certain? Perhaps with this step value? Running at 60 FPS?

Yes
```
[sub_resource type="Animation" id="Animation_74h6m"]
resource_name = "method_at_5"
length = 0.208333
step = 0.0416667
tracks/0/type = "value"
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/path = NodePath("Sprite2D:modulate")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/keys = {
"times": PackedFloat32Array(0, 0.208333),
"transitions": PackedFloat32Array(1, 1),
"update": 0,
"values": [Color(1, 1, 1, 1), Color(1, 0.85098, 0, 1)]
}
tracks/1/type = "method"
tracks/1/imported = false
tracks/1/enabled = true
tracks/1/path = NodePath(".")
tracks/1/interp = 1
tracks/1/loop_wrap = true
tracks/1/keys = {
"times": PackedFloat32Array(0.208333),
"transitions": PackedFloat32Array(1),
"values": [{
"args": [],
"method": &"print_i_worked"
}]
}
```

And still there is no MRP, so we cannot investigate. Possibly there is something strange about your environment, but if you are the only one who has that project, there is nothing we can do.

**Comment by LakshayaG73** [comment] 2022-12-05 12:09
I cannot repro it on an empty project on beta 7 either. 

There is some other nuance here that is present in my project. Perhaps there are too many tracks above and they are doing too much work. 

Will test and post.

**Comment by LakshayaG73** [comment] 2022-12-05 13:35
So, I can definitely repro this in **latest** master. I'm just checking to make sure whether this is true in beta 7 as well..

**Comment by LakshayaG73** [comment] 2022-12-05 14:13
So. I cannot repro this in beta 7. 

It is only in master, due to some commit made after the beta 7 fork. 

I have updated the issue version in the description. I incorrectly assumed that by picking master one day after the beta 7 fork, i'd be in the same place. I will send an MRP that repros in latest master soon.

**Comment by LakshayaG73** [comment] 2022-12-05 17:41
I'm not sure what's happening, I'm not able to repro this on a fresh project, but certain animations of mine are still breaking in master. 

For one of the breaking animations, I can see this when I try to call advance(0): 
![image](https://user-images.githubusercontent.com/1243371/205705118-2c3093f6-588b-429a-8327-e30b921a4c93.png)

For another, I notice that the length is extending over and above the 1 frame the animation is supposed to be: 
![image](https://user-images.githubusercontent.com/1243371/205705330-794b7cb3-6e85-4956-a7b7-fba2e1e83748.png)


Hope this helps...

**Comment by LakshayaG73** [comment] 2022-12-06 08:48
@TokageItLab i'm unable to reproduce this on new animations. it only affects certain existing animations. 

Does the above point help at all?

**Comment by TokageItLab** [comment] 2022-12-06 09:44
You cannot create a new MRP, which means that anyone cannot create a new MRP either. Thus, we cannot investigate the actual bug and can only say "Already fixed", at least for this issue.

There are project converters for 3.x and 4.0, but they are not yet complete. We were warned again and again to be careful about using them in real projects, especially since compatibility between Alpha and Beta is not guaranteed.

We really appreciate the feedback, but as long as we/you can't create MRP and we can't investigate bugs, we can't take care of them. Sorry.

**Closed by TokageItLab** 2022-12-06 09:44 UTC
Labels: bug, needs testing, topic:animation

**Comment by LakshayaG73** [comment] 2022-12-06 10:13
Please give me some more time to see if I can find a repro.

This behavior is a bit aggressive. 

There are clear issues with some animation player change.

Please reopen this.

**Comment by Zireael07** [comment] 2022-12-06 10:15
If you say there are issues, then please provide a project demonstrating them. Otherwise the team has to assume it was already fixed if you can't replicate it on new animations

**Comment by LakshayaG73** [comment] 2022-12-06 10:16
I will provide a project.

**Comment by TokageItLab** [comment] 2022-12-06 10:21
We can reopen this or start a new issue if you uproad MRP. Based on what little information you mention above, I'm guessing that the problem is probably related to loading some resource that has nothing to do with the animation process, but unless we can reproduce it, we never know.

**Comment by Zireael07** [comment] 2022-12-06 13:27
Open a separate issue and upload a MRP displaying the problem.
