### ISSUE TITLE
Plugin reload doesn't keeps variables

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5969] opened 2016-07-30 01:46 UTC
Tested on Godot 2.1 rc1, Windows 10 64 bits

I make a plugin which has a custom button in the spatial menu. However, as soon as I save my tool as I edit it, Godot reloads it (which is fine), but member variables get reset to their initial state rather than their previous state.
Because of this, my custom button is back to null once reloaded, the plugin is left completely unusable or in a wrong state, and I have to restart the editor as in 2.0.4 old days.

Here is a test project:
[PluginReload.zip](https://github.com/godotengine/godot/files/391639/PluginReload.zip)
It contains a plugin which edits a 3D Terrain custom node. 
- Click on the Terrain: observe a custom button appears in the menu.
- Make it so terrain_plugin.gd is reloaded by editing the script
- Click on another node, then the Terrain again: observe a Nil error in the console. The reference the plugin had on the button has been lost.

**Comment by vnen** [comment] 2016-07-30 02:08
It's the same as #5273. Looks like soft reloading is not working.

**Comment by Zylann** [comment] 2016-08-14 15:30
It still happens in 2.1 official, and because of #6056 scripts are often wrongly reloaded when I edit my terrain plugin, causing serious freezing (the whole thing reloads when I save a script) and lots of objects are leaking because the script lost all references:
![reload_leaks](https://cloud.githubusercontent.com/assets/1311555/17650085/891355b6-6244-11e6-984b-e48d2412010e.png)

**Comment by AfterRebelion** [comment] 2018-12-04 17:54
Fixed on Godot 2.1.5. Plugin reloads without errors, as expected.

_Also... with this version there seems to be a problem with the example plugin, because the custom button once loaded (when you select a terrain node), appears on all nodes independly of type._

**Comment by Zylann** [comment] 2018-12-04 18:17
@AfterRebelion I wouldn't worry too much about the plugin itself because I no longer maintain the Godot 2 version. I'll have to check if this issue is still valid in 3.0 and 3.1 though.

**Comment by KoBeWi** [comment] 2020-06-11 20:30
@Zylann So did you test it in 3.x? If it's still reproducible, please attach an up-to-date repro project.

**Comment by Zylann** [comment] 2020-06-11 20:48
@KoBeWi that has still been a problem, including 3.2.2 beta4. Member vars get reset to defaults on reload, so things leak and errors occur.

Example with a tool node:
[ToolReload.zip](https://github.com/godotengine/godot/files/4767240/ToolReload.zip)
That happens with any kind of script though (so resources or simple references too)

**Closed** 2022-05-17 13:09 UTC
Labels: bug, topic:editor, confirmed, topic:plugin
