### ISSUE TITLE
Font is rendered different in Label and RichtTextLabel

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#24570] opened 2018-12-23 18:12 UTC
**Godot version:**
v3.1.alpha.calinou.10e9221

**OS/device including version:**
Mac 10.14.1

**Issue description:**
Okay, in total this is a lot of stuff, I guess. But first things first.
<img width="564" alt="bildschirmfoto 2018-12-23 um 19 04 03" src="https://user-images.githubusercontent.com/4989757/50386392-8e86ff00-06e5-11e9-8c12-23d16884dd0c.png">

 The upper one is a Label and the lower one is a RichTextLabel. Both with the same Font but there looking different. Font size is the same and af far as I know every font related is the same (default values)

I really like the Line Skipped param in the Label, but that is not available in the RichTextLabel.
On the other side, I want to colorize words with [color=red]foo[/color] but bb_code is only possible on RichTextLabels.

Also, are there some plans to integrate some of those special Text effects like Game Maker Studio show [here](https://www.youtube.com/watch?v=3lnUyGqEU0w)?

Looks like this is more a feature request than a bug report.

**Comment by volzhs** [comment] 2018-12-23 19:30
would you attach the sample project reproduce it?

**Comment by letsgamedev** [comment] 2018-12-23 19:42
[GitHubExample_fonts.zip](https://github.com/godotengine/godot/files/2706254/GitHubExample_fonts.zip)

In this clean example, the font doesn't look so odd as in my screenshot above. But it looks different in detail.

**Comment by girng** [comment] 2018-12-23 20:49
odd. this is how it looks on w10, 64-bit, gtx 950
![image](https://user-images.githubusercontent.com/45474847/50387438-32a28300-06b1-11e9-8284-597c4b89448e.png)

**Comment by letsgamedev** [comment] 2018-12-24 09:41
The lower has a different white tone. Or is there a different default text color for RichTextLabels? But the more important: The text effects from the other tickets are great! Exactly what we looked for!

**Comment by girng** [comment] 2018-12-24 10:18
> The lower has a different white tone. Or is there a different default text color for RichTextLabels? But the more important: The text effects from the other tickets are great! Exactly what we looked for!

yeah seems like the label version (top) is a bit brighter. font settings are exactly the same on each... weird

**Comment by volzhs** [comment] 2018-12-26 14:38
it's because of default theme.
Default color for `RichTextLabel` is set here.
https://github.com/godotengine/godot/blob/10e9221c49eddc05cb36c0b582060cac9e4c8cef/scene/resources/default_theme/default_theme.cpp#L796
and the `control_font_color` value is here
https://github.com/godotengine/godot/blob/10e9221c49eddc05cb36c0b582060cac9e4c8cef/scene/resources/default_theme/default_theme.cpp#L180

seems not a bug but prefer settings for default theme.
you can see the same white text when setting Custom Colors > Default Color to white.

**Comment by girng** [comment] 2018-12-26 22:04
thanks @volzhs 

@letsgamedev looks like the letter spacing thing might still be a bug. but i don't have a mac and can't replicate that one on windows

**Comment by TheYokai** [comment] 2019-01-04 00:32
@letsgamedev 
There's a patch currently on the works (my own) that was linked above. ( #23658 ) It's still under development and consideration -- any feedback or visual resources for effects that might be desired would be useful for me to try to improve the api. Scaling (like in the video above) is not currently in my patch, for instance. I will look into adding features like that in the near future. Please provide any more examples of interesting text effects in my pull request. 

It is worth noting that some text rendering attributes in Label vs RichTextLabel are different, so things like wrapping and kerning can have some differences between the two classes. To be blunt, I think that the RichTextLabel class does need to have some work done to it in order to improve the rendering to be more consistent and cleaner. A general clean up of the class would be nice, but is not urgent.

**Comment by letsgamedev** [comment] 2019-01-12 08:59
Whats about the Lines Skipped feature like in the Label Element? Shall I make an extra Feature request for that. For me this is very handy to use in Textboxes.

**Comment by wagnerfs** [comment] 2019-01-19 08:16
I want to add to this actually instead of creating a new issue.
![image](https://user-images.githubusercontent.com/106078/51424168-72c22c00-1bb1-11e9-965d-23bb9b421271.png)
![image](https://user-images.githubusercontent.com/106078/51424191-c03e9900-1bb1-11e9-82ae-8dac67401b49.png)

I've tweaked around with all values but no luck, on the editor it's all good, when it's running, the spacing gets all bananas like that.
I can provite my TTF pixel font for testing but seems like it happens with all fonts?

**Comment by txigreman** [comment] 2019-03-28 09:45
I've uploaded a sample project to bug report [#25127](https://github.com/godotengine/godot/issues/25127) where the spacing issue can be seen clearly.

**Comment by txigreman** [comment] 2019-03-28 10:00
In case it helps: I noticed that, in my attached demo project, Label and RichTextLabel behave the same if font size is set to 7:

![image](https://user-images.githubusercontent.com/778778/55147865-7b9e2380-5147-11e9-9080-e00b433db385.png)

If I set the font size to any smaller number the mess begins:

![image](https://user-images.githubusercontent.com/778778/55147969-a5efe100-5147-11e9-8ce0-65eeead66659.png)

With a bigger size they do not look as bad as before, but they still do not look the same:

![image](https://user-images.githubusercontent.com/778778/55147996-b607c080-5147-11e9-9080-0721e82b8234.png)

**Comment by wagnerfs** [comment] 2019-07-23 04:12
Just curious about this one still, I had to stop my game since I need bbcode going and the resolution is too small and make this bug a hell to work with.
I suppose I could also fool around with the RichTextLabel implementation to see if I can get a fix for it, just asking to check if someone else already gave it some thoughts.

**Comment by Eoin-ONeill-Yokai** [comment] 2019-08-12 22:25
I just got back from an overseas trip to the Krita sprint in the Netherlands. While I prepare my pr with necessary revisions, I will promise to investigate this a little bit. 

My guess would be that the font renderer "instance" is configured slightly differently between the two classes. I can't make any promises that I'll find the specific issue, but I'll try to see if there's anything that stands out.

**Comment by volzhs** [comment] 2019-08-13 02:29
I tested this with 3.1.2-devel a5082c010

![Peek 2019-08-13 11-28](https://user-images.githubusercontent.com/8281454/62910980-9a7f1880-bdbd-11e9-94f9-a43ac839a6ee.gif)

seems fixed...

**Comment by txigreman** [comment] 2019-08-13 11:51
MVP

Un saludo,
Iván Arias

________________________________

**Comment by txigreman** [comment] 2019-08-20 16:49
I've tried it out in the nighly build from [hugo.pro](https://hugo.pro/projects/godot-builds/) and the problem still persists.

![bug](https://user-images.githubusercontent.com/778778/63366980-27584200-c37b-11e9-8717-accc5106a7cf.gif)

Both components behave the same in the editor, but they do behave different when running the project.

**Comment by wagnerfs** [comment] 2019-09-15 02:19
Same here, still goes crazy while running, even a working font size will freak out once you dynamically (or set a custom size even) resize the window.
What's intriguing is that it used to work normally on 3.0 and even 2.1.5.

**Comment by Calinou** [comment] 2019-09-15 15:01
> Same here, still goes crazy while running, even a working font size will freak out once you dynamically (or set a custom size even) resize the window.
What's intriguing is that it used to work normally on 3.0 and even 2.1.5.

This could be due to font oversampling, which is enabled by default since 3.1. Does disabling **Rendering > Quality > Dynamic Fonts > Use Oversampling** solve the issue?

**Comment by wagnerfs** [comment] 2019-09-15 20:16
> 
> 
> > Same here, still goes crazy while running, even a working font size will freak out once you dynamically (or set a custom size even) resize the window.
> > What's intriguing is that it used to work normally on 3.0 and even 2.1.5.
> 
> This could be due to font oversampling, which is enabled by default since 3.1. Does disabling **Rendering > Quality > Dynamic Fonts > Use Oversampling** solve the issue?

Yeah, it fixed the issue completely, so it was probably that all along, thanks a bunch, I can finally resume the game!

**Comment by Calinou** [comment] 2019-09-15 21:09
I believe the bug related to font oversampling is tracked in #22580.

**Comment by Calinou** [comment] 2019-12-13 15:31
I'll close this in favor of #22580, as it tracks the remaining issue with RichTextLabel sizing when font oversampling is enabled.

**Closed by Calinou** 2019-12-13 15:31 UTC
Labels: bug, confirmed, discussion, topic:core
