### ISSUE TITLE
Connect Signals will create C# method repeatedly

### ISSUE THREAD

**Issue by FcAYH** [godotengine/godot#75524] opened 2023-03-31 07:59 UTC
### Godot version

Godot Engine - .Net 4.0.1

### System information

Windows11, i7-1280p

### Issue description

When I have written a method in a C# code file and want to connect it to a certain signal. I found that the Godot engine would help me create another method from a code file. Like this:
My code:
```csharp
// Main.cs
using Godot;

public partial class Main : Node
{
	public void GameOver()
	{
		GD.Print("GameOver!");
		GetNode<Timer>("MobTimer").Stop();
		GetNode<Timer>("ScoreTimer").Stop();
	}
}
```
```csharp
// Player.cs
using Godot;

public partial class Player : Area2D
{
	[Signal]
	public delegate void HitEventHandler();
}
```
Now, I want to connect "GameOver" method to the "Hit" signal defined in Player.cs. But after I do as described in the figure below, my "Main.cs" file was automatically modified.
![image](https://user-images.githubusercontent.com/53511336/229054787-df2b8788-cab7-4781-a169-827e79fd7ed5.png)

```csharp
// Main.cs
using Godot;

public partial class Main : Node
{
	public void GameOver()
	{
		GD.Print("GameOver!");
		GetNode<Timer>("MobTimer").Stop();
		GetNode<Timer>("ScoreTimer").Stop();
	}
}

private void GameOver()
{
	// Replace with function body.
}

```
Look at the last four lines above. This seems silly, first of all, I already have the "GameOver" method in my code, so there is no reason to generate another method with the same name. Second, the method should be defined in the class, but this auto-generated method is outside the class.

### Steps to reproduce

Steps to Reproduce
1.  create a new empty project.
![image](https://user-images.githubusercontent.com/53511336/229058992-57176013-fddd-41f5-a850-28659b104851.png)
2. Just choose a 2D Scene Node and named it "Main"
3. Attached a C# script on the Main node.
![image](https://user-images.githubusercontent.com/53511336/229059552-062f62c6-c05f-45bb-875e-299351b12523.png)
4. modified the script as follows
```csharp
using Godot;
using System;

public partial class Main : Node2D
{
	[Signal]
	public delegate void JustAEventHandler();
	
	public void MethodToDueEvent()
	{
		
	}
}
```
5. connect the "MethodToDueEvent" method to "JustA" signal
![image](https://user-images.githubusercontent.com/53511336/229060767-3e0132e7-42b5-4fa7-8fec-34bd5dc5f85c.png)
6. now you can see the bug 
![image](https://user-images.githubusercontent.com/53511336/229060856-38f2b1ab-379c-4323-8110-046bc22aae6e.png)

### Minimal reproduction project

N/A

**Comment by FcAYH** [comment] 2023-03-31 08:08
Just now I found that this bug doesn't trigger when I'm using an external IDE like VS code. It seems that this bug only occurs in the editor integrated into Godot's internal editor

**Comment by AThousandShips** [comment] 2023-03-31 08:22
This seems to be because the method to find an internal function in C# is not implemented in the engine, so it won't be able to find it when using internal editor

**Comment by AThousandShips** [comment] 2023-03-31 08:47
Duplicate of #31817

**Comment by RedworkDE** [comment] 2023-03-31 08:51
Duplicate of https://github.com/godotengine/godot/issues/75391
Tho this issue now has more info about the whole thing, so I would just close the other in favor of this.

**Comment by akien-mga** [comment] 2023-11-10 09:06
- Duplicate of #18721

**Closed by akien-mga** 2023-11-10 09:06 UTC
Labels: bug, topic:editor, usability, topic:dotnet
