### ISSUE TITLE
GDScript 2.0: @export_range won't recognize negative numbers

### ISSUE THREAD

**Issue by Firemanarg** [godotengine/godot#69575] opened 2022-12-04 17:34 UTC
### Godot version

4.0-beta7

### System information

Windows 10

### Issue description

@export_range is throwing out an error when I try to put negative numbers.
I've checked with different values, and the error only appear with negative numbers (int and float):

![image](https://user-images.githubusercontent.com/35619327/205506193-b704d1c9-f5a3-4b65-bde9-031fc891d762.png)

### Steps to reproduce

1. Declare a variable using @export_range
2. Put any negative number inside the @export_range arguments

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment] 2022-12-04 18:09
Duplicate of #41183

**Closed** 2022-12-04 18:19 UTC
