### ISSUE TITLE
BMPFont Import

### ISSUE THREAD

**Issue by sanja-sa** [godotengine/godot#7248] opened 2016-12-05 11:41 UTC
**Operating system or device - Godot version:**
Win10 (64) Godot 2.1.1

**Issue description** (what happened, and what was expected):
When Font import from BMPFont its create absolute path to png file:
![clipboard01](https://cloud.githubusercontent.com/assets/6029207/20883505/382fd72e-baef-11e6-9261-ef040c15cfcd.png)

Solution is: Open Editor -> Edit Font (in poroperty font) -> set save path with .tres 
![clipboard01](https://cloud.githubusercontent.com/assets/6029207/20883606/cb678c76-baef-11e6-828b-f6cd1678bac0.png)
and then correct path in .tres file of Font to relative path (resource path) of png:
![clipboard01](https://cloud.githubusercontent.com/assets/6029207/20883746/661fe61e-baf0-11e6-89c2-b1bf3926ab5c.png)

**Steps to reproduce:**
Import BMP font

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment] 2016-12-05 19:41
I guess it's BMFont, not BM**P**Font.
http://www.angelcode.com/products/bmfont/
just make for sure...

**Comment by RayKoopa** [comment] 2016-12-19 09:38
Probably related: https://github.com/godotengine/godot/issues/4408

**Comment by akien-mga** [comment] 2017-01-02 11:07
Closing as duplicate of #7309 as it's more specific.

**Closed by akien-mga** 2017-01-02 11:07 UTC
Labels: bug, junior job, topic:editor

**Comment by tapir** [comment] 2017-01-13 06:45
How do I create a *.tres file for a font? I'm importin a *.fnt file created with ShoeBox and godot only creates another *.fnt and *.png file when importing. No *.tres file. Changing the path in binary fnt file via hex editor doesn't work.
