### ISSUE TITLE
Weird errors around List allocations when exporting Server build via headless

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#37082] opened 2020-03-16 05:22 UTC
**Godot version:**
Godot headless 3.2.1

**OS/device including version:**
Ubuntu Bionic container image ([summerplay/godot:3.2.1-headless](https://hub.docker.com/repository/docker/summerplay/godot))

**Issue description:**
I am exporting a Godot server build from within a docker container via Godot headless:
```
# In Dockerfile
RUN godot-headless --export-debug "Server" build/instance.pck 
```
The build ends up working fine, however during the build, there are some weird errors that occur after the savepack step:

```
savepack: end
reimport: end
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

It looks to me like something in the ClassDB isn't cleaned up on exit as this error seems to occur immediately before the command exits.

**Steps to reproduce:**
Create a dockerfile that extends from the base image referenced above and exports a server buiild. Build the docker container. Watch the output.

**Comment by Calinou** [comment] 2020-03-16 08:40
Do these occur when exporting an empty project?

**Comment by cdreier** [comment] 2020-04-30 20:46
Hi, i just ran in the same problem - i am using `Godot_v3.2.1-stable_linux_headless.64` on fedora

exporting an empty project with an empty root scene throws me this error

```
./Godot_v3.2.1-stable_linux_headless.64 runner/project.godot --export "Linux/X11" ./test

Godot Engine v3.2.1.stable.official - https://godotengine.org
 
savepack: begin: Packe steps: 102
	savepack: step 2: Speichere Datei: res://default_env.tres
	savepack: step 35: Speichere Datei: res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
	savepack: step 35: Speichere Datei: res://icon.png.import
	savepack: step 68: Speichere Datei: res://root.tscn
	savepack: step 102: Speichere Datei: res://icon.png
	savepack: step 102: Speichere Datei: res://project.binary
savepack: end
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```

any workarounds for this?

**Comment by isibley765** [comment] 2020-06-02 04:38
Caught myself right before making another issue for this.
It's late, so I'm going to just copy it over -- apologies for the length, but I tried to do a sizable amount of user diving first before coming here.

**Godot version:**

3.2.1 (trying to export via linux command line on the [headless linux 64 build](https://godotengine.org/download/server))

**OS/device including version:**

Personally using Ubuntu 18.04 to debug locally, but originally a GitHub Action running off of https://github.com/aBARICHELLO/godot-ci's setup
(i.e. whatever GitHub Actions use for "ubuntu-latest" currently -- [looks like also 18.04](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners))

Also a Bash window in Windows -- that union's still a mess, but besides what seems like Windows&Linux clashes on file permissions symptoms are otherwise the same
<img width="398" alt="godot_export_windows10_memory_leak" src="https://user-images.githubusercontent.com/19479276/83477735-f48ebe80-a461-11ea-9ab2-4ffc8f0bff87.png">


**Issue description:**

Running this on a linux headless `godot --export` seems to always result in the below issue, pictured below (and above). Export type -- linux, windows, mac, or html -- doesn't matter, error is consistent.

```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```
![godot_export_memory_leak](https://user-images.githubusercontent.com/19479276/83476999-19823200-a460-11ea-992b-e641464971cf.png)

Exporting from the Godot GUI on Windows 10 gives me no issues.

***Some context that may or may not help:***
I thought at first this was related to my use in scene of a StaticBody's CollisionShape child with a ConcavePolygonShape, as the code in the `Spatial.tscn` file originally contained a `PoolVector3Array` that I thought was matching the `At: core/pool_vector.cpp:69.` part of the error.
I have since changed the StaticBody's CollisionShape to use just a `BoxShape`, with no `PoolVector` reference in the rest of my project as best I can tell, but the error remains unchanged. My Windows photo link above actually was ran off of this mentioned change.

**Steps to reproduce:**
1. Get the Godot headless & templates for 3.2.1 set up & ready to use, and unzip the attachment below somewhere
2. Check `auto-export.sh` for a bash script on the template setup steps I made to get this working for new linux/ubuntu environments (i.e. GitHub Actions docker shell).
3. I put the godot executable in my path manually, `/usr/local/bin/godot`, after grabbing the [headless godot 64 executable from your site](https://godotengine.org/download/server)
4. The `linux_automated_exports.cfg` can be copied to `export_presets.cfg` for your use, to see what I was working with.

5. Once the templates & godot executable are ready to go, just run these commands in the unzipped folder:
```
mkdir -p build/linux/
sudo godot -v --export "Linux/X11" ./build/linux/test-project.x86_64
```
The rest should match the picture(s)

**Minimal reproduction project:**

[GodotDevelopment-3d-tutorial.zip](https://github.com/godotengine/godot/files/4714631/GodotDevelopment-3d-tutorial.zip)

**Comment by akien-mga** [comment] 2022-03-26 18:58
I've definitely seen this in the past, but I tested now with 3.4.4-stable and I can't reproduce the issue.
I also tested in 4.0 alpha 1 (old alpha just because I had templates installed for it and not for newer alphas) and I don't see the List errors either.

I'll close this as fixed, but please comment if you can still reproduce it so we reopen it.

**Closed by akien-mga** 2022-03-26 18:58 UTC
Labels: bug, topic:porting, confirmed
