### ISSUE TITLE
Nested 2D Raycasts not being set correctly

### ISSUE THREAD

**Issue by SageDest** [godotengine/godot#74318] opened 2023-03-03 20:04 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Forward+

### Issue description

I have a Player node in a world, with a few raycasts, one aiming down for floor collision, and one on the sides for wall collisions from following an online tutorial. It was for the previous version of Godot 3, so I tried recreating it for 4.0, but this seems to be the only issue I've had with it. When grouping the raycasts with a node, the groups don't follow the proper origin point. I wouldn't see why that should make a difference, when they are all part of the player node. 

### Steps to reproduce

When opening the project, you can see a basic group of tiles, with the player in the middle. It has a 3 raycasts, two left and one down. The left raycast that isn't grouped by a node is in the correct position, while the one that is grouped by two nodes is not. The bottom cast, that only is grouped by one node is in the correct position. I've included screenshots for those that can't see the project. 
![bug1](https://user-images.githubusercontent.com/126913703/222815856-7d56c2e2-5993-4a2a-a21a-7a9a407e016e.jpg)
![bug2](https://user-images.githubusercontent.com/126913703/222815859-f6c61c5a-04c4-4ce8-bb0f-e64dd08affc9.jpg)
![bug3](https://user-images.githubusercontent.com/126913703/222815860-17ef3ea1-894d-4800-a303-4ab2ede90010.jpg)
. 

### Minimal reproduction project

[Bug Test.zip](https://github.com/godotengine/godot/files/10885668/Bug.Test.zip)

**Comment by AThousandShips** [comment] 2023-03-08 20:08
Those are `Node` you need to have `Node2D`, or transform isn't used

**Comment by AThousandShips** [comment] 2023-03-08 20:08
Duplicate of #74430

**Comment by AThousandShips** [comment] 2023-03-08 20:24
See #74430

**Closed** 2023-03-09 11:05 UTC
