### ISSUE TITLE
Placing groups of tiles over existing tiles results in half the tiles not replaced

### ISSUE THREAD

**Issue by es1024** [godotengine/godot#65965] opened 2022-09-17 05:45 UTC
### Godot version

4.0.beta1

### System information

Ubuntu 20.04

### Issue description

When placing a set of tiles grouped together over existing tiles, roughly half the tiles are not replaced.

Before placing:
![Screenshot from 2022-09-17 14-40-18](https://user-images.githubusercontent.com/6742815/190842418-3677f778-feb5-448e-89de-89527cd2595b.png)

After placing:
![Screenshot from 2022-09-17 14-49-30](https://user-images.githubusercontent.com/6742815/190842593-8e9fa840-c64c-4145-94f5-5921c76183fb.png)

The pattern of missing tiles is consistent.

### Steps to reproduce

1. Create a project with a TileMap node.
2. Add a TileSet and create an atlas with an image.
3. Group together a set of tiles.
4. Place a rectangle of tiles larger than the group.
5. Place the group of tiles on top of the rectangle.

### Minimal reproduction project

[tile-test.zip](https://github.com/godotengine/godot/files/9591030/tile-test.zip)

**Comment by groud** [comment] 2023-06-20 08:20
I checked the test project, and this is not a bug. You mistaken groups of tiles and "big tiles". Big tiles only take one cell on TileMap, unlike patterns. So what happens is that parts of you big tile is covered by smaller blue tiles because those are not replaced by placing the big tile on a single cell.

Closing as this is expected behavior.

**Closed by groud** 2023-06-20 08:20 UTC
Labels: bug, topic:editor
