### ISSUE TITLE
"get_shader_uniform()" returns null, rather than default values, if uniforms have not been set or reverted

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#64832] opened 2022-08-24 13:04 UTC
### Godot version

4.0.alpha14

### System information

Windows 10, Core i7 5820k, GeForce 980TI

### Issue description

Requesting uniform values with "get_shader_uniform()" will return null values if the uniforms have not been set or reverted rather than default values. This appears to be an issue for Godot internally as well as when you create a new shader material the inspector will also get the null values for the uniforms rather than the defaults from the shader.

![image](https://user-images.githubusercontent.com/4955051/186429061-edb6ec59-68f4-4c59-b3c1-105d2df55d8e.png)
EDIT: updated screenshot as I had misdrawn my line

### Steps to reproduce

Assign a shader material and a custom shader to a mesh and observe how the default values from the shader are not showing up in the inspector.

OR

Open the attached project and open the test scene and look at the assigned material. You can also click the "Get Uniforms" checkbox I set up to see it returning null when you run "get_shader_uniform()" on the uniforms.

### Minimal reproduction project

[shader_uniform_issue.zip](https://github.com/godotengine/godot/files/9416259/shader_uniform_issue.zip)

**Comment by Calinou** [comment] 2022-08-24 15:30
Can you reproduce this in previous 4.0 alphas?

**Comment by Arnklit** [comment] 2022-08-24 16:44
@Calinou tested on Alpha 7 and Alpha 1 and both had the same issue.

**Comment by bitsawer** [comment] 2023-06-01 11:22
This issue has to separate things:

1) `ShaderMaterial.get_shader_parameter()` returns null if the value has not been set using the inspector UI or programmatically. This seems to be by design and if you want to get the actual default value specified in the shader code you'll have to use `shader_material.shader.get_shader_uniform_list(`) or the RenderingServer API which should give the shader code defaults, not the ones stored in a ShaderMaterial overrides. So not really a bug, but this could be documented better.

2) Shader code initial default values not being shown in the inspector UI. This is a bug, should be fixed by https://github.com/godotengine/godot/pull/74937

**Closed** 2023-06-09 09:09 UTC
Labels: bug, regression, topic:shaders
