### ISSUE TITLE
Setting Canvas as Background in WorldEnvironment messes up editor UI

### ISSUE THREAD

**Issue by tlobig** [godotengine/godot#68919] opened 2022-11-20 14:18 UTC
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Windows 10, Vulkan, NVIDIA RTX 3080 Laptop (NVIDIA 516.94)

### Issue description

Adding WorldEnvironment to a 3d Scene, setting Background to Canvas -> all dropdown menus and popups in the editor draw as gray rectangle as long as the scene is shown

![grafik](https://user-images.githubusercontent.com/10432347/202906496-68443d54-82c1-4821-865a-6294cbfe0791.png)

can be reverse by (blindly) selecting a different kind of background or deleting the WorldEnvironment

### Steps to reproduce

- New Project
- 3D Scene
- Add Node -> World Environment
- Create New Environment in Inspector tab
- Click on the new environment and navigate to Background
- Select "Canvas" as background

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2022-11-20 15:00
dupe of... a ton of others, fixed already by #68805

**Comment by akien-mga** [comment] 2022-11-20 15:16
Duplicate of #52467.

**Closed by akien-mga** 2022-11-20 15:16 UTC
