### ISSUE TITLE
ButtonGroup not operating correctly

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#19643] opened 2018-06-19 10:15 UTC
**Godot version:**
Godot_v3.0.2-stable.mono.official

**OS/device including version:**
Windows 10 Pro version 1709 build 16299.492

**Issue description:**
Added some checkboxes to a GridContainer and also to a ButtonGroup, and connected the Pressed signal of each button to a function. Calling GetPressedButton() from the function seems to show incorrect results. I gave each button a name 'button_0', 'button_1' etc. but when clicking each in turn, GetPressedButton() returns out of order results.  As seen below.

```
running cmdline: "C:\xxx\Godot_v3.0.2-stable_mono_win64\Godot_v3.0.2-stable_mono_win64.exe" "--path" "C:/Users/xxx/Documents/TestButtonGroup" "--remote-debug" "127.0.0.1:65349" "--allow_focus_steal_pid" "47116" "--position" "768,420"
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
created button with hash 1128703675
button 1128703675 given name button_0
created button with hash -1454700503
button -1454700503 given name button_1
created button with hash 446762873
button 446762873 given name button_2
created button with hash 1960949332
button 1960949332 given name button_3
created button with hash 194072721
button 194072721 given name button_4
created button with hash 1708259180
button 1708259180 given name button_5
created button with hash -58617431
button -58617431 given name button_6
created button with hash 1455569028
button 1455569028 given name button_7
created button with hash 75969334
button 75969334 given name button_8
created button with hash -1064279968
button -1064279968 given name button_9
button button_0 with hash 1128703675 pressed
button button_0 with hash 1128703675 pressed
button button_2 with hash 446762873 pressed
button button_2 with hash 446762873 pressed
button button_3 with hash 1960949332 pressed
button button_5 with hash 1708259180 pressed
button button_5 with hash 1708259180 pressed
button button_6 with hash -58617431 pressed
button button_8 with hash 75969334 pressed
button button_9 with hash -1064279968 pressed
```

**Steps to reproduce:**
Build and run the supplied project, click each button in turn & observe the output window.

**Minimal reproduction project:**
[TestButtonGroup.zip](https://github.com/godotengine/godot/files/2114796/TestButtonGroup.zip)

**Comment by Xrayez** [comment] 2018-12-08 22:08
Trying to retrieve pressed button with `get_pressed_button()` with no success either, returns `null` in GDScript (each button is set to a toggle mode and assigned to the same group).

The documentation is also misleading it seams, the buttons mustn't have hierarchy established in the scene tree in order for them to act like radio buttons, but that also doesn't fix the problem either way.

**Comment by tom-jk** [comment] 2020-07-26 15:26
Testing MRP with non-mono Godot (converted to gdscript: [19643_gdscript.zip](https://github.com/godotengine/godot/files/4977844/19643_gdscript.zip))

Can reproduce with 3.0.2.stable, 3.0.6.stable.
Can't reproduce with 3.1.stable, 3.2.3.beta1.

Pre-3.1, get_pressed_button() would return null when the selected button was pressed - that is also fixed.

Issue appears to be resolved.

**Comment by akien-mga** [comment] 2020-07-26 15:31
Thanks for testing!

**Closed by akien-mga** 2020-07-26 15:31 UTC
Labels: bug, topic:gui
