### ISSUE TITLE
Threads dont work with optional arguments

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#38042] opened 2020-04-20 12:27 UTC
**Godot version:**
v3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
Starting a new thread on a function with optional arguments doesn't work as expected.
Both calling the function normally and calling the function by emitting a signal works perfectly as expected.

**Minimal reproduction project:**
```gdscript
extends Node2D

var thread : Thread

signal test_signal

func _ready():
	thread = Thread.new()
	thread.start(self, "do_stuff")

	connect("test_signal", self, "do_stuff")
	emit_signal("test_signal")
	
	do_stuff()

func do_stuff(optional_var : int = 0):
	print("HURRAY!")

func _exit_tree():
	thread.wait_to_finish()
```

Gives following error when running:
```
E 0:00:00.812   _start_func: Could not call function 'do_stuff' to start thread 13480: Invalid Argument #0.
  <C++ Error>   Method failed.
  <C++ Source>  core/bind/core_bind.cpp:2694 @ _start_func()
```

Evidently running the start thread command with an actual integer as argument does work.

**Comment by Calinou** [comment] 2020-04-20 13:54
I think this is because the `userdata` passed to `Thread.start()` must not be `null`. This issue is probably a duplicate of another one.

**Comment by Faymoon** [comment] 2020-04-20 15:35
I think it may be because on this line we can see that the arg number is hard coded : 
https://github.com/godotengine/godot/blob/master/core/bind/core_bind.cpp#L2104

**Comment by Faymoon** [comment] 2020-04-21 10:10
I tried to replace the 1 with a zero on the line i linked before and it worked

**Comment by Faymoon** [comment] 2020-04-21 10:20
Threads don't really works as signals, signals can accept multiples parameters but thread just let you give one `userdata`, i think it's the reason why it doesn't work here. I'm working on a real fix. (The fix just before prevent all threads to receive userdata.

**Closed** 2021-07-13 09:39 UTC
Labels: bug, topic:core
