### ISSUE TITLE
Error when initializing an exported array of Custom sub-Resources inside a custom Resource

### ISSUE THREAD

**Issue by jayypluss** [godotengine/godot#75204] opened 2023-03-22 02:09 UTC
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

My code in short is

```
extends Resource
class_name Blueprint

@export var recipe: Array[BlueprintRecipeItem] = []

func _init(p_recipe = []):
    recipe = p_recipe
```

but with this I get an error:

`Trying to assign an array of type "Array" to a variable of type "Array[BlueprintRecipeItem]".`

I also tried `[null]` instead of `[]`

`BlueprintRecipeItem` is also a custom (sub-)Resource class:

```
extends Resource
class_name BlueprintRecipeItem

@export var name:= ''
@export var quantity:= 0

func _init(p_name = '',
	p_quantity = 0):
		name = p_name
		quantity = p_quantity
```

### Steps to reproduce

Create a script with a custom Resource class that has an array of a custom sub-Resource.

### Minimal reproduction project

N/A

**Comment by alfredbaudisch** [comment] 2023-03-22 07:34
Might be related to https://github.com/godotengine/godot/issues/74164. 

If you restart the project, is the error gone?

**Comment by jayypluss** [comment] 2023-03-22 11:22
Yes. It only shows when it enters the tree.

**Comment by YuriSizov** [comment] 2023-06-23 18:35
This is a duplicate of https://github.com/godotengine/godot/issues/72620. The behavior is technically expected, since converting the `[]` literal to a typed array is an ambiguous behavior. You should be able to drop the `= []` part without any downside.

There is also a chance that in future you'd be able to use a typed constructor, e.g. `Array[BlueprintRecipeItem]()`, see https://github.com/godotengine/godot/pull/71336.

**Closed by YuriSizov** 2023-06-23 18:35 UTC
Labels: bug, topic:gdscript
