### ISSUE TITLE
Global script classes not recognized properly after defining them, or when `.godot/global_script_class_cache.cfg` was just generated or is out of sync

### ISSUE THREAD

**Issue by mrpedrobraga** [godotengine/godot#72989] opened 2023-02-09 20:52 UTC
### Godot version

4.0.dev

### System information

Pop! OS

### Issue description

I came here to report what seems to have been reported in #72219, yet when I started making the minimal reproduction project in RC1 it seems to have gotten worse yet.

I have created a simple hierarchy here:
![image](https://user-images.githubusercontent.com/79771992/217931820-e004a8c1-ea6b-4fcd-b91b-f9faf6a31195.png)

`Vehicle` extends `Resoure`, `Car` extends `Vehicle`.

I then have a node `Garage` which exports a variable of type `Vehicle`.

Now, as I try to create a new `Car` resource using the dropdown, it displays "Resource" instead of "Car."
![image](https://user-images.githubusercontent.com/79771992/217933836-9ce3969e-9175-4449-a7fb-d2636c03241c.png)

And then, this hilarious error.
![image](https://user-images.githubusercontent.com/79771992/217934343-d2a0347b-0faf-4886-ba57-7f83ea23d2ca.png)

When dragging a resource from the filesystem it won't let me put it there either.
That's the case for `Vehicle` resources, too, not just `Car`.

![image](https://user-images.githubusercontent.com/79771992/217935042-e49b901f-17cc-4967-9670-098aaa471974.png)

I use Resources A LOT in my workflow (I'd really like to put my Nissan Toyota in my garage, that is), and I'd think I've have found more talk about this.

### Steps to reproduce

Create a class `A` that extends `Resource`.
Create a script that exports a variable of type `A`.
Try to assigning an object of type `A` to the variable. (You can't)

### Minimal reproduction project

[resource_export_issue.zip](https://github.com/godotengine/godot/files/10701397/resource_export_issue.zip)

**Comment by Flavelius** [comment] 2023-02-10 06:41
This only happens when the scripts have the @tool annotation, so it's an issue with that part of the editor logic.
Without it no errors are printed and assignments work as expected.

As for your case, it's not necessary to give them the tool annotation for inheritance or editor assignments to work. If there aren't other usages for it, you can get rid of it while this is not fixed.

**Comment by mrpedrobraga** [comment] 2023-02-10 06:52
I guess this explains how it hasn't been caught. Unfortunately, that's not my real use case, the real one does need `@tool`.

I'll update the original post soon.

**Comment by hoklai1997** [comment] 2023-02-14 03:36
Commenting to +1 the issue. I use custom resources heavily for procedural generation (to store various map operation objects and region operation objects), and use tool scripts to quickly be able to see the outcomes of parameter tuning. This worked into beta 13, however, afterwards my test environments that leverage the tool scripts no longer work.

**Comment by MackyK** [comment] 2023-02-15 02:28
I'm able to reproduce this bug without @tool annotation.

**Comment by akien-mga** [comment] 2023-02-17 09:44
So I tested @mrpedrobraga's MRP, the issue is only reproducible when opening it for the first time. That's because the `.godot/global_script_class_cache.cfg` isn't present in the MRP, and gets generated when the editor is opened. Then the editor doesn't seem to fully update its knowledge of which global script classes exist until it's restarted.

You might therefore experience similar issues when you've just declared a new global class and try to use it. Oftentimes you'll have to restart the editor to make sure everything picks it up.

Potential ways this issue (may be two different bugs) can happen:
- `.godot` folder, and thus `.godot/global_script_class_cache.cfg` is missing. On first editor run, those files get generated, but the editor needs a restart before it picks up all global script classes properly.
- `.godot` folder exists, but `.godot/global_script_class_cache.cfg` is outdated (generated by an older Godot version and somehow in a broken state), or missing, but other files are present. This seems to sometimes lead to not updating the file properly when opening Godot, and the file may have just `list=[]` or an incomplete list of the script classes. (This might be a different bug - at least that's what seems to happen in #73165, and I can trigger this in the MRP here when opening the editor once, restarting (then everything works), closing, deleting only `.godot/global_script_class_cache.cfg` and reopening the editor). I suspect other `.godot` files like `uid_cache.bin` might be involved in this state desync.
- `.godot` folder exists, `.godot/global_script_class_cache.cfg` is up to date and everything works. Then you create a new `class_name`, try to use it, and run into this issue again. You need to restart the editor so it picks it up properly. (That's been the case for years for many things in Godot, should hopefully be improved in the future.)

**Comment by dalexeev** [comment] 2023-02-17 17:10
> I can't make this work after first launch at all. Re-saving script, which normally should help, does nothing.

Does it depend on the `@tool` annotation?

**Comment by mrpedrobraga** [comment] 2023-02-17 17:46
I tested again (and on a different machine, too).

Works like this: I delete the .godot folder, can't assign resources at all. It's indifferent to `@tool` scripts.

Assignment doesn't work with Drag and Drop, Load, Quick Load, PackedScene instantiation (in the editor) or creation of new resources.

Save and Quit,  it all works flawlessly. In fact, if a Resource errors saying it can't be assigned, when you restart, it actually *did* get assigned.

**Closed** 2023-02-18 09:40 UTC
Labels: bug, topic:gdscript, topic:editor
