### ISSUE TITLE
Godot font have a bug (The font is corrupted)

### ISSUE THREAD

**Issue by Bloonear** [godotengine/godot#88143] opened 2024-02-09 15:04 UTC
### Tested versions

+ This bug is present in the Godot_v4.2.1-stable_win64
- It's not the case in Godot_v3.5.3-stable_win64

### System information

Windows 10 - Godot.v4.2.1.stable - Vulkan

### Issue description

The font of the client gets corrupted when opened and it is didn't matter if it is first time or not (on version 4.2.1)
![n](https://github.com/godotengine/godot/assets/159538595/d946c076-d102-4dc7-8dfb-6ff2a591a178)
But it is ok in version 3.5.3
![y](https://github.com/godotengine/godot/assets/159538595/89da36d4-814e-4014-a45a-64405c1d5c06)

### Steps to reproduce

1) open the client
2) The font is buggy and corrupted
(It doesn't matter how many time you reinstall the client)

### Minimal reproduction project (MRP)

1) Download The Godot on the website (https://godotengine.org/) by clicking on "Download Latest 4.2.1" or downloading it from Steam
2) Lunch Godot (By double clicking on Godot_v4.2.1-stable_win64.exe or running it on steam)
3) The Font might be fine at first but close the Godot and lunch it again
4) You can see the font is corrupted (It is still english)
![n](https://github.com/godotengine/godot/assets/159538595/3385a92f-1318-4c54-ac3e-19779eac26ac)
5) and from now on even if you reinstall Godot you saw the corrupted font in first Lunch (It does not affect the old version)
```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment] 2024-02-09 15:06
Duplicate of https://github.com/godotengine/godot/issues/79955

**Closed by AThousandShips** 2024-02-09 15:06 UTC
