### ISSUE TITLE
GDScript 2.0: Unable to cast in child classes using file classes defined in the parent class

### ISSUE THREAD

**Issue by Granpappy** [godotengine/godot#60449] opened 2022-04-23 02:10 UTC
### Godot version

4.0 alpha 6

### System information

Windows 10

### Issue description

Say you have a file class `CustomClass`, and you make a base class called `ParentClass` that will use `CustomClass` by registering it as a type for this class via `const CustomClass := preload("res://CustomClass.gd")`. Make a class that inherits/extends `ParentClass` called `ChildClass`. Now, if you try to cast using `CustomClass` as defined in `ParentClass`, the parser will throw an error saying that `"CustomClass" was not found in the current scope`.

This is weird because it partially recognizes `CustomClass`, as it appears in the dropdown for the auto completion. Also, calling something like `CustomClass.new()` or accessing some member functions/variables/enums defined in `CustomClass` are also acceptable. It doesn't like casting for some reason.

It doesn't like using `CustomClass` as a type for anything, actually.

I tried this issue out in Godot 3 and it worked fine.

### Steps to reproduce

Just make the three scripts below in the same directory and you'll see what I'm talking about.

_CustomClass.gd_
```
extends Resource
```

_ParentClass.gd_
```
extends Node

const CustomClass := preload("res://CustomClass.gd")
```

_ChildClass.gd_
```
extends "./ParentClass.gd"

func _ready() -> void:
	var my_res := CustomClass.new()
	var other_res := my_res as CustomClass # Parser throws error here
	return
```

**Comment by mashumafi** [comment] 2023-02-08 19:12
I can't reproduce this using the steps above. It maybe fixed.

**Comment by YuriSizov** [comment] 2023-02-08 19:19
Let's tentatively close it as many fixes have been done to GDScript since alpha 6

**Closed by YuriSizov** 2023-02-08 19:19 UTC
Labels: bug, topic:gdscript, regression

**Comment by Granpappy** [comment] 2023-02-09 01:49
From what I can tell, it looks to be fixed. I'm not having the issue anymore.
