### ISSUE TITLE
Controls ignore STOP filter mode

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10320] opened 2017-08-13 14:50 UTC
godot 23f6d3fa69935c90c6cdcee342ae99d226e9b4ab

here is sample
https://www.dropbox.com/s/n31lmfwybqbkb1h/mouse_test.zip?dl=0

if you press anywhere in window, _input event will capture this and print to Output, But of you click button, the same will happen, even while it has 'Stop' filter mode.

**Comment by curly-brace** [comment] 2017-08-13 18:05
i've also tried now creating a simple control with script that handles _gui_input and if mouse button is pressed just sets
get_viewport().get_tree().set_input_as_handled()
or
accept_event()
but none of them works 🙄

**Comment by kubecz3k** [comment] 2017-08-18 11:35
@curly-brace so what's the status of this issue?

**Comment by curly-brace** [comment] 2017-08-18 11:52
@kubecz3k well, it is active. i posted this code just to show that it is still possible to block events. but button just seems to ignore this step.

**Comment by rcarjan** [comment] 2017-10-31 08:58
In case anyone is interested, the issue still seems to be present on the latest builds.

**Comment by kubecz3k** [comment] 2017-10-31 12:21
So I think this is a regression, as far as I remember it was working in 2.x

**Comment by vybr** [comment] 2017-12-03 18:11
Can confirm. Even when using "Pass" as the mouse filter, objects behind the control are not receiving input events.

**Comment by mnemotic** [comment] 2018-01-05 16:28
I can confirm that as of da4edf83d, "Stop" filter does not stop event propagation. Neither seems `accept_event()` when called from overridden `_gui_input(event)`.

**Comment by akien-mga** [comment] 2018-01-08 13:09
> After investigating this further, the issues seems to be that events are propagated UP the control hierarchy, instead of DOWN. "Stop" filter does in fact stop an event from bubbling up.

Then it's indeed not a bug, it's how it's supposed to work. Documentation need fixed by https://github.com/godotengine/godot-docs/pull/952.

**Closed by akien-mga** 2018-01-08 13:09 UTC
Labels: documentation, topic:core
