### ISSUE TITLE
One way collision issue if a RigidBody2D spawns close to the platform

### ISSUE THREAD

**Issue by Tetane** [godotengine/godot#15370] opened 2018-01-05 16:59 UTC
**Godot version:**

Build from the Master branch 04/01/2018

**OS/device including version:**

Windows 10

**Issue description:**

I have a RigideBody2D that I control with a script by applying forces and impulses, and I have two StaticBody2D with a collision shape that is set to one way collision.
The RigidBody2D is suppose to path through the StaticBody2D platform on its way up and collide with it on its way down. But it does not collide on its way down if it pass through on its way up. It starts colliding first only when the RigidBody2D does not pass through on its way up.
After the first collision from the side, the one way collision starts to work normally.

![test_godot3](https://user-images.githubusercontent.com/13542748/34617179-d2c7c19c-f23a-11e7-965e-4e40ee401409.gif)

**Steps to reproduce:**
The bug seems to occur when the RigidBody2D spawns too close above to the collision shape of the StaticBody2D at the beginning of the game. 
There is no bug if the collision is not one way or if the RigidBody2D spawn a little bit further away from the platform.

**Minimal reproduction project:**

[test_godo3.zip](https://github.com/godotengine/godot/files/1607196/test_godo3.zip)

Node2D
---- RigidBody2D
--------CollisionShape2D
----StaticBody2D
--------CollisionShape2D (one way collision)
----StaticBody2D
--------CollisionShape2D (one way collision)

**Comment by Zireael07** [comment] 2018-01-05 17:01
How big is the margin on your collisions?

**Comment by Tetane** [comment] 2018-01-05 17:30
@Zireael07 I don't know what are the margin but the bug occur when the collision shape of the RigidBody2D is as close as 10 pixels from the platform at the beginning of the game.

**Comment by eon-s** [comment] 2018-01-14 15:10
@Zireael07 one way do not have margin on 3. 

Tested on b5b2ca8
The bug also occurs if the bottom shape is a regular one (not one side).

If you enable CCD, (surprisingly) works, if the rigid body shape is a bit smaller, works too.
Some kind of tunelling may be happening when the body shape is big enough to nearly touch 2 shapes, one of these being one side.

**Comment by Calinou** [comment] 2020-06-07 16:43
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by eon-s** [comment] 2020-06-08 05:16
I can't reproduce this issue on latest beta, there is still a weird behavior on the corners but is different than the OP.

**Comment by Calinou** [comment] 2020-06-08 07:33
@eon-s Thanks for the reply :slightly_smiling_face: I'll close this then. It might be worth opening a new issue about the behavior on the corners unless there's already a bug report about that.

**Closed by Calinou** 2020-06-08 07:33 UTC
Labels: bug, topic:physics
