### ISSUE TITLE
C# some of the Mesh's methods return int type while it's corresponding virtual ones return long type

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#67097] opened 2022-10-08 21:08 UTC
### Godot version

(mono) 4.0 b1, b2

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

It seems some of the virtual methods return different types than the regular ones, I'm not sure if this is a bug since I don't know what these could be for but it seems to be. I brought this up in discord and was told to report it just to be sure.

What I found right now:

Mesh (class) has `int GetSurfaceCount` and `long _GetSurfaceCount`, ...
In documentation for gdscript the latter (`_get_surface_count`) is a `virtual` one but both return `int`, again at least according to the documentation.
I tried checking in gdscript but the virtual one isn't accesible directly (expected) and I don't know how to properly deal with these through inheritance in gdscript so I'm mostly counting on the documentation about this and the expected return type from the method name.

There're more of these, some of the virtual ones return `long` while the documentation suggest a different type in gdscript (at least from what I checked it seems `int` turned into `long` in c#).

### Steps to reproduce

Check Issue description above.

### Minimal reproduction project

None, related to the code not any project.

**Comment by aaronfranke** [comment] 2022-10-08 21:09
Please update the title to be more descriptive.

GDScript ints are 64-bit, so the equivalent type in C# is `long`.

**Comment by viksl** [comment] 2022-10-08 21:29
> 

Oh, I accidentally cut the title out, sorry.
If the equivalent is `long` then I guess I can just close this issue? Though why one method returns `int` and its virtual `long` then?

**Comment by raulsntos** [comment] 2022-11-22 16:59
> Though why one method returns `int` and its virtual `long` then?

Like **aaronfranke** said, Variant scalar types are 64-bit so when generating the C# bindings we have to assume the types are `long` and `double` unless otherwise specified in the method's metadata. Unfortunately, virtual methods and signals currently don't support the metadata that specifies when a scalar type should use 32-bit instead so right now every virtual method and signal event handler use 64-bit types.

- Duplicate of https://github.com/godotengine/godot/issues/65749

**Closed by raulsntos** 2022-11-22 16:59 UTC
Labels: discussion, topic:dotnet
