### ISSUE TITLE
VSync/Framecap issues

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#24168] opened 2018-12-05 00:24 UTC
So I brought this up in the Godot discord, there appears to be an issue with framecapping and Vsync just totally not working at all

Specs:
GTX 1060
Ryzen 5 1600
16gb DDR4
Windows 10 

Tested Godot versions
3.0.5, V3.1dev.calinou.a3f1ee5

Main issues

Fullscreen --- 
Vsync and Debug>Settings>ForceFPS Both don't work in general, causing ridiculous amounts of frames to be rendered.

Windowed -- 
Vsync alone causes issue above, 
both enabled causes wanted results (properly limited frame rate), 
disabling Vsync, and setting forceFPS, causes issue above.

**Comment by antopilo** [comment] 2018-12-05 02:55
Be sure to check that your VSync settings in your graphic card settings is set to : Let application decides. Otherwise your gpu forces vsync to off.

**Comment by Duskitty** [comment] 2018-12-05 03:12
> 
> 
> Be sure to check that your VSync settings in your graphic card settings is set to : Let application decides. Otherwise your gpu forces vsync to off.

It is set to that, it's legit busted.

**Comment by damianday** [comment] 2018-12-08 13:48
Im also using a gtx1060 and have had similar problems.

**Comment by Chaosus** [comment] 2018-12-27 12:21
Yeah, it have massive fps drop for now

**Comment by Flonka** [comment] 2019-01-22 17:51
I can report the same issue , vsync not working in 3.1. But works in 3.0 stable. Tested by running empty 2d scenes from the godot editor.

Godot_v3.0.6-stable_x11.64 : working (vsync enabled, caps on 60fps)
Godot_v3.1-beta1_x11.64 : not working (vsync enabled, fps runs high) 
Godot_v3.1-beta2_x11.64 : not working (vsync enabled, fps runs high)

*glxinfo exerpt*
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.3.2

OS : Debian 8

**Comment by reduz** [comment] 2019-01-25 23:56
These two are not supposed to be used together, and it's a bad idea to do so. Force FPS is only for testing out stuff. Timing control changed in Godot 3.1 to fix many jitter related issues, which may be the cause for the different behavior you notice.

As this is not a bug, but something you shouldn't do in production, closing this issue.

**Comment by reduz** [comment] 2019-01-25 23:57
@Flonka If your report is about vsync alone, it may be a different issue (please open another), though I am running latest Ubuntu and vsync is working fine.

**Closed by reduz** 2019-01-25 23:56 UTC
Labels: bug, topic:rendering
