### ISSUE TITLE
BaseButton does not implement a public constructor (Mono)

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#35482] opened 2020-01-23 17:37 UTC
**Godot version:**
3.1.2 (Mono)

**Issue description:**
The constructor for `BaseButton` is being generated as `internal` in the GodotSharp assembly. There is no public constructor. This makes it impossible to make custom buttons without using a more specific class, such as `Button`, `ToolButton` etc. 

`BaseButton` contains useful code for handling mouse states (over, pressed etc), and also accommodates touch behaviour when a button is dragged in a scroll container (so the press becomes a drag, not a press). The constructor should really be protected (or maybe even public).

Mono only. GDScript allows classes to extend `BaseButton`.

**Minimal reproduction project:**
No project provided. Not having a public ctor prevents compilation.

**Comment by andy-noisyduck** [comment] 2020-01-23 17:49
Probably related #35484

**Comment by KoBeWi** [comment] 2020-12-12 01:03
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by andy-noisyduck** [comment] 2020-12-12 04:09
No public ctor is generated in 3.2.3.

This issue doesn't seem to have attracted too much love. Ignoring for a moment that it is inconsistent with GDScript's behaviour, I suspect there should be some input on whether this is an issue or not. What would be the correct way to implement custom button types?

**Comment by akien-mga** [comment] 2022-03-08 14:46
It's newer, but more generic, so closing as duplicate of #55549.

**Closed by akien-mga** 2022-03-08 14:46 UTC
Labels: bug, confirmed, topic:dotnet, topic:gui
