### ISSUE TITLE
Some scenes marked as changed just by switching to them in the editor

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6771] opened 2016-10-10 04:44 UTC
**Operating system or device - Godot version:**
Ubuntu Linux 16.04, Godot version fea1fb0925142c3279fd3afaf27e80e78cd2e1e8

**Issue description** (what happened, and what was expected):
Some scenes are somehow marked as changed simply by switching to them as seen in this small video [http://kuuv.io/i/8PTa8Um.mp4](http://kuuv.io/i/8PTa8Um.mp4)

This could be related to an animationplayer being present in the scene even if it's not playing. While not a huge issue by itself, it can lead to minor annoyances like displacing tabs out of view when there are few opened due to the size difference incurred by the (*) mark, and it's an undoable change, meaning a bunch of such changes could potentially push out important stuff out of the undo stack.
On a less technical note, it's slightly bothersome, as it's a change that's not known for no apparent reason.

**Steps to reproduce:**
I can only seem to reproduce it with scenes containing animation players, regardless of their playing state. Changing back and forth to a scene _without_ an animationplayer seems to not trigger it, but jumping to a different scene _with_ an animationplayer does, and any consecutive scenes with.

**Comment by Noshyaar** [comment] 2018-04-07 07:00
Duplicate of #6649 which I think doesn't happen anymore in latest master.

**Closed by Noshyaar** 2018-04-07 07:00 UTC
Labels: bug, topic:editor, usability
