### ISSUE TITLE
Godot 4.0: TileMap not displaying in beta 4 web exports

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#68149] opened 2022-11-02 03:20 UTC
### Godot version

4.0.beta4

### System information

Windows 11, NVIDIA RTX 3070, Intel Core i7

### Issue description

I had noticed web exports were broken in beta 3 so went to test as soon as Yuri mentioned beta 4 was published, just not the post about it, and found that my TileMap in a game I'm working on isn't displaying in web exports - works fine for every other export I've tried, just web doesn't show them.

### Steps to reproduce

1. Download associated project
2. Run it

Or for more detailed ones:

1. Start a new project
2. Add a TileMap with a proper tileset
3. Add an export for web
4. Export for web
5. Load up into itch.io (this is how I did it, but can probably test normally with the button in Godot), see it not work

### Minimal reproduction project

[GodotCollab.zip](https://github.com/godotengine/godot/files/9915632/GodotCollab.zip)

**Comment by Skwint** [comment] 2022-11-02 16:37
Pretty sure that's a duplicate of [Web exports and TileMaps](https://github.com/godotengine/godot/issues/66086)

**Closed** 2022-11-02 17:05 UTC
Labels: bug, platform:web, topic:rendering, topic:2d, topic:export
