### ISSUE TITLE
Godot 4.2 extremely slower than 4.1.3 both starting up and running

### ISSUE THREAD

**Issue by archzeero** [godotengine/godot#85739] opened 2023-12-04 04:04 UTC
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 7600 (Advanced Micro Devices, Inc.; 31.0.21031.1005) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

I've noticed extremely slow down in my project after changing to v4.2 from v4.1.3.

At first it just oppened normally, and even now, if I get the project backup from how it was at v4.1.3, it starts as fast as how it was on v4.1.3, but after really few changes, so I guess it somehow has to do with how v4.2 saves projects, it all of sudden start to become completely slower, despite same CPU and RAM usage.

The actual issue seems around the fact that the process Stop Working at times, both the Editor itself game itself while running.

### Steps to reproduce

I'm not exactly sure, couldn't reproduce with demos or smaller projects, seems somehow related to few changes and project being saved on 4.2, willing to help finding it out

### Minimal reproduction project

Not sure how to achieve a minimal, might have to rely on more people facing similar issues (I've noticed #85608, #85619 maybe could be related and around how it happens on mac not sure)

**Comment by KevinWh0** [comment] 2023-12-05 21:50
Hi, I have the same issue with Godot V4.2.stable. Im running it on Windows 11 22631.2715. I have an Intel 12th gen I7-12700H (14 cores, 20 threads) and I have an RTX 3050 Ti Laptop GPU.

From my few tests, it seems to take around 5 or 6 minutes to open from the time I clicked the exe.
Godot 4.1 didn't have this issue for me and generally started within a few seconds at most.

**Comment by clayjohn** [comment] 2023-12-05 23:33
This sounds like a duplicate of https://github.com/godotengine/godot/issues/20566 which pops up randomly from time to time. Can you try removing your USB devices one-by-one to see if one of them caused the issue?

**Comment by ThePat02** [comment] 2023-12-09 12:03
I just had this issue. There was a USB-C cable plugged into my machine. It was connected to nothing, but caused INSANE loading times on my project. Unplugging it fixed this.

**Comment by Calinou** [comment] 2023-12-09 13:59
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/20566.

**Closed by Calinou** 2023-12-09 13:59 UTC
Labels: platform:windows, needs testing
