### ISSUE TITLE
Weird color picker behaviour

### ISSUE THREAD

**Issue by KDouble48** [godotengine/godot#73935] opened 2023-02-25 16:54 UTC
### Godot version

4.0.rc5.official

### System information

Windows 10, Vulkan, RTX2080 (528.49)

### Issue description

1. When using the colorpicker, I can't undo the change. When trying to close without saving, the editor freezes and I have to close it with the task manager.

2. When using the color picker, the top and bottom of my screen turns black. Nvidia GeForceExperience detects a Game (also works with it disabled). Also the whole screen turns black when I move the editor to my second display and try to open the color picker.
![Black Screen](https://user-images.githubusercontent.com/50096015/221369257-fb42ecda-7238-443c-8c34-6f84d300cfd4.png)
If I move the editor back to my first display, it zooms into the editor.
![Zoom](https://user-images.githubusercontent.com/50096015/221369195-38061692-78ca-4f42-9a3f-6333edd19913.png)
The console mentions wrong pixels sizes. Propably referencing the different resolutions of the displays causing this issue.

### Steps to reproduce

For 1.:
- Create a new project; Forward+
- Create a new 3D scene
- Add a MeshInstance3D
- Add a new BoxMesh to Instance
- Save
- Add a new StandardMaterial3D
- Change Albedo color with the color picker
- Close color selector
- (Optional: Try to undo the chage, won't undo color change)
- Close editor; don't save
- Freeze

For 2.:
See Issue description.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-03-15 20:05
1. Is fixed
2. Is duplicate of #74048

**Closed by KoBeWi** 2023-03-15 20:05 UTC
Labels: bug, platform:windows, topic:rendering, topic:editor
