### ISSUE TITLE
[Feature Request] Vim-like mode

### ISSUE THREAD

**Issue by mrbig033** [godotengine/godot#27613] opened 2019-04-02 18:14 UTC
**Godot version:**
- 3.1.stable.official

**OS/device including version:**
- MX-Linux 18
- Window Manager: [i3](https://i3wm.org/)
- compton 0.1~beta2+20150922
- OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)

**Issue description:**

Right now the only external editor with proper support for Godot seems to be VSCode. The second best is Vim, and the third is Emacs. I tried all of them. They're subpar and the switching breaks my workflow. The built-in editor is good enough for regular users, but for Vim/Emacs folks there are not enough text manipulation commands and customization options.

Furthermore, Emacs/Readline compatible keybindings would also be handy in every part of the interface. But this requirement could be replaced by simply adding more keybinding customization options.

*I made this issue in part to make it separate from the one requesting Emacs keys*.

**Comment by Calinou** [comment] 2019-04-02 18:19
Duplicate of https://github.com/godotengine/godot/issues/17213.

**Closed by Calinou** 2019-04-02 18:19 UTC

**Comment by mrbig033** [comment] 2019-04-02 18:22
> Duplicate of #17213.
> 
> By the way, some Readline keybindings such as Ctrl + K and Ctrl + U are already implemented in LineEdit nodes (both in the editor and exported projects).

I don't know what that is. And [the documentation](http://docs.godotengine.org/uk/latest/classes/class_lineedit.html) is austere to say the least :/

**Comment by Calinou** [comment] 2019-04-02 22:35
@mrbig033 The class reference is primarily written to help developers understand what nodes' properties and methods can be used for. However, I think the default bindings featured in LineEdit are worth documenting there as they're definitely not obvious (and may interfere with user-written logic). You could create an issue about that :slightly_smiling_face:

**Comment by mrbig033** [comment] 2019-04-03 23:59
Thank you, @Calinou. I will do so as soon as I get acquainted with it.

**Comment by Calinou** [comment] 2019-04-04 12:29
@mrbig033 I opened a pull request that documents LineEdit's key bindings, see #27656.
