### ISSUE TITLE
Godot 3 has no Movement and Rotation axis locks

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#14440] opened 2017-12-09 06:56 UTC
Godot 3 has no Movement and Rotation axis locks for PhysicsBody (3D) class. The only thing I found is axis_lock property in RigidBody but it's for rotation and allows only 1 axis lock.

Is any form to make a workaround or I have to migrate the 3d platformer project I'm doing to Unity3d?

![screenshot_20171209_034759](https://user-images.githubusercontent.com/18708610/33793305-6b4d2dce-dc94-11e7-881d-a96874daa690.png)

**Comment by akien-mga** [comment] 2017-12-09 09:14
Duplicate of #12500. There's a pending PR that implements it: #12756.

**Closed by akien-mga** 2017-12-09 09:14 UTC
Labels: enhancement, topic:physics, usability

**Comment by Alexia-AT-Digitecnology** [comment] 2017-12-09 10:52
No, @akien-mga , the PR #12756 only add constraints for movement, not for rotation.
