### ISSUE TITLE
Area2D CollisionMask is bugged

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot#44220] opened 2020-12-09 13:23 UTC
**Godot version:**

3.2.3 Mono

**OS/device including version:**

Windows 10, Rx570, GLES2

**Issue description:**

Lets say I have 2 Area2D objects AreaA (on CollisionLayer1) and AreaC (CollisionLayer2).

I set the CollisionMask of AreaA to 5 and  AreaC to 1.

If I then call **AreaA**.GetOverlappingAreas() while areas A and C collide - I will get result other than empty array.
This is extremly broken and dangerous. It basically renders the entire concept of collision Layers and Masks uselles, one cannot rely on them at all.
Changing the mask of **C** suddenly changes the GetOverlappingAreas of **A** !

If AreaC has a CollisionMask to some other value (other than 1) - **AreaA**.GetOverlappingAreas() returns  empty array (as expected)

**Steps to reproduce:**
Look at the posted example.

**Minimal reproduction project:**
[Area2dBugtesting.zip](https://github.com/godotengine/godot/files/5666173/Area2dBugtesting.zip)

**Comment by madmiraal** [comment] 2020-12-09 13:33
Duplicate of #7644.

BTW There is a PR to fix this: #42268

**Closed by madmiraal** 2020-12-09 13:33 UTC

**Comment by LordBrkica** [comment] 2020-12-09 13:39
Holy shit - this bug stems from January 2017.

Why not put with some information (with BIG RED LETTERS) in the documentation of[ GetOverlappingAreas()](https://docs.godotengine.org/en/stable/classes/class_area2d.html#class-area2d-method-get-overlapping-areas) that the method is broken ?
I mean its broken, its known - why not state the obivous as soem warning ? One can always delete the warning when the fix is implemented.
