### ISSUE TITLE
Current script error disappears if you use Ctrl+F

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#30566] opened 2019-07-13 19:07 UTC
Godot 3.1.1

Reproduction steps:
1) Write a script, and put an error in it
2) See the script editor highlights the error and shows what it is at the bottom:
![image](https://user-images.githubusercontent.com/1311555/61175552-9aff7600-a5a9-11e9-96d2-ed7b9e6c2af8.png)
3) Type `Ctrl`+`F` to open incremental search
![image](https://user-images.githubusercontent.com/1311555/61175568-cbdfab00-a5a9-11e9-9c44-c4724e45e6fc.png)
4) then `Esc` to close it: notice the error message is no longer shown, despite the error still being present.
![image](https://user-images.githubusercontent.com/1311555/61175566-c08c7f80-a5a9-11e9-86f6-2b53978344da.png)

It also happens with Ctrl+R (incremental replace)

**Comment by YeldhamDev** [comment] 2019-07-13 23:09
Duplicate of #29234.

**Closed by YeldhamDev** 2019-07-13 23:09 UTC
Labels: bug, topic:editor
