### ISSUE TITLE
[4.0] Built-In Scripts cause crash when creating new custom Objects and Nodes

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#67779] opened 2022-10-23 04:28 UTC
### Godot version

Godot 4.0 beta 3

### System information

Windows 10 

### Issue description

Ran into a crash while working on my project, I debugged it a bit and it seems the scene crashing is caused when trying to create new custom Objects or Nodes from within a Built-In Script; with the debugger stating the following:
![image](https://user-images.githubusercontent.com/17155529/197373726-833457e7-84dd-4d37-b00f-fc9b4fceeb72.png)

I've gone ahead and attached a minimal reproduction project with one custom Object, one custom Node and two Scenes. Both Scenes are using the same setup and logic to create the Objects and Nodes, the only difference is the crashing scene is using a Built-In Script. As seen below:

https://user-images.githubusercontent.com/17155529/197373643-4b8e8293-d5cf-46de-888a-a0389e04d804.mp4

### Steps to reproduce

1. Open example project
2. Open `script_built_in.tscn`
3. Run scene
4. *Crash*
5. View debugger for the following output:
`Invalid Call. Nonexistent function 'new' in base 'GDScript'`
6. Close `script_built_in.tscn`
7. Open `script_file.tscn`
8. Run scene
9. *No crash*

Note: *Both example Scenes have the same setup and logic, the only difference is one is using a Built-In Script and the other isn't*

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/9845738/example.zip)

**Comment by kdada** [comment] 2022-10-24 19:37
If you load a script with GDScript loader, it will set script path correctly via GDScript::load_source_code().

But a built-in script is loaded by  TCSN loader. The loader only set path via `Resource::set_path()`. Therefore GDScript.path is always empty. GDScript parser can't set dependencies for it because there are many owner checks:

```
	if (!p_owner.is_empty()) {
		singleton->dependencies[p_owner].insert(p_path);
	}
```

**Comment by KoBeWi** [comment] 2022-10-25 15:43
This is not a crash. It's also duplicate of #51538

**Closed by KoBeWi** 2022-10-25 15:43 UTC
Labels: bug, archived, topic:gdscript
