### ISSUE TITLE
The pointer skips away by dragging over an integer value in the Inspector

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#25046] opened 2019-01-16 20:34 UTC
**OS**
Linux Ubuntu 18.04 LTS

**Godot version:**

07e2046980c903268ef0d2f5a73caea77d511519

**Issue description:**

While testing the issue https://github.com/godotengine/godot/issues/22652#issuecomment-444291646
 I discovered an another issue:

* open the project
* drag the LMB above the Custom Fonts -> Size [42] spinbox
the pointer jumps away 8-/

![image](https://user-images.githubusercontent.com/4047289/51276406-f3780100-19d4-11e9-8560-238bbb224cf5.png)

**Comment by akien-mga** [comment] 2019-02-25 15:15
Confirmed in 88a36e20cb. It's not critical though so moving to next milestone.

**Comment by bojidar-bg** [comment] 2019-09-15 16:42
Is this still valid?

**Comment by capnm** [comment] 2019-09-16 20:02
> Is this still valid?

AFAIK nobody has even tried to fix this issue. 
You can check that with the mentioned project:
https://github.com/godotengine/godot/files/2646416/mouse_cursor_bug.zip

**Comment by akien-mga** [comment] 2020-01-13 11:35
Still reproducible in the current `master` branch.

Might be Linux specific though and linked to their way the cursor is captured. It's possible that dragging the custom font size value triggers an automatic update to refresh the font which interferes with the captured cursor.

**Comment by Windsdon** [comment] 2020-07-24 17:41
I can confirm that this bug happens on Windows.

Also, I should add that this bug seems to **only happen on the font size slider**. Other sliders work fine.

Current setup:

- Godot Engine v3.2.2.stable.mono.official 
- Windows 10 Enterprise 1903

![](https://user-images.githubusercontent.com/1307584/88419216-10b93700-cde5-11ea-8ecf-8f81d004912e.gif)

**Comment by pouleyKetchoupp** [comment] 2020-07-25 19:09
The same issue actually happens with any property that uses `_change_notify()` without an argument on a property with range. 

When you search in the codebase, there are lots of other potential cases. I've tried one randomly (`hframes` & `vframes` in `Sprite`) and it does occur too.

I wonder what would be a possible approach to fix it all over the engine:
1. Search through the codebase for similar cases and change all `_change_notify()` into specific property notifications like #40701 does. That would work but it's a lot of manual changes.

2. Maybe there could be a way to fix it on the spinner itself, or on the inspector? The issue is that `EditorSpinnerSlider` makes the mouse invisible, and sets it back on mouse release, while warping it to its previous position. In case the inspector is entirely refreshed, the mouse is set back to visible without being warped back, which causes it to end up at the center of the screen. Warping it back when the spinner is refreshed would cause the cursor to flicker while hanging the edited value, so I'm not sure how it could be fixed.

**Comment by opl-** [comment] 2020-07-25 19:38
While this could possibly be fixed everywhere, for example by somehow storing the control focus while rebuilding the tree or changing the strategy used when `_change_notify` is called without specifying a property, I'm not sure how to even approach that. Overall calling `_change_notify` with the names of the properties that changed should be more efficient, as instead of recreating the whole inspector tree only the relevant property inspectors get updated.

Storing the control focus sounds like a lot of effort for what is ultimately a workaround for missing code. Changing the second could be an improvement but I believe would require having access to the previous property value. This is technically already stored in the nodes of each `EditorProperty`, at least for the primitive types, so it might be possible by implementing a new `EditorProperty` method, but ultimately `_change_notify` calls should probably be as specific as possible anyway to improve performance (which could be especially useful when dealing with large arrays, for example).

**Comment by akien-mga** [comment] 2021-09-16 13:25
Fixed in `3.x` with #47235, though AFAIU it's still valid in `master`.

**Comment by opl-** [comment] 2021-09-16 13:32
From what I remember this issue existed because `_change_notify` wasn't being called with the name of the property which was changed, causing the inspector to rebuild the UI the user was interacting with. Since #45879, `_change_notify` no longer exists, meaning that unless the new method is somehow broken, it should work on master. I can't test this myself at the moment.

**Comment by akien-mga** [comment] 2021-09-16 13:40
Thanks, I've tested quickly and I can't seem to reproduce the issue in `master`, so it might indeed be solved too.

**Closed by akien-mga** 2021-09-16 13:40 UTC
Labels: bug, topic:editor, confirmed
