### ISSUE TITLE
increasing the main font size cause Godot to crash

### ISSUE THREAD

**Issue by MohammadAboulEla** [godotengine/godot#65478] opened 2022-09-07 14:53 UTC
### Godot version

Godot Engine v4.0.alpha16.official.86dd3f312

### System information

Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti

### Issue description

keep crashing when I'm increasing the main font size in the editor settings

### Steps to reproduce

editor settings> increase font size

### Minimal reproduction project

any project

**Comment by Calinou** [comment] 2022-09-07 16:46
Does this occur if you set an increased font size *once* by entering a new value, rather than dragging the value to set it? If not, this is probably a duplicate of https://github.com/godotengine/godot/issues/59798.

**Comment by KoBeWi** [comment] 2022-10-05 11:29
Likely fixed by #66859
Comment if you can still reproduce in newest master.

**Closed by KoBeWi** 2022-10-05 11:29 UTC
Labels: bug, topic:editor, crash
