### ISSUE TITLE
AnimatedSprite2D Shader Uses UV Coordinates From Spritesheet

### ISSUE THREAD

**Issue by qweeren** [godotengine/godot#85355] opened 2023-11-25 18:59 UTC
### Godot version

4.1.3.stable

### System information

Windows 10 - Godot v4.1.3.stable - Vulkan

### Issue description

When adding a fragment shader to a AnimatedSprite2D; the shader doesnt get its uv data from the current frame, it gets the uv from the whole sprite sheet.
I was trying to add a shader that uses a pentagon shape as a mask. But the pentagon got clipped and moved arround per frame. I dont know the backend but it would make much more sense if it used the frames uv coords (or whatever that causes this got fixed).

### Steps to reproduce

Add an AnimatedSprite2D
Use a sprite sheet of anything.
Add a shader to that.

### Minimal reproduction project

N/A

**Comment by arkology** [comment] 2023-11-25 19:11
See https://github.com/godotengine/godot/issues/57401

**Comment by Chaosus** [comment] 2023-11-26 10:15
Duplicate of #57401

**Closed by Chaosus** 2023-11-26 10:15 UTC
