### ISSUE TITLE
Close other scenes (other than the current opened scene)

### ISSUE THREAD

**Issue by fire** [godotengine/godot#27493] opened 2019-03-28 15:47 UTC
**Godot version:**
3.1

**Issue description:**

As a Godot contributor, I am working on the asset importer and I open many scenes. Having a button to close other scenes than the open one would help my workflow. Imagine 40 scenes open but only the open scene is relevant.

The feature is right clicking on the scene tab and then clicking close to close other scenes. The wording can be different.

**Comment by Calinou** [comment] 2019-03-28 15:51
Similar to Web browsers, we can offer two options: one that closes all other tabs, and one that closes all tabs to the right (so you can close many tabs in a more selective manner).

![image](https://user-images.githubusercontent.com/180032/55172041-b3be5a00-5179-11e9-96e6-87c746c2f189.png)

**Comment by Calinou** [comment] 2019-03-28 15:53
Duplicate of https://github.com/godotengine/godot/issues/19701.

**Closed by Calinou** 2019-03-28 15:53 UTC
Labels: enhancement, topic:editor, usability
