### ISSUE TITLE
Autoload signal connected through C# delegate does not disconnect when receiver is freed

### ISSUE THREAD

**Issue by chaseberry** [godotengine/godot#82346] opened 2023-09-26 02:13 UTC
### Godot version

v4.1.1.stable.mono.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

When a node connects to a Signal created in an Autoload through C#s EventHandler, it continues to receive that signal after it has been freed.  This can cause unintended behavior and ObjectDisposedExceptions.

The signal is disconnected when the 'Connect' function is used with a Callable. 

https://github.com/godotengine/godot/issues/66319 is very related, and a possible jumping off point, although it was fixed a year ago.

### Steps to reproduce

Create a signal in a script that is used in an Autoload.
Have a condition in the same Autoload script to emit the signal.
In another script, use C#s += to connect the signal to a function.
Free the second script.
Repeat the condition in the Autoload that emits the signal.

### Minimal reproduction project

Run the included SignalTest project from Scene 1.
Click anywhere, three signal debugs should print.
Press enter to change to another scene.
Click anywhere, no signal debugs should print, but one does.

[SignalTest.zip](https://github.com/godotengine/godot/files/12721275/SignalTest.zip)

**Comment by Wagnard** [comment] 2023-10-08 00:15
I can observe the same issue on my side.

**Comment by paulloz** [comment] 2023-10-08 23:52
Duplicate of #70414

**Closed** 2023-10-09 11:01 UTC
Labels: bug, confirmed, topic:dotnet
