### ISSUE TITLE
Custom Resources don't have Icons in FileSystem dock

### ISSUE THREAD

**Issue by Modleyyy** [godotengine/godot#70559] opened 2022-12-25 14:58 UTC
### Godot version

3.x (Probably 4 too, haven't checked yet)

### System information

Windows

### Issue description

When creating a Custom Resource (which we will call from now on CR for short) and giving it an Icon, everything works fine.
![image](https://user-images.githubusercontent.com/115263256/209472328-b3b992f8-5566-4c82-a4fa-3e58a26cfb98.png)

You can see the Icon normally when creating the CR in the Resource List.
![image](https://user-images.githubusercontent.com/115263256/209472396-6f72a79e-bbcf-4162-a925-6dca151ed796.png)

But somehow, when in the FileSystem dock, the Icon is replaced by a default file Icon.
![image](https://user-images.githubusercontent.com/115263256/209472443-ae8adbe8-83bf-4cb8-a4cb-43324ab302a3.png)

I've checked, and seems like this problem has been here for a long time. Does anyone know how to fix it? I hope if someone knows how, they'll do it for Godot 3 too. Also, I DO have checked for older versions of Godot, and it also didn't work. I still haven't checked Godot 4 because my graphic card is too old to support GLES3, so go see if it works there.

### Steps to reproduce

Just create a CR, give it a Class Name and Icon, create a new instance of this CR and save it to the Project folder, then the Icon doesn't appear in the FileSystem dock.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10300168/project.zip)

**Comment by Fabien2S** [comment] 2022-12-25 15:04
Can confirm for v4.0.beta10.mono.official [d0398f62f]

**Comment by KoBeWi** [comment] 2022-12-25 15:48
Duplicate of #32706

**Closed by KoBeWi** 2022-12-25 15:48 UTC
