### ISSUE TITLE
Unicode support please.

### ISSUE THREAD

**Issue by Angluca** [godotengine/godot#1644] opened 2015-04-07 17:20 UTC
I use it on mac.

Solutions
http://www.michaelsydenham.com/getting-godot-engine-to-display-japanese/
It's can work, But can't use IME input unicode to it.

**Comment by reduz** [comment] 2015-04-08 00:29
what specific input language are you using?

**Comment by niu2x** [comment] 2015-04-08 00:31
I want to use chinese, how to do?

**Comment by reduz** [comment] 2015-04-08 00:40
i'm not really sure, is the IM for chinese the same as for korean and japanese?

**Comment by Angluca** [comment] 2015-04-08 03:01
I input Chinese, Yes it the same as for korean and japanese.

**Comment by michaeldesu** [comment] 2015-04-08 10:48
I've just tried entering Japanese into a label text field (inspector value), but the chars appear as English instead of direct Japanese (as is usual on Mac, irrespective of font setting). I could try it on Windows if you like. Is there anything specially needed to enter & use Asian chars?

**Comment by michaeldesu** [comment] 2015-04-08 11:33
Well I can't enter Japanese into a label on windows either, and I imported a japanese fnt (with unicode set) as well, but no good. I guess the editor (fields in the inspector) is not supporting unicode, however from this post (http://www.godotengine.org/forum/viewtopic.php?f=11&t=86&p=294&hilit=japanese#p1203) it seems to have once supported it? This issue has also been raised here: https://github.com/okamstudio/godot/issues/29
I was pleased to read in the docs that font culling seems to have been considered, which is a relief since the Japanese font I made is 5Mb!

**Comment by michaeldesu** [comment] 2015-04-09 09:42
I have an update - I am new so I'm not so familiar with unicode status of GD, but after some research on the forum, I think it the editor seems to work with CJK. I just tried an experiment after reading this forum post (http://www.godotengine.org/forum/viewtopic.php?f=11&t=725&p=3310&hilit=unicode#p3310) and I reported a result here (https://github.com/okamstudio/godot/issues/29) after stumbling upon that issue. I wonder if Angluca can try again, by setting up an editor font (you'll have to import one, being careful to set unicode as the font type when importing). I'd be glad to hear a confirmation from reduz, but it seems the editor does indeed support unicode (and IME text entry) provided that initially, a unicode font is setup as an editor font.

**Comment by niu2x** [comment] 2015-04-09 13:17
I import a font, set global font, and editor font...
Result is that,, if I call set_text() to set a label's text value, it can display chinese character..
But it can't display in editor,,
Do you mind make a description detailed?

**Comment by niu2x** [comment] 2015-04-09 13:40
I see it

**Comment by niu2x** [comment] 2015-04-09 13:41
我沒有多看資料，打扰了

**Comment by OlexiyKravchuk** [comment] 2015-04-09 18:39
I also have a problem to blank lines when I use my native language, the editor does not have any place that could accept what I write something other than the digits when I'm in natural language :(

**Comment by michaeldesu** [comment] 2015-04-09 23:07
@niu2x: is your problem solved?
@OlexiyKravchuk : what is your language? BTW I wrote a mistake before. I said "provided that initially, a unicode font is setup as an editor font". I should have said "global font". Did you setup an appropriate unicode font as a global font? When I get some time, I will write up a summary instruction & put onto the forum (in the sticky beginners post)

**Comment by niu2x** [comment] 2015-04-09 23:23
I CAN not solve it.
Except in runtime，the engine can't show my   
native character in gui just like your screen snap。thank ，I desire your summary。
thank you

**Comment by michaeldesu** [comment] 2015-04-10 02:59
@niu2x I wrote a summary on my <a href='http://www.michaelsydenham.com/getting-godot-engine-to-display-japanese/'>blog</a>. Hope it helps.

**Comment by niu2x** [comment] 2015-04-10 04:04
maybe your IME is special. Your IME have a special top-left corner to cache your native character.
But when I touch a key,--- even if I have select my native IME,---- the char releated to the key I touched enter the "text widget" right away. I can't input a chinese character.
Is there something I missed?

**Comment by michaeldesu** [comment] 2015-04-10 04:08
@niu2x I used the standard IME in Microsoft windows. What operating system are you using? I guess I can try setting up a Chinese IME & font and try on PC or Mac. Which Chinese system are you using (simple or traditional or other)?

**Comment by niu2x** [comment] 2015-04-10 04:19
My operating system  is  fedora20.
I use the IME distributed with the system.
Simple Chinese.
I'm going to have a try in other system.
Thank you

**Comment by niu2x** [comment] 2015-04-10 04:22
yeah, I Know.
It take effect in my xp system.
It have to  install a special IME to input.

**Comment by michaeldesu** [comment] 2015-04-10 04:30
I just tried simplified Chinese using the method I described, and it seems to work (on Windows 8.1 using the standard Microsoft Pinyin IME)
![image](https://cloud.githubusercontent.com/assets/11791450/7081907/f9a6a264-df8d-11e4-8219-7fce51a137ec.png)

**Comment by michaeldesu** [comment] 2015-04-10 04:41
@niu2x The other thing you can try on fedora is install the fonts as I mentioned, but inupt the text into another text editor (where the IME should be ok in that program) and then copy and paste the text from the text editor into the text value in Godot. Try as an experiment to see if this workaround can work.

**Comment by niu2x** [comment] 2015-04-10 04:51
Ok，i will have a try。
open source project is always difficult to work in a special enviroment。
thanks for your time。
good lunch

**Comment by Angluca** [comment] 2015-04-10 06:09
Can't input Chinese on mac.

**Comment by michaeldesu** [comment] 2015-04-10 06:27
@Angluca I'll try Japanese a bit later on my Mac & let you know (confirm or otherwise)

**Comment by dbsGen** [comment] 2015-04-10 06:34
Can input on Ubuntu, too.

**Comment by sampad1370** [comment] 2015-04-10 06:42
Hi to all!!
how can write Arabic language in editor!!?
thanks.

**Comment by Angluca** [comment] 2015-04-10 07:04
@michaeldesu Oh It's work now! Thank you very much, I always can't use IME input word, Only copy&paste to it, But I think It's no matter.

**Comment by Angluca** [comment] 2015-04-10 07:16
@niu2x 在mac上不能在GODOT里面输入中文, LINUX上应该也差不多, 可能跟不支持IME有关吧, 不过可以复制粘帖进去, 问题也算是解决了, 希望以后支持输入法输入,

**Comment by michaeldesu** [comment] 2015-04-10 07:17
@Angluca I did the setup process on my Mac, and I agree with you. The IME doesn't work on the Mac, but it's possible to paste in Japanese from a text editor etc. I agree, it's not ideal. @reduz do you think it's possible to make the Mac support text entry from its IME? Seems like the similar issue from Linux. With Windows, it's just lucky MS supports the 'alternative' text-entry scheme.

**Comment by michaeldesu** [comment] 2015-04-10 07:18
@Angluca I think it's important not to close it, since there's still an issue with non-Latin text entry

**Comment by sampad1370** [comment] 2015-04-10 07:24
Hi to all!!
how can write Arabic language in editor!!?
i use import font but don't work for Arabic Font!!
How do this? Please Help me. 
thanks.

**Comment by michaeldesu** [comment] 2015-04-10 07:24
@sampad1370 seems like there was some discussion about Arabic here https://github.com/okamstudio/godot/issues/982 but I'm not sure about the conclusion. Anway if you follow my method using the appropriate Arabic font, it should be fine (unless there is some font direction issue)

**Comment by sampad1370** [comment] 2015-04-10 07:31
Hi to all!!
how can write Arabic language in editor!!?
i use import font but don't work for Arabic Font!!
How do this? Please Help me. 
thanks.

**Comment by sampad1370** [comment] 2015-04-10 07:32
Hi to all!!
how can write Arabic language in editor!!?
i use import font but don't work for Arabic Font!!
How do this? Please Help me. 
thanks.

**Comment by sampad1370** [comment] 2015-04-10 07:32
Hi to all!!
how can write Arabic language in editor!!?
i use import font but don't work for Arabic Font!!
How do this? Please Help me. 
thanks.

**Comment by sampad1370** [comment] 2015-04-10 07:32
Hi to all!!
how can write Arabic language in editor!!?
i use import font but don't work for Arabic Font!!
How do this? Please Help me. 
thanks.

**Comment by Angluca** [comment] 2015-04-10 07:34
@sampad1370 Sorry, Maybe only paste now, Don't repost. You can download arabic language font.
http://www.michaelsydenham.com/getting-godot-engine-to-display-japanese/

**Comment by GungnirInd** [comment] 2015-04-10 07:35
sampad, see issue [#982](https://github.com/okamstudio/godot/issues/982) for details on the engine's Arabic support (long story short, it's being worked on but it's not ready yet).

**Comment by sampad1370** [comment] 2015-04-10 07:40
sorry,excuse me!!
my browser don't send this post,but now send all post!! :O

**Comment by sampad1370** [comment] 2015-04-10 07:57
thanks for your help,but Arabic and Persian Language is a difficult challenge for Godot Engine!!
any one have a another answer?
thanks again of all and excuse me for post repeatedly before.

**Comment by niu2x** [comment] 2015-04-10 09:40
I must tell you，even paste can't work in fedora。maybe i need to install another ime or install win8

**Comment by michaeldesu** [comment] 2015-04-10 10:45
@niu2x That's surprising that paste doesn't even work - well at least you know Windows works (best so far for text entry) & Mac works for pasting. I guess any version of Windows will be ok (not just 8 since the IME in 8 is pretty much the same as earlier versions of Windows). Hopefully text entry via IMEs will be fixed in the future.

**Comment by niu2x** [comment] 2015-04-10 11:45
OK, let me skip the problem.

**Comment by OlexiyKravchuk** [comment] 2015-04-10 14:11
@michaeldesu 
my native language is Ukrainian, today I found a good way here http://www.michaelsydenham.com/getting-godot-engine-to-display-japanese/, but it's not exactly what I would have wanted to see, I would like to to carry out the official localization of all Godot in my native language, as do the blender for all languages, supported out of the box! :)

**Comment by OlexiyKravchuk** [comment] 2015-04-10 14:51
When have a way to make the translation I am happy take part to make contributions for Godot translation for my language, and perhaps even other that I know!

**Comment by michaeldesu** [comment] 2015-04-10 23:37
@OlexiyKravchuk I guess a formal or separate requestis needed to allow the editor GUI itself to be localised. JFYI I noticed this <a href="http://www.godotengine.org/forum/viewtopic.php?f=11&t=86&p=310#p1214">post</a> that shows MaryNate started or demonstrated the possibility to do an independent Chinese localisation within the source code directly.

**Comment by OlexiyKravchuk** [comment] 2015-04-11 16:19
Yes, I be there today, it's an interesting project, I hope in the final outcome will be possible to conveniently add any number of translations in any language, and it will have the official support out of the box as in the blender!

**Comment by bushig** [comment] 2015-05-03 21:49
Unicode support really should be added for 1.1 release. It seems to be reason of other problems, for example godot does not save its configs becouse of non latin path to appdata.

**Comment by bushig** [comment] 2015-11-01 12:03
Any info on this issue? I think the problem can be fixed for 2.0 by changing standard font.

**Comment by akien-mga** [comment] 2015-11-01 12:11
Closing as a duplicate of #29.

**Closed by akien-mga** 2015-11-01 12:11 UTC
Labels: archived
