### ISSUE TITLE
having a space in a `.blend` prevent mesh from being imported

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#77843] opened 2023-06-04 18:14 UTC
### Godot version

4.1.dev (4d5f10fc3a)

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When there is a space in the `.blend` file name the `.bin` file will have a corrupted name with `%20`instead of spaces. This will result in godot not finding the file and meshes not to be imported. Might be system/architecture dependant.

### Steps to reproduce

1. open godot
2. add a .blend file with a space in it 
3. See the errors

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-06-05 11:48
Duplicate of #76813 indeed, it's a Blender bug fixed in 3.6.

**Closed by akien-mga** 2023-06-05 11:48 UTC
