### ISSUE TITLE
GLES3: Drawing a MultiMesh after VisualServer.canvas_item_add_* draw commands change the MultiMesh color

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot#45711] opened 2021-02-04 18:40 UTC
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

Intel® HD Graphics (Cherry Trail) GLES3

**Issue description:**

I'm creating a custom 2d particle system using MultiMesh to draw all the particles. I noticed that the mesh color is somehow shared from a previous node drawed. In the case, a CollisionShape2D is drawing the RectangleShape2D gizmo, with a blue color with opacity, when the particle system is drawed, all the instances inside multimesh has the same color of the RectangleShape2D gizmo.

**Steps to reproduce:**
1. In a new 2D project, create a Node2D with a CollisionShape2D with any shape and another Node2D;
2. In the second Node2D, give it a tool script that will draw the multimesh;
3. In the _enter_tree method, add a code to generate a multimesh with N instances and give each instance a random position;
4. In the _draw method call the draw_multimesh to draw the generated multimesh (don't forget to pass a non-null texture!);
5. If you can't see nothing, save the scene, exit and enter again to load the tool script;
6. Toggle the visibility of the CollisionShape2D node to see how it affects the color of the drawed MultiMesh;
7. Try to give a random color to each instance too;
8. Move the CollisionShape2D to be after the Node2D, notice how the color from the MultiMesh is correct now.

**Minimal reproduction project:**

[Issue.zip](https://github.com/godotengine/godot/files/5927795/Issue.zip)

**Comment by ghsoares** [comment] 2021-02-04 18:51
I just found something that is causing this issue: VisualServer.canvas_item_add_rect and maybe the others VisualServer.canvas_item_add_*. I can't find the implementation in the source code, but if I call these methods on the _draw function, the color parameter will change how the other draw commands will look.

**Comment by Calinou** [comment] 2021-02-04 19:03
Can you try to reproduce this in [3.2.4RC1](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-1) which features 2D batching in GLES3?

**Comment by ghsoares** [comment] 2021-02-04 19:10
@Calinou 3.2.4RC1 still have the same issue. Changing the driver to GLES2 seens to fix this in both versions

**Comment by ghsoares** [comment] 2021-02-04 19:19
The only way to fix it right now is to add any VisualServer.canvas_item_add_* command that takes a white color as modulate, for example I used `draw_rect(Rect2(Vector2.ZERO, Vector2.ZERO), Color.white)` before the draw_mutlimesh to clear the previous draw command with a different color

**Comment by lawnjelly** [comment] 2021-02-05 08:40
I took a quick look last night. It shouldn't be affected by batching as multimesh isn't batched and is done the same as 3.2.3.

That said I couldn't really understand what the OP was suggesting is going wrong, perhaps some screenshots would help.

**Comment by ghsoares** [comment] 2021-02-05 13:51
@lawnjelly There is some screenshots:
This is the desired effect, some instances with each one a random color:
![image](https://user-images.githubusercontent.com/43936806/107041619-7d9f8780-679f-11eb-9457-be68e5399867.png)

This is the effect achieved when the CollisionShape2D draws the gizmo:
![image](https://user-images.githubusercontent.com/43936806/107041666-8db76700-679f-11eb-9465-00a0f6b723a0.png)

This is the effect achieved when I draw a rectangle with a red color with a bit of opacity:
![image](https://user-images.githubusercontent.com/43936806/107041861-c5261380-679f-11eb-9001-1121585e831c.png)

Now, if I the CollisionShape2D draws the gizmo, and I draw a rectangle, but before I draw the multimesh I use the fix I provided here: https://github.com/godotengine/godot/issues/45711#issuecomment-773545358, the effect is as desired:
![image](https://user-images.githubusercontent.com/43936806/107042081-16360780-67a0-11eb-9fb7-a6ada8d02a6f.png)

This is scene tree:
![image](https://user-images.githubusercontent.com/43936806/107042122-21893300-67a0-11eb-9462-b881c81a748b.png)

**Comment by ghsoares** [comment] 2021-02-05 13:53
@Calinou Can you provide me the link in the Godot repository to the VisualServer.canvas_item_add_multimesh implementation? I couldn't find it in the source code.

**Comment by Calinou** [comment] 2021-02-05 14:05
> Can you provide me the link in the Godot repository to the VisualServer.canvas_item_add_multimesh implementation? I couldn't find it in the source code.

It's only in the `3.2` branch as the `master` branch renamed VisualServer to RenderingServer (and made backwards-incompatible changes): https://github.com/godotengine/godot/blob/24cb60893f1dd428cffb43341d3791be0d734401/servers/visual/visual_server_canvas.cpp#L885-L898

**Comment by ghsoares** [comment] 2021-02-05 14:23
It seens that the CommandMultiMesh doesn't have a modulate property. Maybe the fix is to add a modulate property to use when drawing the multimesh.
https://github.com/godotengine/godot/blob/24cb60893f1dd428cffb43341d3791be0d734401/servers/visual/rasterizer.h#L819-L825

**Comment by lawnjelly** [comment] 2021-02-05 15:37
Ah I see it now - it only occur in the editor in your min reproduction project. Yes it looks like a state or one of the modulates is getting out of sync or not being set.

A quick step through suggested that the modulates were correct, but whether they were getting sent correctly to GL or the shader was set up correctly I don't know (I'm not really familiar with multimesh).

It seems to occur in 3.2.1 so it's quite an old bug.

These ones that rely on editor debug drawing to show up can be quite difficult and time consuming to track down. It's better to get them to reproduce in a min reproduction project that runs rather than in the editor itself .. as they are so many things drawing in the editor it can be difficult to find the culprit.

**Comment by clayjohn** [comment] 2021-02-05 16:48
I think all we need to do is reset the modulate property before the multimesh is drawn. 

So add:
```
glVertexAttrib4f(VS::ARRAY_COLOR, 1.0, 1.0, 1.0, 1.0);
```
Here:
https://github.com/godotengine/godot/blob/3e2e21434d5aee7c2ea5cff26a4bb5fd9c17ea68/drivers/gles3/rasterizer_canvas_gles3.cpp#L905

**Comment by ghsoares** [comment] 2021-02-05 17:03
> I think all we need to do is reset the modulate property before the multimesh is drawn.
> 
> So add:
> 
> ```
> glVertexAttrib4f(VS::ARRAY_COLOR, 1.0, 1.0, 1.0, 1.0);
> ```

It could be interesting if we could provide a modulate color to the draw command, as it's done in VisualServer.canvas_item_add_mesh.

**Comment by ghsoares** [comment] 2021-02-05 17:13
> Ah I see it now - it only occur in the editor in your min reproduction project. Yes it looks like a state or one of the modulates is getting out of sync or not being set.
> 
> A quick step through suggested that the modulates were correct, but whether they were getting sent correctly to GL or the shader was set up correctly I don't know (I'm not really familiar with multimesh).
> 
> It seems to occur in 3.2.1 so it's quite an old bug.
> 
> These ones that rely on editor debug drawing to show up can be quite difficult and time consuming to track down. It's better to get them to reproduce in a min reproduction project that runs rather than in the editor itself .. as they are so many things drawing in the editor it can be difficult to find the culprit.

This problem occur in the running game too. I'm using the gizmos from the CollisionShape2D as example, but anything that is drawed with some module color changes the multimesh color in the running scene also.

**Comment by akien-mga** [comment] 2021-04-28 15:02
Fixed by #47582.

**Closed by akien-mga** 2021-04-28 15:02 UTC
Labels: bug, topic:2d, topic:rendering
