### ISSUE TITLE
MultiplayerSynchronizer Not Syncing On Spawn or Sync

### ISSUE THREAD

**Issue by GregHilston** [godotengine/godot#64129] opened 2022-08-08 21:15 UTC
### Godot version

4.0.alpha12 & 4.0.alpha13

### System information

Windows 10

### Issue description

A sync variable is failing to synchronize from the server to the clients.

Here's some relevant output from the server:

```
network create_player creating new eastern Player with ID 664147086
player _ready position (50, 200)
player _ready sync_position (50, 200)
```

Here's some relevant output from a client:

```
player _ready position (0, 0)
player _ready sync_position (0, 0)
```

Notice how the expected `(50, 200)` that the server has proven its Player object has set to its `position` and `sync_position`? I expect this value to be set on the Client's side, but in actuality, the client has a `position` and `sync_position` value of `(0, 0)`.

Since I'm leveraging `MultiplayerSynchronizer`, I have the `sync_position` variable checked off for `Spawn` and `Sync`, I'd expect the Server's idea of that variable to sync to the clients.

### Steps to reproduce

1. Launch the server. There's a `run-server.bat` and `run-server.sh` script, both of which has absolute paths, that a quick modification can fix.
2. Launch two clients. One can do this using Godot itself, or use the `run-client.bat` or `run-client.sh` scripts, which once again have absolute paths.
3. Look at the output of the player's position on the server's console and compare it to the output from the player's console. Additionally, you'll see the two players have spawned in the same location, and not the intended locations. IE: First player on the left of the screen, second player on the right of the screen.

### Minimal reproduction project

[pong.zip](https://github.com/godotengine/godot/files/9285062/pong.zip)

Attached is the current state of my project. I'm aware this is not minified, but it should highlight the situation.

**Comment by jgillich** [comment] 2022-08-09 03:01
Your synchronizer authority is set to the client, that's why you can't set its values on the server. It's unfortunate that all examples do this currently, but the general recommendation for synchronizers is to always have them be server-controlled and handle player input using RPC.

**Comment by GregHilston** [comment] 2022-08-09 03:08
@jgillich I follow at a high level what your describing. This particular project means nothing to me, as I'm simply using it to learn.

So that I can better understand and potentially submit an updated example of multiplayer pong to the Godot examples repo, or as a blog post, can you walk me through how to resolve this particular issue? 

I'm happy to apply this knowledge to other areas in this project and close this issue.

Thanks again for your time

**Comment by cridenour** [comment] 2022-08-09 03:18
I think this is a different issue although @jgillich may be correct depending on the game.

The `MultiplayerSpawner` does not sync spawn variables from a nested `MultiplayerSynchronizer` (intentional?) 

By moving the `MultiplayerSynchronizer` out of the `Networking` node here, I'm able to get the expected logs. 

But then the `MultiplayerSynchronizer` won't update the `sync_position` on updates, maybe because of #62027

**Comment by jgillich** [comment] 2022-08-09 03:22
https://github.com/godotengine/godot/issues/62027 is already fixed in alpha13

**Comment by GregHilston** [comment] 2022-08-09 03:23
Interesting. Alright, so I should be able to use alpha13 to avoid #62027. 

And to follow suite with @jgillich 's first advice, I might want to leverage some code that looks like this in my Ball's `_ready` method?

```
# int constructor taking a string is currently broken :(
# https://github.com/godotengine/godot/issues/44407
# https://github.com/godotengine/godot/issues/55284
$Networking/MultiplayerSynchronizer.set_multiplayer_authority(str(name).to_int())
```

I don't have this working _just_ yet, but I believe I'm getting close.

**Comment by GregHilston** [comment] 2022-08-09 03:26
Interesting that I'm unable to recreate the expected logs that @cridenour is seeing when simply running Alpha 13. IE I have **not** rearranged the child/parent relationship of `MultiplayerSynchronizer` and `Networking` nodes

**Comment by cridenour** [comment] 2022-08-09 03:28
Rearranging the nodes **is** necessary - regardless of alpha 12/13. Once you make the Synchronizer a direct child of the scene spawned by the Spawner, it should sync that Spawn variable. 

I then encountered a 12-specific bug, but good to know that's already fixed.

**Comment by GregHilston** [comment] 2022-08-09 03:50
Ah, I understand what you're saying now.

I'm definitely running into an unexpected situation still. If I run my project with Godot 4 Alpha 12, I can see the paddles spawned on the server in the expected spots, which is great progress, but I'm unable to move the paddles.

if I run the very same project with Godot 4 Alpha 13, I can move the paddles, but they both were spawned with un-synced positions.
[pong.zip](https://github.com/godotengine/godot/files/9286598/pong.zip)

I haven't been able to debug this thoroughly, since moving the Synchronizer out, and making it a direct child of the scene, like you recommended. I've also failed to get the ball to move.

I can report back tomorrow, after I've had some time to continue to debug this.

_I've attached my updated project, in case either of you wanted to look_

**Comment by jgillich** [comment] 2022-08-09 03:57
@GregHilston Here's what I meant https://github.com/jgillich/godot-pong-64129/commit/5bb4903e924e264acfea87dbc4ac73600b070a33

You give the authority back to the server and send player inputs over RPC. This also makes it much harder to cheat. I haven't touched the ball, but the players spawn in the correct positions now. (tested on some recent master versions, but it should also work with alpha 13)

**Comment by cridenour** [comment] 2022-08-09 04:03
Haven't had a chance to test the latest project zip but even if you set the authority to the client in `_ready` the spawn variables should already be available and synced. That sounds like a regression between 12/13. 

Tomorrow I'll update my own project to 13 and see what I find.

**Comment by jgillich** [comment] 2022-08-09 04:15
> in _ready the spawn variables should already be available and synced

Is that how it's supposed to work? That wasn't entirely clear to me. :grinning:  In that case I agree, this may be a regression.

cc @Faless

**Comment by Faless** [comment] 2022-08-09 12:50
> Is that how it's supposed to work?

`Spawn` variables (not `sync`) are available in `_ready` you can check the following minimal project, which seems to work as expected in both alpha13 and latest master.

[proj_mp_spawn.zip](https://github.com/godotengine/godot/files/9290526/proj_mp_spawn.zip)

**Comment by GregHilston** [comment] 2022-08-09 14:25
@Faless ill test out the project you've sent on my end, both to verify it works and to see if I spot any differences in my project vs this one.

The sync variables that I'm referencing that are not sending clients the proper data are both spawn and sync variables.

**Comment by GregHilston** [comment] 2022-08-09 20:54
@Faless Opening your attached `proj_mp_spawn.zip` results in an error loading the `main.tscn` scene:

> Load failed due to missing dependencies
> res://main.gd

![proj-mp-spawn-error](https://user-images.githubusercontent.com/4227776/183759470-98649f3f-4e01-43c9-9bdb-d6cd0f9b7aae.PNG)

clicking:

> Open Anyway

seems to work. I'm able to run two instances of the main scene, press `Server` on the first one and `Client` on the second, and the debug output seems to be correct. Which I see leverages the `MultiplayerSpawner` in combination with the `@export var my_prop`.

So this leads me to my original situation, I'm still unsure why I'm unable to see the syncing work as expected on my end. Both initially and when it updates.

@cridenour, Please let me know if you end up running my latest project. 

I appreciate everyone's help here :)

**Comment by cridenour** [comment] 2022-08-10 14:48
@GregHilston so I ended up removing the Networking node and had the Synchronizer use the Player as the Root Path, which got the variables working at spawn. I then was seeing an issue where they were both the same position again - but that was because of a race condition in your player positioning logic. Moving the `players.append(id)` up to the top helped that.

Tested on 13 and all seemed to work as expected.

[pong.zip](https://github.com/godotengine/godot/files/9301023/pong.zip)

That still leaves one issue, that after testing I think I can reason into words.

@Faless Am I correct in saying a NetworkSynchronizer will not receive Spawn variables if it's **root path** is not the owner of the scene spawned with MultiplayerSpawner? Doesn't seem to matter where it is in the scene tree. Is that documented / intentional?

**Comment by GregHilston** [comment] 2022-08-10 18:47
@cridenour Thanks for sharing this zipped up project! I was able to see the left and right players (paddles) spawning at the expected position. To anyone following along, or someone reading this in the future, you'll have to fix a fewthings before the project runs:

1. convert all the spaces to tabs
2. comment out line 60 in networking.gd, which references a node that no longer exists (`print('network create_player we have set sync_position to %s ' % str(east_player_scene.get_node('Networking').sync_position))`)
3. update the `run-server.bat` and `run-client.bat`. I'd recommend modifying them to point to the current directory, like this `"G:\Desktop\godot\Godot_v4.0-alpha13_win64\Godot_v4.0-alpha13_win64.exe" --path "." --server` and this `"G:\Desktop\godot\Godot_v4.0-alpha13_win64\Godot_v4.0-alpha13_win64.exe" --path "."`, respectively.

@cridenour Just to be clear, you running this project on your machine did **not** sync the movement of the players(paddles) right? You were only concerned with spawning the paddles at the correct spot, right?

**Comment by cridenour** [comment] 2022-08-10 20:26
@GregHilston I had thought it was syncing but upon looking at my own zip, it's clearly not. Something strange is going on.

**Comment by GregHilston** [comment] 2022-08-11 02:45
@cridenour I think I solved my problem by seeing a difference in the `player.tscn` and `ball.tscn`, however I was misreading the files haha...

I'm going to upload my latest project. I've modified the game slightly, to make debugging easier. When the first player connects, their paddle is spawned off to the left. The player's position is *not* syncing. However, I am also spawning a ball, and it's position *is* syncing. I've gone through the project and as far as I can tell, I've attempted to do the position syncing the same. 

I'm uploading this in case you, or anyone else, has the bandwidth to download it and take a look as well.

[pong.zip](https://github.com/godotengine/godot/files/9305695/pong.zip)

**Comment by Faless** [comment] 2022-08-11 07:17
> Am I correct in saying a NetworkSynchronizer will not receive Spawn variables if it's **root path** is not the owner of the scene spawned with MultiplayerSpawner?

@cridenour yes, for spawn variables to work the **root path** must be the owner of the scene being spawned by the MultiplayerSpawner.

It's something I'm not really sure we can change without degrading performance during spawn, though it's worth investigating and definitely should be clarified in the documentation in the meantime.

**Comment by cridenour** [comment] 2022-08-11 15:59
@Faless I think the limitation makes sense, just need to surface that more. Docs for sure and maybe a runtime (or editor warning) when the root path isn't the owner and was spawned by a Spawner (only known at runtime I guess). 

If there's interest I could look at doing a PR for that.

**Comment by GregHilston** [comment] 2022-08-11 18:29
I'm still thinking there's either a user error, of my doing, or a misunderstanding of the sync_variables at play here. If anyone has the bandwidth to continue to look into that with me, that'd be great.

As I still haven't been able to figure out how to get a second sync variable to sync.

**Comment by GregHilston** [comment] 2022-08-11 19:27
I have yet another update. I have two versions of the project here. `pong.zip` and `pong-two.zip`. The former is the most recent version of the project and does **not** sync the Player (paddle)'s position. The latter is an older commit, but **does** sync the Player (paddle)'s position.

I for the life of me cannot see why the older project is working, while the newer project is not.

If anyone is willing to try to point out to me what I was doing right, and am currently not doing right, that will be the final stake in coffin for this issue.

As always, super appreciative of everyone's time.

current project, paddles/players position do not sync from client to server or other clients
[pong.zip](https://github.com/godotengine/godot/files/9311496/pong.zip)

older commit of project, where paddles/players position **do** sync from client to server and other clients
[pong.zip](https://github.com/godotengine/godot/files/9311498/pong.zip)

**Comment by GregHilston** [comment] 2022-08-12 13:55
I've made some progress, but haven't solved this just yet. I'm convinced I'm setting the multiplayer authority wrong for my players.

I believe this is why the ball syncs no problem, as the server is the authority on that object.

The players however, are each supposed to be their own authority. So I need to figure out how to correctly set the authority of the players when they connect, then have the multiplayer spawner spawn these players to the clients, with the correct authority. Then have the players check for authority correctly.

**Comment by GregHilston** [comment] 2022-08-12 19:27
Interesting. So I was able to get the syncing of the player paddle to work by moving the `@export sync_position` from the root node, down to a Node called `Networking`.  _I was originally doing this, but it was recommended to remove this, as there was a bug where synced variables could not be on the root._

What's interesting now is that we're failing to be able to modify the Player's position before spawning them. 

So I'm seeming able to get my project into two exclusive states:

1. Get the player 's position to sync, but unable to set its original spawn location
2. Be unable to sync the player's position, but be able to set the player's original spawn location...

Example 1 zipped up here:
[pong.zip](https://github.com/godotengine/godot/files/9329075/pong.zip)

**Comment by GregHilston** [comment] 2022-08-14 05:12
i have not been able to make more progress on recreating my scene's issue. I sat down to make a minimum project to see if I could demonstrate what Im experiencing, and yet my minimum project works as expected...

I'll give up on this endeavor in a few days, and we can close this issue ha

**Comment by GregHilston** [comment] 2022-08-24 23:44
Hi all, I'm going to stop trying to solve this issue, as I've spent more time than I care to admit trying to figure this out.

I'll either give RPCs a try and or patiently wait till Beta is released.

Your guys' call if we close this ticket or not. I know I'm not the only one experiencing this, as another @cridenour was experiencing it above

> @GregHilston I had thought it was syncing but upon looking at my own zip, it's clearly not. Something strange is going on.

But my pong project might just have a specific unique incorrect implementation or configuration. Thanks everyone!

**Comment by cridenour** [comment] 2022-08-24 23:57
> as another @cridenour was experiencing it above

To be fair, it's only in your attached project. My own project uses MultiplayerSynchronizers extensively, including Spawn variables, without issue. I would like to know why but I don't have enough bandwidth to debug the exact reason this setup doesn't work.

**Comment by GregHilston** [comment] 2022-08-25 01:26
@cridenour Oh yeah, apologies if my comment above came off different than I intended. I was trying to express that this _seems_ to be very much a *me* problem, and perhaps this issue being up is of little use to everyone else.

Don't get me wrong, I'd be grateful to understand why this is happening, as I'm only making this Pong project for learning, but I don't know if the Godot project will benefit by having this issue still up. 

Hope that clarifies.

**Comment by Faless** [comment] 2022-10-03 00:41
@GregHilston I had some time to debug the project using Godot 4.0 beta 1.
There is a small error in the MRP: the `spawn_path` of the `BallMultiplayerSpawner` in `network.tscn` is not correctly set to the `Balls` node. Fixing that, results in the ball spawning correctly.
Additionally, I noticed that the `ball.tscn` scene was loading an inline gdscipt instead of the `ball.gd`. Changing it to use the `ball.gd` script resulted in a moving ball (properly syncing).
Attached the fixed project: [pong.zip](https://github.com/godotengine/godot/files/9693906/pong.zip).
Closing, as this seems to be just a small configuration error.

**Closed by Faless** 2022-10-03 00:41 UTC
Labels: documentation, topic:network, topic:multiplayer

**Comment by GregHilston** [comment] 2022-10-03 02:35
@Faless

What a pleasant surprise. Thanks for taking time out of your day to sit down and help me review my code. I did stop pursuing multiplayer endeavors when i was unable to resolve this issue, so thank you very much.

I'll end up downloading your project and fixing my project with the notes you've provided.

Have a great week!

**Comment by GregHilston** [comment] 2022-10-06 20:39
@Faless I sat down to run the project of mine that you modified again, and I realize that one thing that wasn't fixed is the Player's networking sync_position is still not propagating from the server to the clients. Did you have any discovery on that?

**Comment by Faless** [comment] 2022-10-06 21:13
You synchronize `sync_position` via a synchronizer which has the client's authority, so it won't sync from the server to the client, but from the client to the server (and other clients when server relying is supported).

**Comment by tateorrtot** [comment] 2023-07-16 03:56
Still experiencing my clients not being able to sync to my host. Is this behaviour of having to use RPCs to sync to thee server intended or am I just dumb and misunderstanding?

**Comment by Nuxij** [comment] 2023-09-27 17:31
I have this issue. I tried this:

`@export var initial_position`

```
player = packedscene.initiate()
# player.global_position = spawn_point.global_position # doesn't work
player.initial_position = spawn_point.global_position
spawn_root_path.add_child(player)
```

I see them spawn in the right location on the server game and then the client player jumps off to 0,0.

I print `initial_position` in `player._ready()` where I suppose it should be available and it's set to `(0,0)`.

I'm also about to try RPC but it seems a bit heavy when the spawner should just respect the initial position I set?

**Comment by GregHilston** [comment] 2023-09-27 17:44
If I recall correctly, I never solved this. I learned that the initial
position is not respected by clients...

If you solve it, I'd be very interested in how. Especially if it doesn't
use the rpc approach

**Comment by cridenour** [comment] 2023-09-28 04:56
The best way to handle this IMO is with a custom spawn function. 

```gdscript
extends MultiplayerSpawner

@export var player: PackedScene

func _init() -> void:
  spawn_function = _spawn_custom

func _spawn_custom(data: Variant) -> Node:
  var scene: Player = player.instantiate() as Player
  scene.peer_id = data.peer_id
  scene.initial_transform = data.initial_transform
  # Lots of other helpful init things you can do here: e.g.
  scene.is_master = multiplayer.get_unique_id() == data.peer_id
  scene.get_node('PlayerNetworking').set_multiplayer_authority(data.peer_id)

  return scene
```

Then call it with 

```gdscript
$PlayerSpawner.spawn({ 'peer_id': peer_id, 'initial_transform': spawn_point.global_transform })
``` 

and read it in Player with 

```gdscript
var is_master: bool
var initial_transform: Transform3D

func _ready() -> void:
  if is_master:
    global_transform = initial_transform
```

**Comment by olivatooo** [comment] 2023-10-02 16:32
THANK YOU SO MUCH! This is the only place that I found an example of _spawn_custom in godot 4

**Comment by cridenour** [comment] 2023-10-02 23:37
> THANK YOU SO MUCH! This is the only place that I found an example of _spawn_custom in godot 4

Ah right. That's because the API changed in the betas. Used to need a custom script on the spawner itself and a special `_spawn_custom` but now it's just a callable you set on the spawner. The `_init` function I used is just a way of restoring the previous behavior (since my game already used it). 

This now could be done in a parent script by setting `$MultiplayerSpawner.spawn_function = my_spawn_function` and define `my_spawn_function` as we do `_spawn_custom`. No custom MultiplayerSpawner script required, though there's nothing wrong doing it the way I do above.
