### ISSUE TITLE
glTF tree hierarchy doesn't respect Blender collections

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50790] opened 2021-07-23 20:28 UTC
### Godot version

v4.0.stern-flowers.331.custom_build [471aae3b7]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

The tree structure in blender:
![image](https://user-images.githubusercontent.com/58845030/126837873-b1af9d42-fa3d-4822-b704-d432e39f0959.png)

The tree structure in godot:
![image](https://user-images.githubusercontent.com/58845030/126837950-978695d5-b246-4f18-b092-1e287dd66906.png)

As you can see, godot doesnt respect the hierarchy, which each collection should be a empty `Node3D` This will make easier to organize things during development!

### Steps to reproduce

* Create various collections in blender
* Export to GLB
* Import inside godot

**Comment by pycbouh** [comment] 2021-07-23 21:06
Collections in Blender are not the same as a tree hierarchy, their contents is not guaranteed to be unique (multiple collections can have the same object). They are more like tags. So I’m not sure this is possible.

**Comment by nonunknown** [comment] 2021-07-23 21:11
but how to organize the tree then?

**Comment by pycbouh** [comment] 2021-07-23 21:48
> Also I dont know if having same object in 2 collections is possible, it really is?

Yes, press <kbd>Shift + M</kbd>


https://user-images.githubusercontent.com/11782833/126844669-3e87aebf-a0a9-4bde-90e5-796ba1b12aac.mp4


-----
> but how to organize the tree then? 

Using parenting and empties maybe?

**Comment by nonunknown** [comment] 2021-07-23 22:04
Interesting, does blender has something like a unique ID for each object? this way the glb importer from godot can detect duplicates!

**Comment by pycbouh** [comment] 2021-07-23 22:07
> Interesting, does blender has something like a unique ID for each object?

All names (for both collections and objects) must be unique, as far as I know. If you name something with a name that is already taken, the other object will be renamed as "name.001", "name.002", etc.

> this way the glb importer from godot can detect duplicates!

I guess, but would that be the expected behavior for everyone?

**Comment by nonunknown** [comment] 2021-07-23 23:05
well, if not then this can be a boolean in the import settings!

**Comment by fire** [comment] 2021-07-24 02:42
Not sure what things I can do without patching Blender gltf2 export. I'm out of ideas.

**Comment by nonunknown** [comment] 2021-07-24 10:32
@fire do you think what about having an old approach back? remember when godot has a better collada addon for blender, maybe a blender plugin for exporting .glb/.gltf which supports godot?

**Comment by fire** [comment] 2021-12-06 19:26
See https://github.com/KhronosGroup/glTF-Blender-IO/issues/1456 for recent news.

**Comment by andyp123** [comment] 2021-12-27 02:03
If the glb file is later able to contain data about Blender's collections, I don't think they should be used to change the imported scene hierarchy, because as @pycbouh points out, they are meant for scene organization and grouping objects.

Godot has EditorScenePostImport, which could potentially be used to import and organise scenes differently based on collections and other metadata, and I think that arranging an imported scene differently to what is standard should be handled there.

**Comment by fire** [comment] 2022-01-04 22:46
Since this is physically not in the gltf file. I don't think it will be supported in Godot Engine.

You can put it in the gltf file but it isn't Godot's exporter.

Proposing to close.

**Comment by SwatDoge** [comment] 2023-09-21 08:27
For anyone interested, me and a friend made a workaround using blender empties:

[https://github.com/SwatDoge/DQBCTEGS](https://github.com/SwatDoge/DQBCTEGS)

We don't really care about the technicalities, we need the hierarchy sorting for our workflow.

**Comment by lgxm3z** [comment] 2024-03-27 16:30
Blender (**4.1.0**) has a new glTF export option "**Full Collection Hierarchy**"
(https://github.com/KhronosGroup/glTF-Blender-IO/issues/1456)

![image](https://github.com/godotengine/godot/assets/28831375/6e58ca7f-63fd-4c5d-ab62-d12b6d40c4d7)

<br/>


Unfortunately, this still has some bugs like: https://github.com/KhronosGroup/glTF-Blender-IO/issues/2175

**Comment by lgxm3z** [comment] 2024-04-10 09:43
I think this issue can now be closed...

@nonunknown

**Comment by akien-mga** [comment] 2024-04-10 11:39
Closed as fixed in Blender 4.1.0.

**Closed by akien-mga** 2024-04-10 11:39 UTC
Labels: enhancement, topic:import, topic:3d
