### ISSUE TITLE
.import & .godot folder not hidden on Windows

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#58657] opened 2022-03-01 16:08 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

The .import & .godot folders are not hidden on windows, but hidden on linux and osx...
- if they are meant to be hidden they should be hidden everywhere?
- other 'hidden' folders like .git are hidden on windows?

### Steps to reproduce

- make new project on windows and git init
- .git is hidden but .import is not (even though it is on other systems)

**Comment by Calinou** [comment] 2022-03-01 16:24
Duplicate of https://github.com/godotengine/godot-proposals/issues/801. This is not a bug, this is standard OS behavior which Godot doesn't aim to override.

**Closed by Calinou** 2022-03-01 16:24 UTC
