### ISSUE TITLE
Invalid signal on pass as parameter

### ISSUE THREAD

**Issue by iiiron** [godotengine/godot#100527] opened 2024-12-17 19:36 UTC
### Tested versions

- godot 4.3 stable

### System information

develop env

### Issue description

I reproduced it with minimal code [signalbugtest.zip](https://github.com/user-attachments/files/18170447/signalbugtest.zip)

signal param not available when specific parameters are not passed. 

![Image](https://github.com/user-attachments/assets/696b50ce-22eb-4e11-9255-93660e7794f9)

![Image](https://github.com/user-attachments/assets/e798afaf-de4f-48ae-988c-1c54525da8b7)

![Image](https://github.com/user-attachments/assets/2b1261e4-6c2f-4454-a8c2-0646f6929b10)

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by matheusmdx** [comment] 2024-12-19 00:26
I did some tests and i think this is not a bug, the `StepDeal` refcount object created in the `_ready` function is simple being deleted because is going out of scope before the lambda use the signals passed and that makes the signals be invalid as well. I put some prints in the mrp and that's the result:

```
StepDeal.then func called, deal param = <anonymous lambda>(lambda)
Lambda, awaiting 1 second...
_ready callback end. # Printed at the end of _ready function in the node2d script
Parameter A: RefCounted(step_deal.gd)::[signal]_deal_done
Parameter B: <RefCounted#-9223372008752937719>
--------------
Lambda, awaiting 1 second...
StepDeal object out of scope, deleting... # Printed in the StepDeal script when receives NOTIFICATION_PREDELETE
Parameter A: null::[signal]_deal_done
Parameter B: <null>
--------------

```
> signal param not available when specific parameters are not passed.

The reason why this happens is because when you pass `self` together with the signal, you're keeping the refcount alive and this keeps the object valid, basically the only "valid" parameter in this case is the `self` that keeps a reference from your `StepDeal` object. You can simple solve that by moving the `StepDeal` object creation outside the `_ready` scope and keeping in the script scope like this:

```
extends Node2D

var deal = StepDeal.new() # Always valid until the node be deleted, so never go out of scope before the time

func _ready() -> void:
	deal.then(func(a: Signal, b = null):
		print("Lambda, awaiting 1 second...")
		get_tree().create_timer(1).timeout.connect(func():
			print("Parameter A: ", a)
			print("Parameter B: ", b)
			print("--------------")
			a.emit()
		)
		return a
	)
	deal.start()
	print("Ready end")

```

Which prints:

```
StepDeal.then func called, deal param = <anonymous lambda>(lambda)
Lambda, awaiting 1 second...
Ready end
Parameter A: RefCounted(step_deal.gd)::[signal]_deal_done
Parameter B: <RefCounted#-9223372008803269370>
--------------
Lambda, awaiting 1 second...
Parameter A: RefCounted(step_deal.gd)::[signal]_deal_done
Parameter B: <null>
--------------
Deal done
```

**Comment by iiiron** [comment] 2024-12-19 06:23
Thank you! I also realized last night that this is a memory management issue. 

It was my lack of understanding of GDScript that caused me to not comprehend what was happening in the code. Thank you for your explanation.

**Closed** 2024-12-19 06:24 UTC
Labels: topic:gdscript, needs testing
