### ISSUE TITLE
Failed to compile for Alpine/musl target

### ISSUE THREAD

**Issue by Uniformbuffer3** [godotengine/godot#63978] opened 2022-08-05 22:17 UTC
### Godot version

v4.0.alpha.custom_build [9f408aef4]

### System information

Alpine linux 3.16, Intel N6005

### Issue description

Hi, i was trying to compile Godot 4 (master) on an Alpine machine and it compiles correctly until the last linking phase when it throws this error:
```
[ 96%] Linking Program bin/godot.linuxbsd.tools.64 ...
[100%] progress_finish(["progress_finish"], [])
[100%] /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: platform/linuxbsd/crash_handler_linuxbsd.linuxbsd.tools.64.o: in function `handle_crash(int)':
/home/*****/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56: undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/*****/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:81: undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.tools.64] Error 1
scons: building terminated because of errors.
```

On the Godot compiling guide are reported the necessary dependencies to build on Alpine, so i suppose it is a supported system, otherwise i'm sorry for the noise.

Thanks for the dedicated time, have a good day.

### Steps to reproduce

Just compile Godot targetting/on a musl machine.

**Comment by Calinou** [comment] 2022-08-06 02:16
Duplicate of https://github.com/godotengine/godot/issues/57193.

**Closed by Calinou** 2022-08-06 02:16 UTC
