### ISSUE TITLE
Import tab losses functionality when tab location is changed.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#10414] opened 2017-08-18 04:09 UTC
**Operating system or device - Godot version:**
Windows 10 x64 Godot Alpha1

**Issue description:**
If you change the location of the import tab, all of its functionality gets lost until the editor is restarted.

**Steps to reproduce:**
pick a different location to have the import tab besides the default. all import settings becomes lost.

**Link to minimal example project:**
so much for editor customization for now.

**Comment by akien-mga** [comment] 2018-01-08 13:00
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment] 2018-09-05 20:35
The import tab is here:
May have to do with something going on in ENTER/EXIT tree - 
https://github.com/godotengine/godot/blob/master/editor/import_dock.cpp

**Comment by Mr-Slurpy** [comment] 2018-09-26 04:44
Unless I'm misunderstanding something, I can't seem to reproduce this bug. Running commit 8fc92ae86faed72c402e7770246ed18d50b5c43b

Although I did seem to run into a different problem where after reimporting an asset the importer would select an asset I previously selected. Not a big deal though since I could just reselect the asset I want.

**Comment by akien-mga** [comment] 2018-10-05 07:11
Assuming fixed then, thanks for checking.

**Closed by akien-mga** 2018-10-05 07:11 UTC
Labels: bug, hero wanted!, topic:editor
