### ISSUE TITLE
Numpad 3D shortcuts only work with numlock on

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#52546] opened 2021-09-10 18:03 UTC
### Godot version

3.4.beta4

### System information

Windows 10 Lenovo IdeaPad Flex, keyboard is logitech

### Issue description

Keyboard shortcuts for 3D like numpad 5 to switch orthogonal do not work unless numlock is on.

### Steps to reproduce

1. Turn numlock off
2. press 5 on the numpad
3. turn numlock on
4. press 5 on the numpad

**Comment by Calinou** [comment] 2021-09-10 18:39
If you create an `_input(event)` function and `print(event)` inside, do you get anything printed when you press numpad keys with numlock disabled in the Output panel?

I wonder if Godot can even "see" the key presses here.

**Comment by ShatReal** [comment] 2021-09-10 19:08
Yes, the event gets printed out.

**Comment by Calinou** [comment] 2021-09-10 19:32
I guess this can be fixed by assigning a second shortcut by default once https://github.com/godotengine/godot/pull/51273 is merged.

**Comment by EricEzaM** [comment] 2021-09-21 02:45
I am quite confident this is 100% expected and correct. The shortcuts are for Keypad numbers.

The whole point of numlock is that is switches between two different functionalities of the numpad. See below from [this site](https://www.computerhope.com/jargon/n/numlock.htm).
![image](https://user-images.githubusercontent.com/41730826/134103827-004b70b5-ae54-46e8-a455-ee867d8307a3.png)
In Godot, make a script with `func _input(event): print(event.as_text)` and with numlock on it will print numbers (KP_8, etc), and with numlock off, it will print home, pageup, end, UNKOWN, etc (for 7, 9, 1, and 5 respectively).

**Comment by akien-mga** [comment] 2021-09-21 07:56
Indeed, that's expected behavior. We could handle both events for the 3D shortcuts but I don't see much point doing so, as it may conflict with existing shortcuts, or prevent users from using those keys for their own shortcuts.

**Closed by akien-mga** 2021-09-21 07:56 UTC
Labels: discussion, topic:editor, topic:input, topic:3d

**Comment by Calinou** [comment] 2021-09-21 14:15
> We could handle both events for the 3D shortcuts but I don't see much point doing so, as it may conflict with existing shortcuts, or prevent users from using those keys for their own shortcuts.

If https://github.com/godotengine/godot/pull/51273 is merged, we can support this out of the box while allowing users to customize both shortcuts.

**Comment by Calinou** [comment] 2021-11-11 18:41
For future reference, I can't reproduce this issue on `master` on Linux (using the `fr-oss` keyboard layout). So this appears to have been resolved indirectly somehow.
