### ISSUE TITLE
cannot use covariant types as return types in overridden methods in scripts

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#76143] opened 2023-04-16 19:43 UTC
### Godot version

4.0.2.stable

### System information

windows 10

### Issue description

gdscript does not allows usage of covariant types in return types of overridden methods. In other words, an overridden method cannot change the return type of the method to a more specific type, one that inherits from the type being returned in the parent implementation of the method.

### Steps to reproduce

in a new or existing project, put the code bellow in a script
```gdscript
class A:
	func f()->Object: return null
class B extends A:
	func f()->Node: return null
```
and see the error pop up

![image](https://user-images.githubusercontent.com/5783414/232337940-bcf229a3-ddec-4b44-8cf8-542f412b210e.png)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-04-16 19:46
Not a bug, just how virtual functions work in GDScript, this is proposal territory if one doesn't already exist

**Comment by Gnumaru** [comment] 2023-04-16 19:48
I'm sorry. I didn't knew this was the intended design.

**Comment by AThousandShips** [comment] 2023-04-16 19:51
As far as I recall at least, don't see anything explicit stated in the documentation about this being supported, and isn't necessarily always so

**Comment by AThousandShips** [comment] 2023-04-16 19:55
Also duplicate of #72403

**Comment by KoBeWi** [comment] 2023-04-16 20:41
Closing as duplicate.

**Closed by KoBeWi** 2023-04-16 20:41 UTC
