### ISSUE TITLE
Application stops responding upon calling SceneTree.Quit and never really quits

### ISSUE THREAD

**Issue by HKunogi** [godotengine/godot#96978] opened 2024-09-13 20:30 UTC
### Tested versions

- Reproducible on v4.4.dev.mono.custom_build [74de05a01c8716a42d4e3427f607d7bea76b35e5] when using Run on Separate Thread for either or both of the physics (2D/3D)

### System information

Windows 11 x64 and Ubuntu 24.04 ARM64

### Issue description

When calling the SceneTree.Quit, instead of correctly quitting the application, instead, the application stops responding and does not actually quit, it stays lingering into an non-responsive state, may it be running from console only or with actual UI, as long as "Run on Separate Thread" is ticked on either of the physics (2D and/or 3D).

### Steps to reproduce
- Enable Run on Separate Thread on project settings
- Simply call SceneTree.Quit

### Minimal reproduction project (MRP)

[mrp-quitbug.zip](https://github.com/user-attachments/files/16999018/mrp-quitbug.zip)

**Comment by matheusmdx** [comment] 2024-09-13 22:43
Bisecting points to commit 2d1dd41ef5dcb51ddb607ba572e63b605b9191be from pr #96760 as the culprit

![image](https://github.com/user-attachments/assets/da0de3c4-abf4-447e-95f5-a299d0452c88)

<br>

We had a similar issue #96931 with a pr to fix: #96959 but only talks about Rendering and Script server so just to make sure, @RandomShaper pr #96959 also works for this case?

**Comment by CedNaru** [comment] 2024-09-13 23:07
That PR will work on anything that runs on the WorkerThreadPool, which includes the physic servers too.

**Comment by clayjohn** [comment] 2024-09-16 16:40
This is indeed a duplicate of https://github.com/godotengine/godot/issues/96931 and will be fixed by #96959

**Closed** 2024-09-16 23:05 UTC
Labels: bug, topic:physics, regression
