### ISSUE TITLE
Menu's become new windows and other windows exit as soon as mouse leaves

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#39596] opened 2020-06-16 13:15 UTC
**Godot version:**

V4.0.dev.custom_build.bc5ba1c26

**OS/device including version:**
GTX760, Arch Linux LTS with i3 window manager.

**Issue description:**
When hovering over a menu, a whole new window suddenly opens instead.
![IMG_20200616_220747](https://user-images.githubusercontent.com/56970759/84826084-63246c80-b05d-11ea-8d99-b269c98d310a.jpg)
The log doesn't give any error, but it keeps saying the usual "_window_changed"

The annoying part is that the editor keeps going 50% of my screen for a split second because my mouse went over something that tried to open an entire new window. But everytime when I try to go with my mouse inside of the new window to click on a menu item, it just decides to close it instead. Even ctrl+s opens an entire window, taking up 50% of my screen, and same thing with other windows that open like that, the moment my mouse enters or leaves that window, it closes.

What I expect is that such things open within the engine instead of an entire new window, because with i3, that means taking half of your screen.

**Steps to reproduce:**
Use Arch Linux-lts, latest version together with i3 window manager and compile the version of Godot of how it is right now in git. I also had this issue when using the godot-git aur. 

Edit: Dragged in the picture

**Comment by Anutrix** [comment] 2020-06-16 14:21
@voylin The link is kinda broken markdownwise. Try dragging the image directly into the Github issue instead of using GDrive.

**Comment by voylin** [comment] 2020-06-16 21:10
> @voylin The link is kinda broken markdownwise. Try dragging the image directly into the Github issue instead of using GDrive link.
> 
> Related to or duplicate of #37930.

It may be a duplicate but it looks like for him it takes up his entire screen, that's why I thought it may be better to open a new issue. If this turns out to be the exact same issue, please close this one. 

For now, I can fix this by the single window option in the editor. This seem to be working without any troubles so far.

**Comment by mrushyendra** [comment] 2020-06-16 23:53
Could be added to #37734?

**Comment by akien-mga** [comment] 2020-06-17 09:08
> Could be added to #37734?

Done.

**Comment by Riteo** [comment] 2020-07-22 01:20
> > @voylin The link is kinda broken markdownwise. Try dragging the image directly into the Github issue instead of using GDrive link.
> > Related to or duplicate of #37930.
> 
> It may be a duplicate but it looks like for him it takes up his entire screen, that's why I thought it may be better to open a new issue. If this turns out to be the exact same issue, please close this one.
> 
> For now, I can fix this by the single window option in the editor. This seem to be working without any troubles so far.

This is a duplicate. It took up their entire screen because probably of some other thing they did(maybe set the window to floating, or maybe moved it to another session?), but the original issue gave me the same effects as this one.

**Comment by akien-mga** [comment] 2020-07-22 07:41
Closing as duplicate of #37930 then.

**Closed by akien-mga** 2020-07-22 07:41 UTC
Labels: bug, topic:core
