### ISSUE TITLE
Godot v3.1-rc A Breakpoint outside a loop will be interrupted in each iterative process of this loop

### ISSUE THREAD

**Issue by JustusPan** [godotengine/godot#26864] opened 2019-03-10 06:16 UTC
**Godot version:**

Godot v3.1.rc1.official

**OS/device including version:**

Dell XPS 13
i7-7560U
iris 640

**Issue description:**

A Breakpoint set after a loop will be interrupt during looping process.

**Steps to reproduce:**
open minimum project and set breakpoint as shown below, then press F6
```  
extends Node2D

func _ready():
	
	for i in range(3):
		 print(1)

	print("break_each_loop_process_here") <----------set bk here and it will be interrupt 4 times
	print("break_after_loop_finish")
	pass
	
func _process(delta):
	for i in range(3):
		 print(1)

	print("break_each_loop_process_here") <----------set bk here and it will be interrupt 4 times each frame
	print("break_after_loop_finish")
```  

**Minimal reproduction project:**

[godot_v3.1-rc1_breakpoint_issue.zip](https://github.com/godotengine/godot/files/2949121/godot_v3.1-rc1_breakpoint_issue.zip)

**Comment by JustusPan** [comment] 2019-03-10 06:24
**Supplement**
if I use "breakpoint" keyword instead, it works as expectation.
This issue will only be encountered when I set a breakpoint by mouse clicking on the head of editor line.

**Comment by groud** [comment] 2019-03-10 08:11
Related, if not duplicate of #26789

**Comment by akien-mga** [comment] 2019-03-10 10:14
Duplicate of #26789 indeed.

**Closed by akien-mga** 2019-03-10 10:14 UTC
