### ISSUE TITLE
Vulkan: Subsurface scattering artifacts

### ISSUE THREAD

**Issue by gitscher** [godotengine/godot#57158] opened 2022-01-24 22:11 UTC
### Godot version

Godot 4.0 alpha 1 

### System information

Windows 10 64bit Vulkan GeForce RTX 3080 Treiberversion 511.23

### Issue description

![Subsurf_Scatter](https://user-images.githubusercontent.com/94169968/150871092-5cacb7e9-687b-4195-9425-fcd824636052.png)
No artifacts 
#

![Subsurf_Scatter2](https://user-images.githubusercontent.com/94169968/150871104-09c34ee5-e33c-4f3a-9ec2-af3c19a69890.png)
zoom out or rotate display arise Artifacts 
#

![Subsurf_Scatter3](https://user-images.githubusercontent.com/94169968/150871108-18b28450-2859-4f61-9987-b3f969593b9c.png)
materials such as refraction with subsurface scatter also contain
Artifacts 
#

![Subsurf_Scatter4](https://user-images.githubusercontent.com/94169968/150871116-214d5b80-67e3-4e50-98ff-abd8d89b693b.png)
objects with subsurface scatter that are in the foreground and transparent objects with subsurface scatter in the background also produce Artifacts 
#

![Subsurf_Scatter5](https://user-images.githubusercontent.com/94169968/150871127-aa51164f-27c8-4dce-85a9-13a8a2bbb158.png)
x and y and z axes are rendered black
#

![Subsurf_Scatter6](https://user-images.githubusercontent.com/94169968/150871133-a50f08dc-531d-4cdc-86ba-79dcca48c006.png)
Object with transmittance is not completely displayed on the ground. Only a quarter.
#

### Steps to reproduce

start projeckt and move camera viewport and then the flickering starts when rotating or zooming.

### Minimal reproduction project

[Subsurf Scatter.zip](https://github.com/godotengine/godot/files/7929221/Subsurf.Scatter.zip)

**Comment by Calinou** [comment] 2022-01-24 22:14
> Uploading Subsurf Scatter.zip…

The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

**Comment by gitscher** [comment] 2022-01-24 22:27
[Subsurf Scatter.zip](https://github.com/godotengine/godot/files/7929238/Subsurf.Scatter.zip)

**Comment by mrjustaguy** [comment] 2022-01-25 15:14
Hm yes, I've seen something like this when I moved from a Quadro K2000 to a GTX 1050 TI a few days ago in one of my projects... I didn't think much of it as it looked like it could have been messed up Shader Cache but I guess it wasn't.. Sadly don't have it available to me anymore...

Someone on a GTX 600 series GPU or 700 Series (Make sure it's Kepler based GPU) should open this to see if they can reproduce, and AMD GPUs should be tested, as this might be specific to Newer Nvidia GPUs.

**Comment by AlfonsoGrimaldo** [comment] 2022-01-25 18:44
On my GTX 960 Maxwell architecture it seems to work a bit better.
![Screenshot](https://user-images.githubusercontent.com/48926464/151035904-f5784b4d-daff-4ed4-a503-4bf1026cedb8.jpg)
The box doesn't seem to present many problems.
![Screenshot2](https://user-images.githubusercontent.com/48926464/151037251-5fbd4c3d-84fd-497e-9196-5b8c96b5295c.jpg)
![Screenshot3](https://user-images.githubusercontent.com/48926464/151037272-55b851bb-ebc8-4520-ba11-add50d92c69c.jpg)
But, objects present artifacts and overlap.
![Screenshot4](https://user-images.githubusercontent.com/48926464/151038304-fce707d0-32bb-4576-8832-1333cfa7c81d.jpg)

**Comment by gitscher** [comment] 2022-01-30 15:51
![Subsurf Scatter](https://user-images.githubusercontent.com/94169968/151706626-d2a4627b-4963-459c-89b4-beeb42dfd370.png)

with the AMD Radeon RX 5700 graphics card it works without artifacts. Driver version 21.10.2

#
![Subsurf Scatter2](https://user-images.githubusercontent.com/94169968/151706633-e75044fe-be89-4da0-9377-c3185eedf1b4.png)
but this is still the same. Object with transmittance is not completely displayed on the ground. Only a quarter.

**Comment by gitscher** [comment] 2022-03-31 09:51
![Subsurface4 0Alpha5](https://user-images.githubusercontent.com/94169968/161026387-4385b091-5604-453a-bf3d-4e257051fc68.png)
Windows 10 64bit Vulkan GeForce RTX 3080 Godot 4.0 alpha 5

The objects do not have artifacts and overlaps on the ground.
With Transparency Mode Alpha Scissor it works best with the Alpha 5 version. The other is still the same.

[Subsurf Scatter.zip](https://github.com/godotengine/godot/files/8388136/Subsurf.Scatter.zip)

**Comment by gitscher** [comment] 2022-07-10 09:13
![Unbenannt](https://user-images.githubusercontent.com/94169968/178138617-7feaf823-fa95-4e02-940e-8af04f8b1b24.png)

no more subsurface scattering artifacts with Godot 4.0 alpha 11

**Comment by Calinou** [comment] 2022-07-10 16:25
Closing per the above comment.

**Closed by Calinou** 2022-07-10 16:25 UTC
Labels: bug, topic:rendering, topic:3d
