### ISSUE TITLE
Input is not recognized when exporting, even if inside the editor the input works.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#25394] opened 2019-01-27 23:24 UTC
Hi, I made this small tool, but It seems the input is not recognized, neither as keyboard presses nor the GUI button signal when exporting.

I attach the project.

[ChordProject.zip](https://github.com/godotengine/godot/files/2800894/ChordProject.zip)

EDIT : This is a converted project from the 3.0 build initally. (Made initially on 3.0 then reopened with the beta version).

Input works fine on projects made directly from beta version, it seems it doesn't get properly updated when opened with the beta version.

EDIT: The input works when exported from a 3.0 version (I ported my files from 3.1 beta project to the old 3.0 project).

**Comment by eon-s** [comment] 2019-01-28 10:46
Example project works fine on beta 3 on linux. 

Can you fill the details required by the issue template? OS, exact godot version (if from master, beta 1, 2, 3), etc.

**Comment by ca3games** [comment] 2019-01-28 22:40
Lubuntu 18.01
Godot beta 2

**Comment by clayjohn** [comment] 2019-04-21 19:06
@ca3games can you reproduce in 3.1? It sounds like this may have been fixed in beta 3. If it has, then we should close this.

**Comment by Calinou** [comment] 2020-03-25 17:25
I'll close this due to lack of response from OP. If you can still reproduce this on Godot 3.2.1 or later, please comment.

**Closed by Calinou** 2020-03-25 17:25 UTC
Labels: topic:core, topic:input
