### ISSUE TITLE
2D collision not detected if bodies are already overlapping

### ISSUE THREAD

**Issue by TimCarp** [godotengine/godot#40638] opened 2020-07-23 17:20 UTC
**Godot version:**
3.2.2-stable_x11.64 (this issue was not present in 3.2.1)

**OS/device including version:**
Linux Mint 20 Cinnamon

**Issue description:**
If two RigidBody2D's are overlapping, and have their collision layer/mask bits set such that they don't "see" each other, and then if you change those layer/mask bits such that they should now see each other, a collision is not actually registered until they are separated and then brought into collision again. This issue is new in Godot 3.2.2. It was not present in 3.2.1.

Video of attached project running in both Godot 3.2.2 and 3.2.1:
[video_demos.zip](https://github.com/godotengine/godot/files/4967665/video_demos.zip)

**Steps to reproduce:**
1. Create two RigidBody2D's, "A" and "B".
1. On one of them "B", set it's collision_layer and collision_mask bits such that it will not collide with the other body "A".
1. Ensure the bodies overlap. Since they do not see each other, this should be possible.
1. Now, while the simulation is running, change those collision_layer and collision_mask bits on "B" such that it should see "A".
1. Notice that nothing happens, even though they should now be colliding

**Minimal reproduction project:**
Here is a small project demo'ing this issue. Try it with both Godot 3.2.2 and 3.2.1. This issue appears only in 3.2.2.
[collision_issue_minimal_proj.zip](https://github.com/godotengine/godot/files/4967664/collision_issue_minimal_proj.zip)

Screenshot from the minimal project:
![Screenshot from 2020-07-23 13-08-50](https://user-images.githubusercontent.com/68702387/88316357-3b34c280-cd07-11ea-942a-d9fb3f25ad41.png)

**Comment by Rubonnek** [comment] 2020-07-23 18:25
I'm not able to reproduce this with [3.2.3 beta1](https://downloads.tuxfamily.org/godotengine/3.2.3/beta1/)

**Comment by aaronfranke** [comment] 2020-07-24 06:58
Confirmed, this issue exists in 3.2.2 but is fixed in 3.2.3 beta 1 ([here's the diff](https://github.com/godotengine/godot/compare/3.2.2-stable..89f57ae12244f3269c9e3fe4684e16ec1fd2c989) if you want to figure out what fixed it).

**Closed by aaronfranke** 2020-07-24 06:58 UTC

**Comment by madmiraal** [comment] 2020-07-24 09:52
Fixed with #39895.
