### ISSUE TITLE
Node3D / CanvasLayer show() & hide() cannot be overridden

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#65341] opened 2022-09-04 21:47 UTC
### Godot version

Godot 4 Alpha 15 & 8c7be6358

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

8c7be6358

In CanvasLayer and Node3D, `show()` and `hide()` cannot be overridden locally. In some cases, they will work if called from other classes, including `self`. However I have several CanvasLayer/Control based classes where show/hide cannot be called from other classes.

```gdscript
func show() -> void:
	print("Overridden show()")

# Will not call the function above. Calls super.show() instead
func _on_show() -> void:
	show()                                   

# This will call the local show
func _on_overridden_show() -> void:
	self.show()

```

This affects all UI Controls, and all meshes and all visible objects in game.

Canvas layer's version is a copy of Node3D's version in https://github.com/godotengine/godot/pull/58144 

It may affect all of these classes:

```
$ egrep -rI \ show\\\( /c/gd/godot
/c/gd/godot/editor/dependency_editor.h: void show(const String &p_path);
/c/gd/godot/editor/dependency_editor.h: void show(const Vector<String> &p_folders, const Vector<String> &p_files);
/c/gd/godot/editor/dependency_editor.h: void show(Mode p_mode, const String &p_for_file, const Vector<String> &report);
/c/gd/godot/editor/dependency_editor.h: void show();
/c/gd/godot/editor/plugins/physical_bone_3d_editor_plugin.h:    void show();
/c/gd/godot/scene/3d/node_3d.h: void show();
/c/gd/godot/scene/main/canvas_item.h:   void show();
/c/gd/godot/scene/main/canvas_layer.h:  void show();
/c/gd/godot/scene/main/window.h:        void show();
```

### Steps to reproduce

See code above or run MRP

### Minimal reproduction project

[test_show.zip](https://github.com/godotengine/godot/files/9485591/test_show.zip)

**Comment by Calinou** [comment] 2022-09-04 23:36
Related to https://github.com/godotengine/godot/issues/55024.

**Comment by KoBeWi** [comment] 2022-09-05 01:18
Also related: #63705 I closed it as duplicate of the aforementioned issue, but there is inconsistency in this behavior, so maybe it's worth being a separate issue.

**Comment by tinmanjuggernaut** [comment] 2022-09-11 16:14
Actually a lot of my Control based classes do not call show/hide from other classes, which is where I'm overriding these mostly. However some do work. I've found one where it works on first load, but then not later. I haven't figured out what the difference is. If I change the problem classes to use _show() it works as expected, even the one that works at the beginning but not later. Alpha 15.

**Comment by tinmanjuggernaut** [comment] 2022-11-19 00:55
@Calinou Can this be added to the roadmap and milestones so it doesn't get lost? Thanks.

**Comment by YuriSizov** [comment] 2023-02-02 17:57
This is indeed a duplicate of https://github.com/godotengine/godot/issues/63705. These methods are not supposed to be overridden. If a proposal is made, a virtual method can be added for them, but you can already customize the behavior by connecting to the `visibility_changed` signal.

**Closed by YuriSizov** 2023-02-02 17:57 UTC
Labels: bug, topic:core, topic:gdscript
