### ISSUE TITLE
GPUParticles2D intermittent emission after Godot_v4.2-dev6

### ISSUE THREAD

**Issue by AldeonMoriak** [godotengine/godot#83929] opened 2023-10-25 08:13 UTC
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Manjaro, GeForce GT 520M, GLES3

### Issue description

After Godot_v4.2-dev6 GPUParticles2D sometimes are shown and sometimes are not. It doesn't have a pattern when this happens
In the examples below, clouds, footstep dusts and dash effects are particles.

Works in Godot_v4.2-dev6:
[godot_4.2_dev6.webm](https://github.com/godotengine/godot/assets/37976890/b2f7f9a4-6800-4a76-9f3e-d4d2d92de808)

Broken in Godot_v4.2-beta1:
[godot_4.2-beta1.webm](https://github.com/godotengine/godot/assets/37976890/5a775cb9-17bd-4b98-aed9-814f067e20d1)

Broken in Godot_v4.2-beta2:
[godot_4.2-beta2.webm](https://github.com/godotengine/godot/assets/37976890/efb5f990-48b6-4077-a628-7876efeec8ec)

Broken in Godot_v4.2-beta3:
[godot_4.2-beta3.webm](https://github.com/godotengine/godot/assets/37976890/af6c0f91-6508-4632-868f-a6afae93c460)

Broken in Godot_v4.2-dev6:
Spawning of enemis which is a particle is broken too.

None of these problems happen in Godot_v4.1-stable.

### Steps to reproduce

That's the tricky part. I couldn't produce it again with a brand new project but in the game that I already have the problem emerges all the time. 

So I attach the game, if it's okay :sweat_smile

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/13163062/Archive.zip)

**Comment by akien-mga** [comment] 2023-10-25 08:50
CC @QbieShay @clayjohn

**Comment by akien-mga** [comment] 2023-10-30 14:37
Thanks for the clear bug report! Consolidating in this other similar issue:

- Duplicate of #84072.

**Closed by akien-mga** 2023-10-30 14:37 UTC
Labels: bug, regression, topic:particles

**Comment by QbieShay** [comment] 2023-10-30 15:02
I don't think the particle rework was in beta1 @akien-mga ..?
