### ISSUE TITLE
Memory access out of bounds【3.X Android HTML5 GLES2】

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#60841] opened 2022-05-07 04:01 UTC
### Godot version

3.x

### System information

Android HTML5

### Issue description

A tip about Memory access out of bounds.And the rendering scene shows badly.Only on Android HTML5, the IOS is well.
I can't found where the problem is.But on GLES3, it is no tips about the memory,But the mesh with blend shape will disappear.。
![ea9288503f4865c3e407448cf5b7310](https://user-images.githubusercontent.com/52338846/167237422-80dda8ea-9132-4021-8201-2ae27b0f83da.jpg)
。

### Steps to reproduce

#

**Comment by lawnjelly** [comment] 2022-05-07 08:33
Which commit hash is this, or roughly what does the build correspond to (3.4, 3.5 beta 2 etc?), or is this the latest 3.x branch?

#60829 was a very recent change to blendshapes, if this has just appeared. Also we had a lot of problems like this from octahedral compression.

**Comment by Atem1995** [comment] 2022-05-07 08:40
> 

It is the latest 3.x branch. #60829 fixes the issue #60525.But there are still some problems.

**Comment by Calinou** [comment] 2022-05-28 14:50
@Atem1995 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment] 2022-05-28 14:52
Duplicate of https://github.com/godotengine/godot/issues/58078.

**Closed by Calinou** 2022-05-28 14:52 UTC
Labels: bug, platform:html5, platform:android, topic:rendering, needs testing

**Comment by al-bezd** [comment] 2024-02-01 15:07
how fix it??

**Comment by AThousandShips** [comment] 2024-02-01 15:09
See https://github.com/godotengine/godot/issues/58078

**Comment by al-bezd** [comment] 2024-02-01 15:11
> См. [№ 58078.](https://github.com/godotengine/godot/issues/58078)

thnx)))
