### ISSUE TITLE
[2.1.3] 3D grid lines are all messed up

### ISSUE THREAD

**Issue by t-boom** [godotengine/godot#8404] opened 2017-04-14 02:23 UTC
**Operating system or device - Godot version:**
Ubuntu 14.04, Godot 2.1.3

**Issue description:**

Opened Godot to see the 3D view, with grid lines all over the place. Dragging around made them move around crazy.

Expected: Lines that follow perspective

**Steps to reproduce:**

Open Godot and look at the 3D view

**Link to minimal example project:**

Here are some pictures
![godot-crazy-grid-1](https://cloud.githubusercontent.com/assets/1735659/25031009/c5437be6-2086-11e7-9d9d-422b1162b415.png)
![godot-crazy-grid-2](https://cloud.githubusercontent.com/assets/1735659/25031010/c8c0567c-2086-11e7-9c75-d99d2d62466e.png)

And here is a video
[Godot-Crazy-Grid.zip](https://github.com/godotengine/godot/files/921277/Godot-Crazy-Grid.zip)

**Comment by bojidar-bg** [comment] 2017-04-14 07:49
Duplicate of #6003, sorry.

Also, got fixed in 3.0.

**Closed by bojidar-bg** 2017-04-14 07:49 UTC

**Comment by t-boom** [comment] 2017-04-14 13:50
Ah, indeed. I don't know why I couldn't find it.

Well, one more reason to get hyped for 3,0 ☺
