### ISSUE TITLE
Autotile bug with walls (3*3 bitmask)

### ISSUE THREAD

**Issue by wyrmling** [godotengine/godot#27121] opened 2019-03-16 12:33 UTC
**Godot version:**
3.1.stable.official

**Issue description:**
Wrong behavior, when autotiles being placed close to corners:
![tile](https://user-images.githubusercontent.com/13387159/54474656-174a9e00-47f0-11e9-9648-1c46c93ff67a.gif)
Bitmask:
![autotile_bitmask](https://user-images.githubusercontent.com/13387159/54474654-131e8080-47f0-11e9-8da2-358ca21dd965.png)

**Expected:**
![not_possible_cases](https://user-images.githubusercontent.com/13387159/54475044-5d563080-47f5-11e9-839b-b95a17c80cf9.png)

**Minimal reproduction project:**
[autotile_bug.zip](https://github.com/godotengine/godot/files/2973897/autotile_bug.zip)

**Comment by bojidar-bg** [comment] 2019-03-16 13:41
Duplicate of #17063.

**Closed by bojidar-bg** 2019-03-16 13:41 UTC
Labels: bug, topic:core
