### ISSUE TITLE
FSR2 breaks refraction rendering

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#83759] opened 2023-10-21 22:25 UTC
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Godot v4.2.beta2 - Fedora Linux 38 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 Threads)

### Issue description

As the title says, refraction rendering breaks when FSR2 is enabled.
![image](https://github.com/godotengine/godot/assets/781121/b429819c-4cfe-4c05-9d87-14310debe8ab)

### Steps to reproduce

Download and open the included MRP, run it and press T to reproduce.

### Minimal reproduction project

[RefractionFSRBug.zip](https://github.com/godotengine/godot/files/13061948/RefractionFSRBug.zip)

**Comment by Calinou** [comment] 2023-10-21 22:33
cc @DarioSamo

**Comment by DarioSamo** [comment] 2023-10-22 03:47
Was beta 2 made before this [PR](https://github.com/godotengine/godot/pull/83192)? Sounds like it's probably related.

**Comment by akien-mga** [comment] 2023-10-22 09:55
> Was beta 2 made before this [PR](https://github.com/godotengine/godot/pull/83192)? Sounds like it's probably related.

Yes, it was built from f8818f85e6c43cdf1277e8ae85eba19ca0a003b0 (one day before that PR was merged).

**Comment by clayjohn** [comment] 2023-10-22 10:03
This is a duplicate of https://github.com/godotengine/godot/issues/83152 which is fixed in master and will be fixed in beta 3

**Closed by clayjohn** 2023-10-22 10:03 UTC
Labels: bug, topic:rendering, topic:3d
