### ISSUE TITLE
Legible output for typeof()

### ISSUE THREAD

**Issue by anakimluke** [godotengine/godot#9336] opened 2017-06-23 20:57 UTC
Currently, `typeof()` returns an integer and you have to look at the global scope to see what it means. 

It would be better for it to return something that is human-readable.

**Comment by groud** [comment] 2017-06-23 21:06
I don't think this will ever happen, as comparing integers is less costly that comparing strings

**Comment by vnen** [comment] 2017-06-23 21:42
The most that could be done is a translation function between the type values and their names. I don't thinks it is useful though, except maybe for debug prints.

**Comment by anakimluke** [comment] 2017-06-23 21:49
Or maybe global constant integers named after the types? This way the code would look better, but the debug prints would still be ugly.

**Comment by anakimluke** [comment] 2017-06-23 22:15
I guess I misunderstood how the global scope works. This already works:
```swift
if typeof("Hello world.") == TYPE_STRING:
    print("It's a string.")
```

But still, a translation function or a `typeof` function that returns a string would be nice for the debug prints.

**Comment by bojidar-bg** [comment] 2017-06-24 11:13
Maybe... if we get a `strtypeof` or something similar, which would return the string name of the type?

**Comment by anakimluke** [comment] 2017-06-25 01:36
I implemented this myself, but I don't know if it was done the right way.

https://github.com/anakimluke/godot/commit/680f4dffd62897fedc1d91e113aa0b9eed8d89e9

Should I make a pull request?

**Comment by bojidar-bg** [comment] 2017-06-25 11:25
@anakimluke Looks good, but I think the type names should be as in the docs, using capital letters.. Also, I think there should be some function about that in the various variant* files.

**Comment by vnen** [comment] 2017-06-25 14:08
BTW, while you are at it, you should make the same for the `ERR_` constants.

**Comment by anakimluke** [comment] 2017-06-26 00:11
@vnen You mean, a function to translate? If so, can you give me some examples on how to provoke these errors in gdscript?

**Comment by vnen** [comment] 2017-06-26 00:37
@anakimluke yes, a function that takes an error number and returns a human-readable string. You can find them on the [Global Scope](http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html]) (just search for `ERR_`). If you want an example of errors occurring, you can call [File.open()](http://docs.godotengine.org/en/latest/classes/class_file.html#class-file-open) with a file that doesn't exist. It will return an `ERR_FILE_NOT_FOUND`.

```GDScript
var file = File.new()
var err = file.open("res://path/that/dont/exist", file.READ).
```

**Comment by anakimluke** [comment] 2017-06-26 01:20
I rewrote the code to take the strings directly from the global scope.

https://github.com/anakimluke/godot/commit/3128da5275fdb9cd549a56a5498a13e925da99ee

Is it a better approach? New types can be added and changed(except for `TYPE_NIL`) without the need to update the function.
A problem would be that it would compare strings instead of ints.

**Comment by anakimluke** [comment] 2017-06-27 00:26
Added error2str.

I'm back using the switch. Also, that code wouldn't work with the error2str function because the constants aren't increasing exactly linearly.

I alerted on `core/global_constants.cpp` that these functions have to be updated if something changes.

I also thought that it would be nice to do something in case the type/error doesn't exist; I added a `default` to the switch. Should it return an empty string? An error message?(This one would be confusing with error2str) Should it handle the error like `VALIDATE_ARG_COUNT` and `VALIDATE_ARG_NUM` are handling? Or some other way of handling? What is the meaning of life? Is this all a dream?

https://github.com/anakimluke/godot/commit/edd326ef1f96e69a62b2ea54b94cc482ae980fc3

**Comment by bojidar-bg** [comment] 2017-06-27 08:51
@anakimluke Well, I think you can use the `ERR_FAIL_INDEX` macro, though I'm not completely sure..

**Comment by kubecz3k** [comment] 2018-04-03 11:28
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by anakimluke** [comment] 2018-04-17 13:37
Hi! Yeah, I still would like to try to add this myself, if that's ok.

**Comment by kubecz3k** [comment] 2018-04-19 07:30
@anakimluke since you have already the code, people make a pull request so it could get proper review and discussion there

**Comment by vnen** [comment] 2018-04-19 15:38
@anakimluke you can read the [Pull Request guide](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) to help you with the steps, if needed.

**Comment by akien-mga** [comment] 2020-05-26 13:42
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 13:42 UTC
Labels: discussion, feature proposal, topic:gdscript
