### ISSUE TITLE
Re-import glb model doesn't change the old glb model

### ISSUE THREAD

**Issue by Ebbombe** [godotengine/godot#90241] opened 2024-04-05 07:48 UTC
### Tested versions

Bug found in 4.2.1 (Forward+)

### System information

Windows 11

### Issue description

I imported some 3d models in the editor with drag and drop in a folder and then put in a scene, after that i modified (change origin  of the 3d model) and re-exported from blender as glb with the same name (overwriting) and re-imported them (using the re-import command in Godot to refresh the glb file) no changes at all neither in the scene nor in the re-importef model 

### Steps to reproduce

- export a 3d model in glb from blender (4.1)
- import 3d model in godot (drag and drop in a folder in the editor)
- put model in the scene
- return to blender and cahnge the origin to the model and export overwriting the glb model
- re-import the 3d model in godot (by refreshing button in the godot editor)

### Minimal reproduction project (MRP)

N/A

**Comment by huwpascoe** [comment] 2024-04-06 12:00
Following the instructions exactly:
- `path/model.blend` is exported as...
- `exportpath/model.glb` is user copied to...
- `godotproj/model.glb` is imported by Godot.

After editing

- `path/model.blend` is re-exported as...
- `exportpath/model.glb`.
- `godotproj/model.glb` is unchanged.


Even if reimport is clicked, there's no way Godot can know about the exported file if it's not drag dropped over the existing one?

**Comment by caioraphael1** [comment] 2024-05-11 16:43
I use 4.3-dev5, and I'm also having this problem consistently when reimporting .gltf files. This happens whether the node is from the .gltf file itself, or from an Inherited Scene. This makes that every time I reimport something, I have to delete the old instance and create a new one, or check every single 'undo' icon in the Inherited Scene, to update manually the changes made in the re-import.

I've only tested it with .gltf, I don't use .glb or .blend.

**Comment by fire** [comment] 2024-05-11 17:21
Did you mean to link another issue number?

**Comment by caioraphael1** [comment] 2024-05-11 17:45
> Did you mean to link another issue number?

ooops, now the link is correct

**Comment by Rindbee** [comment] 2024-05-24 01:25
It actually changes, but it automatically overwrites the changed properties to keep the scene as it was when it was opened.

If you don't want this behavior, you can close the scene tab when importing.

**Comment by passivestar** [comment] 2024-06-07 06:15
I initially thought that this is a duplicate of my issue https://github.com/godotengine/godot/issues/90659. In https://github.com/godotengine/godot/issues/90659 I mentioned that modifying geometry in such a way that it would change its dimensions or adding/removing objects forces the whole imported scene to update. However recently I'm often facing a problem where that workaround doesn't work. Not even clicking "Reimport" works. Which is what this issue is describing. I have to do this for a mesh to get updated:

> I have to delete the old instance and create a new one

**Comment by passivestar** [comment] 2024-06-30 14:12
> I have to do this for a mesh to get updated:
> I have to delete the old instance and create a new one

Just found out that instead of deleting and creating a new instance pressing "Scene -> Reload Saved Scene" works too. So the problem is that the host scene doesn't get updated when a gltf inside of it gets reimported

That is only the case when editable children is disabled though, if editable children are enabled then indeed you need to press every revert icon near every transform and subresource like meshes because for some reason godot overwrites those in inherited scenes or when editable children is used, dumping all of that data into the host scene. Isn't the point of scene inheritance to be able to add/modify data selectively?

**Comment by caioraphael1** [comment] 2024-06-30 14:42
> Just found out that instead of deleting and creating a new instance pressing "Scene -> Reload Saved Scene" works too. So the problem is that the host scene doesn't get updated when a gltf inside of it gets reimported

that's really good to know, thanks! I wish this as fixed tho, its quite annoying

**Comment by fire** [comment] 2024-06-30 16:13
Can you check if https://github.com/godotengine/godot/pull/92279 fixes or doesn't fix this issue?

**Comment by passivestar** [comment] 2024-06-30 16:33
> Can you check if https://github.com/godotengine/godot/pull/92279 fixes or doesn't fix this issue?

It doesn't fix this issue, I was using only the master branch for the past month

**Closed** 2024-07-08 17:17 UTC
Labels: bug, needs testing, topic:import
