### ISSUE TITLE
SceneTreeEditor does not disable attempting to add nodes above root

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#60292] opened 2022-04-16 04:12 UTC
### Godot version

3d8c971ff8936a7c57bdae536d050207077a9427

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

On the Godot 4 branch, the scene tree editor will allow you to drag a scene instance onto it and above the root node. While this is not allowed, the tree considers this a valid action; it won't add the instance, but will spit out an error. This does not happen in the 3.x branch, and I believe the reason seems to be that Godot 4 has switched to using a hidden root node above the actual root, so a check for whether dragged data is valid is being bypassed.

### Steps to reproduce

Create and save two seperate scenes with one node in the root
Open the first scene
Drag the second scene onto the scene tree above the root node
Observe the error

### Minimal reproduction project

N/A

**Comment by Geometror** [comment] 2022-11-23 21:58
![Godot_v4 0-beta4_win64_MI44spbars](https://user-images.githubusercontent.com/50084500/203652607-6d4eb4a0-a7e2-4248-875c-7216b6f78ddc.gif)
Seems like this got fixed in the meantime. I can't reproduce this with beta4. Can you confirm?

**Comment by YuriSizov** [comment] 2023-01-12 15:01
Following the steps from the OP I can't reproduce it either with b11.

https://user-images.githubusercontent.com/11782833/212101180-d48e05ba-5d82-4bdf-9c2b-eac742653654.mp4

Let me know if it's still reproduceable in some way, and we can reopen.

**Closed by YuriSizov** 2023-01-12 15:01 UTC
Labels: bug, topic:editor, topic:gui
