### ISSUE TITLE
OpenGL: Top of window flickers when using fullscreen with `keep` stretch aspect on macOS

### ISSUE THREAD

**Issue by RandomWalrus13** [godotengine/godot#72852] opened 2023-02-07 18:42 UTC
### Godot version

4.0beta17

### System information

MacOS Ventura 13.2

### Issue description

When my app enters fullscreen mode, the top of the screen that is not included in the render flickers on and off. I attached a video of this effect. This is very distracting to people trying to play my game.

https://user-images.githubusercontent.com/111152655/217336481-aa4d6511-5425-4934-ae86-0ed20c93db56.mov

### Steps to reproduce

<img width="669" alt="Screenshot 2023-02-07 at 12 42 24 PM" src="https://user-images.githubusercontent.com/111152655/217336624-a37601eb-c79b-47be-9c58-dc5d8e56fc87.png">
Here are the settings

### Minimal reproduction project

[Inverted.zip](https://github.com/godotengine/godot/files/10680581/Inverted.zip)
This zip file has a minimal project

**Comment by Calinou** [comment] 2023-02-07 22:55
@RandomWalrus13 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by clayjohn** [comment] 2023-02-07 23:22
I have seen a similar issue using the gl_compatibility renderer on PopOS 22.04 with the stretch mode set to Viewport. It seems like the engine is giving the renderer the dimensions minus the title bar even though it expects the entire window to be rendered

**Comment by RandomWalrus13** [comment] 2023-02-08 00:36
Is there a solution to this issue?

**Comment by clayjohn** [comment] 2023-02-08 00:40
@RandomWalrus13 Can you please let us know what rendering method you are using? it is reported in the top right-hand corner of the editor

**Comment by RandomWalrus13** [comment] 2023-02-08 00:41
I am using the compatibility rendering method

**Comment by Calinou** [comment] 2023-02-08 00:50
Can you reproduce this when using Forward+ or Mobile instead?

**Comment by RandomWalrus13** [comment] 2023-02-08 13:46
This problem does not occur while using the Forward+ rendering method. Although, as far as I know, I do not think you can export to WebGL using Forward+.

**Comment by clayjohn** [comment] 2023-02-08 21:08
> This problem does not occur while using the Forward+ rendering method. Although, as far as I know, I do not think you can export to WebGL using Forward+.

No, you can't export to Web with the Forward+ or Mobile backends. Is this issue only reproducible on web export for you?

**Comment by RandomWalrus13** [comment] 2023-02-08 21:28
Yes. This issue does not appear in Foward+ plus rendering. I am using that for now while waiting for the problem to be resolved.

**Comment by Calinou** [comment] 2023-02-10 15:10
Duplicate of https://github.com/godotengine/godot/issues/71799 (same cause).

**Closed by Calinou** 2023-02-10 15:10 UTC
Labels: bug, platform:macos, topic:porting, needs testing
