### ISSUE TITLE
[4.0] NavigationRegion ignores NavigationAgent3D's agent_height_offset

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#57084] opened 2022-01-23 15:31 UTC
### Godot version

4.0-dev.20220118

### System information

Windows 10

### Issue description

NavigationRegion ignores NavigationAgent3D's agent_height_offset and the agent doesn't move at all. Should walk under platforms given the proper offset.

### Steps to reproduce

A NavigationMesh with Agent/Height = 2 and two NavigationAgent3D, one with AgentHeightOffset = 0 and the other with 2.
![1](https://user-images.githubusercontent.com/98270528/150685679-f3632ba8-35c6-40b3-b364-cc3403d7cb44.png)

Short agent goes to destination by walking under the platform, tall agent doesn't move.

![2](https://user-images.githubusercontent.com/98270528/150685686-d7eea439-3154-49e2-96c6-71a6af0474e6.png)

@AndreaCatania 

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/7920752/project.zip)

**Comment by venilark** [comment] 2022-01-31 09:02
Tried it with Alpha 1 just in case, same outcome.

**Comment by smix8** [comment] 2022-05-13 17:57
@venilark 

This is not a bug but a badly named and unexplained agent property.

What `navigation_height_offset` does it subtracts this value from the y-axis of all pathpoints and checks in the agents `get_next_location()` and `update_navigation()` functions and nothing else.

With -2.0 y-axis like in the example your agent gets dug into the ground and stuck.

If you want navigation for different sized agents you need to create different layers regions or a new map for each agent size and bake different NavigationMeshes with different agent height settings.

**Comment by venilark** [comment] 2022-05-16 11:26
> @venilark
> 
> This is not a bug but a badly named and unexplained agent property.
> 
> What `navigation_height_offset` does it subtracts this value from the y-axis of all pathpoints and checks in the agents `get_next_location()` and `update_navigation()` functions and nothing else.
> 
> With -2.0 y-axis like in the example your agent gets dug into the ground and stuck.
> 
> If you want navigation for different sized agents you need to create different layers regions or a new map for each agent size and bake different NavigationMeshes with different agent height settings.

I get this error if I bake two overlapping navmeshes with different agent heights.
E 0:00:00:0735   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problem.
  <C++ Source>   modules/navigation/nav_map.cpp:566 @ sync()

Short agent goes under the platform, tall agent gets stuck on it, it ignores the "tall" region. Haven't tested anything about layers yet.

**Comment by smix8** [comment] 2022-05-19 21:57
@Calinou @akien-mga 
Can be closed as this is not a bug but another navigation setup / lack of documentation issue.
Added a note for docs to explain how to create navigation for different sized characters.

**Comment by Calinou** [comment] 2022-05-19 21:58
> Added a note for docs to explain how to create navigation for different sized characters.

Is this note added to the documentation yet? If not, I'd prefer leaving this issue open so we remember to document this.

**Comment by smix8** [comment] 2022-05-19 22:08
@Calinou 
Sorry, in my mind I already made the doc draft pr ... but I now realized it is still only resting on my harddisk.

**Closed** 2022-06-01 17:44 UTC
Labels: bug, topic:navigation, topic:3d
