### ISSUE TITLE
Strange StyleboxFlat regression with high corner radius

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#52623] opened 2021-09-13 00:17 UTC
### Godot version

3.4 beta, 95162ca393e48d73a2a3d14147f6fb85779696ec

### System information

Windows 11, GLES3, Vega 56

### Issue description

There is some strange regression that I can't entirely pinpoint, here's the jist of it:

~~Corner radius seems different from what is shown in the editor to the actual final look in the game:~~ (not a bug actually)

![imagen](https://user-images.githubusercontent.com/3101690/133007487-03337199-ef19-49aa-8dab-d67da46ea766.png)

Additionally, if the corner radius is very high it creates this strange line on the top left corner>

![imagen](https://user-images.githubusercontent.com/3101690/133007510-fe4a64f3-3eea-4f98-9427-b01690d7aa7b.png)

This wasn-t present in earlier versions of 3.x at least in 03c41fa34cc23fcd9361016298b861f469bdba22

### Steps to reproduce

Create a StyleboxFlat with a high corner radius.

**Comment by Calinou** [comment] 2021-09-13 00:19
> This wasn-t present in earlier versions of 3.x at least in 03c41fa

https://github.com/godotengine/godot/pull/51442 was merged just after that commit.

cc @Geometror

**Comment by EIREXE** [comment] 2021-09-13 00:22
> 
> 
> > This wasn-t present in earlier versions of 3.x at least in 03c41fa
> 
> #51442 (and its `3.x` version #51589) was merged just after that commit. Can you reproduce this if you disable antialiasing in the StyleBoxFlat? For 45-degree beveled angles, you don't really need antialiasing.
> 
> cc @Geometror

Disabling AA does indeed fix that

**Comment by Calinou** [comment] 2021-09-13 00:25
Given how this is a corner case (no pun intended), it may be better to document this in the class reference if we can't fix it without causing undesirable side effects for common use cases (rounded corners).

**Comment by EIREXE** [comment] 2021-09-13 00:26
> 
> 
> Given how this is a corner case (no pun intended), it may be better to document this in the class reference if we can't fix it without causing undesirable side effects for common use cases (rounded corners).

For sure, that would make sense

**Comment by Geometror** [comment] 2021-09-14 00:52
> There is some strange regression that I can't entirely pinpoint, here's the jist of it:
> 
> Corner radius seems different from what is shown in the editor to the actual final look in the game:

Maybe I overlooked something or misunderstood you, but I cant really see the regression there :) 
The stylebox preview in the inspector has the same corner radius (bottom left) as the stylebox in the game (58 pixels), but since the prefix stylebox has a greater height, the chamfer does not reach the top left corner. However, the other corner with the radius set to 1024 looks the same because the actual corner radius is clamped to the stylebox's height.

Nevertheless, the strange line is indeed a regression. When modifying the fake AA code in StyleBoxFlat I forgot to change the corner adaption part. I hope I can open a PR soon to fix that (when I figured out how to remove a weird overlap when using a transparent border color).
I managed to eliminate the strange lines for fully opaque borders:
![grafik](https://user-images.githubusercontent.com/50084500/133172725-917e1c13-c885-4595-89de-84b84c3293fa.png)

But as Calinou said, this is a corner case in which the fake AA doesn't even work correctly (also present in 3.3; only the outer side of the border has a fake AA gradient, but in this case it has the length 0), so I would recommend to disable it. Here's an idea: A shear property in StyleBoxFlat would enable this type of effect in a better way (more flexible, less "hacky").

**Comment by EIREXE** [comment] 2021-09-14 15:59
> > There is some strange regression that I can't entirely pinpoint, here's the jist of it:
> > Corner radius seems different from what is shown in the editor to the actual final look in the game:
> 
> Maybe I overlooked something or misunderstood you, but I think that isn't a regression.
> The stylebox preview in the inspector has the same corner radius (bottom left) as the stylebox in the game (58 pixels), but since the prefix stylebox has a greater height, the chamfer does not reach the top left corner. However, the other corner with the radius set to 1024 looks the same because the actual corner radius is clamped to the stylebox's height.
> 
> Nevertheless, the strange line is indeed a regression. When modifying the fake AA code in StyleBoxFlat I forgot to change the corner adaption part. I hope I can open a PR soon to fix that (when I figured out how to remove a weird overlap when using a transparent border color).
> I managed to eliminate the strange lines for fully opaque borders:
> ![grafik](https://user-images.githubusercontent.com/50084500/133172725-917e1c13-c885-4595-89de-84b84c3293fa.png)
> 
> But as Calinou said, this is a corner case in which the fake AA doesn't even work correctly (also present in 3.3; only the outer side of the border has a fake AA gradient, but in this case it has the length 0), so I would recommend to disable it. Here's an idea: A shear property in StyleBoxFlat would provide an option to achieve this type of effect in a better way (more flexible, less "hacky").

I see, this makes sense

**Comment by Calinou** [comment] 2021-09-14 16:48
A skew option sounds good to me – feel free to open a proposal for it :slightly_smiling_face:

**Closed** 2021-09-15 21:20 UTC
Labels: bug, documentation, regression, topic:gui
