### ISSUE TITLE
Mouse input position gets offset when resizing (Stretch Mode set to "Viewport")

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#44915] opened 2021-01-04 17:54 UTC
**Godot version:**
v4.0.dev.custom_build.950dedbb6

**OS/device including version:**
Windows 10

**Issue description:**
Tested in 2D and 3D
When setting Stretch mode to "Viewport", and the screen is resized, the mouse input get's offset. 
Here are video showing this (the window has already been resized):

https://user-images.githubusercontent.com/47060866/103562912-e38bad00-4e89-11eb-9ddd-6cd0fc03aff2.mp4

https://user-images.githubusercontent.com/47060866/103560860-8a6e4a00-4e86-11eb-82ee-a4d00b9f2d41.mp4

This does NOT happen when stretch mode is set as disabled or canvas_items

**Steps to reproduce:**
-In any project, add a button (or anyway to detect mouse input). 
-Go Project Settings>Display>Window>Stretch and change mode to "Viewport"
-Load Project, resize the window and use your input detection method to see if mouse input is offset

**Minimal reproduction project:**
[Button_Offset.zip](https://github.com/godotengine/godot/files/5766072/Button_Offset.zip)

**Comment by Calinou** [comment] 2021-01-04 18:12
Duplicate of https://github.com/godotengine/godot/issues/29570 ?

**Comment by JustYourAverageJosh** [comment] 2021-01-04 18:39
I don't think so, because this is for the main default viewport, not any additional subviewports.

**Comment by awalone995** [comment] 2021-01-09 17:16
any workaround except not using viewports yet : ^ (

**Comment by juse4pro** [comment] 2021-01-20 20:46
I am also struggling to find a proper solution. :(

**Comment by Calinou** [comment] 2021-01-20 20:47
@juse4pro This issue is only about the `master` branch, not Godot 3.2.x.

**Closed** 2022-01-23 16:27 UTC
Labels: bug, confirmed, topic:input, topic:gui
