### ISSUE TITLE
Mono: Adding a autoload script outputs error in console "does not inherit a Node"

### ISSUE THREAD

**Issue by evan-boissonnot** [godotengine/godot#46257] opened 2021-02-20 17:03 UTC
**Godot version:**

3.2.3 mono

**OS/device including version:**

gitlab / ci => docker image davidwesst/godot-mono:3.2.3

**Issue description:**

ERROR: _create_autoload: Script does not inherit a Node: res://Sources/App/Shared/Scenes/Dialog/Scripts/DialogBoxsProxy.cs.
   At: editor/editor_autoload_settings.cpp:357.

**Steps to reproduce:**
Add a class C#, that inherits Godot.Node
Add it on Autoload

run godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe

**Comment by Calinou** [comment] 2021-02-20 17:19
Duplicate of https://github.com/godotengine/godot/issues/36787.

**Closed by Calinou** 2021-02-20 17:19 UTC
