### ISSUE TITLE
Cannot scale VehicleBody

### ISSUE THREAD

**Issue by masonjoyers** [godotengine/godot#3844] opened 2016-02-27 05:57 UTC
**Operating system or device:**
Linux 4.4.1 64 bit

**Issue description** (what happened, and what was expected):
Created VehicleBody object in editor and applied scale. Scale and position are ignored during run time.

Expected behavior:
Scale and position is maintained during run time.

**Steps to reproduce:**
Create a VehicleBody object and apply scale via the editor.

**Link to minimal example project** (optional but very welcome):
http://git.bragafvl.com/masonjoyers/race-game/tree/4315c2c5ec6ae45450c8ff8dcddaeda2afc4ef8b

**Comment by bojidar-bg** [comment] 2016-02-27 13:08
@masonjoyers ~ BTW, [What is the proper letter case for spelling Godot?](http://godotengine.org/qa/172/what-is-the-proper-letter-case-for-spelling-godot) (on Godot QA)

**Comment by kubecz3k** [comment] 2016-02-29 08:51
Simple body scaling is not supported yet, but as far as I know there are plans to support it in the future.

**Comment by kubecz3k** [comment] 2016-02-29 08:52
related issue: https://github.com/godotengine/godot/issues/1505

**Comment by kubecz3k** [comment] 2016-02-29 08:55
Related issue: https://github.com/godotengine/godot/issues/1505 
From this one it seems that body scaling will be possible only or uniform shapes

**Comment by akien-mga** [comment] 2018-05-25 08:43
Duplicate of #1505 which was fixed in 3.0.

**Closed by akien-mga** 2018-05-25 08:43 UTC
Labels: feature proposal, topic:core, usability
