### ISSUE TITLE
White lines around tiles when switching to fullscreen mode

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#47932] opened 2021-04-15 19:03 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 7, 64 bit
CPU: FX 8350
GPU: GTX 1060 (3GB)
RAM: 16GB
My Project uses GLES2

**Issue description:**
After using Tilemaps i got white lines on some of the tiles.
Enabling "Pixel Snap" helped to get rid of them while in window mode without resizing the window.
But when i resize the window or switch to fullscreen mode, those lines are back.

**Steps to reproduce:**
1.) Create a Tilemap
2.) Build a level with that tilemap
3.) Enable "Pixel Snap"
4.) Start the game
5.) Go to Fullscreen or change Window Size

**Comment by Calinou** [comment] 2021-04-15 21:58
@Wombyte2 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, when filtering is enabled on textures, it's expected that there will be mipmap bleeding artifacts due to filtering.

**Comment by lawnjelly** [comment] 2021-04-16 06:43
Very probably a duplicate of #45047, see there for additional explanation and workarounds.

**Comment by Wombyte2** [comment] 2021-04-16 09:40
I uploaded a minimal version of my project that i'm working on. It only includes one scene with some tilemaps placed there. If you have a view on it in normal window size the error does not occur, but when you change the size, especially if you maximize the window you can clearly see it. 

I also made 2 screenshots, the first one is the game in normal window size, the second one is maximized:
![tile1](https://user-images.githubusercontent.com/72589109/115005299-0590c480-9ea8-11eb-9f84-e03035a53854.PNG)
![tile2](https://user-images.githubusercontent.com/72589109/115005302-06295b00-9ea8-11eb-80e2-aec9a5ef4142.PNG)


[PirateBattle_MINIMAL.zip](https://github.com/godotengine/godot/files/6324001/PirateBattle_MINIMAL.zip)


> 
> 
> @Wombyte2 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Also, when filtering is enabled on textures, it's expected that there will be mipmap bleeding artifacts due to filtering if the textures are rendered at a scale factor different than 100%. You can work around this by changing the color of fully transparent pixels in an image editor to roughly match the rest of the image. Also, when using a PNG optimizer, configure it so it doesn't discard the colors of fully transparent pixels.

I don't have filtering enabled. 



> 
> 
> Very probably a duplicate of #45047, see there for additional explanation and workarounds.

I read that, but to be honest: I did not get it. I'm mostly a programmer not a graphics dude, so talking about "Contracting UV's" and "zero alpha" => I have no clue what that means :/

**Comment by Wombyte2** [comment] 2021-04-16 09:46
While reading the #45047 issue again, i would like to try that "edge padding", but have no clue on where to enable that?
using duckduckgo search only leads me to readings about "edge padding".

**Comment by Zireael07** [comment] 2021-04-16 09:54
"Edge padding" means to repeat pixels of your tiles' edges. Since Godot doesn't have an automated way of doing it, you need a graphics editor.

For an example, I'll assume your sprite is 32x32. Open a graphics editor, create a canvas that is 34x34, paste the sprite in the center so that you get a single pixel wide border, copy and paste every edge to the so far empty border, done.

I recommend Krita or GIMP.

BTW requiring edge padding is not solely a Godot problem, here's a Unity discussion: https://forum.unity.com/threads/tilemap-has-tearing-between-tiles-even-with-pixel-snap.499154/

**Comment by Wombyte2** [comment] 2021-04-16 10:14
> p

Ah i see, okay than this is not a good solution for me. As mentioned before I'm bad with graphics, it would take to long for me to do it that way. Maybe there's another solution? 
I believe you that this is not only a Godot problem, I worked alot with Unity in the past and Unity has it's own issues. But meanwhile I prefer Godot for its easier handling. 
However would be great to find a solution somehow that might be easier than editing every single sprite.

**Comment by Calinou** [comment] 2021-04-16 14:18
> However would be great to find a solution somehow that might be easier than editing every single sprite.

You can probably automate this operation using a program like [ImageMagick](https://imagemagick.org/), but you'll have to find the command to do it.

**Comment by clayjohn** [comment] 2021-04-16 15:32
I ran the attached project and can reproduce the line artifacts around the island tiles. 

The solution in this case is not adding edge padding. Godot actually adds edge padding by default for 2D images. To enable or disable edge padding you can toggle the "fix alpha border" setting in the texture's import settings. 

The issue here is due to a poorly formatted sprite sheet. The tiles are arranged with no space between them, so when filtering or mipmapping is used the colors bleed over the edges of the tiles. [Calinou rightly recognized this above](https://github.com/godotengine/godot/issues/47932#issuecomment-820755983)

There are two ways you can fix this:

1. Toggle off "filter" in the spritesheet's import settings (remember you will have to reimport after doing so); or
2. Reformat your sprite sheet to leave space between tiles.

**Comment by Zireael07** [comment] 2021-04-16 15:37
Aaah, I didn't know it was a spritesheet. I thought it was individual tiles...

**Comment by Calinou** [comment] 2021-04-16 22:14
@Wombyte2 Can you reproduce this after disabling batching in the Project Settings?

**Comment by clayjohn** [comment] 2021-04-17 17:37
I ran it with batching on and off and with the single rect fallback on and off, in all cases the only way to get rid of the artifact was to turn filtering off.

**Comment by filipworksdev** [comment] 2023-10-28 19:08
I can confirm this is still happening in 4.1  . This is an issue specifically an issue with this etting being on 
![image](https://github.com/godotengine/godot/assets/99937119/66d34ae5-27bf-4df3-8cfc-7fc03ea77586)

**Comment by Calinou** [comment] 2023-10-31 08:05
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39720, as this is due to the same cause.

**Closed by Calinou** 2023-10-31 08:05 UTC
Labels: topic:rendering, documentation, topic:2d
