### ISSUE TITLE
Editor FPS drops when a popup window is open on Wayland

### ISSUE THREAD

**Issue by smallcloverstudio** [godotengine/godot#75770] opened 2023-04-06 23:04 UTC
### Godot version

4.0.2

### System information

Ubuntu 22.04 wayland

### Issue description

When a popup window shown the frame rate of the entire engine down.
I know that the editor run on optimized mod so when the main editor window is not focused the engine decrease the frame rate
but that decrement apply to the popup window such as file dialog and it annoying to use it with low frame rate "take a while after input event or selecting directory ..."

### Steps to reproduce

there is many way but this have the high effect:
open the editor
press attach a script button
press chose file to open file dialog
and you get it

### Minimal reproduction project

N/A

**Comment by smallcloverstudio** [comment] 2023-04-06 23:13
this issue happen with wayland .
I don't have any problem with xorg

**Comment by Calinou** [comment] 2023-04-06 23:22
I can't reproduce this on Fedora 37 KDE with X11:

https://user-images.githubusercontent.com/180032/230511110-92e6fcdf-33af-4176-a029-17507da8d33d.mp4

**Comment by smallcloverstudio** [comment] 2023-04-07 13:41
[Screencast from 07 أفريل, 2023 CET 02:36:05 م.webm](https://user-images.githubusercontent.com/127943614/230618619-f919495f-70e5-4887-afb3-ca1d88b74755.webm)

**Comment by Calinou** [comment] 2023-04-07 14:26
The fact it's dropping to 1 FPS means this is not related to the FPS limit reduction when the editor window is unfocused (the default is 10 FPS). It's due to something else entirely.

**Comment by smallcloverstudio** [comment] 2023-04-07 15:00
@Calinou I will keep using single window mode cuz I can't use Xorg in my environment.

**Comment by CalebJohn** [comment] 2023-05-29 05:12
I believe this is a duplicate of https://github.com/godotengine/godot/issues/69926 . In which case, this is likely a quirk with how godot interacts with mutter (wayland display server).

**Comment by akien-mga** [comment] 2023-05-29 08:54
Duplicate of #69926.

**Closed by akien-mga** 2023-05-29 08:54 UTC
Labels: bug, platform:linuxbsd, topic:editor, topic:porting
