### ISSUE TITLE
Android --  using .NET cryptography elements can make the application hang

### ISSUE THREAD

**Issue by architeer** [godotengine/godot#86624] opened 2023-12-30 02:58 UTC
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - GLES3 (Compatibility) - Quadro 2000M () - Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz (8 Threads)

### Issue description

When running on Android, certain .NET cryptography method call or instantiations can hang the Godot app.

Each of the following line of code can hang the app:

```csharp
byte[] byteArray = System.Security.Cryptography.RandomNumberGenerator.GetBytes( 32 );
System.Security.Cryptography.Rfc2898DeriveBytes rfc2898DeriveBytes = new System.Security.Cryptography.Rfc2898DeriveBytes( Encoding.UTF8.GetBytes( "test_password" ), Encoding.UTF8.GetBytes( "test_salt" ), 10000, System.Security.Cryptography.HashAlgorithmName.SHA512 );
```
Note, running on the windows desktop, those lines of code runs good.  On the Android, it hangs the app.

### Steps to reproduce

Export project to Android.

Run any of the following lines of code on the Android:

```csharp
byte[] byteArray = System.Security.Cryptography.RandomNumberGenerator.GetBytes( 32 );
System.Security.Cryptography.Rfc2898DeriveBytes rfc2898DeriveBytes = new System.Security.Cryptography.Rfc2898DeriveBytes( Encoding.UTF8.GetBytes( "test_password" ), Encoding.UTF8.GetBytes( "test_salt" ), 10000, System.Security.Cryptography.HashAlgorithmName.SHA512 );
```

### Minimal reproduction project (MRP)

N/A

**Comment by raulsntos** [comment] 2024-01-09 19:44
- This is likely a duplicate of https://github.com/godotengine/godot/issues/84559

**Comment by raulsntos** [comment] 2024-02-25 06:40
I'll close this issue to consolidate in https://github.com/godotengine/godot/issues/84559. As a summary of what's happening:

Currently .NET Android exports use the `linux-bionic` runtime identifier which doesn't support the JNI that is required for crypto APIs. This means that you have to provide the OpenSSL library yourself, if you are able to package libssl.so and libcrypto.so into the APK it should fix your issue.

There's a new PR that changes the way Android exports work to use the `android` runtime identifier instead. This allows us to use the JNI for crypto support, so it should fix the issue without having to manually provide libssl.so and libcrypto.so.
- https://github.com/godotengine/godot/pull/88803

**Closed by raulsntos** 2024-02-25 06:40 UTC
Labels: bug, platform:android, topic:dotnet
