### ISSUE TITLE
Issue with built-in scripts and export vars

### ISSUE THREAD

**Issue by Cschlaefli** [godotengine/godot#24901] opened 2019-01-11 01:32 UTC
**Godot version:**
3.1 custom build f7d2750

**OS/device including version:**
Fedora 29  4.19.13-300.fc29.x86_64

**Issue description:**
If you create a built-in script that extends a script with an export variable, and you don't have any instances of the parent script in the scene, the variable defaults to null instead of the value assigned in the parent script.  Manually assigning the value in the editor changes the value, but since it automatically assigns the default value when using non-built-in scripts, seems that's how built-in scripts should behave.

**Steps to reproduce:**
Create a script with an assigned export variable, create a built-in script on a node that extends the originial script, and the export variable there will default to null. 

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2747719/test.zip)
Note: haven't tested if having _init() functions in these scripts matter, but I doubt it.

**Comment by jlahman** [comment] 2019-01-17 23:37
Just used your test project on a more recent build of godot, and once the project loads, the problem is there, but if I do anything( like add an empty node that does nothing) and save, the value updates to the original. 

I also can't get the issue to reappear by manually going through the process on a new project. Perhaps this was fixed by one of the PR's merged between then and now?

**Comment by akien-mga** [comment] 2019-02-25 12:13
Tested in the current master branch (88a36e20cb), and I confirm that the bug seems fixed. Same result as @jlahman, the node with builtin script does have `null` export var initially, but resaving them/changing values fixed the problem.

**Closed by akien-mga** 2019-02-25 12:13 UTC
Labels: bug, topic:core
