### ISSUE TITLE
Viewport 2D child nodes are not visible in the editor.

### ISSUE THREAD

**Issue by KC098** [godotengine/godot#58232] opened 2022-02-17 09:13 UTC
### Godot version

3.4.2

### System information

Windows 10 GLES3 AMD Radeon HD 8730M

### Issue description

When assigning a 2D/Control child node to a viewport node, suddenly the nodes disappear, unable to edit them.
There is already an issue report [#2139](https://github.com/godotengine/godot-proposals/issues/2139) but seems like it hasn't been fixed. 
I tried the [demo](https://godotengine.org/asset-library/asset/129) that showcases the functionality I desire, but still the issue happens.

Before adding to viewport.
![image](https://user-images.githubusercontent.com/73260374/154441588-096a5452-b832-4ddf-a4b5-e47a72b59cba.png)
After adding it.
![image](https://user-images.githubusercontent.com/73260374/154441754-07427ce5-4201-442e-b765-7902408aef74.png)

### Steps to reproduce

1. Add a viewport node
2. Add a 2D/Control Node, a sprite or color rect would do
3. Move the node in the viewport
4. End

**Comment by Chaosus** [comment] 2022-02-17 14:09
Duplicate of https://github.com/godotengine/godot/issues/50185

**Closed by Chaosus** 2022-02-17 14:09 UTC
