### ISSUE TITLE
Can't assign nodes to exported node Array in the editor

### ISSUE THREAD

**Issue by pedrotrschneider** [godotengine/godot#73115] opened 2023-02-11 19:18 UTC
### Godot version

4.0 RC 1

### System information

Fedora Linux 37, Ryzen 7 5600U, Radeon integrated graphics

### Issue description

If I export an Array[Node] (it can be any type of node, be it a custom class or a default node), I can't assign fields in the editor.

### Steps to reproduce

1. Create a new scene of any type

2. Add a script to the root of the scene with the code
``` gdscript
@export var nodes: Array[Node]
```

3. Add some children `Node` to the root of the scene.
4. Try to assign those nodes in the editor to fields in the exported array.

[Screencast from 2023-02-11 16-00-23.webm](https://user-images.githubusercontent.com/62211260/218276927-b6e21465-add7-4c34-a123-ec70ee943d50.webm)

### Minimal reproduction project

[node_export_array.zip](https://github.com/godotengine/godot/files/10714543/node_export_array.zip)

**Comment by YuriSizov** [comment] 2023-02-11 19:20
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by YuriSizov** 2023-02-11 19:20 UTC
