### ISSUE TITLE
Horizontal ScrollBar shown when ScrollContainer child is exactly the same width as the ScrollContainer

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28464] opened 2019-04-27 12:05 UTC
**Godot version:**
v3.1

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
When setting the width of an item to the exact same width as the ScrollContainer that contains it, the ScrollContainer will still add a horizontal scroll bar:

<img width="684" src="https://media.giphy.com/media/fXgpX8oEuHdBXaRDIk/giphy.gif">

The expected behaviour is that only when setting a width _larger_ than the ScrollContainer would a horizontal scroll bar be added.

**Minimal reproduction project:**
[scrollcontainer-scrollbars.zip](https://github.com/godotengine/godot/files/3123875/scrollcontainer-scrollbars.zip)

**Comment by mitchcurtis** [comment] 2019-04-27 12:10
I had set a min_size on the Control that was preventing it from going lower.

**Comment by mitchcurtis** [comment] 2019-04-27 12:38
I've updated this with a new example. The problem is still there.

**Comment by mitchcurtis** [comment] 2019-04-27 14:02
A workaround for this is to disable horizontal scrolling altogether. Once that is done, the behaviour is as expected. A ScrollContainer whose child's width is equal to its own width should behave as if horizontal scrolling was disabled.

**Comment by tom-jk** [comment] 2020-07-30 21:32
can reproduce in 3.1.stable, 3.2.stable, 3.2.3.beta1

MRP: [29012.zip](https://github.com/godotengine/godot/files/5003856/29012.zip)

Try changing min size of the TextureRect (eg. set bigger than ScrollContainer, then smaller, see if scrollbars go). Also run the scene and press Enter, will grow and shrink TextureRect, see what happens. Try a few different sizes for the scrollcontainer.

**reproduction steps:**

1. In a scene with a control, add a scrollcontainer, set size. The size of the scrollcontainer makes a difference. ~For example, at 640x480 the vertical scrollbar appears. At 256x256, no scrollbar appears. At 255x255, both scrollbars appear~ This keeps changing on me, just try different sizes, see what happens (but it's frustratingly temperamental).
2. add a texturerect, set texture->icon.png and set tiled (optional), set min size to scrollcontainer size.

There may now be scrollbar(s) in the scrollcontainer in the editor.

3. save and reload the scene.

Any scrollbars in the editor have now gone. Similarly if you run the scene there'll be no scrollbars.

4. set the texturerect min size to greater than scrollcontainer size (try on each axis, and both).

Scrollbar(s) appear, as they should do.

5. set the texturerect min size back to being the same as scrollcontainer.

Scrollbar(s) may still be there, which they shouldn't be.

----

I had thought that this might be mitigated by enabling editor settings -> update continuously or by otherwise getting the control to redraw, but it's not a rendering issue.

If there's difficulty reproducing the issue I can record a video.

**Comment by mitchcurtis** [comment] 2020-07-31 07:30
Not sure why the bug label was removed from this. It's not a feature request, it's incorrect behaviour. See how other UI toolkits behave.

**Comment by aaronfranke** [comment] 2020-08-24 20:48
In the GIF in the OP, it is necessary to add the horizontal scrollbar, since space is needed for the vertical scrollbar.

**Comment by KoBeWi** [comment] 2024-11-25 13:45
Looks fixed in 4.4.

**Closed by KoBeWi** 2024-11-25 13:45 UTC
Labels: enhancement, topic:gui
