### ISSUE TITLE
Input propagation.

### ISSUE THREAD

**Issue by Zentropic** [godotengine/godot#76871] opened 2023-05-09 02:39 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  When entering a key in a control, eg. a LineEdit, that is also used by an input map, causes the control to receive the input and the input map action to occur.  For example, a body is controlled by WASD, and you type in either of those letters into a LineEdit, the control should be the only sink for that input because it has the focus and only one thing should have the focus.  This is a problem if an interface in a game is active while the action is occurring.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by and-rad** [comment] 2023-05-09 06:34
I don't think this is a bug, but intended behavior. Because you don't know whether specific games *do* want multiple elements to react to the same input. That's what the `Mouse Filter` options and `set_input_as_handled()` functions are for. Maybe [this](https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html) page in the docs makes it clearer?

**Comment by Zentropic** [comment] 2023-05-09 07:14
Or alternately is there any way to change the order so that input is first accepted by Controls, that is, Control._gui_input () executing before Node._input ().  There should be a simple flag that can be changed to specify the order through Viewport.

**Comment by AThousandShips** [comment] 2023-05-09 07:19
Is the `LineEdit` before the node in the scene tree?

**Comment by AThousandShips** [comment] 2023-05-09 07:24
Yes input is passed in that order, and accepted events *should* not be passed on, and `LineEdit` does accept the event and prevent it from propagation

What function do you use for input, the usual `_input`

**Comment by AThousandShips** [comment] 2023-05-09 07:26
Or wait order is reversed

Test if you put the input *after* the node

**Comment by AThousandShips** [comment] 2023-05-09 07:26
See the link above

**Comment by Zentropic** [comment] 2023-05-09 07:27
The LineEdit is in a scene that is a singleton.  The functions I use for checking input are simply in _physics_process () via Input.is_action_pressed ().  I suppose I'll try moving the singleton node further down the tree...

**Comment by AThousandShips** [comment] 2023-05-09 07:28
Oh, that isn't affected btw

**Comment by AThousandShips** [comment] 2023-05-09 07:29
`is_action_pressed` is not affected by the accepting of events, you need to use `_input` if you want to combine GUI and input

**Comment by Zentropic** [comment] 2023-05-09 07:32
Ah, I'll try that then because the order made no difference.

**Comment by AThousandShips** [comment] 2023-05-09 07:32
You should probably use focus events of the gui to control if movement is allowed pr not

**Comment by AThousandShips** [comment] 2023-05-09 07:33
The functions of `Input` are not affected by accepting events and similar, by design

**Comment by Zentropic** [comment] 2023-05-09 07:34
The problem is that I don't want to have to handle the focus on multiple controls just for this, but I did forget that Input works separately to the event system so thanks for that.  I will adjust what's necessary and hopefully it will work as I intend.

**Comment by AThousandShips** [comment] 2023-05-09 07:37
I don't remember if focus is inherited, check if using `has_focus` on some shared parent of your gui

**Comment by AThousandShips** [comment] 2023-05-09 07:41
But I don't think it has to be all that complicated to do event based

I believe focus entered and edited is ordered correctly so you can have one central function pair handling it to update a pause mode or movement inhibit mode

**Comment by AThousandShips** [comment] 2023-05-09 07:45
Or to avoid that all together I'd suggest clearly separating GUI and game controls by using a menu opening and closing, but I'm not sure your specific context is a conventional game context or not

**Comment by Sauermann** [comment] 2023-05-09 08:14
> is there any way to change the order so that input is first accepted by Controls, that is, Control._gui_input () executing before Node._input ()

Within a viewport, the order currently is `Node._input` for all nodes and afterwards `Control._gui_input` and afterwards `Node._unhandled_input`.

Have you tried to use `Node._unhandled_input` instead of `Node._input` in order to implement the WASD-control. This ought to give the `LineEdit` a chance to accept the event beforehand.

**Comment by AThousandShips** [comment] 2023-05-09 08:15
They are using the `Input` singleton it appears so none of this affects it unfortunately

**Closed** 2023-05-09 15:45 UTC
Labels: documentation, topic:input
