### ISSUE TITLE
Add a 'clone project' to the projects window

### ISSUE THREAD

**Issue by drarem** [godotengine/godot#9632] opened 2017-07-13 16:07 UTC
Request to add a 'clone project' to the projects window when it first opens.

Other enhancement to the projects window:
- add default workspace location(s), when creating a new project you can specify A, B, C, etc locations rather than having to navigate all the time to the actual location.

**Comment by vnen** [comment] 2017-07-13 19:08
There's a Default Project Path in the Editor Settings. If set, this path will open by default when creating a new project.

Cloning a project is as easy as duplicating the folder, though the Project Manager could have a shortcut to duplicate + import.

**Comment by drarem** [comment] 2017-07-13 20:20
Thanks, didn't know about the project manager.. never took time to explore the editor :P   besides cutting and pasting, you have to go into the .ini file and update the filename to prevent it having the same name as the copied one.

**Comment by quantum-entangler** [comment] 2018-01-26 18:20
> @vnen said:
> Cloning a project is as easy as duplicating the folder, though the Project Manager could have a shortcut to duplicate + import.

This. 

After installing the demos I wanted to duplicate a project from the projects window and couldn't find the button for it so I went searching to make sure I don't open up a duplicate of this. I don't ever want to be working in the demo projects directly, only a duplicate of the reference project. Saving over them by accident might end up giving me a lot of headaches later on - as such it is a nice little feature that I'd very much like to request. It's little things like this that make all the difference in terms of usability.

Could this be made a milestone for 3.1 or 3.2?

**Comment by Calinou** [comment] 2020-06-18 12:47
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-18 12:47 UTC
Labels: enhancement, topic:editor
