### ISSUE TITLE
Visual Bug on Tab Intendings

### ISSUE THREAD

**Issue by CornerLord** [godotengine/godot#24467] opened 2018-12-19 07:49 UTC
Couldn't find a duplicate.

**Godot version:**
3.1 alpha official

**OS/device including version:**
Windows 10

**Issue description:**
When scrolling scripts, tab intending marks 
![image](https://user-images.githubusercontent.com/30197104/50205729-e209ed80-0371-11e9-8626-46d7ba51a753.png) disappear and reappear.

**Steps to reproduce:**
Write enough code with intendings so you can scroll the script.

**Visual representation:**
Focus on lines 20-29 for example.
![gif](https://user-images.githubusercontent.com/30197104/50206127-1e8a1900-0373-11e9-99b1-84f06050d431.gif)

**Comment by akien-mga** [comment] 2018-12-19 08:15
Duplicate of #24250, fixed by #24327.

**Closed by akien-mga** 2018-12-19 08:15 UTC
Labels: bug, topic:editor
