### ISSUE TITLE
Unable to get the value of the Y orientation more/less than 90 degrees without impacting other axes

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#3681] opened 2016-02-12 09:15 UTC
Ubuntu 15.04, GTX 965M

Unable to get the value of the Y orientation more/less than 90 degrees. This changes the adjacent axis.
http://rghost.ru/7dHwdyrhL

Additional video
http://rghost.ru/6fZrslBwy

**Comment by akien-mga** [comment] 2016-02-12 09:19
Thanks for making this new issue and video :)

I understand the issue better now, I think what might be needed is a hotkey to lock in an axis when rotating objects by dragging in the 3D viewport.

**Comment by akien-mga** [comment] 2016-07-22 07:52
I believe this is also a duplicate of #1479 that will be fixed in 3.0.

**Closed by akien-mga** 2016-07-22 07:52 UTC
Labels: bug, topic:editor, usability
