### ISSUE TITLE
Mono Export Template Marked As Trojan

### ISSUE THREAD

**Issue by SureDroid** [godotengine/godot#23213] opened 2018-10-22 06:44 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10 - 64 bit

**Issue description:**
When downloading the export template (tpk) from the official website or while installing it in-editor, Windows Anti-Virus marks the file as "Win32/Spursint.F!cl" (trojan) with the file marked being "3.0.6.stable.mono\windows_64_release.exe.tmp" and the download is canceled. This worked previously, and all of a sudden, doesn't work anymore. Expected behavior is the tpk is downloaded and can be installed and used for packaging.

**Steps to reproduce:**
Download tpk from [official site](https://godotengine.org/download/windows) or in editor and install.

**Image:**
![trojan](https://user-images.githubusercontent.com/31707957/47280368-b8b02980-d59b-11e8-9f63-6f57aca41e67.png)

**Comment by akien-mga** [comment] 2018-10-22 12:07
@hpvb Any clue on how to debug this?

**Comment by Jalu1** [comment] 2018-10-22 18:52
This is a weird thing, might just be me but it is coming across as a tpz file, not tpk. Why would that happen? Could that be the cause? The file, while downloading, says it is ~340 megabytes, but after downloading is 0 bytes and cannot be opened.

**Comment by SureDroid** [comment] 2018-10-22 22:00
Maybe you could compare the md4 hash and check if the site has been hacked, but I have no clue. If you need me to send my installation files I can. I should also mention that games that have been packaged with the win64 exe also has been detected and removed by the antivirus.

**Comment by Anutrix** [comment] 2019-07-11 10:22
@SureDroid After I clicked reanalyze at your Virus Total link, I changed from 1/62 detection to 0/67 detection. So it seems that it was a false positive.

**Comment by akien-mga** [comment] 2019-07-11 10:35
Closing as we can't impact false positives in anti virus software.

**Closed by akien-mga** 2019-07-11 10:35 UTC
Labels: bug
