### ISSUE TITLE
Empty hidden folders appearing in the current directory at Godot launch

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#49273] opened 2021-06-03 09:20 UTC
**Godot version:**
Godot Engine v4.0.dev.calinou.4e52b8401

**OS/device including version:**
Debian Buster amd64 / Radeon RX550 (radeon)

**Issue description:**
When you launch Godot (from a terminal), it will create an empty HIDDEN .godot/editor folder in the current directory.
Polluting any folder you happen to be in for no reason is bad enough, but that's not all. If you don't have write access to the current folder, then Godot will not even launch - it throws an error and quits immediately.

**Steps to reproduce:**
```
cd /  # Navigate to a folder you don't have write access to
~/godot/godot  # Launch Godot - it will throw an error and not launch
cd ~/Downloads  # Navigate to an empty folder you do have write access to
~/godot/godot  # Launch Godot and observe empty hidden .godot/editor appear (which stays even after you close Godot)
```

**Expected behavior:**
- Godot launches regardless of whether or not do you have write access to the current folder;
- If there is no reason to pollute the current folder (i.e. there is no project in the current folder), Godot creates any of its files in your home directory, not in the current folder.

**Comment by bruvzg** [comment] 2021-06-03 13:23
Same as #49179

**Comment by Calinou** [comment] 2021-06-03 13:54
Duplicate of https://github.com/godotengine/godot/issues/49179 (same cause).

**Closed by Calinou** 2021-06-03 13:54 UTC
Labels: bug, topic:editor
