### ISSUE TITLE
Global volumetric fog light didn't affect at certain camera rotation

### ISSUE THREAD

**Issue by mintyleaf** [godotengine/godot#69583] opened 2022-12-04 21:03 UTC
### Godot version

4.0 beta 7

### System information

MacOS, Forward+, Intel 520

### Issue description

https://user-images.githubusercontent.com/17470408/205515424-e3d1dead-fb3a-41ff-a4b1-4cb3bb896c0c.mov

### Steps to reproduce

- Set up volumetric fog in environment
- Set up a spotlight
- Rotate camera (even) in editor
You don't get a light shafts from spotlights at default camera rotation, but get at any other

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2022-12-04 22:32
Duplicate of https://github.com/godotengine/godot/issues/57722.

**Closed by Calinou** 2022-12-04 22:32 UTC
