### ISSUE TITLE
Popout Code Editor

### ISSUE THREAD

**Issue by infamousflame** [godotengine/godot#30299] opened 2019-07-03 19:03 UTC
I like the built in code editor for godot, but would like to be able to use it on a different monitor while also using the preview mode. Having the ability to pop out the code editor would be a nice feature that I would appreciate.

**Comment by TheDuriel** [comment] 2019-07-03 19:09
4.0 will make multiple windows _possible_. (But it might not come with it.) Its been talked about plenty before.

**Comment by KoBeWi** [comment] 2019-07-03 19:09
Duplicate of #9059
Likely coming finally in 4.0.

**Closed** 2019-07-03 19:09 UTC
