### ISSUE TITLE
Android Apk can't be installed

### ISSUE THREAD

**Issue by GM637** [godotengine/godot#60091] opened 2022-04-10 03:23 UTC
### Godot version

3.5 beta 3

### System information

Android 11, 2 GB ram, x86 ( not confirmed ), GLES 3

### Issue description

I tried to install the new android engine port but it doesn't let me install even if it looks like its doing it. After waiting for like few minutes the app says " App not installed " . I tried all sort of things, restarting, boosting RAM, and freeing Device Space ( I have no idea what i should try to fix actually )

### Steps to reproduce

Theres isnt any reproducing step, im stuck not being able to install the app.

**Comment by sairam4123** [comment] 2022-04-10 04:48
Can reproduce the issue, I got a Moto e5 plus 2017 model.

**Comment by Calinou** [comment] 2022-04-10 17:22
Duplicate of https://github.com/godotengine/godot/issues/59835.

**Closed by Calinou** 2022-04-10 17:22 UTC
Labels: bug, platform:android, topic:export

**Comment by GM637** [comment] 2022-04-13 10:51
Thx!
