### ISSUE TITLE
Tablet not well supported

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21144] opened 2018-08-18 11:02 UTC
Hi there,

I use a Wacom tablet to draw or sculpt, and sometimes i just want to drop assets in Godot and do some tests keeping working with a pen tablet, but Godot seem not working very well with those.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/tablet.jpg

**Comment by groud** [comment] 2018-08-18 12:53
Duplicate of #20474

**Closed** 2018-08-18 12:54 UTC
Labels: archived
