### ISSUE TITLE
Exported games GLES2 do not work

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#26871] opened 2019-03-10 14:55 UTC
**Godot version:**
3.1 RC1

**OS/device including version:**
windows 7 64 bits 8 gb ram core2quad geforce 9800gt

**Issue description:**
It can not be exported. It does not work on web with glsl2
and the .exe does not work either

**Steps to reproduce:**
simply export the project and test it

**Minimal reproduction project:**
simply export the project and test it
![6](https://user-images.githubusercontent.com/12847027/54086826-f4ba1000-432b-11e9-9514-3c5d8105f667.JPG)

![no abre godot](https://user-images.githubusercontent.com/12847027/54086736-08b14200-432b-11e9-9d52-d020dda01455.JPG)
![2](https://user-images.githubusercontent.com/12847027/54086743-0f3fb980-432b-11e9-990b-6fb9d76f772d.JPG)
![3](https://user-images.githubusercontent.com/12847027/54086766-35fdf000-432b-11e9-8a1b-9d8bfb4dfed7.JPG)
![4](https://user-images.githubusercontent.com/12847027/54086786-562daf00-432b-11e9-8d82-c82ba013ec51.JPG)
![5](https://user-images.githubusercontent.com/12847027/54086790-5a59cc80-432b-11e9-8377-98350248cc05.JPG)

**Comment by akien-mga** [comment] 2019-03-10 15:01
> Godot version:
3.1

What exact version...? 3.1 is not released yet.

Please provide a project that reproduces the issue, I can't reproduce it myself.

**Comment by kone9** [comment] 2019-03-10 15:39
![Captura](https://user-images.githubusercontent.com/12847027/54087431-88daa600-4331-11e9-851a-e693866cfaf6.JPG)

**Comment by kone9** [comment] 2019-03-10 15:40
You can download the project from here and open it with that version of godot engine
https://drive.google.com/open?id=1HeyG-cgvHNWsItCFebXLvXpWrMGyIQDP

**Comment by kone9** [comment] 2019-03-10 15:41
Tell me if you need something more.

**Comment by kone9** [comment] 2019-03-10 15:44
![8](https://user-images.githubusercontent.com/12847027/54087518-4c5b7a00-4332-11e9-8293-2a808b0be84b.JPG)

**Comment by akien-mga** [comment] 2019-03-10 15:46
You should give a name to your binaries.

**Comment by kone9** [comment] 2019-03-10 15:48
> 
> 
> > Godot version:
> > 3.1
> 
> What exact version...? 3.1 is not released yet.
> 
> Please provide a project that reproduces the issue, I can't reproduce it myself.

see the comments below

**Comment by kone9** [comment] 2019-03-10 15:49
> You should give a name to your binaries when you export.

I do not understand what you mean by that .... Godot 2 exported the project without complications, I do not understand where the problem is

**Comment by kone9** [comment] 2019-03-10 15:52
> You should give a name to your binaries when you export.
It's okay like that?
![9](https://user-images.githubusercontent.com/12847027/54087607-41551980-4333-11e9-8b28-fdba078a77cb.JPG)

**Comment by kone9** [comment] 2019-03-10 15:53
Ok, now there is another problem
![12](https://user-images.githubusercontent.com/12847027/54087641-909b4a00-4333-11e9-8fa6-ae67d6ebbc8e.JPG)

**Comment by kone9** [comment] 2019-03-10 15:56
the .exe is still closing tell me if you want something else that can help you ... I'll answer in a few hours now I'm going to eat.

**Comment by kone9** [comment] 2019-03-10 15:57
Although it works in the project it does not work when exporting
https://www.youtube.com/watch?v=1sGFox0J5lU

**Comment by kone9** [comment] 2019-03-10 17:18
If you need something else, any video or something, I'll do it ...

**Comment by kone9** [comment] 2019-03-10 18:15
I opened another project and to my surprise I worked GLSL2 in web and the exe
![2](https://user-images.githubusercontent.com/12847027/54089376-183e8400-4347-11e9-8d2f-ec3c4da4879b.JPG)
![5](https://user-images.githubusercontent.com/12847027/54089395-445a0500-4347-11e9-93b5-172fdb5a4011.JPG)
No need to say ... I have no choice but to start using it and doing tests ... Thanks.

**Comment by avril-gh** [comment] 2019-03-10 21:32
> I opened another project and to my surprise I worked GLSL2 in web and the exe

Make sure your project use templates from proper location.

1. Godot editor and export templates MUST be exact same version.
2. There are 2 places from which editor might take templates for exporting depending on settings.

one is default (global) location for templates (if its not set in project setting)
(look editor menu -> open editor data / settings folder -> templates)

and another one is custom location bound to the project (if its set in project settings)
(look menu project -> export -> custom package)

**Comment by akien-mga** [comment] 2019-03-10 22:49
Closing then as it seems to be working.

If you still have an issue with the original project, you need to figure out what's the problem in this specific project (resources not exported for example), but it's likely not a Godot issue.

**Closed by akien-mga** 2019-03-10 22:49 UTC
