### ISSUE TITLE
GDScript 2.0: Nonexistent function 'new' in base 'GDScript' when class used first in built-in script

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#58957] opened 2022-03-09 22:43 UTC
### Godot version

4.0-alpha4

### System information

Ubuntu, Nvidia, Vulkan

### Issue description

Calling `new()` on a `GDSscript` that has been registered via `class_name` causes the aforementioned error when the class is referenced first in an built-in script.

When the class has been extended or instantiated beforehand, the error does not occur.
The error does also not occur when the GDSscript is loaded via `load`or `preload`.

### Steps to reproduce

1. Create a blank project
2. Create a new script with contents:
```swift
extends Node
class_name MyClass
```
3. Create a new scene, add any kind of root node and attach a built-in script with contents:
```swift
extends Node

func _ready():
	MyClass.new()
```
4. Press F6 and notice error log:
> Invalid call. Nonexistent function 'new' in base 'GDScript'.

### Minimal reproduction project

[godot_4_gdscript_new_bug.zip](https://github.com/godotengine/godot/files/8218709/godot_4_gdscript_new_bug.zip)

**Comment by KoBeWi** [comment] 2022-03-09 23:46
Duplicate of #51538

**Closed by KoBeWi** 2022-03-09 23:46 UTC
Labels: bug, topic:gdscript
