### ISSUE TITLE
NavigationAgent2D has repath loop issue

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#95628] opened 2024-08-16 10:01 UTC
### Tested versions

- Reproducible in 4.3.stable, 4.2.1.stable and 4.1.2.stable

### System information

Godot v4.3.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

In this scenario, Blue Godot wants to go to Green Godot : 
![nav_issue_1](https://github.com/user-attachments/assets/b2b3caa2-66c4-44c4-836b-72384bd90d16)

But Blue Godot is stuck in place as it constantly hesitates between 2 paths : 
![nav_issue_2](https://github.com/user-attachments/assets/e00c068f-7d5e-480e-b2f7-e7bba7aecf37)
![nav_issue_3](https://github.com/user-attachments/assets/796edc9d-c014-428d-8f6e-d74c59438837)

Blue Godot _path_desired_distance_ is equal to 10. If I set the _path_desired_distance_ to 20, Blue Godot manages to choose the lower path, but crosses the red obstacle.

This scenario is a simplification of a more complex scenario that suddenly happened in a complex project, with multiple NPCs that constantly use navigation in various scenarios. I tried to adjust _path_desired_distance_ in my project but when I set it higher it breaks on other scenarios (basically, when I set higher values, NPCs paths sometime cross obstacles but NPCs cannot cross these obstacles due to physical collision).

**About this simple scenario, I don't understand how I can end in a repath loop since Blue Godot does not seem to overshoot distance to the next point. Is it kind of a path finding heuristic edge case ?**

### Steps to reproduce

Just run the MRP

### Minimal reproduction project (MRP)

[mrp_nav_repath_loop.zip](https://github.com/user-attachments/files/16635823/mrp_nav_repath_loop.zip)

**Comment by smix8** [comment] 2024-08-16 11:46
Thanks for reporting. This not a bug but a responsiblity of the script coding to fix.

The reason why it is even happening is because the script sets a new target position every single frame.

This queries a new path everytime and resets the entire path every single frame. In turn this breaks every consistency in the movement. Querying a new path is not something that you find in the official documentation script example for this very reason. It is also mentioned in the documentation under the common agent issues. https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#pathfollowing-common-problems

**Comment by rob1gat** [comment] 2024-08-16 14:48
Thanks for your fast and clear answer.

I updated my code by adding a distance check and it works now.

For some reason, I was thinking that the entire path was reset each frame by _get_next_path_position()_ method (instead of _set_target_position()_), so I have assumed that path resetting was inevitable.

Maybe the documentation you linked could be updated to add some hints on what could trigger a path reset ?

**Comment by smix8** [comment] 2024-11-05 22:45
Closing as this is documented in a few places by now like the agent function documentation and common agent problems.

**Closed by smix8** 2024-11-05 22:45 UTC
Labels: topic:navigation, topic:2d
