### ISSUE TITLE
Error: Can't run project: no main scene defined in the project.

### ISSUE THREAD

**Issue by stupid-kid-af** [godotengine/godot#61823] opened 2022-06-08 17:57 UTC
### Godot version

4.0

### System information

X11, UHD 630

### Issue description

I've made an appimage for godot.3.4.4 (stable) and it works very perfectly [https://github.com/stupid-kid-af/Godot-AppImage/releases/tag/godot-3.4.4-stable-mono](url).
But when I made an AppImage for 4.0 (dev) it didn't opened saying that [https://github.com/stupid-kid-af/Godot-AppImage/releases/tag/4.0](url)
`Error: Can't run project: no main scene defined in the project.`

Please try to fix these issues
Thanks

### Steps to reproduce

1. Just open the first one (godot-3.4.4 AppImage) and it works 
2. Download and the open the godot-4.0 AppImage
3. It will say that "Error: Can't run project: no main scene defined in the project."

**Comment by stupid-kid-af** [comment] 2022-06-08 18:05
And also this occur occurs when you open the AppImage of godot executable not in any scene
The actual application doesn't run

**Comment by stupid-kid-af** [comment] 2022-06-08 19:41
Here's my AppRun file I don't think that there is a problem with bundler because it makes AppImage with same AppRun on 3.x
Btw thanks for replying
`#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
EXEC="${HERE}/usr/bin/godot.linuxbsd.opt.tools.64.mono"
exec "${EXEC}"
`

**Comment by stupid-kid-af** [comment] 2022-06-09 19:13
Any help there

**Comment by Calinou** [comment] 2022-06-09 20:59
Looking at the error message, do you have any Godot projects lying around directly within your `$HOME` directory? If so, this is due to the same cause as https://github.com/godotengine/godot/issues/60332.

**Comment by stupid-kid-af** [comment] 2022-06-11 11:12
> Looking at the error message, do you have a newly created Godot projects lying around directly within your `$HOME` directory? If so, this is due to the same cause as #60332.
> 
> Try moving this project away from `$HOME` (that is, within a subfolder like Documents).

Thanks!
I moved AppImage to a subfolder and it worked perfectly but everyone have to move the AppImage. That's weird but only a working way.
Thanks for your support!

**Comment by Calinou** [comment] 2022-06-11 14:07
Duplicate of https://github.com/godotengine/godot/issues/60332 (same cause).

**Closed by Calinou** 2022-06-11 14:07 UTC
Labels: platform:linuxbsd, topic:thirdparty

**Comment by ncce6** [comment] 2024-01-10 09:57
It's because I didn't add the main scene in the project settings, and I solved this problem perfectly after adding it
