### ISSUE TITLE
Expose ScriptEditor's Active TextEdit for EditorPlugins

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#28170] opened 2019-04-18 15:39 UTC
**Godot version:** 3.1-official

**Issue description:**

I'm thinking about making more EditorPlugins, especially related to the Script editor, but there is a problem, is not very easy to figure out which TextEdit is current active. So it would be really useful to have access to it via the `ScriptEditor` or `EditorInterface` classes or something on that lines.

Also this had been requested in https://github.com/godotengine/godot/issues/21417 but as a comment, so I'm making a dedicated issue request for that.

**Comment by rainlizard** [comment] 2021-03-21 01:34
Proposal: https://github.com/godotengine/godot-proposals/issues/2278

**Comment by Paulb23** [comment] 2021-06-01 11:34
Duplicate of godotengine/godot-proposals/issues/2278 fixed by #48605

**Closed by Paulb23** 2021-06-01 11:34 UTC
Labels: enhancement, topic:editor, topic:plugin
