### ISSUE TITLE
AnimationPlayer Node but simplier only for Sprite Animations

### ISSUE THREAD

**Issue by aaronmzn** [godotengine/godot#9323] opened 2017-06-23 01:54 UTC
Basically an AnimatedSprite node + keyframing everything and tracks, specially keyframing a function in a certain frame of the animation or an CollisionShape for hitbox purpose

Spritesheets or multiple image sprites are way simplier, it only needs duration of animation, and if it needs to loop or not. but doing this in the AnimationPlayer node its very complicated because you have put first the timeline length, the step between frames and at this point youre just guessing and trying every number so your animation looks good.

AnimationPlayer is excellent for separated part characters but not so good for simple sprite animations if you want to use its amazing features.

**Comment by nunodonato** [comment] 2017-06-23 07:28
did you try using AnimatedSprite?

**Comment by StraToN** [comment] 2017-06-23 08:47
I confirm, AnimatedSprite does EXACTLY what you want.

**Comment by balfrog** [comment] 2017-06-23 13:41
Really? how? :/ It sure can do animations but can it keyframe everything like in AnimationPlayer?

**Comment by StraToN** [comment] 2017-06-23 15:03
No. 
AnimatedSprite sure is way simpler than AnimationPlayer. Its objective is create simple sprite animations by setting a collection of textures and an FPS setting. If you want more than this, then it is no more "simple" and you probably need AnimationPlayer.

**Comment by homer666** [comment] 2017-06-23 17:10
The one big issue with AnimatedSprite that everyone seems to have is that it requires all your frames to be separate images. To a lot of sprite artists it's a very counter-intuitive requirement; most other engines let you make animations by just feeding in little sprite sheets per animation, and that's what people are used to seeing. Personally I've seen people consider the AnimatedSprite's current "separate image" functionality to be a deal-breaker, notably Game Maker users exploring alternatives.

I wholeheartedly support what @balfrog is proposing, and it would be amazing to see something like this implemented by 3.0. I think it would go a long way toward appealing to novice 2D game developers coming from other engines.

**Comment by bojidar-bg** [comment] 2017-06-23 17:40
Well, maybe we should just make AnimatedSprite/SpriteFrames support texture regions, frames, and whatnot?

Frankly, we already have 4-5 nodes related to animations: AnimationPlayer, AnimationTreePlayer, AnimatedSprite, AnimatedSprite3D, and Tween. Adding one more (SimpleAnimationPlayerForSprite?) is not going to help, at all.

Adding to which, AnimatedSprite already does most of what's needed, and is especially designed for animations of sprites, and people wanting something simple, not as powerful as AnimationPlayer. Which is, accidentially, exactly what @homer666 mentioned.

Potentially, one day, we might add a _tool_, not another node, to the Animation editor (which is used by the AnimationPlayer editor), which would allow people to just say "put these frames uniformly between time A and time B", or maybe something even more tuned to this exact scenario. Potentially, it might even be part of the Asset Library. But, adding a "X node but simpler" is a no-go IMHO.

**Comment by bojidar-bg** [comment] 2017-06-23 17:53
I'd like to also reply to the original post, by mentioning a slight workaround:

If you want an animation from frame X to frame Y, you can just use interpolation between the frames:
![image](https://user-images.githubusercontent.com/5276727/27494152-4493a596-5855-11e7-9de4-3b9ca55af8d1.png)
To do this, just change the last dropdown to "continious" and "linear", instead of the default "discrete".."nearest". Care must be taken for looping animations, since it would also interpolate from the last keyframe to the first. That's why I have duplicated the last one so that it won't be able to interpolate it back to the first.

I don't think this workaround is really useful in all cases, but I wanted to mention it, just in case.

**Comment by bojidar-bg** [comment] 2017-06-24 11:19
> Well, maybe we should just make AnimatedSprite/SpriteFrames support texture regions, frames, and whatnot?

Since we are getting a near-duplicate of that part, I think we should move discussion concerning it to #9340.

Feel free to continue discussing other options here though.

**Comment by balfrog** [comment] 2017-06-24 22:33
we don't need a new node, adding features to one its enough.

**Comment by balfrog** [comment] 2017-06-25 01:51
We don't need a new node, adding features to a existing node its enough,

could be adding the keyframe everything feature + tracks to AnimatedSprite node or a frame only option to AnimationPlayer node to animate sprites only (frame by frame) where you can change the duration of animation

_also a cool feature could be that you can change the duration of certain frames where its 0.5 frames per second but a single frame can say 0.75 secs :)_


> If you want an animation from frame X to frame Y, you can just use interpolation between the frames:
> image
> To do this, just change the last dropdown to "continious" and "linear", instead of the default "discrete".."nearest". Care must be taken for looping animations, since it would also interpolate from the last keyframe to the first. That's why I have duplicated the last one so that it won't be able to interpolate it back to the first.

yes but in the current version its a bit buggy when you want it to loop, I think this will be fixed in 3.0

**Comment by alexzheng** [comment] 2017-06-25 06:06
> I'd like to also reply to the original post, by mentioning a slight workaround:
@bojidar-bg 
It seems there is still a little problem for looping animations.

Say, I have 10 frames, animation length is 1s, and the step is 0.1
I set the first frame to 0 an the last frame to 9, and change to continuous and linear,turn looping on, then the frame for each step becomes (0,0,1,2,3,4,5,6,7,8,0)
the last frame 9 is lost, shouldn't it be  (0,1,2,3,4,5,6,7,8,9,0)?

**Comment by bojidar-bg** [comment] 2017-06-25 11:24
@alexzheng Check #6173 for that, you might notice I didn't tell you to add a keyframe for every frame, and that I said explicitly that the last frame must be duplicated.

**Comment by alexzheng** [comment] 2017-06-25 12:51
Is the issue fixed in the latest GitHub code? 
I did not add keyframe for every frame, I just use continuous mode to  interpolate values.
It seems the  interpolated values are still not correct.

**Comment by kubecz3k** [comment] 2018-04-03 11:31
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:41
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2018-05-29 08:41 UTC
Labels: discussion, topic:core, topic:editor
