### ISSUE TITLE
Transform and Matrix UI elements get out of sync

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#20850] opened 2018-08-09 15:13 UTC
**Godot version:**

a71a5fc0c3f5d487d3f18c3b9e9a768052795e86

**OS/device including version:**

Linux

**Issue description:**

![image](https://user-images.githubusercontent.com/4047289/43907829-b3fea3fa-9bf6-11e8-9235-548c5e7ad113.png)

**Steps to reproduce:**
Change the Transform and Matrix values, move the 3D gismo.

**Minimal reproduction project:**

[2018-08-09-transform-ui.zip](https://github.com/godotengine/godot/files/2274701/2018-08-09-transform-ui.zip)

**Comment by KoBeWi** [comment] 2019-04-18 22:04
The issue is that moving gizmos only update translation/rotation/scale, but not the transform matrix. You need to reselect node to update matrix.

**Comment by KoBeWi** [comment] 2020-07-20 22:01
Changing transform in the inspector works fine now, gizmo still doesn't update transform in 15a9767

**Comment by KoBeWi** [comment] 2021-06-03 21:52
Fixed in 5d9cab3

**Closed by KoBeWi** 2021-06-03 21:52 UTC
Labels: bug, confirmed, topic:editor
