### ISSUE TITLE
4.1.1 raycast on HeightMapShape3D collision Bug

### ISSUE THREAD

**Issue by dr3muchiy** [godotengine/godot#82574] opened 2023-09-30 07:05 UTC
### Godot version
4.1.1

### System information
Windows 10, Nvidia GeForce GTX 1060 / Vulkan

### Issue description
raycast by mouse position through StaticBody3D with HeightMapShape3D at certain angles in certain places doesn't see the collision

Zones that raycast does not see are located on the perimeter of the HeightMapShape3D quad.
But not the entire perimeter, but only in some places.
Closer to the center of the quad there are no raycast glitches

if you change the camera angles, glitch zones may disappear in some places and appear in others.

### Steps to reproduce

run Minimal reproduction project
if you don't move or rotate the camera the raycast-glitch zone will be along the right edge of the HeightMapShape3D quad

if you click on a quad and the raycast works correctly, a red ball will move to the place where you clicked.
also output to the console :"raycast ok"

if the click is in the place of the bug, the ball will not move to the click location,
the output to the console will be  :"raycast result == null"

### control
move - ui_left, ui_right, ui_up, ui_down
To rotate the camera, hold down - mousMiddle
MOUSE__WHEEL_UP/DOWN - lengthen or shorten the camera tripod

### Minimal reproduction project
all code is in tactCam.gd
the raycast_from_mouse() is called from _physics_process()

[raycastHeightmapBug.zip](https://github.com/godotengine/godot/files/12774149/raycastHeightmapBug.zip)

**Comment by dkaste** [comment] 2023-12-06 20:53
This is probably a duplicate of #68238

**Closed** 2023-12-07 07:26 UTC
Labels: bug, topic:physics, topic:3d
