### ISSUE TITLE
Platform 'server' not yet ported to the new GLES3 backend

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#7432] opened 2017-01-05 11:51 UTC
**Operating system or device - Godot version:**
manjaro linux - godot 3.0-alpha

**Issue description** (what happened, and what was expected):
compiling with platform=server are there some errors:
```
drivers/gles3/rasterizer_scene_gles3.cpp:3755:19:

 error: 'glClearDepth' was not declared in this scope
   glClearDepth(1.0);
                   ^
drivers/gles3/rasterizer_scene_gles3.cpp:3867:19: error: 'glClearDepth' was not declared in this scope
   glClearDepth(1.0);
                   ^
drivers/gles3/rasterizer_scene_gles3.cpp:3973:34: error: 'GL_FILL' was not declared in this scope
  glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
                                  ^~~~~~~
drivers/gles3/rasterizer_scene_gles3.cpp:3973:41: error: 'glPolygonMode' was not declared in this scope
  glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
                                         ^
In file included from core/typedefs.h:116:0,
                 from core/rid.h:34,
                 from ./servers/visual_server.h:33,
                 from ./servers/visual/rasterizer.h:33,
                 from drivers/gles3/rasterizer_storage_gles3.h:4,
                 from drivers/gles3/rasterizer_scene_gles3.h:4,
                 from drivers/gles3/rasterizer_scene_gles3.cpp:1:
drivers/gles3/rasterizer_scene_gles3.cpp: In member function 'virtual void RasterizerSceneGLES3::render_shadow(RID, RID, int, RasterizerScene::InstanceBase**, int)':
core/error_macros.h:107:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   do {if ((m_index)<0 || (m_index)>=(m_size)) { \
                          ~~~~~~~~~^~~~~~~~~~
drivers/gles3/rasterizer_scene_gles3.cpp:4318:3: note: in expansion of macro 'ERR_FAIL_INDEX'
   ERR_FAIL_INDEX(shadow,shadow_atlas->quadrants[quadrant].shadows.size());
   ^~~~~~~~~~~~~~
drivers/gles3/rasterizer_scene_gles3.cpp:4341:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (shadow_cubemaps[i].size>shadow_size*2)
                                  
drivers/gles3/rasterizer_scene_gles3.cpp:4419:18: error: 'glClearDepth' was not declared in this scope
  glClearDepth(1.0);
                  ^
```

**Steps to reproduce:**
clone latest git 
scons platform=server tools=no target=debug bits=64

**Comment by hpvb** [comment] 2017-02-16 22:40
I don't think the VisualServer API is stable enough at this time to implement a dummy rasterizer so that the server can actually run. I'll happily do this once reduz gives the go-ahead on the api though.

**Comment by hpvb** [comment] 2017-02-16 22:48
```
<reduz> TMM, not done yet
<reduz> john_cephalopoda, and again, not done yet
 karroffel, also not ready yet :P
 i hope that by begining of April, the API will be stable
```
:)

**Comment by reduz** [comment] 2017-08-05 18:28
probably better to kick server resurrection to 3.1, too many things to do and fix

**Comment by akien-mga** [comment] 2017-09-18 11:11
Closing as duplicate of the (more recent, but also more active) #8361.

**Closed by akien-mga** 2017-09-18 11:11 UTC
Labels: bug, platform:linux, topic:buildsystem, topic:rendering
