### ISSUE TITLE
Creating a new node creates a duplicated child node

### ISSUE THREAD

**Issue by Master-J** [godotengine/godot#38239] opened 2020-04-26 19:11 UTC
**Godot version:**
master (5f645e5d84b73fbf7ff83137d3d0a5f7408c3ba6)

**OS/device including version:**
Window 10 64 bit

**Issue description:**
When creating a new node using the Create Node window the editor will add a duplicate child node to the node you just created.

**Steps to reproduce:**
Open a scene
Open the Create Node window
Select any Node you want to add
Confirm the selection
The selected node will be added to the scene tree with a duplicate of itself as a child of it.

**Minimal reproduction project:**
(Not sure if linking a reproduction project here is meaningfull, the linked gif should be enougth to show the issue, can make one if necessary)
![EditorCreatesDuplicates](https://user-images.githubusercontent.com/54776415/80317162-67bd6900-8802-11ea-86bc-7cd06c59702f.gif)

**Comment by ThakeeNathees** [comment] 2020-04-28 10:05
duplicate of #37331

**Closed** 2020-04-28 10:53 UTC
Labels: bug, topic:editor
