### ISSUE TITLE
Error building android on windows (TypeError: environment can only contain strings)

### ISSUE THREAD

**Issue by badrazizi** [godotengine/godot#2974] opened 2015-12-02 08:06 UTC
TypeErorr: environment can only contain strings

```
C:\godot>scons p=android tools=no target=release 
scons: Reading SConscript files ... 
Godot Android!!!!! (armv7) (with neon) 
scons: done reading SConscript files. 
scons: Building targets ... 
build_gles2_headers(["drivers\gles2\shaders\blur.glsl.h"], ["drivers\gles2\shaders\blur.glsl"]) 
build_gles2_headers(["drivers\gles2\shaders\canvas.glsl.h"], ["drivers\gles2\shaders\canvas.glsl"]) 
build_gles2_headers(["drivers\gles2\shaders\canvas_shadow.glsl.h"], ["drivers\gles2\shaders
\canvas_shadow.glsl"]) build_gles2_headers(["drivers\gles2\shaders\copy.glsl.h"], ["drivers\gles2
\shaders\copy.glsl"]) build_gles2_headers(["drivers\gles2\shaders\material.glsl.h"], ["drivers\gles2
\shaders\material.glsl"]) run(["core\method_bind.inc", "core\method_bind_ext.inc"], 
["core\make_binders.py"]) C:\Program Files\Var\Android_NDK/toolchains/arm-linux-androideabi-
4.8/prebuilt//windows-x86_64/bin/arm-linux-androideabi-g++ /Foplatform\android\os_android.os /c 
platform\android\os_android.cpp /TP -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections 
-funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ 
-D__GLIBC__ -Wno-psabi -march=armv7-a -mfloat-abi=softfp -ftr ee-vectorize -funsafe-
math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED 
-mfpu=neon -D__ARM_NEON__ -O2 -ffast-math -fomit-frame -pointer -fno-exceptions 
-DNO_SAFE_CAST -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL 
-DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED 
-DVO RBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED 
-DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED 
-DSPEEX_ENABLED -DGDSCRI PT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED 
-DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math 
-Itools -Idrivers -I. -Iplatform\andr oid "-IC:\Program Files\Var\Android_NDK\platforms\android-
15\arch-arm\usr\include" "-IC:\Program Files\Var\Android_NDK\sources\cxx-stl\gabi++\include" 
"-IC:\Pro gram Files\Var\Android_NDK\sources\cpufeatures" -Idrivers\builtin_openssl2 
-Iplatform\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl 2\openssl 
-Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2
\crypto\modes -Idrivers\opus\silk\float -Idrive rs\opus -Idrivers\opus\celt -Idrivers\opus\silk 
-Idrivers\opus\silk\float 
scons: *** [platform\android\os_android.os] TypeError : environment can only contain strings 
Traceback (most recent call last): File "C:\Python27\Lib\site-packages\scons-2.3.4\SCons
\Taskmaster.py", line 248, in execute self.targets[0].build() File "C:\Python27\Lib\site-packages
\scons-2.3.4\SCons\Node\__init__.py", line386, in build self.get_executor()(self, **kw) File 
"C:\Python27\Lib\site-packages\scons-2.3.4\SCons\Executor.py", line 362,in __call__ return 
self.do_execute(target, kw) File "C:\Python27\Lib\site-packages\scons-2.3.4\SCons\Executor.py", 
line 344,in do_execute status = act(*args, **kw) File "C:\Python27\Lib\site-packages\scons-
2.3.4\SCons\Action.py", line 909, in __call__ show, execute, chdir, executor) File "C:\Python27
\Lib\site-packages\scons-2.3.4\SCons\Action.py", line 977, in __call__ return c.__call__(self, target, 
source, env, *args, **kw) File "C:\Python27\Lib\site-packages\scons-2.3.4\SCons\Action.py", line 
586, in __call__ stat = self.execute(target, source, env, executor=executor) File "C:\Python27
\Lib\site-packages\scons-2.3.4\SCons\Action.py", line 809, in execute result = spawn(shell, escape, 
cmd_line[0], cmd_line, ENV) File "./platform/android\detect.py", line 88, in mySpawn rv = 
mySubProcess( cmdline, env ) File "./platform/android\detect.py", line 66, in mySubProcess 
stderr=subprocess.PIPE, startupinfo=startupinfo, shell = False, env = env) File "C:\Python27
\lib\subprocess.py", line 710, in __init__ errread, errwrite) File "C:\Python27\lib\subprocess.py", line 
958, in _execute_child startupinfo) 
TypeError: environment can only contain strings 
scons: building terminated because of errors.
```

my environment

```
>>> import os 
>>> os.environ
 {'TMP': 'C:\\Users\\Badr\\AppData\\Local\\Temp', 'COMPUTERNAME': 'BADR-PC', 
'ANDROID_NDK_ROOT': 'C:\\Program Files\\Var\\Android_NDK', 'USERDOMAIN': 'BADR-PC', 
'VS100COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\', 
'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 
'COMMONPROGRAMFILES': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_IDENTIFIER': 
'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files (x86)', 
'PROCESSOR_REVISION': '2a07', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Program 
Files\\Common Files\\Microsoft Shared\\Windows Live;##;C:\\Python27\\;C:\\Python27\\Scripts; 
C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Windows\\system32;C:\\Windows; 
C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\; C:\\Program 
Files\\Lenovo\\Bluetooth Software\\;C:\\Program Files\\Lenovo\\Bluetooth Software\\syswow64; 
C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\; 
C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live; C:\\Program Files\\Intel\\WiFi
\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'PROGRAMFILES(X86)': 
'C:\\Program Files (x86)', 'WINDOWS_TRACING_FLAGS': '3', 'TEMP': 'C:\\Users\\Badr\\AppData
\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 
'PROCESSOR_ARCHITECTURE': 'x86', 'PATHEXT': 
'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'ALLUSERSPROFILE': 
'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\Badr\\AppData\\Local', 'HOMEPATH': '\\Users
\\Badr', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Badr', 'LOGONSERVER': 
'\\\\BADR-PC', 'PROMPT': '$P$G', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 
'ANDROID_HOME': 'C:\\Program Files\\Var\\Android_SDK', 'EMSCRIPTEN_ROOT': 'C:\\Program 
Files (x86)\\EMSCRIPTEN_ROOT', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 
'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'HOMEDRIVE': 
'C:', 'SYSTEMDRIVE': 'C:', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 
'NUMBER_OF_PROCESSORS': '4', 'APPDATA': 'C:\\Users\\Badr\\AppData\\Roaming', 
'PROCESSOR_LEVEL': '6', 'PROCESSOR_ARCHITEW6432': 'AMD64', 
'COMMONPROGRAMW6432': 'C:\\Program Files\\CommonFiles', 'OS': 'Windows_NT', 'PUBLIC': 
'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\Badr'}

```

**Comment by akien-mga** [comment] 2015-12-02 08:44
What version of Godot are you trying to build? Could you try with the latest master branch?
Also the logs are pretty hard to read as there are no newlines... but Windows often does a bad job with newlines so I can't blame you :)

**Comment by badrazizi** [comment] 2015-12-02 08:55
From Nov 28, 2015
I will try with the last commit and post the result

**Comment by akien-mga** [comment] 2015-12-02 08:58
Thanks; I don't expect a lot of changes since Nov 28 though, just wanted to check as the log mentions includes like ```-Idrivers\opus\silk -Idrivers\opus\silk\float``` which were recently removed; but their removal probably won't change much regarding the compilation issue you're having.

**Comment by badrazizi** [comment] 2015-12-02 10:20
also happen with the last commit same error

**Comment by akien-mga** [comment] 2015-12-02 10:28
Thanks for checking.

**Comment by punto-** [comment] 2015-12-02 10:33
I had this problem on another platform recently, I put this in the
"mySubProcess" function in detect.py:

nenv = {}
for k in env:
if type(env[k]) == type(""):
nenv[k] = env[k]


and use that for the call to Popen instead of "env". I'd like to know which
key is not a string tho..

**Comment by akien-mga** [comment] 2015-12-02 10:38
Then maybe try:
```
nenv = {}
badenv = {}
for k in env:
    if type(env[k]) == type(""):
        nenv[k] = env[k]
    else:
        badenv[k] = env[k]
print(badenv)
```
to debug.

**Comment by badrazizi** [comment] 2015-12-02 11:38
thanks for the help 
it's print
{'SystemRoot': u'C:\\Windows'}

**Comment by ZuBsPaCe** [comment] 2015-12-02 15:50
Got the same error and the first error is related to SystemRoot, which seems to be stored as unicode string.

You can add following lines in front of the subprocess.Popen call in platform\android\detect.py (line 67):
 print(env)
 env['SystemRoot'] = 'C:\\Windows'

The first error will be gone, but other errors will appear:
arm-linux-androideabi-g++: error: /Foplatform\android\os_android.os: No such file or directory
arm-linux-androideabi-g++: error: /c: No such file or directory
arm-linux-androideabi-g++: error: /TP: No such file or directory

1) Where does SystemRoot come from? I can't find any reference in godot.
2) I was able to build for android within the last month. But I can't find a working changeset now, which is really strange. Is this caused by something else than godot?

**Comment by akien-mga** [comment] 2015-12-02 15:55
> 1) Where does SystemRoot come from? I can't find any reference in godot.

It seems to be part of the default ENV in Scons: http://www.scons.org/doc/1.2.0/HTML/scons-user/x4613.html It doesn't seem declared explicitely as a Unicode string though, it's strange.

The errors you're having after fixing the string one are the same as #1403.

**Comment by akien-mga** [comment] 2015-12-02 16:02
> It seems to be part of the default ENV in Scons: http://www.scons.org/doc/2.4.1/HTML/scons-user/ch28s02.html It doesn't seem declared explicitely as a Unicode string though, it's strange.

The definition of SystemRoot might come from MSVC or the way Python is setup on Windows though. You can try ```print env.Dump('ENV')``` to check if it's also listed as Unicode there.

Not sure how we should workaround this in Godot's buildsystem though. Maybe ensure that all arguments are converted to ascii strings?

**Comment by ZuBsPaCe** [comment] 2015-12-02 16:26
We could fix the unicode issue like this: https://gist.github.com/ZuBsPaCe/6b1980b42e324b242abb
(Simply copied from someone else: https://groups.google.com/a/continuum.io/d/msg/conda/WyUcv0xdE4g/raWnenTm07kJ)

I don't yet understand, how I can fix the errors afterwards. I'm confused, because it worked not so long ago...

**Comment by ZuBsPaCe** [comment] 2015-12-02 16:49
Hey, I'm able to build godot for android like this without the env.patch above:
scons platform=android target=release tools=no android_neon=no -j8

Please try this, too. Don't know yet why it works like this... Gonna be afk for a while.

**Comment by badrazizi** [comment] 2015-12-03 02:42
that's weird I still get error but this time without saying what is the error
```
c:\godot>scons platform=android target=release tools=no android_neon=no 
scons: Reading SConscript files ... 
Godot Android!!!!! (armv7) 
scons: done reading SConscript files. 
scons: Building targets ... 
build_gles2_headers(["drivers\gles2\shaders\blur.glsl.h"], ["drivers\gles2\shaders\blur.glsl"]) build_gles2_headers(["drivers\gles2\shaders\canvas.glsl.h"], ["drivers\gles2\shaders\canvas.glsl"]) build_gles2_headers(["drivers\gles2\shaders\canvas_shadow.glsl.h"], ["drivers\gles2\shaders\canvas_shadow.glsl"]) build_gles2_headers(["drivers\gles2\shaders\copy.glsl.h"], ["drivers\gles2\shaders\copy.glsl"]) build_gles2_headers(["drivers\gles2\shaders\material.glsl.h"], ["drivers\gles2\shaders\material.glsl"]) run(["core\method_bind.inc", "core\method_bind_ext.inc"], ["core\make_binders.py"]) %ProgramFiles%\Var\Android_NDK/toolchains/arm-linux-androideabi-4.8/prebuilt//windows-x86_64/bin/arm-linux-androideabi-g++ -o platform\android\os_android.os -c-DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__GLIBC__ -Wno-psabi -march=armv7-a -mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -mfpu=vfpv3-d16 -O2 -ffast-math -fomit-frame-pointer -fno-exceptions -DNO_SAFE_CAST -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -I. -Iplatform\android -Iplatform\android\%ProgramFiles%\Var\Android_NDK\platforms\android-15\arch-arm\usr\include -Iplatform\android\%ProgramFiles%\Var\Android_NDK\sources\cxx-stl\gabi++\include -Iplatform\android\%ProgramFiles%\Var\Android_NDK\sources\cpufeatures -Idrivers\builtin_openssl2 -Iplatform\android\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\modes platform\android\os_android.cppscons: *** [platform\android\os_android.os] 
scons: building terminated because of errors.
```

**Comment by ZuBsPaCe** [comment] 2015-12-03 07:56
@badrazizi Looks like the environment variable ANDROID_NDK_ROOT is not correct. Please remove %ProgramFiles% from the string and replace it with a full path. Mine looks like this:
![environment variable android ndk](https://cloud.githubusercontent.com/assets/4233942/11554769/3aa0269c-999b-11e5-8406-27d1edbc29e5.png)

For Reference, here's the output I get: https://gist.github.com/ZuBsPaCe/18e3e599af3432b2064b

**Comment by akien-mga** [comment] 2016-03-07 12:27
Based on the above comment, I think this was a user configuration issue, so closing.

**Closed by akien-mga** 2016-03-07 12:27 UTC
Labels: bug, platform:android, platform:windows, topic:buildsystem

**Comment by MarufSarker** [comment] 2016-07-11 20:12
(_for future visitors_)

If you are still having this issue on _Windows_, this might help you.

**Scenario:**
```
Build For:             Android
Python:                2.7.12
SCons:                 v2.5.0.rel_2.5.0:3544:95d356f188a3[MODIFIED]
Android SDK API:       23
Android SDK Tools:     25.1.7
Android NDK:           r12b-windows-x86_64
Gradle:                2.14
Java:                  1.8.0_92
JavaC:                 1.8.0_92
```
(_If your scenario is different, and the solving method does not solve your problem, you might find my debugging process helpful_)

**Debugging:**
As many were mentioning `detect.py` and the solution was also provided for the `detect.py`, I initially added `print(env)` inside `detect.py` (_mentioned locations by others_), but was unsuccessful to even get a console log.
Then, I followed the error log and found that, the `methods.py` file was logged along with `SCons`. So, I added the `print(env)` inside `methods.py` before error lines (_inside `use_windows_spawn_fix` > `mySpawn`_).
The logged messages were different (_not dramatic but slightly_) than Python's standard `os.environ`. Here the `'PATH'` key's value had an '`u`' flag before it, which flagged the value as unicode, I assume, and that caused the issue or, sanitizing it resolved the issue, visibly.

**Solving Method:**
(_the original solution was provided by ZuBsPaCe at [https://gist.github.com/ZuBsPaCe/6b1980b42e324b242abb](https://gist.github.com/ZuBsPaCe/6b1980b42e324b242abb#file-env-patch-L11)_)

In
  `./methods.py` file, at line _1378_ (_line number might change at any time_),

inside
```
def use_windows_spawn_fix(self, platform=None):
    def mySpawn(sh, escape, cmd, args, env):
```
before
```
if len(cmdline) > 32000 and cmd.endswith("ar") :
```
add
```
env = {str(key): str(value) for key, value in env.iteritems()}
```
to sanitize the provided/passed `env` value.

Resulting code might look like this:
```
def mySpawn(sh, escape, cmd, args, env):
  newargs = ' '.join(args[1:])
  cmdline = cmd + " " + newargs
  env = {str(key): str(value) for key, value in env.iteritems()}
```

(_This process might be called from platform specific `detect.py` files, but as my debugging process's call stack didn't showed the `detect.py` file, so I added this line inside `methods.py`, although the solution was initially mentioned for `detect.py`_)

**What does the line do?**
`env` (_passed on_) is a dictionary type Python variable, where sometimes passed value from _Windows_ might add a `u` flag to indicate _unicode_ value. Like -
`{..., 'PATH': u'...;..', ...}`
The `u` flag causes the problem.
The code sanitizes the key-value pairs and creates a standard dictionary type value.

_For clarifications, see -_
[https://stackoverflow.com/questions/3294889/iterating-over-dictionaries-using-for-loops-in-python](https://stackoverflow.com/questions/3294889/iterating-over-dictionaries-using-for-loops-in-python)
[https://stackoverflow.com/questions/19121722/build-dictionary-in-python-loop-list-and-dictionary-comprehensions](https://stackoverflow.com/questions/19121722/build-dictionary-in-python-loop-list-and-dictionary-comprehensions)
[https://www.python.org/dev/peps/pep-0274/](https://www.python.org/dev/peps/pep-0274/)

Thanks :)

_N.B._: If this line (_the added code snippet_) does not cause any issue (_tested by others or Godot members  (@akien-mga)_) for other platforms (_namely linux, osx_), permanently adding the line inside `methods.py` might be helpful for _Windows_ users.
