### ISSUE TITLE
Warning about unused variables, that are being assigned in dictionaries.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#28513] opened 2019-04-29 15:38 UTC
**Godot version:**

a0180fa

**OS/device including version:**

Win10 64-bit

**Issue description:**

Sometimes warnings appear about not using variables when they're assigned within dictionaries.

![image](https://user-images.githubusercontent.com/13004169/56907773-aadce300-6aad-11e9-8d21-f9074f173360.png)

**Steps to reproduce:**

Use code like the following:

```
extends Node2D

export var some_float : float = 1.0

func _ready():
	pass
	
	
func make_dictionary():
	
	var d = {
		
		the_float = some_float
	}
	
	return d
```

**Comment by akien-mga** [comment] 2019-04-29 15:39
Duplicate of #20975.

**Closed by akien-mga** 2019-04-29 15:39 UTC
