### ISSUE TITLE
Discarding unsaved changes doesn't actually discard unsaved changes

### ISSUE THREAD

**Issue by danielzting** [godotengine/godot#40199] opened 2020-07-08 04:03 UTC
**Godot version:**

v3.2.2.stable.official

**OS/device including version:**

macOS Catalina 10.15.5 (19F101)
MacbookAir8,1

**Issue description:**

If you try to close an unsaved script and discard its changes, the changes are in fact not saved to disk. However, opening the script the next time will bring back the changes. In addition, the output console shows the following errors:

```
 core/io/config_file.cpp:296 - ConfigFile parse error at /Users/danielting/Library/Application Support/Godot/projects/human-computer-simulator-e3ec1ec4e8437580903c6b50e04cac9d/project_metadata.cfg:14: Unexpected identifier: 'PackedColorArray'..
 core/io/config_file.cpp:296 - ConfigFile parse error at /Users/danielting/Library/Application Support/Godot/projects/human-computer-simulator-e3ec1ec4e8437580903c6b50e04cac9d/project_metadata.cfg:14: Unexpected identifier: 'PackedColorArray'..
 core/io/config_file.cpp:296 - ConfigFile parse error at /Users/danielting/Library/Application Support/Godot/projects/human-computer-simulator-e3ec1ec4e8437580903c6b50e04cac9d/project_metadata.cfg:14: Unexpected identifier: 'PackedColorArray'..
 Cannot load editor settings from file '/Users/danielting/Library/Application Support/Godot/projects/human-computer-simulator-e3ec1ec4e8437580903c6b50e04cac9d/project_metadata.cfg'.
```

*However x2*, this only happens if the changes are syntactically correct.
Note: running the project seems to always load whatever is actually on disk.

**Steps to reproduce:**
1. Open any script
2. Add something like `print(0)` anywhere
3. Click File -> Close and choose Discard
4. Verify outside the editor that the changes have seemingly been discarded, but...
5. Open the file again, the changes are still there?
6. Change `print(0)` to something with invalid syntax like `print(0*)`
7. Close and reopen file, this time the changes got discarded??

It seems like Godot is checking the syntax and if it is correct, it stores the file contents in some sort of cache. Otherwise, it reverts back to the last syntactically correct edit. You can check this behavior by first copy-pasting `print(0*)` and reopening; the whole line will be removed. But if you first type `print(0)` and then add the asterisk, only the asterisk will get removed.

**Comment by KoBeWi** [comment] 2021-03-06 19:25
I can confirm this in 3.2.4 rc3 and a4b5edf
The error doesn't appear though.

**Comment by Calinou** [comment] 2021-06-04 21:31
Duplicate of https://github.com/godotengine/godot/issues/18010.

**Comment by Naros** [comment] 2023-10-05 02:30
I can also reproduce this against 4.2.dev5.

**Closed** 2023-10-05 14:34 UTC
Labels: bug, topic:editor, confirmed
