### ISSUE TITLE
Method selector in the script editor does not take soft wrapping into account, leading to incorrect scrolling

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#58649] opened 2022-03-01 09:49 UTC
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

I remember that initially the method title was located at the top of the screen.
Now for some reason the method title is randomly placed when a method is selected.

https://user-images.githubusercontent.com/19652075/156145995-9a76c1f5-3a5d-4b0e-ac1c-3220d8247a7d.mp4

### Steps to reproduce

see the video

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2022-03-01 15:30
> Now for some reason the method title is randomly placed when a method is selected.

This occures because the method may be near the end of the script. In this case, it's not possible for the editor to scroll down unless **Scroll Past End Of File** is enabled in the Editor Settings.

**Comment by Torguen** [comment] 2022-03-01 20:15
No!, watch the video, watch the scroll bar on the right, the methods I select are pretty far from the end, except one of them. All the others should be placed at the top of the screen.

**Comment by Torguen** [comment] 2022-03-04 17:22
With the option "no distraction mode" activated it works even worse, the method is located at the bottom.
I think this is a bug, not a discussion.

https://user-images.githubusercontent.com/19652075/156811430-ed751c1e-2235-45a4-87c0-c8773e883b11.mp4

**Comment by Calinou** [comment] 2022-03-04 18:44
I see what's happening now. This bug happens because the method selector doesn't take soft wrapping into account when scrolling.

cc @Paulb23

**Comment by Torguen** [comment] 2024-02-06 17:24
Still in 3.6 beta 4

**Comment by kitbdev** [comment] 2024-07-24 03:14
- Is there a difference between this and https://github.com/godotengine/godot/issues/70438?

**Comment by Torguen** [comment] 2024-07-24 04:01
> * Is there a difference between this and [Selecting methods in script editor methods list does not position them consistently when scrolling, if Word Wrap option is enabled. #70438](https://github.com/godotengine/godot/issues/70438)?

Is the same. I forgot I had already reported it.

**Comment by akien-mga** [comment] 2024-07-24 07:09
Duplicate of #70438.

**Closed by akien-mga** 2024-07-24 07:09 UTC
Labels: bug, topic:editor
