### ISSUE TITLE
Does gdscript export to android/ios already obfuscated or keep as original?

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#37669] opened 2020-04-07 17:49 UTC
I mean var name, function name,,...
Example in gdscript:
func myname():
 var myvar1
 var myvar2

Does it keep that function "myname" and that vars when export project to android/ios or it will be converted to something else?  I heard it will be converted to bytecode in .pck but don't know how about .apk file?

**Comment by Ev1lbl0w** [comment] 2020-04-07 17:56
I don't think so *(for any platforms, as a matter of fact)*, look here: #19790

**Comment by Calinou** [comment] 2020-04-07 18:06
Duplicate of #24716.

**Closed by Calinou** 2020-04-07 18:06 UTC
