### ISSUE TITLE
Invalid operands 'Vector2' and 'Nil' in operator 'not'

### ISSUE THREAD

**Issue by juliohq** [godotengine/godot#69807] opened 2022-12-09 13:41 UTC
### Godot version

4.0 beta 7

### System information

Arch Linux, Vulkan 1.2.0, AMD Radeon RX 560, i3-2120

### Issue description

Checking `if not direction` raises `Invalid operands 'Vector2' and 'Nil' in operator 'not'.`.

It works:
```gdscript
if not Vector2():
    pass
```

### Steps to reproduce

```gdscript
var direction = Vector2()

if not direction:
    pass
```

### Minimal reproduction project

```gdscript
var direction = Vector2()

if not direction:
    pass
```

**Comment by juliohq** [comment] 2022-12-09 13:43
Seems to be related to #53108.

**Comment by KoBeWi** [comment] 2022-12-09 13:50
Duplicate of #44688

**Closed by KoBeWi** 2022-12-09 13:50 UTC
