### ISSUE TITLE
'Kakaotalk' makes Tooltips broken.

### ISSUE THREAD

**Issue by dewcked** [godotengine/godot#52935] opened 2021-09-22 13:18 UTC
### Godot version

3.3.3 stable

### System information

Windows 10 build 19043.1165

### Issue description

Hovering is broken when [KakaoTalk](https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=ENG&tab=all) is running and on system tray so tooltips won't appear. Hovering works fine if you quit the Kakaotalk.

### Steps to reproduce

Download KakaoTalk from link, install and run it. Then open Godot Engine and try to hover anything... tooltips are totally broken. then in the system tray, exit Kakaotalk. try again hovering and you will see it working again. Order is not important.

**Comment by Calinou** [comment] 2021-09-22 13:32
Duplicate of https://github.com/godotengine/godot/issues/32990 (same cause). This may be fixed in 4.0 as tooltips are separate windows there.

**Closed by Calinou** 2021-09-22 13:32 UTC
