### ISSUE TITLE
RichTextLabel freezes Godot 4.1-rc2 on Fit Content

### ISSUE THREAD

**Issue by nextonphotos** [godotengine/godot#78932] opened 2023-07-02 04:48 UTC
### Godot version

v4.1.rc2.official [46424488e]

### System information

Godot v4.1.rc2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 30.0.15.1278) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

Under certain circumstances, attempting to set Fit Content on a RichTextLabel causes Godot to freeze and eventually just close.  The problem doesn't seem to happen for me on Godot_v4.0.3-stable_win64 using the same sample project.

### Steps to reproduce

I start a new scene with a Control node as root.  I add a RichTextLabel as child of the Control and put some random text in it.  Then under Layout->transform for the label, I reset the size, which results in x of 1 and y of 0.

At this point, I check and then uncheck the Fit Content option in RichTextLabel. Everything works as expected. If after I uncheck the box, I switch over to the Control node and then switch immediately back and try to check the Fit Content box again, Godot freezes and eventually crashes.

It's happened randomly at other times, but this is the most reliable way I've found to make it always crash for me.

If I open the attached sample project, switch to the label, check and uncheck Fit Content, switch to the Control and immediately back to the label and then try to check Fit Content again, it crashes every time.

### Minimal reproduction project

[RichText Error.zip](https://github.com/godotengine/godot/files/11928707/RichText.Error.zip)

**Comment by qarmin** [comment] 2023-07-02 06:08
Looks like duplicate of https://github.com/godotengine/godot/issues/78849

**Comment by akien-mga** [comment] 2023-07-02 10:30
Related to #78912.

**Comment by nextonphotos** [comment] 2023-07-02 15:42
> Looks like duplicate of #78849

Yeah, I saw that one before I made the report, but since BBCode didn't need to be enabled for the crash to happen for me, I wasn't sure if it was a duplicate or not. If it is, at least there is another test case for the fix.

**Closed** 2023-07-03 13:27 UTC
Labels: bug, regression, topic:gui
