### ISSUE TITLE
HTML5 export should warn on large textures

### ISSUE THREAD

**Issue by novalis** [godotengine/godot#68388] opened 2022-11-07 22:00 UTC
### Godot version

3.5.1

### System information

HTML5, Chrome on Android (and Mobile Safari on iOS), GLES2 or 3

### Issue description

I exported my game to HTML5, and it refused to load on Mobile Safari -- I just got a blank screen after the progress bar.  On Chrome, it loaded, but a TileSet was rendered in all black.  It turned out that the TileSet was 4608x512, which has a dimension larger than 4096.  By rearranging the tiles (to a 1536x1536 tileset), I was able to make it work.  I would have liked the HTML5 exporter to say "Sorry, you have an asset that's too big -- if you export this, it won't work".

### Steps to reproduce

Create a texture with a dimension larger than 4096 (or perhaps 2048?)

**Comment by Calinou** [comment] 2022-11-07 22:52
Duplicate of https://github.com/godotengine/godot/issues/31414.

**Closed by Calinou** 2022-11-07 22:52 UTC
