### ISSUE TITLE
Controls focus_exited signal doesn't seem to work for regrabbing focus

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#35089] opened 2020-01-13 16:56 UTC
**Godot version:**
v3.1.2

**OS/device including version:**
Windows 10 Pro Education 64 bit

**Issue description:**
the focus_exited signal can't be used for locking focus by using `grab_focus()` and `grab_click_focus()`

**Steps to reproduce:**
- download this project
[AstroWars.zip](https://github.com/godotengine/godot/files/4054683/AstroWars.zip)
- run it
- press a button either by keyboard or mouse
- while its flashing try to move the selection
- see that it moves

**Minimal reproduction project:**
see above

**Comment by tom-jk** [comment] 2020-07-20 19:01
The problem in the case of this particular project is that you create an infinite loop of grabbing focus back and forth:

- A gets focus, B loses focus
- B steals focus back from A, A loses focus
- A steals focus back from B, B loses focus,
- B steals focus back and so on...

You can see this by adding prints to your focus and unfocus callbacks.

A straightforward solution is to keep a record of who exactly should own the focus, for example:

```gdscript
extends Control

var lock_focus = false
var lock_onto = null

...

func _on_option_press(node):
	lock_onto = node
	goto_scene(15, 4, null)

func _on_option_focus(node):
	$Options/Rect.rect_position = node.rect_position
	
func _on_option_unfocus(node):
	if (lock_focus and lock_onto == node):
		node.grab_click_focus()
		node.grab_focus()

...
```

So, this is not a bug in Godot.

**Comment by Calinou** [comment] 2020-07-20 20:19
Closing per @tom-jk's comment.

**Closed by Calinou** 2020-07-20 20:19 UTC
Labels: enhancement, topic:gui
