### ISSUE TITLE
call_group() always fails

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#72308] opened 2023-01-29 13:39 UTC
### Godot version

v4.0.beta.custom_build [a3dae9e54]

### System information

Ubuntu

### Issue description

using `get_tree().call_group()` seems to always fail with an unspecific "Method/function failed." error message.

please see MRP.

### Steps to reproduce

```swift
extends Node2D

func _ready():
	get_tree().call_group("test", "hide")
```
```
E 0:00:00:0412   main.tscn::GDScript_i80u7:6 @ _ready(): Method/function failed.
  <C++ Source>   ./core/object/method_bind.h:162 @ ptrcall()
  <Stack Trace>  main.tscn::GDScript_i80u7:6 @ _ready()
```

### Minimal reproduction project

[godot_4_call_group_bug.zip](https://github.com/godotengine/godot/files/10529876/godot_4_call_group_bug.zip)

**Comment by kleonc** [comment] 2023-01-29 17:34
Regression, caused by #71844. cc @vonagam
(MRP works fine in https://github.com/godotengine/godot/commit/0587ac3f5ae829fd14488648ed2214df0780096a, doesn't work in https://github.com/godotengine/godot/commit/4011a0915efd90854247a609651d7e31b412b1da)

**Comment by vonagam** [comment] 2023-01-29 19:47
Ok, this is some preexisting problem which was revealed by my change. The parameters type of `call_group` are string names, and now strings (shown in the example) are converted to string names according to the types. But this produces the shown error. You can reproduce the issue before my changes by calling with `(&"test", &"hide")`.

**Comment by KoBeWi** [comment] 2023-01-30 16:03
> Ok, this is some preexisting problem which was revealed by my change.

Which means it's a duplicate of #65689

**Closed by KoBeWi** 2023-01-30 16:03 UTC
Labels: bug, topic:core, topic:gdscript, regression
