### ISSUE TITLE
Scene files changing in unexpected way after saving

### ISSUE THREAD

**Issue by Srogozins** [godotengine/godot#4126] opened 2016-03-22 23:53 UTC
**Operating system or device:**
Arch Linux

**Issue description** (what happened, and what was expected):
It appears that whenever I save a scene file in the editor(so far tested with TSCN and XML formats) in addition to whatever changes I make, additional changes are introduced, and this happens even if I don't make any changes myself. The changes seem to be related to sub_resources, e.g., their IDs get switched and occur all over the file. This complicates committing changes to scenes in an SCM system, making it a choice between making a messy commit or sorting what was intentional change and what wasn't each time. 
If it's an intended feature, there should be a way to disable it, or at at least a way to diff the scene while ignoring these changes should be provided.

**Steps to reproduce:**
Seems to occur with scenes that have multiple nodes and resources. It's enough to just open the scene and immediately save it in the editor. The scene file registers as changed after that. Tested on v.2.0.1

**Link to minimal example project** (optional but very welcome):
 Can be reproduced with the [platformer demo](https://github.com/godotengine/godot/tree/master/demos/2d/platformer).
Sample diffs of the occurring changes on a scene from my project and from the platformer demo:
https://gist.github.com/Srogozins/f867df7c60c5bcfe3790

**Comment by akien-mga** [comment] 2016-03-23 06:56
Shortly before the 2.0 release, a more stable ordering mechanism was added at least for TSCN; do you get such random changes reliably with TSCN? The changes shown in your diff seem to go from a badly ordered set of subresources to a properly ordered one (1, 2, 3, etc.). Note that I've also noticed such strange behaviours when converting XML files to TSCN: the format after the conversion is a bit messed up, and the scene has to be saved a second time for the "final" ordering to be applied.

As for XML, I don't know if the fixed ordering was applied there or not. At any rate, those random file changes are something I've always been complaining about, and the objective is to make sure they don't happen :)

**Comment by Srogozins** [comment] 2016-03-23 21:11
I can't say that I've been able to reliably get these changes yet, so it might have been a bit too hasty to say that this happens *whenever* a scene is saved, I just didn't see any system to it. Your explanation is good news to me, because I indeed have converted my scenes from XML to TSCN. If that really is going to be a one time occurrence that can be made to happen right after the conversion, and its changes encapsulated in the conversion commit, I can find a way to work around it without letting this become an obstacle.

Though, this makes me wonder why wouldn't the ordering be done as part of the conversion.

**Comment by akien-mga** [comment] 2016-03-23 21:45
Maybe the ordering is done in the function Save, but not Save as? Or only when saving an existing TSCN to TSCN, instead of creating it for the first time, if those are different functions. I can't check it right now, but I guess that by looking in the git history to find the commit where @reduz added the ordering mechanism, one could already see where it's included and try to find where it's missing.

**Comment by reduz** [comment] 2016-03-23 21:56
No.. They should alwas be ordered, but it's possible that this is an old
file saved as new?

**Comment by reduz** [comment] 2016-06-21 01:40
did not get any further feedback with this issue, it is possible that an old scene saved as new changes order... other than that i don't know

**Comment by davcri** [comment] 2017-11-15 17:56
Confirming this issue: I discovered this strange behaviour while using git to share code with my friends.

I made a video that shows steps to reproduce the bug using the official platformer demo:  https://youtu.be/ugBndXHI1dw
In the video I also edit a node name, but I think that it is not necessary.

**Comment by Zylann** [comment] 2017-12-26 19:09
Happened to me in 2.1.4 today, I added a new prop to an existing level and almost got the entirety of the TSCN be modified because of resource ID swaps:

![image](https://user-images.githubusercontent.com/1311555/34362968-5327a1d8-ea78-11e7-9e6a-68696cb19bef.png)

Another occurence of this happened to me earlier with my `tileset.tres`, where every change in it was... nothing. Just pure ID swaps for the sake of it, no idea how they happened. Maybe the resource got saved again when a scene referencing it was saved...

![image](https://user-images.githubusercontent.com/1311555/34363039-b21551ae-ea78-11e7-9f1d-7b0f0812be9d.png)

**Comment by romlok** [comment] 2018-03-23 13:46
I just experienced this today in 3.0.2.
All the project had is two simple 3D scenes, which are instanced into a test scene. All three had been individually saved and committed, but numerous sub-resources within the two instanced scene files then got renumbered when I hit "play" on the project.

**Comment by jbibbo** [comment] 2018-05-16 19:30
i think we have also experienced this bug. We might have a bit of niggle to the problem so I will describe our situation:

- v3.0.2
- main scene has maybe three or four levels deep of structure.
- two developer working on two different platforms: mac and win.

if Developer A ( win ) saves a scene, then s(he) is able to reopen/play without any changes to the project. However, if Developer B (mac) opens and plays the scene it saves it out and scene and modifies in wildly, unexpected ways.

**Comment by DualMatrix** [comment] 2018-09-16 14:59
If I recall correctly this issue was fixed in one of the 3.0.x versions.

**Comment by Chaosus** [comment] 2018-09-16 15:07
Yes, but it also can be an issue for 2.x versions..

**Comment by akien-mga** [comment] 2018-09-17 09:05
I doubt any additional work will be done on this for the 2.1 branch (though the initial issue reported here might be fixed in 2.1.5 to some extent), so closing as fixed in 3.1.

**Closed by akien-mga** 2018-09-17 09:05 UTC
Labels: bug, topic:core
