### ISSUE TITLE
Window node fullscreen mode not working

### ISSUE THREAD

**Issue by jeanahelver** [godotengine/godot#78530] opened 2023-06-21 17:48 UTC
### Godot version

4.0.3.stable

### System information

windows 11

### Issue description

fullscreen on the window node is not working and will show up as a windowed.

### Steps to reproduce

disable Embed Subwindows in Project Settings/Display/Window.
create a window node and set its mode to fullscreen.

### Minimal reproduction project

[fullscreen.zip](https://github.com/godotengine/godot/files/11821834/fullscreen.zip)

**Comment by akien-mga** [comment] 2023-06-21 20:58
I can't reproduce the issue on Linux (KDE on X11) with 4.0.3. Might be Windows specific?

**Comment by jpcerrone** [comment] 2023-06-22 12:32
I can reproduce it on Windows 11 on the latest master (e74bf831c2d3ece79b849405f03999281f807648) . I'll try taking a look!

**Comment by jpcerrone** [comment] 2023-06-22 17:57
I think I figured out where the problem is. It starts inside the [Window::_make_window](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/scene/main/window.cpp#L539) function. 

The [DisplayServer::get_singleton()->window_set_mouse_passthrough(mpath, window_id);](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/scene/main/window.cpp#LL569C10-L569C10) call resets the `wd.fullscreen` property to false, and this, during the call to [_update_window_size();](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/scene/main/window.cpp#L588) is what ends up re-setting the window to not be fullscreen.

Inside `window_set_mouse_passthrough` , the function call 
https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/platform/windows/display_server_windows.cpp#L1000 generates a `WM_WINDOWPOSCHANGED` message (as mentioned in [the MSDN docs](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/platform/windows/display_server_windows.cpp#L1000)). It is [the handling of this message](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/platform/windows/display_server_windows.cpp#LL3403C7) that ends up setting the `wd.fullscreen` property to false. It then fails to reset it to `true` because the next condition isn't met: 
```c++
if (window_rect.position == screen_position && window_rect.size == screen_size) {
	window.fullscreen = true;
}
```

The handling of this message can be confirmed to be the culprit since commenting out the [SetWindowRgn(windows[p_window].hWnd, nullptr, TRUE);](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/platform/windows/display_server_windows.cpp#L1000) line makes it so that the `wd.fullscreen` property isn't reset and it fixes the problem.

I' haven't been able to figure out what should be changed here. I'm not sure whether the  `SetWindowRgn(windows[p_window].hWnd, nullptr, TRUE)`; is even needed (since it's setting the region to `NULL`). Or if a change should be made inside the `WM_WINDOWPOSCHANGED` handling to account for cases where the screen is in fullscreen mode.

Hope this helps someone with more knowledge than I have figure out what to do.

**Comment by jpcerrone** [comment] 2023-06-23 14:52
Looking into it a bit more, it seems that the next portion of the `WM_WINDOWPOSCHANGED` handling code is indeed the culprit:
``` c++
if (window_rect.position == screen_position && window_rect.size == screen_size) {
	window.fullscreen = true;
}
```
Since in fullscreen mode there's a 1px border around the entire window, this comparisson fails since it compares `[-1,-1, 1921, 1081]` with  `[0, 0, 1920, 1080]`.

Something that could be done is to detect when this kind of border is present and ignore it before comparing. Like this:
``` c++
RECT wrect;
GetWindowRect(hWnd, &wrect);

// In fullscreen mode, the window rect can have a 1px border around its full resolution, so ignore it for the rect comparissons.
if (wrect.left < 0){
	int offset = wrect.left;
	wrect.left -= offset;
	wrect.right += offset;
}
if (wrect.top < 0){
	int offset = wrect.top;
	wrect.top -= offset;
	wrect.bottom += offset;
}
```

I tested adding the previous section of code and the issue dissapears. I also checked to see if https://github.com/godotengine/godot/issues/57787 re-appears with these changes but it doesn't. (It's the issue that was intended to be fixed by https://github.com/godotengine/godot/pull/57790)

**Comment by bruvzg** [comment] 2023-07-04 10:03
> Since in fullscreen mode there's a 1px border around the entire window, this comparisson fails since it compares [-1,-1, 1921, 1081] with [0, 0, 1920, 1080].

This should never happen (client rect can be 1 pixel smaller, but window size should be exact), so something else is wrong.

**Closed** 2023-07-08 16:24 UTC
Labels: bug, topic:core, topic:porting, needs testing
