### ISSUE TITLE
Back button doesn't navigate backwards in script editor's help

### ISSUE THREAD

**Issue by pigigi** [godotengine/godot#44601] opened 2020-12-22 22:32 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10

**Issue description:**
Reading help from the script editor, I clicked an internal link. Clicking the back button brought me back to the code window I was in before searching. I would've expected to be brought back to where he was before following the link.

I suppose the current behavior makes sense and is consistent. I wish there was a way to navigate backwards in the help though.

Couldn't find a discussion about the current behavior. Proposal?

**Steps to reproduce:**
- Search the script editor's offline help.
- Click a link.
- Press the backwards-pointing arrow in the top right corner of script editor.

**Minimal reproduction project:**
None needed.

**Comment by Calinou** [comment] 2020-12-22 22:50
Duplicate of https://github.com/godotengine/godot-proposals/issues/954.

**Closed by Calinou** 2020-12-22 22:50 UTC

**Comment by pigigi** [comment] 2020-12-23 19:01
Oh jeez, thanks. Apologies.

Kind of a pain to search two repos but I'll try to remember.
