### ISSUE TITLE
Bezier tracks giving wrong values.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#20116] opened 2018-07-12 17:13 UTC
Trying out the AnimationPlayer Bezier track in a 3.0 Windows build from 2 days ago.

It seems that when I create more than one keyframe the values that come out are actually very spiky, though the curve in the editor says otherwise.  Might it be that the left handles are to blame?

Here is a screenshot where I'm using the range of 0 to 1.  While scrubbing through to these regions, it will modify the given track values with a bad value.  Also when I do canvas drawing to debug it, using `bezier_track_interpolate()` will also return these large spiked values.

![godot_2018-07-12_20-11-22](https://user-images.githubusercontent.com/13004169/42648502-d4f71b5c-860f-11e8-9218-3ac908cd0a5d.png)

In the screenshot looking at the alpha and dot it shows that at time .32 the result in the curve is 1.035, but given what is set in the curve editor it should be around .75.

On a side note, the snapping and such is wonky in the curve editor.

**Comment by dodgyville** [comment] 2018-07-13 05:04
Looks like #19777

**Comment by bojidar-bg** [comment] 2018-07-13 05:32
Closing as duplicate of #19777, but feel free to repost the screenshot there.

**Closed by bojidar-bg** 2018-07-13 05:32 UTC
