### ISSUE TITLE
Texture resources appear to have an optional resource_name that cannot be set anywhere

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [godotengine/godot#43809] opened 2020-11-24 06:39 UTC
**Godot version:**

3.2.4 beta2

**OS/device including version:**

Windows 10 
GTX 1650 Super
GLES2

**Issue description:**

This panel seems to suggest there is an internal name for Texture resources but it doesn't work and there is no way of setting that value.  Textures and Stream Textures are all in fact Resources and actually have an internal resource_name but values are never set and cannot be set via importing and will always report as empty string. 

![image](https://user-images.githubusercontent.com/36826319/100056148-25d5bf00-2df3-11eb-934e-a5617dba54aa.png)
 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2020-11-24 07:04
Duplicate of #13358.

**Closed by akien-mga** 2020-11-24 07:04 UTC
