### ISSUE TITLE
Built-in documentation displays strings as a vertical line instead of normal horizontal line

### ISSUE THREAD

**Issue by larinius** [godotengine/godot#75087] opened 2023-03-18 22:53 UTC
### Godot version

4.0.1.rc2

### System information

Windows 10

### Issue description

If open documentation with Alt+F1 some titles or code examples are displayed incorrectly as vertical lines.

![image](https://user-images.githubusercontent.com/5310985/226144032-7ab55c4c-a1ee-4a5a-a3ad-8f2b41cbf041.png)

### Steps to reproduce

`var strings : Array[String]`
Put the caret at Array, press Alt+F1

### Minimal reproduction project

`var strings : Array[String]`

**Comment by MisoMosiSpy** [comment] 2023-03-21 12:45
Didn't observe this issue with current build v4.1.dev.custom_build [a44fde12f]

![Screenshot 2023-03-21 134246](https://user-images.githubusercontent.com/52410428/226609515-a4bcc40d-2ce3-4040-8e59-9e30d04b7d87.png)

**Comment by JohnMeadow1** [comment] 2023-04-11 10:45
Can confirm. Happened to me 4 times in few days.
4.0.2.stable
Can't reproduce it reliably.

**Comment by akien-mga** [comment] 2023-06-20 05:52
This sounds like a duplicate of #77558, which should be fixed in 4.1 beta 3.

**Comment by YuriSizov** [comment] 2023-06-26 12:41
Yes, indeed. Please comment if it's still a problem in 4.1 after beta 3, and we can reopen this.

**Closed by YuriSizov** 2023-06-26 12:41 UTC
Labels: bug, topic:editor, confirmed
