### ISSUE TITLE
Ctrl-D doesn't respect the Scene tree view focus if the Script editor is open. The highlighted line is duplicated instead of the selected node

### ISSUE THREAD

**Issue by albertnez** [godotengine/godot#64404] opened 2022-08-14 20:54 UTC
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

If the Script editor is open, Pressing <kbd>Ctrl</kbd>-<kbd>D</kbd> will duplicate the Highlighted line, even if the Script editor is not focused. The most common behavior is that at some point I click on a Node in the Scene tree view to duplicate it, but the shortcut duplicates the line in the (now out of focus) Script editor, instead of the node in the now focused Scene tree view.

I don't know if this was present in Godot 3.4, but it's more visibler in 3.5 since now the Script tab is "sticky", and remains open after clicking on some node, instead of switching to the 2D or 3D view.

Note that when the Node is selected, other shortcuts like Deleting with <kbd>Del</kdb> work on the Node correctly, respecting the focused view.

### Steps to reproduce

1. Create a Godot scene with 1 Node, and 1 Script attached
2. Open the Script View
3. Click on the Node in the Scene View
4. Press <kbd>Ctrl</kbd>-<kbd>D</kbd>.
5. The highlighted line gets duplicated, instead of the Node (the node can't be duplicated as it's a root, but you'd get a message anyway).

### Minimal reproduction project

Setup is too small / simple to warrant uploading a project. But if it does help, I can provide.

**Comment by Calinou** [comment] 2022-08-14 21:37
Duplicate of https://github.com/godotengine/godot/issues/52861.

**Closed by Calinou** 2022-08-14 21:37 UTC
