### ISSUE TITLE
Replace in Files content changes not show in script editor

### ISSUE THREAD

**Issue by joemicmc** [godotengine/godot#61439] opened 2022-05-26 15:43 UTC
### Godot version

4.0 alpha 8

### System information

Windows 10

### Issue description

When using Replace in Files (shortcut ctrl+shift+r) the file contents are changed, but the script editor doesn't show changes.

### Steps to reproduce

- Open the sample project
- Open find_and_replace.tscn
- Run project
- ABC is printed to output
- Open find_and_replace.gd
- Selected text ABC and press ctrl+shift+r to open Replace in Files window
- Enter replacement text XYZ
- Click Replace...
- Click Replace all (no undo)

Expected outcome:
- Script editor shows content changes

Actual outcome:
- Script editor resizes slightly (bit weird) and the content changes are not displayed
- If you run the project again you will see XYZ printed to output so the replacement has happened

### Minimal reproduction project

[find_and_replace.zip](https://github.com/godotengine/godot/files/8780201/find_and_replace.zip)

**Comment by Calinou** [comment] 2022-05-26 18:07
Duplicate of https://github.com/godotengine/godot/issues/57870.

**Closed by Calinou** 2022-05-26 18:07 UTC
Labels: bug, topic:editor
