### ISSUE TITLE
Godot4 c# methods call,call_deferred,call_group fail

### ISSUE THREAD

**Issue by crasy1** [godotengine/godot#67623] opened 2022-10-19 10:18 UTC
### Godot version

4.0 beta

### System information

win10 ,mac

### Issue description

if c# script has a method with default params,will call method fail when call,call_deferred,call_group this method without param,but it is work on gdscript.

### Steps to reproduce

1.download demo.zip
2.run node_2d_gd.tscn
3.click  buttons
4.watch print

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/9819499/demo.zip)

**Comment by raulsntos** [comment] 2022-10-19 11:09
Duplicate of https://github.com/godotengine/godot/issues/59025

**Closed by raulsntos** 2022-10-19 11:09 UTC
Labels: bug, topic:dotnet
