### ISSUE TITLE
Cannot override set_cell in TileMap tool

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#65685] opened 2022-09-12 05:48 UTC
### Godot version

4.0.alpha16

### System information

MacOS Monterey

### Issue description

When attempting to override the behaviour of the set_cell method in an inherited script, the overriding method is not called.

### Steps to reproduce

1. Create tool script that extends tilemap and attach to tilemap node
2. override set_cell method in script
3. reload scene to enable tool script
4. set a cell within the tilemap to try trigger set_cell method
5. observe super class set_cell method being called instead of subclass

### Minimal reproduction project

[tilemap_tool.zip](https://github.com/godotengine/godot/files/9544915/tilemap_tool.zip)

**Comment by KoBeWi** [comment] 2022-09-12 09:15
Duplicate of #55024

**Closed by KoBeWi** 2022-09-12 09:15 UTC
