### ISSUE TITLE
Vulkan: Adding Normal Map to material turn mesh into black

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49186] opened 2021-05-29 14:45 UTC
**Godot version:**

v4.0.dev.custom_build.364ea7f28
#364ea7f28

**OS/device including version:**

windows 10 x64
AMD R7 200 series

**Issue description:**

When adding normal material to mesh it turns black, not to metion that when opening the spatialmaterial the fps goes down: as mentioned in #49170
```
Set: 3 Binding: 0 Type: UniformBuffer Length: 128
Set: 3 Binding: 1 Type: Texture Length: 1
Set: 3 Binding: 2 Type: Texture Length: 1
Set: 3 Binding: 3 Type: Texture Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 1 Type: Sampler Length: 12
Set: 0 Binding: 2 Type: Sampler Length: 1
Set: 0 Binding: 3 Type: StorageBuffer Length: 0
Set: 0 Binding: 4 Type: StorageBuffer Length: 0
Set: 0 Binding: 5 Type: StorageBuffer Length: 0
Set: 0 Binding: 6 Type: UniformBuffer Length: 4224
Set: 0 Binding: 7 Type: StorageBuffer Length: 0
Set: 0 Binding: 8 Type: StorageBuffer Length: 0
Set: 0 Binding: 9 Type: Texture Length: 1
Set: 0 Binding: 10 Type: Texture Length: 1
Set: 0 Binding: 11 Type: StorageBuffer Length: 0
Set: 0 Binding: 12 Type: StorageBuffer Length: 0
Set: 0 Binding: 13 Type: UniformBuffer Length: 368
Set: 1 Binding: 0 Type: UniformBuffer Length: 2672
Set: 1 Binding: 1 Type: StorageBuffer Length: 0
Set: 1 Binding: 2 Type: Texture Length: 1
Set: 1 Binding: 3 Type: Texture Length: 1
Set: 1 Binding: 4 Type: Texture Length: 1
Set: 1 Binding: 5 Type: Texture Length: 1
Set: 1 Binding: 6 Type: Texture Length: 8
Set: 1 Binding: 7 Type: Texture Length: 8
Set: 1 Binding: 8 Type: StorageBuffer Length: 0
Set: 1 Binding: 9 Type: Texture Length: 1
Set: 1 Binding: 10 Type: Texture Length: 1
Set: 1 Binding: 11 Type: Texture Length: 1
Set: 1 Binding: 12 Type: Texture Length: 1
Set: 1 Binding: 13 Type: Texture Length: 1
Set: 1 Binding: 14 Type: Texture Length: 1
Set: 1 Binding: 15 Type: Texture Length: 1
Set: 1 Binding: 16 Type: Texture Length: 1
```

**Steps to reproduce:**
* Get the PBR textures below
* Create a MeshInstance
* Attach all textures to proper places

**Minimal reproduction project:**

[rock-slab-wall1-bl.zip](https://github.com/godotengine/godot/files/6564832/rock-slab-wall1-bl.zip)

**Comment by Calinou** [comment] 2021-05-29 15:11
Duplicate of https://github.com/godotengine/godot/issues/48886 (same cause).

**Closed by Calinou** 2021-05-29 15:11 UTC
