### ISSUE TITLE
Possible memory leak when light is moving (Vulkan)

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#33522] opened 2019-11-10 15:46 UTC
**Godot version:**
Godot Engine v4.0.devel.custom_build.d6abb52db (updated on 08-11-2019)

**OS/device including version:**
Windows 10 64bits

**Issue description:**
When light is moved (by Animation or by script in the _process functions), the static memory (Performance.MEMORY_STATIC) increases continuously.

Comparative video between Godot 3.1.1.1 and Godot Vulkan :
https://marion-maxime.com/Divers/GodotVulkanIssues/VideoRAM.mp4

**Steps to reproduce:**
1. Add a light (tested with DirectionnalLight and PointLight)
2. Animate this light (tested with an Animation and the _process functions)

**Minimal reproduction project:**

**Comment by qarmin** [comment] 2019-11-10 19:05
For now version 4.0, even after opening project, have some big leaks, so I don't know if this leaks are related to yours.
You can check what leaks(not always all things are listed) by running Godot from console with verbose flag `godot -v`

**Comment by KoBeWi** [comment] 2020-10-07 23:43
Is this still reproducible in 8a4f402?

**Comment by NykolaR** [comment] 2020-10-16 18:03
I get these leaks with moving omni and spot 3D lights, and also get continuous leaking when using a directional light with shadows enabled.

Possibly related, I also get static memory leaks with non animated omni and spot 3D lights when my "player" moves, which has it's camera child to it. It does not produce leaks when rotating the camera, only when its parent moves. This leaking becomes more intense the more lights with shadows I have active (with the most lights I tried, 24, leaking around 0.5mb/s when moving the character)

This is on Linux 5.8.11-1-manjaro, GPU Radeon RX 570, on Godot builds:
v4.0.dev.custom_build.94e5f66cb and
v4.0.dev.calinou.88a3db5bf

**Comment by TechnoPorg** [comment] 2022-02-28 01:41
I can no longer reproduce this issue, using the following test script:
```
@tool
extends DirectionalLight3D

var previous_memory = 0

func _process(delta):
	var static_mem = Performance.MEMORY_STATIC
	if(static_mem != previous_memory):
		print(static_mem)
		previous_memory = static_mem
	rotate_x(10 * delta)
```
It prints once, and then nothing prints again, while I can see the light rotating in the editor.

**Comment by Calinou** [comment] 2022-02-28 01:49
@TechnoPorg Could you also do tests with OmniLight3D and SpotLight3D? Remember to enable shadows for all lights, and have dynamic objects that move near the OmniLight3D and SpotLight3D.

**Comment by TechnoPorg** [comment] 2022-03-01 01:01
I'm also unable to reproduce this with OmniLight3D and SpotLight3D, with a plane mesh and a spinning cube next to the light, which is casting a shadow.

**Comment by Calinou** [comment] 2022-03-01 14:58
Closing per @TechnoPorg's comment.

Note that if you get error spam due to lights with shadows
, this is already covered by another issue: https://github.com/godotengine/godot/issues/56599

**Closed by Calinou** 2022-03-01 14:58 UTC
Labels: bug, topic:rendering, confirmed
