### ISSUE TITLE
Can't use Undo anymore

### ISSUE THREAD

**Issue by rayojarr** [godotengine/godot#20920] opened 2018-08-11 15:26 UTC
**Godot version:**
3.0.6

**OS/device including version:**
              Windows 10

**Issue description:**
when i use tilemaps for my platforming game but i when undo ( Ctrl + Z ) a few times,
i get this error
core/undo_redo.cpp:337 - Condition ' action_level > 0 ' is true. returned: ""
 core/undo_redo.cpp:316 - Condition ' action_level > 0 ' is true.
and then i can't undo anymore
is there any solution for my problem?
will their be a fix for this in a future update?

Open a new scene and place a few tiles then Undo the tile placements ( Alt + Z ) Until it gives the error above
https://github.com/godotengine/godot/issues

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-08-15 19:54
We'll need detailed steps to reproduce the issue to be able to help you.

**Comment by rayojarr** [comment] 2018-08-18 13:52
Sorry for the delay. I recorded the steps to recreate this error
https://youtu.be/BZh4iGWk568

**Comment by rayojarr** [comment] 2018-08-18 13:52
sorry i misclicked with the close issue

**Comment by KoBeWi** [comment] 2019-10-16 15:11
@rayojarr The video died. Also I spam undo like mad, but no error appears. If you don't write the exact steps, I'll just close this issue. (also make sure to test it with 3.2 alpha)

**Comment by KoBeWi** [comment] 2020-10-24 20:26
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-10-24 20:26 UTC
Labels: bug, topic:core
