### ISSUE TITLE
The VideoPlayer cannot open the file ogv (Godot 3.0))

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#11829] opened 2017-10-04 12:03 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04

The **VideoPlayer** cannot open the file ***.ogv**

![videoplayer](https://user-images.githubusercontent.com/11325733/31174661-eeaa941a-a93e-11e7-9cac-cf408c1dbc89.png)

**Comment by terahxluna** [comment] 2017-10-04 12:53
Duplicate of #10031 ?

**Comment by bojidar-bg** [comment] 2017-10-04 14:42
Indeed, seems like a duplicate of #10031.

**Closed by bojidar-bg** 2017-10-04 14:42 UTC
Labels: bug, topic:editor
