### ISSUE TITLE
Visual Issues when Adding a CSGBox

### ISSUE THREAD

**Issue by turtletooth** [godotengine/godot#26422] opened 2019-02-28 21:51 UTC
Godot 3.1 Beta 9

Windows 10

3D Scene
Add a Spatial
Add a CSG Box
The grid disappears.

**Comment by turtletooth** [comment] 2019-02-28 22:02
The scale also doesn't update in the Inspector when the red dots are changed.

**Comment by bojidar-bg** [comment] 2019-03-04 18:55
Cannot reproduce on master/beta 10. Looks like this on my end:
![image](https://user-images.githubusercontent.com/5276727/53755153-7ccc8f80-3ebe-11e9-91b7-708d3bc2b017.png)

Perhaps you zoomed in just the right amount as to see only the box, and it looked like the grid disappearing?

**Comment by turtletooth** [comment] 2019-03-04 20:27
just tested on beta 10.  Same results.

![godot](https://user-images.githubusercontent.com/4576381/53760838-402e7300-3e81-11e9-822d-d10377b6b6cf.PNG)

**Comment by Calinou** [comment] 2019-03-04 20:43
What graphics card (and driver version) are you using?

**Comment by turtletooth** [comment] 2019-03-06 17:32
Surface Pro 2018 i7 16gb ram, Intel Iris Plus 640

**Comment by turtletooth** [comment] 2019-03-08 22:20
Strangely, adding a light fixes this.

**Comment by clayjohn** [comment] 2020-01-10 07:08
Looks to be a driver specific issue that was never reproduced by others. Closing for now. 

If you are still encountering this problem in recent versions, I can re-open.

**Closed by clayjohn** 2020-01-10 07:08 UTC
Labels: bug, topic:editor, topic:rendering
