### ISSUE TITLE
Graphical glitch when editing/playing 3D game on Pixel 7 when Glow is On

### ISSUE THREAD

**Issue by etherealxx** [godotengine/godot#87044] opened 2024-01-10 16:14 UTC
### Tested versions

Reproducible in 4.2.1.stable

### System information

Godot v4.2.1.stable - Android - Vulkan (Mobile) - integrated Mali-G710 -  (8 Threads)

### Issue description

Running the same apk with Issue https://github.com/godotengine/godot/issues/86707 's MRP will results to this glitch in Pixel 7. Only UI is clearly visible and the 3D section looks like a zoomed camera. Same glitch will occurs when running the MRP's main scene on the android editor. The problem exist on all three rendering methods. (wait for the gif to shows up)
![screen-20240108-1737552-lscutted_00 00 00 000-ezgif com-resize](https://github.com/godotengine/godot/assets/64251396/895790e7-6d8d-4e25-a7f7-a03b7e71dae4)
However, Turning Glow to Off in the `prototype` scene, `WorldEnvironment` node, at inspector, `Glow` unchecked, it fixes the problem.
![Screenshot_20240109-212006xx](https://github.com/godotengine/godot/assets/64251396/d5807a0b-9894-4fb6-8ebe-cfff7e741096)

Currently it's unknown what is causing the problem, since the same device can also run other game smoothly with no problem. The problem is also pretty specific, since other physical android devices could run the MRP just fine. Maybe it has something to do with Pixel 7's chipset (Google Tensor G2).

### Steps to reproduce

- download and extract the MRP, or clone from this for the full untrimmed project: https://github.com/etherealxx/Godot-Third-Person-Controller-Mobile
- open the project in godot
- Install Android Build Template
- Set up your android SDK path and debug keystore path correctly on editor settings
- Export the project into android (apk) with the provided template (using gradle build, minimum sdk 24, target sdk 33, arm64-v8a) (actually not using gradle build would also results the same)
- Install the exported apk into the affected device (Google Pixel 7)
- Launch the app

### Minimal reproduction project (MRP)

[godot4-3d-snapdragon-bug.zip](https://github.com/godotengine/godot/files/13890085/godot4-3d-snapdragon-bug.zip)

**Comment by AThousandShips** [comment] 2024-01-10 16:46
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/86621

**Comment by etherealxx** [comment] 2024-01-10 16:58
@AThousandShips should i close this then? this one has MRP though

**Comment by AThousandShips** [comment] 2024-01-10 17:00
This should be closed, as the other one has more discussion and is older, please comment with your MRP on the other one instead

Duplicate of https://github.com/godotengine/godot/issues/86621

**Closed by AThousandShips** 2024-01-10 17:00 UTC
