### ISSUE TITLE
Unwanted editor issue when losing and gaining focus (alt-tab)

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#10949] opened 2017-09-03 23:11 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 3.0 29db531fc8360b1e6d5e23008b208517b6d8c627

**Issue description:**

While editing a tilemap, tabbing out godot and clicking to gain focus 2 tiles will be drawn

![https://i.imgur.com/g9YeP1G.gif](https://i.imgur.com/g9YeP1G.gif)

**Comment by mrcdk** [comment] 2017-09-06 01:20
Changed the title of the issue because it affects the whole editor. I've tracked it down to this PR https://github.com/godotengine/godot/pull/7162

**Comment by akien-mga** [comment] 2017-09-06 09:39
CC @iboshkov.

**Comment by akien-mga** [comment] 2018-01-08 12:05
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by iboshkov** [comment] 2018-01-08 22:34
Hi, so seems like I missed this issue somehow, and only just now noticed the notification in my inbox, I don't have a Windows machine right now available to me, but I'm going to try to reproduce this hopefully this week, looking through the pull request I didn't spot what could be causing this issue. Has anyone tried it on a non-Windows platform ?

**Comment by reduz** [comment] 2018-09-05 20:54
Can anyone check this one?

**Comment by NilsIrl** [comment] 2019-07-14 11:39
> Hi, so seems like I missed this issue somehow, and only just now noticed the notification in my inbox, I don't have a Windows machine right now available to me, but I'm going to try to reproduce this hopefully this week, looking through the pull request I didn't spot what could be causing this issue. Has anyone tried it on a non-Windows platform ?

I have the bug on linux (X11 and `i3-wm` w/ `focus_follows_mouse` set to `no`)

**Comment by NilsIrl** [comment] 2019-07-14 11:43
@mrcdk you mention `alt-Tab`? has it got anything to do with it? Or is it just gaining focus by clicking?

**Comment by NilsIrl** [comment] 2019-07-14 12:50
Is this really an issue?

It seems like every app I can think about has the same behaviour as Godot.

**Comment by akien-mga** [comment] 2019-11-26 12:43
I can't reproduce it on Linux. Is this still reproducible on Windows?

**Comment by KoBeWi** [comment] 2019-11-29 20:48
It's still reproducible and got even worse, see #34003

**Comment by KoBeWi** [comment] 2020-06-23 19:06
Closing in favor of #24970, which is more up-to-date.

**Closed by KoBeWi** 2020-06-23 19:06 UTC
Labels: bug, hero wanted!, topic:editor
