### ISSUE TITLE
Issue building from shortcut keys

### ISSUE THREAD

**Issue by iamjoeysox** [godotengine/godot#70893] opened 2023-01-03 19:40 UTC
### Godot version

4.0beta10

### System information

OSX 13.1

### Issue description

It seems that you cannot build the game from the normal command+b shortcut if your most recent focus was the text editor.

If you however first click into the node inceptor pane then run the same shortcut command it seems to work. Not a show stopper or anything, but it adds up throughout a work day and becomes extremely annoying haha. I don't remember this happening in 3.5, but I could be wrong.

### Steps to reproduce

1. Open any 4.0 project
2. Write something in the text editor but keep your focus inside the text editor when finished
3. Try to build the game with the keyboard shortcut (command+b)

### Minimal reproduction project

This isn't needed.

**Comment by Paulb23** [comment] 2023-01-04 21:31
Duplicate of #56961

**Closed by Paulb23** 2023-01-04 21:31 UTC
