### ISSUE TITLE
Enabling GLES2 forces clear background of controls in Editor

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#32675] opened 2019-10-09 09:39 UTC
**Godot version:** 
Godot 3.2 alpha 1

**OS/device including version:**
macOS Mojave v10.14.8

**Issue description:**
I opened a GLES2 mobile project that I'm working on in the new alpha build. The background color on the majority of controls in the editor itself are alpha = 0, regardless of which monitor I open the editor on. When I switch to GLES3, everything goes back to normal, so my assumption is that when you switch to GLES2 renderer, the renderer has an error on Macs, but I do not know specifically what yet.

**Steps to reproduce:**
1) Create a GLES2 project
2) Open it on a Mac

**Minimal reproduction project:**
[BorkedGLES2Repro.zip](https://github.com/godotengine/godot/files/3706612/BorkedGLES2Repro.zip)

<img width="189" alt="Screen Shot 2019-10-09 at 5 34 13 AM" src="https://user-images.githubusercontent.com/148612/66470049-e9ac9700-ea56-11e9-8dde-f3c1df3b6db3.png">
![Screen Shot 2019-10-09 at 5 35 12 AM](https://user-images.githubusercontent.com/148612/66470051-e9ac9700-ea56-11e9-8bc5-e533a36d4bd8.png)
![Screen Shot 2019-10-09 at 5 35 30 AM](https://user-images.githubusercontent.com/148612/66470052-e9ac9700-ea56-11e9-953b-91fa222a4d6d.png)
![Screen Shot 2019-10-09 at 5 35 50 AM](https://user-images.githubusercontent.com/148612/66470053-e9ac9700-ea56-11e9-8a51-9bfb57a60e32.png)

**Comment by WolfgangSenff** [comment] 2019-10-09 09:51
Odd that it didn't include my other screenshots. Suffice it to say, they look pretty bad too.

**Comment by akien-mga** [comment] 2019-10-09 09:56
Duplicate of #32601 (fixed in master branch).

**Closed by akien-mga** 2019-10-09 09:56 UTC

**Comment by WolfgangSenff** [comment] 2019-10-09 10:05
Thanks! I'll get the nightly build then. :)
