### ISSUE TITLE
Collision of CharacterBody3D does not respect position set after instantiating (first tick only?)

### ISSUE THREAD

**Issue by vermeeren** [godotengine/godot#58445] opened 2022-02-22 19:39 UTC
### Godot version

4.0 master e17c29ab80e9bf4ac6ccf60e023252b3113cbf39

### System information

Debian bookworm (testing)

### Issue description

Following the first 3D game tutorial with Godot 4 I run into the issue when upon instantiating the mob there is unexpected collision occurring in the exact middle position of the playing field, which presumably is the 0,0,0 position.

https://user-images.githubusercontent.com/5957454/155204055-d5339176-436b-488c-b985-827343369658.mp4

The logic here is very simple. When the timer triggers in the Main scene to spawn a mob:

```gdscript
# main.gd
func _on_mob_timer_timeout():
	var mob = mob_scene.instantiate()
	$SpawnPath/SpawnLocation.unit_offset = randf()
	add_child(mob)
	mob.initialize($SpawnPath/SpawnLocation.position, $Player.position)

# mob.gd
func initialize(start_pos, player_pos):
	position = start_pos
	look_at(player_pos)
	rotate_y(randf_range(-PI / 4, PI / 4))

	var speed = randf_range(min_speed, max_speed)
	motion_velocity = Vector3.FORWARD * speed
	motion_velocity = motion_velocity.rotated(Vector3.UP, rotation.y)
```

---

I also tried enabling the Mob's CollisionShape3D Disabled parameter using the inspector and then adding to the bottom of `mob.gd`'s `initialize()`:

```gdscript
$CollisionShape3D.set_deferred("disabled", false)
```

Behaviour is the same, which is strange as the Mob position is absolutely set before enabling collisions.

Perhaps something changed in Godot 4 and I'm doing it wrong but it feels like there is a single-tick delay on updating the collision's position somehow, as graphically (including with debug show hitboxes) everything looks good and collision with mobs also works properly.

---

Changing Mob like this:

```gdscript
func initialize(start_pos, player_pos):
	...
	$CollisionShape3D.disabled = true

func _physics_process(_delta):
	$CollisionShape3D.set_deferred("disabled", false)
	move_and_slide()
```

Resolves the issue, which makes me believe it is indeed a "tick 0" issue where somehow the collision's position is not updated properly.

### Steps to reproduce

Open up attached project and play.

### Minimal reproduction project

[squash_the_creeps.zip](https://github.com/godotengine/godot/files/8119651/squash_the_creeps.zip)

**Comment by rburing** [comment] 2022-03-13 09:27
This is a duplicate of https://github.com/godotengine/godot/issues/58132. In my view the tutorial code is flawed; it is a documentation issue of the type described in https://github.com/godotengine/godot/issues/45638.

**Closed** 2022-03-13 15:09 UTC
Labels: bug, topic:physics, topic:3d
