### ISSUE TITLE
Select tool translates node when dragging w/o the gizmo over geometry

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#87949] opened 2024-02-04 15:48 UTC
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]
v4.3.dev.custom_build [b4e2a24c1]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

When attempting to region-select over geometry while a node is selected, and the select tool is enabled, the selected node ends up being translated, which seems wrong.

https://github.com/godotengine/godot/assets/105675984/6d39ec75-21bc-40e9-8e93-8a13e56d3496

### Steps to reproduce

See video.

Select node using select tool.

Attempt to region select over some kind other geometry like another mesh. 

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment] 2024-02-04 15:54
I can't reproduce it. Select Mode will always select.

**Comment by ryevdokimov** [comment] 2024-02-04 15:58
I also just tested on master and can reproduce on that build as well. To be clear, you are holding down the mouse starting on-top of some geometry like a mesh, and then dragging as if you're doing a region select?

**Comment by AThousandShips** [comment] 2024-02-04 16:00
This is specific to region select, which isn't specified in the issue report

Note that this was done by design as far as I can tell

**Comment by ryevdokimov** [comment] 2024-02-04 16:03
Fair point. I updated the reproduction instructions. I did a git blame to trace some of the PRs involved with this back and I couldn't find any explanation that this was by design.

**Comment by AThousandShips** [comment] 2024-02-04 16:04
I mean the comment saying it implies design, and it was approved as such, see:
* https://github.com/godotengine/godot/pull/57847

**Comment by KoBeWi** [comment] 2024-02-04 16:05
The PR linked shows a different issue.

**Comment by ryevdokimov** [comment] 2024-02-04 16:05
> I mean the comment saying it implies design, and it was approved as such, see:
> 
> * [Improved region-select in the 3D editor viewport #57847](https://github.com/godotengine/godot/pull/57847)

Yes, I saw that PR, but I don't see an explanation that translating the node in place of region select is the intended design.

**Comment by AThousandShips** [comment] 2024-02-04 16:06
Yes but it's the origin of this, at least we need to ensure the issues in that PR doesn't resurface

But I fail to see how "select only if nothing is selected" isn't clear intention

**Comment by ryevdokimov** [comment] 2024-02-04 16:12
Fair point again, but it also isn't true and isn't described in the PR itself only in the comment of the code itself which can be overlooked. In both 4.2 and master, you can region select while nodes are selected, but only outside geometry. This isn't explained anywhere, and also doesn't really make any sense IMO.

**Comment by AThousandShips** [comment] 2024-02-04 16:15
Well that's a pretty important difference, would have made quite a difference in my interpretation of the issue if it had been specified

**Comment by AThousandShips** [comment] 2024-02-04 16:16
Oh thank you for specifying that part 🙂 it got lost in the very long title 😄

**Comment by ryevdokimov** [comment] 2024-02-04 16:17
Triple fair point, I'll do better in my explanations from the get-go. Sometimes I just get caught up in writing code.

**Comment by AThousandShips** [comment] 2024-02-04 16:19
Oh it's natural, I should have read more carefully, but good to add in the description of the PR, especially with very long titles it's easier to get the info from the text

**Comment by ryevdokimov** [comment] 2024-02-04 18:21
Titles too long, descriptions too short got it. 😂

**Comment by Cammymoop** [comment] 2024-02-05 02:36
This is a duplicate of #85736

**Closed** 2024-02-05 13:59 UTC
Labels: bug, topic:editor, topic:3d
