### ISSUE TITLE
Feature request : Ability to select instanced scenes from the viewport.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#7404] opened 2016-12-31 21:17 UTC
**Operating system or device - Godot version:**
Any version.
 Any OS

**Issue description** (what happened, and what was expected):
doesn't seem like you can select an instance scene from inside the 3d viewport when the instanced scene is apart of another scene.

**Steps to reproduce:**
create an instance 3D scene. add that scene to another 3D scene. try to select the instance.

**Link to minimal example project** (optional but very welcome):
I know instance feature is broken at the moment. don't know if the devs know about this so just putting it out there.

**Comment by akien-mga** [comment] 2017-01-02 13:52
Duplicate of #2852 and/or #4099.

**Closed by akien-mga** 2017-01-02 13:52 UTC
