### ISSUE TITLE
Ability to create mesh from default shapes

### ISSUE THREAD

**Issue by Qwertie-** [godotengine/godot#762] opened 2014-10-08 03:42 UTC
There should be a way to create a mesh from a set of default shapes similar to the way you can with colliders.

![screenshot from 2014-10-08 14 11 40](https://cloud.githubusercontent.com/assets/6601505/4553605/09aacd7a-4e9d-11e4-9680-663a012bcb8c.png)

**Comment by akien-mga** [comment] 2015-10-31 10:01
Closing as a duplicate of #861.

**Closed by akien-mga** 2015-10-31 10:01 UTC
Labels: archived
