### ISSUE TITLE
Specific Model's Convex Collision Body Generation Causes Unresponsiveness

### ISSUE THREAD

**Issue by AaronCRobinson** [godotengine/godot#24800] opened 2019-01-06 00:30 UTC
**Godot version:**
Godot-v3.0.6-stable

**OS/device including version:**
Windows 10 - insider branch

**Issue description:**
Godot spin loops (non-responsive crash) when doing convex body for specific model. Other models work fine. This may be part of #8811 ?

**Steps to reproduce:**
Using Mesh options, attempt to make a Convex or Trimesh body for the mesh in question. 

**Minimal reproduction project:**

[A.zip](https://github.com/godotengine/godot/files/2730023/A.zip)

**Comment by Chaosus** [comment] 2019-01-06 08:42
Duplicate of #21141

**Closed by Chaosus** 2019-01-06 08:42 UTC
