### ISSUE TITLE
Can we get generic support for GetNode with csharp?

### ISSUE THREAD

**Issue by exts** [godotengine/godot#17091] opened 2018-02-27 21:43 UTC
**Godot version:**
3.x

I think it would be nice to have support for generics for certain global functions like `GetNode` for instance changing:

```csharp
var button = GetNode("MyButtonNode") as MyButton;
```

to:

```csharp
var button = GetNode<MyButton>("MyButtonNode"); // would infer MyButton or null if not found.
```

I searched and couldn't find anything regarding this yet.

**Comment by akien-mga** [comment] 2018-02-27 22:12
Duplicate of #16871.

**Closed by akien-mga** 2018-02-27 22:12 UTC

**Comment by exts** [comment] 2018-02-27 22:29
Damn, github search failed me today. Sorry about that.

**Comment by akien-mga** [comment] 2018-02-27 22:40
No worry :)
