### ISSUE TITLE
Control consumes CollisionObject events for Area2D despite mouse_filter set to "pass"

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#54529] opened 2021-11-03 00:49 UTC
### Godot version

3.3.4 stable, 3.4rc3, Godot v4.0.dev.20211015.official [f113dc986]

### System information

Win 64, Nvidea 765M

### Issue description

This one has cost me a lot of frustration and debugging time. Tested and confirmed in all current versions: 3.3.4, 3.4, 4.0.

If there is a Control overlapping an Area2D, the Control will consume the input event and mouse_entered and mouse_exited signal, despite mouse_event being set to "pass".

**This makes it impossible to use Area2D nodes and Control nodes in the same project when both overlap and need the mouse events**

https://user-images.githubusercontent.com/47016402/139970970-37d8ca75-53e1-4302-9a17-7787a740ded8.mp4

And  mouse_entered and mouse_exited signals of the Area2D won't fire either when the Area2D is overlapping with the Control:

https://user-images.githubusercontent.com/47016402/139999079-ddfc4d05-cc7e-422e-ac79-401143ad4eb5.mp4

### Steps to reproduce

1. Add a Control node, set it's mouse_filter to "pass" and connect the gui_input(event) signal to a script
2. Add a Area2D node and a CollisonShape2D, and connect the input_event(event) signal to a script
3. Make sure the Area2D is overlapping the Control node
4. Observe the Area input_event(event) signal not firing any more

### Minimal reproduction project

Godot 3.X minimal project: 
[area_over_control_bug_godot3.zip](https://github.com/godotengine/godot/files/7464746/area_over_control_bug_godot3.zip)

Godot 4.0 minimal project:
[area_over_control_bug_godot4.zip](https://github.com/godotengine/godot/files/7464745/area_over_control_bug_godot4.zip)

**Comment by BimDav** [comment] 2021-11-03 16:24
I think that the first case respects the documentation of MOUSE_FILTER_PASS: "Even if no control handled it at all, the event will still be handled automatically, so unhandled input will not be fired." Since the event is handled, it will not collide with Areas.

The second case (mouse_entered and mouse_exited signals) is probably due to the same reason, but documentation should explain that events must not be handled for these signals to be emitted.

That being said, maybe the event should not be handled automatically in the Control, since your usercase seems common.

**Comment by golddotasksquestions** [comment] 2021-11-03 20:00
Yes, but it should not be handled! That's the whole point of this issue.

**Comment by BimDav** [comment] 2021-11-03 21:33
I agree with you. I was signaling that this behavior seems at least a little bit intended, and is not purely a bug. It is even almost properly described in the documentation. There probably is a reason why events are marked as handled in this case, and we have to figure it out before changing anything.

**Comment by BimDav** [comment] 2021-11-06 09:40
I did not see any good reason for the previous behavior. Inputs were simply automatically handled as long as the control's filter was not MOUSE_FILTER_IGNORE.

**Comment by golddotasksquestions** [comment] 2022-03-05 14:09
I just ran into this issue again yesterday and now will have to find yet another workaround. :((

I have reduced this issue to this most basic reproduction:
![area_control_pass](https://user-images.githubusercontent.com/47016402/156886833-8201a171-d410-4431-ad57-ce098d503652.png)

**Comment by kitbdev** [comment] 2023-11-13 18:41
This is intentional behavior.

Controls are for gui, and Node2Ds are for gameplay. They are separate by design.
[Area2D](https://docs.godotengine.org/en/latest/classes/class_area2d.html#class-area2d) is specifically for the 2D physics system. It only receives mouse enter/exit signals as part of physics picking if it is not used for the gui.
As the [InputEvent documentation](https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html#how-does-it-work) says, physics picking happens after gui input.
Also, Area2Ds do not have mouse filters like Controls do.


You should probably either use only Node2Ds (change ColorRect to be a Sprite) or use only Controls (change Area2D to be a Control).
For Controls, if you need mouse events to work with a non-rectangular shape you will need to check the mouse position manually.
For Node2Ds, [_mouse_shape_enter](https://docs.godotengine.org/en/latest/classes/class_collisionobject2d.html#class-collisionobject2d-private-method-input-event) may be useful.

**Comment by kitbdev** [comment] 2024-01-29 22:26
Actually, I cannot reproduce this in Godot 4.0 or any 4.x version, I believe it was actually fixed in #61088. 
With mouse filter Pass, both the TextureRect and the Area2D receive mouse events.
With mouse filter Ignore, only the Area2D receives mouse events.
With mouse filter Stop, only the TextureRect receives mouse events.

**Comment by Sauermann** [comment] 2024-01-29 22:33
It looks like this issue didn't get closed after it was resolved.
Fixed by #61088.

**Closed by Sauermann** 2024-01-29 22:33 UTC
Labels: bug, topic:physics, topic:input, topic:gui
