### ISSUE TITLE
Can't Open Godot 4 Project with Visual Studio 2022

### ISSUE THREAD

**Issue by xer0-1ne** [godotengine/godot#80829] opened 2023-08-20 19:58 UTC
### Godot version

4.2.dev3.mono

### System information

macOS Ventura 13.5.1

### Issue description

When trying to open a project with Visual Studio 2022, an error is presented on the project:

`Load failed: Unknown solution item type: {8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED}`

### Steps to reproduce

Create a new project.  
Go to `Project` > `Tools` > `C#` > `Create C# Solution`
Create a C# script file.
Try to open the project with Visual Studio 2022.
-OR-
Click the script icon to open the file with your preferred editor that was configured in the Editor settings.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2023-10-21 10:52
- Duplicate of https://github.com/godotengine/godot/issues/67029.
- Fixed by https://github.com/godotengine/godot/pull/81802.

**Closed by raulsntos** 2023-10-21 10:52 UTC
Labels: bug, topic:buildsystem, needs testing, topic:dotnet
