### ISSUE TITLE
TextureArray reported as null in the debugger, when it isn't

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#38965] opened 2020-05-22 18:42 UTC
Godot 3.2.1

I have a `TextureArray` resource in my project (atlas image imported as TextureArray). I want to load it with `load` in GDScript, but no matter what I try, it always reports as `null` in the debugger. But if I print it, I get `[TextureArray:1171]`.

Test project:
[LoadTextureArray.zip](https://github.com/godotengine/godot/files/4669798/LoadTextureArray.zip)
Put a breakpoint at the `print` statement in `main.gd`, and start the scene.

**Comment by rileylyman** [comment] 2020-05-25 20:14
Deleting the `.import` folder within your project files fixed the problem for me.

**Comment by rileylyman** [comment] 2020-05-29 04:43
@Zylann Does deleting the folder yield any results?

**Comment by Zylann** [comment] 2020-05-29 09:12
@rileylyman that's one way of doing it, since Godot holds a lock on the file in `.import` basically. For some reason it does that and never releases it as soon as it loads the resource...

**Comment by baptr** [comment] 2023-03-01 08:00
I'm guessing this is a dupe with #36801 - variables greater than 1MiB in size are hidden by the debugger.

**Comment by Calinou** [comment] 2023-03-01 18:27
Duplicate of https://github.com/godotengine/godot/issues/36801.

**Closed by Calinou** 2023-03-01 18:27 UTC
Labels: bug, topic:core
