### ISSUE TITLE
FileSystem - Remove subfolder bug

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#27526] opened 2019-03-30 11:12 UTC
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7x64

**Steps to reproduce:**
1. Create folder,
2. In this folder create new subfolder,
3. Delete subfolder

Result: subfolder physically deleted, BUT it is still displayed in FileSystem with root files in it + errors in console. Bug disappears after redraw (alt+tab to another window and back to godot)

Console:
```
 core/io/image_loader.cpp:56 - Error opening file: res://111/2222/111/icon.png
 editor/editor_file_system.cpp:1618 - Error importing: res://111/2222/111/icon.png
 editor/editor_file_system.cpp:1624 - Condition ' !f ' is true.
 core/io/image_loader.cpp:56 - Error opening file: res://111/2222/icon.png
 editor/editor_file_system.cpp:1618 - Error importing: res://111/2222/icon.png
 editor/editor_file_system.cpp:1624 - Condition ' !f ' is true
```

![bug2](https://user-images.githubusercontent.com/1552169/55275337-d07f9c80-52f5-11e9-8ca2-309a4274c34e.gif)

**Comment by qarmin** [comment] 2019-03-31 06:34
I have different error on Ubuntu 18.04.2 when I just try create and delete folder.
```
mv: nie można przenieść '/home/rafal/Pobrane/test00/new folder/' do '/home/rafal/.local/share/Trash/files/new folder': Katalog nie jest pusty
ERROR: move_to_trash: move_to_trash: Could not move the resource "/home/rafal/Pobrane/test00/new folder/" to the trash can "/home/rafal/.local/share/Trash/files"
   At: platform/x11/os_x11.cpp:3173.
```
in english - mv: Could not move /home/rafal/Pobrane/test00/new folder/ to /home/rafal/.local/share/Trash/files/new folder': because directory isn't empty. 
Also with same error I can't delete folder created inside Godot, but I can delete  folder created outside it.
I think that can be a problem with creating a folder inside Godot.

**Comment by TheDuriel** [comment] 2019-04-03 00:07
Also on Windows 7, able to replicate it. This has been bugging me since 2.1 glad to see someone actually made it reproducible.

**Comment by breakmt** [comment] 2019-04-05 13:19
Not sure why it is not labeled as a bug still. I'm afraid that it will pass without attention

**Comment by ShyRed** [comment] 2019-04-14 11:49
Can't reproduce on Win10 64Bit

**Comment by breakmt** [comment] 2019-04-14 14:49
@ShyRed yes, on Win10 x64 folder disappears immediately, but there are still errors in console, so it still works not fully correctly

**Comment by CJNA** [comment] 2019-04-20 02:08
I could not reproduce it on Win10 x64 and Linux 16.04 x64.
No output log appears. 
Maybe it is platform dependent + something else? 
I took a look at the code itself as well. Seems to make a logical sense to me.

Based on the log, at least on your platform, godot created another copy of parent directory, and icon.png.

Hierachy seems to be flipped somehow.

**Comment by CJNA** [comment] 2019-04-22 01:57
Tried it with Ubuntu 18.04 LTS x64. Couldn't reproduce error as well.

**Comment by Anutrix** [comment] 2019-06-26 16:02
Couldn't reproduce on Windows 10. Seems to be a Windows 7 bug. The bug on Linux that qarmin has seems to be a different issue.

**Comment by qarmin** [comment] 2019-06-26 16:28
Now, after clean install Ubuntu 19.04, I can't reproduce this error

**Comment by KoBeWi** [comment] 2019-11-19 15:14
This issue still happens. You can try steps from #33378. And if they don't work, put some dependency into the higher directory. Then try recreating the sub-directory and deleting again. Eventually the bug should occur.

**Comment by FrederickDesimpel** [comment] 2019-12-30 13:03
I have this bug too, on Windows 10 x64

**Comment by KoBeWi** [comment] 2020-01-02 15:50
OMG 😠

I just encountered a case where deleting a directory in my project will ALWAYS trigger this bug 100% of the time, even after restarting. So happy that I found a reliable repro I copied the project to another location to make sure and guess what, it doesn't happen. This made me suspect that it depends on some cached project-specific files, making it really hard to reproduce.

**Comment by rcorre** [comment] 2020-02-09 21:11
I can repro on Linux `3.2.rc.custom_build.505fee0b6` consistently with the following steps:

- Create a folder `bar`
- Add a custom resource inside `bar` (probably any file works, the folder just needs to be non-empty)
- Duplicate the folder `bar` to `foo`
- Delete `bar`
- Duplicate `foo` to `bar`
- Delete `bar`

If you `rm ~/.local/share/Trash/files/bar/*`, you can delete `bar` again.

I was actually pretty surprised that Godot was even "trashing" files, given the "Can't be restored" warning I figured deleting a file in Godot just `rm`'d it.

**Comment by rcorre** [comment] 2020-02-09 21:18
I've got an even scarier extension to this that involes ending up with the wrong data in your fies:

Given the following custom resource:

```
extends Resource
class_name MyResource

export(String) var data: String
```

Create the following:

- one/
    - new_resource.tres (data = "One")
- two/
    - new_resource.tres (data = "Two")

Now:

- Duplicate `two` to `three`
- Note that `three/new_resource.tres` has `data="Two"`
- Delete the directory `three`
- Duplicate `one` to `three`
- Note that `three/new_resource.tres` has `data="Two"` (it should be "One"!!!)

Its as though Godot just restored the old deleted folder instead of duplicating `one`.

**Comment by TheDuriel** [comment] 2020-02-10 00:11
The resource may have still been open in the inspector. (which keeps previously opened resource cached. note the arrows at the top.)

**Comment by rcorre** [comment] 2020-02-10 13:12
@TheDuriel you might be right, but I can't figure out how to get the inspector to show the new value. I've saved the resource, and keep clicking between different resources, but it keeps showing the wrong value.

![1581340399](https://user-images.githubusercontent.com/2496231/74152825-1f1be980-4bdd-11ea-824d-150d55123b74.png)

**Comment by TheDuriel** [comment] 2020-02-10 19:56
Have you confirmed that the new file contains the correct value?

The point at which resources get saved, after editing, is a bit iffy. It's typically caught by general use of ctrl+s.

**Comment by rcorre** [comment] 2020-02-11 03:35
Yup, that's what I was trying to demonstrate in my less-than-obvious screenshot :)

The terminal on the right is showing the expected value in the resource file, but the UI keeps showing the old value (even after selecting a different resource and selecting the original resource again).

So the bug isn't as scary as I thought, more just annoying.

**Comment by TheDuriel** [comment] 2020-02-21 14:22
Unrelated to above.

Can confirm this still happens on 3.2 latest on Windows 10. Delete a folder, empty or not. Changes are not reflected in the File Dock, further use of the Dock risks the subfolder issue to arise.

**Comment by jluini** [comment] 2020-03-21 20:47
I'm having this issue in windows aswell.
In one ocassion I lost a scene file (tscn) when manipulating files (his contents were replaced by another scene's contents). I could recover it thanks to git.
I just recommend closing all open scenes before doing the manipulation and restart editor when it messes up.

**Comment by tinmanjuggernaut** [comment] 2020-06-20 23:08
Win10/64
Godot 3.2.1

#33378 was closed in favor of this bug, but that bug includes details and behavior that are not mentioned here. 

When deleting a subfolder Godot reimports every single file and locks up for a few minutes. It happens very often, but not every single time. When it does happen on a large project, it's very annoying as the editor is frozen and the console reports the error below. The folder usually does get removed.
```
   At: drivers/windows/file_access_windows.cpp:344
ERROR: Failed to get modified time for: D:/GD/curse-of-the-phoenix/project/assets/models/characters/goblin/Goblin/src/assets/sfx/Spot FX/Goblin/GoblinPunch4.wav.
```

**Comment by KoBeWi** [comment] 2020-06-21 11:07
I actually didn't have this bug for a long time (on operations that used to cause it pretty much always). Not sure what fixed it for me, it's possible it was fixed in one of 3.2.2 betas.

Anyone still experiencing it in 3.2.2 rc2?

**Comment by KoBeWi** [comment] 2020-07-28 20:56
Ok, I just had it multiple times in 3.2.3 rc1. It's less severe though. The reimporting still happens, but the fake folder no longer appears.

**Comment by me2beats** [comment] 2020-09-26 13:06
same bug on Windows7-64 3.2.3 
also I somehow got `platform/windows/os_windows.cpp:3611 - SHFileOperation error: 124`

I suppose this is the clue.

**Comment by cgbeutler** [comment] 2020-11-25 23:20
I have a very large project and get this printout hundreds of times. I usually run from VSCode and it can lock up VSCode for a good minute while it prints the errors. I just have to sit and wait.

Godot itself prints a different error than VSCode (aka the command line.) The command line prints stuff like:
```
ERROR: Failed to get modified time for: D:/repos/tswb/scenes/menus/world_map/icon.png.
   At: drivers/windows/file_access_windows.cpp:344
```
The file `D:/repos/tswb` is my project folder and `D:/repos/tswb/scenes/menus/world_map` is the deleted folder.

It's almost like the path to the deleted folder is set as the project root directory for a bit!? That seems crazy, though. Not sure why it would do that. Maybe a list is generated somewhere of files to re-check and it does some hack for relative paths or something... idk. Food for thought.

**Comment by akien-mga** [comment] 2020-12-03 07:36
To clarify, https://github.com/godotengine/godot/issues/27526#issuecomment-478316165 and other similar reports about `move_to_trash` on Linux are not related to this issue, they're duplicates of #42840.

**Comment by Flavelius** [comment] 2021-03-22 12:29
It's probably related; When moving folder structures around, sometimes these ghost folders remain, which are not on the actual OS filesystem, just in godot. This still happens in 3.3.rc6.

**Comment by cgbeutler** [comment] 2021-03-22 23:06
> It's probably related; When moving folder structures around, sometimes these ghost folders remain, which do not exist in the actual OS filesystem, just in godot. This still happens in 3.3.rc6.

Do those ghost folders show they they are empty? I occasionally get deleted folders show up with what looks like most of res:// as their ghost contents. Hitting delete, then cancel on anything in the tree seems to trigger a refresh that gets rid of the ghosts.

**Comment by Flavelius** [comment] 2021-03-23 06:35
They are displayed as empty. I'll try the delete-cancel trick the next time it happens, as this seems to more likely trigger on larger projects with more deep nested file/folder structures, i cannot reproduce it in simpler ones.

**Comment by KoBeWi** [comment] 2022-03-03 00:49
Can anyone still reproduce this in 3.5 or 4.0? I'm fairly sure the issue was fixed, haven't seen it in ages.

**Comment by tinmanjuggernaut** [comment] 2022-03-09 21:49
I have not seen it in a long time using 3.4 and 3.5.

**Comment by akien-mga** [comment] 2022-03-09 21:55
Thanks, assuming fixed. Please comment if you can still reproduce it in a recent Godot release.

**Closed by akien-mga** 2022-03-09 21:55 UTC
Labels: bug, topic:editor, confirmed
