### ISSUE TITLE
Android Export issue: jarsigner error #1, export.cpp warnings

### ISSUE THREAD

**Issue by DeRobyJ** [godotengine/godot#3294] opened 2016-01-09 16:35 UTC
Hi!
First of all, the installation of both godot and the android requirements went great, the guide is clear.

Then, I was able to produce and apk, but it doesn't work because of these errors.

First, jarsigner error #1, which was resolved in another issue by deleting META-INF from the apk. However I didn't find any META-INF.

In fact, this problem is probably caused by a bunch of export.cpp errors.
Whenever I try to export to Android, the program outputs these:

- platform/android/export/export.cpp:854 - Screen res name in a resource, should be plaintext
[4 times]

and then
- platform/android/export/export.cpp:799 - Application name in a resource, should be plaintext (but you can ignore this).

- platform/android/export/export.cpp:810 - Activity name in a resource, should be plaintext (but you can ignore this)

I tried it on a almost plain project of mine and on the "Area 2D input events" demo project.

So, am I missing somthing?
I'm using Ubuntu Studio 14.04, tried both Godot 1.1 and the last Alpha of 2.0 (the errors are the same)
Using Openjdk 6 from ubuntu repositories.

Thanks in advance!

**Comment by reduz** [comment] 2016-01-09 16:58
The warnings are unrelated and should eventually be removed I guess.Would
appreciate if you could describe the jarsigner error.

**Comment by DeRobyJ** [comment] 2016-01-09 17:05
Steps:
- Project open
- Export, Android
- Settings almost untouched (added project name and keystore, just to try)
- Export
the bar loads till 99%, when a message like "debug apk something" shows, then popup:
'jarsigner' returned with error #1

**Comment by reduz** [comment] 2016-01-10 17:40
Can you check the console (command line) and/or debug error log and paste the entire error?

**Comment by DeRobyJ** [comment] 2016-01-11 18:20
Sorry I'm relatively new to godot, how do I do it?

**Comment by akien-mga** [comment] 2016-07-08 14:28
I believe this was fixed by #5235.

**Closed by akien-mga** 2016-07-08 14:28 UTC
Labels: bug, platform:android, topic:porting

**Comment by reduz** [comment] 2016-07-08 14:35
this is generally also because of wrong Java version. I would kill to be
able to sign jars within Godot..

**Comment by akien-mga** [comment] 2016-07-08 14:45
This *used* to be due to wrong Java version, but honestly since I started using Godot I never saw anyone not manage to sign jars with OpenJDK 7 or OpenJDK 8. But I've seen that argument a lot :p
I think the issue is most of the time that people haven't configured their adb or signing keys properly.

**Comment by reduz** [comment] 2016-07-08 14:48
I can't sign jars with OpenJDK 9 :P

**Comment by reduz** [comment] 2016-07-08 14:49
Though It seems to be our fault, Jarsigner throws an error because the date
of the files we add is wrong in Java 8, and this becomes a fatal error in
Java 9, we should probably fix it

**Comment by akien-mga** [comment] 2016-07-08 14:51
Didn't even know Java 9 was a thing already :p
