### ISSUE TITLE
Code Editor — when dragging the mini-map it also selects code.

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#94077] opened 2024-07-08 14:41 UTC
### Tested versions

v4.3.beta.custom_build [6a13fdcae]

### System information

Godot v4.3.beta (6a13fdcae) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

When you use the mini-map in the code editor, dragging it up/down will often start selecting the code instead.

![image](https://github.com/godotengine/godot/assets/392218/bb5f5f5b-cdc7-4e21-baf1-cbe918ad795a)

### Steps to reproduce

Fiddle about in the code editor.

### Minimal reproduction project (MRP)

NA

**Comment by kitbdev** [comment] 2024-07-09 18:18
I can't reproduce (26d1577f3 Windows 10.0.22631)
Do you have a consistent setup?
Some other information that would be useful for reproduction:
- Is word wrap enabled?
- Are any lines folded?
- Is scroll_past_end_of_file enabled?
- Does the minimap take up the full height and need to scroll?
- Where are you clicking inside of the minimap?
- Were you selecting text before dragging the minimap?
- Does it happen anywhere in the script (top and bottom)?
- Did you use right-click? (If so, then it should be fixed by https://github.com/godotengine/godot/pull/91778)

**Comment by vabrador** [comment] 2024-07-09 19:44
I can reproduce this behavior on:

Windows 11 - 4.2.2.stable.official [15073afe3] - GL Compatibility - GeForce RTX 3070 Ti

if I shrink the editor window width to be as small as it is allowed to get. Additionally, only the portion near the bottom of the minimap appears to have this issue for my test script, ~300 lines of commented-out code.
 GIF:
![2024-07-09 1 Script Editor Minimap Issue](https://github.com/godotengine/godot/assets/4485426/c6e239be-9c95-4ab1-a91c-1e8d1f33d215)

For my reproduction:
- word wrap: disable
- lines folded: none
- scroll past end of file: enabled
- lower third of the minimap
- text selection prior to minimap click appears to have no impact on reproducibility
- left click only

**Comment by kitbdev** [comment] 2024-07-09 21:36
@vabrador 
- Since you are on 4.2.2 that sounds like https://github.com/godotengine/godot/issues/63842
- and it is fixed by https://github.com/godotengine/godot/pull/91720 in 4.3 beta 1.

**Comment by vabrador** [comment] 2024-07-10 02:55
@kitbdev Ah yep, looks like I was actually experiencing #63842 earlier.

Re-tested on 4.3 beta2:
Windows 11 - v4.3.beta2.official [b75f0485b] - GL Compatibility - GeForce RTX 3070 Ti
- Could not reproduce

Re-tested on the issue author's build:
Windows 11 - v4.3.beta.custom_build [6a13fdcae] - GL Compatibility - GeForce RTX 3070 Ti
- Could not reproduce
- Also could not reproduce with Forward+ renderer, word wrap, or line folding

**Comment by donn-xx** [comment] 2024-07-10 06:32
> I can't reproduce .. Do you have a consistent setup? Some other information that would be useful for reproduction:

I pull from Godot 4.3 dev main now and then and compile. Nothing fancy. 

>     * Is word wrap enabled?
I tried it both ways. Same result.
 
>     * Are any lines folded?
Also tried this both ways. Same result.
 
>     * Is scroll_past_end_of_file enabled?
I enabled it now and it's a bit harder to get the bug, but it's still happening.
 
>     * Does the minimap take up the full height and need to scroll?
Yes.
 
>     * Where are you clicking inside of the minimap?
I have tried various places in the green block (that denotes the page) and the bug varies. I notice that if I click and drag very quickly it happens. If I click, paaaauuuussseee, then drag things work as expected.

>     * Were you selecting text before dragging the minimap?
Yes and No. Both cause the bug.

>     * Does it happen anywhere in the script (top and bottom)?
Yes.
 
>     * Did you use right-click? (If so, then it should be fixed by [Fix TextEdit mouse selection and scroll cancel #91778](https://github.com/godotengine/godot/pull/91778))
I get a popup menu when I use right click, even on the map. Not sure what you mean.

**Closed** 2024-08-06 10:40 UTC
Labels: bug, topic:editor
