### ISSUE TITLE
AnimatedTexture: ext_resource, invalid UID

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#72273] opened 2023-01-28 20:53 UTC
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 10

### Issue description

I am using an AnimatedTexture to create a spinner icon, it loads 8 spinner textures and combines them into one animation.
When I close the project and delete the *.import files, then open them again, the *import files are created but the UID is invalid and I get the following warnings.

```
W 0:00:00:0803   Test.gd:5 @ _ready(): res://assets/spinner.tres:3 - ext_resource, invalid UID: uid://crhotvwkqevtn - using text path instead: res://assets/spinner/Progress7.svg
  <C++ Source>   scene/resources/resource_format_text.cpp:448 @ load()
  <Stacktrace>   Test.gd:5 @ _ready()
```

![image](https://user-images.githubusercontent.com/347037/215290705-b26fae34-d3fd-4811-a493-c9f9490239c6.png)

I used this texture in my plugin and typically the images are imported when the project is opened or a plugin is installed.
But it does not work for AnimatedTexture.

### Steps to reproduce

Open the attached project and run the test scene.
You will receive 8 warnings.

### Minimal reproduction project

[AnimatedTexture.zip](https://github.com/godotengine/godot/files/10528262/AnimatedTexture.zip)

**Comment by nezvers** [comment] 2023-02-09 12:39
Godot 4.0 RC1
`scene/resources/resource_format_text.cpp:448` Also spams when using version controls systems.
If a colleague does some changes to scenes his `uid`s are put into scene files.

**Comment by KoBeWi** [comment] 2023-02-27 22:30
*.import files are not supposed to be deleted.

**Comment by MikeSchulze** [comment] 2023-02-28 16:45
> *.import files are not supposed to be deleted. It makes them re-assign new UID and to fix that you need to save the dependent scenes again.

but it makes no sense to push *.import files to github, so this is a problem when you pull from github.
E.g. AssetLib is pulling fom GitHib.

**Comment by akien-mga** [comment] 2023-02-28 16:51
Yes, `*.import` files (like `character.png.import`) _should_ be pushed to your Git repository. Those files contain information on _how_ to import the file. If you delete them, it will use default values, which may no be what you want.

**Comment by MikeSchulze** [comment] 2023-02-28 18:57
sounds like a regression, this was not need on Godot3

**Comment by akien-mga** [comment] 2023-02-28 19:00
> sounds like a regression, this was not need on Godot3

This was the same on Godot 3. You're confusing the `*.import` files and the `res://.import/` folder (now `res://.godot/` in Godot 4). The _folder_, you shouldn't commit, but the `*.import` files, you should. It's been like this since Godot 3.0.

**Comment by MikeSchulze** [comment] 2023-02-28 19:33
hm but why i don't need them for all the other images i have?
https://github.com/MikeSchulze/gdUnit4/tree/master/addons/gdUnit4/src/ui/assets
For all this images i get no warnings, this occures only for the AnimatedTexture

**Comment by MikeSchulze** [comment] 2023-03-04 15:08
@akien-mga , @KoBeWi i fixed my issue now by update the uid's and push the *.image files to github.
But it still open the question:
Why this only happens on AnimatedTexture?
All other images had no issues.

**Comment by KoBeWi** [comment] 2023-03-04 17:00
It might have something to do with the fact that AnimatedTexture is not a "real" texture (i.e. it's not imported etc.).

**Comment by clemens-tolboom** [comment] 2023-05-23 11:27
I can confirm opening `addons/gdUnit4/src/ui/assets/spinner.tres` explicit then save makes the error go away.

I hope this downstream PR fixes it https://github.com/MikeSchulze/gdUnit4/pull/193 ... then we can close this.

**Comment by MikeSchulze** [comment] 2023-05-23 18:05
> I can confirm opening `addons/gdUnit4/src/ui/assets/spinner.tres` explicit then save makes the error go away.
> 
> I hope this downstream PR fixes it [MikeSchulze/gdUnit4#193](https://github.com/MikeSchulze/gdUnit4/pull/193) ... then we can close this.

My problem is already solved as described above. See comment from March 4
The load or preload has no affect to this scenario, the root cause is the way how Godot4 now loads resources.
On Godot 3 there was no need to store the  *.image files to github.

**Comment by KoBeWi** [comment] 2023-05-23 23:27
So what exactly is the problem here? Texture UUID is stored inside the `*.import` files, which don't exist in your MRP. Once you import the project and re-save the texture, the warnings will be gone and will not re-appear when you delete `.godot` folder. Everything functions as intended.
Also not sure what you mean by "AnimatedTexture" being special. It's not even related to the animated texture. You will get the same warning when you add a sprite to your scene with `icon.svg` and then delete `icon.svg.import`.

**Comment by MikeSchulze** [comment] 2023-05-24 09:07
@KoBeWi 
The main problem "was" that a plugin spams this kind of errors when no *.import files are included.
This was not necessary in Godot3 is only mandatory with Godot4.
At the time of bug creation I could see a different behavior of AnimatedTexture and standard textures when loading (no *.import files included). The error was only spam for AnimatedTexture.
Since I deliver the *.import files with the plugin there are no more error messages.

Be that as it may, I find it a pity that you are now forced to deliver the *.import files with the plugin, although they are newly created during the first import. Thus, in the end, the resources are found and re-imported, the displayed error is just very misleading.


For me, this is done so far, the ticket can therefore be closed gladly.

**Comment by AThousandShips** [comment] 2023-05-24 09:22
Having a special error for when a file doesn't have an `*.import` will spam users with errors each time they add a new file

But it doesn't make any sense not to include those files, how would you get import settings?

**Comment by KoBeWi** [comment] 2023-05-24 11:31
In Godot 4 the external dependencies are tracked by UID and path, and UID is checked first. Thanks to this you can have a file anywhere in the project and copy it to anywhere in another project and all dependencies will just work if you copy all necessary files. UIDs are stored inside resources. In case of TRES/RES files they are directly inside, in case of PNGs and other imported files, they obviously can't be inside the file, so they are stored inside `.import`. If you delete the `.import` file, the UID is re-assigned, so all dependencies using this UID will complain and try to use path.

While deleting these files "worked" in 3.x, it doesn't mean it was correct to do so. If you used any import settings like repeat of filter, they'd be lost.

Closing as it's not a bug nor a regression of any kind.

**Closed by KoBeWi** 2023-05-24 11:31 UTC
Labels: discussion
