### ISSUE TITLE
Gravity is still applied to RigidBody when custom integrator is enabled

### ISSUE THREAD

**Issue by missed-ledgedash** [godotengine/godot#40895] opened 2020-07-31 03:18 UTC
**Godot version:**
3.2.3-rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
Enabling the `custom_integrator` property on a RigidBody should stop gravity and other forces from being automatically applied, giving the developer full control over what forces are applied to the body. Between 3.2.2-stable and 3.2.3-rc2 there must've been a change that caused bodies to still be affected by gravity, even when it's set to use a custom integrator. I didn't test to see if air friction was also being applied, and I haven't tested RigidBody2D at all.

**Steps to reproduce:**
1. Add RigidBody to a scene
2. Enable the `custom_integrator` property
3. Run the scene (the body should still be affected by gravity)

**Minimal reproduction project:**
[rigidbody custom integrator regression test.zip](https://github.com/godotengine/godot/files/5004878/rigidbody.custom.integrator.regression.test.zip)

**Comment by Calinou** [comment] 2020-07-31 07:35
Duplicate of https://github.com/godotengine/godot/issues/40508?

**Comment by missed-ledgedash** [comment] 2020-07-31 17:54
Tested with 3.2.3-rc3, seems to have been fixed.

**Comment by akien-mga** [comment] 2020-07-31 18:17
@Calinou That was the correct duplicate, the issue was fixed by reverting the PR that caused the regression.

**Closed by akien-mga** 2020-07-31 18:17 UTC
Labels: bug, regression, topic:physics
