### ISSUE TITLE
Godot 4.0 beta 2, Resizeable/Borderless properties bug (DisplayServer regression)

### ISSUE THREAD

**Issue by ghashy** [godotengine/godot#67036] opened 2022-10-07 16:47 UTC
### Godot version

4.0 beta 2

### System information

MacBook Pro M1, Big Sur 11.7, gles3/vulkan

### Issue description

Changing of the default state of these checkboxes in project settings:

<img width="868" alt="Screenshot 2022-10-07 at 17 00 50" src="https://user-images.githubusercontent.com/109857267/194604145-2dd2eb6d-3e68-4640-a41c-481d06261311.png">

causes impossibility of changing the window position from code:

```
extends Panel

var following: bool = false
var dragging_start_position: Vector2i = Vector2i()
var mouse_position: Vector2i
var window_position: Vector2i

func _ready():
	self.connect("gui_input",Callable(self,"_on_top_bar_gui_input"))

func _on_top_bar_gui_input(event):
	if event is InputEventMouseButton:
		if event.get_button_index() == 1:
			following = !following
			dragging_start_position = Vector2i(get_local_mouse_position())

func _process(delta):
	if following && mouse_position != Vector2i(get_global_mouse_position()):
		mouse_position = Vector2i(get_global_mouse_position())
		window_position = DisplayServer.window_get_position()
		DisplayServer.window_set_position(window_position + mouse_position - dragging_start_position)
```

It worked in the first beta version.

### Steps to reproduce

Open my example project, launch it, try to move the window with a mouse( use "panel" node for moving, on the center of the window).
Next, open project settings and toggle Display/Window/Resizeable and/or Display/Window/Borderless checkboxes.
Next, launch the project and try to move the window again.

### Minimal reproduction project

[ScreenMouseDrag.zip](https://github.com/godotengine/godot/files/9735737/ScreenMouseDrag.zip)

**Comment by akien-mga** [comment] 2023-02-22 13:10
Seems fixed as of 4.0 RC 3, at least I can't reproduce it on Linux. Please comment if you still reproduce it.

**Closed by akien-mga** 2023-02-22 13:10 UTC
Labels: bug, topic:porting, regression
