### ISSUE TITLE
Godot Linux version 15/16 open then crashes shorly after

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [godotengine/godot#72527] opened 2023-02-01 17:52 UTC
### Godot version

4.0 dev beta 15/16

### System information

fedora linux, gnome de, Nvidia gtx 1650 mobile, Intel i5 9300H, 16Gb dram

### Issue description

Shortly after opening godot, the app closes itself. There is no error.

### Steps to reproduce

Open the Linux x86_64 version, wait approximately a half second, and watch it close.

### Minimal reproduction project

It's just the executable

**Comment by Yagich** [comment] 2023-02-01 20:38
Can't reproduce on Manjaro/KDE. Are you on X11 or Wayland? Can you try running the binary with `--verbose`?

**Comment by Kiwi-the-Cat** [comment] 2023-02-02 13:28
I was on Gnome on Xorg, I downgraded my Libx11 and it's working properly now

**Comment by akien-mga** [comment] 2023-02-02 13:55
Duplicate of #69352

**Closed by akien-mga** 2023-02-02 13:55 UTC
Labels: needs testing
