### ISSUE TITLE
godot error initializing : directional shadow framebuffer status invalid and other

### ISSUE THREAD

**Issue by MrPeace03** [godotengine/godot#30013] opened 2019-06-23 19:34 UTC
![Capture](https://user-images.githubusercontent.com/52131799/59981042-a3920b80-95fe-11e9-9194-a661640f18fe.PNG)

**Comment by KoBeWi** [comment] 2019-06-23 19:39
First error is a duplicate of #28894

**Comment by akien-mga** [comment] 2019-08-11 17:15
Duplicate of #28894 indeed. Not enough details to know if there's anything else here.

**Closed by akien-mga** 2019-08-11 17:15 UTC
Labels: bug, topic:rendering
