### ISSUE TITLE
`await` does not work when waiting for audio signals

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#88264] opened 2024-02-13 01:02 UTC
### Tested versions

- Reproducible in Godot 4.3.dev3.
- Not reproducible in Godot 4.3.dev2 and before, neither Godot 4.2.x

### System information

Godot v4.3.dev (d3352813e) - Windows 10.0.22631 - GLES3 (Compatibility) - Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21910.5) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

When using the `await` keyword to wait for an audio to finish with the `finished` signal, the code gets stuck and never executes the line after, even after the audio itself finished playing.

This issue **only occurs for audio signals**, others like `await get_tree().create_timer(1.0).timeout` behave fine.

Here's 2 videos, first in Godot 4.2. 
[TestGodot42.webm](https://github.com/godotengine/godot/assets/63003002/133ee058-9c53-41cd-b514-e1b94945854c)

And Godot 4.3.dev3
[TestGodot43.webm](https://github.com/godotengine/godot/assets/63003002/84e9bfe5-655c-4d83-b347-ea6e518a712d)

### Steps to reproduce

1. Have a AudioStreamPlayer node attached to your scene
2. Include it in your script.
3. Play the audio, and `await <audio>.finished`
4. Put a statement like `print("Here")` and notice how it never gets printed.

### Minimal reproduction project (MRP)

[Music Finish Await.zip](https://github.com/godotengine/godot/files/14254251/Music.Finish.Await.zip)

**Comment by KoBeWi** [comment] 2024-02-13 02:45
Duplicate of #87802

**Closed by KoBeWi** 2024-02-13 02:45 UTC
