### ISSUE TITLE
The initial offset of the CollisionShape2D is way off

### ISSUE THREAD

**Issue by TutorialDoctor** [godotengine/godot#14419] opened 2017-12-08 18:09 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mac OSX Sierra, v3.0.beta.build1, 

**Issue description:**

The initial offset of the CollisionShape2D is way off when adding it a a child to a Rigid body object.

**Steps to reproduce:**
Add  a RigidBody2D with a Sprite and CollisionShape2D node as children.

**Link to minimal example project:**

[Test Game.zip](https://github.com/godotengine/godot/files/1543476/Test.Game.zip)

**Comment by gururise** [comment] 2017-12-08 21:24
I believe this is a duplicate of #13835 

Would be nice to attach the minimal project example to the original issue though!

**Comment by gururise** [comment] 2017-12-10 17:16
I just tried this on the latest git version (in Linux) and am **unable to reproduce the bug**.  I tried with multiple RigidBody2D's at different locations with sprites.  Whenever I add a collisionshape2d, it gets added at local position (0,0) as it should. 

@TutorialDoctor Are you still able to recreate this issue in the most recent versions?

**Comment by TutorialDoctor** [comment] 2017-12-11 02:12
It happened with **Godot 3.0-dev**. It happened when I duplicated the first **RigidBody2D** with Sprite and **CollisionShape2D** to create the second group. I may have uploaded the corrected version?

**Comment by dherring** [comment] 2017-12-11 03:00
I also tried and failed to reproduce this.
Debian 9.3, Godot_v3.0-beta1_x11.64

**Comment by akien-mga** [comment] 2018-01-05 13:46
Assuming fixed/invalid since two testers could not reproduce it with recent builds. Please comment if you can still reproduce the issue in the current master branch or 3.0 beta 2.

**Closed by akien-mga** 2018-01-05 13:46 UTC
Labels: bug, topic:physics
