### ISSUE TITLE
Export NodePath gets buggy in release build. (Totally fine on debug build and editor)

### ISSUE THREAD

**Issue by ashfidable** [godotengine/godot#41494] opened 2020-08-24 19:15 UTC
**Godot version:**
Godot 3.2.2 stable

**OS/device including version:**
Windows 10

**Issue description:**
I used `export var anim_player_path: NodePath` and then initialized in a variable, `onready var anim_player: AnimationPlayer = get_node(anim_player_path)`.
and many more for my state machine (based on few nodes, 3 infact)
Now, when I instance 2-3 enemies - 
It works really well and as planned in _editor_ and _debug_ build. The moment I export a release build based on this, after I kill one enemy using `queue_free()` that got lots of export _nodepaths_. Game just crashes. Simply crashes. Then after whole day of going through this pain, checking if there was a memory leak and all that baddies. I noticed that if I **hardcode** the _nodepaths_ then exporting them, it works. 

Unfortunately, **this happens because the second instance of the enemy just references the first instance of enemy**. So when I kill the first enemy, the second enemy's animation player.. and other nodes just loses the references and the game crashes. 

I didn't find any issues about this or maybe my search was bad. I didn't try reproducing it but my enemy is really modular. So, I can try it again if you guys ask me so!

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-08-24 19:21
Duplicate of https://github.com/godotengine/godot/issues/28922. This is most likely fixed in the `master` branch but unfortunately, it can't be fixed in 3.2.x.

**Closed by Calinou** 2020-08-24 19:21 UTC
