### ISSUE TITLE
Add examples in godot engine documentation.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30034] opened 2019-06-24 14:08 UTC
I think examples are essential for documentation to be easily understandable. Here are my suggestions on the subject:

- Examples can be code blocks like the ones from the website so that they can have both C# code examples and GDScript.
- They can be foldable. This will make it easier to possibly add more than one example if desired.

And here are a few examples of how the code could be represented:
- Values should always be initiated first into variables with meaningfull names, this will help the users understand the meaning of the value better. Showcase:
`var popup = PopupMenu.new()`
`get_tree().get_root().add_child(popup)`
`popup.add_check_shortcut(shortcut,5,true)`
`popup.add_item("item a")`
`popup.add_item("item)`
`popup.add_item("item c")`
Can be changed to:
`var popup = PopupMenu.new()`
`get_tree().get_root().add_child(popup)`
`var some_index = 5`
`popup.add_check_shortcut(shortcut, some_index, true)`
`var item_value_1 = "item a"`
`var item_value_1 = "item b"`
`var item_value_1 = "item c"`
`popup.add_item(item_value_a)`
`popup.add_item(item_value_b)`
`popup.add_item(item_value_c)`
While the item value where pretty much self-examplaing, the index value of `add_check_shortcut` was not. In the second example it should be self explaining.

- Code examples should be short and as closely dedicated as possible to the class in reference (as pointed by @NathanLovato in #29911)

**Comment by clayjohn** [comment] 2019-06-24 15:32
Duplicate of https://github.com/godotengine/godot/issues/25963 Feel free to copy this over into a comment on the existing issue as your comments are helpful. It just makes the most sense for us to track all comments under one issue rather than having multiple threads going at the same time :)

**Closed by clayjohn** 2019-06-24 15:32 UTC
Labels: documentation, enhancement
