### ISSUE TITLE
Focus rect not clipped by scroll container

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#15154] opened 2017-12-29 11:07 UTC
Godot 3.0
I have a tree widget inside a scroll container, when I scroll the tree out of sight, the tree widget is clipped correctly, but the focus rect is still drawn.
![focus_rect](https://user-images.githubusercontent.com/11153232/34435847-7adf5260-ece0-11e7-9391-82954d0c47c1.png)

**Comment by Noshyaar** [comment] 2017-12-29 12:17
Duplicate of #15154 (same issue, different places)

**Closed** 2018-01-03 10:49 UTC
Labels: archived
