### ISSUE TITLE
Automatic update checking leads to broken URL

### ISSUE THREAD

**Issue by seyaidev** [godotengine/godot#92622] opened 2024-06-01 06:47 UTC
### Tested versions

- Reproducible in Godot 4.3 beta 1

### System information

Windows 11 - Godot v4.3.beta1.official [a4f2ea91a]

### Issue description

Automatic update checking lists an invalid version `4.3-4.3.` available for download, and links to a non-existent page on the Godot website.

[https://godotengine.org/download/archive/4.3-4.3](https://godotengine.org/download/archive/4.3-4.3)

![image](https://github.com/godotengine/godot/assets/10445573/873e2e0e-f200-469d-8966-58b9e69a3fe3)

### Steps to reproduce

1. Download Godot v4.3 beta 1 from the website
2. Launch it once and turn Network mode -> Online
3. Open a project and do whatever
4. Close editor
5. Re-open Godot 4.3

### Minimal reproduction project (MRP)

N/A

**Comment by lvcivs** [comment] 2024-06-01 07:58
Duplicate of #92593

**Comment by AThousandShips** [comment] 2024-06-01 08:33
Thank you for reporting, consolidating in:
* #92593

**Closed by AThousandShips** 2024-06-01 08:33 UTC
Labels: bug, topic:editor, confirmed
