### ISSUE TITLE
Can't create framebuffer for vd on old Intel GPU

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#1260] opened 2015-01-18 08:19 UTC
I created a new project in Godot, and when it was opened, the 3D view was looking weird and this error was shown at the bottom of the editor: `drivers/gles2/rasterizer_gles2.cpp:3972 - Can't create framebuffer for vd`

Here is a screenshot:

![godoterror](https://cloud.githubusercontent.com/assets/1055216/5791807/64d8fce2-9eb8-11e4-88a4-41ecd35c2aec.png)

**Comment by reduz** [comment] 2015-01-18 11:05
what is your video hardware?

**Comment by shackra** [comment] 2015-01-18 19:45
`00:02.0 VGA compatible controller: Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)`

**Comment by UsernameIsAReservedWord** [comment] 2015-01-18 21:06
I'm quite suprised that you did not have problems with this GPU before, because with the GMA3150 (which is a slightly upgraded 945GM) i had before, godot was not really usable.

it's far from being a gaming GPU .... Benchmarks show that you can expect up to 2 fps with Left4Dead. (yes, TWO fps) and an average of 4 fps (FOUR) in Doom3.

as for the error you mentionned, if you managed to run it under windows, it's normal, since the windows driver is very limited. and if you run it under linux, it is also normal since most recent opengl extensions are implemented in software and that several of them are buggy ...

**Comment by reduz** [comment] 2015-01-18 21:14
but the patch you mentioned enables optimus, which might mean you also have
an nvidia gpu in that computer?

**Comment by shackra** [comment] 2015-01-18 22:53
If you are referring to my laptop, well, no, I don't have any NVIDIA card in this laptop.

Juan Linietsky writes:

> but the patch you mentioned enables optimus, which might mean you also have
> an nvidia gpu in that computer?
>
> On Sun, Jan 18, 2015 at 6:06 PM, UsernameIsAReservedWord <
> notifications@github.com> wrote:
>
>> I'm quite suprised that you did not have problems with this GPU before,
>> because with the GMA3150 (which is a slightly upgraded 945GM) i had before,
>> godot was not really usable.
>>
>> it's far from being a gaming GPU .... Benchmarks show that you can expect
>> up to 2 fps with Left4Dead. (yes, TWO fps) and an average of 4 fps (FOUR)
>> in Doom3.
>>
>> as for the error you mentionned, if you managed to run it under windows,
>> it's normal, since the windows driver is very limited. and if you run it
>> under linux, it is also normal since most recent opengl extensions are
>> implemented in software and that several of them are buggy ...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1260#issuecomment-70425939>.
>>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/1260#issuecomment-70426276

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by UsernameIsAReservedWord** [comment] 2015-01-19 00:50
@reduz : just in case you missed the link in IRc, here it is again :
https://github.com/UsernameIsAReservedWord/intel_GMA_opengl_info

**Comment by ArcFutahito** [comment] 2015-01-25 18:25
@shackra So, basically, there is no answer, except "Get a new hardware?". Then, what hardware should I choose? What is the root of this problem? Just my videocard not being able to handle the stuff? Incompatibility with newer solutions in rendering? Not good enough drivers? What configuration won't give me bugs? 
P.S. Ugh, it's all my luck, after a week of search to find a good engine and find out that it's incompatible with my terrible hardware.

**Comment by shackra** [comment] 2015-01-25 22:40
I guess it is support, @ArcFutahito , do not despair!

**Comment by ArcFutahito** [comment] 2015-01-26 12:05
@shackra Of course I won't. The engine looks amazing (especially after reading EULAs of other "free" projects), almost too amazing to be true. So there should've been some sort of catch to it. And I'm glad it's hardware, not shady license or just plain terrible business models to get indie devs on hook *ahem* unity, anarchy, xamarin and every mainstream engine that makes you sell your soul to the devil *ahem*

**Comment by UsernameIsAReservedWord** [comment] 2015-01-26 13:27
@ArcFutahito : about hardware compatibility, maybe you could go to the forum, or to the IRC channel and ask to users what hardware and OS they successfully use with the most recent compiled version of Godot ?
Into the Developement Roadmap, it is written that OpenGL ES 3.0 backend is planned for the end of 2015.
Current version requires OpengGL ES 2.0.

**Comment by reduz** [comment] 2015-01-26 14:09
Im on vacation so you will have to wait.. Godot has a compatibility mode
for old hardware such as yours, the problem is that the detection of it is
what fails.. Exact capabilities of ancient hardware are not very easy to
detect

**Comment by ArcFutahito** [comment] 2015-01-26 14:21
@reduz Thank you for your response! It's important to have a good rest and I'm not going anywhere anyway. Just knowing that there's someone on the team aware of the issue is reassuring so, sure, take your time. If you need more data from me, I have both linux and windows installed and can provide it, given the instructions.

**Comment by punto-** [comment] 2015-01-27 09:52
We can also probably get the windows build to link against Angle libraries for better gles2 support on older hardware with some minimum head-against-desk-banging. The main problem is distributing angle (or including it somewhere to be compiled for windows and windows 8)

**Comment by shackra** [comment] 2015-03-04 01:30
Nothing new on this issue?

Is easy and cheap to get a Thinkpad T60 from amazon or Ebay to test Godot though... or you have the testing issue solved?

**Comment by reduz** [comment] 2015-03-04 01:34
probably not, this is a seriously old GPU and OpenGL 2 (Unlike Direct3D)
makes it pretty impossible to detect what is supported and what is not
Angle may solve this, but it's really not a priority

**Comment by shackra** [comment] 2015-03-04 01:35
No 3D games for me in a while then :)

**Comment by shackra** [comment] 2015-04-02 23:00
> or annoy Juan and Ariel to fix what is not working for you.

Psss, @reduz and @punto- !

**Comment by shackra** [comment] 2015-07-29 17:08
> Ok, will do a round of some weeks of bugfixing. Please update your favorite issues so they are easier to find on github! Add a comment or create new ones if not there.

Uh, are you free from priorities right now to re-visit this issue?

**Comment by shackra** [comment] 2015-11-08 21:01
Hope this is not forget. 3D used to work correctly in the early stages of Godot development...

**Comment by Ace-Dragon** [comment] 2015-12-13 20:17
Please note that even Blender will, from version 2.77 onward, expect the user to have hardware supporting OpenGL 2.1 or newer if you want to even use it (and even that is pretty darn conservative as far as graphic requirements go).

Nowadays, consider yourself lucky if you can find *any* 3D-capable application that works with such an old and basic graphics chip.

**Comment by Algrin6** [comment] 2015-12-15 17:30
Please see the next page for workaround:
http://www.godotengine.org/topics/13167

**Comment by techtonik** [comment] 2016-01-31 10:44
With 2.0 Beta I don't see the message, but GoDot is extremely slow. How can I help with detection which features it needs? I only need 2D for now.

**Comment by techtonik** [comment] 2016-01-31 10:46
Can this tool help? http://piglit.freedesktop.org/

**Comment by jabarrera** [comment] 2016-04-03 18:05
I have the same issue with my Nvidia Gforce 7300 GT on GNU/Linux.

I understand it could be hard to maintain two different renders but It'd be great to have 2D or 3D basic acceleration instead of old cards (there a a lot of them in the world :) ).

@techtonik , the message is not show because GLES2 is disabled. When you try to turn on, obviously the message is showed in the output. : )

**Comment by akien-mga** [comment] 2016-07-19 12:38
So that's yet another old GPU with half-assed OpenGL 2.1 support that we don't manage to prevent from misbehaving (see #1162). Do we can/want to do something about it, or should it be closed as wontfix?

**Comment by techtonik** [comment] 2016-07-20 12:01
If it is possible to assess half-assedness of certain card by testing specific bug-o-feature - that would be ideal variant as it allows to test drivers and reenable some bug-o-feature if the card is fixed (for example, with drivers).

Depending on half-assessment, Godot could exit, turn on full emulation (opengl32sw.dll), translation to DirectX support (ANGLE, Windows), or turn partial feature emulation (e.g. regal).

**Comment by Calinou** [comment] 2016-07-20 12:34
> turn on full emulation (opengl32sw.dll)

Does full software emulation ever give the user a good experience?

**Comment by techtonik** [comment] 2016-07-21 06:26
> Does full software emulation ever give the user a good experience?

For some game types like "visual novel" the question is why OpenGL is used at all? If Godot will be able to calculate features needed from target platform, then software emulation could be acceptable. Intel SDK may give a good performance for certain 3D features even on CPU.

**Comment by akien-mga** [comment] 2016-07-21 07:08
For game types like "visual novel", why do you want to use a 2D and 3D game engine at all? Just use Ren'Py. Use the right tool for the right purpose, don't try to bring down Godot's capabilities just to match your own usage that other simpler tools fulfil perfectly.

**Comment by techtonik** [comment] 2016-09-30 06:51
It is not to bring down Godot, but to make it more flexible. Ren'Py is awesome, but it would be more awesome to be able to extend it's narrative features with puzzles and mini games. Also, we are looking for game engine to build educational lessons and while Ren'Py has the lowest entry barrier, it needs to be expanded.

Anyway, if Godot could be flexible enough to detect what capabilities are needed for compiled game, that could be a huge win over other frameworks, especially on small platforms like Raspberry PI or maybe even Arduino.

**Comment by akien-mga** [comment] 2017-03-06 13:02
Sorry for the lack of progress on this issue in 2 years, but I think it won't ever be fixed. The trend is naturally to go towards requiring more OpenGL features, old GPUs with less than OpenGL 2.1 support (or barely 2.1, but apparently Godot 2.x needs some GL 3.0 features that 99% of OpenGL 2.1 capable hardware seems to support) are almost impossible to support.

So, this issue is a "won't fix" I guess.

**Closed by akien-mga** 2017-03-06 13:02 UTC
Labels: bug, topic:rendering

**Comment by techtonik** [comment] 2017-09-26 08:21
The design of Godot that makes all games require all its features is the showstopper for adoption.
