### ISSUE TITLE
Setter function is not called for newly created export variables

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#81972] opened 2023-09-20 11:08 UTC
### Godot version

4.2.dev.5

### System information

Windows 11

### Issue description

When you create an export variable with setter function, then changing the value in the inspector, does not call the setter function.

### Steps to reproduce

Create a scene
Add an export variable as below:
```gdscript
enum SIZE {SMALL= 100, NORMAL = 200, LARGE = 400}

@export var image_size : SIZE = SIZE.NORMAL:
	set(value):
		print(value)
@export var image_length: int = 0:
	set(value):
		print(value)
```
no go back to the inspector and change the values. There will be no print statements as the methods are not called. 

**Workaround:**
Restart the editor and it will work

### Minimal reproduction project

If required, I can provide one, but loading the project, will not reproduce the bug.

**Comment by tokengamedev** [comment] 2023-09-20 11:17
may be adding the `@tool` required editor restart. it is hard to figure out, which one is the issue.

**Comment by mieldepoche** [comment] 2023-09-20 12:17
this works on my end:
```gdscript
@tool
extends Node

enum SIZE {SMALL= 100, NORMAL = 200, LARGE = 400}

@export var image_size : SIZE = SIZE.NORMAL:
    set(value):
        print(value)
@export var image_length: int = 0:
    set(value):
        print(value)
```

you just need to reload your scene (`Scene > Reload Saved Scene`) for your new tool script to start acting I think

**Comment by tokengamedev** [comment] 2023-09-20 13:18
I will test this in 3.x and 4.1 and update

**Comment by tokengamedev** [comment] 2023-09-20 13:43
Tested on 3.5.2
The behavior was instantaneous and worked fine. It didn't require reload of scene or Project
Tested on 4.1.1
The behavior was similar to the issue here. It required either Reload of Saved scene or Project

It still remains a regression bug.

> you just need to reload your scene (Scene > Reload Saved Scene) for your new tool script to start acting I think

This is not the solution, in my opinion. and appreciate testing the scenario.

**Comment by Reverendissimo** [comment] 2023-09-25 18:07
same issue here. saving and reloading does not change anything.
i can see in the output that something is called but not my function.
the value in the inspector revert to default if i try to change it 
![image](https://github.com/godotengine/godot/assets/34273963/a59ddf88-ceae-4567-b5e3-61efa8310cc4)
![image](https://github.com/godotengine/godot/assets/34273963/597a94ff-87e4-40aa-a48d-1c870970a4ee)

**Comment by dalexeev** [comment] 2023-09-27 19:26
* Looks like a duplicate of #66381.
* Closing to consolidate the discussion, I will add details to the issue.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-09-27 19:26 UTC
Labels: bug, topic:gdscript, topic:editor
