### ISSUE TITLE
Autocomplete inside of `match` statement not working

### ISSUE THREAD

**Issue by brno32** [godotengine/godot#89576] opened 2024-03-16 16:11 UTC
### Tested versions

- Reproducible in Godot 4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.2849) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

When writing a `match` statement in GDScript, autocomplete doesn't work with enums

### Steps to reproduce

```GDScript
extends CharacterBody2D

var state = PlayerState.IDLE

enum PlayerState {
	IDLE,
	WALKING
}

func handle_movement_state():
	match state:
		PlayerState.IDLE:
			print("player is idle")
		# try adding PlayerState.W - there will be no autocomplete/intellisense
		# but it should prompt you to enter WALKING
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-03-16 16:19
Can you try this in [4.2.2.rc2](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/)?

**Comment by HolonProduction** [comment] 2024-03-16 17:06
Duplicate of #72328

**Comment by AThousandShips** [comment] 2024-03-16 17:06
Consolidating there :) Thank you for your report

**Closed by AThousandShips** 2024-03-16 17:06 UTC
Labels: bug, topic:editor
