### ISSUE TITLE
Animation Tab Resizing Freezes Godot

### ISSUE THREAD

**Issue by Captainkittyca2** [godotengine/godot#71421] opened 2023-01-14 18:57 UTC
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10, Forward+, Intel Iris Xe Graphics

### Issue description

When I resize the animation tab, there's a high chance of it freezing godot, for seemingly forever until i close godot. My project kept on freezing sometimes while resizing the animation tab. Beta 12 never crashed for me in any moment that wasn't me resizing the animation tab. It literally only happens when i'm resizing that tab, not always, but it feels like a 50/50 chance of freezing or not depending on how many seconds i'm taking to resize that tab.

### Steps to reproduce

Use Forward+ and have a 3d model with animations, try to resize the animation tab for longer than 2 seconds. If it doesn't freeze godot the first time you resize that tab, try a few more times for longer than 2 seconds.

### Minimal reproduction project

[New folder.zip](https://github.com/godotengine/godot/files/10418608/New.folder.zip)

**Comment by KoBeWi** [comment] 2023-02-04 17:19
Can't reproduce in beta 17.
Please attach a *real* MRP.

**Comment by Captainkittyca2** [comment] 2023-02-04 17:22
> Can't reproduce in beta 17. Please attach a _real_ MRP.

then that might means it was fixed in beta 17. Since i made this post using beta 12.
Also i ddin't include a real mvp because in the rules, it mentions that no need to include a mvp but i can't submit without including, which is why i did that.

**Comment by KoBeWi** [comment] 2023-02-04 17:26
You could've just written "N/A".
Like the text you highlighted said.
And while MRP can be sometimes irrelevant, not everyone has "a 3d model with animations" ready for testing (I don't).

> then that might means it was fixed in beta 17.

Comment if it's otherwise.

**Comment by Captainkittyca2** [comment] 2023-02-04 17:27
> You could've just written "N/A". Like the text you highlighted said. And while MRP can be sometimes irrelevant, not everyone has "a 3d model with animations" ready for testing (I don't).
> 
> > then that might means it was fixed in beta 17.
> 
> Comment if it's otherwise.

Just tested, and i tried resizing the tab multiple times, it didn't crash, seems fixed. In beta 12 it was so frustrating lel

**Comment by Captainkittyca2** [comment] 2023-02-04 17:28
nevermind, it just crashed

**Comment by Captainkittyca2** [comment] 2023-02-04 17:30
it took longer than normal to crash though compared to beta 12, i had to resize it from it taking up most of the vertical screen, to it taking up little of the vertical screen constantly and eventually it froze godot, the same way that beta 12 did. Only difference is took more tries

**Comment by Captainkittyca2** [comment] 2023-02-04 17:33
oh also the animation wasn't playing when i was resizing it, just a small note

**Comment by Captainkittyca2** [comment] 2023-02-04 17:37
In beta 17, you have to resize it from very short to very big and vice versa, like 10 times before it freezes godot, in beta 12, it would freeze after maybe 2 tries

**Comment by Calinou** [comment] 2023-02-04 19:33
@Captainkittyca2 Please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

**Comment by Captainkittyca2** [comment] 2023-02-27 14:21
Why was this removed from 4.0 milestone? @KoBeWi

**Comment by KoBeWi** [comment] 2023-02-27 14:24
It was never in the milestone.
Seems like no one else was able to reproduce this issue so far.

**Comment by Captainkittyca2** [comment] 2023-02-27 14:25
How can you know whether or not it wasn't in a milestone after it as removed? i'm still getting used to github overall

**Comment by KoBeWi** [comment] 2023-02-27 14:26
Not sure if regular users can see the full history.
![image](https://user-images.githubusercontent.com/2223172/221589638-54aa952b-df65-4437-9936-0bc5a660dc18.png)

**Comment by Captainkittyca2** [comment] 2023-02-27 14:27
i can't see full history, no
![image](https://user-images.githubusercontent.com/68467449/221590010-a54a21a3-a201-4c43-9842-0900b59ad115.png)

**Comment by Captainkittyca2** [comment] 2023-02-27 14:27
only "modified"

**Comment by KoBeWi** [comment] 2023-02-27 14:28
But you can see it's the only milestone note here.

**Comment by Captainkittyca2** [comment] 2023-02-27 14:29
anyways, won't adding it to milestone make a developer actually test it out?
Because right now it's in the middle of nowehere

**Comment by KoBeWi** [comment] 2023-02-27 14:35
So as I said in my first comment, you need to attach a *real MRP*, i.e. any zip with a model with animations that can be used to test the issue. I just tested with a random AnimationPlayer and it works without any problems, so this can't be reliably reproduced.

And by "No one else was able to reproduce this issue so far." I meant any user. If the issue was common or critical or whatever, there would be some duplicates or comments or at least upvotes. There is no activity here, so it's clear no other user had this problem.

**Comment by Captainkittyca2** [comment] 2023-02-27 15:58
it's not as easy to reproduce in beta 17 and RCs as it is in beta 12
The reason why i wanted people to test in beta 12 first is to check if i'm only having this issue because of my PC version combined with version of godot 4 or if it's entirely because of godot 4
With beta 17 and onwards, it still occurs but it's much more uncommon. So it's hard for even you to come by it. Which is why if i can confirm that even you or others can get it in beta 12 after about 3 tries maybe, then that means you can probably even get it in beta 17 and onwards even if it's more uncommon in those.

**Comment by YuriSizov** [comment] 2023-03-09 18:34
As there aren't any other reports for this, and there isn't a reproduction project for us to test this against, I'm going to close this report. Please try 4.0 stable and if you experience an issue, open a new report with a proper reproduction project.

Also, please keep discussions about issues on topic, and edit your messages instead of multiposting. Both of these problems makes it very hard to contributors to help you and figure out what the actual information about the problem is.

**Closed by YuriSizov** 2023-03-09 18:34 UTC
Labels: bug, topic:editor, needs testing, crash
