### ISSUE TITLE
Dragging and dropping files into the FileSystem tab crashes the editor

### ISSUE THREAD

**Issue by brogers-tech** [godotengine/godot#73264] opened 2023-02-14 02:55 UTC
### Godot version

v4.0.rc1.official

### System information

Windows 10, Forward+ Project, Mobile Project

### Issue description

When using either Forward+ or Mobile type project, if you try to drag and drop a resource into the FileSystem of a Godot Project from the operating systems file navigator, a window appears with no title or any other discerning information.  It then hangs until the Close button is pressed and then crashes Godot.  If you go back into the project the resource will be in the FileSystem.  This was tested with a .png and a .mp3 file.  

This doesn't appear to happen with a Compatibility project.  It also doesn't happen if you drag the files into the Project directory directly using the systems file system navigator like when you right click and "Open in File Manager"

### Steps to reproduce

Steps
- Create a Forward+ or Mobile Project
- Open up the directory in the operating systems file system navigator where you have a file to drag in
- From the OS' file system navigator drag the file to the Godot FileSystem tab
- Window pops up with the loading information
- Window pop up with no title or other features
- Close...wait
- Crash
- Reopen and file is in project FileSystem

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-02-14 03:13
Duplicate of https://github.com/godotengine/godot/issues/53871

Fixed by https://github.com/godotengine/godot/pull/73214

The fix will be in RC2! Please test it out once it releases to confirm.

**Closed by clayjohn** 2023-02-14 03:13 UTC
