### ISSUE TITLE
Godot 4 Beta 8 Refactoring Scenes breaks related scenes dependencies

### ISSUE THREAD

**Issue by clapik** [godotengine/godot#70130] opened 2022-12-15 22:16 UTC
### Godot version

4.0 beta 8

### System information

Windows 10, RTX3080

### Issue description

Moving the scenes to different folders will break dependencies.

### Steps to reproduce

**Reproduction Steps:**

- Create a folder, create a scene, Scene 1. Attach a script.
- Add that scene to another scene. 
- Now, move Scene 1 and its script to another folder by dragging them over.

-> All dependencies are now broken. 

**Examples of broken scenes:**
before:
```
[gd_scene load_steps=2 format=3 uid="uid://dbqutbxb7b04p"]

[ext_resource type="Script" path="res://scripts/areas/hitbox.gd" id="1_iet4x"]

[node name="Hitbox" type="Area2D"]
script = ExtResource("1_iet4x")

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
```
after being moved to another folder:
```
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://common/areas/hitbox.gd" id="1_iet4x"]
```
Another example:
before:
```
...
[ext_resource type="PackedScene" uid="uid://dbqutbxb7b04p" path="res://scripts/areas/hitbox.tscn" id="15_kkvhj"]
[ext_resource type="PackedScene" uid="uid://dcarc7q3k1m4o" path="res://scripts/areas/hurtbox.tscn" id="15_pw10o"]
[ext_resource type="PackedScene" uid="uid://brad30pn0eian" path="res://scripts/areas/chaser.tscn" id="18_wafgm"]

[sub_resource type="CapsuleShape2D" id="CapsuleShape2D_b47ho"]
radius = 4.0
height = 12.0
...
```
after (parsed error)
```
...
[ext_resource type="PackedScene" uid="uid://dbqutbxb7b04p" path="res://common/areas/hitbox.tscn" id="15_kkvhj"]
[ext_resource type="PackedScene" uid="uid://dcarc7q3k1m4o" path="res://common/areas/hurtbox.tscn" id="15_pw10o"]
[ext_resource type="PackedScene" uid="uid://brad30pn0eian" path="res://common/areas/chaser.tscn" id="18_wafgm"]
p_wrap = true
tracks/5/keys = {
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [0]
}
...
```

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-12-15 22:19
Duplicate of https://github.com/godotengine/godot/issues/69794

**Closed by akien-mga** 2022-12-15 22:19 UTC
