### ISSUE TITLE
Modifying string names in dictionary's new key field results in it constantly unfocusing

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#78773] opened 2023-06-27 22:58 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.54.03) - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

When setting the new key field to a string name, and trying to modify it, every time you type a letter the text box unfocuses.

### Steps to reproduce

 - Create a script that exports a Dictionary variable
 - Set a StringName to the new key field
 - Everytime you hit a letter on your keyboard, the text box unfocuses.

https://github.com/godotengine/godot/assets/69520693/ec035e2e-6b09-4cb6-a108-455401bfb6e2

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/11887966/minimal.zip)

**Comment by kleonc** [comment] 2023-06-28 00:30
Can't reproduce in v4.1.rc1.official [1f9e540f1]. @RadiantUwU Can you test [this version](https://downloads.tuxfamily.org/godotengine/4.1/rc1/)?

**Comment by Sauermann** [comment] 2023-06-28 04:43
Duplicate of #78712.
My guess is, that it got fixed by #78643.

**Comment by AThousandShips** [comment] 2023-06-28 05:10
Duplicate of #78712

Thank you for reporting

**Closed by AThousandShips** 2023-06-28 05:10 UTC
Labels: bug, topic:editor, usability, topic:input
