### ISSUE TITLE
Text corrupted on C# supported lastest version

### ISSUE THREAD

**Issue by MarckJavier** [godotengine/godot#93545] opened 2024-06-24 12:21 UTC
### Tested versions

4.2.2 stable c# support 

### System information

Windows 11 - Godot.v4.2.2.stable 

### Issue description

Due a configuration to use external editor visual studio.ink acces direct on windows 11 all text of godot get corrupted and it doesn't read well.
I add a picture of the bug:
![340134649-37f55f8a-2de6-4902-9fea-46200be92649](https://github.com/godotengine/godot/assets/72543902/8a709313-9605-4e09-995b-fcd975029c39)

### Steps to reproduce

create a .cs script, then try to change the highlight text form godotscript to c# on text editor in godot, then go to preferences and activate external editor and select the .ink of visual studio community 2022. Finally close and open godot proyect.

### Minimal reproduction project (MRP)

[godot proyect.zip](https://github.com/user-attachments/files/15955581/godot.proyect.zip)

**Comment by raulsntos** [comment] 2024-06-24 13:26
This looks like the messages used in [pseudolocalization](https://docs.godotengine.org/en/stable/tutorials/i18n/pseudolocalization.html). Check if pseudolocalization is enabled in Editor Settings:

![](https://github.com/godotengine/godot/assets/3903059/51bc70d5-22ea-40b1-beb5-8822cce4a5b9)

**Comment by akien-mga** [comment] 2024-06-24 13:49
Indeed, this isn't a bug, but a debug feature, which you seem to have enabled inadvertently.

Closing as it's not a bug - but we'll remove the feature anyway as several users seem to have had issues with it over the years, and the feature isn't used much.

**Closed by akien-mga** 2024-06-24 13:49 UTC
Labels: bug, platform:windows, topic:editor, needs testing, topic:gui
