### ISSUE TITLE
Can't edit TileMap or TileSet after opening its shader

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#32002] opened 2019-09-06 05:10 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10 Pro 64-bit

**Issue description:**
Once you open a Shader on a TileMap, you can no longer modify the tiles. This happens because the Shader panel is shown instead of the TileMap panel. This persists even if you close and reopen Godot. It took me a while to figure out how to resume editing the TileMap, either by:
A. Remove the Shader from the TileMap; or
B. Collapse the Shader in the Inspector the navigate away and then back to editing the TileMap.

**Steps to reproduce:**
1. Create a TileMap
2. Add a ShaderMaterial to the TileMap
3. Add a Shader to the ShaderMaterial
4. Open the Shader

**Minimal reproduction project:**
[TileMapShaderBug.zip](https://github.com/godotengine/godot/files/3582276/TileMapShaderBug.zip)

**Comment by Zireael07** [comment] 2019-09-06 06:17
I also had this issue, so big props for describing it (I couldn't figure out what I did wrong)

**Comment by KoBeWi** [comment] 2020-01-12 13:31
Seems to have the same cause as #28211

The Shader Editor blocks the Tilemap Editor.

**Comment by Zireael07** [comment] 2020-08-07 08:17
Still an issue in 3.2.3 RC3 according to securas.

**Comment by MrPingouin** [comment] 2021-05-02 14:27
I confirm the issue on Godot 3.3 stable official linux.

**Comment by Shoes01** [comment] 2021-05-06 14:28
Might be interesting to note: if you add a Shader to the specific Tile (inside TilesetEditorContext > Selected Tile > Material), you are still able to edit the TileMap.

**Comment by golddotasksquestions** [comment] 2021-06-20 00:56
@Shoes01 that's true, unfortunately in this case you no longer can access the Tileset bottom panel. 
So your options are either not being able to draw cells, or edit the Tileset anymore which both suck as even as a workaround.

**Comment by Torguen** [comment] 2021-07-09 13:56
This has been fixed in 3.3.2?
Well it works for me now, now I can edit the tilemap even though it has a shader.

https://user-images.githubusercontent.com/19652075/125089027-475b9080-e0ce-11eb-8ab9-6b865b0d5998.mp4

**Comment by KoBeWi** [comment] 2021-07-09 14:23
The issue is that you can't edit the tiles while the shader is unfolded. See the OP:
> resume editing the TileMap, either by:
B. Collapse the Shader in the Inspector the navigate away and then back to editing the TileMap.

So it's still valid.

**Comment by Calinou** [comment] 2021-07-13 17:39
As a workaround, you may be able to save the shader to an external .shader file and edit it using an external text editor.

**Comment by reduz** [comment] 2023-01-11 15:42
Does this still happen after the shader editor refactor?

**Comment by KoBeWi** [comment] 2023-01-11 15:46
Yes.

**Comment by bmolyneaux** [comment] 2023-01-12 03:28
I realized that the best way to edit the TileSet after adding a shader to the TileMap is to just select the TileSet from the Inspector:
![image](https://user-images.githubusercontent.com/1959973/211967151-84521fe9-8088-4845-9990-816a39a489e0.png)
This will activate the TileSet editor.

I think this was made a bit more obvious by the visual changes to the inspector which more clearly highlight which resource is selected within the inspector.

It looks like the TileSet and TileMap editors are (normally) automatically enabled when a TileMap node is selected (regardless of whether the TileSet resource is). However they are not enabled if the Shader was previously selected. I think a reasonable fix would be to ensure that the TileSet and TileMap editors are still enabled when a TileMap node is selected, even if the Shader editor is the one that's active.

**Closed** 2023-01-22 10:20 UTC
Labels: bug, topic:editor, confirmed, usability, topic:2d
