### ISSUE TITLE
Array slice() returns last element instead of empty array

### ISSUE THREAD

**Issue by dagophil** [godotengine/godot#38586] opened 2020-05-09 10:23 UTC
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Windows 10 Pro, 1909, 18363.778

**Issue description:**
When calling the Array.slice() function with indices that are out of range, it returns a list with the last element. I think it is more useful if an empty list is returned instead.
Examples:
`[1, 2, 3].slice(1, 0)` returns `[]`, this is okay.
`[1, 2, 3].slice(2, 1)` returns `[]`, this is okay.
`[1, 2, 3].slice(3, 2)` returns `[3]`, this is strange!

The requested behavior is important for consistency:
Say I have an array and want to create a sub-array which does not contain the first element.
For most cases, I can use `slice(1, -1)`: The result of `[1, 2, 3].slice(1, -1)` is `[2, 3]`, as expected.
However, arrays with single elements currently require special treatment, because the result of `[1].slice(1, -1)` is `[1]` and not `[]`.

**Steps to reproduce:**
A gdscript with the following content prints `[3]`, but it should print `[]`:
`print([1, 2, 3].slice(3, 2))`.
A gdscript with the following content prints `[1]`, but it should print `[]`:
`print([1].slice(1, -1))`

**Comment by madmiraal** [comment] 2020-05-09 11:00
Duplicate of #34284, and fixed with #38415, which is included in Godot 3.2.2 beta 2.

**Comment by dagophil** [comment] 2020-05-09 11:09
Okay thank you :) I searched the issues for "array slice", but I probably only searched the open issues.

**Closed** 2020-05-09 11:11 UTC
