### ISSUE TITLE
Fetching a texture in _draw() results in it being all white when attempting to draw it

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#94584] opened 2024-07-21 10:06 UTC
### Tested versions

4.3.beta3

### System information

Godot v4.3.beta3 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

The texture seems to wait for something to happen before it sets itself up and can be drawn. Unfortunately, this something doesn't happen when the texture is created in _draw() to be drawn immediately.

### Steps to reproduce

This works:

```gdscript
extends Node2D

var g: GradientTexture2D

func _ready() -> void:
	g = GradientTexture2D.new()
	g.gradient = Gradient.new()

func _draw() -> void:
	g.draw_rect(get_canvas_item(), Rect2(0, 0, 64, 64), false)
```

This doesn't work:

```gdscript
extends Node2D

func _draw() -> void:
	var g := GradientTexture2D.new()
	g.gradient = Gradient.new()
	# Adding it to a TextureRect immediately also seems to fix the issue.
	#var t := TextureRect.new()
	#t.texture = g
	g.draw_rect(get_canvas_item(), Rect2(0, 0, 64, 64), false)
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment] 2024-07-21 10:09
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/25296

**Comment by clayjohn** [comment] 2024-07-24 21:23
Ya, `g` is getting deleted at the end of the function because there any no references to it anymore. 

Closing as duplicate of https://github.com/godotengine/godot/issues/25296

**Closed by clayjohn** 2024-07-24 21:23 UTC
