### ISSUE TITLE
Connection dialog not always connect signal to node

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29540] opened 2019-06-06 11:23 UTC
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Sometimes when I try to connect signal to node, Godot shows error in Output tab and doesn't connect signal

```
ERROR: _make_or_edit_connection: Condition ' !it ' is true.
   At: editor/connections_dialog.cpp:475.
```
**Steps to reproduce:**
![file](https://user-images.githubusercontent.com/41945903/59029303-34769200-885e-11e9-914a-78ab4e5cfc09.gif)

**Comment by akien-mga** [comment] 2019-06-11 12:55
CC @YeldhamDev maybe since you poked at this class recently.

**Comment by YeldhamDev** [comment] 2019-06-11 14:33
Been trying for a while, and I'm completely unable to reproduce this. **Maybe** my latest commit fixed this? If not, could you describe exactly how you're clicking on the tree item when it happens? Maybe it's deselecting it somehow?

**Comment by qarmin** [comment] 2019-06-11 15:27
I still have this error.
With the highest probability (maybe 10 - 20%) this error occurs when I try to connect signal with root of scene.
The steps to reproduce are rather simple
1 click at node
2 fast clicks at the signal
2 fast clicks at destination node

**Comment by YeldhamDev** [comment] 2019-06-12 14:09
Does it only happen when double clicking?

**Comment by qarmin** [comment] 2019-06-12 17:23
Probably yes,
I found that sometimes Connect button just disable itself when connection window appear, and then this error occurs
![Zrzut ekranu z 2019-06-12 19-21-48](https://user-images.githubusercontent.com/41945903/59372320-87ad8080-8d47-11e9-976e-52d1011bb573.png)

**Comment by YeldhamDev** [comment] 2019-06-12 19:56
Still unable to reproduce it, but here is a little analysis:
- The `_make_or_edit_connection` method fails because there's no item selected in the tree.
- That method is only called by `ok_pressed`, which needs an item to be selected in the tree to work.
So somehow, the item is being deselected between those two functions. Now to find out how.

**Comment by YeldhamDev** [comment] 2019-06-12 20:11
Ok, let's try a solution: I assume that you know how to compile the engine, right?
So, put `set_hide_on_ok(false);` on the `ConnectDialog::ConnectDialog()` function in the "editor/connections_dialog.cpp" file. Then try reproducing the bug again.

**Comment by qarmin** [comment] 2019-06-12 21:10
Still error occurs.

**Comment by akien-mga** [comment] 2020-01-16 09:19
Is this still reproducible in the current master branch?

**Comment by KoBeWi** [comment] 2020-12-18 16:45
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-18 16:45 UTC
Labels: bug, topic:editor

**Comment by Samwalton9** [comment] 2022-08-08 09:21
I had this issue today in 3.5.stable when connecting signals in quick succession. Specifically, my setup is the following: 
<img width="239" alt="Screenshot 2022-08-08 at 10 20 10" src="https://user-images.githubusercontent.com/12038840/183384783-53d91296-895f-4ec9-b1bb-1a520dd0a9b8.png">

When connecting each of the `pressed()` signals to the MainMenu script one after another, I would sometimes get this error after clicking the Connect button. It seemed, qualitatively, like it happened if I double clicked the signal, then clicked Connect quickly.

**Comment by Samwalton9** [comment] 2022-08-08 09:21
Ah just spotted this issue has been re-opened at https://github.com/godotengine/godot/issues/63710.
