### ISSUE TITLE
Cannot use constant variable of other class as contant value of current class

### ISSUE THREAD

**Issue by quabug** [godotengine/godot#1122] opened 2015-01-05 05:17 UTC
```python
class OtherClass:
	const CONSTANT_VARIABLE = 0

const TEST = OtherClass.CONSTANT_VARIABLE
# error: expected constant expression
```

**Comment by akien-mga** [comment] 2015-11-05 17:07
Marking as a duplicate of #1110 (but we'll have to remember to check that both cases are fixed when fixing #1110, I'll make a note there).

**Closed by akien-mga** 2015-11-05 17:07 UTC
Labels: archived
