### ISSUE TITLE
Button pressed doesn't work

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#30767] opened 2019-07-23 02:04 UTC
windows 7 home 64 bit
godot 3.1.1

the pressed style on buttons doesn't seem to show.

how to reproduce?
1. make a theme and make normal, focus, and hover all have the same style.
2. give the pressed a diffrent style.
3. notice the button in the theme viewer and the game when it's ran doesn't change when you click on it.
[Desktop.zip](https://github.com/godotengine/godot/files/3419830/Desktop.zip)

please fix this for all gui controls.

**Comment by groud** [comment] 2019-07-23 08:54
Your problem comes from the fact you used a theme overriding the "Focus" status of the button.
As focus is drawn on top of the button, you cannot see the theme behind.

**Comment by bojidar-bg** [comment] 2019-07-23 08:55
Note that the "focus" stylebox is draw on top of whatever is underneath. That way you don't need additional styles for "pressed and focused", "normal and focused", "hover and focused", etc.

**Comment by groud** [comment] 2019-07-24 13:14
I will close this issue, as this is indeed not a bug. 
If you feel like the documentation lacks details on that part, please open an issue in the godot-docs repository.

**Closed by groud** 2019-07-24 13:14 UTC

**Comment by Shadowblitz16** [comment] 2019-07-26 16:24
@groud please reopen this issue the focus should not be drawn on top but drawn instead.
drawing on top makes pixelart controls very hard to do when this way both are easy to do.

if anything there should be some sort of option for this, and clearer documentation on how it is normally drawn

**Comment by groud** [comment] 2019-07-26 16:32
This is another problem then, if you think that the focus stylebox should not be drawn on top of the others, please open another issue for that.
