### ISSUE TITLE
Unable to initialize video driver. Ubuntu 18.04, Nvidia

### ISSUE THREAD

**Issue by strattonbrazil** [godotengine/godot#27494] opened 2019-03-28 15:57 UTC
**Godot version:** 3.1.stable.official
**OS/device including version:** Ubuntu 18.04, GeForce GTX 960, nvidia driver

**Issue description:**
While trying to start godot I encounter an error related to my video card not supporting a current OpenGL version.  

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:157.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:167.
Fontconfig error: Cannot load default config file
Gtk-Message: 22:07:42.387: GtkDialog mapped without a transient parent. This is discouraged.
```

This will pop up a warning saying the video driver doesn't support the necessary version of OpenGL.  

**Steps to reproduce:**
* clean build of Ubuntu 18.04
* install nvidia drivers
* reboot and confirm nvidia driver in use
* start godot

This seems identical to issue #26925, however, a reboot did not fix the problem for me.

**Comment by qarmin** [comment] 2019-03-28 19:05
Try to use this PPA https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa and install 418 nvidia drivers

**Comment by strattonbrazil** [comment] 2019-03-29 01:19
I'd like to understand the problem a bit more before switching graphics drivers. I haven't had problems with this driver and glxInfo reports a 4.x version of OpenGL. 

How does Godot derive the video capabilities?

**Comment by strattonbrazil** [comment] 2019-03-29 06:11
I built godot locally from master and was able to build and launch it without any errors.  

```
$ scons -j8 platform=x11
...
$  ./bin/godot.x11.tools.64 
OpenGL ES 3.0 Renderer: GeForce GTX 960/PCIe/SSE2
```

I'll try a release build, but I'm curious what's in the Ubuntu package that would cause this problem.

**Comment by ShyRed** [comment] 2019-04-01 18:25
@strattonbrazil Where did you get the failing Godot version from? Did you happen to use a snap install?

**Comment by strattonbrazil** [comment] 2019-04-01 19:17
@ShyRed I used the software store as well as the CLI snap install, which I'm guessing are the same build.  Both exhibited the problem.  #27548 looks like the same issue.

**Comment by ShyRed** [comment] 2019-04-01 20:04
@akien-mga All reporters verified that the official build by the Godot team is fine. It seems the snap install as well as the ubuntu software store distribute a different build which causes errors. I guess that the maintainer(s) of said builds need to investigate and fix the problem on their side? 😕

**Comment by akien-mga** [comment] 2019-04-01 20:51
Let's close as duplicate of #27548 and focus discussions there then. Feel free to paste your system details there anew for completeness (OS, GPU, driver).

**Closed by akien-mga** 2019-04-01 20:51 UTC
Labels: bug, platform:linuxbsd, topic:porting
