### ISSUE TITLE
Label and Button disappear when run on Android Virtual machine

### ISSUE THREAD

**Issue by wangdong20** [godotengine/godot#58736] opened 2022-03-04 08:12 UTC
### Godot version

3.3.2 stable

### System information

Windows10, NVIDIA GEFORCE 940MX

### Issue description

I just exported Android apk with ArmV7a and x86 architectures and install the apk in Android virtual machine which is ported on Windows10 PC. I can run the app on VM but label and buttons were disappeared after click button to go to next scene. It kept producing "a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute." errors again and again.

### Steps to reproduce

Export project as apk.
Run on Android virtual machine.
It could open the app but buttons and labels were disappeared with given errors: "a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute."
The virtual machine I am using is Pixel 2 API 27 with x86 ABI.

**Comment by Calinou** [comment] 2022-03-04 08:16
@wangdong20 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, [Godot 3.3.x is not supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.3](https://godotengine.org/article/maintenance-release-godot-3-4-3) and check if the issue still occurs there.

**Comment by wangdong20** [comment] 2022-03-04 12:16
> @wangdong20 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Also, [Godot 3.3.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.3](https://godotengine.org/article/maintenance-release-godot-3-4-3) and check if the issue still occurs there. Also make sure to test this after switching to the GLES2 renderer, as GLES3 performs poorly on low-end devices (including the Android emulator).

Just test it again with 3.4.3 Godot export. It still occurs. It seems only happened on emulator so far.

**Comment by madmiraal** [comment] 2022-03-24 18:31
I can reproduce this problem with this MRP: [GLVertexAttributeError.zip](https://github.com/godotengine/godot/files/8344338/GLVertexAttributeError.zip)

When clicking the top button and then the lower button, the lower button and it's label disappear and the logcat will produce the following errors:
```
org.godotengine.glvertexattribute E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xd3461270
org.godotengine.glvertexattribute E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 4 vbo 8 allocedBufferSize 128 bufferDataSpecified? 1 wantedStart 0 wantedEnd 184
```

**Note:** I have reproduced this on the current Android emulator (31.2.9) with the following AVD:
- Nexus 10
- Android 9 (API 28)

It does not happen with the previous Android emulator (31.2.8) with the above AVD. Neither does it happen with the current emulator (31.2.9) and another AVD: Pixel with Android 11 (API 30).

I have this issue with more than one project. All the projects generate the same error messages i.e:
```
E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute.
```
What differs is the `E/emuglGLESv2_enc: Out of bounds vertex attribute info:`. The `clientArray? 0 attribute 4 vbo 8` and `bufferDataSpecified? 1 wantedStart 0` are always the same. The difference is only in the `allocedBufferSize` and the ` wantedEnd`, but the `allocedBufferSize` is always less than the `wantedEnd`.

**Comment by madmiraal** [comment] 2022-03-28 07:08
This issue is related to batching. It works fine if I disable batching.
Furthermore, I can confirm that `vbo 8` is the buffer allocated to the batching vertex buffer here:
https://github.com/godotengine/godot/blob/d8e460cd570cf288eace241762c40998b9924cb9/drivers/gles2/rasterizer_canvas_gles2.cpp#L2330
And `attribute 4` is the texture uv that is always included here:
https://github.com/godotengine/godot/blob/fa9e2f8e211737a39b2ea5a090731a5de74d600b/drivers/gles2/rasterizer_canvas_gles2.cpp#L202-L204

**Comment by madmiraal** [comment] 2022-03-28 07:26
I suspect this has something to do with batch ordering and somewhere the memory is getting mangled, because, in my [MRP](**url**) [above](https://github.com/godotengine/godot/issues/58736#issuecomment-1077924706) in the emulator specified, if, after clicking the top button and then the lower button, to make the lower button and it's label disappear, clicking the top button again, makes the lower button reappear and the logcat error messages stop.
**Note:** The buttons are texture buttons, so, although the `normal`, `pressed`, `focused`, `hover` textures are all the same, clicking the buttons is technically changing the texture assigned to the button.

**Comment by lawnjelly** [comment] 2022-03-28 12:10
I've managed to get this reproducing with @madmiraal 's MRP and the Pixel 2 API 27 x86 emulator. I'll see if I can track this down.

**Comment by lawnjelly** [comment] 2022-03-28 12:51
It seems actually to be to do with the large texture used for the `TextureRect` (which is 5996 x 4002 pixels). If I changed the texture to from `Background.jpg` to use `icon.png`, it seems to fix it.

I can't yet say the precise cause, but it is possible either the large texture is corrupting something on the Android driver side, or there is something in batching which isn't dealing with it (perhaps maybe larger than 4096?).

I'll keep investigating. In general for Android I would advise using 2048 maximum texture size unless you can guarantee your hardware will handle 4096, and use power of two sizes where possible, especially if any wrapping might be needed.

**Comment by lawnjelly** [comment] 2022-03-29 15:36
I've been spending most of today doing verification and testing on the data concerned in the test case with lots of logging to logcat, and detective work and I can't work out anything wrong with the index buffer, vertex buffer, which VertexAttribArray are enabled, or the glVertexAttribPointer calls.

Something seems to be happening when the indices go above 4, but there are 8 verts in the vertex buffer, with a stride of 16 bytes (hence the vertex buffer is 128 bytes). But the error suggests it is trying to use up to 168 bytes:
```
2022-03-29 16:15:36.164 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: batch_upload_buffers verts size 68
2022-03-29 16:15:36.164 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: FVF_REGULAR 1088
2022-03-29 16:15:36.164 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: first vert : 0 num elements : 102 sizeof vert : 16
2022-03-29 16:15:36.191 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: batch_upload_buffers verts size 8
2022-03-29 16:15:36.191 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: FVF_REGULAR 128
2022-03-29 16:15:36.191 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: first vert : 0 num elements : 6 sizeof vert : 16
2022-03-29 16:15:36.191 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: first vert : 4 num elements : 6 sizeof vert : 16
2022-03-29 16:15:36.192 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: batch_upload_buffers verts size 68
2022-03-29 16:15:36.192 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: FVF_REGULAR 1088
2022-03-29 16:15:36.192 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: first vert : 0 num elements : 102 sizeof vert : 16
2022-03-29 16:15:36.192 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: batch_upload_buffers verts size 8
2022-03-29 16:15:36.192 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: FVF_REGULAR 128
2022-03-29 16:15:36.193 5843-5872/org.godotengine.wangdongvertexerrorbatching I/godot: first vert : 0 num elements : 12 sizeof vert : 16
2022-03-29 16:15:36.193 5843-5872/org.godotengine.wangdongvertexerrorbatching E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x94793110
2022-03-29 16:15:36.193 5843-5872/org.godotengine.wangdongvertexerrorbatching E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 0 vbo 8 allocedBufferSize 128 bufferDataSpecified? 1 wantedStart 0 wantedEnd 168
2022-03-29 16:15:36.193 5843-5872/org.godotengine.wangdongvertexerrorbatching E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0x94793110
2022-03-29 16:15:36.193 5843-5872/org.godotengine.wangdongvertexerrorbatching E/emuglGLESv2_enc: Out of bounds vertex attribute info: clientArray? 0 attribute 4 vbo 8 allocedBufferSize 128 bufferDataSpecified? 1 wantedStart 0 wantedEnd 168
```

I was suspecting the driver was being really finicky about something but I now can't discount the possibility this could be an emulator bug, there seem to have been several in this area, see:

https://issuetracker.google.com/issues?q=android%20emulator%20vertex%20attribute

@madmiraal does indicate it still occurs in 31.2.9 emulator, I've been using API 27 which may have been before any fixes.

Has anyone had this occur on actual devices?

I'm loathe to blame this on an emulator bug because there's a lot of things that can go wrong with compiling for android and differences of types etc, but I'm running out of ideas. Will keep trying.

**Comment by lawnjelly** [comment] 2023-02-12 14:19
Probably worth closing as no further reports since, and seems like an emulator bug.

**Closed by lawnjelly** 2023-02-12 14:19 UTC
Labels: bug, platform:android, topic:rendering, needs testing, topic:2d
