### ISSUE TITLE
Cannot create a Resource with a @tool annotation

### ISSUE THREAD

**Issue by vaartis** [godotengine/godot#69715] opened 2022-12-07 10:51 UTC
### Godot version

4.0.beta7

### System information

Gentoo Linux

### Issue description

When trying to create a resource with RMB > Create Resource, instead of creating it logs an error, but only if resource has a `@tool` annotation.

### Steps to reproduce

1. Try to create a resource with `@tool`
2. Look at the log, the log says:
```
  editor/editor_data.cpp:551 - Parameter "p_object" is null.
  editor/filesystem_dock.cpp:2082 - Condition "!c" is true.
```

### Minimal reproduction project

DialogueLineContainer.gd
```gdscript
@tool

extends Resource
class_name DialogueLineContainer
```

**Comment by KoBeWi** [comment] 2022-12-07 12:14
Looks like duplicate of #69356, but with different error for some reason.

**Closed by KoBeWi** 2022-12-07 12:14 UTC

**Comment by vaartis** [comment] 2022-12-07 12:30
Probably because they're trying to set the resource and I'm trying to create a new one.

**Comment by KoBeWi** [comment] 2022-12-07 12:33
Leave a comment in that issue. Pretty sure the cause is the same.
