### ISSUE TITLE
Orphan .import files should be cleaned up

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#24233] opened 2018-12-08 20:07 UTC
Godot 3.0.6

I deleted some textures from the system explorer, thinking that Godot would cleanup their .import files like Unity does. Turns out it doesn't do it. I think it would help if Godot could do this, along with cleaning up the associated data in the `.import` folder.

**Comment by girng** [comment] 2018-12-09 01:08
related to https://github.com/godotengine/godot/issues/18314 and https://github.com/godotengine/godot/issues/17733

**Comment by Calinou** [comment] 2019-07-09 23:23
Duplicate of #17733.

**Closed by Calinou** 2019-07-09 23:23 UTC
Labels: enhancement, topic:editor
