### ISSUE TITLE
Polygon2D's UV editor's Bones are displayed on wrong position

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#29009] opened 2019-05-19 17:09 UTC
**Godot version:** 3.2.dev.custom_build 
**commit:** d111d59

**OS/device including version:** Windows 10

**Issue description:** Bones are displayed on the wrong position in the Polygon2D UV editor.

You see that the Bones are displayed above the actual Polygon2D, which is wrong and doesn't look good.
![afbeelding](https://user-images.githubusercontent.com/3944421/57985325-569ea080-7a66-11e9-82ae-572a3841c11c.png)

This is how it looks in the 2D Viewport and this is also the correct position.
![afbeelding](https://user-images.githubusercontent.com/3944421/57985348-aa10ee80-7a66-11e9-97f7-c7bddb5a259a.png)

After readjusting the PivotPoint and stacking 2 Polygons 2D nodes on each other +  the Child Polygon2D also having Skeleton2D/Bones2D hierarchy ... I think after doing those things is when the issue came to the light.

**Steps to reproduce:**
With more details..

1. Get auto-imported Polygon2D by dragging and drop texture into the 2D viewport, you get choice which type node you want to use, pick Polygon2D. Redraw the Polygon2D if possible.
2. Make Skeleton2D + Bone2D hierarchy.
3. Connect Skeleton2D to Polygon2D 
4. Readjust the pivot point
5. Readjust the Bone hierarchy position again.

When you try to paint the Polygon2D's bone weights in the UV editor, the bones are not displayed on the correct position as they are in the Viewport 2D.

**Minimal reproduction project:**

In this project you can see it yourself in the Whip scene -> UV editor -> Bone weight tab.
[Polygon2DTester.zip](https://github.com/godotengine/godot/files/3195340/Polygon2DTester.zip)

**Comment by akien-mga** [comment] 2020-01-15 14:43
Still seems reproducible in the current master branch.

**Comment by madmiraal** [comment] 2020-04-18 13:33
This is not a bug.

@Qws Your "Painful" `Polygon2D` has an `Offset` of `x=-16.06` and `y=-196.055` so in the `Polygon2D UV Editor` it is drawn at this position relative to the `Skeleton2D`. If you reset the offset, you will see the `Texture` and the `Skeleton` being displayed in the `Editor` exactly the same way as in the `Polygon2D UV Editor`:
![Polygon2DUV Editor](https://user-images.githubusercontent.com/9253928/79638991-a909a500-8180-11ea-9484-ccf7adf67619.png)
Now, if you move your `Skeleton2D` to where you want it i.e. `x=16.06` and `y=196.055`:
![Polygon2DUV Editor2](https://user-images.githubusercontent.com/9253928/79639088-3a791700-8181-11ea-8be4-7149636fe7b1.png)
They will be aligned in the `Polygon2D UV Editor`:
![Polygon2DUV Editor3](https://user-images.githubusercontent.com/9253928/79639100-4d8be700-8181-11ea-8c0c-3fe1cd6c6296.png)

**Comment by madmiraal** [comment] 2020-06-28 11:43
Closing as not a bug in Godot, but an issue with the user's project.

**Closed by madmiraal** 2020-06-28 11:43 UTC
Labels: bug, confirmed, topic:editor
