### ISSUE TITLE
Tree item dragging behaves incorrectly

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#49240] opened 2021-06-01 12:21 UTC
Godot version:
v4.0.dev.custom_build.0286495f5

OS/device including version:
Windows 10

Issue description:
Tree item dragging behaves incorrectly, which seems to be a result of mishandling of touch dragging on a touchscreen. This affects the editor scene dock, file system dock, etc.
![tree_drag_1](https://user-images.githubusercontent.com/28705694/120321509-f8278080-c315-11eb-99fb-4927def0fe07.gif)

Steps to reproduce:
Add enough nodes to the scene tree until you see the scroll bar appears. Then try to drag&drop a node.

Minimal reproduction project:
No need.

**Comment by KoBeWi** [comment] 2021-06-01 13:22
Duplicate of #39087

**Closed by KoBeWi** 2021-06-01 13:22 UTC
