### ISSUE TITLE
Make square joysticks circular

### ISSUE THREAD

**Issue by isnt-alice** [godotengine/godot#27592] opened 2019-04-02 09:50 UTC
Some joysticks are "square", returning diagonals as `Vector2(1, 1)` instead of the usual `Vector2(~0.707, ~0.707)`.
This causes the same "fast diagonals" problem that naive WASD implementations have, but is significantly more difficult to fix than simply normalizing the vector.

**Comment by CptPotato** [comment] 2019-04-02 11:43
Is there a downside to normalizing it if the length is greater than 1?

**Comment by isnt-alice** [comment] 2019-04-02 11:49
Kind of? Doing that creates a deadzone in the "corners" of square joysticks.
So, everything outside the circle becomes 1.
![Diagram](https://user-images.githubusercontent.com/48971470/55400260-32145680-5502-11e9-96ab-6f3ac7e5f5f8.png)

**Comment by Zylann** [comment] 2019-04-02 13:01
I've quickly put this demo together in an attempt fo prototype a function doing such conversion:
[SquareAxis.zip](https://github.com/godotengine/godot/files/3034004/SquareAxis.zip)
But I think other approaches exist.

**Comment by groud** [comment] 2019-04-02 13:04
In any case the engine does not handle the way you map the values to a circle, it's up to the user to code it (and that's by design, specifically for those kind of issues). We only provide a way to retrieve values per-axis.
Please be a little bit more precise with your problem, do you have a code sample that do not work or something like that ?

**Comment by isnt-alice** [comment] 2019-04-02 13:31
> In any case the engine does not handle the way you map the values to a circle

In passing, I thought maybe it should, so I made this. Nothing more, really.

**Comment by groud** [comment] 2019-04-02 13:34
Well, this was lengthily discussed before, and we decided to keep things simple on the engine side and let users handle that. This fits most situations.

**Comment by isnt-alice** [comment] 2019-04-02 13:43
@groud All is good then.
@Zylann 
![square_axis](https://user-images.githubusercontent.com/48971470/55407162-5f690080-5512-11e9-8de5-1ff8b0a023a2.gif)

**Comment by groud** [comment] 2019-04-02 13:49
So I'll close this issue then, as it's neither a feature request, nor a bug. 
If you need help on you own implementation, please ask on the [other community channels](https://godotengine.org/community).

**Closed by groud** 2019-04-02 13:49 UTC
Labels: discussion, topic:input
