### ISSUE TITLE
StaticBody2D not visible by Area with Monitorable off

### ISSUE THREAD

**Issue by menip** [godotengine/godot#20364] opened 2018-07-22 17:30 UTC
**Godot version:**
cfcb6e1

**Issue description:**
Static bodies inherit physics body, so should be able to be seen via area. However, while an area with monitoring flag on and monitorable flags off can see kinematic bodies, it does not see static bodies. Enabling the monitorable flag lets area see both, but this seems to not be in line with area description.

**Minimal reproduction project:**
[StaticBodyAreaBug.tar.gz](https://github.com/godotengine/godot/files/2217245/StaticBodyAreaBug.tar.gz)
Run and see what is printed.

**Comment by akien-mga** [comment] 2018-11-05 07:05
Duplicate of #17238.

**Closed by akien-mga** 2018-11-05 07:05 UTC
