### ISSUE TITLE
GDScript 2.0: "Identifier not found" when trying to connect to super function

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#57337] opened 2022-01-28 06:59 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

windows 10

### Issue description

When when trying to connect a signal to super function, willl report "Identifier not found" when run.
![ttt](https://user-images.githubusercontent.com/35988767/151501867-855ecd41-ca06-4460-a33d-941cf42d302d.PNG)

Note: If add `self` before `f1`, it will run well.

### Steps to reproduce

1. Open the reproduction project.
2. Run

### Minimal reproduction project

[SuperFuncConnectTest.zip](https://github.com/godotengine/godot/files/7956464/SuperFuncConnectTest.zip)

**Comment by gustavi** [comment] 2022-01-29 07:51
Confirmed here. The bug is in master for months.

**Comment by AttackButton** [comment] 2022-01-29 12:19
I think for the moment using `self` could work, like `s.connect(self.f1)`.

**Comment by strank** [comment] 2022-02-12 01:50
Hi, note that this is a duplicate of #54172, and there is also a PR for that one: #56830. So #57529 and #56830 are trying to solve the same issue.

**Closed** 2022-02-12 01:54 UTC
Labels: bug, topic:gdscript
