### ISSUE TITLE
Gridmap spatial gizmo is not responding

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19860] opened 2018-06-30 18:17 UTC
Godot 3.0.4

With a Gridmap node, the spatial gizmo cannot be moved, rotated or scaled. It places tiles instead.
The gizmo should be able to receive and handle input before the gridmap plugin.

Note: when I first open the scene, the gizmo responds, but it doesn't anymore as soon as any tile in the right panel is selected.

Similar to #17499

**Comment by KoBeWi** [comment] 2020-06-15 17:11
Still reproductible in 77990b8

**Comment by KoBeWi** [comment] 2020-06-17 09:31
Sooo after some investigation, editor plugins will receive the input first, which makes it impossible to filter them out by gizmo. Maybe the gizmo should just be hidden for some plugins (e.g. the Gridmap).

**Comment by Zylann** [comment] 2020-06-17 09:33
Problem is, it makes sense for my plugin to have that gizmo...

**Comment by KoBeWi** [comment] 2020-06-17 09:37
Not really. In 2D you can edit the TileMap only when select tool is active. Move, scale and rotate tools will affect the actual node.

We could do something similar in 3D. Disable the gizmo when select tool is active and enable it on move/rotate/scale tools, but also prevent interacting with the GridMap with these tools.

**Comment by Zylann** [comment] 2020-06-17 11:59
> Disable the gizmo when select tool is active and enable it on move/rotate/scale tools

Oh no... I *never* use these modes, never needed to really... it was so handy to have everything at hand with the default tool... :(
It just feels to me the way input works here has a flawed design. If something is in front of my mouse, that thing should get the input, that's about it...

> In 2D you can edit the TileMap only when select tool is active

That's TileMap's problem though, it's was a choice for it to not have a gizmo I guess... these nodes aside, I'd be sad to be forced to switch to a different mode to move things just because gizmos can't be made to react in proper hit order.

**Comment by KoBeWi** [comment] 2020-06-17 12:33
> Oh no... I never use these modes, never needed to really... it was so handy to have everything at hand with the default tool... :(

I mean it would be disabled only for the editor plugins (and optionally), so it doesn't interfere with them. Is moving the node around that important operation in your terrain plugin? Painting should be the more common operation, and if you need to move the whole terrain, switching to move tool for a moment shouldn't be a problem (especially because we have shortcuts for that). Although I never used your plugin, so maybe I'm missing something.

**Comment by Zylann** [comment] 2020-06-17 12:36
> Is moving the node around that important operation in your terrain plugin?

It's not a frequent thing to do, but it does happen. I had users report that they can't move the terrain, and I had to tell them explicitely to do that through the inspector.

**Comment by KoBeWi** [comment] 2020-06-17 12:39
Then requiring to switch tools wouldn't hurt probably. Making gizmo work like you described wouldn't be ideal either, because it would be easy to accidentally move or rotate your nodes while editing.

**Comment by akien-mga** [comment] 2024-11-18 13:43
Fixed by #96922.

**Closed by akien-mga** 2024-11-18 13:43 UTC
Labels: bug, topic:editor, confirmed
