### ISSUE TITLE
3.0 alpha. SurfaceTool.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#8188] opened 2017-03-28 15:23 UTC
**Operating system or device - Godot version:**
Windows 10 3.0 alpha

**Issue description:**
I create a generated mesh from SurfaceTool. And its not visible in Viewport, and no error message in console. Code added to MeshInstance. Here code.

	extends MeshInstance
	
	var m
	var s = SurfaceTool.new()
	var vert = [
	Vector3(-0.5,0.5,0),
	Vector3(0.5,0.5,0),
	Vector3(-0.5,-0.5,0),
	Vector3(0.5,-0.5,0)
	]
	
	func _ready():
		s.begin(4)
	
		s.add_vertex(vert[0])
		s.add_vertex(vert[1])
		s.add_vertex(vert[3])
	
		s.add_vertex(vert[1])
		s.add_vertex(vert[2])
		s.add_vertex(vert[3])
	
		s.index()
		s.generate_normals()
		
		m = s.commit()
		set_mesh(m)

And same with custom ConcavePolygonShape(collision shape). Code added to StaticBody. Here code.

	extends StaticBody
	
	var vert = [
	Vector3(-0.5,0.5,0),
	Vector3(0.5,0.5,0),
	Vector3(-0.5,-0.5,0),
	Vector3(0.5,-0.5,0)
	]
	
	func _ready():
		generateCollisionShape()
	
	func generateCollisionShape():
		var shape = ConcavePolygonShape.new()
		var tri_arr = [vert[0],vert[1],vert[2],vert[0],vert[3],vert[2]]
		shape.set_faces(tri_arr)
	
		add_shape(shape)

**Comment by Zylann** [comment] 2017-03-28 16:28
Did you turned around the point where you generate that shape? Maybe it's because of backface culling?
I use SurfaceTool massively in my module and it works fine so far.

**Comment by sezit** [comment] 2017-03-28 17:22
I use animation for rotate node. Here i rewrite code... and nothing changed. And even add custom normals on vertex. And i not in first time use SurfaceTool and this code work perfect in 2.1.2 :3

![screeshot](https://cloud.githubusercontent.com/assets/6241034/24418299/344d2ac2-13f4-11e7-8c0d-83f0d48d9daa.png)

	extends Spatial
	
	var mesh = Mesh.new()
	var s = SurfaceTool.new()
	var vert = [
	Vector3(-1,0,-1),
	Vector3(1,0,-1),
	Vector3(1,0,1),
	Vector3(-1,0,1)
	]
	
	func _ready():
		s.begin(Mesh.PRIMITIVE_TRIANGLES)
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[0])
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[1])
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[2])
		
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[0])
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[2])
		s.add_normal(Vector3(0,1,0))
		s.add_vertex(vert[3])
	
		s.index()
	
		mesh = s.commit()
		$MeshInstance.set_mesh(mesh)

**Comment by Zylann** [comment] 2017-03-28 17:52
I see a black quad, which is ok because you have no lights in your scene and it has no UVs and no colors.

**Comment by sezit** [comment] 2017-03-28 18:14
@Zylann This screenshot from 2.1.2 - of course its works. You use build from what date?

I use night build from "fixnum.org/godot/", and last build where this code works is "February 16, 2017 at 17:22" and yes it's Godot 3.0. Maybe its helps :3

**Comment by Zylann** [comment] 2017-03-28 18:55
I use build af282b56feb8d84049f911dd1d91d82bd2211727

**Comment by bojidar-bg** [comment] 2017-03-30 11:32
So, should we close this as fixed?

**Comment by sezit** [comment] 2017-03-30 20:43
Today's build still not working.

**Comment by Zylann** [comment] 2017-03-30 22:16
Hmmm... looks like some configurations don't work. I made a triangle that shows, but if I give it a slightly bigger size, it vanishes.

**Comment by Zylann** [comment] 2017-03-30 22:23
Ok, weird weird weird:

This shows a triangle:
```gdscript
	var s = SurfaceTool.new()
	var k = 1.0
	s.begin(Mesh.PRIMITIVE_TRIANGLES)
	s.add_vertex(Vector3(-k,0,-k))
	s.add_vertex(Vector3(1,0,-k))
	s.add_vertex(Vector3(1,0,1))
	var mesh = s.commit()
	$MeshInstance.set_mesh(mesh)
```
This doesn't:
```gdscript
	var s = SurfaceTool.new()
	var k = 1.0
	s.begin(Mesh.PRIMITIVE_TRIANGLES)
	s.add_vertex(Vector3(-1,0,-1))
	s.add_vertex(Vector3(1,0,-1))
	s.add_vertex(Vector3(1,0,1))
	var mesh = s.commit()
	$MeshInstance.set_mesh(mesh)
```

**Comment by sezit** [comment] 2017-03-31 08:34
Lol, just tested all OK (about print Vector3()) :3
![1](https://cloud.githubusercontent.com/assets/6241034/24542859/f39a7584-1605-11e7-8bb5-4197e22c004f.png)

**Comment by Zylann** [comment] 2017-03-31 09:06
You have to test the exact same script, really, otherwise it doesn't repro. @Hinsbart got the same issue after doing that too. It's extremely fishy :'D

**Comment by bojidar-bg** [comment] 2017-03-31 09:09
I think this is a bug stemming from #7815, @hpvb.

@Zylann And no, that's not the first paranormal bug with hashing either: #3843 :wink:

**Comment by hpvb** [comment] 2017-03-31 09:59
It's possible, but it would surprise me as I don't see how the hashing codepaths could be called in this case. I'll do a little gdb investigating this weekend.

**Comment by jmf** [comment] 2017-04-13 14:02
I used the following code to successfully generate a triangle:
```gdscript
extends MeshInstance

func _ready():
	var tri = Mesh.new()
	var surfTool = SurfaceTool.new()
	surfTool.begin(Mesh.PRIMITIVE_TRIANGLES)
	surfTool.add_vertex(Vector3(0,5,0))
	surfTool.add_vertex(Vector3(10,5,0))
	surfTool.add_vertex(Vector3(10,5,10))
	
	surfTool.generate_normals()
	surfTool.index()
	surfTool.commit(tri)
	set_mesh(tri)
```
I have no problems with generation. Bigger meshes are also no problem, as this screenshot shows:
https://lut.im/L4wicny39A/njEtUjEIFxrszZMM.png

**Comment by jmf** [comment] 2017-04-13 14:32
Ah, I didn't understand the issue at first. Since I never have vertexes with the same position hashes in a triangle, this problem never occurred for me.

**Comment by bojidar-bg** [comment] 2017-04-13 14:49
I tested this right before #7815 and right after #7815 (on 36986531afe3996de05640ff02088d18b24d409c and 903a3aa5f0e128abb1fb752c10b343b34af8f799), and I can confirm that the issue is caused by it.

Testing script:
```gdscript
func _ready():
  print(Vector3(-1, 0, 1))
  print(Vector3(1, 0, -1))
```

Pre-#7815 output:
```
(-1, 0, 1)
(1, 0, -1)
```
Post-#7815 output:
```
(-1, 0, 1)
(-1, 0, 1)
```

Closing as duplicate (and another symptom of) #8081.

**Closed by bojidar-bg** 2017-04-13 14:49 UTC
Labels: bug, confirmed, topic:gdscript
