### ISSUE TITLE
MacOS crash with backtrace

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#61199] opened 2022-05-19 18:41 UTC
### Godot version

3.5.rc

### System information

MacOS 12.2 M1

### Issue description

Program crashed during routine project editing/running.

 handle_crash: Program crashed with signal 11
 Engine version: Godot Engine v3.5.rc.custom_build
 Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
 [1] 1   libsystem_platform.dylib            0x00000001acadc4e4 _sigtramp + 56
 [2] Object::call_multilevel_reversed(StringName const&, Variant const**, int) (in godot35rc1) (object.cpp:772)
 [3] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (in godot35rc1) (gdscript_function.cpp:0)
 [4] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (in godot35rc1) (object.cpp:899)
 [5] _Thread::_start_func(void*) (in godot35rc1) (core_bind.cpp:2715)
 [6] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (in godot35rc1) (thread.cpp:79)
 [7] void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >(void*) (in godot35rc1) (thread:299)
 [8] 8   libsystem_pthread.dylib             0x00000001acac5240 _pthread_start + 148

### Steps to reproduce

I added a prints() line to a script while the project was running - never crashed before like this.

**Comment by Koyper** [comment] 2022-05-19 18:48
I was fixing an out-of-range index error in OptionButton.get_item_metadata() that may have also caused an error statement from the godot-sqlite plug-in (https://github.com/2shady4u/godot-sqlite). This code has been completely stable through 3.4.4.stable.

**Comment by Koyper** [comment] 2022-05-19 19:06
There appears to be a regression with the OptionButton indexing - I will try to isolate it and post a separate issue...

**Comment by Calinou** [comment] 2022-05-19 20:01
> There appears to be a regression with the OptionButton indexing - I will try to isolate it and post a separate issue...

In this case, that would be a duplicate of https://github.com/godotengine/godot/issues/61179.

**Comment by Koyper** [comment] 2022-05-19 20:26
> In this case, that would be a duplicate of #61179.

Yes, I believe that is the same issue. Thanks!

**Closed** 2022-05-19 20:29 UTC
