### ISSUE TITLE
Shader Material First Rendering Is Black

### ISSUE THREAD

**Issue by Yunxi-awa** [godotengine/godot#95012] opened 2024-08-01 09:09 UTC
### Tested versions

- Reproducible in: 4.3.rc1.mono

### System information

Godot v4.3.rc1.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.5592)

### Issue description

No shader:
![image](https://github.com/user-attachments/assets/f8d67521-7cd3-4155-bfa1-d09eb1941177)

If you add a ShaderMaterial to it and set a shader (the code can be viewed below):
![image](https://github.com/user-attachments/assets/652eb6e7-377f-4ec9-9860-ed9cfe623730)

To make it not render as black, just change the filter parameter:
![image](https://github.com/user-attachments/assets/2fc247e9-a1d4-4faf-879b-077a5f8d374f)

Then change it back to 1.0: (Desired Rendering Results)
![image](https://github.com/user-attachments/assets/27e15ef1-31cd-4871-b0b4-14e5acb9bcfa)

### Steps to reproduce

1. Create a shader:
```
shader_type canvas_item;

uniform float filter: hint_range(1.0, 2.0, 0.1);

void fragment() {
	 vec4 tex = texture(TEXTURE, UV);
	 COLOR = vec4(tex.rgb * filter, tex;)
}
```
2. Select a control and add a ShaderMaterial, while setting the shader to the one you just created.
3. Your control will be rendered in black.
4. change the parameter called filter to another value and change it back to 1.0. You will notice that although the filter parameter was also 1.0 when you added the shader, it does not appear black this time.

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment] 2024-08-01 17:10
If I had to guess, I would say that the default value is 0, but the editor clamps the displayed value to 1 because the range is 1-2.

Following your reproduction steps then checking the resulting .tscn file, I can see the filter value is indeed defaulting to `null` 

```
[sub_resource type="ShaderMaterial" id="ShaderMaterial_aqsde"]
shader = ExtResource("1_dplo5")
shader_parameter/filter = null
```

**Comment by clayjohn** [comment] 2024-08-01 17:12
After searching existing issues, it turns out that this is a duplicate of a known issue, https://github.com/godotengine/godot/issues/44454

Accordingly, I will close this issue in favour of https://github.com/godotengine/godot/issues/44454 so that we can track the problem in one place

**Closed by clayjohn** 2024-08-01 17:12 UTC
Labels: bug, topic:editor, confirmed, topic:shaders
