### ISSUE TITLE
Breakpoints or errors cause Godot window to be flagged as "Not Responding" by Windows

### ISSUE THREAD

**Issue by petermcgarvey1111** [godotengine/godot#95506] opened 2024-08-14 01:45 UTC
### Tested versions

This happens to me in 4.2.2 and 4.2.1 but not in 3.5.3.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21910.5) - AMD Ryzen 5 1400 Quad-Core Processor (8 Threads)

### Issue description

Basically if there is an error OR a breakpoint, the runtime goes "not responding" and needs to close. It makes it impossible to debug anything. Screenshot of a project with nothing but a breakpoint causing this:

![image](https://github.com/user-attachments/assets/218214e2-0117-47c3-add8-0b339d9bc9d9)
![Untitled](https://github.com/user-attachments/assets/0c9701d4-ffc9-4b23-a921-29bfb999d57a)

### Steps to reproduce

Add a breakpoint in any line of code that will run, and run the project

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment] 2024-08-14 07:20
CC @bruvzg

**Comment by bruvzg** [comment] 2024-08-14 07:23
This should be already fixed by https://github.com/godotengine/godot/pull/94452

**Comment by akien-mga** [comment] 2024-08-14 07:36
Duplicate of #73374 then.

**Closed by akien-mga** 2024-08-14 07:36 UTC
Labels: platform:windows, topic:porting, needs testing
