### ISSUE TITLE
Cannot assign elements to an exported Array of Nodes

### ISSUE THREAD

**Issue by saltern** [godotengine/godot#77084] opened 2023-05-15 02:34 UTC
### Godot version

v4.0.3.rc2.mono.official [2ac4e3bb3]

### System information

Windows 10 22H2

### Issue description

When exporting a variable where the type is any kind of node, a box saying "Assign..." appears and you can specify a node via the editor no problem. When the exported variable is an array of nodes, the same box appears for each element in the array, but attempting to assign a node in the same way does nothing.

### Steps to reproduce

- Create a node, attach a script to it, and in it create an export variable with type Array[Node].
- From the inspector, add a new element to the array.
- Click "Assign..." to bring up the "Select a Node" window.
- Choose any node.
- The node doesn't get assigned and the array remains unchanged.

### Minimal reproduction project

[Node array export.zip](https://github.com/godotengine/godot/files/11473709/Node.array.export.zip)

**Comment by Calinou** [comment] 2023-05-15 02:59
- Duplicate of https://github.com/godotengine/godot/issues/62916.

**Closed by Calinou** 2023-05-15 02:59 UTC

**Comment by VikingAntics** [comment] 2023-05-31 03:26
This bug is fixed in 4.1 dev3, however, if you add @tool to the script, it reverts to the previous bugged behavior and will not assign the selected node.  It does 'flash' the change for an instant, but then reverts back to the original value.
