### ISSUE TITLE
Allow scripts marked with `class_name` to use their class within the script without causing a cyclic dependency

### ISSUE THREAD

**Issue by novemberisms** [godotengine/godot#25252] opened 2019-01-23 10:50 UTC
**Godot version:** 
3.1 beta 2

**OS/device including version:** 
Windows

**Issue description:**
As suggested in the title, having a script not be able to use its own Class name in its own script is severely limiting. For instance, one could not make any factory methods or methods that make more of the class. I came across this limitation when trying to make a 'Set' class. Trying to use the identifier `Set` results in an error: `Parser Error: Using own name in class file is not allowed (creates a cyclic reference)`

```
extends Reference
class_name Set

# with static typing
# this line causes an error
func union(other: Set) -> Set: 
    # this line also causes an error
    var result = Set.new() 
    # do stuff
    return result

# even without static typing

func intersection(other):
    # we can't even do this
    var result = Set.new()
    # do stuff
    return result

func copy():
    return Set.new(my_items)
```

**Comment by novemberisms** [comment] 2019-01-23 10:53
**Temporary Workaround**
I found a way to do what I want here, but it feels inelegant and renaming the script or moving it becomes a hassle.

```
extends Reference
class_name Set

var Self = load("res://set.gd") # set.gd is the name of the script

func union(other): 
    var result = Self.new() 
    # do stuff
    return result

func intersection(other):
    var result = Self.new()
    # do stuff
    return result

func copy():
    return Self.new(my_items)
```

**Comment by Chaosus** [comment] 2019-01-23 11:05
Seems like a duplicate of #21461..

**Comment by novemberisms** [comment] 2019-01-30 06:15
UPDATE: It seems as of 3.1 beta 3, this is now allowed

```
class_name MyClass

func test(instance: MyClass) -> MyClass:
    return instance
```

Thank you to whoever worked on this issue! It really helps a lot.

However I cannot close this yet as the following is still not allowed

```
class_name MyClass

var id: int

func _init(n: int):
    id = n

func clone() -> MyClass:
    return MyClass.new(id) # still causes the cyclic dependency error
```

**Comment by Angular-Angel** [comment] 2019-04-30 15:06
Mmm, I ran into this issue too. Need to check if a nodes parent is the same class as it, but can't. Be nice to see it patched out soon. :/

**Comment by Angular-Angel** [comment] 2019-05-01 13:38
I found a work around by overriding get_class to give the right answer, then going "get_class().case_comp(parent.get_class()), but it's kind of a hack. Being able to do things properly would be nice. :/

**Comment by silkentrance** [comment] 2019-05-25 21:25
While you can use the class_name as type hints to parameters of methods of your class, you cannot use them as type hints for the return result. The latter will give you the error described by the OP.

```
extends Node
class_name Useful

func equals(p_other: Useful) -> bool:

  return false

func copy() -> Useful:

  return Useful.new()
```

While `equals` will work just fine, `copy` will result in the parser complaining about a cyclic reference.

To resolve this issue, one must use `get_script().new()`, e.g.

```
func copy() -> Useful:

  return get_script().new(with-params)
```

and if you have a base class that implements this, you need to

```
func duplicate() -> TimeInfo:

  return get_script().get_base_script().new(with-params)
```

rather complicated, but this is a valid work around and also removes the need to the preload.

**Comment by Gastronok** [comment] 2019-08-12 13:39
You can't use class_name type hints even in parameters if some other class also has a type-hinted reference to your class.

Having a main scene with   
```
extends Node2D

func _ready():
	var attribute : Attribute = null
```
And a separate class with:
```
extends Node
class_name Attribute

func function(other_attribute : Attribute) -> void:
	pass
```
will still fail in eb98c5e04 with a cyclic dependency error, though removing either one of the Attribute hints will succeed.

Also in my particular project the cyclic dependency error is not shown by the editor so this manifests as a resource leak.

**Comment by RomanKoziolek** [comment] 2020-02-16 15:26
I hope my finding will help at least some of you.

Short: I could check own custom class when I used **as** operator.
Long:
I'm developing a mission objectives system for my game and use a hierarchy of nodes of custom class MissionObjectiveBase which have child nodes inheriting from this custom class.

I got the cyclic dependency error when I used the `is` operator:
`child is MissionObjectiveBase`

but it worked fine when I used the `as` operator:
`child as MissionObjectiveBase`

I use Godot **3.2**.

**Comment by rrei** [comment] 2020-02-27 22:58
@RomanKoziolek nice find! I've also tested and confirmed this to be working in 3.2!

It's just a pity that this kind of obscure hack is needed in the first place, so I hope this is properly fixed in GDScript soon...

**Comment by aaronfranke** [comment] 2020-04-19 23:06
This is a duplicate of #21461.

**Closed by aaronfranke** 2020-04-19 23:06 UTC
Labels: topic:gdscript, usability

**Comment by AliBouarab** [comment] 2020-11-20 17:48
I had the same issue when that prevented me to implement a Builder pattern using a static method:
```
class_name MyClass

static func build() -> MyClass:
  var new_instance  = MyClass.new()
  ...
  return new_instance
```
Workaround described  [by ](https://github.com/godotengine/godot/issues/25252#issuecomment-456757786) is nice but require to not change file tree without changing source code.

I use this trick to have current source file path even in static method (in which get_script() is not available):
```
static func build() :
    var new_instance = load(GodotExt.current_script_path()).new()
    ...
    return new_instance
```
with
```
class_name GodotExt

static func current_script_path():
    return get_stack()[1].source    <- return usable script path
```
This trick can be used to avoid similar cyclic dependency issue.
This call stack using may slow execution but it works, waiting for incoming global dependency fixing
