### ISSUE TITLE
Tooltips with rounded corners appear with square black corners in non-embedded windows

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#92883] opened 2024-06-07 17:40 UTC
### Tested versions

- Reproduces in v4.1.2-rc1
- Doesn't happen in v4.1.1-stable
- First bugged commit is c66dfd2cfe8f2bb11b1ac5b237b9aba63fdd069f

### System information

Windows 11 - Vulkan (Forward+) - MD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

When the project setting "Embed Subwindows" is off, tooltips with rounded corners have a rectangular black background behind the tooltip.

What it should look like:

![expected](https://github.com/godotengine/godot/assets/8843118/f0587406-cd8c-4518-8157-bfa135b7d618)

What it looks like:

![actual](https://github.com/godotengine/godot/assets/8843118/92c0c2b2-4478-4e38-8b9b-a850ce4fe378)

In the "working" version the tooltips actually do also have a rectangular background, but it's the same color as the parent's background so it's a lot harder to see.

### Steps to reproduce

Run MRP and hover the button.

### Minimal reproduction project (MRP)

[tooltip-corners.zip](https://github.com/user-attachments/files/15742312/tooltip-corners.zip)

**Comment by kleonc** [comment] 2024-06-07 19:51
Can reproduce in:
- v4.1.4.stable.official [fe0e8e557]
- v4.2.2.stable.official [15073afe3]
- v4.3.dev5.official [89f70e98d]

Can't reproduce in:
- v4.3.dev6.official [89850d553]
- v4.3.beta1.official [a4f2ea91a]

Probably fixed by #86553, specifically:
https://github.com/godotengine/godot/blob/e96ad5af98547df71b50c4c4695ac348638113e0/scene/main/viewport.cpp#L1477-L1478

I guess this part only needs to be backported into 4.2 and 4.1, the rest seems unrelated? :thinking: cc @Koyper

**Comment by anniryynanen** [comment] 2024-06-07 19:53
This also happens in master.

**Comment by anniryynanen** [comment] 2024-06-07 20:00
...but I also see it in v4.3.beta1, so there must be something different in our setups.

**Comment by anniryynanen** [comment] 2024-06-07 20:19
I checked it on my laptop to see if it's a Windows only issue, but I can also reproduce this in

Godot v4.3.beta1 - Arch Linux <span>#</span>1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 - Tty - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

**Comment by kleonc** [comment] 2024-06-07 20:19
> ...but I also see it in v4.3.beta1, so there must be something different in our setups.

Oh, I've tested on the Compatibility renderer, that must be it (sorry for not mentioning it before).

**Comment by Koyper** [comment] 2024-06-07 20:28
> I guess this part only needs to be backported into 4.2 and 4.1, the rest seems unrelated? 🤔

Yes, the transparent flag setting for non-embedded windows was added by #86553, but the Project per_pixel_transparency has to be enabled for it to work. If that doesn't actually work, please report here and I'll have a look.

**Comment by anniryynanen** [comment] 2024-06-07 20:34
Per pixel transparency fixes it for me in Linux, but not in Windows.

**Comment by bruvzg** [comment] 2024-06-07 20:42
> Per pixel transparency fixes it for me in Linux, but not in Windows.

Per-pixel transparency should almost always work with OpenGL, but with Vulkan it depends on GPU driver capabilities, and a lot of Windows drivers do not support it (and it can't be fixed in Godot while preserving reasonable performance).

**Comment by bruvzg** [comment] 2024-06-07 20:44
https://vulkan.gpuinfo.org/listsurfacecompositealphamodes.php?platform=windows - seems like currently only 12.7% of Windows systems support it.

**Comment by Koyper** [comment] 2024-06-07 20:45
Works correctly for MacOS also. You could call `DisplayServer.is_window_transparency_available()` on Windows and see what happens?

>Returns true if the window background can be made transparent. This method returns false if Display > Window > Per Pixel Transparency > Allowed is set to false, or if transparency is not supported by the renderer or OS compositor.

**Comment by anniryynanen** [comment] 2024-06-08 04:43
That must be it, `DisplayServer.is_window_transparency_available()` is `false`.

How does the Godot editor have transparent rounded corners? They work fine for me in Windows and the editor performance is fine for a non-game app. I guess it's the window decorations from Windows.

The project I want these tooltips for is also not a game and doesn't need super performance, so maybe I could make my own Godot build for it with the pixel transparency support.

Or I could add it as a code only option to Godot and put it behind a huge "THIS WILL KILL YOUR PERFORMANCE" warning. Would that be likely to be merged if I made a PR?

**Closed** 2024-06-08 04:47 UTC
Labels: bug, confirmed, regression, topic:gui

**Comment by bruvzg** [comment] 2024-06-08 07:11
> How does the Godot editor have transparent rounded corners?

Where? I think Godot editor is not using transparent corners anywhere, and do not have transparency enable.
> Would that be likely to be merged if I made a PR?

**Comment by bruvzg** [comment] 2024-06-08 07:14
> Or I could add it as a code only option to Godot and put it behind a huge "THIS WILL KILL YOUR PERFORMANCE" warning. Would that be likely to be merged if I made a PR?

It's not implemented, but we tested something similar for 3.x at some point, and performance was abysmal, like 3.fps max. The idea is to render to the offscreen texture and present it using `UpdateLayeredWindow`.

**Comment by anniryynanen** [comment] 2024-06-08 07:21
> > How does the Godot editor have transparent rounded corners?
> 
> Where? I think Godot editor is not using transparent corners anywhere, and do not have transparency enable.

In the settings windows:

![image](https://github.com/godotengine/godot/assets/8843118/d6fcdb9c-d0f2-40e1-bcda-c7bf611b0670)

**Comment by anniryynanen** [comment] 2024-06-08 07:22
I'm guessing it's because they're native windows and have the Windows decorations.

**Comment by bruvzg** [comment] 2024-06-08 07:23
> In the settings windows

It's a standard Windows 11 window frame, Godot is not drawing or controlling it.
