### ISSUE TITLE
  Can't open file from path 'res://.godot/global_script_class_cache.cfg'.

### ISSUE THREAD

**Issue by flobotics** [godotengine/godot#72284] opened 2023-01-28 22:50 UTC
### Godot version

d33c1b50

### System information

win 11

### Issue description

If you build a XR project you get this output in  
 Can't open file from path 'res://.godot/global_script_class_cache.cfg'.

### Steps to reproduce

create project with 3d node and xr-origin, xr-camera, xr-controller, enable xr in project settings and build for windows, then this output appears 

### Minimal reproduction project

create project with 3d node and xr-origin, xr-camera, xr-controller, enable xr in project settings and build for windows, then this output appears

**Comment by kuhnchris** [comment] 2023-01-28 23:25
By "Build for Windows" I assume you mean create an export for Windows Desktop, correct?
Because just from the description itself within the editor I haven't got an issue (aside from the shaders throwing
```
ERROR: Condition "variant_size == 0 && variants_enabled[i]" is true. Returning: false
   at: ShaderRD::_load_from_cache (servers\rendering\renderer_rd\shader_rd.cpp:410)
``` times 20 or so after activating XR)

Do these errors pop up on your side too?
```


ERROR: OpenXR: Unsupported io path /interaction_profiles/htc/vive_cosmos_controller/user/hand/left/input/system/click
   at: (modules\openxr\openxr_api.cpp:264)
ERROR: OpenXR: Unsupported io path /interaction_profiles/htc/vive_focus3_controller/user/hand/left/input/system/click
   at: (modules\openxr\openxr_api.cpp:264)
ERROR: OpenXR: Unsupported io path /interaction_profiles/htc/vive_focus3_controller/user/hand/right/input/trigger/touch
   at: (modules\openxr\openxr_api.cpp:264)
ERROR: OpenXR: Unsupported io path /interaction_profiles/htc/vive_focus3_controller/user/hand/left/input/thumbrest/touch
   at: (modules\openxr\openxr_api.cpp:264)
```

I'm compiling the debug export templates so it will take me a hot minute to confirm if your error is due to the "Export" part, I'll let you know what I can see from my side.

**Comment by kuhnchris** [comment] 2023-01-28 23:58
Hmm, I cannot confirm this issue, sadly - all I get is this:
```
C:\Users\kuhnc\Documents\Issue72284\export>export.exe

C:\Users\kuhnc\Documents\Issue72284\export>Godot Engine v4.0.beta.custom_build.218bef90a - https://godotengine.org
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   0.1.0
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.2.0
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650

ERROR: Couldn't find the given section "" and key "list", and no default was given.
   at: (core\io\config_file.cpp:87)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
ERROR: Condition "active_sets.size() == 0" is true. Returning: false
   at: OpenXRAPI::sync_action_sets (modules\openxr\openxr_api.cpp:2535)
```

Could you please upload your project so I can check if it may have already been fixed on the latest `master` ?
Attached I added my minimal project for this: [Issue72284-xr.zip](https://github.com/godotengine/godot/files/10528606/Issue72284-xr.zip)

**Comment by flobotics** [comment] 2023-01-29 16:06
i downloaded beta-16,created new project, created a 3d-node, saved the scene, downloaded export templates, export windows-desktop (no xr enabled or anything) and export


<img width="755" alt="cfg-file-error" src="https://user-images.githubusercontent.com/11964445/215339017-f6140341-4b60-453a-ab79-249acffde999.png">

**Comment by bitsawer** [comment] 2023-02-05 09:32
Similar to https://github.com/godotengine/godot/issues/72451, should be fixed by https://github.com/godotengine/godot/pull/72452.

**Comment by akien-mga** [comment] 2023-02-06 15:08
Duplicate of #72451

**Closed by akien-mga** 2023-02-06 15:08 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing, topic:export
