### ISSUE TITLE
Godot 4, in GDExtension, calling the function godot::ResourceLoader::get_singleton()->load(fullpath); will crash when exiting

### ISSUE THREAD

**Issue by dualfold** [godotengine/godot#69898] opened 2022-12-11 07:31 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

In GDExtension, calling the function ResourceLoader::get_singleton()->load(path); would result in a crash when godot editor exits.

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (ae86d907e75c3de9b039e7cc77e521bc9739e6dc)
Dumping the backtrace.
[0] <couldn't map PC to fn name>
[1] Object::~Object (D:\godotengine\godot\core\object\object.cpp:1834)
[2] JavaClassWrapper::`scalar deleting destructor'
[3] unregister_core_types (D:\godotengine\godot\core\register_core_types.cpp:370)
[4] Main::cleanup (D:\godotengine\godot\main\main.cpp:3446)
[5] widechar_main (D:\godotengine\godot\platform\windows\godot_windows.cpp:183)
[6] _main (D:\godotengine\godot\platform\windows\godot_windows.cpp:205)
[7] main (D:\godotengine\godot\platform\windows\godot_windows.cpp:217)
[8] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[9] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================

Unhandled exception at 0x00007FFA3B1B7110 in godot.windows.editor.x86_64.exe: 0xC0000005: Access violation executing location 0x00007FFA3B1B7110.

0x00007FFA3B1B7110 is the value of _instance_bindings[i].free_callback 

### Steps to reproduce

Load a resource from GDExtension godot-cpp, then exit the editor 

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-12-11 10:22
Duplicate of https://github.com/godotengine/godot-cpp/issues/889

**Closed by akien-mga** 2022-12-11 10:22 UTC
