### ISSUE TITLE
Grab focus only works on input nodes.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#15388] opened 2018-01-06 07:04 UTC
**Godot version:**
3.0 beta 2 x64

**OS/device including version:**
windows 10 x64

**Issue description:**
 only control nodes such as buttons, text fields , sliders, etc are able to grab focus. All other control nodes will return false if you do a check.

**Steps to reproduce:**
have multiple control nodes that do not take any input from the user try to gain focus will result in failure. Trying to use any other form of input except a mouse without knowing which control is in focus leads to disaster when say using a game-pad. 

**Minimal reproduction project:**

**Comment by eon-s** [comment] 2018-01-06 16:38
Pressing "tab" to change focus also break all the controls.

**Comment by reduz** [comment] 2018-09-06 16:30
Not a bug. If you want a node to be able to get focus, use the set_focus_mode() function.
Closing.

**Closed by reduz** 2018-09-06 16:30 UTC
Labels: bug, topic:core

**Comment by reduz** [comment] 2018-09-06 16:33
Added a warning, to avoid this from happening again.

**Comment by capnm** [comment] 2018-09-07 00:13
> Added a warning, to avoid this from happening again.

It comes now always after the editor start.
![grab-focos-warning](https://user-images.githubusercontent.com/4047289/45191276-91e3a100-b242-11e8-830f-7aeda0689c6b.png)
