### ISSUE TITLE
ImageLoaderSVG: Couldn't set target on ThorVG canvas.

### ISSUE THREAD

**Issue by Crystalwarrior** [godotengine/godot#72478] opened 2023-01-31 22:26 UTC
### Godot version

4.0.beta16

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1050

### Issue description

Importing SVG's from Kenney.NL fails with the following message:
```
  ImageLoaderSVG: Couldn't set target on ThorVG canvas.
  core/io/image_loader.cpp:101 - Error loading image: res://assets/icons/skull.svg
  editor/editor_file_system.cpp:2004 - Error importing 'res://assets/icons/skull.svg'.
```

### Steps to reproduce

1. Grab icons from Kenney.NL here: https://www.kenney.nl/assets/board-game-icons
2. Try importing an .svg from it
3. The process will fail:
![image](https://user-images.githubusercontent.com/3470436/215897851-d58237cf-5868-4a07-97a2-758e2cababc3.png)

### Minimal reproduction project

N/A

**Comment by fire** [comment] 2023-02-01 06:53
[kenney_boardgameicons.zip](https://github.com/godotengine/godot/files/10554006/kenney_boardgameicons.zip)

![skull](https://user-images.githubusercontent.com/32321/215972305-06647e9f-0959-40d8-9602-87994a3a152e.svg)

@mgrudzinska Here's a test case if you're interested. 

![image](https://user-images.githubusercontent.com/32321/215972409-dc1c66fa-f02c-4264-be3a-d0516220056e.png)

**Comment by mgrudzinska** [comment] 2023-02-01 13:00
@fire thanks for info :)

I see that the problem is that there's no viewbox attrib. We have pr solving this, but it has to be rebase/updated. Sorry for that. I'll take care of that today.

But still these svgs are a bit wired, because they are shifted and only part of the picture is visible - like the skull.svg you sent, that's not the whole skull... is that what you'd expect? I checked some other svg viewers and none of them showed the whole skull.

**Comment by fire** [comment] 2023-02-02 00:36
I confirm that firefox shows the skull offset too.

**Comment by capnm** [comment] 2023-03-08 18:36
:timer_clock: :timer_clock: :timer_clock:
E.g. all the vector files from https://www.kenney.nl/assets/prototype-textures have the same issue.
A quick »emergency« solution is to open the images in Inkscape, press ctr-a,  sh+ctrl+r (resize page to selection) and overwrite the svg...

![grafik](https://user-images.githubusercontent.com/4047289/223804210-4e5a3b0e-e752-474f-b874-a7a61c6ca64c.png)

**Comment by mgrudzinska** [comment] 2023-03-09 01:31
@capnm I'll try to make the pr ready asap - it is after rev and waiting for some changes.

**Comment by mgrudzinska** [comment] 2023-03-10 23:51
https://github.com/thorvg/thorvg/pull/1318

**Comment by capnm** [comment] 2023-03-11 08:24
@mgrudzinska the only OS software I can that can handle such images is Inkscape, it brings from the user perspective correct result, when I use it to recalculate the image _width/height_ .
E.g. your first test-image:
<details><summary>test1.svg</summary>

```svg
<svg width="400" height="200" viewBox="0 0 200 ">
      <linearGradient id="Gradient1" x1="0" x2="30%" y1="0" y2="40" gradientUnits="userSpaceOnUse">
      <stop offset="0%" stop-color="red" />
      <stop offset="50%" stop-color="black" stop-opacity="0" />
      <stop offset="100%" stop-color="green" />
    </linearGradient>

  <path fill="blue" d="M 0 0 h 400 v 400 z" opacity="0.1"/>
  <path fill="green" d="M 0 400  h 400 v -400 z"/>
    <path stroke="none" fill="url(#Gradient1)" d="M0 0 L100 0 100 100 0 100 0 0"/>
    <path fill="none" stroke="#00ff00" stroke-width="1" d="M0 0 L 100 100"/>
</svg>
```
</details>

<details><summary>test1_inkscape.svg</summary>

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="400.35355"
   height="400.35355"
   viewBox="0 0 200 "
   version="1.1"
   id="svg17"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs21" />
  <linearGradient
     id="Gradient1"
     x1="0"
     x2="120.00001"
     y1="0"
     y2="40"
     gradientUnits="userSpaceOnUse">
    <stop
       offset="0%"
       stop-color="red"
       id="stop2" />
    <stop
       offset="50%"
       stop-color="black"
       stop-opacity="0"
       id="stop4" />
    <stop
       offset="100%"
       stop-color="green"
       id="stop6" />
  </linearGradient>
  <path
     fill="#0000ff"
     d="M 0.35355339,0.35355339 H 400.35355 V 400.35355 Z"
     opacity="0.1"
     id="path9" />
  <path
     fill="#008000"
     d="M 0.35355339,400.35355 H 400.35355 V 0.35355339 Z"
     id="path11" />
  <path
     stroke="none"
     fill="url(#Gradient1)"
     d="M 0.35355339,0.35355339 H 100.35355 V 100.35355 H 0.35355339 V 0.35355339"
     id="path13"
     style="fill:url(#Gradient1)" />
  <path
     fill="none"
     stroke="#00ff00"
     stroke-width="1"
     d="M 0.35355339,0.35355339 100.35355,100.35355"
     id="path15" />
</svg>
```
</details>

Perhaps it's worth taking a look at their code:
https://gitlab.com/inkscape/inkscape/-/tree/master/src/svg

![krita-ss](https://user-images.githubusercontent.com/4047289/224473579-d1b8bded-2c68-4484-ba19-a9d3dbb40300.jpg)

**Comment by capnm** [comment] 2023-03-11 18:28
Only the last image from your PR
<details><summary>t8.svg</summary>

```svg
<svg width="0">
      <linearGradient id="Gradient3" x1="0.9" x2="0.1" y1="0" y2="0.5">
      <stop offset="0%" stop-color="red" />
      <stop offset="50%" stop-color="black" stop-opacity="0" />
      <stop offset="100%" stop-color="green" />
    </linearGradient>

  <path fill="yellow" d="M 0 0 h 400 v 400 z"  opacity="0.9"/>
  <path fill="green" d="M 0 400  h 400 v -400 z"/>
    <path stroke="none" fill="url(#Gradient3)" d="M0 0 L100 0 100 100 0 100 0 0"/>
    <path fill="none" stroke="#00ff00" stroke-width="1" d="M0 0 L 100 100"/>
</svg>
```
</details>

shows errors (changing the _width_ > 0 works)

<details><summary>Godot internal errors</summary>

```
ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:103)
ERROR: Error loading image: res://assets/tests/t8.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://assets/tests/t8.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:103)
ERROR: Error loading image: res://assets/tests/t8.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://assets/tests/t8.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
...
```
</details>

Images t1-t7 are ok.

**Comment by mgrudzinska** [comment] 2023-03-13 00:35
@capnm I've updated the pr, but it's still under rev

**Comment by capnm** [comment] 2023-03-13 08:52
@mgrudzinska 
I haven't had a chance to read through the code yet, had only a quick look at the SVG specs and Godot results with the last pr. The spec is, as you said, very css specific. Here, he suggests, missing SVG size attributes should mean _auto_, so the whole image here, Godot now shows only 1x1 px image.

https://docs.google.com/presentation/d/1POUiroOBbLmXYlQKf0pIR8zVkHWH9jRVN-w8A4aNsIk/edit#slide=id.g1e19b0d66_285


ViewBox, I guess width/height too: »A value of zero disables rendering of the element.« In this case the lib gives here a not usable a picture with zero width or height (Godot gives errors). E.g. the linux gnome image viewer shows a transparent picture with the correct size.
     
https://www.w3.org/TR/SVG2/coords.html#ViewBoxAttribute

**Comment by mgrudzinska** [comment] 2023-03-13 22:11
> @mgrudzinska I haven't had a chance to read through the code yet, had only a quick look at the SVG specs and Godot results with the last pr. The spec is, as you said, very css specific. Here, he also suggests, missing SVG size attributes should mean _auto_, so the whole image here, Godot now shows only 1x1 px image.

I missed this, I'll solve this asap and let you know

**Comment by capnm** [comment] 2023-03-14 04:57
Do you know what should be done from the Godot side and/or what the intent is for ThorVG generated image, with _zero svg or viewBox width/height_ attributes? If I'm reading the debugger backtraces correctly, Godot is currently getting an image with a width or height of zero, which results in error. In html/css context, which we don't have here, the intent is to not render the image. I think ThorVG should provide a _transparent area in the image size_ or also as by _auto_ the whole image in this case. :thinking:

**Comment by mgrudzinska** [comment] 2023-03-15 00:44
@capnm I didn't take a look in a godot code.
the problem with incorrect size should be solved in the last commit.
these are two separate cases:
- svgs with ```viewbox="1 2 300 0"``` (height=0) - nothing should be rendered - as I understand this is handled in godot correctly, right?
- svgs with ```width="0"``` or ```height="0"``` - there is a problem?
If so, I'd like to handel the latter in the same way as the former - although it's not exactly the svg standard - I'll consult this with guys, just need to know whether it solves the problem

**Comment by capnm** [comment] 2023-03-15 08:35
> these are two separate cases:
> 
>     * svgs with `viewbox="1 2 300 0"` (height=0) - nothing should be rendered - as I understand this is handled in godot correctly, right?
> 
>     * svgs with `width="0"` or `height="0"` - there is a problem?
>       If so, I'd like to handel the latter in the same way as the former - although it's not exactly the svg standard - I'll consult this with guys, just need to know whether it solves the problem

I'm just considering using Godot in our classes, so I'm looking at the errors now more from a philosophical side :) 

E.g. Gnome image viewer shows by 0's in svg width or height and by  viewbox(0 0 0 0) without svg's width and height - a 1x1 px image.  In other cases, the full sized image. 

I assume that Godot doesn't have access to the image data or the full size values. Guess: he is trying to create a zero size symbol here, giving out lots of internal errors and marking the image as broken. With zeros in the size,  1 px placeholder (+ documentation) could fix the issue... :thinking: 

@fire ?

<details><summary>Screenshots</summary>

![grafik](https://user-images.githubusercontent.com/4047289/225248884-8c047dfc-7b16-4a9d-a01e-93862804ebbc.png)
![Bildschirmfoto von 2023-03-15 05-38-59](https://user-images.githubusercontent.com/4047289/225246240-252ae4a8-b64d-4513-946c-a0edc325f53d.png)

</details>

**Comment by fire** [comment] 2023-03-15 16:10
I think defaulting to a 1x1 image is better usability than fail looping, but I have not thought through the consequences.

**Comment by capnm** [comment] 2023-03-15 17:26
The other option could be to remove everything from the SVG tag (this case works now, @mgrudzinska  is almost there!) and render an equally sized transparent image (this would represent something similar to the "do not render" in the SVG standard) or the provided image (optionally?).

**Comment by mgrudzinska** [comment] 2023-03-16 00:37
I'm quite sure, that for the t3.svg (```viewBox="0 0 200 0"```) for the latest version of the corresponding pr (after changes pushed yesterday) you should get ```ERR_INVALID_DATA``` from the ```picture->load``` api. 
Let us discuss whether it's the best approach. we could render an empty scene and then both apis result in success. 

for t8.svg (```width="0"```) setting the canvas target won't return success, but you know the width and height values so you can set whatever values you want if some of them is zero. both as before - let us discuss this, because maybe we should handle this case exactly like the above...

**Comment by capnm** [comment] 2023-03-16 04:59
@fire You wrote the bindings, please correct me if I got it wrong. The debugger has troubles stepping in the code (godot changes thorvg's pointers to internal api or multithreading issues).

1 Godot looks at the file extensions, loads the svg data itself and knows nothing else of the contents.
2 Sends it to thorvg's sw-renderer.
3 Gets the image data, width and height.
4 Attempts to change the color in the svg file and sends it to thorvg to create a file icon. 

In cases the svg file contais swg's or viewBox's width or height (or both) 0, it gets zero width or height (or no success?) from the thorvg api. At this point we don't know the image size. The question is what to do next.

**Comment by fire** [comment] 2023-03-16 05:17
Is zero size a failure case of import. Its technically valid to zero width height image but I thought a zero area image is invalid.

**Comment by capnm** [comment] 2023-03-16 05:33
In web context it's used to currently hide or not render the image.

**Comment by capnm** [comment] 2023-03-16 13:22
@mgrudzinska quick test for latest godot tip + pr1318
[godot_pr1318_diff.zip](https://github.com/godotengine/godot/files/10990870/godot_pr1318_diff.zip)

Issues: svg without viewport/viewbox ,  <svg width="0"> (t8) and viewbox without viewport that contains 0s –
get now marked as broken. Errors:

```
ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:103)
ERROR: Error loading image: res://prototype_textures_orig_vec/texture_02.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://prototype_textures_orig_vec/texture_02.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
ERROR: Error loading image: res://prototype_textures_orig_vec/texture_01.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://prototype_textures_orig_vec/texture_01.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
```

<details><summary>Screenshots</summary>

![230316](https://user-images.githubusercontent.com/4047289/225629862-dee27fd7-0c5a-42cd-9b25-5f8b755d8ab6.png)

[vp_vb_tests.zip](https://github.com/godotengine/godot/files/10991257/vp_vb_tests.zip)

</details>

**Comment by mgrudzinska** [comment] 2023-03-16 16:09
omg it's a huge diff :D but I don't see what did you change in godot in image_loader_svg.cpp. could you share?

**Comment by mgrudzinska** [comment] 2023-03-16 16:54
I'll be available in a few hours and i run it myself

**Comment by capnm** [comment] 2023-03-16 17:16
You were very hardworking :D _image_loader_svg.cpp_ hasn't been changed since 2022-12. You can clone the godot tip and run _git apply pr1318.diff_

**Comment by mgrudzinska** [comment] 2023-03-17 00:12
1. so, the viewbox error is now solved in [#1318](https://github.com/thorvg/thorvg/pull/1318)
2. all svgs with the width or height value set to zero - in my opinion you have to handle the result in the image_loader_svg.cpp file. For now you'll get an error msg:
ImageLoaderSVG: Couldn't set target on ThorVG canvas.
because width and/or height are zero. you can change it to any value you want, like instead of zero use 1. it will be the canvas, but still nothing will be drawn, so maybe this is the sollution

I didn;t manage to install everything to run the code on my computer... butt the above should be helpfull

**Comment by capnm** [comment] 2023-03-17 05:08
Here are the docs what you need for any OS, may help: https://docs.godotengine.org/en/latest/contributing/development/compiling/index.html I can take a look at it over the weekend.

**Comment by capnm** [comment] 2023-03-17 18:51
@mgrudzinska 
After https://github.com/godotengine/godot/pull/75034 the svg import
is now error free for all images we get with a 0 size! 

The only small problem I can see is the case without viewport and viewbox, all images width/height is 1 px larger than it should be. Maybe some float rounding problems...
 
<details><summary>Details</summary>

```svg
<svg>
  <linearGradient id="Gradient1" x1="0" x2="30%" y1="0" y2="40" gradientUnits="userSpaceOnUse">
    <stop offset="0%" stop-color="red" />
    <stop offset="50%" stop-color="black" stop-opacity="0" />
    <stop offset="100%" stop-color="green" />
  </linearGradient>

  <path fill="blue" d="M 0 0 h 400 v 400 z" opacity="0.3"/>
  <path fill="green" d="M 0 400  h 400 v -400 z"/>
  <path stroke="none" fill="url(#Gradient1)" d="M0 0 L100 0 100 100 0 100 0 0"/>
  <path fill="none" stroke="#00ff00" stroke-width="1" d="M0 0 L 100 100"/>
</svg>
```
![grafik](https://user-images.githubusercontent.com/4047289/225991136-c494af50-d4c3-4d69-9062-dd704b0ad151.png)
https://github.com/capnm/godot4/tree/update_thorvg_pr1318
</details>

**Comment by mgrudzinska** [comment] 2023-03-20 23:58
@capnm  good catch! I noticed this but I wanted to solve this after we agree with https://github.com/thorvg/thorvg/pull/1318


> After https://github.com/godotengine/godot/pull/75034 the svg import is now error free for all images we get with a 0 size!

I hope that I've misunderstood - all of the images have a size equal 0? even if it shouldn;t be?

**Comment by capnm** [comment] 2023-03-21 03:06
@mgrudzinska 
> I hope that I've misunderstood - all of the images have a size equal 0? even if it shouldn;t be?

Most images show a picture :+1:  I didn't examine if they are correct cropped. The 0 size is no longer a bug after this patch. It renders 1 pixel images in this case. 
<details><summary>From all test images, I posted:</summary>

The 0 size cases are:
\<svg width="0"> (the Gnome Image Viewer: whole picture) -> t8.svg
\<svg viewBox="0 0 0 200"> (giv: 1 pixel)
\<svg viewBox="0 0 200 0"> (giv: 1 pixel)
\<svg viewBox="0 0 0 0"> (giv: 1 pixel)
\<svg width="0" height="0" viewBox="0 0 200 200"> (giv: 1 pixel)
\<svg width="0" height="200" viewBox="0 0 20 20"> (giv: 1 pixel)
same:
\<svg width="0" height="200" viewBox="0 0 200 200">
\<svg width="200" height="0" viewBox="0 0 20 20">

This renders a transparent 200x200 sized images (giv: 200x200 cropped picture):
\<svg width="200" height="200" viewBox="0 0 0 0">
\<svg width="200" height="200" viewBox="0 0 0 200">
\<svg width="200" height="200" viewBox="0 0 200 0">

</details

**Comment by mgrudzinska** [comment] 2023-03-21 18:37
great, so I'll take care now of this one extra pixel

**Comment by mgrudzinska** [comment] 2023-03-21 23:25
https://github.com/thorvg/thorvg/pull/1333 should solve the extra pixel

but still we have https://github.com/thorvg/thorvg/issues/1331 and https://github.com/thorvg/thorvg/issues/1332 - both connected with svg without viewbox and width/height info. the problem described in the latter was mentioned in this issue.

**Comment by mgrudzinska** [comment] 2023-03-21 23:41
@capnm please take a look:
https://github.com/thorvg/thorvg/issues/1332#issuecomment-1478728411
do you have many such svgs that don;t have a viewbox/viewport info and are shifted so only a part of them is visible (like shield and skull on the very top of this issue)? I think that they are incorrect, so they should be cut and only partially visible, but I may be wrong. 
could you please comment?

**Comment by mgrudzinska** [comment] 2023-04-03 10:41
@capnm please double check and let us know whether there is still some issue here

**Comment by capnm** [comment] 2023-04-03 12:26
@mgrudzinska everything related to the image size and empty viewport/viewbox seems to be ok now. I have not yet received a response to #75034, I hope that one day it will be fixed too :)

**Comment by mgrudzinska** [comment] 2023-04-17 11:47
@capnm @fire guys if there is still some issue regarding ThorVG please let me know. from my point of view it is solved already.

**Comment by capnm** [comment] 2023-04-17 15:15
@mgrudzinska  Currently I get ~90% crash by reading svg images on current godot \+ tvg tip
https://github.com/thorvg/thorvg/issues/1370
The tests I looked at before were ok.

**Comment by capnm** [comment] 2023-04-26 23:49
@mgrudzinska update:
Both current godot 26fb911f79d7b16c46ca476923fe1f32ab5d27ed and thorvg 65116b87ada27689d79fa4db241cf777f3b268c5 github tip work together (the crash/dealock has been fixed). If the changes are in your next release, I don't see any issues.

**Closed** 2023-05-12 08:18 UTC
Labels: bug, topic:thirdparty, topic:import
