### ISSUE TITLE
Signal method does not get generated when connecting a signal to a method in script

### ISSUE THREAD

**Issue by georgikoemdzhiev** [godotengine/godot#21695] opened 2018-09-02 14:01 UTC
**Godot version:**
3.0.6 [C#]

**OS/device including version:**
N/A

**Issue description:**
When Connecting a signal to a method, the method does not get created in the script.

**Steps to reproduce:**
1. Click on a Node and create a C# script
2. Open the "Signals" section and select a signal and then press Connect x2 (leave the default name of the method)
3. Inspect the script. There should be a method with the default signal name but it it is nowhere to be found

**Minimal reproduction project:**

[Godge the Creeps.zip](https://github.com/godotengine/godot/files/2343411/Godge.the.Creeps.zip)

**Comment by Calinou** [comment] 2020-02-22 22:10
Duplicate of #23208.

**Closed by Calinou** 2020-02-22 22:10 UTC
Labels: bug, topic:mono
