### ISSUE TITLE
Shrinking in play mode

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#34030] opened 2019-11-30 19:51 UTC
**Godot version:**
3.1.2.stable.official
**OS/device including version:**
Linux Mint on a Mac Mini 2012
**Issue description:**

**Steps to reproduce:**
Place buttons in a scene, play it, then resize it to small and size it back

**Minimal reproduction project:**
![Hnet-image](https://user-images.githubusercontent.com/41384991/69905381-a4368700-1380-11ea-9b55-1f9f38da25ba.gif)

**Comment by Calinou** [comment] 2021-05-06 17:39
Duplicate of https://github.com/godotengine/godot/issues/37242 (same cause).

**Closed by Calinou** 2021-05-06 17:39 UTC
Labels: bug, topic:core
