### ISSUE TITLE
Android crash on scene loading with relative path

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#4125] opened 2016-03-22 21:45 UTC
**Operating system or device:**
Android 4.0.3 ;  LG P700

**Issue description** (what happened, and what was expected):
When some scenes are loaded by script, the Android app crashes on startup. The phone must be rebooted. 
- If you run only the scene it works nice also on Android. 
- If you instance the scene by editor the app works nice too.
- It crashes only if the scene is loaded in a script.

**Steps to reproduce:**
- Click on the example project link. (wait a minute hubiC seems slow on my Firefox)
- Check the zip file and download it. The poisoned scene is "PausePopup2.tscn"
- Connect an Android device.
- Run the project on Android.
- Epileptic persons should switchoff the device immediately.

**Link to minimal example project** (optional but very welcome):

 http://ovh.to/KsqY4Xb

**Comment by DriNeo** [comment] 2016-03-24 11:06
Android really needs paths who begin with " res:// " otherwise the loading fails.

It's my bad but I leave to you the choice to close this issue. Maybe the file paths format need consistency between PC and Android.

**Comment by neikeq** [comment] 2016-03-24 13:17
I would open a new issue and close this one, or include you last message in the **Issue description** (I didn't port to Android yet, so I can't give an opinion).

**Comment by DriNeo** [comment] 2016-03-24 17:25
Maybe you can rename the issue.

**Comment by reduz** [comment] 2016-06-21 01:29
i can't get the sample project, would appreciate if you can post it again

**Comment by Faless** [comment] 2017-02-15 13:41
You **should always use `res://`** to access project **resources** as stated by [the official documentation](http://docs.godotengine.org/en/stable/tutorials/step_by_step/filesystem.html#resource-path).

**Relative paths** eg. `load("test.gd")` or `load("scene/test.tscn")` actually **works** (just tested in 2.1 branch).

Access to file system via **absolute paths** (`C:\` and `/`) are there for platform that allows it (**mainly PC and Servers**) and **discouraged** unless you really need it.

For **writable** File System (eg. preferences, temp files, and so on) **`user://` should be used** (I think you will need the `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permission on android but you can double check).

I think this can be closed.

**Comment by Faless** [comment] 2017-02-15 13:46
> PC allows simple " / " to represent the root project, but Android need "res://" otherwise the app crashes and the O.S freezes on some devices ( or every devices and I'm the only one to write paths with " / " ?)

This was actually fixed by #7172 and previous long PR/Issue history ( :crying_cat_face: ) and now correctly points to the root of the file system.

**Comment by bojidar-bg** [comment] 2017-02-15 13:51
Yeah, closing as yet one of those misapplications of the root filesystem path.... Also, duplicate of #4280

**Closed by bojidar-bg** 2017-02-15 13:51 UTC
Labels: bug, platform:android, topic:core
