### ISSUE TITLE
Saving a scene unfolds all nodes in all open scene tabs in which it has been instanced

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#29975] opened 2019-06-22 08:19 UTC
**Godot version:**
3.2-dev 2f63811c9

**OS/device including version:**
Windows 10 x64

**Issue description:**
Upon saving a scene, all open scene tabs that contain it as an instance somewhere in the tree (including within other instances) will have all of its nodes unfolded when switching to their tabs. The folding state isn't actually saved to disk, so you can restore it by closing and re-opening the affected scenes.

**Steps to reproduce:**
1. Create two scenes named "SceneA" and "SceneB"
2. Instance "SceneB" in "SceneA"
3. Fold the root node of "SceneA"
4. Switch to "SceneB" and save
5. Switch back to "SceneA"; the root node will be unfolded

**Comment by Xrayez** [comment] 2019-06-25 11:27
I encounter this issue quite a lot, it starts to be annoying especially with somewhat deep hierarchy of instanced scenes.

I can reproduce this a bit differently but the result is the same eventually, namely:
1. Save scene and close it in order save folding state (should save it anyway, another bug?)
2. Open it again, see folding state remained.
3. Modify one of the instanced scenes separately (just resave it).
4. Return back to original scene and see all nodes unfolded.

So the difference is that I don't have to run the scene at all.

**Comment by homer666** [comment] 2019-08-27 03:02
At a glance it seems somewhat related to #3395

**Comment by Xrayez** [comment] 2019-09-06 16:37
Found some commits related for this issue (from recent to oldest):

* https://github.com/godotengine/godot/commit/e647342140d8eb960b2a72d83b4b86e43aef4fc7 - quite a bunch of changes by @reduz here, likely regression.
* https://github.com/godotengine/godot/commit/4b85ddabdaf8314238cfecb1fa74ccb08f5d67d3
* https://github.com/godotengine/godot/commit/5065e46381814746eeddb4c44b5eb1540b0331f8

**Comment by KoBeWi** [comment] 2019-09-09 01:29
Sooo... this annoyed me a lot recently and I decided to look into fixing this.

Node class has a `data.display_folded` property, which determines whether it is folded. It is modified _only_ inside `set_display_folded()`.

Then there's `is_displayed_folded()` which returns that property. The lines that make nodes in tree (un)folded on scene load/switch are these:
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/scene_tree_editor.cpp#L202-L204
For whatever reason, following the reproduction steps, `is_displayed_folded()` in the line above will return false, even though `set_display_folded()` is never called before the folding breaks. I'm lost ;_;

Unless I missed something in the investigation, `display_folded` can only be set to false in a constructor in this case. But nodes aren't recreated on scene switch AFAIK.

**Comment by Xrayez** [comment] 2019-09-09 08:39
The fact that saving scenes is not deterministic #30538 which could mess up node indexing #28309/#23766 in `tscn` files may result in broken folding state saved in config file per scene.

But it might be not the case because the folding state is saved based on actual node paths:

```ini
[folding]

node_unfolds=[  ]
resource_unfolds=[  ]
nodes_folded=[ NodePath("node") ]
```

> The folding state isn't actually saved to disk, so you can restore it by closing and re-opening the affected scenes.

So yeah, unless you manually save a scene.

**Comment by KoBeWi** [comment] 2019-09-09 08:52
> The fact that saving scenes is not deterministic #30538/#23766 which could mess up node indexing #28309 in tscn files may result in broken folding state saved in config file per scene.

But this would only affect anything if the folding was loaded from the file, which isn't the case here. This code isn't executed between save and tab change:
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/editor_folding.cpp#L210-L212

**Closed** 2019-09-23 08:32 UTC
Labels: bug, topic:editor, usability

**Comment by VideoGirlAi** [comment] 2024-05-03 02:47
I don't know if it's OK to revive this issue, but I want to report it's happening again in Godot 4.2.2. I fold nodes, switch a scene, save that scene, then revert to the previous scene, and all nodes are unfolded.

**Comment by akien-mga** [comment] 2024-05-03 06:40
Please open a new issue, this was fixed 5 years ago. What you experience is a different / new bug.
