### ISSUE TITLE
Arrays in sub-class not work!!!

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#2015] opened 2015-05-31 14:16 UTC
I have a subclass with arrays, and when it start the reference to arrays is missing!
In some cases I can use push_back but, out of functions arrays appears null or empty!
I using Godot 1.1 build with last code at 31/05
![captura de tela_2015-05-31_08-37-14](https://cloud.githubusercontent.com/assets/85936/7902182/857a3c18-0786-11e5-9196-b1b427c2f729.png)

**Comment by reduz** [comment] 2015-05-31 15:04
what happens if you do something like
var layers = []
instead?

**Comment by marcosbitetti** [comment] 2015-05-31 20:00
The problem remains :(

**Comment by marcosbitetti** [comment] 2015-06-10 01:39
Well, I not solve other solution at moment. I initialize arrays outside de object instancing and set it before. The most insane is at this moment it occurs just only arrays.
code: http://pastebin.com/3Sg6YHDv

**Comment by reduz** [comment] 2016-01-03 23:41
This bug is because by default Array() is not shared, this will change eventually in 2.1. However, using [] instead of array should work.

**Comment by reduz** [comment] 2016-01-03 23:42
just get used to use [] instead of Array(), or you will constantly face whit issue

**Comment by akien-mga** [comment] 2016-03-30 09:44
Closing as a duplicate of #4114 which has some more input about all the weird behaviours one can face when using Array().

**Closed by akien-mga** 2016-03-30 09:44 UTC
Labels: bug, topic:gdscript
