### ISSUE TITLE
godot aapt2 compile and aapt2 link

### ISSUE THREAD

**Issue by miqueias9889** [godotengine/godot#55915] opened 2021-12-13 20:54 UTC
### Godot version

3.3 STABLE

### System information

LINUX

### Issue description

godot aapt2 compile and aapt2 link

I'm trying to generate the res folder from godotgame.aab using aapt2 compile and aapt2 link but at the time I run error, so please tell me how godot generates the res folder using aapt2 compile and aapt2 link, how can I use the lib godot godot-lib.release.aar to generate the aab correctly, with all the res/ that org.godotengine.godot asks when run for example my ta failing in org.godotengine.godot.R$layout ??

### Steps to reproduce

Generate aab without gradle using android cmdline, using:

aapt2 compile

aapt2 link

javac

d8

bundle-all.jar

**Comment by Calinou** [comment] 2021-12-13 21:06
Duplicate of https://github.com/godotengine/godot/issues/55738. Please do not create additional issues if you don't get an answer quickly – it's likely that nobody knows the answer. Also, exporting to Android from a 32-bit OS is no longer officially supported by Google.

**Closed by Calinou** 2021-12-13 21:06 UTC
