### ISSUE TITLE
hovering collision from tilemap

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19956] opened 2018-07-04 08:56 UTC
Godot version: 3.0.4 stable
OS/device including version: Win 7

Issue description:

Strange hovering collision:
![hovering col](https://user-images.githubusercontent.com/40721994/42266908-f21ca9d4-7f77-11e8-82dc-1b55a75d150b.jpg)

The Godot face should have contact the the yellow ground. I'm not sure if this is a bug or user error but if it's not a bug and user error applying collisions needs to become easier. 

I've tried encasing the whole tile: 
![col1](https://user-images.githubusercontent.com/40721994/42267105-6d85b5ac-7f78-11e8-82e4-b9ddbc961c1d.jpg)

But I've noticed that there is a small gap so I thought that maybe that is the problem and changed it:
![col2](https://user-images.githubusercontent.com/40721994/42267128-82518858-7f78-11e8-8ef0-712421783ddd.jpg)

Both result in the same hovering problem. 

Steps to reproduce:
Create a tilemap from a tileset

Minimal reproduction project:
[Farty Flies2.zip](https://github.com/godotengine/godot/files/2162489/Farty.Flies2.zip)

**Comment by groud** [comment] 2018-07-04 15:50
You should not scale collision shapes. Reset the scale to (1,1), then use the single handles to change the box size. Not the ones with the orange rectangle.

**Comment by BrahRah** [comment] 2018-07-05 18:04
I've reset the scale to to 1,1 but the problem is still there. I'll try to recreate the whole tileset and not touch the outside ones.

**Comment by groud** [comment] 2018-07-05 19:33
Confirmed, I was able to reproduce the bug.
It seems that the tileset considers the collision shape without whether or not the sprite is centered or not.

**Comment by bojidar-bg** [comment] 2018-07-20 12:42
Can you confirm it on master/3.1?

**Comment by MarianoGnu** [comment] 2018-08-26 20:00
I have seen something similar in my friend's setup, he had scalled static bodies and collision shapes on the "tileset setup scene", make sure your static bodies and collision shapes have (1, 1) scale and merge the tileset again.

**Comment by DaniilDigtyar** [comment] 2018-11-21 20:44
![hoveringcollision](https://user-images.githubusercontent.com/32536694/48867215-c690de80-edd5-11e8-981f-d75732f0db20.gif)

Godot version: 3.0.6 stable
OS/device including version: Win 7

Seem like I have the same bug, in the TileSet all the nodes had been reset to scale (1,1) and offset 0.

**Comment by DaniilDigtyar** [comment] 2018-11-22 16:53
@bojidar-bg All the StaticBody2D nodes are on the correspondent sprite.
If you put the Knight character in the TileSet scene seems to collide perfectly.

![tilesettest](https://user-images.githubusercontent.com/32536694/48915567-6bb3c180-ee7f-11e8-8363-6ed8a27fc9a5.gif)

**Comment by MarianoGnu** [comment] 2018-11-22 17:01
Did you check if this still happens after converting scene to tileset again with Godot 3.1 alpha2? I'm almost sure this is caused by how the converter handles the pivot cell alignment used to be relative to cell's topleft corner, for some reason someone changed it to align rectangles instead, and this is more difficult to manage imho.

**Comment by bojidar-bg** [comment] 2018-11-22 17:47
@DaniilDigtyar the gif shows that they all have a Transform value 25,25; it should be 0,0.

**Comment by DaniilDigtyar** [comment] 2018-11-23 16:29
![capture](https://user-images.githubusercontent.com/32536694/48953177-38d40100-ef45-11e8-8e14-f5b7576ef7eb.PNG)
It works!
Like @bojidar-bg said all the child nodes of every Sprite must have the Transform value 0,0, if it's different the child collision node, change its location based of the parent node.
Maybe the same happened to @BrahRah

**Comment by bojidar-bg** [comment] 2018-12-12 12:50
I can't confirm this issue with the sample project given by the OP on 3.1, assuming fixed by #19343.

If someone can confirm this on **3.1**, this issue might be reopened.

**Closed by bojidar-bg** 2018-12-12 12:50 UTC
Labels: bug, confirmed, topic:core
