### ISSUE TITLE
Animation player play_backwards doesn't work from 4.2.2 upwards

### ISSUE THREAD

**Issue by DaanMuller** [godotengine/godot#90964] opened 2024-04-20 21:43 UTC
### Tested versions

4.2.2 stable, 4.3 dev versions

### System information

OS X 13.6.2

### Issue description

play_backwards doesn't work anymore for the animation player in 2d, haven't tested 3d, from version 4.2.2 onwards

### Steps to reproduce

just try to play an animation in animationplayer with play_backwards, it doesn't play the animation.

### Minimal reproduction project (MRP)

n.a.

**Comment by Nazarwadim** [comment] 2024-04-21 10:05
On my version `4.3 dev5`, it works in both 2D and 3D. Could you describe your case in more detail?

**Comment by TokageItLab** [comment] 2024-04-21 11:05
I don't know what to say because there is no MRP, if the issue relying on UpdateModeDiscrete, it has been resolved in 4.3.

**Comment by TokageItLab** [comment] 2024-04-21 11:10
In any case, the current version cannot reproduce the issue, so close it.

If you have information that can be added, send new Issue with **Minimal reproduction project**. MRP is must and should not be n.a.

**Closed by TokageItLab** 2024-04-21 11:10 UTC
Labels: bug, needs testing, regression, topic:animation

**Comment by GOKORURI007** [comment] 2024-05-10 19:13
I guess you forgot to wait for the animation to finish before making the object invisible.

Here is an example:
```
    $AnimationPlayer.play_backwards("ani")
    await $AnimationPlayer.animation_finished     # This line is indispensable
    $SettingPanel.visible = !$SettingPanel.visible
```

**Comment by t0mtee** [comment] 2024-06-14 16:43
I actually am having this issue. I hope this constitutes as an MRP: [MRP.zip](https://github.com/user-attachments/files/15841113/MRP.zip)
When you let the platform fully rise and then jump off it the animation doesn't play backwards as it should.

If this project isn't valid for whatever reason I'm happy to try and recreate it on a completely new project - this is just a project I have going with some personal information taken out.

**Comment by gulagkulak** [comment] 2024-09-09 09:47
I'm having the same issue. Built a small platformer with 4.1/4.2 last year and had the character walking backwards with play_backwards("walking") just fine. Brought the project into 4.3 today and play_backwards("walking") doesn't work anymore. It's just stuck on the first frame for some reason.

**Comment by AThousandShips** [comment] 2024-09-09 10:50
Please open a new issue with clear reproduction steps and an MRP as instructed above

**Comment by gulagkulak** [comment] 2024-09-09 11:44
MRP was provided by @t0mtee in the previous comment.

**Comment by AThousandShips** [comment] 2024-09-09 11:49
Then please add that to a new issue
