### ISSUE TITLE
Control get_focus_neighbor works only with manually assigned neighbours

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#77729] opened 2023-06-01 12:54 UTC
### Godot version

4.0.3

### System information

Windows 10, all renderers, Nvidia GTX2070

### Issue description

I'm trying to add a common game feature - continuous button traverse (focusing on the following UI in the direction). Every way possible I hit a brick wall to realize it.
With a keyboard, it "works" by default, thanks to an event echo. It is too fast and not usable. For a gamepad, it doesn't happen.

The last solution was to use the `get_viewport().gui_focus_changed.connect(gui_focus_changed)` signal to receive the focused Control node and change focus to its neighbor. Except it doesn't work automatically as it would with built-in UI actions, because there is no way to get a neighbor of a side without manually going over EVERY control to assign neighbors.

`Control.get_focus_neighbour(side: Side)` should give the same neighbor that would be focused automatically using UI actions.
Or at least give Control a method to focus on a neighbor to the side if there is any.
 

### Steps to reproduce

The first solution was to remove "ui_right", "ui_left", "ui_down" and "ui_up" events from the input map to trigger actions from a code. Everything would be fine if `Input.action_press("ui_right")` worked in full extension instead of just `Input.is_action_pressed()` and `Input.is_action_just_pressed`.

Workaround to that would be to add arbitrary events to UI actions and trigger them with `Input.parse_input_event()`. But then I have to pray that a player won't trigger them.

### Minimal reproduction project

.

**Comment by Calinou** [comment] 2023-06-01 12:56
- Duplicate of https://github.com/godotengine/godot-proposals/issues/6690.

**Closed by Calinou** 2023-06-01 12:56 UTC
