### ISSUE TITLE
OpenSimplexNoise causes lag and errors

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#53854] opened 2021-10-15 18:08 UTC
### Godot version

4.0.dev

### System information

Windows 10, GTX 1050 ti

### Issue description

If I try to set a noise texture onto something in the 3d viewport, it cause a lot of errors and lags the engine.

Here's some errors:
  Set: 2 Binding: 0 Type: StorageBuffer Length: 0
  Set: 3 Binding: 0 Type: UniformBuffer Length: 128
  Set: 3 Binding: 1 Type: Texture Length: 1
  Set: 3 Binding: 2 Type: Texture Length: 1
  Set: 3 Binding: 3 Type: Texture Length: 1
  Set: 3 Binding: 4 Type: Texture Length: 1
  Uniforms were never supplied for set (3) a

### Steps to reproduce

Create a new meshinstance or CSG shape, add a standardmaterial 3d, then use a noise texture for albedo, normal map etc., the material will not show in the viewport, and the engine will lag, and many errors will be printed. The lag only occurs after you select "opensimplexnoise."

**Comment by Calinou** [comment] 2021-10-15 23:44
Duplicate of https://github.com/godotengine/godot/issues/51361.

**Closed by Calinou** 2021-10-15 23:44 UTC
Labels: bug, topic:rendering
