### ISSUE TITLE
crash when creating CSGBox3D

### ISSUE THREAD

**Issue by dwoodruffsf** [godotengine/godot#61002] opened 2022-05-13 14:33 UTC
### Godot version

v4.0.alpha.custom_build.2f47a0747

### System information

Windows 11, Vulkan, GeForce RTX 3060 Laptop

### Issue description

Crash occurs when creating a CSGBox3D node in a 3D scene. I tested a CSGSphere3D and found it also to crash. Sorry if CSG functionality just isn't implemented yet in 4.0. This was a local build compiled in master branch with `scons p=windows target=release_debug`. 

```
C:\dev\godot\godot>
Godot Engine v4.0.alpha.custom_build.2f47a0747 - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1280620204672
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:156)
Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - GeForce RTX 3060 Laptop GPU

Editing project: C:/dev/godot/examples/test_4.0 (C:::dev::godot::examples::test_4.0)

Godot Engine v4.0.alpha.custom_build.2f47a0747 - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1847317704496
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:156)
Vulkan API 1.2.162 - Using Vulkan Device #0: NVIDIA - GeForce RTX 3060 Laptop GPU

WARNING: FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:92)
ERROR: Index p_index = 1 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   at: VectorWriteProxy<class Variant>::operator [] (C:\dev\godot\godot\core/templates/vector.h:52)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (2f47a0747cd0ab0c823dee831167d168ec844f11)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Array::operator[] (C:\dev\godot\godot\core\variant\array.cpp:80)
[1] Array::operator[] (C:\dev\godot\godot\core\variant\array.cpp:80)
[2] CSGShape3DGizmoPlugin::redraw (C:\dev\godot\godot\modules\csg\editor\csg_gizmos.cpp:352)
[3] EditorNode3DGizmo::redraw (C:\dev\godot\godot\editor\plugins\node_3d_editor_gizmos.cpp:118)
[4] Node3D::add_gizmo (C:\dev\godot\godot\scene\3d\node_3d.cpp:472)
[5] Node3DEditor::_request_gizmo (C:\dev\godot\godot\editor\plugins\node_3d_editor_plugin.cpp:7116)
[6] MethodBindT<Node3DEditor,Object *>::call (C:\dev\godot\godot\core\object\method_bind.h:332)
[7] Object::callp (C:\dev\godot\godot\core\object\object.cpp:838)
[8] SceneTree::call_group_flagsp (C:\dev\godot\godot\scene\main\scene_tree.cpp:273)
[9] SceneTree::call_group_flags<Node3D *> (C:\dev\godot\godot\scene\main\scene_tree.h:260)
[10] Node3D::update_gizmos (C:\dev\godot\godot\scene\3d\node_3d.cpp:422)
[11] Node3DEditor::edit (C:\dev\godot\godot\editor\plugins\node_3d_editor_plugin.cpp:5480)
[12] EditorNode::_edit_current (C:\dev\godot\godot\editor\editor_node.cpp:2303)
[13] EditorNode::push_item (C:\dev\godot\godot\editor\editor_node.cpp:2122)
[14] SceneTreeDock::_push_item (C:\dev\godot\godot\editor\scene_tree_dock.cpp:1373)
[15] SceneTreeDock::_do_create (C:\dev\godot\godot\editor\scene_tree_dock.cpp:2190)
[16] SceneTreeDock::_create (C:\dev\godot\godot\editor\scene_tree_dock.cpp:2304)
[17] Callable::call (C:\dev\godot\godot\core\variant\callable.cpp:51)
[18] Object::emit_signalp (C:\dev\godot\godot\core\object\object.cpp:1120)
[19] CreateDialog::_confirmed (C:\dev\godot\godot\editor\create_dialog.cpp:396)
[20] Callable::call (C:\dev\godot\godot\core\variant\callable.cpp:51)
[21] Object::emit_signalp (C:\dev\godot\godot\core\object\object.cpp:1120)
[22] Object::emit_signal<> (C:\dev\godot\godot\core\object\object.h:773)
[23] Tree::gui_input (C:\dev\godot\godot\scene\gui\tree.cpp:3454)
[24] Control::_call_gui_input (C:\dev\godot\godot\scene\gui\control.cpp:942)
[25] Viewport::_gui_call_input (C:\dev\godot\godot\scene\main\viewport.cpp:1304)
[26] Viewport::_gui_input_event (C:\dev\godot\godot\scene\main\viewport.cpp:1534)
[27] Viewport::push_input (C:\dev\godot\godot\scene\main\viewport.cpp:2719)
[28] Window::_window_input (C:\dev\godot\godot\scene\main\window.cpp:974)
[29] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\dev\godot\godot\core\object\callable_method_pointer.h:104)
[30] Callable::call (C:\dev\godot\godot\core\variant\callable.cpp:51)
[31] DisplayServerWindows::_dispatch_input_event (C:\dev\godot\godot\platform\windows\display_server_windows.cpp:2068)
[32] Input::_parse_input_event_impl (C:\dev\godot\godot\core\input\input.cpp:658)
[33] Input::flush_buffered_events (C:\dev\godot\godot\core\input\input.cpp:884)
[34] DisplayServerWindows::process_events (C:\dev\godot\godot\platform\windows\display_server_windows.cpp:1781)
[35] OS_Windows::run (C:\dev\godot\godot\platform\windows\os_windows.cpp:748)
[36] widechar_main (C:\dev\godot\godot\platform\windows\godot_windows.cpp:175)
[37] _main (C:\dev\godot\godot\platform\windows\godot_windows.cpp:199)
[38] main (C:\dev\godot\godot\platform\windows\godot_windows.cpp:211)
[39] __scrt_common_main_seh (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[40] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Open new Godot project. 
2. Create a 3D Scene as the Root Node
3. right-click root node and select "Add Child"
4. Double-click on `CSGBox3D` node option. 
5. Observe crash in console window.

**Comment by Zireael07** [comment] 2022-05-13 15:05
dupe of #60936 (one of the first results if you search for CSGBox3D, please search before posting issues)

**Closed** 2022-05-13 16:03 UTC
