### ISSUE TITLE
Shadows on Sprite3D with billboarding disappear when close to a light source

### ISSUE THREAD

**Issue by robbyhunt** [godotengine/godot#58004] opened 2022-02-12 09:13 UTC
### Godot version

3.4.2.stable

### System information

Windows 10, OSX 11.3.1

### Issue description

There seems to be a cube around light sources where shadows on billboarded Sprite3Ds disappear:
![bug1](https://user-images.githubusercontent.com/32852473/153705331-60c86ec9-b34b-4ce1-bbcd-432692bee409.gif)

After some experimenting of my own, shadows work as expected without billboarding enabled, but simply rotating the sprite with code isn't a fix since this creates flat shadows from the sides rather than the fake 3d sort of shadows billboards produce.

Another example in a more complex scene:
![bug2](https://user-images.githubusercontent.com/32852473/153705344-906e0894-6b8b-4306-9c9d-9d89a63ac167.gif)

### Steps to reproduce

I've recreated the issue in a new project with just an OmniLight and Sprite3D to make sure it isn't something with my specific scene/environment. You can see any node variables [here](https://imgur.com/a/KJupWHx)

### Minimal reproduction project

[Sprite3DShadowBug.zip](https://github.com/godotengine/godot/files/8053110/Sprite3DShadowBug.zip)

**Comment by robbyhunt** [comment] 2022-02-12 13:56
After some further testing I believe this is an issue with billboarding on more than just Sprite3D nodes. I've replicated the issue with a quad mesh instance as well so far.

**Comment by clayjohn** [comment] 2022-11-23 02:39
Duplicate of https://github.com/godotengine/godot/issues/41420

Closing this so we can track the issue in one place

**Closed by clayjohn** 2022-11-23 02:39 UTC
Labels: bug, topic:rendering, topic:3d
