### ISSUE TITLE
Shader transparency problem

### ISSUE THREAD

**Issue by 451507056** [godotengine/godot#79648] opened 2023-07-19 05:20 UTC
### Godot version

4.0.3.stable and 4.1.1.stable

### System information

windows10，gtx1050ti

### Issue description

I encountered this transparency issue when using shader 4.0.3, my shader was fine in 3.5.1, this also happened in 4.1.1, not only in the editor, I found the problem when the game was running.

https://github.com/godotengine/godot/assets/6943500/fb4a2ddc-eb0d-402f-9e4f-ae4781d10d2d

https://github.com/godotengine/godot/assets/6943500/5c1c98e8-4e86-42e1-a019-51fc114ed94d

### Steps to reproduce

Follow the video.

### Minimal reproduction project

[test3_5_1.zip](https://github.com/godotengine/godot/files/12091305/test3_5_1.zip)
[test4_1_1.zip](https://github.com/godotengine/godot/files/12091314/test4_1_1.zip)

**Comment by bitsawer** [comment] 2023-07-19 05:36
Thanks for the report! This seems to be duplicate of https://github.com/godotengine/godot/issues/49781, so closing.

The linked issue has plenty of discussion and a few workarounds, including this one https://github.com/godotengine/godot/issues/49781#issuecomment-1543250039

**Closed** 2023-07-19 05:37 UTC
Labels: archived
