### ISSUE TITLE
3D Editor perspective display modes are confusing when using the compatiblity renderer

### ISSUE THREAD

**Issue by Mohamed-Kr** [godotengine/godot#74407] opened 2023-03-05 00:37 UTC
### Godot version

4.0.stable

### System information

Windows 11, i7, gpu:Intel® Iris™ Plus Graphics (integrated)

### Issue description

When using the compatibility renderer, the modes starting with "Display" in the perspective drop-down button located at the top-left corner of the 3D editor do not work.
Toggling these modes produces no effect (they behave like "Display Normal"), except for "Display Unshaded" which behaves as expected.

Also, I'm not sure but I think that some options like "Display Advanced->VoxelGI Lightning" will never be implemented for the compatibility renderer, and if it is the case I think that they should be disabled when using it to avoid confusion.

### Steps to reproduce

1. switch to compatibility renderer
2. have a meshinstance3D with a mesh visible in the 3D editor
3. toogle the modes wich names begins with "Display" in the perspective drop-down button located at the top-left corner

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-03-05 09:38
Those are more properly called modes, not options

**Comment by Mohamed-Kr** [comment] 2023-03-05 12:11
Ah ok thank you, I'll edit then

**Comment by clayjohn** [comment] 2023-03-06 07:02
Duplicate of https://github.com/godotengine/godot/issues/74420#issue-1610087266

**Closed by clayjohn** 2023-03-06 07:02 UTC
