### ISSUE TITLE
Bottom half on screen won't hover on button in Beta 4

### ISSUE THREAD

**Issue by AmilcarGodot** [godotengine/godot#68583] opened 2022-11-12 22:50 UTC
### Godot version

4.0 beta 4

### System information

Windows 10

### Issue description

I updated Godot 4 Beta 4 from Beta 2, i have a weapons radial menu in my game that was wprking perfectly in beta 2, it's no more working in beta 4. Thanks for taking a look at it 

### Steps to reproduce

No code to display just buttons i used to hover on in beta 2 and not in beta 4

**Comment by Sauermann** [comment] 2022-11-12 23:14
I tried, but I can hover Buttons in current beta, even when they are in the bottom half on the screen.
Can you please upload a minimal reproduction project, so that we can evaluate the problem?

**Comment by AmilcarGodot** [comment] 2022-11-12 23:37
Sorry my bad !! I added a negative px positions in the animation player including the 2D panel. That's why it wasn't working properly

**Comment by Sauermann** [comment] 2022-11-12 23:44
Thanks for the explanation. Looks like you can close this issue, because it is resolved.

**Closed** 2022-11-12 23:45 UTC
Labels: archived
