### ISSUE TITLE
Godot 4.2: mouse_entered will not trigger after GUI Disable Input toggled in SubViewport

### ISSUE THREAD

**Issue by xynanlee** [godotengine/godot#91320] opened 2024-04-29 17:19 UTC
### Tested versions

Reproducible in 4.2.1-stable and 4.2.2-stable, not in 4.1-stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

mouse_entered signal reside in a StaticBody2D under a SubViewport will not trigger anymore after `GUI Disable Input` is toggled off and on.

### Steps to reproduce

1. Open the MRP.
2. Play the scene.
3. Move mouse cursor onto the Godot logo.
4. Observe the `enter` text printed out in the Output panel.
5. Select Remote at the Scene dock.
6. Click on SubViewport.
7. Toggle GUI > Disable Input On and Off.
8. Repeat Step 3.
9. No subsequent `enter` text will be print out in the Output panel.

### Minimal reproduction project (MRP)

[4.2.2-stable_InputIssue.zip](https://github.com/godotengine/godot/files/15152543/4.2.2-stable_InputIssue.zip)

**Comment by AThousandShips** [comment] 2024-04-29 17:50
I'd say this is expected, the setting disables input for the viewport, see [here](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-property-gui-disable-input):
> If true, the viewport will not receive input events.

The naming might be a bit ambiguous but the description is obvious

**Comment by Sauermann** [comment] 2024-04-29 18:01
bisected to #67791

**Comment by akien-mga** [comment] 2024-08-12 21:38
Closing as this works in 4.3, and the issue in 4.2 seems to be intended behavior as per the above comment.

**Closed by akien-mga** 2024-08-12 21:38 UTC
Labels: discussion, confirmed, topic:input
