### ISSUE TITLE
Glow Post Process is non uniform through screen axis. 

### ISSUE THREAD

**Issue by vitorbalbio** [godotengine/godot#43110] opened 2020-10-26 21:16 UTC
**Godot version:**
3.2.4 but also in 3.2.3

**OS/device including version:**
Windows 10, GLSL3

**Issue description:**
Glow Post Process blur looks spread more in vertical than horizontal axis causing oval shapes.
Off
![godot windows tools 64_amzlUmAFFp](https://user-images.githubusercontent.com/6172013/97229512-3f192a80-17b7-11eb-86a1-6b72b863ef4a.png)

On
![godot windows tools 64_uk2D2EOqdu](https://user-images.githubusercontent.com/6172013/97229525-43454800-17b7-11eb-89f5-40d14b15fdea.png)

**Steps to reproduce:**
Check the effect in a glow sphere

**Minimal reproduction project:**
[TesteGodot2.zip](https://github.com/godotengine/godot/files/5441599/TesteGodot2.zip)

**Comment by clayjohn** [comment] 2020-10-26 21:20
Fixed in master by https://github.com/godotengine/godot/pull/41668 and https://github.com/godotengine/godot/pull/42201

**Comment by Calinou** [comment] 2020-10-26 21:59
See also https://github.com/Calinou/godot-docs/tree/add-snake-pascal-toggle which was closed in `master`. I don't know if we can backport this to 3.2.x.

**Comment by clayjohn** [comment] 2021-03-31 20:07
@briansemrau feel free to make a PR adding a "high quality mode" in 3.x. 

For your benefit, the cause of this is because the horizontal pass is reading from a texture that is 2x larger than itself, while the vertical pass reads from a framebuffer that is the same size as itself. The horizontal pass thus has a range of only 1.5 pixels (in framebuffer space) while the vertical pass has a range of 2.

Your solution compresses the vertical pass to a range of 1.5, but it is still using 7 texture lookups! A better solution is to increase the range of the horizontal pass by adding an optional extra texture lookup that has a range of 4 pixels, thus increasing the range in framebuffer space to 2 pixels, just like the vertical pass.

**Comment by Calinou** [comment] 2021-10-15 23:45
This was implemented by https://github.com/godotengine/godot/pull/51491 (available in the next 3.4 beta), closing.

**Closed by Calinou** 2021-10-15 23:45 UTC
Labels: bug, topic:rendering
