### ISSUE TITLE
Animation loop doesn't work with imported 3D scene

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#20467] opened 2018-07-25 23:08 UTC
**Godot version:**
9423f23ffb80c946dec380f73f3f313ec44d0d18

**OS/device including version:**
Linux 4.17.8

**Issue description:**
"Animation Looping" doesn't work when you have an "imported" animation player like this:
![captura de tela de 2018-07-25 20-04-12](https://user-images.githubusercontent.com/1387165/43232154-f3bc240c-9045-11e8-9c75-12b93b8764cc.png)

**Steps to reproduce:**
Import an 3D animation from Blender using better collada plugin;
Enable Loop Animation;
Press F5;

**Minimal reproduction project:**
[Loop Test.zip](https://github.com/godotengine/godot/files/2229818/Loop.Test.zip)

**Comment by karroffel** [comment] 2018-07-31 09:08
If you use BetterCollada you can name your animation `TheAnimation-loop` and it will be imported with loop enabled.

The problem is that imported animations are read-only. You can change them in the editor, but they are only changed in memory and not on disk, so as soon as you start running the game, a new process is spawned which reads data from disk.

This should be better documented and maybe a "copy-on-write" could be made for resources?

**Comment by reduz** [comment] 2018-07-31 09:45
If you ask them to save to disk, new tracks added and loop info will be
kept on reimport. Maybe it should be the default behavior.

**Comment by myuniquename** [comment] 2020-05-07 06:50
I have same issue with imported with glb animation file. I don't think it's it's collada specific issue

**Comment by Sl3dge78** [comment] 2020-06-17 23:27
After a bit of digging around I found out that there already exists a nice warning that pops up if the flag "track_set_imported" is set on the animation track. The thind is that this flag only gets set when choosing "Files" as Storage option in the importer.
Which I think is the opposite of what we want because changes get populated properly on anim files stored outside of the original one. 
Working on a fix for this...

**Closed** 2020-06-19 21:45 UTC
Labels: bug, topic:core, topic:editor
