### ISSUE TITLE
Ctrl + Enter replaces selected text with a newline in the script editor (should move to the next line instead)

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#55855] opened 2021-12-12 09:37 UTC
### Godot version

v3.4.stable.official [206ba70f4] and the online editor: https://editor.godotengine.org/releases/3.4.1.rc2/

### System information

Windows 10 21H1, Geforce GTX 550 Ti, GLES2 and GLES3

### Issue description

In the script editor.
Selecting text and pressing `ctrl enter` or `shift ctrl enter`,
replaces the selection with a newline.

Expected:
Cancel the selection and move the cursor to a:
- new empty line below (`ctrl enter`)
- new empty line above (`shift ctrl enter`)

This would make `ctrl (shift) enter` behave the same with or without selected text.

If the intention is to replace the selected text with a new line,
then `enter` can be pressed without holding down a modifier key.

### Steps to reproduce

- create a new or open an existing script
- type some text, for example:
```
var test = 3
```
- select `test`

>Explanation of symbols:
cursor = `|` (vertical bar)
selection start = `[`
selection end = `]`

```
var [test]| = 3
```
- press `ctrl enter`

### observed
```
var 
| = 3
```
Result: A newline replaced the selected text.

### expected:
After `ctrl enter`:
```
var test = 3
|
```
Result: The cursor is on a new empty line below, and the selected text stays unmodified.

Or after pressing `shift ctrl enter`:
```
|
var test = 3
```
Result:  The cursor is on a new empty line above, and the selected text stays unmodified.

### notes:
An application that shows the expected behavior is Visual Studio Code.

**Comment by Calinou** [comment] 2021-12-12 15:14
I can reproduce this when text is selected in 3.4.stable and `master` 2a9dd654b.

When no text is selected, I can't reproduce this on 3.4.stable and `master` 2a9dd654b. Both <kbd>Ctrl + Enter</kbd> and <kbd>Ctrl + Shift + Enter</kbd> work as expected.

**Comment by preslavb** [comment] 2021-12-12 18:06
Hey, this seems like a good one to take as a first PR. I've fixed this locally and am currently going through the docs on how to submit a pull request for the engine.

**Comment by Calinou** [comment] 2021-12-12 18:13
> Hey, this seems like a good one to take as a first PR. I've fixed this locally and am currently going through the docs on how to submit a pull request for the engine.

This will likely require different pull requests to be fixed in both `master` and `3.x`, since TextEdit was refactored into separate classes (TextEdit and CodeEdit) in `master`. I recommend opening a pull request against `master` first, then a separate pull request against `3.x`.

**Comment by preslavnpetrov** [comment] 2021-12-12 22:23
PR #55884 submitted for review.

**Closed** 2022-01-24 20:33 UTC
Labels: enhancement, topic:editor, confirmed, usability, topic:gui
