### ISSUE TITLE
Shadows disappear at certain viewing angles with distant camera far plane

### ISSUE THREAD

**Issue by minoaut** [godotengine/godot#91753] opened 2024-05-09 09:40 UTC
### Tested versions

Reproducible in: v4.3.dev.custom_build [7ebc86641]
Not reproducible in: v4.3.dev.custom_build [51991e201]
Regression introduced in: v4.3.dev.custom_build [4577dfdb6]

### System information

Ubuntu 24.04 LTS - Vulkan (Forward+) - reproducible with both Intel IGP and NVIDIA dedicated

### Issue description

If the Camera3D far plane is set to something high like 1e5..1e6, shadows disappear at certain viewing angles either completely or partially. The affected angles are narrow, but once found and the camera stays put, shadows can stay off indefinitely. 

Shadows may disappear partially. In my project, trees (MultimeshInstance) are often unaffected, but not always, while all vehicles and terrain lose their shadows regularly. Where shadows disappear they all disappear at the same time, no matter the object type or distance. 

Shadow settings seem to have no influence on this. The only setting that I found to have an impact is the camera far plane:
far = 4000 (default) -> cannot reproduce
far = 1e5  -> can reproduce at few angles 
far = 1e6  -> can reproduce at many angles 

I happen to need at least 1e5, better 1e6, else the clouds don't render right.

### Steps to reproduce

- Run the attached sample project
- observe for a few seconds (10-30s)
- shadows should disappear briefly at multiple rotation angles
  look for whole walls flashing bright white

### Minimal reproduction project (MRP)

[disappearing_shadows_example.zip](https://github.com/godotengine/godot/files/15260455/disappearing_shadows_example.zip)

**Comment by minoaut** [comment] 2024-05-11 02:42
I let git bisect do it's thing and it found this commit:
4577dfdb6747600438ac4b86c29a4d6c12ec9b0a is the first bad commit

With that commit shadows start to disappear.

**Comment by minoaut** [comment] 2024-05-11 04:47
Here's the workaround I'm using now,. It's terrible, don't commit. 
I'm not sure what the real issue is. Maybe the frustum planes don't factor in the changed far plane for some reason?
```
diff --git a/servers/rendering/rendering_light_culler.cpp b/servers/rendering/rendering_light_culler.cpp
index 8dc2d85bdf..0d8a6d90ce 100644
--- a/servers/rendering/rendering_light_culler.cpp
+++ b/servers/rendering/rendering_light_culler.cpp
@@ -418,7 +418,7 @@ bool RenderingLightCuller::_add_light_camera_planes(LightCullPlanes &r_cull_plan
 	// Deal with special case... if the light is INSIDE the view frustum (i.e. all planes face away)
 	// then we will add the camera frustum planes to clip the light volume .. there is no need to
 	// render shadow casters outside the frustum as shadows can never re-enter the frustum.
-	if (lookup == 63) {
+	if (1 || lookup == 63) {
 		r_cull_planes.num_cull_planes = 0;
 		for (int n = 0; n < data.frustum_planes.size(); n++) {
 			r_cull_planes.add_cull_plane(data.frustum_planes[n]);

```

**Comment by Chaosus** [comment] 2024-05-11 11:01
cc @lawnjelly

**Comment by lawnjelly** [comment] 2024-05-11 16:13
Likely duplicate of #89560 , so may be fixed already.
Cannot test as away from home.

**Comment by lawnjelly** [comment] 2024-05-12 13:26
Yes I can confirm this is already fixed by #91790 .

I'll close this issue and reopen #89560 temporarily to hopefully reduce the chance of duplicate issues.

**Closed by lawnjelly** 2024-05-12 13:26 UTC
Labels: bug, topic:rendering, regression, topic:3d

**Comment by minoaut** [comment] 2024-05-13 06:01
Hmm.. I tested v4.3.dev [7ebc86641] and the problem is still there. Commit 2ba22d1 is included, I checked.
What am I missing?

@lawnjelly have you been able to run my sample project?  This is what I see, note the flashing:

https://github.com/godotengine/godot/assets/100795439/21318f21-c165-4fcf-b843-9b76bc121544

**Comment by lawnjelly** [comment] 2024-05-13 07:21
I tested again and it looks fixed as far as I can see. The commit you are testing looks like from last week, the fix was added 3 days ago.

Note that the time of the PR was made isn't the same as the time it was merged into master (which is later).

These are the logs from the commit you tested, they seem to go up to May 4th, which is 9 days ago:
https://github.com/godotengine/godot/commits/7ebc866418b075df58cbe4e31fcf8b0c3acd70a1/

You can download the artifacts from the actual PR to test (click view details):
https://github.com/godotengine/godot/pull/91790
