### ISSUE TITLE
2D Platformer demo - one-way platform malfunctions

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#2345] opened 2015-08-09 05:30 UTC
https://youtu.be/GOQqWtPViDA

**Comment by zhagsenkk** [comment] 2015-08-09 07:34
It's caused by the player's collision shape and the one way collision platform.When everything is gone in video,the player's position is here:
-403318496,67354935296
-404388192,67533594624
-405457888,67712253952
-406527584,67890913280
-407597280,68069572608
-408666976,68248231936
-409736672,68426891264
-410806368,68605550592
-411876064,68784209920

**Comment by agameraaron** [comment] 2015-08-30 19:08
A duplicate of the bug reported can be found here, but for me I could only replicate in OSX, not Windows: https://github.com/okamstudio/godot/issues/2038

**Comment by vipsbpig** [comment] 2015-09-16 09:48
I replicate this in windows, when set "target_fps" into "30" in project setting,will replicate it easily.

It seem the physics doesn't work as my expected
"target_fps=30",no fixed_fps 
![godot_one_way_03](https://cloud.githubusercontent.com/assets/1953549/9901397/1ccee60a-5c9a-11e5-925b-93be3293d748.gif)
![godot_one_way_01](https://cloud.githubusercontent.com/assets/1953549/9901398/1cda8aa0-5c9a-11e5-8a2e-4f2f73c4e1a4.gif)
"target_fps=30,fixed_fps=60"
![godot_one_way_04](https://cloud.githubusercontent.com/assets/1953549/9901411/2d337952-5c9a-11e5-939f-ac0a023decba.gif)
It will freeze in some loop.

When android once touch the one way platform screen become grey besides the UI ,it might be the some problem.

**Comment by AlexHolly** [comment] 2015-09-16 11:36
+1 grey on android

**Comment by vnen** [comment] 2015-09-16 13:58
There's a similar problem in HTML5 too, only instead of screen being grey, you can still see the parallax background. The left and right controls still works.

**Comment by agameraaron** [comment] 2015-11-11 02:52
My duplicate bug report was removed, so this video is now simply being relinked for supplementation to this bug report: https://www.youtube.com/watch?v=Ngi-YJWPDsc
Recorded in OSX on my 09' Mac Mini. 

By the way, in this video is how it happens for me *every* time. It is strange that you guys are getting other results.

**Comment by akien-mga** [comment] 2015-12-16 10:56
From @ndee85 on #2294:

> One way collisions worked once good for me. After this commit I had problems: 32b1b47

> Now my character falls often through the collider. I have a moving platform that can float. Once It starts moving the character falls immediately through.

> I send you an email a while back with my project which had the problem. Would be great if this could be fixed again :-)

**Comment by reduz** [comment] 2015-12-31 21:47
wrong id :(

**Closed** 2016-01-01 15:13 UTC
Labels: bug, confirmed, high priority, topic:demos

**Comment by ndee85** [comment] 2016-01-01 17:06
Great.. will try it out right now. Building new godot version!
Thanks for fixing that issue! :+1:
