### ISSUE TITLE
TileMap2D ignore visible properties if y-sort flag is true

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#29143] opened 2019-05-24 03:58 UTC
**Godot version:** 3.1 stable

**OS/device including version:** ubuntu android

**Issue description:** as stated in issue title. i dont know this is intended or not but i feel it so annoying.

**Steps to reproduce:** set y sort to true and set visible to false, but TileMap2D still visible 

**Minimal reproduction project:**  not needed it so obvious.

**Comment by KoBeWi** [comment] 2019-05-24 14:59
I can't reproduce it. Does it happen in exported project? (you mentioned Android)

**Comment by fian46** [comment] 2019-05-24 15:20
yes it also happened on android exported

**Comment by fian46** [comment] 2019-05-24 15:20
i will put gif to proof it soon

**Comment by fian46** [comment] 2019-05-24 15:29
![tilemap](https://user-images.githubusercontent.com/13792627/58339212-aa9cf100-7e7b-11e9-95c3-dcd4279331c5.gif)

**Comment by fian46** [comment] 2019-05-24 15:31
![linux](https://user-images.githubusercontent.com/13792627/58339335-edf75f80-7e7b-11e9-8a45-02540305c6db.gif)

the node already set visible = false

**Comment by fian46** [comment] 2019-05-24 15:35
![android](https://user-images.githubusercontent.com/13792627/58339665-a8876200-7e7c-11e9-95bd-30338eda6b03.gif)

**Comment by KoBeWi** [comment] 2019-05-24 15:35
Ok, I found a way to reproduce. It only happens **if the Tilemap is also a child of YSort**. What's also interesting, Tilemap will lose its `modulate` when `y_sort` is enabled.

**Comment by fian46** [comment] 2019-05-24 15:36
yes my tilemap is under y_sort

**Comment by fian46** [comment] 2019-05-24 15:38
is it wrong to have tilemap under ysort node or i am just missing documentation here ...

**Comment by AtomaFajrovulpo** [comment] 2019-10-31 16:46
https://github.com/godotengine/godot/files/3794884/VSort.Bug.Demo.zip

**Comment by bojidar-bg** [comment] 2019-10-31 17:02
Duplicate of #28501?

**Comment by AtomaFajrovulpo** [comment] 2019-10-31 17:08
@bojidar-bg It is a different problem.

**Comment by AtomaFajrovulpo** [comment] 2019-10-31 17:11
I think so.

**Comment by tabletopcrow** [comment] 2019-10-31 22:44
You're not the only one, it's not working for me either

**Comment by AtomaFajrovulpo** [comment] 2019-11-01 10:56
@tabletopcrow Fixed on 3.2.

**Comment by KoBeWi** [comment] 2019-12-15 22:53
> Fixed on 3.2.

**Closed by KoBeWi** 2019-12-15 22:53 UTC
Labels: bug, topic:core
