### ISSUE TITLE
When exporting a enum with no zero value defined, the editor takes the wrong default value

### ISSUE THREAD

**Issue by AndreSacilotto** [godotengine/godot#76933] opened 2023-05-11 01:19 UTC
### Godot version

4.1.0-dev.1

### System information

Win10

### Issue description

Export a enum without a value defined for 0 can create a visual bug in the editor that makes the default value wrong.

Godot consider the default value of all exported enums to be always 0, but a enum dont necessary will have a 0 defined.

So by default it assumes all enum always start with 0, but since the enum dont have a 0 it shows the first element instead, but it dont actually use its value.

### Steps to reproduce

Create a c# enum with no zero value and other class that export that enum.

Example:
```cs
public enum TDirection : int
{
     RightToLeft = -1,
     LeftToRight = 1,
}
```

```cs
public partial class Test : Node
{
     [Export] public TDirection tDir;
}
```

### Minimal reproduction project

[EnumBugDefault.zip](https://github.com/godotengine/godot/files/11447259/EnumBugDefault.zip)

**Comment by AndreSacilotto** [comment] 2023-05-11 01:45
Yes there is a workaround that is simply explicitly defining the default value:
```cs
public partial class Test : Node
{
     [Export] public TDirection tDir = TDirection.RightToLeft;
}
```

What I'm trying to point out in this issue is that the editor shows the wrong when you dont do it.

It will show `RightToLeft` with value `0`, and since that is not defined in any place it is a bug.

**Comment by Calinou** [comment] 2023-05-11 01:54
Can you reproduce this in GDScript?

**Comment by AndreSacilotto** [comment] 2023-05-11 02:21
Well I thought it was a c# bug, but seens like it's not - @Calinou yes it also happens on GDScript.

```
enum State {A = -1, B = 1}

@export var n1 :State
@export var n2 :State

func _ready():
	print(n1)
	print(n2)
```

**Comment by akien-mga** [comment] 2023-05-11 10:53
Duplicate of #74123 (and I'm pretty sure this is discussed in other issues, but I can't find them easily, GitHub search is failing me).

It's indeed a known design issue with the way enums work and the fact that exported variables get zero'ed by default, even if their export hint limits the valid range to something that doesn't contain zero.

**Closed by akien-mga** 2023-05-11 10:53 UTC
Labels: bug, topic:editor
