### ISSUE TITLE
Godot_v3.1-beta1_win64 - error in position objects GridMap using Mesh Library

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#24867] opened 2019-01-09 14:54 UTC
**Godot version:**
v3.1-beta1_win64

**OS/device including version:**
windows 64

**Issue description:**
error in Grid Map

**Steps to reproduce:**
picture send attach

![ero1](https://user-images.githubusercontent.com/39173940/50907104-b4aedd80-140d-11e9-93e8-2111653716b7.png)
![ero2](https://user-images.githubusercontent.com/39173940/50907105-b5477400-140d-11e9-9823-d8a840d4a6bd.png)

**Comment by Chaosus** [comment] 2019-01-09 18:18
Please attach an example project where this issue is reproductable

**Comment by giovanigsilva** [comment] 2019-01-10 16:49
[project_with_error.zip](https://github.com/godotengine/godot/files/2746294/project_with_error.zip)

![error3](https://user-images.githubusercontent.com/39173940/50983568-dc25a900-14e6-11e9-8ee8-86aafaed1911.png)
![error4](https://user-images.githubusercontent.com/39173940/50983569-dcbe3f80-14e6-11e9-8e1f-1b28f13f29f8.png)
![error5](https://user-images.githubusercontent.com/39173940/50983572-dd56d600-14e6-11e9-91bc-c6c235b0a711.png)
![error6](https://user-images.githubusercontent.com/39173940/50983573-dd56d600-14e6-11e9-8884-9c5198e29e87.png)

**Comment by giovanigsilva** [comment] 2019-01-10 16:51
> Please attach an example project where this issue is reproductable

ok

**Comment by Chaosus** [comment] 2019-01-10 17:55
Yeah, I see, looks like a bug, but fix for this is not trivial as it could easily break the existing people projects

**Comment by Chaosus** [comment] 2019-01-10 17:57
Maybe the @reduz will help you, I assign him to this issue

**Comment by KoBeWi** [comment] 2020-07-05 14:13
This is more like missing feature, there's a related proposal: https://github.com/godotengine/godot-proposals/issues/805 so closing in favor of it.

Also the icon bug is fixed when you re-export the meshlib.

**Closed by KoBeWi** 2020-07-05 14:13 UTC
Labels: bug, topic:core
