### ISSUE TITLE
Editor window fullscreens on save

### ISSUE THREAD

**Issue by ffernn-dev** [godotengine/godot#67419] opened 2022-10-15 00:00 UTC
### Godot version

4.0.beta2

### System information

Arch (Linux 6.0.1), KDE Plasma (5.26.0), AMD 5700G integrated graphics

### Issue description

The main godot editor window goes to maximized mode when hitting either ctrl+s or one of the right click menu save buttons (scene, script etc).
Confirmed to not happen on MacOS, not sure about windows.

### Steps to reproduce

Create a new project, make a scene, hit ctrl+s.

**Comment by Calinou** [comment] 2022-10-15 00:17
Duplicate of https://github.com/godotengine/godot/issues/66413 (fixed in latest `master` branch).

**Closed by Calinou** 2022-10-15 00:17 UTC
