### ISSUE TITLE
Updating video driver while Godot editor is open freezes and blanks UI, may cause loss of unsaved data

### ISSUE THREAD

**Issue by jefreestyles** [godotengine/godot#100214] opened 2024-12-09 19:18 UTC
### Tested versions

- Reproducible in v4.3.stable.official

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

 was attempting to fix several Vulkan-related issues that pop up when building with --verbose turned on by updating my Nvidia Graphics Driver.

E 0:00:00:0213   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_get_json: Failed to open JSON file C:\ProgramData\obs-studio-hook\obs-vulkan32.json
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1798990300688
  <C++ Source>   drivers/vulkan/rendering_context_driver_vulkan.cpp:308 @ _debug_messenger_callback()

W 0:00:00:0214   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1798990300688
  <C++ Source>   drivers/vulkan/rendering_context_driver_vulkan.cpp:305 @ _debug_messenger_callback()

The driver update did not fix my issues.  However; I noticed that if I have the Godot editor open and a file waiting to be saved, when the video driver refreshes the screen, the Godot editor UI is gone and the window is empty.  When I try closing the window, I get an empty saved dialogue with no way of saving since the buttons are gone.  I have to CLTR+ALT+DELETE to task manager to close Godot and lose my saved edits.

Is that a known issue?  Does Godot need a graceful failure process that can prevent lost of changed data?  Warn users to close Godot before updating drivers somehow?

Nvidia Graphics Driver 566.36 (Installed)
PhysX System Software 9.23.1019 (A newer or same version is present.)
HD Audio Driver 1.4.2.6 (Installed)

![Image](https://github.com/user-attachments/assets/9e290e3d-fb48-4dbe-8473-d8ded80ca23f)

Processor	13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

Edition	Windows 11 Home
Version	23H2
Installed on	‎4/‎19/‎2023
OS build	22631.4460
Experience	Windows Feature Experience Pack 1000.22700.1047.0

### Steps to reproduce

- Create a new project and add a scene and script.
- Make a change to script or scene.
- Open Nvidia GeForce Experience.
- Go to Drivers tab.
- Update video driver using or reinstall newest video driver.

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment] 2024-12-09 20:12
Thank you for checking. This is indeed a duplicate of https://github.com/godotengine/godot/issues/98386

I'll go ahead and close this issue in favour of https://github.com/godotengine/godot/issues/98386 so we can track it in one place. 

For future readers, you can still save your projects when this happens by hitting "ctrl + s" (or by clicking where the save button should be). 

As a cautionary tale, this is why the GPU driver update dialogue tells you to close all your other running apps before the update starts.

**Closed by clayjohn** 2024-12-09 20:12 UTC
