### ISSUE TITLE
DirectionalLight shadows artifacting in wide viewports

### ISSUE THREAD

**Issue by xylas-dev** [godotengine/godot#43582] opened 2020-11-15 23:23 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 7, Geforce 780, GLES2/GLES3

**Issue description:**
DirectionalLight shadows produce artifacting when the viewport aspect is wide. I have created a project which uses a ViewportContainer to rotate a scene 90 degrees, the only difference between these two screenshots is the rotation of the camera and viewport, all rendering and light settings are the same.
![capture_2020-11-15_18-01-12](https://user-images.githubusercontent.com/74514583/99199641-984cfc00-276e-11eb-8395-281b4bffa298.jpg)

**Steps to reproduce:**
In a scene with a DirectionalLight with shadows enabled, resize the window to be wide or narrow. The shadows will produce artifacting depending on how wide the window is.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/5543303/test.zip)
Press spacebar to change the orientation of the viewport and camera.

**Comment by Calinou** [comment] 2020-11-15 23:38
Duplicate of https://github.com/godotengine/godot/issues/23603.

**Closed by Calinou** 2020-11-15 23:38 UTC
