### ISSUE TITLE
Editor sizes wrong when moving between retina screen and non-retina 2nd monitor

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8282] opened 2017-04-06 04:19 UTC
**Operating system or device - Godot version:**
OSX 10.11
Godot 2.1.3
Macbook pro retina with attached thunderbolt display.

**Issue description:**
Godot opens up fine on the laptop window. I can move the project browser fine between the monitors. Open up a project it renders fine on the retina display but gets completely blown out of perportions on the thunderbolt display.

My guess is that its not detecting the switch between retina resolution on the one monitor and non-retina on the 2nd monitor and thus not adjusting the scaling accordingly.
Strange that the project selection window works fine though.

**Steps to reproduce:**
Move the editor window between a retina and non-retina display

**Comment by Hinsbart** [comment] 2017-04-06 05:54
Closing as duplicate of #5688.

**Closed by Hinsbart** 2017-04-06 05:54 UTC
