### ISSUE TITLE
Godot Web Editor not using/allowing gles3

### ISSUE THREAD

**Issue by SIsilicon** [godotengine/godot#52455] opened 2021-09-07 04:35 UTC
### Godot version

3.3.3.stable

### System information

Windows 10, Google Chrome Browser

### Issue description

Even though the editor may say that is using GLES 3, all the objects and the editor itself still act as if it's running in GLES 2. 
**edit** And yes, the browser supports WebGL 2.0.
**edit** Also, I checked and this quirk has been here since Godot 3.3.

### Steps to reproduce

Just enter a project with GLES 3. If you try to edit the environment, you'll notice that features such as ssao and tone mapping are not available.

**Comment by akien-mga** [comment] 2021-09-17 20:04
> If you try to edit the environment, you'll notice that features such as ssao and tone mapping are not available.

Indeed, I can reproduce this. This indeed means that the rasterizer implementation reports `true` for `VisualServer::get_singleton()->is_low_end()`, i.e. it's GLES2. Any idea why @Faless?

**Comment by Faless** [comment] 2021-09-18 07:24
GLES3 (WebGL2) has always been disabled in the Web Editor.

**Comment by Faless** [comment] 2021-09-18 07:25
Originally, the project manager would not allow you to create GLES3 projects at all, not sure when it changed.

**Comment by SIsilicon** [comment] 2021-09-18 14:08
Here?
https://github.com/godotengine/godot/blob/bb2772d2f2edc4ff5615044acee1b112dce66c50/platform/javascript/os_javascript.cpp#L808

**Comment by Faless** [comment] 2021-09-18 15:26
@SIsilicon that's the commit that disables GLES3 for the web editor.
As I said, it has always been disabled, but that was also reflected in the project manager creation pop-up, which doesn't seem to be the case right now.

**Comment by akien-mga** [comment] 2021-09-18 15:52
IIRC it was disabled in the prototype phase due to issues, but I don't think we aimed for it to stay this way. Do you remember what the issues were? Was it just context switching being problematic?

**Comment by Faless** [comment] 2021-09-18 16:08
IIRC the reason was browsers never really free the GL context. Which means the canvas must be deleted and recreated every time the editor or game changes from GLES3 to GLES2. It needs some rework of the `misc/html/editor.html` page I think.

**Comment by akien-mga** [comment] 2021-10-20 08:40
Fixed by #53991.

**Closed by akien-mga** 2021-10-20 08:40 UTC
Labels: discussion, platform:html5, topic:rendering, topic:editor, confirmed
