### ISSUE TITLE
Editor layout doesn't remember file system position

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#54806] opened 2021-11-09 14:59 UTC
### Godot version

4.0.dev 9444a3f01d3a8c4f49ddf24e3acc65b399ee0609

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

I use to customize the editor layout, it works well for everything but the file system layer. I have no idea, but here a record of the issue:
![bug-layout](https://user-images.githubusercontent.com/6616005/140947855-9bc5c5f2-06fa-4ff9-81a5-5fef973f887d.gif)

### Steps to reproduce

1. Launch Godot Engine, and load any project
2. Change the position of the File system layer
3. Close Godot Engine
4. Repeat step 1, the file system layer is back to its default position

**Comment by YLL** [comment] 2021-12-03 12:24
Same here for version v4.0.dev.20211117.official [175690957].

I checked around and found it might be a bug when saving the docking infos without removing the old ones.

It's visible when moving panels to the docking position with a smaller id (i.e. from dock_4 to dock_2).

Below is what the **_editor_layout.cfg_** looks like with a few times of moving around the panels and quit.

> [docks]
> dock_1="Scene,Import"
> dock_2="FileSystem"
> dock_3="Scene,Import"
> dock_filesystem_split=-63
> dock_filesystem_display_mode=0
> dock_filesystem_file_list_display_mode=1
> dock_split_1=37
> dock_split_2=0
> dock_hsplit_1=0
> dock_hsplit_2=70
> dock_hsplit_3=-70
> dock_hsplit_4=0
> dock_filesystem_file_sort=0
> dock_4="FileSystem"
> dock_5="Inspector,Node"
> dock_split_3=0
> dock_6="FileSystem"

**Comment by YLL** [comment] 2021-12-03 21:10
Located this bug was introduce in commit 902d468f5233f97f56771ce60159aabf2a78a113

which should just modify the _**editor_log.cpp**_ but inserted the following lines to the _**editor_node.cpp**_

and caused the old layout settings getting combined with the latest settings and then write to _**editor_layout.cfg**_
>	// Load and amend existing config if it exists.
>	config->load(EditorSettings::get_singleton()->get_project_settings_dir().plus_file("editor_layout.cfg"));

**Comment by YLL** [comment] 2021-12-04 00:21
Doubled checked these codes for layout saving. This bug is caused by` EditorNode::_save_docks_to_config() `not clearing the previous section before writing the new ones in the same section.

It's OK before 902d468f5233f97f56771ce60159aabf2a78a113 adds the layout settings for editor log into the  _**editor_layout.cfg**_ and `EditorNode::_save_docks()` dosen't need to load the existing settings and it just constructs a new config file.

Tested in v3.4.stable.official [206ba70f4] and this bug also leads to not saving named layouts properly.
This is the steps to reproduce the bug in any Godot versions from 3.x to 4.0

1. Reset layout to Default
2. Save the current layout with name "test"
3. Move FileSystem panel to dock_8 ( the last docking position )
4. Save the current layout with name "test"
5. Check the content of `editor_layout.cfg` in editor data path
6. Found duplicate FileSystem entries in the "test" section

I drafted a pullrequest #55612 , should fix the bug.

**Comment by YLL** [comment] 2021-12-04 10:05
@Calinou 
As I mentioned before, the `EditorNode::_save_docks_to_config()` is basicly untouched since [5dbf1809c6e3e905b94b8764e99491e608122261] . So the bug of not saving named layout properly is there ever since.
Should I create a new issue for the current 3.x version, or we can just add a cherry pick label for 3.4.RC version?

**Comment by xsellier** [comment] 2022-03-24 10:03
Still happening d7d528c15f0e858b52bb0f510ff47e65c2341de1

**Comment by YLL** [comment] 2022-03-25 06:31
> Still happening [d7d528c](https://github.com/godotengine/godot/commit/d7d528c15f0e858b52bb0f510ff47e65c2341de1)

My patch is still waiting for review . Since it's marked 4.0 milestone, it won't be merged soon I suppose.

**Comment by nathanfranke** [comment] 2022-07-03 05:19
I think I am having a similar issue with the Inspect+Node docks.

1) Change the docks to this:
![image](https://user-images.githubusercontent.com/14253836/177025883-813957d3-c873-443e-93a7-ee4a9b28b55b.png)

2) Move the Node dock to the same position as the inspector:
![image](https://user-images.githubusercontent.com/14253836/177025898-151dff21-6f3d-4502-9495-0e1c9634aa46.png)

3) Project→Reload Current Project

4) The docks are back to what they were previously:
![image](https://user-images.githubusercontent.com/14253836/177025942-25f23053-47a5-4005-97aa-161ca0ab2b84.png)

Workaround
---

Drag the _Inspector_ dock onto the _Node_ dock. This puts both of them in the bottom right location, and it seems to save after that.

![image](https://user-images.githubusercontent.com/14253836/177025978-d93c19aa-ac1b-472b-854b-c96bf91628c8.png)
![image](https://user-images.githubusercontent.com/14253836/177025997-1c2884e0-5e99-4efc-8f6f-ca4441c3d3ce.png)

**Comment by KoBeWi** [comment] 2022-08-25 18:11
I tried to reproduce the issue using the same exact layout from the OP, but it doesn't seem to be happening anymore. Can anyone still reproduce in 4.0? What are the reproduction steps?

**Comment by YLL** [comment] 2022-09-02 04:57
I checked the latest master branch. It's fixed in another duplicate issue #57142.
This one should be marked as duplicate and fixed.
I'll close my pull request.

**Closed** 2022-09-02 05:55 UTC
Labels: bug, topic:editor, confirmed, regression
