### ISSUE TITLE
Wrong preview image generated when playing an edited scene

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12686] opened 2017-11-05 22:21 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/9a78efc7c270211e49fd7b2f071b61c706febffc

**Issue description:**

![https://i.imgur.com/GkD5Xoo.gifv](https://i.imgur.com/GkD5Xoo.gif)

**Steps to reproduce:**
1. Open two different scenes
2. Change to the script tab
3. Move to another scene and hit `Play the edited scene (F6)`
4. The wrong preview image will be generated for that scene (it will be the last scene opened)

**Comment by dragmz** [comment] 2017-11-19 23:35
I think it's caused by taking the viewport texture as a preview when saving before run but the viewport does not seem to be refreshed when switching a scene with script opened.

**Comment by reduz** [comment] 2017-11-22 17:12
i think the problem is that the 2D viewport (and 3D) is not updated when switching scene, maybe forcing it to update at least once when switching would be a proper fix

**Comment by dragmz** [comment] 2017-11-23 19:04
@reduz I've extracted the code that draws a selected viewport from VisualServerViewport::draw_viewports and added a force flag so the viewport update_mode and hide_canvas can be ignored then I'm calling it it _save_scene_with_preview. Do you think that's acceptable? The fix is available here:

https://github.com/dragmz/godot/commit/cb5e7f864adae1032c6145e2092e2fcf670e4780

**Comment by volzhs** [comment] 2017-12-10 05:40
@dragmz would you make PR for that to make dev not to forget to review it?

**Comment by reduz** [comment] 2018-09-05 22:26
Is this still a problem? I think this was changed or fixed recently

**Comment by akien-mga** [comment] 2018-09-09 12:55
This is indeed fixed in the master branch.

**Closed by akien-mga** 2018-09-09 12:55 UTC
Labels: bug, topic:editor
