### ISSUE TITLE
Script changes won't be saved

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3137] opened 2015-12-26 05:13 UTC
This is a weird and random bug but it's very crucial to have fixed.
I tend to use built-in scripts instead of a proper saved file for some minor scripting on some nodes.
Sometimes when I change something on the code  these changes won't be saved.

When I press Ctrl + S to save it does save the scene and the little (*) indicator disappears from the file name as it was saved correctly. However when the game is run, it's the previous version of the code that is running. I can re-edit and re-save the script several times but its still the old version that gets loaded in-game.

I can confirm that because when I close the editor and reopen the project, the script is the previous version as it was never saved.

I don't know if this extends also to common script (.gd) files but I guess it does.
I can't provide a sample project or steps to reproduce because it appears to be random (although I've encountered it very often working on my project )

I'm using the version at commit 09e3dd1ecb9d09d2cbd170cd99d552fb2a310d24
I'm on Linux Mint 17.

**Comment by kubecz3k** [comment] 2015-12-26 10:36
@FEDE0D When it comes to "ordinary" gd script files I don't think this issue applies to them (never observed yet, while had some problems with those build into scenes). Which file-format for your 'scripted-scenes' do you use (scn|xscn|tscn)?

**Comment by 29jm** [comment] 2015-12-26 11:14
I can confirm this issue, with a scene in scn format.

**Comment by kubecz3k** [comment] 2015-12-26 12:17
Would be ideal if we could have detailed step by step instructions on how to reproduce this issue... I assume there exist some sequence of opening/saving/closing/reverting/switching to other scene, actions that is causing this..

**Comment by ScotFlux** [comment] 2015-12-28 20:23
I also have this kind of issue with a new build provided by Kelinci Senja on Facebook.

Godot v2.0.alpha-r2575 + Windows 7 x64

**Comment by kubecz3k** [comment] 2015-12-29 09:31
@ScotFlux What file format are you using? Gd or those are putted inside scn|xscn|tscn?

**Comment by ScotFlux** [comment] 2016-01-06 16:18
@kubecz3k I used the .gd(s). I haven't test script(s) inside scn|xscn|tscn.

**Comment by reduz** [comment] 2016-01-23 19:14
Did you untick this by chance?
![rbs](https://cloud.githubusercontent.com/assets/6265307/12532193/5fdc8f80-c1ec-11e5-883b-2bb239d1ff5b.png)
I just can't reproduce this in any way otherwise

**Comment by FEDE0D** [comment] 2016-01-23 19:26
No. I those are still checked.

**Comment by reduz** [comment] 2016-01-23 21:57
No idea then, I can't reproduce this.. but I fixed a bug that may be related some hours ago

**Comment by MarianoGnu** [comment] 2016-01-24 04:29
Btw, menu script>save was not working at all (even for .gd files), didn't check if it was fixed this week

**Comment by FEDE0D** [comment] 2016-01-24 04:40
That must me it

**Comment by reduz** [comment] 2016-01-25 03:27
menu > save was fixed a few days ago, so closing this

**Closed by reduz** 2016-01-25 03:27 UTC
Labels: bug, topic:editor, topic:gdscript

**Comment by felipefacundes** [comment] 2022-02-12 17:46
This is a bug for sure. I'm going through the same problem. Every time this happens, I have to create a new project and port everything there, which slows down production a lot. It gets in the way too much! And also if you try to "save as" it doesn't allow overwriting. I'm using the latest stable version of Godot 3.4.2. Please check this as it is a bug that was present in previous versions. Look at this post is from 2020 and it hasn't been fixed yet.

In my case my problem is not with the GDScript itself, but with saving an existing scene that I had to change, when creating a node or when I am going to change the scene

I reported this error as well
https://godotengine.org/qa/80242/scene-not-saving

**Comment by Calinou** [comment] 2022-02-12 17:50
@felipefacundes Please don't bump old closed issues by copy-pasting the same message.
