### ISSUE TITLE
is_on_floor() with KinematicBody2D stops working correctly when the character runs automatically

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#42940] opened 2020-10-20 15:36 UTC
**Godot version:** 3.2.3.stable.official
(Regular and Mono Editions, [Official Download](https://godotengine.org/download/linux))

---

**OS/device including version:** Personal 64-bit Home Computer (Tower) with
Linux Mint Debian Edition 4 64-bit ([More specifications](https://termbin.com/hped))

---

**Issue description:** I am making an Autorunner.
When implementing the Jump by itself (you cannot run), the floor detection works perfectly as expected.
Only after adding the single line that makes Autorunning work, ```is_on_floor()``` rapidly alternates between ```true``` and ```false``` when it should constantly output ```true```.

---

**Steps to reproduce in the minimal reproduction project:**
Simply enable the _Player_ node's _Running Mode_ in the Inspector.
You'll see that the bug happens only when it's enabled.

---

**Steps to reproduce in a new project:**
1. Create a 2D Scene with Tiles
(it doesn't matter if it's a Tilemap or Individual Blocks)
(a long floor, and a scrolling camera or screen wrap, are recommended to observe the player character for a longer time) 
2. Create a _KinematicBody2D_, then add a _Sprite_ and _CollisionShape2D_ as children
3. Add this script to the _KinematicBody2D_
(It turns the body into a player which falls with gravity,
and has the ability to jump but Not the ability to run):
```
extends KinematicBody2D


const UP_DIRECTION = Vector2(0,-1)
var motion = Vector2.ZERO
	#Making this 2 standalone variables, motion_x and motion_y,
	#doesn't change anything. I have tried.


func _physics_process(_delta):
	gravity()

	to_jump()

	move_and_slide(motion, UP_DIRECTION)

	print( is_on_floor() ) #This line makes it much easier to verify the bug


const GRAVITY = 200

func gravity():
	if is_on_floor():	motion.y = 0
	else:	            motion.y += GRAVITY


var JUMP_FORCE = -2000

func to_jump():
	if Input.is_action_just_pressed("jump"):
		if is_on_floor():	motion.y = JUMP_FORCE
```

4. Extend the Script (Add the ability to Run):
```
extends KinematicBody2D


[...]
var motion = Vector2.ZERO
	#[...]


const RUN_SPEED = 800

func _physics_process(_delta):
	#The order of the lines in the function actually doesn't matter.
	#The bug happens either way.
	
	gravity()
	
	motion.x = RUN_SPEED
	
	to_jump()
	
	[...]
[...]
```

---

**Minimal reproduction project:** [is_on_floor().zip](https://github.com/godotengine/godot/files/5409822/is_on_floor.zip)

**Comment by Sosasees** [comment] 2020-10-20 16:02
Really Fast, I managed to fix the bug in my own project with [advance from TwistedTwigleg on the Forums](https://godotforums.org/discussion/comment/42864/#Comment_42864).
But this doesn't necessarily mean that it's fixed in the engine itself.

I personally think that actually fixing this is not the only viable strategy, but making it more well-known is also very viable since it could be very easy for the game creator to avoid when ze's aware of this.

**Comment by rcorre** [comment] 2020-10-22 12:46
Looking at the forum post, I see @TwistedTwigleg said:

> What is strange with this, in my opinion, is that jumping even works with this solution! I thought move_and_slide_with_snap made jumping hard because the snapping code would force the character to stick to the ground, but I guess this is not the case.

 I would have expected this as well. Are these docs no longer accurate? https://docs.godotengine.org/en/stable/classes/class_kinematicbody.html#class-kinematicbody-method-move-and-slide-with-snap:

> As long as the snap vector is in contact with the ground, the body will remain attached to the surface. This means you must disable snap in order to jump, for example. You can do this by setting snap to (0, 0, 0) or by using move_and_slide instead.

**Comment by madmiraal** [comment] 2020-10-23 12:04
The "bug" is that `is_on_floor()` returns true when there is no motion. `is_on_floor()` should only return `true` if the `KinematicBody` collided with a floor in the last call to `move_and_slide` or `move_and_slide_with_snap()` The description in the documentation has been recently updated to make this clearer: #42696.

As explained by @TwistedTwigleg, to ensure `is_on_floor()` consistently returns `true`, there needs to be a downward motion into the floor on every call to `move_and_slide()` or use `move_and_slide_with_snap()`.

> What is strange with this, in my opinion, is that jumping even works with this solution! I thought move_and_slide_with_snap made jumping hard because the snapping code would force the character to stick to the ground, but I guess this is not the case.

The snap suggested is in the wrong direction. The snap vector should point down. So it's not actually snapping, it's just coincidentally colliding with the floor, for the same reason it collides with the floor when there is no motion.

However, I put "bug" in inverted commas, because the user expectation is that if the `KinematicBody` was on the floor, and there is no motion, that `is_on_floor()` should continue to return `true` as it does now. "It's not a bug, it's a feature." ;-)

Closing, because this is not a bug, and the documentation has already been updated.

**Closed by madmiraal** 2020-10-23 12:04 UTC
Labels: bug, topic:physics
