### ISSUE TITLE
NavigationPolygon in a NavigationRegion2D opens the 3D settings

### ISSUE THREAD

**Issue by IfgiU** [godotengine/godot#89342] opened 2024-03-10 00:03 UTC
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Linux Mint 21.2 (Victoria) - X11 - GLES3 (Compatibility) - AMD Radeon Vega 10 Graphics (raven, LLVM 15.0.7, DRM 3.42, 5.15.0-94-generic) () - AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

When creating a new NavigationPolygon inside of a NavigationRegion2D and selecting the Parsed Collision Masks, the settings for 3D open up instead of 2D.
Demonstration video:

https://github.com/godotengine/godot/assets/78791908/3ae117fb-d0a7-4895-a5a3-d0f27ea5a0e8

### Steps to reproduce

1. Create a new NavigationRegion2D.
2. In the inspector window, click on Navigation Polygon and create a new one.
3. Open the settings of the newly created NavigationPolygon by clicking on it again.
4. Expand the Geometry entry.
5. Under "Parsed Collision Mask" click on the three dots.
6. Click on "Edit Layer Names"
7. Even though we're creating a NavigationRegion2D, the settings for the 3D-Physics open.

### Minimal reproduction project (MRP)

N/A

**Comment by smix8** [comment] 2024-03-10 02:01
Hi, thanks for reporting. This was already fixed in master with PR https://github.com/godotengine/godot/pull/88156.

**Comment by akien-mga** [comment] 2024-03-10 10:35
Closing as duplicate of https://github.com/godotengine/godot/issues/88154, the fix will be included in 4.2.2.

**Closed by akien-mga** 2024-03-10 10:35 UTC
Labels: topic:navigation
