### ISSUE TITLE
Spinner indicates constant redraw when "Caret Blink" is on

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6167] opened 2016-08-16 09:16 UTC
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
When "Caret Blink" option is on, spinner indicates constant redraw (not only in script editor window).

**Steps to reproduce:**
1. Go to settings.
2. Enable "Caret Blink".
3. Switch do "2D".
4. Look to spinner. 

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-08-16 09:29
Duplicate of the now-closed #5100, should have been fixed by @Paulb23 in #5107

**Comment by Paulb23** [comment] 2016-08-16 13:03
This is expected as #5328 adds caret blink to `line edit`, sharing the same setting.

**Comment by Zylann** [comment] 2016-08-17 08:31
I have the same thing, but with particles in the scene, even if the editor is in script mode.

**Comment by neikeq** [comment] 2016-08-17 14:24
I have constant redraw too, but I am not sure if it comes from caret blink. The redraw delay is slower than caret blink's delay.

**Closed** 2016-11-06 16:16 UTC
Labels: bug, topic:editor
