### ISSUE TITLE
Character " ď " in filename when exporting for android. Apk file cannot be installed

### ISSUE THREAD

**Issue by BastionInCzech** [godotengine/godot#41016] opened 2020-08-04 09:10 UTC
Version 3.2 for Ubuntu 20.20

Added a loď.png file which contained " ď " character in filename. Exporting for android and then manually installing using adb install returned:
`<pre>adb: failed to install android.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1712501736.tmp/base.apk: File assets/.import/loď.png-e8bb301e9075ab97686d1e3642e772f8.stex in manifest does not exist`

Direct export (using the android button in godot) returned a Load Error: Could not install to device

When i renamed this file to lod it started working as intended.
I am aware that this may be due to limitations of android but I think there should be a warning or something. 

**Steps to reproduce:**
Create a new project.
Add a file with a special character like " ď " (I haven't tested any other).
Try to export for android

 

**Minimal reproduction project:**

[Asteroids.zip](https://github.com/godotengine/godot/files/5021167/Asteroids.zip)

**Comment by Calinou** [comment] 2020-08-04 09:27
Duplicate of #18222.

**Closed by Calinou** 2020-08-04 09:27 UTC
