### ISSUE TITLE
Color picker eyedropper not working

### ISSUE THREAD

**Issue by OlliO6** [godotengine/godot#70020] opened 2022-12-13 16:46 UTC
### Godot version

4 beta 8 mono (aslo in beta 7 and maybe earlier but not in 3.x)

### System information

Windows 11

### Issue description

When i try to pick a color using the pipette picker thing, it does nothing.

![GodotColorPickerBug](https://user-images.githubusercontent.com/104021024/207392439-5705e510-25e3-47f1-b6aa-27e049baad74.gif)

### Steps to reproduce

Open  a color picker e.g. `CanvasItem.modulate` and press the pipette button to the left of the previous color field.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-13 16:48
It doesn't seem to work on my end either on 4.0.beta8 (Linux).

**Comment by KoBeWi** [comment] 2022-12-13 17:03
Seems like duplicate of #68979, but it was Windows-only 🤔

**Comment by pegasusearl** [comment] 2022-12-26 12:26
I'm not sure if this is related, I got **similar but different** bug on **linux** regarding color picker. The color picker **do pick color**. But it **didn't apply** the color to the settings. So I have to slightly change the value to apply the color that just got picked.

Manjaro Linux x86_64, Kernel: 5.15.78-1-MANJARO, NVIDIA GeForce GTX 1650
v4.0.beta10.official [d0398f62f]

https://user-images.githubusercontent.com/23167087/209548685-4314d3a8-6590-46ce-a40d-d219589fe1f1.mp4

**Comment by Shadetheartist** [comment] 2023-01-11 17:45
This is still going on in the current build, i think the color is being set in the color panel, but not actually propagating out and updating what it needs to. If you just nudge the picked value with one of the sliders it will fix itself. So probably we just need to call an update function after selecting the color with the color picker.

**Comment by Flavelius** [comment] 2023-01-18 17:00
This seems to be still an issue in beta13 (it is for me), and moving some sliders a tiny bit doesn't auto-adjust the rest for me as in the described workaround.

**Comment by andersmmg** [comment] 2023-08-14 14:53
For me, clicking the picker button sets the color gradients selector location to black, but the actual set color doesn't change until I click. Once I do, it just always selects the color black. This is on v4.1.1.stable.mono.official [bd6af8e0e]

**Comment by KoBeWi** [comment] 2023-11-13 13:46
This should've been fixed by #74962

**Closed by KoBeWi** 2023-11-13 13:46 UTC
Labels: bug, confirmed, regression, topic:gui
