### ISSUE TITLE
Enabling SDFGI causes Condition "!light_storage->owns_light_instance(light_instance)" is true. Continuing.

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#67806] opened 2022-10-23 15:24 UTC
### Godot version

4.0beta3

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

Godot keeps outputting:

Condition "!light_storage->owns_light_instance(light_instance)" is true. Continuing.

![image](https://user-images.githubusercontent.com/15805689/197400698-4d4d3ec3-0424-42f5-9faa-9d85d537720a.png)

### Steps to reproduce

Turn on SDFGI and at some point it will throw errors until Godot is closed and reopened.

**Comment by Calinou** [comment] 2022-10-23 15:28
Duplicate of https://github.com/godotengine/godot/issues/57840.

**Closed by Calinou** 2022-10-23 15:28 UTC
