### ISSUE TITLE
[3.0 Alpha] Viewport get broken after click on mesh(res) in inspector.

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#11634] opened 2017-09-27 14:27 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 Alpha build from 25.09.2017 Windows 10 GTX 550Ti

**Issue description:**
Viewport get broken after click on mesh(res) in inspector.
![pic](https://user-images.githubusercontent.com/6241034/30918634-cde7db80-a3a7-11e7-8135-aa3e8f49341c.png)

**Steps to reproduce:**
1.Add mesh node.
2.Add any mesh.
3.Click on mesh resource.
4.If scale left or right toolbar all back to normal.

**Comment by groud** [comment] 2017-09-27 14:32
Duplicate of #11266

**Closed by groud** 2017-09-27 14:32 UTC
