### ISSUE TITLE
Allow documentation of exported script properties

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#10137] opened 2017-08-07 05:41 UTC
Often script properties are supposed to be edited by artists (or, in general, not by the author of the script) and a tooltip explaining their meaning would be helpful. But it seems currently Godot only supports tooltips for builtin properties documented in `classes.xml`. It should be easy to expand `PropertyInfo` with documentation field which could be settable from GDScript or other bindings.

**Comment by Zylann** [comment] 2017-08-07 09:54
Duplicate of https://github.com/godotengine/godot/issues/6204

**Closed** 2017-08-07 09:57 UTC
Labels: archived
