### ISSUE TITLE
bug editor

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#53037] opened 2021-09-24 22:56 UTC
### Godot version

3.3 stable / 3.4 beta 5 / v4.0.dev.custom_build.21775f81a

### System information

windows 10 , gt 730

### Issue description

https://user-images.githubusercontent.com/49615968/134747408-645821d0-841b-4039-b5c0-e76688d37660.mp4

### Steps to reproduce

.......

### Minimal reproduction project

......

**Comment by pycbouh** [comment] 2021-09-24 23:37
Duplicate of https://github.com/godotengine/godot/issues/31133.

**Closed by pycbouh** 2021-09-24 23:37 UTC
