### ISSUE TITLE
Small Bug: When attempting to load resource using the icon in animation editor, the open button is not highlighted (cannot be clicked), double clicking the file still works, as does dragging the image into the editor

### ISSUE THREAD

**Issue by MadOgre** [godotengine/godot#16552] opened 2018-02-11 04:24 UTC
![screenshot](https://user-images.githubusercontent.com/2278723/36069526-81117ece-0eb9-11e8-99be-5a4e23f0aee7.png)

**Comment by Noshyaar** [comment] 2018-02-11 10:37
Duplicate of #16231, Fixed by #16251

**Closed by Noshyaar** 2018-02-11 10:37 UTC
