### ISSUE TITLE
Depth texture imported in various compression modes results in a crash if "DeepParallax" mode is enabled

### ISSUE THREAD

**Issue by TheMoye** [godotengine/godot#39161] opened 2020-05-30 07:56 UTC
**Godot version:**
v3.2.1.stable.official and v3.2.2.beta3.official

**OS/device including version:**
Windows 10 Pro 64 bits Version 1909 (18363.836)
NVidia GeForce RTX 2080, NVidia Studio Driver v442.92, GLES3

**Issue description:**
Displaying a scene containing an object whose material has a depth texture in various compression modes when the DeepParallax option is activated causes a Godot crash.
No crash when the DeepParallax option is disabled, regardless of the compression mode chosen and its quality. 

Enabling DeepParallax : 
- Crash when the compression mode is set to "Uncompressed" at the opening of the scene. 
- Do not crash in "VideoRam" compression mode, no matter the quality.
- Crash in "Lossy" compression mode if the scene is displayed in the editor when reimporting the texture.
- Crash in "Lossless" compression mode, at the opening of the scene.

Attached are the normal and depth textures used for this test.

[Depth_and_Normal_maps.zip](https://github.com/godotengine/godot/files/4705288/Depth_and_Normal_maps.zip)

**Comment by Calinou** [comment] 2020-06-02 21:12
I can't reproduce this on Godot 3.2.1 (GeForce GTX 1080, NVIDIA 440.82, Fedora 31).

Minimal reproduction project: [test_deep_parallax_crash.zip](https://github.com/godotengine/godot/files/4719730/test_deep_parallax_crash.zip)

**Comment by TheMoye** [comment] 2020-06-03 05:34
Hi Calinou,

I can't reproduce the issue with your project on Windows either.
Maybe it's coming from somewhere else?

I attach a minimal project where the crash happens : 
[Dummy2.zip](https://github.com/godotengine/godot/files/4721202/Dummy2.zip)

Dragging the texture **TestPente10_OK_Height.png** in the texture parameter of the **pente.material** when the **pente.res** scene is displayed in the editor is enough to make it crash for me.
If I remember, I'll test it on Debian.

**Comment by Leocesar3D** [comment] 2021-05-19 06:26
I can attest that it happens in my game project too. When I enable the Deep Parallax option in the Depth section of my Spatial Material and run the game on the editor it hangs and crashes reporting no errors. With the Deep Parallax disabled there is no crashing or hanging.
I am using a GeForce GTX 1070 on Windows 10.

**Comment by Calinou** [comment] 2021-05-19 14:45
This is likely due to an infinite loop happening in the shader, but I haven't managed to reproduce this with Deep Parallax yet.

**Comment by Calinou** [comment] 2022-11-04 22:12
@TheMoye @Leocesar3D Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment] 2022-11-04 22:17
I've tested this again on 3.5.1 (Linux, Radeon RX 6900 XT) and can't reproduce this.

Also, I noticed that the test project has contact shadows enabled. These are prone to causing GPU freezes, especially on lower-end GPUs. As such, contact shadows have been removed in 4.0.beta and their use is not recommended in 3.x: https://github.com/godotengine/godot/pull/35316

Please test this again with the **Contact** property of the DirectionalLight node set to its default value of `0.0`.

**Comment by Leocesar3D** [comment] 2022-11-05 01:56
I’ve updated my project to Godot 3.5.1 and the Deep Parallax shader effect is working as it should. No more freezes or crashes.

**Comment by Calinou** [comment] 2022-11-05 17:16
Alright, closing then.

**Closed by Calinou** 2022-11-05 17:16 UTC
Labels: bug, topic:editor, needs testing, topic:import, crash
