### ISSUE TITLE
RichTextLabel's meta_underlined property controls cursor shape

### ISSUE THREAD

**Issue by George--K** [godotengine/godot#42249] opened 2020-09-22 15:19 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
When setting the meta_underlined property of RichTextLabel to false the cursor shape when hovering over a meta tag changes from CURSOR_POINTING_HAND to CURSOR_ARROW. This behaviour can't be overriden using set_default_cursor_shape and hover signals.

**Steps to reproduce:**
1. Download the attached project
2. Run
3. Mouse over "meta text here"
4. Try checking and unchecking the "Meta Underlined" property of RichTextLabel
5. Notice the signals attached to the hover signals with set_default_cursor_shape

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/5262386/example.zip)

Note:
This is entirely because of these lines in rich_text_label.cpp get_cursor_shape method
`if (!underline_meta) {`
`	return CURSOR_ARROW;`
`}`
This is at the very least unintuitive and not what the documentation says about this property at all. ("If true, the label underlines meta tags such as [url]{text}[/url].") Also I'm not sure if the issue is set_default_cursor_shape or the fact that get_cursor_shape hard sets the cursor to CURSOR_ARROW, but the fact that this behaviour can't be changed via the signals that would be most logical to use is awkward to deal with.

**Comment by Calinou** [comment] 2020-10-01 22:41
Out of curiosity, why don't you want to use the pointing hand cursor when hovering over a meta tag?

This seems to be a useful feature for accessibility purposes.

**Comment by George--K** [comment] 2020-10-02 15:37
> Out of curiosity, why don't you want to use the pointing hand cursor when hovering over a meta tag? This seems to be a useful feature for accessibility purposes.

I do want to use it. Which is exactly why it frustrates me that I can't do that without enabling underlining. That's why I was trying to change cursor shape manually via events, but it doesn't seem to actually do anything.

**Comment by Calinou** [comment] 2020-10-02 15:42
@George--K Right, I misunderstood your original report.

**Comment by akien-mga** [comment] 2021-10-21 09:58
Duplicate of #20719, fixed by #52067.

**Closed by akien-mga** 2021-10-21 09:58 UTC
Labels: topic:gui
