### ISSUE TITLE
OpenGL error: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL. [nvidia, Windows]

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9915] opened 2017-07-27 13:45 UTC
Godot 3.0 alpha1 official
Windows 10 64 bits
nVidia

I got this error a little while after the import process, and it started spamming every frame when I "Open anyways" an obj that was imported as a scene:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.
   At: drivers\gles3\rasterizer_gles3.cpp:123
mesege
```

It started spamming only after a few attempts to open obj files that were imported as scenes (same project as in #9910)

**Comment by reduz** [comment] 2017-08-22 13:05
more reproduction conditions appreciated, nothing can be done with this as is

**Comment by Zylann** [comment] 2017-08-22 21:18
I tried again the following:
1) Create a project
2) Export a cube from Blender in it as .obj
3) Double-click on the .obj in Godot and click "Open anyways"

Then I saw the error.

The problem is... I tried again 5 times in various ways, it doesn't repro again. It's either random or very specific.

**Comment by reduz** [comment] 2017-10-03 21:18
this maaaay be fixed since my last commit

**Comment by akien-mga** [comment] 2018-01-09 16:20
Can you still reproduce this one @Zylann?

**Comment by Zylann** [comment] 2018-01-09 20:43
I gave it a few minutes importing an OBJ, and had no error apart from this:
```
ERROR: Node::set_name: Condition ' name == "" ' is true.
   At: scene\main\node.cpp:1144
```
I fiddled a little bit and got to a point where I reimported the mesh and.... waited for 5 minutes (the mesh usually imports in about 10 seconds). I'll see if I can repro that other thing later.

**Comment by akien-mga** [comment] 2018-01-16 10:21
Sounds like unrelated issues, so let's close this one and you can open a new one for the `name == ""` issue as well as the import delay.

**Closed by akien-mga** 2018-01-16 10:21 UTC
Labels: bug, platform:windows, topic:rendering

**Comment by Zylann** [comment] 2018-01-16 10:24
The mesh importing time is probably not a bug. It is just really dead slow in debug (by a ratio of *100*).
