### ISSUE TITLE
2D: isometric tile artefacts

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4747] opened 2016-05-22 03:35 UTC
**Operating system or device - Godot version:**
Any (Linux), master

**Issue description** (what happened, and what was expected):
Iso tiles do not match - have gaps and artefacts.
You can see it on https://youtu.be/hQXrL7tHp9s (use max resolution) or run isometric_light demo
for best effect
**Steps to reproduce:**
Look at isometric_light demo

**Link to minimal example project** (optional but very welcome):
Use isometric_light demo

p.s. @akien-mga Yes, 2D does have bugs too. If you say it is because of me, I'll throw a brick at you.
...
p.p.s. Just kidding.
btw, if I use square tyles RPG-maker style, will I have this too, or should I avoid tilemaps completely
and use sprites and ad-hoc script to generate scenery?

**Comment by slapin** [comment] 2016-05-22 05:18
In the following image you can see artefacts in editor:

![tilemap_artefacts_editor](https://cloud.githubusercontent.com/assets/6099/15452365/7ddf64c8-1ff5-11e6-8c2b-be7159487a8f.png)

In game they can be seen too generally when map moves, but it is hard to make video showing that
and hard to catch moment to do screenshot.
Filtering is disabled for the tiles.

**Comment by slapin** [comment] 2016-05-22 06:49
the following woodo makes artefacts go away with filtering disabled (but makes tiles look bad)
This means the artefacts are caused by transparent pixels within tiles' edge even when made
sharp. Upscaling the tile makes edge out of region, which makes tilemap happy.
Strangely, bottom and top alpha-transparency doesn't produce artefacts. Any ideas?

```python
def scale(s):
    flist = glob.glob(s)
    print("List:", flist)
    for f in flist:
        os.system("convert %s -scale %dx%d\! %s.scaled.png" %(f, szx + 4, szy + 0, f))
        os.system("convert %s.scaled.png -crop %dx%d+2+0\! %s.scaled.png" %(f, szx, szy, f))
        os.system("convert %s -scale %dx%d\! %s.scaled2.png" %(f, szx + 4, szy + 0, f))
        os.system("convert %s.scaled2.png -adaptive-sharpen 1x1.6 %s.scaled2.png" %(f,  f))
        os.system("convert %s.scaled2.png -geometry +2+0 %s.scaled.png -composite %s.scaled.png" %(f, f, f))
```

**Comment by slapin** [comment] 2016-05-23 21:32
[Wall1.zip](https://github.com/godotengine/godot/files/278305/Wall1.zip)

**Comment by eska014** [comment] 2016-05-23 22:32
Closing this as duplicate of #1682

**Closed by eska014** 2016-05-23 22:32 UTC
Labels: bug, topic:rendering
