### ISSUE TITLE
Last RC mono release RC3 broke my project with a bunch of errors

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#41060] opened 2020-08-06 04:03 UTC
**Godot version:**

Godot 3.2.3 RC3

**OS/device including version:**

Windows 10 /  Android Project 

**Issue description:**

After Switching to the last RC3 release i got these errors in my project , i have no clue about it , i am mixing between C# and gdscript .
![image](https://user-images.githubusercontent.com/27586088/89489171-8690ab80-d7b2-11ea-920e-cd40e14156b8.png)

**Steps to reproduce:**
My project is working fine on the previous Rc2 version 

**Minimal reproduction project:**

i will try to test each issue after getting some thoughts about this

**Comment by mbrlabs** [comment] 2020-08-06 07:03
That's probably related to #40991

**Comment by ICatRegister** [comment] 2020-08-06 14:06
I have exactly the same issue with classical build

**Comment by akien-mga** [comment] 2020-08-17 09:18
Duplicate of #40991.

**Closed by akien-mga** 2020-08-17 09:18 UTC
Labels: bug, regression, topic:mono
