### ISSUE TITLE
Cannot call function on custom Resource (Nonexistent function)

### ISSUE THREAD

**Issue by co42** [godotengine/godot#23456] opened 2018-11-02 14:38 UTC
**Godot version:**

`master` `a3501c096f32506bf2262e36a302bf65f4ad0f4a`

**OS/device including version:**

Linux

**Issue description:**

I can't call a function on a custom loaded resource.

MyResource.gd
```
extends Resource

export(int) var value = 42

func twice():
    return value * 2
```

SaveLoad.gd
```
tool
extends EditorScript

const MyResource = preload("res://MyResource.gd")

func _run():
    var my_resource = MyResource.new()
    print(my_resource.twice())
    ResourceSaver.save("res://my_resource.tres", my_resource)
    var my_resource_loaded = ResourceLoader.load("res://my_resource.tres")
    print(my_resource_loaded.value)
    print(my_resource_loaded.twice())
```

Output
```
84
42
 res://SaveLoad.gd:12 - Invalid call. Nonexistent function 'twice' in base 'Resource (MyResource.gd)'.
```

**Steps to reproduce:**
Run `SaveLoad.gd`.

**Minimal reproduction project:**
[resource-issue.zip](https://github.com/godotengine/godot/files/2542859/resource-issue.zip)

**Comment by bojidar-bg** [comment] 2018-11-08 13:40
Seems like even doing this is enough to trigger the bug:
```gdscript
# ...
func _run():
    var my_resource = Resource.new()
    my_resource.script = MyResource
    print(my_resource.twice()) # --> Invalid call
```

**Comment by IllusiveS** [comment] 2018-11-16 22:03
I believe the problem is with all script-inherited classes, i have a script inheriting from spatial in an EditorScript and the issue also occures there.

**Comment by IllusiveS** [comment] 2018-11-19 00:00
@bojidar-bg 
After some poking around i think more accurate description of this issue is that objects instanced in EditorScript's _run do not have their script class set?
Not sure how to word it but calling get_class() returns string with base type.

**Comment by bojidar-bg** [comment] 2018-11-19 11:07
Ahh, try putting in a tool-mode script. It likely be from the fact that non-tool scripts get instanced as placeholders when setting them in the editor.
If that is the case, the bug is that the real script gets instanced when calling `MyResource.new()`.

**Comment by earlroxas13** [comment] 2019-06-13 08:48
Hi guys,
I discover this bug myself awhile ago when creating plugin for my game.
So, here i'm gonna add some detail to this bug:
1. Aside from functions you cannot access normal variable too. By normal variable, i mean is class variable that you dont export, so the only thing that can be accessed from loaded resource is exported variables.
2. This also happen in plugin script. It's very annoying that my Custom Resource cannot be accessed in my plugin, even when It can be accessed on game runtime.
OK, that's what i discover today.
Hope it can help to fix this bug.

**Comment by bojidar-bg** [comment] 2019-06-13 17:32
@earlroxas13 Did you try making the resource script a `tool` script?

**Comment by earlroxas13** [comment] 2019-06-14 02:12
@bojidar-bg I just tried putting tool in my Custom Resource script, and now all the errors is gone. :)
So making the resource a tool script, is it what it should be or is it just a temporary solution/workaround?

**Comment by bojidar-bg** [comment] 2019-06-14 08:34
It is the way it is supposed to be. Non-tool scripts should be unusable in the editor.
That being said, their __exported__ variables should be usable even when not set as `tool` scripts.

**Comment by KoBeWi** [comment] 2020-07-28 23:37
So this is not a bug. https://github.com/godotengine/godot/issues/23456#issuecomment-501611267 says that you can access exported variables, which is correct. Non-exported variables are part of script internal logic and they can't be accessed in non-tool mode in the editor. Closing.

**Closed by KoBeWi** 2020-07-28 23:37 UTC
Labels: bug, topic:core, topic:gdscript
