### ISSUE TITLE
Custom InputMap actions don't work in exported project

### ISSUE THREAD

**Issue by quinnyo** [godotengine/godot#9250] opened 2017-06-18 14:41 UTC
**Operating system or device - Godot version:**
3.0 master (33bf180), Windows 10

**Issue description:**
Any actions I create in the editor have no InputEvents associated with them in the exported project. The result being that none of the actions are ever triggered. You can verify the problem with InputMap.get_action_list(...)
The built-in actions (ui_* stuff) work fine.

Have I missed something crucial about setting up actions?

Note that when launching from the editor - or a binary in the project folder - the actions work fine.
This is not tied to debug/release/tools builds, but seemingly the exported data (.cfb?) in the .pck file (at write or read time?).

example project: 
[action_test.zip](https://github.com/godotengine/godot/files/1083140/action_test.zip)

Try running from editor and exporting and running.
Press space ("action1") and the up key ("ui_up") and see the counters change.
action1 works from editor/project but not when exported
The top line shows the results of get_action_list (empty when exported).

**Comment by akien-mga** [comment] 2017-07-24 17:46
Duplicate of #9472.

**Closed by akien-mga** 2017-07-24 17:46 UTC
Labels: bug, topic:core
