### ISSUE TITLE
[v3.2.4.rc2] SceneTreeEditor::_update_tree called with wrong arguments

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#46344] opened 2021-02-23 12:10 UTC
**Godot version:** Godot Engine v3.2.4.rc2.official

**OS/device including version:** Windows 10

**Issue description:** Setting the `Shape` of `CollisionShape2D` in the editor throws the following error exactly 9 times:

`core/object.cpp:1257 - Error calling method from signal 'timeout': 'SceneTreeEditor::_update_tree': Method expected 1 arguments, but called with 0..`

**Steps to reproduce:**

1. Add a `CollisionShape2D` to the scene;
2. Set the `Shape` property in the editor;
3. The error will arise.

**Minimal reproduction project:** 
[create_shape_tree_update.zip](https://github.com/godotengine/godot/files/6028766/create_shape_tree_update.zip)

The project contains a main scene with a lot of `CollisionShape2D` to test, setting the `Shape` of any of them will cause the error.

**Comment by qarmin** [comment] 2021-02-23 12:33
Duplicate of https://github.com/godotengine/godot/issues/45938, already fixed

**Closed by qarmin** 2021-02-23 12:33 UTC
