### ISSUE TITLE
3.0 Shader Language: increments (++) does not work

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10661] opened 2017-08-26 17:15 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
windows 64, 73132c9, nvidia

i was trying to implement blur shader today. editor crashed multiple times while i was writing this. and finally it doesn't work (but works on shadertoy for example)

putting this on the Sprite (with standard icon as texture) and uncommenting last line will crash the editor. and there is while instead of for, because fors just don't work (known issue tho). but why is it crashing the editor??? nothing is written into the console, so i have no idea what is happening.

```glsl
shader_type canvas_item;

float SCurve (float x) {
    x = x * 2.0 - 1.0;
    return -x * abs(x) * 0.5 + x + 0.5;
    //return dot(vec3(-x, 2.0, 1.0 ),vec3(abs(x), x, 1.0)) * 0.5; // possibly faster version
}

vec4 BlurH (sampler2D source, vec2 size, vec2 uv, float radius) {
    if (radius >= 1.0) {
        vec4 A = vec4(0.0); 
        vec4 C = vec4(0.0); 
        float width = 1.0 / size.x;
        float divisor = 0.0; 
        float weight = 0.0;
        float radiusMultiplier = 1.0 / radius;
        float x = -radius;
        while (x <= radius) {
            A = texture(source, uv + vec2(x * width, 0.0));
            weight = SCurve(1.0 - (abs(x) * radiusMultiplier)); 
            C += A * weight; 
            divisor += weight;
            x++;
        }
        return vec4(C.r / divisor, C.g / divisor, C.b / divisor, 1.0);
    }
    return texture(source, uv);
}

void fragment() {
    //COLOR = BlurH(TEXTURE, vec2(64.0, 64.0), UV, 20.0); //crashes even with 2.0 radius
}
```

**Comment by Zylann** [comment] 2017-08-26 20:01
Is it freezing or crashing with "doesn't respond"? Because, an insanely expensive shader can also look like a crash since it would slow down the editor enough to be frozen :p

**Comment by reduz** [comment] 2017-08-26 20:09
leaving the crash aside (need to check it)..

I was thinking of adding an option to the texture importer plugin to
generate gaussian blurred mipmaps, this way you can blur sprites easily by
just using textureLod()

**Comment by novemberist** [comment] 2017-08-26 20:28
Linux, https://github.com/godotengine/godot/commit/53c0010932f9c1becb63c16243f3a00ede359989, Intel HD4000 here.

I tried your shader code and uncommented the last line but it doesn't crash or slow down the editor for me. However, the only thing that happens to the icon sprite is that it becomes invisible...

**Comment by curly-brace** [comment] 2017-08-27 06:35
it is not expensive, because it crashes with 4 iterations. on windows 10 it iw like windows goes black for a few seconds and then appears standard window with running progressbar that tells that godot engine stopped working and asks whether i want to close it or debug.

**Comment by Zireael07** [comment] 2017-08-27 08:41
Looks like you have a driver or system issue @curly-brace ..

**Comment by Smellyhobo101** [comment] 2017-08-28 15:09
Win7 64 bit, GTX 770, driver 385.41. This shader crashed godot and my graphics driver.

**Comment by curly-brace** [comment] 2017-08-28 15:24
update here. i've found out the minimal shader code that will crash the editor:
```glsl
shader_type canvas_item;

void fragment() {
    float c = texture(TEXTURE, UV).r;
    float i = 0.0;
    while (i < 3.0) {
        c += texture(TEXTURE, UV).r;
    }
}
```

**Comment by groud** [comment] 2017-08-28 15:28
Lol, then this is probably a duplicate of #10560, as you're creating an infinite loop... ^^

**Comment by curly-brace** [comment] 2017-08-28 15:31
@groud oh i've forgot about increment, lol. but even with increment it crashes (tested it now)

**Comment by groud** [comment] 2017-08-28 15:32
What about with `i = i+1` ?

**Comment by curly-brace** [comment] 2017-08-28 15:37
@groud yeah. works with i+=1. so there are two issues with loops - deadloop problem and ++ problem. mine here concerns increment.

**Comment by groud** [comment] 2017-08-28 15:38
> @groud yeah. works with i+=1. so there are two issues with loops - deadloop problem and ++ problem. mine here concerns increment.

Awesome, could you rename the issue with something like "++ operators in shader crashes the editor" ?

**Comment by curly-brace** [comment] 2017-08-28 15:41
so the minimal code is now
```glsl
shader_type canvas_item;

void fragment() {
	float i = 0;
	i++;
}
```

**Comment by akien-mga** [comment] 2017-08-28 15:43
It's the same cause as #10687 I think, #10590 broke operators. @hpvb was looking into it.

**Comment by curly-brace** [comment] 2017-08-29 07:14
just found out that preincrement (++x) actually works

**Comment by curly-brace** [comment] 2017-08-29 07:35
actually preincrement does not work, it just does not crash the editor, but shader is invalid and produces white screen.

**Closed** 2017-09-05 18:25 UTC
Labels: bug, topic:editor
