### ISSUE TITLE
Project list is not ordering by favorites

### ISSUE THREAD

**Issue by arturjpv** [godotengine/godot#5906] opened 2016-07-25 19:25 UTC
Mac OSX El Capitan - Godot 2.1 RC.

This could not be a bug... but If I recall correctly, in previous versions, when marking a project in the project list as favorite (with the star) these projects were listed before the other projects. This seems not to be the case now. Even marking a project as favorite is listed last.

To reproduce:
- Create a project
- Add samples project by searching
- Mark the first created project as favorite (the star)
- Quit godot
- Start godot -> The favorite project is not at the top

**Comment by eska014** [comment] 2016-07-25 21:55
Can't reproduce on FreeBSD or Win7

**Comment by vnen** [comment] 2016-07-25 22:02
Try to move the editor settings file elsewhere, so it can be recreated when you open the engine again. Then see if the problem persists. If it is solved by that procedure, you might attach the file here (in a ZIP) so the bug can be tested.

**Comment by arturjpv** [comment] 2016-07-26 20:04
Ok, tried to analyze the steps to reproduce the bug.

You don't need a new project to make it happen. Just with the scanned samples is ok. New instructions to try to reproduce the problem:

- Open godot
- Select one project as favorite (the star)
- Open that project
- Quit godot
- Start godot

The important step I missed is opening the project.

**Comment by vnen** [comment] 2016-07-26 20:27
Are you sure the projects are still marked as favorite? If not, this is a re-occurrence of #5469.

**Comment by arturjpv** [comment] 2016-07-26 21:20
You are right. My fault again explaining myself. They are not marked as favorites after that. It could be the same case.

**Comment by akien-mga** [comment] 2016-07-29 05:57
I still can't reproduce on Linux using the above steps. Whether I close the project manager or open the project, the favorites are properly saved and show on top next time I run the project manager.

**Comment by arturjpv** [comment] 2016-07-30 17:00
Let me share a small video replicating the problem.

https://dl.dropboxusercontent.com/u/7549551/GodotFavoriteList.mov

I will remove it in the future, but for now is the fast way to show the problem.

vnen asked for the settings file if this was persisting. Which file do you mean? I can share it if you think it can help.

**Comment by vnen** [comment] 2016-07-30 23:29
@arturjpv Yes, the editor settings file. It's on `~/.godot/editor_settings.tres` (or some similar folder on you user directory, I'm not sure where for OSX). Moving that file out of the folder will force Godot to recreate it, which might solve the issue and the old file might be a good asset for debugging.

**Comment by arturjpv** [comment] 2016-07-31 09:45
@vnen, unfortunately the problem persists even removing the settings file and recreating it.
I will try to find time to compile godot and debug the issue.

**Comment by vnen** [comment] 2016-08-04 21:18
May be a race condition then: if you favorite and open the project too fast, it doesn't have time to update the file before the project manager has a chance to save the settings file.

**Comment by arturjpv** [comment] 2016-08-04 22:00
No, it doesn't look like a race condition. I did that debug session waiting for the favorite entry to be stored in the file before opening the project.

The favorite entry seems to be lost when the opened project saves the settings again to store new things once opened.

**Comment by arturjpv** [comment] 2017-01-27 19:01
This issue seems solved in the maintenance release 2.1.2

**Closed** 2017-01-27 19:24 UTC
Labels: bug, platform:osx, topic:editor
