### ISSUE TITLE
Crash when trying to auto-complete an internal editor class in the GDscript editor

### ISSUE THREAD

**Issue by JFonS** [godotengine/godot#23323] opened 2018-10-27 14:32 UTC
**Godot version:** 
13582354fd9

**Issue description:**
Godot crashes when trying to auto-complete an internal editor class in the GDscript editor.

Backtrace:
```
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f5875493e00] (??:0)
[2] Map<StringName, int, Comparator<StringName>, DefaultAllocator>::operator[](StringName const&) const (??:0)
[3] /home/jfons/Projects/godot/bin/godot.x11.tools.64.3.0(+0xff9b33) [0x55895437fb33] (??:0)
[4] /home/jfons/Projects/godot/bin/godot.x11.tools.64.3.0(+0xff56b5) [0x55895437b6b5] (??:0)
[5] GDScriptLanguage::complete_code(String const&, String const&, Object*, List<String, DefaultAllocator>*, bool&, String&) (??:0)
[6] ScriptTextEditor::_code_complete_script(String const&, List<String, DefaultAllocator>*, bool&) (??:0)
[7] ScriptTextEditor::_code_complete_scripts(void*, String const&, List<String, DefaultAllocator>*, bool&) (??:0)
[8] CodeTextEditor::_complete_request() (??:0)
[9] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[10] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[11] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[12] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[13] TextEdit::query_code_comple() (??:0)
[14] CodeTextEditor::_code_complete_timer_timeout() (??:0)
[15] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[16] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[17] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[18] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[19] Timer::_notification(int) (??:0)
[20] Timer::_notificationv(int, bool) (??:0)
[21] Object::notification(int, bool) (??:0)
[22] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[23] SceneTree::idle(float) (??:0)
[24] Main::iteration() (??:0)
[25] OS_X11::run() (??:0)
[26] /home/jfons/Projects/godot/bin/godot.x11.tools.64.3.0(main+0xdc) [0x55895429c435] (??:0)
[27] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f5875480223] (??:0)
[28] /home/jfons/Projects/godot/bin/godot.x11.tools.64.3.0(_start+0x2e) [0x55895429c28e] (??:0)
-- END OF BACKTRACE --
```

Seems like the problem is here: https://github.com/godotengine/godot/blob/220f50e790223c7bc63fd3d2ca3327aa6dcc5d3c/modules/gdscript/gdscript_editor.cpp#L1321
Because `p_identifier` is not in the global map, but I don't know much about this part of the engine so I don't think I could fix it.

**Steps to reproduce:**
Edit any GDscript, type "EditorNode", everything works fine. Add a dot "." at the end (like trying to access EditorNode's members), Godot crashes.

**Comment by RandomShaper** [comment] 2018-10-28 02:05
Duplicate of #22914.

**Closed by RandomShaper** 2018-10-28 02:05 UTC
Labels: bug, topic:editor, topic:gdscript
