### ISSUE TITLE
`VIEW` fragment shader built-in is the opposite vector as it should be

### ISSUE THREAD

**Issue by Flarkk** [godotengine/godot#50449] opened 2021-07-14 11:29 UTC
### Godot version

all

### System information

n/a

### Issue description

`VIEW` is currently the unit vector from the fragment to the camera, although the documentation says the opposite.

[Documentation](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/spatial_shader.html#fragment-built-ins) : `in vec3 VIEW | Vector from camera to fragment position (in view space).`

The sample shader code below outputs a blueish quad, which denotes `VIEW` points towards positive Z.
Instead, negative Z may be expected :
```
shader_type spatial;
render_mode unshaded;

void vertex() {
}

void fragment() {
    ALBEDO = VIEW;
}
```
![image](https://user-images.githubusercontent.com/49606622/125614363-80c7bc15-1dab-44cf-88fc-b3ba19d697ba.png)

The fix can be either negating `VIEW`, or changing the documentation.
That said, I assume most people would expect a negated `VIEW`, because the name of the built-in suggests it points towards the view direction.

### Steps to reproduce

-

**Comment by clayjohn** [comment] 2021-07-14 14:32
Duplicate of https://github.com/godotengine/godot-docs/issues/4267

**Closed by clayjohn** 2021-07-14 14:32 UTC
