### ISSUE TITLE
AtlasTextures - Tile StretchMode isnt working

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45700] opened 2021-02-04 11:06 UTC
**Godot version:**
3.2.4 beta 6 mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
When the user create an atlastexture with autoslice, selecting a sprite and then change strech mode to tile (which should tile the sprite) instead it expands the sprite:

![image](https://user-images.githubusercontent.com/58845030/106884238-cb44c300-66bf-11eb-8cd1-9545ae8d47dd.png)

**Steps to reproduce:**
* Create a TextureRect
* Add new AtlasTexture
*  Add the sprite sheet
* set to auto slice
* Select the sprite
* Change StretchMode to Tile

**Comment by lawnjelly** [comment] 2021-02-04 12:52
I don't know about the UI side, but it isn't surprising. GPUs only tend to support tiling over the whole texture, which won't work with an atlas. Unless you jump through hoops and try and do tiling manually in the fragment shader like with ninepatches in GLES3, but that is generally a disaster and not advisable.

You can do this kind of thing with texture arrays instead of atlases. But these are not supported in Godot 3.2, I don't think GLES2 supports them.

So it seems more of a UI issue in that it is giving the impression you can do something, that you can't.

**Comment by nonunknown** [comment] 2021-02-04 13:00
yeah agree, seems to be a feature that can be done, but in reality it cant!

**Comment by hamad-almamari** [comment] 2021-02-07 10:43
Hello you can do that with normal Sprite Node

Just add New Sprite (Can be from Atlas)

Then simply use this shader: (To edit the UV)

```
shader_type canvas_item;

uniform vec2 scale = vec2(1.0, 1.0);
uniform vec2 regionPosition = vec2(0.0, 0.0);  // sub Image position pixel (for atlas: use same as region XY) / for non atlas keep it 0,0
uniform vec2 regionSize = vec2(64., 64.);  // sub Image size pixel 

void fragment() {

	// real size of tuxture in pixels
	vec2 texSize = vec2(1,1) / TEXTURE_PIXEL_SIZE; // TEXTURE_PIXEL_SIZE may be for atlas

    float uv_w =  regionSize.x / texSize.x;
    float uv_h =  regionSize.y / texSize.y;
    float uv_x =  regionPosition.x / texSize.x;
    float uv_y =  1.0 - regionPosition.y / texSize.y -uv_h;
			
	vec2 newUvAtlas = vec2(mod(UV.x * scale.x  , uv_w ) + uv_x  , mod(UV.y * scale.y, uv_h) + uv_y);
			
    COLOR = texture(TEXTURE, newUvAtlas);
}

```
 Thats is :)


![1](https://user-images.githubusercontent.com/18581054/107144004-9c458000-6951-11eb-8df9-306641dfb3c7.PNG)

![2](https://user-images.githubusercontent.com/18581054/107144062-06f6bb80-6952-11eb-80aa-f94e0caec78b.PNG)
![3](https://user-images.githubusercontent.com/18581054/107144064-0a8a4280-6952-11eb-8bda-65a0cf63c4fc.PNG)


I think this Godot also should pass the Region (position + Size) and the scale to the shader code, it will be very helpful, when anyone can use those things without need to write them in the editor. but i think @akien-mga is working to improve the shader system I hope it will make it esiaer to access the proprieties form the shader with out need to do input staff.

**Comment by hamad-almamari** [comment] 2021-02-07 10:57
+ you can use this also with Polygon2D 
is is faster to use this shader than the tilemap. you can play with it.
imagin if Polygon2d just has the curve tool same as Path2d This will be amazing for top down games (easily you can make your levels + performance.
![4](https://user-images.githubusercontent.com/18581054/107144452-b16fde00-6954-11eb-8321-bd5f86b491a1.PNG)

**Comment by lawnjelly** [comment] 2021-02-07 12:36
Just to reiterate, you *can* do such tiling in the fragment shader (this is already done for ninepatches in GLES3, and for some situations when tiling is used without non power of 2 support). The question is more whether we *should* support this, especially at this stage in 3.2 lifetime.

There are two problems to overcome:
* This can run very slowly on some hardware (i.e. some mobile) and kick the GPU into a low precision mode. Just making this available will cause people to use the feature, then they will complain when their game doesn't run properly on certain hardware, and we will get more support issues filed etc.
* As your shader shows, you also need to transfer the region to the shader to enable it to do such tiling. We have to weigh up the cost of this in terms of the benefits versus the complexity of the standard shader, batching (it probably wouldn't be worth batching, so would go via legacy) and extra bug surface and maintenance burden.

If you or anyone wants to make a PR adding the feature it will get looked at - but bear in mind these points will be relevant. You may have more luck with such features for Godot 4.0, where vulkan and texture arrays in GLES3 will be available. Also, as you show, if someone really wants to do this currently, it is possible with a custom shader.

**Comment by Calinou** [comment] 2021-05-18 21:33
Duplicate of https://github.com/godotengine/godot/issues/20472.

**Closed by Calinou** 2021-05-18 21:33 UTC
Labels: topic:2d, topic:editor
