### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by gavriil07** [godotengine/godot#24375] opened 2018-12-15 17:13 UTC
**Godot version:**
Godot 3.1 alpha 3 release

**OS/device including version:**
Windows 10, nVidida gtx 1070

3.0.6 was ok

**Comment by girng** [comment] 2018-12-15 20:13
is this the entire autocomplete feature, or just when writing specific text?

**Comment by timoschwarzer** [comment] 2018-12-16 01:31
Can't confirm. We need more information on when this happens.

**Comment by gavriil07** [comment] 2018-12-16 19:09
Just tried to set the position of a 2D node, when trying to type position the autocomplete does not trigger inside update function, Vector2 for example worked..

**Comment by eon-s** [comment] 2018-12-17 01:35
Is that node on the current selected scene? otherwise the editor does not have a way to know what type of node it is (unless you put it on a typed variable).

**Comment by dreamsComeTrue** [comment] 2018-12-23 20:15
Fun fact:
When you try autocomplete in code like this:
```python
func _ready():
	$Timer.connect("timeout", self, "_on_Timer_timeout") 
	pos| <- cursor here
```

it works flawlessly. But when you mess up indentation in your code, like:
```python
func _ready():
	$Timer.connect("timeout", self, "_on_Timer_timeout") 
pos| <- cursor here
```

autocomplete does not trigger, even when CTRL+Space (which is not an issue in my opinion - Godot tries to parse your script, and when it find it's incorrect indentation, it fails to autcomplete). Is that maybe your case?

**Comment by Chaosus** [comment] 2018-12-27 10:10
@dreamsComeTrue Please create a separate issue about it

@gavriil07 The issue is make up incorrectly. I give you some advices

1. The autocomplete **does** work(but not everywhere), so the topic name should be something like this - "Auto-completion does not work when [reason].
2. Describe the place where it happens in topic header, instead inside discussion.
3. Try use search before creation of new topic, because there is already a bunch of autocompletion issues. 

This issue seems like a duplicate of #22807. Closed.

**Closed by Chaosus** 2018-12-27 10:10 UTC

**Comment by eon-s** [comment] 2018-12-27 11:46
@dreamsComeTrue that is not a bug, if the cursor is out of scope, you won't get autocompletion in any editor.
