### ISSUE TITLE
Changing a slider's value in the inspector prints error in editor if value_changed signal is assigned to a method

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#20058] opened 2018-07-09 09:33 UTC
**Godot version:**
3.0.4 Mono

**OS/device including version:**
KDE Neon

**Issue description:**
If you have a HSlider or VSlider with the `value_changed` signal connected to a method, then changing its value in the editor causes the following error to be printed:
`` core/object.cpp:1202 - Error calling method from signal 'value_changed': 'HSlider(HSlider.gd)::_on_HSlider_value_changed': Method not found.
``

**Steps to reproduce:**
1. Create a HSlider with a script attached and assign a method to its `value_changed` signal.
2. Change the slider's value in the inspector
3. Observe error.

**Comment by akien-mga** [comment] 2018-07-22 15:59
Duplicate of #13070.

**Closed by akien-mga** 2018-07-22 15:59 UTC
