### ISSUE TITLE
All Godot 3.x exports crash when running on iPad Mini 4 with iPadOS 15.7.1

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot#68726] opened 2022-11-16 08:01 UTC
### Godot version

3.x

### System information

iPad Mini 4 Wi-Fi with 128 GB of storage, iPadOS 15.7.1

### Issue description

Might related to #67949

All games made with Godot 3.x crashes when running on iPad Mini 4th generation with iOS 15.7.1 (running fine with earlier iPadOS 14.x) I cannot inspect any of logs/consoles since I don't have Macintosh to debug and submit error information.

### Steps to reproduce

1. Open up Safari or any of browsers.
2. Open up websites with Godot games.
3. Games seem to load up just fine, and immediately crash and web pages repeatedly refresh.

**Comment by akien-mga** [comment] 2022-11-16 08:47
Duplicate of #67949

**Closed by akien-mga** 2022-11-16 08:47 UTC
