### ISSUE TITLE
Ripples and outside setting.

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2419] opened 2015-09-03 19:52 UTC
Do not operate the settings "test_width", "test_height" in the project. At the start of the editor always starts in the resolution of "800x600"
When Scaling picture windows greatly dazzled.

**Comment by bojidar-bg** [comment] 2015-09-09 10:22
duplicate of https://github.com/okamstudio/godot/issues/2426 ?

**Closed** 2015-11-09 12:54 UTC
Labels: archived
