### ISSUE TITLE
YSort companion node

### ISSUE THREAD

**Issue by gusthe** [godotengine/godot#3281] opened 2016-01-08 18:24 UTC
**_Disclaimer**_ : I am not asking for YSort to sort all sub-nodes of it's child nodes. 

Would it be possible to add a new node that would only serve as a container/symbolic link within YSort nodes, where its contents would be YSorted as if they were direct children of the YSort node for better organization?

I'm not asking for this to interfere with other nodes or instanced nodes that are already children of the YSort node. They should all work the same way as before.

**_example**_

YSort1

> > **_sprite1**_ <---- YSorted because it is a direct child node of the YSort node
> > **_instanced nodes**_ <---- would still get sorted like they currently already do just like sprites 1-2(and its children would **_not**_ be sorted)
> > **_sprite2**_
> > (**_New node**_)
> > 
> > > > **_sprite3**_
> > > > **_sprite4**_ <---- Direct children of the new node (sprite3 and 4) would be YSorted as if they were direct children of the YSort1 node like sprites 1-2

I apologise for resubmitting this issue. I submitted it two days ago https://github.com/godotengine/godot/issues/3258 but it was closed because everyone thought I was asking to sort **_all**_ sub-nodes of children of YSort nodes.

**Comment by bojidar-bg** [comment] 2016-01-08 21:21
@gusthe ~ Here is the main problem with your idea: you cannot do it with the current node structure and renderer, without doing some "hacks" (discussed below).

Here is an example: Imagine you have 6 nodes, at different *global* Y coordinates:
````
YSort
- A (Y:1)
- B (Y:4)
- C (Y:6)
- YSortLink (Y:3) # This is the new container node
- YSortLink - E (Y:2) # Children of YSortLink
- YSortLink - F (Y:5)
````
After sorting by global Y (lower Y goes first in this example):
````
YSort
- A (Y:1)
- YSortLink - E (Y:2)
- YSortLink (Y:3)
- B (Y:4)
- YSortLink - F (Y:5)
- C (Y:6)
````
Unfortunatelly, we can't just move the node outside of its parent, plus it would be drawn either directly on top, or directly behind (with "CanvasItem/Behind Parent"=true). Thus we change our tree to fit:
````
YSort
- A (Y:1)
- YSortLink (Y:3)
- YSortLink - E (Y:2) (Behind parent checked)
- YSortLink - F (Y:5) (oops! This node just went behind B, while it should be in front of it. This would get very confusing to anybody just starting with the engine.)
- B (Y:4)
- C (Y:6)
````
---
Ok... there **should** be *some* solution to the problem? Well, I can think of a few, each with its drawbacks:

1. Use z-index. This has the side effect of overwriting the already present z-index, which would be... nasty. (as it means you will have to keep foreground in seperate nodes/wrappers => more organizational issues)
2. Change the rendering system to have some `virtual order`, used for sorting internally. Probably the best solution, and the most complex too. Now we have: node order, z-index, and virtual order.
3. Change the node system, so nodes are in a tree, but are actually in a list, that gets sorted by YSort and others. That would laaagggggg, so `#2` is better

**Comment by gusthe** [comment] 2016-01-08 21:45
Would there be any way to do it where the YSortLink node would not be given a Y value at all? Kind of like how the AnimationPlayer(from what I can tell) node dosen't have any x y or z values? Sorry if what I'm saying doesn't make any sense.

**Comment by reduz** [comment] 2016-01-08 22:14
I don't think this is fixable in any way, and I still fail to see why it is
needed

**Comment by gusthe** [comment] 2016-01-08 22:25
I can't comment on whether it's fixable or not, but we can at least discuss it can't we? I can only speak for myself, when I say it would certainly be of value for my purposes. YSort is the only option I'm aware of that will allow me to perform this kind of sorting. And in my case I'll be looking at many hundreds of nodes all under one YSort node because that's the only place I can put them to sort them. It's not a deal breaker for me, but I thought I could at least inquire or suggest a possible solution.

**Comment by kubecz3k** [comment] 2016-01-08 22:28
@gusthe Hmm maybe some kind of "search" for scene tab would solve your problem?

**Comment by reduz** [comment] 2016-01-08 22:32
The problem is that for this to be fast, it has to be simple. The sorting
of children Y-Sort nodes is done in-place with a local stack copy, so
anything more complex won't do.
A remote link is also not possible because nodes are processed in tree
order, and hacking this process would require adding a lot of code that
will make the process more unnecesarily complex, as well as prone to bugs
(a lot of behaviors rely on trees being processed in order). In other
words, It's too much hack for something that I feel is a corner case and no
simple solution comes to mind.

**Comment by gusthe** [comment] 2016-01-08 22:35
@kubecz3k You mean to search for a specific node in the scene, like something specific under the YSort node?

**Comment by gusthe** [comment] 2016-01-08 22:37
@reduz If that's that case then I can understand why it would be difficult to change. I wasn't looking to suggest major changes like that. I was only looking for something simple. Should I just close this issue?

**Comment by reduz** [comment] 2016-01-08 22:49
I will think for a way to do this, so don't close it yet

**Comment by kubecz3k** [comment] 2016-01-08 22:55
@gusthe yeah exactly, I was thinking about possibility to filter nodes with fragment of their name, something similar to how it's when you are opening a scene with ctrl+shift+o, but under 'search button in the scene tab, where are all the nodes.

**Comment by bojidar-bg** [comment] 2016-01-09 08:40
@gusthe @reduz BTW, would a node that transfers all of its children to its parent at _enter_tree be a nice solution? This would also fix all kinds of similar organizational problems, and it is simple to do with the current codebase. The downside is that it would change nodepaths to its children...

**Comment by reduz** [comment] 2018-03-18 13:05
We discussed a nice way to potentially do this at Godoton, would like to
give it a try when back from GDC

**Comment by danielytics** [comment] 2018-03-18 13:51
I’d be willing to help out, but I’m new to the Godot codebase so would need some guidance.

**Closed** 2018-11-12 19:42 UTC
Labels: enhancement, topic:core, topic:editor, usability
