### ISSUE TITLE
Unable to exit out of editor fullscreen mode in Godot 4.2 rc2

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#85398] opened 2023-11-26 19:21 UTC
### Godot version

v4.2.rc2.official [1ba920fad]

### System information

Godot v4.2.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When I enter fullscreen mode in the editor with shift + f11 while being in or then going to the 3D editor, I can't exit it anymore by pressing the same keybind.

### Steps to reproduce

Create a new Godot project
Press shift + f11 to enable editor fullscreen
Go to the 3D editor
Try to exit editor fullscreen with shift + f11

### Minimal reproduction project

Create a new Godot project

**Comment by akien-mga** [comment] 2023-11-26 21:47
I can't reproduce on Linux (Mageia 9, KDE/X11) with 4.2-rc2.

Do you have any custom plugin installed that would handle Shift+F11 as a hotkey?

**Comment by Diordany** [comment] 2023-11-26 21:55
> I can't reproduce on Linux (Mageia 9, KDE/X11) with 4.2-rc2.

I also couldn't reproduce this issue on Linux 6.6.2-arch1-1 with KDE/X11 using Godot Engine v4.2.rc2.official [1ba920fad].

**Comment by xxSeys1** [comment] 2023-11-26 21:58
In 4.2 rc1 after trying to disable fullscreen with shift + F11 the window reverts to a small size (about the window size of Godot project manager). This is not because it was in that size before making it fullscreen (before making it fullscreen it was in fullscreen but with window title bar visible).

Beta 6 also behaves this way.

Beta 5 behaves as expected (Editor window return to fullscreen but with window title bar visible)

I'm testing this in an empty project so no plugins are there that could take control of shift + f11

UPDATE: 4.2 rc2 now behaves the same way as 4.2 rc1

**Comment by akien-mga** [comment] 2023-11-26 22:02
Thanks for testing, this sounds like a regression from #84504 which was merged for 4.2-beta6. CC @jitspoe @bruvzg

**Comment by bruvzg** [comment] 2023-11-27 10:39
I can't reproduce inability to exit full screen.

> In 4.2 rc1 after trying to disable fullscreen with shift + F11 the window reverts to a small size (about the window size of Godot project manager). This is not because it was in that size before making it fullscreen (before making it fullscreen it was in fullscreen but with window title bar visible).

This is expected behavior for setting window mode to `WINDOW_MODE_WINDOWED` (which was fixed by https://github.com/godotengine/godot/pull/84504), but I guess editor shortcut should instead save previous mode and restore it to maximized if it was before entering FS.

**Closed** 2023-11-27 18:42 UTC
Labels: bug, platform:windows, topic:editor, regression
