### ISSUE TITLE
Godot 4: WorldEnvironment doesn't work in 2D.

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#58604] opened 2022-02-27 19:13 UTC
### Godot version

v4.0-alpha3

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

I was trying to improve the graphics of my 2D game. But The WorldEnvironment didn't work. The glow didn't work. Neither the others.
I am using Vulkan Mobile graphics.

### Steps to reproduce

1. Create a new Project (Vulkan Mobile)
2. Create a 2D Scene
3. Add a `WorldEnvironment` and enable the glow.
4. Add a `Sprite2D` and increase its `modulate` color to a high raw value like `Color(5, 5, 5)`
5. Add another `Sprite2D` for the glow to "reflect" off of.

### Minimal reproduction project

[WorldEnvironment.zip](https://github.com/godotengine/godot/files/8149285/WorldEnvironment.zip)

**Comment by Calinou** [comment] 2022-02-27 20:17
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-02-27 20:17 UTC

**Comment by Dan-Gamin** [comment] 2022-02-27 20:57
> Duplicate of #52467.

@Calinou, you sure? it doesn't look like the same issue. Or do you need the `background-mode` set to canvas for it to work?

**Comment by Calinou** [comment] 2022-02-27 22:31
Glow also behaves differently on the Vulkan mobile renderer: https://github.com/godotengine/godot/issues/55901
