### ISSUE TITLE
Area2D does not change properties of monitoring nor monitorable

### ISSUE THREAD

**Issue by xklakoux** [godotengine/godot#5484] opened 2016-06-29 11:11 UTC
godot 2.0.3 64-bit non-steam osx 10.11.5 

**Issue description** (what happened, and what was expected):
maybe i'm missing something obvious but when I set enable monitoring or set monitorable on Area2D it does nothing

**Steps to reproduce:**
set_enable_monitoring(false)
set_monitorable(false)
print(is_monitoring_enabled()) #gives True
print(is_monitorable()) #gives True

**Comment by volzhs** [comment] 2016-06-29 11:44
any error message on debug panel or console?

**Comment by vnen** [comment] 2016-06-29 15:11
I cannot reproduce this. Can you provide a minimal project showing the bug? It's quite clear you didn't try with a minimal sample since the check function is actually called `is_monitoring_enabled()`, so maybe there's a bug in your project's logic.

**Comment by xklakoux** [comment] 2016-06-30 13:24
I did try it of course. When I was filling up the issue I already got rid of that part in my project, here I just typed it by hand and made stupid mistake. Sorry, I corrected it already. Here's the sample project:
[test_monitor.zip](https://github.com/godotengine/godot/files/341513/test_monitor.zip)

**Comment by vnen** [comment] 2016-06-30 13:42
The minimal project is more involved than your first steps, now I can see what's wrong. If you take a look at the debugger you will see two errors:

![godot windows opt tools 32_2016-06-30_10-33-48](https://cloud.githubusercontent.com/assets/5599796/16490014/4f577bea-3eae-11e6-992c-e648bb6ee325.png)

That means you can't call `set_enable_monitoring()` nor `set_monitorable()` during the `body_enter`/`body_exit` signals. You should use `area.call_deffered("set_enable_monitoring", false)`. This also means you couldn't test right away, you'd need to wait for the next frame.

Closing as not a bug.

**Closed by vnen** 2016-06-30 13:42 UTC

**Comment by xklakoux** [comment] 2016-06-30 13:50
my bad, thanks a lot
