### ISSUE TITLE
Cannot create a script that inherits from a custom script in Godot 4.

### ISSUE THREAD

**Issue by godofgrunts** [godotengine/godot#67552] opened 2022-10-17 19:34 UTC
### Godot version

v4.0.beta3.offical [01ae26d31]

### System information

Arch Linux Linux 6.0.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Oct 2022 18:58:49 +0000 x86_64 GNU/Linux

### Issue description

After instancing a scene file as a node that already has a script, I cannot remove that script and add a new that is inheriting from the script that was originally attached.

### Steps to reproduce

I can go through the process up until I need to click `Create` at the bottom of the `Attach Node Script` window when nothing happens.

![image](https://user-images.githubusercontent.com/338843/196264928-963ebe2b-9bb0-4b19-baf9-d2101155232b.png)

![image](https://user-images.githubusercontent.com/338843/196265047-09d225b8-b7cd-4172-86ef-f85cf60976a3.png)

![image](https://user-images.githubusercontent.com/338843/196265307-e4e51242-a9d9-4757-aa10-bd3b7439ebd5.png)

![create](https://user-images.githubusercontent.com/338843/196266015-ba1269ff-23bc-4a16-a800-a60a3fd11fad.gif)

### Minimal reproduction project

[platformerv4.zip](https://github.com/godotengine/godot/files/9803903/platformerv4.zip)

**Comment by godofgrunts** [comment] 2022-10-17 19:37
When I run `godot4 -v` I get the following error message when trying to attach the script.

```
ERROR: Parameter "type" is null.
   at: _create_new (editor/script_create_dialog.cpp:379)
```

**Comment by MaximeCohen** [comment] 2022-10-17 20:56
Same problem on windows 10 system with same error:

![image](https://user-images.githubusercontent.com/9808923/196281409-bbf60852-c04c-4b03-8292-8341cb7a9bf1.png)

**Comment by KoBeWi** [comment] 2022-10-17 21:08
Duplicate of #65827

**Closed by KoBeWi** 2022-10-17 21:08 UTC
