### ISSUE TITLE
The editor isn't opened

### ISSUE THREAD

**Issue by jshlw** [godotengine/godot#35288] opened 2020-01-18 17:26 UTC
**Godot version:**
3.2 RC1

**OS/device including version:**
Windows 10 64 bits
Intel HD Graphics

**Issue description:**
I opened Godot on Windows 10 and when I opened my project, it doesn't appeared. Note that I use on Ubuntu too and it's working. By clicking on run button in the project manager my project runs without issue.

**Steps to reproduce:**
Just open Godot on Windows 10.

**Comment by Anutrix** [comment] 2020-01-19 11:21
What happens when you double-click your project name in the project list? Does it do anything? Any error message on console or does a crash happen?

**Comment by jshlw** [comment] 2020-01-19 11:43
Everything shown is the Godot logo and sponsors. No error messages, the last thing printed to the debug console are my graphics. Yes, it's dual boot. Yes, I tried creating a new project and it's the same bug.

**Comment by akien-mga** [comment] 2020-01-19 11:59
Can you test this build? https://github.com/godotengine/godot/issues/35242#issuecomment-575986789

**Comment by jshlw** [comment] 2020-01-19 12:13
Another problem is that any exported builds are not working too (event for linux). When I double click a exported executable, it doesn't start up and keeps on the Godot logo (the RAM it consumes keeps growing).

**Comment by jshlw** [comment] 2020-01-19 12:23
@akien-mga It's working!

**Comment by akien-mga** [comment] 2020-01-19 12:40
Thanks, closing as duplicate of #35242 then.

**Closed by akien-mga** 2020-01-19 12:40 UTC
