### ISSUE TITLE
CanvasItem's Clip Content does not clear background with Vulkan Mobile + Error spam.

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#67437] opened 2022-10-15 10:05 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, rtx 3060 ti, mobile vulkan

### Issue description

CanvasItem's Clip Content does not clear background with Vulkan Mobile.

With GLES and Vulkan Forward+ everything works fine.

![mobile_clip_report](https://user-images.githubusercontent.com/54563399/195980566-d89d4b04-01e1-45eb-80ff-4ae9a558d915.png)

### Steps to reproduce

Set the backend to Vulkan Mobile and try using Clip Content.

### Minimal reproduction project

[enginetest.zip](https://github.com/godotengine/godot/files/9791752/enginetest.zip)

**Comment by clayjohn** [comment] 2022-10-15 17:11
Closing as duplicate of https://github.com/godotengine/godot/issues/67160

**Closed by clayjohn** 2022-10-15 17:11 UTC
Labels: bug, topic:rendering
