### ISSUE TITLE
Godot Editor freezes randomly when a tooltip or a context menu appears, or while building a project

### ISSUE THREAD

**Issue by RobotoSkunk** [godotengine/godot#82207] opened 2023-09-23 19:32 UTC
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - Debian GNU/Linux trixie/sid trixie - Vulkan (Compatibility) - NVIDIA GeForce GTX 1650 (nvidia) - AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G (4 Threads)

### Issue description

I've been using Godot for just three days and I've experimented a lot of freezes with the editor, but sadly it happens randomly.

I've tried to reproduce it on purposefully, but it still happens randomly.

When the editor freezes, it becomes unusable and it can't even be closed via the close button. I have to force the kill process by the KDE System Monitor to close it and open it again to continue working.

### Steps to reproduce

1. Open any project in Godot 4.1.1.mono.build.

2. Generally, these happen when
- a tooltip appears,
- when a context menu is opened,
- when a value is changed in the inspector,
- when the editor tries to close an open window (not the editor itself),
- or when the editor is saving the project to build and test (it gets stuck in the saving process).

### Minimal reproduction project

N/A

**Comment by danilw** [comment] 2023-09-23 21:06
if you use Nvidia to render Editor - I know similar behavior on Nvidia GPUs.

Try - `Editor -> Editor Settings -> Interface-Editor-> check Single Window mode`

Say if it help/no.

**Comment by RobotoSkunk** [comment] 2023-09-23 22:33
> if you use Nvidia to render Editor - I know similar behavior on Nvidia GPUs.
> 
> Try - `Editor -> Editor Settings -> Interface-Editor-> check Single Window mode`
> 
> Say if it help/no.

I think it helped because now even the tooltip doesn't lag the engine. But I have a question, wouldn't that be a problem for games that can create new windows?

**Comment by danilw** [comment] 2023-09-23 23:58
> wouldn't that be a problem for games that can create new windows?

**I can be wrong** but _I think_ this bug happening because of - `problem with how the driver reports the fence completion status` - and on Nvidia and some other "lowend/old GPUs" - there is problem with complex Vulkan applications.

Because driver-bugs especially in "old generations GPU".

And Godot editor is complex application and _if you make/reach same level of complexity in your application_ - you need to contact Nvidia/other corpo to force them fix their driver before release of your software - as you know every AAA+ game released with "new drivers" because in many cases it just does not work with old drivers.

In AMD-opensource drivers you can fix them by hands, and project like Godot did help find many driver bugs and ppl fix them.

**Answer:**

if you targeting "low-end hardware" - most likely you wont make "ultra complex app" - so you dodge this type of problem when design "minimal low-end application".

And if you target mid+ hardware atleast 3+yo - it mostly fine with Vulkan on GPUs.

**Comment by Sauermann** [comment] 2023-10-08 10:44
Can you please check, if this could be a duplicate of #79088 or #74548

**Comment by RobotoSkunk** [comment] 2023-10-09 00:29
> Can you please check, if this could be a duplicate of #79088 or #74548

It looks like a duplicate of both because both scenarios happened

**Comment by Sauermann** [comment] 2023-10-09 05:19
Consolidating as a duplicate with the two bug reports as per the comment above.

**Closed by Sauermann** 2023-10-09 05:19 UTC
Labels: bug, topic:editor, crash, topic:gui
