### ISSUE TITLE
Assigning a Node to Array[Node] in the editor has no effect.

### ISSUE THREAD

**Issue by stylemistake** [godotengine/godot#63117] opened 2022-07-17 17:19 UTC
### Godot version

4.0.dev (3ae61590e1)

### System information

Arch Linux, Vulkan, RX 550

### Issue description

When using the following:

```gd
@export var links_to: Array[Node] = []
```

...and attempting to assign a node on first array item, dialog shows, but after selecting the node it does not actually assign anything (no effect).

Main workaround is to keep using arrays of type`Array[NodePath]`, however I have personally decided to hard code a list of links as variables, since I only need 3 at most.

```gd
@export var links_to_node_1: Node3D
@export var links_to_node_2: Node3D
@export var links_to_node_3: Node3D
```

### Steps to reproduce

This script on any Node:

```gd
extends Node

@export var links_to: Array[Node] = []
```

**Comment by KoBeWi** [comment] 2022-07-17 22:13
Duplicate of #62916

**Closed by KoBeWi** 2022-07-17 22:13 UTC
Labels: bug, topic:gdscript, topic:editor
