### ISSUE TITLE
Opening file dialog to change main scene messes scrolling of ProjectSettings

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34710] opened 2019-12-31 01:10 UTC
Godot 3.2 beta4
Windows 10 64 bits

![image](https://user-images.githubusercontent.com/1311555/71606602-1a89fd00-2b6a-11ea-958b-b4ce14575902.png)

1) Open Project Settings
2) In the Run section, next to the Main Scene property, click on the folder icon to open the file dialog
3) Cancel the file dialog: observe the property list is now offset negatively.

**Comment by coppolaemilio** [comment] 2019-12-31 01:22
Same over here (Windows 10 64, 3.2), good catch!

**Comment by dankan1890** [comment] 2019-12-31 01:47
Can't reproduce on 3.2 5fa1905

**Comment by Anutrix** [comment] 2020-01-02 12:54
Isn't this a duplicate of https://github.com/godotengine/godot/issues/34486, fixed by https://github.com/godotengine/godot/pull/34572?

**Comment by akien-mga** [comment] 2020-01-02 12:59
Indeed.

**Closed by akien-mga** 2020-01-02 12:59 UTC
