### ISSUE TITLE
4.4.dev5 hovering on tool tip makes it turn on and off constantly, doesn't stay on

### ISSUE THREAD

**Issue by PauliusMM** [godotengine/godot#99830] opened 2024-11-29 11:06 UTC
### Tested versions

Reproducible only on 4.4.dev5 works fine with 4.4.dev4 and stable 

### System information

Windows 11, RTX 3080, AMD 5800X3D

### Issue description

https://github.com/user-attachments/assets/1be9f1f9-d017-4494-bc0a-cd0dce1c4179

as the video shows, you can see it turning on and off, works fine on any older version

### Steps to reproduce

Open godot and try hovering over a tool tip

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-11-29 11:21
* Duplicate of #99287.
* Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2024-11-29 11:21 UTC
