### ISSUE TITLE
Accessing Enum.keys() causes a quiet crash

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#70896] opened 2023-01-03 20:51 UTC
### Godot version

4.0b10

### System information

Windows 10

### Issue description

The keys method on enums causes the game to crash without warning. This worked in previous betas

### Steps to reproduce

1. Create an enum
2. Try to access the enum keys in a script using the keys() method

See attached project

### Minimal reproduction project

[enum_crash_issue.zip](https://github.com/godotengine/godot/files/10339688/enum_crash_issue.zip)

**Comment by KoBeWi** [comment] 2023-01-03 21:49
Duplicate of #70495

**Closed by KoBeWi** 2023-01-03 21:49 UTC
