### ISSUE TITLE
Autocomplete doesn´t list functions after if, while and for blocks.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#23264] opened 2018-10-24 21:40 UTC
**Godot version:**

Godot 3.1dev
451e5fd0511bc2c17a66fc73a0de9a5169109517

**OS/device including version:**

Win764bit

**Issue description:**

Autocomplete only list variables and constants after if,while and for blocks:
![autocompletebug](https://user-images.githubusercontent.com/11712737/47463117-99a4d800-d7e5-11e8-9525-20798f7efb16.gif)

Related:
https://github.com/godotengine/godot/issues/21915

**Comment by avencherus** [comment] 2018-10-24 22:47
May be related to this as well:  https://github.com/godotengine/godot/issues/22121

**Comment by Ranoller** [comment] 2018-10-25 05:33
Sorry ... i think i didn't express myself. Autocomplete only list variables and constants after if, but should list methods too (like before).

**Comment by kimjiy9607** [comment] 2020-02-18 19:39
Hi I am trying to reproduce this bug but I cannot.
It would be really nice if I can get any help or advice about how to reproduce this bug.
Thank you.

**Comment by Ranoller** [comment] 2020-02-19 10:24
yes, it was fixed some time ago, i forget the issue... closing

**Comment by KoBeWi** [comment] 2020-05-09 22:45
Reopening, because it seems to be a thing again (if it was ever fixed....):
![image](https://user-images.githubusercontent.com/2223172/81486775-7fabd880-9257-11ea-90f4-c32096c0fb7e.png)

Tested in ff5dfcd

**Comment by me2beats** [comment] 2021-04-16 22:14
I have this problem too in 3.2.3 and 3.3rc9, Linux

![completion if](https://user-images.githubusercontent.com/16458555/115089002-d3747680-9f2a-11eb-9ee3-c9c058c94d48.png)


![completion](https://user-images.githubusercontent.com/16458555/115089019-dd967500-9f2a-11eb-8972-16f70b927ba6.png)

**Comment by HolonProduction** [comment] 2024-10-14 11:10
I'm closing this as completed in 4.x.

Rationale:
In v3.6.stable.official [de2f0f147] identifiers will show up after `if`/`for`/... if they were defined before the statement. Parsing will fail at this points since the if statement is incomplete and will produce an error.
Supporting completion even with parser errors was added in the GDScript rewrite for 4.x, back porting is not feasible.

**Closed by HolonProduction** 2024-10-14 11:10 UTC
Labels: bug, topic:gdscript, topic:editor, usability
