### ISSUE TITLE
Exported NodePath has inconsistent empty values

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21556] opened 2018-08-29 06:42 UTC
**Godot version:** 3.1 custom

**Issue description:**
If a NodePath is exported and never assigned, its value will be null. If it is assigned and then cleared, the value will be an empty string. 

**Proposal:**
Make the default value either be null or "" and document it

**Comment by akien-mga** [comment] 2018-08-29 07:06
As far as I know that's by design, any identifier with no value assigned is `Null` initially. The export hint is just that, a hint, for the editor, so it doesn't impact the type of the variable (it's still dynamically typed).

So for GDScript, `export(NodePath) var node_path` and `export var node_path` are the same things, identifiers which are not yet pointing to any data.

On the other hand, once you've assigned data to the identifier, it has a type, and clearing it will give you an empty object of that type (unless you clear it by assigning to `Null` again).

Consider this example which is valid GDScript:
```gdscript
export(NodePath) var node_path
export(Dictionary) var dict
export(Vector3) var vec3

func _ready():
	print(node_path)
	print(dict)
	print(vec3)
	node_path = 42
	dict = "Hello world"
	vec3 = ["It's a duck"]
	print(node_path)
	print(dict)
	print(vec3)
```
Prints:
```
Null
Null
Null
42
Hello world
[It's a duck]
```

**Comment by akien-mga** [comment] 2018-08-29 07:08
Now with type hints:
```gdscript
export(NodePath) var node_path: NodePath
export(Dictionary) var dict: Dictionary
export(Vector3) var vec3: Vector3

func _ready():
	print(node_path)
	print(dict)
	print(vec3)
```
Prints:
```
{}
(0, 0, 0)
```
So it works fine, apart from the fact that empty NodePaths don't seem to have a proper `print` representation.

**Comment by QbieShay** [comment] 2018-08-29 07:32
I see. I still think that it should be discussed because it can represent a problem. 
I had this code:
```GDScript
if nodepath == null:
   my_thing = get_parent()
else:
   my_thing = get_node(nodepath)
```

This worked until I opened a scene, assigned the nodepath and cleared it. What happened then is that the object was trying to reference itself as the my_thing and my game crashed. Tracking down this bug wasn't very hard but i think this should be addressed in a more elegant way.

**Comment by akien-mga** [comment] 2018-08-29 07:35
IMO in your use case you should either use type hints, or initialize your export vars to make sure that they're not null, so:
```gdscript
export(NodePath) var nodepath = NodePath()
# or
export(NodePath) var nodepath: NodePath

...
    if nodepath == NodePath():
        my_thing = get_parent()
    else:
        my_thing = get_node(nodepath)
```

**Comment by akien-mga** [comment] 2018-08-29 07:40
I don't think we can change the fact that `export(NodePath) var nodepath` is `null` until assigned, as I mentioned the `export()` keyword is just defining a hint for the inspector, but it doesn't imply typing of the variable.

Within a script,
```gdscript
export(NodePath) var node_path
export(Dictionary) var dict
export(Vector3) var vec3
```
is exactly the same as
```gdscript
var node_path
var dict
var vec3
```

What could be done however is to fully deprecate the `export(<Type>)` syntax now that we have optional typing, and use `export var nodepath: NodePath` instead to provide both editor hints *and* typing.

CC @bojidar-bg @vnen

**Comment by name-here** [comment] 2020-10-23 17:32
Isn't this fixed by the new `@export` annotation?

**Comment by vnen** [comment] 2020-11-10 00:39
> Isn't this fixed by the new `@export` annotation?

I guess so, because now you can only use the type hint to set the export type, so it should always default to an empty default value instead of `null` (if it's not an object type).

**Comment by Calinou** [comment] 2021-08-21 20:19
Closing per @vnen's comment.

**Closed by Calinou** 2021-08-21 20:19 UTC
Labels: discussion, topic:core, topic:gdscript
