### ISSUE TITLE
Resizable Window Dialog with set Rect.MinSize moves when hitting minsize

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot#33819] opened 2019-11-22 16:14 UTC
Godot Version: **3.1.beta1**
Used on: **Windows10**

![WindowDialogMoving](https://user-images.githubusercontent.com/10502115/69441377-e9d4cd80-0d4a-11ea-9d23-0b74710bb36d.gif)

**When using a Window Dialog Node, and setting this to be 'resizable', while also having set a minimum X or Y size for the Window Dialog, the behaviour of the window seems inconsistent. When resizing the window from the right or bottom, it will stop when it reaches the minimum size, and not allow the user to size the window to be any smaller. When resizing the window from the left or top, it will start moving in the direction you are resizing in, when it reaches the minimum size.**

*I expect it should not move at all, and stay in place when being resized while already at it's minimum size.*

**REPRODUCTION STEPS**
*1. Create an empty project.
2. Add a 'Window Dialog' node to a 2D scene, and make it visible.
3. Make the Window Dialog 'resizable' in the inspector.
4. Give the Window Dialog a Min(imum) Size in the Rect tab of the inspector.
5. Play the project.
6. Resize the Window Dialog from the left side, towards the minimum size, and compare this with resizing the window from the right side.
7. Resizing from the left side of the window will cause the window to move across the screen when it hits it's given minimum size, while resizing from the right will not.*

**Comment by Zylann** [comment] 2019-11-23 02:45
Duplicate of https://github.com/godotengine/godot/issues/23831 ?

**Comment by Arecher** [comment] 2019-11-23 05:51
Ah, you're right. I looked around for earlier reports already, but I must have missed yours.
Good to see the bug is already known about!

**Closed** 2019-11-23 08:11 UTC
