### ISSUE TITLE
AnimationPlayer resume animation by play() after pause() make call method track called function call again

### ISSUE THREAD

**Issue by rt9391** [godotengine/godot#86147] opened 2023-12-14 03:58 UTC
### Tested versions

4.2.1.stable

### System information

win11 godot 4.2.1.stable

### Issue description

AnimationPlayer resumes animation by play() after a pause() make call method track **called function** call again
This does not happen in 4.1.3

### Steps to reproduce

1.  make an animation with a call method track, calls a method at 1s.
2.  play the animation.
3.  wait till 1s is passed.
4.  pause it.
5.  resume animation by play(), the function called before the resume position will call again.

### Minimal reproduction project (MRP)

[teststeBUGANUM.zip](https://github.com/godotengine/godot/files/13668108/teststeBUGANUM.zip)

**Comment by rt9391** [comment] 2023-12-14 04:02
![image](https://github.com/godotengine/godot/assets/91177204/ac93384f-51d7-41d6-a654-255ba6ddb813)
![paseuresumbug](https://github.com/godotengine/godot/assets/91177204/06fdc004-e53f-4566-86de-21fa870a6bfd)

**Comment by rsubtil** [comment] 2023-12-15 18:51
Bisected to 7ed7ea53e6221eff6e6bf1e357706533e9a31e8c (https://github.com/godotengine/godot/pull/85569), cc @TokageItLab

**Comment by AThousandShips** [comment] 2023-12-15 18:54
Duplicate of https://github.com/godotengine/godot/issues/85950

**Comment by rt9391** [comment] 2023-12-16 03:08
> Closing as a duplicate of:
> 
> * [Method at time 0 in animation gets called repeatedly if paused and resumed #85950](https://github.com/godotengine/godot/issues/85950)
> 
> See [#85950 (comment)](https://github.com/godotengine/godot/issues/85950#issuecomment-1848835749), this is intentional

this is not a duplicate of it, that one repeatedly called method is **at 0s**, paused at 0, and resumed at 0 (Or just at 1s, which has been considered as the same key being processed at the end of the last play and the start of the next play).
In this case, the method is at 1s, paused **after 1s**, and resumed **after 1s**. Yet still being called.

**Closed** 2024-01-03 09:29 UTC
Labels: bug, regression, topic:animation
