### ISSUE TITLE
Control with scale (0,0) causes error in editor

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#18087] opened 2018-04-09 15:41 UTC
**Godot version:**

3.1.dev 36552c2c9

**OS/device including version:**

**Issue description:**

below error keeps occuring if scene has `Control` node with scale (0,0)
```
core/math/math_2d.cpp:321 - Condition ' det == 0 ' is true.
```

![screenshot from 2018-04-10 00-36-20](https://user-images.githubusercontent.com/8281454/38507420-67182cfe-3c57-11e8-9343-e75eebc2b76a.png)

**Steps to reproduce:**
1. Add `Control` node
2. make it scale (0,0)
3. click anywhere in viewport

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2018-04-10 06:00
It's normal that it errors out (a scale of (0, 0) makes no sense), but we need to either find a way to prevent inputting (0, 0) as scale, or show a better error message.

**Comment by volzhs** [comment] 2018-04-10 06:05
I found this while making an animation of Control node, like zooming effect for UI, by scaling 0.0 to 1.0

**Comment by Noshyaar** [comment] 2018-04-10 15:56
Closing as duplicate of #7332

**Closed by Noshyaar** 2018-04-10 15:56 UTC
Labels: bug, topic:editor
