### ISSUE TITLE
8 Bone Influence Animations do not function properly with glTF2 and ESCN

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#28840] opened 2019-05-12 15:53 UTC
**Godot version:**
Tried with nightly ecceabe and 3.1-stable

**Issue description:**
When exporting from blender to Godot, a number of issues appear:
### Blender
https://gfycat.com/VariableCircularBighornsheep

### Exported escn
https://gfycat.com/LikelyGlamorousAlleycat

### Exported gltf
https://gfycat.com/WickedGargantuanHare

I'm not sure if it's an importer problem, exporter problem, or both. Better collada seems to work.

**Steps to reproduce:**
Import the models given in the zip file and play the animations
[3dreport.zip](https://github.com/godotengine/godot/files/3170266/3dreport.zip)

**Comment by bojidar-bg** [comment] 2019-05-12 16:05
Most escn problems should be reported on the godot-blender-exporter-plugin repository :smiley:

**Comment by QbieShay** [comment] 2019-05-12 16:36
@bojidar-bg yes, but I am not entirely sure that this is an escn exporter problem

**Comment by marstaik** [comment] 2019-09-24 05:16
The GLTF file seems to be fixed by #32213

![charon](https://user-images.githubusercontent.com/5601015/65483035-b8757980-de4f-11e9-9b9f-f22eec93dea5.gif)

**Comment by fire** [comment] 2020-01-09 21:02
The escn export bug should be report to https://github.com/godotengine/godot-blender-exporter since it's external to the code in this repository.

The glTF2 file looks correct.

Thanks for your contribution.

**Comment by samdze** [comment] 2020-01-09 21:37
Tried the gltf file with 3.2 beta 5, the result did not change, same behaviour as in the issue description:
different (wrong, with weird vertices displacements) result compared to the Blender animation.
> 
> 
> The GLTF file seems to be fixed by #32213
> 
> ![charon](https://user-images.githubusercontent.com/5601015/65483035-b8757980-de4f-11e9-9b9f-f22eec93dea5.gif)

The gif shows exactly the same issues the op describes, i don't think this should be marked as fixed.

**Comment by fire** [comment] 2020-01-09 22:39
This model uses 8 bone influences which isn't currently supported in Godot Engine master.

**Comment by fire** [comment] 2020-01-09 22:45
![output](https://user-images.githubusercontent.com/32321/72111077-9d3f5480-32ee-11ea-860c-8099af2e0c68.gif)

However, if one was to patch Godot Engine to have 8 weight influences. It should look like this.

https://github.com/godotengine/godot/pull/27641

**Comment by KoBeWi** [comment] 2020-11-29 23:32
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by fire** [comment] 2020-11-29 23:39
This is still a valid bug. Reduz is implementing this for master.

**Comment by fire** [comment] 2020-12-17 22:32
https://github.com/godotengine/godot/pull/44430 implemented the rendering feature needed for this. Will need to verify that the gltf2 has it too.

**Closed** 2020-12-30 14:24 UTC
Labels: bug, confirmed, topic:import

**Comment by fire** [comment] 2020-12-30 14:41
Note 8 weights for escn should be tracked separately.
