### ISSUE TITLE
[4.0.alpha14] Bad Control performance in editor when transforming parented nodes through the viewport.

### ISSUE THREAD

**Issue by fakeZaki** [godotengine/godot#64797] opened 2022-08-23 17:40 UTC
### Godot version

4.0.alpha14

### System information

Windows 11

### Issue description

When you transform a Control node that is parented to another Control node in the viewport through any of the modes (Select, Move, Rotate and Scale), the transformation is very low framerate, which i would estimate to be in between 10-20FPS. The only node that has a lower performance impact when parented to a Control node is the base Control node, which is still noticeably choppy.
When you change the properties by dragging in the inspector, it does not seem to lower the framerate
Is not a problem in 3.5.

### Steps to reproduce

Create any Control node (in this example the basic control node).
Create any other Control node (in this case a Label) and parent it to the other Control node.
Try moving it around in the viewport.

**Comment by Calinou** [comment] 2022-08-23 17:54
Duplicate of https://github.com/godotengine/godot/issues/61343 (fixed in latest `master` branch).

**Closed by Calinou** 2022-08-23 17:54 UTC
