### ISSUE TITLE
Godot does not recognize button releases for "ibuffalo snes controller" or "8bitdo sn30"

### ISSUE THREAD

**Issue by sicienss** [godotengine/godot#47630] opened 2021-04-04 18:04 UTC
**Godot version:**
v.3.2.3 custom build ([GodotSteam](https://github.com/Gramps/GodotSteam) v3.8.1)

**OS/device including version:**
Windows 10, Razer Blade 15 (intel core i7, NVIDIA GeForce RTX 2070 w/ Max-Q)

**Issue description:**
- The `ibuffalo snes controller` as well as the `8bitdo sn30` are recognized by Godot calls of `Input.get_joy_name()`
- Godot recognizes button presses
- But Godot does not seem to recognize releases of the D-PAD buttons
- For example, if you press D-PAD Down (joy button 13), and call `print(Input.is_joy_button_pressed(0, 13))` in `_process()` to debug, you'll see that it remains `true` even after you release
- The face buttons correctly release, but the D-PAD buttons, do not

**Steps to reproduce:**
See above

**Additional notes:**

A player of my published project also reported receiving this error in their logs when trying to use the ibuffalo snes controller. I suspect it's related:

```
Godot Engine v3.2.3.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
**ERROR**: Condition "output_button == JOY_INVALID_OPTION && output_axis == JOY_INVALID_OPTION" is true. Continuing.
   At: main\input_default.cpp:1142:InputDefault::parse_mapping() - Condition "output_button == JOY_INVALID_OPTION && output_axis == JOY_INVALID_OPTION" is true. Continuing.
```

**Comment by Calinou** [comment] 2021-04-04 19:25
Duplicate of https://github.com/godotengine/godot/issues/46766 (fixed in 3.3rc).

**Closed by Calinou** 2021-04-04 19:25 UTC
