### ISSUE TITLE
Sticky note inside the editor

### ISSUE THREAD

**Issue by Jackain** [godotengine/godot#16743] opened 2018-02-16 10:49 UTC
Hi,
Just a suggestion that would be helpfull to me and probably others:
When i open Godot, i would like something like a sticky note that a wrote to show somewhere on the screen, and i could know what i was doing last time i opened Godot, what to do next or whatever i wrote inside. 
Be able to write comment (on a note, not in GDscript) and attach it the node i want, so i could write inside what to improve on this or that node.
Commenting in GDScript is good but can be pain in the arse to read.
And thank you for this wonderfull tool that is Godot Engine!

**Comment by groud** [comment] 2018-02-16 11:03
Like the grease pencil in Blender, that's a cool idea I like it :)

**Comment by akien-mga** [comment] 2018-02-16 11:22
That's a duplicate of #7361. It's a good candidate for an editor plugin IMO.

**Closed by akien-mga** 2018-02-16 11:22 UTC
Labels: feature proposal, topic:editor
