### ISSUE TITLE
3.6 beta editor becomes unresponsive after error

### ISSUE THREAD

**Issue by Silentcody52** [godotengine/godot#86005] opened 2023-12-10 15:41 UTC
### Tested versions

3.6.beta3

### System information

Godot 3.6.beta3 mobile Editor using a one plus 6t

### Issue description

If you run faulty code that result in a error the screen will then black and the whole editor will be become unresponsive, leaving the editor and then opening again and trying to edit or run the game will still result in a unresponsive black screen
 The only way to make it work again is to close the app entirely rather then just leaving (when doing this  you will not be shown where the faulty code is Rather you are booted to the main scene) rather then just leaving this is worse then the beta 2 version which I have been using to make my game in that one simply leaving and rejoining will cause the black screen to go away and show you where the error comes from 

There is no need for a screen shot 

### Steps to reproduce

*Write faulty code
*Run it 
*and it happens 

### Minimal reproduction project (MRP)

No need to

**Comment by AThousandShips** [comment] 2023-12-10 15:43
To confirm, this happens with *any* invalid code? Syntax error as well or just code that has errors otherwise?

**Comment by Silentcody52** [comment] 2023-12-10 18:30
> To confirm, this happens with _any_ invalid code? Syntax error as well or just code that has errors otherwise?

Yes

**Comment by m4gr3d** [comment] 2024-10-17 12:42
Duplicate of https://github.com/godotengine/godot/issues/77966

**Closed by m4gr3d** 2024-10-17 12:42 UTC
Labels: platform:android, topic:editor, needs testing
