### ISSUE TITLE
C# Issue: Creating a generic class which inherits from Node crashes the editor

### ISSUE THREAD

**Issue by DraconicMentalist** [godotengine/godot#71083] opened 2023-01-08 19:06 UTC
### Godot version

4.0 Beta 10

### System information

Windows 10

### Issue description

Exactly as the title says, creating a generic C# class that inherits from Node instantly crashes the editor silently and without throwing an error. Editor crashes on startup until the .cs file containing the generic class is removed.

### Steps to reproduce

Create a generic C# class that inherits from Node. Project crashes instantly, then crashes on every attempt at reopening the editor. 

### Minimal reproduction project

The reproduction project crashes upon starting the editor.
[Generic Class Bug Reproduction.zip](https://github.com/godotengine/godot/files/10369245/Generic.Class.Bug.Reproduction.zip)

**Comment by raulsntos** [comment] 2023-01-09 03:07
Sounds like a duplicate of https://github.com/godotengine/godot/issues/67140 which was fixed by https://github.com/godotengine/godot/pull/70511. The fix did not make it for beta 10 but will be included in the next one.

**Closed** 2023-01-09 07:20 UTC
Labels: bug, topic:editor, topic:dotnet, crash
