### ISSUE TITLE
Touchscreen presses are offset within the editor and while testing

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#19586] opened 2018-06-15 20:30 UTC
**Godot version:**
v3.0.3.stable.official.e649ec7

**OS/device including version:**
Windows 10 Pro v1709 (Fall Creator's Update), on a Surface Pro 4

**Issue description:**
Within the editor and while testing my applications, using the touchscreen (or the Surface Pen) does not work as expected. While touches and presses are registered as normal, their registered location is offset by some amount. For example, clicking on the root node in my scene tree will register as the clicking the node just below it; clicking the Add Node button registers as clicking the root node; I have to click just above the Use Snap toggle in order to lock a node; etc. Regular mouse usage is not affected and works as expected.

I don't know if the Surface Pro 4's default display scaling (200%) is at fault, because even setting Scaling on the executable (on the compatibility tab) to be performed by the system instead of the application does not fix the issue.

This issue did not occur while I was using 3.0.2 or 3.0.1, and continues to not occur even on a freshly downloaded copy of 3.0.2.

Also, I tried some of the release candidates for 3.0.3, and the issue appears to have cropped up sometime between rc1 and rc2. (rc1 works properly, rc2 and rc3 have the offset issue)

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by KeithArch** [comment] 2018-06-20 17:28
I have experienced the same problem on a Dell XPS One 2710 27" touchscreen.  The same problem occurs when using InputEventScreenTouch and InputEventScreenDrag.  However, it only happens when using touch input directly, it does not occur when using the mouse for touchscreen emulation.

**Comment by akien-mga** [comment] 2018-06-20 17:59
CC @RandomShaper

**Comment by RandomShaper** [comment] 2018-06-20 18:54
@KeithArch, is your issue on Windows too?

**Comment by KeithArch** [comment] 2018-06-20 19:00
@RandomShaper Yes Windows 10 Home version 1803 April 2018 update.

**Comment by KeithArch** [comment] 2018-06-20 19:02
I am running the following gdscript attached to a root sprite node:

extends Sprite
func _input(event):
	if event is InputEventScreenTouch:
		position = event.position

**Comment by RandomShaper** [comment] 2018-06-21 19:04
Could somebody try with #19708?

**Comment by KeithArch** [comment] 2018-06-22 11:40
I'm not sure how to go about that, as I am only just getting started with Godot and only have a basic knowledge of C++ via Visual Basic.  I am willing to have a go but can you point me towards some reasonably detailed instructions as to what I need to do.  Thanks

**Comment by RandomShaper** [comment] 2018-06-23 11:02
Here is [a prebuilt Godot 3.0.4 + #19708 for Windows, x64](https://drive.google.com/open?id=1Bj3XM4jwUzWBDr1vQeGJaTpV0z8GiOlE) so you affected users can test if/how the issue is still present after the intended fix.

**Comment by KeithArch** [comment] 2018-06-23 11:55
Thanks, for that.  I have given it a try and that fixes the issue (at least for me).  Thanks for your effort in this. :)

**Comment by LikeLakers2** [comment] 2018-06-23 14:38
It's fixed the issue for me too. Thanks.

**Comment by LikeLakers2** [comment] 2018-06-23 15:03
Actually, and perhaps this is an unrelated issue, I don't seem to be able to right-click things with my Surface Pen even in your fix build? I'm able to right-click things with it in 3.0.2.

**Comment by akien-mga** [comment] 2018-06-26 13:41
>  I don't seem to be able to right-click things with my Surface Pen even in your fix build? I'm able to right-click things with it in 3.0.2, and right-clicking with a regular mouse in any version works fine.

@RandomShaper Do you want to look into this now, or should I merge #19708 and we open a new issue for this one?

**Comment by RandomShaper** [comment] 2018-06-26 15:12
I'll try to fix it within the next few hours. If I weren't able, I'd let you know so this one can be merged.

**Comment by RandomShaper** [comment] 2018-06-26 19:03
I've updated the PR and the Godot binary (it's the same link).

@LikeLakers2 (or any other affected user), please test right-clicking again.

**Comment by LikeLakers2** [comment] 2018-06-26 21:38
@RandomShaper Seems to work for me. Thanks. :)

**Closed** 2018-07-03 13:41 UTC
Labels: bug, topic:input
