### ISSUE TITLE
Sequential resource ID generates conflicts in VCS 

### ISSUE THREAD

**Issue by veryprofessionaldodo** [godotengine/godot#25416] opened 2019-01-28 14:44 UTC
**Godot version:**
This problem was encountered in Godot 3.1 Beta 2, and was present in both Linux and Windows versions. The specific hardware information is not relevant to this particular case.

**Issue description:**
Me and a couple of friends decided to try out Godot for this year's Global Game Jam, and quickly ran into an issue when multiple people decide to alter the same scene, caused by the overlapping of sequential IDs. This lead to manually change the .tscn file on a code editor and manually look for the resources differences, and see in which places it was mentioned.

**Steps to reproduce:**
- More than one person change the same scene (whether by adding or removing different nodes).
- The scene now has overlapping IDS for different resources.  
- Someone commits and pushes, the other pulls, and conflicts emerge due to those overlapping IDs.

**Possible solution:**
By making the ID generation non-sequential, and using a hash (maybe based on node name), the merge could now go more smoothly if the commits involve different resources. If two people commit a resource with an identical name, the problem persists **but** it is now more manageable, because the hash should be identical **ONLY** on the same resource. All the other resources would still be valid and would not need to be altered manually on the .tscn file.

If there is already a way to fix this I apologize or there is already a submitted issue regarding this situation I apologize, but I made quite a bit of research and I found nothing regarding this specific problem.

**Comment by akien-mga** [comment] 2019-01-28 14:48
Duplicate of #22226.

**Closed by akien-mga** 2019-01-28 14:48 UTC

**Comment by veryprofessionaldodo** [comment] 2019-01-28 14:53
I had run into that, but thought it wasn't quite what I was experiencing. After reading the comments more thoroughly I see you're right, sorry! :)
I'll try and see if I can fix this, would be a good thing to add to this cool engine.
