### ISSUE TITLE
First-class functions in GDScript

### ISSUE THREAD

**Issue by rezgi** [godotengine/godot#30979] opened 2019-07-30 21:09 UTC
**Godot version: 3.2**

A follow-up of the issue [GDScript: First-class functions roadmap #23](https://github.com/godotengine/godot-roadmap/issues/23) by [vnen](https://github.com/vnen) where he said in 3.2 there would be support for first-class functions, array functions map(), reduce(), filter() and short syntax for lambdas.

The issue is still open, so what about it for 3.2 ?

**Comment by KoBeWi** [comment] 2019-07-30 21:41
Isn't that basically a duplicate of #2684?

AFAIK, lambdas were moved to 4.0, because they need more discussion on how they should be implemented (there's a closed PR that did it wrong).

As for array methods, they could still come for 3.2 if there is a contributor willing to make them. There's a PR for filter #30874, which has high chance of being merged.

So yeah, nice status update, but closing this as duplicate.

**Closed by KoBeWi** 2019-07-30 21:41 UTC

**Comment by rezgi** [comment] 2019-07-30 22:25
Hi there. Sorry it's my first use of Github discussions and I'm still quite confused about how these threads work. I mainly wanted to update this feature request but your reply gave me plenty infos ! Thank you very much.
