### ISSUE TITLE
Unexpected Result when using Stretch Mode Options in 3.1 Alpha

### ISSUE THREAD

**Issue by TheExtremeGamer** [godotengine/godot#21691] opened 2018-09-02 12:45 UTC
Godot Version: v3.1.alpha.official

OS: Windows 7 Ultimate
GPU: Intel HD Graphics 4000 
API: OpenGL ES 2.0

I was creating a game with a resolution of 640 x 480 (480p), I took an image with identical resolution and centered it.

(Imagine Black Bars around it where needed)
![sonic and knuckles sonic 3001](https://user-images.githubusercontent.com/42900573/44951416-91599d80-ae31-11e8-9237-89439dd926a4.png)

Works, right?
I am looking to expand it horizontally for the sake of wider aspect ratios.

![image](https://user-images.githubusercontent.com/42900573/44951723-e4cfe980-ae39-11e8-8c11-39261fcfa20b.png)

However, when setting the stretch mode to "viewport" and the aspect to "keep_height" this happens.
[Windowed for Convenience]
![image](https://user-images.githubusercontent.com/42900573/44951748-b3a3e900-ae3a-11e8-96ad-371005b50380.png)

It appears to align the zero coordinates with the left side of the screen as opposed to centering the original viewport.

I'm not even sure if this is in fact a bug or a design choice.

HOW TO REPRODUCE
1. Set the Resolution Accordingly, Obtain and Import a matching image. (Image purely for referencing purposes)
2. Stretch settings should set to "viewport" in mode and "keep_height" in Aspect
3. Take the image and place where needed match by pixel
4. Test the Game in Fullscreen or a Resizable Window

**Comment by guilhermefelipecgs** [comment] 2018-09-02 15:46
I think this is not a bug.

How to solve:
Use a `Control` node and change "Layout" to "Center":
![captura de tela de 2018-09-02 12-42-39](https://user-images.githubusercontent.com/1387165/44957872-c60b3a80-aead-11e8-9ebf-2d620eb982c4.png)
and you will get the desired result:
![captura de tela de 2018-09-02 12-42-24](https://user-images.githubusercontent.com/1387165/44957871-c60b3a80-aead-11e8-8a66-cbceff79cd0e.png)

**Comment by Calinou** [comment] 2021-02-19 20:32
Closing per @guilhermefelipecgs's comment. When designing for multiple aspect ratios, you need to configure UI anchors correctly.

**Closed by Calinou** 2021-02-19 20:32 UTC
Labels: discussion
