### ISSUE TITLE
3.2.3 mono/c# - [Tool] script - othernode.Call(otherMethodName) doesn't work/fails silently

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#43282] opened 2020-11-02 21:15 UTC
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Win10

**Issue description:**

In a [Tool] script:
Doing a `node.Call` on methods of other nodes just does nothing where checking `node.HasMethod` does return true.
Doing `CallDeferred` prints an error about the method not existing.

Expected: (`node is MyClass`) check foremost should work, but doesn't, so `node.Call` seems like a fallback workaround, as `node.HasMethod` correctly returns true; doesn't work, but should.

**Steps to reproduce:**
Add a [Tool] script to a node, add a non-tool script with some method to another node. From the first (tool) script try to check if the second, other node is of the required script type. This returns false as the editor doesn't recognize the custom script. Then do a othernode.HasMethod call with some method of the other node as argument. This returns true.
Then do a othernode.Call() with the method name as argument. This fails silently.

**Comment by navstev0** [comment] 2020-11-06 05:24
This is likely because of an issue I had reported. Your C# node doesn't have a script. https://github.com/godotengine/godot/issues/41310. I worked around it, but it was quite painful.

**Comment by Flavelius** [comment] 2020-11-06 05:59
In my case i was trying to call a pre-existing node, one that i had created normally and assigned the script by hand. The script to be called (on the other node) also was created manually (and is a non-toolscript). But maybe it's still a similar problem.

**Comment by raulsntos** [comment] 2023-07-12 10:26
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. May be a duplicate of https://github.com/godotengine/godot/issues/59830.

Also, about the `node is MyClass` check. This doesn't work in Tool scripts unless `MyClass` is also declared as a Tool script. This is because the editor can't instantiate non-Tool scripts.

**Comment by raulsntos** [comment] 2023-08-12 01:55
Since the linked issues have been fixed and you didn't provide an MRP, is it OK to close this as a duplicate or can you still reproduce this in Godot [4.2-dev3](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-3/)?

**Comment by Flavelius** [comment] 2023-08-12 11:02
I cannot test it, i don't have/use Godot currently. But those issues sounded like this could be marked as duplicate.

**Closed** 2023-08-13 18:27 UTC
Labels: bug, topic:editor, topic:dotnet
