### ISSUE TITLE
Script editor mouse wheel scrolling bug

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#22744] opened 2018-10-05 00:25 UTC
**Godot version:**
3.1 alpha

**Issue description:**
There's a really weird bug that doesn't allow you to scroll to the last line of the script, but only if you use mouse wheel. You can scroll further if you manually drag the scroll bar.
Related video: https://youtu.be/rXvXLZ2t0hk

**Steps to reproduce:**
1. Run the minimal project
2. Open the script
3. Press console to expand it
4. Try scrolling to the bottom with mouse wheel

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/2448538/TestProject.zip)

**Comment by avencherus** [comment] 2018-10-05 03:27
Have also had this happen once a week ago, but I could figure out how to reproduce it.

Thought at first it had something to do with code folding, because that was what I did last, but haven't seen it lately.

**Comment by swarnimarun** [comment] 2018-10-05 20:40
I have had this happen to me a few months ago as well I believe but I am not sure. But it might be a much older bug.

**Comment by kellams** [comment] 2018-10-05 20:55
It seems that the conversion from an int to a double when calculating max_v_scroll was rounding down in some cases so the editor couldn't scroll to the bottom.

**Comment by avencherus** [comment] 2018-10-05 21:43
@kellams Nice catch.  I'll check it out.

**Comment by akien-mga** [comment] 2018-10-06 10:36
Fixed by #22774.

**Closed by akien-mga** 2018-10-06 10:36 UTC
Labels: bug, topic:editor
