### ISSUE TITLE
Bug in localized remapped resources

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#34058] opened 2019-12-02 10:24 UTC
**Godot version:**
Godot 3.1.2-rc (4b855aa88e)

**OS/device including version:**
MacOSX 10.14.6

**Issue description:**
I have three localizations for my game: en, ru, de. Also I have remapped some images:
![Снимок экрана 2019-12-02 в 13 14 50](https://user-images.githubusercontent.com/1177068/69951157-c73e7380-1505-11ea-86d6-dd0aaa2cae45.png)

When I run the game my text resources had been localized, but not images:
![Снимок экрана 2019-12-02 в 13 16 26](https://user-images.githubusercontent.com/1177068/69951253-fa810280-1505-11ea-84c2-5037788b47ee.png)

(title on purple flag in english, text below in russian)

If I set up test localization for example `ru`, I can see both types of resources in russian:
![Снимок экрана 2019-12-02 в 13 18 34](https://user-images.githubusercontent.com/1177068/69951413-459b1580-1506-11ea-9b3a-a345dd913c02.png)

![Снимок экрана 2019-12-02 в 13 19 04](https://user-images.githubusercontent.com/1177068/69951455-577cb880-1506-11ea-8ca8-28c9d58415b8.png)

Also I checked on android 8.1.0. The same behavior.
 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by HaSa1002** [comment] 2019-12-04 11:59
Is your systems language set to russian?

**Comment by DrMoriarty** [comment] 2019-12-04 12:00
@HaSa1002 yes

**Comment by HaSa1002** [comment] 2019-12-04 12:07
Hmm. I can't reproduce it. Do you have a minimal project?

**Comment by DrMoriarty** [comment] 2019-12-04 12:53
@HaSa1002 
[lang-test.zip](https://github.com/godotengine/godot/files/3921840/lang-test.zip)

project with one localized texture and one localized string (en, ru, de)

My system locale is ru, when I start the project it shows russian text and english image.
![Снимок экрана 2019-12-04 в 15 49 38](https://user-images.githubusercontent.com/1177068/70143944-f1329a00-16ad-11ea-8564-486f09a6c211.png)

When I set `locale/test=ru` both of them in russian

**Comment by akien-mga** [comment] 2019-12-04 13:03
Likely duplicate of #31673 which was fixed by #33883, and cherry-picked in 3.1.2-stable. Did you try the stable version?

**Comment by HaSa1002** [comment] 2019-12-04 13:04
My system is german (and windows) and I get the correct result, when I play it. 
![grafik](https://user-images.githubusercontent.com/14185889/70144694-c7be4200-169e-11ea-84f6-7897216d13c8.png)

**Comment by DrMoriarty** [comment] 2019-12-04 13:34
I have found the problem!
When I remapped my resource to `Russian` it doesn't work. When I remapped it to `Russian (Russia)` it works.
I guess that the former means `ru` and the last one means `ru_RU`. 
And I have a new question. How should I remap resource in order to match more than one locale, for example one picture for `ru_RU` and for `ru_UA`?

**Comment by akien-mga** [comment] 2019-12-04 13:45
Right, I can confirm that on Linux:
```
$ LANG=ru ~/tmp/godot/stable/3.1/Godot_v3.1.2-stable_x11.64
```
works fine, but:
```
$ LANG=ru_RU ~/tmp/godot/stable/3.1/Godot_v3.1.2-stable_x11.64
```
reproduces the bug. So it's not a duplicate of #31673.

The code that handles remapping the images probably doesn't use the same `ll_CC` --> `ll` fallback used by text translation.

**Closed** 2019-12-05 05:50 UTC
Labels: bug, topic:core
