### ISSUE TITLE
Wrong action when overwriting Skeleton2D restpose

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#54996] opened 2021-11-15 14:27 UTC
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

The menu for `Skeleton2D` which allows for overwriting the rest position and setting a new rest position. But the actions which will happen are diffrent than the text says. For me when clicking "Reset to Rest Position" the current pose will become the new rest pose and when clicking "Overwrite Rest Pose" the pose will be set to the rest pose. I am using the "en" as language code but seems to apply to other translations as well.

### Steps to reproduce

- create a `Skelton2D`
- attach a `Bone2D`
- select the `Skeleton2D` node
- click on the option in the menubar and select "Reset to Rest Pose" -> the current pose becomes rest pose
- select `Bone2D` and move it a bit
- select the `Skeleton2D` node
- click on the option in the menubar and select "Overwrite Rest Pose" -> the pose is set back

**Comment by Calinou** [comment] 2021-11-15 14:30
Duplicate of https://github.com/godotengine/godot/issues/54793 (will be fixed in 3.4.1).

**Closed by Calinou** 2021-11-15 14:30 UTC
