### ISSUE TITLE
Recursive dictionary creation creates a really big log file (Infinite error chain)

### ISSUE THREAD

**Issue by Rokle** [godotengine/godot#95108] opened 2024-08-03 20:24 UTC
### Tested versions

- Reproducible in: 4.3-rc2, v4.2.2.stable.official [15073afe3]
- Not reproducible in: v3.5.1.stable.official [6fed1ffa3] 

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 770 () - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

Recursive dictionary creation creates a really big (4gb+) log file on project launch and crashes system
Log file content
```
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.142 - Forward+ - Using Vulkan Device #0: NVIDIA - GeForce GTX 770
 
USER ERROR: Max recursion reached
   at: recursive_hash (core/variant/dictionary.cpp:267)
USER ERROR: Max recursion reached
   at: recursive_hash (core/variant/dictionary.cpp:267)
....
```
And it goes on for millions of rows

In v3.5.1.stable.official [6fed1ffa3] log file isn't filled and game window just crashes
Log file
```
Godot Engine v3.5.1.stable.official.6fed1ffa3 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 770/PCIe/SSE2
Async. shader compilation: OFF
 ```

### Steps to reproduce

Create blank project 
Create node, add code and paste following
```gdscript
extends Control

func _ready():
	var a = {}
	var b = {}
	b[a] = {a:a}
	a[b] = {b:b}

```
Launch

### Minimal reproduction project (MRP)

N/A

**Comment by ajreckof** [comment] 2024-08-03 21:11
Duplicate of #80990

**Closed by ajreckof** 2024-08-03 21:11 UTC
