### ISSUE TITLE
Adding a Node from Recent-list inserts wrong Node

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#58732] opened 2022-03-04 07:31 UTC
### Godot version

v4.0.alpha.custom_build [d0c3094da]

### System information

Debian 11, Vulkan

### Issue description

When adding a node, on the lower left of the "Create New Node" window there is a list of recently inserted Nodes.
When the list contains `SubViewportContainer` and `SubViewport` and I double-click on `SubViewport`, I would expect that a `SubViewport` is inserted into the scene tree.
However current behavior is, that a `SubViewportContainer` is inserted.

Same issue happens for "Node" and "Node2D".
This seems to happen, because "SubViewportContainer" starts with the substring "SubViewport".

https://user-images.githubusercontent.com/6299227/156718415-76cba933-54de-4da0-96ac-bb31c54d9930.mp4

### Steps to reproduce

Load and run MRP
1. Click on Add Node Icon
2. Double-Click in recent list on `SubViewport`
3. A `SubViewportContainer` is inserted into the SceneTree

### Minimal reproduction project

[BugNodeInserterDoubleClick.zip](https://github.com/godotengine/godot/files/8183774/BugNodeInserterDoubleClick.zip)

**Comment by Calinou** [comment] 2022-03-04 08:02
Duplicate of https://github.com/godotengine/godot/issues/51632 (same cause).

**Closed by Calinou** 2022-03-04 08:02 UTC
