### ISSUE TITLE
More Polygon2D shapes/tools for prototyping?

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot#7042] opened 2016-11-05 12:10 UTC
Hello,

Making some prototyping with Godot engine, I believe that it would be nice if we could:
- make easily regular shapes with Polygon2D (e.g. circle, rectangle, ...),
- import the polygon defined in Polygon2D in CollisionPolygon2D through the GUI,
- add some tools, such as extrusion, to make complex shape more easily,
- allow shapes with hole (e.g. rings)

It does not need to be a fully fledged vectorial editor, but I think a bit some more tools/shapes could help prototyping.

**Comment by bojidar-bg** [comment] 2016-11-05 12:21
First point is duplicate of #6750.

**Comment by eon-s** [comment] 2016-11-05 14:02
Second point is possible now in the inspector with copy-paste polygon array resource.

There was another request for polygon tools for unions and other operations, extrude could be related to that.

**Comment by bojidar-bg** [comment] 2016-11-05 15:42
@eon-s Said request is #6740 (but it is only about unions, so no merging into it I guess)

**Comment by blurymind** [comment] 2016-11-09 10:26
This is somewhat related:
https://github.com/godotengine/godot/issues/6477

**Comment by eon-s** [comment] 2017-05-18 18:14
Now that 3 will have primitive meshes, maybe some polygon presets can be added for 2D too?
Like a polygon based circle and ellipse (these 2 cover many shapes depending of the vertex amount).

**Comment by Noshyaar** [comment] 2018-04-08 02:14
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Nodragem** [comment] 2018-04-12 09:04
ok, so PR #16483 would only solve the first point, right?

Concerning point 2, @eon-s, can you tell me what are the steps to follow to do it? I just tried 3.0.2 and could not figure it out.

Thanks.

**Comment by eon-s** [comment] 2018-04-12 09:33
@Nodragem 1 and 3 may be solved by the CSG tools if implemented.

The second, if you use the inspector to copy and paste parameters, the array values can be easily copied and pasted to another.
![copy_params](https://user-images.githubusercontent.com/10215987/38668853-3914228e-3e1b-11e8-9fc8-d21a8565298e.png)

**Comment by Zireael07** [comment] 2018-04-12 09:50
I believe copy/paste params copies all params, not just the ones you might want...

**Comment by eon-s** [comment] 2018-04-12 10:38
In the case of arrays, it only copy values.

I would like that option to be "section specific" to copy only a small set of properties.

**Comment by Zireael07** [comment] 2018-04-12 10:45
(+1 to section specific, I mean)

**Comment by akien-mga** [comment] 2018-11-22 12:33
See also #22275.

**Comment by akien-mga** [comment] 2020-05-26 11:24
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by akien-mga** 2020-05-26 11:24 UTC
Labels: feature proposal, topic:editor
