### ISSUE TITLE
Bad font quality v3.2.1.RC1

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#36567] opened 2020-02-26 15:35 UTC
**Godot version:**
Godot Engine v3.2.1.rc1.mono.official
**OS/device including version:**
Windows 10 (OS Build 18363.657)
**Issue description:**
Fonts seem to have bad quality in **v3.2.1.RC1**:
![75359193-b9a64900-58bc-11ea-80f5-6497706ac795](https://user-images.githubusercontent.com/1850856/75360224-2d952100-58be-11ea-8873-59ca65d6a31d.png)

**3.2 Stable:**
![image](https://user-images.githubusercontent.com/1850856/75359254-d17dcd00-58bc-11ea-8813-36275ed626c7.png)

So far this only seems to be an issue with **v3.2.1.RC1**. In **3.2 Stable** everything looks as expected. This happens for both the editor and the running projects.
**Steps to reproduce:**
Open editor settings > Rendering > Quality and try scrolling down (this does happen on other setting pages also but that seems to have been consistently reproducible for me).

**Comment by Calinou** [comment] 2020-02-26 15:40
I'm pretty sure I've seen a bug report about this one already, but I can't find it right now.

**Comment by bojidar-bg** [comment] 2020-02-26 15:48
I feel I've spotted this in the inspector once, but in my case, scrolling up and down fixed it.

**Comment by zaksnet** [comment] 2020-02-26 16:04
> I feel I've spotted this in the inspector once, but in my case, scrolling up and down fixed it.


Indeed thats how you can recreate it but there are cases where this cant be fixed by scrolling (like still content):


**3.2.1.RC1**:
![image](https://user-images.githubusercontent.com/1850856/75362879-03ddf900-58c2-11ea-952d-b9a111fb1c50.png)


**3.2 Stable:**
![image](https://user-images.githubusercontent.com/1850856/75362328-39cead80-58c1-11ea-9d03-9af9576b67b3.png)

**Comment by volzhs** [comment] 2020-02-26 16:04
possibly related to #32959

**Comment by qarmin** [comment] 2020-02-26 16:09
Same thing happens in 4.0 branch

**Comment by akien-mga** [comment] 2020-02-26 16:11
Duplicate of  #36087.

**Closed by akien-mga** 2020-02-26 16:11 UTC
Labels: bug, topic:editor, topic:rendering
