### ISSUE TITLE
Failed to build assemblies for Godot Mono

### ISSUE THREAD

**Issue by 4nd3r5on** [godotengine/godot#80739] opened 2023-08-17 22:04 UTC
### Godot version

4.2.dev.mono

### System information

Arch Linux, .NET SDK Version 7.0.110, x86_64 arch, scons v4.5.2

### Issue description

Failed to build assemblies for Godot Mono that were built from source without any errors.

Command to build assemblies: `./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin`

Error:
```
/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(148,3): error MSB4019: The imported project "/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
```
This error was logged for 3 times for some reason

### Cloning and preparing
```sh
$ git clone https://github.com/godotengine/godot.git
$ cd godot 
$ export GODOT_ROOT=$(pwd) # /home/anderson/godot
```
### Building
```sh
$ scons platform=linuxbsd module_mono_enabled=yes tools=yes
```
No errors

### Generating glue
```sh
$ ./bin/godot.linuxbsd.editor.x86_64.mono \
  --headless \
  --generate-mono-glue {GODOT_ROOT}/modules/mono/glue
```
No errors or warnings
The Godot API sources were successfully generated

### Building assemblies. Error
$ `./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin`
```
Running MSBuild:  /usr/bin/dotnet msbuild /home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  Restored /home/anderson/godot/modules/mono/glue/GodotSharp/GodotPlugins/GodotPlugins.csproj (in 76 ms).
  Restored /home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj (in 76 ms).
  Restored /home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj (in 91 ms).
  Restored /home/anderson/godot/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/Godot.SourceGenerators.Internal.csproj (in 104 ms).
/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(148,3): error MSB4019: The imported project "/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj(47,3): error MSB4019: The imported project "/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(148,3): error MSB4019: The imported project "/home/anderson/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
  Godot.SourceGenerators.Internal -> /home/anderson/godot/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/bin/Debug/netstandard2.0/Godot.SourceGenerators.Internal.dll
  ```

### Minimal reproduction project

No project needed

**Comment by QueenTurtle** [comment] 2023-12-16 16:22
I'm running into the same issue. I'm just following the documentation found at: https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html

**Godot Version:**
godot mono 4.3.dev [f8a2a9193]

**System information**
Distro: Fedora 39 (xfce spin)
donet-sdk 8.0
scons 4.5.2


**Output:**
`/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(145,3): error MSB4019: The imported project "/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj(47,3): error MSB4019: The imported project "/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj(145,3): error MSB4019: The imported project "/home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GeneratedIncludes.props" was not found. Confirm that the expression in the Import declaration "Generated/GeneratedIncludes.props" is correct, and that the file exists on disk.
  Godot.SourceGenerators.Internal -> /home/me/src/godot/godotEngine/godot/modules/mono/glue/GodotSharp/Godot.SourceGenerators.Internal/bin/Debug/netstandard2.0/Godot.SourceGenerators.Internal.dll`

**Comment by akien-mga** [comment] 2024-05-15 15:00
I don't seem to reproduce the issue on Fedora 40 with dotnet-sdk-4.0 in the current `master` branch. Can you still reproduce it?

For @4nd3r5on, can you double check that the use of `GODOT_ROOT` may not be the problem here?
Notably:
```
$ ./bin/godot.linuxbsd.editor.x86_64.mono \
  --headless \
  --generate-mono-glue {GODOT_ROOT}/modules/mono/glue
```
Is the lack of `$` before `{GODOT_ROOT}` a typo, or is that a shell that expands `{GODOT_ROOT}` into the env variable as opposed to `${GODOT_ROOT}` in bash?

**Comment by QueenTurtle** [comment] 2024-05-15 19:04
I have just tried it with the latest master branch, however it worked perfectly this time.

**Comment by AThousandShips** [comment] 2024-09-14 15:46
Closing as this seems to not be reproducible any longer, if someone can still reproduce this please comment here

**Closed by AThousandShips** 2024-09-14 15:46 UTC
Labels: topic:buildsystem, needs testing, topic:dotnet

**Comment by shana** [comment] 2025-04-18 17:08
Just FYI, I just ran into this issue because one of the classes had a method and a property exposed with the same name, which triggers the hard failure in https://github.com/godotengine/godot/blob/09ea7bc6a3058505dbb4138d435292b74668b2b9/modules/mono/editor/bindings_generator.cpp#L4204

Even though that `ERR_FAIL_COND_V_MSG` is supposed to log the error to the console, no log showed up about it, not even when running in verbose mode. Other warnings about method name conflicts that the generator is supposed to be outputting to the console also don't show up (like `ERROR: Method 'play_backwards' conflicts with an already existing method in type 'AnimationPlayer' and has been ignored.`, which I can see them when step debugging the logger). I think there's an issue with the logging of the bindings generator where some messages are getting lost, which is leading to confusion about why the generator seemingly succeeds but does nothing.
