### ISSUE TITLE
Texture3D fails with more than 2 layers

### ISSUE THREAD

**Issue by AntonWedemeier** [godotengine/godot#24872] opened 2019-01-09 21:05 UTC
**Godot version:**
The most recent version I tried was Godot Engine v3.1.beta.calinou.e46f28e
(nighly build downloaded 2018-01-09)

**OS/device including version:**
Windows 10 Pro 64 bits with 

**Issue description:**
I tried using the new Texture3D. I could not get an image from the Texture3D. So I made a small test project., see Steps to reproduce. The code as shown runs ok. But when I change the number of layers to a higher number then I get:
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTX 660 Ti/PCIe/SSE2
* drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054
** Debug Process Stopped **
The number of layers filled does not make a difference.

**Steps to reproduce:**
func _ready():
	var tex3D = Texture3D.new()
	tex3D.create(64, 64, 2, Image.FORMAT_RGBA8) 
	var img1 : Image = Image.new()
	img1.load("icon.png")
	tex3D.set_layer_data(img1, 0)
	tex3D.set_layer_data(img1, 1)
	tex3D.set_layer_data(img1, 2)
	var img2 : Image = Image.new()
	img2 = tex3D.get_layer_data(0)
	img2.save_png("img.png")
	print ("ready")

**Minimal reproduction project:**

[Test3D.zip](https://github.com/godotengine/godot/files/2742595/Test3D.zip)

**Comment by bruvzg** [comment] 2019-01-10 13:02
Works with up to 3 layers for me. Crashes with 4 on `save_png` call. macOS 10.14.2.

Stack trace:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
Godot(11131,0x11087b5c0) malloc: Incorrect checksum for freed object 0x7ff0b9997200: probably modified after being freed.
Corrupt value: 0x83e2a169a533b1f
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7f9dc23e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7fa92c1c pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff7f9451c9 abort + 127
3   libsystem_malloc.dylib        	0x00007fff7fa546e2 malloc_vreport + 545
4   libsystem_malloc.dylib        	0x00007fff7fa6886c malloc_zone_error + 184
5   libsystem_malloc.dylib        	0x00007fff7fa50e87 small_free_list_remove_ptr_no_clear + 1195
6   libsystem_malloc.dylib        	0x00007fff7fa4fb49 small_malloc_from_free_list + 398
7   libsystem_malloc.dylib        	0x00007fff7fa4f3cf small_malloc_should_clear + 290
8   libsystem_malloc.dylib        	0x00007fff7fa4cc17 szone_malloc_should_clear + 173
9   libsystem_malloc.dylib        	0x00007fff7fa4b807 malloc_zone_malloc + 103
10  libsystem_malloc.dylib        	0x00007fff7fa4b783 malloc + 24
11  org.godotengine.godot         	0x0000000102da4e8d png_malloc_base + 109 (pngmem.c:95)
12  org.godotengine.godot         	0x0000000102da4de5 png_malloc + 53 (pngmem.c:179)
13  org.godotengine.godot         	0x0000000102dcb5f9 png_compress_IDAT + 89 (pngwutil.c:943)
14  org.godotengine.godot         	0x0000000102dcfe57 png_write_filtered_row + 39 (pngwutil.c:2758)
15  org.godotengine.godot         	0x0000000102dcf088 png_write_find_filter + 1160 (pngwutil.c:2742)
16  org.godotengine.godot         	0x0000000102dc6889 png_write_row + 1097 (pngwrite.c:901)
17  org.godotengine.godot         	0x0000000102dc6961 png_write_image + 113 (pngwrite.c:624)
18  org.godotengine.godot         	0x0000000102dd2440 ResourceSaverPNG::save_image(String const&, Ref<Image> const&) + 2112 (resource_saver_png.cpp:165)
19  org.godotengine.godot         	0x0000000104ada237 Image::save_png(String const&) const + 103 (image.cpp:1753)
20  org.godotengine.godot         	0x0000000104af346d MethodBind1RC<Error, String const&>::call(Object*, Variant const**, int, Variant::CallError&) + 765 (method_bind.gen.inc:1251)
21  org.godotengine.godot         	0x0000000104b18ed2 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 1490 (object.cpp:945)
22  org.godotengine.godot         	0x0000000104c10a1c Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) + 460 (variant_call.cpp:1049)
23  org.godotengine.godot         	0x0000000102588593 GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) + 38227 (gdscript_function.cpp:1070)
24  org.godotengine.godot         	0x0000000102535e21 GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) + 193 (gdscript.cpp:1204)
25  org.godotengine.godot         	0x0000000102535eb0 GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) + 96 (gdscript.cpp:1213)
26  org.godotengine.godot         	0x00000001039cf0ab Node::_notification(int) + 3163 (node.cpp:139)
27  org.godotengine.godot         	0x000000010397d537 Node::_notificationv(int, bool) + 151 (node.h:46)
28  org.godotengine.godot         	0x0000000104b14422 Object::notification(int, bool) + 50 (object.cpp:957)
29  org.godotengine.godot         	0x00000001039d0703 Node::_propagate_ready() + 275 (node.cpp:184)
30  org.godotengine.godot         	0x00000001039d0699 Node::_propagate_ready() + 169 (node.cpp:173)
31  org.godotengine.godot         	0x00000001039d6527 Node::_set_tree(SceneTree*) + 167 (node.cpp:2520)
32  org.godotengine.godot         	0x0000000103a10a2c SceneTree::init() + 60 (scene_tree.cpp:457)
33  org.godotengine.godot         	0x0000000101fde175 OS_OSX::run() + 69 (os_osx.mm:2545)
34  org.godotengine.godot         	0x0000000101fe5718 main + 1464 (godot_main_osx.mm:100)
35  libdyld.dylib                 	0x00007fff7f89ced9 start + 1
```

**Comment by karroffel** [comment] 2019-01-23 10:19
closing as a duplicate of #23531

**Closed by karroffel** 2019-01-23 10:19 UTC
Labels: bug, topic:core
