### ISSUE TITLE
Rigid body entering sleep state cause child areas to sleep too.

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#23590] opened 2018-11-08 10:26 UTC
**Godot version:**
de0d3065 - 3.1 alpha custom

**OS/device including version:**
ArchLinux 4.18.16-arch1-1-ARCH

**Issue description:**
When attaching an area as a child of a rigidbody and monitoring the area contacts with another area, the signal "area exited" is fired when the parent rigidbody enters the sleep state.

**Steps to reproduce:**
Add an area to the scene
Add a rigidbody to the scene and add an area to the rigidbody. Monitor the area enter and area exit signals fired by this area.
Create an environment where the rigidbody can sleep (a small box for example)
Launch and observe that after around 1s that the rigidbody stopped moving, the signal area_exited is fired from the area that is a child of the rigidbody, even if the environment area is still overlapping with the area.

**Minimal reproduction project:**
[SleepArea.zip](https://github.com/godotengine/godot/files/2561298/SleepArea.zip)

Play the scene and look at the console: after a small amount of time the signal area exited is fired.
Play again the scene after setting "can_sleep" on the rigidbody to false and the area exited signal is not fired anymore.

@AndreaCatania

**Comment by tom-jk** [comment] 2020-07-22 12:49
Testing the MRP:
Can reproduce in 3.1.alpha2.
Can't reproduce in 3.1.1.stable, 3.2.2.stable or 3.2.3.beta1.

Appears to be resolved.

**Comment by akien-mga** [comment] 2020-07-22 12:53
Thanks, closing as fixed in 3.1.

**Closed by akien-mga** 2020-07-22 12:53 UTC
Labels: bug, topic:physics
