### ISSUE TITLE
Object was deleted while awaiting a callback [AnimationTree]

### ISSUE THREAD

**Issue by Favkis** [godotengine/godot#43802] opened 2020-11-23 19:02 UTC
I find some like these here and there but no fix

**Godot version:**
v3.2.2.stable.custom_build

**OS/device including version:**
RTX 2080, latest, GLES3

**Issue description:**
After I added new animations to AnimationPlayer, when I click AnimationTree godot hangs in while forever spamming `Object was deleted while awaiting a callback`

**Steps to reproduce:**
No idea it's my months old project with dozens of classes, objects and items.

**Minimal reproduction project:**
Project weights 1.53 GB already

**Comment by Favkis** [comment] 2020-11-23 19:10
I opened it in steam godot and it works. I tried 2 custom built godots - first one is voxel addon and second one is voxel+heightmap build.

**Comment by Calinou** [comment] 2020-11-23 20:47
Duplicate of #35653 (the underlying issue is the same).

**Closed by Calinou** 2020-11-23 20:47 UTC

**Comment by Favkis** [comment] 2020-11-23 21:00
@Calinou I started getting same issue on official without custom build, however after doing what you did it actually helped and it doesn't freeze now when I open AnimationTree, thanks.
