### ISSUE TITLE
"Application Not Responding" almost every time Godot quits

### ISSUE THREAD

**Issue by e-e** [godotengine/godot#29107] opened 2019-05-22 17:59 UTC
**Godot version:**

3.1.1

**OS/device including version:**

MacOS 10.14.3

**Issue description:**

[error.txt](https://github.com/godotengine/godot/files/3208673/error.txt)

**Steps to reproduce:**
Open Godot
Quit Godot
Happens both when quitting to project list and just quitting out of godot completely

**Minimal reproduction project:**

**Comment by ibrahn** [comment] 2019-05-23 19:22
Not sure what the root cause of the error is, but #29134 should hopefully turn it from a hang into a regular crash-on-exit with stack trace

**Comment by Ranoller** [comment] 2019-05-23 22:44
I use godot alternatively in 4 computers + 1 laptop. 2 computer crashes on exit and 2 not. The 2 that crashes, crashes 2 times: first the project manager once a project is selected, later crash godot editor on exit... not to annoying to me, only for confirmation.

**Comment by metalim** [comment] 2019-06-03 16:56
Duplicate of #15754.
Looks like old issue.

**Comment by pwilkins** [comment] 2019-09-17 19:24
I have the same issue as reported by @e-e .  If someone creates a pull-request to fix it, I'd be happy to build and test it.

**Comment by Calinou** [comment] 2019-09-17 21:32
I'll close this as a duplicate of #15754, as this issue seems to be describing the same bug.

**Closed by Calinou** 2019-09-17 21:32 UTC
Labels: bug, topic:core
