### ISSUE TITLE
Camera doesn't Work/Render when it is child of a Rigidbody

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#9965] opened 2017-07-29 10:05 UTC
**Operating system or device - Godot version:**
Godot 3.0 Alpha, Windows 10, Wacom Cintiq Companion 2

**Issue description:**

When I was attempting to make a 3D racetrack demo using PBR, I parented the camera into a 3D rigidbody node to allow the camera to follow the rigidbody vehicle, but when I started to test out the level by playing the scene, the camera doesn't render the scene correctly or does not show anything at all. I have no idea on how this is happening but unfortunately the camera immediately breaks when parenting in a rigidbody. It also generates errors in the debug area:

`0:00:10:0919 - Condition ' determinant() == 0 ' is true`
`0:00:10:0919 - Condition ' p_axis.is_normalized() ==  false ' is true`
and
`0:00:11:0022 - Condition ' det == 0' is true`

**Steps to reproduce:**

Try parenting by click and dragging the camera node to the rigidbody node to see if the results are the same or not based on what I've encountered so far.

**Comment by eon-s** [comment] 2017-07-29 11:39
I can't reproduce, can you make a small example with the error?

**Comment by Corruptinator** [comment] 2017-07-29 21:17
I'm currently rendering out an example using a screen capture.

**Comment by Corruptinator** [comment] 2017-07-29 23:05
Here is an unlisted youtube link showing what is happening, for some reason when I do make the camera a child of a normal rigidbody with a normal mesh, it works fine. Where it breaks is when I imported the model from Blender using the Better Collada Exporter:

https://youtu.be/6sTjxIb7_uA

**Comment by Corruptinator** [comment] 2017-07-29 23:08
One time it just wouldn't render at all, but now it just causes the camera to zoom in even when I havent changed any camera settings. Somehow when exported from Blender, the rigidbody parenting setup is causing the camera not to work right.

Bottom line: Not all nodes are capable of making the camera node work right. There should be a way to preserve the camera setting and rendering to make sure nothing like what is shown in the video link happens.

**Comment by eon-s** [comment] 2017-07-29 23:33
A bit of confussion in my poor english xD
But check the scales of imported elements, the ' det == 0' usually refers to a problem with a Transform matrix determinant, look at the scales while running (remote inspector) too.

**Comment by Corruptinator** [comment] 2017-07-30 20:41
Ok, I'll check it out.

**Comment by reduz** [comment] 2017-08-31 12:03
i cant really say there is enough information on this report to make an idea of what is going on. A short example project would be great.

**Comment by reduz** [comment] 2017-09-01 17:30
closing unless an example project is submitted, I just cant figure it out from the information provided

**Closed by reduz** 2017-09-01 17:30 UTC
Labels: bug, topic:core
