### ISSUE TITLE
Rendering issue with DEPTH_TEXTURE reading.

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#50027] opened 2021-06-30 15:02 UTC
### Godot version

3.0 ... 3.3.2

### System information

Windows 10, GLES 3, Nvidia 1050 

### Issue description

I'm just reading the DEPTH_TEXTURE and don't expect any changes in the picture. I don't apply the received value anywhere. However, it seems that normals are inverted.

![image](https://user-images.githubusercontent.com/48552343/123983995-f6141880-d9cc-11eb-84ad-ec65f902d72b.png)

### Steps to reproduce

Just comment or uncomment reading DEPTH_TEXTURE.

### Minimal reproduction project

[depth_buffer_error.zip](https://github.com/godotengine/godot/files/6741883/depth_buffer_error.zip)

**Comment by Lexpartizan** [comment] 2021-06-30 15:28
Im sorry, i found same issue right now.
https://github.com/godotengine/godot/issues/29206

**Comment by clayjohn** [comment] 2021-06-30 16:26
Thanks for searching existing issues!

Duplicate of https://github.com/godotengine/godot/issues/29206

**Closed by clayjohn** 2021-06-30 16:26 UTC
