### ISSUE TITLE
Godot keeps preloading stuff within folders having .gdignore

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20743] opened 2018-08-05 18:06 UTC
Godot 3.1 master 464d59935dccd558e54f30de24c9ad8ce4e7b686
Windows 10 64 bits

I added a `.gdignore` to a folder in my project, however Godot keeps loading all the stuff in it on editor startup:
![image](https://user-images.githubusercontent.com/1311555/43688540-957de7ae-98e2-11e8-8345-8e90b91d6532.png)

Repro:
1) Open a project in the editor (use `-v` for verbose output)
2) Close the project
3) Add a `.gdignore` in a folder
4) Open the project again: files are still preloaded

**Comment by groud** [comment] 2018-08-05 19:09
I'm not sure this is how .gdignore is meant to be used. If it works like .gitignore you need a single .gdignore at the root and must specify, one per line, the folders you want to be ignored.

**Comment by Zylann** [comment] 2018-08-05 19:15
The way it was currently done is that all folders that have `.gdignore` in it should be ignored by the resource loader.

**Comment by eon-s** [comment] 2018-08-06 01:11
That ignore file is for the loader or the importer? I think it does not auto import but can load and probably import manually too.

**Comment by Zylann** [comment] 2018-08-06 09:27
@eon-s it should be both. Initially it was needed because Godot was trying to import `.obj` files which were actually compilation binaries and then choke on them, but more generally it's a way to have folders being ignored regarding any resource management (though file API should still work).
In that case I think Godot tries to load that stuff because a plugin is referencing them.

**Comment by vnen** [comment] 2018-08-06 16:01
I don't think this is a bug. If you are preloading things from somewhere, it doesn't matter where those things are. I mean, if you are trying to load a resource A and this resource depends on the resource B that is in an ignored folder, it should just load both. If the loading of B fails, this will cascade and fail A too, which is probably not what you want.

The `.gdignore` file is only meant for the importer. Native resources won't be affected.

**Comment by Zylann** [comment] 2018-08-06 17:25
@vnen wasn't it for the exporter as well? I would find awkward to have to tell the editor twice in two different ways to ignore the same folder...  but that would be another issue

**Comment by KoBeWi** [comment] 2020-06-19 13:16
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

btw, [according to documentation](https://docs.godotengine.org/en/stable/getting_started/workflow/project_setup/project_organization.html#ignoring-specific-folders), files in ignored folders can't be loaded with `load` and `preload`, so dependencies should probably fail too, for consistency.

**Comment by Zylann** [comment] 2020-06-19 23:19
I tried an MRP, could not reproduce this.
There is something a bit suspicious in my screenshot in the first post: my plugin was enabled and was probably the one loading all that stuff.

**Comment by fire** [comment] 2020-11-16 18:44
Closing since Zylann cannot reproduce.

**Closed by fire** 2020-11-16 18:44 UTC
Labels: bug, topic:editor, topic:import

**Comment by boruok** [comment] 2021-01-16 15:07
can any else reproduce this? i've putted .gdignore in /bin/screenshots/.gdignore and godot generates .import files, also textures appears in filesystem.

**Comment by KoBeWi** [comment] 2021-01-16 16:05
@boruok See #33314
