### ISSUE TITLE
Code scrolling and Editor slow on huge files due to connection information

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#32236] opened 2019-09-21 15:15 UTC
3.2 alpha 2e065d8ad
Windows 10

I hope this is the right place to ask questions about the beta and alpha build.  If not please direct me to the right spot.

I have a game with 25k lines of code.  Every time I open it in the alpha build, it takes 5 times as long to load and once loaded it will freeze a lot while scrolling through code or switching from one func to another another.

Are there any particular new settings in the editor that I can turn off to see if it will speed up?

**Comment by KoBeWi** [comment] 2019-09-21 15:32
Are you using custom build or a nightly one? This might be the same case as #32195

If it's not, code minimap might be the culprit.

**Comment by ondesic** [comment] 2019-09-21 15:39
Assuming it is a nightly from https://hugo.pro/projects/godot-builds/

I will check if minimap is the problem

**Comment by ondesic** [comment] 2019-09-21 16:03
After disabling code minimap, I still get the tremendous slow down.  I notice also that if I hover over a function name in the "function names" window, godot will freeze for 5 seconds and then the hover text will appear.  In v3.1, hovering over a function in the "function names" will almost instantly cause the hover text to pop up.
If I load a project that has 300 lines of code, everything is fast again.

**Comment by ondesic** [comment] 2019-09-27 17:37
here are 2 videos comparing the slow down.  Same big project opened in 3.1 and latest nightly 3.2 
The first video I hover over the function list in 3.1 and the hint dialog pops up almost immediately.  The second video freezes completely and stalls for a long time before the hint dialog pops up.

**Everything** is painstakingly slower while editing as well as navigating menus.  Every few letters of code typed and godot freeze for a little bit.  

[2 Videos.zip](https://github.com/godotengine/godot/files/3663918/3.1.zip)

**Comment by ondesic** [comment] 2019-10-09 20:07
from the post and video I provided above, are there any ideas as to what else I could disable or what the major bog down could be?  I just downloaded the latest alpha today and it has the same proglem

**Comment by lawnjelly** [comment] 2019-10-14 09:37
Wild hunch, try changing values in Editor settings->Low Processors Mode Sleep Usec and Unfocused. I'm only saying that because it is new for 3.2 and could possibly be e.g. thinking it was unfocused incorrectly. Worth ruling out anyway.

Also we fixed something in the polling of gdscript language server just a couple of days ago (where it was polling far too frequently) in latest master, so it is possible that this may have been affecting things (especially if it was polling 25,000 lines of code too frequently). So do try latest nightly build again to compare.

If you can run task manager and let us know what percentage of CPU godot is using in both 3.1 and 3.2 that might be helpful info, and even better if you could would be to profile it but you may not be familiar with doing this.

**Comment by ondesic** [comment] 2019-10-14 15:47
I will try the newest.  Any suggestions on a number to set Low Processors Mode Sleep Usec and Unfocused to?

**Comment by Calinou** [comment] 2019-10-14 15:57
@ondesic I think most of the slowdown was coming from the LSP polling. The "Low Processors Mode Sleep Usec" setting forces the editor to sleep at least this many microseconds before rendering another frame. The default value (6900) effectively caps the editor to 144 FPS (but note that V-Sync, which is enabled by default, will likely cap it below). Higher values will result in a lower FPS.

**Comment by ondesic** [comment] 2019-10-14 19:31
When I open the project in 3.1 the CPU usage is 3% almost always. 
When I open the same project in the latest nightly, while losing, anytime I click on a menu, click on code, or hover over the fuction names, the CPU jumps to 24%

**Comment by lawnjelly** [comment] 2019-10-15 09:02
And just to clarify, when you say 25k lines of code, is this gdscript?

**Comment by ondesic** [comment] 2019-10-15 15:09
Yes, all GDscript

**Comment by ondesic** [comment] 2019-10-19 21:04
Any more ideas I can test?

**Comment by lawnjelly** [comment] 2019-10-20 08:10
I just procedurally created a gdscript file that was 20k lines long for a test. It was a little bit slower but still quite usable.

However when I turned on minimap it was quite a bit slower (I have that turned off as I don't use it). But 20k lines in one file might be worse case for the minimap.

There may be something that is going on in your particular project which is causing the slowdown.

If you really want to track it down, short of putting your 25K project available for download, you would probably need to compile Godot from source (or have a version with symbols inside for the profiler), then run it with a profiler to try and detect the bottlenecks.

I've used 'very sleepy' in the past (http://www.codersnotes.com/sleepy/) on windows but most any profiler should do. You would want to turn the profiler on just for the period where you were messing around in the files and getting these slowdowns. The profiler will tell you the exact functions and lines of code which are taking up the most time.

To clarify when I mentioned a change you should be using a build after, it is this commit:
#32714

**Comment by lawnjelly** [comment] 2019-10-20 08:44
This is a profile of my build with a 100K line of code gdscript file, for reference. It may be something else that is bottlenecking your case.

![profile_godot_100Kfile](https://user-images.githubusercontent.com/21999379/67156903-5c055d00-f31c-11e9-9103-e3b2dc0b3106.png)

I know next to nothing about the gdscript parsing etc, so can only look for spikes on the profile. Nothing is jumping out at me as taking 'all the time', although there is probably room for lots of optimization for just moving around the file.

CowData resizing is generally a problem, probably in vectors, although there was a consensus to add a new more traditional vector on #irc shortly before GodotCon, which should help alleviate this kind of bottleneck.

Generally it seems to be doing an awful lot of allocating / deallocating for just moving around a file, whether that is the parser or the display code I don't know. Certainly the TextEdit itself may not be great with such big files.

Of course the other question is, is this 25K loc file actually game code? Or data? If it is data you may be better off loading it manually from a separate file. And could you separate this code into several files rather than trying to do it all in one?

**Comment by ondesic** [comment] 2019-10-21 16:54
Perhaps I can dabble in building and profiling Godot.
In the meantime here is what I have found:

- I first thought it was the "minimap".  However, 3.1 has the "minimap" and I have tested to.  In 3.1 there is no difference with the speed.
- If I open my project in 3.2, it takes 5x as long to load compared to 3.1.  
- Once loaded, the 3.2 editor is super slow until I close the 25k script.  The speed for 3.2 goes back to normal when small scripts are opened.
- Most importantly, the speed slowdown seems to be completely isolated to 3.2.  The 3.1 editor has no speed problems working with the 25k lines of code.

Is there an archive of the nightlies?  Perhaps I can go back and test them through time and see when the slowdown first started?

**Comment by Calinou** [comment] 2019-10-21 19:12
> Is there an archive of the nightlies? 

Unfortunately, I don't have space to store all the nightly builds, so you'll have to build commits manually to test them. Luckily, you can use [git-bisect](https://git-scm.com/docs/git-bisect) to efficiently test commits between a range (here, `3.1.1-stable..master`). This means you won't have to build and test *all* commits, only a subset of them.

**Comment by akien-mga** [comment] 2019-10-21 20:17
> I first thought it was the "minimap". However, 3.1 has the "minimap" and I have tested to. In 3.1 there is no difference with the speed.

3.1 doesn't have the minimal, it was merged in August (#31302).
You can try to disable it, there's a setting for it.

**Comment by ondesic** [comment] 2019-10-21 21:15
I have turned it off in 3.2 with no luck in solving the problem

**Comment by ondesic** [comment] 2019-10-22 04:41
Thank you so much for leading me in the right direction.  I am now Git bisecting and am narrowing it down.  I'll let you now what I find

**Comment by ondesic** [comment] 2019-10-22 13:40
Been testing all day and last night.  Every build **before** commit a6562cd0048f1dadb3c1ab2f8583e21251634365 is super fast with my huge code.  Here is where the problem started:

`commit a6562cd0048f1dadb3c1ab2f8583e21251634365
Date:   Sat Apr 20 12:51:25 2019 +0100

    Display connection information in the script editor

 editor/code_editor.cpp                  |   1 +
 editor/editor_settings.cpp              |   1 +
 editor/plugins/script_editor_plugin.cpp |  12 +++
 editor/plugins/script_editor_plugin.h   |   1 +
 editor/plugins/script_text_editor.cpp   | 165 +++++++++++++++++++++++++++++++-
 editor/plugins/script_text_editor.h     |  24 +++++
 scene/gui/text_edit.cpp                 | 126 +++++++++++++++++++++---
 scene/gui/text_edit.h                   |  21 ++++
 8 files changed, 335 insertions(+), 16 deletions(-)`

**Comment by Calinou** [comment] 2019-10-22 16:57
@ondesic Thanks for bisecting your way to the regression! This is going to be very helpful :heart:

**Closed** 2019-10-27 11:46 UTC
Labels: bug, regression, topic:editor

**Comment by ondesic** [comment] 2019-10-28 16:10
GREAT JOB!!
So much faster!!!
