### ISSUE TITLE
Button 'pressed' signal is called when released, and 'released' is not called

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6019] opened 2016-08-03 00:18 UTC
Tested on Godot 2.0.4 and 2.1 rc1, Windows 10 64 bits

`Button` (inheriting `ButtonBase`) defines `pressed` and `released` signals. However, only one of them gets triggered, and at the wrong moment:
`pressed` triggers when the button is released,
`released` is never triggered.

I expected `pressed` and `released` to be called at the moment indicated by their name.

Repro:
[ButtonReleased.zip](https://github.com/godotengine/godot/files/398409/ButtonReleased.zip)
Play the main scene, press, and release the button.

**Comment by eska014** [comment] 2016-08-03 02:06
This is a duplicate of #4625, see my comment there: https://github.com/godotengine/godot/issues/4625#issuecomment-218563160
See also #5696 and #5262

**Closed by eska014** 2016-08-03 02:06 UTC
