### ISSUE TITLE
Exported Variables disappearing in editor upon launching a scene

### ISSUE THREAD

**Issue by JWR26** [godotengine/godot#82266] opened 2023-09-24 20:54 UTC
### Godot version

v4.1.1.stable.official

### System information

Windows 10 Pro

### Issue description

When running a scene, the exported variables that have been set in the editor are "null" and causing a crash. Below is a screen shot showing the remote scene where the variables are null. This is followed by a screenshot of the local scene where we can see that the exported variables do not appear.

![image](https://github.com/godotengine/godot/assets/64645223/e946990f-db4c-4e75-a5db-b5746c95417d)

![image](https://github.com/godotengine/godot/assets/64645223/83b0eccf-044a-4663-a49c-fd4247d50b31)

On both screenshots, it can be clearly seen that there are 3 exported variables in the script of the scene in question.

Upon stopping the scene and returning to the editor, the exported variables have dissapeared from the inspector panel. Reloading the scene does not make them reappear. I am obliged to restart godot then reassign the exported variables.

This does not occur at regular intervals and happens intermittently, notably when I am editing the scripts of the "exported nodes" classes.

### Steps to reproduce

the error is happening when running the test_arena.tscn in entities/arena. Currently the exported variables are unassigned, so assign them (only one possible node per variable) and then run the scene.

Edit the scripts res://entities/ship/player_input_component.gd and res://entities/ship/weapon_component.gd for example then re-run the project. 

As mentioned in the issue, the problem happens sporadically therefore several reruns of these steps may be required to have the game crash on a null instance.

### Minimal reproduction project

[godot_export_crash_issue.zip](https://github.com/godotengine/godot/files/12709638/godot_export_crash_issue.zip)

**Comment by evvv-vvve** [comment] 2023-09-29 03:37
Can confirm I'm also experiencing this, 4.1.1 stable

**Comment by benfc1993** [comment] 2024-02-18 00:54
This appears to only happen when `interface/editor/update_continuously` is enabled

**Comment by BlackDragonBE** [comment] 2024-05-16 16:58
Happened to me in 4.2.2 stable. Update Continuously wasn't enabled, enabling it didn't change anything. Reloading the project fixes it.

**Comment by vnen** [comment] 2024-05-17 13:24
Could not reproduce on master. This needs more specific steps to reproduce, otherwise it's going to be difficult to pinpoint the issue.

**Comment by kwameopareasiedu** [comment] 2024-07-27 09:38
Also experiencing this with 4.2.2 stable. Included a screen recording for clarity

https://github.com/user-attachments/assets/6a2cec14-9905-445e-981b-706d21684372

![image](https://github.com/user-attachments/assets/674b008d-719d-4a77-b978-6ad16012fdbe)

**Comment by oebelysk** [comment] 2024-08-21 05:26
Had the same problem on 4.3 stable. When the project was saved or run, the variables and their values would disappear until the script was saved.

I am using VSCode as a text editor and the script was inheriting from another script that also had export variables. Restarting the project fixed everything however.

**Comment by eldinoyev** [comment] 2024-09-03 12:36
Same exact issue here with v4.3.stable.mono.official on MacOS. As others have said, reloading fixes the problem.

**Comment by TheOakleaf** [comment] 2024-09-13 16:22
Same issue at 4.3.stable.official Win11
using vsCode as an external editor.
Restarting editor fixes issue temporarily.

**Comment by BlackDragonBE** [comment] 2024-09-17 15:15
@vnen I think I finally found the root cause. In some instances, a script gets opened in Godot's script editor even though "Use External Editor" is enabled, this causes issues as Godot seems to try to update the script via the internal editor even though it should ignore that and use the code from the external editor.

I noticed I had several script files open in Godot every time the issue happened.

Steps to replicate the issue in Godot 4.3:

1. Turn off Use External Editor in Editor Settings.
2. Create a new script with a single @export, an AudioStream for example, and save the script.
3. Attach the script to a node in a new scene.
4. Save the scene.
5. Turn on Use External Editor in Editor Settings.
6. Open VS Code for example and use it to edit the script: add another @export and save the script.
7. Return to Godot, the new exported value should be visible. Try assigning anything to it and save the scene.
8. The new exported value disappears. 
9. Open the Script tab in Godot and close all scripts.
10. Save the script in VS Code again.
11. Try using the new exported value in Godot and save the scene. It should work as expected now.

That still doesn't explain why Godot still opens script files in its internal editor sometimes in the background, but it's a start.

**Comment by akien-mga** [comment] 2024-09-24 11:09
Fixed by #96007 (thanks @BlackDragonBE for confirming).

**Closed by akien-mga** 2024-09-24 11:09 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing

**Comment by AlegreAugustoGerman** [comment] 2025-04-23 00:05
tengo el mismo problema en godot 4.4.1 , no veo los @export en godot  tengo deshabilitado interfaz/editor/actualización, Usar editor externo en la configuración del editor,  probé con otros tutoriales pero desde que me lo descargue es así.
