### ISSUE TITLE
4.0 When exporting an array resource, the value cannot be set

### ISSUE THREAD

**Issue by PoisonousGame** [godotengine/godot#61653] opened 2022-06-03 06:16 UTC
### Godot version

V4.0 alpha9.official

### System information

Win11  GeForce GTX1060 6GB

### Issue description

4.0 When exporting an array resource, the value cannot be set. 3.x is normal
4.0 I write like this:
![image](https://user-images.githubusercontent.com/39994989/171797122-8b46d897-7c7b-4083-870c-f85fbb009f9d.png)
result:
![image](https://user-images.githubusercontent.com/39994989/171797236-452a3053-a689-43bc-beb6-dceaf7bc5925.png)

3.x I write like this:
![image](https://user-images.githubusercontent.com/39994989/171797323-72e8b750-1e26-4abc-bccb-39cac4dd67d7.png)
result:
![image](https://user-images.githubusercontent.com/39994989/171797378-e567ecee-bca6-4f81-adc0-2f5b9eca3b8d.png)

4.0 I write like this:
![image](https://user-images.githubusercontent.com/39994989/171797460-2b5fb71f-d272-4f9a-b0f8-9677e6dc2935.png)
result:
![image](https://user-images.githubusercontent.com/39994989/171797501-3d0a109c-c058-403d-b9e6-f542a97b8005.png)

### Steps to reproduce

.

### Minimal reproduction project

[4.0test.zip](https://github.com/godotengine/godot/files/8830011/4.0test.zip)
[3.xtest.zip](https://github.com/godotengine/godot/files/8830016/3.xtest.zip)

**Comment by Calinou** [comment] 2022-06-03 08:36
Duplicate of https://github.com/godotengine/godot/issues/58285.

**Closed by Calinou** 2022-06-03 08:36 UTC
Labels: bug, topic:gdscript
