### ISSUE TITLE
Problem clearing Cubemaps

### ISSUE THREAD

**Issue by ThomasMorley-T3D** [godotengine/godot#2016] opened 2015-05-31 17:53 UTC
![cubemap](https://cloud.githubusercontent.com/assets/11800663/7903001/2dc0aab2-0794-11e5-97fb-8a072b3dc077.jpg)
I think I found a bug... I can't clear a Cubemap from the WorldEvironment node once I have added it on my Linux OS. After you try to clear the Cubemap the editor starts messing up as well. Godot 1.1 stable

**Comment by akien-mga** [comment] 2015-11-06 11:40
Can you still reproduce this issue in the current master branch @ThomasMorley-T3D?

**Comment by akien-mga** [comment] 2016-05-20 13:42
Ping :)

**Comment by nunodonato** [comment] 2016-05-21 08:41
Yes this issue is still present. If you set a Mode to cubemap but dont have a cubemap assigned, things get messed up fast :)

**Comment by bojidar-bg** [comment] 2017-03-26 19:30
Uhm. What about current master?

**Comment by nunodonato** [comment] 2017-03-26 19:56
@bojidar-bg can't reproduce it in master any more. seems to be fixed. but perhaps it would be nice to fix it in the 2.x branch

**Comment by Chaosus** [comment] 2018-09-17 10:01
Closed as its fixed it in 3.x + its not critical + its very old

**Closed by Chaosus** 2018-09-17 10:01 UTC
Labels: bug, confirmed, platform:linuxbsd, topic:rendering
