### ISSUE TITLE
`Curve2D.get_closest_offset()` returns wrong value

### ISSUE THREAD

**Issue by MarcPhi** [godotengine/godot#62301] opened 2022-06-22 08:42 UTC
### Godot version

4.0 alpha 9

### System information

Windows 11, Vulkan

### Issue description

The method `Curve2D.get_closest_offset(point)` returns the wrong offset.
(looks like it also effect Curve3D)

Bug exists since 4.0 alpha 9.

### Steps to reproduce

```
var curve = Curve2D.new()
curve.add_point(Vector2(0,0))
curve.add_point(Vector2(10000,0))
	
print(curve.get_closest_offset(Vector2(5000,0)))
# returns 5415.22 should be 5000
```

**Comment by akien-mga** [comment] 2022-06-22 09:49
Probably a regression from #58152 or #58023, CC @raulsntos.

**Comment by MarcPhi** [comment] 2022-06-22 12:54
Found the problem: The _bake() function (in curve.cpp) is not properly working. The distance between two baked points is not  the bake_interval. 

test:
```
var curve = Curve2D.new()
curve.add_point(Vector2(0,0))
curve.add_point(Vector2(50,0))
curve.bake_interval = 5
var bp = curve.get_baked_points()
for i in len(bp)-1:
	print(bp[i].distance_to(bp[i+1]))
```
results in:
```
5.0000319480896
4.99504423141479
4.99979496002197
4.9999942779541
5.00514221191406
4.99794769287109
5.00040435791016
4.99457550048828
5.00242614746094
5.00007247924805
0.00456619262695
```
On longer curves (>10000) the distances between points can even reach values +- 0.5 of the specified bake_interval.

**Comment by raulsntos** [comment] 2022-06-22 16:32
I can reproduce this in `v3.3.stable.official` so I don't think it's a regression, it also doesn't seem related to the mentioned PRs since they were merged after 3.3 was released and they don't change the output of the provided code, it seems like this has always been the behavior of `get_closest_offset`.

As I understand it, I don't think the returned offset is meant to be the exact offset in the curve for the given point but more like out all the baked points get the offset for the baked point that is closest to the given point, so maybe this is more of a documentation issue. The distance between the baked points can never be guaranteed to be exactly `curve.bake_interval` and that may also need clarification in the documentation.

**Comment by CousCous4** [comment] 2022-12-13 23:06
This seems to be fixed in 4.0 Beta 8. I'm working in 3D and the following code prints 5000 correctly now after refactoring by @xiongyaohua :

	var curve = Curve3D.new()
	curve.add_point(Vector3(0,0,0))
	curve.add_point(Vector3(10000,0,0))
	print(curve.get_closest_offset(Vector3(5000,0,0)))
	# correctly returns 5000

Haven't tried 2D but think it might be fixed now too.

**Comment by MarcPhi** [comment] 2022-12-14 00:13
@CousCous4 it looks like it's not fixed for Curve2D

```
var curve = Curve2D.new()
curve.add_point(Vector2(0,0))
curve.add_point(Vector2(10000,0))	
print(curve.get_closest_offset(Vector2(5000,0)))
# returns 2410 should be 5000
```

It seems like the error is now greater than before.

**Comment by xiongyaohua** [comment] 2022-12-14 01:00
Strange. I should have fixed this. I'll investigate.

**Comment by xiongyaohua** [comment] 2022-12-14 02:03
> @MarcPhi  I think it should definitly try to match the bake intervall as much as possible (except the last).
> Thats why you would use get_baked_points() and not tessellate().

Currently the `bake_interval` means the upper limit of the lengths of baked segments. There is no guarantee that each segments are of the same length. This implementation method is chosen because the code is simpler and faster.

The main difference of `get_baked_points` and `tessellate` is the former is cached and the latter is calculated on the fly.

I think for most application it is not necessary to keep baked points perfectly spaced, as you can always `sample_baked()` or `sample_baked_with_rotation()` at fixed offset intervals.  You can even cache those sampled points for performance.

**Closed** 2022-12-14 10:26 UTC
Labels: bug, topic:core
