### ISSUE TITLE
Android compilation window shows two bars

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#48878] opened 2021-05-20 08:55 UTC
**Godot version:**

3.3.1 stable mono

**OS/device including version:**

win10 64

**Issue description:**

At the moment of clicking on the android icon to compile and run on an android phone, Godot shows two bars, the top bar does not show anything and when the compilation finishes the window disappears and a new window appears with a single bar (it is the top run bar that previously appeared in the initial window).

First window
![Captura](https://user-images.githubusercontent.com/19652075/118949857-ed560e80-b959-11eb-93e5-536395bda5d7.PNG)

Second window
![Captura2](https://user-images.githubusercontent.com/19652075/118949877-f21ac280-b959-11eb-9e12-0e5616e53c34.PNG)

**Steps to reproduce:**
Compile and run on an android phone

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-05-20 12:52
I think this is done by design when using one-click deploy. The first progress bar is about deployment itself, the second progress bar is about exporting (which is a subtask of the one-click deploy process).

**Comment by Torguen** [comment] 2021-05-20 12:55
Ah, I was surprised because this did not happen in the previous RC and stable versions.

**Comment by Calinou** [comment] 2021-05-20 12:56
> Ah, I was surprised because this did not happen in the previous RC and stable versions.

Are you sure about this? This is the kind of thing that may only happen from time to time, as opposed to always happening.

**Comment by Torguen** [comment] 2021-05-20 14:35
I am totally sure, at least in some RC versions the top bar did not appear.
That is, two bars never appeared at the same time as in the first image.

**Comment by m4gr3d** [comment] 2023-05-30 00:46
Closing as expected behavior.

**Closed by m4gr3d** 2023-05-30 00:46 UTC
Labels: discussion, platform:android, topic:editor, topic:export
