### ISSUE TITLE
Impossible to resize collision shape for tile when vertex outside of tilesheet

### ISSUE THREAD

**Issue by johhnry** [godotengine/godot#34970] opened 2020-01-09 21:50 UTC
**Godot version:** 
v.3.1.2.stable.official

**OS/device including version:**
Pop!_OS 19.10 (highly derived from Ubuntu)

**Issue description:**
I am following the tilemap tutorial in the documentation and accidentally I created a collision shape (rectangular) in an Atlas tile which is bigger than the size of the tilesheet : 

![Capture d’écran de 2020-01-09 22-41-50](https://user-images.githubusercontent.com/35373357/72107280-4b6bee00-3331-11ea-95e4-23a53a8a138e.png)

**Steps to reproduce:**
Now if I want to resize the rectangle collision shape to fit the tile, I can't select any vertex outside the tilesheet (but I can grab and move the two left corners).

**Minimal reproduction project:**
[tilemap.zip](https://github.com/godotengine/godot/files/4042642/tilemap.zip)

**Comment by Rottenburger** [comment] 2020-01-10 11:30
If you select "Keep polygon inside region Rect." then select one of the vertices inside the palette (see red circles) it resets the position of the two vertices that are 'out of bounds'

![solution](https://user-images.githubusercontent.com/40438324/72150071-90793a00-339c-11ea-9ee3-7fc676d9b892.png)

**Comment by johhnry** [comment] 2020-01-10 15:29
Hi,

Thanks for your answer.
Yes I tried that but it's a little bit hacky.

Have a nice day

**Comment by akien-mga** [comment] 2021-02-24 10:05
Reopening as the issue is still not fixed in 3.2.4 RC 3 and `master`, apparently #42150 did not work? CC @groud @DashCell

**Comment by DashCell** [comment] 2021-03-03 13:25
@akien-mga Could you, please, give me more details about the reproduction of the problem? as you can see, the collision rectangle corrects itself when it is larger than the area of ​​the tileset.

![34970](https://user-images.githubusercontent.com/28615299/109812121-6de25a00-7c0a-11eb-86e6-a1064f28cb2d.gif)

**Comment by DashCell** [comment] 2021-03-03 13:43
@akien-mga I am working on the problem. It was my mistake during my reproduction of the issue.

**Comment by dszhblx** [comment] 2021-03-10 08:20
The issue is still not fixed in 3.2.4 RC4.
Isometric tile game need it to be fixed.
Thanks

**Comment by dszhblx** [comment] 2021-03-15 12:55
The issue is still not fixed in 3.2.4 RC5.

**Comment by akien-mga** [comment] 2023-02-17 11:43
Fixed by #73218.

**Closed by akien-mga** 2023-02-17 11:43 UTC
Labels: bug, topic:editor, usability
