### ISSUE TITLE
Webassembly export fails to run on load (template bug)

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#16990] opened 2018-02-24 21:19 UTC
**Godot version:** v3.0 release_debug

**OS/device including version:** Arch linux, Chromium 64.0.3282.167, Firefox 58

**Issue description:** On trying to load the game, we get the following error:

```
Uncaught TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': parameter 9 is not of type 'ArrayBufferView'.
    at _glTexImage2D (http://pika.tech:83/index.js:4:239121)
    at __ZN22RasterizerStorageGLES316texture_set_dataE3RIDRK3RefI5ImageEN12VisualServer11CubeMapSideE (wasm-function[7793]:2120)
    at __ZN18VisualServerRaster16texture_set_dataE3RIDRK3RefI5ImageEN12VisualServer11CubeMapSideE (wasm-function[25230]:109)
    at __ZN13StreamTexture4loadERK6String (wasm-function[19617]:255)
    at __ZN33ResourceFormatLoaderStreamTexture4loadERK6StringS2_P5Error (wasm-function[19826]:46)
    at __ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error (wasm-function[26949]:186)
    at __ZN22ResourceFormatImporter4loadERK6StringS2_P5Error (wasm-function[28803]:107)
    at __ZN14ResourceLoader5_loadERK6StringS2_S2_bP5Error (wasm-function[26949]:186)
    at __ZN14ResourceLoader4loadERK6StringS2_bP5Error (wasm-function[26942]:906)
    at __ZN31ResourceInteractiveLoaderBinary4pollEv (wasm-function[29086]:644)
```

Happens in release and debug builds, but debug shows a better output log.

As a note, the last log line is:
```
**ERROR**: Condition ' image->is_compressed() ' is true. returned: image
**ERROR**:    At: drivers/gles3/rasterizer_storage_gles3.cpp:559:_get_gl_image_and_format() - Condition ' image->is_compressed() ' is true. returned: image
```

However, this is a red herring, it is actually a warning in the JS console. The true error only prints in the JS console.

**Steps to reproduce:**
Grab latest version of https://github.com/Calinou/godot-sponza
Grab latest export templates
Export as debug or release for HTML5 with default settings
After loading all the files, game crashes.

**Minimal reproduction project:**

https://transfer.sh/nJjB9/html5.zip Export that produced this error (expires in 14 days from time of posting - was too large to put on github)
Actual project is just a straight checkout of https://github.com/Calinou/godot-sponza and add HTML5, change no options

**Comment by eska014** [comment] 2018-02-25 11:32
duplicate of #15983, workaround there

**Closed by eska014** 2018-02-25 11:32 UTC
