### ISSUE TITLE
Light2D (Alpha Mask) ignores CanvasModulate

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#49244] opened 2021-06-01 18:17 UTC
**Godot version:**
3.3.2
3.3.1

**OS/device including version:**
Win 10 x64, GTX 1070, Driver: 462.59, GLES3, GLES2

**Issue description:**
If the Light2D goes over the Sprite, the sprite ignores the CanvasModulate Node.
Same for Label.

**Steps to reproduce:**
Add a Node2D, Sprite (with a texture), CanvasModulate and Light2D Node.
Set a dark color for the CanvasModulate.
For the Light, add a New ImageTexture, set the size to e.g. 64x64, change the color to transparent and set the mode to "Mask"

**Comment by Calinou** [comment] 2021-06-01 20:29
Duplicate of https://github.com/godotengine/godot/issues/37654.

**Closed by Calinou** 2021-06-01 20:29 UTC

**Comment by SmartySmart702** [comment] 2021-06-02 11:06
Oh sorry, my bad. Should have searched better.
