### ISSUE TITLE
Crash when Using Vulkan Mode and click "Display Desktop" Button

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [godotengine/godot#77052] opened 2023-05-14 05:27 UTC
### Godot version

4.0.3 rc1 till 4.1dev2

### System information

Windows 11, GLES3, x86_64, AMD APU A4-7210 with AMD R3 Graphics and AMD R5 M330

### Issue description

When Godot 4 runs in the background, if you click "display desktop" buttom on the right of the dock, it will crash, and today it crashed for xth time and i opened event logger, in which i found this:
**Source:**
Godot Engine

Date
‎2023/‎5/‎14 12:39
Event name:	APPCRASH
Application name:	Godot_v4.0.3-rc2_win64.exe
App version:	4.0.3.0
Application time stamp:	00000000
**Error module name:	amdvlk64.dll**
Error module version:	27.20.20913.2000
Error module time stamp:	62e93d35
Error code:	c0000005
Error offset:	00000000000714e2
OS Version:	10.0.22621.2.0.0.256.48
Area settings ID:	2052
Other info 1:	273f
Other info 2:	273f500d1bbb8d6ffaffe1dfdb2b962d
Other info 3:	4c82
Other info 4:	4c8296269a01841721fa80d09503848d

Extra info
Storage Segment ID:	7318944d0de4ed792d6c5617479555db (2120164182569866715)

### Steps to reproduce

1. Have a computer with AMD graphic card with driver version 27.20.20913.2000
2. Open Godot 4, and open a random project and run it in Vulkan mode (Forward+ or Mobile).
3. Click "display desktop" button and it will soon crash

### Minimal reproduction project

Nope

**Comment by Calinou** [comment] 2023-05-14 13:07
- Duplicate of https://github.com/godotengine/godot/issues/76709.

**Closed by Calinou** 2023-05-14 13:07 UTC
