### ISSUE TITLE
BoneAttachment3D gives errors if removed from scene tree then added again

### ISSUE THREAD

**Issue by A-Hugh-Mann** [godotengine/godot#81552] opened 2023-09-11 19:54 UTC
### Godot version

4.2.dev.custom_build.332bc469c

### System information

Arch Linux

### Issue description

If a BoneAttachment3D is removed from its parent with remove_child() an error will occur.

`Attempt to disconnect a nonexistent connection from '@Skeleton3D@31:<Skeleton3D#97123305808>'. Signal: 'bone_pose_changed', callable: 'BoneAttachment3D::on_bone_pose_update'.`

If that BoneAttachment3D is later added back with add_child(), another error will occur.

`connect: Signal 'bone_pose_changed' is already connected to given callable 'BoneAttachment3D::on_bone_pose_update' in that object.`

### Steps to reproduce

run this in a node somewhere on the scene tree.
```
var test: Skeleton3D = Skeleton3D.new()
test.add_bone("bone")
add_child(test)

var attach: BoneAttachment3D = BoneAttachment3D.new()
attach.set_bone_name("bone")
test.add_child(attach)

test.remove_child(attach) # gives error "Attempt to disconnect a nonexistent connection from..."
test.add_child(attach) # gives error "connect: Signal 'bone_pose_changed' is already connected to given callable..."
```

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment] 2023-09-14 18:57
Thanks for the report. Looks like a duplicate of https://github.com/godotengine/godot/issues/69614 with some minor variation, so closing this to keep discussion in one place.

**Closed by bitsawer** 2023-09-14 18:57 UTC
