### ISSUE TITLE
Camera2D doesn't get set as current when reloading scene

### ISSUE THREAD

**Issue by popcar2** [godotengine/godot#72612] opened 2023-02-02 16:23 UTC
### Godot version

4.0.beta17

### System information

Windows 10, GTX 1050 mobile, Compatibility renderer

### Issue description

I have one Camera2D in my scene. When I first run the game, it gets set as the main (current) camera, but when I run `get_tree().reload_current_scene()`, it doesn't reset to the new camera and just stays in the same position. It worked fine in beta16, so this is probably due to the [new Camera2D changes](https://github.com/godotengine/godot/pull/65698)

Quick video: 

https://user-images.githubusercontent.com/16920817/216381041-3b90b84a-f3af-4146-b842-2d599d69bd99.mp4

### Steps to reproduce

- Add a Camera2D to the scene
- Move the camera
- Run `get_tree().reload_current_scene()`
- The reset camera isn't set as current

Or just download the project below, run level 1, and hold 'R'

### Minimal reproduction project

[Platformer Quickstart.zip](https://github.com/godotengine/godot/files/10571049/Platformer.Quickstart.zip)

**Comment by akien-mga** [comment] 2023-02-02 16:34
Duplicate of #72074

**Closed by akien-mga** 2023-02-02 16:34 UTC

**Comment by popcar2** [comment] 2023-02-02 16:39
> Duplicate of #72074

I think you may have linked the wrong issue, this issue has nothing to do with renaming nodes
