### ISSUE TITLE
No editor description generated for export_flags

### ISSUE THREAD

**Issue by djpeach** [godotengine/godot#78353] opened 2023-06-17 00:55 UTC
### Godot version

4.0.3

### System information

MacOS Ventura 13.4

### Issue description

The comment description generation syntax does not work for the `@export_flags`

### Steps to reproduce

Create a project and attempt to give  descriptions to @export_flags variable

```
## this description does not show up
@export_flags ("RMB", "LMB") var consumable_inputs: int = 1
```

### Minimal reproduction project

NA

**Comment by dalexeev** [comment] 2023-06-17 07:30
![](https://github.com/godotengine/godot/assets/47700418/0a6f2b6a-1d16-4d85-8ce4-10bc8a889d8a)
![](https://github.com/godotengine/godot/assets/47700418/2b244ce2-a027-498c-ad67-fb79a18552fa)

* Duplicate of #70217.

**Closed** 2023-06-17 08:01 UTC
