### ISSUE TITLE
Viewport: Embed Subwindows option breaks tooltip and dropdown rendering

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#64754] opened 2022-08-22 22:44 UTC
### Godot version

0c5f254956f0115e363ce08045dd178dc30b54f8

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Using the "Embed Subwindows" option on viewports breaks tooltips and dropdowns:

![Screenshot from 2022-08-23 00-36-39](https://user-images.githubusercontent.com/347965/186031418-1e254d60-1aa8-4db7-be95-db158efa9c1a.png)

### Steps to reproduce

1. Add a viewport or window
2. Tick "Embed Subwindows"
3. Add OptionButton as a child
4. Run and click the button

### Minimal reproduction project

[tooltips.zip](https://github.com/godotengine/godot/files/9398044/tooltips.zip)

**Comment by Rindbee** [comment] 2022-08-22 23:19
Related to #64689 (possible duplicate).

**Comment by Calinou** [comment] 2022-08-22 23:20
Duplicate of https://github.com/godotengine/godot/issues/64689 (same cause).

**Closed by Calinou** 2022-08-22 23:20 UTC
