### ISSUE TITLE
Godot does not prompt to fix broken references.

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#77228] opened 2023-05-19 06:24 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

When a `Resource` (a script file in this case), referenced in another `Resource` (a scene file in this case), is moved outside of Godot (for example as a result of a merge), it leaves the invalid reference.

### Steps to reproduce

- Create a new project
- Create an scene
- Add a child node
- Create and attach a script to the child new
- Move the script outside of Godot

Observe:

Godot still references the old path of the script. Still shows the icon to open the attached script which result in an empty text editor. And trying to show the script in the FileSystem results in an error. You will also get "File not found" error when opening the project and when executing it.

Godot does not prompt to fix the broken reference, (nor removes it, nor creates a new script file), instead it keeps the invalid reference.

### Minimal reproduction project

[MovedScriptTest.zip](https://github.com/godotengine/godot/files/11514010/MovedScriptTest.zip)

**Comment by KoBeWi** [comment] 2023-05-26 06:41
Duplicate of #76941

**Closed by KoBeWi** 2023-05-26 06:41 UTC
