### ISSUE TITLE
Can't get shortcuts from EditorSettings

### ISSUE THREAD

**Issue by devvoid** [godotengine/godot#44307] opened 2020-12-11 22:27 UTC
**Godot version:**
Godot 3.2.3

**OS/device including version:**
Ubuntu 20.04.1 LTS

**Issue description:**
Function `get_shortcut()` in EditorSettings is not exposed to gdscript, making it impossible to get editor shortcuts in a plugin.

Judging by the code in `editor/editor_settings.cpp`, it looks like you're supposed to get shortcuts by prefixing its name with "shortcuts" (`shortcuts/editor/save_scene`, for example) but that doesn't work either.

**Steps to reproduce:**
* Call `EditorSettings.get("shortcuts/editor/save_scene")`
* See warning that `shortcuts/editor/save_scene` doesn't exist in editor settings
* Try to call `EditorSettings.get_shortcut("editor/save_scene")`
* See how gdscript complains that the function `get_shortcut` doesn't exist in `EditorSettings`.

**Minimal reproduction project:**
[PluginProblem.zip](https://github.com/godotengine/godot/files/5681866/PluginProblem.zip)

Enable the plugin included in the project to see the problem in action.

**Comment by SirQuartz** [comment] 2021-07-03 03:17
I can confirm that this behavior is odd, not only because it's not expected, but also because the method `get_shortcut` already exists within `editor_settings.cpp` is even used by other methods within the class, at least internally.

<img width="913" alt="editor_settings_get_shortcut" src="https://user-images.githubusercontent.com/62965063/124341525-f3f7b880-db8a-11eb-923f-db40fbb40875.PNG">

I've tried exposing the shortcut to GDScript:

<img width="913" alt="editor_setings_bind_method" src="https://user-images.githubusercontent.com/62965063/124341530-ff4ae400-db8a-11eb-864e-552a6868569d.PNG">

It compiles fine and even shows up in the editor with an autocomplete hint and appears in the class documentation:

<img width="501" alt="editor_settings_autocomplete" src="https://user-images.githubusercontent.com/62965063/124341543-1689d180-db8b-11eb-88d1-d6583e57b21a.PNG">

<img width="453" alt="get_shortcut_doc" src="https://user-images.githubusercontent.com/62965063/124341561-37522700-db8b-11eb-94c5-71b8b28c133f.PNG">

But when you actually try to use it it says 
<img width="764" alt="get_shortcut_error" src="https://user-images.githubusercontent.com/62965063/124341553-286b7480-db8b-11eb-9a0b-97ad2cdc10e8.PNG">

Not really sure what's going on here, but I'm not really the most familiar with C++ or with how Godot actually exposes things to GDScript, but I'm sure someone can find what's actually going on here.

**Comment by AnidemDex** [comment] 2022-03-07 03:55
There's a proposal to expose those functions (https://github.com/godotengine/godot-proposals/issues/4112) and a related pr that makes it possible (https://github.com/godotengine/godot/pull/58585)

**Comment by YuriSizov** [comment] 2022-09-05 15:21
Closing in favor of the aforementioned proposal.

**Closed by YuriSizov** 2022-09-05 15:21 UTC
Labels: enhancement, topic:editor, topic:plugin
