### ISSUE TITLE
Script names do not default to snake_case

### ISSUE THREAD

**Issue by IAmNotIsaac** [godotengine/godot#75037] opened 2023-03-17 18:43 UTC
### Godot version

4.0 stable

### System information

N/A

### Issue description

When creating scripts on nodes, the name will use the name of the scene if it is the root node (which does default to snake_case). This does not apply to unsaved scenes, children of unsaved scenes, or even children of saved scenes, where in which all should take on the snake_case of the node's name they are being applied to. See video attached.

https://user-images.githubusercontent.com/60862333/225991023-15f78b4d-4b77-46da-802a-3dab69bce25a.mp4

### Steps to reproduce

Setup is thoroughly described and visualised in both the issue description and the provided video.

### Minimal reproduction project

N/A

**Comment by IAmNotIsaac** [comment] 2023-03-17 18:47
Tested in 4.0 rc2, the issue remains. The setup is identical.

**Comment by Calinou** [comment] 2023-03-18 00:08
- Duplicate of https://github.com/godotengine/godot-proposals/issues/1211.

**Closed by Calinou** 2023-03-18 00:08 UTC
