### ISSUE TITLE
Godot froze by inflating the editor_settings.tres file to 385MB with 82 C2 and 82 C3 pairs of bytes

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#7251] opened 2016-12-05 22:54 UTC
**Operating system or device - Godot version:**
Arch Linux
Godot 2.2.r6004.4235abe (godot-git)

**Issue description** (what happened, and what was expected):
While working on a project, I added a Sprite and realized I have the filter on. I went to Project Settings, Image Loader, unchecked the box on the left of `filter` and suddenly Godot froze. I forcefully closed it by killing it's parent process (the desktop environment).

From that point on, every single attempt to start Godot ended in it being stuck on the logo screen with 100% CPU and ever-increasing memory usage.

Through the use of `strace` I have located the source of this bug to be the `editor_settings.tres` file, and immediately realized I was not wrong - the file weighed 385 MB. Through the use of `head` and `tail` commands I have managed to locate the position of the problem - the file was filled with pairs of bytes 82 C2 and 82 C3. However, this wasn't the whole file - the beginning was intact.

Further inspection revealed that the corruption started at the character that was supposed to be `ż` in the name of a different project (not the one I was working on before Godot froze for the first time) - represented as C5 BC in Unicode.

**Steps to reproduce:**
I have not yet found any way to reproduce this.
I have tried reimporting the two projects with a fresh `.godot`, and deselecting `filter` - which worked.

**Link to `editor_settings.tres`:**
https://zatherz.eu/junk/editor_settings.zip
Note: the zip is 3.6 MB, but 385MB after unpacking.

**Comment by BBric** [comment] 2016-12-06 19:29
I have the same bug (#6888) on Ubuntu, but i did not have notice the size increasing of this file (not at this point), after some launches (maybe 10) Godot don't start (memory dump error) and then reinitialize this file.

**Comment by bojidar-bg** [comment] 2016-12-06 19:39
Right, that's a duplicate of #6888 (and 6888 is such a nice number anyway... :smile:)

**Closed by bojidar-bg** 2016-12-06 19:39 UTC
Labels: bug, topic:core, topic:editor
