### ISSUE TITLE
remote debug leaves a large amount of Inspector items unset

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#45170] opened 2021-01-13 21:54 UTC
**Godot version:**
3.2.3

**OS/device including version:**
linux

**Issue description:**
Remote debug window leaves a lot of the panels completely blank making debugging impossible.

Here material is set
![image](https://user-images.githubusercontent.com/12863685/104514800-c2ddf880-55e9-11eb-8ce2-f40fe5a6d0ed.png)

In debug, it is completely blank, making checking what parameters have been set or if any dynamically loaded resources have been put in.

![image](https://user-images.githubusercontent.com/12863685/104514748-a9d54780-55e9-11eb-8beb-aa77410622eb.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-01-13 22:14
I don't think displaying shader parameters was ever supported in the remote inspector.

**Comment by chucklepie** [comment] 2021-01-13 22:50
Ok, but how is anyone supposed to debug? I know it's all about who has time to do it, but if you can inspect the data in code then that means it's not a technical issue...

I just find it odd that the Inspector is missing so much information in debug/remote, not just materials. Is it on any feature list to do this (add more node information to the debug)?

**Comment by Calinou** [comment] 2021-01-13 23:07
> Is it on any feature list to do this (add more node information to the debug)?

There are no plans to improve the debugging functionality for now.

**Comment by chucklepie** [comment] 2021-01-13 23:52
Ok thanks. I guess it's back to print statements.

**Comment by Calinou** [comment] 2021-03-25 20:00
Duplicate of https://github.com/godotengine/godot/issues/28353 (same cause).

**Closed by Calinou** 2021-03-25 20:00 UTC
Labels: bug, topic:editor
