### ISSUE TITLE
Move cs file to subfolder creates error "file not found" on start scene

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#16364] opened 2018-02-03 20:22 UTC
**Godot version:**
3.0rc1 mono version

**OS/device including version:**
Not related.

**Issue description:**
When I move a cs file to a subfolder and I want to run a scene, I get an error because the cs file cannot be found any more:

As it is german I translate it to english.

CSC(0,0): Source file "D:\Programmieren\godot\error\Test.cs" was not found

**Steps to reproduce:**
1. Create project, add a spatial node and attach a cs script called "test.cs".
2. Start the project - works.
3. create a subfolder with any name
4. move the cs file to the subfolder.
5. Start scene, get error as described

Something similar happen when you detach a script from the node and delete from the resource folder. 

**Minimal reproduction project:**
Not needed.

**Comment by RiverMesa** [comment] 2018-02-06 03:51
This is caused by the fact that the `.csproj` file does not automatically detect changes to `.cs` files (whether it's them being moved, deleted or renamed) - see #12917 and #12415.

You can either manually edit the `.csproj` file, or use a dedicated IDE that can automatically update `.csproj` files when changes occur, to resolve this.

**Comment by vnen** [comment] 2018-02-06 14:12
Closing this as duplicate.

**Closed by vnen** 2018-02-06 14:12 UTC
