### ISSUE TITLE
[3.2.4 rc2] Scene tree doesn't update after performing Merge From Scene

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#46047] opened 2021-02-15 11:19 UTC
Godot version:
3.2.4 rc2

OS/device including version:
Windows 10

Issue description:
When merging a node from another scene, the local scene tree doesn't update in time. This is newly introduced in `3.2.4.rc2`.

Occurs in `3.2.4.rc2`:
![rc2](https://user-images.githubusercontent.com/28705694/107939811-3a74be00-6fc2-11eb-8ba0-f24db8b5a7d9.gif)

Doesn't occurs in `3.2.4.rc1`:
![rc1](https://user-images.githubusercontent.com/28705694/107939798-3779cd80-6fc2-11eb-90d1-56734b8bc7e9.gif)

Steps to reproduce:
Create and save two random nodes as scenes, then merge one into another.

Minimal reproduction project:
[test.zip](https://github.com/godotengine/godot/files/5981201/test.zip)

**Comment by lentsius-bark** [comment] 2021-02-15 11:46
I can confirm, scene tree also doesn't automatically update when you save a branch as a scene.

**Comment by lawnjelly** [comment] 2021-02-15 11:56
Probably a duplicate of #45988

**Comment by akien-mga** [comment] 2021-02-15 12:02
Duplicate of #45988, fixed by #46048.

**Closed by akien-mga** 2021-02-15 12:02 UTC
