### ISSUE TITLE
Editor crash when i try to come back after project running on android

### ISSUE THREAD

**Issue by eksonmude** [godotengine/godot#83935] opened 2023-10-25 10:37 UTC
### Godot version

4.1.1.stable

### System information

Android

### Issue description

It's really sad to see new versions coming in but see godot mobile "crash editor on after project running back" bug still not fixed. My android 7 phone doesn't has any problems with this bug, but on my android 10 phone it's impossible.

Note: i don't know, but it's probably something about PID (i don't know what is it, i'm just sharing an option - based on my search here on issues page)

### Steps to reproduce

label

### Minimal reproduction project

label

**Comment by AThousandShips** [comment] 2023-10-25 10:39
Duplicate of https://github.com/godotengine/godot/issues/80000

**Closed by AThousandShips** 2023-10-25 10:39 UTC
