### ISSUE TITLE
Moving files in Godots "File System" view causes reimports and breaks references

### ISSUE THREAD

**Issue by MartinHaeusler** [godotengine/godot#29607] opened 2019-06-08 16:44 UTC
**Godot version:**
v3.1.1, Mono Edition

**OS/device including version:**
Windows 10

**Reproduction Steps:**
- I have a 3D model (an *.obj file) which I imported into Godot and placed in a 3D scene.
- I created a standard spatial material for the mesh and assigned it to the mesh.
- In Godots "file system" view created a subfolder as a sibling to the *.obj file and the material.
- Still in "file system", I click & drag the *.obj file and the material into the subfolder

**What happened:**
- Godot will now (for whatever reason) reimport the files as if they were new
- The mesh is still present in the scene, but the assignment of the material is gone.

**What should have happened instead:**
- Godot should have realized that moving a file does not require a reimport, as only the file location has changed, not its content. Furthermore, the move happened within the Godot editor, which is another reason why Godot should not have performed a reimport.
- Godot should have recognized that moving an asset file managed by Godot requires updating all references to it in the project.

This is a *major* pain, especially for larger projects this is a showstopper.

**Comment by LinuxUserGD** [comment] 2019-06-08 21:17
Do you can really assign a material to a the *.obj file?
I think you can only assign a material to a .tscn because assigning a material doesn't override the *.obj file, it's read-only.

**Comment by MartinHaeusler** [comment] 2019-06-08 22:22
Oh yeah, sorry, that's what I meant. I added the *.obj file to the project, dragged the contained mesh into the scene, then applied the material to the mesh in the scene. I don't know if using an *.obj file specifically has any influence on this at all, it's just what I did.

**Comment by KoBeWi** [comment] 2020-08-05 22:55
The re-import on move still happens in 3.2.3 rc3, not sure about breaking references.
@MartinHaeusler Did anything change? (include some minimal reproduction project if the issue is still valid)

**Comment by KoBeWi** [comment] 2024-04-23 09:56
Most of the file moving issues were resolved in Godot 4, so this is likely no longer relevant (please comment if it's otherwise, with a reproduction project).
Rescan after move is tracked by #50576

**Closed by KoBeWi** 2024-04-23 09:56 UTC
Labels: bug, topic:editor
