### ISSUE TITLE
Godot 3.2 Alpha-2 Glitchy tilemaps

### ISSUE THREAD

**Issue by Burchard36** [godotengine/godot#32884] opened 2019-10-17 03:08 UTC
**Godot version:**
3.2 Alpha-2

**OS/device including version:**
Windows 10 
Possible important?: 
GPU: Intel HD 4K
CPU: Core i5

Tried with GLES2 & GLES3
**Issue description:**
When painting Tile Maps the screen is really jittery, video attatched

**Steps to reproduce:**
Create a Tilemap in Node2D (I use hexagon tiles so i put the following Cell settings)

Half-Offset: Offset-X
Cell Size X: 122
Cell Size Y: 104

Every other settings on the tilemap are left untouched, ~~im not sure if the issue is caused because of the Offset-X or not haven't tried without it~~Its not an offset issue just tried it

**Minimal reproduction project:**
[New Game Project.zip](https://github.com/godotengine/godot/files/3737236/New.Game.Project.zip)

Once i find a good site for uploading a video to ill post it as a comment, for now ping me on discord for the video until i post it (@Notlad | Node (Grr)#8402 )

EDIT: Had to use youtube :( 

https://youtu.be/Zh2NxKrMs_A

**Comment by securas** [comment] 2019-10-17 13:58
Add to this... On windows
- Saving a scene whilst editing a tilemap causes the tilemap edit to stop working. Does not happen on mac osx.
- Changes of the some of the tilemap properties on windows do not take effect immediately. Especially glitchy with the center of the tile property.

**Comment by gusthe** [comment] 2019-10-18 17:58
I think it has something to do with godot's window size. On smaller displays I get this behavior, but not on my 1080x1920 monitor when godot is maximized.

**Comment by npip99** [comment] 2019-10-21 16:26
[In terms of you using YouTube, just an FYI you can upload gifs to github and they'll be rendered properly. Converting the video to a gif and drag-and-dropping it in will probably work just fine]

**Comment by Burchard36** [comment] 2019-10-22 04:53
i have tried a few things, not a larger moniter but i can try that in the next few days, also npip i tried uploading the video raw and github said "Nuh uh" 😂

**Comment by aaronfranke** [comment] 2020-01-15 23:15
The minimal reproduction project you posted does not contain a scene, it is empty except for the default stuff and one image called `plain_grass.png`.

**Comment by bojidar-bg** [comment] 2020-01-15 23:59
From the video this issue appears to be a duplicate of #28135 (fixed since 3.2 beta 3). Closing as such.
The later problems mentioned by @securas should probably be split off as separate issues.

**Closed by bojidar-bg** 2020-01-15 23:59 UTC
Labels: bug, topic:rendering
