### ISSUE TITLE
Doubles printed to tscn files vary based on build type, causing issues with source control.

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#33368] opened 2019-11-05 19:30 UTC
**Godot version:**
3.1 stable
3.1.1 stable
3.2 alpha3
**OS/device including version:**
Windows 10 MinGW builds
**Issue description:**
When saving scene files in windows 10 the `"%lg"` specifier behaves differently in `_snprintf_s()` used by MinGW vs `sprintf()` (or `_snprintf_s()` in msvc)

**Steps to reproduce:**
Load a scene with a very small float in one cell of a transform matrix:
e.g. edit  `godot-demo-projects/3d/ik/look_at_ik.tscn` and set 
```
[node name="Camera" type="Camera" parent="."]
editor/display_folded = true
transform = Transform( -4.37114e-08, 0, 1, 0, 1, 0, -1, 0, -4.37114e-08, 38.9742, 0.50733, -21.9354 )
```

and then save.

Load the project with the linux client and save the scene, `-4.37114e-08` will stay the same.

Load the project with the Windows client (Godot_v3.1.1-stable_win64.exe from godotengine.org, _works in wine_ !) and save the scene and the number will be saved as `-4.37114e-008`

**Minimal reproduction project:**
[ik.zip](https://github.com/godotengine/godot/files/3810829/ik.zip)

# Research

It seems like `_snprintf_s` in MinGW is broken, if we remove `#define snprintf _snprintf_s` from `ustring.cpp` the problem goes away!

https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L50

```diff
diff --git a/core/ustring.cpp b/core/ustring.cpp
index ff8fcaaaaf..8b129271ae 100644
--- a/core/ustring.cpp
+++ b/core/ustring.cpp
@@ -48,7 +48,9 @@
 #include <stdlib.h>
 #endif
 
-#if defined(MINGW_ENABLED) || defined(_MSC_VER)
+#pragma GCC poison _snprintf_s
+
+#if defined(_MSC_VER)
 #define snprintf _snprintf_s
 #endif
```

This would also help with this issue: https://github.com/godotengine/godot/issues/22324

Keywords: git version control float printf precision windows linux mingw

**Comment by jamie-pate** [comment] 2019-11-05 22:35
This test program when complied with `x86_64-w64-mingw32-gcc main.cpp -o main; wine main.exe` also has the extra leading 0 on the exponent:

```c++
#include <stdio.h>
#include <stdlib.h>

int main() {
    double num = -4.37114e-08;
    char buff[256] = {0};
    #define __
    printf("%lg\n", num);
    snprintf(buff, 255, "%lg", num);
    printf("%s\n", buff);
#ifdef _snprintf_s
    _snprintf_s(buff, 255, "%lg", num);
    printf("%s\n", buff);
#endif
}
```

**Comment by jamie-pate** [comment] 2019-11-05 22:52
Looks like a dup of https://github.com/godotengine/godot/issues/24137

**Comment by Calinou** [comment] 2019-11-05 22:59
Duplicate of #24137.

**Closed by Calinou** 2019-11-05 22:59 UTC
Labels: bug, platform:windows, topic:core
