### ISSUE TITLE
Wrong Catalan locale when printing OS.get_locale() on macOS.

### ISSUE THREAD

**Issue by hiulit** [godotengine/godot#33875] opened 2019-11-25 12:20 UTC
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Mojave 10.14.6 (18G103)

**Issue description:**

I have my OS locale set to **Català** (you have it under [Catalan](https://github.com/godotengine/godot/blob/54e97e5ee69f311b165effc5f84b2387017d40df/core/translation.cpp#L91)) but when I print `OS.get_locale()` I get `en_ES`, which I don't think it even exists. It should return `ca_ES` ([Catalan (Spain)](https://github.com/godotengine/godot/blob/54e97e5ee69f311b165effc5f84b2387017d40df/core/translation.cpp#L93)) in my case.

***Note***:
I have Godot's locale set to `en`.

**Steps to reproduce:**

Set the OS locale to **Català** (`ca_ES`) and print `OS.get_locale()`.

**Minimal reproduction project:**

Nothing to add here.

**Comment by akien-mga** [comment] 2019-11-25 12:51
Does it work properly in 3.1.2 RC 1 or 3.2 beta 2?

**Comment by bruvzg** [comment] 2019-11-25 13:51
Duplicate of #31673.

I have done some more testing, and I was able to reproduce it.

Running `.app` bundle always returns `en_XX`, running app from the console returns locale correctly.

**Comment by akien-mga** [comment] 2019-11-25 14:04
Closing as duplicate then.

**Closed by akien-mga** 2019-11-25 14:04 UTC
Labels: bug, platform:osx, topic:porting
