### ISSUE TITLE
Black strips in GLES 3 when using SSAO

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34580] opened 2019-12-24 11:06 UTC
**Godot version:**
Godot 3.2 Beta 4
**OS/device including version:**
Ubuntu 19.10 Nvidia 970  435.21
**Issue description:**
When I add to scene world environment with enabled sky and SSAO, then with default settings I get very strange black Black strips in 3D objects.

**Steps to reproduce:**
1. Move camera close to the plane
2. Rotate/move camera
![jfile](https://user-images.githubusercontent.com/41945903/71410428-7eca2f80-2645-11ea-8c15-eb509a181bff.gif)

**Minimal reproduction project:**
[AAAA.zip](https://github.com/godotengine/godot/files/3998120/AAAA.zip)

**Comment by Calinou** [comment] 2019-12-24 11:18
What's your Near and Far values defined in the View menu at the top of the 3D viewport?

**Comment by qarmin** [comment] 2019-12-27 14:38
I looked and I had Z-Far 10000(Z-Near was untouched), because in past I probably set this value in editor settings, because default 500 is too low for me and probably for a lot of other people.

**Comment by Calinou** [comment] 2020-02-28 17:41
Duplicate of #13129, which is now resolved in the `master` branch thanks to SSAO having been rewritten.

**Closed by Calinou** 2020-02-28 17:41 UTC
Labels: bug, topic:rendering
