### ISSUE TITLE
Any non-latin symbols make debugger swear

### ISSUE THREAD

**Issue by BeLuckyDaf** [godotengine/godot#4004] opened 2016-03-10 16:40 UTC
**Operating system or device:**
Windows 10

**Issue description** what happened, and what was expected):
I live in Russia, so I do have russian keyboard layout and if I write some russian letters or whatever it will not appear in the editor, and i won't be able to erase it or backspace. And I also won't be able to compile the code. The only way out is to undo the action by pressing Ctrl-Z.

Just letting you know :)

**Comment by volzhs** [comment] 2016-03-10 16:44
You can type and see by doing this.
http://docs.godotengine.org/en/latest/reference/changing_editor_fonts.html

**Comment by akien-mga** [comment] 2016-03-10 16:50
Duplicate of #871 (the issue being that the non ascii characters are added to the script, but not shown).

**Closed by akien-mga** 2016-03-10 16:50 UTC
