### ISSUE TITLE
Xbox gamepads return "__XINPUT_DEVICE__" instead of a unique number

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#51772] opened 2021-08-17 02:36 UTC
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

In my game the user can select which joystick want to use.
The problem, current godot version doesn't ensure a unique GUID to identify the joystick.
For example if the user connect two xbox controllers, get_joy_guid return:
"__XINPUT_DEVICE__"

I expect a way to get an unique identifier for each connected joystick, so I can restore the current joystick when the game is restarted.

### Steps to reproduce

Connect two xbox controllers and look at the get_joy_guid result for each joystick.

**Comment by hoontee** [comment] 2021-08-21 02:39
Duplicate of #29894.

> on Windows all XBox One controllers should be detected as an XInput device i.e. this is working as expected.

The GUID isn't unique between gamepads. If you were to connect any identical gamepads, `get_joy_guid` would return the same value for all of them.

**Comment by HeartoLazor** [comment] 2021-08-22 00:12
> Duplicate of #29894.
> 
> > on Windows all XBox One controllers should be detected as an XInput device i.e. this is working as expected.
> 
> The GUID isn't unique between gamepads. If you were to connect any identical gamepads, `get_joy_guid` would return the same value for all of them.

Then there isn't a safe way to get an unique id per joystick and guid is working as intended?
If the answer is yes, this is a feature request for a unique id per joystick.

**Comment by Calinou** [comment] 2021-08-22 00:15
> If the answer is yes, this is a feature request for a unique id per joystick.

This repository is now used for bug reports only. Feature proposals should be made on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository after searching for duplicates.

**Comment by madmiraal** [comment] 2021-12-29 10:46
> Then there isn't a safe way to get an unique id per joystick and guid is working as intended?

Yes, `Input.get_joy_guid()` is working as intended. It returns the product GUID used to identify the type of controller not the controller instance. The GUID is used by the SDL mapping to map the buttons and axes to the expected buttons, joysticks and triggers.

So this issue can be closed. See https://github.com/godotengine/godot/issues/51773#issuecomment-1002524312 for issues with identifying controllers between game restarts when creating your proposal.

**Closed** 2022-01-11 10:39 UTC
Labels: bug, platform:windows, topic:input
