### ISSUE TITLE
Animation Player Not playing the Animation

### ISSUE THREAD

**Issue by MigrelNB** [godotengine/godot#88219] opened 2024-02-11 22:06 UTC
### Tested versions

- Reproducible in 4.2.1 stable

### System information

Windows 11 4.2.1 stable Compatibility

### Issue description

I'm trying to make a game that has a square as the character and in his animations i use a lot of rotationing, positioning and scaling , my issue is with the jumping animation, on the editor it plays just fine:

https://github.com/godotengine/godot/assets/141843993/6645e5fd-740e-4281-a8d7-004ed12e902d

but when i enter the game, it doesn't work:

https://github.com/godotengine/godot/assets/141843993/07502a86-6754-4eba-865d-04a5aac7d972

here's my code for the character:

```
extends CharacterBody2D


const SPEED = 450.0
const JUMP_VELOCITY = -650.0
const Acceleration = 90.0
const Friction = 50.0
@onready var spr = $Sprite2D
@onready var Anim = $AnimationPlayer

# Get the gravity from the project settings to be synced with RigidBody nodes.
var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")


func _physics_process(delta):
	# Add the gravity.
	if not is_on_floor():
		velocity.y += gravity * delta
	
	# Handle jump.
	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = JUMP_VELOCITY
	elif Input.is_action_just_released("ui_accept") and not velocity.y > 1:
		velocity.y = velocity.y / 2

	# Get the input direction and handle the movement/deceleration.
	# As good practice, you should replace UI actions with custom gameplay actions.
	var direction = Input.get_axis("ui_left", "ui_right")
	
	if direction:
		velocity.x = move_toward(velocity.x, direction * SPEED, Acceleration)
		spr.flip_h = false
		
	else:
		velocity.x = move_toward(velocity.x, 0, Friction)
	if direction < 0:
		spr.flip_h = true
	
	Handle_Animation(direction)
	
	move_and_slide()
	
func Handle_Animation(direction):
	if direction:
		Anim.play("Run")
	else:
		Anim.play("Idle")
	
	if not is_on_floor():
		Anim.play("Jump")
	
```
	

### Steps to reproduce

-- Make an animation using the AnimationPlayer Node that scales an Sprite2D
-- Play it through code when the character isn't on the floor

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment] 2024-02-11 23:09
Keep in mind that this is not the place to ask for coding help. If you are not confident that this is a bug, I would heavily recommend asking first on the [Godot Forum](https://forum.godotengine.org/), or the other [communities](https://godotengine.org/community/) (such as official Reddit or Discord).

I don't personally believe this is a bug, but let's see. Change this line:
>```
>	if not is_on_floor():
>		Anim.play("Jump")
>```
To:
```
	if not is_on_floor() and not Anim.current_animation != "Jump":
		Anim.play("Jump")
```
See if that solves the issue.

**Comment by GreentheNinja** [comment] 2024-02-12 02:10
In my experience, playing the same animation multiple times shouldn't reset the animation unless it already ended. Instead, I believe the problem is that `Anim.play("Run")` or `Anim.play("Idle")` will *always* be called before `Anim.play("Jump")`, causing the animation to play all over again from the beginning.

**Comment by MigrelNB** [comment] 2024-02-12 11:45
Thanks for the help, although i tried both of the methods you guys mentioned none worked, but thanks still, i'll move this to the godot forums, and also sorry for posting this on the wrong place

**Comment by Mickeon** [comment] 2024-02-12 12:38
I am closing the issue as it is not a bug, but if something is wrong feel free to be against this.

After looking at it more, I do believe that what @GreentheNinja suggested _should_ do the trick. To reiterate, the problem is that because `play()` is called multiple times, the animation _looks like_ it is stopped, but it is actually restarting every time, every frame.
```GDScript
func Handle_Animation(direction):
	if is_on_floor():
		if direction:
			Anim.play("Run")
		else:
			Anim.play("Idle")

	else:
		Anim.play("Jump")
```

**Closed** 2024-02-12 12:38 UTC
Labels: needs testing, topic:animation

**Comment by MigrelNB** [comment] 2024-02-12 13:31
Oh, it worked this time, thanks
