### ISSUE TITLE
crash when loading a webp with wrong extension (jpg in this case)

### ISSUE THREAD

**Issue by frankiezafe** [godotengine/godot#25799] opened 2019-02-11 15:54 UTC
**Godot version:**

branch master, commit: 5e837b3f13ab1e3b31bb8d705e87820fa4eff21e

**OS/device including version:**

Linux Mint 18.2 Sonya 64bits

**Issue description:**

Editor crashes when trying to load a .webp with .jpg extension (downloaded from firefox).

**Steps to reproduce:**
- Download this image on your drive: https://images.designtrends.com/wp-content/uploads/2015/12/22072514/Seamless-Wood-Texture.jpg;
- create a material somewhere;
- try to load this image has a texure.

Good luck!

**Bug report**

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fafcf2694b0] (??:0)
[2] EditorPropertyResource::_file_selected(String const&) (/home/frankiezafe/forge.godot/godot/editor/editor_properties.cpp:1998)
[3] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[4] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:945 (discriminator 1))
[5] Object::emit_signal(StringName const&, Variant const**, int) (/home/frankiezafe/forge.godot/godot/core/object.cpp:1231 (discriminator 1))
[6] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:1288)
[7] EditorFileDialog::_action_pressed() (/home/frankiezafe/forge.godot/godot/editor/editor_file_dialog.cpp:358 (discriminator 4))
[8] EditorFileDialog::_item_dc_selected(int) (/home/frankiezafe/forge.godot/godot/editor/editor_file_dialog.cpp:536)
[9] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[10] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:945 (discriminator 1))
[11] Object::emit_signal(StringName const&, Variant const**, int) (/home/frankiezafe/forge.godot/godot/core/object.cpp:1231 (discriminator 1))
[12] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:1288)
[13] ItemList::_gui_input(Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/scene/gui/item_list.cpp:566 (discriminator 4))
[14] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[15] Object::call_multilevel(StringName const&, Variant const**, int) (/home/frankiezafe/forge.godot/godot/core/object.cpp:779 (discriminator 1))
[16] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:886)
[17] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/scene/main/viewport.cpp:1542 (discriminator 2))
[18] Viewport::_gui_input_event(Ref<InputEvent>) (/home/frankiezafe/forge.godot/godot/scene/main/viewport.cpp:1842 (discriminator 3))
[19] Viewport::input(Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/scene/main/viewport.cpp:2663 (discriminator 2))
[20] Viewport::_vp_input(Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/scene/main/viewport.cpp:1319)
[21] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[22] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:945 (discriminator 1))
[23] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/frankiezafe/forge.godot/godot/core/object.cpp:870)
[24] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/frankiezafe/forge.godot/godot/scene/main/scene_tree.cpp:262)
[25] SceneTree::input_event(Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/scene/main/scene_tree.cpp:418 (discriminator 6))
[26] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/frankiezafe/forge.godot/godot/main/input_default.cpp:414)
[27] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/frankiezafe/forge.godot/godot/main/input_default.cpp:260)
[28] OS_X11::process_xevents() (/home/frankiezafe/forge.godot/godot/platform/x11/os_x11.cpp:2137 (discriminator 3))
[29] OS_X11::run() (/home/frankiezafe/forge.godot/godot/platform/x11/os_x11.cpp:2973)
[30] /home/frankiezafe/forge.godot/godot/bin/godot.x11.tools.64(main+0xda) [0x116a240] (/home/frankiezafe/forge.godot/godot/platform/x11/godot_x11.cpp:56)
[31] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fafcf254830] (??:0)
[32] /home/frankiezafe/forge.godot/godot/bin/godot.x11.tools.64(_start+0x29) [0x116a099] (??:?)
-- END OF BACKTRACE --
```

**Comment by Anutrix** [comment] 2020-04-08 14:02
> 
>     * create a material somewhere;
> 
>     * try to load this image has a texure.
> 
Can you explain what you mean by this because I can't seem to reproduce the issue? Atleast no crashes.

**Comment by fire** [comment] 2020-10-27 03:44
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by fire** 2020-10-27 03:44 UTC
Labels: bug, crash, topic:core, topic:import
