### ISSUE TITLE
The content in the 2D editor cannot be manipulated normally

### ISSUE THREAD

**Issue by Vasilyevski** [godotengine/godot#72746] opened 2023-02-05 02:33 UTC
### Godot version

4.0beta17

### System information

Android10 MT6765 Mobile

### Issue description

When the 2D editor view is movable, manipulate the content in the editor and the editor view moves with the movement of your finger

https://user-images.githubusercontent.com/120901575/216798385-820893ca-7255-409f-be65-da0355654142.mp4

When the editor view is pinned, the operation is normal

https://user-images.githubusercontent.com/120901575/216798660-5901b9c4-9e40-4fa2-9d15-388332eb4962.mp4

### Steps to reproduce

Move, rotate, or scale content in the 2D editor

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment] 2023-02-05 09:35
This looks like a duplicate of #72385

**Comment by akien-mga** [comment] 2023-02-06 15:07
Indeed, closing as duplicate of #72385. Please add further information there if relevant instead of opening a new issue.

**Closed by akien-mga** 2023-02-06 15:07 UTC
Labels: bug, platform:android, topic:editor
