### ISSUE TITLE
Mouse cursor gets trapped in center of editor, have to forcefully restart it.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#18777] opened 2018-05-10 22:35 UTC
**This happens in 3.0.2**, and I'm using Windows 10.

I don't know the exact conditions to reproduce this, but it happens periodically when you try to drag and drop and texture from the file manager over to the node inspector.  When crossing the canvas, sometimes it will glitch out, and trap the cursor there.

The cursor vanishes and any attempt to move or drag it from there will get this crazy jittering as it seems to be fighting to force the cursor back to the middle of the canvas.  The only escape is forcefully closing Godot through task manager, alt+tabbing, etc.

Our work around has to be to save every time we successfully plant a texture.  X)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13004169/39897165-c3803c0a-54b9-11e8-87aa-f46f220a175f.gif)

_(The jittering is more rapid than is captured by this GIF)_

Although there isn't any obvious method to reproduce it, the fastest way seems to be by frequently and quickly dragging textures into the texture property of various Sprite nodes.  Sometimes waving the drag about randomly before getting to the inspector might also trigger it, because it may be something it hovers over at the wrong time that triggers it.

**Also, I have noticed this happen in 2.1 as well.**

**Comment by nobuyukinyuu** [comment] 2018-05-13 12:55
Check and see if you can get this happening more consistently if during a drag you hit the right mouse button at some point.  I'd like to know if it's related at all to #18647 / #17891.

**Comment by avencherus** [comment] 2018-05-13 16:37
@nobuyukinyuu No, it wasn't related to the right mouse button.  From looking at those references, it may be related to https://github.com/godotengine/godot/issues/17810.  Since  almost every time it happened to us it involved dragging a texture to a sprite node.

I should also add today when using 2.1, I had it happen when I was dragging a scene from the file manager to a selected node in the scene tree.  There were sprites in that scene, so it may or may not be because of the texture assignments.  It is really hard to determine what the conditions are to recreate it, so far it appears as if it were random.

**Comment by Web-eWorks** [comment] 2018-05-28 18:38
Can you confirm this is still happening on recent master builds? As of 37cda5795961c6eeca456aa38adb40a06cac5084, there are some improvements that may help this issue.

**Comment by nobuyukinyuu** [comment] 2018-05-31 15:08
I have tested the issue with actions which capture the mouse in ColorPicker, SpinBox and inside the new inspector.  No longer able to replicate the bug under the previous conditions, so it looks like these improvements have fixed the problem for me.

**Comment by Web-eWorks** [comment] 2018-05-31 16:43
@avencherus Can you confirm the issue is fixed?

**Comment by avencherus** [comment] 2018-05-31 19:33
@Web-eWorks I will give it a try, haven't done a build in some time, will this nightly build here ( https://hugo.pro/projects/godot-builds/) include these changes?

**Comment by Web-eWorks** [comment] 2018-05-31 19:37
The PR in question was merged 6 days ago, so the nightly should have it.

**Comment by avencherus** [comment] 2018-05-31 19:44
@Web-eWorks As far as I can't reproduce it.  Have dropped a few dozen sprites and scenes, no hanging.  I will let you know if it ever reappears.

Thanks for taking a look into it.  X)

**Comment by Web-eWorks** [comment] 2018-05-31 19:47
> Thanks for taking a look into it.

Taking a look into it? I fixed it! :smile:

@akien-mga I think this issue is resolved and can be closed now.

**Comment by akien-mga** [comment] 2018-05-31 20:31
Fixed by #19151.

**Closed by akien-mga** 2018-05-31 20:31 UTC
