### ISSUE TITLE
"Toggle comment" undesirable behaviour

### ISSUE THREAD

**Issue by vjrossi** [godotengine/godot#4198] opened 2016-04-02 11:29 UTC
Take any 3 consecutive lines of code (1, 2, & 3)
Place cursor at start of line 1.
Use keyboard (Shift Down-arrow) or mouse (click & drag down) to highlight lines 1 & 2 fully. Cursor is now at beginning of line 3.
Press Ctrl-K or Edit/Toggle comment

Expected: lines 1 & 2 commented out with # at start of each line (as these lines only, are highlighted)

Actual: lines 1, 2 & 3 commented out with # at start of each line

IMO this can create an unwanted comment-out line of code, often going unnoticed.

Note: if lines 1 & 2 are partially selected, then only lines 1 & 2 are commented-out.

I suggest my "expected" behaviour above, should be the actual, as per other code editors with a similar feature.

**Comment by akien-mga** [comment] 2016-04-02 11:51
I'm almost sure I saw an issue about this already, but I can't find it anymore :D If someone finds it, the least descriptive one could be closed as a duplicate of the other.

**Comment by Paulb23** [comment] 2016-04-02 13:37
@akien-mga You might be thinking of #3803

**Comment by akien-mga** [comment] 2016-04-02 13:51
Indeed, thanks. I can't tell if it's exactly a duplicate, but it could be that fixing this bug will fix the other if they have a similar cause in the selection mechanism.

**Comment by neikeq** [comment] 2016-04-02 17:52
I thought about applying the same rule to the first selected line, so if the selection starts in the last column (no text selected in that line) it wouldn't comment that line either. However, IntelliJ IDEA seem to comment that line anyway, so it may be the expected result. Thoughts?

@akien-mga @Paulb23 I don't think the issues are related, though maybe both can be fixed in a similar way.

**Comment by luiz-pv9** [comment] 2016-04-02 18:01
I just tested this behaviour and fixing (if it is really undesirable) was simple.

After [this line](https://github.com/godotengine/godot/blob/master/tools/editor/plugins/script_editor_plugin.cpp#L1258) in script_editor_plugin.cpp, I just added:

```cpp
int column_end = tx->get_selection_to_column();
if(column_end == 0) {
    // We're at the very beginning of the last selected line
    end -= 1;
}
```

@neikeq SublimeText works this way. It ignores the last selected line if the cursor is at the beginning.

**Comment by neikeq** [comment] 2016-04-02 18:14
@luiz-pv9 after decreasing `end` by 1 it should check if `begin` is greater than `end`, and do single line comment if true (like when there is no selection active). Otherwise it would result in nothing commented.

Regarding my question about other editors, I meant the column the selection starts from :P

**Comment by luiz-pv9** [comment] 2016-04-02 18:27
Oh, I see. That makes sense.

Regarding the begin > end check, I don't think it's necessary. The code I posted is already inside an `if` that checks if a selection exists (else do a single line comment). So it only decrements `end` if *a selection exists* and *ends in the first column of a line*.

**Comment by neikeq** [comment] 2016-04-02 18:45
Oh, never mind... I got confused because I was also increasing `begin` by 1 if no text was selected in that line. Fine then, feel free to open a PR :)

**Comment by luiz-pv9** [comment] 2016-04-02 19:18
@neikeq I finally see what you mean - sorry, slow day. If the selection starts at the end of a line where no text is selected, that line should *not* be commented. Correct me if I'm wrong, but it seems that the editor already "fixes" it by pushing the selection and cursor to the next line, not allowing a line with an empty selection.

1. Put cursor at the end of a line
2. Hold shift
3. Press down

The selection starts on the next line.

Anyway... thanks for the patience, this is my first time exploring godot's source. I'll send a pull request with a simple fix and we can improve from that.

**Comment by neikeq** [comment] 2016-04-02 19:37
Actually the editor seems to include that first line with no text selected. But, as mentioned above, I think that's fine since IntelliJ IDEA has the same behaviour (I couldn't test with any other editors), so your changes should be enough.

**Comment by vjrossi** [comment] 2016-04-03 22:10
Missed the discussion but thanks. Actually #3803, while unrelated does remind me that this toggle-comment action also creates multiple undo steps which is pretty tedious (and while undoing, even leaves your code temporarily in a state it was never in). Might open another issue for that.

**Closed** 2016-04-04 05:31 UTC
Labels: bug, topic:editor, usability
