### ISSUE TITLE
after clicking edit for a project I get a "blank" window that draws nothing

### ISSUE THREAD

**Issue by mutantbob** [godotengine/godot#31602] opened 2019-08-23 15:04 UTC
**Godot version:**
Godot_v3.1.1-stable_x11.64

**OS/device including version:**
Gentoo
Linux oasis 4.14.65-gentoo #1 SMP Thu Jan 10 10:26:50 EST 2019 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux
01:00.0 VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750] (rev a2) (prog-if 00 [VGA controller])

**Issue description:** **Steps to reproduce:**

In the Project Manager I select a project and click the Edit button.
A "blank" window appears covering the entire display (which is quite greedy on a 4K monitor).  The window isn't black, it just has whatever pixels were in the space before the window appeared.

The process is consuming >50% CPU in the background

**Minimal reproduction project:**
This same bug occurs when creating a new project.  

I have never been able to use the editor.  It always goes into this undead state.

I have no difficulty using blender (2.79) with cycles/GPU rendering, so my GPU isn't too broken.

**Comment by mutantbob** [comment] 2019-08-23 15:07
This problem also occurs on my laptop:

Linux herakleion 4.12.12-bob #38 SMP Sat Dec 9 23:32:34 EST 2017 x86_64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz GenuineIntel GNU/Linux
01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1) (prog-if 00 [VGA controller])

**Comment by Calinou** [comment] 2019-08-23 16:07
Can you see something if you resize the editor window?

**Comment by Garrom** [comment] 2019-08-23 19:03
What desktop environment are you using @mutantbob  ? I can tell it is not happening on my end with XFce. Maybe try install different DE and try if is happening on different DE too. You can uninstall this "testing" DE later.

**Comment by mutantbob** [comment] 2019-08-23 21:54
Resizing the window is the first thing I do (because a full screen 4K window is kind of hilarious).  It does not cause the app to draw anything.

**Comment by mutantbob** [comment] 2019-08-23 21:55
My desktop environment is fvwm.  Can you name a different window manager that I could invoke from the command line instead of fvwm?

**Comment by Garrom** [comment] 2019-08-24 11:53
@mutantbob To exclude (or prove) possibility that this is caused by desktop environment, try one I'm using, which is XFce https://wiki.gentoo.org/wiki/Xfce . You can login into xfce insted of fvwm and try start godot and see if it works or not

**Comment by mutantbob** [comment] 2019-09-05 19:01
Trying the xfce environment made Godot work (and littered my system with a dozen processes I had to kill to clean up my desktop when I switched back).

I wonder why Godot can't function with fvwm2 while blender works without a hitch.

**Comment by Calinou** [comment] 2019-09-05 21:18
@mutantbob Can you try building the latest `master` branch from source or download a [daily build](https://hugo.pro/projects/godot-builds/)? This may have been fixed by #31277.

**Comment by mutantbob** [comment] 2019-09-08 04:15
I will give it a try.  Maximizing seems like a really bad idea anyway, especially on 4K monitors.

**Comment by Calinou** [comment] 2019-09-08 12:15
@mutantbob The editor window is maximized automatically because this is what makes the most sense on most desktop and laptop monitors.

**Comment by mutantbob** [comment] 2019-09-10 15:22
Inkscape seems to want to maximize as well.  it is equally anoying, even when I'm not using a 4K monitor.  Basically any app that thinks it deserves a monopoly on screen pixels will be wrong when I am using it.  It seems like this might be a religious thing like emacs/vi, or strong/dynamic typing.

**Comment by akien-mga** [comment] 2019-11-08 13:59
Assuming fixed by #31277, please comment if you can still reproduce it in 3.2 beta releases.

**Closed by akien-mga** 2019-11-08 13:59 UTC
Labels: bug, topic:editor, topic:rendering
