### ISSUE TITLE
Raycast nodes don't take into account a rotation of a capsule collision shape

### ISSUE THREAD

**Issue by hormoz1** [godotengine/godot#3243] opened 2016-01-05 13:03 UTC
_bugsquadedit: Some small video footage that explains it very well:_ https://www.youtube.com/watch?v=sH4BqLvXerU&feature=youtu.be 
_Additionally project made by @hormoz1 but simplified a little:_ https://dl.dropboxusercontent.com/u/168251/godot/bugsquad/RayCapsuleProblem.7z 
 
---

Hello.
There is a problem that I think it is a bug in godot it is a little hard to explain but I will say example you have raycast object with ray to 0,-1,0 when you put it under a box shape it will detect a the collision but it will not detect a collision if you put it under a capsule shape(unless you put the raycast completely into the object or the ray to is (0,1,0) there is a project that you can download and see:
http://www.mediafire.com/download/8m503pg60zd3f2j/Fps.zip
In here the player won't fall because the gravity scale is 0.
You will see that the raycast 1 will detect collision with the T but the raycast 2 will not detect any collision with Player.

**Comment by kubecz3k** [comment] 2016-01-05 13:08
Was able to confirm this issue, will add short info at the beginning of the first post

**Comment by reduz** [comment] 2016-01-23 21:54
i think it's expected that rays shot from within a shape do not work, at least that is what i see in the demo

**Comment by kubecz3k** [comment] 2016-01-23 23:12
@reduz this makes sense, if ray origin position is outside the capsule it works as expected, shame I didn't noticed this earlier!
@hormoz1 Take a look at this, I'm not able to reproduce the issue anymore, so I'm assuming it was a case in your project as well.

**Comment by reduz** [comment] 2016-01-24 21:03
i'm closing it, i really can't reproduce :(

**Closed by reduz** 2016-01-24 21:03 UTC
Labels: bug, topic:core
