### ISSUE TITLE
Polygon2D antialiasing not working with GLES3 renderer 

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#41646] opened 2020-08-31 11:59 UTC
**Godot version:**
3.2.2 and 3.2.3.rc4

**OS/device including version:**
Windows 10, GeForce GTX 660

**Issue description:**
I enabled antialiasing for a Polygon2D and it had no effect when using the GLES3 renderer (worked fine with GLES2 tough). 

**GLES3 (AA not working):**
![gles3](https://user-images.githubusercontent.com/8750135/91716649-5c9f8e80-eb90-11ea-97e7-3b9da8e512ec.png)

**GLES2 (AA works):**
![gles2](https://user-images.githubusercontent.com/8750135/91716653-5f01e880-eb90-11ea-911d-69e579882277.png)

**Steps to reproduce:**
Create a Polygon2D with various angles and enable antialiasing.

**Minimal reproduction project:**
[Polygon2AntiAliasing.zip](https://github.com/godotengine/godot/files/5150122/Polygon2AntiAliasing.zip)

**Comment by Calinou** [comment] 2020-08-31 12:01
Duplicate of https://github.com/godotengine/godot/issues/10241. You have to disable HDR to fix it in GLES3.

**Closed by Calinou** 2020-08-31 12:01 UTC

**Comment by mbrlabs** [comment] 2020-08-31 12:09
I tried turning it off, but it didn't fix the issue. 
I also just tried it my Linux Laptop (UHD Graphics 620) and AA is not working there in either (GLES2 and GLES3 with HDR on and off).

**Comment by Calinou** [comment] 2020-08-31 12:37
@mbrlabs 2D antialiasing in Godot is known not to work reliably in general. I don't think much can be done about it before 4.0 is released.

**Comment by mbrlabs** [comment] 2020-08-31 12:45
@Calinou alright, thanks for your help!
It's not that big of a deal. I was just playing around with polygons while working on a prototype. I can live without them ;)
