### ISSUE TITLE
High pitched static noise without playing any audio

### ISSUE THREAD

**Issue by CoreTaxxe** [godotengine/godot#67457] opened 2022-10-15 18:45 UTC
### Godot version

4.0 beta 3

### System information

Windows 11, Vulkan, RTX 3070

### Issue description

High pitched Static Noise in almost empty scene without any audio related node in 3D
Pitch changes based on camera rotation and MeshInstance Material the camera is looking at. 

Im not talking about the normal speaker noise but the high pitched in between. Whenever I am tilting the camera towards the floor the pitch changes to the louder one and when looking back it becomes higher but more quiet.

https://user-images.githubusercontent.com/47256718/196002659-a784dfb1-1681-422f-afd6-161fe1e7e08a.mp4

Happens on EVERY speaker/headphone I try. 
ONLY happens in this specific project.
Across ALL betas and alphas. (8-13)
CAN NOT reproduce thus the attached Project.

### Steps to reproduce

No idea.

### Minimal reproduction project

[AudioBug.zip](https://github.com/godotengine/godot/files/9792847/AudioBug.zip)

**Comment by clayjohn** [comment] 2022-10-15 18:57
Have you confirmed that the sound is coming out of your speakers and is not coming from your CPU/CPU fan?

If the sound is coming from the computer (not through the speakers) the issue may be a result of the computer overworking itself from not having vsync on. In an empty or near empty scene without vsync, Godot will render as many frames per second as your computer can handle. This can lead to a high CPU/GPU load which stresses your system.

**Comment by CoreTaxxe** [comment] 2022-10-15 19:01
Indeed without vsync the issue no longer exists however the noise 100%
comes from the speakers and not the computer itself. (I asked my family as
well and only the person with headphones on could hear the noise)

Clay John ***@***.***> schrieb am Sa., 15. Okt. 2022, 20:58:

**Comment by TheDuriel** [comment] 2022-10-15 19:59
From the description it sounds like coil whine (typically high pitch hard to hear) or electric interference on a badly isolated motherboard (which ends up on the audio port and travels up into your headset).

Can you confirm the sounds till occurs when you have Godot muted in your OSs audio mixer? Can you confirm that a desktop recording contains the sound?

**Comment by CoreTaxxe** [comment] 2022-10-15 20:14
I've tested unity and unrealy and minecraft an none of those had any noise at all (at uncapped framerate with maxed out GPU and CPU). 

I dug a bit into coil whine and it appears it can change from application to application. Still odd it only happens in 4.x

(The same project has no noise AT all in 3.x + 3.x runs the same project at roughly double the fps)

**Comment by TheDuriel** [comment] 2022-10-15 20:28
> I've tested unity and unrealy and minecraft an none of those had any noise at all (at uncapped framerate with maxed out GPU and CPU).

This basically means nothing when it comes to coil whine. Yep.

> Edit : the noise persists with muted Godot (both editor and debug scene).

Last test you can do is to complete mute all system sound. But it sounds like it boils down to a cosmetic hardware error.

**Comment by fire** [comment] 2022-10-16 02:39
@RevoluPowered found some causes of audio error for the mac

**Comment by CoreTaxxe** [comment] 2023-02-17 13:52
It seems fixed in the master branch.

It's still noticeable in beta 3 but isn't in master. I can't tell when it vanished since I didn't really try the betas but its gone now 🤷. (Used the same project AND new ones.)

I'll comment again if it returns..

**Comment by akien-mga** [comment] 2023-02-17 13:53
Thanks, closing for now then.

**Closed by akien-mga** 2023-02-17 13:53 UTC
Labels: bug, needs testing, topic:audio

**Comment by Stalker2106x** [comment] 2024-11-12 22:17
For future readers,

Coil whine happens when FPS is outrageously high in any project.
Set a FPS limit to cap FPS, 300FPS seems like a reasonable amount, and works for me.
Setting can be found in **application >run > max_fps**
