### ISSUE TITLE
[4.0] Materials, duplicated in File Browser, affecting each copy (should get unique IDs instead)

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#64113] opened 2022-08-08 16:54 UTC
### Godot version

[4.0] alpha (any)

### System information

Windows 10, but it's irrelevant

### Issue description

- If you make a material and save it as a file, you can then make a duplicate in the file browser of Godot editor.
- Unfortunately, if you do so, you will be stuck in the broken scene loop:
- Editing each copy will affect their look in runtime (but not in the editor) – all of them will look the same in runtime
- Deleting any copy will break the game (and the scene), unless you'll re-create the same name copy (or clean the scene file manually)

So, you should not be allowed to copy material files, or they have to receive a unique ID if being copied. Otherwise, it will cause issues at runtime and the deletion of such broken materials.

### Steps to reproduce

1. Make a material
2. Save it as a file with .material format
3. Assign to something (like cube mesh)
4. Make another cube mesh
5. Duplicate the material in the file browser (with right click - duplicate)
6. Change new material
7. Assign to the second mesh
8. Run the game (all copies look the same)

Optionally:

1. Delete any copy
2. Run the game
3. It crashed, due to missed material (that isn't even used)

**Comment by Rinocrosser** [comment] 2022-08-08 17:06
PS. It is possible, that many other file formats (like scenes) are also affected, I just haven't faced this as my daily use case.  This one is just the most obvious one – make a copy of the material and just plug in some other maps.

**Comment by Calinou** [comment] 2022-08-08 17:22
Duplicate of https://github.com/godotengine/godot/issues/54774.

**Closed by Calinou** 2022-08-08 17:22 UTC
