### ISSUE TITLE
Vulkan: OmniLight shadows do not disappear when deactivated

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#62725] opened 2022-07-04 23:46 UTC
### Godot version

4.0 Alpha 11

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Omnilight shadows will not disappear when disabled via checkbox.
They will remain active, and will not update when the omnilight is moved.
Saving the scene, closing and reopening resolves this.

### Steps to reproduce

- Open the Minimal Reproduction Project, or create a new scene with a basic object and an omnilight
- Enable shadows for the sole omnilight
- Move the light around, shadows will update
- Disable shadows for omnilight
- Move it around, shadows will not update and will seem to be "dragged" along as the light is moved
- Disabling/re-enabling the light altogether does not resolve this. Only saving, closing the scene and reopening will resolve.

### Minimal reproduction project

[OmniLight_Shadows_Bug.zip](https://github.com/godotengine/godot/files/9042348/OmniLight_Shadows_Bug.zip)

**Comment by Calinou** [comment] 2022-07-04 23:53
Duplicate of https://github.com/godotengine/godot/issues/50343.

**Closed by Calinou** 2022-07-04 23:53 UTC

**Comment by WickedInsignia** [comment] 2022-07-04 23:56
Thanks. I always do a search for duplicates before I report but guess I missed this one!
