### ISSUE TITLE
Switching to another app and returning to Godot causes scripts to reload from disk, losing unsaved changes

### ISSUE THREAD

**Issue by sbruce** [godotengine/godot#4656] opened 2016-05-14 18:52 UTC
**Operating system or device - Godot version:**
Windows 10
Godot Version 2.0.3

**Issue description** (what happened, and what was expected):
If I have new, unsaved, code in a script and switch to another applications, when I return Godot the script is reloaded from disk and any unsaved changes are lost. Undo/Redo does not restore the changes.

I would expect when I returned to Godot that my unsaved changes would remain.

**Steps to reproduce:**
1. Enter new code into a script.
2. Switch to another app. Either CTRL+TAB or clicking on an app icon
3. Switch back to Godot.

**Comment by SuperUserNameMan** [comment] 2016-05-14 19:00
It happened to me once this afternoon, but i cant reproduce it.
Windows 8
official godot 2.0.3 win64

**Comment by vnen** [comment] 2016-05-14 19:44
Closing as a duplicate of #4444.

**Closed by vnen** 2016-05-14 19:44 UTC
