### ISSUE TITLE
Theme preview window needs a horizontal scroll bar, when the font is very large.

### ISSUE THREAD

**Issue by deaton1337** [godotengine/godot#39247] opened 2020-06-02 20:42 UTC
Hello,
I did search for this issue, so apologies if it's already been raised,

**Godot version:**
3.2.1 stable & 3.2.2 beta2

**OS/device including version:**
Windows 10 2004

**Issue description:**
When a dynamic font is added to an object and the size is set to (about) over 160, the theme preview window font size grows and forces any other windows off the side of the screen.
You then have to select Output, Debugger, Audio or Animation and resize the IDE to get it back. If you select the Theme preview again, it will resize the IDE.

**Steps to reproduce:**
Add a textbox, add some text, add a custom theme, default font and make the font size 200.

**What should happen**
(I think) The theme preview box should have a horizontal scroll bar, when required, so the IDE doesn't resize.

### This is font size 100 - Display 1920 x 1080 ###
![godot1](https://user-images.githubusercontent.com/19559049/83567312-5100e500-a519-11ea-8349-f0825fb23d46.png)

### This is font size 200 - Display 1920 x 1080 ###
![godot2](https://user-images.githubusercontent.com/19559049/83567392-71c93a80-a519-11ea-80dd-f2e0709b7f33.png)

**Comment by Calinou** [comment] 2020-06-02 20:49
Duplicate of #34509 and possibly others (the underlying issue is the same).

**Closed by Calinou** 2020-06-02 20:49 UTC

**Comment by deaton1337** [comment] 2020-06-02 21:02
Ah yes.. sorry ... thanks
