### ISSUE TITLE
argument list on get_method_list containing only useless data

### ISSUE THREAD

**Issue by MiroloTech** [godotengine/godot#80216] opened 2023-08-03 12:56 UTC
### Godot version

4.1.1 stable

### System information

Windows 11

### Issue description

when trying to acces arguments from the ```get_method_list()``` function, it always returns ```{ "name": "arg0", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }```, instead of the actual data. I acces the data like this:
```
var methods = p.get_method_list()
var args = methods[0].args
```

### Steps to reproduce

To test, enter this code into empty script and run:

```
extends Node

func test(a : String, b : String):
	return a + b

func _ready():
	var methods = self.get_method_list()
	for m in methods:
		if m.name == 'test':
			var args = m.args
			print(args)
			
			"""
			should return:
				{ "name": "a", "class_name": "Node", "type" : 4, "hint": .....,
				  "name": "b", "class_name": "Node", "type" : 4, "hint": .....,
				}
			"""

```

### Minimal reproduction project

unneccesarry

**Comment by AThousandShips** [comment] 2023-08-03 12:59
Duplicate of #33624

**Closed by AThousandShips** 2023-08-03 12:59 UTC
