### ISSUE TITLE
Crash when pressing Back button after running the project on Android

### ISSUE THREAD

**Issue by JoelMartinss** [godotengine/godot#80000] opened 2023-07-28 22:47 UTC
### Godot version

4.1.1

### System information

Mobile - Godot Editor 4 (4.1.1)

### Issue description

When I test the project on mobile, it runs normally. But when I press the button to go back to the project, it crashes (I can't go back to the project, just restarting the app)...The name "Mobile" in the upper-right corner turns red; I don't know if this has to do with anything.

### Steps to reproduce

There is no code, it's an app error

### Minimal reproduction project

N/A

**Comment by adamscott** [comment] 2023-07-30 16:30
Hi! Can you join the error stack that the system makes available when the crash occurs, if it is available? Right now, it would be difficult to debug.

Congrats for being the 80000th issue/pull request, by the way.

**Comment by Calinou** [comment] 2023-07-30 22:03
- Related to https://github.com/godotengine/godot/issues/77966 (possible duplicate).

**Comment by ZishAan23** [comment] 2023-08-18 03:28
Same thing is happening with me.
Pls can anyone solve it

**Comment by BurnSWE** [comment] 2023-10-20 07:51
I have the same issue on my phone Samsung Galaxy S9. 
When running a scene, I can't exit without having to close the entire editor.
This is not an issue when running scenes on my tablet, a Samsung Galaxy tab5. Then it closes down to the editor.

**Comment by Calinou** [comment] 2023-10-20 23:28
@BurnSWE Which Android versions are your Galaxy S9 and Tab S5 running respectively?

**Comment by BurnSWE** [comment] 2023-10-21 05:20
@Calinou 
Galaxy S9 is running android 10.
Galaxy Tab S5E is running android 11.

**Comment by Calinou** [comment] 2023-10-21 10:27
cc @m4gr3d

**Comment by eksonmude** [comment] 2023-10-25 10:28
that is true, on my android 7 phone everything is okay on project running, but on my android 10 phone (oh my god), it happens the same thing, the app crashes on back after i run a project.

**Comment by m4gr3d** [comment] 2023-11-03 14:07
Duplicate of https://github.com/godotengine/godot/issues/79291

**Closed by m4gr3d** 2023-11-03 14:07 UTC
Labels: bug, platform:android, topic:editor, needs testing, crash
