### ISSUE TITLE
Can't run scene with `.res` or `.tres` extension

### ISSUE THREAD

**Issue by RockyMadio** [godotengine/godot#35709] opened 2020-01-29 18:07 UTC
**Godot version:**
3.2 ( from 3.1)

**OS/device including version:**
Windows 10

**Issue description:**
Play scene - buttons do not work as intended (F5 and F6, and Ctrl+Shift+F5)
Our project runs flawlessly in 3.1. However by clicking any of those, the latest 3.2 will always play the default scene (in the config) .

Removed the path in default scene setting, F6 and Ctrl+Shift+F5 will launch the default Godot project manager (list of launchable projects). F5 will ask for scene.

Changing the default scene with another scene will temporarily fix the issue. But it will repeat again as you want to F6 one another scene.
**Steps to reproduce:**
I am not sure how to reproduce this. A new project will not show this issue. But our project has already reached a big scale. There must be some conflicts in one of the conflig files. Please help :(

You would reproduce the bug like this : Create 2 scenes, A and B, make A default scene, close A, and F6 with B. if the game runs with A, it is the bug.

**Comment by KoBeWi** [comment] 2020-01-29 19:12
What happens if you replace `project.godot` with an empty one?

**Comment by RockyMadio** [comment] 2020-02-14 13:28
I tried, and it still shows the same issue. The empty project just lets me reset the default scene. As I repeated all steps mentioned above, It still does not change.

**Comment by RockyMadio** [comment] 2020-03-05 20:25
This issue occures when you have main scenes as .res, changing them to .tscn will solve the problem.  Most of my assets are saved as .res, they still run properly.

**Comment by akien-mga** [comment] 2020-03-06 09:20
Why close it? It seems you found a workaround/explanation but the bug is still present, no?

**Comment by RockyMadio** [comment] 2020-03-07 01:14
> Why close it? It seems you found a workaround/explanation but the bug is still present, no?

i thought it was a mistake on my end -.- So do you think it is a bug?

**Comment by KoBeWi** [comment] 2020-03-07 17:57
Ok, I managed to confirm the issue. The problem is that you can't run scenes with `.res` extension (unless it's a main scene).

`.res` do appear as one of the extensions when saving scene
![image](https://user-images.githubusercontent.com/2223172/76149957-73639d80-60a5-11ea-9a13-fbe9bf7654a6.png)
so either the bug should be fixed or the extension removed from the list.

**Comment by akien-mga** [comment] 2020-03-09 08:49
While `.res` and `.scn` are exactly the same thing, I think it's likely fine to remove `.res` from the allowed extensions to reduce confusion. `.tres` is already missing even though it's also equivalent to `.tscn`.

On the other hand the engine itself should still be able to run scenes using `.tres` or `.res` if users do happen to force using these extensions for some reason. But if it works already with the main scene, I guess it's just the Play Scene code which adds this restriction.

**Comment by Calinou** [comment] 2020-04-29 12:58
This is likely a regression from #33149. I guess I should allow using `.res` and `.tres` to run scenes as well.

**Closed** 2020-05-20 09:46 UTC
Labels: bug, confirmed, regression, topic:editor
