### ISSUE TITLE
`parse_property` autocomplete raise bad signature error

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#75321] opened 2023-03-25 13:40 UTC
### Godot version

4.1.dev (4640b553a21) but present since 4.0

### System information

MacOS 13.1 M1 Pro

### Issue description

when autocompleting the `_parse_property` function with types it will raise bad signature error. 
<img width="1261" alt="Capture d’écran 2023-03-25 à 14 40 06" src="https://user-images.githubusercontent.com/66184050/227720683-86051bcb-f210-433a-acec-aa5c1f8e08f6.png">

This is because instead of completing with enum types it completes with int types. I don't know if this is a bug only in this function or in all function containing variable typed with enums as I don't know of any other virtuam function typed with enums 

### Steps to reproduce

1. activate add type hint
2. create a script inheriting EditorInspectorPlugin
3. start typing `func _parse_property`
4. autocomplete the rest

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment] 2023-03-25 13:43
Thanks for your report, this is a duplicate of https://github.com/godotengine/godot/issues/75311.

**Closed by YuriSizov** 2023-03-25 13:43 UTC
