### ISSUE TITLE
[3.5] MultiMesh Instance 2D crashes when adding a Mesh

### ISSUE THREAD

**Issue by jasonwinterpixel** [godotengine/godot#65795] opened 2022-09-14 19:42 UTC
### Godot version

3.5 Linux x11, Open GL ES 3

### System information

Linux Mint, OpenGLES 3.0, AMD Radeon RX 580 GPU

### Issue description

Adding a mesh to a MultiMesh which is a assigned to a MultiMeshInstance2D crashes in rasterizer_canvas_gles3.cpp with a segfault on this line:

`glDrawArraysInstanced(gl_primitive[s->primitive], 0, s->array_len, amount);`

At some point earlier, this is emitted as well:
```
ERROR: GL ERROR: Source: OpenGL Type: Error     ID: 1   Severity: High  Message: GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array)
```

### Steps to reproduce

Add MultiMeshInstance2D to a scene
Add a MultiMesh to the MultiMeshInstance2D
Add a Quad Mesh to the MultiMesh
Crash

### Minimal reproduction project

[TestMultiMesh.zip](https://github.com/godotengine/godot/files/9569427/TestMultiMesh.zip)
Open the TestMultiMesh scene.

Set the MultiMeshInstance2D to visible.

Crash.

**Comment by clayjohn** [comment] 2022-09-14 21:37
How reliably can you reproduce? 

I tried reproducing both from creating a project from scratch and from the MRP and I wasn't able to reproduce

I used Godot 3.5-stable, my system specs are PopOS 22.04 intel cpu and igpu

**Comment by jasonwinterpixel** [comment] 2022-09-15 03:33
I can reproduce it 100% of the time, with default settings, with a fresh download of godot 3.5.

**Comment by qarmin** [comment] 2022-09-15 08:33
Also cannot reproduce on Ubuntu 22.04 with GTX 970 and intel HD 3000

**Comment by lawnjelly** [comment] 2022-09-15 11:34
It is reproducing for me, with Intel HD graphics 630, Linux Mint 20.

```
1   ??                                                                                                                                     0x7ffff4b87a38 
2   ??                                                                                                                                     0x7ffff4b30e03 
3   ??                                                                                                                                     0x7ffff461288c 
4   ??                                                                                                                                     0x7ffff45dc748 
5   ??                                                                                                                                     0x7ffff45c7b9a 
6   ??                                                                                                                                     0x7ffff46a1863 
7   RasterizerCanvasGLES3::render_batches                                                                 rasterizer_canvas_gles3.cpp 947  0x422053e      
8   RasterizerCanvasBatcher<RasterizerCanvasGLES3, RasterizerStorageGLES3>::flush_render_batches          rasterizer_canvas_batcher.h 2525 0x422dd9b      
9   RasterizerCanvasBatcher<RasterizerCanvasGLES3, RasterizerStorageGLES3>::render_joined_item_commands   rasterizer_canvas_batcher.h 2634 0x4227334      
10  RasterizerCanvasGLES3::render_joined_item                                                             rasterizer_canvas_gles3.cpp 1430 0x4223161      
11  RasterizerCanvasGLES3::canvas_render_items_implementation                                             rasterizer_canvas_gles3.cpp 1915 0x4224a57      
12  RasterizerCanvasBatcher<RasterizerCanvasGLES3, RasterizerStorageGLES3>::batch_canvas_render_items_end rasterizer_canvas_batcher.h 819  0x4225f37      
13  RasterizerCanvasGLES3::canvas_render_items_end                                                        rasterizer_canvas_gles3.cpp 62   0x421bbde      
14  VisualServerCanvas::render_canvas                                                                     visual_server_canvas.cpp    272  0x624fcef      
15  VisualServerViewport::_draw_viewport                                                                  visual_server_viewport.cpp  231  0x62ab62f      
16  VisualServerViewport::draw_viewports                                                                  visual_server_viewport.cpp  342  0x62ac50c      
17  VisualServerRaster::draw                                                                              visual_server_raster.cpp    115  0x62430d2      
18  VisualServerWrapMT::draw                                                                              visual_server_wrap_mt.cpp   85   0x62b359c      
19  Main::iteration                                                                                       main.cpp                    2357 0x2d5b1e3      
20  OS_X11::run                                                                                           os_x11.cpp                  4035 0x2d0f55e      
... <More>                                                                                                                                                

```
Line is:
```
glDrawArraysInstanced(gl_primitive[s->primitive], 0, s->array_len, amount);
```
s->primitive is `VS::Primitive_triangles`, amount is ZERO, array_len is 6. It could be the zero causing it?

**Comment by clayjohn** [comment] 2022-09-15 15:49
Fixed by https://github.com/godotengine/godot/pull/65826

**Closed by clayjohn** 2022-09-15 15:49 UTC
Labels: bug, topic:rendering, needs testing, crash
