### ISSUE TITLE
Suggestion:  Material sphere display as option

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#6450] opened 2016-09-10 21:22 UTC
When editing a material in the visual editor, there is no button to hide the sphere.  This causes there to be a very limited amount of space to view parameters of the material and is really annoying.

**Comment by bojidar-bg** [comment] 2016-10-17 09:25
I think this is a dupilicate of #6542 (I prefer closing this one, since the other has way more publicity), am I correct?

**Comment by Noshyaar** [comment] 2018-04-06 10:36
Closing/Moving to #6542, also the issue is still relevant in 9ad1800 3.1 master

**Closed by Noshyaar** 2018-04-06 10:36 UTC
Labels: enhancement, topic:editor, usability
