### ISSUE TITLE
TabContainer is incompatible with keyboard/gamepad inputs

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#46111] opened 2021-02-17 08:09 UTC
**Godot version:**
3.2.3.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
I'm using a TabContainer to code my settings menu, but nothing I do changes the tabs on a gamepad or a keyboard. It really should *at least be functional* with all input types.

**Steps to reproduce:**
1. Add a TabContainer
2. Add multiple pages with focus-able items, such as `Button`
3. Attempt to switch pages using only a gamepad or keyboard

Problems:
1. ~~When cursor focus is lost from all elements, nothing will regain cursor focus except from a click.~~ Solved: If [Control.get_focus_owner()](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-get-focus-owner) is null, Control.grab_focus() a default element.
2. Even with cursor focus on any element, there is no way to select or change the tabs.

**Minimal reproduction project:**
[TabContainer.zip](https://github.com/godotengine/godot/files/5994163/TabContainer.zip)

**Comment by JapanYoshi** [comment] 2021-02-17 15:37
> This is something you can handle manually by calling the `grab_focus()` method on a Control node.
Is there a way to check if nothing is focused, besides iterating through every Node and seeing if it has focused?

**Comment by Calinou** [comment] 2021-02-17 15:55
> Is there a way to check if nothing is focused, besides iterating through every Node and seeing if it has focused?

Not that I know of, although I don't think it's too slow to check all controls to see if they're focused.

**Comment by ShatReal** [comment] 2021-02-18 04:43
Actually, you can use the [Control.get_focus_owner()](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-get-focus-owner) function.

**Comment by Calinou** [comment] 2023-02-16 01:29
Duplicate of https://github.com/godotengine/godot/issues/25877.

**Closed by Calinou** 2023-02-16 01:29 UTC
Labels: discussion, topic:gui
