### ISSUE TITLE
Using an external code editor prevents Godot from reloading tool and editor scripts

### ISSUE THREAD

**Issue by RabbitB** [godotengine/godot#17044] opened 2018-02-26 13:56 UTC
**Godot version:**
Godot 3.0.1 Stable win64

**OS/device including version:**
Windows 10 Pro x64

**Issue description:**
If you use an external code editor (in this case VS Code; I haven't tried other editors) to edit tool or editor scripts, the in-engine editor will update properly to display the changes you made to the script in the external editor, but Godot is silently failing to actually reload the scripts.

The effect is that you modify a script, test something that relies on that script, and find that your changes are not reflected on execution.

Because it's relevant, this is how I have VS Code setup:

```
Use External Editor: √
Exec Path: C:/Program Files/Microsoft VS Code/code.exe
Exec Flags: {project} --goto {file}:{line}:{col}
```

**Steps to reproduce:**

• Make sure `Use External Editor` is off
• Create a simple tool GDScript
```
tool
extends Node2D

func _ready():
    print("Visible Output Text")
```
• Create a simple scene that consists of a single Node2D with the previously created script attached.
• Save and close the scene, then reopen and read what's printed to the output window (will be "Visible Output Text")
• Edit the script so that it prints "Different Text" and save.
• Close and reopen the scene and read what's printed to the output window again (should be "Different Text")
• Now repeat this process, but first enable `Use External Editor`

From experimenting, it looks that as long as `Use External Editor` is active, Godot fails to reload the scripts, even if you close the external editor. The only way to make it reload the scripts is to close Godot entirely, and relaunch.

**Comment by neikeq** [comment] 2018-02-26 14:06
This is a duplicate of #10946, although this issue has some useful detailed information.

Just to be sure, do you see the error `ERROR: set_path: Another resource is loaded from path` on script reload when running Godot the terminal?

If not, is any other error printed to the terminal?

**Comment by RabbitB** [comment] 2018-02-26 14:17
There is no error printed to the terminal. The only time I see an error, is if I close Godot before closing the external editor. Then the terminal holds until the external editor closes.

These are the two errors I get in that instance:

`WARNING: ObjectDB::cleanup: ObjectDB Instances still exist! At: core\object.cpp:1989`
`ERROR: ResourceCache::clear: Resources Still in use at Exit! At: core\resource.cpp:418`

**Comment by T4g1** [comment] 2018-08-09 13:51
I have the same problem with an external editor both on platform x11 and windows with latest master. Also, console gives the following output:
```
ERROR: set_path: Another resource is loaded from path: res://Level/Level.gd (possible cyclic resource inclusion)
   At: core/resource.cpp:78.
```

**Comment by carlmartus** [comment] 2019-04-19 08:20
When I save from an external editor, I get two red lines in the *Output window*:
```log
 core/resource.cpp:79 - Condition ' exists ' is true.
 modules/gdscript/gdscript.cpp:557 - Condition ' !p_keep_state && has_instances ' is true. returned: ERR_ALREADY_IN_USE
```
The tool script is not updated after this. However, if I make any change in the script from the internal code editor. The script reloads successfully.

Version: *v3.1.stable.official*
OS: *Debian testing*

**Comment by takaturre** [comment] 2019-07-10 08:59
_Godot 3.1.1, Windows 10_
I also get the `Another resource is loaded from path ...  (possible cyclic resource inclusion)` error when creating a GDScript programmatically and resaving it over the old file. The error comes when opening a scene that references the script (on the root), but only if it had been in the editor script list previously but is not anymore. The problem is actually worse, when the old script is still in the editor's script list - in that case, I don't get any error, but the scene is actually referencing the old script. It will only update (and the error appear), when I close the script from the editor's script list, and re-open the scene. 

... Also tried removing the script from disk for a couple of frames and asking EditorFileSystem to `scan` and `update_path` as well as `script.reload()` but couldn't get it working. (The scanning seems to happen after a timeout, so maybe should wait for longer.)  ... Maybe if there was a command to "force refresh" or "unload" a script, it could work.. ? (Thought `update_path` would do that.)

**Comment by akien-mga** [comment] 2020-01-22 08:11
Closing as duplicate of #10946 (as should have been done [two years ago](https://github.com/godotengine/godot/issues/17044#issuecomment-368514013) to avoid having redundant reports in two different threads).

If anything discussed here is missing in #10946, please link or copy it over :)

**Closed by akien-mga** 2020-01-22 08:11 UTC
Labels: bug, topic:core

**Comment by luislodosm** [comment] 2021-05-30 23:39
Godot 3.3.2
Visual Studio Code 1.56
macOS 11.4

Error when editing a script externally:

<img width="591" alt="Captura de pantalla 2021-05-31 a las 0 38 56" src="https://user-images.githubusercontent.com/63356898/120123749-9dbce180-c1a8-11eb-8255-51d029c2d761.png">

**Comment by mehmet0zen** [comment] 2022-10-08 17:36
Apparently the error occurs when you turn on the **"Use External Editor"** settings, I made a source code search and it seems like they didn't implement a code for this, so it will give the error of `ERR_FAIL_MSG("Another resource is loaded from path '" + p_path + "' (possible cyclic resource inclusion).")` if you checked this;
<img width="894" alt="Screen Shot 2022-10-08 at 1 30 40 PM" src="https://user-images.githubusercontent.com/62778054/194720231-ef8bc786-2524-4ff3-8a95-016e05ca0ec6.png">
But if you uncheck it, it won't be usefull for the snippets, what I would suggest is, make sure that you filled the **Exec Path** Correctly, and there is nothing in **Exec Flags** that would brake the code.
