### ISSUE TITLE
Add: Binaries for headless/server versions of Godot with Mono

### ISSUE THREAD

**Issue by andrewdbanks** [godotengine/godot#25786] opened 2019-02-10 23:53 UTC
**OS/device including version:**
All desktop platforms

**Issue description:**
The available binaries for download on the main page are available in headless/server form, but only for Linux, and neither of them are Mono-enabled.  It would be great to be able to download those in Mono-enabled form for all operating systems.

**Comment by akien-mga** [comment] 2019-02-11 10:03
The headless/server platform only exists for Linux currently. See #11389.

Regarding distributing headless/server builds for Mono, that could likely be done, cc @hpvb @neikeq.

**Comment by andrewdbanks** [comment] 2019-02-11 13:29
> The headless/server platform only exists for Linux currently. See #11389.
> 
> Regarding distributing headless/server builds for Mono, that could likely be done, cc @hpvb @neikeq.

Yes, sorry, I should have linked that issue as well, since I was basically requesting the mono-enabled versions in addition to #11389.

**Comment by JoshLee0915** [comment] 2019-10-16 22:00
I hope this question is not out of scope for this issue or should have been asked on #11389, but does any one know what needs to be done to for Godot to support headless/server templates with mono? 

I noticed that the mono build scripts do not make checks for the server platform and I think the glue is not generating correctly so I assume it is not supported atm.

**Comment by neikeq** [comment] 2019-10-16 22:58
I think these may be already working with Mono, but I'm not sure. What I've tested is building with `platform=server tools=yes`.

What is the difference between server and headless? Are these supported as export platforms? All I can find in the 3.1.1 download files are `Godot_v3.1.1-stable_linux_headless.64.zip` and `Godot_v3.1.1-stable_linux_server.64.zip`. Are these built with `tools=yes`?

**Comment by Calinou** [comment] 2019-10-16 23:12
> What is the difference between server and headless? Are these supported as export platforms?

`headless` is an headless *editor*, i.e. `platform=server tools=yes`. `server` is an headless "export template", i.e. `platform=server tools=no` (note that there's no export preset platform for it yet).

**Comment by JoshLee0915** [comment] 2019-10-16 23:22
The problem I ran into while trying to build that with mono was this line here in the mono build scripts:
https://github.com/godotengine/godot/blob/119bf237209414a49879fba40459f22315ab1467/modules/mono/build_scripts/mono_configure.py#L265

This throws an assert false that crashes the build. I got it working by adding server to the list of platforms but I was also getting a segfault while trying to generate the mono glue though it generated fine if I ran it again. Also my attempts at running my built servers thus far have resulted in crashes due to what looks to be mono failing some assembly check. I am still digging into that issue though.

**Comment by neikeq** [comment] 2019-10-17 22:08
All right, I think `headless` is already working then. Although I've only used it for generating bindings.

`server` (the export template) should be ok after fixing those platform conditions in the build system (I've actually already fixed that in my local fork). However, I don't know how usable it will be without exporting from the editor (as there is no such export preset platform right now).

**Comment by dsge** [comment] 2019-10-18 19:26
So... is there a way to build a headless editor with mono support from the 3.1.1 stable release? I would use it in CI to automatically build (aka "export") releases after someone pushes new code. So basically I would like to have a headless mono version of the editor to build binaries for x11/windows.

By following the [Compiling with Mono](https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_mono.html) documentation I do not get far because as others pointed out there is no `headless` platform:
```
$ scons p=headless tools=yes module_mono_enabled=yes mono_glue=no
scons: Reading SConscript files ...
No valid target platform selected.
The following platforms were detected:
	haiku
	server
	windows
	x11

Please run SCons again with the argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
```
If `server` is in fact an export template rather than the headless editor then I'm sort of out of options. What am I missing? Is it possible to build this from the 3.1.1 release?

**Comment by Calinou** [comment] 2019-10-18 19:50
@dsge You can build an headless editor by using `platform=server tools=yes`. If you use `platform=server tools=no`, you'll build a dedicated server instead (without editor functionality).

**Comment by dsge** [comment] 2019-10-18 20:56
@Calinou Thank you for your quick response. I've tried to build it with `platform=server` which does kinda seem to work however when I export a game with it then the game fails to launch. If I export the game using the official 3.1.1 mono x11 editor (the one with GUI) then the game **does** launch.

Again, I'm following the [Compiling with Mono](https://docs.godotengine.org/en/3.1/development/compiling/compiling_with_mono.html) guide as closely as I can. 
I am using `monkey_pong` as my example: https://github.com/godotengine/godot-demo-projects/tree/master/mono/monkey_pong
I've opened this project using the GUI editor to generate an `export_presets.cfg`: [export_presets.cfg.txt](https://github.com/godotengine/godot/files/3745612/export_presets.cfg.txt)

```
$ git checkout tags/3.1.1-stable -b local3.1.1
```
```
$ scons p=server tools=yes module_mono_enabled=yes mono_glue=no
```
[editorbuild1.txt](https://github.com/godotengine/godot/files/3745580/editorbuild1.txt)
```
$ ./bin/godot_server.x11.tools.64.mono --generate-mono-glue modules/mono/glue
```
[generate-mono-glue.txt](https://github.com/godotengine/godot/files/3745581/generate-mono-glue.txt)
```
$ scons p=server target=release_debug tools=yes module_mono_enabled=yes
```
[editorbuild2.txt](https://github.com/godotengine/godot/files/3745585/editorbuild2.txt)
```
$ ./bin/godot_server.x11.opt.tools.64.mono \
     --path ~/workspace/godot-demo-projects/mono/monkey_pong/ \
     --export "Linux/X11" ~/workspace/deleteme/headlessbuild/pongdemo
```
[pongdemobuild.txt](https://github.com/godotengine/godot/files/3745587/pongdemobuild.txt)

After all these the game is exported as expected. However when I launch it the game window disappears after the loading screen and a `mono_crash.0.0.json` file appears next to the game files.
[mono_crash.0.0.json.txt](https://github.com/godotengine/godot/files/3745598/mono_crash.0.0.json.txt)

Since the official GUI editor (from [here](https://downloads.tuxfamily.org/godotengine/3.1.1/mono/Godot_v3.1.1-stable_mono_x11_64.zip)) **can** actually export a working version of the game (the game starts and works as expected) that means the issue is obviously with my headless build somehow. But I have no idea what the problem is or how to fix it. What am I doing wrong?

**Comment by JoshLee0915** [comment] 2019-10-22 05:34
@dsge After looking over you build output I think you are hitting the same problem as I am. In all my current tests I have been getting either the mono api out of sync issue that you are getting (if I am trying to run the headless) or a Mono: Core API hash mismatch if I try to use the server template I built. This is why I think it may be a problem with how the glue is being generated.

Its a bit late for me right now but I will attempt to generate the mono glue again tomorrow with the platform set to server and attach the build output of the segfault I get when I run it the first time in-case it is of help to anyone.

**Comment by JoshLee0915** [comment] 2019-10-22 14:47
After doing some more surface level digging I wonder if maybe it is related to the problem commit 1509890dbcca743cd306f55403be7a1729904652 was trying to fix and the server build is not properly defining `DEBUG_METHODS_ENABLED`. 

That would explain it for the release builds but does not fully answer why the debug builds are having trouble with the API Hashes when trying to build a mono enabled server unless my assumption of when `DEBUG_METHODS_ENABLED` should be defined is incorrect. 

@neikeq do you by chance have any additional information or thoughts around this?

**Comment by ricardoalcantara** [comment] 2019-10-31 18:11
@neikeq 

> server (the export template) should be ok after fixing those platform conditions in the build system (I've actually already fixed that in my local fork). However, I don't know how usable it will be without exporting from the editor (as there is no such export preset platform right now).

You could merge that change because it's just matter of export it for linux and change the binary to the server exported template.

And after that we will have godot mono headless and server working just like the ordinary binaries.

**Comment by JoshLee0915** [comment] 2019-11-01 00:45
I think I actually got this working and I plan on making a pull request myself if there is not one already once I have fully tested it.

**Comment by ricardoalcantara** [comment] 2019-11-01 02:12
@JoshLee0915 I thought the same, I already checked and there is no pull request, I am building 3.1.1 mono headless e server on linux, gonna test it too, and to build server I changed that line
file: modules/mono/config.py
```
270: if platform in ['windows', 'osx', 'x11', 'server']:
```

**Comment by JoshLee0915** [comment] 2019-11-01 05:25
Ok I think I actually have it running. I built both a server and headless and was able to export a project on a digital ocean droplet running a Ubuntu 18.04 server using Mono version 6.4.0.198. The project looked like it exported successfully even though I got a few errors at the end but these look to be clean up errors but here is a screen shot in case anyone cares.
![image](https://user-images.githubusercontent.com/10620778/68003590-9aabe900-fc33-11e9-895e-cf4d9f84d765.png)

The exported project is running but I am crashing when my script tries to call GetTree() and I am not sure why this is happening yet so there may still be an issue. I think it may be related to issue #30603 though since it looks to be a similar error.

I should note that I tested these changes on the 3.1 branch. I was having trouble getting the export templates to run properly in 3.2 for even an x11 or Windows system due to Core API mismatches which I think is related to the same problem references in issues #32185 and #33011.

@ricardoalcantara A quick note for you I think you need to add another server flag check to line 386 in 3.1

`elif platform == 'x11' or platform == 'server':`

A similar change needs to be done in 3.2 to line 389 in mono_configure.py. I was having trouble getting the binaries to run without having those copy over.

I think I may have hijacked this issue though since it is about adding Binaries for mono headless/server to the download page and not fixing build issues so unless I hear otherwise I'll make a new issue tomorrow for this.

**Comment by ricardoalcantara** [comment] 2019-11-01 23:05
@JoshLee0915 For 3.1.1 on linux remember to set MONO_THREADS_SUSPEND=preemptive at least I need to set it, it was fixed on 3.2.

https://github.com/godotengine/godot/issues/28667

And thanks for the 386 line tip.

**Comment by JoshLee0915** [comment] 2019-11-02 05:49
That was the problem @ricardoalcantara! Thank you so much for the tip!

**Comment by dsge** [comment] 2019-12-07 11:12
A quick update for me:

With the latest master ( 8eb183aebb9c79ff92d6f566af7ad2f91696ce08 ) I was able to build a working headless version of godot using the same exact commands I outlined in my [previous comment](https://github.com/godotengine/godot/issues/25786#issuecomment-543942242). No manual change was necessary to the source code on top of the latest master.

The tricky/confusing part was that the build (`scons p=x11 target=release tools=no module_mono_enabled=yes`) generates two things:
- a `data.mono.x11.64.release` folder
- and a `godot.x11.opt.64.mono` binary

Both of these would have to be moved to a `$HOME/.local/share/godot/templates/3.2.beta.mono` folder because that is where godot looks for them. However at that point you get a cryptic error message:
```
[...]
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:288.
ERROR: _fs_changed: Project export failed with error code 7.
[...]
```
This is because you also have to rename the `godot.x11.opt.64.mono` binary to `godot.x11.opt.64.mono` which I only guessed because this is how the official binary is called in my `templates/3.1.1.stable.mono` folder. After that the project could be successfully exported and this time the exported game actually ran:

https://imgur.com/fjvZXVO

**Comment by akien-mga** [comment] 2019-12-07 12:30
@dsge All this should be documented already in https://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html#building-export-templates and https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html#export-templates

Note that you're not building a headless binary with `scons p=x11`, the headless is `scons p=server tools=yes`.

**Comment by akien-mga** [comment] 2019-12-13 21:02
I'm building headless/server binaries for Mono since 3.2 beta 2: https://downloads.tuxfamily.org/godotengine/3.2/beta2/mono/

**Closed by akien-mga** 2019-12-13 21:02 UTC
Labels: enhancement, topic:mono
