### ISSUE TITLE
GLES2 Flickering lights

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#33110] opened 2019-10-27 13:30 UTC
**Godot version:**
3.1 Stable

**OS/device including version:**
Zorin OS 12 Core (Ubuntu 16.04 LTS)

**Issue description:**
Lights flicker in GLES2 wen moving/rotating the view/camera, this happens in editor, game and Android (maybe more but I only tested those). It happens to all light types (omni, spot and directional).
https://youtu.be/MZhBTE5mzkY

**Steps to reproduce:**
Just add some lights to an GLES2 scene and move the view/camera around.

**Comment by volzhs** [comment] 2019-10-27 13:37
I guess #28485 is related.
your scene has a pretty big mesh with more than 8 lights.

**Comment by Janders1800** [comment] 2019-10-27 13:45
No it doesn't. There are only 3 lights total, and the mesh is not a solid chunk, and even if it was, it shouldn't do that.

**Comment by Calinou** [comment] 2019-10-27 16:54
Can you reproduce this in 3.2alpha3?

**Comment by clayjohn** [comment] 2019-10-27 18:02
Looks like a duplicate of https://github.com/godotengine/godot/issues/28819 which was already fixed in master

**Comment by Janders1800** [comment] 2019-10-27 18:14
It seems to be fixed on 3.2 alpha 3

**Closed** 2019-10-27 18:27 UTC
Labels: bug, topic:rendering
