### ISSUE TITLE
Custom Bootsplash Image Doesn't Show Up On Android (Black Screen Instead)

### ISSUE THREAD

**Issue by TomatoVerified** [godotengine/godot#41089] opened 2020-08-06 20:26 UTC
**Godot version:**
3.2.2

**OS/device including version:**
N/A

**Issue description:**
Custom bootsplash image doesn't show, instead, a black screen appears.

**Steps to reproduce:**
export game as apk, install it on android phone, and open it.

**Minimal reproduction project:**
[Shadow Swiper.zip](https://github.com/godotengine/godot/files/5037802/Shadow.Swiper.zip)

**Comment by Calinou** [comment] 2020-08-06 23:09
Duplicate of https://github.com/godotengine/godot/issues/21824.

**Closed by Calinou** 2020-08-06 23:09 UTC

**Comment by MiqueiasDevGames** [comment] 2022-03-14 21:18
Solution:

Android 12 SplashScreen Godot


[https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12](https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12)
