### ISSUE TITLE
GiProbe baking problem

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#15184] opened 2017-12-30 04:46 UTC
**Godot version:**
build dated 29-12-17

**OS/device including version:**
Win10

**Issue description:**
When trying to bake the giprobe in my demo project("Headcase") I found that I am unable to bake the giprobe with the correct result. It has been about 6 weeks since I last touched this project, which is why it has taken me so long to report this issue.

In the following image, the correct gi bake is displayed on the left (from a build from 15th Nov). On the right is the same scene, but baked in a current build, showing a very odd result.

![gibug1](https://user-images.githubusercontent.com/7741669/34451294-e031c3ec-ed75-11e7-9f80-8c59d84fa93e.jpg)

After going through and testing a number of builds from November, I have isolated the problem to originating somewhere between 15th and 16th Nov. I am guessing that it is caused by either 7010ee3cb980fca18248fa168a4dabd78cf51e9d or 1980a54dbbb50f27b8560167683109c485dcf7c9
This scene is totally reliant up luminant textures and has no lights, so this looks likely to be the cause.

I am also noticing that bake times have increased dramatically since the progress bar was added. I just timed it in the build from 29thOct and it was about 10secs. In a current build, it takes about a minute, which doesn't sound like a lot, but is about a 6x increase. Not sure if this is solely due to the progress bar or not?

 I am now trying to do more work on this project so that I can release the project to the community in time for the Godot3 release early next year. Alas, I can't do any more work on this, until this is sorted out. Any help on this matter would be much appreciated :)

**Steps to reproduce:**

**Minimal reproduction project:**
Presumably @reduz is the only person who can work this problem out. Not sure if he has this project or not, but @Akien can link to it if required. Also @BastiaanOlij has confirmed that he had the same baking problem with this project file.

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by lehthanis** [comment] 2017-12-30 14:03
I think overall there's been some regression on GI proves. See #15164 also. @fracteed have you ever attempted overlapped gi probes?

**Comment by hpvb** [comment] 2017-12-30 20:59
Can you check to see what the results are with GIProbe compared to baking? Previously the baking generated a much lighter result than GIProbe which I believe was a bug previously. 

As for the speed, there are two possibilities:
a) Baking is now based on cell sizes which may have increased the amount of work required for that scene, depending on the settings you used previously
b) The official (beta) win32 binaries no longer have OpenMP support built in due to problems with extra DLLs being required.

**Comment by vnen** [comment] 2017-12-30 22:35
> b) The official (beta) win32 binaries no longer have OpenMP support built in due to problems with extra DLLs being required.

I don't think that's it, because OpenMP was added together with the lightmapper, and fracteed's reference build is 29-Oct, way before it was introduced.

**Comment by fracteed** [comment] 2017-12-30 23:00
@hpvb I have isolated the giprobe baking problem to have originated somewhere between the 15th and 16th of Nov. It works perfectly on the 15th, but on the 16th it exhibits this issue, which still exists in a current build. It is most likely one or both of the 2 issues I listed in the original post as they both relate to giprobe baking and emissions. My scene is totally reliant on luminant material emission and has no lights. Most people using giprobe are using lights with their scenes, which is probably why this issue has not been highlighted earlier.

With reference to the baking speed slowing down, it is related to this commit 495bcd730177f58053b8e76199d3ccd15ca0dcc9
If I try a build before this, it bakes in about 10 secs, after this commit it takes about a minute. Not sure if it is the progress bar or something else in the commit? Keep in mind that the scene had 2140 objects, so the speed issue is probably not really noticeable when people are trying giprobe baking with scenes of 200 or less objects. An actual game level would likely have many more thousands of objects than my scene.

 When working with luminant objects to light your scene, as opposed to using lights, a quick bake is a huge time saver as you are constantly moving items around, tweaking materials, then hitting bake just to see any lighting. As you could imagine, going from 10 secs to 60 secs really slows down the workflow. When using lights and gi, baking time is not as crucial, since the gi is just giving your bounced light and you can see your basic lighting in realtime. 

@vnen yes, this has nothing to do with recent developments with the lightmapper...I just wish I had found this issue earlier!

@lehthanis sorry, I have never tried overlapping probes. One of my goals on this project was to see how large I could make a level with a single probe. Any larger than what I have, I would have to add another probe. I would image that you have to get creative with the borders of the probes and hide them with geometry.

**Comment by lehthanis** [comment] 2017-12-30 23:15
@fracteed @reduz says they should overlap and blend just fine, so I'm eager to see how that looks and what tweaking it takes to get it to look good. 

I'm also super eager to see some of your level structure work and how things are organized.

**Comment by reduz** [comment] 2018-01-05 22:20
@lehthanis his project uses a single GIProbe, so not related I think
@fracteed are you sure it's not related to the propagation value? I think I may have changed the default value of propagation and you are just seeing that. Try setting it to 1.0 and it should work like it used to.

**Comment by reduz** [comment] 2018-01-05 22:21
I'm most likely sure it's the propagation, as it used to be in 1.0 and i can see in your screen that it's 0.85. Closing as I believe it's not a bug.

**Comment by akien-mga** [comment] 2018-01-05 23:21
From @fracteed on IRC:
> reduz: with regards to my gi baking issue that you closed, the propagation value makes no difference. There is something broken with texture emission and giprobe

**Comment by reduz** [comment] 2018-01-11 19:19
Ah, now that comes to mind, i think a bug was fixed regarding to texture emission and baking recently, i wonder if it had anything to do with this

**Comment by fracteed** [comment] 2018-01-11 22:12
@reduz I have older builds sitting here that I have tried several times from the 15th and 16th of Novemeber. Baking works fine before  7010ee3 and 1980a54 were added. It has been broken ever since for emissive materials. Have also tried it on a stripped down scene, so I know that it is not specific to just my demo scene.

**Comment by reduz** [comment] 2018-01-11 23:24
@fracteed but before those commits, emission textures were not supported.. so i am kind of puzzled.
I just removed an extra multiplication of emission that was not needed, though that will make emission even darker (unless you were using emission <0). can you give it a try?

**Comment by reduz** [comment] 2018-01-11 23:48
That was not a bug, and all code I can find seems to be correct. Maybe the old behavior was a bug.

**Comment by tagcup** [comment] 2018-01-12 00:12
The old behavior was indeed buggy. Before those fixes, energy value affected only emissive color and not the emissive texture.

Another behavioral change introduced in those commits was (may not be related) that is that when the material doesn't have an albedo channel, the output albedo is simply albedo color.

It's on this line:
https://github.com/godotengine/godot/blob/master/scene/3d/voxel_light_baker.cpp#L541

@reduz does this make sense to you?

The old code simply didn't output any albedo when the material lacked an albedo texture (code [here](https://github.com/godotengine/godot/blob/495bcd730177f58053b8e76199d3ccd15ca0dcc9/scene/3d/gi_probe.cpp#L954))


@fracteed  I can look into it further during the weekend if you can attach a simple scene

**Comment by tagcup** [comment] 2018-01-12 00:15
@fracteed BTW, can you not get a brighter scene by tuning energy and propagation values?

**Comment by fracteed** [comment] 2018-01-12 00:42
@tagcup would be great if you could have a look at the scene as well. The original demo scene file is at https://drive.google.com/file/d/1iOfUFM-yoppWObm3jdysw5wU0_6eyMVj/view?usp=sharing
When you open it in a current build, the cached gi is correct, but when you hit bake, you will see the issues. Let me know if you need any more details! (note I will delete this download link after a day or so, as it is not meant to be public yet)

**Comment by reduz** [comment] 2018-01-12 00:46
I am testing in special scenes and the GI baking seems perfect, I will probably have to assume the previous behavior was a bug and the way it is now is correct.

**Comment by reduz** [comment] 2018-01-12 00:51
@fracteed one thing I am noting from before and after is that objects will bake emission even if emission is disabled in the material. Maybe you have materials with emission values but disabled? other than that it seems it only worked for materials, but not textures.

**Comment by tagcup** [comment] 2018-01-12 01:11
@fracteed Thanks, I downloaded it

**Comment by fracteed** [comment] 2018-01-12 01:37
I have had a go at redoing the lighting, but have had to crank everything to its maximum. The emissive light materials are now at max on 16 (before was 8). The giprobe energy is at 16 (before was 5), dynamic range on minimum at 1 (before was 4). It is looking a lot closer now, but I still get none of the yellowish tint from the emissive color(have also added the same in the albedo). It makes the scene look monochromatic, whereas before the scene had all the yellow/orange warmth cast into the scene. Note that I am just using straight color for emissions, not an image texture.

![headcase_no_light_color](https://user-images.githubusercontent.com/7741669/34855695-342d33e0-f795-11e7-8048-07f1b15171a1.jpg)

**Comment by reduz** [comment] 2018-01-12 01:40
You likely want to increase the dynamic range, not decrease it

**Comment by fracteed** [comment] 2018-01-12 01:45
@reduz that is what I thought as well, but it is getting darker. Here is the same settings, with dynamic range at the other extreme...16

![headcase_no_light_color2](https://user-images.githubusercontent.com/7741669/34855918-76b46610-f796-11e7-82a2-bc249469fa6d.jpg)

**Comment by volzhs** [comment] 2018-01-12 02:01
I don't know much about 3d but... my 2 cents, shouldn't Auto Exposure be used in this scene?

**Comment by tagcup** [comment] 2018-01-12 02:18
Ah, no, I get it now.
It's a bug that I introduced on this [line](https://github.com/godotengine/godot/commit/1980a54dbbb50f27b8560167683109c485dcf7c9#diff-a33e6fd7cebf2d8c1785393b5110ff3eR963). I was thinking like Color was a RGB because all constructors in that code were 3-parameters, but it's actually RGBA.

So after my change, energy also multiplies the alpha too, sorry about that. 

Replacing

```cpp
float emission_energy = mat->get_emission_energy();
```

with something like

```cpp
float emission_energy_val = mat->get_emission_energy();
Color emission_energy(emission_energy_val, emission_energy_val, emission_energy_val);
```

should fix it

**Comment by fracteed** [comment] 2018-01-12 02:24
@tagcup awesome news! Did you get a chance to try it out on my scene? Is it likely that the original material and giprobe settings should work ok with this bugfix?

**Comment by tagcup** [comment] 2018-01-12 02:24
Actually, no, Color's operator* does more than multiplication, it clamps the values between 0 and 1.
Maybe we can add a pure multiplication function to Color

**Comment by reduz** [comment] 2018-01-12 02:30
oh, I see the problem now, Color operator clamps, there is no reason for it
to clamp... this also probably explains why the voxel cone trace baking was
not working.. I will remove the clamp.

**Comment by reduz** [comment] 2018-01-12 02:33
@tagcup I did not notice when operators for Color were contributed that they included clamping. Clamping makes no sense for this class, just removed everything and everything works great now.

**Comment by tagcup** [comment] 2018-01-12 02:36
@fracteed Yep, just tested and it works.

I basically added

```cpp
static Color color_mul_rgb(const Color &c, float s) {
	return Color(c.r * s, c.g * s, c.b * s);
}
```
in voxel_light_baker.cpp as a temporary workaround locally

and replaced * with that function here

```
		if (mat->get_emission_operator() == SpatialMaterial::EMISSION_OP_ADD) {
			mc.emission = _get_bake_texture(img_emission, Color(1, 1, 1) * emission_energy, emission_col * emission_energy);
		} else {
			mc.emission = _get_bake_texture(img_emission, emission_col * emission_energy, Color(0, 0, 0));
		}
```

which became

```
		if (mat->get_emission_operator() == SpatialMaterial::EMISSION_OP_ADD) {
			mc.emission = _get_bake_texture(img_emission, color_mul_rgb(Color(1, 1, 1), emission_energy), color_mul_rgb(emission_col, emission_energy));
		} else {
			mc.emission = _get_bake_texture(img_emission, color_mul_rgb(emission_col, emission_energy), Color(0, 0, 0));
		}
```

@reduz Leftover from pure SDR days I guess?
But should energy multiply the alpha at all? Maybe we do need something like `color_mul_rgb` above?

**Comment by tagcup** [comment] 2018-01-12 02:36
@reduz Ah maybe you meant removing the clamp and using

```cpp
float emission_energy_val = mat->get_emission_energy();
Color emission_energy(emission_energy_val, emission_energy_val, emission_energy_val);
```

**Comment by tagcup** [comment] 2018-01-12 02:43
BTW a little tangential but did GI baking get slower? Maybe that just because the geometry in @fracteed scene is a little involved

**Comment by reduz** [comment] 2018-01-12 02:48
No.. the progress bar is adding some delay, need to make it update less often

**Comment by reduz** [comment] 2018-01-12 02:49
@tagcup I am removing clamp from all the Color operators, they dont make sense as far as HDR is involved.

**Comment by fracteed** [comment] 2018-01-12 02:56
@tagcup great to hear that the scene will bake correctly again :)

And yeah, the baking time is massively slower since the progress bar was added. As I noted in my original post it has gone from about 10 secs to about a minute on my quadcore laptop for this demo scene. The irony is that the progress bar usually freezes at about the 200 object mark and just hangs there!

**Closed** 2018-01-12 03:11 UTC
Labels: bug, topic:rendering

**Comment by tagcup** [comment] 2018-01-12 03:27
@reduz I think we still need to replace

```cpp
float emission_energy = mat->get_emission_energy();
```

with something like

```cpp
float emission_energy_val = mat->get_emission_energy();
Color emission_energy(emission_energy_val, emission_energy_val, emission_energy_val);
```

in voxel_light_baker.cpp 

Right now emission energy is still affecting alpha.

**Comment by reduz** [comment] 2018-01-12 03:29
I think alpha is ignored in emission anyway.

**Comment by tagcup** [comment] 2018-01-12 03:34
Ah OK I see

**Comment by fracteed** [comment] 2018-01-12 06:58
Just built the master to test, and it all looks good, so thanks for the fixes guys! 

Still, concerned about the baking time being so much slower than it used to be. I even tried adding a couple of more 00's to the variable that reduz changed and recompiled. So it would only update about every 20 seconds, but it still didn't really speed up baking time. Is there anything else that can be changed to get it back to its former speed glory?...was such a pleasure to use when it was about 10secs for a bake :)

**Comment by tagcup** [comment] 2018-01-12 15:59
Great
It'd probably be a good idea to open a new issue for that
