### ISSUE TITLE
[2.1] rigidbody gets stuck in between tiles when following a navigation2d path

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#8184] opened 2017-03-28 09:18 UTC
**Operating system or device - Godot version:**
Windows 8. Godot version 2.1.2

**Issue description:**
at random times, but at the same position, a rigidbody or kinematicbody will get stuck in between tiles when following a navigation2d path.
Attached a gif file presenting the error, and the project used for testing. Is not a collision problem, there are no collisions shapes on the tiles tested with.
![nav_error](https://cloud.githubusercontent.com/assets/16140708/24397727/d3987694-13af-11e7-80f2-6a1607187c39.gif)
[test_prj.zip](https://github.com/godotengine/godot/files/878061/test_prj.zip)

**Steps to reproduce:**
move the mouse on the region presented on the gif file. Seems the errors appears as a function of the distances it has to travel, or maybe it depends only on the starting point.. could not say for sure.

[Edit: attached the correct project]

**Link to minimal example project:**

**Comment by nunodonato** [comment] 2017-03-29 06:34
The scene in the example project doesn't match the gif, so I dont know if I'm testing it correctly but couldn't replicate this bug here.

Linux, Godot 2.1.2

**Comment by plucian** [comment] 2017-03-29 06:45
arrrrr..sorry about that. I edited the initial comment adding the correct project.

**Comment by nunodonato** [comment] 2017-03-29 08:31
This is not a bug in the navigationpath but in your code
you can easily fix this by changing the code to

`var distance = points[points.size()-2] - get_global_pos()
if (distance.length()<1):
	distance = points[points.size()-3] - get_global_pos()`

**Comment by plucian** [comment] 2017-03-29 09:19
I "fixed" it before submitting the report, in a slightly different way (when distance is less than 1... here I tried many values...  then switch to next point).
The question stands, why that happens ? The navigation returns correct, values, is it because of the "move" function that can't deal with smaller than 1px values ? What is the reason for moving back when that happens ? This issue appeared many times in the QA questions. And that moving back behavior happens often, but not always. Sometimes stops entirely the moving, sometimes is just a small back and forth move, but the movements continues in the right direction.

**Comment by nunodonato** [comment] 2017-03-29 09:53
You are right, I'm tweaking a few things and it seems the values returned sometimes have strange values

**Comment by nunodonato** [comment] 2017-03-29 10:31
I think this might be a precision issue, as I'm getting points that seem to be rounded to the player position, and thus sometimes it moves it opposite direction.

I'm not familiar with the pathfinding code, so perhaps we'll have to wait until @reduz can take a look at this...

**Comment by plucian** [comment] 2017-03-29 12:53
well, I implemented your solution (was simpler than what I had) and it happened again when going up. The problem with the fix, is that, sometimes that distance need to be less than one, for a sharp turn.

**Comment by nunodonato** [comment] 2017-03-29 13:15
yeah, I know... its possible to get some hacks in there to fix these cases, but its better to fix it well :)

**Comment by plucian** [comment] 2017-03-31 16:43
seems every hack I put in there, still fails at some point...arr

**Comment by bojidar-bg** [comment] 2017-08-15 07:55
Closing as duplicate of #10324, which is somewhat clearer about the root problem. (Decided after discussion with @karroffel)

**Comment by plucian** [comment] 2017-08-18 10:17
the problem is still there even with mister Shaper's fix, and is true, the root problem is not clear.

**Comment by bojidar-bg** [comment] 2017-08-18 10:45
@plucian Are you sure you are testing on 3.0/master branch? The fix hasn't been ported to 2.1 yet.

**Comment by plucian** [comment] 2017-08-18 11:23
I thought it was actually ported to 2.1: 
https://github.com/godotengine/godot/pull/10377
am I wrong ?

**Comment by bojidar-bg** [comment] 2017-08-18 12:18
Aw, my bad, right 😃 Have you recompiled or used a build of the branch more recent that the merge?

**Comment by plucian** [comment] 2017-08-18 12:57
compiled 2.1 branch yesterday. ( still has the bug that the play button remains pressed, but only happens on windows 10, on windows 8. is fine..strange). Anyway the problem seems to be different from what karroffel explained, this is not a problem with the first/last point in the array and is not a point duplication either.

**Comment by kubecz3k** [comment] 2018-04-10 16:49
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:23
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:23 UTC
Labels: bug, topic:core
