### ISSUE TITLE
GDScript 2.0: Invalid comparison after implicit narrowing conversion from float to typed int

### ISSUE THREAD

**Issue by ksubox** [godotengine/godot#62650] opened 2022-07-02 21:07 UTC
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 11, Radeon 560, Vulkan

### Issue description

I have this script

```
extends Node3D
var currentCount : int = 0
var targetCount : int = 3

func _process(_delta):
	while (targetCount > currentCount):
		print("test")
		currentCount += 1

func _on_change_count(_changed : bool, slider : Slider):
	var cnt = slider.value
	print("Count: ", cnt)
	targetCount = cnt

```
Output is correct:
test 0
test 1

Then after start application I change targetCount to 1
And output is incorrect !!! Eternal loop.
Count: 1
test 2
test 3
test 4
test 5
test 6
............ loop continues

### Steps to reproduce

Just make new scene and copy script from above. Then somehow set targetCount member variable while running project.

### Minimal reproduction project

This test project produces stable error on my comp.
Just a little move slider to the right to change target count to 1.

[Text41Err.zip](https://github.com/godotengine/godot/files/9033712/Text41Err.zip)

**Comment by Calinou** [comment] 2022-07-02 21:09
> Then somehow set targetCount member variable while running project.

Are you referring to live script reloading, or changing the value from a signal?

**Comment by ksubox** [comment] 2022-07-02 21:29
I found problem
In signal I had to set member with self....:
`self.targetCount = cnt`
And it works well.

**Comment by ksubox** [comment] 2022-07-02 21:34
But I believe in case of signal if we MUST use self to modify member variables, it would be nice to have runtime error like "variable doesn't exist" if we DON'T specify self. Otherwise in Debugger we can see changed value which is actually wrong.
Right ?

**Comment by akien-mga** [comment] 2022-07-02 22:00
This is a bug, there's definitely something weird going on in this example.

**Comment by gotnospirit** [comment] 2022-07-03 03:32
The debugger shows
"W 0:00:01:0441   Narrowing conversion (float is converted to int and loses precision).
  <Erreur C++>   NARROWING_CONVERSION
  <Source>       BaseObject.gd:18"

Using "var cnt = int(slider.value)" and everything works without the need on self

**Comment by kleonc** [comment] 2022-07-03 08:51
Seems like there's something wrong when assigning a non-typed `float` variable to a typed `int` variable. This part in MRP:
```gdscript
	var cnt = slider.value
	targetCount = cnt
```

A simpler example, `t2` case below (test cases differ only in the first two lines):
```gdscript
@tool
extends EditorScript

func _run():
	t1() # OK
	t2() # NOT OK
	t3() # OK
	t4() # OK

func t1():
	var t = 1
	var f = 3.0
	t = f
	print("\ntypeof(t)=%s" % [typeof(t)])
	for i in range(5):
		print("%s > %s %s" % [t, i, t > i])

func t2():
	var t: int = 1
	var f = 3.0
	t = f
	print("\ntypeof(t)=%s" % [typeof(t)])
	for i in range(5):
		print("%s > %s %s" % [t, i, t > i])

func t3():
	var t = 1
	var f: float = 3.0
	t = f
	print("\ntypeof(t)=%s" % [typeof(t)])
	for i in range(5):
		print("%s > %s %s" % [t, i, t > i])

func t4():
	var t: int = 1
	var f: float = 3.0
	t = f
	print("\ntypeof(t)=%s" % [typeof(t)])
	for i in range(5):
		print("%s > %s %s" % [t, i, t > i])
```
Output (`TYPE_INT == 2`, `TYPE_FLOAT == 3`):
```
typeof(t)=3
3 > 0 true
3 > 1 true
3 > 2 true
3 > 3 false
3 > 4 false

typeof(t)=3
3 > 0 true
3 > 1 true
3 > 2 true
3 > 3 true
3 > 4 true

typeof(t)=3
3 > 0 true
3 > 1 true
3 > 2 true
3 > 3 false
3 > 4 false

typeof(t)=2
3 > 0 true
3 > 1 true
3 > 2 true
3 > 3 false
3 > 4 false
```

In general there's something wrong about assigning non-typed variable to a typed variable, the same as above the other way around:
```gdscript
func t5():
	var t: float = 1.0
	var f = 3
	t = f
	print("\ntypeof(t)=%s" % [typeof(t)])
	for i in range(5):
		print("%s > %s %s" % [t, i, t > i])
```
output:
```
typeof(t)=2
3 > 0 true
3 > 1 false
3 > 2 false
3 > 3 false
3 > 4 false
```

**Comment by linkpy** [comment] 2022-07-03 11:48
Well, in the GDScript evaluator, in the case of t2 the result is always true because the evaluator is basically doing `4613937818241073152 > i` : 
```
(gdb) frame 2
#2  0x000055555bf65e8f in OperatorEvaluatorGreater<long, long>::validated_evaluate (left=0x7fffffffb528, right=0x555563139be0, r_ret=0x7fffffffb5a0) at core/variant/variant_op.h:671
671                     *VariantGetInternalPtr<bool>::get_ptr(r_ret) = *VariantGetInternalPtr<A>::get_ptr(left) > *VariantGetInternalPtr<B>::get_ptr(right);
(gdb) p *left
$7 = {type = Variant::FLOAT, _data = {_bool = false, _int = 4613937818241073152, _float = 3, ... (elided)
```
Line 671 is basically `*r_ret->_data._bool = left->_data._int > right->_data._int`, but `left` is a float so its `_int` field is junk. Futhermore, `A = long` (so int64_t I would assume) instead of `double`. It seems here the codegen outputs the wrong comparison operator in the bytecode.

**Comment by linkpy** [comment] 2022-07-03 12:58
Code used : 
```gdscript
extends Node

func _ready() -> void:
	var t: int = 1
	var f = 3.0
	t = f # line 6
	
	print("t: ", typeof(t), "; 5: ", typeof(5), "; t > 5: ", t > 5)
```

A quick glance at the gdscript resolver gives this : 

When reducing the assignment at line 6, the assignee type is int (explicitely annotated) so this is OK.
The assigned value type is float (inferred) so this is OK.
The assignment type is float (inferred) which I find a bit weird since I would expect it to be of the type of the assignee but this isn't the place for this point.
At the end, the analyzer does it job and after the assignment, `t` is still of type `int`, so seems like the issue is either with the codegen or with the bytecode.

And now with the compiler : 

The compiler, in this case, writes an assign instruction **without** conversion (the execution leads to gdscript_compiler.cpp:1211). The float variant stored in `f` is directly assigned to `t` without any cast. So the bug comes from `GDScriptAnalyzer::reduce_assignment` which doesn't check if a conversion is necessary in this case.

So to fix this issue, we need to add checks in `reduce_assignment` to avoid generating an assignment instruction leading to a variant of the wrong type in a variable.

**Comment by Calinou** [comment] 2022-10-26 16:47
> Is this issue still valid?


The issue is still valid, but we lack people to review GDScript pull requests (as vnen is currently unavailable).

**Closed** 2022-12-30 19:38 UTC
Labels: bug, topic:gdscript, confirmed
