### ISSUE TITLE
Game window loses focus on start, must left-click first to enable inputs

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#74619] opened 2023-03-08 21:06 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Sometimes when running a scene, the game loses focus, keyboard doesn't work and mouse events get ignored, you must left click to focus on the game window and start playing.

### Steps to reproduce

Run the scene several times. Sometimes it will work just fine, others you will try to move with WASD or move the mouse and nothing will happen. Left click if that happens to "solve" the issue.
These are the settings for the Window.

![imagen](https://user-images.githubusercontent.com/98270528/223848922-432da29e-c6a0-4ae7-ba4f-c7e9d571b649.png)

### Minimal reproduction project

[focus.zip](https://github.com/godotengine/godot/files/10925224/focus.zip)

**Comment by Orgull1972** [comment] 2023-03-09 05:32
I'm having almost the identical issue. Reorted it in #74587 You're not alone!

**Comment by akien-mga** [comment] 2023-03-09 07:33
Duplicate of #74587

**Closed by akien-mga** 2023-03-09 07:33 UTC

**Comment by Wisdawms** [comment] 2023-09-25 16:14
how fix this?

**Comment by Midrule** [comment] 2024-01-16 00:44
Having "Resizeable" uncheck is what causes this. Turning it back on will make it focus on startup. Maybe changing the setting after starting the game if you want it to stay unsizeable?

**Comment by Nagasadri** [comment] 2024-08-21 14:07
I had an issue where Windows' taskbar showed on top of the game on exclusive fullscreen mode, even after the player clicks on the window to give it focus.

Disabling "Resizeable" fixed that too.
