### ISSUE TITLE
Godot crash at disconnection of RemoteDesktop session

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#4988] opened 2016-06-02 12:26 UTC
**Operating system or device - Godot version:**
Latest dev build as of writing this, happens with stable version too.
Win10 x64, but I think it applies to other windows versions or Linux/MacOSX

**Issue description** (what happened, and what was expected):
Godot crash when disconnecting a RemoteDesktop (RDP) session. But to be more precise, It works fine during the session. And after I disconnect from the remote PC, logging in the same PC (with disconnected session), Godot shows "it stopped working, looking for solutions from Microsoft". Thankfully, I save my work regularly, but this issue could cause the loss of unsaved work.

**Comment by reduz** [comment] 2016-06-12 00:51
I no longer have a windows computer, so anyone who wants to take a look at this be welcome

**Comment by RebelliousX** [comment] 2017-02-01 21:03
After some debugging, I found that it is due to RtAudio, an exception was thrown:
```
RtApiDs::callbackEvent: error (Buffer lost) getting current write position!
```
![screenshot 2017-02-01 14 55 05](https://cloud.githubusercontent.com/assets/1888186/22525890/c41d120c-e88e-11e6-9e55-909d81821426.png)

I admit, it is daunting me to edit `RtAudio.cpp` file with its >10k lines.

**Comment by bojidar-bg** [comment] 2017-02-02 08:41
A duplicate of #7272 then?

**Comment by RebelliousX** [comment] 2017-02-02 10:06
@bojidar-bg it seems to be the case. But not sure if fixing it requires modifying Godot's source, or the 3rdparty library RtAudio? Should I post an issue in github's RtAudio repo about this?

**Comment by Calinou** [comment] 2018-04-11 16:11
#7272 was closed as resolved a while ago, so I'm closing this one as well; please comment if you can still reproduce this issue.

**Closed by Calinou** 2018-04-11 16:11 UTC
Labels: bug, pr welcome, topic:editor
