### ISSUE TITLE
ResourceLoader.load_interactive(key) - does not return resource from cache

### ISSUE THREAD

**Issue by MadDogMayCry0** [godotengine/godot#45482] opened 2021-01-26 15:02 UTC
3.2.4-beta6
Even if the resource has already been loaded earlier by
```
ResourceLoader.load_interactive(key)
``` 
and there is a link to it somewhere, then 
```
ResourceLoader.load_interactive(key)
```
will not take the resource from the cache. It just returns NULL and shows an error - Cyclic reference.
```
Expected behavior - the resource will be taken from the cache
```

See comments in loader/files.gd
```
#Uncomment this to get cache to works
```
Project files zip:
[loader.zip](https://github.com/godotengine/godot/files/5874844/loader.zip)

**Comment by Calinou** [comment] 2021-01-26 15:08
@MadDogMayCry0 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by JosephHalter** [comment] 2021-11-13 16:52
It still seems to be the case in 3.4 stable.

**Comment by CloudMax94** [comment] 2022-07-27 17:06
Still happening in 3.5 RC 7 for me Recently started migrating my project to godot and came across this.
I do threaded resource loading with load_interactive before transitioning to a new scene.

If I happen to try and load an asset through the ResourceLoader a second time, I get a cyclic reference error.

I have however noted it never seem to happen if I wait about 20-25 seconds after the very first load. 
After that I'm able to load it as often and quickly as I want.

**Comment by Calinou** [comment] 2022-07-27 17:19
Duplicate of https://github.com/godotengine/godot/issues/33809.

**Closed by Calinou** 2022-07-27 17:19 UTC
Labels: bug, topic:core, confirmed
