### ISSUE TITLE
AnimatedSprite2D not loading Sprite sheet accurately

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#74721] opened 2023-03-10 14:58 UTC
### Godot version

4.0 Mono Stable

### System information

Windows 11, NVidia RTX 3060, Vulkan/Forward+

### Issue description

![Screenshot 2023-03-10 085712](https://user-images.githubusercontent.com/1558027/224348393-19dcde8c-19c1-4c57-8c12-97ef222505a8.png)

It's kinda hard to see from the screenshot, but when loading in a Sprite sheet to the AnimatedSprite2D, the auto generated cells are clipping the one above. This does not happen when loading the Sprite sheet into the frames of an AnimationPlayer.
I tried adjusting the offset and separation but that didn't solve the problem. It's as if the generated grid needs nudging up a pixel row.

It might be related to this issue?
https://github.com/godotengine/godot/issues/67164

### Steps to reproduce

![Walk](https://user-images.githubusercontent.com/1558027/224348242-6b7db3c2-36f5-4ea0-af57-546e232056b0.png)

Load the above Sprite sheet into an AnimatedSprite2D node and zoom in. You should be able to see the overlap between cells.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-10 15:07
If it is the behaviour in the editor that is the problem it's due to filtering, should be fixed by #73962, depending on your settings

**Comment by nathanjwtx** [comment] 2023-03-10 15:58
Ok. Shall I close this issue?

**Comment by AThousandShips** [comment] 2023-03-10 15:59
Check the PRs and see if the issues they link describe your issue, otherwise see if they will fix your issue, I think it is what's wrong but can't check myself at the moment

**Comment by KoBeWi** [comment] 2023-03-17 01:55
> This does not happen when loading the Sprite sheet into the frames of an AnimationPlayer.

It does
![image](https://user-images.githubusercontent.com/2223172/225792132-3e99b15b-1ec7-478d-8ee4-036d67b016c3.png)
You need to use nearest filtering.

This is editor-only issue, closing as duplicate of #57550

**Closed by KoBeWi** 2023-03-17 01:55 UTC
