### ISSUE TITLE
"Play Project" button plays the current edited scene

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10724] opened 2017-08-28 15:30 UTC
**Ubuntu 17.04, Godot build: 1674bd5**

**Issue description:**
Instead of playing the project, the "Play Project" buttons play the current scene you're editing.

**Comment by Zireael07** [comment] 2017-08-28 16:39
Duplicate of #10675

**Closed** 2017-08-28 20:18 UTC
