### ISSUE TITLE
GDScript 2.0: `load_source_code()` error in console

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#47641] opened 2021-04-05 12:16 UTC
**Details:**

![image](https://user-images.githubusercontent.com/58845030/113572737-21b27d00-95ef-11eb-83c7-8b5e0835d6af.png)

**Issue description:**
I'm testing gdscript, and printing a simple hello world throws an error, but it still works:
![image](https://user-images.githubusercontent.com/58845030/113572839-5b838380-95ef-11eb-9800-a398a467f2a1.png)

but this error happens:
![image](https://user-images.githubusercontent.com/58845030/113572933-879f0480-95ef-11eb-8617-e8cd5b7174e3.png)

**Steps to reproduce:**
* Attach a script
* type print("hello world")

**Minimal reproduction project:**
[tt.zip](https://github.com/godotengine/godot/files/6258060/tt.zip)

**Comment by Blackiris** [comment] 2021-04-07 11:45
It looks like the error message is caused because the source code is embedded inside Node2D.tscn, and thus, has no path.

After compiling the script, GDScript::load_source_code(const String &p_path) is called but in that case, path is null which triggered the error.

**Comment by Blackiris** [comment] 2021-04-07 21:07
Here is the call stack leading to the error:
> GDScriptCompiler::compile 
> GDScriptCache::finish_compiling(const String &p_owner)   (p_owner is in fact the path here)
> GDScriptCache::get_shallow_script(const String &p_path, const String &p_owner)
> GDScript::load_source_code(const String &p_path)

First of all, GDScriptCache::finish_compiling it called only in the GDScriptCache::compile method
https://github.com/godotengine/godot/blob/47aef8e8dcc61b505777a84e31a507ee555d188f/modules/gdscript/gdscript_compiler.cpp#L2562
 that's why I would first change its argument name from p_owner to p_path

Then, inside finish_compiling, it looks like all the code need the path (= p_owner) to work:
https://github.com/godotengine/godot/blob/47aef8e8dcc61b505777a84e31a507ee555d188f/modules/gdscript/gdscript_cache.cpp#L222-L245

But in the reproduction case, the script in embedded and had no path, so to fix the issue, I would simply replaced the previous line by:
`return path == String() ? OK : GDScriptCache::finish_compiling(path);`
with `String path = p_script.get_path()`

But because I don't really understand the goal of finish_compiling, I don't really know the consequences...

**Comment by qarmin** [comment] 2021-08-17 19:17
This seems to be fixed in master

**Closed by qarmin** 2021-08-17 19:17 UTC
Labels: bug, topic:gdscript, regression
