### ISSUE TITLE
Godot 3.5.2 - Mouse position not fully going to the right

### ISSUE THREAD

**Issue by Oplexitie** [godotengine/godot#81720] opened 2023-09-15 23:27 UTC
### Godot version

3.5.2 stable

### System information

Windows 10 and Linux Mint - Godot 3.5.2

### Issue description

When measuring the mouse position, I noticed that the mouse didn't fully go to the right of the screen by 1 pixel.
This caused an issue in my project where scrolling the screen to the right was slightly slower than scrolling to the left.

I tested this on my Windows 10 Desktop, with a resolution of 1920x1080, my Godot Project sized accordingly to the screen, but when the mouse is all the way to the right of the screen, my mouse indicates that the x coordinate is 1919.

I tried the same test with my Linux Mint Labtop, with a resolution of 1600x900, my Godot Project sized accordingly to the screen, and when the mouse is all the way to the right of the screen, my mouse indicates that the x coordinate is 1599.

I found a way to fix this issue in my project, but I still find it weird that it doesn't register the last pixel.
If this is expected behaviour, I apologize for wasting your time.

### Steps to reproduce

1 - Use this script on a Node.
```
extends Node2D

var mouse_position : Vector2

func _physics_process(delta):
	mouse_position = get_viewport().get_mouse_position()	
	print(mouse_position.x)
```
2- Move your mouse all the way to the right, and check the print output.

### Minimal reproduction project

[BugTest.zip](https://github.com/godotengine/godot/files/12629328/BugTest.zip)

**Comment by floatingpointer** [comment] 2023-09-16 08:24
The first pixel is 0, so for 1920x1080 the last `x` pixel is correctly 1919.

You may want to create a test project just for the scrolling to isolate that, if the solution isn't something more obvious, e.g., if you're expecting the last pixel to be =resolution and calculating speed based on that, that could be your problem.

Another possibility: If you have code modifying scroll speed, any addition you perform to adjust speed may not be considering direction, which wouldn't apply speed equally to both directions.

**Comment by kleonc** [comment] 2023-09-16 10:46
> The first pixel is 0, so for 1920x1080 the last `x` pixel is correctly 1919.

Exactly, it's working as intended. Simpler (but abstract) example: if you'd have a fullscreen with a 1x1 resolution then the whole screen would be the `(0, 0)` pixel, pixel coordinates `(1, 1)` would be out of screen (and mouse wouldn't be able to reach there).

Closing as no bug.

@Oplexitie For the future: if you're not sure you're facing a bug please try asking for help in [other community channels](https://godotengine.org/community/) (Q&A, Discord, Reddit, etc.) before opening an issue in here (this is a bug tracker, not a help desk). :slightly_smiling_face:

**Closed by kleonc** 2023-09-16 10:46 UTC
