### ISSUE TITLE
Custom keyboard shortcuts don't override default behavior

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#12164] opened 2017-10-16 21:44 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4
Godot 3.0 (built from master)

**Issue description:**
When using custom shortcuts, default behavior is executed before shortcut-behavior is executed.

**Steps to reproduce:**
Override keyboard shortcuts for 'Script Editor / Next Script' with Ctrl+PageDown
Override keyboard shortcuts for 'Script Editor / Previous Script' with Ctrl+PageUp

Use shortcuts in script editor.
When pressing Ctrl+PageUp see that cursor jumps to the first line of the file before going to previous script.
When pressing Ctrl+PageDown see that cursor jumps to the last line of the file before going to next script.

**Comment by akien-mga** [comment] 2018-01-15 10:59
Is this still reproducible in Godot 3.0 RC1?

Also, aren't the "default behaviors" also defined in the editor shortcuts? If so you might need to undefine them if you want to override them.

**Comment by BeayemX** [comment] 2018-01-15 21:18
The bug is still there but the behavior changed slightly.
When trying to use `Control+PageDown` for `Script Editor/History Next` and `Control+PageUp` for `Script Editor/History Prev` the cursor just jumps around like `Control` is not pressed and `History Next` and `History Prev` are not executed at all.

The "default behavior" in this case for PageUp and PageDown is just to scroll by one page. Maybe this is handled differently than other shortcuts?

**Comment by ShawnMcCool** [comment] 2018-04-30 15:13
So yeah, I have changed the default "QWER" shortcut functionality in the spacial editor and the changes have zero effect.

**Comment by KoBeWi** [comment] 2020-06-13 14:08
Soo, some keys do have default behavior, like mentioned PageUp. While it doesn't make sense to have shortcuts that override e.g. End or Home, there are some key combinations that are not used, e.g. Control + PageUp or Alt + End. Right now it's impossible to use them as shortcuts, because Alt + End acts as End etc. This could be easily fixed by ignoring certain non-shortcut key combinations in TextEdit.

**Closed** 2021-02-18 18:37 UTC
Labels: bug, topic:editor, usability
