### ISSUE TITLE
Better GUI Editor

### ISSUE THREAD

**Issue by RealAquilus** [godotengine/godot#28845] opened 2019-05-12 19:52 UTC
I love Godot really much, the only things that at the moment makes me complain are (the most bloated) problems with large world (LOD ecc ecc) and the less cited GUI Editor. Maybe it's just me (since i have been using Unity for really a long time) but i can't get confortable designing gui in Godot, i can't get really into layout (in unity seems just easier to drag this around and then make sure with anchor how it should respond), and one thing that i really hate is the fact that we have to instance a new dynamic font everytime we want to change the font size.
Would be possible to share some love to the GUI Designer?
Thanks and keep the great stuff coming!!

PS Don't want to start any type of flame i cited unity just because is what i have used more, and i'm not saying that Godot should "copy" unity, maybe just found another way that is more comfortableor even better than the unity ones, who knows!

**Comment by Calinou** [comment] 2019-05-12 21:03
> and one thing that i really hate is the fact that we have to instance a new dynamic font everytime we want to change the font size.

To ease the pain of creating multiple font resources, it's possible to write an editor plugin that would generate a set of `.tres` files for a given font with predefined sizes.

**Comment by aaronfranke** [comment] 2019-05-13 00:44
I agree. I actually love the overall design of Control nodes, but they are confusing at first, and some things are simply more annoying than they should be, like changing the font size as you said.

**Comment by chiboreache** [comment] 2019-05-13 06:05
+1

get rid of from drop-down menus

there enough place for dedicated buttons

**Comment by chiboreache** [comment] 2019-05-13 06:06
+1

get rid of drop-down menus

there enough place for dedicated buttons

**Comment by chiboreache** [comment] 2019-05-13 06:07
+1

get rid of drop-down menus

there is enough space for dedicated buttons

**Comment by Daw11** [comment] 2019-05-13 08:43
The problem is that, when you place a Control, you have no idea of what it's going to do because it doesn't creaty any giizmos.

In the documentation of the gui there's a good image that shows very well what you should see when you edit a node:
![ui_anchor_and_margins](https://user-images.githubusercontent.com/3595817/57607334-18d3e080-756b-11e9-8364-f30372eb10f4.png)

Right now you have to trial and error because every control node is just an empty box.

Some nodes like the horizzontal and vertical lists should have gizmos showing an example of how the items inside them will behave.

This gizmos should probably show only when you select a single node, because there are usually many Control nodes overlapping each other.

**Comment by groud** [comment] 2019-05-13 09:11
> The problem is that, when you place a Control, you have no idea of what it's going to do because it doesn't creaty any gizmos.

In 3.1, you have to activate them using the `View` > `Show helpers` menu.

**Comment by Vultraz** [comment] 2019-05-13 10:41
Definitely a +1, especially on the font resources thing.

**Comment by KoBeWi** [comment] 2019-05-13 11:27
I guess this is related: #26491, #26492

**Comment by RealAquilus** [comment] 2019-05-13 22:18
Would be also nice to have some fonts to come with Godot, to prototype without having to import any ttf

**Comment by Megalomaniak** [comment] 2019-05-14 06:18
> > The problem is that, when you place a Control, you have no idea of what it's going to do because it doesn't creaty any gizmos.
> groud said:
> In 3.1, you have to activate them using the `View` > `Show helpers` menu.

Enable by default for 4.0?

**Comment by groud** [comment] 2019-05-14 06:31
I have a pending PR making it visible by default, so yes

**Comment by Daw11** [comment] 2019-05-14 08:03
> > The problem is that, when you place a Control, you have no idea of what it's going to do because it doesn't creaty any gizmos.
> 
> In 3.1, you have to activate them using the `View` > `Show helpers` menu.

Thank you, I didn't notice that there was already this option.

**Comment by epuscasu** [comment] 2019-06-28 19:35
Not that big of an issue, just a 'nice to have' feature - the currently selected Anchor (selectable via the Layout menu) could be identifiable via the Layout menu (as in hightlighed, or something similar):
![image](https://user-images.githubusercontent.com/11788042/60366612-b3419380-99f4-11e9-93d4-c70bcab04342.png)

Currently, the only way to find out the anchor is interpreting the values in the Control -> Anchor menu

![image](https://user-images.githubusercontent.com/11788042/60366646-cce2db00-99f4-11e9-8536-a874dec8d08a.png)

**Comment by mindinsomnia** [comment] 2019-07-08 08:01
> "one thing that i really hate is the fact that we have to instance a new dynamic font everytime we want to change the font size."

This is one thing that absolutely drives me nuts. There's gotta be a better way to do this, some way of Godot just automatically creating new dynamic fonts or scaling an existing font based on font size selections?

**Comment by Calinou** [comment] 2019-07-08 13:09
@mindinsomnia The DynamicFont usability issues are being discussed in https://github.com/godotengine/godot/issues/24255. There's a [pull request](https://github.com/godotengine/godot/pull/29762) that makes easy scaling available in Label and RichTextLabel, although fonts will be a little blurry due to how it's implemented.

**Comment by KoBeWi** [comment] 2021-01-17 17:08
The font issue is already resolved in 4.0, anything else mentioned here that is still wanted should have a [proposal opened](https://github.com/godotengine/godot-proposals). Closing, as this issue doesn't belong to this repository anymore.

**Closed by KoBeWi** 2021-01-17 17:08 UTC
Labels: discussion, enhancement, topic:editor, usability
