### ISSUE TITLE
Fail to load texture files declared in materials associated to .obj files

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#20924] opened 2018-08-11 19:05 UTC
**Godot version:**
3.0.5

**OS/device including version:**
Windows 10, 64bits, and likely all other OS

**Issue description:**
I rewrite here one of my comment on #17475 as it may be more relevant to file a specific issue for it:

When importing .obj files with material using textures files (map_Kd, map_Ks, map_Kn etc) Godot fails to load the texture file(s) if the path in the .mtl is expressed in **its absolute value** (eg: "C:/foo/bar/diffusemap.png") as Blender can do when exporting in wavefront format.

After some debugging I found that:

1. The current code adds systematically the godot's local path before:
eg: `"C:/foo/bar/diffusemap.png" -> "res://bla/bleh/C:/foo/bar/diffusemap.png"`

2. None of the different resource loaders available within the .obj import process can handle any texture file extensions supported by Godot (".png",".hdr",".jpg",".tga"). In fact only the StreamTexture files (".stex") can be used. This implies the texture has been already loaded by Godot (in other words it forces you to use a Godot folder to save textures and have Blender pointing onto it).

The second point assumes Godot's ability to load directly external resources (ie. not already imported), and for that I'm not sure about the current policy...

(may be related to #17848)

**Comment by Overblob** [comment] 2018-09-25 11:37
Point 1. seems to be fixed by #22174

**Comment by KoBeWi** [comment] 2020-06-19 13:18
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 16:27
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.
(btw this sounds a bit like #28203)

**Closed by KoBeWi** 2020-09-28 16:27 UTC
Labels: bug, topic:import

**Comment by songangel72** [comment] 2021-02-23 18:16
Yes this still exists in 3.2.4.rc2 and the mtl file DOES exist.

**Comment by songangel72** [comment] 2021-02-23 18:34
Update:  I moved the texture into the project directory, edited the .mtl file by hand and used the absolute path to the texture, and re-imported and now it works.  Even though an absolute path was used, the importer has trouble loading the texture if is not in the project directory structure.  See the attached 
[MRP-updated.zip](https://github.com/godotengine/godot/files/6031137/MRP-updated.zip)
updated MRP.

**Comment by KoBeWi** [comment] 2021-02-23 23:35
Why would you want textures with absolute paths?
I tried the second project and it properly loads the texture when absolute path is provided in mtl, so not sure what's the problem.

**Comment by songangel72** [comment] 2021-02-24 01:24
> Why would you want textures with absolute paths?
> I tried the second project and it properly loads the texture when absolute path is provided in mtl, so not sure what's the problem.

This is not based on what I want.  Blender exports OBJ files with an absolute path to the texture in the .mtl file (look at the first MRP).  All I did was move the texture into the project folder and change that path in the wall.mtl file to point to its new location.  

There is a problem with importer because it refuses to load the texture unless it is placed in the project folder which makes sense, but it is not obvious to anyone attempting to import the model.  I am suggesting that the importer copy the texture into the project folder and change the path in the .mtl file as part of the import process.

**Comment by KoBeWi** [comment] 2021-02-24 02:56
> I am suggesting that the importer copy the texture into the project folder and change the path in the .mtl file as part of the import process instead of just expecting it to be there with no warning to the user.

Sounds more like a material for a proposal than a bug to me: https://github.com/godotengine/godot-proposals
