### ISSUE TITLE
Exported array with nodes does not allow nodes

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#73582] opened 2023-02-19 10:28 UTC
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 11, Nvidia GeForce GTX 1050, 27.21.14.5771, Vulkan

### Issue description

Exported Arrays when specified with nodes (objects) do not work, it's same for both built-in nodes as well as Custom classes. it works if the array is of type NodePath rather than Node (object).

Here's a video which explains the problem:
https://youtu.be/0ugxyVASWxs

### Steps to reproduce

Create a script and export a array which is of type Node or object for example:
```
@export var images: Array[Sprite]
```
Try to assign a node to the exported array.
Assert whether godot does nothing or assigns the node to the selected element.

As a video:
https://youtu.be/Sjvpf0LcyaM

### Minimal reproduction project

[exported_node_array.zip](https://github.com/godotengine/godot/files/10776620/exported_node_array.zip)

**Comment by YuriSizov** [comment] 2023-02-19 10:40
Duplicate of https://github.com/godotengine/godot/issues/62916

**Closed by YuriSizov** 2023-02-19 10:40 UTC
