### ISSUE TITLE
[Godot 4rc5]  Wrong ELF class

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#73921] opened 2023-02-25 12:31 UTC
### Godot version

v4.0.rc5.official [6296b4600]

### System information

Debian 11

### Issue description

I run this example https://godotengine.org/storage/blog/multiplayer-in-godot-4-0-scene-replication/project.zip (its just an example like anything else more simple - I linked it because is an easy thing to do:) ) 

The example is configured as "Forward" rendering mode. Of course in my real project I use "Compatibility" mode.
But if I set in Project properties to run in verbose mode I have In output dock this (inside my comment to point out my config): 
```

--- Debugging process started ---
Godot Engine v4.0.rc5.official.6296b4600 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
XInput: Refreshing devices.
XInput: No touch devices found.
Text-to-Speech: Cannot load Speech Dispatcher library!
Vulkan devices:
  #0: Intel Intel(R) HD Graphics 4000 (IVB GT2) - Supported, Integrated  <------- I run it with my Intel card
  #1: Unknown llvmpipe (LLVM 11.0.1, 256 bits) - Supported, CPU
Vulkan API 1.2.145 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 4000 (IVB GT2) <--- idem here
Optional extension VK_KHR_fragment_shading_rate not found
Optional extension VK_KHR_shader_float16_int8 not found
Optional extension VK_KHR_16bit_storage not found
Optional extension VK_GOOGLE_display_timing not found
- Vulkan Variable Rate Shading not supported <--- no idea if is related. can be
- Vulkan multiview supported:
  max view count: 16
  max instances: 268435455
- Vulkan subgroup:
  size: 32
  stages: STAGE_FRAGMENT, STAGE_COMPUTE
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_QUAD
Using present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
Using "default" pen tablet driver...
Creating VMA small objects pool for memory type index 0
Shader 'CanvasSdfShaderRD' SHA256: b67c886f7dcfb4756d663e1d9d950ee0c3a3b80b09ae8ed31c5115924e0394fa
Shader 'SkeletonShaderRD' SHA256: 21b74a3204ccb5e55ebd9bcddec48ee7a971825f9efd9824f6fe309fe2c95784
Shader 'ParticlesShaderRD' SHA256: fbcd0441db6622896ecc0ff865855ee43490806b93d62fd598e4b81860cd2298
Shader 'ParticlesCopyShaderRD' SHA256: de4916ac02d8e33afc23dd7c3697b014e3b67d87806c16aa97b13e188650a177
Shader 'CanvasShaderRD' SHA256: 40d140bd6ffd69386f4a6d73390d0535fe64de6b00c4c15e49e562ff065c578e
Shader 'CanvasOcclusionShaderRD' SHA256: bae278745362c89f605dfa978140d90857bfe367146fc8b2b3955643a7d5b2c0
Shader 'ClusterRenderShaderRD' SHA256: e4d584541567bda30fefefaefa26060c606da12e7744d6293b045f984737f3c9
Shader 'ClusterStoreShaderRD' SHA256: b53f9921590a4dc6e1847d684dc71af0cc5bd92212bb22fb18e31a2ce9890d21
Shader 'ClusterDebugShaderRD' SHA256: 5e5138fd08b79ef54d82d706ed89892edfaf80445cbc4b4e36577c79bb198a98
Shader 'SceneForwardClusteredShaderRD' SHA256: a6aa61d225b464561c39f1e07de08e75abe16a9dcf634b632c0154eaadc38a9e
Shader 'ResolveShaderRD' SHA256: fd160bf7d2b40b14054a03cba4378241313642811332483ea33f0211399a2e7d
Shader 'TaaResolveShaderRD' SHA256: 91328f2ecc7fc59950d357714874943e8b4c5bd2056fa716ad898347be235d14
Shader 'SsEffectsDownsampleShaderRD' SHA256: ceb2732107827707b7d1377fd79bbdceba44494bf092b9be696f6ba1442f444f
Shader 'SsilShaderRD' SHA256: ab27720ee72ce7ad2f5ce88eb10cf58c880543bf64067d4b30faabf7ea90d4d5
Shader 'SsilImportanceMapShaderRD' SHA256: 6fbca2e63a4794612526e0b911f3b78be120d9b48a09199d7551c9f0e2750508
Shader 'SsilBlurShaderRD' SHA256: b5efd66dc39009b6dcd35b79dc7be943e869ac62c86446087055d3230a4e078d
Shader 'SsilInterleaveShaderRD' SHA256: 32ad543d57fc1905faaa092d216e4f82b4aea6e657ae32dc4b5c4f7082c4eef6
Shader 'SsaoShaderRD' SHA256: 55ab763c0f5bee494cd1b5ab39dc7ab81715add32ab992c6efe6067cdbcc4d58
Shader 'SsaoImportanceMapShaderRD' SHA256: 0885f44298976a83ad10b37a6337cda9af86662920daff87184f2c1b51eead5e
Shader 'SsaoBlurShaderRD' SHA256: 5358b316c1adfe921a662aee0d95fb8f42dc294f10e35c483c0b4f916f64bf45
Shader 'SsaoInterleaveShaderRD' SHA256: 5da212a3ee64f682a67a3d90cafad3cd6affbd037b790b447ef644f148c64df3
Shader 'ScreenSpaceReflectionScaleShaderRD' SHA256: d0d11ddb8eb6ebe4818c61c1a1878e731a3f8921ea69e5533286a6eb4a86bd23
Shader 'ScreenSpaceReflectionShaderRD' SHA256: f1a966f7b37002965333d9d856307376c935904c970d4e3b06fee152a9af0207
Shader 'ScreenSpaceReflectionFilterShaderRD' SHA256: 331a0c51addb83c0326fbde6472e4908b716f90c2b03fc14431220cfed054c25
Shader 'SubsurfaceScatteringShaderRD' SHA256: 23b270883ca4fb0e19dd58b10ae9e45eb7345642b0644700c9b54c92da9e6b2c
Shader 'SkyShaderRD' SHA256: b30ddf1fabe639032815b04b1335919d7740f981f9943977015aff337edc9e08
Shader 'VoxelGiShaderRD' SHA256: 40f9b61509f63abb6a396bd2782aa285ac6914376414cd130cbc56dda0f760d0
Shader 'VoxelGiDebugShaderRD' SHA256: 615e96fc2bb2cd00f22ae9ee1f49353f1dc96421b4db22191886398623e356b9
Shader 'SdfgiPreprocessShaderRD' SHA256: bb8511029ffdce3b00159cc63da069618d4122d5e6f7ba1bfa50c8427e222460
Shader 'SdfgiDirectLightShaderRD' SHA256: 58a0d3e6a3d0e120d779a94b48b06bbf777d6433a1cdf7c80b29ecf5af20740e
Shader 'SdfgiIntegrateShaderRD' SHA256: 209fe163019eb45c8028263720f8c800a9f9f8c4a1bb91bd2408203c131840f3
Shader 'GiShaderRD' SHA256: 0cb4e09014dbdd1f4434fad00cadd4d63bc089304343db38fe500b37e34c34e3
Shader 'SdfgiDebugShaderRD' SHA256: 899cbcff12f661aa094b5ac6d8e1ff5c371ed6898821d0d68cec058a3bc989e1
Shader 'SdfgiDebugProbesShaderRD' SHA256: 73ac18d055c207613001dc269506ee0958540071e4f438eb7cbc1c9af1f416ab
Shader 'VolumetricFogShaderRD' SHA256: 9b3da9968ca07ccae0cd837543a218bac5d5306eafdaee06c57721191dff3b9b
Shader 'VolumetricFogProcessShaderRD' SHA256: 69d924b2f17d57e68d12e64c5c08dfe3725802dc2b308a03eed9a843f2fc9656
Shader 'BokehDofShaderRD' SHA256: e6c9bca557375b79fbe7aa73ca9449ebac7847c0dd9fdb328df1e8662b4ad2d7
Shader 'CopyShaderRD' SHA256: 82570120767593caabfbcb9d787e0c3b2ee700872f1b90c17d2913013aeef8a7
Shader 'CopyToFbShaderRD' SHA256: 14ec79cefc3b6d5c4a715c0ba4eb45abf101f0edd0bb838b6780c57680ac9dcc
Shader 'CubeToDpShaderRD' SHA256: 9411608a2ba8794c1b2e074498bb38491be818ebcc455efe29af16fb20a4c002
Shader 'CubemapDownsamplerShaderRD' SHA256: f126d4ff14f897e7696c179ce9e040a803d27f5d120c979bf151c68c9e0919a0
Shader 'CubemapFilterShaderRD' SHA256: b6025c2157272e8df4abcf42a5b51681ee83f951db917326746e30c169234428
Shader 'CubemapRoughnessShaderRD' SHA256: 98933cb40ba3501226cba9086397a8dcde39edae5a61924453f2311cd1abcd74
Shader 'SpecularMergeShaderRD' SHA256: acff8b4db448114dd184f9b1502827782d55c91353dd0ce9ba38e263b045147a
Shader 'LuminanceReduceShaderRD' SHA256: 4d17a3b3ba2b02421c1ae5e7a05d1d38a59a0db13c8209702367bdb14f7671c5
Shader 'TonemapShaderRD' SHA256: 6b30709acf52964ce8ecbcb9858aed3f0f96c6dcab271d189f1922ecc27637c9
Shader 'FsrUpscaleShaderRD' SHA256: 609e41839ff15f3ae6f10b146833d4757a1c85763cd1654aaeaa3cd31c6717be
Shader 'RoughnessLimiterShaderRD' SHA256: 89ee2a1600f082d02ee17887f6abedc746d3689be4e8852dada937832719328d
Shader 'SortShaderRD' SHA256: 88fba6396aaab00b2490a28b1c6ce264833f11a3e4fc19c2d50441a2d0c796a1
Shader 'BlitShaderRD' SHA256: 6f5e8db2934ddfdcaa8c64ccd53b1e913d2f3b945f154c53cea470d6503552ab
JoypadLinux: udev enabled and loaded successfully.
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.pci-0000_00_1b.0.analog-stereo
PulseAudio: detected 2 output channels
PulseAudio: audio buffer frames: 512 calculated output latency: 11ms
 
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 1899056592
EDITOR API HASH: 811264320
Loaded builtin certs
--- Debugging process stopped ---
```

In debug dock I have some errors:
```

E 0:00:00:0093   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 137069680
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:267 @ _debug_messenger_callback()

E 0:00:00:0093   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_scanned_icd_add: ICD libnv_vulkan_wrapper.so.1 doesn't support interface version compatible with loader, skip this ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 137069680
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:267 @ _debug_messenger_callback()

E 0:00:00:0093   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 137069680
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:267 @ _debug_messenger_callback()

E 0:00:00:0093   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/usr/lib/i386-linux-gnu/libvulkan_lvp.so: wrong ELF class: ELFCLASS32
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 137069680
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:267 @ _debug_messenger_callback()

```

I can guess that is a limitation/wrong config?( but I dont see errors in other app) of my linux driver  for my Intel card but I was not sure 100% So I posted this issue.

I can post the project.godot content too:

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

run/main_scene="res://multiplayer.tscn"
config/features=PackedStringArray("4.0")

[debug]

settings/stdout/verbose_stdout=true

[display]

window/vsync/vsync_mode=0

[editor]

movie_writer/movie_file="/home/vale/godot4/movie.png"

```

ps.: I tried to run my project in "Forward" mode too and I have the same issue as this one in addition it will freeze the entire PC and I have to access with ssh to reboot it. From remote shell I run top and I saw godot are using 100% of my cpu.

### Steps to reproduce

I can guess it happen in my laptop only but eventually I posted the configuration I used.

### Minimal reproduction project

See link in description

**Comment by akien-mga** [comment] 2023-02-25 12:53
Duplicate of https://github.com/KhronosGroup/Vulkan-Loader/issues/262

The Vulkan packages on your system are probably a couple of years old.

**Closed by akien-mga** 2023-02-25 12:53 UTC
