### ISSUE TITLE
code not working anymore cause continue not supported in gdscript 2

### ISSUE THREAD

**Issue by HamidKazemzadeh** [godotengine/godot#75093] opened 2023-03-19 03:17 UTC
### Godot version

4.0 stable

### System information

windows 10

### Issue description

I have a code for finite state machine that use match to change state and after changing state use continue to skip current state codes and jump to next state, but in gdscript2 continue doesn't work the same way as before, so my code doesn't work anymore and I don't know what is the replacement for "continue" to make it work

### Steps to reproduce

```gdscript
match currentState:
		STATES.AIR:
			sprite.play("jump")	
			
			if is_on_floor() and velocity.y == 0:
				currentState=STATES.FLOOR
				#! lastJumpDirection = 0
				continue
			elif is_near_wall():
				currentState = STATES.WALL
				continue
			elif should_climb_ladder():
				currentState = STATES.LADDER
				continue
			# Add the gravity.
			velocity.y += gravity * delta
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-19 07:09
If this is inside a loop then continue should move to the next iteration, if not this is a bug, but it's not clear from your code what you want it to do exactly

**Comment by AThousandShips** [comment] 2023-03-19 07:24
But please for issues that aren't bugs, please turn to the [community channels](https://godotengine.org/community) as this is for bugs only

**Comment by dalexeev** [comment] 2023-06-22 11:36
I agree. This is not a bug, but an intentional change. There was a suggestion to replace it with some new keyword, but we did not find a word that conveys the exact meaning of the old behavior (for example, `fallthrough` means a little different). Also, the ability to jump to a different `match` branch often results in less readable code.

**Comment by Calinou** [comment] 2023-06-22 20:19
Closing per the above comments.

**Closed by Calinou** 2023-06-22 20:19 UTC
Labels: topic:gdscript
