### ISSUE TITLE
Font rendering in PopupPanel

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot#77873] opened 2023-06-05 11:04 UTC
### Godot version

4.0.3

### System information

Fedora and macOS

### Issue description

I have a problem with font rendering in PopupPanel.
Everything with fonts is ok in whole game apart of Popups. Settings per label is the same like in other places in game.
The problem occurs with any font where I would like the rendering to be as "nearest".

Popup (Bad):
![Zrzut ekranu z 2023-06-05 13-03-45](https://github.com/godotengine/godot/assets/5132385/879836d4-a205-4588-b20e-92f56d1f61ba)

Other Place (Good):
![Zrzut ekranu z 2023-06-05 13-03-23](https://github.com/godotengine/godot/assets/5132385/d8f4dc09-16cc-4051-a6f3-86362cf8af47)

### Minimal reproduction project

[font-rendering-problem.zip](https://github.com/godotengine/godot/files/11651900/font-rendering-problem.zip)

**Comment by Sauermann** [comment] 2023-06-05 11:13
This sounds similar to https://github.com/godotengine/godot/issues/54030#issuecomment-1094143542
Do you use the `canvas_items` stretch mode?

**Comment by michaldev** [comment] 2023-06-05 11:15
Yes

**Comment by Sauermann** [comment] 2023-06-05 11:22
Then this is as a known issue a duplicate of the other bugreport.

**Comment by michaldev** [comment] 2023-06-05 11:35
Ok, I see. I didn't find this earlier because I focused my search on fonts.

**Comment by akien-mga** [comment] 2023-06-05 11:57
Duplicate of #54030

**Closed by akien-mga** 2023-06-05 11:57 UTC

**Comment by michaldev** [comment] 2023-06-08 22:01
It seems that it's probably not the same issue after all. 

BTW, there's a minimal reproducible project attached in the post:
<img width="652" alt="Zrzut ekranu 2023-06-8 o 23 59 11" src="https://github.com/godotengine/godot/assets/5132385/157413c7-55b6-4ccb-9da5-5465ccf62f06">
<img width="652" alt="Zrzut ekranu 2023-06-8 o 23 59 13" src="https://github.com/godotengine/godot/assets/5132385/c3c14acf-199e-4839-a964-b26cae546fd0">
