### ISSUE TITLE
draw_polyline skips lines in GLES2

### ISSUE THREAD

**Issue by Sakar** [godotengine/godot#38703] opened 2020-05-12 21:39 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Windows 10
macOS Catalina 10.15.1

**Issue description:**
When the video driver is set to GLES2, `draw_polyline` skips every other line, giving a dashed line effect. Switching to GLES3 resolves this issue.

GLES2:
![gles2](https://user-images.githubusercontent.com/371438/81747095-8748c880-9475-11ea-8a67-672c6b60ae8b.png)

GLES3:
![gles3](https://user-images.githubusercontent.com/371438/81747101-89128c00-9475-11ea-8697-fe45fdccd3c0.png)

**Steps to reproduce:**
Call `draw_polyline` with any set of points. Change video driver between GLES2 and GLES3 to observe difference.

**Minimal reproduction project:**
[Polyline_Test.zip](https://github.com/godotengine/godot/files/4618538/Polyline_Test.zip)

**Comment by allkhor** [comment] 2020-05-13 19:38
Confirmed on **Godot v3.2.2.beta.custom_build.** e42318e
OS: **Xubuntu 16.04.6 LTS**
Workaround: change default width to: 
`draw_polyline(circle_points, Color.white, 1.0000001).`

**Comment by Calinou** [comment] 2020-05-14 07:29
> draw_polyline(circle_points, Color.white, 1.0000001).

This is because it makes Godot use triangle strips to draw lines rather than OpenGL's line primitives.

**Comment by lawnjelly** [comment] 2020-05-14 09:05
The problem is actually simple! GLES3 is drawing a polyline as a GL_LINE_STRIP (each new vertex adds a new linked line) and GLES2 is drawing it as GL_LINES (each pair of vertices forms a line).

All we need to do is agree on a standard so they both do the same thing! :grinning:

**Comment by akien-mga** [comment] 2020-05-14 18:33
Fixed by #38734.

**Closed by akien-mga** 2020-05-14 18:33 UTC
Labels: bug, topic:rendering
