### ISSUE TITLE
[C#] Scripts that export a 'resource' type in a property cannot be assigned without an InvalidCastException

### ISSUE THREAD

**Issue by Panthr75** [godotengine/godot#83980] opened 2023-10-26 04:59 UTC
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Windows 10

### Issue description

For C# Scripts that have a custom property list where one of the properties's hint is `HintType.ResourceType` and the hint string is the name of the script, attempting to assign it throws an InvalidCastException:
```
modules/mono/glue/runtime_interop.cpp:1324 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'Y'.
  at X._Set(StringName property, Variant value)
  at Godot.Bridge.CSharpInstanceBridge.Set(IntPtr godotObjectGCHandle, godot_string_name* name, godot_variant* value) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 67
```

### Steps to reproduce

# Generic Overview
1. Create a script named `Foo.cs`
2. Create a script named `Bar.cs`
3. Open the `Bar.cs` script. Make the base class `Resource`
4. Mark `Bar` as a `GlobalClass`
5. Open `Foo.cs`
6. Mark `Foo` as a `Tool`, and `GlobalClass`.
7. Paste the following code inside the class body of `Foo`:
```cs
private Bar barRef;

public override Variant _Get(StringName property)
{
  if (property == "bar_ref")
  {
    return this.barRef;
  }
  return default;
}

public override bool _Set(StringName property, Variant value)
{
  if (property == "bar_ref")
  {
    this.barRef = value.As<Bar>();
  }
  return true;
}

public override Array<Dictionary> _GetPropertyList()
{
  return new Array<Dictionary>()
  {
    new Dictionary()
    {
      ["name"] = "bar_ref",
      ["hint"] = (int)PropertyHint.ResourceType,
      ["type"] = (int)Variant.Type.Object,
      ["usage"] = (long)PropertyUsageFlags.Default,
      ["hint_string"] = nameof(Bar)
    }
  };
}
```
8. Import missing references like `Godot.Collections`
9. Save both scripts and recompile them
10. Create a new `Bar` resource in the FileSystem
11. Create a new `Foo` object in a scene.
12. Attempt to assign `Bar` to `bar_ref` property in `Foo`
13. InvalidCastException

# Minimal Reproduction Project
1. Open up the project
2. Make sure to compile the scripts
3. Open `root` scene if not already open.
4. On the root node, there should be a script named `Foo`. If not, add it.
5. Click on the `Bar Ref` property and assign it to `bar` in the FileSystem
6. InvalidCastException

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/13173001/project.zip)

**Comment by raulsntos** [comment] 2023-10-26 17:58
Tool scripts are instantiated and executed in the editor, but non-Tool scripts are not. Your `Bar` type is not marked with the `[Tool]` attribute so the editor can't instantiate it when you assign it to a property of the Tool script `Foo`.

Add the `[Tool]` attribute to the `Bar` type or use a less specific type for the `Foo.barRef` field (e.g.: `Resource`).

- Duplicate of https://github.com/godotengine/godot/issues/55596.

**Closed by raulsntos** 2023-10-26 17:58 UTC
Labels: bug, topic:dotnet

**Comment by Panthr75** [comment] 2023-10-26 22:04
Is it possible that there make a specific error for this in the editor instead of throwing an Invalid Cast Exception?
