### ISSUE TITLE
Crashes when triggering autocomplete in Visual Studio Code

### ISSUE THREAD

**Issue by cstria0106** [godotengine/godot#51977] opened 2021-08-22 09:57 UTC
### Godot version

3.3.3.stable.official.b973f997f

### System information

macOS BigSur 11.5.1

### Issue description

Sorry for my poor English. Godot crashes when editing godot script and triggering autocomplete (control + space) on empty line in Visual Studio Code.

No problem on Godot version 3.3.2. I think it only occurs on 3.3.3.

Here is error log on console.

```

handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff20440d7d _sigtramp + 29
[2] 2   ???                                 0xaaaaaaaaaaaaaaaa 0x0 + 12297829382473034410
[3] Image::copy_internals_from(Ref<Image> const&)
[4] Object* ClassDB::creator<GDScriptWorkspace>()
[5] Object* ClassDB::creator<GDScriptWorkspace>()
[6] Object* ClassDB::creator<GDScriptWorkspace>()
[7] Object::get_instance_id() const
[8] Object::get_instance_id() const
[9] EditorPlugin* EditorPlugins::creator<GridMapEditorPlugin>(EditorNode*)
[10] EditorPlugin* EditorPlugins::creator<GridMapEditorPlugin>(EditorNode*)
[11] Object* ClassDB::creator<GDScript>()
[12] Object* ClassDB::creator<GDScript>()
[13] GDScriptLanguageProtocol::is_initialized() const
[14] GDScriptLanguageProtocol::is_initialized() const
[15] Image::copy_internals_from(Ref<Image> const&)
[16] Node::is_inside_tree() const
[17] Node::is_inside_tree() const
[18] DirAccess* DirAccess::_create_builtin<DirAccessOSX>()
[19] DefaultAllocator::alloc(unsigned long)
[20] DirAccess* DirAccess::_create_builtin<DirAccessOSX>()
[21] 21  libdyld.dylib                       0x00007fff20416f3d start + 1
-- END OF BACKTRACE --
```

### Steps to reproduce

* Create empty project.
* Create new Godot Script.
* Open the script with Visual Studio Code.
* Trigger autocomplete on empty line. (by pressing Control + Space)

**Comment by Calinou** [comment] 2021-08-22 10:06
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-08-22 10:06 UTC
