### ISSUE TITLE
GLES2 Dissolve Shader shadow bug

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#29581] opened 2019-06-07 15:53 UTC
**Godot version:** Godot 3.1.1

**OS/device including version:** Windows 10

**Issue description:**

GLES3 | GLES2
:---:|:---:
![GLES3](https://user-images.githubusercontent.com/12462089/59116768-7e529b80-8976-11e9-9779-1ae495bfd9ac.png) | ![GLES2](https://user-images.githubusercontent.com/12462089/59116785-8d394e00-8976-11e9-8ce4-e20963c6a961.png)

**Minimal reproduction project:**

[DissolveShadow.zip](https://github.com/godotengine/godot/files/3266696/DissolveShadow.zip)

**Comment by Calinou** [comment] 2019-06-07 16:00
This sounds similar to https://github.com/godotengine/godot/issues/26568 or https://github.com/godotengine/godot/issues/27207 (not sure which).

**Comment by clayjohn** [comment] 2019-06-23 06:10
Good catch, duplicate of https://github.com/godotengine/godot/issues/26568

**Closed by clayjohn** 2019-06-23 06:10 UTC
Labels: bug, topic:rendering
