### ISSUE TITLE
Distribute Godot on the Windows 10 Store

### ISSUE THREAD

**Issue by anneomcl** [godotengine/godot#17985] opened 2018-04-05 04:34 UTC
I know the open source art program Krita has done something similar, but perhaps Godot could be on the Windows 10 app store along with Steam to streamline the update experience for those who don't have the Steam client open all the time. Krita is also a paid app, so perhaps that could help fund development if there's interest in that option.

**Comment by akien-mga** [comment] 2018-04-05 11:28
What are the requirements for shipping on Windows 10 Store? Does it need to be a UWP app, or can it be a classical win32 like our current version?

**Comment by vnen** [comment] 2018-04-05 20:10
In theory it might work with the Desktop Bridge, but it needs further investigation.

**Comment by Calinou** [comment] 2018-04-05 20:44
For the record, [Inkscape is also available in the Windows Store](https://inkscape.org/en/release/0.92.3/windows/windows-store/dl/). I don't think it's an UWP application, so there must be a way to do it (sandboxing will very likely be applied to the executable still).

**Comment by vnen** [comment] 2018-04-05 20:53
Yes, the Desktop Bridge allows a regular Win32 app to be packaged and published in the store. I do think it is sandboxed and might forbid some syscalls, so it needs to be properly tested.

What concerns me most is the process forks for running the editor from the project manager and running the game from the editor.

**Comment by anneomcl** [comment] 2018-04-05 21:04
If there are any concerns with onboarding that are not on any Microsoft docs, I can get in contact with the store team. I used to work with them and I'm sure they'd be happy to have more apps like Godot.

I'm not as familiar with the intricacies of Godot's source, but as mentioned, there mainly needs to be a UWP wrapper around the Win32 app.

**Comment by mattiascibien** [comment] 2018-04-13 08:09
Here is a simple packaging project i built using [this guide](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net) for packaging. It seems that the app is running fine but I have not tested it intensively. The included godot.exe is the x64 version of the latest stable release downloaded from the website.
[GodotWinStore.zip](https://github.com/godotengine/godot/files/1906390/GodotWinStore.zip)

**Comment by vnen** [comment] 2018-07-11 17:52
I tested the Desktop Bridge and it seems to work fine with Godot. I need to do more thorough tests in [S mode](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-test-windows-s) but at first it seems to work fine (apart from things that call external programs, like some exporting processes). And I doubt anyone will do real development on a Windows S system, since it's too restricted and many dev tools can't even be installed.

The sandbox isn't that bad and allow downloading projects from the asset lib, creating folders and projects in a user-selected, and run the projects from the editor.

I also need to investigate the proper way to open a store account for Godot.

**Comment by akien-mga** [comment] 2018-07-22 10:12
Note that publishing on the Windows Store doesn't seem to be frictionless: https://twitter.com/Krita_Painting/status/1019849392835190785

Their 10.8.5 policy which is bothering Krita might also kill the Asset Lib for the Windows Store build.

**Comment by Calinou** [comment] 2019-12-21 16:52
Is this still relevant today, considering the current state of the Windows 10 store?

**Comment by vnen** [comment] 2020-01-02 14:20
The advantage of publishing would be that we get a signed binary that won't trigger the usual Windows warnings. It also has an auto-updater (which can be good or bad, but would be the same as the Steam version).

**Comment by GeorgeS2019** [comment] 2020-01-14 23:20
can someone either close this or assign this to milestone 4.0 just like [this](https://github.com/godotengine/godot/issues/20271) and [this](https://github.com/godotengine/godot/issues/19320)?

**Comment by GeorgeS2019** [comment] 2020-06-22 00:30
@anneomcl  please check if this [recent UWP export experience](https://github.com/godotengine/godot/issues/30558#issuecomment-644163804) address your issue

**Comment by vnen** [comment] 2020-06-22 00:43
@GeorgeS2019 can you please read the issues before spamming your message? This issue is about publishing the Godot editor in the Windows store, it has nothing to do with UWP export.

**Comment by GeorgeS2019** [comment] 2020-06-22 00:56
@vnen, in my view, UWP export is still not easy to reproduce. Making Godot as Windows (UWP instead of Win32) Store app is more of feature proposal than an issue to be discussed here.

**Comment by vnen** [comment] 2020-06-22 02:02
@GeorgeS2019 we can publish a Win32 app in the store as I mentioned before. This doesn't need UWP at all. This issue is more about bureaucracy (having an official Godot account in the MS store and integrating it in the release process) than technical (except for the Desktop Bridge integration).

Though my point was that this is not related to UWP export so your comment was not relevant.

**Comment by GeorgeS2019** [comment] 2020-06-22 02:21
@vnen    the future of NET5 and future Windows OS is to move away from Win32 to UWP.  The fact that the label has been changed from Windows to UWP reflects the "Future-looking" thinking.

**Comment by vnen** [comment] 2020-06-22 02:43
@GeorgeS2019 label change was a mistake that I didn't notice before. It doesn't matter what the future is supposed to be, this issue is not about UWP export, it's about the editor and not about exported games.

**Comment by Calinou** [comment] 2022-01-25 14:55
Closing, as the UWP platform port is considered in maintenance mode (and is unlikely to be ever able to run a full-blown Godot editor with no caveats).

**Closed by Calinou** 2022-01-25 14:55 UTC
Labels: enhancement, platform:windows, topic:porting

**Comment by mattiascibien** [comment] 2022-01-25 15:00
What about publishing as Win32? It is now possible without issues. Did the publishing of both a .NET packaged app and a win32 one and everything went pretty fine.

**Comment by Calinou** [comment] 2022-01-25 15:03
> What about publishing as Win32? It is now possible without issues.

I didn't know this was possible :slightly_smiling_face: 

Is a bridging process still required? I remember it breaking a lot of things and only working reliably with Electron apps.

**Comment by mattiascibien** [comment] 2022-02-02 08:25
Hello,

I finally found the time to test this. I have packaged godot 4.0 alpha1 using MSIX and it went pretty fine at the moment. Godot is installed fine using Win11 app installer and it runs fine without issues. At the moment I have used [Advanced Installer Express](https://www.advancedinstaller.com/express-edition.html) to package the app as it is the easiest way at the moment (not the only one, it should also be possible to use the WapProj Template From Visual Studio but I did not succeed in packaging a single compiled exe, only C++ and .NET apps linked as a project dependency at the moment).

![image](https://user-images.githubusercontent.com/1300681/152117263-f036c58c-6cff-453b-8a39-8a5f9887cef1.png).

Here is an MSIX file signed with a test certificate which should be installed in Current User->Personal (the pw is the same as the cert name).

**Be warned though**: the test certificate, after testing should be removed so you don't have holes in your security, but it is the same with all the self-created ones. This won't be a problem as it should be used only to upload on the windows store, where Microsoft actually replaces it with their own secure one.

Here is the test MSIX: https://we.tl/t-fnmlN1yfHY

Also remember that there is still the option to upload Win32 apps directly to the microsoft store if needed but it is needed to get in touch with Microsoft.

**Comment by ZarmDev** [comment] 2022-09-07 18:59
So is godot considering distributing Godot on ms store?

**Comment by Calinou** [comment] 2022-09-08 01:04
> So is godot considering distributing Godot on ms store?

There are no plans to release Godot on the Microsoft Store for now.

**Comment by hawkerm** [comment] 2023-04-09 06:23
Having Godot installable through store or `winget` would be nice as then you can get auto-updating capabilities of MSIX packaging.

Right now having to manually check for updates, download each interim release of the .NET version, unzip to a folder, resetup some shortcut to run the exe... there's a lot of steps.

Would be nice to just have installed and auto-update when there's a new version, or be able to install/uninstall versions side-by-side in `winget`. Also, would make setting up a new dev-box or sandbox environment easier.

**Comment by Calinou** [comment] 2023-04-10 18:41
> Right now having to manually check for updates, download each interim release of the .NET version, unzip to a folder, resetup some shortcut to run the exe... there's a lot of steps.

This is all you need:

```command
scoop install godot-mono
```
