### ISSUE TITLE
Can't edit Theme

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#4636] opened 2016-05-12 13:43 UTC
**Operating system or device - Godot version:**
Arch Linux - Godot version May 12, 2016 (48dc4d92a8f3c9eb42456eda2433c6fcaff0c723)

**Issue description** (what happened, and what was expected):
When choose edit Theme Godot will freeze.

**Steps to reproduce:**
- Add node that inherit from control (from me is Button)
- Inspector->Theme->Edit
- Godot freeze.

**Link to minimal example project** (optional but very welcome):
None

**Comment by vnen** [comment] 2016-05-12 16:00
I get a crash when I try this. But this is actually a problem with recent GCC as reported in #4623. I don't have the problem with Clang. So I'll archive this as duplicate of #4623, as it's the same problem.

For the time being, I recommend building Godot with Clang (add `CC="clang" CXX="clang++"` to the SCons command line).

**Closed by vnen** 2016-05-12 16:00 UTC
Labels: bug, topic:editor
