### ISSUE TITLE
Cannot Save Scene while Shader Editor is Open

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#84601] opened 2023-11-08 03:17 UTC
### Godot version

4.5 Beta 5

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

Cannot save any scene after changes while the Shader Editor is open.

### Steps to reproduce

- Open MRP
- Open Shader Editor by double-clicking on the Visual Shader
- Move the cube
- Try to save scene with Ctrl+S

### Minimal reproduction project

[ShaderEditorSaveBug.zip](https://github.com/godotengine/godot/files/13291645/ShaderEditorSaveBug.zip)

**Comment by jsjtxietian** [comment] 2023-11-08 04:32
I guess related to #84064.

**Comment by reduz** [comment] 2023-11-08 10:55
Folks, we are paper cutting with this all the time. I don´t know where this should be documented so we don´t keep running into this issue again every some years, probably the source code.

To clarify, the intended behavior is:

No matter where you are, if script editor, shader editor, scene editor, etc. Ctrl-S (or the shortcut assigned to save-scene) should always take precedence over everything else. When you save scene, all edited subresources or external resources are also saved, so its always a "save all" shortcut. If the script or shader editors have the same shortcuts as the scene save, then it should check this and trigger a scene save instead (and opened scripts/shaders will be saved anyway).

**Comment by WickedInsignia** [comment] 2023-11-08 11:17
Maybe a dedicated shortcut to save file separate from Ctrl+S is needed, such as Ctrl+Alt+S? There may be some cases someone wants to save a shader without saving their changes to a scene (maybe if they were experimenting with objects in the scene to test the shader and did not want to save those scene changes).
Using File > Save File seems fine to me though and I agree with you. I don't believe a good use-case existed to justify that commit.

**Comment by YuriSizov** [comment] 2023-11-08 11:35
> Maybe a dedicated shortcut to save file separate from Ctrl+S is needed, such as Ctrl+Alt+S?

That's what we had in the script editor, and it was a usability nightmare for many years, until we resolved it in Godot 4, allowing contexts for shortcuts. Then this was extended to the shader editor as well, because it's no different from the script editor at this point.

You can edit any number of shaders, unrelated to the current scene included. You can detach it and work in a different window, within a separate context from the main editor. You don't even have to have the 2D/3D view open, so saving the scene instead of the currently edited shader would be completely unexpected.

We want to have a WYSIWYG experience, so you save with intent. Alternatively, we need a true save everything shortcut, but that never existed and is not currently possible.

**Comment by WickedInsignia** [comment] 2023-11-08 12:02
Not being able to save scene while the shader editor is open is a usability nightmare all its own unfortunately. Saving the scene with related resources is the expected behavior currently across the editor, and is only broken in a couple corner cases that aren't expected by the user. "Save" isn't usually contextual in apps like other shortcuts and almost always refers to the overall scene or project file. This is consistent with other engines and 3D DCC tools.
The key to "saving with intent" is the intent part. There should be consistency the user can expect. Hitting Ctrl+S while editing a StandardMaterial shouldn't suddenly change behavior entirely when editing a VisualShader.
StandardMaterials have a "Save Resource" button that is easily accessible, and there's ample space to include the same thing in the shader/visualshader editor. Alternatively Blender uses Alt+S to save files external from the project file, such as images, so there'll be some overlap with users already familiar with that.

Not exactly sure what the best solution is, but Ctrl+S being hijacked while the shader editor is open ain't it. That's inconsistent UX design of arguably the single most important operation in the editor.

**Comment by YuriSizov** [comment] 2023-11-08 12:09
> Not being able to save scene while the shader editor is open is a usability nightmare all its own unfortunately.

That's just a bug, and it's fixable without drastic changes 🙃

**Comment by jsjtxietian** [comment] 2023-11-08 12:44
Just pop here to mention that before the shortcut commit, when no scene is opened and I'm editing my shader, if I press Ctrl +S to save my shader, godot's will have an Alert window as mentioned in #84039. If we change ctrl + s 's behaviour back to global save, this alert window might need some consideration.

**Comment by WickedInsignia** [comment] 2023-11-08 12:52
@akien-mga That makes sense but is a pretty serious UX inconsistency, even with adequate contextual highlighting. Although the Shader Editor can be broken out to float, it will still see plenty of use when docked and where Ctrl+S is expected to save the scene + resources. In every other docked window with the 3D editor open that's exactly what it does, including the ShaderMaterial editor.
In most other engines and DDC tools Ctrl+S is expected to save the project and not change contextually, such as how Blender uses Alt+S to save external files and avoid throwing a curveball.
Users will expect Ctrl+S to save the scene + shader file, just as it does with the StandardMaterial editor.
If the user wants to save the shader file but not the scene, they know to look for it since they know Ctrl+S always saves the scene and resources. For Ctrl+S **not** to do that is not expected behavior.

I may be pushing the issue here but Save is the single operation where users should always know exactly what to expect. If there's one thing to respect the industry standard on, it's this.

**Comment by akien-mga** [comment] 2023-11-13 11:21
I think we can consider this as fixed by #84614, and the discussion on the UX downgrade can be continued in #84623 which aims at addressing it.

**Closed by akien-mga** 2023-11-13 11:21 UTC
Labels: bug, topic:editor, topic:input, regression
