### ISSUE TITLE
Maintain Aspect anchor

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#15252] opened 2018-01-01 19:29 UTC
I was looking for this earlier and couldn't find. What I mean is, if any Control-based node occupies 25% of the screen on 480p, it must also occupy 25% of the screen in 1080p. I know how do this manually, you have to set the anchors like this:
```
Anchor left: pos.x / screen_width
Anchor top: pos.y / screen_height
Anchor right: (pos.x + size.x) / screen_width
Anchor bottom: (pos.y + size.y) / screen_height
```
But if the UI changes, there's the need to recalculate those anchors. There should be a 'Maintain Aspect' anchor that calculates it automatically using the code above. Or if there is already something that does this, then it should be more visible.

*I do know about viewport stretch on the project settings, but then it applies to everything*

**Godot 3.0 Beta 2**

**Comment by volzhs** [comment] 2018-01-01 20:29
why did you remove issue template? your godot version?

![screenshot from 2018-01-02 05-28-25](https://user-images.githubusercontent.com/8281454/34470842-ceeed96c-ef7d-11e7-8763-d2c071de7450.png)
with godot 3.0, you can do it like above.

this will cover top 25% of the screen on whatever screen size.

**Comment by mateusak** [comment] 2018-01-02 01:50
I included it now, although it was not really necessary since it's not present in neither 2.1 nor 3.0.
Yes, I know how to do it. The thing is, it's a pain in the ass. Imagine this; there's a screen of 1600x900, you have a button in X:35 and Y:27, the button is 16x16px. This means that to maintain aspect its anchors should be:

```
Left: 0.021875
Top: 0.03
Right: 0.031875
Bottom: 0.047778
```

Okay, but now for some reason I need to move the button. And there I go again to calculate its anchors. If it can be simplified, I don't see why it shouldn't.

**Comment by bojidar-bg** [comment] 2018-01-02 15:36
Maybe another dragging mode, in which it moves anchors instead of margins would help? Potentially it might be triggered by holding Ctrl/Shift/Alt.

**Comment by mateusak** [comment] 2018-01-02 15:39
I like how you approach problems @bojidar-bg. I like it very much.

**Comment by groud** [comment] 2018-01-02 15:44
I don't really get the problem. 
You can drag the anchors using the dedicated helpers (the green pins, activated with the 'h' key).

Also, if you activate smart snapping, anchors can be snapped to the node side, which should solve your problem.

**Comment by mateusak** [comment] 2018-01-02 15:49
Hmm... I can't do that. I don't know if I'm doing it wrong or what. But in any way, the issue then is visibility. I think there should be a toggle option to show anchor guides in the anchors submenu, since it's where people naturally go when messing with anchors.

**Comment by groud** [comment] 2018-01-02 15:51
It's in "View"/"Show helpers".

**Comment by mateusak** [comment] 2018-01-02 16:08
Here's a summary of improvements regarding anchors which would improve the creation and maintenance of UI:

- Every control node when selected should show its anchor helpers, disregarding 'Show helpers' option.
- When changing only anchors the node will get strangely relocated, which interrupts workflow.  (probably a bug)
- Add a 'Maintain aspect' button to 'Layout' which sets the anchors to the node's boundaries.

**Comment by groud** [comment] 2018-01-02 17:14
> Every control node when selected should show its anchor helpers, disregarding 'Show helpers' option.

When I implemented it @reduz told me it was better not to show them by default. But I'm personally not against the idea. This has to be discussed.

> When changing only anchors the node will get strangely relocated, which interrupts workflow. (probably a bug)

Can you open an issue for this one ? With a screen capture if possible, I cannot reproduce.

> Add a 'Maintain aspect' button to 'Layout' which sets the anchors to the node's boundaries.

Adding a "Set to the node's boundaries" option in "Layout" / "Anchors only", would make sense.
Maybe we can also have a modifier (ctrl, alt or shift) to keep the margin values when moving the anchors too.

**Comment by groud** [comment] 2018-01-12 08:59
> When changing only anchors the node will get strangely relocated, which interrupts workflow. (probably a bug)

This is fixed now.

**Closed** 2019-05-20 15:44 UTC
Labels: feature proposal, topic:editor
