### ISSUE TITLE
Exported variables are duplicated/rereferenced on duplicated scenes

### ISSUE THREAD

**Issue by fireWizard23** [godotengine/godot#83551] opened 2023-10-18 10:46 UTC
### Godot version

4.1.2.stable

### System information

Windows 11 - AMD Ryzen 5 Laptop

### Issue description

When you have an exported node like a Sprite, and its parent scene is duplicated, the duplicated scenes is now going to reference the same exported node. Basically, duplicated scene with exported variables will reference the original exported variable of the original scene

Tried it out in v4.0.4.stable it is working as expected. Tried out on 4.1.1.stable and 4.1.2.stable, the rereferencing is happening.
Drag & Dropping the same scene will not have the same bug. Only duplication (ctrl + D) will cause the bug.

### Steps to reproduce

1. Have a main scene.
2. Create a mob scene
3. Attach a script to mob scene
4. Add an exported node
5. Assign the exported node in the editor
6. Drag and drop the mob scene in the main scene
7. Duplicate (Ctrl + D) the dragged mob 

The duplicated mob scene is now going to reference the same exported node

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/13011616/reproduction.zip) <--- 4.0 bug not here

[reproduction.4.1.zip](https://github.com/godotengine/godot/files/13011814/reproduction.4.1.zip) <--- 4.1 bug here

**Comment by lostminds** [comment] 2023-10-18 15:30
Looks like duplicate of https://github.com/godotengine/godot/issues/82670?

**Comment by AThousandShips** [comment] 2023-10-22 13:29
Duplicate of #82670

**Closed by AThousandShips** 2023-10-22 13:29 UTC
