### ISSUE TITLE
GDScript editor parse error with hex literals containing "b"

### ISSUE THREAD

**Issue by johngirvin** [godotengine/godot#33711] opened 2019-11-18 16:08 UTC
**Godot version:**
3.2 BETA 1

**Issue description:**
An "parse error" is raised in the GDScript editor when entering a hex literal containing a lower case "b" character.

**Steps to reproduce:**
1. Open a GDScript editor
2. Enter the code `var x = 0xb`
3. Observe the "Parse error: Invalid numeric constant at 'b'" message
4. Alter the code to `var x = 0xB`
5. Observe the parse error is cleared

**Comment by Calinou** [comment] 2019-11-18 16:23
Duplicate of #33710.

**Closed by Calinou** 2019-11-18 16:23 UTC
