### ISSUE TITLE
Weapon Trail Node

### ISSUE THREAD

**Issue by RevampedSpider** [godotengine/godot#25206] opened 2019-01-22 04:14 UTC
I think one of the biggest letdowns of Godot for me is the inability to create good weapon trails with the Particle system. That's why I think Godot should have a node that can create a weapon trail in 3D and 2D. A user could have two nodes that they put on the bottom and top of the blade. This would be a really helpful feature for people making hack and slash games and such. There could also be customization options for the trail like what color it would be, lifetime, and even the texture. This would be a really great addition and would more than likely allow me to decide to use Godot for my games rather than struggle with the choice between Unity and Godot.

**Comment by girng** [comment] 2019-01-22 05:50
uncheck local cords, attach particle to your weapon =]

**Comment by groud** [comment] 2019-01-22 08:19
Duplicate of #22217

**Closed** 2019-01-22 08:19 UTC
Labels: archived
