### ISSUE TITLE
Tooltips get cropped at window border when using single window mode

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#59942] opened 2022-04-06 15:38 UTC
### Godot version

4.0 dev (e4f0fc50f79336cf76beec40e5e8e5164b288714)

### System information

macOS 12.3.1

### Issue description

The tooltip gets cropped by the window border:

![Screen Shot 2022-04-06 at 11 04 57](https://user-images.githubusercontent.com/5599796/162012835-8bd48be4-254d-4f52-8aca-51906b9c202b.png)

When using single window mode, the tooltip cannot extend across the window boundaries. In this case the tooltip should be repositioned to not be cropped.

### Steps to reproduce

- Enable single window mode.
- Hover the mouse cursor over a button on the edge of the window, such as the Play Scene button.

### Minimal reproduction project

Can be reproduced with an empty project.

**Comment by Sauermann** [comment] 2022-11-22 17:22
I can't reproduce this behavior on WIndows 10 and on Linux X11 Xfce with v4.0.beta.custom_build [e3a51e53e].

Seems to be a duplicate of #66477 which got solved by #67046.

**Closed** 2022-11-22 17:27 UTC
Labels: bug, topic:editor
