### ISSUE TITLE
Running the debugger opens godot engine menu

### ISSUE THREAD

**Issue by tam0705** [godotengine/godot#12856] opened 2017-11-12 10:27 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 aplha 2 - Windows 10

**Issue description:**

I run godot's debugger and it showed godot engine main menu instead of my project. The bug still happened randomly after I restarted the editor.
This is what console prints in normal way:

 ```
running cmdline: "D:\Godot Engine\Godot_v3.0-alpha2_win64.exe" "--path" 
"D:/Godot%20Engine/Projects/3.0%20networking" "--remote-debug" "127.0.0.1:6007" "--
allow_focus_steal_pid" "10748" "--position" "171,84"
```

and what it prints when the bug appeared (if I remembered):

```
running cmdline: "D:\Godot Engine\Godot_v3.0-alpha2_win64.exe" "--path"  "D:/Godot%20Engine/Projects/3.0%20networking" "--remote-debug" "127.0.0.1:6007" "--
allow_focus_steal_pid" "10748" "--position" "171,84" "res://lobby.tscn"
```

`lobby.tscn` is my main scene.

**Comment by Noshyaar** [comment] 2017-11-12 10:43
Duplicate of #11391?

**Comment by akien-mga** [comment] 2017-11-12 20:05
> Duplicate of #11391?

Looks like it yes.

**Closed by akien-mga** 2017-11-12 20:05 UTC
