### ISSUE TITLE
Editor: I can not hide GridMap (2.1.x)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#7601] opened 2017-01-21 18:42 UTC
**Operating system or device - Godot version:**
win

**Issue description:**

**Steps to reproduce:**
1 create a GridMap
2 draw there anything
3 click on the icon show/hide for GridMap and it can not be hidden.

**Link to minimal example project:**
:

**Comment by akien-mga** [comment] 2017-01-21 18:48
Duplicate of #907. Please mention your Godot version next time, as asked in the template.

**Closed by akien-mga** 2017-01-21 18:48 UTC
