### ISSUE TITLE
(Feature request) Configure the template added to each script

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#6838] opened 2016-10-16 01:23 UTC
Just thought it would be nice to be able to configure the template for each type of script, just to automatize something the programmer want on every script, or just to get rid of the current template.

I just wonder if it would be best to handle this as a Project Setting or as an Editor Setting (IMO a project setting would handle it well).

**Comment by vnen** [comment] 2016-10-16 01:34
Duplicate of #4132, which is more ample.

**Closed by vnen** 2016-10-16 01:34 UTC
