### ISSUE TITLE
[Suggestion] Allow the ignoring of detected assets, with a .gdignore

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#10075] opened 2017-08-04 05:23 UTC
So, while using Godot I've experienced a few annoyances with the import system, notably bloat in the repository due to automatically imported files. For example, I have a folder with documents for my game, and included are images. These images would never be included in the game, but instead in the documentation, and yet Godot automatically imports the images. What I suggest is allowing for a .gitignore-like system, where users can define a pattern, directory, or file they want Godot to overlook.

**Comment by Hinsbart** [comment] 2017-08-04 06:55
Duplicate of #8461

**Closed by Hinsbart** 2017-08-04 06:55 UTC
