### ISSUE TITLE
Some cursor types not being drawn correctly

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#14878] opened 2017-12-20 18:38 UTC
**Godot version:**
master:  045f810

**OS/device including version:**
Ubuntu 17.10

**Issue description:**
- **CURSOR_BDIAGSIZE & CURSOR_FDIAGSIZE:** Shows default arrow.
- **CURSOR_MOVE & CURSOR_CAN_DROP:** Shows pointing hand.
- **CURSOR_VSPLIT & CURSOR_HSPLIT:** They are supposed to show the system's split cursor. I don't think my current cursor theme has this one, but I'm putting here just in case.

**Comment by akien-mga** [comment] 2018-01-05 11:44
CC @guilhermefelipecgs @xsellier.

**Comment by guilhermefelipecgs** [comment] 2018-01-05 12:33
@YeldhamDev Can you provide a example? I couldn't reproduce this.

**Comment by YeldhamDev** [comment] 2018-01-05 16:33
@guilhermefelipecgs I've a done some more testing, and it seems that **BDIAGSIZE** and **FDIAGSIZE** work on some cursor themes but not others (works with Breeze, but not with DMZ, for example). But **MOVE** and **CAN_DROP** doesn't seem to work at all.

[Test.tar.gz](https://github.com/godotengine/godot/files/1607175/Test.tar.gz)

**Comment by guilhermefelipecgs** [comment] 2018-01-05 21:48
This is a problem with the theme itself.
Gnome use Adwaita, KDE use Breeze, but both have incompatible cursor names. ```CURSOR_MOVE``` for example, is setted to ```hand1``` in Godot, in Adwaita ```hand1``` is "closed hand" and in Breeze is "pointer". I don't think it's worth trying to fix it because doesn't exisit a convention in Linux for cursor's name.
I don't know what we can do about that :(

**Comment by reduz** [comment] 2018-01-06 17:03
On Unixes, this is highly window manager / theme dependent. I'm not sure it can be fixed.

**Comment by akien-mga** [comment] 2018-01-08 15:30
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by xsellier** [comment] 2018-01-08 15:35
We might add a note for the Linux user in the documentation saying that the behavior may change depending on the user cursor theme used.

**Comment by akien-mga** [comment] 2020-02-08 22:58
Reopening so that #36003 can close it properly.

**Closed** 2020-02-10 09:40 UTC
Labels: bug, platform:linuxbsd, topic:gui, topic:porting
