### ISSUE TITLE
Save branch as scene on a control node also adds hidden nodes to the scene

### ISSUE THREAD

**Issue by kilojool** [godotengine/godot#59243] opened 2022-03-17 15:32 UTC
### Godot version

4.0.alpha4.official

### System information

Windows 10

### Issue description

When using the Save Branch as Scene on a more complicated control node such as GraphEdit, the "hidden" nodes are also saved to the scene.
![Skärmklipp](https://user-images.githubusercontent.com/2656574/158834701-73189913-7698-41fd-8a1e-cffd7654cbf5.PNG)

### Steps to reproduce

Add any Control node which contains "hidden" nodes, such as a TabContainer or GraphEdit, and then right click and choose Save Branch as Scene on it or it's parent.

**Comment by KoBeWi** [comment] 2022-04-24 09:01
Duplicate of #54960

**Closed by KoBeWi** 2022-04-24 09:01 UTC
Labels: bug, topic:editor, regression
