### ISSUE TITLE
"Attach script" does not work when a shader editor is open

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#23402] opened 2018-10-30 14:12 UTC
**Godot version:** 955a913a1fcc7551a3e03017eb2ac8edc4ee7043

**Issue description:**

When the shader editor is open, and in the Scene tree one right-clicks on a node, the pop up menu opens as usual. When selecting "Attach script" from there, nothing happens.

Workaround: left-click on the node in the scene tree. The shader editor will close. Now right-click and "Attach shader", and it works.

**Comment by volzhs** [comment] 2018-10-30 17:21
I guess it's same issue with #19714

**Comment by akien-mga** [comment] 2018-10-31 09:18
Duplicate of #19714.

**Closed by akien-mga** 2018-10-31 09:18 UTC
