### ISSUE TITLE
Kinematicbody3d   is_on_floor retrigger when it on the ground    (bug)

### ISSUE THREAD

**Issue by cg1743gmail** [godotengine/godot#34917] opened 2020-01-08 15:01 UTC
**Godot version:**  any   3.2v5  3.1 2,3.2v4

**OS/device including version:**window

**Issue description:**  Kinematicbody3d   is_on_floor retrigger when it on the ground    (bug),
like this:    
func   physics_process(delta):
         fall()
        move_and_slide(motion)
func fall():
	if is_on_floor():
		motion.y = 0
print(" grounded")
	else:
               motion.y = gravity 
               print(" i am fly")

it will happen like this:   grounded,i am fly......   grounded,i am fly......   grounded,i am fly......   grounded,i am fly......for ever, how to slove that?
		
		

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-01-13 22:33
Duplicate of #33833.

**Closed by Calinou** 2020-01-13 22:33 UTC
