### ISSUE TITLE
Menu and mouse behavior enhancement suggestion

### ISSUE THREAD

**Issue by NiNEngine** [godotengine/godot#19601] opened 2018-06-16 15:18 UTC
**Godot version:**
v3.0.2 official *(but applies to all versions if i'm not mistaken).

**OS/device including version:**
macOS / Ubuntu *(but applies to all versions if i'm not mistaken).

**Issue description:**
Currently, to trigger a menu option with the mouse is necessary to open the menu (click! - _**release**_), point the option and trigger the option (click! - _**release**_).

It would be possible to trigger them also opening the menu (click! and **hold**), point to the option an just then **release** the mouse button to trigger it? It is a common convention in most operating systems UI, and I really miss it.

I understand it can be difficult to implement, but in my opinion it would make the Godot UI even better and enjoyable than it already is.

**Minimal reproduction project:**
1. Click and **hold** the mouse button over the 'Scene' main menu.
2. Drag the mouse to 'New Scene'.
3. **Release** the button. It won't create a new scene!

Thank you.

**Comment by vnen** [comment] 2018-06-16 18:08
Duplicate of #11692

**Comment by NiNEngine** [comment] 2018-06-16 19:03
Hi! After reading #11692 (I couldn't find it before), I still think this is not a duplicate (at least, of that issue).

Currently, you can't open _another_ menu, hovering (with or **without** holding the mouse button) over it **nor clicking while the previous one is open** (like in #15939). But this is orthogonal.

What I suggested was not opening another menu, nested or not. Was about something you _can_ do with single clicks currently: triggering a menu option, like in the previous steps.

I mean: you can't (there is no way) to:
1. Open the Scene menu.
2. Open its sibling, Project menu, and closing Scene menu in just one step.

This is described implicitly in #11692. He compare it with Blender - where its not necessary to hold the button to get that result.

What I suggested was:
1. **Click and hold** the mouse button over the 'Scene' main menu.
2. Drag the mouse to **its son** 'New Scene'.
3. **Release** the button. It won't _do stuff_ (not related with opening a menu)!

Which **it's currently possible** using simple clicks:
1. **Click and release** the mouse button over the 'Scene' main menu.
2. Drag the mouse to its son 'New Scene'.
3. **Click and release**. It will _do stuff_ (not related with opening a menu)!

Because I considered #11692 and #15939 separated issues (even before I knew they were already submitted), I omitted additional details as "what to do if the menu is open through clicking and holding, but the mouse is released out of the menu area?": that would be related to those issues as that kind of things **won't work as expected even clicking and releasing the button**.

I'm sorry if I expressed myself bad: I can't make a gif of the mouse button!

Thank you, again!

**Comment by vnen** [comment] 2018-06-16 19:13
Sorry, I misread the request.

**Comment by dreamsComeTrue** [comment] 2019-10-18 20:21
I believe this is fixed now (3.2 alpha)

**Comment by Calinou** [comment] 2019-10-18 21:35
If I'm reading OP correctly, the main point of this feature request is implemented, but it's not possible to hold down the mouse button on a menu, switch to another menu, then release the mouse button on an option in the other menu. In contrast, this is possible in Blender 2.80.

I tested this on commit https://github.com/godotengine/godot/commit/119bf237209414a49879fba40459f22315ab1467.

**Comment by dreamsComeTrue** [comment] 2019-10-18 21:39
>  but it's not possible to _hold down_ the mouse button on a menu, switch to another menu (without releasing the mouse button first), then release the mouse button on an option in the other menu.
> 

Yep, that's right - this one is still missing.

**Comment by NiNEngine** [comment] 2019-11-24 00:05
It works there, and can also be done in the current version. This makes me so happy. Thank you : )

**Comment by akien-mga** [comment] 2020-06-02 09:54
Closing as apparently the main part is fixed already.

We're moving feature proposals to [godot-proposals](https://github.com/godotengine/godot-proposals), so if more work is needed on this area and does not qualify as bug reports, please open proposals there.

**Closed by akien-mga** 2020-06-02 09:54 UTC
Labels: feature proposal, topic:editor, usability
