### ISSUE TITLE
intersect_ray does not return closest collider when using Bullet physics

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#12711] opened 2017-11-07 00:50 UTC
Windows 10 Home Edition
NVidia GTX 950
Custom Godot 3.0 build

Calling intersect_ray inside _physics_process is not returning the closest collider.  This problem happens when Bullet physics is selected as the physics engine.  When GodotPhysics is selected I get the intended behavior.  The first gif shown below is not what I want and represents Bullet physics.  The second gif is using GodotPhysics.  The blue cube is being moved around using the AnimationPlayer.

![your_gif_from_mp4togif_com_1510015314554](https://user-images.githubusercontent.com/7462993/32471403-b8d24dda-c322-11e7-9009-e8938f8ed814.gif)
![your_gif_from_mp4togif_com_1510015356362](https://user-images.githubusercontent.com/7462993/32471411-be010dbe-c322-11e7-813a-b756b0b5a40d.gif)

Steps to Reproduce:

1. Open Test.tscn
2. Switch Physics Engine to "Bullet", run test scene
3. Switch Physics Engine to "GodotPhysics", run test scene

**Link to minimal example project:**
[MovieCam.zip](https://github.com/godotengine/godot/files/1448264/MovieCam.zip)

**Comment by supagu** [comment] 2017-12-13 00:10
I am getting a problem with intersect_ray also using bullet physics which is also not a problem with the godot physics.

For me, intersect_ray does not always intersect with collision shapes in my level. If I cast a ray straight through my sphere, it will seem to work with some collision spheres, but not others.

**Comment by akien-mga** [comment] 2017-12-13 07:23
CC @AndreaCatania

**Comment by AndreaCatania** [comment] 2017-12-13 08:16
@remorse107 Thank you for report, @supagu can you please also upload a sample project so I can test both?

**Comment by supagu** [comment] 2017-12-14 00:49
@AndreaCatania getting a sample project is not really a trivial endeavour. I could give you access to my project, email me at supagu@gmail.com if you need this.

**Comment by AndreaCatania** [comment] 2017-12-23 00:34
I've tested it and I can confirm the problem, but this project is not focused to the raycast so debug it is harder.

So I've created an easier scene (that works correctly) with a moving object, thus I can confirm you that the intersect_ray returns the closest collision.

[MovieCam2.zip](https://github.com/godotengine/godot/files/1583733/MovieCam2.zip)

The problem is another, @supagu and @remorse107 are you able to create a sample project with this reproducible problem with more focus on intersect shape (something similar to the scene I did)? 

Thanks you in advance!!

**Comment by akien-mga** [comment] 2018-01-16 10:59
Not critical for the upcoming 3.0 release, so moving to the next milestone. A fix can still be cherry-picked for 3.0.x maintenance releases once available in the master branch.

**Comment by AndreaCatania** [comment] 2018-08-26 07:13
Recently I've modified how raycast works by adding a boolean that control if exclude or not areas... Can you please check if this issue still?

**Comment by remorse107** [comment] 2018-09-08 19:58
I reviewed your modified version of my project, and I also re-tested my old project.  The old MovieCam project works as it should using either physics engine.  So your recent change must have been the fix.

**Comment by AndreaCatania** [comment] 2018-09-09 12:11
Good :) I'm closing it. Thanks you for your issue report

**Closed by AndreaCatania** 2018-09-09 12:11 UTC
Labels: bug, topic:physics
