### ISSUE TITLE
Script Editor steals shortcut focus from FileSystem

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#48944] opened 2021-05-21 22:11 UTC
**Godot version:**

3.3.1-stable

**OS/device including version:**

Windows 10 (Pro) Version 20H2 (OS Build 19042.985)

**Issue description:**

I had been working on some GDScripts when I decided I wanted to duplicate one of the files in my project. I selected the file I wanted to duplicate and pressed Ctrl-D to duplicate the file. The line of code I last worked on in the script editor became duplicated ("Clone Down").

https://user-images.githubusercontent.com/227734/119202744-b01f7880-ba4e-11eb-9dd8-3fed0420c9b0.mp4

I expected the file I had selected in the FileSystem to be duplicated.

**Steps to reproduce:**
Create a new project.
Add a script to a node and enter the Script Editor.
Click on the script filename in the FileSystem view and press Ctrl-D in an attempt to duplicate it.
Notice that whatever line of code was last highlighted is now duplicated, but the file you selected has not been duplicated.

**Minimal reproduction project:**

[DuplicateBugMinimal.zip](https://github.com/godotengine/godot/files/6525280/DuplicateBugMinimal.zip)

**Comment by Calinou** [comment] 2021-05-21 22:58
This is one of those editor input focus issues that can't be fixed completely in `3.x`, but has been fixed in `master` already.

**Comment by Deozaan** [comment] 2021-05-21 23:07
> I'm fairly sure I've seen a duplicate of this, but I can't find it right now.

I tried searching for an existing issue before posting this, but I also couldn't find one that appeared to match.

**Comment by Paulb23** [comment] 2021-05-22 14:21
Yep duplicate of #46678

**Closed by Paulb23** 2021-05-22 14:21 UTC
Labels: bug, topic:editor, topic:input
