### ISSUE TITLE
2D Viewport Issues

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#58204] opened 2022-02-16 18:40 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

**Workflow Issues**

After creating a SubViewportContainer and a SubViewport and a child control. I cannot see anything, it is all pink and black until I close and reopen the scene? _This works in 3._
[![1.gif](https://i.postimg.cc/fyF270Mh/1.gif)](https://postimg.cc/SY6fkRXZ)
And then once it is visible it is not able to be laid out like a normal control? I need to reparent it to see the layout menu and center it? And then reparent it again to put it back? Perhaps there is a way to show and use the layout menu directly without extra steps? _This does not work in 3 either._
[![2.gif](https://i.postimg.cc/NfD7wH3G/2.gif)](https://postimg.cc/BX81TXZR)
And then after all that it looks like it is in the wrong position in editor (3/4 off screen) but is in right position when running.  _This works in 3._

**Main Issue**
I have a cursor class that draws custom animated cursors. It sets the position with `global_position = get_global_mouse_position()` but does not seem to work over viewport? _This works in 3._
[![3.gif](https://i.postimg.cc/wjJNjRPs/3.gif)](https://postimg.cc/75HhBhqx)

### Steps to reproduce

- run the project and notice mouse skip over viewport
- disable Cursor.tscn in autoload settings and works fine

### Minimal reproduction project

https://github.com/rakkarage/GenerateTexture

**Comment by Calinou** [comment] 2022-02-16 20:13
The first part of this issue is already reported in https://github.com/godotengine/godot/issues/55471.

If I understand correctly, the second part of this issue should have been fixed by https://github.com/godotengine/godot/pull/57082, which is included in 4.0alpha2. cc @madmiraal

**Comment by madmiraal** [comment] 2022-02-17 09:29
@rakkarage When reporting multiple issues, please open multiple issues and ensure that there is only one issue per issue report.

> After creating a SubViewportContainer and a SubViewport and a child control. I cannot see anything, it is all pink and black until I close and reopen the scene? This works in 3.

As identified by @Calinou, this is a duplicate of #55471.

> And then once it is visible it is not able to be laid out like a normal control? I need to reparent it to see the layout menu and center it? And then reparent it again to put it back? Perhaps there is a way to show and use the layout menu directly without extra steps? This does not work in 3 either.

This is a duplicate of #20619

> And then after all that it looks like it is in the wrong position in editor (3/4 off screen) but is in right position when running. This works in 3.

This is a separate issue and should be opened as a separate issue.

> I have a cursor class that draws custom animated cursors. It sets the position with global_position = get_global_mouse_position() but does not seem to work over viewport? This works in 3.

This is a duplicate of #30215. It doesn't work in 3.x either.

**Comment by akien-mga** [comment] 2022-02-17 09:46
Closing as duplicate of the aforementioned three issues.

Please open a new issue for this part specifically:

>> And then after all that it looks like it is in the wrong position in editor (3/4 off screen) but is in right position when running. This works in 3.
>
> This is a separate issue and should be opened as a separate issue.

**Closed by akien-mga** 2022-02-17 09:46 UTC
Labels: bug, topic:rendering, topic:input, regression

**Comment by Calinou** [comment] 2022-02-17 17:50
Superseded by https://github.com/godotengine/godot/issues/58247.
