### ISSUE TITLE
Script Editor drawing over Script Save Dialog

### ISSUE THREAD

**Issue by danielpcs** [godotengine/godot#7140] opened 2016-11-17 20:38 UTC
Windows 10 Home 64-Bits
Godot version: 2.1.1 Stable 32-bits

While editing an unsaved script if you have a function tooltip showing and try to save it the script editor is rendered over the Save Dialog.

Steps to reproduce:
1. Add a new script to a node from Inspector
2. Type the name of a function that uses arguments without adding any arguments and without closing it with ")"
3. Wait for the tooltip to show
4. _Ctrl+Alt+S_ to try to save it

[**Screenshot**](https://gyazo.com/31d2162beabcbb798e6bc52ff48a2348)

Additional info:
I think it might be related to Andreas Haas "Fix code completion drawing under other gui elements.".
It doesn't happen in 2.1.0 Stable so it's definitely a 2.1.1 bug.

**Comment by akien-mga** [comment] 2016-11-17 20:41
CC @Hinsbart. It might be worth checking if master is affected too.

**Comment by bojidar-bg** [comment] 2016-11-18 08:37
Duplicate of #6769, sorry (so, master should be unaffected)

**Closed by bojidar-bg** 2016-11-18 08:37 UTC
Labels: bug, topic:editor
