### ISSUE TITLE
WorldEnvironment Canvas Background Mode Affects Editor

### ISSUE THREAD

**Issue by mutater** [godotengine/godot#62683] opened 2022-07-03 16:46 UTC
### Godot version

4.11.dev afdae67

### System information

Windows 10, AMD Ryzen 5 3600, AMD Radeon 6700 XT, Vulkan

### Issue description

When a WorldEnvironment node is added to a 2d scene and the background mode is set to canvas, all popup menus in the editor are filled with the canvas color. I expect the editor to not be affected by the WorldEnvironment node, only the game.

NOTE: When closing the editor, the menus previously covered by the WorldEnvironment Canvas are visible for a split second.

![image](https://user-images.githubusercontent.com/55255197/177049143-e18590b7-ecd3-45bb-8a1d-1b8b68d5f987.png)
![image](https://user-images.githubusercontent.com/55255197/177049235-6c3b34b1-7133-4fe7-a09e-b34229fb745d.png)

### Steps to reproduce

Start a new project
Choose Node2D
Add a WorldEnvironment node
Set Background Mode to Canvas

### Minimal reproduction project

I don't know how to save the project because menus aren't visible.

**Comment by Calinou** [comment] 2022-07-03 18:58
Duplicate of https://github.com/godotengine/godot/issues/52467.

**Closed by Calinou** 2022-07-03 18:58 UTC
