### ISSUE TITLE
ctrl+s in script editor does not work without an open scene

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#28000] opened 2019-04-14 00:59 UTC
**Godot version:**

3.1

**OS/device including version:**

Any

**Issue description:**

The ctrl+s shortcut within the script editor does not work unless a scene file is currently open in the scene editor. It displays a warning telling you that you can only save with an open scene.

**Steps to reproduce:**
Close all scenes, edit a script, press ctrl+s.

**Minimal reproduction project:**

**Comment by KoBeWi** [comment] 2019-04-14 01:49
Duplicate of #22730?

**Comment by TheDuriel** [comment] 2019-04-14 02:18
Not quite. You can save manually. But the hotkey pops up with an error message.

**Comment by vnen** [comment] 2019-04-14 04:27
Duplicate of #11801 actually.

The thing is that <kbd>Ctrl</kbd>+<kbd>S</kbd> is the shortcut to save the scene (which can't be done if there's no scene to save). The shortcut to save a script is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd>.

**Closed by vnen** 2019-04-14 04:27 UTC
