### ISSUE TITLE
Simple "re-route" node for visual scripting

### ISSUE THREAD

**Issue by zachThePerson** [godotengine/godot#22258] opened 2018-09-19 17:54 UTC
In almost all other node editing software there is a really helpful node that does literally nothing; It just sits there and acts as a "noodle bender," so the flow of the noodles can be bent around other nodes.

Simple Photoshopped example: https://imgur.com/a/nMS6bvx

It's a really small detail, but I find when it comes to making clean and understandable node trees they are a lifesaver

**Comment by groud** [comment] 2018-09-19 18:56
Duplicate of #11001

**Closed by groud** 2018-09-19 18:56 UTC
Labels: enhancement, topic:visualscript, usability
