### ISSUE TITLE
Editor crashes when attempting to rename node within BlendTree editor

### ISSUE THREAD

**Issue by skn3** [godotengine/godot#61808] opened 2022-06-08 12:56 UTC
### Godot version

4.0.alpha9

### System information

osx Monterey 12.3.1, Vulkan, MacBook Pro (14-inch, 2021

### Issue description

Editor crashes when attempting to rename node within BlendTree editor.

### Steps to reproduce

Create an AnimationTree
Add a BlendTree node
Edit the BlendTree
Add a OneShot (or any other) node
Click the text entry box to rename the new OneShot node
Editor hard crashes!

**Comment by Calinou** [comment] 2022-06-08 15:56
Related to https://github.com/godotengine/godot/issues/58822 (possible duplicate?).

**Comment by SoapSpangledGames** [comment] 2022-07-03 12:30
I have the same issue in 4.0 alpha 10. I'm also seeing the same behavior as in #58822. When a crash doesn't occur, the resulting name changes randomly or it changes to null. At times, the name of the previously selected node changes (to null or to some other name previously used by some other randomly chosen node) at the same time.

The name change seems to work more frequently when I tab out of the name field, but not always.

**Comment by Calinou** [comment] 2022-11-04 19:22
Duplicate of https://github.com/godotengine/godot/issues/58822.

**Closed by Calinou** 2022-11-04 19:22 UTC
Labels: bug, topic:editor, confirmed, crash, topic:animation
