### ISSUE TITLE
RayCast2D behaves erratically if a lot of exceptions are added

### ISSUE THREAD

**Issue by whitelion351** [godotengine/godot#37736] opened 2020-04-10 02:55 UTC
**Godot version:**
3.2.1.stable

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
I have an instanced object moving to the right with 2 raycasts attached as children. One pointing left and one pointing down. They are both enabled and set to detect Areas. As it moves right, it places a "tail_segment" (think of the game snake) in its previous location with an Area2D attached. There are other instances of this object that are spawned in front of the primary object and move upwards. They have the same action of placing "tail segments" behind them as they move. After about 15-20 seconds, the raycast that is pointing left on the primary object will start missing the segments i am placing. The first object hit by the raycast that is a tail of the primary should turn green. It slowly gets worse the longer the project is run. 

**Steps to reproduce:**
Run the project and watch the raycast detect objects to the left of the primary object. The problem does not occur if no objects are spawned over time by setting can_spawn = false in Environment.gd. Pressing Enter can toggle spawning while project is running

**Minimal reproduction project:**
[raycast_issue.zip](https://github.com/godotengine/godot/files/4459671/raycast_issue.zip)

**Comment by bojidar-bg** [comment] 2020-04-10 06:56
I ran the attached project, but I'm not sure what I should be looking at in it. It looks the same to me, no matter how long I run it:

![image](https://user-images.githubusercontent.com/5276727/78970247-8f79b500-7b11-11ea-8bc9-b22a7168dcb4.png)

**Comment by whitelion351** [comment] 2020-04-10 08:41
Hi, thanks for looking. The green block on the red line should stay a constant distance from the right most side which is the raycasts are coming from. when I run it as stated above the green block starts to move erractically. (It's not really moving but the blocks further back are being detected instead of the newly spawned blocks). I hope I am making sense

**Comment by whitelion351** [comment] 2020-04-10 19:25
I ran the project on my Linux machine and while the problem is still there, it does not seem nearly as bad. I think i have discovered though, that is has something to do with adding exceptions to the raycast in gdscript. If the raycast hits an object that was not created by its parent, (In this project case, if it hits a blue block instead of a red one) it will add an exception and do a force_raycast_update. I have confirmed that it is not adding any red blocks to the exceptions list.
However, if I remove the code for adding exceptions then it works as expected, albeit it starts detecting the blue blocks as well.

**Comment by whitelion351** [comment] 2020-04-11 07:05
It is definitely raycast exceptions. I have made a much simpler project demonstration the issue I am having. Behold:
[raycast_exceptions_issue.zip](https://github.com/godotengine/godot/files/4464168/raycast_exceptions_issue.zip)

![raycast_exceptions_issue_win10](https://user-images.githubusercontent.com/56313776/79037576-4401ee00-7b87-11ea-9688-4fd66b1e8df3.gif)

The top line is being drawn and added to the bottom line's raycast exceptions. The bottom line does the same as it did before; raycasts to the left, the block it hits changes color to green and then it moves to the right. The green block should always appear to be 2 blocks away from the right most block. 
But this does not happen. The raycast starts missing blocks as if they are in it's exceptions.

**Comment by whitelion351** [comment] 2020-04-11 09:15
I found that if i clear the raycast exceptions and do a force_raycast_update at the beginning of _physics_process, then i get the expected behaviour. Is there a limit or some quantity of exceptions that would cause a raycast to behave as depicted above? I will wait to hear from someone before I close this issue in case it actually is an issue that needs correcting.
BTW I love godot. Keep up the good work guys!

**Comment by madmiraal** [comment] 2020-12-01 13:49
The problem is the `StaticBody2D`s that are added to the `RayCast2D` exceptions are being freed, but not removed from the `RayCast2D` exceptions. The memory of the freed `StaticBody2D` is being reallocated to new `StaticBody2D`s, which are considered to already be members of the `RayCast2D` exceptions. This is why clearing the `RayCast2D` exceptions at the beginning of `_physics_process` solves the problem. Alternatively, they can be removed from the `RayCast2D` exceptions before being freed.

**Comment by madmiraal** [comment] 2020-12-01 15:41
Closing as fixed on master with 4f163972bbd9c. This ensures that RIDs are compared using their ID not the pointer to the underlying data, which can be reallocated when freed.

**Closed by madmiraal** 2020-12-01 15:41 UTC
Labels: bug, topic:physics

**Comment by whitelion351** [comment] 2020-12-03 19:12
That is a very good explanation. Thankyou for looking into it.
