### ISSUE TITLE
2D Sprite "jittering", very noticeable when using camera smoothing

### ISSUE THREAD

**Issue by forbjok** [godotengine/godot#35606] opened 2020-01-27 00:54 UTC
**Godot version:**
3.1.2 stable, GitHub master (3.2), Vulkan branch (4.0)

**OS/device including version:**
Windows 10 x64 v1909

**Issue description:**
Pretty much as soon as I made my test level larger than a single screen, I noticed something was off. After a bit of testing, I've found out what it is. It seems like any time the camera moves, there is some sort of inconsistency in the positions sprites are being rendered at, causing them to "jitter" back and forth by one pixel even though the camera is only moving in one direction.

Example gifs showing the issue:
![A5aCVeO](https://user-images.githubusercontent.com/4687674/73144517-c447a580-40a6-11ea-8bf2-8c0b32d006d3.gif)
![EhPwu5N](https://user-images.githubusercontent.com/4687674/73144521-cb6eb380-40a6-11ea-81e5-e41ef9bde8b5.gif)

How noticeable it is depends on circumstances. Generally, from what I've found, it's most noticeable if you have camera smoothing turned on and the smoothing speed set to a very low value, but the problem isn't related to the camera smoothing. It's also present with camera smoothing turned off, just harder to notice.

In case it was a bug that had already been fixed, I tried compiling Godot myself from both the master (presumably what will become 3.2) and vulkan (4.0?) branches to try them out, but unfortunately the problem still seems to be present in both of those. It looks a bit different in the Vulkan branch, due to what I assume is some sort of smoothing/blur filter being applied (there may be a way to turn that off, but I couldn't find it) to the background, but it is definitely still there.

**Steps to reproduce:**

1. Start minimal reproduction project
2. Run far enough to the right that the camera starts scrolling and stop.
3. Watch the vertical lines of the background brick wall or the ground near the player to see the sprite jittering back and forth by one pixel until the camera fully stops

**Minimal reproduction project:**
[godot-jitter-repro-project.zip](https://github.com/godotengine/godot/files/4115122/godot-jitter-repro-project.zip)

**Comment by Seel** [comment] 2020-01-27 05:18
Seems to me like the camera itself isn't respecting the pixel snap setting.

**Comment by forbjok** [comment] 2020-01-27 06:37
The issue happens regardless of whether Pixel Snap is enabled or not.
If the issue was caused by the camera, shouldn't everything be jittering?
As far as I can tell, it's only the sprites that jitter. The background tilemap and text label does not.

**Comment by Seel** [comment] 2020-01-27 06:49
> 
> 
> The issue happens regardless of whether Pixel Snap is enabled or not.
> If the issue was caused by the camera, shouldn't everything be jittering?
> As far as I can tell, it's only the sprites that jitter. The background tilemap and text label does not.

The tilemap is one cohesive unit so it does jitter, but individual tiles within might not. I tried this right now with multiple tilemap layers, background and foreground, and that way you can really see them jitter too.

Since pixel snap doesn't seem to affect the camera, it's position.x can be something like 10.375940 and relative to this position one object that's pixel snapped might get it's position rounded up to the nearest pixel, while another one's gets rounded down.

At least that's my interpretation of what's happening.

**Comment by forbjok** [comment] 2020-01-27 07:29
> The tilemap is one cohesive unit so it does jitter, but individual tiles within might not.

I tried looking at the edge of the screen during scrolling, and I was not able to spot any jittering on the background itself relative to the edge. Shouldn't it be possible to see it jitter if comparing it to the edge?

In my example project the background and foreground actually are two separate tilemaps (although they use the same tileset), and I've never been able to spot any jittering between them.

Maybe pixel snap works differently than I thought, but I would have thought that if this was caused by pixel snapping, it would stop happening when Pixel Snap was turned off?

**Comment by Seel** [comment] 2020-01-27 08:01
Not saying pixel snap is the cause, rather it doesn't really do anything.

[pixeltest-isodemo.zip](https://github.com/godotengine/godot/files/4115986/pixeltest-isodemo.zip)

I messed with the 2D isometric demo a bit, you can really see the jitter between walls and pillars and the floor tiles in this.

**Comment by forbjok** [comment] 2020-01-27 08:16
Ah, yes. There's definitely some jittering going on there. I wonder why I'm only seeing it with the sprites in my game.

**Comment by lawnjelly** [comment] 2020-01-27 10:52
I've not done any 2D stuff with Godot but it looks like the problem is something like this : your character sprite position is not snapped relative to your background.

i.e. if snapping is every 1.0 in units, and your background is at position 4.0, and your sprite is at 6.7:

### At camera position 2.0
_(assuming we are using a floor function to snap, but same will happen with round)_
background = 4.0 - 2.0 = 2.0 = 2
sprite = 6.7 - 2.0 = 4.7 = 4

### at camera position 1.6
background = 4.0 - 1.6 = 2.4 = 2
sprite = 6.7 - 1.6 = 5.1 = 5

Thus as the camera moves you are getting relative movement between the two by 1 pixel. The solution is to snap the background and the sprite positions relative to each other.

**Comment by Seel** [comment] 2020-01-27 11:43
> 
> 
> Thus as the camera moves you are getting relative movement between the two by 1 pixel. The solution is to snap the background and the sprite positions relative to each other.

Pixel snap should be handling this, shouldn't it?
And it does, if you have an integer camera position, but since the camera is not snapped you get unpredictable results.

If for example you put this in the camera's _process function:
position = player.position.round()
force_update_scroll()
Everything works and there's no jitter with this, but you cannot use the camera node's smoothing function.

**Comment by forbjok** [comment] 2020-01-27 11:45
I tried manually .floor()-ing the positions of the camera and sprite in various gdscript handlers yesterday, and so far I haven't found anything that actually fixes the jitter. Maybe I could try implementing a custom camera that just sets the underlying render position directly (pretty sure I saw some way to do that somewhere, but I forget what it's called) and .floor()s it. Will definitely try that later.

If that fixes it, this kinda seems like something that should just be done automatically by default. I can't think of any reason you'd ever actually want objects arbitrarily jittering relative to each other during scrolling.

**Comment by Seel** [comment] 2020-01-27 11:57
> 
> 
> I tried manually .floor()-ing the positions of the camera and sprite in various gdscript handlers yesterday, and so far I haven't found anything that actually fixes the jitter.

Did you try without camera smoothing enabled? That should work, otherwise the smoothing happens after your script and turns the camera position into a float again.

my scene tree is ordered like this:
player
    sprite
    collision shape etc.
camera

This way the camera gets the player position after the player moved.
`onready var player = get_node("../Player")

func _process(delta):
	position = player.position.round()
	force_update_scroll()`

This should work.

**Comment by lawnjelly** [comment] 2020-01-27 12:16
Ok I downloaded your demo project and got it working:

1) In your player scene, create a new Node2D and call it Player
2) Make this new Node2D the scene root (so that the kinematic thing is a child of it)
3) Move the Sprite to be a child of this root node.
4) Change the
```
onready var sprite: = get_node("Sprite")
```
to
```
onready var sprite: = get_node("../Sprite")
```
5) In _physics_process at the end add:
```
	sprite.position = Vector2(floor(position.x), floor(position.y))
```

Obviously you'll want to tweak it a bit but the general idea is this .. to separate the physics representation (kinematic) from the visual representation. The physics rep can have float coordinates, but the visual representation should be floored or rounded to whole numbers.

With this working, there will always be an integer relative relationship between the background and the sprites, and you won't get this jitter.

**Comment by forbjok** [comment] 2020-01-27 12:24
> Did you try without camera smoothing enabled?

I don't remember if I tried rounding the camera position with smoothing turned off, but the jitter is present without smoothing. It's just more noticeable when smoothing is enabled.

> This should work.

I'll try that when I have the opportunity, although I'll probably still have to either implement a custom camera or just implement custom smoothing on the existing one.


> Ok I downloaded your demo project and got it working:
> 
> 1. In your player scene, create a new Node2D and call it Player
> 2. Make this new Node2D the scene root (so that the kinematic thing is a child of it)
> 3. Move the Sprite to be a child of this root node.
> 4. Change the
> 
> ```
> onready var sprite: = get_node("Sprite")
> ```
> 
> to
> 
> ```
> onready var sprite: = get_node("../Sprite")
> ```
> 
> 1. In _physics_process at the end add:
> 
> ```
> 	sprite.position = Vector2(floor(position.x), floor(position.y))
> ```
> 
> Obviously you'll want to tweak it a bit but the general idea is this .. to separate the physics representation (kinematic) from the visual representation. The physics rep can have float coordinates, but the visual representation should be floored or rounded to whole numbers.
> 
> With this working, there will always be an integer relative relationship between the background and the sprites, and you won't get this jitter.

I'll try this as well when I have the opportunity, but wouldn't rounding the position set to the viewport's canvas_transform (I believe this is what Camera2D sets internally?) also fix the issue?

**Comment by lawnjelly** [comment] 2020-01-27 12:45
> I'll try this as well when I have the opportunity, but wouldn't rounding the position set to the viewport's canvas_transform (I believe this is what Camera2D sets internally?) also fix the issue?

I'm not sure exactly what you mean, but it may be possible to achieve the same math effect via a slightly different mechanism (again, I am not familiar with 2D). But once you have a moving camera, snapping positions to pixels on the screen no longer works because you will get this jiggling, you need to snap relative to the SCENE.

**Comment by golddotasksquestions** [comment] 2020-01-27 17:36
I don't use Camera smoothing with pixelart for that reason. Which is a shame, because if it wasn't for this issue, there would be no reason not to use smoothing.

**Comment by forbjok** [comment] 2020-01-27 18:13
> > I tried manually .floor()-ing the positions of the camera and sprite in various gdscript handlers yesterday, and so far I haven't found anything that actually fixes the jitter.
> 
> Did you try without camera smoothing enabled? Otherwise the smoothing happens after your script and turns the camera position into a float again.
> 
> my scene tree is ordered like this:
> 
> ```
> player
>     sprite
>     collision shape etc.
> camera
> ```
> 
> This way the camera gets the player position after the player moved.
> 
> ```
> onready var player = get_node("../Player")
> 
> func _process(delta):
> 	position = player.position.round()
> 	force_update_scroll()
> ```
> 
> This should work.

I can confirm that this fixes the jitter, although it makes the built-in smoothing unusable, so I'll have to reimplement that manually.



> Ok I downloaded your demo project and got it working:
> 
> 1. In your player scene, create a new Node2D and call it Player
> 2. Make this new Node2D the scene root (so that the kinematic thing is a child of it)
> 3. Move the Sprite to be a child of this root node.
> 4. Change the
> 
> ```
> onready var sprite: = get_node("Sprite")
> ```
> 
> to
> 
> ```
> onready var sprite: = get_node("../Sprite")
> ```
> 
> 1. In _physics_process at the end add:
> 
> ```
> 	sprite.position = Vector2(floor(position.x), floor(position.y))
> ```
> 
> Obviously you'll want to tweak it a bit but the general idea is this .. to separate the physics representation (kinematic) from the visual representation. The physics rep can have float coordinates, but the visual representation should be floored or rounded to whole numbers.
> 
> With this working, there will always be an integer relative relationship between the background and the sprites, and you won't get this jitter.

This does fix the jitter for the player, but would have to be implemented separately for every sprite, making it rather impractical.


Ultimately, this is the solution (or workaround) I arrived at:
```
extends Camera2D

# Smoothing duration in seconds
const SMOOTHING_DURATION: = 0.2

# The node to follow
var target: Node2D = null

# Current position of the camera
var current_position: Vector2

# Position the camera is moving towards
var destination_position: Vector2

func _ready() -> void:
	current_position = position

func _process(delta: float) -> void:
	destination_position = target.position
	current_position += Vector2(destination_position.x - current_position.x, destination_position.y - current_position.y) / SMOOTHING_DURATION * delta
	
	position = current_position.round()
	force_update_scroll()
```

It's a combination of Seel's suggestion with a custom reimplementation of camera smoothing based on one I created in a MonoGame-based engine years ago. This completely fixes the issue for all sprites without having to do anything specific in each sprite, while still having a nice smooth camera.

This still seems like something Camera2D should be doing internally by default though, as I can't imagine the current behavior ever being desirable.

**Comment by Calinou** [comment] 2020-01-27 19:11
It seems Camera2D currently doesn't have specific code to handle the **Use Pixel Snap** project setting. It makes sense to also snap the camera's coordinates when that setting is enabled.

**Comment by lawnjelly** [comment] 2020-01-27 19:44
Agree, the simple camera snapping may be good enough in this case :+1:. The snapping per sprite works with the more general case, because it allows things like variable size pixel blocks (e.g. 1 sprite pixel is 4x4 on screen), and zooming, non-snapped camera etc. But it may be overkill in this situation, and could of course be custom implemented in a game that needed this.

**Comment by forbjok** [comment] 2020-01-27 20:28
I made a pull request that rounds the Camera2D origin to nearest pixel before setting the canvas transform. This fixes the jittering without any special camera script.

Not sure if it's implemented in the most idiomatic way possible, but it seems to work at least.

**Comment by fossegutten** [comment] 2020-01-28 19:55
Great addition! Had amworkaround script for this. Please add for 3.2 👍

**Comment by fossegutten** [comment] 2020-01-28 21:46
The reason that smoothing and custom camera scripts seem to increase jitter is because camera parent node will always be aligned to camera perfectly, if smoothing is disabled. Camera parent is usually player node, so player and bacground will draw fine. Other nodes with non-rounded positions will still jitter. If pixel snap in editor is used, you will only see jitter for moving sprites.

@forbjok commit fixes the issue for all cases. Very clever indeed! I was using a gdscript workaround hack for this.

**Comment by Tuatarian** [comment] 2020-07-18 07:42
One fix for this that worked for me, when pixel snap and such did not, was setting the Camera's update mode in the inspector from Idle to Physics. Completely removed the jitter

**Comment by fossegutten** [comment] 2020-08-01 16:33
I figured out a way to fix the jitter completely from gdscript, by coding a custom camera.
Using physics mode or pixel 2D snap is not necessary at all.

I do this as a final step on my camera transform:

`t.origin = t.origin.snapped(Vector2.ONE * global_scale)`

To port this to the default camera, the position should be Snapped by the zoom value, instead of Vector2(1.0, 1.0)! Simple as that.

**Comment by nihiluis** [comment] 2020-08-05 15:59
is this the same bug?

https://godotengine.org/qa/78937/remove-render-jitter-artifacts-from-moving-camera

The strategies laid out in this issue didn't work for me.

**Comment by m6502** [comment] 2020-08-25 08:30
@forbjok  I may have a present for you.

![GIF 25-Aug-20 10-29-01](https://user-images.githubusercontent.com/1667712/91151383-e0073e80-e6bd-11ea-937b-5e818f226309.gif)

**Comment by ujjawal49** [comment] 2020-08-25 10:43
@m6502 please help me too I'm also facing this issue. In my case I'm not even moving the camera. Only Sprites are moving using this code.
```
public float speed = 2f;

void Update () 
{
transform.position += Vector2.left * speed * Time.deltaTime;
}
```
Please help!😣

**Comment by m6502** [comment] 2020-08-25 10:47
@ujjawal49 do you have a small test project I could try?

**Comment by ujjawal49** [comment] 2020-08-25 10:50
@m6502 sure let me make the on a small scale and I'll give you the link for it.

**Comment by ujjawal49** [comment] 2020-08-25 11:33
@m6502 ok so here is the project :- https://drive.google.com/file/d/1DxWb-xBdVp1gf_G-HO70-Cz_HP7rk-r_/view?usp=drivesdk

In the project while playing, look at the pipes closely while the come towards the left. It looks so bad.

If you want to check how bad it feels while playing the APK it's here (ignore all the buttons, just click on start, other buttons are for my test purposes):- https://drive.google.com/file/d/1qe11Q3pib52yrS7LUdACTYMY1dilbmaw/view?usp=drivesdk

Thanks.

**Comment by m6502** [comment] 2020-08-25 11:55
@ujjawal49 there's a small problem with your project, in that it's an Unity 3D project. Am I missing something? 😅

**Comment by ujjawal49** [comment] 2020-08-25 11:59
@m6502 it's a .rar file and inside it's a unity project. I don't think you are missing something, what's the issue?

**Comment by ujjawal49** [comment] 2020-08-25 12:02
@m6502 oh yes I didn't saw that it's a godot forum.

**Comment by m6502** [comment] 2020-08-25 12:08
(Insert joke about upgrading from Unity to Godot here) :stuck_out_tongue_winking_eye:

**Comment by ujjawal49** [comment] 2020-08-25 12:12
@m6502 no, I believe I'll be able to fix this issue within 5-6 thousand years so no chance of upgrading from unity to godot.😂😣

**Comment by m6502** [comment] 2020-08-26 09:34
Made the pull requests to fix this :-)

**Comment by Zireael07** [comment] 2020-08-26 10:13
You're trying to PR to your own fork's master, not Godot's master branch.

**Comment by m6502** [comment] 2020-08-26 10:32
Fantastic!

**Comment by golddotasksquestions** [comment] 2020-08-26 14:51
Is it possible to get those fixes cherrypicked for the 3.X branch?

**Comment by Zireael07** [comment] 2020-08-26 15:09
One of the PRs is made for 3.2 branch

**Comment by m6502** [comment] 2020-08-26 15:51
@golddotasksquestions Yes, I created two pull requests for 3.x and 4.x. Hopefully it'll be there for the 3.2.3 release. I'll be on 3.x for a while :-)

**Comment by Calinou** [comment] 2020-08-26 16:21
> Hopefully it'll be there for the 3.2.3 release

The 3.2.3 release is imminent, so I'm afraid it can only be merged for 3.2.4.

**Comment by SyliawDeV** [comment] 2020-10-23 13:09
> @golddotasksquestions Yes, I created two pull requests, for 3.x and 4.x. Hopefully it'll be there for the 3.2.3 release. I'll be on 3.x for a while :-)



> @forbjok I may have a present for you.
> 
> ![GIF 25-Aug-20 10-29-01](https://user-images.githubusercontent.com/1667712/91151383-e0073e80-e6bd-11ea-937b-5e818f226309.gif)

Hi, how you fix that problem I have the same when player stop it jitting, I dont know how to fix it at this time. v3.2.3

**Comment by m6502** [comment] 2020-10-23 13:11
@SyliawDeV  It'll be corrected when you download the next Godot version including the pull request that fixes the bug :-)

**Comment by SyliawDeV** [comment] 2020-10-24 04:24
> @SyliawDeV It'll be corrected when you download the next Godot version including the pull request that fixes the bug :-)

oh maybe v3.2.4 stable, I check beta version everyday but not seem it fix or not. But hear u say that I can wait for new version. :)

**Comment by Calinou** [comment] 2020-10-24 11:26
@SyliawDeV This pull request hasn't been merged yet, so it won't be in 3.2.4 if it's not merged by the time 3.2.4 is released.

**Comment by SyliawDeV** [comment] 2020-10-24 11:30
> @SyliawDeV https://github.com/godotengine/godot/pull/41535 hasn't been merged yet, so it won't be in 3.2.4 if it's not merged by the time 3.2.4 is released.

Hm, dont know how other people do with that.
Until I know that I will sleep in freeze.

**Comment by m6502** [comment] 2020-10-24 13:28
@Calinou @SyliawDeV I'll try to add the required project setting and test it this weekend so it can be merged in the next revision.

**Comment by SyliawDeV** [comment] 2020-10-24 13:34
> @Calinou @SyliawDeV I'll try to add the required project setting and test it this weekend so it can be merged in the next revision. 

You just warm me from freeze. 🤩

**Comment by akien-mga** [comment] 2020-11-16 17:25
Fixed by #43194 (4.0) and #43554 (3.2.4).

**Closed by akien-mga** 2020-11-16 17:25 UTC
Labels: bug, confirmed, topic:rendering

**Comment by Medved1991** [comment] 2021-12-30 06:45
Many users have problems with camera2D lag in Godot. I spent a lot of time on project settings. Used all camera setup options. Tried to fix the delays with code. It was all unsuccessful. Godot has long had problems with this, and they are not corrected. The only thought I came up with was to use Unity. It's a pity, but until this problem is solved, it makes no sense to use the Godot engine.

**Comment by m6502** [comment] 2021-12-30 08:16
@Grizzly-pride Before my fix was pulled there was one 3.x version released including it. You could always give it a try to see if that would fix your problems; it certainly did for me. 

I'm willing to give this a try again at some point because it's a deal-breaker for too many people, myself included. I've already seen people remake projects in Unity because the customers didn't like the objects and the maps not being in sync, and that's a pity because if someone spends time to learn Godot and has to switch to Unity it's going to be difficult to convince them to take the step back because of fear of having to spend the time again for nothing. This is by far the worst issue Godot has.

**Comment by Calinou** [comment] 2021-12-30 17:10
An alternative solution for now is to avoid relying on Camera2D smoothing (or only use it to a minimal amount). The kind of smoothing Camera2D performs (asymptotic smoothing) is not something that was used in 90s pixel art games anyway :slightly_smiling_face:

**Comment by superlazyname** [comment] 2022-06-27 18:38
I think I ran into this in v3.4.4 on Linux. The Pixel Snap setting seemed to fix it but I don't completely understand what causes this and I'd like a bit more information if anyone can provide it.

Strangely enough it only happened with very specific sprites. I tried all of the following:
- Moving the sprite up and down in the tree hierarchy
- Moving the sprite around in the scene
- Putting another sprite in the same spot where the jittering one was (it did not jitter)

It does not seem to be relat4ed to the order that sprites are added to the scene, or any pattern I was able to find.

**Comment by golddotasksquestions** [comment] 2022-06-27 18:47
> Strangely enough it only happened with very specific sprites. 

Maybe try comparing Sprites with odd and even number of texture side length. If that's the cause, try disabling the "centered" property of the Sprite.

**Comment by SteveDunning** [comment] 2023-12-04 17:42
How are people solving this issue in 4.1.3? It seems also that 'pixel snap' as mentioned above has been removed from the project settings.

**Comment by zhengxiaoyao0716** [comment] 2024-03-08 10:35
I found this problem still exist at the v4.2.1.stable version.


https://github.com/godotengine/godot/assets/12682063/5d73763f-0809-4f48-ba9d-20160f7e4cbd

[test_project.zip](https://github.com/godotengine/godot/files/14536997/test_project.zip)

**Comment by Calinou** [comment] 2024-04-16 01:07
> I found this problem still exist at the v4.2.1.stable version.

For future reference, this occurs because the project isn't using physics interpolation. This means the player sprite is moving at a different frequency than the screen is being rendered at, which will cause visible jitter. To resolve this, you need physics interpolation. 2D physics interpolation will be available in 4.3: https://github.com/godotengine/godot/pull/88424

Until 4.3 is released, you can use https://github.com/lawnjelly/smoothing-addon (also for 3D).

**Comment by Jaso333** [comment] 2024-05-01 21:43
> > I found this problem still exist at the v4.2.1.stable version.
> 
> For future reference, this occurs because the project isn't using physics interpolation. This means the player sprite is moving at a different frequency than the screen is being rendered at, which will cause visible jitter. To resolve this, you need physics interpolation. 2D physics interpolation will be available in 4.3: #88424
> 
> Until 4.3 is released, you can use https://github.com/lawnjelly/smoothing-addon (also for 3D).
> 
> Regarding the original issue, this was improved a lot in 4.3 too: #87297

I'm using a custom build with Physics Interpolation available. I have it switched on, and it is still jittering exactly as it is described in the opening post.

**Comment by Calinou** [comment] 2024-05-06 20:34
> I'm using a custom build with Physics Interpolation available. I have it switched on, and it is still jittering exactly as it is described in the opening post.

Please open a new issue with a minimal reproduction project attached. Also, make sure the stretch scale mode is set to `integer`: https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#stretch-scale-mode

**Comment by Lisunxing** [comment] 2025-06-27 04:45
> > 我正在使用具有 Physics Interpolation （物理插值） 的自定义版本。我打开了它，但它仍然像开篇文章中描述的那样抖动。
> 
> 请打开一期新刊，并附上最小复制项目。此外，请确保将 stretch scale mode 设置为 ： https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#stretch-scale-mode`integer`

The problem still persists in version 4.4.1.stable, which I am currently using. It has been troubling me for a long time, and I've tried many approaches, but none of them worked.

https://github.com/user-attachments/assets/7979fabf-32f8-4de3-8dc9-9e09a0d300fb

**Comment by Lisunxing** [comment] 2025-06-27 05:42
> > I'm using a custom build with Physics Interpolation available. I have it switched on, and it is still jittering exactly as it is described in the opening post.
> 
> Please open a new issue with a minimal reproduction project attached. Also, make sure the stretch scale mode is set to `integer`: https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#stretch-scale-mode

I think I've found the issue. I've fixed the shaking in my game by rounding the coordinates to integers using round() when my character stops moving. After doing this, the camera's movement became completely smooth without any shaking. The tile map never had any shaking — it was always just the character that was shaking.
