### ISSUE TITLE
static func overriding works not expected

### ISSUE THREAD

**Issue by iRumba** [godotengine/godot#82476] opened 2023-09-28 08:21 UTC
### Godot version

4.1.1.stable

### System information

Windows 10, GLES2, Intel(R) UHD Graphics 630

### Issue description

I have classes
```
extends Object

class_name A 

static func print():
    print(get_message())

static func get_message():
    return "A"
```
and
```
extends A

class_name B

static func get_message():
    return "B"
```

So, when I evaluate code `var m = B.GetMessage()` I have "B" in variable m

But if I evaluate `B.print()` I see "A" in console. 

### Steps to reproduce

Nothing

### Minimal reproduction project

Nothing

**Comment by dalexeev** [comment] 2023-09-28 10:54
Duplicate of:

* #72973
* #77895

Thanks for the contribution nonetheless!

**Closed by dalexeev** 2023-09-28 10:54 UTC
Labels: bug, topic:gdscript
