### ISSUE TITLE
Alpha 17 and Beta1 immediate crash on startup

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#66059] opened 2022-09-18 17:32 UTC
### Godot version

Godot 4 Alpha 17, Beta1

### System information

Win 64, Nvidea 765M

### Issue description

Alpha 16 works and starts up normally like previous Alpha versions, but both Alpha 17 and Beta1 immediately show white window and crash.

When running from the command line or in verbose mode I get this:

Alpha 17:

> Godot Engine v4.0.alpha17.official.22a09fef5 - https://godotengine.org
> WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
>         ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
>         Objects - 1
>                 Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 98471040
>      at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:168)

Beta1:

> Godot Engine v4.0.beta1.official.20d667284 - https://godotengine.org
> WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
>         ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
>         Objects - 1
>                 Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 158027072
>      at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:168)

not sure how relevant this is though, since when I run Alpha 16 in verbose mode I also get a similar warning:

> ...
> WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
>         ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
>         Objects - 1
>                 Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 108508144
>      at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:168)
> ...

Unfortunately the above warning is all I get in console printout when I try to run Alpha 17 or Beta1. :/

### Steps to reproduce

Double click the executable

**Comment by clayjohn** [comment] 2022-09-19 16:18
I have a feeling your GPU doesn't support Vulkan. There have been other reports of [similar GPUs crashing instead of displaying the proper error message](https://github.com/godotengine/godot/issues/58927#issuecomment-1194688350)

To confirm my theory can you download the Vulkan SDK and attempt to run the sample project? https://vulkan.lunarg.com/sdk/home

**Comment by Zireael07** [comment] 2022-09-19 17:28
@clayjohn note that alpha 16 works, though

**Comment by clayjohn** [comment] 2022-09-19 17:35
> @clayjohn note that alpha 16 works, though

Oof. Thanks for pointing that out! I missed that part somehow. 

This Issue looks suspiciously similar to https://github.com/godotengine/godot/issues/61218 (although in that case though the user is on linux). It sounds like we aren't doing a good enough validation of supported features so indeed this is distinct from https://github.com/godotengine/godot/issues/58927 (which applies to devices with no Vulkan support)

**Comment by golddotasksquestions** [comment] 2022-09-19 17:54
Yes, Alpha 16 and all previous Alphas work fine without crash on start up. There have been some occasional crashes while I was using the Alphas, but that was pretty rarely. Nothing out of the ordinary for an Alpha build. 

During Pre-Alpha phase I had issues with instant crash on startup (https://github.com/godotengine/godot/issues/49656), but not during the Alpha phase.

**Comment by clayjohn** [comment] 2022-09-19 18:05
I looked through the commits between Alpha 16 and Alpha 17 and nothing stood out as being the obvious culprit (I didn't see anything related to Vulkan configuration or initialization). This indicates it may be something else. 

@golddotasksquestions Do you have any ability to compile the engine from source so you can bisect the changes and figure out which PR introduced the issue?

**Comment by golddotasksquestions** [comment] 2022-09-19 18:06
@clayjohn 

> Do you have any ability to compile the engine from source so you can bisect the changes and figure out which PR introduced the issue?

I have never done that and would not know how tbh.

**Comment by clayjohn** [comment] 2022-09-19 18:12
If you are interesting in trying/learning We have detailed instructions on how to bisect regressions in the docs [here](https://docs.godotengine.org/en/latest/community/contributing/bisecting_regressions.html)

We also have detailed instructions on downloading the source and compiling the engine from scratch https://docs.godotengine.org/en/latest/development/compiling/index.html

**Comment by akien-mga** [comment] 2022-09-20 14:47
Can you test a recent `master` build generated by our CI?
You can download the "windows-editor" artifact at the bottom of this page for example: https://github.com/godotengine/godot/actions/runs/3090635263

Just to rule out potential buildsystem issues as I have been changing some things around LTO and there was notably a regression in alpha 17 and beta 1 (since fixed). I don't think it's involved here but testing a CI build should help confirm it.

**Comment by golddotasksquestions** [comment] 2022-09-20 16:32
@akien-mga 

I downloaded and ran the editor artifact form this link you provided and it started without issues:
![image](https://user-images.githubusercontent.com/47016402/191314254-b857179b-bb31-4d46-ae22-24d34f2374e3.png)

**Comment by clayjohn** [comment] 2022-09-20 17:01
Great! Looks like this is already fixed in master

**Closed by clayjohn** 2022-09-20 17:01 UTC
Labels: bug, platform:windows, needs testing, crash, regression

**Comment by akien-mga** [comment] 2022-09-20 20:20
I'm not so sure, it may still be caused by specifics of the build options or toolchains used for official builds.
