### ISSUE TITLE
Can not select sprites with region and flip_H set to True.

### ISSUE THREAD

**Issue by AurumStein** [godotengine/godot#16535] opened 2018-02-10 12:18 UTC
**Godot version:**
v3.0.stable.official

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Can not select sprites with region and flip_H set to True.

**Steps to reproduce:**
Use spritesheet and set it to region and try using flip_h = true.
![STEPS](https://media.giphy.com/media/26hkhOHE236DosmwE/giphy.gif)

**Comment by groud** [comment] 2018-02-10 13:11
Closing as a duplicate of #16461

**Closed by groud** 2018-02-10 13:11 UTC
