### ISSUE TITLE
Tileset intermittently hangs or crashes godot when adding many collision layers

### ISSUE THREAD

**Issue by KevinFrazier** [godotengine/godot#87958] opened 2024-02-04 20:48 UTC
### Tested versions

4.2-stable

### System information

Apple M1 OS version: 14.3 (23D56)

### Issue description

After adding multiple collision layers to tiles, Godot eventually crashes or hangs

Special number I notice is about 20 in 1 tileset. Doesn't seem to be a particular tileset 

### Steps to reproduce

Open tileset, paint > physics layer. Add a bunch of collision layers in different methods:
- Click each tile
- Click, hold, and drag
- Eventually it either crashes or hangs

### Minimal reproduction project (MRP)

Sample scene and log
https://drive.google.com/drive/folders/1YuQTOgBl-6IIdq5UTFkNpzHIHzHrtCVA?usp=sharing

**Comment by AThousandShips** [comment] 2024-02-04 20:55
Are you talking about the editor?

This might be solved already, can you test with [4.2.2.rc1](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-1/)?

**Comment by KevinFrazier** [comment] 2024-02-04 20:56
will try and get back to you

**Comment by KevinFrazier** [comment] 2024-02-04 21:12
So upgrading to 4.2.2 issue fixed this above issue, but I came across another issue with undo and redo combinations when adding/ removing collisions. No log unfortunately and just hangs. Should I close this and open another?

**Comment by AThousandShips** [comment] 2024-02-04 21:25
That's separate, please open a separate (or two) bug reports for those, just to make it easier to track, and if you're able to see if there's any reports of those open already

Closing as a duplicate of:
* https://github.com/godotengine/godot/issues/86226

**Closed by AThousandShips** 2024-02-04 21:25 UTC
Labels: bug, crash, topic:2d
