### ISSUE TITLE
ERROR: read_response_body_chunk: HTTP Chunk too big

### ISSUE THREAD

**Issue by anzhi0708** [godotengine/godot#44272] opened 2020-12-10 17:41 UTC
**Godot version:** 
```
Godot_v3.2.3-stable_x11.64
```

**OS/device including version:** 
```
Type: Laptop System: Apple product: MacBookAir7,2 v: 1.0 
Intel HD Graphics 6000 vendor: Apple driver: i915
Kernel: 5.4.0-56-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal
```

**Issue description:**

When trying to install `PythonScript` by `touilleMan` with AssetLib,
```
ERROR: read_response_body_chunk: HTTP Chunk too big!! >16mb
   At: core/io/http_client.cpp:591.
```

**Steps to reproduce:**
Try and install `PythonScript` by `touilleMan` with AssetLib

**Comment by Calinou** [comment] 2020-12-10 19:19
Duplicate of https://github.com/godotengine/godot/issues/41882.

**Closed by Calinou** 2020-12-10 19:19 UTC
