### ISSUE TITLE
Color Picker Turns Game Window Black

### ISSUE THREAD

**Issue by joshchristiane** [godotengine/godot#77854] opened 2023-06-04 21:56 UTC
### Godot version

4.0.2 Stable

### System information

Windows 11, Vulkan Forward+, GTX 2070, AMD Ryzen

### Issue description

Very simple issue, whenever I use the "color picker" (only tested in 2D mode) the entire game viewport window turns black and the color picker thus becomes useless.

This must have something to do with my second display, because when I unplug that display everything works as expected. Not sure why this is happening but I know it's a bug.

For information sake I am using two displays, one is a UHD 4k display, and the secondary is a 1080p display.

### Steps to reproduce

1. Open any Godot project, new or otherwise.
2. Have a second display connected.
3. Try use colour picker in 2D/UI mode.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-06-04 22:03
I think this has been fixed in master in https://github.com/godotengine/godot/pull/74962#pullrequestreview-1434324222

Could you test Godot 4.1 dev 4 and see if the issue still occurs?

**Comment by KoBeWi** [comment] 2023-06-05 12:27
Duplicate of #74048

**Closed by KoBeWi** 2023-06-05 12:27 UTC
