### ISSUE TITLE
javascript access from godot not working

### ISSUE THREAD

**Issue by samtsejerome** [godotengine/godot#47444] opened 2021-03-28 19:03 UTC
**Godot version:**
3.2.3

**OS/device including version:**
macbook pro and macos 10.15.6

**Issue description:**
I tried out the functionality described in this page:
https://docs.godotengine.org/pt_BR/stable/getting_started/workflow/export/exporting_for_web.html#calling-javascript-from-script
exported the test project to html5 and uploaded to a server and loaded the project over http it ran ok, but the key feature under test  (js execution ) did nothing

**Steps to reproduce:**
1. create a project that uses JavaScript.eval to run javascript code (e.g an alert)
2. export the project to html5
3. upload  exported  project to web server
4.  open project in desktop browser (e.g. chrome)
expected outcome:
the javascript code executes.

actual outcome:
it doesn't - nothing happens.

example project to reproduce:

[data_persistance.zip](https://github.com/godotengine/godot/files/6217893/data_persistance.zip)

**Comment by Calinou** [comment] 2021-03-28 20:21
Can you see any error messages in the browser console while trying to evaluate JavaScript code from GDScript?

**Comment by samtsejerome** [comment] 2021-03-31 23:52
I didn’t check the console (just saw no alert )

Jerome Mayeux

**Comment by martinrudolf** [comment] 2021-04-02 02:57
Tried exporting of HTML5 code (Godot 3.2.3) not on macos, but on Windows 10.
But anyway:
the problem is most probably caused by the fact that in the example project, UI.TextEdit is two-liner (CR inserted, with 2nd line empty), so generated alert will not work in this situation. A text on only one line works well on the server for me...

**Comment by samtsejerome** [comment] 2021-04-04 19:03
thanks youre right that was the error not the eval implementation - my apologies!
though whilst it works for an alert eval has provided a dead end for themore useful task of persisting a high score ( it seems to disallow access to html5 localstorage e.g. Window.localStorage or Window.sessionStorage (perhaps  they are not available in a webassemply..? I don't know. )
Is that a separate defect or expected behaviour..?

Thx J.

**Comment by martinrudolf** [comment] 2021-04-08 21:45
You are welcome!
As for persisting data in HTML5: I successfully use the method open_encrypted_with_pass in my Godot HTML5 project. 
(Of course, I am not sure what is the reason of your problem you are dealing with...)

**Comment by Faless** [comment] 2022-02-12 02:59
Closing as this was an issue in the user code (causing invalid JS to be passed to `eval`).

I also suggest you have a look at the new [Godot <-> JS interface](https://godotengine.org/article/godot-web-progress-report-9) which is simpler to use and less error prone.

**Closed by Faless** 2022-02-12 02:59 UTC
Labels: bug, platform:html5, topic:porting, needs testing
