### ISSUE TITLE
Removed animation still used in Animated Sprite object. (set_animation: There is no animation with name 'New Anim'.)

### ISSUE THREAD

**Issue by luffah** [godotengine/godot#40263] opened 2020-07-10 16:46 UTC
(hello)

**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Ubuntu bionic (probably not related to device...)

**Steps to reproduce:**
The issue is related to the IDE.

I followed the tutorial  [Your first game](https://docs.godotengine.org/fr/stable/getting_started/step_by_step/your_first_game.html), while adding an animation, i added an extra one that i removed (trash icon in left panel "Animation :" of animated sprite) and got the error :
```
set_animation: There is no animation with name 'New Anim'.
```

(To workaround the issue i edited the scene file in Vim and guess the animation reference was wrong.)

At the moment i added the animation 'New Anim' (not nammed), it replaced the existing setting (in right pane : Animated Sprite > Animation  e.g. 'walking').
And when i removed the animation, the setting stay at 'New Anim'.

For a more coherent gui (given a dialog already exists), the setting (if used) shall be replaced by the next/previous existing one; or at least the setting shall be highlighted to see the error.

**Comment by btzr-io** [comment] 2020-09-18 07:25
I have the same issue on my project.
```
Godot Engine v3.2.3.stable.official
OpenGL ES 3.0 Renderer: GeForce GTX 1650/PCIe/SSE2
```

**Comment by EduardoCopat** [comment] 2021-04-02 19:40
Workaround: On the AnimatedSprite properties, changed Animation from `New Anim` to `default` again.

**Comment by KoBeWi** [comment] 2021-07-07 12:57
Duplicate of #28658

**Closed by KoBeWi** 2021-07-07 12:57 UTC
Labels: bug, topic:editor
