### ISSUE TITLE
Replacing for "" with "selected only" crashes the editor on certain circunstances

### ISSUE THREAD

**Issue by QuartzKnight** [godotengine/godot#39562] opened 2020-06-15 12:20 UTC
**Godot version:**
Godot v3.2.1 stable official

**OS/device including version:**
Windows 7 home premium service pack 1

**Issue description:**

When replacing "var " for "" on a block of selected code  the editor crashed

**Steps to reproduce:**
To reproduce, on a new script, write:
```
var a
var b
var c
```
Then, press ctrl+r, write "var " on the search box and let the replace box emprty, then check "selected only", select var a and b and press "

**Minimal reproduction project:**

[ReplaceBug.zip](https://github.com/godotengine/godot/files/4780145/ReplaceBug.zip)
The project just contains a script named "new_script.gd"

**Comment by akien-mga** [comment] 2020-06-15 12:48
Duplicate of #37416 (fixed in 3.2.2).

**Closed by akien-mga** 2020-06-15 12:48 UTC
Labels: bug, topic:editor
