### ISSUE TITLE
Autocomplete doesn't suggest properly when passing through a singleton global variable

### ISSUE THREAD

**Issue by thethunderingmarmot** [godotengine/godot#75212] opened 2023-03-22 08:20 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11

### Issue description

I have an autoload singleton with some children and its script has some onready vars that reference them so that I can do "singleton.child". The problem is that when I write methods in a child script, even if the onready vars in the singleton are statically typed, if I access them from outside the singleton using its global variable, autocomplete won't suggest them, but will only suggest the child's base class methods. Though, if inside the singleton I access those same onready variables without passing through the singleton global variable, autocomplete works as expected.

### Steps to reproduce

1) Create a scene with Node as a parent
2) Add a Node as a child of the previous Node
3) Attach a script to the parent Node and declare an onready var that references its child like so `@onready var child := $childNode as ChildNodeType`
4) Attach a script to the child Node and declare a random function like so `func random_function(): pass`
5) Set the whole scene as an autoload singleton with the global variable turned on
6) Create another scene to set as main scene
7) Attach a script to the parent node of that scene and in its _ready function try to access the random_function we declared before passing through the singleton global variable
8) You will now notice how `singleton.child.random_function()` doesn't get autocompleted, but works anyway

### Minimal reproduction project

[SingletonAutocompleteTest.zip](https://github.com/godotengine/godot/files/11037707/SingletonAutocompleteTest.zip)

**Comment by Calinou** [comment] 2023-04-01 17:03
- Duplicate of https://github.com/godotengine/godot/issues/71296.

**Closed by Calinou** 2023-04-01 17:03 UTC
Labels: bug, topic:gdscript, topic:editor, usability
