### ISSUE TITLE
Editor crashes when "Particles Animation" is enabled

### ISSUE THREAD

**Issue by th1z** [godotengine/godot#43589] opened 2020-11-16 10:20 UTC
**Godot version:**
v3.2.4.beta1.official

**OS/device including version:**
Nvidia, GLES3

**Issue description:**
Editor crashes without any error message when "Particles2D/Material/CanvasItemMaterial/Particles Animation" option is enabled.
The Editor also crashes when an existing "CanvasItemMaterial" with the option "Particles Animation" enabled is assigned to a "Particles2D" node

"CPUParticles2D" on the other hand seems to work fine.

**Steps to reproduce:**
Create a new project.
Create a "Particles2D" Scene
Create a "CanvasItemMaterial" for the Particles2D Scene
Enable "Particles Animation"
Editor crashes

**Comment by akien-mga** [comment] 2020-11-16 10:49
Duplicate of #42994, this is fixed in the latest `3.2` branch (will be fixed in 3.2.4 beta 2).

**Closed by akien-mga** 2020-11-16 10:49 UTC
Labels: bug, crash, topic:editor
