### ISSUE TITLE
Web Builds load very slowly on MacBook M1, not at all on iOS

### ISSUE THREAD

**Issue by cube-drone** [godotengine/godot#74131] opened 2023-02-28 23:48 UTC
### Godot version

4.0.rc6

### System information

Macbook Pro, M1, 2020

### Issue description

In a blank project with nothing but the Godot Icon, web builds load - well, _slowly_, but at least within the boundaries of sanity on Windows devices.

On my Macbook Pro M1, though, loading times - after the WASM is loaded into the browser - on Firefox and Chrome - take _so_ long that the project seems broken. It's not- though - Firefox will complain and ask to shut down the thread, but if you tell Firefox to hold its horses, and wait it out for about a minute, _eventually_ the project will load. 

On my iPhone, loading just spins forever. I understand that web builds aren't recommended on iOS, but it's worth noting, at least.

I'm wondering if this is maybe a weird interaction between the compiled WASM and the ARM architecture? Idk, I'm too much of a goober to know anything about assembly. 

### Steps to reproduce

This is trivial to reproduce: You can actually, I believe, see this with the Web Editor:

https://editor.godotengine.org/releases/4.0.rc6/godot.editor.html

( although it also works with any blank RC6 project, afaik ) 

I've also set up a very basic example with RC1: ( https://cardchapter.com/v2/main-2023-02-13T05%3A02%3A26.266Z/ ) that has similar behaviour: very very very slow boot-up, then it works fine. 

Load it up on a M1 Mac (I don't have an M2 or an Intel mac or I'd try it on those) and the editor takes upwards of a minute to load, _after_ the WASM is downloaded from the server. 

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-02-28 23:53
Duplicate of #70691

**Closed by akien-mga** 2023-02-28 23:53 UTC
