### ISSUE TITLE
GLES2 depth_draw_alpha_prepass rendering a shadow for transparent material

### ISSUE THREAD

**Issue by Tobi-La** [godotengine/godot#27207] opened 2019-03-18 15:21 UTC
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10

**Issue description:**
My project has meshes that are partially transparent. In GLES3 shadows are only drawn for the parts of the mesh that has alpha > 0, in GLES2 however this isn't working. GLES 2 always renders the full shadow.

To make it clear I compared a mesh which has set ALPHA to 0.0 in the fragment shader:

This is how it looks on GLES3:
![gles3](https://user-images.githubusercontent.com/25849067/54540900-199c2c00-4999-11e9-930b-b6ff00ab01d3.PNG)

And it looks like this on GLES2:
![gles2](https://user-images.githubusercontent.com/25849067/54540907-1c971c80-4999-11e9-944e-6c4e9ad274eb.PNG)

**Steps to reproduce:**
- Create a new 3D scene
- add a light source
- add two meshes, one which is casting a shadow and one which is receiving the shadow
- attach a custom shader to the casting object and set `ALPHA = 0.0;` in the fragment shader

**Minimal reproduction project:**

[AlphaShadow.zip](https://github.com/godotengine/godot/files/2978886/AlphaShadow.zip)

**Comment by kagonzalez** [comment] 2019-04-02 16:04
We have found some strange behavior to this bug, to begin with the issue only seems to be present on windows and linux in gles2 whereas with macs it exists in gles3 and not gles 2. Second, the issue seems to reside within visual_server_scene which seems to be an interface for the different GL versions, likely within `VisualServerScene::_update_dirty_instance()`

**Comment by kagonzalez** [comment] 2019-04-02 16:59
We realized that you could make the shadow not appear by change the Cast Shadow geometry property to Off. We don't think that shadow is determined by transparency in gles2.

**Comment by Tobi-La** [comment] 2019-05-03 07:10
You mean the shadow is not intended to be determined by transparency or is currently not determined? The cast shadow property wouldn't help me, because in my real project only a part of my mesh is transparent so I need the shadow not to be drawn only for those parts.

**Comment by clayjohn** [comment] 2019-06-23 06:10
Duplicate of https://github.com/godotengine/godot/issues/26568 all future discussions of this issue should take place there.

**Closed by clayjohn** 2019-06-23 06:10 UTC
Labels: bug, topic:rendering
