### ISSUE TITLE
Surfacetool generated mesh has lighting problem in final triangle

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#56026] opened 2021-12-17 17:11 UTC
### Godot version

3.4-stable

### System information

Windows10/Quest2(Android) and GLES2/GLES3

### Issue description

This problem shows up in my App where I have a sequence of points between which I draw thin rectangles so it looks like a series of line segments.

For some reason the lighting is calculated from the other side of the surface in a way that is not consistent with the triangles.  

The triangles are complete diagonals from one corner to the opposite corner of the rectangle.  

The lighting goes wrong in half of one of the triangles.

![image](https://user-images.githubusercontent.com/677254/146580515-90dbc343-122e-4cd0-b19c-e8181271452f.png)

In fact the problem always occurs in part of the final triangle that is added to the `SurfaceTool`.

![image](https://user-images.githubusercontent.com/677254/146580605-8759b62d-27cd-4737-a391-75276a2d1e48.png)

### Steps to reproduce

see below.  

When you run the minimal project it prints out the value of `SurfaceTool.commit_to_arrays()` to show that the normals are all correctly oriented:

> ARRAY_FORMAT_VERTEX: [(0, -0.2, 0), (2, -0.2, 0), (0, 0.2, 0), (0, 0.2, 0), (2, -0.2, 0), (2, 0.2, 0)]
> ARRAY_FORMAT_NORMAL: [(-0, -0, -1), (-0, -0, -1), (-0, -0, -1), (0, 0, -1), (0, 0, -1), (0, 0, -1)]

### Minimal reproduction project

[surfacetoolproblem.zip](https://github.com/godotengine/godot/files/7736605/surfacetoolproblem.zip)

**Comment by lawnjelly** [comment] 2021-12-17 17:58
Posting this issue just in case related, as that was to do with final triangles also: #52399

**Comment by clayjohn** [comment] 2021-12-17 18:06
Yes, looks like a duplicate of https://github.com/godotengine/godot/issues/52399 which was fixed by https://github.com/godotengine/godot/pull/54768 which will be in the upcoming 3.4.1 release.

@goatchurchprime Can you please try RC3 and let us know if the issue is fixed for you. You can download RC3 here: https://downloads.tuxfamily.org/godotengine/3.4.1/rc3/

**Comment by goatchurchprime** [comment] 2021-12-17 22:35
Yep, it's not there in 3.4.1/rc3

**Comment by akien-mga** [comment] 2021-12-17 22:41
Duplicate of #52399

**Closed by akien-mga** 2021-12-17 22:41 UTC
Labels: bug, topic:rendering, needs testing, topic:3d
