### ISSUE TITLE
Add properties to Tile definitions

### ISSUE THREAD

**Issue by nhydock** [godotengine/godot#14592] opened 2017-12-12 15:09 UTC
The current implementation of tiles for use in TileMapping is missing a few valuable features for RPGs and other tile based game types that can be found in RPG Maker and Tiled, a key one being the ability to add dynamic properties to tile definitions in your tileset.  Now that Dictionary support has been added to Godot 3's inspector, now would be a great time to add a properties dictionary to Tiles so because they can be configured and edited more easily.

Properties attached to tile types are incredibly useful for defining extra data that can be used, such as defining tile density for casting shadows in a roguelike, or saying if a terrain is mud or sand so your character will move slower in it, or saying which background to show when the player gets in a random encounter.  This stuff can be done already using additional nodes like Areas and checking collision, but that doesn't lend itself well to procedural generations, or it ends up making a game that has simple grid based movement and boolean based collision become more complex than it needs to be.  This way, instead of having logic hard coded against your arbitrary ids in a tileset, you can instead just check a tile's properties to see if it has what you're looking for.

```python
x = 1
y = 2
if tilemap.get_cell(x, y).properties["passable"]:
    moveTo(x, y)
```

**Comment by vnen** [comment] 2017-12-12 15:11
Duplicate of #12634

**Closed by vnen** 2017-12-12 15:11 UTC
