### ISSUE TITLE
Editor Crash: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#90675] opened 2024-04-14 19:29 UTC
### Tested versions

I can't reproduce again in Godot_v4.2.2-rc3_linux.x86_64

### System information

Manjaro (Plasma Kernel 6.6.26-1-MANJARO) - Godot_v4.2.2-rc3 - Compatibility

### Issue description

Hello, I am working in Godot 4.2.2-rc3 with: 

(I don't think this has much to do with anything)
```gdscript
@export var xp_curve : Curve
```

And Godot 4.2.2-rc3 randomly crash 😢 , I was sharing my screen in discord too... I don't know if that has anything to do with it...

I see another similar issue 😕 https://github.com/godotengine/godot/issues/75308#issue-1640410710

The main problem can be: **xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed**

```
   ~/programas  ./Godot_v4.2.2-rc3_linux.x86_64 --verbose                                                                           INT ✘ 
Godot Engine v4.2.2.rc3.official.16a8334b8 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Xshape 1.1 detected.
Xinerama 1.1 detected.
Xrandr 1.6 detected.
Xrender 0.11 detected.
Xinput 2.2 detected.
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
glx: failed to create dri3 screen
failed to load driver: nouveau
Only one GPU found, using default.
ScreenSaver: DBus 1.14.10 detected.
PortalDesktop: DBus 1.14.10 detected.
Using "default" pen tablet driver...
Shader 'CanvasSdfShaderGLES3' SHA256: 25a751b4a35cec0b5a7def67b5e598c5d5608e468a0facc1174a2868cbc990e1
Shader 'SkeletonShaderGLES3' SHA256: 7b6852be1d301d8f67580962773f3f6095925650f349db86f4e9badbe82a2196
Shader 'ParticlesShaderGLES3' SHA256: 3b7ab2a08228c7e89b1a11501dc77b128977d73f2b9a11b0c87b6851d74725c5
Shader 'ParticlesCopyShaderGLES3' SHA256: ff7018e928278a885440f9e454f76d766cef90e87d23a2aeeff3bc1cc8d7041d
Shader 'CopyShaderGLES3' SHA256: f8c2ab6ac3402e9312725d4a339cebf042cbbda73fc730c44fd611b25a1750ef
Shader 'CanvasShaderGLES3' SHA256: a8d333e3bd3fc3b54c593d8e700ecd1b1f1e9818546065b1c7fa876d65242fa7
Shader 'CanvasOcclusionShaderGLES3' SHA256: 68eb1f66abd5e7bebdd85bb6fa8263d2a062e110c8eb7bb0dbbcab291353bdbc
Shader 'SceneShaderGLES3' SHA256: a6078dca0877f57f41a8c7030c227954efb820c9e5c57363794251eeb778a64c
Shader 'SkyShaderGLES3' SHA256: b4a3451103fc72c729e402d2b059fdcc8098dd6ccb22cbfd56de1794c14e1a3b
Shader 'CubemapFilterShaderGLES3' SHA256: 9acf92eff10d5f211ceb47d788424af1050196c8e823ec577386dda32b4c7895
OpenGL API 4.6 (Core Profile) Mesa 24.0.2-manjaro1.1 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics (CML GT2)
JoypadLinux: udev enabled and loaded successfully.
PulseAudio 17.0.0 detected.
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.pci-0000_00_1f.3.analog-stereo
PulseAudio: detected 2 output channels
PulseAudio: audio buffer frames: 512 calculated output latency: 11ms
 
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 1929821543
EDITOR API HASH: 487156474
EditorSettings: Load OK!
Loaded system CA certificates
EditorSettings: Save OK!
Editing project: /home/matiasvme/git/RPGNodes
Godot Engine v4.2.2.rc3.official.16a8334b8 - https://godotengine.org
EditorSettings: Save OK!
TextServer: Added interface "Dummy"
XR: Clearing primary interface
XR: Removed interface "Native mobile"
XR: Removed interface "OpenXR"
PulseAudio: context terminated
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Xshape 1.1 detected.
Xinerama 1.1 detected.
Xrandr 1.6 detected.
Xrender 0.11 detected.
Xinput 2.2 detected.
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.                                                                
    ~/programas  glx: failed to create dri3 screen                                                                                ✔  5s  
failed to load driver: nouveau
Only one GPU found, using default.
ScreenSaver: DBus 1.14.10 detected.
PortalDesktop: DBus 1.14.10 detected.
Using "default" pen tablet driver...
Shader 'CanvasSdfShaderGLES3' SHA256: 25a751b4a35cec0b5a7def67b5e598c5d5608e468a0facc1174a2868cbc990e1
Shader 'SkeletonShaderGLES3' SHA256: 7b6852be1d301d8f67580962773f3f6095925650f349db86f4e9badbe82a2196
Shader 'ParticlesShaderGLES3' SHA256: 3b7ab2a08228c7e89b1a11501dc77b128977d73f2b9a11b0c87b6851d74725c5
Shader 'ParticlesCopyShaderGLES3' SHA256: ff7018e928278a885440f9e454f76d766cef90e87d23a2aeeff3bc1cc8d7041d
Shader 'CopyShaderGLES3' SHA256: f8c2ab6ac3402e9312725d4a339cebf042cbbda73fc730c44fd611b25a1750ef
Shader 'CanvasShaderGLES3' SHA256: a8d333e3bd3fc3b54c593d8e700ecd1b1f1e9818546065b1c7fa876d65242fa7
Shader 'CanvasOcclusionShaderGLES3' SHA256: 68eb1f66abd5e7bebdd85bb6fa8263d2a062e110c8eb7bb0dbbcab291353bdbc
Shader 'SceneShaderGLES3' SHA256: a6078dca0877f57f41a8c7030c227954efb820c9e5c57363794251eeb778a64c
Shader 'SkyShaderGLES3' SHA256: b4a3451103fc72c729e402d2b059fdcc8098dd6ccb22cbfd56de1794c14e1a3b
Shader 'CubemapFilterShaderGLES3' SHA256: 9acf92eff10d5f211ceb47d788424af1050196c8e823ec577386dda32b4c7895
OpenGL API 4.6 (Core Profile) Mesa 24.0.2-manjaro1.1 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics (CML GT2)
JoypadLinux: udev enabled and loaded successfully.
PulseAudio 17.0.0 detected.
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.pci-0000_00_1f.3.analog-stereo
PulseAudio: detected 2 output channels
PulseAudio: audio buffer frames: 512 calculated output latency: 11ms
 
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 1929821543
EDITOR API HASH: 487156474
EditorSettings: Load OK!
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
Loaded system CA certificates
EditorSettings: Save OK!
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
Godot_v4.2.2-rc3_linux.x86_64: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

If you want more information you can ask 👍🏻 

### Steps to reproduce

nop

### Minimal reproduction project (MRP)

nop

**Comment by ttencate** [comment] 2024-05-23 09:27
Any reason why this is not a duplicate of #75308?

**Comment by akien-mga** [comment] 2024-05-23 09:39
Duplicate of #75308 indeed.

**Closed by akien-mga** 2024-05-23 09:39 UTC
Labels: bug, platform:linuxbsd, topic:porting, crash
