### ISSUE TITLE
Geometry.is_polygon_clockwise() returns False when clockwise and True when counterclockwise.

### ISSUE THREAD

**Issue by Meowsolini** [godotengine/godot#53574] opened 2021-10-08 16:18 UTC
### Godot version

3.2.3

### System information

Windows 10

### Issue description

Geometry's method **is_polygon_clockwise()** takes a PoolVector2Array representing vertices of a 2D polygon as its argument and should return True if the Vector2s in the PoolVector2Array are listed in clockwise order, but it seems to return the opposite. It's returning True when the polygon is _counterclockwise_ and False when it's clockwise. Maybe it thinks that a positive Y value is up rather than down?

I wrote a simple test for this. _test_a_ is listed in clockwise order, and _test_b_ is listed in counterclockwise order. I put both of them into **Geometry.is_polygon_clockwise()**, and it returns the opposite of what it should be.
 
```gdscript
extends Node2D

func _ready():
	var test_a: PoolVector2Array = PoolVector2Array([\
		Vector2(2, 0), Vector2(0, 2), Vector2(-2, 0), Vector2(0, -2)])
	var test_a_is_clockwise: bool = Geometry.is_polygon_clockwise(test_a)
	print("test_a_is_clockwise: ", test_a_is_clockwise) # Should be True!
	
	var test_b: PoolVector2Array = PoolVector2Array([\
		Vector2(2, 0), Vector2(0, -2), Vector2(-2, 0), Vector2(0, 2)])
	
	var test_b_is_clockwise: bool = Geometry.is_polygon_clockwise(test_b)
	print("test_b_is_clockwise: ", test_b_is_clockwise) # Should be False!
```

Here's what the console prints when I run the 2D scene:
```
test_a_is_clockwise: False
test_b_is_clockwise: True
```

### Steps to reproduce

1. Create a PoolVector2Array with at least three Vector2s as vertices of a 2D polygon. List them in clockwise order. In Godot's 2D space, positive Y values are down, and negative Y values are up.
2. Use your PoolVector2Array as the argument in Geometry.is_polygon_clockwise() method.
3. The method will return False when it should be True.

**Comment by Calinou** [comment] 2021-10-08 16:32
cc @Xrayez

**Comment by Calinou** [comment] 2021-10-08 17:40
Duplicate of https://github.com/godotengine/godot/issues/49716.

**Closed by Calinou** 2021-10-08 17:40 UTC
Labels: bug, topic:core
