### ISSUE TITLE
Scons multithread compilation and *.gen files issue on Windows

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11060] opened 2017-09-07 22:45 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Windows 10 x64. 

```
Z:\cpp\godot>scons --version
SCons by Steven Knight et al.:
        script: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
        engine: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
        engine path: ['C:\\development\\Python27\\Scripts\\..\\Lib\\site-packages\\scons-2.5.1\\SCons']
Copyright (c) 2001 - 2016 The SCons Foundation

Z:\cpp\godot>python --version
Python 2.7.13

Z:\cpp\godot>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Issue description:**

Launching a scons build with the `-j` parameter (multithread compilation) may error at compiling files that need a `*.gen.*` file because that file hasn't been created yet or it's being created in a different thread. Launching the compilation again without any modifications will move to the next `*.gen.*` file (and may or not error with that)

This issue may or not occur on different `*.gen` files depending on the order of how the jobs end and start

This issue doesn't happen with a non-multithreaded compilation.

![https://i.imgur.com/nyec4V7.png](https://i.imgur.com/nyec4V7.png)

**Steps to reproduce:**
Launch a build starting from a clean state and using the `-j` parameter

**Comment by Zireael07** [comment] 2017-09-08 06:48
Scons multithreaded has issues on Windows where it doesn't find files, and it isn't limited to .gen.h.

**Comment by hpvb** [comment] 2017-09-08 11:41
I think this is windows specific as I was able to build Godot successfully with -j128 on a real 128 thread machine using Linux.

The question is is this a problem with our SConstruct file or a bug in scons/windows.

**Comment by Zireael07** [comment] 2017-09-08 11:45
Yes, this is a Windows specific problem and IIRC a problem on the scons side.

**Comment by Calinou** [comment] 2017-09-08 13:23
This happens only with builds done using MSVC (tested with VS 2015 and VS 2017) on Windows – builds for Android, HTML5 and Windows (using MinGW) platforms can be done multi-threaded without any issues.

**Comment by bojidar-bg** [comment] 2017-09-11 13:32
Isn't this a duplicate of #5042?

**Comment by neikeq** [comment] 2017-09-11 15:10
@bojidar-bg Yes.

**Comment by bojidar-bg** [comment] 2017-09-11 16:47
Closing as duplicate of #5042.

**Closed by bojidar-bg** 2017-09-11 16:47 UTC
