### ISSUE TITLE
Error Building Webassembly Template WITHOUT threads

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot#56932] opened 2022-01-19 05:38 UTC
### Godot version

3.4, and latest master

### System information

Windows 10, Visual Studio 2022 

### Issue description

I'm trying to compile export template for HTML, and it seems to produce 

godot.javascript.opt.threads.zip

even though I don't have threads enabled. When I try to add threads_enabled=no  I get errors:

I'm also not able to generate visual studio project file with scons p=windows vsproj=yes. It runs without error, but doesn't generate the file.

### Steps to reproduce

Windows, 
Using Scons 4.2
x64 Native Command Prompt for VS 2020 (also tried the x86 x64 Command prompt and x64 x86, and just ordinary administrator privilege cmd)

scons platform=javascript tools=no target=release

expected result: godot.javascript.opt.zip
actual result: godot.javascript.opt.threads.zip

the same thing happens with target=debug

I tried adding threads_enabled=no, but this causes strange errors.

Also,
scons p=windows vsproj=yes executes fine, but nothing happens.

**Comment by rossunger** [comment] 2022-01-19 05:39
I should mention, I'm new to compiling from source, and I'm feeling kinda lost and overwhelmed with it! apologies if I've misunderstood something.

**Comment by akien-mga** [comment] 2022-01-19 09:05
> 3.4, and latest master

What you describe is expected in `master`, and shouldn't happen in `3.4`, so can you double checks which versions you tried building?

Godot 4.0 requires threading support, so it's no longer possible to disable it.

**Comment by akien-mga** [comment] 2022-01-19 09:08
I can confirm that it's not possible to build the `master` branch without `threads_enabled=no`, despite the option still existing. It fails with:
```
./core/object/object.h:556:2: error: no type named 'mutex' in namespace 'std'; did you mean 'Mutex'?
        std::mutex _instance_binding_mutex;
        ^~~~~~~~~~
        Mutex
./core/os/mutex.h:102:7: note: 'Mutex' declared here
using Mutex = MutexImpl<FakeMutex>;
      ^
```
and then a ton of errors since not being able to compile `Object` means nothing can be compiled.

**Comment by rossunger** [comment] 2022-01-19 14:40
Thanks for the quick response! 
This was absolutely my issue!! I was on master branch by accident (I thought I was on 3.4!) 

Any thoughts on the vsproj not being generated?

**Comment by akien-mga** [comment] 2022-01-19 14:43
> Any thoughts on the vsproj not being generated?

No idea, but that should probably be a new bug report as it's not related to the web platform (as it's to build for Windows). Maybe the current logic is not compatible with VS 2022.

**Comment by rossunger** [comment] 2022-01-19 14:44
ok! thank you

**Comment by akien-mga** [comment] 2022-01-19 14:55
There's still a bug that we need to fix:

https://github.com/godotengine/godot/issues/56932#issuecomment-1016227732

**Comment by akien-mga** [comment] 2023-02-22 09:02
Fixed by https://github.com/godotengine/godot/pull/65094.

**Closed by akien-mga** 2023-02-22 09:02 UTC
Labels: bug, platform:web, topic:buildsystem, confirmed
