### ISSUE TITLE
Godot unexpected multithreaded performance

### ISSUE THREAD

**Issue by Cpl-snafu** [godotengine/godot#12140] opened 2017-10-16 03:35 UTC
**Operating system or device - Godot version:**
OS: Windows 10 (v 1703)
Godot version: 2.1.4

**Issue description:**
I noticed poor multi threaded performance.
Using the code as seen in [issue 7832](https://github.com/godotengine/godot/issues/7832), I got the following results (in ms):

test : 370
test multi: 919
ratio: 2.483784

The multi-threaded performance should be better than single core performance.
If I run OS.get_processor_count, it returns 1.

I tested on two systems and got similar results.
Main system CPU: AMD fx-8350
Secondary system CPU: Intel core I7-4510U
Given that I'm new to the godot engine, I'm sure that I'm doing something really dumb.
Yet I can't manage to figure it out.
Any help is greatly appreciated.

**Steps to reproduce:**
Run the code as displayed in issue 7832

**Comment by Hinsbart** [comment] 2017-10-16 07:29
> Using the code as seen in issue 7832, I got the following results (in ms):

Then, isn't this a duplicate of #7832?

**Comment by Cpl-snafu** [comment] 2017-10-16 08:39
Tbh, my mind was a bit clouded.
I thought because the ratio I got was so far off what they got, it was a different issue.

Unless the documentation is wrong, OS.get_processor_count shouldn't return 1 on either of my systems.
It should return 2,4 or 8 depending on the system and whether it counts virtual cores as well.
So I guess that remains as a bug.

As for the "main" issue.
Multi-threading is doing weird things, which is indeed a duplicate.

I'm not really familliar with the do's and don'ts of issue trackers.
As far as i'm concerned the "main" issue can be closed.
What to do with the processor count bug, I'll leave up to you to decide.

**Comment by Hinsbart** [comment] 2017-10-16 08:43
> What to do with the processor count bug, I'll leave up to you to decide.

Please feel free to open another issue about that bug.
In the meantime, I'm closing this as duplicate of #7832

**Closed by Hinsbart** 2017-10-16 08:43 UTC
Labels: bug, topic:core
