### ISSUE TITLE
[C#] casing of method GetWorld3d in Node3D does not capitalize the letter D as the set convention in 4.0.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#70725] opened 2022-12-30 01:08 UTC
### Godot version

4.0 beta 10

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

In `Node3D` there's a method `GetWorld3d()`, if you go through it you can see it like this:
```
public World3D GetWorld3d() => (World3D) NativeCalls.godot_icall_0_49(Node3D.MethodBind32, Object.GetPtr((Object) this));
```
It gives `World3D` but it's called `GetWorld3d`, since everything is now either `2D` or `3D` I assume this was just missed? :)

I'm not sure if this belongs to one of the renaming issues here or not I'm a little bit lost in them not sure what is currently relevant or not so I apologize in case I should have added this just as a post in the discussion.

It's not a serious issues but inconsistency which slipped through I guess.

### Steps to reproduce

See above.

### Minimal reproduction project

Nothing.

**Comment by raulsntos** [comment] 2023-01-01 18:30
Duplicate of https://github.com/godotengine/godot/issues/28748

**Closed by raulsntos** 2023-01-01 18:30 UTC
