### ISSUE TITLE
Asign int value to float problem

### ISSUE THREAD

**Issue by davidkbd** [godotengine/godot#32906] opened 2019-10-18 15:33 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 8

**Issue description:**
This problem is only present when executing a .exe without debug.

```
func _ready():
	var value : float = 3
	$Label.text = str(value)

```
The label contains a "0"

```
func _ready():
	var value : float = 3.0
	$Label.text = str(value)
```

Now the label contains a "3"

If the project is exported with debug enabled, the label contains "3" in both cases

I think if this is the correct behaviour then a compilation error is required, but none error es thrown. Really, the problem is that running from the editor the asigned value is accepted...

**Steps to reproduce:**
Define a float variable, and asign a int value in any moment of the program.
Export the project without debug, and execute the .exe.

**Minimal reproduction project:**

**Comment by volzhs** [comment] 2019-10-18 18:05
cc @vnen @bojidar-bg

**Comment by qarmin** [comment] 2019-10-18 18:12
Similar to #24035, release build lose some info about variables.

**Comment by vnen** [comment] 2019-10-19 00:58
It's a duplicate of #24035

**Closed by vnen** 2019-10-19 00:58 UTC
Labels: bug, topic:gdscript
