### ISSUE TITLE
Godot with Mono fails to run non-Mono projects

### ISSUE THREAD

**Issue by wluckin** [godotengine/godot#24636] opened 2018-12-28 12:13 UTC
**Godot version:** 3.1-alpha4

**OS/device including version:** OpenSUSE Tumbleweed 20181219

**Issue description:**

I started a new project with C# support. Added a single label to a 2D scene, which I then saved. I attempt to run the scene with the "Play Scene" button, and no window appears.

In the console output, I see:
```
modules/mono/editor/csharp_project.cpp:155 - Method/Function Failed, returning: FAILED
 modules/mono/editor/godotsharp_builds.cpp:388 - Condition ' metadata_err != OK ' is true. returned: false
 editor/editor_node.cpp:4501 - A Godot Engine build callback failed
```

This issue is not present in the 3.0 builds.

**Steps to reproduce:**
Create a new project, add a label, attempt to play the scene.

**Comment by wluckin** [comment] 2018-12-28 12:51
Sorry to have wasted your time, guys, this was (mostly) my fault after checking the console output.

Godot couldn't run the scene because of a missing C# project file, that it couldn't compile because my msbuild wasn't on my path.

However, perhaps showing this error in the editor would be nice?

Nevertheless, if I'd have checked that the prereqs were configured properly, this wouldn't have been a problem.

**Comment by aaronfranke** [comment] 2019-01-27 07:10
@neikeq The problem is that Godot 3.1 beta2 Mono can't run non-Mono projects. I just came onto GitHub to report this, but found it already reported here. Ideally, I would like to be able to download a single copy of Godot (the Mono version) and be able to use it for my non-Mono projects as well.

![h](https://user-images.githubusercontent.com/1646875/51797825-5d17bc80-21d8-11e9-8019-340ba32c0f12.png)

Minimal reproduction project: [MonoErrors.zip](https://github.com/godotengine/godot/files/2799837/MonoErrors.zip)

Open in Godot 3.1 beta 2 without Mono: It runs fine.

Open in Godot 3.1 beta 2 with Mono: It fails to run.

I suggest changing the title to "Godot with Mono fails to run non-Mono projects" or similar.

**Comment by akien-mga** [comment] 2019-01-27 09:10
Confirmed, I can't run my non-Mono projects with 3.1 beta 2, it errors out with:
```
Unhandled Exception:
System.IO.FileNotFoundException: Could not find file "/home/akien/tmp/godot/test/CoinDash-test/Coin Dash.csproj"
File name: '/home/akien/tmp/godot/test/CoinDash-test/Coin Dash.csproj'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <c6a2acbd92134eb789822df70cec4630>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in <c6a2acbd92134eb789822df70cec4630>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)
  at System.Xml.XmlDownloadManager.GetStream (System.Uri uri, System.Net.ICredentials credentials, System.Net.IWebProxy proxy, System.Net.Cache.RequestCachePolicy cachePolicy) [0x00018] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlUrlResolver.GetEntity (System.Uri absoluteUri, System.String role, System.Type ofObjectToReturn) [0x00032] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlTextReaderImpl.FinishInitUriString () [0x0004c] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlTextReaderImpl..ctor (System.String uriStr, System.Xml.XmlReaderSettings settings, System.Xml.XmlParserContext context, System.Xml.XmlResolver uriResolver) [0x000c7] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlReaderSettings.CreateReader (System.String inputUri, System.Xml.XmlParserContext inputContext) [0x0003b] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlReader.Create (System.String inputUri, System.Xml.XmlReaderSettings settings, System.Xml.XmlParserContext inputContext) [0x0000a] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at System.Xml.XmlReader.Create (System.String inputUri) [0x00000] in <bccd0c518adb40dd93c3dc75c8510998>:0 
  at Microsoft.Build.Construction.ProjectRootElement.Open (System.String path, Microsoft.Build.Evaluation.ProjectCollection projectCollection) [0x00008] in <cadf3f8064dc4583871ae7ae8e895ba0>:0 
  at Microsoft.Build.Construction.ProjectRootElement.Open (System.String path) [0x00006] in <cadf3f8064dc4583871ae7ae8e895ba0>:0 
  at GodotSharpTools.Project.ProjectUtils.GetIncludeFiles (System.String projectPath, System.String itemType) [0x00029] in <844f9d8f959e4e6bb4a144167d102670>:0 
ERROR: generate_scripts_metadata: Method/Function Failed, returning: FAILED
   At: modules/mono/editor/csharp_project.cpp:155.
ERROR: editor_build_callback: Condition ' metadata_err != OK ' is true. returned: false
   At: modules/mono/editor/godotsharp_builds.cpp:388.
ERROR: call_build: A Godot Engine build callback failed.
   At: editor/editor_node.cpp:4507.
```

**Comment by neikeq** [comment] 2019-01-27 17:11
The error looks like a duplicate of #23432, which was fixed by 9cd24b4f6d0938d4c51eb20f9630eb4281c7056f. Was this commit included in beta 2? Can you reproduce this on latest master?

**Comment by akien-mga** [comment] 2019-01-27 17:34
Yeah beta 2's build was started right before you merged that PR. It is in beta 3 though, I'll test to confirm that it works.

**Comment by akien-mga** [comment] 2019-01-27 17:36
Yeah, beta 3 works fine.

**Closed by akien-mga** 2019-01-27 17:36 UTC
Labels: bug, high priority, topic:mono

**Comment by mnn** [comment] 2019-02-10 15:59
Are you sure it is fixed?

```
$ ./mod_test.x86_64 
OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/xxx/godot/mod_test/Build/data_Godot/Mono/lib/mono/4.5/mscorlib.dll' directory.
```

I am getting this with 3.1.beta**3**.mono.official (Linux, 64b). Exported binary is in `/xxx/godot/mod_test/Build/`.

It got me confused for a while. After adding one empty C# script the build works (from editor it was working even without the dummy C# script).

**Comment by neikeq** [comment] 2019-02-10 16:46
@mnn This is a different error, can you open a new issue?
