### ISSUE TITLE
Toolscript Setter not called properly

### ISSUE THREAD

**Issue by bozoVuksan** [godotengine/godot#70345] opened 2022-12-20 11:06 UTC
### Godot version

v4.0.beta9.mono.official [e780dc332]

### System information

Windows 10 Home, Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz   2.90 GHz, 

### Issue description

I have an Exported Variable with a GETTER/SETTER. 
When the Setter is called I am printing to the console. 

**Expected Behaviour**
I am expecting the print to happen when the Variable is changed through the Inspector. When I am setting it or removing it.

**Current Behaviour**
The Setter is called when pressing the revert Button (Without reverting the value. Might be another bug?).
It calls the Setter of the property. This doesn't seem correct. 

### Steps to reproduce

https://user-images.githubusercontent.com/11051231/208652416-ff14ddbe-3a80-451e-a56f-b4f37d19e26f.mp4

### Minimal reproduction project

[ToolScriptExportedVariableIssue.zip](https://github.com/godotengine/godot/files/10267814/ToolScriptExportedVariableIssue.zip)

**Comment by Zireael07** [comment] 2022-12-20 12:03
The revert button is supposed to set the variable to the default value. Since it SETS the value, it calls the setter.

The real bug is that the revert button doesn't actually reset in your case

**Comment by bozoVuksan** [comment] 2022-12-20 12:06
Yeah but I would also expect it to call the setter when the variable is applied in the editor, which it doesn't right now.

**Comment by raulsntos** [comment] 2022-12-20 17:44
This doesn't seem to be exclusive to C#, here's your MRP ported to GDScript: [ToolScriptExportedVariableIssue-gd.zip](https://github.com/godotengine/godot/files/10270851/ToolScriptExportedVariableIssue-gd.zip)

The issue is that exported properties of type Node (`PROPERTY_HINT_NODE_TYPE`) are actually just exporting a NodePath behind the scenes which is the `metadata/_editor_prop_ptr_ChildReference` member that gets set by the editor so the setter is not called.

**Comment by diegzumillo** [comment] 2022-12-21 05:39
Confirmed here as well. Setter doesn't get called when changing value in the editor (with @export).

**Comment by Calinou** [comment] 2022-12-29 21:38
Duplicate of https://github.com/godotengine/godot/issues/65916.

**Closed by Calinou** 2022-12-29 21:38 UTC
Labels: bug, topic:core, topic:editor, confirmed
