### ISSUE TITLE
Wrong pop up position of new nodes in animation tree edition (DisplayServer regression)

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#58990] opened 2022-03-10 16:13 UTC
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

When adding new nodes in an animation tree, such nodes appear way below clicked position. 

![wrong-offset](https://user-images.githubusercontent.com/8985409/157704800-54f66844-e298-4471-866f-30b9a8ada13a.gif)

### Steps to reproduce

Add nodes to an animation tree.

### Minimal reproduction project

None, just add nodes to an animation tree.

**Comment by Calinou** [comment] 2022-03-10 16:34
This is a duplicate of another issue (where it occurs with the VisualScript editor instead, which also uses GraphEdit/GraphNode).

**Comment by TokageItLab** [comment] 2022-03-11 00:15
Dupe of https://github.com/godotengine/godot/issues/57410.

**Closed by TokageItLab** 2022-03-11 00:15 UTC
Labels: bug, topic:editor, regression, topic:gui, topic:animation
