### ISSUE TITLE
[4.2] Problem with displaying 3D models

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#85549] opened 2023-11-30 16:01 UTC
### Godot version

4.2 Stable

### System information

Windows 10, Radeon RX 560 Series

### Issue description

Decided to run this demo - [[godot-4-3D-Characters](https://github.com/gdquest-demos/godot-4-3D-Characters)](https://github.com/gdquest-demos/godot-4-3D-Characters)
But all model textures display large pixels
![123](https://github.com/godotengine/godot/assets/130399274/111465d6-5e8f-4547-bae0-3d1fdcb20d33)
![1233](https://github.com/godotengine/godot/assets/130399274/3bc1ad37-ddfc-41c9-8f69-66ef0ccf4b07)

### Steps to reproduce

Run the demo from the link

### Minimal reproduction project

follow the links

**Comment by clayjohn** [comment] 2023-11-30 18:09
Running the demo looks fine on my intel integrated graphics. 

Can you reproduce that issue on older versions of Godot?

To be perfectly frank, those artifacts look like GPU corruption artifacts to me. It might be a sign that your GPU is malfunctioning. You can try running a few non-Godot games and see if you spot similar artifacts in them.

**Comment by YuriSizov** [comment] 2023-11-30 19:31
> Running the demo looks fine on my intel integrated graphics.

Same here with NVidia. In fact, the cover image for the release article is made with this project, so it worked perfectly fine in RC2 and stable.

**Comment by JekSun97** [comment] 2023-11-30 20:28
Sorry for the quality of the gif, the video failed to load.
Maybe this problem is only on AMD video cards?
![gdLog 00_00_00-00_00_30](https://github.com/godotengine/godot/assets/130399274/e1c4637a-03de-4429-a498-d90b277a3630)

**Comment by clayjohn** [comment] 2023-12-01 16:10
This might be a duplicate of https://github.com/godotengine/godot/issues/76258

**Comment by JekSun97** [comment] 2023-12-02 00:36
I discovered that this only happens in Forward+ mode

**Comment by JekSun97** [comment] 2023-12-08 22:09
Also when reducing the window size the problem seems to disappear:
https://youtu.be/hb5O4nz3Leo?si=Gwo3wYhQ6bU1j6Jj

**Comment by JekSun97** [comment] 2024-01-12 09:05
The problem disappeared in version 4.3 dev2

**Comment by Calinou** [comment] 2024-01-12 16:10
Thanks for following up :slightly_smiling_face: Closing.

**Closed by Calinou** 2024-01-12 16:10 UTC
Labels: topic:rendering, needs testing, topic:3d

**Comment by JekSun97** [comment] 2024-01-29 19:18
> Thanks for following up 🙂 Closing.

This problem occurs again in 4.2.2-rc1 but does not occur in 4.1.4-rc1

**Comment by YuriSizov** [comment] 2024-01-29 19:49
Everything that 4.1.4 has, is included in 4.2.2. And everything included in 4.2.2 is in 4.3. So I would wager a guess that all 3 versions are affected (or at least 4.1.4 and 4.2.2) and the problem is just hard to reproduce reliably.

**Comment by JekSun97** [comment] 2025-01-18 17:43
Hello again... This problem is present again in 4.4 beta1 :'(
