### ISSUE TITLE
Editor crash when setting GPUParticle draw pass with any mesh material as Particle Billboard.

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#70382] opened 2022-12-21 02:43 UTC
### Godot version

4.0 Beta 9

### System information

macOS v13.0

### Issue description

Immediate editor crash.

### Steps to reproduce

1. Add a GPU Particle.
2. Set draw pass 1 to QuadMesh.
3. Create a new standard material for QuadMesh.
4. Set billboard to Particle Billboard.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2022-12-21 06:57
I can't reproduce this issue running on PopOS 22.04. 

Can you run the engine from the command line, reproduce the issue, and then let us know if there is anything printed?

**Comment by Tetane** [comment] 2022-12-21 10:34
I tested it on windows 10 (Nvidia GTX 980). The editor crashes sometime, but not always.
When it's not crashing, it prints an error at each frame:
```
ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7345)
```

And just before the crash, I get these errors:
```
ERROR: Condition "!shader" is true. Returning: RID()
   at: RenderingDeviceVulkan::render_pipeline_create (drivers\vulkan\rendering_device_vulkan.cpp:5983)
drivers\vulkan\rendering_device_vulkan.cpp:5983 - Condition "!shader" is true. Returning: RID()
ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
   at: PipelineCacheRD::_generate_version (servers\rendering\renderer_rd\pipeline_cache_rd.cpp:61)
servers\rendering\renderer_rd\pipeline_cache_rd.cpp:61 - Condition "pipeline.is_null()" is true. Returning: RID()
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7298)
This render pipeline requires (0) bytes of push constant data, supplied: (16)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7315)
No render pipeline was set before attempting to draw.
Exception thrown at 0x00007FF654E83C65 in godot.windows.editor.dev.x86_64.exe: 0xC0000005: Access violation reading location 0x00000000EEDE783A.
```

The debugger stops the execution in "core\templates\cowdata.h" at line 133 during the crash.

**Comment by clayjohn** [comment] 2023-01-11 21:41
Duplicate of https://github.com/godotengine/godot/issues/69156. I am closing this issue in favour of https://github.com/godotengine/godot/issues/69156 so that we can track this issue in one place

**Closed by clayjohn** 2023-01-11 21:41 UTC
Labels: bug, topic:rendering, needs testing, crash
