### ISSUE TITLE
Crash when dragging polygon points in inspector

### ISSUE THREAD

**Issue by 0ttoman** [godotengine/godot#61272] opened 2022-05-22 09:04 UTC
### Godot version

v3.5.rc1.official.e86d840d4

### System information

Linux 5.17.4-100.fc34.x86_64, Mesa Intel(R) HD Graphics 520 (SKL GT2)

### Issue description

Crash when user tries to rearrange the polygon points in the inspector,
but drags the point to a field where it is not supposed to be.

### Steps to reproduce

- create any polygon node
- create multiple points
- drag the index 0 point down and then up like in the picture

![Screenshot_20220522_105140](https://user-images.githubusercontent.com/24543934/169686682-90fa0097-f299-412b-a231-de471396ae60.png)

Godot will crash with multiple Errors like
```
ERROR: Invalid new child position: 7.
   at: move_child (scene/main/node.cpp:386)
ERROR: Invalid new child position: -1.
   at: move_child (scene/main/node.cpp:386)
```

### Minimal reproduction project

[oob_bug.tar.gz](https://github.com/godotengine/godot/files/8749102/oob_bug.tar.gz)

**Comment by timothyqiu** [comment] 2022-05-22 12:53
Possible duplicate of #54734

**Comment by kleonc** [comment] 2022-05-22 14:13
> Possible duplicate of #54734

Indeed, duplicate of #54734.

**Closed by kleonc** 2022-05-22 14:13 UTC
Labels: bug, topic:editor, crash
