### ISSUE TITLE
Vector2 math bit corruption

### ISSUE THREAD

**Issue by SlitheringMule** [godotengine/godot#50251] opened 2021-07-07 15:55 UTC
### Godot version

3.3.2.stable.official

### System information

Windows 10

### Issue description

Doing maths with _Vector2_s returns slightly corrupted answers 👀, though the x and y components should be floats and not lose any precision, leading me to believe that this is not due to floating point errors.

This might be due to unnecessary maths going on in the background, perhaps deteriating the precision of the numbers.

The example in the steps to reproduce better illustrate the problem.

This bug might lead to rotated _Vector2_s having a value larger than their original length!

### Steps to reproduce

```
func _ready() -> void:
	var anumber : float = -0.1234567
	var actual_answer : float = -123.4567
	print("multiply_then_extract_x " + var2bytes((Vector2(anumber, 0) * 1000).x).hex_encode())
	print("extract_x_then_multiply " + var2bytes(Vector2(anumber, 0).x * 1000).hex_encode())
	print("multiply_original_float " + var2bytes(anumber * 1000).hex_encode())
	print("actual_answer           " + var2bytes(actual_answer).hex_encode())
```

### Minimal reproduction project

Run the above code in Godot.

**Comment by kleonc** [comment] 2021-07-07 19:13
The cause is the same as in #50022: `Vector2.x`, `Vector2.y` are `float` (32-bit) on the C++ side but in GDScript `float` is 64-bit so there are conversions happening all over in different places.
This C++ snippet shows what conversions lead to the results in your example:
```
#include <iostream>

void print_as_hex(float f) {
	std::cout << std::hex << *((uint32_t*)&f) << std::endl;
}
void print_as_hex(double d) {
	std::cout << std::hex << *((uint64_t*)&d) << std::endl;
}

int main() {
	double anumber = -0.1234567;
	double actual_answer = -123.4567;
	
	print_as_hex((float)((float)anumber * (double)1000));
	print_as_hex((double)(float)anumber * (double)1000);
	print_as_hex(anumber * (double)1000);
	print_as_hex(actual_answer);
	
	return 0;
}
```
Output:
```
c2f6e9d5
c05edd3a99800000
c05edd3a92a30553
c05edd3a92a30553
```

**Comment by SlitheringMule** [comment] 2021-07-07 19:53
Is there a way to force _Vector2_s to use double precision?

**Comment by Calinou** [comment] 2021-07-07 20:05
> Is there a way to force _Vector2_s to use double precision?

See https://github.com/godotengine/godot/issues/288.

**Comment by SlitheringMule** [comment] 2021-07-07 21:59
> 
> 
> > Is there a way to force _Vector2_s to use double precision?
> 
> Not yet, see #288.

If double precision and even possible more (as per https://github.com/godotengine/godot-proposals/issues/892) were implemented it would make Godot usable for professional simulations, as many of the Vector2 problems (such as this issue, which also happens when rotating _Vector2_s, and _transform_ not multiplying correctly) would no longer be present. It would make Godot suitable for a range of professional applications, and I believe this would be high beneficial for the project.

**Comment by SlitheringMule** [comment] 2021-07-07 22:06
I believe that it is very imporant that a high-level of accuracy through precision is available to those users who need and, and having consistency by not converting between 32 and 64-bit floats, but rather using 64-bit all along. This would likely take a lot of work but this would be one of the features that would make Godot evolve into a very professional product.

**Comment by aaronfranke** [comment] 2021-07-07 22:32
@SlitheringMule I agree with you. Although I think having 32-bit floats as an option is still useful.

That said, this issue is a duplicate of https://github.com/godotengine/godot-proposals/issues/892, closing. If you want to see this implemented, feel free to give the proposal a :+1: and let people know about this problem and the proposal.

**Closed by aaronfranke** 2021-07-07 22:32 UTC
Labels: bug, topic:core
