### ISSUE TITLE
Suddenly cannot select or move nodes anymore

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#32787] opened 2019-10-12 21:14 UTC
**Godot version:**
3.2. Alpha2

**OS/device including version:**
Win7

**Issue description:**
Using my LMB I cannot select nodes in the viewport anymore or move them around in the viewport it they are selected via the scene panel. I had to close and restart the editor to make it work again.

![cant_move_tool](https://user-images.githubusercontent.com/47016402/66707725-ae0b1900-ed45-11e9-9c4b-b6ec9f59d87c.gif)

**Steps to reproduce:**
No idea how to reproduce this. I was just selecting and moving nodes for all I can remember.

**Comment by clayjohn** [comment] 2019-10-12 21:23
Can you experiment and figure out a way to reproduce? 

If you can't reproduce then neither can anyone else. And if no one else can reproduce, then no one can fix the underlying bug.

**Comment by golddotasksquestions** [comment] 2019-10-12 21:39
I'm retracing my steps, but without success so far.

**Comment by akien-mga** [comment] 2020-07-27 12:12
I'll close this as without steps to reproduce, it's pretty difficult to fix. It does seem buggy on the GIF as it pans even though the select tool was enabled, but we can't debug further as is.

If anyone finds a way to reproduce this issue, please comment and we'll reopen it.

**Closed by akien-mga** 2020-07-27 12:12 UTC
Labels: bug, topic:editor

**Comment by PracticalNPC** [comment] 2022-08-09 18:00
I'm trying to narrow down on the cause of this bug, are you using an Xbox controller and/or using the Steam version of Godot?

**Comment by Calinou** [comment] 2022-08-09 21:04
> I'm trying to narrow down on the cause of this bug, are you using an Xbox controller and/or using the Steam version of Godot?

If you can reproduce this on 3.5 or later, please open a new issue with a minimal reproduction project attached.

**Comment by golddotasksquestions** [comment] 2022-08-15 12:27
@PracticalNPC 

Yes, I was using Xbox controller at that time, but not the Steam version of Godot.
