### ISSUE TITLE
Can't draw_texture use load

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#81263] opened 2023-09-03 06:59 UTC
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

window10 64bit

### Issue description

![GIF 2023-9-3 14-40-54](https://github.com/godotengine/godot/assets/35988767/3f40376f-45b1-4a3a-ac11-eb4f59288935)

### Steps to reproduce

/

### Minimal reproduction project

[TexDrawTest.zip](https://github.com/godotengine/godot/files/12505329/TexDrawTest.zip)

**Comment by AThousandShips** [comment] 2023-09-03 08:14
Using `load` in this place is not recommended, it's not instant, you should load the texture before

Now, setting aside that this is not a good usage of `load` here, this might be a bug

**Comment by AThousandShips** [comment] 2023-09-03 08:15
Please also fill in the report more properly, describe the steps rather than using a video, not everyone are able to watch a video for many reasons

**Comment by AThousandShips** [comment] 2023-09-03 08:46
Duplicate of #25296

**Closed by AThousandShips** 2023-09-03 08:46 UTC
Labels: discussion, topic:rendering, topic:2d
