### ISSUE TITLE
Duplicated animation keys when re-importing glb files.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#40361] opened 2020-07-14 00:54 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Pop OS 20.04
Nvidia 440.100

**Issue description:**
When I re-import my glb files every animation key seems to be duplicated. This happens every time I click re-import so after a while the list is massive. In the import settings I have ``Storage`` on ``Files (.anim)`` and I have the option ``Keep Custom`` on.

**Steps to reproduce:**
1. Open the ``AnimatedCube.glb``, it shows 3 bones in the animation.
![image](https://user-images.githubusercontent.com/14081613/87367863-69363c00-c57c-11ea-9ecd-734db7337cc9.png)
2. Select ``AnimatedCube.glb`` and re-import it.
3. Now open it op as ``New Inherited``.
![image](https://user-images.githubusercontent.com/14081613/87367988-b7e3d600-c57c-11ea-9563-ed98c02a12e1.png)
4. Every key has been duplicated.

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/4920888/BugReport.zip)

**Comment by alroyo** [comment] 2020-09-14 20:37
This issue may be a duplicate of #39959 and solved with #39968

I have encountered this problem recently with 3.2.2 version as you mentioned. I'd say you can choose between:

- Downgrade your project to 3.2.1, as it is the closest stable release.
- Upgrade to 3.2.3 (RC-6 right now) and get all the nice regression fixes (like this one).

Hope it helps

**Comment by akien-mga** [comment] 2020-09-14 20:46
Indeed, seems like a duplicate of #39959. Thanks for the review.

**Closed by akien-mga** 2020-09-14 20:46 UTC
Labels: bug, topic:import
