### ISSUE TITLE
Animating Area's collision shape causes non detection for signal

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#34605] opened 2019-12-25 20:24 UTC
**Godot version:**
3.2 beta 4
**OS/device including version:**
ubuntu 18.04
**Issue description:**
 The title describes the bug
**Steps to reproduce:**
create an spatial node, insert area + collision shape as sphere, create a animationplayer
animate the sphere radius to expand from 0.1 to 3 in about 0.3secs setup the signal to detect some rigidbody and voila! doesnt work :( 

**Minimal reproduction project:**
https://github.com/nonunknown/crashcreator/tree/alpha -> check for resources/explosion.res

**There's a workaround? **
yes there is, just setup the sphere radius to the size you want and then disable it after some time, i.e:
```
_ready():
    yield(get_tree().create_timer(1,false),"timeout")
    queue_free()
```

**Comment by KoBeWi** [comment] 2019-12-25 23:00
Might be duplicate of #33369

**Comment by Calinou** [comment] 2020-01-13 22:43
Duplicate of #33369.

**Closed by Calinou** 2020-01-13 22:43 UTC
