### ISSUE TITLE
Saving and clicking Play at the same time causes errors in ProgressDialog, makes editor unresponsive

### ISSUE THREAD

**Issue by jamesgiddings** [godotengine/godot#44063] opened 2020-12-03 09:49 UTC
Had a look but couldn't spot anything

**Godot version:**

Godot Engine v3.2.2.stable.official - https://godotengine.org

**OS/device including version:**
Windows 10 Home
Intel i5-9400F
OpenGL ES 3.0 Renderer: GeForce GTX 1660/PCIe/SSE2

**Issue description:**

Crash

**Steps to reproduce:**
Editor crashes if you save and click play too quickly. 

If I Ctrl-S to save and then click the play scene button too soon, I get a crash.

**Comment by Zireael07** [comment] 2020-12-03 09:54
Since it's Windows, maybe it's related to file locking limitations or the save on play editor setting? Try disabling the latter?

**Comment by akien-mga** [comment] 2020-12-03 10:02
Can you clarify what you mean by "crash"? Is there a stacktrace in the console, or does Windows notify you that "This app does not respond"?

**Comment by jamesgiddings** [comment] 2020-12-07 14:00
Windows notifies me that the app is not responding - the editor is greyed out and windows has to close Godot. Apologies for the delay in responding.

**Comment by jamesgiddings** [comment] 2021-01-12 09:47
So I've found out that this was actually to do with having text highlighted in the console when trying to play the game. I think that is probably not a problem, it was just happening to me frequently because I am often inspecting data which I'm printing due to the other issue I'm having with not being able to view three-level nested dictionaries in the inspector.

**Comment by VedatGunel** [comment] 2021-01-12 10:12
I think the original issue is valid, as i can reproduce it by trying to save with Ctrl + S and hit Play at the same time. The game runs without issue, but the editor becomes unresponsive and the following errors are shown in console:

```
ERROR: task_step: Condition "!tasks.has(p_task)" is true. Returned: cancelled
   At: editor/progress_dialog.cpp:205
ERROR: task_step: Condition "!tasks.has(p_task)" is true. Returned: cancelled
   At: editor/progress_dialog.cpp:205
ERROR: task_step: Condition "!tasks.has(p_task)" is true. Returned: cancelled
   At: editor/progress_dialog.cpp:205
ERROR: task_step: Condition "!tasks.has(p_task)" is true. Returned: cancelled
   At: editor/progress_dialog.cpp:205
ERROR: task_step: Condition "!tasks.has(p_task)" is true. Returned: cancelled
   At: editor/progress_dialog.cpp:205
Godot Engine v3.2.4.beta4.official - https://godotengine.org
ERROR: end_task: Condition "!tasks.has(p_task)" is true.
   At: editor/progress_dialog.cpp:231
```

**Comment by akien-mga** [comment] 2021-01-12 10:19
Indeed, I can reproduce it too on Linux. I don't get a crash, but the editor doesn't handle input properly anymore (it still displays logs from the running game so it's not frozen).

**Comment by VedatGunel** [comment] 2021-01-14 20:33
@akien-mga Had you tested this in 3.2 as well? Because I'm trying to reproduce it in the master branch, but I couldn't manage to do it.

**Comment by akien-mga** [comment] 2021-01-14 21:04
I did try on latest `3.2` indeed. I just tried `master` and I also can't reproduce the issue there, so it seems to be fixed in `master`.

As it's not really critical, I think we can close this as fixed then.

**Closed by akien-mga** 2021-01-14 21:04 UTC
Labels: bug, confirmed, topic:editor
