### ISSUE TITLE
Toolbar tooltips lock current selection

### ISSUE THREAD

**Issue by Repiteo** [godotengine/godot#78370] opened 2023-06-17 15:45 UTC
### Godot version

4.1.beta2

### System information

Windows 11, Forward+, RTX 3080

### Issue description

If a tooltip of one of the items in the main toolbar features tooltips, those tooltips appearing for a selection will lock that selection in & hovering over other options won't have any effect. Canceling out of the selection through other means (clicking a spacer) will return the selection list to standard behavior

### Steps to reproduce

https://github.com/godotengine/godot/assets/17489292/14718381-def2-4183-aa1c-995a53447185

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment] 2023-06-17 15:54
Can you please check, if this is a duplicate of #73926?

**Comment by Repiteo** [comment] 2023-06-17 15:59
Potentially? I don't know if progress was made since, but in my case the _only_ area affected was the toolbar. Other areas, like the inspector, handle tooltips without issue

https://github.com/godotengine/godot/assets/17489292/6f75627a-0257-4c74-972f-bb8917a2cf1c

**Comment by Calinou** [comment] 2023-06-17 17:46
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73926.

**Closed by Calinou** 2023-06-17 17:46 UTC
