### ISSUE TITLE
Animation blend nodes do not slerp quaternions along shortest path

### ISSUE THREAD

**Issue by J-Ponzo** [godotengine/godot#81755] opened 2023-09-16 19:47 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 Threads)

### Issue description

When blending animations together, quaternion interpolation are not always along the shortest path. I think that should be the case

The issue occurred with different AnimationTree Nodes :
- Blend2
- BlendSpace1D
- BlendSpace2D

### Steps to reproduce

- Extract the given "AnimBlendIssue" sample project then Open it
- Open main.tscn
- Select the AnimationTree node
- In the AnimationTree panel  play with the blend slider of the Blend2 Node
![Capture](https://github.com/godotengine/godot/assets/32590977/7d4730c9-48d5-48e2-907e-c7d44bd53065)

=> The prism in the viewport rotates 270° clock side will I'm expecting 90° counter clock side

Note : For convenience the animation clips Rotation1 and Rotation2 consist of only one rotation track with only one keyframe :
- Rotation1 : x = -0.062; y = 0.997; z = -0.003; w=0.052
- Rotation2 : x=0.046; y=-0.742; z=-0.042; w=0.668

### Minimal reproduction project

[AnimBlendIssue.zip](https://github.com/godotengine/godot/files/12641425/AnimBlendIssue.zip)

**Comment by J-Ponzo** [comment] 2023-09-16 20:10
Reproduced with :
- v4.2.dev4.official [549fcce5f]

**Comment by TokageItLab** [comment] 2023-09-16 21:11
Dupe of https://github.com/godotengine/godot/issues/81021. See also https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#for-better-blending.

The appropriate reference angle must be set manually as Rest or RESET. It does not make sense to get the shortest path from the immediately preceding frame. Even if it is the shortest path when comparing blends, it may not be the shortest path during playback of the animation.

**Closed by TokageItLab** 2023-09-16 21:11 UTC
Labels: documentation, topic:animation
