### ISSUE TITLE
Bug with loading global Script

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#28010] opened 2019-04-14 09:22 UTC
In Godot 3.1 official:

I have multiple globals via autoload defined. Im using them in this capacity for a longer time already, but all of a sudden the same constellation suddenly throws the error:

"Parser Error: Class 'ControllerDamage' was found in global scope but its script could not be loaded"

I tried reverting the changes i made, but nothing seemed to fix it, but commenting out the code or load():

![image](https://user-images.githubusercontent.com/24807557/56090801-6515fd00-5ea7-11e9-9d4a-cb6c26a8f287.png)

The controllerDeath, while being identical in nature (just a Node with a static func), didnt have that same error.

Upon inserting the:

`var ControllerDamage = load("res://Prefabs/Controllers/ControllerDamage.gd")`

the code works perfectly fine again.

Maybe this error relates to: https://github.com/godotengine/godot/issues/27136 ?

But i dont have the same "reference loop error" like the other issue

**Comment by Dentrax** [comment] 2019-05-26 13:12
I'm getting the exact same error. Any update related to this? @akien-mga

**Comment by lmerriam** [comment] 2019-05-30 22:15
+1 having the same issue

**Comment by caffeine-mgn** [comment] 2019-07-24 00:08
+1

**Comment by santouits** [comment] 2019-07-24 01:13
Someone has to upload a simple reproducable project though

**Comment by caffeine-mgn** [comment] 2019-07-24 17:04
[bug.zip](https://github.com/godotengine/godot/files/3427981/bug.zip)

Run the scene and you will see the bug

**Comment by fahim44** [comment] 2019-07-27 16:59
+1

**Comment by patriceperez** [comment] 2019-11-07 01:47
any updates on this please?

**Comment by caffeine-mgn** [comment] 2019-11-08 09:32
> 
> 
> any updates on this please?

use C#

Script language in Godot is bad, IMHO :)
Jvm-bytecode is better. If godot use jvm-bytecode we can use any other language: Java, Scala, Kotlin, Python, Ruby, Lua.

**Comment by KoBeWi** [comment] 2020-11-02 23:45
This is pretty much duplicate of #27136 (based on the newest MRP), so closing.

**Closed by KoBeWi** 2020-11-02 23:45 UTC
Labels: bug, confirmed, topic:core
