### ISSUE TITLE
Reroute Visualscript node connections

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28176] opened 2019-04-18 21:31 UTC
In UE4s Blueprints you can [add a "reroute node"](https://docs.unrealengine.com/en-us/Engine/Blueprints/BP_HowTo/ConnectingNodes#rerouteconnections) which can be useful for large scripts. I don't know exactly how this would work in Godot, but maybe middle clicking on a connection would add a pin that you could drag around?
![Concept](https://user-images.githubusercontent.com/28286961/56393199-f1bc1480-6233-11e9-87ca-7e46058f695a.png)

**Comment by Chaosus** [comment] 2019-04-19 05:09
Duplicate of #11001

**Closed by Chaosus** 2019-04-19 05:09 UTC
