### ISSUE TITLE
for in loop using underscore crashes editor

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#69923] opened 2022-12-11 19:16 UTC
### Godot version

v4.0.beta8.official [45cac42c0]

Using external editor Visual Code.

### System information

Windows 10

### Issue description

Using `_` as variable in a for loop crashes the editor. Also i somewhat expected that an underscore is allowed.

### Steps to reproduce

Use the code below, sometimes you have to rename the `_` underscore to something valid and back.

```
for _ in range(2):
    pass
```

### Minimal reproduction project

N/A

**Comment by cora-schallock** [comment] 2022-12-12 08:48
Hello IceflowRE, 

Short Answer: 

Since the '_' character is used in Godot to represent private properties/methods/unused variables, I'd suggest using a work around such as:
```
for _i in range(2):
    pass
```    
If I am understanding Godot's reserved keyword/ charter system, this behavior is expected as a single `_` is not allowed as a variable name.

Longer Answer:
    
When I initially tried to replicate your bug, I noticed that the editor was displaying a parser error, specifically "Expected loop variable name after "for".  

It appears that the error message is indeed from [godot's parser](https://github.com/godotengine/godot/blob/eb555d7559371963d846811260a11fb07dd72a3d/modules/gdscript/gdscript_parser.cpp) (line 1806). Looking at the code, it appears to be it expecting an "Identifier" token from the tokenizer, but because the '_' is a special charter used to denote private methods, it is treated as a separate token by the [tokenizer](https://github.com/godotengine/godot/blob/58ca3031419cacb35c530cebe68e87a4c27dde06/modules/gdscript/gdscript_tokenizer.cpp) (here in the "token_names" there is an entry for "_". Meaning that when the tokenizer sees a single underscore, it is treated as a underscore token rather than an "Identifier" token).

Hence the error message.

As for why it crashes, if you look at Godot's documentation for the for loop, it specifies "the current array element is stored in the loop variable". Since a single _ is not seen an "Identifier" the current array element can not be stored as a single underscore is not treated as a variable under the logic of godot's tokenization system.

I noticed that when I tried to declare a variable outside a loop, with the name of a single underscore (i.e. `var _ = 2`) I also see this same error message. This makes me think that the single underscore naming convention is not allowed (unlike some languages like Python).

**Comment by dalexeev** [comment] 2023-02-11 18:11
I can't reproduce the crash. `_` instead of a loop variable is currently not supported, see godotengine/godot-proposals#1282.

**Comment by YuriSizov** [comment] 2023-02-11 18:15
Closing per the comment above. Please provide an MRP and more details if the issue still happens on your end with the latest version of Godot 4.

**Closed by YuriSizov** 2023-02-11 18:15 UTC
Labels: bug, topic:gdscript, needs testing, crash

**Comment by IceflowRE** [comment] 2023-02-24 13:54
> I can't reproduce the crash. `_` instead of a loop variable is currently not supported, see [godotengine/godot-proposals#1282](https://github.com/godotengine/godot-proposals/issues/1282).

Yep there is no crash anymore!
But the code is accepted though and the script seems to be skipped. No parser error.

**Comment by dalexeev** [comment] 2023-02-25 13:36
> But the code is accepted though and the script seems to be skipped. No parser error.

![](https://user-images.githubusercontent.com/47700418/221359812-68a46dae-cfa3-45b3-89b0-687406f8b14d.png)

**Comment by IceflowRE** [comment] 2023-02-26 11:09
> > But the code is accepted though and the script seems to be skipped. No parser error.
> 
> ![](https://user-images.githubusercontent.com/47700418/221359812-68a46dae-cfa3-45b3-89b0-687406f8b14d.png)

?

I mean i can still execute it without any error.
