### ISSUE TITLE
Encrypted export HTML5 doesn't work

### ISSUE THREAD

**Issue by LionYanisse** [godotengine/godot#44791] opened 2020-12-29 10:17 UTC
**Godot version:**
3.2.3-stable

**OS/device including version:**
Windows

**Issue description:**
On 3.2.3-stable version, HTML5 export with encryption key doesn't work : there is a message "Unknown file open mode: wx+"
On 3.2.2-stable version and older, HTML5 export with encryption work like it supposed to !

**Steps to reproduce:**
Export on HTML5 with encryption key with a templated generated by using 3.2.3-stable code => export doesn't work
Export on HTML5 with encryption key with a template generated by using 3.2.2-stable code => export works !

**Comment by Calinou** [comment] 2020-12-29 10:46
> On 3.2.3-stable version, HTML5 export with encryption key doesn't work : there is a message "Unknown file open mode: wx+"

Do you get this error message when exporting the project or when attempting to run it?

With Godot 3.2.3, can you successfully export to other platforms with encryption enabled? (Also, did you recompile the HTML5 export template to use your encryption key? This is absolutely required.)

**Comment by akien-mga** [comment] 2020-12-29 11:08
This is not a regression, it's a change in Emscripten 2.0.9 and later. You likely used an older version of Emscripten for your 3.2.2 template, and it would work with 3.2.3 too.

The issue is fixed in 3.2.4 with https://github.com/godotengine/godot/commit/8d93c723f16e3a94b65ce68f91381b3b531a5ef7#diff-3aa132bdffdc765b8f64827978ea6e3f2b17d96eb08c53b02cb9b28d354c5189, you can either backport this fix or use an older Emscripten.

**Closed by akien-mga** 2020-12-29 11:08 UTC
Labels: bug, platform:html5, regression, topic:porting
