### ISSUE TITLE
Godot3_signtool error:  If param "Embed Pck" is set it  cripples the exported Windows EXE

### ISSUE THREAD

**Issue by Ramedes** [godotengine/godot#62351] opened 2022-06-23 14:03 UTC
### Godot version

3.4.stable

### System information

Win10 GLES3

### Issue description

A repeatable error with Windows signtool.exe  occurs if:

1) Someone exports the project with the param "Embed Pck"
2) A valid Microsoft Authenticode Certificate is used (*.pfx) 
3) Export Game for Windows 64-Bit (AMD64/x86_64 Arch)

But it works if the param "Embed Pck" is not set and the Godot generated *.pck file
is placed into the exported Exe folder.

The same effect occurs if no Godot3 Signing is used and the exported Godot EXE Runtime is signed by
Command line with for example:
signtool sign /f ..\mycert.pfx /t http://timestamp.sectigo.com /p xxxxx /ac ..\root.crt.pem ux.exe  (using SHA256)

The Signature added in both cases (with Godot or just with signtool exe from command prompt) is valid
but in both cases it crippled the exported Runtime Exe file.

### Steps to reproduce

1) In Export settings enable Signing
2) In Export settings enable "Embed as PCK"
3) Export a Game for Windows 64-Bit (AMD64)

**Workaround**
Not using  "Embed as PCK"
![fail](https://user-images.githubusercontent.com/74136052/175318377-81b29b43-61a0-4fd1-82e0-5cd488e7f131.png)

### Minimal reproduction project

1) In Export settings enable Signing
2) In Export settings enable "Embed as PCK"
3) Export a Game for Windows 64-Bit (AMD64)

**Comment by akien-mga** [comment] 2022-06-23 14:07
Duplicate of #32310, fixed in 3.5.

**Closed by akien-mga** 2022-06-23 14:07 UTC

**Comment by Ramedes** [comment] 2022-06-23 14:20
Excellent, thanks
