### ISSUE TITLE
Can't connect more than one array to a Node signal

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#97044] opened 2024-09-15 15:42 UTC
### Tested versions

4.3.stable

### System information

Windows 11 - Godot 4.3.stable - Forward+

### Issue description

I want to connect a signal of a node to the erase function of many arrays, when I try to do that an error appears telling me that the signal is already connected

### Steps to reproduce

play the MRP and you'll see, the project is very simple, it has only 2 scripts

### Minimal reproduction project (MRP)

[minimal-reproduction-project.zip](https://github.com/user-attachments/files/17006353/minimal-reproduction-project.zip)

**Comment by ghmart** [comment] 2024-09-15 16:08
Maybe using  "CONNECT_REFERENCE_COUNTED" flag will help:
~~~
parent.died.connect(arr_2.erase.bind(parent), Object.CONNECT_REFERENCE_COUNTED)
~~~

**Comment by Castro1709** [comment] 2024-09-15 16:09
But that's because the signal "died" is already connected to the array method, a signal can only be connect to a method once, that's why you are getting the error, if you want you "died" signal to call the method twice, each time with a different arr I recommend you this code:
`
func _ready():
	parent.died.connect(func () -> void:
		arr.erase(parent)
		arr_2.erase(parent)
		)
`
I don't think this is a bug...

**Comment by AThousandShips** [comment] 2024-09-15 16:12
Not a bug indeed, when connecting the bound arguments are ignored and only the method and object are considered, so you can't connect the same method of the same object to the same signal without the flag

Closing as not a bug, please ask for more support in the other [community channels](https://godotengine.org/community/)

**Closed by AThousandShips** 2024-09-15 16:12 UTC
