### ISSUE TITLE
[WIP] GLES2 error: initialize: Directional shadow framebuffer status invalid on macOS

### ISSUE THREAD

**Issue by follower** [godotengine/godot#33739] opened 2019-11-19 15:59 UTC
{ [WIP Report] See: #26570 for original details. Created issue as requested in https://github.com/godotengine/godot/pull/31259#issuecomment-551838962 }

**Godot version:** v3.1.2-rc1_osx.64

**OS/device including version:** Mac

**Issue description:**

The shadows in the editor & application are incorrect and display "garbage" which seems like uninitialized memory--and changes over time.

When the application is run the following error is displayed in Error console:

```
E 0:00:00:0266   Directional shadow framebuffer status invalid
  <C Source>     drivers/gles2/rasterizer_scene_gles2.cpp:3378 @ initialize()
```

* Incorrect shadows in editor: ![godot-directional-shadow-buffer-bug--editor](https://user-images.githubusercontent.com/189962/69162296-4e2c3d00-0b51-11ea-8c3e-c5356a405bfe.png)

* Incorrect shadows in application: ![godot-directional-shadow-buffer-bug--app](https://user-images.githubusercontent.com/189962/69162388-74ea7380-0b51-11ea-9e3b-cf66c70274ab.png)

**Steps to reproduce:**

[TODO]

**Minimal reproduction project:**

[TODO]

Note:

 * This *doesn't* occur in 3.2 beta 1.

 * *Updated:* Possibly related comment regarding underlying issue: https://github.com/godotengine/godot/pull/31259#issuecomment-532937006

**Comment by clayjohn** [comment] 2019-11-19 16:36
Looks like #31259 just needs to be cherrypicked.

**Comment by akien-mga** [comment] 2019-12-19 08:50
> Created issue as requested in [#31259 (comment)](https://github.com/godotengine/godot/pull/31259#issuecomment-551838962)

What I was referring to is a new issue for the 3.2 branch to cater to @endragor's comment in https://github.com/godotengine/godot/pull/31259#issuecomment-532937006.

This WIP report seems to be a duplicate of #26570 which is already fixed?

**Closed** 2019-12-19 08:51 UTC
Labels: bug, platform:ios, topic:porting, topic:rendering
