### ISSUE TITLE
[3.5] Project doesnt automatically save when exporting

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#58982] opened 2022-03-10 12:03 UTC
### Godot version

v3.5.beta.custom_build [b81251d4a]

### System information

Windows 10

### Issue description

* My build: https://github.com/godotengine/godot/pull/58900

When you modify a script and click Project-> Export, Godot doesnt save the changes!!!!

### Steps to reproduce

* Create a Project
* Create a script
* Export
* Modify script without saving
* Export

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2022-03-10 15:53
Duplicate of https://github.com/godotengine/godot-proposals/issues/3605.

**Closed by Calinou** 2022-03-10 15:53 UTC
Labels: enhancement, topic:editor, topic:export
