### ISSUE TITLE
Rotate tool has deadzone on X axis

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#56582] opened 2022-01-07 03:25 UTC
### Godot version

4.0.dev.custom_build.2c7fcdd7f

### System information

Linux 5.15.10-arch1-1

### Issue description

When using the rotate tool and moving the mouse to rotate around the X axis, there is a deadzone where the transform doesn't change and mouse movements don't seem to be registered.

https://user-images.githubusercontent.com/2496231/148322454-e8aa5115-bec2-42f3-ac09-b625a172ed18.mp4

### Steps to reproduce

1. Add a MeshInstance
2. Activate the rotate tool
3. Grab the X (red) handle
4. Move the mouse in a circle around the object in the 3D view

**Comment by TokageItLab** [comment] 2022-01-07 05:39
Gizmo was recently updated, and I thought that might have caused the regression, but this problem seems to be unrelated as it occurs whether it is merged or not.

From the looks of it, it seems like the dead zone is created by distance. In other words, if the rotation axis is close enough to the object, it will rotate properly. My guess is that something invisible, like the YZ plane, is causing the dead zone.

**Comment by TokageItLab** [comment] 2022-01-07 09:10
@akien-mga It's not regression, there is same issue in 3.x.

**Comment by Logharaa** [comment] 2022-02-04 12:11
I confirm #56946 fixes the issue

**Closed** 2022-02-08 20:13 UTC
Labels: bug, topic:editor, topic:3d
