### ISSUE TITLE
Some sliders not loosing focus on mouse release + mouse cursor offset when they loose focus (DisplayServer regression)

### ISSUE THREAD

**Issue by Logharaa** [godotengine/godot#57446] opened 2022-01-30 13:14 UTC
### Godot version

4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, 2560x1440 display (125% scaling)

### Issue description

On some specific sliders, like the ones in Settings or in Preview environment, releasing the mouse click after changing the value of the slider does not make it loose focus, we are "stuck" in it.
I forced the loss of focus by clicking the "Enter" key, but then the mouse cursor is offset from the slider :

![SliderBug](https://user-images.githubusercontent.com/38374449/151701005-3b41fc73-2293-46bb-afac-13db1136e429.gif)

Sliders that are in the inspector do not have this problem though, the loss of focus is effective on mouse release and there is no cursor offset.

### Steps to reproduce

1. Create Root Node: 3D Scene
2. Edit Sun and Environment settings
3. Use a slider

**Comment by Calinou** [comment] 2022-01-30 21:30
Duplicate of https://github.com/godotengine/godot/issues/57383.

**Closed by Calinou** 2022-01-30 21:30 UTC
Labels: bug, platform:windows, topic:editor, topic:porting, regression
