### ISSUE TITLE
Button height can't be shrunk down past 20 pixels

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25807] opened 2019-02-12 02:46 UTC
Godot version: 3.0.6

buttons cannot be resized less than 16x20 when they have a texture style margin of 3,3,3,3.
I would think that all ui widgets can be resized down to 1x1 pixel no matter the 9 slice size

1. create a base button
2. add a normal texture style to it
3. add specify a 9 slice of 3,3,3,3
4. try to scale it down past 16x16

[9 Slice and ui size restrictions.zip](https://github.com/godotengine/godot/files/2853896/9.Slice.and.ui.size.restrictions.zip)

I have noticed this with other widgets too.
it seems that they can't be shrunk down past their default size or something

**Comment by smallporgies** [comment] 2019-02-13 23:15
In 3.1 I can't scale it down past 6x20 strangely enough, I dug into the code and noticed the font is one of the things that contributes to the minimum size of a control. By overriding the default font on the control with a blank one I can shrink it down to 0x1.

**Comment by Shadowblitz16** [comment] 2019-02-14 02:53
see fonts shouldn't affect the scale of the control if they are too small the text should either flood over the control of be clipped by it if clip is enabled.

same with icons

**Comment by KoBeWi** [comment] 2020-11-20 20:15
Well, this is intended behavior not a bug, so closing. It's like saying Label should be able to be shrunk below text size. It doesn't sound useful.

> I would think that all ui widgets can be resized down to 1x1 pixel no matter the 9 slice size

You can open a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by Shadowblitz16** [comment] 2020-11-21 19:37
@KoBeWi This happens even if there is plenty of space for it to shrink without clipping text

also if clip text is enabled then it should be posiable

**Comment by KoBeWi** [comment] 2020-11-21 20:15
> This happens even if there is plenty of space for it to shrink without clipping text

That's a problem with font height actually. Compare with labels:
![image](https://user-images.githubusercontent.com/2223172/99886571-dac67b00-2c3d-11eb-974b-ec916a3f89bf.png)
Both have minimum height, equal to the height of the font.

> also if clip text is enabled then it should be posiable

This is arguable. It's more useful if only width gets clipped, because even if button is e.g. half width of the text, you can still read it (with half height, not so much).

Well, but the doc doesn't state that, so let's say it's a valid issue. Either we should mention that only width gets clipped or change the behavior. The relevant code is here:
https://github.com/godotengine/godot/blob/48049b8d9e3830ddea5c6844997d928871c16d27/scene/gui/button.cpp#L36-L60

**Closed** 2024-12-11 23:41 UTC
Labels: bug, discussion, topic:gui
