### ISSUE TITLE
Suggestion: Allow AnimatedSprite to play in reverse (or introduce a method to do so)

### ISSUE THREAD

**Issue by exts** [godotengine/godot#20777] opened 2018-08-07 00:05 UTC
**Godot version:**
Master

**OS/device including version:**
All

**Issue description:**
Currently if you have an animated sprite that sits down, the best way to reverse that animation is to create a new named animation with the sprites in reverse order and to play that specific animation. 

Wouldn't it be easier if we had a new parameter or method to just play the animation backwards? `$AnimatedSprite.play_reversed()`

**Comment by vnen** [comment] 2018-08-07 03:28
Duplicate of #17787

**Closed by vnen** 2018-08-07 03:28 UTC
Labels: feature proposal, topic:core
