### ISSUE TITLE
Color Picker blanks the screen out

### ISSUE THREAD

**Issue by meatrack** [godotengine/godot#74955] opened 2023-03-15 19:48 UTC
### Godot version

4.0

### System information

Windows 11  Processor	Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz, 3096 Mhz, 8 Core(s), 16 Logical Processor(s) Name	Intel(R) UHD Graphics 630

### Issue description

When selecting the dropper button when picking a color, the screen goes black.

### Steps to reproduce

Select the albedo for  changing the color on mesh materiel for example, and opening up the color picker, when you click the dropper icon, the screen goes black.

### Minimal reproduction project

[ExampleProject.zip](https://github.com/godotengine/godot/files/10984008/ExampleProject.zip)

**Comment by KoBeWi** [comment] 2023-03-15 20:02
Duplicate of #74048

**Closed by KoBeWi** 2023-03-15 20:02 UTC
