### ISSUE TITLE
Export only contains .import files and not the source files

### ISSUE THREAD

**Issue by JonnyTech** [godotengine/godot#77044] opened 2023-05-13 21:05 UTC
### Godot version

4.0.2, 4.0.3 rc1

### System information

Debian

### Issue description

Images added to my project are not accessible once the project is exported - but the associated .import files are.

### Steps to reproduce

Add image files to the project ie: /images/image.svg
Access the images while running the editor is ok
Export the project - make sure to include all resources
The images are not available from the export as res://images/ files
Listing the res:// folder shows the .import files exist there

### Minimal reproduction project

[error.zip](https://github.com/godotengine/godot/files/11470577/error.zip)

**Comment by JonnyTech** [comment] 2023-05-13 21:13
Also, please note that there is an issue with Godot's .svg import - the stars in the included flags images of eu.svg and us.svg are not rendered correctly.
![godot](https://github.com/godotengine/godot/assets/3584732/db744227-ab0f-4dac-9af4-b081d007e8dd)
![image](https://github.com/godotengine/godot/assets/3584732/c1e82a8e-db55-4a8d-a416-0ac4070361ff)

**Comment by Calinou** [comment] 2023-05-14 02:33
- Duplicate of https://github.com/godotengine/godot/issues/25672 (same cause).

Please open a separate issue for the SVG rendering, but note that is most likely a big within ThorVG (the linrary used to rasterize SVGs on import in Godot 4).

**Closed by Calinou** 2023-05-14 02:33 UTC
