### ISSUE TITLE
Nonstop errors on breakpoint: getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#46388] opened 2021-02-24 16:46 UTC
**Godot version:**
`3.2.4 RC 2` and `3.2.4 RC 3`

**OS/device including version:**
Windows 10, GLES3,  `GeForce GTX 1050 Ti/PCIe/SSE2`

**Issue description:**
Under certain conditions, (not sure exactly which), I get spammed with this error:
```
E 0:00:12.010   getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:160 @ getornull()
```

**Steps to reproduce:**
Do as shown in [this example video](https://user-images.githubusercontent.com/60025044/109033912-b8089000-768c-11eb-8e44-20f294ee49ea.mp4).

1. Run game. 
2. Select `Move`
3. Move next to demon.
4. Select `Attack`
5. Watch errors pile up when the code hits a breakpoint

```
Controls:
- Arrow keys: Move cursor
- Enter: Select menu option / Select cell to move character to
- Escape: Quit
```

**Minimal reproduction project:**
[getornull error.zip](https://github.com/godotengine/godot/files/6037471/getornull.error.zip)

**Comment by Calinou** [comment] 2021-02-24 18:22
Duplicate of https://github.com/godotengine/godot/issues/38229.

**Closed by Calinou** 2021-02-24 18:22 UTC
