### ISSUE TITLE
[Feature] Window minimum size

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21199] opened 2018-08-19 20:54 UTC
There should be an option in the project settings to set the minimum window size.
Not there in **v3.0.5-stable**

If anyone needs it, I coded this workaround. It works, but only when the user finishes resizing (releases the mouse).
In your __on_screen_resize_ method:
<code>

	if window_size.x < MinX || window_size.y < MinY:
		yield(get_tree(), "idle_frame")
		OS.window_size = Vector2(MinX, MinY)
</code>

**Comment by YeldhamDev** [comment] 2018-08-19 21:00
Related to https://github.com/godotengine/godot/issues/14806.

**Comment by char0xff** [comment] 2018-08-19 21:05
I should improve my searching skills in GitHub. How do I perform a search inside the issue title?

**Comment by YeldhamDev** [comment] 2018-08-19 23:16
@char0xff There's a search bar inside the "Issues" tab, if that's what you're talking about:
![screenshot at 2018-08-19 20-15-21](https://user-images.githubusercontent.com/30739239/44314231-bb9c6b80-a3ec-11e8-9087-a338a4c696b9.png)

**Comment by char0xff** [comment] 2018-08-20 06:28
No I meant the filter, but I've found it, it's:
_in:title_

**Comment by Chaosus** [comment] 2019-03-04 17:52
Ah.. its a duplicate.. Closed as duplicate of #14806

**Closed by Chaosus** 2019-03-04 17:52 UTC
Labels: enhancement, topic:core
