### ISSUE TITLE
EditorHelp formatting issues when viewing class reference document in Editor.

### ISSUE THREAD

**Issue by Zentrophy** [godotengine/godot#78179] opened 2023-06-13 11:12 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  I have encountered formatting issues of the text for EditorHelp/class reference documents in the ScriptEditor.  Unfortunately I can't reliably trigger the issue because it does seem somewhat random.  Sometimes when I view a DOC, the text is in one long vertical line as though the control (RichTextLabel) hasn't correctly determined the size available to it.  If I scroll further down the document, and then move to other documents, etc. and then back to the one that has been scrolled, the formatting may be fine from that point to the end, but prior to the initial scroll point is the thin vertical line of text.  Sometimes it happens with a DOC that's been newly opened, or one that I have visited before in the Editor run.

  If I jiggle the resizing border of the panel, the formatting fixes itself, but it may have to be done multiple times in the same document as you scroll around.

### Steps to reproduce

  Open a DOC, but other than that I don't know.  It might happen.  It might not.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-06-13 11:13
* Duplicate of #77558

**Closed by AThousandShips** 2023-06-13 11:13 UTC
Labels: bug, topic:editor
