### ISSUE TITLE
Crash when renaming animation StateMachine inside of an StateMachine created with the Group button

### ISSUE THREAD

**Issue by OlliO6** [godotengine/godot#70678] opened 2022-12-28 20:59 UTC
### Godot version

4.0.beta10.mono

### System information

Windows 11

### Issue description

There is weird behaviour with a crash sometimes when renaming an `AnimationNodeStateMachine` that lives inside another StateMachine and was previously created using the `Group Selected Node(s)` button.

![GodotCrash](https://user-images.githubusercontent.com/104021024/209870450-c799a7d9-a6f9-4285-b7ef-b24e27bb3c8b.gif)

### Steps to reproduce

- Add a `AnimationTree` with a `AnimationNodeStateMachine` as the root.
- Add some `AnimationNodes` to that StateMachine.
- Select these Nodes and press the `Group Selected Node(s)` button.
- Rename the resulting StateMachine.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-12-29 21:33
Duplicate of https://github.com/godotengine/godot/issues/58822.

**Closed by Calinou** 2022-12-29 21:33 UTC

**Comment by OlliO6** [comment] 2022-12-30 00:08
Ok, I for some reason don't get a crash anymore, instead this happens.
![image](https://user-images.githubusercontent.com/104021024/210022667-6e239050-d1ea-4128-a4d4-7a191d09f871.png)

**Comment by TokageItLab** [comment] 2022-12-31 10:19
@Calinou Does this and #58822 crashes are caused by the same reason? I am puzzled as I cannot reproduce #58822...
