### ISSUE TITLE
More TestObjects?

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5764] opened 2016-07-18 00:11 UTC
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
Could we get more primitives like the testcube? Like cylinder, sphere, capsule, plane, and quad?

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment] 2016-07-18 05:11
Sorry, duplicate of #1381

**Closed by bojidar-bg** 2016-07-18 05:11 UTC
