### ISSUE TITLE
CollisionObject2D nodes inside CanvasLayer with FollowViewport enabled are not affected by movement

### ISSUE THREAD

**Issue by adamz5k** [godotengine/godot#35052] opened 2020-01-12 19:47 UTC
**Godot version:** 3.2 Beta 6

**OS/device including version:** Windows 64bit

**Issue description:** `CollisionObject2D`s inside a `CanvasLayer` do not take the layer offset/position into account when FollowViewport is enabled in the `CanvasLayer`

**Steps to reproduce:**
- Create a 2D scene with: 
-- `Camera2D` (current with movement)
-- `CanvasLayer` with FollowViewport enabled. (changing scale doesn't seem to matter)
-- `CollisionObject2D` (like `Area2D`) with a `CollisionShape2D` with a connected signal (I used mouse entered/exited - easiest to see the issue with)
-- Turn on visible collision shapes
Note that the `CollisionShape2D` appears to move when the camera moves, but the area on the screen where the collision shape registers collisions remains the same.

**Minimal reproduction project:**
[FollowViewportIssue.zip](https://github.com/godotengine/godot/files/4051269/FollowViewportIssue.zip)

**Comment by cgbeutler** [comment] 2020-02-12 21:22
This may be related to: #35965 ???  Could be wrong, but they both deal with matrix space transforms maybe not being applied right.

**Comment by KoBeWi** [comment] 2020-12-24 00:08
Still valid in 3.2.4 beta4

**Comment by lawand** [comment] 2022-03-18 21:48
still happening in 3.4.3.stable

**Comment by Sauermann** [comment] 2022-11-10 20:13
I verified, that this is a duplicate of #35965
and that it gets fixed in V4 by #59682

**Comment by KoBeWi** [comment] 2022-11-22 19:11
I tested #https://github.com/godotengine/godot/pull/59682 and it does not seem to fix the issue.

**Comment by Sauermann** [comment] 2022-11-22 19:30
@KoBeWi This MRP also makes #64652 visible.
 If you apply #59682 together with #66076, you will see, that this MRP works as expected.

**Comment by akien-mga** [comment] 2022-11-22 21:26
Duplicate of #35965 and #64652.

**Closed by akien-mga** 2022-11-22 21:26 UTC
Labels: bug, confirmed, topic:physics
