### ISSUE TITLE
CSG causing game hard crash after some time change parent visibility

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#27393] opened 2019-03-25 04:24 UTC
**Godot version:** 3.1 stable

**OS/device including version:** Ubuntu 18.04 64 bit driver GLES 2

**Issue description:** CSG causing game hard crash after multiple time change parent visibility

**Steps to reproduce:** run game files below this error will accumulate in debugger error until game crash
E 0:00:01:0956   Condition ' !n ' is true.
  <C Source>     modules/csg/csg_shape.cpp:285 @ _update_shape()

**Minimal reproduction project:**
[csg_bug_hard_crash.zip](https://github.com/godotengine/godot/files/3001480/csg_bug_hard_crash.zip)

**Comment by qarmin** [comment] 2019-03-25 12:12
Can't reproduce on ubuntu 18.04 Nvidia GTX 970 a53645e after 1,5 min testing

**Comment by fian46** [comment] 2019-03-25 12:31
that is the funny part on my test sometimes it crash sometime it is not.

**Comment by bojidar-bg** [comment] 2019-03-25 18:43
I ran the reproduction project 15 times (in groups of 5) under GDB, around 2-3 minutes every run. Couldn't reproduce.

Can you try to either capture a crash under [`rr`](https://rr-project.org/), or capture a backtrace under `gdb`?

**Comment by fian46** [comment] 2019-03-25 21:43
to be honest this crash image is not produced by the project i attach. the project i attach is part of my game. it the last scene i add and the crash started so i assume that the cause. after i inspect it also contains this 2 error

E 0:01:56:0527   Condition ' context == __null ' is true.
  <C Source>     modules/websocket/lws_client.h:45 @ _lws_poll()
  <Stack Trace>  WS.gd:183 @ _process()

E 0:01:56:0573   Too many errors! 67 errors were dropped.
  <C Source>     :73701936

nothing else strange on console or debugger

![weird](https://user-images.githubusercontent.com/13792627/54955831-5fed1e80-4f89-11e9-9998-9a27fd8e45df.gif)

**Comment by bojidar-bg** [comment] 2019-03-25 23:03
@fian46 Try to see if the minimal reproduction project you linked to the issue crashes as well. If it does, try to get it crash while running under `gdb`, and take a stacktrace from there.

**Comment by fian46** [comment] 2019-03-25 23:07
what you do mean running under gdb ? is it just hit play button or export debug ?

**Comment by bojidar-bg** [comment] 2019-03-26 10:00
> The GNU Debugger (GDB) is a portable debugger that runs on many Unix-like systems and works for many programming languages, including Ada, C, C++, Objective-C, Free Pascal, Fortran, Go and partially others – [Wikipedia](https://en.wikipedia.org/wiki/GNU_Debugger)

Basically, to run the game in GDB:
1. Open a terminal and `cd` to the directory of the game. (The one with `project.godot`)
2. Run `gdb ./path/to/godot.x11.tools`
3. It will load some debugging information. When it is done, write `run` to start the game.
4. Make it crash, somehow.
5. When it crashes, type `bt` or `backtrace` to get information of where the crash is happening exactly.
6. Post the results.

In case the editor is crashing, and not just the game, do the same, but with `run -e` on step 3.
In case the game is not crashing under GDB, try running it directly from the project manager, and see if it still crashes.
In any case, you can probably try to run Godot from a terminal, so you can see what is being printed to stdout (which also includes a stacktrace, even if it is a bit less useful that GDB's).

**Comment by bojidar-bg** [comment] 2019-03-26 10:09
> to be honest this crash image is not produced by the project i attach. the project i attach is part of my game. it the last scene i add and the crash started so i assume that the cause. after i inspect it also contains this 2 error before crash
> ```
> E 0:01:56:0527 Condition ' context == __null ' is true.
> modules/websocket/lws_client.h:45 @ _lws_poll()
> WS.gd:183 @ _process()
> 
> E 0:01:56:0573 Too many errors! 67 errors were dropped.
> :73701936
> ```

To be honest, I don't see how the linked minimal reproduction project can cause an error in `modules/websocket`, given it does not use websockets. Are you sure the crash can be observed in it?

**Comment by fian46** [comment] 2019-03-26 10:46
ok i will test my game with it. the crash actually happened im my game not the reproduction minimal project. i just assume it must be that scene since it spam tons of error.

**Comment by fian46** [comment] 2019-03-26 11:47
false alarm i cannot make it crash again 😂. i think we can close this issue. thank you for helping @bojidar-bg

**Comment by bojidar-bg** [comment] 2019-03-26 12:20
Ok, closing as unreproducible. If you manage to crash it again, it might be reopened :smiley: .

**Closed by bojidar-bg** 2019-03-26 12:20 UTC
Labels: bug, needs testing, topic:core
