### ISSUE TITLE
TileSet script _is_tile_bound(...) does not get called in the editor when update_bitmask_region(...) is called

### ISSUE THREAD

**Issue by thorlucas** [godotengine/godot#38285] opened 2020-04-28 07:17 UTC
**Godot version:**

v3.2.1 stabel.mono.official

**OS/device including version:**

macOS Catalina v10.15.4

**Issue description:**

If you add a script to a `TileSet`, the `_is_tile_bound(...)` method (or presumably any methods) are not called, even when manually calling `update_bitmask_region(...)` via an editor tool. This makes it impossible to show custom bindings in the editor, which can impede level design.

**Steps to reproduce:**

Attach a `TileSet` script, and override the function `_is_tile_bound(...)`. Create an editor tool that will call `update_bitmask_region(...)` on the `TileMap` that contains this `TileSet`. Observe that `_is_tile_bound(...)` is not called when in the editor, but is called when running the game.

**Minimal reproduction project:**

See above. It's really quite a simple issue to reproduce.

**Comment by bojidar-bg** [comment] 2020-04-28 08:14
Does the TileSet script have tool mode on? If it doesn't, its functions cannot be called within the editor.

I tried reproducing with the above steps: it worked when adding `tool` to the TileSet script.

**Comment by thorlucas** [comment] 2020-04-28 18:07
Ah, this is the issue — the TileSet script needs `[Tool]` as well, not only the caller.

**Comment by Calinou** [comment] 2020-10-09 11:31
@thorlucas Have you found a solution to this issue?

**Comment by kleonc** [comment] 2021-08-07 18:48
@Calinou reread their comments. :wink: As pointed out, script needs to be a `tool` to run in the editor.
Not a bug.

**Comment by Calinou** [comment] 2021-08-07 22:49
Closing per @kleonc's comment.

**Closed by Calinou** 2021-08-07 22:49 UTC
Labels: bug, topic:core, topic:2d
