### ISSUE TITLE
Godot 4: Beta 2 - Custom Resource Exported Arrays and Dictionaries not showing default values in Inspector.

### ISSUE THREAD

**Issue by dmbro** [godotengine/godot#66907] opened 2022-10-04 21:40 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

When exporting Arrays and Dictionaries in custom Resources, the Inspector doesn't provide the default values specified in code and instead sets the properties to null. 

![image](https://user-images.githubusercontent.com/25791994/193935731-ea0e8469-71f1-41d2-a3b2-454222084dd3.png)
![image](https://user-images.githubusercontent.com/25791994/193935767-fe229855-fc53-4e83-8d7f-629c2cf98bab.png)

### Steps to reproduce

- Create a new script extending ```Resource```
- Create an exported Array or Dictionary and set a value to it.
- Create a new ```Resource``` file (.tres or .res) using the new script.
- View the custom resource's properties in the Inspector.

### Minimal reproduction project

[ResourceTest.zip](https://github.com/godotengine/godot/files/9711017/ResourceTest.zip)

**Comment by Calinou** [comment] 2022-10-04 22:23
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-10-04 22:23 UTC
