### ISSUE TITLE
input doesn't work in x11 (64bit) export

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#10929] opened 2017-09-03 16:45 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Kubuntu 17.04, Godot git master, Geforce 840m 

(templates are same version as godot)

**Issue description:**
when exporting the project game starts fine, and seems to be running (animations work) but input doesn't do anything. keyboard, or gamepad doesn't seem to respond.  

**Steps to reproduce:**
export to linux_x11_64, run the project, try to control the character.

**Comment by vnen** [comment] 2017-09-04 03:38
Duplicate of #9472.

**Closed by vnen** 2017-09-04 03:38 UTC
