### ISSUE TITLE
The sound player does not reset when a playback ends

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#41792] opened 2020-09-05 18:07 UTC
**Godot version:**

3.2.3 RC5 Mono

**OS/device including version:**

win10 64 home
nvidia gt440

**Issue description:**

When you play a sound and the playback ends, the player does not allow a new playback by pressing the PLAY button. It is necessary to press the STOP button even though the playback has already ended. It is understood that the STOP button is to stop something that is playing, not to stop something that has already finished.

**Steps to reproduce:**
Add a streamplayer node
Add any sound
Play sound on Godot's built-in player
Wait for the sound to finish playing
Press PLAY again.
You don't get a new playback, you need to press STOP.

![bug](https://user-images.githubusercontent.com/19652075/92310986-5b68ca00-efb3-11ea-802a-d64e4b91bdbe.gif)

**Minimal reproduction project:**

It is not necessary, just follow the steps to reproduce the error.

**Comment by FlashDaggerX** [comment] 2020-09-16 16:46
This issue is also present in master. See the pull request above.

**Comment by Calinou** [comment] 2021-03-20 20:16
Duplicate of https://github.com/godotengine/godot/issues/36816.

**Closed by Calinou** 2021-03-20 20:16 UTC
Labels: bug, topic:audio, topic:editor
