### ISSUE TITLE
You cannot change the "Handle Mode" of a Bezier Track Key in the inspector

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#74302] opened 2023-03-03 14:34 UTC
### Godot version

4.0.stable

### System information

Windows 10, GTX 980 Ti, Vulkan Forward+

### Issue description

If you select an animation key in a bezier animation, you cannot change it's Handle Mode from the inspector, it works to do it by right clicking on it though.

https://user-images.githubusercontent.com/4955051/222747210-8a4ebff9-f501-4018-b2f9-a135102864e4.mp4

### Steps to reproduce

1. Create an Animation Player
2. Key any value as a Bezier key
3. Go to the Bezier editor and select the key
4. Try changing the handle type in the inspector

### Minimal reproduction project

NA

**Comment by timothyqiu** [comment] 2023-03-03 16:05
Duplicate of #74224

**Closed by timothyqiu** 2023-03-03 16:05 UTC
