### ISSUE TITLE
Euler sequences, Quats, and DCMs

### ISSUE THREAD

**Issue by ericstoneking** [godotengine/godot#19600] opened 2018-06-16 13:32 UTC
**Godot version:**
3.0.2.stable.official

**OS/device including version:**
OSX and Win10 (unlikely to be a factor)

**Issue description:**
Using the inspector to transform a spatial node, rotation did not behave as expected.  This could be just a failure of documentation, as the rotation sequence is not apparent.  But I have a long-term objective that would be served by a more general solution than just puzzling out which Euler sequence is in current use.  Maybe a more general solution would be of use to others as well.

**Steps to reproduce:**
Using a mesh instance with geometry that makes rotations traceable (I used a 1:4:9 brick), I experimented with rotations, trying to discern whether the rotation sequence was a "Body" (intrinsic)
sequence or a "Space" (extrinsic) one, and what order the rotations were done in.

Rotating 90 deg about Z, then 90 deg about Y, then 90 deg about X, the last rotation was neither about Body X nor Space X.

Rotating 90 deg about X, then 90 deg about Y, then 90 deg about Z, the second rotation looked like a Space rotation, and the third looked like a Body rotation.

I conclude that the rotation sequence used is not ZYX nor XYZ.  It is not apparent from the inspector nor the Transform class documentation what sequence is used.  Rather than go through all possible sequences to find the one being used, I would like to contribute code to use any sequence desired by the user.

I am new to Godot.  I would like to use it as a rendering engine for a long-standing simulation project of mine.  It would improve my workflow if I could explicitly choose the rotation sequence in the Inspector and (probably) also in GDscript.  The attachment [DCMsForGodot.txt](https://github.com/godotengine/godot/files/2108170/DCMsForGodot.txt) is a set of C routines for converting from Euler angles (all Body-3 and Body-2 sequences) to direction cosine matrices (DCMs) and back, and also from DCMs to quaternions and back.   Would anyone like to adapt and incorporate them?

Thanks,
-Eric

**Comment by groud** [comment] 2018-06-16 14:36
Duplicate of #9782

**Comment by tagcup** [comment] 2018-06-16 18:08
Godot uses YXZ BTW (this is documented in the [doc on rotations](http://docs.godotengine.org/en/3.0/tutorials/math/rotations.html) which will be removed soon because some people think it's not a good fit, but should be fine since it's also documented in Basis docs), and the convention is Y is "up" and ground is the XZ plane

**Comment by ericstoneking** [comment] 2018-06-16 19:04
Thanks for clueing me in.  My primary application is spacecraft in orbit, though.  Having a full set of Euler sequence options would help me handle other conventions for "up", of which there are a few. ;-)

I have gathered that y'all aren't keen on Euler angles.  I heartily agree that they have their limits.  But I do use them regularly for user input/output (and gimballed joints).  Being able to see and set the sequence in the inspector would give me flexibility that I promise(!) I would use.

A more modest proposal, whether or not you care to adopt multiple Euler sequences.  As it stands, *the* sequence is YXZ, but in the inspector the angles are laid out in XYZ order.  Were they labeled in YXZ order, I reckon I'd have figured out the Euler sequence on my own.  And if you do adopt all the sequences as I propose, then it is important to point out to the user that the three angles are listed in order of rotation, not in XYZ order.  The "Body-2" (aka proper Euler) sequences only use two axes anyway, like XYX or ZXZ.

**Comment by tagcup** [comment] 2018-06-16 19:48
BTW, rotations are always stored in matrix representation (or DCM, if you prefer; to me that's just the fundamental representation of SO(3), but of course you equivalently can think of the columns as basis vectors of the new frame giving you "direction cosines") when using `Basis`, and as a quaternion (Spin(3) representation) when using `Quat`.

Euler angles themselves are never stored.

**Comment by ericstoneking** [comment] 2018-06-16 19:50
Thanks for the link to the rotation documentation.  A little long on theory, lol.  

If the inspector improvement is in the pipeline, I can abide peaceably.  There are a few other things about this engine that I need to learn, too. :-)

I got "proper" Euler jargon off of wikipedia.  I call all 24 sequences Euler angles in conversation, and only get into the Body/Space-2/3 when I need to.

**Comment by tagcup** [comment] 2018-06-16 19:55
> A little long on theory, lol.

That's pretty short if you consider it talk not just 3D rotations in Euclidian space but rather Lie groups in general (which is necessary because that what it takes to *properly* explain why quaternions work for 3D rotations: the fact that Spin(3) is a double cover of SO(3)).

**Comment by ericstoneking** [comment] 2018-06-17 11:33
ROFL.  We should take this conversation offline.  If it hasn't already drifted off-topic, it's about to :-)

**Comment by aaronfranke** [comment] 2019-11-15 22:15
Is there anything else in this issue that wasn't already discussed in https://github.com/godotengine/godot/issues/9782?

**Comment by Calinou** [comment] 2020-04-17 20:09
I think the rest was covered in #9782 and the current documentation about rotations, so this can be closed.

**Closed by Calinou** 2020-04-17 20:09 UTC
Labels: discussion, documentation, enhancement
