### ISSUE TITLE
Gameplay entered/exited signals and notification issues

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#56494] opened 2022-01-04 21:00 UTC
### Godot version

3.4.2 stable

### System information

OS: Arch Linux, CPU: Ryzen 5, GUP: RX 480

### Issue description

There are two maybe related issues with gameplay entered/exited signals and notifications.

- Notifications seem just never to work.
- Signals work, but they don't if there is an exterior room.

### Steps to reproduce

I have attached a minimal reproduction project with a roaming mesh instance that moves between two rooms. The print statements for notifications are never executed. The print statements for signals are not executed, but if the ExteriorRoom room group is deleted they will be triggered.

Note that I have not used any portals, but I assume this should work regardless. I have portals in my project, and I get the very same issue.

### Minimal reproduction project

[roaming_gamplay_callback_issue.zip](https://github.com/godotengine/godot/files/7810380/roaming_gamplay_callback_issue.zip)

**Comment by Calinou** [comment] 2022-01-04 21:16
cc @lawnjelly

**Comment by lawnjelly** [comment] 2022-01-05 08:30
After a bit of debugging, you may be a little embarrassed, but the problem is you are moving your test box in the wrong direction. :grinning: 

![rooms](https://user-images.githubusercontent.com/21999379/148184403-ea29091d-6b58-43e3-bfe4-e19961e3e724.png)

If you look at your situation, you have an exterior room (0), a room that the camera is in on the left (1) and a room that the box starts in (2).

In order to enter gameplay, the box from room (2) has to enter room (1) where the camera is, as there are no portals so it operates only on the rooms that objects are within. For this to happen the box has to move _left_ in the diagram and x must be decreased, however the script is setup so that the x coordinate _increases_ with each frame. Thus the box moves around of room 2 into room 0, then off to infinity, but never enters room 1.

The reason it appears to work when you delete the exterior room is that once the box moves to the right into "no man's land", I can't remember exactly what happens but it may pick some default room like zero, which may coincidentally be the one in which the camera is.

If you change the script to move the box correctly to the left, it works. :+1: 

On the plus side though this project did show up that #37626 is spamming warnings in some situations. I did mention at the time I wasn't sure that warning PR was a good idea.

**Comment by lawnjelly** [comment] 2022-01-05 08:31
Closing as this seems to be a problem in the MRP rather than an engine bug.

**Comment by m4nu3lf** [comment] 2022-01-05 12:58
@lawnjelly I was convinced to have reproduced the issue in my main project. Now I managed to find the root cause of the issue in my main project though.
The problem there is that I'm using the signals gameplay entered/exited on a visibility notifier, but the visibility notifier, while it gets notifications it doesn't trigger signals. Is this intentional?

**Comment by lawnjelly** [comment] 2022-01-05 13:36
Ah yes this may be true.

Having a look, it looks like `VisibilityNotifier` will only receives Notifications from the gameplay monitor, and not signals (no matter your project setting). This is because in most cases users will be using the in built functionality of VisibilityNotifier.

However, this in turn creates the appropriate Screen Entered and Screen Exited signal in the VisibilityNotifier, so you should be able to use this instead if you want to use signals. Here is the code which triggers them, in the same way as VisibilityNotifier usually works when objects enter and exit the screen:

```
		case NOTIFICATION_ENTER_GAMEPLAY: {
			_in_gameplay = true;
			if (cameras.size() && Engine::get_singleton()->are_portals_active()) {
				emit_signal(SceneStringNames::get_singleton()->screen_entered);
				_screen_enter();
			}
		} break;
		case NOTIFICATION_EXIT_GAMEPLAY: {
			_in_gameplay = false;
			if (cameras.size() && Engine::get_singleton()->are_portals_active()) {
				emit_signal(SceneStringNames::get_singleton()->screen_exited);
				_screen_exit();
			}
		} break;
```
There is no signal in the case where a VisibilityNotifier enters gameplay but is not in the view frustum (this tallys in because VisibilityNotifiers aren't intended to do anything except when they are in view).

The logic is thus:
Object must be both in view AND in gameplay to send "screen entered", and if either become false it is "screen exited" etc.

I'll try and add this to the docs as it isn't clear in this particular case.

**Comment by lawnjelly** [comment] 2022-01-05 14:48
> I have simply created a script to make use of those notifications.

Yup I think on reflection this is probably a good compromise in your situation, because modifying the engine to send signals _and_ notifications for this special case won't be very efficient, and we are after all doing all this for greater performance.

So I guess we can say it is possible already, but just not documented yet. :+1:

**Comment by m4nu3lf** [comment] 2022-01-19 19:48
@lawnjelly I think I found a real bug this time. I have noticed that the gameplay_entered/gameplay_exited signals are not called when:

1) You have a scene with an external room.
2) The active camera is inside the external room.
3) You switch to another scene (optional).
4) You switch to the same scene as before with the camera starting in the external room.

The first time you load the scene you get the callback, but not at step 4. It seems clear to me that some state is being retained if you unload a scene with a portal system and a camera active.
The only workaround I found for the issue is to add the following steps after step 2:

2.a) Deactivate/delete the active camera and do not activate any other camera.
2.b) Wait for at least two idle frames.

Not too pretty, but it works in my case as the loading screen starts with a black screen so, the two black screen frames are not noticeable.

Here is the MRP which I derived from the previous one:

[roaming_gamplay_callback_issue.zip](https://github.com/godotengine/godot/files/7900154/roaming_gamplay_callback_issue.zip)

If you look at the root node you should see the workaround. Remove that and you only get the signal/notifications for "gameplay entered" the first time only.

**Comment by lawnjelly** [comment] 2022-01-20 18:33
Yes it's possible I'm not sending gameplay exit signals when the room system is unloaded, more interesting is not sending the entered signal. There is probably something that just needs a reset, am investigating. :+1:

**Comment by akien-mga** [comment] 2022-01-21 17:34
Fixed by #57033.

**Closed by akien-mga** 2022-01-21 17:34 UTC
Labels: bug, topic:core, topic:3d

**Comment by m4nu3lf** [comment] 2022-01-24 19:59
@lawnjelly I believe I found another related issue. The "gameplay_exited" signal is not triggered for the "exterior" RoomGroup (although the gamplay_entered is triggered when you "re-enter" the exterior room. I think this is important because it is what the tutorial says it should be used to toggle directional lights or other exterior exclusive stuff.
Here is the MRP 
[exterior_gamplay_exited_issue.zip](https://github.com/godotengine/godot/files/7928491/exterior_gamplay_exited_issue.zip)

**Comment by m4nu3lf** [comment] 2022-01-24 20:14
@lawnjelly Actually it's a general problem for very room/roomgroup, not just the "exterior" one

**Comment by lawnjelly** [comment] 2022-01-25 08:50
Ah I've figured it out, there is a bug, there's an optimization to prevent processing unless it changes rooms, but that isn't keeping the active room ids up to date. Should be quite easy to solve. :+1:
