### ISSUE TITLE
Brace mismatch highlight appears for comments as well

### ISSUE THREAD

**Issue by InkONat** [godotengine/godot#84556] opened 2023-11-06 23:41 UTC
### Godot version

4.2.beta1

### System information

Windows 11 - Godot 4.2.beta1

### Issue description

![image](https://github.com/godotengine/godot/assets/61206149/8c574cde-313d-442f-b301-b1cce6d3a8fa)
![image](https://github.com/godotengine/godot/assets/61206149/b85636a8-d64d-4d06-99bc-11e01ab55c65)

for some reason, the bracket is only highlighted if the caret is next to the bracket

### Steps to reproduce

1 - Make a comment
2 - End it with ) and dont include an opening bracket (
3 - Put your caret next to it

### Minimal reproduction project

N/A: too trivial, just open any project and make a comment

**Comment by Calinou** [comment] 2023-11-07 10:21
> for some reason, the bracket is only highlighted if the caret is next to the bracket

This is done by design for brace mismatch highlighting, but it shouldn't happen within comments.

**Comment by InkONat** [comment] 2023-11-09 02:51
what happens now that a pull request has been open to fix the issue? should this issue get closed or what

**Comment by akien-mga** [comment] 2023-11-09 06:59
Issues are closed when/if the pull request is merged. So for now it should stay open.

**Comment by Paulb23** [comment] 2023-11-10 07:48
Going to close as a duplicate of #53332, and it's not an easy fix see comment in #53364

**Closed by Paulb23** 2023-11-10 07:48 UTC
Labels: bug, topic:editor, confirmed, topic:gui
