### ISSUE TITLE
`const` values made out of structures like `Color` have editable components.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#54718] opened 2021-11-07 13:45 UTC
### Godot version

v3.4.stable.official (206ba70f4b2a3eac4455bb21bd7c8af76285bd86)

### System information

N/A

### Issue description

As noticed in https://www.youtube.com/watch?v=v1iFfCq3_Ao

Take this code:

```
### The preloader script.
# This scene should just be used for (pre)loading stuff and then switching to the first "proper" scene of
# the program.
# This scene is (by default) a Node2D in case you want some kind of loading screen here.

extends Node2D

const a_color = Color.blue

func _ready () -> void:
	config_helper.load_config ()
	a_color.r = 1
	print (a_color)
	if (not helper_functions.change_scene ("res://Scenes/UI/main_menu.tscn") == OK):
		get_tree ().quit ()
	return
```

The line `a_color.r = 1` should return an error, as `a_color` is a `const` which implies all its member values are also `const`.

### Steps to reproduce

See above.

**Comment by Calinou** [comment] 2021-11-07 15:43
Duplicate of https://github.com/godotengine/godot/issues/30212.

**Closed by Calinou** 2021-11-07 15:43 UTC
