### ISSUE TITLE
Unable to write to file xxxx file in use, locked or lacking permissions  (Windows 7)

### ISSUE THREAD

**Issue by muafakul** [godotengine/godot#20269] opened 2018-07-19 09:51 UTC
**Godot version:**
Godot Engine V3.0.5.stable.mono.official

**OS/device including version:**

Windown 7
service pack 1

**Issue description:**
I CAN NOT BUILD OR EXPORT TO ANDROID 
PLEASE SEE SCREENSHOOT BELOW 
https://raw.githubusercontent.com/muafakul/muafakul.github.io/master/Screenshot_146.png

another screenshoot
https://raw.githubusercontent.com/muafakul/muafakul.github.io/master/Screenshot_147.png

**Steps to reproduce:**
I DONT KNOW

**Minimal reproduction project:**
I DONT KNOW

**Comment by KellyThomas** [comment] 2018-07-19 10:09
duplicate of https://github.com/godotengine/godot/issues/20017?

**Comment by akien-mga** [comment] 2018-07-19 10:12
Duplicate of #19389 (and #20266 - you could have just edited it instead of opening a new issue 3 times).

**Closed by akien-mga** 2018-07-19 10:12 UTC
