### ISSUE TITLE
Cannot find Scene Unique Node when a node is reparented

### ISSUE THREAD

**Issue by Nitricswight** [godotengine/godot#87209] opened 2024-01-15 10:55 UTC
### Tested versions

- Reproducible in 4.2.1-stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12018.5) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

### Issue description

A node cannot find a scene unique node after it has been reparented to somewhere else in the hierarchy. You can work around it by caching the result, but this still seems odd to me.

### Steps to reproduce

-Scene with a scene unique node
-Reparent one node at runtime and try and access the unique node with %
```
reparent($"../newParent")
print(%Globals.name)
```

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment] 2024-01-15 11:37
Scene Unique Nodes require a common `owner` with the node from which you are querying the unique node. Probably when the parent changes, the `owner` is cleared. Node paths in general and Scene Unique Nodes in particular are intended to initialize "static" scene scripts. If you add/move/delete a node at runtime, then you should store the node reference in a variable instead of querying with node path each time.

**Comment by bitsawer** [comment] 2024-01-15 13:02
This could be a duplicate of https://github.com/godotengine/godot/issues/81480, which was fixed in the master a few days ago by https://github.com/godotengine/godot/pull/81506.

**Closed** 2024-01-15 13:21 UTC
