### ISSUE TITLE
[3.4.beta2] Strange dot at the end of y axis when using Procedural Sky

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#51129] opened 2021-08-01 03:36 UTC
### Godot version

v3.4.beta2.official

### System information

Windows 11, GLES3

### Issue description

Strange dot at the both ends of y axis when using Procedural Sky.

![sky_dot](https://user-images.githubusercontent.com/28705694/127758270-411720ac-ceef-486c-ac6b-16d5d5bca5b4.gif)

### Steps to reproduce

Create a Procedural Sky, check out the y axis end.

### Minimal reproduction project

No need.

**Comment by clayjohn** [comment] 2021-08-01 04:21
Duplicate of https://github.com/godotengine/godot/issues/37192

**Closed by clayjohn** 2021-08-01 04:21 UTC
Labels: bug, topic:3d
