### ISSUE TITLE
Kinematicbody2D can't fit in a perfectly sized hole

### ISSUE THREAD

**Issue by Jamination** [godotengine/godot#37021] opened 2020-03-13 07:59 UTC
**Godot version:**
3.2.1 Mono Stable

**OS/device including version:**
Windows 10 Home x64

**Issue description:**
A 24x24 Kinematicbody2D cannot fit in a 24x24 hole, I've been trying to get around this issue by changing the size of the collision shape a pixel smaller on the sides, but this leads to one-pixel offsetting when I move the body around.

![image](https://user-images.githubusercontent.com/44449108/76600464-e8e4c900-64fe-11ea-8b9e-48f8de9d16a0.png)

**Steps to reproduce:**
Create a new Godot 3.2.1 project, and set up a whole of the same size as the Kinematicbody2D. Then put the Kinematicbody2D over the whole and write a quick script to move it downwards with move_and_slide(). It won't fit through the gap.

**Minimal reproduction project:**
[Minimal Reproduction Project.zip](https://github.com/godotengine/godot/files/4328447/Minimal.Reproduction.Project.zip)

**Comment by Zireael07** [comment] 2020-03-13 08:01
I believe there is a "margin" you have to take in the account, something like 0.02?

**Comment by Jamination** [comment] 2020-03-13 08:31
Ah thank you. I'll try that when I get home!

**Comment by KoBeWi** [comment] 2020-03-13 12:56
Looks like duplicate of #23140
IIRC reduz said something about reworking the physics to remove the margins.

**Comment by Calinou** [comment] 2020-03-13 13:11
Duplicate of #23140.

**Closed by Calinou** 2020-03-13 13:11 UTC
Labels: documentation, topic:physics
