### ISSUE TITLE
PackedScene circular dependency issue

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#84538] opened 2023-11-06 17:29 UTC
### Godot version

4.1.3

### System information

Windows 11

### Issue description

If you reference two scenes to each other using packed scenes the scenes lock up with "Load failed due to missing dependencies"

### Steps to reproduce

create 2 scenes that each have a script assigned referencing the other 

scene1:
´´´
extends Node2D
@export var scene1 : PackedScene
´´´

scene2:
´´´
extends Node2D
@export var scene2 : PackedScene
´´´
and assign the two scenes to their appropriate variable in the inspector.

### Minimal reproduction project

[scene-circular-dependecy-issue.zip](https://github.com/godotengine/godot/files/13270517/scene-circular-dependecy-issue.zip)

**Comment by AThousandShips** [comment] 2023-11-06 17:39
This is a known issue, see:
* https://github.com/godotengine/godot/issues/80877

This is likely a duplicate of https://github.com/godotengine/godot/issues/76641

**Closed by AThousandShips** 2023-11-06 17:39 UTC
