### ISSUE TITLE
Can't run scene from inside editor

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#28781] opened 2019-05-09 15:15 UTC
**Godot version:**
Master 
Reverting this commit https://github.com/godotengine/godot/pull/26977/commits/85cc435103e539990f095966aaa3ea786a7dd386 fixes the issue

**OS/device including version:**
Ubuntu 16.04 
Awesome WM

**Issue description:**
The editor opens fine, but when you click to launch the scene within editor it won't open another window and immediately exits with the following error:
``drivers/unix/net_socket_posix.cpp:199 - Socket error - 104``

And in the terminal the following printout
```
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  199
  Current serial number in output stream:  199
```

My guess is that this line is the culprit
https://github.com/godotengine/godot/blob/48d31632a5f794f578879c80ab1bc5bcd44c1092/platform/x11/os_x11.cpp#L1192

Maybe `` "_NET_FRAME_EXTENTS"`` is not available on every device/version of x11?
_edit:_ after doing more research this appears to be the case awesome WM doesn't support it and apparently many others don't as well.

@bruvzg Tagging you as you were the one to make the commit, any reason why this would cause the issue?

**Steps to reproduce:**
1) Compile from master
2) run
3) try to play scene from within editor

**Comment by akien-mga** [comment] 2019-05-09 15:31
Related to #28538 (affecting i3wm and also caused by #26977) which was fixed by #28557.

**Comment by clayjohn** [comment] 2019-05-09 15:33
To add more info. It seems that I can also fix this on my end by updating my WM. It may be the case that the majority of WMs wont have problems so long as they are up to date. In which case it may not be worth fixing. 

@akien-mga What do you think?

**Comment by akien-mga** [comment] 2019-05-09 15:35
It would probably be best to add some fallback code for WMs which don't support this (yet) to make sure it works fine.

**Comment by bruvzg** [comment] 2019-05-09 16:16
Confirmed, `XGetWindowProperty` crashes if atom is invalid, "_NET_FRAME_EXTENTS" was added EWMH version 1.3 (in 2005), check #28784.

**Closed** 2019-05-09 16:30 UTC
Labels: bug, high priority, platform:linuxbsd, regression, topic:porting
