### ISSUE TITLE
full screen behaves oddly on OSX El Capitan/Yosemite (and likely Mavericks too)

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#3332] opened 2016-01-12 23:24 UTC
Yosemite (actually Mavericks ) introduced that custom full screen feature that any app can use. This seems to affect Godot applications in a bad way. 

So there are a few issues to report here.
1. Godot app viewport option (as opposite to 2d) seems to have no effect on Yosemite and resolution is never changed. In fact any choice combo simply makes the app goes in Yosemite full screen.
2. Godot app does not go full screen on Yosemite if fullscreen is selected and on but resizable is not selected. In fact it prevents the app from ever being able to go full screen and the Yosemite fullscreen is greyed out and cannot be used.  
3. Mouse near edge of the screen seems to trigger menu and dock (if hidden) right on top of the running app. This makes any game using say top and bottom window edge to scroll map (like for ex TBS) no longer possible. This is a big issue for me right now as I want the window to capture the mouse and the window to stay focused on the game . I don't wanna see any OS menus appearing on top of my game.
   ![screen shot 2016-01-12 at 6 20 25 pm](https://cloud.githubusercontent.com/assets/6987027/12280050/3865c2d2-b959-11e5-9c5e-080ffc0cf0e6.png)
   ![screen shot 2016-01-12 at 6 20 21 pm](https://cloud.githubusercontent.com/assets/6987027/12280143/c43c163a-b959-11e5-9de3-95ecc0482c8d.png)

When OSX saves screenshots it removes the mouse pointer. In the images above my mouse is at max bot position and max top position.

If anyone has suggestions or work arounds for these issues I am all ears. Also, I have a mac running latest and greatest patches (OSX and Godot) so I can test anything you want me to.

**Comment by trollworkout** [comment] 2016-01-13 10:55
@kubecz3k I am using November 3, 2015 at 12:34 Mac OS X 64-bit development tools from http://fixnum.org/godot/#latest_noerror  which is the latest available build for all platforms without errors. The issue is still present. Likely is a new OSX full screen mechanic introduced since Mavericks that's the issue.

I am currently on El Capitan now and issue is still present.

**Comment by purpleorangegames** [comment] 2016-01-14 18:46
@trollworkout Does this still happens on the latest build?

**Comment by trollworkout** [comment] 2016-01-14 19:02
@purpleorangegames  Yes. This is unchanged  unfortunately. I have strong suspicion is due to the changes Mavericks brought to full screen. Full screen is no longer true full screen but rather an glorified maximize. I need to figure out a way to trap an capture the mouse inside the window until I quit the game or Command+TAB out of it.

**Comment by fleskesvor** [comment] 2018-05-26 15:08
Fullscreen still behaves oddly with 3.0.2-stable on High Sierra. Exporting a game with fullscreen=true and resizeable=false causes the game to be launched in Windowed mode, and in my demo project the game window is too large to fit the screen. Using fullscreen=true and resizable=true, however, launches the game in actual fullscreen.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment] 2018-09-26 02:29
@fleskesvor  is this still an issue for latest 3.1 alpha?

**Comment by xsellier** [comment] 2019-03-01 17:44
It stills happen on every version (Fullscreen function has not been changed since 2.1)

**Comment by eduardonunesp** [comment] 2020-05-04 09:52
If I tested correctly it works fine for a fullscreen on `macOS 10.15.4` (however using the fullscreen as it normally behaves on macs with a fullscreen going to a different workspace and making it full screen), I created a small game and exported with full screen on mac and it works as expected.

**Comment by bruvzg** [comment] 2020-07-02 08:13
> Fullscreen still behaves oddly with 3.0.2-stable on High Sierra. Exporting a game with fullscreen=true and resizeable=false causes the game to be launched in Windowed mode, and in my demo project the game window is too large to fit the screen. Using fullscreen=true and resizable=true, however, launches the game in actual fullscreen.

This was fixed it #27490

The rest (moving to new workspace, and accessible menu, title and dock) is completely normal and expected behavior on any modern macOS version.

**Closed by bruvzg** 2020-07-02 08:13 UTC
Labels: bug, platform:osx, topic:core
