### ISSUE TITLE
Can't load PO file if missing newline at end of file on last msgstr

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#20375] opened 2018-07-23 09:03 UTC
**Godot version:**
3.0.2

**OS/device including version:**
linux mint 18.3

**Issue description:**
example for [topic from forum](https://godotdevelopers.org/forum/discussion/comment/24412#Comment_24412)

By default app used en_US locale.
Also added two transliations in text .po files: es_ES, ru_RU (UTF-8).
As I think after locale changed the title of button "New Game" also must be changed, but it didn't.
What I'm doing wrong?

**Steps to reproduce:**
export project in godot and click buttons

**Minimal reproduction project:**
project.godot:
```
...
[locale]
translations=PoolStringArray( "res://es.po" )
...
```
es.po
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-06-28 18:31+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: POScene.tscn
msgid "New Game"
msgstr "Juego Nuevo"
```
SetES.gd
```
extends Button

func _on_SetES_pressed():
	TranslationServer.set_locale("es")
	print(TranslationServer.get_locale())
```
POScene.tscn:
![screenshot at 2018-07-24 12-44-03](https://user-images.githubusercontent.com/15020827/43130418-57635bfe-8f3f-11e8-87b3-4fe76cdd10ca.png)
![screenshot at 2018-07-24 12-44-19](https://user-images.githubusercontent.com/15020827/43130426-5996e9c2-8f3f-11e8-9071-91b6938b5435.png)

Project: [godot-po.zip](https://github.com/godotengine/godot/files/2222974/godot-po.zip)

Thanks.

**Comment by akien-mga** [comment] 2018-07-24 10:59
Your PO file fails loading:
```
ERROR: load_translation: :23 Unexpected EOF while reading 'msgid' at file: 
   At: core/io/translation_loader_po.cpp:78.
ERROR: _load: Failed loading resource: res://es.po
   At: core/io/resource_loader.cpp:186.
```

Apparently Godot chokes on the `#, fuzzy` before the header's empty `msgid`.

**Comment by akien-mga** [comment] 2018-07-24 11:04
Ah no, the issue is that you're missing a newline character at the end of the file on the last msgstr, so Godot doesn't finish parsing it properly.

**Comment by r3d9u11** [comment] 2018-07-24 12:50
@akien-mga ok, there is my changed .po:
```
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-06-28 18:31+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: POScene.tscn
msgid "New Game"
msgstr "Juego Nuevo"
```
and now I can see only translated button (I can't switch to default English title):
![screenshot at 2018-07-24 15-49-22](https://user-images.githubusercontent.com/15020827/43138963-032ce0e0-8f40-11e8-9041-4afc86d58b1b.png)

**Comment by akien-mga** [comment] 2018-07-24 12:56
Yeah I've seen that too. It works on the master branch, but not fully on the 3.0 branch. I'm not sure why yet.

**Comment by akien-mga** [comment] 2018-07-24 12:58
That's because the 3.0 branch needs this fix backported: #19213.

In the meantime, you can just rename "Language" to "X-Language".

**Comment by r3d9u11** [comment] 2018-07-24 13:07
@akien-mga I tried to rename `es.po` to `es_ES.po`, `Language: es` to `Language: es_ES`, call TranslationServer.set_locale("es_ES"). But without success

**Comment by r3d9u11** [comment] 2018-07-24 13:11
@akien-mga Ah, I mean rename parameter Language to X-Language, not value :-D
Thank! It work

**Comment by r3d9u11** [comment] 2018-07-24 13:12
@akien-mga leave this issue to be opened?

**Comment by akien-mga** [comment] 2018-07-24 13:13
Yes, until #20407 is merged.

**Closed** 2018-07-24 16:12 UTC
Labels: bug, topic:core

**Comment by r3d9u11** [comment] 2018-07-24 18:03
@akien-mga also without empty line in end of file will not work

**Comment by akien-mga** [comment] 2018-07-24 18:10
> also without empty line in end of file will not work

There *must* be an empty line at the end of the file.

**Comment by r3d9u11** [comment] 2018-07-24 20:14
@akien-mga thanks for clarification!
