### ISSUE TITLE
\t not worked for string in the Label

### ISSUE THREAD

**Issue by nekronk** [godotengine/godot#4327] opened 2016-04-15 14:34 UTC
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
**\t** not worked in the method set_text() for Label object
Example:
get_node("Label").set_text('tab test**\t**wwww')

**Steps to reproduce:**
1. Create the Control node
2. Create the Label node in the Control
3. Create new script for Control node
4. Set script text:

```
extends Control

func _ready():
    get_node("Label").set_text('tab test\twwww')

```

**Link to minimal example project** (optional but very welcome):
See screenshot: http://i.imgur.com/Dw6y6YE.png

**Comment by StraToN** [comment] 2016-04-15 14:49
Very close to #2967
Maybe consider merging both issues?

**Comment by akien-mga** [comment] 2016-04-15 15:02
Indeed, closing as duplicate of #2967. I'll add a mention about ``\t`` and Label there.

**Comment by nekronk** [comment] 2016-04-15 15:04
How to do it? I don't know! I'm here for the first time. This issue will need to be shut down?

**Comment by DarthSmart** [comment] 2022-02-11 15:47
Apparently \t still doesnt work for Labels in 3.4.2 🤨

**Comment by VapidLinus** [comment] 2023-04-16 09:52
This was closed but was not fixed by the linked PR. Issue still present in Godot 4

**Comment by bruvzg** [comment] 2023-04-16 11:52
It's not a bug as such, tab width is context dependent, and by default, tab character in most of the fonts is zero width. But I guess adding an option to enable tab stops for the `Label` will make sense (since `RichTextLable` already support it).

**Closed** 2023-06-09 11:47 UTC
Labels: bug, topic:gui
