### ISSUE TITLE
Wrong behavior of Line2D when setting WidthCurve to a number less than 1.0

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#85134] opened 2023-11-20 11:46 UTC
### Godot version

4.2 rc1

### System information

Win 11,CPU amd5600,GPU 5700xt,gl rendering mode

### Issue description
See the gif. I think the right effect is that the bottom or up width of texture become just smaller.  
![4](https://github.com/godotengine/godot/assets/10054853/6c145e32-7fd1-4a60-b9b7-7c46c128ae95)

### Steps to reproduce

1. Make a line2d node.
2. set it a texture and set the Texture_Mode to "Tile" mode.
3. add a width curve and make a point less than 1.
4. see the result.

### Minimal reproduction project

[BugTest_line2d.zip](https://github.com/godotengine/godot/files/13413684/BugTest_line2d.zip)

**Comment by Calinou** [comment] 2023-11-20 11:51
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by zhagsenkk** [comment] 2023-11-20 11:55
> Please upload a minimal reproduction project[1](#user-content-fn-1-f59119319697bb4427bf3c54b36b19c0) to make this easier to troubleshoot.
> 
> Also, can you reproduce this on 4.1.3?
> 
> ## Footnotes
> 1. A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.****Note for C# users:** If your issue is _not_ Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available. [↩](#user-content-fnref-1-f59119319697bb4427bf3c54b36b19c0)

OK, Update

**Comment by kleonc** [comment] 2023-11-20 13:18
Duplicate of #83306.

**Closed by kleonc** 2023-11-20 13:18 UTC
Labels: bug, topic:rendering, needs testing, topic:2d
