### ISSUE TITLE
Game crashes without any information when parsing certain XML files

### ISSUE THREAD

**Issue by XBigTK13X** [godotengine/godot#40415] opened 2020-07-15 14:02 UTC
**Godot version:**
- Godot Engine v3.2.2.stable.official

**OS/device including version:**

OS
 - Windows 10 Home 64-bit

GPU Model
 - NVIDIA GeForce GTX 1070

Drivers
 - 26.21.14.4614

Backend
- OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2

**Issue description:**
### What Happened
Using XMLParser to ingest an XML resource. The game silently crashes (even with -debug enabled) when the parser hits the start of a multiline XML comment containing malformed XML. Note that this behavior isn't deterministic. Sometimes the file will parse without godot crashing.

### What is Expected
The comment is either ignored, combined into a single XML comment node, or exposed as a new multiline comment node type. Regardless of the solution, the uncommented data in the XML file should be made available.

**Steps to reproduce:**

Create an XML file with nonuniform spacing and invalid data wrapped in multiline comments.

**Minimal reproduction project:**

[xml-multiline-comment.zip](https://github.com/godotengine/godot/files/4925684/xml-multiline-comment.zip)

Note that I also included a short video in the project demonstrating the crash after running the project a few times.

**Comment by qarmin** [comment] 2020-07-15 14:31
Backtrace is similar to #38904
```
Opening XML file res://asset/multiline-comment.xml
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fae39565210] (??:0)
[2] XMLParser::_parse_comment() (/mnt/Miecz/godot3.2/core/io/xml_parser.cpp:203)
[3] XMLParser::_parse_current_node() (/mnt/Miecz/godot3.2/core/io/xml_parser.cpp:337)
[4] XMLParser::read() (/mnt/Miecz/godot3.2/core/io/xml_parser.cpp:393)
[5] MethodBind0R<Error>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:237 (discriminator 4))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:922 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1127 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1085)
[9] GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1237)
[10] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:901 (discriminator 1))
[11] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (/mnt/Miecz/godot3.2/core/message_queue.cpp:250)
[12] MessageQueue::flush() (/mnt/Miecz/godot3.2/core/message_queue.cpp:299)
[13] SceneTree::iteration(float) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:484 (discriminator 2))
[14] Main::iteration() (/mnt/Miecz/godot3.2/main/main.cpp:2082)
[15] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3233)
[16] /usr/bin/godot(main+0x125) [0x141dbab] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[17] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fae395460b3] (??:0)
[18] /usr/bin/godot(_start+0x2e) [0x141d9ce] (??:?)
-- END OF BACKTRACE --
```

**Comment by XBigTK13X** [comment] 2020-07-15 15:13
Thank you for the additional info.

If anyone is looking to work around this bug and doesn't need the comments, here is a snippet to strip them out at runtime. My particular use case doesn't allow me to preprocess the files on disk.

```
var absolute_path = resolve(relative_path)

var file = File.new()
if ! file.file_exists(absolute_path):
	print("Unable to find referenced file [" + absolute_path + "]")
file.open(absolute_path, File.READ)
var xml_content = file.get_as_text()
var reg_ex = RegEx.new()
var expression = "<!--[\\s\\S\\n]*?-->"
reg_ex.compile(expression)
xml_content = reg_ex.sub(xml_content, "", true)
var xml_parser = XMLParser.new()
xml_parser.open_buffer(xml_content.to_utf8())
return xml_parser
```

**Comment by gr4ph0s** [comment] 2020-07-17 19:43
With Godot 4 in a local build, I'm not able to reproduce the crash.
Is it a 3.2.2 issue only?

**Comment by jeansorgemoel** [comment] 2020-07-23 22:43
Hi,

I reproduce this issue on godot 3.2.2 (not all time, 50% time crash)
With Fix https://github.com/godotengine/godot/pull/40036 never crashed

1. The method to decode xml comment on godot 3.2.2 (and godot 4), it is calculate number '<' and '>', when we have same number, it's end of comment (it's not XML standard)

2. The fix https://github.com/godotengine/godot/pull/40036 update method to decode xml comment.
   * decode with specification https://www.w3.org/TR/2008/REC-xml-20081126/#sec-comments


In your case, in your comment, you have this code:
<code>
<price amount="250"
</code>
missing '>', so godot can't detect correctly the end of comment, and sometimes doesn't identify end of data and crash
In fact, godot continue to read next-char and can read out of buffer


to solve this issue, two options:
1. [workaround] complete in your xml file, to have same '<' & '>' [it's strange, because your xml data is xml valid]
   * or remove your comment

2. Wait the new release include the fix https://github.com/godotengine/godot/pull/40036
   (I don't know when this fix is merged in official branch)

Sum up:
 * this bug exist on godot 3.2.2 and godot 4
 * workaround is to update the xml comment (number '<' equal number '>')
 * wait next release include Fix https://github.com/godotengine/godot/pull/40036

**Closed** 2021-05-21 10:26 UTC
Labels: bug, crash, topic:core
