### ISSUE TITLE
Godot 4 Lightmap freezes

### ISSUE THREAD

**Issue by SenhorPatolino** [godotengine/godot#69574] opened 2022-12-04 17:27 UTC
### Godot version

4.0 beta 6 & 7

### System information

Windows 10, Vulkan, NVIDIA Driver V.527.37 

### Issue description

Lightmapper freezes when "determining optimal atlas size". For me it always freezes when reaching 26%.

### Steps to reproduce

Hit bake lightmaps

### Minimal reproduction project

[Debug.zip](https://github.com/godotengine/godot/files/10149107/Debug.zip)

**Comment by Calinou** [comment] 2022-12-04 18:34
Duplicate of https://github.com/godotengine/godot/issues/63423.

**Closed by Calinou** 2022-12-04 18:34 UTC
