### ISSUE TITLE
(C#) Godot game crashes when trying to GD.Print a value that initializes with null

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot#40319] opened 2020-07-12 16:49 UTC
**Godot version:**

v3.2.2.stable.mono.official

**OS/device including version:**

Windows 10 Pro, Racing P1 mini computer, Intel(R) HD Graphics 400 GLES3

**Issue description:**

If working with C# with godot 3.2.2 mono and tries to GD.Print any variable type initialized with value "null" it crashes the game (the game, not the editor) without any message in output console inside Editor, nor in the console.

For example:

GD.Print(null); // System.ArgumentNullException: Value cannot be null, behaves as it is.
Node2D test = null;
GD.Print(test); // This freezes the game and after a time appears the "Godot Engine stopped working", without throwing any error

**Steps to reproduce:**
1. Create a C# project
2. Create a simple script
3. Try to GD.Print a variable initialized with null

**Minimal reproduction project:**

A bit lazy to create one, if really needed I upload one

**Comment by akien-mga** [comment] 2020-07-13 13:54
Duplicate of #37309.

**Closed by akien-mga** 2020-07-13 13:54 UTC
Labels: bug, crash, topic:mono
