### ISSUE TITLE
 in godot version 3.2, will you still have problems with the Samsung SM-G930F mobile phone? It does not work 3D animated bones imported from Blender, it locks the phone and closes the application.

### ISSUE THREAD

**Issue by giovanigsilva** [godotengine/godot#29885] opened 2019-06-18 22:46 UTC
Godot version: 3.1.1

OS/device including version: SM-G930F

Issue description:
It does not work 3D animated bones imported from Blender, it locks the phone and closes the application

Steps to reproduce: animated bones imported from Blender. (GLES2). on test in cell phone, crash everytime
[game3dcharacters.zip](https://github.com/godotengine/godot/files/3303714/game3dcharacters.zip)

example in file

**Comment by giovanigsilva** [comment] 2019-06-18 22:48
Godot version: 3.1.1

OS/device including version: SM-G930F

Issue description:
It does not work 3D animated bones imported from Blender, it locks the phone and closes the application

Steps to reproduce:  animated bones imported from Blender

**Comment by clayjohn** [comment] 2019-06-18 23:22
This is a duplicate of https://github.com/godotengine/godot/issues/28298 which was closed by https://github.com/godotengine/godot/pull/29751

**Closed by clayjohn** 2019-06-18 23:22 UTC
