### ISSUE TITLE
Background don't change until engine restart

### ISSUE THREAD

**Issue by mhdchehade** [godotengine/godot#9269] opened 2017-06-19 13:09 UTC
Windows 10 - Godot 2.1.2.stable.official

When I change default_clear_color under Render (Scene > Project Settings) the 2d or 3d view doesn't get updated until restart.

**Comment by bojidar-bg** [comment] 2017-06-19 16:46
Duplicate of #6795, sorry.

**Closed by bojidar-bg** 2017-06-19 16:46 UTC
