### ISSUE TITLE
Accessing SCREEN_TEXTURE generates artifacts

### ISSUE THREAD

**Issue by yaelatletl** [godotengine/godot#43844] opened 2020-11-25 07:41 UTC
**Godot version:**
4.0 at 32b31a5fa47b1e068be98f3196cf5d83a2260667

**OS/device including version:**
Vulkan, Windows 10, AMD RX 5700 stock settings, driver 20.11.1

**Issue description:**
Using the Screen texture in a shader results on a series of artifacts, updating the configuration in the project change the appearence of the artifacts.
![imagen](https://user-images.githubusercontent.com/28612272/100196234-3868fa80-2ebe-11eb-87f1-b2c108b0dc17.png)

further changing led me to a crash, but I'm not sure if it's related:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] CowData<RenderingDevice::AttachmentFormat>::get (E:\godot\core\templates\cowdata.h:153)
[1] Vector<RenderingDevice::AttachmentFormat>::operator[] (E:\godot\core\templates\vector.h:89)
[2] RenderingDeviceVulkan::framebuffer_format_create (E:\godot\drivers\vulkan\rendering_device_vulkan.cpp:3299)
[3] RenderingDeviceVulkan::render_pipeline_create (E:\godot\drivers\vulkan\rendering_device_vulkan.cpp:5094)
[4] RenderPipelineVertexFormatCacheRD::_generate_version (E:\godot\servers\rendering\rasterizer_rd\render_pipeline_vertex_format_cache_rd.cpp:42)
[5] RenderPipelineVertexFormatCacheRD::get_render_pipeline (E:\godot\servers\rendering\rasterizer_rd\render_pipeline_vertex_format_cache_rd.h:83)
[6] RasterizerSceneHighEndRD::_render_list (E:\godot\servers\rendering\rasterizer_rd\rasterizer_scene_high_end_rd.cpp:1123)
[7] RasterizerSceneHighEndRD::_render_scene (E:\godot\servers\rendering\rasterizer_rd\rasterizer_scene_high_end_rd.cpp:1918)
[8] RasterizerSceneRD::render_scene (E:\godot\servers\rendering\rasterizer_rd\rasterizer_scene_rd.cpp:7002)
[9] RenderingServerScene::_render_scene (E:\godot\servers\rendering\rendering_server_scene.cpp:2390)
[10] RenderingServerScene::render_camera (E:\godot\servers\rendering\rendering_server_scene.cpp:1847)
[11] RenderingServerViewport::_draw_3d (E:\godot\servers\rendering\rendering_server_viewport.cpp:87)
[12] RenderingServerViewport::_draw_viewport (E:\godot\servers\rendering\rendering_server_viewport.cpp:137)
[13] RenderingServerViewport::draw_viewports (E:\godot\servers\rendering\rendering_server_viewport.cpp:540)
[14] RenderingServerRaster::draw (E:\godot\servers\rendering\rendering_server_raster.cpp:116)
[15] RenderingServerWrapMT::draw (E:\godot\servers\rendering\rendering_server_wrap_mt.cpp:93)
[16] Main::iteration (E:\godot\main\main.cpp:2434)
[17] OS_Windows::run (E:\godot\platform\windows\os_windows.cpp:622)
[18] widechar_main (E:\godot\platform\windows\godot_windows.cpp:163)
[19] _main (E:\godot\platform\windows\godot_windows.cpp:185)
[20] main (E:\godot\platform\windows\godot_windows.cpp:199)
[21] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[22] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Steps to reproduce:**

You can easily recreate this by setting refraction in a material.

**Comment by fracteed** [comment] 2020-11-26 03:50
I can confirm that I am also having this issue on master, using Win10 and 960M.

**Comment by angad-k** [comment] 2021-03-08 14:53
Can confirm too. 
Without refraction:
![wo_refraction](https://user-images.githubusercontent.com/54415525/110337511-0124f080-804c-11eb-8710-b11614090cb6.PNG)
With refraction : 
![w_refraction](https://user-images.githubusercontent.com/54415525/110337473-f702f200-804b-11eb-8028-e5a7711d0d0b.PNG)

https://user-images.githubusercontent.com/54415525/110337348-d89cf680-804b-11eb-97e7-701ad9e8cb9e.mp4

**Comment by clayjohn** [comment] 2022-11-10 22:51
I can't reproduce this issue on Beta 4. Given how long its been (and how much Godot has changed) I have a feeling that this issue has been fixed. Can someone who was previously able to reproduce confirm that this issue isn't present in Beta 4?

**Comment by fracteed** [comment] 2022-11-11 02:07
@clayjohn It seems to be working fine for me.

**Comment by clayjohn** [comment] 2022-11-11 02:09
Wonderful! Thanks for checking. Closing as fixed.

**Closed** 2022-11-11 02:09 UTC
Labels: bug, topic:rendering, confirmed, crash, topic:shaders
