### ISSUE TITLE
Placing a rotated tile in GridMap deletes the adjacent tile

### ISSUE THREAD

**Issue by clayheaton** [godotengine/godot#26374] opened 2019-02-27 20:43 UTC
**Godot version:**
3.1 beta 8

**OS/device including version:**
MacOS

**Issue description:**
Placing a _rotated_ tile next to an already-placed tile on a GridMap causes the already-placed tile to disappear.

**Steps to reproduce:**
Open the project and the `TestLandscapeGrid` scene...

Given this setup:

![screen shot 2019-02-27 at 3 33 31 pm](https://user-images.githubusercontent.com/205364/53521029-15b97000-3aa5-11e9-882c-8b8c2f5efa49.png)

Try taking the selected tile and placing it here:

![screen shot 2019-02-27 at 3 34 14 pm](https://user-images.githubusercontent.com/205364/53521050-28cc4000-3aa5-11e9-82f7-d30919afcdce.png)

Everything works fine. Undo that placement. Press `s` once to rotate the tile and then try placing it as shown here:

![screen shot 2019-02-27 at 3 35 24 pm](https://user-images.githubusercontent.com/205364/53521120-53b69400-3aa5-11e9-8efd-a8c3e5c748de.png)

When you click to place it, the adjacent tile disappears, as shown here:

![screen shot 2019-02-27 at 3 36 07 pm](https://user-images.githubusercontent.com/205364/53521168-6c26ae80-3aa5-11e9-82c3-991bdf835781.png)

**Minimal reproduction project:**

[ufo_test.zip](https://github.com/godotengine/godot/files/2912240/ufo_test.zip)

**Comment by zedutchgandalf** [comment] 2019-03-13 19:07
This is not a bug. Your tiles have their pivot set in the corner (as is the case for all Kenney tiles by default). Thus, when you're rotating the tile, it appears as if its moving to neighbouring tiles since you're rotating around its pivot (its corner) and not the actual center. So even though it visually looks as if you're placing it in the same spot in both cases, you're actually overwriting the other tile's data when you're trying to place the rotated tile. This is basically the same problem as people are having in #24602

**Comment by clayheaton** [comment] 2019-03-13 19:12
Interesting... that makes sense, but then suggests that it would require a lot of pre-Godot work with the Kenney tiles to make them usable in Godot. That's not the fault of Godot, of course, but makes me wonder if Godot can or should support a way to work with those tiles (or other assets with a similar problem) short of having to open all of them in Blender and re-export them. Or is there another way to quickly change a set of tiles in Godot?

**Comment by zedutchgandalf** [comment] 2019-03-13 19:30
>  if Godot can or should support a way to work with those tiles
That's pretty much what #24602 is asking for. If we could change the mesh's pivot in the engine itself, this would be pretty easy to do (e.g. using an import script). Right now, I don't think there's anything you can do in Godot itself to fix it...

**Comment by Xenoamor** [comment] 2019-08-12 21:41
@clayheaton you can write blender scripts to do what you're asking

**Comment by akien-mga** [comment] 2020-01-14 13:24
Closing then as it's not a bug. 3.2 has support for applying an offset to OBJ files on import, particularly relevant for Kenney's notoriously offset meshes.

**Closed by akien-mga** 2020-01-14 13:24 UTC
Labels: bug, topic:editor

**Comment by insomniacUNDERSCORElemon** [comment] 2024-11-18 13:41
I'm experiencing this issue now (in 4.3) with .glb models. With my own models, the center-point in the corner makes sense for grid snapping, so centering these is undesirable.

I don't even really care if the rotation causes it to shift cells, but I would like the empty cells to be correctly identified (with some small margin for error). 

I am not sure if bigger cells (2x2, 1x1x2 etc) already have their bounding boxes detected properly, it would be nice to have those in the same meshlib as I already planned to use smaller gridmaps for different types of detail/placement (rooms > furniture > objects). Not so great if a corner of the same wall has to be on a different gridmap.
