### ISSUE TITLE
Opening project/material using visual shader instance uniforms results in many errors failure to compile shaders

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#83431] opened 2023-10-16 09:50 UTC
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - macOS 13.6.0 - Vulkan (Mobile) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

It appears something has broken in compiling shaders (maybe visual shaders) using instance shader uniforms in the Mobile renderer. Opening a scene where one is used gives me the following errors:
```
servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:183 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.
  servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:183 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.
  servers/rendering/renderer_rd/shader_rd.cpp:293 - Error compiling Fragment shader, variant #2 (
  #define MODE_RENDER_DEPTH
  ).
  servers/rendering/renderer_rd/shader_rd.cpp:294 - Failed parse:
 WARNING: 0:73: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
           "precision mediump int; precision highp float;" 
  ERROR: 0:1763: 'instance_index' : undeclared identifier 
  ERROR: 0:1763: '[]' : scalar integer expression required 
  ERROR: 0:1763: '' : compilation terminated 
  ERROR: 3 compilation errors.  No code generated.
```

Followed by 27000+ error lines of what looks like complete printouts of some very long godot internal shaders like servers/rendering/renderer_rd/shader_rd.cpp 

![Screenshot 2023-10-16 at 11 37 21](https://github.com/godotengine/godot/assets/17763524/6fc653df-cec9-4f9a-ac56-d7affc45bf03)

Considering the number of shader compilation errors lines, perhaps it would be a good idea to limit the output of full shader code? As this probably does not contribute to making the issue easier to find and also slows down the interface a little in cases like this. 

### Steps to reproduce

Open the attached empty project with just a material referencing a visual shader.
If it's not selected already, select the material in the FileSystem browser to get the errors.

### Minimal reproduction project

[InstanceShaderTest.zip](https://www.lostminds.com/godot/InstanceShaderTest.zip)

**Comment by clayjohn** [comment] 2023-10-16 09:53
Duplicate of https://github.com/godotengine/godot/issues/83391

Fixed by https://github.com/godotengine/godot/pull/83400

**Closed by clayjohn** 2023-10-16 09:53 UTC
