### ISSUE TITLE
Using a texture in 3d Sprite causes error

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#57983] opened 2022-02-11 17:26 UTC
### Godot version

4.0 Alpha 2

### System information

Windows 10 Intel 4690k GTx 1060 

### Issue description

Assigning an image to a sprite 3d causes Condition "p_elem->_root,
which in larger scenes causes a ridiculous amount of extra loading time. (can range from anywhere from 1 - 10 seconds)

### Steps to reproduce

1. Create a sprite3d
2. Assign a texture (default icon)
3. Save the scene and exit
4. Anytime you open this scene, Condition "p_elem->_root will appear.

### Minimal reproduction project

[SpriteGlitch.zip](https://github.com/godotengine/godot/files/8050532/SpriteGlitch.zip)

**Comment by Calinou** [comment] 2022-02-12 16:54
Duplicate of https://github.com/godotengine/godot/issues/55682 (fixed by https://github.com/godotengine/godot/pull/57319). Please comment if you can still reproduce this on a build made after https://github.com/godotengine/godot/pull/57319 was merged.

**Closed by Calinou** 2022-02-12 16:54 UTC
Labels: bug, topic:rendering, regression, topic:3d
