### ISSUE TITLE
Server disconnected + Warnings 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#15043] opened 2017-12-25 14:49 UTC
Godot 3 - Windows 7-64

OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
SCAN PROJECTS AT: c:/Users/homev3/Documents/GoDot/Godot_v3.0-alpha2_win64
found: 46 projects.
OPENING: c:/Users/homev3/Documents/GoDot/beta/projects/teeclone (c:::Users::homev3::Documents::GoDot::beta::projects::teeclone)
running cmdline: "C:\godot\bin\godot.windows.tools.64.exe" "--path" "c:/Users/homev3/Documents/GoDot/beta/projects/teeclone" "--editor"
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Running: C:\godot\bin\godot.windows.tools.64.exe --path c:/Users/homev3/Documents/GoDot/beta/projects/teeclone --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 7204 --position 448,240 res://main.tscn
running cmdline: "C:\godot\bin\godot.windows.tools.64.exe" "--path" "c:/Users/homev3/Documents/GoDot/beta/projects/teeclone" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "7204" "--position" "448,240" "res://main.tscn"
OpenGL ES 3.0 Renderer: GeForce GT 650M/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Nothing read: Invalid argument
ERROR: StreamPeerTCPWinsock::read: Server disconnected!

   At: drivers\windows\stream_peer_tcp_winsock.cpp:202
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
     At: drivers\png\image_loader_png.cpp:66

**Issue description:** and steps to reproduce it:

I make a new project in a new folder and I copied in a folder with some images in.
When I clicked in godot he recognized the folder with all images inside  but in console and in output I have these warnings + error as server disconnected:

![image](https://user-images.githubusercontent.com/13235119/34340795-8d946f6e-e982-11e7-8580-22f2406dcb7d.png)

Thank you.

**Comment by KoltesDigital** [comment] 2017-12-29 01:16
I have the same problem with `v3.0-beta2` on *Windows 10 64bit*. The firewall asked to accept or reject the app, I accepted but it doesn't help.

**Comment by KoltesDigital** [comment] 2017-12-29 21:13
I compiled the engine and with this version it works.

**Comment by mhilbrunner** [comment] 2018-01-12 04:19
@git2013vb: Please try again with a more recent version (compile Godot, wait for the 3.0 RC or get one of the daily builds here: http://godot3builds.digitecnology.com/index.php).

If it still happens, comment here and we'll reopen. For now assuming it was fixed seeing KoltesDigital's comments above.

Note: The PNG/iCCP errors will likely still happen, as they are caused by invalid PNG profiles commonly exported by Photoshop. Newer PNG library does no longer simply accept them. See here how to fix these files: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile.

Closing for now.

**Closed by mhilbrunner** 2018-01-12 04:19 UTC

**Comment by MrTaron** [comment] 2018-01-12 22:16
I'm getting the same thing.

It's hard to pin-point the exact problem since I don't get any info in my debugger, but from what I've noticed:
Happens 2% at random, but...
100% if my Area2D intersects/enters a CollisionShape2D from my TileMap.

So weird.

**Comment by mhilbrunner** [comment] 2018-01-13 01:17
@MrTaron Beta 2 or more recent version?
