### ISSUE TITLE
Shader editor grabs at least some shortcuts from the script editor

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#21592] opened 2018-08-30 03:23 UTC
**Godot version:** 3.1alpha 02490db

**OS/device including version:** Linux

**Issue description:** Having both the script and shader editors open, Ctrl+D duplicates the current line in the shader editor, even when the script editor has keyboard focus. Ctrl+V does work properly so I suppose this is an issue with editor shortcuts not going to the proper text editor rather than focus?

**Comment by KoBeWi** [comment] 2019-03-02 21:00
This also happens when you have e.g. 2D view open and the node with shader is selected. Any action you'd want to do on the node is instead grabbed by the shader editor.

**Comment by KoBeWi** [comment] 2020-06-12 20:59
There are few similar issues, so I will close this as duplicate of #17591

**Closed by KoBeWi** 2020-06-12 20:59 UTC
Labels: bug, topic:editor, usability
