### ISSUE TITLE
Strange way to hide cursor with mouse modes

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#27889] opened 2019-04-10 06:32 UTC
**Godot version: v3.1.stable.official**

My game switches between 3D captured and 2D mouse movement. I came across this oddity, though it could just be something that I don't understand.

```
func _ready():
	yield(get_tree(), 'idle_frame')
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _input(event):
	if Input.is_action_pressed("ui_accept"):
		Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```

If you keep the yield() line the mouse will be invisible when it switches to confined.
If you remove the yield() line the mouse will be visible when it switches to confined. (move mouse to see it)

For my game I was after a confined mouse mode with a hidden cursor that isn't restricted to the center of the screen the way captured does. So I will keep the yield(), but this seems like it could be an obscure bug in the engine which is why I'm reporting it.

**Comment by TheDuriel** [comment] 2019-04-10 07:32
Using yield() in ready is generally not a good idea, and might contributing to the odd behavior you are experiencing.

**Comment by ludorverr** [comment] 2019-04-10 08:17
It looks like I can recreate the issue without yield() in ready.

```
func _input(event):
	if Input.is_action_pressed("ui_right"):
		Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	if Input.is_action_pressed("ui_accept"):
		Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```
1. Press ui_right key.
2. Press ui_accept key.
Mouse remains hidden.

In the help file for MOUSE_MODE_CONFINED it says: "Makes the mouse cursor visible but confines it to the game window."
So I would assume that if you cannot see the cursor after setting mouse mode to CONFINED then this is a bug.
There could potentially be games out there that rely on this behaviour to hide the cursor. (just as I am tempted to)

This has the same bug:
```
func _input(event):
	if Input.is_action_pressed("ui_accept"):
		Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
		Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```

But this works fine, no bug:
```
func _ready():
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```

**Comment by Calinou** [comment] 2020-08-18 14:27
I can't reproduce this on 3.2.2 on Fedora 31, closing.

[confined_mouse_mode_bug.zip](https://github.com/godotengine/godot/files/5090951/confined_mouse_mode_bug.zip)

(Note that this bug may be OS-dependent due to mouse modes having OS-specific implementations.)

**Closed by Calinou** 2020-08-18 14:27 UTC
Labels: bug, topic:core, topic:input

**Comment by rainlizard** [comment] 2020-08-18 14:44
It is indeed fixed. A recent fix too, I checked and it looks like this bug was still present in 3.2.1
