### ISSUE TITLE
Manipulators for non-uniform scaling in 3d viewport?

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8523] opened 2017-04-24 21:19 UTC
Arch Linux, all Godot versions

Are there any plans to add manipulators for scaling objects non-uniformly in the 3d scene editor (scale mode) or maybe shortcuts to confine operations to certain axes like e.g. in blender? Right now there are only gizmos for translation and rotation, though scale is apparently always set uniformly. if you want to scale an object only by one or two axes, it's currently only possible via the inspector.

**Comment by n-pigeon** [comment] 2017-04-25 06:39
+1 must have for proper 3D work.

**Comment by eon-s** [comment] 2017-04-26 03:00
Related/duplicate of #7419

**Closed** 2017-04-26 05:37 UTC
Labels: feature proposal, junior job, topic:editor
