### ISSUE TITLE
Infinite external editor instances spawned when starting the engine.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#19841] opened 2018-06-29 16:46 UTC
**Searched previously:**
https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+infinite+external+editor

**Godot version:**
latest master b7f17a1

**OS/device including version:**
Windows 10

**Issue description:**
I was going through the C# Introduction.

Using a separate, working build of the engine, I set the external text editor path to be my Code.exe file for VS Code and toggled "Use External Editor" on. I did not supply any arguments to it (possibly a documentation problem if this is the cause of the Issue).

I then closed the editor after setting up the external text editor assignment so that I could checkout master.

I did a fresh pull. Started compilation. When it finished, I started it up again, only this time it started spawning Code.exe windows in an infinite loop. I had to force-close the Godot Editor in order for it to stop generating instances.

**Edit:** Looks like this is happening even when I re-use the official binary of Godot 3.0.3. It may not even be an issue with the editor itself and is instead an issue with the parameters specified for VS Code, or just using VS Code somehow...

**Edit:** I tried it using the 3.0.3 binary again, but this time using Atom instead of VS Code, with no exec args. Same issue happened.

**Steps to reproduce:**
1. Get a copy of master at b7f17a1 (or maybe a different version if it bugs during step 3?).
2. Compile and run it.
3. Setup VS Code as the external editor with no arguments.
4. Restart the engine instance / bootup an instance of the compiled b7f17a1 engine.

**Comment by Anutrix** [comment] 2019-07-09 12:11
Couldn't reproduce with Notepad++ with latest master https://github.com/godotengine/godot/commit/8d6a95347537c5e3084f269bdf98d1128b67b29b on Windows 10 1903.

**Comment by Anutrix** [comment] 2019-07-09 12:36
Couldn't reproduce with Microsoft Visual Studio 2017 with latest master 8d6a953 on Windows 10 1903.
But it has the issue of creating a new instance of Visual Studio whenever a script is opened in Godot instead of just shifting the focus to already open instance of Visual Studio.

**Comment by KoBeWi** [comment] 2020-08-24 23:13
Can anyone still reproduce this bug in [Godot 3.2.3 rc4](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-4) or any later release?

**Comment by Anutrix** [comment] 2020-08-25 05:52
I want to add a note which may or may not be related to issues. Few older versions of Visual Studio 2019 (pre16.4 at least) had a bug where it would spawn multiple instances and be stuck with "Modified by external tools." popup window. After this, all VS windows would turn unresponsive.
Note that I could only reproduce it with Unity 2020.x but the bug was in VS itself which is why I mentioned it here.

**Comment by KoBeWi** [comment] 2020-09-28 16:29
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:29 UTC
Labels: bug, topic:editor

**Comment by Joy-less** [comment] 2025-12-18 02:30
Very old issue, but this happened to me on Godot 4.5.1 when opening my Godot project. About 20+ instances of VSCode were started which had to be stopped manually. I think this may have been caused by VSCode trying to update when launched. I can't reproduce it though, but might be worth looking into if someone else reports the same issue.

**Comment by AThousandShips** [comment] 2025-12-18 09:22
If you end up being able to replicate it please open a new report!
