### ISSUE TITLE
Can not build godot on Linux Mint Mate 18.2 x86_64

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#13296] opened 2017-11-25 23:52 UTC
**Issue description:**
```bash
$ scons platform=x11
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 50%] Compiling ==> drivers/unix/os_unix_global_settings_path.gen.cpp
drivers/unix/os_unix_global_settings_path.gen.cpp:3:44: error: no 'String OS_Unix::get_global_settings_path() const' member function declared in class 'OS_Unix'
 String OS_Unix::get_global_settings_path() const {
                                            ^
scons: *** [drivers/unix/os_unix_global_settings_path.gen.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by NathanWarden** [comment] 2017-11-25 23:56
If I'm not mistaken, I believe that's an old gen file that needs to be deleted.

**Comment by toby3d** [comment] 2017-11-26 00:05
I need re-clone this repo?

**Comment by Kornelijus** [comment] 2017-11-26 00:08
duplicate of #13076
`rm -f drivers/unix/os_unix_global_settings_path*` should fix it.

**Comment by vnen** [comment] 2017-11-26 00:14
Duplicate of #13076.

**Closed by vnen** 2017-11-26 00:14 UTC
