### ISSUE TITLE
Parser bug in V4.0 alpha.15 on macOS

### ISSUE THREAD

**Issue by tservas** [godotengine/godot#65335] opened 2022-09-04 18:00 UTC
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

MacOS 11.8.6, Intel HD Graphics 5000

### Issue description

Starting the attached MRP results in several errors being printed in the debug output. Two of them being the following

```
E 0:00:41:0328   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:656 @ resolve_class_interface()
```

```
E 0:00:41:0328   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4049 @ is_type_compatible()
```

It says that these errors should be reported. So here you go.
The parser errors show up on my iMac with macOS 12.5 too.

The other errors

```
E 0:00:10:0520   _debug_messenger_callback:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140212565260800
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:171 @ _debug_messenger_callback()
E 0:00:10:0520   render_pipeline_create: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
  <C++ Error>    Condition "err" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:6844 @ render_pipeline_create()
E 0:00:40:0701   _debug_messenger_callback:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140212548009984
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:171 @ _debug_messenger_callback()
E 0:00:40:0701   render_pipeline_create: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
  <C++ Error>    Condition "err" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:6844 @ render_pipeline_create()
```

seem to have another source related to Vulkan.
I am currently working on my old MacBook Air. The vulkan related errors don't show up on my iMac (macOS 12.5).

### Steps to reproduce

Parser Bugs:
- Open the attached MRP (Edit-Mode) and look at the output (Output tab)
- Additionally playing the main scene also produces the errors

Vulkan related bugs:
- Play the main scene on a MacBook Air Intel Graphics 5000.
- Look at the debug output to see the vulkan related errors.

### Minimal reproduction project

[parser_bug.zip](https://github.com/godotengine/godot/files/9485202/parser_bug.zip)

**Comment by Calinou** [comment] 2022-09-04 18:38
Related to https://github.com/godotengine/godot/issues/58542.

**Comment by clayjohn** [comment] 2022-11-17 07:38
Duplicate of #58542

**Closed by clayjohn** 2022-11-17 07:38 UTC
Labels: bug, topic:gdscript
