### ISSUE TITLE
TextureRegion Snap doesn't update upon selection

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#35280] opened 2020-01-18 13:37 UTC
**Godot version:**
3.2.rc1

**OS/device including version:**
Solus 4 Gnome

**Issue description:**
When selecting a new `Snap Mode` in the TextureRegion plugin's tab, it doesn't automatically update the canvas to that mode. We have to select another node, then come back to the one we want to define a TextureRegion to have the plugin updated to the mode selected

**Steps to reproduce:**
1. Create a 2D scene
2. Add a Sprite node
3. Add a Texture to it
4. Turn on `region_enabled`
5. Open the TextureRegion tab
6. Change the Snap Mode

**Comment by YeldhamDev** [comment] 2020-01-19 13:06
Unless I misunderstood the issue, I'm unable to reproduce this:
![Peek 2020-01-19 10-04](https://user-images.githubusercontent.com/30739239/72681526-6d493b80-3abc-11ea-9cc4-daebd6f14b98.gif)

**Comment by henriiquecampos** [comment] 2020-01-19 14:50
@YeldhamDev try to follow the reproducing steps without setting a TextureRect before changing the mode.

Set `rect_region_enabled` to true, immediately change the Snap Mode from None to, e.g., Autoslice

**Comment by YeldhamDev** [comment] 2020-01-19 15:20
@henriiquecampos I'm sorry, but everything still works as expected in my end...

This is the second bug that happens to you that hides itself from me, I wonder if there's something deeper.

**Comment by akien-mga** [comment] 2020-01-19 15:26
> This is the second bug that happens to you that hides itself from me, I wonder if there's something deeper.

Possibly an editor or project setting?

**Comment by henriiquecampos** [comment] 2020-01-19 17:14
Seems this happens particularly to AutoSlice, the sliced rects don't update, at least visually.

[Video with a project set from scratch](https://youtu.be/58Pfst6ybRs)

**Comment by YeldhamDev** [comment] 2020-01-19 17:46
Repeated each action in the video in a fresh project, still nothing. So the problem isn't in the project settings.

The only thing really different between us that I can see is that you use Gnome and I Plasma, but I can't imagine how would that affect anything.

**Comment by tom-jk** [comment] 2020-07-18 15:47
The autoslice bug has since been fixed (#37614). I cannot reproduce any issues with changing to it or the other textureregion snap modes when following the steps given here, in Godot 3.2.2.stable.

@henriiquecampos can you still reproduce this issue?

**Comment by henriiquecampos** [comment] 2020-07-21 17:57
@tom-jk nope, seems like it's fixed. Thanks a lot.

**Comment by akien-mga** [comment] 2020-07-21 18:08
Thanks, closing then.

**Closed by akien-mga** 2020-07-21 18:08 UTC
Labels: bug, confirmed, topic:editor
