### ISSUE TITLE
C# StringExtensions has some "missing methods"

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot#29338] opened 2019-05-31 10:29 UTC
**Godot version:**
3.1.1 C# x64

**OS/device including version:**
Windows 10/7

**Issue description:**
[Attempted to access a missing method.](https://i.imgur.com/kK4o3UR.png)
[It happens for all of the methods, that would call this enlisted methods.](https://i.imgur.com/CiIZnuv.png)
[Stackcalls without a try/catch](https://i.imgur.com/Rj96eQf.png)

**Steps to reproduce:**
1. Setup a basic C# Mono project.
2. Try using previously mentioned methods.

**Minimal reproduction project:**
[2D_Test.zip](https://github.com/godotengine/godot/files/3240880/2D_Test.zip)

**Comment by KoBeWi** [comment] 2020-07-31 19:39
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 16:40
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:40 UTC
Labels: bug, topic:mono
