### ISSUE TITLE
Script errors when trying to run exported project in 4.0 branch

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#47699] opened 2021-04-07 12:22 UTC
**Godot version:**
4.0.dev.custom_build. bc229cdf2

**OS/device including version:**
Ubuntu 20.04 CI

**Issue description:**

Project runs fine in editor, but after exporting shows errors and fails to run
Some of error messages
``` 
SCRIPT ERROR: Parse Error: Function "quit()" not found in base null.
          at: GDScript::reload (res://Autoload/Autoload.gd:56)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:832)
ERROR: Condition "register_funcs.has(p_name)" is true.
   at: add_register_func (modules/visual_script/visual_script.cpp:2604)
ERROR: Condition "!valid_type" is true. Continuing.
   at: start (main/main.cpp:2117)
ERROR: Condition "!p_source.is_set()" is true. Returning: true
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3362)
SCRIPT ERROR: Parse Error: Too many arguments for "is_parent_class()" call. Expected at most 0 but received 2.
          at: GDScript::reload (res://AutomaticBugs/ValueCreator.gd:359)
SCRIPT ERROR: Parse Error: Too many arguments for "is_parent_class()" call. Expected at most 0 but received 2.
          at: GDScript::reload (res://AutomaticBugs/ValueCreator.gd:359)
```

Full CI log - https://github.com/qarmin/RegressionTestProject/pull/37/checks?check_run_id=2281171466

**Steps to reproduce:**
Export project in 4.0 branch and try to run it
CI instructions - https://github.com/qarmin/RegressionTestProject/blob/4.0/.github/workflows/linux_builds_swiftshader_exported.yml

**Minimal reproduction project:**
https://github.com/qarmin/RegressionTestProject/tree/4.0

**Comment by lyuma** [comment] 2021-08-05 19:29
seems to get past the original error. but I'm having some issues with the autoloads being null...

```
600 choosen classes from all 797 classes.

#################### AESContext ####################
SCRIPT ERROR: Invalid set index 'number' (on base: 'Nil') with value of type 'int'.
          at: parse_and_return_objects (res://AutomaticBugs/ParseArgumentType.gd:21)
WARNING: A Thread object has been destroyed without wait_to_finish() having been called on it. Please do so to ensure correct cleanup of the thread.
ERROR:     at:  FATAL: Index p_index = 2102 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
~Thread (core/os/thread.cpp:122)
   at: operator[] (./core/templates/vector.h:49)
Segmentation fault
```

Regarding the "`WARNING: A Thread object has been destroyed without wait_to_finish`", I'm running into a very similar issue on our project (with 430 .gd files!!). I'd like to use this as a reproduction case for that error.  It's not 100% reliable but seems like 80% reliable.

**Comment by akien-mga** [comment] 2023-02-26 20:47
Is this still reproducible in the latest builds?

**Comment by Mickeon** [comment] 2024-03-09 22:51
Asking the same question as above, a whole year layer?

**Comment by lyuma** [comment] 2024-03-10 03:43
I re-opened the same RegressionTestProject I had on disk which had given the Segmentation fault and I can confirm that this problem no longer happens on the version I tested (4.2.1 stable) even after fixing the missing types and such.

Because it appears to be solved, I will close the issue. Comment or open a new issue if there is still a problem.

**Closed by lyuma** 2024-03-10 03:43 UTC
Labels: bug, topic:gdscript, regression
