### ISSUE TITLE
Downloading export templates through editor much, much slower than through browser

### ISSUE THREAD

**Issue by Nallebeorn** [godotengine/godot#15950] opened 2018-01-21 18:57 UTC
**Godot version:**
Godot 3.0 RC2

**OS/device including version:**
Windows 10

**Issue description:**
For me, downloading the export templates through the editor's interface is painfully slow, even though downloading through Firefox takes less than a minute. After starting the download in the editor, I could open Firefox, go to godotengine.com, find the blog post announcing Release Candidate 2 and fully download the .tpz from the URL provided, and by the time I was done Godot had only reached 5%.

I initially selected the HTTPS mirror in both cases, but the HTTP one doesn't appear to be any faster.

(This is obviously not a blocker, so I realized it won't get fixed before the 3.0.0 release... But it's something to look into, since this makes downloading the templates from the editor *less* convenient than the old way)

**Comment by poke1024** [comment] 2018-01-24 18:39
May I ask from inside which project you did that download? I had a similar effect inside the platformer demo and found out that it was actually particles hogging my cpu (see https://github.com/godotengine/godot/issues/15932#issuecomment-359269487).

**Comment by akien-mga** [comment] 2018-01-24 18:42
I've seen the same slow download each time I used the feature myself, including in near-empty test projects with just a Sprite and a couple Controls.

**Comment by Calinou** [comment] 2018-01-26 16:56
Some other users have confirmed this on Discord with 3.0 RC3.

**Comment by kurtisharms** [comment] 2018-01-26 17:07
I can confirm this problem with a completely empty Godot project.

I have a 30Mbps internet connection, and a direct download with my browser over HTTP or HTTPS is fine. But the editor downloader is extremely slow over both HTTP and HTTPS. Tested with RC3 on Windows 10 x64.

**Comment by MattUV** [comment] 2018-01-30 22:02
It is also really slow to download from the asset library.
I realize that the download progress is updated at every frame. Maybe that's what slows everything. it could be good to update it every 1 or 2 seconds maybe

**Comment by dragmz** [comment] 2018-02-04 12:17
I think this is because of buffer reallocation in HttpRequest::_update_connection():

    body.append_array(chunk);

It's probably the best to download to file instead of memory but I'd suggest merging #16385 first to get better file write performance.

**Comment by akien-mga** [comment] 2018-03-02 23:37
Fixed by #16430.

**Closed by akien-mga** 2018-03-02 23:37 UTC
Labels: bug, confirmed, topic:editor, topic:network
