### ISSUE TITLE
All values greater than 52 bits give rise to calculation errors

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#38682] opened 2020-05-12 00:34 UTC
**Godot version:**
Godot_v3.2.1-stable_win64

**OS/device including version:**
Windows 7

**Issue description:**
All values greater than 52 bits give rise to calculation errors

**Steps to reproduce:**
copy paste the following lines into the script, run it, and check the local variables

	var int_50bit = 1125899906842623
	var int_51bit = 2251799813685247
	var int_52bit = 4503599627370495
	
	var int_53bit = 9007199254740991
	var int_54bit = 18014398509481983
	var int_55bit = 36028797018963967
	var int_56bit = 72057594037927935
	var int_57bit = 144115188075855871
	var int_58bit = 288230376151711743
	var int_59bit = 576460752303423487
	var int_60bit = 1152921504606846975
	var int_61bit = 2305843009213693951
	var int_62bit = 4611686018427387903
	var int_63bit = 9223372036854775807
	var int_64bit = 18446744073709551616

**Minimal reproduction project:**
![image](https://user-images.githubusercontent.com/10380658/81625178-c25ce480-9400-11ea-9ec9-96775db5b233.png)

**Comment by Zylann** [comment] 2020-05-12 00:48
Those values are shown in `SpinBox` controls. Those controls use a `double` to represent numbers, not `int64`, because they can also support decimal ones. It could be that `double` (or the code used to print them) cannot handle such large numbers.

**Comment by OlexiyKravchuk** [comment] 2020-05-12 01:30
@Zylann 
Even if the control is used double, it does not clarify the change in the state of the bits.
But I'm talking about calculations, I found this bug when I worked with bitwise operations "|, &, ~, ^" and bitwise shift "<<, >>", I couldn’t understand for a long time why the calculations were wrong, but then gradually increasing the number I found out that all bits in int after 52 are rounded in the wrong way, and this led to a heap of unforeseen errors in further calculations.

**Comment by Calinou** [comment] 2020-05-12 07:18
Duplicate of #33095.

**Closed by Calinou** 2020-05-12 07:18 UTC
