### ISSUE TITLE
Constant variables are not treated as constant expressions after second inheritance from the base class

### ISSUE THREAD

**Issue by RedouxG** [godotengine/godot#64542] opened 2022-08-17 17:18 UTC
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

Creating a base class that defines constant or enum variable and inheriting it second hand from another class, code editor stops treating the base class variable as a constant expression when trying to create a new constant that consists of a base class constant.

Attempting to create a constant variable in the third class that consists of constant defined in the first class returns a constant expression error. Doing the same in 2nd class does not return this error and works fine.

### Steps to reproduce

1) Create base class with a constant or enum 
2) Create 2nd class that inherits the base class
3) Create third script that inherits the 2nd class, and define a new constant variable that consists of base class constant variable

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/9364809/bug.zip)

**Comment by Calinou** [comment] 2022-11-16 21:00
Duplicate of https://github.com/godotengine/godot/issues/68251.

**Closed by Calinou** 2022-11-16 21:00 UTC
Labels: bug, topic:gdscript
