### ISSUE TITLE
C# StreamTexture is never freed from VRAM

### ISSUE THREAD

**Issue by LauPhi** [godotengine/godot#65392] opened 2022-09-06 02:18 UTC
### Godot version

v3.5.stable.mono.official [991bb6ac7]

### System information

Windows 10, GLES3

### Issue description

When loading a StreamTexture from C# script, the resource is never freed from VRAM when the variable is not referenced anymore. 
 
![Capture](https://user-images.githubusercontent.com/14290756/188532963-ffbfa50a-549e-44ae-afaa-54a0c1b04b82.PNG)

I saw that this looks like https://github.com/godotengine/godot/issues/62224 but I am not sure it may be related because this is on v3.5.

### Steps to reproduce

Steps to reproduce
- Load a StreamTexture from an imported texture.
- Do not reference this variable anymore.
- It should be removed from VRAM, it is not.

### Minimal reproduction project

[VRAM.zip](https://github.com/godotengine/godot/files/9492799/VRAM.zip)

**Comment by Calinou** [comment] 2022-09-06 02:20
Related to https://github.com/godotengine/godot/issues/36649 (likely the same cause).

**Comment by LauPhi** [comment] 2022-09-06 02:21
It does not happen in GDScript by the way.

**Comment by KietNguyen10112000** [comment] 2022-09-06 04:56
Maybe, this isn't a bug, it's about the Mono C# garbage collector. It seems 160MB isn't large enough for Mono to perform GC.

**Comment by LauPhi** [comment] 2022-09-06 12:41
Triggering the garbage collector manually does not free these resources.

**Comment by KietNguyen10112000** [comment] 2022-09-06 13:52
Maybe, something that prevent Mono to collect these managed objects in _Ready call (it can be asych tasks or some internal things of Godot, ...). But when you perform GC in the frame loop, these resources are freed and everything just fine.
![image](https://user-images.githubusercontent.com/57041977/188651436-cd29b851-a621-42f3-ba8e-a67c7deebfaa.png)
![image](https://user-images.githubusercontent.com/57041977/188651599-f9463673-4be5-4105-bf17-c1a69109273a.png)

**Comment by Calinou** [comment] 2022-09-06 16:11
Triggering the GC won't work; you need to call `Dispose` on the StreamTexture instance instead.

**Comment by KietNguyen10112000** [comment] 2022-09-06 16:43
Hmp, I mean Mono's GC will free these objects in the future (and this is not a bug). C# is garbage collected language, so call dispose to manually release resource is not necessary and sometime unsafe (I meet this issue before :D, so hope no one wastes 3 days to solve the bug is not a bug)

**Comment by LauPhi** [comment] 2022-09-07 20:00
@Calinou 
This does not seem related to resources, as the following code produces the same behavior, without incrementing the resources.
Also this does not seem related to the garbage collector, because it can also fill up you VRAM entirely without the guard I put in.

```csharp
using Godot;
using System;

public class MainScene : Node
{
    private UInt64 GetVRAMMB()
    {
        UInt64 vram = (UInt64)Performance.GetMonitor(Performance.Monitor.RenderTextureMemUsed);
        return vram / 1024 / 1024;
    }

    private UInt64 GetResourceCount()
    {
        return (UInt64)Performance.GetMonitor(Performance.Monitor.ObjectResourceCount);
    }

    private void PrintInfo()
    {
        GD.Print(String.Format("Resources: {0}.", GetResourceCount()));
        GD.Print(String.Format("VRAM:      {0} MB.", GetVRAMMB()));
    }

    private void CreateTexture()
    {
        Image image = new Image();
        image.Create(1024, 1024, false, Image.Format.Rgba8);

        ImageTexture texture = new ImageTexture();
        texture.CreateFromImage(image);
    }

    public override void _Process(float delta)
    {
         if(GetVRAMMB() >= 2048)
             return;

        CreateTexture();
        PrintInfo();
    }
}
```

**Comment by KietNguyen10112000** [comment] 2022-09-08 02:29
`image.Create(1024, 1024, false, Image.Format.Rgba8)` this line will create 1K texture on underlying Godot engine memory (or system memory) and just some bytes of Image object will be allocated on Managed Heap of C# runtime, so these managed bytes is not large enough for Mono to trigger garbage collector (if I remember correctly C# manage heap is about 2GB).

> [https://www.mono-project.com/docs/advanced/garbage-collector/sgen/](url)
> The garbage collector will trigger a collection when there is no space anymore in the memory already requested from the operating system. 

You can manually trigger garbage collector and see what happen.
In normal use, large objects will be created at initialization time (old generation), and just small objects (young generation) will be spawned at runtime, this's also the psychology behind generation garbage collector design.

**Comment by KietNguyen10112000** [comment] 2022-09-08 02:33
And trust me, C# and Godot do nothing wrong about memory management (at least at this time and idk the future :D)

**Comment by LauPhi** [comment] 2022-09-08 04:17
Indeed, calling the garbage collector with:
```csharp
GC.Collect();
```
Just after the reference disposal seems to free up the VRAM.
Also, calling ```ImageTexture.Dispose()``` or ```using``` with the IDisposable from Godot.Object works too.

I do hope that this will not mean I will have to call the GC manually to free up the VRAM in normal situations, because I intent to load textures this way to circumvent https://github.com/godotengine/godot/issues/65394.

Thank you @KietNguyen10112000.
Please @Calinou tell me if this is considered normal behavior so this can be closed.

**Comment by raulsntos** [comment] 2022-09-08 09:18
The GC does not necessarily collect resources right away, they should be collected eventually but if you need them to be freed as soon as possible you should be using the `Dispose` method or an `using` statement. It is in fact a good practice to always dispose types that implement `IDisposable`. See https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=net-6.0#remarks.

I don't recommend calling `GC.Collect()` for other than debugging purposes. The recommendation is to use `using` statements or the `Dispose` method which should free your resources as soon as possible (but may not happen immediately).

If disposing the objects from C# does not eventually free them that would be a memory leak so forcing the GC to run allows us to check if it is indeed a memory leak or it's just that the GC hasn't collected them yet:

```csharp
GC.Collect(GC.MaxGeneration);
GC.WaitForPendingFinalizers();
```

According to the comments from @KietNguyen10112000 and @LauPhi it seems that triggering the GC manually **does** free the resources which means there is **no** memory leak so I'll close this issue, but let me know if I misunderstood your comments.

**Closed by raulsntos** 2022-09-08 09:18 UTC
Labels: bug, topic:dotnet
