### ISSUE TITLE
3D Editor inconsistent lines color

### ISSUE THREAD

**Issue by Creuilcreuil** [godotengine/godot#17270] opened 2018-03-05 01:51 UTC
**Godot version:** 
3.0.2

**OS/device including version:** 
Ubuntu LTS 16.04.4

**Issue description:** 
3d lines colors are inconsistent

![godot_bug_lines](https://user-images.githubusercontent.com/12054179/36954039-7d363156-201f-11e8-9008-fd1b9dd7fc21.gif)

**Steps to reproduce:**
Open the 3d editior

**Comment by eon-s** [comment] 2018-03-06 23:58
Graphics card? 
Looks like a duplicate of #17029

**Comment by leotada** [comment] 2018-03-07 00:06
Same to me with AMD RX480 using open source driver AMDGPU.

**Comment by vnen** [comment] 2018-03-07 02:13
Closing as duplicate of #17029.

**Closed by vnen** 2018-03-07 02:13 UTC
Labels: bug, topic:rendering
