### ISSUE TITLE
A function to change parent

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#5581] opened 2016-07-07 07:33 UTC
A function to change parent could be useful
Node.change_parent(ParentNode)

There is a workaround to Node.add_child(Node) then Node.quee_free() the old one, but it will loose all its instanced values.

**Comment by akien-mga** [comment] 2016-07-07 07:46
```
parent_node1.remove_child(child_node)
parent_node2.add_child(child_node)
```
:)

**Comment by akien-mga** [comment] 2016-07-07 07:49
Also to some extent a duplicate of #1905, so closing.

**Closed by akien-mga** 2016-07-07 07:49 UTC
Labels: discussion, feature proposal, topic:core

**Comment by bojidar-bg** [comment] 2016-07-07 07:51
@akien-mga Ahh.. I knew it there was a dupe :smile:

**Comment by akien-mga** [comment] 2016-07-07 08:18
See also #1943, #1949, #2657 and #3290..

**Comment by akien-mga** [comment] 2016-07-07 08:20
Bottom line, yes adding a helper function to reparent a node would be cool, but it wouldn't automagically solve the above-mentioned issues (just see how many commits the other guys did in their PRs that did not get merged).

**Comment by Dillybob92** [comment] 2016-12-01 09:08
Haha. I think the gotcha is most people forget that if you remove the child node you can still access it and move it wherever.  What I first thought was if we do `remove_child` that node is poofed permanently, which isn't the case. We are free to re-parent that sucker wherever we want :D

**Comment by bojidar-bg** [comment] 2016-12-01 09:37
Maybe something like `detach_child` would be more informative?
