### ISSUE TITLE
WorkerThreadPool::_add_group_task crash

### ISSUE THREAD

**Issue by fire** [godotengine/godot#63879] opened 2022-08-03 14:48 UTC
### Godot version

3ea9a7daea58c825a78ce1b5ed5d2becc2f84966 + 50 branches

### System information

popos 22.04 Linux, Vulkan, NVIDIA 3000 series

### Issue description

![image](https://user-images.githubusercontent.com/32321/182637938-ea75b37b-9f28-4a03-8f39-49c57493e1ef.png)

Godot Engine crashes.

```
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
memdelete<WorkerThreadPool::BaseTemplateUserdata>(WorkerThreadPool::BaseTemplateUserdata * p_class) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/os/memory.h:108)
WorkerThreadPool::_add_group_task(WorkerThreadPool * this, const Callable & p_callable, void (*)(void *, uint32_t) p_func, void * p_userdata, WorkerThreadPool::BaseTemplateUserdata * p_template_userdata, int p_elements, int p_tasks, const String & p_description) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/object/worker_thread_pool.cpp:303)
WorkerThreadPool::add_template_group_task<GodotStep3D, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr)>(GodotStep3D*, void (GodotStep3D::*)(unsigned int, void*), decltype(nullptr), int, int, bool, String const&)(WorkerThreadPool * this, GodotStep3D * p_instance, void (GodotStep3D::*)(GodotStep3D * const, unsigned int, void *) p_method, decltype(nullptr) p_userdata, int p_elements, int p_tasks, bool p_high_priority,  p_description) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/object/worker_thread_pool.h:181)
GodotStep3D::step(GodotStep3D * this, GodotSpace3D * p_space, real_t p_delta) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_3d/godot_step_3d.cpp:346)
GodotPhysicsServer3D::step(GodotPhysicsServer3D * this, real_t p_step) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_3d/godot_physics_server_3d.cpp:1615)
PhysicsServer3DWrapMT::thread_step(PhysicsServer3DWrapMT * this, real_t p_delta) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:40)
CommandQueueMT::_flush(CommandQueueMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/templates/command_queue_mt.h:373)
CommandQueueMT::wait_and_flush(CommandQueueMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/templates/command_queue_mt.h:414)
PhysicsServer3DWrapMT::thread_loop(PhysicsServer3DWrapMT * this) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:59)
PhysicsServer3DWrapMT::_thread_callback(void * _instance) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/servers/physics_server_3d_wrap_mt.cpp:47)
Thread::callback(Thread * p_self, const Thread::Settings & p_settings, Thread::Callback p_callback, void * p_userdata) (/home/elee/Documents/chibifire/groups-engine-workspace/godot/core/os/thread.cpp:75)
execute_native_thread_routine (Unknown Source:0)
libc.so.6!start_thread(void * arg) (pthread_create.c:442)
libc.so.6!clone3() (clone3.S:81)
```

### Steps to reproduce

For our project when we use the background loader and the download file is 200+ megabytes.

### Minimal reproduction project

I wasn't able to reduce our project maybe we can try the previous demo from https://github.com/godotengine/godot/issues/56776

**Comment by akien-mga** [comment] 2022-08-03 14:54
Duplicate of #63671.

**Closed by akien-mga** 2022-08-03 14:54 UTC
