### ISSUE TITLE
Typehints on inner classes don't recognize the class if created from the GDScript resource

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#61567] opened 2022-05-31 15:00 UTC
### Godot version

v4.0.alpha.custom_build.532e253a7

### System information

Linux, Vulkan, 1070M

### Issue description

I've been working on porting the Nakama client to Godot 4. In Godot 3, it uses this pattern where there's a bunch of "namespaces" (*.gd scripts with lots of inner classes - they are automatically generated from Swagger definitions) and some generic methods that take the inner class as an argument, so that it knows what class to wrap the response from the server in.

Anyway, while working on this, I discovered that typehints on these inner classes don't work (ie. they won't correctly recognize the class as being the class) if they are created from the GDScript resource. I get a runtime error like:

```
Trying to return value of type "InnerClass1" from a function which the return type is "MyNamespace"
```

This may be related to issue #61635 

### Steps to reproduce

I've included a minimal reproduction project below, but here is the key code (from the Main.gd in the project) to illustrate the problem:

```gdscript
extends Node2D

func _ready():
	# This works fine!
	var n = create_normal_class("Normal")
	print (n)
	
	# This gets the runtime error :-(
	var i = create_inner_class("Inner")
	print (i)

func _do_and_create(p_value: String, p_class: GDScript):
	return p_class.new(p_value)

func create_normal_class(p_value: String) -> MyClass:
	return _do_and_create(p_value, MyClass)

func create_inner_class(p_value: String) -> MyNamespace.InnerClass1:
	return _do_and_create(p_value, MyNamespace.InnerClass1)
```

### Minimal reproduction project

[godot-4-typehint-bug.zip](https://github.com/godotengine/godot/files/8806295/godot-4-typehint-bug.zip)

**Comment by vnen** [comment] 2022-12-22 14:19
I cannot reproduce this on current master. It might have been fixed with other changes, so I'm closing this. If that's not the case let me know and I'll reopen.

**Closed by vnen** 2022-12-22 14:19 UTC
Labels: bug, topic:gdscript, regression
