### ISSUE TITLE
Atlas Merging Tool not working

### ISSUE THREAD

**Issue by filippo-fornai** [godotengine/godot#82995] opened 2023-10-08 11:41 UTC
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 11

### Issue description

Atlas Merge Tool is supposed to create a texture composed of the different textures of the chosen atlases. Instead it creates a transparent image of the **right size** 

### Steps to reproduce

Hp: Using 64x64 tiles png images. Every tile is a **single** image.

1. Create a new TileSet
2. Resizing Tile Size from 16x16 to 64x64 ( as the Tiles used are 64x64 )
3. drag and drop multiple images into TileSet tab
5. Images get imported without tiles created (possible problem?)
6. Manually create tiles clicking on [...] for each tile and selecting "Create Tiles in Non-Transparent Texture Region"
7. Use "Atlas Merging Tool" to create singular atlas from single image atlases
8. While selecting multiple atlases the preview of the output is empty
9. Click Merge
10. The resulting texture image is **transparent**, the atlas has correct size 

https://github.com/godotengine/godot/assets/85365023/19c0b9e3-8ef4-4c97-a2b9-02c3a1e31976

### Minimal reproduction project

[Github_issue.zip](https://github.com/godotengine/godot/files/12840543/Github_issue.zip)

**Comment by kleonc** [comment] 2023-10-08 18:45
Duplicate of #80870, fixed since `v4.2.dev4` by #80943 (which is marked for cherry picking to 4.1).

> 4\. Images get imported without tiles created (possible problem?)

This part is also fixed since `v4.2.dev4` (by #79678, not marked for cherry picking to 4.1).

**Closed by kleonc** 2023-10-08 18:45 UTC
