### ISSUE TITLE
Weird undo/redo behavior with backspace/delete

### ISSUE THREAD

**Issue by wareya** [godotengine/godot#77442] opened 2023-05-24 15:34 UTC
### Godot version

4.0.3

### System information

Windows 10

### Issue description

In Godot 4's script editor, when I delete things with backspace or the delete key in the text editor, they're all bundled together into a single undo/redo operation, regardless of what kinds of cursor navigation have happened in the middle. This is extremely unintuitive and unlike any other text editor I use, including the Godot 3 script editor. I cannot find an editor option controlling this; if there is one, it's poorly labeled.

### Steps to reproduce

Open a script, select a line, use backspace to delete it, select another line far away, use backspace or delete to delete it, then press ctrl+Z exactly once. Both line deletions will be undone. Do not do any other operations. Do not use "cut"/ctrl+x instead of backspace/delete; "cut" works as expected.

https://github.com/godotengine/godot/assets/585488/c7b8ff19-a3c6-4236-a494-e53857f77755

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-05-24 15:36
Duplicate of #77101 (same cause)

**Closed** 2023-05-24 16:34 UTC
