### ISSUE TITLE
Saving Requires a Root Node

### ISSUE THREAD

**Issue by TheRealCatherine** [godotengine/godot#28040] opened 2019-04-15 03:04 UTC
**Godot version:**
3.1-stable-win64

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When only .gd files are open in the editor and user is viewing the script editor tab, allow saving with ctrl-s without "saving requires a root node" warning.

When starting a project I often start by creating .gd script base class files. While creating these I press Ctrl-S to save but it pops up "saving requires a root node" notices unless I create a dummy scene file to sit around. Then later in development I will have to open a scene file, and possibly accidentally mess with something in it, just to be able to use ctrl-s while editing .gd files.

**Steps to reproduce:**
Create a new project then create a new .gd script without making a scene. Open the new .gd file for editing, add something to it. Press CTRL-S

**Comment by homer666** [comment] 2019-04-15 07:20
Ctrl-Alt-S is the shortcut for saving only the open script, and will work without any scenes open. If you want, you can rebind that shortcut to also be Ctrl-S in Editor Settings, and it should "just work" in any context (there's probably some hidden consequence to this... but it worked fine from my limited testing of it.)

**Comment by KoBeWi** [comment] 2019-04-15 12:15
Looks similar to #28000

**Comment by akien-mga** [comment] 2019-04-15 12:27
Duplicate of #11801.

**Closed by akien-mga** 2019-04-15 12:27 UTC
