### ISSUE TITLE
i still think that rect2 no rotate with control is bug...

### ISSUE THREAD

**Issue by yuyubibibobibo** [godotengine/godot#35104] opened 2020-01-14 01:02 UTC
**Godot version:**
3.2 beta6
**OS/device including version:**
windows 10
**Issue description:**
control rotate 90,but global and locol rect2 is still 0 degree...
i think it is bug,if it be designed like this, it confuse me very much,
at least, rect2 Description in doc
Rect2 consists of a position, a size, and several utility functions. It is typically used for fast overlap tests.
so if our control can rotate, how can we text overlap...
**Steps to reproduce:**

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4056769/ReproductionProject.zip)

**Comment by clayjohn** [comment] 2020-01-14 01:41
Duplicate of https://github.com/godotengine/godot/issues/35043

As was explained in that issue. ``get_rect()`` returns a rect in local space. If you want to compare an object/point against it, you need to transform that point into the controls local space.

**Closed by clayjohn** 2020-01-14 01:41 UTC

**Comment by yuyubibibobibo** [comment] 2020-01-14 02:08
> Duplicate of #35043
> 
> As was explained in that issue. `get_rect()` returns a rect in local space. If you want to compare an object/point against it, you need to transform that point into the controls local space.

sure，get_rect is local space，get_mouse_position is local space too，it donot work...

**Comment by yuyubibibobibo** [comment] 2020-01-14 02:09
> > Duplicate of #35043
> > As was explained in that issue. `get_rect()` returns a rect in local space. If you want to compare an object/point against it, you need to transform that point into the controls local space.
> 
> sure，get_rect is local space，get_mouse_position is local space too，it donot work...same as global...

**Comment by yuyubibibobibo** [comment] 2020-01-14 03:39
> > > 重复[＃35043](https://github.com/godotengine/godot/issues/35043) 
> > > 正如这个问题进行了解释。`get_rect()`返回本地空间中的矩形。如果要比较一个对象/点，则需要将该点转换为控件的局部空间。
> > 
> > 
> > 当然，get_rect是局部空间，get_mouse_position也是局部空间，它不起作用...与全局空间相同...



> > > Duplicate of #35043
> > > As was explained in that issue. `get_rect()` returns a rect in local space. If you want to compare an object/point against it, you need to transform that point into the controls local space.
> > 
> > 
> > sure，get_rect is local space，get_mouse_position is local space too，it donot work...same as global...

i used get_rect().has_point(get_local_mouse_position),it is norect 

> > > Duplicate of #35043
> > > As was explained in that issue. `get_rect()` returns a rect in local space. If you want to compare an object/point against it, you need to transform that point into the controls local space.
> > 
> > 
> > sure，get_rect is local space，get_mouse_position is local space too，it donot work...same as global...

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4057230/ReproductionProject.zip)
