### ISSUE TITLE
C# tool scripts do not run property setters when property is of type Node

### ISSUE THREAD

**Issue by Tuckertcs** [godotengine/godot#76190] opened 2023-04-18 01:05 UTC
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Linux Mint 20.3 (Cinnamon)

### Issue description

Creating a tool script with exported properties works as intended if the type is anything but `Node`. In the case of `Node` properties, the setter code is never run. Properties of type `int` or `Resource`, for example, work fine.

### Steps to reproduce

Create the following C# script and add it to a Node in the editor:

```c#
using System;
using Godot;

[Tool]
public partial class Test : Node
{

    int testInt;
    [Export] public int TestInt
    {
        get { return testInt; }
        set
        {
            // This code runs:
            testInt = value;
            GD.Print("Int was set!");
        }
    }

    Resource testResource;
    [Export] public Resource TestResource
    {
        get { return testResource; }
        set
        {
            // This code runs:
            testResource = value;
            GD.Print("Resource was set!");
        }
    }

    Node testNode;
    [Export] public Node TestNode
    {
        get { return testNode; }
        set
        {
            // This code does not run:
            testNode = value;
            GD.Print("Node was not set!");
            testNode = null;
            GD.Print("Node was not overridden to null!");
        }
    }
}
```

Now, edit the value of each property, in order.

Update `int`, add some `Resource`, then create a child Node and add it to `TestNode`.

### Expected Output:

The console should display the following:

```
Int was set!
Set TestInt
Resource was set!
Set TestResource
Node was not set!
Node was not overridden to null!
Set Node
```

The property values in the editor's inspector should reflect the values you set them to, except `TestNode` should be overridden to `null` and thus always display `<empty>`.

### Actual Output:

The console displays the following:

```
Int was set!
Set TestInt
Resource was set!
Set TestResource
Set metadata/_editor_prop_ptr_TestNode
```

The property values in the editor's inspector reflect the values you set them to. Even `TestNode` will not override to `null` and thus will display the value you set, rather than `<empty>`, like it should.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11256936/test.zip)

**Comment by Tuckertcs** [comment] 2023-04-18 01:11
Just updated to Godot version v4.0.2.stable.mono.official [7a0977ce2], in case the bug was fixed recently, but the issue persists.

**Comment by RedworkDE** [comment] 2023-04-18 08:18
Duplicate of #74141 (Also a C# specific duplicate was created 5h earlier as #76182)

**Comment by KoBeWi** [comment] 2023-04-18 12:49
Closing as duplicate.

**Closed by KoBeWi** 2023-04-18 12:49 UTC
