### ISSUE TITLE
3D models given scale -1 have strange looking normals

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#26710] opened 2019-03-06 15:23 UTC
**Godot version:**

3.1.10

**OS/device including version:**

**Issue description:**

When a 3D model is scaled X (-1), Y (1), Z (1) inside Godot the normals are looking strange afterwards.
For comparison when the same thing is done in Unity 2017.4 the normals look.. well normal afterwards.

Is this Godot behavior intended or not? 
Flipping a 3D model around in Godot using scale should not ruin the normals.

In the below image the problem is illustrated:
(The model in the middle was exported with inverted normals)
![godot](https://user-images.githubusercontent.com/15687516/53889896-7dcd0080-4027-11e9-8161-7e46dac311ba.jpg)

And for comparison in this next image the same scaling has been applied to a Dinosaur model in Unity and there are no problems with the normals.
![unity](https://user-images.githubusercontent.com/15687516/53890404-72c6a000-4028-11e9-86ca-181d75dfe818.jpg)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ace-Dragon** [comment] 2019-03-06 15:40
Is there is a good reason to want to have negative scales instead of just rotating the object?

If this is really needed, then perhaps Godot can have a few functions that would allow the normals to be re-calculated on command.

**Comment by bojidar-bg** [comment] 2019-03-06 15:53
Duplicate of #25696?

**Comment by jesperkondrup** [comment] 2019-03-07 07:15
@Ace-Dragon We have a few 3d characters that are rendered from the side view in a fight scene (like Tekken) and we want their "best side" to be facing the camera. 
We have not been able to flip the model + rig in Blender without weird animation results but it looks like we have to give it another go.

**Comment by Ace-Dragon** [comment] 2019-03-07 15:55
I see, then it would be useful for Godot to have a function that can recalculate mesh normals.

**Comment by clayjohn** [comment] 2019-04-18 06:15
Can you try this again but with the render flag "ensure_correct_normals"? I think that is all you need. By default Godot uses a shortcut for normal transformation and assumes scale is the same in all three directions "ensure_correct_normals" should be used with any non-uniform scale.

**Comment by jesperkondrup** [comment] 2019-04-23 07:20
@clayjohn Unfortunately we already tried this but it does not fix the problem.

**Comment by clayjohn** [comment] 2019-05-26 22:22
@jesperkondrup and @PullTheStrings Are you using GLES3 or GLES2

I am unable to reproduce this issue in GLES3.

**Comment by jesperkondrup** [comment] 2019-05-27 06:23
> @jesperkondrup and @PullTheStrings Are you using GLES3 or GLES2
> 
> I am unable to reproduce this issue in GLES3.

Good find @clayjohn I just tested this and you are 100% correct, we are using GLES2 and it's only in GLES2 I see the issue.

**Comment by clayjohn** [comment] 2019-05-30 14:54
Superseded by #29317

**Closed by clayjohn** 2019-05-30 14:54 UTC
Labels: bug, topic:rendering
