### ISSUE TITLE
Editor interface is broken by Tilemap

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#6879] opened 2016-10-20 15:11 UTC
Linux, 1280x1024, godot 2.1.1

What am I doing:
- create the project and open (editor starts maximized)
- add Tilemap node (all is ok)
- create new tileset for it in its inspector (bingo!)
- move mouse to the center of the window
- ...
- PROFIT

And when I unmaximize the window, UI won't scale itself horizontally anymore (when I resize the window),  it scales only vertically (may be this is the clue?)

After the bug occurred, I can't even move the right pane's splitter to the left, but if I add say node2d to the hierarchy and select it, I can resize the pane as I want (but UI won't fix tho), but upon selecting Tilemap, all reverts back (the resized right panel)

But if I switch from Tilemap to something other and unmaximize the window - UI 'cures' :laughing:

**Comment by curly-brace** [comment] 2016-10-21 13:45
got to know that on 16:9 screens it appears too, bat rarely. seems like turning on loDPI setting on 4:3 makes godot's UI behave like on 16:9, but still causes this bug on both ratios

**Comment by manokara** [comment] 2016-10-21 22:24
The controls have a minimum size and stuff gets clipped or rearranged when you resize the window, and that's not limited to Tilemap (it's just that its minimum size is quite big, apparently). It's not necessarily broken, but definitely could be enhanced. I use LoDPI on a 1920x1080 monitor, and the UI clips around 1300 px on the horizontal when the tilemap node is selected, and around 980 when it's another Node2D.

By the way, 1280x1024 is 5:4, but that doesn't make too much of a difference in this case I guess.

**Comment by curly-brace** [comment] 2016-10-22 07:39
yeah may be it is not broken, but needs enchancement.. but for now to work with tilemap in my 5:4 (or 4:3?) screen, i need resize window after i've finished working with tilemap node. and that's not much of convenience tho

**Comment by williamd1k0** [comment] 2016-10-22 08:01
I have the same problem on a 1024x786 monitor (4:3) .
I can't edit some script variables.

![image](https://cloud.githubusercontent.com/assets/10428035/19617915/3ddfbf18-981c-11e6-9e07-2f44a57037b1.png)

**Comment by Lebostein** [comment] 2016-10-30 17:45
Same problem here with 2.1 on Mac OS 10.10.5. Very anoying.

**Comment by bojidar-bg** [comment] 2016-11-24 09:52
Umh.. Isn't this a duplicate of #6879 to some extent?

**Comment by curly-brace** [comment] 2016-11-24 10:02
@bojidar-bg yeah, seems like it is

**Comment by bojidar-bg** [comment] 2016-11-24 10:08
@curly-brace Thanks for confirming :smile: 
Closing as duplicate of #6461.

**Closed by bojidar-bg** 2016-11-24 10:08 UTC
Labels: bug, topic:editor, usability
