### ISSUE TITLE
Too many array elements cause slow editor

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69704] opened 2022-12-07 06:33 UTC
### Godot version

4.0-beta7

### System information

win10

### Issue description

Unable to load it and run print it

![11](https://user-images.githubusercontent.com/112788136/206105791-62cf3dac-7e3a-40bb-b5a3-2ab6972e88b1.png)

### Steps to reproduce

![3333](https://user-images.githubusercontent.com/112788136/206105278-1d9b488c-d908-4f50-a422-59da1391c056.png)

### Minimal reproduction project

![55555](https://user-images.githubusercontent.com/112788136/206105771-67b6457a-1008-40a6-b382-3d524c077a80.png)

**Comment by Zireael07** [comment] 2022-12-07 07:50
Printing will always slow the editor down, the more the bigger the array is (more lines/more formatting work)

Use the debugger/remote scene tree instead of printing

**Comment by xiaoliang6669** [comment] 2022-12-07 07:53
I don't want to print, but I want to use it. As a result, I can only save the coordinates in a file and then read them, otherwise the editor will get stuck

**Comment by xiaoliang6669** [comment] 2022-12-07 07:55
Even if I save the coordinates in another script, loading and calling it will flash back

**Comment by Zireael07** [comment] 2022-12-07 08:02
You don't have to print it to editor to use it. I am loading a long list of stars from CSV w/o printing it.

Also make sure you save the list to some variable once you've loaded, this way you don't recreate the list every time...

**Comment by xiaoliang6669** [comment] 2022-12-07 08:06
> 您不必将其打印到编辑器即可使用它。我正在从CSV加载一长串星星，而无需打印它。
> 
> 还要确保在加载后将列表保存到某个变量中，这样您就不会每次都重新创建列表......

According to my test, when I write an array variable on the editor, it will be stuck if there are more than 2000 elements, and it will flash back when I read it

**Comment by akien-mga** [comment] 2022-12-07 10:07
For the last time, please upload a **minimal reproduction project** in your bug reports. Otherwise, we can't afford to spend time trying to recreate the potential issues that you claim exist without having any details on how to reproduce those issues.

If you say that the editor is slow when an array contains too many elements, please make a simple project which demonstrates this (single scene with a single script that has a big array which slows the editor) and attach it here as a zip.

Otherwise, we'll simply have to ignore your issues going further as they're all too low quality to work on.

**Comment by DissonantVoid** [comment] 2022-12-22 14:43
I made a reproduction project for what it's worth..
[slow_editor_recreation.zip](https://github.com/godotengine/godot/files/10287679/slow_editor_recreation.zip)
tried printing a file full of vectors with size of 140kb (just like OP). print just fine, can't reproduce

**Comment by akien-mga** [comment] 2022-12-22 14:59
Thanks for testing! Closing then. We can reopen if a minimal reproduction project that actually triggers the issue is provided.

**Closed by akien-mga** 2022-12-22 14:59 UTC
Labels: topic:core, needs testing

**Comment by omarfrinjary** [comment] 2024-04-14 10:28
you are right because the RAM usually be 16 GB and this file probably is 10 MG so it not so much
