### ISSUE TITLE
Godot 4.0 beta 1 - Can't run editor: "Assertion Failed"

### ISSUE THREAD

**Issue by nefrace** [godotengine/godot#65847] opened 2022-09-15 20:34 UTC
### Godot version

4.0 beta 1

### System information

Acer Nitro 5 on Windows 11, Ryzen 5 4600H, GTX 1650 Ti v.516.94

### Issue description

After clicking the executable, a white window appears with an error described on a screenshot below
![изображение](https://user-images.githubusercontent.com/18103556/190503047-57cdf289-d055-48ed-bc73-c3030d83e80b.png)

### Steps to reproduce

Just launch an exe file of Godot Engine

## Update
I've just tried to open Alpha 15 which worked fine before and it didn't open with the same error. Perhaps it's just some driver issue.

**Comment by Calinou** [comment] 2022-09-15 21:31
Do you have a laptop with hybrid graphics (specifically AMD integrated + NVIDIA dedicated)?

**Comment by yeet227** [comment] 2022-09-16 04:43
I do is that the issue

**Comment by nefrace** [comment] 2022-09-16 06:16
> Do you have a laptop with hybrid graphics (specifically AMD integrated + NVIDIA dedicated)?

Yes, but I've set up my settings to launch any program only on the dedicated Nvidia card.

**Comment by lsio8306** [comment] 2022-09-16 07:28
I have the same issue. First I thought my graphic card was too old (GTX560). Now, I think this is not the case. I did upgrade the driver.

**Comment by dwexel** [comment] 2022-09-17 05:05
same issue here, I also have a laptop with a AMD chip and NVIDIA graphics card (asus zepyrus g14)

**Comment by tulipan-it** [comment] 2022-09-24 12:16
I'm having exactly the same issue (same text in error description).
I have a laptop with
Processor:
AMD Ryzen 7 5800H with Radeon Graphics, 3201 Mhz, 8 Core(s), 16 Logical Processor(s)
Graphics card:
NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by nefrace** [comment] 2022-10-03 10:27
Small update about this issue:

When I go to Device Manager and shut down integrated AMD card and then try to launch Godot - all works perfectly. Then I can turn it on again and it still works until reboot.

**Comment by tulipan-it** [comment] 2022-11-28 08:07
It now works. 

When I tested for the first time (alpha 16 dated 2022-09-07) it crashed. When testing earlier this month with the beta version (beta4 dated 2022-11-01), it crashed. However, when testing again today with beta4 (v4.0.beta4.official [e6751549c]), it doesn't crash.

I interpret it as some drivers on my system has been updated, and happen to fix the issue. Either...
1. Windows 10
2. The graphics card: NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by nefrace** [comment] 2022-11-28 08:19
@tulipan-it it still doesn't work for me with Vulkan. If the project was set up to use OpenGL then it works.
Same config but with updated drivers: Windows 11, AMD Ryzen 4600H, GTX 1650 Ti v.526.98

**Comment by nefrace** [comment] 2022-12-09 17:55
Found a workaround which really works.
As said in [this article](https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus), you need to add the environment variable to your system with the name `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` and value of `1`.
After doing this all seems to work fine.

**Comment by tulipan-it** [comment] 2022-12-09 18:22
Glad you found a solution. I guess my AMD Radeon integrated GPU got updated drivers, and solved it for me.

**Comment by Calinou** [comment] 2022-12-09 18:39
Duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-12-09 18:39 UTC
Labels: bug, topic:rendering, topic:editor, crash
