### ISSUE TITLE
Viewports do not show the scene inside them

### ISSUE THREAD

**Issue by 244164401** [godotengine/godot#51976] opened 2021-08-22 09:44 UTC
### Godot version

v3.4 beta4.official [6a058cbf3]

### System information

Win11

### Issue description

Here is my node layout:

```
Node2D
    |- HBoxContainer
        |-ViewportContainer
            |-Viewport
                |- Camera2D
                |- Node2D (the linked scene)
        |-ViewportContainer
            |- Viewport
                |- Camera2D
                |- Node2D (the linked scene)
```
The linked scene looks like this:

```
Node2D
    |- CanvasLayer
         |- ColorRect
```
They do not show neither in the editor nor while running (they are black). The Camera2Ds are set as current. The ViewportContainers take half of the screen by using size flags and have the "Stretch" property enabled.

I went to the community and found the answer:https://godotengine.org/qa/59054/viewports-do-not-show-the-scene-inside-them
But I want to be able to update the viewport size automatically

### Steps to reproduce

According to this node structure, you can reproduce

### Minimal reproduction project

[splitscreen_start.zip](https://github.com/godotengine/godot/files/7027188/splitscreen_start.zip)

**Comment by Calinou** [comment] 2021-08-22 10:08
@244164401 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Do the Viewports have a **Size** property with a width and height both greater than 0? This is different from the ViewportContainer's **Rect Size**.

**Comment by 244164401** [comment] 2021-08-23 12:02
> @244164401 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Do the Viewports have a **Size** property with a width and height both greater than 0? This is different from the ViewportContainer's **Rect Size**.

Uploaded, please check

**Comment by Calinou** [comment] 2021-08-23 14:33
@244164401 I can't see any Viewport node in the minimal reproduction project. Also, no main scene is defined.

**Comment by 244164401** [comment] 2021-08-23 16:21
> @244164401在您上传的最小复制项目中，我看不到任何视口节点。此外，没有定义主要场景。

[splitscreen_start.zip](https://github.com/godotengine/godot/files/7033446/splitscreen_start.zip)

**Comment by 244164401** [comment] 2021-08-23 16:37
> @244164401 I can't see any Viewport node in the minimal reproduction project you uploaded. Also, no main scene is defined.

When I finished placing the node, it displayed like this:
![image](https://user-images.githubusercontent.com/39994989/130483880-38e53aed-5c9f-444c-ad97-c1ecf8daa472.png)
The strange thing is running can be displayed properly:
![image](https://user-images.githubusercontent.com/39994989/130484027-8f8344ec-9203-4798-a7b9-47bcf4a7ec58.png)
When you save and close the node, reopen it and display normally again:
![image](https://user-images.githubusercontent.com/39994989/130484304-a2853d61-5779-4f36-a291-9f1a8263cea7.png)

**Comment by Calinou** [comment] 2021-08-23 16:40
Duplicate of https://github.com/godotengine/godot/issues/39387.

**Closed by Calinou** 2021-08-23 16:40 UTC
Labels: documentation, topic:gui
