### ISSUE TITLE
Detect too high lightmap texel density and warn before baking lightmaps

### ISSUE THREAD

**Issue by bosman697** [godotengine/godot#59988] opened 2022-04-07 14:32 UTC
### Godot version

Godot_v3.4.4-stable_win64

### System information

Windows 10 Gles2.0

### Issue description

I create objects with collision save them as .tres , then i put thoose object on level. Them i add simple light and bakelightbox but when i press bake lightmap godot  turn off .  GI woks fine  but i want bake lightmap becouse i using Gles2
https://gyazo.com/72eccb1755e3b27d09ce4503bc6b1a22

### Steps to reproduce

just import mesh create collision and save as .tres next add this object to level  them light and bake lightmap

### Minimal reproduction project
https://we.tl/t-TSb6rFhv8W

*Bugsquad edit: GitHub mirror of the above WeTransfer: [New Game Project.zip](https://github.com/godotengine/godot/files/844416/New.Game.Project.zip)*

**Comment by bosman697** [comment] 2022-04-07 15:07
here https://we.tl/t-TSb6rFhv8W

**Comment by Calinou** [comment] 2022-04-07 15:59
Baking lightmaps is taking an extremely long time in the test project:

![image](https://user-images.githubusercontent.com/180032/162246689-5452419d-adac-4661-a211-79cd6f57769a.png)

I assume this is because the texel density is too high on the imported scenes. Try increasing **Lightmap Texel Size** in the Import dock to something like 0.5 or 1.

**Comment by akien-mga** [comment] 2024-01-19 10:10
Duplicate of #54679.

**Closed by akien-mga** 2024-01-19 10:10 UTC
Labels: enhancement, topic:rendering, topic:editor, topic:3d
