### ISSUE TITLE
Enable File Logging project setting does not work for print and printerr in gdscript

### ISSUE THREAD

**Issue by squished-01** [godotengine/godot#35678] opened 2020-01-28 22:35 UTC
Is there any rational reason why print and printerr is being omitted from log files, even with file logging and verbose stdout enabled?

**Comment by Calinou** [comment] 2020-01-28 22:39
Duplicate of #33253. Also, please fill in the issue template next time.

**Closed by Calinou** 2020-01-28 22:39 UTC
