### ISSUE TITLE
Can't export to zip or pck on Ubuntu

### ISSUE THREAD

**Issue by LuminousNutria** [godotengine/godot#25191] opened 2019-01-21 17:15 UTC
**Godot version:**

3.0.6 64-bit

**OS/device including version:**

Ubuntu 18.04 64-bit 

**Issue description:**

Tried to export the game to a zip or pck file, but it just went back to the prior screen without apparently doing anything.

**Steps to reproduce:**
Go to Project >> Export >> Export PCK/Zip and try to export.

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-01-21 19:00
Did you configure any export preset?

**Comment by starry-abyss** [comment] 2019-01-22 16:59
Likely a #24894 duplicate

**Comment by akien-mga** [comment] 2019-01-22 22:12
Indeed, closing as duplicate of #24894.

**Closed by akien-mga** 2019-01-22 22:12 UTC
