### ISSUE TITLE
Make new_script automatically selected when creating new script

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#29082] opened 2019-05-21 18:33 UTC
**Godot version:**
3.1.1

**Issue description:**
When creating a new script, it is very tedious to set the name, espacialy when it has a long file path. Making it the name autoselected would be very handy when adding many scripts.

![image](https://user-images.githubusercontent.com/28286961/58121294-5d184e00-7c07-11e9-8a85-5df3f2148a4d.png)

**Steps to reproduce:**
Create a new file in the FileSystem tab.

**Comment by akien-mga** [comment] 2019-05-22 09:14
Duplicate of #25611, already implemented in the master branch.

**Closed by akien-mga** 2019-05-22 09:14 UTC
Labels: enhancement, topic:editor, usability
