### ISSUE TITLE
Can't overwrite font while editor open

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23781] opened 2018-11-17 22:43 UTC
**Godot version:**
3.1 alpha

**OS/device including version:**
Windows 10

**Issue description:**
When you try to overwrite a .ttf file, you can't. It says file is in use and you need to close Godot to do it. It's extremely annoying when you edit the font to fix missing glyphs and you need to constantly reload the project.

Looking at issues I found #4522 and seems like it's unfixable Windows-only issue. Well, there is workaround possible: treat .ttf files as importable resources. Whenever a .ttf file is detected, add it to .import directory and use that copy. When the original file changes, unload the old file temporarily and replace it. Not sure how much possible or viable it is, but well, the problem affected me enough to create this issue.

**Comment by akien-mga** [comment] 2018-11-18 09:44
It's a duplicate of #4522, and the reasons for closing it are still valid. This is a Windows limitation and there's no way around it.

Working it around by duplicating resources that don't need it into the `.import/` would be wasteful IMO. If this is done for fonts, then it should be done for videos too, which can be quite sizable, making the project directory heavy for little gain.

Given that it's a common Windows limitation that affects all software, I don't feel we should go through hoops to provide a better UX than what Windows itself cares to provide.

**Comment by KoBeWi** [comment] 2018-11-18 11:38
> If this is done for fonts, then it should be done for videos too, which can be quite sizable, making the project directory heavy for little gain. And the same would likely happen with any kind of resources currently in use, including Godot's own

Haven't tested it with videos (although last time I used them there wasn't such problem), but it happened to me only with fonts so far. So the workaround should be only for resources that this happens to.
If anything, this behavior could be optional. I wouldn't mind my project getting a lot bigger if I didn't need to reload it every few minutes when working on something locked.

**Comment by akien-mga** [comment] 2020-12-05 10:23
Duplicate of #23773.

**Closed by akien-mga** 2020-12-05 10:23 UTC
Labels: discussion, enhancement, platform:windows, topic:editor
