### ISSUE TITLE
File case warnings only in 32 version of editor.

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#30301] opened 2019-07-03 21:40 UTC
**Godot version:**

Godot master d8ce7aeddcaeea503d8d247c55a2cd83ccbbc2c4 (02/07/2019)
32 bit version of editor, compiled with VS2019
Python 2.7.13
Scons 2.5.1

**OS/device including version:**

Tested in win 7 32 y 64 bit.

**Issue description:**

Console throws a lot of warnings like this:
![32Bit Case mismatch](https://user-images.githubusercontent.com/11712737/60625244-7a842e80-9de7-11e9-9a4e-c98a142454db.png)

64 bit version of editor in same system not.
I don´t know if is related with the fact that 32 bit versión doesn´t compile with vs2015 and vs2017 any more: https://github.com/godotengine/godot/issues/28949

I make test and the issue is present on start and on focus gain (In focus gain only with plugins)... not when working inside godot.
It´s not present in new projects... 
I can´t easy isolate because windows says there are 3002 files in project without git stuff... but happend in some templates of the library. 

Main issue is that this warning **is only in 32 bit version of editor**

**Steps to reproduce:**
Open godot editor 32 bit in windows and beggin a project with "Godot Open Dialogue" template. This throws the error.

**Comment by KoBeWi** [comment] 2020-11-27 21:08
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by KoBeWi** [comment] 2022-05-04 11:10
Closing due to lack of update. Comment if  you can still reproduce in Godot 4.0.

**Closed by KoBeWi** 2022-05-04 11:10 UTC
Labels: bug, platform:windows, topic:editor, cherrypick:3.x
