### ISSUE TITLE
Allow resizing of nodes in Visual Script

### ISSUE THREAD

**Issue by TheRealCatherine** [godotengine/godot#28314] opened 2019-04-22 23:01 UTC
**Godot version:**
3.1-stable-win64

**Issue description:**
Its currently not possible to resize nodes in the visual script editor. They should have a resize handle in the lower right hand corner and elide values that are too big to show. Additionally, there should be a standard, reasonable maximum auto-resize-to size (for when values are entered into node slots)

Right now if you put a 20,000 character string into a string input on a node you will get an unusable node.

For example here: showing this full string in the node editor is not useful and wastes a lot of space. Now imagine a multi-paragraph text.

![image](https://user-images.githubusercontent.com/31754592/56538370-73f45380-6528-11e9-968e-e68aa5ea3a36.png)

**Steps to reproduce:**
Create a node with a String input. Paste or type a paragraph into it.

**Comment by Jummit** [comment] 2019-04-27 11:08
I would solve this a different way. You can set hints for variables that allow for a large input field:
![image](https://user-images.githubusercontent.com/28286961/56848836-715d7980-68ed-11e9-9b9a-bf340ddbd048.png)
![image](https://user-images.githubusercontent.com/28286961/56848837-73273d00-68ed-11e9-9a0f-6332e51eb274.png)
How about making this hint available for function arguments? That would solve the issue.

**Comment by Jummit** [comment] 2019-04-27 11:09
Also, duplicate of #6074

**Comment by groud** [comment] 2019-04-27 14:03
Closing as duplicate of#6074

**Closed by groud** 2019-04-27 14:03 UTC
Labels: enhancement, topic:editor, topic:visualscript
