### ISSUE TITLE
Editor progress dialogs not using editor theme

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#71414] opened 2023-01-14 17:09 UTC
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

N/A

### Issue description

The editor progress dialogs in Beta 12 seem to no longer use the editor theme. May be related to #71209

![Screenshot from 2023-01-15 00-06-38](https://user-images.githubusercontent.com/25323231/212485682-e6cc8249-1463-4981-b563-745f319b6a7c.png)
![Screenshot from 2023-01-15 00-06-47](https://user-images.githubusercontent.com/25323231/212485685-7d80dbd1-6e3a-4727-9e4c-32c364e61210.png)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment] 2023-01-14 17:16
Duplicate of https://github.com/godotengine/godot/issues/71351, already fixed.

**Closed** 2023-01-14 17:18 UTC
