### ISSUE TITLE
Inspector feedback

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#19084] opened 2018-05-21 16:20 UTC
So, Godot got a new inspector. Exciting! I took some time to have a look for issues and possible improvements.

1. Formatting and tags should be filtered from tooltips
![tooltip](https://user-images.githubusercontent.com/1654763/40315833-cdab2468-5d1c-11e8-8766-b09eba2f16ec.PNG)
1. When editing subresources, there is no vertical scrollbar
![verticalscroll](https://user-images.githubusercontent.com/1654763/40316047-5aa7f74c-5d1d-11e8-9b5d-981ba882211d.PNG)
1. Is there a shortcut for editing the subresource besides Right click -> Edit? Like CTRL+Click on it?
1. On resources like the Texture above, there should be a way to "show resource in folder/on disk" to see where it's saved
1. There should be a vertical gutter to choose how much space values and keys have
![gutter](https://user-images.githubusercontent.com/1654763/40316611-23f9f496-5d1f-11e8-8e95-4d7fb89a25d4.gif)
1. I really like how they associate X/Y/Z with the gizmo colors for the axis there:
![gizmocolor](https://user-images.githubusercontent.com/1654763/40316770-a81b7b32-5d1f-11e8-9221-f6f81946274b.PNG)
1. The inspector could be more compact in general. Compare:
![compact1](https://user-images.githubusercontent.com/1654763/40316843-e3cb5cf6-5d1f-11e8-9545-3572337794e2.PNG)
vs 
![compact2](https://user-images.githubusercontent.com/1654763/40316846-e5b2452a-5d1f-11e8-9217-cb7c6e41581b.PNG)
In some instances its better already, like here:
![compact3](https://user-images.githubusercontent.com/1654763/40317916-34cba19e-5d23-11e8-870a-8c688b153133.PNG)
1. Also see those yellow arrow after controls above? They allow you to easily undo specific changes and reset the field to whatever it was prior to your change.
1. Dropdowns like the layer mask selections should stay open to allow multiple changes without having to reopen the dropdown each time
1. Seeing as keys can actually have focus, allow me to select "Position" (like below) and then reset both values at once by pressing "0", or allow me to enter any number to set both at the same time:
![position](https://user-images.githubusercontent.com/1654763/40318051-a3111616-5d23-11e8-999f-ee7a49b11eb4.PNG)

**Comment by Zireael07** [comment] 2018-05-21 16:37
That's some amazing feedback!

**Comment by groud** [comment] 2018-05-21 16:46
@djrm number 5 would solve the question we had. It looks like a good idea

**Comment by reduz** [comment] 2018-05-21 17:04
Answers to feedback
1. Agreed, I think we need custom tooltip support for this, should be relatively easy to add
2. That is intended, it would be unusable and very confusing with one
3. No, so feedback welcome. I am still not sure how often this use case is needed to justify a simpler way
4. Is there nothing like this on the sub-menu? maybe opening/collapsing it should select it on the filesystem
5. Yes, agreed on this, I am waiting to make sure the current layout is final for this, should hopefully be easy to add.
6. The look is being worked on by @djrm , but, if worth it, this may be doable. I am not sure yet.
7. I dont get the point
8. you have undo/redo for this. Godot uses revert button for something else. May eventually add a RMB to revert to default value, but I dont think this is a common use case to justify it.
9. makes sense
10. I dont see this is a common use case to justify it

**Comment by reduz** [comment] 2018-05-21 17:05
@mhilbrunner in general, the idea is to NOT do something the way Unreal does. The goal of the Godot inspector is to be very compact horizontally, so some things are different because of this.

**Comment by reduz** [comment] 2018-05-21 17:13
@groud, @djrm once the layout is more or less final, I want to save both the horizontal ratio AND the scroll somewhere for each object, so its cached. Not sure if the HRatio should be saved or simply be an editor setting.

**Comment by vnen** [comment] 2018-05-21 17:20
Just to note, the tooltip issue was already there in the old inspector: #15431.

**Comment by neikeq** [comment] 2018-05-21 18:15
Here is another source for inspiration:

![Akira Inspector](https://user-images.githubusercontent.com/7718100/40322523-f836b542-5d32-11e8-92ee-bc177a4080cd.png)
_[Source](https://github.com/Alecaddd/Akira)_

I think it's easier to the eyes to have the xy fields placed horizontally. The label merged with the text field also make it clearer. In the case of Rect, I think it should be two rows, the first for xy and the second for wh (width and height).

**Comment by djrm** [comment] 2018-05-21 18:54
i would prefer to have most of properties in two rows, this is more compact and offers a better layout, since we now can probably see every property name (without it being chopped), and we have a dedicated space for extra options like keying and revert option, i think most of the time having two rows will even reduce the vertical size of the property, but of course you might have a reduced working space for every input (this can be solved by stacking the inputs when the space is really small), that applies to properties with 4 inputs per row (3 inputs will have acceptable size)

![screenshot from 2018-05-21 13-40-27](https://user-images.githubusercontent.com/1103897/40323966-a5e18424-5cfc-11e8-9de4-0fea73ed96d8.png)

**Comment by groud** [comment] 2018-05-21 21:12
I would prefer a two-row inputs too. I think the XYZ on the same line is far easier to read.

**Comment by toger5** [comment] 2018-05-21 23:05
I think the colors for xyz is nice!
And having them aligned horizontal is better imo

**Comment by djrm** [comment] 2018-05-21 23:33
@toger5 this might be off-topic here, but i am also planning to overhaul the godot theme, to address the issue of all the widgets looking the same.

**Comment by reduz** [comment] 2018-05-22 00:33
@djrm that two row concept looks pretty nice imo, would it still make sense for single entries though? In that case I feel it may be wasted vertical space

**Comment by djrm** [comment] 2018-05-22 00:56
@reduz, no the point is to make it single line when using single values.

**Comment by Bauxitedev** [comment] 2018-05-22 10:06
I'd like to add, in Unity, you can right click the transform and then select "Reset" to reset it to the identity transform. That would be really useful to have in Godot as well. (Also there's a separate "Reset Rotation" button too in newer version)
![reset](https://user-images.githubusercontent.com/31383123/40356141-837f4328-5db8-11e8-92d0-21a7c4123cb5.png)

**Comment by mhilbrunner** [comment] 2018-05-22 13:33
@djrm Please keep in mind that any change on the theme can require large amounts of work from the docs team, as we need to re-create every screenshot to update it to the current look. We only now reached 90% of screenshots updated to 3.0, there are still a few here and there from 2x left.

This will be fun for the new inspector *as is*. I'm not saying don't change anything; change it if it is worth it, but keep this in mind.

**Comment by groud** [comment] 2018-05-22 13:39
> @djrm Please keep in mind that any change on the theme can require large amounts of work from the docs team, as we need to re-create every screenshot to update it to the current look. 

Hmm... If we start to bother about the documentation first then nothing moves. The engine comes before the documentation. I would just let @djrm make all the enhancements needed (there are a lot), which is far more important (to me) than a perfectly up-to-date set of screenshots.

**Comment by mhilbrunner** [comment] 2018-05-22 13:55
@groud:
>Hmm... If we start to bother about the documentation first then nothing moves

I'm not advocating for that. If a change is a clear improvement, make it.
But we should try to minimize changing stuff just for the sake of changing it.

Changing inspector stuff is fine, as thats now changed radically anyway. For other things, we should weight the improvements against exhausting both our resources (the docs team) and user fatigue (as we just changed nearly all UI with 3.0). *3.1* is a *minor* release after all.

I'm just asking to keep this in mind. If a change still is an improvement, change it. :)
The docs team will catch up to it eventually.

**Comment by groud** [comment] 2018-05-22 14:04
> But we should try to minimize changing stuff just for the sake of changing it.

This never happens. We never do changes "just for the sake of it", that's why most PRs are reviewed.
I'm sorry, but I don't understand why trying to discourage people for doing changes on the engine, just for the documentation to be up-to-date. Once we reach a "perfect" design for the editor, this should not be a problem anymore.

**Comment by reduz** [comment] 2018-05-22 14:37
@Bauxitedev Yeah, I was thinking a RMB over the property name so you can copy/paste/reset/go to doc or something like this would be really nice

**Comment by toger5** [comment] 2018-05-22 15:22
@mhilbrunner maybe we can do a plugin for the docs which allows to generate all screnshots at once by moving the editor in the correct position and copying part of the viewport buffer ?

**Comment by mhilbrunner** [comment] 2018-05-22 15:36
@toger5 I think thats a lot of work and overkill. And @groud is right, maybe that was overly cautious. Godot seems fairly good with only merging stuff that improves the engine.

**Comment by groud** [comment] 2018-05-22 15:42
> @mhilbrunner maybe we can do a plugin for the docs which allows to generate all screnshots at once by moving the editor in the correct position and copying part of the viewport buffer ?

That's probably overkill, but we might make a simple script to update all screenshots maybe ? Something that lists all existing screenshots, then allows you to select and area on the screen then create a file for this screenshot (with the same name). It should not be hard to do I believe.

**Comment by toger5** [comment] 2018-05-23 00:58
@mhilbrunner @groud  I agree that it is overkill and it is also really hard to actually make it really useful.

I still wanted to do editor plugins so I tried to test how far you can go with them. you basically can do anythin. like literally anything it's amazing!!!

this is the current approach for the automate_screenshots plugin
https://twitter.com/Toger50/status/999090363364184064

**Comment by Zylann** [comment] 2018-05-24 00:21
Late to the party, but point 7) might be incompatible with point 5).

**Comment by jonbonazza** [comment] 2018-05-27 20:05
Just some general feedback. I've notice that the project leads often reply to various things with, "x would be too confusing". It's fine to be opinionated, but when building a product that other people use, your personal gut feeling isn't always correct. It's ofyen times better to not be so quick to make assumptions about what people want, but instead seek validation.

It's your project to run how you want, of course, but as a friendly suggestion, I'd consider listening more to your user's requests before being so quick to say No. After all, they are the ones actually using the product and feeling the pain points first hand.

As a professional software engineer myself (and also an opinionated one at that haha), I understand you have a vision that you want to adhere to, but in the end, if your users are saying something will make their lives easier, it's probably for good reason.

**Comment by smt923** [comment] 2018-06-27 15:12
I realise this issue is getting old but I still think there's discussion to be had here, and I think this is the best place for it

For point 7, while it does seem some parts of the inspector are getting better for this, it still seems like there is a lot of room for improvement here, stacking everything vertically and not grouping values is a huge waste of space, just in the OP's example, the image of UE4 takes less editor space but is showing 12 values, the one of Godot is using more space, has wasted space over on the left and is only showing 5 values - this is directly less space efficient and means that anyone using Godot has to spend more time scrolling through values to find what they want

I appreciate attempts to keep Godot's editor friendly for a wide range of screen sizes, but to me it seems like there could be some sort of happy balance where there is either a "small display" setting or some sort of dynamic grouping to values so that if you have a large display, you can let Godot take a bit more width to render things with a lot more efficiency 

(excuse my poor editing skills but I think it gets my idea across)
![concept](https://i.imgur.com/aRJ8qVm.png)

Specifically, the new transform is **great**, but right under it there is room to collapse those groups of variables into groups of 3 too, freeing up a huge amount of space, reducing the time spent scrolling and increasing the number of values shown on the screen at once (and this is in a very small height example, in an editor inspector with many more things grouped and not just edited together I imagine the difference increases slightly)

To me, this is a massive benefit, and it would still work well on smaller displays given the right scaling - Unity can squeeze it's inspector down incredibly small and still show off groups well:

![unity](https://i.imgur.com/5BerJwR.png)

I can get by with the current inspector, but I think usability changes like these are what makes using the engine feel even better, and the new inspector is a huge step towards that, but I still feel like there is currently a lot of wasted space even in the new inspector, even just some of the margins and padding

**Comment by Jummit** [comment] 2018-12-13 10:12
So this is currently in no milestone, shouldn't this be in 3.2?

**Comment by mhilbrunner** [comment] 2018-12-14 11:33
Maybe; but I probably should have another look, see which of these were fixed and open seperate issues for the remaining ones, then close this one.

Easier to have an issue per, well, issue and this was just a fast feedback after the new inspector arrived. :)

**Comment by toger5** [comment] 2018-12-15 02:19
maybe we could close this one now ? since some things are already addressed? And create new issues for the annoyances that still exist.

**Comment by MelvinWM** [comment] 2019-03-15 17:02
@mhilbrunner @toger5 Good idea, I have tried to create a list below, please do mention any errors in it. Once it is complete and there are issues for all parts that are still relevant, we can close this issue.

- [x] 1: Formatting and tags should be filtered from tooltips. **Fixed as per latest version of master**
- [x] ~~2: When editing subresources, there is no vertical scrollbar~~ **Working as intended**
- [ ] 3: Shortcut or similar for editing the subresource besides Right click -> Edit, like CTRL+Click on it. **Since you can edit sub-resources inside the same inspector just by left-clicking on it, is this still relevant/useful?**
- [x] 4: On resources like the Texture above, there should be a way to "show resource in folder/on disk" to see where it's saved. **Fixed as per latest version of master**
- [ ] 5: https://github.com/godotengine/godot/issues/7133
- [x] 6: I really like how they associate X/Y/Z with the gizmo colors for the axis there. **Fixed as per latest version of master**
- [ ] 7: The inspector could be more compact in general.
- [ ] 8: Also see those yellow arrow after controls above? They allow you to easily undo specific changes and reset the field to whatever it was prior to your change.
- [ ] 9: Dropdowns like the layer mask selections should stay open to allow multiple changes without having to reopen the dropdown each time. **As far as I understand, this issue has been fixed as per latest version of master. Can anyone confirm?**
- [x] ~~10: Seeing as keys can actually have focus, allow me to select "Position" (like below) and then reset both values at once by pressing "0", or allow me to enter any number to set both at the same time.~~ **Too uncommon to justify it**

**Comment by akien-mga** [comment] 2019-11-14 12:07
Thanks for the thorough summary @MelvinWM.

>  9: Dropdowns like the layer mask selections should stay open to allow multiple changes without having to reopen the dropdown each time. **As far as I understand, this issue has been fixed as per latest version of master. Can anyone confirm?**

Layer bitmask selection is no longer done within a dropdown but is directly embedded in the Inspector, so this is indeed fixed (unless there are other dropdowns with a similar use case, but I can't think of any right away).

**Comment by akien-mga** [comment] 2019-11-14 12:10
As most points are now addressed, I'll close this. The remaining points should likely go in new issues on https://github.com/godotengine/godot-proposals for further discussion.

**Closed by akien-mga** 2019-11-14 12:10 UTC
Labels: topic:editor, usability
