### ISSUE TITLE
reading from depth texture  disables depth test.

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot#69293] opened 2022-11-28 11:56 UTC
### Godot version

4 beta 6

### System information

Kubuntu

### Issue description

When reading from the depth texture in the shader, everything becomes messed up if it overlaps itself.
I think when this happens no specific draw order is imposed.

### Steps to reproduce

1- Make a model that overlaps itself
2- Make a shader material that reads from DEPTH_TEXTURE.

### Minimal reproduction project

[gd4test.zip](https://github.com/godotengine/godot/files/10103374/gd4test.zip)

**Comment by Calinou** [comment] 2022-11-28 14:04
Duplicate of https://github.com/godotengine/godot/issues/63675 (same cause – see below).

Reading from the depth texture forces the material to be transparent, which causes [transparency sorting issues](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting). These are an inherent limitation of the rendering engine, and cannot always be resolved.

**Closed by Calinou** 2022-11-28 14:04 UTC
