### ISSUE TITLE
Adding 3D Model via drag and drop into the view port does not work

### ISSUE THREAD

**Issue by YahArt** [godotengine/godot#58310] opened 2022-02-19 08:12 UTC
### Godot version

4.0 dev alpha 2 build

### System information

Manjaro KDE Nvidia RTX 3070

### Issue description

Godot Build: Godot 4 Alpha Version 2

When trying to drag an import 3D model (e.g glb format) into the view port the model does not show up. However it does show up when drawing the model directly to the scene tree.

### Steps to reproduce

- Create a new Godot 4 Project
- Import any 3d model (glb, fgx, obj etc.)
- Drag and drop the 3d model directly into the viewport -> model does not show u
![model_drag_and_drop_problem](https://user-images.githubusercontent.com/2711677/154792766-82182f83-520c-4f86-b1b1-6628fef1c0b4.png)
p

**Comment by lyuma** [comment] 2022-02-19 08:38
Duplicate of #55985

It was fixed by this PR: #58007 which unfortunately didn't make the cut for alpha2. The fix will be part of alpha3.

For now, as a workaround, drag the model directly from FileSystem into the Scene hierarchy without going over the content area, since that is what triggered the bug.

**Closed by lyuma** 2022-02-19 08:38 UTC
