### ISSUE TITLE
Black screen bug (Windows 10, Godot v3.2)

### ISSUE THREAD

**Issue by Bimi124** [godotengine/godot#40338] opened 2020-07-13 06:54 UTC
# Godot version:
3.2

# OS/device including version:
Windown 10 (64 Bits)

# Issue description:
I've just tried to test a games start screen using the start button.
The screen got black, my mouse pounter disappeared and I wasn't able to hit keys like `Ctrl + Tab`, `Windows-Logo + D` etc. but the power lamp was on.
I've colosed my laptop to turn the operating system into the sleeping mode but as I woke it up the Screen was still black.
I ned to hold the start button to power the laptop down and after I had rebooted it everything went right...

# No idea how to reporducre it
If anyone here knows it, please write a comment.

**Comment by Calinou** [comment] 2020-07-13 08:37
Duplicate of #40337.

**Closed by Calinou** 2020-07-13 08:37 UTC
