### ISSUE TITLE
Auto Switch To Rider/vscode When Selecting a scene that has C# script , without clicking on the script icon 

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#38583] opened 2020-05-09 01:31 UTC
**Godot version:**

3.2.2beta2mono

**OS/device including version:**

Windows 10

**Issue description:**

I don't know if it is a bug or a feature but it is so irritating when switching over scenes and trying to modify something in the scene instead of the script.

**Steps to reproduce:**

Set Rider or VsCode as default MONO IDE from Editor settings .

!["defaul"](https://i.imgur.com/UPGyx9v.png)

Click on a scene tab that has a C# script , it will jump to the IDE without pressing on the script icon automatically , and opens to script of the scene pressed.
Every time i press a scene tab that has a C# script i have to return back to Godot so i can edit something in the scene  itself .

IMO : the IDE should not be opened automatically unless a click on the script icon .

**Comment by van800** [comment] 2020-05-09 17:09
There is a well hidden setting to disable that. "Open dominant script .."

**Comment by Calinou** [comment] 2020-05-09 17:13
Duplicate of #13429.

**Closed by Calinou** 2020-05-09 17:13 UTC
