### ISSUE TITLE
CanvasLayer sometimes renders child TextureRects in the wrong order???

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#48286] opened 2021-04-29 04:19 UTC
**Godot version:**

3.3

**OS/device including version:**

Windows 10 Intel UHD Graphics 620 GLES3

**Issue description:**

This happened, somehow?
![](https://cdn.discordapp.com/attachments/713075589300486234/837177099252531210/unknown.png)
I expected the highlighted icon.png to be drawn on top. It's not??!

**Steps to reproduce:**
I have no clue because I was unable to reproduce this. But it definitely happened!!!!

**Minimal reproduction project:**

**Comment by clayjohn** [comment] 2021-04-29 04:33
Please upload an MRP so others can attempt to reproduce this issue. 

If neither you nor others can reproduce the issue, then it unfortunately cannot be fixed.

**Comment by lawnjelly** [comment] 2021-04-29 06:48
If you can't reproduce it, it's possible it was caused by the particular change you made in the editor causing a stale version of something. To reproduce it you may have to create a project reproducing the change you made in the editor to create it, and then it may only occur for one frame.

**Comment by Zireael07** [comment] 2021-04-29 07:02
Related to https://github.com/godotengine/godot/issues/46788?

**Comment by lawnjelly** [comment] 2021-04-29 07:07
> Related to #46788?

Yes looks very likely, and that has a reprod project. :+1:

**Comment by akien-mga** [comment] 2021-04-29 11:43
Closing as duplicate of #46788.

**Closed by akien-mga** 2021-04-29 11:43 UTC
Labels: bug, needs testing, topic:rendering
