### ISSUE TITLE
Array type is not inferred after filter

### ISSUE THREAD

**Issue by michaeltintiuc** [godotengine/godot#72800] opened 2023-02-06 17:13 UTC
### Godot version

v4.0.beta17.official [c40020513]

### System information

Linux

### Issue description

The following error is thrown when trying to assign to a typed array the result of a filter function:
`Trying to assign an array of type "Array[Node]" to a variable of type "Array[Foo]".`

### Steps to reproduce

- Create a parent node of any type
- Add children of various types
- Filter children by specific type and assign them to the parent's typed prop

### Minimal reproduction project

```gdscript
extends Node3D

var foos: Array[Foo]

func _ready():
        #  throws error
	foos = get_children().filter(func (c): return c is Foo)

        # works fine
	for c in get_children():
		if c is Foo: foos.append(c)
```

**Comment by KoBeWi** [comment] 2023-02-06 23:03
Duplicate of #59721

**Closed by KoBeWi** 2023-02-06 23:03 UTC
Labels: topic:gdscript
