### ISSUE TITLE
Opening a Color picker in the inspector places it outside the display border

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#91722] opened 2024-05-08 16:45 UTC
### Tested versions

4.3 dev, 2042420bd7f43bb834316d7ca4631ab2fcfcc820

### System information

Windows 11

### Issue description

Opening a color picker dialog for the full-screened inspector (in the standard editor layout) place it outside the window, which makes it unusable:

![изображение](https://github.com/godotengine/godot/assets/3036176/e7a0eadd-e2a6-4063-a011-aac13468f9ad)

Probably a recent regression (does not present in 4.3 dev 6)

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

No need

**Comment by Chaosus** [comment] 2024-05-09 07:38
Bisected to 5c28814b3944f899c6e8971f28c7857e4c2a9e13, cc @KoBeWi

**Comment by jsjtxietian** [comment] 2024-05-10 05:01
Maybe it also affects the ColorPicker's preset buton, it's size is calculated as `(int(get_minimum_size().width) - (preset_container->get_h_separation() * (PRESET_COLUMN_COUNT - 1))) / PRESET_COLUMN_COUNT`, and I got -5 at the current master.

**Comment by KoBeWi** [comment] 2024-05-16 08:45
A variation of this issue still exists.
![image](https://github.com/godotengine/godot/assets/2223172/aa7a839b-ac3f-4491-bb76-93e3c42676ce)
Low ColorPickers appear below task bar. I don't know what is the cause this time.

**Comment by akien-mga** [comment] 2024-06-18 14:18
Was this fixed by #92664?

**Comment by KoBeWi** [comment] 2024-06-18 15:15
No.

**Comment by anniryynanen** [comment] 2024-06-20 08:16
I'm going to put some time into trying to fix this.

**Closed** 2024-06-20 14:25 UTC
Labels: bug, topic:editor, regression, topic:gui
