### ISSUE TITLE
"Save on focus loss" causes task icon to blink after Alt + Tab (DisplayServer regression)

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot#57521] opened 2022-02-01 17:20 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10 Version 20H2 Build 19042.1415; Vulkan; RTX 3060 6GB; Ryzen 5900HS

### Issue description

When I activate "Save on focus loss" in the editor's settings,
then ALTTAB to another window,
my normally hidden taskbar shows up,
with Godot's icon *demanding* attention by blinking in my face.

I haven't found a way to make it stop,
except for turning "Save on focus loss" off again.

I've also tried turning it off and on again *twice*, just to be sure.

### Steps to reproduce

1. Turn on "Save on focus loss".
2. ALTTAB.

Please note that the blinking stops the second I ALTTAB back to Godot.
Then, when I ALTTAB away again, it starts again.

I'm not ready for such a relationship. D:

**Comment by Calinou** [comment] 2022-02-01 17:44
Can you reproduce this if you enable **Single Window Mode** in the Editor Settings then restart the editor?

**Comment by SolsticeProjekt** [comment] 2022-02-01 18:08
Yes, it's still happening with **Single Window Mode** enabled.

**Comment by KoBeWi** [comment] 2022-06-04 16:27
This actually looks like duplicate of #53256

**Closed by KoBeWi** 2022-06-04 16:27 UTC
Labels: bug, platform:windows, topic:editor, regression
