### ISSUE TITLE
Key inputs are randomly lost and non-responsive in web export when hosted in an iframe

### ISSUE THREAD

**Issue by jordo** [godotengine/godot#55248] opened 2021-11-23 05:49 UTC
### Godot version

3.4

### System information

Firefox + Chrome, all OSs

### Issue description

We host our web builds on various web portal sites.  We experience (seemingly random) times where keyboard inputs from the `<canvas>` are not passed through to godot engine.  All keyboard input is just lost, even though the game's canvas is still in focus.  Mouse cursor and click events are fine, it is just related to keyboard input.

### Steps to reproduce

This is incredibly hard to reproduce, as it is quite random, and requires a lot of setup...  But export a 3.4 project to web, and host exported game within an iframe of another site.

This issue has only come up after upgraded to v 3.4, it seems this issue could be somewhat related to the refactor of js input here:  https://github.com/godotengine/godot/commit/b7ac3c1aeb52f9136e2bf4237740d7d6eeb69be7

**Comment by jordo** [comment] 2021-11-23 06:10
When our site gets into this state, I can confirm this line of code does NOT run (breakpoint on line 12296 does not hit):

![image](https://user-images.githubusercontent.com/323868/142978078-96e2fd7a-a3bc-498a-9fcd-d43af4708326.png)

When this breakpoint does not hit for a key press, regular mouse and cursor events run fine.

**Comment by jordo** [comment] 2021-11-23 06:25
OK, so I can confirm how to reliably reproduce the issue (at least on chrome).  When the game is hosted in an iframe, if you click outside the canvas/iframe, then click back in, keyboard inputs will cease.

**Comment by jordo** [comment] 2021-11-23 06:32
I _think_ this is probably related to this removal:

https://github.com/godotengine/godot/commit/b7ac3c1aeb52f9136e2bf4237740d7d6eeb69be7#diff-44731e0168fe89a03ed7f77c76c86beaf84fdcb1097c763e7f4eee3a8c540cf8L371-L373

If I'm reading that correctly,  previously we were explicitly focusing the canvas (for iframe) on mouse button event?

**Comment by Chaosus** [comment] 2021-11-23 07:48
cc @Faless

**Comment by jordo** [comment] 2021-11-23 08:42
I can confirm that the removal of this https://github.com/godotengine/godot/commit/b7ac3c1aeb52f9136e2bf4237740d7d6eeb69be7#diff-44731e0168fe89a03ed7f77c76c86beaf84fdcb1097c763e7f4eee3a8c540cf8L371-L373 was the regression.  Putting this back in fixed. It re-focusses the canvas on mouse event in an iframe

**Comment by Faless** [comment] 2021-11-23 09:09
Duplicate of #55017, already fixed via #55111

**Comment by jordo** [comment] 2021-11-25 05:11
This fix doesn't appear to work in firefox 95, but I can confirm it does work in chrome 96.

Can confirm that putting [this](https://github.com/godotengine/godot/commit/b7ac3c1aeb52f9136e2bf4237740d7d6eeb69be7#diff-44731e0168fe89a03ed7f77c76c86beaf84fdcb1097c763e7f4eee3a8c540cf8L371-L373) back into the cpp side fixes the issue on firefox as well as chrome.

**Comment by Faless** [comment] 2021-11-26 08:50
> [This](https://github.com/godotengine/godot/pull/55111) fix doesn't appear to work in firefox 95, but I can confirm it does work in chrome 96.

Thanks a lot for investigating this, should be fixed via #55342 .

**Closed** 2021-11-26 09:42 UTC
Labels: bug, platform:html5, topic:porting, topic:input, regression
