### ISSUE TITLE
"File" class not available in EditorPlugin script?

### ISSUE THREAD

**Issue by everythingandnothingdev** [godotengine/godot#50922] opened 2021-07-27 03:31 UTC
### Godot version

4.0dev (1f69582)

### System information

Windows 10, Vulkan, RTX 2080

### Issue description

This seems like a basic thing, but can't seem to access File class from an editor plugin.

![image](https://user-images.githubusercontent.com/87843097/127090888-ed30539e-8cbf-4537-ac56-35a8a37db65f.png)

### Steps to reproduce

Create a plugin with this script

```gdscript
@tool
extends EditorPlugin

func _enter_tree():
    var file = File.new()
```

**Comment by akien-mga** [comment] 2021-07-27 06:25
Duplicate of #50831, this was fixed already.

**Closed by akien-mga** 2021-07-27 06:25 UTC
