### ISSUE TITLE
Supporting Vulkan ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [godotengine/godot#3775] opened 2016-02-19 12:07 UTC
Vulkan is out ! :) 
https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification
https://community.arm.com/groups/arm-mali-graphics/blog/2016/02/16/porting-a-graphics-engine-to-the-vulkan-api
http://gpuopen.com/vulkan-renderpasses/

**Comment by kubecz3k** [comment] 2016-02-19 12:18
Hello @LifeIsStrange We know vulcan is out :)  But there is already issue about this :) Closing because it's duplicate of: https://github.com/godotengine/godot/issues/3729

**Closed by kubecz3k** 2016-02-19 12:18 UTC
Labels: archived
