### ISSUE TITLE
`LineEdit` Save Branch as Scene, Adds a Timer node to the Scene 

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#61029] opened 2022-05-14 13:16 UTC
### Godot version

4.0.alpha8

### System information

Windows 11

### Issue description

![Godot_v4 0-alpha8_win64_192j1yCzBP](https://user-images.githubusercontent.com/27586088/168427409-b70325b2-2f5c-4464-b63a-22009619bbec.png)

![Godot_v4 0-alpha8_win64_v7apd0WsYx](https://user-images.githubusercontent.com/27586088/168427244-a69d2466-8c85-466f-8f10-7acc32495400.png)

Saving a `LineEdit` node as a scene adds random Timer child nodes to the LineEdit .

![Godot_v4 0-alpha8_win64_FQzGuoOjZV](https://user-images.githubusercontent.com/27586088/168427291-7da88886-4aa4-4021-8adf-7414d740d344.png)

### Steps to reproduce

1. Create a scene with a `LineEdit` node.
2. Save the LineEdit node as a scene.
3.  The LineEdit will have a timer node attached to it in the new created scene.

**Comment by Calinou** [comment] 2022-05-14 18:19
This is because Save Branch as Scene is saving internal nodes. cc @KoBeWi 

PS: I wonder if LineEdit actually needs a Timer, or whether it could perform its cursor blinking using a low-level approach. This could improve performance in complex GUIs with dozens of LineEdits or more.

**Comment by KoBeWi** [comment] 2022-05-14 18:25
This is duplicate of #54960

**Closed by KoBeWi** 2022-05-14 18:25 UTC
Labels: bug, topic:editor, regression
