### ISSUE TITLE
Create a way to browse packed resources inside .pck file 

### ISSUE THREAD

**Issue by hedin-hiervard** [godotengine/godot#29655] opened 2019-06-10 12:42 UTC
**Godot version:**
3.1

**Issue description:**

I have a directory called Levels with a bunch of json files I use as level templates. While developing I used `Directory` to iterate through them and load them. But when I export the project there is no (known to me) way to do this, so I end up with an empty list.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by dalexeev** [comment] 2019-06-11 16:40
https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_projects.html#export-mode

**Comment by hedin-hiervard** [comment] 2019-06-11 17:15
> https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_projects.html#export-mode

I read this and using this. Can you please elaborate a little bit on how can I iterate through resources in a directory inside a .pck file?

**Comment by Calinou** [comment] 2019-06-11 17:22
A workaround for now is to generate a text file containing a list of paths in a directory, and making sure it's exported using a non-resource export filter (like `*.txt`). This file can be generated using a shell or Batch script, or in GDScript using an editor plugin.

**Comment by dalexeev** [comment] 2019-06-11 18:36
This does not negate the bug (non-obvious `Directory` behavior), but you can also try to make a non-resource file a resource:
https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/import_plugins.html

**Comment by hedin-hiervard** [comment] 2019-06-12 07:07
Yes, I understand the possible workaround and is well aware of export options. I reported this because I believe `Directory` should behave more consistently.

**Comment by scottkunkel** [comment] 2019-06-12 14:46
I cannot replicate:
```
extends Resource
class_name FileExt

static func list_files_in_directory(path, filter):
	var files = []
	var dir = Directory.new()
	dir.open(path)
	dir.list_dir_begin()
	var lFile = File.new()

	while true:
		var file = dir.get_next()
		if file == "":
			break
		elif filter:
			if file.ends_with(filter):
				files.append(file)
		else:
			files.append(file)

	return files
```

calling with ("res://jsonfiles/", ".json") will list all json files correctly
you do have to export all resources:
![image](https://user-images.githubusercontent.com/22383351/59361046-41343380-8cff-11e9-8cde-3b2504ecf3ba.png)

**Comment by Calinou** [comment] 2020-07-03 14:37
Duplicate of #25672.

**Closed by Calinou** 2020-07-03 14:37 UTC
Labels: bug, topic:core
