### ISSUE TITLE
Adding a GPU Particles 2D crashes Godot

### ISSUE THREAD

**Issue by TheNormandyProject** [godotengine/godot#73721] opened 2023-02-22 00:49 UTC
### Godot version

4.0-RC1-mono

### System information

MacOS Monterey 12.4, M1 Max (10c CPU, 32c GPU), Vulkan

### Issue description

`renderer: gl_compatibility`
`renderer.mobile: mobile`
`renderer.web: gl_compatibility`

Adding a GPU Particles 2D crashes Godot

### Steps to reproduce

Create an empty project with gl_compatibility 
Add a GPU Particles 2D node
Crashes

MacOs Crash Log:
[log.txt](https://github.com/godotengine/godot/files/10798986/log.txt.txt)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-02-22 01:38
Duplicate of https://github.com/godotengine/godot/issues/72469

**Closed by clayjohn** 2023-02-22 01:38 UTC
