### ISSUE TITLE
Materials are rendering black on old intel g41 chipset (default environment not working)

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#25512] opened 2019-01-31 12:42 UTC
**Godot version:3.1**

**OS/device including version:Windows 7 64 bit**
 Intel g41 express chipset
Open Gl 2.1

**Issue description:** I used GLES2 renderer. Adding  a mesh instance gives a completely black cube. Adding materials has no effect. The sky is rendering as it should. Using mesa3d as a open GL 3.1 fixes this problem. Otherwise it occurs on every project

**Steps to reproduce:** Add a cube in Godot 3.1 on intel g41 express on GLES2 project

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment] 2019-01-31 16:58
Without logs this might be pretty hard to find and fix.

**Comment by TIBI4** [comment] 2019-01-31 21:36
Where do I find the needed logs? I'm with the same problem but in HTML5 export, and looking at the browser console, does not show any error related.

> Without logs this might be pretty hard to find and fix.

**Comment by bojidar-bg** [comment] 2019-02-01 10:12
Well, Godot prints some information to stdout, which you can get on windows by running it from the command line, or from the console window which opens alongside Godot (in debug builds).

**Comment by nikhilCad** [comment] 2019-02-01 12:33
Here is the log
https://drive.google.com/file/d/1z8KfR_Wu7dqddRKIxIMUoh05Cp2Slssi/view?usp=drivesdk

**Comment by nikhilCad** [comment] 2019-02-15 08:25
I just wanted to point out that this issue has NOT been fixed in Godot 3.1 beta 4
![image](https://user-images.githubusercontent.com/47214394/52843864-57532e00-3129-11e9-8530-bdf9a7c81bd0.png)

**Comment by nikhilCad** [comment] 2019-02-15 09:38
![image](https://user-images.githubusercontent.com/47214394/52847767-16601700-3133-11e9-8059-d19c1337b1e4.png)
It turned out that I just needed to add a light to the scene. Though when I ran the same project on Mesa with a opengl 3.3 'emulated' environment, I found that a mesh with no materials was rendering blue without any material or light.
It is still a issue, but a minor one now.

GLES3-no lights give blue mesh
GLES2-no lights give black mesh

**Comment by akien-mga** [comment] 2019-02-27 13:27
Is this still reproducible in 3.1 beta 8 or later?
Also make sure to have the `default_env.tres` defined as default environment in your project settings, otherwise it's normal that there is no default lighting. If it's defined and it still doesn't work, it might be that the settings used in `default_env.tres` don't work for your GPU, you could try to edit them to see what happens.

**Comment by nikhilCad** [comment] 2019-02-27 14:48
Using beta 8 here, and its still not fixed
![untitled](https://user-images.githubusercontent.com/47214394/53498608-a5264980-3acc-11e9-9059-1987f51d8ed1.png)
With that said, g41 chipset is quite old,2008 I think, and I dont think any serious(or even hobbyist) would be using it. Only I am stuck with it. :)

**Comment by nikhilCad** [comment] 2019-05-12 11:29
Still present in latest Calinou builds

**Comment by clayjohn** [comment] 2019-12-15 18:06
Is this present in 3.1.2 or 3.2 beta x?

**Comment by nikhilCad** [comment] 2019-12-16 07:50
@clayjohn 
3.2 beta 3

No lights in any of these

Default Environment
![image](https://user-images.githubusercontent.com/47214394/70888257-ebba4580-2005-11ea-9001-e8c97f5f94d3.png)

No Environment(red material applied)
![image](https://user-images.githubusercontent.com/47214394/70888339-202e0180-2006-11ea-92e9-e55c52aab14b.png)

No Environment No material
![image](https://user-images.githubusercontent.com/47214394/70888386-3b990c80-2006-11ea-8157-da5679c34b90.png)

A custom environment with no changes to default values(red material)
![image](https://user-images.githubusercontent.com/47214394/70888521-8e72c400-2006-11ea-9cfa-48b6dc59a11e.png)

A custom environment with no changes to default values(red material)+ directional light
![image](https://user-images.githubusercontent.com/47214394/70888629-ced24200-2006-11ea-8d8e-1102e9e80552.png)

**Comment by nikhilCad** [comment] 2019-12-16 07:55
No light; Red Material; Custom Env; Ambient light set to white
![image](https://user-images.githubusercontent.com/47214394/70888936-73548400-2007-11ea-9330-657c10eee025.png)

**Comment by nikhilCad** [comment] 2019-12-16 08:00
Do remember that my hardware is ancient.

**Comment by KoBeWi** [comment] 2020-12-07 16:24
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Zireael07** [comment] 2020-12-07 16:26
I seem to remember a similar bug being closed as fixed after the batching changes?

**Comment by Calinou** [comment] 2020-12-07 17:01
> I seem to remember a similar bug being closed as fixed after the batching changes?

Yes, that was https://github.com/godotengine/godot/issues/30330.

**Comment by nikhilCad** [comment] 2020-12-08 06:54
@KoBeWi I am extremely sorry, but I have sold off that PC. So I can't check.

**Comment by KoBeWi** [comment] 2020-12-08 10:31
Closing then. If someone can still reproduce, comment.

**Closed by KoBeWi** 2020-12-08 10:31 UTC
Labels: bug, cherrypick:3.2, topic:rendering

**Comment by DeudzXD** [comment] 2021-12-13 01:15
I have the same issue
![image](https://user-images.githubusercontent.com/77695632/145737513-9bdb433d-deff-4dbb-acdd-d7fc4a0423f1.png)
![image](https://user-images.githubusercontent.com/77695632/145738137-fa31c0e0-6c1e-4eab-a154-bbe644c98940.png)

I'm In Godot 3.3.3

I have a Intel i3 550
Window 10 64 bit
Also with the GLES2 render

**Comment by KoBeWi** [comment] 2021-12-13 01:17
Does it happen in Godot 3.4?

**Comment by DeudzXD** [comment] 2021-12-13 19:37
![image](https://user-images.githubusercontent.com/77695632/145876736-37a760dd-d4e2-472e-9b73-e321f95d928f.png)
Yep

**Comment by ghsoares** [comment] 2022-01-03 15:08
![image](https://user-images.githubusercontent.com/43936806/147946527-8e22bfc4-e923-45cb-84d4-a3677b589fd3.png)
Still getting the same issue on Godot v3.4.stable.mono.official.206ba70f4

Windows 10 64 Bit
Intel HD Graphics 2000
GLES 2

**Comment by ghsoares** [comment] 2022-01-03 15:14
What does fix is to use a mesa 3d .dll file in the same directory of the godot executable, this way Godot will be forced to render in the CPU instead of the GPU using mesa drivers.

**Comment by 8bou3** [comment] 2022-01-09 10:16
# I tested this on an old CPU with intel HD Graphics:

### Ubuntu 20.04 LTS:
Godot worked will without any problem with meshes or performance on both GLES2 and GLES3

### Windows 10 Pro 64-bit:
Meshes are completely black,
Then I tried to force render on the CPU by using this [.dll file](https://drive.google.com/file/d/1bzylSRdNhCR2yCinL4vKS7v-OyRdt2E0/)
At first it seems good but I noticed that the imported materials are completely black.

### Testing device:
- **CPU:** Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz
- **GPU:** `(built-in)` Intel® HD Graphics for Previous Generation Intel® Processors
- **RAM:** 2×Samsung 2GB DDR3 SDRAM Memory 240pin PC3-10600U 1333MHz `(2×2GB DDR3)`
- **OS:** Windows 10 Pro 64-bit + Ubuntu 20.04 LTS

## Screenshots (using [.dll file](https://drive.google.com/file/d/1bzylSRdNhCR2yCinL4vKS7v-OyRdt2E0/)):

### GLES2:
- **FPS:** (170 - 180)
- **Left:** raw mesh instance
- **Center:** mesh instance with spatial material (no imports)
- **Right:** mesh instance with spatial material (imported texture)

![image](https://user-images.githubusercontent.com/67455370/148677432-ad83bb50-1abc-46cd-b19c-45f66d35b795.png)

### GLES3:
- **FPS:** (31 - 34)
- **Left:** raw mesh instance
- **Center:** mesh instance with spatial material (no imports)
- **Right:** mesh instance with spatial material (imported texture)

![image](https://user-images.githubusercontent.com/67455370/148677850-576b466e-b88d-4327-94bf-c885517b25f7.png)

**Comment by return2monki** [comment] 2022-08-03 22:22
https://i.imgur.com/I95crK7.gif - Windows 10 Intel HD Graphics 620 on Godot 3.4.5

Just wanted to show this issue still exists, it only happens without a directional light OR if you have a meshinstance with a spatialmaterial and another without in the same area. No problem in GLES2 or with directional light visible.

The flickering speed is not consistent, some camera positions it doesn't flicker at all. Some directions it flickers even faster.

Btw I'm having the exact same problems from https://github.com/godotengine/godot/issues/30330 which was closed. Either something broke it since then or it was never really fixed. I'm using roughly default settings on a new project.

OP seems to having a separate problem from me and all the other people hijacking this issue though, to be clear. But maybe the problem is related?

**Comment by 066489** [comment] 2024-01-06 03:26
> https://i.imgur.com/I95crK7.gif - Windows 10 Intel HD Graphics 620 على Godot 3.4.5
> 
> أردت فقط أن أوضح أن هذه المشكلة لا تزال موجودة، فهي تحدث فقط بدون ضوء اتجاهي أو إذا كان لديك مثيل شبكي يحتوي على مادة مكانية وآخر بدونه في نفس المنطقة. لا توجد مشكلة في GLES2 أو مع رؤية الضوء الاتجاهي.
> 
> سرعة الوميض ليست متسقة، وفي بعض أوضاع الكاميرا لا تومض على الإطلاق. تومض في بعض الاتجاهات بشكل أسرع.
> 
> راجع للشغل أواجه نفس المشاكل بالضبط من [رقم 30330](https://github.com/godotengine/godot/issues/30330) الذي تم إغلاقه. إما أن شيئًا ما قد كسره منذ ذلك الحين أو لم يتم إصلاحه أبدًا. أنا أستخدم الإعدادات الافتراضية تقريبًا في مشروع جديد.
> 
> يبدو أن OP يواجه مشكلة منفصلة عني وعن جميع الأشخاص الآخرين الذين يختطفون هذه المشكلة، لكي نكون واضحين. ولكن ربما تكون ا![02](https://github.com/godotengine/godot/assets/68303825/e2c765a8-57bb-43dc-b356-6423a9be978e)
![01](https://github.com/godotengine/godot/assets/68303825/6274fa38-c609-4eed-b019-fe725c77ba28)



> @clayjohn 3.2 بيتا 3
> 
> لا أضواء في أي من هذه
> 
> البيئة الافتراضية ![صورة](https://user-images.githubusercontent.com/47214394/70888257-ebba4580-2005-11ea-9001-e8c97f5f94d3.png)
> 
> لا توجد بيئة (تم تطبيق المادة الحمراء) ![صورة](https://user-images.githubusercontent.com/47214394/70888339-202e0180-2006-11ea-92e9-e55c52aab14b.png)
> 
> لا توجد بيئة لا توجد مادة ![صورة](https://user-images.githubusercontent.com/47214394/70888386-3b990c80-2006-11ea-8157-da5679c34b90.png)
> 
> بيئة مخصصة بدون تغييرات على القيم الافتراضية (المادة الحمراء) ![صورة](https://user-images.githubusercontent.com/47214394/70888521-8e72c400-2006-11ea-9cfa-48b6dc59a11e.png)
> 
> بيئة مخصصة بدون تغييرات على القيم الافتراضية (المادة الحمراء) + ضوء الاتجاه ![صورة](https://user-images.githubusercontent.com/47214394/70888629-ced24200-2006-11ea-8d8e-1102e9e80552.png)

ERROR
![01](https://github.com/godotengine/godot/assets/68303825/82c9658a-28b6-41eb-9073-cb2e8ba6de8f)
FIX
![02](https://github.com/godotengine/godot/assets/68303825/1eb63689-aff3-44f0-9a74-35eb877ad3e3)

**Comment by Calinou** [comment] 2024-01-09 01:12
>  FIX

This doesn't actually fix the issue, merely sidestep it. Using a fixed ambient light color is different from using the sky as a source of ambient light color.

**Comment by 066489** [comment] 2024-01-28 23:40
As you said, it's just avoiding the problem, but at least it works if you intend to work on your project on another computer temporarily, and if you want to export your project, just fill the world environment settings in another computer and paste them inside your project, or move your entire project to export it from another computer.

Perhaps the problem is due to the incompatibility of Godot 3.5 with the motherboard or processor, because I did not encounter the problem in Godot 4 or another device.
This is a partial solution for those who have not found a solution and do not want to spend their brains trying to find a solution
And sorry for talking so much
