### ISSUE TITLE
Godot crashes when using vscode

### ISSUE THREAD

**Issue by Daniel-Ros** [godotengine/godot#52375] opened 2021-09-03 11:42 UTC
### Godot version

3.3.3-1

### System information

manjaro 

### Issue description

Downloaded Godot from the official repo, and using VScode as an external editor, made simple node with an area2D and rectangle collision shape.
when trying to add a signal to the area2D node itself, the function does not appear automatically and when I try to add it manually Godot crashes  
after I re-open Godot it de-attaches the script from the nore

backtrace:
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7f69382bada0] (??:0)
[2] /usr/bin/godot(+0x2ad2797) [0x556dc4ce5797] (??:0)
[3] /usr/bin/godot(+0x2a9e7ef) [0x556dc4cb17ef] (??:0)
[4] /usr/bin/godot(+0x86456b) [0x556dc2a7756b] (??:0)
[5] /usr/bin/godot(+0x85823b) [0x556dc2a6b23b] (??:0)
[6] /usr/bin/godot(+0x859286) [0x556dc2a6c286] (??:0)
[7] /usr/bin/godot(+0x2aa11cf) [0x556dc4cb41cf] (??:0)
[8] /usr/bin/godot(+0x2aa2117) [0x556dc4cb5117] (??:0)
[9] /usr/bin/godot(+0x8775a6) [0x556dc2a8a5a6] (??:0)
[10] /usr/bin/godot(+0x877f5c) [0x556dc2a8af5c] (??:0)
[11] /usr/bin/godot(+0x83ee5b) [0x556dc2a51e5b] (??:0)
[12] /usr/bin/godot(+0x84403a) [0x556dc2a5703a] (??:0)
[13] /usr/bin/godot(+0x844210) [0x556dc2a57210] (??:0)
[14] /usr/bin/godot(+0x2a9ea24) [0x556dc4cb1a24] (??:0)
[15] /usr/bin/godot(+0x1ac4255) [0x556dc3cd7255] (??:0)
[16] /usr/bin/godot(+0x1acf5ea) [0x556dc3ce25ea] (??:0)
[17] /usr/bin/godot(+0x697801) [0x556dc28aa801] (??:0)
[18] /usr/bin/godot(+0x67af24) [0x556dc288df24] (??:0)
[19] /usr/bin/godot(+0x665e2f) [0x556dc2878e2f] (??:0)
[20] /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f69382a5b25] (??:0)
[21] /usr/bin/godot(+0x66a03e) [0x556dc287d03e] (??:0)
-- END OF BACKTRACE --

### Steps to reproduce

add the stool script to the stool node, add the signal, manually add the signal _on_input_event

### Minimal reproduction project

[Toilet manager.zip](https://github.com/godotengine/godot/files/7105583/Toilet.manager.zip)

**Comment by KoBeWi** [comment] 2021-09-03 12:09
Duplicate of #51923

**Closed by KoBeWi** 2021-09-03 12:09 UTC
