### ISSUE TITLE
Raycast2D hits disabled collision shapes

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#12685] opened 2017-11-05 21:49 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 alpha 2 Mono version

**Issue description:**

Expecting raycasts to ignore disabled collision shapes. Unless there is a different usage in mind?

**Comment by kubecz3k** [comment] 2017-11-06 19:32
@Boothand could you confirm if this was working correctly in 2.x?

**Comment by kubecz3k** [comment] 2017-11-06 19:33
Also please provide small reproduction project. It's not much work, but it helps a lot.

**Comment by Boothand** [comment] 2017-11-08 00:40
[Raycast disabled collider example.zip](https://github.com/godotengine/godot/files/1452187/Raycast.disabled.collider.example.zip)

In 2.1, there is no 'Disabled' flag on the CollisionShape2D, so don't know how to compare.

**Comment by kubecz3k** [comment] 2017-11-08 10:48
@Boothand, Oh I see. So it's a new feature and a new bug :)

**Comment by akien-mga** [comment] 2018-01-05 15:18
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by Boothand** [comment] 2018-01-05 15:51
I won't need it personally (don't have time for Godot for a while) but I'd argue it's gameplay critical. Something that is not supposed to have collision in various states will be considered by raycasts, and working around it could be pretty troublesome, unless there is a way to 'raycast all' and manually skip every collider that is set to disabled. Sorry I don't have time to gear up and look into this now though.

**Comment by ondesic** [comment] 2018-04-19 04:47
I can confirm this problem is still here, which completely breaks my game because my object has different collision bodies for when he ducks and other actions.  These are all disabled but raycasting still picks up all the shapes.  It would be GREAT if this could be fixed.

**Comment by reyalpsirc** [comment] 2018-09-10 22:36
For me what works as a temporary workaround is to switch the `collision_layer` to something that I do not use when I want it disabled.

**Comment by salomander86** [comment] 2018-10-18 12:32
3.0.6 the bug is still there, and it's pretty critical =(

**Comment by reduz** [comment] 2018-11-10 12:01
Can't reproduce any longer, so closing.

**Comment by reduz** [comment] 2018-11-10 12:02
I am not sure what fixed this in master though so it could be backported, @hpvb may have an idea? 
Else let me know and I could try looking for it.

**Closed by reduz** 2018-11-10 12:01 UTC
Labels: bug, confirmed, topic:physics

**Comment by reduz** [comment] 2018-11-10 12:02
(i did not fix it btw, at least not willingly)

**Comment by akien-mga** [comment] 2018-11-10 21:09
I'll check what fixed it in the master branch.

**Comment by akien-mga** [comment] 2018-11-10 21:56
Found it, it was fixed by #17151.
