### ISSUE TITLE
Viewport texture ignored in 3D material outside of Editor

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#31301] opened 2019-08-11 19:46 UTC
**Godot version:**
3.1.1 stable

**OS/device including version:**
Linux/Web

**Issue description:**
ShaderMaterial with ViewportTexture, do not have this texture outside of editor
**if this ShaderMaterial set in Mesh->Material**

**Steps to reproduce:**
Create Viewport with Sprite, create Plane, make ShaderMaterial with Viewport texture, set it as material in **Mesh->Material**, save this Material
duplicate Plane, in second Plane set saved Material in Material or Geometry->Material Override
**both Planes will display Viewport texture in Editor**
Launch project, one of Plane will be black(no texture).
(on screenshot 3 planes, one for each material option)
![1](https://user-images.githubusercontent.com/24825887/62838801-86d29580-bc89-11e9-84c4-dafbfe5eb9c1.png)

**Minimal reproduction project:**
https://danilw.github.io/godot-utils-and-other/bug_viewport/BUG_viewport_material.zip

**Comment by clayjohn** [comment] 2019-08-11 20:11
All resources using the ViewportTexture need to be set to "Local to Scene" Your first plane is not set to local to scene so the texture doesn't appear, but in your other one you did set "Local to Scene" so it did appear.

**Comment by danilw** [comment] 2019-08-11 20:13
but it work in Editor...so
it little confused me, sorry if it not bug

**Comment by TheDuriel** [comment] 2019-08-11 20:14
iirc ViewportTextures will print a configuration warning in this scenario.

**Comment by clayjohn** [comment] 2019-08-11 20:17
Ah, actually this is a duplicate of https://github.com/godotengine/godot/issues/19247

Closing in favour of that. 

@TheDuriel It prints a warning when the ViewportTexture is not set local to scene, but it doesn't print a warning when the mesh is not set local to scene. But it needs both.

**Closed by clayjohn** 2019-08-11 20:17 UTC
Labels: discussion, documentation, topic:core, topic:rendering
