### ISSUE TITLE
System still turning off the screen

### ISSUE THREAD

**Issue by AndersonVale** [godotengine/godot#47652] opened 2021-04-05 23:47 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Ubuntu Linux 64bits 20.04 / Radeon R7 250X

**Issue description:**
Playing the game in fullscreen/windowed with a joystick, causes my screen turning off after 5 minutes
The keep_screen_on option is enabled, but have no effect

**Comment by Calinou** [comment] 2021-04-05 23:52
Duplicate of https://github.com/godotengine/godot/issues/5073.

**Closed by Calinou** 2021-04-05 23:52 UTC
