### ISSUE TITLE
Godot editor crashes when deleting a script

### ISSUE THREAD

**Issue by OscarPindaro** [godotengine/godot#71853] opened 2023-01-22 11:46 UTC
### Godot version

4.14

### System information

Linux oscardeck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux

### Issue description

When deleting a script, the Godot editor freezes for some seconds and then completely crashes. When reopening Godot, the file has been deleted.

### Steps to reproduce

If you are using my project:

1. Select the foo.gd file
2. Press Del or right click and delete

If creating a project on your own:

1. Create a new godot project
2. create a new script with the default configuration
4. Select the foo.gd file
5. Press Del or right click and delete

![image](https://user-images.githubusercontent.com/39062210/213914102-a3859a87-7e1d-478e-8c68-2ca943888c51.png)

### Minimal reproduction project

[GodotTest.zip](https://github.com/godotengine/godot/files/10474321/GodotTest.zip)

**Comment by martinruefenacht** [comment] 2023-01-22 11:55
I think this is a duplicate of #71713

**Comment by OscarPindaro** [comment] 2023-01-22 12:18
Yes you are right, the main difference is that I'm on Linux

**Comment by akien-mga** [comment] 2023-01-22 12:46
This is unlikely to be platform specific.

Duplicate of #71713

**Closed by akien-mga** 2023-01-22 12:46 UTC
