### ISSUE TITLE
scene editor enhancements

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27873] opened 2019-04-09 22:20 UTC
Proposal: 

Add the ability to cycle between open scenes via hotkey. 

Ctrl+Tab (Test it in your browser.) This would allow for a faster workflow when editing several scenes at once. (I am doing a lot of menial labor right now manually switching between scenes by clicking the tabs. Especially since i need to make various similar changes to scenes where instancing is not a viable option. Like loading a new texture into a sprite for 12 scenes in a row.)

Add a menu option for closing all open scenes, perhaps in a context menu in the Scene Tab list. (Try it in your browser.) This menu could be expanded with a reload option as well (closes then opens the scene again, to allow tool scripts to refresh.),

**Comment by qarmin** [comment] 2019-04-10 06:55
https://github.com/godotengine/godot/pull/26597

**Comment by groud** [comment] 2019-04-10 07:06
Closing as a duplicate of #26597 and #19701

**Closed by groud** 2019-04-10 07:06 UTC
