### ISSUE TITLE
GPUParticles2D causes high GPU load in editor

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#74281] opened 2023-03-03 09:44 UTC
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

GPUParticles2D causes high GPU load when visible in editor window. This is a problem when testing and games from the editor because the GPU usage of the editor can cause the game to lag, which makes testing difficult.
Switching to a script tab in the editor, or making the particle system node hidden instantly drops the GPU usage to almost zero.

The actual GPU load varies, with the same scene sometimes causing near 100% load and sometimes more like 30%, just by restarting Godot or Windows.

I have encountered this using a particle system with 40 particles and a lifetime of 3 seconds. I included the particle system in the MRP.

### Steps to reproduce

Create a 2D particle system with around 40 particles. It seems like more effects cause more load.
Check GPU load in system while toggling visibility of particle system.

### Minimal reproduction project

[MRP_particles_godot4.zip](https://github.com/godotengine/godot/files/10880620/MRP_particles_godot4.zip)

**Comment by Calinou** [comment] 2023-03-03 09:50
Duplicate of https://github.com/godotengine/godot/issues/39758.

As a workaround, hide particle nodes in the editor and show them using a script that sets `visible = true` in `_ready()`.

**Closed by Calinou** 2023-03-03 09:50 UTC
