### ISSUE TITLE
move_and_collide jaggy collision results, velocity/distance seems odd

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#57918] opened 2022-02-10 15:32 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, RTX 2070

### Issue description

When using move_and_collide the collision isn't smooth along surfaces. If animated the motion looks jaggy. This behaviour does not has happen in Alpha 1, there it was smooth all along.
###edit
In fact in Alpha 1 the motion is also jaggy but around the factor 10 less.
Maybe only a default value has been changed?
Using the default physics settings. Settings look the same in projectsettings(advanced)
###
The distance argument does not make sense to me. The move_and_collide does not travel the distance given when called.
(But this could be my misinterpretation)

### Steps to reproduce

see attached file
watch the jaggy motion when the ball "slides" along the walls

### Minimal reproduction project

[Godot4Test.zip](https://github.com/godotengine/godot/files/8042218/Godot4Test.zip)

**Comment by fabriceci** [comment] 2022-02-16 12:07
I just read the code, I saw you forget to multiply the speed (called `dir` in your code) with `delta`. Is it solving your issue? This was changed after alpha 1 (before the delta was applied automatically).

**Comment by D2klaas** [comment] 2022-02-16 12:19
When i multiply the dir with delta the jaggyness reverts back to the behavior of ALPHA 1 ... way smoother. But it isn't a continuous motion. i dont know the inner workings of the godot physics ... it looks like some hidden voxel world to collide with (maybe thats it how it works).
Still don't know what the actual length of the dir should mean. I've thought move_and_collide moves the object by the dir vector (instantly) and collides(stops) with/when hitting anything.

But anyway ... many thanks, it looks way better now!

**Comment by fabriceci** [comment] 2022-03-09 13:20
I think the issue should be closed as the regression was due to the recent API change which require to use the `delta`. For the remaining jaggyness, seems to be due to the double `force_update_transform` used in the code before and after `move_and_collide`.

**Closed** 2022-03-09 13:27 UTC
Labels: bug, topic:physics, regression
