### ISSUE TITLE
C# exported members of base class lose their values on assembly reload when derived class is `[Tool]`

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#54415] opened 2021-10-30 11:20 UTC
### Godot version

v3.3.4.stable.mono.official [faf3f883d]

### System information

Windows 10

### Issue description

I have a base class which exports a member property:

```csharp
namespace RefreshIssue
{
    public class BaseClass : Node
    {
        private string _test;
 
        [Export]
        public string Test
        {
            get => _test; 
            set => _test = value;
        }
    }
}
```

I also have a derived class which also exports a member property and is `[Tool]`:

```csharp
namespace RefreshIssue
{
    [Tool] 
     public class DerivedClass : BaseClass
    {
        private string _test2;

        [Export] 
        public string Test2
        {
            set => _test2 = value;
            get => _test2;
        }
    }
} 
```

I create an empty scene and put in  a single node of `DerivedClass`. I fill out both properties and save the scene. Now I change some code (maybe in another class) and trigger a rebuild in the editor. After the assemblies are reloaded the `Test1` property (of the base class) is reset to `null` (its default value) while the `Test2` property still has its value set. If the derived class has no `[Tool]` set , then both properties stay intact.

### Steps to reproduce

Using the attached sample project, open `test.tscn`. Check the inspector values of the only node in the scene. They are initialized like this:

![image](https://user-images.githubusercontent.com/327257/139530854-54acd281-f246-4083-b120-42783f72a57e.png)

Now edit a script file (e.g. add a blank space somewhere) and re-build in the editor while the scene is still open. The editor will start the build and then do an assembly reload. After this, the property of the base class is reset to `null`:

![image](https://user-images.githubusercontent.com/327257/139530898-1a9bb5e7-afe8-4461-834e-e2f6620ac685.png)

### Minimal reproduction project

[RefreshIssue.zip](https://github.com/godotengine/godot/files/7446384/RefreshIssue.zip)

**Comment by raulsntos** [comment] 2021-10-30 11:33
Duplicate of #37812

**Comment by derkork** [comment] 2021-10-30 11:39
Man I searched the bug list up and down and i couldn't find it. I guess i need to improve my search-foo :D

**Closed** 2021-10-30 12:21 UTC
