### ISSUE TITLE
Networking rpc broken when using separate server side and client side scripts

### ISSUE THREAD

**Issue by pietru2004** [godotengine/godot#80248] opened 2023-08-04 10:51 UTC
### Godot version

4.1

### System information

Windows 10 Forward+

### Issue description

I have Network script that is diffrent on both server side and client side.
It is separated so server would need less maintaining.
Server is used only to connecting players, whenever new player joins server only updates player order list.

**Theory is**
After setting player order/sending new one function is the same on both sides - it runs set_player_order, where on server it just is pass, on server the current "host/master client" synces world data to newly connected client so that client can sync vehicles...

**In Practice**
I get
![obraz](https://github.com/godotengine/godot/assets/51274570/20b78de5-05d0-4f9c-8c1d-1576b9b6d856)
![obraz](https://github.com/godotengine/godot/assets/51274570/33670645-03f5-451b-877b-57948b324778)

I have checked and seen proposal(https://github.com/godotengine/godot-proposals/issues/7065) talking about it, but I think this is a bug cause the function meant to be called is the same on both sides...

### Steps to reproduce

Have 2 scripts/2 projects
Both have some functions shared and one or both have some that are unique
Make Sure node path is the same on both
Try calling RPC for example from server to client.

(I think code from (https://github.com/godotengine/godot-proposals/issues/7065) should work to get this error)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-08-04 12:20
> I have checked and seen proposal(https://github.com/godotengine/godot-proposals/issues/7065) talking about it, but I think this is a bug cause the function meant to be called is the same on both sides...

As mentioned in the proposal, *all* RPC methods must be implemented on both client and server, even if they're empty on one side.

Closing, as this is not a bug but a design decision (which https://github.com/godotengine/godot-proposals/issues/7065 is debating).

**Closed by Calinou** 2023-08-04 12:20 UTC
