### ISSUE TITLE
"@tool“ signal connect is not working when you first create scripts

### ISSUE THREAD

**Issue by yulan233** [godotengine/godot#82443] opened 2023-09-27 13:55 UTC
### Godot version

4.2dev5

### System information

Windows11 Godot4.2dev5 Forward

### Issue description

When you first create a script, then connect a signal to a method, then add @tool, this method doesn't work, but after you restart godot it works.
![Screenshot_2023-09-27-21-48-34-097_org godotengine editor v4](https://github.com/godotengine/godot/assets/36557229/92a24e44-9960-43d2-b88e-8fd341d09e17)

### Steps to reproduce

When you first create a script, then connect a signal to a method, then add @tool, this method doesn't work, but after you restart godot it works.

### Minimal reproduction project

[Mystical Horror Racer.zip](https://github.com/godotengine/godot/files/12739431/Mystical.Horror.Racer.zip)

**Comment by wareya** [comment] 2023-09-27 16:53
Reopening the scene also works, not just restarting godot entirely.

**Comment by dalexeev** [comment] 2023-09-27 19:14
Looks like a duplicate of the following issues:

* #66381
* #81972

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-09-27 19:14 UTC
