### ISSUE TITLE
Lambda references are corrupted when script is modified while debugging

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#62769] opened 2022-07-06 07:29 UTC
### Godot version

v4.0.alpha.custom_build [83ad1231a]

### System information

Arch on 5.18.9-arch1-1

### Issue description

Code:
```gdscript
extends Node

func this_is_never_referenced1() -> void:
	print("This is never referenced1")

func this_is_never_referenced2() -> void:
	print("This is never referenced2")

func this_is_never_referenced3() -> void:
	print("This is never referenced3")

func this_is_never_referenced4() -> void:
	print("This is never referenced4")

var hello := func() -> void:
	print("Hi")

# This works fine:
#var hello := hellofunc
#func hellofunc():
#	print("Hi")

func _process(_delta: float) -> void:
	hello.call()

```

Output:
```
Hi
Hi
Hi
…
--- Script modified now ---
This is never referenced2
This is never referenced2
This is never referenced2
…
```

Note for testers: This is not an issue with GDScript member variables, since I discovered (and can reproduce) this issue with `Performance.add_custom_monitor`.

### Steps to reproduce

1) Open MRP in editor
2) Run project
3) Modify script (e.g. add a single `#` to an empty line)

### Minimal reproduction project

[test4.zip](https://github.com/godotengine/godot/files/9052581/test4.zip)

**Comment by adamscott** [comment] 2023-01-08 16:30
I confirm this issue on master (fcba87e).

**Comment by adamscott** [comment] 2023-01-08 16:33
CC @vnen

**Comment by jue131** [comment] 2023-03-16 07:59
Why is this marked as low priority? This causes runtime crashes to me all the time when i try using Synchronize Script Changes feature. In 4.0 betas, 4.0-stable and 4.0.1-rc1, sometimes, it throws a totally random error like `Cannot access member without instance`, `Bad index address`, `Invalid call: Nonexistent utility function ''`, or (most likely) just crashes the runtime making Synchronize Script Changes absolutely broken and unusable. Am I the only one having this issue?

**Comment by vnen** [comment] 2023-03-16 09:18
> Why is this marked as low priority? [...] Am I the only one having this issue?

I won't say you are the only one, but lambdas are new in Godot 4.0 which was released not long ago so there's not a lot of usage currently. This issue in particular didn't have any activity after the report, so it's natural to assume it's not hit often.

It also happens only when editing if the game is running. While annoying it's not the most critical issue since you can close the game (or it will crash, which is not much different) when editing the script. This is most a concern for `@tool` script since they run on the editor and may crash everything, but again it does not seem to happen often enough to have lots of reports.

Lastly, the "low priority" setting is for the roadmap project which was mostly used to filter issues for the 4.0 release. At that point this one didn't seem so important when compared to the other issues. The fact it was added to the project technically makes this higher priority than all the other issues that weren't added.

**Comment by NotDaze** [comment] 2023-05-16 23:42
This still happens in v4.0.2.stable.official [7a0977ce2]

**Comment by akien-mga** [comment] 2023-09-13 09:58
Tested this, the bug still seems reproducible in 4.1.1-stable and 4.2-dev (98b50eb3083094a352b36b184d7b60b77ad982fe), but in non deterministic ways.

So far I've seen:

## With 4.1.1

In all cases modifying the script while it's running causes it to stop printing "Hi".

- Sometimes it also causes a call error:

```
Invalid call to function '_process(lambda) (Callable)'. Expected 1 arguments.
0 - res://scene.gd:26 - at function: _process
```
(highlight the `hello.call()` - interesting how it refers to `_process(lambda)`, it's getting references wrong?)

- Or a crash (no debug symbols for 4.1.1)

There may be more scenarios, I then moved to testing in 4.2.

## With 4.2-dev

In all cases modifying the script while it's running causes it to stop printing "Hi".

- Sometimes it just stops printing, and nothing bad happens
- Sometimes it also causes a call error:

```
Cannot access member without instance.
0 - res://scene.gd:15 - at function: @implicit_new
1 - res://scene.gd:24 - at function: _process
```
![image](https://github.com/godotengine/godot/assets/4701338/56c72bff-9388-4ef6-a9a4-caf5a584de89)

- Sometimes it causes another call error:

```
Invalid call to function '_process(lambda) (Callable)'. Expected 1 arguments.
0 - res://scene.gd:25 - at function: _process
```

- Or another error:

```
Invalid call. Nonexistent utility function ''.
0 - :17 - at function:
1 - res://scene.gd:26 - at function: _process
```
Plus these errors:
```
ERROR: Condition "path.is_empty()" is true.
   at: compute_checksums (./editor/debugger/debug_adapter/debug_adapter_types.h:70)
ERROR: Resource file not found: res:// (expected type: )
   at: _load (./core/io/resource_loader.cpp:279)
```

- Or yet another error:

```
Internal script error! Opcode: 1 (please report).
0 - :16 - at function:
1 - res://scene.gd:26 - at function: _process
```

- And finally, sometimes it crashes, with this stacktrace:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (98b50eb3083094a352b36b184d7b60b77ad982fe)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x36980) [0x7f5c5b214980] (??:0)
[2] StringName::StringName(StringName const&) (/usr/include/c++/12/bits/atomic_base.h:488)
[3] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/akien/Projects/godot/godot.git/./modules/gdscript/gdscript_vm.cpp:2212)
[4] GDScriptLambdaCallable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/akien/Projects/godot/godot.git/./modules/gdscript/gdscript_lambda_callable.cpp:90)
[5] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/akien/Projects/godot/godot.git/./core/variant/callable.cpp:50)
[6] _VariantCall::func_Callable_call(Variant*, Variant const**, int, Variant&, Callable::CallError&) (/home/akien/Projects/godot/godot.git/./core/variant/variant_call.cpp:1025)
[7] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.editor.dev.x86_64.orig() [0x98695ee] (/home/akien/Projects/godot/godot.git/./core/variant/variant_call.cpp:2040)
[8] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/akien/Projects/godot/godot.git/./core/variant/variant_call.cpp:1184)
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/akien/Projects/godot/godot.git/./modules/gdscript/gdscript_vm.cpp:1734)
[10] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/akien/Projects/godot/godot.git/./modules/gdscript/gdscript.cpp:1843)
[11] bool Node::_gdvirtual__process_call<false>(double) (/home/akien/Projects/godot/godot.git/./scene/main/node.h:318 (discriminator 1))
[12] Node::_notification(int) (/home/akien/Projects/godot/godot.git/./scene/main/node.cpp:58)
[13] Node::_notificationv(int, bool) (/home/akien/Projects/godot/godot.git/./scene/main/node.h:49 (discriminator 14))
[14] Object::notification(int, bool) (/home/akien/Projects/godot/godot.git/./core/object/object.cpp:831)
[15] SceneTree::_process_group(SceneTree::ProcessGroup*, bool) (/home/akien/Projects/godot/godot.git/./scene/main/scene_tree.cpp:948)
[16] SceneTree::_process(bool) (/home/akien/Projects/godot/godot.git/./scene/main/scene_tree.cpp:1020 (discriminator 2))
[17] SceneTree::process(double) (/home/akien/Projects/godot/godot.git/./scene/main/scene_tree.cpp:510)
[18] Main::iteration() (/home/akien/Projects/godot/godot.git/main/main.cpp:3505)
[19] OS_LinuxBSD::run() (/home/akien/Projects/godot/godot.git/platform/linuxbsd/os_linuxbsd.cpp:933)
[20] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.editor.dev.x86_64.orig(main+0x15a) [0x53f5dc0] (/home/akien/Projects/godot/godot.git/platform/linuxbsd/godot_linuxbsd.cpp:76)
[21] /lib64/libc.so.6(+0x236b7) [0x7f5c5b2016b7] (??:0)
[22] /lib64/libc.so.6(__libc_start_main+0x85) [0x7f5c5b201775] (??:0)
[23] /home/akien/Projects/godot/godot.git/bin/godot.linuxbsd.editor.dev.x86_64.orig(_start+0x21) [0x53f5ba1] (??:?)
-- END OF BACKTRACE --
```

**Comment by rune-scape** [comment] 2023-09-13 20:55
i ran into this problem so much, i got a fed up and fixed it myself, i have a working testable version here: https://github.com/rune-scape/godot/tree/rune-lambda-hotswap

it swaps out the function pointers used in LambdaCallables when a script is reloaded
if it cant find a good replacement it invalidates the callable, so no more 'Bad Address Index' and crashes, it tells you its called an invalid lambda
the logic it uses to swap lambdas is very simple right now, swapping only if the argument count vaguely matches, and no lambdas were added or removed, evaluated for each function the lambda was in
also should be safe across threads, because lambdas can be created on any thread. i took care to make sure it wouldnt slow lambda creation down, but wouldnt create any data shearing

**Closed** 2023-10-20 13:16 UTC
Labels: bug, topic:gdscript, confirmed, high priority
