### ISSUE TITLE
Export vas of type array with a set function always get reset to their default value

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [godotengine/godot#66269] opened 2022-09-22 17:03 UTC
### Godot version

4.0.beta1

### System information

Window 10

### Issue description

When using an `@export var` of type Array with a set function, it will always get reset to its default value when running the scene, regardless of what the user puts in the properites editor. In `@tool` scripts, this overrides the values in the properties editor as well.

### Steps to reproduce

Create a node with the following code in it:

```gdscript
@export var array: Array[int] = [12] :
	set(val):
		array = val


func _ready():
	print(array)
```

Set the `array` variable to something other than `[12]` by editing the properties of the node in the properties editor.

Run the scene.

**Expected result:** The engine prints the value you set `array` to, which should not be `[12]`

**Obtained result:** The engine prints the value `[12]`

### Minimal reproduction project

[test_export_array.zip](https://github.com/godotengine/godot/files/9627929/test_export_array.zip)

**Comment by Lilith-In-Starlight** [comment] 2022-09-22 17:04
The interesting thing is that this always results in a call to the `set` function. If you add a print statement to the set function, it will be printed once the value is changed.

**Comment by gotnospirit** [comment] 2022-09-24 00:35
The setter is not called, it seems to be specific to `Array`, because it works with `Dictionary` or `int`.
Not related to the default value, and setting more than one value in inspector change nothing

**Comment by Calinou** [comment] 2022-09-24 15:11
Duplicate of https://github.com/godotengine/godot/issues/62753.

**Closed by Calinou** 2022-09-24 15:11 UTC
