### ISSUE TITLE
Vulkan: GPUParticles3D makes fps goes down when selecting the Node

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49170] opened 2021-05-28 17:44 UTC
**Godot version:**

v4.0.dev.custom_build.364ea7f28

**OS/device including version:**
windows 10 x64
AMD R7 200 series

**Issue description:**
This is a simple Particle with no material, emitting just one Quad mesh:
![image](https://user-images.githubusercontent.com/58845030/120022623-0a768700-bfc3-11eb-8ec3-31e4c1c25147.png)
Notice that it isnt select and at FPS

Now look when the user selects the node:
![image](https://user-images.githubusercontent.com/58845030/120022678-211cde00-bfc3-11eb-8a2d-97fcf5a00d3d.png)

Error Message:
```
ERROR: Condition "!uniform_set" is true.
at: RenderingDeviceVulkan::draw_list_bind_uniform_set (drivers\vulkan\rendering_device_vulkan.cpp:6454)
```

**Steps to reproduce:**
* Add a GPUParticles3D
* Add a quadMesh
* Add a particleMaterial
* Select the node itself

**Minimal reproduction project:**
N/A

Note:

By using CPUParticles3D I noticed that the error mentioned above (also the FPS slowdown) is caused when adding a new `New StandardMaterial3D`

**Comment by eon-s** [comment] 2021-08-14 19:29
Windows 10 and GTX 1050 here, Godot v4.0.dev.20210811.official [7188cb601]

I have noticed this with regular MeshInstance nodes and seems to be the same problem, can be triggered by opening the mesh or the material in the inspector, disappears when hiding the resource view of Mesh or StandardMaterial.

Mesh resource hidden:
![mesh hidden](https://user-images.githubusercontent.com/10215987/129458141-c5a309d2-3677-45e9-8486-b67a99ed0a22.png)

Mesh resource visible:
![mesh visible](https://user-images.githubusercontent.com/10215987/129458155-cc48f4d7-d615-4413-aaf7-221aedce80aa.png)

**Comment by KoBeWi** [comment] 2022-05-31 23:12
Can't reproduce. When selecting particles, my FPS drops from 1200 to 900 (or from 550 to 450, depending on mood), which isn't as severe as described in the OP.

Windows 10 with GTX 1060

**Comment by eon-s** [comment] 2022-06-02 18:05
Tried it again on 4.0a8 with the same settings and looks way better now, goes from 500 to 400-350, I guess it will improve later.

**Comment by Calinou** [comment] 2022-06-02 18:18
Closing per the above comments. Please comment if you can still reproduce this on the latest `master` branch.

**Closed by Calinou** 2022-06-02 18:18 UTC
Labels: bug, topic:rendering, topic:editor, regression, topic:3d, performance
