### ISSUE TITLE
Weird export value problem.

### ISSUE THREAD

**Issue by LadyDefile** [godotengine/godot#60056] opened 2022-04-09 08:53 UTC
### Godot version

v3.5.beta3.mono.official [3c0d32562]

### System information

Windows 10, C# 10, Ryzen 5, 3060 ti

### Issue description

So, had a fun bug just now. For some reason the value got stuck in my Export variable (C# script). I was exporting a property (Not sure if that is relevant). The property is `internal float DetectionRange`. I had it set to 300  by accident ( I meant 30 ). I then noticed that was much, much too big and went and set it to 30 in the editor. It *remained* 300 in the compiled game. Confused, I began to troubleshoot and I could not find any point that I was altering it to 300 in my code. My testing involved
* Print variable as the first line in _Ready(), 300 from the jump.
* Trace my code through to see if there was any point where it was modified inadvertently, nothing odd.
* Change the values in the editor... and that's when something interesting happened.

I changed the variable to *3* and it printed "3". I changed it back to "30" and it printed "300". So, on a whim, I put 29, it printed "29", I put 31, it printed "31", and I put 30 back and it printed "300".

I don't know if this is a cache issue somewhere or something but restarting the editor fixed the issue. I didn't change a single line of code, just rebooted the editor and the range is *30* as expected.

### Steps to reproduce

I haven't the slightest clue. It happened entirely by accident.

**Comment by akien-mga** [comment] 2023-11-17 09:47
Sorry for the delay replying here.

This seems pretty difficult to troubleshoot as it's not easy to reproduce. I suspect something was out of sync with compiling the C# script, and which assembly was getting loaded at runtime.

Things have improved a lot since 3.5 in the 4.x branch, so it might be that whatever caused this issue has been addressed already. If not, we'll need to find more insights into how to reproduce this consistently, but I don't expect this effort to be bootstrapped off a year old bug report for 3.x, so I suggest we close this one.

**Closed by akien-mga** 2023-11-17 09:47 UTC
Labels: bug, topic:editor, needs testing, topic:dotnet
