### ISSUE TITLE
Minimizing a transient window crashes Godot

### ISSUE THREAD

**Issue by fazil47** [godotengine/godot#57616] opened 2022-02-04 08:00 UTC
### Godot version

v4.0.alpha.custom_build (c24fc415d), v4.0.alpha1.official (31a7ddbf8)

### System information

Windows 11, Vulkan Clustered/Vulkan Mobile, Nvidia 1650

### Issue description

Minimizing any transient window crashes Godot.

https://user-images.githubusercontent.com/18116695/152492833-dbf7fb68-fe56-4979-a528-5e0e990e0d89.mp4

### Steps to reproduce

Minimize any transient window like the editor settings, project settings etc.

**Comment by KoBeWi** [comment] 2022-02-04 11:39
The stack trace is almost identical to #51537, so likely the same issue.
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.alpha.custom_build (d235c1bb1964b80d776a64aa2a1b198a8e52bf72)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] vk_optimusGetInstanceProcAddr
[2] RenderingDeviceVulkan::prepare_screen_for_drawing (C:\Users\Tomek\Desktop\Godot\godot\drivers\vulkan\rendering_device_vulkan.cpp:8697)
[3] RendererCompositorRD::prepare_for_blitting_render_targets (C:\Users\Tomek\Desktop\Godot\godot\servers\rendering\renderer_rd\renderer_compositor_rd.cpp:38)
[4] RendererViewport::draw_viewports (C:\Users\Tomek\Desktop\Godot\godot\servers\rendering\renderer_viewport.cpp:719)
[5] RenderingServerDefault::_draw (C:\Users\Tomek\Desktop\Godot\godot\servers\rendering\rendering_server_default.cpp:92)
[6] RenderingServerDefault::draw (C:\Users\Tomek\Desktop\Godot\godot\servers\rendering\rendering_server_default.cpp:383)
[7] Main::iteration (C:\Users\Tomek\Desktop\Godot\godot\main\main.cpp:2705)
[8] OS_Windows::run (C:\Users\Tomek\Desktop\Godot\godot\platform\windows\os_windows.cpp:629)
[9] widechar_main (C:\Users\Tomek\Desktop\Godot\godot\platform\windows\godot_windows.cpp:168)
[10] _main (C:\Users\Tomek\Desktop\Godot\godot\platform\windows\godot_windows.cpp:190)
[11] main (C:\Users\Tomek\Desktop\Godot\godot\platform\windows\godot_windows.cpp:204)
[12] WinMain (C:\Users\Tomek\Desktop\Godot\godot\platform\windows\godot_windows.cpp:218)
[13] __scrt_common_main_seh (d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[14] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment] 2022-02-04 12:05
Duplicate of #51537

**Closed by akien-mga** 2022-02-04 12:05 UTC
Labels: bug, platform:windows, topic:porting, crash
