### ISSUE TITLE
Godot supposedly fails to update bindings to script files and crashes after file rename in certain conditions

### ISSUE THREAD

**Issue by Exzerios** [godotengine/godot#58716] opened 2022-03-03 16:58 UTC
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10

### Issue description

Hello.

A small project is attached to this issue. The code itself was not tested due to this issue and is extremely likely to have bugs. This is probably what is causing the issue.
The issue: when renaming some script files in the project - the editor crashes and refuses to start until 1 of 2 conditions is met:
1. Either the renamed file being renamed back to what is was manually in the explorer
2. Or lines using the code from renamed file are deleted or commented

The issue **doesn't** occur if you first comment those lines of code, then change script file name, then uncomment these lines.
The issue **does** occur if one of those files being renamed manually using explorer when the editor isn't launched - it starts crashing when opening the project.

### Steps to reproduce

In the attached project there are 2 files affected by this issue:
1: //Scripts/Threading/ThreadJobSharedData.gd
2: //Scripts/Utility/Utils.gd

Trim func from Utils.gd is commented in Main.gd on line 22, and the file can be renamed freely. After uncommenting this line, renaming Utils leads to a crash, and project cannot be opened afterwards until steps in description done.

Code using ThreadJobSharedData.gd is not commented, renaming the file leads to a crash without any additional steps.

### Minimal reproduction project

[RebuildIt.zip](https://github.com/godotengine/godot/files/8179504/RebuildIt.zip)

**Comment by KoBeWi** [comment] 2022-06-01 12:58
Can't reproduce in alpha 8

**Comment by adamscott** [comment] 2023-01-08 15:27
Cannot reproduce on master (fcba87e). I suggest to close this issue.

**Closed** 2023-01-08 15:46 UTC
Labels: bug, topic:gdscript, topic:editor, crash
