### ISSUE TITLE
Scrolling with mouse click doesn't stop on mouse release

### ISSUE THREAD

**Issue by Logharaa** [godotengine/godot#48181] opened 2021-04-25 12:49 UTC
**Godot version:**
v4.0.dev.custom_build.15a85fe97

**OS/device including version:**
Windows 10

**Issue description:**
When scrolling on the file system by clicking and moving our mouse vertically, it works but the scroll doesn't stop when we release the mouse click. We need to click again to stop the scroll : 

![godot4_scroll_bug](https://user-images.githubusercontent.com/38374449/115993843-e0e9ca80-a5d4-11eb-8e42-203262c5ae5b.gif)

**Steps to reproduce:**
Add enough files to a Godot 4 project so that there is a scroll bar in the file system, and scroll down by clicking and moving your mouse downward.

**Comment by Calinou** [comment] 2021-04-25 14:30
Duplicate of https://github.com/godotengine/godot/issues/38665.

**Closed by Calinou** 2021-04-25 14:30 UTC
