### ISSUE TITLE
Main window does not refocus when a modal closes (DisplayServer regression)

### ISSUE THREAD

**Issue by name-here** [godotengine/godot#44956] opened 2021-01-06 05:02 UTC
**Godot version:**
`master` (cdfcf68)
From past experiences, I think this has happened with every version since multi-window support was added, but I could be wrong.

**OS/device including version:**
macOS Catalina

**Issue description:**
When temporary pop-up windows (I _think_ they're called modals?) close, either automatically, through the user pressing the "Close"/"Cancel" button, pressing the [esc] key, or through the user pressing the OS close button (red x), the window they came from is not re-focused.  This also happens when saving, which I think is because the engine pops up a window to show progress while saving, then closes it when done.

This behavior is especially annoying because you can't interact with the main window again (including keyboard input) until you click on it.  So, each time you save, you have to click the main window again to re-focus it.

**Steps to reproduce:**
Do anything that creates a pop-up window, then close the pop-up.  Options include:
- Clicking "New Project" in the Project Manager
- Clicking the plus icon in the Scene panel
- Saving a project, scene, etc.

**Minimal reproduction project:**
You don't even need a project to reproduce this.

**Comment by Byteron** [comment] 2022-01-25 20:51
This should be a high priority fix because it makes using the editor on macos a real pain.
every time you press CMD + S to save a script the main window loses focus and you have to click on the window again to continue typing your code. It's awful.

**Comment by Calinou** [comment] 2022-01-25 21:11
See https://github.com/godotengine/godot/issues/56938#issuecomment-1016263270.

**Comment by Byteron** [comment] 2022-01-25 21:21
if that fix is included in the Godot 4 Alpha, then it didn't work.
if the fix didn't make it into Alpha 1, then great. :D

**Comment by tavurth** [comment] 2022-04-09 23:15
@name-here @Byteron can you check this? Seems like an easy closed issue if it's working now.

**Comment by lostminds** [comment] 2023-02-28 07:30
I've not encountered this issue at all as far as I can remember, working with the 4.0 editor on macOS since the early beta versions. And I can't reproduce it on the current 4.0rc6 build. @name-here @Byteron are you still experiencing this issue?

**Comment by akien-mga** [comment] 2023-06-22 14:38
No answer, so assuming fixed.

**Closed by akien-mga** 2023-06-22 14:38 UTC
Labels: bug, platform:macos, confirmed, regression, topic:gui
