### ISSUE TITLE
3.2.4 rc4 fails to run HTML export in any run mode (Linux)

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#46733] opened 2021-03-06 16:18 UTC
**Godot version:**
Godot_v3.2.4-rc3_x11.64

**OS/device including version:**
Linux mint 64

**Issue description:**
Installed latest 3.2.3 rc4 to see if it fixes a stuttering audio issue I reported on switching scenes (#46472 ), installed all the exporters and created a HTML using all the default entries. I can confirm that 3.2.3 stable is just fine with all same settings.

When I run on Chromium or Firefox using Regular mode I first get an empty popup:
![image](https://user-images.githubusercontent.com/12863685/110213032-35ef4700-7e96-11eb-9bb4-3796090eff53.png)

Then on closing I get one of these two errors depending on which browser:
![image](https://user-images.githubusercontent.com/12863685/110213045-42739f80-7e96-11eb-82ce-c86e5ee76f2a.png)

![image](https://user-images.githubusercontent.com/12863685/110213054-4d2e3480-7e96-11eb-992f-6edf51e151da.png)

The error is within the WASM and I'm wondering if it's somehow a 32/64 bit issue?
![image](https://user-images.githubusercontent.com/12863685/110213069-60410480-7e96-11eb-851a-6f66bec24034.png)

However, if I change the Export Type to Threads then on Firefox and only firefox I do not get the popup but it immediately goes to this message:
![image](https://user-images.githubusercontent.com/12863685/110213222-fa08b180-7e96-11eb-96ac-85175b3b4452.png)

With Threads if I start Chromium, it works, however apart from a maybe 5-10fps drop, audio is honestly truly awful. The audio is stuttering every few milliseconds to the point where it simply sounds like it is breaking up and cannot keep up/ran out of memory or processing power.

Happy to provide whatever is needed.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-03-06 16:38
Duplicate of https://github.com/godotengine/godot/issues/46352 (fixed in the latest `3.2` branch).

Enabling threads in the HTML5 export requires specially configuring the web server for it.

**Closed by Calinou** 2021-03-06 16:38 UTC

**Comment by chucklepie** [comment] 2021-03-06 17:54
Thanks. Two questions please:

1. When/which release candidate will this fix arrive
2. If we are getting hosting on third party (e.g. itch.io) can we presume that they will have CORS enabled. Also in the javascript for the generated web build you can make a native fetch() command and determine if CORS is enabled.
3. Bonsus question: why is CORS required for local threading?

**Comment by Calinou** [comment] 2021-03-06 17:57
> When/which release candidate will this fix arrive

3.2.4rc4 :slightly_smiling_face: 

> If we are getting hosting on third party (e.g. itch.io) I guess we can presume that they will have CORS enabled to your specification?... 

No, as I said, you can't assume that third parties will add the required headers for security reasons.

**Comment by chucklepie** [comment] 2021-03-06 17:58
yes, i saw, so I updated my comment to:
if we cannot presume they have the same CORS data, surely the Godot code should be detection this (according to teh internets this may do the trick https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq)

So to add to my previous issue regarding stuttering, if we cannot rely on threads, then Godot will always have an audio issue that is not present on other engines?

**Comment by Calinou** [comment] 2021-03-06 17:59
> So to add to my previous issue regarding stuttering, if we cannot rely on threads, then Godot will always have an audio issue that is not present on other engines?

Yes, as running the audio worker in a dedicated thread is absolutely required to get low latency. Other engines work around this by using external JavaScript libraries to play audio such as Howler.js, but this adds a lot of complexity as soon as you want to support more than basic use cases: https://github.com/godotengine/godot/issues/40891#issuecomment-710575394

(Godot's audio engine is pretty advanced, it's not limited to playing sound effects and music.)

**Comment by chucklepie** [comment] 2021-03-06 18:01
Ok, but yes, if threads are being used there needs to be a means of detecting this otherwise people will release builds and not know whether threads are fully working or not (in my case using threads locally caused massive slowdown of audio).
