### ISSUE TITLE
Moving BakedLightmap with Light Data make engine crash

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#35554] opened 2020-01-25 16:27 UTC
**Godot version:**
3.2 rc3 MONO Version

**OS/device including version:**
Linux Manjaro

**Issue description:**
If you change the parent of a BakedLightmap with calculate Light Data make the engine crash.

**Comment by Calinou** [comment] 2020-01-25 16:44
Duplicate of #28350.

**Closed by Calinou** 2020-01-25 16:44 UTC
