### ISSUE TITLE
Setting RichTextLabel's "Line Separation" to a value below 0 crashes the game/editor.

### ISSUE THREAD

**Issue by giffi-dev** [godotengine/godot#64603] opened 2022-08-19 04:35 UTC
### Godot version

4.0.alpha14 & master

### System information

Arch Linux, AMD Radeon 6700 XT, Vulkan

### Issue description

Setting a RichTextLabel's "Line Separation" property to a value below 0 crashes the editor if done in the editor and the game if done by code.
I tried but didn't find any other fields from nodes which would cause a crash like this.

### Console output about the crash:
```
ERROR: Index p_index = 1 is out of bounds (count = 1).
   at: operator[] (./core/templates/local_vector.h:168)
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.alpha14.official (106b6805018649b13da9e9508e80611f62ed660a)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e8e0) [0x7f665503e8e0] (??:0)
[2] /usr/bin/godot4() [0x2c36aed] (??:0)
[3] /usr/bin/godot4() [0x423d3b4] (??:0)
[4] /usr/bin/godot4() [0x295ffd4] (??:0)
[5] /usr/bin/godot4() [0xf38ffa] (??:0)
[6] /usr/bin/godot4() [0x4243388] (??:0)
[7] /usr/bin/godot4() [0x406fa94] (??:0)
[8] /usr/bin/godot4() [0x4825ec5] (??:0)
[9] /usr/bin/godot4() [0x42ab757] (??:0)
[10] /usr/bin/godot4() [0x2a2bfe5] (??:0)
[11] /usr/bin/godot4() [0xe29591] (??:0)
[12] /usr/bin/godot4() [0xdc08a1] (??:0)
[13] /usr/lib/libc.so.6(+0x29290) [0x7f6655029290] (??:0)
[14] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f665502934a] (??:0)
[15] /usr/bin/godot4() [0xddbace] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Video of the editor crashing:

https://user-images.githubusercontent.com/47903526/185543065-feea8a8e-3c4d-46fe-8788-872c09e4f30b.mp4

### Minimal reproduction project

In the project there's a small piece of code which does crash when the project is ran.
```gdscript
extends Node2D

func _ready() -> void:
	$RichTextLabel.set("theme_override_constants/line_separation", -1)
```
[RichTextLabel crash.zip](https://github.com/godotengine/godot/files/9379170/RichTextLabel.crash.zip)

**Comment by timothyqiu** [comment] 2022-08-19 08:35
Duplicate of #64194

**Closed by timothyqiu** 2022-08-19 08:35 UTC
