### ISSUE TITLE
Tooltip clips window edge

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#40687] opened 2020-07-25 01:56 UTC
**Godot version:** 3.2.2 stable

**OS/device including version:** Linux Mint 20, kernel 5.3.0-62-generic, i3wm

Gles3

**Issue description:**

Tooltip clips the window edge, being impossible to read.

![tooltip](https://user-images.githubusercontent.com/6402237/88446505-c0e86900-ce00-11ea-8395-66431f643aee.gif)

**Comment by volzhs** [comment] 2020-10-13 10:38
duplicate of #37191

**Closed** 2020-10-13 10:42 UTC
Labels: bug, topic:gui
