### ISSUE TITLE
particles2d is busted in latest builds

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#10762] opened 2017-08-29 17:39 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.a2027cf

The particles don't move at all no matter the initial velocity. Check example project

[godot-dbg.zip](https://github.com/godotengine/godot/files/1261149/godot-dbg.zip)

**Comment by hpvb** [comment] 2017-08-29 22:00
I think this is due to the shader parser being broken at the moment. I'm looking at it in #10687

**Comment by akien-mga** [comment] 2017-08-31 12:17
Duplicate of #10687.

**Comment by akien-mga** [comment] 2017-08-31 12:18
At least I assume so, please reopen if that's not fixed once the problematic PR has been reverted.

**Closed by akien-mga** 2017-08-31 12:17 UTC
Labels: bug, topic:core
