### ISSUE TITLE
Godot 3.2.1 official crashes ARCH Linux to power off state

### ISSUE THREAD

**Issue by Zappo-II** [godotengine/godot#39672] opened 2020-06-19 10:05 UTC
**Godot version:**

```
[un@asus-ux31e ~]$ godot --version
3.2.1.stable.official
[un@asus-ux31e ~]$ 
```

**OS/device including version:**

```
[un@asus-ux31e ~]$ uname -a
Linux asus-ux31e 5.7.3-arch1-1 #1 SMP PREEMPT Wed, 17 Jun 2020 19:42:12 +0000 x86_64 GNU/Linux
[un@asus-ux31e ~]$ lspci -v
...
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 1427
	Flags: bus master, fast devsel, latency 0, IRQ 36
	Memory at ddc00000 (64-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
...
```

**Issue description:**

Since some days, no matter what project I use, godot just crashes my ARCH Linux right down to power off state after various time periods which are unpredictable and more short than long...

At first I thought there was something wrong with my project but no matter which project I choose it just happens anyway...

I tried using LTS kernel but the same behaviour occurs...

Before I could work perfectly well with godot versions since 3.0 on this machine...

Since ARCH is a rolling release distro I can not spot the update since when this strange behaviour occurred...

Everything else is working fine on this particular machine.

**Steps to reproduce:**

* Start godot
* Open any project
* Do anything in the project

**Minimal reproduction project:**

* dodge_the_creeps

**Comment by Calinou** [comment] 2020-06-19 10:13
Duplicate of #18871.

**Closed by Calinou** 2020-06-19 10:13 UTC
