### ISSUE TITLE
Camera position shifts when linking a child scene to a parent.

### ISSUE THREAD

**Issue by dynamite-ready** [godotengine/godot#15180] opened 2017-12-29 23:23 UTC
I'm using the 3.0 beta, on Window 8, on a Nvidia GTX 960m.

I have a main scene, and have linked 2 scenes to it. The main scene has one camera (3D), and is  presently the only camera in the entire project. 

On some random occasions, the camera appears to shift position when I run the main scene (i.e. the perspective will change), until I select and edit one of the linked scenes, and then go back to edit the main scene.

After doing so, the scene's camera will then be positioned as normal. 
I seriously doubt this can be a user error bug, but I'm open to correction.

**Comment by Dillybob1992** [comment] 2017-12-30 02:15
Hi there, can you supply a example project as well? ty

**Comment by Heathal** [comment] 2017-12-30 20:18
I have also been experiencing issues with this.  The camera in my main scene will sometimes appear zoomed in until I edit my linked scene, or until I close and reopen my main scene.  I’m on Beta 3.0 ver 2, Windows 10, with an Intel HD Graphics onboard card.

**Comment by dynamite-ready** [comment] 2017-12-31 15:42
Yes. That sounds like the same bug. I'll try to put together a small example, but it's difficult to find time at the moment. Seems like it's not too hard to reproduce though.

**Comment by akien-mga** [comment] 2018-01-05 10:16
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by dynamite-ready** [comment] 2018-01-05 15:14
I'd agree it's not a critical bug, but I have also noticed it on OSX.
Regardless of status, I'll aim to create an example at some point, or at least screenshot what I'm seeing.

**Comment by reduz** [comment] 2018-09-06 16:15
I could not reproduce, so any example project will be appreciated. Otherwise, this will be closed.

**Comment by akien-mga** [comment] 2019-01-19 13:52
Closing as per the above.

If you can still reproduce this issue in the current master branch / 3.1, please attach a project that helps reproduce it.

**Closed by akien-mga** 2019-01-19 13:52 UTC
Labels: bug, topic:editor
