### ISSUE TITLE
Godot 4 editor preventing modern standby sleep on Windows

### ISSUE THREAD

**Issue by HunterAhlquist** [godotengine/godot#81706] opened 2023-09-15 19:55 UTC
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11 22H2, Modern Standby enabled laptop (in my case Microsoft Surface Laptop Studio w/NVIDIA GPU)

### Issue description

It seems that Godot is always keeping an audio stream active even while idle in the editor, preventing sleep. Found out because my laptop died in my backpack. 
Here's the offending request that goes away when I close the editor:
```
[DRIVER] Realtek High Definition Audio(SST) (INTELAUDIO\FUNC_01&VEN_10EC&DEV_0274&SUBSYS_10EC121C&REV_1000\5&1543d6b8&0&0001)
An audio stream is currently in use.
```

### Steps to reproduce

1. Use `powercfg /requests` while GD4 is closed to see normal functioning. No media should be running in the background
2. Open a GD4 project
3. Use `powercfg /requests` again and a similar request should appear depending on your audio setup:
```
[DRIVER] Realtek High Definition Audio(SST) (INTELAUDIO\FUNC_01&VEN_10EC&DEV_0274&SUBSYS_10EC121C&REV_1000\5&1543d6b8&0&0001)
An audio stream is currently in use.
```
This request will prevent sleep on a Windows laptop with modern standby even when idle and minimized. Applications shouldn't keep an open power request when no media is playing.

### Minimal reproduction project

Any new blank project (tested with GD4) should produce this issue.

**Comment by AThousandShips** [comment] 2023-09-15 19:58
Duplicate of https://github.com/godotengine/godot/issues/28039

**Closed by AThousandShips** 2023-09-15 19:58 UTC
