### ISSUE TITLE
CSG: add/substract operation problem

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#38001] opened 2020-04-19 07:54 UTC
**Godot version:** Godot_v3.2.1-stable_win64 (build 10.03.2020)

**OS/device including version:** Windows 10 x64

**Issue description:**
CSG operations UNION and SUBSTRACTION results in unexpected artifacts when the CSGShapes edges aligned 

<a href="https://ibb.co/D9kvLmr"><img src="https://i.ibb.co/D9kvLmr/Csg-Operation-Issue.png" alt="Csg-Operation-Issue" border="0"></a>

**Steps to reproduce:**
Added an example project to show the problem

**Minimal reproduction project:**
<a href="https://drive.google.com/file/d/1xm6WZc4ZUa7tJMFlbZ9vSBsllHSF6qqL/view?usp=sharing">CsgTest.zip</a>

**Comment by Calinou** [comment] 2020-04-19 09:22
Duplicate of #21125.

**Comment by madmiraal** [comment] 2020-08-11 15:10
In response to this [comment](https://github.com/godotengine/godot/pull/38011#issuecomment-671981124).

@MikeSchulze I've looked at the project provided and I don't see any issues in 3.2.2.stable.

If you're referring to the the first shape been drawn over the second shape, when the faces are aligned, this is by design. One shape has to be dominant, and when faces are perfectly aligned the second shape is considered inside. If this is not desired, simply make the second shape slightly bigger.

If you're referring to something else, please be more specific.

**Comment by MikeSchulze** [comment] 2020-08-11 15:37
hi @madmiraal at first thanks for explaining.
The example project contains the current and the expected variant.
When two shapes perfectly alignedand and i substract from,  so my expection is all overlapping shapes are substracted. (removed)
"One shape has to be dominant, and when faces are perfectly aligned the second shape is considered inside" 
For addition yes, but when i substract no dominat face exists because is fully subsracted.

And if you look at TestD example the result has partial removed faces

**Comment by madmiraal** [comment] 2020-08-11 16:17
@MikeSchulze Thanks for the clarification.

Test D definitely shows an issue; so reopening this issue for that.

Regarding the ordering of the shapes, thinking about it, you may be right, it may make more sense to reverse the logic i.e. put the second shape outside the first if the faces are aligned; in all cases, not just subtraction.

**Comment by MikeSchulze** [comment] 2020-08-11 17:13
@madmiraal thanks for supporting.

**Closed** 2020-08-13 08:16 UTC
Labels: bug, topic:core

**Comment by MikeSchulze** [comment] 2020-08-14 13:33
thx for fast fixing
