### ISSUE TITLE
Editor Scene Previews Incorrect

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#57321] opened 2022-01-27 18:29 UTC
### Godot version

 3.4.2.stable

### System information

MacOS Monetary 12.1, GLES3, Apple M1

### Issue description

The scene previews shown on hover or in the file viewer are almost never correct.

### Example 1:

Editor Tab Hover Preview
![image](https://user-images.githubusercontent.com/28269330/151420130-15d1ea5e-c886-4149-8681-80838160b2de.png)
Open a File pop up
![image](https://user-images.githubusercontent.com/28269330/151420295-f3d57dc1-fc36-46e0-94e2-ee81813061c3.png)
Actual Scene
![image](https://user-images.githubusercontent.com/28269330/151420179-0d302e93-1af1-4324-9461-2cdf16dee52b.png)

The scene being previewed incorrectly is open in the list, but its preview is also incorrect.

### Example 2:

4 Scenes incorrectly showing a preview for another which is no longer even open.
![image](https://user-images.githubusercontent.com/28269330/151420561-5380b088-8b72-49af-8ff9-c1eca4bf6db2.png)
![image](https://user-images.githubusercontent.com/28269330/151420596-7b5c20af-dd2d-4662-9b49-31f1aebeb819.png)
![image](https://user-images.githubusercontent.com/28269330/151420612-4235b4a1-c25d-4395-b726-9d8aec82255f.png)
![image](https://user-images.githubusercontent.com/28269330/151420636-4c3cb958-8d1b-453f-8f4c-e4e010b01d35.png)
(AttackMenu is _not_ the scene being shown.)

Almost every single one of my scenes does this, the ones that work correctly are the exception instead of the rule. Clicking on the scene does not fix the picture, nor does saving.

### Steps to reproduce

As far as I can tell it happens on any project that has more than a few scenes. Estimation would be 12, but I can't manage to nail down the exact specific number.

**Comment by Calinou** [comment] 2022-01-27 19:11
Related to https://github.com/godotengine/godot/issues/47267.

I think the best way to fix this would be to add a node dedicated to act as a "preview camera" for 2D and 3D scene previews.

**Comment by Deozaan** [comment] 2023-05-11 05:50
I think this may be a duplicate of #33808

**Comment by Calinou** [comment] 2023-05-11 06:31
- Duplicate of https://github.com/godotengine/godot/issues/33808.

**Closed by Calinou** 2023-05-11 06:31 UTC
Labels: bug, topic:editor
