### ISSUE TITLE
Crash during RpcId

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#51697] opened 2021-08-15 17:06 UTC
### Godot version

3.4.beta3.mono

### System information

Debian 10

### Issue description

I use rpcid calls almost everywhere(4 projects connected together).
But when I try to send this resource something weird happen:
```
public class UserInfo : Resource
    {
        public int userInfoID;
        public string userName;
        public string faction;
        public int highestLevel;
        public int currentLevel;
        public int gold;
        public int gem;
    }
```
I did few tests and if I use a reduced version with just one variable like:

```
public class UserInfo : Resource
    {
        public int userInfoID;
}
```

it work properly.
 When I add more variables in class i begin to receive from the other side of rpcid weird values.
If I use the complete class the destination of the rpc crash.

### Steps to reproduce

I do a simple call like:
```
    UserInfo userInfo = new UserInfo
            {
                userInfoID = 1,
                currentLevel = 0,
                gem = 0,
                gold = 0,
                highestLevel = 25,
                faction = "red",
                userName = "name"
            };
RpcId(playerID, "FetchUserInfo", userInfo);`
```

and in the  other side something simple too:

```
 [Remote]
        public void FetchUserInfo(UserInfo userInfo)
        {
            Log.Print(Log.DEBUG, userInfo.userName);
            // ,
            // " lev:",
            // userInfo.currentLevel,
            // " faction:",
            // userInfo.faction,
            // " gem:",
            // userInfo.gem,
            // " gold:" ,
            // userInfo.gold,
            // " caplevel:",
            // userInfo.highestLevel,
            // " name",
            // userInfo.userName);
        }
```

### Minimal reproduction project

na

**Comment by Calinou** [comment] 2022-04-06 22:48
@git2013vb Can you (or anyone else) still reproduce this bug in [Godot 3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by git2013vb** [comment] 2022-04-08 07:31
@Calinou Thank you for your reply. Sadly I was forced to hold my projects due this and other very old bugs that put together didn't give me the opportunity to use this game engine for now. Waiting so long is not helping to keep going in my projects using this GE. I was hoping with all donations your team got during these years your team was able to fix some of bugs that I opened. But this is not the case apparently. So, after years of contribution to Godot  I'm forced to studying another game engine. I hope your team will be able to give me the opportunity to come back. Thank you very much.

**Comment by QbieShay** [comment] 2022-04-08 16:55
Fixing bugs it's really really difficult without a minimal reproduction project, which is why we ask people to include one in their issues: narrowing down the exact cause of the bug will make it way more likely for people to be able to fix it.

**Comment by git2013vb** [comment] 2022-04-08 17:56
> Fixing bugs it's really really difficult without a minimal reproduction project, which is why we ask people to include one in their issues: narrowing down the exact cause of the bug will make it way more likely for people to be able to fix it.

If I take the time test the software , make a minimal project, post everything here and answer questions from people who try in any way possible to close the issue with less effort possible (happen), after that I still need to wait YEARS for the bug be fixed you can understand how I feel. 

If I have to do it - that is reasonable of course - I expect to have the fix ready in a reasonable period. How much is a "reasonable period"? If you ask me is from 15 working days to at max 2 months. 

Not 1/2/3/4 years for sure :))

So don't ask to have a minimal project for this or any and other issues of mine.  As I stated before, I'm busy with another game engine. Where I have to port everything I made in Godot in another language. If have someone who is passionate to find bugs and to fix them I'm sure they will not have problems to fix 90% of all issue opened in GH without having a minimal project. If he can't means there is something wrong with Godot source code.

Thank you.

**Comment by Calinou** [comment] 2022-04-08 18:20
Closing, as nobody has been able to reproduce this issue since it was opened. Since OP is not going to provide a minimal reproduction project, there's no real point in keeping the issue open.

> How you (as team) invest the donations? Or how you define priorities in your project? The result, in my side, is this one.

This is detailed on the website's [Governance](https://godotengine.org/governance) page. Remember that Godot is provided with [no warranty](https://godotengine.org/license) whatsoever, even if you make donations.

**Closed by Calinou** 2022-04-08 18:20 UTC
Labels: bug, topic:network, topic:dotnet, crash
