### ISSUE TITLE
Project Open fails on recompiled Godot and plugged Android device

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#25960] opened 2019-02-16 23:09 UTC
x11
f6fcbcfe9eb09af63b545865d7341190519ac63e

Editor hangs on "Project Open" when Godot was recompiled while having a plugged Android device.

Workaround: Unplug the device
Maybe it is something simple, otherwise the workaround is fine too.

```
Thread 1 "godot.x11.tools" received signal SIGINT, Interrupt.
__lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: file or folder not found.
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff6673098 in __GI___pthread_mutex_lock (mutex=0x7391ab0)
    at ../nptl/pthread_mutex_lock.c:113
#2  0x0000000001b27116 in MutexPosix::lock (this=0x7391aa0)
    at drivers/unix/mutex_posix.cpp:39
#3  0x000000000221da95 in EditorExportPlatformAndroid::get_device_count (
    this=0x684c370) at platform/android/export/export.cpp:1211
#4  0x0000000001cfdf57 in EditorRunNative::_notification (this=0x81b0f20, 
    p_what=17) at editor/editor_run_native.cpp:77
#5  0x0000000001cff32a in EditorRunNative::_notificationv (this=0x81b0f20, 
    p_notification=17, p_reversed=false) at editor/editor_run_native.h:39
#6  0x00000000031ba53e in Object::notification (this=0x81b0f20, 
    p_notification=17, p_reversed=false) at core/object.cpp:955
#7  0x00000000024b8973 in SceneTree::_notify_group_pause (this=0x60192e0, 
    p_group=..., p_notification=17) at scene/main/scene_tree.cpp:969
#8  0x00000000024b65a8 in SceneTree::idle (this=0x60192e0, p_time=0.121509552)
    at scene/main/scene_tree.cpp:518
#9  0x00000000011a01f9 in Main::iteration () at main/main.cpp:1876
#10 0x0000000001d9689e in ProgressDialog::task_step (this=0x762f990, 
    p_task=..., p_state=..., p_step=0, p_force_redraw=true)
    at editor/progress_dialog.cpp:223
#11 0x0000000001c4afe9 in EditorNode::progress_task_step (p_task=..., 
    p_state=..., p_step=0, p_force_refresh=true) at editor/editor_node.cpp:3286
```

**Comment by akien-mga** [comment] 2020-01-13 14:35
Is this still reproducible in the current master branch?

If so, could you give slightly more detailed steps to reproduce?

**Comment by KoBeWi** [comment] 2020-12-06 00:35
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-06 00:35 UTC
Labels: bug, platform:android, topic:editor
