### ISSUE TITLE
`Parsing the config failed` warning popup when creating a plugin with `Activate now` enabled

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#46560] opened 2021-03-01 14:50 UTC
**Godot version:**

3.2.4rc3

**OS/device including version:**

Linux

**Issue description:**

After creating a plugin for example:
![test activate plugin error](https://user-images.githubusercontent.com/16458555/109512141-97de3400-7ac5-11eb-9dbb-fbbcd7930d81.png)

I get this popup every time:
![parsing the config failed](https://user-images.githubusercontent.com/16458555/109511106-8c3e3d80-7ac4-11eb-8d17-90d2723f6d49.png)

- No errors in Output
- The plugin seems to be created correctly but just not activated
- If `Activate now?` checkbox is off, the popup doesn't appear.
- I haven't seen this popup in earlier versions.

**Steps to reproduce:**
1. Create a new Godot project
2. Create a plugin (`Project` - `Project Settings` - `Plugins` - `Create`)
Specify:
- plugin name
- subfolder
- script name
Make sure `Activate now?` checkbox is on
Then press `Create`
The popup with error (see above) should appear

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2021-03-01 15:56
CC @Shatur95 (didn't check if it's actually a regression from your changes yet though).

**Comment by Shatur95** [comment] 2021-03-01 16:56
@akien-mga, The issue was fixed by #46389 (3.2).

But the issue will persist in master because it do not have backward-compatible check. Should I just return full plugin path from here?
https://github.com/godotengine/godot/blob/09b5d6886f8ef736ca83e3ec965f50a2cb7152f2/editor/plugin_config_dialog.cpp#L115

**Comment by me2beats** [comment] 2021-03-09 12:28
It seems it is fixed in `rc4`, I don't see the popup anymore

**Closed** 2021-03-09 12:54 UTC
Labels: bug, regression, topic:editor, topic:plugin
