### ISSUE TITLE
GDScript allows name a variable the same as a function parameter

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7588] opened 2017-01-20 16:30 UTC
**Operating system or device - Godot version:**
Godot 2.1 (probably also affects 3.0)

**Issue description:**
A variable inside a function can be named like a parameter for that function with no error. I expect that in an inner scope, but not at the main scope of the function.

**Steps to reproduce:**
This script:
```
func function(param):
    var param # This should produce an error
    if true:
        var param # Here I think it's OK to allow it
                  # since you are shadowing the parameter
                  # inside an inner scope at your own risk
```

**Comment by bojidar-bg** [comment] 2017-01-20 18:14
Dupe of #3730.

**Closed by bojidar-bg** 2017-01-20 18:14 UTC
