### ISSUE TITLE
Video  player audio issues when audio mix_rate is different than 44100 Hz

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12941] opened 2017-11-15 04:13 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/8e8240450edc48f4fb379e593a4ef7f54ab656b7
Windows 10 WASAPI audio driver (48000 Hz)

**Issue description:**

The audio when playing any video (webm vp8 or vp9 or ogv) doesn't play smoothly. It's synced as far as I can tell but it cut offs constantly. It only seems to happen when the audio mix_rate is different than 44100 Hz 

A webm video: https://streamable.com/9nkc6
A ogv video: https://streamable.com/eodlf

With the audio driver set to `RtAudio-DirectSound` the issue isn't present because it defaults to 44100 Hz:

Sintel trailer OGV 720p with WASAPI: https://streamable.com/x9pdx
Sintel trailer OGV 720p with RtAudio-DirectSound: https://streamable.com/2ranp

**Steps to reproduce:**
1. Set the audio mix rate to something that's not 44100 Hz
2. Add a video
3. Play it

**Comment by mrcdk** [comment] 2017-11-15 04:15
Pinging @hi-ogawa

**Comment by akien-mga** [comment] 2018-01-05 14:58
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by mrcdk** [comment] 2018-01-05 22:53
It makes using a video with audio impossible to use. Not sure if people or how many people are using it. I'm guessing people aren't really using videos with audio because there's not been any other similar issues so I'd say it's not critical for 3.0 release.

**Comment by akien-mga** [comment] 2018-01-05 22:58
I've played two WebMs with audio today and it was fine (Big Buck Bunny's trailer and Elephant Dream's first 2 min). Not a tremendous quality but that's WebM, not Theora.

Anyway, it's "OK" if video with audio is buggy in 3.0 if a fix comes in a later 3.0.1. If you start developing a game in 3.0, there will likely be a couple 3.0.x or even 3.1 before the project is ready for production and the bogus video playback should be something people can live with for a while (hence not "critical" to get 3.0 out of the door IMO).

**Comment by akien-mga** [comment] 2018-01-05 23:09
I've tried the Sintel trailer in OGV 720p, there was a little bit of stuttering at first but then it played fine: https://download.blender.org/durian/trailer/sintel_trailer-720p.ogv

Same with Big Buck Bunny 480p (note: had to rename to ogv otherwise Godot tries to import it as an AudioStream), it plays fine locally. I had one moment with stuttering at the start, then it was smooth.

Testing on Mageia 6 x86_64 with a debug build at 061db1ca.

**Comment by mrcdk** [comment] 2018-01-05 23:19
I think I've found the issue, it's the audio driver godot uses. Using Windows 10 with a release_debug build at https://github.com/godotengine/godot/commit/8e8240450edc48f4fb379e593a4ef7f54ab656b7

Sintel trailer OGV 720p with WASAPI: https://streamable.com/x9pdx
Sintel trailer OGV 720p with RtAudio-DirectSound: https://streamable.com/2ranp

I'll update the issue.

**Comment by akien-mga** [comment] 2018-01-05 23:23
Ping @marcelofg55, it seems to be specific to the WASAPI driver.

**Comment by marcelofg55** [comment] 2018-01-06 00:25
@akien-mga I'll check it out it this weekend.

**Comment by marcelofg55** [comment] 2018-01-06 16:28
I've just tested it with the project from https://github.com/hi-ogawa/godot-examples/tree/master/video_player_test and it played fine on my Windows 10 using the WASAPI driver. I've tried to test it with the Sintel trailer but godot is complaining about it: `No loader found for resource: res://sintel.ogv`, maybe I'm missing something here? I've compiled with defaults `scons p=windows target=release_debug`

**Comment by mrcdk** [comment] 2018-01-06 19:04
Uhm, those are the same files I tested too, the sound is choppy with WASAPI but fine with RtAudio-DirectSound. Maybe it has nothing to do with the driver but it's a latency issue? AFAIK WASAPI has more latency than rtaudio...

I get this running the test project with `Debug/Verbose stdout` enabled:
```
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1056 calculated latency: 22ms
```
and for rtaudio
```
audio buffer frames: 512 calculated latency: 11ms
```

For your other question, I compile it with the same command so I don't know why you can't load `ogv` 😕

**Comment by marcelofg55** [comment] 2018-01-06 19:52
I've managed to reproduce the issue using the HDMI audio from my monitor (instead of using my audio card). I'm trying to find the problem now.

**Comment by marcelofg55** [comment] 2018-01-06 21:50
I kept digging about this and I could reproduce this on OSX too if I set `audio/mix_rate` to 48000, with 44100 it works fine. On windows with WASAPI the same happens, if my device is set to 44100 movie audio works fine, with 48000 audio starts cracking.
So this is not a WASAPI driver bug, the movie audio code from godot is bugged when a mix_rate other than 44100 is set.

**Comment by mrcdk** [comment] 2018-01-06 21:57
Yep, can confirm. Updated issue title and text.

**Comment by mrcdk** [comment] 2018-01-06 22:09
I think both vorbis and opus audio modules should extend `AudioStreamPlaybackResampled` which takes care of resampling the samples to the `AudioServer` sample rate

**Closed** 2018-01-07 16:06 UTC
Labels: bug, platform:windows, topic:audio
