### ISSUE TITLE
Erasing tile in tilemap gives an output "error"

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23556] opened 2018-11-06 12:46 UTC
**Godot version:**
calinou.3cf3c41

**OS/device including version:**
OSX Mojave

**Issue description:**
<img width="882" alt="captura de ecra 2018-11-06 as 12 42 23" src="https://user-images.githubusercontent.com/10358443/48065189-f0d18200-e1c1-11e8-97e4-035b077eaaed.png">

When I erase an autotile from the tilemap I get the following output error message:

<img width="819" alt="captura de ecra 2018-11-06 as 12 42 32" src="https://user-images.githubusercontent.com/10358443/48065211-ff1f9e00-e1c1-11e8-8b0a-d634837836e8.png">

**Comment by groud** [comment] 2018-11-06 12:59
I'd say this is a duplicate of #21549

**Closed** 2018-11-10 20:53 UTC
Labels: bug, topic:editor
