### ISSUE TITLE
The Godot main menu appears instead of the game when trying to playtest

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#13832] opened 2017-12-02 13:17 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 Beta 1- Windows

**Issue description:**
When attempting to playtest, sometimes Godot's main menu appears instead of the actual game as if I'm launching another instance of the engine (except it's still "linked" to the editor). So if I press Stop or F7, the main menu closes also.
Pressing reload or running for a second time after this happens will usually run the game properly. There was one instance where this happened twice in a row.

**Steps to reproduce:**
Not sure as it seems slightly random. But it happens almost consistently if you run the game after you've made a change (to code, for example).

[Image](https://i.imgur.com/YAdIolc.png)

**Comment by Sslaxx** [comment] 2017-12-02 13:36
Duplicate of #11391?

**Comment by vybr** [comment] 2017-12-02 13:55
Oh, my bad. I didn't see that when I was searching for it.

**Closed** 2017-12-02 13:55 UTC
