### ISSUE TITLE
Couldn't build summator module from docs

### ISSUE THREAD

**Issue by Athomield** [godotengine/godot#15659] opened 2018-01-13 11:07 UTC
**Godot version:**

Todays build (1/13/2018)

**OS/device including version:**

Win 10 MSVC 2017 compiler

**Issue description:**

I can't build the module from the summator tutorial from the docs.

Note : I don't have mono installed.

this is the (long) error that I get 
```
[Initial build] Compiling ==> modules\summator\register_types.c
register_types.c
\godot\godot-master\core\os/mutex.h(45): error C2061: syntax error: identifier 'Mutex'
\godot\godot-master\core\os/mutex.h(45): error C2059: syntax error: ';'
\godot\godot-master\core\os/mutex.h(45): error C2449: found '{' at file scope (missing function header?)
\godot\godot-master\core\os/mutex.h(57): error C2059: syntax error: '}'
\godot\godot-master\core\typedefs.h(69): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\typedefs.h(69): error C2059: syntax error: '<'
\godot\godot-master\core\error_macros.h(58): error C2146: syntax error: missing ')' before identifier 'p_type'
\godot\godot-master\core\error_macros.h(58): error C2081: 'ErrorHandlerType': name in formal parameter list illegal
\godot\godot-master\core\error_macros.h(58): error C2061: syntax error: identifier 'p_type'
\godot\godot-master\core\error_macros.h(58): error C2059: syntax error: ';'
\godot\godot-master\core\error_macros.h(58): error C2059: syntax error: ')'
\godot\godot-master\core\error_macros.h(64): error C2061: syntax error: identifier 'ErrorHandlerFunc'
\godot\godot-master\core\error_macros.h(67): error C2143: syntax error: missing '{' before '*'
\godot\godot-master\core\error_macros.h(70): error C2065: 'errfunc': undeclared identifier
\godot\godot-master\core\error_macros.h(74): error C2059: syntax error: '}'
\godot\godot-master\core\error_macros.h(76): error C2143: syntax error: missing ')' before '*'
\godot\godot-master\core\error_macros.h(76): error C2143: syntax error: missing '{' before '*'
\godot\godot-master\core\error_macros.h(76): error C2059: syntax error: ')'
\godot\godot-master\core\error_macros.h(77): error C2143: syntax error: missing ')' before '*'
\godot\godot-master\core\error_macros.h(77): error C2143: syntax error: missing '{' before '*'
\godot\godot-master\core\error_macros.h(77): error C2059: syntax error: ')'
\godot\godot-master\core\error_macros.h(79): error C2146: syntax error: missing ')' before identifier 'p_type'
\godot\godot-master\core\error_macros.h(79): error C2081: 'ErrorHandlerType': name in formal parameter list illegal
\godot\godot-master\core\error_macros.h(79): error C2061: syntax error: identifier 'p_type'
\godot\godot-master\core\error_macros.h(79): error C2059: syntax error: ';'
\godot\godot-master\core\error_macros.h(79): error C2513: ' ': no variable declared before '='
\godot\godot-master\core\error_macros.h(79): error C2059: syntax error: ')'
\godot\godot-master\core\error_macros.h(80): error C2146: syntax error: missing ')' before identifier 'fatal'
\godot\godot-master\core\error_macros.h(80): error C2081: 'bool': name in formal parameter list illegal
\godot\godot-master\core\error_macros.h(80): error C2061: syntax error: identifier 'fatal'
\godot\godot-master\core\error_macros.h(80): error C2059: syntax error: ';'
\godot\godot-master\core\error_macros.h(80): error C2513: ' ': no variable declared before '='
\godot\godot-master\core\error_macros.h(80): error C2059: syntax error: ')'
\godot\godot-master\core\error_macros.h(80): error C2065: 'false': undeclared identifier
\godot\godot-master\core\error_macros.h(91): error C2061: syntax error: identifier '_err_error_exists'
\godot\godot-master\core\error_macros.h(91): error C2059: syntax error: ';'
\godot\godot-master\core\typedefs.h(133): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\typedefs.h(133): error C2059: syntax error: '<'
\godot\godot-master\core\typedefs.h(200): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\typedefs.h(200): error C2059: syntax error: '<'
\godot\godot-master\core\typedefs.h(266): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\typedefs.h(266): error C2059: syntax error: '<'
\godot\godot-master\core\typedefs.h(277): error C2061: syntax error: identifier '_GlobalLock'
\godot\godot-master\core\typedefs.h(278): error C2059: syntax error: '~'
\godot\godot-master\core\typedefs.h(279): error C2059: syntax error: '}'
\godot\godot-master\core\safe_refcount.h(163): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(163): error C2371: 'atomic_conditional_increment': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(156): note: see declaration of 'atomic_conditional_increment'
\godot\godot-master\core\safe_refcount.h(164): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(164): error C2371: 'atomic_decrement': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(157): note: see declaration of 'atomic_decrement'
\godot\godot-master\core\safe_refcount.h(165): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(165): error C2371: 'atomic_increment': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(158): note: see declaration of 'atomic_increment'
\godot\godot-master\core\safe_refcount.h(166): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(166): warning C4028: formal parameter 2 different from declaration
\godot\godot-master\core\safe_refcount.h(166): error C2371: 'atomic_sub': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(159): note: see declaration of 'atomic_sub'
\godot\godot-master\core\safe_refcount.h(167): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(167): warning C4028: formal parameter 2 different from declaration
\godot\godot-master\core\safe_refcount.h(167): error C2371: 'atomic_add': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(160): note: see declaration of 'atomic_add'
\godot\godot-master\core\safe_refcount.h(168): warning C4028: formal parameter 1 different from declaration
\godot\godot-master\core\safe_refcount.h(168): warning C4028: formal parameter 2 different from declaration
\godot\godot-master\core\safe_refcount.h(168): error C2371: 'atomic_exchange_if_greater': redefinition; different basic types
\godot\godot-master\core\safe_refcount.h(161): note: see declaration of 'atomic_exchange_if_greater'
\godot\godot-master\core\safe_refcount.h(179): error C2061: syntax error: identifier 'public'
\godot\godot-master\core\safe_refcount.h(189): error C2065: 'count': undeclared identifier
\godot\godot-master\core\safe_refcount.h(189): warning C4133: 'function': incompatible types - from 'int *' to 'uint64_t *'
\godot\godot-master\core\safe_refcount.h(192): error C2061: syntax error: identifier 'unref'
\godot\godot-master\core\safe_refcount.h(192): error C2059: syntax error: ';'
\godot\godot-master\core\safe_refcount.h(192): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\safe_refcount.h(201): error C2143: syntax error: missing '{' before '<cv-qualifer>'
\godot\godot-master\core\safe_refcount.h(201): error C2059: syntax error: '{'
\godot\godot-master\core\safe_refcount.h(206): error C2143: syntax error: missing ')' before '='
\godot\godot-master\core\safe_refcount.h(206): error C2072: 'init': initialization of a function
\godot\godot-master\core\safe_refcount.h(206): error C2059: syntax error: ')'
\godot\godot-master\core\safe_refcount.h(206): error C2143: syntax error: missing ';' before '{'
\godot\godot-master\core\safe_refcount.h(206): error C2449: found '{' at file scope (missing function header?)
\godot\godot-master\core\safe_refcount.h(209): error C2059: syntax error: '}'
\godot\godot-master\core\os/memory.h(45): error C2061: syntax error: identifier 'Memory'
\godot\godot-master\core\os/memory.h(45): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(45): error C2449: found '{' at file scope (missing function header?)
\godot\godot-master\core\os/memory.h(63): error C2059: syntax error: '}'
\godot\godot-master\core\os/memory.h(71): error C2061: syntax error: identifier 'new'
\godot\godot-master\core\os/memory.h(71): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(71): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(72): error C2061: syntax error: identifier 'new'
\godot\godot-master\core\os/memory.h(72): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(72): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(74): error C2061: syntax error: identifier 'new'
\godot\godot-master\core\os/memory.h(74): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(74): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(79): error C2061: syntax error: identifier 'delete'
\godot\godot-master\core\os/memory.h(79): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(79): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(80): error C2061: syntax error: identifier 'delete'
\godot\godot-master\core\os/memory.h(80): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(80): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(81): error C2061: syntax error: identifier 'delete'
\godot\godot-master\core\os/memory.h(81): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(81): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(88): error C2055: expected formal parameter list, not a type list
\godot\godot-master\core\os/memory.h(90): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\os/memory.h(90): error C2059: syntax error: '<'
\godot\godot-master\core\os/memory.h(99): error C2061: syntax error: identifier 'new'
\godot\godot-master\core\os/memory.h(99): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(99): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(109): error C2061: syntax error: identifier 'predelete_handler'
\godot\godot-master\core\os/memory.h(109): error C2059: syntax error: ';'
\godot\godot-master\core\os/memory.h(109): error C2059: syntax error: '<parameter-list>'
\godot\godot-master\core\os/memory.h(113): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\os/memory.h(113): error C2059: syntax error: '<'
\godot\godot-master\core\os/memory.h(122): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\os/memory.h(122): error C2059: syntax error: '<'
\godot\godot-master\core\os/memory.h(138): error C2143: syntax error: missing '{' before '<'
\godot\godot-master\core\os/memory.h(138): error C2059: syntax error: '<'
\godot\godot-master\core\os/memory.h(138): fatal error C1003: error count exceeds 100; stopping compilation
scons: *** [modules\summator\register_types.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment] 2018-01-13 11:24
Can you share your code?

**Comment by Noshyaar** [comment] 2018-01-13 12:01
Probably this http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html#creating-a-new-module

**Comment by Athomield** [comment] 2018-01-13 12:04
[summator.zip](https://github.com/godotengine/godot/files/1628297/summator.zip)
This is the summator module code, the godot code was from a branch I downloaded a couple of hours ago.

**Comment by vnen** [comment] 2018-01-13 16:29
I can build this fine if I rename `register_types.c` to `register_types.cpp` (and update SCsub accordingly). This should be a C++ file since it includes C++ headers. I wonder how it worked in the past if not by luck.

**Comment by vnen** [comment] 2018-01-13 16:31
Closing since this is not a bug.

**Closed by vnen** 2018-01-13 16:31 UTC
Labels: bug, platform:windows, topic:buildsystem

**Comment by Athomield** [comment] 2018-01-13 17:24
Oh so the documentation should be updated too I suppose. Anyway thanks.

**Comment by vnen** [comment] 2018-01-13 17:28
> Oh so the documentation should be updated too I suppose. Anyway thanks.

It's what I thought at first, but I checked and the documentation sample is already a C++ file.

**Comment by Athomield** [comment] 2018-01-13 17:30
My bad I had these files for over a month now, and when I checked the new docs I didn't notice this change.
