### ISSUE TITLE
Shortcuts disregard area focus

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#22429] opened 2018-09-25 17:15 UTC
**Steps to reproduce:**
Set Clone Down and Duplicate Node to the same shortcut (ex Ctrl-D). Open Script Editor. Select Node in Scene Tree. Scene Tree editor area has focus, indicated by a light area outline. Use the shortcut. Both the selected node, and the line with the cursor in the Script Editor (which doesn't have focus), are duplicated.

**What was expected**
Shortcuts working in the area that has focus (excluding ones that affect global areas, like the top bar - ex Play the Project shortcut).

**Comment by Zylann** [comment] 2018-09-25 17:37
That would be yet another to add to that list: https://github.com/godotengine/godot/issues/9069#issuecomment-398042162

**Comment by KoBeWi** [comment] 2020-06-19 13:28
Closing as duplicate of #36205, which has a linked PR

**Closed by KoBeWi** 2020-06-19 13:28 UTC
Labels: bug, topic:core, topic:editor, usability
