### ISSUE TITLE
Installing godot git plugin caused an error ( error loading extension )

### ISSUE THREAD

**Issue by vdqvdw** [godotengine/godot#84112] opened 2023-10-28 13:20 UTC
### Godot version

4.1.2.stable

### System information

Godot v4.1.2.stable - macOS 13.5.0 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

I want to use git as a version control.
So i installed Godot Git Plugin (4.0+).
It caused error. 

- error message popup
```
Error loading extension: res://addons/godot-git-plugin/git_plugin.gdextension
```

- error message in debugger console
```
Invalid URL scheme:  	https://.
  core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-git-plugin/git_plugin.gdextension
  Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

### Steps to reproduce

Install Godot Git Plugin (4.0+) in AssetLib
![image](https://github.com/godotengine/godot/assets/12380853/c5163dc3-2c48-4fe1-b50b-432df3c3ea89)

### Minimal reproduction project

Any new project with Compatibility Renderer like below image
![image](https://github.com/godotengine/godot/assets/12380853/31a9f51c-4b03-49ec-8cfb-61f316d5cd1d)

**Comment by AThousandShips** [comment] 2023-10-28 13:23
The version for 4.0 is not compatible with 4.1+ because GDExtension was rewritten, check [here](https://github.com/godotengine/godot-git-plugin/tree/master) to get an up to date version instead

**Comment by AThousandShips** [comment] 2023-10-28 13:28
Duplicate of https://github.com/godotengine/godot-git-plugin/issues/196

**Closed by AThousandShips** 2023-10-28 13:28 UTC

**Comment by vdqvdw** [comment] 2023-10-28 14:29
> The version for 4.0 is not compatible with 4.1+ because GDExtension was rewritten, check [here](https://github.com/godotengine/godot-git-plugin/tree/master) to get an up to date version instead
> 
> See the error message, it says what is wrong, there's no compatibility check file which is required (which shows it's for 4.0)
> 
> I'd say this belongs on the [dedicated page](https://github.com/godotengine/godot-git-plugin)

Thank you. I'll try.
