### ISSUE TITLE
Godot 4.0 alpha 8 Export Android Apk Crash

### ISSUE THREAD

**Issue by szp2076250** [godotengine/godot#61018] opened 2022-05-14 01:59 UTC
### Godot version

Godot Engine v4.0.alpha8.official.cc3ed63af - https://godotengine.org

### System information

Windows10

### Issue description

Godot Engine v4.0.alpha8.official.cc3ed63af - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1425561897808
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
Vulkan API 1.2.141 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1060 5GB

Editing project: D:/Game/Game (D:::Game::Game)

Godot Engine v4.0.alpha8.official.cc3ed63af - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2702842886160
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
Vulkan API 1.2.141 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1060 5GB

WARNING: FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:92)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8572)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8572)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8572)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8572)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8572)
ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2244)
ERROR: Condition "!material" is true.
   at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2466)
ERROR: 1 shaders of type BokehDofRasterShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:700)

Godot Engine v4.0.alpha8.official.cc3ed63af - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2677001725632
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
Vulkan API 1.2.141 - Using Vulkan Device #0: NVIDIA - GeForce GTX 1060 5GB

WARNING: FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:92)
ERROR: Transient parent has another exclusive child.
   at: (scene/main/window.cpp:441)
0 param: --xr_mode_regular
1 param: --use_immersive
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: lib/arm64-v8a/libgodot_android.so
ADDING: kotlin/annotation/annotation.kotlin_builtins
ADDING: kotlin/collections/collections.kotlin_builtins
ADDING: kotlin/coroutines/coroutines.kotlin_builtins
ADDING: kotlin/internal/internal.kotlin_builtins
ADDING: kotlin/kotlin.kotlin_builtins
ADDING: kotlin/ranges/ranges.kotlin_builtins
ADDING: kotlin/reflect/reflect.kotlin_builtins
ADDING: AndroidManifest.xml
ADDING: res/anim-v21/fragment_fast_out_extra_slow_in.xml
ADDING: res/anim/fragment_fast_out_extra_slow_in.xml
ADDING: res/animator/fragment_close_enter.xml
ADDING: res/animator/fragment_close_exit.xml
ADDING: res/animator/fragment_fade_enter.xml
ADDING: res/animator/fragment_fade_exit.xml
ADDING: res/animator/fragment_open_enter.xml
ADDING: res/animator/fragment_open_exit.xml
ADDING: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-nodpi-v4/splash.png
ADDING: res/drawable-nodpi-v4/splash_bg_color.png
ADDING: res/drawable-v21/notification_action_background.xml
ADDING: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable/notification_bg.xml
ADDING: res/drawable/notification_bg_low.xml
ADDING: res/drawable/notification_icon_background.xml
ADDING: res/drawable/notification_tile_bg.xml
ADDING: res/drawable/splash_drawable.xml
ADDING: res/layout-v16/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_action.xml
ADDING: res/layout-v21/notification_action_tombstone.xml
ADDING: res/layout-v21/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_template_icon_group.xml
ADDING: res/layout/custom_dialog.xml
ADDING: res/layout/downloading_expansion.xml
ADDING: res/layout/godot_app_layout.xml
ADDING: res/layout/notification_action.xml
ADDING: res/layout/notification_action_tombstone.xml
ADDING: res/layout/notification_template_icon_group.xml
ADDING: res/layout/notification_template_part_chronometer.xml
ADDING: res/layout/notification_template_part_time.xml
ADDING: res/layout/status_bar_ongoing_event_progress_bar.xml
ADDING: res/mipmap-anydpi-v26/icon.xml
ADDING: res/mipmap-hdpi-v4/icon.png
ADDING: res/mipmap-hdpi-v4/icon_background.png
ADDING: res/mipmap-hdpi-v4/icon_foreground.png
ADDING: res/mipmap-mdpi-v4/icon.png
ADDING: res/mipmap-mdpi-v4/icon_background.png
ADDING: res/mipmap-mdpi-v4/icon_foreground.png
ADDING: res/mipmap-xhdpi-v4/icon.png
ADDING: res/mipmap-xhdpi-v4/icon_background.png
ADDING: res/mipmap-xhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxhdpi-v4/icon.png
ADDING: res/mipmap-xxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxxhdpi-v4/icon.png
ADDING: res/mipmap-xxxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxxhdpi-v4/icon_foreground.png
ADDING: res/mipmap/icon.png
ADDING: res/mipmap/icon_background.png
ADDING: res/mipmap/icon_foreground.png
ADDING: resources.arsc

### Steps to reproduce

project -> export -> export project 

it will crash and console log stop at :
ADDING: resources.arsc

Anyone can help，thanks a lot.

**Comment by Calinou** [comment] 2022-05-14 18:40
Duplicate of https://github.com/godotengine/godot/issues/60404. This should be fixed by https://github.com/godotengine/godot/pull/60943, which hasn't landed in 4.0.alpha8 but will be in the next alpha/beta.

**Closed by Calinou** 2022-05-14 18:40 UTC
