### ISSUE TITLE
Editor freeze when clicking Skeleton node of a glTF scene with 500+ bones

### ISSUE THREAD

**Issue by lmomimi** [godotengine/godot#35652] opened 2020-01-28 07:30 UTC
**Godot version:**
3.2 rc 4

**OS/device including version:**
macos 10.15.2
*Issue description:**
[New Game Project.zip](https://github.com/godotengine/godot/files/4121086/New.Game.Project.zip)

**Steps to reproduce:**
open BAQIR-RIG.glb  click armature_baq node,editor freeze

**Minimal reproduction project:**

*Bugsquad edit (keywords for easier searching): select, selecting, crash*

**Comment by akien-mga** [comment] 2020-01-28 07:57
I can confirm the freeze on the `master` branch on Linux. It likely also happens in earlier versions, it's not a regression.

The attached project has a glTF file with a 514-bones skeleton, and generating the Inspector for all 514 bones is what is taking so much time, eventually exceeding the max MessageQueue size if using the default of 1024. If increased to 4096, it works for me after a temporary freeze of ~1 min, then shows the inspector:
![Screenshot_20200128_084101](https://user-images.githubusercontent.com/4701338/73244352-060d4480-41aa-11ea-9de9-0e3340e359cd.png)

This is similar to #29238, the Inspector should use paging to avoid creating controls for so many bones.

The deadlock would be fixed by #35653, though it's not a proper fix for this issue.

**Comment by fire** [comment] 2020-01-28 17:30
A proper fix would be switching to the tree based editor.

https://github.com/godotengine/godot/pull/33871

This missed the Feature Freeze in 2019 Summer.

**Comment by slapin** [comment] 2020-04-02 00:44
Yeah confirm this using scene imported from escn.

**Closed** 2020-05-27 09:04 UTC
Labels: bug, confirmed, topic:editor
