### ISSUE TITLE
Phantom Directional Light

### ISSUE THREAD

**Issue by 1SMOL** [godotengine/godot#65626] opened 2022-09-10 19:07 UTC
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Windows 11

### Issue description

If there is no directional light in any scene, godot for some reason continues to assume there is a directional light. This is especially annoying if you are using a panorama sky that is overcast, or night time, but there is still this phantom sun in the sky.

### Steps to reproduce

Just create a basic scene in godot with no directional light, and for added annoyance, make a new `WorldEnvironment` and use a panorama sky with an hdri.

**Comment by mrjustaguy** [comment] 2022-09-10 19:35
There's an Editor only directional sun by default, that you can toggle off.

**Comment by JohanAR** [comment] 2022-09-10 20:10
These 3 buttons control the editor preview light and environment

**Comment by Calinou** [comment] 2022-09-10 20:18
Closing, as this is not a bug, but the preview sun (and sky).

**Comment by 1SMOL** [comment] 2022-09-10 20:19
I'll be honest, it doesn't make sense to me to have a 'preview light' in the main editor. If you want a directional light, or light in general, then that should be left up to the artist/developer to spawn out the preferred light.

But for importing prompts, absolutely a preview light is perfect for that.

**Closed by Calinou** 2022-09-10 20:18 UTC

**Comment by JohanAR** [comment] 2022-09-10 20:24
All scenes won't have a light, e.g. player, enemies, items, and it would be difficult to edit them in the darkness.

**Comment by Calinou** [comment] 2022-09-10 20:27
See https://github.com/godotengine/godot-proposals/issues/1599 where the preview sun and sky system was discussed.

**Comment by 1SMOL** [comment] 2022-09-10 20:30
> All scenes won't have a light, e.g. player, enemies, items, and it would be difficult to edit them in the darkness.

Oh yep, still switching over from unity and keep forgetting some of the godot workflow. Scenes being the equivalent to unity's prefabs and all that fun stuff
