### ISSUE TITLE
Shader Globals of a type sampler disappear after reload

### ISSUE THREAD

**Issue by OlivierVanHoutte** [godotengine/godot#60805] opened 2022-05-05 19:44 UTC
### Godot version

4.0.alpha7

### System information

Windows 10, Vulcan

### Issue description

When reloading a project, my newly created shader global of one of the 4 sampler types disappears.
When checking the "project.godot" file, the shader global is defined and thus should still exists. 
I assume it doesn't get loaded correctly.

### Steps to reproduce

Open a new project.
In project settings, add a shader global with type sampler2D, sampler2DArray, sampler3D or samplerCube.
Save
Reload the project.
Go back to project settings to witness it missing.
Open the "project.godot" file in a text editor scroll down to find the shader globals

### Minimal reproduction project

Minimal project is an empty project.

**Comment by Calinou** [comment] 2022-05-05 23:04
As far as I know, sampler shader globals aren't supported due to hardware limitations.

**Comment by KoBeWi** [comment] 2022-05-13 22:42
Can't reproduce in alpha 8.

**Comment by Atraitus** [comment] 2023-07-24 15:03
This issue is still present in 4.2.dev1.  The sampler global uniform works perfectly after being created and functions as expected, but fails to load when the project is saved and then reopened.  Upon recreation in project settings and recompiling the shader, it once again functions as expected, but the cycle continues when the project is closed and it fails to reappear after reopening the project, causing the shader to not compile upon project open.

**Comment by OlivierVanHoutte** [comment] 2023-07-30 19:12
If you really need to, you can use `RenderingServer.global_shader_parameter_add()` and define it at runtime as a temporary workaround . 
Using samplers as global uniforms seems to work perfectly fine. It just doesn't get loaded correctly in the editor.

**Comment by Kiramin** [comment] 2023-08-02 17:20
If you call RenderingServer.global_shader_parameter_add() early enough (before the shader compilation) you avoid the errors (at least was working for me in the editor). I was doing this in _enter_tree() of a Global Variable @tool script that I put Project Settings->Autoload

**Comment by OlivierVanHoutte** [comment] 2023-08-06 12:57
Tried and tested, Works great, thx @Kiramin !!

**Comment by bitsawer** [comment] 2023-08-16 09:31
Missed this issue when making PR https://github.com/godotengine/godot/pull/80654, but looks like this issue was also fixed by it.

**Closed by bitsawer** 2023-08-16 09:31 UTC
Labels: bug, topic:rendering, topic:editor, confirmed, topic:shaders
