### ISSUE TITLE
Godot Web Build reloads infinitely on github.io

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#97580] opened 2024-09-28 09:55 UTC
### Tested versions

4.4.dev2
master branch as of 28.09.2024

### System information

Any

### Issue description

https://github.com/user-attachments/assets/80af8339-850d-414c-b9a1-12313b0eda42

### Steps to reproduce

1. Go to https://swarkin.github.io/wsclicker

### Minimal reproduction project (MRP)

Not a MRP but the project in question: https://github.com/Swarkin/wsclicker

**Comment by yankscally** [comment] 2024-09-28 10:05
hey - I've been following this project. 

tested this and got the same result on ChromeOS

[Screen recording 2024-09-28 10.46.57 AM.webm](https://github.com/user-attachments/assets/956b90a7-07fc-4ce5-92ce-5de4d6c37526)

**Comment by RedMser** [comment] 2024-09-28 12:23
It is caused by following code (note the `window.location.reload()` at the end): https://github.com/godotengine/godot/blob/76a135926aef1f02f27e4e09093787f2c670956d/misc/dist/html/full-size.html#L153-L171

CC @adamscott

**Comment by Swarkin** [comment] 2024-09-28 12:28
I cannot do this as I need CORS headers for threads to work...

**Comment by AThousandShips** [comment] 2024-09-28 12:38
For me the following error occurs in the console for the running page:
> Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

**Comment by AThousandShips** [comment] 2024-09-28 12:44
Have you actually built the template with threads? The template file doesn't have "threads" in the name which is normally added, you need to build it with threads explicitly enabled

**Comment by RedMser** [comment] 2024-09-28 12:50
> I cannot do this as I need CORS headers for threads to work...

I haven't done any threaded web apps before, so my assessment might be wrong. But as far as I can read online (search for "github pages cross origin isolation"), you need to do some additional work to enable cross origin isolation headers on github pages. Here is one example I found: https://docs.wasmer.io/sdk/wasmer-js/how-to/coop-coep-headers

**Comment by AThousandShips** [comment] 2024-09-28 12:52
> But the infinite reload is still something that should be fixed (show an error message on the web page instead).

This might be something that happens before the engine can load properly (it seems at least one error happens immediately in the service worker) so might be something we don't have any power over, but not sure exactly where things are breaking exactly

**Comment by adamscott** [comment] 2024-09-28 17:37
I don't have access to a computer this weekend, but I'll see what I can do Monday.

**Comment by adamscott** [comment] 2024-10-02 14:52
> > I cannot do this as I need CORS headers for threads to work...
> 
> https://github.com/gzuidhof/coi-serviceworker gets around the use of headers on hosters where you cannot change them

We do handle this directly in the Web export template since #86089.

**Comment by mhilbrunner** [comment] 2024-10-04 16:54
cc @adamscott ^

**Comment by adamscott** [comment] 2024-10-04 17:14
@Swarkin Did you rename `wsclicker_client_web_wasm32.html` to `index.html`?

**Comment by Swarkin** [comment] 2024-10-04 17:31
I did, do I need to rename everything containing `wsclicker_client_web_wasm32` to index?

**Comment by adamscott** [comment] 2024-10-04 17:32
@Swarkin Try exporting the project using `index.html` as name directly (without any renaming afterwards). We should advise people to never rename files in the docs.

The service worker fails to load `wsclicker_client_web_wasm32.html` and then everything fails.

**Comment by Swarkin** [comment] 2024-10-04 17:47
Seems like that was the actual issue, even though Im pretty sure that it worked this way in the past? Anyways thank you!
Should we convert this into a documentation issue and leave it open?

**Comment by adamscott** [comment] 2024-10-04 18:32
> Seems like that was the actual issue, even though Im pretty sure that it worked this way in the past? Anyways thank you! Should we convert this into a documentation issue and leave it open?

There's definitely something wrong when a file can't be loaded. I'll try to fix the infinite loading.

**Comment by adamscott** [comment] 2024-10-25 17:00
Weird. I tried to rename in a small test project `test.html` to `index.html`, and it still works...

I'll create a PR for the documentation and close this issue. Then, if the problem returns, I'll be there to fix it.

**Closed by adamscott** 2024-10-25 17:00 UTC
Labels: bug, platform:web, confirmed, needs testing, crash
