### ISSUE TITLE
AnimationSprite crash

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#24630] opened 2018-12-27 18:09 UTC
**Godot version:**
![image](https://user-images.githubusercontent.com/13235119/50489855-5bf14500-0a0a-11e9-808c-50fc5d9597cd.png)

**OS/device including version:**
win7-64

**Issue description:**
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Set<BaseButton * __ptr64,Comparator<BaseButton * __ptr64>,DefaultAllocator>::front (c:\godot\core\set.h:573)
[1] Set<BaseButton * __ptr64,Comparator<BaseButton * __ptr64>,DefaultAllocator>::front (c:\godot\core\set.h:573)
[2] BaseButton::_unpress_group (c:\godot\scene\gui\base_button.cpp:46)
[3] BaseButton::_gui_input (c:\godot\scene\gui\base_button.cpp:157)
[4] MethodBind1<BaseButton,Ref<InputEvent> >::call (c:\godot\core\method_bind.gen.inc:815)
[5] Object::call_multilevel (c:\godot\core\object.cpp:779)
[6] Object::call_multilevel (c:\godot\core\object.cpp:886)
[7] Viewport::_gui_call_input (c:\godot\scene\main\viewport.cpp:1515)
[8] Viewport::_gui_input_event (c:\godot\scene\main\viewport.cpp:1856)
[9] Viewport::input (c:\godot\scene\main\viewport.cpp:2608)
[10] Viewport::_vp_input (c:\godot\scene\main\viewport.cpp:1293)
[11] MethodBind1<Viewport,Ref<InputEvent> const & __ptr64>::call (c:\godot\core\method_bind.gen.inc:815)
[12] Object::call (c:\godot\core\object.cpp:945)
[13] Object::call (c:\godot\core\object.cpp:869)
[14] SceneTree::call_group_flags (c:\godot\scene\main\scene_tree.cpp:262)
[15] SceneTree::input_event (c:\godot\scene\main\scene_tree.cpp:418)
[16] InputDefault::_parse_input_event_impl (c:\godot\main\input_default.cpp:440)
[17] InputDefault::parse_input_event (c:\godot\main\input_default.cpp:260)
[18] OS_Windows::WndProc (c:\godot\platform\windows\os_windows.cpp:709)
[19] WndProc (c:\godot\platform\windows\os_windows.cpp:938)
[20] TranslateMessageEx
[21] CallWindowProcW
[22] CallWindowProcW
[23] glDebugEntry
[24] TranslateMessageEx
[25] TranslateMessage
[26] OS_Windows::process_events (c:\godot\platform\windows\os_windows.cpp:2197)
[27] OS_Windows::run (c:\godot\platform\windows\os_windows.cpp:2754)
[28] widechar_main (c:\godot\platform\windows\godot_win.cpp:150)
[29] _main (c:\godot\platform\windows\godot_win.cpp:172)
[30] main (c:\godot\platform\windows\godot_win.cpp:184)
[31] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264)
[32] BaseThreadInitThunk
-- END OF BACKTRACE --

**Steps to reproduce:**
Add AnimationSprite node , set "New SpiritFrame", click in "SpiritFrames", click "OpenEditor"
ps: Happen once. The next time it worked.

**Minimal reproduction project:**
NA

**Comment by guilhermefelipecgs** [comment] 2018-12-28 15:43
This also happens when you click in "Open Editor" to edit TileMap. I think it's the same log.

**Comment by guilhermefelipecgs** [comment] 2018-12-28 15:47
Maybe it's the same problem #20887 and #23672.

**Comment by akien-mga** [comment] 2019-01-26 00:12
Duplicate of #23672 indeed.

**Closed by akien-mga** 2019-01-26 00:12 UTC
Labels: bug, topic:core
