### ISSUE TITLE
Camera2D jiggling with Rotating mode

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#4455] opened 2016-04-26 21:13 UTC
Win7 64bit, Godot 2.0.1-stable

When a Camera2D (with Rotating option enabled) is inside of a quickly rotating object some jiggling is visible.

**Steps to reproduce:**
- Create a new scene
- Create a hierarchy:

>[Node2D] main
>> [Node2D] RotatingObj
>>> [Polygon2D or any other visible Node2D] Obj
>>> [Camera2D]

>> [AnimationPlayer]

- Enable Rotating option in the camera
- Add an animation, autoplay, looped, create a keyframe for RotatingObj rotation 0 degrees at second 0, and a keyframe for rotation 360 at second 1 (so the object does a full circle in a second)
- Play the scene

The object will jiggle visibly.
This is probably due to the nature of the engine. Probably hard to fix, but thought it's a good idea to place it here :)

This occured on a low-end laptop. Might not be as noticable on desktops.

**Comment by mateusak** [comment] 2016-04-26 22:17
Probably a V-Sync issue, isn't it?

**Comment by kubecz3k** [comment] 2016-04-27 07:59
Sounds like duplicate of https://github.com/godotengine/godot/issues/2043
This one will be fixed when interpolation between normal and physic frame will be implemented
Can you check if you are able to observe jitter  in "[Motion Test"](https://downloads.tuxfamily.org/godotengine/2.0.2/Godot_v2.0.2_stable_demos.zip) demo?

**Comment by WalasPrime** [comment] 2016-04-27 08:22
Yep, 2nd and 4th jitter together from time to time.
The GPU is an Intel HD Graphics 3000 (at least that's what the device manager tells me). The performance is "okay" on this laptop, never thought there would be jitter in something like this :D

Well, I guess it's a duplicate of #2043 then :) Thanks.

**Comment by kubecz3k** [comment] 2016-04-27 08:24
Haven't seen your comment at the moment when attaching a labels.. archiving because it's a duplicate of https://github.com/godotengine/godot/issues/2043

**Closed by kubecz3k** 2016-04-27 08:24 UTC
Labels: archived, bug, topic:rendering
