### ISSUE TITLE
Two different export arrays will be shared if they are initialized to same value

### ISSUE THREAD

**Issue by cccccroge** [godotengine/godot#36526] opened 2020-02-25 07:24 UTC
**Godot version: 3.2

**OS/device including version: Windows 10

**Issue description:**
If two different export array variables are initialized to same value when declared,
modify one of them will affect the other unexpectedly.

I'm not sure if this is the same behavior as the doc says, although what it says is this will happen between instances using same script, not between two variables in same script. I treat it as a different problem.
>  exported arrays are shared between all instances. This means that editing them in one instance will cause them to change in all other instances [Ref](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_exports.html#exporting-arrays)

**Steps to reproduce:**
1. Add a node2D as main scene
2. Attach script as follow:
```
extends Node2D

export(Array, int) var A = [1, 2, 3]
export(Array, int) var B = [1, 2, 3]

func _ready():
	print(A)
	print(B)
	A[0] = 0
	print(A)
	print(B)
```
3. Run the scene and it outputs:
```
[1, 2, 3]
[1, 2, 3]
[0, 2, 3]
[0, 2, 3]
```

**Minimal reproduction project:**
[array_bug.zip](https://github.com/godotengine/godot/files/4248576/array_bug.zip)

**Comment by cccccroge** [comment] 2020-02-25 07:25
possibly duplicate of #36520

**Comment by Calinou** [comment] 2020-02-25 08:12
This is actually a duplicate of #20436.

**Closed by Calinou** 2020-02-25 08:12 UTC
