### ISSUE TITLE
GLTF2 Reimport always clears surface names

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#35728] opened 2020-01-30 02:34 UTC
**Godot version:**
3.2
**OS/device including version:**
ArcoLinux
**Issue description:**
![image](https://user-images.githubusercontent.com/28724859/73414652-10782d00-42d5-11ea-98f4-9a0a523fce18.png)

![image](https://user-images.githubusercontent.com/28724859/73414665-1837d180-42d5-11ea-8ddf-d43c861abc4e.png)

Godot doesn't use the surface names when importing, so you wind up with blank.  Even if you assign them in Godot, Godot will clear them when reimporting.  It doesn't seem to matter that the .mesh files are stored externally, unlike the animation files which will retain their settings on reimport.

**Comment by somnivore** [comment] 2020-01-30 02:48
I recreated the whole scene and it seems to preserve the names, now.  There must've been some kind of mismatch with the previous scene and the .glb.

**Comment by somnivore** [comment] 2020-01-30 04:41
Nevermind, Godot just doesn't update immediately.  Restarting the editor shows Godot isn't preserving anything.

**Comment by fire** [comment] 2020-01-30 20:48
Will be a bit slow, but interested in looking at it.

**Comment by Shatur95** [comment] 2020-01-31 13:36
This also may be related with #35697. Looks like the model do not saves material paths

**Comment by fire** [comment] 2020-02-02 07:45
Reviewing the issue:

* materials do have names
* In gltf2 primitives / aka surfaces in Godot don't have names

Sidenote:

For the slots to exist the scene must be exported with materials.

**Comment by KoBeWi** [comment] 2020-12-23 23:13
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by aaronfranke** [comment] 2023-08-17 19:08
Tested in Godot 4.0 and 4.1.1. Surface names are not blank anymore, they are saved.

Re-importing a GLB file does reset this name back to what's in the file, but I think this is expected behavior, it's a good thing that reimporting a file will give you the new data from that file. I don't know what the use case is for changing the surface name after import, but if you want to make changes, you can duplicate the resource.

Closing as fixed in Godot 4.0.

**Closed by aaronfranke** 2023-08-17 19:08 UTC
Labels: bug, topic:import
