### ISSUE TITLE
[4.0] Strange behavior of OmniLight3D in the editor

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#57578] opened 2022-02-03 08:15 UTC
### Godot version

4.0 Alpha 1

### System information

Windows 11, Intel IRIS Xe

### Issue description

As you move around the 3D scene, the light sources begin to change their brightness (as in the video), which makes it difficult to design levels.

Couldn't find a similar issue, but if this is a duplicate, I apologize.

https://user-images.githubusercontent.com/13809475/152305063-b96dcfef-8691-4878-8787-bc23372ccf72.mp4

### Steps to reproduce

1. Create a scene
2. Place objects on it
3. Place OmniLight3D

Light bulb settings are shown in the video.

If you need a minimal example, I can attach my own. But I don't think it will be required.

**Comment by mrjustaguy** [comment] 2022-02-03 08:33
Mobile Renderer? if so duplicate of https://github.com/godotengine/godot/issues/55881

**Comment by SkanerSoft** [comment] 2022-02-03 08:48
I don't know how mobile it is, since this effect appears directly in the editor (see the attached video).

**Comment by Zireael07** [comment] 2022-02-03 09:13
Are you using Vulkan Clustered or Vulkan Mobile?

**Comment by SkanerSoft** [comment] 2022-02-03 09:23
Oh, yes, it's a mobile Vulkan! At first I thought it was a mobile device.
On a mobile device, light sources are not displayed at all)

**Comment by akien-mga** [comment] 2022-02-03 09:30
That's indeed a duplicate of #55881 then.

For information, the Vulkan Mobile renderer can be used both on mobile and desktop, and is intended to be more friendly to lower end devices. But currently it's still quite a work-in-progress with a lot of known bugs, so it's not really usable right now (doesn't work at all on some mobile GPUs). The high end Vulkan Clustered backend is more stable and better tested for now. (Of course the aim is that the Vulkan Mobile backend should also become stable in the future, but for experimenting with 4.0 alpha the Vulkan Clustered backend will give better results.)

**Closed by akien-mga** 2022-02-03 09:30 UTC
Labels: bug, topic:rendering, topic:3d
