### ISSUE TITLE
GLES2 Lightmap baking issue with GridMap

### ISSUE THREAD

**Issue by vansoest** [godotengine/godot#37657] opened 2020-04-07 12:53 UTC
**Godot version:**
**3.2.1**, **godot-bin** packaged from Arch User Repository.

**OS/device including version:**
Arch Linux latest 2020-04-06 
Kernel version:  **5.5.13-arch2-1**
NVidia module driver version: **440.64**
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
GPU: 01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [**GeForce GTX 1050 Ti]** (rev a1)

**Issue description:**
Got Artifacts by baking the Lightmaps for GLES2 with a GridMap.
[screenshot.png](https://raw.githubusercontent.com/vansoest/GLES2LightmapIssue/master/screenshot.png)

**Steps to reproduce:**
Import  the glTF 2.0 file into Godot as scene with Light Baking: **Gen Lightmaps** as import setting to auto unwrap uv2 maps. Export the Scene as **tiles.meshlib**. 

Add following Nodes:
* Add WorldEnvironment and Environment with ProceduralSky.
* Add GridMap with **tiles.meshlib**.
* Add DirectionalLight and transform the rotation.
* Add BakedLightmap change Mode to **RayTrace** and Quality to **High**.

Draw a test case in the GridMap and change the extends of the BakedLightmap suitable for the test case.
Click on Bake Lightmaps button.

**Minimal reproduction project:**
https://github.com/vansoest/GLES2LightmapIssue

**Comment by Calinou** [comment] 2020-04-07 13:10
Duplicate of #29203 and #30929. The lightmapper will be rewritten in Godot 4.0.

**Closed by Calinou** 2020-04-07 13:10 UTC
