### ISSUE TITLE
Vulkan: Label's material's UV are incorrect when used in a custom shader

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50452] opened 2021-07-14 13:39 UTC
### Godot version

v4.0.dev.calinou [fabc3b93f]

### System information

Window10

### Issue description

Label's material's UV look like wrong.
![222](https://user-images.githubusercontent.com/35988767/125631906-e39ec56d-df34-4011-9c20-6012a29a293a.PNG)

```COLOR.a *= UV.x;```
![1](https://user-images.githubusercontent.com/35988767/125631267-0d63de03-8d99-4538-b21b-3a79d6053734.PNG)
```COLOR.a *= UV.y;```
![2](https://user-images.githubusercontent.com/35988767/125631450-ba530d43-c567-4a2e-bb6f-d97af4fbac93.PNG)

### Steps to reproduce

1. Create a label
2. set label's text to something
3. create a material
4. set material code like this: COLOR.a = UV.x
5. look

### Minimal reproduction project

[LabelUvTest.zip](https://github.com/godotengine/godot/files/6816459/LabelUvTest.zip)

**Comment by Calinou** [comment] 2021-07-15 23:23
Duplicate of https://github.com/godotengine/godot/issues/23210.

**Closed by Calinou** 2021-07-15 23:23 UTC
Labels: bug, regression, topic:2d, topic:rendering
