### ISSUE TITLE
Spotlight-Projector projection broken/mismatched

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#58237] opened 2022-02-17 12:05 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10, RTX 2070

### Issue description

The light projection of the spot light does only show a small spot of the given texture as projection

![editor_screenshot_2022-02-17T125733](https://user-images.githubusercontent.com/21973505/154477879-b5e0ee88-584d-4001-b393-f94a7b858ad3.png)

### Steps to reproduce

create SpotLight3D
assign projector texture
shine on receiving object

### Minimal reproduction project

[spotlight_projector.zip](https://github.com/godotengine/godot/files/8088460/spotlight_projector.zip)

**Comment by Calinou** [comment] 2022-02-17 17:13
Duplicate of https://github.com/godotengine/godot/issues/50445 (already fixed in the latest `master` branch).

**Closed by Calinou** 2022-02-17 17:13 UTC
Labels: bug, topic:rendering, topic:3d
