### ISSUE TITLE
global shader const syntax error

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#38818] opened 2020-05-18 02:04 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Linux

**Issue description:** **Steps to reproduce:**
in Godot shader write:
```
const int a=1;
const int b=a+1;
```
result error:
```
drivers/gles3/shader_gles3.cpp:164 - CanvasShaderGLES3: Vertex Program Compilation Failed:
0(118) : error C1503: undefined variable "m_a"
```

**Comment by clayjohn** [comment] 2020-05-18 02:37
You can't add numbers together outside of a function in shaders. It's not a bug.

This same code works if you put it inside a function.

This is from the GLSL spec:

> Declarations of globals without a storage qualifier, or with just the const qualifier, may include initializers, in which case they will be initialized before the first line of main() is executed. Such initializers must be a constant expression.

**Comment by akien-mga** [comment] 2020-05-18 06:07
Can we intercept this to provide a syntax error?

**Comment by clayjohn** [comment] 2020-05-18 06:32
@akien-mga That would certainly be nice. 

In addition, it looks like in the generated code the defines are in the wrong order
```
314: const int m_b=(m_a+1);
315: const int m_a=1;
```

**Comment by clayjohn** [comment] 2020-05-18 06:35
Actually, it looks like it is intentionally supported for GLES3 

See https://github.com/godotengine/godot/issues/37457 and https://github.com/godotengine/godot/pull/37462

So we need to look into why the constants are still in the wrong order

cc @Chaosus

**Comment by clayjohn** [comment] 2020-05-18 06:58
Yep fixed in https://github.com/godotengine/godot/pull/37795

**Closed by clayjohn** 2020-05-18 06:58 UTC
Labels: discussion, topic:rendering, topic:shaders
