### ISSUE TITLE
Script buttons in tree don't open external editor when internal Script Editor feature is disabled

### ISSUE THREAD

**Issue by benjoesgames** [godotengine/godot#71959] opened 2023-01-24 09:19 UTC
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10

### Issue description

Wanted to use external script editor while disabling the internal editor to not accidentally open it but that disables all script buttons and they don't open the script in the external editor anymore.

### Steps to reproduce

**Setup:**
1. Set up external script editor based on [official documentation](https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#using-an-external-text-editor) (VSCode in my case)
3. Create a node and attach a script to it and save it
4. Click the _Open Script_ icon next to the node in the Scene view
5. Make sure the script opens in the external editor
6. Disable the _Script Editor_ in the _Editor>Manage Editor Features..._ menu
4. Click the _Open Script_ icon next to the node again

**Expected:**
The script opens in the external script editor based on settings. (Just like when the feature is enabled.)

**Actual:**
Nothing happens. 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-01-24 11:23
Duplicate of https://github.com/godotengine/godot/issues/59758.

**Closed by Calinou** 2023-01-24 11:23 UTC
