### ISSUE TITLE
iOS 13.1+ Crash on Application Exit

### ISSUE THREAD

**Issue by dylantmarsh** [godotengine/godot#34952] opened 2020-01-09 13:39 UTC
**Godot version:**
3.2 beta 5

**OS/device including version:**
Tested on:
Apple iPhone 11 Pro - iOS 13.3
Apple iPad (7th Generation) - iOS 13.1.1
Apple iPhone 7 - iOS 13.1.2
Tested various android devices and none encounter this issue. This seems to be iOS specific.

**Issue description:**
On iOS devices running iOS 13.1.1+ (I have not personally tested this on lower versions of iOS), closing the app results in what appears to be some sort of crash/memory leak. Below is some of the reporting from XCode. There was [another issue reported fixed #7966 ](https://github.com/godotengine/godot/issues/7966) that is similar to this but I am not sure if it was intended to be in 3.2 beta 5. It seems iOS is dropping frames, performance is not great at all despite reporting 60 FPS in the debugger. Using `get_tree().quit()` does not work on iOS - not sure if this is related.

```
2020-01-08 21:06:38.710038-0500 Geocrash[3819:57474] Can't end BackgroundTask: no background task exists with identifier 5 (0x5), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
iphone_finish
2020-01-08 21:06:38.741265-0500 Geocrash[3819:57474] **WARNING**: ObjectDB Instances still exist!
2020-01-08 21:06:38.741331-0500 Geocrash[3819:57474]    At: core/object.cpp:2076:cleanup() - ObjectDB Instances still exist!
**WARNING**: ObjectDB Instances still exist!
   At: core/object.cpp:2076:cleanup() - ObjectDB Instances still exist!
2020-01-08 21:06:38.753357-0500 Geocrash[3819:57474] **ERROR**: BUG!
2020-01-08 21:06:38.753451-0500 Geocrash[3819:57474]    At: core/string_name.cpp:107:unref() - BUG!
**ERROR**: BUG!
   At: core/string_name.cpp:107:unref() - BUG!
Geocrash(3819,0x1020f9800) malloc: *** error for object 0x282c86d40: pointer being freed was not allocated
Geocrash(3819,0x1020f9800) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Steps to reproduce:**
AFAIK any minimal project exported and ran on iOS will experience this crash when closing the app on iOS.

**Comment by akien-mga** [comment] 2020-01-09 13:46
```
**WARNING**: ObjectDB Instances still exist!
   At: core/object.cpp:2076:cleanup() - ObjectDB Instances still exist!
```
This means that you have orphan nodes which are being leaked, you can enable `debug/settings/verbose_stdout` to see more details about the nodes being leaked. You can also use the editor debugger on desktop to monitor if there are any orphan nodes while you run and quit the game.

This might be what leads to:
```
**ERROR**: BUG!
   At: core/string_name.cpp:107:unref() - BUG!
```
which needs to be fixed nevertheless, especially if it triggers a crash.

**Comment by dylantmarsh** [comment] 2020-01-09 13:59
Thank you for the thread to follow, here is the verbose output showing the orphan nodes:

```
2020-01-09 08:57:48.013605-0500 Geocrash[16745:263153] Leaked instance: ICloud:50
Leaked instance: ICloud:50
2020-01-09 08:57:48.013649-0500 Geocrash[16745:263153] Leaked instance: GameCenter:48
Leaked instance: GameCenter:48
2020-01-09 08:57:48.013695-0500 Geocrash[16745:263153] Leaked instance: InAppStore:49
Leaked instance: InAppStore:49
2020-01-09 08:57:48.013767-0500 Geocrash[16745:263153] Leaked instance: InputEventScreenTouch:2073 - Resource name:  Path:
Leaked instance: InputEventScreenTouch:2073 - Resource name:  Path: 
2020-01-09 08:57:48.013802-0500 Geocrash[16745:263153] Leaked instance: iOS:51
Leaked instance: iOS:51
2020-01-09 08:57:48.027511-0500 Geocrash[16745:263153] Orphan StringName: ICloud
Orphan StringName: ICloud
2020-01-09 08:57:48.027553-0500 Geocrash[16745:263153] Orphan StringName: GameCenter
Orphan StringName: GameCenter
2020-01-09 08:57:48.027568-0500 Geocrash[16745:263153] Orphan StringName: InputEventScreenTouch
Orphan StringName: InputEventScreenTouch
2020-01-09 08:57:48.027580-0500 Geocrash[16745:263153] Orphan StringName: iOS
Orphan StringName: iOS
2020-01-09 08:57:48.027591-0500 Geocrash[16745:263153] Orphan StringName: InAppStore
Orphan StringName: InAppStore
2020-01-09 08:57:48.027604-0500 Geocrash[16745:263153] StringName: 5 unclaimed string names at exit.
StringName: 5 unclaimed string names at exit.
```

I will do a formal test on an empty test project this afternoon and put it on git as a test repo if I get the same result. Thanks!

**Comment by akien-mga** [comment] 2020-01-09 14:24
Thanks, the output shows that it's things internal to the iOS port that are leaking, so it would likely not be due to your project indeed. It should thus also happen in an empty project.

It's likely a regression caused by #32326, CC @starryalley @godotengine/ios. The `ios` singleton is not properly freed on cleanup.

**Comment by samgreen** [comment] 2020-01-10 09:11
When the app is closed, _all memory_ will be reclaimed by the OS. I'm not really clear on what it means to free a singleton, since it should exist for the lifetime of the application, I don't consider this a leak. All those classes have been touched by #22784

**Comment by akien-mga** [comment] 2020-01-14 12:07
CC @bruvzg

**Comment by bruvzg** [comment] 2020-01-14 14:16
I do not see any code for freeing any iOS singletons at all (for most of the singletons it's done in the associated `unregister_...` function).

> It's likely a regression caused by #32326

It's just saving pointer to the singleton, should not affect anything.

**Comment by bruvzg** [comment] 2020-01-14 14:20
> When the app is closed, all memory will be reclaimed by the OS.

That's true for any modern OS, but it won't call destructors for not static objects (and Godot singletons are not static objects).

**Comment by zxcvdev** [comment] 2020-01-18 08:37
Crash can be reproduced in Godot 3.2 RC 1 with iPhone Simulator (using Xcode 11.3.1) with any Godot Project. Just to be clear, the crash occurs when the app is closed, not when the app is moved to the background.

Further testing shows that:
* `iOS`, `GameCenter`, `InAppStore` and `ICloud` instances are created but indeed never deleted on exit. The code for this is missing.
* Unhandled input events are not freed on exit either. `InputEventScreenTouch` and `InputEventScreenDrag` events that haven't been handled yet due to lag for example are still present in `event_queue` on exit. More prevalent though is when the app is moved to the background by swiping up on iPhone X and newer, new touch input events are stored in the `event_queue` (which they shouldn't be?) and so when closing the app, event instances are still present in `event_queue` and are not getting freed.

I will make a PR with a quick fix to prevent a crash, however the logic on how inputs are handled by Godot on the iPhone should be looked at. Especially when switching the app between background and foreground.

**Closed** 2020-01-18 14:23 UTC
Labels: bug, high priority, platform:ios, topic:core
