### ISSUE TITLE
WindowDialog Titlebar Missing When Creating Theme

### ISSUE THREAD

**Issue by pixelinkmedia** [godotengine/godot#29723] opened 2019-06-12 17:13 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 7
Desktop

**Issue description:**
When creating a theme, I add a WindowDialog class... under styles, there is only the panel style. If I try to set the panel style, the window title bar disappears (actually it is not even there to begin with) and title text. So, if I run the game, the titlebar and text is missing from the WindowDialog after theme change. If using default theme and run, the dialog shows everything.

**Steps to reproduce:**
Just add a new theme and add WindowDialog class, change "panel" style.

![griscontainer2](https://user-images.githubusercontent.com/51757955/59372556-c75b7480-8d15-11e9-8a8b-ced91f278c6a.jpg)

**Comment by TheDuriel** [comment] 2019-06-13 02:54
The title is not a unique element. It is part of the stylebox, created by adding an outline and custom offset.

**Comment by pixelinkmedia** [comment] 2019-06-13 10:00
Yeah... However, it still doesn't Show when I edit the style, when i making a theme.
Even when you run the game... it doesn't show.

**Comment by MunWolf** [comment] 2019-09-20 02:15
You can make it by for example using the expand margin and border in the flat style box.
![image](https://user-images.githubusercontent.com/3696546/65293944-d9d71c80-db54-11e9-8505-61aaa8783f82.png)
This is controlled by the stylebox so you need to make it so the stylebox handles it if you define a custom one.

**Comment by bojidar-bg** [comment] 2020-02-05 12:27
Duplicate of #3095. You could open a proposal about changing this behavior, however.

**Closed by bojidar-bg** 2020-02-05 12:27 UTC
Labels: bug, topic:editor
