### ISSUE TITLE
project.godot is not reloaded if changed outside of the Editor

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#27502] opened 2019-03-28 22:33 UTC
**Godot version:**

current master

**OS/device including version:**

Windows10, reproductible always

**Issue description:**

While i was working i pulled changes from a git repository, the godot.project changed, but when i returned to the editor these changes wasn't reflected, so if you save anything, the changes to godot.project will be reverted.
This can cause 2 problems:
1. If the change on properties affects the game runtime (like using custom properties or whatever), you will need to restart the editor make it work
2. If you are distracted you can add the project.godot file to the next commit and cause a regression

**Steps to reproduce:**
described avobe, you can modify the file with a text editor to simulate pulling changes

**Comment by TheRealCatherine** [comment] 2019-04-07 01:16
Ah you beat me to filing this one! It is certainly annoying having to close and restart the editor when doing a git pull.

I must say this is one of the things I do like about Unity - you can just git pull with the editor open and it will offer to reload the scene after noticing the external change.

If nobody beats me to fixing it I'm hoping to take a crack at this one within the next week or two

**Comment by akien-mga** [comment] 2019-04-07 10:22
Duplicate of #20250.

**Closed by akien-mga** 2019-04-07 10:22 UTC
Labels: bug, topic:editor
