### ISSUE TITLE
TreeItem checkbox can be toggled when clicking to the left of the fold button

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#91685] opened 2024-05-07 22:37 UTC
### Tested versions

4.3 dev6 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Title.

https://github.com/godotengine/godot/assets/2223172/5d64f3ab-ad88-42cc-9ad0-2b727dedac64

I can't count how many times I tried to fold or unfold something and it toggled the checkobx instead. It's especially annoying when propagating checks, because it can cause information loss in a branch when not all checkboxes were enabled. I have a big REVERT button in case I accidentally toggle something and I use it alot.

I think the area to the left of the folding icon should fold instead of edit the item.

### Steps to reproduce

1. In a tree with checkboxes (e.g. export preset resource list) click to the left of the fold button

### Minimal reproduction project (MRP)

N/A

**Comment by kleonc** [comment] 2024-05-07 22:44
Looks familiar... duplicate of #55774?

**Closed** 2024-05-08 10:31 UTC
Labels: bug, discussion, usability, topic:gui
