### ISSUE TITLE
Missing texture for MeshEditor light1 and light2 buttons

### ISSUE THREAD

**Issue by Trashtalk217** [godotengine/godot#65243] opened 2022-09-02 11:25 UTC
### Godot version

4.0.dev (9142904c24)

### System information

Arch Linux

### Issue description

Two missing texture symbols over yonder:
![image](https://user-images.githubusercontent.com/24552941/188128615-57f5a0fd-3554-453a-8c1e-4b09eeaed703.png)

### Steps to reproduce

1. Create a new project.
2. New scene: select 3D node
3. Add child node MeshInstance
4. Select Mesh 'New Sphere Mesh'
5. Open the Mesh editor
6. See missing textures

### Minimal reproduction project

[test2.zip](https://github.com/godotengine/godot/files/9477462/test2.zip)

**Comment by Trashtalk217** [comment] 2022-09-02 11:29
I think the file relevant for this issue is [this one](https://github.com/godotengine/godot/blob/master/editor/plugins/mesh_editor_plugin.cpp). And some additional info from the command line:

```
tempo:godot$ ./bin/godot.linuxbsd.tools.x86_64 
Godot Engine v4.0.alpha.custom_build.9142904c2 - https://godotengine.org
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Vulkan API 1.2.0 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 (KBL GT2)
 
Editing project: /home/tempo/Other Projects/Godot 4 Projects/test2
Godot Engine v4.0.alpha.custom_build.9142904c2 - https://godotengine.org
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Vulkan API 1.2.0 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 (KBL GT2)
tempo:godot$  
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:75)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:99)
```

**Comment by Calinou** [comment] 2022-09-02 15:41
Duplicate of https://github.com/godotengine/godot/issues/65090 (same cause).

**Closed by Calinou** 2022-09-02 15:41 UTC
