### ISSUE TITLE
flickering black screen at startup GLES2 (export android x86)

### ISSUE THREAD

**Issue by walkibe2015** [godotengine/godot#28543] opened 2019-04-30 21:00 UTC
**Godot version:**
3.1.1

**Target OS/device including version:**
Asus K010 build WW-2.2.33.144
android 4.4.2 (32 bit)
CPU : Processeur Intel Atom® Z3745 
GPU : Intel HD Graphics (Bay Trail)
OpenGL ES 3.0 - Build CL-260519-CI-15.33-24169

**Issue description:**
Hi,
when i start a remote debug of a GLES2 project on an Asus K010, i just get a flickering black screen.
Thanks for looking.

adb logcat -s godot:E :

<pre>E/godot   (11038): **ERROR**: SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:233: &apos;constructor&apos; : not enough data provided for constructi
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:129:_display_error_with_code() - SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:
E/godot   (11038): **ERROR**: Method/Function Failed, returning: __null
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:288:get_current_version() - Method/Function Failed, returning: __null
E/godot   (11038): **ERROR**: Condition &apos; !version &apos; is true. returned: false
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:88:bind() - Condition &apos; !version &apos; is true. returned: false
E/godot   (11038): **ERROR**: SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 2:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 4:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 4:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 4:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 4:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:233: &apos;constructor&apos; : not enough data provided for constructi
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:129:_display_error_with_code() - SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 2:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 4:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 4:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 4:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 4:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:
E/godot   (11038): **ERROR**: Method/Function Failed, returning: __null
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:288:get_current_version() - Method/Function Failed, returning: __null
E/godot   (11038): **ERROR**: Condition &apos; !version &apos; is true. returned: false
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:88:bind() - Condition &apos; !version &apos; is true. returned: false
E/godot   (11038): **ERROR**: SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 2:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 4:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 4:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 4:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 4:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:233: &apos;constructor&apos; : not enough data provided for constructi
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:129:_display_error_with_code() - SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 2:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 4:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 4:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 4:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 4:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 4:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 6:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 6:
E/godot   (11038): **ERROR**: Method/Function Failed, returning: __null
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:288:get_current_version() - Method/Function Failed, returning: __null
E/godot   (11038): **ERROR**: Condition &apos; !version &apos; is true. returned: false
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:88:bind() - Condition &apos; !version &apos; is true. returned: false
E/godot   (11038): **ERROR**: SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:233: &apos;constructor&apos; : not enough data provided for constructi
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:129:_display_error_with_code() - SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:
E/godot   (11038): **ERROR**: Method/Function Failed, returning: __null
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:288:get_current_version() - Method/Function Failed, returning: __null
E/godot   (11038): **ERROR**: Condition &apos; !version &apos; is true. returned: false
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:88:bind() - Condition &apos; !version &apos; is true. returned: false
E/godot   (11038): **ERROR**: SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:233: &apos;constructor&apos; : not enough data provided for constructi
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:129:_display_error_with_code() - SceneShaderGLES2: Vertex shader compilation failed:
E/godot   (11038): ERROR: 1:50: &apos;transpose&apos; : built-in redefinition is not allowed 
E/godot   (11038): ERROR: 3:199: &apos;vertex_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:199: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4-component vector of float&apos;
E/godot   (11038): ERROR: 3:201: &apos;world_transform&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:201: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;4X4 (default)row_major matrix of float&apos;
E/godot   (11038): ERROR: 3:215: &apos;normal_attrib&apos; : undeclared identifier 
E/godot   (11038): ERROR: 3:215: &apos;=&apos; :  cannot convert from &apos;float&apos; to &apos;3-component vector of float&apos;
E/godot   (11038): ERROR: 3:299: &apos;camera_inverse_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;vertex_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:28: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:29: &apos;normal_interp&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:29: &apos;assign&apos; :  cannot convert from &apos;3-component vector of float&apos; to &apos;float&apos;
E/godot   (11038): ERROR: 5:233: &apos;projection_matrix&apos; : undeclared identifier 
E/godot   (11038): ERROR: 5:
E/godot   (11038): **ERROR**: Method/Function Failed, returning: __null
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:288:get_current_version() - Method/Function Failed, returning: __null
E/godot   (11038): **ERROR**: Condition &apos; !version &apos; is true. returned: false
E/godot   (11038):    At: drivers/gles2/shader_gles2.cpp:88:bind() - Condition &apos; !version &apos; is true. returned: false
</pre>

**Steps to reproduce:**
Create an OpenGL ES 2.0 project
Create a scene with a sprite
add the Godot icon as texture
Add export Android X 86
Remote debug

**Minimal reproduction project:**
[gles2sprite.zip](https://github.com/godotengine/godot/files/3133024/gles2sprite.zip)

**Comment by KoBeWi** [comment] 2020-08-13 18:51
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 16:41
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 16:41 UTC
Labels: bug, platform:android, topic:rendering
