### ISSUE TITLE
Output terminal is not scrollable

### ISSUE THREAD

**Issue by TurtleKwitty** [godotengine/godot#61837] opened 2022-06-09 03:04 UTC
### Godot version

4.0.alpha9.official

### System information

Linux

### Issue description

The output terminal doesn't become scrollable without forcing a UI refresh of it by using the button controls

### Steps to reproduce

print to the output terminal multiple times

### Minimal reproduction project

[Test - 4.zip](https://github.com/godotengine/godot/files/8866437/Test.-.4.zip)

Just press play and wait a couple seconds for the terminal to fill up

**Comment by jgillich** [comment] 2022-06-09 04:03
Duplicate of https://github.com/godotengine/godot/issues/61324

**Closed** 2022-06-09 06:52 UTC
