### ISSUE TITLE
Exiting godot doesn't stop adb

### ISSUE THREAD

**Issue by baptistepouget** [godotengine/godot#4073] opened 2016-03-16 18:48 UTC
**Operating system or device:**
Arch Linux 64 bits and steam version of godot

**Issue description** (what happened, and what was expected):
When I exit godot (steam version, I have not tried with the non steam one) the adb process doesn't close itself so steam says that I am in game and I have to manually kill the process

**Steps to reproduce:**
-Start steam version of godot from steam
-Launch a project
-click the cross to exit godot
-use top command
-see that there is an adb process running
-see that steam says that you're in game
-kill the adb process
-steam no longer says that you're in game

**Comment by kubecz3k** [comment] 2016-03-16 19:34
related issue: https://github.com/godotengine/godot/issues/3813

**Comment by punto-** [comment] 2016-03-18 07:05
this used to work, maybe the commit for this didn't make it to the 2.0
branch? it was 1 or 2 days after the release, it added a parameter to
editor_settings.xml and the ._sc_ file

**Comment by akien-mga** [comment] 2016-03-18 07:21
I did backport the relevant commit to the 2.0 branch, see f619b057.
Now, I don't see "Shutdown Adb On Exit" in the Android editor settings in the master HEAD nor in 2.0.1, so I think you forgot to set it, you're only checking if it's defined in the above commit. Maybe it should be exposed to be configurable?

It is defined in my ``._sc_`` file for Godot 2.0.1 on Steam though:
```
[presets]
android/shutdown_adb_on_exit=true
```

About the bug itself I haven't checked yet if I can reproduce it.

**Comment by est31** [comment] 2016-03-19 08:31
its in fact a dupe of #3813.

**Comment by kubecz3k** [comment] 2016-03-19 09:44
Since  discussion is currently going on in this issue I'm closing https://github.com/godotengine/godot/issues/3813 as duplicate.  
Solution proposed in https://github.com/godotengine/godot/issues/3813:
>@est31: Its most probably caused by the android adb server , which gets started by godot and then runs for as long as the phone is connected. Don't really know why adb has been designed this way, most probably to offer some state over the command line.
> Godot should simply kill that process on exit: http://developer.android.com/tools/help/adb.html#stopping
> The issue then of course is that it might cause problems with people who want to use adb separately from godot.

**Comment by punto-** [comment] 2016-03-20 05:06
as far as i know this is fixed in the steam build, we check for a property
in editor settings, and run adb kill-server or something like that when the
editor exits. I think I tested it on linux when I did the last push to
Steam, but I don't remember.. do we at least see this code in the 2.0
branch?

**Comment by akien-mga** [comment] 2016-03-20 08:24
> do we at least see this code in the 2.0 branch?

Yes, as I mentioned already the code is in 2.0.1 too. It was cherry-picked in f619b05.

**Comment by akien-mga** [comment] 2016-03-20 09:07
Just to confirm that it was not removed later on:
- the code is there in 2.0.1-stable: https://github.com/godotengine/godot/blob/2.0.1-stable/platform/android/export/export.cpp#L1496-L1505
- and in master HEAD: https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L1496-L1505

I've just tested the Steam build and I can confirm that it does not seam to work.

I've tried also putting a build of the master branch in my Steam folder to use the embedded ``._sc_`` file (which works based on the list of demos it showed me), but the bug is still there.

My ``._sc_`` file has:
```
  GNU nano 2.5.3                                                   Fichier : ._sc_                                                                                                           

[init_projects]

list=["demos/viewport/screen_capture", "demos/viewport/gui_in_3d", "demos/viewport/3d_in_2d", "demos/viewport/2d_in_3d", "demos/misc/window_management", "demos/misc/udp_chat", "demos/misc/$

[presets]
android/shutdown_adb_on_exit=true
```

**Comment by akien-mga** [comment] 2016-03-20 09:14
It added some print_line's and it seems that ``EditorSettings::get_singleton()->get("android/shutdown_adb_on_exit")`` evaluates to false even with the above copied ``._sc_`` file.

**Comment by akien-mga** [comment] 2016-03-20 09:29
Ah of course! The code that loads the preset is only loaded when generating the ``editor_data/editor_settings.xml`` for the first time. If the file exists already (i.e. for all existing Steam users) the new preset is not parsed.

**Comment by akien-mga** [comment] 2016-03-20 09:32
As a side note that's a config value that should be exposed in the editor settings directly so that users can toggle it on/off. Maybe it should be made default too? Even when running outside Steam I wouldn't be against having adb killed when closing Godot (as long as it can be toggled off for those who don't want this behaviour).

**Closed** 2016-03-20 17:34 UTC
Labels: bug, topic:editor
