### ISSUE TITLE
Can't navigate from default directory

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#719] opened 2014-09-21 20:51 UTC
Create new scene
Add node2d
add script to node (works fine)
reload scene
add new node2d
add script to node 
Save a File dialog default to Roaming dir and trying to go to parent directory does not work
![script_saving_issue](https://cloud.githubusercontent.com/assets/8853364/4350002/147de152-41d1-11e4-9de9-39fba117999a.png)

**Comment by eska014** [comment] 2015-10-30 21:41
This issue is somewhat old and appears to be fixed by now. I could not reproduce it. If anyone still encounters this bug, briefly comment and it'll be reopened.

**Closed by eska014** 2015-10-30 21:41 UTC
