### ISSUE TITLE
Warnings / Errors add up when saving running game

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33429] opened 2019-11-07 15:27 UTC
**Godot version:**

_3.2 beta 1_

**OS/device including version:**

All

**Issue description:**

When you save whilst a game is running from the editor, the warning / error amount adds up if you the project while the game is running in background.

**Steps to reproduce:**

Have at least 1 warning / error, run the game using the play button in the editor, save the game in any way.

_Edit - Clarification: The game must be left running_

When running normally using the play button in the Editor:
![image](https://user-images.githubusercontent.com/55881826/68502889-71094800-0259-11ea-9fb3-7d619603d1d9.png)
After leaving the game in the background and saving:
![image](https://user-images.githubusercontent.com/55881826/68502931-8f6f4380-0259-11ea-8dd3-82957e0e4fd3.png)
Pressing saving again:
![image](https://user-images.githubusercontent.com/55881826/68502988-b0d02f80-0259-11ea-86b1-6deed395e515.png)
And so on ...

**Minimal reproduction project:**

[Debug Error Warning Demo.zip](https://github.com/godotengine/godot/files/3820330/Debug.Error.Warning.Demo.zip)

**Comment by groud** [comment] 2019-11-07 16:21
Could you paste the errors you have here ?

**Comment by AtomaFajrovulpo** [comment] 2019-11-07 16:22
It just duplicates the warning about deta not being used.

**Comment by Xrayez** [comment] 2019-11-08 10:48
You can write `_delta` so that the warning system will ignore it as unused. You can also disable certain type of warnings, or simply disable the warning system in the project settings.

**Comment by AtomaFajrovulpo** [comment] 2019-11-08 11:36
I just had to make a warning to show the bug and that was the easiest I could make 😄 !
Thanks for the `_delta` tip !

**Comment by groud** [comment] 2019-11-08 11:39
Anyway, I think the error staking up is an expected behavior (might be improved if needed). 
Same for the _delta thing, since it's only a warning.

I'll close this as the initial issue is solved.

**Comment by AtomaFajrovulpo** [comment] 2019-11-08 12:01
@groud My issue was never delta giving a warning, it was that the warnings and errors stack up. Could you please re-open this issue ?

**Comment by Xrayez** [comment] 2019-11-08 12:06
@AtomaFajrovulpo do they stack up on every `_process` call? If that's the case, I wasn't able to reproduce it myself. If you have a project which was created before warning system was added in Godot, then you'd have to make sure that you actually fix those. That's why I was saying that disabling the warning system could be a feasible solution for you, because it can take a while to fix all those warnings when you have more high-priority stuff to do in your project.

**Comment by groud** [comment] 2019-11-08 12:27
> @groud My issue was never delta giving a warning, it was that the warnings and errors stack up. Could you please re-open this issue ?

What do you mean by "stacking up". Could you please provide a screenshot ? Without precise information it's impossible to solve the problem.

**Comment by AtomaFajrovulpo** [comment] 2019-11-08 18:58
When running normally using the play button in the Editor:
![image](https://user-images.githubusercontent.com/55881826/68502889-71094800-0259-11ea-9fb3-7d619603d1d9.png)
After leaving the game in the background and saving:
![image](https://user-images.githubusercontent.com/55881826/68502931-8f6f4380-0259-11ea-8dd3-82957e0e4fd3.png)
Pressing saving again:
![image](https://user-images.githubusercontent.com/55881826/68502988-b0d02f80-0259-11ea-86b1-6deed395e515.png)
And so on ...

**Comment by groud** [comment] 2019-11-08 19:17
I was able to reproduce the bug. Indeed, if you keep the game running in the background and save, the code warnings are printed again.

**Comment by fisbe** [comment] 2019-12-08 23:46
Hi, I would like to work on this issue. Does anyone have any advice on what classes I should begin looking into?

**Comment by AtomaFajrovulpo** [comment] 2020-02-02 21:58
Fixed in #33429

**Comment by akien-mga** [comment] 2020-02-05 14:17
@AtomaFajrovulpo This commit has never been merged in the master branch though... #34244.

**Comment by AtomaFajrovulpo** [comment] 2020-02-05 22:34
@akien-mga I thought that something wasn't right, but anyway somehow the problem has been fixed in 3.2 stable :/

**Comment by akien-mga** [comment] 2020-02-06 07:41
Åh ok, closing then.

**Closed by akien-mga** 2020-02-06 07:41 UTC
Labels: bug, confirmed, topic:core
