### ISSUE TITLE
Mouse reaction conflict between control nodes and 2D viewport

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#40691] opened 2020-07-25 06:28 UTC
**Godot version:**
Godot 3.2.2 win 64

**OS/device including version:**
Windows 10 x64 (Vega 8 with Ryzen 3)

**Issue description:**
The control nodes stop reacting when there's a viewport 2D scene.

**Steps to reproduce:**
Create a Basic GUI, make a 2D scene.
Create a Viewport, add the 2D scene.
Control nodes on the parent scene will stop working.

**Minimal reproduction project:**
[Editor (GUI).zip](https://github.com/godotengine/godot/files/4974995/Editor.GUI.zip)

There's two scenes (bugged scene and non bugged scene).
Use the two to compare, specially on the bugged scene, click on the center right checkboxes, they don't work, they only work when you click Import Sprites, hit cancel, then the 2D scene inside the viewport dissapears and the checkboxes works.

**Comment by Sauermann** [comment] 2022-11-06 21:08
In your MRP, the `Control` BODY in the `SubViewport` accepts the events, that you are missing in the main viewport.

This is a duplicate of #39666.

**Closed** 2022-11-06 21:11 UTC
Labels: topic:input
