### ISSUE TITLE
Unable to run exported binary on macOS 10.12.4.

### ISSUE THREAD

**Issue by chenzhekl** [godotengine/godot#8498] opened 2017-04-23 14:56 UTC
**Operating system or device - Godot version:** 

macOS 10.12.4, Godot 2.1.3

**Issue description:**

Export a blank scene, and got the following messages when running.

`The application "a.app" can't be opened.`

**Steps to reproduce:**

1. Create a new project.
2. Add a `Control` Node, and save the scene.
3. Export to `Mac` target with default setting.
4. Run the exported binary.

**Link to minimal example project:**

**Comment by chenzhekl** [comment] 2017-04-23 15:08
Found a solution, `chmod +x a.app/Contents/MacOS/*`. May be related to #527.

**Comment by akien-mga** [comment] 2017-04-23 16:35
Duplicate of #527 yes.

**Closed by akien-mga** 2017-04-23 16:35 UTC
