### ISSUE TITLE
SDFGI Exhibits Flickering Artifacts

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#74597] opened 2023-03-08 10:13 UTC
### Godot version

4.0 Stable

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

Transitions into dark areas will sometimes flicker in current SDFGI implementation.
This has presented very strongly in specific areas of my environments, but only specific areas and was thus difficult to track down in a reproducible example.
It is not resolved by using debanding or re-initiating SDFGI.

I've identified a couple areas in the attached MRP that exhibit this issue. They're presented as fairly minor here, but they've been alarmingly present in my own projects and playing around with the SDFGI settings is bound to create some in different areas in this scene.
The issue only seems to occur with camera movement and ~~has not been tested at runtime~~ has now been validated to appear at runtime.
![SDFGIFlickering_01](https://user-images.githubusercontent.com/70243134/223684468-1898b99e-7718-4925-9644-316c26968409.jpg)
![SDFGIFlickering_02](https://user-images.githubusercontent.com/70243134/223685080-27283d9b-d4c4-401c-85c0-9160e1126870.jpg)

### Steps to reproduce

Load MPR and observe areas highlighted above.
Seems to be more present in off-axis geometry but ultimately unsure.

### Minimal reproduction project

[SDFGIFlickering.zip](https://github.com/godotengine/godot/files/10919518/SDFGIFlickering.zip)

**Comment by Calinou** [comment] 2023-03-20 21:34
- Duplicate of https://github.com/godotengine/godot/issues/74633 (this is caused by reflections, even on fully rough materials).

**Closed by Calinou** 2023-03-20 21:34 UTC
Labels: bug, topic:rendering, topic:3d
