### ISSUE TITLE
Toggling AutoLoad flags current scene as unsaved

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#36000] opened 2020-02-08 01:54 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
When toggling an autoload, the current scene's saved status is flagged as dirty and the autoload toggle is added to the undo stack.  This may be intended behavior, but since autoloads are on a global scope, I would've imagined their behavior to be similar to how EditorPlugin enable/disable works (that is, outside of the undo stack).  Probably related to #29000.

**Steps to reproduce:**
I was in the scene's script editor when toggling the autoload, but had to move back to the 2d editor to perform the undo operations and return the scene to its "unchanged" status.  Try toggling an autoload in a similar situation.

**Comment by KoBeWi** [comment] 2020-02-08 12:32
You mean in project settings? Then it's duplicate of #8117

**Comment by Calinou** [comment] 2020-02-08 15:55
Duplicate of #8117.

**Closed by Calinou** 2020-02-08 15:55 UTC
