### ISSUE TITLE
The position of a node is not _ready when used inside any "Container" node

### ISSUE THREAD

**Issue by tocruise** [godotengine/godot#86413] opened 2023-12-22 01:20 UTC
### Tested versions

- Reproducible in Stable 4.2, Windows 10

### Issue description

Any type of "Control" node, when used within any type of "Container" node, fails to provide correct node.position when `_ready` is called. However, `_process` is able to print the correct position, implying there's something happening between `_ready` and `_process` that makes the`node.position` correct.

If a node calls _ready, I think it's fair to assume that the Node's data, including it's `position`, is ready, which in this case it is not. There's no mention in the docs that a node would call _ready, but not actually be ready, so I can only assume this is a bug.

It might also be worth noting in case it's not clear, but it also affects @onready variables too. If you do something like `@onready var panelposition = self.position`, it'll return (0,0) even if it actually does have a position set manually.

### Steps to reproduce

1. Create a new project
2. Create a `CanvasLayer`, and set it to full-rect to fill the screen
3. Add any type of "Container" node (found under `Node > CanvasItem > Control > Container`). I personally used a `MarginContainer`
4. Add any other type 2D node as a child. I personally used a `PanelContainer`, but you can use anything; a TextureRect, Panel, whatever.
5. Make sure you move position this node out of the top left corner. I personally just anchor it to the middle of the parent.
6. Attach a script to this new child (from step 4), and in the `_ready` function print the position of the node. There are several methods, but I used `self.position`. You'll find that it will return (0, 0)
7. Upon right-clicking the MarginContainer, and changing it's type to something other than a Container node, that the console will output the correct value for the child node now. Equally, you can also add a line to the top of the `_process` function of the script we made in Step 6 that returns the position, because as soon as the first `_process` is called, the data is somehow correct.

### Minimal reproduction project (MRP)

[Project.zip](https://github.com/godotengine/godot/files/13747342/Project.zip)

**Comment by tocruise** [comment] 2023-12-22 01:31
I believe this post describes the same issue: https://www.reddit.com/r/godot/comments/pzre3c/rect_position_isnt_giving_me_the_right_value/

**Comment by tocruise** [comment] 2023-12-22 01:48
Sorry, just to add a bit more to this; it seems that `self.position` returns the anchor position when called within _ready, but then in _process returns it's actual transform position (matching the editor known position inside the Node inspector).

- If you take the same project
- Add a normal "Control" node between the MarginContainer and the Child
- Make the child minium 50x50
- Make the new Control node full rect, and then make the child centered on both axis'
- The output in console is (-25,-25) at _ready, but then changes to (-551, 299) at _process (it'll change to [whatever you screen is] / 2 - 25)

**Comment by rsubtil** [comment] 2023-12-22 19:08
> If a node calls _ready, I think it's fair to assume that the Node's data, including it's position, is ready,

Yeah, but that's really happening is that `Container`s defer node sorting (the process of re-positioning the children nodes) to the next frame, so you're not able to know the node's final position at that stage. I agree that this should be documented better.

**Comment by tocruise** [comment] 2023-12-23 07:23
> > If a node calls _ready, I think it's fair to assume that the Node's data, including it's position, is ready,
> 
> Yeah, but what's really happening is that `Container`s defer node sorting (the process of re-positioning the children nodes) to the next frame, so you're not able to know the node's final position at that stage. I agree that this should be documented better.

Maybe it's just me, but that seems like a huge oversight. The `_ready` function, which is arguably the main function of nodes, cannot recall the position of a container node under any circustmances? I feel like the general user assumes that when `_ready` is called, the node has already reached that position, especially when the node editor shows that position in the inspector. You definitely don't expect it to not be in the position that it's been set to by the time `_ready` is called. Sorry, maybe I'm repeating myself here, but I'm just trying to be clear in case this does become part of the docs.

@rsubtil I guess at this juncture, the only thing I can do is work around it. Is there anyway to access that sorting function you mentioned, so that I could include new code? So that, for example, I'd be able to save the position or set the position of a node _after_ it's been re-positioned. Or would the only real way of doing this involve setting up some kind of bool switch in the `process` function that runs once and then switches off for future `process` calls? I ask because if this is genuinely intended behavior, which as you describe it it sounds like it might be, how did the developers of these functions intend for people to get positions of their nodes when they're inside containers? I mean, surely they thought about that. I don't think it's a huge ask to want to to be able to set/get the position of a node when it exists within another one of the most common nodes. I can't imagine that's going to be a rare occurance at all given that Container nodes are so prevalent. I'm genuinely baffled this hasn't been raised before (or maybe it has and I just can't find the thread).

**Comment by tocruise** [comment] 2023-12-24 06:02
Okay, so another day of experimenting and I'm getting there...

I first attempted to use deferred calls, which had it's own set of inconsistencies. For some reason they'd be able to see some variables and not others. As in, if I had a `node.position = x` and a `movenow = true` statement in the same deferred fucntion call, for some reason the `process` function would know the `movenow` bool had updated, but not that the `position` also had. Super weird stuff. I've yet to find an answer as to why that is.

`get_tree().process_frame.connect(XXXXXX, CONNECT_ONE_SHOT);` seems to be the answer to the question above. Seems like a roundabout hacky way to get information that should be able at the get-go, but oh well, here we are. For some reason, this has introduced it's own set of problems, like the `position` of nodes not being correct if their parent is not immediately visible from application launch. As for why that's happening, I have no idea. Another one for the docs. Maybe it's just me, but again, "visible" surely just means not visible, as in, simply not drawn on the viewport. The fact that it also just neglects to do a ton fo other things is really unfuriating - infuriation that wouldn't exist if the docs actually explained what functions did in detail. The "visible" method under CanvasItems in the docs says nothing about this.

It's getting a bit tiresome at this point that so many of these functions work in ways you don't expect them to, and the docs mention nothing of it, so I'm just left to sift through hundreds of github issues and reddit posts, looking for some other unlucky developer who's had the misfortune of trying to do something so basic and primitive in this engine and has not been able to pull it off. Anyway, my answer is here for anyone who stumbles on it. This is how I got around it. I think this'll likely be my last comment until it's picked up and tagged as a bug/improvement.
Cheers

**Comment by rsubtil** [comment] 2023-12-28 10:41
> Is there anyway to access that sorting function you mentioned, so that I could include new code?

This doesn't seem to be exposed to GDScript. There are `pre_sort_children` and `sort_children` signals that might be useful though (https://docs.godotengine.org/en/stable/classes/class_container.html#signals).

About using deferred calls, a cleaner way to do it is to use `await`:
```gdscript
func _ready():
    # Code runs before a frame is processed
    ...
    
    await get_tree().process_frame
    # Code below now runs after a process frame passed
    ...
```
Can you share your use-case for needing to know the node's position? The `Container`'s job is to handle all positioning of it's child elements, so it could be argued that a reliable way to know a final node's position is not needed, and that you might be using the wrong node for what you're doing.

**Comment by AThousandShips** [comment] 2023-12-28 16:33
Duplicate of https://github.com/godotengine/godot/issues/72024

**Closed by AThousandShips** 2023-12-28 16:33 UTC
Labels: discussion, needs testing, topic:gui

**Comment by AThousandShips** [comment] 2023-12-28 16:39
In the future remember the [code of conduct](https://godotengine.org/code-of-conduct/) and remain constructive, this is not the place for venting frustration 🙂

**Comment by tocruise** [comment] 2023-12-29 09:39
I think it's inappropriate to go through thumb-down'ing and emoji reacting to my comments in a negative way, proceeding to inappropriately go against the code of conduct you've just linked by using the same tone I supposedly used, and then closing the discussion. I think if we're all here for the right reasons, which should be to constructively make Godot better, we shouldn't be passive-aggressivly reacting to people's comments and then closing threads as if to say "You're wrong, I'm right. End of discussion. Bye". Text never translates well over the internet because it's missing tone and context, but I was never rude or innappropriate above (I think when you have a moment you should have a quick read through the linked Code of Conduct's "Always assume positive intent from others." section because it describes exactly what you didn't do here). I don't know which bit you seem to have taken so personally, but I'd be interested to know so that I can clarify or reword, and so that I don't make the same mistake of wording it in such an "inappropriate tone" again. We're going off on a slight tangent here, so there's no pressure to answer, but I don't think it would've been fair for me not to at least ask what I did wrong, especially if I'm breaking a rule and I don't even know which one I'm supposedly breaking. I can only chalk it up to my British sarcasm not translating well.

> This is for a very valid and good reason, performance, sorting should only be done once per frame

Yes, despite the sarcastic and condescending "right?", I agree with you (see, you're doing it too, and two wrongs don't make a right. Anyway...). That was never even a point of contention so I don't understand the harsh tone. But yes, that's really good to know. I'm always looking to learn how this engine works and that's fascinating stuff! Just to reiterate again, as is my whole point here, it would be nice if this was documented somewhere. I've no issue with Godot doing things in a very specific and perhaps counterintuitive way, my issue entirely is that it's not documented. `ready` has certain connotations, and when the docs don't fully explain what is considered `ready` and what isn't, you're left to assume. For example, wouldn't it have been great if this whole interaction could've been avoided? I'd love to have been able to get an answer as good as yours without having to prowl github for days, eventually open an issue, and then wait 2 weeks. Maybe it wasn't clear, likely because I absolutely suck at explaining things, but my 'issue' is more in the line of "_why_ does Godot do this, and can we get that '_why_' bit added to the docs".

Thanks again for this insight though, I'll add it to my personal notes for now.

I don't know if I personally agree that it's a duplicate of [72024](https://github.com/godotengine/godot/issues/72024), but I'll accept that it is for the sake of not wanting to cause anymore upset, and close the thread going forward.

@rsubtil Thanks for this solution. This should be a cleaner way of doing things. My primary use case for knowing the position is so that I can animate nodes through code. I can't tween the position of a node if it's position is not correct. Also, after the node no longer needs to be animated, I'd like to return it to it's starting position, which I can't do unless I make a note of it at the start. Does that make sense? I don't know if I explained that very well!.

**Comment by AThousandShips** [comment] 2023-12-29 09:50
First of all I didn't close this for that reason, this is a duplicate 🙂 it's the exact same issue and providing a signal solves both issues

You are reading attitude into my message that isn't there, I'm simply responding to your very clear frustration expressed in non constructive ways, like:
> It's getting a bit tiresome at this point that so many of these functions work in ways you don't expect them to

> I'm genuinely baffled this hasn't been raised before 

> The fact that in the process of not drawing it that it also just neglects to do a ton fo other things is really unfuriating

So I'm sorry you felt I had a bad tone in responding to you, but I genuinely do not intend any such tone and I don't see how you read it into what I am saying, I'm providing a clear and reasonable explanation and responding to your non constructive attitude

Also you reading attitude into my reactions which are related to your breach of the CoC is not passive aggressive, and you first accusing me of things I do not do and then proceed to do so yourself is major projection, please act professional 

Have a good day

**Comment by tocruise** [comment] 2023-12-29 21:10
> You are reading attitude into my message that isn't there.

Crazy how that can happen, huh? Do you not think that perhaps you did that in your first response? To be clear, I'm not being sarcastic here, I'm genuinely curious. Do you not think if your messages can convey an attitude that's not reflective of yourself, that perhaps you could be doing the same thing in reverse?

> and you first accusing me of things I do not do and then proceed to do so yourself is major projection

Wait, what? No, you accused me, then proceeded to do that yourself. Not the other way around. I made my post, you thought I was rude, acted rude yourself, and then hypocritically linked the code of conduct and explained how I was breaking it. But again, see, you're doing it again. You can't say "you're projecting" and then following it up with "act professional". Acting professional, and in line with the CoC, is not acusing others of projecting when they're saying a point you don't think it constructuive, proceeding to misjudge the tone, and then accusing them of going against the Code of Conduct - the same code of conduct that explains you shouldn't just assume someone is being rude and argumentative especially if they've done nothing explicitly to show that. To use an analogy, you can't go up to someone in the street and punch them in the face because you thought you overheard them saying something they didn't actually say, and then when that person goes to punch you back because they think your attack was unjust, you wave the "Assualt and personal bodily harm" laws in front of them like a shield. In other words, enforcing a law or a rule, shouldn't involve the enforcer breaking it too. You can explain what the code of conduct is and how it might've been broken, without defiling it.

At the end of the day, we clearly come from different backgrounds, and you're reading my text, that I'm saying lightheartedly, in a tone you're familiar with, which is making it come across rude. It's happening to both of us, clearly.

To reiterate what I said above, I think if we're talking about what's constructive and professional, I don't think it's constructuve to be thumb-down'ing an asnwer to the main issue. Above, I found a solution to my original question, which was to use deferred calls, and for some reason you've downvoted it. I think it's fair for you to disagree with parts of that statement, but it's objectively an answer to the question, and I don't think downvoting it simply because you disagree with me, even when it's perfectly valid answer, is appropriate or constructive for the community, or for other users looking for an answer to this problem - especially when you don't follow up with why it's wrong, or why you've downvoted it. It comes across like you're doing it because your mad and upset, and not because you're actually trying to be constructive.

To elaborate on those points, and to partially reword them for clarity - because the CoC defines that I should do that if someone is misunderstanding:

> It's getting a bit tiresome at this point that so many of these functions work in ways you don't expect them to

How is that non-constructive? I'm explaining how the docs clearly lack in many regards, and that functions don't behave how you would intuitively expect them to because of it. You can't know what you don't know. If the docs don't explain something, and you assume something else because of it, thats the fault of the docs, not the user. I was originally going to mention which parts of the docs were lacking, but it didn't seem appropriate to mention other parts of the doc when the guidelines for this project state it should be one issue per thread. It would've just muddied the waters too much to start mentioning other parts of the docs that are incomplete, but I still found it appropriate to mention how it's part of a bigger problem without being specific.

> I'm genuinely baffled this hasn't been raised before

I am. That isn't rude. I'm surprised an issue surrounding position has not been raised before, because it seems like getting/setting the position of a node would be almost one of the absolute barebone requirements of a game engine. Would it not? It also eludes to the idea that perhaps I'm doing something wrong. If that's not a normal request, and something the game engine is unable to do, what is the right way to do it? I'm trying to gain an understanding of; if this issue hasn't been raised before, why hasn't it. And look at that, I was actually right, it had been raised before, in the duplicate that you linked, so my surprisement was actually granted.

> The fact that in the process of not drawing it that it also just neglects to do a ton fo other things is really unfuriating

Yes, a function behaving in a way not explained in the docs would lead users to frustration. That's not a statement out of emotion, it didn't even particularly infuriate me personally, I was making the point that it would be confusing and inconsistent for users. That's absolutely constructive. Again, the docs should explain this better. If I had swapped the word "infuriating" for something else, like "confusing", or "inconsistent" would it somehow be more constructive? They're all synonmous for conveying the same emotion in the user...

I think at this point, I don't think we're going to say anything else that's going to be constructive. You clearly just disagree with me, and I disagree with you, and that's okay, I just wish this conversation could've gone differently. I think what we're divulging into is too subjective and discussing it further will just lead to derailing the thread into a conversation about tone of conveying oneself online (even more so than it already has). But in future, I think we'd all benefit if you just didn't go into things being immediately accusatory. Like the Code of Conduct states, you could've asked me to elaborate or re-word something if you took issue with my tone or vernacular, and I would've been happy to do that. The way we both speak clearly just doesn't translate well over text, and that's unfortunate.

Have a great rest of your week/weekend. Cheers.

**Comment by AThousandShips** [comment] 2023-12-29 21:41
Please, take a step back, all I did was tell you to be constructive and not vent your frustration but be constructive, and explained to you in calm and clear ways why this makes perfect sense and how what you expect simply isn't how things do or *could* work, how you turn this into me attacking you or being passive aggressive I can't understand

I simply stated that your *literal expression of frustration* has no place here, and yes, saying "confusing" instead of "infuriating" would be more constructive

You could just have responded to this by saying that you understand that this isn't about your frustration over things, but instead you turned this into two enormous walls of text decrying that I explained and *asked* you to be constructive instead of venting your frustration, or accusing me of closing this issue to silence you, instead of it being a duplicate of another issue that covers this exact topic

Good day

**Comment by AThousandShips** [comment] 2023-12-29 21:53
One final note:
As someone who spend a lot of time with bug evaluation and identification, volunteering my time with no reward other than helping people and making this a better engine, it's not very helpful or enjoyable to see people vent their frustration that things don't work or that things are bad

I understand that it can be frustrating when things don't work as you expect, but that's no reason to vent this frustration here when people are here to help and to explain things

I'm not saying this as a "oh you have to love this engine!", but considering the enormous time of our spare time me and so many others give to this project it's tiresome when people come into these channels with frustration, especially in cases where that frustration is actually not due to anything not working correctly, as in this case

There's a reason why the code of conduct asks that you don't vent frustration but remain constructive, I ask that you respect that

I am sorry that you took my response this personally, but that is genuinely none of my fault, so I ask you to take a step back

Again, have a good day

**Comment by tocruise** [comment] 2023-12-31 00:02
The entirety of your last two comments is literally "venting frustration". If you don't feel like that you're not being rewarded or applauded for contributing, don't do it, but bringing that to this thread is innapropriate. 

> two enormous walls of text decrying that I explained and asked you to be constructive instead of venting your frustration

I don't think that's a particularly fair characterization. You accused me of being frustrated, I asked which bits specifically so that I could reword them to show it was not of frustration, and now the process of me rewording what I said has been denoted to "walls of text decrying..."? I'm damned if I do, and damned if I don't.

Again, what I've explained and reworded several times now is how my original comments were constructuve, and that you're misconstruing it as frustration. The objective intent was that it's not to be taken as frustration, and you're still taking it as frustration unfortunately, even after I've explained it was not to be taken that way. There's just not much I can do about that. If I say "{xyz}", and you say "you _sound_ really frustrated", and I say "no, not at all. I think you just misheard me", and then you turn around and say "no, you _**are**_ frustrated" - how am I supposed to respond to that? I wasn't frustrated, I'm still not frustrated, and your unwillingness to believe that has just left us arguing over semantics, because for some reason you're just absolutely unwilling to even slightly give an inch that you could be wrong, and that you maybe just misread my tone (which you did, because again, I wasn't frustrated). That's just not a particularly fair or proper or way to conduct a conversation. You've just immediately defaulted to "I'm right, and you're wrong", even though as the author of the original text, the intent is on me, not you.

All I ask, for the betterment of the community, is that you politely ask people to rephrase things in future. I think that's a fair request. I can't believe this has really been blown this far out of proportion.

**Comment by AThousandShips** [comment] 2023-12-31 09:38
If you think that I asked for any reward or praise you entirely missed the point 🙁 but that does explain your attitude if you think I'm sharing your entitled attitude

> is that you politely ask people to rephrase things in future. 

Excuse me? I literally said "In the future remember the code of conduct and remain constructive, this is not the place for venting frustration 🙂"

What more do you ask!?

Since you have blocked me I'll end this conversation here, I'd you keep harassing me over this I will report you to the code of conduct team

**Comment by AThousandShips** [comment] 2023-12-31 10:02
Since you have blocked me I assume you won't engage in any further conversation with me

However given your attitude and approach I do consider any further replies here as harassment and will report it to the code of conduct team, this is not productive and you keep making baseless accusations against me, misrepresentations of my words, and outright ignoring what I'm saying

Have a nice day

**Comment by Zireael07** [comment] 2023-12-31 10:17
@tocruise As a 3rd party who has been seeing this pop up in my feed, I can't see how you keep saying AThousandShips is not constructive (nor can I tell why they thought you were just "venting frustration" at first - before the thread was closed)

Thread was closed as a duplicate of another issue, not because of "frustration" or anything like that. AFTER the thread was closed, two of your comments are just rants, "crazy how that can happen" and similar passive-aggressive things.

**Comment by tocruise** [comment] 2024-01-01 02:01
> @tocruise As a 3rd party who has been seeing this pop up in my feed, I can't see how you keep saying AThousandShips is not constructive (nor can I tell why they thought you were just "venting frustration" at first - before the thread was closed)

I mean it's all subjective at the end of the day, but personally, I don't find complaining about how being a volunteer and not being thanked for it is at all relevant to the issue I raised. If there's a need for a literal example of "venting frustration" that has to be it.

> Thread was closed as a duplicate of another issue, not because of "frustration" or anything like that.

I totally get that, and I think my words are being slightly twisted here - or possibly just misunderstood from explanation. What I was saying is that jumping into a conversation and quickly going "btw, you broke the rules by doing this bad thing you did, bye" and then jumping back out is a bit of an unfair way to engage in a conversation. I think the appropriate response would've been to give me opportunity to explain or correct what I said, instead of just immedaitely accusing me of doing something purposefully bad and not allowing me to correct the record. I think they're failing to understand that I was aware of the CoC and never said anything out of frustration, and instead of allowing me to clarify that, I was instead scolded for it. It's like your parents spanking you for cussing, and not giving you the opportunity to explain they simply misheard you say something else. This whole thing has just been a complete misunderstanding, from start to finish. It's effectively "you broke the rules because I _think_ you _meant_ {xyz}".

> AFTER the thread was closed, two of your comments are just rants.

The last comment was a full explanation/re-phrasing of what I'd said, and an acknowledgement that both I and the other user were both clearly not reading eachother's tones correctly, and that they were just getting upset over a non-issue. I just don't think it's fair that I'm being attacked, and then when I try to diligently explain what's been misunderstood (ironically so that it doesn't happen again) I'm being told I shouldn't. "Rant" implies that I'm talking nonsense and shouting wildly, but I've been calm and specific about what's been discussed.

I think it's totally fair for you to subjectively understand it that way, I'm not going to deny you that, but do the same rules not apply to them too? How is their rant about volunteering on Godot any more relevant than me rephrasing what I'd said when I was asked to do so? That doesn't seem like a non-partisan way to judge this conversation, especially when you're both from the same "team" of contributers. I'm effectively fighting a 3-on-1.

"passive-aggressive things."

I'm just pointing out a blatant hypocrisy. As I said before, enforcing the rules shouldn't require breaking them. You can't keep poking someone with a stick, and then when they poke you with a stick back threaten to have them banned. Shouldn't the person who started the stick poking be held somewhat accountable for getting poked back?

I mean, the user is now saying that if I make another comment, any comment at all, **_in my own thread_**, I'm going to be reported for harassment? This would be like me standing in my own house, and someone willingly coming up to my door, and then telling me they're going to report me for harrassment for being in my own home. I'd totally get it if I was going into their house, or their thread, but I raised this issue and I'm now being told that if I comment or clarify information in a thread **I made**, I'm "harrassing" (Some would argue that it's already harrassment if you're diligently going into someone else's thread on a daily occurance to accuse them of things they have not done). This whole thread has been blown way out of proportion, and I just can't understand how we got here. This is a thread I started. If someone makes a comment, or asks a question, I'm going to respond to it because it's the polite thing to do. I'm not forcing anyone to come here, or anyone to respond, and I only comment when someone asks me something or accuses me of something. I've not said anything aggressive, or intentionally hurtful, and I'm certainly not "aggressively intimidating" anyone. I'm happy to let this thread go. Let's just call it a day. I really don't get why it keeps getting re-opened. I've said several times now that this conversation isn't going to be productive, but it keeps getting re-opened.

**Comment by AThousandShips** [comment] 2024-01-01 10:39
You keep lying about me, so I will take this to the code of conduct team, they will arbitrate over this, until then I am locking this thread
