### ISSUE TITLE
Odd behaviour with a cylinder collision shape

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#38426] opened 2020-05-03 06:56 UTC
**Godot version:**
Godot 3.2 commit 8426ed2650ac740796a19d4a28a453db539c0fff

**OS/device including version:**
Windows 10

**Issue description:**
A rigid body with a box collision shape reacts very weird when coming into contact with a static body that uses a cylinder collision shape.

It works fine if that static body has a box collision shape

**Steps to reproduce:**
Create a static body as a cylinder
Create a rigid body with a box shape
Let the rigid body fall on top of the static body but away from its center

Experiment a little with sizes. I found that creating a rectangular box really shows the issue well. 

**Minimal reproduction project:**
This project shows a cylinder collider and box collider side by side with the same rigid body being dropped on it. On the box it nicely falls, on the cylinder it bounces and rolls for no apparent reason

[godot_cylinder_physics_issue.zip](https://github.com/godotengine/godot/files/4569724/godot_cylinder_physics_issue.zip)

This shows it in even more splendor:
https://youtu.be/zp6NubkIbCY

**Comment by pwab** [comment] 2020-05-04 04:23
Maybe related to #27212

**Comment by BastiaanOlij** [comment] 2020-05-04 11:12
> Maybe related to #27212
Very likely the same issue... It brings back the age old discussion about the margins in Bullet not being very friendly to VR work where we often work with centimeter sized objects.

**Comment by Calinou** [comment] 2020-05-05 15:11
Duplicate of #16505.

**Closed by Calinou** 2020-05-05 15:11 UTC
Labels: bug, topic:physics
