### ISSUE TITLE
Script editor, Replace. Left to right selected word not replaced

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#55994] opened 2021-12-16 15:18 UTC
### Godot version

Godot v3.4.stable.official [206ba70f4]

### System information

Windows 10 21H1

### Issue description

In the Script editor.
Pressing the Replace button, should replace the left to right selected word,
instead of the next occurrence.

### Reproduction steps:
- create or open a script
- copy/paste:
```
func abc_one():
    pass

func abc_two():
    pass
    
func abc_three():
    pass
```

- select (from left to right) the letters "abc" in the first function "abc_one"
- press `ctrl r` to open the find/replace panel at the bottom.
The selected word appears in the find input box,
and the cursor blinks in the replace input box.
- type a replacement word: "def"
- press the Replace button

### Observed
The first function name "abc_one" remains unmodified.
The second function name "abc_two" changed to "def_two".
"abc" is selected in the third function name "abc_three".

### Expected
The first function name "abc_one" should have changed to "def_one",
since it was selected.
The second function name "abc_two" should have "abc" selected.

### Cause
The replace operation replaces the next occurrence,
following the cursors current position.

Selecting "abc" in the first function name "abc_one":
- From left to right, leaves the cursor after "abc".
Therefore the replace operation finds the next occurrence in the second function name "abc_two".
- From right to left, leaves the cursor before "abc".
Therefore it replaces the selected word as expected.

### Note
Double left mouse button clicking selects a word, but it leaves the cursor at the end of the word.

### A possible solution
Maybe the replace operation should start looking for the next occurrence,
from the beginning of the selection.

**Comment by KoBeWi** [comment] 2022-01-01 16:46
Duplicate of #33315

**Closed by KoBeWi** 2022-01-01 16:46 UTC
Labels: enhancement, discussion, topic:editor, usability
