### ISSUE TITLE
Crash whenever the signature of a static method on a class_name class with no extends can be compiled

### ISSUE THREAD

**Issue by Eclextic** [godotengine/godot#96282] opened 2024-08-29 11:50 UTC
### Tested versions

- Tested on v4.4 dev 1 mono (v4.4.dev1.mono.official [28a72fa43])
- I did not get this crash before that version

### System information

Godot v4.4.dev1.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 Threads)

### Issue description

It's a crash, also title

### Steps to reproduce

1. Create a class with the class_name keyword
2. Give it a static method
3. Fill the signature of the static method from a different class (in this case extending Node)
4. See the entire editor crash silently

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/user-attachments/files/16798521/bug.zip)

Open the project, go into the script (`ScriptBNode`) that doesn't compile and type `true` as the function's parameter to try to get it to compile

**Comment by Eclextic** [comment] 2024-08-29 11:57
This bug easily fkn happens whenever anyone uses a Utils class...

Please fix this quickly as it is extremely reliable to produce (on my machine anyways) and it's obnoxiously annoying to work with. Using an external editor doesn't fix the problem and only when *saved* with the external editor and *after* opening Godot with the saved file, does it not crash anymore, i.e. only when Godot doesn't try to recompile that specific line...

**Comment by AThousandShips** [comment] 2024-08-29 12:07
You'll find that you get more help if you're polite and less demanding

Also I can't get this to happen, following your instructions, nothing crashes, so this doesn't "easily fkn happen"

Please provide more details as this isn't enough to replicate this bug

**Comment by AThousandShips** [comment] 2024-08-29 13:35
This is a duplicate of:
* https://github.com/godotengine/godot/issues/96239

Which has already been fixed, the fix will be available in dev2 or if you build from source

**Closed by AThousandShips** 2024-08-29 13:35 UTC
Labels: bug, topic:gdscript, needs testing, crash

**Comment by Eclextic** [comment] 2024-08-29 16:41
That's why I haven't seen it reported xd

(has it really been fixed this fast??? 👏🏼👏🏼👏🏼)

**Comment by AThousandShips** [comment] 2024-08-29 16:47
We have a very fast fix time some times! Always good to search closed issues as well! And no problem!
