### ISSUE TITLE
Godot 3.2 beta6 viewport rendering bug

### ISSUE THREAD

**Issue by kruglinski** [godotengine/godot#35042] opened 2020-01-12 08:36 UTC
**Godot version: 
Godot 3.2 beta6

**OS/device including version:**
OS: Microsoft Windows [Ver 10.0.17763.914]
Video card: NVIDIA GTX 960

**Issue description:**
When switch to gles2 renderer, editor viewport always display solid object

GLES 3 viewport rendering
![gles3_normal](https://user-images.githubusercontent.com/2869425/72216227-7042aa00-3559-11ea-9f2b-0b5afabdb970.png)
![gles3_wireframe](https://user-images.githubusercontent.com/2869425/72216226-6faa1380-3559-11ea-9f6c-4687b90333f7.png)
![gles3_overdraw](https://user-images.githubusercontent.com/2869425/72216228-72a50400-3559-11ea-98ba-460adb7d9bc8.png)
![gles3_unshaded](https://user-images.githubusercontent.com/2869425/72216230-759ff480-3559-11ea-9649-a5f83e49301e.png)

GLES 2 viewport rendering
![gles2_normal](https://user-images.githubusercontent.com/2869425/72216233-83557a00-3559-11ea-8fd2-0a7c4eca7627.png)
![gles2_wireframe](https://user-images.githubusercontent.com/2869425/72216236-86e90100-3559-11ea-8201-ea7cb4153ba3.png)
![gles2_overdraw](https://user-images.githubusercontent.com/2869425/72216237-8a7c8800-3559-11ea-8cba-2884be53e6a8.png)
![gles2_unshaded](https://user-images.githubusercontent.com/2869425/72216238-8d777880-3559-11ea-8267-85ccad828090.png)

**Steps to reproduce:**
1.switch to gles 2 renderer
2.try viewport rendering options to see this issue

**Minimal reproduction project:**
[fbx_test.zip](https://github.com/godotengine/godot/files/4050410/fbx_test.zip)

**Comment by bojidar-bg** [comment] 2020-01-12 08:44
Duplicate of #27018.

**Closed by bojidar-bg** 2020-01-12 08:44 UTC
