### ISSUE TITLE
Godot4: Orthographic camera3d returns different depth result in shader from Godot3 

### ISSUE THREAD

**Issue by linnal** [godotengine/godot#66007] opened 2022-09-17 21:13 UTC
### Godot version

4.0-beta1

### System information

Linux

### Issue description

I'm porting a silhouette shader from Godot 3 to 4 and I may have found a regression. 
The shader works as expected if the camera is using a perspective projection but not if I change to an orthoganal one. 
In Godot 3.5 it works in both modes. 

#### Godot 3 shader
```glsl
void fragment( ){
  float depth = texture(DEPTH_TEXTURE, SCREEN_UV).x;
  vec3 ndc = vec3(SCREEN_UV, depth) * 2.0 - 1.0;
  vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
  view.xyz /= view.w;
  float linear_depth = -view.z;

  float vz = -VERTEX.z;

  ALBEDO = color.rgb;
  ALPHA = color.a * float( vz > linear_depth + bias);
}

```

#### Godot 4 shader
```glsl
void fragment( ){
  float depth = texture(DEPTH_TEXTURE, SCREEN_UV).x;
  vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth);      
  vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
  view.xyz /= view.w;
  float linear_depth = -view.z;

  float vz = -VERTEX.z;

  ALBEDO = color.rgb;
  ALPHA = color.a * float( vz > linear_depth + bias);
}
```

### Steps to reproduce

I uploaded a zip file with 2 sample projects, one for Godot 3 and one for Godot 4. 
If you run the project, by pressing ENTER you will toggle between the 2 camera modes. 
You can also view this from the editor, by changing the projection. 

### Minimal reproduction project

[GodotoShaderIssue.zip](https://github.com/godotengine/godot/files/9592610/GodotoShaderIssue.zip)

### Godot 3.5 Orthographic projection - working as expected
![3 5_ortho](https://user-images.githubusercontent.com/4586189/190876317-434b41ee-b540-4386-a4cf-05fbd72ed75d.png)
### Godot 3.5 Perspective projection - working as expected
![3 5_persp](https://user-images.githubusercontent.com/4586189/190876318-b63f8f3d-ef9d-4711-ba17-22d244922497.png)
----
### Godot 4 Orthographic projection - NOT working
![4_ortho](https://user-images.githubusercontent.com/4586189/190876322-6cb931a5-d101-476f-97e3-6ab922632a99.png)
### Godot 4 Perspective projection - working as expected
![4_persp](https://user-images.githubusercontent.com/4586189/190876323-d043917e-6567-458a-bf8f-bf036ec560ac.png)

**Comment by Calinou** [comment] 2022-09-17 23:21
This is probably not a bug. The `DEPTH` value's range was changed to conform to the Vulkan specification: https://github.com/godotengine/godot/issues/61065#issuecomment-1127098250

**Comment by linnal** [comment] 2022-09-18 08:25
> This is probably not a bug. The depth value's range was changed in 4.0 to conform to the Vulkan specification: [#61065 (comment)](https://github.com/godotengine/godot/issues/61065#issuecomment-1127098250)

It is taking into account the new value range, I followed [the doc](https://docs.godotengine.org/en/latest/tutorials/shaders/advanced_postprocessing.html#depth-texture).

This in Godot3 `vec3 ndc = vec3(SCREEN_UV, depth) * 2.0 - 1.0;`  was changed in this `vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth); ` in Godot 4. 

For convenience I added the 2 shaders in the description above.

**Comment by iiMidknightii** [comment] 2022-12-16 19:16
Don't know how much it helps to add to this, but I'm seeing the same behavior.  I'm trying to replicate the volumetric clouds shader from a Sebastien Lague video, and while I get results with a perspective Camera3D, I get no results with an Orthographic Camera3D.

**Comment by Scony** [comment] 2023-01-06 20:58
I think this is the same issue as https://github.com/godotengine/godot/issues/68878
@linnal try changing `INV_PROJECTION_MATRIX` to `inverse(PROJECTION_MATRIX)`

**Comment by EntroPiGames** [comment] 2023-02-21 15:52
Could this also be the reason why the `Proximity Fade` and `Linear Scene Depth` visual shader nodes don't work when using an orthographic camera in Godot 4 rc 2?

**Comment by npip99** [comment] 2023-11-22 22:38
Definitely a duplicate, can we close this in favor of https://github.com/godotengine/godot/issues/68878?

**Closed** 2023-11-22 22:55 UTC
Labels: topic:shaders, topic:3d
