### ISSUE TITLE
Regression on altas texture packing at export - Godot 2 - commit bbf6694

### ISSUE THREAD

**Issue by Guaranapps** [godotengine/godot#19307] opened 2018-06-01 16:28 UTC
**Godot version:**
2.1.4

**OS/device including version:**
Archlinux

**Issue description:**
There is a regression in packing texture on altas at export.
Packing seems to be less square as before.
It seems that commit bbf66945e7cebfbd3141e8ef3d4fe1e712b1f241 introduce this regression (https://github.com/godotengine/godot/pull/10604)

Here is packing before commit (atlas is 990x641) -> require 1024x1024 texture :
![packing_before](https://user-images.githubusercontent.com/33926763/40850910-26f4ab78-65c6-11e8-8f29-93c86ffdc52a.jpg)

Here is packing with commit (atlas is 230x3525) -> require 256x4096 texture (some device doesn't support 4096 texture):
![packing_after](https://user-images.githubusercontent.com/33926763/40852091-9b85968e-65c9-11e8-9fdb-47586bb06f23.jpg)

**Steps to reproduce:**
Se below for project to reproduce bug, just go in export and generate altas preview:
bad size is 4096x512 and expected size is 1024x2048

**Minimal reproduction project:**
[PackingExportBug.zip](https://github.com/godotengine/godot/files/2063429/PackingExportBug.zip)

**Comment by akien-mga** [comment] 2018-09-18 11:18
@DrMoriarty This is apparently caused by #10604, can you help debug/fix the regression?

**Comment by akien-mga** [comment] 2018-09-18 13:59
Fixed by #22215.

**Closed by akien-mga** 2018-09-18 13:59 UTC
Labels: bug, topic:editor

**Comment by Guaranapps** [comment] 2018-09-18 14:30
Thank you very much, I just test with my original textures and it works perfectly! :+1:
