### ISSUE TITLE
I can't use AtlasTexture on AnimatedTexture on buttons (TextureButton)

### ISSUE THREAD

**Issue by MasTho0128** [godotengine/godot#43581] opened 2020-11-15 23:12 UTC
Godot version:
3.2.2 Stable

Godot Engine v3.2.2.stable.official
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 4600
OpenGL ES 2.0 Batching: ON

I have an animation in sprite sheet and when I upload it all and cut it with atlas in pixel snap mode it does not play the animation

Steps:
1: Create a node type texturebutton
2: Add in normal texture and give new animated texture
3: select all the frames you want in the atlas mode and crop the image
4: run and check that the animation does not run.

**Comment by Calinou** [comment] 2020-11-15 23:43
Duplicate of https://github.com/godotengine/godot/issues/30295. AtlasTexture currently doesn't support animation.

**Closed by Calinou** 2020-11-15 23:43 UTC

**Comment by MasTho0128** [comment] 2020-11-15 23:50
> Duplicado de [# 30295](https://github.com/godotengine/godot/issues/30295) . AtlasTexture actualmente no admite animación.

Well, I'll do it with animatedsprite, I hope that in the future you can include animation with atlastexture
