### ISSUE TITLE
Program closes when I use the shift key to select two nodes

### ISSUE THREAD

**Issue by Appsmofera** [godotengine/godot#4002] opened 2016-03-09 23:18 UTC
**Operating system or device:**
Mac

**Issue description** (what happened, and what was expected)
Program closes when I select the second node using the shift key

**Steps to reproduce:**
Just select tow nodes using the shift key

**Link to minimal example project** (optional but very welcome):
Happens in every project

**Comment by freemanfromgodotengine** [comment] 2016-03-10 01:40
Can't reproduce on Linux. Godot compiled 3 days ago.

**Comment by akien-mga** [comment] 2016-03-10 05:34
Probably a duplicate of #3541.

**Closed by akien-mga** 2016-03-10 05:34 UTC
Labels: bug, topic:editor
