### ISSUE TITLE
Inconsistent behavior of Tab key in editor

### ISSUE THREAD

**Issue by bfedie518** [godotengine/godot#67598] opened 2022-10-18 23:08 UTC
### Godot version

4.0 beta 3

### System information

Windows 10

### Issue description

The tab key behaves inconsistently when shifting focus between fields in the editor.  This is a regression from 3.5. 

**Godot 3.5.1:** 
![godot3_tab_key](https://user-images.githubusercontent.com/17280776/196559843-3141da62-338a-442d-a982-586f6508d0bb.gif)

**Godot 4.0 beta 3:** 
![godot4_tab_key](https://user-images.githubusercontent.com/17280776/196560331-9f06dbca-32e0-4a29-9f8c-0354cdcec706.gif)

In the 3.5 example, each time I pressed tab the next option was selected for editing.  

In 4.0, I:
1. Selected position.x with the mouse then pressed tab.  Position.y was focused (but not selected) and position.x was not deselected.
2. Pressed tab a few more times.  Nothing happened.  Position.x remained selected and position.y remained focused.
3. Pressed enter to confirm position.x
4. Pressed enter to select position.y
5. Pressed tab.  Position.y was deselected and size.x was focused (but not selected).
6. Pressed tab.  Size.y was focused but not selected.
7. Deselected everything with the mouse and re-selected position.x
8. Pressed enter to confirm position.x.
9. Pressed tab.  Position.y was focused but not selected.
10. Pressed enter to select position.y.
11. Pressed tab.  Size.x was focused while position.y stayed selected.  This is different than what happened in step 5.
12. Pressed enter to confirm size.x.
14. Pressed tab.  Size.y was selected for editing.

### Steps to reproduce

Select fields and try to tab through them.

### Minimal reproduction project

N/A  Happens in editor no matter the project.

**Comment by Calinou** [comment] 2022-10-19 22:34
Duplicate of https://github.com/godotengine/godot/issues/37723 (same cause).

**Closed by Calinou** 2022-10-19 22:34 UTC
