### ISSUE TITLE
move_and_slide() Collision Issues

### ISSUE THREAD

**Issue by froggestspirit** [godotengine/godot#69884] opened 2022-12-11 00:01 UTC
### Godot version

4.0 Beta 8

### System information

Linux

### Issue description

move_and_slide appears to catch on seams of a StaticBody3D model when the CollisionShape3D scale transform isn't uniform.

### Steps to reproduce

Create a StaticBody3D (something like a game level), create a CharacterBody3D, with a CollisionShape3D (I tested with sphere and capsule) child (maybe also a sphere for visibility). Add a script to move the CharacterBody3D, test. Right now, the character should move around without any issues.

Next, in the CollisionShape3D, unlink the uniform scaling in transform, and scale any of the axis, so it's not equal to the other axis (like X = 1, Y = 1.2, Z = 1) and test. The character should now jitter, or occasionally get stuck when moving over seams of the StaticBody3D

In the attached example, Y scale for the CollisionShape3D is set to 2.2, so it should be problematic when testing.

### Minimal reproduction project

[platformer.zip](https://github.com/godotengine/godot/files/10201211/platformer.zip)

**Comment by Zireael07** [comment] 2022-12-11 09:17
Scaling collision shapes is definitely something to be avoided!

**Comment by Calinou** [comment] 2022-12-29 19:47
Duplicate of https://github.com/godotengine/godot/issues/5734 (same cause). Scaling PhysicsBodies isn't supported, especially in a non-uniform manner. Uniform scaling may eventually be supported, but it's very unlikely that non-uniform scaling will ever be supported.

In most cases, can resize the shape's extents instead – make sure it's made unique first, so that other instances are not affected. You can use `duplicate()` for this in a script.

**Closed by Calinou** 2022-12-29 19:47 UTC
