### ISSUE TITLE
Sometimes the proprties of the control is not updated in the inspector

### ISSUE THREAD

**Issue by DavidTzur** [godotengine/godot#49393] opened 2021-06-07 16:22 UTC
ver: 3.3.2

Case number1:  
1. When changing the anchor points by anchor point handler (changing the position of one of the four small green "arrows")
the margin properties should change accordingly. It indeed happens but it is not immediately reflected in the Inspector.
The same happens when using the "keep ratio" command.    (Probably similar reasons).
2. Similar to 1, when changing anchor by the handler, and then pressing ctrl-z (undo) the change is not reflected in margin properties inside the inspector.  (Need to press on something else and back on the control object)

**Comment by Calinou** [comment] 2021-06-07 16:36
Duplicate of https://github.com/godotengine/godot/issues/49004 (same cause).

**Closed by Calinou** 2021-06-07 16:36 UTC

**Comment by DavidTzur** [comment] 2021-06-07 16:54
Ok,
However, The first case is not mentioned there.  (But maybe the reason is the same, I don't know...)
