### ISSUE TITLE
MultiMesh: setting visible_instance_count is ignored after the first frame

### ISSUE THREAD

**Issue by vfig** [godotengine/godot#62809] opened 2022-07-07 08:57 UTC
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 10; NVidia GTX 1060; Vulkan.

### Issue description

I am trying to dynamically change how many instances of my multimesh get drawn, by setting `visible_instance_count` each frame, according to what my game needs. But this only works on the first frame; on subsequent frames, `visible_instance_count` is updated (as reading the property back confirms), but the number of instances drawn remains the same as on the first frame, neither more nor less.

### Steps to reproduce

1. Run the MRP.
2. Wait two seconds for the visible_instance_count to start being incremented each frame (and printed to the console).
3. Note that the number of visible cubes does not change accordingly.

### Minimal reproduction project

[bug_multimesh_visible_instances.zip](https://github.com/godotengine/godot/files/9061936/bug_multimesh_visible_instances.zip)

**Comment by vfig** [comment] 2022-07-08 15:45
I think #45862 is probably due to the same cause. Maybe #56357 as well?

Further background: I encountered this problem because I expected that setting visible_instance_count would be essentially free to do every frame, only changing the number of instances passed in to the relevant draw calls. So I was surprised to find that there was some kind of caching behaviour going on with it. I take it that visible_instance_count is cached in order to rebuild the AABB when it changes? The discussion of the unexpected performance implications of automatic AABB rebuilding (instead of requiring a suitable custom AABB to be provided) over in godotengine/godot-proposals#957 seems relevant.

**Comment by Syntaxxor** [comment] 2022-09-22 21:59
I'm able to replicate this in 4.0.beta1, though there's a (rather inefficient) workaround of just setting `instance_count` instead.

**Comment by JonqsGames** [comment] 2022-11-30 14:00
Just faced this issue on the current master branch. The fix explained by @rburing is working well. I'm not sure to fully understand the reason why it could not be implemented as is. If there is a performance issue i think we should do it anyway since this feature is avaible whith other renderer (gles3 and mobile handles the change on the fly from what i see in the code) and open a new ticket for further optimization.

**Comment by phire** [comment] 2022-12-09 21:02
Also just encountered this on current master.

I tested and it's not just a vulkan bug, it's appears to be a regression that effects the gl_compatibility backend too. I suspect it dates back to #44838 when the dependency changed notifications were split up.

@rburing's fix appears to be the correct approach. Discussions about performance are red herrings, the bug needs to be fixed.   
Though, it could be optimised slightly by modifying  `_multimesh_mark_all_dirty` to take a range so that only the extra elements between the old and new counts are marked as dirty.

**Closed** 2023-02-03 23:42 UTC
Labels: bug, topic:core, topic:rendering, topic:3d
