### ISSUE TITLE
Small Rectangle Shape Behavior

### ISSUE THREAD

**Issue by eldidou** [godotengine/godot#38043] opened 2020-04-20 12:53 UTC
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When using rectangleShape with a small scale (when the RectangleShape _extents_ multiplied by the collision shape _scale_ is equal to 0.5 or less), if the shapes are subject to forces (like gravity) they overlap (among themselves, and with other PhysicBodies).
This is does not happen when the shape is just slightly bigger (0.6 for example), or when using another collision shape (CircleShape for example)
![Screenshot from 2020-04-20 14-01-12](https://user-images.githubusercontent.com/7119609/79752254-4b0dc680-8314-11ea-9833-b9837511a1ea.png)

**Steps to reproduce:**

- Create several (~5) RigidBody2D
        with a RectangleShape with an extents of 0.5
        with same transform.y value
        slightly spaced on the x axis
- Reduce the default gravity to 5
- Add a StaticBody below the rigid bodies

**Minimal reproduction project:**
[rectangleShapeOverlap.zip](https://github.com/godotengine/godot/files/4503515/rectangleShapeOverlap.zip)

**Comment by pwab** [comment] 2020-05-03 14:53
I was able to reproduce this with your sample on my Windows 10 machine. I was able to stop the bodies from sinking by manipulating the `physics_fps` parameter in ProjectSettings to a value way beyond 120 (try 1000 if you want).

By the way this problem is known for quite a while:
https://www.reddit.com/r/godot/comments/7w5i47/physics_low_accuracy/

So this seems to be a duplicate of #16505.

**Comment by Calinou** [comment] 2020-05-03 17:30
Duplicate of #16505 and #2092.

**Closed by Calinou** 2020-05-03 17:30 UTC
Labels: bug, topic:physics
