### ISSUE TITLE
Double clicking a node in the Scene tab doesn't always register to rename it.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#6670] opened 2016-10-01 13:58 UTC
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.2 alpha (September 30th)

**Issue description** (what happened, and what was expected):
When double clicking a node in the Scene tab the node will be centered in the 2D or 3D panel, and it wont open the dialog to change the node's name. I have to double click it again, and even then sometimes it doesn't register. Sometimes I have to double click several times before it will let me change the node name. Double clicking should only be used to rename a node, not to center it in the view, we can already press the "F" key to focus on the selected node. And as far as I can tell there's no shortcut or button in the right click menu of a node to rename it, so double clicking is the only way.

**Steps to reproduce:**
Try to double click a node in the Scene tab.

**Comment by vnen** [comment] 2016-10-01 15:52
Duplicate of #6452.

**Closed by vnen** 2016-10-01 15:52 UTC
