### ISSUE TITLE
Windows release export crashes on scene change

### ISSUE THREAD

**Issue by lorenzo-arena** [godotengine/godot#75422] opened 2023-03-28 11:33 UTC
### Godot version

4.0.1.stable

### System information

Windows 11, Ryzen 3700U Vega 10 iGPU

### Issue description

I'm having a lot a problems with the release export of my game on Windows. Running the game from the editor or exporting it as debug doesn't present the issue.

One of the problems seems to be already tracked https://github.com/godotengine/godot/issues/70910, but after removing some of the objects in a GridContainer I'm still getting crashes (not always) on scene change. I've enabled file logs and only sometime I get the following lines reported in the log; other times no error is reported.

```
USER ERROR: Condition "!canvas_item" is true.
   at: canvas_item_clear (servers/rendering/renderer_canvas_cull.cpp:1642)
```

I've not tried to reproduce the issue in a minimal project but I can try if it's necessary.

### Steps to reproduce

- create various scenes with many UI elements and containers
- do a release export of the game (for Windows, not sure if the same happens on Linux)
- run the game and switch between such scenes
- randomly, but typically after 4-6 scene changes the game crashes

### Minimal reproduction project

N/A

**Comment by saipheblue** [comment] 2023-06-28 22:00
So glad I found this topic  was going mental because the game crashed 4/5 times on scene change and I had no idea why. Can confirm this is happening only during windows export without debug. With debug it all works. And only with scenes with many nodes in my small project with just scene change button it works flawlessly.
v4.0.stable.official [92bee43ad]

**Comment by gmjosack** [comment] 2023-07-08 20:00
I've also run into this. Only solution I've found is to not use the change scene methods and instead have a master node just manage child node changes. I've also seen this pop up semi often for people in various game dev discord help channels.

**Comment by Calinou** [comment] 2023-07-09 13:11
@lorenzo-arena @saipheblue @gmjosack Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by gmjosack** [comment] 2023-07-09 15:57
Spent a while trying to pull things out of a project where I've experienced this but as I remove more functionality it stops crashing and haven't been able to find a decent minimal reproduction. Will continue to attempt to find something.

**Comment by gmjosack** [comment] 2023-07-09 18:40
I've managed to get something the crashes fairly regularly but not super consistently. 

This project is setup with a player that can move with arrows and a keybind of `r` to restart the scene. When restarting the scene sometimes the game will crash. My best success at reproducing is to hold a direction with the arrows and tap `r` to restart and it will occasionally crash. hooking up xdb64 it seems to crash in something related to creating a thread? The crashes were more frequent in my actual game projects and they're intermittent so it seems like some kind of race condition possibly.

Note: I only see crashes in non-debug builds on Windows. Running the project in the editor and Debug builds on windows never crash.

[minimal-crash-repro.zip](https://github.com/godotengine/godot/files/11995862/minimal-crash-repro.zip)

**Comment by akien-mga** [comment] 2023-07-11 14:47
Related to:
- #75802
- #78788
- #70910

Didn't test to confirm if it would be a duplicate of any of those.

#78988 may fix them / this issue too.

**Comment by gmjosack** [comment] 2023-07-16 15:31
I continue to see reports about this in the Godot help channels so adding a quick workaround here so people can see it when linked this issue:

Having a node that manages scenes for you instead of using the change scene functions seems to be an effective workaround.

Add a signal you can access from anywhere. If you don't already have an autoload you can add a new script such as `events.gd` with the following:
```gdscript
extends Node

signal change_scene(path_to_scene)
```
and add is as an autoload called `Events`. 

Make a new scene with a Node as a base called `SceneManager`.
Add your existing Main Scene as a child of the `SceneManager`and make `SceneManager` your new Main Scene.
Add a script the the `SceneManager` with the following:

```gdscript
extends Node

func _ready():
	Events.change_scene.connect(_change_scene)


func _change_scene(path_to_scene):
	for child in get_children():
		remove_child(child) # Crashes without explicitly removing from the scene.
		child.queue_free()

	var new_scene = load(path_to_scene).instantiate()
	add_child(new_scene)

```


Then whenever you need to change scenes you can just use the following code:

```gdscript
Events.change_scene.emit("res://path/to/new/scene.tscn")
```

**Comment by YuriSizov** [comment] 2023-07-26 16:53
This is likely fixed by https://github.com/godotengine/godot/pull/78988. The fix will be available for public testing in dev2, or you can compile the current master branch and test that. Let me know if the issue is still relevant after the fix and we can reopen it.

**Closed by YuriSizov** 2023-07-26 16:54 UTC
Labels: bug, platform:windows, confirmed, crash, topic:export

**Comment by Fizzzo42** [comment] 2023-09-10 12:13
@gmjosack 's workaround worked. Still a problem with 4.1.1

**Comment by greenya** [comment] 2023-10-06 23:26
This is still a problem in 4.1.2 for Windows Desktop Release build.

**Comment by Calinou** [comment] 2023-10-06 23:40
As mentioned in the above comment, the fix is only in 4.2.dev currently. It hasn't been cherry-picked to 4.1.x yet, but this is planned as per the `cherrypick:4.1` label on https://github.com/godotengine/godot/pull/78988.

**Comment by YuriSizov** [comment] 2023-10-07 11:33
Note that the label doesn't mean it's planned. It's only considered, but since this is a core change, it may be better to leave it be and suggest you update to 4.2 instead.

**Comment by greenya** [comment] 2023-10-07 11:51
> Note that the label doesn't mean it's planned. It's only considered, but since this is a core change, it may be better to leave it be and suggest you update to 4.2 instead.

Thank you for response.

I actually have tried 4.2.dev6 version yesterday i have even bigger issues with it. It doesn't crash on scene changes but it has some issues with animation (in my simple game character has couple of run animation frames, in 4.2.dev6 they are just 1 frame, some character seems like slide without animation), also input keys (they sometimes stuck in pressed state). So i guess i will use 4.1.2 for now and Debug build for Windows platform.

**Comment by KccbzZ** [comment] 2023-10-24 11:53
Omg this is so exciting. @gmjosack 's workaround seems to have saved my first big project that I worked on for ages. I have never really exported any of my projects so far, so now that I ran into this issue, I felt hopeless about it for the past week or so.

I'm super grateful that you posted this workaround here! I'm very shaky about actually believing my eyes that there's no errors in my release build and that it ACTUALLY doesn't crash haha!

Thank you so much for posting this, super grateful for you!! :D

**Comment by YuriSizov** [comment] 2023-11-16 19:37
@Benardus Yes, that is correct.

**Comment by Lippanon** [comment] 2023-11-18 14:45
v4.2.rc.custom_build [80de898d7]
I'm crashing on release only, Windows 64bit. When opening through cmd there is no error or anything, it just crashes. Can this be reopened? Or https://github.com/godotengine/godot/issues/79318? I don't see any errors in debug and verbose doesn't help either so I'm not sure what to do.

**Comment by YuriSizov** [comment] 2023-11-20 12:25
@Lippanon Please open a new report with as much information as you can provide. A crash can happen for any number of reason, and from your description there is no link to either issue at this time.
