### ISSUE TITLE
OpenGL: 3D MSAA crashing Meta Quest 2 OS when using compatibility mode

### ISSUE THREAD

**Issue by talesrt** [godotengine/godot#93349] opened 2024-06-19 13:22 UTC
### Tested versions

4.3 beta 1

### System information

Oculus Quest 2 - Godot 4.3 - Compatibility

### Issue description

When using compatibility mode for rendering and applying any kind of MSAA antialiasing the game makes the OCULUS Quest 2 hardware go to 100% Gpu and instantly crashes the OS. Problem happens when using Remote build.

### Steps to reproduce

- Create a project on godot 4.3 with compatibilyt render mode
- Create a Scene 
- In the antialias options inside project settings:
- Pick MSAA to 2x (or any other)
- Do a remote deploy direct to oculus quest 2
- Wait for the installation of the apk in the oculus
- 100 % GPU and crash

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment] 2024-06-19 13:27
CC @godotengine/xr

**Comment by dsnopek** [comment] 2024-06-19 13:45
Hm, I've got two personal projects using Godot 4.3-beta1, that I'm running with the compatibility renderer and MSAA 2x on the Quest, which run fine. I just re-tested one of them on the Quest 2, since I mostly test with Quest 3, and it works fine on that headset as well.

Can you share an MRP?

**Comment by BastiaanOlij** [comment] 2024-06-24 06:19
Same question as @dsnopek , been running this config for a long time without issues but mostly testing on Quest 3 but also recently on Pico 4. So there has to be something else at play here.

Also it would be interesting to see if https://github.com/godotengine/godot/pull/93530 resolves this, simply because it removes a bug that introduces a serious performance drain.

**Comment by matheusmdx** [comment] 2024-06-24 10:41
Maybe related to https://github.com/godotengine/godot/issues/92910#issuecomment-2181941214

**Comment by m4gr3d** [comment] 2024-06-27 14:47
> Maybe related to [#92910 (comment)](https://github.com/godotengine/godot/issues/92910#issuecomment-2181941214)

Yeah I think it's a duplicate of the issue referenced above.
@talesrt that issue should be resolved in 4.3 beta 2.

**Closed** 2024-08-20 10:50 UTC
Labels: bug, platform:android, topic:rendering, topic:xr, crash
