### ISSUE TITLE
KinematicBody move_and_slide never slides on Plane shape

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#16431] opened 2018-02-05 21:43 UTC
**Godot version:** Godot 3.0 Stable

**OS/device including version:** Arch Linux

**Issue description:**

Move and slide totally fails to move, at least when on a plane collision
As a bonus, move_and_collide never returns what it collided with

**Steps to reproduce:**
1. Create plane collision (static body)
2. Create KinematicBody cube
3. Move cube above plane
4. move_and_slide(Vector3(1, -1, 0))
5. Cube stops when hitting the floor, other functions reporting collides/slides/etc show 0 done
6. Switch to move_and_collide, print return value, notice that it returns null *always*

**Minimal reproduction project:**

[MoveSlideBug.zip](https://github.com/godotengine/godot/files/1696879/MoveSlideBug.zip)

**Extra notes:**
Speculation: move_and_slide breaks due to move_and_collide never returning a collision, so it thinks it's done sliding, causing the rest of the kinematic physics to break down

**Comment by eon-s** [comment] 2018-02-05 22:24
Seems to be related to #5910 which may correspond to `move_and_collide` now, also there are mentions that `test_move` does not work with planes which may be closer to the root of the problem.

**Comment by Silvea12** [comment] 2018-02-05 22:38
Seems like it. Wish they'd warn somewhere.

**Comment by fracteed** [comment] 2018-02-06 00:56
Although I haven't looked at your file, it sounds similar to the issues I am having with my shooter game. When the player and npc's touch a floor/wall in my game, they will tend to come to a stop fairly abruptly, rather than sliding. The same code with native Godot physics slides perfectly. I was going to try and recreate this issue with a simple scene, but it seems like @Silvea12 has done so here.

**Comment by Silvea12** [comment] 2018-02-06 13:24
@fracteed It seems like it only applies to the plane. As a plane has no thickness, bullet seems to not like it so much (or whatever handles kinematic move_and_collide) so it returns nothing.

The stop is in relation to the fact that move_and_slide calls move_and_collide before sliding, and will return immediately if no collisions were hit - i.e. it assumes no slide needs to be performed. This is as if it stopped in mid air, seeing no reason to continue trying to adjust itself.

**Comment by fracteed** [comment] 2018-02-07 01:34
Maybe it is a different issue. I only use box shape collisions and have never even tried the plane collision. Regardless, I am still getting very glitchy sliding using Bullet. However my kinematic bodies are travelling quite fast, so this may be a factor. The native godot physics slides perfectly in the same instance, but bullet kinematic bodies catch all the time, so I am using some very hacky code to force bodies away from collision shapes to try and avoid this!

Does your issue go away if you change from Bullet to native godot physics?

**Comment by fracteed** [comment] 2018-02-07 02:46
Not sure if they are related or not, but I have added my issue here #16459

**Comment by AndreaCatania** [comment] 2018-09-07 05:21
This is not a bug, The plane shape is not mean to be a walkable floor

**Comment by eon-s** [comment] 2018-09-07 10:11
@AndreaCatania can it be possible to add a warning when a PhysicsBody/2D has a plane (or line) shape?

**Comment by akien-mga** [comment] 2018-09-10 13:46
Closing as it's the same issue as #17893, where a potential enhancement is discussed.

**Closed by akien-mga** 2018-09-10 13:46 UTC
Labels: bug, discussion, topic:physics
