### ISSUE TITLE
HingeJoint bug

### ISSUE THREAD

**Issue by Zotyx** [godotengine/godot#43364] opened 2020-11-06 17:28 UTC
Another report: https://github.com/godotengine/godot/issues/18351

**Godot version:**
v3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
[Spatial]
I've created a custom vehicle (using a RigidBody) that have some custom wheels (RigidBody). Each wheel is connected to the body with a HingeJoint (node A: vehicle body, node B: current wheel). The problem is that when I set the value of the HingeJoint's motor max impulse above 1, each wheel spins, stops, spins again, stops again etc ...

**Minimal reproduction project:**
The attached file shows a very basic plane with the custom wheels.
[HingeJoint Bug.zip](https://github.com/godotengine/godot/files/5502603/HingeJoint.Bug.zip)

**Comment by Calinou** [comment] 2020-11-06 17:53
Can you reproduce this when switching to GodotPhysics?

**Comment by Zotyx** [comment] 2020-11-06 18:11
@Calinou Switching to GodotPhysics seems to be very slow and in some cases it just doesn't work, maybe I did something wrong ?

**Comment by Zotyx** [comment] 2020-11-06 19:22
I forgot to notify that a hinge joint seems to rotate only when it collides with a ground or whatever, not if it is in the air.

**Comment by Zotyx** [comment] 2020-11-06 22:54
So, have you a solution @Calinou ?  Or is it a bug that will be fix ? Sorry to ping you again, I'm just frustated that I can't finish my code.

**Comment by Calinou** [comment] 2020-11-06 22:59
@Zotyx I don't know how this can be fixed, sorry.

**Comment by Zotyx** [comment] 2020-11-06 23:03
Oh okay, I think that I will just make a plane without wheels because I think that making wheels from scratch is too complicated. Thanks anyway !

**Comment by madmiraal** [comment] 2020-11-07 08:43
Duplicate of #18351.

**Closed by madmiraal** 2020-11-07 08:43 UTC
Labels: bug, topic:physics
