### ISSUE TITLE
Creating new project folder, naming it has keypress lag

### ISSUE THREAD

**Issue by kryptot7** [godotengine/godot#28744] opened 2019-05-07 19:58 UTC
**Godot version:**
3.1.1-stable x64

**OS/device including version:**
Windows 10 Home, version 1803 (64-bit)
Intel Core i3-7100U
8GB RAM

**Issue description:**
The Create a Folder... dialogue box in the Project Manager's Open a Directory view has a delay when entering keys.
Example: I press the following keys: g, o, d, i, Backspace, o, and t.
Expected result: "godot"
Actual result: "godo" The first keypress does nothing. But when I press "o", "g" pops up, etc.
Sometimes the last letter (in this case, "t") pops up automatically after a delay. This happened as I switched to Firefox to keep typing and then went back to Godot: the text box now said "godot".

**Steps to reproduce:**
Open Godot.
New Project.
Browse.
Create Folder.
Start typing.

**Minimal reproduction project:**
Not necessary

**Comment by Calinou** [comment] 2019-05-07 20:03
This should be resolved by updating your driver to the latest version *provided by Intel*, see https://github.com/godotengine/godot/issues/23069#issuecomment-471168356.

**Comment by turtletooth** [comment] 2019-05-07 20:52
The problem with that is that not all vendors have released the right drivers.  If you Run godot with the 
--verbose flag, it will serve as a temporary fix.
Here is step by step tutorial if it helps- https://www.youtube.com/watch?v=le801I8WIw4

**Comment by Calinou** [comment] 2019-07-16 21:32
I'll close this as a duplicate of https://github.com/godotengine/godot/issues/23069.

**Closed by Calinou** 2019-07-16 21:32 UTC
Labels: topic:editor
