### ISSUE TITLE
Parser bug (please report) when doing StringName conversion (formerly causes string corruption)

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#49843] opened 2021-06-22 23:43 UTC
### Godot version

277db14b647d3184b341a359020c0acc4549afaf

### System information

Windows 10

### Issue description

There appears to be issues with conversion between between StringName and String. In this case, we have a dictionary containing strings for keys, and integers for values. The bug results in the first character of strings contained in this dictionary get decremented after calling get_subname on a NodePath.

```
Pre-call get_subname{FoxRun:4}
Post-call get_subname{EoxRun:Null}
```

In this case, we have identified that this issue can be triggered as a result of accessing accessing the .resource_name property earlier on a Resource containing a matching name, which is declared to return StringName:
```ADD_PROPERTY(PropertyInfo(Variant::STRING_NAME, "resource_name"), "set_name", "get_name");```

While get_name is declared to return String
```String Resource::get_name() const;```

The corruption is as if a String object is being reinterpret_cast as a StringName, since the first word of a String is the first character, while the first word of StringName is the reference count. The first character is being decremented, which leads me to suspect it is being treated as a reference count.

We have had some trouble creating the most minimal reproduction of this bug, so I included a modified version of an addon designed to both rename animations on imported scenes, and extract their movement into usable root motion data (most of which has been removed since it is not necessary to demonstrate this string corruption bug).

A lot of this is still based on speculation, but this is what we have managed to find so far.

### Steps to reproduce

Simply load the project and observe the output of the prints from lines  68 and 70 of root_motion_extractor_functions.gd in the console. You'll note how the string contained in the dictionary FoxRun gets its first character decremented after get_subname is called. You can also reimport fox.glb to see the first character decrement further.

However, if you change the lines
```
if p_animation_conversion_table.has(animation.resource_name):
	var root_motion_extraction_flags: int = p_animation_conversion_table[animation.resource_name]
```
to
```
if p_animation_conversion_table.has(animation.get_name()):
	var root_motion_extraction_flags: int = p_animation_conversion_table[animation.get_name()]
```
on lines 46-47 in the file root_motion_extractor_functions.gd then reload the project and reimport, there should no longer be any string corruption issues.

### Minimal reproduction project

[string_name_bug.zip](https://github.com/godotengine/godot/files/6697944/string_name_bug.zip)

**Comment by TokageItLab** [comment] 2021-06-22 23:58
Related #48515

**Comment by lyuma** [comment] 2021-06-23 00:01
Yes, it is related to the whole situation with StringName and String.

But, to avoid distractions, I would like to keep this issue scoped solely on memory corruption, crashes and other undefined behavior which was not intended.

**Comment by lyuma** [comment] 2021-08-05 17:57
I believe this original issue is fixed. (ignoring the skeleton related errors which I do not believe are related)

However, what's with the "Parser bug (please report)". maybe this issue should be investigated further so that the parser bug can be fixed?

```
Godot Engine v4.0.dev.custom_build (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
Initialising RootMotionExtractor plugin
Add AutoLoad
  Cannot open file 'res://.godot/imported/fox.glb-861302955982eb61072d359641168149.scn'.
  scene\3d\skeleton_3d.cpp:471 - Index p_bone = -1 is out of bounds (bones.size() = 24).
  Parser bug (please report): Trying to check compatibility of unset value type
Pre-call get_subname{FoxRun:4}
Post-call get_subname{EoxRun:Null}
  scene\3d\skeleton_3d.cpp:471 - Index p_bone = -1 is out of bounds (bones.size() = 24).
  Parser bug (please report): Trying to check compatibility of unset value type
Pre-call get_subname{FoxRun:4}
Post-call get_subname{EoxRun:Null}
  scene\3d\skeleton_3d.cpp:471 - Index p_bone = -1 is out of bounds (bones.size() = 24).
  Parser bug (please report): Trying to check compatibility of unset value type
Pre-call get_subname{FoxRun:4}
Post-call get_subname{EoxRun:Null}
  scene\3d\skeleton_3d.cpp:471 - Index p_bone = -1 is out of bounds (bones.size() = 24).
  Parser bug (please report): Trying to check compatibility of unset value type
```

**Comment by lyuma** [comment] 2024-11-29 20:19
Even after fixing the syntax errors in the MRP, I cannot reproduce any parser bugs on Godot 4.3. I'm closing this issue as outdated.

**Closed by lyuma** 2024-11-29 20:19 UTC
Labels: bug, topic:gdscript
