### ISSUE TITLE
Renaming Node Causes Issues in Inherited Scenes

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#16650] opened 2018-02-12 19:13 UTC
==Changed to a feature request Original post is below for posterity==

When you change the name of a node that is used in an inherited scene, if it isn't the root node all changes to that node and it's children are reverted in the inherited scene with an error  

I think it would be a good idea to implement a system to change names in said situation without potentially undoing a lot of changes.

==original post==

**Godot version:**
3.0

**OS/device including version:**
Windows 10

**Issue description:**
When you change the name of a node that is used in an inherited scene, all changes to that node and it's children are reverted in the inherited scene with the error  
scene\resources\packed_scene.cpp:149 - Node './(NODE)' was modified from inside an instance, but it has vanished.
Node not found: (NODE)

Pretty sure this is a regression.

**Steps to reproduce:**
Create scene with node.
Add child node.
Create inherited scene from first scene, add another child to the child node in that scene.
Rename first child node in first scene. Save.
Observe errors

**Comment by Zylann** [comment] 2018-02-12 20:29
Are you sure it's a regression?

When you inherit a scene, you have only two ways of referring to the node you inherit:
- Its name: so if you change the name in the base scene you loose the reference
- Its index: so if you change the order in the base scene you loose the reference too

Given this fact, renaming nodes which are used in inherited scenes will always cause problems, UNLESS the editor detects every single scene inheriting the base scene and change the name of the node in them.

**Comment by eon-s** [comment] 2018-02-12 22:00
Can't reproduce on linux, when saving base scene got a message "must reload? 1" and the changes were reflected in the inherited scene.

Steps were:
-create inherited.
-change the name on one of the base nodes.
-save base scene.

**Comment by Zylann** [comment] 2018-02-12 22:11
@eon-s now do this... but make sure you have only one scene open at a time (i.e make sure the inherited scene is NOT open when you do the change in its base). This makes me think of an issue I had too, not exactly the same issue but similar behaviors: https://github.com/godotengine/godot/issues/14921

**Comment by starlord1311** [comment] 2018-02-12 22:11
can i take up this issue? @ElfEars

**Comment by eon-s** [comment] 2018-02-12 23:42
@Zylann I did that first but supposed the error was with both scenes open because got no errors, I wonder if is related to the windows saving issue.

**Comment by ElfEars** [comment] 2018-02-13 00:08
@Zylann IIRC I actually had BOTH scenes open in editor at the same time when I got the error.

Strange, now I can't seem to be able to reproduce...

I was renaming a tileset when it happened...
Will test with a tileset...

@starlord1311 Not sure what you mean but help is always appreciated! :D

**Comment by ElfEars** [comment] 2018-02-13 00:13
Ok, will update first post but some more steps are required.

Updated steps are as follows:

Create scene with node.
Add child node.
Create inherited scene from first scene, add another child to the child node.
Rename first child node in first scene. Save.
Observe errors

**Comment by eon-s** [comment] 2018-02-13 00:17
Now I was able to reproduce but makes sense, the original node was removed (scene file store name, not ID) so the child got removed because the parent does not exist anymore.

**Comment by ElfEars** [comment] 2018-02-13 00:20
Hmm. Interesting... I sure this worked in 2.1. Will test there.

**Comment by ElfEars** [comment] 2018-02-13 00:22
hmm. Guess I was mistaken. All I can ask is if this is feasable as a feature request.

**Comment by eon-s** [comment] 2018-02-13 00:33
This is the way the scene uses the inheritance:
```
[gd_scene load_steps=2 format=2]
[ext_resource path="res://Area2D.tscn" type="PackedScene" id=1]
[node name="Area2D" index="0" instance=ExtResource( 1 )]

script = null

[node name="Node2D" type="Node2D" parent="Label2" index="0"]
```

Using child order will break the possibility of reorder the base scene, an option could be to add an unique ID to the nodes of that particular scene file so inherited scenes can use that ID instead of node name, not sure what other use could have to make sense the change on the scene format.

**Comment by Zylann** [comment] 2018-02-13 00:42
@eon-s like I said in my first comment :p

**Comment by ElfEars** [comment] 2018-02-13 00:45
A unique ID sounds like a good idea that could have a lot of applications (although as @Zylann said it too has it's issues). All in all I'd vouch for it but I'm not an expert so if it would have any adverse changes to the scene format I wouldn't be the most aware.

**Comment by Calinou** [comment] 2020-05-26 14:14
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-05-26 14:14 UTC
Labels: feature proposal, topic:editor

**Comment by PLyczkowski** [comment] 2020-05-26 14:22
Related proposal: https://github.com/godotengine/godot-proposals/issues/518
