### ISSUE TITLE
Can't get Android screen size

### ISSUE THREAD

**Issue by HumanDuck23** [godotengine/godot#23347] opened 2018-10-28 10:34 UTC
**Godot version:**
Godot 3.0.6

**OS/device including version:**
Android 8.0/ Huawei Mediapad M5 8.4"

**Issue description:**

In the game a circle is supposed to reappear at the top of the screen once it goes out at the bottom. I do this by measuring coordinates and the function "OS.get_screen_size().y". On my laptop this works without any issues, but on my tablet it stays outside of the screen for a few seconds. I take it that this is because "OS.get_screen_size().y" isn't returning the correct value.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment] 2018-10-28 17:14
Did you try with `get_viewport().size` or `get_viewport_rect()`?

**Comment by KoBeWi** [comment] 2020-08-07 20:48
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 17:18
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 17:18 UTC
Labels: bug, topic:core
