### ISSUE TITLE
Editor Crashes While Saving

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#5599] opened 2016-07-08 18:34 UTC
**Operating system or device - Godot version:** Windows 7 x64, Godot 2.0.3 Stable.

**Issue description** (what happened, and what was expected): When trying to add sprites to one of my scenes, the editor crashes while saving. This has happened four times in a row now.

**Steps to reproduce:** Open the attached project. Open the scene `res://Basketball/Grandpa.tscn`. Add a Sprite to the Grandpa object. Load the texture `res://Basketball/GFX/Torso.png` for the sprite. Rename the newly created node to Torso. Press CTRL + S.

Actually, it seems like the crash will occur if you just try to save `res://Basketball/Grandpa.tscn` in any capacity.

**Link to minimal example project** (optional but very welcome): 
[Crash.zip](https://github.com/godotengine/godot/files/354868/Crash.zip)

**Comment by akien-mga** [comment] 2016-07-08 18:57
I can't reproduce on Linux x64 using either Godot 2.0.3 or the upcoming 2.0.4 (not published yet).

I think you might have permission issues in your project folder. Maybe you opened the tscn file in a text editor and Windows won't let Godot overwrite it?

**Comment by Gastronok** [comment] 2016-07-08 20:23
I was duplicating the scene from scratch, and I think I found the problem:

You cannot have a TextureProgress which is a child of a Node.

Try creating a new project/scene, setting the root node as a Node (not Node2D), adding a TextureProgress, and saving. This triggers a crash for me, presumably for the same reasons.

**Comment by Zylann** [comment] 2016-07-10 01:31
Godot 2.0.4 also started crashing at my 2D scenes even if the scene is made of one tilemap, with no errors in the console.

I found that if I remove the tileset from the tilemap, Godot no longer crashes. But if I add it back, it crashes again.
I read in the console that Godot is trying to re-write the `tileset.tres` while I'm saving the scene, which is useless and unexpected:
`Also saving modified external resource: res://tilesets/terrain_tileset.tres`
This file has no reason to have been modified in any way.

**Comment by SuperUserNameMan** [comment] 2016-07-10 09:32
Here, 2.0.4 crashes each time i CTRL+S scripts from 2.0.3 projects.

**Comment by akien-mga** [comment] 2016-07-10 09:35
The crashes in 2.0.4 are due to #5620, and have been fixed in the 2.0 branch. Need to build new binaries now..

For the crashes in 2.0.3, I'm not sure where it would come from.

**Comment by Zylann** [comment] 2016-07-10 12:50
@akien-mga are you sure? My test project doesn't have scripts at all.

**Comment by akien-mga** [comment] 2016-07-10 12:53
@Zylann Yes, your test project no longer crashes.

**Comment by Zylann** [comment] 2016-07-10 12:54
@akien-mga does it still try to save the tileset? I think I'll make another issue for it, unless it's related to the crash

**Comment by akien-mga** [comment] 2016-07-10 12:56
Yes it does.

**Comment by vnen** [comment] 2016-07-19 15:38
> I cannot have a TextureProgress which is a child of a Node2D.

I could reproduce this the first time I tried, but only the first time. One more paranormal bug?

**Comment by akien-mga** [comment] 2016-07-24 11:23
Can you reproduce this bug in 2.1-beta?

**Comment by Gastronok** [comment] 2016-07-24 16:19
I cannot appear to reproduce it in 2.1-beta, neither via the original example nor the more minimal steps posted later.

**Comment by akien-mga** [comment] 2016-07-24 16:22
Awesome :) We're about to release 2.1 rc1 and I don't intend to make a new 2.0.x release (unless there's a critical regression), so I guess we can consider this issue as fixed for 2.1, and wontfix for 2.0.

**Closed by akien-mga** 2016-07-24 16:22 UTC
Labels: bug, platform:windows, topic:editor
