### ISSUE TITLE
TextureAtlas importer ignoring alpha in region mode and cuts sprites unexpectedly

### ISSUE THREAD

**Issue by AHAHACKA** [godotengine/godot#33448] opened 2019-11-08 13:19 UTC
**Godot version:**
3.2 beta 1

**OS/device including version:**
windows 10

**Issue description:**
In "region" mode unexpected behavior with sprites. In some cases alpha ignored. in other case got half of sprites or empty atlas . Example project with sprites is attached.

**Steps to reproduce:**
1. select all sprites from folder and import with "region" mode. Shadow in sprites cuts away. Mesh2D sprites is ok (shadow full).
files all_sprites_region.png and all_sprites_mesh2d.png respectively.

2. select 3 first sprites only and get empty atlas in region mode and half-cutted sprites in region mode.
files only3first_region.png and  only3first_mesh2d.png respectively.

**Minimal reproduction project:**
[New Game Project1.zip](https://github.com/godotengine/godot/files/3824715/New.Game.Project1.zip)

**Comment by dalexeev** [comment] 2019-11-09 08:34
Duplicate of #33106?

**Comment by holzmb** [comment] 2019-12-27 11:12
Yes, it's the same issue.

**Comment by akien-mga** [comment] 2020-01-17 18:09
Closing as duplicate of #33106.

**Closed by akien-mga** 2020-01-17 18:09 UTC
Labels: bug, topic:import
