### ISSUE TITLE
Import gltf file via `drag & drop` and delete it leads to editor crash

### ISSUE THREAD

**Issue by Snowapril** [godotengine/godot#53552] opened 2021-10-08 03:01 UTC
### Godot version

Godot Engine v4.0.dev.20210924.official.5e4a71200

### System information

Windows 10, GTX 960, 30.0.15.1010, Vulkan

### Issue description

When I import just one GLTF file through `drag & drop`, two files are created in the filesystem tab (not one).
After that, I delete one of them then godot editor go crashed 

This issue is not caused when I import gltf through other ways except `drag & drop`.

### Steps to reproduce

1. Drag & Drop the gltf file to editor (anywhere on the editor screen)
2. Delete that imported gltf file from the filesystem tab
3. Crashed 😢

### Minimal reproduction project

[godot_sample.zip](https://github.com/godotengine/godot/files/7308161/godot_sample.zip)

Here is gltf file that crashed the godot 
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure/glTF

**Comment by CheapMiao** [comment] 2022-02-04 18:52
I meet the same problem, too.
After drag file into a project, I even see two same gltf in file system.

**Comment by KoBeWi** [comment] 2022-05-13 23:46
Can't reproduce in alpha 8.

**Comment by fire** [comment] 2023-01-16 16:54
Closing due to lack of issue reproduction.

**Closed by fire** 2023-01-16 16:54 UTC
Labels: bug, topic:editor, confirmed, topic:import, crash, topic:3d
