### ISSUE TITLE
An already freed `Object` evaluates to `true` when used as a condition in `if`

### ISSUE THREAD

**Issue by rakun99** [godotengine/godot#44861] opened 2021-01-01 20:00 UTC
![Снимок](https://user-images.githubusercontent.com/46073558/103445176-7cec7080-4c8a-11eb-9319-ac91d7937793.PNG)

**Godot version:**
3.2.4 beta 4

**OS/device including version:**
Windows 7

**Issue description:**
Godot sends an error even when I make precaution that target doesn't Null.
I send a bunch of missiles with predefined target. First missile crashes the target and target is queue_freed. Because of that other missiles receive null, but I got an error.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-01-01 20:11
@rakun99 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by KoBeWi** [comment] 2021-01-02 23:34
You are supposed to use `is_instance_valid()` to avoid this error. So it should be either
```
if is_instance_valid(target):
    stuff
```
or
```
if not is_instance_valid(target):
    target = null

if target:
    stuff
```

That said, this error used to report [deleted object] instead of null. Not sure if the new behavior is intended.

**Comment by Zireael07** [comment] 2021-01-03 09:15
IIRC is_instance_valid() can be a fake positive too, so it isn't a fix...

**Comment by KoBeWi** [comment] 2021-01-03 09:52
No, fake positives were fixed in the newest 3.2 releases.

**Comment by rakun99** [comment] 2021-01-03 19:52
> @rakun99 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Well, I used a steering behavior form KidsCanCode demo. 
> You are supposed to use is_instance_valid() to avoid this error. So it should be either

Wow, it worked. Thanks. So problem is solved.

**Comment by kleonc** [comment] 2023-01-02 17:22
The same in v4.0.beta10.official [d0398f62f]:
![Godot_v4 0-beta10_win64_jalHL8aUoC](https://user-images.githubusercontent.com/9283098/210262569-ad67d7fd-843d-4940-870b-e94d81e8c7d8.png)

Related: #59816.

It's GDScript specific issue, right? :thinking:

**Comment by KoBeWi** [comment] 2023-01-02 17:28
@kleonc The screenshot you posted looks correct. The error reports the object as 'previously freed'.

**Comment by kleonc** [comment] 2023-01-02 17:34
> @kleonc The screenshot you posted looks correct. The error reports the object as 'previously freed'.

Oh, so the only issue in here is the error message saying "null instance" instead of something like "previously freed"?

**Comment by KoBeWi** [comment] 2023-01-02 17:45
Well, the behavior is unintuitive, but the idea is that you have to use `is_instance_valid()` to make sure whether the object is freed or not. I think the fact that checking the object directly is inconsistent is due to performance reasons.

**Comment by vnen** [comment] 2023-02-24 23:24
This is not a bug and from the discussion on #59816, it is expected behavior that `if freed_object:` evaluates to `true`. In general you should check why you are getting a freed object and if it is expected you should use `is_instance_valid()`.

**Closed by vnen** 2023-02-24 23:24 UTC
Labels: bug, discussion, topic:core, topic:gdscript

**Comment by LO-0116** [comment] 2025-02-27 00:47
> You are supposed to use `is_instance_valid()` to avoid this error. So it should be either
> 
> ```
> if is_instance_valid(target):
>     stuff
> ```
> 
> or
> 
> ```
> if not is_instance_valid(target):
>     target = null
> 
> if target:
>     stuff
> ```

Why is this necessary? Why isn't previously freed instanced evaluated to `false` by default? Issue persists in v4.3.stable.official [77dcf97d8]

**Comment by Zireael07** [comment] 2025-02-27 08:21
@LO-0116 This is a scripting design issue that has been discussed back and forth to death.
