### ISSUE TITLE
Cyclic PackedScene exports crashes game

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#65057] opened 2022-08-29 21:45 UTC
### Godot version

051f24b067642a241d0a4acbb1b7644e11700bfc

### System information

Windows 10

### Issue description

I set up two scenes:

- SceneA
- SceneB

Both scenes export a `PackedScene` like so:
```gdscript
@export var other_scene:PackedScene
```
Then, I set other_scene in SceneA to SceneB and I set other_scene in SceneB to SceneA. Starting the game crashes with the following:
```
Running: C:/Users/Miguel/Documents/godot/bin/godot4.exe --path C:/Users/Miguel/Desktop/cyclic-packed-scenes --remote-debug tcp://127.0.0.1:6007 --editor-pid 19712 --position 1344,756 res://scene_a.tscn

Godot Engine v4.0.alpha.custom_build.051f24b06 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080
 
ERROR: res://scene_b.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene_a.tscn
   at: ResourceLoaderText::load (scene\resources\resource_format_text.cpp:486)
ERROR: Failed loading resource: res://scene_b.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:222)
ERROR: res://scene_a.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene_b.tscn
   at: ResourceLoaderText::load (scene\resources\resource_format_text.cpp:486)
ERROR: Failed loading resource: res://scene_a.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:222)
ERROR: Failed loading scene: res://scene_a.tscn
   at: (main\main.cpp:2780)
ERROR: 1 RID allocations of type 'class GodotBody3D * __ptr64' were leaked at exit.
ERROR: 1 RID allocations of type 'class GodotArea3D * __ptr64' were leaked at exit.
ERROR: 1 RID allocations of type 'class GodotSpace3D * __ptr64' were leaked at exit.
ERROR: 1 RID allocations of type 'class GodotArea2D * __ptr64' were leaked at exit.
ERROR: 1 RID allocations of type 'class GodotSpace2D * __ptr64' were leaked at exit.
ERROR: 2 RID allocations of type 'class NavMap' were leaked at exit.
ERROR: 2 RID allocations of type 'struct RendererSceneRenderRD::ShadowAtlas' were leaked at exit.
ERROR: 1 RID allocations of type 'struct RendererSceneRenderRD::ReflectionAtlas' were leaked at exit.
ERROR: 1 RID allocations of type 'struct RendererRD::TextureStorage::RenderTarget' were leaked at exit.
ERROR: 2 RID allocations of type 'class RendererRD::TextureStorage::Texture' were leaked at exit.
ERROR: 1 RID allocations of type 'struct RendererCanvasCull::Canvas' were leaked at exit.
ERROR: 1 RID allocations of type 'struct RendererViewport::Viewport' were leaked at exit.
ERROR: 1 RID allocations of type 'stERROR: Condition "_first != nullptr" is true.
   at: SelfList<class GDScriptFunction>::List::~List (C:\Users\Miguel\Documents\godot\core/templates/self_list.h:106)
ERROR: Condition "_first != nullptr" is true.
   at: SelfList<class GDScript>::List::~List (C:\Users\Miguel\Documents\godot\core/templates/self_list.h:106)
```

### Steps to reproduce

1. define SceneB as other_scene in SceneA
2. define SceneA as other_scene in SceneB

### Minimal reproduction project

[cyclic-packed-scenes.zip](https://github.com/godotengine/godot/files/9448110/cyclic-packed-scenes.zip)

**Comment by Atlinx** [comment] 2022-08-30 01:58
I downloaded and ran the project and I can't seem to reproduce the error. I'm on the latest version of Godot (18159a6574e40c36c1aed0d1cae1dc8a32879efa) on Windows 11.

Maybe the error is there because you haven't open the project once in the editor first? For my Godot CLI setups I have to open the project once in the editor to import all the assets first, and then I'm able to run my test runner scenes.

**Comment by bitbrain** [comment] 2022-08-30 05:43
> EDIT: Whoops I didn't realize the project didn't come primed

It does but due to this bug Godot 4 seems to remove the setup when first loading it to "fix it" (I get a broken dependencies popup)

**Comment by Rindbee** [comment] 2022-08-31 09:36
Seems to be a duplicate of #24146.

**Closed** 2022-08-31 10:05 UTC
Labels: bug, topic:core
