### ISSUE TITLE
Uneven RichLabel BBCode text centering using [center] tags 

### ISSUE THREAD

**Issue by rokasv** [godotengine/godot#64779] opened 2022-08-23 11:14 UTC
### Godot version

3.1 - 3.5

### System information

Windows 10 GLES2/3, NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

### Issue description

Creating a RichLabel with basic centered text using the following code: 
```
	label.bbcode_text = \"[center]This is some text to show bad centering aaaaaai\\n a[/center]\"
```
Yields this result:

![1 - Copy](https://user-images.githubusercontent.com/13801432/186143260-513fe0ac-f886-4eed-ae13-c69fed2b2fd5.PNG)

The yellow overlay text measures the distance from the text to the richlabel rectangel boundaries. The sides should be either be exactly the same or differ by 1 pixel. They do not, which makes it a bug. 

The issue does not appear if the text does not need to be broken with newlines to fit in the rectangle width. My guess is that this bug is caused by the engine inserting newlines and forgetting to remove spaces where the newlines are inserted, causing the individual lines to have trailing whitespaces included in the width calculation, offsetting the text.

### Steps to reproduce

Create a RichLabel with a pixel font and use BBCode to center text, then compare the text padding sizes.  

### Minimal reproduction project

Minimal project: [Bad BBCode Centering.zip](https://github.com/godotengine/godot/files/9401916/Bad.BBCode.Centering.zip)

**Comment by akien-mga** [comment] 2022-08-23 11:24
That's pretty much the same issue as #64738, the difference is whitespace that doesn't get trimmed when wrapping. @bruvzg

**Comment by bruvzg** [comment] 2022-08-23 11:25
> That's pretty much the same issue as https://github.com/godotengine/godot/issues/64738

It is the same issue.

**Comment by akien-mga** [comment] 2022-08-23 11:26
Duplicate of #64738.

**Closed by akien-mga** 2022-08-23 11:26 UTC
Labels: bug, topic:gui
