### ISSUE TITLE
While in _draw() method, appending / not appending a Vector2 to a PackedVector2Array crashes the engine (only in 4.0.beta11)

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#71316] opened 2023-01-13 08:00 UTC
### Godot version

4.0.beta11

### System information

Windows 11

### Issue description

The issue is that declaring a PackedVector2Array in the `_draw()` method, and then sometimes leaving it empty and on other draw times appending a Vector2 to it causes a crash / freeze.
- Happens on both: tool side with `@tool` (crashing editor) as well as on game side (crashing game window).
- Only happens in beta11, does not occur in beta10 or any earlier I've tested.
- Does not happen, if appends a Vector2 every time, or never appends one. It's about the _conditionality_ of leaving it sometimes empty - not sure if needs to be on the very next frame or just next time.

### Steps to reproduce

Steps:
- Create a new scene and put a `CanvasItem` based node in there and put a script to it.
- In the script define `_draw` method and in it define a variable of `PackedVector2Array` type.
- Then add a `Vector2` to that array conditionally: on some draws no point is added, on some draws a point is added.
- There's no need to actually draw anything.

The screenshot tells it all - clicking "Enabled" on freezes the engine:
![image](https://user-images.githubusercontent.com/16601926/212269041-c89feccf-b075-475e-81b6-81a9494b8ad0.png)

### Minimal reproduction project

Open the `Test.tscn`, select the "Test" node and click the "Enabled" property on in the `Inspector`. The engine will crash / stay looping forever.
[PackedVector2ArrayBeta11Bug.zip](https://github.com/godotengine/godot/files/10409404/PackedVector2ArrayBeta11Bug.zip)

**Comment by takaturre** [comment] 2023-01-13 08:21
Could be (the same core issue). However, in this case there's no resizing, as it's (supposed to be) a new `PackedVector2Array` every time. (Though if Godot somehow reuses things behind the veils for these kind of scenarios, could be the exact same issue, I suppose.)

**Comment by kleonc** [comment] 2023-01-13 11:44
Confirmed in v4.0.beta11.official [91713ced8].
Can't reproduce in https://github.com/godotengine/godot/commit/3c9bf4bc210a8e6a208f30ca59de4d4d7e18c04d.

Likely fixed by #71228, closing.

**Closed by kleonc** 2023-01-13 11:44 UTC
