### ISSUE TITLE
ScrollContainer grabber in kinetic scroll goes in wrong direction

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#30899] opened 2019-07-28 20:40 UTC
**Godot version:**
Godot 3.1.1.stable.official

**OS/device including version:**
Manjaro Linux

**Issue description:**
Whe you use a scrollContainer and use the grabber, when you release it with some kinetic force, the scroller goes immediatly to the opposite direction. This is visible in mobile build or in pc version only if you enable Touch from Mouse in project settings.

**Steps to reproduce:**
Create a scene with the ScrollContainer and scrol with the grabber.

**Comment by Anutrix** [comment] 2019-07-29 16:25
Can you provide a test project? I can't seem to get it even working. There seems many bugs in ScrollContainer.

**Comment by grevius5** [comment] 2019-07-29 16:49
[ScrollContainer.zip](https://github.com/godotengine/godot/files/3443333/ScrollContainer.zip)
Here it is ;)

**Comment by Anutrix** [comment] 2019-07-29 17:12
![a](https://user-images.githubusercontent.com/11459028/62067620-c3e26500-b251-11e9-93fd-19c99655f34d.gif)
Watch it till the end. I don't know if it's same issue but sometimes the mouse gets stuck on one of the buttons and scrolls even if mouse is released. 
But I couldn't reproduce on my Windows PC(even with emulate touch from mouse enabled).

**Comment by KoBeWi** [comment] 2020-11-18 22:53
Still valid in 3.2.4 beta2

The main issue I see is that cursor stucks scrolling when you release mouse button outside the window.

**Comment by KoBeWi** [comment] 2022-01-20 01:14
Looks fixed in 3.5

**Closed by KoBeWi** 2022-01-20 01:14 UTC
Labels: bug, confirmed, topic:gui
