### ISSUE TITLE
TileMapLayer doesn't have an option to sort tiles horizontally

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#92682] opened 2024-06-02 11:38 UTC
### Tested versions

4.3 beta 1, 4.3 dev 6

### System information

Windows 11 - Godot 4.3.beta1 - Forward+

### Issue description

If you need to overlap tiles that have 4 cells (2x2) there is no option to set which way to align them horizontally. It is by default from left to right, but if you use y-sorting it somehow turns right to left. There are even some places in which this alignment will not be consistent. This is shown in the minimal reproduction project.

I found [this](https://stackoverflow.com/questions/61741489/godot-tiles-in-tilemap-sorting-wrong) while searching the internet, but it makes the tile map invert its y-sorting too, so it does not solve the problem.

This issue does not let me put walls, which are bigger than one cell, to be put horizontally like shown below.

![a0743e969f68042b5802680cd2f6c480ba086e93](https://github.com/godotengine/godot/assets/4398470/d34eb92d-5d73-41d0-abf2-8912e60409e4)

![image](https://github.com/godotengine/godot/assets/4398470/02b0d854-c4e5-4c72-995d-1ec06aa2057f)

P.S. This also happens in the TileMap class for godot 4.2.1 stable

### Steps to reproduce

Create a TileMapLayer, set a tileset atlas which takes 4 cells for each of its tiles and overlap them horizontally. They will be sorted from left to right (right is in front), and if you turn y-sort ON, it aligns them from right to left.

### Minimal reproduction project (MRP)

[minimal_reproduction_project.zip](https://github.com/user-attachments/files/15525113/minimal_reproduction_project.zip)

**Comment by KoBeWi** [comment] 2024-06-02 20:28
This is a missing feature not a bug.

**Comment by AThousandShips** [comment] 2024-06-02 20:31
Indeed, must have missed the title and just gone off the vauger description in the post, I could have sworn the title had changed

**Comment by agrimminck** [comment] 2024-06-02 21:20
Yep, my bad, it was a feature proposal

**Comment by agrimminck** [comment] 2024-06-03 00:26
> This is a missing feature not a bug.

Although the tilemap, when it is not y-sorted it aligns from right to left, which is what I need, and when y-sorted it aligns from left to right, could that count as a bug?

**Comment by Zireael07** [comment] 2024-06-03 06:46
@agrimminck If it is a feature proposal please move it to the correct repository

**Comment by agrimminck** [comment] 2024-06-03 15:17
> @agrimminck If it is a feature proposal please move it to the correct repository

I've searched how to do that but I haven't found it

**Comment by KoBeWi** [comment] 2024-06-03 15:20
You'll need to close this issue and open new one here:
https://github.com/godotengine/godot-proposals

**Closed** 2024-06-03 15:25 UTC
Labels: enhancement, feature proposal, discussion, needs testing, topic:2d
