### ISSUE TITLE
C# [Signal] not exposed as GDScript Signal, kind of a bug.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72352] opened 2023-01-30 03:46 UTC
### Godot version

4.0.beta16.mono

### System information

N/A

### Issue description

`[Signal] public delegate void SGEventHandler();`

```
func a(): pass

func _run() -> void:
	var inst = load("res://CSharpSignalNotExposedAsGDScriptSignal/new_script.cs").new()
	inst.connect("SG", a) # This workds.
	inst.SG # deosn't work. Not a bug, but can it return a Signal ?
	inst.SGEventHandler # deosn't work.

```
Overall I think Signal is way better than using String. Also what about `get_signal_connection_list()` C# equivalent? Does it return a bunch of strings?
Had no time to check, I stayed up late today for a long time, I need to hurry to bed...

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10532045/godot.4.0.beta15.bugs.0.zip)

**Comment by raulsntos** [comment] 2023-01-30 03:56
- Duplicate of https://github.com/godotengine/godot/issues/71348
- Should be fixed by https://github.com/godotengine/godot/pull/71356 which will be part of beta 17.

**Closed by raulsntos** 2023-01-30 03:56 UTC
