### ISSUE TITLE
Crash while code editor while typing.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/godot#22241] opened 2018-09-19 09:02 UTC
**Godot version:**
3.1 master

**OS/device including version:**
Fedora 28 64-bit

**Issue description:**
While typing code the editor crashes.

**Steps to reproduce:**
The function looks like this (its in a class)
```
func _init(materials=[], corner_heights=[CornerHeights.new(0, 0), CornerHeights.new(0, 0), CornerHeights.new(0, 0), CornerHeights.new(0, 0)]):
	self.materials = materials.duplicate()
	self.corner_heights = []
```
If I type "corner_heights." the editor crashes.

Backtrace reports the following:
```
#0  0x00000000010189df in CowData<GDScriptParser::Node*>::get (p_index=-1, this=0x151051c0) at ./core/cowdata.h:146
#1  Vector<GDScriptParser::Node*>::operator[] (p_index=-1, this=0x151da1d8) at ./core/vector.h:89
#2  _guess_identifier_type (p_context=..., p_identifier=..., r_type=...) at modules/gdscript/gdscript_editor.cpp:1225
#3  0x000000000100f7b4 in _guess_expression_type (p_context=..., p_expression=0x15105d20, r_type=...) at modules/gdscript/gdscript_editor.cpp:667
#4  0x000000000102af19 in GDScriptLanguage::complete_code (this=0x6b64ca0, p_code=..., p_base_path=..., p_owner=0xb804810, r_options=0x7fffffffb5b0, r_forced=@0x7fffffffb5a7: false, 
    r_call_hint=...) at modules/gdscript/gdscript_editor.cpp:2517
#5  0x000000000221a743 in ScriptTextEditor::_code_complete_script (this=0xd69c260, p_code=..., r_options=0x7fffffffb5b0, r_force=@0x7fffffffb5a7: false)
    at editor/plugins/script_text_editor.cpp:601
#6  0x000000000221a5cc in ScriptTextEditor::_code_complete_scripts (p_ud=0xd69c260, p_code=..., r_options=0x7fffffffb5b0, r_force=@0x7fffffffb5a7: false)
    at editor/plugins/script_text_editor.cpp:590
#7  0x0000000002483998 in CodeTextEditor::_complete_request (this=0xd6a0c70) at editor/code_editor.cpp:718
#8  0x0000000000fa446e in MethodBind0::call (this=0xa6725b0, p_object=0xd6a0c70, p_args=0x7fffffffbc80, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:54
#9  0x0000000003ea5f0d in Object::call (this=0xd6a0c70, p_method=..., p_args=0x7fffffffbc80, p_argcount=0, r_error=...) at core/object.cpp:968
#10 0x0000000003ea834e in Object::emit_signal (this=0xd660830, p_name=..., p_args=0x7fffffffbc80, p_argcount=0) at core/object.cpp:1254
#11 0x0000000003ea8af3 in Object::emit_signal (this=0xd660830, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1307
#12 0x000000000293d275 in TextEdit::query_code_comple (this=0xd660830) at scene/gui/text_edit.cpp:5830
#13 0x00000000024838d5 in CodeTextEditor::_code_complete_timer_timeout (this=0xd6a0c70) at editor/code_editor.cpp:708
#14 0x0000000000fa446e in MethodBind0::call (this=0xa672450, p_object=0xd6a0c70, p_args=0x7fffffffc750, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:54
#15 0x0000000003ea5f0d in Object::call (this=0xd6a0c70, p_method=..., p_args=0x7fffffffc750, p_argcount=0, r_error=...) at core/object.cpp:968
#16 0x0000000003ea834e in Object::emit_signal (this=0xd69eb30, p_name=..., p_args=0x7fffffffc750, p_argcount=0) at core/object.cpp:1254
#17 0x0000000003ea8af3 in Object::emit_signal (this=0xd69eb30, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1307
#18 0x00000000026d8a41 in Timer::_notification (this=0xd69eb30, p_what=25) at scene/main/timer.cpp:61
#19 0x00000000026db09f in Timer::_notificationv (this=0xd69eb30, p_notification=25, p_reversed=false) at scene/main/timer.h:38
#20 0x0000000003ea60c2 in Object::notification (this=0xd69eb30, p_notification=25, p_reversed=false) at core/object.cpp:978
#21 0x00000000026b5520 in SceneTree::_notify_group_pause (this=0x6c2faf0, p_group=..., p_notification=25) at scene/main/scene_tree.cpp:958
#22 0x00000000026b28ab in SceneTree::idle (this=0x6c2faf0, p_time=0.00833333377) at scene/main/scene_tree.cpp:509
#23 0x0000000000f37de1 in Main::iteration () at main/main.cpp:1801
#24 0x0000000000f09a1b in OS_X11::run (this=0x7fffffffd070) at platform/x11/os_x11.cpp:2820
#25 0x0000000000efb27b in main (argc=3, argv=0x7fffffffd7d8) at platform/x11/godot_x11.cpp:55
```

**Comment by vnen** [comment] 2018-09-19 11:36
This is a duplicate of #21700. I'll be soon pushing a fix.

**Closed by vnen** 2018-09-19 11:36 UTC
Labels: bug, topic:gdscript
