### ISSUE TITLE
get_local_mouse_position() / get_global_mouse_position() returns (0,0) in editor tool scripts in Godot 4

### ISSUE THREAD

**Issue by GuyUnger** [godotengine/godot#68501] opened 2022-11-11 02:02 UTC
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

get_local_mouse_position() and get_global_mouse_position() returns (0,0) in tool scripts in the editor in Godot 4. In 3.x it always returned the mouse position. I don't know if this is intended behavior and I've tried to look for an alternative way to get the mouse position but haven't been able to find it, but also this should just return the mouse position imo.

### Steps to reproduce

make a tool script and print/use get_local_mouse_position() or get_global_mouse_position()

**Comment by Sauermann** [comment] 2022-11-11 06:25
looks like a duplicate of #60390

**Comment by kleonc** [comment] 2022-11-11 12:27
Duplicate of #60390.

**Closed by kleonc** 2022-11-11 12:27 UTC
