### ISSUE TITLE
3D Particles color gradient / albedo of mesh is preferred over particle material

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#9781] opened 2017-07-22 20:57 UTC
**Operating system or device - Godot version:**
Manjaro, master as of posting
commit: aa798eb

Particles seems to ignore any color modulation in the process material. This is causing problems trying to create effects such as clouds and other fade out effects. Would be nice for 3.0.

Can provide a project if needed, but adding a color gradient to a particle3d node in the process material is enough to replicate. Was wondering if anyone else was getting this error.

**Comment by Zylann** [comment] 2017-07-28 00:12
Godot 3.0 alpha1, Windows 10 64 bits, nVidia geforce 940M:

I'm getting this too, color or gradient don't do anything. I'm using built-in procedural quad meshes.

Project: 
[ParticlesColorRamp.zip](https://github.com/godotengine/godot/files/1181605/ParticlesColorRamp.zip)

**Comment by Bauxitedev** [comment] 2017-08-27 09:27
This is not a bug, although it might be kind of confusing at first why this happens. You need to set the material of the particle mesh to use the **vertex color as albedo** (because internally, the particles are colored by setting the vertex colors). A demonstration:

![albedo](https://user-images.githubusercontent.com/31383123/29748581-a2e93470-8b19-11e7-8b24-4df647ce2d2a.png)

![parts](https://user-images.githubusercontent.com/31383123/29748647-a20f010a-8b1a-11e7-88e4-acd77fb1fd46.gif)

(also you should check the Transparent flag if you want alpha to work in the color ramp)

**Comment by Jummit** [comment] 2020-04-14 08:15
This should be documented. I had to search for this issue to find out why colors weren't working.

**Comment by Calinou** [comment] 2020-04-14 08:22
Ideally, we should disable a node configuration warning if vertex colors *should* be enabled but they aren't, but this sounds difficult to detect programmatically.

Even better, **Vertex Color > Use As Albedo** should be enabled automatically when creating a new SpatialMaterial for use in Particles or CPUParticles.

**Comment by clayjohn** [comment] 2020-04-14 15:37
@Calinou this is documented in the ParticleMaterial documentation here http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/particle_shader.html#vertex-built-ins

I disagree that we should force use_as_albedo on users. Many users use COLOR as a general purpose data container.

**Comment by Zireael07** [comment] 2020-04-14 15:40
That's shading reference, not material/particle documentation, though.

**Comment by clayjohn** [comment] 2020-04-14 15:43
@Zireael07 fair enough. Please also see the Particles Material documentation http://docs.godotengine.org/en/latest/classes/class_particlesmaterial.html#class-particlesmaterial-property-color

**Comment by clayjohn** [comment] 2020-06-20 21:35
Closing as this is documented in multiple places
http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/particle_shader.html#vertex-built-ins 
and
http://docs.godotengine.org/en/latest/classes/class_particlesmaterial.html#class-particlesmaterial-property-color

**Closed by clayjohn** 2020-06-20 21:35 UTC
Labels: documentation, enhancement, topic:core, topic:rendering
