### ISSUE TITLE
Connecting signal from Node panel deselects node

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#46035] opened 2021-02-14 23:36 UTC
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows 10 Pro

**Issue description:**

Godot automatically deselects the node when connecting signals in a scene. See reproduction steps.

When connecting several signals through the Node panel, it's tedious having Godot automatically deselect the node, since you have to reselect the node after connecting each signal.

I don't care for Godot automatically opening the text editor when you connect a signal, but I don't see any reason why deselecting the node is desireable. There's nothing useful in the Node or Inspector panels for a .gd file. I think this is just a bug.

**Steps to reproduce:**

1. Connect a signal from the Node panel
2. Godot automatically opens the gdscript in the text editor for the node signal was connected to
3. The original node selection is replaced with the .gd file being selected

**Comment by Calinou** [comment] 2021-02-15 00:49
I suppose the inspector for the script is opened because the editor technically "edits" the script to make it open in the script editor.

**Comment by wjl** [comment] 2023-06-14 20:50
Just to ping on this, I'm using Godot 4.0.3 in 2023 and came here to report this bug today, but found this was already reported for Godot 3.2.3 more than 2 years ago.

This is a significantly annoying issue when you have multiple signals to connect from a node.

Please consider fixing this, it's very surprising and disconcerting behavior that significantly affects usability.

**Comment by YuriSizov** [comment] 2023-06-26 16:20
This is a duplicate of https://github.com/godotengine/godot/issues/21950, so consolidating there. https://github.com/godotengine/godot/pull/54071 would fix it.

**Closed by YuriSizov** 2023-06-26 16:20 UTC
Labels: enhancement, topic:editor, confirmed, usability
