### ISSUE TITLE
Sporadic mouse movement with MOUSE_MODE_CAPTURED

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#17288] opened 2018-03-05 21:39 UTC
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Using `MOUSE_MODE_CAPTURED` causes the mouse to sporadically move, that is while moving the mouse at constant speed it seems that sometimes it will jump forward greater distance than before.
it's mostly visible when rotating around objects.

This makes first person control feel un-smooth and laggy, which makes `MOUSE_MODE_CAPTURED` unsuitable for it, while it's its main use case.

When trying other mouse modes or rotating with the arrow keys I didn't notice this problem.

Also this problem may require a keen eye to notice, and I don't know if it happens on other machines.

Video of the problem (when mouse is visible it's confined mode, when hidden it's captured mode):
[2018-03-05 04-09-31.zip](https://github.com/godotengine/godot/files/1779513/2018-03-05.04-09-31.zip)

Update:
I tested it a bit more and it seems that if I directly modify the camera's `rotation`, it happens, but if I use `rotate_y()` it doesn't. Which is a bit weird because it seems to be a combination of modifying `rotation` and using `MOUSE_MODE_CAPTURED`?

Might be related to this issue:
https://github.com/godotengine/godot/issues/14855

**Steps to reproduce:**
Try moving around a box mesh while looking at it, with MOUSE_MODE_CAPTURED on.

You can also  alt-tab away, and alt-tab back to the game window, and the mouse will stay visible.
If you try to move the mouse at a constant speed you'll notice that the cursor sometimes jumps greater distance than usual.

**Minimal reproduction project:**
[mouse_jitter.zip](https://github.com/godotengine/godot/files/1782712/mouse_jitter.zip)
Note: `mouse2.gd` uses `rotate_y()`.

**Comment by Akira1San** [comment] 2018-03-05 22:26
Yes i have the same issue in Win 8.1 64b. It seams, that its starts from Godot 2x series.

**Comment by Akira1San** [comment] 2018-04-03 07:51
This issue really prevents from developing FPS/TPS games and even any games, that uses MOUSE_MODE_CAPTURED. It should really be fixed for 3.1.

**Comment by EzraT** [comment] 2018-05-14 18:08
I can confirm this happens on Linux too. (Ubuntu Budgie 18.04 on Nvidia Driver version 390.48)
My character controller uses rotate_object_local to rotate the camera, and the same issues occur with MOUSE_MODE_CAPTURED enabled.

**Comment by GlaDOSik** [comment] 2018-09-21 06:51
I'm also having this kind of problem when strafing around object and keeping the aim at it. The camera jitters which makes the object in the center of screen very unstable looking. But I'm not sure if it's related only to MOUSE_MODE_CAPTURED. Tho without it, the problem is less noticable. Will try to create minimal project with example.

**Comment by Calinou** [comment] 2019-07-14 13:34
I can't reproduce this on commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987 on Linux using the given example project.

**Comment by akien-mga** [comment] 2019-07-15 09:01
Assuming fixed in 3.1.

**Closed by akien-mga** 2019-07-15 09:01 UTC
Labels: bug, platform:windows, topic:core

**Comment by Enhex** [comment] 2019-07-15 20:02
Tested on Godot_v3.1.1-stable_win64 and the jitter is gone.
