### ISSUE TITLE
A "-server" switch for Windows

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#6059] opened 2016-08-06 22:28 UTC
I was exploring the subject of "serverside godot", and since I work mainly on Windows there is no "platform=server_win32" build (just the linux target). I figured out "ok, so I can do OS.get_name() == "server" to check if this scene should run serverside scripts", but what if I'd like to run a server on Windows?

A possible way to do this would be to add a -server switch (executable arg) that would:
- Enable -quiet and -nowindow options
- Explicitly set OS name to Server
  This solution would work on every platform, unless submodules like the filesystem assume that "Server" OS means "use linux drivers".

An alternative would be to add a "server_win32" target, which would probably yield a smaller exe right? Any plans on that?

Or maybe there is a way to read execution arguments from script-level? Thoughts?

**Comment by bojidar-bg** [comment] 2016-08-07 14:01
Duplicate of #2081?

**Comment by WalasPrime** [comment] 2016-08-07 14:16
Not at all. I'm looking for a way to tell my project to run serverside or clientside scripts directly from the console (an optional argument for godot.exe).

**Comment by akien-mga** [comment] 2016-08-08 09:56
The `server` platform should actually be merged back into `platform/x11` IMO, and there should be a `server=yes` compilation argument for Windows, OSX and Linux X11, to be able to build server binaries (headless, lightweight, etc.) for all desktop platforms.

**Comment by akien-mga** [comment] 2016-08-08 09:56
See also #2390.

**Comment by punto-** [comment] 2016-08-08 10:13
The main issue with this is that the window manager layer is not really
abstracted, so the OS class also implements the window system. It can
probably be done, then X11 would become a driver (along with wayland,
windows, maybe osx), and the OS can use a dummy window for a headless
build. We already have the dummy visual server and audio server. The thing
is for most OSs there's only 1 window manager, so at the time it wasn't
worth thinking about it.

**Comment by WalasPrime** [comment] 2016-08-08 10:17
+1 for server=yes compilation argument instead of platform=server

**Comment by akien-mga** [comment] 2017-09-18 11:16
I've opened #11389 as a clearer issue to discuss making the headless version multiplatform.

**Closed by akien-mga** 2017-09-18 11:16 UTC
Labels: feature proposal, platform:windows, topic:buildsystem, topic:core
