### ISSUE TITLE
Shader on a tilemap stops editing

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#50431] opened 2021-07-13 17:34 UTC
### Godot version

3.3 stable

### System information

linux mint

### Issue description

I hope I'm not being silly here, but I add a shader to a tilemap material and on doing so editing is disabled.

With shader: cannot edit (no grid)
![image](https://user-images.githubusercontent.com/12863685/125498828-d95209fd-b8c1-427b-b60d-48b8a89e25c9.png)

With no shader: can edit
![image](https://user-images.githubusercontent.com/12863685/125498978-4c3cddab-f5da-4a29-8047-c6d08e16f7fd.png)

If this is a bug, is there a workaround other than clearing my shader whenever I want to edit my tilemap?

### Steps to reproduce

1. add a shader
2. try to edit

**Comment by Calinou** [comment] 2021-07-13 17:38
Duplicate of https://github.com/godotengine/godot/issues/32002. As a workaround, save the shader to an external `.shader` file and edit it using an external text editor.

**Closed by Calinou** 2021-07-13 17:38 UTC

**Comment by chucklepie** [comment] 2021-07-13 17:50
Thanks. I did search for 'tilemap shader' and other variants :)

btw, why has this been pushed to 4.0, is it just to make use of the new tilemap system? People may not want to use 4.0 for a long time.
