### ISSUE TITLE
Lighting in cube maps generated by ReflectionProbe is incorrect

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#14452] opened 2017-12-09 15:27 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS: Windows 7 64-bit
Godot version: Godot 3 beta 1
GPU Model: Nvidia GTX 760

**Issue description:**

The lighting in cube maps generated by ReflectionProbe is incorrect. For example, the main scene in the minimal example project (link below) looks as follows. In particular, note that the walls are evenly lit:

![picture01](https://user-images.githubusercontent.com/3524191/33796810-1fc34112-dcf4-11e7-8c77-d507458156af.jpg)

However, when we look at a reflecting object, note that that one of the room's walls is completely black, whereas two of the other walls are lit far too brightly:

![picture02](https://user-images.githubusercontent.com/3524191/33796879-430d5de6-dcf5-11e7-8fd8-e8111021f92b.jpg)

Stranger still, if I rerun the game a multiple times, I occasionally get different (and even worse) results, as if the effects are accumulating. (Once or twice the walls turned bright pink, although I unfortunately didn't manage to capture a screenshot!):

![picture03](https://user-images.githubusercontent.com/3524191/33796818-45f5c5b2-dcf4-11e7-8fae-2cd7408b488b.jpg)

**Steps to reproduce:**

I have quickly put together a minimal example project based on [Calinou's FPS demo](https://github.com/Calinou/fps-test) to demonstrate the issue.

Load and run the example project (controls are WASD + Space to jump). Note the incorrect lighting demonstrated in the cube maps when looking at the reflecting prisms.

NB: The ReflectionProbe can be found in res://scenes/lighting.tscn

**Link to minimal example project:**

https://drive.google.com/open?id=1ir3XWASEWqleEu6I209fpAA-hOVqkoeX

**Comment by reduz** [comment] 2017-12-26 16:03
I can't run the attached example (please make something simpler) and can't reproduce with a simple demo.. anyone else can?

**Comment by Calinou** [comment] 2017-12-26 18:03
I can reproduce it (in the editor), notice how the reflected wall is darker than the "real" wall.

![screenshot_20171226_185938](https://user-images.githubusercontent.com/180032/34361922-122aec20-ea6f-11e7-8051-39ab8febed66.png)

**Comment by reduz** [comment] 2017-12-26 18:05
@Calinou That's kind of expected, as reflection can't reflect itself, so reflective objects will look black.

**Comment by bruvzg** [comment] 2017-12-26 18:20
macOS 10.13.2 (AMD FirePro D300), beta 2: one reflected wall looks black, one blue

![reflect](https://user-images.githubusercontent.com/7645683/34362059-d8d5e75e-ea78-11e7-8417-d17930e13097.png)

![reflect2](https://user-images.githubusercontent.com/7645683/34362183-1989e164-ea7a-11e7-9698-d3d0e5d383eb.png)

**Comment by zejji** [comment] 2017-12-26 20:17
@reduz - While I expect the triangular reflecting objects to look black in the reflection, it's the (mostly matte) wall that shouldn't be black.

Do you know why the example project won't run on your computer? It's a very simple example just containing a few meshes, collision objects and some basic FPS controls. (I suppose I could remove the physics objects and controls if that helps...)

**Comment by capnm** [comment] 2017-12-26 23:07
Looks like some strange bug in the godot's object jungle. After opening the instanced Lighting scene (other tab), the rendering in the editor becomes correct:

![before](https://user-images.githubusercontent.com/4047289/34366264-a1752ccc-ea99-11e7-9ee9-01bdb773118d.jpg)
![after](https://user-images.githubusercontent.com/4047289/34366269-a9c256d4-ea99-11e7-8d4a-4a0aaa50065f.jpg)

**Comment by AndreaCatania** [comment] 2018-01-12 00:01
@zejji can you please tell us if this problem still there? since we did couple fix on the shader.

**Comment by reduz** [comment] 2018-01-12 19:42
I may be doing something wrong but i cant reproduce..

**Comment by brainsick** [comment] 2018-01-12 20:46
If the issue is the black wall, then I still see that with <commit> on Ubuntu 17.10 x64, AMD Radeon R9 Fury.  In the Editor and when running the project.

I had to rename the 'owner' variable before the project would run.

![screenshot from 2018-01-12 14-43-06](https://user-images.githubusercontent.com/1111573/34894492-43e5293e-f7a7-11e7-9c51-1421e498f135.png)
![screenshot from 2018-01-12 14-44-55](https://user-images.githubusercontent.com/1111573/34894495-47ed2496-f7a7-11e7-83b5-0eff400d52c8.png)


I had to disable the full screen.  It actually startled me when it took over all 3 monitors.

**Comment by bruvzg** [comment] 2018-01-12 20:54
702e28f26, macOS, wall reflections still black and blue.
![refl_test](https://user-images.githubusercontent.com/7645683/34894810-808ce090-f7eb-11e7-92ec-7fbf075e1e95.png)

**Comment by reduz** [comment] 2018-01-18 11:14
I unfortunately could not reproduce this, not even on mac. lets hope someone else can take a look at it and find the problem.

**Comment by reduz** [comment] 2018-09-06 15:34
I am still unable to reproduce this problem, but given this code will be rewritten for Godot 3.2, that may close the issue. Kicking there.

**Comment by akien-mga** [comment] 2019-11-26 13:21
Is this still reproducible in the current master branch?

**Comment by bruvzg** [comment] 2019-11-26 13:28
> Is this still reproducible in the current master branch?

Yes, it's still the same.

**Comment by akien-mga** [comment] 2020-07-27 12:14
How about now? :)

Also, is it specific to GLES3 or does it also reproduce with GLES2?

It's likely quite different in the `master` branch with Vulkan, can anyone see if a similar issue exists or not?

CC @clayjohn @lawnjelly

**Comment by Calinou** [comment] 2021-09-04 00:05
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-09-04 00:05 UTC
Labels: bug, topic:rendering, confirmed
