### ISSUE TITLE
Actions don't retain any space characters in their name.

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#17757] opened 2018-03-25 11:13 UTC
**Godot version:** 
3.0.2 (steam version)
**OS/device including version:** 
Linux Mint 17.1 'Rebecca' 64-bit MATE

**Issue description:**
When actions are added via GDScript, they no longer contain their spaces. This breaks the code in my 2.1 project which expects the spaces. Before in 2.1 this worked as expected meaning this might very well be a regression.

In example, this code here is placed at the beginning of the program before any manipulation of events in my program occurs: `print(str(InputMap.get_actions()))`
Results in this truncated output: `[cross, square, ... dpaddown, dpadright, dpadup, ... share, triangle]`
The entries for `dpaddown, dpadright, etc.` should contain spaces. I don't mess with the action's at all, including their names. As I said I do manipulate the events themselves, however that comes later in my program's logic. I placed the get_actions() command right under _ready() of the master script.

**Steps to reproduce:**
I'll investigate, but seems it might be as simple as adding an action with a space in the name and then trying to access the actions list to confirm that spaces are no longer there.

**Minimal reproduction project:**
I'll do it if this isn't clear enough.

**Comment by eon-s** [comment] 2018-03-26 10:48
Probably duplicated of #17322, and seems to be fixed already (try a master build).

**Comment by akien-mga** [comment] 2018-03-26 10:53
Indeed, duplicate of #17322 (fixed in the master branch by #17474). Might be fixed in 3.0.3 too if we cherry-pick the relevant change.

**Closed by akien-mga** 2018-03-26 10:53 UTC
