### ISSUE TITLE
Android: Pressing Back button exits the editor when running the project

### ISSUE THREAD

**Issue by Sleff1** [godotengine/godot#61611] opened 2022-06-01 17:53 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

V3.5 and 4.0

### System information

Android 11

### Issue description

When playing a scene whole Godot editor turns of when pressing a back button I just want to close palyed scene and go back to the editor but i can't Sometimes it's working normal and I'm going back to the editor and sometimes not I think that there should be on screen floating button to close the scene and that would be good solution or even opening it as a separate app

### Steps to reproduce

I have no idea looks like it's random

**Comment by Calinou** [comment] 2022-07-10 16:00
As a workaround, add a button on your game that calls `get_tree().quit()` when pressed.

**Comment by WaterExpensive** [comment] 2022-07-30 21:47
> As a workaround, add a visible Button node on your game that calls `get_tree().quit()` when pressed.

Unfortunately, this does not appear to solve the issue (using godot Alpha 13)

https://user-images.githubusercontent.com/34092413/181997131-b2b2d1b9-2fef-4d2e-b66c-ee90e380978a.mp4

**Comment by Sleff1** [comment] 2022-08-12 14:01
I tried everything but nothing helps...

**Comment by gabydoo** [comment] 2022-10-23 19:29
I would like to add that this bug occurs all the time in my current setup:
Operating system: Android 12
Godot version: 4.0 Beta 3
Device: Samsung Galaxy Tab S8

**Comment by m4gr3d** [comment] 2022-11-27 04:36
The behavior is not intentional and caused by an input-related crash bug when returning to the editor from the running project.

The issue has already been fixed on the 3.x branch, but still remains on the 4.x branch.

**Comment by Liquidful** [comment] 2022-11-27 14:00
Just tried the latest 3.x branch, doesn't seem to work.
However I do recall a release candidate of 3.5 that actually fixed the problem, however everything after said candidate stil has the problem.

**Comment by m4gr3d** [comment] 2022-11-27 22:42
> Just tried the latest 3.x branch, doesn't seem to work. 

@Liquidful Do you mean you tried a custom build from the `3.x` branch and the issue is still present (i.e: pressing back from the running project causes the editor to close as well?) ?

**Comment by Liquidful** [comment] 2022-11-28 08:54
Not a custom build, just the official 3.5.1 package found on the website,
And yes, the same issue is still present. (Android 12, Xiaomi Pad 5)

**Comment by m4gr3d** [comment] 2022-11-28 14:58
> Not a custom build, just the official 3.5.1 package found on the website, And yes, the same issue is still present. (Android 12, Xiaomi Pad 5)

@Liquidful That's expected. The fixes are being made for the upcoming 3.6 release as they contained some large refactor to the input logic which we deemed unsuitable for the 3.5.x releases.

We'll soon make that release available through the play store which will provide an easier (and automatic) way to keep up-to-date with the latest improvements.

**Closed** 2023-01-26 15:03 UTC
Labels: bug, platform:android, topic:editor, confirmed, usability

**Comment by Unknownman21229** [comment] 2023-02-17 14:32
I have a problem, no matter how many times i click return, it doesn't return to the editor, it won't quit even with get_tree().quit()

**Comment by m4gr3d** [comment] 2023-02-17 17:36
> I have a problem, no matter how many times i click back, it doesn't return to the editor, it won't quit even with get_tree().quit()

I've seen that behavior when the debugger is on and stopped at a breakpoint. Check to ensure that there's no breakpoints in your gdscript code prior to running the project.

**Comment by LotusLegends** [comment] 2023-10-16 13:16
Same problem happening in my android device 
Infinix Smart 5 android 10, 32-bit
Even i tried godot 4.1.2 and 4.2 beta 
Problem is not solved please fix it 
As soon as possible.

**Comment by SamiunNafis** [comment] 2023-11-15 15:18
> > Not a custom build, just the official 3.5.1 package found on the website, And yes, the same issue is still present. (Android 12, Xiaomi Pad 5)
> 
> @Liquidful That's expected. The fixes are being made for the upcoming 3.6 release as they contained some large refactor to the input logic which we deemed unsuitable for the 3.5.x releases.
> 
> We'll soon make that release available through the play store which will provide an easier (and automatic) way to keep up-to-date with the latest improvements.

It's already been a year and 3.6.0.beta.3 has been released yet I'm still facing this issue. I've installed the official app from play store still facing the issue

**Comment by Calinou** [comment] 2023-11-15 15:23
If this only occurs with a script error, see https://github.com/godotengine/godot/issues/77272.

**Comment by m4gr3d** [comment] 2023-11-15 15:49
> > > Not a custom build, just the official 3.5.1 package found on the website, And yes, the same issue is still present. (Android 12, Xiaomi Pad 5)
> > 
> > @Liquidful That's expected. The fixes are being made for the upcoming 3.6 release as they contained some large refactor to the input logic which we deemed unsuitable for the 3.5.x releases.
> > 
> > We'll soon make that release available through the play store which will provide an easier (and automatic) way to keep up-to-date with the latest improvements.
> 
> It's already been a year and 3.6.0.beta.3 has been released yet I'm still facing this issue. I've installed the official app from play store still facing the issue

@SamiunNafis there was a second fix needed which is being added by https://github.com/godotengine/godot/pull/84279.
That fix hasn't been merged yet but will be part of the next beta release.
