### ISSUE TITLE
Godot 4 load_threaded_get_status does not work properly

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#68754] opened 2022-11-16 23:51 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

It's the same issue as in : https://github.com/godotengine/godot/issues/56882
this function does not work properly `load_threaded_get_status `, some times it does and sometimes it does not and the game crash with no errors

### Steps to reproduce

Same as in this issue : https://github.com/godotengine/godot/issues/56882

**Comment by clayjohn** [comment] 2022-11-17 07:09
Duplicate of #56882

**Closed by clayjohn** 2022-11-17 07:09 UTC
