### ISSUE TITLE
Some input keys not working normally

### ISSUE THREAD

**Issue by raietracer** [godotengine/godot#61265] opened 2022-05-21 23:38 UTC
### Godot version

3.2.3.stable, 3.3.stable, 3.4.stable, 3.4.4.stable

### System information

Windows 10

### Issue description

I defined some standard inputs in my Project Settings: Input Map (WASD for 2D movement)
I scripted the movement for a kinematic as I normally would.
Playtesting the game I noticed that my W and S keys were only being read for a couple frames before the game acts like I lifted my finger off the key.
I set up joypad inputs and plug in my wired xbox controller and it read normally.  Up and Down continue as long as the stick is tilted respectively.  So I added D-pad inputs and it also works normally.
Continuing that train of though back on the keyboard, I added print() statements during the input handling and tried the arrow keys and they were bugged similarly to WASD (in that vertical movement halted shortly after down-press)

It seems that for whatever reason Godot treats my keyboard's W, S, Up, and Down arrow keys differently from the rest.
There may be more keys receiving this discrimination, the only keys I confirmed were bugged were those 4 ^
I read input in one function and called that function in _physics_process()
I also tried using _process() and it acts identically as far as I can tell.

The movement doesn't stutter and flicker, it just halts very quickly after pressing the button down, no matter how long the button is held.  Sometimes it works for a couple calls before halting, once it even lasted nearly two seconds of processing first, but it doesn't start moving again on its own.  Generally moving side-to-side for a while before testing the W / S / UP / DOWN keys results in the vertical movement lasting longer before halting.

I saw a thread similar to this, but the user had a nearly opposite issue of their controller's input being treated just like my keyboard's inputs are and their keyboard's inputs working fine, my issue is vice versa.

### Steps to reproduce

Add Input actions for up/down/left/right and assign W/A/S/D respectively.
Setup some graphics to visualize the test and create a KinematicBody2D player.
In the player script, set a function to read input and call that function in whichever _process() you wish.
In the "read input" function, handle each input case respectively with velocity modifications normalized at the end.
: Notice left-to-right movement acts normally while up-and-down movement halts shortly after pressing the input.

### Minimal reproduction project

[Simplest.zip](https://github.com/godotengine/godot/files/8748516/Simplest.zip)
Both Controller and keyboard have 2 options for inputs in this example and on my end all movement works except vertical movement initiated using the keyboard.

**Comment by Calinou** [comment] 2022-05-22 00:06
Related to https://github.com/godotengine/godot/issues/45628 (possible duplicate)?

**Comment by raietracer** [comment] 2022-05-23 01:52
> Related to #45628 (possible duplicate)?

This is the thread I mentioned seeing, while the issue seems similar my results are different.  The vertical movement works fine using a wired xbox 360 controller in my project, it's just the keyboard that bugs for me.

**Comment by raietracer** [comment] 2022-05-23 01:57
https://github.com/godotengine/godot/issues/45628#issuecomment-782840254

The current workaround I've implemented is to remap axis inputs to their own actions on the project settings' Input Map.
I read each action and handle them as if they were the same using a script.  The linked comment on the related thread helps for anyone running into this bug.

**Comment by madmiraal** [comment] 2022-05-27 04:40
This is a duplicate of #45628.

**Closed** 2022-05-27 07:58 UTC
Labels: bug, topic:input
