### ISSUE TITLE
Please disable "delete all" script option in godot 2.1.4

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#14824] opened 2017-12-19 13:26 UTC
**Godot version:**
Godot 2.1.4

**OS/device including version:**
Win7

**Issue description:**
"Delete all" right click option in script editor is very annoying. This option delete all the script and have not undo. Clicking that by error can destroy many hours of work. This option should never have existed, we have "del" key!!!!

**Steps to reproduce:**
Open your favorite project, or one with no version control system, open the most complex script, right click in script editor, select delete all and laught very strong.

**Minimal reproduction project:**
Any project in your computer is usable, laughting is assured.

**Comment by Hinsbart** [comment] 2017-12-19 14:33
Duplicate of #8533

**Closed by Hinsbart** 2017-12-19 14:33 UTC
Labels: enhancement, topic:editor, usability
