### ISSUE TITLE
VolumetricFog breaks and recalculates when viewports are resized, then updates only when the Editor is redrawn

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#62796] opened 2022-07-06 21:30 UTC
### Godot version

4.0 Alpha11

### System information

Win Nvidea 765M

### Issue description

See "steps to reproduce" below.

https://user-images.githubusercontent.com/47016402/177645227-d2ccd09a-9e4d-43cc-a7f0-91ae7d01493a.mp4

I have no idea what is going on here besides my description, but if the fog needs to be recalculated for whatever reason, I would expect it to update back to the desired density/look according to the settings _without_ having to move the mouse or provide any other sort of input. 

### Steps to reproduce

1. Enable VolumetricFog in the WorldEnvironment
2. Add Camera and enable Preview Camera in a separate Viewport
3. Resize Viewports by dragging the seperation
4. Don't move mouse cursor to observe VolumetricFog not updating back to it's original and intended density/look
5. move mouse cursor slowly to force the Engine to update VolumetricFog. Observe how it only updates incrementally: If you stop moving the mouse, it will stop updating back to intended density/look according to the VolumetricFogs settings.
6. move mouse cursor fast to force VolumetricFog to update all the way back to the normal - it's the settings.

### Minimal reproduction project

[volumetric_fog_cam_preview_bug.zip](https://github.com/godotengine/godot/files/9058124/volumetric_fog_cam_preview_bug.zip)

**Comment by Calinou** [comment] 2022-07-06 21:41
Duplicate of https://github.com/godotengine/godot/issues/62794 (same cause).

**Closed by Calinou** 2022-07-06 21:41 UTC
