### ISSUE TITLE
Occlusion Culling?

### ISSUE THREAD

**Issue by TheMisteryMan** [godotengine/godot#27788] opened 2019-04-07 23:15 UTC
Hello,I'm interested in using Godot to create a 3D game, but I've heard that there in't occlusion culling.  
  
I saw a comment from late last year about it being added in the next release, but when asked, they wouldn't answer on whether that meant 3.2, or 4.0, etc...

Sorry if this has been asked before, I couldn't find anything that seemed like this while searching through closed/opened issues.

**Comment by TheDuriel** [comment] 2019-04-07 23:53
https://github.com/godotengine/godot/issues/22048#issuecomment-421475081

it's on the roadmap. and will be added when able.

https://github.com/godotengine/godot-roadmap/blob/master/ROADMAP.md

**Comment by clayjohn** [comment] 2019-04-08 04:46
Also note, these sorts of questions shouldn't be asked here. Please look into the various [community channels](http://docs.godotengine.org/en/latest/community/channels.html) for places to ask questions like this. Issues are for posting about bugs/suggestions.

**Comment by Chaosus** [comment] 2019-04-08 06:38
Duplicate of #22048.
I've also added "Occlusion culling" to the name of #22048 to avoid further duplicated issues

**Closed by Chaosus** 2019-04-08 06:38 UTC
