### ISSUE TITLE
Shadows cover sprites when set to show behind sprite

### ISSUE THREAD

**Issue by Ken-Vermette** [godotengine/godot#74265] opened 2023-03-03 01:26 UTC
### Godot version

4.0.stable.official

### System information

Linux (KDE Neon 5.26), X11, AMD Vega64

### Issue description

Shadows via LightOccluder2D are cast over top sprites, regardless of order.

![Screenshot_20230302_133948](https://user-images.githubusercontent.com/7060411/222604723-5950f86f-2a64-4430-a27d-699197cd0c1d.png)
![Screenshot_20230302_134001](https://user-images.githubusercontent.com/7060411/222604726-d9f71161-7a2b-4455-ae61-71f5828c175b.png)

### Steps to reproduce

1. Create a Sprite2D with a CanvasTexture containing a diffuse layer and normal map
2. Add a LightOccluder2D as a child of the sprite, set CanvasItem > Show Behind Parent to true
3. Run with a light source nearby

Expected result: Shadow should not cover the parent sprite
Actual result: Shadow covers the parent sprite

### Minimal reproduction project

[gd-shadow-bug.zip](https://github.com/godotengine/godot/files/10877235/gd-shadow-bug.zip)

**Comment by Calinou** [comment] 2023-03-03 02:02
For reference, this was cross-posted on Reddit: https://www.reddit.com/r/godot/comments/11gakvf/godot_40_getting_shadows_to_not_cover_sprites/

**Comment by naturally-intelligent** [comment] 2023-04-16 17:13
Can confirm this, I tried playing with a variety of settings, with same issue. Glad I found this ticket so I can stop wondering

**Comment by riazey** [comment] 2023-04-22 18:12
This feature would be GREATLY appreciated, especially for top-down. It's actually #1 on my "I wish godot did this" list! I see a lot of people over time ask about it on reddit/discord including myself.

There were a few people who said "this will be better in Godot 4.0" but I haven't seen anything aaa~! T^T Shadows not overlaying sprites like this seems to me to be pretty essential to- well using lights haha!

Right now it's nearly impossible to use without workarounds, [complex setups](https://www.imaginaryrobots.net/posts/2022-02-03-understanding-light2d-masks-godot/), or really hacky methods which usually produce visual bugs. It's not particularly intuitive either. Most answers you find on the internet right now say "use culling/masks" but then reveal they've never used it themselves or know how to implement it haha!

I beg for this feature to be a thing, or for someone to come forth with a method that isn't crazy complex! I will literally die for you if you do.  (╯‵^′ )╯︵┻━┻

**Comment by ErrantOverflow** [comment] 2023-04-22 21:53
Same here

**Godot version**
4.0.2-4

**System information**
Linux (6.2.11-arch1-1 Gnome), X11, GTX 1660 Ti Mobile laptop
running the entire session with dedicated graphics with optimus-manager

Setting the Cull Mode to "CounterClockWise" on the LightOccluder2D has the following result

![image](https://user-images.githubusercontent.com/65794451/233807953-20bb044c-0621-4887-82cf-5a353fc27285.png)

You can instead add a new CanvasItemMaterial to the sprite and sets it's Light Mode to "Unshaded", which makes the shadows not clip through the sprite, however this has the side effect of having a sprite that is not affected by the light2D, so it looks out of place

![image](https://user-images.githubusercontent.com/65794451/233808044-c2973582-3092-4bbe-bfd5-b243ec7a7920.png)

I've tried all sorts of crazy combinations of changing the Light and Visibility masks of the occluder, light source and sprite to no effect.

**Comment by riazey** [comment] 2023-04-22 22:42
May be related to [this issue](https://github.com/godotengine/godot/issues/74265) and also noticed it was removed from the 4.1 roadmap- :(

**Comment by Calinou** [comment] 2023-04-22 22:47
> May be related to [this issue](https://github.com/godotengine/godot/issues/74265) and also noticed it was removed from the 4.1 roadmap- :(

You've linked to the same issue you commented on (wrong link?).

**Comment by riazey** [comment] 2023-04-23 05:00
> > May be related to [this issue](https://github.com/godotengine/godot/issues/74265) and also noticed it was removed from the 4.1 roadmap- :(
> 
> You've linked to the same issue you commented on (wrong link?).

Fixed, I think I was originally going to comment there, thanks

**Comment by hmturnbull** [comment] 2023-06-23 20:22
I worry that using light masks would lead to the shadow not affecting other sprites that it really should affect, even beyond its own object.

I keep thinking the LightOccluder2D should have a boolean property like `exclude_owner` that, when checked, would make it so the occluder doesn't affect its `owner` or any children thereof?

Would that work?

**Comment by Calinou** [comment] 2023-07-03 10:07
- Duplicate of https://github.com/godotengine/godot/issues/64939.

**Closed by Calinou** 2023-07-03 10:07 UTC
Labels: topic:rendering, confirmed, topic:2d

**Comment by Barabah** [comment] 2023-10-10 10:55
Here is my solution.
First of all, any light source which must to cast shadows from, should have two pointLight2d nodes, one for those objects which will be reciev the shadows and second which for those which wont. Between first and secon light only two diferences, first in Range property Item Cull Mask layer must be on default 1, like his Item Cull Mask layer in Shadow property which must be enabled, the second light in Range Item Cull Mask layer must be 2 and shadows shuold be disabled at all.
 Bellow screenshots of the settings, i've marked importand red
 
![Desktop Screenshot 2023 10 10 - 13 39 04 45](https://github.com/godotengine/godot/assets/70694365/34841588-dc34-4de8-a7bf-001d19cb8350)
![Desktop Screenshot 2023 10 10 - 13 39 09 24](https://github.com/godotengine/godot/assets/70694365/9cbcb36c-cf5f-4c43-8a74-d3afc8b3fee7)
![Desktop Screenshot 2023 10 10 - 13 39 14 18](https://github.com/godotengine/godot/assets/70694365/d829890b-bae2-451f-8df9-5bdcfcf2b33c)
![Lamp_01](https://github.com/godotengine/godot/assets/70694365/d9e117ee-9f93-41b0-8735-b94a5f1fb1c8)
![lamp_02](https://github.com/godotengine/godot/assets/70694365/c50d85c1-eb70-425d-9fe6-1578b6f71e02)
![lamp_03](https://github.com/godotengine/godot/assets/70694365/433cc497-4b65-445b-a896-2d0a3cdc71ec)
![lamp_04](https://github.com/godotengine/godot/assets/70694365/d8200f8b-5a45-43aa-b229-c781f57646db)
![player_01](https://github.com/godotengine/godot/assets/70694365/f073ee26-8afd-4f2b-83b9-185999a2e19c)
![player_02](https://github.com/godotengine/godot/assets/70694365/9b0ec060-0879-4448-bd84-b169a356976b)
