### ISSUE TITLE
macOS: documentation font is small after re-opening a project

### ISSUE THREAD

**Issue by teki** [godotengine/godot#6033] opened 2016-08-04 12:39 UTC
**Operating system or device - Godot version:**

macOS 10.11.6 (retina)
godot 2.1 rc2

**Issue description** (what happened, and what was expected):

Font in the documentation becomes very small after re-opening a project.

**Steps to reproduce:**

- create a project
- open documentation
- close project
- re-open the project
- click on the documentation in the file/doc selector
- see photo

before:
<img width="1032" alt="screen shot 2016-08-04 at 10 37 20 pm" src="https://cloud.githubusercontent.com/assets/5516/17401978/0d48781a-5a94-11e6-9841-1fe463332f37.png">

after re-open:
<img width="1042" alt="screen shot 2016-08-04 at 10 34 13 pm" src="https://cloud.githubusercontent.com/assets/5516/17401979/0d9f552c-5a94-11e6-837f-cdad0fa73a39.png">

** workaround **
Close the docs and re-open them.

**Comment by bojidar-bg** [comment] 2016-08-04 14:18
I guess, duplicate of #5995.

**Closed by bojidar-bg** 2016-08-04 14:18 UTC
