### ISSUE TITLE
Docs enhancement for v3 - add instructions how to capture screenshot

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#15976] opened 2018-01-22 16:46 UTC
**Godot version:**
v3

**Issue description:**
I haven't found any instructions how to capture screen shot for v3 in any of the resources commonly available. viewport.queue_screen_capture() has been removed since 2 so all info found about it is useless now.

Only thanks to https://github.com/godotengine/godot/issues/8371 and liberal experimenting did I came up with: 

    var data = get_viewport().get_texture().get_data()
    data.flip_y()
    data.save_png('screenshot.png')

If example is wrong, there is better way or it is already covered in docs but I couldn't find please delete this request.

**Comment by volzhs** [comment] 2018-01-22 20:09
https://github.com/godotengine/godot-demo-projects/blob/master/viewport/screen_capture/screen_capture.gd

```gdscript
	get_viewport().set_clear_mode(Viewport.CLEAR_MODE_ONLY_NEXT_FRAME)
	# Let two frames pass to make sure the screen was captured
	yield(get_tree(), "idle_frame")
	yield(get_tree(), "idle_frame")

	# Retrieve the captured image
	var img = get_viewport().get_texture().get_data()
  
	# Flip it on the y-axis (because it's flipped)
	img.flip_y()

	# Create a texture for it
	var tex = ImageTexture.new()
	tex.create_from_image(img)

	# Set it to the capture node
	get_node("capture").set_texture(tex)
```

should add top 3 lines of this example.

**Comment by nadnam** [comment] 2018-01-22 20:35
Thank you for that, I completely forgot about updated demos. I only used v2 ones in the beginning. Hopefully this comment will be easily searchable via google.

**Comment by trollworkout** [comment] 2018-01-23 00:23
your wanna get the window viewport texture and save it as a file.

**Comment by wyattbiker** [comment] 2018-10-13 23:28
Why does `var img = get_viewport().get_texture().get_data() `get the image flipped?

**Comment by avencherus** [comment] 2019-01-31 14:31
Wondering why get_data() stalls the game.  Is it locking the thread?

**Comment by burstina** [comment] 2019-02-21 22:49
yes, in beta5 `get_viewport().get_texture()` gets the texture flipped h and w.
Guess it is a bug

**Comment by akien-mga** [comment] 2019-02-22 09:38
Closing as it's covered in the demo linked by @volzhs. If there's a need for adding it to a tutorial in the online docs, please open an issue on https://github.com/godotengine/godot-docs

**Closed by akien-mga** 2019-02-22 09:38 UTC
Labels: documentation

**Comment by jdknox** [comment] 2020-01-08 11:05
`viewport.get_texture().get_data()` doesn't capture any of the rendered fonts or `draw_rect` calls on sprites.  Is this by design?
