### ISSUE TITLE
Blender-like shortcuts for moving, scaling and rotating Meshes in 3D

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#15969] opened 2018-01-22 10:51 UTC
Would love to see some Blender like shortcuts for manipulating objects in 3D space in Godot. But only for Scale, Move, Rotate (same as Gizmos)  

**Keys**
G = Grab/Move
S = Scale 
R = Rotate
ESC = exit move/scale/rotate mode and cancel changes
left mouse click or ENTER = accept changes
mouse pos = freeform move/scale/rotate

KEY <optional: AXIS> <optional: UNITS>

Of course these should also be remap-able in shortcuts.

These would be different than Q  Tool Select, W  Tool Move, E Tool Rotate, R Tool Scale
The above shortcuts can be changed to keys 1 Tool Select 2 Tool Move 3 Tool Rotate 4 Tool Scale or R Rotate can be moved to Shift+R instead. Either way 

**For Example**

press G to begin grab/move mode (freeform grab/move based on mouse pos)
press ESC to escape grab/move mode and cancel changes 
click L mouse or press ENTER to accept

press R to begin rotate (freeform rotate in any direction based on mouse pos)
press ESC to escape rotate and cancel all changes
click L mouse or press ENTER to accept

press G X  to grab/move in X axis only (grab/move based on mouse pos)
click L mouse or press ENTER to accept

press G Y -2 to grab/move -2 units in Y axis
click L mouse or press ENTER to accept (however if you move the mouse it reverts to G Y and mouse pos )

press S X 1.5 to scale by  x 1.5 in X axis
click L mouse or press ENTER to accept (if you move the mouse reverts to S X and mouse pos)

press R Y 45 to rotate about Y axis 45 degrees
click L mouse or press ENTER to accept (if you move the mouse reverts to R Y and mouse pos)

Actions change dynamically as you type
R Y 45 <backspace erase
R Y 4
RY 49

**Comment by alex9099** [comment] 2018-01-22 11:02
Agree

**Comment by mysticfall** [comment] 2018-01-22 11:11
I really like the idea, because I can see how it aligns with the effort Godot's making in its attempt to develop a consistent open source workflow as described in the documentation:

> Default 3D scene navigation controls are similar to Blender (aiming to have some sort of consistency in the free software pipeline)

**Comment by ZX-WT** [comment] 2018-01-22 12:37
I believe this has been mentioned somewhere that godot's shortcut is not following the idea behind blender, but I don't remember the detail, however, I do agree that entering the axis and number is a good feature.

**Comment by JayFontenot** [comment] 2020-02-19 17:57
Similar to #3995. I would also really appreciate this. After getting used to Blender's way of manipulating objects, it's hard/mildly annoying to go back to using gizmos for everything. It just feels like such a faster and more seamless workflow manipulation objects like Blender does, compared to using gizmos all the time.

**Comment by Calinou** [comment] 2020-02-19 20:15
Duplicate of #3995 indeed :slightly_smiling_face:

**Closed by Calinou** 2020-02-19 20:15 UTC
Labels: enhancement, topic:editor, usability
