### ISSUE TITLE
Stop scrolling while drag and drop

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#24603] opened 2018-12-26 11:39 UTC
**Godot version:**
3.1 Alpha 4

**OS/device including version:**
Windows 10

**Issue description:**
It's quite annoying that the FileSystem always scrolls up when you want to (for example) put an audio file into a variable.
It should scroll only when the cursor hovers over the "FileSystem" area

**Steps to reproduce:**
![2018-12-26_12-32-55](https://user-images.githubusercontent.com/42905358/50444855-0c781f80-090b-11e9-9cc9-ee54d009c11e.gif)

**Comment by groud** [comment] 2018-12-26 11:42
Duplicate of  #23375

**Closed by groud** 2018-12-26 11:42 UTC
