### ISSUE TITLE
MacOS crash when selecting an empty scene tab

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#61869] opened 2022-06-09 23:03 UTC
### Godot version

v4.0.alpha9.official

### System information

macOS Monterey - 12.4 - M1 - Vulkan

### Issue description

When creating a new scene and selecting an empty tab, the editor crashes:

https://user-images.githubusercontent.com/2206700/172959291-6df9ccb5-139d-4ed9-8596-71a8938d4a31.mp4

### Steps to reproduce

1. Open a new empty project
2. Create a new scene
3. select a root node
4. click on another empty scene tab

### Minimal reproduction project

It is not needed since this happens on an empty project already.

**Comment by Calinou** [comment] 2022-06-09 23:15
Duplicate of https://github.com/godotengine/godot/issues/61654.

**Closed by Calinou** 2022-06-09 23:15 UTC
