### ISSUE TITLE
2d physics: Lots of RigidBodies produce many collisions and won't get to "sleep"

### ISSUE THREAD

**Issue by marynate** [godotengine/godot#515] opened 2014-06-15 05:20 UTC
Testcase project: 

https://www.dropbox.com/s/9pijuuoo1zzlqgf/test_physics_2d_sleep.zip

Reproduce: 

click "Generate" button several times, observer that when island getting lot's rigibody, it will take forever to turn into sleep state (turn into red color)

**Comment by kubecz3k** [comment] 2015-10-30 12:31
I'm unsure what is current status of the bug, could you @marynate test it on current nightlies?

**Comment by akien-mga** [comment] 2016-04-18 18:43
I tried the test project and could still reproduce the bug. Here's a version fixed for recent API changes (active --> !sleeping): [test_physics_2d_sleep.zip](https://github.com/godotengine/godot/files/224486/test_physics_2d_sleep.zip)

As @reduz pointed it out, the issue is that all RigidBodies seem to produce an endless stream of mini collisions, so they'll never get to sleep.

To bugsquad: We have several duplicates of this issue I think, don't hesitate to close them as duplicates of this one when stumbling on them.

**Comment by akien-mga** [comment] 2017-06-28 12:50
Closing as duplicate of the more recent #515.

**Closed by akien-mga** 2017-06-28 12:50 UTC
Labels: bug, confirmed, topic:physics
