### ISSUE TITLE
Objects of custom instance classes cannot be decoded by marshalls

### ISSUE THREAD

**Issue by tlloancy** [godotengine/godot#84552] opened 2023-11-06 22:32 UTC
### Godot version

4.1.3

### System information

Windows 10

### Issue description

E 0:00:47:0705   Message.gd:46 @ from_raw(): Class 'FileAccess' or its base class cannot be instantiated.
  <Erreur C++>   Condition "!ti->creation_func" is true. Returning: nullptr
  <Source C++>   core/object/class_db.cpp:341 @ instantiate()
  <Pile des appels>Message.gd:46 @ from_raw()
                 WebRTCClient.gd:30 @ _process()

`from_raw() is a byte_to_var_with_objects() function`

### Steps to reproduce

try to decode an array containing a FileAccess object among many other vars

byte_to_var_with_objects([FileAccess.open(path, FileAccess.READ), a, b, c, d, ...])

### Minimal reproduction project

N/A

**Comment by fire** [comment] 2023-11-07 02:40
@Faless Any ideas why this would happen? Do we need a better reproduction project?

**Comment by tlloancy** [comment] 2023-11-07 23:27
nonetheless thank you for that because it made me rethink my code twice

**Comment by Faless** [comment] 2023-11-08 06:20
Custom instance classes like `FileAccess`, cannot be decoded since they do not have a constructor, and the remote end have no way of knowing how to instantiate the object.

Transferring `FileAccess` objects also doesn't make sense, what are you trying to achieve?

**Comment by AThousandShips** [comment] 2023-11-08 10:11
Should probably error when trying to encode an object that can't be instantiated, and handle the error on the decoding side with more direct information

But the use case is indeed broken to begin with

**Closed** 2023-12-19 19:37 UTC
Labels: enhancement, discussion, topic:core
