### ISSUE TITLE
WorldEnvironment renders sky in engine but not in game.

### ISSUE THREAD

**Issue by danielkariv** [godotengine/godot#67483] opened 2022-10-16 11:06 UTC
### Godot version

4.0.beta.3

### System information

MacOS 12.6, Macbook M1, Vulkan

### Issue description

There seems to be an issue with rendering the sky element of WorldEnvironment. 
By default, without setting an custom WorldEnvironment, the sky is shown as gray in game while in engine it render just as expected:
<img width="710" alt="Screen Shot 2022-10-16 at 13 48 08" src="https://user-images.githubusercontent.com/38776931/196031157-bf2eef6f-6a3f-4d1a-b2d7-3e380fe14711.png">
<img width="710" alt="Screen Shot 2022-10-16 at 13 48 33" src="https://user-images.githubusercontent.com/38776931/196031161-d01c0865-1857-41ba-a89e-d2d89750f72d.png">
(In a new project, the bugged sky isn't gray but dark purple like the following cases)

I tried to set a custom WorldEnviorment and choose different sky options but there are issues rendering them too
For example:
In Engine vs Game of ProceduralSky :
<img width="710" alt="Screen Shot 2022-10-16 at 13 44 52" src="https://user-images.githubusercontent.com/38776931/196031220-ed0c1d79-bb11-47fd-8342-cfc6d4265d44.png">
<img width="710" alt="Screen Shot 2022-10-16 at 13 45 25" src="https://user-images.githubusercontent.com/38776931/196031224-6e1c5635-b418-4af2-bf7c-f4209b0f666b.png">
In Engine vs Game PhysicalSky:
<img width="710" alt="Screen Shot 2022-10-16 at 13 45 57" src="https://user-images.githubusercontent.com/38776931/196031227-b06150c8-0686-4618-ab20-65dd6af94f88.png">
<img width="710" alt="Screen Shot 2022-10-16 at 13 46 10" src="https://user-images.githubusercontent.com/38776931/196031230-b4c0c450-c15d-4193-ad97-17c4b4143152.png">
Setting Custom Color as sky does seems to work fine though. 

I tried to use both Forward Plus and Mobile rendering backend. This issue started with beta 3.

### Steps to reproduce

Steps to follow:
Create new project, add 3d camera, and try to run it. By default it should be show a purple background. I added a sample code that has few meshes and WorldEnvironment node.

### Minimal reproduction project

[Sky Testing.zip](https://github.com/godotengine/godot/files/9794279/Sky.Testing.zip)

**Comment by Calinou** [comment] 2022-10-16 17:46
Duplicate of https://github.com/godotengine/godot/issues/67449.

**Closed by Calinou** 2022-10-16 17:46 UTC
Labels: bug, topic:rendering, topic:3d
