### ISSUE TITLE
'Corrupted header in binary project.binary (not ECFG)' with exported PCK over 2.1 GB (32-bit signed int)

### ISSUE THREAD

**Issue by ZZZZZcode** [godotengine/godot#27168] opened 2019-03-17 16:44 UTC
**Godot version:**

3.1

**OS/device including version:**

Windows 7 x64

**Issue description:**

Cannot run exported project (there are 2 files in the folder *.EXE and *.PCK)
Get error:
--
Corrupted header in binary project.binary (not ECFG)
core/project_setting.cpp:484
Error: Could not load gme data at path '.'. Is the .pck file missing?
--
Looks like is something wrong with "project.binary" file in the PCK archive.
IMPORTANT THING:
If PCK file less that 2.1 GB all runs ok. If PCK file more than 2.1GB - i get error.

**Steps to reproduce:**
Just export project with PCK file size more than 2.1GB

**Minimal reproduction project:**
Sorry cannot provide this :(

**Comment by Galileo53** [comment] 2019-03-19 09:42
Same problem with our project. It works if smaller than 2GB but fails if bigger than 2GB.
This is a showstopper because we cannot shrink the project below 2GB.

**Comment by ZZZZZcode** [comment] 2019-03-19 09:51
Yeah... I`m sure its a nasty bug. Maybe the solution is separate resources in several PCK files. 
Then use:
ProjectSettings.load_resource_pack(....)

**Comment by akien-mga** [comment] 2019-03-19 15:05
CC @hpvb @RandomShaper

**Comment by bruvzg** [comment] 2019-03-19 15:27
I can partially confirm this on macOS, Godot unable to store individual large files inside PCK:
* During export Godot is trying to load whole file into `Vector<uint8_t>`.
* `get_file_as_array`, `get_buffer`, `set_buffer` function use `int` type size and files are truncated.
* Resulting PCK can be more than 2 GB, and I didn't reproduce any corruption of other files in the PCK.
* Windows `get_len` implementation also use `int` (https://github.com/godotengine/godot/blob/master/drivers/windows/file_access_windows.cpp#L222).

**Comment by bruvzg** [comment] 2019-03-19 15:54
Also, Unix file access implementation uses `long x = ftell(...)` in multiple places.

AFAIK by default `ftell` / `fseek` are limited to 32-bits. Probably `fseek64` / `_fseeki64` (or whatever platform specific equivalents are) should be used instead in both Unix and Windows implementations.

**Comment by RandomShaper** [comment] 2020-01-08 20:35
Moved this one to 4.0, since file access will keep being 32-bit in 3.x (and that's the cause of the problem).

**Comment by akien-mga** [comment] 2020-10-01 09:24
Closing as superseded by https://github.com/godotengine/godot-proposals/issues/400 to keep everything in the same place.

**Closed by akien-mga** 2020-10-01 09:24 UTC
Labels: bug, high priority, platform:windows, topic:core

**Comment by Patashu** [comment] 2024-06-02 15:25
Adding a comment to this because this is the top google search result for this error message and there is a totally unrelated reason why it can happen!

How it happened: Apparently if you upload HTML5 builds to itch.io in multiple succession, and some people played on the intermediate build, their browser will cache some but not all of the HTML5 files, allowing them to attempt to play the game in an inconsistent state.

The solution: tell them to Ctrl+F5 lmao. No idea if there's an automateable solution besides 'don't do that'

**Comment by LightningStorm0** [comment] 2025-01-21 19:56
Is there a possibility that the itch.io caching bug has to do with the browser and not itch.io? I'm this error even when using the builtin http server in Godot.

I hard refresh the page and the game works one, but the next time I try to run it (even just a regular refresh) it gives me the error again.

![Image](https://github.com/user-attachments/assets/1af14bab-bd73-46f5-8951-759661376b7c)
![Image](https://github.com/user-attachments/assets/559efdce-80e5-4d6f-aa77-862b819af79d)

**Comment by Calinou** [comment] 2025-01-21 20:46
@LightningStorm0 Please continue the discussion on https://github.com/godotengine/godot/issues/101643.
