### ISSUE TITLE
Saving GDScript enum crashes the editor

### ISSUE THREAD

**Issue by caimantilla** [godotengine/godot#75458] opened 2023-03-29 12:17 UTC
### Godot version

4.0.1.stable.custom_build [19501f8eb]

### System information

macOS Ventura 13.2.1, GLES3, arm64

### Issue description

Saving an enum in the built-in editor causes a crash. This happens across multiple projects, even when the enum keys have their values automatically assigned, or when the trailing comma is omitted. I tested both the official build and 4.0 commit [19501f8eb] (built without x86 support) of Godot 4.0.1, and it still happens. It does not happen in Godot 4.0.

Update:
Saving from the File dropdown does not cause a crash.
However, if I use the save hotkey (Command + S) even after this, the editor crashes.

https://user-images.githubusercontent.com/103377610/228531532-a5de7748-aac3-4b18-aea6-8e4281108160.mp4

### Steps to reproduce

Open Godot 4.0.1.
Create a new GDScript resource.
Write an enum, then use the save hotkey.
Crash.

### Minimal reproduction project

N/A

**Comment by caimantilla** [comment] 2023-03-29 14:36
> > ### Steps to reproduce
> > Open Godot 4.0.1.
> > Create a new GDScript resource.
> > Write an enum, then use the save hotkey.
> > Crash.
> > ### Minimal reproduction project
> > N/A
> 
> Can't reproduce, more details needed. Does it happen in a blank new project? If no, minimal reproduction project would be needed too.

It does occur on a new project as well.

After some more testing, it only happens with a tool script while a scene is open (even if they're unrelated), if the "save scene" command is used. The "save script" command doesn't cause a crash.

Even with the 2D editor focused rather than the script editor, and using the `scene dropdown -> save scene` button instead of the "save scene" hotkey (Command + S), it still crashes.

Here's a reproduction project. In the test script, create a new enum while the test scene is open, then save the scene.

[temp.zip](https://github.com/godotengine/godot/files/11102003/temp.zip)

**Comment by kleonc** [comment] 2023-03-29 15:43
> Here's a reproduction project. In the test script, create a new enum while the test scene is open, then save the scene.
> 
> [temp.zip](https://github.com/godotengine/godot/files/11102003/temp.zip)

@caimantilla Still can't reproduce, can you list a detailed list of steps? You've said it happens only for a tool script but the script in the MRP has `@tool` commented out... no idea at which step I'm supposed to uncomment it to trigger the crash etc. Tried few different ways, no single crash for me. I've tried e.g.:

1. Open [MRP](https://github.com/godotengine/godot/files/11102003/temp.zip).
2. Open `res://tscne.tscn` (double click in the file system dock).
3. Open `res://new_script.gd` (double click in the file system dock).
4. Uncomment `@tool` line.
5. Write at the bottom of that script:
```gdscript
enum AnotherOne {
	ONE = 1,
}
```
6. From the menu: `Scene` -> `Save Scene`.
7. No crash.

And to be sure: does it happen also in v4.0.1.stable.official [cacf49999] or just in a custom build?
(I've tried both v4.0.1.stable.official [cacf49999] and current `master`)

Oh, and BTW if you're using a custom build then maybe you can already provide a crash log? You'd need to be running a build with debug symbols though.

**Comment by mattsputnikdigital** [comment] 2023-03-30 20:30
Im on OSX 12.6.3 and Godot 4.0.1 and saving any scene crashes the editor, only once the scene has been saved once, the first time works fine.

**Comment by coppolaemilio** [comment] 2023-03-30 20:42
I'm on Ventura 13.2.1 and Godot 4.0.1. Can't reproduce.

**Comment by YuriSizov** [comment] 2023-03-30 20:58
> Im on OSX 12.6.3 and Godot 4.0.1 and saving any scene crashes the editor, only once the scene has been saved once, the first time works fine.

That's likely https://github.com/godotengine/godot/issues/75156, and so can be the OP.

**Comment by YuriSizov** [comment] 2023-03-30 21:06
> > > ### Steps to reproduce
> > > Open Godot 4.0.1.
> > > Create a new GDScript resource.
> > > Write an enum, then use the save hotkey.
> > > Crash.
> > > ### Minimal reproduction project
> > > N/A
> > 
> > 
> > Can't reproduce, more details needed. Does it happen in a blank new project? If no, minimal reproduction project would be needed too.
> 
> It does occur on a new project as well.
> 
> After some more testing, it only happens with a tool script while a scene is open (even if they're unrelated), if the "save scene" command is used. The "save script" command doesn't cause a crash.
> 
> Even with the 2D editor focused rather than the script editor, and using the `scene dropdown -> save scene` button instead of the "save scene" hotkey (Command + S), it still crashes.
> 
> Here's a reproduction project. In the test script, create a new enum while the test scene is open, then save the scene.
> 
> [temp.zip](https://github.com/godotengine/godot/files/11102003/temp.zip)

Okay, based on this description, this is definitely the same as https://github.com/godotengine/godot/issues/75156. So I'll close it as a duplicate.

**Closed by YuriSizov** 2023-03-30 21:06 UTC
Labels: bug, topic:gdscript, topic:editor, needs testing, crash, regression
