### ISSUE TITLE
List of open files in Script Editor doesn't disambiguate duplicate file names

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#27978] opened 2019-04-13 11:37 UTC
The following two files have different paths but the same file name:

<img width="189" alt="Screen Shot 2019-04-13 at 1 29 18 PM" src="https://user-images.githubusercontent.com/6002340/56079120-54ef1680-5df0-11e9-91ce-6b77b2053284.png">

You can see which is which by hovering over each one, but that really disrupts the user's workflow.

As a reference, Qt Creator will show as little of the path as possible in order to disambiguate:

<img width="277" alt="Screen Shot 2019-04-13 at 1 33 01 PM" src="https://user-images.githubusercontent.com/6002340/56079148-b44d2680-5df0-11e9-9a13-3db1d29824cb.png">

For further reference, I think this is the function where it happens:

https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/plugins/coreplugin/editormanager/documentmodel.cpp?id=75696f96390ca6f818aa7fd13c1104a6eed6089b#n142

**Comment by mitchcurtis** [comment] 2019-04-13 11:46
If this is fixed, it would be great if the disambiguated path was also shown in the window title:

<img width="294" alt="Screen Shot 2019-04-13 at 1 44 27 PM" src="https://user-images.githubusercontent.com/6002340/56079268-8a94ff00-5df2-11e9-8b4b-ebb9492a97e0.png">

**Comment by Calinou** [comment] 2019-04-13 12:05
This can be worked around by setting **Text Editor → Open Scripts → List Script Names As** to **Parent Directory and Name**. However, it will always display one directory, even if there's no ambiguity.

![image](https://user-images.githubusercontent.com/180032/56079465-11e37200-5df5-11e9-89d9-93cd7858f2ff.png)

**Comment by Paulb23** [comment] 2019-04-13 12:30
Duplicate of #20029

**Closed by Paulb23** 2019-04-13 12:30 UTC
Labels: enhancement, topic:editor, usability
