### ISSUE TITLE
GDScript inner class creation fails from the outside

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#66451] opened 2022-09-26 15:38 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

SteamOS 3.3.1

### Issue description

Two issues with GDscript in Godot 4:

1. inner class creation fails from the outside. The constructor finishes without errors though.
2. `Object.get_clas`s ignores class/class_name and retuns only the extended buil-in type

Example:

```gdscript
class_name Outer
extends RefCounted

var inner : Inner


func _init():
		print("Outer.new")
		self.inner = Inner.new()


class Inner extends RefCounted:
	
	var value : float
	
	func _init():
		print("Outer.Inner.new")
```

Test Cases:

```gdscript
extends Node

var outer : Outer
var inner : Outer.Inner

# Called when the node enters the scene tree for the first time.
func _ready():
	self.outer = Outer.new()

	# working as expected
	self.outer.inner.value = 1.0

	# bug #1: class name are only returns built-in types (RefCounted)
	print("Outer class: " + self.outer.get_class())
	print("Inner class: " + self.outer.inner.get_class())

	# bug #2: innner class instantiation from the outside fails silently
	self.inner = Outer.Inner.new()
	# hence the reference to `self.inner` is `null` and this yields to an error
	self.inner.value = 1.0
```

Output:

```
Outer.new
Outer.Inner.new
Outer class: RefCounted
Inner class: RefCounted
Outer.Inner.new
```

Error: `Invalid set index `value` (on base 'Nil") with value of type 'float'`

### Steps to reproduce

Launch the sample project and observe the **Output** as well as the **Debugger** error.

### Minimal reproduction project

[InnerClassBugs.zip](https://github.com/godotengine/godot/files/9647666/InnerClassBugs.zip)

**Comment by TheDuriel** [comment] 2022-09-27 20:39
2. is not a bug. Override the function if you wish to set a "name" for your class.

**Comment by michael-nischt** [comment] 2022-09-27 20:41
![image](https://user-images.githubusercontent.com/500820/192630874-16630f2a-b160-4c6e-8aac-c20db737b841.png)

Then it is a documentation bug is it's marked `const` and not `virtual`?

**Comment by TheDuriel** [comment] 2022-09-27 20:43
No?

Functions are marked as virtual when it is expected that the engine calls them automatically. This is not the case here. You are explicitly calling it, but want it to do something different than what it is made to do. There is absolutely nothing stopping you from overriding **any** function of any class.

**Comment by michael-nischt** [comment] 2022-09-27 20:52
Ah yea, actually says so in the docs that you have to yourself. Personally, I think it's stupid this way but fair enough.

**Comment by akien-mga** [comment] 2022-09-27 20:52
> Functions are marked as virtual when it is expected that the engine calls them automatically. This is not the case here. You are explicitly calling it, but want it to do something different than what it is made to do. There is absolutely nothing stopping you from overriding **any** function of any class.

That's not correct, overriding non virtual builtin functions is not supported. See #55024.

Anyway that first issue is a duplicate of #21789.

This ticket should focus on the second issue (in general, please keep one bug per GitHub issue).

**Comment by TheDuriel** [comment] 2022-09-27 21:21
@akien-mga 

![image](https://user-images.githubusercontent.com/44248915/192637860-342e7b69-6d78-4fd5-8d2c-6841c081d380.png)

This is what I meant.

**Comment by michael-nischt** [comment] 2022-09-27 21:27
I believe without `virtual`, it means if `C` code calls `get_class` on the object it won't call into the script?

**Comment by TheDuriel** [comment] 2022-09-27 23:33
This is correct. But at the same time, you would never expect it to. (Except in editor addon or tool script use cases, where the editor won't call your overrides.)

But for most purposes, this is just fine.

**Comment by bsil78** [comment] 2022-12-04 01:35
@michael-nischt : I cannot reproduce in Godot 4 beta 7, seems fixed, no ?

**Comment by rune-scape** [comment] 2022-12-04 11:48
i just tested that this is fixed as of https://github.com/godotengine/godot/pull/68374 @akien-mga

**Closed** 2022-12-05 09:57 UTC
Labels: bug, topic:gdscript
