### ISSUE TITLE
Nine Patch Stretch Property in TextureProgress with different Fill Modes

### ISSUE THREAD

**Issue by Foxomat** [godotengine/godot#33222] opened 2019-10-31 22:24 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Version 1903

**Issue description:**
-the Nine Patch Stretch Property of the TextureProgress Node doesn't work properly with all Fill Modes.
-selecting Left to Right, Right to Left, Top to Botom, Bottom to Top scales the Node as expected.
-selecting any other mode (Clockwise Modes and Bilinear Modes) prohibits the Node from scaling as the NinePatchRect but just leaves the Node in its original size.
-Issue persists when the size of the node is determined by parent container node.

**Steps to reproduce:**
-create a TextureProgress node
-add a texture
-set Nine Patch Stretch to On
-select an above mentioned Fill Mode (any Clockwise mode, any Bilinear mode)
(-fiddle with the size of the node)
(-compare to behavior when selecting a normal fill mode like left to right)

**Minimal reproduction project:**
-project is just 2 TextureProgress Nodes, the upper one stretching correctly, the lower one not.

[Bug-Demo.zip](https://github.com/godotengine/godot/files/3796014/Bug-Demo.zip)

**Comment by fossegutten** [comment] 2020-01-02 15:14
Was about to report a bug myself about the nine patch. The Nine Patch Stretch calculations should probably be updated for texture_progress, when the "value" gets updated.

**Comment by Haledire** [comment] 2020-07-18 16:13
Still a problem as of 3.2.2
Was going to suggest a solution for someone's healthbar and noticed trying to set up a Top to Bottom bar works fine, but a bottom to top fails to stretch the fill image.
![TexIssue](https://user-images.githubusercontent.com/164616/87856863-eac8f980-c8ef-11ea-8767-79c6a451644b.png)

[TexProgFail.zip](https://github.com/godotengine/godot/files/4941960/TexProgFail.zip)

**Comment by Reneator** [comment] 2020-11-13 13:58
Still a problem in 3.2.3:

When trying to use "Nine patch rect" with a texture that is 100x100 and trying to set its rect smaller than its original size (like 50x50):

clockwise:
![image](https://user-images.githubusercontent.com/24807557/99079758-ac52fb00-25c0-11eb-8214-63ec6c854753.png)
but left to right works properly:
![image](https://user-images.githubusercontent.com/24807557/99079823-becd3480-25c0-11eb-9975-e2faae8022a8.png)

**Comment by Kayomn** [comment] 2021-04-09 14:54
Still a problem in 3.3 rc8

**Comment by Calinou** [comment] 2021-04-09 15:04
Related to https://github.com/godotengine/godot/issues/45791, which will be fixed by https://github.com/godotengine/godot/pull/45815.

**Comment by akien-mga** [comment] 2021-06-21 07:07
Assuming fixed by #45815. Please comment if that's not the case.

**Closed by akien-mga** 2021-06-21 07:07 UTC
Labels: bug, confirmed, topic:gui

**Comment by lucassardois** [comment] 2022-01-05 14:52
I'm not sure this is working as intended. Here is the same texture with the same stretch margins for the Left to Right fill mode and the Clockwise fill mode:

Left to Right:
![image](https://user-images.githubusercontent.com/11078371/148237491-4fc04224-ea7f-4e51-bc1c-215109fe1e4e.png)

Clockwise:
![image](https://user-images.githubusercontent.com/11078371/148237560-09bbf0d2-9886-4c1c-9b4c-4f3b0c48e94a.png)

As you can see the Left to Right fill mode works as intended, but the clockwise fill is wrong. I'm on Godot 3.4.2.

**Comment by Calinou** [comment] 2022-01-05 15:18
@lucassardois Are you using GLES3 or GLES2 in your project? Nine-patch is only fully supported in GLES3 as it's impossible to replicate in GLES2 without causing performance drops on some devices (due to UV manipulation triggering a software fallback on many drivers).

**Comment by Calinou** [comment] 2022-01-05 16:50
@lucassardois Please open a new issue with a minimal reproduction project attached, as the root cause is likely different.
