### ISSUE TITLE
Recent opened popups doesn't update focus

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50533] opened 2021-07-16 23:15 UTC
### Godot version

v4.0.stern-flowers.312.custom_build [0e265b047]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When you for example click "Add new Child Node" the new popup window will not get focused!
Same happens for AnimationPlayer's add new animation

Note: Sometimes work, and other times not!

### Steps to reproduce

* Open godot
* Open Project
* Click "Add child Node"
* The window will open, but if you type you can see that it doesnt get focus!
* Add a new animation player node
* click Animation
* click new
* same thing will happen

### Minimal reproduction project

N/a

**Comment by Calinou** [comment] 2021-07-16 23:48
Duplicate of https://github.com/godotengine/godot/issues/49978.

**Closed by Calinou** 2021-07-16 23:48 UTC
Labels: bug, topic:editor

**Comment by nonunknown** [comment] 2021-07-16 23:55
sorry for duplicating it, I searched for focus which was the only word I could think att, but awesome to confirm it :D
