### ISSUE TITLE
GradientTexture1D can't be set as shader parameter

### ISSUE THREAD

**Issue by ElfWitch** [godotengine/godot#81780] opened 2023-09-17 03:02 UTC
### Godot version

4.2.dev4

### System information

Windows 10 Vulkan

### Issue description

Attempting to set a GradientTexture1D as a parameter of Sampler2D won't work since 4.2.dev4. This worked in 4.2.dev3.
![image](https://github.com/godotengine/godot/assets/109904725/7856a024-2ad1-407a-9ad9-969ab82ca6d1)
Creating a GradientTexture1D file and setting it as a shader parameter does work, but creating a local one doesn't.

### Steps to reproduce

see above

### Minimal reproduction project

[gradients.zip](https://github.com/godotengine/godot/files/12641968/gradients.zip)

**Comment by bitsawer** [comment] 2023-09-17 03:13
Thanks for the report. Duplicate of https://github.com/godotengine/godot/issues/81712 and fixed in the master.

**Closed by bitsawer** 2023-09-17 03:13 UTC
