### ISSUE TITLE
Unexpected blinks of Tooltips in Inspector property

### ISSUE THREAD

**Issue by MrBBBaiXue** [godotengine/godot#47610] opened 2021-04-04 03:39 UTC
**Godot version:**
3.3 rc7

**OS/device including version:**
Windows 10 Pro x64
with GLES3

**Issue description:**
There is a video that may best describe the issue:

https://user-images.githubusercontent.com/17956756/113497807-de4a0700-9539-11eb-829e-26648effd7eb.mp4

It seems like Godot 4.0 doesn't have this issue.

**Steps to reproduce:**
Hover the pointer on any property in Inspector.
I have reproduce it on three different machines.

**Comment by floppyhammer** [comment] 2021-04-04 08:56
Couldn't reproduce this with either GLES2 or GLES3.

**Comment by MrBBBaiXue** [comment] 2021-04-04 10:33
> Couldn't reproduce this with either GLES2 or GLES3.

Maybe because I'm using the laptop with two video cards?

**Comment by Zireael07** [comment] 2021-04-04 10:44
@MrBBBaiXue: Possibly, and you haven't mentioned what cards are they (on all three machines that repro the problem)?

**Comment by floppyhammer** [comment] 2021-04-04 10:48
@MrBBBaiXue Same case here.

**Comment by MrBBBaiXue** [comment] 2021-04-04 11:10
> @MrBBBaiXue: Possibly, and you haven't mentioned what cards are they (on all three machines that repro the problem)?
> 
> EDIT: Also, do you have a program called Fences (by Stardock) installed by any chance?

Ah, sorry I forget it.
Machine 1: Intel UHD Graphics 630, Geforce GTX 1050Ti (Notebook)
Machine 2: Intel UHD Graphics 630, Geforce MX350
Machine 3: Readon Graphics, Geforce GTX 1660Ti

All of them HAVE Fences installed.
Maybe I should try to uninstall it ?

**Comment by Calinou** [comment] 2021-04-04 12:35
> All of them HAVE Fences installed.
> Maybe I should try to uninstall it ?

Indeed :slightly_smiling_face: 

Duplicate of https://github.com/godotengine/godot/issues/32990.

**Closed by Calinou** 2021-04-04 12:35 UTC
Labels: bug, topic:gui
