### ISSUE TITLE
Holding "Ctrl+S" will display multiple save dialog

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#3946] opened 2016-03-06 05:09 UTC
**Operating system or device:**
OS: Ubuntu 15.10 64-bit

**Issue description** (what happened, and what was expected):
- _What happened:_ I opened a very simple project with just one scene added on it. When I held `Ctrl+S` to save the scene, multiple save scene dialog kept popping. Even when I released `Ctrl+S`, the multiple appearing of save dialog will not stop (it stopped at a certain time after the release). Like this:

![gifrecord_2016-03-06_122852](https://cloud.githubusercontent.com/assets/3685613/13552312/59389b06-e398-11e5-8ac7-b7a5a33eb387.gif)
- _What was expected:_ I was expecting that these multiple save dialog will not be appearing. When I tried to save a scene with no changes (_the one with no `(*)` on the editor tab_), I was expecting also that a save scene dialog will not appear. I was expecting also that when I released `Ctrl+S`, the appearing of multiple save dialog will stop.

**Steps to reproduce:**
1. Create a new project
2. Add a new scene with just a `Panel` node
3. Save the scene on the file system
4. Hold `Ctrl+S` for about 10 seconds (_expected here to show the multiple save dialog_)
5. Release `Ctrl+S` (_expected that multiple save dialog keeps appearing and it will stop at a certain time after the release_) 
6. Move the `panel` to make changes on the scene (_expected there will be `(*)` on the tab_)
7. Press `Ctrl+S` to save the scene
8. Press `Ctr+S` again (_expected that save scene dialog will not appear since there are no changes on the scene_)

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment] 2016-03-06 12:41
I think this would fix it:
``` diff
@@ -2080,7 +2080,9 @@ void EditorNode::_menu_option_confirm(int p_option,bool p_confirmed) {
 			if (scene && scene->get_filename()!="") {
 
 				//_save_scene(scene->get_filename());
-				_save_scene_with_preview(scene->get_filename());
+				if (unsaved_cache) {
+					_save_scene_with_preview(scene->get_filename());
+				}
 				return;
 			};
 			// fallthrough to save_as
```
But isn't the current behaviour normal? Most software I use will save the file anyway, even if there are no changes.

**Comment by akien-mga** [comment] 2016-03-06 12:56
I think the fix would be more to prevent resaving based on the same held input. So when holding Ctrl+S, it should be processed only once.

**Comment by neikeq** [comment] 2016-03-06 13:30
I think that's handled by _MenuButton_ on _\_unhandled_input_. Other application also handle echo keys for accelerators. The problem seems to be that Godot queues these echo events, so _Save_ will be called for each of them, even if these events were fired while the scene was still being saved.

**Comment by OvermindDL1** [comment] 2016-03-06 20:04
Shouldn't it run the Save command on KeyUp like most apps (with a
corresponding KeyDown before)?

On Sun, Mar 6, 2016 at 6:30 AM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment] 2016-03-22 01:06
Actually, most apps fire Save with echo events too, but they ignore these events while doing the heavy work.
What's the right way to stop listening for input events during intensive processing? I tried calling `file_menu->set_process_unhandled_input(false);` at the beginning of _\_save_scene_with_preview_ method and `file_menu->set_process_unhandled_input(true);` at the end, but that didn't seem to work...

**Comment by bojidar-bg** [comment] 2016-04-06 11:32
@neikeq Well, we can just use `InputEventKey.echo`/`InputEvent.is_echo()`, no?

**Comment by vnen** [comment] 2016-06-17 03:23
Is this still valid? I can't reproduce on Windows.

**Comment by mohaalak** [comment] 2016-06-17 07:34
I can't reproduce it in mac , I think it's safe to close this issue. ping @akien-mga to close the issue

**Closed** 2016-06-17 07:36 UTC
Labels: bug, junior job, topic:editor, usability
