### ISSUE TITLE
[WebGL2] 2D lights not working properly on Mozilla Firefox

### ISSUE THREAD

**Issue by vgabler** [godotengine/godot#17930] opened 2018-04-02 18:31 UTC
**Godot version:**
Godot 3.0 (stable, win64)

**OS/device including version:**
Windows 10 home single language 64 bits
Intel Core i7-6700, 3.4ghz
16GB ram
Latest drivers on NVIDIA's Geforce GTX 745 4gb

**Issue description:**
2D lights are not working correctly on Mozilla Firefox. If you use only 1 light in the whole scene, it may function, but 2 is enough to break everything. This can be seen even on the 2d light sample from Godot's main website.

Google Chrome version 65.0.3325.181 64 bits (expected):
<img src="http://i66.tinypic.com/2di1y50.png" border="0">
_Lights are working perfectly._

Mozilla Firefox  version 59.0.1 (64-bit) (messed up):
<img src="http://i65.tinypic.com/nzgint.png" border="0">
_Lights are not illuminating other objects correctly, some colors are being shown and shadows are completely out of place. Its like only the orange light is barely working._

**Steps to reproduce:**
Using the export templates from <a href="https://godotengine.org/download/windows">Godot's official website</a>, export the project to HTML5 and play it on Mozilla Firefox

**Minimal reproduction project:**
<a href="https://godotengine.org/asset-library/asset/116">Godot's lights and shadows demo.</a>

**Comment by eon-s** [comment] 2018-04-02 19:20
Cannot reproduce using Firefox version 59.0.2 in Ubuntu 17.10, Godot 3.0.2.

**Comment by clayjohn** [comment] 2019-12-14 04:30
Closing as not able to reproduce.

**Closed by clayjohn** 2019-12-14 04:30 UTC
Labels: bug, platform:html5, topic:rendering
