### ISSUE TITLE
Sprites turn black after exiting the game and going back in on Android with Adreno 200 GPU

### ISSUE THREAD

**Issue by blackwolf12333** [godotengine/godot#1322] opened 2015-01-31 12:54 UTC
Every time I press the home button to exit the game, and when I later return to it, the sprites are all black.

These images show [before](http://i.imgur.com/VYUohgG.jpg) and [after](http://i.imgur.com/LxyZ7pq.jpg).

**Comment by okamstudio** [comment] 2015-01-31 14:05
Android 2.3 by chance?

**Comment by blackwolf12333** [comment] 2015-01-31 18:07
No, it's on android 4.0.3

**Comment by reduz** [comment] 2015-01-31 19:22
Strange, which phone is it?

**Comment by blackwolf12333** [comment] 2015-01-31 19:46
LG optimus l5.

**Comment by mookiexl** [comment] 2015-02-15 00:22
Exact same issue on my Qpad. It has same Adreno 200 GPU as Optimus l5, maybe it's related?

**Comment by okamstudio** [comment] 2015-02-15 03:26
ah i've seen this before.. these phones don't seem to like keeping the
glcontext when app is sent to background, so when restored everything is
gone. Godot used to support this, it would just load everything back from
disk (but takes a while).

It seems this broke at some point for some reason though, and I don't have
any of those old phones to test anymore.. It's a problem of old and really
low end phones though..


On Sat, Feb 14, 2015 at 9:23 PM, mookiexl <notifications@github.com> wrote:

> Exact same issue on my Qpad. It has same Adreno 200 GPU as Optimus l5,
> maybe it's related?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1322#issuecomment-74398189>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment] 2016-04-01 09:32
IIRC there were some renderer improvements for low-end GPUs like what one can find on the OUYA, maybe it had an impact on this issue with Adreno 200? Could you check if the issue is still valid in recent Godot versions?

**Comment by akien-mga** [comment] 2016-06-18 21:03
Ping. Does anybody have a device with the Adreno 200 GPU and could try to reproduce this issue? If not we'll have to close it as old, since we can't really fix it blindly.

**Comment by mookiexl** [comment] 2016-06-18 21:43
Cannot build from source at the moment, but it was still there in 2.0.3 stable.

**Comment by akien-mga** [comment] 2017-06-28 14:08
At this stage, I assume that it's a GPU and driver-specific issue on older phones, and it's quite unlikely that it will be fixed in Godot itself (as Godot 3.0 will even require GLES 3.0 support that such GPUs don't provide), so closing as "can't fix".

**Closed by akien-mga** 2017-06-28 14:08 UTC
Labels: bug, confirmed, platform:android, topic:rendering
