### ISSUE TITLE
Mipmap artifacts over large distance or narrow angles

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56035] opened 2021-12-17 20:48 UTC
### Godot version

4.0 58712e96aea12bda2d5111d96961f529d15a693c

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

A texture that was showing fine over large distances is now having artifacts at certain "mipmap levels":

In Godot 4:
![image](https://user-images.githubusercontent.com/1311555/146605331-ae5c0372-ea0e-4fea-9523-85fde1fc2e05.png)

In Godot 3.4:
![image](https://user-images.githubusercontent.com/1311555/146605480-0b4159c9-0677-43e2-99a3-4befe017d4a6.png)

The problem is still visible with other filtering modes, to some degree.

### Steps to reproduce

1) Add a grass texture to the project
2) Create a `StandardMaterial3D` with the texture as albedo and UV scale to `100,100,100`
3) Create a `MeshInstance3D` with a `BoxMesh` on it of size `50,50,50`
4) Put the material on the mesh instance: observe artifacts at some angles, or when viewed from far away

### Minimal reproduction project

[Mipmaps.zip](https://github.com/godotengine/godot/files/7737672/Mipmaps.zip)

**Comment by Calinou** [comment] 2021-12-17 21:01
Duplicate of https://github.com/godotengine/godot/issues/49981
.

The issue goes away if you switch the texture to Lossless compression in the Import dock, click **Reimport** then reload the scene:

![image](https://user-images.githubusercontent.com/180032/146607506-c7e57e34-c50c-424c-a9de-c7bfde2ba7f9.png)

**Closed by Calinou** 2021-12-17 21:01 UTC

**Comment by Zylann** [comment] 2021-12-17 21:10
So we just can't anymore have a compressed texture with mipmaps like we could in Godot 3?

**Comment by Calinou** [comment] 2021-12-17 21:25
> So we just can't anymore have a VRAM compressed texture with mipmaps like we could in Godot 3? Even though it used the same algorithm for the same test case?

It's a bug, and my suggestion is just a workaround. In the meantime, to save memory, you can use lower-resolution textures using the **Size Limit** option in the Import dock (so you don't have to modify your source images). Once this issue is fixed, you can set **Size Limit** back to 0.

> Also, that's a power-of-two texture. In #49981 (comment) the explanation seems to be about non-power-of-two.

The underlying cause is likely the same. I modified that issue's title to mention that this is not exclusive to NPOT textures.

**Comment by Zylann** [comment] 2021-12-17 21:27
Oh, sorry for a moment I thought the linked issue was closed somehow and I freaked out^^"
