### ISSUE TITLE
SDFGI Rendering Errors in Editor with Instanced Light Scenes

### ISSUE THREAD

**Issue by deadpixelsociety** [godotengine/godot#67380] opened 2022-10-14 06:08 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10, Vulkan, Geforce 2060

### Issue description

When adding a child scene that contains an omnilight to a scene with a WorldEnvironment with SDFGI enabled error spam (that does not stop) can happen in the editor.

![image](https://user-images.githubusercontent.com/6668682/195774147-b7784b78-032c-4759-82ea-58edf16e1a94.png)

Sometimes it doesn't trigger the error, sometimes it does, but it is a consistent issue. You may have to play with it, add a light scene, reload the world scene, etc.

### Steps to reproduce

1. Create a world made from child scene objects for walls, floors, ceiling, and a light source.
2. Add light source scene to world.
3. Add WorldEnvironment and a new environment.
4. Enable SDFGI.

### Minimal reproduction project

[GI Error Reproduction.zip](https://github.com/godotengine/godot/files/9782917/GI.Error.Reproduction.zip)

**Comment by deadpixelsociety** [comment] 2022-10-14 14:17
I loaded this test project up in Godot 4 Beta 3 to confirm it's still an issue in the new release, and it still happens though the output is slightly different:

![image](https://user-images.githubusercontent.com/6668682/195869280-e0d8fc5a-7763-432d-9f99-212efe6d385c.png)

**Comment by Calinou** [comment] 2022-10-14 16:29
Duplicate of https://github.com/godotengine/godot/issues/57840.

**Closed by Calinou** 2022-10-14 16:29 UTC
Labels: bug, topic:rendering, topic:3d
