### ISSUE TITLE
Exported variables reset to default on non-tool scripts when saving a scene

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#47515] opened 2021-03-31 06:41 UTC
**Godot version:**
db31445b905d94f055ffd210aee6d93cc39b8c96

**OS/device including version:**
Windows 10

**Issue description:**
Any variable you mark as @export with a script will get its value reset to its default any time you save a scene. If the script is marked as a tool script, the variable will save as intended though.

**Steps to reproduce:**
1. Open the project and main scene
2. Set the 'test_property' property in the root node to any value other that 0
3. Save the scene

**Minimal reproduction project:**
[godot_4_export_variables_test.zip](https://github.com/godotengine/godot/files/6234310/godot_4_export_variables_test.zip)

**Comment by Calinou** [comment] 2021-03-31 09:15
Duplicate of https://github.com/godotengine/godot/issues/41690.

**Closed by Calinou** 2021-03-31 09:15 UTC
Labels: bug, regression, topic:gdscript
