### ISSUE TITLE
some form of conditional operator for gd script

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3517] opened 2016-01-30 09:36 UTC
Would be nice to have some form shorthand for if condition a otherwise b.

in Python you can do 
value = b if a > 10 else c
and previously 
value = [c, b][a > 10]

In C++ or Java
value  = ( a > 10 ? b : c )

in gd script maybe something like this could work
if expression1 a else b
value = (if expression1 a else b)
if expression1 value = a else value = b

possibly
if expression1: a else: b

if something follows after if statement on the same line then is the result of true and an else must be following to be valid which will have the result for false

**Comment by neikeq** [comment] 2016-01-30 10:36
Duplicate of #1961

**Comment by trollworkout** [comment] 2016-01-30 10:41
you can close this i guess if it a duplicate

**Closed** 2016-01-30 11:08 UTC
Labels: archived, enhancement, topic:gdscript
