### ISSUE TITLE
Object Pool causes is_instance_valid method to be called on the wrong object

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#22395] opened 2018-09-24 09:15 UTC
**Godot version:**
3.1 custom

**OS/device including version:**
ArchLinux 4.18.8-arch1-1-ARCH

**Issue description:**
Objects A and B both extend VBoxContainer. A has a method called "remove", B doesn't.
A has a yield on a tween complete, when the tween is completed A is queued_free
B is instanced on a signal basis (when event X happens, instance B)

What happened is that, when the event that instances B is called at the same time as the one that actually frees A (a very hard to reproduce conditions), the method remove is called on B instead, causing a crash.

We guessed that the problem lies in the object pool, since A is both checked for null and is_instance_valid. We solved the problem by manually setting the reference to A to null after the tween starts, but this issue might be causing other problems somewhere else.

**Steps to reproduce:**
Sadly, could not reproduce.

**Comment by QbieShay** [comment] 2018-12-13 11:06
I think this is an ABA problem (https://en.wikipedia.org/wiki/ABA_problem)
The fix to this is to manually invalid your reference, since the pools are not counting generations.

**Comment by QbieShay** [comment] 2019-02-05 14:12
@hpvb

**Comment by isaacremnant** [comment] 2019-03-31 09:09
This is SO frustrating. I've ran into this problem at least 3 times now. The function is appropriately named, it *does* tell you if the instance is *valid* or not but the *desired* behavior here really is: *tell me if the instance I'm about to call is the one I saved before". [This part of the documentation is just plain wrong:](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#memory-management)

> Alternatively, when not using references, the is_instance_valid(instance) can be used to check if an object has been freed.

[I'm attaching a pretty minimal project to showcase this](https://github.com/godotengine/godot/files/3026365/test.zip). Basically I'm growing a line and freeing previous points while spamming the object pool with garbage. The saved nodes will often get messed up so the line sometimes closes. The behavior itself is pretty weird (may be a bug with the object pool?). Why is a reference suddenly reassigned to another of the points?

**Comment by sdfgeoff** [comment] 2019-04-18 09:28
Hit is as per link above. Not a minimal reproduction project, but I'll just bump this issue again.

**Comment by akien-mga** [comment] 2019-04-19 19:45
See also #28191 for another MRP: [is_instance_valid.zip](https://github.com/godotengine/godot/files/3097474/is_instance_valid.zip)

**Comment by akien-mga** [comment] 2020-01-08 12:19
I'll close as duplicate of the newer #32383 since it's getting more attention. Still no fix though :/

**Closed by akien-mga** 2020-01-08 12:19 UTC
Labels: bug, confirmed, high priority, topic:core
