### ISSUE TITLE
Code editor trackpad scroll speed too fast and pan is too sensitive

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot#6786] opened 2016-10-11 07:06 UTC
**Operating system or device - Godot version:**
Macbook Pro Mac OS 10.12
All Godot versions

**Issue description** (what happened, and what was expected):
1. Code editor trackpad scroll speed is way too fast
2. The L/R pan is too sensitive, when scrolling up and down it also scrolls right - there should be a threshold set.

**Steps to reproduce:**
Open some code and scroll multiple lines.

**Comment by Hinsbart** [comment] 2016-10-11 08:28
Closing as duplicate of #492.

**Closed by Hinsbart** 2016-10-11 08:28 UTC
