### ISSUE TITLE
4.2 dev6 node AnimationPlayer Play Not effective

### ISSUE THREAD

**Issue by wsqrin** [godotengine/godot#82905] opened 2023-10-06 10:25 UTC
### Godot version

4.2 dev 6 mono

### System information

win11 22H2

### Issue description

4.2 dev6 node AnimationPlayer Play Not effective but 4.2 dev5 is normal

### Steps to reproduce

    public override void _PhysicsProcess(double delta)
    {
        ChangeAnimation();
    }

    private void ChangeAnimation()
    {
        var anim = Velocity.X switch
        {
            < 0 => "left",
            > 0 => "right",
            _ => "down"
        };

        if (Velocity.Y < 0) anim = "up";

        animation_play?.Play("walk-" + anim);
    }

### Minimal reproduction project

    public override void _Ready()
    {
        animation_play = GetNode<AnimationPlayer>("AnimationPlayer");
    }

**Comment by AThousandShips** [comment] 2023-10-06 10:42
Can you please provide an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available. 

No information about the animations were provided so very difficult to test this, so please provide a project, and make sure to convert the example code to GDScript, so more people can test it

**Comment by akien-mga** [comment] 2023-10-06 10:46
Likely duplicate of #82828?

**Comment by AThousandShips** [comment] 2023-10-06 10:56
If so then it would have been fixed by #82898

**Comment by LeeWannacott** [comment] 2023-10-06 14:41
I'm on 4.2 dev 6 mono as well.

There is definitely some funky stuff going on, but it's only for some animations. Like my player character has gone invisible (none of the animations show) and animal running animations are effected which sounds like https://github.com/godotengine/godot/pull/82898 (which probably isn't in the build I'm using yet): 

It's late, I'll investigate/retry tomorrow.

**Comment by LeeWannacott** [comment] 2023-10-07 01:21
I compiled from source; looks like https://github.com/godotengine/godot/pull/82898 fixed the animal running animations. Although my player character is still invisible, so it's probably a different issue; I'll look into reproducing it in a minimal project.

**Comment by LeeWannacott** [comment] 2023-10-07 12:58
Update: looks like its this issue: https://github.com/godotengine/godot/issues/82949

**Closed** 2023-10-09 13:43 UTC
Labels: bug, needs testing, topic:animation
