### ISSUE TITLE
Preload fails in exported project if convert_text_resources_to_binary is true

### ISSUE THREAD

**Issue by k0bolde** [godotengine/godot#66561] opened 2022-09-28 18:06 UTC
### Godot version

4.0.beta1.official

### System information

ubuntu 20

### Issue description

Preloading a tscn with the the project setting convert_text_resources_to_binary true fails to load when exported.

Might be related to #66014  since that's what gave me the work around of setting convert_text_resources_to_binary to false.

### Steps to reproduce

Check that the project setting convert_text_resources_to_binary is true (it's the current default).
Preload any tscn in a script, then export the project, then run it. The preload will fail with a file does not exist error.

The attached project should load and display the text "I got loaded" and it does when run through the editor. 

When exported to linux the project fails to load with the error `SCRIPT ERROR: Parse Error: Preload file "res://src/loadme.tscn" does not exist.`

### Minimal reproduction project

[preloaderror.zip](https://github.com/godotengine/godot/files/9667801/preloaderror.zip)

**Comment by akien-mga** [comment] 2022-09-28 18:33
Duplicate of https://github.com/godotengine/godot/issues/56343

**Closed by akien-mga** 2022-09-28 18:33 UTC
