### ISSUE TITLE
Android live edit don't update newly added signals

### ISSUE THREAD

**Issue by fzdravko** [godotengine/godot#28821] opened 2019-05-11 02:11 UTC
**Godot version:**
Godot 3.1.1. stable official

**Issue description:**
Android live edit don't update newly added signals.

**Steps to reproduce:**
If I add new button and assign new signal on it (pressed()) and add code for pressed action, button on android device don't react on press (like the signal is not connected). If I deploy again to device, everything works.

Another question - Is it possible to restart game on android without deploying.

Thank you.

**Comment by zacharytyhacz** [comment] 2019-05-12 02:40
I do not believe the code can automatically update through live edit, just node-editing, but I may be wrong. 

However, I can +1 you that this does not work ( adding signal and adding code with live edit ) 

Also, are you using GLES3 or GLES2?

**Comment by fzdravko** [comment] 2019-05-12 08:42
I'm using GLES3 (tried with GLES2 also).

**Comment by KoBeWi** [comment] 2020-08-12 23:28
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 22:35
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:35 UTC
Labels: bug, platform:android, topic:core
