### ISSUE TITLE
Godot Steam Bug

### ISSUE THREAD

**Issue by svtsmka** [godotengine/godot#56254] opened 2021-12-26 15:51 UTC
### Godot version

3.4.2

### System information

Windows 10 GLES3

### Issue description

 Godot doesn't track time Steam.
You can use Godot C# in Steam and track your time??

### Steps to reproduce

After I run Godot in Steam, it shows that I am using Godot, and when I open a project in Steam, it says that I am online

### Minimal reproduction project

Run godot, "Steam okey you play Godot"
I open project godot, "Steam say me okey you online"

**Comment by Calinou** [comment] 2021-12-26 15:52
Duplicate of https://github.com/godotengine/godot/issues/18233.

>  You can use Godot C# in Steam and track your time??

There are currently no plans to offer Mono-enabled Godot on Steam. It may happen in the far future [once Mono is distributed as an add-on rather than as a separate executable](https://github.com/godotengine/godot-proposals/issues/2333).

**Closed by Calinou** 2021-12-26 15:52 UTC
