### ISSUE TITLE
[4.2.1 rc 1] Models are not displayed correctly

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#85946] opened 2023-12-09 00:06 UTC
### Tested versions

in godot 4.1.3 everything is fine

### System information

Windows 10, Radeon RX 560 Series, Vulkan(Forward+)

### Issue description

Model appears with black pixels but disappear when screen size is changed:
https://youtu.be/hb5O4nz3Leo?si=Gwo3wYhQ6bU1j6Jj
this only happens in mode Forward+

### Steps to reproduce

Run this demo on an amd graphics card - [[godot-4-3D-Characters](https://github.com/gdquest-demos/godot-4-3D-Characters)](https://github.com/gdquest-demos/godot-4-3D-Characters)

### Minimal reproduction project (MRP)

Link

**Comment by clayjohn** [comment] 2023-12-09 00:43
Duplicate of https://github.com/godotengine/godot/issues/85549

You don't need to open a new version of the issue for new versions of the engine. It's best to just use the original bug report.

**Closed by clayjohn** 2023-12-09 00:43 UTC
