### ISSUE TITLE
Moving in scene by using middle mouse-wheel stops working

### ISSUE THREAD

**Issue by Glitchy-Tozier** [godotengine/godot#47007] opened 2021-03-14 19:41 UTC
**Godot version:** v3.2.3.stable.flathub

**OS/device including version:**
- Linux Mint 20.1 Cinnamon
- Intel© Core™ i7-4710MQ CPU @ 2.50GHz × 4
- GLES3 (but I tried with GLES2 and the problem still persisted.

**Issue description:**

By clicking on the mousewheel and moving the mouse around, you usually can move around in your 2D Workspace. However, if I zoom out even a little bit, this function seizes to exist. Movement gets restricted more and more and spasms for a few seconds, before the 2D port becomes entirely unresponsive to dragging.

**Steps to reproduce:**
Not sure what initially triggered this. It may just be me being a beginner and accidentally clicking some weird option. I can't remember doing that though.
What I can do now to reproduce the bug:
1. Go to 2D (at the top)
2. Scroll out a bit
3. Try to move everything. It might move a few pixels, but then it stays unresponsive.

I could upload a screen capture if that helps.

**Minimal reproduction project:** The "Pong with GDScript" example game that can be found in the Godot Asset "Store".

**Comment by Calinou** [comment] 2021-03-14 20:41
This is done by design to prevent the camera from moving too far away from the game scene. You can disable this behavior by unchecking **Constrain Editor View** in the Editor Settings.

**Closed by Calinou** 2021-03-14 20:41 UTC

**Comment by Glitchy-Tozier** [comment] 2021-03-14 20:51
I see, thank you!

**Comment by Macksaur** [comment] 2023-06-06 20:48
I fixed this in https://github.com/godotengine/godot/pull/73223 but constraining might be being entirely removed.
