### ISSUE TITLE
range with more then 1 parameter causes flicker and app crash on Android

### ISSUE THREAD

**Issue by slasktotten** [godotengine/godot#42081] opened 2020-09-15 09:46 UTC
Godot version:
v3.2.2

OS/device including version:
Multiple Android devices, both actual hardware and emulator

Issue description:
Using range with more then 1 parameter causes app to crash / screen flicker on Android.
The only useful bit from Logcat is the following:
```
**SCRIPT ERROR**: Parse Error: Too many arguments for 'hash()' call. Expected at most 1.
At: res://hello_world.gdc:7:GDScript::load_byte_code() - Parse Error: Too many arguments for 'hash()' call. Expected at most 1.

```
Steps to reproduce:
`for i in range(0, 25, 1)`

**Comment by akien-mga** [comment] 2020-09-15 09:54
Can you provide a reproduction project?

I tried and I can't reproduce it. No problem with this script:
```
extends Label

func _ready():
	for i in range(0, 25, 1):
		text += " " + str(i)
```

The Label properly lists all numbers from 0 to 24.

**Comment by akien-mga** [comment] 2020-09-15 09:55
Are you maybe using export templates which do not match your Godot version? That's the usual suspect when getting bytecode errors, as the bytecode of different Godot versions is not compatible.

**Comment by slasktotten** [comment] 2020-09-15 09:59
I'll check export templates
I Just added a Node and then a script with the following:
`func _ready():
	for i in range(0, 25, 1):
		print_debug(i)`

**Comment by slasktotten** [comment] 2020-09-15 10:14
Right. Was totally me being an idiot. Had forgotten to point my Path to Godot I was using. Many apologies. Will keep the export template bytecode error in mind in the futre!

**Comment by akien-mga** [comment] 2020-09-15 10:16
Great, closing then.

**Closed by akien-mga** 2020-09-15 10:16 UTC
Labels: bug, platform:android, topic:gdscript
