### ISSUE TITLE
Clip content doesn't clip the children properly

### ISSUE THREAD

**Issue by ZeEndy** [godotengine/godot#69383] opened 2022-11-30 10:10 UTC
### Godot version

4.0 beta 6

### System information

Windows 10, RTX3070 TI, Vulkan

### Issue description

Found a bug with the ``clip content`` option on containers in which if the value is lower than or equals ``0.28``
I've seen that if the x value is ``0.28`` then it shows the whole thing but if its the y value it has weird bug where it partially shows it

### Steps to reproduce

Step 1: Create Control Node
Step 2: Add a child to it weather it be a button or texture
Step 3: Enable clip content
Step 4: Change the any of the sizes to be less that 0.281

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2022-11-30 20:14
Could you please upload an MRP to make this easier for contributors to troubleshoot?

An MRP is a project that is as small as can be while still reproducing the bug you are reporting. We include the MRP in the bug reporting template as including one greatly increases the chance that a contributor will be able to reproduce the bug you reported and be able to fix it.

**Comment by ZeEndy** [comment] 2022-11-30 20:51
[MRP.zip](https://github.com/godotengine/godot/files/10127202/MRP.zip)
I made 2 sliders for testing
bottom one changes the x size of the control
side one controls the zoom of the camera because after a little testing it seems it also is affected by it

**Comment by Rindbee** [comment] 2022-12-01 00:13
Duplicate of #56579.

**Comment by ZeEndy** [comment] 2022-12-01 08:56
Got it closing

**Closed** 2022-12-01 08:56 UTC
Labels: bug, topic:gui
