### ISSUE TITLE
Inherited CollisionShape2D ignoring the Shape2D

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#11574] opened 2017-09-25 12:52 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Godot 2.1.3 

**Issue description:**
When inheriting a scene with a CollisionShape2D node, the inherited scene doesn't overwrite the parent's shape. It should since it is an inherited scene and that's what inheritance is aimed for :P

**Steps to reproduce:**
1. Create a test scene with a StaticBody2D as ground for testing purposes
1. Create any physics character (RigidBody2D or Kinematicbody2D)
1. Add a CollisionShape2D to it, do not create a Shape2D yet
1. Create an inherited scene using the above scene as parent
1. Now Add a Shape2D to this scene
1. Instantiate it in the test scene with the ground
1. Apply a movement so it can collide with the ground

Watch it passing by the ground.

Now repeat the same process starting in the 3rd step, but now add a Shape2D to the parent scene

Test it again and now it collides.

I couldn't fix this even when I try to manually add the Shape2D using GDScript.

**Comment by bojidar-bg** [comment] 2017-09-25 14:31
Duplicate of #2314 (same problem causing it), which was fixed in 3.0.

**Closed by bojidar-bg** 2017-09-25 14:31 UTC
Labels: bug, topic:physics
