### ISSUE TITLE
Texture is displayed on wrong side of mesh

### ISSUE THREAD

**Issue by penguinroad** [godotengine/godot#9599] opened 2017-07-11 08:14 UTC
**Operating system or device - Godot version:**
Ubuntu Mate 16.04,
I3 3.6ghz, 4gb ram, nvidia gtx 750TI

Godot v3.0.alpha.custom_build

git clone on July 10th 2017

**Issue description:**

texture is displayed on wrong side of mesh

**Steps to reproduce:**
1. create a plane using blender, unwrap UV, assign material and texture
2. export object to .dae, import into godot project
3. load object into main scene
4. texture should be displayed on top side of plane, instead it's shown on bottom side of plane

**Link to minimal example project:**

**Comment by reduz** [comment] 2017-09-29 14:18
works fine for me, may be your plane was scaled or had normals flipped

**Comment by reduz** [comment] 2017-11-06 14:55
closing as cant reproduce

**Closed by reduz** 2017-11-06 14:55 UTC
Labels: bug, topic:plugin
