### ISSUE TITLE
AnimatedSprite2D editor carrying changes over between different items of the UI

### ISSUE THREAD

**Issue by kenneth-leblanc** [godotengine/godot#80575] opened 2023-08-13 02:05 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1694) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

When editing the FPS or Frame Duration on a SpriteFrames resource, if you select another animation (FPS) or another frame (Frame Duration), right after changing the value, before changing focus, both the originally selected item and the newly selected item will receive the change.
Here is an animation of the bug as it applies to FPS.

![AnimationBug](https://github.com/godotengine/godot/assets/4635469/38e68905-623c-4f67-86b1-313132f7c971)

I would expect it to apply the change to the originally selected item and not apply the change to the newly selected item.

### Steps to reproduce

Make an AnimatedSpite2D node
Add a SpriteFrames resource
Add at least 2 animations
Change the FPS of the first animation, then before hitting enter, select a different animation. The new FPS will be applied to both the old animation and the newly selected animation.
You can do the same for Frame Duration by adding two frames and editing frame duration and then selecting another frame.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-08-13 07:23
* Duplicate of #79445.
* Will be fixed by #79692.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-08-13 07:23 UTC
