### ISSUE TITLE
Godot is not removing a Camera Node

### ISSUE THREAD

**Issue by tobiasbu** [godotengine/godot#24225] opened 2018-12-08 03:45 UTC
**Godot version:**

3.0.6 stable

**OS/device including version:**

Godot Editor, Windows 10

**Issue description:**

Changing the parent's node of the Camera is not working. Also when I toggle the visibility to `off` or set `Current` property to false the Camera stills render the scene.

**Steps to reproduce:**

1. I created a helper function to set parent of a Node (it would be nice if we can have a similar function in the Godot API)

```GDScript
func set_parent(parent, node):
	var nodeParent = node.get_parent(); 
	if (nodeParent == parent):
		return;
	nodeParent.remove_child(node);
	print(nodeParent.is_a_parent_of(node))
	parent.add_child(node);
```
2. Then in some script:

```GDScript
func _ready():
	var firstNode = get_node("/root/Game/");
	var mainCamera = firstNode.get_node("MainCamera");
	set_parent(self, mainCamera);
```
The camera node stills child of the `firstNode`...

3. Testing

Printing if the node is child of the previous parent outputs `True`

```GDScript
	print(nodeParent.is_a_parent_of(node))
```
If I just remove the Camera node with `nodeParent.remove_child(node);` it doesn't remove. It still rendering the scene.

**Minimal reproduction project:**

For this issue I'm sharing this **[project](https://drive.google.com/file/d/1bCm4AhZfONMtCbcBAdIkPYrbOi9RPuIV/view?usp=sharing)**.

**Comment by eon-s** [comment] 2018-12-10 04:01
`remove_child` does not delete the node (and it will leak references), but it should reset the current camera on the viewport when the camera leaves the tree, I suppose.

**Comment by akien-mga** [comment] 2020-06-20 21:24
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2021-02-03 19:58
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2021-02-03 19:58 UTC
Labels: bug, topic:core
