### ISSUE TITLE
F8 hotkey seems to be hardcoded

### ISSUE THREAD

**Issue by Avtem** [godotengine/godot#64352] opened 2022-08-13 09:02 UTC
### Godot version

3.5 stable

### System information

Windows 7 x64 SP1

### Issue description

So, Godot allows you to rebind your keys. Everything i rebinded works as expected except "F8" or "Stop execution" command. i rebinded this action to F12 key and when i run the game and want to terminate it by pressing F12 - nothing happens. But F8 for some reason still terminates my game.

### Steps to reproduce

Assign F12 to "Stop" command.
Run the game and press F12
Nothing will happen. But F8 still executes this command

**Comment by Calinou** [comment] 2022-08-13 10:23
Duplicate of https://github.com/godotengine/godot/issues/23929.

**Closed by Calinou** 2022-08-13 10:23 UTC
