### ISSUE TITLE
Differentiate between left and right shift in input map

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot#27962] opened 2019-04-12 19:46 UTC
Right now when binding keys to the input map left shift and right shift are both seen as "shift." you should be able to map input specifically to left shift or right shift.

**Comment by Calinou** [comment] 2019-04-12 19:49
Duplicate of https://github.com/godotengine/godot/issues/3347.

**Closed by Calinou** 2019-04-12 19:49 UTC
