### ISSUE TITLE
OmniLight shadows are calculated based on editor Display Mode, leads to quirks when enabling while in Wireframe view

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26200] opened 2019-02-23 17:09 UTC
Godot 3.0.6
Godot 3.1 beta6

I found out while testing a project on Discord that after toggling wireframe mode, the shadow of `OmniLight` sometimes projects wireframes instead, as if the scene rendered for the shadowmap was still in wireframe mode.

![image](https://user-images.githubusercontent.com/1311555/53289401-7edf7180-378d-11e9-8839-bda0be169f04.png)

Repro steps (as they happened initially):
1) Have an OmniLight with shadow enabled in Cube mode
2) Enable wireframe mode in the editor
3) Look around
4) Switch back to normal render mode: shadows are now wireframe

However, it doesn't always reproduce. I tried in simplified projects and was unable to get it. I only managed to repro twice in the original project but it seems to be random. ~~For this reason I also don't know if it reproduces in 3.1 beta6 yet~~. Maybe an uninitialized variable?

**Edit:
I found another set of steps which reproduce 100%.**
1) Have an OmniLight with shadow enabled in Cube mode and no shadows
2) Enable wireframe
3) Enable shadows
4) Disable wireframe: see it still projects wireframe

3.1 project: 
[OmniLightShadowWireframe.zip](https://github.com/godotengine/godot/files/2897038/OmniLightShadowWireframe.zip)

**Comment by clayjohn** [comment] 2020-07-11 06:44
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2021-04-28 12:38
It seems still reproducible in 3.3-stable.

The steps to reproduce show that the issue seems to be that the shadow get computed when enabled for the current display mode, so if it's Wireframe when they are enabled, the projected shadows will be wires even after switching to Normal mode.

Similarly, enabling shadows while in Overdraw or Unshaded display mode will lead to not seen any shadows when switching to Normal mode.

In either case, toggling shadows fixes it to match the current display mode again.

Changing display modes should likely force recomputation of shadows.

**Comment by akien-mga** [comment] 2021-04-28 12:42
That specific issue seems fixed in `master`, enabling shadows while in Wireframe mode will not lead to quirky shadows. There's another bug though that disabling shadows doesn't actually refresh the viewport but that's another issue :)

So I think this can be considered solved as it's not a critical issue to fix for 3.x (it only affects the edited scene until refreshed). Still, it might be fixable in 3.x if someone is motivated.

**Closed by akien-mga** 2021-04-28 12:42 UTC
Labels: bug, confirmed, topic:editor, topic:rendering
