### ISSUE TITLE
AnimationPlayer - Bezier key editing doesn't use snapping in curve edit mode

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#19468] opened 2018-06-09 16:17 UTC
**Issue description:**
As the title says, when editing bezier keys (in bezier curve editing mode) the keys ignore the time snapping option. I'm not sure if this is a bug or by design? Seems like it would be nice to have the option at least :)

**Comment by golddotasksquestions** [comment] 2019-09-02 10:59
Bezier curves keys not snapping makes the whole feature unusable for me. If I would not want them to snap, I would just uncheck the snapping button.

**Comment by KoBeWi** [comment] 2019-10-17 18:42
So what version was that? The snapping seems to work since 3.1. Could you confirm it's fixed?

**Comment by golddotasksquestions** [comment] 2019-10-20 13:40
Snapping does not work for me in 3.1. Win64:
![nosnap_curve_31](https://user-images.githubusercontent.com/47016402/67160221-dd75e300-f34e-11e9-89b8-50fbfcaf4dde.gif)

In 3.2 alpha2 there is horizontal snapping on the time axis, but no vertical snapping on the value axis and no snapping for handlers. Meaning the sole purpose for making this faster a graphical way to input data is defeated, as I would still have to go over to the inspector every time so set precise values (Even worse because due to handlers there are far more values to set)

![nosnap_curve_32](https://user-images.githubusercontent.com/47016402/67160301-be2b8580-f34f-11e9-8168-2d85f7582a84.gif)

**Comment by KoBeWi** [comment] 2022-01-11 22:42
In b52f90e79 there is horizontal snapping of handles, but no vertical snapping.

Seeing as it's is not a bug, I'll close it in favor of this proposal: https://github.com/godotengine/godot-proposals/issues/3141
You can comment in there about vertical snapping, if it wasn't mentioned already.

**Closed by KoBeWi** 2022-01-11 22:42 UTC
Labels: enhancement, discussion, topic:editor
