### ISSUE TITLE
Threading changes in 3.2.4-rc3 break C# threading

### ISSUE THREAD

**Issue by timothyparez** [godotengine/godot#46550] opened 2021-03-01 10:09 UTC
**Godot version:**
3.2.4-rc3

**OS/device including version:**
Ubuntu

**Issue description:**
This PR https://github.com/godotengine/godot/pull/45618 breaks C# threading.

**Steps to reproduce:**
Honestly it's hard to tell, I have a number of Task<T> running in the background 
in order to handle requests. It worked in 3.2.1, then other issues prevented me from
using newer version of Godot until 3.2.4-rc2 where everything just worked.  

**Minimal reproduction project:**
Will try to make one that causes the issue and then post it.  
Just wanted this PR to get flagged as soon as possible, would hate to see this end up in 3.2.4 final.

**Comment by akien-mga** [comment] 2021-03-01 10:19
>  This PR #45618 breaks C# threading.

Did you confirm that by testing a local revert, or is it a hunch based on the similarity of the PR and the issue you're experiencing?

**Comment by timothyparez** [comment] 2021-03-01 12:41
What I did so far is open the project in rc2 and see it work,
open the project in rc3 and see it fail and then repeat.

As for building it from source, given my geographical location it will take some time for 
me to download everything first.

**Comment by akien-mga** [comment] 2021-03-01 13:05
I can do a bisect myself if you can provide a project that reproduces the issue (which would likely be needed in any case to debug and fix the issue).

**Comment by oknpk** [comment] 2021-03-04 13:15
Same situation exists in my project. I use interactive loader inside the thread. All textures turn black box when loading is complete.
It works fine in the 3.2.4 rc2.
I've been having some time problem at work for a while. I could not produce a sample project in a simple structure. If no one has done it, I'll create a sample project over the weekend.

**Comment by akien-mga** [comment] 2021-03-04 13:59
I've done some tests with Godot `Thread` and `ResourceLoader.LoadInteractive` in the thread but couldn't reproduce any kind of breakage with 3.2.4 RC 3. So we'll really need a reproduction project indeed to debug further. I'm probably going to build 3.2.4 RC 4 tomorrow so there's a risk we won't have a fix for this issue by then... and then there might be a need for another RC 5 afterwards.

**Comment by oknpk** [comment] 2021-03-04 14:47
Sorry. When I tried it again, I realized that my problem was not thread sourced but weakref. I will create a new issue topic title related to the problem.

**Comment by timothyparez** [comment] 2021-03-05 03:01
Pinned it down to calling `GetStringSize` in another thread.
The attached project works great in rc2, crashes in rc3

[Issue46550.zip](https://github.com/godotengine/godot/files/6087893/Issue46550.zip)


Relevant code:

```
using Godot;
using System;
using System.Threading.Tasks;
public class Node2D : Godot.Node2D
{
    public override void _Ready()
    {
        var task = Task.Factory.StartNew(() => ProcessStuff(), TaskCreationOptions.LongRunning);
    }

    public void ProcessStuff()
    {

        var fontData = (DynamicFontData)GD.Load("res://Ubuntu-B.ttf");
        var font = new DynamicFont()
        {
            FontData = fontData,
            Size = 16,
        };

        font.GetStringSize("Let it crash");        
    }
}
```

Hope this helps.

**Comment by timothyparez** [comment] 2021-03-05 03:03
Pinned it down to calling `GetStringSize` in another thread.
The attached project works great in rc2, crashes in rc3

[Issue46550.zip](https://github.com/godotengine/godot/files/6087893/Issue46550.zip)


Relevant code:

```
using Godot;
using System;
using System.Threading.Tasks;
public class Node2D : Godot.Node2D
{
    public override void _Ready()
    {
        var task = Task.Factory.StartNew(() => ProcessStuff(), TaskCreationOptions.LongRunning);
    }

    public void ProcessStuff()
    {

        var fontData = (DynamicFontData)GD.Load("res://Ubuntu-B.ttf");
        var font = new DynamicFont()
        {
            FontData = fontData,
            Size = 16,
        };

        font.GetStringSize("Let it crash");        
    }
}
```

Hope this helps.

**Comment by akien-mga** [comment] 2021-03-05 08:30
Thanks, that's a great reproduction project. I couldn't trigger the issue on Linux so it might be macOS-specific.

**Comment by timothyparez** [comment] 2021-03-05 09:02
I do not use MacOS
I use Ubuntu 20.10...

Am able to reproduce it with the sample 100% of the times.

**Comment by akien-mga** [comment] 2021-03-05 09:02
Welp my bad, I got mixed up with the other macOS issues.

**Comment by akien-mga** [comment] 2021-03-05 09:03
Do you get any backtrace when it crashes?

**Comment by RandomShaper** [comment] 2021-03-05 09:11
Indeed, that's helpful! I'll check it.

**Comment by timothyparez** [comment] 2021-03-05 09:19
Will do that when I get back to the office.

**Comment by akien-mga** [comment] 2021-03-05 11:28
I set up a Ubuntu 20.04 VM to test (note: not 20.10, but I thought it might be close enough), and install Mono 6.12.0.122 and MSBuild 16.6 from the current upstream repo: https://www.mono-project.com/download/stable/

Sadly still can't reproduce the issue :|

**Comment by timothyparez** [comment] 2021-03-05 12:12
I added the `._sc_` file and confirmed it's running in self contained mode.  
Unzipped the project in a new folder and opened it

```
./Godot_v3.2.4-rc3_mono_x11.64 -v --editor /home/timothy/TMP/Issue46550/project.godot
```
The output and mono log are attached.

**Mono**

```
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:33:28 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

```
**msbuild**:

```
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.1520
```
[monolog+output.zip](https://github.com/godotengine/godot/files/6090362/monolog%2Boutput.zip)

**Comment by akien-mga** [comment] 2021-03-05 12:27
Thanks! The crash log lacks debug symbols (expected as official binaries are built without them, you'd have to build from source to get them), but whatever it includes is already useful:
```
Thread 9 (Thread 0x7f99849ff640 (LWP 179050)):
#0  0x00007f99a775068f in __GI___wait4 (pid=pid@entry=179059, stat_loc=stat_loc@entry=0x7f99849fd294, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007f99a775060b in __GI___waitpid (pid=pid@entry=179059, stat_loc=stat_loc@entry=0x7f99849fd294, options=options@entry=0) at waitpid.c:38
#2  0x0000000000f12ed2 in dump_native_stacktrace (signal=signal@entry=0x3cd60db "SIGSEGV", mctx=mctx@entry=0x7f9974002370) at mini-posix.c:1112
#3  0x0000000000f12fe9 in mono_dump_native_crash_info (signal=signal@entry=0x3cd60db "SIGSEGV", mctx=mctx@entry=0x7f9974002370, info=info@entry=0x0) at mini-posix.c:1156
#4  0x0000000000f05caf in mono_handle_native_crash (signal=0x3cd60db "SIGSEGV", mctx=mctx@entry=0x7f9974002370, info=info@entry=0x0) at mini-exceptions.c:3423
#5  0x0000000000e7d459 in altstack_handle_and_restore (ctx=0x7f9974002370, obj=0x0, flags=<optimized out>) at exceptions-amd64.c:879
#6  0x00007f99a71b7989 in ?? () from /lib/x86_64-linux-gnu/libGLdispatch.so.0
#7  0x00007f99849fe230 in ?? ()
#8  0x0000000002e4beb8 in RasterizerStorageGLES2::texture_create() ()
#9  0x0000000000000002 in ?? ()
#10 0x00000000075ee0d0 in ?? ()
#11 0x00007f997400e5e0 in ?? ()
#12 0x00007f99849fe230 in ?? ()
#13 0x00007f9974015460 in ?? ()
#14 0x0000000000000008 in ?? ()
#15 0x0000000000000002 in ?? ()
#16 0x00000000018e2ea2 in VisualServerWrapMT::texture_create() ()
#17 0x00007f997400e5e0 in ?? ()
#18 0x00007f99849fe230 in ?? ()
#19 0x00007f9974015460 in ?? ()
#20 0x0000000000000008 in ?? ()
#21 0x0000000000000002 in ?? ()
#22 0x00007f997400e5e0 in ?? ()
#23 0x00007f997400e5e0 in ?? ()
#24 0x00007f99849fe230 in ?? ()
#25 0x00007f9974015460 in ?? ()
#26 0x0000000000000008 in ?? ()
#27 0x0000000000000002 in ?? ()
#28 0x0000000001c210ab in ImageTexture::ImageTexture() ()
#29 0x0000000000000001 in ?? ()
#30 0x00007f9974015480 in ?? ()
#31 0x00007f99849fe230 in ?? ()
#32 0x000000000348d4a0 in Ref<ImageTexture>::instance() ()
#33 0x00007f99849fe230 in ?? ()
#34 0x0000000001bd1439 in Ref<Image>::ref_pointer(Image*) [clone .isra.0] [clone .lto_priv.4] [clone .lto_priv.0] ()
#35 0x00007f9974022dc0 in ?? ()
#36 0x00007f9974015220 in ?? ()
#37 0x00007f99849fe230 in ?? ()
#38 0x0000000001da6a7f in DynamicFontAtSize::_bitmap_to_character(FT_Bitmap_, int, int, float) ()
#39 0x00007f997401ff28 in ?? ()
#40 0x00007f990000000d in ?? ()
#41 0x0000000000000001 in ?? ()
#42 0x0000000000000000 in ?? ()
```

It seems to confirm a crash triggered in `RasterizerStorageGLES2::texture_create()` due to `DynamicFont`.

That sounds quite similar to #46679, and instead of platform-specific, this might be a GPU driver specific issue.

**Comment by timothyparez** [comment] 2021-03-05 15:26
[godot-3.2.4-rc-log.zip](https://github.com/godotengine/godot/files/6091473/godot-3.2.4-rc-log.zip)

From the debug version you provided

**Comment by bruvzg** [comment] 2021-03-05 16:52
Left few stack traces from macOS in the #46679 (same issue), seems like it's always crashing on OpenGL texture API function called from the thread.

**Comment by timothyparez** [comment] 2021-03-06 02:06
@akien-mga you cannot reproduce it locally, maybe we have different GPU vendors or drivers?

Mine:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:01:00.0  On |                  N/A |
| 38%   42C    P8    12W / 120W |   1476MiB /  3016MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Closed** 2021-03-06 23:01 UTC
Labels: bug, regression, topic:mono
