### ISSUE TITLE
Deleting any scripts in the file tree crashes the editor

### ISSUE THREAD

**Issue by Frontrider** [godotengine/godot#71886] opened 2023-01-22 22:47 UTC
### Godot version

4.0 beta 14

### System information

Manjaro Linux

### Issue description

Deleting any scripts in the file tree instantly crashes the editor. This one particular case only seems to happen with scripts.

I only have this backtrace for it.
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta14.official (28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7efefab9da00] (??:0)
[2] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x1b89e43] (??:0)
[3] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x1ba2230] (??:0)
[4] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x271296c] (??:0)
[5] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2c3a22e] (??:0)
[6] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x44a6efa] (??:0)
[7] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b7c4e9] (??:0)
[8] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b7cf4b] (??:0)
[9] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2addb85] (??:0)
[10] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b24dd7] (??:0)
[11] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b29031] (??:0)
[12] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b5a73b] (??:0)
[13] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x2b58b05] (??:0)
[14] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0xe546f4] (??:0)
[15] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x423dedc] (??:0)
[16] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0x423ed25] (??:0)
[17] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0xe55a6d] (??:0)
[18] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0xdd3762] (??:0)
[19] /usr/lib/libc.so.6(+0x23290) [0x7efefab88290] (??:0)
[20] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7efefab8834a] (??:0)
[21] /home/frontrider/godot/Godot_v4.0-beta14_linux.x86_64() [0xdf310e] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Delete any scripts in the file tree. The script does not need to be opened, nor attached to anything.

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-01-23 00:21
Duplicate of #71713 (already fixed).

**Closed** 2023-01-23 00:21 UTC
