### ISSUE TITLE
Button released() signal not working

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#4625] opened 2016-05-11 16:45 UTC
Button released() signal is not working.
Also the same for TextureButton.

Using git commit 7b471068cf8e4d166d8b0569b489f595213c3b52 under Mageia 5 (Linux x64)

**Comment by akien-mga** [comment] 2016-05-11 16:54
I can reproduce it with 7b47106 too, on Mageia 6 (Linux x64).

**Comment by akien-mga** [comment] 2016-05-11 17:13
It's supposed to be emitted here: https://github.com/godotengine/godot/blob/4a4f247/scene/gui/base_button.cpp#L88-L91
But obviously that doesn't work.

**Comment by eska014** [comment] 2016-05-11 19:24
The `released` signal is only emitted when the button is in "click on press" mode, since it's just the same as `pressed` otherwise

**Comment by SuperUserNameMan** [comment] 2016-05-11 23:14
same problem with official 2.0.2stable win64
( i'm just adding this useless message to be sure to receive further github notifications about this issue since I had to use the "click on press" mode workaround )

**Comment by reduz** [comment] 2016-05-11 23:48
This is not a bug, if you want to receive pressed/released combo you have
to use the click on press mode. Buttons by default emit pressed when
released otherwise.

**Comment by akien-mga** [comment] 2016-05-12 05:44
Then I'd say it's not a bug, but it dearly needs to be documented, as the name of the signal is a bit misleading. As an end user I'd expect my button to emit ``released`` when released, not only if using a specific mode. Even by reading the source code I couldn't really understand what ``released`` was meant to be used with, as this class is full of various states with similar names I got me confused :p

**Comment by neikeq** [comment] 2016-05-12 09:26
I swear there was already an issue about this, with the same conclusion. I can't find it...

**Comment by vnen** [comment] 2016-05-12 14:48
Can't the button send both signals when released? Also, IMO "Click on press" should be default.

**Comment by rgrams** [comment] 2016-05-12 18:56
When would you not want to get a released signal when a button is released?

**Comment by akien-mga** [comment] 2016-05-17 08:57
> Can't the button send both signals when released?

+1

**Comment by reduz** [comment] 2016-06-17 19:15
I don't know, I think it would be the same to make it emit both together than not emitting it. People would then complain about why both pressed and released happen at the same time.. I vote for closing this and make sure this is well documented

**Comment by vnen** [comment] 2016-06-17 20:11
I'm okay with keeping behavior and documenting, but it will go to my list of confusing API names that I will always complain...

IMO `button_down`/`button_up` instead of `pressed`/`released` is way simpler and unambiguous. And to use `clicked` as what is currently `pressed` since there's already "Click on press" option, so it's easier to see that the `clicked` signal will be emitted on press.

**Comment by reduz** [comment] 2016-06-17 20:27
how about button_up / button_down signals, and then leave pressed as it is?
that should make "release" less confusing
won't change now for compatibility but could be fixed for 3.0

**Comment by akien-mga** [comment] 2017-01-13 17:49
Fixed in de8cc30.

**Closed by akien-mga** 2017-01-13 17:49 UTC
Labels: documentation, junior job, topic:core
