### ISSUE TITLE
Key combinations don't work as expected in the Script editor on certain keyboard layouts

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#73362] opened 2023-02-15 14:47 UTC
### Godot version

4 RC2

### System information

Mac 11.6.8

### Issue description

On my Swedish keyboard, I have to press Option+number to get some special characters, for example @ and $. In the Script Editor these key combinations move focus to any of the four editor sections (2D, 3D, Script and AssetLib) instead of typing out the character.

If the ScriptEditor has focus I would expect all key combinations that generate characters to work as character input instead of Editor hotkeys.

### Steps to reproduce

On a Mac, go to Script Editor.
With a Swedish keyboard layout press Option + 2. 
The expected result would be to type "@", instead the focus is moved to the 3D Editor.

### Minimal reproduction project

-

**Comment by akien-mga** [comment] 2023-02-15 14:53
Duplicate of #66678

**Closed by akien-mga** 2023-02-15 14:53 UTC
