### ISSUE TITLE
Add A temp:// Data Path

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22363] opened 2018-09-22 23:44 UTC
It would be useful to have `temp://` as a data path option (like `res://` or `user://`). This would link to a directory whose files would be wiped after the engine is closed. This would allow for temporary file storage without the need for the user to manually clean up the directory themselves, along with allowing them to not need to figure out these temporary file paths themselves.

**Comment by reduz** [comment] 2018-09-22 23:53
This could be useful, but I am not quite sure how portable is this to every
platform.

**Comment by demipixel** [comment] 2018-09-23 00:30
For platforms that don't support it, maybe just put it in `res://_tmp/` and delete it once the game stops? (Or delete it on open if it didn't get deleted last time for some reason)

**Comment by vnen** [comment] 2018-09-23 00:42
> For platforms that don't support it, maybe just put it in res://_tmp/

If this is done then it should be in `user://` since `res://` is read-only in most platforms. The problem is that it might conflict with an actual path used by the project.

**Comment by LikeLakers2** [comment] 2018-09-23 00:47
> (Or delete it on open if it didn't get deleted last time for some reason)

I could think of some use cases for not deleting it on open, such as restoring state in the event of a crash. Perhaps deleting it upon opening the engine could be an option that's on by default?

> The problem is that it might conflict with an actual path used by the project.

You could use something like `user://.godot_temp/` (or `user://.godot/temp/`) which is unlikely to be a folder name that any game would use, even for their own temporary directory within `user://`.

**Comment by demipixel** [comment] 2018-09-23 01:02
> If this is done then it should be in user:// since res:// is read-only in most platforms.

Yep, my bad, mistype

**Comment by aaronfranke** [comment] 2018-09-23 10:09
> wiped after the engine is closed. 

It might also be a good idea for Godot to wipe that directory before starting as well.

**Comment by Calinou** [comment] 2018-09-23 11:49
Each OS has a way to create temporary directories in a standard location. On Linux, using `mktemp -d` creates a directory with a random name in `/tmp` and returns its absolute path (e.g. `/tmp/tmp.7TarLH6iLK).

Windows has a `%TEMP%` environment variable which points to the temporary data directory, there's probably an API to generate temporary directories as well.

**Comment by LikeLakers2** [comment] 2018-09-23 17:59
> It might also be a good idea for Godot to wipe that directory before starting as well.

I responded to someone else suggesting that here https://github.com/godotengine/godot/issues/22363#issuecomment-423783414, just so you know.

**Comment by LikeLakers2** [comment] 2019-07-05 08:36
Hey, I've been thinking about seeing if it'd be hard to implement this idea for some time now, but have no idea where to start.

Would anybody be able to point me to some relevant files to help get me started, or perhaps give me an idea of what I'd need to do to implement this sort of thing?

**Comment by clayjohn** [comment] 2020-05-27 18:33
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by clayjohn** 2020-05-27 18:33 UTC
Labels: feature proposal, topic:core
