### ISSUE TITLE
godot 3 compile web error

### ISSUE THREAD

**Issue by Lightnet** [godotengine/godot#17342] opened 2018-03-07 18:49 UTC
**Godot version:**
godot 3 build git

**OS/device including version:**
window 10 64bit

**Issue description:**
Can't compile the web version for module build.
I follow the link: http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_web.html

**Steps to reproduce:**

call scons platform=javascript tools=no target=release

**Minimal reproduction project:**

```
[vcvarsall.bat] Environment initialized for: 'x86'
Already up to date.
scons: Reading SConscript files ...
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 53%] [94mCompiling [95m==> [93mthirdparty\misc\clipper.cpp[0m
thirdparty\misc\clipper.cpp:901:7: error: cannot use 'throw' with exceptions disabled
      throw clipperException("Coordinate outside allowed range");
      ^
thirdparty\misc\clipper.cpp:1049:5: error: cannot use 'throw' with exceptions disabled
    throw clipperException("AddPath: Open paths must be subject.");
    ^
thirdparty\misc\clipper.cpp:1081:5: error: cannot use 'throw' with exceptions disabled
    throw; //range test fails
    ^
thirdparty\misc\clipper.cpp:1065:3: error: cannot use 'try' with exceptions disabled
  try
  ^
thirdparty\misc\clipper.cpp:1445:5: error: cannot use 'throw' with exceptions disabled
    throw clipperException("UpdateEdgeIntoAEL: invalid call");
    ^
thirdparty\misc\clipper.cpp:1513:5: error: cannot use 'throw' with exceptions disabled
    throw clipperException("Error: PolyTree struct is needed for open path clipping.");
    ^
thirdparty\misc\clipper.cpp:1563:3: error: cannot use 'try' with exceptions disabled
  try {
  ^
thirdparty\misc\clipper.cpp:2841:5: error: cannot use 'throw' with exceptions disabled
    throw clipperException("ProcessIntersections error");
    ^
thirdparty\misc\clipper.cpp:2830:3: error: cannot use 'try' with exceptions disabled
  try {
  ^
thirdparty\misc\clipper.cpp:3005:8: error: cannot use 'throw' with exceptions disabled
  else throw clipperException("DoMaxima error");
       ^
10 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
scons: *** [thirdparty\misc\clipper.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

**Comment by AlexHolly** [comment] 2018-03-07 20:19
duplicate https://github.com/godotengine/godot/issues/16960

**Comment by bojidar-bg** [comment] 2018-03-08 06:33
Indeed, closing as duplicate of the above-mentioned #16960.

**Closed by bojidar-bg** 2018-03-08 06:33 UTC
