### ISSUE TITLE
Using Eyedropper on color in second monitor crashed

### ISSUE THREAD

**Issue by protodrew** [godotengine/godot#63807] opened 2022-08-02 06:38 UTC
### Godot version

3.2.3 stable

### System information

Pop_OS 22.04, GLES3, X11, Gnome

### Issue description

When in the editor theme settings using the eyedropper on a color in a second display crashes Godot, tested twice and both times had to be killed by system monitor.

### Steps to reproduce

1. start a project (I did this on a brand new project but I don't think it matters)
2. go to the editor settings and then the theme category
3. change color (I tested with base and accent) and select eyedropper
4. move mouse to second monitor, at this point it has already crashed, but attempting to select a color proves it.

This kills the engine and attempting to alt-f4 brings up the "Exit the editor?" dialogue, which is also unresponsive

### Minimal reproduction project

Unneeded as it can be done on a brand new project

**Comment by JohanAR** [comment] 2022-08-02 17:39
Duplicate of #55003 ?

**Comment by Calinou** [comment] 2022-08-02 23:38
> 3.2.3 stable

[Godot 3.2.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) and check if the issue still occurs there.

**Closed** 2022-08-02 23:39 UTC
