### ISSUE TITLE
Project manager menu takes game pad input

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#15765] opened 2018-01-16 01:29 UTC
**Godot version:**
Godot RC1

**OS/device including version:**
\windows 10 x64

**Issue description:**
while on the Project manager menu if you select the run button it remains in focus/selected causing any further input from the game pad to be send to the Project manager.

**Steps to reproduce:**
the run button should be deselected/ lose focus after each press.

**Minimal reproduction project:**

**Comment by BeayemX** [comment] 2018-01-16 15:40
Duplicate of #15199

**Closed** 2018-01-16 15:50 UTC
Labels: archived
