### ISSUE TITLE
Autocompletion doesn't work for `class_name`

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#45890] opened 2021-02-11 10:11 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Linux

**Issue description:**

Autocompletion does not work for `class_name` keyword.

**Steps to reproduce:**
1. create a new script
2. write `cla`
as you can see, autocompletion appears with `clamp`, `class` and `ClassDB` but there is no `class_name` suggestion

![class_name](https://user-images.githubusercontent.com/16458555/107623489-37ed2e00-6c7b-11eb-8490-edce9f0e97c2.png)

**Minimal reproduction project:**

**Comment by arnoldochavez** [comment] 2021-02-12 09:17
Can be easily solved adding the string "class_name" here:
https://github.com/godotengine/godot/blob/e9a25b8552150393db9632fff23c0f60403b987a/modules/gdscript/gdscript_editor.cpp#L1067-L1071

**Comment by HolonProduction** [comment] 2023-06-06 14:20
Duplicate of #76344

**Closed** 2023-06-06 14:38 UTC
Labels: bug, topic:gdscript, topic:editor
