### ISSUE TITLE
line_draw always draws with width=1

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8289] opened 2017-04-06 15:28 UTC
**Operating system or device - Godot version:** Godot 3(master), Linux

**Issue description:**
Using any width value in draw_line seems to be useless, the drawn line is always 1px(?) in width.

**Comment by akien-mga** [comment] 2017-04-06 15:45
From IRC logs:
```
[17:33] <reduz_> nunod, in 3.0? not sure what to do about it, opengl 3.x does not support it
[17:33] <reduz_> nunod, as well as antialiasing, it's not supported either
[17:34] <reduz_> nunod, there probably should be a way around this, but i have no idea how to solve it
[17:34] <reduz_> for line width, a triangle could be used, which is not too bad
[17:34] <reduz_> well, two triangles
[17:34] <reduz_> but for antialiasing, no clue
[17:34] <nunod> reduz_, antialiasing seems to work fine
[17:34] <nunod> only the width is ignored
[17:35] <reduz_> i know, i mean antialiased thick lines
[17:39] <reduz_> nunod, it could be done with a shader without that much difficulty i guess, will have to see how to fix this eventually
[17:40] <reduz_> it must be fixable somehow
[17:40] <reduz_> i can think of ways to fix it, it's just not simple
[17:41] <Akien> reduz_: https://mattdesl.svbtle.com/drawing-lines-is-hard
[17:42] <Akien> Looks useful
```

**Comment by Zylann** [comment] 2017-04-06 18:02
In Godot master it's possible to draw polygon-based thick lines with Line2D ;)

**Comment by nunodonato** [comment] 2017-04-06 19:03
@Zylann I tried it, but can't get anything to show on the screen. Any examples available?

**Comment by Zylann** [comment] 2017-04-06 19:36
2D shapes themselves aren't broken, but this is: https://github.com/godotengine/godot/issues/7840#issuecomment-280926186

**Comment by nunodonato** [comment] 2017-04-06 19:41
@Zylann so... it doesnt work at the moment, right? :)

**Comment by Zylann** [comment] 2017-04-06 19:56
It works but you can't see it (in the issue I linked you can see the wireframe is correct), so... for the end user it doesn't works indeed^^

**Comment by nunodonato** [comment] 2017-04-06 19:59
so I guess its safe to close this, since the problem is basically in #7840 , right?

**Comment by Zylann** [comment] 2017-08-27 02:34
I found SpatialMaterial has an option for line width, which I needed to make some debug lines more visible, but it has no effect. Should it be removed or are there plans to implement general purpose line rendering in both 2D and 3D?

**Comment by akien-mga** [comment] 2018-12-05 14:37
If not done already, it could probably be reimplemented in the GLES2 backend. According to @reduz in https://github.com/godotengine/godot/issues/8289#issuecomment-292216210 the usual method is not supported in GLES3, so it needs a different implementation (or it will be fixed only when properly implemented in the Vulkan backend).

**Comment by JohnMeadow1** [comment] 2018-12-05 17:03
I have tested GLES2 on Godot 3.1 alpha 2, and it is the same.
So maybe we should drop or disable **Line Width** property  in **GeometryInstance** for now? 
It can be quite confusing, at current state.

**Comment by JohnMeadow1** [comment] 2018-12-07 15:09
I have researched this a bit, and apparently this is not a bug.
According to some standards (sorry no source) rendering API should support rendering a line with **at least** 1px width. 
What I managed to dig up is that modern Opengl, and DirectX support line_width=1 and that is all.
This is probably because drawing a line as a geometry is usually used only for debuging (e.g. ray tracing) and wireframe rendering. For game purposes you will most of the time use textured quads, So this is why they might have dropped it. 

Regarding **Line Width** property in **GeometryInstance**. If we want to render lines that are thicker, we need to write our own method for doing so. **Line Width** property is just not supported.
Unless I'm completely wrong, we might just need to drop Line Width property altogether, and think about Lines3D node.  

As mentioned before drawing-lines-is-hard.

**Comment by blakeearth** [comment] 2019-01-08 02:31
Draw_line's width parameter works as expected on my Windows machine running 3.0.6 Stable.

**Comment by Skaruts** [comment] 2019-07-24 17:23
I'm having this problem in 3D in Godot 3.1.1, in both GLES2 and 3.

**Comment by Calinou** [comment] 2019-07-24 19:51
@Skaruts It seems the 3D issue has been mentioned above in this thread, no need to create a new issue.

**Comment by Skaruts** [comment] 2019-07-25 05:02
@Calinou, indeed. I was just wondering. 

Although, I'm also wondering how the editor's 3D gizmos are drawn. Because they have thick lines. Could you point me to the place in Godot's source where this happens? I've no clue where to find it, but I wonder if I might find a workaround there.

**Comment by Calinou** [comment] 2019-07-25 11:07
@Skaruts It's in `spatial_editor_gizmos.cpp`:

https://github.com/godotengine/godot/blob/ad0d87b4dddfe6b9e88510dd526bcd4028ba3030/editor/spatial_editor_gizmos.cpp#L203

Gizmos are drawn using procedural meshes generated using ArrayMesh.

**Comment by Skaruts** [comment] 2019-07-25 14:37
@Calinou interesting... I always thought the manipulators would be made with `ImmediateGeometry`.

Anyway, thanks a lot for pointing me to it.

**Comment by bluenote10** [comment] 2019-12-13 12:52
For me (v3.1.2 stable, Linux) the width seems to be working, but it is the `antialiased=true` which doesn't seem to have any effect:

![image](https://user-images.githubusercontent.com/3620703/70801581-8cfb8e80-1daf-11ea-920e-c92c04899e4f.png)

Is this expected / tracked by this or another issue?

**Comment by JayFontenot** [comment] 2020-02-23 02:06
> For me (v3.1.2 stable, Linux) the width seems to be working, but it is the `antialiased=true` which doesn't seem to have any effect:
> 
> ```gdscript
> draw_line(Vector2(0, 0), Vector2(100, 200), Color(255, 0, 0), 3.0, true)
> ```
> 
> ![image](https://user-images.githubusercontent.com/3620703/70801581-8cfb8e80-1daf-11ea-920e-c92c04899e4f.png)
> 
> Is this expected / tracked by this or another issue?

I'm on v3.2 stable, Linux, having the same issue with anti-aliasing

**Comment by Calinou** [comment] 2020-02-23 13:25
@bluenote10 `Color(255, 0, 0)` will create an extremely overbright red color (255 times brighter than a non-overbright red)! This is why you can't see the antialiasingh effect at all. You want to use `Color(1, 0, 0)` or `Color8(255, 0, 0)` instead :wink:

**Comment by KoBeWi** [comment] 2020-12-24 15:32
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Skaruts** [comment] 2021-01-10 13:32
@KoBeWi it's not working for me in 3D, netiher in GLES2 nor GLES3. Lines are all 1 width. However, GLES3 doesn't work well anyway in my old Radeon HD 4870, and I don't know if it's supposed to work in GLES2 to begin with.

I suppose I can try to find time to make an MRP, if this is supposed to work in GLES2. I won't fiddle with GLES3, as it stalls a lot on my end.

**Comment by Calinou** [comment] 2021-01-10 13:49
> However, GLES3 doesn't work well anyway in my old Radeon HD 4870, and I don't know if it's supposed to work in GLES2 to begin with.

GLES2 should work on old GPUs, but GLES3 isn't expected to work correctly indeed.

**Comment by Skaruts** [comment] 2021-01-10 13:55
> GLES2 should work on old GPUs, but GLES3 isn't expected to work correctly indeed.

I meant the line widths, though. But I guess you answered my question, and it's not supposed to work at all in my gfx card, at least in 3.2.x. (I'll be switching to an NVIDIA soon anyway.)

**Comment by YuriSizov** [comment] 2023-02-22 12:07
I don't think this a problem in master, especially after fixes like https://github.com/godotengine/godot/pull/69851. Hardware limitation still applies of course, as described above.

**Closed by YuriSizov** 2023-02-22 12:07 UTC
Labels: bug, topic:rendering, topic:2d
