### ISSUE TITLE
Making dialog visible freezes editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56625] opened 2022-01-08 15:03 UTC
### Godot version

13d25f9

### System information

W10

### Issue description

When you add any Window-based node to the scene, e.g. AcceptDialog and set the `visible` property to true (it's under Flags category), the editor will freeze.

EDIT:
The comment below is more correct, I tested only with dialogs.

### Steps to reproduce

1. Add AcceptDialog
2. Enable `visible`
3. 🥶

**Comment by mieldepoche** [comment] 2022-01-08 15:26
I also have this behaviour on linux, godot 4.0.dev.20220105.official.8f6cba3a4.

I noticed that

1. the editor only freezes if the dialog has its `transcient` _and_ `visible` flags both set to `true`
2. the freeze only occurs when manipulating `AcceptDialog` (and inherited) nodes, not on the base `Window` or `Popup`.

**Comment by gerhean** [comment] 2022-01-10 04:11
Speaking of which, there's no documentation as to what exactly the `transcient` flag (and some other properties) is supposed to do.

**Comment by Chaosus** [comment] 2022-01-10 08:23
Duplicate of https://github.com/godotengine/godot/issues/51362

**Closed by Chaosus** 2022-01-10 08:23 UTC
Labels: bug, topic:editor, regression, topic:gui
