### ISSUE TITLE
Godot sometimes doesn't respond to mouse clicks until I click multiple times

### ISSUE THREAD

**Issue by DodyAlkarkhi** [godotengine/godot#46212] opened 2021-02-19 09:24 UTC
**Godot version:**
v3.2.3 stable

**OS/device including version:**
Windows 10

**Issue description:**
Basically the title. Sometimes it does respond, sometimes it doesn't. And sometimes there is a lag. [Video](https://user-images.githubusercontent.com/38881427/108484693-ffa9a900-7293-11eb-844c-d0c3cf258dd8.mp4)

**Steps to reproduce:**
There is probably something with my system that does this, so don't know.

**Minimal reproduction project:**
Not project related.

Would appreciate if someone is able to help. I can provide additional files or info as well

**Comment by Calinou** [comment] 2021-02-19 14:30
Duplicate of #23069. Try updating your graphics driver to the latest version *provided by Intel*. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2021-02-19 14:30 UTC

**Comment by DodyAlkarkhi** [comment] 2021-03-04 16:04
A bit late but it worked with --verbose. Thank you!
