### ISSUE TITLE
Home/End don't go to start/end of line when suggestions are open

### ISSUE THREAD

**Issue by CodexNotFound** [godotengine/godot#73701] opened 2023-02-21 19:45 UTC
### Godot version

4.0RC2, 4.0RC3

### System information

Windows 10

### Issue description

I'm a heavy user of the "home" and "end" keys on my keyboard while programming. In Godot 3.x these two buttons would always move to the beginning and end of the line as is expected from any text based editor. 

I just tried the 4.0RC2 and RC3 releases and here Home and End don't work whenever the suggestions dropdown is open.
![image](https://user-images.githubusercontent.com/105505041/220442058-390a574d-1ef4-4e17-9d96-9818102b360b.png)

### Steps to reproduce

1. Open any project
2. Create or open any GDscript file
3. Trigger the suggestions dropdown and press `Home`/`End` and see nothing happening
4. Press `Escape` to close the dropdown
5. Press `Home`/`End` again and see the cursor move to the start and end of the line.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-02-21 20:53
Duplicate of #71471

**Closed by KoBeWi** 2023-02-21 20:53 UTC
