### ISSUE TITLE
Top toolbar in main view forces the view to expand and cannot be resized narrower than the toolbar

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#58964] opened 2022-03-10 03:13 UTC
### Godot version

4.0 alpha 4

### System information

Linux

### Issue description

When selecting some nodes like Label, a bunch of different buttons are added to the top toolbar in the main view (the one right under the tabs). It becomes long enough to resize the neighboring docks, and the docks can't be widened again since the main view has to be as wide as the toolbar is.

Not sure what the node layout is of that toolbar, but simply putting it in an HScrollContainer would solve the problem, though not be ideal since there shouldn't really be a scroll bar there. Blender simply crops the toolbar and you can click and drag with the middle mouse button to scroll it. That works but it's not obvious to new users.

### Steps to reproduce

Add a Label to the scene, select it to make the top bar really long. Use the grabber on the left or right of the main view to make it narrower, and see that it is limited by the length of the toolbar.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2022-03-10 07:24
Duplicate of https://github.com/godotengine/godot/issues/58052

**Closed by akien-mga** 2022-03-10 07:24 UTC

**Comment by akien-mga** [comment] 2022-03-10 15:10
No worry, it was not easy to find without knowing that it's there :)
