### ISSUE TITLE
Zooming in the GDScript editor is very slow

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#51349] opened 2021-08-07 04:41 UTC
### Godot version

4cb406e02a7bc5761fd081b944cc1a5b09e2a365

### System information

Windows 10

### Issue description

It took almost 3 seconds to perform which is unacceptable (before was also slow but not such slow).

### Steps to reproduce

Use CTRL+SCROLL in the script editor.

### Minimal reproduction project

Too trivial to reproduce.

**Comment by akien-mga** [comment] 2021-08-07 09:00
Maybe related to #51314?

**Comment by Calinou** [comment] 2021-08-07 12:11
The editor has to re-rasterize the font every time you zoom in the script editor, which means it takes a while at larger font sizes.

**Comment by Chaosus** [comment] 2021-08-07 12:31
How does this thing work in VSCode? - it's smooth and fast as should be.

**Comment by Calinou** [comment] 2021-08-07 12:36
> How does this thing work in VSCode? - it's smooth and fast as should be.

I'd run a [C++ profiler](https://docs.godotengine.org/en/latest/development/cpp/using_cpp_profilers.html) over Godot to see what's taking the most time when zoomin in the script editor.

**Comment by RevoluPowered** [comment] 2021-08-09 21:08
One of the causes: it's saving every damn time you change the scroll depth

<img width="980" alt="Screenshot 2021-08-09 at 22 08 21" src="https://user-images.githubusercontent.com/748770/128774692-df02c3e4-466e-46f2-956a-a851e2011812.png">

**Comment by RevoluPowered** [comment] 2021-08-09 21:11
found another bug which seems to be the actual issue

**Comment by Chaosus** [comment] 2021-08-13 19:58
I think this was mostly fixed by #51585, further speed improvement may be an enhancement, it's not very slow anymore.

**Comment by RevoluPowered** [comment] 2021-08-14 06:49
Reopening because wasn't fixed by #51585 (resizing was still broken)

I fixed this in #51655

**Closed** 2021-09-21 13:18 UTC
Labels: bug, topic:gdscript, topic:editor, regression, performance
