### ISSUE TITLE
Ctrl+Z stops to work in Godot 2.1.3

### ISSUE THREAD

**Issue by cpusam** [godotengine/godot#8580] opened 2017-04-29 17:11 UTC
**Operating system or device - Godot version:**
Linux XUbuntu 16.04.1

**Issue description:**

The undo shortcut not works, not undo some modification. In previous godot version (2.1.2) the undo works but bad, sometimes it works sometimes not. Now in Godot 2.1.3 it stops to work completely.

**Steps to reproduce:**
Just press Ctrl + Z

**Link to minimal example project:**

**Comment by Zylann** [comment] 2017-04-29 18:08
Might be related or not, but I found out that some editor plugins clear the undo history under certain conditions. For example, the shader editor does that if a new shader is created in the inspector while a shader is already being edited. As a result, it not only clears actions done on a resource, it also clears whatever was done since Godot is open.

**Comment by sam-leo** [comment] 2017-04-29 20:51
Hum, ok, I tried a simple project and the undo works, I've tested in some project and only in mine undo not works. When I used godot 2.1.2 in this same project the undo works perfectly. I'm not using any shaders, it's just a project with normal resources.

**Comment by jedStevens** [comment] 2017-05-01 09:10
I've found many errors with the undo feature, it would be nice if each view (2d/3d/script) had their own separate histories, and crtl+z changed the current one.

I just find myself having to mash undo for things to undo, like 3-10 presses for one change sometimes.

**Comment by bojidar-bg** [comment] 2017-05-01 12:34
I guess we should go over all uses of the editor's undoredo and clean them up...
That's about 202 `commit_action` lines,  **12 `clear_history` lines**, and a few other uses here and there...

**Comment by Zylann** [comment] 2017-05-01 13:41
PRs too? Mine uses this global undo too...

**Comment by bojidar-bg** [comment] 2017-05-01 15:21
@Zylann Well, PRs are to be reviewed by reviewers, though feel free to check if you aren't doing something weird there.

**Comment by Zylann** [comment] 2017-05-01 15:40
Well... I'm clearing the whole history, which is not nice. A better option would have been to include the target resource in the undo action, but because UndoRedo is global, you would have to undo changes to the resource before being able to undo what you did on unrelated stuff before.

**Comment by reduz** [comment] 2017-05-01 15:56
I did a few fixes in the 3.0 branch, where I think it works properly

**Comment by sam-leo** [comment] 2017-05-02 02:26
Just a little note: in the script editor the undo works great, but my game cannot undo on the 2d view editor

**Comment by insomniacUNDERSCORElemon** [comment] 2017-07-05 08:20
I have noticed a tiny oddity with this: undo doesn't work if you have not moved your mouse since the last action.

Do certain actions (seen with moving an item, toggling visibility, moving or deleting a vertex on a polygon2d, changing node order) and keep the mouse still. Mash undo and it'll do nothing. Now move the mouse even a tiny bit and not undo works again.

--------------------

Note that after changing node order the mouse pointer keeps a hand as if it still thinks dragging is still occurring, so possibly it's getting locked on mouse input and that's why undo stops working until the mouse is moved.

**Comment by kubecz3k** [comment] 2018-04-07 10:45
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment] 2018-04-07 14:32
I found that Ctrl+Z stops working in the scene if you have the shader editor open, even if you explicitely focus the scene tree or the viewport. Undo basically gets taken by the shader editor regardless. Closing the shader editor then makes you able to undo things in the scene.

**Comment by akien-mga** [comment] 2018-11-22 10:49
This issue is quite old and lacks visibility, so IMO it would be better to open a new one against the master branch, describing what the current state is for undo-related issues.

**Closed by akien-mga** 2018-11-22 10:49 UTC
Labels: bug, needs testing, topic:editor, usability

**Comment by roman-sitewits** [comment] 2020-12-11 13:52
Still happening, needs a fix desperately. I have never seen so many bad decisions in the GUI. Eg: you can't run with F5 if you are in an input field, you have to press ESC every time. Shader window closing and I have to click multiple times to re-open the editor. This is just off the top of my mind, and critical to be fixed sooner than most other stuff since if it's unusable, other stuff don't matter.

**Comment by Calinou** [comment] 2020-12-11 14:10
@roman-sitewits Please open a new issue for that, it's likely unrelated. Also, note that shortcut handling has been rewritten for 4.0.

**Comment by elvisish** [comment] 2021-10-31 21:04
Just want to comment that info/redo shortcuts are still amazingly broken and unreliable.

**Comment by JoeZPS** [comment] 2022-08-24 03:05
Hey guys, just click Undo in the scene tab and it will work
![image](https://user-images.githubusercontent.com/111733378/186311231-122b7afa-dc72-49f5-ba51-80ba43b3ff3f.png)
