### ISSUE TITLE
RigidBody "bumps" on collision seams

### ISSUE THREAD

**Issue by iwilliams** [godotengine/godot#66778] opened 2022-10-02 18:32 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Linux Ubuntu

### Issue description

A `RigidBody` rolling across a flat surface composed of several collision shapes will bump or snag when crossing the seam between the two collision shapes.

https://user-images.githubusercontent.com/5215799/193470180-917729be-9817-4f77-a4ae-d55388a3a0d3.mp4

### Steps to reproduce

1) Create a surface made of several collision shapes / static bodies.
2) Create a `RigidBody` ball.
3) Apply an impulse to the ball and observe the bump.

### Minimal reproduction project

[mini-golf.zip](https://github.com/godotengine/godot/files/9693208/mini-golf.zip)
Press "Space" to launch the balls.

**Comment by Calinou** [comment] 2022-10-02 23:13
Duplicate of https://github.com/godotengine/godot/issues/50463.

**Closed by Calinou** 2022-10-02 23:13 UTC
