### ISSUE TITLE
Change particles to use emission rate rather than max allowed particles. 

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#4294] opened 2016-04-12 12:49 UTC
**Issue description:** (what happened, and what was expected):

Currently, particle emitters don't have an emission rate property, they just have an "Amount", which controls the maximum particles allowed to exist at one time (from that emitter). You can't directly control the particle emission rate. Besides being confusing, this causes at least two issues:

**1. Changing the particle Lifetime changes the emission rate** (double the lifetime --> half the emission rate), which means you have to adjust two properties at once to get the effect you want. 

**2. Animating the Amount to a lower value will delete particles instantly rather than letting them expire normally.** This is the real issue. Because of this there's no way to animate an emitter's spawn rate without it looking horrible and choppy as random particles vanish instantly. Enabling/disabling works fine, but obviously that's pretty limited.  

[Edit] **3. Since Amount and Lifetime are linked, we can never have a random particle lifetime feature.** Being able to spawn particles with variable lifetimes would be a nice addition to particle systems, but since that would mess up your spawn rate, it's not really an option with the current setup. 

_A side issue: the Amount can't be set to zero for some reason._

**Comment by akien-mga** [comment] 2018-04-04 08:11
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:50
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2018-05-29 08:50 UTC
Labels: enhancement, topic:core
