### ISSUE TITLE
Error: affine_invert: Condition "det == 0" is true

### ISSUE THREAD

**Issue by MugenTwo** [godotengine/godot#36642] opened 2020-02-28 13:39 UTC
**Godot version:**
3.2

**OS/device including version:**
Kubuntu 20.04

**Issue description:**
While running my game, I am getting spam errors of:
E 0:00:01.065   affine_invert: Condition "det == 0" is true.
  <C++ Source>  core/math/transform_2d.cpp:51 @ affine_invert()

**Steps to reproduce:**
Add the following line in C# code: 
rigidBody2d.Transform = newTransform;

From what I can understand this is not the right way to do what I want to achieve.
But nevertheless, if the API does allow this, I believe the error must be addressed.

**Comment by aaronfranke** [comment] 2020-02-29 06:53
What is the output of `GD.Print(newTransform);`?

**Comment by MugenTwo** [comment] 2020-03-01 08:18
The output is something like this:
((0, 0), (297.6345, 0), (0, 0))
((0, 0), (446.4517, 0), (0, 0))
((0, 0), (0, -37.6484), (0, 0))
((0, 0), (297.2244, 0), (0, 0))
((0, 0), (445.8366, 0), (0, 0))
((0, 0), (0, -40.46407), (0, 0))
((0, 0), (296.7818, 0), (0, 0))
((0, 0), (445.1726, 0), (0, 0))
((0, 0), (0, -43.262), (0, 0))
((0, 0), (296.3065, 0), (0, 0))
((0, 0), (444.4598, 0), (0, 0))
((0, 0), (0, -46.04094), (0, 0))
((0, 0), (295.7989, 0), (0, 0))

**Comment by aaronfranke** [comment] 2020-03-01 08:37
@MugenTwo This is expected behavior. The determinant is zero because the X axis of your transform is `(0, 0)` (the part on the left), so Godot has to throw an error.

```cs
        Transform2D translation = new Transform2D();

        translation.y = motion * distance;
```

You are creating a new Transform2D called `translation` and setting `translation.y` without setting `translation.x`, also note that `translation` is a misleading name since this is a full transform. More importantly, you need to use `Transform2D.Identity` instead of `new Transform2D()`, since in C# it is a language feature that parameterless constructors make every member the default value.

I think you should [read the code more closely](https://github.com/godotengine/godot-demo-projects/blob/master/2d/physics_platformer/platform/moving_platform.gd):

```gdscript
	var xf = Transform2D()
	
	xf[2]= motion * d 
```

Index 2 is the origin, and also as I said you need to use Identity, so try this instead:

```cs
        Transform2D transform = Transform2D.Identity;

        transform.origin = motion * distance;
```

Anyway, I'm closing this because this isn't a Godot bug.

**Closed by aaronfranke** 2020-03-01 08:37 UTC

**Comment by MugenTwo** [comment] 2020-03-01 08:48
@aaronfranke Isn't godot supposed to tell me which line and code generated an error instead of showing a cpp error?

**Comment by aaronfranke** [comment] 2020-03-01 09:24
@MugenTwo Godot already told you that the determinant is zero, and it already told you that it's a problem with the transform. There is no possible way for Godot to give more details about the error. 

In your original code you are starting with a zeroed-out transform and setting the Y component. So what does Godot do, tell you to set the X component? That's not even a line of code causing the problem, it's a lack of code. But even then, that's not the solution you were looking for, since you meant to set the origin instead of the Y component.
