### ISSUE TITLE
Abnormal Spinning/Swooping Rigidbody Behaviour

### ISSUE THREAD

**Issue by DezBoyle** [godotengine/godot#70965] opened 2023-01-05 19:04 UTC
### Godot version

v4.0.beta8.mono

### System information

Windows 10 x64

### Issue description

Long-shaped rigidbodies swoop and spin around abnormally, even with a single primitive collider and an empty project.

Reproduced on an empty project with this setup
https://imgur.com/a/n4MiDAa

Rigidbody spins and behaves abnormally when falling.
VIDEO : https://i.imgur.com/TmckQst.mp4

https://user-images.githubusercontent.com/41555304/210860145-0e955e43-5809-4ed5-96f6-9fc5e008839f.mp4

### Steps to reproduce

- Add a rigidbody with a long-shaped collisionshape.
- Drop the rigidbody on a slope
- Abnormal behavior

### Minimal reproduction project

[BrokenPhysicsReproduction.zip](https://github.com/godotengine/godot/files/10354986/BrokenPhysicsReproduction.zip)

**Comment by Calinou** [comment] 2023-01-06 23:31
Duplicate of https://github.com/godotengine/godot/issues/61827.

**Closed by Calinou** 2023-01-06 23:31 UTC
Labels: bug, topic:physics, topic:3d
