### ISSUE TITLE
TileMap Tile Origin Center not respected by map_to_world()

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#2884] opened 2015-11-23 13:26 UTC
When calling map_to_world() in gdscript the returned coordinates are the top-left of the tile even if the tile origin is set to Center.  The expected behavior is that the center of the tile is returned.

Commit b12c2846ee03584c096a80cabe157560b74fa1bf includes a change to fix tile_map.cpp and it works perfect in runtime but the editor no longer displays properly.  tile_map_editor_plugin.cpp is very dense and trying to fix it to account for this change is intimidating so I wanted some feedback before attempting to tackle this issue.

**Comment by akien-mga** [comment] 2015-11-29 12:53
This might be related to #2513 which also seems to refer to unimplemented methods to better manage tile centering.

**Comment by reduz** [comment] 2016-01-23 22:00
Are you sure you want map to world to do that? I'm not sure I can think of reasons why something else should be the default behavior.

**Comment by reduz** [comment] 2016-01-23 22:00
When you edit with the editor, and click with the mouse this function is used... if it worked differently the tile editor would not work

**Comment by akien-mga** [comment] 2016-07-15 09:06
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment] 2018-01-09 17:50
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment] 2018-01-09 17:50
BTW this might be fixed in 3.0, there were various changes to this stuff.

**Comment by Piripant** [comment] 2018-07-26 14:54
This issue is still present. I also noticed that this creates an inconsistency, where `world_to_map` and `map_to_world` are no longer inverse functions:
```
var map_pos = world_to_map(global_position)
var original_position = map_to_world()
# but now we have that
original_position != global_position
```
If the behavior of `world_to_map` and `map_to_world` must be preserved like this to work in the editor, I think an optional argument to calculate the coordinates considering the tiles offset would be nice. (I have found that on `map_to_world` is already present but does not seem to work).

Let me now if I can help in any way!

**Comment by akien-mga** [comment] 2018-12-14 16:35
If this is still relevant in the current master, could someone provide a simple project that reproduces the issue?

**Comment by akien-mga** [comment] 2018-12-14 16:38
We're about the enter the beta stage and *release freeze* for Godot 3.1, where only critical bug reports will be prioritized. Moving this issue to the 3.2 milestone, but please comment if you think that this issue is a must-fix for 3.1. (Do note that issues fixed after 3.1 is released may still see their fix backported to the stable 3.1.x releases.)

**Comment by Azza292** [comment] 2018-12-18 18:53
Currently having this issue in my project. I would also expect changing the `tile_origin` would change the output of `map_to_world()`. Ref: https://github.com/Azza292/MazeMover/tree/master/MoveMaze

**Comment by Brickcaster** [comment] 2018-12-18 21:52
I resolved the issue locally by declaring my own map_to_world() transfer function.  It's been a while, but when I delved into the tilemap.cpp file, there seemed to be a lot of interdependent features.  The same function that the python calls upon is also used by the editor for drawing stuff like grid lines.

The function I'm using (which makes a lot of assumptions given my use-case) is thus:

`func map_to_world(vect):
	return (.map_to_world(vect)+Vector2(32,35))`

Shouldn't be too hard to insert similar functionality into the C++.

**Comment by Azza292** [comment] 2018-12-19 13:30
Thanks @Brickcaster, This is what I ended up implementing. 

```
extends TileMap

...

func map_to_world(map_position, ignore_half_ofs=false):
	return .map_to_world(map_position, ignore_half_ofs) + get_cell_size() / 2
```

**Comment by Brickcaster** [comment] 2020-06-17 15:53
Not sure if related, but I attempted to create [Langton's](https://en.wikipedia.org/wiki/Langton%27s_ant) Ant in Godot Engine, intended as a teaching exercise.  I ran into a problem on the third iteration where the ant moves from (-1,0) to (0,-1) (2 steps) and it suffers other weird artifacts around the axis.  If I change the starting position to 100,100 (via line 4 of ant.gd), it behaves as expected, at least until the ant hits the y axis.

Here's a minimal project demonstrating this.  Press "enter" to advance the ant one step.
[Langtons_Ant_bugged.zip](https://github.com/godotengine/godot/files/4793742/Langtons_Ant_bugged.zip)

**Comment by cbondurant** [comment] 2020-07-11 19:56
I would like to also note that I am having this issue as well.

My main use-case is that I would like to be able to use the center of the tile as a reference when aligning non-tile sprites to the grid, as otherwise I have no simple visual indicator of where they will be in relation to the tilemap.

**Comment by KoBeWi** [comment] 2021-05-17 19:08
According to this comment in the new tileset editor, the method should center of the tile:
https://github.com/godotengine/godot/blob/92c04fa727e3fc507e31c1bce88beeceb98fb06a/scene/2d/tile_map.cpp#L905-L907
Seems like it's not the case here:
![image](https://user-images.githubusercontent.com/2223172/118542698-a8f92180-b753-11eb-8e8c-45299aa777ac.png)
```
func _ready() -> void:
	print($TileMap.map_to_world(Vector2i(0, 0)))
	print($TileMap.map_to_world(Vector2i(1, 0)))
```
Result:
```
(16, 16)
(48, 16)
```
Both tiles return the same y value.
[Node.zip](https://github.com/godotengine/godot/files/6496270/Node.zip)

**Closed** 2022-01-24 20:03 UTC
Labels: bug, topic:editor, confirmed

**Comment by FuzzyHerbivore** [comment] 2022-07-31 09:48
Kind of a newb here, but I stumbled across this as well. I used "Tile Origin: Center" for the given TileMap and was expecting map_to_world to deliver the center coordinates then, because all sprite nodes I use are centered (and in fact the "Offset -> Centered" option of Sprites is defaulted to "On"). What is the "Tile Origin" setting for, if not for this if I may ask?
