### ISSUE TITLE
Polygon2D and Holes (subpolygons / clipping)

### ISSUE THREAD

**Issue by renatodex** [godotengine/godot#41447] opened 2020-08-22 10:09 UTC
## **Godot version:**
3.2

## **OS/device including version:**
MacOS Mojave 10.14.5

## **Issue description:**
I'm having issues trying to draw a Polygon with a Hole inside using `Polygon2D` object.
I've tried many different approaches, but it seems something is not working on Polygon2D.

Basically, I have a Polygon in the shape of "C"letter, and then I Draw another Polygon, in the shape of "I" letter, like this:
<img width="200" src="https://user-images.githubusercontent.com/68507/90953656-edb18f80-e443-11ea-9c43-51eba94bdf4d.png"></img>

And then what I try to do, is to do a Merge operation using `Geometry#merge_polygon_2d`, and the result is applied back to the Polygon2D using the `set_polygons` function.
I can confirm that the `merge_polygon_2d` is returning both **Boundary** and **Hole** Polygons, but i'm not able to use these polygons to draw a new polygon with the hole as a subpolygon, using the result of the merge operation.

So what I have when I do `set_polygons(merge_result)` is nothing: (the Polygon just don't render anything)

<img width="200" src="https://user-images.githubusercontent.com/68507/90953892-be038700-e445-11ea-8cfa-379ed45d0165.png"></img>

It's important to know that if I use the `set_polygon` (singular) method, I can successfully render both **Boundary** and **Hole** Polygons returned by the `merge_polygon_2d` operation:

<table>
<tr>
<td>
**Boundary Polygon** (`merge_result[0]`)
<img width="200" src="https://user-images.githubusercontent.com/68507/90953918-f1461600-e445-11ea-9e66-6efe025238e9.png"></img>
</td>
<td>
**Hole Polygon** (`merge_result[1]`)
<img width="200" src="https://user-images.githubusercontent.com/68507/90953924-fb681480-e445-11ea-8c08-24e1209ee5c4.png"></img></td>
</tr>
</table>

## **Expectation**
By assigning result of merge operation to `set_polygons`, I was expecting something like this:

<img width="200" src="https://user-images.githubusercontent.com/68507/90954049-4fbfc400-e447-11ea-9986-59701a7e9af9.png"></img>

## **Steps to reproduce:**
- Create a Polygon2D "A". in the shape of "C" Letter
- Create another Polygon2D "B" in the shape of "I" Letter, creating an intersection with a Hole shape. (see image below)
- Merge Polygon A with B, and apply the `polygons` result to Polygon A.
- Hide Polygon B for cleaning purposes
- You should see that the Polygon disappear after `set_polygons(merge_result)`

<img width="200" src="https://user-images.githubusercontent.com/68507/90953656-edb18f80-e443-11ea-9c43-51eba94bdf4d.png"></img>
(example image showing Polygon disposition)

## **Minimal reproduction project:**
https://github.com/renatodex/godot_polygon2d_hole_issue

## **Extra Notes**

It's important to note that I've tried @Xrayez module `Goost` to see if I could make it work, but actually, it seems it's a problem from Polygon2D itself.
It's also important to note that I know that there is a `draw_polygon` function to be used with `draw`, but I really want to make Polygon2D work, **since they allow me to have better Remote visualization of all creation processes happening on my project**.

Also, in this demo, I've used the `set_polygons` function, but I'm not sure how much it works, because it seems by the project documentation that this part of Polygon2D is not done yet:
![image](https://user-images.githubusercontent.com/68507/90953633-af1bd500-e443-11ea-93ac-0cef23830c87.png)

**Comment by Xrayez** [comment] 2020-12-27 13:52
I've recently implemented `PolyNode2D` class in goostengine/goost#39 which acts like `Polygon2D` but also allows to use boolean operations (like in CSG nodes in 3D). Holes are automatically drawn if you add two nodes: parent and child with child operation set to `OP_DIFFERENCE`.

Alternatively you can use `PolyNode2D.make_from_outlines(polygons: Array)` which will do this for you, but you'll have to make sure that the hole's vertices in `polygons` have clockwise orientation.

Since this is unlikely to be added/fixed in 3.2, that should be a good alternative to use over `Polygon2D`, at least for visualization purposes (it's also possible to assign textures and normal map to customize drawing.

Holes support can still be added in 4.0.

**Comment by Necronomicron** [comment] 2023-04-23 20:49
Is there any update on this? Or plans at least? 🤔

**Comment by smix8** [comment] 2023-04-29 04:12
The Polygon2D `polygons` Array is for `PackedInt32Array`'s of indices for the `polygon` vertices.
If you set them up correctly they render multiple polygons just fine and as intended by the rendering.

Your "Expectation" does not exist in rendering. The rendering has no concept of a polygon "hole".

If you want the rendering to display something that looks like a polygon with a hole you need to convert your Geometry2D outline arrays into multiple polygons and render them individually e.g. slice your polygon in two halves around that hole.

This is how all the debug visuals are drawn inside the Editor as those create new polygons or meshes to display with holes correctly (if they even support holes, e.g. Polygon2D doesn't). E.g. the NavigationPolygon converts the Editor drawn outlines into vertices and polygon arrays with indices  and the debug visuals draw each of those polygons individually.

The missing documentation has also been fixed so I don't think that there is anything more to do for this issue.

**Comment by Calinou** [comment] 2023-10-27 08:42
This still seems to be a documentation issue, unless you're referring to adding editor functionality to merge/split polygons in the 2D editor (in which case this should be discussed in https://github.com/godotengine/godot-proposals/issues/913).

**Comment by Necronomicron** [comment] 2023-10-27 09:10
> This still seems to be a documentation issue, unless you're referring to adding editor functionality to merge/split polygons in the 2D editor (in which case this should be discussed in [godotengine/godot-proposals#913](https://github.com/godotengine/godot-proposals/issues/913)).
> 
> If you are calling Geometry2D functions from code, surely you can call a few more – but you need to be able to learn about this somehow.

I'm talking about the ability to create polygons with holes and corresponding collisions. From the code and in the editor. From scratch **and** using boolean operations.

**Comment by Calinou** [comment] 2024-02-18 23:51
Closing in favor of https://github.com/godotengine/godot-proposals/issues/9127, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2024-02-18 23:51 UTC
Labels: topic:core, topic:rendering, documentation, topic:2d
