### ISSUE TITLE
Theme StyleBoxFlat Shadow is not working on TextEdit.

### ISSUE THREAD

**Issue by cybergeek1943** [godotengine/godot#68341] opened 2022-11-06 19:50 UTC
### Godot version

3.5-stable

### System information

Windows 11, GLES2, GeForce GTX 1650

### Issue description

I want to have a shadow as a border whenever TextEdit is focused. Now this works just fine when theming LineEdit. But the shadow theming property does not work at all when applying it to TextEdit.
![Screenshot_20221106_124925](https://user-images.githubusercontent.com/98766012/200191599-5ba6cc7d-49b5-45f8-aab8-5eb21e684477.png)
![Screenshot_20221106_124723](https://user-images.githubusercontent.com/98766012/200191600-c16adcca-da28-41e9-8cc2-5b746442deb0.png)
![Screenshot_20221106_124745](https://user-images.githubusercontent.com/98766012/200191601-e979ca22-fa79-4d8c-a647-84a8c6046b85.png)

### Steps to reproduce

Just use the Minimal reproduction project or simply try to theme a TextEdit with a shadow.

### Minimal reproduction project

Here is an example: [Godot Testing.zip](https://github.com/godotengine/godot/files/9946710/Godot.Testing.zip)

**Comment by Calinou** [comment] 2022-11-06 20:42
Duplicate of https://github.com/godotengine/godot/issues/32996 (same cause).

**Closed by Calinou** 2022-11-06 20:42 UTC
