### ISSUE TITLE
Parsing error when referencing members of an inherited class

### ISSUE THREAD

**Issue by EmeraldSlash** [godotengine/godot#32885] opened 2019-10-17 03:45 UTC
**Godot version:** 3.1

**OS/device including version:** Windows 7 Pro

**Issue description:** When trying to reference members of a class inherited through class_name, the editor shows a parsing error. This can sometimes be fixed by using `self` before the member name, however not always. The specific errors thrown are:
- `Method 'MethodName' is not declared in the current class`
- `Identifier 'identifier' is not declared in the current scope`.

Examples of different types of statements that can throw this error:
- `$AnimationPlayer.play_animation("show")`
- `position.x = 0`
- `self.set_physics_process(true)`

This issue doesn't occur when the file path of the inherited class is used instead of its given class_name, i.e. `extends "res://Enemy.gd"` parses fine but `extends Enemy` doesn't.

**Steps to reproduce:**
- Create a new .gd file and give it a class_name
- Create another script and extend the .gd file you created by its class_name
- Try to reference members of the .gd file

**Comment by KoBeWi** [comment] 2019-10-22 14:30
Could you test if it works in 3.2 alpha?

**Comment by tom-jk** [comment] 2020-08-10 16:50
Testing with given reproduction steps on linux mint 18.3.

Can't reproduce with 3.1.alpha1, 3.1.stable, 3.1.2.stable, 3.2.alpha0, 3.2.2.stable, 3.2.3.rc3

<details><summary>scripts used and 3.1.stable output</summary>

MyNode.gd
```gdscript
extends Node
class_name MyNode

var member_a = 10
var member_b = 32
var member_c = "funny"

func method(param):
	print("method: ", param)

func overrideable(param):
	print("overrideable: ", param)
```

MyExtraNode.gd
```gdscript
extends MyNode

var x = member_a
var y = member_b
var z = member_c

func _ready():
	print(member_a)
	print(member_b)
	print(member_c)
	method(str(member_a + member_b) + " = " + member_c)
	overrideable("myself")
	.overrideable("my parent")

func overrideable(param):
	print("overriden: ", param)
```

Output when MyExtraNode.gd attached to a node and scene run:

```
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTX 750 Ti/PCIe/SSE2
10
32
funny
method: 42 = funny
overriden: myself
overrideable: my parent
** Debug Process Stopped **
```

</details>

No errors given. No difference between `extends MyNode` and `extends "res://MyNode.gd"`. If I make an error in the base class and save, then those errors are thrown in the extending class which is expected. Correcting the errors in base solves errors in extending.

@EmeraldSlash could you provide a minimal project that reproduces the issue?

**Comment by akien-mga** [comment] 2020-12-10 13:37
No answer, so closing. Please comment if you can still reproduce the issue, and make sure that there is an up-to-date reproduction project.

**Closed by akien-mga** 2020-12-10 13:37 UTC
Labels: bug, topic:gdscript
