### ISSUE TITLE
SMI experiment Center issue while running web version of the app

### ISSUE THREAD

**Issue by Garimamudgal** [godotengine/godot#29969] opened 2019-06-21 22:06 UTC
**Godot version:**

godot 3

**OS/device including version:**

 
SMI  experiment center for eye tracking data

**Issue description:**

I try to run web version of my app in firefox browser, it works fine.
but when i embedd the url in the SMI experiment center , and run it remotly on a system, the app version doesn't open and it gives error "Browser doesn't support web assembly"

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2019-07-08 15:10
Godot's HTML5 export requires WebAssembly as of 3.0, as it's much more efficient than asm.js. If the browser doesn't support WebAssembly, I don't think anything can be done about it.

**Comment by Garimamudgal** [comment] 2019-08-19 21:20
Can it be the case that the interface between the new Firefox browser and the SMI software needs to be updated ?

**Comment by Calinou** [comment] 2020-04-25 19:54
@Garimamudgal How does the SMI experiment center work exactly? Is it a browser plugin or something? Is it a standalone browser using a built-in OS WebView like Internet Explorer or EdgeHTML?

**Comment by Faless** [comment] 2020-07-28 00:37
This seems related to the Firefox version/configuration used by an external software.
There is not much we can do about it and given the lack of information I'm closing the issue.

Feel free to comment if the problem is still there, possibly providing some extra information (e.g. the Firefox version).

**Closed by Faless** 2020-07-28 00:37 UTC
Labels: bug, platform:html5, topic:porting, topic:thirdparty
