### ISSUE TITLE
Viewports are layered on top of UI in 2.1

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7890] opened 2017-02-25 22:24 UTC
godot 2.1.2 stable official from website, linux kubuntu 16.10 x64

When using viewports THIS happens
![screenshot_20170226_001943](https://cloud.githubusercontent.com/assets/10696955/23335241/b6885c8a-fbb9-11e6-8f5f-7bf906e3daa1.png)

Project: https://github.com/godotengine/godot/files/448339/Viewport.Example.zip
(change root node to canvas layer)

Connected to #6356 somehow.

**Comment by bojidar-bg** [comment] 2017-02-26 15:24
Duplicate of #1840 probably, though the latter was fixed in 3.0..

**Comment by ArcFutahito** [comment] 2017-02-26 18:18
Now, what exactly you mean by "fixed"? Because sprite just doesn't appear with viewport for me in 3.0.
Two screenshots. Sprite not in viewport and sprite under viewport. 
![screenshot_20170226_201702](https://cloud.githubusercontent.com/assets/10696955/23342299/a1489946-fc60-11e6-8222-7bf40858d7f4.png)
![screenshot_20170226_201720](https://cloud.githubusercontent.com/assets/10696955/23342300/a2c9c79a-fc60-11e6-8bf2-f99d149c6f63.png)

**Comment by Zylann** [comment] 2017-02-26 20:23
that's the way it is in 2.1.2 too. You don't see what's inside a viewport node in the editor, but if you play the scene you can see it.

**Comment by ArcFutahito** [comment] 2017-02-28 21:00
That's kinda against WYSIWYG paradigm though. Viewports worked in 2.2

**Comment by Zylann** [comment] 2017-02-28 21:13
Not saying it's a feature though^^ I'm not sure wether it's normal behaviour or not

**Comment by ArcFutahito** [comment] 2017-02-28 21:16
2.1.2 official shows things inside viewport just fine by the way https://lut.im/70OdMZhMM3/E1ubXFheXilIv8Pb.png

**Comment by kubecz3k** [comment] 2018-04-10 17:26
I'm not sure what was on the screen above and how this should work in the end, but I can confirm the behavior is still the same in 3.0.2

**Comment by akien-mga** [comment] 2019-01-06 09:01
I can't reproduce that issue in 2.1.5 (no overlap with the editor UI after changing type to CanvasLayer):
![screenshot_20190106_095915](https://user-images.githubusercontent.com/4701338/50734110-c38d5a00-1199-11e9-85b4-c388b3241a69.png)

I don't see any UI overlap issue in the master branch either, so closing.

**Closed by akien-mga** 2019-01-06 09:01 UTC
Labels: bug, topic:editor, topic:rendering
