### ISSUE TITLE
connecting signal creates method outside the class.

### ISSUE THREAD

**Issue by Crare** [godotengine/godot#70258] opened 2022-12-18 14:32 UTC
### Godot version

v3.5.1.stable.mono.official [6fed1ffa3]

### System information

Windows 10, GLES3

### Issue description

Connecting signals adds method outside C# script's class. which won't work.

### Steps to reproduce

I tried to add UI node Button's Signal to control node that is above in the node hierarchy.
Double-clicked the pressed() signal in the Node list and selected the control node to attach it to.
control node has existing C# script in it. After clicking the connect button, it adds the method at the end of the script file outside of the method class.

Also sometimes double-clicking won't work when adding multiple signals consecutively from many buttons to the control node.

### Minimal reproduction project

1. add control node.
2. add button node as it's child.
3. create C# script on control node.
4. add signal connection from the button node to the control node.
5. control node's C# script now has new button methods, but they are outside the class.

**Comment by KoBeWi** [comment] 2022-12-18 16:42
Duplicate of #18721

**Closed by KoBeWi** 2022-12-18 16:42 UTC
