### ISSUE TITLE
Godot build error with c#

### ISSUE THREAD

**Issue by HHKSYT** [godotengine/godot#52769] opened 2021-09-17 07:17 UTC
### Godot version

v3.3.3.stable.mono.official [b973f997f]

### System information

Windows 10

### Issue description

I try to run a 2D game project with C# and it is showing this error

```Failed to build project solution```

How do I fix it please help me

### Steps to reproduce

in MS build it show this

 ```C:\Users\user\Desktop\godot projcet\first game\first game.csproj(0,0): The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettings' threw an exception.  ```

I have installed .NET 4.7.2 developer pack and in csproj file I wrote this 

```<TargetFramework>net4.7.2</TargetFramework>```

### Minimal reproduction project

[Firstgame.zip](https://github.com/godotengine/godot/files/7183519/Firstgame.zip)

**Comment by Calinou** [comment] 2021-09-17 07:20
Duplicate of https://github.com/godotengine/godot/issues/41734.

**Closed by Calinou** 2021-09-17 07:20 UTC
