### ISSUE TITLE
Can't use android godot even in English language due the window size (like #60728, but even in english it don't works)

### ISSUE THREAD

**Issue by JoluMorsanDev** [godotengine/godot#60743] opened 2022-05-04 03:30 UTC
### Godot version

3.5.beta5.official [815f7fe63]

### System information

moto e6 play, android 9, x32 gpu arch (I can't check the gpu, but I remember that)

### Issue description

When I open the godot app, (in both spanish and english), the ui doesn't fit in the screen, so I can't create nor open any project (neither in the assetstore).
In #60728, it says that the solution is turning the language using the device settings, but even doing that it doesn't fit.
![imagen_2022-05-03_222713569](https://user-images.githubusercontent.com/64111076/166619426-c8f16d5a-a935-4aec-93c8-cc16211f078a.png)

### Steps to reproduce

-Install any version of godot in android (found in the snapshots, betas and alphas)
-Open it
-Enjoy the issue :D

**Comment by Calinou** [comment] 2022-05-04 15:36
Duplicate of https://github.com/godotengine/godot/issues/60743. This is actually the same issue under the hood, but your device's screen resolution is too low for the editor scale that was automatically chosen.

**Closed by Calinou** 2022-05-04 15:36 UTC
Labels: bug, platform:android, topic:editor
