### ISSUE TITLE
Option button click mask is offsetted if you resize window and set change stretch mode on project settings

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot#57936] opened 2022-02-10 20:40 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

The option button click mask is not resized with the window, but the stretch mode shows the button on the correct place scalled. If you switch the stretch mode back to disabled on the project settings, you can see that the button click mask is not being resized.
![OptionButtonClickMask](https://user-images.githubusercontent.com/88800565/153492695-c6b64ff8-5d22-4224-b1ec-4774110657fb.gif)

### Steps to reproduce

1 - Make a new project, set in projects settings window stretch mode to anything than disabled.
2 - Add a option button and some items.
3 - Test scene, go in widowed mode, resize the window to a smaller size.
4 - Try to select the option button items, the button mask is not resized as the window is.

### Minimal reproduction project

[OptionButtonBrokenProject.zip](https://github.com/godotengine/godot/files/8044075/OptionButtonBrokenProject.zip)

**Comment by Calinou** [comment] 2022-02-10 21:11
Duplicate of https://github.com/godotengine/godot/issues/54030.

**Closed by Calinou** 2022-02-10 21:11 UTC
