### ISSUE TITLE
Error when compiling the file thirdparty\etc2comp\EtcImage.cpp

### ISSUE THREAD

**Issue by Mintormo** [godotengine/godot#33087] opened 2019-10-26 13:26 UTC
**Godot version:** 3.2 (commit a8e007f055c69483c77945739f2c3218de5e5c44)

**OS/device including version:** Windows 7 x64, compiler MinGW 6.3.0 (gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0)

**Issue description:** When compiling the file **thirdparty\etc2comp\EtcImage.cpp** with MinGW, an error occurs and the build process stops.

**Steps to reproduce:**
1. Execute command "scons -j 2 use_mingw=true bits=64" in console.

**Comment by akien-mga** [comment] 2019-10-26 13:36
What error?

**Comment by bruvzg** [comment] 2019-10-26 13:46
Probably duplicate of #20405, #12417 and #9258, make sure your MinGW installation use `posix threads` (check comments in #9258 and [compiling_for_windows.html#troubleshooting](https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_windows.html#troubleshooting)).

**Comment by Mintormo** [comment] 2019-10-26 13:50
There's a few mistakes. The output is poorly formatted, so I give you a link to it at github gist: https://gist.github.com/Mintormo/ad95478cfb38f2ce77ca94e5a94328b5#file-gistfile1-txt

**Comment by Mintormo** [comment] 2019-10-26 15:40
> 
> 
> Probably duplicate of #20405, #12417 and #9258, make sure your MinGW installation use `posix threads` (check comments in #9258 and [compiling_for_windows.html#troubleshooting](https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_windows.html#troubleshooting)).

Thank you! I downloaded the posix version of mingw and everything compiled. However, for some reason it takes a very long time to link.

**Closed** 2019-10-26 15:40 UTC

**Comment by bruvzg** [comment] 2019-10-26 15:52
> However, for some reason it takes a very long time to link.

Default MinGW linker is extremely slow indeed.

I'm currently using [this clang/lld toolchain](https://github.com/mstorsjo/llvm-mingw) to cross-build on macOS and it's much faster.(it has pre-build releases for Windows as well, but I do not know how well they work.)
