### ISSUE TITLE
Adding a CollisionShape2D causes the editor to crash

### ISSUE THREAD

**Issue by brettkromkamp** [godotengine/godot#76784] opened 2023-05-06 17:48 UTC
### Godot version

v4.0.3.rc1.official [2d74ee0e5]

### System information

Windows 11, Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### Issue description

Just adding a CollisionShape2D node to a completely new project causes the editor to crash/close. This does not happen with v4.0.2.

OS, CPU and GPU:

- Windows 11 Home, version	22H2, OS build 22621.1635, Windows Feature Experience Pack 1000.22641.1000.0
- Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
- NVIDIA GeForce RTX 2060, Driver version 531.68
- 15.84 GB RAM
- 1920x1080, 144Hz

### Steps to reproduce

1. Create a new project
2. Switch to 2D view
3. Add a CollisionShape2D node

Immediately after adding (or, at least, trying to add) a CollisionShape2D node, the editor crashes. 

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-05-06 18:55
Duplicate of #76543. Already fixed in #76546 (for the next version). Workaround in the meantime: https://github.com/godotengine/godot/issues/76543#issuecomment-1527667759.

**Closed by kleonc** 2023-05-06 18:55 UTC
