### ISSUE TITLE
Output tab showing above Animation tab

### ISSUE THREAD

**Issue by Muller-Castro** [godotengine/godot#32840] opened 2019-10-14 20:49 UTC
**Godot version:** 3.1.1.stable

**OS/device including version:** Windows 10

**Issue description:** If you select an AnimationPlayer node, switch scene, open Output tab and then go back to the first scene, the Output tab will appear above the Animation tab

**Steps to reproduce:**

![UIBug](https://user-images.githubusercontent.com/37383316/66781805-a44ef600-eeaa-11e9-8138-ee1e339fb0ec.gif)

**Minimal reproduction project:**

**Comment by codecustard** [comment] 2019-10-14 22:07
It appears to be fixed in the latest master branch.

**Comment by volzhs** [comment] 2019-10-15 00:16
can reproduce it 3.1.2-alpha 8f3fea2058

**Comment by volzhs** [comment] 2019-10-15 01:04
can't reproduce it with 3.2-alpha 74ab8be57a

**Comment by akien-mga** [comment] 2019-12-19 08:47
Closing as fixed in 3.2 then. If anyone can identify the commit that fixed it, and it's safe to backport, we can include it in a future 3.1.x release too.

**Closed by akien-mga** 2019-12-19 08:47 UTC
Labels: bug, topic:editor, usability
