### ISSUE TITLE
Folder duplicating in the FileSystem tab

### ISSUE THREAD

**Issue by jamesfoxbr** [godotengine/godot#77713] opened 2023-05-31 20:51 UTC
### Godot version

4.0.3 stable version on steam

### System information

Windows 10 64 bit

### Issue description

When I run a project a second duplicated folder I called "scripts" appear in the Godot FileSystem tab. When I check on windows file explorer there is just one folder. The diplicated folders in the Godot FileSystem show exact the same files inside.  It's noting serious but I'm reporting because is a bug

### Steps to reproduce

I just run the project to test pressing the "play" button and notice the second folder appear. If I close Godot and open again there is one folder but when press play the duplicated appear.  I just see this in my last project I'm not sure if happen when I open other projects

### Minimal reproduction project

[Tanks.zip](https://github.com/godotengine/godot/files/11618771/Tanks.zip)

**Comment by KoBeWi** [comment] 2023-05-31 22:13
Probably duplicate of #76021
Not sure why is it repeatable though.

**Comment by Calinou** [comment] 2023-06-09 18:54
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/76021.

**Closed by Calinou** 2023-06-09 18:54 UTC
