### ISSUE TITLE
Animated tres files are not paused when the tree is paused

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#44626] opened 2020-12-23 18:21 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Linux mint 19.1

**Issue description:**
Animated Textures (tres) do not pause when game is paused via get_tree().paused=true

Observe the gif below, when the first dialog appears (this is set to process so does not pause) the game pauses ok however teh green conveyor below which is an animated tres file in the tilemap does not. Now, wait for the next screen and when the second dialog appears you will notice the blue graphics (animated texture in a tilemap) are still spinning despite the game being paused

![Peek 2020-12-23 18-08_animtexbug](https://user-images.githubusercontent.com/12863685/103025794-74898c80-454a-11eb-8ec8-0459b55c9dcc.gif)

It is irrelevant whether the tres is part of a tilemap or a texture to a sprite, the same thing happens, i.e. animated tres are not pausing. Note, particles pause just fine so it is not linked to #41582 that I raised a while ago regarding particles/tres not stopping during debug. This is a more serious bug as it affects gameplay.

**Steps to reproduce:**
1. create an animated tres file
2. add it to a sprite
3. pause the game

**Comment by Calinou** [comment] 2021-01-02 23:17
Duplicate of https://github.com/godotengine/godot/issues/44625.

**Closed by Calinou** 2021-01-02 23:17 UTC

**Comment by Atermnus** [comment] 2022-01-25 21:07
Have found a quick fix for this.

var alltiles =tile_set.get_tiles_ids()
# grab tileset
for i in alltiles:
		tile_set.tile_get_texture(i).pause = val
#for each id make pause = to val, where val is the paused val

Do not know it's performance, works well on a tileset with around 200 tiles, but haven't tried it on a low-spec machine.

**Comment by Calinou** [comment] 2022-01-25 21:20
@Atermnus I recommend posting the workaround on https://github.com/godotengine/godot/issues/44625 too, as people may not stumble upon this particular issue from a web search (it's a duplicate of another issue).
