### ISSUE TITLE
Reimporting a 3D mesh (imported as single mesh) doesn't update it in opened scene, must close and reopen

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#14338] opened 2017-12-06 21:46 UTC
Godot 3.0 master
Windows 10 64 bits
nVidia geforce 940M

Similar to https://github.com/godotengine/godot/issues/10017 (if not the same?)
I have an opened scene which contains an instance of an imported OBJ scene. I modified the scene in Blender, exported it, but in Godot I don't see any difference. I have to close the scene and reopen it to see the difference.

**Comment by ScottMakesGames** [comment] 2017-12-07 08:54
Can confirm, I have experienced this for a couple of months at least

**Comment by bretzl** [comment] 2019-01-10 08:58
Can confirm that the bug exists in 3.1 (tracked since alpha 4):

Version:
Godot v3.1 beta 1

OS:
Windows 10 / Debian 9 
64 bits

Very inconvenient with my work flow...

**Comment by akien-mga** [comment] 2019-11-26 13:18
Is this still reproducible in the current master branch?

If so, could someone provide a reproduction project that allows testing it easily?

**Comment by vitorbalbio** [comment] 2020-01-01 23:24
Same here in 3.2 Beta 4 importing GLTF files made in Blender

**Comment by setzer22** [comment] 2020-05-19 11:15
@akien-mga  I can confirm the issue is still present in the latest godot 3.2 stable build. I'm uploading a very simple project where the issue can be reproduced.

The project has four important resources:
- cube.glb, a cube model
- sphere.glb, a sphere model
- mesh.glb, a copy of either mesh.glb  or cube.glb
- MeshInherited.tscn, an inherited version of the mesh.glb scene with no modifications, created by double-clicking mesh.glb in the FileSystem tab, selecting "New Inherited" and immediately saving.

**Steps to reproduce:**

1. Open the project in godot, and open MeshInherited.tscn. Ensure no other scenes are open.
2. Minimize godot and, using a file manager, delete `mesh.glb` and duplicate either `cube.glb` or `sphere.glb` to a new file. Rename the new copy as `mesh.glb`. 
3. Go back to godot. A reimport will be triggered, but the inherited scene will show the old mesh.
4. Open mesh.glb (double-click in the FileSystem tab, and choose "Open Anyway"). The new mesh will be shown.
5. Go back to the MeshInherited.tscn tab, the mesh is updated.

[MeshReimportIssue.zip](https://github.com/godotengine/godot/files/4649967/MeshReimportIssue.zip)

**Comment by Zylann** [comment] 2020-05-19 11:49
@setzer22 if you import the mesh as a scene, then you are not hitting the same exact issue. The problem I had was with an OBJ, which is imported as a mesh resource directly. That means the import process should normally go flawlessly, since there is no node hierarchy to magically replace.
Lately I did the same thing in 3.2, imported an OBJ, modified it in Blender but this time I saw the result update in Godot. So probably the original issue got fixed?

Meshes imported as scenes however, are a different story. They do contain mesh resources that must be updated, but should the hierarchy or object counts change, nodes don't update, which is what you are experiencing I believe.

**Comment by setzer22** [comment] 2020-05-19 12:03
I see now. Thanks for clarifying that! I will open a separate issue l.

**Comment by WickedInsignia** [comment] 2021-07-15 23:27
Can confirm still happening in 2021. Mesh will not update in an open scene in Godot 3.3.2. Using GLTF exports from Blender into Godot and although reimport is recognized, mesh won't update. Please note that materials are included in this particular export. Closing and reopening the scene resolves it.

**Comment by Zylann** [comment] 2021-07-16 00:09
> Using GLTF exports from Blender into Godot and although reimport is recognized, mesh won't update

Note that importing as mesh with OBJ is different than what GLTF import does. GLTF is imported as a scene, while OBJ is imported as a mesh resource. Maybe that's a different issue.

**Closed** 2023-01-23 14:36 UTC
Labels: bug, topic:editor, confirmed, topic:import, topic:3d
