### ISSUE TITLE
Godot 3.1 Change flags on an image texture

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#26721] opened 2019-03-06 18:21 UTC
**Godot version:**
Latest from source code (master branch)

**OS/device including version:**
ArchLinux

**Issue description:** Long message:
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7ff6ea36ce00] (??:0)
[2] Object::_change_notify(char const*) (/home/ggc/repos/godot/./core/object.h:567 (discriminator 2))
[3] StreamTexture::set_flags(unsigned int) (/home/ggc/repos/godot/scene/resources/texture.cpp:829)
[4] MethodBind1<unsigned int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[5] ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) (/home/ggc/repos/godot/core/class_db.cpp:1020)
[6] Object::set(StringName const&, Variant const&, bool*) (/home/ggc/repos/godot/core/object.cpp:422)
[7] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (/home/ggc/repos/godot/core/undo_redo.cpp:306 (discriminator 2))
[8] UndoRedo::redo() (/home/ggc/repos/godot/core/undo_redo.cpp:333)
[9] UndoRedo::commit_action() (/home/ggc/repos/godot/core/undo_redo.cpp:255)
[10] EditorInspector::_edit_set(String const&, Variant const&, bool, String const&) (/home/ggc/repos/godot/editor/editor_inspector.cpp:1996)
[11] EditorInspector::_property_changed(String const&, Variant const&, String const&, bool) (/home/ggc/repos/godot/editor/editor_inspector.cpp:2012)
[12] MethodBind4<String const&, Variant const&, String const&, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/./core/method_bind.gen.inc:2898 (discriminator 33))
[13] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/core/object.cpp:942 (discriminator 1))
[14] Object::emit_signal(StringName const&, Variant const**, int) (/home/ggc/repos/godot/core/object.cpp:1228 (discriminator 1))
[15] EditorProperty::emit_changed(StringName const&, Variant const&, StringName const&, bool) (/home/ggc/repos/godot/editor/editor_inspector.cpp:88 (discriminator 3))
[16] EditorPropertyFlags::_flag_toggled() (/home/ggc/repos/godot/editor/editor_properties.cpp:546 (discriminator 6))
[17] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/./core/method_bind.gen.inc:56 (discriminator 4))
[18] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/core/object.cpp:942 (discriminator 1))
[19] Object::emit_signal(StringName const&, Variant const**, int) (/home/ggc/repos/godot/core/object.cpp:1228 (discriminator 1))
[20] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/ggc/repos/godot/core/object.cpp:1284)
[21] BaseButton::_gui_input(Ref<InputEvent>) (/home/ggc/repos/godot/scene/gui/base_button.cpp:147 (discriminator 2))
[22] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[23] Object::call_multilevel(StringName const&, Variant const**, int) (/home/ggc/repos/godot/core/object.cpp:777 (discriminator 1))
[24] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/ggc/repos/godot/core/object.cpp:883)
[25] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/ggc/repos/godot/scene/main/viewport.cpp:1542 (discriminator 2))
[26] Viewport::_gui_input_event(Ref<InputEvent>) (/home/ggc/repos/godot/scene/main/viewport.cpp:1914 (discriminator 3))
[27] Viewport::input(Ref<InputEvent> const&) (/home/ggc/repos/godot/scene/main/viewport.cpp:2668 (discriminator 2))
[28] Viewport::_vp_input(Ref<InputEvent> const&) (/home/ggc/repos/godot/scene/main/viewport.cpp:1319)
[29] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/./core/method_bind.gen.inc:729 (discriminator 12))
[30] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/ggc/repos/godot/core/object.cpp:942 (discriminator 1))
[31] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/ggc/repos/godot/core/object.cpp:867)
[32] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/ggc/repos/godot/scene/main/scene_tree.cpp:262)
[33] SceneTree::input_event(Ref<InputEvent> const&) (/home/ggc/repos/godot/scene/main/scene_tree.cpp:418 (discriminator 6))
[34] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/ggc/repos/godot/main/input_default.cpp:414)
[35] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/ggc/repos/godot/main/input_default.cpp:260)
[36] InputDefault::flush_accumulated_events() (/home/ggc/repos/godot/main/input_default.cpp:677)
[37] OS_X11::process_xevents() (/home/ggc/repos/godot/platform/x11/os_x11.cpp:2462)
[38] OS_X11::run() (/home/ggc/repos/godot/platform/x11/os_x11.cpp:3004)
[39] /home/ggc/repos/godot/bin/godot.x11.tools.64(main+0xdc) [0x1165422] (/home/ggc/repos/godot/platform/x11/godot_x11.cpp:56)
[40] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7ff6ea359223] (??:0)
[41] /home/ggc/repos/godot/bin/godot.x11.tools.64(_start+0x2e) [0x116528e] (??:?)
-- END OF BACKTRACE --

**Steps to reproduce:**
Importe a DEA with an image, change flags inside image properties like mipmaps, filters, repeat, etc.

**Comment by volzhs** [comment] 2019-03-06 18:54
duplicate of #26640 ?

**Comment by akien-mga** [comment] 2019-03-06 18:56
>  Latest from source code (master branch)

What exact commit? This bug has been fixed a few hours ago.

**Comment by akien-mga** [comment] 2019-03-06 21:52
Assuming that it's indeed a duplicate of #26640.

**Closed by akien-mga** 2019-03-06 21:52 UTC
