### ISSUE TITLE
A class_name I deleted weeks ago showed up in autocomplete and received cutsom highlighting

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#83723] opened 2023-10-21 12:44 UTC
### Godot version

Godot v4.2.beta2 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.beta2 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/ba2a3222-2ff2-4d3f-bb2e-6a9723a46437)

I deleted this class weeks ago. The script named does no longer exist.

![image](https://github.com/godotengine/godot/assets/85438892/a44a8611-6067-4540-9573-e8eb509d6ba1)

Nothing at all shows up in my filesystem when I search this string.

### Steps to reproduce

No reproduction steps, but hopefully this description is enough.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment] 2023-10-22 02:18
* Related to / duplicate of #78642.

**Comment by HolonProduction** [comment] 2024-10-14 11:57
Given that #78642 was closed we might want to close this as well and only reopen if it actually happens.

**Closed** 2024-10-14 17:03 UTC
Labels: bug, topic:gdscript, topic:editor
