### ISSUE TITLE
Debugger displays non-null image loaded from file as <null>

### ISSUE THREAD

**Issue by aklapatch** [godotengine/godot#77593] opened 2023-05-28 22:13 UTC
### Godot version

4.0.3.stable

### System information

- OS: Windows 10
- Godot Version 4.0.3.stable
- Rendering Dirver: Vulkan
- Rendering Method: Forward+
- Graphics Card:  Intel(R) HD Graphics 620
- CPU: Intel Core i5-7200U

### Issue description

When loading an image from a file, the debugger incorrectly shows that the loaded image is `<null>`. The assert that catches a null value does not trip, nor does the print statement print `null`. It prints `<Image#-(long number)>` instead.

### Steps to reproduce

Put a test image (I used a jpg) in `user://` with the name `test-image.jpg`. The program will load it. The print statements and the assert will see/show the image value isn't `null`, but the debugger will show the image's value is `<null>`.
The debugger showing `img` is `null`:
![image](https://github.com/godotengine/godot/assets/33169247/d15eba69-c67e-4676-98e3-b98b3caa487e)
The output printing that `img` isn't null:
![image](https://github.com/godotengine/godot/assets/33169247/31afedab-bc4b-40d7-9419-065e208add62)

### Minimal reproduction project

[godot-bug-repro.zip](https://github.com/godotengine/godot/files/11585993/godot-bug-repro.zip)

**Comment by AThousandShips** [comment] 2023-05-28 22:30
* Duplicate of #36801

**Closed** 2023-05-29 09:01 UTC
