### ISSUE TITLE
Area2D does not register in 3.4 but works in 3.3.x

### ISSUE THREAD

**Issue by svendixon** [godotengine/godot#55492] opened 2021-11-30 19:48 UTC
### Godot version

Godot Engine v3.4.stable.official

### System information

Window 10 Pro, 64-bit, GeForce GTX 980 Ti, GLES3

### Issue description

Area2D does not see a body if it's removed, added, then repositioned. This worked in 3.3.x.

### Steps to reproduce

When I moved my project over to 3.4 I noticed this issue. It's common in my game (during a scene transition) to remove, add, and reposition my player in a new scene. I also have objects that are disabled using Area2Ds, that eventually re-enable. I created a simple test file to try and narrow down what is happening, however I'm confused as to what is going on here.

In the test file at the start, I remove, add, and reposition the player. The Area2D is also disabled then re-enabled. If you move the player using the arrow keys in the x axis, no on enter is triggered. However if you move in the y axis an on enter is triggered.

![area_2d_issue](https://user-images.githubusercontent.com/14341036/144109977-25475c40-c923-471b-9b3b-b0f9c38640c2.gif)

**If you open this test file in 3.3.4 for example everything seems to work fine.**

There are a couple of things that you can do make it work within this simple test case, however my game does all this in a more complex way. But it might also help to narrow down what is happening.

This causes it work...
1. Change _physics_process to a _process in game.gd.
2. OR Change _process to a _physics_process in area.gd

Is there some order happening here? Why should this matter? Why does moving in the y axis trigger the Area2D?

### Minimal reproduction project

[area_2d_issue.zip](https://github.com/godotengine/godot/files/7627999/area_2d_issue.zip)

**Comment by akien-mga** [comment] 2021-11-30 19:57
This seems fixed in the `3.x` branch as of 6cf77f80b53d215de4915719cc13ba700d44dd4f, it might have been fixed since 3.4-stable (I can reproduce it in 3.4). I'll let @pouleyKetchoupp confirm.

**Comment by pouleyKetchoupp** [comment] 2021-11-30 23:41
Confirmed fixed in 3.4.1 RC1, must have been fixed by #54925 or #55050.

**Closed by pouleyKetchoupp** 2021-11-30 23:41 UTC
Labels: bug, topic:physics, regression
