### ISSUE TITLE
Impossible to extend node parent functions (warning treated as error)

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#78911] opened 2023-07-01 14:46 UTC
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11

### Issue description

I can't extend parent node function like [docs explain](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance) using `super`.

### Steps to reproduce

I tried to extend `set_disable` method of a `Button`:

```
extends Button


func set_disabled(disabled_: bool):
	super(disabled_)
```

I get the error:

`The method "set_disabled" overrides a method from native class "BaseButton". This won't be called by the engine and may not work as expected. (Warning treated as error.)`

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-07-01 14:49
Overriding built-in methods that are not virtual is not supported

**Comment by AThousandShips** [comment] 2023-07-01 14:50
Duplicate of: #55024

**Closed by AThousandShips** 2023-07-01 14:50 UTC

**Comment by dalexeev** [comment] 2023-07-01 14:53
See comments in #55024 and #72608 for details.

**Comment by dalexeev** [comment] 2023-07-01 14:59
I think it's worth adding an explanation in the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance) that we can refer to since this question keeps coming up even after the warning in GDScript.

**Comment by AThousandShips** [comment] 2023-07-01 15:01
Best to open an issue over in [docs](https://github.com/godotengine/godot-docs)

**Comment by dalexeev** [comment] 2023-07-01 15:48
* See godotengine/godot-docs#7591.
