### ISSUE TITLE
Modules no longer show up in VisualStudio Projects

### ISSUE THREAD

**Issue by marstaik** [godotengine/godot#37037] opened 2020-03-14 01:47 UTC
**Godot version:**
master branch

**OS/device including version:**
Windows 10

**Issue description:**
VisualStudio projects generated with scons no longer show modules folder.
![2fp](https://user-images.githubusercontent.com/5601015/76672575-fc258200-655a-11ea-8fbf-c453fec5d18d.png)

**Steps to reproduce:**

1. Pull latest master
2. execute `scons vsproj=True`

**Comment by Chaosus** [comment] 2020-03-14 04:25
Duplicate of https://github.com/godotengine/godot/issues/36384

**Closed by Chaosus** 2020-03-14 04:25 UTC
