### ISSUE TITLE
classes overriden by `@export_group`

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#74277] opened 2023-03-03 07:56 UTC
### Godot version

1c1524a6

### System information

ArchLinux x11

### Issue description

Class goes out of scope when `export_group` has string with same name as class name.
![image](https://user-images.githubusercontent.com/70787919/222663073-8cb74090-6812-4771-a86b-3653b9ac1b27.png)

### Steps to reproduce

```gdscript
extends Node
class_name R
@export_group("R")
func _ready() -> void: R.new()
```

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10879413/bug.zip)

**Comment by dalexeev** [comment] 2023-03-03 08:45
Duplicate of #73843.

**Closed** 2023-03-03 09:20 UTC
Labels: archived
