### ISSUE TITLE
Pixel bleeding in Tilemaps with filtering enabled

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8084] opened 2017-03-20 04:28 UTC
Godot 2.1.2 x64 Linux kubuntu 16.10

When enabling filtering for tilesets, you can see bleeding from neighboring tiles on edges. For example
![sc-06_25_34-2003](https://cloud.githubusercontent.com/assets/10696955/24088682/1274593a-0d36-11e7-8db0-342149b005f8.png)
You can clearly see that pixels from white tile above are bleeding into the one displayed.

Steps to reproduce: 
1. Create a tilemap from tileset with filtering enabled.
2. Paint tiles that have differently colored neighbors to see the bleeding.

**Comment by bojidar-bg** [comment] 2017-03-20 11:12
Note this is NOT a duplicate of #1682.

@ArcFutahito BTW, this is [mentioned in the docs](http://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html#offset-and-scaling-artifacts), so it is a known issue..

**Comment by ArcFutahito** [comment] 2017-03-20 11:18
[Bad Zoom.tar.gz](https://github.com/godotengine/godot/files/854581/Bad.Zoom.tar.gz)
If only disabling filtering didn't make things worse

**Comment by ArcFutahito** [comment] 2017-03-20 11:22
Honestly, I am out of options. With filtering I have artifacts, without filtering sprites become complete shit during movement, zooming out makes art look like shit and blowing up pixel art to 1.5x size makes it look bad.
On top of all this games stutter despite >60 fps which looks more and more like some fuckup in the engine.

Jokes aside, I am really bummed about godot right now.

**Comment by Zylann** [comment] 2017-03-20 13:41
How about introducing a slight padding to the UVs? I used to do that in my previous projects.

Another way is to add a margin of 1 pixel to all your sprites (so instead of say 32x32 you have 34x34 per tile, where you fill the margins with one row/column of pixels from the opposite side) and select an inset of 32x32 of that. This hack can probably be automated, never tried it but just had the idea :)

**Comment by reduz** [comment] 2017-03-20 14:05
This is a hardware limitation of any engine that runs over a 3D API.

I was thinking of adding a hack in 3.0 to clamp the uvs to the region if
repeat is disabled, though (this is impossible to do in 2.1).

**Comment by Shockblast** [comment] 2017-03-20 15:54
sorry my english
you try to use texture "power of two"? example image file size: 8x8 16x16 32x32...
The engine has problems with this "rule" with 2.1
I do not know if 3.0 happens the same (unofficial godot compiles)

**Comment by ArcFutahito** [comment] 2017-03-20 22:17
@reduz Even without problems in filtering that leaves the issue of stuttering. https://www.youtube.com/watch?v=p4niEyvqLZo
It's not because of load, it's not because of heavy scene, it's not because of too many calls each frame, but it's there without doubt.

**Comment by reduz** [comment] 2017-03-20 22:23
At this point I don't think this is godot fault anymore. After VSync was
implemented it does no longer depend on Godot..

**Comment by ArcFutahito** [comment] 2017-03-20 22:34
Is it driver/hardware dependent? I have vsync turned off and tried limited/unlimited fps. Both produce this stuttering.

**Comment by reduz** [comment] 2017-03-20 22:42
vsync turned off OR limiting fps will always result in stuttering. Just
leave vsync on and do not limit fps.

**Comment by ArcFutahito** [comment] 2017-03-20 22:52
Same thing with vsync on.

**Comment by reduz** [comment] 2017-03-20 22:59
most likely driver issue then. If your stutter happens from time to time
(ie, a skip every a few seconds), then that's your OS/compositor fault

**Comment by ArcFutahito** [comment] 2017-03-20 23:12
Only in Godot though. Other games and OS itself play on smooth 60 fps

**Comment by reduz** [comment] 2017-03-20 23:19
it may be because godot uses all your CPU by default, does it happen if you
run your exported game with

-fdelay 1

?

**Comment by reduz** [comment] 2017-03-20 23:20
although vsync should take care of that so you don't use all your fpu.

Honestly Godot does nothing special on it, I suggest you pay attention in
your other games, as general when a lot of thing goes on on screen its
difficult to notice stuttering but it's still there

**Comment by ArcFutahito** [comment] 2017-03-20 23:21
On video I have system monitor to preempt this question. It's certainly not because of cpu load.

**Comment by reduz** [comment] 2017-03-20 23:26
beats me then, talk to whoever supplies video driver for your compositor
and ask them to take a look. Godot does nothing out of the ordinary so it's
definitely not at fault for the stutter.

Most likely it's triggering a bug in your specific setup.

**Comment by ArcFutahito** [comment] 2017-03-20 23:35
I would've thought that if there was unusual behavior in other games or applications but a bug in setup that's popping up only in godot? I'm not sure.

**Comment by Zylann** [comment] 2017-03-20 23:38
If you believe the problem comes from Godot, you can eventually install profiling samplers yourself everywhere in the main loop to find out where stutter happens on the lower level, if you find how to do it with minimal overhead.

**Comment by reduz** [comment] 2017-03-20 23:44
Yes, defininitely. If it only happens to few people in specific
configurations, it is most likely unrelated to Godot.
I noticed this behavior with Noveau drivers, and they went away when
installing the binary Nvidia driver, and in far most cases users report
this when running under Linux compositors.

**Comment by ArcFutahito** [comment] 2017-03-20 23:45
I'm on radeon driver though.

**Comment by reduz** [comment] 2017-03-20 23:46
Godot just issues OpenGL calls then calls flip, that's it. There's nothing
strange or complex that might be failing, and it's the same code that runs
in all platforms. There is no code that might be producing this behavior
because there is simply no OS specific graphics code at all in Godot.

**Comment by ArcFutahito** [comment] 2017-03-20 23:48
Hmmm... I'll try to test it on other setups, maybe setup windows to see if it's linux being awful again.

**Comment by ArcFutahito** [comment] 2017-03-21 01:00
Killed off Kwin and ran the game without it, it seems you were right, compositor did slow it down quite a bit.

**Comment by ArcFutahito** [comment] 2017-03-22 03:17
@reduz I think zooming is contributing to this choppiness too. Ran platformer demo with .7 zoom in camera and it's all messed up

**Comment by yuyoDev** [comment] 2017-10-29 02:48
@ghost How did you kill kwin and how did you run the game without kwin?
I have a R9 270X and i have some jittering in motion godot-example 
radeon drivers

**Comment by vnen** [comment] 2017-11-22 02:48
This was probably solved by the `Clip Uv` property of the TIleMap. In any case, the author deleted the account, so if anyone has this problem they can open a new issue.

**Closed by vnen** 2017-11-22 02:48 UTC
Labels: discussion, topic:rendering

**Comment by ZingBlue** [comment] 2019-10-16 19:43
I'm having issues with this, especially when the camera moves.

**Comment by clayjohn** [comment] 2019-10-16 19:47
The solutions above are still valid. You need to have a margin between all sprites in your Sprite sheet. This is a limitation of all 3D rendering APIs.

**Comment by ZingBlue** [comment] 2019-10-16 20:53
> 
> 
> The solutions above are still valid. You need to have a margin between all sprites in your Sprite sheet. This is a limitation of all 3D rendering APIs.

I am running a 2D game and I have 3D disabled in the project settings.(OPEN GLES3)

**Comment by clayjohn** [comment] 2019-10-16 21:03
Even in 2D your game still uses OpenGL. OpenGL is a 3D graphics API. It doesn't matter if your game is 2D or 3D.

**Comment by ZingBlue** [comment] 2019-10-16 21:06
![image](https://user-images.githubusercontent.com/23709367/66958874-0845fb80-f01e-11e9-9bb3-a666fb56ad32.png)
Is this the same issue as everyone else is having? I am trying the solutions and they don't seem to fix my issue.

**Comment by ZingBlue** [comment] 2019-10-16 21:49
I temporary solved it by turning off the filter.
