### ISSUE TITLE
kinematic body child not syncing to physics

### ISSUE THREAD

**Issue by PracticalNPC** [godotengine/godot#50407] opened 2021-07-13 01:22 UTC
### Godot version

3.3.2stable

### System information

windows 10, GLES3, GeForce GTX 1070

### Issue description

When stacking two kinematicbody2Ds that use move_and_slide_with_snap() on a vertical moving platform you get some unintended results where the bottom kinematic body will likely fall through. A similar issue is mentioned [here ](https://github.com/godotengine/godot/issues/49497) by @azagaya (another [example](https://imgur.com/a/hQmDqBP))

To make **KinematicBodyB** collide with **KinematicBodyA** without facing these repercussions, I've removed the mask of **KinematicBodyA** from colliding with **KinematicBodyB** and created a **KinematicBodyA_child** that will collide with **KinematicBodyB**. 

In other words, the **KinematicBodyA** collides with the platform but does not collide with **KinematicBodyB**. the **KinematicBodyA_child** does not collide with the platform but collides with **KinematicBodyB**. I hope this makes sense. 

I then locked the position of this child to the origin of **KinematicBodyA** so that it would simply follow the movement path of its parent. 

Unfortunately, this isn't always the case. there are moments throughout some tests that show **KinematicBodyA_child** is not always staying on its parent despite all of my efforts to keep its local position at Vector2.ZERO. As a result, **KinematicBodyB** will float above or "clip" through **KinematicBodyA**

![bug2](https://user-images.githubusercontent.com/73863114/125373609-79315900-e353-11eb-8b4b-7a9df454f590.gif)

### Steps to reproduce

1. create a moving kinematic body platform and sync to physics (without move and slide) and set the collision layer and mask to both 1 and 3 and set_sync_to_physics(true)
2. create a second kinematic body that uses move_and_slide_with_snap(), set its the collision layer and mask to 3
3. create a third kinematic body and set  the collision layer and mask to 2, make this a child of the second kinematic body and set_sync_to_physics(true)
4. create a 4th kinematic body that uses move_and_slide_with_snap() and set collision layer and mask to both 1 and 2

### Minimal reproduction project

[moving platforms and stacked kinematics bug.zip](https://github.com/godotengine/godot/files/6805238/moving.platforms.and.stacked.kinematics.bug.zip)

**Comment by pouleyKetchoupp** [comment] 2021-10-01 17:52
Closing as duplicate of https://github.com/godotengine/godot/issues/49497, but I've added a note there to check this use case for test.

**Closed by pouleyKetchoupp** 2021-10-01 17:52 UTC
Labels: bug, topic:physics, topic:2d
