### ISSUE TITLE
Create New Node dialogue no longer shows node descriptions

### ISSUE THREAD

**Issue by YannBurrett** [godotengine/godot#26081] opened 2019-02-20 09:55 UTC
**Godot version:**
3.1 Beta 5

**OS/device including version:**
Windows 10 64

**Issue description:**
When adding a new node, the node's description is no longer visible.

**Steps to reproduce:**
Open the Create a New Node dialogue
Select a node

![image](https://user-images.githubusercontent.com/37750928/53082831-9ef50380-34f5-11e9-9ba8-866f70b5f842.png)

**Comment by akien-mga** [comment] 2019-02-20 10:01
Duplicate of #25820, it's been fixed since then :)

**Closed by akien-mga** 2019-02-20 10:01 UTC
