### ISSUE TITLE
"Compile Error: Identifier not found" when using AutoLoad singletons in tool scripts

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#9810] opened 2017-07-24 12:17 UTC
**Operating system or device - Godot version:** v3.0-alpha

**Issue description:**
Using an AutoLoad singleton in a `tool` script causes a Compile Error when the script is ran in the editor:
```
 res://objects/random_tile_map/random_tile_map.gd:22 - Compile Error: Identifier not found: Logger
```
Expected behavior: load singletons in `tool` mode, or at least pre-set them to something like `null` so that you can test with `get_tree().is_editor_hint()` and call functions on them only when available.

**Steps to reproduce:**
1. Add an AutoLoad singleton called `Test` with a single function `test()`
2. Add a node with this script:
```
tool
extends Node

func _ready():
  if !get_tree().is_editor_hint(): Test.test()
```
3. Save, or reload the project if needed

**Comment by Hinsbart** [comment] 2017-08-01 19:01
Duplicate of #6886. Although that one talks about export vars not working, it's the same problem in the end.

**Closed** 2017-08-01 20:13 UTC
Labels: bug, topic:editor
