### ISSUE TITLE
Bad display when scrolling "About Godot" popup

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55153] opened 2021-11-20 09:01 UTC
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

Godot logo is partially hidden on scroll down. Both "Authors" and "Donators" tabs are affected.

![image](https://user-images.githubusercontent.com/2736557/142720628-0a9f3748-67fb-445d-982c-6f66121889dd.png)

![image](https://user-images.githubusercontent.com/2736557/142720641-4e3efbda-5430-4c41-8921-2860638b10a1.png)

The bug was present on `dev.20210727_win64` build. Godot 3.4 is not affected.

### Steps to reproduce

1. Open Godot
2. Help menu
3. About Godot
4. Scroll down a bit

### Minimal reproduction project

Non applicable

**Comment by akien-mga** [comment] 2021-11-20 09:24
Duplicate of #36164

**Closed by akien-mga** 2021-11-20 09:24 UTC
