### ISSUE TITLE
Control Anchors Bug

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3604] opened 2016-02-06 03:15 UTC
When using a Control node if you attempt to use the Ratio anchor mode, then attempt to modify the Margin associated with the Ratio anchor you will find that the Margin will not accept floating point values, instead it will only accept whole integers, however, this results in only being able to specify the ratio in "whole screen units", which obviously is not nearly as useful as being able to specify 0.2 of the width, etc.

![godotcontrolanchorbug](https://cloud.githubusercontent.com/assets/17059062/12864350/f34e15e0-cc55-11e5-8661-69c1ccde2ba6.png)

**Comment by 29jm** [comment] 2016-02-06 10:35
I think this is a duplicate of #2048

**Comment by akien-mga** [comment] 2016-02-06 10:54
Indeed.

**Closed by akien-mga** 2016-02-06 10:54 UTC
Labels: bug, topic:editor, usability
