### ISSUE TITLE
GLES2 Directional shadow framebuffer status invalid error and shadow bug

### ISSUE THREAD

**Issue by hyperJJmaster** [godotengine/godot#28894] opened 2019-05-15 01:29 UTC
**Godot version:**
Version 3.1.1

**OS/device including version:**
Nvidia Geforce 6150SE nforce 430

Windows 7 x64

**Issue description:**
Console Error
![image](https://user-images.githubusercontent.com/24927155/57742363-7ad53880-7686-11e9-8449-c08c491b4519.png)

Shadows ON 
![image](https://user-images.githubusercontent.com/24927155/57742433-bc65e380-7686-11e9-8070-e205d9a3b4fe.png)

Shadow OFF
![image](https://user-images.githubusercontent.com/24927155/57742473-de5f6600-7686-11e9-89a2-79f4debfc224.png)

**Steps to reproduce:**
open godot. boom error

for shadow bug. Shadow option is enabled

**Comment by volzhs** [comment] 2019-05-15 01:50
seems duplicate of #26570

**Closed** 2019-08-11 17:14 UTC
Labels: bug, topic:rendering
