### ISSUE TITLE
Horrible CanvasGroup performance on Android devices

### ISSUE THREAD

**Issue by PickleJesus123** [godotengine/godot#83127] opened 2023-10-10 22:25 UTC
### Godot version

4.1.1

### System information

Google Pixel 6a - Android 13

### Issue description

I am porting my Unity games to Godot. I was using CanvasGroups to group together my UI TextureRects and 'fade' them in unison during UI animations. I have discovered that if I have too many of these CanvasGroups visible at once (probably 20+), the FPS drops dramatically and the game almost crashes. When I replace all the CanvasGroups with simple Control nodes, the FPS immediately goes back up. It doesn't seem to be an issue on my Windows builds, and it definitely doesn't have anything to do with the large number of TextureRects being drawn - it just seems to be affected by the CanvasGroups

I am fine with foregoing CanvasGroups for my mobile projects, but I worry that other new users may "intuitively" try the same thing as me and mistakenly doubt Godot's capabilities.

### Steps to reproduce

Instantiate a moderate number of prefabs with this hierarchy:
- Control node -> Canvas Group -> 3 TextureRects

Run on Android. Once you get 20+ of these instantiated, it lags like crazy. If you remove the CanvasGroup from the middle of the heirarchy, it goes back to being lightning quick.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2023-10-10 22:48
- Related to https://github.com/godotengine/godot/issues/79439.

This was also reported in https://github.com/godotengine/godot/issues/74540#issuecomment-1460039523.

Every CanvasGroup needs to copy a region of the screen every frame, so it's going to be slow on fillrate-constrained devices like mobile GPUs.

**Comment by PickleJesus123** [comment] 2023-10-10 22:54
> * Related to [CanvasItem clip children is extremely slow #79439](https://github.com/godotengine/godot/issues/79439).
> 
> This was also reported in [#74540 (comment)](https://github.com/godotengine/godot/issues/74540#issuecomment-1460039523).
> 
> Every CanvasGroup needs to copy a region of the screen every frame, so it's going to be slow on fillrate-constrained devices like mobile GPUs.
> 
> As a workaround, use the `viewport` stretch mode and a low base resolution (like 540×960). This will decrease the fillrate requirements a lot.

Perhaps there should be a 'warning label' in the Godot documentation about using CanvasGroups on mobile projects

**Comment by clayjohn** [comment] 2023-10-10 23:55
This is a duplicate of https://github.com/godotengine/godot/issues/79439

I'm going to close this issue so we can track the problem in one place

**Closed by clayjohn** 2023-10-10 23:55 UTC
Labels: discussion, topic:rendering, topic:2d
