### ISSUE TITLE
Local variables assigned with super() cause autocomplete to crash the editor

### ISSUE THREAD

**Issue by axo-lotl** [godotengine/godot#58943] opened 2022-03-09 19:21 UTC
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

If I create a new local variable by a statement such as `var local_variable = super()` then writing `local_variable.` causes the autocomplete dialog to stall, which causes the Godot editor to crash.

To illustrate, I have a minimal project of two files:

BaseItemFactory.gd:
```
extends Node
class_name BaseItemFactory

func make_item():
	return 0
```

DerivedItemFactory.gd
```
extends BaseItemFactory
class_name DerivedItemFactory

func make_item():
	var item = super() + 5
	# item.     CRASHES AUTOCOMPLETE
	return item
```

Typing `item.` on the line where the comment is attempts to open the property autocomplete dialog and crashes the program. 

I've tested a few slightly different cases, and it seems to be an issue related to `super()`.

The crash persists even if any of these changes are made:
1. `super()` is replaced with `super().make_item()`
2. type hints are added to the function `make_item` or the variable `item`
3. the body of `make_item` in `BaseItemFactory` changes (even a body with just `pass` will still trigger the crash)
4. the number of arguments to `make_item` changes
5. if the local variable `item` is assigned not to `super()` alone but to an expression involving `super()` (like `super() + 5` or something)
6. if `BaseItemFactory` instead extends from `Resource`
7. if no local variable is assigned and autocomplete is attempted after on `super()`, e.g.
   ```
    extends BaseItemFactory
    class_name DerivedItemFactory
    
    func _make_item():
	    return super()  # replacing with return super().a and program crashes
    ```

The crash doesn't occur with the following change:
1. `DerivedItemFactory` calls the base class's `make_item` from a differently named function, e.g. 
  ```
  extends BaseItemFactory
  class_name DerivedItemFactory
  
  func _make_item():
	  var item = super.make_item()
	  # item.     DOESN'T CRASH AUTOCOMPLETE
	  return item
  ```

### Steps to reproduce

1. Create a new class, A with a function. (Whether it has arguments, has type hints, or actually returns something doesn't seem to matter.)
2. Create a new class, B, extending A.
3. In B, create a function that overrides a function in A. In that function, create a local variable and assign it to any expression that includes super().
4. Trigger the local variable's property autocomplete. The editor crashes.

### Minimal reproduction project

[Bug_Property_Assignment_Setter_Use.zip](https://github.com/godotengine/godot/files/8217510/Bug_Property_Assignment_Setter_Use.zip)

**Comment by Zoomulator** [comment] 2022-04-12 20:50
I've encountered the same crash.

The suggested workaround doesn't work for me though.
I have to comment out the line with `super()` before I edit the function that uses it lest it crashes.

There's also no error output whatsoever, even with a target=debug build running with a console.

**Comment by coppolaemilio** [comment] 2023-02-23 23:27
@axo-lotl Can you check if this is fixed in the latest version?

**Comment by vnen** [comment] 2023-02-24 13:41
I cannot reproduce this, it might have been fixed with the many changes since the report.

**Closed** 2023-02-24 14:07 UTC
Labels: bug, topic:gdscript, crash
