### ISSUE TITLE
Run multiple instances for the purpose of quickly testing networked applications

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#20329] opened 2018-07-21 12:58 UTC
At the moment when developing a networked application that you want to test you have to make your changes, export, and then open it twice (or once in the editor, once from the export)

Being able to open two instances directly from the editor without having to export would be a productivity boost for anyone working on networked applications.

**Comment by Zylann** [comment] 2018-07-21 14:22
I think there was an issue about that already.
For now I do this by running 1 editor and X command line debuggers.

**Comment by bojidar-bg** [comment] 2018-07-21 14:38
Duplicate of #7008

**Closed by bojidar-bg** 2018-07-21 14:38 UTC
