### ISSUE TITLE
[WebGL2] Large delay when creating first MeshInstance

### ISSUE THREAD

**Issue by literalcitrus** [godotengine/godot#16050] opened 2018-01-25 00:58 UTC
**Godot version:**
3.0 RC3

**OS/device including version:**
Windows 10
Intel 15-7500 (Intel HD Graphics 630)
Firefox Quantum/Chrome

**Issue description:**
There seems to be a large delay when the first MeshInstance is added to the game, whether that be loaded with the original scene (in which case the game will just be a black screen before the scene appears) or added to the scene via a script (in which case the game will hang). This delay is slightly noticeable in the editor or desktop exports, but is much longer in HTML5 exports (around 10 seconds). The delay can sometimes be extensive enough to cause a WebGL context lost error. Any subsequent MeshInstances do not have this delay.

**Steps to reproduce:**
Create project and add a MeshInstance with an attached Mesh. Either place it in the main scene or instance it via code in some way. Delay should occur between when the MeshInstance is added to the scene tree and when it first appears on screen.

**Minimal reproduction project:**
[html5test.zip](https://github.com/godotengine/godot/files/1662191/html5test.zip)

**Comment by vnen** [comment] 2018-01-25 01:45
For what I can tell this is an issue with ANGLE and its D3D11 backend (I'm struggling with UWP because of this). With Firefox and ANGLE disabled, it works much better.

**Comment by literalcitrus** [comment] 2018-01-25 02:29
When I disable angle I get "WebGL2 not available" on Chrome, and an immediate WebGL context lost error on Firefox. Same results on another PC with an i7 3770 + GTX970.

**Comment by vnen** [comment] 2018-01-25 02:49
I believe Chrome has no native option if you disable ANGLE, other than the SwiftShader which is a CPU-bound implementation, so it won't really work (major performance caveat is set to true). For Firefox I'm a bit surprised, but I haven't tested it thoroughly.

**Comment by akien-mga** [comment] 2019-01-20 11:05
Is this still reproducible with the GLES2 / WebGL 1 renderer in the current master branch?

**Comment by clayjohn** [comment] 2019-11-30 16:43
Hasn't been reproduced, so closing

**Closed by clayjohn** 2019-11-30 16:43 UTC
Labels: bug, platform:html5, topic:rendering
