### ISSUE TITLE
The editor freeze while using Small Deploy with Network FS (and with huge amount of assets or nodes)

### ISSUE THREAD

**Issue by s0ra** [godotengine/godot#17465] opened 2018-03-12 03:40 UTC
**Godot version:**
v3.0.2 stable-win64

**OS/device including version:**
Windows 7 64-bit

**Issue description:**
possible related issue #14590 (closed)
The editor freezes when debugging on an Android device with small deploy. The game doesn't crash but the editor freeze. I imported many images to the project and enabled small deploy with network fs. Clean new project (after the issue appears) also freezes the editor with similar error messages as the project I was working.  As following:
```
ERROR: RichTextLabel::_process_line: MS: get_data - 114844002
Index line=0 out of size (l.offset_caches.size()=0)
MS: open_file - 114845583
   At: OPEN: res://Scenes/TileSet/TouchScreenButton.tscn
scene\gui\rich_text_label.cpp:117
MS: open_file_end - 114849116
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114852836
   At: scene\gui\rich_text_label.cpp:117
GET BLOCK - offset: 0, blocklen: 3000000
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
MS: get_data - 114868689
ERROR: RichTextLabel::_process_line: CLOSED
Index line=0 out of size (l.offset_caches.size()=0)
MS: get_data - 114872309
   At: MS: open_file - 114873126
scene\gui\rich_text_label.cpp:117
OPEN: res://Scenes/TileSet/TouchScreenButton.tscn.remap
ERROR: RichTextLabel::_process_line: MS: open_file_end - 114876901
Index line=0 out of size (l.offset_caches.size()=0)
MS: get_data - 114880190
   At: scene\gui\rich_text_label.cpp:117
MS: open_file - 114881684
ERROR: RichTextLabel::_process_line: OPEN: res://Scenes/TileSet/TouchScreenButt
on.tscn
MS: open_file_end - 114885682
Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: MS: get_data - 114889709
Index line=0 out of size (l.offset_caches.size()=0)
GET BLOCK - offset: 0, blocklen: 3000000
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: MS: get_data - 114900550
Index line=0 out of size (l.offset_caches.size()=0)
CLOSED
   At: MS: get_data - 114903427
scene\gui\rich_text_label.cpp:117
MS: open_file - 114904143
OPEN: res://Scenes/TileSet/TouchScreenButton.tscn.remap
ERROR: RichTextLabel::_process_line: MS: open_file_end - 114908065
Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:117
MS: get_data - 114911763
ERROR: RichTextLabel::_process_line: MS: open_file - 114913261
Index line=0 out of size (l.offset_caches.size()=0)
OPEN: res://Scenes/TileSet/TouchScreenButton.tscn
   At: scene\gui\rich_text_label.cpp:117
MS: open_file_end - 114917546
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114921119
   At: scene\gui\rich_text_label.cpp:117
GET BLOCK - offset: 0, blocklen: 3000000
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114931527
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
CLOSED
ERROR: RichTextLabel::_process_line: MS: get_data - 114938252
Index line=0 out of size (l.offset_caches.size()=0)
MS: open_file - 114939130
   At: OPEN: res://Scenes/TileSet/TouchScreenButton.tscn.remap
scene\gui\rich_text_label.cpp:117
MS: open_file_end - 114943011
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114949500
   At: scene\gui\rich_text_label.cpp:117
MS: open_file - 114951309
ERROR: RichTextLabel::_process_line: OPEN: res://Scenes/TileSet/TouchScreenButt
on.tscn
Index line=0 out of size (l.offset_caches.size()=0)
MS: open_file_end - 114955917
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: MS: get_data - 114959302
Index line=0 out of size (l.offset_caches.size()=0)
GET BLOCK - offset: 0, blocklen: 3000000
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114970404
   At: scene\gui\rich_text_label.cpp:117
CLOSED
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114974694
   At: MS: open_file - 114976284
scene\gui\rich_text_label.cpp:117
OPEN: res://Scenes/TileSet/TouchScreenButton.tscn.remap
ERROR: RichTextLabel::_process_line: MS: open_file_end - 114979984
Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:117
MS: get_data - 114984619
ERROR: RichTextLabel::_process_line: MS: open_file - 114986506
Index line=0 out of size (l.offset_caches.size()=0)
OPEN: res://Scenes/TileSet/TouchScreenButton.tscn
   At: scene\gui\rich_text_label.cpp:117
MS: open_file_end - 114990422
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.
size()=0)
MS: get_data - 114994022
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: GET BLOCK - offset: 0, blocklen: 3000000
Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:117
ERROR: RichTextLabel::_process_line: MS: get_data - 11
```

**Steps to reproduce:**
1. Import many image assets. (Don't stop the freezing after deleting most of the assets)
2. Create about 16 * 16 Sprites and TouchScreenButtons with ( .duplicate(DUPLICATE_USE_INSTANCING))
2. Enable remote debugging and small deploy with network fs. (Increase the fs page size to 3000000 only makes the editor working once more)
3. Debug the application on an Android device via USB multiple times.

**Minimal reproduction project:**
Project with this tileset's many tiles:
 https://github.com/crawl/tiles

**Comment by akien-mga** [comment] 2019-12-14 00:01
Seems like a duplicate of #17815.

**Closed by akien-mga** 2019-12-14 00:01 UTC
Labels: bug, platform:windows, topic:editor
