### ISSUE TITLE
TextureButton doesn't show Pressed image when clicked in V3.4 like it did in V3.3 stable

### ISSUE THREAD

**Issue by furroy** [godotengine/godot#55146] opened 2021-11-20 02:10 UTC
### Godot version

3.4 stable

### System information

Win10, 3080

### Issue description

When a normal (toggle mode is false) TextureButton is clicked, the Pressed image should show as long as the mouse is still over the button and left mouse is held down.  

This last worked in V3.3 stable

### Steps to reproduce

Make TextureButton in test scene
Ensure toggle mode is false
Add textures for Normal, Pressed, Hover, Focus
Run scene
Click and hold down button, it always shows Focus and never Pressed

### Minimal reproduction project

[TextureButton.zip](https://github.com/godotengine/godot/files/7573742/TextureButton.zip)

**Comment by kleonc** [comment] 2021-11-20 03:00
Can't reproduce (`3.4.stable`):
![XcBfPj2NGs](https://user-images.githubusercontent.com/9283098/142712226-c3a17d42-d00c-49e9-9e6f-ae76535729a7.gif)
![VyAN7PmSOT](https://user-images.githubusercontent.com/9283098/142712255-642886ac-ee19-459b-925a-0d5f30985241.png)

**Comment by furroy** [comment] 2021-11-20 03:10
You didn't assign the Focused image.

**Comment by kleonc** [comment] 2021-11-20 04:54
> You didn't assign the Focused image.

Right, didn't read careful enough. In fact, I didn't assign a single texture, just run the minimal reproduction project.

So you're right. It's indeed reproducible without a problem. But you're not right about it working differently in `3.3`, it works the same way in there. It seems it behaves like that even in `3.0`. And indeed, the relevant part of the source code hasn't changed throughout the versions: if focused, `focused` texture is being drawn last, despite of what texture was drawn previously.

<details>
  <summary>Relevant source code (click to expand)</summary>

* `3.0`:
https://github.com/godotengine/godot/blob/362774c6176596f87506e3d330dd1d12b0b75e19/scene/gui/texture_button.cpp#L168-L177
* `3.3`:
https://github.com/godotengine/godot/blob/056a927f62cbc8fce066cf81a20d048865fcdfe1/scene/gui/texture_button.cpp#L218-L229
* `3.4`:
https://github.com/godotengine/godot/blob/f737ed4da03af2afb6dd9725b43182ba22aef7d4/scene/gui/texture_button.cpp#L227-L238

---

</details>

So to make it clear: when you're pressing the button `pressed` texture is being drawn but `focused` texture is being drawn on top of it.
I'm guessing `focused` texture is assumed to be some type of an overlay (for example just a border, with transparent middle part). In such a case it would work as expected.

Your example with "just a border" focused texture:
![button_stone_focus2](https://user-images.githubusercontent.com/9283098/142714784-d3afc4ee-b115-4be4-8799-f3834dd09a67.png)
![Godot_v3 3-stable_win64_NPWHYtuK3Y](https://user-images.githubusercontent.com/9283098/142714804-370cf5e8-e5d9-4ced-b8bb-b4127f2d5596.png)
![59JPA3R1o2](https://user-images.githubusercontent.com/9283098/142714822-ddcdb4c0-daab-4898-ba76-223fd38dc5be.gif)

**Comment by furroy** [comment] 2021-11-20 14:18
I dunno, I gave out a demo of my game built with Godot_v3.3-stable_win64.exe and it worked before.

**Comment by Calinou** [comment] 2021-11-20 16:10
The Focused texture is meant to be an *overlay* over existing images. This is expected behavior, closing.

**Closed** 2021-11-20 16:11 UTC
Labels: bug, regression, topic:gui

**Comment by kleonc** [comment] 2021-11-20 16:30
@Calinou I don't see anything about it in the `TextureButton`'s docs, it should probably be mentioned in there.

**Comment by neepsnikeep** [comment] 2024-11-23 05:07
Still nothing in the docs, please give some info on this there. Took me way too long to find this issue in order to find out what's going on.

**Comment by Calinou** [comment] 2024-11-23 17:32
> Still nothing in the docs, please give some info on this there. Took me way too long to find this issue in order to find out what's going on.

This is already documented in the class reference: https://github.com/godotengine/godot/pull/55165

I've opened a PR to document this in the manual, but I couldn't find a great location for the added note: https://github.com/godotengine/godot-docs/pull/10313
