### ISSUE TITLE
[iOS]Can't record and play audio

### ISSUE THREAD

**Issue by gnefnap** [godotengine/godot#39292] opened 2020-06-04 16:32 UTC
**Godot version:**
3.2.1.stable.official (Steam)

**OS/device including version:**
iPhone 6, iOS 12.4.6

**Issue description:**

I'm making a project that can both record and play sounds.

What happened is, it won't play sound with Audio Input ON which can be set in Project Settings.
If I turn Audio Input OFF, it can play sound but unable to record, and iOS didn't ask for mic usage permission.

**Steps to reproduce:**
1. Start the newly built app on iOS, with Audio Input ON.
2. iOS asks for permission for mic usage.
3. Tap "Allow".
4. Record sound. (not sure whether or not really recorded)
5. Try to play the recorded sound - no sound can be heard.
6. Try to play another in-app sound - no sound can be heard.
7. Turn OFF Audio Input in Project Settings and restart.
8. Re-build for iOS and launch the app.
9. iOS not asking for mic permission.
10. Try to record - not working.
11. Try to play another in-app sound - in-app sound plays.

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/3.2-57baf0a/audio/mic_record

**Comment by Calinou** [comment] 2020-06-05 12:00
Duplicate of #33885.

**Closed by Calinou** 2020-06-05 12:00 UTC

**Comment by audiosdroid** [comment] 2022-06-07 11:49
I developed an iOS Audio Godot plugin named AudiosPlugin that solves this issue. Please see the GitHub page:
https://github.com/audiosdroid/Godot-iOS-Audio-Plugin
