### ISSUE TITLE
Parallax2D (and ParallaxLayer) applies repeat to children nodes before their rotation

### ISSUE THREAD

**Issue by squirrel-bat** [godotengine/godot#95574] opened 2024-08-15 17:10 UTC
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Pop!_OS 22.04 LTS - Wayland - GLES3 (Compatibility) - AMD Radeon Graphics (radeonsi, raphael_mendocino, LLVM 15.0.7, DRM 3.57, 6.9.3-76060903-generic) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

With the introduction of Parallax2D nodes, repeated children nodes will be placed in respect to their own rotation.
In the screenshot below, the sprite seen on the right is the repeat of the Sprite2D on the left side, with it's rotation set to 12° and Parallax2D's rotation left at 0°.

The same issue occurs with a setup of ParallaxBackground > ParallaxLayer > Sprite2D.

![Screenshot from 2024-08-15 18-47-03](https://github.com/user-attachments/assets/9716c516-2ddd-44bc-adda-82e8e1660958)

I am not sure if this is the intended behaviour? Please let me know if there is missing information or if I am misunderstanding how Parallax2D works! :)

### Steps to reproduce

* Create a Parallax2D node and set any Repeat Size with a minimum Repeat Times of 1
* Add a child node (Sprite2D) and set it's **rotation** to anything other than 0°

### Minimal reproduction project (MRP)

[parallax_demo_MRP.zip](https://github.com/user-attachments/files/16627666/parallax_demo_MRP.zip)

**Comment by markdibarry** [comment] 2024-08-15 23:26
You know, I have no idea. I assumed it should be the same between the two versions, but I'm not sure what is desired. If it's more desired and doesn't have any bad side effects, I'd be happy to look into changing how it works.

**Comment by kleonc** [comment] 2024-08-18 17:24
As pointed out in https://github.com/godotengine/godot/pull/95666#issuecomment-2295258620 ParallaxLayer/ParallaxBackground behave the same way in v4.3.stable.official [77dcf97d8] which is a regression compared to v4.2.stable.official [46dc27791]. Parallax2D was just added so not a regression but both me and @markdibarry consider this a bug. Hence marking as such.

v4.2.stable.official [46dc27791]|v4.3.stable.official [77dcf97d8]
-|-
![V5Xq3RMX6w](https://github.com/user-attachments/assets/64d7d2e0-496c-4cb8-aecf-4d8c33075bbd)|![s4gOLbO21z](https://github.com/user-attachments/assets/d287ebc7-3f67-42ed-b9ff-20a65f4d25b7)

**Closed** 2024-08-19 12:38 UTC
Labels: bug, discussion, topic:rendering, regression, topic:2d

**Comment by Macksaur** [comment] 2024-09-13 02:21
I'm on 83d54ab2ad and this seems to be broken, I can't get the MRP to produce the new behaviour. Actually, wait, it does work but only on `Compatibility` and does not work on `Forward+`.

**Comment by kleonc** [comment] 2024-09-13 14:43
> I'm on [83d54ab](https://github.com/godotengine/godot/commit/83d54ab2ad476ae265b323c2b88f4623b922f4c6) and this seems to be still broken, I can't get the MRP from #95666 to produce the new behaviour. Actually, wait, it does work but only on `Compatibility` and does not work on `Forward+`.

Seems like #92797 was not properly rebased to account for the changes in `servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp` done in https://github.com/godotengine/godot/commit/1bd8372813d8a329188c05e8cc8c0c66f60b1735 / #95666. cc @stuartcarnie

Basically this part from the current `master` is pre-#95666 because of this:
https://github.com/godotengine/godot/blob/74de05a01c8716a42d4e3427f607d7bea76b35e5/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L2149-L2166

So that's a new regression and, if anything, should be rather reported as a new issue.

**Comment by stuartcarnie** [comment] 2024-09-13 20:41
@kleonc thanks for directing me to the issue! It is fixed in #96977
