### ISSUE TITLE
move_and_slide is not working the same on godot 3.1.2 and 3.2

### ISSUE THREAD

**Issue by ennQ** [godotengine/godot#35024] opened 2020-01-11 21:15 UTC
**Godot version:** v3.2.beta5 and v3.1.2.stable

**Issue description:** On godot 3.2, the option stop on slope is not working properly, the kinematic body does not stop and continue to slide. Where on godot 3.1.2, with the same code, the kinematic body does stop when not moving on the slope.

**Minimal reproduction project:** I've got a very basic demo project showing the issue with just 1 kinematic body moving  on a plane with a slope. If you run it with godot 3.1.2, the kinematic body stop on slope but if you run it with godot 3.2, the kinematic body slides on it until it touch the ground. 

Demo project : [DemoSlope.zip](https://github.com/godotengine/godot/files/4049862/DemoSlope.zip)

Here's 2 gif i took from the project run with godot 3.2 and godot 3.1.2 : 

Gif of the sample project with godot 3.1.2:

![Gif of project with godot 3.1.2](https://user-images.githubusercontent.com/58097205/72210659-0a094900-34bf-11ea-9297-ddf7efde556f.gif)

Gif of the sample project with godot 3.2:

![Gif of project with godot 3.2](https://user-images.githubusercontent.com/58097205/72210666-1d1c1900-34bf-11ea-9b2a-5b56d6e7e21a.gif)

And here is the code for moving the kinematic body (used in this sample project): 

```
extends KinematicBody

const GRAVITY = -24.8

var vel = Vector3()

const MOUSE_SENSITIVITY = 0.05
const MAX_SPEED = 10
const ACCEL = 10

var dir = Vector3()

var camera


func _ready():
	camera = $Camera
	
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)


func _process(delta):
	process_input(delta)
	
	dir.y = 0
	dir = dir.normalized()
	
	var hvel = vel
	hvel.y = 0
	hvel = hvel.linear_interpolate(dir * MAX_SPEED, delta * ACCEL)
	
	vel.x = hvel.x
	vel.z = hvel.z
	
	vel.y += GRAVITY * delta
	vel = move_and_slide(vel, Vector3.UP, true)

func process_input(delta):
	dir = Vector3()
	var cam_xform = camera.get_global_transform()

	var input_movement_vector = Vector2()

	if Input.is_action_pressed("forward"):
		input_movement_vector.y += 1
	if Input.is_action_pressed("backward"):
		input_movement_vector.y -= 1
	if Input.is_action_pressed("left"):
		input_movement_vector.x -= 1
	if Input.is_action_pressed("right"):
		input_movement_vector.x += 1

	input_movement_vector = input_movement_vector.normalized()

	# Basis vectors are already normalized.
	dir += -cam_xform.basis.z * input_movement_vector.y
	dir += cam_xform.basis.x * input_movement_vector.x
	
	if Input.is_action_just_pressed("ui_cancel"):
		if Input.get_mouse_mode() == Input.MOUSE_MODE_VISIBLE:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)

func _input(event):
	if event is InputEventMouseMotion and Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
		camera.rotate_x(-deg2rad(event.relative.y * MOUSE_SENSITIVITY))
		self.rotate_y(deg2rad(event.relative.x * MOUSE_SENSITIVITY * -1))

		var camera_rot = camera.rotation_degrees
		camera_rot.x = clamp(camera_rot.x, -70, 70)
		camera.rotation_degrees = camera_rot
```

I can comment the piece of code if some of this is not clear, but its very basic fps movements.
Also if you use a QWERTY keyboard you might need to re bind the inputs of the project, because i used an AZERTY keyboard to move the kinematic body.

That said, i dont know why the default KinematicCharacterController of Bullet Physics is not implemented in Godot, it's used in the Xenko engine for example and work very well with slopes.

**Comment by jclc** [comment] 2020-01-12 23:50
Shouldn't you be doing physics integration in _physics_process, not in _process?

**Comment by ennQ** [comment] 2020-01-13 01:24
I just tried the same code while putting the velocity calculation and applying movement into _physics_process and i got the same result.

I understand where the issue come from tho:
move_and_slide with the stop on slope option on true actually stops the kinematic body on a slope if the velocity is null. 
And with this code on godot 3.1.2, when you dont press any keys, the input direction vector after decceleration (hvel) actually go to 0 while on godot 3.2, when you dont press any keys, the vector hvel will never reach 0 and so godot will not make you stop on the slope.

I don't know if thats where the issue come from or if it can help, but thats what i noticed by monitoring the velocity (vel) while going on the slope.

**Comment by madmiraal** [comment] 2020-01-17 13:23
Duplicate of #34117?
Have you tried the suggestions [there](https://github.com/godotengine/godot/issues/34117#issuecomment-565698923)?

**Comment by Calinou** [comment] 2020-01-29 22:19
Duplicate of #34117.

**Closed by Calinou** 2020-01-29 22:19 UTC
Labels: bug, regression, topic:physics
