### ISSUE TITLE
ERROR: Index track = <N> is out of bounds (tracks.size() = 0).    at: _set (scene/resources/animation.cpp:98)

### ISSUE THREAD

**Issue by unwave** [godotengine/godot#55765] opened 2021-12-09 19:33 UTC
### Godot version

v4.0.dev.calinou [f1e3c8724]; v4.0.dev.custom_build [1b9fb5c96]

### System information

Operating system: Windows-10-10.0.18362-SP0 64 Bits; Graphics card: GeForce GTX 760M/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 425.31

### Issue description

This project: https://github.com/TokageItLab/3d-platform-test-for-godot4 by @TokageItLab

Repeating error:

```
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
```

<details>
  <summary>Index track  = from 0 to 54</summary>

 ```
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 1 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 2 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 3 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)

...

ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 54 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
```

</details>

I have tried with:
`v4.0.dev.custom_build [1b9fb5c96]`
`v4.0.dev.calinou [f1e3c8724]` https://hugo.pro/projects/godot-builds/

Operating system: `Windows-10-10.0.18362-SP0 64 Bits`
Graphics card: `GeForce GTX 760M/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 425.31`

Cannot move.
![211209_221204_godot_3d_platform_test_(DEBUG)](https://user-images.githubusercontent.com/39925416/145460702-9fd12bbb-b4b5-417e-831d-2f715fc568d2.png)

### Steps to reproduce

Open the project with the specified versions.

**Comment by and-rad** [comment] 2021-12-09 21:01
This is likely a duplicate of #55292. `Transform` animation tracks were replaced by individual `rot/loc/scale` tracks. If you want your old animations to work with current 4.0 you have to convert them manually or reimport them.

**Comment by TokageItLab** [comment] 2021-12-09 21:53
I know that project is outdated, and I need to re-import the animations, but I also need to fix a serious bug in the  animation blending currently #54205. Please wait a while until those are fixed.

**Comment by unwave** [comment] 2021-12-09 22:02
Thanks. I got it. It was confusing because the project is already for Godot 4 and it silently rewrites ".godot" changing config_version=4 to config_version=5. https://github.com/godotengine/godot/commit/e81c689592bd493aa2ff67b8e9d2d9107572647a#diff-1f1c9f2b376ebc877b4dd450504a553c1e79950bacfdf2bb0e7893e425a97b4d

```
C:\Users\Asus-PC>D:\Desktop\godot.exe D:\games\my\godot\godot_4\3d-platform-test-for-godot4-main\project.godot
Godot Engine v4.0.dev.calinou.f1e3c8724 - https://godotengine.org
Vulkan API 1.1.0 - Using Vulkan Device #0: NVIDIA - GeForce GTX 760M

ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
   at: _set (scene/resources/animation.cpp:98)
ERROR: Index track = 0 is out of bounds (tracks.size() = 0).
...
```

Does even not give the prompt:
![211210_005606_godot_Please_Confirm](https://user-images.githubusercontent.com/39925416/145482136-ac7f1122-2e43-43da-a3f7-d7320cde9403.png)

**Comment by Calinou** [comment] 2021-12-09 22:05
Duplicate of https://github.com/godotengine/godot/issues/55292.

**Closed by Calinou** 2021-12-09 22:05 UTC

**Comment by unwave** [comment] 2021-12-09 22:31
@Calinou Do you mean it is supposed to prompt with any method of opening project? 

> config_version=4 was never used in a stable Godot release

What do you mean by it? v3.4.stable.official [206ba70f4] creates ".godot" with `config_version=4`

**Comment by Calinou** [comment] 2021-12-09 22:42
> Do you mean it is supposed to prompt with any method of opening a project?

It will only prompt if you open a project from the project manager, as the warning dialog is part of the project manager, not the editor. If you open a project from the command line, the warning dialog will never have an opportunity to appear.
