### ISSUE TITLE
Incorrect blending of imported animations (glb extension).

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#88805] opened 2024-02-25 08:01 UTC
### Tested versions

Reproducible in 4.2.1 stable and 4.3 dev.
3.5.3 works as expected.

### System information

Ubuntu 22.04

### Issue description

Blending of imported animations is not right. The issue is best described in the attached videos: the hands are always touching the weapon in the animations imported from Blender. However, when blending both animations with a Blend2 node the **hands get out of the weapon** (first video, Godot 4.3 dev and 4.2.1). This issue translates to all the blending nodes. Importantly, we can see that **Godot 3.5.3 blends the animations as expected** (second video). Also, Blender blends the animations as expected (third video).
The issue persists even disabling animation player optimization in the import menu.

https://github.com/godotengine/godot/assets/8985409/865644dd-9986-497d-8544-553916fb0493

https://github.com/godotengine/godot/assets/8985409/b1c453bf-7e94-4c09-9610-8d8ee9e71e89

https://github.com/godotengine/godot/assets/8985409/3eaeb0ad-4989-4d8d-9c1c-01570d2805bb

### Steps to reproduce

Download the attached project and play with the blend amount value of the Animation Tree.
If we set up this in Godot 3.5.3, the animations work as expected.

### Minimal reproduction project (MRP)

[fps 43.zip](https://github.com/godotengine/godot/files/14395607/fps.43.zip)

**Comment by TokageItLab** [comment] 2024-02-28 11:01
Probably dupe of https://github.com/godotengine/godot/issues/81021. I believe the model's rest is just not set correctly.

**Comment by TokageItLab** [comment] 2024-02-28 11:59
If you want to make the shortest blending based on the arms bent wide, you can solve this problem by setting the bent arms as "rest" as below.

[fps 43_rerest.zip](https://github.com/godotengine/godot/files/14433378/fps.43_rerest.zip)

If you want to have the shortest possible blend between specific blends, taking into account the blending with the animation, you may need to rewrite rest according to State, if the model takes rest pose in somewhere.

I am not sure how the rest pose is handled in DCC software, but seeing that it is not exported as an animation, if the rest pose is made into an animation and included in the blend on DCC software, the result may be the same as in Godot 4.x.

**Closed by TokageItLab** 2024-02-28 11:59 UTC
Labels: bug, needs testing, topic:import, topic:animation, topic:3d

**Comment by jcarlosrc** [comment] 2024-03-01 21:06
I get that making a deterministic animation system is important, but there are things that does not seem to be ok with the current implementation. Prioritizing rotation towards rest pose against the closest animation is strange . An animation system should be first of all visually consistent, and right now it seems we need to fight and find technical workarounds to make it look the way we want. I am encountering far more undesired visual artifacts now than in Godot 3.x. It is not  big it is a feature, but it is getting too hard to make a simple FPS animation system to work as intended. I thought the new "not deterministic" option would get it close to the Godot 3.x state but it does not.
