### ISSUE TITLE
Flipped variant tiles are shown unflipped in collision shape editor

### ISSUE THREAD

**Issue by rainerdeyke** [godotengine/godot#60947] opened 2022-05-11 14:54 UTC
### Godot version

4.0-alpha7

### System information

Lubuntu 22.4 LTS

### Issue description

After creating a flipped variant tile, the tile is shown unflipped in the collision shape editor for that tile.  This makes it difficult to draw complex collision shapes for flipped tiles.

### Steps to reproduce

Create a tileset.
Give the tileset a physics layer.
Add a texture atlas to the tileset containing at least one non-symmetrical tile.
Create a variant tile from this tile.
Select the variant tile.
In the tile settings, check the H Flip checkbox under Rendering.
Open Physics --> Physics Layer 0 in the tile settings.
Scroll down to see the tile image in its original unflipped orientation.

### Minimal reproduction project

[test_project.zip](https://github.com/godotengine/godot/files/8670993/test_project.zip)

**Comment by Calinou** [comment] 2022-05-11 15:11
cc @groud

**Comment by groud** [comment] 2022-05-12 13:03
Closing as duplicate of https://github.com/godotengine/godot/issues/56390, which is a consequence of https://github.com/godotengine/godot/issues/44365

**Closed by groud** 2022-05-12 13:03 UTC
Labels: bug, topic:editor, topic:2d
