### ISSUE TITLE
SpinBox doesn't update value when set with `set_value_no_signal`

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot#75528] opened 2023-03-31 09:37 UTC
### Godot version

`master` (db77702177ba259d375dae3fb88473a8711c4faa)

### System information

Arch Linux

### Issue description

Likely a regression from https://github.com/godotengine/godot/pull/68097. When using SpinBox nodes, and setting their value in code using the new `set_value_no_signal` method, the internal LineEdit won't update the displayed value until it's interacted with.

### Steps to reproduce

- Create a SpinBox node, set a value like `3`
- Add a script that sets the value to something else, like `5`
```gdscript
extends SpinBox

func _ready():
	set_value_no_signal(5)
```
- Run the scene. The SpinBox will still say `3`. Interacting with it (left-click) updates the value to `5`, and any edits to it also propagate the changes successfully.

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/11120433/repro.zip)

**Comment by lawnjelly** [comment] 2023-03-31 09:46
We could argue that this is to be expected - it is pretty much a given that internal nodes that rely on the signal for functionality will not work. So perhaps this is a documentation issue?

Or maybe you could fire off a warning if this was used in such nodes.

**Comment by rsubtil** [comment] 2023-03-31 09:54
While it can be expected, I think it's confusing to the user, as the displayed and internal values may be different. As a user I expect `set_value_no_signal` to allow me to set the interface with some arbitrary values without firing signals to my scripts. But when these signals are necessary for internal nodes to work properly, then that behavior should be preserved.

**Comment by KoBeWi** [comment] 2023-03-31 13:32
Duplicate of #70821 btw

**Closed by KoBeWi** 2023-03-31 13:32 UTC
Labels: bug, topic:gui
