### ISSUE TITLE
Graphics freeze after waking from sleep

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#66302] opened 2022-09-23 13:19 UTC
### Godot version

4.0.beta1

### System information

Manjaro Linux (KDE X11)

### Issue description

If Godot 4 is open when I close my laptop to put it to sleep, when I open it again and wake it up Godot freezes. It seems to just be the renderer that freezes, because shortcuts like quit, open project manager, etc. still work.

### Steps to reproduce

- Open a project in Godot 4
- Put device to sleep
- Wake it up
- The UI does not update anymore, but shortcuts work

I've been able to reproduce this every time.

**Comment by Calinou** [comment] 2022-09-23 15:24
Duplicate of https://github.com/godotengine/godot/issues/52738.

**Closed by Calinou** 2022-09-23 15:24 UTC
