### ISSUE TITLE
Editor crashes when deleting children of GraphNode

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#69082] opened 2022-11-23 23:40 UTC
### Godot version

4.0b6

### System information

Linux/Manjaro

### Issue description

Deleting the last child of a GraphNode crashes the editor, unless that GraphNode has been resized at least once by the user. The issue is easy to avoid, but the crash is still odd.

There is another crash in which deleting all the children of GraphNode at once will crash

### Steps to reproduce

First crash:
1. Create a new scene with a GraphNode, and do not resize it;
2. Add any Control that draws content, like a Button;
3. Delete the new child you just created;
4. Observe the crash

Second crash:
1. Create a new scene with a GraphNode;
2. Add multiple Controls as children;
3. Select all of them and delete them from the scene;
4. Observe the crash.

### Minimal reproduction project

[graphnode-crash-repro.zip](https://github.com/godotengine/godot/files/10079773/graphnode-crash-repro.zip)

This project has two scenes: `graph_node.tscn` showcases the first crash with a default size GraphNode and a single content-drawing Control. The `graph_node_multiple_children.tscn` scene has a GraphNode with multiple children that crash the editor when deleted.

**Comment by John-Gdi** [comment] 2022-11-28 07:34
I have open #69284 to solve the issue. Both two crashes are caused by invalid child pointer, so a safe checking was added to avoid this problem.

**Comment by akien-mga** [comment] 2022-12-05 13:48
Fixed by #69284.

**Closed by akien-mga** 2022-12-05 13:48 UTC
Labels: bug, crash, topic:gui
