### ISSUE TITLE
Unexpected weird behaviour of a RigidBody2D with Mouse

### ISSUE THREAD

**Issue by martinpelli** [godotengine/godot#49847] opened 2021-06-23 01:00 UTC
### Godot version

3.3 stable

### System information

Windows 10 64 bits GLES2

### Issue description

I seriously don´t know how to describe the issue. I am making  a brick breacker game, where instead of a palette you manage a cannon, so it has a  **CollisionPolygonShape**. Some times, when playing, I noticed that I was hitting the ball **without the CollisionPolygionShape** of the cannon, So I realized that I was hitting the ball with the **MOUSE**. I am pretty sure that you can hit the ball with the mouse, don´t ask me how ,because I don´t have any idea. **I don´t have any script** for the mouse, the RigidBody2D is **not setted to pickable**. It´s very difficult to notice it becasue not always happen, I recorded a video where it´s clear, but I had some times where it was more obviusly.
 
https://imgur.com/a/EzBjJGk

In this video you can see the ball at the last of the video, is not hitting the CollisionPolygonShape (don´t confuse with the CollisionShape, big blue of the TouchScreenButton) and I apply an impulse to the ball with the mouse, which obiusly it shouldn´t  happen.

edit: I also noticed that if you change the CollisionPolygon2D of the body to a rectangle CollisionShape, if you hit the ball with the body against the wall, you can see that the ball will stop, but if you hold the mouse without releasing the left click, the ball make an impulse every time, so maybe it’s a problem of the clamp function

### Steps to reproduce

-Download the minimal reproduction project
-Select the scene called Escene.tscn
-Play the scene
-Click inside the TouchScreenButton (the big blue CollisionShape) and holding with out release, move the body to the rigth until it stop because of the clamp function. 
-Try to move the mouse to the ball without releasing the body, like in the video and after a few times you will notice that the mouse can hit the ball.

### Minimal reproduction project

[MouseBug.zip](https://github.com/godotengine/godot/files/6698100/MouseBug.zip)

**Comment by pouleyKetchoupp** [comment] 2021-08-06 01:24
It looks like the game does what's expected from the script, but it's hard to see it from the debug shapes.

This line makes the Body move and hit the ball:
`var collision = Body.move_and_collide(Body.to_local(Vector2(pos.x - offset,clamp_y.x)),false)`

Then these lines reset the Body position when it moved too much on the right:
`Body.global_position.x = clamp(Body.global_position.x,clamp_x.x,clamp_x.y)`
`Body.global_position.y = clamp(Body.global_position.y,clamp_y.x,clamp_y.y)`

So you don't see it, but the body actually moves to the right along the mouse, collides with the ball and is moved back.
You can see it clearly if you comment the two lines that set the Body global position.

In order to handle limits properly, you need to clamp the motion you apply to the Body in move_and_collide. Let me know if that helps.

**Comment by martinpelli** [comment] 2021-08-08 20:38
@pouleyKetchoupp Yes some day ago I thought that could be the clamp function. How I can clamp the motion in move_and_collide? **Thanks for your help and your time !!**

**Comment by pouleyKetchoupp** [comment] 2021-08-09 18:28
@martinpelli No problem! Here's how you can clamp the motion before `move_and_collide` in your script:

```
if event is InputEventScreenTouch:
	offset = pos.x - Body.global_position.x
		
pos.x = offset + clamp(pos.x - offset,clamp_x.x,clamp_x.y)
pos.y = clamp(pos.y,clamp_y.x,clamp_y.y)

var collision = Body.move_and_collide(Body.to_local(Vector2(pos.x - offset,clamp_y.x)),false)
```

I'm closing this issue since it's not a bug with the engine.

**Closed by pouleyKetchoupp** 2021-08-09 18:28 UTC
Labels: bug, topic:physics, topic:2d

**Comment by martinpelli** [comment] 2021-08-09 20:08
@pouleyKetchoupp  that worked!! Thanks bro :)
