### ISSUE TITLE
Spot light projector don't work

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#2506] opened 2015-09-23 08:32 UTC
I asked on FB group and, at least another user  had bad luck with this feature. Here a simple test case saved with 2.0 alpha:  http://ffxrunner2.ffx.it/godot_testcases/testcase_projector_lamp.zip

**Comment by procedural** [comment] 2016-08-15 19:40
Related to https://github.com/godotengine/godot/issues/2002

**Comment by bojidar-bg** [comment] 2016-12-19 14:44
Right, dupe of #2002

**Closed by bojidar-bg** 2016-12-19 14:44 UTC
Labels: bug, topic:core
