### ISSUE TITLE
Can't make Tilemap as root node

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#25310] opened 2019-01-25 02:22 UTC
**Godot Version**
3.1 beta 2
**OS Version**
Windows 10 version 1803

**Issue description:**
Instanced a tilemap scene into another scene and the tilemap was completely distorted. It appears this happens when the tilemap is the root node of the scene. I made a Node2D as the root node and it fixed it.

**Tilemap scene**
![image](https://user-images.githubusercontent.com/16636969/51720969-b12a7180-201d-11e9-8abf-deff33e7a1ba.png)

**Scene with tilemap scene instanced**
![image](https://user-images.githubusercontent.com/16636969/51721009-dd45f280-201d-11e9-9f59-44316bc65526.png)

**Corrected tilemap scene**
![image](https://user-images.githubusercontent.com/16636969/51721023-f51d7680-201d-11e9-982e-86877a42e188.png)

**Scene with corrected tilemap scene instanced**
![image](https://user-images.githubusercontent.com/16636969/51721038-0fefeb00-201e-11e9-9cbf-89127787f6b3.png)

**Steps to reproduce:**
Make tilemap as root node
Instance the tilemap into another scene

**Comment by akien-mga** [comment] 2019-01-25 09:04
CC @MarianoGnu @YeldhamDev @guilhermefelipecgs

**Comment by groud** [comment] 2019-01-31 15:51
I cannot reproduce the bug on master. Could you try with the latest beta and provide a sample project ?

**Comment by groud** [comment] 2019-02-19 14:02
Closing as I could not reproduce the bug and no sample project were provided.

**Closed by groud** 2019-02-19 14:02 UTC
Labels: bug, topic:core
