### ISSUE TITLE
the fonts size of built-in documents is too small to see clearly

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#10850] opened 2017-09-01 09:31 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.1.*

**Issue description:**

the built-in is very handy, but is almost useless with so small font size.
However,sometimes, the font size is normal.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Calinou** [comment] 2017-09-01 09:46
Can you take a screenshot of the editor when you see that the documentation font is too small? It looks fine for me here.

**Comment by alexzheng** [comment] 2017-09-01 10:24
<img width="1678" alt="screen shot 2017-09-01 at 6 23 07 pm" src="https://user-images.githubusercontent.com/1130047/29966049-b79851da-8f42-11e7-9436-38ee41fd7660.png">

**Comment by akien-mga** [comment] 2017-09-01 10:26
What is your macOS version, and your screen resolution? Do you have several monitors connected?

**Comment by alexzheng** [comment] 2017-09-01 10:29
device: MacBook Pro
OS: macOS Sierra
Version 10.12.6
Resolution: Default for display
no additional monitors connected.

**Comment by akien-mga** [comment] 2017-09-01 10:36
What is "Default for display" in pixels?

**Comment by alexzheng** [comment] 2017-09-01 11:07
device: MacBook Pro (15-inch, Late 2016)

default resolution: 1680 * 1050

**Comment by akien-mga** [comment] 2017-09-01 11:17
Ok, that shouldn't be interpreted as HiDPI (limited in the auto mode to >= 192 DPI and width >= 2000), so the culprit is somewhere else.

**Comment by groud** [comment] 2017-09-01 11:53
Are you sure you are using the default zoom level for the script editor ? Is there any other places where the text is that small ?

**Comment by alexzheng** [comment] 2017-09-01 12:11
I have not noticed any where else is so small until now.
It seems it's not the issue about the script editor, if the script were also that small, it's impossible to code.

**Comment by Calinou** [comment] 2017-09-01 17:52
> Ok, that shouldn't be interpreted as HiDPI (limited in the auto mode to >= 192 DPI and width >= 2000), so the culprit is somewhere else.

I think @alexzheng is talking about the DPI-independent pixels here. macOS uses 2× scaling for hiDPI on laptop displays, so their screen resolution is actually double that one (in each dimension).

**Comment by akien-mga** [comment] 2017-09-01 19:43
Good, if so the problem is maybe that the documentation is not DPI aware (does not use EDSCALE).

**Comment by spkingr** [comment] 2018-08-06 14:31
Same problem in my computer, win10, 4K screen resolution.
The script font size is normal, but the build in document font size is too small to read.
How to fix that? Thanks!

**Comment by akien-mga** [comment] 2018-09-17 14:18
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:18 UTC
Labels: bug, topic:editor

**Comment by paulmiller** [comment] 2020-03-19 21:30
This is still an issue in Godot 3.2 (I'm on Linux, if that matters.) I have a UHD monitor and by default all text is too small. I can fix most of the text via Editor Settings > Interface > Editor > Main/Code Font Size but the documentation font is still too small.

![godot-docs-screenshot](https://user-images.githubusercontent.com/4240296/77116548-99fece00-69ed-11ea-8843-24071bb68ef6.png)

**Comment by Calinou** [comment] 2020-03-19 22:12
@paulmiller While there is a way to adjust the documentation font size, you generally want to change **Interface > Editor > Editor Scale** rather than adjusting all font sizes manually. It's easier and will also adjust icon sizes :slightly_smiling_face:

**Comment by paulmiller** [comment] 2020-03-19 22:24
Thanks!
