### ISSUE TITLE
Order of input_event signals: "visible order"

### ISSUE THREAD

**Issue by dbenoy** [godotengine/godot#24259] opened 2018-12-10 13:40 UTC
**Godot version:**

cac8cc8

**OS/device including version:**

Ubuntu 18.04 / Radeon RX 560

**Issue description:**

When I place down two Area2Ds, and then I produce an input_event signal for two areas at once (because they overlap), it doesn't produce the signals in the order I would expect.

Since these events are meant to detect what the user is trying to interact with on their screen, I would have expected it act based on what would be in the 'foreground' and what would be in the 'background' (if the Area2Ds were hypothetically visible), and allow my code to mark the interaction as 'handled' by whatever means, so that background elements don't react when the player is trying to interact with something in the foreground.

So for 3D Areas, it should be done in order from nearest to farthest from the camera, and for Area2D it should use z_index and the reverse order of appearance in the node tree.

**Steps to reproduce:**
1. Load the attached project
1. Note the order of ClickArea1 and ClickArea2, and also the order of Sprite and Sprite2
1. Run the program and click. 'Left' appears in the output when you may expect 'Right'
1. Changing the z_index of the Area2D objects doesn't seem to help.

**Minimal reproduction project:**

[collision-input-order.zip](https://github.com/godotengine/godot/files/2663307/collision-input-order.zip)

**Script from the project:**
```
extends Node2D

func _on_ClickArea1_input_event(viewport, event, shape_idx):
    if (event is InputEventMouseButton and event.button_index == BUTTON_LEFT and event.pressed):
        if get_tree().is_input_handled():
            return
        get_tree().set_input_as_handled()
        print("Left")

func _on_ClickArea2_input_event(viewport, event, shape_idx):
    if (event is InputEventMouseButton and event.button_index == BUTTON_LEFT and event.pressed):
        if get_tree().is_input_handled():
            return
        get_tree().set_input_as_handled()
        print("Right")
```

**Comment by dbenoy** [comment] 2018-12-10 13:43
There may be some workaround where the signal handler tries to determine what collision objects may be obscuring it, and if it's in the 'background' then it could decide not to act.

But in the case where you have some areas which are actually _supposed_ to allow the user's clicks to pass through it, then this means that all the signal handlers (even in very different parts of the project, perhaps in otherwise self-contained instances) would have to have an awareness of the behavior of these other nodes, and figure out under which circumstances it would want to claim the input event, and under which circumstances it would want to allow it to 'pass through' to a background object.

**Comment by Naryosha** [comment] 2018-12-11 16:08
I tried your minimal project and the input event order of the overlapped area seems to be random. Sometimes I got an expected "Right" without changing anything.

**Comment by dbenoy** [comment] 2018-12-11 17:01
Wow. That makes the problem even worse.

I got 'Left' consistently but it may have been a coincidence.

**Comment by Andevid** [comment] 2019-01-24 22:55
I have already built another example project at here https://github.com/Andevid/View-Order

**Comment by meheleventyone** [comment] 2021-11-06 12:34
https://user-images.githubusercontent.com/5731661/140609767-f615f9c0-32b9-497d-9650-ab94041690ad.mp4

I think I ran into this issue but am very new to Godot. From what I've found the z index is respected if you save the project before running it but if you just click the run button after changing the values then the order will be the same as the previous scene values.

Attached is a video repro.

**Comment by meheleventyone** [comment] 2021-11-06 14:16
Some further information.

I dug into the source and found the point where these input_event signals are generated: https://github.com/godotengine/godot/blob/13aaa7312427e98661dba0183cbbee6bbc8f6542/scene/main/viewport.cpp#L647

So the results from the physics engine intersect_point are just used in order. This led me to suspect that the script level call would suffer from the same issue. In testing I confirmed that is the case. The ordering in the 2D physics scene is different to the visual ordering in the editor sometimes.

Of course it's subjective as to what the correct order should be but I think an intuitive heuristic would be matching the visual ordering and above all the result should be consistently the same.

**Comment by Sauermann** [comment] 2022-11-24 09:37
duplicate of #23051

**Closed** 2022-11-24 09:38 UTC
Labels: bug, usability, topic:input
