### ISSUE TITLE
Godot 4 beta 2 Can't export to web, file in use or lacking premission 

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#67019] opened 2022-10-07 09:14 UTC
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650, i5-11300H

### Issue description

![image](https://user-images.githubusercontent.com/80917990/194517047-420c8d49-df70-4ce4-9c26-ee6ae72e4908.png)

### Steps to reproduce

make a new project, choose mobile in renderer, and try to export to web 
using the HTML5 button in the top right produces the same error and the webpage is just a black screen
Running godot as an admin also didn't help

### Minimal reproduction project

[Uploading Example.zip…]()

**Comment by akien-mga** [comment] 2022-10-07 10:29
Duplicate of #65660.

**Closed by akien-mga** 2022-10-07 10:29 UTC
