### ISSUE TITLE
Using Websocket and HTTPRequest together causes HTTPRequest to not connect

### ISSUE THREAD

**Issue by ipeerbhai** [godotengine/godot#35139] opened 2020-01-15 00:41 UTC
I have a small app I've written that uses both the HTTPRequest node and a WebSocketClient to communicate with a custom server.  I've tested this to repro with Godot 3.1.2 stable.

The websocket and the HTTPRequest are in separate .gd files, and each is attached to a node like this:
/root/Player/HTTPRequest
/root/RTC

Both nodes work correctly individually.
When the "RTC" node makes a websocket connection, HTTPRequest stops sending the "request_completed" signal.  The underlying HTTPClient stops working, and spins at STATUS_CONNECTING if WebSocketClient is active.

I'm working around the bug by using a signal in the player object to indicate that it is done using HTTP, which the RTC node waits for with an explicit yield.  This is a short-term fix, as I need to make other HTTP calls -- which won't work at all as long as the websocketclient is alive.

I've attached both GDScripts -- putting the two nodes into an App and removing the yield in the RTC will result in the HTTPRequest not working wtih any URL.

[Player.zip](https://github.com/godotengine/godot/files/4062498/Player.zip)
[RealTimeCommunication.zip](https://github.com/godotengine/godot/files/4062499/RealTimeCommunication.zip)

**Comment by Faless** [comment] 2020-02-22 15:43
I don't see how that can happen in the engine, plus, I can't reproduce the issue with this simple test project: [proj_test.zip](https://github.com/godotengine/godot/files/4239539/proj_test.zip) .
I suspect it's some error in the user code or infrastructure, there's not much we can do without a minimal reproduction project.
Closing, but feel free to comment if the attached test does not work for you, or if you feel the issue is still valid and you can provide a minimal reproduction project.
I'll promptly reopen in case.

**Closed by Faless** 2020-02-22 15:43 UTC
Labels: bug, topic:network
