### ISSUE TITLE
godot animation player fully crashing my system

### ISSUE THREAD

**Issue by bluewarrior06** [godotengine/godot#52950] opened 2021-09-22 21:27 UTC
### Godot version

3.3.3.stable.official

### System information

windows 10, GLES3, Intel HD Graphics 620

### Issue description

when ever I have a ton of bones or the animation has tons of keyframes, the engine freezes up and my pc just crashes, literally just crashes my pc, black screen. 

at first I thought it was that I didn't shut down my laptop for a while, but when I turned my pc back on, the animationplayer still crashed my pc.

I'm not sure if this is a problem with my pc not being strong enough, but my CPU is low/normal when it happens, and I don't see any spikes in memory so I'm not sure on what it is.

### Steps to reproduce

create an animation player and either assign a bunch of keys too it, or create a bunch of tracks (around 30 tracks did the job for me)

**Comment by Calinou** [comment] 2021-09-22 21:30
Duplicate of https://github.com/godotengine/godot/issues/35653 (same cause).

**Closed by Calinou** 2021-09-22 21:30 UTC
