### ISSUE TITLE
$"AnimationPlayer".stop(true) or stop(false) both just simply pause the animation without reset.

### ISSUE THREAD

**Issue by BracerJack** [godotengine/godot#41838] opened 2020-09-07 06:12 UTC
[Animation_Learning.zip](https://github.com/godotengine/godot/files/5181317/Animation_Learning.zip)

**Godot version:**
Version 3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
$"AnimationPlayer".stop(true) #Pause the animation.
$"AnimationPlayer".stop(false) #Pause the animation
Both pause the animation, none reset it back to starting position.
And why do this instead of a simple pause() and stop() ?

**Steps to reproduce:**
Minimum basic file attached to replicate issue.

**Comment by IlTrain** [comment] 2020-09-07 06:16
Working on it

**Comment by BracerJack** [comment] 2020-09-07 06:18
Hello IlTrain, thank you for replying, what does "working on it" means here ?

1: Working on fixing this bug ?
2: Working on a stop() and pause() function so that it actually makes linguistic sense and no longer require people to read the manual to know which is which because nobody will actually remember without reading the manual or experiment on it again ?

Which of the two ? Thanks IlTrain :D

**Comment by IlTrain** [comment] 2020-09-07 06:30
Hi, first of all sorry if it will take a while, I am currently on another pc and I have no way to access mine, so I have to reinstall everything. I'm starting to work to make sure that when "$AnimationPlayer.stop()" is called the animation starts again from the beginning

**Comment by IlTrain** [comment] 2020-09-07 08:20
I've just added the pause() method, now I'm testing

**Comment by IlTrain** [comment] 2020-09-07 08:30
This is what I added:
$AnimationPlayer.pause() # Pauses The Animation
$AnimationPlayer.pause(true) # Also Pauses The Animation
$AnimationPlayer.pause(false) # Makes The Animation Continues

**Comment by BracerJack** [comment] 2020-09-07 08:52
Wait...why would you add a pause (true) if pause actually work ?
Is the message behind it = "pause(true) because pause(false) actually do other MAGICAL things that no one asked for ?"

Pleased don't implement pause(true/false/require any arguments at all)
pause() should just work as stand alone without arguments.

Yes if you can implement resume that would be awesome too.
So AnimationPlayer will have:
1: play() //start from beginning
2: pause() //pause, and NO ARGUMENTS, please don't make thing unnecessarily complicated, it should just be pause and nothing else.
3: resume ()

There is one other crazy thing:
AnimationPlayer".seek(0, true) 
WHY is there another argument requiring a true or false ?
Because you want to see the animation to 0 and NOT have it updated ? In what universe would anyone want that ?
Please just make it .seek(0) that's it, please stop the excessive boolean arguments, this is madness.

**Comment by IlTrain** [comment] 2020-09-07 09:00
Just in time, I was making the pr. Let me remove the boolean argument.
Thank you very much for the feedback

**Comment by BracerJack** [comment] 2020-09-07 09:08
Where can I download the next built that have pause()/resume()/and seek(arg) without the rubbish addiction true/false requirement ?   
I cannot work with Godot as it presently is at this moment as the current implementation is pure madness.

**Comment by IlTrain** [comment] 2020-09-07 09:10
I will build a custom build for you

**Comment by IlTrain** [comment] 2020-09-07 09:55
I didn't add seek(arg) because of not breaking the compatibility, but if I don't go wrong the seek's second argument is optional

**Comment by Calinou** [comment] 2020-09-07 12:50
> I cannot work with Godot as it presently is at this moment as the current implementation is pure madness.

I don't think that prevents you from shipping projects :slightly_smiling_face: 

Also, I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by KoBeWi** [comment] 2020-09-11 12:33
The AnimationPlayer not resetting on `stop(true)` is a known issue #27499 (there's a fix that's not merged yet; you can use a workaround)

The refactor of stop/pause/play is discussed here: https://github.com/godotengine/godot-proposals/issues/287

Closing, as the issue is already tracked.

**Closed by KoBeWi** 2020-09-11 12:33 UTC
