### ISSUE TITLE
Editor Script: Autocomplete does not allow scrolling list with mousewheel. 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22196] opened 2018-09-17 20:17 UTC
**Godot version:**
3.1 alpha
Mac OS X, High Sierra

**Issue description:**
Editor Script: Autocomplete does scroll long options list with mouse wheel.  Must use arrow keys. 

**Steps to reproduce:**
in a script function type `Control.` and you will see the list of class options after the ".". Scrolling with mouse wheel is not available, neither is a scrollbar.

**Comment by akien-mga** [comment] 2018-09-18 06:29
Would likely be fixed by #21181.

**Comment by KoBeWi** [comment] 2021-02-24 22:52
Is this system specific issue? I can't reproduce it on Windows in any version.

**Closed** 2021-06-01 15:58 UTC
Labels: enhancement, topic:editor, usability
