### ISSUE TITLE
ViewportTexture cascade of errors when moving the TextureRect using it

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20776] opened 2018-08-06 23:43 UTC
Godot 3.0.6
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

I am trying to setup a simple scene for a shader feedback effect, with a viewport that always render and never clears so I can accumulate frames.
but found a number of confusing stuff.

I seem to have broken my setup by simply changing the sibling index of my output node.
![image](https://user-images.githubusercontent.com/1311555/43746201-bb211bea-99da-11e8-8f65-b19fb56bc7af.png)
Then weird stuff happened when I tried to fix it.

Reproduction project: 
[FeedbackViewportIssues.zip](https://github.com/godotengine/godot/files/2264466/FeedbackViewportIssues.zip)

1) Open main.tscn: notice nothing renders, but it's a separate issue #20775
2) Drag `TextureRect` upwards in the scene tree so it appears before `ViewportContainer`. notice errors print in the console:
```
ERROR: Node not found: ViewportContainer/Viewport
   At: scene/main/node.cpp:1524
ERROR: ViewportTexture: Path to node is invalid
   At: scene/main/viewport.cpp:65
```
This is unexpected because the path should be the same, only the sibling index changed.

3) Click on the texture of the `TextureRect`, click on the `Viewport Path` property icon, and select again the viewport to fix the path. Notice the path that was assigned actually starts from the root of the editor:
`/root/EditorNode/@@5/@@6/@@14/@@16/@@20/@@24/@@25/@@26/@@42/@@43/@@50/@@51/@@6457/@@6323/@@6324/@@6325/@@6326/@@6327/@@6328/Node/ViewportContainer/Viewport`

Of course if you save that scene it's going to be persistently broken :p

**Comment by clayjohn** [comment] 2018-08-07 03:53
Related: #19259 and #16067

**Comment by KoBeWi** [comment] 2020-06-19 13:09
@Zylann Can you check if this is fixed in 3.2.2? I can't reproduce it even in 3.0.6, not sure why.

**Comment by Zylann** [comment] 2020-06-19 23:00
I can't reproduce in 3.0.6 or 3.2.2 rc1 either. It managed to happen before, so either there is some lucky uninitialized variable somewhere, or a pesky little detail is missing from the repro.

**Comment by KoBeWi** [comment] 2020-06-19 23:15
So I will close it for now.

**Closed by KoBeWi** 2020-06-19 23:15 UTC
Labels: bug, topic:core
