### ISSUE TITLE
Pressed keyboard keys on android are recognized false

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39688] opened 2020-06-19 17:43 UTC
**Godot version:**
3.2.1.stable.official
**OS/device including version:**
Windows 10 Home 1909 | Samsung Galaxy S7
**Issue description:**
On my laptop, everything works, but not on my phone.
```
var rng = RandomNumberGenerator.new()
var audible_ascii = -1
func _ready():
	rng.randomize()

func _unhandled_key_input(event):
	if event.is_pressed():
		print("hello")

func new_key():
	var my_random_number = rng.randi_range(87, 122)
	if my_random_number < 97:
		my_random_number -= 39
	var conversion_raw_array = PoolByteArray([my_random_number])
	var visual_var_that_has_nothing_to_do_with_the_pressed_key = conversion_raw_array.get_string_from_ascii()
	audible_ascii = rng.randi_range(87, 122)
	if audible_ascii < 97:
		audible_ascii -= 39
	var conversion_raw_array2 = PoolByteArray([audible_ascii])
	audible_key = conversion_raw_array2.get_string_from_ascii()
	print(str(audible_key))
```

I know this is bad code. Look over [here:](https://godotengine.org/qa/74672/how-can-check-user-pressed-key-that-depends-random-variable?show=74675#a74675) That's what I'm trying to do.
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by MaaaxiKing** [comment] 2020-06-19 18:48
My whole game is based on this 😂☹

**Comment by MaaaxiKing** [comment] 2020-06-22 15:31
Can't anyone confirm?😶

**Comment by madmiraal** [comment] 2022-06-28 18:21
It's not clear from the description what the actual issue is i.e. the code provided doesn't do anything other than print "hello" when a key is pressed. However, looking at the linked Q&A, it's probably simply Android virtual keyboards returning UNKNOWN scancodes i.e. #36991.

So I suggest closing this as a duplicate of #36991.

**Closed** 2022-06-29 07:28 UTC
Labels: bug, platform:android, topic:input
