### ISSUE TITLE
Camera2D is borked after reload_current_scene()

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#72591] opened 2023-02-02 12:24 UTC
### Godot version

Godot 4 Beta 17

### System information

Windows 11

### Issue description

Camera2D essentially stops working entirely after get_tree().reload_current_scene() is called.
it doesn't update its position anymore, it just stays in place wherever it was in the moment reload_current_scene is called.

It doesn't matter if the Camera is newly spawned on _ready, or if it's child of some moved node.
It just stops moving altogether after reload_current_scene()

### Steps to reproduce

1) Create new Project in Godot 4 Beta 17
2) Add Camera2D
3) Move Camera2D around via code
4) call get_tree().call_current_scene() in one way or another
5) camera does not update position anymore

### Minimal reproduction project

-

**Comment by KoBeWi** [comment] 2023-02-02 12:29
Duplicate of #72529
There's a workaround at the bottom.

**Closed by KoBeWi** 2023-02-02 12:29 UTC
Labels: bug, regression, topic:2d
