### ISSUE TITLE
Beta 8 corrupting scene files

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#69953] opened 2022-12-12 12:41 UTC
### Godot version

Godot 4 Beta 8

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Multiple times today I've lost scene files due to corruption and have had to restore from backup. I've only experienced this in beta 8.

It definitely occurs when moving files within Godot, but not all the time. It has occurred adjusting and renaming nodes within a scene then saving, and other situations I'm a bit vague on. The first time the engine crashed and when I came back the scene was corrupted. Subsequent instances occurred without crashes. I've been making a lot of new scenes building assets the last few days and have had no issue there.

In my MRP, when I move the files, I get the following console errors every time. It appears that the scene writer is stripping out external resources. Then the scene parser has a problem reading the new scene files that reference external resources at the top, but the detail below is missing. This causes the console errors.

```
 - 4
ERROR: res://new folder/m_canvas_item.tres:4 - Parse Error: Unexpected end of file
   at: get_dependencies (scene/resources/resource_format_text.cpp:891)
 - 5
ERROR: res://new folder/node_2d.tscn:5 - Parse Error: Unexpected end of file
   at: get_dependencies (scene/resources/resource_format_text.cpp:891)
ERROR: res://new folder/m_canvas_item.tres:4 - Parse Error:
   at: load (scene/resources/resource_format_text.cpp:514)
ERROR: Failed loading resource: res://new folder/m_canvas_item.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
```

My console from previous corruptions have also included these errors and line numbers. I also included the lines from closing the project.

```
ERROR: Method/function failed. Returning: error
   at: rename_dependencies (scene/resources/resource_format_text.cpp:915)
ERROR: Condition "!windows.has(p_window)" is true. Returning: Point2i()
   at: window_get_position (platform/windows/display_server_windows.cpp:896)
ERROR: Condition "!material" is true. Returning: true
   at: material_casts_shadows (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2706)
ERROR: Condition "!material" is true. Returning: false
   at: material_is_animated (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2693)
ERROR: Condition "!material" is true.
   at: material_get_instance_shader_parameters (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2719)
ERROR: Condition "!material" is true.
   at: material_update_dependency (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2731)
ERROR: 8 RID allocations of type '6NavMap' were leaked at exit.
ERROR: 8 RID allocations of type 'P11GodotArea2D' were leaked at exit.
ERROR: 8 RID allocations of type 'P12GodotSpace2D' were leaked at exit.
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: 8 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 8 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 58 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 48 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
ERROR: 8 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 8 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
WARNING: 109 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9774)
ERROR: 105 RID allocations of type 'PN18TextServerAdvanced22ShapedTextDataAdvancedE' were leaked at exit.
ERROR: 19 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1999)
```

After restarting, trying to open a corrupted scene, additional errors:

```
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Laptop GPU

WARNING: Mesh uses old surface format, which is deprecated (and loads slower). Consider re-importing or re-saving the scene. Path: ""
     at: (scene/resources/mesh.cpp:1137)
ERROR: Attempt to open script 'res://tests/node_3d.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1045)
ERROR: res://test/node_3d.tscn:5 - Parse Error:
   at: load (scene/resources/resource_format_text.cpp:514)
ERROR: Failed loading resource: res://test/node_3d.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:596)
ERROR: res://test/node_2d.tscn:5 - Parse Error:
   at: load (scene/resources/resource_format_text.cpp:514)
ERROR: Failed loading resource: res://test/node_2d.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:596)
ERROR: Can't open file from path 'res://tests/test_assets/water_test_shader.gdshader'.
   at: (core/io/file_access.cpp:699)
ERROR: res://test/test_assets/test_scene_40.tscn:16 - Parse Error: Expected '['
   at: load (scene/resources/resource_format_text.cpp:514)
ERROR: Failed loading resource: res://test/test_assets/test_scene_40.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:596)
ERROR: Attempt to open script 'res://tests/test_save.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1045)
ERROR: res://test/test_save.tscn:6 - Parse Error: Expected '['
   at: load (scene/resources/resource_format_text.cpp:514)
ERROR: Failed loading resource: res://test/test_save.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:596)
```

```
ERROR: res://node_2d.tscn:9 - Parse Error: [ext_resource] referenced non-loaded resource at: res://m_canvas_item.tres
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:178)
ERROR: res://node_2d.tscn:15 - Parse Error: [ext_resource] referenced non-loaded resource at: res://m_canvas_item.tres
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:178)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:596)
ERROR: Transient parent has another exclusive child.
   at: (scene/main/window.cpp:473)
ERROR: Transient parent has another exclusive child.
   at: (scene/main/window.cpp:473)
```

While developing the MRP, I moved all files into the new folder within Godot, allowing it to adjust resources. Then I took a previous copy of the project, and moved the files into the same folder for the sake of running a diff. The only difference should be that resource locations should now have `/new folder/` in the former.
eg: 

```
-[ext_resource type="Shader" path="res://canvas_item.gdshader" id="1_u0yr2"]
+[ext_resource type="Shader" path="res://new folder/canvas_item.gdshader" id="1_u0yr2"]
```

However you can see that they are wildly different. Godot has removed countless subresources.

[corrupt_diff.txt](https://github.com/godotengine/godot/files/10207492/corrupt_diff.txt)

@akien-mga 

### Steps to reproduce

1. Open the MRP with the console open.
2. Move all the files into the `new folder`, all at once or one at a time.
3. Review the scene file contents or try to open it afterwards.

The scene that originally looked like this:

```
[gd_scene load_steps=3 format=3 uid="uid://bfu8f5n0bpy7i"]

[ext_resource type="Material" uid="uid://osmo50s430w7" path="res://m_canvas_item.tres" id="1_1oqa1"]
[ext_resource type="Texture2D" uid="uid://coo5o8l630xxs" path="res://icon.svg" id="1_si28r"]

[node name="Node2D" type="Node2D"]

[node name="TextureRect" type="TextureRect" parent="."]
material = ExtResource("1_1oqa1")
offset_right = 40.0
offset_bottom = 40.0
texture = ExtResource("1_si28r")

[node name="Sprite2D" type="Sprite2D" parent="."]
material = ExtResource("1_1oqa1")
position = Vector2(72, 223)
texture = ExtResource("1_si28r")

```

Now looks like this:
```
[gd_scene load_steps=3 format=3]

[ext_resource type="Material" path="res://new folder/m_canvas_item.tres" id="1_1oqa1"]
[ext_resource type="Texture2D" uid="uid://coo5o8l630xxs" path="res://new folder/icon.svg" id="1_si28r"]

```

### Minimal reproduction project

[test_scene_corrupt.zip](https://github.com/godotengine/godot/files/10207888/test_scene_corrupt.zip)

**Comment by KoBeWi** [comment] 2022-12-12 12:43
Duplicate of #69794

**Closed by KoBeWi** 2022-12-12 12:43 UTC

**Comment by tinmanjuggernaut** [comment] 2022-12-13 05:49
Fixed by https://github.com/godotengine/godot/pull/69961
