### ISSUE TITLE
Signal declared but never emitted error bug

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#24692] opened 2019-01-01 12:24 UTC
**Godot version:**
v3.1.alpha.official

**Issue description:**
connect("planet", self, "emit_signal", ["parameter"])
works where the method string refers to the Object method "emit_signal" but it generates an error message of "The signal 'planet' is declared but never emitted." But this signal is emitted.

**Minimal reproduction project:**
```gdscript
extends Spatial

signal planet

func _ready():
	for p in $Planets.get_children():
		p.connect("planet", self, "emit_signal", ["planet"])
		#p.connect("planet", self, "emit", ["planet"])

#Just some code to test the alternative way to do it
func emit(name, args = null):
	emit_signal(name, args)
```

**Comment by rodolforg** [comment] 2019-01-03 00:04
It is not explicitly called.
The static analyzer maybe can't solve this issue. Perhaps it should shows "The signal 'planet' is declared but seems to be never emitted."

Although I wonder why one would use so indirect call.

**Comment by timoschwarzer** [comment] 2019-01-03 12:07
@rodolforg 	The signal _is_ called.

```gdscript
p.connect("planet", self, "emit_signal", ["planet"])
```

This should "forward" the event "planet" if emitted by `p`.

**Comment by jsphpio** [comment] 2019-01-04 12:54
@rodolforg "Although I wonder why one would use so indirect call." My galaxy scene has planets that emit the "planet" signal when they are encountered by a space ship. It has a script that connects to it's planets signals. The Galaxy is one of many in a universe and it relays a "planet" signal to the Universe.

**Comment by akien-mga** [comment] 2019-01-14 11:24
It would be good to provide a complete reproduction project. Your script is quite confusing but as I understand it, you indeed never emit the `planet` signal declared in this script. You connect the `planet` signal of the `$Planets.get_children()` nodes (same script? can't know) to emit this script's `planet` signal recursively...

All in all it looks like an error in your scripting logic, but to know for sure we'd need a project that reproduces it (and ideally not reusing the same signal name in different scripts while trying to chainload them, which makes things hard to understand and error prone).

**Comment by akien-mga** [comment] 2021-07-23 21:25
No update in 18 months, so closing. Please comment if you can still reproduce this issue, and make sure to include a minimal reproduction project.

**Closed by akien-mga** 2021-07-23 21:25 UTC
Labels: bug, topic:core
