### ISSUE TITLE
Proximity Fade broken due to DEPTH_TEXTURE syntax change

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#71803] opened 2023-01-21 12:39 UTC
### Godot version

v4.0.beta14.official [28a24639c]

### System information

MacOS 13.1

### Issue description

Due to the removal of `DEPTH_TEXTURE` in https://github.com/godotengine/godot/pull/70967, there's a regression for the Proximity node in Visual Shaders and the Proximity Fade option in the StandardMaterial3D since they still use the old syntax

### Steps to reproduce

Open MRP or follow these steps:
1. create new 3D scene
2. add a MeshInstance3D node with a mesh
3. add a Custom Material and a Visual Shader for it
4. Add a Proximity node and connect it to `ALPHA` or `COLOR`

For the StandardMaterial Bug follow the above steps 1 and 2 but create a StandardMaterial3D and enable ProximityFade

### Minimal reproduction project

[shader-bug.zip](https://github.com/godotengine/godot/files/10472176/shader-bug.zip)

**Comment by akien-mga** [comment] 2023-01-21 13:05
This was already fixed by #71760.

**Comment by paddy-exe** [comment] 2023-01-21 14:59
@akien-mga This bug is also in the StandardMaterial3D. Your mentioned PR only fixes the visual shader node

**Comment by clayjohn** [comment] 2023-01-22 02:32
The old syntax isnt used in StandardMaterial3D, I have a feeling 
the StandardMaterial part of this issue is a duplicate of https://github.com/godotengine/godot/issues/71739 which was fixed by https://github.com/godotengine/godot/pull/71764

StandardMaterial was updated when DEPTH TEXTURE was removed: 
https://github.com/godotengine/godot/blob/c3539b4561f9b4d7dc4ba1c5859217e7fbf9c6fe/scene/resources/material.cpp#L1288

**Comment by Chaosus** [comment] 2023-01-22 06:54
@clayjohn Just interesting - `textureLod` with 0.0 Lod parameter, should be identical to `texture` by result, so using the `textureLod` here is doubtful?

**Comment by paddy-exe** [comment] 2023-01-22 15:33
@clayjohn then it must have been fixed after the point release of the beta 14

**Comment by clayjohn** [comment] 2023-01-22 17:29
Yes, #71764 was merged after beta 14

**Comment by paddy-exe** [comment] 2023-01-22 20:40
I will close this issue then

**Closed** 2023-01-22 20:40 UTC
Labels: bug, regression, topic:shaders
