### ISSUE TITLE
Shift key doesn't work in web export

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#74925] opened 2023-03-14 23:14 UTC
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Firefox 110.0, Linux

### Issue description

On web exports, inputs mapped to the shift key are not triggered. Nor does comparing `event.physical_keycode == KEY_SHIFT` work. For some reason though, `event.as_text()` still returns `Shift` on web.

This same issue seems to have been reported for Godot 2.1.3 but was closed without being resolved: https://github.com/godotengine/godot/issues/10120

### Steps to reproduce

- try to capture an input mapped to shift in a web exported project
- input doesn't register, other keys work as normal

### Minimal reproduction project

[MRP_shift_html5.zip](https://github.com/godotengine/godot/files/10974591/MRP_shift_html5.zip)
This project contains several different ways of detecting inputs. Should be useful to compare how editor/desktop/web builds react to shift keypresses.

**Comment by Rindbee** [comment] 2023-03-15 04:21
`Shift`, `Ctrl`, `Alt` seem to match the keycodes of their initials in web exports.

**Comment by akien-mga** [comment] 2023-03-15 06:46
Duplicate of #74415

**Closed by akien-mga** 2023-03-15 06:46 UTC
