### ISSUE TITLE
Script editor window getting over everything

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#7187] opened 2016-11-25 18:10 UTC
windows 10 godot 2.1

when you are editing a script then open another window(class help, project settings, etc) the script editor keep on top, making very hard to do anything.
If you change the tab from script to any other the problem is solved.

Start to editing a script, try to open another window, like project settings.

illustrative print of my screen
http://pasteboard.co/2gUaeBltd.png

**Comment by avril-gh** [comment] 2016-11-26 12:17
duplicate of https://github.com/godotengine/godot/issues/7156 `editor's text area overlaps windows when code completion popup is on`

**Comment by vnen** [comment] 2016-11-26 14:35
Closing as duplicate. FYI, this is fixed in master but haven't yet been fixed in the stable releases.

**Closed by vnen** 2016-11-26 14:35 UTC
Labels: archived
