### ISSUE TITLE
Godot 3.2.4 beta FBX support bug

### ISSUE THREAD

**Issue by baragd** [godotengine/godot#45119] opened 2021-01-12 04:05 UTC
I get just a spatial node !

Windows 10

When I do import in godot for any fbx file .. I get just a spatial node ( I do not think the problem is from blender )

FBX file :
https://drive.google.com/folderview?id=1WI523BakoxgcFkIyfX0_8ZqX16cvqQsJ

**Comment by Al-Shahrior** [comment] 2021-01-12 06:41
Hare is the console output
![image](https://user-images.githubusercontent.com/31450209/104278837-6e485980-54d3-11eb-805d-ce7f9ffd0a66.png)

**Comment by Al-Shahrior** [comment] 2021-01-12 06:49
I think for now you can use obj file. You can export obj file from blender. Hare is a screenshot.
![image](https://user-images.githubusercontent.com/31450209/104279459-89679900-54d4-11eb-9a54-e19ab02d5675.png)

**Comment by Zireael07** [comment] 2021-01-12 07:39
Literally what it says in the console - NOT a bug.

**Comment by Xrayez** [comment] 2021-01-13 21:21
Just because the message says it's not a bug, it doesn't mean it's not a bug.

I mean, the message does imply that it's possible to workaround the problem, and I understand that some things are difficult to resolve, but again I'd treat this as a bug.

I've seen a tendency with Godot development that certain bugs get "fixed" by documentation changes alone, it's a slippery slope... These kind of things should only be documented when there's really no way to fix the problem, and not because someone is lazy to fix a bug. 😛

**Comment by Calinou** [comment] 2021-01-13 22:16
@baragd @Al-Shahrior Try importing in Godot 3.2.5 beta 5: https://github.com/godotengine/godot/pull/44897

**Comment by baragd** [comment] 2021-01-19 04:46
@Calinou @Al-Shahrior 
Well it looks like the old problem has been solved

![bandicam 2021-01-19 06-26-58-163](https://user-images.githubusercontent.com/77251565/104988173-7a2ea100-5a28-11eb-928f-92c1889cf2a6.png)

The export from Blender without animation is excellent on Godot but with the animation it is horrible

![bandicam 2021-01-19 06-24-24-006](https://user-images.githubusercontent.com/77251565/104988342-e0b3bf00-5a28-11eb-89c0-f840a40ce35a.png)

The truth is I am interested in the fbx topic in this update because previously this was the old update mode

![bandicam 2021-01-19 06-30-41-210](https://user-images.githubusercontent.com/77251565/104988620-9bdc5800-5a29-11eb-9dc7-77bfa1a72124.png)

These bumps are much lighter in gltf, along with some other problems, so gltf are not a substitute for fbx for me.

**Comment by akien-mga** [comment] 2022-04-06 22:24
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Closed by akien-mga** 2022-04-06 22:24 UTC
Labels: bug, topic:import
