### ISSUE TITLE
Cropped and uninformative tooltips on scene tabs

### ISSUE THREAD

**Issue by voidexp** [godotengine/godot#30439] opened 2019-07-08 20:37 UTC
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Home v1809, AMD Ryzen 5 1600, nVidia GTX 1080 Ti (driver v430.86) 

**Issue description:**
With multiple scenes opened, while hovering over the scene tabs, a cropped and highly uninformative rectangular tooltips appear:

![tooltip_bug](https://user-images.githubusercontent.com/595098/60840575-7df92a80-a1d8-11e9-86a6-b4fc1fc51739.png)
![tooltip_bug_2](https://user-images.githubusercontent.com/595098/60840576-7e91c100-a1d8-11e9-87b3-be4046dc1a11.png)

**Steps to reproduce:**
1) Create a project with multiple scenes with some visual elements (the "Your first game" tutorial project will work fine)
2) Open multiple scenes
3) Move the mouse over inactive scene tab

*What happens:* cropped tooltip appears
*What is expected*: a tooltip with the overview of the whole scene

**Minimal reproduction project:**
[godot-demo.zip](https://github.com/godotengine/godot/files/3370104/godot-demo.zip)

**Comment by sparkart** [comment] 2019-08-08 10:05
Right now the intended behavior is to preview the viewport of the scene when it was last saved, not the entire scene. That expected behavior does not work correctly as it does some weird cropping.

What I'm wondering is if it is better to fix the intended behavior or change it completely to view the entire scene, as I would imagine it could become useless in very large scenes where it scales it so tiny. In my opinion, being able to control how the thumbnail looks by setting the editor's viewport in the scene and then saving seems to be more beneficial than a one size fits all solution of saving the entire scene.

**Comment by Calinou** [comment] 2019-11-16 21:27
We could get better previews by making the user place an (optional) camera node that will only be used for editor previews. This has the upside of providing a more consistent result, at the cost of requiring some manual work.

If no camera node is present, the current viewport will be used for the preview (like currently).

**Comment by KoBeWi** [comment] 2024-12-26 12:26
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7232

**Closed by KoBeWi** 2024-12-26 12:26 UTC
Labels: bug, topic:editor, confirmed
