### ISSUE TITLE
High DPI in WebGL unsupported, causes incorrect mouse position calculation

### ISSUE THREAD

**Issue by kroltan** [godotengine/godot#29725] opened 2019-06-12 17:40 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10 Pro, and Android 9.0

**Issue description:**
WebGL builds do not take into account non-unit scales such as in high-density mobile or desktop screens.

I attempted to manually scale the canvas in accordance to `window.devicePixelRatio` (see snippet below), which corrects the resolution issue perfectly, but causes incorrect mouse coordinate calculations within the engine.

```js
var ratio = window.devicePixelRatio || 1;
var width = window.innerWidth;
var height = window.innerHeight;
canvas.width = width * ratio;
canvas.height = height * ratio;
canvas.style.width = width;
canvas.style.height = height;
```

**Steps to reproduce:**
 1. Create a project, set up a simple UI main scene with some buttons scattered around.
 2. Export to WebGL, and visit the resulting page on a hidpi screen (mobile or desktop)
 3. Observe that it is rather blurry.
 4. Make a new export using [this HTML shell](https://gist.github.com/kroltan/f84319ed8e5661b27972f6326e85a558), which contains the resolution-correction snippet above.
 5. Observe that the resolution is perfect, but mouse coordinates appear scaled such that only the topleftmost `1/ratio` portion of the screen can be interacted with.

For example, if the pixel ratio is 2, clicking on the visual screen's bottom right (`(width, height)`) will translate to a click in the center of the screen (`(width / 2, height / 2)`)

(If you do not have a high DPI screen, the issue can be faked by opening your browser's devtools and running `devicePixelRatio = 2`)

**Minimal reproduction project:**
[godot-hidpi-bug.zip](https://github.com/godotengine/godot/files/3282533/godot-hidpi-bug.zip)

I've made a simple script that draws dots where a mouse click is detected. Simply open a build with both shells, open it in a browser and click around the game screen.

**Comment by scottkunkel** [comment] 2019-06-12 19:25
same as
https://github.com/godotengine/godot/issues/29661

**Comment by kroltan** [comment] 2019-06-12 20:51
You are correct. Sorry for the duplicate.

**Comment by akien-mga** [comment] 2019-06-12 20:54
Closing as duplicate of #29661 then, I pasted the link to the MRP there.

**Closed by akien-mga** 2019-06-12 20:54 UTC
Labels: bug, platform:html5, topic:porting, topic:rendering

**Comment by scottkunkel** [comment] 2019-06-12 21:07
Thank you for providing the project, though :-)
