### ISSUE TITLE
Custom resource only able to be inherited from script after editor restart

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#37927] opened 2020-04-16 08:05 UTC
**Godot version:**
3.2 stable

**OS/device including version:**
Win 10 1903

**Issue description:**
After you create a script that inherits resource, give it a class name, and save it, it is not available from the 'New Resource' dialog until after the editor is restarted.

**Steps to reproduce:**
New Project
Add Script
```
class_name MyNewResource
extends Resource

export (String) var thing
```
Save script
Right click in FileSystem -> New Resource
Search for your class, it's not there
Restart Editor
Right click in FileSystem -> New Resource
Now it is there.

**Minimal reproduction project:**
As Above

Is there a refresh asset database method or something? Any ideas on where to look to resolve this?

**Comment by Calinou** [comment] 2020-04-16 08:24
> Is there a refresh asset database method or something? Any ideas on where to look to resolve this?

Try saving the scene then use **Scene > Revert Scene** at the top of the editor. You can bind it to a shortcut in the Editor Settings if you plan on using it often.

**Comment by EricEzaM** [comment] 2020-04-16 08:36
I couldn't find any docs on 'Revert Scene', are they any details on what exactly it does? I know about how you can revert properties with the little grey arrow on the property editor. How does this expand to a scene level? Or is the same word used for different meaning?

**Comment by Calinou** [comment] 2020-04-16 09:43
Revert Scene basically reloads the current scene without closing the editor. It's functionally equivalent to closing the scene then reopening it.

**Comment by EricEzaM** [comment] 2020-04-16 14:19
@Calinou No go unfortunately... Revert Scene has no effect, restarting the editor still resolves it. I'll try look into it. Any hints for where to look appreciated.

**Comment by EricEzaM** [comment] 2020-04-16 23:22
Update on this one, seems to only occur when using an external editor, as I am with VS Code. When I turn off the external editor in Editor Settings and use the built-in one, it works fine, and the resources are able to be created as soon as I save the script file.

**Comment by EricEzaM** [comment] 2020-04-17 05:16
Any reason why this button is hidden? Enabling this button and then clicking it resolves the issue without editor restart. It's all set up and ready to go... just needs to be shown!

https://github.com/godotengine/godot/blob/30ab5c9baae1cad3e157d906395a4eb8cef77e42/editor/filesystem_dock.cpp#L2513-L2519

**Comment by Calinou** [comment] 2020-04-17 08:20
@EricEzaM It's probably intended as a debugging option and should normally not be needed. However, I think it makes sense to expose it given the number of bugs related to external editors right now. Feel free to open a pull request :slightly_smiling_face:

**Comment by Calinou** [comment] 2020-04-29 12:33
Duplicate of #24633.

**Closed by Calinou** 2020-04-29 12:33 UTC
