### ISSUE TITLE
Resources derived classes created in C# doesnt appear in Resource Window

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45390] opened 2021-01-23 15:03 UTC
**Godot version:**
3.2.4 beta 6 Mono

**OS/device including version:**
Windows 10 x64

**Issue description:**
When te user creates a new Resource derived class, it doesnt appear in resource window
![image](https://user-images.githubusercontent.com/58845030/105598032-e4ba4680-5d72-11eb-9ac7-85ed43cc5631.png)

**Steps to reproduce:**
Create a new Resource derived class:
![image](https://user-images.githubusercontent.com/58845030/105598235-f3a0f900-5d72-11eb-941e-83eda78b2555.png)
Click Build
Open "Create new Resource" window

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2021-01-23 15:15
Doesn't this feature depend on https://github.com/godotengine/godot/pull/44879?

**Comment by nonunknown** [comment] 2021-01-23 15:16
yes!

**Comment by Calinou** [comment] 2021-01-23 15:32
Duplicate of https://github.com/godotengine/godot/issues/27470.

**Closed by Calinou** 2021-01-23 15:32 UTC
Labels: topic:editor, topic:mono
