### ISSUE TITLE
Android APK "damaged" when exported without debug

### ISSUE THREAD

**Issue by WouterB15** [godotengine/godot#17572] opened 2018-03-16 21:20 UTC
Well I've searched for this for ages around on the internet with no succes, so I'm just going to make a post about it. Most of the posts I did find were all of Godot 2.0 and solutions were suggested with options that are not a thing with Godot 3.0.2 anymore (the version I'm using).

So whenever I try to install the APK (transferred to my phone by USB and Google Drive) it says the APK "seems damaged". This only happens when I export it without debug. Everything works fine when I export with debug.
The phone I'm using at this moment is an Honor 8 Lite. It runs Android 7.0 and Emui 5.0.

How do I fix this issue?

**Comment by akien-mga** [comment] 2018-04-06 05:46
I can't reproduce this. Do you have a release.keystore properly configured?

**Comment by WouterB15** [comment] 2018-04-09 15:26
Now that you say that, I noticed I did not have a release.keystore. Only a debug.keystore. If I look up how to make a release.keystore it never works for me. How would I do that?

**Comment by volzhs** [comment] 2018-04-09 15:47
you can see better logs if run editor on terminal.
is there any suspicious message on terminal when exporting?

**Comment by WouterB15** [comment] 2018-04-09 15:51
This is the most suspicious I can find:
```
*******************GORRRGLE***********************
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
unicode error: invalid skip
```

**Comment by volzhs** [comment] 2018-04-09 16:08
there should be more logs like this...

```
exporting res://Control.tscn
exporting res://default_env.tres
0 param: --use_depth_32
1 param: --use_immersive
   adding: META-INF/MANIFEST.MF
   adding: META-INF/ANDROIDD.SF
   adding: META-INF/ANDROIDD.RSA
  signing: AndroidManifest.xml
  signing: build-data.properties
  signing: classes.dex
  signing: error_prone/Annotations.gwt.xml
  signing: jsr305_annotations/Jsr305_annotations.gwt.xml
  signing: lib/armeabi-v7a/libgodot_android.so
  signing: protobuf.meta

... keep signing many files...

  signing: assets/project.binary
  signing: assets/_cl_
jar signed.

... and more logs...
```

**Comment by WouterB15** [comment] 2018-04-09 16:09
It seems like you meant the log of signing the keystore?

**Comment by volzhs** [comment] 2018-04-09 16:13
your logs is ended with `0 param: --use_depth_32`
but there should be logs for signing files and much more after that.

**Comment by WouterB15** [comment] 2018-04-09 16:17
I left the custom packaged empty(because it asked for an APK), the extra arguments I left empty(I didn't know what should be there, and I used Armeabi-V 7a as the architecture(because I don't know what it changes). I have no clue if that affects that?

**Comment by WouterB15** [comment] 2018-04-11 20:30
So now it does give a proper command output:
`jarsigner: Certificate chain not found for: .   must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.`
I've tried fixing it but I don't know how.

**Comment by seyacat** [comment] 2018-04-16 15:02
I have same problem, resolve check filenames, i have filenames with "ñ" and with "-", remove this characters solve the problem.
Take care use only A-z characters an no spaces on filenames

**Comment by WouterB15** [comment] 2018-04-16 18:52
> I have same problem, resolve check filenames, i have filenames with "ñ" and with "-", remove this characters solve the problem.
Take care use only A-z characters and no spaces on filenames

Thank you for your suggestion, but it still doesn't work. I still get the same problem:
```
running cmdline: "C:/GameDev/jdk-9.0.4/bin/jarsigner.exe" "-digestalg" "SHA1" "-sigalg" "MD5withRSA" "-verbose" "-keystore" "C:/Users/-----/.android/release.keystore" "-storepass" "android" "C:\Users\-----\AppData\Local\Temp/Godot/tmpexport-unaligned.apk" ""
jarsigner: Certificate chain not found for: .   must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.
running cmdline: "C:/GameDev/jdk-9.0.4/bin/jarsigner.exe" "-verify" "-keystore" "C:/Users/-----/.android/release.keystore" "C:\Users\-----\AppData\Local\Temp/Godot/tmpexport-unaligned.apk" "-verbose"

  s = signature was verified
  m = entry is listed in manifest
  k = at least one certificate was found in keystore

no manifest.

jar is unsigned.
```

**Comment by muzir** [comment] 2018-08-12 13:11
I have same problem, and @seyacat comment help me to address the problem. My problem is some of the direction png files names contains spaces like "up button.png", "down button.png", I remove the spaces and problem is solved.

**Comment by sturm30** [comment] 2019-09-29 07:52
> I have same problem, and @seyacat comment help me to address the problem. My problem is some of the direction png files names contains spaces like "up button.png", "down button.png", I remove the spaces and problem is solved.

That fixed my problem. This is exactly the step-to-reproduce for this bug.

**Comment by Calinou** [comment] 2019-09-29 12:46
@sturm30 Since this appears to be handled by jarsigner, is this something we can fix on our side?

**Comment by sturm30** [comment] 2019-10-01 20:11
Well, I actually am just a Godot user. I am a software developer and an IT bachelor but I am not in "the dark side", if you know what I mean.
In any case, I suggest to write a note onto the documentation page: https://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_android.html
Describing the situation. I am new on github, I know this could not be the correct place to write such a suggestion ... but i can't find any better.

**Comment by KoBeWi** [comment] 2020-11-01 23:52
I remember having similar issue with unicode characters in file names. This doesn't look documented yet, so the issue is likely still valid in 3.2.3.

Since it's more a documentation issue, should we transfer it?

**Comment by akien-mga** [comment] 2020-11-02 07:08
I don't know if that should be documented, it sounds like a bug to me. I can't imagine that jarsigner would never be able to sign a jar with filenames containing spaces, that's a pretty big limitation for Android otherwise.

**Comment by m4gr3d** [comment] 2021-01-05 09:10
Closing as the original issue seems to have been tied to a misconfigured release keystore.

**Closed by m4gr3d** 2021-01-05 09:10 UTC
Labels: bug, confirmed, discussion, platform:android, topic:porting
