### ISSUE TITLE
print(5.0) shows no indication that the value is a float

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#6361] opened 2016-09-01 09:04 UTC
**Operating system or device - Godot version:**
Linux X11; Debian Testing
Godot 2.1

**Issue description** (what happened, and what was expected):

```
func _ready():
    print(5.0)
```

output:

```
5
```

expected output:

```
5.0
```

---

This also has knock-on consequences for producing misleading error messages, such as dict-lookup errors:

```
var data = {5: 'hello'}
print(data[5.0])

---
Invalid get index '5' (on base: 'Dictionary').
```

**Comment by supaiku-o** [comment] 2016-09-02 12:18
It's a one-liner, but it will cause so much grief, when all the code logic breaks.
(at least for me, because I don't cast any json number to int)

```diff
diff --git a/core/variant.cpp b/core/variant.cpp
index a78c07d..3b04d59 100644
--- a/core/variant.cpp
+++ b/core/variant.cpp
@@ -1513,7 +1513,7 @@ Variant::operator String() const {
                case NIL: return "";
                case BOOL: return _data._bool ? "True" : "False";
                case INT: return String::num(_data._int);
-               case REAL: return String::num(_data._real);
+               case REAL: return String::num_real(_data._real);
                case STRING: return *reinterpret_cast<const String*>(_data._mem);
                case VECTOR2: return "("+operator Vector2()+")";
                case RECT2: return "("+operator Rect2()+")";

**Comment by Noshyaar** [comment] 2018-04-06 09:51
Reproducible in 3.1 master 9ad1800

**Comment by Calinou** [comment] 2020-06-18 14:31
Closing in favor of https://github.com/godotengine/godot-proposals/issues/465, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2020-06-18 14:31 UTC
Labels: enhancement, topic:gdscript
