### ISSUE TITLE
Export node array don't allow to assign a value in the editor

### ISSUE THREAD

**Issue by XenokNyx** [godotengine/godot#72906] opened 2023-02-08 17:36 UTC
### Godot version

4.0 rc1, Beta 17

### System information

Windows 10

### Issue description

A export variable of type Array[node] appear in the editor and everything seems to work but when assigning a node the array doesn't update and keep all it's values at null.

![NodeArray](https://user-images.githubusercontent.com/6534007/217607581-ed3d2fe9-f837-47a5-9cbd-13aafcb56947.PNG)

### Steps to reproduce

Create a script with 
`@export var nodes : Array[Node]`
or `[Export] Node[] nodeArray;` in C#

Try to assign a value in the editor.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-02-08 17:38
Duplicate of https://github.com/godotengine/godot/issues/62916.

**Comment by YuriSizov** [comment] 2023-02-08 19:14
Yep.

**Closed by YuriSizov** 2023-02-08 19:14 UTC
