### ISSUE TITLE
**ERROR**:  does not have a library for the current platform - GDNative on iOS, Godot 3.0 Beta 2

### ISSUE THREAD

**Issue by haxpor** [godotengine/godot#15476] opened 2018-01-08 03:23 UTC
**Godot version:**

* Godot 3.0 Beta 2 official
* C++ GDNative in question that I tested was built for macOS (x86_64), and iOS (arm64, armv7, armv7s). The latter is a single fat binary.

I tested it successfully with macOS, but faced with error for iOS.

I included 2 projects to test this issue out
1. Godot project which includes with built libraries for both platform in question
2. Exported iOS project with further build settings setup (steps included at the end of this issue)

**OS/device including version:**
* iOS 11.2.5
* macOS 10.13

**Issue description:**
Create a simple GDNative in C++, then integrate with Godot project. Try to export into iOS project using an updated & fixed iOS export template found [here](https://github.com/godotengine/godot/issues/15203#issuecomment-355818086). Built and run project successfully on iOS device, but then during run-time it shows error as follows

```
2018-01-08 07:57:08.876729+0800 ios-export[1646:597846] [DYMTLInitPlatform] platform initialization successful
*********** main.m
running app main
2018-01-08 07:57:11.569809+0800 ios-export[1646:597729] +[CATransaction synchronize] called within transaction
after init super 0x104d0a300
2018-01-08 07:57:11.769958+0800 ios-export[1646:597729] Metal GPU Frame Capture Enabled
2018-01-08 07:57:11.776568+0800 ios-export[1646:597729] Metal API Validation Enabled
******** screen size 640, 1136
after init gles 0x104d0a300
******** adding observer for sound routing changes
******** adding observer for keyboard show/hide
glview is 0x104d0a300
Path: /var/containers/Bundle/Application/2F76ED70-16B6-42B3-BEDE-D4B11A5C7789/ios-export.app
godot_iphone /var/containers/Bundle/Application/2F76ED70-16B6-42B3-BEDE-D4B11A5C7789/ios-export.app/ios-export
cwd /private/var/containers/Bundle/Application/2F76ED70-16B6-42B3-BEDE-D4B11A5C7789/ios-export.app
os created
setting data dir to /var/mobile/Containers/Data/Application/C7E48CA1-B536-4BEB-9E40-51C6DFAB79E6/Documents from /var/mobile/Containers/Data/Application/C7E48CA1-B536-4BEB-9E40-51C6DFAB79E6/Documents
setup 0
cadisaplylink: 1start animation!
******** screen size 640, 1136
2018-01-08 07:57:12.137619+0800 ios-export[1646:597729] +[CATransaction synchronize] called within transaction
2018-01-08 07:57:12.140697+0800 ios-export[1646:597729] +[CATransaction synchronize] called within transaction
2018-01-08 07:57:12.147198+0800 ios-export[1646:597729] +[CATransaction synchronize] called within transaction
2018-01-08 07:57:12.202078+0800 ios-export[1646:597729] OpenGL ES 3.0 Renderer: Apple A9 GPU
OpenGL ES 3.0 Renderer: Apple A9 GPU
2018-01-08 07:57:12.210221+0800 ios-export[1646:597729] GLES3: max ubo light: 102
GLES3: max ubo light: 102
2018-01-08 07:57:12.210376+0800 ios-export[1646:597729] GLES3: max ubo reflections: 113, ubo size: 144
GLES3: max ubo reflections: 113, ubo size: 144
2018-01-08 07:57:12.349320+0800 ios-export[1646:597729] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-01-08 07:57:12.350798+0800 ios-export[1646:597729] [MC] Reading from public effective user settings.
2018-01-08 07:57:12.542211+0800 ios-export[1646:597729] ARVR: Registered interface: Native mobile
ARVR: Registered interface: Native mobile
2018-01-08 07:57:12.629283+0800 ios-export[1646:597729] **ERROR**: Condition ' status != 0x8CD5 ' is true.
2018-01-08 07:57:12.629323+0800 ios-export[1646:597729]    At: drivers/gles3/rasterizer_storage_gles3.cpp:6334:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
**ERROR**: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6334:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
2018-01-08 07:57:12.630568+0800 ios-export[1646:597729] **ERROR**: Condition ' status != 0x8CD5 ' is true.
2018-01-08 07:57:12.630594+0800 ios-export[1646:597729]    At: drivers/gles3/rasterizer_storage_gles3.cpp:6334:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
**ERROR**: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6334:_render_target_allocate() - Condition ' status != 0x8CD5 ' is true.
2018-01-08 07:57:12.741109+0800 ios-export[1646:597729] **ERROR**:  does not have a library for the current platform
2018-01-08 07:57:12.741181+0800 ios-export[1646:597729]    At: modules/gdnative/nativescript/nativescript.cpp:995:init_library() - Condition ' lib_path.length() == 0 ' is true.
**ERROR**:  does not have a library for the current platform
   At: modules/gdnative/nativescript/nativescript.cpp:995:init_library() - Condition ' lib_path.length() == 0 ' is true.
2018-01-08 07:57:12.743976+0800 ios-export[1646:597729] **SCRIPT ERROR**: Attempt to call function 'new' in base 'NativeScript' on a null instance.
2018-01-08 07:57:12.744023+0800 ios-export[1646:597729]    At: <built-in>:3:_ready() - Attempt to call function 'new' in base 'NativeScript' on a null instance.
**SCRIPT ERROR**: Attempt to call function 'new' in base 'NativeScript' on a null instance.
   At: <built-in>:3:_ready() - Attempt to call function 'new' in base 'NativeScript' on a null instance.
2018-01-08 07:57:13.227255+0800 ios-export[1646:597729] [Error] setCurrentGameFromInternal: ignoring -- nil bundleIdentifier :(null)
2018-01-08 07:57:13.331679+0800 ios-export[1646:597729] [Error] _authenticateUsingAlert:Faied to authenticate player with existing credentials.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognized by Game Center." UserInfo={GKServerStatusCode=5019, NSLocalizedDescription=The requested operation could not be completed because this application is not recognized by Game Center., NSUnderlyingError=0x1c445e390 {Error Domain=GKServerErrorDomain Code=5019 "status = 5019, no game matching descriptor: ios:org.godotengine.iosgame2:1.0:1.0+-1" UserInfo={GKServerStatusCode=5019, NSLocalizedFailureReason=status = 5019, no game matching descriptor: ios:org.godotengine.iosgame2:1.0:1.0+-1}}}
2018-01-08 07:57:13.362115+0800 ios-export[1646:597729] [Error] startAuthenticationForExistingPrimaryPlayer:Failed to Authenticate player.Error: Error Domain=GKErrorDomain Code=15 "The requested operation could not be completed because this application is not recognized by Game Center." UserInfo={NSLocalizedDescription=The requested operation could not be completed because this application is not recognized by Game Center.}

```

From full log above, the relevant part is as follows

```
2018-01-08 07:57:12.741109+0800 ios-export[1646:597729] **ERROR**:  does not have a library for the current platform
2018-01-08 07:57:12.741181+0800 ios-export[1646:597729]    At: modules/gdnative/nativescript/nativescript.cpp:995:init_library() - Condition ' lib_path.length() == 0 ' is true.
**ERROR**:  does not have a library for the current platform
   At: modules/gdnative/nativescript/nativescript.cpp:995:init_library() - Condition ' lib_path.length() == 0 ' is true.
2018-01-08 07:57:12.743976+0800 ios-export[1646:597729] **SCRIPT ERROR**: Attempt to call function 'new' in base 'NativeScript' on a null instance.
2018-01-08 07:57:12.744023+0800 ios-export[1646:597729]    At: <built-in>:3:_ready() - Attempt to call function 'new' in base 'NativeScript' on a null instance.
**SCRIPT ERROR**: Attempt to call function 'new' in base 'NativeScript' on a null instance.
   At: <built-in>:3:_ready() - Attempt to call function 'new' in base 'NativeScript' on a null instance.
```

If things run properly, it should print out followings

```
test
1
True
```

and shows Godot sprite on screen. If not, it should not print anything, and Godot sprite wouldn't show on screen.

**Steps to reproduce:**
* Try to run Godot project (see attached file) on macOS first to see whether it works
* You can directly open attached exported Xcode project then run on iOS device to see the problem, or try to re-export iOS project from Godot editor again.
* If you re-export from editor, you need to configure the following for Xcode project
   * Click on project name at Project Navigator panel, then click on General. At *Embedded Binaries*, add `libsimple_library_ios_fat.dylib` for both of occurrences.
   * At build settings, search for `Library Search Paths`, then add `$(SRCROOT)/ios-export/dylibs/simple_library` (this will allow compilation process to succeed, and be able to find our shared library as copied into `dylibs/simple_library` automatically by exporting process).
   * At build settings again, search for `Runpath Search Paths`, then add `@executable_path/Frameworks` (for some reason, I need this to be able to successfully initialize Godot at startup. If not, it crashes even before Godot'd be loaded).
* Run the project.
* You will see the error log like above, and see no expected results printed or any Godot sprite on screen.

**Minimal reproduction project:**
* [Godot project](https://internal.abzi.co/godot/ExportedXcodeProject.tar.gz)
* [Exported Xcode Project](https://internal.abzi.co/godot/GodotProject.tar.gz)

**Edit**
I included information from executing `otool -L libsimple_library_ios_fat.dylib` here as well as reference. I have to set it to `@rpath/libsimple_library_ios_fat.dylib` via `install_name_tool` command in order to let linking step be able to find and pass through.

```
libsimple_library_ios_fat.dylib (architecture armv7):
	@rpath/libsimple_library_ios_fat.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
libsimple_library_ios_fat.dylib (architecture armv7s):
	@rpath/libsimple_library_ios_fat.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
libsimple_library_ios_fat.dylib (architecture arm64):
	@rpath/libsimple_library_ios_fat.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.1)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

**Comment by akien-mga** [comment] 2018-01-08 07:23
CC @karroffel @endragor

**Comment by haxpor** [comment] 2018-01-08 09:08
Further investigated, I found out that `.dylib` should not be used directly inside iOS (macOS is ok) as per stated on https://developer.apple.com/library/content/technotes/tn2435/_index.html. I'm currently using this approach in test project above.

![screen shot 2018-01-08 at 4 45 22 pm](https://user-images.githubusercontent.com/673757/34663982-7f05af36-f494-11e7-91de-124a722c15c4.png)

So this leaves me 2 options to try
1. Try to convert `.dylib` to be in framework bundle format
2. If 1. didn't work, then statically build a binary with Godot engine instead

I checked at engine code regarding to `**ERROR**:  does not have a library for the current platform` and as communicated with a user in discord, such path should be set by Godot prior to exporting. 

Inside [nativescript.cpp](https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L998-L1001) as follows
```
// See if this library was "registered" already.
	const String &lib_path = lib->get_current_library_path();
	ERR_EXPLAIN(lib->get_name() + " does not have a library for the current platform");
	ERR_FAIL_COND(lib_path.length() == 0);
```

there are no paths information at all presented that led to my issue.

Although 1. above is an option to try but as there are no paths information available, I wonder whether **statically** build a binary is only a way to go (see [here](https://github.com/godotengine/godot/issues/15183#issuecomment-354547097) as well for suggestion to go with static linking) ?

**Comment by karroffel** [comment] 2018-01-08 15:23
On iOS it's intended that you use static linking. I am not sure how the workflow is exactly, but @endragor should know more about that.

The PR that added the iOS GDNative exporting is #11783

**Comment by endragor** [comment] 2018-01-11 10:11
@haxpor so continuing the discussion from #11783 as this is a more appropriate place: could you confirm that you build .a library for iOS and specify it in your .gdnlib file? It should work just fine as long as the library doesn't hide symbols required by Godot: `godot_nativescript_init`, `godot_gdnative_init`, etc.

**Comment by haxpor** [comment] 2018-01-11 11:04
Yes, I built it as `.a`. and specified them in `.gdnlib` as well as check whether template binary is the correct one.

This is my `SConstruct` for GDNative. I built with `scons platform=ios use_llvm=yes dynamic=no`
<details>
<summary>SConstruct to bulid GDNative</summary>

```python
#!python
import os, subprocess

def sys_exec(args):
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
    (out, err) = proc.communicate()
    return out.rstrip("\r\n").lstrip()

platform = ARGUMENTS.get("platform", ARGUMENTS.get("p", "osx"))
target = ARGUMENTS.get("target", "debug")
godot_headers_path = ARGUMENTS.get("headers", os.getenv("GODOT_HEADERS", "/Volumes/Slave/Downloads/godot-3.0-dev/modules/gdnative/include/"))
godot_bindings_path = ARGUMENTS.get("cpp_bindings", "cpp_bindings/")
dynamic = ARGUMENTS.get("dynamic", "yes")

# This makes sure to keep the session environment variables on windows, 
# that way you can run scons in a vs 2017 prompt and it will find all the required tools
env = Environment()
if platform == "windows":
    env = Environment(ENV = os.environ)
elif platform == "ios":
    SDK_MIN_VERSION = "8.0"
    # we could do better to automatically find the right sdk version
    SDK_VERSION = "11.2"
    IOS_PLATFORM_SDK = sys_exec(["xcode-select", "-p"]) + "/Platforms"
    env["CXX"] = sys_exec(["xcrun", "-sdk", "iphoneos", "-find", "clang++"])

if ARGUMENTS.get("use_llvm", "no") == "yes" and platform != "ios":
    env["CXX"] = "clang++"

# put stuff that is the same for all first, saves duplication
cpp_bindings_libname = 'libgodot_cpp_bindings_%s.a' % platform
if platform == "osx":
    env.Append(CCFLAGS = ['-g','-O3', '-std=c++14', '-arch', 'x86_64'])
    env.Append(LINKFLAGS = ['-arch', 'x86_64', '-framework', 'Cocoa', '-Wl,-undefined,dynamic_lookup'])
elif platform == "ios":
    env.Append(CCFLAGS = ['-g','-O3', '-std=c++11', '-arch', 'arm64', '-arch', 'armv7', '-arch', 'armv7s', '-isysroot', '%s/iPhoneOS.platform/Developer/SDKs/iPhoneOS%s.sdk' % (IOS_PLATFORM_SDK, SDK_VERSION) , '-miphoneos-version-min=%s' % SDK_MIN_VERSION])
    env.Append(LINKFLAGS = ['-arch', 'arm64', '-arch', 'armv7', '-arch', 'armv7s', '-isysroot', '%s/iPhoneOS.platform/Developer/SDKs/iPhoneOS%s.sdk' % (IOS_PLATFORM_SDK, SDK_VERSION) , '-miphoneos-version-min=%s' % SDK_MIN_VERSION, '-Wl,-undefined,dynamic_lookup'])
elif platform == "linux":
    env.Append(CCFLAGS = ['-g','-O3', '-std=c++14', '-Wno-writable-strings'])
    env.Append(LINKFLAGS = ['-Wl,-R,\'$$ORIGIN\''])
elif platform == "windows":
    if target == "debug":
        env.Append(CCFLAGS = ['-EHsc', '-D_DEBUG', '/MDd'])
    else:
        env.Append(CCFLAGS = ['-O2', '-EHsc', '-DNDEBUG', '/MD'])
    env.Append(LINKFLAGS = ['/WX'])
    cpp_bindings_libname = 'godot_cpp_bindings'

def add_sources(sources, dir):
    for f in os.listdir(dir):
        if f.endswith(".cpp"):
            sources.append(dir + "/" + f)

env.Append(CPPPATH=[godot_headers_path, godot_bindings_path + 'include/', godot_bindings_path + 'include/core/' ])

env.Append(LIBS=[cpp_bindings_libname])
env.Append(LIBPATH=[ godot_bindings_path + 'bin/' ])

sources = []
add_sources(sources, "src")

def change_id(self, arg, env):
    sys_exec(["install_name_tool", "-id", "@rpath/libsimple_library_%s.dylib" % platform, "bin/libsimple_library_%s.dylib" % platform])

# determine to link as shared or static library
if dynamic == "yes":
    library = env.SharedLibrary(target='bin/simple_library_%s' % platform, source=sources)
else:
    library = env.StaticLibrary(target="bin/simple_library_%s" % platform, source=sources)

# can't figure it out what type of parameter should be at 1st one
# send in '' and it works
if dynamic == "yes":
    change_id_action = Action('', change_id)
    AddPostAction(library, change_id_action)
    Default(library)
```
</details>

**Comment by endragor** [comment] 2018-01-11 12:33
@haxpor not sure if I can help without a sample project. Statically linking GDNative library on iOS does work for me with latest Godot. My guess is that there is a configuration problem lurking somewhere, but it's hard to say without a full project. Can you check that your .a file exists within the folder created during iOS export? Should be under `<export_name>/<path_to_your_lib_in_resources>/<lib_name>.a`.

**Comment by haxpor** [comment] 2018-01-11 18:53
Thank you so much!

I did check and confirm that `.a` is present and linked during compiled. In this case, I have to add `Library search path` for Xcode to be able to find with value of `@(SRCROOT)/ios-export/simple_library`.

Sample projects are as follows.
**Note** I didn't include result binary in GDNative project, but included all without any files ignored in exported Xcode project, so you can just hit run.

* Repository to GDNative library, SimpleLibrary: [on bitbucket](https://bitbucket.org/haxpor/godot-3.0-beta2-cpp-custom-module)
* Exported xcode project (I did 2 level compression in order to upload here, unzip first, then use `tar xvf exportedXcodeproject.tar.xz`: 
[exportedXcodeproject.tar.xz.zip](https://github.com/godotengine/godot/files/1623747/exportedXcodeproject.tar.xz.zip)

**Comment by endragor** [comment] 2018-01-20 06:52
@haxpor you need to wrap your entry point declarations into `extern "C" {}`  section. If you use official bindings, I guess those should be updated? Or if the user is supposed to define those entry points, then README should be updated. Wondering how it worked for you on macOS though... /cc @karroffel

**Comment by karroffel** [comment] 2018-01-20 09:21
Oh yes, README needs updating but the demo projects are up to date

**Comment by akien-mga** [comment] 2019-01-19 16:08
What's the state on this issue?

**Comment by vini-guerrero** [comment] 2019-04-26 07:20
Does anyone have an example on how to specify the .a library in the .gdnlib file? E.g. Where (method) it should be and how to send/receive params for/from the .a lib? (Should we use call_deferred in this case as well?)

**Comment by KoBeWi** [comment] 2020-09-29 08:43
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by Calinou** [comment] 2020-12-19 15:59
I'll close this as nobody else has been able to reproduce this recently.

**Closed by Calinou** 2020-12-19 15:59 UTC
Labels: bug, platform:ios, topic:gdnative, topic:porting

**Comment by Flash1232** [comment] 2021-01-28 00:05
Not sure if this is a misconfiguration of mine and at all related to this issue - but whenever I export my barely started project on Linux and there are the Godot Git plugin libraries in the project root, I get:
```
ERROR: initialize: No library set for this platform
   At: modules/gdnative/gdnative.cpp:290.
```
Everything seems to work fine though. Just the error is there. If I remove just the two git_api.* files, no error message there. I also tried excluding the files from the export dialog but that doesn't help.

**Comment by knochenhans** [comment] 2021-03-28 19:58
> ```
> ERROR: initialize: No library set for this platform
>    At: modules/gdnative/gdnative.cpp:290.
> ```

Exactly the same problem with the same conditions here with Godot v3.3.rc6 under Arch Linux.

**Comment by Calinou** [comment] 2021-03-28 20:44
@knochenhans Since this issue is very old by now, I'd advise opening a new issue with a minimal reproduction project attached.
