### ISSUE TITLE
Extraneous lines when saving a Custom Resource that iterates dictionary or array in a parent class

### ISSUE THREAD

**Issue by dandeliondino** [godotengine/godot#74020] opened 2023-02-27 03:15 UTC
### Godot version

4.0-rc5-official

### System information

Windows 11

### Issue description

ResourceSaver.save() creates extra lines of " = null" when saving a custom resource that iterates a dictionary/array that is defined in a parent class. This prevents future loading of the saved resource file.

Notes:
- simply referencing the dictionary or array does not cause these extraneous lines, they must be iterated (even if the function iterating them is never called)
- duplicating the parent-defined dictionary or array, even with a deep copy, and iterating the duplicate still results in extraneous lines

main.gd
```
func _ready() -> void:
	var parent_resource := ParentResource.new()
	var child_resource := ChildResource.new()
	
	print("result=", ResourceSaver.save(parent_resource, "user://parent_resource.tres"))
	print("result=", ResourceSaver.save(child_resource, "user://child_resource.tres"))

	var _loaded_parent_resource := load("user://parent_resource.tres")
	var _loaded_child_resource := load("user://child_resource.tres")
```

parent_resource.gd
```
class_name ParentResource
extends Resource

@export var dict := {}
@export var arr := []

func iterator() -> void:
	for key in dict.keys():
		pass

	for item in arr:
		pass
```

child_resource.gd
```
class_name ChildResource
extends ParentResource

func child_iterator() -> void:
	for key in dict.keys():
		pass

	for item in arr:
		pass
```

parent_resource.tres
```
[gd_resource type="Resource" script_class="ParentResource" load_steps=2 format=3]

[ext_resource type="Script" path="res://parent_resource.gd" id="1_flsqn"]

[resource]
script = ExtResource("1_flsqn")
dict = {}
arr = []
```

child_resource.tres
```
[gd_resource type="Resource" script_class="ChildResource" load_steps=2 format=3]

[ext_resource type="Script" path="res://child_resource.gd" id="1_4k2vj"]

[resource]
script = ExtResource("1_4k2vj")
 = null
 = null
dict = {}
arr = []
```

### Steps to reproduce

1. Create a custom resource with a dictionary or array as an export variable
2. Create a second custom resource that extends the first resource, and contains a function that iterates the dictionary/array defined in the first resource
3. Create an instance of the second resource using .new() and save it using ResourceSaver.save()
4. Open the .tres file with a text editor and notice a line that contains only:  = null
5. Load the saved .tres file with load() and receive Parse Error: Extra tag found when parsing main resource file

### Minimal reproduction project

[custom_resource_test.zip](https://github.com/godotengine/godot/files/10835669/custom_resource_test.zip)

**Comment by akien-mga** [comment] 2023-02-27 06:41
Duplicate of https://github.com/godotengine/godot/issues/73905

**Closed by akien-mga** 2023-02-27 06:41 UTC
