### ISSUE TITLE
Imported glTF meshes always use the Disabled cull mode by default, which is problematic for meshes with negative scale

### ISSUE THREAD

**Issue by knil79** [godotengine/godot#59414] opened 2022-03-22 13:54 UTC
### Godot version

3.4.3

### System information

Windows 10, GLES3, Geforce GTX 1070, driver 471.11

### Issue description

When mirroring a MeshInstance (scale -1,-1,-1) with a mesh and a material. The light falling on it is inverted
![image](https://user-images.githubusercontent.com/18348392/159497605-235e9a8d-936a-4daa-9235-19bc85fbd294.png)

### Steps to reproduce

Including simple project that shows this very well. The light is wrong for all types of light, enviromental, directional, spot and omni light.

### Minimal reproduction project

[mirror_mesh_bug.zip](https://github.com/godotengine/godot/files/8324838/mirror_mesh_bug.zip)

**Comment by Calinou** [comment] 2022-03-22 16:16
Duplicate of https://github.com/godotengine/godot/issues/39936 (same cause).

This is because glTF materials are imported with their cull mode set to **Disabled** by default, which enables double-sided material rendering and breaks on inverted meshes. To fix this, set the Cull Mode to **Back** on the SpatialMaterial (which is the default on materials other than imported glTF materials).

For reference, this also happens with the FBX importer: https://github.com/godotengine/godot/issues/42294

**Comment by knil79** [comment] 2022-03-22 16:33
I dont know if this is the same thing but if i have double sided meshes the setting cull mode to back makes it look very wrong

![image](https://user-images.githubusercontent.com/18348392/159528693-1c24a669-74a4-460f-83d9-34178c81092e.png)

setting it to Front makes the light go wrong on the inverted mesh

![image](https://user-images.githubusercontent.com/18348392/159528888-ad51bc3d-88f7-4dd5-b897-e9a409d00c8b.png)

So complex meshes with multiple sides doesnt seem to work for this.

**Comment by Calinou** [comment] 2022-03-22 16:37
> setting it to Front makes the light go wrong on the inverted mesh

Try enabling **Ensure Correct Normals** in the SpatialMaterial's Flags section.

**Comment by Calinou** [comment] 2022-03-22 16:44
Double-check if your mesh normals are configured correctly in Blender. Are they pointing outward as expected?

**Comment by knil79** [comment] 2022-03-22 16:59
> Double-check if your mesh normals are configured correctly in Blender. Are they pointing outward as expected?

I will check ASAP. My initial test looks like it will work, the inside normals might need to point inward though. But the normals seems to be the culprit!

**Comment by knil79** [comment] 2022-03-22 17:09
@Calinou Yes! it was the normals!

**Comment by Calinou** [comment] 2022-03-22 17:24
Closing, as this is actually an issue with the mesh normals and not a rendering issue within Godot.

**Closed by Calinou** 2022-03-22 17:24 UTC
Labels: discussion, topic:import, topic:3d
