### ISSUE TITLE
API reference lacks descriptions for many methods, constants, signals, etc.

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3488] opened 2016-01-27 15:43 UTC
_Docteam edit (by @akien-mga): Hijacking the original issue to make it a general topic about missing API doc._

The incomplete API reference is a known issue and improving it is a work in progress.
You are very welcome to help by proposing pull requests on the XML reference in `doc/base/classes.xml`.

See http://www.godotengine.org/article/fill-blank-class-reference for more information and https://etherpad.net/p/godot-classref-status for a list of what documentation writers are currently working on.

Also don't hesitate to come on #godotengine-devel on Freenode IRC, as writing method descriptions often requires diving into the source code, so better do it surrounded by fellow code lurkers :)

---

_Initial OP message:_

I found missing doc's for "void free()" and "get_method_list()" in Object

**Comment by vnen** [comment] 2016-01-27 15:54
Well, there's a lot of missing docs for the API. Even Object has 7 more undocumented methods besides what you mentioned.

I guess we need a master issue for missing API docs, @akien-mga.

**Comment by akien-mga** [comment] 2016-01-27 15:56
Well if the issue is about methods that are undocumented, I don't think that we need an issue for it. One just had to open the XML file or Godot to see what is documented or not :) (or godotengine.org/projects/godot-engine/wiki/List_of_classes_and_documenters for what was already reviewed).

On the other it can happen that some methods are not even *shown* as existing in the API doc, and that's a bug (like the missing info about `typeof()` that I added a couple days ago).

**Comment by vnen** [comment] 2016-01-27 16:00
@akien-mga I didn't mean to *list* every missing method, just to have an open issue to show that we are aware about the incomplete documentation (and maybe also to invite people to contribute).

**Comment by akien-mga** [comment] 2016-01-27 16:12
Why not. I'll edit the title and the OP to add links to the wiki about helping fill the API reference then :)

**Comment by akien-mga** [comment] 2016-01-27 16:17
Done. Sorry for hijacking your topic @AlexHolly :D

**Comment by trollworkout** [comment] 2016-02-01 06:00
All functions in the Image class (except Description and Constructor) do not have any description.

**Comment by trollworkout** [comment] 2016-02-01 06:01
ImageTexture class only has the functions and variable index/glossary and nothing else.

**Comment by trollworkout** [comment] 2016-02-04 09:36
preload , yield, PI are also undocumented

**Comment by akien-mga** [comment] 2016-02-04 09:39
PI is documented.

**Comment by AlexHolly** [comment] 2016-03-31 22:49
Looks like the core/variant.h link is not working it has one "godotengine/" too much.

http://docs.godotengine.org/en/latest/reference/variant_class.html
https://github.com/godotengine/godotengine/godot/blob/master/core/variant.h

**Comment by akien-mga** [comment] 2016-04-01 05:48
Thanks, I fixed it.

**Comment by djrm** [comment] 2016-06-17 17:54
Broken links in issue description.
should point to http://www.godotengine.org/article/fill-blank-class-reference maybe

**Comment by vnen** [comment] 2016-06-17 17:57
@djrm thanks, I updated the links in the OP.

**Comment by Kermer** [comment] 2016-06-20 18:36
I recently made a tool, which creates GUI for editing the classes.xml file. Linking it, in case someone might find it useful
https://github.com/Kermer/ClassesXML

**Comment by mhilbrunner** [comment] 2017-10-27 22:53
@akien-mga Close this? Quite outdated, last ~1.5 years ago and the 3.0 class doc seems to shape up nicely

**Comment by akien-mga** [comment] 2017-10-28 01:32
Indeed.

**Closed by akien-mga** 2017-10-28 01:32 UTC
Labels: documentation, enhancement, hacktoberfest
