### ISSUE TITLE
Godot 4 Beta 3 crashes after "Open Asset Library" dialog is dismissed

### ISSUE THREAD

**Issue by ByteSeb** [godotengine/godot#67410] opened 2022-10-14 21:41 UTC
### Godot version

v4.0.beta3.official (01ae26d31)

### System information

Windows 11, Ryzen 5 2600, RX 6600

### Issue description

I downloaded a Standard Build of Godot 4 Beta 3 (Windows 64 bit) from [this website](https://downloads.tuxfamily.org/godotengine/4.0/beta3/).

The downloaded zip contains an exe and cmd files, that both will launch the Engine. With either of them I have the same error, that is that when opening it, a dialog will appear asking to open the Asset Library or to dismiss it. Any of these actions will cause Godot to crash after a couple of seconds. Launching it from the command line doesn't seem to give any error messages, and not interacting with the dialog won't cause it to crash, but you will not be able to do anything until you interact with it.
This error was also present in Beta 1 and 2.

Instead of crashing, it should open the Asset Library or dismiss the popup, letting the user continue using the program.

https://user-images.githubusercontent.com/85042318/195945746-44512531-36de-48fa-b23a-2f0f3f77b8a4.mp4

### Steps to reproduce

Run the exe or cmd files from the Godot 4 Beta 3 zip download on Windows 11. When a dialog asking for confirmation appears, close the window, click on "Open Asset Library" or "Cancel". Wait a couple of seconds, and the program will automatically crash.

**Comment by Calinou** [comment] 2022-10-14 23:05
Can you reproduce this when starting the executable with the `--single-window` command line argument?

**Comment by ByteSeb** [comment] 2022-10-14 23:23
> Can you reproduce this when starting the executable with the `--single-window` command line argument?

That argument seems to fix the dialog bug. However, I created a new project, and when opening it, it won't ever load. The window freezes and doesn't show anything:
![image](https://user-images.githubusercontent.com/85042318/195956957-42129041-d8a5-46dd-ad18-c553c6998bc5.png)

This is the output I got from the terminal:

> PS C:\Users\ByteSeb\Downloads\Godot_v4.0-beta3_win64.exe> .\Godot_v4.0-beta3_win64.exe --single-window
PS C:\Users\ByteSeb\Downloads\Godot_v4.0-beta3_win64.exe> engine.org
Godot Engine v4.0.beta3.official.01ae26d31 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD Radeon RX 6600
 diting project: D:/Projects/GodotProjects/Test
Editing project: D:/Projects/GodotProjects/Test
Godot Engine v4.0.beta3.official.01ae26d31 - https://godotengine.org
Godot Engine v4.0.beta3.official.01ae26d31 - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.t.cpp:1601)
   at: window_resize (drivers/vulkan/vulkan_context.cpp:1601)X 6600
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD Radeon RX 6600

**Comment by Calinou** [comment] 2022-10-14 23:28
Which graphics drivers version are you using? I wonder if AMD's graphics driver has regressed here.

**Comment by ByteSeb** [comment] 2022-10-14 23:53
> Which graphics drivers version are you using? I wonder if AMD's graphics driver has regressed here.
> 
> Also, do you have third-party utilities like RTSS or MSI Afterburner installed? See #57937.

Oh, seems that having RTSS opened in the background was the issue. using Godot without it being opened solves the issue. 
Thanks, and sorry for the duplicate.

**Comment by clayjohn** [comment] 2022-10-14 23:58
Closing as duplicate of https://github.com/godotengine/godot/issues/57937

**Closed by clayjohn** 2022-10-14 23:58 UTC
Labels: bug, topic:editor, needs testing, crash
