### ISSUE TITLE
[3.x] `Area2D` will not detect any `StaticBody2D` nodes if its `monitorable` is set to `false`

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot#93830] opened 2024-07-01 19:56 UTC
### Tested versions

3.5.3-stable

### System information

Linux 6.9.5-1-MANJARO, KDE X11

### Issue description

If `Area2D::monitorable` is set to `false`, it will not be able to detect any `StaticBody2D` bodies.

### Steps to reproduce

1. Create a properly setup `Area2D` node with basic scripts to detect any bodies.
2. Set its `monitorable` property to `false`
3. Create `StaticBody2D` and overlap it.
4. There's no response from the `Area2D` that the `StaticBody2D` node is detected.

This is also tested with `Area2D` nodes attached to `RigidBody2D` and it makes no difference.

### Minimal reproduction project (MRP)

[area_2d_bug.zip](https://github.com/user-attachments/files/16058464/area_2d_bug.zip)

**Comment by noMoreEver** [comment] 2024-07-02 07:36
think about the meaning of the word `monitorable`, it designed to let `area2d` not monitor any body enter or leave event

**Comment by alvinhochun** [comment] 2024-07-02 08:05
Should be a duplicate of #17238

**Closed** 2024-07-02 09:11 UTC
