### ISSUE TITLE
UI inconsistencies with Plugin nodes selection/deselection

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#8104] opened 2017-03-22 14:25 UTC
**Issue description:**
Special dock options (like with the Path2D node) that should only be shown when the plugin node is selected are kept showing even when you "reset" selection by clicking on an empty space on the canvas. If the plugin node is a Control node, the "Anchor" button on the upper tab of the editor will disappear, but not docks manually handled with handles(object) and make_visible(visible).
Also, when you select said Plugin Node with the mouse selection box, the special dock won't appear - even when the plugin is the only node being selected. As the previous example, if the plugin node is a Control node, the "Anchor" option will appear - but not any of the docks handled with handles(object) and make_visible(visible).

Hopefully I could describe those inconsistencies well. They are not Engine-breaking, but when creating a Plugin Node, they look like annoying bugs for the user.

**Link to minimal example project:**
Linking a small project with a plugin + custom dock example.
[ui-problem.zip](https://github.com/godotengine/godot/files/861695/ui-problem.zip)

**Comment by kubecz3k** [comment] 2018-04-10 16:29
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:22
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:22 UTC
Labels: bug, topic:editor
