### ISSUE TITLE
`Resource.duplicate(true)` triggers parser error when resource's script has `class_name`

### ISSUE THREAD

**Issue by khellste** [godotengine/godot#70570] opened 2022-12-25 22:40 UTC
### Godot version

4.0beta10

### System information

Windows 10, Vulkan

### Issue description

`duplicate` always crashes on a custom resource when `subresources=true` is passed for the first argument, with the error "`Condition "path.is_empty()" is true.`". This happens whether or not there are subresources.

Based on the error, it looks like a `resource_path` is expected, but this is an in-memory resource which has never been persisted to disk.

![image](https://user-images.githubusercontent.com/3039797/209483382-0c614a2f-7e4d-4a83-8be2-61828715db4b.png)

### Steps to reproduce

1. Create a simple custom class extending `Resource`.
2. Call `duplicate(true)` on an instance of the custom class.

### Minimal reproduction project

[ResourceDuplicationBug.zip](https://github.com/godotengine/godot/files/10300715/ResourceDuplicationBug.zip)

**Comment by kleonc** [comment] 2022-12-26 17:09
Duplicate of #68666, the same cause: https://github.com/godotengine/godot/issues/68666#issuecomment-1329776082. Closing as it can be tracked in there (I've added https://github.com/godotengine/godot/issues/68666#issuecomment-1365288526 to directly refer to this report).

**Closed** 2022-12-26 17:14 UTC
Labels: bug, archived, topic:core, topic:gdscript

**Comment by rcorre** [comment] 2022-12-30 15:40
In godot3, `duplicate(true)` on a custom resource does not create a parse error, but rather a runtime error

```
SCRIPT ERROR: Trying to assign value of type '' to a variable of type 'PlayerInput.gd'.
```

Is this still the same issue, or should I file a new one?

**Comment by kleonc** [comment] 2022-12-30 17:28
@rcorre The root cause seems to be the same: the script is being duplicated and thus it's treated as a completely different script / it's not recognized to be the same as the original script (`'PlayerInput.gd'`). In the error message it seems that the script's path is being printed out and it's empty (`''`) because the duplicated script is not saved to any file. So the error itself is rather correct. In `master` this error (still can be reached after ignoring the parser error) seems to be a little improved as it shows the base type when there's no file path, like:
```
Trying to assign value of type 'Resource' to a variable of type 'PlayerInput.gd'.
```

So I'd say yes, that's the same issue. Both:
- the parser error (not present in `3.x`)

and:
- the type mismatch error on assignment you've mentioned

are just symptoms to the same issue (in `3.x`/`master`): the script being duplicated (when it probably shouldn't).
