### ISSUE TITLE
Overzealous Warnings: Unreachable statement

### ISSUE THREAD

**Issue by storyfeet** [godotengine/godot#33419] opened 2019-11-07 09:50 UTC
**Godot version:** 

 3.1.1

**OS/device including version:** 
Linux PopOs

**Issue description:**  
return in a match statement does not make the code beneath it unreachable, yet the compiler seems to think it does.

**Steps to reproduce:**

```
func on_card_selected(x,y):
	match card_at(x,y).ctype:
		CardInfo.CType.WALL:
			return

	meeples[current_player].slide_to(x,y,card_sz)
	current_player = (current_player + 1 )%4
```

gives this warning.

```
W 0:00:00:0777   Unreachable code (statement after return) in function 'on_card_selected()'.
  <Source>       game.gd:60
```

**Minimal reproduction project:**
To get this match statement

**Comment by akien-mga** [comment] 2019-11-07 10:18
Duplicate of #30458

**Closed by akien-mga** 2019-11-07 10:18 UTC
