### ISSUE TITLE
Renaming animation node renders blend tree unusable

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20942] opened 2018-08-12 10:59 UTC
**Godot version:**
`master` / 80a8636a

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
When renaming an animation node inside a blend tree, the connections disappear upon saving the file and it fails to open again due to broken node references.

Manually editing the content of `.tres` or `.tscn` file that contains the blend tree seems to be the only safe method for renaming animation nodes for now.

**Comment by akien-mga** [comment] 2018-08-16 11:58
Duplicate of #20210.

**Closed by akien-mga** 2018-08-16 11:58 UTC
Labels: bug, topic:editor
