### ISSUE TITLE
Strange physics when a RigidBody2D has an active Camera2D

### ISSUE THREAD

**Issue by r-mice** [godotengine/godot#21464] opened 2018-08-26 22:42 UTC
**Godot version:**

3.1.dev.calinou.0a8ac1a

**OS/device including version:**
Kubuntu 18.04.1 x64

**Issue description:**
The camera drags the rigidbody and makes it go through the objects at high speed

**Steps to reproduce:**
Put a Camera2D node inside a RigidBody2D and set the current property of the camera to active.

**Minimal reproduction project:**
[cam-bug.zip](https://github.com/godotengine/godot/files/2321965/cam-bug.zip)

**Comment by eon-s** [comment] 2018-08-26 23:52
Duplicate of the already fixed #21289 
Try a more recent build and report back if the problem is still present.

**Comment by nobuyukinyuu** [comment] 2018-08-27 01:37
probably also related to #21448 , will update and close my issue once I can get a build newer than 4 days ago...

**Closed** 2018-08-27 07:40 UTC
Labels: bug, topic:physics

**Comment by r-mice** [comment] 2018-08-29 20:04
Well, this is really weird. I wait some days to try again, download today a new version from [here](https://hugo.pro/projects/godot-builds/) but, again I have the same error, so I can't understand why some says that this problem is already fixed. @eon-s @nobuyukinyuu , Are you test my project above? Sorry if bothering, but this thing interest me much.

**Comment by akien-mga** [comment] 2018-08-29 20:15
I've tested the linked project but it seems to work fine for me (Linux, self-compiled, debug build).

Also seems to work fine with Calinou's AppImage build from today (Linux, release_debug).
