### ISSUE TITLE
Opening the Asset Library Maxes out CPU

### ISSUE THREAD

**Issue by Matacrat** [godotengine/godot#56400] opened 2022-01-01 13:41 UTC
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10 64-bit and AMD Athlon 3000G with Radeon Vega 3 Graphics 3.50 GHz (v.21.30.23.01-211018a-373652C) 8.00 GB RAM (5.93 GB usable) 

### Issue description

Opening the Asset Library Maxes out the CPU.
It also freezes the computer and has to be forced off if the asset library is left open.
![GodotCPU](https://user-images.githubusercontent.com/48725508/147851686-40974d89-3b6b-44d0-ac29-cb76c9cc958b.png)

### Steps to reproduce

1. Open Godot
2. Open the Asset library

**Comment by Torguen** [comment] 2022-01-01 16:28
Works good in v3.4.2.stable.official [45eaa2daf]

**Comment by Calinou** [comment] 2022-01-01 16:37
Duplicate of https://github.com/godotengine/godot/issues/51530.

**Closed by Calinou** 2022-01-01 16:37 UTC
