### ISSUE TITLE
TileMap issue

### ISSUE THREAD

**Issue by Jedzkie** [godotengine/godot#42844] opened 2020-10-16 03:18 UTC
**Godot version:**
Tested on 3.1, 3.2 versions.

**OS/device including version:**
Windows 10 2004 64bit

**Issue description:**
8x8 sized sprites shows unusual behavior (jaggery and it seems like jumping a little bit while walking/running on tilemaps). But on a plain staticbody node, it walks fine.

**Steps to reproduce:**

**Minimal reproduction project:**
[Test_Jedzkie.zip](https://github.com/godotengine/godot/files/5388967/Test_Jedzkie.zip)

Video:
https://drive.google.com/file/d/1MHgWDGu0sUiCtvACWFa3Z6UGKxX1btiq/view

**Comment by Calinou** [comment] 2020-10-16 06:57
Duplicate of https://github.com/godotengine/godot/issues/35606?

**Comment by lawnjelly** [comment] 2020-10-16 09:08
Am struggling to work out what you are referring to. I've run your project in 3.2.3 and 3.2 and watched the video in slo mo. You may need to make this more obvious to the readers, perhaps by editing the project or the video.

You may be referring to general jitter, the need for fixed timestep interpolation (#30068), or to a 2d physics effect (am suspecting this because you refer to a difference on a static body).

Also try running in 3.2.3, sometimes older bugs have been fixed.

**Comment by Jedzkie** [comment] 2020-10-16 10:10
@lawnjelly I made that test project on 3.2.3, and i got the same result.

**Comment by Jedzkie** [comment] 2020-10-16 10:11
@Calinou i tried 16x16 and 32x32 sprites, and got no problem as what I've encountered in 8x8 sprites.

**Comment by madmiraal** [comment] 2020-10-16 14:22
If it is physics jitter, it may be a duplicate of #40498, but #40498 doesn't have an MRP. The physics jitter in 2D is a lot less than 3D, and barely noticeable, but it does exist. Most of the physics jitter is fixed with #35945 and it's 3.2 version #37498.

**Comment by pouleyKetchoupp** [comment] 2021-01-14 18:29
Fixed in #42574, closing.

**Closed by pouleyKetchoupp** 2021-01-14 18:29 UTC
Labels: bug, confirmed, topic:physics
