### ISSUE TITLE
Godot crashes when assigning a variable a method call from the same variable on the last line of a script

### ISSUE THREAD

**Issue by megalobyte** [godotengine/godot#58041] opened 2022-02-13 05:53 UTC
### Godot version

26b21dc0cb

### System information

Arch, Vukan, X11, NVIDIA GeForce GTX 1070/PCIe/SSE2

### Issue description

Godot will crash when assigning to a variable and using a method from that same method. Godot will crash once the user enters `.` to access a method. This only occurs when editing on the last line of the file.  

No crash dump is printed after the crash. Apologies for the title gore

### Steps to reproduce

1. Open any script
2. Go to the last line in the file 
3. Type something like `position = position.` 
4. Godot should crash

### Minimal reproduction project

N/A

**Comment by arczewski** [comment] 2022-02-13 23:02
I'm not confident enough in engine source code to fix it but as for now if this will help someone this is what I found.
1. This is caused by gdscript_editor.cpp:1762 if statement checking and later changing current_line which is later modified by back to previous value by _guess_expression_type.
`gdscript_editor.cpp:1762
if (last_assigned_expression && last_assign_line != p_context.current_line) {
		GDScriptParser::CompletionContext c = p_context;
		c.current_line = last_assign_line;
		r_type.assigned_expression = last_assigned_expression;
		if (_guess_expression_type(c, last_assigned_expression, r_type)) {
			return true;
		}
	}`
2. It only happends on last line because current_line and end_line are not equal.  end_line has X + 1 value because of  gdscript_tokenizer.cpp:1288 which adds new line at the end of the file and increment line variable which is then passed to token used in gdscript_editor that has infinite recursion.
3. Quick workaround I found is to replace in gdscript_tokenizer.cpp:315:make_token  method:
`token.end_line = line`
with
`token.end_line = pending_newline ? line - 1 : line;`
but I didn't have enough time to dig deep and understand the whole parser to confidently make a fix pull request worthy.
Maybe this info will help someone fix the issue,

**Comment by SaracenOne** [comment] 2022-02-22 01:36
Can anyone confirm if this still an issue? I was fixing another GDScript which sounded like it might be related to this, but I can't get this crash to trigger in master either. Can anyone confirm this is still crashing?

**Comment by vermeeren** [comment] 2022-02-22 02:48
@SaracenOne It was still an issue in b0ba9468ee40dad636dc9c5cd7b53c24041390d8, just pulled from master and tested 256069eaf00be2340259f896695014d92b1e22ed which appears to have fixed the issue.

The only GDScript diff between these 2 commits is ae0026bc7b0b33195a2f8c5a8e85afd2127ffd05 so I think it's safe to say #58275 fixed this issue.

**Comment by megalobyte** [comment] 2022-02-22 03:04
@vermeeren is correct. I tested with the latest master, no crash. Reverted commit ae0026bc7b0b33195a2f8c5a8e85afd2127ffd05 and then it crashed

**Comment by akien-mga** [comment] 2022-02-22 07:31
Fixed by #58275.

**Closed by akien-mga** 2022-02-22 07:31 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed, crash
