### ISSUE TITLE
Save and Close Crashing Editor

### ISSUE THREAD

**Issue by CalebMRichardson** [godotengine/godot#12813] opened 2017-11-10 18:23 UTC
On Windows 10 x64 Running Godot x32 from the most recent build from the master branch. 

Steps to reproduce 
1. Open Scene
2. Make a change
3. Close Godot
4. Select "Save and Close"

It seems to be happening in both 2D and 3D scenes. 

Console output only says - "CrashHandlerException: Program crashed"

![godotcrash](https://user-images.githubusercontent.com/14320944/32672682-d454c8a4-c600-11e7-923b-7972fd91a0a9.gif)

**Comment by Zireael07** [comment] 2017-11-10 19:04
I believe this has been reported already but I can't find the issue number.

**Comment by CalebMRichardson** [comment] 2017-11-10 19:07
@Zireael07 I briefly looked and didn't see anything. I'll take another look though. Thanks!

**Comment by Noshyaar** [comment] 2017-11-11 06:17
Could be related to #9405, not sure. Please include a stack trace if available.

**Comment by icnikerazah** [comment] 2017-12-04 00:38
same bug on macos sierra

**Comment by icnikerazah** [comment] 2017-12-04 08:38
Why does it take so long to be fixed? This is very serious high priority issue. Unbelievable

**Comment by akien-mga** [comment] 2017-12-04 08:47
> Why does it take so long to be fixed? (a month) This is very serious high priority issue. Unbelievable

Because not everyone can reproduce this issue (I can't on Linux using the above steps to reproduce), and none of the people who can actually reproduce it have tried to provide relevant debugging info. We can't fix a bug if we can't reproduce it and don't know what caused it.

**Comment by icnikerazah** [comment] 2017-12-04 08:55
I will try reproduce this issue, and i will send crash logs.

**Comment by icnikerazah** [comment] 2017-12-04 10:23
I have this bug every godot 3 builds,  same steps

1.     Open Scene
2.     Make a change
3.     Close Godot
4.     Select "Save and Close"


[this_is_crash.txt](https://github.com/godotengine/godot/files/1526619/this_is_crash.txt)
[another_crash.txt](https://github.com/godotengine/godot/files/1526620/another_crash.txt)
[crash.txt](https://github.com/godotengine/godot/files/1526621/crash.txt)

**Comment by icnikerazah** [comment] 2017-12-04 10:28
terminal output 
[terminal output.txt](https://github.com/godotengine/godot/files/1526646/terminal.output.txt)

**Comment by icnikerazah** [comment] 2017-12-04 10:30
godot's saving logic is defective.

**Comment by chongdashu** [comment] 2017-12-11 22:38
Tried to reproduce on Windows x64 with 64-bit Godot.
Wonder if it might be a 32-bit issue? Will give it a shot.

**Comment by icnikerazah** [comment] 2017-12-16 13:56
version: godot3builds.digitecnology.com/builds/2017-12-15.12:12:09.433cb6f49/godot-v3.0-osx.fat.zip
on 32bit and 64bit app, i have same crash.

**Comment by volzhs** [comment] 2017-12-20 04:28
I could reproduce this on ubuntu, but I can't with b08735f20987a6188fd54c5e2dcd072dc316b413 now.

**Comment by chongdashu** [comment] 2017-12-20 07:36
I reproduced this on Windows even at b08735f

**Comment by akien-mga** [comment] 2018-01-05 14:57
Fixed by #14860.

**Closed by akien-mga** 2018-01-05 14:57 UTC
Labels: bug, topic:editor
