### ISSUE TITLE
Tilemap node not getting its initial row correctly?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#51877] opened 2021-08-19 09:00 UTC
### Godot version

3.3.3 rc2 mono

### System information

w10 64

### Issue description

For tree organization reasons, I had to put the tilemap nodes inside a 2D node, this now causes me problems with the coordinates.

If a tilemap node is the child of another node (for example, the child of a 2D node), row 0 of the tilemap is indicated at coordinate 0 of the father node, this happens even if the tilemap has tiles even higher than the father node, in this video it can be seen.

Godot says "well, if the Y coordinate of the parent node is 100, then row 0 of the tilemap will be set there".
But the tilemap has tiles before the Y coordinate of the parent node, so that's confusing.

Observe the video, first I indicate what row 0 of the tilemap is, this is because it is inside a node2D, then row 0 is set to the Y coordinate of the father node.
But the tilemap has tiles above this, so row 0 should be the first tile of the tilemap, this is shown in the final part of the video where I scroll up the screen.

https://user-images.githubusercontent.com/19652075/130040492-b3fa3d2b-91ca-4236-9a6d-0b78113c9f72.mp4

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by akien-mga** [comment] 2021-08-19 09:11
That's not a bug, cell coordinates in a tilemap are like cartesian coordinates in the position, they can also take negative values. The cell `(0, 0)` is at the origin of the TileMap node (which here is offset by the origin of the parent Node2D), but you can still place tiles anywhere on the screen, including at negative offsets.

**Comment by kleonc** [comment] 2022-11-05 12:41
As @akien-mga pointed out, it does work as intended. TileMap is affected by the parent transformations like any other CanvasItem. The cells are relative to the given TileMap and their coordinates of course can be negative. Not sure why would anyone assume anything different. So I don't think there's need to clarify anything in the docs or something like that. Hence just closing.

**Closed by kleonc** 2022-11-05 12:41 UTC
Labels: topic:core, topic:2d
