### ISSUE TITLE
Vulkan renderer not updating screen after computer suspension + memory leak

### ISSUE THREAD

**Issue by ShepDowell** [godotengine/godot#74094] opened 2023-02-28 04:24 UTC
### Godot version

4.0.rc6

### System information

Ubuntu 22.10, RTX 2060, Vulkan

### Issue description

If I open any Godot 4 project, suspend my computer, then resume it, the renderer no longer updates to the screen. It also causes a memory leak (left it until it hit 4.9 GB). This only occurs when using the Forward+ or Mobility renderer. The Compatibility renderer does not have this issue; it works fine.

It also occurs to exported projects (if Forward+ or Mobility renderer used).

I assume something in the Vulkan renderer is being disconnected by the computer suspension, and is not reconnected when resumed. If I move Godot to a second monitor, then disconnect the monitor, the issue doesn't present, only if I suspend the computer. I cannot test on any other operating system.

### Steps to reproduce

- open any 4.0 project
- set renderer to Forward+ or Mobility
- suspend computer
- resume computer
- attempt to move or interact with anything in the godot window. Resizing also works

### Minimal reproduction project

N/A any project works, including default new project

**Comment by lyuma** [comment] 2023-02-28 05:18
Duplicate of #52738

**Closed by lyuma** 2023-02-28 05:18 UTC
