### ISSUE TITLE
Linux unable to open Godot 4.0 Beta 2

### ISSUE THREAD

**Issue by Dylised** [godotengine/godot#67237] opened 2022-10-11 08:33 UTC
### Godot version

4.0 BETA2

### System information

Google Chrome: Version 105.0.5195.134 (Official Build)  (64-bit) Platform: 14989.107.0 (Official Build) stable-channel octopus Channel: stable-channel Firmware Version: Google_Meep.11297.250.0 ARC Enabled: true ARC: 9040963 Enterprise Enrolled: false Developer Mode: false

### Issue description

Godot 4.0 BETA unable to open on linux 64bit build - below is the command line when: /Godot_v4.0-beta2_linux.x86_64 is ran -

![Screenshot 2022-10-11 9 25 57 PM](https://user-images.githubusercontent.com/93733308/195040204-4cadee31-09b2-40ac-bec9-b917c435f032.png)

### Steps to reproduce

.

**Comment by clayjohn** [comment] 2022-10-11 18:24
Does your device have a GPU capable of supporting vulkan? It appears that Godot is defaulting to llvmpipe as it isn't seeing any vulkan-capable devices. llvmpipe is essentially a GPU emulator that is very slow and doesn't really support vulkan. 

It also looks like you are running a chromebook. Godot doesn't support chromeOS directly, so you need to ensure that you are actually running linux on your chromebook and that your install of linux has access to things like the GPU. 

One thing you can do to get more information about vulkan on your device is to install the vulkan sdk and try running the vkcube executable.

**Comment by Calinou** [comment] 2022-10-12 23:01
Duplicate of https://github.com/godotengine/godot/issues/38428 (same cause).

Most Chromebooks don't have hardware that can support Vulkan well (if at all), so you may have to stick to the OpenGL renderer.

There's an OpenGL renderer you can test with the `--rendering-driver opengl3` [command line argument](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html), but many features are still missing, especially in 3D. Note that you may have to create a project from the command line (see that page's description) to bypass the project manager. See also https://github.com/godotengine/godot/issues/58927.

**Closed by Calinou** 2022-10-12 23:01 UTC
