### ISSUE TITLE
C# AnimationPlayer doesn't show a method in animation track.

### ISSUE THREAD

**Issue by bytebuffr** [godotengine/godot#42856] opened 2020-10-16 16:31 UTC
**Godot version:**

v3.2.3.stable.mono.official

**OS/device including version:**

GLES3, Nvidia GEFORCE 750Ti

**Issue description:**

I created the method AttackAnimationFinished and want to add it to AnimationPlayer in animation track named "Functions". But for some reason exactly this method doesn't display in list. If my project written in GDScript then all this fine. But with C# such an issue.

**Steps to reproduce:**
Saved the project again.
Restart the Godot.
Delete method and rewrite it.

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-10-16 18:26
Duplicate of https://github.com/godotengine/godot/issues/39156 and/or https://github.com/godotengine/godot/issues/37803.

**Closed by Calinou** 2020-10-16 18:26 UTC
