### ISSUE TITLE
`Extend Script` doesn't work with script without `class_name`

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#68236] opened 2022-11-03 22:17 UTC
### Godot version

4.0.beta.custom_build (c0de8d32d)

### System information

Windows 11, Vulkan Clustered, Geforce 1660 (522.25)

### Issue description

![image](https://user-images.githubusercontent.com/10379487/199844711-b7e9c7a9-c00a-4ff5-8189-5ea71e020bf6.png)

`Extend Script` does not create an inheritor script. After clicking `Create` button, the following appears in the console:

```
editor\script_create_dialog.cpp:379 - Parameter "type" is null.
```

### Steps to reproduce

- add script (without class_name) to node
- extend it with `RMB->Extend Script`

**Comment by KoBeWi** [comment] 2022-11-03 22:23
Duplicate of #65827

**Closed by KoBeWi** 2022-11-03 22:23 UTC
