### ISSUE TITLE
Inspector variables description not showing if inside a category

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#70452] opened 2022-12-22 17:01 UTC
### Godot version

4.0.beta9

### System information

macOS Monterey 12.3.1

### Issue description

When exporting variables and adding a description, the description won't show up if these variables are inside a category.

### Steps to reproduce

Here is an example of a script why this issue:

```gdscript
extends Node2D

## The description will show well.
@export var this_var_is_ok = "Value"

## This one too.
@export var another_var_ok = "Value"

@export_category("My Grouped Vars")

## This description won't show up in the inspector.
@export var var_not_ok = "NOK"
```

Now putting the mouse over the property in the inspector, the first two variables' descriptions will show well.

<img width="600" alt="CleanShot 2022-12-22 at 15 07 40@2x" src="https://user-images.githubusercontent.com/1923206/209151788-a1833303-c9f0-404e-ae07-a00585df6830.png">

But, doing the same with the variable inside the category, we have this result:

<img width="554" alt="CleanShot 2022-12-22 at 15 08 37@2x" src="https://user-images.githubusercontent.com/1923206/209151942-d276a015-7e42-43b2-a0df-b9884ba365ce.png">

If you check the code above, a description exists but does not show up. It needs to be shown.

### Minimal reproduction project

[property-description-export-group.zip](https://github.com/godotengine/godot/files/10287517/property-description-export-group.zip)

**Comment by kleonc** [comment] 2022-12-22 18:13
Duplicate of #64432.

**Closed** 2022-12-22 18:13 UTC
