### ISSUE TITLE
Material render priority settings don't work with No Depth Test material flag

### ISSUE THREAD

**Issue by thottee** [godotengine/godot#35247] opened 2020-01-17 18:32 UTC
**Godot version:**
3.1.2+

**OS/device including version:**
Windows 8.1

**Issue description:**
Material render priority settings don't work with No Depth Test material flag.

**Steps to reproduce:**
1. Create an object and a material for this object, with a next step material, where enable "no depth test" flag, and set render priority to -1.
2. Create a second object (like a wall), and set render priority -1 on this object material, and put first object behind of this object.

![godot_ndt_mat](https://user-images.githubusercontent.com/42456553/72636036-7d4b0900-395e-11ea-9654-5a11b42920e9.png)

When it worked right, the covered part of first object got "no depth test" material, and it looked like on this picture in godot 3.1.1:
![godot3 1 1_ndt_rp](https://user-images.githubusercontent.com/42456553/72636367-314c9400-395f-11ea-99a6-bf8679f72f73.png)

After 3.1.2, this isn't work. The "no depth test" material appear always.

**Minimal reproduction project:**
2 objects and 2-3 material.

**Comment by Calinou** [comment] 2020-01-17 18:57
Please upload a minimal reproduction project to make this easier to reproduce.

**Comment by clayjohn** [comment] 2020-01-17 19:05
Duplicate of https://github.com/godotengine/godot/issues/31164

An explanation of what to do to reproduce the behaviour from 3.1: https://github.com/godotengine/godot/issues/31164#issuecomment-518868682

**Closed** 2020-01-17 19:16 UTC
