### ISSUE TITLE
TileSet vertical slider didn't resize

### ISSUE THREAD

**Issue by Razorback1911** [godotengine/godot#33971] opened 2019-11-28 16:04 UTC
**Godot version:** Godot Engine v3.1.1.stable.official

**OS/device including version:** Windows 10 pro (1909 - 18363.476)

**Issue description:** The vertical slider didnt refresh correctly when a texture is selected in TileSet and previously zoomed in

**Steps to reproduce:** We have a Nav node and a TileMap node.
Add a texture (big is better) to the TileSet + New Single Tile
Zoom in the Tile at the maximum
Cick on the tileMap node to escape the TileSet menu
Return to the TileSet
Select the Tile
The zoom is kept but the vertical slider is not refresh and act like the Tile is not zoom in.
When you move the zoom the slider is refresh.

Reload Godot reset the zoom.

**Comment by KoBeWi** [comment] 2019-11-28 16:49
Sounds like duplicate of #28143, already fixed in 3.2

**Closed by KoBeWi** 2019-11-28 16:49 UTC
