### ISSUE TITLE
2D stretch mode doesn't scale properly

### ISSUE THREAD

**Issue by abueide** [godotengine/godot#39892] opened 2020-06-27 17:39 UTC
**Godot version:**

4.0, b55d859c5f092d145cd0d2c8df9ac5d42c500626

**OS/device including version:**

Windows, Vulkan

**Issue description:**

I set my resolution to 320x180. I set the test resolution to scale up to 1280x720. I set the stretch mode to 2D. When I start the game the camera is really far zoomed out, and doesn't show the camera region that is represented in the editor. When I resize the window, it doesn't stretch the content, it just stays the same size and shows more of the screen.

![NDuh3IFjhh](https://user-images.githubusercontent.com/19354425/85928600-62fd4b80-b86b-11ea-8410-532427d3df31.gif)

**Steps to reproduce:**
Open repro project, run game.

**Minimal reproduction project:**

[repro.zip](https://github.com/godotengine/godot/files/4840990/repro.zip)

**Comment by Calinou** [comment] 2020-06-27 18:48
Related to #37941.

**Comment by txj-mssl** [comment] 2020-06-28 12:09
I have this problem, too

**Comment by akien-mga** [comment] 2022-03-26 19:00
Duplicate of #37941.

**Closed by akien-mga** 2022-03-26 19:00 UTC
Labels: bug, topic:rendering, confirmed, regression
