### ISSUE TITLE
Bitmap fonts (.fnt) are not correctly displayed in Theme preview and on Label3D

### ISSUE THREAD

**Issue by substract** [godotengine/godot#68656] opened 2022-11-14 17:21 UTC
### Godot version

Godot 4 beta 4

### System information

Windows 10

### Issue description

Bitmap fonts (.fnt) will not show the font correctly in the theme preview and when used on Label3D (the "white bar" on the screenshot) 
Using such a theme will however work as expected on Buttons and Labels outside the Theme preview.

![screen1](https://user-images.githubusercontent.com/14269417/201723909-aa279460-b01b-446d-8e45-9a9d1dc646e5.JPG)
![screenshot24](https://user-images.githubusercontent.com/14269417/201723979-e03c7ddf-2156-4ab7-a831-754c7ea1ea24.png)
![screen2](https://user-images.githubusercontent.com/14269417/201723985-d3e80fea-5cf1-49fd-8d3d-55d1cffc0ff3.JPG)

### Steps to reproduce

Use the .fnt font file on a Theme

Use the .fnt font file on a Label3D

### Minimal reproduction project

[bitmap_font_test.zip](https://github.com/godotengine/godot/files/10006561/bitmap_font_test.zip)

**Comment by bruvzg** [comment] 2022-11-14 17:55
Can't reproduce, bitmap fonts are working fine in both preview and Label3D. Please provide your bitmap font file to test, most likely it is not loaded correctly. Unlike UI controls, Label3D and Preview will not fall back to the default built-in font and display hex code/white boxes if the font is not loaded or do not have required glyphs.

**Comment by substract** [comment] 2022-11-14 20:04
Oh ok. I have attached a minimal project with my font.
I figured out how to create a .fnt file and made a little tool in godot to create one but i guess there must be something off then.

**Comment by bruvzg** [comment] 2022-11-14 20:27
Your file have missing `font size` (it's probably should be ignored by importer) and `char count` set to one `1` whine there are 81 char in the file (this is clearly wrong):

If the first 4 lines of the `fnt` file are changed to the following, it will work:
```
info face="plaque" size=16
common lineHeight=6
page id=0 file="plaque.png"
chars count=81
```

**Comment by bruvzg** [comment] 2022-11-14 20:37
Loading fonts with missing font size should be fixed by https://github.com/godotengine/godot/pull/68664, and your tool should set valid number of chars.

**Comment by substract** [comment] 2022-11-14 20:53
Wow, thanks a lot for your help! You people are fantastic!
Sorry for reporting a non-bug

**Closed** 2022-11-14 22:36 UTC
Labels: bug, topic:editor, topic:gui
