### ISSUE TITLE
Always Open Output On Play opens the debugger when set to false

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#66496] opened 2022-09-27 12:15 UTC
### Godot version

4.0b1

### System information

Linux/Manjaro

### Issue description

The editor setting `run/output/always_open_output_on_play`, when set to `false` is unhelpful, as it opens the Debugger dock when the app is run. (which means it technically works, as it doesn't open the Output dock 😛)

### Steps to reproduce

Set `run/output/always_open_output_on_play` to `false`

**Comment by Calinou** [comment] 2022-09-27 14:53
This is done by design: https://github.com/godotengine/godot/blob/c2f66648f1cb7f26adf77cc3cf91052c95be5dbe/editor/debugger/editor_debugger_node.cpp#L212-L216

We should probably change this option from a boolean to an enum **Run > Output > Open Bottom Panel On Run**, so you can choose which bottom panel should appear:

- None
- Output
- Debugger

**Comment by miv391** [comment] 2023-09-16 16:55
> This is done by design:

Is this really a designed behaviour? I would suggest keeping the setting as it is, but removing that code presented in Calinou's message completely. In my opinion it shouldn't be Debugger's responsibility at all to open Output according to some setting. Debugger also shouldn't force itself to be the selected tab. Editor node is already opening Output if the setting is true:
https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/editor/editor_node.cpp#L4105-L4107

At least for me this is a constant annoyance. If I'm checking memory consumption from Debugger / Monitors tab page, I need to reopen that tab _every_ time I restart project. It would so much better if I could use this setting to keep the tabs as they are.

Calinou's suggestion would be slightly better than the current situation, but it feels quite cumbersome that I should go to settings to select which tab I want to see when I start the project. Almost always I want to see same tab I'm already looking at. So the simplest solution would be to not to change the tab at all (unless specifically asked by the "Always Open Output on Play"=true setting).

**Comment by KoBeWi** [comment] 2024-07-24 21:43
Fixed by #91033

**Closed by KoBeWi** 2024-07-24 21:43 UTC
Labels: discussion, topic:editor
