### ISSUE TITLE
Visual bug/artifact when using varying UV offset in a (distortion) shader in Godot 4.2+ mobile renderer

### ISSUE THREAD

**Issue by 11811341** [godotengine/godot#90818] opened 2024-04-17 19:43 UTC
### Tested versions

Reproducible in Godot 4.2 and above using the mobile renderer. NOT present in 4.1

### System information

Windows 10, mobile renderer, Godot 4.2.1

### Issue description

When a distortion shader is applied to a plane that uses a varying UV offset to create the distorted effect, a triangular patch of "roughness" appears in the portion opposite the camera. This problem was not present in Godot 4.1x. 

Video of the issue can be seen here:
https://www.reddit.com/r/godot/comments/1c5sd1z/day_2_of_seeking_help_with_shader_bugged_by_42/

Image from the MRP, undesirable area circled red:
![image](https://github.com/godotengine/godot/assets/61829368/0df47827-ff56-4ccc-97c9-7b994bcebdda)

### Steps to reproduce

1. Use Godot 4.2 or above
2. Use mobile renderer
3. Basic scene setup for better visibility (Light & Environment, these don't affect the bug, but make it more easily visible)
4. Set up a plane and create and apply a new Shader material 
5. Use the following minimal shader code:

shader_type spatial;

uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, repeat_disable;

uniform float refraction_strength = 0.05;
uniform sampler2D refraction_noise;

void vertex() {
}

void fragment() {
  vec2 offset = texture(refraction_noise, UV).rg;
  offset = 2. * offset - 1.;
  offset *= refraction_strength;
  vec2 ouv = SCREEN_UV + offset;
  ALBEDO = texture(SCREEN_TEXTURE, ouv).rgb;
}

### Minimal reproduction project (MRP)

[Bugfinding.zip](https://github.com/godotengine/godot/files/15016140/Bugfinding.zip)

**Comment by clayjohn** [comment] 2024-05-02 04:24
This might be a duplicate of https://github.com/godotengine/godot/issues/88786. It seems the issue doesn't occur on all devices, what CPU and GPU are you testing on?

**Comment by 11811341** [comment] 2024-05-02 15:21
Yeah it definitely looks that way... It looks even more similar to the other one you linked  (#88585). 
It shows up on my intel i7-6700k GTX1070, as well as on my honor 50, as well as an honor 90 phone. 
Would be really sus if it was a device issue.

**Closed** 2024-05-07 12:25 UTC
Labels: bug, topic:rendering, confirmed, topic:shaders
