### ISSUE TITLE
characterbody3D behaves weird when adding constant gravity to linear_velocity

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#51367] opened 2021-08-07 15:27 UTC
### Godot version

4.0.dev

### System information

Solus linux

### Issue description

i zero out the linear_velocity and add a forward moving vector to it, after calling move_and_slide it moves at a constant rate.
when i add gravity to linear velocity, even if i zero out the linear_velocity at the start of physics_procces, the characterbody3D keeps accelerating at a rapid pace and get out of control

### Steps to reproduce

just uncomment the gravity vector addition line in the reproduction project
[test.zip](https://github.com/godotengine/godot/files/6949312/test.zip)

**Comment by Calinou** [comment] 2021-08-07 16:06
Can you reproduce this on 3.3.2 with Bullet or GodotPhysics? `master` uses GodotPhysics only.

**Comment by barbaros83** [comment] 2021-08-07 17:27
@Calinou this uses the characterbody3D from 4.0, it has a lot of changes compared to 3.3

**Comment by barbaros83** [comment] 2021-08-07 17:43
@Calinou i made a similar test in 3.3.2 and set the 3d physics engine to godot physics but it worked as expected, didnt encounter the same strange behavior as in 4.0

**Comment by Calinou** [comment] 2021-08-07 18:04
cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment] 2021-08-12 01:02
This bug is due to #50523, it works correctly if you change the line to `linear_velocity = linear_velocity + Vector3.DOWN * 9.8` to avoid the `+=` operator.

Closing as duplicate.

**Closed by pouleyKetchoupp** 2021-08-12 01:02 UTC
Labels: bug, topic:physics
