### ISSUE TITLE
Godot 4.1: Error creating a CollisionPolygon2D with no holes or self-intersection: (Convex decomposing failed!)

### ISSUE THREAD

**Issue by artlessgames** [godotengine/godot#84670] opened 2023-11-09 15:55 UTC
### Godot version

Godot v4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 730 (Intel Corporation; 31.0.101.4575) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

In my project, I use offset_polyline to generate the outline of a curve and create a collision polygon with it.
In some rare cases, the polygon generation simply fails.
![QQ图片20231109235303](https://github.com/godotengine/godot/assets/79254895/26f80b27-22c5-4d35-8902-d71fc16791dc)
(The points are highlighted with white dots, we can see there's no hole or self-intersection)

By the way, is it possible to detect "Convex decomposing failed" in gdscript? Delete the invalid shape sounds like an option if I don't have a better choice.

### Steps to reproduce

Create a StaticBody2D and attach the code below:

```gdscript
extends StaticBody2D
func _ready():
	var cc = CollisionPolygon2D.new()
	add_child(cc)
	var v:PackedVector2Array=[Vector2(29, 63), Vector2(32, 65), Vector2(55, 83), Vector2(70, 91), Vector2(70, 91), Vector2(83, 99), Vector2(93, 103), Vector2(106, 109), Vector2(116, 111), Vector2(116, 111), Vector2(127, 113), Vector2(130, 115), Vector2(144, 122), Vector2(153, 124), Vector2(154, 125), Vector2(165, 128), Vector2(181, 133), Vector2(192, 135), Vector2(193, 135), Vector2(203, 139), Vector2(224, 143), Vector2(224, 143), Vector2(235, 146), Vector2(236, 146), Vector2(246, 150), Vector2(259, 152), Vector2(259, 152), Vector2(279, 156), Vector2(289, 156), Vector2(293, 157), Vector2(303, 161), Vector2(308, 163), Vector2(311, 167), Vector2(312, 172), Vector2(311, 177), Vector2(308, 181), Vector2(304, 183), Vector2(299, 184), Vector2(296, 183), Vector2(287, 180), Vector2(278, 180), Vector2(275, 180), Vector2(254, 175), Vector2(241, 173), Vector2(239, 173), Vector2(229, 169), Vector2(219, 167), Vector2(219, 167), Vector2(197, 162), Vector2(196, 162), Vector2(186, 158), Vector2(176, 156), Vector2(175, 156), Vector2(158, 151), Vector2(158, 151), Vector2(147, 148), Vector2(137, 145), Vector2(134, 144), Vector2(120, 136), Vector2(111, 134), Vector2(111, 134), Vector2(100, 132), Vector2(98, 131), Vector2(83, 125), Vector2(83, 125), Vector2(72, 120), Vector2(71, 120), Vector2(58, 111), Vector2(43, 103), Vector2(41, 102), Vector2(17, 84), Vector2(14, 81), Vector2(12, 76), Vector2(13, 71), Vector2(15, 67), Vector2(19, 64), Vector2(24, 63)]
	cc.set_polygon(v)
```

### Minimal reproduction project

N/A
```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment] 2023-11-09 15:59
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment] 2023-11-09 16:02
Your shape simply isn't a complex polygon, it is convex in shape

**Comment by AThousandShips** [comment] 2023-11-09 16:07
Are there any more details to the error message?

**Comment by artlessgames** [comment] 2023-11-09 16:09
Document says: A node that provides a thickened polygon shape (a prism) to
a CollisionObject2D
<https://docs.godotengine.org/en/stable/classes/class_collisionobject2d.html#class-collisionobject2d>
parent
and allows to edit it. The polygon can be concave or convex. This can give
a detection shape to an Area2D
<https://docs.godotengine.org/en/stable/classes/class_area2d.html#class-area2d>
or
turn PhysicsBody2D
<https://docs.godotengine.org/en/stable/classes/class_physicsbody2d.html#class-physicsbody2d>
into
a solid object.

I think it is okay to be a convex.

Error message:

E 0:00:00:0434   test1.gd:9 @ _ready(): Convex decomposing failed!
  <C++ 源文件>      core/math/geometry_2d.cpp:53 @
decompose_polygon_in_convex()
  <栈追踪>          test1.gd:9 @ _ready()
E 0:00:00:0438   decompose_polygon_in_convex: Convex decomposing failed!
  <C++ 源文件>      core/math/geometry_2d.cpp:53 @
decompose_polygon_in_convex()

A Thousand Ships ***@***.***> 于2023年11月10日周五 00:07写道：

**Comment by AThousandShips** [comment] 2023-11-09 16:10
My bad got the case backwards, not relevant at present 🙂

**Comment by artlessgames** [comment] 2023-11-09 16:12
[test.zip](https://github.com/godotengine/godot/files/13310293/test.zip)
Sorry, I'm not familiar with github. Can I upload the project in this way?

**Comment by AThousandShips** [comment] 2023-11-09 16:16
Duplicate of https://github.com/godotengine/godot/issues/27197

**Comment by AThousandShips** [comment] 2023-11-09 16:17
The decomposition breaks because you have two of the same points in a row, removing that should fix this

**Closed by AThousandShips** 2023-11-09 16:16 UTC
Labels: bug, topic:physics, needs testing, topic:2d

**Comment by artlessgames** [comment] 2023-11-09 16:22
Thank you. It worked.
