### ISSUE TITLE
"Fix Silhouette" in Retargeting does not work well on models other than A-pose or T-pose

### ISSUE THREAD

**Issue by fire** [godotengine/godot#65656] opened 2022-09-11 15:23 UTC
### Godot version

https://github.com/godotengine/godot/commit/200b9cde88da485659a6376266af8e9bf7be186f

### System information

Windows 11, GLES3, RTX 3000

### Issue description

https://sketchfab.com/3d-models/valora-twitch-prime-emote-c430ff2028744abfa132774b0771f25d 

> トカゲ — Today at 01:50
If you load it into blender, you can see that the model is a titan...

> トカゲ — Today at 02:02
Since the rest is neither T-pose nor A-pose, the T-poser does not seem to work very well for the fingertips

> トカゲ — Today at 02:11
> Whether or not the T-poser works depends on the rest that is loaded. So I think this PR is important:
> https://github.com/godotengine/godot/pull/40274

>トカゲ — Today at 02:19
> So, the problem is that there are gltfs which have neither A-pose nor T-pose as a bound pose, > but only a pose for the first frame of the animation for about the issue of missing conversions 
maybe

### Steps to reproduce

1. Load godot
2. Setup glb to for retargeting
3. The retargeting doesn't match

### Minimal reproduction project

[valora__twitch_prime_emote.zip](https://github.com/godotengine/godot/files/9542870/valora__twitch_prime_emote.zip)

**Comment by fire** [comment] 2022-09-11 15:24
@TokageItLab I typed up the bug report.

**Comment by TokageItLab** [comment] 2022-09-11 16:10
@fire I don't know what "missing conversions" you are talking about.
Retargeting works fine. The problem is that certain bones are not fixed properly by the T-poser when neither T-pose nor A-pose is used?

**Comment by fire** [comment] 2022-09-11 16:13
Yes. Some bones are unable to be matched while not in A-pose or T-pose. We should do something but allow the animation to pass is not that great.

**Comment by TokageItLab** [comment] 2022-09-11 16:19
I don't see this as a critical bug, well, I will look when I have time whether the algorithm can be improved.

**Comment by lyuma** [comment] 2023-04-28 01:09
I tested this model and it technically works now that #76499 is merged.,
![Screenshot showing the model dancing](https://user-images.githubusercontent.com/39946030/235024730-2b200009-721a-4ad1-b178-4e42e9aed987.png)

However, the problem with this model is it contains several bones which do not fall under Godot's SkeletonProfileHumanoid and animates those bones, so any attempt to share this animation with other models might miss some data

**Comment by Invertex** [comment] 2023-12-11 00:49
This issue is still somewhat relevant I believe, unless I'm missing something.
I've noticed that Fix Silhouette does not work well on animation files that don't have typical bindpose, like for example a running animation. In an attempt to fix bones that are at extreme angles, it can end up not looking anywhere near as proper as the original animation. 

Often animation packages come with a base model that's in a normal bind pose and then a bunch of individual files that only contain a single animation track that has no typical bindpose.

I believe a simple fix to this issue for most cases would be the option for Fix Silhouette to utilize the bone transform values from a target model (and show an error if the target is not a matching rig). This would allow it to fix the animation based on that target's bind pose instead of its own.

**Comment by TokageItLab** [comment] 2023-12-11 00:51
I remember having several conversations with @lyuma about it. There must be some way to select the animation before importing.

**Closed** 2024-03-24 04:13 UTC
Labels: enhancement, usability, topic:import, topic:animation, topic:3d
