### ISSUE TITLE
Without autocomplete if the code has  an error

### ISSUE THREAD

**Issue by sgleto** [godotengine/godot#37564] opened 2020-04-03 22:24 UTC
Hi! I am here to report a bug.

If the code has an error, the autocomplete does not work.

Please, fix that.

**Comment by dreamsComeTrue** [comment] 2020-04-04 07:35
That requires substantial work over Script's code editor.
@vnen is actually working on GDScript refinements, but IDK whether that covers also working on script parser to continue in case of errors.

Temporarily, you can look at the error description (with line number) at the bottom of code editor, and try to fix errors, line by line.

**Comment by Calinou** [comment] 2020-04-04 11:37
Duplicate of #33191.

**Closed by Calinou** 2020-04-04 11:37 UTC

**Comment by Ranoller** [comment] 2020-04-07 08:25
This is not an error, this is a feature.... very useful for me. I see that doesn´t autocomplete and inmediatly i go to last writed lines to add "pass" or ":" or whatever....
