### ISSUE TITLE
enum type in autoload cannot be used in B10 nonexistent function 'has'

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#70560] opened 2022-12-25 15:06 UTC
### Godot version

b10

### System information

win10 vulkan

### Issue description

Enum cannot use the 'has' function, and this problem does not exist in b9

b9:
![b9](https://user-images.githubusercontent.com/14953625/209473169-6abaa253-3738-407c-b190-f3f9a1f0fc5d.png)

b10:
![b10](https://user-images.githubusercontent.com/14953625/209473172-2f2da24c-1bd3-4970-b7f7-ca6702441433.png)

### Steps to reproduce

create a tscn and set autoload . Then use the enum method 

### Minimal reproduction project

[global_enum_test_.zip](https://github.com/godotengine/godot/files/10300183/global_enum_test_.zip)

**Comment by timothyqiu** [comment] 2022-12-26 02:45
Duplicate of #70495

**Closed by timothyqiu** 2022-12-26 02:45 UTC
