### ISSUE TITLE
Inspector tooltips show formatting tags

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#15431] opened 2018-01-07 06:08 UTC
**Godot version:**

master, cd63407

**Issue description:**
Inspector tooltips are showing `[code][/code]` formatting tags in member descriptions from the xml class reference.

![screen shot 2018-01-06 at 9 44 49 pm](https://user-images.githubusercontent.com/3812514/34647074-c25ddb96-f32c-11e7-8e4e-586687644af9.png)

**Comment by Geequlim** [comment] 2018-01-07 06:14
We can get the raw content of bbcode text like `RichTextLabel.get_text()`.
Or show tooltips with RichTextLabel ?

**Comment by poke1024** [comment] 2018-01-07 08:40
I tried using `RichTextLabel` for this a few weeks ago, for some reason it never showed up; might be something with the way `RichTextLabel` computes its size. I think `RichTextLabel` would be nice.

**Comment by Geequlim** [comment] 2018-01-07 09:20
@poke1024 Do you mean the height of the content ? You can get that value by its vscroll control.

**Comment by poke1024** [comment] 2018-01-07 09:24
@Geequlim No, I just mean I didn't manage to have `RichTextLabel` in the tooltip code ever show any visible label; but it would be great if someone tries this/looks into this again.

**Comment by akien-mga** [comment] 2018-01-07 11:52
Ah looks like I had forgotten to open an issue for this.

> We can get the raw content of bbcode text like RichTextLabel.get_text().

The problem is that we have no RichTextLabel here. I did implement a marvellous hack that would instance a RTL, set the bbcode and then get back the raw text to put in the tooltip, and it worked fine, but it was really ugly :D

So there are two possible solutions:
- Make tooltips use RTL so that this formatting works out of the box
- Extract some of the parser logic from RTL and put it in DocData or similar so that the raw XML strings can be rid of their formatting tags when parsed for tooltips

**Comment by akien-mga** [comment] 2018-07-28 08:03
Fixed by 336db8bcd1ab9f08009efc58896510b66f5fe561.

**Closed by akien-mga** 2018-07-28 08:03 UTC
Labels: bug, documentation, topic:editor
