### ISSUE TITLE
Can't change delimiter option on non-parsed csv files (i.e. with the wrong delimiter)

### ISSUE THREAD

**Issue by FabPei** [godotengine/godot#86491] opened 2023-12-24 14:10 UTC
### Tested versions

Godot 4.2 stable (and 4.0 stable)

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3713) - AMD Ryzen 7 6800HS Creator Edition (16 Threads)

### Issue description

CSV files created by (german) MS Excel cant be imported, no matter the separator. The same data when exported via GDocs gets imported.

My guess: MS Excel adds a special BOM to the csv.

### Steps to reproduce

1. Create a new Google docs & Excel table with any translation data, e.g.:
keys;en;de;fr;
Play;Play;wort;word;
Start;Start;wort;word;
2. Export Google docs to csv. Save as Excel table as csv (doesnt matter if UTF8 or not)
3. Copy to Translation folder in Godot
4. Only the GDocs csv is accepted.

Additional steps:
GDocs download .xlsx, open with MS Excel, save as csv -> import wont work too

### Minimal reproduction project (MRP)

![Screenshot 2023-12-24 150602](https://github.com/godotengine/godot/assets/80212635/a0f232a8-f27a-46d6-ae5f-4fdd9511fb0d)

**Comment by Vovkiv** [comment] 2023-12-24 15:58
Can you provide invalid and valid csv files?

**Comment by FabPei** [comment] 2023-12-24 23:43
[GitHub issue from Excel.csv](https://github.com/godotengine/godot/files/13763040/GitHub.issue.from.Excel.csv)
[GitHub issue from GDocs.csv](https://github.com/godotengine/godot/files/13763041/GitHub.issue.from.GDocs.csv)

Invalid is the one from Excel, valid from GDocs.
The problem seems to be related to this Issue: https://github.com/godotengine/godot/issues/38245
Apparently, Excel will always save with BOM, GDocs does not. Maybe a warning should be added that Excel CSV won't work.

**Comment by Vovkiv** [comment] 2023-12-25 08:29
Yeah, https://github.com/godotengine/godot/issues/38245#issuecomment-737246353. For now, I think, it's better to use LibreOffice Calc instead of Microsoft World anyway.

**Comment by FabPei** [comment] 2023-12-31 10:19
> Yeah, [#38245 (comment)](https://github.com/godotengine/godot/issues/38245#issuecomment-737246353). For now, I think, it's better to use LibreOffice Calc instead of Microsoft Excel anyway.

Should i close this issue then and repost it as a feature request?

**Comment by Vovkiv** [comment] 2023-12-31 10:23
> Should i close this issue then and repost it as a feature request?

I think this should be considered as bug that should be fixed in Godot csv importer rather then feature request. But I don't think there something wrong to add proposal (don't forget to link this issue to proposal for better context) without closing this issue. In any case, maintainers close that proposal themself if they don't agree that this should be considered as proposal.

**Comment by AThousandShips** [comment] 2023-12-31 17:57
This isn't necessarily about the BOM, this file is in ISO-8858-15, not in utf8 at all, so the encodings are wrong

**Comment by FabPei** [comment] 2023-12-31 18:17
> This isn't necessarily about the BOM, this file is in ISO-8858-15, not in utf8 at all, so the encodings are wrong
> 
> Supporting this would require supporting this encoding, it seems to match extended ascii (depending on if it's ISO-8859-15 or ISO-8859-1, only supported if it's the latter), but we'd have to change some methods and would require adding this to the `FileAccess` format
> 
> I'm not sure this is a worthwhile change to cover this strange format of Excel, which is largely non-standard

I didnt think, that it was entirely different coding. Strange that its such a specific thing. Is it known if this issue with MS Excel csv exist, if an non-european MS Excel version is used for exporting?

**Comment by AThousandShips** [comment] 2023-12-31 18:21
I have no clue, I just know that the file you uploaded is not in utf8, Windows largely use non-utf formats for legacy reasons, but this is largely outside the scope of this, and I think this should be handled by converting the files or using a compatible editor, rather than adding additional systems to the editor

**Comment by AThousandShips** [comment] 2023-12-31 22:23
The real issue here is that the import menu is unavailable for a resource that can't be parsed, meaning you can't change it to accept colon instead of comma, as the encoding is something I don't think we should change, it's a lot of complicated extra steps and it only works for a small code range

**Comment by inhalt120g** [comment] 2024-01-01 01:36
Excel can export CSV in the correct format, but it has to be set up appropriately when exporting. I just tested it:
![localization test with a file from Excel](https://github.com/godotengine/godot/assets/106015575/f319e1b7-6381-4a0c-b23e-c383755e99d5)

The Excel file was made in Excel set to Japanese, on MacOS set to Chinese.
Here is what the right setting looks like when exporting (it probably looks different on Windows but it should be somewhere there):
![スクリーンショット 2024-01-01 9 34 24](https://github.com/godotengine/godot/assets/106015575/b1d89ee0-d9a3-4352-b564-c7307df0a1b3)

**Comment by FabPei** [comment] 2024-01-01 11:14
> The real issue here is that the import menu is unavailable for a resource that can't be parsed, meaning you can't change it to accept colon instead of comma, as the encoding is something I don't think we should change, it's a lot of complicated extra steps and it only works for a small code range

Yeah i guess that makes sense

**Comment by FabPei** [comment] 2024-01-01 11:14
> Excel can export CSV in the correct format, but it has to be set up appropriately when exporting. I just tested it: ![localization test with a file from Excel](https://private-user-images.githubusercontent.com/106015575/293527062-f319e1b7-6381-4a0c-b23e-c383755e99d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDc4NDMsIm5iZiI6MTcwNDEwNzU0MywicGF0aCI6Ii8xMDYwMTU1NzUvMjkzNTI3MDYyLWYzMTllMWI3LTYzODEtNGEwYy1iMjNlLWMzODM3NTVlOTlkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjdiMDJhOTJiZWQxZTkxZDljZGEzNWQ1YThhZWI1N2U4NWJmYjg3N2NiYjA5Mjc1MzIzODc2Nzg4NzM2MDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plmCqRj3pTvvTfzSg4sF5prvOmD3FGGZ74z6NDR1lvk) [ ![localization test with a file from Excel](https://private-user-images.githubusercontent.com/106015575/293527062-f319e1b7-6381-4a0c-b23e-c383755e99d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDc4NDMsIm5iZiI6MTcwNDEwNzU0MywicGF0aCI6Ii8xMDYwMTU1NzUvMjkzNTI3MDYyLWYzMTllMWI3LTYzODEtNGEwYy1iMjNlLWMzODM3NTVlOTlkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjdiMDJhOTJiZWQxZTkxZDljZGEzNWQ1YThhZWI1N2U4NWJmYjg3N2NiYjA5Mjc1MzIzODc2Nzg4NzM2MDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plmCqRj3pTvvTfzSg4sF5prvOmD3FGGZ74z6NDR1lvk) ](https://private-user-images.githubusercontent.com/106015575/293527062-f319e1b7-6381-4a0c-b23e-c383755e99d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDc4NDMsIm5iZiI6MTcwNDEwNzU0MywicGF0aCI6Ii8xMDYwMTU1NzUvMjkzNTI3MDYyLWYzMTllMWI3LTYzODEtNGEwYy1iMjNlLWMzODM3NTVlOTlkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjdiMDJhOTJiZWQxZTkxZDljZGEzNWQ1YThhZWI1N2U4NWJmYjg3N2NiYjA5Mjc1MzIzODc2Nzg4NzM2MDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plmCqRj3pTvvTfzSg4sF5prvOmD3FGGZ74z6NDR1lvk) [ ](https://private-user-images.githubusercontent.com/106015575/293527062-f319e1b7-6381-4a0c-b23e-c383755e99d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDc4NDMsIm5iZiI6MTcwNDEwNzU0MywicGF0aCI6Ii8xMDYwMTU1NzUvMjkzNTI3MDYyLWYzMTllMWI3LTYzODEtNGEwYy1iMjNlLWMzODM3NTVlOTlkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjdiMDJhOTJiZWQxZTkxZDljZGEzNWQ1YThhZWI1N2U4NWJmYjg3N2NiYjA5Mjc1MzIzODc2Nzg4NzM2MDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plmCqRj3pTvvTfzSg4sF5prvOmD3FGGZ74z6NDR1lvk)
> 
> The Excel file was made in Excel set to Japanese, on MacOS set to Chinese. Here is what the right setting looks like when exporting (it probably looks different on Windows but it should be somewhere there): ![スクリーンショット 2024-01-01 9 34 24](https://private-user-images.githubusercontent.com/106015575/293527111-b1d89ee0-d9a3-4352-b564-c7307df0a1b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDc4NDMsIm5iZiI6MTcwNDEwNzU0MywicGF0aCI6Ii8xMDYwMTU1NzUvMjkzNTI3MTExLWIxZDg5ZWUwLWQ5YTMtNDM1Mi1iNTY0LWM3MzA3ZGYwYTFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTU0NWQ0NTdjOTU5OWYyNmU3OTRiODBlMmIyZTllMWQ3YWY1Y2ZlNDk4ZjcxMjlmZGYzN2JkNTg2YmNhZDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EsKyU1aQezMF5AQvZ67_c2wuEmlLNOyPZ31oOPamhGA)

My MS Excel exports semicolon separated csv no matter if the chosen option is UTF csv or normal csv

**Comment by AThousandShips** [comment] 2024-01-01 11:15
Indeed, so that's really a Excel issue, but it would be good to be able to configure non-correct csv files directly, as currently the import configuration menu is empty for these, unsure how easy this would be to achieve though

**Comment by Calinou** [comment] 2024-01-01 13:23
I believe supporting encoding conversion requires integrating a library like `iconv` in Godot, which is a no-go for licensing (LGPL) and binary size reasons.

I would just document this in the error message and tell the user to use the **CSV UTF-8** export mode.

**Comment by AThousandShips** [comment] 2024-01-01 13:36
As far as I can find the BOM isn't an issue, it would be stripped by the loading, the issue is the delimiters, and that an import file with incorrect delimiters can't be configured to be imported with the correct ones (i.e. the ones in the file), the workaround is to change the default settings in the project settings, but unsure how that affects already imported files

**Comment by Calinou** [comment] 2024-01-01 15:45
It should be feasible to devise an heuristic to automatically select the correct delimiter by picking the one that returns the highest amount of columns for the first row.

**Comment by FabPei** [comment] 2024-01-01 16:20
> I believe supporting encoding conversion requires integrating a library like `iconv` in Godot, which is a no-go for licensing (LGPL) and binary size reasons.
> 
> I would just document this in the error message and tell the user to use the **CSV UTF-8** export mode.
> 
> Regarding the BOM exported by Excel, I wonder if we can strip it when reading the file to act like it's not there in the first place… This would most likely be a specific hack done in the CSV importer, rather than something done in FileAccess.

I am wondering why choosing this export option in Excel still leads to a semicolon separated csv (in my case). Perhaps it is a regional thing? https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-change-semicolon-to-comma-when-saving-csv/cf7c9537-82da-448d-9516-82f3a4b13fae

**Comment by Calinou** [comment] 2024-01-22 17:58
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82002.

**Closed by Calinou** 2024-01-22 17:58 UTC
Labels: enhancement, discussion, topic:import
