### ISSUE TITLE
gdscript: Unexpected "Literal" in class body

### ISSUE THREAD

**Issue by xarses** [godotengine/godot#66577] opened 2022-09-29 02:46 UTC
### Godot version

4.0-beta1

### System information

Linux, Pop_OS

### Issue description

When converting 3.4/3.4 Projects, string Literals where allowed in the parser as a form of docstring (supposedly similar to python) However in 4.0, this raises a parser error.

![image](https://user-images.githubusercontent.com/2107834/192927101-baf9118e-2a4e-4d48-b35a-56f0ead35880.png)

Expected result:
3-to-4 conversion should have migrated these to a proper format
documentation should exist mentioning that these are no longer allowed, and what we can use instead

### Steps to reproduce

Convert or create a project with a (string) Literal in the body of a gdscript class.

```gdscript
class Hello extends ServerObsMessage:
	"""
	FROM obs
	TO client
	"""
```

Source: https://github.com/you-win/obs-websocket-gd/blob/master/addons/obs-websocket-gd/obs_websocket.gd#L142-L146

### Minimal reproduction project

https://github.com/you-win/obs-websocket-gd

**Comment by Calinou** [comment] 2022-09-29 15:41
Multiline comments don't exist in GDScript. Using several comment lines starting with `#` is recommended instead.

**Comment by Chaosus** [comment] 2023-01-17 07:29
Duplicate of https://github.com/godotengine/godot/issues/62330

**Closed by Chaosus** 2023-01-17 07:29 UTC
Labels: bug, topic:gdscript
