### ISSUE TITLE
D-pad gets stuck on Retrolink SNES controller

### ISSUE THREAD

**Issue by cheshirecat416** [godotengine/godot#44100] opened 2020-12-04 22:36 UTC
**Godot version:**
3.2.3 official

**OS/device including version:**
Windows 10 home

**Issue description:**
I am attempting to demonstrate controller support on my project. I have a new Retrolink SNES controller. This controller works properly when I run the SDL2 Gamepad Tool. I can generate a mapping for it. 

03000000790000001100000000000000,Retrolink SNES Controller,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:-a4,dpdown:+a4,dpleft:-a3,dpright:+a3,

When I attempt to use this controller in Godot, all buttons work properly with the exception of the D-pad. When I press a D-pad button it registers being pressed but never registers being raised. I see this issue not only in my own project, but also in the standard Godot "Joypads Demo" project. It may be a unique issue to this controller, but the controller works fine in the SDL2 Gamepad tool, as well as with ZSNES. 

This image shows all of the D-pad arrows stuck in the depressed position on the Joypads Demo.
![controller_issue](https://user-images.githubusercontent.com/75506225/101221991-da26df00-3656-11eb-83fb-5ff025804450.png)

This is the controller:
https://www.amazon.com/gp/product/B01MYUDDCV/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Steps to reproduce:**
I am not sure how someone can reproduce the error without the controller, but any help would be appreciated. 

**Minimal reproduction project:**
See above.

**Comment by davthedev** [comment] 2020-12-05 12:04
I can confirm this bug was introduced in 3.2.3 too.

In 3.2.2:
This gamepad model returns "USB Controller" as name.
D-pad presses are seen as left stick axis direction changes.

In 3.2.3:
Gamepad model is "Retrolink USB controller"
D-pad presses are seen as D-pad presses which are never released.
Some button mappings are also changed in comparison with 3.2.2.

It may be caused by the SDL2 Gamepad module on top of which Godot is built.
This modules uses a translation table to map generic gamepad buttons to a standardized gamepad layout, in a quite similar fashion as XInput. 
Gamepads are matched using a combination of variables, including the operating system. This is why the same gamepad may behave differently in the same Godot game on Windows and Linux, for example.

For instance the table says "Button 3 on that brand of controller on operating system X = A button / button 0 (not sure) on the standardized layout".

The translation table is updated from time to time, and Godot 3.2.3 may have used an updated version.
Here is the project that contains the mapping table: https://github.com/gabomdq/SDL_GameControllerDB

The good news is that, as a workaround, it is possible to override those mappings at runtime.
1. Use SDL Gamepad Tool to generate a mapping string: https://generalarcade.com/gamepadtool/ . Repeat this step on each different operating system you plan to release your game on.
2. In your project, call `Input.add_joy_mapping()` to take the updated mapping into account. You probably need to call it multiple times to feed the fixed mapping for each operating system. A good place is an autoload's `ready()` call.

My approach for this gamepad model:
`

    var mappings = [
        "03000000790000001100000010010000,Retrolink SNES Controller,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftx:a0,lefty:a1,platform:Linux,",
        "03000000790000001100000000000000,Retrolink SNES Controller,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftx:a0,lefty:a4,",
    ]
    for mapping in mappings:
        Input.add_joy_mapping(mapping, true)
`

**Comment by akien-mga** [comment] 2020-12-05 12:15
Can you test 3.2.4 beta 3?

**Comment by madmiraal** [comment] 2020-12-05 14:12
Duplicate of #43603, fixed with #42799, and backported to 3.2 (#42800) and included in 3.2.4.beta2.

**Closed** 2020-12-05 14:27 UTC
Labels: bug, topic:input

**Comment by cheshirecat416** [comment] 2020-12-06 17:43
I can confirm it worked in 3.2.4 beta 3. Thanks!
