### ISSUE TITLE
Middle mouse button + Shift defuncts window chrome

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6424] opened 2016-09-07 19:06 UTC
**Operating system or device - Godot version:**
Windows 10 x64 with Anniversary Update, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
As soon as I press the middle mouse button and hit Shift while doing so, either in the Godot engine editor or any game, I no longer see hover effects over my caption buttons, nor does clicking them or the title bar work anymore, e.g., I can't move the window or close it. Alt+F4 is also defunct. The system menu does not open when clicking the window icon.

It sometimes randomly seems to solve itself so that the chrome works again, but that's rarely the case.

**Steps to reproduce:**
Hit the middle mouse button / mouse wheel over the editor or a game window and the Shift key while doing so, and then try to use the window border.

**Comment by Hinsbart** [comment] 2016-09-09 12:27
Mhh, I'm not able to reproduce this.

**Comment by RayKoopa** [comment] 2016-09-09 15:10
I noticed it does not happen all the time to me, but for 90% of it. I remember this was an annoying issue in 2.0 too for me. Let me try to get some cleanly reproducible state and check if not something on my PC causes this issue (I'm not using any special mouse drivers, but a window docking application, I try to disable it).

**Comment by RayKoopa** [comment] 2016-09-11 12:01
I noticed it happens only in combination with holding down `Shift` while having the middle mouse button pressed down. No further programs run on my PC which could intercept something along the lines, and it happens in new or all the sample projects.

**Comment by vnen** [comment] 2018-04-04 17:11
Probably fixed by #15905 (and #15908 for 2.1).

**Comment by RayKoopa** [comment] 2018-04-04 17:36
I definitely don't have a horizontal scroll wheel and it still bugged out in the latest 3 version AFAIK.

**Comment by vnen** [comment] 2018-04-05 00:54
Well, I can't reproduce this at all, not in 2.1.4 nor in 3.0.2 (using Windows 10). Can you try and test it again?

**Comment by RayKoopa** [comment] 2018-04-05 08:35
Since it happened at quite random moments in the middle of working with Godot, I can try, but not right now as I'm not really using Godot anymore :( Right now, I can only tell my mouse has no horizontal wheel, and in the final 3.0.0 I tested some time ago, the chrome still started to lock up.

Some quick test right now did not cause the chrome to freeze, but it was not a thorough test.

**Comment by Anutrix** [comment] 2020-04-12 15:02
Is this reproducible on latest master or 3.2 branch?

**Comment by Calinou** [comment] 2021-05-15 19:49
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.

**Closed by Calinou** 2021-05-15 19:49 UTC
Labels: bug, needs testing, platform:windows, topic:core
