### ISSUE TITLE
Time scale affects PinJoint2D's softness

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5418] opened 2016-06-25 21:51 UTC
**Operating system or device - Godot version:**
Linux 64 bit, 2.0.3

**Issue description** (what happened, and what was expected):
When I have a RigidBody2D connected to StaticBody2D using a PinJoint2D which has softness > 0, and then playing around with OS.set_time_scale(), the connected RigidBody hinges around. I don't think the time scale should affect the softness of a PinJoint2D.

**Comment by reduz** [comment] 2016-07-07 00:55
if you could make a simple demo scene, it would be very appreciated

**Comment by timoschwarzer** [comment] 2016-07-07 09:24
[gd-pinjoint-timescale.tar.gz](https://github.com/godotengine/godot/files/351779/gd-pinjoint-timescale.tar.gz)
@reduz here you are ;-)
Just let the bodies fall down on the platform, the set the time scale to 0.5 or 0.25. You'll see the platforms going up.

**Comment by bojidar-bg** [comment] 2017-01-11 11:16
Pretty bump, what is going on with this issue, any workarounds, is it still valid, etc..

**Comment by timoschwarzer** [comment] 2017-01-12 15:10
I will try if the current master compiles and works...

**Comment by timoschwarzer** [comment] 2017-01-12 15:50
Yes, this issue is still valid and there doesn't seem to be a workaround for it.

**Comment by bojidar-bg** [comment] 2017-01-12 20:22
@timoschwarzer Thanks for confirming!

**Comment by timoschwarzer** [comment] 2018-01-17 10:34
Has this been fixed in 3.0?

**Comment by pwab** [comment] 2020-05-02 17:05
Hey @timoschwarzer I tried to reproduce this issue with your sample file. Because the issue is very old the demo scene had to be updated. What I changed to make it work with Godot 3.2.1:

* Updated to newest project.godot
* Changed Scene from `Node` to `StaticBody` so the PinJoints are able to work with it
* Changed `OS` to `Engine` because `time_scale` moved there

Then I was able to run it and it seems that there is no issue with softness anymore. I'm not sure if my updates changed the way the demo scene worked so would you look into it again and confirm that the issue is not present anymore? Here is the updated project: 
[gd-pinjoint-timescale.zip](https://github.com/godotengine/godot/files/4568288/gd-pinjoint-timescale.zip)

I'm also working on Windows 10 x64 right now. Not sure if this can still be reproduced on Linux machines.

**Comment by madmiraal** [comment] 2020-08-31 14:56
@pwab Thanks for updating the minimal reproduction project. In the original project, the `Default Gravity` is set to 980. If you set the `Default Gravity` to 980, you will notice the issue described.

For everyone's convenience, I've updated @pwab's project with the `Default Gravity` set to 980, to show that the issue still exists in 3.2.2:
[gd-pinpoint-timescale.zip](https://github.com/godotengine/godot/files/5150999/gd-pinpoint-timescale.zip)

**Comment by pwab** [comment] 2020-08-31 21:54
Hey @madmiraal thanks for making this clear. I haven't looked into your updated project yet but if this is a _gravity + time_scale_ thing maybe it is somehow related to #6323?

**Comment by Calinou** [comment] 2022-03-05 21:10
I tried to adjust the softness depending on time scale in the project, but it doesn't appear to be a linear relationship. I let the RigidBodies rest for ~15 seconds on each run:

### Time scale 1.0 with softness = 10

![2022-03-05_22 06 07](https://user-images.githubusercontent.com/180032/156900003-d1ad762f-1aee-473b-8c4b-5479bc5cd272.png)

### Time scale 0.5 with softness = 10

![2022-03-05_22 06 25](https://user-images.githubusercontent.com/180032/156900001-e116e1ce-bce5-4190-85c0-4ee5c2cffedf.png)

### Time scale 0.5 with softness = 20

*The inspector limits PinJoint2D softness to `16.0`, so this must be done with a script.

![2022-03-05_22 07 29](https://user-images.githubusercontent.com/180032/156900005-9025d44c-caf7-4a56-b76a-929227344cda.png)

**Comment by pwab** [comment] 2023-06-21 11:36
This issue is still valid in Godot 4.1 (beta 2) with Godot Physics. It more or less can be summarized that all parts of the physics engine are affected by a `Engine.time_scale` other than 1 (especially above 1). This was discussed in https://github.com/godotengine/godot/issues/24334 and there might be a fix with https://github.com/godotengine/godot/pull/30798.

I just wanted to drop that here because I noticed that this issue is still open and was not mentioned in https://github.com/godotengine/godot/pull/30798. @Calinou maybe this issue could be closed as duplicate in favor of https://github.com/godotengine/godot/issues/24334?

**Comment by Calinou** [comment] 2023-06-21 19:52
Closing in favor of https://github.com/godotengine/godot/issues/24334.

**Closed by Calinou** 2023-06-21 19:52 UTC
Labels: bug, confirmed, topic:physics
