### ISSUE TITLE
visual shader cant connect nodes

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#30691] opened 2019-07-19 15:54 UTC
**Godot version:**
3.2 Dev (Also tested with 3.1 stable)

**OS/device including version:**
Windows 10

**Issue description:**
I am sure that this is something stupid from my side and not an issue but i'v quit trying to work with visual shaders 3 times already because of it so i'd say its worth opening an issue at this point.
I can't seem to be able to connect the nodes for some reason. I expected that all i have to do is click and drag. Is there anything that has to be activated? I'm i missing some vital node? I have tried left, middle and right mouse buttons without success.

![Visual shaders](https://user-images.githubusercontent.com/1850856/61548528-937f1780-aa56-11e9-9cca-f42f774c02a5.gif)

**Comment by Chaosus** [comment] 2019-07-19 16:02
I cannot reproduce this.. can you try Visual Scripts and say if its not working too ?

**Comment by zaksnet** [comment] 2019-07-19 16:06
> I cannot reproduce this.. can you try Visual Scripts and say if its not working too?

Same with Visual Scripts. This seems to only affect my main project, i just created a new one and it works as expected. Is there any more info i can provide? Also, autocomplete has stopped working in my main project.

**Comment by zaksnet** [comment] 2019-07-19 16:09
I also tried deleting the `AppData\Roaming\Godot\projects\ProjectFolder` at some point but that made no difference.

**Comment by zaksnet** [comment] 2019-07-19 16:25
I found how to reproduce it:
- Create a new theme from the default editor theme
![Screenshot_16](https://user-images.githubusercontent.com/1850856/61550332-d8a54880-aa5a-11e9-9772-a24c059a9d2a.png)
- Assign it as the default theme for a project
- Restart the project

**Comment by Anutrix** [comment] 2019-07-19 17:03
Are you getting any error messages?

**Comment by zaksnet** [comment] 2019-07-19 18:13
> Are you getting any error messages?

Nope.

**Comment by bojidar-bg** [comment] 2019-07-20 17:19
Duplicate of #29404, not sure which one is better to be closed though.

**Comment by Chaosus** [comment] 2019-07-30 14:57
Closed as duplicate of #29404

**Closed by Chaosus** 2019-07-30 14:57 UTC
Labels: bug, topic:editor
