### ISSUE TITLE
GDScript 2.0: 0/int(variable) ignores zero division errors

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#62765] opened 2022-07-06 05:43 UTC
### Godot version

4.0alpha11

### System information

Windows 10, GLES3,  NVIDIA Quadro P2000

### Issue description

Using `0/int(variable)` appears to make zero division errors stop working even if the variable is zero. As a result, the game crashes without warning.

```
extends Node2D

var test = 0
var test2 = 0
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	# This results in an error "Division by zero error in operator '/'."
#	test2 = 0/test
	# This causes crash without displaying an error.
	test2 = 0/int(test)
```

### Steps to reproduce

1. Make a new project 
2. Make one node in the tree(probably its class doesn't matter)
3. Copy the code above, attach it to the node and run the project

**Comment by Calinou** [comment] 2022-07-09 19:20
Duplicate of https://github.com/godotengine/godot/issues/59556.

**Closed by Calinou** 2022-07-09 19:20 UTC
Labels: bug, topic:gdscript, confirmed
