### ISSUE TITLE
Light2D misapplies blending when inside nested Viewports

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#71357] opened 2023-01-13 21:41 UTC
### Godot version

3.5.1 stable

### System information

Windows 10 x64, GLES3 with HDR

### Issue description

When using Viewports containing scenes or nodes that are lit by Light2D, the lighting appears to be applied multiple times or with a cumulative effect.  This is most obvious when HDR is enabled for Viewports with "3D" intent, but the effect (and possibly offset alignment) of Light2D may be affected regardless of HDR capability, linear color conversion, and parent container's light mask.  Possibly related to #34673.  

Example:
![image](https://user-images.githubusercontent.com/1023003/212423774-3de0c380-cd3b-40a8-b678-5532fdc9b51f.png)
![image](https://user-images.githubusercontent.com/1023003/212423814-84e6dd7d-9fa7-4345-9e13-9c60ca0ea5c3.png)

The effect is most obvious with "additive" blending mode.  It can be observed in all blending modes however, with different effects depending on the blend mode.

### Steps to reproduce

1.  Create a lit scene or sprite.
2. Create a Viewport and a container to hold it in.
3. Move scene inside of Viewport.
4. (optional)  Nest scene inside multiple viewports and scenes

### Minimal reproduction project
To use, move `NormalMaps1` from the scene root into and out of the child Viewport node to observe the effect.
[MinimalLightTest.zip](https://github.com/godotengine/godot/files/10415603/MinimalLightTest.zip)

**Comment by Calinou** [comment] 2023-01-13 21:58
Duplicate of https://github.com/godotengine/godot/issues/8685, https://github.com/godotengine/godot/issues/46153 and/or https://github.com/godotengine/godot/issues/45615.

**Closed by Calinou** 2023-01-13 21:58 UTC
