### ISSUE TITLE
Keyboard shortcut for "Run Project" does not work while in built-in script editor.

### ISSUE THREAD

**Issue by konsuko** [godotengine/godot#67569] opened 2022-10-18 11:43 UTC
### Godot version

4.0.beta3.official

### System information

macOS 12.4, Apple Silicon

### Issue description

Pressing the keyboard shortcut for "Run Project" when inside the built-in script editor does not work.
One has to first click on something else in the editor, like e.g. somewhere inside the "Scene" tab, for it to work like intended.

I am not sure if this is intentional (feels like it), but it feels wrong, because that keyboard shortcut is  not mapped to anything else within the built-in editor.

It seems like an easy fix and would be appreciated, since it introduced a little bit of unnecessary friction every time one edits a script and wants to try things out.

### Steps to reproduce

1. Open any project
2. Open a script in the built-in script editor window
3. After editing the script, save changes with the keyboard shortcut (Cmd + S), then press the shortcut to "Run Project" (Cmd + B on macOS, probably Ctrl + B on Windows, Linux)

### Minimal reproduction project

Not necessary

**Comment by Calinou** [comment] 2022-10-18 13:02
Duplicate of https://github.com/godotengine/godot/issues/56961.

**Closed by Calinou** 2022-10-18 13:02 UTC
