### ISSUE TITLE
Alpha antialiasing modes do not work

### ISSUE THREAD

**Issue by LauPhi** [godotengine/godot#65340] opened 2022-09-04 19:14 UTC
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Windows 10, Vulkan Clustered

### Issue description

When using transparency option 'Alpha scissor', the alpha antialiasing options do not work.  
Switching between them and changing the 'Alpha antialiasing edge' does nothing.  

![Capture](https://user-images.githubusercontent.com/14290756/188329814-dde31d99-5987-4526-ace0-d06bb1d5dd3a.PNG)

Aliasing is not really clear in the image but it is in the MRP.

### Steps to reproduce

Use a transparent material with 'Alpha scissor' transparency option.  
Switch between alpha antialiasing modes.  
Nothing changes.  

### Minimal reproduction project

[AlphaAntialiasingModeDoesNotWork.zip](https://github.com/godotengine/godot/files/9485351/AlphaAntialiasingModeDoesNotWork.zip)

**Comment by Calinou** [comment] 2022-09-04 19:33
Duplicate of https://github.com/godotengine/godot/issues/64501.

**Closed by Calinou** 2022-09-04 19:33 UTC
