### ISSUE TITLE
find_next_valid_focus hangs the engine when the node is hidden

### ISSUE THREAD

**Issue by Ryhon0** [godotengine/godot#62514] opened 2022-06-29 11:18 UTC
### Godot version

3.4.4 mono, 3.5 rc5 mono

### System information

Arch Linux

### Issue description

Calling `find_next_valid_focus` on a node that's hidden causes the engine to hang.

### Steps to reproduce

* Create a control
* Set visibility to hidden
* Run `find_next_valid_focus` on it

### Minimal reproduction project

[valid_focus.zip](https://github.com/godotengine/godot/files/9009940/valid_focus.zip)

**Comment by KoBeWi** [comment] 2022-06-29 11:36
Duplicate of #49975

**Closed by KoBeWi** 2022-06-29 11:36 UTC
