### ISSUE TITLE
sub window focus and autoswitching is confusing

### ISSUE THREAD

**Issue by raould** [godotengine/godot#6655] opened 2016-09-30 00:06 UTC
**Operating system or device - Godot version:**
linux ubuntu 16.04.1 lts 64 bit running mate wm (not ubuntu wm)
v2.1.stable.official

**Issue description** (what happened, and what was expected):
the relationship among the sub-windows is confusing.

it sorta makes sense to me that when i switch to a different scene tab, the central editor window changes to whatever i was last working on the scene, ok.

but the reverse doesn't happen: if i use the left/right arrows of the central editor pane to go back through history of scripts i've been editing, it doesn't change the scene tab, and it doesn't change the tree.

which means i can easily get confused/worried/lost about "wait am i editing the right file? i thought i'd created this file in another scene?!" etc.

**Comment by Zylann** [comment] 2016-09-30 12:35
The script history is not part of the tab switcher, it's part of the script editor.
so the actual issue is that when you want to go back to a previous script (and only in this case), the history should also remember which scene you had opened at the time. I guess you also want it to re-open if you closed it?

**Comment by raould** [comment] 2016-10-02 00:29
I kinda feel like pretty much everything about the "relationships" among them all is confusing to me. For example, when something goes wrong at runtime and the debugger stops and shows a line of code, I feel like I have no idea where that code actually lives (in what node), what it is related to, just by looking at the windows.

**Comment by Zylann** [comment] 2016-10-02 00:36
Having the path to the node where an error occurred would be handy, I like it. However it's a different issue you are talking about.

When you write a script, it doesn't only go inside the specific node you put it on. You can attach (aka instance) it wherever you like, as long as the node is compatible. That's why, for example, the root node of a scene can use a script (and the script editor can open it when the scene opens), but a script can be used by multiple scenes.

**Comment by raould** [comment] 2016-10-02 00:44
yeah, i agree and understand that it is not a 1-to-1 relationship. :-) but... i feel like that only underscores that the way the things are currently linked is confusing. probably there are ux people who know a canonical industry standard solution to such things for ides.

for example, i assume that even though a gdscript might be associated with more than one node, only one node is running it at a time. thus the debugger should know which scene & node to switch focus to?

**Comment by Zylann** [comment] 2016-10-02 00:51
It could be as simple as opening the script and the scene when the error is met. However i don't feel it would be good when breaking, because I don't want to keep on opening all scenes in my project just because the execution flow got from one node to another xD
But again, I see two issues here. You should consider posting anothe issue about the debugging one.

**Comment by vnen** [comment] 2016-10-02 02:09
There a few problems with this detection of what does the script belong to. One is that Resources can have scripts too, so what would you do? Maybe open in the Inspector, but it might go unnoticed too. Also, scripts are not always in scenes: they might be a singleton or loaded by other scripts.

Finally, you don't want to open scenes. If it's already open, fine, but depending on the scene it might take a while to load from disk and thus it'll slow down the workflow.

Now, while auto-opening scene is pretty much a no-no, it's possible (to a certain extent) to detect what are the owners of a script, as you can do with any resource. Making that more clear in the interface, especially in the debugger, might be a good improvement.

**Comment by Noshyaar** [comment] 2018-04-06 11:43
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ddekany** [comment] 2018-04-20 18:10
This usability issue is still present in Godot 3.

An easy to fix cause of the confusion (among newcomers) is that when you open a script, it looks like as if the script editor is inside the recently selected scene tab. It's a simple visualization issue, but I believe it has substantial negative cognitive effect. Also, it's just bad UI design, and thus makes a bad impression.

Regarding switching back and forth between the script and one of the related scenes... it doesn't have to be perfect and universal, it just has to be handy. How about adding a single button and single hot key that does switching between scene and script, both directions. If you are switching from scene to script, there's no ambiguity, easy. The other direction you could do this:
1. If I have switched to the script from a scene in the past, then just switch back to that scene (to the last one, if there were more such scenes).
2. Otherwise, see if there's a tscn with the same file name as the script (ignoring the file extension and upper- VS lowercase), and if so, switch to that.
3. Otherwise pop up a dialog and tell the user that you can't do this. (This can be further improved by offering a search for scenes/nodes that refer to the script. That's a useful functionality anyway.)

BTW, I think there's a deeper UI design issue here though: separating scenes and scripts as it is now is maybe a bad idea. At least it's certainly confusing. They are all just files I'm working on. If you have used IntelliJ or Eclipse, there all kind of files are in the same list of open files (they all just have tabs in the same tab list). Of course they look differently depending on the file type when you switch to them, but otherwise they are equals; just files you edit. Thus, you can navigate between them with the same functions (like Ctrl[+Shift]+Tab between them back and forth, Ctrl+E and filter-with-typing among them, etc.). Then all this confusion doesn't even start, as there's exactly one "active" file. Note that switching between scene and script is still useful and is compatible with this approach as well.

**Comment by Calinou** [comment] 2020-07-16 09:58
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-07-16 09:58 UTC
Labels: discussion, enhancement, topic:editor, usability
