### ISSUE TITLE
RichTextLabel's BBCode disappears when the window is resized if a DynamicFont is used

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#22203] opened 2018-09-18 03:44 UTC
**Godot version:** 3.1 8f33542

**OS/device including version:** Linux

**Issue description:** A RichTextLabel using a DynamicFont and `bbcode_enabled = true` will clear its text on resizing the window. This happens when the text is set with `append_bbcode`, `parse_bbcode` or `add_text`. This also happen when `text` is set in code or in the editor, but not with `bbcode_text` for some reason. I mentioned this in #18835 a while ago but I should have posted an issue then.

**Steps to reproduce:** Create a RichTextLabel and give it a DynamicFont. Enable BBCode and call parse_bbcode. Text will be cleared on resizing the window.

**Minimal reproduction project:** [TT.zip](https://github.com/godotengine/godot/files/2391094/TT.zip) Press space to show some text then resize the window.

**EDIT: The same thing will also happen if the theme is changed.**

**Comment by Kinsman** [comment] 2018-12-13 23:22
It might not be just that the text disappears, but the text reverts to what its original value was in the editor. I found that the RichTextLabel, with BBcode enabled, would change back to its placeholder text when the window resized.

**Comment by bojidar-bg** [comment] 2018-12-14 11:52
Same issue as #24173?

**Comment by isaacremnant** [comment] 2018-12-14 15:41
> Same issue as #24173?

I think so? It looks like RichTextLabel doesn't store its text and only draws it, so any update will discard what is already there.

**Comment by akien-mga** [comment] 2018-12-14 20:18
Closing as duplicate of #24173 then (newer but with some more activity), I'll mention there that window resize + DynamicFont is also a trigger.

**Closed by akien-mga** 2018-12-14 20:18 UTC
Labels: bug, topic:core

**Comment by mishkarch** [comment] 2022-07-02 16:07
Hi all! This bug is still present in versions 3.4.4 stable and 3.5 RC 5.
In minimal reproduction project from topic starter, but if in scene inspector's bbcode_text are not empty.

**Comment by akien-mga** [comment] 2022-07-02 16:11
This issue was fixed 4 years ago. Please open a new issue if you can reproduce something similar, with a reproduction project updated for 3.4.4 / 3.5 RC 5.
