### ISSUE TITLE
Error compiling android export templates - windows 7 and MinGW

### ISSUE THREAD

**Issue by Squatnet** [godotengine/godot#17829] opened 2018-03-28 19:08 UTC
**Godot version:**

3.0.2 (source)

**OS/device including version:**

Windows 7 64bit
python 3.5
scons 3.0

**Issue description:**

Encountered error compiling android export templates with firebase module. compiles successfully on linux
    
```
scons: Reading SConscript files ...
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
Building for Android (armv7) (with NEON)
Using NDK unified headers
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] ←[91mLinking Static Library ←[95m==> ←[93mmodules\libmodules.android.opt.armv7.neon.a←[0m
scons: *** [modules\libmodules.android.opt.armv7.neon.a] The filename or extension is too long
scons: building terminated because of errors.
```

**Steps to reproduce:**
Compile export templates in windows

**Comment by Squatnet** [comment] 2018-03-28 19:09
Possibly same issue as #3443 #3265 #6844

**Comment by Calamander** [comment] 2018-11-04 04:29
Moving C:\Program Files (x86)\Android\android-sdk directory to C:\Android\android-sdk (and fixing PATH's after the operation) helped me solve this problem.

**Comment by KoBeWi** [comment] 2020-06-17 07:19
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc1](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-1))?

**Comment by KoBeWi** [comment] 2020-09-28 12:41
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 12:41 UTC
Labels: bug, platform:windows, topic:buildsystem

**Comment by YYMMYB** [comment] 2021-11-13 05:19
I meet this bug in Godot 3.4 with godot voxel module.
```
[ 60%] Compiling ==> scene\3d\portal.cpp
[ 60%] Linking Static Library ==> modules\libmodules.android.opt.armv7.neon.a
scons: *** [modules\libmodules.android.opt.armv7.neon.a] 文件名或扩展名太长。
scons: building terminated because of errors.
[Time elapsed: 00:03:20.369]
```

**Comment by YYMMYB** [comment] 2021-11-13 05:30
> Moving C:\Program Files (x86)\Android\android-sdk directory to C:\Android\android-sdk (and fixing PATH's after the operation) helped me solve this problem.

This method helped me solve this problem too.
