### ISSUE TITLE
Empty Export Array Calls Functions on all Arrays

### ISSUE THREAD

**Issue by Wyxaldir** [godotengine/godot#31242] opened 2019-08-09 16:04 UTC
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
Using array.append("String") on an empty exported array will append "String" to all other exported arrays. 

If there is any value in the exported array (via the inspector) then it works as intended.
Adding a value via code does not solve the issue.

**Steps to reproduce:**
Simply create 3 export arrays and leave them empty. Call append on any array, and see them all receive the value. 

**Minimal reproduction project:**
[Empty Export Array Calls Functions on all Arrays.zip](https://github.com/godotengine/godot/files/3487116/Empty.Export.Array.Calls.Functions.on.all.Arrays.zip)

**Comment by Wyxaldir** [comment] 2019-08-09 16:10
If you add values in the inspector, and then remove them in code, then it works as intended.

**Comment by KoBeWi** [comment] 2019-08-09 16:15
I've seen a similar issue somewhere and even thought it was resolved, but I tested in master and it still happens.

**Comment by Zylann** [comment] 2019-08-09 16:24
Does it happen too if you add values, but the *same ones* to all instances?

**Comment by Wyxaldir** [comment] 2019-08-09 16:26
If you add null to all of them in the inspector then it works fine

**Comment by creikey** [comment] 2019-08-10 11:48
Initializing the arrays as
```python
export(Array) var a
export(Array) var b
```
does not reproduce the issue on linux

**Comment by TheDuriel** [comment] 2019-08-10 11:48
```
#extends Node2D
#
#export(Array) var ar_1
#export(Array) var ar_2
#export(Array) var ar_3
#
#
#func _ready():
#	ar_1.append(4)
#
#	print(ar_1)
#	print(ar_2)
#	print(ar_3)

extends Node2D

export(Array) var a
export(Array) var b

func _ready():
    a.append("test")
    print("Array A: ", a)
    print("Array B: ", b)

#export var a = []
#export var a: Array
#export var a: Array = []
#export(Array) var a
#export(Array) var a: Array = []
```

any of these will do it on Windows 7
note that modifying the array in the inspector will prevent this.

**Comment by akien-mga** [comment] 2019-08-12 06:25
Related to #24134, likely duplicate of #28978.

**Closed by akien-mga** 2019-08-12 06:25 UTC
Labels: bug, topic:gdscript

**Comment by bncastle** [comment] 2023-04-08 16:23
This behavior still occurs in Godot 3.5.2 stable, and the zipped project that @Wyxaldir  originally attached still demonstrates this. It appears that all exported Array vars that are set to an empty array are for some reason pointing to the same array because modifying any of them modifies them all.
<img width="428" alt="Godot-Exported arrays bug" src="https://user-images.githubusercontent.com/1876691/230732061-70395034-190e-4cbf-9b86-b3fbecdf2eb0.png">

**Comment by bncastle** [comment] 2023-04-08 16:48
This bug still occurs when using Godot 3.5.2 stable and is reproducible using the zipped project @Wyxaldir provided. It appears that exported Arrays in a script which are initialized to '[]' all point to the same memory location as appending to any one of them appends the same value to them all.

**Comment by Zireael07** [comment] 2023-04-08 17:13
@bncastle Further confirmation that this is a dupe of #24134
