### ISSUE TITLE
Can only set cursors to 32 x 32 textures.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#19907] opened 2018-07-02 06:05 UTC
Regarding **Input.set_custom_mouse_cursor()**, I'm experiencing this in the 3.0.4 build.

@guilhermefelipecgs Has a regression occurred from this time: https://github.com/godotengine/godot/issues/17992 ?

Example project: [32x32 limit.zip](https://github.com/godotengine/godot/files/2153912/32x32.limit.zip)

**Comment by akien-mga** [comment] 2018-07-02 06:43
Duplicate of #17992, the fix #18002 was merged in the master branch, not cherry-picked yet into the 3.0 branch.

**Closed by akien-mga** 2018-07-02 06:43 UTC
