### ISSUE TITLE
When using a controller analog stick to scroll through UI elements, focus moves more than once per input action

### ISSUE THREAD

**Issue by Nubilous** [godotengine/godot#55434] opened 2021-11-29 11:09 UTC
### Godot version

3.4.1.rc1

### System information

Windows 10

### Issue description

If you have more than two buttons in a row and a controller stick up/down/left/right is set for ui_up/down/left/right, when pressing the analog stick in the intended focus change direction, the focus will very rapidly scroll down the list of buttons, instead of only ticking down once (which was the behavior in 3.3). This breaks using focus for complex controller UIs in 3.4.

Tested using an Xbox 360 wired controller and a wireless Switch Pro controller. As mentioned, the sample project works as expected in 3.3, but behaves in the described broken fashion in 3.4.rc1.

### Steps to reproduce

1. Create a list of more than two buttons (in a VBoxContainer, for example)
2. Make sure the analog left stick up/down/left/right is set for ui_up/down/left/right in the Input Map
3. Give the first button focus
4. Start the project
5. Move the analog stick down
6. Focus will briefly blink for the buttons inbetween, and then immediately move on to the next, only stopping at the bottom-most button.

### Minimal reproduction project

[godot-controller-test.zip](https://github.com/godotengine/godot/files/7617637/godot-controller-test.zip)

**Comment by Calinou** [comment] 2021-11-29 12:14
Duplicate of https://github.com/godotengine/godot/issues/54959.

**Closed by Calinou** 2021-11-29 12:14 UTC
