### ISSUE TITLE
Navigation recomputes incorrect longer path to unreachable target

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#78943] opened 2023-07-02 10:35 UTC
### Godot version

v4.1.rc2.official.46424488e

### System information

Ubuntu 23.04, Vulkan, NVIDIA GeForce RTX™ 2060 / NVIDIA GeForce RTX™ 2060, NVIDIA Driver Version: 525.105.17, NVML Version: 12.525.105.17

### Issue description

Navigation server should compute (and recompute) the shortest path to the target. In this example I have two unlinked nav meshes  and we want to showcase the edge connection feature in v4.1 with this moving platform. When the connection gets broken and the agent needs to recompute the path it goes to the side instead of remaining stationary.

Expected result is like in the first part of the demo where the agent moves to the edge of the nav mesh then waits for the platform.

https://github.com/godotengine/godot/assets/1177508/7d1b307b-d7c9-4042-b3c2-ab1ae695ebab

### Steps to reproduce

Run the demo and notice that when the agent has to recompute the path because the link is broken due to the moving platform it computes a path to the side which is not what's expected. The expected behavior is to find the point closest to the target position (on the other island) which in this case should be the middle of the platform where the moving platform connects.

This looks like a bug to me.

### Minimal reproduction project

[godot-4-dbg.zip](https://github.com/godotengine/godot/files/11929237/godot-4-dbg.zip)

**Comment by smix8** [comment] 2023-07-03 21:56
What happens here is that, due to the lack of virtual connections (navigation links) and the constant severed navigation mesh edge connections the agent is searching new paths every single frame. The pathfinding only really has two navigation polygons available for the path search but it does not know that in advance. The one starting polygon that the agent is already standing on and the neighbor polygon that is "behind" it (not really).

The path search starts at the position of the agent and goes to the closest edge position of the neighbor polygon building this as the first "searched" path segment. The path search now realizes that it is stuck as there is no virtual connection that allows the pathfinding to know it could go to the "waiting" position to reach the other side. It has run out of new polygons to search.

The fallback in those situations is to return a path to the closest position possible by distance **_but only inside the fully searched path polygon corridor_**. The first, starting polygon is not a fully search polygon, it only has the segment from start position to edge positions. Therefor the start position is further away than the corner of the second polygon. As a result the pathfinding thinks the corner position is closer and snaps to it.

Also regarding the other linked issue in the documentation, when I say navigation links do not work without a script handling it I mean it. This and others are the exact reasons for it. Without a navigation link you get sometimes those path corridors depending on polygon layout that are not really usable or weird agent behavior from all the navigation map resets. With a navigation link alone without script the agent will just travel through thin air to the other side because it does not understand there is a platform.

**Comment by smix8** [comment] 2023-07-03 23:49
If you can please test the linked pr to see if it fixes that issue.

**Comment by razcore-rad** [comment] 2023-07-07 06:34
I had time to check the PR (mono artifact) with the platforms demo project and it seems that the issue is fixed. Thanks for the detailed explanation here & on Rocket.Chat as well, I understand the system somewhat now.

So like I mentioned, the moving platform demo is fixed by this PR, but I think the system still has some bugs in the way it handles going to the closest point to the target position that is outside the navigation map.

I merged together the moving platform demo with the islands demo from the docs repo (https://github.com/godotengine/godot-docs/issues/7598) and updated it a bit. Please check `res://islands/islands.tscn` and see that when the navigation links are **disabled** and the agent is inside the navigation region to the left, giving it an unreachable target to the right of the screen doesn't compute a closest-to-unreachable-target path. I'm using the white rectangle as an indicator for the given target position.

![image](https://github.com/godotengine/godot/assets/1177508/1d2ea84f-5bc0-4c05-af87-a0ffd928ce01)

![image](https://github.com/godotengine/godot/assets/1177508/0f2e3539-0dd5-4d47-952c-752c7cd9e718)

![image](https://github.com/godotengine/godot/assets/1177508/abceb85a-e01a-44f1-9cdb-721b8185d26f)

As you can see in the images above, most of the target positions to the right of `NavigationRegion2D1` do not produce any paths.

Giving it a target position other than the right side does produce correct paths:

![image](https://github.com/godotengine/godot/assets/1177508/7ccccc66-d988-49ee-b38f-0a0f29a55a4e)

I'm not sure if this is the same issue so let me know if I should open a separate issue for this case.

Here's the project tried with your PR (Godot Engine v4.1.rc.mono.custom_build.c105e1c2f):

[godot-4-dbg.zip](https://github.com/godotengine/godot/files/11975364/godot-4-dbg.zip)

**Comment by smix8** [comment] 2023-07-08 19:56
Well in that case the issue is that the left polygon is a singe convex polygon disconnected from everything.

Since the pathfinding loops through the established edge connections it faces a situation with an empty loop because the polygon has no connections at all. The fallback for this situation is returning an empty path.

You can try this by changing the left polygon to a concave layout so that it is forced to rebuild with 2+ convex polygons like the right polygon is. This alone is enough to not show the issue because it now has at least a single self-connection between the two polygon edges so the full loop can run.

**Comment by smix8** [comment] 2023-07-08 21:23
I updated the pr with another fix for this new issue. If you find time please test again.

**Comment by razcore-rad** [comment] 2023-07-09 04:21
I tested a few scenarios that I could think of with Godot Engine v4.2.dev.mono.custom_build.28e251c5c and it seems like everything works as expected. For now I don't have anything else to report, thanks @smix8!

**Closed** 2023-07-09 22:08 UTC
Labels: bug, topic:navigation
