### ISSUE TITLE
Selection rectangle in the about menu is not clipped 

### ISSUE THREAD

**Issue by groud** [godotengine/godot#12348] opened 2017-10-23 10:15 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Current master

**Issue description:**
In the "About" menu of the editor, the selection rectangle of a focussed item is not clipped when scrolling. Picture (see the selection rectangle being draw over the tabs):
![2017-10-23-121124_802x309_scrot](https://user-images.githubusercontent.com/6093119/31883883-b0364948-b7eb-11e7-985a-d09f907a4dd3.png)

**Comment by groud** [comment] 2017-10-23 11:09
Ping @Noshyaar :)

**Comment by Noshyaar** [comment] 2017-10-23 13:22
Duplicate of #9612, there is a bit more investigation in the original thread. (I have no idea how to fix it properly.)

I think this needs to be fixed because it's very apparent. There were at least 4 reports already. 😛

**Closed by Noshyaar** 2017-10-23 13:22 UTC
Labels: bug, hacktoberfest, topic:editor

**Comment by groud** [comment] 2017-10-23 13:25
Oh sorry, I couldn't find it this with "selection" or "focus" in the issues.
