### ISSUE TITLE
Keys not working if Ctrl+Alt is needed

### ISSUE THREAD

**Issue by MuffinLover42** [godotengine/godot#38919] opened 2020-05-21 11:53 UTC
**Godot version**
v3.2.1.stable.mono.official

**OS and device**
Windows 10 on MSI gf62 8rd

**Issue description:**
The keys that need to be typed by using Ctrl + Alt do not get recognized by Godot. They get picked up by other programs though. I believe it is caused because those keys need Ctrl & Alt to be pressed to register, as I have tested with the On-screen-keyboard and I still have that problem. In my case it is a big problem because in my country's keyboard layout the curly and square brackets among other keys need that combination.

**Steps to reproduce:**
Can be reproduced by creating a script and trying to write a character that needs the said combination

**Minimal reproduction project:**
None. The issue can be recreated in any project.

**Comment by Ev1lbl0w** [comment] 2020-05-21 18:54
What is your keyboard layout? I can test this and see if I can find the problem

**Comment by vnen** [comment] 2020-05-22 00:54
Duplicate of #6851

**Closed by vnen** 2020-05-22 00:54 UTC
