### ISSUE TITLE
[Godot 4rc3] Window "Attach Node Script" vertical size overflow screen

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#73758] opened 2023-02-22 13:01 UTC
### Godot version

v4.0.rc3.official [7e79aead9]

### System information

Windows 7-64 :) 

### Issue description

I run a hello world example with Godot 4 rc3 and the window opened to attach script to node showed with a vertical size overflow the screen
I'm not sure 100% (I have different OS scattered in my room)  But If I recall correct it happen in Debian 11 too with 4rc2

### Steps to reproduce

Well, I "installed" godot in a new computer and I run it in compatibility mode then I set a control node with a label where on it I set "hello world", then I clicked in the icon to add a script in the control node.
The window "Attach Node Script" opened but its vertical size overflow the screen. I can estimate of double vertical monitor size

### Minimal reproduction project

na

**Comment by akien-mga** [comment] 2023-02-22 13:07
I think I saw this once too on Linux, but then couldn't reproduce it.

**Comment by akien-mga** [comment] 2023-02-24 12:18
Was this with RC 3, or RC 4? I suspect this might have been a regression from recent Label shaping changes which were reverted in RC 4.

**Comment by akien-mga** [comment] 2023-02-24 12:38
Great, very likely fixed by #73809 then.

**Closed by akien-mga** 2023-02-24 12:38 UTC
Labels: bug, topic:editor, usability
