### ISSUE TITLE
Collision geometry: generated static bodies can't be updated

### ISSUE THREAD

**Issue by nodefish** [godotengine/godot#17327] opened 2018-03-07 07:46 UTC
**Godot version:**
3.0.2 stable

**OS/device including version:**
Win10 64-bit latest

**Issue description:**

Generated static collision bodies are cached by mesh file name and cannot be updated.

**Steps to reproduce:**

1. Import mesh (.obj) named e.g. `model.obj`
2. Use `Create [Tri-Mesh/Convex] Static Body`
3. Update `model.obj` in modeling program and export it
4. Try to re-generate static body

Outcome: the static collision body for `model.obj` cannot be updated.

Workaround 1: export the updated model with a new name (e.g. `model-.obj`), reimport into Godot, generate mesh again

Workaround 2: delete all `.import` files for the mesh and inside the `.import` folder, close Godot editor and reopen it, recreate `MeshInstance` and set it to the mesh, re-generate static collision body

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment] 2020-02-13 08:42
@nodefish Can you reproduce this in Godot 3.2?

**Comment by tom-jk** [comment] 2020-07-12 21:05
Can't reproduce in 3.2.2.stable on linux mint 18.3 (assuming `Mesh -> Create Trimesh Static Body` is the equivalent of `Create [Tri-Mesh/Convex] Static Body`).

A minimal project for convenience (just a scene with a suzanne exported from Blender v2.81.16): 
[17327.zip](https://github.com/godotengine/godot/files/4909511/17327.zip)

**Comment by Calinou** [comment] 2020-07-13 08:50
@tom-jk Thanks for testing this! Closing as resolved.

**Closed by Calinou** 2020-07-13 08:50 UTC
Labels: enhancement, topic:core
