### ISSUE TITLE
Godot return error #1 when exporting apk file

### ISSUE THREAD

**Issue by LehaGameDev** [godotengine/godot#67482] opened 2022-10-16 10:35 UTC
### Godot version

3.5.1

### System information

Windows 10, GLES 3, NVIDIA Geforce GTX 550 Ti

### Issue description

When exporting an APK using the SDK Build-tools 30 and older versions, "apksigner" returns an error #1, if the SDK Build-tools lower than version 30, then godot does not return any errors, but the application on android is still not installed

### Steps to reproduce

Follow the steps from the Godot guide

**Comment by Calinou** [comment] 2022-10-16 17:24
Did you install Godot through Steam? See https://github.com/godotengine/godot/issues/62768.

**Comment by m4gr3d** [comment] 2023-05-30 00:31
Duplicate of https://github.com/godotengine/godot/issues/58192, should be resolved by https://github.com/godotengine/godot/pull/67668

**Closed by m4gr3d** 2023-05-30 00:31 UTC
Labels: enhancement, platform:android, topic:editor, needs testing
