### ISSUE TITLE
Error Release/Debug: 'class SceneTree' has no member named 'get_edited_scene_root'

### ISSUE THREAD

**Issue by purpleorangegames** [godotengine/godot#3386] opened 2016-01-19 12:16 UTC
I got error on all my release and debug builds, only tool built correctly.

```
[21:21:48][Step 5/28] g++ -o scene/main/viewport.x11.debug.64.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DOC_X86_ASM -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DOPENGL_ENABLED -DGLEW_ENABLED -DALSA_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=0 -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -Iscene/main/vorbis scene/main/viewport.cpp
[21:21:49][Step 5/28] scene/main/viewport.cpp: In member function 'void Viewport::_vp_input(const InputEvent&)':
[21:21:49][Step 5/28] scene/main/viewport.cpp:1282:50: error: 'class SceneTree' has no member named 'get_edited_scene_root'
[21:21:49][Step 5/28]   if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
[21:21:49][Step 5/28]                                                   ^
[21:21:49][Step 5/28] scene/main/viewport.cpp: In member function 'void Viewport::_vp_unhandled_input(const InputEvent&)':
[21:21:49][Step 5/28] scene/main/viewport.cpp:1307:50: error: 'class SceneTree' has no member named 'get_edited_scene_root'
[21:21:49][Step 5/28]   if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
```

**Comment by akien-mga** [comment] 2016-01-19 12:24
Duplicate of #3384, it's fixed in 1584aea already.

**Closed by akien-mga** 2016-01-19 12:24 UTC
Labels: archived

**Comment by reduz** [comment] 2016-01-19 12:46
i think this was fixed a bit ago in HEAD

On Tue, Jan 19, 2016 at 9:16 AM, PurpleOrangeGames <notifications@github.com

**Comment by purpleorangegames** [comment] 2016-01-19 12:48
Thanks guys, I set the server to build everything again from git.

**Comment by purpleorangegames** [comment] 2016-01-19 23:31
Built successfully.
