### ISSUE TITLE
[Godot4 a2] App crashed when some await situation

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#58382] opened 2022-02-21 08:23 UTC
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

I want a `delay_func` as a function's parameter, but it crashed when running.
![1](https://user-images.githubusercontent.com/35988767/154915358-e91f20ce-79cc-4efe-8890-447fedc05326.PNG)
![2](https://user-images.githubusercontent.com/35988767/154915387-edd10c30-9bea-4aad-bbec-c075eda334e3.PNG)
![3](https://user-images.githubusercontent.com/35988767/154915396-cf707581-8988-4e6b-af22-23dfabc3d6f0.PNG)

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[AwaitTest.zip](https://github.com/godotengine/godot/files/8107496/AwaitTest.zip)

**Comment by CsloudX** [comment] 2022-02-23 01:51
That's weird, today I run the reproduction project in Godot4 alpha3, it's ok, and I try it alpha2, it's ok too!!!

**Comment by akien-mga** [comment] 2022-02-23 06:26
Duplicate of #57126

**Closed by akien-mga** 2022-02-23 06:26 UTC
Labels: bug, topic:gdscript, needs testing, crash
