### ISSUE TITLE
CanvasItemMaterial: Light Mode set to "Light Only" Is Not Visible Under PointLight2D

### ISSUE THREAD

**Issue by Nastalgua** [godotengine/godot#73613] opened 2023-02-20 04:40 UTC
### Godot version

4.0.rc2.official

### System information

macOS Monterey, Apple M1 Pro, Mobile Renderer

### Issue description

When light is placed over a Node2D that has its Light Mode setting in CanvasItemMaterial changed to "Light Only", the node is not visible. Tried on Godot 3.5.1; works fine using that version.

### Steps to reproduce

1. Create an empty 2D scene.
2. Create a Sprite2D (or some other Node2D).
3. Add a CanvasItemMaterial and change the Light Mode to "Light Only".
4. Create a PointLight2D and place it over the Sprite2D.

### Minimal reproduction project

[Light Mode.zip](https://github.com/godotengine/godot/files/10779632/Light.Mode.zip)

**Comment by Wllwl2** [comment] 2023-03-03 18:58
Almost all ways to make invisible nodes in the shadow (including this one) do not work or are not very obvious.

**Comment by clayjohn** [comment] 2023-03-03 19:04
Duplicate of https://github.com/godotengine/godot/issues/44559. Sorry I missed this when tagging it originally.

**Closed by clayjohn** 2023-03-03 19:04 UTC
Labels: bug, topic:rendering, topic:2d
