### ISSUE TITLE
[CSharp] Custom Resources do not load as their correct types when loading from EditorPlugin.

### ISSUE THREAD

**Issue by MarioBossReal** [godotengine/godot#85834] opened 2023-12-06 11:55 UTC
### Tested versions

Reproducable in 4.2.stable.mono, and in Godot 4.1 aswell.

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

Attempting to load a custom C# resource from within an EditorPlugin (and possibly from anywhere that isnt runtime) yields an object that does not match the type of the custom resource. It is impossible to type-cast the loaded resource to its correct type.

### Steps to reproduce

How to use the minimal reproduction project:

Requirements: Godot v4.2.stable.mono, Godot-compatible .NET SDK.

-Load the project in Godot v4.2.stable.mono
-Be sure to build the project at least once
-Disable and enable the included EditorPlugin - observe how the resource fails to load properly from the console output.
-Run the scene "runtime_resource_load_test.tscn" - observe how the resource loads properly from the console output.

### Minimal reproduction project (MRP)

https://github.com/MarioBossReal/ResourceLoadFailureMRP

**Comment by raulsntos** [comment] 2023-12-07 01:51
Scripts not marked as `[Tool]` can't be instantiated in the editor, instead we create a placeholder to hold the necessary data (that's how you can edit it in the inspector). So you need to add the `[Tool]` attribute to the C# classes that you want to use in the editor (this includes resources that you want to access from plugins because plugins run in the editor).

Make sure to read the [_Running code in the editor_](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#doc-running-code-in-the-editor) documentation page for more information.

- Closing as duplicate of https://github.com/godotengine/godot/issues/55596.

**Closed by raulsntos** 2023-12-07 01:51 UTC
