### ISSUE TITLE
When MeshInstance in editor 3D view editor grid is invisible

### ISSUE THREAD

**Issue by ayndqy** [godotengine/godot#39811] opened 2020-06-24 20:36 UTC
**Godot version:**
3.2.1 x64

**OS/device including version:**
Windows 10 1909
Intel Core i3-7020U + HD 620
GLES3

**Issue description:**
When MeshInstance in editor 3D view editor grid is invisible
Only in GLES3
![image](https://user-images.githubusercontent.com/59361040/85624388-81e4bd80-b672-11ea-9517-3e34364e05aa.png)
![image](https://user-images.githubusercontent.com/59361040/85624407-8a3cf880-b672-11ea-9903-a4697b842444.png)

**Steps to reproduce:**
1. Add 'MeshInstance' on 3D scene
2. Change 'Mesh' property
3. Point editor camera at him

**Minimal reproduction project:**
[RPGTest.zip](https://github.com/godotengine/godot/files/4827765/RPGTest.zip)

**Comment by Calinou** [comment] 2020-06-25 07:39
Duplicate of #30330.

**Closed by Calinou** 2020-06-25 07:39 UTC
