### ISSUE TITLE
HTML5 export weird duplication of the texture.

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#28121] opened 2019-04-17 10:47 UTC
I didn't find similar issues

**Godot version:**
3.1

**OS/device including version:**
Ubuntu 18.04. GT 1030

**Issue description:**
When I export my scene with HTML5 export the texture looks duplicated in weird way. (The scene has only one texture) 

**Steps to reproduce:**
Export the scene with HTML5 export and open in browser. 

**Minimal reproduction project:**
https://www.dropbox.com/s/cnvi28wrg9tygcv/3D%20intro.zip?dl=0

**Comment by bojidar-bg** [comment] 2019-04-17 11:11
A screenshot might help with determining the cause of the issue.
Here is how a 3.1-stable export looks in Firefox:
![Screenshot_20190417_140424](https://user-images.githubusercontent.com/5276727/56283276-e70d5c80-6119-11e9-8e9e-f1a9526a3625.png)
And here is the same version running natively on linux:
![Screenshot_20190417_140637](https://user-images.githubusercontent.com/5276727/56283324-115f1a00-611a-11e9-9d82-28795b051b8c.png)

**Comment by bojidar-bg** [comment] 2019-04-17 11:16
Note that the texture is specified as to be stored in Video Ram, potentially WebGL has limitations on the size of textures which can be uploaded to it. Maybe try importing it in some other mode, or decreasing the size of the texture.

**Comment by gravit22** [comment] 2019-04-17 11:20
Thank you. Decreasing size of the texture helped but other mods didn't help.

**Comment by KoBeWi** [comment] 2020-08-20 23:11
Can anyone still reproduce this bug in [Godot 3.2.3 rc3](https://godotengine.org/article/release-candidate-3-2-3-rc-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment] 2020-12-10 16:09
No answer, so closing. Please comment if you can still reproduce it, and make sure that an up-to-date reproduction project is included.

**Closed by akien-mga** 2020-12-10 16:09 UTC
Labels: bug, platform:html5, topic:rendering
