### ISSUE TITLE
New default project path for new projects

### ISSUE THREAD

**Issue by LittleWhite-tb** [godotengine/godot#21307] opened 2018-08-23 05:51 UTC
Hello,

On Linux, when creating a new project, the default project path is the home folder of the user.
I think it would be more adequate to specify a default project path to a specific Godot folder (eg. $HOME/GodotProjects on Linux). 

(Of course, this is also applicable on other OSes)

**Comment by akien-mga** [comment] 2018-08-23 07:47
There's already an editor option to set your preferred default path. I don't think enforcing one is a good idea, we all have different preferences and personally I'm annoyed by software that creates folders in my $HOME without asking (looking at you `~/VirtualBox VMs`).

This proposal partly overlaps with #6020, so I'll close it as duplicate of that one, and we can continue the discussion there.

**Closed by akien-mga** 2018-08-23 07:47 UTC
