### ISSUE TITLE
textures go black GLES3 when zoom in or out and during debug game (3D)

### ISSUE THREAD

**Issue by Pradnyakhadayate** [godotengine/godot#65240] opened 2022-09-02 10:44 UTC
### Godot version

v3.4.5.stable.official [f9ac000d5]

### System information

Windows 11, GLES3, Intel UHD Graphics 605 (26.20.100.7986)

### Issue description

Hi, I am using a laptop with the latest intel uhd drivers. When i zoom in our out all the textures that i have applied to the mesh (CSGBox and CSGPolygon) suddenly turn black until i turn back to the previous zoom. When i go to debug in my game, the textures constantly turn black and back to their original textures every frame and whenever i turn around. I have attached screenshots of the debug game when i turn. Is there any way that i can avoid this? I have also issued this problem into godot's qa:
[https://godotengine.org/qa/138235/textures-in-3d-go-black-during-zoom-in-or-out]
![Screenshot (1156)](https://user-images.githubusercontent.com/82781770/188122253-4ef307b5-8b65-4a0e-bcb7-743b260636dd.png)
![Screenshot (1157)](https://user-images.githubusercontent.com/82781770/188122261-83441def-8643-4182-b506-a5be1758481e.png)
![Screenshot (1158)](https://user-images.githubusercontent.com/82781770/188122263-5ddaa641-c335-4c71-8c9a-3cfa2b2a1a67.png)
![Screenshot (1159)](https://user-images.githubusercontent.com/82781770/188122267-e8c60b52-27fb-435c-a578-4d6872b6438d.png)

### Steps to reproduce

This is the only code in my script that i have written (no other code):
`extends KinematicBody

func _unhandled_input(event):
	if event is InputEventMouseMotion:
		_handle_camera_rotation(event)

func _handle_camera_rotation(event):
	rotate_y(deg2rad(-event.relative.x))
	
`
	
I believe the problem is **mainly** in the **editor**, not in the actual code. 

### Minimal reproduction project

I apologize for not uploading any ZIP archive of my project as i am having exporting issues.

**Comment by Calinou** [comment] 2022-09-02 15:44
Duplicate of https://github.com/godotengine/godot/issues/25512.

**Closed by Calinou** 2022-09-02 15:44 UTC
