### ISSUE TITLE
[v4.0beta17] [Win 11] Gray border setting WINDOW_MODE_FULLSCREEN via code

### ISSUE THREAD

**Issue by rafma0** [godotengine/godot#72734] opened 2023-02-04 21:19 UTC
### Godot version

v4.0.beta17

### System information

Windows 11

### Issue description

Setting the window mode to `WINDOW_MODE_FULLSCREEN` via code adds a gray border around the screen

https://user-images.githubusercontent.com/28578847/216789112-d2a129b6-7799-45dd-80fa-c36c0afae4cf.mp4

I think it won't be visible correctly in this video if watched from a browser (if it's not, please download and open it in VLC). There's a 1-pixel border around the screen that appears only if you set the window mode to `WINDOW_MODE_FULLSCREEN` via code. This issue doesn't occur if the project window mode is set to `Fullscreen` and you haven't set anything via code, or if you've set it to `WINDOW_MODE_EXCLUSIVE_FULLSCREEN`.

![image](https://user-images.githubusercontent.com/28578847/216789972-8fcac60c-801a-4268-8b20-ed9c2deff760.png)

### Steps to reproduce

```python
DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
```

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-02-04 23:31
Duplicate of #63500.

**Closed by kleonc** 2023-02-04 23:31 UTC
