### ISSUE TITLE
Add Modifier keys left/right support

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#3347] opened 2016-01-14 08:28 UTC
The thing is, in Godot the modifier keys **SHIFT, CTRL, ALT/OPTION and WINDOWS** keys for
both the left and right side are considered as the same key. Pressing left CTRL should be different
than pressing the right CTRL. Same for the other modifier keys. In Godot, left and right modifier keys share the same scancode.

From my experience with DirectInput in DirectX, it can be done. although Godot does not use DI.

Also, provide an option to disable propagating the **WINDOWS** key event to the OS, when Godot window is focused. Again, it can be done in DirectInput but don't know how Godot deals with Input. Currently, when I set up an action to use the windows key in game, when pressing it the start menu pops up.

**Comment by bojidar-bg** [comment] 2016-01-15 12:34
I think that we should have three options for each button: `left`, `right` and `both`. This means that for <kbd>SHIFT</kbd>, it becomes `LEFT_SHIFT`, `RIGHT_SHIFT` and `SHIFT` (this is to maintain compatibility and ease of use).

@RebelliousX ~ not propagating <kbd>WINDOWS/META</kbd> or any other modifier key (esp. <kbd>ALT</kbd>) to the OS, *would* mean **different** behaviour on different OS-es and/or display managers, as this is quite unlikely to be doable on X11 linux, and probably impossible by design on Wayland.

**Comment by vnen** [comment] 2016-01-15 14:49
I wouldn't expect to use the Windows key in a game. And in Windows 10 <kbd>Win</kbd>+<kbd>G</kbd> brings up the game bar, so this shortcut should pass through to the OS. So I don't think that stopping propagation is a good idea.

I also agree with @bojidar-bg about the three options for modifiers.

**Comment by akien-mga** [comment] 2016-01-15 15:23
> I wouldn't expect to use the Windows key in a game. And in Windows 10 Win+G brings up the game bar, so this shortcut should pass through to the OS. So I don't think that stopping propagation is a good idea.

+1, if using some of these keys in a game, be especially careful to cross-platform and cross-hardware compatibility. Many laptops have only one "windows" key for example, like on mine there is only a windows key on the right, and it's seen by xinput as "Left Windows" :)

> I also agree with @bojidar-bg about the three options for modifiers.

The proposal is sensible yeah.

**Comment by RebelliousX** [comment] 2016-01-15 17:28
Well, I agree about the Win key and I get the point about game bar for recording gameplay. Also, the proposal of @bojidar-bg is good one to avoid breakage of old code.

**Comment by neikeq** [comment] 2016-05-26 13:01
What's the progress on this issue? Did anyone have luck implementing @bojidar-bg's proposal?

**Comment by bojidar-bg** [comment] 2016-05-26 13:41
I haven't done anything on it, would be nice if somebody with multiple available platforms will try (since it might have to touch OS classes)

**Comment by Anutrix** [comment] 2019-06-23 13:48
Anyone working on this?

**Comment by andrewmwalker98** [comment] 2019-11-19 03:23
Bump I too would like this feature

**Comment by Calinou** [comment] 2019-11-19 09:54
@andrewmwalker98 Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by xdevionx** [comment] 2022-09-20 13:54
GODOT has blocked all my keys I can not even make a screenshot. Also AHK is completely blocked. I can not semi-automate the engine with AHK to work faster. Does anyone know how to fix this in GODOT so I can use AHK and EXCEL lists for automation and control MAUS again with AHK.

**Comment by Calinou** [comment] 2023-06-30 23:28
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1387, as feature proposals are now tracked on the Godot proposals repository.

**Closed by Calinou** 2023-06-30 23:28 UTC
Labels: enhancement, topic:input
