### ISSUE TITLE
4.0.rc5: Editor crashes when loading .ogv in VideoStreamPlayer

### ISSUE THREAD

**Issue by dimroc** [godotengine/godot#73992] opened 2023-02-26 17:53 UTC
### Godot version

4.0.rc5

### System information

MacOS 13.1, Macbook Pro 2018, Intel UHD Graphics 630, Radeon Pro 560X

### Issue description

Adding `.ogv` video to VideoStreamPlayer crashes on save and restart after selecting .etc2 texture compression in Project Settings. This may be because I'm on an intel mac.

It also crashes on VideoStreamPlayer node creation when loading `.ogv` video if .etc2 is already selected.

### Steps to reproduce

1. Create project with mobile renderer
2. Add VideoStreamPlayer node
3. Load .ogv video
4. Enter project settings and set .etc2.
5. Save and restart
6. Editor never restarts. Subsequent loads crash.

### Minimal reproduction project

[VideoTest4.zip](https://github.com/godotengine/godot/files/10834325/VideoTest4.zip)

**Comment by akien-mga** [comment] 2023-02-26 18:04
Duplicate of #72976

**Closed by akien-mga** 2023-02-26 18:04 UTC
Labels: archived

**Comment by FlankeR-46** [comment] 2023-02-27 04:52
This problem only occurs with video files that DO NOT have an audiotrack. There are no problems with regular OGV files. In version 3.5, there was no such problem either.

**Comment by akien-mga** [comment] 2023-02-27 06:09
It's already fixed, see the duplicate issue.

**Comment by FlankeR-46** [comment] 2023-02-27 07:16
I'm new to Github. I was looking at a duplicate issue, saw a fix. I have not found anywhere that it is about the absence of a audiotrack. Or I was looking in the wrong place :) Thank you, sorry for the trouble :)

**Comment by akien-mga** [comment] 2023-02-27 07:20
No trouble made :) And thanks for the extra input, this seems consistent with what the fix handles #73958 (it makes sure to only process video - theora - when there is some, and audio - vorbis - when there is some).
