### ISSUE TITLE
ItemList emits the item_selected signal even for non-selectable items

### ISSUE THREAD

**Issue by qrrk** [godotengine/godot#52288] opened 2021-08-31 17:49 UTC
### Godot version

3.3.3 stable

### System information

Linux

### Issue description

For non-selectable items inside an ItemList, there is no visual reaction to mouse clicks or arrow keys (and this is correct), but the item_selected signal is still emitted.

### Steps to reproduce

1. Create a UI scene with an ItemList and some items in it.
2. Ensure that all items in the list are made non-selectable using the set_item_selectable method.
3. Create a handler for the item_selected signal of the ItemList.
4. Try clicking on some items in the item list and observe the handler get called.

### Minimal reproduction project

[ItemList_selectable_bug.zip](https://github.com/godotengine/godot/files/7085836/ItemList_selectable_bug.zip)

**Comment by Calinou** [comment] 2021-08-31 17:58
Duplicate of https://github.com/godotengine/godot/issues/37277.

**Closed by Calinou** 2021-08-31 17:58 UTC
