### ISSUE TITLE
Adding track for 'Frame' field on Sprite increments it, but does not move the animation position forward

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#49330] opened 2021-06-05 02:08 UTC
**Godot version:** 3.3.2.stable.mono

**OS/device including version:** Windows 10

**Issue description:** Typically if you add a key frame to the Frame field it will increment its value and move the animation position forward, meaning you can keep clicking to easily keyframe a bunch of animation frames from a spritesheet. But in this case when you add the track, it just gets incremented and does not move the animation position forward, meaning you have to manually reset the Frame field value before adding in the rest of the keyframes.
I would expect it to move the animation position forward when you create a new track for the Frame field, or just not increment the Frame value.

**Steps to reproduce:**  
Create a Sprite node and an AnimationPlayer Node 
Set the sprite to have 5 Hframes
Create an animation
Click the key next to the 'Frame' field on the Sprite to add a new track for it

https://user-images.githubusercontent.com/7292421/120876823-07f6cd00-c581-11eb-9d6e-c14cce041bdd.mov

**Minimal reproduction project:**

[AnimSpriteIssue.zip](https://github.com/godotengine/godot/files/6601892/AnimSpriteIssue.zip)
open Node2D scene, create an animation for the Animation Player, add a track to the Frame field on the sprite

**Comment by timothyqiu** [comment] 2021-06-05 10:01
I think this is a duplicate of #33681.

**Comment by KoBeWi** [comment] 2021-06-05 12:26
Yep, duplicate of #33681

**Closed by KoBeWi** 2021-06-05 12:26 UTC
