### ISSUE TITLE
Vulkan: GPUParticles2D Local Coords don't work correctly

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#50453] opened 2021-07-14 13:50 UTC
### Godot version

v4.0.dev.calinou [fabc3b93f]

### System information

Windows10

### Issue description

Particles2D local coords was wrong

### Steps to reproduce

1.Create a Particle2D
2.Set Gravity to Vector3(0,0,0)
3.Unchecked Local Coords
4.Edit code make particles moving
It's look like this:
![111](https://user-images.githubusercontent.com/35988767/125633298-f1dc8cc2-c70e-46a5-87dc-b97c3e8dbf66.gif)

In Godot3, It's looks like(My expected):
![222](https://user-images.githubusercontent.com/35988767/125634525-5e586d22-1625-4b58-a67a-b82edc6044ff.gif)

### Minimal reproduction project

[ParticlesTest.zip](https://github.com/godotengine/godot/files/6816547/ParticlesTest.zip)

**Comment by akien-mga** [comment] 2022-01-24 22:46
Seems reproducible in 4.0 alpha 1 and 30701e3966fe0869868d09d57249ff140e55849e.

The bug description wasn't obvious to me so clarifying for future readers: the problem in the first video is that already emitted particles still move following the emission point, while they should stay static once emitted.

**Comment by Calinou** [comment] 2022-01-24 22:49
Duplicate of https://github.com/godotengine/godot/issues/56892.

**Closed by Calinou** 2022-01-24 22:49 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:2d
