### ISSUE TITLE
In TileSet, next_alternative_id does not change when an alternative is deleted

### ISSUE THREAD

**Issue by Wanchai** [godotengine/godot#68403] opened 2022-11-08 08:11 UTC
### Godot version

v4.0.beta4.mono.official [e6751549c]

### System information

Windows 10, GLES3

### Issue description

On your tileset if you create an alternative, its ID will be 1. If you delete it and create another one, the ID will be 2.

Not that bad you might say. I agree, but when I try to set ID to 1 in the tileset editor, Godot crashes. And it creates bugs with the alternative when I re-launch.

I tried to reproduce it on a simpler project and even if the non-decrementing problem is there, Godot does not crash this time.

### Steps to reproduce

On a tileset:
- create a tile
- create 3 alternatives
- delete them
- create an alternative

The ID is 4 and not 1.

### Minimal reproduction project

In this tileset you will see that I created several alternatives, deleted them, created one, set the ID to one my self.

When I created other alt. their ID's were: 5,6,7

[godotbug.zip](https://github.com/godotengine/godot/files/9958983/godotbug.zip)

**Comment by groud** [comment] 2022-11-08 13:12
The ID being incremented to the "ever maximum" is expected behavior. I didn't wanted to mess tiles with random ones when creating new alternatives.
Changing the alternative ID should not crash though, so that's indeed a bug.

**Comment by groud** [comment] 2023-06-22 13:14
I cannot reproduce the crash anymore. Could you confirm it is fixed on the latest version ?

**Comment by YuriSizov** [comment] 2023-11-14 21:38
Assuming this is fixed for now, but please let me know if you can still reproduce the issue, so we can reopen it.

**Closed by YuriSizov** 2023-11-14 21:38 UTC
Labels: bug, topic:editor, needs testing, crash, topic:2d
