### ISSUE TITLE
AnimationPlayer has offsets on keys that makes the animation jitter if you put in the correct keys

### ISSUE THREAD

**Issue by Lortemanden** [godotengine/godot#94164] opened 2024-07-10 09:24 UTC
### Tested versions

- Reproduced in 4.3.beta2

### System information

Windows 10

### Issue description

When creating a animation for the AnimationPlayer you set in keys, but the editor places those keys with a 0.0333 time offset. This also happens when you drag the keys around. While this in itself is a small bug, if you remove the time offset to the correct value the animation start to jitter as shown in the video. 

https://github.com/godotengine/godot/assets/55434783/fa812002-1a4a-40e0-9bd5-cb1fc9225ed5

### Steps to reproduce

-To visualize it create a sprite
- Create a animation player
- Create a animation with the sprites rotation
- Make the sprite rotate left and right
- Make the last key end with the same value as the first
- Then remove the offset from the last key so it matches the length of the animation
- Set the animation to loop and it will start to jitter

### Minimal reproduction project (MRP)

[animationTest.zip](https://github.com/user-attachments/files/16158695/animationTest.zip)

**Comment by ydeltastar** [comment] 2024-07-11 11:11
I can't reproduce it in 4.3.beta3.
It was probably fixed by https://github.com/godotengine/godot/pull/92670.

**Comment by Lortemanden** [comment] 2024-07-12 08:05
I can still produce it in 4.3.beta3 but it seems to require using a cubic interpolation mode. Unsure if this is intended but still feels like a bug to  me.

**Comment by AThousandShips** [comment] 2024-07-12 09:11
> Probably fixed by #92670.

That was in beta2 so couldn't have fixed it

**Comment by ydeltastar** [comment] 2024-07-12 12:32
> I can still produce it in 4.3.beta3 but it seems to require using a cubic interpolation mode. Unsure if this is intended but still feels like a bug to me.

Does it add an offset when setting a keyframe in lastest version? I tried it in the mrp too but it seems to be working as expected.

If by jitter you mean the slight pause at the end/start of the animation, that's the effect of the cubic interpolation in loop mode. When you place keyframes at the start and end, it creates a non-continuous interpolation slope since two control points are overlapping in the same spot. You have to delete the last (or first) frame and leave it empty to make the slope continuous.

**Comment by TokageItLab** [comment] 2024-07-13 16:07
Dupe of https://github.com/godotengine/godot/issues/86003

**Closed by TokageItLab** 2024-07-13 16:07 UTC
Labels: bug, needs testing, topic:animation
