### ISSUE TITLE
Resize indicator mouse cursor stays after leaving Dialog

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8984] opened 2017-05-29 18:26 UTC
**Operating system or device - Godot version:**
X11, Godot master

**Issue description:**
When hovering over the border of a re-sizable `WindowDialog`, the mouse cursor doesn't change back after leaving the Dialog bounds (in the "outside" direction).

![cursor_bug](https://cloud.githubusercontent.com/assets/8281916/26559000/ff1ce0e2-44ac-11e7-8f5b-be80b15fd51e.gif)

**Comment by akien-mga** [comment] 2017-05-29 18:41
Duplicate of #7622 I think.

**Comment by bojidar-bg** [comment] 2017-05-29 18:41
Duplicate of #7622?

**Closed** 2017-05-29 18:41 UTC
Labels: bug, junior job, topic:core, usability
