### ISSUE TITLE
Confusing error message when naming a local variable the same as a property

### ISSUE THREAD

**Issue by marcinn1** [godotengine/godot#83798] opened 2023-10-22 21:54 UTC
### Godot version

v4.1.2.stable.arch_linux

### System information

Linux

### Issue description

When you declare local var with a same name as a property, you will get confusing error at runtime.

### Steps to reproduce

Declare var as a property, then declare local variable with same name, then access both in the same line:

```gdscript
var x = 0.0

func _process(delta):
    var x = x + delta
```

You will get an error at runtime: `Invalid operands 'float' and 'Nil' in operator '+'`.
1. The parser should raise an error.
2. Or GDScript should evaluate internal `x` as a property first (which is set to `0.0`), then assign `0.0+delta` to a local variable `x`.

### Minimal reproduction project

^^

**Comment by jmattspartacus** [comment] 2023-10-23 00:06
It seems like this should throw an error, unless shadowing is a desired behavior.

**Comment by dalexeev** [comment] 2023-10-23 05:28
* Duplicate of #54944.
* Fixed by #79880 for 4.2.

Thanks for reporting the bug nonetheless!

**Closed by dalexeev** 2023-10-23 05:28 UTC
Labels: bug, topic:gdscript
