### ISSUE TITLE
Right-clicking a button when another button is highlighted

### ISSUE THREAD

**Issue by NeoTheThird** [godotengine/godot#8193] opened 2017-03-29 08:33 UTC
**Operating system or device - Godot version:**  Ubuntu 16.04.2, Godot Engine v. 2.1.2.stable.official

**Issue description:**
If a button is highlighted and a different button is right-clicked, both buttons recieve the signal. This is not the case for left-clicks.

**Steps to reproduce:**
Open the Godot Engine, download, install and open YeOldeDM/Minesweeper from the asset lib, start the game, left-click a tile, move the blue frame to an unpressed tile and right-click a different unpressed tile. Both tiles receive the signal, as visible by the "F".

**Link to minimal example project:**
https://github.com/YeOldeDM/godot-minesweeper
https://godotengine.org/qa/13550/how-to-disable-button-highlighting

**Comment by kubecz3k** [comment] 2018-04-10 16:47
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by kubecz3k** [comment] 2018-04-10 16:48
I'm not sure, but looking at https://godotengine.org/qa/13550/how-to-disable-button-highlighting do I correctly assume there was not bug in the engine and the issue can be closed?

**Comment by akien-mga** [comment] 2019-04-15 14:23
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:23 UTC
Labels: bug, topic:core
