### ISSUE TITLE
After 3.2 update imported materials got roughness set to 0

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#35757] opened 2020-01-30 21:16 UTC
**Godot version:**
3.2 Steam
**OS/device including version:**
Linux
**Issue description:**
All my imported materials from blender got Roughness set to 0 so the sky color affects them, ruining the picture. Do I need manually go through every material and fix it by hand? I don't really want to go through over a hundred models/nodes fixing the materials...
![Screenshot_20200130_191918](https://user-images.githubusercontent.com/41639190/73490990-b2c00f80-43be-11ea-81c6-395540bd4418.png)

**Steps to reproduce:**
Have project where materials are imported from blender's Dae file.
Get 3.2 update.

**Minimal reproduction project:**

**Comment by fire** [comment] 2020-01-31 03:01
This might be an interaction with the defaults in Godot Engine not being written to the scene files.

Can you provide a test project?

**Comment by gdesecrate** [comment] 2020-01-31 06:41
Here you go. In 3.1 It would be just a black shape not affected by background color. But in 3.2 it got roughness set to 0 it seems at import.

[godottest.zip](https://github.com/godotengine/godot/files/4137901/godottest.zip)

**Comment by DeerTears** [comment] 2020-02-06 20:04
I've also had this problem actually. I'll have to create a minimum reproduction project for this but I've experienced this when importing a Blender 2.8-made .glb model with 15 materials. 3 of them got their roughness value successfully carried over from Blender to Godot (0.66, 0.75, 0.8) but the other 12 were meant to have a roughness of 1, and Godot imported them with a roughness of 0.5. Even in complete shadow I'd have my character's skin glowing with the colour of the sky, exactly like the arms/hands in gdesecrate's screenshot.

**Comment by gdesecrate** [comment] 2020-02-07 10:17
This bug inspired me to improve my content workflow

**Comment by Calinou** [comment] 2020-09-06 23:23
@gdesecrate Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by fire** [comment] 2020-10-27 03:32
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

Also. I tried godottest.zip in 3.2 and it didn't seem to trigger the bug. Roughness was 0.08 in Material.material.

**Closed** 2020-10-27 03:32 UTC
Labels: bug, topic:import
