### ISSUE TITLE
Godot 4 script conversion swaps all "on" to "checked" and "off" to "unchecked"

### ISSUE THREAD

**Issue by handre-dev** [godotengine/godot#71399] opened 2023-01-14 15:06 UTC
### Godot version

4.0.beta10

### System information

Windows 10

### Issue description

Rather funny and catastrophic bug. Couldn't find it in the open issues (strangely).

When performing a "Convert Full Project" from 3.5.1 to 4.0.beta10 (and probably previous versions too), "_on_" and "_off_" (no matter if they are part of strings, variable names, function names) are changed to "_checked_" and "_unchecked_".

Looks like occurrencies with underscore before the words are spared.

![image](https://user-images.githubusercontent.com/96829602/212478354-b3aa99c1-f0b2-42c2-9ea1-00ed1391c1cc.png)
![image](https://user-images.githubusercontent.com/96829602/212478373-7179a3f6-fa38-4237-880f-81d6600e3a8a.png)

Minimal project included.

### Steps to reproduce

Import the project in Godot 4 and full convert

### Minimal reproduction project

[conversion test checked.zip](https://github.com/godotengine/godot/files/10417980/conversion.test.checked.zip)

**Comment by Zireael07** [comment] 2023-01-14 18:21
duplicate of #70983

**Closed** 2023-01-14 23:29 UTC
