### ISSUE TITLE
ResourceLoader load_threaded_get_status  progress: Array = [] is always [0]

### ISSUE THREAD

**Issue by VP-GAMES** [godotengine/godot#56882] opened 2022-01-17 23:47 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 dev

### System information

Linux Ubuntu 20.04.3 LTS 

### Issue description

From Godot Documentation:
● ThreadLoadStatus load_threaded_get_status(path: String, progress: Array = [])

Returns the status of a threaded loading operation started with load_threaded_request() for the resource at path. See ThreadLoadStatus for possible return values.

An array variable can optionally be passed via progress, and will return a one-element array containing the percentage of completion of the threaded loading.

But progress value is always  [0]

### Steps to reproduce

It is simple to reproduce, run this Project: https://github.com/VP-GAMES/Godot4InteractiveSceneChanger

Add print(_progress) in func  _update_progress() [Line 53] in this script: https://github.com/VP-GAMES/Godot4InteractiveSceneChanger/blob/main/addons/interactive_scene_changer/InteractiveSceneChanger.gd

Output
[0]
[0]
[0]
[0]
.
.
n

**Comment by nathanfranke** [comment] 2022-05-04 01:40
I can't reproduce

```
0.5
0.5
0.5
0.5
0.5
0.5
0.25
```

**Comment by VP-GAMES** [comment] 2022-07-26 12:33
Fixed in godot 4 alpha 12 (I tested it) 
Output is float value from 0.0 - 1.0
[0.0]
[0.1]
[0.3]
[0...]
[0..]
[0.]
[1.0]

**Comment by metanoia83** [comment] 2022-10-16 23:53
Bug is still in beta 2. progress[0] output is always 0.

**Comment by gelvinp** [comment] 2022-11-05 06:27
Also having this issue in beta 4.

**Comment by owstetra** [comment] 2022-11-16 23:23
This bug is till in Beta 5 too

**Comment by donn-xx** [comment] 2022-11-24 16:26
Can confirm, Godot 4.0 beta 6, always [0] until last moment and then it's suddenly [1]. There is no graduation between.

**Comment by akien-mga** [comment] 2022-11-24 17:41
It would be useful to have a minimal reproduction project that actually exhibits the issue. It doesn't seem to be the case in the OP's project.

**Comment by donn-xx** [comment] 2022-11-24 19:57
[progress_bug.zip](https://github.com/godotengine/godot/files/10087037/progress_bug.zip)

Here's a small project. Have a look at the output. I'd expect to see 0.1, 0.2, 0.3 ... 1.0 or something like that but all one sees is 1. It may be due to the scene files it's loading being so small, but stuff them with some big gltf scene or something.

**Comment by erniel** [comment] 2022-12-25 14:53
the bug is still in godot 4 beta 10

**Comment by Bucham** [comment] 2022-12-29 18:15
It also happens to me in godot 4 beta 10. It goes from 0 directly to 1.

**Comment by akien-mga** [comment] 2023-01-10 10:46
> [progress_bug.zip](https://github.com/godotengine/godot/files/10087037/progress_bug.zip)
> 
> Here's a small project. Have a look at the output. I'd expect to see 0.1, 0.2, 0.3 ... 1.0 or something like that but all one sees is 1. It may be due to the scene files it's loading being so small, but stuff them with some big gltf scene or something.

Thanks! I tested, adding a big .glb in `scene0001.tscn` to be able to have more than one load step, and I can confirm the bug. It seemingly never worked in this scenario.

https://github.com/godotengine/godot/issues/56882#issuecomment-1195423772 reported it working in 4.0 alpha 12, but I think it's a different case.

Looking at the code:

https://github.com/godotengine/godot/blob/91713ced81792b10fdc9367b7f355738e5d52777/core/io/resource_loader.cpp#L389-L409

For a resource with dependencies, the progress value might be valid and report basically the dependency count. But in the `else` case, `load_task.progress` seems to always be 1.0. And indeed I don't see any code setting `progress` to a value different from 1.0.

**Comment by reduz** [comment] 2023-01-10 10:50
Same bug? #65380

**Comment by akien-mga** [comment] 2023-01-10 10:58
> Same bug? #65380

Indeed. @gotnospirit has a proposed solution there, would be good to have a PR unless you think it's not the right approach. https://github.com/godotengine/godot/issues/65380#issuecomment-1242892124

**Comment by reduz** [comment] 2023-01-10 17:32
Besides fixing #65380, I am not sure this is a bug and I don't think its possible to get reliable progress in all types of scenes. Let me explain how the threaded loading algorithm works so you understand why:

Scenes contain two types of resources:
* External resources (other resources stored on disk)
* Internal resources (sub-resources stored inside the resources you are loading).

To get the perfect load %, you would need to amount to all the tree of external resources until the very end. The problem is that, this is not know from the beginning because threaded loading has a limit on how many resources are being loaded at the same time.

This means that, at the beginning of the load, you only know the resource being loaded has N external resources, but not how many subresources they have. So, if you are loading a resource that is a single scene that has a subscene in another file, you don't know all the resources the subscene has.

The "correct" way to solve this would be, at export time, check the dependency chart of every resource and save it in some metafile, so you can tell in advance how many "steps" are needed to load the resource. This is a lot of work and beyond 4.0 expected feature set. It will probably get added at some point in the future.

**Comment by Zireael07** [comment] 2023-01-10 18:23
> The current algorithm should work going from 0 to 1 reliably because it splits every scene progress in

0-50% - All external resources
50-100% - All internal resources


Clearly, from this issue, it doesn't work like that. It's stuck at 0 and then suddenly jumps to 100.

I do not care that the rate is not constant. I don't care if the algorithm is not perfect, that the jumps are uneven, but I need the loading bar to make sense to my players and not look like the game's stuck immediately.

**Comment by donn-xx** [comment] 2023-01-11 09:01
Perhaps some kind of 'fake' progress that goes log slow until the recursion starts popping back up to the top level? I wouldn't mind an overall progress (at the top level) and then a different behaviour while Godot is plumbing the unknown depths of ones scene trees.

**Comment by realkotob** [comment] 2023-01-16 22:18
@reduz Your suggested solution is not bad but it is massively engineered in this case, as @Zireael07 pointed out we do not need a perfect percentage.

In many games and applications we are shown "Loading 2/10 files" which then changes to "Loading 42/389" etc. In unity this is shown when building an executable, the number of files is variable and also you usually only see 2 number snapshots of this before it jumps to the next resource category.

![image](https://user-images.githubusercontent.com/43449832/212772883-b440c30f-aac2-4258-8a78-a9ce9e33a018.png)

An actual percentage progress is not really necessary, just providing a "loaded file number" and a "total loaded + pending file number" would be completely adequate for showing to players in a loading screen.

So many games do not bother to show accurate percentages, like in The Sims where they just show nonsensical text. Sure there is a progress bar, but in some games it jumps around and that does not matter. What matters is being able to show progress. ANY progress.

![image](https://user-images.githubusercontent.com/43449832/212772696-8cedff56-5ebc-4431-ad55-5fcdd733f445.png)

I believe the old Windows file copy/download dialog is also a good notorious example, it was jumping around all the time and it still made sense on the whole.

![image](https://user-images.githubusercontent.com/43449832/212773260-891821f6-3bcc-4b5e-8473-085f68fb95cb.png)

This is an image from Windows XP, but even on Windows 11 now the file counter is not stable, although more stable because it enumerates them before it starts.

Again, this is not perfect and people might want an accurate progress percentage so they can use it for analytics reporting, preparing cutscenes or gameplay, but that is not the most common usecase. The most common use case is just showing some form of progress for the user. Currently there is 0 of that.

**Comment by TokisanGames** [comment] 2023-01-16 23:06
> Besides fixing #65380, I am not sure this is a bug and I don't think its possible to get reliable progress in all types of scenes. 

The bottom line is we need to give users some indication that the game has not crashed and is still loading. That's the whole point. A crashed game results in a refund, a bad review, and additional lost sales.

In Godot 3, the ResourceInteractiveLoader identified some 130 loading stages in my game and was able to give a finely detailed percentage. Now in Godot 4 it goes from 0 to 1. That is a major downgrade and is far too coarse. Continuous progress with 100% accuracy is unnecessary, and wasn't provided in 3. 

> The current algorithm should work going from 0 to 1 reliably because it splits every scene progress in
> 0-50% - All external resources
> 50-100% - All internal resources

There's two steps right there. You can easily get a list of all external sources and files that contain the internal resources and take a percentage of that. Or you can also get all of the file sizes of the files and the resources in the PCK and calculate based upon bytes loaded off the disk.

Even 25% chunks would be helpful. But surely there is a more reasonable solution. What did GD3 RIL do? Why can't you do that again?

**Comment by realkotob** [comment] 2023-01-16 23:12
@TokisanGames You pointed out what I wanted to say in a much more concise way 👍 

> What did GD3 RIL do? Why can't you do that again?

Godot 3 did not have threaded resource loading AFAIK, which is the differentiator here that adds complexity.

**Comment by TokisanGames** [comment] 2023-01-16 23:37
> Godot 3 did not have threaded resource loading AFAIK, which is the differentiator here that adds complexity.

[ResourceInteractiveLoader](https://docs.godotengine.org/en/stable/classes/class_resourceinteractiveloader.html) was the progress providing loader in GD3. It was removed in GD4, and now the only class available with an interactive loading poller is the threaded function of ResourceLoader. However it doesn't actually provide what the documentation says it provides.

It doesn't matter to me, and probably most other gamedevs, whether the loader is technically threaded or a single threaded process. The only thing that matters is an engine provided mechanism for providing progress to the end user. This ticket and the several other duplicate issues are not about threads, but about progress indication. The loader defaults to a single thread anyway. Multithreaded is broken.

Right now on my game, my title screen takes 13-17 seconds to load. I'm using single threaded mode and I get 0 for most of that time, then the last two frames are .75 and 1. So basically no progress.

In multithreaded mode my game may or may not load. I just tried three times. 2 failures stuck in a loop, one partial load. The game ran but half the assets were missing. In all three instances, progress started and ended at .874625. Never 0 or 1. So no progress and no load.

**Comment by eh-jogos** [comment] 2023-02-21 19:13
Still happening on 4.0rc3
![image](https://user-images.githubusercontent.com/13070158/220436743-4825d39d-7b1c-4d8d-9a71-aa42d6d64857.png)

> The current algorithm should work going from 0 to 1 reliably because it splits every scene progress in
> 
>     * 0-50% - All external resources
> 
>     * 50-100% - All internal resources

The algoritm @reduz  described in a [comment above](https://github.com/godotengine/godot/issues/56882#issuecomment-1377612987) does not seem to be working or I should have seen at least 0.5 somewhere. What I'm loading is a huge tscn with lot's of external resources, so at least in the 0-50% range I should be getting something, right?

I agree with the other comments, even if it was just counting the list of external resources in the tscn/tres and not going any deeper than that it would be a lot better.  I always had the impression the number of "stages" in Godot's 3.x ResourceInteractiveLoader was related to the list of external resources as they were usually close when loading scenes with it.

I also agree with the other comments this is a big "break" in relation to 3.x, is there any chance that there will be any improvements in this before 4.0 stable? Or is this going to be in a later release in favor of a more complex fix? 

Even if it only shows progress for .tscn and .tres files I think it's already an improvement.

**Comment by maximkulkin** [comment] 2023-04-02 13:54
Ok people. I've spent some time to debug this and I can confirm there is a problem. First I thought it was an issue with the memory synchronization between threads (because progress on each thread it's just pointer to a float). I did an experiment on replacing all progress pointers from pointer to a float to pointer to std::atomic<float>. That did not help. Though I think it will backstab you if you try to load resources using subthreads.

Then I did some more tracing and found out that the progress for loading external resources is just not reported: [Hello? Where is the progress report?](https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L514) It [does report progress for internal resources](https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L600-L602), though "resources_total" value ([obtained from "load_steps" field](https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L1099-L1103)).

After fixing this (in both Text and Binary ResourceLoader) it starts showing progress, but there's another issue. Documentation for ResourceLoader::load_threaded_get_status() [states](https://github.com/godotengine/godot/blob/1c1524a651e6d670d0d591b050d8c4bbb721d6e9/doc/classes/ResourceLoader.xml#L90):
```
An array variable can optionally be passed via [param progress], and will return a one-element array containing the percentage of completion of the threaded loading.
```
Notice "containing the **percentage** of completion". But if you look at it's [implementation](https://github.com/godotengine/godot/blob/1c1524a651e6d670d0d591b050d8c4bbb721d6e9/core/io/resource_loader.cpp#L429) it will be obvious that it returns value in range from 0 to 1. Not an end of the world, but some consistency would be nice.

And lastly, it's all good and dandy, unless you want to use subthreads. This part never worked for me. If my scene loads fine in single threaded mode, it produces errors if I do subthreads. And the reason for that is that both Text and Binary resource loaders in case of subthreads fire a request to load an external subresource, but they [never wait for them to finish loading](https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L469-L483). And when those loaders proceed with initializing internal subresources or main resource, in a lot of cases it ends up having external resources not loaded yet and thus complains about missing resources. There's just no waiting for them. Not sure if it was ever tested. And I believe once it will work, then it will start having those thread memory synchronization/stale memory issues.

**Comment by Zireael07** [comment] 2023-04-02 14:33
> Notice "containing the percentage of completion". But if you look at it's [implementation](https://github.com/godotengine/godot/blob/1c1524a651e6d670d0d591b050d8c4bbb721d6e9/core/io/resource_loader.cpp#L429) it will be obvious that it returns value in range from 0 to 1. Not an end of the world, but some consistency would be nice.

In programming, 0-1 indeed often is used to represent percentage. This should be clarified in the docs I think, it's not an implementation issue as such IMHO.

**Comment by maximkulkin** [comment] 2023-04-03 22:05
@RandomShaper I checked your PR and it's a great improvement. I especially like moving logic on spawning new load threads from particular resource loaders into central ResourceLoader. However, that PR won't fix the external resources counting problem, which seem to be the case here. I was holding my PR to figure out subtask loading, but since you've already took care of it, I will post my PR.

**Closed** 2023-05-11 08:55 UTC
Labels: bug, topic:core, confirmed

**Comment by Miguelito223** [comment] 2023-07-21 17:21
is happent the same to me

**Comment by matthew1006** [comment] 2024-01-29 11:22
This bug is still present in 4.2.1 web exports.

```
extends Node

@export_file("*.tscn") var scenePath
@onready var progressBar := $%ProgressBar as ProgressBar

func _ready():
	ResourceLoader.load_threaded_request(scenePath, "PackedScene")

func _process(_delta):
	var progress = []
	var status = ResourceLoader.load_threaded_get_status(scenePath, progress)
	print(progress)
	if status == ResourceLoader.THREAD_LOAD_LOADED: # Finished loading.
		get_tree().change_scene_to_packed(ResourceLoader.load_threaded_get(scenePath))
		
	elif status == ResourceLoader.THREAD_LOAD_IN_PROGRESS:
		progressBar.set_value(progress[0])
```

![image](https://github.com/godotengine/godot/assets/7364976/ed985efa-830b-4fe2-ba8f-84f7cb420d6e)
