### ISSUE TITLE
Function local Array variable not being reinitialised on repeat executions 

### ISSUE THREAD

**Issue by MagellanicGames** [godotengine/godot#35629] opened 2020-01-27 16:34 UTC
**Godot 3.1.2**

**OS**: Kubuntu 18.04 64-bit

In functions, if you declare a local Array variable without an initialising, it retains its data on each subsequent run (like a static function variable in C/C++).

I would like to mention, I tested this in 3.2 RC4 and the bug is fixed, I just wasn't sure whether this would be pulled back into 3.1 or a maintenance release in the future.
It might be similar to issue #27997, didn't quite understand.
Please ignore if that is the case.  Apologies if so.

**How to reproduce:**

- Create an empty 2d scene with a button.

- Connect the button to a function with no parameters

- Run and each pressing of the button will increase number of items in the array.  There should only ever be 2.

**Function Code**: 
`	

var array : Array
	
	array.push_back("String 1")
	array.push_back("String 2")
	print("Num items in array: " +  str(array.size()))`
**Minimal reproduction**
[LocalVarBug.zip](https://github.com/godotengine/godot/files/4118098/LocalVarBug.zip)

Obviously, being safe and initialising the variable will avoid this, ie _var array : Array = []_

**Comment by KoBeWi** [comment] 2020-03-05 13:31
Closing this as #28603 that fixed the issue is considered for 3.1.3

**Closed by KoBeWi** 2020-03-05 13:31 UTC
