### ISSUE TITLE
wiki doesn't has enough information about extending engine code

### ISSUE THREAD

**Issue by strobe** [godotengine/godot#72] opened 2014-02-14 13:50 UTC
Please update wiki about advanced topics like:
- what is general architecture of engine?
- how to start writing c++ extension?
- what is the export template from developer perspective and how it possible to 
tune template code or write new from scratch?
- what is development environment you would like to recommend to working on engine code?

In other words please also provide documentation for quick starting contribution for engine itself.

**Comment by akien-mga** [comment] 2015-10-29 10:40
Keeping this one open for the reference for now, but it will have to be moved to OpenProject once it is confirmed for documentation project management.

**Comment by akien-mga** [comment] 2015-10-29 10:44
Actually closing this one as duplicate of #73, since the latter has more participants.

**Closed by akien-mga** 2015-10-29 10:44 UTC
Labels: archived, needs discussion
