### ISSUE TITLE
Sprite Region Editor doesn't save states between sessions.

### ISSUE THREAD

**Issue by zinj** [godotengine/godot#3245] opened 2016-01-05 14:38 UTC
If you have a scene for a sprite setup, the sprite region editor always starts at a default state, (no grid, no snap, grid steps every 10px, zoom 1). So you need to set up the editor every time.

**Comment by volzhs** [comment] 2016-01-05 14:46
maybe it is duplicated issue with #3197

**Comment by zziinnjj** [comment] 2016-01-05 16:06
yes it is.

**Comment by vnen** [comment] 2016-01-05 18:01
Archiving this as duplicate of #3197. Thanks for spotting, @volzhs.

**Comment by MarianoGnu** [comment] 2016-01-05 19:39
This is not a duplicate, because i never setted the region editor to save the previous config (was waiting until someone complains :P ) anyway, #3197 must be fixed before this can be archieved

**Comment by akien-mga** [comment] 2016-01-05 20:04
Usually we archive duplicates even when the bug they duplicate has not been fixed yet ("archived" means either "duplicate", "won't fix" or "invalid"). But here since it will still be valid when #3197, I reopen it.

**Comment by reduz** [comment] 2016-01-07 12:29
It should save this state in the scene, but not in the global settings.
@MarianoGnu  I fixed the code that saves the config and opens it again (hopefully) so feel free to give this a try

**Comment by MarianoGnu** [comment] 2016-01-08 01:34
great to know

**Closed** 2016-01-11 10:28 UTC
Labels: bug, topic:editor, usability
