### ISSUE TITLE
Key presses lagging severely

### ISSUE THREAD

**Issue by PlasmaScreamTV** [godotengine/godot#41676] opened 2020-09-01 13:53 UTC
**Godot version:**
Godot version 3.2.2 stable mono

**OS/device including version:**
 Windows 10, 64-bit processor, 8 GB RAM, Intel Core i5-7200U CPU at 2.50 GHz

**Issue description:**
  If I, for example, press “F” nothing happens, even if I wait a while. Then if I press “H”, for example, the “F” appears instead. Then if I press Ctrl the “H” appears, and so on… This only happens when on the project select screen, though. As soon as I’m in a project, the key presses are just delayed by a second or so, instead of waiting for the next key press to happen.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-09-01 14:02
Duplicate of #23069. Try updating your graphics driver to the latest version *provided by Intel*. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2020-09-01 14:02 UTC
