### ISSUE TITLE
Middle click on functions to open docs

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#6115] opened 2016-08-11 14:17 UTC
When I was learning how to use game maker (or checking other people's code) I always made use of a nice feature of the code editor: when you use your middle mouse click you open the docs entry of that particular function/class you clicked.
It can also be opened from the right click menu.

So, if you have a "extends Node2D" at the top and you want to check the docs for that class you can click on it and read it instead of going to the docs tab and typing the class name.

I would love to contribute to the UI but I'm still getting used to source code.

**Comment by vnen** [comment] 2016-08-11 14:55
This is a bit problematic because it's hard to tell what is the real function due to duck-typing. Notice that you can press <kbd>Shift</kbd>+<kbd>F1</kbd> to open the search help dialog with the current function/class already filled in the search field. Many times you will see more than one result and the editor can't figure out which you mean, so that's why the search box opens.

Also, middle click is expected to be a paste function on Linux (even though it currently doesn't work, see #3030).

Finally, I pretty much prefer the <kbd>Ctrl</kbd>+<kbd>LMB</kbd> shortcut as proposed in #4807.

**Comment by reduz** [comment] 2016-08-11 15:01
Ctrl-lmb makes more sense to me.. when you hold control and move around, it
should underline selected identifiers

On Aug 11, 2016 11:55, "George Marques" <notifications@github.com> wrote:

This is a bit problematic because it's hard to tell what is the real
function due to duck-typing. Notice that you can press Shift+F1 to open the
search help dialog with the current function/class already filled in the
search field. Many times you will see more than one result and the editor
can't figure out which you mean, so that's why the search box opens.

Also, middle click is expected to be a paste function on Linux (even though
it currently doesn't work, see #3030
<https://github.com/godotengine/godot/issues/3030>).

Finally, I pretty much prefer the Ctrl+LMB shortcut as proposed in #4807
<https://github.com/godotengine/godot/issues/4807>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/6115#issuecomment-239186409>,
or mute the thread

**Comment by Zylann** [comment] 2016-08-11 18:02
There are cases where code completion works, so that means the editor was able to lookup the function. In these cases the help page should open if there is no ambiguity. For example, on a new script, if I trigger the help shortcut on `set_process`, the search opens instead of the page.

**Comment by vnen** [comment] 2016-08-15 14:33
Closing as duplicate of #4807.

**Closed by vnen** 2016-08-15 14:33 UTC
