### ISSUE TITLE
compile error current master branch on osx

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot#13333] opened 2017-11-27 05:14 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

I only tested on osx high sierra

**Issue description:**

master branch is broken as of this commit 8dc89e787c8b2bc444010d67bcb47378add80061

```
ools.64.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/libmodules.osx.tools.64.a(rand_win.osx.tools.64.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/libmodules.osx.tools.64.a(debug.osx.tools.64.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/libmodules.osx.tools.64.a(wincerts.osx.tools.64.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/libmodules.osx.tools.64.a(cpu.osx.tools.64.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: modules/libmodules.osx.tools.64.a(lookup.osx.tools.64.o) has no symbols
[ 51%] Compiling ==> platform/javascript/api/api.cpp
[ 52%] Compiling ==> drivers/unix/thread_posix.cpp
[ 52%] Compiling ==> drivers/unix/tcp_server_posix.cpp
[ 52%] Compiling ==> drivers/unix/ip_unix.cpp
[ 52%] Compiling ==> drivers/unix/packet_peer_udp_posix.cpp
[ 52%] Compiling ==> drivers/unix/file_access_unix.cpp
[ 52%] Compiling ==> drivers/unix/os_unix_global_settings_path.gen.cpp
drivers/unix/os_unix_global_settings_path.gen.cpp:3:17: error: out-of-line definition of 'get_global_settings_path' does not match any declaration
      in 'OS_Unix'
String OS_Unix::get_global_settings_path() const {
                ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [drivers/unix/os_unix_global_settings_path.gen.osx.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**

scons p=osx use_llvm=yes

**Link to minimal example project:**

i just tested the latest commit

https://github.com/godotengine/godot/commit/8dc89e787c8b2bc444010d67bcb47378add80061

**Comment by hungrymonkey** [comment] 2017-11-27 05:26
going to close for now. i am going to check my tree at the moment

**Comment by groud** [comment] 2017-11-27 05:58
Please remove the .gen.* files by running 'clean -f -X'. Then build again.

**Comment by akien-mga** [comment] 2017-11-27 06:44
Duplicate of #13076.

**Closed by akien-mga** 2017-11-27 06:44 UTC
Labels: archived

**Comment by hungrymonkey** [comment] 2017-11-27 12:55
thanks

**Comment by hungrymonkey** [comment] 2017-11-27 13:09
my bad should had check closed issues reports thanks
