### ISSUE TITLE
Interacting with Godot after Pop!_OS System Suspend causes computer restart

### ISSUE THREAD

**Issue by GlennHS** [godotengine/godot#93388] opened 2024-06-20 11:31 UTC
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Linux Pop!_OS (Latest Stable Release) - Godot v4.2.2.stable.official [15073afe3] - CPU i9-9900k - GPU 1060 6GB Nvidia

### Issue description

I put my machine in suspend mode at night and when I turn it on and navigate to Godot it doesn't respond to any input, the cursor doesn't change when mousing over interactive elements, and attempting to move the window causes my system to crash

### Steps to reproduce

 - Boot up Godot (latest stable version)
 - Create a new project or load an existing one
 - Put your machine into "Suspend"
 - Wake machine from suspend
 - Try interacting with Godot
   - Will be unable to interact with anything - *[Expected - Should work as normal]*
 - Try moving Godot's window
   - Will cause system to crash and restart - *[Expected - Should work as normal]*

### Minimal reproduction project (MRP)

N/A

**Comment by djtech-dev** [comment] 2024-06-24 19:35
By "system reset" do you mean that the Desktop Environment crashed (so you had to re-enter in your user/profile) or that the machine turns off (maybe with some "PANIC ERROR" writings on the screen)?

**Comment by Calinou** [comment] 2024-06-24 20:05
- See https://github.com/godotengine/godot/issues/52738.

**Comment by GlennHS** [comment] 2024-06-24 20:48
> By "system reset" do you mean that the Desktop Environment crashed (so you had to re-enter in your user/profile) or that the machine turns off (maybe with some "PANIC ERROR" writings on the screen)?

Yes, the desktop environment crashed and I had a full reboot cycle including going through putting in my cryptdisk password. There was no error message given, it just black-screened and started up again

> Also, from where did you install Godot? (website, flatpak, PopOS's package manager, ...)

I installed Godot from the website to my documents and then launch it via the launcher

**Comment by akien-mga** [comment] 2024-11-29 21:07
Duplicate of #52738 which is documented here:
https://docs.godotengine.org/en/stable/tutorials/troubleshooting.html#the-editor-project-freezes-or-displays-glitched-visuals-after-resuming-the-pc-from-suspend

**Closed by akien-mga** 2024-11-29 21:07 UTC
Labels: bug, platform:linuxbsd, topic:editor
