### ISSUE TITLE
[Editor] Some shortcuts in `ScriptEditor` are captured by `ShaderEditor`

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#56013] opened 2021-12-17 09:28 UTC
### Godot version

3.4.stable

### System information

Win10

### Issue description

Some shortcuts in ScriptEditor, like `Ctrl+K, Ctrl+Up/Down, Ctrl+D`, are captured and handled by ShaderEditor:

(I press `Ctrl+K` in ScriptEditor, but the line in ShaderEditor is commented, and the cursor went there)
![bug](https://user-images.githubusercontent.com/12966814/146521274-8ec3b3ad-7ed9-49e4-9686-cdacdd9cbf50.gif)

### Steps to reproduce

Open both Script Editor and Shader Editor. Press `Control+K`(toggle comment) in Script Editor.

**Comment by Calinou** [comment] 2021-12-17 17:02
This is a duplicate of another issue, but I can't find it right now. This most likely can't be fixed in `3.x` and will only be fixable in 4.0 as part of the editor shortcut rework.

**Comment by zaevi** [comment] 2021-12-17 18:33
> This most likely can't be fixed in `3.x` and will only be fixable in 4.0 as part of the editor shortcut rework.

Oh it's 3.x only, because I couldn't reproduce it in recent 4.0 build.

**Comment by akien-mga** [comment] 2021-12-17 18:35
Duplicate of #52861

**Closed by akien-mga** 2021-12-17 18:35 UTC
Labels: bug, topic:editor, topic:input
