### ISSUE TITLE
Editor stuck when closing project on macOS

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29371] opened 2019-06-01 08:54 UTC
**Godot version:**
3.1

**OS/device including version:**
MacOS 10.14.4

**Issue description:**
stucked when close some project

**Steps to reproduce:**
1. Open the project :
https://github.com/zszen/godot_lesson/tree/master/dodge_the_creeps
2. Do something or not 
3. close the project
4. stuck ....

I found that not all project stuck. Only someone. I don't know what is speciel with it. So I upload the code for report.

**Minimal reproduction project:**
https://github.com/zszen/godot_lesson/tree/master/dodge_the_creeps

**Comment by akien-mga** [comment] 2019-06-01 09:27
I cannot reproduce the issue on Linux with Godot 3.1.1.
This might be a duplicate of #29107.

**Comment by zszen** [comment] 2019-06-01 16:47
@akien-mga maybe cause by the simbol "!". From start the game learning, I fill with "Dodge The Creeps!" for the name. But it also stucked after I remove the simbol. I guess is it.

**Comment by KoBeWi** [comment] 2020-07-28 00:41
Can anyone still reproduce this bug in [Godot 3.2.3 rc1](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-1) or any later release?

**Comment by KoBeWi** [comment] 2020-09-28 22:24
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:24 UTC
Labels: bug, platform:macos, topic:core
