### ISSUE TITLE
Classes created in plugin using class_name not accessible via the editor

### ISSUE THREAD

**Issue by Granpappy** [godotengine/godot#58378] opened 2022-02-21 03:38 UTC
### Godot version

4.0 alpha 2

### System information

Windows 10

### Issue description

Named classes should show up in the GODOT editor for enabled plugins when adding a new node, but the editor does not recognize them.

### Steps to reproduce

1. Create new plugin
2. Add new script (under you newly created plugin folder) and give it a class name (class_name TestClass)
3. Enable this plugin
4. Make a new scene and click 'Add Child Node' under the 'Scene' tab
5. Search for your newly created class (TestClass)

If you find it, then I'm just a dunce. If you don't, then this is a bug.

### Minimal reproduction project

[PluginTest.zip](https://github.com/godotengine/godot/files/8106034/PluginTest.zip)

**Comment by TheDuriel** [comment] 2022-02-21 16:04
This is intended. Godot does not scan addons/ for class_names. You are meant to register the classes in your plugin script.

**Comment by Calinou** [comment] 2022-02-21 17:47
Duplicate of https://github.com/godotengine/godot/issues/30048.

**Closed by Calinou** 2022-02-21 17:47 UTC
