### ISSUE TITLE
Invisible palette

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#8450] opened 2017-04-18 21:08 UTC
**Operating system or device - Godot version:** Linux Mint Mate 18.1 (x64_86), custom_build 3.0 (commit 7088d9e)
**Issue description:** Just an invisible palette, which, after all, works as it should.
**Steps to reproduce:**
![image](https://cloud.githubusercontent.com/assets/5412322/25153083/b4dfd17e-24a4-11e7-9d05-3e19848895ae.png)

**Comment by karroffel** [comment] 2017-04-18 22:23
Duplicate of #8372

**Closed by karroffel** 2017-04-18 22:23 UTC
