### ISSUE TITLE
Autocompletion for string arguments adds extra quote (`'` or `"`) at the end of the string

### ISSUE THREAD

**Issue by hilias** [godotengine/godot#70535] opened 2022-12-24 20:23 UTC
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

On the text editor when using autocomplete on function arguments that receive Input Map names after autocompleting the function name, the string autocompleted appears with an extra " at the end.
This doesnt happen if you write " and then accept the Input name in the dropdown

### Steps to reproduce

- On the script editor
- Start writing `Input.get_vector` but when the dropdown appears with the autocomplete suggestion for `Input.get_vector` press enter to accept it, then press enter again to accept the Input map suggestion
- The autocompleted input name should have an extra "

### Minimal reproduction project

N/A

**Comment by hilias** [comment] 2022-12-24 20:32
[Recording](https://youtu.be/ML3J3v93p0Q) of the issue

**Comment by Calinou** [comment] 2022-12-24 22:18
This is a duplicate of https://github.com/godotengine/godot/issues/48436, but for the built-in editor. I can reproduce this on 4.0.beta8-9-10, but I think there's another open issue for this already.

**Closed** 2023-01-14 23:11 UTC
Labels: bug, confirmed, regression, topic:gui
