### ISSUE TITLE
Multiple viewports in 3D scene editor don't work

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8195] opened 2017-03-29 13:45 UTC
I'm pretty sure this is a well known issue, but I couldn't find it here, so I will open a new one for it. Currently most of the options under "View" in the 3d scene window don't work properly. So there is no way to work in multiple viewports or change the display mode (normal, shadeless, wireframe, overdraw). Clicking on the "Settings" dialog even crashes Godot completely. 

Godot version:  Godot 3.0 (master build from Mar 26, 2017)
OS: Arch Linux (Kernel 4.10.6)
GPU: Intel HD4000 with  Mesa 17.0.2

steps to reproduce are clear from the text description, i think.

**Comment by akien-mga** [comment] 2017-03-29 13:57
I'm pretty sure we have an issue template and it would be nice if you could follow it :) Your post lacks crucial information about what Godot version you are reporting that issue against.

**Comment by novemberist** [comment] 2017-03-29 14:07
Yes, sorry. I have updated my description.

**Comment by reduz** [comment] 2017-03-29 14:23
Ah, I remember they were disabled for a reason.. need to check why

**Comment by akien-mga** [comment] 2017-04-25 05:36
Closing as duplicate of the (newer) #8489 which is slightly more detailed.

**Closed by akien-mga** 2017-04-25 05:36 UTC
Labels: bug, topic:editor
