### ISSUE TITLE
Android ItemScrollList with Gridcontainer not scrollable on Button but on label only

### ISSUE THREAD

**Issue by DisDoh** [godotengine/godot#41959] opened 2020-09-10 19:31 UTC
**Godot version:**

3.2.2-stable

**OS/device including version:**

Android 10 and Android 8 not tested on other but same behavior is expected.

**Issue description:**

Android ItemScrollList with GridContainer not scrollable on Button but on label only.
I expected to be able to have an action_down on a button and move up or down but only label in GridContainer are having this behavior.

**Steps to reproduce:**
Create a node2d with a child ItemScrollList with a child GridContainer with
 some child label and button.

**Minimal reproduction project:**

[ListDeviceNode2D.tscn.zip](https://github.com/godotengine/godot/files/5204250/ListDeviceNode2D.tscn.zip)

**Comment by Calinou** [comment] 2020-09-10 21:02
Duplicate of https://github.com/godotengine/godot/issues/16318?

**Comment by DisDoh** [comment] 2020-09-10 21:04
yep thanks sorry for the duplicate

**Comment by akien-mga** [comment] 2020-09-11 06:39
Well that issue is fixed in 3.1, so not really a duplicate if it's back in 3.2.2.

**Comment by DisDoh** [comment] 2020-09-11 07:36
I've set the mouse filter of the button on pass and it works like that is it the way to do it or should it work without it?

**Comment by akien-mga** [comment] 2020-09-11 07:39
Ah right, that's the expected behavior I think. Buttons intercept mouse/touch input, so if you want to scroll instead of consume the touch event, they should indeed have mouse filter PASS.

**Closed by akien-mga** 2020-09-11 07:39 UTC
Labels: bug, platform:android, topic:gui, topic:input
