### ISSUE TITLE
GL compatibility 3D scaling

### ISSUE THREAD

**Issue by smallcloverstudio** [godotengine/godot#76301] opened 2023-04-20 17:24 UTC
### Godot version

4.0.2

### System information

Ubuntu, Windows11

### Issue description

when applying 3d scaling the viewport does not stretch to the window size.
![Screenshot from 2023-04-20 18-21-49](https://user-images.githubusercontent.com/127943614/233441566-0b74bafd-1841-42d9-9d46-9e6ad9a65f1f.png)
![Screenshot from 2023-04-20 18-21-19](https://user-images.githubusercontent.com/127943614/233441592-72288b5d-8862-4e51-b2ad-0fe4d59b387e.png)

### Steps to reproduce

very simple:
with glcompatibility back-end

set rendering/scaling_3d/scale to "<1" in project settings

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-04-20 17:28
Duplicate of https://github.com/godotengine/godot/issues/70142

Please remember to search existing issues before opening one of your own.

**Closed by clayjohn** 2023-04-20 17:28 UTC
