### ISSUE TITLE
Container won't update rect_size after Sprite child's region_rect increased.

### ISSUE THREAD

**Issue by MaaaxiKing** [godotengine/godot#39336] opened 2020-06-06 15:29 UTC
**Godot version:**
3.2.1.stable
**OS/device including version:**
Windows 10 Home 1909
Intel(R) UHD Graphics 620
GLES3
**Issue description:**
A container which has a Sprite child doesn't update it's size after the Sprite's region rect increased.
**Steps to reproduce:**
Create a scene with root Node Container. Add a Sprite as a child to it. Import a texture with repeat enabled. Set this texture to the sprite. Enable region. Set w or h to something bigger than the texture size.
**Minimal reproduction project:**

[Container Sprite region bug.zip](https://github.com/godotengine/godot/files/4740528/Container.Sprite.region.bug.zip)

**Comment by TheDuriel** [comment] 2020-06-07 09:18
Containers do not sort Node2D's. Use a TextureRect instead.

**Comment by kleonc** [comment] 2024-06-03 15:36
As mentioned Containers are meant to sort child Controls, not Node2Ds. Hence this behavior is expected, by design. Closing as not a bug (for proposing changes see https://github.com/godotengine/godot-proposals).

**Closed by kleonc** 2024-06-03 15:36 UTC
Labels: discussion, topic:gui
