### ISSUE TITLE
Animation Player Panel (is forced to be 100% width) and Pushes the whole UI to the right 

### ISSUE THREAD

**Issue by mohammedzero43** [godotengine/godot#60064] opened 2022-04-09 13:56 UTC
### Godot version

4.0 alpha 6

### System information

Win11 , Nvidia MX 450

### Issue description

When You open the animation panel, then you select a Control (UI) element , the whole interface is over-expanded and hides the icons and the panels on the right side of the screen

![Bug Screenshot](https://gcdnb.pbrd.co/images/zvMAr6DXjgAz.png?o=1)

### Steps to reproduce

1- Create Control Node 
2- Create Animation Player
3- Select animation player (and reveal animation panel)
4- Select Control Node (from step 1) again

**Comment by KoBeWi** [comment] 2022-04-09 16:03
Duplicate of #31133
(it's unrelated to AnimationPlayer btw)

**Closed by KoBeWi** 2022-04-09 16:03 UTC
