### ISSUE TITLE
Can't see remote node properties if it's a tool script

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#31257] opened 2019-08-10 02:59 UTC
**Godot version:**

Godot v3.1

**OS/device including version:**

Windows 10

**Issue description:**

I tried checking the node properties on the remote tab in the scene tree when running the scene but since the script of the node is a tool script it returns this error:

```Script inherits from native type 'Control', so it can't be instanced in object of type: 'ScriptEditorDebuggerInspectedObject'```

**Steps to reproduce:**
1. Create a scene
2. Create a node
3. Make a script, attach the script to the node and then make that script a tool script
4. Run the scene normally
5. Check the node in the remote tab
6. Engine returns above error

**Comment by Zireael07** [comment] 2019-08-10 07:36
Duplicate of https://github.com/godotengine/godot/issues/29506

**Comment by KoBeWi** [comment] 2019-08-10 11:17
Closing as duplicate.

**Closed by KoBeWi** 2019-08-10 11:17 UTC
