### ISSUE TITLE
Adding multiple extra call arguments to signal crashes, corrupts scene

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#58449] opened 2022-02-22 21:32 UTC
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10

### Issue description

When adding multiple extra arguments to signal call via editor, result is a crash (good case) or corrupted scene file (!). Result depends on exact steps, but either way adding multiple arguments doesn't work. Here's scene file contents before and after corruption:

Everything is good here:
```
[gd_scene load_steps=2 format=3 uid="uid://dwg012adkucx"]

[ext_resource type="Script" path="res://signal_binding.gd" id="1_cjsg7"]

[node name="Node" type="Node"]
script = ExtResource( "1_cjsg7" )
```
Here's corrupted version after I tried to add 2 bool values to the call (notice that script reference voids and instead of actual values there's nulls):
```
[gd_scene format=3 uid="uid://dwg012adkucx"]

[node name="Node" type="Node"]
script = 

[connection signal="ready" from="." to="." method="_on_node_ready" binds= [null, null]]
```

### Steps to reproduce

Here's how to corrupt your scene:
- Make new scene
- Add a script to a node (built in or external)
- Connect some signal to function, add 2 or more extra arguments
- Save

Here's how to crash:
- Edit any existing signal connection and add 2 or more extra arguments

**Comment by KoBeWi** [comment] 2022-02-22 21:49
Duplicate of #57057, but the scene corruption part is new.

**Comment by aXu-AP** [comment] 2022-02-23 08:14
Oh sorry, I tried searching for this, but signals in my head didn't connect. Maybe this should be closed in favour of existing issue, just move any new findings into that thread? It's likely coming from the same problem.

**Comment by akien-mga** [comment] 2022-02-23 08:28
Sounds good, could you add your findings to the other issue?

Closing as duplicate of #57057.

**Closed by akien-mga** 2022-02-23 08:28 UTC
Labels: bug, topic:editor, high priority, crash, regression
