### ISSUE TITLE
Crash！Ctrl + z to undo or   backspace when create a new folder in godot  4.0 stable editor

### ISSUE THREAD

**Issue by Kurt-Morrison** [godotengine/godot#74234] opened 2023-03-02 13:07 UTC
### Godot version

4.0 stable

### System information

ubuntu16.04

### Issue description

ctrl + z to undo or   backspace when create a new folder in godot 4.0 stable editor，crash！

### Steps to reproduce

ctrl + z to undo or   backspace when create a new folder in godot 4.0 stable editor

### Minimal reproduction project

Any scene

**Comment by akien-mga** [comment] 2023-03-02 13:10
Duplicate of https://github.com/godotengine/godot/issues/74197

**Closed by akien-mga** 2023-03-02 13:10 UTC
Labels: bug, platform:linuxbsd, topic:input
