### ISSUE TITLE
ResourceLoader.load_threaded_request use_sub_threads = true causes Editor + Player to hang.

### ISSUE THREAD

**Issue by cosmoddd** [godotengine/godot#78734] opened 2023-06-27 04:26 UTC
### Godot version

4.1

### System information

Godot v4.1.beta3 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3203) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When I use `ResourceLoader.load_threaded_request(_scene, "", true)` in 4.0.3 Stable, my set of three scenes loads in about five seconds.

When I use the same command in 4.1b3, to load the same data, the program hangs for roughly 3-5 minutes, or crashes.  After spending time troubleshooting, I am left with the impression that the use_sub_threads feature seems to slow down the editor when there are heavier scenes to load.  

I tried moving the level loading thread to a new thread group (the new 4.1 feature), but this threw a ton of errors dealing with the level loading being on the wrong thread. 

Other things I've done to try to alleviate the issue:

- clean reimport of .godot project file
- clean export to standalone build in Windows
- disabled physics where possible

All to no avail.  I'm including a smaller project so you can try to see what's happening during the `ResourceLoader.load_threaded_request(level, "", true)` command yourself.

I didn't change anything in my project - except upgrade to 4.1.

Possible regression?

### Steps to reproduce

Download and extract the project: [here](https://drive.google.com/file/d/1oRVXJjNyuqcimBIXDVf0Z0-UVdA8uJQu/view?usp=sharing)

Import the project.

Load in a series of models that test the engine's ability to load a large scene.

Play the scene and notice the load speed timer in the output window.

On line 16 of BaseLevel.gd, compare the editor behavior for 
`ResourceLoader.load_threaded_request(level, "", true)`
to
`ResourceLoader.load_threaded_request(level, "", false)`

Notice how there's a serious bottleneck when the use_sub_threads setting is set to 'true'.

### Minimal reproduction project

Download and extract the project: [here](https://drive.google.com/file/d/1oRVXJjNyuqcimBIXDVf0Z0-UVdA8uJQu/view?usp=sharing)

**Comment by RandomShaper** [comment] 2023-06-28 08:58
> [...] compare the editor behavior [...]

From the GDScript in the MRP:
> `# setting the threaded_request ot true causes a bottleneck in the editor`

I'm not sure I'm understanding the issue. The editor is not affected by that GDScript code, which is only executed at runtime.

I've tried anyway to trigger problems in multi-threaded loading, to no avail. I've even forced lower number of threads than actually on my system (12, to match yours; and even 4) and added an artificial delay to the load of each individual resource, to simulate a slower hard disk, to see if I could create some kind of deadlock.

So, I need more clues. It would be great to get minidumps at the moments of both the reported situations (locked for a long time and on the crash).

**Comment by cosmoddd** [comment] 2023-06-28 18:10
Here's a visual indicator of what happens when I load the game using both methods.
`ResourceLoader.load_threaded_request(level, "", false)`
![dimaond start no_thread_sm2](https://github.com/godotengine/godot/assets/9627628/2777cb21-d353-4678-b3cb-41a28db8e756)

`ResourceLoader.load_threaded_request(level, "", true)`
![dimaond start thread](https://github.com/godotengine/godot/assets/9627628/eb770acc-6728-43c9-970d-ea4092e2a9e1)

**Comment by RandomShaper** [comment] 2023-06-29 16:14
Thank you very much for the extra info, but sadly I'm still not able to reproduce the issue.

The best way of providing .dmp files would be to use WinDbg (unless you have it already installed, you can get it from https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/).

Once installed:
- Start the game.
- Start _WinDbg (X64)_ from the Start menu.
- In the menu bar, _File -> Attach to a Process_. It's easier if you select _By Executable_ and find the one starting with _godot_ in the list (be sure to pick the one corresponding to the running game, not the editor).
- Exercise the game until you run into one of the pathological situations.
- If it's the crash, the debugger will likely break itself.
- If it's the deadlock, you'll have to choose _Debug -> Break_ from the menu bar.
- Now, in the _Command_ window, at the botoom, you can type commands. Type this one: `.dump /mA C:\Users\<your_windows_user>\Desktop\godot.dmp` and hit Enter.
- Now you should have the roughly 1.5 GiB file there. Please provide it to me via some appropriate file sharing method (ideally, one for the crash and one for the deadlock).

I know it's a lot to ask, but it will help immensely. If someone from the production team can reproduce, they may help obatining the minidumps.

**Comment by cosmoddd** [comment] 2023-06-29 19:05
Thanks for getting back to me with detailed instructions on debugging this issue. 

Using the method above, I was not able to get my build to crash, only lock up.  

[Here is the minidump file, compressed in a .zip.](https://drive.google.com/file/d/1Kqa8U8QTl0bGKzx90hgQ9X3Gk1U4Tpt6/view?usp=sharing)  (lmk if you need me to post uncompressed)

Here is a gif of my screen following the steps given, including the errors thrown.

![dimaond start debug dump2_sm](https://github.com/godotengine/godot/assets/9627628/fb815271-7c83-4ca9-9261-f1a5f92b7761)

This error only occurred when `ResourceLoader.load_threaded_request(level, "", true)` was set to "true."  

I appreciate the attention on this issue and I hope my information is useful.

**Comment by kaist-kihwan** [comment] 2023-06-30 01:17
I have similar issue. When I use `ResourceLoader.load_threaded_request(scene, "", true)`, at certain point, the progress stops lke below.
```
0.53125
0.54166662693024
0.69014418125153
0.86001598834991
0.86001598834991
0.86001598834991
0.86001598834991
0.86001598834991
0.86001598834991
```

**Comment by RandomShaper** [comment] 2023-06-30 10:01
@cosmoddd, hmm... I was expecting the WinDbg you could download from there was the same I have on my machine (which is part of the Windows SDK), but it turns out it's a different one (maybe just newer?).

Thank you very much for providing the dump! It's actually a crash, by the way. If you can reproduce the stall at some point, please capture it, too.

Unfortunately, I didn't realize that we don't (and can't) have PDB files for official builds. However, I may still have a trick up my sleeve before having to ask you to get the minidumps from a custom build I would provide to you.

Aside, can you please try with the project setting `threading/worker_pool/use_system_threads_for_low_priority_tasks` being `false`. (@akien-mga, if that turns out to avoid the issues, we could at least document it as a workaround in the release notes in case I'm not able to do the proper fix, or make a PR that assumes the functional value of the setting.)

**Comment by univeous** [comment] 2023-06-30 11:39
I'm having the same issue in Godot 4.1 rc1.
After disabling `threading/worker_pool/use_system_threads_for_low_priority_tasks`, `ResourceLoader.load_threaded_request(level, "", true)` can properly load without hanging, but it spits out some error logs about `Attempting to initialize the wrong RID`. 
There are no such logs when `ResourceLoader.load_threaded_request(level, "", false)`.

**Comment by cosmoddd** [comment] 2023-06-30 11:55
I'd be happy to use a custom build if it gives you the info you need.  Let me know what the preferred protocol is for sending that over.

As for setting `threading/worker_pool/use_system_threads_for_low_priority_tasks` to false, that did made a difference!  My game's loading times behave as they did in version 4.0.3.  

One thing of note:

When I start a new game using `ResourceLoader.load_threaded_request(level, "", true)`
and `threading/worker_pool/use_system_threads_for_low_priority_tasks`, these errors are thrown.

![image](https://github.com/godotengine/godot/assets/9627628/17b0e9ce-ef6c-4a4b-9607-975e30e44a89)

I'm currently troubleshooting where exactly that happens in my scripts and will let you know once I find the issue.

**Comment by RandomShaper** [comment] 2023-06-30 15:09
Interestingly enough, I'm able to reproduce the issue with the official build, but neither with my local MSVC nor MinGW builds, despite being non-dev, etc. I still can investigate it with what I have (and @akien-mga will kindly provide). Stay tuned.

**Comment by akien-mga** [comment] 2023-06-30 15:53
Here's the config used for official builds: https://github.com/godotengine/build-containers#toolchains

Windows: MinGW 9.0.0, GCC 11.2.0, binutils 2.37, on Fedora 36

I'll make you an official build of 4.1-rc2 with debug symbols. In the past we've had crashes due to regressions in binutils.

**Comment by RandomShaper** [comment] 2023-06-30 18:18
If tomorrow is the release day, I won't have time to fix this for 4.1.0-stable in the end.

**Comment by akien-mga** [comment] 2023-06-30 18:26
Not tomorrow, but some time next week. But depending on the complexity of the bugfix, we might consider it out of scope for 4.1 already as we don't plan another RC (unless really needed), so we wouldn't take much risk.

**Comment by akien-mga** [comment] 2023-07-03 17:44
The issue is worked around by #78977, so this can be considered fixed. But I'll keep the issue open as I believe RandomShaper intends to look into a better fix later (though it's starting to look like we'd have to fix MinGW or GCC itself :)).

**Comment by cosmoddd** [comment] 2023-11-14 14:44
This issue has resurfaced in Godot 4.2 Beta6.  

The steps to reproduce this bug are exactly the same as described in my initial report.

The [Minimal Reproduction Project ](https://drive.google.com/file/d/1oRVXJjNyuqcimBIXDVf0Z0-UVdA8uJQu/view?usp=sharing) will consistently reproduce this issue.

**Comment by akien-mga** [comment] 2023-11-14 17:50
I don't seem to reproduce the issue on Linux, but that's consistent with the fact that this seemed to be a Windows/MinGW specific issue.

We changed the MinGW version we target in [4.2-beta3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/) to use a newer version. This might have impacted this. Could you test both [4.2-beta3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/) and [4.2-beta2](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-2/) and let us know if you see any difference?

If both still have the bug, could you test older dev snapshots to pinpoint the first one which regressed? (Assuming that you don't have the problem in 4.1.3-stable.)
Conversely, if neither have the bug, please test newer snapshots leading to beta6.

**Comment by cosmoddd** [comment] 2023-11-15 02:05
I've tested all the 4.2 betas in sequence with the Minimal Reproduction Project:

4.2-beta1:  no issues after Run Current Scene 10 times
4.2-beta2:  no issues after Run Current Scene 10 times
4.2-beta3:  no issues after Run Current Scene 10 times
4.2-beta4:  no issues after Run Current Scene 10 times
4.2-beta5:  no issues after Run Current Scene 10 times

4.2-beta6:  

When I press Run Current Scene in beta6, the loading is unpredictable.  The test either stalls and then crashes or loads quickly as expected.  This gif illustrates what's happening.

1 opens to scene
2 hang then crash
3 hang then open
4 opens
5 opens
6 opens
7 opens
8 opens
9 opens
10 opens
11 opens
12 hang then open
13 hang then  crash
14 opens

When I reopen the editor, I can usually get it to hang then crash at least once on the first three tries.

![loading thread issues return](https://github.com/godotengine/godot/assets/9627628/a934d8e4-06e8-4e29-935a-265da6a813b9)

A second test:

1 hang then open
2 hang then open
3 hang then crash
4 open
5 open
6 open
7 hang then crash

![loading thread issues return 2](https://github.com/godotengine/godot/assets/9627628/2bc1bddb-681b-4a9b-b1e7-f107f37b93c6)

**Closed** 2023-11-21 14:44 UTC
Labels: bug, topic:core, crash, regression
