### ISSUE TITLE
Tiles are seemingly randomly resetted in the editor

### ISSUE THREAD

**Issue by MarcusRiemer** [godotengine/godot#73674] opened 2023-02-21 11:41 UTC
### Godot version

Initially, 4.0.rc2, last seen on 4.0.rc6

### System information

1. Linux, Integrated Intel Graphics, Vulkan Backend
2. Linux, Nvidia Graphics with proprietary drivers, Vulkan Backend

### Issue description

"Something" in Godot 4 RC2 keeps removing properties I have set on tilesets not only during editing runtime, but also on disk. I didn't perceive this behavior earlier and I started working with Godot 4 around Beta 14.

### Steps to reproduce

1. Create a tileset with a terrain set that has two terrains.
![image](https://user-images.githubusercontent.com/2138773/220329260-ef4ed049-802d-49f5-b3b7-67c57224a013.png)

3. Paint some of the tiles properly.
![image](https://user-images.githubusercontent.com/2138773/220331735-3d374bcc-b165-47f5-bd0c-84b857ff088a.png)
![image](https://user-images.githubusercontent.com/2138773/220331983-1cb4afcd-f7ec-4cb9-ac6f-4d56372fb3dd.png)

4. Do some work in the editor / restart the editor. Neither triggers the problem with 100% certainty, but "often". I usually recognize this problem once the "Terrain" Tile Map painting tool shows nothing but the "Connect Mode" and "Path Mode" options for a certain terrain.

5. So suddenly all bits **except for the center bit are lost**. This also applies to e.g. physics layer properties, they are just gone. If I saved in the meantime, checking the changes in git reveals that these properties have indeed been deleted from the files.
![image](https://user-images.githubusercontent.com/2138773/220332748-665699b9-868f-4ac9-98f7-80e94f081a38.png)
![image](https://user-images.githubusercontent.com/2138773/220334155-0ace7b22-58ba-4f02-98b4-f747dba3da77.png)

### Minimal reproduction project

[godot-v4-tile-painting-repro.zip](https://github.com/godotengine/godot/files/10793038/godot-v4-tile-painting-repro.zip)

**Comment by groud** [comment] 2023-02-22 09:10
Could you check if this is still happening on RC3? We believe it might have been fixed.

**Comment by MarcusRiemer** [comment] 2023-02-23 18:53
There is still something odd going on here, after updating to RC3 it suddenly added physics properties that I'm quite certain to never have touched while editing my tileset:

![image](https://user-images.githubusercontent.com/2138773/221002462-26c5558c-d339-4f87-9324-aebc6c6b919e.png)

I also again lost some terrain bitsets, but I can't say with 100% certainty that this happened with the RC3. Will keep you posted either way, I sadly still haven't found a proper way to reproduce this. At this point I can't even say for sure that it is related to me actually using the tile editor.

**Comment by MarcusRiemer** [comment] 2023-02-25 20:03
I'm now on RC 5 and I can't quite tell whether this is related, but suddenly the tile editor stopped reacting to switching between tile graphic files. The image somewhat indicates this: I'm on a indoor dungeon tileset but whats presented to me are terrains from an outdoor tileset.

![image](https://user-images.githubusercontent.com/2138773/221375992-ad2a466f-bbc3-41c0-8c30-4ffd4cff6d7e.png)

The first load of a tile set seems to fail all the time:

![image](https://user-images.githubusercontent.com/2138773/221377257-f7988715-f0fd-405f-87fc-6b12fc72d8c2.png)

The errors in the output seem unrelated, although I don't have any plugins currently activated :thinking: 

```
Godot Engine v4.0.rc5.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:70 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.
```

**Comment by MarcusRiemer** [comment] 2023-02-25 20:12
The previous comment was edited, it contained a stupid mistake on my side :flushed: The described behaviour of mismatched terrains was a case of PICNIC.

**Comment by KoBeWi** [comment] 2023-02-26 21:39
@MarcusRiemer Do you have up-to-date reproduction project?
I tried the one you provided and can't reproduce any of the issues you described here.

I only found a very minor bug where TileMap tab does not appear if it's selected right after opening scene (due to being scene root in this case), caused by #72420

**Comment by MarcusRiemer** [comment] 2023-02-28 09:13
I sadly didn't manage to replicate it in the sample project either, but the bug occurred again yesterday evening in my "production" project. But this time I saw when it happened: I had moved the window focus away from Godot 4.0.rc6.mono (yes, I started experimenting with C# in the meantime) and the moment I re-entered the mouse and Godot regained focus all tiles were reset to the "middle only" state. The attached screenshot had correct terrain assignments just seconds before:

![image](https://user-images.githubusercontent.com/2138773/221805914-2cab57b3-9e99-477d-85da-90a61539aca9.png)

Thankfully I had saved before, so I could revert to a previous state by closing Godot and re-starting it. I didn't find a way to force reloading a resource other than a scene, so restarting Godot was the only thing that came to my mind.

**Comment by PrinceOfCanada** [comment] 2023-03-05 02:45
(Apologies if this is not formatted correctly, this is my first post.)

I can confirm I am having this issue as well. It happens fairly consistently for me, but I can't seem to figure out the _exact_ trigger. It happens consistently enough that I cannot make progress on my project as my tileset changes are deleted within minutes.

All of the painted data I save for the Tileset is removed, including collision masks and terrain details. Normal tile information, including tile animation, seems to save correctly.

![image](https://user-images.githubusercontent.com/45891129/222938211-b3c574ad-561a-497e-9117-876c5267e6e0.png)
![image](https://user-images.githubusercontent.com/45891129/222938217-16964f64-e76c-489b-9733-fa4184aef0b9.png)

I've attached a two screenshots of an example terrain painting being reset. In this particular instance, I clicked on a different window on my other monitor, and when I clicked back into Godot the error occurred, resetting the tiles as in screenshot two.

![image](https://user-images.githubusercontent.com/45891129/222938220-f163ebc8-a6f3-42d7-a9a3-c29eadd6470d.png)

The tileset editor also slows down slightly, which I assume has to do with the mass amount of errors that begin generating in the output. I took a screenshot (screenshot three) of the error messages, which took several minutes to load since Godot generated more than 200k of them in seconds. 

Extra details:
- This is the latest stable release of Godot 4.0
- Windows 10 System
- One of my tiles is animated, the rest are static. 
- Problem seems to occur more when rapidly switching between editing the tileset and editing the tile map, or possibly when switching between windows / when Godot loses focus. However I cannot confirm a one-to-one trigger. 
- When the issue occurs, I can also no longer paint anything on the tiles, nor can I paint tiles onto the tilemap. 
- Eventually Godot crashes due to the flood of errors.

**Comment by Zireael07** [comment] 2023-03-05 09:36
Can you attach your project?

**Comment by PrinceOfCanada** [comment] 2023-03-05 14:11
[Tilset Issue Project.zip](https://github.com/godotengine/godot/files/10891969/Tilset.Issue.Project.zip)
Absolutely! The tilemap I'm editing is in Farm.tscn/TileMaps/Back, and the tileset is called BackSpring.tscn.

**Comment by KoBeWi** [comment] 2023-03-05 20:01
Thanks, I was able to reproduce the issue.
It happens when a TileData points to a TileSet that does not exist, but I don't know what causes this.

**Comment by Loufe** [comment] 2023-03-07 23:48
Hi everyone, I cannot provide any test data as I'm unsure what exactly is causing it, but I'm wondering if my project is suffering from this issue as well. For whatever reason, the Physics Layer 0 property is occasionally completed wiped from a tileset. ALL other properties are conserved, for what that's worth. Here's an example, where the Z index values were preserved but not the physics layer 0:
![image](https://user-images.githubusercontent.com/5817861/223580881-47658e98-e92e-4204-834f-0f4798f9e0b6.png)

![image](https://user-images.githubusercontent.com/5817861/223580910-8f471f2e-518b-4d6e-9af2-13314252c9e6.png)

I saw a spam of red lines. Unfortunately I didn't have logging enabled and I took no screenshots, so I can't confirm if we're suffering the same problem as [PrinceOfCanada](https://github.com/PrinceOfCanada)

**Comment by sgt** [comment] 2023-04-02 13:25
I encounter this too. Haven't noticed what triggers this, but at some seemingly random moments my tileset (saved as a .tres resource) loses both the collision markup in the physics layer and the terrain markup as well. If I find out more, I'll report.

**Comment by sgt** [comment] 2023-04-02 18:27
I tried to localise the bug and found out it's happening when the Dialogue Manager (v2.14.0) plugin is present (this might also be the case with @SqueakyThePig 's project that uses it as well). My knowledge of Godot is limited and I couldn't find what causes this, but since this sometimes crashes the whole editor, maybe it's not just a problem with the plugin? Here is a sample project to reproduce this:

[tileset_troubles.zip](https://github.com/godotengine/godot/files/11133000/tileset_troubles.zip)

1. Click on TileMap node and open the TileSet Paint interface, selecting Terrain paint property, notice the painted terrain on top of the tilemap.
2. In Inspector, add new terrain for the existing terrain set, press ctrl-S to save.
3. Press Alt-Tab to switch focus to another app, then again to switch back.
4. Notice the terrain markup is lost (or sometimes Godot just crashes).

The error messages:

```
--- Debug adapter server started ---
--- GDScript language server started ---
Add Autoload
  editor/editor_node.cpp:8238 - Condition "plugins_list.has(p_plugin)" is true.
Add element to property array with prefix terrain_set_0/terrain_.
  drivers/gles3/storage/mesh_storage.cpp:487 - Condition "!mesh" is true. Returning: 0
[^^^ tons of those ^^^]
Attempt to disconnect a nonexistent connection from '<Object#0>'. Signal: 'property_list_changed', callable: 'Object::notify_property_list_changed'.
  scene/resources/tile_set.cpp:5408 - Condition "!tile_set" is true. Returning: false
  scene/resources/tile_set.cpp:5403 - Condition "!is_valid_terrain_peering_bit(p_peering_bit)" is true. Returning: -1
[^^^ tons of those ^^^]
```

**Comment by Loufe** [comment] 2023-04-02 18:32
@sgt I can confirm that we're also using Dialogue Manager, you're on to something.

**Comment by KoBeWi** [comment] 2023-04-02 21:43
The MRP from https://github.com/godotengine/godot/issues/73674#issuecomment-1455103492 where I confirmed the issue also has this addon 🤔

**Comment by nathanhoad** [comment] 2023-04-02 22:25
The Dialogue Manager doesn't have any actual references to Tileset stuff so I'm not sure how it would be related yet. I'll have a look at that example project when I get a chance and see if I can work out what's up.

**Comment by KoBeWi** [comment] 2023-04-02 22:32
It doesn't need to be related to TileSet. It might be e.g. wrong use of `_handles()` method or some UndoRedo shenanigans (AFAIK TileSet editor uses it in some unique way). I checked the `plugin.gd` and didn't find anything suspicious.

**Comment by sgt** [comment] 2023-04-02 23:13
I have localised the problem further. The TileSet reset is triggered when the plugin calls `get_editor_interface().get_resource_filesystem().scan()` on focus change (and then proceeds to update its own json configs -- I tried to disable the handler code, the problem is still there). My (uneducated) guess is that the TileSet somehow doesn't survive the scan() call for reasons unaffiliated with the plugin.

The call in question is at `main_view.gd:262`

**Comment by nathanhoad** [comment] 2023-04-03 00:56
@sgt I think you're right about there being an issue with calling `scan()`. Replacing it with a call to `reimport_files(open_buffers.keys())` seems to work and doesn't seem to crash in that test project any more (for me anyway). I have a bit more testing/optimisation to do but if that works then I'll make the change to Dialogue Manager and do a version bump.

**Comment by Loufe** [comment] 2023-04-03 00:58
Thank you both very much for your hard work on this, @nathanhoad @sgt , it's very much appreciated!

**Comment by nathanhoad** [comment] 2023-04-03 02:14
I've released [Dialogue Manager v2.14.1](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v2.14.1) which _should_ work around whatever is happening in `EditorFileSystem.scan()`.

**Comment by HelpfulFerret** [comment] 2023-04-10 09:57
I'm seeing the same (or a variant, at least) issue on Godot 4.0.2 without any plugins installed or running. I have one TileMap whose tileset collision changes aren't propagating to the terrain created with it. I am also unable to add or remove atlases from the tileset, the remove/add buttons are outright disabled now, and so are the Paint, Eraser and the 3 dots options.

I then created a new TileMap (thinking perhaps having created the original in 4.0.0 that some corrupted data had been present in it that might be resolved in a fresh 4.0.2 node) I was seeing a swarm of errors when I Erased some tiles, then undid it (though this one I cannot reproduce, it seems to work at the moment).

The repeating error thrown is
editor/editor_node.cpp:8243 - Condition "plugins_list.has(p_plugin)" is true.

**Comment by Lertos** [comment] 2023-04-10 21:47
I am having the same issue as @HelpfulFerret. No plugins installed, using 4.0.2. I have tried having the TileSet saved as a separate resource, as well as making it unique. Seems to randomly clear my physics layer values - it doesn't get rid of the layer, just all the saved collision layers (so that the player doesn't collide anymore).

**Comment by kvognar** [comment] 2023-04-15 00:57
This happened to me as well. I've updated my Dialogue Manager plugin so hopefully it won't happen again, but just want to throw my vote in for this as too.

**Comment by nathanhoad** [comment] 2023-04-20 08:55
Yeah the issue isn't technically a Dialogue Manager thing - as far as I can tell it's a problem with scanning in EditorFileSystem. The changes to Dialogue Manager just worked around the issue.

**Comment by Proggle** [comment] 2023-04-22 23:16
I can confirm this is happening to me without any plugins, having entire physics layers get wiped for my tilesets makes this sort of unsuable.

**Comment by cpuccino** [comment] 2023-05-17 11:03
Keeps happening on 4.0.2 stable (with mono) - although im not using dotnet on my code base
```
 0:4/0/terrain_set = 0
 0:4/0/terrain = 0
 0:4/0/probability = 20.0
-0:4/0/physics_layer_0/linear_velocity = Vector2(0, 0)
-0:4/0/physics_layer_0/angular_velocity = 0.0
-0:4/0/terrains_peering_bit/right_side = 0
-0:4/0/terrains_peering_bit/bottom_right_corner = 0
-0:4/0/terrains_peering_bit/bottom_side = 0
-0:4/0/terrains_peering_bit/bottom_left_corner = 0
-0:4/0/terrains_peering_bit/left_side = 0
-0:4/0/terrains_peering_bit/top_left_corner = 0
-0:4/0/terrains_peering_bit/top_side = 0
-0:4/0/terrains_peering_bit/top_right_corner = 0
 1:4/0 = 0
 1:4/0/terrain_set = 0
 1:4/0/terrain = 0
 1:4/0/probability = 5.0
-1:4/0/physics_layer_0/linear_velocity = Vector2(0, 0)
-1:4/0/physics_layer_0/angular_velocity = 0.0
-1:4/0/terrains_peering_bit/right_side = 0
-1:4/0/terrains_peering_bit/bottom_right_corner = 0
-1:4/0/terrains_peering_bit/bottom_side = 0
-1:4/0/terrains_peering_bit/bottom_left_corner = 0
-1:4/0/terrains_peering_bit/left_side = 0
-1:4/0/terrains_peering_bit/top_left_corner = 0
```

**Comment by MewPurPur** [comment] 2023-06-03 08:27
This just happened to me in 4.1.dev4, just confirming that we haven't accidentally fixed this yet. (vanilla Godot, no mods)

**Comment by akien-mga** [comment] 2023-06-26 09:11
While this is a nasty issue, it's unlikely to be fixed for 4.1-stable as we're now in release freeze, and any change to this logic might risk introducing other regressions. As soon as a potential fix is PR'ed, we'll assess it for cherry-picking to 4.1.x (and possibly 4.0.x if the fix seems safe enough).

**Comment by groud** [comment] 2023-06-26 09:15
> While this is a nasty issue, it's unlikely to be fixed for 4.1-stable as we're now in release freeze, and any change to this logic might risk introducing other regressions. As soon as a potential fix is PR'ed, we'll assess it for cherry-picking to 4.1.x (and possibly 4.0.x if the fix seems safe enough).

I recently made those two PRs: https://github.com/godotengine/godot/pull/78477 and https://github.com/godotengine/godot/pull/78561. They might have fixed the issue, but it is hard to know without reliable reproduction steps. Please let me know if anyone still experience the bug in the next release.

**Comment by sgt** [comment] 2023-07-07 17:17
Well, I tried out the reproduction steps I listed [previously](https://github.com/godotengine/godot/issues/73674#issuecomment-1493409225) and the problem doesn't seem to occur now.

**Comment by Proggle** [comment] 2023-11-03 20:35
I will say it hasn't happened to me since the update, so to me at least it seems like it's fixed and can be closed.

**Comment by KoBeWi** [comment] 2023-11-03 20:46
Closing then. Please comment if you still manage to reproduce in 4.2 beta4 or newer.

**Closed by KoBeWi** 2023-11-03 20:46 UTC
Labels: bug, topic:editor, needs testing, high priority, regression, topic:2d

**Comment by BradlyLanducci** [comment] 2025-05-11 17:10
I've been having similar issues, tiles in my tile maps are being modified on disk seemingly randomly without any errors. Sometimes they just disappear and all it takes is restarting Godot.

**Comment by KoBeWi** [comment] 2025-05-11 17:33
What version? Does it happen with TileMapLayer or TileMap?

**Comment by BradlyLanducci** [comment] 2025-05-11 17:39
It's happening on a TileMapLayer Godot Version 4.3.1

Here's a video of it happening. I can try to reproduce it in a new project I could upload.

https://github.com/user-attachments/assets/1c006d6f-82bb-48da-8a01-f117591196d0

**Comment by KoBeWi** [comment] 2025-05-11 17:44
That looks like unrelated issue.

**Comment by BradlyLanducci** [comment] 2025-05-11 17:48
Alright, well I'll keep investigating then.

**Comment by KoBeWi** [comment] 2025-05-11 18:03
I mean, it looks like a bug, but you should open a new report. A reproduction project with steps would be helpful too.

**Comment by BradlyLanducci** [comment] 2025-05-11 19:24
I went ahead and created an issue #106289
