### ISSUE TITLE
Low Resolution Sprite in Sprite Texture Preview [Godot 3.1 Beta 3]

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#25446] opened 2019-01-29 01:14 UTC
**Godot version: Godot 3.1 Beta 3**

**OS/device including version: Windows 10 64-bit Wacom Cintiq Companion 2**

**Issue description:**
Don't know if its a bug but for some reason the sprite texture preview is displayed at a low resolution when click and dragging a sprite from the FileSystem:

![image](https://user-images.githubusercontent.com/5027750/51877036-7b3c0480-231f-11e9-8451-531c4df20d80.png)

And I also found out that the sprite preview is also at low resolution if attempting to opening the file through a file window:

![image](https://user-images.githubusercontent.com/5027750/51877097-c0603680-231f-11e9-8cea-90f7c9b0b9a5.png)

**Steps to reproduce:**
Open a new 2D project and try bringing in high resolution sprites (A.K.A. Godot's "icon.png") to test the texture preview.

**Comment by volzhs** [comment] 2019-01-29 01:22
duplicate of #25378 and fixed by a089061

**Closed by volzhs** 2019-01-29 01:22 UTC
