### ISSUE TITLE
The "Saving" popup does not have the editor's theme

### ISSUE THREAD

**Issue by TamerSoup625** [godotengine/godot#71417] opened 2023-01-14 17:46 UTC
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10 Home 21H2, AMD A10-9620P RADEON R5, 64 bit system

### Issue description

The popup that appears in the center of the screen e.g. when saving a scene does not use the editor's theme, but rather uses the default theme. This appears both if using single window and multi window mode. This is clearly a regression.

https://user-images.githubusercontent.com/107559799/212487397-7b7f2425-9417-4ebf-97a5-b9efcb69dd73.mp4

### Steps to reproduce

1. Open any project with the editor.
2. Save a scene.
3. Notice how the default theme is used for the popup.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-14 23:33
Duplicate of https://github.com/godotengine/godot/issues/71351

**Closed by akien-mga** 2023-01-14 23:33 UTC
