### ISSUE TITLE
Race condition in `Resource::connect_changed`

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#96115] opened 2024-08-26 12:45 UTC
### Tested versions

4.3

### System information

Windows 11

### Issue description

62d9ce6445283d2bc1daa973350f91df56a826bf changed `Resource::connect_changed` to delay signal connection if the `ResourceLoader` is currently loading. This leads to issues if a ResourceLoader creates a `PackedScene` with eg a `MeshInstance3D` or `CollisionShape3D` on a thread other than the main thread.

```
<core\object\object.cpp(1369): Object::connect> Condition "!p_callable.is_valid()" is true. Returning: ERR_INVALID_PARAMETER:
Cannot connect to 'changed': the provided callable is not valid: MeshInstance3D::_mesh_changed

<core\object\object.cpp(1369): Object::connect> Condition "!p_callable.is_valid()" is true. Returning: ERR_INVALID_PARAMETER:
Cannot connect to 'changed': the provided callable is not valid: Node3D::update_gizmos
```

### Steps to reproduce

- create a loader that creates a `PackedScene` with `MeshInstance3D` and sets a mesh
- load a resource with the loader via `ResourceLoader::load_threaded_requet

### Minimal reproduction project (MRP)

-

**Comment by akien-mga** [comment] 2024-08-26 12:55
> ### Tested versions
> 
> 4.3

Please be more explicit, you mention 4.3 but then refer to a commit which has just been merged in `master` for 4.4, and thus isn't in 4.3.

**Comment by 0x0ACB** [comment] 2024-08-26 12:57
Uhm the commit has been added in 4.3 stable though. And I only downloaded the 4.3-stable tag:

![image](https://github.com/user-attachments/assets/41bb98ba-73be-49ec-ab89-6eb3b1f49df3)

**Comment by akien-mga** [comment] 2024-08-26 12:59
Ah my bad, I mistook #94526 for #94169.

**Comment by RandomShaper** [comment] 2024-08-26 13:01
An MRP would help immensely.

**Comment by 0x0ACB** [comment] 2024-08-26 13:25
This one triggers it quite reliably for me
[project.zip](https://github.com/user-attachments/files/16749139/project.zip)

**Comment by RandomShaper** [comment] 2024-08-30 06:49
My assessment so far:
- This is not what we usually call a race condition, as this behavior is deterministic.
- The only issue in a case like the one in the MRP is the warnings being printed, with no real damage.
- That said, I can see why this behavior would be a problem in a more complex loader that actually needs to change resources later than being assigned (e.g., the `PrimitiveMesh` changed later in the MRP).

**Comment by Hilderin** [comment] 2024-09-01 20:36
I think the cause for this issue also causes the issue #96443

While debugging #96443, I was able to find out that `MeshInstance3D::_mesh_changed` is executed after the inherited scene is loaded correctly.

In `MeshInstance3D::_mesh_changed`, it reverts back the overridden material.

![Image](https://github.com/user-attachments/assets/88e902f4-583b-40c1-99ff-84f8df82044d)

![Image](https://github.com/user-attachments/assets/7dbfe7bb-e481-4a4b-afda-f250b3fd97c5)




I think this also causes the problem I'm had a couple of times restarting the editor where all the material vanishes. I'm not able to find a way to reproduce it systematically:
![Image](https://github.com/user-attachments/assets/89ca610e-4a73-4bc5-8120-da03260186b3)

**Closed** 2024-09-06 09:13 UTC
Labels: bug, topic:core, regression
