### ISSUE TITLE
InputEventMouseMotion pressure and tilt returns 0

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#36319] opened 2020-02-18 11:00 UTC
**Godot version:** 3.2. stable

**OS/device including version:** Win 64

**Issue description:** 
According to the [3.2. changelog](https://gist.github.com/Calinou/49aefe52ce8f67ffa3f743932123d14f), pen pressure and tilt are now supported:

> Windows/macOS/X11: Support for graphic tablet pen pressure and tilt in InputEventMouseMotion.

However the pressure property will always return a float of 0 and the tilt property will always return a Vector2(0,0), regardless if you use a mouse or a tablet and pen, regardless of the pressure or tilt of my pen.

**Steps to reproduce:**
```
extends Node2D

func _input(event):
	if event is InputEventMouseMotion:
		print("pressure: ", event.pressure)
		print("relative: ", event.relative)
		print("tilt: ", event.tilt)
		print("speed: ", event.speed)
```

**Comment by akien-mga** [comment] 2020-02-18 12:02
CC @bruvzg

**Comment by ericrybick** [comment] 2020-02-19 21:58
Pressure works for me (Win 10 x64, Gaomon PD1560). However, I cannot test tilt because my tablet does not support it. 

![prts](https://user-images.githubusercontent.com/8831226/74879969-946c8480-536a-11ea-9f5f-0b45b6856093.png)


It could be helpful to know which tablet you are using. Have you checked whether pressure and tilt work in other programs?

**Comment by golddotasksquestions** [comment] 2020-02-20 10:39
I use a Wacom Intuos and I have no problem with pressure sensitivity or tilt in any other software, even web apps.

Someone on Reddit mentioned Windows Ink has to be enabled, but I checked and it is enabled.

**Comment by capnm** [comment] 2020-02-22 02:40
Related: https://github.com/godotengine/godot/issues/35793#event-3021986306 (3.2.+) 
The pressure value has been corrected, but the tile value range (now it is only half) has been broken under Linux.

**Comment by bruvzg** [comment] 2020-05-04 10:48
Pressure should be fixes after #35802, half value tilt after #37756.

**Comment by akien-mga** [comment] 2020-05-04 10:50
Closing as fixed by #35802 and #37756.

**Comment by golddotasksquestions** [comment] 2020-05-04 12:59
@akien-mga This is marked for Milestone 4.0, any chance this fix will be included in 3.2.2?

**Comment by akien-mga** [comment] 2020-05-04 13:35
If you look at the PRs, once is already in 3.1.1, and the other one has the `cherrypick:3.2` label, identifying it as a candidate for including in the 3.2 branch.

**Comment by golddotasksquestions** [comment] 2020-05-04 13:57
@akien-mga 

Yes, I've seen that. But issue is still present in 3.2.1 stable as well as 3.2.2 beta1. 
Pressure prints "0", tilt prints "(0, 0)"

This but has 4.0 milestone ... So I'm still confused if this fix will be added to 3.2.2?

**Comment by bruvzg** [comment] 2020-05-04 14:02
What version of Windows are you using? I did not notice this issue was about Windows, both fixes are for Linux only.

**Comment by SleepProgger** [comment] 2020-05-04 22:09
I can confirm this issue on Windows 10 with the `Huion HS610`. Pressure and tile are both zero.
Driver are the up to date Huion Driver.

The same code works fine on another Windows 10 machine with a `XP-PEN 22E Pro`.
Windows INK active in both cases.

**Closed** 2020-05-05 14:27 UTC
Labels: bug, needs testing, platform:windows, topic:input
