### ISSUE TITLE
Visual Shader - Unable to change varying data type

### ISSUE THREAD

**Issue by hannahbernal02** [godotengine/godot#90124] opened 2024-04-02 06:00 UTC
### Tested versions

- Reproducible in 4.1.stable.official

### System information

Windows 10 - 4..1.stable.official - Compatibility

### Issue description

Clicking on the datatype dropdown list in the Add Varying dialog cause the dialog to immediately close. This causes only varyings of float data types to be created.

### Steps to reproduce

1. Create a new Visual Shader script
2. Click on Manage Varying button
3. Select Add Varying
4. In the Add Varying dialog, name the new varying
5. Click on the data type dropdown list
6. Observe the dialog closes. The varying is not created

### Minimal reproduction project (MRP)

[Varying Bug.zip](https://github.com/godotengine/godot/files/14832160/Varying.Bug.zip)

**Comment by Chaosus** [comment] 2024-04-02 10:19
Seems like a duplicate of https://github.com/godotengine/godot/issues/79109. Check if it's fixed in 4.2.1 version.

**Closed** 2024-06-06 16:35 UTC
Labels: bug, topic:editor
