### ISSUE TITLE
CollisionPolygon2D vertex duplication

### ISSUE THREAD

**Issue by DersuG** [godotengine/godot#72231] opened 2023-01-28 06:19 UTC
### Godot version

v4.0.beta15.official
v4.0.beta16.official

### System information

Windows 10 (64 bit)

### Issue description

CollisionPolygon2D vertices are duplicated once drawn, sometimes hundreds of times. This seems to cause collision detection to bug out and make things teleport. EDIT: Still an issue on beta 16.
![Godot_v4 0-beta15_win64_2O8Gn0Tb3Q](https://user-images.githubusercontent.com/27244244/215250116-adce48fa-c496-49ea-a381-eada8243cdd3.png)
![Godot_v4 0-beta15_win64_TFUS8C1apB](https://user-images.githubusercontent.com/27244244/215250144-05848051-213a-4462-966b-b7162af9c33a.png)

### Steps to reproduce

Add a CollisionPolygon2D as a child of a StaticBody2D. Then, draw the vertices.
![Godot_v4 0-beta15_win64_5KCQQF4091](https://user-images.githubusercontent.com/27244244/215250211-f258a6c7-acb2-46a7-b9af-5284adfd0b96.png)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10526077/test.zip)

**Comment by bitsawer** [comment] 2023-01-28 06:44
Probably a duplicate of https://github.com/godotengine/godot/issues/72133

**Closed** 2023-01-28 12:37 UTC
