### ISSUE TITLE
Can't use Ctrl-A to select all in tool mode

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#2155] opened 2015-06-22 22:30 UTC
1. Choose any LineEdit in any Godot's tab ( for example pos of some node ).
2. Double click to edit it.
3. Hit Ctrl-A to select all text in this line edit.
4. "Add new node" window will appear instead of selecting all text.

**Comment by KillerJaguar** [comment] 2015-06-22 22:51
Ctrl+A globally to add new node has always been something that's annoyed me

**Comment by akien-mga** [comment] 2015-11-11 13:03
Duplicate of #1094.

**Closed by akien-mga** 2015-11-11 13:03 UTC
Labels: archived
