### ISSUE TITLE
BackBufferCopy GLES2 regression in v3.2.2

### ISSUE THREAD

**Issue by Zoomulator** [godotengine/godot#43644] opened 2020-11-18 12:52 UTC
**Godot version:**
3.2.2
3.2.3

**OS/device including version:**
Windows 10
GLES2
NVidia GTX 1060 6GB

**Issue description:**
BackBufferCopy doesn't copy at the right moment when using Godot >= v3.2.2 with GLES2. This worked fine in v3.2.1 of Godot, so this is a regression.
Works fine with GLES3.

v3.2.1 with GLES2
![bild](https://user-images.githubusercontent.com/1069303/99532541-c3209580-29a4-11eb-9ab3-ff075e223871.png)

v3.2.2 and v3.2.3 with GLES2
![bild](https://user-images.githubusercontent.com/1069303/99532730-0bd84e80-29a5-11eb-9411-1d6c1a76ee63.png)

**Steps to reproduce:**
* Create a 2D scene.
* Add a sprite.
* Add a BackBufferCopy.
* Add another sprite overlapping the first.
* Add a Mesh covering both sprites and set its shader to output `COLOR = texture(SCREEN_TEXTURE, SCREEN_UV) * vec4(1,1,1,0.5);`
* The result should make the second sprite semi-transparent.

**Minimal reproduction project:**
[BackBufferCopyGLES2.zip](https://github.com/godotengine/godot/files/5560065/BackBufferCopyGLES2.zip)

**Comment by akien-mga** [comment] 2020-11-18 12:59
It's a regression from the new 2D batching.
It also happens with GLES3 in 3.2.4 beta builds (tested 68973cadf71f66f8e6fab270e441f24a1ff213b4) as they now extend the batching to GLES3 too.

Disabling batching solves it both for GLES2 and GLES3.

**Comment by Zoomulator** [comment] 2020-11-18 13:11
@akien-mga Yep, confirmed that disabling batching works in my project. Thanks for the feedback!

**Comment by lawnjelly** [comment] 2020-11-18 14:45
K I'll take a look. :+1:

**Comment by lawnjelly** [comment] 2020-11-19 11:41
Ok got renderdoc installed, it looks like it is capturing the backbuffer twice, so the last version is when both rects are drawn (instead of just one capture with the first). This is probably due to the rects being batched together. This may not be too tricky to fix after all. :+1:

**Comment by akien-mga** [comment] 2020-11-25 07:26
Fixed by #43818.

**Closed by akien-mga** 2020-11-25 07:26 UTC
Labels: bug, regression, topic:rendering
