### ISSUE TITLE
Editor translations do not ignore fuzzy strings

### ISSUE THREAD

**Issue by ObaniGemini** [godotengine/godot#9371] opened 2017-06-25 18:59 UTC
*Bugsquad edit:* Repurposing this issue to track the actual problem: "fuzzy" translation strings are used by the editor, they should not be.

---

**GNU/Linux, Debian 9, 64-bit**

**Issue description**
On deleting an animation of *AnimationPlayer*, a pop-up appears saying "duplicate animation" instead of "delete animation".
Still there in 2.1.4

**Comment by anakimluke** [comment] 2017-06-26 02:16
For me, it shows "Delete animation?" when I click the trash can icon.

**Comment by bojidar-bg** [comment] 2017-06-26 09:16
It seems to be a bug with the french translation?
https://github.com/godotengine/godot/blob/e5d890c23ab6a9cb8edbbdb4a41db7f1a1653941/editor/translations/fr.po#L3053

**Comment by akien-mga** [comment] 2017-06-26 09:20
1. If it's a translation bug, you should have mentioned in the original issue that you're using the editor in French @ObaniGemini. We should not have had to guess it.
2. The string is marked as fuzzy. If it's displayed nevertheless instead of reverting to the English msgid, that's a bug that we need to fix. Fuzzy strings in gettext means that they need to be reviewed, and should not be used in production.

**Comment by ObaniGemini** [comment] 2017-06-26 13:23
Indeed, sorry about that. I didn't think about that kind of problem

**Comment by akien-mga** [comment] 2017-07-02 09:48
Repurposed the issue to track the real problem. Fuzzy strings should not be displayed/imported, the English translations should be used instead.

**Comment by r1cebank** [comment] 2017-07-05 17:15
I would like to take a stab at this issue, I found this file:
https://github.com/godotengine/godot/blob/master/editor/translations/extract.py
Am I looking at the right place?

Thanks

**Comment by akien-mga** [comment] 2017-07-05 20:14
Not exactly, that one is extracting the strings that need to be translated and then generates the template. Then the translations (po files) are synchronised with the updated template via `make merge`, and has the expected behaviour.

The issue happens when actually importing the translated strings from the .po files in the engine, so here: https://github.com/godotengine/godot/blob/master/editor/SCsub#L95-L142
Or when using the actual generated headers, so in the C++.

**Comment by r1cebank** [comment] 2017-07-05 21:07
Thanks @akien-mga, i will look at that.

**Comment by r1cebank** [comment] 2017-07-07 18:08
sorry to bug you again @akien-mga , i am trill trying to wrap my heads around how translation is being used in godot. I found in https://github.com/godotengine/godot/blob/826784d965a5200670f13709d69e3135bf1f4d9e/core/io/translation_loader_po.cpp#L112 we are skipping reading the line that starts with `#`, do you think this is the best place to fix issue? The SCsub files you gave me generate the header to be used later in the editor but I am not very sure how the header works.

Any help is appreciated, thanks in advance

**Comment by akien-mga** [comment] 2017-07-07 18:12
You seem to be on good tracks. The `if (l == "" || l.begins_with("#"))` should likely be split, and the case where the line begins with `"# fuzzy"` (or maybe begins with `"#"` and contains fuzzy, to be sure) should trigger some logic to ignore the next translated string.

**Closed** 2017-07-13 09:48 UTC
Labels: bug, junior job, topic:editor
