### ISSUE TITLE
Vulkan: 3D shadows are not disabled correctly

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#64503] opened 2022-08-16 16:38 UTC
### Godot version

4.0.dev (d5d22ab0)

### System information

Windows 10, Vulkan Clustered and Mobile

### Issue description

When enabling and then disabling shadows of a SpotLight3D, the shadows get stuck in a broken intermediate state.

You still see the shadows, but moving the light source does not update the shadows (merely updates the light's position and culling).

https://user-images.githubusercontent.com/5117197/184933011-08db3e6d-488e-4382-98f5-2e8ae4241038.mp4

### Steps to reproduce

- Create SpotLight3D
- Create objects that cast shadows
- Enable shadows, then disable shadows on the light

### Minimal reproduction project

[toggle_shadows.zip](https://github.com/godotengine/godot/files/9352827/toggle_shadows.zip)

**Comment by Calinou** [comment] 2022-08-16 19:53
Duplicate of https://github.com/godotengine/godot/issues/50343.

**Closed by Calinou** 2022-08-16 19:53 UTC
Labels: bug, topic:rendering
