### ISSUE TITLE
Inspector "Copy Rotation" feature copies in radians instead of euler

### ISSUE THREAD

**Issue by scraprats** [godotengine/godot#98319] opened 2024-10-18 20:56 UTC
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Not relevant

### Issue description

When copy-pasting rotation in the editor, pasted value is in radians instead of euler.

### Steps to reproduce

1.
![Screenshot_20241018_224707](https://github.com/user-attachments/assets/0583ecab-f37e-4fe4-b1ec-9d4f70f22e00)
2.
![Screenshot_20241018_224724](https://github.com/user-attachments/assets/06ea18a9-9e44-4b94-8b85-ddef3841887c)
3.
![Screenshot_20241018_224919](https://github.com/user-attachments/assets/c06f75ce-c76e-408f-b911-25d16e6e08c4)

### Minimal reproduction project (MRP)

N/A

**Comment by Ninjaboi8175** [comment] 2024-10-23 19:55
This doesn't appear to happen in 4.4.dev and properly copy-pastes euler angles between nodes.


https://github.com/user-attachments/assets/acdb0fda-8bf8-4c1d-983b-6203e916bc1f

**Comment by scraprats** [comment] 2024-10-24 08:32
> This doesn't appear to happen in 4.4.dev and properly copy-pastes euler angles between nodes.

Paste to exported Vector3 property.

**Comment by AThousandShips** [comment] 2024-10-24 10:26
Please upload an MRP to confirm that this is not user error and incorrectly configured properties

**Comment by scraprats** [comment] 2024-10-24 10:32
[Uploading new-game-project.tar.gz…]()

**Comment by AThousandShips** [comment] 2024-10-24 10:33
@scraprats You didn't let it upload completely, please try again make sure it has finished

**Comment by AThousandShips** [comment] 2024-10-24 10:37
You haven't exported the property as an angle, you need to register it as being edited as radians, using:
```gdscript
@export_range(-180, 180, 0.001, "radians_as_degrees") var angle_radians
```
Otherwise it will not treat the values any differently

**Comment by scraprats** [comment] 2024-10-24 10:40
No this is nonsense. This is a bug. You can obviously close this if you think this is acceptable behavior.

**Comment by AThousandShips** [comment] 2024-10-24 10:44
Did you try the suggestion? This is intended behavior, values are stored as radians, not degrees, if you copy them to something else they will be treated as the value they have

Please try the solution, if it doesn't work then it is a bug

**Comment by scraprats** [comment] 2024-10-24 10:45
This is a nonsense crutch and I am not going to use this. Unreal can do this right, Unity as well. Fix it or close it as invalid, it's up to you.

**Comment by AThousandShips** [comment] 2024-10-24 10:50
Please be constructive and reasonable, this isn't a "crutch" it's the way value handling is implemented

Closing as this is not a bug and there's a specific, dedicated, and documented system to handle this

**Closed by AThousandShips** 2024-10-24 10:50 UTC
Labels: bug, topic:editor, usability, needs testing

**Comment by syntaxerror247** [comment] 2024-10-24 11:12
@scraprats use this, it will solve your problem. I did not wanted to help due to your trashy behaviour but this is to show you that this wasn't a issue with engine, it was just you being hyper.
```
@export_custom(PROPERTY_HINT_RANGE, "-360,360,0.001,radians_as_degrees") var Pasted: Vector3
```

**Comment by scraprats** [comment] 2024-10-24 11:15
You're out of your mind.
