### ISSUE TITLE
[3.4.4.stable.official Web Editor] `print()` does not seem to work

### ISSUE THREAD

**Issue by Froggo8311** [godotengine/godot#59877] opened 2022-04-04 15:23 UTC
### Godot version

3.4.4.stable-web

### System information

HTML5

### Issue description

It seems that the `print()` function does not add to the "Output" panel.

### Steps to reproduce

Run `print()` in a GDScript file.

**Comment by Calinou** [comment] 2022-04-04 20:19
Duplicate of https://github.com/godotengine/godot-proposals/issues/3895. See also https://github.com/godotengine/godot/issues/45799 – this is due to missing debugger support, but it's likely impossible to achieve within HTML5's security confines.

**Closed by Calinou** 2022-04-04 20:19 UTC

**Comment by belzecue** [comment] 2023-01-14 18:48
Also see browser console workaround [here](https://github.com/godotengine/godot-proposals/issues/3895#issuecomment-1382885950).
