### ISSUE TITLE
round(), int() returns incorrect value

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#2057] opened 2015-06-09 15:17 UTC
```
print(round(123456.0), ",", round(123456789.0), ",", round(1234567890.0))
print(int(123456.0), ",", int(123456789.0), ",", int(1234567890.0))
```
both cases prints ``123456,123456792,1234567936``

**Comment by choikwa** [comment] 2015-06-09 17:49
sounds like precision issue. My guess is underneath implementation uses single-precision.

**Comment by akien-mga** [comment] 2015-11-12 14:41
Yes like @choikwa says, I guess it's a matter of using single precision for floats, and thus numbers with 10 significant digits like your second one show precision issues.

See #288 for a request to add double precision support.

I'll close the issue as I believe it's not a bug but just a consequence of #288 not being solvd yet, though feel free to tell me if you think this is not the appropriate resolution.

**Closed by akien-mga** 2015-11-12 14:41 UTC
Labels: archived, enhancement, topic:core
