### ISSUE TITLE
HTTP-Download is corrupted, when file is too big

### ISSUE THREAD

**Issue by BenjaDev** [godotengine/godot#11963] opened 2017-10-09 07:22 UTC
On Ubuntu 16.04
Godot Vers 2.1.1

I tried to download some videos. It worked, as I wanted to download a short video, but if the video is bigger than 4 seconds, the downloaded file is currupted. 

**Steps to reproduce:**
In example project, in http-script, there are 4 lines on top for downloading 2 different videos, one works, the other not. You just need to comment/uncomment 2 lines.

Links to the videos:
https://upload.wikimedia.org/wikipedia/commons/a/a4/Xacti-AC8EX-Sample_video-001.ogv (NOT working)
http://techslides.com/demos/sample-videos/small.ogv (working)

[example_download_fail.zip](https://github.com/godotengine/godot/files/1367743/example_download_fail.zip)

**Comment by groud** [comment] 2017-10-09 08:43
Godot 2.1.1 ? Can you try with 2.1.4 ?

**Comment by BenjaDev** [comment] 2017-10-09 09:28
Remains exactly the same. Tried it with 2.2 alpha, same problem.

**Comment by Zylann** [comment] 2017-10-09 10:20
Possibly duplicate of https://github.com/godotengine/godot/issues/7345
Which is itself a possible duplicate of https://github.com/godotengine/godot/issues/6103

**Comment by BenjaDev** [comment] 2017-10-09 10:27
I saw these issues, but i thought  ´OS.delay_usec(1)´ was the solution which didn't work for me.

**Comment by mhilbrunner** [comment] 2017-12-12 18:31
Using current master for Godot 3, both videos work fine after download.

I used the following code to download them with GDScript:
https://gist.github.com/mhilbrunner/7e30f057794b68cc5e3e23dc4be0b9c7

**Comment by akien-mga** [comment] 2017-12-13 07:14
Assuming fixed, please comment/open a new issue if it's not the case.

**Closed by akien-mga** 2017-12-13 07:14 UTC
Labels: bug, topic:network
