### ISSUE TITLE
Lock Selected Nodes causes signal `item_lock_status_changed` error

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#67868] opened 2022-10-25 12:12 UTC
### Godot version

v4.0.beta3.official.01ae26d31

### System information

Arch Linux

### Issue description

Locking or unlocking a node in the scene produces an error message:
```
ERROR: Error calling from signal 'item_lock_status_changed' to callable: 'SceneTreeEditor::SceneTreeEditor::_update_tree': Method expected 1 arguments, but called with 0..
   at: emit_signalp (core/object/object.cpp:1057)
```

### Steps to reproduce

1. Select a Node3D or CanvasItem node in the scene dock.
2. Click the lock icon labeled "Lock/Unlock Selected Node(s)" in the viewport toolbar, or use the Ctrl-L or Ctrl-Shift-L hotkey.
3. Observe error message in the output bottom panel.

**Comment by KoBeWi** [comment] 2022-10-25 13:19
Duplicate of #67557

**Closed by KoBeWi** 2022-10-25 13:19 UTC
