### ISSUE TITLE
Editing a Curve2D on Path2D causes a softlock

### ISSUE THREAD

**Issue by leaokaue** [godotengine/godot#97386] opened 2024-09-23 22:44 UTC
### Tested versions

- Reproducible in 4.3

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 (NVIDIA; 32.0.15.6081) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

Editing a Curve2D on a Path2D node causes a softlock on the current scene, making it so you can't make any other changes to the nodes in the current scene.

### Steps to reproduce

- Add a Path2D node and some other test nodes
- Edit the Curve2D, add some new points, move them around
- You will be unable to edit anything else in the scene, until you reload the current scene

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment] 2024-09-23 23:49
Same as #97248, duplicate of #96081

**Comment by kleonc** [comment] 2024-09-24 08:40
> Same as #97248, duplicate of #96081.

Hence closing this issue.

> This issue is already solved in 4.4 dev2.

And it's cherry-picked into 4.3.1 (not yet released).

**Closed by kleonc** 2024-09-24 08:40 UTC
