### ISSUE TITLE
Godot editor crashes when editing gdscript files from VS code

### ISSUE THREAD

**Issue by mmohatra** [godotengine/godot#53222] opened 2021-09-29 16:07 UTC
### Godot version

v3.3.3.stable.official.b973f997f

### System information

Linux Mint 20.2 Cinnamon, GLES3, AMD Ryzen 5 5500U with Radeon Graphics,  AMD RENOIR (DRM 3.40.0 5.11.0-37-generic LLVM 12.0.0)

### Issue description

Godot editor crashes when editing scripts using external editor VSCode with following stacktrace.

`handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fb879d8b210] (??:0)
[2] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0xe15f97] (??:0)
[3] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f78a1a] (??:?)
[4] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f288f5] (??:?)
[5] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0xe50446] (??:0)
[6] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0xe447b5] (??:0)
[7] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f2cec1] (??:?)
[8] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f2d90c] (??:?)
[9] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f64a28] (??:?)
[10] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x2f7fd1b] (??:?)
[11] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0xe142e4] (??:0)
[12] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x1cda1ae] (??:0)
[13] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x1ceb9c8] (??:0)
[14] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x3119a3d] (??:?)
[15] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x990dcd] (??:0)
[16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fb879d6c0b3] (??:0)
[17] /home/mmohatra/Applications/Godot_v3.3.3-stable_x11.64() [0x99f5ae] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)`

### Steps to reproduce

- Create a new script (Ex. **BaseTestScene.gd**)
- Create a new scene (Ex. **TestScene.tscn**)
- Attach a new script to **TestScene.tscn** named **TestScene.gd** where **TestScene.gd**  extends from **BaseTestScene.gd**
- Enable VS Code as use external editor in Editor->Editor Setting -> External
- Open and try to edit **BaseTestScene.gd** from VSCode and the godot editor crashes.
- Works normally when editing **TestScene.tscn** though.

### Minimal reproduction project

[Test Project.zip](https://github.com/godotengine/godot/files/7253398/Test.Project.zip)

**Comment by Calinou** [comment] 2021-09-29 16:22
Duplicate of https://github.com/godotengine/godot/issues/51923.

**Closed by Calinou** 2021-09-29 16:22 UTC
