### ISSUE TITLE
In "inspector" script variables doesn't shows

### ISSUE THREAD

**Issue by biomassya** [godotengine/godot#69003] opened 2022-11-22 14:04 UTC
### Godot version

3.5.1 stable

### System information

Windows 10

### Issue description

In "inspector" script variables doesn't shows If to add "export var"  in base script and extend it in other

### Steps to reproduce

1 Create KinematicBody2d 
2 Create a script ("Tank") with inheriting KinematicBody2d  (extend KinematicBody2d)
3 Create script inheritting from "Tank" script
4 Attach this new script to  KinematicBody2d node
5 Add to Tank script line "export (int) var Name":
6 Save
7 Select KinematicBody2d and look at tab ":Inspector:

There is no variable shows at all
Should show variable (property) Name

The solution is to restart completely GoDot editor

### Minimal reproduction project

[bugtest.zip](https://github.com/godotengine/godot/files/10068060/bugtest.zip)

**Comment by adamscott** [comment] 2022-11-23 12:37
Cannot reproduce on Godot 3.5.1 (Linux), unfortunately.

**Comment by DissonantVoid** [comment] 2022-12-22 20:41
The project works fine for me without changing anything, and I can see the exported variables in the inspector strange..
is the issue happening in the Minimal reproduction project for you? exactly as it is without changing anything?
don't mean to doubt you it's just weird how both I and the comment above this can't seem to reproduce the issue, can you recheck please?

**Comment by biomassya** [comment] 2022-12-23 22:17
It's working.

 22 2022 г. в 21:41, Dissonant Void ***@***.***>:

**Comment by Calinou** [comment] 2022-12-23 22:32
Closing per the @biomassya's comment. Please comment if you can still reproduce this on the latest Godot version.

**Closed by Calinou** 2022-12-23 22:32 UTC
Labels: topic:editor, needs testing
