### ISSUE TITLE
Class property array incorrectly displayed in extension_api.json

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#64426] opened 2022-08-15 09:06 UTC
### Godot version

4.0-rc13

### System information

n/a

### Issue description

Currently, class's property array are rendered in `extension_api.json` as regular properties:
```python
{
    "name": "AudioStreamRandomizer",
    [...]
    "properties": [
        {
            "type": "stream_",
            "name": "streams",
            "setter": "",
            "getter": "",
            "index": -1
        },
    [...]
}
```

However this is misleading:
- the value in type field is not a valid type (the `stream_` value comes from an "array element prefix" set when registering the property array)
- this property cannot be directly accessed (at least as far as I know: it is not present in the documentation and I couldn't find a way to access them from GDScript). Instead this property seems to be only used by the node editor.

So I guess this array property is not a real property and should be [added to the list of ignored ones](https://github.com/godotengine/godot/blob/eda6800f5dc01981f3626580d91a619b496acb5f/core/extension/extension_api_dump.cpp#L843-L848) when dumping the json

### Steps to reproduce

n/a

**Comment by raulsntos** [comment] 2022-08-15 13:35
Duplicate of https://github.com/godotengine/godot/issues/63066

**Closed by raulsntos** 2022-08-15 13:35 UTC
Labels: bug, archived, topic:gdextension
