### ISSUE TITLE
High CPU usage when AnimationTree is set to enabled

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58366] opened 2022-02-20 20:16 UTC
### Godot version

v3.4.3.rc1.official [894b6d504]

### System information

Mac OSX (Intel 2019)

### Issue description

When `AnimationTree` is set to enabled, the CPU usage of a scene jumps.

If you have multiple `AnimationTree`s then the CPU usage can easily get out of hand.

Related to https://github.com/godotengine/godot/issues/30115

### Steps to reproduce

1. Add an `AnimationTree`
2. Check CPU usage when enabled and disabled

### Workaround

Disable the `AnimationTree` in the editor but add a script to enable it when the game starts.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-02-20 20:20
Duplicate of https://github.com/godotengine/godot/issues/24705.

In the future, please spend more time searching for issues before opening a new issue :slightly_smiling_face:

**Closed by Calinou** 2022-02-20 20:20 UTC

**Comment by tavurth** [comment] 2022-02-20 21:08
@Calinou I performed three different searches for this and it didn't come up 🤔
