### ISSUE TITLE
Editor setting -> run -> Window Place -> centered is not actually centered

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#44169] opened 2020-12-07 14:59 UTC
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

In Editor Settings  -> Run -> -> Window Place -> Rect

If set to centered window is not actually centred on a screen. Top left corner of the window is in the centre of a screen whereas user will expect a centre of the window to be in centre of a screen.

**Steps to reproduce:**
Any project

**Minimal reproduction project:**

Any Project

**Comment by Calinou** [comment] 2020-12-07 15:01
Are you using a hiDPI display (Windows scaling above 100%)? If so, this is a duplicate of https://github.com/godotengine/godot/issues/13017.

**Comment by Feniks-Gaming** [comment] 2020-12-07 15:48
Yes this is the same issue. I have 1440p display scaled up above 100%

**Closed** 2020-12-07 15:52 UTC
