### ISSUE TITLE
C# AStar.SetPointDisabled(bool isDisable) inverted value

### ISSUE THREAD

**Issue by barrrettt** [godotengine/godot#33396] opened 2019-11-06 17:28 UTC
**IMPORTANT, PLEASE READ**

Feature / Enhancement requests are no longer accepted in the main Godot repository.
Please open an item by filling the relevant fields in the *Proposals* repository:

https://github.com/godotengine/godot-proposals/issues/new/choose

Do not submit to this repository or your issue will be closed.

**IMPORTANT, PLEASE READ**

**Comment by barrrettt** [comment] 2019-11-06 17:33
When use in c#: 
instanceAStar.SetPointDisabled(idPoint,true);
the point is Enable! not disable.

I think you have to change the name of the function (SetPointEnable) or internal behavior.

**Comment by Chaosus** [comment] 2019-11-06 18:16
This name was suggested and approved by @reduz, because disabling is more usual then enabling in that case. By default they are all enabled.

**Comment by Chaosus** [comment] 2019-11-07 11:53
I close this - the issue is just about a matter of taste (and the "rename something to something" requests currently pushed into https://github.com/godotengine/godot/issues/16863).
I think the API for AStar is pretty stabilized to not expect major changes in 4.0 and especially 3.2. The mono (C#) API is automatically generated from GDScript API which uses the syntax approved by @reduz.

Other than that, the issue is badly formed - please follow the template next time: https://github.com/godotengine/godot/issues/new?assignees=&labels=&template=bug_report.md&title= 

Also, no need to make warnings for other users in its description. It's a moderator's job.

**Closed by Chaosus** 2019-11-07 11:53 UTC
