### ISSUE TITLE
Re-export to macOS from Linux throws error in move_to_trash

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#42232] opened 2020-09-21 22:18 UTC
**Godot version:**

3.2.2.stable.custom_build.bc8eea3e9

**OS/device including version:**

Linux 5.8.8-arch1-1

**Issue description:**

Running "Export All" multiple times can cause an error as Godot fails to overwrite the prior export.

**Steps to reproduce:**

1. Set up an export for Mac (Runnable) `.zip`
2. Run "Export All"
3. Run "Export All" again
4. See error:

```
platform/x11/os_x11.cpp:3438 - move_to_trash: Could not move the resource "/home/rcorre/.cache/godot/JetHook.app" to the trash can "/home/rcorre/.local/share/Trash/files"
```

Manually removing "/home/rcorre/.cache/godot/JetHook.app" avoids the error.

**Minimal reproduction project:**

**Comment by aaronfranke** [comment] 2020-09-22 08:45
Please re-test with Godot 3.2.3 stable. Mac exporting is known to be broken in 3.2.2.

**Comment by akien-mga** [comment] 2020-09-22 08:47
> Please re-test with Godot 3.2.3 stable. Mac exporting is known to be broken in 3.2.2.

I don't think it would make a difference here, the issue is more with `move_to_trash` likely not handling folder deletion.

**Comment by bruvzg** [comment] 2020-09-22 08:50
Linux `move_to_trash` seems to use `mv` to move folders to the trash, without renaming it. If the `.app` folder from the previous export already exists in the trashcan it fails.

**Comment by rcorre** [comment] 2020-09-22 11:33
Could be related to https://github.com/godotengine/godot/issues/27526?

**Comment by bruvzg** [comment] 2020-09-22 12:04
> Could be related to #27526?

It's probably the same (at least move_to_trash part).

Bad solution: add `-f` to the `mv` and overwrite existing copy.
Better solution: check for existing copy and add number to newly deleted one (similar to node duplication naming).

**Comment by AnantAhuja** [comment] 2020-10-01 02:20
Can I work on this issue? Will I be working on the 3.2.3 branch or the master branch?

**Comment by rcorre** [comment] 2020-10-01 11:07
@AnantAhuja can you check if this is an issue on `master`? I did not.
If it is, then you should fix on `master` and backport to `3.2`.
Thanks!

**Comment by fredkozlowski** [comment] 2020-10-02 02:34
Hi, I've just submitted a PR for this on 3.2 that appends a number to the exports moved to trash. I just saw that you mentioned it would be good to test on master branch. I'll test that soon and cancel my existing PR? Or should I cancel it now and test on master then resubmit?

**Comment by rcorre** [comment] 2020-10-02 11:37
The [pull-request template](https://raw.githubusercontent.com/godotengine/godot/master/.github/PULL_REQUEST_TEMPLATE.md) says:

```
Pull requests should always be made for the `master` branch first, as that's
where development happens and the source of all future stable release branches.

Relevant fixes are cherry-picked for stable branches as needed.

Do not create a pull request for stable branches unless the change is already
available in the `master` branch and it cannot be easily cherry-picked.
Alternatively, if the change is only relevant for that branch (e.g. rendering
fixes for the 3.2 branch).
```

I can't really say, as I'm not a maintainer, but it would be preferable to target `master` first (and verify that this issue actually exists on `master` and wasn't somehow fixed).

**Comment by fredkozlowski** [comment] 2020-10-02 21:14
Gotcha, will check. Thanks for the help.

**Comment by rcorre** [comment] 2020-11-12 11:54
I just hit this again, and I noticed it is moving a file from `.cache`. I'd assume anything in `.cache` is safe to delete, so can we just `rm` it instead of Trashing it?

**Comment by akien-mga** [comment] 2020-12-03 07:37
#44021 will fix this. But indeed we could just `rm` the folder instead of moving it to trash here.

**Closed** 2020-12-03 10:09 UTC
Labels: bug, junior job, topic:editor, topic:porting
