### ISSUE TITLE
Building GridMap in a Thread may miss cells' both rendering and phsic body

### ISSUE THREAD

**Issue by LiBooks** [godotengine/godot#63106] opened 2022-07-17 11:47 UTC
### Godot version

Godot 4.0 alpha 12

### System information

Windows10  Vulkan

### Issue description

When I use GridMap in a Thread and use its “set_cell_item” function , I find that some cells cannot be set and it will also affect its octave. This is different from the bug I submitted before, because the missing cell not only has no rendering, but also has no physical body .And the loss of these cells occurs when gridmap runs “set_cell_item” function , but the previous bug occurred during the movement of players.

I checked the source code of gridmap , and I think the problem is between  “set_cell_item” function and “_octant_update” function .This is because when using GridMap to create a world , the thread often executes the "set_cell_item "function dozens or even more times, which will continuously write information to the "Octant" and "cell_map" . However, this part is only an operation on data , the code that really involves rendering and physical systems is executed by the main thread, which means that when the main thread works, other threads will still keep writing data to gridmap .In addition, the order of writing is to write into “Octant” first and then “cell_map”.
![QQ截图20220717185457](https://user-images.githubusercontent.com/69752853/179395141-f489f889-09fa-43a7-a409-030b8b478b23.png)
![QQ截图20220717190230](https://user-images.githubusercontent.com/69752853/179395195-f835b623-692e-4179-90f6-068ea9b4281a.png)

The above figure shows the code executed by the main thread. You can see that octant is accessed first, and then cell_ map。 However, due to the asynchronous execution of the thread, another thread may not have written to the cell_ map , and finally an error occurs in this place. Besides ,the previous code has erased the rendering and physical body of the cell in octant.

My suggestion is to change the order of the last few lines of "set_cell_item" function in "grid_map.cpp" file like the following figure.
 
![%QOCF54L501{9B B4RO@T)J](https://user-images.githubusercontent.com/69752853/179396449-e54e2f9a-0729-46a6-92af-c6e5035d9cf7.png)

### Steps to reproduce

The project uses gridmap to create the same world repeatedly, but by observing, you will find that some cells and octants in this world will disappear。

### Minimal reproduction project

[GridMap_BUG.zip](https://github.com/godotengine/godot/files/9127532/GridMap_BUG.zip)

**Comment by LiBooks** [comment] 2022-07-17 14:07
My suggestion is wrong and I will try to find the reason .

**Comment by Calinou** [comment] 2022-07-17 16:51
Duplicate of https://github.com/godotengine/godot/issues/42917.

**Closed by Calinou** 2022-07-17 16:51 UTC
Labels: bug, topic:core, topic:3d

**Comment by LiBooks** [comment] 2022-07-18 12:43
> archived

I 

> Duplicate of #42917. Thanks for posting your investigation nonetheless 🙂

I have thought of a way to solve this problem and tested it. I will submit the code later.
