### ISSUE TITLE
Project Manager doesn't draw latest state

### ISSUE THREAD

**Issue by VenteXx** [godotengine/godot#35377] opened 2020-01-20 19:42 UTC
**Godot version:**
3.1.2 but also 3.2 RC1 + 3.2 RC2

**OS/device including version:**
Windows 10

**Issue description:**
The Project Manager always skips the latest framedraw until the next should be drawn. This results in the UI being a framedraw behind. This can be observed by typing something into the search bar or just moving the cursor around. So for example if I start to type "search", first I type the 's' character and nothing appears. Once i type the next character the 's' appears.
This also affects the Godot startup because the Splashscreen shown beforehand doesn't get cleared and if i don't move my mouse inside of the UI the Project Manager basically doesn't show up.

Out of curiosity I tried an unofficial build of the 4.0 Vulkan branch and it seems to work there just fine.

I might record a video showing the issue if requested.

**Steps to reproduce:**
I guess this can't be reproduced on every System because there doesn't seem to be a Problem anywhere else, but for me it is: 
- Opening Godot

**Minimal reproduction project:**
None

**Comment by Zireael07** [comment] 2020-01-20 19:44
What is your GPU?

**Comment by akien-mga** [comment] 2020-01-20 19:47
Likely duplicate of #23069.

If so, updating your Intel GPU drivers should solve it. If your OEM artificially restricts the Intel drivers version available, you can install the latest version compatible with your GPU from Intel's support website.

**Comment by VenteXx** [comment] 2020-01-20 19:47
I'm just using integrated graphics. It's an Intel HD 505 (coupled with an N4200 processor if that matters).

**Comment by Calinou** [comment] 2020-01-20 20:20
Duplicate of #23069. Try updating your graphics driver to the latest version *provided by Intel*. Alternatively, start the Godot editor with the `--verbose` command-line argument, which can also mitigate the issue.

**Closed by Calinou** 2020-01-20 20:20 UTC

**Comment by VenteXx** [comment] 2020-01-20 20:30
@Calinou OEM So it didn't want to let me install newest Intel driver, so i had to force it. This didn't actually fix the issue, but `--vebose` did. So why does the `--verbose` argument fix it, because isn't it just for activating verbose console output or what is going on there

**Comment by Calinou** [comment] 2020-01-20 20:31
> So why does the --verbose argument fix it, because isn't it just for activating verbose console output or what is going on there

It does, but I guess printing something causes the editor window to redraw no matter if somethng changed.

**Comment by VenteXx** [comment] 2020-01-20 20:35
I know i could just make a shortcut, but can't this issue be fixed in a more permanent way (without the arg) ?
I mean i'm fine with this. I'm actually kind of happy that it behaves like it should now because it was a bit annoying, but i just want to know

**Comment by Calinou** [comment] 2020-01-20 21:09
@VenteXx We don't know what's causing the original issue in the first place. It appears to be fixed by accident in the Vulkan rewrite, so there's that :slightly_smiling_face:

**Comment by VenteXx** [comment] 2020-01-21 08:07
Guess i'll have to wait for 4.0 then. I really look forward to this release and I really like Godot :D Also thank you guys for the quick responses :)
