### ISSUE TITLE
A function to get a list of all defined functions in the current .gd

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3489] opened 2016-01-27 15:45 UTC
I'm looking for a function to get a list of all functions that I defined in the current .gd.

**Comment by StraToN** [comment] 2016-01-27 16:34
Duplicate of #3238

**Comment by AlexHolly** [comment] 2016-01-27 18:40
I think the solution of your issue will also work for my use case.
I don't need to see them in the editor but an array at runtime.

**Comment by StraToN** [comment] 2016-01-28 12:55
Oh, I get it : you want a **GDScript function** that gives you a list of all the functions in a .gd file. 
I think a Regex could help here, as function names are set between a **func** keyword and a semicolon.

**Comment by MarianoGnu** [comment] 2016-01-28 14:18
Un fact GDScript saves references of all functions stored by name, so it should be posible to get them. (Its already possible with c++)

**Comment by bojidar-bg** [comment] 2016-01-28 17:56
Are you looking for `Object.get_method_list`?

**Comment by AlexHolly** [comment] 2016-01-29 10:46
get_method_list gives me to much. I played a little bit around, but was not able to find my defined func's.

**Comment by reduz** [comment] 2016-01-29 10:59
do you want this for a specific use case?

**Comment by AlexHolly** [comment] 2016-01-29 11:07
Yes I'm playing around with REST and want to add "routes" to a service each route is one function. Currently I add them manually in ready() to my dictionary. I want this to happen automatically.

**Comment by reduz** [comment] 2016-01-31 18:32
I just realized method flags were not visible to script, only a flags field when using method_list
binded method flags (you can find them in globals), and added a METHOD_FLAG_FROM_SCRIPT
so you can tell which ones are from script

**Closed** 2016-01-31 18:41 UTC
Labels: feature proposal, topic:gdscript, usability

**Comment by AlexHolly** [comment] 2016-02-01 17:42
I don't know why I have to do +1 but it works now thanks

```
	for fun in get_method_list():
		if(fun["flags"] == METHOD_FLAG_FROM_SCRIPT+1):
			print(fun["name"])
```

**Comment by akien-mga** [comment] 2016-02-01 17:51
I think you need to use bitwise operators to evaluate the flags, as your function like has two flags here: METHOD_FLAG_NORMAL (1) and METHOD_FLAG_FROM_SCRIPT (64), hence the need for +1.

I don't have much experience with it, but I guess replacing `==` by `&` should do the trick (see https://github.com/godotengine/godot/wiki/gdscript#operators)

**Comment by AlexHolly** [comment] 2016-02-01 17:55
Yes! it works, thanks.

**Comment by me2beats** [comment] 2020-08-24 15:01
if anyone is still looking for a function to get a list of methods defined/overridden in a script, you can use this
```gdscript
var methods = obj.get_script().get_script_method_list()
```
