### ISSUE TITLE
display issue in landscape orientation on iOS

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11547] opened 2017-09-24 15:48 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1 
iOS

**Issue description:**

Just display an Admob interstitial ad in a game in landscape
the ads can not be displayed correctly.

**Steps to reproduce:**
This is the code in the module that add the interstitial to the root view :
  UIViewController *rootViewController = (ViewController *)((AppDelegate *)[[UIApplication sharedApplication] delegate]).window.rootViewController;
            [interstitial presentFromRootViewController:rootViewController];

**Link to minimal example project:**

**Comment by alexzheng** [comment] 2017-09-24 15:49
![img_9969](https://user-images.githubusercontent.com/1130047/30784171-f80ccfa0-a182-11e7-8376-844ecdd5f5d2.PNG)

**Comment by alexzheng** [comment] 2017-09-24 15:51
If the supported orientation of the iOS project is set to portrait, the ads can be display as expected.

**Comment by alexzheng** [comment] 2017-09-24 15:53
what it looks like in portrait
![img_9970](https://user-images.githubusercontent.com/1130047/30784189-70330b0c-a183-11e7-921f-41c6ac4ff5b1.PNG)

**Comment by akien-mga** [comment] 2017-09-25 11:10
We can't provide support for thirdparty modules. Until it's establish that it would be an engine issue, you should report bugs experienced with the admob module to its developers. If they can confirm that they are doing everything right and that the issue is in Godot, then they can open a bug report here.

**Comment by alexzheng** [comment] 2017-09-27 04:04
I reported this issue to google admob group, and they replied:
Hi there,

Thanks for providing me the requested information. However, I'm afraid that we do not support any third-party platforms and/or plugins in this forum (such as "Godot") and we will not be able to guarantee that everything will be working as intended. I would recommend you reach out to the support team of the platform/plugin you are using for further assistance on this.

Regards,
Joshua Lagonera
Mobile Ads SDK Team

**Comment by alexzheng** [comment] 2017-09-27 04:06
I think it's not the issue of the admob SDK, I have integrated the SDK in other engines and works well.

**Comment by alexzheng** [comment] 2017-09-27 06:49
I contact the Admob SDK developer and ask them to review my module code:
They replied:

Hi there,

I looked through your implementation and I didn't notice anything suspicious from our perspective, and the code implementation seems to be straightforward. Although I noticed that you seem to be using the Application's Root ViewController to present your Interstitial Ads and not the current ViewController. You can check out on where to appropriately display the Interstitial Ad from our official documentation.

As previously mentioned, it would be best for you to contact the support team of the platform you are using for further assistance as they are out of scope for our support.

Regards,
Joshua Lagonera
Mobile Ads SDK Team

**Comment by akien-mga** [comment] 2017-09-27 06:57
I was not telling you to get in touch with the Admob SDK developers, but with those who developed the Admob module you are using. There is no Admob integration in Godot, so you must have included it from a thirdparty.

**Comment by alexzheng** [comment] 2017-09-27 10:11
The module code is quite straightforward.
You can check the code here:
https://github.com/alexzheng/admob_for_godot.git

**Comment by akien-mga** [comment] 2017-09-27 11:02
It would have been useful to mention in the first place that you are the module developer..

**Comment by alexzheng** [comment] 2017-09-27 11:26
Because I thought the module code related to load and show the interstitial is nothing more than the demo code from the official documents, it's not important.
It must be something  issue related to the root view controller in the Godot code or the template project settings.

**Comment by groud** [comment] 2017-09-27 13:07
Isn't that a duplicate of #11628 then ?

**Comment by alexzheng** [comment] 2017-09-27 13:12
absolutely different issues.

#11628 is only happen on the iOS 11, and the content of game itself displayed incorrectly.

**Comment by alexzheng** [comment] 2017-09-27 13:14
really lots of issues after upgrade to iOS 11.

**Comment by alexzheng** [comment] 2017-10-03 11:46
Is any contributor taking care of this issue?
It really prevents the engine from publishing games.

**Comment by bojidar-bg** [comment] 2017-10-03 14:50
I know nothing of iOS (or OSx and Objective C), but the only thing related to their comment which I could find is:

https://github.com/godotengine/godot/blob/c5ab18f33e34b49b0603382af4af5e3fcd18c4ed/platform/iphone/app_delegate.mm#L91-L93

Not sure if it would help though :[

**Comment by alexzheng** [comment] 2017-10-04 01:21
UIViewController *rootViewController = (ViewController *)((AppDelegate *)[[UIApplication sharedApplication] delegate]).window.rootViewController;
           
 UIViewController *rootViewController = [AppDelegate getViewController];

This result is the same. It's just get the root view controller.
 There must be something wrong related to orientation in the root view controller.

**Comment by alexzheng** [comment] 2017-10-09 05:28
It happens when only landscape left and landscape right is enabled for the device orientation,if portrait is also enabled, it will show correctly.

**Comment by akien-mga** [comment] 2017-10-14 08:15
Maybe @BastiaanOlij or @endragor can help with this one and #11628.

**Comment by BastiaanOlij** [comment] 2017-10-14 13:08
Haven't done too much with this in iOS 11, I've locked my projects in landscape mode because you don't want this sort of rotation for AR, Apple does some weird stuff. When I did accelerometer and gyro code I did spend some time making sure it worked correctly with auto rotation but that was purely in detecting what the rotation was.

Wish I knew more about this to actually give some worth while advise.

**Comment by alexzheng** [comment] 2017-10-14 15:15
this issue is not only happens on iOS 11,it also happens on iOS 10.
#11628 only happens on iOS 11.
And the termination issue #11623 also only happens on iOS 11.

**Comment by alexzheng** [comment] 2017-10-14 15:17
This issue happens even if locked the project orientation to landscape.

**Comment by sersoong** [comment] 2017-11-09 12:49
# Same Issue.
I can **confirm** that it was caused by the godot **compile** procedure.
But I don't know how it happened.
Maybe some compile flags was wrong.
You can try this code in **app_delegate.mm**:
Just put it in '**application didFinishLaunchingWithOptions**' function

```
self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
CGRect rect = [[UIScreen mainScreen] bounds];
printf("**************** app rect:%f %f\n",rect.size.width,rect.size.height);
```

You will find the rect value was wrong.
For example:
the rect of iphone 5s in landscape mode is 
**************** app rect:568.000000 320.000000
but,Its actual value is
320 568
So I guess the admob set width and height by this value.
@alexzheng @akien-mga @BastiaanOlij You should pay attention to it.

**Comment by sersoong** [comment] 2017-11-10 04:41
I've found the reason.
And fix it in my code.
Perfect.
![capture](https://user-images.githubusercontent.com/24988459/32643171-6f2dfbf8-c614-11e7-8e66-9eb8337da0ec.jpg)

**Comment by alexzheng** [comment] 2017-11-10 09:15
What did you modified？
It seems nothing need to modify after changing the compile SDK path.

**Comment by Calinou** [comment] 2020-06-07 14:39
@alexzheng Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by alexzheng** [comment] 2020-06-07 14:56
no

**Comment by akien-mga** [comment] 2020-06-07 15:45
Closing as fixed then.

**Closed by akien-mga** 2020-06-07 15:45 UTC
Labels: bug, platform:ios, topic:porting
