### ISSUE TITLE
Upper folder file ".." does not work in filechooser

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#11087] opened 2017-09-09 06:54 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mageia 6

**Issue description:**
In the Project manager, navigating the filesystem is difficult because double clicking the upper folder ".." does not have any effect.

![image](https://user-images.githubusercontent.com/1289207/30237899-455d7adc-953c-11e7-9aa3-85c4fa9b52f6.png)

**Steps to reproduce:**
Create a new project and move to the upper folder.

**Link to minimal example project:**
N/A

**Comment by hpvb** [comment] 2017-09-09 20:02
I was looking at this earlier today but it seems to be fixed on current master. Can you verify that?

**Comment by kubecz3k** [comment] 2017-09-11 08:59
I can confirm in 9a8acbaed532f634fdf851e9bed2e200b12c5c41 (confirmed with 'import' dialog)

**Comment by hpvb** [comment] 2017-09-11 09:35
OK, strange, it seems to be working for me on Linux/Fedora 26 now, while it previously was not. We'll have to investigate what's up. Project manager navigation works properly for me now at least. I'll look at some more dialogs. Sorry!

**Comment by StraToN** [comment] 2017-09-12 17:27
Seems fixed in current master.

**Comment by kubecz3k** [comment] 2017-09-12 17:53
Yes it's fixed for me also

**Closed by kubecz3k** 2017-09-12 17:53 UTC
Labels: bug, confirmed, topic:editor
