### ISSUE TITLE
Theme doesn't apply to tooltip

### ISSUE THREAD

**Issue by mastermarkus** [godotengine/godot#25058] opened 2019-01-17 10:51 UTC
**Godot version:**
3.0.6 stable
[tooltip_bug_demo.zip](https://github.com/godotengine/godot/files/2768284/tooltip_bug_demo.zip)

**OS/device including version:**
Windows 10 64bit

**Issue description:**
When adding theme to regular GUI button that's inside VBoxContainer you can't change it's style

**Steps to reproduce:**
1)Create new scene
2)Add VBoxContainer to scene as root node
3)Inside VBoxContainer add "Button" node
4)Click on Button node in Node Explorer
5)Go to button properties look for category "Hint" and change Tooltip property to some text
6)Now still under Button node, look for category "Theme", click on theme dropdown - > "New Theme"
7)Context menu should appear a the bottom with GUI controls, find "Edit Theme..." at the top of context menu
8)Click on "Edit Theme..." -> "Add Class Items"
9)Click on two dot's (..)  -> Find "Tooltip Panel" then click on it
10)Click on "Add All"
11)Now in inspector window look for "Tool tip Panel" and click on it
12)Under "Tooltip Panel" click on style folder and on"Panel" click the drop down menu, click "NewStyleBoxFlat", click drop down again and then "edit" and then you should see "Bg Color" property change that to red for example.
13)Now save scene and try out if the Tool Tip theme worked

If you set up the node hierarchy exactly how i described it shouldn't work and you should see Default tool tip that has white/grey background with black borders and black text.

**Minimal reproduction project:**
The project demo zip is provided above

**Comment by Andrettin** [comment] 2019-03-02 09:31
I am encountering the same issue. I added tooltip label and panel settings to a texture button's theme; the button is itself a scene. When I play the button scene by itself, the tooltip appears correctly. When I instance the button scene within another scene, the tooltip shows with the default settings.

**Comment by Chaosus** [comment] 2019-03-04 18:10
Duplicate of #18478

**Closed by Chaosus** 2019-03-04 18:10 UTC
Labels: bug, topic:core
