### ISSUE TITLE
[MacOS] Top menu is missing in 4.1 builds

### ISSUE THREAD

**Issue by gokomer** [godotengine/godot#78923] opened 2023-07-01 23:39 UTC
### Godot version

v4.1.rc2.official [46424488e]

### System information

MacOS 14.0 Beta (23A5276g) - M2 Pro 

### Issue description

Top menu is missing in all the 4.1 builds. I've tried all the beta, dev and rc builds. It works in 4.0.3 stable version.

![image](https://github.com/godotengine/godot/assets/11593018/c66a9832-443b-4b6f-bd7f-1d3f113b5c71)

### Steps to reproduce

Open any project.
Top menu is missing.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment] 2023-07-03 06:52
I can't reproduce it, might be macOS 14.0 Beta specific issue.

**Comment by gokomer** [comment] 2023-07-03 11:50
Unfortunately I don't have macos 13 device to test it. I thought since it works in 4.0.3 it is a Godot regression.

**Comment by Gokhan-Uysal** [comment] 2023-07-03 12:04
It is visible in MacOs13.4.1

**Comment by bruvzg** [comment] 2023-09-27 09:39
Can't reproduce on the release version of Sonoma (14.0 - 23A344) either, probably was a beta bug.

**Comment by YuriSizov** [comment] 2023-11-15 14:56
Closing based on the discussion above.

**Closed by YuriSizov** 2023-11-15 14:56 UTC
Labels: bug, platform:macos, topic:porting, regression
