### ISSUE TITLE
Find in files popup flickers indefinitely

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#72062] opened 2023-01-25 18:01 UTC
### Godot version

v4.0.beta.custom_build [9de0c73e4]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

When opening the Find in files popup on a script, the window flickers indefinitely (the focus toggles between the main Godot app and the popup very fast), making all interactions break (it may even affect other apps like code editors and the System Monitor, but you can kill the process by opening the System Monitor and right-clicking on godot, as the keyboard may not work).

![Godot v4 0 beta custom_build  9de0c73e4  - Find in files popup flickers indefinitely](https://user-images.githubusercontent.com/1067772/214644737-a4d141f4-9e6f-4c48-a43c-c5d25402707c.gif)

The issue is not present on beta snapshot 13.

The issue doesn't occur if you select a mere doc page instead of a script.

### Steps to reproduce

0. I recommend opening a System Monitor to get ready to kill the process
1. Open a project and open a script
2. Open the Find in files popup (Ctrl+Shift+F)
3. Try to close the popup: it doesn't work
4. You can minimize or maximize it, but it keeps running like crazy in the background
5. Kill the godot process

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-25 18:09
Duplicate of https://github.com/godotengine/godot/issues/72012

**Closed by akien-mga** 2023-01-25 18:09 UTC
