### ISSUE TITLE
UI UX Problem with the default folder made me delete all my documents

### ISSUE THREAD

**Issue by 4Robato** [godotengine/godot#74874] opened 2023-03-13 18:36 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

This is an UX problem and not a bug itself. The issue I had is that I **got my entire Documents folder deleted** (where I had a lot of personal files) with a few clicks. It's not that Godot doesn't warn you but it's that is not the expected behavior and I think it's quite important that even if not a bug, it can really be awful for the user.

The issue is that when creating a project, or in my case, downloading an Asset Library Project, the default folder is Documents. I just discovered that tab the other day and saw some interesting projects I wanted to quickly check out. Then I press download and then 'install and edit'. The project didn't seem to open properly (after the disaster I understood it was because in my documents folder I had a lot of files) and then I decided to quit the project since I thought it was broken or corrupted. Then I selected the project and let Godot delete the files since I thought Godot knows what it installed.

The problem was that the default folder is always set to Documents (this wasn't my first download and I knew how it worked I just forgot that time) and pressing quickly two button simply deleted a lot of important documents and I just spended a tooon of time trying to recuperate them and I'm not sure I'll be able to. I know it is a user mistake at the end and maybe I should have been more careful but I think the default behavior should simply create a folder with the name of the project to avoid this kind of situations.

I'm surprised if I'm the only person who had this problem and a lot of messy things can happen.

### Steps to reproduce

Just create a project or download an Asset Library Project and see that the default path is Documents and not a new folder with the name of the project.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-03-13 18:38
Real life example of why #74678 is HIGH PRIORITY

**Comment by Calinou** [comment] 2023-03-13 19:11
Duplicate of https://github.com/godotengine/godot/issues/74678 (same cause).

**Closed by Calinou** 2023-03-13 19:11 UTC
