### ISSUE TITLE
Camera3D cannot be selected by clicking the gizmo

### ISSUE THREAD

**Issue by stijn-h** [godotengine/godot#64289] opened 2022-08-11 18:44 UTC
### Godot version

4.0-alpha14

### System information

W10

### Issue description

Camera3D can't be selected by clicking on the gizmo. I would expect it to have some clickable bounding box for use in editor.

![image](https://user-images.githubusercontent.com/25907608/184215440-7852f09c-c397-4fb6-a6a0-b6369c1343ce.png)

### Steps to reproduce

1. Add Camera3D node to scene, as root or anything else. 
2. Try to select it by clicking the gizmo, or region select.

**Comment by Calinou** [comment] 2022-08-11 19:42
Duplicate of https://github.com/godotengine/godot/issues/53083.

**Closed by Calinou** 2022-08-11 19:42 UTC
