### ISSUE TITLE
Renaming files in the FileSystem should edit the path of preload("path") inside all scripts.

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#57828] opened 2022-02-08 22:48 UTC
### Godot version

3.4.2

### System information

Linux

### Issue description

Renaming files in the FileSystem should edit the path of preload("path") inside all scripts (The path is a compile time const).

### Steps to reproduce

Create `art1.png` and `art2.png`.
Create a Sprite in your Main Scene and set its Texture to the `art1.png` file.
Attach a script to the Sprite.
In the script add `const art = preload("res://art2.png")`
Play your project and notice no errors.
In the FileSystem rename `art1.png` to `heart1.png`
In the FileSystem rename `art2.png` to `heart2.png`
Play your project and notice that the texture path was updated to the new file name but the script's "const" preload path was not.
preload's path is a compile time const that should be updated on renames.

**Comment by Calinou** [comment] 2022-02-08 22:59
Duplicate of https://github.com/godotengine/godot-proposals/issues/899. Implementing this feature essentially requires refactor tooling to safely modify scripts in an automated manner.

**Closed by Calinou** 2022-02-08 22:59 UTC
