### ISSUE TITLE
Unavailable debugger with multiple game instance

### ISSUE THREAD

**Issue by scorsi** [godotengine/godot#24010] opened 2018-11-27 11:51 UTC
**Godot version:**
3.0

**OS/device including version:**
MacBook Pro 13-inch 2017 (10.14.1 Mojave)

**Issue description:**
Unable to debug with two instance of godot: client and server. Which is very very very useful when creating networking multiplayer game.
This is a known issue since 2016 but may be forgotten: [Godot QA](https://godotengine.org/qa/6261/multiple-game-instances).

In one editor, we can't open more than one game.
If we run two editors, the last game window opened can't connect to the godot debugger.
(For those who don't know how to run multiple instance of a programme in Mac: `open -n -a <program in apps or .app file>`)

There is an error message in the last editor which launch the game: `Error listening on port 6007`.
May be the problem is due to the listening port which is the same for all godot editor instance/window.
Could you think is it possible to start an available port discovery to start the godot debugger and game with the same available port, we could so run multiple game instance for client/server ?

**Comment by Chaosus** [comment] 2019-04-18 06:30
Yeah, seems like a duplicate of #20020. Closed.

**Closed by Chaosus** 2019-04-18 06:30 UTC
