### ISSUE TITLE
Creating AudioStreamPlayer node creates AudioStreamPlayer2D node instead

### ISSUE THREAD

**Issue by HoratioZEDU** [godotengine/godot#18414] opened 2018-04-25 10:41 UTC
**Godot version:** Godot 3.0.2 stable(downloaded via Steam)

**OS/device including version:** Debian Linux 9 x86_64

**Issue description:** When creating a new AudioStreamPlayer node as a child of a Node2D(maybe for other nodes that extend Node2D, I can't check right now), it sometimes creates the node as an AudioStreamPlayer2D. I think this only happens when adding from the "Recently Added" list to the bottom left of the "Add Node" menu. 

**Steps to reproduce:** Create a Node2D in a new scene, and add a new AudioStreamPlayer node. Delete that node and add it again from the "Recently Added" list in the bottom left of the menu.

**Comment by vnen** [comment] 2018-04-25 14:57
Duplicate of #16789.

**Closed by vnen** 2018-04-25 14:57 UTC
