### ISSUE TITLE
TCP_Server opens 2 connections

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#34152] opened 2019-12-06 18:46 UTC
**Godot version:**
Tried Beta 1, Beta 3, Stable 1.1
**OS/device including version:**
Windows 10 1903
**Issue description:**
I am trying 
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment] 2019-12-06 18:52
Duplicate of #34151

**Closed by groud** 2019-12-06 18:52 UTC
