### ISSUE TITLE
Cyclic Resource referral crashes Godot

### ISSUE THREAD

**Issue by Megaguy32** [godotengine/godot#39547] opened 2020-06-14 21:38 UTC
- Cyclic resource referral causes Godot to crash
- Resources don't reflect their .tres files
- When using arrays, element of exported array in Resource appears as [empty] 

**Godot version:**
v3.2.1.stable.flathub

**OS/device including version:**
Linux Mint 19.3
Fujitsu Lifebook AH530

**Issue description:**

I am working with resources and am having a bad time. I made a related issue recently, but this is a new issue.
I have a project where I have a custom resource class.
These resources have dependencies of other resources, sometimes these dependencies are cyclic.
I used an exported variable of type Resource to represent the dependencies.
And when I drag and drop the resources, the moment it becomes cyclic, Godot crashes.

And when I reopened Godot, in the Resource editor the resource I dragged and dropped appears [empty], but the .tres file shows the resources defined.

If I use arrays of Resources, then Godot Godot doesn't crash, but when I close and reopen Godot the one of the elements appears [empty]

**Steps to reproduce:**
there are two resources A and B, and an exported property called dependee.
in A, drag and drop B into dependee
in B, drag and drop A into dependee
and viola 

**Minimal reproduction project:**

[Cyclic Resource Referal.zip](https://github.com/godotengine/godot/files/4777244/Cyclic.Resource.Referal.zip)

**Comment by Calinou** [comment] 2021-03-29 16:59
Duplicate of https://github.com/godotengine/godot/issues/41111.

**Closed by Calinou** 2021-03-29 16:59 UTC
Labels: bug, crash, topic:editor
