### ISSUE TITLE
Select (Property/method/..) Description is hidden

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#26120] opened 2019-02-21 13:26 UTC
**Godot version:**
beta 5

**OS/device including version:**
win 10 64bit

**Issue description:**
When you want to set a property or function the description is hidden.

![image](https://user-images.githubusercontent.com/41632592/53171968-1c933f00-35dc-11e9-8e00-50a96578e7a4.png)

![image](https://user-images.githubusercontent.com/41632592/53171989-287f0100-35dc-11e9-8004-811a0e82710a.png)

**Comment by akien-mga** [comment] 2019-02-21 13:30
Duplicate of #25820, fixed in the master branch.

**Closed by akien-mga** 2019-02-21 13:30 UTC
Labels: bug, topic:editor
