### ISSUE TITLE
GPU Particles Throwing Engine Error

### ISSUE THREAD

**Issue by bozoVuksan** [godotengine/godot#66392] opened 2022-09-25 10:35 UTC
### Godot version

4.0 Beta

### System information

Windows 10,NVIDIA GeForce GTX 960M,Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz, 2901 Mhz, 2 Core(s), 4 Logical Processor(s)

### Issue description

When using a GPUParticle and adding a Mesh to Draw Pass the console starts throwing following Error.
servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:1291 - Condition "!multimesh" is true.

### Steps to reproduce

Created a 3D Scene
Added GPUParticle
Added Process Material in GPUPartcile
Added new Box Mesh to Draw Pass.
Console starts throwing following Error: servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:1291 - Condition "!multimesh" is true.
Performance gets impacted

**Comment by Zireael07** [comment] 2022-09-25 11:59
confirming

**Comment by akien-mga** [comment] 2022-09-25 12:31
Duplicate of https://github.com/godotengine/godot/issues/65888

**Closed by akien-mga** 2022-09-25 12:31 UTC
