### ISSUE TITLE
Typed array methods return Variant

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#63892] opened 2022-08-04 00:02 UTC
### Godot version

ea4b8de

### System information

Windows 10 x64

### Issue description

```GDScript
var arr: Array[int]
var v := arr[0] # works
var v2 := arr.front() # Could not infer the type of the variable "v2" because the initial value is a variant.
```
I'd expect the `front()` to correctly return `int`.

### Steps to reproduce

1. Add typed array
2. Try infer return value of any method that returns an element

**Comment by akien-mga** [comment] 2022-08-04 07:14
Related to https://github.com/godotengine/godot/pull/62709#issuecomment-1173929054

I don't know if that's fixable given that TypedArrays are still normal Variant arrays internally. Maybe with more specific handling for their hint in GDScript.

**Comment by amoriqbal** [comment] 2022-10-09 12:39
Two possible ideas to fix this:
1. Treat arrays as Objects. Array[int] and Array[float] should then be objects of two different autogenerated classes (say e.g. _GD_TypedArray_1 and _GD_TypedArray_2).
2. Change the definition of Variant::Type from enum to a class. Then we can keep member variables to keep track of other details like type of elements of array. We can also use operator overloading to enable something like arr1.type == arr2.type.

**Comment by kleonc** [comment] 2022-10-26 12:05
Duplicate of #59721.

**Closed by kleonc** 2022-10-26 12:05 UTC
Labels: bug, topic:core, topic:gdscript
