### ISSUE TITLE
Navigation2D calculating deformed paths with small vertex values

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#7224] opened 2016-12-01 17:44 UTC
**Operating system or device - Godot version:**
Ubuntu 14.04 64bit
Godot 2.1.1 stable

**Issue description** (what happened, and what was expected):
When using Navigation2D with polygons whose vertices have values from 0.0 to 20.0, the calculated path is wrong. Tries to go through obstacle polygons.

**Steps to reproduce:**
Run the example project. It generates a new path every 3 seconds.

To experiment, increase the variable "navPolyStretch" by 10 or by 100, and also the start and end point of the path. You will see, the path is suddenly calculated perfectly.

**Link to minimal example project** (optional but very welcome):
[Test Scene Navigation2D with drawn Polys.zip](https://github.com/godotengine/godot/files/625364/Test.Scene.Navigation2D.with.drawn.Polys.zip)

**Comment by Noshyaar** [comment] 2018-04-08 03:48
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 14:13
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2019-04-15 14:13 UTC
Labels: bug, topic:core
