### ISSUE TITLE
'Drag and Drop' and 'Clear' are not functional in Cubemap creation.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6189] opened 2016-08-17 22:19 UTC
**Operating system or device - Godot version:**
Windows 10 - Godot 2.1

**Issue description** (what happened, and what was expected):
When creating a Cubemap resource, you can not drag and drop textures onto the appropriate slot in the editor. It seems that trying to clear the texture slot does not work properly either.

**Steps to reproduce:**
Create a WorldEnvironment Node **->** Create a new Environment **->** Create a new Cubemap in said Environment **->**  Attempt to drag textures onto appropriate 'Side' slots **->** Fail miserably **->** Sigh deeply as you now have to spend 20 precious seconds of your life manually loading the six textures.

**Comment by bojidar-bg** [comment] 2016-08-18 05:30
Aww, yet another CubeMap resource editor bug

**Comment by AfterRebelion** [comment] 2018-12-04 18:53
Confirmed on Godot 2.1.5.
![2018-12-04 19_47_05-godot engine - testing - node2d tscn _](https://user-images.githubusercontent.com/559819/49465265-79f9ca00-f7fd-11e8-8d31-fe777f366407.png)

Since i didn't know how to create a cubemap (As far as I know, they aren't supported anymore) on Godot 3.0, I used 3.1 alpha 2 to create the resource, since it is still avaliable, and it works as it should:
![imagen](https://user-images.githubusercontent.com/559819/49465443-f12f5e00-f7fd-11e8-996b-0be68b0dedfa.png)
But yeah, it isn't really useful there...

**Comment by akien-mga** [comment] 2018-12-04 20:01
Thanks, closing as "fixed" in 3.0 since CubeMap is no more.

**Closed by akien-mga** 2018-12-04 20:01 UTC
Labels: bug, topic:editor, usability
