### ISSUE TITLE
Vulkan: Enabling SS Reflections in Environment causes artifacts

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45297] opened 2021-01-18 22:44 UTC
**Godot version:**
[7fc9d4c](https://github.com/godotengine/godot/commit/7fc9d4c79b3b790ff75c32317c25410f58ed1f68)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Enabling SS Reflections in Environment causes artifacts in editor viewport.
Also these errors are getting spammed in console:
<details>
<summary>Error:</summary>

>ERROR: Attempted to use an unused shader variant (shader is null),
   at: (./servers/rendering/renderer_rd/pipeline_cache_rd.h:70)
ERROR: Condition "!pipeline" is true.
   at: draw_list_bind_render_pipeline (drivers\vulkan\rendering_device_vulkan.cpp:6112)
ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6305)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (./servers/rendering/renderer_rd/pipeline_cache_rd.h:70)
ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6305)
ERROR: Source and Destination textures must be the same format.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:2805)
ERROR: Uniforms supplied for set (3):
Set: 1 Binding: 0 Type: CombinedSampler Length: 1
Set: 1 Binding: 1 Type: CombinedSampler Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: Image Length: 1
Set: 0 Binding: 1 Type: Image Length: 1
Set: 1 Binding: 0 Type: Image Length: 1
Set: 1 Binding: 1 Type: Image Length: 1
Set: 2 Binding: 0 Type: Image Length: 1
Set: 3 Binding: 0 Type: CombinedSampler Length: 1
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6755)

</details>

[Video](https://drive.google.com/file/d/14kbgkizFya4MQn9ebmCd_41fQK1eemLv/view?usp=sharing)

**Steps to reproduce:**
Enable SS Reflections in Environment in WorldEnvironment node.

**Minimal reproduction project:**
[SSRTest.zip](https://github.com/godotengine/godot/files/5832653/SSRTest.zip)

**Comment by clayjohn** [comment] 2021-01-18 23:24
Duplicate of https://github.com/godotengine/godot/issues/40779

Can you please post the above information as a response to that issue so that it is all tracked in one place?

**Closed by clayjohn** 2021-01-18 23:24 UTC

**Comment by Xartorx** [comment] 2021-01-18 23:28
Oh, sorry, didn't find that issue when i was searching.
Will re-post there.

**Comment by clayjohn** [comment] 2021-01-19 00:06
Thanks!
