### ISSUE TITLE
X11: VSync not working unless it's activated in code

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#25399] opened 2019-01-28 03:21 UTC
This issue might be related to #25377
**Godot version:**
3.1 beta 3

**OS/device including version:**
OS: MX Linux 17(based on Debian 9)
GPU: Intel HD Graphics 

**Issue description:**
VSync only seems to work when activated from code. This doesn't happen on windows.

**Steps to reproduce:**
Activate VSync from the editor in any project and the option will be ignored.

**Comment by groud** [comment] 2019-01-28 14:43
Likely duplicate of  #25377

**Comment by ForLoveOfCats** [comment] 2019-02-18 12:31
I can confirm that vsync is still not working with 3.1 Beta 5 (mono build but I don't think that is very relevant but needed mentioning) I am running a Radeon R7 360 with the RadeonSi (amdgpu) Mesa drivers (Mesa version is 18.3.2)


This project has vsync enabled and prints the fps to the console. 
[vsync.zip](https://github.com/godotengine/godot/files/2875569/vsync.zip)
![image](https://user-images.githubusercontent.com/30666851/52951229-3b30d600-334f-11e9-8aaa-2d5ecaf39bb0.png)

**Comment by akien-mga** [comment] 2019-02-18 12:37
Does vsync work otherwise on your system, e.g. running `glxgears`?

**Comment by ForLoveOfCats** [comment] 2019-02-18 13:00
glxgears is not running with vsync 
![image](https://user-images.githubusercontent.com/30666851/52952572-f3ac4900-3352-11e9-9379-ca306eb67c12.png)

However I cannot tell if it is even trying to sync with the vblank
![image](https://user-images.githubusercontent.com/30666851/52952596-045cbf00-3353-11e9-8fb6-73a66458bcb6.png)
![image](https://user-images.githubusercontent.com/30666851/52952632-26eed800-3353-11e9-8b92-416832b0195a.png)

I'll go check some gl based games and see if vsync works in them on this rig.

**Comment by ForLoveOfCats** [comment] 2019-02-18 13:08
I just tested an when running TF2 with vsync enabled the fps still exceeds my monitor's refresh rate by a great deal. Very odd....

**Comment by MightyPrinny** [comment] 2019-02-18 17:14
I think this was a system issue, I added 
<application name="Godot">
    <option name="vblank_mode" value="-1"/>
</application>
to my .drirc and the issue  was fixed, I don't know if anything related to vsync changed from beta 3 to beta 5 but I can't replicate the issue anymore even if I remove this from my .drirc

**Closed** 2019-02-18 17:15 UTC
Labels: bug, topic:rendering
