### ISSUE TITLE
TextEdit's C# AddColorRegion and AddKeywordColor Dont Work 

### ISSUE THREAD

**Issue by Airbus5717** [godotengine/godot#41791] opened 2020-09-05 16:23 UTC
Godot version 3.2
GLES2
Windows 10 version 2004
```csharp
using Godot;
using System;

public class TextEditor : TextEdit
{
    string hello = "var";
    public override void _Ready()
    {
       //testing 
        AddColorRegion(hello, ";", Colors.blue ,false);
    }


}
````

**Comment by Calinou** [comment] 2020-09-05 18:39
Duplicate of https://github.com/godotengine/godot-proposals/issues/1420.

**Closed by Calinou** 2020-09-05 18:39 UTC
