### ISSUE TITLE
Connecting signal does not create function when using external editor

### ISSUE THREAD

**Issue by zacryol** [godotengine/godot#36459] opened 2020-02-22 18:15 UTC
**Godot version:** 3.2

**OS/device including version:** Solus Linux, Windows 10

**Issue description:** When an external editor (in this instance, VSCode) is enabled and configured, connecting a signal via the Godot editor does not create the target function

**Steps to reproduce:**

- Create new Godot project
- Add one or more nodes, at least one capable of emitting a signal (tested: Button and Area2D)
- If you haven't yet, configure and enable external code editor (In my case, it is VSCode, with the godot-tools plugin)
- Create a new script on a node. This should open the project and new script in VSCode
- Back in Godot, select emitting node, connect to node with script.
- Window focus goes back to vscode, but the function is not created.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/4239743/bug.zip)
Since it's more procedure-based than setup-based, it's a bit hard to convey with just a project, but I've attached a project where I tested this. You can see that there are multiple signals connected, but none of the functions are in the .gd script file.

**Comment by zacryol** [comment] 2020-02-22 18:19
Seems similar to issue [#21695](https://github.com/godotengine/godot/issues/21695), though it was described differently.

**Comment by zacryol** [comment] 2020-02-22 18:36
> Seems similar to issue [#21695](https://github.com/godotengine/godot/issues/21695), though it was described differently.

I didn't mean that this is a duplicate issue. That one was described as a C# issue; this is an "External Editor" issue. Just saying that maybe the root cause between them is similar.

**Comment by brentbartlett** [comment] 2020-02-24 01:53
I believe this is duplicate to 23208.

**Comment by akien-mga** [comment] 2020-02-24 07:12
Indeed, duplicate of #23208.

**Closed by akien-mga** 2020-02-24 07:12 UTC
