### ISSUE TITLE
The mouse wheel does not work

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#6953] opened 2016-10-28 16:47 UTC
**Operating system or device - Godot version:**
Ubuntu 16.04 - Godot 2.1

**Issue description** (what happened, and what was expected):
```
    if Input.is_action_pressed('ui_wheel_up') or Input.is_action_pressed('ui_wheel_down'):
        print('pressed')
```
no print

**Steps to reproduce:**
Add to Project settings/Input map the Mouse wheel ('ui_wheel_up' or 'ui_wheel_down')

**Comment by bojidar-bg** [comment] 2016-10-28 17:08
Two things,
1. Duplicate of #3340, and thus not a bug (nor a feature)
2. Master branch has `is_action_just_pressed` which is useful for such fast events.

In short - mouse wheel event are so short in duration, that they can be sensed only in `_process_input`.

**Comment by neikeq** [comment] 2016-10-30 14:33
Closing for the reasons above.

**Closed by neikeq** 2016-10-30 14:33 UTC
