### ISSUE TITLE
Terrible performance on .NET when having several scripted nodes on the scene

### ISSUE THREAD

**Issue by Asaduji** [godotengine/godot#98175] opened 2024-10-14 15:15 UTC
### Tested versions

- Reproducible in v4.3.stable.mono.official.77dcf97d8

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6590) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

I was getting some terrible performance on my project after adding a C# script to a node that was instantiated around 4000 times, while that sounds like a lot individually the nodes weren't processing anything crazy so I started profiling the issue and found out the problem was indeed adding the `_Process` method to the script that was created 4000 times.

### Steps to reproduce

I didn't take a look at the internals but looks like it's using reflection or something similar to find the `_Process` method on every script and that is extremely slow, here is a comparison:

Here is the script of the main node of the main scene:

```cs
using Godot;
using System.Collections.Generic;

public partial class NodeManager : Node
{
	[Export]
	public PackedScene NodeScene;

	private readonly List<NodeScript> _nodes = new();

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		DisplayServer.WindowSetVsyncMode(DisplayServer.VSyncMode.Disabled);

		for (var i = 0; i < 5000; i++)
		{
			var node = (NodeScript)NodeScene.Instantiate();

			 _nodes.Add(node);

			AddChild(node);
		}
	}
}
```

It just creates 5000 nodes and adds them as a child, each node has the following `NodeScript` script:

```cs
using Godot;

public partial class NodeScript : Node
{
	private double _timer = 0;
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
	}

	
	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
		HandleTimer(delta);
	}	

	private void HandleTimer(double delta)
	{
		if (_timer >= 1.0d)
		{
			_timer = 0.0d;

			GD.Print("Hello");
		}

		 _timer += delta;
	}
}
```

As you can see individually each node isn't doing much, you can remove the console print if you want, it won't affect the performance in a noticeable way.

Here's the issue though, we're getting 200 FPS on a completely empty scene with no rendering happening at all on a Ryzen 9 7950X3D
![image](https://github.com/user-attachments/assets/9ed08fea-2f3d-47f8-8b40-459d4b504901)

On a project with more going on, I was getting around 50-40 fps, can't imagine how bad it would be on a less powerful machine.

However, if instead we remove the `_Process` method from `NodeScript`, create our own `OnProcess` method and call it inside a for loop in the `_Process` method of the script of the root node (can be any node really) the difference is pretty big:

```cs
using Godot;
using System.Collections.Generic;

public partial class NodeManager : Node
{
	[Export]
	public PackedScene NodeScene;

	private readonly List<NodeScript> _nodes = new();

	 // Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		DisplayServer.WindowSetVsyncMode(DisplayServer.VSyncMode.Disabled);

		for (var i = 0; i < 5000; i++)
		{
			var node = (NodeScript)NodeScene.Instantiate();

			 _nodes.Add(node);

			AddChild(node);
		}
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
        	foreach (var node in _nodes)
        	{
            		node.OnProcess(delta);
        	}
	}
}
```

```cs

using Godot;

public partial class NodeScript : Node
{
	private double _timer = 0;
	// Called when the node enters the scene tree for the first time.
	 public override void _Ready()
	{
	}

	
	// Called every frame. 'delta' is the elapsed time since the previous frame.
	//public override void _Process(double delta)
	//{
	//	HandleTimer(delta);
	//}
	

	public void OnProcess(double delta)
	{
		HandleTimer(delta);
	}

	private void HandleTimer(double delta)
	{
		if (_timer >= 1.0d)
		{
			_timer = 0.0d;

			GD.Print("Hello");
		}

		_timer += delta;
	}
}
```

Our game is suddenly running at 2800 FPS

![image](https://github.com/user-attachments/assets/599ef381-a7f8-4aa6-9927-2bb73e629f11)

We're seeing a x14 improvement here and this isn't happening just in a synthetic test like this one, it's happening on any project with many C# scripted nodes running on the scene.

I don't know how this is internally implemented but I will guess every `_Process` function gets called from native for every node and does some kind of reflection to find either the function or the node itself, as the profiler said most of the CPU time is spent doing comparisons between `StringName` types: 
![image](https://github.com/user-attachments/assets/140e8c0d-2400-4320-817e-71c2fb25f9ee)
93% of CPU time comes from this:
![image](https://github.com/user-attachments/assets/aa3cf400-fdb4-4d31-a701-86da8e36763e)
So I will guess it is really using `InvokeGodotClassMethod` to find the method by name using reflection.

Wouldn't be possible to instead make a single call to .net that just updates all nodes the same way I just did in the example?

Also please note this happens in .net 6, .net 7 and .net 8

### Minimal reproduction project (MRP)

[dotnet-performance-test.zip](https://github.com/user-attachments/files/17365904/dotnet-performance-test.zip)

**Comment by YYF233333** [comment] 2024-10-15 11:38
Port the MRP to GDScript and got simillar results.

[process-performance-test.zip](https://github.com/user-attachments/files/17377102/process-performance-test.zip)

|  | GDScript | C# |
|--------|--------|--------|
| Using _process | about 160 fps | 100~110 fps |
| Using custom loop | about 180 fps | about 2500 fps |

the overhead exists in both side but for GDS it isn't so serious because gdscript runs quite slow ( compared to C# ), removing these calls imporve little performance. But in C# side it become the main part ( if you do little work each call ).

AFAIK communicating with godot runtime that often from C# is not recommanded, so either remove these calls or do some heavier work in the call. They don't batch these calls may because you can have a mixture scene with half gds nodes and half c# nodes, you have to call `_process` one by one because you can't know beforehand whether it is gds or C#.

**Comment by conde2** [comment] 2024-10-15 12:27
I can confirm this, the idea of moving this loop to C# seems very promising. The performance gains can't be ignored.

**Comment by Asaduji** [comment] 2024-10-15 12:32
> Port the MRP to GDScript and got simillar results.
> 
> [process-performance-test.zip](https://github.com/user-attachments/files/17377102/process-performance-test.zip)
> 
> GDScript	C#
> Using _process	about 160 fps	100~110 fps
> Using custom loop	about 180 fps	about 2500 fps
> the overhead exists in both side but for GDS it isn't so serious because gdscript runs quite slow ( compared to C# ), removing these calls imporve little performance. But in C# side it become the main part ( if you do little work each call ).
> 
> AFAIK communicating with godot runtime that often from C# is not recommanded, so either remove these calls or do some heavier work in the call. They don't batch these calls may because you can have a mixture scene with half gds nodes and half c# nodes, you have to call `_process` one by one because you can't know beforehand whether it is gds or C#.

I think the main problem isn't just that it's getting called from managed for every object (although that ofc affects something), the main performance issue the profiler found is the way `_Process` method is found for the node object but I could be wrong ofc.

And while doing heavier work on the `_Process` call makes the results get closer, the difference is usually at least 2x the performance, exponentially increasing the more scripted nodes you have and the less work each node has to do, I just think this could be a good performance hit to fix.

Wouldn't it be possible from the .NET side to keep track of all managed node objects and call them in a batch that way?

**Comment by paulloz** [comment] 2024-10-15 19:31
Hello, and thank you for the detailed report. I am closing to consolidate the issue into #89217.

As explained in other issues describing the situation, a solution would be to re-write how `InvokeGodotClassMethod` works to use function pointers instead. Since we are currently working on the new C# bindings based on GDExtension (already using a different logic to call virtual methods), this is unlikely to change at the moment.

Note that #89826 goes in this direction too, but would need to be polished, and quite heavily tested, to be considered for merging. 

As for batching the calls in particular, I believe it'd be a much more convoluted way to solve this, and likely introduce other issues (e.g. how to order the calls, to name one). If you are however interested in manually batching numerous entities, you might want to read through godotengine/godot-proposals#2380.

**Closed by paulloz** 2024-10-15 19:31 UTC
Labels: needs testing, topic:dotnet, performance
