### ISSUE TITLE
Godot does not remember the configuration of the tilemap editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#52879] opened 2021-09-20 19:10 UTC
### Godot version

3.3.3 stable mono

### System information

w10 64

### Issue description

Godot does not remember anything about:

The zoom you set in the tile editor

![Sin título](https://user-images.githubusercontent.com/19652075/134060391-9332c06f-e7aa-449a-a472-edb6acbf2b30.png)

The size, even if you save the layout, the size will not be remembered.

![Captura](https://user-images.githubusercontent.com/19652075/134060419-1a03b7df-7b9c-4698-b41f-ed5b4679a5cb.PNG)

It is very annoying to have to be configuring these two things several times a day.
Hopefully someone will repair them soon, I would be tremendously grateful.

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2021-09-20 20:09
Duplicate of https://github.com/godotengine/godot/issues/22832.

**Closed by Calinou** 2021-09-20 20:09 UTC
