### ISSUE TITLE
TileMap/set light occluders break upon scene reload via code

### ISSUE THREAD

**Issue by ka0s420** [godotengine/godot#66882] opened 2022-10-04 14:21 UTC
### Godot version

4.0 beta 2

### System information

win 10

Intel i7-7700 cpu, nvidia gtx 1060 6gb gpu

### Issue description

Light occluders in tilemap change position or disappear when using 

`get_tree().reload_current_scene()`

In my own non minimal project the occluders change position in a way that bears no obvious relation to how they should be placed. In the minimal reproduction I made, they simply disappear from the screen ( i didnt implement camera movement to check if they're just off screen!)

before calling  reload current scene:

![light_ocluder_bug_pic1](https://user-images.githubusercontent.com/23391250/193843601-08e06e36-b15d-4557-8602-1a0be0f5526b.PNG)

After calling reload current scene:

![light_occluder_bug_pic2](https://user-images.githubusercontent.com/23391250/193843679-d59878d2-4962-424b-92b0-26c35ad557dc.PNG)

### Steps to reproduce

Place tiles with occluders into a scene with a light2d with shadows enabled. Create a way to call `get_tree().reload_scene()` (attach script to main node and call the function when detecting input. After this, the occluders should change position -  note however in the images that not all of the occluders moved. - note to better visualise their presence, add canvas modulate and set the colour to black so the shadows are visible.

### Minimal reproduction project

[minimal_Occluder_project.zip](https://github.com/godotengine/godot/files/9707715/minimal_Occluder_project.zip)

**Comment by ka0s420** [comment] 2022-10-04 14:50
@groud I'm not sure of the etiquette, so please forgive me, but I thought this might be in your field after you assigned the other tilemap issue.

**Comment by groud** [comment] 2022-10-04 17:18
It is my field, but this issue was already reported. Closing this one as a duplicate of https://github.com/godotengine/godot/issues/65572

**Closed by groud** 2022-10-04 17:18 UTC
