### ISSUE TITLE
Environment of the camera can't be loaded from disk

### ISSUE THREAD

**Issue by karolgotowala** [godotengine/godot#3220] opened 2016-01-03 17:48 UTC
Just like the title says if one saves environment of the camera to the disk it doesnt work, changed values doesnt do nothing on camera viewport environment only works by assigninig new via function "New Environment" on camera.

**Comment by kubecz3k** [comment] 2016-01-04 17:14
@karolgotowala seems like nasty bug indeed, as a temporary workaround if you are not using multiple cameras with different environments I would suggest to have one WorldEnvironment node in your root scene and environments of camera set to null. As far as I know in this case cameras will share this one environment.

**Comment by reduz** [comment] 2016-01-10 18:38
I can't reproduce...

**Comment by kubecz3k** [comment] 2016-01-11 09:46
Can't reproduce as well on 176afb2feb7ed235bf9d7528ee3e8af092f12f90 build. @karolgotowala What build are you using? How are you creating enviroment resource on the disc?

**Comment by akien-mga** [comment] 2016-06-18 19:03
No answer from the OP and two developers couldn't reproduce, so closing this issue as old. If you can still experience the bug, feel free to reopen or open a new issue with detailed steps to reproduce and ideally an example project that triggers the bug easily.

**Closed by akien-mga** 2016-06-18 19:03 UTC
Labels: bug, topic:core
