### ISSUE TITLE
is_hovered() not working properly on Android

### ISSUE THREAD

**Issue by abhiagnihotri01** [godotengine/godot#47433] opened 2021-03-28 06:42 UTC
**Godot version: 3.2.2 stable**

**OS/device including version: Android**

**Issue Description -** I have a TextureButton. First time when i click this button (button_down) and then button_up outside the TextureButton. Second time when i click the same button (button_down) and then button_up on the TextureButton, the is_hovered() function not getting called on this TextureButton. The is_hovered() should be called everytime when i do button_up on the Texture_Button.
But if i first time only click this button (button_down) and button_up on the TextureButton, the is_hovered() function getting called.
Same thing is working for Mac. Mac behaving as expected.

**Comment by Calinou** [comment] 2021-03-28 14:03
Duplicate of https://github.com/godotengine/godot/issues/20881 (same cause).

**Closed by Calinou** 2021-03-28 14:03 UTC
