### ISSUE TITLE
Can't export to windows 

### ISSUE THREAD

**Issue by draxdeveloper** [godotengine/godot#2238] opened 2015-07-08 14:20 UTC
All my windows exports are resulting in crashing.
The export to Linux is working,

**Comment by reduz** [comment] 2015-07-08 14:52
yeah users reported this, not sure why it happens though, help would be
appreciated

**Comment by draxdeveloper** [comment] 2015-07-08 14:55
yeah... there is any solution?

**Comment by kubecz3k** [comment] 2015-07-09 09:48
@draxdeveloper If you are asking about temporary solution... On my linux 64bit machine I can export to windows and game runs without any problems... Maybe try on virtual machine and see how it goes?

**Comment by akien-mga** [comment] 2015-11-11 10:24
Duplicate of #2189.

**Closed by akien-mga** 2015-11-11 10:24 UTC
Labels: archived
