### ISSUE TITLE
PopupMenu vseparation misaligns item hitboxes (fixed in `master`)

### ISSUE THREAD

**Issue by brianwinterpixel** [godotengine/godot#56455] opened 2022-01-03 03:06 UTC
### Godot version

3.4.2

### System information

W10, GLES3

### Issue description

When modifying a custom theme for PopupMenu, the VSeparation parameter can be useful for spacing out options, particularly for mobile. However, this misaligns the hitbox of all the items.

https://user-images.githubusercontent.com/95356449/147896833-a00b21bd-247c-440c-85d5-74d043b560b4.mp4

### Steps to reproduce

Add a custom theme to the project with a configuration for PopupMenu.
Set vseparation to 100.

Create an OptionButton or PopupMenu, add several items.

When hovering over the items with the mouse, notice how the wrong items are being highlighted.

### Minimal reproduction project

[project(1).zip](https://github.com/godotengine/godot/files/7800223/project.1.zip)

**Comment by jmb462** [comment] 2022-01-03 20:03
Seems that the problem is more the position of first and last item too close to the border than the hitbox, isn't it ?

In 4.0 it looks like that : 

![image](https://user-images.githubusercontent.com/3649998/147974770-c935fac8-257d-46f6-95f4-8691cd003c0f.png)

**Comment by akien-mga** [comment] 2022-01-12 15:47
Fixed by #56471.

**Closed by akien-mga** 2022-01-12 15:47 UTC
Labels: bug, topic:gui
