### ISSUE TITLE
Normal Map + Refraction causes shader bindings error spam

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#71881] opened 2023-01-22 21:01 UTC
### Godot version

Godot 4 Beta14

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Moving from b12 to b14 I now get repeating error spam without any clue as to where the problem is.

Bisect reveals:
[faea9f5c10abfc66284ea208d4f20eb03732a3bd] Remove SCREEN_TEXTURE, DEPTH_TEXTURE, and NORMAL_ROUGHNESS_TEXTURE
https://github.com/godotengine/godot/pull/70967

Narrowing it down, it is caused by a Standard material that has both Normal Map and Refraction enabled.

```
ERROR: All the shader bindings for the given set must be covered by the uniforms provided. Binding (6), set (3) was not provided.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5393)
ERROR: Condition "!us" is true.
   at: uniform_set_set_invalidation_callback (drivers/vulkan/rendering_device_vulkan.cpp:5833)
ERROR: Uniforms supplied for set (3):
Set: 3 Binding: 0 Type: UniformBuffer Writable: N Length: 144
Set: 3 Binding: 1 Type: Texture Writable: N Length: 1
Set: 3 Binding: 2 Type: Texture Writable: N Length: 1
Set: 3 Binding: 3 Type: Texture Writable: N Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 1 Type: Sampler Writable: N Length: 12
Set: 0 Binding: 2 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 3 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 4 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 5 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 8 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 9 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 10 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 11 Type: Texture Writable: N Length: 1
Set: 0 Binding: 12 Type: Texture Writable: N Length: 1
Set: 0 Binding: 13 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 14 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 15 Type: UniformBuffer Writable: N Length: 496
Set: 1 Binding: 0 Type: UniformBuffer Writable: N Length: 5632
Set: 1 Binding: 1 Type: UniformBuffer Writable: N Length: 144
Set: 1 Binding: 2 Type: StorageBuffer Writable: N Length: 0
Set: 1 Binding: 3 Type: Texture Writable: N Length: 1
Set: 1 Binding: 4 Type: Texture Writable: N Length: 1
Set: 1 Binding: 5 Type: Texture Writable: N Length: 1
Set: 1 Binding: 6 Type: Texture Writable: N Length: 1
Set: 1 Binding: 7 Type: Texture Writable: N Length: 8
Set: 1 Binding: 8 Type: Texture Writable: N Length: 8
Set: 1 Binding: 9 Type: StorageBuffer Writable: N Length: 0
Set: 1 Binding: 10 Type: Texture Writable: N Length: 1
Set: 1 Binding: 11 Type: Texture Writable: N Length: 1
Set: 1 Binding: 12 Type: Texture Writable: N Length: 1
Set: 1 Binding: 13 Type: Texture Writable: N Length: 1
Set: 1 Binding: 14 Type: Texture Writable: N Length: 1
Set: 1 Binding: 15 Type: Texture Writable: N Length: 1
Set: 1 Binding: 16 Type: Texture Writable: N Length: 1
Set: 1 Binding: 17 Type: Texture Writable: N Length: 1
Set: 1 Binding: 18 Type: UniformBuffer Writable: N Length: 896
Set: 1 Binding: 19 Type: Texture Writable: N Length: 1
Set: 1 Binding: 20 Type: Texture Writable: N Length: 1
Set: 2 Binding: 0 Type: StorageBuffer Writable: N Length: 0
Set: 3 Binding: 0 Type: UniformBuffer Writable: N Length: 160
Set: 3 Binding: 1 Type: Texture Writable: N Length: 1
Set: 3 Binding: 2 Type: Texture Writable: N Length: 1
Set: 3 Binding: 3 Type: Texture Writable: N Length: 1
Set: 3 Binding: 4 Type: Texture Writable: N Length: 1
Set: 3 Binding: 6 Type: Texture Writable: N Length: 1
   at: (drivers/vulkan/rendering_device_vulkan.cpp:7347)
ERROR: Uniforms supplied for set (3):
Set: 3 Binding: 0 Type: UniformBuffer Writable: N Length: 144
Set: 3 Binding: 1 Type: Texture Writable: N Length: 1
Set: 3 Binding: 2 Type: Texture Writable: N Length: 1
Set: 3 Binding: 3 Type: Texture Writable: N Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 1 Type: Sampler Writable: N Length: 12
Set: 0 Binding: 2 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 3 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 4 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 5 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 8 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 9 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 10 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 11 Type: Texture Writable: N Length: 1
Set: 0 Binding: 12 Type: Texture Writable: N Length: 1
Set: 0 Binding: 13 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 14 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 15 Type: UniformBuffer Writable: N Length: 496
Set: 1 Binding: 0 Type: UniformBuffer Writable: N Length: 5632
Set: 1 Binding: 1 Type: UniformBuffer Writable: N Length: 144
Set: 1 Binding: 2 Type: StorageBuffer Writable: N Length: 0
Set: 1 Binding: 3 Type: Texture Writable: N Length: 1
Set: 1 Binding: 4 Type: Texture Writable: N Length: 1
Set: 1 Binding: 5 Type: Texture Writable: N Length: 1
Set: 1 Binding: 6 Type: Texture Writable: N Length: 1
Set: 1 Binding: 7 Type: Texture Writable: N Length: 8
Set: 1 Binding: 8 Type: Texture Writable: N Length: 8
Set: 1 Binding: 9 Type: StorageBuffer Writable: N Length: 0
Set: 1 Binding: 10 Type: Texture Writable: N Length: 1
Set: 1 Binding: 11 Type: Texture Writable: N Length: 1
Set: 1 Binding: 12 Type: Texture Writable: N Length: 1
Set: 1 Binding: 13 Type: Texture Writable: N Length: 1
Set: 1 Binding: 14 Type: Texture Writable: N Length: 1
Set: 1 Binding: 15 Type: Texture Writable: N Length: 1
Set: 1 Binding: 16 Type: Texture Writable: N Length: 1
Set: 1 Binding: 17 Type: Texture Writable: N Length: 1
Set: 1 Binding: 18 Type: UniformBuffer Writable: N Length: 896
Set: 1 Binding: 19 Type: Texture Writable: N Length: 1
Set: 1 Binding: 20 Type: Texture Writable: N Length: 1
Set: 2 Binding: 0 Type: StorageBuffer Writable: N Length: 0
Set: 3 Binding: 0 Type: UniformBuffer Writable: N Length: 160
Set: 3 Binding: 1 Type: Texture Writable: N Length: 1
Set: 3 Binding: 2 Type: Texture Writable: N Length: 1
Set: 3 Binding: 3 Type: Texture Writable: N Length: 1
Set: 3 Binding: 4 Type: Texture Writable: N Length: 1
Set: 3 Binding: 6 Type: Texture Writable: N Length: 1
   at: (drivers/vulkan/rendering_device_vulkan.cpp:7347)
```

### Steps to reproduce

* Make a meshinstance and box shape in the scene tree
* Make a Standard material
* Enable Normal Map and Refraction

### Minimal reproduction project

n/a

**Comment by clayjohn** [comment] 2023-01-22 22:31
this issue is a duplicate of #71739 which was fixed by #71764

**Closed by clayjohn** 2023-01-22 22:31 UTC
Labels: bug, topic:rendering, regression
