### ISSUE TITLE
Vulkan problem in 4.0 alpha 1

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#57170] opened 2022-01-25 00:07 UTC
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

w10 64 Radeon vega 8

### Issue description

When I run godot and also when I run some scene, it takes considerably longer than the 3.x versions.
This message appears when running any scene, even empty.
![Captura2](https://user-images.githubusercontent.com/19652075/150885994-9b5e6b74-98cd-45fb-a64a-2c7c3fcc00fb.PNG)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2022-01-25 00:14
The editor will take longer to start the first time because shaders haven't been cached yet: https://github.com/godotengine/godot-proposals/issues/3657

As for the error message, this is a duplicate of https://github.com/godotengine/godot/issues/45725.

**Closed by Calinou** 2022-01-25 00:14 UTC

**Comment by Torguen** [comment] 2022-01-25 08:15
Ok the installation of thi:
https://sdk.lunarg.com/sdk/download/1.2.198.1/windows/VulkanRT-1.2.198.1-Installer.exe
Has solved the problem
