### ISSUE TITLE
Tab container items overflow while resizing and then switching to another tab

### ISSUE THREAD

**Issue by ankitpriyarup** [godotengine/godot#25346] opened 2019-01-26 15:45 UTC
**OS/device including version:**
Xubuntu 18.04

**Issue description:**
Tab container items overflow while resizing and then switching to another tab. It happens on the project settings window.

**Steps to reproduce:**
1) Open project settings window and switch to some other tab say AutoLoad
2) Resize the window to a smaller version
3) Now go the General tab

All items of the General tab will be overflowing
![screenshot from 2019-01-26 21-15-12](https://user-images.githubusercontent.com/31309984/51789523-82440500-21af-11e9-9eac-8afab08293b3.png)

**Comment by akien-mga** [comment] 2019-01-26 19:38
Duplicate of #21404.

**Closed by akien-mga** 2019-01-26 19:38 UTC
