### ISSUE TITLE
Material viewport on import window do not change when using external material

### ISSUE THREAD

**Issue by loafbrr** [godotengine/godot#72578] opened 2023-02-02 09:01 UTC
### Godot version

4.0 beta 17

### System information

windows 10,vulkan, amd radeon graphics

### Issue description

![2023-02-02_16-57](https://user-images.githubusercontent.com/31808683/216277734-831a9f45-1edf-4d07-827d-873c732763f4.png)

material preview on the window only works with the material set on the gltf file and does not change when you switch to an external material

### Steps to reproduce

import a gltf object with a material, go to material tab of advanced import setting window, pick the material, tick enabled and set path to the external material

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment] 2023-02-28 03:54
Duplicate of https://github.com/godotengine/godot/issues/64974

**Closed by clayjohn** 2023-02-28 03:54 UTC
