### ISSUE TITLE
Sprite's normals flipped on Y-axis in 2D mode

### ISSUE THREAD

**Issue by greygraphics** [godotengine/godot#39190] opened 2020-05-31 12:37 UTC
**Godot version:**
v3.2.1

**OS/device including version:**

I am using a 2020 MacBook with Intel Iris Plus Graphics and Mac OS 10.15.5 Catalina. I have selected GLES3 as backend.

**Issue description:**

The normal map for my sprite is behaving as if the y-axis is flipped, but the texture is right side up (notice the slit at the top of the sprite). In 3D, the normals behave correctly.

**Steps to reproduce:**
Use a normal map designed for a 3D mesh on a sprite.
![godot-normal-maps](https://user-images.githubusercontent.com/26239210/83352511-388f9f80-a34c-11ea-96df-0d918d191848.gif)

**Minimal reproduction project:**

[MicroConsole.zip](https://github.com/godotengine/godot/files/4707642/MicroConsole.zip)

**Comment by Calinou** [comment] 2020-05-31 12:47
Duplicate of #18299.

**Closed by Calinou** 2020-05-31 12:47 UTC
