### ISSUE TITLE
GPU Particles look different from 4.1.1 to 4.2

### ISSUE THREAD

**Issue by jbromberg** [godotengine/godot#83850] opened 2023-10-23 16:22 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.5.0 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

We use particles extensively throughout our project and after upgrading to 4.2 and running the project I noticed the particles all look different. It seems it may be something to do with the normal map and/or the opacity of the particles. The screenshots below illustrate the visual differences.
<img width="590" alt="Screenshot 2023-10-23 at 12 16 22 PM" src="https://github.com/godotengine/godot/assets/58891459/44528e9e-a79b-4e5e-95f6-11d674167af1">
<img width="550" alt="Screenshot 2023-10-23 at 12 15 53 PM" src="https://github.com/godotengine/godot/assets/58891459/565ca54a-845d-44a3-b883-425483fbcf95">

### Steps to reproduce

Run both repro projects in their respective versions of Godot to see the difference between the appearance of the particles.

### Minimal reproduction project

[particle-bug-4.1.1.zip](https://github.com/godotengine/godot/files/13073293/particle-bug-4.1.1.zip)
[particle-bug-4.2-beta2.zip](https://github.com/godotengine/godot/files/13073295/particle-bug-4.2-beta2.zip)

**Comment by AThousandShips** [comment] 2023-10-23 16:24
How does this look in 4.1.2? (4.1.1 is not a supported version, though changes from 4.1.1 to 4.1.2 would be considered a regression if undesired)

**Comment by Calinou** [comment] 2023-10-23 16:24
I can't reproduce this on 4.2.beta f8818f85e:

![image](https://github.com/godotengine/godot/assets/180032/511d597e-cce8-4bfa-84ab-73004eea3d52)

This was likely a regression from https://github.com/godotengine/godot/pull/81138 fixed since 4.2.beta2.

**Comment by jbromberg** [comment] 2023-10-23 16:25
> How does this look in 4.1.2? (4.1.1 is not a supported version, though changes from 4.1.1 to 4.1.2 would be considered a regression if undesired)

Looks the same as 4.1.1

**Comment by jbromberg** [comment] 2023-10-25 02:05
> I can't reproduce this on 4.2.beta [f8818f8](https://github.com/godotengine/godot/commit/f8818f85e6c43cdf1277e8ae85eba19ca0a003b0) with the 4.2.beta2 MRP:
> 
> ![image](https://user-images.githubusercontent.com/180032/277406031-511d597e-cce8-4bfa-84ab-73004eea3d52.png)
> 
> This was likely a regression from #81138 fixed since 4.2.beta2.

Interesting. Still seeing the issue in the newly released beta 3. Can you confirm?

**Comment by clayjohn** [comment] 2023-10-25 12:40
I wonder if there is an issue with the saved mesh. I can see that the MRP has a GLB, but the GLB isn't used by the particles, instead it seems that the mesh has been extracted to a .res file. 

@jbromberg Can you try the following:
1. Re-import the GLB file
2. Re-extract the mesh from the GLB

Alternatively:
1. Use the GLB in the particles instead of the .res mesh

**Comment by clayjohn** [comment] 2023-10-31 11:01
I took a deeper look into this today and it appears the issue stems from the source model not having any Tangents, yet it uses normal_mapping. As a reminder, to use normal maps you must have both normals and tangents. 

Usually, this can be fixed by selecting "ensure_tangents" in the import settings. However, in this MRP, checking "ensure_tangents" isn't enough because this model doesn't contain UVs either, which are necessary to generate tangents.

This has the same root issue as https://github.com/godotengine/godot/issues/83236 since multiple people are running into it, we may need to explore the solution I posted there

**Comment by clayjohn** [comment] 2023-10-31 14:18
Note for other maintainers, the MRP attached doesn't actually reproduce the issue. But the meshes in the MRP do. 

The MRP needs to have ``normal_map`` enabled to reproduce the issue. The GLB file has that, but the particle system in the MRP has ``normal_map`` disabled.

**Comment by akien-mga** [comment] 2023-10-31 20:10
Consolidating in https://github.com/godotengine/godot/issues/83236 as it seems to be the same root issue, and it's not about GPU Particles in the end.

**Closed by akien-mga** 2023-10-31 20:10 UTC
Labels: bug, archived, platform:macos, topic:rendering, regression, topic:3d, topic:particles
