### ISSUE TITLE
Godot 4: Imported mesh materials will not use mipmapping

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#62583] opened 2022-07-01 04:23 UTC
### Godot version

4.0 Alpha 10

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Imported mesh materials will not use mipmapping by default, and mipmapping cannot be set for imported models w/ textures due to the infinite inheritance loop bug (cannot edit mesh materials since Godot will ask to create a new inherited scene for the object, but will fail to do that).

### Steps to reproduce

- Export a GLTF (in my case, embedded) with a few objects with a unique PBR material that uses image files (albedo, roughness, normal).
- Import and place GLTF file directly into 3D view. Mipmapping is obviously non-functional due to shimmering textures.
- Create a new inherited scene based on the GLTF file. Attempt to edit the material for an object, Godot will request to create a new inherited scene for the object or else changes may be lost. Upon confirmation, it will simply open the GLTF file again in a new scene.

**Comment by Calinou** [comment] 2022-07-01 17:49
Duplicate of https://github.com/godotengine/godot/issues/62295.

**Closed by Calinou** 2022-07-01 17:49 UTC
