### ISSUE TITLE
Calling a C# method with a parameter marked with "params" from GDscript works incorrectly

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#20189] opened 2018-07-16 12:02 UTC
**Godot version:**
3.0.4 Mono

**OS/device including version:**
KDE Neon

**Issue description:**

I have this method defined in C#, that uses the `params` keyword to take a variable amount of arguments and turn them into a list. It prints some information about the argument list.
```
   public void Params(params string[] list)
    {
        GD.Print($"Params we got: {list} with length {list.Length}");
        
        foreach (var thing in list)
        {
            GD.Print($"We got: {thing}");
        }
    }
```

Now I'm trying to call it from GDscript when a button is pressed, using the following code:
```
extends Node

func _on_Button_pressed():
	Test.Params("broken")
	
```

Unfortunately, this results in an empty array being passed to the C# method, since it prints this:
```
Params we got: System.String[] with length 0
```

Additionally, feeding multiple arguments into it, like `Test.Params("a", "b")` results in an error in the editor when pressing the button:
```
Invalid call. Nonexistent function 'Params' in base 'Node (Test.cs)'.
```
**Steps to reproduce:**
Download the reproduction project and run it, then press the button and observe console output.

**Minimal reproduction project:**

[mono_params_bug.zip](https://github.com/godotengine/godot/files/2197477/mono_params_bug.zip)

(ignore the name, I'm trying to rename the project but there seems to be another bug there where it breaks C# entirely)

**Comment by neikeq** [comment] 2019-09-14 16:32
Closing as duplicate of #29775. This issue was created first, but the latter one uses a more recent version for the example reproduction project, so it's preferable.

**Closed by neikeq** 2019-09-14 16:32 UTC
Labels: bug, topic:mono
