### ISSUE TITLE
Custom Resource does not update in editor if changed/saved from script

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#24646] opened 2018-12-28 19:35 UTC
___

***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**

Godot 3.1 alpha 4 and 3.2 master (a0ce88f953a4311edc726523ff8724b891407855)

**OS/device including version:**

Windows 10 x64
Manjaro Linux 18.1.5

**Issue description:**

I'm using a Node with a tool script to open a file and generate a custom resource. For instance, using a Twine/Yarn dialogue data to generate a native godot resource (.tres) with `ResourceSaver.save()`.

The issue is when I need to re-import this data and overwrite the .tres file. If this resource is already loaded in the resource cache/history of the editor, the .tres will be updated but if I save/run any scene, it will be overwritten again with the cached data.

To fix it I need to import the data and restart the editor.

**Steps to reproduce:**
1. Open the mininal reproduction project;
2. Run the Main scene (it will print a "Lorem ipsum" imported from **data1.txt**);
3. Re-import data using the **data2.txt** file (select **ImportData** in the Scene Tree, change the **path** and click in the **import** checkbox);
3.1. Open the **data.tres** file in an external text editor (its content will be a *GNU/Linux Interjection* quote);
4. Run the Main scene again (it will print a "Lorem ipsum" again);
4.1. Open the **data.tres** file in an external text editor again (its content will be a Lorem ipsum);

**Minimal reproduction project:**

[custom-resource-update.zip](https://github.com/godotengine/godot/files/4041644/custom-resource-update.zip)

**Comment by nhydock** [comment] 2019-01-01 16:13
I'm having this issue with pretty much any custom resources tres file.  If you change any data in an external application it will not resync in Godot, external including running your own game from the editor.  Appears that the engine is not watching changes to the filesystem for file modification, only file creation and deletion.

A fast workaround to fix this would be to expose the ability to manually reindex the project with a button on the FileSystem inspector in Godot editor.  This is a common ability that I see in many IDEs that index their projects, such as IntelliJ.  There should also probably be a filesystem watcher (inotify) that recursively checks and reimports files if it detects any changes potentially from external editors.  This would help significantly when dealing with things like git merge conflicts while the editor is open, since I usually always have it running when working on a project.

**Comment by NathanLovato** [comment] 2019-01-18 23:31
That sounds fine by me :)

**Comment by williamd1k0** [comment] 2019-01-21 23:20
> @reduz  Maybe a method you can override to do your own logic would be enough?

How exactly would that work?

**Comment by nicolasdiehl** [comment] 2019-03-01 00:21
Godot 3.1.beta.calinou.9ca6ffa win x64:
Open VehicleBody in Godot,
Open VehicleBody in text editor,
Change mass in text editor and save,
--> Mass of VehicleBody doesn't change in Godot.
Close VehicleBody in Godot without saving or changing something,
--> Text editor complains that mass of VehicleBody changed back to old value.

So to pull changes from git it seems that I first have to close Godot, then pull, then reopen Godot.

**Comment by williamd1k0** [comment] 2019-03-12 20:54
Forgot to say that I managed to workaround it by "reloading" the resource after saving it.
```gdscript
var res = CustomRes.new()
var res_path = "custom-res.tres"
ResourceSaver.save(res_path, res)
res = null # I don't remember now if this is really necessary
load(res_path)
```

**Comment by akien-mga** [comment] 2020-01-09 10:54
Is this still reproducible in the current master branch / latest 3.2 builds?

**Comment by williamd1k0** [comment] 2020-01-09 17:27
Yep, still reproducible. 
Tested with master (a0ce88f953a4311edc726523ff8724b891407855).

**Comment by MikeMnD** [comment] 2020-03-24 16:54
Just to add up another case where the editor doesn't refresh the .tres

I have a Tileset with collisions if I add a collision manually in the .tres and if this is a new collision shape for a particular tile. It's loaded fine.
But if I edit existing shape than the new shape is not loaded until I close the Godot editor and reopened it again.

First thing I was looking was some button "Reload resource" or "Reimport"
So it'll be really good is something like this is added.

**Comment by Calinou** [comment] 2020-03-24 17:44
> But if I edit existing shape than the new shape is not loaded until I close the Godot editor and reopened it again.

If you save the scene, you can use **Scene > Revert Scene** to reload the scene file on disk. This is faster than closing and reopening the editor. There's no keyboard shortcut associated to that action by default, but you can define one in the Editor Settings.

**Comment by MikeMnD** [comment] 2020-03-24 17:54
> If you save the scene, you can use Scene > Revert Scene to reload the scene file on disk.

This doesn't help in my case. I'm using a Tileset file (.tres) it's not a scene and doesn't have Revert.
I tried reverting the main scene as also the scene which holds the Tilemap which holds the Tileset.  No effect until I restarted the Godot Editor.

**Comment by raptdwar** [comment] 2020-05-13 08:51
Are there any news about this issue?
I was implementing an in-game editor like @NathanLovato said in the previous comment. 
For my use case I managed to bypass the actual problem by making a copy of the targeted resource in the user:/ folder and checking if the file exists there before the actual resource in the res:/ directory.

This will definitely help anyone making in-game resource editors

**Comment by Calinou** [comment] 2020-05-13 08:56
@raptdwar As far as I know, nobody has started working on a fix yet.

**Comment by cgbeutler** [comment] 2020-07-11 01:16
Anyone know a workaround?

I made an editor that saves off textures to res, but it's having this issue..

**Comment by Shadowblitz16** [comment] 2020-10-27 21:25
This really needs to be addressed.
I shouldn't have to implement a custom handler or call reload or update through setters.
The editor should do all this for us.

**Comment by setzer22** [comment] 2020-11-08 11:22
Note that the **Scene > Revert Scene** approach suggested above does not seem to work (anymore?). At least not with AnimationTrees as resources. This leaves me with no other choice than restarting the editor every time I want to see the changes to my procedurally generated resources.

**Comment by aaaaaaaaargh** [comment] 2020-12-07 23:57
Looks like my issue may be related to this one. In my case I want to create multiple resources in a custom importer. Right now I'm simply doing it by calling:

`ResourceSaver.save(filename, res, ResourceSaver.FLAG_REPLACE_SUBRESOURCE_PATHS | ResourceSaver.FLAG_CHANGE_PATH)`

I'm doing this to produce multiple files and even write to the imported file itself without any problems on filesystem level. However, the editor simply will not update the resources as it should, it either displays some cached version of the file or simply throws an error about no valid resource loader being found.

I tried many things, including re-loading the resource after it has been saved, copying the file manually using `Directory.copy()`, using `.take_over_path()` but none of them seemed to have worked.

What I'm expecting is the editor to reload the resource once I have updated it using the `ResourceSaver`. The observed behaviour does not update anything, at least not in a reliable way. So that begs the question: Is this some kind of bug or am I doing the wrong thing here?

**Comment by cgbeutler** [comment] 2020-12-08 23:11
**Workaround I use:**

The main issue is that the editor has loaded and cached the resource already. That cached ref is already held by all kinds of things and there may not be a way to really replace all of their references.

In other words, we need to maintain the cached value, even when saving. You can call `ResourceLoader.exists` to see if it was already saved or `ResourceLoader.has_cached` if you just care about cache. If the cache is there, you can call 'ResourceLoader.load' to get that cached value. From there, change what data you need to and _then_ you can re-save it.

Here is an example from the included minimal project:
```coffeescript
tool  #<must be tool to get editor's ref
...
func import():
	var f = File.new()
	f.open(path, f.READ)
	var text = f.get_as_text()
	
        # Get cached value first, then update and save.
	var res
	if ResourceLoader.exists('res://data.tres'):
		res = ResourceLoader.load('res://data.tres')
	else:
		res = CustomData.new()
	
	res.data = text
	
	ResourceSaver.save('res://data.tres', res)
	OS.alert('Saved to res://data.tres', 'Import')
```

NOTE:  This may occasionally have issues if you are editing the script of the cached value. In those cases you may need to restart the editor, but this method will at least limit how often you have to hard-reset.

**Comment by raptdwar** [comment] 2021-02-13 21:14
Does [#31747](https://github.com/godotengine/godot/pull/31747) resolve this issue?

**Comment by williamd1k0** [comment] 2021-02-14 03:52
> Does [#31747](https://github.com/godotengine/godot/pull/31747) resolve this issue?

Probably not, as it appears to be related only to scene files and project.godot (https://github.com/godotengine/godot/pull/31747/files#diff-b88f0bde58b731e8dd353707c8011fb7a1e452f0db2c9f15f4b7905d60e5e52eR884).

**Comment by FeralBytes** [comment] 2021-03-10 03:55
If #45880 is included in 3.2.4rc4 then it does not fix this issue.

**Comment by cgbeutler** [comment] 2021-04-21 19:45
> So basically no easy way to fix this issue ? I'm on 3.3.rc9 :( 

Check out my earlier reply for a workaround. Maintaining resource refs is good to learn anyway.

To add a similar bug's workaround: If you mainly have an issue with losing data after editing scripts, you may need to export more variables. When the editor sees a resource's script updated, it will then construct a new one and copy all exported variables over to the new one. That means any data not in init, default values, or exports will be lost.

**Comment by SyliawDeV** [comment] 2021-04-22 01:34
> > So basically no easy way to fix this issue ? I'm on 3.3.rc9 :(
> 
> Check out my earlier reply for a workaround. Maintaining resource refs is good to learn anyway.
> 
> To add a similar bug's workaround: If you mainly have an issue with losing data after editing scripts, you may need to export more variables. When the editor sees a resource's script updated, it will then construct a new one and copy all exported variables over to the new one. That means any data not in init, default values, or exports will be lost.

I'm currently use TexturePacker importer and export from there as spritesheets(png and tpsheets(json)) but my work not just make all assets and import once some time I need to add new texture to spritesheet or remove some. And yes the editor doesn't seem to update the region, side the plugin create a atlas.  But when I check region in resources fille (.tres) is updated the region but not in the editor.

**Comment by cgbeutler** [comment] 2021-04-22 05:23
If the plugin is creating resources that are already saved to disk, then read my big guide above. You need to load all previously saved resources first to get the cached version, then update and save them. Even if you don't plan on keeping any of the old data, you still need to load first.

If you are doing all that correctly, then you should be able to collapse and expand the resource in the inspector to see the new data. If that doesn't work, you are probably loading the old one wrong. If collapsing and re-opening does refresh the data, then you at least have that as a workaround till it's fixed.

**Comment by Ittikowa** [comment] 2021-05-19 15:59
This bug costed me hours of work this morning. I finally realized it wasn't my code but the editor doing strange things.

I'm not writing a plugin like the others. I'm just saving a resource from code  and then trying to inspect it to make sure I got the correct results. The problem is that unless it's a new file the editor won't display the contents properly. In fact when I do re-save it without reloading the scene I get strange results, like data being out of place or just plain wrong. It's as if the cached resource IS attempting to be updated, but simply failing to do it properly and being entirely out of sync.

When I reload the saved scene (as suggested above by Calinou), or close and reopen Godot, the file's contents appear correct. I also now have a data printout before I save the file, so I know the data is correct either way. So from what I can tell there is obviously something very wrong with the way Godot attempts to update saved resources in the inspector.

**Comment by Trystan-SA** [comment] 2021-06-15 15:52
Same issue, lost about 2 hours. It feels like I'm fighting the editor which is not a good thing at all.

**Comment by hunterloftis** [comment] 2022-01-01 19:18
Is there no way to trigger updating a resource's representation in the editor? I just ran into this bug as well. With:

```gd
export(Texture) var surface_mask: Texture
# ...
surface_mask = _get_surface_mask()
```

The mask only updates in the editor after blurring and focusing the node.

**Comment by KoBeWi** [comment] 2022-03-03 00:34
I can't reproduce the issue in 3.5 beta with the original reproduction project. Anyone can provide updated project or is the issue fixed?

**Comment by KoBeWi** [comment] 2022-05-15 00:34
Closing due to no response. Comment with a new MRP if you can still reproduce in 3.5 or 4.0.

**Closed by KoBeWi** 2022-05-15 00:34 UTC
Labels: bug, topic:editor, confirmed, topic:import

**Comment by williamd1k0** [comment] 2022-05-28 23:24
Sorry for the delay on replying.

So, as mentioned by @[lyuma](https://github.com/lyuma) in https://github.com/godotengine/godot/issues/30302#issuecomment-1140052274, the problem can be solved by calling `Resource.take_over_path(path)` before or after saving the resource (assuming you are updating the resource via script).

Reproduction project using the approach mentioned above: [custom-resource-update-fix.zip](https://github.com/godotengine/godot/files/8792322/custom-resource-update-fix.zip)

>I haven't tested it on recent versions of Godot yet.

**Comment by KoBeWi** [comment] 2022-05-28 23:46
What are the exact steps to reproduce? I tried the project and seems like the resource is saved correctly even without `take_over_path()`

**Comment by williamd1k0** [comment] 2022-05-29 00:00
I just tried reproducing (without `take_over_path()`) in Godot v3.4.4 and it's working fine, so I assume the workaround is only needed in versions prior to v3.3.4.

**Comment by KoBeWi** [comment] 2022-05-29 00:25
Well, then the issue is indeed resolved. Thanks for confirming.

**Comment by levidavidmurray** [comment] 2022-11-27 03:11
So, I guess I was hoping these would act similar to Unity's `ScriptableObject`.

I have a `Config.gd` class that extends `Resource` which holds, as I'm sure you can guess, various game relevant config data. I've gone ahead and created a `Config.tres` which works all fine and dandy. However, if I add a new exposed variable to `Config.gd`, this change is not reflected in the editor. The only way I can get it to update is by either dereferencing the reference script (losing all my saved data), or restarting Godot.

Is this the intended functionality?

I'm using Godot v3.5.1 by the way.

**Comment by KoBeWi** [comment] 2022-11-27 17:02
> Is this the intended functionality?

No. The property list should be updating automatically.

**Comment by ForestGameDev** [comment] 2023-10-13 16:56
It seems this is not fully resolved. In Godot 4.1 I created a new Resource type with an exported int. From a Tool script I assigned the int value:

```
my_resource.size = 10 #assigned in some other method

var my_vector = Vector2i(my_resource.size, my_resource.size)
print(my_vector) #produces (0,0)
```

I then tried saving the value to an intermediate value, and that worked:

```
my_resource.size = 10  #assigned in some other method

var helper = my_resource.size
var my_vector = Vector2i(helper , helper)
print(my_vector) #produces (10,10)
```

**Comment by KoBeWi** [comment] 2023-10-13 18:27
Can you attach a minimal project?

**Comment by MoogieOuttaMyDepth** [comment] 2024-08-10 20:32
I am also having this issue in Godot 4.2.2 Stable.

I'm aware of the bugsquad edit up top that says it's been confirmed, but a project file was requested and I can provide that for you.

Problem: I have a custom resource, horse_atlas_resource.gd (horse_atlas_resource.tres) which defines a dictionary containing a series of sprite coordinates for differently-coloured horses on a texture atlas. At game load, the Main scene looks at this resource and randomly picks keys from it to spawn different coloured horses into the scene.

Bug: If I change horse_atlas_resource.gd to add a new horse colour, remove an existing one, or alter the coordinates of an existing one, none of these changes are reflected. And this is not just an editor issue: **Restarting Godot does not fix the problem for me.**

Workaround: I must manually delete and recreate  horse_atlas_resource.tres, otherwise my changes to the .gd script are never reflected in the project.

See attached, hope it helps resolve this very serious issue.

[Horses.zip](https://github.com/user-attachments/files/16570834/Horses.zip)

**Comment by KoBeWi** [comment] 2024-08-12 10:20
@MoogieOuttaMyDepth It's unrelated to this issue, which is about using ResourceSaver to save the resource using a script.

Your problem is that modifying the script does not mark the Resource as modified. Normally when you change a resource and press Ctrl+S, editor will automatically save all modified resources. It does not happen when changing the resource's script and you have to save it manually, from the save menu in the inspector:
![image](https://github.com/user-attachments/assets/0c0d4cff-08da-4cfc-bd6e-6093fa6562d1)
(this way you don't have to re-create it)

Although this behavior is a result of another bug. The `character_frames` variable is saved even though it's equal to the default value. Normally if something is equal to default then it's not saved, so when you change the default in script, all saved resources will use it automatically (unless they have the value overriden).

And finally, your problem is discrepancy in default value in script vs default value saved in resource. But since you are using the default value anyway, you don't need the resource at all - you can use the Dictionary defined in script directly if they are supposed to be equal anyway. Resources are only useful when you change their properties in the inspector or using custom editors.

**Comment by lucassene** [comment] 2024-09-03 08:31
I have a similar issue when using 4.3, although my changes are being saved in the file.

I have a simple Resource containing two exported Dictionaries that I change and save using a @tool script.

If I check the resource file in the editor after running the save method, it will appear as unchanged. BUT, if I check the file externally (Nodepad), my changes are there and saved. The issue is simply the resource visualization in the Inspector is not being updated. That can be confirmed when I restart the editor, and I can see all my changes to the Resource file in the Inspector.

**Comment by kirkatia98** [comment] 2025-01-10 19:10
Confirmed,  "Scene > Reload Saved Scene" works to refresh the resource for me in 4.3

Hopefully we get a fix

**Comment by Zehir** [comment] 2025-02-25 20:55
Bringing my own stone to this issue, I had the same problem to save a JSON Resource.
The [solution](https://github.com/godotengine/godot/issues/24646#issuecomment-2583655473) from @kirkatia98 did not work for me.
I took some insiration from the [save_resource](https://github.com/V-Sekai/unidot_importer/blob/7480b19649d50eef93cc8efd7ec9aa83d63a1bcb/unidot_utils.gd#L10-L44) function from unidot_importer. And I made this if you have the same issue as me and found this issue in the future : 

```gdscript
@tool
extends EditorScript

func _run() -> void:
	var prototree_path = "res://test.json"
	var existed: bool = FileAccess.file_exists(prototree_path)
	
	for editor in EditorInterface.get_script_editor().get_open_script_editors():
		if editor.get_meta("_edit_res_path") == prototree_path:
			editor.free()

	var prototree: JSON = JSON.new()
	var random_value: float = randf()
	prototree.data = {"foo": random_value}

	if existed:
		prototree.take_over_path(prototree_path)
	else:
		var new_uid = ResourceUID.create_id()
		ResourceUID.add_id(new_uid, prototree_path)
	ResourceSaver.save(prototree, prototree_path, ResourceSaver.FLAG_CHANGE_PATH)
	if not existed:
		EditorInterface.get_resource_filesystem().update_file(prototree_path)
```

**Comment by fbsr** [comment] 2025-05-22 22:54
Adding notify_property_list_changed() in property setters works for me to show real-time changes in the inspector:

```
extends Resource
@export var example: int:
    set(value):
        if example!= value:
            example= value
            notify_property_list_changed()

```
