### ISSUE TITLE
Object doesn't stop moving when key pressed and Vector3 normalized

### ISSUE THREAD

**Issue by mo-moxi** [godotengine/godot#42189] opened 2020-09-19 08:25 UTC
Don't know if this is a feature or a bug, but when a direction key is pressed the Kinematicbody keeps moving in the direction pressed. The only way to prevent this is to zero the Vector3 before the get_input is called.

Godot Engine v3.2.3.stable.mono.offical

Sample code:

func get_input()
       	if Input.is_action_pressed("ui_right") && Input.is_action_pressed("ui_left"):
		_velocity.x = 0
	elif Input.is_action_pressed("ui_right"):
		_velocity.x = SPEED
		rotate_z(-ROTATE)
	elif Input.is_action_pressed("ui_left"):
		_velocity.x = -SPEED
		rotate_z(ROTATE)

func _physics_process(_delta):	
	get_input()
#   bug in Godot: normalized speed keeps moving the object
	_velocity =_velocity.normalized()
	move_and_slide(_velocity)

**Comment by Firepal** [comment] 2020-09-19 08:49
you never set "_velocity" to zero when you're done using ```move_and_slide```, so Godot will keep calling ```move_and_slide``` every physics frame with the "_velocity" variable as first argument, still set to a non-zero value.

So DO zero the Vector3, before or after ```get_input()``` is called!
```_velocity = Vector3.ZERO```

This is not a bug with Godot, just a simple oversight in your code. :)

**Comment by mo-moxi** [comment] 2020-09-19 16:16
Hi, yeah. I got that after running a print 'debug' before normalizing. I
also put velocity.zero as well, but thought this was overkill (not knowing
that the engine retains the previous keystroke value though nothings been
pressed). So maybe this isn't such an oversight, especially when normalized
is remove and the object stops...
Anyway, I stuck in an if statement which stopped the oversight.

Many thanks.

Mo

**Comment by KoBeWi** [comment] 2020-09-19 17:16
Closing, because not bug. Use other community channels next time if you are not sure: https://godotengine.org/community

**Closed by KoBeWi** 2020-09-19 17:16 UTC
