### ISSUE TITLE
GDScript 2.0: Project fails to run due to parser bug - "tried to assign unset node without an identifier"

### ISSUE THREAD

**Issue by minionprocyk** [godotengine/godot#62006] opened 2022-06-13 20:31 UTC
### Godot version

4 alpha 9

### System information

Fedora 35

### Issue description

Ive been playing around in Godot 4 alpha builds and seems like when I open an existing project from a previous build I receive: 

E 0:00:00:0659   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:656 @ resolve_class_interface()

### Steps to reproduce

- Create godot 4 alpha 2 build 
- Add some scenes, Texture2D resources, some static, some dynamic
- Import this build into godot 4 alpha 9

These steps are probably not very helpful, I can look into debugging this one myself.

**Comment by Calinou** [comment] 2022-06-13 23:07
Related to https://github.com/godotengine/godot/issues/58542.

**Comment by BrianMWest** [comment] 2022-11-09 03:46
In 4beta4 I can reproduce this with a circular reference of a singleton to a preloaded scene.

`Load` singleton contains `var is_loading_screen_active := false` and `var Plain := preload("res://<...>/Plain.tscn")`

`Plain.tscn`'s script contains contains `Load.is_loading_screen_active = true`. When attempting to run the project, it fails with the above parser bug. Removing the corresponding line in Plain's script allows it to run. It seems like the parser attempts to convert the script for the preloaded scene as it's processing the Load singleton (DFS-style), and it is then attempting to resolve the reference to `Load` in the script when it hasn't finished processing the Load singleton yet

**Comment by clayjohn** [comment] 2022-11-17 07:39
Duplicate of #58542

Closing in favour of #58542 which includes an MRP

**Closed by clayjohn** 2022-11-17 07:39 UTC
Labels: bug, topic:gdscript, needs testing
