### ISSUE TITLE
Y Axis Flickering

### ISSUE THREAD

**Issue by Thane5** [godotengine/godot#50997] opened 2021-07-29 07:30 UTC
### Godot version

v4.0.dev.calinou [48857194b]

### System information

Windows 10, Vulkan. Nvidia RTX 3070, driver 471.41 WHQL

### Issue description

In a blank scene, the green Y axis flickers when rotating the view. After moving the view for a at least once, the flicker stops appearing.

### Steps to reproduce

Create new project, rotate view.

**Comment by Chaosus** [comment] 2021-07-29 08:42
Duplicate of #37016

**Closed by Chaosus** 2021-07-29 08:42 UTC
