### ISSUE TITLE
Tool script does not run until the scene is reloaded

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#25275] opened 2019-01-24 01:01 UTC
Godot 3.0.6
Godot 3.1 beta 2

I made a simple tool script which uses `_draw()` to have custom visuals. But I noticed that once I finished writing it and setting it up, it was still not running in the scene. Only saving, closing and re-opening the scene made it run.
The same happens if you add a tool script to a node, this script won't run until you reload the scene, even if existing instances of it are running already.

Reproduction project: 
[ToolScriptDoesntRunYet.zip](https://github.com/godotengine/godot/files/2789781/ToolScriptDoesntRunYet.zip)

1) Open the project, see the main scene has one working node with custom `tool` draw (using `custom.gd`)
2) Create another `Node2D`
3) Put another `custom.gd` script on it: notice it doesn't work
4) Save the scene, close it, and reopen it: notice it works now

**Comment by kubecz3k** [comment] 2019-01-24 17:24
I think that by design `File -> Soft reload script ` (ctrl + shift +R) is a fast way to reload the tool script for the editor. Can you check if it's working in your case?

**Comment by KoBeWi** [comment] 2019-02-28 19:23
The quickest way to reload scene is Reload scene button in Scene menu. Works in this case.

**Comment by Chaosus** [comment] 2019-03-08 16:47
@KoBeWi Its called "Revert scene" actually and its even not have a editor shortcut

**Comment by swarnimarun** [comment] 2019-09-20 01:01
I looked into the issue slightly while I was working with the Visual Script Tool Mode feature. The best way of for fixing it does seem to be a forced reload of the scene, the question is how to handle the save, I guess we can just ask if we want to save the scene.?

For VisualScript we can do it automatically(from the UI itself), while for normal scripts we could create a notification asking to Reload the Scene and hint the hotkey for it?

**Comment by Zylann** [comment] 2019-09-20 12:20
I don't think this needs to reload the scene on every save of the script, that would be overkill. It would only need this if the script was not `tool` before, and became `tool` after. But then if this detection can be done, the scene wouldn't need to even be reloaded, is it?

**Comment by swarnimarun** [comment] 2019-09-20 19:36
That's what I meant. If it detects that the Script became Tool but there hasn't been a scene reload it will notify.

**Comment by KoBeWi** [comment] 2021-12-02 12:51
The `@tool` actually works immediately. The reason why your square doesn't draw after saving is that `_draw()` is called when Node2D is added to scene tree or calls `update()` or is made visible.
![xhVqwWQCPg](https://user-images.githubusercontent.com/2223172/144425154-de1aa1bf-726f-4958-a8a1-a037234942da.gif)

Another case is when you add `_process()` to the script. `set_process()` is called internally inside ready, so there is no way to enable it without reloading the scene.

Maybe we could detect this and add a warning, but otherwise the issue can be closed.

**Comment by KoBeWi** [comment] 2022-09-17 15:50
Closing as per above comment. Open a proposal if you still think something should be done.

btw
> Its called "Revert scene" actually and its even not have an editor shortcut

You can just assign a shortcut if you want quick access. I use it all the time.

**Closed by KoBeWi** 2022-09-17 15:50 UTC
Labels: enhancement, topic:editor, usability, topic:plugin
