### ISSUE TITLE
Vulkan: Spotlight3D shadows are broken.

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#45819] opened 2021-02-08 07:56 UTC
**Godot version:**
[57e2822](https://github.com/godotengine/godot/commit/57e2822a05c29db3980ad243c37a34acf6c4d14b)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Spotlight3D has weird banding with shadows enabled. Moreover, disabling shadows does not remove banding nor shadows.
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/2698825/107190556-fac73880-69fb-11eb-9d76-76fd6b0a987b.mp4

</details>

**Steps to reproduce:**
Add Spotlight3D to test scene and enable shadows.

**Minimal reproduction project:**
[SpotlightTest.zip](https://github.com/godotengine/godot/files/5941998/SpotlightTest.zip)

**Comment by BastiaanOlij** [comment] 2021-05-10 04:39
@reduz I can confirm this is still happening on the current master:

![image](https://user-images.githubusercontent.com/1945449/117606582-85efd000-b19d-11eb-9e51-54ad28038313.png)

Updated material tester project: https://github.com/godotengine/godot-demo-projects/pull/616

**Comment by Calinou** [comment] 2022-08-08 17:13
I can't reproduce this on 4.0.alpha f85a81696 (Linux, NVIDIA 515.57) with the MRP, closing.

![image](https://user-images.githubusercontent.com/180032/183475150-1ba0e94e-a31c-4f3d-9b4b-2075e3b6d176.png)

**Closed by Calinou** 2022-08-08 17:13 UTC
Labels: bug, topic:rendering, confirmed, regression
