### ISSUE TITLE
Project Manager is not keyboard friendly

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8149] opened 2017-03-25 19:06 UTC
**Ubuntu 16.10 - Godot version: tested on 2.1.2 stable but may affect all builds**

**Issue description:**
Can't use keyboard on the Project Manager using all the options.
Keyboard shortcuts and common navigation (using arrows and tabs) is expected to work.

**Steps to reproduce:**
Try to use the project manager with keyboard to run, edit, import and create projects.

**Comment by Anutrix** [comment] 2019-07-04 21:12
In latest master https://github.com/godotengine/godot/commit/550f436f8fbea86984a845c821270fba78189143 , tab and arrow keys work BUT seems to be in bad shape.
Issues:
You need to first click on search or similar before any keys start working(Just hovering isn't enough).

Also, after pressing tab a few times, you get focus on the small "open project folder" buttons. Then holding arrow keys highlights projects, while pressing arrow keys or tab key highlights the "open project folder" buttons. It is buggy. Sometimes pressing keys once shift focus to next button, sometimes twice.

It would be nice if someone could confirm this and list out the needed changes.

**Comment by Calinou** [comment] 2019-07-04 21:15
Would it make sense to select and focus on the first project automatically (as long as there is at least one project in the list)?

**Comment by eon-s** [comment] 2019-07-04 22:11
Focus on the first project or "new project" button if the list is empty.

**Comment by rcorre** [comment] 2020-03-23 00:11
@Calinou any plans for making a PR from 2897818? I could have sworn that Godot 3.1 autofocused the first project, but in Godot 3.2 it focuses the button column on the right.

**Comment by rcorre** [comment] 2020-03-23 00:15
Yup, just rebuilt 3.1 and confirmed, it _did_ focus the first project, so there was some regression in 3.2.

**Comment by Calinou** [comment] 2020-03-23 08:16
@rcorre In the `master` branch, the search field is now automatically focused so you can press Enter after searching for anything. This hasn't been cherry-picked to the `3.2` branch yet though.

**Comment by rcorre** [comment] 2020-03-24 13:04
@Calinou ah, so it does! That's pretty nice. The up/down arrows still take you down the buttons on the side rather than the project list though ... is that intentional?

**Comment by Calinou** [comment] 2020-03-24 13:56
@rcorre No, but I haven't looked into solving this yet. If we fix this, we need to find alternative shortcuts for individual actions so they can all be performed using the keyboard exclusively.

For starters, maybe we could make <kbd>Ctrl + Enter</kbd> run a project instead of editing it?

**Comment by eon-s** [comment] 2020-03-24 17:20
ctrl+enter to edit the project sounds better, and check the neighbour of the file selection dialog because it keeps scrolling on the project list if you go out of the file list with arrow keys.

**Comment by Calinou** [comment] 2020-03-24 17:41
@eon-s When you double-click a project, it will be edited. I'd rather have the "simplest" keyboard action be consistent with that. Running a project directly is typically a secondary action. Most people open the project manager to edit projects :slightly_smiling_face:

**Comment by eon-s** [comment] 2020-03-24 20:02
@Calinou yes, you are right, I have read it wrong :+1:

**Comment by Anutrix** [comment] 2020-03-25 16:13
The last time I checked arrow keys work on both project list and buttons at the same time. For example, on pressing down arrow key, not only listed 2nd project but also 2nd button of the right side list is highlighted.

**Comment by LightningAA** [comment] 2021-05-14 14:12
Duplicate of https://github.com/godotengine/godot-proposals/issues/532?

**Comment by Zireael07** [comment] 2021-05-14 15:33
Most likely yes, since this is older this should probably be closed in favor of the proposal.

**Comment by Calinou** [comment] 2021-05-14 15:53
Closing in favor of https://github.com/godotengine/godot-proposals/issues/532.

**Closed by Calinou** 2021-05-14 15:53 UTC
Labels: topic:editor, usability
