### ISSUE TITLE
[Godot v4.0] - Beta 7 HTML5 Does Not Work?  Beta 6 & Beta 5 HTML5 Works?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#69664] opened 2022-12-06 13:54 UTC
### Godot version

v4.0 Beta 7 Vs. Beta 6 & Beta 5

### System information

Windows 10/11 64Bit Edge/Firefox/Chrome/Opera / Linux 64Bit Firefox/Chrome

### Issue description

Hi,

Godot 4 Beta 7 HTML5 builds do not work?
Beta 6 & Beta 5 HTML5 builds do work.

Can this be fixed in Beta 8?

Jesse

### Steps to reproduce

DOES NOT WORK?:
https://betamaxheroes.org/games/TS3-Godot_4/Godot_4_Beta_7/index.html

WORKS:
https://betamaxheroes.org/games/TS3-Godot_4/Godot_4_Beta_6/index.html
https://betamaxheroes.org/games/TS3-Godot_4/Godot_4_Beta_5/index.html

### Minimal reproduction project

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by Sauermann** [comment] 2022-12-06 14:07
Might be a duplicate of #69489. Not enough info to be sure.

**Comment by akien-mga** [comment] 2022-12-06 14:12
#69489 would make any HTML5 project fail, so I'll assume it's a duplicate indeed.

Let us know if it's still reproducible once beta 8 is released.

**Closed by akien-mga** 2022-12-06 14:12 UTC
