### ISSUE TITLE
3.3 Regression: Editor rendering problem after connecting Skeleton2D property for a Polygon2D.

### ISSUE THREAD

**Issue by SaffronStreams** [godotengine/godot#48641] opened 2021-05-11 14:19 UTC
I am using Windows 10 and encountered this problem in Godot 3.3 stable, this does not happen in 3.2.3 stable (or any previous versions that I've used).

I noticed previously that when trying to edit a character in a project I've been working on, that I would have problems copying a Polygon2D node and adjusting the UV, in 3.3 the polygon would turn invisible. I noticed that if I just opened the same project in 3.2.3, the polygon was still visible. I couldn't reproduce it and couldn't find it mentioned here yet so thought it was an error on my side (I would think Polygon2D + Skeleton2D are still ubiquitous in 2D projects?). 

But then today I thought of the extra step of attaching a Skeleton2D node to the Polygon and found that there the problem arises.

This is the same project, with the same node selected, first opened in 3.3:

![PolygonProblem3 3](https://user-images.githubusercontent.com/50481103/117829725-53180b80-b273-11eb-9801-229f32e3a4e4.png)

Compare with it opened in 3.2.3:

![PolygonProblem3 2 3](https://user-images.githubusercontent.com/50481103/117829803-61662780-b273-11eb-81d9-9fdff7a80ff1.png)

I think you could have a similar effect previously when you hooked up a polygon to a Bone2D that wasn't part yet of the rest pose of a skeleton 2D ( but having it turn invisible by just connecting it to the skeleton makes it real hard to position the bones).

Minimal reproduction project (used in screenshots)
[PolygonUVTester.zip](https://github.com/godotengine/godot/files/6459800/PolygonUVTester.zip)

**Comment by akien-mga** [comment] 2021-05-11 15:12
I can reproduce the issue in current `3.x` branch and 3.3.1 RC 1.

**Comment by lawnjelly** [comment] 2021-05-11 16:20
This looks like I just need to fallback to not doing any skinning / using an identity transform when there are no bones, it doesn't look too complicated but I'll make sure it works if some verts are skinned and some not.

**Comment by akien-mga** [comment] 2021-05-13 15:40
Fixed by #48647.

**Closed by akien-mga** 2021-05-13 15:40 UTC
Labels: bug, confirmed, regression, topic:2d, topic:rendering
