### ISSUE TITLE
Command line parsing: can't pass custom arguments without leading hash ( -custom )

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8721] opened 2017-05-12 02:01 UTC
I'm trying to add some command line parsing code and have found an issue.

In the editor if I supply a command line:
-lang en
this works fine, if I do:
-lang en -mqwe -Test
this works fine, but if i do:
-lang en -mqwe Test

then it falls over at load time. I suspect it is trying to load Test as a scene as if any command line argument not starting with a - gets treated as the scene to load.

**Comment by bojidar-bg** [comment] 2017-05-12 10:05
Well, obviously, `-mqwe` doesn't take an argument, while `-lang` does. (it should have been `--lang`, but, whatever)

Just the same way you can do `godot -e res://test.tscn` to open the editor for `test.tscn`, but doing `godot -path res://test.tscn` would try to open the project at `res://test.tscn`, and fail.

**Comment by supagu** [comment] 2017-05-12 10:59
-mqwe is a command line argument I want to add to the game using gdscript. I would expect godot to only use the argument "-lang en" as it is an engine supported parameter. Infact, I wouldn't even expect that to be consumed but it is as OS.get_cmdline_args() does not return any value with "-lang en" in it.

so the engine shouldn't do anything with "-mqwe Test" yet Test is being used to seemingly load a scene.

**Comment by bojidar-bg** [comment] 2017-05-12 11:04
@supagu For now, you might use `-mwqe=Test` as a workaround. In the future, we should probably devise some smarter way for doing this (but this issue is marked as "discussion", so feel free to give suggestions!)

**Comment by kubecz3k** [comment] 2018-04-19 18:04
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2019-04-15 15:53
Note: This is still a valid request.

I plan to work on adding support for passing custom arguments after a double dash separator, such as `godot -e --path /path/to/game -- custom-arg1 custom-args2=42`, but haven't had time yet. If anyone else wants to have a go at it, feel free to.

**Comment by API-Beast** [comment] 2019-05-17 21:54
I would classify this as a bug rather than a feature proposal. Passing anything without prefixing it with a "-" will crash the engine.

The problem is that it will interpret anything like a scene file it should launch.
The easiest way to fix this would be to make it check the file ending, and only interpret it as main scene file to launch if the ending is either .tscn or scn.

**Comment by Calinou** [comment] 2019-05-17 22:25
While this issue is still present, as a workaround, it's possible to parse arguments written `--like=this`. See [this Q&A answer](https://godotengine.org/qa/45094/there-arguments-running-from-with-headless-server-version?show=45120#a45120) for an example.

**Comment by API-Beast** [comment] 2019-05-18 07:45
That doesn't really solve anything. For example, the common command line interface for a application to open a specific document is to pass that file name as an single argument. Users and developers alike depend on this convention. For example if you Drag & Drop a file from the Windows Explorer onto an executable then it will launch the executable with the file as first argument. For any Godot application this will cause a crash.

**Comment by lupoDharkael** [comment] 2019-11-05 14:23
relevant to: https://github.com/godotengine/godot/pull/26213

**Closed** 2020-01-10 12:48 UTC
Labels: discussion, feature proposal, topic:core
