### ISSUE TITLE
[4.4 Dev 5] Empty Project High CPU usage.

### ISSUE THREAD

**Issue by agorangetek** [godotengine/godot#99784] opened 2024-11-28 10:16 UTC
### Tested versions

Reproducible in: 4.4.dev5

### System information

Godot v4.4.dev5 - Windows 10.0.26100 - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 32.0.12019.1028) - AMD Ryzen 7 9700X 8-Core Processor (16 threads)

### Issue description

High CPU usage with an empty project. low_processor_usage_mode() does not make a difference. 1 of the threads on my CPU is at 100% usage. This applies to the editor and projects run from the editor.

### Steps to reproduce

Launch the editor. Also create a Control node and run a project. The editor and the running project will each use 100% of a CPU thread.

### Minimal reproduction project (MRP)

N/A

**Comment by YYF233333** [comment] 2024-11-28 10:21
See #99593

**Comment by clayjohn** [comment] 2024-11-29 21:05
I suspect thats right and this is a duplicate of #99593 which was fixed by https://github.com/godotengine/godot/pull/99688

**Closed** 2024-12-19 06:45 UTC
Labels: bug, topic:core, regression
