### ISSUE TITLE
Undo/Redo not working in 3D editor

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#58251] opened 2022-02-17 18:29 UTC
### Godot version

3,x (747d11b5b977dcd056269bdd90628fdc396eb30b)

### System information

Windows 11

### Issue description

Undo/Redo is not working in the 3D editor when performing transform operations. Seems to only happen directly after starting Godot. When you do an undo/redo operation in the script editor and then try it again in 3D it works.

Does not happen in 3.5 beta1. Not tested on master.

### Steps to reproduce

1. Open Godot
2. Move some nodes in 3D, then try to undo the move -> not working
3. Open a script, make an edit and then undo it
4. Switch to the 3D viewport, move something and undo it-> works

**Comment by Calinou** [comment] 2022-02-17 18:32
This is likely because the script editor intercepts undo/redo shortcuts. This sounds related to https://github.com/godotengine/godot/issues/53424, which *can* be reproduced on 3.4 and 3.5beta1.

**Comment by mbrlabs** [comment] 2022-02-17 18:55
I just noticed it's not only the undo/redo shortcuts but also ESC...well probably all shortcuts that are used by the script editor.

**Comment by KoBeWi** [comment] 2022-02-18 00:46
For whatever reason this is a regression from #57900
I'll see if the same happens in master.

**Comment by timothyqiu** [comment] 2022-02-18 05:20
I want to inspect this but I can't reproduce this on my machine :( Undoing 3D transform works both before and after editing any script.

**Comment by mbrlabs** [comment] 2022-02-18 08:20
@timothyqiu make sure to setup a 3D as main scene before, so you don't have to click anywhere when you launch Godot. Then reopen Godot and you should be able to directly reproduce it in the main scene.

**Comment by timothyqiu** [comment] 2022-02-18 09:31
So far:

* There is indeed a copy paste mistake in #57900. This second argument should not be there. But removing it does not fix this issue.

    https://github.com/godotengine/godot/blob/e2287a201a54a113bb1461cd5997a23cc9c1f50d/scene/2d/canvas_item.cpp#L374
* You don't have to undo in Script editor, simply switch to it and back makes undo working.
* Seems like the Script editor's edit menu thinks itself visible in tree initially. I'll take a further look.

**Comment by KoBeWi** [comment] 2022-02-19 08:41
Ok, something is definitely bugged here:
![godot windows tools 64_S5HJzP7pA8](https://user-images.githubusercontent.com/2223172/154793680-c8237050-5ac9-4a84-859a-4162bd9da650.gif)

**Comment by akien-mga** [comment] 2022-02-21 11:34
IIUC this should be fixed by #58386, can someone confirm?

**Comment by KoBeWi** [comment] 2022-02-21 11:43
Yes, this was fixed.

**Closed by KoBeWi** 2022-02-21 11:43 UTC
Labels: bug, topic:editor, regression
