### ISSUE TITLE
Reversed text input in skeleton modifications

### ISSUE THREAD

**Issue by pooroligarch** [godotengine/godot#65277] opened 2022-09-03 06:47 UTC
### Godot version

v4.0.alpha15.official.432b25d36

### System information

Fedora 36 KDE

### Issue description

![image](https://user-images.githubusercontent.com/40056096/188083830-149ae578-931b-4496-b618-b6912ee55c77.png)
The text ends up right to left. When I copy the text it's also reversed so this is not just a rendering issue. Select, delete and backspace work as expected (LTR). Setting the text direction manually has no effect.

### Steps to reproduce

* Create a new Skeleton3D
* Add a modification stack
* Add a modification to the stack 
* Write something in a bone name field (with ccd/jiggle/fabrik you need to set the chain length to >0 first)

**Comment by KoBeWi** [comment] 2022-09-03 12:41
Duplicate of #62876

**Closed by KoBeWi** 2022-09-03 12:41 UTC
