### ISSUE TITLE
VisualScripting concatenate not working

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#25935] opened 2019-02-16 11:33 UTC
**Godot version: f5477ee**

**OS/device including version:**

Win10 64bit

**Issue description:**

String concatenate block in VS does not read values in the box, so you have to separately create constants and plug them in. In the picture you can see that only hello word is being sent to output. I am not sure if that is the desired behavior and if it is it might be a little confusing for newcomers. 

**Steps to reproduce:**
![vs](https://user-images.githubusercontent.com/9384421/52899133-ccd10400-31e6-11e9-932f-25aa304ea5c0.PNG)

**Minimal reproduction project:**

**Comment by Chaosus** [comment] 2019-02-16 13:57
Its a duplicate of https://github.com/godotengine/godot/issues/19609, currently default value is setted to  null no matter what

**Closed by Chaosus** 2019-02-16 13:57 UTC

**Comment by Chaosus** [comment] 2019-02-16 14:11
As a workaround you can use second property or constant ^^
