### ISSUE TITLE
@export_enum does not export string values

### ISSUE THREAD

**Issue by Wyxaldir** [godotengine/godot#66564] opened 2022-09-28 19:21 UTC
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

When using the new @export_enum you cannot assign a value of String to the variable like you should be able to (according to the docs).

### Steps to reproduce

Add a script to a node with the following code:
`@export_enum("A", "B", "C") var my_string : String`
You will get the error "@export_enum" annotation requires a variable of type "int" but type "String" was given instead.".

**Comment by KoBeWi** [comment] 2022-09-28 20:55
Duplicate of #54828

**Closed by KoBeWi** 2022-09-28 20:55 UTC
