### ISSUE TITLE
[godot 4.0 beta.10~13]A bug about text editor parsing.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#71668] opened 2023-01-19 11:01 UTC
### Godot version

4.0 Beta 10~13

### System information

Window10

### Issue description

This is an unexpected malignant bug, which will **crash directly** when you export the release version on your PC.
![1](https://user-images.githubusercontent.com/52338846/213424627-b5c42b61-d6f3-4b29-9aae-b368e7198339.PNG)
If you don't add "return ‘expected variable type’" at the end of the function, it will crash in the release version.
![2](https://user-images.githubusercontent.com/52338846/213425647-feb209fe-423d-464f-b799-650fe6efabfa.PNG)

But if you add "return expected variable type" at the end of the function, it will notify Unreachable code.
![3](https://user-images.githubusercontent.com/52338846/213425657-1799a456-07e8-410e-b802-2c6d121ac0e5.PNG)

### Steps to reproduce

略

### Minimal reproduction project

略

**Comment by akien-mga** [comment] 2023-01-19 11:11
Duplicate of #71577

**Closed by akien-mga** 2023-01-19 11:11 UTC
