### ISSUE TITLE
Godot 4.0.alpha15 : iOS app keep crashing on startup

### ISSUE THREAD

**Issue by luxmargos** [godotengine/godot#65234] opened 2022-09-02 07:36 UTC
### Godot version

4.0.alpha15

### System information

macOS 12.3.1, Rx560, Vulkan(MoltenVK), iPhone7 (MN8X2KH/A), iOS 15.6.1

### Issue description

Hello, I'm in testing on several godot4 versions. Including alpha13,14,15 and custom builds. Unfortunately, no succeed for ios till now.

Here is the log messages when I start the iOS app which exported through godo4.alpha.15, even same output other alpha versions.

Is the iOS platform not yet ready? Or is there something I missed?

I love godot engine. Please give me advice.

```text
2022-09-02 15:34:20.913424+0900 gd4-app[12542:420301] Metal GPU Frame Capture Enabled
2022-09-02 15:34:20.913671+0900 gd4-app[12542:420301] Metal API Validation Enabled
*********** main.m
running app main
2022-09-02 15:34:21.059753+0900 gd4-app[12542:420301] Warning: Unable to create restoration in progress marker file
Path: /var/containers/Bundle/Application/70C5A51F-02EC-4BC8-ADDB-EC8316430E3A/gd4-app.app
godot_ios /var/containers/Bundle/Application/70C5A51F-02EC-4BC8-ADDB-EC8316430E3A/gd4-app.app/gd4-app
cwd /private/var/containers/Bundle/Application/70C5A51F-02EC-4BC8-ADDB-EC8316430E3A/gd4-app.app
os created
2022-09-02 15:34:21.065358+0900 gd4-app[12542:420301] USER ERROR: Condition "!configured" is true.
2022-09-02 15:34:21.065422+0900 gd4-app[12542:420301]    at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
USER ERROR: Condition "!configured" is true.
   at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
...
...
...
2022-09-02 15:34:21.071958+0900 gd4-app[12542:420301] USER ERROR: Class  already has a method .
2022-09-02 15:34:21.071981+0900 gd4-app[12542:420301]    at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
USER ERROR: Class  already has a method .
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
2022-09-02 15:34:21.072034+0900 gd4-app[12542:420301] USER ERROR: Condition "!configured" is true.
2022-09-02 15:34:21.072059+0900 gd4-app[12542:420301]    at: StringName (core/string/string_name.cpp:267) - Condition "!configured" is true.
USER ERROR: Condition "!configured" is true.
   at: StringName (core/string/string_name.cpp:267) - Condition "!configured" is true.
...
...
2022-09-02 15:34:21.074308+0900 gd4-app[12542:420301] USER ERROR: Class  already has a method .
2022-09-02 15:34:21.074350+0900 gd4-app[12542:420301]    at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
USER ERROR: Class  already has a method .
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
...
...
...
2022-09-02 15:34:21.154268+0900 gd4-app[12542:420301] USER ERROR: Class '' already has signal ''.
2022-09-02 15:34:21.154290+0900 gd4-app[12542:420301]    at: add_signal (core/object/class_db.cpp:790) - Condition "check->signal_map.has(sname)" is true.
USER ERROR: Class '' already has signal ''.
   at: add_signal (core/object/class_db.cpp:790) - Condition "check->signal_map.has(sname)" is true.
2022-09-02 15:34:21.154326+0900 gd4-app[12542:420301] USER ERROR: Condition "!configured" is true.
2022-09-02 15:34:21.154594+0900 gd4-app[12542:420301]    at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
USER ERROR: Condition "!configured" is true.
   at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
...
...
...
2022-09-02 15:34:21.169085+0900 gd4-app[12542:420301] USER ERROR: Condition "!configured" is true.
2022-09-02 15:34:21.169366+0900 gd4-app[12542:420301]    at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
USER ERROR: Condition "!configured" is true.
   at: StringName (core/string/string_name.cpp:327) - Condition "!configured" is true.
2022-09-02 15:34:21.169408+0900 gd4-app[12542:420301] USER ERROR: Class  already has a method .
2022-09-02 15:34:21.169432+0900 gd4-app[12542:420301]    at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
USER ERROR: Class  already has a method .
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
setting data dir to /var/mobile/Containers/Data/Application/C6D2B158-74EB-4251-93DA-AC9921F39FD7/Documents from /var/mobile/Containers/Data/Application/C6D2B158-74EB-4251-93DA-AC9921F39FD7/Documents
2022-09-02 15:34:21.187947+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.188030+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.188526+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.188593+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
...
...
...
setup 0
2022-09-02 15:34:21.231024+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.231100+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
******** setting up keyboard input view
******** adding observer for keyboard show/hide
start animation!
2022-09-02 15:34:21.309411+0900 gd4-app[12542:420301] USER ERROR: AudioOutputUnitStart failed, code: -50
2022-09-02 15:34:21.309554+0900 gd4-app[12542:420301]    at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:251) - AudioOutputUnitStart failed, code: -50
USER ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:251) - AudioOutputUnitStart failed, code: -50
2022-09-02 15:34:21.327620+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.327742+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.329585+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.329648+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
...
...
...
2022-09-02 15:34:21.576546+0900 gd4-app[12542:420301] Vulkan API 1.1.216 - Using Vulkan Device #0: Apple - Apple A10 GPU
Vulkan API 1.1.216 - Using Vulkan Device #0: Apple - Apple A10 GPU
2022-09-02 15:34:21.583300+0900 gd4-app[12542:420301] fopen failed for data file: errno = 2 (No such file or directory)
2022-09-02 15:34:21.583384+0900 gd4-app[12542:420301] Errors found! Invalidating cache...
2022-09-02 15:34:21.917764+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.917847+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.918336+0900 gd4-app[12542:420301] USER ERROR: Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:21.918408+0900 gd4-app[12542:420301]    at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
USER ERROR: Condition "!classes.has(ti.inherits)" is true.
   at: _add_class2 (core/object/class_db.cpp:402) - Condition "!classes.has(ti.inherits)" is true.
2022-09-02 15:34:22.098801+0900 gd4-app[12542:420476] fopen failed for data file: errno = 2 (No such file or directory)
2022-09-02 15:34:22.098889+0900 gd4-app[12542:420476] Errors found! Invalidating cache...
2022-09-02 15:34:26.492816+0900 gd4-app[12542:420476] validateWithDevice, line 3718: error 'Render Pipeline Descriptor Validation
No valid pixelFormats set.
'
validateWithDevice:3718: failed assertion `Render Pipeline Descriptor Validation
No valid pixelFormats set.
'
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
validateWithDevice:3718: failed assertion `Render Pipeline Descriptor Validation
No valid pixelFormats set.
'
(lldb) 
```

### Steps to reproduce

* Create simple godot-project
* Export to iOS with godot4.0.alpha15-template
* Build and run on iOS Device

### Minimal reproduction project

[gd4.alpha15.project.zip](https://github.com/godotengine/godot/files/9475767/gd4.alpha15.project.zip)

**Comment by Calinou** [comment] 2022-09-02 15:54
Duplicate of https://github.com/godotengine/godot/issues/64471.

**Closed by Calinou** 2022-09-02 15:54 UTC

**Comment by SnailRabbids** [comment] 2023-05-27 12:52
Hi @Calinou @luxmargos,
I have the same errors as you in your logs:
"2022-09-02 15:34:22.098801+0900 gd4-app[12542:420476] fopen failed for data file: errno = 2 (No such file or directory)
2022-09-02 15:34:22.098889+0900 gd4-app[12542:420476] Errors found! Invalidating cache..."

It appears ONLY on first run. Do you have an idea why it happens? Do I need to do something with it?
