### ISSUE TITLE
Vulkan: Editor hangs up after enabling "Use Two Bounces" in GI Probe 

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#44998] opened 2021-01-07 19:19 UTC
**Godot version:**
[c7b4514](https://github.com/godotengine/godot/commit/c7b45141de9538e06dee0f4fd7799ff75d5f4eff)

**OS/device including version:**
Windows 10 / Nvidia GeForce GTX 1080 Ti (457.30) / Vulkan

**Issue description:**
Editor hangs up after enabling "Use Two Bounces" in GIProbeData and baking GI probe.
<details>
    <summary>Error in console</summary>

> ERROR: Condition "page_pool == nullptr" is true.
>    at: PagedArray<class RID>::push_back (D:\a\godot\godot\core/templates/paged_array.h:186)
> ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
>    at: VulkanContext::prepare_buffers (drivers\vulkan\vulkan_context.cpp:1237)
> ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
>    at: VulkanContext::swap_buffers (drivers\vulkan\vulkan_context.cpp:1300)

</details>

**Steps to reproduce:**
1. Add GI Probe to scene
2. Check "Use Two Bounces" in GIProbeData
3. Bake GI Probe

**Minimal reproduction project:**
[Here](https://github.com/godotengine/godot/files/5783948/GIProbeTest.zip)

**Comment by Calinou** [comment] 2021-01-07 20:42
@Xartorx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Xartorx** [comment] 2021-01-07 21:06
@Calinou [Done](https://github.com/godotengine/godot/files/5783948/GIProbeTest.zip)

**Comment by novemberist** [comment] 2021-01-08 04:31
I have a similar issue. My editor and subsequently whole computer will suddenly and increasingly slow down whenever I bake the GI Probe and eventually freete (only if there is at least one mesh with "dynamic" gi property present in the scene)

This is independent of the "use two bounces" checkbox though.

Sounds like a memory leak or infinite loop somewhere to me.

**Comment by Calinou** [comment] 2021-08-08 16:01
@Xartorx @novemberist Can you still reproduce this in the latest `master` branch or nightly builds?

**Comment by Xartorx** [comment] 2021-08-08 16:43
@Calinou yes, still crashes, but now with different error:

<details>
<summary>
Error:
</summary>

```
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (.\servers/rendering/renderer_rd/pipeline_cache_rd.h:75)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7277)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7294)
```

and

```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::swap_buffers (drivers\vulkan\vulkan_context.cpp:1853)
ERROR: Attempted to use an unused shader variant (shader is null),
   at: (.\servers/rendering/renderer_rd/pipeline_cache_rd.h:75)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7277)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7294)
ERROR: Vulkan: Did not create swapchain successfully.
   at: (drivers\vulkan\vulkan_context.cpp:1777)
```

</details>

Version: v4.0.dev.custom_build [73cd3f0b3]

**Comment by Calinou** [comment] 2022-01-31 12:36
I can't reproduce this on `master` fc09d783f (Linux, NVIDIA 495.46), closing.

https://user-images.githubusercontent.com/180032/151794846-07014edc-6049-4449-a15b-c13c5ea1c351.mp4

**Closed by Calinou** 2022-01-31 12:36 UTC
Labels: bug, topic:rendering, topic:editor
