### ISSUE TITLE
Script editor no longer updates when the file was modified on disk

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#21168] opened 2018-08-19 00:05 UTC
Godot master ff8e6f920cd99954c3394412713950c1195199f2
Windows 10 64 bits

Reproduction steps:
1) Open a project with a script inside
2) Open the script in Godot
3) Open the script from another text editor, modify it and save it
4) Go back to Godot: notice the script does not update.

This worked in 3.0.6.
I found it while working on #21166, as it also prevents open files from updating as well. Find in Files actually *does* tell the script editor to update, but even that has no effect.

Note: my dev Godot binary is in the `C:` drive, but my test project is in the `D:` drive, in case that eventually matters.

**Comment by Paulb23** [comment] 2018-09-15 19:08
Duplicate of #21956, fixed by #22069

**Closed by Paulb23** 2018-09-15 19:08 UTC
Labels: bug, topic:gdscript
