### ISSUE TITLE
Named Addon Classes which Extend Resource not added to ClassDB 

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#36534] opened 2020-02-25 15:06 UTC
**Godot version:**
3.2

**OS/device including version:**
Win 10

**Issue description:**
Named Classes using class_name are not added to the ClassDB (and thus can't be created using the editor interface) if they are contained within `res://addons` and extend `Resource`

Classes which extend Resource outside of the folder are registered as expected. As are classes in the folder which extend Reference or Object.

**Steps to reproduce:**
Create a Named GDScript Class file which extends Resource and place it in a subdirectory within res://addons

**Minimal reproduction project:**

**Comment by TheDuriel** [comment] 2020-02-25 15:08
If this is intentional, then _all_ uses of class_name within res://addons should be ignored. And not just resources.

**Comment by Calinou** [comment] 2020-04-05 21:16
Duplicate of #30048.

**Closed by Calinou** 2020-04-05 21:16 UTC
