### ISSUE TITLE
Cant count more than 70k in 2.1

### ISSUE THREAD

**Issue by blankonn** [godotengine/godot#6083] opened 2016-08-09 08:27 UTC
Ubuntu gnome 64bit ; 2.1 rc1

**Issue description** (what happened, and what was expected): the result variable is stuck in 63516, what I expected is... A lot of number ?

Reproduce using this code:

extends Node2D

var test = 1000
var result = 1

func _ready():
	set_process(true)
	pass

func _process(delta):
	while ( test > 1):
		result = result * test
		test -= 1
	print (result)

*Soon*

**Comment by akien-mga** [comment] 2016-08-09 08:31
It would be nice if you could write real code and not pseudo code, obviously the snippet you gave won't run in Godot.

**Comment by Sslaxx** [comment] 2016-08-09 09:28
I'm not entirely sure what this guy was asking about, but https://dl.dropboxusercontent.com/u/67740160/Issue_6083_Results.txt is the result of creating a test like the one he appears to have.

**Comment by akien-mga** [comment] 2016-08-09 09:30
Thanks for checking @Sslaxx, it was also my understanding that integers in Godot (at least on x86) should be in the range [-2^31;2^31].

**Comment by blankonn** [comment] 2016-08-09 09:47
here's what I mean :
![selection_012](https://cloud.githubusercontent.com/assets/16377781/17512187/e22e7510-5e50-11e6-92c1-44e3a945ef04.png)

**Comment by Sslaxx** [comment] 2016-08-09 09:49
@blankonn - this issue has been reported before, though I can't remember the issue number at the moment.

**Comment by akien-mga** [comment] 2016-08-09 10:44
I believe this might have been fixed already in Godot 2.1 RC2 with #5900.

**Comment by bojidar-bg** [comment] 2016-08-09 10:48
I think this is a duplicate of #5867

**Comment by akien-mga** [comment] 2016-08-09 10:50
Indeed.

**Closed by akien-mga** 2016-08-09 10:50 UTC
Labels: bug, topic:core
