### ISSUE TITLE
Adding New SpriteFrames to AnimatedSprite doesn't automatically open the SpriteFrames panel

### ISSUE THREAD

**Issue by NelloDev** [godotengine/godot#32895] opened 2019-10-17 17:01 UTC
**Godot version:**
3.2.alpha.custom_build.119bf2372

**OS/device including version:**
5.3.6.arch1-1

**Issue description:**
The [docs](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#sprite-animation) say that adding a "New SpriteFrames" to the Frames property of AnimatedSprite should automatically open the SpriteFrames panel but this doesn't happen. You need to click on the Frames "SpriteFrames" property for the panel to open.

Selecting another node in the Scene and then returning to the AnimatedSprite node automatically opens the SpriteFrames panel so I'm assuming the panel is still intended to open and that it not opening automatically isn't an intentional change in 3.2

update: removing the SpriteFrames property and re-adding it opens the SpriteFrames panel as described in the docs https://streamable.com/oc5jm

**Steps to reproduce:**
1. In the Scene panel select the AnimatedSprite node
2. In the Inspect panel find the Frames property and click "[empty]" -> "New SpriteFrames"

**Minimal reproduction project:**
[YourFirstGame.zip](https://github.com/godotengine/godot/files/3740451/YourFirstGame.zip)

**Comment by KoBeWi** [comment] 2019-10-17 17:27
Was it ever behaving like that? I tried in 3.0 and it's the same. Maybe it's just outdated documentation.

**Comment by NelloDev** [comment] 2019-10-17 17:54
Oh, well, I guess it did at one point! And in my mind it makes sense because any other time you select the AnimatedSprite node with a "SpriteFrames" Frames property it automatically opens the SpriteFrames panel. I suppose either making it open the panel or updating the docs telling the reader to click the property to open the panel would work

**Comment by NelloDev** [comment] 2019-10-17 18:02
Are you sure? If the docs are right it's an engine issue but if the docs are wrong then it's a doc issue. They could just as easily say "Wait, actually this is an issue for https://github.com/godotengine/godot"

**Comment by KoBeWi** [comment] 2019-10-17 18:10
This could be a doc from Godot 2.1 probably. The inspector was changed once or twice since then and I assume this just wasn't updated.

**Comment by NelloDev** [comment] 2019-10-17 18:28
Or maybe this critical feature was lost in the shuffle (I kid.) It makes sense to me that it would open because it seems someone decided that if the active node is an AnimatedSprite and it has the Frames->SpriteFrames property then the SpriteFrames panel should be open.

Oh and I just did some more testing and it seems that if you clear the SpriteFrames property then re-add it the SpriteFrames panel does open automatically as described in the docs. So maybe it is a bug?

**Comment by NelloDev** [comment] 2019-10-17 18:34
Here's a video showing what I explained in my last comment, I've included it in an udpate to the original issue https://streamable.com/oc5jm

**Comment by codecustard** [comment] 2019-10-19 00:47
I think that it should open automatically. I've noticed this issue in other editors as well (can't remember which one) and if you're new to Godot you wouldn't even know that those panels are even a thing.

**Comment by thiagoamendola** [comment] 2019-10-23 04:40
I'd like to work on this one. 

Should the SpriteFrames panel appear right after creating the AnimatedSprite node or after creating a new SpriteFrames resource?

**Comment by NelloDev** [comment] 2019-10-23 04:43
I believe right afteradding the SpriteFrames to AnimatedSprite because without it you wouldn't need the panel

**Comment by PatrickMassot** [comment] 2021-12-31 13:05
This still isn't fixed in v3.4.2.stable.official.45eaa2daf, and is very confusing for beginners.

**Comment by akien-mga** [comment] 2022-09-20 12:33
This was a problem with the docs, it's intended behavior that it doesn't auto-open when creating the resource.
The docs have been updated accordingly to mention that you have to click the resource to open its editor:
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/02.player_scene.html#sprite-animation

**Closed by akien-mga** 2022-09-20 12:33 UTC
Labels: bug, topic:editor, confirmed, documentation
