### ISSUE TITLE
get_property_list  usage returns 135168 for user_defined property 

### ISSUE THREAD

**Issue by Ehsanwww** [godotengine/godot#84937] opened 2023-11-15 13:07 UTC
### Godot version

4.2 beta 5, 4.2 beta 4

### System information

windows 10

### Issue description

Hello everyone, thanks for your great engine, 
issue is about get_property_list for resources and nodes; i defined some properties inside class and inside that class, i defined some other properties but the issue is when i call  get_property_list , in usage of get_property_list, returns 135168 which is not valid. 

### Steps to reproduce

```gdscript
func return_node_property_mine(_resource)->Array:
	var list:Array = _resource.get_property_list()
	
	print("list:",list)	
	print("#########")
	var filter_list = []
	for i in list:
			if(i["usage"])==4096:
				filter_list.append(i)
```
================

### Minimal reproduction project
```gdscript
func return_node_property_mine(_resource)->Array:
	var list:Array = _resource.get_property_list()
	
	print("list:",list)	
	print("#########")
	var filter_list = []
	for i in list:
			if(i["usage"])==4096:
				filter_list.append(i)
	return filter_list
```

**Comment by Calinou** [comment] 2023-11-15 13:09
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by kleonc** [comment] 2023-11-16 16:55
> in usage of get_property_list, returns 135168 which is not valid.

It is valid, usage is composed of different [PropertyUsageFlags](https://docs.godotengine.org/en/4.1/classes/class_%40globalscope.html#enum-globalscope-propertyusageflags) bit flags. To check whether the given flag is set use `&` bitwise AND operator.

```
135168 == (131072 + 4096) ==  (PROPERTY_USAGE_NIL_IS_VARIANT | PROPERTY_USAGE_SCRIPT_VARIABLE)
```
```gdscript
for property_info in obj.get_property_list():
	if property_info.usage & PROPERTY_USAGE_SCRIPT_VARIABLE:
		...
```

No bug here, not sure if some docs need clarification.

**Comment by YuriSizov** [comment] 2023-11-16 17:29
Thanks for the explanation, kleonc. Closing as not a bug.

**Closed by YuriSizov** 2023-11-16 17:29 UTC
Labels: topic:core
