### ISSUE TITLE
Renaming/Moving Files Should Also Update AutoLoad Tab

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#19401] opened 2018-06-07 03:25 UTC
I think that when you rename or move a file, the autoloaded node paths should be updated as well. Currently when you rename or move autoloaded scenes and scripts, you have to re-add them in the AutoLoad tab.

**Comment by KoBeWi** [comment] 2018-07-31 15:16
Ah, I was annoyed each time I wanted to change Autoload path and found out that I have to remove it and re-add. I wanted to suggest adding patch changing, but then realized I need it only when moving file, so fixing this issue would work for me too.

**Comment by akien-mga** [comment] 2018-11-08 14:54
Duplicate of #22995, fixed by #23000.

**Closed by akien-mga** 2018-11-08 14:54 UTC
Labels: enhancement, topic:editor, usability
