### ISSUE TITLE
Loading resources from user://

### ISSUE THREAD

**Issue by Hubber116sx** [godotengine/godot#18367] opened 2018-04-22 21:50 UTC
An error from https://github.com/godotengine/godot/issues/2319 is occurring in Godot 3.0.2. This error does not occur when loading a tscn file.

ERROR: _load: No loader found for resource: user://icon.png
   At: core/io/resource_loader.cpp:186.

**Comment by PJB3005** [comment] 2018-04-23 08:15
I may be wrong here but isn't the problem here that loading an image like that when it's not imported by the editor doesn't work? The resource loader tries to load `SteamTextures` which don't exist for `user://`. You could try using `ImageTexture` I believe.

**Comment by LinuxUserGD** [comment] 2018-04-23 09:59
func load_jpg(file):

	var jpg_file = File.new()

	jpg_file.open(file, File.READ)

	var bytes = jpg_file.get_buffer(jpg_file.get_len())

	var img = Image.new()

	var data = img.load_jpg_from_buffer(bytes)

	var imgtex = ImageTexture.new()

	imgtex.create_from_image(img)

	jpg_file.close()

	return imgtex


func load_png(file):

	var png_file = File.new()

	png_file.open(file, File.READ)

	var bytes = png_file.get_buffer(png_file.get_len())

	var img = Image.new()

	var data = img.load_png_from_buffer(bytes)

	var imgtex = ImageTexture.new()

	imgtex.create_from_image(img)

	png_file.close()

	return imgtex

**Comment by LinuxUserGD** [comment] 2018-04-23 10:10
#17748

**Comment by bojidar-bg** [comment] 2018-04-23 10:37
Yes, looks like a duplicate of #17848 indeed. Closing.

**Closed by bojidar-bg** 2018-04-23 10:37 UTC
