### ISSUE TITLE
nodes assigned to an instance "add_control_to_container" always return null

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#88296] opened 2024-02-13 20:27 UTC
### Tested versions

Godot_v4.2.1-stable_win64

### System information

windows 10 vulkan foward+

### Issue description

nodes inside an instance always return nil when assigned to a control_container.
"res://addons/tiletest/tiletest.gd:101 - Invalid set index 'text' (on base: 'Nil') with value of type 'String'."

The error follows into the next line of code, if check for =! null
" res://addons/tiletest/tiletest.gd:107 - Invalid get index 'position' (on base: 'Nil')."

### Steps to reproduce

- create a plugin / @tool / extends EditorPlugin
- on func _enter_tree():
- load an instance, and add it to "add_control_to_container"
- add the instance nodes to variable
- access the nodes values
- enable the plugin in project settings
- restart godot

### Minimal reproduction project (MRP)

[tilePlugTest.zip](https://github.com/godotengine/godot/files/14271778/tilePlugTest.zip)

**Comment by kleonc** [comment] 2024-02-13 23:28
Fix/don't ignore your errors. After enabling the plugin:

```
res://addons/tiletest/tiletest.gd:45 - Cannot call method 'get_viewport' on a null value.
```

The error is caused by this line:

```gdscript
	get_editor_interface().get_edited_scene_root().get_viewport().add_child(dockedEditorDraw)
```
`get_edited_scene_root()` can return `null`.
This line failing like that makes all the subseqent lines in `_enter_tree()`:
```gdscript
	subVcont = dockedScene.get_node("SubViewportContainer");
	subVport = dockedScene.get_node("SubViewportContainer/SubViewport");

	label1 = dockedScene.get_node("Label");
	label2 = dockedScene.get_node("Label2");

	img = dockedScene.get_node("SubViewportContainer/SubViewport/Icon");
	camTl = dockedScene.get_node("SubViewportContainer/SubViewport/Camera2D");
	blk = dockedScene.get_node("Blk");
	blk2 = dockedScene.get_node("Blk2");
```
never execute. So all warnings are correct as your `label1`, `label2`, etc. are indeed null.

No bug in here, closing.

**Closed by kleonc** 2024-02-13 23:28 UTC

**Comment by jonSP12** [comment] 2024-02-14 08:29
but that is impossible... I cant check for null on enter tree, func ready is the same thing...
"get_editor_interface().get_edited_scene_root().get_viewport()" its part of the editor, also cant check for null there ?

The error goes away if godot is started with the plugIN off, or by turning it off and on.... So i dont understand whats going on ?

**Comment by jonSP12** [comment] 2024-02-14 09:07
fixed "get_editor_interface().get_edited_scene_root()" can be checked for null()

```
func _physics_process(delta):
	if not is_instance_valid(dockedScene) || dockedScene.visible == false || get_editor_interface().get_edited_scene_root() == null:
		return;
```
