### ISSUE TITLE
[3.x][GDScript] Autocomplete doesn't use the correct type for onready variables when assigned

### ISSUE THREAD

**Issue by Macksaur** [godotengine/godot#61978] opened 2022-06-12 21:23 UTC
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Windows 10

### Issue description

When assigning an initializer to an onready variable such as `= get_node(...)` type information appears to be lost and the variable is retyped as a `Node` type.

This prevents using autocomplete and is really frustrating.

### Steps to reproduce

```gdscript
class Test:
	extends Node2D
	
	var member

# this expression appears to retype test2 as a Node due to get_node()
onready var test2:Test = get_node("not real")

# NOTE: autocomplete works fine if you comment out: = get_node(...)
#onready var test2:Test

func _ready() -> void:
	test2.mem # <- ERROR can't autocomplete (Test.member)
	test2.pos # <- ERROR can't autocomplete (Node2D.position)
	test2.filename # OK (Node.filename)

	var test:Test
	test.member # OK, can autocomplete (Test.member)
	test.position # OK (Node2D.position)
	test.filename # OK (Node.filename)
```

**Comment by KoBeWi** [comment] 2022-06-13 00:02
Duplicate of #39228
You can use `onready var test2 := get_node("not real") as Test` as a workaround.

**Closed by KoBeWi** 2022-06-13 00:02 UTC
