### ISSUE TITLE
TileSetEditor causes resize error

### ISSUE THREAD

**Issue by Sputnik-7** [godotengine/godot#46523] opened 2021-02-28 19:48 UTC
**Godot version:**

Godot_v3.2.4-rc3_win64.exe

**OS/device including version:**

Windows 7 Home Premium 64 bits

GPU: Intel HD Graphics 3000
CPU: Intel (R) Core(TM) i3-2330M CPU @2.20GHz

GLES2

**Issue description:**

In the lower panel when I open the TileSet Editor the Node Dock positioned on the right of the screen is resized incorrectly.
I have to close the editor anyway and manually resize the screen to get it fixed.
I seem to have noticed this same error working with other editors and other versions of Godot.

**Steps to reproduce:**

You just have to create a new Tile Set in any project, open the TileSet Editor and click on the image to start editing; for example adding collisions and then it resizes badly.

Attached image:
![Godot 3-2-4 RC3 error](https://user-images.githubusercontent.com/58500577/109431224-21b5d080-79e4-11eb-9304-88a6c8ecdd11.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2021-02-28 20:33
Duplicate of https://github.com/godotengine/godot/issues/31133.

**Closed by Calinou** 2021-02-28 20:33 UTC
