### ISSUE TITLE
Mouse click has a weird behaviour ?

### ISSUE THREAD

**Issue by Kadhel** [godotengine/godot#9450] opened 2017-06-30 09:41 UTC
**Operating system or device - Godot version:**
- Windows 7 Pro, Service Pack 1
- 64 bits
- Godot_v2.1.3-stable_win64

**Issue description:**
I noticed a problem with the buttons (and scrollbars) and the mouse inputs.
Actually, when you hold another mouse button than the left button (so, right button, wheel button, etc), then you press the left click, then you release the other button, and finally you release the left click, the button appears pressed but is not considered as pressed.
Same problem for the scrollbar buttons.
(Note that the problem happens also when you hold two other buttons than the left)
It's something which happens very rarely (I discovered it by accident), but it can happen with all Godot's buttons (including these in the editor).

**Steps to reproduce:**
- Press Right-click with mouse over a button and hold it
- Press Left-click and hold it, with the previous right-click holded.
- Release Right-Click
- Release Left-Click
(It also works with the wheel-click instead of Right-Click)

Thanks !

**Comment by Zylann** [comment] 2017-06-30 12:21
Reproduced in the project manager of Godot 2.1.3. Works with almost anything: scrollbars, buttons, drop downs.

**Comment by vnen** [comment] 2017-06-30 14:18
Does this happens in other OS?

**Comment by willnationsdev** [comment] 2017-07-02 23:22
I just tried this in Windows 10 with Godot 3.0 pre-alpha. Can confirm it's happening here as well.

Also, the button_down event fires, but not the button_up, button_pressed, or button_toggled events.

**Comment by lexum0** [comment] 2017-07-04 14:14
Can confirm in macOS, same behavior

**Comment by kubecz3k** [comment] 2018-04-03 11:21
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment] 2018-04-03 12:52
This clicking repro is a similar story to this one: https://github.com/godotengine/godot/issues/14373#issuecomment-350515100

**Comment by akien-mga** [comment] 2018-05-29 08:47
#14373 and related issues were fixed recently in the master branch. Is this one still valid, or fixed too?

**Comment by bojidar-bg** [comment] 2018-09-23 18:49
Can reproduce on 3.0.5's project manager, Import button, following steps in the OP. Cannot reproduce on the Tabs.

**Comment by Anutrix** [comment] 2019-06-26 15:53
Couldn't reproduce the issue on master eeee1dc73e6344a5541ee323b6ae61744b3348b6 and 3.1.1 stable.

**Comment by akien-mga** [comment] 2019-06-26 16:02
Indeed, I can reproduce it with a current build from the `3.0` branch, but it's fixed in the `3.1` branch and master.

**Closed by akien-mga** 2019-06-26 16:02 UTC
Labels: bug, topic:core, usability
