### ISSUE TITLE
Exported variables reset to their default values in all scene instances when the variable name in the source is changed

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#62643] opened 2022-07-02 18:22 UTC
### Godot version

Godot 3.4.4 and previous versions, Godot 3.5 RC5, Godot 4.0 Alpha11

### System information

Win Nidea 765M

### Issue description

If the name of an exported variable is changed, the value of this export variable _in all instances_ of this scene are reset.

This can be detrimental to a project since the behaviour of an instance is often set and determent by it's exported variables. This is often missed and only many commits later discovered (if at all), leading to lot's of time wasted on pointless bug hunting.

I often come across people in the community channels [going through the same thing](https://www.reddit.com/r/godot/comments/vkm5r9/comment/idq5qxo/?utm_source=share&utm_medium=web2x&context=3). Often the reasons why this happens are not obvious which can lead to lot's of insecurity and confusion, especially for beginners.

Possibly related:
https://github.com/godotengine/godot/issues/43659
https://github.com/godotengine/godot/issues/45337
https://github.com/godotengine/godot/issues/46103 # very similar, however this one is about changing the type, not the name
https://github.com/godotengine/godot/issues/43402

### Steps to reproduce

1. create a main scene
2. create another original scene
3. add export variable to original scene 
4. instance original scene in main scene
5. set exported variable of instances in main scene to unique values per instance
6. change exported variable name in original scene and save
7. observe all instances in main scene having their exported variable value reset to default

### Minimal reproduction project

Godot 3.X:
[export_var_name_change_bug_G3.zip](https://github.com/godotengine/godot/files/9033416/export_var_name_change_bug_G3.zip)

Godot 4.0 Alpha11:
[exported_variable_name_change_bug_G4_Alpha11.zip](https://github.com/godotengine/godot/files/9033418/exported_variable_name_change_bug_G4_Alpha11.zip)

**Comment by akien-mga** [comment] 2022-07-02 19:19
That's a necessary design constraint of the whole system, I don't see how it could happen otherwise? If you rename an exported variable, you "break compat" with your own framework and thus the previous name doesn't exist anymore. Existing scenes that have a value saved for the old name won't know what to assign it to and it will be dropped.

Possibly it could show an error dialog when you open or save such a scene and tell you that `some_var` with value `42` doesn't seem to correspond to any builtin or exported variable, and ask you if you want to assign this value to another builtin or exported variable. But that could be quite tedious and make e.g. opening `3.x` scenes in 4.0 a hassle.

**Comment by golddotasksquestions** [comment] 2022-07-02 19:41
Idk what the best solution is for this from the core perspective, I just know that this is quite a massive issue from a user perspective who is not aware about this.

Personally I would want and expect the values of my instanced scenes to stay the same. After all I changed the name in the source scene, not the value. But I also understand what you are saying how Godot currently does not seem to have a way to know or differentiate this name change to someone completely removing an existing exported variable and create a totally new one. How should Godot know one is the same as the other while something else is not?

The only option I can think of right now is by allowing the user to right-click on the exported variable _in the Inspector_ and then click "Rename variable in all it's instances", and then Godot collecting all the files in which this node is used, temporarily store the individual value those individual instances, rename the in the source script file, then apply the temporary stored values to the individual instances variable with the new name.

**Comment by AThousandShips** [comment] 2022-07-02 19:59
I don't really see how this is an issue someone with experience in programming etc. would not be aware of, but I could see a reason to pop up a warning when changing a script with "this will make instances of this script lose track of this value/break compatibility", but otherwise this isn't something I have seen ever be something that software or tools really had systems for

But I can imagine a solution as follows, as part of a tool for the editor specifically just to fix/update instances:
* Fetch all instances of this script
* Load their properties and locate the property being renamed
* Write back with the property renamed

This would have to be done specifically from the editor when changing the script as otherwise you could get into really confusing territory by having conflicting renames, for example:
* Rename `property_a` to `property_b`
* Create new `property_a`
* Rename `property_a` to `property_c`

If the fixing of this would happen on opening rather than when a command is invoked this would require the editor to know when in this sequence the file was originally saved, or it would rename some original `property_a` to `property_c` when they should in fact be `property_c`, etc.

**Comment by AThousandShips** [comment] 2022-07-02 20:14
My suggestion for that if it would be something to implement would be to add a function to ResourceLoader, basically like `rename_dependencies` but for properties in scripts, which renames any instance of property X in a node/resource which has a script that inherits from a script Y

**Comment by golddotasksquestions** [comment] 2022-07-02 20:28
I think any of those options would be an improvement. Right now this value reset is completely silent. I think at the very least a warning is needed to let users know when they change exported variable names, they will lose the value of this variable in all existing instances. To you and other expert programmers this may be so obvious they have not even be reminded about it. I on the other hand know about all this too well since years (because I have lost a lot of data this way), but I still regularly forget about it and kill my data. This happened so often now I just avoid export variables altogether.

**Comment by AThousandShips** [comment] 2022-07-02 20:32
I'm sorry I didn't mean to say it was obvious, I only meant it to say I wouldn't consider it a bug as such

**Comment by kakatoto-collab** [comment] 2022-07-03 05:21
I use Godot C# 3.5.

Yes it is really a problem when you are making a game with a lot of custom resources. At first, I was seeing this custom resource system as an opportunity to gain time by avoiding passing datas by code but  since changing name of exported varaible reset the values, I am now wasting a lot of time with this feature. Also another problem close to this one : when you have an exported enum, if you add a constant to your enum, then all the enum will be disturbed in the custom resources.

I dont know how Godot internally handles this but it seems that this system should work with references rather than with values.

**Comment by AThousandShips** [comment] 2022-07-03 06:19
> I dont know how Godot internally handles this but it seems that this system should work with references rather than with values.

Are you talking about resources open in the editor currently? Because otherwise I don't see how references matter? Have you looked at how scene and resource files are laid out in the filesystem and how properties are handled?

**Comment by AThousandShips** [comment] 2022-07-03 07:23
So as an immediate solution to this for anyone who suffers from this would be to simply rename the properties in the files affected by an external text editor (requires them to be saved in text format .tscn/.tres, but that's the recommended approach if you are using VCS)

**Comment by AThousandShips** [comment] 2022-07-03 07:39
My suggestion for a feature would be:
- Add a context menu option for export variables, "rename variable" which would rename it in all instances (and possibly in this same script, doing it across all other scripts is far more involved)
- Make script editor track all exported variables on most recent save/load and have it warn when one is lost
- Have it prompt the user when saving with one of these warnings unresolved, to preclude this being missed
- Add a function to the ResourceLoader akin to `rename_dependencies` taking a `HashMap<Pair<String,String>,String> renaming property X in class Y (or any inheriting from it, could be more involved) to Z

This would be decently complex I think in total but I think most of the underlying steps could be straight forward, my main concern would be that it would require traversing all files in the project as there is no tracking of instances in files from what I know

**Comment by kakatoto-collab** [comment] 2022-07-03 09:14
> Are you talking about resources open in the editor currently? Because otherwise I don't see how references matter? Have you looked at how scene and resource files are laid out in the filesystem and how properties are handled?

Maybe I was unclear but I was talking about custom ressources opened in editor. I was not talking about Godot's reference class.

**Comment by AThousandShips** [comment] 2022-07-03 09:17
I don't see how references would matter here, the access to properties in the editor operates through the get/set functions and not by having a reference to the property, as far as I know there's no way of doing that, properties in the inspector and in the loaded scene are handled by name

**Comment by kakatoto-collab** [comment] 2022-07-03 09:35
Why isnt it possible to track the properties in the inspector and in loaded scenes by reference instead of by name ?

**Comment by AThousandShips** [comment] 2022-07-03 09:58
Firstly a number of types (the builtin primitive types like Vector2/3, Transform2/3D, Basis, etc.) are not handled by reference internally, especially not in GDScript, secondly a lot of properties have special get/set behavior, for example most of the transform related properties in Node3D does some magic on getting and setting, updating dirty transforms etc.

Now one *could* do this by instream having references to the get/set *functions* but that again would not work for GDScript

Further there are properties that simply do not have a dedicated get/set function to reference, nor any value to reference, those provided by get_property_list for example, these can only really be managed by using the functions, with these cases you'd also risk running into a ton of dangling references if you for example remove a track from an animation

I'm not well versed in the deep internals of some of this but as I understand it the use of the property name is the only way that works universally, and provides a straight forward single interface for doing this not having to deal with the various ways this would be solved for different types, for example the difference between a type from C++ and one from GDScript, having very different internals

And in the end this would do nothing to remedy this problem, the exported variable vanishes if you rename it

Further doing any kind of automatic resolution of this would cause bugs of its own, consider this:
```gdscript
@export var A : int
@export var B : int
```
Changing to
```gdscript
@export var B : int
@export var C : int
@export var D : int
```

How should this be resolved automatically, does the user want to rename A to C, or to D, or delete A and just add C and D?

**Comment by AThousandShips** [comment] 2022-07-03 10:07
I see that you work in C# and I haven't touched C# in years and years and perhaps references work differently there

**Comment by kakatoto-collab** [comment] 2022-07-03 10:07
Thanks for your reply, the first part of your answer outperforms my competencies but I can try to answer about the very end : 

In your example with exported variables A and B becoming B, C and D, it is imppossible to know how godot should interpret this by only see the beginning and the end of the process, but  does the fact  those changes are made one after one by the user can help ? For example A becomes C first, then it is moved after B... etc... 

I dont know if scriptable objects are handled better in Unity.

**Comment by AThousandShips** [comment] 2022-07-03 10:14
I mean that's still not reliable, the script editor can't read your mind, what if you delete A, then add C, and then decide to add D to replace A, this is mostly to explain why I think this kind of thing isn't really done much in my experience at least, the risk of misinterpreting the user's intention and making things worse is high

**Comment by kakatoto-collab** [comment] 2022-07-03 10:16
If A is deleted, then A is deleted, there is no problem with that case. Very same for adding C. But if you cut A and paste it, the intended behaviour is that the editor keeps the values you stored before.

**Comment by AThousandShips** [comment] 2022-07-03 10:17
If you cut and paste it nothing changes, does it? Unless you cut it, save the script, and then paste it, and save again?

**Comment by kakatoto-collab** [comment] 2022-07-03 10:21
I you cut it and paster it nothing happens indeed. If you cut it, build the solution (with Godot C") and then paste it and build it again, then the value is reset.

**Comment by AThousandShips** [comment] 2022-07-03 10:23
Like build it in the editor? I haven't used Godot C# so I'm not familiar with the work flow, but why would you do that? What would you expect the engine to do?

**Comment by kakatoto-collab** [comment] 2022-07-03 10:24
Ah, btw, when you cut and paste varaibles in another order, it works ! The values are still there. The only case when it doesnt work is then :
- changing variable name of an exported variable
- adding or removing a constant in en enum, then the exported enum variable is disturbed

**Comment by AThousandShips** [comment] 2022-07-03 10:28
The second is a separate issue #56000

The thing with the cut, build, paste thing is that there's no variable with that name in between, I don't see how that would work, nor why it would be expected to work?

**Comment by kakatoto-collab** [comment] 2022-07-03 10:29
Actually it already works, see my previous post.

**Comment by AThousandShips** [comment] 2022-07-03 10:30
Okay! I wasn't sure what you meant by another order

**Comment by KoBeWi** [comment] 2022-07-03 15:33
The problem is non-existent if you use a VCS in your project (even offline).

Also there is a proposal that would solve this problem:
https://github.com/godotengine/godot-proposals/issues/3152

**Comment by akien-mga** [comment] 2022-07-03 16:24
> The problem is non-existent if you use a VCS in your project (even offline).

I wouldn't say non-existent, as you still need to be tech savvy enough to:
- Notice in your diffs that you're losing data
- Retrieve it manually before committing / from an old commit when you lost it

But yeah, it helps a lot to recover potential data loss.

> Also there is a proposal that would solve this problem:
https://github.com/godotengine/godot-proposals/issues/3152

I had a feeling from the start that this issue should have been a proposal, and indeed there's one. Let's continue the discussion there. (Folks who commented above, feel free to add/summarize your ideas in that proposal.)

**Closed by akien-mga** 2022-07-03 16:24 UTC
Labels: discussion, topic:core
