### ISSUE TITLE
Mono iOS Deploy - System.EntryPointNotFoundException for SystemNative_GetNonCryptographicallySecureRandomBytes

### ISSUE THREAD

**Issue by DavidJVitale** [godotengine/godot#38810] opened 2020-05-17 21:16 UTC
**Godot version:**
3.2.2-beta2-mono

**OS/device including version:**
OSX 10.15.4
XCode 11.4.1
iPhone 8, iOS 13.4.1

**Issue description:**
Deploying a Mono C# project on iOS with 3.2.2 works fine in the simulator, fails on real device deploy when you "Archive" the project and deploy on physical iOS device via Ad hoc distribution of an `.ipa` file. The application display the loading image, then crashes immediately with this unhandled exception of an apparent linking error:

```
May 17 14:02:26 Davids-iPhone DodgetheCreeps[22461] <Notice>:                   
Unhandled Exception:                                                            
System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.EntryPointNotFoundException: SystemNative_GetNonCryptographicallySecureRandomBytes
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <e8ca3a82b1c44b21ba65f40b11f07643>:0 
  at System.Random.GenerateGlobalSeed () [0x00000] in <e8ca3a82b1c44b21ba65f40b11f07643>:0 
  at System.Random..cctor () [0x00000] in <e8ca3a82b1c44b21ba65f40b11f07643>:0  
   --- End of inner exception stack trace ---                                   
  at Main..ctor () [0x00000] in <928693da75cb4a549db27400f3bb9797>:0            

```

This is reproducible on my personal Godot project, as well as the public sample of "Dodge the Creeps".

Relevant logs:

[Archive Build Log](https://github.com/godotengine/godot/files/4641038/Archive.DodgetheCreeps_2020-05-17T14-06-15.txt)
[idevicesyslog output during crash](https://github.com/godotengine/godot/files/4641028/testcreeps.txt) (I build in cloud and deploy local, so unfortunately no access to USB debugging in xCode...)

**Steps to reproduce:**
1) Using the "Dodge The Creeps" Mono demo project, Export for iOS. Fill in Apple Team ID, identifier, 120x120 icon, etc.
2) Open the exported project in XCode. Optionally run in simulator to assert that it works there. Change device to Build Only Device of `DodgeTheCreeps > Generic iOS Device`, select `Build > Archive`, like his:
    - ![remmina_screenshot-2020-5-17-20:27:19 070641](https://user-images.githubusercontent.com/18691334/82159453-fa21bd00-9842-11ea-845d-2be68144ea48.png)
3) Press "Distribute App" then "Ad hoc distribution"
    - ![remmina_screenshot-2020-5-17-20:27:53 366171](https://user-images.githubusercontent.com/18691334/82159457-060d7f00-9843-11ea-9e09-a9b049772ada.png)
    - Make sure you authenticate to Apple in XCode and have added your device udid in apple developer settings
4) Finish off the distribution process to get your outputed `DodgeTheCreeps.ipa` file. Deploy to your physical iOS device
    - I did this with [libimobiledevice](https://www.libimobiledevice.org/) software by running `ideviceinstaller -i /path/to/DodgeTheCreeps.ipa`
5) After the app installs on your physical iOS device, open the app. You should see the loading screen, then an immediate crash.
    - I parsed captured logs with `idevicesyslog`

**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/mono/dodge_the_creeps with the above steps

**Comment by DavidJVitale** [comment] 2020-05-29 02:07
FYI, just tested again with 3.2.2-beta3--I'm getting the same result with that as well.

**Comment by DavidJVitale** [comment] 2020-06-14 23:08
Just tested again with 3.2.2-rc1--same result

**Comment by neikeq** [comment] 2020-07-31 18:45
For reference, #40633 also includes an example project for reproducing this issue.

**Comment by andy-noisyduck** [comment] 2020-08-04 15:30
So its documented, `Random` is used by `ThreadPool.QueueSegment` internally, and so you can end up running into this when using Tasks (e.g. `Task.Delay` will throw this exception for me).

**Comment by 7sDream** [comment] 2021-02-09 09:48
Reproduce this when export for macOS too, at version `v3.2.3.stable.mono.official`.

<img width="831" alt="Xnip2021-02-09_17-47-42" src="https://user-images.githubusercontent.com/7822577/107345797-eb7ce380-6afe-11eb-9469-612063bd8fc0.png">

**Comment by neikeq** [comment] 2021-05-16 17:56
This was created first but I'm going to close it as duplicate of #40757 because discussion has developed more there.

**Closed by neikeq** 2021-05-16 17:56 UTC
Labels: bug, platform:ios, topic:mono
