### ISSUE TITLE
Building for Android from Windows fails

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6383] opened 2016-09-03 13:57 UTC
**Operating system or device - Godot version:** Windows 10 64-bit (build 14393), Godot Git commit https://github.com/godotengine/godot/commit/ee37c2f4330e9bd247576b5834cd2660cb520e13

I use [this build script](https://gist.github.com/Calinou/44edbd5d9c4a2ac0dbc8f165b8b7f0ce) to compile for Android from Windows. [MinGW-w64](http://mingw-w64.org) 5.4.0 (also tried with 6.2.0), Android SDK (with all required tools) and NDK are installed.

It fails with the following error:

```
=====
In file included from core\math/math_funcs.h:36:0,
                 from core\math/vector3.h:34,
                 from core\math/aabb.h:34,
                 from core/variant.h:36,
                 from core/object.h:33,
                 from core/resource.h:32,
                 from core/script_language.h:32,
                 from modules\visual_script\visual_script.h:4,
                 from modules\visual_script\visual_script.cpp:1:
C:\Users\Hugo\AppData\Local\Android\android-ndk\platforms\android-14\arch-arm\usr\include/math.h:24:0: warning: "__pure2" redefined
 #define __pure2
 ^
In file included from C:\Users\Hugo\AppData\Local\Android\android-ndk\platforms\android-14\arch-arm\usr\include/math.h:20:0,
                 from core\math/math_funcs.h:36,
                 from core\math/vector3.h:34,
                 from core\math/aabb.h:34,
                 from core/variant.h:36,
                 from core/object.h:33,
                 from core/resource.h:32,
                 from core/script_language.h:32,
                 from modules\visual_script\visual_script.h:4,
                 from modules\visual_script\visual_script.cpp:1:
C:\Users\Hugo\AppData\Local\Android\android-ndk\platforms\android-14\arch-arm\usr\include/sys/cdefs.h:198:0: note: this is the location of the previous definition
 #define __pure2 __attribute__((__const__)) /* Android-added: used by FreeBSD libm */
 ^
modules\visual_script\visual_script.cpp: In member function 'virtual bool VisualScript::are_subnodes_edited() const':
modules\visual_script\visual_script.cpp:1124:23: error: 'const class VisualScriptNode' has no member named 'is_edited'
    if (F->get().node->is_edited()) {
                       ^

=====
scons: *** [modules\visual_script\visual_script.android.opt.debug.armv7.neon.o] Error 1
```

Both debug and release mode compilation end with this error.

**Comment by vnen** [comment] 2016-09-03 15:30
Duplicate of #6358. All builds with `tools=no` are failing.

**Closed by vnen** 2016-09-03 15:30 UTC
