### ISSUE TITLE
No mouse input (compiled Godot build from source)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#14483] opened 2017-12-10 00:33 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu Linux 16.04, Ultrabook

**Issue description:**
 When I run the compiled Godot build with libxi-dev package installed, the program doesn't notice any mouse input and crashs immediately

**Steps to reproduce:**
This bug appears on an Ultrabook (Intel computer with touch support) on Ubuntu Linux 16.04
Terminal:
- git clone https://github.com/godotengine/godot.git
- scons p=x11 bits=64 -j 8

Output:

- scons p=x11 bits=64 -j 8
scons: Reading SConscript files ...
Package xi was not found in the pkg-config search path.
Perhaps you should add the directory containing `xi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xi' found
xi not found.. cannot build with touch. Aborting.

- After installing the "xi" package (sudo apt-get install libxi-dev), deleting folder, cloning and compiling:

Output:

- Please, commit your changes or stash them before you can merge.
Aborting
11) 2 FTSC1000:00 2808:5120
Using touch device: FTSC1000:00 2808:5120
WARNING: initialize: XOpenIM failed
   At: platform/x11/os_x11.cpp:227.
WARNING: initialize: XCreateIC couldn't create xic
   At: platform/x11/os_x11.cpp:404.
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile

- Godot runs and crashs by clicking inside the window

**Comment by RandomShaper** [comment] 2017-12-10 01:11
Related/dupe of #14427.

**Closed** 2017-12-10 01:11 UTC
Labels: archived
