### ISSUE TITLE
Cannot access variables of saved resource with flag bundle resources on Android

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#60975] opened 2022-05-12 16:05 UTC
### Godot version

3.4.2

### System information

Android 8

### Issue description

Using ResourceSaver with flag bundle resources on a custom resource and then loading it back, does not seem to work right out of the box. after loading, trying to access any of it's variables will result in an "invalid index" error.
this happens specifically on android.

however, i managed to resolve this error by changing "gdscript export mode" to "text" and now it works fine.
windows and linux do not require this change, is this intended behaviour?

### Steps to reproduce

1- use ResourceSaver to save any custom resource with flag bundle resources on.
2- use resource loader to load it back.
3- try to print any variable of the resource.

**Comment by Calinou** [comment] 2022-05-12 16:18
@eitantsu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by kendalf** [comment] 2023-05-31 19:20
I can confirm this looks like its still a problem in v3.5.stable.official [991bb6ac7]
I think HTML5 is also affected.

**Comment by AThousandShips** [comment] 2023-06-20 13:56
@kendalf can you provide a minimum reproduction project? Otherwise this will be closed since OP is ghost and no MRP was provided

**Comment by AThousandShips** [comment] 2023-06-27 13:23
Closing per the above comment, if someone can reproduce this issue please open a new issue for this, make sure to include a minimum reproduction project (instructions are available when opening an issue)

**Closed by AThousandShips** 2023-06-27 13:23 UTC
Labels: bug, platform:android, needs testing, topic:export

**Comment by max-pi** [comment] 2023-11-08 21:03
it's the same issue as https://github.com/godotengine/godot/issues/65393

not android specific
