### ISSUE TITLE
Performance issues with VideoPlayer and Webm

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#21719] opened 2018-09-03 08:26 UTC
**Godot version:** 3.1 custom

**Issue description:**
When using webm in a videoplayer, the performance is horrible, even after stopping the video and setting the stream to null. Converting the webm to ogv fixes the problem.

**Minimal reproduction project:**
Can't make one right now, will do later

**Comment by akien-mga** [comment] 2018-10-15 15:04
Reopening as this needs to be mentioned in the documentation, and looking at the code I'm not sure that platforms other than Linux can easily locate yasm and use it.

**Comment by akien-mga** [comment] 2018-12-18 11:37
The relevant code that checks for `yasm` for `x86` platforms is here: https://github.com/godotengine/godot/blob/3a2ca68af3c8bafe9f60f09bd8fece894fe3a925/modules/webm/libvpx/SCsub#L281-L328

It was likely only ever tested on Linux, as it doesn't really make sense for Windows IMO since `yasm` doesn't seem to be part of the typical MSVC distribution. Yasm can be [downloaded from here](https://yasm.tortall.net/), but that still references VS 2010 as the latest version, so might not even work against VS 2017, and I'm pretty sure MSVC comes with its own ASM compiler that could be used instead.

On macOS it might work when installed with homebrew, could someone test? (@Calinou maybe?)

I think neither my nor @hpvb's official builds ever included `yasm` in the build environment so far, be it on Linux, macOS or Windows.

Documentation wise, it's already mentioned for Linux, and I could add a mention to it for macOS if it's confirmed working out of the box when installed via homebrew. For Windows, I think it would be better to refactor the above code to use MSVC's own ASM compiler (is that MASM?).

**Comment by akien-mga** [comment] 2018-12-18 11:38
Note that eventually we want to drop the `webm` and `theora` modules, and use instead @KidRigger's GDNative VideoDecoder to provide support for all formats via FFmpeg. But in the meantime (and likely for 3.1 at least) it would be good to fix this buildsystem issue.

**Comment by bruvzg** [comment] 2018-12-19 18:40
> On macOS it might work when installed with homebrew, could someone test?

homebrew `yasm` works fine for macOS build and MinGW cross-builds on macOS.

**Comment by hpvb** [comment] 2019-01-28 19:11
I'll add Yasm to the build containers.

**Comment by hpvb** [comment] 2019-02-24 00:15
Fixed as of https://github.com/godotengine/build-containers/commit/c81e929d896a541b94405512ca944b4bc3e5700c

**Closed by hpvb** 2019-02-24 00:15 UTC
Labels: documentation, enhancement, topic:buildsystem
