### ISSUE TITLE
Font is blurry in godot 4 compared to godot 3

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#71046] opened 2023-01-08 01:03 UTC
### Godot version

4 beta 10 and 3.5.1

### System information

win 11

### Issue description

Godot 3

![image](https://user-images.githubusercontent.com/69117768/211176013-b30ea842-4d4d-4a22-a1fa-0b917d070a82.png)

Godot 4

![image](https://user-images.githubusercontent.com/69117768/211176018-b61c9bf4-349b-4105-afda-94d06cb51c98.png)

Both have a font size of 12, which I think is the "proper" size of the font. However, the Godot 4 is randomly blurry in some places. No, turning off anti-aliasing doesn't fix the issue, it just makes the blurry pixels completely white so the font looks thicker in some places.

### Steps to reproduce

Use the font "power_red_and_green" from pokemon essentials

[power_red_and_green.zip](https://github.com/godotengine/godot/files/10367501/power_red_and_green.zip)

### Minimal reproduction project

none

**Comment by Atem1995** [comment] 2023-01-08 01:18
Check the Texture property under CanvasItem and select texture_filter as Nearest.

**Comment by ShatReal** [comment] 2023-01-08 01:20
> Check the Texture property under CanvasItem and select texture_filter as Nearest.

no, didn't change anything.

**Comment by markdibarry** [comment] 2023-01-08 01:34
Have you checked the `Import Defaults` tab for the `Font Data` importer in your Project Settings?

**Comment by Calinou** [comment] 2023-01-08 01:51
Duplicate of https://github.com/godotengine/godot/issues/70327.

**Closed by Calinou** 2023-01-08 01:51 UTC
