### ISSUE TITLE
Little squares artifacts appear on surfaces

### ISSUE THREAD

**Issue by eviltrout** [godotengine/godot#67676] opened 2022-10-20 14:34 UTC
### Godot version

4.0 Beta 3

### System information

Macbook Pro 14" M1 Max, MacOS 12.6

### Issue description

From some camera angles (and/or viewport sizes) you will see little square artifacts. They seem to be 32x32 in size.

<img width="1233" alt="Screen Shot 2022-10-20 at 10 27 52 AM" src="https://user-images.githubusercontent.com/17538/196977493-ef628d9e-5b1c-4809-8a7a-e6a57cb41426.png">

I belive they are related to lighting as if I don't have an Omnilight I can't see them.

Moving the camera will make them disappear but then they will re-appear if you put it back to the exact same position. The issue seems to be deterministic - if I save the project and open it again in the same position they are visible right away.

It is easier to see them if you make the OmniLight have more energy, but you can see them with a standard 1.0 energy too.

This does not seem to happen on the same version of Godot 4 (beta 3) on Windows. It seems to be something related to MacOS.

 

### Steps to reproduce

Any scene with an OmniLight seems to do it. I've included one with a CSGBox3D and OmniLight which is quite minimal and shows the issue. If you cannot see them with the test project I've attached it might be due to a different viewport size. Try moving the camera around slowly while looking at the ground and you will see it.

### Minimal reproduction project

[TestVulkan.zip](https://github.com/godotengine/godot/files/9831109/TestVulkan.zip)

**Comment by clayjohn** [comment] 2022-10-20 20:59
Duplicate of https://github.com/godotengine/godot/issues/61108

**Closed by clayjohn** 2022-10-20 20:59 UTC
