### ISSUE TITLE
c# custom signal, After scene switching, you can still access the data of the previous scene.

### ISSUE THREAD

**Issue by ice-ko** [godotengine/godot#83378] opened 2023-10-15 09:29 UTC
### Godot version

Godot v4.2-beta1

### System information

Win11

### Issue description

Use the same script for multiple scenes, after switching scenes. Send a signal in a new scene, and the data returned after receiving the signal is the data in the previous scene.

https://github.com/godotengine/godot/assets/20471045/9761e6c8-9cad-47f7-9dd1-ba54d25cee03

### Steps to reproduce

1. Start the game, click Next to switch scenes, click the mailbox to trigger the signal
2. Receive the signal from the mailbox. The flag variable is the value in the previous scenario.

My English is not very good. There may be errors in the description. Please check the dmeo file, which contains a minimum test version.

### Minimal reproduction project

[TestDemo.zip](https://github.com/godotengine/godot/files/12909135/TestDemo.zip)

**Comment by raulsntos** [comment] 2023-10-15 11:52
Signals connected with `+=` are not automatically disconnected when the node is freed. This is a bug and has already been reported in https://github.com/godotengine/godot/issues/70414. As a workaround you can use `_ExitTree` to disconnect the signal:

```csharp
public override void _ExitTree()
{
    GameFlags.Instance.GameFlagsChanged -= UpdateNodes;
}
```

Alternatively, you can use the `Connect` method instead of `+=` and that shouldn't need you to manually disconnect the signal:

```csharp
public override void _Ready()
{
    defaultNode = GetNode<Node2D>("01");
    switchNode = GetNode<Node2D>("02");

    GameFlags.Instance.Connect(GameFlags.SignalName.GameFlagsChanged, Callable.From(UpdateNodes));
    UpdateNodes();
}
```

- Closing as duplicate of https://github.com/godotengine/godot/issues/70414.

**Closed by raulsntos** 2023-10-15 11:52 UTC
