### ISSUE TITLE
intersect_point() returns empty array inside CSG boxes or colliders that aren't Static

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#65580] opened 2022-09-09 16:43 UTC
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

intersect_point() works with Rigidbodies with Static or Kinematic mode work fine but not CSG boces despite "use collision" being set to true.

Update: added a Staticbody with a Box Collisionshape, it works if the point is inside it too.

### Steps to reproduce

Place CheckIntersectPoint inside one of the CSG boxes, left click and it will return empty, same inside the Rigidbody with modes either Static or Kinematic, then it works.

### Minimal reproduction project
Updated project with the StaticBody.
[testIntersectPoint.zip](https://github.com/godotengine/godot/files/9538364/testIntersectPoint.zip)

**Comment by Calinou** [comment] 2022-09-09 17:01
CSG boxes with Use Collision generate a StatidBody, not a RigidBody.

**Comment by venilark** [comment] 2022-09-09 20:05
> CSG nodes with **Use Collision** enabled generate a StatidBody, not a RigidBody.
> 
> Have you tested this with a StaticBody that has a primitive collision shape added to it? Also try switching the 3D physics engine to GodotPhysics instead of the default Bullet.

Changed to GodotPhysics, same result. Added a StaticBody with a Box CollisionShape, it works inside it.

**Comment by Calinou** [comment] 2022-09-09 21:30
Duplicate of https://github.com/godotengine/godot/issues/58038 (CSG nodes create concave/trimesh collision shapes).

**Closed by Calinou** 2022-09-09 21:30 UTC
Labels: topic:physics, topic:3d
