### ISSUE TITLE
Disabling Script Editor disables opening scripts in External Editor

### ISSUE THREAD

**Issue by d0rf3n** [godotengine/godot#36714] opened 2020-03-01 21:32 UTC
**Godot version:** 3.2

**OS/device including version:** Win10

**Issue description:**
Disabling Script Editor in the "Manage Editor Features..." makes it so that the external editor (at least VSCode for me) doesn't work. Which is kinda funny since otherwise you probably don't wanna disable it?

Meaning, it doesn't open anymore when:
- opening Godot
- try to open scripts for almost anywhere in the editor

**Steps to reproduce:**
1. Use a external editor (only tested with VSCode).
2. Disable the Script Editor using Editor -> Manage Editor Features... -> Uncheck Script Editor
3. Try to open any script...

**Comment by d0rf3n** [comment] 2020-03-01 21:44
After some testing the once that works/not that I found are:

**Not**
- Scene (clicking icon, also Attach Script is no longer available)
- FileSystem (both double click and open)
- Inspector (New Script doesn't open anything)

**Works**
- Existing Signals in Node (Adding a new signal does change the script on save, but doesn't open/focus it)

Also I am quiet sure, but not fully, that this is not intended. I could understans that all these features are connected to the script editor, so perhaps it disables it too much. Only UI option is enough, since the external editor is the only thing that opens anyway.

**Comment by BigRed-118** [comment] 2020-03-03 03:47
What sort of functionality were you looking to get out of disabling the Script Editor?

**Comment by Calinou** [comment] 2020-03-03 08:26
@BigRed-118 Disabling the script editor is meant to be done for artists or level designers so they can't accidentally make changes to scripts. See [this page](https://godotengine.org/article/godot-32-will-allow-disabling-editor-features) for detailed rationale.

To answer the original issue, I'm not sure if this is intended behavior or not.

**Comment by d0rf3n** [comment] 2020-03-03 10:06
@BigRed-118  @Calinou For the same reason as below (from the page you linked) I think it's a neat way of reducing clutter if you use an external editor, only 2d / 3d views, or the like.

So it's hard to think this is intended, since the external editor does open sometimes and other times times not. In it's current state.

> We got requests from single developers working on 2D games that they would like to disable the 3D editor and nodes from the Create dialog. The reasoning is that, if not in use, they just add clutter.

> With this feature, they can be simply disabled, adding a small usability boost.

**Comment by BigRed-118** [comment] 2020-03-05 02:42
@Calinou Do you know who would be able to answer what the intended behavior should be? If you're disabling script editing it sounds like it could make sense for the external editor to be disabled as well.

**Comment by d0rf3n** [comment] 2020-03-05 08:35
I'd prefer if it didn't. And at the moment it only does so half way. You can always disable the external editor by unchecking it, so keeping it seperate would increase the amount of flexibility.

It would make sense however to hide the UI elements to open scripts if both were disabled. This would work in accordance with the intent of removing features not needed by some "designers"not the like, and in educational purposes.

**Comment by Calinou** [comment] 2020-03-05 10:44
@BigRed-118 I think @reduz is probably the one to ask since he implemented the editor profiles feature. That said, he's often busy so it may take a while for him to respond.

**Comment by BigRed-118** [comment] 2020-03-07 20:37
@d0rf3n I'm sorry that I'm having trouble understanding, but doesn't enabling the external editor pretty much give you what you want? Disabling the Script Editor seems to just disable all script editing regardless if an internal or external editor is used. Why does the external editor need to work when Script Editor is disabled? Why can't the Script Editor just stay enabled in that case? If not all scripting gets disabled when Script Editor is disabled that could be an issue.

**Comment by Calinou** [comment] 2021-01-02 17:16
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2059, as the implementation in that proposal makes more sense. Instead of toggling whether you use an external editor, it makes more sense to switch between the built-in and external editor. Disabling the script editor in the editor features should still prevent using that feature entirely (for artists and level designers).

**Closed by Calinou** 2021-01-02 17:16 UTC
Labels: bug, topic:editor
