### ISSUE TITLE
Remote debug not showing actual material parameters

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#43882] opened 2020-11-26 09:06 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
Linux

**Issue description:**
In the screenshot you can see in code I am setting two shader parameters. The values are shown in the debug as 486,473 for one and 250 as the other.

I have selected 'frag', which points to the ColorRect being debugged and is shown on the main inspector pane.

However, there are no sections in the property pane that are showing the actual values of the parameters being set, it is simply showing the default values set up in the shader uniform. This is problematic because it makes it impossible to trace faults. In my case I'm debugging why colour_pos is being set but radius is not, and as you can see I have no idea what has actually been set or not. I.e. I know that the 'Ignore Centre Point' is definitely 486,473 in the game and not 100,100.

It seems that the debug pane only ever updates certain values, such as Node/Node2D.

![image](https://user-images.githubusercontent.com/12863685/100329522-a9dfa080-2fc5-11eb-843e-4dc78b13c07f.png)

This is the case for many nodes in Godot not just the one mentioned, so perhaps it is 'as designed' or a known limitation of the debugger that is part of an ongoing proposal or change?

The debug pane should have the actual values for all properties available.

**Comment by Calinou** [comment] 2021-03-25 20:00
Duplicate of https://github.com/godotengine/godot/issues/28353 (same cause).

**Closed by Calinou** 2021-03-25 20:00 UTC
Labels: bug, topic:editor, topic:shaders
