### ISSUE TITLE
Inspecting remote Dictionary value fails to show instance, shows large negative integer instead.

### ISSUE THREAD

**Issue by ohadfarkash** [godotengine/godot#93757] opened 2024-06-29 19:55 UTC
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b]
- Not present in: v4.2.2.stable.official [15073afe3]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4575) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Just a small beta bug.

When inspecting remote nodes with a dictionary type member, the inspector shows the dictionary incorrectly. The values for objects are shown as a large integer (likely related to the Object ID). These integers can't be further inspected, and trying to click on it throws warnings in the inspector stating that the number is too large.

This was checked in 4.2.2 and worked fine.

### Steps to reproduce

1. Create a script inheriting from node so it can become a remote instance.
2. Define a variable as a dictionary.
3. At any point in the code, add an instance of an object to the dictionary under any key.
4. Run and inspect the remote node member. Trying to inspect the properties of the object instance will be impossible.

![image](https://github.com/godotengine/godot/assets/38788875/a67f39f7-5eef-490e-b428-660decf16c34)
*Inspector does not show the object properly in 4.3.beta2*

![image](https://github.com/godotengine/godot/assets/38788875/db1bf987-88c9-4b9c-a28d-df098fbdd695)
*The good old days*

NOTE: This works in 4.3.beta2 just fine for other types, just not objects.

### Minimal reproduction project (MRP)

MRP: [RemoteDictionaryBug4.3.beta2.zip](https://github.com/user-attachments/files/16042002/RemoteDictionaryBug4.3.beta2.zip)

**Comment by matheusmdx** [comment] 2024-06-29 21:28
This looks like a duplicate of #92533 (maybe the first issue needs to edit the title for something more clear)

**Comment by Chaosus** [comment] 2024-08-04 14:58
Indeed, its fixed on rc2.

**Closed by Chaosus** 2024-08-04 14:58 UTC
