### ISSUE TITLE
Error: "The export hint isn't a resource type" / "Expected a constant expression" for custom Resource type

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#36314] opened 2020-02-18 00:01 UTC
**Godot version:** 3.2

**OS/device including version:** Linux Mint 19.3 Cinnamon

**Issue description:**

When trying to export a custom Resource variable in a GD script, parsing fails with error. If the custom Resource is defined in a separate GD script (starts with `extends Resource`), the error reads "The export hint isn't a resource type" yet it is. if it's an embedded Python-style class (`class CustomResource extends Resource`), it reads "Expected a constant expression".

Replacing the custom type with Texture will work, for instance.

The workaround is to export the path to the instance of custom Resource as a String instead, and `load()` that path on `_ready`. Alternatively, if we only have one instance of custom Resource, we can hard-code a `preload()` of that path. But both solutions are not robust against path change (as opposed to clicking on exported Resource member > Load in Inspector) and do not allowing resource embedding (as opposed to clicking on exported Resource member > New [Resource Type] in Inspector).

On my project, I precisely need this for those two cases:
- point some script to some unique custom Resource (workaround is OK, as path and name is unlikely to change often, so I can preload the resource with hard-coded path)
- create a complex Resource type by embedding an array of sub-Resources (workaround is *not* OK, I need to create a new instance of my sub-Resource, which is nothing more than a small struct, for each array entry; then drag and drop those sub-Resources to the complex Resource's array entries)

The second case could be solved without using Resources at all, if the export hints allowed us to embed unnamed struct/tuples (`e.g. export(Array, (int, float, String))`) or if Godot could recognize struct-like classes, e.g.

```py
extends Resource
class_name ComplexResource

class StructLikeClass extends Resource:
    var i : int
    var f : float
    var s : String

export(Array, StructLikeClass) var content
```

**Steps to reproduce:**

A. Create two scripts:

```py
extends Resource
class_name MissionInfo
```

```py
extends Resource
class_name MissionData

export(Array, MissionInfo) var mission_scenes
```

Save and see the error: "The export hint isn't a resource type"

![image](https://user-images.githubusercontent.com/1067772/74692850-044f0380-51e1-11ea-9f7f-4d1a2de70867.png)

B. Create one script:

```py
extends Resource
class_name MissionData

class MissionInfo extends Resource:
    """""" # just because pass fails to parse in a class, and we need some indent

export(Array, MissionInfo) var mission_scenes
```

Save and see the error: "Expected a constant expression"

![image](https://user-images.githubusercontent.com/1067772/74692893-39f3ec80-51e1-11ea-90e3-deae79f177cb.png)

**Comment by hsandt** [comment] 2020-02-18 00:31
Wow, I found a crazy workaround to embed custom Resources:

1. First, you need to apply method A above, not B, so the custom Resource type is exposed.

```py
# MissionInfo.gd
extends Resource
class_name MissionInfo
    export(int) var i = 10
```

2. Since custom Resources are not accepted, export an array of generic Resource (base type):

```py
# MissionData.gd
extends Resource
class_name MissionData

export(Array, Resource) var mission_scenes
# or export(Resource) var my_resource if you only need one
```

Now it parses and the member appears in the inspector. Add an entry to the array. You need to find your custom type in the very long list of Resource types!

![image](https://user-images.githubusercontent.com/1067772/74693506-06ff2800-51e4-11ea-92e5-8ba6c3ae557c.png)

Oddly enough, the Resource does not appear with the class_name, but just as "Resource". Don't be fooled though, it's the correct type. Just click on "Resource" and you'll see the members appear. You can now edit them.

This works with both embedded resource and resources stored in an external file (Load):

![image](https://user-images.githubusercontent.com/1067772/74693898-af61bc00-51e5-11ea-9499-ba197e106d69.png)

But it's still not enough because:
- we must go through the very long list of Resources
- we are less strict, as we allow any Resource type and a misclick will generate wrong data
- the custom Resource still reads as "Resource" (probably custom Resource exposition was actually never implemented?)

**Comment by Calinou** [comment] 2020-02-18 08:44
Duplicate of #30694.

**Closed by Calinou** 2020-02-18 08:44 UTC
