### ISSUE TITLE
Crash when moving directories in FileSystem pane

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28012] opened 2019-04-14 13:07 UTC
**Godot version:**
v3.1.stable.official

**OS/device including version:**
MacBook Pro
macOS 10.14.4

**Issue description:**
I created a new "assets" folder in the project's root directory, and dragged and dropped my "audio" folder into it. It said it was reimporting audio assets and then it crashed:

```Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5bfa22c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5c057bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5bf0c6a6 abort + 127
3   org.godotengine.godot         	0x0000000108918e02 handle_crash(int) + 2898
4   libsystem_platform.dylib      	0x00007fff5c04cb5d _sigtramp + 29
5   ???                           	0x000000010bf46240 Engine::singleton + 8
6   org.godotengine.godot         	0x000000010ab3ead6 Object::set(StringName const&, Variant const&, bool*) + 102
7   org.godotengine.godot         	0x000000010ab94f17 Resource::reload_from_file() + 407
8   org.godotengine.godot         	0x00000001094a5c18 EditorNode::_resources_reimported(Vector<String> const&) + 280
9   org.godotengine.godot         	0x00000001094fb18e MethodBind1<Vector<String> const&>::call(Object*, Variant const**, int, Variant::CallError&) + 302
10  org.godotengine.godot         	0x000000010ab41f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
11  org.godotengine.godot         	0x000000010ab43e40 Object::emit_signal(StringName const&, Variant const**, int) + 2016
12  org.godotengine.godot         	0x000000010ab42602 Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 114
13  org.godotengine.godot         	0x000000010942aa9c EditorFileSystem::reimport_files(Vector<String> const&) + 1548
14  org.godotengine.godot         	0x00000001094293db EditorFileSystem::_update_scan_actions() + 2027
15  org.godotengine.godot         	0x000000010942edd6 EditorFileSystem::_notification(int) + 1334
16  org.godotengine.godot         	0x000000010943804c EditorFileSystem::_notificationv(int, bool) + 76
17  org.godotengine.godot         	0x000000010ab3e9d3 Object::notification(int, bool) + 19
18  org.godotengine.godot         	0x0000000109c74978 SceneTree::_notify_group_pause(StringName const&, int) + 1976
19  org.godotengine.godot         	0x0000000109c74e58 SceneTree::idle(float) + 600
20  org.godotengine.godot         	0x000000010894d95f Main::iteration() + 799
21  org.godotengine.godot         	0x0000000108923407 OS_OSX::run() + 631
22  org.godotengine.godot         	0x000000010892613b main + 811
23  libdyld.dylib                 	0x00007fff5be673d5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010ad420ec _IP_ResolverPrivate::_thread_function(void*) + 60
3   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 2:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5bf9f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c0585a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff31758a4b CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff31757ffa CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010a97270d VisualServerScene::_gi_probe_bake_thread() + 29
3   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 4:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff2f469eda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff2f469e4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff2f46639f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff2f465df4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff2f465956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010911104b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x0000000109259adf EditorExportPlatformAndroid::_device_poll_thread(void*) + 8543
4   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010911104b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x0000000109814934 EditorFileServer::_thread_start(void*) + 884
4   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2f9f013e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2f9ef6ac __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2f9eee0e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2d07dd1a _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x00000001089262e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x000000010a98c788 VisualServerWrapMT::texture_get_data(RID, int) const + 248
3   org.godotengine.godot         	0x000000010a4daec3 ImageTexture::get_data() const + 51
4   org.godotengine.godot         	0x000000010924e892 ResourceSaverPNG::save(String const&, Ref<Resource> const&, unsigned int) + 210
5   org.godotengine.godot         	0x000000010ad946e5 ResourceSaver::save(String const&, Ref<Resource> const&, unsigned int) + 373
6   org.godotengine.godot         	0x000000010957ad7a EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) + 1914
7   org.godotengine.godot         	0x0000000109578ed3 EditorResourcePreview::_thread() + 2019
8   org.godotengine.godot         	0x00000001091148a5 ThreadPosix::thread_callback(void*) + 85
9   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
10  libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
11  libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000111a0a5c0  rcx: 0x00007ffee72e66d8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee72e6710  rsp: 0x00007ffee72e66d8
   r8: 0x00000000000130a8   r9: 0x00007fff8ee61048  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000015  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5bfa22c6  rfl: 0x0000000000000206  cr2: 0x00007fff8ee5f188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

**Comment by mitchcurtis** [comment] 2019-04-14 13:10
After re-launching the editor, it seems like the audio folder was actually successfully moved, despite the crash.

I tried dragging my "sprites" folder into there (just contains images) and it worked fine.

**Comment by groud** [comment] 2019-04-14 13:35
Related to or duplicate of #22230

**Comment by akien-mga** [comment] 2019-04-17 07:55
Other related issue/possible duplicate: #26394

**Comment by mitchcurtis** [comment] 2019-04-20 07:41
Just got another one after moving a new audio file to my project. I opened Godot and it said it was automatically reimporting stuff and then it crashed:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5bfa22c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5c057bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5bf0c6a6 abort + 127
3   org.godotengine.godot         	0x0000000106b5be02 handle_crash(int) + 2898
4   libsystem_platform.dylib      	0x00007fff5c04cb5d _sigtramp + 29
5   ???                           	0x000000010a189240 Engine::singleton + 8
6   org.godotengine.godot         	0x0000000108d81ad6 Object::set(StringName const&, Variant const&, bool*) + 102
7   org.godotengine.godot         	0x0000000108dd7f17 Resource::reload_from_file() + 407
8   org.godotengine.godot         	0x00000001076e8c18 EditorNode::_resources_reimported(Vector<String> const&) + 280
9   org.godotengine.godot         	0x000000010773e18e MethodBind1<Vector<String> const&>::call(Object*, Variant const**, int, Variant::CallError&) + 302
10  org.godotengine.godot         	0x0000000108d84f63 Object::call(StringName const&, Variant const**, int, Variant::CallError&) + 355
11  org.godotengine.godot         	0x0000000108d86e40 Object::emit_signal(StringName const&, Variant const**, int) + 2016
12  org.godotengine.godot         	0x0000000108d85602 Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 114
13  org.godotengine.godot         	0x000000010766da9c EditorFileSystem::reimport_files(Vector<String> const&) + 1548
14  org.godotengine.godot         	0x000000010766c3db EditorFileSystem::_update_scan_actions() + 2027
15  org.godotengine.godot         	0x0000000107671b9f EditorFileSystem::_notification(int) + 767
16  org.godotengine.godot         	0x000000010767b04c EditorFileSystem::_notificationv(int, bool) + 76
17  org.godotengine.godot         	0x0000000108d819d3 Object::notification(int, bool) + 19
18  org.godotengine.godot         	0x0000000107eb7978 SceneTree::_notify_group_pause(StringName const&, int) + 1976
19  org.godotengine.godot         	0x0000000107eb7e58 SceneTree::idle(float) + 600
20  org.godotengine.godot         	0x0000000106b9095f Main::iteration() + 799
21  org.godotengine.godot         	0x0000000106b66407 OS_OSX::run() + 631
22  org.godotengine.godot         	0x0000000106b6913b main + 811
23  libdyld.dylib                 	0x00007fff5be673d5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x0000000106b692e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x0000000108f850ec _IP_ResolverPrivate::_thread_function(void*) + 60
3   org.godotengine.godot         	0x00000001073578a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 2:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5bf9f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c0585a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff31758a4b CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff31757ffa CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x0000000106b692e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x0000000108bb570d VisualServerScene::_gi_probe_bake_thread() + 29
3   org.godotengine.godot         	0x00000001073578a5 ThreadPosix::thread_callback(void*) + 85
4   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 4:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff2f469eda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff2f469e4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff2f46639f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff2f465df4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff2f465956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010735404b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x000000010749cadf EditorExportPlatformAndroid::_device_poll_thread(void*) + 8543
4   org.godotengine.godot         	0x00000001073578a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff5bf9ff32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5bf2b914 nanosleep + 199
2   org.godotengine.godot         	0x000000010735404b OS_Unix::delay_usec(unsigned int) const + 59
3   org.godotengine.godot         	0x0000000107a57934 EditorFileServer::_thread_start(void*) + 884
4   org.godotengine.godot         	0x00000001073578a5 ThreadPosix::thread_callback(void*) + 85
5   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5bf9c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5bf9c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2f9f013e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2f9ef6ac __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2f9eee0e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2d07dd1a _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff5bf9def2 read + 10
1   org.godotengine.godot         	0x0000000106b692e9 SemaphoreOSX::wait() + 25
2   org.godotengine.godot         	0x0000000108bcf788 VisualServerWrapMT::texture_get_data(RID, int) const + 248
3   org.godotengine.godot         	0x000000010871dec3 ImageTexture::get_data() const + 51
4   org.godotengine.godot         	0x0000000107491892 ResourceSaverPNG::save(String const&, Ref<Resource> const&, unsigned int) + 210
5   org.godotengine.godot         	0x0000000108fd76e5 ResourceSaver::save(String const&, Ref<Resource> const&, unsigned int) + 373
6   org.godotengine.godot         	0x00000001077bdd7a EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) + 1914
7   org.godotengine.godot         	0x00000001077bbed3 EditorResourcePreview::_thread() + 2019
8   org.godotengine.godot         	0x00000001073578a5 ThreadPosix::thread_callback(void*) + 85
9   libsystem_pthread.dylib       	0x00007fff5c0552eb _pthread_body + 126
10  libsystem_pthread.dylib       	0x00007fff5c058249 _pthread_start + 66
11  libsystem_pthread.dylib       	0x00007fff5c05440d thread_start + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff5c0543f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000118d6f5c0  rcx: 0x00007ffee90a36d8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee90a3710  rsp: 0x00007ffee90a36d8
   r8: 0x00000000000130a8   r9: 0x00007fff8ee61048  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000015  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5bfa22c6  rfl: 0x0000000000000206  cr2: 0x00007fff8ee5f188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

```

**Closed** 2019-06-04 20:30 UTC
Labels: bug, high priority, topic:editor
