### ISSUE TITLE
I can't save

### ISSUE THREAD

**Issue by Fritzmeinzer** [godotengine/godot#43902] opened 2020-11-26 22:39 UTC
**Godot version:** Godot Version 3.2.3

**OS/device including version:** Chrome OS Acer Chromebook 315

**Issue description:**

My saves won't be validated. So recently My Godot game has been resetting itself like all my scenes and nodes are gone and it looks like when you start up a brand new project. Although all my assets are still there such as sprites and music but I have to reimport my Nodes. This was not a one-time thing, This happens EVERYTIME I quit the editor and I constantly save my work but it still keeps doing this please help!!
**Steps to reproduce:**
When I look into my files my project.godot is gone

**Minimal reproduction project:**

**Comment by Calinou** [comment] 2020-11-26 23:04
> OS/device including version: Chrome OS Acer Chromebook 315

How are you running Godot? Did you install a Linux distribution and run it?

**Comment by Fritzmeinzer** [comment] 2020-11-27 15:20
No, I used

wget
https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_x11.64.zip
unzip Godot_v3.2.3-stable_x11.64.zip
./Godot_v3.2.3-stable_x11.64

**Comment by Calinou** [comment] 2021-06-15 17:28
Duplicate of #40968 (same cause).

**Closed by Calinou** 2021-06-15 17:28 UTC
Labels: platform:linuxbsd, topic:editor, topic:porting
