### ISSUE TITLE
Godot Showcase section should be relisted

### ISSUE THREAD

**Issue by nikhilCad** [godotengine/godot#31594] opened 2019-08-23 09:02 UTC
**Godot version:**

-

**OS/device including version:**

-

**Issue description:**

First of all, I am not sure where to post it, posting here as I thought that the devs would see it.
https://godotengine.org/showcase
Chrome trip is on the first page! When you have great games like Rings of Saturn and Kingdoms of the Dump.
The website itself is kind of less fancy as compared to  other engines.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment] 2019-08-23 09:46
Duplicate of godotengine/godot-website#7.

**Closed by akien-mga** 2019-08-23 09:46 UTC
