### ISSUE TITLE
Godot Editor Sizing Is off When Dragged Onto a Separate Monitor

### ISSUE THREAD

**Issue by arcticmatt** [godotengine/godot#36315] opened 2020-02-18 00:42 UTC
**Godot version:**
3.2.stable.official

**OS/device including version:**
macOS Catalina 10.15.2

**Issue description:**
When I drag the Godot editor from my laptop screen to my second monitor, the sizing gets all off (it's too zoomed in).

**Steps to reproduce:**
See issue description.

**Minimal reproduction project:**
An empty project is fine. 

How it looks when you drag the editor onto the second monitor
![image](https://user-images.githubusercontent.com/4356178/74694263-5aea1c80-51a4-11ea-941c-a83006caa3dd.png)

How it looks when you start Godot on the second monitor
![Screen Shot 2020-02-17 at 4 40 38 PM](https://user-images.githubusercontent.com/4356178/74694237-3d1cb780-51a4-11ea-9bbe-619daf6f610c.png)

**Comment by Calinou** [comment] 2020-02-18 08:34
Duplicate of #30880 (it's the other way around, but the underlying issue is the same).

**Closed by Calinou** 2020-02-18 08:34 UTC
Labels: bug, topic:editor
