### ISSUE TITLE
Duplicating an instanced scene in code doesn't duplicate attached materials even when set local to scene

### ISSUE THREAD

**Issue by rhofour** [godotengine/godot#55075] opened 2021-11-18 02:11 UTC
### Godot version

3.4

### System information

Fedora 35 (64-bit)

### Issue description

Take a scene with an node with a material set to "local to scene" (such as the example GUI in 3D project).

If I duplicate the scene in the editor I get another instance with separate materials. However, if I duplicate the same scene using Node.duplicate instead I get a new instance that shares the same material as the parent. This is with or without passing the DUPLICATE_USE_INSTANCING flag.

### Steps to reproduce

1) Duplicate a scene using Node.duplicate
2) Observe the material is shared between both instances

### Minimal reproduction project

This can be seen in the examples GUI in 3D project. Simply add the following C# script to the scene root:

```
using Godot;
using System;

public class gui_in_3d : Spatial
{
    public override void _Ready()
    {
        Spatial gui = GetNode<Spatial>("GUIPanel3D");
        Node clone = gui.Duplicate();
        AddChild(clone);

        // So they don't overlap.
        gui.Translate(new Vector3(0.0f, 2.0f, 0.0f));

        // Read out the materials and paths.
        PrintInfo(gui);
        PrintInfo(clone);
    }
    private void PrintInfo(Node gui)
    {
        SpatialMaterial mat = (SpatialMaterial) gui.GetNode<MeshInstance>("Quad").GetActiveMaterial(0);
        GD.Print("Material for ", gui.GetPath(), " ", mat);
    }
}
```

Running this will then clone the GUIPanel3D node and show that both the original node and the new clone share the same material.

**Comment by rhofour** [comment] 2021-11-18 03:02
It might be worth noting for some reason in one of my projects this wasn't the case in 3.3.x, but is in 3.4. However, every time I try and simplify that down to a minimal reproduction I can't. The minimal reproduction I described will repro this issue in 3.3.x.

**Comment by rhofour** [comment] 2021-11-19 00:35
This seems to apply to textures too. I get the same thing when using a Sprite3D with a local to scene Texture.

**Comment by rhofour** [comment] 2021-11-20 15:12
I think this might be the same bug as #47918.

**Comment by Rindbee** [comment] 2022-08-15 07:14
Duplicate of #45350.

**Closed** 2022-08-15 08:59 UTC
Labels: bug, topic:core, topic:rendering
