### ISSUE TITLE
[4.0-pre-alpha] Failed to export to Android

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53662] opened 2021-10-11 05:52 UTC
### Godot version

v4.0.dev.20211004.official [2e8cba0bd]

### System information

Windows 11, Vulkan Mobile

### Issue description

![image](https://user-images.githubusercontent.com/28705694/136739010-b41d170c-52e0-4ded-b31b-6d219b6379eb.png)

My export settings, which will do in 3.x:
![image](https://user-images.githubusercontent.com/28705694/136739063-3166b5c9-973b-4b34-a4a7-d324bf5dcc66.png)

If I put the keystone path in the export preset, the export still fails.
![image](https://user-images.githubusercontent.com/28705694/136739446-93f6e722-b4d6-4a86-b92b-15a38002d590.png)

### Steps to reproduce

Try to export to Android.

**Comment by AFE-GmdG** [comment] 2021-10-16 18:18
At least in 3.3.3 and 3.3.4 the export to android isnt working as well - the generated APKs are not signed, even if all settings correct set. I tried it with 3.2.3 and in this case it worked fine.

**Comment by Calinou** [comment] 2021-10-16 18:45
> At least in 3.3.3 and 3.3.4 the export to android isnt working as well - the generated APKs are not signed, even if all settings correct set. I tried it with 3.2.3 and in this case it worked fine.
> 
> The errormessage said ![image](https://user-images.githubusercontent.com/14022522/137598124-17362f1d-4f2b-4ddb-bcbf-bcac3a4051bb.png)

This is unrelated to the issue reported here. This appears to be the same cause as https://github.com/godotengine/godot/issues/18222.

**Comment by autofool** [comment] 2021-12-04 14:58
Are you using jdk11?

**Comment by floppyhammer** [comment] 2021-12-06 01:32
@autofool jdk8 I suppose.

**Comment by autofool** [comment] 2021-12-27 06:12
You need to use jdk11 for Godot4. [check here](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html)

**Comment by floppyhammer** [comment] 2021-12-27 07:00
Upgraded to jdk11, new error

<img width="652" alt="image" src="https://user-images.githubusercontent.com/28705694/147443912-114c31bf-bc88-45bb-a7ff-10771124fab2.png">

APK can be generated but cannot be installed on mobile phones.

**Comment by autofool** [comment] 2021-12-29 06:21
Have you recreated your store and store key with jdk11?

**Comment by floppyhammer** [comment] 2021-12-30 02:02
@autofool Yes, I've recreated the keystore file.

**Comment by autofool** [comment] 2022-01-02 05:44
This issue could be specific to Windows 11. Have you tried in Windows 10? Unfortunately I don’t have Windows 11 device to probe more into the error.

**Comment by KoBeWi** [comment] 2022-06-04 14:06
@floppyhammer Can you check if it works for you with the official alpha templates?
Android export was fine last time I tried it.

**Comment by floppyhammer** [comment] 2022-06-07 04:57
@KoBeWi No for v4.0.alpha9.official [fc18891db].

<img width="597" alt="image" src="https://user-images.githubusercontent.com/28705694/172299137-8bc264e4-1b60-4d31-b104-2e90086699d7.png">

**Comment by floppyhammer** [comment] 2022-08-26 03:25
It turns out that this is the 4.0 counterpart of https://github.com/godotengine/godot/issues/58192.

**Comment by akien-mga** [comment] 2023-02-22 15:15
Closing as duplicate of #58192 if it's not version specific.

**Closed by akien-mga** 2023-02-22 15:15 UTC
Labels: bug, platform:android, topic:editor, topic:export
