### ISSUE TITLE
Visual Shader with proxiimity fade nodes are broken when transitioning to Godot Beta 14

### ISSUE THREAD

**Issue by MeshVoid** [godotengine/godot#72022] opened 2023-01-25 09:16 UTC
### Godot version

Godot Beta 14

### System information

Windows 10, Vulkan, Forward+

### Issue description

Opening project with Godot Beta 14 broke some visual shaders that I made in previous iterations of Godot. I had a water shader working perfectly in previous iterations of Godot, now it's broken, I don't know why. I have attached the .tres vshader file to this bug report. 

Here's the same shader in Godot beta 12:
![image](https://user-images.githubusercontent.com/35863328/214523424-b1d71224-5252-40bd-8fed-c6c43d47c0ee.png)

Here's the same shader in Godot beta 14:
![image](https://user-images.githubusercontent.com/35863328/214523629-1a3de662-1066-4bd9-aa47-fd34c71d938a.png)

I think it is caused because I was using the proximity fade node quite a bit in my shader, but I don't know how to make the shader work now, would be grateful for any help fixing it.

### Steps to reproduce

Extract the .tres file and export to your project in Godot Beta 14, apply to meshInstance plane geometry.  It doesn't work, but did work in previous betas. If you open it in Godot Beta 12, for example it will work as expected. 

### Minimal reproduction project

Here's the shader file:
[WaterVS2.zip](https://github.com/godotengine/godot/files/10497730/WaterVS2.zip)

N/A

**Comment by akien-mga** [comment] 2023-01-25 09:26
Duplicate of #71803, this is fixed in 4.0 beta 15: https://downloads.tuxfamily.org/godotengine/4.0/beta15/

Note that you will still get compilation errors when opening that shader initially:
```
SHADER ERROR: DEPTH_TEXTURE has been removed in favor of using hint_depth_texture with a uniform.
To continue with minimal code changes add 'uniform sampler2D DEPTH_TEXTURE : hint_depth_texture, filter_linear_mipmap;' near the top of your shader.
```

This is because the generated code doesn't get automatically regenerated to match the change in the shader language.

You can force regenerating it by doing any change to the Visual Shader, and that should solve it.

**Closed by akien-mga** 2023-01-25 09:26 UTC

**Comment by MeshVoid** [comment] 2023-01-25 09:54
Thank you, didn't know that beta 15 is up already, it's fixed and working in beta 15. I tried doing any changes to Visual Shader in beta 14 and didn't get any results at all, tried to convert it to shader and couldn't fix it as well by adding some lines that debugger threw at me.

I did exactly that:

> To continue with minimal code changes add 'uniform sampler2D DEPTH_TEXTURE : hint_depth_texture, filter_linear_mipmap;' near the top of your shader.

**Comment by akien-mga** [comment] 2023-01-25 10:14
Yeah in beta 14 the Visual Shader node for proximity fade was still using `DEPTH_TEXTURE` internally.
