### ISSUE TITLE
Node is created outside of the viewport in RTL editors

### ISSUE THREAD

**Issue by BSSM7** [godotengine/godot#77262] opened 2023-05-20 00:10 UTC
### Godot version

4.1 dev2, 4.0.3

### System information

Windows 10, ryzen 5900x, radeon 6950xt (driver: 23.2.2)

### Issue description

There are two bugs:
- When I create a new node, it is created outside of the viewport. (as in first video)
- When I run the project, all the content inside the viewport dont appear. (as in second video)
I believe the second issue is related to the first.

Note: these problems are in RTL editors.

https://github.com/godotengine/godot/assets/121864036/84f0d434-0d1b-4c23-9fb0-510257e2e191

https://github.com/godotengine/godot/assets/121864036/b2bc20c7-1e2e-4d04-99e7-d66860ffced2

### Steps to reproduce

Videos explain.

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment] 2023-05-20 03:24
Try to describe the reproduction steps clearly in text, my browser (firefox / chromium) cannot play the video normally. I had to download the videos to my computer to play them.

It seems to be caused by the different coordinate systems used by `Control` and `Node2D`.

In addition, **left**/**right** is a bit misleading, descriptions like **begin**/**end** are suitable for LTR/RTL.

**Comment by BSSM7** [comment] 2023-05-20 23:03
I've been playing with it, and I think I've figured out what the problem is. It is simple and I'm not sure if it was a bug or not :)
but I feel there is a bug.

Anyway, I want to correct some of what I have mentioned above:
- I said :"..**all** the content inside the viewport dont appear".  and that's **not correct**. All nodes that belong to Node2d are working fine.
- The problem applies only to Control nodes. It is actually just about "Layout Direction".


**Steps to reproduce**
1. Open Godot Editor (English version).
2. Create a 2d Scene.
3. Create any Control node as child for it, and click on it, and don't move it.
4. Go to Inspector -> Layout -> Layout Direction -> set it to Right-to-Left (**this option is the default for RTL editors**).
And here you will notice that the node itself and its borders are outside of the viewport **(this is the first problem)**.
I believe it should be inside the viewport, maybe the top right corner.

5. Drag that Control node in the center of viewport, and run the project.
Here you will notice that nothing displays on the screen.

6. Drag that Control node to left outside of the borders of the viewport, and run the project.
Here we will find our lost node shows itself on the screen, but also in an inverted way.

@Rindbee Last point I didnt get it, but if you mean the "convention" I see that RTL/LTR are perfect; because they are objective, while begin/end are subjective; because they depend on which direction the person begins/ends with.
Also RTL/LTR are known convention, so that I mentioned them. other than this I didnt get it

**Comment by Rindbee** [comment] 2023-05-21 00:11
> Last point I didnt get it, but if you mean the "convention" I see that RTL/LTR are perfect; because they are objective, while begin/end are subjective; because they depend on which direction the person begins/ends with, so they will lead to more misleading. Also RTL/LTR are known convention, so that I mentioned them. other than this I didnt get it

I thought left/right should be relative to me (in screen they should be fixed), but in those alignments, would be swapped relative to `layout_direction`, but the text description didn't change, and then I'm a bit out of it.

![0](https://github.com/godotengine/godot/assets/30386067/d0d05466-fdf8-4fe4-a49a-b263e7126505)


| LTR | RTL |
| :----: | :----: |
| ![1](https://github.com/godotengine/godot/assets/30386067/1e9a1794-36bd-4ac0-896c-af15f32d44ce) | ![2](https://github.com/godotengine/godot/assets/30386067/2f643a1a-f08a-4eed-af78-733f6cab4d27) |

**Comment by BSSM7** [comment] 2023-05-21 02:03
Could you please redo the steps? I just made a small change on them.

**Comment by Rindbee** [comment] 2023-05-21 04:19
> Could you please redo the steps? I just made a small change on them (step1 and step4).

Yes, I can reproduce it.
![3](https://github.com/godotengine/godot/assets/30386067/7d1489aa-8d40-48d6-8491-a36ece822e0e)

**Comment by BSSM7** [comment] 2023-05-21 04:27
This is before the last change on the steps I mentioned, and it does not display the bug.
Then please try again but:
- In Arabic version.
- Set the layout direction on : Inherted. and run the project after the steps, you will see the bug, I hope.

**Comment by BSSM7** [comment] 2023-05-21 04:36
Also, Try to make Control node as child for Node2d.

**Comment by bruvzg** [comment] 2023-05-26 13:29
I'm not sure what the best solution here. This is not fixable without significant changes to the non-`Control` nodes, `Node2D` do not have size, so there's no inside either.

**Comment by bruvzg** [comment] 2023-06-06 08:42
> I'm not sure what the best solution here. This is not fixable without significant changes to the non-Control nodes, Node2D do not have size, so there's no inside either.

Actually I'm wrong, non-Control seems to have proper `get_parent_anchorable_rect` based on viewport visible rect. But layout expect it to always have `0,0` origin, which is not the case for non-Controls. Should be an easy fix.

**Comment by bruvzg** [comment] 2023-06-06 08:51
> non-Control seems to have proper get_parent_anchorable_rect based on viewport visible rect. But layout expect it to always have 0,0 origin, which is not the case for non-Controls. Should be an easy fix.

This will work with Nodes like Sprite2D and similar stuff with visible rect, but still won't work with empty Node2D scene root (since it still doesn't have size), but I do not think it's should be considered as a bug.

**Closed** 2023-06-09 11:47 UTC
Labels: bug, topic:editor, needs testing, topic:2d
