### ISSUE TITLE
2D label ignores rotation at runtime

### ISSUE THREAD

**Issue by mschulzeLpz** [godotengine/godot#37577] opened 2020-04-04 10:42 UTC
**Godot version:**
3.2.1.rc2.offical
**OS/device including version:**
Windows 10
**Issue description:**
I try to create a UI with rotated labels in by using editor functionallity.
**Steps to reproduce:**
* create a simple scene
* add a HBoxContainer
* add a Label to the container
* set rect rotation to 270

The editor shows the correct rotation, but is reseted on runtime

<img src="https://i.postimg.cc/W4hkzT8s/Label-Rotation-Issue.png">

**Minimal reproduction project:**
https://drive.google.com/drive/folders/118XNo2g2K6kXGNAq0xQijb9wWr-K9WJX?usp=sharing

**Comment by Anutrix** [comment] 2020-04-04 11:22
You are not supposed to set transforms like the rotation of children of Containers. The containers themselves do set it. You get a warning telling that too.

**Comment by mschulzeLpz** [comment] 2020-04-04 14:12
I try different ways and nothing is working.
When i added a label direct under the root control and set the rotation than it works as expected
When i added the label under other controls e.g. GridContainer it fails and is reset when reload the project.
Also use "extra" Container for a label (by the way makes no sence to have a extra layer only for a label) and set the rotation on the Container not works. Is also reset on project loading.

I attach my example project maybe this will better show the problem

**Comment by Zireael07** [comment] 2020-04-04 14:23
It is not working because all Containers control rotations, as @Anutrix  told you.

**Comment by mschulzeLpz** [comment] 2020-04-04 14:32
Can you provide me an working example please?
I applied the rotation to the parent Container of the label and in not works

**Comment by aaronfranke** [comment] 2020-04-04 14:46
Children of containers have their position and rotation exclusively determined by their parent. 

The minimal reproduction project you posted doesn't actually show the bug because this isn't an issue of things being different on runtime, this is about things being invalid - if you restart Godot, you will see that everything moves to be the way it's supposed to be.

This is [well documented](https://docs.godotengine.org/en/latest/tutorials/gui/gui_containers.html) and Godot already has a big yellow warning and also prevents you from visually editing children of containers to prevent you from getting into this invalid state.

Currently Godot doesn't prevent you from editing the values *in the inspector*, but this part is already being tracked by #28718 which will be fixed by #30623 in 4.0.

**Closed by aaronfranke** 2020-04-04 14:46 UTC

**Comment by Erfa** [comment] 2022-03-05 21:38
So if rotation is also controller by the parent, how do you rotate something? There's no RotationContainer, right? Do you need to write a custom container for this to work?
