### ISSUE TITLE
Sound file import loop error 

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#40694] opened 2020-07-25 12:12 UTC
**Godot version:**
3.2.2

**OS/device including version:**
Ubuntu Studio 20.04 lts

**Issue description:**
i import some audio file whit the **loop option on**, if i **disabled this option in the inspector** the music loop over and over again, to fix that i must re-import the audio files disabling the loop option. The same happens when importing audio files whit the loop option disabled. 

**Steps to reproduce:**
just import a file whit the loop option on or off and try to disable this option in the inspector, the audio file will keep the imported value.

**Comment by Calinou** [comment] 2020-07-25 12:22
@CHIESOFTWARE Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment] 2020-07-25 12:23
Duplicate of #40359.

**Closed by Calinou** 2020-07-25 12:23 UTC
