### ISSUE TITLE
Images appear scrambled in latest unstable

### ISSUE THREAD

**Issue by algorev** [godotengine/godot#8027] opened 2017-03-14 18:19 UTC
**MacOS El Capitan 10.11.6 - 3.0**

**Issue description:**

Godot visualizes the default icon.png (in the file browser and the file system tab) file as a weird scrambled bunch of pixels, though it looks normal in the rest of the editor.
It also tries to visualize every file, even those that aren't images.

**Steps to reproduce:**
1. Compile and open godot.
2. Create a project.
3. Open the project.

**Link to minimal example project:**

Will be quicker to test if you just create the project yourself, since it's the default project anyway.

**Comment by vnen** [comment] 2017-03-14 23:21
Seems like the same as #7812

**Comment by kubecz3k** [comment] 2017-03-17 15:18
archiving since it's as a duplicate of https://github.com/godotengine/godot/issues/7812

**Closed by kubecz3k** 2017-03-17 15:18 UTC
