### ISSUE TITLE
_process(delta) not called

### ISSUE THREAD

**Issue by TimurKhan** [godotengine/godot#25674] opened 2019-02-06 23:11 UTC
**Godot version 3.0**
**Windows 10/x64**
I defined a class from Node. I use `set_process(true)` in `_ready()` constructor. But the method `_process()` is not called. WTF?

`extends Node
var idle = 0.0
func _ready():
	set_process(true)
func _process(delta):
	idle += delta
	print(idle)`

**Comment by Ranoller** [comment] 2019-02-06 23:34
Can be print instruction dissabled in project settings
Can be Node not added to the scene or to Autoloads
Can be a lot of things, but not a godot bug.  I compile godot from 2.0 and this bug never happened,

**Comment by TimurKhan** [comment] 2019-02-06 23:38
Print instruction enabled in project settings. I can check `idle` from other point. 
Node and class added to the scene or to Autoloads
Not working :-(

**Comment by Ranoller** [comment] 2019-02-06 23:38
Upload your project

**Comment by volzhs** [comment] 2019-02-07 06:12
do you expect it's running in editor without running game?

**Comment by groud** [comment] 2019-02-07 09:54
Is your node in the game tree ? (you used add_child in your game code)

**Comment by TimurKhan** [comment] 2019-02-07 12:17
Boys and girls. I cannot post all the project code in which this situation arose. On one side, it contains a very huge and very interesting code that I am not ready to share with the world. On the other hand, 99% of the code is a calculation that does not affect the game cycle, the display, or anything else.
But the fact remains. Apparently this is a bug. But I don’t understand how to cope with it, or how to give a hint to the developers.
Tnx to all

**Comment by TimurKhan** [comment] 2019-02-07 12:23
> Ваш узел находится в дереве игр? (вы использовали add_child в коде игры)

No, this is a separate class. This class contains several variables that are read from interface elements that are elements of a tree (scene).
But the class itself functions separately from (above) the tree of visual elements. This is a child class of Node.
I made a test project with a similar organization. And it all works. I really don't understand. The difference between a test and a real project is only in the presence of computational procedures and functions that are not directly related either to the physics flow or to other flows. I actually planned from `_process (delta)` to call triggers initiating calculations.

**Comment by TimurKhan** [comment] 2019-02-07 12:30
I will try to consistently kill the functions until I stumble on the source of the problem. If I find such a source, I will describe it here.
Thank you friends for participating

**Comment by timoschwarzer** [comment] 2019-02-07 14:41
Sorry, but no one can help you if you don't give us code to work with. You could make a separate project reproducing the problem. But as @Ranoller said, I've never came across `_process` not being called and one would definitely notice that.

> But the class itself functions separately from (above) the tree of visual elements. This is a child class of Node.

It sounds to me like that node is not added to the tree anywhere, which in fact is required for processing to work.

**Comment by timoschwarzer** [comment] 2019-02-07 14:42
...and you don't need to `set_process(true)` in `_ready` anymore since 3.0.

**Comment by groud** [comment] 2019-02-07 14:46
> No, this is a separate class. This class contains several variables that are read from interface elements that are elements of a tree (scene). But the class itself functions separately from (above) the tree of visual elements. This is a child class of Node.

This is not what I meant. If you create a node but it is not added to the actual SceneTree, like instantiating a node without using add_child, this function will never be called. See https://docs.godotengine.org/en/3.0/getting_started/step_by_step/scene_tree.html

**Comment by TimurKhan** [comment] 2019-02-07 15:52
@groud Yes! Solved!
I added a class instance to the root of the tree `add_child`. All is decided! It all worked!
Thank you so much!

**Comment by TimurKhan** [comment] 2019-02-07 16:00
PS Surprisingly another. Here is the test file. In it is the skeleton of my program. In contrast, it has many purely computational operations. And it works. But my code worked only after the announcement "add child" in the root
[Test.zip](https://github.com/godotengine/godot/files/2841640/Test.zip)

**Comment by groud** [comment] 2019-02-07 16:08
> Here is the test file. In it is the skeleton of my program. In contrast, it has many purely computational operations. And it works. But my code worked only after the announcement "add child" in the root

I am not sure about what this means, but without a reproduction test case it is going to be hard to tell.

Anyway, since the problem is solved I close the issue then :)

**Closed by groud** 2019-02-07 16:08 UTC
Labels: bug, topic:gdscript

**Comment by TimurKhan** [comment] 2019-02-07 16:26
@groud Thank you! You saved 6 months of my work
