### ISSUE TITLE
Distorted sprites when rotating 90 degrees with pixel_snap

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#29882] opened 2019-06-18 22:29 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
Pixels got distorted on a 90 degree rotated sprite. Expected to not get distortion, since it is a right angle rotation. Distorted sprite to the left. On the right side i rotated the sprite before adding to Godot, and it works as expected with 0 degrees rotation:

![image](https://user-images.githubusercontent.com/15088582/59723833-02830980-9228-11e9-9f3d-f9bd32f9c5e7.png)

**Steps to reproduce:**
Rotate a sprite to 90 degrees and enable pixel_snap in project settings. Move the sprite to a position where the pixels get distorted.

**Minimal reproduction project:**
[MobileShooter - Copy.zip](https://github.com/godotengine/godot/files/3303661/MobileShooter.-.Copy.zip)

**Comment by KoBeWi** [comment] 2019-06-18 22:31
Might be related to #20616

**Comment by fossegutten** [comment] 2019-06-18 22:44
Yes it might be, i got an around 90.00002 degree imprecision when i printed global_rotation_degrees. Kind of a big deal for pixel art games :) Have to rotate sprite in external image editor for now. Workaround is to keep duplicate sprites

**Comment by clayjohn** [comment] 2019-06-19 01:31
Duplicate of https://github.com/godotengine/godot/issues/29677

**Closed** 2019-06-19 07:59 UTC
Labels: bug, topic:core, topic:rendering

**Comment by fossegutten** [comment] 2019-06-19 11:22
Setting rotation in _ready does not work for me, with the attached project
