### ISSUE TITLE
'UV' appears to be calculated incorrectly for `PlaceholderTexture2D` in Canvas Item shader

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#77058] opened 2023-05-14 10:42 UTC
### Godot version

4.0.2-stable

### System information

Windows 10, NVIDIA GeForce GTX 1660 ti

### Issue description

The `UV` field in shaders **APPEARS** to be incorrect for `NoiseTexture2D` and `PlaceholderTexture2D`. I am still a shader noob so it's possible this is somehow intended. 

There are additional details and screenshots in the reproduction, but here is a screenshot, showing how `PlaceholderTexture2D` is acting different than a manually imported texture:

![image](https://github.com/godotengine/godot/assets/18729296/5ca06bf1-80e8-4aee-81f1-3e1bc540e367)

### Steps to reproduce

Create a shader with the following simple code:

```glsl
shader_type canvas_item;

void fragment() {
	COLOR.rgb = vec3(UV.y);
}
```

Create a number of `Sprite2D` nodes. Apply the material to all of them. Additionally, export a 500x500 blank texture from your application of choice. Or download something from the internet.

Next, apply textures using the drop-down. Here are my results:

1. PlaceholderTexture2D, with size set to 500x500: Sprite2D remains pure white, except for a small strip of gradient on the top (incorrect UV)
2. NoiseTexture2D, with size set to 500x500: Sprite2D remains pure white, except for a small strip of gradients on the top (incorrect UV)
3. Manually imported 500x500 texture: Sprite2D shows the correct gradient, matching the preview and the shader code.
4. GradientTexture2D, with size set to 500x500: Sprite2D shows the correct gradient, matching the preview and the shader code. Please note that the default `GradientTexture2D` is an x-axis gradient, this is why I made my shader code use `UV.y`

Expected results: I expect a `PlaceholderTexture2D` to act the same as an imported texture of the same size.

### Minimal reproduction project

Reproduction steps are very simple. But tag me and I can create a .zip if you feel it's really required.

**Comment by AThousandShips** [comment] 2023-05-14 10:45
> Reproduction steps are very simple. But tag me and I can create a .zip if you feel it's really required.

Since they are so simple, please add an MRP, otherwise *each* person testing this has to copy the steps, and important to see the exact conditions under which this happens for you, it just makes things easier for everyone

**Comment by AThousandShips** [comment] 2023-05-14 10:57
It does *not* happen if you set the noise texture up with an actual noise in my case

**Comment by AThousandShips** [comment] 2023-05-14 11:23
This is due to that internally a placeholder texture is just 4x4 pixels, and that's where the UV calculations are taken from

**Comment by AThousandShips** [comment] 2023-05-14 11:40
Duplicate of #65165

**Comment by kleonc** [comment] 2023-05-14 17:45
Duplicate of #65165.

**Closed by kleonc** 2023-05-14 17:45 UTC
Labels: archived
