### ISSUE TITLE
Scene editor not shows node struct when redo

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#8626] opened 2017-05-02 16:47 UTC
**Operating system or device - Godot version:**
Linux XUbuntu 16.04.2, Godot 2.1.3

**Issue description:**

When open a new project and add a Node2D and save and undo and redo, the node not shows in the scene editor. The error is not shows the nodes when redo.

**Steps to reproduce:**
-open a project
-add Node2D and save
-now press Ctrl+Z
-so pŕess Ctrl+Shift+Z
-see in the scene editor, the node not shown
-now add other Node2D and it it will be shown as sub node of the firstly added

**Link to minimal example project:**

**Comment by eon-s** [comment] 2017-05-02 22:29
It seems that redo if the root was removed does not update the scene tree.
You can see the node if you change scene tab and come back to the original.

Can be reproduced on Master too.

**Comment by Paulb23** [comment] 2017-11-16 23:19
Can now be closed. Also Fixed by #12976

**Comment by akien-mga** [comment] 2017-11-16 23:25
Duplicate of #6125, fixed by #12976.

**Closed by akien-mga** 2017-11-16 23:25 UTC
Labels: bug, topic:editor, usability
