### ISSUE TITLE
Project Autoload On Export To Home Folder On Linux

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4832] opened 2016-05-26 23:21 UTC
**Operating system or device - Godot version:**
Linux, Godot version 2.0.3

**Issue description** (what happened, and what was expected):
I exported my project to my home directory and on next load of Godot it loads and runs my project instead of bringing up the project manager and editor.

**Steps to reproduce:**
Export an X11 to your project folder. Load Godot. My Godot executable is in /usr/bin, I don't know if that has anything to do with it.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-05-27 06:31
That's the expected behaviour. The Godot binary does not keep track of the location of your game's data, but instead looks for the presence of ``data.pck``, ``data.zip`` or an ``engine.cfg`` file in the current directory or its parent directory.

You can work it around by using the ``-pm`` argument to force opening the project manager: ``godot -pm``. But generally speaking, you should mostly move your data.pck to ``$(HOME)/mygame`` instead of ``$(HOME)`` or something like that :)

**Comment by bojidar-bg** [comment] 2016-05-27 07:56
@akien-mga ~ We should probably encourage `.desktop` file writers to add `-pm` anyway...

**Comment by bojidar-bg** [comment] 2016-05-27 07:56
Also, related/duplicate of #4787.

**Comment by akien-mga** [comment] 2016-05-27 08:02
> We should probably encourage .desktop file writers to add -pm anyway...

That's a good point, I should add that to my Mageia RPM :)

**Comment by bojidar-bg** [comment] 2016-05-27 08:07
@akien-mga Lemme guess --- `$HOME`.

**Comment by toliaferrode** [comment] 2016-05-27 21:30
Thanks guys.

**Comment by neikeq** [comment] 2016-05-28 12:02
Closing as solved. Feel free to open it if there is something missing.

**Closed by neikeq** 2016-05-28 12:02 UTC
