### ISSUE TITLE
Can't keep_3d_linear in Subviewport Godot 4

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot#63557] opened 2022-07-27 22:19 UTC
### Godot version

4.0.alpha12

### System information

Pop!OS 22.04, Ryzen 7 5800h, Nvidia RTX 3070 mobile

### Issue description

in Godot 3.x there is an option in Viewport Node :
keep_3d_linear 
detailed desc for what it does : 

"If true, the result after 3D rendering will not have a linear to sRGB color conversion applied. This is important when the viewport is used as a render target where the result is used as a texture on a 3D object rendered in another viewport. It is also important if the viewport is used to create data that is not color based (noise, heightmaps, pickmaps, etc.). Do not enable this when the viewport is used as a texture on a 2D object or if the viewport is your final output. For the GLES2 driver this will convert the sRGB output to linear, this should only be used for VR plugins that require input in linear color space!"

so it doesn't exist now in Godot Engine 4

### Steps to reproduce

any godot engine 4 alpha 12 project
make a new SubViewport Node 
the option isn't available. 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment] 2022-07-27 22:24
Duplicate of https://github.com/godotengine/godot/issues/41406.

**Closed by Calinou** 2022-07-27 22:24 UTC
Labels: archived, topic:rendering, topic:3d

**Comment by ywmaa** [comment] 2022-07-27 22:27
sorry, but for some reason I kept searching and couldn't find it.
