### ISSUE TITLE
Properties Added With _get_property_list() Are Not Being Set

### ISSUE THREAD

**Issue by Kalcen** [godotengine/godot#68797] opened 2022-11-17 15:38 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10

### Issue description

I'm trying to learn how to make custom addons, and I'm having some issues getting custom properties to work. I prefer using `_get_property_list()` since it allows me to assign properties to groups, but for some reason the properties wont change in the inspector. I'm aware of the `_get(property)` and `_set(property, value)` functions, but they seemed ineffective when I tried using them, but I could be misunderstanding their functionality.

Overall `_get_property_list()` seems kind of hackey to use right now, especially since I have to use `get(property)` to access them in code... so it would be really nice if I could add `@export` vars to groups instead as making and referencing those are way easier.

### Steps to reproduce

Install the custom plugin, enable it and place its custom node SceneProperties into a 3D scene. The script containing `_get_property_list()` is `scene_properties.gd`.

### Minimal reproduction project

[scene_properties_issue.zip](https://github.com/godotengine/godot/files/10033028/scene_properties_issue.zip)

**Comment by Mickeon** [comment] 2022-11-17 16:44
> I'm aware of the `_get(property)` and `_set(property, value)` functions, but they seemed ineffective when I tried using them, but I could be misunderstanding their functionality.

I tried using them as well when updating the documentation and unlike 3.x, they do not seem to work at all, I can back you up on this.

**Comment by KoBeWi** [comment] 2022-11-17 18:39
Can't reproduce. Are you sure you are using it correctly?
```GDScript
@tool
extends Node

var test = 0

func _get_property_list() -> Array:
	return [{name = "test", type = TYPE_INT}]

func _get(property: StringName):
	if property == &"test":
		return test

func _set(property: StringName, value) -> bool:
	if property == &"test":
		test = value
		return true
	return false
```

**Comment by Kalcen** [comment] 2022-11-18 18:10
It looks like @KoBeWi 's  script was they key and the property now updates when changed in the inspector. Also `@export_group` works as well. Thanks so much for the clarification and the help!

**Comment by KoBeWi** [comment] 2022-11-18 20:50
Closing. Not sure what you tried, but your script is missing `_get()` and `_set()`, which are responsible for reading and writing the properties. `_get_property_list()` only defines the properties, but doesn't handle them.

**Closed by KoBeWi** 2022-11-18 20:50 UTC
Labels: topic:editor, needs testing

**Comment by Kalcen** [comment] 2022-11-20 22:17
> Closing. Not sure what you tried, but your script is missing `_get()` and `_set()`, which are responsible for reading and writing the properties. `_get_property_list()` only defines the properties, but doesn't handle them.

The original script didn't contain _get() _set() because I was unsure of how to properly use it due to a lack of examples in the documentation. Once I copied the syntax used in you're example, the functions worked properly.

**Comment by YuriSizov** [comment] 2022-11-21 00:23
@Kalcen You can also have normal, unexposed (no `@export`) properties and then expose them with `_get_property_list`. Then you don't need `_get` and `_set`, as the variable itself will be used. You can still define your own setter and getter using the new property syntax (or `setget` in 3.x).

So actually, since KoBeWi used the same name, this also works:

```gdscript

@tool
extends Node

var test = 0

func _get_property_list() -> Array:
	return [{name = "test", type = TYPE_INT}]
```

**Comment by donn-xx** [comment] 2022-12-07 13:01
None of the samples on this page seem to work in Godot 4 Beta 7.

The simple one above by @YuriSizov  shows no property at all. 

The one in the docs at (https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-get-property-list) does not seem to do anything either. All you see is the @exported property, but nothing else happens.

Putting a print("foo") into the _get_property_list() func does not print foo.

Is this a bug or am I doing a dumb?

**Comment by YuriSizov** [comment] 2022-12-07 13:25
@donn-xx Did you forget to make your script `@tool`?

**Comment by donn-xx** [comment] 2022-12-07 18:22
@YuriSizov It does use @tool — but reloading the scene worked. Thank you!

(I think reloading the scene should not be required, but maybe that's being worked on.)

**Comment by donn-xx** [comment] 2022-12-14 16:25
I have since learned to not use _set or _get as they really cause wierd behaviour in other nodes. For example, for some reason a multimesh node stopped working at all. I can't find the sense of it, nor how to reproduce it, but when I use the new get: and set(v): on the @export vars, things work better.

**Comment by YuriSizov** [comment] 2022-12-14 17:19
Methods prefixed with `_` are internal, you don't call them, you only implement them. Externally you use methods without a prefix. Neither of them is new.

**Comment by donn-xx** [comment] 2022-12-15 07:28
Yes, I grok that. I'll try to reproduce the problem. Sorry for being vague.

**Comment by donn-xx** [comment] 2022-12-15 15:00
Is there any way to supply tooltips from the _get_property_list() func? Like the ## remarks above an @export command currently does?

**Comment by YuriSizov** [comment] 2022-12-15 16:13
No, there is not. Please don't use GitHub for support questions. Refer to our community platforms instead.
