### ISSUE TITLE
Improving workflow to change Windows game icon (PE data edition)

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#21347] opened 2018-08-24 05:32 UTC
**Godot version:**
v3.1.dev.calinou.5df9109

**OS/device including version:**
windows 10 x64

**Issue description:**
When export to windows desktop with application icon set to icon file, the created executable has the default godot icon.

**Steps to produce:**
Export >> Windows Desktop >> select an icon for the Icon parameter >> Export

**Comment by Calinou** [comment] 2018-08-24 06:39
You need to follow the instructions from the [Changing application icon for Windows](http://docs.godotengine.org/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html) page before the icon can effectively be modified when exporting.

I think this should be made clearer on the Export dialog to avoid confusion.

**Comment by Yuki001** [comment] 2018-08-24 11:15
I just replace the icon successfully. The new ico file must contains : 16*16 32*32 48*48 64*64 128*128 256*256 subimages to replace the godot default icon. 
And you can export the same exe file twice to avoid Issue #21360

**Comment by aaronfranke** [comment] 2018-08-28 07:01
Would it be possible for Godot to automatically create an ICO file from "icon.png"? If it's too big a library to include in Godot, perhaps it could search for if other tools like ImageMagick are installed.

**Comment by Xrayez** [comment] 2018-12-19 18:06
As suggested in the docs I've successfully converted icon with the following command:
```sh
convert icon.png -define icon:auto-resize=256,128,84,64,63,60,56,48,47,42,40,32,31,30,28,24,20,16 icon.ico
```
(had to drop `magick` from it, I think it depends on how you get the ImageMagick binaries)

The only issue is that I can't convert it with high-DPI resolutions (512, 1024 etc):
```
convert: InvalidDimensions `icon.ico' @ error/icon.c/WriteICONImage/908.
```

**Comment by Garrom** [comment] 2019-04-07 16:54
I have problems with it too. I'm unable to set icon to exe file. Using wine and rcedit from terminal results with `error fixme:ver:GetCurrentPackageId (0x23fd40 (nil)): stub`

**Comment by Calinou** [comment] 2020-11-21 14:35
Duplicate of https://github.com/godotengine/godot/issues/27765.

**Closed by Calinou** 2020-11-21 14:35 UTC
Labels: enhancement, platform:windows, topic:editor
