### ISSUE TITLE
Adding a texture smaller than a TileMap cell size breaks the TileSet editor

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#54839] opened 2021-11-10 15:45 UTC
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

When you place a Texture in the TileSet editor that is smaller than the TileMap cell size, the TileSet editor stop working. You are not able anymore to add or edit tiles. Even if you reduce the cell size a restart of Godot is necessary.

### Steps to reproduce

1. create a TileMap node and change its cell size to something bigger than your tile set texture.
2. Create a new TileSet in the tile_set property of TileMap.
3. Add your tile set texture in the TileSet editor
4. Try to create a tile
5. The TileSet editor is broken

### Minimal reproduction project

[TilesetIssue.zip](https://github.com/godotengine/godot/files/7514023/TilesetIssue.zip)

**Comment by boruok** [comment] 2021-11-11 00:18
related to #54691 and #52760

**Comment by golddotasksquestions** [comment] 2021-11-16 20:14
I can't confirm this bugreport.

I tried to replicate, but I only noticed https://github.com/godotengine/godot/issues/52760, meaning as soon as you click on the zoom + or - everything works as expected.

Steps I tried to replicate:
Create a new TileMap, set cell size to 128x128
Create a new Tileset, load the icon.png as texture
create a new Single Tile (here you have to first click the zoom + or -)
click on the TileMap in the Scene Panel and start drawing tiles.

works fine

@boruok can you confirm you also just observed the #52760 bug?

**Comment by BraindeadBZH** [comment] 2021-11-17 08:55
> 
> 
> I can't confirm this bugreport.
> 
> I tried to replicate, but I only noticed #52760, meaning as soon as you click on the zoom + or - everything works as expected.
> 
> Steps I tried to replicate: Create a new TileMap, set cell size to 128x128 Create a new Tileset, load the icon.png as texture (which is 64x64) create a new Single Tile (here you have to first click the zoom + or -) click on the TileMap in the Scene Panel and start drawing tiles.
> 
> works fine
> 
> @BraindeadBZH can you confirm you also just observed the #52760 bug?

Effectively, by zooming in/out seems to "fix" my issue.

**Comment by akien-mga** [comment] 2021-11-17 09:20
Duplicate of #52760

**Closed by akien-mga** 2021-11-17 09:20 UTC
Labels: bug, topic:editor, topic:2d
