### ISSUE TITLE
Calling set_name() on Sprite3D crashes the game 

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#926] opened 2014-12-05 22:04 UTC
Game crashes without error message.
```javascript
-------------------

var bloodSplatterAsset = preload("res://level building blocks/Blood Splatter.xscn")

func takeHit(amount):
	health = health - amount	
	
	print("health now: "+str(health))
	
	var blood = bloodSplatterAsset.instance()
	#blood.set_name(currBloodName) # setting a name does not work on Sprite3D ?!?!
	var bloodPos = self.get_parent_spatial().get_translation() + self.get_translation()
		
	blood.set_translation(bloodPos)
	get_node("/root/Level").add_child(blood)
	
	blood.get_node("AnimationPlayer").play("splatter")
	var playingAnim = yield(blood.get_node("AnimationPlayer"), "finished")
	
	var currSplatter = get_node("/root/Level/Blood Splatter")
	if (currSplatter != null):
		#print("delete splatter")
		currSplatter.queue_free()
	
```javascript

**Comment by bojidar-bg** [comment] 2015-05-10 15:13
Does this work without yield? I've heard that yield is not well supported in GDScript...

**Comment by kubecz3k** [comment] 2015-11-02 10:55
Bug is quite old and I cannot reproduce it in any way in d123c89c5802777e02402108d9271ed2f29368fe build. It look like it's fixed now. Feel free to open new issue with some simple test case project if it's still in force.

**Closed by kubecz3k** 2015-11-02 10:55 UTC
Labels: archived, bug, topic:core
