### ISSUE TITLE
`Clip Children` creates a screen mirror on Mobile renderer 

### ISSUE THREAD

**Issue by reptofrog** [godotengine/godot#80426] opened 2023-08-08 18:11 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Fedora Linux 38 (Workstation Edition), GNOME 44.3 Wayland

### Issue description

`Clip Children` creates a screen mirror on Mobile renderer.

[Screencast from 2023-08-08 22-00-30.webm](https://github.com/godotengine/godot/assets/36744029/9cf48c43-1efd-40b5-8679-9b062cedb8d5)

---

![Screenshot from 2023-08-08 22-08-10](https://github.com/godotengine/godot/assets/36744029/a969edce-1e14-4ece-bb02-22606182f2cd)

[Screencast from 2023-08-08 22-10-42.webm](https://github.com/godotengine/godot/assets/36744029/bd584631-627e-43b4-bf45-52adfd1d6743)

### Steps to reproduce

1) Switch to Mobile renderer
2) Create a `TextureRect` or a `Sprite2D`
3) Give it a texture with transparency
4) Put anything inside of it
5) Enable `Clip Only` in `Clip Children`

### Minimal reproduction project

[Clip Children Screen Mirror Bug.zip](https://github.com/godotengine/godot/files/12294577/Clip.Children.Screen.Mirror.Bug.zip)

**Comment by AThousandShips** [comment] 2023-08-08 18:13
Thank you for reporting, duplicate of:
* #75956

**Closed by AThousandShips** 2023-08-08 18:13 UTC
