### ISSUE TITLE
Regression: ui_text_caret_left includes $

### ISSUE THREAD

**Issue by novalis** [godotengine/godot#81384] opened 2023-09-06 15:19 UTC
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - Debian GNU/Linux bookworm/sid bookworm - Vulkan (Forward+) - dedicated AMD Radeon RX 5600 XT (RADV NAVI10) () - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

Consider the following code:
```
func foo():
    $Foo.text = "foo"
    #     ^<-- cursor is here
```

In the Godot editor, when I press ctrl-left (ui_text_caret_left) in Godot 3.x, ny cursor goes to just after the $.  In 4.1, my cursor goes to just before $.  This is not what I prefer, because what I usually want to do is to insert another layer of UI.  Or maybe I want to replace $Up with $Down because I've copy-pasted.  Now I have to type the $ again.

### Steps to reproduce

Move all your UI elements into a VBoxContainer because you suddenly realize that you need another column.  Try to insert `V/` in front of all node names.  Get annoyed because you can't use ctrl-left to navigate to the beginning of the node name.

### Minimal reproduction project

n/a

**Comment by MewPurPur** [comment] 2023-09-06 15:51
This has been reported before; it's a bug that's existed before 4.0 was in alpha.

**Comment by AThousandShips** [comment] 2023-09-06 15:57
Related:
* https://github.com/godotengine/godot/issues/56402

**Comment by KoBeWi** [comment] 2023-09-06 16:11
Closing as duplicate of #56402, as it has the same cause.
From what I understand this is intended behavior, but it's inconsistent between `$` and `%`.

**Closed by KoBeWi** 2023-09-06 16:11 UTC
