### ISSUE TITLE
Visual shader editor node selection and position issues

### ISSUE THREAD

**Issue by jscheel** [godotengine/godot#10989] opened 2017-09-05 04:56 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOS: 10.12.5 macbook pro (retina)
godot: 2.1.3 and 2.1.4

**Issue description:**
- After adding a node, several nodes will be randomly selected. (2.1.3 and 2.1.4)
- Randomly, when selecting a node or making a connection, several other nodes will be selected. (2.1.3 and 2.1.4)
- Sometimes, you cannot deselect a node. (2.1.4, haven't replicated on 2.1.3)
- When panning, if a node is selected, the node moves as well. (2.1.4)
- After deleting a node, several random nodes are selected. When the mouse moves all of the selected nodes are repositioned on top of each-other. (2.1.3 and 2.1.4)
- Node positions are hidpi dependent. Meaning, if I organize my graph on a retina display, then open godot on a normal display, the nodes are 2x further apart from each-other. (only tested on 2.1.4, will have to test 2.1.3 when I have my other monitor again)

<img width="226" alt="Example of post-delete repositioning" src="https://user-images.githubusercontent.com/211478/30045888-8873daaa-91cc-11e7-95bf-3b2d83707310.png">
(Example of post-delete repositioning)

**Comment by blurymind** [comment] 2017-09-05 15:41
I also get this bug, it's really annoying.

Sometimes nodes get constantly resized too

**Comment by jscheel** [comment] 2017-09-05 16:31
Ok, added 2.x versions that each issue have been tested on, and added another issue regarding hidpi positioning of nodes.

**Comment by eon-s** [comment] 2017-09-06 19:26
The issue is on GraphEdit too or just the shader editor? (I don´t remember this problem on 2.2 visual script editor)

**Comment by jscheel** [comment] 2017-09-06 19:35
@eon-s as in a GraphEdit node placed in a scene, or is there another place?

**Comment by eon-s** [comment] 2017-09-06 20:08
I was sure that saw this before #4433 

Maybe the fix was not ported to 2.1.

**Comment by akien-mga** [comment] 2018-09-17 14:20
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Closed by akien-mga** 2018-09-17 14:20 UTC
Labels: bug, topic:editor
