### ISSUE TITLE
web load

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#1864] opened 2015-05-08 03:39 UTC
Hope to be able to support web loading
For example:

func _ready():
  texture = load("http://www.google.com/logo.png")

**Comment by reduz** [comment] 2015-05-09 21:31
I suppose an asynchronous loading function should be added eventually..

**Comment by cjmxp** [comment] 2015-06-19 01:20
Try to integrate curl Lib

**Comment by reduz** [comment] 2015-06-19 01:47
godot already has http support and ability to do http requests on a thread,
it' s not that difficult

**Comment by marcosbitetti** [comment] 2015-06-19 10:04
The only difficult is manage HTTP return messages, like redirects. I work on it http://pastebin.com/uZKSkJL3

**Comment by akien-mga** [comment] 2015-11-16 14:00
Duplicate of #2310...

**Closed by akien-mga** 2015-11-16 14:00 UTC
