### ISSUE TITLE
Duplicating a scene in the editor makes them have the same uid

### ISSUE THREAD

**Issue by groud** [godotengine/godot#55577] opened 2021-12-03 10:02 UTC
### Godot version

4.0dev

### System information

Linux

### Issue description

Duplicating a scene in the editor leads them to share the same uid. This leads to issues at instantiation time, as usually one of the two scenes will be instantiated instead of the other.

To workaround the issue, I had to remove in a text editor the uid field in the .tscn file, so it is definitely this same uid in both scenes that caused the issue.

### Steps to reproduce

Duplicate a scene in the file system dock, modify one of them, and instantiate them both in another scene.
Run this last scene, and notice that the same scene will be instantiated twice.

### Minimal reproduction project

Ask if needed.

**Comment by akien-mga** [comment] 2021-12-03 10:13
Duplicate of #54774.

**Closed by akien-mga** 2021-12-03 10:13 UTC
Labels: bug, topic:core, topic:editor
