### ISSUE TITLE
Horizontal scroll does not work in AnimationPlayer interface

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#54567] opened 2021-11-03 20:43 UTC
### Godot version

3.3.4.stable.official (Steam)

### System information

macOS High Sierra 10.13.6, MacBook 2010 geforce 320m

### Issue description

Horizontal scroll (by Magic Mouse or trackpad) does not work on AnimationPlayer window.

### Steps to reproduce

Create AnimationPlayer node
Create new animation
Increase animation length
Try to perform a horizontal scroll with touch

### Minimal reproduction project

[godotanim.zip](https://github.com/godotengine/godot/files/7470557/godotanim.zip)

**Comment by Calinou** [comment] 2021-11-03 21:14
Duplicate of https://github.com/godotengine/godot/issues/28077 (and https://github.com/godotengine/godot/issues/38237 to an extent).

**Closed by Calinou** 2021-11-03 21:14 UTC
