### ISSUE TITLE
Reverts prefabs to default (editable children)

### ISSUE THREAD

**Issue by BTK-InterBlock** [godotengine/godot#33786] opened 2019-11-21 13:25 UTC
Godot version: 3.2 beta 1

OS/device including version: windows 10

I prepared a prefab (scene) for my project. Then I use that prefab in the root scene. I right-click on that node in the editor and select editable children. change some colors, size and save. 
problem is when you move that prefab to another node. When I did that prefab automatically lost the editable children option. I saved everything and restarted Godot.exe and then I saw that all prefabs are reverted back to default.

video: https://www.dropbox.com/s/n61acuojpdnchuq/Test.mp4?dl=0

**Comment by KoBeWi** [comment] 2019-11-21 15:15
Duplicate of #23979

**Closed by KoBeWi** 2019-11-21 15:15 UTC
