### ISSUE TITLE
PBR Roughness is broken in 4.0 beta

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#69476] opened 2022-12-02 07:54 UTC
### Godot version

4.0 beta 7

### System information

Windows 10 960m

### Issue description

There seems to be several issues currently with roughness in spatial materials in 4.0.
The first one that I observed was that a full black albedo material could have no reflections, either from the environment (hdri or procedural sky) or lights, regardless of the roughness amount. Albedo color should not effect roughness.

This is how it looks in 3.5 with a procedural sky which is correct:

https://user-images.githubusercontent.com/7741669/205240916-c84a22bf-e847-4fd7-ab4f-7dea71896ade.mp4

This is how it looks in 4.0 with metallic showing nothing, but non-metallic is ok:

https://user-images.githubusercontent.com/7741669/205240842-558b8100-fc41-43b9-acc8-4fea1e870f3a.mp4

In 3.5 with just an omni:

https://user-images.githubusercontent.com/7741669/205241164-0f1fa0b8-d78d-43ff-84ac-0fbf645223a9.mp4

In 4.0 with an omni:

https://user-images.githubusercontent.com/7741669/205241259-1a5f564e-dd96-46d8-acb7-6a3ecaaa0508.mp4

A most likely related issue is the roughness in general looks much less rough than it should.

Here is a comparison using a hdri and a metallic material in 3.5 and 4.0:

![godot_metallic](https://user-images.githubusercontent.com/7741669/205241609-4117ac28-7743-43f5-878b-400efec4f6b1.jpg)

And for reference in Blender and Substance Painter. As can be seen 3.5 is very close, but 4.0 is not rough enough:

![blender_substance_metallic](https://user-images.githubusercontent.com/7741669/205241795-dcefc83c-1d2b-4370-beaf-481c1dbdea0a.jpg)
Here are the same comparisons using a dielectirc material for all 4 apps:

![godot_dielectric](https://user-images.githubusercontent.com/7741669/205242087-8771a24f-b691-4fc5-bc12-e35dc8e7ac31.jpg)

![blender_substance_dielectric](https://user-images.githubusercontent.com/7741669/205242127-11462f25-7d64-4d7e-9a8b-7e9b2b00b288.jpg)

@clayjohn this is probably up your alley! Afaik these issues have been in 4.0 for a while.

 

 

### Steps to reproduce

- Create a sphere
- Give ir a material with pure black albedo and add a light and/or a sky to the scene
- No reflections will be seen on the sphere

### Minimal reproduction project

[hdri_roughness.zip](https://github.com/godotengine/godot/files/10139085/hdri_roughness.zip)

**Comment by mrjustaguy** [comment] 2022-12-02 08:06
This is the Mobile renderer?

**Comment by fracteed** [comment] 2022-12-02 08:11
No, it is the Vulkan forward renderer. Haven't tried the others, but am guessing they have the same issue.

**Comment by clayjohn** [comment] 2022-12-02 17:11
Looking into these now. The metallic/albedo issue doesn't look like a bug to me. An albedo value of (0,0,0) should eliminate specular reflections in a purely metallic material. You can observe the same behaviour in Blender for example. 

The roughness indeed looks off, so I will take a closer look and see if it is something that we can fix

**Comment by fracteed** [comment] 2022-12-02 23:33
@clayjohn That is not correct in blender. Not sure how you are getting that result, but the pure black will kill reflections in the facing but not all of the grazing angle reflections ...as can be seen in these videos. They all have the same hdri, with material as full metallic, roughness of 0, ramping up from full black to full white in the albedeo:

Eevee:


https://user-images.githubusercontent.com/7741669/205406766-7dab7b04-e8e1-4948-8f9c-7dfaa829b46c.mp4

Cycles path tracer (which is ground truth in PBR):


https://user-images.githubusercontent.com/7741669/205406988-4c2cc229-b1d0-43d2-a096-4114bd867b03.mp4

Substance Painter:


https://user-images.githubusercontent.com/7741669/205407074-19745b75-55da-4d13-95cf-c258009e3a77.mp4

And godot 4 , which looks like the facing and grazing angles are both going up and down at the same rate:

https://user-images.githubusercontent.com/7741669/205407282-65c763be-5b1a-4179-8e11-d350b2eb7fd0.mp4

**Comment by clayjohn** [comment] 2022-12-02 23:52
@fracteed All I did was turn metallic to 1.0 and base color to black:

![Screenshot (302)](https://user-images.githubusercontent.com/16521339/205410167-f88bf36b-88a3-4037-b5c3-39394ed26f5a.png)

Unreal Engine is the exact same. With Metallic at 1.0 and albedo at black, there are no reflections

![Screenshot (300)](https://user-images.githubusercontent.com/16521339/205410163-0cca101a-73f8-4b98-96b9-e08605e67079.png)

I can't see your settings in blender above, but for substance you can see that substance differentiates between base color and Metallic color and metallic color is set to white. That is likely where the reflections are coming from. In game engines we usually simplify and make albedo turn into "metallic color" based on the metallic value. Perhaps in Blender you are also using a BRDF

**Comment by fracteed** [comment] 2022-12-02 23:56
@clayjohn Here is the blend file. And showing in blender changing the metallic slider from full to no metallic. The grazing reflections are not really changing, only the facing. Jist using the default principled BSDF.

https://user-images.githubusercontent.com/7741669/205410580-cd602b0a-d2b9-4bbc-8738-ab9d2c95f6ab.mp4


[roughness_metallic_black.zip](https://github.com/godotengine/godot/files/10145096/roughness_metallic_black.zip)

**Comment by clayjohn** [comment] 2022-12-03 00:18
@fracteed Opening that blend file is giving me the same results I got before. I'm downloading the latest version of blender now to see if the difference is caused by my blender being out of date

**Comment by fracteed** [comment] 2022-12-03 00:26
@clayjohn That was done in blender 3.3. If you want to send me the blend file you are using I can look at it.

Just tried in Unity, as I don't have Unreal installed. Not sure how to put in the hdri, so just using the default sky. Same material with 0 roughness and scrubbing between metallic range of 0-1 and base color or 0 -1. Getting the same result as I would expect. 


https://user-images.githubusercontent.com/7741669/205412602-5f5e064e-097b-47a5-8375-20efbca8d93a.mp4

**Comment by fracteed** [comment] 2022-12-03 00:43
@clayjohn and lastly, here it is shown in Substance Designer. You can see from the node graph what is going on. Black color, black for roughness (ie 0) and I am scrubbing the metallic from full black to white range. As can be seen the grazing reflections stay unchanged:

https://user-images.githubusercontent.com/7741669/205413637-ccd315ea-b2b2-4eb2-a3a6-08fe766ca31b.mp4

**Comment by clayjohn** [comment] 2022-12-03 00:49
@fracteed Thanks for following up. With Blender 3.3 I am now getting the same results you are. I have also taken a closer look at Godot 3.5 and am convinced that you are right, the old behaviour is more "correct". I'll take a look at the current PBR stuff and see if I can spot what regressed.

**Comment by fracteed** [comment] 2022-12-03 00:55
@clayjohn good to hear, as I had run out of PBR renderers to demo it on :)

**Comment by fracteed** [comment] 2022-12-03 00:56
@clayjohn and just on a related note. Is it a known issue that hdri's look so bad in the background in 4.0? If you look at the hdri in this issue in 3.5 it is fine, but in 4.0 it is distorted. I can file a separate issue if this is not already known.

**Comment by clayjohn** [comment] 2022-12-03 00:59
> @clayjohn and just on a related note. Is it a known issue that hdri's look so bad in the background in 4.0? If you look at the hdri in this issue in 3.5 it is fine, but in 4.0 it is distorted. I can file a separate issue if this is not already known.

@fracteed Kind of, the HDRI compressor is really broken. I couldn't even open your scene on my device, I had to manually edit the ``.import`` file to disable VRAM compression. With VRAM compression disabled the background looks fine

**Comment by clayjohn** [comment] 2022-12-03 01:12
Now that I have refreshed myself on the issue, I am put in a difficult place. Very technically speaking, an albedo value of (0,0,0) is not physically plausible for a metallic object. Metals can only have an albedo between 0.66 and 1.0 see chart [here](https://google.github.io/filament/images/material_chart.jpg). Anything outside that range is no longer physically based. 

In https://github.com/godotengine/godot/issues/40753 I mentioned the above fact in support of the 3.x behaviour (the behaviour that you want restored). 

However, I later added https://github.com/godotengine/godot/pull/63587 as I was increasingly seeing something like https://github.com/godotengine/godot/pull/63587 implemented in other engines and was finally swayed by https://github.com/godotengine/godot-proposals/issues/4818. At the time, it made sense to me that an object with an albedo of (0,0,0) would absorb all incoming light. Technically speaking that is what should happen under our PBR definition of albedo despite the fact that an albedo of (0,0,0) does not exist in the real world. Also, at the time it appeared that all other PBR renderers had the same behaviour. 

Now the story is a bit different. Eevee has flipped and is now back to our old behaviour. Unity and Substance use the old behaviour. Unreal, Filament, and Frostbite all use the same behaviour that we now use in Godot 4.0. So it is totally unclear to me which we should go with. 

Filament has by far the best discussion/justification for why they use their current behaviour (they cite frostbite in doing so) https://google.github.io/filament/Filament.html#lighting/occlusion/specularocclusion

**Comment by fracteed** [comment] 2022-12-03 01:14
> @fracteed Thanks for following up. With Blender 3.3 I am now getting the same results you are. I have also taken a closer look at Godot 3.5 and am convinced that you are right, the old behaviour is more "correct". I'll take a look at the current PBR stuff and see if I can spot what regressed.
> 
> _Edit: Naturally this is going to be more complex than it at first seems. The regression comes from #63587 which was implemented in response to [godotengine/godot-proposals#4818](https://github.com/godotengine/godot-proposals/issues/4818) Which was an extension of #40753. The trouble is #40753 was reporting as a bug, the exact behaviour you are asking to be implemented. In that Issue the user insists that all PBR renderers extinguish the specular reflection if the base color is dropped to solid black._

Oh wow, I hadn't seen that "issue" before. I really think that this user was off base and doesn't really understand how pbr should work. Of course it is all approximations, and a user needs to find clever ways around the specular and reflection problems. There is a lot confusion in general in the blender and godot community with the default 0.5 specular value, as you no doubt know!

The gold standard for a realtime renderer should be comparing it with a path tracer. For instance Cycles and Eevee are designed to be as close as possible to each other. Everyone from studios to indies use the substance tools and these match up almost perfectly with Blender and Unity/Unreal. Godot 4 should definitely be trying to match Blender as closely as possible, which will also mean compliance with the Substance. Godot 3.5 was very close, though it still looked slightly off in the grazing angle, but it was much more acceptable than what is happening in 4.0.

**Comment by fracteed** [comment] 2022-12-03 01:19
@clayjohn ah, sorry I was typing before I read your comment. I did not realise that Filament and Unreal were different is this respect. Interesting but annoying! Funnily enough I use pure black metallic materials in my game which is why I noticed this change from 3.5.

Personally I think 4.0 should match Blender and Substance in this regard as that is what 99% of users will be using, but I understand this is a problem if you are basing the pbr code on Filament.

**Comment by fracteed** [comment] 2022-12-03 01:27
@clayjohn It would also be interesting to know if the path tracer in Unreal also uses this behaviour as well as their realtime engine? I have used tons of offline path tracers for rendering and never seen this behavior. Even though I understand that it may be more physically since there are not any close to black materials in the real world. 

Ideally you should stick to the 16-235 range for realistic materials I agree. As I work in motion graphics, I tend to like bending the rules with pbr when appropriate and prefer the "old" method which gives more control. This also would apply to npr style games as I am currently making. If I wanted a full black material, then I would just use an unshaded material.

**Comment by fracteed** [comment] 2022-12-03 02:11
@clayjohn and just for curiosity, I did look up some photos of real world black metal spheres. They are actually very reflective, and I can't even see the facing angle reflections disappear (which happens in the pbr approximation)

This is black tungsten carbide:
![Carbide-Ball](https://user-images.githubusercontent.com/7741669/205417363-c3be8419-3ef9-44db-a8c5-d2557936784a.jpg)

And electroplated black (titanium) stainless steel (I couldn't download the photos):
https://metalsphere.com/product/black-stainless-steel-gazing-ball/

Much closer to the blender/substance look and what all path tracers that I have used do. Maybe it is something that should be put up for the community to vote on?

**Comment by clayjohn** [comment] 2022-12-03 02:47
> @clayjohn It would also be interesting to know if the path tracer in Unreal also uses this behaviour as well as their realtime engine? I have used tons of offline path tracers for rendering and never seen this behavior. Even though I understand that it may be more physically accurate since there are not any close to black metals materials in the real world.

I just checked Unreal engine's path tracer (in version 4.26) and it is the same behaviour as the realtime engine. Albedo (0,0,0) is solid black. As soon as Albedo is (1,1,1) there are reflections.

**Comment by clayjohn** [comment] 2022-12-03 03:10
Well, I have an idea that may make everyone happy enough. To me, the most important part of https://github.com/godotengine/godot/pull/63587 was that it allows users to treat a specular of less than 0.02 as a signal to disable specular reflections with dielectric materials. This is standard behaviour in other PBR engines. As a side-effect of doing so is that reflections are also effectively disabled when using a black albedo with metals. 

I can modify the code so that it only has an impact on dielectric materials. This matches the behaviour in Eevee which allows using specular to scale reflections on dielectrics, but does not eliminate reflections in metals when albedo is (0,0,0). 

The only holdback I have is that the user who reported https://github.com/godotengine/godot/issues/40753 explicitly claims that metals with an albedo of (0,0,0) should have no reflections whatsoever. So at least one person desires that behaviour.

I will make a draft PR for testing and discussion. Let me know if you need access to a binary to test or if you can compile it yourself.

**Comment by fracteed** [comment] 2022-12-03 03:25
@clayjohn thanks for all your attention on this matter! It is interesting that Unreal went in that direction. I guess at the end of the day most Godot users will author in Blender and/or Substance so will expect them to look as close as possible. I do realise that the matter I am talking about is a somewhat corner case, but I still think a realtime pbr renderer should be as close as possible to an offline path tracer (the Unreal path tracer being the exception).

Out of interest I did a quick render test in Blender between eevee and cycle. The first 2 spheres are metallic (roughness of 0 and 1 respectively). The last 2 spheres are dielectric (roughness of 0 and 1). What I am seeing in the Unreal/Filament style is what I would expect for a full black, full roughness material. So with the Blender method you can get both, just using the roughness. 

Cycles: 
![cycles_comparison](https://user-images.githubusercontent.com/7741669/205420444-413d2ab6-a0db-42c2-9f44-73c0c4315072.jpg)

Eevee:
![eevee_comparison](https://user-images.githubusercontent.com/7741669/205420451-26d31aee-af52-4707-b0e9-529eac7275bb.jpg)


I personally rarely touch the 0.5 spec default except maybe for ice and water or skin. Are you proposing that the godot method will look the same as eevee unless you actually change the specular from 0.5? Yes, I think I can download directly from the github autobuild if a PR is put up. I haven't compiled it myself in a long time.

**Comment by clayjohn** [comment] 2022-12-03 03:33
> I personally rarely touch the 0.5 spec default except maybe for ice and water or skin. Are you proposing that the godot method will look the same as eevee unless you actually change the specular from 0.5? 

More or less yes. Right now Godot ignores specular for metallic materials (for the purposes of IBL reflection anyway). While in Eevee a specular value of 0 removes the reflection regardless of whether the material is a dieletric or metal. My proposed middle ground would leave the specular behavior the same in Godot, but would change it so that an albedo of (0,0,0) would not remove reflections in metals.

**Comment by fracteed** [comment] 2022-12-03 03:41
Cheers, that sounds good. It is also the lights in the current method that don't show up at all for a full black/zero roughness metallic material (unlike 3.5). Will it also make lights visible if on the default 0.5 specular value?

I am happy to leave feedback when you are able to put up a PR (assuming there is a github autobuild)

**Comment by clayjohn** [comment] 2022-12-03 04:00
> Will it also make lights visible if on the default 0.5 specular value?

Yep, lights will have the same behaviour as IBL. Totally dark in the center, but will reflect at glancing angles

**Comment by akien-mga** [comment] 2022-12-03 11:52
Fixed by #69514 and #69522.

**Closed by akien-mga** 2022-12-03 11:52 UTC
Labels: bug, topic:rendering, topic:3d
