### ISSUE TITLE
HTTPClient: app is crashed when connection terminated by remote side (maybe not)

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#2902] opened 2015-11-24 15:38 UTC
![godot_bug](https://cloud.githubusercontent.com/assets/7677575/11371515/fa70e40c-92d9-11e5-88b1-b4984aaca59a.jpg)

Repeated periodicaly when I make a http/https requests. Code from https://github.com/godotengine/godot/wiki/http_client without "OS.delay" because with delays repeated frequently

**Comment by akien-mga** [comment] 2015-11-24 15:42
I don't see a crash here. Isn't it just a normal behaviour? The connection was terminated so it stops?

**Comment by ealataur** [comment] 2015-11-24 20:37
Yes. Application is crashed and no print any other debug info. Request is processing in thread but application is close without any debug info about crash..

**Comment by akien-mga** [comment] 2015-11-24 20:57
Could you provide a test project that reproduces the issue?

**Comment by ealataur** [comment] 2015-11-24 21:25
https://app.box.com/s/h6sp4ctpbp457e29vcaaxr4trtkexakr
if you did repeatedly press button than app is simply closed

**Comment by ealataur** [comment] 2015-11-24 21:36
When not load ssl certificates to project bug is not reproduced..

**Comment by primesoftware** [comment] 2015-12-10 15:13
@ealataur See #2157. I'm working on tossing out OpenSSL in favor of the lighter weight mbedTLS.

**Comment by reduz** [comment] 2015-12-12 20:59
oh so it' s an openssl issue :( 
@primesoftware : very much looking forward to that :D

**Comment by Faless** [comment] 2018-03-20 19:44
the mbedTLS switch happened, I can't reproduce this bug in `2.1` either, closing

**Closed by Faless** 2018-03-20 19:44 UTC
Labels: bug, topic:core, topic:network
