### ISSUE TITLE
Unable to write to file when installing export templates

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#20017] opened 2018-07-07 14:55 UTC
Godot version: 3.0.4
OS/device including version: Win7

Issue description:
I've tried to export the project as android apk. But I get:
![can t download android templates](https://user-images.githubusercontent.com/40721994/42412074-0b7fcb96-8206-11e8-8761-3fb7edd37ea4.jpg)

It seems that a lot of files are installed but I don't know if it's all of them:
![some files](https://user-images.githubusercontent.com/40721994/42412092-2a0dca54-8206-11e8-8566-33cff3cdac12.jpg)

The export works though: I've created an apk and opened it on an android device and it seems to work.

Steps to reproduce:
Open the export window.

Minimal reproduction project:
[Finger & Screen RPG.zip](https://github.com/godotengine/godot/files/2172847/Finger.Screen.RPG.zip)

**Comment by Zylann** [comment] 2018-07-07 15:34
Same as #14339 ?

**Comment by akien-mga** [comment] 2018-07-19 10:12
Duplicate of #19389.

**Closed by akien-mga** 2018-07-19 10:12 UTC
