### ISSUE TITLE
Files dragged into the FileSystem dock appear twice, despite only 1 copy appearing on disk.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#48456] opened 2021-05-04 14:51 UTC
**Godot version:**
4.0 c26cff7

**OS/device including version:**
WIN 10

**Issue description:**

https://user-images.githubusercontent.com/41730826/117023345-5e7faa00-ad3c-11eb-9d2a-4ca0e819649c.mp4

**Steps to reproduce:**
Drag and drop files into FileSystem dock, 2 appear, but in the project folder there is only 1 file, as shown in video.

**Comment by EricEzaM** [comment] 2021-05-04 14:56
Dunno why the video isn't embedding on GitHub...

**Comment by Calinou** [comment] 2021-05-04 15:07
> Dunno why the video isn't embedding on GitHub...

You need to add a blank line before *and* after the URL.

**Comment by EricEzaM** [comment] 2021-05-04 15:12
Thanks @Calinou

**Comment by EricEzaM** [comment] 2021-05-07 09:53
Could someone confirm this? I have gone back to commits from Mid 2020 and it is still happening... it could be something else? idk

A confirmation on windows and other platforms would be appreciated.

**Comment by foxydevloper** [comment] 2021-07-20 16:45
Can confirm this happens for me on Windows 10 as well. Deleting either of the files causes the editor to crash too.

**Comment by Calinou** [comment] 2022-05-04 22:17
I can't reproduce this on 4.0.alpha 174c14762fd38f8a8f0a04f69a5fdf3f81fc1b75 (Linux, NVIDIA 510.60.02).

**Comment by steel97** [comment] 2022-09-01 13:01
Just checked alpha builds from 1 to 4 and in my case issue gone in **alpha 4**. 
Newer versions also doesn't have this issue in my case.
Tested on **Windows 11**

**Comment by akien-mga** [comment] 2022-09-01 13:06
Thanks, closing as fixed in 4.0 alpha 4.

**Closed by akien-mga** 2022-09-01 13:06 UTC
Labels: bug, topic:editor, confirmed
