### ISSUE TITLE
`reload()` of `GDScript` causes memory leak

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#99169] opened 2024-11-13 10:10 UTC
### Tested versions

- Reproducible in v4.4.dev4.official [36e6207bb]

### System information

Windows 11, Vulkan API 1.3.280 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

Can see memory increasing and Object count increasing by this code:
```
extends Node2D

func _ready() -> void:
	for i in 100:
		for j in 10:
			var a = GDScript.new()
			a.source_code = "extends Object\nvar value = 2212"
			a.reload()
		await get_tree().create_timer(1).timeout

```
<img width="1199" alt="屏幕截图 2024-11-13 175654" src="https://github.com/user-attachments/assets/330be7e7-3b2f-42b9-a9cb-4bac17a497e4">

Object's count won't increase without using `reload()` however we must use `reload()` to let the code take effect if we want to use somthing like `var obj = a.new()`

### Steps to reproduce

1. run MRP
2. see monitor

### Minimal reproduction project (MRP)

[test_resource_free.zip](https://github.com/user-attachments/files/17730480/test_resource_free.zip)

**Comment by dalexeev** [comment] 2024-11-19 08:05
If you modify the example as follows, there is no longer a memory leak:

```gdscript
func _ready() -> void:
    var a = GDScript.new()
    for i in 100:
        for j in 10:
            a.source_code = "extends Object\nvar value = 2212"
            a.reload()
        await get_tree().create_timer(1).timeout
```

So I think this is a duplicate of #77513. The problem is not `reload()`, but that `GDScript` resources are never removed due to extra reference in `GDScriptCache`.

**Closed by dalexeev** 2024-11-19 08:05 UTC
Labels: bug, topic:gdscript

**Comment by jinyangcruise** [comment] 2024-11-19 13:22
Thanks for your advice. I think the `a` is still a leak which is affordable. This is a good workaround.
