### ISSUE TITLE
add_child in tool script reflected in editor view but not scene tree

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#34739] opened 2020-01-02 02:25 UTC
**Godot version:**

3.1.2.stable.custom_build

**OS/device including version:**

Linux 5.4.6-arch1-1 GNU/Linux

**Issue description:**

When a `tool` script adds a child to a node, you can see the node in the 3D view, but not in the scene tree.

**Steps to reproduce:**

1. Create a scene with a `Spatial` root
2. Create another scene with a `MeshInstance` and add a `Mesh`
3. Add the following script to the spatial

```
tool
extends Spatial

export(PackedScene) var scene: PackedScene setget set_scene,get_scene

func set_scene(val: PackedScene):
	scene = val
	add_child(scene.instance())

func get_scene():
	return scene
```

4. Place the `PackedScene` from step 2 in the scene field via the editor
5. Note that the MeshInstance is visible, yet not shown in the scene tree

**Minimal reproduction project:**
[example.zip](https://github.com/godotengine/godot/files/4014784/example.zip)

![1577931482](https://user-images.githubusercontent.com/2496231/71649486-306bff00-2cdd-11ea-8873-855a6aa7554b.png)

**Comment by Calinou** [comment] 2020-01-02 02:33
Wasn't this done by design to prevent persisting the added nodes to the scene file?

**Comment by rcorre** [comment] 2020-01-02 02:36
That actually makes sense, and in my case I wouldn't want it persisted. Feel free to close if this is intentional.

**Comment by bojidar-bg** [comment] 2020-01-02 08:40
Duplicate of #12456? Perhaps `add_child`'s documentation should have a note mentioning `set_owner` added to it.

**Comment by TheWhiteLlama** [comment] 2020-01-02 17:01
> Duplicate of #12456? Perhaps `add_child`'s documentation should have a note mentioning `set_owner` added to it.

good idea! Especially for beginners it's quite confusing when they start working on tools

**Closed** 2020-01-03 08:08 UTC
Labels: bug, topic:editor
