### ISSUE TITLE
character encoding cyrillic converter

### ISSUE THREAD

**Issue by NordeN37** [godotengine/godot#66823] opened 2022-10-03 15:18 UTC
### Godot version

Godot_v4.0-beta2 linux

### System information

Ubuntu 22.04

### Issue description

Project name encoding error in taskbar "Gnome 42"
![image](https://user-images.githubusercontent.com/43890873/193613979-03cf01fd-cf06-47be-9f7c-785f333673fb.png)

### Steps to reproduce

Start projekt name "Новый игровой проект"

**Comment by akien-mga** [comment] 2022-10-04 08:03
Duplicate of #56655

**Closed by akien-mga** 2022-10-04 08:03 UTC
