### ISSUE TITLE
EXR import crashes the editor 

### ISSUE THREAD

**Issue by BenjaminSauder** [godotengine/godot#13490] opened 2017-12-01 20:51 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot_v3.0-beta1_win64
GTX 970

**Issue description:**
Godot crashes when trying to import a .exr file.

**Steps to reproduce:**
1. create new project
2. import .exr file.

**Link to minimal example project:**
[exr_crash.zip](https://github.com/godotengine/godot/files/1522936/exr_crash.zip)

**Comment by JuanDidNothingWrong2** [comment] 2017-12-01 22:40
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by JuanDidNothingWrong2** [comment] 2017-12-01 22:40
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by reduz** [comment] 2017-12-05 17:58
I couldn't find the problem with this. It's either the EXR library not working properly or a bug from my part.
EXR should be disabled if this can't be fixed. Code is here:

https://github.com/godotengine/godot/blob/master/modules/tinyexr/image_loader_tinyexr.cpp#L37

Maybe updating tinyexr is the way to go.

**Comment by akien-mga** [comment] 2017-12-05 20:35
I can reproduce the issue with the provided project, on Mageia 6 Linux with a debug binary compiled with GCC 5. Backtrace:
```
(gdb) bt
#0  ImageLoaderTinyEXR::load_image (this=0x4f80d80, p_image=..., f=0x115df700, p_force_linear=false, p_scale=1) at modules/tinyexr/image_loader_tinyexr.cpp:139
#1  0x000000000284fffe in ImageLoader::load_image (p_file=..., p_image=..., p_custom=0x0, p_force_linear=false, p_scale=1) at core/io/image_loader.cpp:65
#2  0x000000000187986d in ResourceImporterTexture::import (this=0x85e60b0, p_source_file=..., p_save_path=..., p_options=..., r_platform_variants=0x7fffffffc668, 
    r_gen_files=0x7fffffffc660) at editor/import/resource_importer_texture.cpp:365
#3  0x0000000001619a67 in EditorFileSystem::_reimport_file (this=0x8603710, p_file=...) at editor/editor_file_system.cpp:1370
#4  0x000000000161b7df in EditorFileSystem::reimport_files (this=0x8603710, p_files=...) at editor/editor_file_system.cpp:1488
#5  0x0000000001613397 in EditorFileSystem::_update_scan_actions (this=0x8603710) at editor/editor_file_system.cpp:472
#6  0x00000000016169d6 in EditorFileSystem::_notification (this=0x8603710, p_what=17) at editor/editor_file_system.cpp:981
#7  0x000000000161db7a in EditorFileSystem::_notificationv (this=0x8603710, p_notification=17, p_reversed=false) at editor/editor_file_system.h:100
#8  0x00000000027601b4 in Object::notification (this=0x8603710, p_notification=17, p_reversed=false) at core/object.cpp:923
#9  0x0000000001cdc366 in SceneTree::_notify_group_pause (this=0x5485a30, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:916
#10 0x0000000001cda1ab in SceneTree::idle (this=0x5485a30, p_time=0.13333334) at scene/main/scene_tree.cpp:493
#11 0x0000000000e8d038 in Main::iteration () at main/main.cpp:1719
#12 0x0000000000e6911f in OS_X11::run (this=0x7fffffffd5e0) at platform/x11/os_x11.cpp:2126
#13 0x0000000000e5f77b in main (argc=2, argv=0x7fffffffdab8) at platform/x11/godot_x11.cpp:54(gdb) bt
#0  ImageLoaderTinyEXR::load_image (this=0x4f80d80, p_image=..., f=0x115df700, p_force_linear=false, p_scale=1) at modules/tinyexr/image_loader_tinyexr.cpp:139
#1  0x000000000284fffe in ImageLoader::load_image (p_file=..., p_image=..., p_custom=0x0, p_force_linear=false, p_scale=1) at core/io/image_loader.cpp:65
#2  0x000000000187986d in ResourceImporterTexture::import (this=0x85e60b0, p_source_file=..., p_save_path=..., p_options=..., r_platform_variants=0x7fffffffc668, 
    r_gen_files=0x7fffffffc660) at editor/import/resource_importer_texture.cpp:365
#3  0x0000000001619a67 in EditorFileSystem::_reimport_file (this=0x8603710, p_file=...) at editor/editor_file_system.cpp:1370
#4  0x000000000161b7df in EditorFileSystem::reimport_files (this=0x8603710, p_files=...) at editor/editor_file_system.cpp:1488
#5  0x0000000001613397 in EditorFileSystem::_update_scan_actions (this=0x8603710) at editor/editor_file_system.cpp:472
#6  0x00000000016169d6 in EditorFileSystem::_notification (this=0x8603710, p_what=17) at editor/editor_file_system.cpp:981
#7  0x000000000161db7a in EditorFileSystem::_notificationv (this=0x8603710, p_notification=17, p_reversed=false) at editor/editor_file_system.h:100
#8  0x00000000027601b4 in Object::notification (this=0x8603710, p_notification=17, p_reversed=false) at core/object.cpp:923
#9  0x0000000001cdc366 in SceneTree::_notify_group_pause (this=0x5485a30, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:916
#10 0x0000000001cda1ab in SceneTree::idle (this=0x5485a30, p_time=0.13333334) at scene/main/scene_tree.cpp:493
#11 0x0000000000e8d038 in Main::iteration () at main/main.cpp:1719
#12 0x0000000000e6911f in OS_X11::run (this=0x7fffffffd5e0) at platform/x11/os_x11.cpp:2126
#13 0x0000000000e5f77b in main (argc=2, argv=0x7fffffffdab8) at platform/x11/godot_x11.cpp:54
```

> Maybe updating tinyexr is the way to go.

That can't hurt and I see references to various crash fixes in upstream commits, so I'll give this a go. I think the bug would likely still be in our own module though, the crash happens in our code and not in the upstream lib.

**Comment by reduz** [comment] 2017-12-05 20:37
if you want to give a try to updating it then cool, last time I checked this problem it seemed to me it was definitely the library fault

**Comment by akien-mga** [comment] 2017-12-05 20:55
As expected, updating the library to the current upstream/master doesn't fix the crash. I'll dig into our code and try to debug a bit more.

**Comment by akien-mga** [comment] 2017-12-05 21:38
Alright, fix incoming :)

**Closed** 2017-12-06 23:22 UTC
Labels: bug, confirmed, hero wanted!, topic:editor
