### ISSUE TITLE
`Polygon2D` animations fail to interpolate between `AnimationNodeStateMachine` animation nodes.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#75400] opened 2023-03-27 17:14 UTC
### Godot version

4.0

### System information

Windows 10

### Issue description

Creating an animation track for a `Polygon2D` node's `polygon` property and setting that track's Update Mode to "Continuous" (so that I can smoothly interpolate between polygon vertex positions) does not work when transitioning between those animations inside a `AnimationNodeStateMachine`.

![no interp](https://user-images.githubusercontent.com/34152090/228009525-1036ae89-dfd5-43ec-8dd2-221978cbc47a.gif)

The triangle should smoothly transition between the two animation states (as it did in 3.5) but instead does nothing at all.

### Steps to reproduce

- create a `Polygon2D` and an `AnimationPlayer`.
- in the `AnimationPlayer` create two animations, each having a `Polygon2d` `polygon` property keyframe where the `Polygon2d` has its points at different positions.
- set the animation tracks' Update Mode to "Continuous" in each of the animations.
- create an `AnimationTree` node and connect it to the `AnimationPlayer`
- in the `AnimationTree` node, with `AnimationNodeStateMachine`, create two animation nodes per the two animations. create a transition between them with an `xfade_time` of 0.5. 
- activate the animationtree and test the transition between the two animations.

### Minimal reproduction project

N/A

**Comment by TokageItLab** [comment] 2023-03-28 04:48
Dupe of #73342

**Closed by TokageItLab** 2023-03-28 04:48 UTC
Labels: bug, topic:animation
