### ISSUE TITLE
Parse error tscn: Quotes in node name

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot#18646] opened 2018-05-05 22:08 UTC
**Godot version:**

master

**OS/device including version:**

any

**Issue description:**

Quotes in node name will cause tscn to fail at parsing.

**Steps to reproduce:**

load up a gltf2.0 object with quotes

create a scene

make any change to a object with quote in its name

save the scene

parse errors

**Minimal reproduction project:**

[quote_node.zip](https://github.com/godotengine/godot/files/1977127/quote_node.zip)

**Comment by hungrymonkey** [comment] 2018-05-05 23:15
as a workaround use this to delete chars

not exhausted list of chars needed to be deleted

```
[]"
```

there are probably more chars

**Comment by vnen** [comment] 2018-05-06 00:05
Duplicate of #18448

**Closed by vnen** 2018-05-06 00:05 UTC
