### ISSUE TITLE
Editor randomly crashes while reimporting assets

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#28069] opened 2019-04-15 21:02 UTC
**Godot version:**

3.1

**OS/device including version:**

Windows10 

**Issue description:**

**Steps to reproduce:**
Whenever i rename or move a file on the filesystem or add an important amount of new files. Godot randomly crashes. It is not caused by a particular file or path or extension, it just happens anytime. Might be caused by memory corruption

**Comment by MunWolf** [comment] 2019-04-16 06:39
I encountered this as well when I was renaming a folder.

**Comment by akien-mga** [comment] 2019-04-17 07:51
Duplicate of #26394 and/or #28012.

**Closed by akien-mga** 2019-04-17 07:51 UTC
Labels: bug, topic:editor
