### ISSUE TITLE
GradientTexture1D no longer works as a sampler2D texture.

### ISSUE THREAD

**Issue by LunaticWyrm467** [godotengine/godot#81739] opened 2023-09-16 14:16 UTC
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

Windows 11, RTX 3050 Laptop, 11th Gen i5, Vulkan

### Issue description

For whatever reason, whenever I attempt to set a GradientTexture1D as a sampler2D texture for any shader, the texture simply vanishes when the game is run or when I reload the scene. I first noticed this issue when I updated from 4.2 dev 3 to 4.2 dev 4, and all of my materials that required gradients simply reset on the spot. I tried recreating the gradients as a separately saved resource, but Godot would shortly reset the texture fields after a quick reload, and would fail to render those textures in-game.

### Steps to reproduce

1) Create a simple shader that renders a texture from a sampler2D uniform.
2) Drop in a Gradient1DTexture into the sampler2D uniform field from the material's shader parameters.
3) Reload the project or run the game.
4) Take note of the lack of the loaded gradient texture. If you reloaded the project, the texture field in the shader parameters should be empty again.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-09-16 14:17
Duplicate of https://github.com/godotengine/godot/issues/81712

**Closed by AThousandShips** 2023-09-16 14:17 UTC
