### ISSUE TITLE
Initialization bugs in inner classes with several (2) levels of inheritance

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#3387] opened 2016-01-19 14:37 UTC
Running the script

``` python
extends Spatial

class Foo extends Node:
        func _init(f):
                .init()
                print("Foo")
class Bar extends Foo:
        var d
        func _init(f, g):
                ._init(f)
                d = g
class Bar2 extends Bar:
        var t
        func check(d):
                t = d
                print(t)
func _ready():
        var ch = Bar2.new("a", "b")
```

tells me that new() requires 0 arguments. If we run Bar.new("a") instead, everything works properly.
Adding separate _init() to Bar2 doesn't solve a problem, as changing Bar2 to this:

``` python
class Bar2 extends Bar:
        var t
        func check(d):
                t = d
                print(t)
        func _init(f, g):
                ._init(f, g)
```

produces error message which requires 2 arguments for .new()

**Comment by slapin** [comment] 2016-01-19 14:48
Well, 2 levels can't be called many, does it? As the reaction to *many* might be wontfix just because of that word. The problem starts for ma at exactly 2nd level of inheritance.

**Comment by slapin** [comment] 2016-01-19 14:49
Need to mention that Bar class works as intended (really seriously tested that)., only Bar2 and later have problems.

**Comment by akien-mga** [comment] 2016-01-19 14:54
Thanks for the precision.

**Comment by akien-mga** [comment] 2016-01-19 20:45
I can reproduce the issue with the above snippet.

**Comment by TheHX** [comment] 2016-01-19 21:21
@slapin @akien-mga
I'm not sure if this is a bug, following the [wiki](http://godotengine.org/projects/godot-engine/wiki/GDScript#Arguments-to-Parent-Constructor), the above code should be:
```GDScript
extends Spatial

class Foo extends Node:
        func _init(f):
                print("Foo")
class Bar extends Foo:
        var d
        func _init(f, g).(f):
                d = g
class Bar2 extends Bar:
        var t
        func check(d):
                t = d
                print(t)
        func _init(f, g).(f, g):
            pass

func _ready():
        var ch = Bar2.new("a", "b")
```
I tested both snippets and this one run fine.

**Comment by akien-mga** [comment] 2016-01-19 21:28
Oh nice catch @TheHX. While doing some testing right now I was also starting to wonder if @slapin's call of ```.init()``` was the proper way of calling the ancestor's constructor, but I didn't know about this _init().() construct.

**Comment by slapin** [comment] 2016-01-19 22:12
Thanks a lot for help, guys
Well, I was told to use ._init() before.
Anyway, what should I do if I need to cook arguments for parent constructor (not just pass them)?
any more advanced example?
This stuff is not really easy to be found also this thing is not similar to other languages,
so it deserves a few examples.
Also I wonder why my implementation works until extended twice?

**Comment by bojidar-bg** [comment] 2016-01-20 12:27
@slapin Maybe the problem is that `_init` is called automatically, and isn't supposed to be called by hand? (Info taken from the [same wiki link](http://godotengine.org/projects/godot-engine/wiki/GDScript#Arguments-to-Parent-Constructor))

**Comment by slapin** [comment] 2016-01-20 18:01
Basically the problem is that capabilities of overriding class constructor are very limited (confirmed by @reduz, so it is to be worked around now, and probably will be fixed later, but at least it is considered misfeature. So if you need extra constructor, use pseudo-constructor (additional function) now, and override it in your class tree.

**Comment by reduz** [comment] 2016-02-01 03:27
yes you are not supposed to call the parent constructor, it's called automatically. However, after talking to slapin, it makes sense to detect a call to it and if so, allow that one to be used.
Yet, this is 2.1 material.

**Comment by akien-mga** [comment] 2016-03-24 09:28
Potentially related: #942

**Comment by reduz** [comment] 2016-06-28 14:21
too difficult to do for little gain, and not a bug, may do it at some other time

**Comment by akien-mga** [comment] 2016-07-15 10:27
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Calinou** [comment] 2020-06-14 14:02
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Closed by Calinou** 2020-06-14 14:02 UTC
Labels: confirmed, enhancement, topic:gdscript

**Comment by slapin** [comment] 2020-06-15 10:30
I wonder, do you even read the bugs you close? The message looks
awkward at best.

**Comment by akien-mga** [comment] 2020-06-15 10:43
@slapin That's a copy pasted message which has been posted on more than 1000 issues over the past few weeks.

**Comment by slapin** [comment] 2020-06-15 11:26
Well, that bug might be relevant if 2.x is supported yet and totally not a
feature request, JFYI.
