### ISSUE TITLE
[4.0 Beta 4] - Windows 11 64Bit - HTML5 - "max_fps" limit 30 FPS / "physics_ticks_per_second" no limit ?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#68629] opened 2022-11-13 23:03 UTC
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 11 64Bit - Edge/Firefox/Chrome/Opera

### Issue description

Hi,

Running v4.0 Beta 4 on Windows 11 Pro 64Bit.

HTML5 builds are locked to 30 Frames Per Second when using "max_fps" ?
Using "physics_ticks_per_second" instead creates no limit on FPS ?

Is above intended behavior of Godot v4.0 ?
Thanks!

Jesse

### Steps to reproduce

Download and open below project:
https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

It uses by default "physics_ticks_per_second" and there is no limit to FPS.

Switch all "physics_ticks_per_second" to "max_fps" and then build and run in browser.
HTML5 build is limited to 30 FPS on Windows 11 64Bit ?

### Minimal reproduction project

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by Sauermann** [comment] 2022-11-13 23:18
related to #68439

**Comment by clayjohn** [comment] 2022-11-14 00:08
Yes, sounds like a continuation of #68439 which was closed as the 30 FPS limit appears to be a Windows 11 regression.

**Comment by Calinou** [comment] 2022-11-14 14:27
Duplicate of https://github.com/godotengine/godot/issues/68439. Wait for a fix to land on Windows 11 :slightly_smiling_face:

**Closed by Calinou** 2022-11-14 14:27 UTC
