### ISSUE TITLE
Add Metadata button misses some padding

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#65041] opened 2022-08-29 14:28 UTC
### Godot version

4.0 Alpha 13

### System information

PopOS 22.04 - NVIDIA Corporation GP107GLM

### Issue description

Text inside the `Add Metadata` button is not well centered, even when resizing the whole right panel to a maximum width.

My screen resolution is 3840 x 2160 (16:9)

![2022-08-29_16-19](https://user-images.githubusercontent.com/3624853/187224067-6c21795c-4f1c-43e3-8e4a-a6baf3dc9f56.png)

### Steps to reproduce

Just create a project, add any node, and have a look at the `Add Metadata` button in the inspector.

### Minimal reproduction project

No need. Any stock node's inspector will do.

**Comment by kleonc** [comment] 2022-08-29 15:04
Duplicate of #64371.

**Closed by kleonc** 2022-08-29 15:04 UTC

**Comment by kleonc** [comment] 2022-08-29 15:06
> ### Godot version
> 
> 4.0 Alpha 13

Or is it actually happening in `4.0 Alpha 13` and it's a different issue / I've closed it too fast?

**Comment by hakro** [comment] 2022-08-29 17:24
> Or is it actually happening in 4.0 Alpha 13 and it's a different issue / I've closed it too fast?

My bad, I got mixed up with all the versions I have :)
It's working fine in `4.0 Alpha 13`
But it's broken in `4.0 Alpha 14`
