### ISSUE TITLE
Godot crashes when using the settin "save on focus loss" on steam deck

### ISSUE THREAD

**Issue by ducketyduck** [godotengine/godot#91032] opened 2024-04-22 23:11 UTC
### Tested versions

Reproducibe in godot 4.2

### System information

Steam Os

### Issue description

The godot editor tends to crash when the setting "interface/editor/save_on_foxus_loss" is enabled, tested in 2 projects:
project 1 is bigger than the other, and it crashes as soon as ctrl + s is pressed, or it just spontaneously crashes if the project is open for long enough (a couple of minutes). Project 2 is a lot smaller, didn't experience crashes on save, but on both projects as soon as I would run the project the editor would crash. 

### Steps to reproduce

- Use the steam Os operating systeam (have not tested on other linux distros)
- Enable interface/editor/save_on_foxus_loss in the editor settings
- Run the project

### Minimal reproduction project (MRP)

I'm not including anything since this doesn't depend on the project

**Comment by Rindbee** [comment] 2024-04-23 03:27
Seems to be a duplicate of #78558.

**Comment by akien-mga** [comment] 2024-04-23 09:18
Consolidating in #78558. Thanks for the report!

**Closed by akien-mga** 2024-04-23 09:18 UTC
