### ISSUE TITLE
Controller/Joystick Button 0 Launches a new Instance of the Game

### ISSUE THREAD

**Issue by PTrottier** [godotengine/godot#21003] opened 2018-08-14 14:10 UTC
**Godot version:** v3.0.6.stable.official.8314054

**OS/device including version:** Windows 10 Version: 1803 OS build: 17134.191; Fedora 28 
It appears to be joystick and computer agnostic.

**Issue description:** When running the game, the button 0 on my joystick triggers running cmdline: "path/to/executable" "--path" "path/to/game". I was under the impression that this was a setting in the Project Settings > Input Map and in this case "ui_accept" (which maps button 0) but the "Enter" and "Space" keys don't behave this way. I was expecting to be able to map button 0 to perform a particular action but instead it appears to be stuck to launching a new window and starting the game again.

**Steps to reproduce:** 

1. Launch the Godot Launcher
2. Select any game 
3. Press run
4. Press button 0 on joystick 0

**Minimal reproduction project:**

It appears to me that this issue is project agnostic.

**Comment by akien-mga** [comment] 2018-08-14 14:48
Duplicate of #15199, fixed in the master branch.

**Closed by akien-mga** 2018-08-14 14:48 UTC
Labels: bug, topic:input

**Comment by PTrottier** [comment] 2018-08-14 14:55
@akien-mga Apologies

**Comment by akien-mga** [comment] 2018-08-14 15:06
There's nothing to apologize for, it's ok to file duplicates - it's our job to find and close them ;)
