### ISSUE TITLE
Sprites in SpriteFrames (animated sprites) are previewed as blurry regardless of Texture Filtering mode

### ISSUE THREAD

**Issue by FlourL** [godotengine/godot#74180] opened 2023-03-01 19:31 UTC
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

![Skärmbild 2023-03-01 202603](https://user-images.githubusercontent.com/47177904/222244097-ddc853ce-59d2-47fe-a133-1a6807ccc74a.png)

As you can see the frames end up as blurry even though I have texture filter set to "nearest".

This is also the case when trying to seperate the frames, which makes it hard to split them correctly on particularly high res sprites

### Steps to reproduce

1. Add animated sprite to scene
2. Create new Sprite Frames
3. Add frames from sprite sheet
4. change texture filtering in either project setting or in the inspector, note no difference in preview

### Minimal reproduction project

not required as there are very few steps to reproduce

**Comment by clayjohn** [comment] 2023-03-01 19:37
Duplicate of https://github.com/godotengine/godot/issues/57550

Will be fixed by https://github.com/godotengine/godot/pull/73962

**Closed by clayjohn** 2023-03-01 19:37 UTC
