### ISSUE TITLE
Error on launch : vkEnumeratePhysicalDevices reported zero accessible devices.

### ISSUE THREAD

**Issue by MANM-ANMM** [godotengine/godot#45104] opened 2021-01-11 16:38 UTC
**Godot version:**

51992250e67d0fea1087ee3d9973f0b825349884

**OS/device including version:**

Windows 10 Famille
Version 10.0.18363 Numéro 18363

GPU : Nvidia Geforce GTX 1050
Driver : 461.09
Backend : Vulkan
I have an integrated GPU but I run Godot with my GPU above.

**Issue description:**

![image](https://user-images.githubusercontent.com/63152138/104209563-2fae9280-5432-11eb-8928-34f385134587.png)

I don't understand what is exactly a "installable client driver". This may be the issue... sorry for that.
Godot print me this error directly without opening any graphical window when I run it.

**Steps to reproduce:**
I just try to run godot.
I don't really know what to said else here. If you have questions.

**Minimal reproduction project:**

This is an error on startup so I havn't any project.

**Comment by MagdielM** [comment] 2021-01-11 17:29
This may be completely unrelated, but I remember having a similar issue when trying to build my own Vulkan application. After going back and forth with LunarG's Vulkan SDK team, we determined my particular issue had to do with AMD's Switchable Graphics Layer, a Vulkan validation layer that's enabled by default on my system that was causing issues when counting physical devices on my particular setup (laptop with both an integrated and dedicated GPU). Now I had thought that Vulkan validation layers were not supposed to run at all on non-debug builds, but no configuration I tried helped my case. AMD also never got back to me about the issue, so this is all the info I can provide.

**Comment by MANM-ANMM** [comment] 2021-01-11 19:50
Thanks for the clue

I just notice that Godot print me another message after I close the pop up error window, so here it is:
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:1560)

**Comment by Mrsir8433** [comment] 2021-06-01 14:41
Is this problem resolvable?? anyone got any workaround?

**Comment by Fedron** [comment] 2021-06-09 08:56
I was having the same issue as @MagdielM turns out all you need to resolve the issue is:

1. Search "Environment variables" in the start menu and open the first result
2.  Click on "Environment Variables"
3. Click "New" under the "System variables" section
4. Set the variable name as "DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1"
5. Set the variable value as 1

This did the trick for me and I don't get the ICD related error anymore when trying to run my own Vulkan application

**Comment by MANM-ANMM** [comment] 2021-06-09 19:31
It seems to work for me, Godot take a fair long time to launch but this issue seems resolvable this way. Thank you.

**Comment by Calinou** [comment] 2021-06-09 20:42
> It seems to work for me, Godot take a fair long time to launch but this issue seems resolvable this way. Thank you.

This is a known issue, see https://github.com/godotengine/godot/issues/43351.

**Comment by RelativeParadox** [comment] 2021-11-04 15:08
This issue should be fixed for AMD integrated GPUs, the fix was pushed in an AMD driver update. Once I updated the AMD drivers vulkan was able to select my dGPU.  It seems the problem was with how gpus are filtered, specifically in AMDs filter layer.
Documented here: https://github.com/KhronosGroup/Vulkan-Loader/issues/552

My Specs
dGPU: GTX 1660Ti
iGPU: AMD Integrated in Ryzen 7 4000 Series Mobile Chipset

Installing drivers directly from AMD could stop updates from the OEM for your computer, the OEM supplies an older custom version of their drivers so if you are getting this error they have not updated their version of the drivers.

**Comment by Mart-Bogdan** [comment] 2024-04-20 17:31
Seting this environment variable resolves the issue:

`DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1`

**Comment by Calinou** [comment] 2024-04-29 22:26
This was the same root cause as https://github.com/godotengine/godot/issues/57708 and was resolved by https://github.com/godotengine/godot/pull/73450, closing.

If you still run into this issue, update to the latest graphics driver version provided by your graphics driver vendor (not Windows Update, not your desktop/laptop OEM).

**Closed by Calinou** 2024-04-29 22:26 UTC
Labels: platform:windows, topic:rendering, topic:thirdparty
