### ISSUE TITLE
Nvidia: 3D view becomes unusable when editing a MeshInstance in the inspector

### ISSUE THREAD

**Issue by Arjan219** [godotengine/godot#11266] opened 2017-09-14 14:06 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
OS: Linux Mint 64bit
Godot Engine v3.0.alpha.custom_build.8c08f23
GPU: NVIDIA Corporation GF119M [GeForce 610M]
Graphics driver: nvidia-375.66

**Issue description:**
When editing the shape of a MeshInstance in the inspector, the 3D view goes black and is unusable until Godot is restarted.
![screenshot from 2017-09-14 15-51-06](https://user-images.githubusercontent.com/28710711/30433715-778528b6-9965-11e7-869c-bc0a390cfc55.png)

**Steps to reproduce:**
- Add a MeshInstance to the scene
- For the MeshInstance, create a new shape
- Edit the shape

**Comment by hpvb** [comment] 2017-09-14 14:11
Tried to reproduce this on Linux/X11 Fedora 26 with Intel graphics and everything appears to be OK. Do you see any output on the terminal while when you do this?

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.1.7
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

**Comment by henkz1** [comment] 2017-09-14 14:29
I can confirm this on ubuntu 17.04, gtx 750 Ti, nvidia 375.66, resizing the window makes everything go back to normal in my case.
Related or duplicate of https://github.com/godotengine/godot/issues/9891 and https://github.com/godotengine/godot/issues/10090

**Comment by Arjan219** [comment] 2017-09-14 14:32
When starting Godot from the terminal i see several pages worth of this error:
`ERROR: clear_icon: Condition ' !icon_map.has(p_type) ' is true. At: scene/resources/theme.cpp:289.`
Nothing out of the ordinary except for that error.
Switching to integrated Intel graphics next.

**Comment by Arjan219** [comment] 2017-09-14 14:42
It doesn't seem to happen after switching to Intel's integrated graphics, so this seems to be an Nvidia-only bug.
I know it's slightly off-topic, but Godot seemed to start much quicker after switching to Intel.

**Comment by Vorion86** [comment] 2017-09-14 15:45
I can confirm this on Windows 10 (1703), Nvidia GTX1070, driver 385.41, godot v3.0.alpha.custom_build.57516a4.
Resizing the window or running the project seems to fix it for the current session. After restarting the editor and editing the shape, it goes black again.

**Comment by rminderhoud** [comment] 2017-09-14 23:29
Confirming this bug as well on Ubuntu 17.10 and nvidia

Like @Arjan219 I also have the `!icon_map.has(p_type) is true` error but I have a few more additional ones. I have not updated my drivers, only re-compiled godot.

```
...
OpenGL ES 3.0 Renderer: GeForce GTX 780/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: gdnative/singletons
SVG_GENERATION TIME: 0.219176
...
OpenGL ES 3.0 Renderer: GeForce GTX 780/PCIe/SSE2
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
SVG_GENERATION TIME: 0.217183
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
...
try to see fs update2
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
...
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6261.
loading scene DEFERRED
actually loading it
ERROR: clear_icon: Condition ' !icon_map.has(p_type) ' is true.
   At: scene/resources/theme.cpp:289.
...
```

**Comment by fracteed** [comment] 2017-09-15 01:56
I have also had this happen very sporadically on Windows 10 (960m card). I can't replicate this, but I always have to reload the project to rectify it. This is using a build that it about a week old.

**Comment by kubecz3k** [comment] 2017-09-22 17:43
related issue #10090

**Comment by volzhs** [comment] 2017-09-22 18:07
`icon_map` error is resolved by #11283 now.

**Comment by djrm** [comment] 2017-10-03 19:27
duplicate of #9891

**Comment by groud** [comment] 2017-10-03 20:54
> duplicate of #9891

Yup! Closing :)

**Closed by groud** 2017-10-03 20:54 UTC
Labels: bug, topic:drivers, topic:rendering
