### ISSUE TITLE
web export audio crackling on ios17 devices

### ISSUE THREAD

**Issue by KoitHal** [godotengine/godot#93039] opened 2024-06-11 15:59 UTC
### Tested versions

Reproducible from 4.3 dev 3 to 4.3 beta 1.

### System information

iOS17 HTML5

### Issue description

The audio playback on web exports on ios17 devices is horribly crackly. I've narrowed it down to the crackling always being in the left channel. Also tried many different apple devices and to my surprise, this does not happen on ios 16, but only ios17. And now tried the developer beta of ios 18 and it's still there as well. 
Also the issue is present on older macbooks running Ventura, but not on newer ones running Sonoma.

If I add a Panner effect to my audio bus and pan the audio all the way to the right channel and export it to the web, the issue is not there, but now the audio is only in the right channel of course.
I tried different source files, file types, different projects. In the end for this test I just made a new project and added an AudioStreamPlayer2D node, added an .mp3 and set it to autoplay.

So far what else i've tried:

experimenting with the Low Processor Mode - no result

increasing the Output Latency for web(Project Settings >Audio>Driver) - no result

setting the mix rate manually for web (Project Settings >Audio>Driver) - no result

Also on another note, the iOS session category options(Audio>General) don't seem to do anything.
Setting it to Playback still requires the silent mode to be switched off.

https://github.com/godotengine/godot/assets/166396732/7d708a20-e694-4da9-a6de-337b0ae33ae9

### Steps to reproduce

add AudioStreamPlayer2D node to the scene
add an audio file as the stream and set to autoplay
export it for the web and try it out on an ios17 device

### Minimal reproduction project (MRP)

[audio_issue_proj.zip](https://github.com/user-attachments/files/15791717/audio_issue_proj.zip)

**Comment by AThousandShips** [comment] 2024-06-11 16:01
Related:
* https://github.com/godotengine/godot/issues/87329

**Comment by math77** [comment] 2024-06-17 14:17
Same issue on my Macbook M1 Sonoma

**Comment by adamscott** [comment] 2024-07-07 16:20
Closing as duplicate of #87329

**Closed by adamscott** 2024-07-07 16:20 UTC
Labels: bug, platform:web, platform:ios, needs testing, topic:audio
