### ISSUE TITLE
Godot editor hang on "Play Project"

### ISSUE THREAD

**Issue by nj-designs** [godotengine/godot#38975] opened 2020-05-23 07:43 UTC
**Godot version:**
v3.2.stable.mono.official

**OS/device including version:**
Apple Mac mini (2018)

macOS Catalina (10.15.4)

**Issue description:**
Had been performing usual work flow of creating scences, editing C# scripts (VSCode external editor).

Clicked "Play",  Godot editor just froze. Unable to easily kill process.

Note, targeting local Mac OSX application.

**Steps to reproduce:**
Unfortunately not repeatable, but crash logs attached below. Will update issue with more information if I can repeat.
[crash.zip](https://github.com/godotengine/godot/files/4671362/crash.zip)

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment] 2020-05-30 18:48
Duplicate of #37713, fixed in 3.2.2.

**Closed by akien-mga** 2020-05-30 18:48 UTC
Labels: crash, platform:osx, topic:editor

**Comment by Mirodil** [comment] 2020-08-31 00:45
I see the same issue. What was solution for this?
