### ISSUE TITLE
Wildcard in match statements crashes non-debug builds

### ISSUE THREAD

**Issue by handre-dev** [godotengine/godot#71987] opened 2023-01-24 17:45 UTC
### Godot version

4.0.beta14

### System information

Windows 10 x64

### Issue description

```
func _ready():
    print(myfunc("foo"))
    
func myfunc(what : String) -> int:
    match what:
        "foo":
            return OK
        _:
            return FAILED
```

This pattern runs fine in the editor and in debug builds, but when exported in non-debug builds it will crash the execution and log this:

```
USER SCRIPT ERROR: Parse Error: Not all code paths return a value.
   at: GDScript::reload (res://main.gd:13)
```

Looks like the parser bug reported [here](https://github.com/godotengine/godot/issues/64181) was resolved at some point but it's still present when exporting without debug. Exporting with debug will instead work fine.

### Steps to reproduce

- Copy paste the code above in an empty project
- Export without debug, no matter the platform
- Check the log file

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment] 2023-01-24 19:59
Duplicate of https://github.com/godotengine/godot/issues/55045

**Closed by akien-mga** 2023-01-24 19:59 UTC
