### ISSUE TITLE
Crash when opening Godot with secondary monitor

### ISSUE THREAD

**Issue by arturjpv** [godotengine/godot#2216] opened 2015-06-29 22:00 UTC
Godot opened correctly the first time. I played a little bit with it. After that, it always crashed.

Macbook Air 11' from early 2015 + Secondary monitor.
Mac OSX Yosemite.

Godot opens always correctly without the secondary monitor.

Edited: removed crash log.

**Comment by arturjpv** [comment] 2015-07-01 12:33
Ok, found some time to debug the issue.

In function OS_OSX::initialize(...) from os_osx.mm

the call:
[window_object center];

seems to cause a windowDidResize notification. In windowDidResize the context is being used before the context is initialized.

Moving the [window_object center] call below the context creation seems to fix the problem:

    context = [[NSOpenGLContext alloc] initWithFormat:pixelFormat shareContext:nil];
    ERR_FAIL_COND(context==nil);

    [context setView:window_view];
    [context makeCurrentContext];

    [NSApp activateIgnoringOtherApps:YES];

    [window_object center];
    [window_object makeKeyAndOrderFront:nil];


May be it would be interesting to delay also the setting of the delegate.
After this modifications, Godot starts and opens the window of the project manager in the correct screen. Once I select a project, the scene window always gets opened in the main screen. It would be interesting to open the new window in the same screen where the project manager started, but this is not related with the crash.

**Comment by iPruch** [comment] 2015-07-01 22:56
I am experiencing the same crash with similar conditions: MacBook Pro 13' (early 2015) with external monitor. If I unplug the external display cable, then Godot just works. Same with Godot examples.

**Comment by Lexas** [comment] 2015-10-27 16:34
o/ same as iPruch, with a MacBook Pro 15'. Godot can only work on the primary display.

**Comment by reduz** [comment] 2015-10-27 16:35
hmm.. this is only on osx?

**Comment by vnen** [comment] 2015-10-27 16:54
@reduz see #2656 that reports a similar problem in Ubuntu.

**Comment by reduz** [comment] 2016-01-02 16:16
osx only i'm afraid so there is not much I can do at the moment

**Comment by akien-mga** [comment] 2016-01-21 15:21
> see #2656 that reports a similar problem in Ubuntu.

But apparently it was fixed by itself when doing updates, so so far it still seems to be OSX only.

**Comment by akien-mga** [comment] 2016-07-21 09:01
Is this bug still valid in the current master branch?

**Comment by akien-mga** [comment] 2016-07-27 12:00
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by reduz** [comment] 2016-07-27 12:02
Ah, I could not reproduce this one on my MBP with an attached monitor

**Comment by arturjpv** [comment] 2016-07-27 13:36
Ok, I will try to reproduce the issue again if I can get a second monitor again.

I remember the problem had something to do with  moving the godot window to the secondary screen, closing godot there, and then reopening.

Be aware that by secondary I also mean screen 2. If you have an external monitor but is configured as screen 1 maybe is not crashing.

**Comment by akien-mga** [comment] 2017-09-18 11:22
Assumed fixed in 3.0 as there were many improvements done to multiple monitors handling on all platforms.

**Closed by akien-mga** 2017-09-18 11:22 UTC
Labels: bug, platform:osx, topic:editor
