### ISSUE TITLE
GPU Particles jitter when paused

### ISSUE THREAD

**Issue by GregX999** [godotengine/godot#76387] opened 2023-04-24 03:23 UTC
### Godot version

4.02

### System information

Windows 11

### Issue description

When a GPU Particles node is paused (using get_tree().paused = true), the particles jitter.

![PixelPause](https://user-images.githubusercontent.com/677791/233892991-e230c395-d03e-4e7a-9b30-a540e120d34f.gif)

### Steps to reproduce

Create a basic GPU Particles node and a script that can pause and un-pause it.

### Minimal reproduction project

[ParticlePause.zip](https://github.com/godotengine/godot/files/11306070/ParticlePause.zip)
(The Godot icon will chase the mouse. Press "P" to toggle pause state.)

**Comment by Calinou** [comment] 2023-04-24 09:32
- Duplicate of https://github.com/godotengine/godot/issues/50824 (same cause).

**Closed by Calinou** 2023-04-24 09:32 UTC
Labels: bug, topic:2d, topic:particles
