### ISSUE TITLE
Strange behavior with GDscript 2.0 calculations

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#71172] opened 2023-01-10 18:22 UTC
### Godot version

4.0.beta11

### System information

Mac OS 12.6 M1 Max

### Issue description

I upgraded to 4.0.beta11 and a script that worked in 4.0.beta10 isn't working anymore. I try to isolate the problem and seems to be with `max` function and float/int variables but I'm not sure.

```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int
var _rows: int

var _cell_size_scaled: Vector2

func generate() -> void:
  _cols = max(floor(_shape.size.x / _cell_size), 1)
  _rows = max(floor(_shape.size.y / _cell_size), 1)

  print("_shape_size.x = ", _shape.size.x) # 2000
  print("_cols = ", _cols) # 44
  print("_shape.size.x / _cols  = ", _shape.size.x / _cols) # 0 <= problem here
  print("2000 / 44 = ", 2000 / 44) # 45

  _cell_size_scaled.x = _shape.size.x / _cols # 2000 / 44
  _cell_size_scaled.y = _shape.size.y / _rows # 20000 / 441

  print("_cell_size_scaled = ", _cell_size_scaled) # (0, 0) but should be (45.45454, 45.35147)
```

But if I assign the calculations to `_cols` and `_rows` at the variable declaration, the problem is gone:
```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int = max(floor(_shape.size.x / _cell_size), 1)
var _rows: int = max(floor(_shape.size.y / _cell_size), 1)

var _cell_size_scaled: Vector2

func generate() -> void:
  print("_shape_size.x = ", _shape.size.x) # 2000
  print("_cols = ", _cols) # 44
  print("_shape.size.x / _cols  = ", _shape.size.x / _cols) # 45.4545454545455 <= problem is gone
  print("2000 / 44 = ", 2000 / 44) # 45

  _cell_size_scaled.x = _shape.size.x / _cols # 2000 / 44
  _cell_size_scaled.y = _shape.size.y / _rows # 20000 / 441

  print("_cell_size_scaled = ", _cell_size_scaled) # (45.45454, 45.35147)
```

### Steps to reproduce

1. Create a script:
```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int = max(floor(_shape.size.x / _cell_size), 1)
var _rows: int = max(floor(_shape.size.y / _cell_size), 1)

var _cell_size_scaled: Vector2

func generate() -> void:
#  uncomment these lines to force incorrect behavior
#  _cols = max(floor(_shape.size.x / _cell_size), 1)
#  _rows = max(floor(_shape.size.y / _cell_size), 1)

  print("_shape_size.x = ", _shape.size.x)
  print("_cols = ", _cols)
  print("_shape.size.x / _cols  = ", _shape.size.x / _cols)
  print("2000 / 44 = ", 2000 / 44)
  _cell_size_scaled.x = _shape.size.x / _cols
  _cell_size_scaled.y = _shape.size.y / _rows

  print("_cell_size_scaled = ", _cell_size_scaled)
```

2. Call created script from another script:
```gdscript
var my_script = MyScript.new()
my_script.generate()
```

3. Check the output:
Incorrect output:
```
_shape_size.x = 2000
_cols = 44
_shape.size.x / _cols  = 0
2000 / 44 = 45
_cell_size_scaled = (0, 0)
```

Correct output:
```
_shape_size.x = 2000
_cols = 44
_shape.size.x / _cols  = 45.4545454545455
2000 / 44 = 45
_cell_size_scaled = (45.45454, 45.35147)
```

### Minimal reproduction project

Edit: https://github.com/godotengine/godot/issues/71172#issuecomment-1377965866
[number.zip](https://github.com/godotengine/godot/files/10387228/number.zip)

**Comment by stephannv** [comment] 2023-01-10 18:36
Oh, there is a serious problem when iterating over _cols and _rows. It is crashing godot with a infinite loop:
```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int
var _rows: int

var _cell_size_scaled: Vector2

var _grid: Array

func generate() -> void:
#  uncomment these lines to force incorrect behavior
  _cols = max(floor(_shape.size.x / _cell_size), 1)
  _rows = max(floor(_shape.size.y / _cell_size), 1)

  print("_cols", _cols) # 44
  print("_rows", _rows) # 441
  _grid = []
  for i in _cols:
    print(i) # 0
    _grid.append([])
    for j in _rows: # this will cause an infinite loop and crash godot
      print(j) 
      _grid[i].append(-1)
```

@clayjohn I should update the issue title and description with infinite loop problem or it is fine just this comment?

**Comment by clayjohn** [comment] 2023-01-10 18:39
Commenting here is fine. The issue appears to be related

**Comment by stephannv** [comment] 2023-01-10 18:43
Casting to int or assigning the values at the variable declarations solves the issue:
### Casting to int
```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int
var _rows: int

var _cell_size_scaled: Vector2

var _grid: Array

func generate() -> void:
  _cols = int(max(floor(_shape.size.x / _cell_size), 1)) # <= casting to int
  _rows = int(max(floor(_shape.size.y / _cell_size), 1)) # <= casting to int

  print("_cols", _cols) # 44
  print("_rows", _rows) # 441
  _grid = []
  for i in _cols: # no infinite loop
    print(i)
    _grid.append([])
    for j in _rows:
      print(j) 
      _grid[i].append(-1)
```

### Assigning at the variable declaration
```gdscript
class_name MyScript extends Node

var _shape: Rect2 = Rect2(-1000, 100, 2000, 20000)
var _radius: float = 64

var _cell_size: float = _radius / sqrt(2)

var _cols: int = max(floor(_shape.size.x / _cell_size), 1) # calc at variable declaration
var _rows: int = max(floor(_shape.size.y / _cell_size), 1) # calc at variable declaration

var _cell_size_scaled: Vector2

var _grid: Array

func generate() -> void:
  print("_cols", _cols) # 44
  print("_rows", _rows) # 441
  _grid = []
  for i in _cols: # no infinite loop
    print(i)
    _grid.append([])
    for j in _rows:
      print(j) 
      _grid[i].append(-1)
```

**Comment by issork** [comment] 2023-01-10 20:14
This seems to be a general issue, ran into this with the Dictionary 'get' method. Methods returning Variant are no longer cast to int when returning a float and assigning to a int variable.

**Comment by adamscott** [comment] 2023-01-10 21:38
@stephannv Please upload a minimal reproduction project, especially if numerous steps are needed for recreating the issue. Each contributor would need to do these steps instead of just downloading and running your example.

**Comment by issork** [comment] 2023-01-10 22:01
Here's the MRP from the issue I closed since it was a duplicate;
https://github.com/godotengine/godot/files/10386350/DictGetMRP.zip

**Comment by stephannv** [comment] 2023-01-10 22:16
Here is the MRP:
[number.zip](https://github.com/godotengine/godot/files/10387216/number.zip)

```gdscript
extends Node2D

var _integer: int
var _float: float = 64

func _ready() -> void:
  miscalculate()
#  infinite_loop() # <= uncomment this


func infinite_loop() -> void:
  _integer = max(_float, 1)

  for i in _integer:
    print(i)

func miscalculate () -> void:
  _integer = max(_float, 1)

  var point = Vector2()

  point.x = _integer / 2

  print("This number should be 32: ", point.x)

```

**Closed** 2023-01-11 00:05 UTC
Labels: bug, topic:gdscript, regression
