### ISSUE TITLE
Popups always appear on the first monitor regardless of position of editor 

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#37326] opened 2020-03-26 18:10 UTC
**Godot version:**
https://github.com/godotengine/godot/commit/5f1107aa30295e686be6f41cb6d17fc2cff1e036

**OS/device including version:**
Windows 10

**Issue description:**
I have two monitors and popups like menus appear only on the first monitor, whereas the editor on second.

**Comment by akien-mga** [comment] 2020-03-27 08:48
Duplicate of #37320.

**Closed by akien-mga** 2020-03-27 08:48 UTC
Labels: bug, regression, topic:editor, usability
