### ISSUE TITLE
Not able to call method in subclass

### ISSUE THREAD

**Issue by qtren** [godotengine/godot#57332] opened 2022-01-28 02:15 UTC
### Godot version

4.0 alpha

### System information

Windows 10

### Issue description

Not able to overwrite queue_free for some reason. I did not test other methods. 

### Steps to reproduce

Node2D
-- Node2D

In the subnode, overwrote Node2D's queue free like this:
func queue_free():
        print("freed")
        super.queue_free()

Then in the parent Node2D's _ready()
call $Node2D.queue_free(). Nothing gets printed but in the remote scene tree, the child is freed.

![Capture1](https://user-images.githubusercontent.com/72534736/151475283-751edb43-ace6-45cc-b7b6-3d9c1a2435ab.PNG)
![Capture2](https://user-images.githubusercontent.com/72534736/151475284-d9f52328-0c16-4cbb-ac33-8f4e211e905d.PNG)
![capture3](https://user-images.githubusercontent.com/72534736/151475285-5d754691-d3bc-423b-be6c-6fd3a63376f2.PNG)

### Minimal reproduction project

[gd4test.zip](https://github.com/godotengine/godot/files/7955203/gd4test.zip)

**Comment by akien-mga** [comment] 2022-01-28 11:38
I don't think that overriding builtin methods like this is supported, nor intended to be. But it's weird that it's not raising an error here about invalid shadowing of a builtin method.

**Comment by KoBeWi** [comment] 2022-01-28 11:45
Duplicate of #55024
Seems like we don't have such warning yet, there's a PR that implements it.

**Closed by KoBeWi** 2022-01-28 11:45 UTC
Labels: bug, topic:gdscript
