### ISSUE TITLE
Writing quotation marks makes cursor jump to the bottom of the page [Windows, US International layout]

### ISSUE THREAD

**Issue by lmsonic** [godotengine/godot#25548] opened 2019-02-01 15:19 UTC
**Godot version:**
Godot 3.1 beta3, and beta2

**OS/device including version:**
Windows 7 (EDIT: i forgot to add that I'm using and American International layout for my keyboard)

**Issue description:**
When i try to write in a script a quotation mark, the cursor jumps down to the bottom of the page, selecting everything in between

![image](https://user-images.githubusercontent.com/25965198/52131428-07f70300-263d-11e9-88f9-d53ea034dc89.png)

**Steps to reproduce:**
Write a quotation mark at the top of a script

**Minimal reproduction project:**
It works for every script

**Comment by ankitpriyarup** [comment] 2019-02-08 19:06
It's seems non reproducible in Ubuntu 18.04.1 LTS

**Comment by lmsonic** [comment] 2019-02-08 19:47
> It's seems non reproducible in Ubuntu 18.04.1 LTS

Yeah, it didn't work on mine either

**Comment by Calinou** [comment] 2019-02-08 21:22
This could be related to the keyboard layout you're using on Windows. Does it happen if you use something like QWERTY instead?

**Comment by DleanJeans** [comment] 2019-02-09 08:13
Can't reproduce this on Windows 10 - 3.1 Beta 3

**Comment by lmsonic** [comment] 2019-02-09 15:55
I forgot to add it, i'm using an American layout for my keyboard

**Comment by Vulcwen** [comment] 2019-02-10 15:27
Can't reproduce this either on Windows 7 (laptop), godot 3.1 beta 3, american keyboard layout.

**Comment by EL-SHREIF** [comment] 2019-02-15 16:25
It seems non-reproducible in Ubuntu 18.10

**Comment by erri120** [comment] 2019-03-27 16:57
This happens to me every time. It's caused by the keyboard. I use the Razer Blackwidow Chroma V2 (QWERTY,Windows with US-INT layout) and I need to hit the quotation mark two times to show 

>  ""
If you press it once, nothing appears unless you press another key and it it looks like this:

> "s
This is implemented due to special letters like Ä,Ë,Ö,.. can only be typed using the quotation mark following the letter (the whole think also applies for single quotation marks á,é,ó,...).
Other editors don't care what typ of layout you have so I normally just hit the button two times to get "" and than move into the marks. 
Godot on the other hand jumps to the bottom of the script while selecting everything from the start of the mark to the end of the script. Godot probably interpretes the double press of a quotation mark as something else, resulting in the selection.
I hope this gets a fix, hitting double " works with everything else but Godot and I will not misplace years of muscle memory for on editor.

**Comment by DarknessCatt** [comment] 2019-04-02 00:16
I can't reproduce this on Godot 3.1 on OSX, however it seems godot is acknowledging your double double quotes as a "select all" shortcut. Does removing the shortcut (Editor->Editor Settings->Shortcuts->Select All) affects this?

**Comment by erri120** [comment] 2019-04-04 12:29
> 
> 
> I can't reproduce this on Godot 3.1 on OSX, however it seems godot is acknowledging your double double quotes as a "select all" shortcut. Does removing the shortcut (Editor->Editor Settings->Shortcuts->Select All) affects this?

Nope, doesn't help. Is there a debug option for Godot to see what function is called when you press double quotation marks?

**Comment by FrederickKDP** [comment] 2019-04-12 21:57
Same issue, you can "workaround" pressing " once, then space to cancel, but still is terrible not only for the extra step, but because easily you can end up erasing the whole rest of your code.
I'm using English International keyboard.

**Comment by akien-mga** [comment] 2019-04-15 08:42
Can't reproduce on Mageia 7 Linux with English (US) International layout with dead keys. Seems to be specific to that layout *and* Windows.

**Comment by akien-mga** [comment] 2019-04-15 08:42
Same problem with Dutch keyboard layout apparently as per #19976 (also on Windows).

**Comment by akien-mga** [comment] 2019-04-15 09:09
> Have to press twice the quotation mark to put it in as well.

That's normal on that layout as quotation mark is a dead key and can be used to compose accented characters. So to input it you have to press it twice, or press once and then space. But somehow it seems to mess up the TextEdit or CodeTextEditor.

**Comment by Wiering** [comment] 2019-04-22 01:36
The problem could be in the input system.

I did a little test to display which keys are detected in this case.
```
func _input(event):
	if event is InputEventKey:
		if !(event.is_echo()):
			print (str(event.pressed) + " " + str(event.scancode) + " " + event.as_text());
```
Pressing (and releaseing) Shift+" the first time:

True 16777237 Shift
True 39 Shift+Apostrophe
False 39 Shift+Apostrophe
False 16777237 Shift

And the second time:

True 16777237 Shift
True 39 Shift+Apostrophe
True 16777236 Shift+PageDown
False 39 Shift+Apostrophe
False 16777237 Shift

Or without releasing Shift in between:

True 16777237 Shift
True 39 Shift+Apostrophe
False 39 Shift+Apostrophe
True 39 Shift+Apostrophe
True 16777236 Shift+PageDown
False 39 Shift+Apostrophe
False 16777237 Shift


Similar problem: pressing ' twice:

True 39 Apostrophe
False 39 Apostrophe
True 39 Apostrophe
True 16777233 Right
False 39 Apostrophe

 (using Windows 10 with Dutch keyboard layout)

**Comment by Wiering** [comment] 2019-04-26 04:33
I did a little test in C++, printing the windows messages:

Typing "":

WM_KEYDOWN: 0x10
WM_KEYDOWN: 0xde
WM_KEYUP: 0xde
WM_KEYDOWN: 0xde
WM_CHAR: "
WM_CHAR: "
WM_KEYUP: 0xde
WM_KEYUP: 0x10

Typing '':

WM_KEYDOWN: 0xde
WM_KEYUP: 0xde
WM_KEYDOWN: 0xde
WM_CHAR: '
WM_CHAR: '
WM_KEYUP: 0xde

**Comment by catafest** [comment] 2019-07-04 12:13
the same issue with windows 8.1 and Godot 3.1 64 stable, maybe is a virus or an operating system faults because is needed to press twice the key to have a "" ?!

**Comment by catafest** [comment] 2019-07-04 12:22
Fix it
Control Panel\Clock, Language and Region\Language\Language options 
Set the Handwriting to Write each character separately

**Comment by Wiering** [comment] 2019-09-09 00:10
> Fix it
> Control Panel\Clock, Language and Region\Language\Language options
> Set the Handwriting to Write each character separately

Not quite sure which option you are referring to, but that is not a fix but a workaround (the same as changing the keyboard to English). The bug itself needs to be fixed instead of requiring users to change their settings.

**Comment by AdrianSima** [comment] 2020-03-08 09:00
This issue appears for me too in Godot 3.2 with English (US) - United States-International keyboard selected on Windows 10 (1903)
![ezgif-3-b72433f37531](https://user-images.githubusercontent.com/11497308/76159713-e44d9880-612b-11ea-81db-5ac995311e4c.gif)

**Comment by MikeMnD** [comment] 2020-03-28 22:35
I swear every time I put ""  and go typing and delete a block of my code.
Than go ctrl + z just to repeat it again...
And yeah most of the time a do " and space .. but from time to time when I forget... ugh

**Closed** 2020-05-18 14:33 UTC
Labels: bug, cherrypick:3.2, hero wanted!, platform:windows, topic:editor, topic:input
