### ISSUE TITLE
Godot 4 beta crashes when trying to import project - Linux

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#66009] opened 2022-09-17 21:18 UTC
### Godot version

4.0

### System information

Ubuntu Studio 22.04, AMD Radeom , GLESS 2

### Issue description

I wanted to open my Godot 3.5 project in Godot 4 Beta and in the initial menu after closing the pop up that indicates that I have no project available, when clicking on browse to import my project, the Engine crashes.

### Steps to reproduce

- Make sure you don't have any projects available (I haven't tested if the bug occurs when projects are available)
- Open Godot 4 beta.
- Close the pop up that asks if you want to download any available template.
- Click the import project button.
- Press browse to enter the file system.
- Godot will not enter the file system because it will crash.

**Comment by KoBeWi** [comment] 2022-09-17 21:41
Duplicate of #65474

For now you can add your project via drag and drop.

**Closed by KoBeWi** 2022-09-17 21:41 UTC

**Comment by CHIESOFTWARE** [comment] 2022-09-19 17:15
I entered it by drag and drop and now I can't even run the app image. It just doesn't work for me.
