### ISSUE TITLE
Textures are appearing darker in 2d vs 3d

### ISSUE THREAD

**Issue by KuamyWilbanks** [godotengine/godot#50923] opened 2021-07-27 03:38 UTC
### Godot version

3.3.2(stable)

### System information

windows 10, gles3

### Issue description

Images are appearing with correct color in 3d space, but in 2d space on the ui, the icons are showing up much darker. I am using the default 2d pixel import options for each icon. I've tried changing every setting, and none of them seem to fix the color of the icon. I must be doing something wrong and there's no way that it is my import settings are wrong.

I am using the same texture for the sprite3d and the sprite2d. I read that there is a possibility that the texture is getting reimported on the fly to 3d import settings instead of 2d pixel settings like I want.

### Steps to reproduce

![wrong_crunch](https://user-images.githubusercontent.com/20715339/127091442-7ffdf5de-cb2a-4b06-ab1e-15ad0e85e94d.png)
![correct_crunch](https://user-images.githubusercontent.com/20715339/127091443-db6bde99-421c-4cac-b4b4-59b1c6b9b2fb.png)
![bad_apple](https://user-images.githubusercontent.com/20715339/127091444-d8f6db82-161a-4fe5-ab25-8e2e38c97878.png)
![correct_apple](https://user-images.githubusercontent.com/20715339/127091446-312bfd64-1677-425f-b928-f36c7c05b852.png)

Use the same png as a texture and then put that texture icon on the hud as a sprite 2d and then put that same texture as a sprite3d in the 3d space.

**Comment by volzhs** [comment] 2021-07-27 03:54
MRP here
[sprite 2d and 3d.zip](https://github.com/godotengine/godot/files/6882556/sprite.2d.and.3d.zip)

GLES3 screenshot
![Screenshot_20210727_125206](https://user-images.githubusercontent.com/8281454/127092716-b10c65c5-b4bc-4caa-b144-355a846bd348.png)

GLES2 screenshot
![Screenshot_20210727_125223](https://user-images.githubusercontent.com/8281454/127092718-65784901-c39c-4303-a7a2-5d8e06eb56ad.png)

@KuamyWilbanks please attach Minimal reproduction project next time

**Comment by KuamyWilbanks** [comment] 2021-07-27 03:57
> MRP here
> [sprite 2d and 3d.zip](https://github.com/godotengine/godot/files/6882556/sprite.2d.and.3d.zip)
> 
> GLES3 screenshot
> ![Screenshot_20210727_125206](https://user-images.githubusercontent.com/8281454/127092716-b10c65c5-b4bc-4caa-b144-355a846bd348.png)
> 
> GLES2 screenshot
> ![Screenshot_20210727_125223](https://user-images.githubusercontent.com/8281454/127092718-65784901-c39c-4303-a7a2-5d8e06eb56ad.png)
> 
> @KuamyWilbanks please attach Minimal reproduction project next time

Thank you very much, will do! Also, your screenshots are much better at presenting the issue.

**Comment by akien-mga** [comment] 2021-07-27 06:28
That's normal, one texture is in linear color space and one is using sRGB. Which one is used depends on where the texture is used, see https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html#srgb and https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html#color-space

**Comment by Calinou** [comment] 2021-07-27 11:53
Duplicate of https://github.com/godotengine/godot/issues/18941 (fixed in `master`).

**Closed by Calinou** 2021-07-27 11:53 UTC
