### ISSUE TITLE
super() causing script error when overriding _init() on the child class and not the parent in release builds

### ISSUE THREAD

**Issue by as-webbyninja** [godotengine/godot#76938] opened 2023-05-11 06:51 UTC
### Godot version

4.0.3, 4.1-dev1, 4.1-dev2

### System information

Windows 11, ASUS Zephyrus G14 2022, Ryzen 9, Radeon 6700S

### Issue description

If you create a custom class script and extend it in a custom sub class script using GDScript, override `_init()` in the sub class but not in the parent class, and then call `super()` in the sub class, it will run fine in the editor or if exported with the debug template. However, if you export a release build, the `super()` call will induce a script error.

I think the bug is that the debugger should throw an error in this case. Trying the same with methods like `_ready` for classes extending nodes or even `_to_string` for a RefCounted class and running in the editor will cause a script error to be caught by the debugger.

In editor:
![debug](https://github.com/godotengine/godot/assets/125445387/f6da77c5-c9d3-4bb9-a4b0-80d2f9218033)

Release build:
![release_error](https://github.com/godotengine/godot/assets/125445387/73a9d098-7c3b-45e4-8761-e3f40ffd3bc9)

### Steps to reproduce

Create two classes
ClassTwo extends ClassOne
ClassTwo overrides virtual method _init() (**ClassOne does not**)
ClassTwo calls super() in _init()
No error in debug/editor
Error in release

### Minimal reproduction project

N/A

**Comment by anvilfolk** [comment] 2023-05-21 20:45
I'm looking into this one :)

The issue is in `ClassDB::get_method_info()`, in the following part of the code:

```
#ifdef DEBUG_METHODS_ENABLED
		MethodBind **method = type->method_map.getptr(p_method);
		if (method && *method) {
			if (r_info != nullptr) {
				MethodInfo minfo = info_from_bind(*method);
				*r_info = minfo;
			}
			return true;
		} else if (type->virtual_methods_map.has(p_method)) {
			if (r_info) {
				*r_info = type->virtual_methods_map[p_method];
			}
			return true;
		}
#else
		if (type->method_map.has(p_method)) {
			if (r_info) {
				MethodBind *m = type->method_map[p_method];
				MethodInfo minfo = info_from_bind(m);
				*r_info = minfo;
			}
			return true;
		}
#endif
```

https://github.com/godotengine/godot/blob/809a98216267f3066b9fec2f02b2042bdc9d3e0d/core/object/class_db.cpp#L515-538

The `DEBUG_METHODS_ENABLED` flag enables a check for virtual methods, whereas without that flag, as in `template_release`, no such check is done.

I believe the error in `template_release` is correct and should be replicated in the editor. The analyzer should be able to tell us whether, when calling `super()`, there are no actual implementations of the method.

**Comment by akien-mga** [comment] 2023-06-21 19:46
Reopening as #77324 was partially reverted by #78533.

**Comment by anvilfolk** [comment] 2023-06-21 20:46
Super thorough and super interesting! There are so many ways in which virtual functions can exist!

Right now this is feeling relatively similar to what already happened in #64253, where we had to essentially unify information stored in debug and non-debug builds (so more stuff ended up stored in release builds) basically so that the GDScript compiler is allowed to _not_ throw errors when attempting to typecheck something related to, in this case, virtual methods in release builds.

I'll test my current solution, which once again is about storing extra info in non-debug builds, in different builds against the examples you've given above and report back when I've got time.

It is annoying that we are increasing runtime memory usage for the sake of validating scripts which should a-priori already be known to work.

**Comment by akien-mga** [comment] 2023-06-21 20:53
If my findings are correct that `_init` is the only virtual method with this problem, we could add a special case for it instead of embedded info on all virtual methods in release builds. But there might be other reasons why virtual method info could be needed in release builds.

**Comment by YuriSizov** [comment] 2023-11-14 21:44
This was properly closed by https://github.com/godotengine/godot/pull/81808.

**Closed by YuriSizov** 2023-11-14 21:44 UTC
Labels: bug, topic:gdscript, topic:export
