### ISSUE TITLE
Enumeration cannot be exported if defined elsewhere

### ISSUE THREAD

**Issue by red1939** [godotengine/godot#46586] opened 2021-03-02 08:38 UTC
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 20H2

**Issue description:**
Enumeration "type" is not working if included from other file. The only thing you can do is to include it's values.

```
# ok
const Imported = preload("res://enum_definition.gd")

# nok
# invalid index 'Sample' in constant expression
export (Imported.Sample) var exported = 0

# nok
# The identifier "Imported" isn't a valid type (not a script or class), or couldn't be found on base "self".
var data: Imported.Sample = Imported.Sample.A
```

This is a big issue, because it forces you to only have one class that is the "owner" of the type which can export it. In the end it forces you to make a `Resource` that holds the definition and exports the type for all other consumers to use `export(Resource) var variableOfTypeEnum`.

**Steps to reproduce:**
Run the code

**Minimal reproduction project:**
[EnumInvalidIndex.zip](https://github.com/godotengine/godot/files/6067166/EnumInvalidIndex.zip)

**Comment by Calinou** [comment] 2021-03-03 14:59
Duplicate of https://github.com/godotengine/godot/issues/14681.

**Closed by Calinou** 2021-03-03 14:59 UTC
