### ISSUE TITLE
"Fullscreen" mode is not filling whole screen

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#90493] opened 2024-04-10 15:36 UTC
### Tested versions

-4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.5161) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

Godot "Fullscreen" has a very little gap at the corners and looking very bad. Alsooo it has weird gray borders too. In exclusive fullscreen this is not a problem. Also i think fullscreen mode is just maximized borderless window. Because same problem occurs on when you set borderless option true and maximize it.
![image](https://github.com/godotengine/godot/assets/78092286/16e6191b-1cc5-4131-9d71-6597ee4d36b5)

### Steps to reproduce

-Just open the godot and turn on fullscreen mode

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment] 2024-04-10 15:56
Duplicate of https://github.com/godotengine/godot/issues/63500

**Closed** 2024-04-10 15:57 UTC
