### ISSUE TITLE
Quit to Project List causes Godot to freeze

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#5665] opened 2016-07-12 23:40 UTC
**Operating system or device - Godot version:**
Windows 7, Godot 2.1 beta

**Issue description** (what happened, and what was expected):
Option Quit to Project List causes editor to freeze. The editor just hangs up and needs to be terminated. It throws out exception c0000005. The Project Manager window opens fine.

**Steps to reproduce:**
1. Open/Create a project
2. Quit to project list

**Sorry for double post #5664. We post it almost at the same time. At least we know it happens also on Win 7.**

**Comment by vnen** [comment] 2016-07-13 00:15
Closing as duplicate of  #5664.

**Closed by vnen** 2016-07-13 00:15 UTC
