### ISSUE TITLE
Windows: no popup when Godot is launched in a folder without a fully valid project

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#17352] opened 2018-03-07 22:26 UTC
Hi there,

When i launch 3.0.2 using windows shortcut Godot closes without showing the project list.

Adding parameter "-e" to shortcut command , Godot is able to launch the editor but it always opens  the same project and i must choose quit to project list to be able to choose the project i wish to work on.

It seems a bug as versions previous to 3.0.1 always launched and displayed the project list and never closed after launch.

**Comment by hpvb** [comment] 2018-03-07 22:33
There is a change in the way the project manager is spawned in 3.0.2 compared to earlier versions. Previously if a project was found but it didn't have a main scene the project manager would show. Now an error is displayed instead. If you're hitting this problem this suggests that there is a project inside the directory you're launching Godot from, but it doesn't have a main scene setup.

Run Godot from outside a project and the problem should go away.

**Comment by DevMagicLord** [comment] 2018-03-07 22:47
Godot folder had sub folders with projects,  i moved Godot to a new empty directory and it shows the project list.
A message saying Godot folder installation must not contain projects folders would help.

**Comment by hpvb** [comment] 2018-03-07 22:57
A text console should have popped up with an error. Did this not happen?

**Comment by DevMagicLord** [comment] 2018-03-07 23:28
I got the no main scene setup, but opening a project with a main scene with a previous version than trying to launch 3.0.2 it closed without no error message.
When it doesn't launch , Godot can add a message like Godot must be installed in an empty folder.

**Comment by DevMagicLord** [comment] 2018-10-08 19:18
By default Godot could run with -e parameter and try to display project list if there is any or an empty list and you could import projects.

Will this be added to 3.1 ?
Or should we make a shortcut and add -e parameter each time we get a new version ?

**Comment by akien-mga** [comment] 2018-12-17 14:11
Duplicate of #19570.

**Closed by akien-mga** 2018-12-17 14:11 UTC
Labels: enhancement, platform:windows, usability
