### ISSUE TITLE
 v3.2.stable.mono.official

### ISSUE THREAD

**Issue by Marre246810** [godotengine/godot#36017] opened 2020-02-08 15:56 UTC
**Godot version:**
 v3.2.stable.mono.official

**OS/device including version:**
Windows 10 Home

**Issue description:**
The issue is that when you create a c# script it gives you an error that goes like this:
` editor/editor_node.cpp:5268 - An EditorPlugin build callback failed.`
this problem only occurs when you create a C# script. And if you remove the script it will still not work.

**Steps to reproduce:**
Create a project, name it whatever.
Create a 2D note, choose the C# script.
try to run the script. You can even try to type in print("Hello, World!");

**Comment by Calinou** [comment] 2020-02-08 16:00
Duplicate of #35897.

**Closed by Calinou** 2020-02-08 16:00 UTC
