### ISSUE TITLE
C# scripts get reset/cleared/reverted by godot in certain circumstances

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#50163] opened 2021-07-04 16:01 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

3.3.2.stable.mono.official

### System information

Windows 10

### Issue description

As the title says, sometimes, godot resets/reverts/clears c# script file contents for reasons unknown.
It's hard to pinpoint exactly where or why it happened (not the first time i experienced this), but i recorded for a while and tried to reproduce it and 'luckily' caught it 2 times in a row - See video:

https://user-images.githubusercontent.com/8841352/124391409-ccbafb80-dcf0-11eb-85fc-49913536b3e9.mp4

Here it seems to have been triggered by opening the project, using the 'Build' option, then doing a 'Save All' (ctrl-s).
In my case rider (IDE) then reloaded the changed file from disk, so i reverted it (undo) to reclaim my missing script content (but it's not related to rider as i can see the content vanishing even from other editors as well).

### Steps to reproduce

Not sure, in my case here 3 specific files seemed affected but no other script. These are used in resources and are toolscripts, maybe that matters somehow, but others that are also used in resources didn't seem to be affected. And i found no steps to reliably trigger it, but it happens somewhat frequently.
I'll try a bit more to see if i can find a reliable MRP

**Comment by Carbone13** [comment] 2021-07-04 16:27
Confirming that it is also happening on my projects, I use the same godot version.
I also have no idea what triggers it :(

**Comment by Flavelius** [comment] 2021-07-04 17:20
After testing a bit further, the SourceCode property of the script resource in question becomes empty when this issue arises. So it seems the editor is actually persisting this empty SourceCode property into the file, while it shouldn't.

**Comment by Calinou** [comment] 2021-07-04 17:31
Can you reproduce this in previous Godot versions such as 3.2.3?

**Comment by Flavelius** [comment] 2021-07-04 18:14
Yes (3.2.3), it seems to happen quite frequently when building, then saving all.

**Comment by nongvantinh** [comment] 2021-08-24 08:45
It happens with you when moving files between folders. And do the deletes files.

**Comment by Flavelius** [comment] 2021-10-04 07:05
Still an issue in 3.3.4

**Comment by MikeSchulze** [comment] 2022-04-25 19:39
I encounter an equivalent problem by generate c# classes over my GdUnit3 c# TestSuite builder


I do as save by using the script editor to save possible changes before extending an existing script `script_editor._menu_option(EDITOR_ACTIONS.FILE_SAVE)`

My code works fine to generate the new scrip but the editor shows still the old content.

After comment out the save action the script is "reload" correctly.

So seams to be the save action is not syncronzed and is overlapping with external script changes.

**Comment by Iceball457** [comment] 2022-12-07 09:40
The worst part of this is that it also devours the local history for the file, making it impossible to recover with Undo/Redo in VSCode. Bumping this because I lost 5 hours of C# after moving a cs file from "res://Scenes/" to "res://Scripts" because Scenes is Godot's favorite directory to put new scripts for some reason.

**Comment by natefoldan** [comment] 2023-03-14 17:17
This is still happening in 4.0

**Comment by willthehuman** [comment] 2023-03-17 22:15
This happened to me in 4.0 without even moving the file. I will try to reproduce it.

**Comment by nongvantinh** [comment] 2023-03-18 00:44
I believe that it has something to do with "state." because when I close the engine and reopen it in another process, The bug does not happen anymore.

**Comment by yosimba2000** [comment] 2023-07-24 18:41
Still happening on 4.1.1 .Net version

I don't know how to reliably make the issue START to happen, but once it happens, it is persistent and is very predictable. So predictable that I know exactly when it's going to happen.

I am using Win10 22H2, C# with VSCode

Here's how it happens:
1) Open your Godot project
2) Open the source code
3) Make any change to source code and save your source code in the code editor
4) Go back to Godot, and just Save the project. You don't even need to compile. Just save.
5) Go back to source code, and find that your change has been undone.
6) Press Ctrl-Z in source code to bring back your change, then resave source code.
7) Go back to Godot and save.
8) Go back to the code editor and see that NO changes were undone. Good!

So here's what I've gathered from this, and I have observed this pattern 100% of the time.
1) Issue only happens the first time you save the project in any Godot session. A Godot session begins when you open the project file, and ends when you close it.
2) If Godot settings are set to Save first before Run (should be by default), then this issue occurs the first time you run the project in that Godot session because it saves the project first before running. Meaning it revert any code change, then compile.
3) Issue does not happen if you make a new Godot project (at least until that project gets infected some how).

**Comment by shayneoneill** [comment] 2023-08-10 03:56
I'm still getting this in 4.1 w/ Rider. I havent yet divined the cause of it, but its super frusturating.

**Comment by Culoextremo** [comment] 2023-09-16 10:36
Can confirm It happens constantly using Rider. It is pretty frustating.

**Comment by yosimba2000** [comment] 2023-09-16 22:24
I have been hit by the bug again, and I was again able to resolve it by clearing out all the files inside the `\.godot\editor` folder, except for editor_layout.cfg in order to preserve the editor layout.

**Comment by shayneoneill** [comment] 2023-09-17 18:49
There are precisely zero circumstances where the godot engine should EVER be *writing* to those C# sciptts if you are using an IDE. Start with that.....

**Comment by guoboism** [comment] 2023-09-18 03:29
Happened on Godot 4.1, twice
Code revert to some random old version hours ago
Not sure what cause it exacly, I have renamed the file around to test how godot handles script renaming

I just think that the editor should not have the access or cache the script anyhow.
This bug should be marked top priority:
- easily destroy hours of work
- violate the common sense that only myself and git can mess with my code
- still not fixed and even not replicatable from 3.x 

which means that simple opening the project somehow could ruin your code 
totally not acceptable and kills the "so far so good" atmosphere for a Unity switcher

**Comment by guoboism** [comment] 2023-09-18 03:38
> It could be fixed if someone managed to reproduce the steps to trigger this bug. In the past, I have tried to locate it, but it only occurs under certain conditions. Due to this instability, no one knows how it has happened, which is why it hasn't been resolved yet. My personal idea is to add a debug trace that throws an exception and catch it when the function performs the cleanup; then, we can write the stack trace to a file and report it here.
> 
> My second idea is to compile the Godot Engine from its source code. While developing our game, we can utilize the debugging features in Visual Studio. This way, if the reset/clear bug occurs, we'll be able to set a breakpoint and begin debugging promptly to capture the issue. As for me, I'm currently busy with a full-time job and studying AI-related topics to incorporate into my game, so I won't be significantly involved in working with Godot, at least until next year. However, you can take the lead.
> 
> You can find the script to build the Godot Engine from source, enabling C# support and generating a Visual Studio Project, in this [link](https://github.com/godotengine/godot/files/12388089/mono_compile.zip). To run it, use **PowerShell**: `Shift + right-click` and choose `Open PowerShell window here`. Note that using other shells won't work and will fail at the `dotnet nuget add source` stage. After placing the script inside the `godot` folder, execute it using the following command: `python3 mono_compile.py`. Remember, the purpose of this script is to allow you to quickly execute these commands without having to copy and paste them every time you pull the latest code from upstream. It has only been tested on Windows 10, 64-bit.

If user dont intent to use the embeded script editor, can you  simple provide an option to not allow any writing to code files overall? So that only external applications can make changes to the code files. That can prevent the damage before actually locating the actual cause

**Comment by nongvantinh** [comment] 2023-09-18 04:24
Hi @guoboism,

I share your concerns about this bug. However, I'm not certain if randomly adding code to the codebase will resolve this issue since we don't know its root cause. This bug seems to **_occur when moving a file and for others when they save their work. It appears to be related to resource saving, but the exact cause remains unknown._**

My current workaround for this bug is to use Visual Studio Code. When it occurs, I can simply press **Ctrl + Shift + P** -> **Local History: Find Entry to Restore** to recover the previously saved data.

Additionally, I have developed a practice of periodically closing and reopening the engine after the editor displays some errors that could potentially cause state changes. This is because **I never** encounter this bug when the editor is freshly opened. This practice helps ensure that I don't encounter the bug, which could potentially erase all of my work.

**Comment by guoboism** [comment] 2023-09-18 07:28
@nongvantinh
Exactly because it is hard to locate the acual cause of the bug. What I suggested is to allow turning off the godot's access to writing to code files so that user can safely use the other part of the engine, espeically for those who dont use the embeded script editor at all.

Think about this: if there is no embeded script editor, what on earth does Godot need to modify the code files for? An engine should only read, compile and run the code.

**Comment by nongvantinh** [comment] 2023-09-18 08:05
Hi @guoboism,

It's actually more than just a C# script; the editor can save various types of files, including Resource files (*.res), Scenes (*.tscn), Import data (*.import), and more. They all use the same saving mechanism.

When I work with Godot 4.1-stable, I sometimes encounter the editor wiping all the custom data I've set for the *.res files. However, when I close it and reopen it, that data comes back as if nothing has happened.

We need more people to dive into the source code to gain a deeper insight into this issue so that we can identify the possible root cause. Given the current state of the engine, which has recently undergone a massive rewrite, we shouldn't expect too much. The core team members have a lot of work to do, and they don't have enough resources to allocate to this particular problem. Just keep in mind the workaround I provided above, and you won't be held back by this bug.

**Comment by nongvantinh** [comment] 2023-09-18 09:51
Hi @guoboism,

After dragging and dropping the C# file:

It performs a lot of operations that include getting a list of files, which will have new paths as a result of this operation. Then it calls the DirAccess:rename method to perform the move operation. After that, it emits a signal for anyone registered to this signal that the file has been moved. Then it updates resource paths (_update_resource_paths_after_move), updates dependencies (_update_dependencies_after_move), updates project settings (_update_project_settings_after_move), and updates the favorites list (_update_favorites_list_after_move). I suspect that FileSystemDock::_update_resource_paths_after_move is causing the bug because it works with cached resources, as others have mentioned above.

For scene saving (Ctrl + S), it calls EditorNode::_menu_option_confirm, which leads to EditorNode::_save_scene. It saves the default environment, _save_editor_states, and then _save_external_resources, which also works with cached data. However, the bug does not occur, so I cannot say anything about this. But this is how things are actually done.

**Comment by guoboism** [comment] 2023-09-18 15:07
@nongvantinh
This is really some deep through investigation! 
But resource managing ( and this caching mechanism) looks a core part of the engine and deal with everything user created, in which case, modifications should be very cautious.

So what is the plan?
Is this something you can attempt to fix alone? Or it has to be fixed by the core team members?

**Comment by nongvantinh** [comment] 2023-09-18 15:20
Hi @guoboism,

It can be fixed by anyone, and they can contribute by creating a pull request for others to benefit from their fix. However, the code I showed above is the way the engine works, and it may not be the root cause. The bug may be elsewhere, where the engine cannot detect that the file has changed and needs to update the cache resource accordingly.

**Comment by Flavelius** [comment] 2023-09-18 16:13
https://github.com/godotengine/godot/issues/43990
I dont know if this issue is still there in 4.0 but this could be one of those wrongly 'valid' cases from the viewpoint of the engine that may cascade into other actions that would otherwise be completely expected and valid.

**Comment by evmoius** [comment] 2023-09-19 22:14
It's happening with me as well trying to do the first steps tutorials on 4.1.1. Pretty frustrating.

**Comment by nongvantinh** [comment] 2023-09-20 03:27
> It's happening with me as well trying to do the first steps tutorials on 4.1.1. Pretty frustrating. I've been enjoying Godot so far, but this is a showstopper. If the editor can just wipe out my code in an external editor (VS) then this makes Godot a no go for serious production work.
> 
> Prioritize this bug ASAP. With the amount of attention Godot is getting right now from experienced Unity developers looking for a new path forward, having issues like this is a quick way to kill the goodwill and interest.

**Since you have only followed the first steps of the tutorials, your project is considered a minimal reproduction project. Could you please try to reproduce the step that causes the bug to occur? Because without that, I would have no clue where to look.**

**Comment by evmoius** [comment] 2023-09-20 04:06
> > It's happening with me as well trying to do the first steps tutorials on 4.1.1. Pretty frustrating. I've been enjoying Godot so far, but this is a showstopper. If the editor can just wipe out my code in an external editor (VS) then this makes Godot a no go for serious production work.
> > Prioritize this bug ASAP. With the amount of attention Godot is getting right now from experienced Unity developers looking for a new path forward, having issues like this is a quick way to kill the goodwill and interest.
> 
> **Since you have only followed the first steps of the tutorials, your project is considered a minimal reproduction project. Could you please try to reproduce the step that causes the bug to occur? Because without that, I would have no clue where to look.**

Thanks for the quick response!  I've been trying to figure out what was causing it but haven't been able to reproduce it reliably. Sometimes it happens after clicking the script icon when VS isn't open. Instead of loading the work you've done, VS will load a script in whatever form you selected when creating it. I've also had it happen after saving via Ctrl + S and then switching window focus back to VS.  You can see your code disappear and the script revert to a newly created one.

What I've also noticed is that once it happens during a session, it tends to happen a lot more.  I've been working through the 3D tutorial and it's been fine for a few hours now.  If I can find a way to reliably reproduce it I'll let you know.

**Comment by guoboism** [comment] 2023-09-20 06:06
Played with a nealy empty project with one script, happened once but can not replicate.
Meanwhile, I found switching the "local to scene" on and off under resource will definitly trigger it. What does setting local is supposed to mean for a C# script here anyway?
![image](https://github.com/godotengine/godot/assets/705499/6c099b8b-cf4f-4678-9f7b-1148b06c2b34)

**Comment by nongvantinh** [comment] 2023-09-20 07:09
Hi @guoboism ,

Would you mind taking some more time to describe the details of each step you take? Alternatively, a short video recording of what you do may suffice.

**Comment by nongvantinh** [comment] 2023-09-21 02:18
It is confirmed that the guess I gave above is correct. The cache system does not recognize the `changes made outside the editor`. Because of this, it overrides the modified C# file with the cached data.
![Screenshot (4)](https://github.com/godotengine/godot/assets/53887662/3ea9e87f-929a-4b70-a8d3-7ceae880d8b2)



I'll dig deeper into the case to understand why. The Pull Request will come in 2-3 days.

**Closed** 2024-01-29 12:28 UTC
Labels: bug, topic:editor, confirmed, topic:dotnet, high priority

**Comment by lightfinesthour** [comment] 2024-04-21 09:20
in v4.2.2.stable.official [15073afe3] :

Godot resets entire script and code file when connecting a node signal to a function in an existing script file.

Why would it even touch the script when i'm connecting it INTO a script that has functions already?

I'm using visual studio code for editing the Godot script files.
This destroyed quite a bit of work, as it removes all code from a file.

I'll change to 4.3 milestone, to see if that helps

**Comment by lightfinesthour** [comment] 2024-04-21 09:38
In v4.3.dev5.official [89f70e98d]

When running the application and changing a script when the app is still running, the script will be reverted back to older state if the app is running into an error.

If i should know better than to edit scripts when the app is running, never mind this comment.
If it sounds like a bug, I can get more specific.

**Comment by AndyGisby** [comment] 2024-08-25 12:53
> @lightfinesthour The fix for this issue should be included in [Godot 4.3 dev 6](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-6/). Try it out and if you still have issues with scripts reverting their content, please open a new issue.

Alas it is not fixed for me in 4.3. Real shame. Not as frequent but I still get the code roll backs when switching between editor and VS. It does destroy hours of work and lead to puzzling debug sessions.

**Comment by AndyGisby** [comment] 2024-10-21 13:36
> The issue occurs when a script in Godot automatically opens in the Godot editor upon encountering an error. If you're editing the code in VSCode and rerunning the game, Godot still uses the version of the script that was previously opened (and unchanged) in its own editor. To fix this, you have to manually close the script in Godot, then edit and save it in VSCode again before running the game.
> 
> This can we fixed is we stop this behavior if external code editor is set.

So, I'm using Visual Studio 2022 and C# for 99.9% of my script work. I can't see where (in the godot Editor) the C# scripts are "open" to close them. Not on the scripts tb for sure? Also, I wonder if there is a file permission clash as I sometimes get the "save as" box pop-up in Visual Studio (after a Ctrl-S) for an existing script - This is usually the red flag for rollback behaviour. Anyway, I'm SO aware of this gotcha now I tend to try a quick editor invoked scene build and run and watch the visual studio editor window like a hawk (Ctrl-Z to undo the reversion, save, try again, etc...) with each code iteration. Not great.

**Comment by MystikalPooka** [comment] 2024-12-30 09:05
This is still happening and I just lost an entire day's worth of work and can not get it working again.

I made the changes to the file, but now everything is messed up. Shader globals no longer get accessed from project settings, even though I can interact with them via C#... Everything is broken now and I am unable to do anything.

New information:

This started happening when godot crashed and was unable to be restarted *at all* due to the shader global ImageTexture being saved in a format that could not load ('ImageTexture' class not found)

I removed the offending shader globals and removed all cache in .godot directory, to find out that not only did 2 of my C# files revert back to HOURS ago - The method names were things I had never even put in (like NewMethod())

PLEASE someone help fix this... I can't keep losing progress like this.

**Comment by D-MAS** [comment] 2025-03-29 00:12
i had this problem too.

Editor > Editor Settings > Text Editor > Use External Editor seems to fix
