### ISSUE TITLE
Changing the type of a node that has been transformed into ROOT deletes all nodes

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27246] opened 2019-03-19 20:43 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Changing the type of a node that has been transformed into ROOT deletes all nodes

**Steps to reproduce:**

1) Create a new scene /  3D scene
![image](https://user-images.githubusercontent.com/11199752/54640025-8ed93100-4a6d-11e9-9bbb-5b3cb8fe36da.png)
2) Create a new node
![image](https://user-images.githubusercontent.com/11199752/54640053-a1536a80-4a6d-11e9-86e1-a7df41456407.png)
3) Right click on the new node and click on "Make Scene Root"
![image](https://user-images.githubusercontent.com/11199752/54640154-d95aad80-4a6d-11e9-8c6d-db0b288ff806.png)
4) Right click on the new root node and click on "Change Type" (choose for example, "Spatial")
![image](https://user-images.githubusercontent.com/11199752/54640223-060ec500-4a6e-11e9-9818-ce41f07e9ab7.png)
5) All children nodes disappear
![image](https://user-images.githubusercontent.com/11199752/54640309-3f473500-4a6e-11e9-8429-da1d123b76d9.png)
6) And also you can't undo
![image](https://user-images.githubusercontent.com/11199752/54640371-66056b80-4a6e-11e9-957b-c96d5dc990b2.png)

**Comment by Zylann** [comment] 2019-03-20 17:55
Similar to https://github.com/godotengine/godot/issues/27222

**Comment by Zireael07** [comment] 2019-03-20 17:58
But not an exact dupe, I believe?

**Comment by groud** [comment] 2019-03-21 11:08
Yes, closing as a duplicate of #27222

**Closed** 2019-03-21 11:09 UTC
Labels: archived

**Comment by follower** [comment] 2019-08-28 16:40
Based on [my investigations](https://github.com/godotengine/godot/issues/27222#issuecomment-525824810) it seems this issue wasn't an exact duplicate of #27222 because it seems while *this* issue no longer occurs in a semi-recent nightly build, the issue described in #27222 *does* still occur.
