### ISSUE TITLE
microsoft visual c++ runtime library

### ISSUE THREAD

**Issue by frrabelo** [godotengine/godot#67166] opened 2022-10-10 00:04 UTC
### Godot version

Godot_v4.0-beta1_win64.exe

### System information

Intel Core i3 2.20GHz RAM 8GB Windows10 64bits Video: GT520 1GHz.  Although GLES3 works. In godot3.5.1 I use GLES2 to avoid problems. But the error happened in godot4.0b1.

### Issue description

I usually use version 3.5.1 downloaded by Steam which by the way works very well. But today I decided to test "Godot_v4.0-beta1_win64.exe" and it didn't open. Just got an error screen: "microsoft visual c++ runtime library". Image link: https://photos.app.goo.gl/uM38eM7S5J6a22Ao8 
https://photos.app.goo.gl/NTsZ518nGccr9VG18
I clicked the "Repetir" button (Retry button). and then Godot closed.
I made other attempts and they all failed.
I reinstalled the "microsoft visual c++ runtime library" package but the error remains.
If anyone here knows of any extra procedures involved in the damn microsoft librarian I would be grateful to know.
I hope this error can be fixed in the future. Thanks!
![erro godot4](https://user-images.githubusercontent.com/37917771/194784602-fbdf4b2c-163f-4fb4-89ba-c5f7663d0109.png)
![erro godot4 cmd](https://user-images.githubusercontent.com/37917771/194784778-e3bafeb2-97bd-4388-aa47-bba0aba97c70.png)

### Steps to reproduce

I downloaded godot4 from the link:
https://downloads.tuxfamily.org/godotengine/4.0/beta1 from page: https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1#downloads
unzipped in windows 10
I ran the "Godot_v4.0-beta1_win64.exe" file
and the error screen appeared
reinstalled the microsoft package
https://www.microsoft.com/en-us/download/confirmation.aspx?id=102159
restart the computer
I ran the "Godot_v4.0-beta1_win64.exe" file again
and the error screen appeared again

### Minimal reproduction project

Godot4 did not open.

**Comment by Zylann** [comment] 2022-10-10 01:12
There is a hint in the popup, and it says more in the console: your graphics card seems to be too old to support Vulkan. I checked [here](https://www.techpowerup.com/gpu-specs/geforce-gt-520.c285) and it says your card model Vulkan support is `N/A`. Other sources like [here](https://forums.developer.nvidia.com/t/vulkan-not-supported-on-gt520/54610/2) or the absence of your card in [this page](https://developer.nvidia.com/vulkan-driver) suggest the same.

**Comment by akien-mga** [comment] 2022-10-10 09:38
Duplicate of #58927 (same cause, that bug tracks how it should be resolved).

**Closed by akien-mga** 2022-10-10 09:38 UTC

**Comment by frrabelo** [comment] 2022-10-11 01:48
Thanks for the answer!
