### ISSUE TITLE
Some links in Godot Editor help don't work.

### ISSUE THREAD

**Issue by germanalen** [godotengine/godot#9641] opened 2017-07-14 08:19 UTC
**Operating system or device - Godot version:**
Manjaro XFCE Edition - Godot 3.0 alpha (https://github.com/godotengine/godot/commit/9a502d3c17d4701b0fd8390e515c52a69dc0bf85)

**Steps to reproduce:**
Open help->Classes->Viewport.
Press first few method names like clear(), find_world().

**Comment by quinnyo** [comment] 2017-07-22 02:50
I think this issue is the same as one I noticed a while ago. It's been like this for quite a long time on the 3.0 master branch at least.

In most pages, (test Node, Viewport) - without scrolling, links below "Public Methods" do not work, but links above do. You can also see the cursor is stuck as the "link clicking" cursor while over the non-working region. If you scroll down so that "Public Methods" is the first visible line, the links work.

In pages like `@GDScript` (because it has no links before Public Methods?), all the links work without scrolling.

**Comment by henkz1** [comment] 2017-09-12 21:51
Been like this for a long time..  https://github.com/godotengine/godot/issues/3671

**Comment by bojidar-bg** [comment] 2017-09-13 06:54
Duplicate of #3671 indeed.

**Closed by bojidar-bg** 2017-09-13 06:54 UTC
Labels: bug, topic:editor
