### ISSUE TITLE
File System Browser not showing contents

### ISSUE THREAD

**Issue by vkbsb** [godotengine/godot#5590] opened 2016-07-08 02:57 UTC
**Operating system or device - Godot version:**
MacOS X
Godot -- master branch JUL 8th 2016

**Issue description** (what happened, and what was expected):
When you open a project with the latest commits from JUL8th, the file system browser stops showing 
the contents of the project directory.  (Works with JUL7th master build).

**Steps to reproduce:**
Checkout the code to the commit d8c31e0e7480906ccf230892b090e3c3cbe1b271 
compile the code and open any of the existing godot projects, you will see that the filesystem
block is not showing the directory contents.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-07-08 06:55
I can reproduce, in e.g. [Jetpaca](https://github.com/KOBUGE-Games/jetpaca) it will only show the contents of the main `res://` dir, but not its subfolders.
![spectacle h14275](https://cloud.githubusercontent.com/assets/4701338/16679499/419edba2-44e8-11e6-8997-de661c2ef369.png)

**Comment by akien-mga** [comment] 2016-07-08 07:06
I think it might be a regression from #5538, investigating.

**Comment by akien-mga** [comment] 2016-07-08 07:16
Alright, I found the regression, sorry about that.
Guess I'll re-review this merged PR to ensure there aren't other such potential regressions.

**Closed** 2016-07-08 07:16 UTC
Labels: bug, topic:editor

**Comment by juliopcrj** [comment] 2020-04-21 06:14
I'm using the latest version from the website, 3.2.1.stable.official, and I'm also experiencing this issue.

Running on a Ubuntu Mate 18.04.

Yesterday I had Kubuntu installed, and I didn't have this problem.

**Comment by akien-mga** [comment] 2020-04-21 06:34
That's very unlikely to be related to a regression fixed 4 years ago. Please open a new bug report.

**Comment by juliopcrj** [comment] 2020-04-21 18:24
Actually, I'm thinking this should be a compatibility issue with the Mate desktop environment, since I just switched to xubuntu 19, and it's working now.

The kubuntu I had installed was also 18.04LTS, so, since the only thing that changed was the DE, I'm guessing that much.
