### ISSUE TITLE
VisualServer Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#34638] opened 2019-12-27 16:06 UTC
**Godot version:**
3.2 beta4 mono
**OS/device including version:**
debian 10
**Issue description:**
Endless log error
E 0:00:01.717   getornull: Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C++ Source>  ./core/rid.h:160 @ getornull()

**Steps to reproduce:**
follow this tutorial https://docs.godotengine.org/en/latest/tutorials/optimization/using_servers.html

**Minimal reproduction project:**
as described in tutorial

**Comment by volzhs** [comment] 2019-12-27 16:17
attaching a minimal reproduction project helps to fix it faster.
everyone who has an interest in this issue needs to create their own demo project to figure out.

**Comment by git2013vb** [comment] 2019-12-28 14:35
> attaching a minimal reproduction project helps to fix it faster.
> everyone who has an interest in this issue needs to create their own demo project to figure out.

I din't make any my own project at all. I used just this code: 
![image](https://user-images.githubusercontent.com/13235119/71545117-1d74ca00-297f-11ea-9368-bd1311191027.png)

Nothing more nothing less

**Comment by Neyzenn** [comment] 2020-02-26 23:19
I am having the same error with 2D, I decided to do a empty project to test all the examples code of server optimization because when use the 3D example for my project simple nothing happen, I just don't see the mesh in editor or in play mode, this image below refer to 2D example code error. 
![Captura de Tela (25)](https://user-images.githubusercontent.com/18087360/75396970-7eb00f80-58d4-11ea-9b10-31728218537c.png)

**Comment by clayjohn** [comment] 2020-02-26 23:46
@Neyzenn 

Thanks for pinging this. The problem is that you are not keeping the reference to ``sprite`` onces the reference goes out of scope the sprite is freed. However, the VisualServer expects it to be kept around. Thats why there is a comment in the script that says "Remember, keep this reference"

IMO example code should be runnable by copy and pasting so this code section should be updated to be
```
extends Node2D

var sprite

func _ready():
    # Create a canvas item, child of this node.
    var ci_rid = VisualServer.canvas_item_create()
    # Make this node the parent.
    VisualServer.canvas_item_set_parent(ci_rid, get_canvas_item())
    # Draw a sprite on it.
    # Remember, keep this reference.
    sprite = load("res://mysprite.png")
    # Add it, centered.
    VisualServer.canvas_item_add_texture_rect(ci_rid, Rect2(sprite.get_size() / 2, sprite.get_size()), sprite)
    # Add the item, rotated 45 degrees and translated.
    var xform = Transform2D().rotated(deg2rad(45)).translated(Vector2(20, 30))
    VisualServer.canvas_item_set_transform(ci_rid, xform)
```

**Comment by Neyzenn** [comment] 2020-02-27 00:51
Now I understand, I did the same in 3D code example and work fine, Thank you @clayjohn.

**Closed** 2020-03-03 19:05 UTC
Labels: cherrypick:3.2, confirmed, documentation, junior job
