### ISSUE TITLE
MacOS: File icons not showing correctly.  Default .gd, .gdshader icon.

### ISSUE THREAD

**Issue by LoadingStill** [godotengine/godot#94296] opened 2024-07-13 03:02 UTC
### Tested versions

— Reproducible 4.2.2-stable, 4.2.1-stable

### System information

MacOS 14.5 - M1

### Issue description

Some default file icons are not showing properly.
<img width="1209" alt="Screenshot 2024-07-12 at 10 26 38 PM" src="https://github.com/user-attachments/assets/42e68af1-d639-44dc-9b91-566582a3f639">
The icon for .gd is in the application as seen above. And is set correctly in the file settings as seen below.
<img width="626" alt="Screenshot 2024-07-12 at 10 12 01 PM" src="https://github.com/user-attachments/assets/0a1630ff-e94f-4d8b-8e04-bd7bd30cd8b2">

Known files with issue:
.gd - the default icns file is in the application config.
.gdshader - the default icns file is in the application config.

Files I can confirm work as intended:
.tscn - the default icns file is in the application config.

### Steps to reproduce

Import or start a new project in macOS.
Add some files.
Save.

### Minimal reproduction project (MRP)

GitHub will not let me upload a .gd file, so here is the code for one.

main.gd
```
extends Sprite2D

var score := [0, 0]# 0:Player, 1: CPU
# Speed at which the paddles move.
const PADDLE_SPEED : int = 500

# goal sound
@onready var scorePlayerSound = $scorePlayer
@onready var scoreCpuSound = $scoreCPU


func _on_ball_timer_timeout():
	$Ball.new_ball()

func _on_score_left_body_entered(body):
	score [1] += 1
	$Hud/CPUScore.text = str(score[1])
	scoreCpuSound.play()
	$ballTimer.start()
	


func _on_score_right_body_entered(body):
	score [0] += 1
	$Hud/PlayerScore.text = str(score[0])
	$ballTimer.start()
	scorePlayerSound.play()

```

**Comment by bruvzg** [comment] 2024-07-13 07:06
Since these file types have `UTTypeConformsTo` set to `public.script`, Finder will try to preview its context as text by default, this is expected behavior. You can toggle it in the folder options:

https://github.com/user-attachments/assets/b0e5dd43-9b6d-4a93-bb90-1711907eaff4

**Comment by Calinou** [comment] 2024-07-13 18:05
Closing per @bruvzg's comment.

**Closed by Calinou** 2024-07-13 18:05 UTC
Labels: platform:macos
