### ISSUE TITLE
Tween does not modify CanvasItem's modulate with a self reference

### ISSUE THREAD

**Issue by danielbill** [godotengine/godot#73918] opened 2023-02-25 10:33 UTC
### Godot version

4.0 RC5

### System information

win10 Gles3 

### Issue description

construct_tween.tween_property(self, "modulate", Color(1,1,1,0), 2)
this line just dont work

### Steps to reproduce

construct_tween = get_tree().create_tween()

construct_tween.tween_property(self, "modulate", Color(1,1,1,0), 2)

### Minimal reproduction project

sorry

**Comment by YuriSizov** [comment] 2023-02-25 12:26
Please provide a reproduction project. There may be an error in your scripts.

**Comment by danielbill** [comment] 2023-02-25 15:03
> Please provide a reproduction project. There may be an error in your scripts.

the whole project is too big ,pls check dig_site.gd
[building.zip](https://github.com/godotengine/godot/files/10831502/building.zip)

**Comment by KoBeWi** [comment] 2023-02-25 15:55
Can't reproduce

https://user-images.githubusercontent.com/2223172/221366616-8fd263e4-f141-47d5-b5bf-f6e545e30ff2.mp4

So it's indeed likely something wrong in your code, but the two scripts you attached don't even run due to errors.
I'd suggest trying to reproduce the issue in a fresh project.

**Comment by KoBeWi** [comment] 2023-05-14 23:01
It's #63994, not related to Tweens at all.
Closing as the OP didn't provide any better MRP. Might've been the same ysort bug.

**Closed by KoBeWi** 2023-05-14 23:01 UTC
Labels: bug, needs testing, topic:animation
