### ISSUE TITLE
Runtime Startup Error with two Graphics cards (Nvidia and ATI) on Windows

### ISSUE THREAD

**Issue by Ramedes** [godotengine/godot#62216] opened 2022-06-19 12:23 UTC
### Godot version

3.4 and 4 Alpha

### System information

NVidia and ATI

### Issue description

OS: Windows 10 Home, x64
Win10-Version: 21H1 (OS Build 19043.1766)
Windows Feature Experience Pack: 120.2212.4180.0
Languages: Display English, Keyboard German
RAM: 16 GBytes (tested with Memtest86+, all tests passed)

Graphics:
NVidia Geforce 1650 GTX -> (NVidia Graphics Driver 516.40 Game ready) - Microsoft WHQL certified
AMD Radeon RX Vega 11  Graphics (Ryzen5 built in), Driver vers: 27.20..14536.3  - Microsoft WHQL certified

### Steps to reproduce

The Situation:
If you build Godot 3.x or Godot 4.x on Windows 10 with Scons + Visual Studio 2022 (latest patches installed)
the compilation succeeded without any errors (Debug and Release build) plus Tools. The Exe binaries are
not crippled or corrupt.

The Problem:
If you run the freshly built "godot.windows.opt.tools.64.exe", the Editor doesn't show up but there is a Visual C/C++ 
runtime error (a Assertion) and the App crashes.

### Minimal reproduction project

Work around:
If you disable the ATI Graphics Driver in Windows Device Manager (let on Nvidia only) the Error disappears
and doesn't come back even if you quit the Godot Editor, re-enable the ATI Graphics Driver and restart the Editor.

**Comment by Calinou** [comment] 2022-06-19 18:10
Duplicate of https://github.com/godotengine/godot/issues/57708.

**Closed by Calinou** 2022-06-19 18:10 UTC
Labels: bug, platform:windows, topic:rendering
