### ISSUE TITLE
Project does not open in old version of Godot Engine

### ISSUE THREAD

**Issue by JulioYagami** [godotengine/godot#24103] opened 2018-12-01 10:32 UTC
**Godot version:**

Godot Engine 3.0.6 and 3.1

**OS/device including version:**

Windows 7 Ultimate 64-bits

**Issue description:**

I created a project in Godot Engine 3.0.6, so I opened it in version 3.1 and when I went back to using 3.0.6 it did not open it so I could edit it.

**Steps to reproduce:**
Create a project in the old version, open in a newer version and try to reopen in the old version.

**Minimal reproduction project:**

**Comment by JulioYagami** [comment] 2018-12-01 10:34
I want to know if there are a way to reverse this problem.

**Comment by guilhermefelipecgs** [comment] 2018-12-01 11:39
Try open `project.godot` and change `config_version=4` to `config_version=3`.

**Comment by groud** [comment] 2018-12-01 11:53
As @guilhermefelipecgs said, change the config_version to 3, but also delete the input mapping entry to reset them.

Closing as a duplicate of #18758.

**Closed by groud** 2018-12-01 11:53 UTC

**Comment by JulioYagami** [comment] 2018-12-01 19:49
> As @guilhermefelipecgs said, change the config_version to 3, but also delete the input mapping entry to reset them.
> 
> Closing as a duplicate of #18758.

How do I make the second item?

**Comment by groud** [comment] 2018-12-01 20:12
You open the project.godot file with a text ediror and delete the input map dictionary.

**Comment by JulioYagami** [comment] 2018-12-01 20:36
I deleted all the inputs and I continue receiving "Load Erros" messages.
"Unable to write to file" and the project.godot path.
"file in use, locked or lacking permissions"

**Comment by groud** [comment] 2018-12-01 20:47
This is another problem. You can try deleting the file.
But it's likely your os permission that prevent the file opening.
