### ISSUE TITLE
Improving SamplePlayer delay when playing a sound

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#4261] opened 2016-04-07 21:21 UTC
**Operating system or device:** Windows 7 x86_64 with Godot Engine 2.1 (Steam version)

**Issue description** I'm making a rythm game, and when a note is played, a "hitsound" is played. But, the sound isn't sync'ed with the user input. I searched on the web and I found that there are a latency with the audio of Godot engine.

So, maybe add a way to have a pre-buffered SamplePlayer and modifiying the audio server for near 0 latency, or just improving latency with SamplePlayer and every audio-related stuff.

**Steps to reproduce:** A SamplePlayer configured with a little sound. Set input processing to true and when a key is pressed, play the sound.

**Link to minimal example project** [Mega.nz](https://mega.nz/#!Lto22IbJ!U8u9PSpqEiukhxmAL3JayP9t1iGz0FGDZCP-7Fyw730) (press the space key for playing the sound)

**Comment by Geequlim** [comment] 2016-05-01 13:48
The same problem with my project.
https://github.com/Geequlim/FlappyBird

**Comment by Zylann** [comment] 2016-05-30 15:33
I have the same issue. My game is playable but it feels like hit and click sounds are a bit off compared to other engines and games.

**Comment by GodotIsAMess** [comment] 2016-11-25 02:43
Because there is a 200 + ms lag for sound input:

Very large bug issue on it here: https://github.com/godotengine/godot/issues/6965, which the developers don't think it's a huge issue, but would rather work on C# integration!

However, you know, 200ms lag for playing sound effects doesn't impact the aesthetics / fluidity of gameplay at all. /s

**Comment by bojidar-bg** [comment] 2016-11-25 08:54
Uh, now I don't know if I should mark this as a duplicate of #6965 or vice-versa. ( @godotengine/bugsquad  )

**Comment by bojidar-bg** [comment] 2017-01-03 18:16
Since the other issue was discussed on more, I guess I'll close this one :smiley:

**Closed by bojidar-bg** 2017-01-03 18:16 UTC
Labels: bug, topic:core
