### ISSUE TITLE
Building Android template fails (2.1)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9769] opened 2017-07-22 13:38 UTC
**Godot version: 2.1/HEAD 63a9b021**

**Issue description:**
Build stops with this error

> thirdparty/libpng/arm/../pngpriv.h: Assembler messages:
> thirdparty/libpng/arm/../pngpriv.h:476: Error: bad instruction `typedef unsigned long png_ptruint'
> clang: error: assembler command failed with exit code 1 (use -v to see invocation)
> scons: *** [thirdparty/libpng/arm/filter_neon.android.opt.debug.armv7.neon.o] Error 1
> scons: building terminated because of errors.

I don't know if this is the same error that was recently fixed in master.

**Comment by akien-mga** [comment] 2017-07-22 15:54
That's a regression from the upgrade to libpng 1.6.30: https://github.com/godotengine/godot/commit/cf52c630341ccd73accb4e6241d96fdfef603666#diff-d623a7b68668214613f9ea22fe00d032L469

It was "fixed" in master by #9722, but I would prefer merging an upstream fix than an apparent workaround. The same patch is mentioned in a netBSD bug report FWIW: http://mail-index.netbsd.org/pkgsrc-bugs/2017/07/05/msg062295.html

The proper upstream fix seems to be this commit: https://github.com/glennrp/libpng/commit/660ce585975b3bdfbd39cd9fe28d4293da05700d

**Comment by akien-mga** [comment] 2017-07-22 16:43
Should be fixed by 39f0dcc, confirmation welcome :)

**Closed by akien-mga** 2017-07-22 16:43 UTC
Labels: bug, platform:android, topic:drivers

**Comment by eon-s** [comment] 2017-07-22 17:31
That was quiiiick, works now :godmode:
