### ISSUE TITLE
Bunch of TODOs in camera_win.cpp

### ISSUE THREAD

**Issue by EyadTamer999** [godotengine/godot#74241] opened 2023-03-02 17:05 UTC
### Godot version

4.0 Stable

### System information

Windows

### Issue description

there exists a lot of unresolved TODOs in file [`modules/camera/camera_win.cpp`](https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/modules/camera/camera_win.cpp)

### Steps to reproduce

N/A just some TODOs

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment] 2023-03-02 17:06
That's not a bug? It's not implemented at the moment

**Comment by EyadTamer999** [comment] 2023-03-02 17:09
my bad, just wanted to point out the TODOs in that file. 
lmk if I should close the issue or keep it as a reminder, as the TODOs might slowly be forgotten.

**Comment by akien-mga** [comment] 2023-03-02 17:09
Duplicate of #46531.

**Closed by akien-mga** 2023-03-02 17:09 UTC
