### ISSUE TITLE
Scene internal mesh normals break on Godot 3 to Godot 4 conversion

### ISSUE THREAD

**Issue by NykolaR** [godotengine/godot#73901] opened 2023-02-25 01:49 UTC
### Godot version

3.5.stable, 4.0rc5

### System information

Linux, AMD. Effects all 4.0 backends

### Issue description

Using the Godot 4 conversion tool to convert Godot 3 3D projects, any scene with mesh data inside of it that I've tried gets converted with what I think are broken normals (see screenshots below)

Godot 3 minimal scene
![image](https://user-images.githubusercontent.com/15218653/221329311-470819b5-47f1-4216-9a05-ed3ebcd945a3.png)

Godot 4 conversion scene
![image](https://user-images.githubusercontent.com/15218653/221329331-3fb0d449-36cb-4c99-a221-f7b0b7826609.png)

### Steps to reproduce

Create any scene in Godot 3 with internal mesh data, convert project to Godot 4

### Minimal reproduction project

[ConversionTest_GD3.zip](https://github.com/godotengine/godot/files/10830016/ConversionTest_GD3.zip)

**Comment by Calinou** [comment] 2023-02-25 17:05
Duplicate of https://github.com/godotengine/godot/issues/63550.

**Closed by Calinou** 2023-02-25 17:05 UTC
Labels: topic:core, topic:rendering, documentation, topic:import, topic:3d
