### ISSUE TITLE
[Feature Request] Add an ability to run script in editor

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#12944] opened 2017-11-15 06:12 UTC
Just like unity's ContextMenuAttribute.
For example:
```gdscript
tool_button func foo():
    print("bar")
```
Then there would be a button called "foo" in inspector, and I can click it to call foo().

**Comment by Calinou** [comment] 2017-11-15 06:54
Can you give concrete use cases of this feature, and why the `tool` keyword at the top of a script isn't sufficient?

**Comment by cutepig49** [comment] 2017-11-15 07:16
Sure.
For example, I am making a tilemap based game, and I want to import my game level from an external editor such as Tiled.
Then,
```gdscript
tool_button func import_map():
    load_map_from_tiled()
    create_tiles()
```
would be great.
Everytime I click the button, my script would load the map file, and render it in editor.

`tool ` keyword seems not let me do this manually, I even dont know when it calls _ready().

**Comment by Zireael07** [comment] 2017-11-15 07:29
@cutepig49 Look up editor plugins in docs? It'd let you do what you want.

**Comment by bojidar-bg** [comment] 2017-11-15 11:30
Duplicate of #9380. Also, the usecase presented should be doable with editor plugins instead.

**Closed by bojidar-bg** 2017-11-15 11:30 UTC
