### ISSUE TITLE
Multimeshinstance does not show in Play Project view (F5)

### ISSUE THREAD

**Issue by infohub-gather** [godotengine/godot#76834] opened 2023-05-08 11:14 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, AMD CPU, Nvidia 3060Ti, Vulkan

### Issue description

I can set up a multimeshinstance quite succesfully in the Godot Editor. I see the multimeshinstances in the Editor.

When I press F5 (Play Project) , no multimeshinstances are visible.

### Steps to reproduce

See the steps above. The screenshot shows the meshes instanced properly. When playing F5, no multimesh is visible.

![multmesh](https://user-images.githubusercontent.com/40435100/236809785-4463936b-8df0-4ca2-a260-508221a4cf58.jpg)

### Minimal reproduction project

N/A

**Comment by kleonc** [comment] 2023-05-08 12:38
> The screenshot shows the meshes instanced properly. When playing F5, no multimesh is visible.
> 
> ![multmesh](https://user-images.githubusercontent.com/40435100/236809785-4463936b-8df0-4ca2-a260-508221a4cf58.jpg)

There's no active camera within the scene shown up above. No idea whether you're actually running that scene, or maybe you're instancing this scene in some other scene where a camera is present. Can't verify/test as there's no MRP (minimal reproduction project) provided.

**Comment by infohub-gather** [comment] 2023-05-08 13:13
@kleonc I have camera in another scene, and this scene gets instanced into that one. I will try to get you a minimal repro project.

**Comment by infohub-gather** [comment] 2023-05-09 09:06
I am currently trying to mimic the conditions under which the main project operates to produce a MRP.

My main thinking cap is that it maybe something to do with spawning the multimesh in an existing scene, and from that perhaps something with the scene not triggering a draw on the multimeshinstance with the available cameras?

**Comment by AThousandShips** [comment] 2023-05-09 11:57
This is why we suggest strongly to make an MRP, not just to reduce the work people have to do when investigating it, but to actually get a reliably reproducible case and work out what possible other issues might play a part

**Comment by infohub-gather** [comment] 2023-05-09 12:14
@AThousandShips Good point. I do wanted to get this issue out there, so it can be found and maybe find others with a similar problem and get to the bottom of it. Hopefully I can get an MRP out soon.

**Comment by kleonc** [comment] 2023-05-09 13:08
@infohub-gather Yeah, as mentioned this issue is currently pretty much not actionable. However, I'd suggest you to check out the behavior (within that project you can't share) for different rendering methods:
![Godot_v4 0 2-stable_win64_NsCMACOQWm](https://github.com/godotengine/godot/assets/9283098/3587b08a-063a-46f6-b463-1a5939c3f4f3)
If it's "not working" only for the one you're using then it's indeed likely a bug, otherwise it could be e.g. something about your setup. Can be only guessing.

And of course check out whether there are any errors in the console (as you haven't said anything about errors / no errors).

**Comment by MGilleronFJ** [comment] 2023-05-12 12:56
See also:
https://github.com/godotengine/godot/issues/67287
https://github.com/godotengine/godot/issues/56357

**Comment by Calinou** [comment] 2023-05-15 14:47
- Duplicate of https://github.com/godotengine/godot/issues/67287.

**Closed by Calinou** 2023-05-15 14:47 UTC
Labels: needs testing, topic:3d
