### ISSUE TITLE
Custom cursor is visible on touchscreen

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#4187] opened 2016-03-31 00:42 UTC
**Operating system or device:**
Android (6.0.1)

**Issue description** (what happened, and what was expected):
The cursor is visible on touchscreens when set to a custom one.

**Comment by reduz** [comment] 2016-06-23 21:43
custom cursors need to be implemented properly with hardware APIs in 3.0, for now i suppose you can hide it using the Input API

**Comment by vnen** [comment] 2016-06-23 23:01
@reduz `Input.set_mouse_mode()` is not working with custom cursors, see #3086.

**Comment by reduz** [comment] 2017-08-04 22:53
moved to 3.1 also a duplicate of.. uh.. can't find it but it's a duplicate

**Closed by reduz** 2017-08-04 22:53 UTC
Labels: bug, platform:android, topic:core
