### ISSUE TITLE
Editor Crashes using floating script window while refocusing it

### ISSUE THREAD

**Issue by hoywren** [godotengine/godot#82159] opened 2023-09-23 00:42 UTC
### Godot version

4.1.1

### System information

Windows 10 - Godot v4.1.1.stable -Vulkan (Forward+)

### Issue description

Editor crashes when the scripting window is in a floating state and un/focusing it with alt + tab. 

### Steps to reproduce

I've been able to reproduce this every time:
1) Open Godots script editor.
2) Put the script editor in floating window state.
3) Alt + Tab.
4) Refocus editor.

### Minimal reproduction project

N/A

**Comment by kitbdev** [comment] 2024-02-10 20:08
Cannot reproduce in 4.1.1 or other 4.1.x versions.
At most I can get an error to show `platform/windows/display_server_windows.cpp:1160 - Condition "wd_window.transient_parent == p_parent" is true.`, but I can't get it to crash.

**Comment by AThousandShips** [comment] 2024-03-06 10:31
Closing as resolved, if someone can replicate this on a supported version please comment

**Closed by AThousandShips** 2024-03-06 10:31 UTC
Labels: bug, topic:editor, needs testing, crash
