### ISSUE TITLE
Signal functions parameters are missing when editing existing function from the UI

### ISSUE THREAD

**Issue by Elektordi** [godotengine/godot#72041] opened 2023-01-25 13:59 UTC
### Godot version

At least on v4.0-beta14 and v3.5-stable

### System information

Ubuntu 20.04

### Issue description

When editing signal connections on the UI:
![image](https://user-images.githubusercontent.com/1229473/214581673-906f3ab8-d0fc-4b53-9dc9-c2981567c3ee.png)

A function with a new name is created, but the parameters are missing:
```
func _on_Icon_child_entered_tree(node):
    pass # Replace with function body.

func _on_Icon_child_entered_tree_newname():
    pass # Replace with function body.
```

_Not sure if it is linked, but the target function name indicated below the signal on the UI is also missing its parameter:_
`. :: _on_Icon_child_entered_tree()`

### Steps to reproduce

- Create empty project, a scene and a Node
- Create a script attached to the Node
- Connect a signal with a parameter using the "Node" panel
- Edit the function name on the "Node" panel

### Minimal reproduction project

No need, the bug happens on an empty project.

**Comment by KoBeWi** [comment] 2023-01-26 11:00
Duplicate of 43219

**Closed by KoBeWi** 2023-01-26 11:00 UTC
