### ISSUE TITLE
Godot 4 script with an empty += assignment crashes the editor

### ISSUE THREAD

**Issue by Nuciloco** [godotengine/godot#51056] opened 2021-07-30 06:54 UTC
### Godot version

v4.0.dev.calinou [48857194b]

### System information

Windows 10, Vulkan, Nvidia GTX 750 Ti

### Issue description

The code that crashes the game is below. What causes the engine to crash is the ``direction +=`` line.

```
extends CharacterBody3D


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


var movement : Vector3
var direction : Vector3
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
#	movement = Vector3.ZERO
	if Input.is_key_pressed(KEY_SPACE):
		pass
	
	if Input.is_key_pressed(KEY_W):
		direction +=
	
	linear_velocity = movement
	up_direction = Vector3.UP
	move_and_slide()
	movement = linear_velocity
	pass
```

### Steps to reproduce

Attach that script above to any CharacterBody3D node.
Press save.
Engine crashes without any errors.

### Minimal reproduction project

[GodotScriptCrashPlusEqual.zip](https://github.com/godotengine/godot/files/6905606/GodotScriptCrashPlusEqual.zip)

**Comment by timothyqiu** [comment] 2021-07-30 12:49
I think this is a duplicate of #49628.

**Comment by akien-mga** [comment] 2021-07-30 12:53
Indeed, that looks quite similar. Closing as duplicate of #49628.

**Closed by akien-mga** 2021-07-30 12:53 UTC
Labels: bug, crash, topic:gdscript
