### ISSUE TITLE
Keyword is causing wrong error reporting in GDScript

### ISSUE THREAD

**Issue by palmerjw** [godotengine/godot#73902] opened 2023-02-25 02:20 UTC
### Godot version

4.0RC3 onwards

### System information

Linux

### Issue description

They keyword is causes incorrect error reporting in GDScript. From what I can tell it does this in two separate instances. 
1. When an object is instantiated in the is if statement a error is rasied about using callable
`if assignment is NodeTypes.new().NodeTypeDictionary[wantedTypes]:`
error : Cannot call on an expression. Use call if its a Callable.

2. When a for loop is used to collect types to be used in the is if statement a error is raised about the current index to be out of scope.

var keys = NODE_TYPE_DICTIONARY.keys()
	for key in keys:
		if doc is key:
error : Could not fine 'key' in current scope.

### Steps to reproduce

1. Create a class named script. 
2. create a dictionary that uses that class name as a key
3. try to create an if x is statement using a for loop of the dictionary using its keys
4. Try to instantiate a object the holds the dictionary in a if x is statement

### Minimal reproduction project

[bugBaybee.zip](https://github.com/godotengine/godot/files/10830079/bugBaybee.zip)

**Comment by dalexeev** [comment] 2023-02-25 11:26
Use new `is_instance_of()` function instead. The right operand of the `is` operator now must be a constant type specifier, not a variable expression.

**Comment by akien-mga** [comment] 2023-02-25 11:36
Duplicate of #73663

**Closed by akien-mga** 2023-02-25 11:36 UTC
Labels: bug, topic:gdscript
