### ISSUE TITLE
OpenGL: _shadow_atlas_find_shadow: Condition "!sli" is true. Continuing.

### ISSUE THREAD

**Issue by salciunas** [godotengine/godot#84747] opened 2023-11-11 11:36 UTC
### Godot version

4.2 beta 5

### System information

Godot v4.2.beta5 - Linux Mint 21.2 (Victoria) - X11 - GLES3 (Compatibility) - GeForce GT 525M (nvidia; 390.157) - Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 Threads)

### Issue description

Getting error when using Shadows in SpotLight3D:

E 0:00:55:0236   _shadow_atlas_find_shadow: Condition "!sli" is true. Continuing.
  <C++ Source>   drivers/gles3/storage/light_storage.cpp:954 @ _shadow_atlas_find_shadow()

### Steps to reproduce

![Screenshot from 2023-11-11 13-28-48](https://github.com/godotengine/godot/assets/98655671/c81110f3-a78a-4c87-9800-85045fd62a77)

### Minimal reproduction project

https://we.tl/t-FpjcvyZYws

**Comment by Calinou** [comment] 2023-11-12 12:12
I can't reproduce this on 4.2.beta da0b1eb12 in a scene that has DirectionalLight3D, OmniLight3D and SpotLight3D with shadows enabled when using the Compatibility rendering method (Linux, GeForce RTX 4090 with NVIDIA 535.113.01).

Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by salciunas** [comment] 2023-11-13 07:31
While preparing the project, I found out that I was getting this error when restarting or going to the next level. Additionally, I was getting this error multiplied in the full project. In a prepared project, it appears a few times. Here is the project source (pressing r, n, and b will show up as errors). https://we.tl/t-FpjcvyZYws

**Comment by akien-mga** [comment] 2023-11-14 22:56
I can confirm the issue with the MRP. On my system (Linux, AMD Radeon Vega M), pressing "R" repeatedly to reload the scene eventually triggers the error. I can reload the scene 4 times without error, the 5th and following times each print the error message 4 times.

Here's the MRP uploaded directly to GitHub after removing the `.godot` folder, so it's much smaller:
[shadow_error.zip](https://github.com/godotengine/godot/files/13358098/shadow_error.zip)

**Comment by bypell** [comment] 2024-01-15 02:31
getting the same error in 4.2.1, as soon as a light is set to cast shadows, the error gets spammed in the console

**Comment by Gh0stGames** [comment] 2024-01-21 07:09
This issue also happens on Windows, can confirm the specific bug is using shadows on a spot light with Compatibility renderer. I wish the Engine would say that it doesn't work with Compatibility mode if that's the case though. 
![image](https://github.com/godotengine/godot/assets/7908464/6649323c-0649-4b51-92a9-007cb3de4f7d)

**Comment by Calinou** [comment] 2024-01-24 19:41
> I wish the Engine would say that it doesn't work with Compatibility mode if that's the case though.

All light/shadow types are intended to work when using the Compatibility rendering method. That's why there's no note about this in the documentation (or node configuration warnings) :slightly_smiling_face: 

We generally don't list known issues in the documentation as these notes have a tendency to be quickly outdated, unless we are certain the known issue will remain relevant for years.

**Comment by RNT-Hank** [comment] 2024-01-26 16:33
Howdy all, long time lurker first time poster.  Confirming Compatibility mode and Spotlight3D shadows.

Janky "workaround" that I've been using:  Zoom away from the scene in all viewports.  Errors stop.  Compile/run game.  No errors when playing.  

![image](https://github.com/godotengine/godot/assets/157826198/36b77205-edfe-4908-b5ad-7e1751c47ee6)

![image](https://github.com/godotengine/godot/assets/157826198/6d714b1a-ad6f-4e5b-bef6-adf6e0bf27e1)

**Comment by Santynolo** [comment] 2024-02-08 14:40
Any idea if this has been fixed in Godot 4.3 dev 3? i have been having the same issues.

**Comment by nuclear** [comment] 2024-02-12 00:50
Im running into the same issue. It can be easily replicated with the following.

- Compability renderer.
- Create a spotlight3D and enable shadows.
- Create a PlayerChar with a Sprite3D. 
- Set the Alpha Cut to Opaque Pre-Pass (otherwise shadows dont even work).

**Comment by Calinou** [comment] 2024-02-12 19:31
> Any idea if this has been fixed in Godot 4.3 dev 3? 

Not that I know of.

> I am also using compatibility backend, with an Intel HD Graphics 4600.

On slow integrated graphics like Haswell IGPs, you probably want to minimize the use of real-time shadows to maximize performance :slightly_smiling_face:

**Closed** 2024-04-05 10:26 UTC
Labels: bug, topic:rendering, confirmed, topic:3d

**Comment by DarioDaF** [comment] 2024-04-09 15:17
Can reproduce on Godot v.4.3.dev5.official [89f70e98d]:
Compatibility mode.
Spotlight with shadow enabled only when the view angle is facing the same Y side as the spotlight and being relatively near the light.
It seems to not care about any other object actually affecting the shadow (error even when no object is visible).
Aspect ratio of the view seems to affect it, thin and long views requre the camera to be much nearer to the light.

![image](https://github.com/godotengine/godot/assets/10617344/16c4ba3e-b7a6-4cb5-894a-96491da3aec4)

Test scene (it's not really "minimal", but pretty close to it):
[TestWeb.zip](https://github.com/godotengine/godot/files/14920514/TestWeb.zip)

**Comment by akien-mga** [comment] 2024-04-09 15:20
@DarioDaF This was fixed 4 days ago, which is after the 4.3-dev5 release. Please test with 4.3-dev6 when it's released :)

**Comment by DarioDaF** [comment] 2024-04-09 15:22
Makes sense sorry I was confused by the cherry pick for 4.2.* and thought it was a regression without checking the date

**Comment by AThousandShips** [comment] 2024-04-29 16:58
Please open a new issue report, as it's a new issue

**Comment by Calinou** [comment] 2024-04-29 21:55
The issue is likely the same as https://github.com/godotengine/godot/issues/71929.
