### ISSUE TITLE
Seg fault with lavapipe (Recorded)

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#59623] opened 2022-03-28 08:23 UTC
### Godot version

4.0 (every alpha version upto ~~5th~~ 10th)

### System information

Linux Mint, GeForce 9500 GS/PCIe/SSE2

### Issue description

i use lavapipe (which uses cpu) because my gpu doesn't support vulkan.
the **seg fault** happens at two different positions in order
1. The godot **seg faults** on creating a new project when the project manager is opened for **The very first time**.
2. And on opening it again it now continues to **seg fault** on splash screen whenever its opened.

The same happened on my laptop. And now i recorded it on my computer to confirm(both using lavapipe)

https://user-images.githubusercontent.com/77773850/160355975-c45b8388-b86b-4ccb-ac04-f9ce4847c1f8.mp4

### Steps to reproduce

1. Use lavapipe
2. ~~Have never opened Godot **4** on your computer before~~ (EDIT: There should be no `~/.config/godot/editor_settings-4.tres` when wou open Godot 4)
3. open for the first time the seg faults on project creation
4. open 2nd,3rd... time. It seg faults on splash (Edit: while `~/.config/godot/editor_settings-4.tres` is present)

### Minimal reproduction project

(None)

**Comment by akien-mga** [comment] 2022-03-28 08:28
What Linux Mint and Mesa versions do you have?

Works fine for me with Mesa 22.0.0 built against LLVM 13.0.1 on Mageia 9.

**Comment by Variable-ind** [comment] 2022-03-28 08:32
Linux Mint 20.3
how do i check the mesa version?

**Comment by Variable-ind** [comment] 2022-03-28 08:35
And where is the data related to **Godot 4** stored? (i assume it's separate from Godot 3.4.4's data).
If i remove it the Godot may load up to project manager again :thinking:

**Comment by Variable-ind** [comment] 2022-03-28 08:40
And here's the project that was made when the "seg. fault" happened.
It may help trace in which phase of project creation did the seg fault happen (cause i noticed it didn't have a default environment)
[New Game Project.zip](https://github.com/godotengine/godot/files/8361069/New.Game.Project.zip)

**Comment by akien-mga** [comment] 2022-03-28 08:47
> Linux Mint 20.3 how do i check the mesa version?

Possibly with something like `dpkg -s mesa-vulkan-drivers` (or any other Mesa subpackage).

Given that Linux Mint 20.3 is based on Ubuntu 20.04 I assume you have Mesa 21.2.6:
https://packages.ubuntu.com/focal-updates/mesa-vulkan-drivers

Lavapipe is still experimental so it was maybe improved in version 22.0.0 which I have.

> And where is the data related to Godot 4 stored? (i assume it's separate from Godot 3.4.4's data).

Same as Godot 3.4.4, i.e. `~/.local/share/godot` and `~/.config/godot`. The editor settings are separate though (`~/.config/godot/editor_settings-3.tres` and `~/.config/godot/editor_settings-4.tres` for Godot 3 and 4 repectively). You could try to delete `~/.local/share/godot/shader_cache` but I doubt it will make much difference).

**Comment by Variable-ind** [comment] 2022-03-28 08:50
here's the mesa
![Screenshot from 2022-03-28 13-49-50](https://user-images.githubusercontent.com/77773850/160361764-4f66c434-f78c-4719-9719-333672cd6ab2.png)

**Comment by Variable-ind** [comment] 2022-03-28 08:54
@[akien-mga](https://github.com/akien-mga) i deleted the `~/.config/godot/editor_settings-4.tres` and it started project manager (But it seg faulted again on creating new project / or clicking **Browse**)

**Comment by Zireael07** [comment] 2022-03-28 11:56
I think there is a second report on segfaulting on clicking Browse

**Comment by Calinou** [comment] 2022-03-28 12:42
Does it work if you start Godot with the `--single-window` command line argument? This should fix crashes related to multi-window usage.

Note that this CLI argument is not automatically passed from the project manager to the editor, so you have to open the editor manually with the `--single-window` [command line argument](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html).

**Comment by Variable-ind** [comment] 2022-03-28 14:12
> Does it work if you start Godot with the `--single-window` command line argument? This should avoid crashes related to multi-window usage.
> 
> Note that this CLI argument is not automatically passed from the project manager to the editor, so you have to open the editor manually with the `--single-window` [command line argument](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html).

All the Crashes still happen at their respective places

**Comment by Variable-ind** [comment] 2022-05-10 10:34
just came back here to tell that this still happens with alpha 7

**Comment by Variable-ind** [comment] 2022-05-22 07:56
I tried it on alpha 8 and there is an additional message appearing now (maybe because of updates of mesa... *I don't know...*)
this is when i click the about button (without `--single-window`)
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha8.official (cc3ed63af68ea9262bf8015d34aa6dd6327112e8)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f6743991090] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```
and this is **with** `--single-window ` (*i noticed a different hex value instead of `[0x7f6743991090]` in this case*)
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha8.official (cc3ed63af68ea9262bf8015d34aa6dd6327112e8)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f7db48bc090] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

**Comment by Calinou** [comment] 2022-10-12 22:52
Duplicate of https://github.com/godotengine/godot/issues/38428.

**Closed by Calinou** 2022-10-12 22:52 UTC
Labels: bug, platform:linuxbsd, topic:rendering, topic:thirdparty
