### ISSUE TITLE
Can't interact with scrollable tooltips in Single Window mode

### ISSUE THREAD

**Issue by Dancovich** [godotengine/godot#97192] opened 2024-09-19 17:02 UTC
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Windows 11, Intel Core i5 10300H, nVidia GTX 1650

### Issue description

In Single Window Mode, tooltips with long texts that need scrolling to access the whole content can't be scrolled. The scroll wheel will instead interact with the editor as if the tooltip wasn't there (viewport will zoom in or out, inspector window will scroll, etc).

### Steps to reproduce

- Create a new project
- Enable Single Window Mode in Editor settings
- Hover the mouse cursor on any UI element that has a long text for tooltip. Example: Tonemap mode of the Sky background type in Environment resources.

![image](https://github.com/user-attachments/assets/f776136d-004a-47dd-a5ec-cbd800a8e19f)

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment] 2024-09-19 18:12
- related https://github.com/godotengine/godot/pull/93967

**Comment by matheusmdx** [comment] 2024-09-19 19:42
This is a duplicate of #92545

**Closed** 2024-09-20 08:01 UTC
Labels: bug, topic:gui
