### ISSUE TITLE
Dragging image into resources folder causes load error and crash

### ISSUE THREAD

**Issue by maranr** [godotengine/godot#57157] opened 2022-01-24 22:07 UTC
### Godot version

4.0 Alpha 1

### System information

Windows 10

### Issue description

Dragging an image file into the resources folder causes a load error and Godot 4 to crash. Upon re-opening the project, the image is in the resources folder. 

![drag_image_godot4](https://user-images.githubusercontent.com/31901090/150872999-0eb9747b-6caf-46ee-b835-9fdb012bb845.png)
 

### Steps to reproduce

Drag image into resources folder.

**Comment by Ev01** [comment] 2022-01-30 05:50
Can confirm this on master and 4.0 alpha 1 using windows 10. I get this error in the console:
```
ERROR: Task 'reimport' already exists.
   at: (editor\progress_dialog.cpp:159)
```

**Comment by Calinou** [comment] 2022-01-30 21:32
Duplicate of https://github.com/godotengine/godot/issues/53871.

**Closed by Calinou** 2022-01-30 21:32 UTC
Labels: bug, topic:editor, confirmed, crash, regression
