### ISSUE TITLE
PacketPeer error.

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#28956] opened 2019-05-17 08:43 UTC
**Godot version:**

v3.1.stable.official

**OS/device including version:**

Windows 10 Pro.

**Issue description:**

I am starting a TCP_server with Godot and when i try to connect from another program ( not godot ) connection is successfull but when godot is trying to read for pakcets the console keeps getting spammed with this error:
E 0:00:03:0099   Condition ' remaining < 4 ' is true. returned: ERR_UNAVAILABLE
  <C Source>     core/io/packet_peer.cpp:220 @ get_packet()
  <Stack Trace>  server.gd:38 @ _process()

EDIT: Doing the following helps me avoid the error"
var packetCount = peer.get_available_packet_count()
if packetCount > 0: ...
But packetCount is always 0 for some reason, even if I send a message to the server.

**Steps to reproduce:**
peer.get_available_packet_count()
var data_received = peer.get_packet()

"var data_received = perr.get_packet()" gives the error. This also happens if i change get_packet() to get_var().

**Minimal reproduction project:**

[Multiplayer Test.zip](https://github.com/godotengine/godot/files/3190634/Multiplayer.Test.zip)

**Comment by Calinou** [comment] 2019-05-17 13:23
PacketPeer is typically used for UDP communication (unless you use PacketPeerStream, which uses the same protocol over TCP).

**Comment by Faless** [comment] 2019-06-19 13:51
> when i try to connect from another program ( not godot )

As [stated in docs](https://docs.godotengine.org/en/latest/classes/class_packetpeerstream.html#description) `PacketPeerStream` **implements a custom protocol** so it won't work if you don't **respect it** when sending data from an external application.

The reproduction project does not include the external client app, and the godot client is not running/broken.

Closing, as this work as expected.

**Closed by Faless** 2019-06-19 13:51 UTC
Labels: bug, topic:network

**Comment by Faless** [comment] 2019-06-19 13:55
@zaksnet I might suggest using other [community channels](https://godotengine.org/community) like Q&A, the discord channel, facebook group, or the IRC channel before opening an issue in the future to save time.

**Comment by Faless** [comment] 2019-06-19 14:46
> I understand that, but what is to respect? Should I include a custom prefix? Custom suffix? Should I include the packet length? That is not included in the documentation.

I see, I think it was not documented on purpose (like the RPC/RSET protocol), because it was originally meant for Godot-to-Godot communication and not as a stable exposed API.

Given that one is not likely to change though, feel free to open another issue asking for documentation, or a PR supplying it.
