### ISSUE TITLE
typing ">" or "<" cycles active scripts in editor

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9149] opened 2017-06-13 10:04 UTC
Arch Linux, Godot 3.0 master, German keyboard layout(qwertz)

If there are multiple scripts (or help windows) opened, whenever I type ">" or "<" the script editor changes to the next or previous script after typing the actual character, which is really annoying. This is probably due to conflicting keybindings, but I haven't changed any of the default bindings myself.

Cycling through scripts with a shortcut seems to be intended. However, "<" and ">" are not a good choice, because they are often used while coding.

steps to reproduce:
1. open a script
2. open another script
3. try to type ">" or "<" in any of them

**Comment by novemberist** [comment] 2017-06-13 15:42
Am I really the only one with this issue? Maybe it's really a problem on my end somewhere. Here's a gif in case my description wasn't clear:  
![godot_script_editor](https://user-images.githubusercontent.com/7927471/27091167-a7a8f1ac-505f-11e7-88b2-2398a934456b.gif)

**Comment by nunodonato** [comment] 2017-06-13 16:05
it happened to me too, maybe some recent commit did it?
Anyway, I disabled those shortcuts in the editor settings and now its fine :)

**Comment by novemberist** [comment] 2017-06-13 16:14
Certainly not the best choice as a default shortcut. I have disabled them for now, too. Didn't think of this earlier because confusingly, the shortcut settings don't show the current bindings (only "None" or nothing, which might also be a bug?) so I assumed it wasn't bound there but somehow hardcoded.

**Comment by bojidar-bg** [comment] 2017-06-13 17:57
This issue is a product of #5419, on which no one thought they would create problems (since all that commented seem to have been QWERTY users).
Can you suggest better shortcuts?

**Comment by Zireael07** [comment] 2017-06-13 18:04
If it's related to user's keyboard layout, is @nunodonato also not a qwerty user?

Can Godot somehow detect the user's layout? Keeping the shortcut on QWERTY (EN, PL are both unaffected, I'm not sure about ES and AR) but disabling it on DE (and any others :P)...

**Comment by nunodonato** [comment] 2017-06-13 18:18
yes, qwerty here

**Comment by Hinsbart** [comment] 2017-06-13 21:48
Well, the shortcuts are "ctrl + <" and "ctrl + >" which is fine IMO.
The problem is that it ignores the modifiers [here](https://github.com/godotengine/godot/blob/master/core/os/input_event.cpp#L288) when the event isn't pressed (and the script editor explicitly ignores pressed events [here](https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp#L1834).
The workaround would be simple, but I'd prefer to fix the action matching logic instead.

**Comment by novemberist** [comment] 2017-06-13 23:17
@bojidar-bg this pr was merged almost a year ago, but the shortcut only started causing problems a couple of days back. i've been using godot3 for some time now and never had any issues before and wasn't even aware of this shortcut.

**Comment by vicguedez** [comment] 2017-06-14 15:28
QWERTY/ES, Debian 9 user here, same issue.

**Comment by novemberist** [comment] 2017-06-14 22:39
@Hinsbart there's definitely some issue with the modifier keys. ctrl+shift+f11 now enables distraction free mode  + fullscreen (which should only be enabled by shift+f11) at the same time

**Comment by reduz** [comment] 2017-06-22 22:59
This might be fixed now, please test!

**Comment by quinnyo** [comment] 2017-06-23 01:29
Fixed for me!

**Closed** 2017-06-23 01:40 UTC
