### ISSUE TITLE
Cannot click meshes in instanced scenes when they are under a spatial node 

### ISSUE THREAD

**Issue by mcanders** [godotengine/godot#4099] opened 2016-03-19 19:01 UTC
**Operating system or device:**
Arch Linux

**Issue description** (what happened, and what was expected):
Meshes in instanced scenes cannot be click-selected when they are beneath a spatial node.  This is especially problematic because Godot's blender/collada export/import results in imported meshes being beneath a spatial node.

I would expect to be able to click instanced objects to select them.

**Steps to reproduce:**
1. Create a new scene with a spatial node at the root (Scene 1)
2. Create another scene with a spatial node at the root (Scene 2)
3. Add a mesh beneath "Scene 2"
4. Create an instance of "Scene2" within "Scene 1"
5. Try to select the instanced scene by clicking on the mesh

**Link to minimal example project** (optional but very welcome):
[UnclickableInstance.zip](https://github.com/godotengine/godot/files/180969/UnclickableInstance.zip)

**Comment by akien-mga** [comment] 2017-01-02 13:53
Is this a duplicate of #2852 (or the other way around, depending on which issue is the clearer about the bug :))

**Comment by mcanders** [comment] 2017-01-02 20:58
They do appear to be duplicates.  Feel free to close this one if you want to.

**Closed** 2017-01-02 21:00 UTC
Labels: bug, topic:editor, usability
