### ISSUE TITLE
[3.0] Setting negative x scale on a node with a skeleton/big hierarchy flips scale every frame.

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11205] opened 2017-09-12 20:26 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win7 x64, Godot 3.0

**Issue description:**

scale = Vector2(-1, 1) flips my character every frame, alternating between 1 and -1, and it happens on the Y axis.
Using set_scale(-1, 1) does the same but on the X axis.

**Steps to reproduce:**
Open example project I attached, open Stork.tscn and run that scene, check the script on the root node.

**Link to minimal example project:**

[Stork 2, scale glitch.zip](https://github.com/godotengine/godot/files/1297317/Stork.2.scale.glitch.zip)

**Comment by Boothand** [comment] 2017-09-12 20:31
Seems to be because move() is called as well. Duplicate of https://github.com/godotengine/godot/issues/5929

Still a bit of an issue, since flipping sprites isn't going to be very manageable with a skeleton hierarchy like this? Also, scale = Vector(1, -1) has expected results, just not on the X axis.

**Comment by letheed** [comment] 2017-09-14 11:14
[Related](https://www.reddit.com/r/godot/comments/6zq588/flipping_an_object_horizontally/)

**Comment by bojidar-bg** [comment] 2018-05-22 16:43
I'm going to close this as a duplicate of #12335 since the latter has more activity. If it is not a duplicate, feel free to comment here and we will reopen it.

As a workaround for the mentioned problem, try putting the whole visual hierarchy inside a Node2D inside the KinematicBody2D. That way, you can have separate visual and physics scale.

**Closed by bojidar-bg** 2018-05-22 16:43 UTC
Labels: bug, topic:core
