### ISSUE TITLE
Godot editor does not work with El Capitan dual full screen feature

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3337] opened 2016-01-13 13:04 UTC
El Capitan (latest OSX) features a custom full screen feature where you can run two applications at the same time in a split split full screen mode.

Godot Editor does not support this because it does or cannot reorganize the UI dynamically . All the components and the layout is fixed and stiff. It should squish itself as much as possible create a horizontally thinner more compact look instead. 

![screen shot 2016-01-13 at 8 01 41 am](https://cloud.githubusercontent.com/assets/6987027/12294956/02bcaaf6-b9cc-11e5-9450-20faf0e4e889.png)

**Comment by reduz** [comment] 2016-01-13 13:28
I'm out of OSX so, any contribution welcome

**Comment by bojidar-bg** [comment] 2016-01-13 14:12
Does the issue occur when you just squash the window manually? (e.g. no fullscreen, etc.)

**Comment by trollworkout** [comment] 2016-01-13 14:15
@bojidar-bg Yes . 

![screen shot 2016-01-13 at 9 15 03 am](https://cloud.githubusercontent.com/assets/6987027/12296512/23df35f0-b9d6-11e5-8be8-23b01608d5b0.png)

**Comment by reduz** [comment] 2016-01-13 14:17
I guess Godot Window does not like being squashed that much :)

**Comment by bojidar-bg** [comment] 2016-01-13 14:19
@trollworkout hm.... that's strange. I can't reproduce it this way under linux, unless I go to sub-768 px size (e.g. when top row buttons start overlapping)

Maybe you can somehow try on a more recent commit?

@trollworkout ~ Also, is this only on very squashed window sizes, or on all sizes smaller than the initial? (also, is it reproducible in the other direction?)

**Comment by trollworkout** [comment] 2016-01-13 14:21
@reduz I guess not :)  

@bojidar-bg 
I can try a new commit but I think from my knowledge I am running the latest OSX one available unless I have to build my own TT_TT

Also looking closer at the screen it seems there is a graphical glitch as well. All the way at the top of the window there is a 20 pixel or so band  of gray space before the engine interface is laid out.

**Comment by akien-mga** [comment] 2016-01-13 14:27
> Also looking closer at the screen it seems there is a graphical glitch as well. All the way at the top of the window there is a 20 pixel or so band of gray space before the engine interface is laid out.

That's fixed in master. I guess you'll have to try building the engine yourself ;) It's relatively easy on Linux and Windows, so I'd expect it to be fine on OSX too.

**Comment by neikeq** [comment] 2016-01-13 14:27
Can't reproduce on linux either. This is the minimum size without this behaviour:
![captura de pantalla de 2016-01-13 15 25 54](https://cloud.githubusercontent.com/assets/7718100/12296776/0e186f82-ba0a-11e5-9e65-da43af6168df.png)

**Comment by trollworkout** [comment] 2016-01-13 14:42
@akien-mga  I will wait around for a more fresh build or see if I can build one myself before trying again. Is not imperative that I have this feature although would be quite handy in doing two things at the same time :)  I like to watch movies or gameplays while I do work

**Comment by trollworkout** [comment] 2016-01-13 14:44
I wish I was on linux so much easier to compile and most apps are always fresh . Macs tend to lag behind kinda bothering me right now.

**Comment by trollworkout** [comment] 2016-01-14 10:44
Guys please keep this open until I get the newest possible version running somehow. It may actually be fixed . I have to figure out how to do that first.

**Comment by purpleorangegames** [comment] 2016-01-14 18:32
@trollworkout try one of the builds I have: http://purpleorangegames.com/godot/
You might need to chmod +x on the one you download. Let me know if you need any help.

Directly link for 64 bits build:
http://purpleorangegames.com/godot/godot.osx.opt.tools.64
```
cd Downloads
sudo chmod +x godot.osx.opt.tools.64
./godot.osx.opt.tools.64
```

**Comment by trollworkout** [comment] 2016-01-14 18:42
I am worry to have wasted ur time guys TT_TT This bug has been fixed in the latest build but was not available for download on OSX so I was behind.
![screen shot 2016-01-14 at 1 42 22 pm](https://cloud.githubusercontent.com/assets/6987027/12333857/a83af3b8-bac4-11e5-87c7-747fa8f29723.png)

**Comment by trollworkout** [comment] 2016-01-14 18:43
@purpleorangegames  works perfect thank you. I have not only did what you said but also replaced the Godot executable inside the app bundle with the one you gave me 64 bit opt osx . Works fine!

**Comment by bojidar-bg** [comment] 2016-01-14 18:43
@trollworkout If it is fixed, close it.

**Comment by trollworkout** [comment] 2016-01-14 18:44
@bojidar-bg  I closed it is fixed

![screen shot 2016-01-14 at 1 44 01 pm](https://cloud.githubusercontent.com/assets/6987027/12333908/f41dcddc-bac4-11e5-8fc5-7077e1184699.png)

**Closed** 2016-01-14 18:44 UTC
Labels: enhancement, platform:osx, topic:editor
