### ISSUE TITLE
Can't edit new Texture resources from Item List Editor

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18246] opened 2018-04-17 02:52 UTC
**Godot version:**

3.0.2 stable
(also e7445c3)

**OS/device including version:**

Windows 10

**Issue description:**

I was attempting to create a simple flat color icon from a GradientTexture for an item inside an OptionButton.  This *appears* to create the resource, but it can't be edited in place from the item list editor.  Attempting to click the cell does nothing, and although you can still right-click the cell and the popup appears with the proper context for its contents, selecting Edit will still do nothing.

**Comment by KoBeWi** [comment] 2019-04-29 23:45
I tried creating texture from here:
![image](https://user-images.githubusercontent.com/2223172/56933736-5a837680-6ae9-11e9-97bc-20839274680e.png)
Unless that's not what OP describes, it works and is editable both in 3.0.6 and 3.1. The problem is that the texture isn't saved and vanishes when you change selected item.

**Comment by KoBeWi** [comment] 2020-07-09 08:32
Fixed in 3.2

**Closed by KoBeWi** 2020-07-09 08:32 UTC
Labels: bug, topic:editor
