### ISSUE TITLE
Can't compile for Android. fatal error: 'features.h' file not found

### ISSUE THREAD

**Issue by FlightBlaze** [godotengine/godot#45002] opened 2021-01-07 23:14 UTC
I'm trying to build Godot for Android 

[https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html](url)

**PS C:\Users\blaze\godot> scons platform=android target=release_debug android_arch=armv7**
```
scons: Reading SConscript files ...
Building for Android (armv7) (with NEON)
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  3%] Compiling shared ==> platform\android\os_android.cpp
=====
b"In file included from platform\\android\\os_android.cpp:31:\r\nIn file included from platform\\android/os_android.h:34:\r\nIn file included from platform\\android/audio_driver_jandroid.h:34:\r\nIn file included from
.\\servers/audio_server.h:34:\r\nIn file included from .\\core/math/audio_frame.h:34:\r\nIn file included from .\\core/math/vector2.h:34:\r\nIn file included from .\\core/math/math_funcs.h:35:\r\nIn file included from .\\core/math/random_pcg.h:34:\r\nIn file included from 
C:\\Users\\blaze\\AppData\\Local\\Android\\Sdk\\ndk\\22.0.7026061/sources/cxx-stl/llvm-libc++/include\\math.h:294:\r\nC:\\Users\\blaze\\AppData\\Local\\Android\\Sdk\\ndk\\22.0.7026061/sources/cxx-stl/llvm-
libc++/include\\__config:218:12: fatal error: 'features.h' file not found\r\n#  include <features.h>\r\n           ^~~~~~~~~~~~\r\n1 error generated.\r\n"
=====
scons: *** [platform\android\os_android.os] Error 1
scons: building terminated because of errors.
```

My environment variables
- ANDROID_HOME = C:\Users\blaze\AppData\Local\Android\Sdk
- ANDROID_NDK_HOME = C:\Users\blaze\AppData\Local\Android\Sdk\ndk\22.0.7026061
- ANDROID_NDK_ROOT = C:\Users\blaze\AppData\Local\Android\Sdk\ndk\22.0.7026061

**Comment by akien-mga** [comment] 2021-01-08 06:59
Duplicate of #44055, NDK r22 is not supported yet. We advise using r21.3 for now.

**Closed by akien-mga** 2021-01-08 06:59 UTC
Labels: platform:android, topic:buildsystem
