### ISSUE TITLE
[4.1] Change Node Type Window exceeds screen height

### ISSUE THREAD

**Issue by Structed** [godotengine/godot#78534] opened 2023-06-21 19:21 UTC
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Windows 11 22H2

### Issue description

When trying to change a node type, the window to do that exceeds the height bounds and is not fully displayed.

I would expect to see the full Window as well as an `OK` and a `Cancel` button.

This issue does **NOT** appear in 4.0.3

![image](https://github.com/godotengine/godot/assets/29922/6f6df252-54a4-47d4-a5a2-58d6bb065157)

### Steps to reproduce

1. Create a new project
2. Choose a root node type
3. Right-click the root node
4. Click "Change Type"
5. The Window opens and exceeds screen height bounds and it's content is not fully visible

### Minimal reproduction project

N/A

**Comment by theraot** [comment] 2023-06-21 20:09
I can confirm. The issue was already present in v4.1.dev1.official [db1302637]

**Comment by akien-mga** [comment] 2023-06-21 20:22
CC @KoBeWi @YuriSizov

**Comment by KoBeWi** [comment] 2023-06-21 20:56
Duplicate of #77785

**Closed by KoBeWi** 2023-06-21 20:56 UTC
Labels: bug, topic:editor, regression
