### ISSUE TITLE
The array is not initialized again within a function

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#27904] opened 2019-04-10 18:03 UTC
Hello

**Godot version:**
Godot 3.1 stable

**Issue description:**
Is a bug??

```
extends Node2D

func _ready():
	print("It's ok: ", array_func())
	print("O_o! : ", array_func())
	
func array_func():
	var arr : Array
	
	arr.append("foo")
	arr.append("var")
	
	return arr
```

Output:
```
It's ok: [foo, var]
O_o! : [foo, var, foo, var]
```

**Minimal reproduction project:**
[ArrayBug?.zip](https://github.com/godotengine/godot/files/3065151/ArrayBug.zip)

**Comment by DeybisMelendez** [comment] 2019-04-10 18:45
No creo que sea un bug Matías, al hacer print en la función `array_func()` creas una variable local `arr` que seguramente se libera en el siguiente frame. Pero como tu tienes dos veces el print, entonces añade 2 veces el `foo` y el `var`. Ya probaste añadiendo: `arr.clear()` al inicio de la funcion?

----------

I do not think it's a Matías bug, when you print in the function `array_func ()` you create a local variable `arr` that will surely be removed in the next frame. But since you have twice the print, then add 2 times the `foo` and the` var`. Have you already tried adding: `arr.clear ()` at the start of the function?

**Comment by MatiasVME** [comment] 2019-04-10 18:50
I think "var arr : Array" should create a new reference. It is being declared.

Also "var arr := []" works well.

**Comment by timoschwarzer** [comment] 2019-04-10 18:55
This is very likely a bug. But I don't know which of these two aspects should be considered a bug:

1. Declaring a variable without assigning a value shouldn't be allowed (`var arr: Array` should be null IMO)

or

2. The type-inferred initial value isn't correctly set on variable declaration. (`var arr: Array` should be interpreted as `var arr: Array = []`)

**Comment by MidZik** [comment] 2019-04-10 20:26
Duplicate of #24134.

Known issue. You should always give your variables an initial value anyway, though.

**Closed** 2019-04-11 06:58 UTC
