### ISSUE TITLE
"Lookup Symbol" fail to jump to local functions defined after the current line

### ISSUE THREAD

**Issue by x2f** [godotengine/godot#29697] opened 2019-06-11 22:20 UTC
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
Main issue:
Control-left-click on a local function call jumps to the function definition if it is defined before the current line in the file. If it is defined after the current line, nothing happens. "Lookup symbol" appears in the popup contextual menu when control-left-click works, and it does not appears in the other case.

Secondary issue: even when control-click works, selecting "lookup symbol" in the contextual menu does not work, which seems to be #27135.

**Steps to reproduce:**

Control-click on a function defined below, then cut-and-paste the function above and retry control-click.

**Comment by KoBeWi** [comment] 2019-06-12 00:43
Duplicate of #20393

**Closed by KoBeWi** 2019-06-12 00:43 UTC
