### ISSUE TITLE
POSSIBLY a small bug in Visual script ' standard ' empty values ' descriptor ' . .? ? :))

### ISSUE THREAD

**Issue by jasperbrooks79** [godotengine/godot#38411] opened 2020-05-02 10:29 UTC
Godot 3.2, Windows 10 . .

Copied from the proposal page, where wrote it, said it should be here, not in proposals, but for bugs . . . Sorry, if wrong place, hope it's correct . . . .

Describe the project you are working on:

A bunch of stuff, a Tomb Raider style game <3 Also, a ' new ' Batman project, like Brightburn . . .

Describe the problem or limitation you are having in your project:
Often, when I drag certain boxes in, in visual scripting, the box has a ' value ', like for an ACTION node, it says on the new box, ' ui_accept ', or something, but it doesn't work, when I press test, it returns NULL, when debugged, with print . . . It happens because some of the boxes I have used, sort of ' LOOK ' like they have a value, but they don't, I think it also happens when dragging a new variable in, without setting it in the dock, one makes them . . . It says ' FALSE ' for a bool, but it really returns NULL, a different value . . .

I know this is incredibly simple, but for BEGINNERS, like me, it's very confusing, because it LOOKS like the box has a value, but it doesn't work, it causes bugs, and it often takes time, to find those bugs and, it's always confusing . . . Is there ANY way, when you put a box or, a variable in, that you can somehow write ' Not set ' or, ' Undefined ', instead of a misleading value, so new users can SEE which boxes are working, and not working, I think when moving a ACTION box in ( for getting keyboard inputs, I use it ), that it has a value, like ui_accept, or if I write a new input name, like PlayerJump in settings, it LOOKS like it ' has ' that value, but during testing, it's not been assigned, it's really ' Empty ' . . . Maybe one could sort of do that, so new boxes show exactly what's inside of them, which might be ' Not set ', ' Empty ', or even ' Null ', ANYTHING that lets a person know, that RIGHT now, Godot has ' made ' a box, with a ' Null ' or, ' Empty ' value, NULL would probably be best, because that's what is printed, in the debugger, when the nodes are like that, very confusing . . .

Describe the feature / enhancement and how it helps to overcome the problem or limitation:
Well, it's a small change to visual scripting, to make it nicer, for beginners . . . I OFTEN make an action button, and then it looks like it works, has the value I want, by default, but it's really is a NULL value, or the button ( input ) doesn't work, I always have to go into ' settings ' for the button, open the list, and pick the right one, it would be nice if the boxes that causes the problem, we're made to look like, when they had no value, we're empty, that they we're ' Null ', ' Empty ', instead of appearing to work, but having no variable or, things in them, so they're ' Empty ' . . .

Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:
Well, it's really just so, that if a node has a ' NULL ' value, it writes NULL, instead of FALSE, TRUE, or other things, by default . . . It's confusing for beginners, please help . . .

If this enhancement will not be used often, can it be worked around with a few lines of script?:
As a visual scripter, I have enough trouble making my games work, making COMPLEX charts and, node trees is VERY demanding, I need as little problems, and for it to be WYSIWYG, as possible, in this case it's just confusing, for beginners . . . . IF something has a NULL, instead of a FALSE, or the input HASN'T been set, in the menu, for an action box, it could just write NULL, instead of falsely saying, it has PlayerJump, or so . . .

Is there a reason why this should be core and not an add-on in the asset library?:
Well, I'm not sure what this means, I'm new to Godot, very noob, I think this is so general, it needs to be in the engine, not some extra download, where it works <3 <3

**Comment by Calinou** [comment] 2020-05-02 22:30
Duplicate of #27611.

**Closed by Calinou** 2020-05-02 22:30 UTC
Labels: topic:visualscript
