### ISSUE TITLE
Input.is_action_just_pressed isn't working 

### ISSUE THREAD

**Issue by AmeerDev1** [godotengine/godot#80461] opened 2023-08-09 21:15 UTC
### Godot version

Android version 4.1.1

### System information

Android - Godot 4.1

### Issue description

I want to make buttons on the screen for a mobile game, for example i have action "jump" for jumping, (added it to the actions in input map and also in the TouchScreenButton too, but when i use Input.is_action_just_pressed i don't get any output at all, if saying that the button doesn't work? It does, Input.is_action_pressed works fine..... But i want 1output/click, and that's what Input.is_action_just_pressed does..... PLEASE HELP I'M LITERALLY SO TIRED... I'm giving up my project until this gets a fix or a solution 🥺🙏

### Steps to reproduce

 @[test_project.zip](https://github.com/godotengine/godot/files/12306958/test_project.zip)

### Minimal reproduction project

[test_project.zip](https://github.com/godotengine/godot/files/12306968/test_project.zip)
![IMG_20230810_000114](https://github.com/godotengine/godot/assets/141875501/9f2be7c0-8b81-444b-bf25-78041c9fa130)

**Comment by Sauermann** [comment] 2023-08-09 23:34
Thank you for the report. This is a known issue and already reported.
Consolidating as a duplicate of #66318.

**Closed** 2023-08-09 23:44 UTC
Labels: bug, archived, platform:android, topic:porting, topic:input
