### ISSUE TITLE
Exporting Node variable can't trigger setget in tool mode.

### ISSUE THREAD

**Issue by Hapenia-Lans** [godotengine/godot#69283] opened 2022-11-28 07:05 UTC
### Godot version

4.0 beta 6

### System information

This is system-independent.

### Issue description

As title. 

This is because when the exported node variable `a_variable` is modified, the editor actually modifies the variable `metadata/_ editor_prop_ptr_a_variable`, so the `setget` defined in the `@ tool` script does not work.

![image](https://user-images.githubusercontent.com/93276898/204214101-9838cda5-d6e1-4389-b5f9-a69c77b85cb4.png)

### Steps to reproduce

```gdscript
@tool
extends Node

@export var a_export_node: Node :
    set(v):
         print("set!")
         a_export_node = v
```

### Minimal reproduction project

very easy to reproduce.

**Comment by hoklai1997** [comment] 2023-01-02 02:53
Godot version
4.0 beta 10

This is still an issue with setget in tool mode. Tested with the following code:

```gdscript
@tool
extends Node2D

@export var foo: bool:
	set(value):
		print("foo setter invoked")
		foo = value
```

In-Editor toggle boolean: `Set foo`
Run Scene: `foo setter invoked`

**Comment by Hapenia-Lans** [comment] 2023-01-03 02:43
> Godot version 4.0 beta 10
> 
> This is still an issue with setget in tool mode. Tested with the following code:
> 
> ```gdscript
> @tool
> extends Node2D
> 
> @export var foo: bool:
> 	set(value):
> 		print("foo setter invoked")
> 		foo = value
> ```
> 
> In-Editor toggle boolean: `Set foo` Run Scene: `foo setter invoked`

Maybe it is another issue? This issue is focus on exporting variable that is `Node` type. And the problem is in editor metadata. Your code can work in previous version, at least the time when I report this.

**Comment by hoklai1997** [comment] 2023-01-03 04:55
I just double checked, the issue was in not reloading the scene to get the most current script behaviour. Closing the scene and reopening resolved the problem. :face_palm:

**Comment by Frontrider** [comment] 2023-04-15 11:08
Does not work. Exported nodes remain nulls in the editor as of 4.0.2.

**Comment by jdboris** [comment] 2023-06-24 08:22
To clarify, OP's bug is still happening in v4.0.3.stable.official. Setting primitive type values in the editor does trigger the setter, but setting `Node` type values doesn't. I still see `Set metadata/_editor_prop_ptr_value` in the Output. `NodePath` does work as a workaround though

**Comment by raulsntos** [comment] 2023-07-01 02:05
- I'm unable to reproduce in v4.1.rc1.mono.official [1f9e540f1].
- It seems this was fixed by https://github.com/godotengine/godot/pull/76389.
- Also, this issue seems to be a duplicate of https://github.com/godotengine/godot/issues/74141.

**Closed by raulsntos** 2023-07-01 02:05 UTC
Labels: bug, topic:editor
