### ISSUE TITLE
@export var seems to assign null values when in @tool mode

### ISSUE THREAD

**Issue by Epsilonraptor** [godotengine/godot#75657] opened 2023-04-04 19:20 UTC
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

If I create a script for a node and declare an export var: 

`@export var node_3d: Node3D`

and set the script as '@tool'

Then I pick the node in the inspector, it will be null anyways.
It works properly for NodePath instead of any other type of node, and it also works properly ingame, but not as a tool.

https://user-images.githubusercontent.com/59066133/229898046-08a47385-f2fe-43a8-98bd-53f1c86ab9d6.mp4

### Steps to reproduce

Create a tool script for any node in a scene, and declare an export variable. Set the node variable in the inspector, try to access that node in the tool script and it will produce an error:

` res://MainScene.gd:20 - Invalid get index 'name' (on base: 'Nil').`

### Minimal reproduction project

Ignore the name of the minimal reproduction project, the name is not related to the issue

[TestExportCustomClass.zip](https://github.com/godotengine/godot/files/11152220/TestExportCustomClass.zip)

**Comment by winston-yallow** [comment] 2023-06-03 11:45
I can reproduce this on v4.0.3.stable.

Not sure if it's of any help for debugging, but when I add a setter with a print statement, it seems like the setter is never called. So it's not set to null, it's simply never set at all.

**Comment by ajreckof** [comment] 2023-06-13 21:25
This is fixed in master by #76389. It is a duplicate of #74141 (for nil) and #74050(for setters).

**Comment by adamscott** [comment] 2023-06-13 21:28
@Calinou Did you encounter the issue yourself recently, like within the last 2 weeks?

**Comment by adamscott** [comment] 2023-06-13 21:36
@Calinou Nevermind, @winston-yallow said that he reproduced it. Misread his comment.
Will close the issue as @ajreckof comment as a duplicate.

**Closed by adamscott** 2023-06-13 21:36 UTC
Labels: bug, topic:gdscript, confirmed

**Comment by TheConceptBoy** [comment] 2023-08-29 21:05
Why was this closed as not planned? Is it because it's duplicate? I've just encountered the same issue in 4.1.1

**Comment by ajreckof** [comment] 2023-09-05 14:30
This was effectively a duplicate but also something that was already fixed in master. I think the fix should be in 4.1
If you can reproduce please do open a new issue it might be a regression or something different that seems similar. And please add a minimal reproduction project as the MRP does not exhibit any wrong behavior in master.
