### ISSUE TITLE
using load(path) outside res results in loader not found

### ISSUE THREAD

**Issue by Jack-MoG** [godotengine/godot#41607] opened 2020-08-29 22:56 UTC
**Godot version:**

v3.2.1 stable edition

**OS/device including version:**

Windows 10

**Issue description:**

Using load(path) on a file outside of the res:// results in a "Loader not found error" despite the file existing 

I'm working on a project that takes 3D models (.obj) from anywhere in a user's computer and adds them to the scene. I was able to find a workaround for 2D files (.png) using the Image class, but I couldn't find an equivalent for 3D. Mainly the Image.load(path) and the ImageTexture.create_from_image(Image) have no counterparts for Meshes. 

**Steps to reproduce:**
use the load(path) method on a path outside of res://

**Minimal reproduction project:**

[Godot load issue demo.zip](https://github.com/godotengine/godot/files/5146085/Godot.load.issue.demo.zip)
This project has a DNA.obj file that can be loaded when it's in the res:// folder, if you make a copy on the desktop and attempt to reach it the error is repeated

**Comment by Jack-MoG** [comment] 2020-08-30 04:06
#14879 deals with the same issue, there doesn't seem to be a fix for it yet, only workarounds for some image and audio files.

**Comment by Calinou** [comment] 2020-08-30 12:49
Duplicate of https://github.com/godotengine/godot/issues/14879.

**Closed by Calinou** 2020-08-30 12:49 UTC
