### ISSUE TITLE
Unable to save edited script via ctrl-s without open scene

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#43375] opened 2020-11-07 11:34 UTC
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

win10

**Issue description:**

When editing a script in the built-in editor (gdscript, created via the Filesystem dock) and trying to save it (ctr+s) with no scene currently open, it won't be saved, but an error is shown that a root node is required to save the scene.

**Steps to reproduce:**
Create a gdscript via filesystem, make sure no scene is open, edit the script and hit ctrl+s to try to save it; notice the error and the script not being saved.

**Comment by Calinou** [comment] 2020-11-07 13:48
Duplicate of https://github.com/godotengine/godot/issues/9069.

**Closed by Calinou** 2020-11-07 13:48 UTC
Labels: bug, topic:editor
