### ISSUE TITLE
Creating a new directory causes a rescan which takes ages

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20202] opened 2018-07-17 03:09 UTC
**Godot version:**
3.1.x (master)

**OS/device including version:**
ubuntu, nvidia

**Issue description:**
Moving a file or creating a new directory causes godot editor to start "scanning files, please wait..." (stdout shows "call rescan!") and it sits at 97% for a minute or so. 

Is this new? And is it possible to avoid this call or speed it up?

**Comment by rminderhoud** [comment] 2018-07-17 14:04
I've also had the editor crash when moving a directory with a large amount of files/sub-directories and it starts the re-scan. Unfortunately I didn't capture the crash logs. I will see if I can reproduce.

**Comment by akien-mga** [comment] 2018-07-24 12:01
Duplicate of #19991.

**Closed by akien-mga** 2018-07-24 12:01 UTC
Labels: bug, topic:editor, usability
