### ISSUE TITLE
Something in this scene ruin everything in WebGL(GLES3) build, only on Windows (example in)

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#32189] opened 2019-09-18 14:17 UTC
**Godot version:**
3.1.1 stable just downloaded

**OS/device including version:**
Windows webbrowsers(all of them)

**Issue description:**
**Maybe** this is ANGLE problem on Windows only.

[TEST LINK](https://danilw.github.io/godot-utils-and-other/BUG_ANGLE_broken/index.html) **DO NOT CLICK IT**, it may ruin entire OS.
This link work without any problems in Linux Web-browsers.
when on Windows OS it does not (look screenshots of error)

**disable ANGLE does not help**

related to https://github.com/danilw/e-ani

**Steps to reproduce:**
Open link above or make HTML5 build from my project. And try launch it in browser

Source project has no scripts, only particles, few meshes, materials, and one animation.

**Minimal reproduction project:**
[zip link](https://danilw.github.io/godot-utils-and-other/BUG_ANGLE_broken/e_ani_webgl_local.zip)

I was able to catch only this two errors, on  Windows. most of launch-times debug console just frozen with no output. I have test it on GPU with 2gb VRAM, and other people try it on 4gb Vram, this is not out_of_VRAM_memory problem.

![1](https://user-images.githubusercontent.com/24825887/65156529-f03b8600-da37-11e9-8e27-0816c59f5c55.jpg)
![2](https://user-images.githubusercontent.com/24825887/65156530-f03b8600-da37-11e9-93ab-2db62fb25b82.jpg)

**Comment by Calinou** [comment] 2019-09-18 15:23
Duplicate of #21957. Try switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**). WebGL 2 implementations are too buggy to be usable in most Web browsers :slightly_frowning_face:

**Comment by danilw** [comment] 2019-09-18 15:24
okey thanks

**Closed by Calinou** 2019-09-18 15:23 UTC
