### ISSUE TITLE
GDScript suggestion: The "With" Construction from GMS

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/godot#18345] opened 2018-04-22 01:11 UTC
It executes the given statement to a given node with the "other" keyword, for example:
```gdscript
extends Node2D
var random_color = Color()
var random_position = Vector2()

func _process(dt):
   var window_size = OS.get_window_size()
   #set random color
   random_color = Color(randf(),randf(),randf())
   random_position = Vector2(rand_range(window_size.x),rand_range(window_size.y))
   #The expression/node is a Polygon2D ($rectangle)
   with ($rectangle):
      set_color(other.random_color)
      set_position(other.random_position)
```

**Comment by vnen** [comment] 2018-04-22 01:47
I don't really see the point of it, only makes the code harder to read because you have to switch context in your head. What's wrong with regular indexing?

```gdscript
var rect = $rectangle
rect.color = random_color
rect.position = random_position
```

**Comment by manokara** [comment] 2018-04-22 03:43
The *with* keyword is a solution to a problem Godot doesn't have. It performs a context switch, so you could do things like `event_perform()` and use scripts to change instance vars. We've got classes, objects have their own functions and you can initialize an instance with arbitrary values by overriding the `_new()` function. 

In your example *with* would be just syntax sugar for vnen's code. In fact, you could even drop the `rect` reference and use `$rectangle` directly, saving an extra line.

**Comment by nobuyukinyuu** [comment] 2018-04-22 03:54
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/with-end-with-statement

For some reason I feel like I remember seeing some kinda syntax either in gdscript or python or something similar where you can initialize several fields of a variable at once using `with`-like syntax, except it took a dictionary as an initializer, something like this:

```
gdscript

func with(target, fields):  #fields is Dict of (String, Variant)
  for key in fields.keys:
    var set_property = target.set(key, fields[key]

    if set_property == false:  #Maybe a method
      if target.has_method(key):
        target_func = funcref(target, key)
        target_func.call_func(fields[key])
```

**Comment by raymoo** [comment] 2018-04-24 20:56
@nobuyukinyuu `with` statements in Python let you initialize something that needs cleanup and it will automatically run the cleanup if there is an exception within the with statement body (or if the body exits normally). It's like RAII in C++ for variables on the stack.

**Comment by eon-s** [comment] 2018-04-25 10:39
Looks like duplicate of #1736, and even being old, has better syntax and examples.

Personally, I find this confusing and error prone related to indentation.

**Comment by nobuyukinyuu** [comment] 2018-04-25 12:06
#1736 is describing something like VB's `Using` blocks.  I'm not so fond of the utility of that one, but unlike that request, I don't find this one confusing at all, especially if existing dictionary syntax can be used (a curly block can simply be proceeded by `with x:`.)

**Comment by coppolaemilio** [comment] 2018-04-28 00:49
Coming from GM:S, I don't think GDScript needs this feature. For those of you who want to know more about it, here you have the official docs on it: https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/401_18_with.html

But again, I don't think this should be implemented.

**Comment by akien-mga** [comment] 2018-05-02 06:47
As described in https://github.com/godotengine/godot/issues/1736#issuecomment-385880186, and according to the various comments here mentioning that the feature from GMS is not particularly relevant/needed in GDScript, I'll close this.

**Closed by akien-mga** 2018-05-02 06:47 UTC
Labels: feature proposal, topic:gdscript
