### ISSUE TITLE
Area Spatial doesn't detect collision (get_overlapping_bodies()) with imported objects

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#21017] opened 2018-08-14 19:05 UTC
**Godot version:** Godot Engine v3.1.dev.custom_build.e5ce6b7

**OS/device including version:**
*buntu derivative 18.04

**Issue description:**
Spatial Area node collide with a static object (a box but concave mesh collision shape when imported from collada) from imported scene. It doesn't detect the collision with **get_overlapping_bodies()**.
Static object made in godot (not imported) instead are detected

**Steps to reproduce:**
1 ) open blender, create a cube with collision (-col) and export with better collada
2) Import the collada model in a godot scene.
3) Add a  Spatial Area object with collision shape and another static object
4) in run time use get_overlapping_bodies() on the Spatial Area to check if both static objects (the imported cube and static object made in godot) are reported

**Minimal reproduction project:**
![preview](https://user-images.githubusercontent.com/42388967/44112458-7002b2d2-a005-11e8-9284-70f9441a630e.gif)
*the dark box is the static object imported (-col suffix)*

[minimaltest.zip](https://github.com/godotengine/godot/files/2288158/minimaltest.zip)

**Comment by bojidar-bg** [comment] 2018-08-15 13:46
Duplicate of #16392

**Closed by bojidar-bg** 2018-08-15 13:46 UTC

**Comment by NewNodeGames** [comment] 2018-10-18 18:49
Why you need Blender for create a cube? lol
