### ISSUE TITLE
Crash when deleting tile in TileMap editor with Y-Sort ticked

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#23873] opened 2018-11-21 11:05 UTC
**Godot version:**

f2cc9698433a32a05c76987acd20a07441313037
(Compilation from 21/11/2018)

**Issue description:**

Right click in tile in TileMap editor in a TileMap node with Y-sort property activated crash godot.

This bug is fixed with the code pasted here: https://github.com/godotengine/godot/issues/23775
So, when @bojidar-bg merge that, this issue can be closed.

**Comment by bojidar-bg** [comment] 2018-11-21 13:00
Duplicate of #23775, no need to keep two issues for that.

**Closed by bojidar-bg** 2018-11-21 13:00 UTC
Labels: bug, topic:editor
