### ISSUE TITLE
When a dictionary or array is exported using an empty value, it is exported as a reference for all other instances of the same scene

### ISSUE THREAD

**Issue by db0** [godotengine/godot#44311] opened 2020-12-12 01:17 UTC
**Godot version:**

3.2.3 stable official

**OS/device including version:**

Windows 10 x64
**Issue description:**

When a dictionary or array is exported using an empty value (i.e. with `= {}` or `= []`), then it will be exported as a reference which is common to all instances of the same scene. 

This does not happen if one declares the variable with just the type, or if one does not export the variable

It is expected that a dictionary assigned to a scene, will be unique to each instance of that scene, rather than act as a sort of reference. It is also expected that dictionaries will act consistent among declaration styles.

**Steps to reproduce:**

export a dictionary variable with an assigned empty dictionary and instance the scene. Fill in some values. Instance another of the same scene. Dictionary in the new scene will start prefilled with the same values.

**Minimal reproduction project:**

In the below project, I have a scene which declared 3 dictionaries in 3 different ways

```
export var dict_empty = {}
export var dict_declared : Dictionary
var dict_unexported = {}
```

Then I instance 3 copies of that scene, and I prefill some values only on the first one. A subsequent print, shows the first dictionary on all three nodes has the same values as the first node.

```
Iter: 0 - Assigned Empty Dict:{a:1, b:2}. Declared Dict:{a:1, b:2}. Unexported Dict:{a:1, b:2}
Iter: 1 - Assigned Empty Dict:{a:1, b:2}. Declared Dict:{}. Unexported Dict:{}
Iter: 2 - Assigned Empty Dict:{a:1, b:2}. Declared Dict:{}. Unexported Dict:{}
```

[exported-dict.zip](https://github.com/godotengine/godot/files/5682264/exported-dict.zip)

**Comment by Calinou** [comment] 2020-12-12 14:02
Duplicate of https://github.com/godotengine/godot/issues/16478.

**Closed by Calinou** 2020-12-12 14:02 UTC
