### ISSUE TITLE
Script tab holds their content, even if closed without saving

### ISSUE THREAD

**Issue by honix** [godotengine/godot#71426] opened 2023-01-14 19:14 UTC
### Godot version

v4.0.beta.custom_build [4c5e09f96]

### System information

Windows 10

### Issue description

Closing script tabs with context menu, doesn't discards its cache properly. Closing with Ctrl+W works fine!

Script tabs seems to have some cache, and this cache is shown when same file opened again, even if script file was closed with Discard changes option.

Reloading editor shows file without cache like changes was really discarded.

### Steps to reproduce

- Create new script
- Type some text in (modify some comments for example)
- Close file by right click on file tab, and click close
- Select Discard on "Save changes?" dialog
- Open it again
- Content look like it was saved

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment] 2023-01-14 19:26
Looks like duplicate of #50578

**Closed** 2023-01-14 19:30 UTC
