### ISSUE TITLE
Editting CollisionShape2D in a duplicated CharacterBody2D resulting simutaneously change.

### ISSUE THREAD

**Issue by EmasikWothlan** [godotengine/godot#87049] opened 2024-01-10 17:49 UTC
### Tested versions

Version: 4.2 stable

### System information

Windows 10 and MacOS Sonoma 14.0

### Issue description

CollisionShape2D inside CharacterBody2D will simutaneously change when editted on a duplicated scene.

### Steps to reproduce

1. click the "+" at top to start a new CharacterBody2D (c_1).
2. add a collision shape 2d and set a rectangle shape
3. save.
4. copy the character body 2d node.
5. click the "+" at top to start a new scene
6. paste the character body 2d node (c_2)
7. save as another scene
8. change the CollisionShape2D's shape of c_2

result: both of the CharacterBody2D's collision shape changed.

PS:
- to reproduce the issue, one should copy either c_1 or c_2's root node (or start new CharacterBody2D), paste to another new scene. After restarting IDE, the "link" of two collision shape node disappears.
- after changing c_2's collision shape, C1's shape changed simutaneously. without adding them to another scene and restart the IDE, c_1's shape becomes as before.
- if both c_1 and c_2 were added to a new scene, after restart, the changing remains.

there might be other behaviors not awared.

### Minimal reproduction project (MRP)

[CollisionShapes.zip](https://github.com/godotengine/godot/files/13891179/CollisionShapes.zip)

**Comment by AThousandShips** [comment] 2024-01-10 17:51
Duplicate of https://github.com/godotengine/godot/issues/75165

**Closed** 2024-01-10 17:51 UTC
