### ISSUE TITLE
Godot can not get translation that contain "msgctxt" from gettext (.po) translations 

### ISSUE THREAD

**Issue by ViewShumoon** [godotengine/godot#75878] opened 2023-04-10 06:47 UTC
### Godot version

4.0.2-stable

### System information

Windows10, x86_64, Vulkan, Intel(R) UHD Graphics 615

### Issue description

Godot can't get translations that contain "msgctxt", the others can get it correctly, like:
```
# Can be translated
msgid "This is strings without msgctxt\n"
msgstr "(en) This is strings without msgctxt\n"

# Can't be translated
msgctxt "The context of this string"
msgid "This is strings has msgctxt\n"
msgstr "(en) This is strings has msgctxt\n"
```

### Steps to reproduce

- Make a scene with three labels  
  | Label | text |  
  | ----------- | ----------- |
  | Label_Source | This is source strings |
  | Label_Without_msgctxt | This is strings without msgctxt |
  | Label_Has_msgctxt | This is strings has msgctxt |
- Generate .pot files of this scene using the Godot editor
- Generate .po files from .pot
  ```
  msginit --no-translator --input=source.pot --locale=en
  ```
- Fill the .po translations
  ```
  msgid "This is source strings"
  msgstr "(en) This is source strings"

  msgid "This is strings without msgctxt"
  msgstr "(en) This is strings withoutmsgctxt"

  msgctxt "The context of this string"
  msgid "This is strings has msgctxt"
  msgstr "(en) This is strings has msgctxt"
  ```
- Import this translation in the editor
- Start the game, observe if the front of the Label is added (en)

### Minimal reproduction project

[gettext-text.zip](https://github.com/godotengine/godot/files/11188335/gettext-text.zip)

**Comment by timothyqiu** [comment] 2023-04-12 12:00
I don't think this is a bug. It seems that the POT does not have `msgctx` and you added `msgctx "The context of this string"` into the PO files manually.

`msgctx` together with `msgid` are used as the translation key. So the PO entry does not match its corresponding POT entry (what it should be).

Auto translation of `Control`s does not use context. You have to call `tr()` with the context manually, and it'll be used when generating the POT file.

**Comment by timothyqiu** [comment] 2024-09-21 15:54
Closing since this is expected behavior as explained above. Feel free to reopen this issue in case you think there is a misunderstanding.

See [this discussion](https://github.com/godotengine/godot-proposals/discussions/8061) if you are interested in making auto translation support contexts.

**Closed by timothyqiu** 2024-09-21 15:54 UTC
Labels: discussion, topic:core
