### ISSUE TITLE
AnimationPlayer editor selection when scrolling

### ISSUE THREAD

**Issue by Yuumayay** [godotengine/godot#89836] opened 2024-03-24 02:09 UTC
### Tested versions

4.3 dev5

### System information

Windows 11 - Compatibility

### Issue description

In the AnimationPlayer editor, when I go to the edge while selecting a range, it does not scroll, and when I scroll with the wheel while selected, the range is displayed incorrectly.

### Steps to reproduce

https://github.com/godotengine/godot/assets/133189500/af30bd3e-3b61-4559-978c-dec168f3bc79

### Minimal reproduction project (MRP)

[godot43test.zip](https://github.com/godotengine/godot/files/14734152/godot43test.zip)

**Comment by TokageItLab** [comment] 2024-03-24 05:48
Duplicate of https://github.com/godotengine/godot/issues/76819.

**Closed by TokageItLab** 2024-03-24 05:48 UTC
