### ISSUE TITLE
Marshalls.base64_to_utf8() not correct decoded

### ISSUE THREAD

**Issue by woogyface** [godotengine/godot#94028] opened 2024-07-07 12:32 UTC
### Tested versions

Reproducable in: "v4.2.2.stable.mono.official [15073afe3]"

### System information

Windows 10 Version: 10.0.19045 Build 19045 - Godot v4.2.2.stable - Compatibility

### Issue description

The function Marshalls.base64_to_utf8 returns almost the correct string. It is missing the last character. third party decoder will return the correct string (tested with https://www.base64decode.org/)

### Steps to reproduce

create a new node. add a script to it. put the following code under _ready() and execute the scene.

```gdscript 
var token := "eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE3MjE1NjM2NTMsImlkIjoiemRhODhtM2xteDg1Y3RyIiwidHlwZSI6ImF1dGhSZWNvcmQifQ"
var decoded_token := Marshalls.base64_to_utf8(token)
print(decoded_token)
```

decoded_token will contain a corrupted dictionary as string. it is missing the last "}" character.

### Minimal reproduction project (MRP)

[MarhallsTest.zip](https://github.com/user-attachments/files/16119321/MarhallsTest.zip)

**Comment by AThousandShips** [comment] 2024-07-07 13:19
It works with `"eyJjb2xsZWN0aW9uSWQiOiJfcGJfdXNlcnNfYXV0aF8iLCJleHAiOjE3MjE1NjM2NTMsImlkIjoiemRhODhtM2xteDg1Y3RyIiwidHlwZSI6ImF1dGhSZWNvcmQifQ=="`, the base64 encoded data in the engine is expected to be fully padded so the input above is incomplete

This might be something to change, but I think this is something to document properly instead

**Comment by AThousandShips** [comment] 2024-07-07 13:22
This is a duplicate of:
* https://github.com/godotengine/godot/issues/34145

See there for more details, closing this as this is not valid or complete base64 input based on the standard

**Closed by AThousandShips** 2024-07-07 13:22 UTC
Labels: discussion, topic:core, documentation
