### ISSUE TITLE
Audio import problem

### ISSUE THREAD

**Issue by honix** [godotengine/godot#1837] opened 2015-05-06 18:02 UTC
*Bugsquad edit:* Initially seen on 1.1 rc2.

Trying to import wav audio files. And got this.

![default](https://cloud.githubusercontent.com/assets/11596541/7499911/061f2372-f433-11e4-8a5b-28ee35c18741.png)

ps: Trying same file on 25april build - success

**Comment by reduz** [comment] 2015-05-06 18:05
can you send the audio file that breaks?

**Comment by honix** [comment] 2015-05-06 18:16
This is nice one - https://drive.google.com/file/d/0B3ZBazA8QzyMcHlrZ1NvRElvek0/view?usp=sharing

**Comment by honix** [comment] 2015-05-06 18:19
Another bug

![default](https://cloud.githubusercontent.com/assets/11596541/7500312/8e293b2a-f435-11e4-9110-26c35278a3b2.png)

But in game works fine

**Comment by akien-mga** [comment] 2015-11-17 07:33
I can't reproduce your first issue in the current master branch, the wav file imports just fine. I can't reproduce the second bug either by trying to play the newly imported file in my SamplePlayer.

So I'll assume this has been fixed in the meantime, but please tell me if you can still reproduce the bug, I'll reopen the issue.

**Closed by akien-mga** 2015-11-17 07:33 UTC
Labels: bug, topic:editor
