### ISSUE TITLE
3D viewport has a vertical split that can cause the viewport to disappear

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#14413] opened 2017-12-08 15:26 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64bit - Godot 3.0 Beta 1

**Issue description:**
On the left side of the 3D viewport there is a vertical split that can be dragged around. If it is dragged all the way to the right side of the viewport the 3D viewport will disappear until you close and reopen the project.

**Steps to reproduce:**
![example gif](https://i.imgur.com/h7CdLNS.gif)

**Comment by ZX-WT** [comment] 2017-12-08 15:34
duplicate of #13197

**Closed** 2017-12-08 15:46 UTC
Labels: archived

**Comment by CowThing** [comment] 2017-12-08 16:01
Ah alright, I tried searching but didn't find that.
