### ISSUE TITLE
Differences between design time and run time in editor

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#52014] opened 2021-08-23 11:30 UTC
### Godot version

3.4.beta4.mono

### System information

Linux 11

### Issue description

An image worth of many words :)
![image](https://user-images.githubusercontent.com/13235119/130440016-3a554db8-119f-4bd6-8710-f6dd6c1f825b.png)

Its not make easy to understand how to design something different from "tutorials" :)
### Steps to reproduce

Good question. I can say I tried different approaches but besides set all full screen I found no solution

### Minimal reproduction project

Its no related to any scripts

**Comment by Zireael07** [comment] 2021-08-23 12:00
What is your stretch mode set to?

**Comment by git2013vb** [comment] 2021-08-23 12:03
![image](https://user-images.githubusercontent.com/13235119/130443975-ae37bfca-bf2b-418e-8803-5cf2d108337f.png)

**Comment by Zireael07** [comment] 2021-08-23 12:09
In that case, you seem to be misunderstanding something about the controls and anchors. The most likely culprit is the HBoxContainer - is it set to the same size the top-level control is? Have you tried setting the min size? In my experience, the containers try to size themselves as small as possible so setting the min size is crucial...

BTW are you aware that the blue lines are your screen size? That means as designed in editor, your whole HUD takes up roughly the top left 1/4 of your screen...

**Comment by git2013vb** [comment] 2021-08-23 12:11
This is not my point. :)
My point is the difference between design time and run time. If I set any value about any object I expect to have same result in run time. Don't you agree?

**Comment by Zireael07** [comment] 2021-08-23 12:14
No, because the whole point of containers like HBoxContainers is that they size themselves automatically and place children automatically.

**Comment by git2013vb** [comment] 2021-08-23 12:16
> No, because the whole point of containers like HBoxContainers is that they size themselves automatically and place children automatically.

Than not explain the problem imo.

**Comment by KoBeWi** [comment] 2021-08-23 12:54
> Its no related to any scripts

Scripts or not it doesn't matter. A reproduction project would be helpful, otherwise we can just guess what is wrong.

**Comment by git2013vb** [comment] 2021-08-23 19:49
[TestDesign.zip](https://github.com/godotengine/godot/files/7034472/TestDesign.zip)
No need to guess . I did my investigation.
The problem happen resizing the window. Using either `OS.WindowSize` or changing the project settings Display-.Wndow->Width & Height.
The panel don't keep its original size and scale down without asking permission. :)
If I set the window size(1024x600) to control size (650x400) the panel size will change from 650x400 to 276x200.

**Comment by KoBeWi** [comment] 2021-08-23 20:17
Well, you did permit the panel to resize, by setting the anchors to Full Rect layout. SetFaction node is set to Full Rect, so it will resize to the viewport. Panel is set to FullRect too, so it will resize to its parent control (and keep the size ratio). If you want your panel to stay in place and don't change size, change its anchors to top-left.

If you want your in-editor scene look the same as in game, make sure that their resolution match, i.e. the blue outline and the window size are the same. Closing, as it's not a bug, but the way anchors work.

**Closed by KoBeWi** 2021-08-23 20:17 UTC
Labels: needs testing, topic:gui
