### ISSUE TITLE
Incorrect shader normal calculation in godot 4 compared to godot 3

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#79647] opened 2023-07-19 03:25 UTC
### Godot version

Godot v4.1.1.rc1 and 3.5.2.stable

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Godot 3
![image](https://github.com/godotengine/godot/assets/40964335/d5590b41-7ca9-4398-a74d-6023fc63c71e)
### Godot 4
![image](https://github.com/godotengine/godot/assets/40964335/e768ad6f-f76d-4fe8-814e-1eff8d17c3f6)

If you did not notice, the positive Z facing direction is broken on the Godot 4 version.
![image](https://github.com/godotengine/godot/assets/40964335/2f0fd57f-8e7f-4199-b261-766dc2697316)
It's correctly calculated in the godot 3 version
![image](https://github.com/godotengine/godot/assets/40964335/c699708b-23b9-411d-8f93-eb2557dbe769)

These are both the exact same scene using the exact same shader.

The z facing normal is controlled by these two lines, which (obviously) breaks it when removed:
![image](https://github.com/godotengine/godot/assets/40964335/41e29231-41ad-472d-b49b-9a48d9fe1f34)

The shader in godot 4:
![image](https://github.com/godotengine/godot/assets/40964335/d55c5b4c-6ae2-4fe4-9f74-2288796f8368)

The exact same shader in godot 3:
![image](https://github.com/godotengine/godot/assets/40964335/8cfa8f6c-0468-4094-a8dc-d03cd8b41f9f)

The expected behavior is that this shader will function the same in godot 3 and 4.

### Steps to reproduce

Open the projects, and observe the shaders and how they are the same in both

### Minimal reproduction project

I've included both projects below.
[NormalsGD4.zip](https://github.com/godotengine/godot/files/12090768/NormalsGD4.zip)
[NormalsGD3.zip](https://github.com/godotengine/godot/files/12090769/NormalsGD3.zip)

**Comment by bitsawer** [comment] 2023-07-19 05:20
Instead of using floating point equality comparison, use an epsilon, like this:

`if (abs(NORMAL.y) < 0.0001) {`

seems to fix the issue.

You should generally avoid compariing floating points using == / != operators. I can be safe in some situations, but in practice it's often not. Especially depending on how you import or generate the mesh, the mesh import pipeline might add some inaccuracies if it recalculates normals or other data.

![abs](https://github.com/godotengine/godot/assets/22456603/c023eb51-a24a-4db6-a1f4-116ae5d4994d)

**Comment by AThousandShips** [comment] 2023-07-19 07:58
Once #77239 is merged you'll be able to use `is_equal_approx/is_zero_approx` as well

**Comment by Calinou** [comment] 2023-07-19 14:50
This is not a bug (but caused by floating-point precision errors), as described above. It might happen to work in Godot 3, but it's not guaranteed that it will keep working there correctly forever. This is why you want to use approximate comparisons instead of exact comparisons.

**Closed by Calinou** 2023-07-19 14:50 UTC
Labels: discussion, topic:rendering
