### ISSUE TITLE
Odd Text Nodes after Tags in XMLParser

### ISSUE THREAD

**Issue by Grandro** [godotengine/godot#31682] opened 2019-08-26 15:52 UTC
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
I am trying to get data from wikipedia articles and they have xml files for them which I try to convert into a dictionary.
While doing so I came across a weird behaviour which I dont know how to handle.
I made this function:

```
func xml_to_dic(file_path):
	var parser = XMLParser.new()
	parser.open(file_path)
	
	while parser.read() != ERR_FILE_EOF:
		var type = parser.get_node_type()
		
		if type == 1:
			print("NODE_NAME START")
			print(parser.get_node_name())
			print("---------------")
		
		if type == 2:
			print("NODE_NAME END")
			print(parser.get_node_name())
			print("---------------")
		
		if type == 3:
			print("NODE_DATA")
			print(parser.get_node_data())
			print("-------------")
```

That prints:
![grafik](https://user-images.githubusercontent.com/48568096/63703655-ad680300-c829-11e9-8410-283c4cea009d.png)

You can find the xml file I am using in this example here:
https://de.wikipedia.org/wiki/Spezial:Exportieren/Blaise_Pascal

I don't understand why after every tag I get a Text Node even tho there isnt any text data stored in it. For example after the tag 'siteinfo' I get a Text Node with weird contents which I dont know how to differ from Text Nodes with data I actually need.

Is there maybe an example of how to properly use the XMLParser?
Or even better, how to convert a XML file into a .json file/dictionary?

**Comment by merumelu** [comment] 2019-08-26 16:56
Duplicate of #23895? Those are the line breaks I think, it might be odd but it's intended behavior.

> Or even better, how to convert a XML file into a .json file/dictionary?

Wikipedia has [an API](https://en.wikipedia.org/wiki/Help:Creating_a_bot#APIs_for_bots) that can output JSON.

**Closed** 2019-10-11 10:44 UTC
Labels: bug, topic:core
