### ISSUE TITLE
Enums in scripts preloaded into consts can no longer be used as export type hints in inherited classes

### ISSUE THREAD

**Issue by rezich** [godotengine/godot#22256] opened 2018-09-19 17:38 UTC
**Godot version:**
b1187b9a2f8e6b6d34a04a4f9e168471de737836

**OS/device including version:**
Windows 10

**Issue description:**
In my game I have a "Global.gd" file that contains enums and static functions that I want to access in many different classes in my game. Such classes contain `const Global = preload("res://Global.gd")`. Some of these classes inherit from parent classes, some of which also contain this code.

In the current version, previously correct code now causes errors. Presumably because of e6a6ea65c7311175603a698b4051b90b2a112161 and/or b5300314426dacff2f8cd4bd76ecb61528f3d899, I now get errors when trying to redefine `const Global` in inherited classes. This is fine, I'm happy to not have to redefine `const Global` in child classes of classes that already have it, but now I can no longer use the enum preloaded from "Global.gd" into a const in the class that my current class is inheriting from as an export hint, as Godot doesn't think it's a constant expression.

**Steps to reproduce:**
1. Create empty project
2. Create new script "Global.gd":
```gdscript
enum SOME_ENUM { ENUM_VAL_A, ENUM_VAL_B, ENUM_VAL_C }
```
3. Create new script "Foo.gd":
```gdscript
extends Node
const Global = preload("res://Global.gd")
```
4. Create new script "Main.gd":
```gdscript
extends "Foo.gd"
export(Global.SOME_ENUM) var quux = Global.SOME_ENUM.ENUM_VAL_A
```
5. Godot should show you the error already.
6. Add new node to scene, attach "Main.gd" to it, save scene, set as main scene, run game.

**Minimal reproduction project:**
[GodotBug.zip](https://github.com/godotengine/godot/files/2398094/GodotBug.zip)

**Comment by rezich** [comment] 2018-09-19 18:37
After further testing, it seems this means I can't access `Global` from within any function inside "Main.gd" either: `Identifier 'Global` is not declared in the current scope`

**Comment by avencherus** [comment] 2018-09-19 22:18
I ran into this one tonight.  Though I think I may of had a different condition.  I'll have to investigate a bit more in the morning, to see if it's related.

**Comment by akien-mga** [comment] 2019-01-23 19:33
Is this still reproducible in the current master branch?

**Comment by rezich** [comment] 2019-01-23 20:06
Current master branch fails to build for me (`core\global_defaults.gen.cpp(2): fatal error C1083: Cannot open include file: 'platform/android/globals/global_defaults.h': No such file or directory`) -- I haven't rebuilt in awhile, did something change or am I doing something wrong?

**Comment by akien-mga** [comment] 2019-01-23 20:09
You should just remove the file `core/global_defaults.gen.cpp`.

**Comment by vnen** [comment] 2019-01-23 23:06
This is a duplicate of #20008. I'm already working on a fix.

**Closed by vnen** 2019-01-23 23:06 UTC
Labels: bug, topic:gdscript
