### ISSUE TITLE
Problem uncompressing assets/plugins/addons from asset store

### ISSUE THREAD

**Issue by alex9099** [godotengine/godot#8331] opened 2017-04-09 11:07 UTC
Arch Linux 64bit - Godot version: master branch

**Issue description:**
Asset store wont extract files inside folders giving a error
Files on Root folder extract correctly

**Steps to reproduce:**
-Open Godot
-Select a project
-Open asset store
-Install some addon that has folders in it (First person controller for example)
-Get the error (which gets out of screen :/)

**Link to minimal example project:**
I dont think this is necessary, it happens in all projects

**Comment by kubecz3k** [comment] 2017-07-23 18:52
I can't reproduce the issue, seems like it was fixed in mean time (tested on 4fe6b2a6744c4852cd3fdf0bc7a3437f8a16645f). If that's not the case let us know.

**Closed by kubecz3k** 2017-07-23 18:52 UTC
Labels: bug, topic:assetlib
