### ISSUE TITLE
Message when switch scenes

### ISSUE THREAD

**Issue by kuryart** [godotengine/godot#39238] opened 2020-06-02 10:49 UTC
This message appears when I switch from a scene to another: 

Switch Scene Tab
 servers/visual/visual_server_canvas.cpp:762 - Condition "pointcount < 3" is true

It seems to be an error that occurs only in the editor, and doesn't seems to have relevant effects, but I think it wasn't supposed to be there. 

I'm on Ubuntu and the project is saved in another partition that is emulated (maybe it's relevant because it caused another error in the past).

**Comment by KoBeWi** [comment] 2020-06-02 11:43
Does it happen with any scene? This looks like the error that shows for empty (Collisiion)Polygon2D nodes.

**Comment by Calinou** [comment] 2020-06-02 13:22
@kuryart When reporting bugs, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it. This way, we can know which Godot version you're using. Also, try to upload a minimal reproduction project if possible.

**Comment by kuryart** [comment] 2020-06-02 14:22
@KoBeWi That's exactly what caused the error. Fixed, sorry for the inconvenience, I'll try to search more before opening a bug thread.

@Calinou Sorry, didn't know that. Gonna follow the issue template henceforward.

**Comment by KoBeWi** [comment] 2020-06-02 14:42
> That's exactly what caused the error. Fixed, sorry for the inconvenience

Does this mean the issue is resolved and can be closed? (just want to make sure, since you didn't close it yourself)

**Comment by Calinou** [comment] 2020-06-02 21:21
@KoBeWi Is there a bug report for those error messages being displayed for no reason?

**Comment by KoBeWi** [comment] 2020-06-02 21:32
Nope. Also it would be weird if this showed without any polygon.

**Comment by kuryart** [comment] 2020-06-08 20:08
> > That's exactly what caused the error. Fixed, sorry for the inconvenience
> 
> Does this mean the issue is resolved and can be closed? (just want to make sure, since you didn't close it yourself)

Yes, I'm closing it.

**Closed** 2020-06-08 20:09 UTC
