### ISSUE TITLE
Cannot access member variable from lambda body due cyclic reference

### ISSUE THREAD

**Issue by RobertBorghese** [godotengine/godot#70592] opened 2022-12-26 15:09 UTC
### Godot version

4.0.beta10

### System information

Windows 10

### Issue description

For top-level class variables, a lambda stored in a dictionary cannot reference the dictionary members.

### Steps to reproduce

Assuming `MyAutoload.gd` is an autoload class, this code that worked in beta 8, no longer works in beta 10.

```gdscript
var f = func():
	MyAutoload.MyDict._str = "New string."

var MyDict: Dictionary = {
	"_str": "",
	"fun": f
}

# Parser Error: Could not resolve member "_OtherClass".
```

Autoload is unrelated however, just wanted to demonstrate how there's an inconsistent error if this is intended behavior. The following occurs regardless of autoload. If the "MyAutoload" part is removed from the lambda, a "cyclic reference" error occurs.
```gdscript
var f = func():
	MyDict._str = "New string."

var MyDict: Dictionary = {
	"_str": "",
	"fun": f
}

# Parser Error: Could not resolve member "f": Cyclic reference
```

### Minimal reproduction project

[Issue_70592_BugProject.zip](https://github.com/godotengine/godot/files/10304077/Issue_70592_BugProject.zip)

**Comment by Zireael07** [comment] 2022-12-26 15:16
From the mention of autoload, possible duplicate of https://github.com/godotengine/godot/issues/70495

**Comment by adamscott** [comment] 2022-12-26 15:43
@RobertBorghese Notwithstanding the possible duplicate, please join a minimal reproduction project when code is needed to demonstrate the issue, even if the code seems simple. It's so much easier for the developers to unzip the project and run it, rather than to create a new project and copy-paste the code.

**Comment by RobertBorghese** [comment] 2022-12-26 16:08
> From the mention of autoload, possible duplicate of #70495

Apologies for bad reporting, this occurs without autoload as well.



> @RobertBorghese Notwithstanding the possible duplicate, please join a minimal reproduction project when code is needed to demonstrate the issue, even if the code seems simple. It's so much easier for the developers to unzip the project and run it, rather than to create a new project and copy-paste the code.

No problem! Updated comment with minimal project! 👌

**Comment by adamscott** [comment] 2022-12-26 16:38
CC @rune-scape 

Seems related to this code:
https://github.com/godotengine/godot/blob/b6e06038f8a373f7fb8d26e92d5f06887e459598/modules/gdscript/gdscript_analyzer.cpp#L240-L248

**Comment by Daiz** [comment] 2023-03-03 23:49
Just ran into this issue myself while playing around with Godot 4.0 stable. Small sample code to demonstrate:

```gdscript
var stats = {
	health = 100
}

var actions = {
	hit = func _hit(damage := 1):
		stats.health -= damage
		if (stats.health <= 0):
			actions.die()
,	die = func _die():
		queue_free()
}
```
This currently errors on `actions.die()` with `Could not resolve member "actions": Cyclic reference.`

**Closed** 2023-08-25 19:51 UTC
Labels: bug, topic:gdscript
