### ISSUE TITLE
Errors shown in console are difficult to track down

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#7469] opened 2017-01-08 14:05 UTC
**Operating system or device - Godot version:**
All OS with console output, all versions

**Issue description**
The error output in console makes it very difficult to track down, where the error lies.
An example is the error:
` ERROR: JacobianEntrySW: Condition ' m_Adiag <= real_t(0.0) ' is true.`

Instead of telling the user, which property in which object caused that error, it references some part of the godot source code.
For basic users, looking at the source code isn't an option, and even advanced users will likely have difficulties to find out, how the configuration of an object in the scene might have caused that error somewhere in code.
This leads to people just ignoring those errors, which makes the messages useless.

**Comment by reduz** [comment] 2017-01-08 14:16
that looks like a bug, more than an error..

**Comment by jmf** [comment] 2017-01-08 14:29
I call it error, since it says "ERROR" in uppercase letters in front of the message. 
I solved that bug already, the point is, that the solution (moving the object center away from the coordinate origin) is impossible to be read from the error itself and very hard to see from the code (for me).

**Comment by bojidar-bg** [comment] 2017-01-08 16:42
I think this might be fixed by #7426

**Comment by jmf** [comment] 2017-01-08 17:15
To clarify: This issue isn't about this specific error message, I just chose it as example for console messages, that don't really state the cause of the displayed error.
I'll close this issue for now.

**Comment by bojidar-bg** [comment] 2017-01-08 17:20
@jmf This hasn't been fixed though.

**Comment by BBric** [comment] 2017-01-08 19:36
With the dynamic languages the errors are sometimes in the executing code instead of calling code, it's the same in Python. Debugging becomes more laborious.

**Comment by bojidar-bg** [comment] 2017-01-08 20:04
Note that the mentioned error was actually caused by some object in the scene and was emitted from the physics server -- totally untraceble in most cases...

**Comment by Noshyaar** [comment] 2018-04-10 16:12
Still reproducible/relevant in 3.1 master 48890b1 : I'm not sure how this could be fixed.

**Comment by Calinou** [comment] 2020-06-18 14:37
Has anyone gotten the *specific* error message below in Godot 3.2.1 or later?

```text
ERROR: JacobianEntrySW: Condition ' m_Adiag <= real_t(0.0) ' is true.
```

**Comment by e344fde6bf** [comment] 2021-03-28 10:43
@Calinou 

One way you can trigger this is by creating a PinJoint and connecting two kinematic bodies to it using Godot physics backend. Tested on 3.3.rc6: [joint-bug.zip](https://github.com/godotengine/godot/files/6217148/joint-bug.zip)

**Comment by Calinou** [comment] 2021-03-28 13:06
@e344fde6bf Thanks! Could you create a separate issue about this?

The error message itself would be better tracked in https://github.com/godotengine/godot/issues/42719, so I'll close this one.

**Closed by Calinou** 2021-03-28 13:06 UTC
Labels: enhancement, topic:core, usability
