### ISSUE TITLE
variables created inside code blocks do not appear in debug window

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#38206] opened 2020-04-25 19:53 UTC
**Godot version:**
3.2.1

**OS/device including version:**
Linux Mint

In the screenshots below the breakpoint is at line 46, the line after 'newpos' is initialised.

If 'var newpos' is declared inside the if block (the second image), the debugger is not picking up the variable to put inside the debugger, and nor does hovering show any tooltip unless newpos is declared outside the if statement.

i.e. it appears the godot debugger is only tracking variables created at the current top level scope of a function.

![image](https://user-images.githubusercontent.com/12863685/80289434-5149db80-8736-11ea-9ad3-9d0985c86978.png)

![image](https://user-images.githubusercontent.com/12863685/80289452-69215f80-8736-11ea-9565-392c7810a620.png)

**Comment by MWFIAE** [comment] 2020-04-25 20:06
I could reproduce this behaviour at first. 
But after a few tries it seems like godot cought up to the variable...

This was the code I used to reproduce it.
![image](https://user-images.githubusercontent.com/6072971/80289714-b60a3380-8740-11ea-8b0c-e72fc5dd7ca7.png)

After replacing the print with breakpoint it did work as expected. Reverting it back to print didn't change anything, it continued to work as expected. Restarted godot in between because I thought maybe it's some kind of caching problem. But it continued to work even after a restart.

**Comment by chucklepie** [comment] 2020-04-25 20:10
Not for me, does it all of the time. Regardless, once is once too many :)

**Comment by chucklepie** [comment] 2020-04-26 09:58
> I could reproduce this behaviour at first.
> But after a few tries it seems like godot cought up to the variable...

I dunno if this makes a difference, but this function call was within the physics process function, not the ready function.

**Comment by BigRed-118** [comment] 2020-05-06 02:10
Can confirm, seeing this every time when setting a breakpoint in an if statement block in the physics process function, that is down from where the variable is declared or initialized. If I set a breakpoint on the initialization it's fine, but any line after that in the if statement block it doesn't show up in the debugger. Works if stepping line by line.

![image](https://user-images.githubusercontent.com/52541536/81132638-c37ba680-8f14-11ea-9270-fceb28804892.png)
No testB
![image](https://user-images.githubusercontent.com/52541536/81132655-d0989580-8f14-11ea-8310-8f22f71cc470.png)

**Comment by BigRed-118** [comment] 2020-05-10 03:43
Also, I'm only seeing this behavior when the breakpoint is set on the last line of the if statement block (or stepping to the last line with the debugger). It looks like this is associated with the line that is chosen for the local variables to loose scope on. It's assigning it to be the last line of the block instead of the line after.

**Comment by chucklepie** [comment] 2020-05-10 11:46
I can confirm this too, well spotted.

So it's somebody got an index-1 problem ;)

I guess the fix for now is to add a pass or non-statement to the end of a block....

**Comment by akien-mga** [comment] 2023-01-08 09:33
Duplicate of https://github.com/godotengine/godot/issues/53442

**Closed by akien-mga** 2023-01-08 09:33 UTC
Labels: bug, topic:gdscript, topic:editor, confirmed
