### ISSUE TITLE
Editor toolbar is bugged and control children handles are invisible when root node is viewport

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#44869] opened 2021-01-02 08:45 UTC
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Win10

**Issue description:**

Control nodes are missing handles in the editor, the toolbar toggles 'Lock' and 'Group' are inverted and don't function correctly (don't change state of the selection) and node specific entries are missing (i.e. Layout for controls), regardless of what is selected. This as discovered is due to the parent/root node being a viewport. When it's set to be of type control all other functionalities are working as expected again.
Viewport as root (bugged):

![grafik](https://user-images.githubusercontent.com/8841352/103453933-2f4e2300-4cdf-11eb-922c-c2b4dd226b5f.png)

Control as root (normal)

![grafik](https://user-images.githubusercontent.com/8841352/103453784-c6b27680-4cdd-11eb-8496-706b106f21ea.png)

Root viewport settings:
![grafik](https://user-images.githubusercontent.com/8841352/103453839-640daa80-4cde-11eb-9ac3-84d2fda316ee.png)

**Comment by Calinou** [comment] 2021-01-02 16:21
Duplicate of https://github.com/godotengine/godot/issues/30910.

**Closed by Calinou** 2021-01-02 16:21 UTC

**Comment by Flavelius** [comment] 2021-01-02 17:13
Locking is the lesser of those misbehaviours, the missing scene handles and toolbar entries are the actual bug!

**Comment by Calinou** [comment] 2021-01-02 17:18
> Locking is the lesser of those misbehaviours, the missing scene handles and toolbar entries are the actual bug!

Please open a separate issue for that after searching for duplicates.

**Comment by KoBeWi** [comment] 2021-01-02 17:23
See also #3572
