### ISSUE TITLE
 GPUParticle size causes crash

### ISSUE THREAD

**Issue by westmentodog** [godotengine/godot#72150] opened 2023-01-27 01:00 UTC
### Godot version

beta4 v4.0

### System information

Win 11, Intel Graphics

### Issue description

new 3d gpu particle node, set to quad then set it's yscale to 0.1m causes program to close.

### Steps to reproduce

new 3d gpu particle node, set to quad then set it's yscale to 0.1m causes program to close.

### Minimal reproduction project

-

**Comment by clayjohn** [comment] 2023-01-27 02:30
Duplicate of https://github.com/godotengine/godot/issues/69454

Fixed by https://github.com/godotengine/godot/pull/72064

**Closed by clayjohn** 2023-01-27 02:30 UTC
