### ISSUE TITLE
Move the view 'camera' of the editor uses QWERTY keys even on AZERTY keyboards

### ISSUE THREAD

**Issue by fire** [godotengine/godot#27541] opened 2019-03-30 21:18 UTC
**Godot version:**
3.1

**Issue description:**
For someone I know. Don't use azerty.

Right-clicking and holding inside the Scene to move the view 'camera' of the editor uses QWERTY keys even on AZERTY keyboards

**Comment by siradam7th** [comment] 2019-03-30 22:39
I suspect this has to do with the translation of the keyboard key codes,which they may not be translated according to the keyboard layout that is currently active, which in this case is an AZERTY layout.

**Comment by Calinou** [comment] 2019-03-30 23:19
Duplicate of #11777.

**Closed by Calinou** 2019-03-30 23:19 UTC
