### ISSUE TITLE
Cannot rename Nodes

### ISSUE THREAD

**Issue by offtherailstech** [godotengine/godot#72221] opened 2023-01-28 02:20 UTC
### Godot version

4.0beta16 and 4.0beta15

### System information

Linux(Endeavor OS)

### Issue description

Since 4.0 beta 15 I cannot rename nodes, or animations in an animated sprite 2d, I suspect I cannot rename anything in the editor though. Typing works fine in scripts, or in save dialogs. 

### Steps to reproduce

Node:
1. Create a node
2. Try to rename

Animated Sprite:
1. In the **Inspector** under the **Animation** section choose **New Sprite Frames** (double click to then open the animation menu)
2. In the **Animations** menu click on default to rename, I can highlight text but deleting, overwriting, adding charters does not work
3. Also tired adding a new animation which pops up as **new_animation**, click on that, also cannot rename

### Minimal reproduction project

[Rename-Issue.zip](https://github.com/godotengine/godot/files/10524348/Rename-Issue.zip)

**Comment by akien-mga** [comment] 2023-01-28 12:28
Duplicate of #72074

**Closed by akien-mga** 2023-01-28 12:28 UTC
