### ISSUE TITLE
Pin for Shader Editor

### ISSUE THREAD

**Issue by SirPigeonz** [godotengine/godot#8746] opened 2017-05-13 18:56 UTC
**Godot 3.0 master**

Pinning for Shader Editor is needed badly. :D 
For now testing shader is really unpleasant. xD
If you do anything in 3D view, Shader Editor closes.
If you want to try your fresh new uniforms in material, switching to material in Inspector also closes Shader Editor.
This is madness :D

**Comment by nunodonato** [comment] 2017-05-13 19:28
also #8069 ;)

**Comment by eon-s** [comment] 2017-05-13 20:36
I wanted to edit the shader resource outside of Godot (could be another option) but the code is not updated by the editor :upside_down_face:

**Comment by reduz** [comment] 2017-11-13 17:02
kicking to 3.1, no time to think out this properly

**Comment by Calinou** [comment] 2021-09-01 19:17
Duplicate of https://github.com/godotengine/godot/issues/32002 (same cause).

**Closed by Calinou** 2021-09-01 19:17 UTC
Labels: enhancement, topic:editor, usability, topic:shaders
