### ISSUE TITLE
Unable to update Pooled Arrays from outside a custom class

### ISSUE THREAD

**Issue by ryehollister** [godotengine/godot#59598] opened 2022-03-27 18:58 UTC
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

When a script has any type of pooled array, updates made outside that script to the pool array do nothing.

The only behaviors that works are type checking and viewing array properties. 

The current workaround is to define a custom function that handles updates to the pooled array inside the script, but is not ideal.

Appears to be in 3.2.3 as well: https://godotengine.org/qa/115937/poolvector2array-inside-resource-does-not-work-bug

### Steps to reproduce

1. Define a pooled array in a custom script. 
2. In another script, attempt to append/resize/remove/append_array/invert items from the reference pooled array.
3. Notice how appends/resizes do not change the array.

In the sample project, run the "Bug Runner"

### Minimal reproduction project

[PoolArraysBugProject.zip](https://github.com/godotengine/godot/files/8358271/PoolArraysBugProject.zip)

**Comment by Zireael07** [comment] 2022-03-27 19:05
Aaah. Confirming this one (on 3.4 stable)!!! I thought it was due to the fact that it was a Resource and not a node.

https://github.com/jarneson/godot-ply has tons of helpers likely due to this very issue, too

**Comment by Calinou** [comment] 2022-03-27 21:05
Doesn't reassigning the entire pooled array work?

**Comment by akien-mga** [comment] 2022-03-27 22:18
Duplicate of https://github.com/godotengine/godot/issues/15265?

**Comment by Calinou** [comment] 2022-03-28 12:19
> Likely so, but shows it needs to be documented better.

This is already documented in the Pool*Array class reference – I'm not sure where else it could be documented.

**Comment by Zireael07** [comment] 2022-03-28 12:27
Looked it up - yes it's documented, but I bet tons of people (like me) didn't understand what "this is passed by value and not by reference" means in practice. So either all the PoolXArrays need to say "they can't be mutated (e.g. appended) from a class property or a variable" or it needs to be called out in Advanced GDScript what "passed by value" means in practice.

**Comment by ryehollister** [comment] 2022-03-29 13:23
Cool. Thanks for looking into this. :)

**Comment by akien-mga** [comment] 2022-05-23 22:20
Fixed by #59637.

**Closed by akien-mga** 2022-05-23 22:20 UTC
Labels: topic:core, documentation
