### ISSUE TITLE
[3.2.4-rc1] AnimationTree: Blending or Adding animations out of a State Machine node doesn't work properly

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#45635] opened 2021-02-01 16:39 UTC
**Godot version:**
3.2.4-rc1

**OS/device including version:**
w10

**Issue description:**
I have 2 animations, if I blend them and set 0 I see the first animation, 1 the second, and 0.5 a mix of both, as intended.

If I do that exact same thing but with these 2 animations encapsulated in 2 different state machines instead, it'll give me the same result for the blending set to 0 or 1, but anything in between will show no animation at all.

Have similar issues with the Add, anything besides 0 shows nothing.

It only seems to be an issue if the two animations inputed in the blender are from state machines, not if only one is. Doesn't seem to affect other types of nodes like BlendTree. Apparently to not have this bug I can encapsulate the states machines in their own separate BlendTree.

**Comment by Calinou** [comment] 2021-02-01 17:19
Duplicate of https://github.com/godotengine/godot/issues/37661 ?

**Comment by Maveyyl** [comment] 2021-02-01 18:07
> 
> 
> Duplicate of #37661 ?

I saw that ticket when searching but it's a different issue. Seems like his issue is Add2 behaves like Blend2. And in his configuration (trying to add a blend space and an anim) I hadn't the issue.

If necessary I can make a gif of my problem.

**Comment by Calinou** [comment] 2021-02-01 18:09
@Maveyyl Can you upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project)?

**Comment by Maveyyl** [comment] 2021-02-01 18:34
Ok I'm lost. I failed to reproduce the bug on both the minimal reproduction and on my actual project where I had it first, despite I've had the issue for 2 days and tried different approaches to solve it.... I'm very sorry.

**Comment by josefkaragoli** [comment] 2021-05-08 21:07
Couldnt reproduce.

**Comment by SaracenOne** [comment] 2021-08-07 13:06
[animation_tree_bugs.zip](https://github.com/godotengine/godot/files/6949117/animation_tree_bugs.zip)
I've managed to make a reproduction project to demonstrate the issue the original author noted, although this is for 4.0 rather than 3.x. If people would like a 3.x version, I can make that too, but I think the bug is consistent on both versions. To test this animation_tree_test_fail.tscn and note the state of the animation tree. The animation tree consists of a blend tree with two state machines, each set up to play one of two animations, and the output of them both being blended together, but as noted, it will only play one of the two animations, and will not blend them. You can compare to the scene animation_tree_test_success.tscn to see expected behaviour with two animations simply being blended together. Although not presented here, it also seems you can blend the result of state machine + a regular animation together, and this works fine, it's just two state machines which seem to fail.

**Comment by SaracenOne** [comment] 2021-08-07 13:07
I will also note that I believe this is a seperate issue from the already well-known additive blend issue. This seems to occur on both adds and regular blends.

**Comment by SaracenOne** [comment] 2021-08-07 20:31
Still debugging this, but it looks like two state machines may somehow be ending up sharing a Playback object which is causing issues.

**Comment by SaracenOne** [comment] 2021-08-08 12:34
Aha! I think I know what the problem is here. The two state machines ended up using the same Playback object, presumably because they were duplicated. I believe this *technically* doesn't make this a bug, but a really bad usability trap. Maybe we can come up with a way so that users don't accidentally do this.

**Comment by SaracenOne** [comment] 2021-08-08 19:54
So far, I've been unable to reproduce exactly what might have caused a state machine to share the same playback resource. In the meantime though, I've discovered a similar bug which requires more specific criteria to trigger, but I believe it to be different so I will create new issue for it.

**Comment by TokageItLab** [comment] 2023-04-08 08:15
The cause of this bug, as @SaracenOne mentioned above, is that the Playback object, which should be unique, somehow has the same reference. It is easy to fix on an individual project, but there is no way to notify the user of this.

Perhaps we need to iterate through the PropertyMap of the AnimationTree at some point to detect that there are same Playback objects and print the error.

**Comment by TokageItLab** [comment] 2023-04-09 01:43
Okay, I pushed the solution in #75759.

> Also, make the PlaybackObject readonly so that it is not stored in tres. This prevents the PlaybackObject from having the same reference, since the PlaybackObject is created with a unique value each time.

**Closed** 2023-04-24 14:50 UTC
Labels: bug, topic:core, confirmed, topic:animation
