### ISSUE TITLE
Some Control nodes are broken under Node2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29400] opened 2019-06-02 15:14 UTC
**Godot version:**
8772beb45, started probably somewhere before

**Issue description:**
In current master, some Controls can't be moved when under Node2D. Affected controls I checked are anything BaseButton, Label and RichTextLabel. When moved in the CanvasItem editor, their `rect_position` and size change to `-nan(ind)`.

**Steps to reproduce:**

1. Add Node2D
2. Add a Button
3. Try to move it

**Comment by groud** [comment] 2019-06-02 15:31
Duplicate of #29305

**Closed** 2019-06-02 15:31 UTC
Labels: archived
