### ISSUE TITLE
Android deprecated gradle build warning

### ISSUE THREAD

**Issue by rieniter** [godotengine/godot#36764] opened 2020-03-03 13:12 UTC
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10 
**Issue description:**
This build was success but with this warning, i don't know this was bug or something, i will leave it here
1st build:
![2020-03-03_200944](https://user-images.githubusercontent.com/34160378/75778728-f07fd180-5d8a-11ea-813f-58d55d1c64d0.png)
2nd build with enable warning:
![2020-03-03_200646](https://user-images.githubusercontent.com/34160378/75778519-8c5d0d80-5d8a-11ea-9847-6d57425ee3ac.png)

**Steps to reproduce:**
![2020-03-03_200730](https://user-images.githubusercontent.com/34160378/75778569-a139a100-5d8a-11ea-8fc2-699ced66f9ca.png)

**Comment by cagdasc** [comment] 2020-03-09 19:54
Hi,

This is not a bug. You can check android gradle plugin [support table](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle). Maybe you can close this issue.

**Comment by Calinou** [comment] 2020-03-18 15:22
@cagdasc We should still see if we can fix as many deprecation warnings while keeping support for old Android versions (5.0 or later).

**Comment by m4gr3d** [comment] 2021-01-05 10:25
This will be addressed automatically when we update to the matching gradle version.

**Closed by m4gr3d** 2021-01-05 10:25 UTC
Labels: platform:android, topic:buildsystem
