### ISSUE TITLE
Creating very simple GUI, editing fields runs message queue out of memory

### ISSUE THREAD

**Issue by jwatte** [godotengine/godot#34592] opened 2019-12-24 22:23 UTC
**Godot version:**
Godot Engine v3.1.2.stable.official

**OS/device including version:**
Windows 10, GLES 2.0, Dell XPS 15, GeForce GTX 1050

**Issue description:**
When editing GUIs, mainly changing sizing of objects, and mainly when using tab to move to the next editor field, the editor hangs for a minute and the console contains "message queue out of memory" messages.
The GUI has about 5 nodes in it, the scene is very simple (and there's no other items in it) so I doubt that it's really a memory problem; more likely some kind of infinite message generation problem, perhaps through some race condition in GUI handling?

Log:

```text
Godot Engine v3.1.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2
Editing project: C:/Users/jwatte/code/godot/buildergame (C:::Users::jwatte::code::godot::buildergame)
Godot Engine v3.1.2.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 1050/PCIe/SSE2
erasing C:\Users\jwatte\AppData\Roaming/Godot/projects/buildergame-a30a628f151f378c7d163c6f6a2e23ff/filesystem_update4
Failed method: LineEdit:_update_callback target ID: 25058
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: ToolButton:_update_callback target ID: 8222
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: ToolButton:_update_minimum_size target ID: 8222
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorPropertyInteger:_update_callback target ID: 25055
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorSpinSlider:_update_callback target ID: 25056
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:show_modal target ID: 25058
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:grab_focus target ID: 25058
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:select_all target ID: 25058
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:_update_callback target ID: 281022
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorPropertyRect2:_update_callback target ID: 281000
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorSpinSlider:_update_callback target ID: 281020
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:show_modal target ID: 281022
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:grab_focus target ID: 281022
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:select_all target ID: 281022
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:_update_callback target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorPropertyVector2:_update_callback target ID: 281053
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: EditorSpinSlider:_update_callback target ID: 281061
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:show_modal target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:grab_focus target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:select_all target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:show_modal target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:grab_focus target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
Failed method: LineEdit:select_all target ID: 281063
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: Message queue out of memory. Try increasing 'message_queue_size_kb' in project settings.
   At: core/message_queue.cpp:56
```

**Steps to reproduce:**
1. Create a GUI with 5 containers (HBox and Vbox items)
2. Edit these items to make them lay out okay; generally the size/minimum size properties
3. Tab between the fields in the inspector
4. After a while, this will start happening

**Minimal reproduction project:**
Not project specific.

**Comment by akien-mga** [comment] 2020-01-28 07:53
Superseded by #35653.

**Comment by akien-mga** [comment] 2020-01-28 07:53
Actually, only indirectly. The heavy Message Queue use in this use case should be looked into.

Could you provide a minimal project that triggers the issue?

**Comment by KoBeWi** [comment] 2020-12-17 18:19
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-12-17 18:19 UTC
Labels: bug, topic:editor
