### ISSUE TITLE
Model with bone and animation crash device for stable but running fine for alpha. GLES2

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#27232] opened 2019-03-19 11:57 UTC
**Godot version:** 3.1 stable

**OS/device including version:** Android/ samsung j 7 core, xiaomi redmi 4 pro

**Issue description:** when exporting with 3.1 alpha project working fine but with 3.1 stable and RC 2 and 3 game just crashed. i don't know previous beta version working or not.  

**Steps to reproduce:** export minimal project with GLES 2 godot 3.1 alpha and stable. run the game on device and boom. 

**Minimal reproduction project:** inside the project there is logcat when device crash.
[simple-bug.zip](https://github.com/godotengine/godot/files/2983164/simple-bug.zip)

**Comment by fian46** [comment] 2019-03-19 12:17
model with animation player will not crash, but if the model have bone and the bone get animated with animation player, device will crash

**Comment by earlroxas13** [comment] 2019-03-20 04:43
#25365 
So that's what happening to me this whole time?! I thought my phone is cursed!
So, I tested on my device:
> Model without skeleton AND animation: Normal
> Model with skeleton and NO animation: Freeze my phone or crash
> Model with skeleton and animation: Freeze my phone or crash
So, summary, it only working when the model dont have skeleton AND animation.
It was tested with 3.1 official stable build.

**Comment by fian46** [comment] 2019-03-20 04:54
no model with simple animation with keyframe is fine for both device. only model with bone and the bone get animated is crashing the device. LOL your device is not cursed.

**Comment by earlroxas13** [comment] 2019-03-20 05:08
On my phone, the model with skeleton and no animation is crashing.
Can you try my project?
[CharacterTest.zip](https://github.com/godotengine/godot/files/2986584/CharacterTest.zip)

When you run the game, you can pick 3 scene:
All 3 scene dont have animation
Model A: Have skeleton -> Crash
Model B: Only mesh (no skel) -> Normal
Model C: 2 simple cube red and blue-ish -> Normal, but the blue one not rendered

**Comment by earlroxas13** [comment] 2019-03-20 05:36
Oh, and sorry im using my own project to test.
And, yes, i tried your project and it also crashing on my phone.

**Comment by akien-mga** [comment] 2019-06-12 13:27
Seems to be a duplicate of #26972.

**Closed by akien-mga** 2019-06-12 13:27 UTC
Labels: bug, high priority, platform:android, topic:rendering
