### ISSUE TITLE
Godot crashed while saving a scene, project can no longer be opened

### ISSUE THREAD

**Issue by krfgbhoiaeuzr** [godotengine/godot#39582] opened 2020-06-15 22:21 UTC
**Godot version:** 
3.2.1.stable

**OS/device including version:** 
Windows 10, build 1909

**Issue description:** 
While saving a scene, godot crashed (stopped responding) at 100% save progress into a black screen, forcing me to manually restart the machine. After that, on opening the project, the message "Error loading: MainScene.tscn / Load failed due to missing dependencies / (SceneLastWorkedOn).tscn" now appears. However, clicking "fix dependencies" shows no errors, and I also checked that all files are still there in explorer. Choosing "open anyway" just tells me the main scene can not be opened due to missing dependencies.

Searched around a bit in open issues and also looked into the project files with text editor, but could not find anything that helps. I assume, the scene file got damaged due to incomplete saving, but i have no idea how to debug or fix that. Being able to open the MainScene again (which should not be damaged) would be nice, so I don't loose all the progress.

Log messages when I open the project:

> ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://Provinz.tscn
     At: scene/resources/resource_format_text.cpp:175
ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://Provinz.tscn
     At: scene/resources/resource_format_text.cpp:175
ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://Provinz.tscn
     At: scene/resources/resource_format_text.cpp:175
ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://Provinz.tscn
     At: scene/resources/resource_format_text.cpp:175
ERROR: open: res://Provinz.tscn:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:843
ERROR: Failed loading resource: res://Provinz.tscn.
   At: core/io/resource_loader.cpp:278
WARNING: _parse_ext_resource: Couldn't load external resource: res://Provinz.tscn
     At: scene/resources/resource_format_text.cpp:175
ERROR: remove_scene: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   At: editor/editor_data.cpp:567
ERROR: recognize: res://default_env.tres:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:1190

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment] 2020-06-16 01:00
Can't help much without the said project to inspect, unfortunately. If the OS had to shutdown it seems like some files got corrupted indeed.

**Comment by krfgbhoiaeuzr** [comment] 2020-06-16 03:11
I can upload the project files if it's really neccesary. Is it safe to remove unrelated parts, like background images, sprites, etc.?

**Comment by Zireael07** [comment] 2020-06-16 06:50
We'd need the whole project folder, but from the looks of the error messages, the files got corrupted unfortunately.

**Comment by Calinou** [comment] 2020-06-16 07:40
> I assume, the scene file got damaged due to incomplete saving, but i have no idea how to debug or fix that. Being able to open the MainScene again (which should not be damaged) would be nice, so I don't loose all the progress.

In the future, we highly recommend setting up some kind of version control (typically using [Git](https://git-scm.com/)) to avoid losing unsaved work. You'll be able to backup your project to a remote service as well.

**Comment by krfgbhoiaeuzr** [comment] 2020-06-16 15:22
Alright, i can live with loosing some work. Don't want to make the whole project public just yet, so uploading everything is not possible.

What about the crash though? Ideally an editor would never crash, but while saving is propably one of the worst times, because it will likely destroy files. Seems like a serious bug which should be further investigated. Should i upload a crash report? Use a Debug build of godot in case it crashes again? Try to create a minimal project that reproduces the issue? Search for windows event logs?

**Comment by Calinou** [comment] 2020-06-16 17:24
> Should i upload a crash report? Use a Debug build of godot in case it crashes again? Try to create a minimal project that reproduces the issue? 

You could run a Godot debug build that will give you a helpful backtrace when it crashes: https://github.com/Calinou/godot-debug-builds

You'll need to start it from a terminal to be able to see the output while it crashes (so you can copy it afterwards). Also, you'll have to rename the executable to `godot.windows.opt.tools.64.exe` due to [this issue](https://github.com/Calinou/godot-debug-builds/issues/1).

> Search for windows event logs?

I don't think Windows event logs will contain anything meaningful for this issue.

**Comment by krfgbhoiaeuzr** [comment] 2020-06-16 19:43
> You'll need to start it from a terminal to be able to see the output while it crashes (so you can copy it afterwards).

Well, when the crash happened, it instantly froze my entire system. So I would not be able copy anything at that point. Does it not automatically save the output somewhere?

**Comment by avencherus** [comment] 2020-06-16 20:56
@krfgbhoiaeuzr In the Project Settings there is a category for logging.  When enabled it saves the console output in the user data folder.

Though not all crashes give output.

**Comment by Calinou** [comment] 2020-06-17 07:22
@avencherus https://github.com/godotengine/godot/issues/33253 might be problematic for this use case though :slightly_frowning_face:

**Comment by qarmin** [comment] 2021-01-20 19:54
Is crash still reproducible?
Without test project we can't check it.

**Comment by Calinou** [comment] 2021-02-14 16:05
Closing, as nobody has been able to reproduce this recently. See also https://github.com/godotengine/godot/issues/31578 which is a closely related issue.

**Closed by Calinou** 2021-02-14 16:05 UTC
Labels: bug, crash, topic:editor
