### ISSUE TITLE
Multiple independent texts can be selected

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#55318] opened 2021-11-25 19:27 UTC
### Godot version

3.4 stable mono

### System information

w10 64

### Issue description

The editor allows you to select several independent texts.
If you copy the texts, only the last text will be copied.
![gif gif](https://user-images.githubusercontent.com/19652075/143492866-56deb2be-db9c-4ac8-93f2-cabe2c247cd0.gif)

### Steps to reproduce

In the gif

### Minimal reproduction project

...

**Comment by Calinou** [comment] 2021-11-25 19:32
Duplicate of https://github.com/godotengine/godot/issues/27511 (fixed in 3.5 by https://github.com/godotengine/godot/pull/54166).

**Closed by Calinou** 2021-11-25 19:32 UTC
