### ISSUE TITLE
Creating variable inside loop will not reset the value after the next loop event

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#26955] opened 2019-03-12 07:18 UTC
**Godot version:** RC2
**OS/device including version:** Windows 10

**Issue description:**
Add this code, and run it
```
func _ready():
	for i in 10:
		var b = SomeBug.new()
		for j in 5:
			b.array.push_back(j)
		print(b.array.size())

class SomeBug:
	var array : Array
```

AFAIK, the `b` variable must be reset inside `i loop`. But, the result in console is like this
```
** Debug Process Started **
OpenGL ES 2.0 Renderer: GeForce GTX 970/PCIe/SSE2
5
10
15
20
25
30
35
40
45
50
** Debug Process Stopped **
```

expected result must be always return 5. Because size of the array is 5, not continuing from before.

**Comment by damarindra** [comment] 2019-03-12 08:38
Yup, for now, that was the fix. I'm pretty sure the result is not intended. It confuses me for one hour, and other people will have this experience too.

**Comment by groud** [comment] 2019-03-12 15:42
This might be a design choice, IIRC arrays are always shared by default.

**Comment by bojidar-bg** [comment] 2019-03-12 15:53
Duplicate of #24134

**Closed by bojidar-bg** 2019-03-12 15:53 UTC
