### ISSUE TITLE
OGG only output in left speaker

### ISSUE THREAD

**Issue by Jerome67000** [godotengine/godot#11263] opened 2017-09-14 11:49 UTC
**Operating system or device, Godot version:**
Windows 8, Godot 3.0alpha1

**Issue description:**
OGG only output in left speaker with AudioStreamPlayer and AudioStreamOGGVorbis

**Steps to reproduce:**
Create AudioStreamPlayer Node
Stream > Load > pick a ogg file
Check 'playing' in AudioStreamPlayer node
sound output only in left speaker

**Link to minimal example project:**
[ogg_bug.zip](https://github.com/godotengine/godot/files/1302819/ogg_bug.zip)

**Comment by ISylvox** [comment] 2017-09-14 11:53
Probably similar to https://github.com/godotengine/godot/issues/10787 , which is already solved by https://github.com/godotengine/godot/commit/5f0d367fef25b30742ba71f12e339137e02c59ab

**Comment by Jerome67000** [comment] 2017-09-14 11:58
Ho yes mayby, I have searched before creating new issue but only on opened issues, sorry.
I can't try from current master for the moment, will try in the week and close it if fixed.

**Comment by akien-mga** [comment] 2017-09-14 12:03
Indeed, it seems like a duplicate of #10787. Feel free to reopen if you can still reproduce it on a recent build (e.g. one from https://bintray.com/calinou/godot/editor).

**Closed by akien-mga** 2017-09-14 12:03 UTC
Labels: bug, topic:audio

**Comment by ISylvox** [comment] 2017-09-14 13:53
Just in case anyone need a newer Win-x64 build (https://github.com/godotengine/godot/commit/8c08f2380d30e300f4f80dd292e9ff83f7bb84fd) for testing, but don't want to compile it themselves.

[Godot_v3.0.alpha.8c08f23_x64.zip](https://github.com/godotengine/godot/files/1303179/Godot_v3.0.alpha.8c08f23_x64.zip)

![godot_v3 0 alpha 8c08f23_x64](https://user-images.githubusercontent.com/20697655/30433401-938b5c46-998e-11e7-8dc5-0df47a304597.png)
