### ISSUE TITLE
Parser bug - trying to check compatibility of unset target type 

### ISSUE THREAD

**Issue by slimelaboratory** [godotengine/godot#65721] opened 2022-09-12 21:07 UTC
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Win 10, intel, vulkan, RTX 2070

### Issue description

Getting an error that this:
`var player_ref : Player = null`
is a parser bug? It's not breaking the game or anything and it's a reference to my player which has 
`class_name Player` at the top of the script.

### Steps to reproduce

Upgraded from snapshot 15 -> 16. Before 16 it didn't happen.

**Comment by Calinou** [comment] 2022-09-12 23:23
Duplicate of https://github.com/godotengine/godot/issues/44375.

**Closed by Calinou** 2022-09-12 23:23 UTC
