### ISSUE TITLE
Clicking textured CSG mesh in viewport crashes Godot

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#70203] opened 2022-12-17 17:47 UTC
### Godot version

4.0 beta 8

### System information

Ubuntu Linux 22.04, Nvidia

### Issue description

Godot crashes when I click a textured CSG node

### Steps to reproduce

1. Open main.tscn
2. Click the textured CSG mesh in the viewport

### Minimal reproduction project

[CSGCrash.zip](https://github.com/godotengine/godot/files/10252314/CSGCrash.zip)

**Comment by Sslaxx** [comment] 2022-12-17 18:02
Unable to replicate using v4.0.beta.calinou.015dc492d.

**Comment by Calinou** [comment] 2022-12-17 19:02
Duplicate of https://github.com/godotengine/godot/issues/69859.

**Closed by Calinou** 2022-12-17 19:02 UTC
