### ISSUE TITLE
TileMap thumbnails

### ISSUE THREAD

**Issue by JeffVenancius** [godotengine/godot#34809] opened 2020-01-04 04:14 UTC
**Godot version:** 3.1.2

**OS/device including version:** Linux

**Issue description:** So, this show up today. Basically, when I rotate or do anything like that on a TileMap, the thumbnails get weird. The tiles itself works OK.

**Steps to reproduce:** I don't know what hapenned. I've restarted the program and it's still there. I've restarted my computer and it didn't worked.

**Minimal reproduction project:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43701418/71759693-4a4d4380-2e8f-11ea-80ee-e9a7f381e40b.gif)

**Comment by dankan1890** [comment] 2020-01-04 17:39
It seems to be the same issue #32346 (solved by #32571), can you test if it's still in beta5?

**Comment by JeffVenancius** [comment] 2020-01-05 03:56
Oh, thanks, it really was the Nvidea flicker, I just turned it off. Also, I've tested on beta5 and it's not hapenning there.

**Comment by akien-mga** [comment] 2020-01-05 08:30
Thanks, closing as duplicate of #32346 then.

**Closed by akien-mga** 2020-01-05 08:30 UTC
Labels: bug, topic:editor
