### ISSUE TITLE
Navigation Mesh causes engine to lock up or crash when unpausing.

### ISSUE THREAD

**Issue by A-Hugh-Mann** [godotengine/godot#100223] opened 2024-12-09 22:43 UTC
### Tested versions

- Reproducible in: 4.4.dev [6f4cb1032] and later commits.
- Not reproducible in: 4.4.dev [d14672863] and previous commits.

### System information

 Godot v4.4.dev - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +000 on Tty -X11 display driver, Multi-window 3 monitors - Vulkan (Forward+) - Dedicated AMD Radeom RX 6600 (RADV NAVI23) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

When unpausing a running project whne there is a NavigationAgent3D in use, the project still freeze entirely, and an instance of addr2line will hang, utilizing an entire core of cpu while eating up several gigs of memory. The project will either hang indefinitely or eventually crash. This does not occur on commits prior to 6f4cb1032, appears to be related to that particular commit.

### Steps to reproduce

Create a new project with a Node3D.
Add a NavigationRegion3D with a MeshInstance or other thing to create a navigation mesh from of your choice as a child of that navigation region.
Set the regions baking aabb, then bake the navigation region.
Add a NavigationAgent3D as a child of any other node.
Add a node of any type as a child of that root Node3D, and give that node this script:
```gdscript
extends Node

func _input(event: InputEvent) -> void:
   if event.is_action_pressed(&"ui_cancel"):
      process_mode = PROCESS_MODE_ALWAYS
      get_tree().paused = not get_tree().paused
```
Run project, then press ESC twice.
Observe that once unpaused, you cannot pause again as the running project is now frozen until it crashes, and observe in your performance monitor that a cpu core is now running at 100% and eating up much memory.

### Minimal reproduction project (MRP)

Not on a system that has Godot installed, unable to get project here, above steps can create it though. Can likely create a script that creates all the neccesary nodes and adds them to a root node upon request if its needed.

**Comment by smix8** [comment] 2024-12-09 22:59
Thanks for reporting this. The related fix for this has just been merged with PR https://github.com/godotengine/godot/pull/100105 and it should be included with the next dev release.

Closing as it is a duplicate of https://github.com/godotengine/godot/issues/100085 and the reported issue has been solved.

**Closed by smix8** 2024-12-09 22:59 UTC
