### ISSUE TITLE
Menus and tooltips sometimes displayed with a large offset

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#51786] opened 2021-08-17 09:44 UTC
### Godot version

4.0.dev Calinou's builds and custom builds

### System information

Windows 10 21H1

### Issue description

Sometimes menus and tooltips displayed with a large offset. I cannot identify any action that causing. Sometimes on the first start of the editor with an empty project, sometimes after a long time of editing an old project, but when happened never goes back to normal (at least never happened to me). If I reopen the editor, it's working ok for the most cases, but sometimes not.

https://user-images.githubusercontent.com/36025825/129700112-9d7dcbaa-caf1-41ec-8119-38f3c0622311.mp4

### Steps to reproduce

If I know, I will share with you. I promise. :)

**Comment by Zireael07** [comment] 2021-08-17 10:28
Do you have two monitors maybe and/or a Retina screen? I am almost certain this is a dupe of an existing issue

**Comment by MmAaXx500** [comment] 2021-08-17 10:32
@Zireael07 Nothing special. One 2560x1440@165Hz monitor.

**Comment by jmb462** [comment] 2021-08-17 13:19
Does it occurs with Single Window mode desactivated in Editor Settings ?

**Comment by MmAaXx500** [comment] 2021-08-17 14:26
@jmb462 Yes, it's deactivated.

**Comment by KoBeWi** [comment] 2021-08-17 19:21
Duplicate of #45740

**Closed by KoBeWi** 2021-08-17 19:21 UTC
