### ISSUE TITLE
Incorrect transform for collision shapes under KinematicBody(3D) first frame after creation and post-add_child translation in _physics_process

### ISSUE THREAD

**Issue by abaire** [godotengine/godot#45650] opened 2021-02-02 01:12 UTC
**Godot version:**
3.2.3 and reproduced at b24c24f64b4ac9c30dc5a9e097163cbc64939645

**OS/device including version:**
Windows 10

**Issue description:**
A KinematicBody3D that is instanced and added to the scene within a `_physics_process` but translated after addition will have collision shapes that are incorrectly translated for the remainder of that physics frame.

This is probably easier to understand from the attached project than it is to describe in words since it's a bit of an odd edge case. 

**Steps to reproduce:**

Create a scene that has a collision shape (e.g., a default box) at the origin (0, 0, 0). 
Attach a script to the object that checks for collisions (e.g., `move_and_slide(Vector3.ZERO)` w/ an associated `get_slide_count()`).

Within the root node's `_physics_process`:
Create a `KinematicBody3D` with a collision shape (e.g., a default box) attached to it.
Add that KB3D to the scene via `add_child`
Modify the translation of the KB3D such that it should not collide with the shape at the origin

Expected:
Since the child is created and moved before the origin object's `_physics_process`, there should be no collision.

Actual:
The origin object detects a collision with the newly added and translated node.

This can be avoided by either:
a) Translating the model before adding it to the tree.
b) Removing and readding the model immediately before returning from `_physics_process`.

**Minimal reproduction project:**
[first_frame_physics_collision_error.zip](https://github.com/godotengine/godot/files/5907848/first_frame_physics_collision_error.zip)

**Comment by Calinou** [comment] 2021-02-02 01:23
Duplicate of https://github.com/godotengine/godot/issues/45598 (same cause). See discussion in https://github.com/godotengine/godot/issues/45638.

**Closed by Calinou** 2021-02-02 01:23 UTC
Labels: bug, topic:physics
