### ISSUE TITLE
built in script not marked as unsaved when you modify code

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#39759] opened 2020-06-22 18:08 UTC
**Godot version:**
3.2.1 stable

**OS/device including version:**
linux mint mate

**Issue description:**
If you create a script for a scene with 'built in' scripting, the scene is not marked as unsaved/dirty when you update the code and on closing the tab, you lose everything without any message. I am creating tools and built in is the neatest way to avoid multiple files and I do not know how many times I've lost everything.

**Steps to reproduce:**
1. create a scene and save it
2. add a new script and select built in
3. modify the script
4. close the scene and watch all your code disappear

**Comment by KoBeWi** [comment] 2020-07-06 09:32
Duplicate of #36281

**Closed by KoBeWi** 2020-07-06 09:32 UTC
