### ISSUE TITLE
Shader - Editor Crash from Uniform Vector Default Value

### ISSUE THREAD

**Issue by EliasWatson** [godotengine/godot#16506] opened 2018-02-08 22:22 UTC
**Godot version:** Godot v3.0 stable

**OS/device including version:** Windows 10 Home x64

**GPU:** GTX 1060 6gb
**Graphics Driver Version:** 390.65

**Issue description:**
A shader with `uniform vec2 a = vec2(0.0);` in it will instantly crash the editor when it's compiled. I have only tested spatial shaders and vec2's, but I imagine it works with any shader type and any vector.

**Steps to reproduce:**
1. Create a mesh node
2. Add a mesh to it, does not matter which
3. Add a ShaderMaterial and click it to enter
4. Create a new shader and edit it
5. Write: `shader_type spatial; uniform vec2 a = vec2(0.0);`
6. Save to compile the shader
7. Editor crashes

**Minimal reproduction project:** [Shader Bug.zip](https://github.com/godotengine/godot/files/1709025/Shader.Bug.zip)

**Comment by vnen** [comment] 2018-02-09 01:15
Thanks for the detailed report, but I'm closing this as a duplicate of #15166.

**Closed by vnen** 2018-02-09 01:15 UTC
