### ISSUE TITLE
Hotkey for distraction-free mode on macOS conflicts with system hotkey (Ctrl+Cmd+D)

### ISSUE THREAD

**Issue by increpare** [godotengine/godot#22883] opened 2018-10-09 13:37 UTC
**Godot version:**
3.0.6.stable.official.8314054

**OS/device including version:**
macOS 10.13.6 (17G65)

**Issue description:**
It says in the tooltip that to make a panel fullscreen I should press ctrl+cmd+D, but it seems I have to press fm+ctrl+cmd+d 
<img width="363" alt="bildschirmfoto 2018-10-09 um 15 27 36" src="https://user-images.githubusercontent.com/465632/46672569-11fd7d80-cbd8-11e8-888e-95026ac5f0fd.png">

I'm on macOS - I checked with both expanded qwerty layout and regular german QWERTZ layout... .  Happens regardless of weather the interface is german or english.

**Steps to reproduce:**

For exact steps -
-Start a blank project. 
-Hover over the "expand to fullscreen" button on the top right of the scene view, notice that it says that the shortcut is ctrl+cmd+D
-Try press them, notice that it does nothing
-Press fn+ctrl+cmd+D, notice it has the intended effect of maximizing the panel.

**Minimal reproduction project:**
Blank project should be enough to reproduce.

**Comment by Calinou** [comment] 2018-10-09 14:18
As far as I know, this is purely hardware-related: most laptops require holding the Fn key to use the function keys, otherwise the OS will intercept them (e.g. for tweaking display brightness).

**Comment by DiogoASTeixeira** [comment] 2018-11-16 11:04
Working on this issue, thinking about changing the shortcut to cmd+shift+D.

**Comment by akien-mga** [comment] 2018-12-17 09:56
Should be changed here: https://github.com/godotengine/godot/blob/ca90dd302b7ebff4ceb3ebc7070dc4c17d626ec0/editor/editor_node.cpp#L5151

It's a trivial change, but needs someone on macOS to actually find a better hotkey and ensure that it works/doesn't conflict with existing hotkeys.

**Comment by eliotpearson** [comment] 2021-01-02 16:45
Hi. Looks like this issue is fixed. Can this issue be closed?

![image](https://user-images.githubusercontent.com/1199317/103461964-01250f00-4cf0-11eb-8db3-39a9f6034332.png)

**Comment by Calinou** [comment] 2021-01-02 16:56
Closing per @eliotpearson's comment. Please comment if you can still reproduce this on Godot 3.2.3 or later.

**Closed by Calinou** 2021-01-02 16:56 UTC
Labels: enhancement, junior job, platform:macos, topic:editor, usability

**Comment by ingie** [comment] 2023-01-21 17:05
> Closing per @eliotpearson's comment. Please comment if you can still reproduce this on Godot 3.2.3 or later.

Still relevant in 3.5.1 - only saw 22883  after posting in https://github.com/godotengine/godot/issues/23548
