### ISSUE TITLE
Make Scene Root deletes other nodes from the scene

### ISSUE THREAD

**Issue by ondrowan** [godotengine/godot#24484] opened 2018-12-19 20:12 UTC
**Godot version:** 3.1 alpha 3

**OS/device including version:** Windows 10 64-bit

**Issue description:** Using "Make Scene Root" deletes other nodes from the scene.

**Steps to reproduce:**

Create any scene with one node. Instantiate it in some other scene. Create other random node in the first scene. Click "Make Scene Root". Everything looks good so far. Save the scene, switch to another scene, switch back to this scene and all other nodes but the root node are gone.

**Comment by ondrowan** [comment] 2018-12-20 13:55
I found another similar bug. I had a `Level1` scene inherited from generic `Level` scene. `Level1` scene had instances of `Player` and `HUD` which I decided to move to `Level` scene instead. After doing so, `Level1` scene showed `Player` and `HUD` twice, which was a bit confusing since I had no idea which one should I delete. It turns out that it considered both pairs of these nodes inherited from base `Level`.

Before:
![image](https://user-images.githubusercontent.com/423776/50288638-c92f3400-0466-11e9-8c4b-3158f89fff7f.png)

After:
![image](https://user-images.githubusercontent.com/423776/50288696-ebc14d00-0466-11e9-807b-862e59321ce6.png)

Duplicates disappeared after saving and playing the scene.

I think it's similar visual glitch as I described in original post. And it makes me question if it's visual glitch in that case as well and it should indeed be a destructive operation.

**Comment by bojidar-bg** [comment] 2018-12-21 09:55
@ondrowan Just to confirm: did the original issue (not the second post) happen in an inherited scene or in a normal scene?

**Comment by DualMatrix** [comment] 2018-12-22 13:41
> Create any scene with one node. Create other random node. Click "Make Scene Root". Everything looks good so far. Save the scene, switch to another scene, switch back to this scene and all other nodes but the root node are gone.

I can't get this to reproduce, do you have more detailed instructions?

**Comment by ondrowan** [comment] 2018-12-22 19:35
@bojidar-bg I tried it with normal scene.

@DualMatrix I just tried it on MacOS with both alpha 3 and alpha 4, and cannot reproduce it now as well. Unfortunatelly, I don't have access to a Windows computer (where I was able to reproduce it on several occasions) for another 2 weeks or so.

**Comment by ondrowan** [comment] 2018-12-22 20:05
@DualMatrix I replicated it in alpha 4 in the end, but didn't realize there's one more thing to be done. Given scene has to be instantiated in some other scene. I've updated original post.

**Comment by vinterskog** [comment] 2019-01-15 17:20
Ran into this bug today and lost some work. Should be high priority imho, this is scary...

**Comment by DualMatrix** [comment] 2019-01-15 22:00
> Given scene has to be instantiated in some other scene. 

Hmm that seems weird, wonder why that happens.

**Comment by DualMatrix** [comment] 2019-01-17 00:16
So I tested a bunch and I'm totally stuck as to what causes this, usually when a node dissapears from the tree it's because the owner wasn't set properly but I checked and that seemed to work fine in this case. 
It almost must have to do with it being an instance, since it only happens when you open a scene that instances it afterwards. 

Does anyone know of a property related to instancing that might not be transferred properly from the old to the new parent?

**Comment by ondrowan** [comment] 2019-01-20 19:45
@reduz I've just tried nightly build and the bug I've described in OP doesn't seem to be fixed. Nodes are still lost when changing parent of scene that's instantiated in other scene.

**Comment by reduz** [comment] 2019-01-22 16:50
There, now it forbids you to do it on inherited scenes too.

**Comment by bojidar-bg** [comment] 2019-03-16 11:34
Reopening then.

**Comment by Toiya** [comment] 2019-03-18 13:01
Just ran into this myself with Godot 3.1 stable and Ubuntu 18.04, and was not able to undo with CTRL + Z. I'm very much a beginner with both Godot and open source contributing, but if there's anything I can help out with, let me know!

**Comment by alvaromunoz** [comment] 2019-03-20 15:48
Just tested this on 3.1 windows 10 and the bug is still there. Here's a gif to show the problem:

![godot_node_problem](https://user-images.githubusercontent.com/2722773/54698596-53427380-4b0e-11e9-8229-03b061e8ef12.gif)

**Comment by earlroxas13** [comment] 2019-06-03 03:45
I also discovered this issue myself, days ago.

But notice after you save the instanced scene, you switch to another scene (that have that scene instanced), back to instance scene, the nodes will be deleted. BUT, do not save the scene now, instead revert it or reopen it. The nodes will be back.

**Comment by aspenforest** [comment] 2019-07-31 13:04
I'm having the same issue on 3.1.1 stable. This is hampering my work progress greatly. Please fix ASAP

**Closed** 2019-09-29 19:37 UTC
Labels: bug, high priority, topic:editor
