### ISSUE TITLE
Can't open Compatibility project easily, if changed to Forward+ or Mobile

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#72130] opened 2023-01-26 18:01 UTC
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 10 22H2, Compatibility, Geforce GTX 550 Ti

### Issue description

When the video card doesn't support Vulkan (in this case: `Geforce GTX 550 Ti`)
If an existing project with renderer `Compatibility`,
is switched to `Forward+` or `Mobile` from inside the project.
Then it can't be opened again “easily”.

### Steps to reproduce

With a video card that doesn't support Vulkan (in this case: `Geforce GTX 550 Ti`)
- Create a new project with the renderer: `Compatibility`
- In the project, change the renderer in Godot's top right corner
- To either `Forward+` or `Mobile`
- On the `Please Confirm...` dialog
- Click on `Save & Restart`
- Godot restarts and shows the dialog:
>Unable to initialize Vulkan video driver
Your video card driver seem not to support the required Vulkan version.
...

- Clicking `OK` closes Godot
- Trying to open the project again, shows the same `not supported` message, and `OK` closes Godot.

### Expected
Maybe the `Your video card driver seem not to support the required Vulkan version.` message 
should be shown before one can click on `Save & Restart`.

Possibly with a message that it's recommended to stay with the `Compatibility` renderer,
since Vulkan doesn't seem to be supported.

Currently, the dialog only says:
>Please Confirm...
Changing the renderer requires restarting the editor.

With two buttons: `Save & Restart` and `Cancel`

The message and renderer choice should probably also be shown when the project is opened,
if one "accidentally" or too quickly clicked on `Save & Restart` without reading.

I don't know if it would be useful in any other case. 
But maybe there could be an option to change an existing project's renderer in the `Project Manager`.

## Workaround to restore the `Compatibility` renderer
- start Godot with: `Godot_v4.0-beta15_win64.exe --rendering-driver opengl3`
- open the project
- change the top right renderer to `Compatibility` and choose `Save & Restart`
this appends the following to the end of `project.godot`
```
[rendering]

renderer/rendering_method="gl_compatibility"
```

Or modify `project.godot` directly and add the lines above.

Now the project can be opened again without starting Godot with the argument `--rendering-driver opengl3`

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment] 2023-01-26 18:05
Should be opened on proposal repo instead, but I'll save you some clicks and say this is related to https://github.com/godotengine/godot-proposals/issues/6084 and dupe of https://github.com/godotengine/godot/issues/58927

**Comment by clayjohn** [comment] 2023-01-26 18:15
Duplicate of https://github.com/godotengine/godot/issues/58927

**Closed by clayjohn** 2023-01-26 18:15 UTC
