### ISSUE TITLE
Inspector Hints clip too much of their content for multi-window mode

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#63347] opened 2022-07-23 14:17 UTC
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

archlinux 5.18.9-zen1-1-zen x86_64 Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere Micro-Star International Co., Ltd. [MSI] Radeon RX 580 Armor 4G OC amdgpu

### Issue description

Inspector Hints have their content erroneously clipped when the editor is not in single window mode. The most common experience I've had being:
![overclipped tooltip](https://user-images.githubusercontent.com/4315446/180608241-18f887f1-146d-41fc-8c33-b02eefe4292b.png)
It also does not seem to account for wrapped text or multi-line text.

And this is what happens even to project settings which may lack content:
![overclipped tooltip 2](https://user-images.githubusercontent.com/4315446/180608570-9568518f-0af6-4362-86be-9b1744e066be.png)
The second one is hard to see but it appears that the lack of a border at the bottom means that its still erroneously clipping.

### Steps to reproduce

1. Make a new project
2. Ensure Editor->Editor Settings->interface/editor/single_window_mode is set to false
3. Add a Node to the SceneTree
4. Hover over a node property

**Comment by Calinou** [comment] 2022-07-23 20:42
Duplicate of https://github.com/godotengine/godot/issues/61712.

**Closed by Calinou** 2022-07-23 20:42 UTC
