### ISSUE TITLE
an universal node able to toggle the visibility of its children

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5314] opened 2016-06-20 14:15 UTC
**Operating system or device - Godot version:**
Official 2.0.3stable win64

**Issue description** (what happened, and what was expected):

Let's imagine I have a branch in my tree that mixes 2D, 3D and Control nodes.

If the parent node is a 3D node and if I hide it, then only 3D children will be hidden too. All other 2D and Control children will remain visible.

It could be handy  to have an "universal" Node that could hide/show its children even if they are of an other type.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment] 2016-06-20 14:19
How about `Node`? :)
More seriously, it sounds like a bug if hiding a parent node does not hide its children, it should not be dependent on their node type IMO.

**Comment by SuperUserNameMan** [comment] 2016-06-20 14:25
Yeah, I first thought that `Node` would be what I needed, but it does not have visibility methods.
Also, I don't think it would wise to add them to it, because `Node` is used as base class for special nodes like `AnimationPlayer`, `EditorPlugin`, `SamplePlayer`, etc which does not need visibility toggle.

As for wether it is a bug or not, I think it was already working like this in 1.0.

**Comment by SuperUserNameMan** [comment] 2016-06-20 14:30
Or maybe, instead of a "universal node", there could be "inherit visibility state from parent node" added to `Spatial` and `CanvasItem` ?

**Comment by punto-** [comment] 2016-06-20 14:44
Both CanvasItem and Spatial have a NOTIFICATION_VISIBILITY_CHANGED, but
they have different values :p

**Comment by akien-mga** [comment] 2016-06-20 14:54
Hm indeed:
- Spatial: https://github.com/godotengine/godot/blob/0dfc4a2029e7a39ce521cc81da94fdaf73341ab2/scene/3d/spatial.h#L133-L140
- CanvasItem: https://github.com/godotengine/godot/blob/d4359b2d09625695a972a40ce76faf90b38f4e59/scene/2d/canvas_item.h#L167-L176
- Control (commented out, as it inherits CanvasItem, so should be dropped): https://github.com/godotengine/godot/blob/55b83157e70a34a933a2a73f14a0052a832d0287/scene/gui/control.h#L215-L228

**Comment by akien-mga** [comment] 2016-06-20 15:12
Discussed this a bit on IRC with @reduz:
```
[17:05] <reduz> Akien, i can't see how that is a bug, and much less an useful feature
[17:06] <Akien> reduz: Well if you hide a node, all its children should be hidden no?
[17:06] <reduz> all the children of the same type
[17:07] <reduz> 3D and 2D functions are not supposed to be mixed like this, I think that's more confusing than helping if it happens
[17:08] <reduz> IMO It's safer to assume that there is no relation between 2D and 3D to understand how they work
[17:08] <reduz> and given this is a very very special case, it should be handled as such with a custom script
[17:09] <Akien> I don't have much experience with 3D, so I might be mistaken. I was supposing that one would want Control children of Spatial nodes to be hidden
[17:10] <Akien> e.g. a kind of icon overlay on top of a 3D character
[17:10] <Akien> But I guess such GUI elements don't work like that in 3D :)
[17:10] <reduz> yeah, they are completely unrealted
[17:10] <reduz> you need to put a viewport to show GUI elements in 3D
```

@SuperUserNameMan Could you give an example of why you want this feature?

**Comment by SuperUserNameMan** [comment] 2016-06-20 15:30
@akien-mga :
Sure.

I need to be able to switch between different branches that each contains a different User Interface and a different 3D or 2D content.

````
Root:Node
    + BranchA:UniversalNode
        + 3dContent:Spatial
        + 2dContent:Node2D
        + UI:Control
    + BranchB:UniversalNode
        + 3dContent:Spatial
        + 2dContent:Node2D
        + UI:Control
    + BranchC:UniversalNode
        + 3dContent:Spatial
        + 2dContent:Node2D
        + UI:Control
````

Only one branch is visible at a time, and the content of other hidden branch are paused.

None of the branches share a common 3d or 2d content or a common UI.
They only share the root script.


And indeed, my current workaround is to use a simple `Node` with a custom script :
````
extends Node

export var visible = true;

func set_hidden(state): #{
	visible = not state;
	for child in get_children(): #{
		if child.has_method("set_hidden"): #{
			child.set_hidden(state);
		#}
	#}
#}

func _ready(): #{
	set_hidden(not visible);
#}
````
... but it is only useful at runtime. Not into the editor.

**Comment by kubecz3k** [comment] 2016-06-20 16:07
@SuperUserNameMan you can add tool keyword on the top, as well as setters/getters to `visible` (and restart the editor if you are on stable 2.0.x), and then this should work in editor as well.

**Comment by SuperUserNameMan** [comment] 2016-06-20 16:25
@kubecz3k : great thanks !
When I tried the `tool` mode and `setget` before, I did not think i had to restart the editor... so it did not work. 
But now it works :+1:

**Comment by vnen** [comment] 2016-06-20 17:05
With the plugin system in 2.1 you can create a custom Node type that has such functionality.

**Comment by TheoXD** [comment] 2016-06-20 19:13
No more nodes please, unless absolutely necessary.

**Comment by kubecz3k** [comment] 2016-06-21 07:49
Not sure what next with this issue, from what reduz said, how it works currently is a design decision and not a bug (seems fine for me)... @SuperUserNameMan are you happy with your current approach?

**Comment by Warlaan** [comment] 2016-06-21 15:06
If you only want one of the three branches to be active at a time, why don't you create a node that contains all three as references but only attaches one of them as a child at a time?
As long as you don't have to change the visibility very often it might even be better for the performance to detach nodes from the tree rather than hide them.

**Comment by SuperUserNameMan** [comment] 2016-06-21 16:21
@Warlaan : yeah that could be an other solution. I'm not really concerned about performance in this case, but I'll try it if I find that my current approach appears to be less adapted.

@kubecz3k : well, the scripted approach works so far. So I'm not sad.
As for this issue, I did not consider it as bug. The "universal node" was a feature proposal.
If i'm the only creature of the universe to think it could have been a handy feature to add, I'm okay with that.

**Comment by kubecz3k** [comment] 2016-06-21 16:42
@SuperUserNameMan Well I don't think you are the only one, but since only some smaller % of projects will need to use this I think it's great candidate for small yet nice plugin for upcoming asset sharing platform :)

**Comment by trollworkout** [comment] 2016-06-22 07:13
Use Node2D as a parent for 2D components and Spatial as a parent for 3D components and don't mix 2D and 3D. It will work fine.   Also as a general rule I don't use generic Node as a parent to 2D or 3D nodes because Node is pretty limited and generic misses position or rotation can't be translated etc.

**Comment by AlexHolly** [comment] 2016-06-24 00:01
@kubecz3k thanks, I was looking for this feature and was about to open an issue.
I tried the same approach as SuperUserNameMan but did not restart the editor.

Is it a bug that a print inside the setter is not showing in the output(tool/editor mode)?

**Comment by kubecz3k** [comment] 2016-06-26 09:57
@AlexHolly I think it's more a design decision than something else. Know for sure that CoreDevs are aware of this fact and it will be addressed at some point. Think I will close this issue, since we all know how to do this stuff at this moment, and with release of 2.1 it will be possible for community to create very simple plugin and share it with ease with other users :)

**Closed by kubecz3k** 2016-06-26 09:57 UTC
Labels: feature proposal, topic:core

**Comment by ericsnekbytes** [comment] 2025-02-16 01:57
My weapons are CharacterBody3D's, and their HUDs (ammo/bullet pip display) are child Control nodes. It makes sense that a weapon and its bullet count/HUD would be together in one tree, so I find it frustrating that hiding my weapon node does not hide its UI children :(

**Comment by arnaucmd** [comment] 2025-07-18 15:29
maybe this is too old but I have the same issue with godot 4.4, basically I toggle a 3d node and nothing happens to the ui nodes... is there any simple workaround?
