### ISSUE TITLE
String::replace_first is not exposed in gdscript

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#34513] opened 2019-12-21 14:24 UTC
**Godot version:**
3.2 beta 4

**Issue description:**
String::replace_first is not exposed in gdscript. This function would be useful when working with strings. 
Also the docs don't explain what is the difference between String::replace and String::replacen

**Comment by KoBeWi** [comment] 2019-12-21 15:34
Duplicate of #33308

**Closed by KoBeWi** 2019-12-21 15:34 UTC
