### ISSUE TITLE
Vulkan: Incorrect glTF mesh rendering due to automatic LOD kicking in too early with scaled bones

### ISSUE THREAD

**Issue by m1ntkat** [godotengine/godot#57895] opened 2022-02-10 03:16 UTC
### Godot version

4.0 Alpha 2

### System information

Windows 11, Vulkan, AMD Radeon RX 5700 XT

### Issue description

![Screenshot 2022-02-09 175650](https://user-images.githubusercontent.com/85989407/153330339-270b03e9-bf6f-49b9-bd0f-a33133355102.png)
![Screenshot 2022-02-09 175628](https://user-images.githubusercontent.com/85989407/153330347-5ea25c76-f176-4df1-9ca3-d0663ea1a90e.png)

### Steps to reproduce

Import a GLTF Mesh into a 3D Scene

### Minimal reproduction project

(https://drive.google.com/file/d/1-CfrKX1gIe6pAInUdzXSVZg63TRjLkzU/view?usp=sharing)

**Comment by fire** [comment] 2022-02-10 05:04
The Google drive is not public.

**Comment by mrjustaguy** [comment] 2022-02-10 12:19
This is Mesh LOD related.

**Comment by Calinou** [comment] 2022-02-10 17:54
As a workaround, set `rendering/mesh_lod/lod_change/threshold_pixels` to `0.0` in the Project Settings to disable the rendering of automatic mesh LOD. To disable LOD temporarily in the editor, click the **Perspective** menu in the top-left corner of the 3D viewport and select **Display Advanced… > Disable LOD**. You can also use the **Display Wireframe** debug draw mode to check how different LOD levels look.

You can also disable LOD generation on specifc imported 3D scenes in the Import dock:

![image](https://user-images.githubusercontent.com/180032/152448816-96adf247-bf95-47a0-a175-cc1ee7953046.png)

**Comment by Calinou** [comment] 2022-02-12 01:52
Reopening, as this issue should still be fixed :slightly_smiling_face: 

I can confirm this on `master` a0558b8af. All the LOD settings are at their default, so I don't know why this is happening. Object scales are also set to their defaults, though I don't know if you used a very large (or small) scale in your 3D DCC (such as Blender) for the character model. cc @fire 

For easier reproduction, I edited the MRP to only include essential files: [Mesh Rendering Bug_1.zip](https://github.com/godotengine/godot/files/8052510/Mesh.Rendering.Bug_1.zip)

**Comment by reduz** [comment] 2022-02-12 10:39
@JFonS

**Comment by fire** [comment] 2022-02-12 11:41
The scale is weird.

![editor_screenshot_2022-02-12T034043](https://user-images.githubusercontent.com/32321/153709804-6b765c71-b119-4a3e-8804-5703c73ef977.png)

The skeleton has a 0.01 scale node and then the skins are 100 times bigger.

**Comment by Zireael07** [comment] 2022-02-12 13:27
@fire: I had some meshes like that - I had to manually change scales and/or reexport, a quirk of export/import from Blender maybe?

**Comment by akien-mga** [comment] 2022-03-18 20:46
As per https://github.com/godotengine/godot/pull/59147#issuecomment-1072778167 it seems the problem might be a bug in the mesh itself.

**Comment by Calinou** [comment] 2022-03-18 21:00
Is there a way to detect such meshes and warn on import that the mesh itself should be fixed?

**Comment by fire** [comment] 2022-03-19 05:11
Typically I see this problem happen when the scale is different from Vector(1,1,1). Maybe warn on this. Sign is important too.

**Comment by reduz** [comment] 2022-04-02 13:32
Maybe we could detect a scale in the armature and apply this to the LOD process, or apply the armature before doing the LOD? (since we mostly care about the resulting indices anyway).

**Comment by mrjustaguy** [comment] 2022-04-02 13:49
The problem is probably with the AABB being incorrect for skinned meshes when any scaling/rotation/translation is done on the bones, be it rest or pose. This is why it's aggressively scaling, because the AABB it's using to determine scale is tiny compared to the mesh.

I've noticed this when I was working with MakeHuman Rigged meshes with the wrong settings used on export that caused the AABB to be rotated by 90 degrees and 10x smaller compared to what it actually was.. Fixing said settings on export fixed the rig so that it wasn't scaled and rotated anymore, and suddenly ALOD was working fine. the LOD meshes haven't changed, just their sensitivity.

**Comment by fire** [comment] 2022-06-15 13:36
May be resolved by https://github.com/godotengine/godot/pull/60115.

**Comment by nathanfranke** [comment] 2022-09-14 14:28
Was this resolved in https://github.com/godotengine/godot/pull/65493?

**Comment by clayjohn** [comment] 2022-09-14 16:26
> Was this resolved in https://github.com/godotengine/godot/pull/65493?

@fire says it does in https://github.com/godotengine/godot/pull/65493#issuecomment-1240199556

Closing as fixed by #65493

**Closed by clayjohn** 2022-09-14 16:26 UTC
Labels: bug, topic:rendering, confirmed, topic:import, regression, topic:3d

**Comment by fire** [comment] 2022-09-14 17:57
I tested #65493 and manually confirmed it is fixed.
