### ISSUE TITLE
Variable refresh rate (VRR) monitor constantly changes hertz while in Godot Editor (or when low-processor mode is enabled)

### ISSUE THREAD

**Issue by Cavas85** [godotengine/godot#38219] opened 2020-04-26 10:23 UTC
Hi Community!

I'm new to Godot and doing my first Tutorial Course. I experienced a problem using Godot that's a bit annoying. While in editor, writing code, my monitor changes the hertz vom 144Hz (normal in Desktop) down to 40Hz. Sometimes it stays at 40, sometimes it changes constantly to numbers somewhere between 40 and 144hz. The problem for me is, that the picture starts flickering (like changing contrast every frame) and thats really distracting. Problem occurs not always, but when working with sprites the problem is more common.

Godot Version 3.2.1
Win 10 Enterprise, Ver. 1909 (Build 18363.778)
Monitor: Asus VG279
Driver: Geforce Game Ready v.445.87

Till now, I only saw this in Godot. But my Monitor is new, so this means nothing. Has anybody suggestions on this issue?

**Comment by Calinou** [comment] 2020-04-26 11:04
Is this a G-Sync or FreeSync monitor?

**Comment by lawnjelly** [comment] 2020-04-26 12:36
Could this be a problem with the monitor / OS? An app shouldn't be able to cause things like changing contrast between frames, most apps (as opposed to games) only do screen updates when something changes.

The only other thing I can think of is that Vsync via compositor setting, but I'm assuming you've got that off (default).

**Comment by Cavas85** [comment] 2020-04-26 18:47
Adaptive-Sync (FreeSync), but G-Sync is activated
RTX 2070 Super

@Calinou I think "Update Continuously" enabled fixed the problem! The worst hz-drop now is down to (just) 130Hz - no more flickering.

@lawnjelly It just looks like the monitor is adjusting contrast. The flickering is so recognizable, because most part of the picture (the editor) is the same color and does not change (just typing code or moving the mouse). But sometimes the monitor goes down to 40Hz, than the picture is really bad. Like watching a video of an old CRT monitor. Maybe thats just what it looks like when the monitor adjusts the hz-rate every second or so. I hope this description is somehow understandable :-D

Not sure about the v-Sync thing. If you mean the settings in the **Nvidia Control Panel / 3D Settings / Manage 3D Settings / VSync** was on "use 3D application setting". No difference if i turn it to "off".

As said - looks like the advice of Calinou fixed it. Thanks for your time!

**Comment by jitspoe** [comment] 2020-10-16 00:39
Seems this may not be just an editor issue.  Somebody reported having flickering issues with freesync enabled in a release build of a game I'm working on.

**Comment by Calinou** [comment] 2020-10-16 06:43
@jitspoe I don't see a reason for this occuring in a project that doesn't use the low-processor mode (which is disabled by default outside the editor).

**Comment by lawnjelly** [comment] 2020-10-16 08:09
https://www.google.com/search?q=freesync+flicker

Is this a description of the problem?
https://www.displayninja.com/what-is-freesync-brightness-flickering/

This does not sounds like a problem with Godot. We just provide frames. No guarantee is made about the regularity of frames. It is the OS / driver / GPU / monitor job to display them.

If it can't do that, I'd be taking it back to the shop personally lol. :grin:

**Comment by Calinou** [comment] 2022-01-24 01:27
Can anyone reproduce this on a [4.0 nightly build](https://hugo.pro/projects/godot-builds/) to see if this is fixed by the DisplayServer refactoring?

**Comment by komerdoor** [comment] 2022-02-27 15:24
> Can anyone reproduce this on a [4.0 nightly build](https://hugo.pro/projects/godot-builds/) to see if this is fixed by the DisplayServer refactoring?
> 
> Also, does anyone know how other applications (such as Blender) manage to avoid this bug without forcing constant redrawing?

Still happening in 4.0 latest nightly on my NVidia 2080s and LG TV and enabling VRR at 119. It drops down to 40hz.

**Comment by komerdoor** [comment] 2022-02-27 16:59
Setting Monitor Technology to Fixed Refresh in the NVidia Control Panel fixed it, without having to enable Update Continuously:
![image](https://user-images.githubusercontent.com/6968133/155891814-8970f57a-107f-4977-8205-4a63aa5a5226.png)

**Comment by HybridEidolon** [comment] 2022-10-01 03:52
Observing this both in editors and at runtime in Godot 4 beta 2 and Godot 3.5.1 using the latest nvidia driver for a gtx 1080. The sync behavior is totally wrong, in all renderers in both versions.

**Comment by Calinou** [comment] 2022-10-01 15:43
Windows (or the NVIDIA Control Panel) should allow you to allow whether VRR affects only exclusive fullscreen apps, or both windowed (+ borderless fullscreen) and exclusive fullscreen apps.

**Comment by HybridEidolon** [comment] 2022-10-02 21:04
Bummer, that's really disappointing. Although, for the DXGI path, does that just require Vulkan to render to surfaces obtained from a DXGI swapchain instead of a VK_KHR_swapchain, and present from DXGI side? That doesn't sound like it'd be too hard to write at least, even without the d3d12 backend.

**Comment by Calinou** [comment] 2022-10-02 23:08
> Although, for the DXGI path, does that just require Vulkan to render to surfaces obtained from a DXGI swapchain instead of a VK_KHR_swapchain, and present from DXGI side? That doesn't sound like it'd be too hard to write at least, even without the d3d12 backend.

I assume it requires the DirectX SDK to be installed at build-time, which has two problems:

- Requires Visual Studio and DirectX SDK to be installed to compile Godot (it's huge).
- Can't compile using MinGW.

**Comment by HybridEidolon** [comment] 2022-10-07 04:28
For reference, [this](https://github.com/krOoze/Hello_Triangle/tree/dxgi_interop) is a Hello World sample which uses DXGI 1.6 swapchain to present while rendering with Vulkan to the same images, which is likely the same approach used by Doom Eternal as mentioned.

A cursory glance at the code indicates the use of d3d12.h and dxgi1_6.h from the Windows 10 SDK. However, [equivalent headers are available under MinGW](https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/include/dxgi1_6.h), so they can be linked against the system d3d12/dxgi.dll. I'd think this would be possible to support without any additional SDK downloads for either compiler since it wouldn't rely on the DirectX shader compiler at all, unlike the full d3d12 driver.

**Comment by russeg** [comment] 2022-12-24 09:49
I have an NVIDIA card with FreeSync monitor, and 3 solutions that worked for me:

1. Enable **Update Continuously**, or
2. In the NVIDIA Control Panel, set Monitor Technology to "**Fixed Refresh**" for Godot executable, or
3. In the NVIDIA Control Panel, G-SYNC to "**Enable for full screen**"  or unchecked

All worked, but I chose 3 because it also fixes other window stutter in Netlimiter and LibreOffice (and maybe some others) without adding their executables.

**Comment by Calinou** [comment] 2023-01-13 16:56
Note that if you're using an OLED display, using the [Black (OLED](https://github.com/godotengine/godot/issues/38219) editor theme preset should mitigate this as fully black areas of an OLED display aren't affected by VRR flicker (which happens because the gamma curve changes slightly depending on the effective refresh rate).

**Comment by northmatt** [comment] 2024-02-03 03:13
Figured I might as well add some info to get around Nvidia's broken VRR driver settings.

Some of you may have noted that the driver settings based fixes here dont work as well now. **Fullscreen Only** option tends to apply to a whole bunch of windowed programs now, including Godot. As well as the per program **Fixed Refresh** option tends to turn VRR off for the entire display when said program is focused, causing 3+ second blackouts with alt tabbing or running the cursor over said program and other programs.

Only have a good fix for the latter problem rather than both unfortunately. Need to download **Nvidia Profile Inspector**, make a new profile for Godot (or preferably a general No VRR one), set **GSYNC - Application State** to **Disallow**, then add your desired executables to the profile.

**Comment by latenssi** [comment] 2024-03-06 17:03
I also had this issue but I got it solved by just setting **"Preferred refresh rate"** to **"Highest available"** for the Godot executable in the NVIDIA Control Panel and leaving everything else as is.

![image](https://github.com/godotengine/godot/assets/1526792/ac391316-0448-4d29-8b68-ce5711647ad5)

For completeness, all NVIDIA Control Panel global 3D settings are on default and I have G-Sync enabled only for full screen mode.

**Closed** 2024-07-19 09:17 UTC
Labels: bug, topic:core, topic:editor, confirmed
