### ISSUE TITLE
Eye Icon Button is not working Godot 2.1.5 rc (regression)

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#17722] opened 2018-03-23 16:24 UTC
*Bugsquad (@Noshyaar) edit:* additional details, formatting

**OS/Godot Version:** Arch Linux, 2.1.5-beta2, 2.1.5-rc

**Issue details:**

Expected: Clicking on the button hides the node, the eye shuts.
Happened: Printed "Toggle Visible", node stays visible, the eye doesn't shut.

Using Property Editor to uncheck `visibility` still works

**Reproduction steps:**
1. New spatial node
2. Click the eye, it will not shut, node stays visible.

![peek 2018-03-24 22-05](https://user-images.githubusercontent.com/26753932/37865474-86aa8846-2faf-11e8-9c1f-9a8fefc1ff47.gif)

---

<Details>
**Godot version:**
git br
* 2.1
  3.0
  master
godot $ cat version.py
short_name = "godot"
name = "Godot Engine"
major = 2
minor = 1
patch = 5
status = "rc"

**OS/device including version:**
ArchLinux

**Issue description:**
eye icon button is not working

**Steps to reproduce:**
You can play with the eye icon button in your project is not working. This eye icon button is for node visibility in your current scene.

![eye_icon](https://user-images.githubusercontent.com/24534/37840853-c4987c4e-2e83-11e8-910d-58c8ab1a8a38.png)
</Details>

**Comment by akien-mga** [comment] 2018-03-23 16:54
Can you be more specific about what you do, and what's the behaviour (as well as the behaviour you would expect)?

For me it works fine, pressing the eye icon turns off the visibility:
![screenshot_20180323_175357](https://user-images.githubusercontent.com/4701338/37842721-2c50947c-2ec3-11e8-95a0-682a9d6d2dfd.png)

![screenshot_20180323_175419](https://user-images.githubusercontent.com/4701338/37842731-368b2be6-2ec3-11e8-960e-aee240cbc8ab.png)

**Comment by girng** [comment] 2018-03-23 19:34
lol, this is because you have  a 2d node under a 3d one. if you disable the 3d node, the 2d won't be hidden with it

add your 2d node under a canvas layer

**Comment by gerardogc2378** [comment] 2018-03-23 20:20
Yes, thanks, I remember the colors :-), but what about this 3d scene:

![3d-scene](https://user-images.githubusercontent.com/24534/37851600-269ef046-2ea5-11e8-9036-3c1309190509.png)


It's not working :-(

**Comment by girng** [comment] 2018-03-23 21:27
what do you mean "not working"? as akien said, is it the actual button not being clicked, or when you click the eye icon it's not doing what you want? little more specific please

**Comment by gerardogc2378** [comment] 2018-03-24 00:13
When you clicked the eye icon button, this is not working, this icon is for visibility :-) right? Sorry if I was incomplete for details.

**Comment by akien-mga** [comment] 2018-03-24 11:18
Can you provide an example project where it's not working? I still don't understand what's not working.

**Comment by gerardogc2378** [comment] 2018-03-24 14:41
Let me be more specific

![eye-icon](https://user-images.githubusercontent.com/24534/37865183-85249780-2f3e-11e8-9f11-bb13a7c34b3b.png)

This little button is not working, I mean when you click this button, this shows or hides the current node in your current scene :-)

**Comment by Noshyaar** [comment] 2018-03-24 14:44
Can confirm on 2.1.5 beta2
- It happens only with Spatial nodes
- Using Property Editor to uncheck `visibility` still works

**Comment by akien-mga** [comment] 2018-03-24 15:34
Thanks for the details, I can reproduce it too now. It worked fine in 2.1.4 so it's a regression.

**Comment by akien-mga** [comment] 2018-03-24 15:51
That's a regression from #15239, ping @sersoong.

**Comment by akien-mga** [comment] 2018-03-24 15:59
Fixed by 3764cf6.

**Closed by akien-mga** 2018-03-24 15:59 UTC
Labels: bug, confirmed, topic:editor

**Comment by gerardogc2378** [comment] 2018-03-24 18:21
FIXED!!! Thanks everyone, I am happy again :-P

**Comment by sersoong** [comment] 2018-03-29 12:35
A terrible logical error.
Sorry for that.
![001](https://user-images.githubusercontent.com/24988459/38089057-baf750d6-3390-11e8-808b-8114813264b4.gif)

**Comment by sersoong** [comment] 2018-03-29 14:24
How about master branch?
Does it have the same problem？
