### ISSUE TITLE
Auto-completion together with autoloads

### ISSUE THREAD

**Issue by tufduckhotmailcom** [godotengine/godot#76402] opened 2023-04-24 13:09 UTC
### Godot version

4.0.2 rc1

### System information

Windows 10

### Issue description

In my projects, I often have a `Common.gd` as autoload and store references to my classes in there. For instance, I have a `var game_ref: Game` in my autoload, and then I can just call `some_method_in_game()` by typing

`Common.game_ref.some_method_in_game()` from anywhere in my code.

But I have noticed that auto-completion cannot fetch `some_method_in_game()`, unless I specifically cast game_ref to Game. This is an issue with variables in auto-loads, autocompletion for classes in the same script file works.

See these examples:

1. Auto-completion works as intended here, when I don't use autoloads.
![works](https://user-images.githubusercontent.com/99537319/234002720-24f14b9c-51fa-47d3-bce2-fbe2ded6d6dc.png)

2. This does not work, some_method_in_game() does not show up.
![does not work](https://user-images.githubusercontent.com/99537319/234002883-94016092-f042-43d8-9c1a-8b68a0fa5e09.png)

3. If I cast it, it works. 
![works with cast](https://user-images.githubusercontent.com/99537319/234002948-fb1c9635-bcec-4ce6-a7d3-b14ea31e94a9.png)

My game_ref variable is static typed in Common.gd.

![autoload](https://user-images.githubusercontent.com/99537319/234003556-46c2fe8e-d310-4359-b752-f70b387f0444.png)

I would like autocompletion to work with autoloads without having to cast the variable. This shouldn't be necessary since the variable already is static typed with the correct class type.

### Steps to reproduce

See issue description.

### Minimal reproduction project

[Demo.zip](https://github.com/godotengine/godot/files/11310667/Demo.zip)

**Comment by Calinou** [comment] 2023-04-24 14:33
- Duplicate of https://github.com/godotengine/godot/issues/74058.

**Closed by Calinou** 2023-04-24 14:33 UTC
