### ISSUE TITLE
Control Clip Content only clips visually

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#18294] opened 2018-04-19 12:37 UTC
**Godot version:**
Godot 3.0.2-stable

**Issue description:**
If a control node clips a child button, the button is still click-able outside of the parent rect.
The button is visually clipped correct, but it is still there and can be clicked, which it shouldn't in my opinion.

On the other hand, if you use a ScrollContainer, it will clip content "correct".

**Steps to reproduce:**
1. Create a Control node
2. Added a button as a child to the Control node, and make it bigger than the Control node.
3. Set clip content on the Control node
4. Run the game and press the button outside of the Control nodes size

Or download my example project.
Try and change the 'Container' node to a ScrollContainer and it has the expected behaviour.

**Minimal reproduction project:**
[ClipContentTest.tar.gz](https://github.com/godotengine/godot/files/1928089/ClipContentTest.tar.gz)

**Comment by KoBeWi** [comment] 2019-04-18 21:54
Looks like duplicate of much older issue: #5172

**Comment by cjmxp** [comment] 2019-04-24 07:17
The problems discovered in 2016 are still unrepaired today.

**Comment by Calinou** [comment] 2019-04-24 11:27
Duplicate of https://github.com/godotengine/godot/issues/5172.

**Closed by Calinou** 2019-04-24 11:27 UTC
Labels: bug, topic:core
