### ISSUE TITLE
Collision mask animation does not work

### ISSUE THREAD

**Issue by Ironsx** [godotengine/godot#23868] opened 2018-11-21 10:05 UTC
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
If you have an animation with one track relative to Collision Mask to activate/deactivate one flag over time, this does not work.
If you play this animation in the Animation console then it runs, but it does not run at runtime...

**Steps to reproduce:**
1) Create a new animation in the AnimationPlayer node of a character (KinematicBody2D in my case)
2) Add a new track with Mask Collision
3) Change it over time at least two times
4) Test it in the Animation Console. It works!
5) Now, Execute the game ant test it...

**Comment by bojidar-bg** [comment] 2018-11-21 15:41
A sample project exhibiting this issue would be welcome.
Did you try with the AnimationPlayer having process_mode=physics?

**Comment by Ironsx** [comment] 2018-11-21 19:14
I have tried today with your solution and it works. Thanks so much!
What worries me is that I tried again like yesterday (Animation idle mode) and today it works...
Thinking now about this it's as if yesterday Godot didn't take the changes I made to the animation, although I saved it several times to make sure...

**Comment by KoBeWi** [comment] 2020-06-29 16:06
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment] 2020-09-28 22:10
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Closed by KoBeWi** 2020-09-28 22:10 UTC
Labels: bug, needs testing, topic:physics
