### ISSUE TITLE
C# cannot export array of PackedScene

### ISSUE THREAD

**Issue by firebelley** [godotengine/godot#70035] opened 2022-12-14 00:59 UTC
### Godot version

v4.0.beta8.mono.official [45cac42c0]

### System information

Windows 11

### Issue description

When I export an array of PackedScene like so:

```cs
[Export]
private PackedScene[] scenes;
```
After build, I am unable to select scenes in the editor and the following error is output:

```
modules/mono/glue/runtime_interop.cpp:1216 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.InvalidOperationException: The type is not supported for conversion to/from Variant: 'Godot.PackedScene[]'
     at Godot.NativeInterop.VariantUtils.GenericConversion`1.ToVariant(T& from) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs:line 17
     at Example.GetGodotPropertyDefaultValues() in C:\Users\Jake\Desktop\Export Array MRP\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\Example_ScriptPropertyDefVal.generated.cs:line 9
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(Type type, IntPtr scriptPtr, IntPtr addDefValFunc) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 927
```

Expected behavior is that exporting arrays works. Using `Godot.Collections.Array` works as expected.

Exporting arrays in the manner above worked in Beta 7.

### Steps to reproduce

1. Export PackedScene array in manner shown above
2. Build project
3. Observe error in output console

### Minimal reproduction project

[Export Array MRP.zip](https://github.com/godotengine/godot/files/10223237/Export.Array.MRP.zip)

**Comment by raulsntos** [comment] 2022-12-14 12:57
Duplicate of https://github.com/godotengine/godot/issues/69822
Should have been fixed by https://github.com/godotengine/godot/pull/69933

**Closed by raulsntos** 2022-12-14 12:57 UTC
