### ISSUE TITLE
Animation editor crash on selecting track key

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#99262] opened 2024-11-15 03:14 UTC
### Tested versions

master[673f396677654220d7e1d5b6fb5ed3b50126b4e6]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

https://github.com/user-attachments/assets/7af02a48-011a-442d-9a90-b88e75795649

### Steps to reproduce

look video

### Minimal reproduction project (MRP)

none

**Comment by PhairZ** [comment] 2024-11-15 08:01
Duplicate of #99249

**Closed** 2024-11-15 10:00 UTC
