### ISSUE TITLE
Drag'n'Drop nodes in scene to exported NodePath

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#6378] opened 2016-09-02 21:14 UTC
Would be awesome if it was possible to drop nodes from Scene Dock to exported NodePath property in Inspector Dock, like in Unity (sorry for saying that xDDD)

In current behavior user has to click property, click Assign, then Scene Tree Dialog shows up and user has to again find and select his node and click OK.

With d'n'd it would be to Lock Inspector on script node (? or any other idea) then find his nodes in 2D/3D view drag them to property in inspector. Done.

**Comment by RayKoopa** [comment] 2016-09-09 07:22
That was literally the first thing I tried before doing it the "manual" way.

**Comment by Hinsbart** [comment] 2016-10-04 21:39
duplicate of #2505

**Closed** 2016-10-04 21:52 UTC
Labels: archived, enhancement, topic:editor
