### ISSUE TITLE
Vulkan: PointLight2D not working with CanvasModulate

### ISSUE THREAD

**Issue by PetrVopa** [godotengine/godot#58688] opened 2022-03-02 16:46 UTC
### Godot version

4.0 alpha 3

### System information

Linux Mint Cinnamon 20.3 x86_64, GPU: nvidia geforce GTX 1650 mobile, Vulkan

### Issue description

Hello, I'm facing a problem with lighting in Godot 4, I'm trying to get my entire screen black (using CanvasModulate) and then using PointLight2d on it. Instead of "showing" the original texture of the background the light just draws its texture on top of "CanvasModulated" background
reddit post: https://www.reddit.com/r/godot/comments/t3fdq4/lightning_in_godot_4/hyxz41x/?context=3

### Steps to reproduce

Add sprite to the scene, add CanvasModulate, make it black and the add PointLight2D with a texture

### Minimal reproduction project

[lights.zip](https://github.com/godotengine/godot/files/8171299/lights.zip)

**Comment by aXu-AP** [comment] 2022-03-10 13:39
I just stumbled upon this bug myself. It seems that the more darker modulation is, the more washed out textures will be. I wonder if it's something like (in pseudocode)
```
color = texture
color *= canvasmodulate // If this is black result is black
color += light // If we readd light to black result doesn't have original color
```
That would explain why color information gets lost. I tried to search in source, and I feel this is what is going on (the shader code is quite convoluted so I couldn't 100% confirm what is happening).

**Comment by aXu-AP** [comment] 2022-04-28 17:46
Oh, sorry, that was pure speculation on my part. The actual computation is in the [canvas shader](https://github.com/godotengine/godot/blob/df4de306a9c20cf4d4e87c89b448ac71f7a31444/drivers/gles3/shaders/canvas.glsl) I believe. However, for my untrained eyes it's hard to read all that shader code and not be overwhelmed. It's quite complicated and covers wide array of cases.

**Comment by Calinou** [comment] 2022-08-21 19:53
Duplicate of https://github.com/godotengine/godot/issues/49922.

**Closed by Calinou** 2022-08-21 19:53 UTC
Labels: bug, topic:rendering, confirmed, regression, topic:2d
