### ISSUE TITLE
Ability to edit Editor Settings from Project Manager

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2771] opened 2015-11-11 14:49 UTC
It's a bummer that you have to open a project in order to edit the Editor Settings, since they're not related to any project.

**Comment by akien-mga** [comment] 2015-11-11 14:50
Good point.

**Comment by slapin** [comment] 2015-11-12 14:52
But these should be still accessible when project is open, too

**Comment by akien-mga** [comment] 2018-05-15 09:46
I've had a quick look at this. It's trivial enough to add a button in the project manager that spawns an `EditorSettingsDialog`, but the issue is that the latter is somewhat tied to editor-only API, so it crashes as there is no `EditorNode` in the project manager.

So to be able to show the editor settings in the project manager, some work should be done on `EditorSettingsDialog` to untie it from the editor (things like undo redo and `SectionedPropertyEditor` cause issues).

Here's a diff to get started if someone is interested:
```c++
diff --git a/editor/project_manager.cpp b/editor/project_manager.cpp
index 97d3a070a..a9e94e4ba 100644
--- a/editor/project_manager.cpp
+++ b/editor/project_manager.cpp
@@ -1504,6 +1504,7 @@ void ProjectManager::_bind_methods() {
 	ClassDB::bind_method("_install_project", &ProjectManager::_install_project);
 	ClassDB::bind_method("_files_dropped", &ProjectManager::_files_dropped);
 	ClassDB::bind_method("_open_asset_library", &ProjectManager::_open_asset_library);
+	ClassDB::bind_method("_open_editor_settings", &ProjectManager::_open_editor_settings);
 	ClassDB::bind_method(D_METHOD("_scan_multiple_folders", "files"), &ProjectManager::_scan_multiple_folders);
 }
 
@@ -1512,6 +1513,10 @@ void ProjectManager::_open_asset_library() {
 	tabs->set_current_tab(1);
 }
 
+void ProjectManager::_open_editor_settings() {
+	settings_config_dialog->popup_edit_settings(); // crashes on press
+}
+
 ProjectManager::ProjectManager() {
 
 	// load settings
@@ -1698,6 +1703,7 @@ ProjectManager::ProjectManager() {
 
 	tree_vb->add_spacer();
 
+	// AssetLib
 	if (StreamPeerSSL::is_available()) {
 		asset_library = memnew(EditorAssetLibrary(true));
 		asset_library->set_name(TTR("Templates"));
@@ -1711,6 +1717,16 @@ ProjectManager::ProjectManager() {
 	settings_hb->set_alignment(BoxContainer::ALIGN_END);
 	settings_hb->set_h_grow_direction(Control::GROW_DIRECTION_BEGIN);
 
+	// Editor Settings
+	settings_config_dialog = memnew(EditorSettingsDialog);
+	//gui_base->add_child(settings_config_dialog); // triggers crash
+
+	Button *settings_btn = memnew(Button);
+	settings_btn->set_text("Settings");
+	settings_hb->add_child(settings_btn);
+	settings_btn->connect("pressed", this, "_open_editor_settings");
+
+	// Language config
 	language_btn = memnew(OptionButton);
 
 	Vector<String> editor_languages;
diff --git a/editor/project_manager.h b/editor/project_manager.h
index a9d23b1f7..939af487a 100644
--- a/editor/project_manager.h
+++ b/editor/project_manager.h
@@ -32,6 +32,7 @@
 #define PROJECT_MANAGER_H
 
 #include "editor/plugins/asset_library_editor_plugin.h"
+#include "editor/settings_config_dialog.h"
 #include "scene/gui/dialogs.h"
 #include "scene/gui/file_dialog.h"
 #include "scene/gui/scroll_container.h"
@@ -52,6 +53,7 @@ class ProjectManager : public Control {
 	FileDialog *scan_dir;
 
 	EditorAssetLibrary *asset_library;
+	EditorSettingsDialog *settings_config_dialog;
 
 	ProjectListFilter *project_filter;
 
@@ -80,6 +82,7 @@ class ProjectManager : public Control {
 	ConfirmationDialog *open_templates;
 
 	void _open_asset_library();
+	void _open_editor_settings();
 	void _scan_projects();
 	void _run_project();
 	void _run_project_confirm();
diff --git a/editor/settings_config_dialog.cpp b/editor/settings_config_dialog.cpp
index c3e9e4ab6..0f8dce7b1 100644
--- a/editor/settings_config_dialog.cpp
+++ b/editor/settings_config_dialog.cpp
@@ -31,7 +31,8 @@
 #include "settings_config_dialog.h"
 
 #include "editor_file_system.h"
-#include "editor_node.h"
+//#include "editor_node.h"
+#include "editor_scale.h"
 #include "editor_settings.h"
 #include "os/keyboard.h"
 #include "project_settings.h"
@@ -136,7 +137,7 @@ void EditorSettingsDialog::_filter_shortcuts(const String &p_filter) {
 }
 
 void EditorSettingsDialog::_undo_redo_callback(void *p_self, const String &p_name) {
-	EditorNode::get_log()->add_message(p_name);
+	//EditorNode::get_log()->add_message(p_name);
 }
 
 void EditorSettingsDialog::_notification(int p_what) {
@@ -176,16 +177,16 @@ void EditorSettingsDialog::_unhandled_input(const Ref<InputEvent> &p_event) {
 
 			if (ED_IS_SHORTCUT("editor/undo", p_event)) {
 				String action = undo_redo->get_current_action_name();
-				if (action != "")
-					EditorNode::get_log()->add_message("UNDO: " + action);
+				//if (action != "")
+				//	EditorNode::get_log()->add_message("UNDO: " + action);
 				undo_redo->undo();
 				handled = true;
 			}
 			if (ED_IS_SHORTCUT("editor/redo", p_event)) {
 				undo_redo->redo();
 				String action = undo_redo->get_current_action_name();
-				if (action != "")
-					EditorNode::get_log()->add_message("REDO: " + action);
+				//if (action != "")
+				//	EditorNode::get_log()->add_message("REDO: " + action);
 				handled = true;
 			}
```

**Comment by akien-mga** [comment] 2018-05-15 11:06
I've had a quick chat with @reduz about this, and I think it would be too much work to uncouple the Editor Settings from `EditorNode`, so I'm closing this issue. It could be revisited if we decide to rewrite the Editor Settings logic in the future.
```
<Akien> BTW, I've had a quick look at making it possible to open the editor settings from the project manager, but it crashes as EditorSettingsDialog seems too tied to EditorNode (so far I saw issues with undo/redo and SectionedPropertyEditor)
<reduz> ah yeah its definitely not possible
<reduz> and even if opened, it may lose a lot of data if settings are changed
<reduz> i am not sure if there is a simple way to do it
<Akien> I think it might be doable to uncouple it from EditorNode, but yeah, I'm not sure it's worth the effort. It would be cool to have the editor settings in the project manager, but not if half of it needs to be rewritten and we lose functionality like undoredo in the editor :)
<reduz> Akien: the code that erases the settings not set while creating it should be disabled, else a lot of settings will be lost
<reduz> Akien: its the system that erases settings that were removed
<Akien> reduz: Ah right, because EditorNode defines many of them
<Akien> reduz: then yeah, I think it's just not worth it unless we decide to rewrite the whole system to register settings
```

**Closed by akien-mga** 2018-05-15 11:06 UTC
Labels: feature proposal, topic:editor, usability
