### ISSUE TITLE
4 errors print in the Godot console when opening a new or other compatibility project.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79830] opened 2023-07-23 16:09 UTC
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Opening any Godot 4.1.1 compatibility project (including new projects) with the Godot 4.1.1 editor causes those 4 errors to be printed in the Godot console:
```php
ERROR: Condition "!texture_allocs_cache.has(p_id)" is true.
   at: texture_free_data (drivers/gles3/storage/utilities.h:111)
ERROR: Cubemap Arrays are not supported in the GL Compatibility backend.
   at: (drivers/gles3/storage/texture_storage.cpp:763)
ERROR: Attempting to use an uninitialized RID
   at: (./core/templates/rid_owner.h:199)
ERROR: Condition "!t" is true.
   at: texture_free (drivers/gles3/storage/texture_storage.cpp:705)
```
I was not able to find their source in the editor settings.
The projects I used to test are new projects so I don't suspect them to be the cause.

I assume they may only happen with the compatibility compiler, as one of them mentions it.
I wasn't able to test other compilers because my hardware does not support them.

The errors do not cause any further problems for a project, but they can look confusing, especially for a new user.
### Steps to reproduce

0. Create a new compatibility project.
1. Open the project with Godot editor with console.
2. Check for the errors in the console.

### Minimal reproduction project

N/A

**Comment by Ybaedbaenn** [comment] 2023-07-23 16:11
I don't know if any of those errors are printed for other users loading projects.

Feel free to ask me for testing any specific thing that may be the cause of them occurring on my hardware.

**Comment by Ybaedbaenn** [comment] 2023-07-23 17:01
Additionally, I found out that closing the editor always yields one additional error:
```php
ERROR: 1 RID allocations of type 'N5GLES37TextureE' were leaked at exit.
```

**Closed** 2023-07-25 12:13 UTC
