### ISSUE TITLE
Exported base class Mono fields are not initialized on _Ready (3.1 RC1 Regression)

### ISSUE THREAD

**Issue by cart** [godotengine/godot#26811] opened 2019-03-09 01:14 UTC
**Godot version:**
3.1 RC1

**OS/device including version:**
Arch Linux

**Issue description:**
Base class [Export]-ed fields are no longer initialized when _Ready() is executed. This is a regression since beta 11 and makes the majority of my game's code break.

**Steps to reproduce:**
1. create a class with an [Export]-ed field (lets call it ClassA)
2. create another class that inherits from ClassA (lets call it ClassB)
3. create a node instance with ClassB as its script and assign the [Export]-ed field a value
4. lets assume the field's value is a NodePath. try accessing that NodePath in ClassB's _Ready function and observe that it is null.

**Minimal reproduction project:**
[InheritanceBreak.zip](https://github.com/godotengine/godot/files/2947939/InheritanceBreak.zip)

When run in RC1, the project above fails with a NullReferenceException. When run in Beta 11, it runs and prints the exported field's value.

**Comment by shartte** [comment] 2019-03-09 12:07
Opened a PR to fix it.

**Comment by akien-mga** [comment] 2019-03-09 13:00
Fixed by #26776.

**Closed by akien-mga** 2019-03-09 13:00 UTC
Labels: bug, high priority, topic:mono

**Comment by neikeq** [comment] 2019-03-09 13:06
I'm confused because @cart describes this as a regression. Yet, if this was fixed by #26776, then it should have never worked before.

**Comment by cart** [comment] 2019-03-09 19:09
All I can say is it definitely regressed in RC1 :smile: 

But the fix works beautifully. Thanks!

**Comment by neikeq** [comment] 2019-03-09 19:34
¯\_(ヅ)_/¯
