### ISSUE TITLE
When pressing play or build: a dotnet error try_get_path_from_dotnet_root on Linux Godot using C sharp  4.1.1

### ISSUE THREAD

**Issue by kepiz** [godotengine/godot#81682] opened 2023-09-15 07:28 UTC
### Godot version

4.1.1.stable.mono.official

### System information

Kubuntu

### Issue description

Pressing play on the editor brings up this error

```
E 0:00:00:0493   try_get_path_from_dotnet_root: The host fxr folder does not exist: /usr/share/dotnet/host/fxr
  <C++ Error>    Condition "!DirAccess::exists(fxr_dir)" is true. Returning: false
  <C++ Source>   modules/mono/editor/hostfxr_resolver.cpp:323 @ try_get_path_from_dotnet_root()
```

There is are similar issues:
https://github.com/godotengine/godot/issues/66353
https://github.com/godotengine/godot/issues/70510

### Steps to reproduce

I have done this but wont fix:

```
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod 777 dotnet-install.sh 
./dotnet-install.sh --channel 7.0

export PATH="$PATH:$HOME/.dotnet"
```

### Minimal reproduction project

N/A

**Comment by kepiz** [comment] 2023-09-15 08:19
when I run dotnet --info I get

```
~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.414
 Commit:    dc3b5c4341

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /snap/dotnet-sdk/220/sdk/6.0.414/

global.json file:
  Not found

Host:
  Version:      6.0.22
  Architecture: x64
  Commit:       4bb6dc195c

.NET SDKs installed:
  6.0.414 [/snap/dotnet-sdk/220/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [/snap/dotnet-sdk/220/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [/snap/dotnet-sdk/220/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

**Comment by kepiz** [comment] 2023-09-15 08:43
confirmed this is not happening on 
Godot Engine v3.5.2.stable.mono.official.170ba337a - https://godotengine.org

**Comment by raulsntos** [comment] 2023-09-15 10:15
Please keep in mind that the `dotnet-install.sh` script is not meant to be used to setup a development environment[^1], it's intended for CI scenarios.

If the standard hostfxr resolution fails, Godot will fall back to the location of the `dotnet` CLI (if it can find it in the PATH).

Due to the way the hostfxr resolution is implemented, if it fails to find hostfxr in the standard install locations it will print an error, even if it can still find it in the fallback location.

If hostfxr was found, everything should still work correctly and the printed error can be ignored. Can you confirm that everything still works as expected, despite printing the error? If so, this is a duplicate of #70510 and can be closed.

[^1]: Read the purpose section of the `dotnet-install` script documentation: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#purpose

**Comment by kepiz** [comment] 2023-09-15 10:35
Thank you , all work as expected

**Comment by YuriSizov** [comment] 2023-09-15 10:57
Closing as a duplicate then, per above comments.

**Closed by YuriSizov** 2023-09-15 10:57 UTC
Labels: bug, platform:linuxbsd, topic:dotnet

**Comment by kepiz** [comment] 2023-09-19 07:19
> Closing as a duplicate then, per above comments.

how do I remove the error being shown in the editor is there a way?
thank you

![image](https://github.com/godotengine/godot/assets/18174709/654fafaa-c47e-4f24-a726-975bbe438649)
