### ISSUE TITLE
Vulkan: MacBook Pro mid-2017 facing graphics issues

### ISSUE THREAD

**Issue by PancakesWasTaken** [godotengine/godot#45926] opened 2021-02-12 16:39 UTC
Godot version:
  Commit hash: #45903 

OS/device including version:
  Device: MacBook Pro mid-2017 with 8 GB of RAM and an i5-7267U CPU
  OS: macOS 10.15.7
  GPU: INTEL - Intel(R) Iris(TM) Plus Graphics 650
  Backend: Vulkan

Issue description:
  I built commit #45903 and then made the bin output into an executable and from there I made a simple scene with a cube 
mesh (with a StandardMaterial3D), plane mesh (with a StandardMaterial3D), and a spotlight. Now I'm getting these errors: 

  `Attempted to use an unused shader variant (shader is null)`
  `This render pipeline requires (0) bytes of push constant data, supplied: (16)`

**NOTE: Like similar issues, my meshes are unlit and are black.
Another NOTE: These errors repeat infinitely and is overloading RAM with some times it increasing to 80% use as well as the CPU as it is lagging my typing as my build is currently running.**

Steps to reproduce:
  1. Use an Intel-powered MacBook.
  2. Fetch a master version (I don't think it matters until this issue gets fixed.)
  3. Compile by following the directions of the Godot docs.
  4. Make the output executable then execute it directly from there or follow the .app packaging instructions. (Remember to have Vulkan installed in your system first!)
  5. Open the project included with this issue.

Minimal reproduction project:
  Project used: [VulkanGodotTest.zip](https://github.com/godotengine/godot/files/5973105/VulkanGodotTest.zip)

**Comment by PancakesWasTaken** [comment] 2021-02-12 16:47
Picture of the console just incase anyone needs it:

<img width="1279" alt="Screen Shot 2021-02-12 at 11 42 25 AM" src="https://user-images.githubusercontent.com/75938196/107796267-a687c580-6d27-11eb-9382-29fa780136a8.png">

**Comment by jsa4000** [comment] 2021-02-12 21:02
Hi, I think this is related iwith the issue I opened here https://github.com/godotengine/godot/issues/45661
If you try directional light it should work as espected, and your meshed must be lighted. However neither omnilight nor sportlight seems to be rendered from some reason.

**Comment by PancakesWasTaken** [comment] 2021-02-13 13:11
Hmm, I may try that later to see if it fixes anything.

**Comment by PancakesWasTaken** [comment] 2021-02-13 13:49
Ok so lighting is fixed but geometry is not working properly, it's like culling is inverted? Also, I almost crashed my build just by opening the output.

**Comment by jsa4000** [comment] 2021-02-16 08:11
> Ok so lighting is fixed but geometry is not working properly, it's like culling is inverted? Also, I almost crashed my build just by opening the output because the engine cannot resolve a shader issue (Apparently?).

What do you mean about the lighting being fixed? Are Sportlights and Omnilights working for you, or it just the directional light, like I commented.

I have found the break change where the issue started:

**[KO] -> 099dee35f4 Added GPU based cluster builder**
[OK] -> 7008e3c6ea Shader optimizations to reduce VGPR usage and increase occupancy

That commit has a lot of changes, hopefully the team will founf the issue soon

**Comment by PancakesWasTaken** [comment] 2021-02-16 13:30
Ok I built pull request #46072 and the problems seem to be fixed with the shader null thing but lights still don't work.

**Comment by bruvzg** [comment] 2021-02-16 14:25
On macOS 11.2.1 (AMD FirePro D300) with current masters of Godot (2a03886cbfadbb51e98d0238506d4a5e2be64ed2) and MoltenVK (https://github.com/KhronosGroup/MoltenVK/commit/4a0a5cd0b471c87f714c82b4f15b690f3731bc4a) I'm getting the same errors:
```
ERROR: Attempted to use an unused shader variant (shader is null),
   at: get_render_pipeline (./servers/rendering/renderer_rd/pipeline_cache_rd.h:71)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: draw_list_set_push_constant (drivers/vulkan/rendering_device_vulkan.cpp:6562)
ERROR: No render pipeline was set before attempting to draw.
   at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:6579)
```
But there are no shader compilation errors, seems like it's using the wrong shader variant. Setup of the shader variant causing `null` errors reach this code: https://github.com/godotengine/godot/blob/cb64f2d96ba25f516ecd6dfb3e80b7ddbb13971f/servers/rendering/renderer_rd/renderer_scene_render_forward.cpp#L294-L295 and is not initialized.

**Comment by PancakesWasTaken** [comment] 2021-02-20 12:17
Any updates on when will this be fixed?

**Comment by Calinou** [comment] 2021-02-20 14:58
@PancakesWasTaken Nobody knows of a definite fix yet, so this may take a while to be fixed. Also, keep in mind the `master` branch isn't production-ready.

**Comment by PancakesWasTaken** [comment] 2021-04-02 14:01
> Picture of the console just incase anyone needs it:
> 
> <img alt="Screen Shot 2021-02-12 at 11 42 25 AM" width="1279" src="https://user-images.githubusercontent.com/75938196/107796267-a687c580-6d27-11eb-9382-29fa780136a8.png">

---

So it appears that a build of bb90d3a will not emit the errors in the console picture that you should see quoted on the top of the comment. But it appears we now have a fragment shader compilation issue that involves the rendering server. I want to also note that the graphics are not affected in the test scene and look generally the same as the last builds even with the supposedly non-compiled fragment shader.

Here is a screenshot of the console:
<img width="1280" alt="Screen Shot 2021-04-02 at 9 50 07 AM" src="https://user-images.githubusercontent.com/75938196/113421351-ef0f4700-9398-11eb-8f78-844ff3a59e04.png">

**Comment by Calinou** [comment] 2021-12-10 15:07
@PancakesWasTaken Can you still reproduce this on a recent build of the `master` branch? You can download a nightly build [here](https://hugo.pro/projects/godot-builds/).

**Comment by Calinou** [comment] 2022-05-20 20:16
Duplicate of https://github.com/godotengine/godot/issues/51898.

**Closed by Calinou** 2022-05-20 20:16 UTC
Labels: bug, platform:macos, topic:rendering, topic:3d
