### ISSUE TITLE
orientation changes cause crash or other issues on iOS

### ISSUE THREAD

**Issue by FuzzyRhombus** [godotengine/godot#9295] opened 2017-06-20 21:00 UTC
**Operating system or device - Godot version:**
iPhone 5S, iOS 10.3.1, Godot v2.1.3

**Issue description:**
There seem to be multiple problems with orientation changes on iOS

1. If your project supports multiple orientations, when an orientation change occurs on iOS, it seems like there is a 50% or greater chance Godot will crash (see https://github.com/godotengine/godot/issues/7945 for related issue). From what I've observed, **"501 error"** will be printed to the console many times while the orientation change is occurring. The crash seems to occur when the orientation change should finish.

2. Additionally, I have a `TextureFrame` with a screen shader in a project that I am resizing when the viewport size changes. On iOS, this causes nothing to render on that `CanvasLayer`. Rotating back to the original orientation does not fix it. I am also calling this resizing function once at startup from `_ready` but that does not cause an issue. FWIW I am using the following project settings and calling `set_size_override` on the viewport for custom sizing through my `Camera2D`:
- orientation = "sensor"
- stretch_aspect = "ignore"
- stretch_mode = "2d"

3. "reverse_portrait" orientation mode does not seem to be supported regardless of the project settings or supported orientations in the Xcode project's .plist

I've tested this on many of the demo projects as well and the first and third issue are still prevalent

Probably doesn't need to be said, but setting a single explicit orientation does not cause any issues

**Steps to reproduce:**
Enable multiple orientations in the project settings and Xcode project. Run on an iOS device and rotate to different orientations

**Comment by alexzheng** [comment] 2017-10-11 10:38
Yes,really too many issues related to the orientation on iOS,but it seems all these issues are just ignored.Nobody take care of these issues.

**Comment by akien-mga** [comment] 2017-10-13 08:56
> Yes,really too many issues related to the orientation on iOS,but it seems all these issues are just ignored.Nobody take care of these issues.

You know the saying, "scratch your own itch"...

**Comment by groud** [comment] 2017-10-13 09:06
> Yes,really too many issues related to the orientation on iOS,but it seems all these issues are just ignored.Nobody take care of these issues.

Don't worry, you're not alone ;) :
![screenshot-2017-10-13 orientation changes cause crash or other issues on ios issue 9295 godotengine godot](https://user-images.githubusercontent.com/6093119/31538507-12c28394-b006-11e7-8b59-e566c1c02e0a.png)

**Comment by alexzheng** [comment] 2017-10-13 10:35
I know there are too many bugs to fix.
But for these that make every project impossible to publish should take higher priority.
I’m just come across Godot and not familiar with the internal,although I have spent days to track the termination and orientation issues,but without fortune.

**Comment by kubecz3k** [comment] 2018-04-03 11:46
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment] 2018-05-29 08:43
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.

**Closed by akien-mga** 2018-05-29 08:43 UTC
Labels: bug, platform:ios, topic:porting
