### ISSUE TITLE
RigidBody briefly appears at scene origin when instanced

### ISSUE THREAD

**Issue by Lefl1** [godotengine/godot#23340] opened 2018-10-28 01:47 UTC
**Godot version:**
970b581

**OS/device including version:**
Linux 4.17.19-1-MANJARO

**Issue description:**
When a scene with a RigidBody as a root node is instanced and the position of the body is changed,
it will appear at the scene origin (global (0, 0, 0)) for a very short amount of time.
This is a problem if there are other objects at this position.

**Steps to reproduce:**

- Create a scene with a RigidBody as a root node.
- Instance said scene.
- Set the position of the RigidBody
    *(Note that this will not actually place the body in the correct position, this is another bug, works fine  when done after adding node to the scene tree.)*
- Add the scene to the SceneTree.
- See that the RigidBody will appear for a brief moment at the scene origin.
    *(it will also interact, as seen in the reproduction project)*

**Minimal reproduction project:**
[godot-instancing-bug.zip](https://github.com/godotengine/godot/files/2522373/godot-instancing-bug.zip)

**Comment by bojidar-bg** [comment] 2018-10-28 15:44
Can confirm, happens on Bullet physics no matter what I tried (including setting a local transform instead of global, waiting for idle/physics frame, deferring the `add_child` call).
Changing to Godot physics immediately fixes the problem (though I had to add a shape to the body).
The body does not register collisions at 0,0,0, but children (an Area in the sample) do. Additionally, MeshInstance-s and similar will render briefly there.

CC @AndreaCatania.

**Comment by tagcup** [comment] 2018-10-28 20:54
Probably related to #22904

**Comment by samdze** [comment] 2018-12-27 15:09
Seems to happen with 2D physics too. Maybe related to #18554 and #18748.
This bug is giving me a lot of problems.

**Comment by avencherus** [comment] 2018-12-27 19:20
@samdze Yes, I think this is in 2D Physics as well.  I was experiencing something like that in work back in 2.1.5, and this probably explains it.  It seemed random to me and hadn't made the connection that it was moving to the world origin.  Since the geometry would shove it around while the game started.

I had tried using characters as RigidBody2D in Character mode, hoping to use certain functionality.  But one thing I struggled with was teleporting the character to the start position, especially at start up.  Sometimes it looked like sleeping worked, other times it would refuse to put the body to sleep.  I would move it with integration transforms, and turn off collision so it didn't report contacts or get stuck, since it almost always had to pass through some wall to get to the spawn location.

Have a real whacky start up algorithm that gives the body a second or so to resolve before fading in, and thankfully it worked.  Though sometimes the characters might have a slight drop to the floor when it reaches the time out.

I have not had much luck with making things with RigidBody2D, they've rather unstable in many ways.

**Comment by Dogpot** [comment] 2019-01-21 23:32
This issue seems to happen in 3.1 beta2 as well. Instancing a RigidBody object and setting its translation to some other location still results in the object generating a collision at its initial location.

**Comment by kubecz3k** [comment] 2019-01-24 17:00
I just wanted to open another issue about this, but I found the original one... Since I already have a gif that's presenting the issue I will attach it...
![instance_at_pos000](https://user-images.githubusercontent.com/6129594/51694645-8f22f600-2001-11e9-843d-db24a6245549.gif)

And reproduction:
[BodiesAlwaysInstancedAtPos000.zip](https://github.com/godotengine/godot/files/2792731/BodiesAlwaysInstancedAtPos000.zip)

**Comment by akien-mga** [comment] 2019-01-24 17:02
@samdze @avencherus Could you open another issue about 2D? This issue is about the 3D part which seems specific to Bullet (doesn't reproduce with GodotPhysics backend).

**Comment by samdze** [comment] 2019-01-24 23:08
There are the issues I mentioned above, #18554 and #18748. I think they might be related.
#18554 seems simpler to deal with.

**Closed** 2019-01-28 08:11 UTC
Labels: bug, confirmed, topic:physics

**Comment by avencherus** [comment] 2019-01-28 17:23
@akien-mga I'll look into the 2D one, next chance I get.

**Comment by avencherus** [comment] 2019-01-29 05:20
@akien-mga Unsuccessful at reproducing in 2D at the moment.  Perhaps it was fixed along the road?  If it still persists, I may be missing some condition.

Not sure where to post this to, because opening a non-issue would be more awkward.

Here is a test project if anyone more familiar with the conditions of the issue would like to try to expose it:  
[3.1 RigidBody2D.zip](https://github.com/godotengine/godot/files/2806166/3.1.RigidBody2D.zip)
