### ISSUE TITLE
move_and_slide jerks moved body on specific collision

### ISSUE THREAD

**Issue by DoctorAlpaca** [godotengine/godot#13095] opened 2017-11-20 14:07 UTC
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 3 89fc453

**Issue description:**
In the provided scene, the "player" is being moved downwards using move_and_slide. On collision with the rotating hexagon, the player is moved about 175 pixels to the left, without any apparent reason.

Of note, this only happens with the downside of the hexagon (which is why it starts rotated at 178°). This behavior is quite elusive, but reproducible enough (even with different timings and angles) to actually occur in a realistic environment.

**Link to minimal example project:**
[physics.zip](https://github.com/godotengine/godot/files/1487884/physics.zip)

**Comment by dherring** [comment] 2017-12-13 09:42
Very close to a solution.  Found a hacky workaround.

Set the following breakpoint to immediately jump to where this happens.
`b servers/physics_2d/space_2d_sw.cpp:498 if p_motion.y>1.7339`

The collider_velocity (soon to be floor_velocity) is set on line 812.
Here are the values that will cause the large jump.
```
body->get_angular_velocity() = -376.676941
rel_vec = {{x = 12.9893188, width = 12.9893188}, {y = -28.0261841, height = -28.0261841}}
```

Then I tool a walk through the collision solver.
The solver is called in "FREE BODY IF STUCK", "ATTEMPT MOTION", and eventually "it collided, let's get the rest info in unsafe advance".

Here was a (useful?) breakpoints.
`b servers/physics_2d/collision_solver_2d_sw.cpp:218

Also of note in space_2d_sw.cpp:33
`#define collision_solver sat_2d_calculate_penetration`


All that said, the problem is nowhere near the collision logic.
The large angular velocity comes from the initialization of the hexblock rotation angle.
When the initial angle is small, the initial velocity is small.
When the initial angle is large, so is the initial velocity.

If the two objects collide when the initial velocity is large, then the explosion happens.
After that first frame, the hexblock velocity is normal, and things are uneventful.

The documentation for KinematicBody2D says "When these bodies are moved manually, either from code or from an AnimationPlayer (with process mode set to fixed), the physics will automatically compute an estimate of their linear and angular velocity."

As a brute-force demo, add the following to rotate.gd, after setting the rotation
`Physics2DServer.body_set_state(self, Physics2DServer.BODY_STATE_ANGULAR_VELOCITY, 0)`
In this particular example, this has to be done the first 8 times _physics_process is called.

There has to be a better way of telling the physics server to reset or limit the velocity.

A quick web search found a few other people having unexplained movements after teleporting characters.  So I don't think this problem can be fixed by a simple initialization hack.

**Comment by Calinou** [comment] 2020-05-13 07:33
Can anyone still reproduce this on 3.2.1 or the `master` branch?

**Comment by tom-jk** [comment] 2020-07-09 11:57
3.2.2.stable, looks ok to me: https://youtu.be/eNZj9l7iseo

**Comment by Calinou** [comment] 2020-07-09 12:04
@tom-jk Thanks for testing this :slightly_smiling_face: Closing as resolved then.

**Closed by Calinou** 2020-07-09 12:04 UTC
Labels: bug, topic:physics
